New page: aria-describedby
mdn/content pull request #10090
Opened 2021-10-26 04:17 UTC by estelle

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-27 14:20 UTC, ericwbailey requested changes
Two big-picture things:

1. I'd like to take a second pass at the examples, more detail in the feedback comment.
2. I know you touch on this lightly, but I'd like to emphasize that `aria-describedby` content should only be a text string, and if there are underlying semantics they might not be announced.

2021-10-30 20:27 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
Maybe we avoid examples for now?

2021-11-01 22:18 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
i edited them and commented them out.

2021-11-01 22:20 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
should we just use the w3c example:
```html
<button aria-describedby="trash-desc">Move to trash</button>
...
<p id="trash-desc">Items in the trash will be permanently removed after 30 days.</p>
```

2021-11-01 22:21 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
i updated the examples we did have and commented them out... should we uncomment or delete? or go with trash example? or all 3?

2021-11-07 20:50 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
I think the trash example would work!

2021-11-09 21:29 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-describedby/index.md
> +```
done!

2021-11-13 19:00 UTC, ericwbailey approved these changes

2021-11-13 19:00 UTC, merged