New page: aria-details
mdn/content pull request #10130
Opened 2021-10-27 20:48 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-28 17:34 UTC, ericwbailey requested changes
There's some pretty large editorial changes that I'm proposing here. Happy to chat about it if you'd like, @estelle.

2021-10-29 19:03 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> + <i title="English pronunciation respelling">BEH-zee-ay</i>) is a mathematically
i wanted to show "semantics" forcing the use of `aria-details` over `aria-describedby`.

2021-10-29 19:04 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> +  <img alt="Animated Bézier curve" src="bezier.gif">
the goal was to show a link to a different page as part of details.

2021-10-29 19:09 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> +Unlike `aria-describedby`, elements referenced by `aria-details` are not used in accessible descriptions and are not stringified when presented to assistive technology users. If the associated conten
updated in a separate commit

2021-10-30 20:29 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> +  <img alt="Animated Bézier curve" src="bezier.gif">
Yes, but I think we should also be striving to have meaningful alt descriptions in code examples to model for anyone reading.

2021-10-30 20:31 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> + <i title="English pronunciation respelling">BEH-zee-ay</i>) is a mathematically
Yup, got that. This use of the `title` attribute is an antipattern, however.

2021-11-01 22:08 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> + <i title="English pronunciation respelling">BEH-zee-ay</i>) is a mathematically
i added an aria-description.

2021-11-01 22:09 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> +  <img alt="Animated Bézier curve" src="bezier.gif">
made a more detailed alt attr.

2021-11-07 20:42 UTC, ericwbailey requested changes

2021-11-07 20:42 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> + <i title="English pronunciation respelling" aria-description="English pronunciation">BEH-zee-ay</i>) is a mathematically
```suggestion
 <i aria-description="English pronunciation">BEH-zee-ay</i>) is a mathematically 
```

2021-11-07 20:42 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-details/index.md
> +  <img alt="Animated Bézier curve showing 4 control points" src="bezier.gif">
```suggestion
  <img alt="Animated Bézier curve showing 4 control points." src="bezier.gif">
```

2021-11-07 20:43 UTC, ericwbailey approved these changes

2021-11-07 20:44 UTC, merged