New page: aria-disabled
mdn/content pull request #10163
Opened 2021-10-29 02:50 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-29 13:45 UTC, LorenzNickel requested changes

2021-10-30 20:44 UTC, ericwbailey requested changes
Nice stuff! A few things for you to take a look at.

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +You generally want users to fill out all the required fields before submitting a form. One way to ensure all required fields are complete is to disable the submit button; but you still want that subm
```suggestion
You generally want users to fill out all the required fields before submitting a form. One way to ensure all required fields are complete is to disable the submit button. However, you still want that submit button to be perceivable to <strong>all</strong> users. That is where the `aria-disabled` attribute comes in.
```

Trying to lower the reading level here a tad, as well as avoiding hardcoded all caps.

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +The `aria-disabled` attribute, when set to `true`, indicates to assistive technologies that the element upon which it is set is disabled. It tells your user the element is not editable or otherwise o
```suggestion
The `aria-disabled` attribute, when set to `true`, indicates to assistive technologies that the element upon which it is set is disabled. This declaration tells your user the element is not editable or otherwise operable without making the element imperceivable.
```

Clarifying what "it" is.

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +There are several elements you may want to disable, but still want the user to know they exist. Some examples include irrelevant options in a radio group, the header button element associated with no
```suggestion
There are several elements you may want to disable, but still want the user to know they exist. Some examples include:

- Irrelevant options in a radio group, 
- The header button element associated with non-collapsible accordion panel, 
- A button when the action associated with the button is unavailable, 
- The icon for the currently visible slide in a slideshow slide picker, and 
- Items in a menu that are not currently selectable. 

In each of these cases, you want the user to know the element is there even though the functionality of that control is removed or "disabled".
```

Breaking this out into a list to lower the reading level a bit. Good examples, though!

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +Note that the state of being disabled applies to the element with `aria-disabled` and all of its focusable descendants.
Should we use a note component for this?

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +> **Note:** Do not use CSS's [`pointer-events: none;`](/en-US/docs/Web/CSS/pointer-events) to make an element non clickable. While it prevents mouse clicks, the element will still be 'clickable' via
```suggestion
> **Note:** If you are using CSS's [`pointer-events: none;`](/en-US/docs/Web/CSS/pointer-events) to make an element non-clickable, make sure you disable interactivity with JavaScript as well. `pointer-events: none;` prevents mouse clicks, but does not prevent the element from being activated via the keyboard.
```

I rephrased this a bit so it couldn't be construed as avoiding ``pointer-events: none;`` all together. I think use of this declaration can be helpful, but to your larger point, should be part of a larger, more comprehensive solution.

2021-10-30 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +When toggling from `aria-disabled="true"` to `"false"`, use JavaScript to 1) toggle the value to `false`, 2) enable the element, and 3) let the user know the control is now enabled. If you used CSS t
```suggestion
When toggling from `aria-disabled="true"` to `"false"`, use JavaScript to: 

1. Toggle the value to `false`, 
2. Enable the element, and 
3. Let the user know the control is now enabled. 

If you used just CSS to style the disabled state using an attribute selector, the selector will no longer match and the disabled styling will no longer be in effect.
```

2021-11-01 21:24 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-disabled/index.md
> +Note that the state of being disabled applies to the element with `aria-disabled` and all of its focusable descendants.
done! added a brief note above then did a shorter pull out note here.

2021-11-02 23:35 UTC, ericwbailey approved these changes

2021-11-02 23:35 UTC, merged