menus.OnClickedData.srcUrl returns <img src>
mdn/content pull request #10214
Opened 2021-11-01 18:08 UTC by rebloor

#### Summary

Addresses the changes made in the return value of `menus.OnClickedData.srcUrl` including:

*updated release notes
* clarification  of `menus.OnClickedData.srcUrl`

Addition of supporting note in compatibility data to follow.

#### Supporting details

Addresses changes made in  [Bug 1659155](https://bugzilla.mozilla.org/show_bug.cgi?id=1659155). 

#### Metadata

This PR…

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-11-02 16:53 UTC, Rob--W requested changes
The focus of this PR is incorrect; it should not be about emphasizing that it's `<img src>`, but stating that it's the `src` URL of an element (i.e. the initially requested URL, even if redirected). It's fine to list examples (as I did below), but the main point is to emphasize that the initial URL is used even if redirected.

2021-11-02 16:53 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/onclickdata/index.md
> +  - : `string`. The `<img src>` value for the clicked element's image or, where the element has no image, the background image, otherwise not returned.
The original documentation was more factual than the current one, because the current one makes it seem like the property is only supported on `<img>` elements.

This is not restricted to images. It is also on `<video>`, `<audio>`, `<img>`, `<input type="image">`, (SVG) `<image href>` - example: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image#svg). Maybe others, but this is what I could find after a quick look.

(And if an image is loaded, also on `<object>`, `<embed>`)

I double-checked just now, and apparently the menu item is not shown on background-image, so let's remove that.

2021-11-03 16:06 UTC, Rob--W approved these changes
r+ but clarify the difference and add bug reference.

2021-11-03 17:50 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/94/index.md
> +- When a context menu is activated, {{WebExtAPIRef('menus.OnClickData','menus.OnClickData.srcUrl')}} returns the raw value of the `src`  attribute of the clicked element.
@Rob--W As the bug is flagged as a security issue and not generally readable do we want to include a reference in the main documentation?

2021-11-03 18:17 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/94/index.md
> +- When a context menu is activated, {{WebExtAPIRef('menus.OnClickData','menus.OnClickData.srcUrl')}} returns the raw value of the `src`  attribute of the clicked element.
The bug will eventually be opened.

2021-11-04 15:13 UTC, merged