Added overrideContentColorScheme to browserSettings
mdn/content pull request #10211
Opened 2021-11-01 15:53 UTC by rebloor

#### Summary

Adds details for the addition of `overrideContentColorScheme` to `browserSettings` including:

- developer release notes
- addition to the `browserSettings` page
- new `overrideContentColorScheme` page

#### Motivation
To address the documentation needs of [Bug 1733461](https://bugzilla.mozilla.org/show_bug.cgi?id=1733461) 

#### Related issues
Fixes [#10146](https://github.com/mdn/content/issues/10146)

#### Metadata

This PR…
- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-01 16:17 UTC, Cimbali requested changes

2021-11-01 16:17 UTC, Cimbali commented on files/en-us/mozilla/add-ons/webextensions/api/browsersettings/overridecontentcolorscheme/index.md
> +- "system": Applies a light or dark theme to webpages based on the browser's theme.
Bug [1529323](https://bugzilla.mozilla.org/show_bug.cgi?id=1529323) also added the `"browser"` value

2021-11-01 17:25 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/browsersettings/overridecontentcolorscheme/index.md
> +- "system": Applies a light or dark theme to webpages based on the browser's theme.
Thanks for the advice @Cimbali, I have addressed in the latest commit

2021-11-04 15:38 UTC, mixedpuppy approved these changes

2021-11-04 17:44 UTC, merged