Adds glossary page for clickjacking
mdn/content pull request #10226
Opened 2021-11-02 09:04 UTC by KanishkTagade

This PR adds a page for the Clickjacking entry in Glossary. 

As requested by the moderator, made all changes within one branch, mentioned here: https://github.com/mdn/content/pull/8577

2021-11-02 21:16 UTC, estelle requested changes
Clickjacking should be capitalized only at start of sentences. Glossary needs to be in markdown rather than HTML. Nice addition to the glossary!

2021-11-02 21:16 UTC, estelle commented on files/en-us/learn/server-side/apache_configuration_htaccess/index.md
> +    - The `frame-ancestors`directive helps avoid [Clickjacking](/en-us/Glossary/Clickjacking) attacks and is similar to the `X-Frame-Options` header
Please make clickjacking lowercase in all cases where it should be lowercase in the rest of this PR. Should it be quoted here?

2021-11-02 21:16 UTC, estelle commented on files/en-us/learn/server-side/django/web_application_security/index.md
> +  - : In this attack a malicious user hijacks clicks meant for a visible top level site and routes them to a hidden page beneath. This technique might be used, for example, to display a legitimate ba
the glossary doesn't really talk about clickjacking "protection". A few options: only link the clickjacking word. Link clickjacking to glossary and protection to the django article, or revert this change.

2021-11-02 21:16 UTC, estelle commented on files/en-us/glossary/clickjacking/index.md
> +<p>Clickjacking is an interface-based attack that tricks website users into unwarily clicking on malicious links. In clickjacking, the attackers embed their malicious links into buttons or legitimate
Unwarily is used correctly, but I think "unwittingly" may be easier to understand ... or something more understandable even.

> In this attack, a malicious user hijacks clicks meant for a visible top-level site and routes them to a hidden page beneath. This technique might be used, for example, to display a legitimate bank site but capture the login credentials into an invisible {{htmlelement("iframe")}} controlled by the attacker. Clickjacking could also be used to get the user to click a button on a visible site, but in doing so actually unwittingly click a completely different button. As a defense, your site can prevent itself from being embedded in an iframe in another site by setting the appropriate HTTP headers.

2021-11-02 21:16 UTC, estelle commented on files/en-us/learn/server-side/first_steps/website_security/index.md
> +- [Clickjacking](/en-us/Glossary/Clickjacking). In this attack, a malicious user hijacks clicks meant for a visible top-level site and routes them to a hidden page beneath. This technique might be us
Nice definition! Uppercase ok here

2021-11-08 18:53 UTC, KanishkTagade reviewed
Hello @estelle, Thank you very much for your detailed review and suggestions. I have checked and corrected the suggested changes and marked them as "Viewed" here. 

I am not sure if I can resolve the conversations here (I purposely left them for another reviewer). Thank you again.
 
I am excited about my first MDN glossary entry. 😃

2021-11-10 10:37 UTC, marcelozarate commented on files/en-us/glossary/clickjacking/index.md
> +<p>Clickjacking is an interface-based attack that tricks website users into unwarily clicking on malicious links. In clickjacking, the attackers embed their malicious links into buttons or legitimate
unintentionally maybe?

2021-12-02 17:42 UTC, KanishkTagade commented
Hello @estelle and @marcelozarate . Apologies for following up on this after a long time. Would you please guide me on the next steps required for adding "Clickjacking" entry to the MDN Glossary? Thank you :)

2021-12-21 02:03 UTC, estelle commented on files/en-us/learn/server-side/django/introduction/index.md
> +    Django enables protection against many vulnerabilities by default, including SQL injection, cross-site scripting, cross-site request forgery and [Clickjacking](/en-us/Glossary/Clickjacking) (see
```suggestion
    Django enables protection against many vulnerabilities by default, including SQL injection, cross-site scripting, cross-site request forgery and [clickjacking](/en-us/Glossary/Clickjacking) (see [Website security](/en-US/docs/Learn/Server-side/First_steps/Website_security) for more details of such attacks).
```

2021-12-21 02:03 UTC, estelle commented on files/en-us/learn/server-side/django/web_application_security/index.md
> +  - : In this attack a malicious user hijacks clicks meant for a visible top level site and routes them to a hidden page beneath. This technique might be used, for example, to display a legitimate ba
```suggestion
  - : In this attack a malicious user hijacks clicks meant for a visible top level site and routes them to a hidden page beneath. This technique might be used, for example, to display a legitimate bank site but capture the login credentials in an invisible [`<iframe>`](/en-US/docs/Web/HTML/Element/iframe "The HTML Inline Frame Element (<iframe>) represents a nested browsing context, effectively embedding another HTML page into the current page. In HTML 4.01, a document may contain a head and a body or a head and a frameset, but not both a body and a frameset. However, an <iframe> can be used within a normal document body. Each browsing context has its own session history and active document. The browsing context that contains the embedded content is called the parent browsing context. The top-level browsing context (which has no parent) is typically the browser window.") controlled by the attacker. Django contains [clickjacking](/en-us/Glossary/Clickjacking) protection in the form of the [`X-Frame-Options middleware`](https://docs.djangoproject.com/en/3.1/ref/middleware/#django.middleware.clickjacking.XFrameOptionsMiddleware "django.middleware.clickjacking.XFrameOptionsMiddleware") which, in a supporting browser, can prevent a site from being rendered inside a frame.
```

2021-12-21 02:03 UTC, estelle commented on files/en-us/learn/server-side/first_steps/website_security/index.md
> +- [Clickjacking](/en-us/Glossary/Clickjacking). In this attack, a malicious user hijacks clicks meant for a visible top-level site and routes them to a hidden page beneath. This technique might be us
```suggestion
- [Clickjacking](/en-us/Glossary/Clickjacking). In this attack, a malicious user hijacks clicks meant for a visible top-level site and routes them to a hidden page beneath. This technique might be used, for example, to display a legitimate bank site but capture the login credentials into an invisible {{htmlelement("iframe")}} controlled by the attacker. Clickjacking could also be used to get the user to click a button on a visible site, but in doing so actually unwittingly click a completely different button. As a defense, your site can prevent itself from being embedded in an iframe in another site by setting the appropriate HTTP headers.
```

2021-12-21 02:03 UTC, estelle commented on files/en-us/web/security/index.md
> +In [Clickjacking](/en-us/Glossary/Clickjacking), a user is fooled into clicking on a UI element that performs some action other than what the user expects.
```suggestion
In [clickjacking](/en-us/Glossary/Clickjacking), a user is fooled into clicking on a UI element that performs some action other than what the user expects.
```

2021-12-21 02:03 UTC, estelle commented on files/en-us/web/security/index.md
> +  - : The **`X-Frame-Options`** [HTTP](/en-US/docs/Web/HTTP) response header can be used to indicate whether or not a browser should be allowed to render a page in a [`<frame>`](/en-US/docs/Web/HTML/
```suggestion
  - : The **`X-Frame-Options`** [HTTP](/en-US/docs/Web/HTTP) response header can be used to indicate whether or not a browser should be allowed to render a page in a [`<frame>`](/en-US/docs/Web/HTML/Element/frame "<frame> is an HTML element which defines a particular area in which another HTML document can be displayed. A frame should be used within a <frameset>."), [`<iframe>`](/en-US/docs/Web/HTML/Element/iframe "The HTML Inline Frame element (<iframe>) represents a nested browsing context, embedding another HTML page into the current one."), [`<embed>`](/en-US/docs/Web/HTML/Element/embed "The HTML <embed> element embeds external content at the specified point in the document. This content is provided by an external application or other source of interactive content such as a browser plug-in.") or [`<object>`](/en-US/docs/Web/HTML/Element/object "The HTML <object> element represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a plugin."). Sites can use this to avoid [clickjacking](/en-us/Glossary/Clickjacking) attacks, by ensuring that their content is not embedded into other sites.
```

2021-12-21 02:03 UTC, estelle commented on files/en-us/web/security/securing_your_site/index.md
> +  - : The `X-Frame-Options:` [HTTP](/en/HTTP) response header can be used to indicate whether or not a browser should be allowed to render a page in a {{ HTMLElement("frame") }}. Sites can use this t
```suggestion
  - : The `X-Frame-Options:` [HTTP](/en/HTTP) response header can be used to indicate whether or not a browser should be allowed to render a page in a {{ HTMLElement("frame") }}. Sites can use this to avoid [clickjacking](/en-us/Glossary/Clickjacking) attacks, by ensuring that their content is not embedded into other sites.
```

2021-12-21 02:17 UTC, estelle approved these changes

2021-12-21 02:17 UTC, merged