[DOM Reference] Update Node interface and its children
mdn/content pull request #10232
Opened 2021-11-02 13:09 UTC by teoli2003

This is part of #9740.

`Node`  is one of the key interfaces to update (`Document` and `Element` are the two other ones)

- The interface page, as well as every 30 properties and methods should have the most modern structure.
-  All have at least one example. I added quite a few live examples too.
-  All pages have been made 100% browser independent and refer only to the modern spec. There is only one non-standard method, mentioning DOM Level 2, as "2.0" is the value of a parameter… It will go away when we stop keeping stuff about IE11. (It is gone in Edge).
- `Node.textContent` has some paragraphs about the difference between this property and `Element.innerText` and `Element.innerHTML`. The plan is to remove these and have a special guide page about it. This will happen in phase 2. Meanwhile, I kept them to be sure we don't lose them.
- AFAIK, I have documented every DOM exception that can be raised.
- Tags have been cleaned.
- There shouldn't be any flaws left, except three non-written pages in other interfaces (they will be documented when I get to these interfaces).
- All properties/methods mentioned for `Node` in the specification are documented.
- I removed en-US/docs/XML/xml:base as xml:base is no more supported by any browser for a long time.
-

2021-11-05 11:03 UTC, Rumyra requested changes

2021-11-05 11:04 UTC, Rumyra commented
Looks really good @teoli2003 - just a couple of tiny nits :)

2021-11-05 13:41 UTC, teoli2003 commented
Thanks. Typo fixed (the console one was weird…)

2021-11-08 14:58 UTC, Rumyra approved these changes

2021-11-08 14:59 UTC, merged

2021-11-10 18:58 UTC, paulirish commented
I've always gotten a lot of value out of the previous example usage of insertBefore that called out the `parentNode`.

![image](https://user-images.githubusercontent.com/39191/141175898-4420fd30-e74c-4eff-9de6-c82a853d7a13.png)

Would you be open to restoring that?