Added a warning about XSS protection causing XSS
mdn/content pull request #10243
Opened 2021-11-02 18:04 UTC by dd-pardal

#### Summary
Added a warning about XSS protection causing XSS vulnerabilities and a link to a video explaining how Chrome's XSS auditor can be exploited.

#### Motivation
Some readers may not be aware that not setting the `X-XSS-Protection` to `0` might make their websites vulnerable to XSS.

#### Supporting details
<https://hackademix.net/2009/11/21/ies-xss-filter-creates-xss-vulnerabilities/>
<https://www.youtube.com/watch?v=8GwVBpTgR2c>

#### Related issues
None.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-08 15:09 UTC, Elchi3 commented
Thanks for your PR!
 I'm happy to add a warning here but the warning text is quite vague. Vulnerable in "some cases" and "some developers chose to set the header to 0". What are those cases? "**some** developers"? I haven't watched the video and we usually don't link much to video content. It would be great if you could elaborate this a bit more for those who aren't security researchers. The warning leaves me a bit puzzled whether or not to set the header now...

2021-11-10 20:56 UTC, dd-pardal commented
I must admit it was vague.

> What are those cases?

Example:

```html
<script>var productionMode = true;</script>
<!-- [...] -->
<script>
  if (!window.productionMode) {
    // Some vulnerable debug code
  }
</script>
```

This code would be 100% safe if XSS protection wasn't a thing. However, if the search query is `?something=%3Cscript%3Evar%20productionMode%20%3D%20true%3B%3C%2Fscript%3E`, the browser might ignore `<script>var productionMode = true;</script>`, causing `window.productionMode` to be evaluated to `undefined` and executing the unsafe debug code. This was explained at the end of the video, hence why I included it. Please note that I haven't tested it in a modern browser, so perhaps this doesn't happen anymore.

> "**some** developers"?

Most (if not all) Google services, GitHub, Twitter and Facebook all set the header to `0`. Discord sets it to `1; mode=block`. Both solutions prevent vulnerabilities like the one I described above; the former would make the browser run all scripts and the latter would prevent the page from being processed at all.

Perhaps I should include this information in the page.

2021-11-12 13:29 UTC, Elchi3 commented
> Should I include this information in the page?

Yes! And thanks so much for your explanations, I think I understand this better now.

2021-11-20 21:51 UTC, BIOSTYMA reviewed
@Elchi3

2021-11-22 10:27 UTC, Elchi3 requested changes
Requesting changes given @dd-pardal still wants to add a bit more context here.

2021-11-26 21:30 UTC, dd-pardal commented
Sorry for taking so long. I forgot about this PR... 😅 I've just added an example of a vulnerability caused by XSS filtering to the document.

2021-11-29 11:26 UTC, Elchi3 approved these changes
Thanks for taking the time to come back to this! 
I'm not a security expert but it reads good to me.

2021-11-29 11:26 UTC, merged