ARIA Roles: minor edit: Slug text case
mdn/content pull request #10252
Opened 2021-11-02 23:29 UTC by estelle

Text case in the slugs for roles were a little all over the place. This fixes the ones that weren't capitalized.
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2021-11-03 01:51 UTC, wbamberg requested changes
Thanks Estelle!

I think these should be like "Web/Accessibility/ARIA/Roles/rolename_role", since `rolename` is an identifier with that case. This matches what we do in other places on MDN like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice or https://developer.mozilla.org/en-US/docs/Web/API/fetch.

2021-11-03 01:51 UTC, wbamberg commented on files/en-us/web/accessibility/aria/roles/button_role/index.html
> +slug: Web/Accessibility/ARIA/Roles/Button_role
I think in cases like this where the page is for an thing called `button` it would be better to keep the case of the thing. Similarly in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice we don't have "Slice" in the slug.

2021-11-04 04:03 UTC, wbamberg commented on files/en-us/web/accessibility/aria/roles/main_role/index.html
> +slug: Web/Accessibility/ARIA/Roles/main_role
I don;t know why there's an MD and an HTML version of this page. Should we delete the HTML version?

2021-11-04 04:07 UTC, wbamberg reviewed
Looks much better, but I had a couple of questions.

2021-11-04 04:07 UTC, wbamberg commented on files/en-us/web/accessibility/aria/roles/role_img/index.html
> +slug: Web/Accessibility/ARIA/Roles/role_Img
should this be img_role?

2021-11-04 16:04 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/main_role/index.html
> +slug: Web/Accessibility/ARIA/Roles/main_role
yes. Several HTML pages came back in. not sure how. Having HTML pages should not hold up the PR. The slugs still need to be fixed

2021-11-04 16:06 UTC, estelle commented
i have another PR in draft form dealing with Roles. Please don't delete the HTML pages or rename files in this one. Doing so will create a huge merge conflict with the next PR. As long as there are no "slug" issues, please approve.

2021-11-04 17:53 UTC, wbamberg approved these changes

2021-11-04 17:53 UTC, merged