New Page: aria-haspopup
mdn/content pull request #10250
Opened 2021-11-02 22:28 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-02 23:38 UTC, estelle commented
my local branch on this is borked, so hopefully this is mergeable ;)

2021-11-06 21:42 UTC, ericwbailey requested changes

2021-11-06 21:42 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-haspopup/index.md
> +
```suggestion
In ARIA, interactive menus, listboxes, trees, grids, and dialogs that appear on top of other content when triggered to appear are considered "popups". These popups are triggered by one or more interactive elements on the page. The availability and type of popup the interactive element will trigger should be identified with the `aria-haspopup` state.
 
```

2021-11-06 21:42 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-haspopup/index.md
> +A [`tooltip`](/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role), being not interactive, is not considered to be a popup in this context.
```suggestion
A [`tooltip`](/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) is not considered to be a popup in this context, as is not interactive.
```

2021-11-06 21:42 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-haspopup/index.md
> +When creating a [`menubar`](/en-US/docs/Web/Accessibility/ARIA/Roles/Menubar_role), a parent [`menuitem`](/en-US/docs/Web/Accessibility/ARIA/Roles/Menuitem_role) should have `aria-haspopup="menu"` (o
```suggestion
When creating a [`menubar`](/en-US/docs/Web/Accessibility/ARIA/Roles/Menubar_role), a parent [`menuitem`](/en-US/docs/Web/Accessibility/ARIA/Roles/Menuitem_role) should have `aria-haspopup="menu"` (or `true`) set. Any button that open a menu should have a role of [`button`](/en-US/docs/Web/Accessibility/ARIA/Roles/Button_role) or, preferably, be a {{HTMLElement('button')}}, and also have `aria-haspopup="menu"` (or `true`) set. [`Tab`](/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_role) elements with popup menus should also have `aria-haspopup="menu"` set. Note that `menubar`s should not be used to create website navigation.
```

2021-11-06 21:43 UTC, ericwbailey approved these changes

2021-11-06 21:44 UTC, merged