New page: aria-hidden
mdn/content pull request #10270
Opened 2021-11-03 17:13 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-03 20:27 UTC, LorenzNickel requested changes

2021-11-03 20:27 UTC, LorenzNickel commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +- CSS {{CSSXref('visibility'}} property
```suggestion
- CSS {{CSSXref('display')}} property
- CSS {{CSSXref('visibility')}} property
```

2021-11-06 22:05 UTC, ericwbailey requested changes
A couple of questions about the `hidden` attribute and modal behavior.

2021-11-06 22:05 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +> **Note:** Consider all disabilities when hiding visibly rendered content from assistive technologies. Not all users of assistive technology are visually impaired. If visible content doesn't match t
💯

2021-11-06 22:05 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +- `role="presentation"` and `role="none"` will remove the semantic meaning of an element while still exposing it and its content to assistive technology.
Nice!

2021-11-06 22:05 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +When working with dialogs, use the [`aria-modal`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) attribute rather than `aria-hidden` to inform assistive technologies that content outside a
I'm confused by this. Are we trying to communicate that non-dialog content will need to be made non-interactive?

2021-11-06 22:05 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +We have a button with a Font Awesome icon. We hide the icon from assistive technologies with `aria-hidden="true"` as exposing the icon to assistive technologies could lead to redundancy or, if the ic
```suggestion
We have a button with [a Font Awesome icon](https://fontawesome.com/). We hide the icon from assistive technologies with `aria-hidden="true"`, as exposing the icon to assistive technologies could lead to redundancy or, if the icon doesn't have the same content as the visible text, confusion. 
```

Linking to Font Awesome for those who may be unfamiliar.

2021-11-09 19:19 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +When working with dialogs, use the [`aria-modal`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) attribute rather than `aria-hidden` to inform assistive technologies that content outside a
Made it more clear: "When working with modal dialog popups, ...."

2021-11-09 19:25 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +- The element or the element's ancestor is hidden with [`visibility: hidden`](/en-US/docs/Web/CSS/visibility)
added a sentence earlier "hides content from assistive technology but doesn't visually hide anything"

and sentence after "Visually hiding elements with `display` or `visibility` hides content from the screen and from assistive technologies."

2021-11-13 19:10 UTC, ericwbailey requested changes
One last thing!

2021-11-13 19:10 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-hidden/index.md
> +When working with modal dialog popups, use the [`aria-modal`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) attribute rather than `aria-hidden` to inform assistive technologies that conte
```suggestion
```

I'd like to remove this section, as a modal will need `aria-modal` to help communicate the presence of a modal, but also requires a lot more to truly work. I'm thinking the steps to discover and remove the non-modal content from both regular screen reader navigation methods and the virtual cursor, and how documenting them here would be way out of scope. 

I worry that keeping this here might communicate that applying only `aria-modal` will be sufficient.

2021-11-21 19:40 UTC, ericwbailey approved these changes

2021-11-21 19:40 UTC, merged