Add glossary entry for UUID
mdn/content pull request #10307
Opened 2021-11-05 04:17 UTC by hamishwillee

Commonly we link to wikipedia, which is a relatively poor entry. I've created an entry and linked to it from some places - in particular Crypto.randomUUID() following discussion here: https://github.com/mdn/content/pull/10198#discussion_r740149450

Note I didn't link from the millions of BluetoothUUID instances. There are so many, and perhaps it has a special meaning we should capture in the glossary too.

2021-11-05 04:53 UTC, wbamberg commented
Thanks! I do agree it's useful to have our own glossary entry here. 

But I think this glossary entry could be more precise. I'm not sure whether "key length" in this item means the length of the identifier or the length of some other key, but if it's the length of the identifier I don't think that's really true. It is as far as I'm aware (and the Wikipedia entry says the same thing) part of the definition of a UUID that it's a 128-bit value whose canonical representation is a 36-character string in the format `123e4567-e89b-12d3-a456-426614174000`. (Also, calling this a "36 byte value" is misleading since it might make someone think it gets you 288 bits of entropy, but you don't, it's still a 128-bit value.)

The standard for it is https://www.rfc-editor.org/rfc/rfc4122, and I'd expect anywhere that uses the term "UUID" to refer to that standard for the definition.

There are differences in how the thing is be generated, but the size and format should be common across those variations.

2021-11-05 13:03 UTC, ddbeck requested changes, later dismissed
I like Will's suggestions. A couple of bonus style points in line comments.

2021-11-05 13:03 UTC, ddbeck commented on files/en-us/glossary/uuid/index.md
> +In theory these ids may not be globally unique, but with large enough identifiers the probability of duplicate ids is vanishingly small.
Consistency for "ID"

```suggestion
In theory these IDs may not be globally unique, but with large enough identifiers the probability of duplicates is vanishingly small.
```

2021-11-05 13:03 UTC, ddbeck commented on files/en-us/glossary/uuid/index.md
> +Many different UUID/GUID schemes have been defined, using different key lengths and mechanisms to reduce duplicate identifiers.
Seems like GUID is rarely used on MDN. Let's pick one term and stick with it.

```suggestion
Many different UUID schemes have been defined, using different key lengths and mechanisms to reduce duplicate identifiers.
```

2021-11-05 15:30 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/messagesender/index.md
> +    Note that in Firefox, before version 54, this value was the extension's internal ID (that is, the {{Glossary("UUID")}} that appears in the extension's URL).
I would be tempted to remove this reference entirely, Firefox 54 was released in June 2017 and ESR support stopped September 2018, so this historic information seems a little benefit.

2021-11-05 15:38 UTC, rebloor commented on files/en-us/glossary/uuid/index.md
> +A **Universally Unique Identifier** (**UUID**) or **Globally Unique Identifier** (**GUID**) is a label that can be used to uniquely identify a particular resource among all other resources of that ty
```suggestion
A **Universally Unique Identifier** (**UUID**) or **Globally Unique Identifier** (**GUID**) is a label used to uniquely identify a resource among all other resources of that type.
```
I wonder if this can be simplified, given that I'm not really aware of a UUID being used for anything other than uniquely identifying a resource.

2021-11-08 01:42 UTC, hamishwillee commented
Thanks all  - suggestions integrated. 

@wbamberg Ah. Over the years I've seen the term UUID overloaded to mean nothing more than you would infer from the name "an identifier that can be treated globally unique". 

I've taken another shot at this using your words from above (which I like). IF this is not up to scratch, I'd be happy for you to edit however you like.

2021-11-09 15:12 UTC, rebloor commented on files/en-us/glossary/uuid/index.md
> +Computer systems generate UUIDs locally using very large random numbers, possibly seeded with timestamp or other information.
`, possibly seeded with timestamp or other information` doesn't seem to add any useful information, it just says "seeded with something". Remove?

2021-11-09 15:20 UTC, rebloor approved these changes

2021-11-09 15:20 UTC, rebloor commented on files/en-us/glossary/uuid/index.md
> +There are a number of versions that differ slightly in the way they are calculated; for example, the inclusion of temporal information.
For clarity, should this be included with the earlier explanation "Computer systems generate UUIDs locally using very large random numbers, sometimes in combination with other details, such as temporal information."

2021-11-09 21:33 UTC, hamishwillee commented on files/en-us/glossary/uuid/index.md
> +Computer systems generate UUIDs locally using very large random numbers, possibly seeded with timestamp or other information.
```suggestion
Computer systems generate UUIDs locally using very large random numbers.
```
Thanks @rebloor . I was going to say "no, this is useful because the fact that it may be seeded with different things is the reason for the different versions of UUID, and the timestamp is one important seeding mechanism as it reduces the chance of clashes at a particular time. 

But I think this is kind of captured lower down, so certainly no harm not to say it here.

2021-11-09 21:37 UTC, hamishwillee commented
I'm merging this following integration of @rebloor last comments. Anyone who would like to iterate is welcome to do so :-). Thanks for the reviews all!

2021-11-09 21:38 UTC, merged