Update index.md
mdn/content pull request #10313
Opened 2021-11-05 10:44 UTC by tristangraaff

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-05 19:51 UTC, estelle requested changes

2021-11-05 19:51 UTC, estelle commented on files/en-us/web/css/_doublecolon_first-line/index.md
> +The **`::first-line`** [CSS](/en-US/docs/Web/CSS) [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) applies styles to the first line of a [block-level element](/en-US/docs/Web/CSS/Visual_formatti
Good feedback. The first sentences or paragraphs of MDN documents are the summary of the property. This content is displayed in search results, browser developer tools, and visual studio code. While this is good thing to point out as a note, it doesn't need to appear in dev tools. Can you add it as a sentence or note after the example:

> The `::first-line` pseudo-element impact the first line of content of block-like containers such as elements with `display` of `block`, `inline-block`, `table-caption`, and `table-cell` and has no impact when the first child of the element, which would be the first part of the first line, is an inline block level element such as inline-tables. 

In terms of images, the first-line is bold when an image is the first content (see https://codepen.io/estelle/pen/bGrvNWz)

2021-11-22 10:29 UTC, Elchi3 commented
@tristangraaff are you planning to come back to this PR?

2022-02-08 03:48 UTC, closed without merging

2022-02-08 03:49 UTC, hamishwillee commented
The core information from this PR was integrated in#12806. Thanks @ddbeck and @tristangraaff (and Estelle)