Added the examples to an example table
mdn/content pull request #10332
Opened 2021-11-06 15:33 UTC by Biki-das

fixes #10055 

i am kinda confused with the introductory lines @rebloor if you could elaborate i can further push it , rest hope the example table is fine , ping me up anytime for anything

2021-11-07 06:38 UTC, Biki-das commented
@rebloor please review

2021-11-07 22:01 UTC, rebloor requested changes
@Biki-das thanks for your help, please let me know if you need any further explanation

2021-11-08 08:11 UTC, Biki-das commented
@rebloor tried my best to do as you said check and if you find errors and something to change ping me up!

2021-11-09 15:50 UTC, rebloor requested changes
Thanks, @Biki-das we are getting there, I've left a few comments

2021-11-09 15:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +
An introduction here would be nice, something such as "This example shows how to set a search provider."

2021-11-09 15:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +"chrome_settings_overrides": {
Please add the code indenting

2021-11-09 15:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +"homepage": "https://developer.mozilla.org/"
Please add the code indenting

2021-11-11 14:44 UTC, Biki-das commented
@rebloor  done with the requested changes

2021-11-11 17:45 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +"homepage": "https://developer.mozilla.org/"
``` suggestion
  "homepage": "https://developer.mozilla.org/"
```

2021-11-11 17:54 UTC, rebloor requested changes
@Biki-das  I've added some suggestions to finish up the code indenting

2021-11-11 17:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +    "name": "Discogs",
``` suggestion
      "name": "Discogs",
```

2021-11-11 17:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +    "search_url": "https://www.discogs.com/search/?q={searchTerms}",
``` suggestion
      "search_url": "https://www.discogs.com/search/?q={searchTerms}",
```

2021-11-11 17:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +    "keyword": "disc",
``` suggestion
      "keyword": "disc",
```

2021-11-11 17:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> +    "favicon_url": "https://www.discogs.com/favicon.ico"
``` suggestion
      "favicon_url": "https://www.discogs.com/favicon.ico"
```

2021-11-11 17:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/chrome_settings_overrides/index.md
> + }
``` suggestion
  }
```

2021-11-12 02:34 UTC, rebloor approved these changes

2021-11-12 02:34 UTC, merged

2021-11-12 02:34 UTC, rebloor commented
Thanks for your help @Biki-das