fix typo
mdn/content pull request #10424
Opened 2021-11-10 07:01 UTC by logic-finder

#### Summary
just little modification on [AudioParam.value document](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/value)
- graduated → gradiated
- add a space `//which is...` → `// which is...`

#### Motivation

> If any **gradiated** or ramped value changing methods have been called and the current time is within the time range over which the **graduated** change should occur, the value is updated based on the appropriate algorithm.

- According to the context of the sentence, it seems `gradiated` is correct.
- I think it is better to have a space in a comment.

#### Supporting details

none

#### Related issues

none

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-11-10 20:40 UTC, wbamberg requested changes
Thanks for this PR! I think we should change the other one, I'm not sure "gradiated" is a word, and if it is, it doesn't seem to be defined in the Web Audio spec.

2021-11-10 20:40 UTC, wbamberg commented on files/en-us/web/api/audioparam/value/index.md
>  - If any gradiated or ramped value changing methods have been called and the current
```suggestion
- If any graduated or ramped value changing methods have been called and the current
```

2021-11-10 20:40 UTC, wbamberg commented on files/en-us/web/api/audioparam/value/index.md
> +  time is within the time range over which the gradiated change should occur, the value
```suggestion
  time is within the time range over which the graduated change should occur, the value
```

2021-11-11 05:00 UTC, logic-finder commented
!! I have thought that 'to graduate' means to get a diploma, so during translation I thought 'why this verb had been used here?', but I just realized it has another meaning. (I regarded 'gradiate' as a word related to 'gradient', so I thought this one was correct)

Thank you for giving me a chance to think about this.

p.s. What made me more surprised was that two words 'graduate' and 'gradient' have a same word origin: a Latin 'gradus', which means 'degree, step'. and it makes sense!

2021-11-12 03:50 UTC, wbamberg approved these changes
Ha, yes, it does have another meaning :). I wasn't sure if "gradiated" might also have some technical meaning that I was unaware of, but I can't find one.

Thanks for the fix @logic-finder !

2021-11-12 03:50 UTC, merged