New page: aria-keyshortcuts
mdn/content pull request #10434
Opened 2021-11-10 19:52 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-13 18:59 UTC, ericwbailey requested changes
A few questions and sadly nixing the `accesskey` portion.

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +The `aria-keyshortcuts` attribute exposes the existence of the shortcut to assistive technologies so the presence of the shortcut can be communicated to the users. Like all ARIA attributes, it has no
```suggestion
The `aria-keyshortcuts` attribute exposes the existence of the shortcut to assistive technologies so the presence of the shortcut can be communicated to its users. Like all ARIA attributes, it has no effect on the functionality of the page; the keyboard behavior must be added via JavaScript event handlers.
```

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Keyboard shortcuts applied to disabled elements should also be disabled.
Are you suggesting that a disabled state be applied to a visible piece of keyboard shortcut UI? My understanding is the keyboard shortcut would continue to "work" if the content it applies to isn't set properly, the effects of it just won't be applied until proper conditions are met

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Ensure all keyboard shortcuts are both visible to sighted users and made available to assistive technology users via `aria-keyshortcuts`.
How?

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Non-modifier keys are keys that have impact when used alone, be that printing a character, moving focus, or otherwise creating a keyboard event when used. Non-modifiers that print a single character
```suggestion
Non-modifier keys are keys that have impact when used alone, be that printing a character, moving focus, or otherwise creating a keyboard event when used. Non-modifiers that print a single character include characters like `P`, `z` and `.`. 

Since the plus sign is used in writing key combinations, it is written as `plus` if used as the non-modifier. Other written-out non-modifiers include white space characters `Space`, `Tab`, and `Enter`, and all characters that result in actions, like `ArrowUp`, `PageUp`, and `Escape`. 

If you want to use a character that might cause problems, like a a double quote character within double quotes, escape the character: `Control+&#39;`. 
```

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Modifier keys must be listed first in each key combination. Possible key combinations include "Control+P" or "Shift+Space" and "Q". If the full shortcut requires all three of these combinations in or
```suggestion
Modifier keys must be listed first in each key combination. Possible key combinations include `Control+P` or `Shift+Space` and `Q`. If the full shortcut requires all three of these combinations in order, it would be written as `aria-keyshortcuts="Control+P Shift+Space Q"`.  When a key combination includes more than one modifier key, the order of the modifiers doesn't matter, but they all must come first, before the non-modifier. 
```

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +#### Don't usurp browser, assistive technology, or operating system shortcuts
```suggestion
#### Don't override browser, assistive technology, or operating system shortcuts
```

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +
I'd like to see another short paragraph here explaining how while overriding an OS/UA keyboard shortcut can be annoying for non-assistive technology users, it can lead to shutting out access completely for an assistive technology users. Specially, avoiding single letter keyboard shortcuts and  common screen reader keyboard shortcuts.

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +
We'll need a short connecting sentence or two here to set up the content to follow.

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Take into account the diversity of available keyboards and the various keyboard language preferences. Modifier keys are often used to create language specific common punctuation symbols and number ch
Nice.

2021-11-13 18:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +While the `accesskey` attribute is natively accessibile to assistive technologies, we ensured the presence of the shortcut was known to sited users a well by highlighting the non-modifier character.
```suggestion
```

Unfortunately, `accesskey` has incredibly [poor browser and assistive technology support](https://webaim.org/techniques/keyboard/accesskey#poor).

2021-11-15 04:39 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +Keyboard shortcuts applied to disabled elements should also be disabled.
i mean "when clicking on the link won't do anything, using the shortcut to the link also shouldn't do anything."

Changing to:
> Keyboard shortcuts applied to disabled elements should also be disabled; when disabling an element for mouse users, remember to disable it for keyboard shortcut users.

2021-11-15 16:48 UTC, estelle reviewed
luckily i copied what i wrote because I had a GitHub fail locally and lost all my work, except I didn't ;)

2021-11-15 23:27 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +
added

2021-11-15 23:28 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +While the `accesskey` attribute is natively accessibile to assistive technologies, we ensured the presence of the shortcut was known to sited users a well by highlighting the non-modifier character.
i left it in, since it is important that they know it exists, but completely reworked it

2021-11-21 19:44 UTC, ericwbailey approved these changes

2021-11-21 19:44 UTC, merged