[DOM Reference] Document NamedNodeMap and children
mdn/content pull request #10446
Opened 2021-11-11 10:48 UTC by teoli2003

Part of #9740 

- Update the DOM sidebar by removing non-existing interfaces (deleted a long time ago)
-  Created the missing pages of `NamedNodeMap`.
- Updated the 2 pages that were existing.

Note: bcd companion PR browser-compat-data#13450 adds the missing `spec_url` entries.

2021-11-11 15:48 UTC, jpmedley requested changes

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/getnameditem/index.md
> +> So, `myMap[str]`is equivalent to `myMap.getNamedItem(str)` when `str` is a string.
```suggestion
> So, `myMap[str]`is equivalent to `myMap.getNamedItem(str)` where `str` is a string.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/item/index.md
> +> So, `myMap[i]`is equivalent to `myMap.item(i)` when `i` is a {{jsxref("Number")}}.
```suggestion
> So, `myMap[i]`is equivalent to `myMap.item(i)` where `i` is a {{jsxref("Number")}}.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/item/index.md
> +An {{domxref("Attr")}} or `null`if the number is greater than or equal to the `length` of
```suggestion
An {{domxref("Attr")}} or `null` if the number is greater than or equal to the `length` of
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/length/index.md
> +An {{jsxref("Number")}} containing the number of objects in the map
```suggestion
A {{jsxref("Number")}} containing the number of objects in the map
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditem/index.md
> +  - : the name of the attribute to remove from the map.
```suggestion
  - : The name of the attribute to remove from the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +remove the {{domxref("Attr")}} corresponding to the given namespace and local name from the map.
```suggestion
removes the {{domxref("Attr")}} corresponding to the given namespace and local name from the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/getnameditem/index.md
> +> So, `myMap[str]`is equivalent to `myMap.getNamedItem(str)` when `str` is a string.
I'm not being nit-picky here. This change is consistent with how such things are generally phrased in English.

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +  - : the namespace of the attribute to remove from the map
```suggestion
  - : The namespace of the attribute to remove from the map
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
```suggestion
    > **Warning:** `namespace` is the URI of the namespace, not the prefix.
    
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
The extra line is not a mistake. Without it, the definition of `localName` is swallowed by the warning.

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +  - : the local name of the attribute to remove from the map.
```suggestion
  - : The local name of the attribute to remove from the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditem/index.md
> +put the {{domxref("Attr")}} identified by its name in the map.
```suggestion
puts the {{domxref("Attr")}} identified by its name in the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditem/index.md
> +If there was already an {{domxref("Attr")}} with the same name in the map,
```suggestion
If there is already an {{domxref("Attr")}} with the same name in the map,
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditem/index.md
> +Return the old attribute if replaced, or `null` if the attribute is new.
```suggestion
Returns the old attribute if replaced, or `null` if the attribute is new.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditemns/index.md
> +put the {{domxref("Attr")}} identified by its name in the map.
```suggestion
puts the {{domxref("Attr")}} identified by its name in the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditemns/index.md
> +Return the old attribute if replaced, or `null` if the attribute is new.
```suggestion
Returns the old attribute if replaced, or `null` if the attribute is new.
```

2021-11-11 15:48 UTC, jpmedley commented on files/en-us/web/api/namednodemap/setnameditemns/index.md
> +  - : the attribute to insert in the map.
```suggestion
  - : The attribute to insert in the map.
```

2021-11-11 15:48 UTC, jpmedley commented on files/jsondata/GroupData.json
>          "ByteString",
@ddbeck I confess that I've never completely understood GroupData.json. I can't evaluate what's been done. Can you please review this or pass it to someone who can?

2022-02-09 12:28 UTC, ddbeck requested changes
Had a look at the GroupData and reviewed the rest while I was here. Thanks, @teoli2003.

2022-02-09 12:28 UTC, ddbeck commented on files/en-us/web/api/namednodemap/removenameditem/index.md
> +remove the {{domxref("Attr")}} corresponding to the given name from the map.
```suggestion
removes the {{domxref("Attr")}} corresponding to the given name from the map.
```

2022-02-09 12:53 UTC, teoli2003 commented on files/jsondata/GroupData.json
> -        "USVString",
Yes, `USVString`must go.

2022-02-09 12:59 UTC, teoli2003 commented on files/jsondata/GroupData.json
> -        "CSSValueList",
They are not part of the DOM but of CSSOM.

2022-02-09 13:04 UTC, teoli2003 commented on files/en-us/web/api/namednodemap/getnameditem/index.md
> +> So, `myMap[str]`is equivalent to `myMap.getNamedItem(str)` when `str` is a string.
Thanks, it is one of my "usual errors" that I'm trying to correct.

2022-02-09 13:49 UTC, teoli2003 commented on files/jsondata/GroupData.json
> -        "DOMString",
Yes DOMString, like USVString, will go away when all links to them will be removed. They are invisible to the web devs.

2022-02-09 13:50 UTC, teoli2003 commented on files/jsondata/GroupData.json
> -        "USVString",
The plan is to say `string` where it is used and to add a sentence saying which restriction it has from another string. There is `ByteString`that is similar too.

2022-02-09 13:53 UTC, teoli2003 commented on files/en-us/web/api/namednodemap/length/index.md
> +An {{jsxref("Number")}} containing the number of objects in the map
Fixed (couldn't directly commit this suggestion as the comment was marked "Outdated")

2022-02-09 13:56 UTC, teoli2003 commented on files/en-us/web/api/namednodemap/getnameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
Looks OK iin preview:
![image](https://user-images.githubusercontent.com/1466293/153215413-3da3899e-ab90-4877-9889-758eb2269596.png)

2022-02-09 14:05 UTC, teoli2003 commented on files/en-us/web/api/namednodemap/removenameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
I'll commit but I don't think the extra line is needed. Here is the screenshot from the preview:
![image](https://user-images.githubusercontent.com/1466293/153217121-05452246-52cb-49f5-8920-7f8013c0346d.png)

2022-02-09 14:22 UTC, teoli2003 commented on files/en-us/web/api/namednodemap/getnameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
```suggestion
    > **Warning:** `namespace` is the URI of the namespace, not the prefix.
```

2022-02-09 15:22 UTC, jpmedley approved these changes

2022-02-09 17:06 UTC, ddbeck commented on files/en-us/web/api/namednodemap/getnameditemns/index.md
> +    > **Warning:** `namespace`is the URI of the namespace, not the prefix.
Nice. Thank you!

2022-02-09 17:07 UTC, ddbeck approved these changes
Looks great. Thank you! 🎉

2022-02-09 17:08 UTC, ddbeck commented
(The failures are an artifact of the introduction of Netlify for contributor docs in December. It's ignorable in this case. Going ahead with a merge anyway.)

2022-02-09 17:08 UTC, merged