Remove the note about `SVGRect` inheriting from `DOMRectReadOnly`
mdn/content pull request #10441
Opened 2021-11-11 06:36 UTC by Andarist

#### Summary

The PR removes incorrect note.

#### Motivation

The note was incorrect

#### Supporting details

This document doesn't define any relationship between those types
https://www.w3.org/TR/SVG11/types.html#InterfaceSVGRect

If we check this in a browser (Chrome) then we won't see this inheriting from the `DOMRectReadOnly`:
<img width="757" alt="Screenshot 2021-11-11 at 07 34 37" src="https://user-images.githubusercontent.com/9800850/141249651-ed7c9208-67d5-4fdd-bde9-b448bf52ad1b.png">

#### Related issues
not applicable

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-11-11 15:22 UTC, jpmedley requested changes, later dismissed

2021-11-13 06:13 UTC, Andarist commented on files/en-us/web/api/svgrect/index.md
> -
Done

2021-11-15 10:32 UTC, Elchi3 commented
> This document doesn't define any relationship between those types https://www.w3.org/TR/SVG11/types.html#InterfaceSVGRect

fwiw, I think this is an outdated spec. https://drafts.fxtf.org/geometry/#DOMRect is more relevant here and defines: 

```
[Exposed=(Window,Worker),
 Serializable,
 LegacyWindowAlias=SVGRect]
interface DOMRect : DOMRectReadOnly { ... }
```

Meaning that SVGRect is a legacy class that is now called DOMRect which in fact inherits from DOMRectReadOnly.

2021-11-15 11:25 UTC, Andarist commented
I'm not sure how to navigate all of the specs properly - so I could make a mistake here. `DOMRect` is also recommended by the SVG 2 spec: https://svgwg.org/svg2-draft/types.html#__svg__SVGGraphicsElement__getBBox . From what I understand the SVG 2 spec is kinda frozen at the moment and has not been implemented in full by any browser: https://nikosandronikos.github.io/svg2-info/svg2-feature-support/

I've tested Chrome, Firefox, and Safari and all of them still implement this as this "legacy" SVGRect. So while it might be true that some specs have redefined the `SVGRect` to be an alias of `DOMRect`, in practice it isn't - and most likely people reading MDN are looking for practical information.

2021-11-15 11:32 UTC, Elchi3 commented
Makes sense to me. Lets leave SVGRect for now then until browsers catch up with the latest spec.

Can you also remove "{{InheritanceDiagram(600, 140)}}" in line 17? It is not needed.

2021-11-15 11:37 UTC, Andarist commented
@Elchi3 done

2021-11-15 11:37 UTC, Andarist commented
@Elchi3 done

2021-11-15 11:46 UTC, Elchi3 approved these changes
Thanks and congratulations on landing your first change here! 👍

2021-11-15 11:47 UTC, merged