Command line tools - fix redirect
mdn/content pull request #10558
Opened 2021-11-16 06:25 UTC by hamishwillee

Fixes #10005

The example is supposed to show how you can use `curl` to follow redirects to a link, and how you can use other tools like grep and awk to filter and modify the results.

It is broken because the MDN URL used for the example has been "fixed" so it is no longer a redirect. Damn that flaw fixer :-).
The original URL used [in the git blame](https://github.com/mdn/content/blame/761511892b9e45c88c4aa45db9efb5840f1c695d/files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.html#L264) is https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch.
So I have put that back in. 

It redirects to https://developer.mozilla.org/en-US/docs/Web/API/fetch in just one hop. The docs seemed to think that there would be three hops but that has perhaps been tidied in the redirects.txt. In any case, the fix I have made just refers to the one hop now.
The "link to test" is only ever displayed in code style, so should not get "fixed" again.

It is enough to see what is going on.

2021-11-17 18:14 UTC, ddbeck requested changes
Thanks, Hamish. That's a clever fix to the problem and the flaws system. Nicely done.

I have one little suggestion in a line comment. Also, PRs like this can be made a little faster to review by putting source format changes in a separate commit from the substantive changes (i.e., the semantic line breaks in one commit, the content changes in a second commit).

2021-11-17 18:14 UTC, ddbeck commented on files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +This doesn't work because the page has been redirected (to [/Web/API/fetch](/en-US/docs/Web/API/fetch))
I think it would really help to still tell the reader what to expect here. It doesn't work, but I'm not sure how the reader is supposed to know that. I'd like to see a return of some text like "you won't get an output".

2021-11-18 07:45 UTC, hamishwillee commented on files/en-us/learn/tools_and_testing/understanding_client-side_tools/command_line/index.md
> +This doesn't work because the page has been redirected (to [/Web/API/fetch](/en-US/docs/Web/API/fetch))
```suggestion
You won't get an output because the page has been redirected (to [/Web/API/fetch](/en-US/docs/Web/API/fetch)).
```

2021-11-18 10:30 UTC, ddbeck approved these changes
Thank you! 🎉

2021-11-18 10:30 UTC, merged