"at least one of this" => "this, that or both"
mdn/content pull request #10554
Opened 2021-11-16 01:30 UTC by ekisacik

#### Summary
The previous wording implied you might be able to chain more than one catch block, which is untrue.

#### Metadata
This PR…
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2021-11-16 18:39 UTC, teoli2003 requested changes

2021-11-16 18:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +A `catch`-block, `finally`-block or both must be present.
We are missing an article here: 
```suggestion
A `catch`-block, a `finally`-block, or both must be present.
```

2021-11-17 02:56 UTC, ekisacik commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +A `catch`-block, `finally`-block or both must be present.
Made the changes, thank you!

2021-11-17 16:08 UTC, teoli2003 approved these changes

2021-11-17 16:11 UTC, merged

2021-11-17 16:11 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: