Update index.md
mdn/content pull request #10585
Opened 2021-11-17 11:43 UTC by fseitun

rewrote a confusing paragraph that might have led to think that all passed arguments to a function are copies.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-17 19:56 UTC, wbamberg requested changes
Thanks, this is much better IMO. I had a couple of wording suggestions.

I like "change" better than "mutate" as it's simpler language, unless there is a good reason to prefer "mutate".

2021-11-17 19:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/functions/index.md
> +an object type parameter, if it's reasigned or mutated, the change will impact outside of the function.
```suggestion
an object type parameter, if it's reassigned or changed, the change will impact outside of the function.
```

Also "is visible outside" seems clearer then "will impact outside of" - was there a particular reason for this change?

2021-11-17 19:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/functions/index.md
> +This means that if a function reassigns a primitive type parameter, the value wont change outside the function. In the case of
```suggestion
This means that if a function reassigns or changes a primitive type parameter, the value won't change outside the function. In the case of
```

2021-11-17 21:25 UTC, fseitun commented on files/en-us/web/javascript/reference/functions/index.md
> +an object type parameter, if it's reasigned or mutated, the change will impact outside of the function.
I prefer mutate since it's the technical term to describe the following situation:
```
const a = {};
a.name = Federico //this is the mutation
```

2021-11-17 21:26 UTC, fseitun commented on files/en-us/web/javascript/reference/functions/index.md
> +This means that if a function reassigns a primitive type parameter, the value wont change outside the function. In the case of
Again I think that the correct term is reassignment, change is just to vague.

2021-11-17 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/functions/index.md
> +an object type parameter, if it's reasigned or mutated, the change will impact outside of the function.
Fair enough. Please just fix the typo, then.

2021-12-23 20:13 UTC, wbamberg approved these changes
👍 thanks, and sorry to be slow to review this.

2021-12-23 20:13 UTC, merged