New page: aria-modal
mdn/content pull request #10605
Opened 2021-11-18 00:44 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-21 20:44 UTC, ericwbailey requested changes
Two big picture questions:

1. What about non-modal dialogs? Should we mention them here?
2. What about suppressing screen reader caret browsing for inert background content?

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +The `aria-modal` attribute indicates whether an element is modal when displayed.
Is this in a modal state, the parent element of a modal, or something else?

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +When a dialog is displayed, if the user's interaction is limited to the contents of the dialog, until the dialog loses focus or is no longer displayed, the dialog is considered a "modal dialog". The
```suggestion
The `aria-modal` attribute is used to indicate the presence of a "modal" element, letting the user know the ability to interact with, or access other content on the page requires the modal dialog to be closed or otherwise lose focus. Modal dialogs are when content is displayed and the user's interaction is limited to its contents until dismissed. 
```

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +When a modal element is displayed, focus is generally placed in the modal. Similarly, assistive technologies (AT) generally navigate to the element unless focus has explicitly been set elsewhere. Dep
```suggestion
When a modal element is displayed, focus is placed in the modal which navigates assistive technologies (<abbr>AT</abbr>) to the modal's content (unless focus has explicitly been set elsewhere). Modals should have focus "trapped" to its contents until dismissed, to communicate the bounds of the modal and help distinguish it from the rest of the page's content.
```

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +In creating modals, ensure the modal can be controlled using only descendants of the modal element. In other words, if a modal dialog has a close button, the button should be a descendant of the dial
```suggestion
Ensure the modal can be controlled using only its descendant elements. If a modal dialog has a close button, the button should be a descendant contained with the modal container in the DOM. 
```

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +When a modal element is displayed, authors SHOULD mark all other contents as inert (such as "inert subtrees" in HTML) if the ability to do so exists in the host language.
```suggestion
When a modal element is displayed, authors <strong>should</strong> mark all other contents as inert (such as "inert subtrees" in HTML). 
```

Should we mention the `inert` attribute, it's current lack of support, the polyfil, and the polyfil's limitiations?

2021-11-21 20:44 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-modal/index.md
> +This partial example includes an alertdialog nested in a full-screen, non-scrollable backdrop. The [`role="alertdialog"`](/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role)	identifies the ele
```suggestion
This partial example includes an `alertdialog` nested in a full-screen, non-scrollable backdrop. 

The [`role="alertdialog"`](/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role)	identifies the element that serves as the alert dialog container. The [`aria-labelledby`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) provides the alert dialog an accessible name by referring to the element that provides the alert dialog title. The [`aria-describedby`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby) attribute gives the alert dialog an accessible description by referring to the alert dialog content that describes the primary message or purpose of the alert dialog.

```

2022-01-07 20:43 UTC, estelle commented
>     2. What about suppressing screen reader caret browsing for inert background content?
Should be handled in the role, not the attribute

2022-02-05 03:32 UTC, closed without merging