Fix developer.google.com links
mdn/content pull request #10637
Opened 2021-11-19 04:52 UTC by hamishwillee

Fixes up links to developer.google.com that have been migrated elsewhere - part of #7586

2021-11-19 05:58 UTC, hamishwillee commented on files/en-us/web/api/clients/claim/index.md
> +The **`claim()`** method of the {{domxref("Clients")}} interface allows an active service worker to set itself as the {{domxref("ServiceWorkerContainer.controller", "controller")}} for all clients wi
Changes in this doc are ALL layout

2021-11-19 05:59 UTC, hamishwillee commented on files/en-us/web/api/document/createelementns/index.md
> -  - : A string that specifies the [namespace
Changes in this doc are ALL layout

2021-11-19 05:59 UTC, hamishwillee commented on files/en-us/web/api/element/setattribute/index.md
> +  You can see this using your browser's page inspector ([Chrome](https://developer.chrome.com/docs/devtools/css/),
This is the only relevant change in this doc - fixed redirect to https://developer.chrome.com

2021-11-19 16:51 UTC, jpmedley requested changes

2021-11-19 16:51 UTC, jpmedley commented on files/en-us/web/api/resize_observer_api/index.md
> +{{Specifications("api.ResizeObserver")}}
Shouldn't this key go in the metadata?

2021-11-19 16:51 UTC, jpmedley commented on files/en-us/web/progressive_web_apps/installing/index.md
> +The example displays a series of fox pictures.If you have a web application compatible device available, use it to navigate to our demo at `https://mdn.github.io/pwa-examples/a2hs/`. You'll see fox p
```suggestion
The example displays a series of fox pictures. If you have a web application compatible device available, use it to navigate to our demo at `https://mdn.github.io/pwa-examples/a2hs/`. You'll see fox pictures, but more importantly, some form of user interface will be available to let you install the site as a web app.
```

2021-11-19 21:17 UTC, estelle approved these changes

2021-11-29 00:28 UTC, hamishwillee commented on files/en-us/web/api/resize_observer_api/index.md
> +{{Specifications("api.ResizeObserver")}}
@jpmedley Probably not. This is an API page so could in theory have multiple interfaces. Generally for these I keep the key in the macro in this case as a hint which part of the API we have chosen to report the spec on. 

There is no firm rule on this.

2021-12-02 18:05 UTC, estelle approved these changes

2021-12-02 18:06 UTC, estelle commented
@jpmedley @hamishwillee Are teh requested changes made? This appears ready for merge but I am blocked by "Merging is blocked
Merging can be performed automatically once the requested changes are addressed."

2021-12-02 19:40 UTC, jpmedley approved these changes

2021-12-02 19:40 UTC, merged