XRSession: Use single page for events
mdn/content pull request #10771
Opened 2021-11-25 15:49 UTC by Elchi3

#### Summary

For all XRSession events, use a single "event type" page. Redirect all onXXX event handler pages to these.

#### Motivation

One place to learn about XRSession events instead of two for each event.

#### Related issues
 The BCD work is done in https://github.com/mdn/browser-compat-data/pull/13597

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-11-29 18:08 UTC, jpmedley requested changes

2021-11-29 18:08 UTC, jpmedley commented on files/en-us/web/api/xrsession/visibilitychange_event/index.md
> +An {{domxref("XRSessionEvent")}} which, in addition to the generic {{domxref("Event")}} class, includes the following properties:
Where are the properties?

2021-11-30 15:08 UTC, Elchi3 commented on files/en-us/web/api/xrsession/visibilitychange_event/index.md
> +An {{domxref("XRSessionEvent")}} which, in addition to the generic {{domxref("Event")}} class, includes the following properties:
Forgot them here, thanks, added!

2021-11-30 15:08 UTC, Elchi3 commented on files/en-us/web/api/xrsession/selectstart_event/index.md
> +addEventListener('selectstart', () => { });
Done everywhere, thank you!

2021-11-30 15:10 UTC, Elchi3 commented on files/en-us/web/api/xrsession/inputsourceschange_event/index.md
> +### Event type
I've now added both 'Event type' and 'Event properties'. The structure for event page is currently under discussion, so there is no rule to follow yet - I'm just making things up. See https://github.com/mdn/content/discussions/10544

2021-11-30 20:03 UTC, jpmedley approved these changes

2021-11-30 20:03 UTC, merged