Fix all WebRTC_API links
mdn/content pull request #10884
Opened 2021-11-30 16:08 UTC by AnilSeervi

#### Summary

- Fixes all WebRTC_API links
#### Motivation

open-source
#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-12-20 19:37 UTC, wbamberg commented on files/en-us/web/api/audiotracklist/addtrack_event/index.md
> +title: "AudioTrackList: addtrack event"
```suggestion
title: 'AudioTrackList: addtrack event'
```

2021-12-20 19:45 UTC, wbamberg requested changes
Thanks for this PR @AnilSeervi !

It looks like this has Prettified the files involved (or used some other opinionated formatter) - as a rule I'd prefer a PR not to do that, and just to make the fix it wants to. But it's OK, and the Prettier version is much better in a few places, so I'm mostly happy with it.

The only bits I complained about are where it's using double-quotes for front matter strings - AFAIK we consistently use single-quotes here, so it seems like it will be confusing to change it in some random cases. One day we will run Prettier over everything and things will be better.

2021-12-20 19:45 UTC, wbamberg commented on files/en-us/web/api/audiotracklist/addtrack_event/index.md
> +title: "AudioTrackList: addtrack event"
```suggestion
title: 'AudioTrackList: addtrack event'
```

2021-12-20 19:45 UTC, wbamberg commented on files/en-us/web/api/audiotracklist/removetrack_event/index.md
> +title: "AudioTrackList: removetrack event"
```suggestion
title: 'AudioTrackList: removetrack event'
```

2021-12-21 03:39 UTC, AnilSeervi commented
I did this change in **codespaces** and as there is no prettier config file in the repo it looks like the config I use was enforced even tho what I did was search and replace every instance.

And because I did it in the web editor, it auto-saved the files that I searched and replaced again, triggering prettier-at-save.

A container can be set-up for working with codespaces like [github/docs ](https://github.com/github/docs) repo has.
More about how to setup here - https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-codespaces-for-your-project

2021-12-21 03:41 UTC, wbamberg approved these changes
👍 thank you @AnilSeervi :)

2021-12-21 03:41 UTC, merged