New page: aria-owns
mdn/content pull request #10892
Opened 2021-12-01 05:57 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-12-04 18:02 UTC, ericwbailey requested changes

2021-12-04 18:02 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +A child element is owned by it's DOM parent by default: in this case, `aria-owns` should not be used.  While the `aria-owns` attribute can be used to rearrange existing child elements into a differen
```suggestion
A child element is owned by it's DOM parent by default: in this case, `aria-owns` should not be used. Avoid using the `aria-owns` attribute to rearrange existing child elements into a different order. While it may be tempting to order the accessibility layer to match order changes created with the CSS {{CSSXref('order')}} property, avoiding both the `order` property and the `aria-owns` attribute is the best option. 
```

2021-12-04 18:02 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +If an element has both `aria-owns` and DOM children then the order of the child elements is the actual DOM children first, then the elements referenced in `aria-owns`. This order can be changed by in
```suggestion
If an element has both `aria-owns` and DOM children, the order of the child elements:

 1. The actual DOM children first, 
 2. Then the elements referenced in `aria-owns`. 
 
 This order can be changed by including the ID references to the actual DOM children in the `aria-owns` value. 
```

2021-12-04 18:06 UTC, ericwbailey requested changes

2021-12-04 18:06 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +An "owning element" is any DOM ancestor of an element. If an element visually, functionally, or contextually appears to "own" (be an ancestor of) an element, but doesn't actually "own" the element in
@estelle Can we rephrase this paragraph? I think we may use to need synonyms for the word "owns" here, in that it gets confusing determining the difference between inherited ownership and programmatically assigned ownership.

2021-12-04 18:06 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +A child element is owned by it's DOM parent by default: in this case, `aria-owns` should not be used. Avoid using the `aria-owns` attribute to rearrange existing child elements into a different order
@estelle The mentioning of CSS layout adjustment here is a surprise. Can we rephrase this paragraph, or possibly put up some content earlier to mention that CSS can make modifications or content ordering?

2021-12-04 18:06 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +When using `aria-owns`, make sure you manage focus order. Ensure the visual focus order matches this assistive technology reading order.
@estelle Do you think we should link to a resource on how to manage focus order here? It might be a new concept for a reader unfamiliar with ARIA/accessibility.

2021-12-10 01:55 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-owns/index.md
> +An "owning element" is any DOM ancestor of an element. If an element visually, functionally, or contextually appears to "own" (be an ancestor of) an element, but doesn't actually "own" the element in
done

2021-12-10 03:00 UTC, sideshowbarker commented
Rebased to fix CI failure (that I caused…)

2021-12-12 23:00 UTC, ericwbailey reviewed
One big picture question I'm wondering about that `aria-owns` brings up: should we mention when ARIA is unsuitable for use? 

[VoiceOver on iOS and macOS both do not currently support `aria-owns`](https://a11ysupport.io/tech/aria/aria-owns_attribute), but this is not be apparent to a person reading this documentation. Is it our job to highlight that? I am thinking:

- Yes, because it is very likely a reader won't do the research themselves, or test on a sophisticated suite of AT.
- If yes, how do we stay on top of maintaining this?
- If no, should we have some sort of bare minimum warning message across all ARIA documentation?

2021-12-14 00:48 UTC, estelle commented
We should put good verbiage to put on every single ARIA page.

2021-12-18 20:46 UTC, ericwbailey approved these changes

2021-12-18 20:46 UTC, merged