Consistent event pages in WebXR docs
mdn/content pull request #10923
Opened 2021-12-02 15:36 UTC by Elchi3

Attempt to make things somewhat consistent. The discussion is still ongoing in https://github.com/mdn/content/discussions/10544 but this brings the event pages I've touched so far to a consistent state.

2021-12-02 17:29 UTC, jpmedley requested changes
Generally, this looks really clean. The changes are just nits.

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrreferencespace/reset_event/index.md
> +  - : An {{domxref("XRRigidTransform")}} object indicating the position and orientation of the specified `referenceSpace`'s native origin after the event, defined relative to the coordinate system be
```suggestion
  - : An {{domxref("XRRigidTransform")}} object indicating the position and orientation of the specified `referenceSpace` object's native origin after the event, defined relative to the coordinate system before the event.
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrreferencespace/reset_event/index.md
> +  - : An {{domxref("XRRigidTransform")}} object indicating the position and orientation of the specified `referenceSpace`'s native origin after the event, defined relative to the coordinate system be
I totally admit this is a judgement call. I don't like to mix fonts in the same word.

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +## Event type
```suggestion
## Event Type
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +## Event type
I didn't think MDN headings were mixed case. Ignore this if that's changed (and let me know). Can you please also look at the headings not directly covered by your changes.

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +## Event properties
```suggestion
## Event Properties
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrcylinderlayer/redraw_event/index.md
> +## Event type
```suggestion
## Event Type
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrcylinderlayer/redraw_event/index.md
> +## Event properties
```suggestion
## Event Properties
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrequirectlayer/redraw_event/index.md
> +## Event type
```suggestion
## Event Type
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrequirectlayer/redraw_event/index.md
> +## Event properties
```suggestion
## Event Properties
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrquadlayer/redraw_event/index.md
> +## Event type
```suggestion
## Event Type
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrquadlayer/redraw_event/index.md
> +## Event properties
```suggestion
## Event Properties
```

2021-12-02 17:29 UTC, jpmedley commented on files/en-us/web/api/xrsystem/devicechange_event/index.md
> +## Event type
```suggestion
## Event Type
```

2021-12-02 17:34 UTC, Elchi3 commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +An {{domxref("XRLayerEvent")}}. Inherits from {{domxref("Event")}}.
I'm quite unsure about this proposal. I think event type pages are different from event interface pages (e.g. https://developer.mozilla.org/en-US/docs/Web/API/XRLayerEvent which could have the diagram).

If you feel strongly about this, I encourage you to propose this in the discussion on the structure of the events page: https://github.com/mdn/content/discussions/10544

2021-12-02 17:35 UTC, Elchi3 commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +## Event type
Headings on MDN are mixed case.

2021-12-02 19:30 UTC, jpmedley commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +An {{domxref("XRLayerEvent")}}. Inherits from {{domxref("Event")}}.
I plan to. 

I don't understand your issue. The macro doesn't say event or or interface. It just shows the relationship and provides links and does so with automation. To provide this manually I have to look it up. Further more, if an inheritance sequence is expanding by adding upstream items, no one has to remember to update event pages. (This happens sometimes. Remember the audio classes that got base classes a few years ago?)

2021-12-07 10:26 UTC, Elchi3 commented on files/en-us/web/api/xrcubelayer/redraw_event/index.md
> +An {{domxref("XRLayerEvent")}}. Inherits from {{domxref("Event")}}.
OK. I've opened https://github.com/mdn/content/pull/11025 to exercise this.

2021-12-07 20:32 UTC, jpmedley approved these changes

2021-12-07 20:32 UTC, merged