Update index.html
mdn/content pull request #1100
Opened 2021-01-08 15:22 UTC by jadjoubran

Code inside Promise constructor runs synchronously. Update code based on mdn/sprints#1251

Closes mdn/sprints#1251

2021-01-08 15:24 UTC, jadjoubran commented
With this update, the output should look like the following:

- 1) Started (Sync code)
- 1) Promise constructor (Sync code)
- 1) Promise made (Sync code)
- 1) Promise fulfilled (Async code terminated)

2021-01-09 10:58 UTC, sideshowbarker requested changes

2021-01-09 10:58 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/promise/index.html
> +    log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Promise constructor (<small>Sync code</small>)');
```suggestion
    log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Promise constructor (<small>Async code</small>)');
```
Right?

2021-01-11 16:28 UTC, jadjoubran commented on files/en-us/web/javascript/reference/global_objects/promise/index.html
> +    log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Promise constructor (<small>Sync code</small>)');
Is it really async? I am not entirely sure because if you look at the output, it seems to me that it's running synchronously

Here's the same code as above that can be run in the browser console (without requiring some DOM elements):

```javascript
function testPromise() {
  // begin
  console.log('A. Started');
  // We make a new promise: we promise a numeric count of this promise, starting from 1 (after waiting 3s)
  let p1 = new Promise((resolve, reject) => {
    // The executor function is called with the ability to resolve or reject the promise
    console.log('B. Promise constructor');
    // This is only an example to create asynchronism
    window.setTimeout(function() {
        // We fulfill the promise !
        resolve();
    }, Math.random() * 2000 + 1000);
  });

  // We define what to do when the promise is resolved with the then() call,
  // and what to do when the promise is rejected with the catch() call
  p1.then(function() {
    // Log the fulfillment value
    console.log('C. Promise fulfilled');
  }).catch((reason) => {
    // Log the rejection reason
    console.log(`Handle rejected promise (${reason}) here.`);
  });
  // end
  console.log('D. Promise made');
}

testPromise();
```

The output is:
- A. Started
- B. Promise constructor
- D. Promise made
- C. Promise fulfilled

2021-01-11 16:53 UTC, sideshowbarker commented
At this point, I’d suggest that for further review, you circle back with @arye-dov-eidelman — who raised the original issue at https://github.com/mdn/interactive-examples/issues/1330 — and see whether he finds that the current patch here is a satisfactory resolution to the original issue he raised.

2021-01-11 22:04 UTC, arye-dov-eidelman commented
Looks good to me. If you wanted to log when the async code starts that would be on line 343.

2021-01-13 09:09 UTC, jadjoubran commented
Sounds good @arye-dov-eidelman. I would rather not mention the async here since people might confuse it with the promise constructor

2021-01-13 09:20 UTC, sideshowbarker approved these changes
> The output is:
> 
> * A. Started
> * B. Promise constructor
> * D. Promise made
> * C. Promise fulfilled

OK, then can we please consider formatting the output exactly like that? I mean, drop all the the stuff in the parentheses? It doesn’t seem necessary for the purpose of what this is intended to illustrate — and in fact to me at least seems distracting.

However, if you feel strongly otherwise, I’m fine with merging this as-is.

2021-01-13 09:20 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/promise/index.html
> +    log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Promise constructor (<small>Sync code</small>)');
```suggestion
    log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Promise constructor;
```

2021-01-13 09:20 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/promise/index.html
> +  log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Started (<small>Sync code</small>)');
```suggestion
  log.insertAdjacentHTML('beforeend', thisPromiseCount + ') Started');
```

2021-01-13 09:24 UTC, jadjoubran commented
Agreed! Fixed, thanks!

2021-01-13 09:56 UTC, sideshowbarker approved these changes

2021-01-13 09:58 UTC, merged

2021-01-14 17:32 UTC, arye-dov-eidelman commented
The code snippet was updated but the live demo wasn't updated.

![Screenshot_20210114-122815_Chrome](https://user-images.githubusercontent.com/7709411/104626588-17be5500-5664-11eb-9e86-827906ea0657.jpg)

2021-01-14 17:35 UTC, arye-dov-eidelman commented
(also p tags for each log would be nice.)

2021-01-14 17:41 UTC, sideshowbarker commented
> (also p tags for each log would be nice.)

Yeah @jadjoubran maybe a follow-up PR to put some link breaks between the log messages?

2021-01-14 17:44 UTC, sideshowbarker commented
> The code snippet was updated but the live demo wasn't updated.

The change hasn’t gone live yet on the production site, so please instead check  https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#advanced_example.

2021-01-15 13:08 UTC, jadjoubran commented
Done 👍