New page: aria-relevant
mdn/content pull request #11017
Opened 2021-12-07 04:18 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-12-11 19:18 UTC, ericwbailey requested changes

2021-12-11 19:18 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-relevant/index.md
> +Used in ARIA live regions, the global `aria-relevant` attribute indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified.
What do you think about "the document," or "the page or view" instead of "the accessibility tree"? I say this because while you're definitely technically correct, a reader may not know what it is.

2021-12-11 19:18 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-relevant/index.md
> +[ARIA live regions](/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) are areas of a web page that are updated when user focus may be elsewhere. When an update is outside of the user's focus, ass
```suggestion
[ARIA live regions](/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) are areas of a web page that are updated when user's attention may be elsewhere. When an update is outside of the user's keyboard focus, assistive technologies such as screen readers use a live region area to report updates to the user.
```

2021-12-14 00:46 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-relevant/index.md
> +Used in ARIA live regions, the global `aria-relevant` attribute indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified.
i linked to https://developer.mozilla.org/en-US/docs/Glossary/Accessibility_tree

2021-12-18 20:42 UTC, ericwbailey approved these changes

2021-12-18 20:42 UTC, merged