New page: aria-roledescription
mdn/content pull request #11040
Opened 2021-12-08 01:28 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-12-11 19:32 UTC, ericwbailey requested changes

2021-12-11 19:32 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +Users depend on the presentation of known role name to understand the the purpose of the element and, if it is a widget, how to interact with it. So, only use `aria-roledescription` to clarify the pu
>only use `aria-roledescription` to clarify the purpose of non-interactive container roles like `group` or `region` and to provide a more specific description to a widget.

Can we make this a note?

2021-12-11 19:32 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +Some assistive technologies (AT), such as screen readers, present the role of an element as part of the user experience. The `aria-roledescription` attribute provides a way to define a different huma
```suggestion
Some assistive technologies (<abbr>AT</abbr>), such as screen readers, present the role of an element as part of the user experience. The `aria-roledescription` attribute provides a way to define a different human-readable name to be presented by AT as the role of an element.
```

2021-12-11 19:32 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +The `aria-roledescription` property overrides how ATs localize and express the name of a role.  When you override a role name the user understands, you can negatively impact a users' ability to under
```suggestion
The `aria-roledescription` property overrides how ATs localize and express the name of a role. When you override a role name the user understands, you can potentially negatively impact a users' ability to understand and interact with an element.
```

2021-12-11 19:32 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +When there are no semantic or ARIA widget roles that correspond to the interaction model of your widget, use `role="application"`, provide an `aria-roledescription` with a human-readable, author-loca
What do you think about removing this all together? I am of the school of thought that authors may think their use case is special, and therefore worthy of a unique roledescription. In these scenarios, the interactions can usually be broken down into smaller pieces that have relevant roles, or needs to be revisited all together. 

In short, I'd much rather have to have an author really dig to discover this info, rather than try to use this paragraph to justify a bad design.

2021-12-11 19:32 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +
If we remove the paragraph on line 23, I'd also advocate for removing this bit.

2021-12-13 22:20 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +When there are no semantic or ARIA widget roles that correspond to the interaction model of your widget, use `role="application"`, provide an `aria-roledescription` with a human-readable, author-loca
I included your note instead: 
> Avoid using the `aria-roledescription` attribute. When a use case appears special, worthy of a unique roledescription, the interactions can often times be broken down into smaller pieces that have relevant roles.

2021-12-13 22:21 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-roledescription/index.md
> +
I kept 23 with a note, but added a paragraph after this example:
> Again, avoid using `aria-roledescription`. In this example, `escape` has no relevant meaning to the user, but `button` with "escape" as a label does.

2021-12-18 20:34 UTC, ericwbailey approved these changes

2021-12-18 20:35 UTC, merged