USB: Single page for events
mdn/content pull request #11051
Opened 2021-12-08 11:14 UTC by Elchi3

Use a single page for USB events.

BCD work: https://github.com/mdn/browser-compat-data/pull/13886

2021-12-08 16:35 UTC, dominiccooney commented on files/en-us/web/api/usb/disconnect_event/index.md
> +An {{domxref("USBConnectionEvent")}}. Inherits from {{domxref("Event")}}.
Nit: Article should be "*A* USBConnectionEvent

2021-12-08 16:42 UTC, dominiccooney commented on files/en-us/web/api/usb/index.md
Not related to your change, but should this page mention that you use `navigator.usb` to get one of these objects?

2021-12-09 19:05 UTC, jpmedley requested changes

2021-12-09 19:05 UTC, jpmedley commented on files/en-us/web/api/usb/connect_event/index.md
> +The **`connect`** property of the {{DOMxRef("USB")}} interface is an event fired whenever a paired device is connected.
```suggestion
The **`connect`** event callback of the {{DOMxRef("USB")}} interface is fired whenever a paired device is connected.
```

2021-12-09 19:05 UTC, jpmedley commented on files/en-us/web/api/usb/connect_event/index.md
> +The **`connect`** property of the {{DOMxRef("USB")}} interface is an event fired whenever a paired device is connected.
I think this conveys more information in roughly the same space. I can make this a formal proposal if need be.

2021-12-09 19:05 UTC, jpmedley commented on files/en-us/web/api/usb/disconnect_event/index.md
> +The **`connect`** property of the {{DOMxRef("USB")}} interface is an event fired whenever a paired device is disconnected.
```suggestion
The **`connect`** event callback of the {{DOMxRef("USB")}} interface is fired whenever a paired device is disconnected.
```

2021-12-09 19:05 UTC, jpmedley commented on files/en-us/web/api/usb/index.md
> +  - : An event fired whenever a previously paired device is connected.
```suggestion
  - : Fired whenever a previously paired device is connected.
```

2021-12-09 19:05 UTC, jpmedley commented on files/en-us/web/api/usb/index.md
> +  - : An event fired whenever a paired device is disconnected.
```suggestion
  - : Fired whenever a paired device is disconnected.
```

2021-12-13 15:45 UTC, jpmedley approved these changes

2021-12-13 15:51 UTC, merged