Clarifications about Safari in the building cross-browser extensions
mdn/content pull request #11102
Opened 2021-12-10 02:32 UTC by rebloor

#### Summary
Updating information regarding Safari in the [Building a cross-browser extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension) article.

#### Motivation
Information about Safari is out of date as it now supports web extensions.

#### Related issues
Fixes feedback on  Updating information about Edge [#11005](https://github.com/mdn/content/pull/11005) 

#### Metadata

This PR…
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-12-10 08:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
>  This polyfill addresses the API namespace and asynchronous event handling across Firefox, Chrome, Opera, and Edge. However, at the time of writing (December 2021), support for Opera and Edge was unof
Remove the part about being unofficial. Edge and Opera are based on Chromium, and if it works in Chrome, it also works elsewhere.

2021-12-10 08:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    At the time of writing, except for Safari, only `"manifest_version"`, `"version"`, and `"name"` are mandatory keys. Safari has a more comprehensive set of mandatory requirements, such as setting
What's this last sentence? That's not true. There was a requirement for background.persistent to be false, but I thought that the property may be ignored if set to true.

2021-12-10 14:58 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
>  This polyfill addresses the API namespace and asynchronous event handling across Firefox, Chrome, Opera, and Edge. However, at the time of writing (December 2021), support for Opera and Edge was unof
This is in line with the comments made in the readme for the polyfill. However, either way, it probably is best to rely on the project notes rather than duplicating them here. Removed.

2021-12-10 15:04 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    At the time of writing, except for Safari, only `"manifest_version"`, `"version"`, and `"name"` are mandatory keys. Safari has a more comprehensive set of mandatory requirements, such as setting
On checking, see this is specifically for iOS. It is mentioned in the Review Your Manifest section of [Assessing Your Safari Web Extension’s Browser Compatibility](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility)

2021-12-10 16:29 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    At the time of writing, except for Safari, only `"manifest_version"`, `"version"`, and `"name"` are mandatory keys. Safari has a more comprehensive set of mandatory requirements, such as setting
It's not `background` but `persistent`.

`persistent` is documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

In response to a question from an extension developer during a WECG meeting, Timothy (Apple) has previously acknowledged the issue and expressed willingness to make the property optional. See following note, copied from https://github.com/w3c/webextensions/blob/main/_minutes/2021-11-11-wecg.md:

> [carlos] The use of “persistent” in the manifest prevents extensions from loading in Safari on iOS - https://developer.apple.com/forums/thread/691542
>
> * [timothy] We currently require the persistent flag to be set to false, to ensure that extensions are designed for non-persistency. We are supportive of one manifest that works in all browsers, and as mentioned in previous meetings a warning rather than an error may be preferred.

Yesterday, Timothy (Apple) said that the `persistent` key is ignored in their latest version with MV3 (source: https://github.com/w3c/webextensions/pull/141/files):

> * [timothy] We have shipped this in [our latest Safari technology preview](https://webkit.org/blog/12137/release-notes-for-safari-technology-preview-136/) - MV3 + event pages. "persistent" key is ignored

2021-12-11 15:13 UTC, Rob--W requested changes
https://github.com/mdn/content/pull/11102#discussion_r766815923

2021-12-14 09:40 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    At the time of writing, except for Safari, only `"manifest_version"`, `"version"`, and `"name"` are mandatory keys. Safari has a more comprehensive set of mandatory requirements, such as setting
@Rob--W Given that it looks as though we're dealing with a moving target, I've removed this reference.

2021-12-14 09:52 UTC, Rob--W approved these changes
r+ with nits addressed.

2021-12-14 09:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +Details about the support for the extension APIs among the main browsers, Firefox for Android, and Safari on iOS can be found on the Mozilla Developer Network [Browser support for JavaScript APIs](/e
"... among the main browsers, Firefox for Android, and Safari for iOS ... "

can't this be misinterpreted as Firefox for Android and Safari for iOS being the main browsers?

2021-12-14 09:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    <tr>
This `<tr>` is redundant (two `<tr>` next to each other without a closing `</tr>`). Remove one.

2021-12-14 10:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +Details about the support for the extension APIs among the main browsers, Firefox for Android, and Safari on iOS can be found on the Mozilla Developer Network [Browser support for JavaScript APIs](/e
Good point, it's certainly a possibility. Rephrased.

2021-12-14 10:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/build_a_cross_browser_extension/index.md
> +    <tr>
Thanks, structure of the table tags is fixed

2021-12-14 10:30 UTC, merged