Page macro: CSP header directives - duplicate source info
mdn/content pull request #11185
Opened 2021-12-14 01:19 UTC by hamishwillee

Part of #3196

The CSP headers all (more or less) included the directive information for sources using the page macro. This directly includes the source in each of the relevant pages.

Chose to duplicate rather than link to this material.

2022-01-08 04:54 UTC, wbamberg commented
Even though I feel like this is my fault, and even though I still don't like the `{{page}}` macro for ad hoc inclusion of content, this PR makes me sad. This is duplication across quite a few pages of quite complex intricate content.

I think it would be better in a case like this to have a single page that documents `<source>` that we can link to from the other pages. An analogy is in the CSS docs where we have [`<color>`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) and link to it from all the places that include a color in their definition, like [`background-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color). I don't know if a thing like this would already have a home in the HTTP docs organization though.

But that's just my opinion really. I'd be happy to hear other views.

2022-01-09 23:44 UTC, hamishwillee commented
@wbamberg Yes, it "hurt" to do this.

As per your original justifications, if the sources can ever be different then the duplication makes sense.

If the sources will always the same then you could duplicate in each place, or have a single source and link, or have a single source and include (using the macro). 

Page inclusion is better for the reader because they don't have to jump around for the information

I think this could be a single page "CSP Sources" or "CSP Directive Sources". You might argue that having just one page helps readers understand that there really is only one set of possible sources so they only need to read it once. But that's just a convenient justification - my main concern is that this is quite detailed and will be hard to maintain in multiple places. So either link or include, but duplication is risky.

2022-01-11 21:58 UTC, wbamberg commented
> @wbamberg Yes, it "hurt" to do this.
> 
> As per your original justifications, if the sources can ever be different then the duplication makes sense.
> 

But they are always the same here, aren't they?

> If the sources will always the same then you could duplicate in each place, or have a single source and link, or have a single source and include (using the macro).
> 
> Page inclusion is better for the reader because they don't have to jump around for the information
> 
> I think this could be a single page "CSP Sources" or "CSP Directive Sources".

I think this would be better.

> You might argue that having just one page helps readers understand that there really is only one set of possible sources so they only need to read it once. But that's just a convenient justification - my main concern is that this is quite detailed and will be hard to maintain in multiple places. So either link or include, but duplication is risky.

Yes, agreed.

I think that if we did want to keep some kind of page inclusion, it might be acceptable if we had a more controlled way to do it. For instance maybe we could have /fragments alongside /files, and let `{{page}}` only reference content under there. That at least makes it explicit that the fragments are fragments, so people editing them know not to break pages that include them. We might also want to restrict the things that they could do, such as not letting them include KS macros, so we could avoid the build dependency problem.

But I'm not sure it's worth it.

2022-01-11 22:08 UTC, hamishwillee commented
I'm happy to try redoing this as a linked page, but not until I get back. So let's park this "for now". 

Re other alternatives, I have used it via fragments before on other systems. This is similarly error prone - yes it tells you that more care needs to be taken, but you still need to do lots of checking, and the one time you don't is the one time it breaks. 

What might help is if a macro inclusion automatically marked all other including instances as "touched" so that they would all appear in the version to be reviewed.

2022-01-31 06:36 UTC, hamishwillee commented
@wbamberg Howdy! OK, this is my attempt at a single page with cross linking. It removes a lot of additional duplication (previously some things uses page macro inclusion and some just duplicated). I am pretty sure that anything that specified a `source` had exactly the same text, except for obvious errors (and base-uri, which has a caveat that has been retained).

2022-02-01 04:01 UTC, wbamberg requested changes
Hi Hamish! I think this is great. I had a few little comments.

2022-02-01 04:01 UTC, wbamberg commented on files/en-us/web/http/headers/content-security-policy/base-uri/index.md
> +Note however that some of the values don't make sense for `base-uri`, such as the keywords `'unsafe-inline'` and `'strict-dynamic'`.
I know it already said this, but as a reader I don't like docs that just say "some of... such as". It leave me thinking, which other ones are there? I don't think it should block this PR, but maybe a follow-up issue to list everything that does not apply?

2022-02-01 04:08 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/sources/index.md
> +title: 'CSP Source Values'
```suggestion
title: 'CSP source values'
```

2022-02-01 04:09 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/sources/index.md
> +title: 'CSP Source Values'
It was already "CSP Source Values", or did you mean using `"`? Single `'` is the way this is done mostly. If OK, please commit it. I'm ambivalent.

2022-02-01 04:11 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/base-uri/index.md
> +Note however that some of the values don't make sense for `base-uri`, such as the keywords `'unsafe-inline'` and `'strict-dynamic'`.
@wbamberg This text comes from the original version. Yes I agree, but I don't know the exceptions, and it is unlikely to be high priority. I'll add an issue once this merges so "someone" can find out.

2022-02-01 04:17 UTC, wbamberg commented on files/en-us/web/http/headers/content-security-policy/sources/index.md
> +title: 'CSP Source Values'
I meant sentence case: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#page_titles .

2022-02-01 04:18 UTC, wbamberg approved these changes
Nice, thank you Hamish!

2022-02-01 04:18 UTC, merged

2022-02-01 07:02 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/base-uri/index.md
> +Note however that some of the values don't make sense for `base-uri`, such as the keywords `'unsafe-inline'` and `'strict-dynamic'`.
Cheers. Thanks for the help. Tracking issue in #12574