Events: Update MDN contribution docs
mdn/content pull request #11196
Opened 2021-12-14 11:20 UTC by Elchi3

I think we agreed on having a single page for events, see https://github.com/mdn/content/discussions/9098

I think we also agreed on a few things for the structure of the single event page, see https://github.com/mdn/content/discussions/10544.

This PR updates the contribution docs. We can refine the contribution docs more once we (I) run into more complex questions like the remaining event handler mixins and bubbling and these sort of things.

cc @jpmedley who asked to be cc'ed.

2021-12-16 10:12 UTC, ddbeck requested changes
Exciting! Thanks for making these changes, Florian. A few suggestions in line comments, but nothing serious I hope. 😄

2021-12-16 10:12 UTC, ddbeck commented on files/en-us/mdn/contribute/howto/write_an_api_reference/index.md
> +Events are documented as sub pages of their target interfaces, using the slug _eventname_\_event with the title set to `Interface eventName event`. The event handler `onEventName` is represented on t
And now for an optional style suggestion:

Like we do in the BCD guidelines, I rather like the imperative for docs like this. I think putting this in more assertive terms—something like "Document events as sub pages of their target interfaces. Use the slug…"—makes it clearer that we expect authors to do a certain thing. By comparison, I read the the passive voice as descriptive and optional.

2021-12-16 10:12 UTC, ddbeck commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +A generic {{domxref("Event")}}.
Throughout this new template text, it might be nice to more clearly distinguish template text from commentary on the template. It doesn't look like there's a convention for this. Maybe using code blocks might be a good way to go, so you could copy and paste them? For instance:

````suggestion
```markdown
A generic {{domxref("Event")}}.
```
````

2021-12-16 17:01 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +A generic {{domxref("Event")}}.
hm yes, the page tries do be an. overall (copy-pastably) template and explanation at the same time. I think that doesn't work very well. I wonder if it is worth to have the template separately?

Alternatively, we could present no overall template, but slices of the template would be presented with the markdown fences with their commentary and scenarios when to use which slice. I think I would prefer this.

2021-12-17 02:18 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +A generic {{domxref("Event")}}.
None of the alternatives are particularly good, which is why I once proposed generating the pre-seeded template using a wizard and I'm also interested in Joe Medley's templates. That way there is much less to explain.

2021-12-17 02:22 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +Fill in a simple example that nicely shows a typical usage of the event, then perhaps some more complex examples (see our guide on how to add [code examples](/en-US/docs/MDN/Structures/Code_examples)
"can" or "should" show, and either or or both? We should state.

2021-12-17 13:10 UTC, ddbeck commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +A generic {{domxref("Event")}}.
I think we'll eventually want separate template files (or generated templates!) for the meta site. I don't actually care to come up with a correct answer here. I just thought for the changes _within the diff_ (not reaching to the rest of the page or any other page) that some distinguishing formatting would be nice. Later on you use italics (_In addition to the properties listed below_), which is also fine. Inverting things would also be fine (e.g., putting commentary in some other format and make template text unmarked).

2022-01-13 15:26 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +Fill in a simple example that nicely shows a typical usage of the event, then perhaps some more complex examples (see our guide on how to add [code examples](/en-US/docs/MDN/Structures/Code_examples)
Went with "should" here. If that doesn't seem practical we can make this rule more lax again.

2022-01-13 15:28 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.md
> +A generic {{domxref("Event")}}.
I've made the boilerplate sentences italic now.
Generated templates would be really great indeed

2022-01-19 13:07 UTC, Elchi3 commented
I think I've addressed the feedback and merge conflicts are also resolved now.

2022-01-24 17:42 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-01-24 17:42 UTC, merged