HTTP UA Client Hint headers
mdn/content pull request #11191
Opened 2021-12-14 06:46 UTC by hamishwillee

This follows on from #10715 by adding docs for the remaining client hint headers.

Note that there are some associated changes in BCD which mean compat tables might not yet render.
- https://github.com/mdn/browser-compat-data/pull/13990 
- https://github.com/mdn/browser-compat-data/pull/13989
- I also can't yet do the Full-Version-List yet because it isn't in a release build https://chromestatus.com/feature/5703317813460992

2021-12-23 22:55 UTC, wbamberg requested changes
Just a few comments. My biggest issue here is that the "client hints" doc is in the glossary, but that's a separate thing.

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/index.md
> +The [UA client hints](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) are request headers that provide information about the user agent and the platform/architecture on which it is running
This Client hints page ought to be in the HTTP docs, not a glossary page. But that's out of scope here.

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +The **`Sec-CH-UA-Arch`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's underlying CPU architecture, such as arm or x86.
```suggestion
The **`Sec-CH-UA-Arch`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's underlying CPU architecture, such as ARM or x86.
```

?

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +A server requests the `Sec-CH-UA-Arch` header by including the {{HTTPHeader("Accept-CH")}} in a _response_ to some request from the client, using the name of the desired header as a token:
I don't think "response" needs to be italicized here, but a tiny point, and arguable.

(I expect this comment will apply to a few other pages here and won't repeat it there.)

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Arch` header to subsequent requests.
I think "opt-in to" is wrong here: if used as a verb it should be "opt into". But just:

```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Arch` header to subsequent requests.
```

...would be clearer IMO.

(I expect this comment will apply to a few other pages here and won't repeat it there.)

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP Caching > Varying responses](/en-US/docs/Web/HTTP/Caching#varying_responses) and {{HTTPHeader("Vary")}}
It's unclear to me how this link is relevant, but maybe it is in some way I don't understand!

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +The **`Sec-CH-UA-Full-Version-List`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's branding and full semantic version i
```suggestion
The **`Sec-CH-UA-Full-Version-List`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's branding and full version information.
```

Semantic versioning is a [specific thing](https://semver.org/) that browsers don't necessarily use (and in face most don't).

There are a few other usages in this page that should be fixed too.

2021-12-23 22:55 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-full-version/index.md
> +The **`Sec-CH-UA-Full-Version`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's full semantic version string.
also in this page

2021-12-24 01:36 UTC, hamishwillee commented on files/en-us/web/http/headers/index.md
> +The [UA client hints](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) are request headers that provide information about the user agent and the platform/architecture on which it is running
I agree. Have raised this before but no one seemed to mind the current position. I will move it next year.

2021-12-24 01:39 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +A server requests the `Sec-CH-UA-Arch` header by including the {{HTTPHeader("Accept-CH")}} in a _response_ to some request from the client, using the name of the desired header as a token:
The only way a server can send this is in a response, since it doesn't make requests. I chose to use italics to highlight that it was a server message. But following the rule "a reviewer finds it annoying and perhaps it therefore is" :-)

```suggestion
A server requests the `Sec-CH-UA-Arch` header by including the {{HTTPHeader("Accept-CH")}} in a response to some request from the client, using the name of the desired header as a token:
```

2021-12-24 01:40 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-bitness/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Bitness` header to subsequent requests.
```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Bitness` header to subsequent requests.
```

2021-12-24 01:40 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Full-Version-List` header to subsequent requests, as shown below:
```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Full-Version-List` header to subsequent requests, as shown below:
```

2021-12-24 01:40 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Full-Version` header to subsequent requests.
```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Full-Version` header to subsequent requests.
```

2021-12-24 01:40 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-model/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Model` header to subsequent requests.
```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Model` header to subsequent requests.
```

2021-12-24 01:41 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-platform-version/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Platform-Version` header to subsequent requests.
```suggestion
The client may choose to provide the hint, and add the `Sec-CH-UA-Platform-Version` header to subsequent requests.
```

2021-12-24 01:41 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +The client may then opt-in to providing the hint, and add the `Sec-CH-UA-Arch` header to subsequent requests.
Yeah, much better thanks. Will roll it out.

2021-12-24 01:45 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +The **`Sec-CH-UA-Full-Version-List`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's branding and full semantic version i
I'm happy to remove, but in fact the string returned appears to actually be a that "specific thing" - i.e. the major.minor.patch format. Happy to remove though - I could be wrong and safer this way.

2021-12-24 01:45 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +The **`Sec-CH-UA-Full-Version-List`** header provides the brand and full semantic version for each brand associated with the browser, in a comma-separated list.
```suggestion
The **`Sec-CH-UA-Full-Version-List`** header provides the brand and full version information for each brand associated with the browser, in a comma-separated list.
```

2021-12-24 01:46 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +> **Note:** This is similar to {{HTTPHeader("Sec-CH-UA")}}, but includes the full semantic version number instead of the signficant version number for each brand.
```suggestion
> **Note:** This is similar to {{HTTPHeader("Sec-CH-UA")}}, but includes the full version number instead of the significant version number for each brand.
```

2021-12-24 01:46 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +A comma separated list of brands in the user agent brand list, and their associated full semantic version number.
```suggestion
A comma separated list of brands in the user agent brand list, and their associated full version number.
```

2021-12-24 01:48 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +Sec-CH-UA-Full-Version-List: "<brand>";v="<semantic version>", ...
```suggestion
Sec-CH-UA-Full-Version-List: "<brand>";v="<full version>", ...
```

2021-12-24 01:48 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +  - : A full semantic build number, such as 98.0.4750.0.
```suggestion
- `<full version>`
  - : A full version number, such as 98.0.4750.0.
```

2021-12-24 01:48 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version/index.md
> +The **`Sec-CH-UA-Full-Version`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's full semantic version string.
```suggestion
The **`Sec-CH-UA-Full-Version`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's full version string.
```

2021-12-24 01:49 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-full-version/index.md
> +  - : A string containing the full semantic version number, like "96.0.4664.93".
```suggestion
  - : A string containing the full version number, like "96.0.4664.93".
```

2021-12-24 01:54 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP Caching > Varying responses](/en-US/docs/Web/HTTP/Caching#varying_responses) and {{HTTPHeader("Vary")}}
@wbamberg See https://developer.mozilla.org/en-US/docs/Glossary/Client_hints#caching_and_client_hints

Basically any client hint potentially changes what resources are returned, so you "generally" want to also specify them in the `Vary` header to make sure that the different responses are cached ... unless they change too often in which case you might want to use some other link.

I agree that the original link is too "abstract". How about I replace this with https://developer.mozilla.org/en-US/docs/Glossary/Client_hints#caching_and_client_hints - or do you see that as unnecessary?

2021-12-24 03:12 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-arch/index.md
> +- [HTTP Caching > Varying responses](/en-US/docs/Web/HTTP/Caching#varying_responses) and {{HTTPHeader("Vary")}}
> @wbamberg See https://developer.mozilla.org/en-US/docs/Glossary/Client_hints#caching_and_client_hints
> 
> Basically any client hint potentially changes what resources are returned, so you "generally" want to also specify them in the `Vary` header to make sure that the different responses are cached ... unless they change too often in which case you might want to use some other link.
> 
> I agree that the original link is too "abstract". How about I replace this with https://developer.mozilla.org/en-US/docs/Glossary/Client_hints#caching_and_client_hints - or do you see that as unnecessary?

I think that's unnecessary since you're already linking to https://developer.mozilla.org/en-US/docs/Glossary/Client_hints. But I don't mind keeping the original `Vary` links in there if you want.

2021-12-24 03:18 UTC, wbamberg commented on files/en-us/web/http/headers/sec-ch-ua-full-version-list/index.md
> +The **`Sec-CH-UA-Full-Version-List`** [user agent client hint](/en-US/docs/Glossary/Client_hints#user-agent_client_hints) request header provides the user-agent's branding and full semantic version i
The spec doesn't call it a semantic version but a "full version" or a "build version" (https://wicg.github.io/ua-client-hints/#sec-ch-ua-full-version-list) and the examples it gives are not semantic versions:

>  "72.0.3245.12", "3.14159", or "297.70E04154A"

(semantic versions need to be X.Y.Z, and the different parts have particular semantics.)

Trying it out in https://user-agent-client-hints.glitch.me/?uach=Sec-CH-UA-Full-Version&uach=Sec-CH-UA-Full-Version-List, with Chrome, I see:

> Sec-CH-UA-Full-Version: "96.0.4664.93"

(or at least so I understand, but maybe I'm misunderstanding something?)

2021-12-24 04:36 UTC, wbamberg approved these changes
Thanks Hamish!

2021-12-24 04:37 UTC, merged

2021-12-27 01:27 UTC, hamishwillee commented
Thanks for review. Good to get this done!