Add note on actualBoundingBoxLeft that the value is calculated reversed
mdn/content pull request #11290
Opened 2021-12-18 04:09 UTC by vlwkaos

#### Summary

Add note on actualBoundingBoxLeft that the value is calculated reversed

#### Motivation

A value of actualBoundingBoxLeft can be confusing due to it not clarifying how it is calculated in reverse.

#### Supporting details

See comments on #11116 for more information.

#### Related issues

Fixes #11116 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-12-18 04:13 UTC, vlwkaos commented
@susbox 

Just added the comment from source code as a note. Do you mind reviewing the changes?
Your other suggestions are sound, but I think is out of scope for mdn/content.

2021-12-20 16:56 UTC, jpmedley requested changes
Thank you for helping us improve this. I have a couple of suggestions.

2021-12-20 16:56 UTC, jpmedley commented on files/en-us/web/api/textmetrics/actualboundingboxleft/index.md
> +> **Note:** `actualBoundingBoxLeft` measures the distance in the leftward direction, so its sign is reversed from our usual physical coordinates.
Instead of adding a note, why not take a shot at rewriting the description on line 14? If you do that, please keep the beginning that reads, "The read-only `actualBoundingBoxLeft` property of the {{domxref("TextMetrics")}} interface is". Consistency helps with scanability in reference documentation.

2021-12-20 16:56 UTC, jpmedley commented on files/en-us/web/api/textmetrics/index.md
> +
Whatever you do on the page for `actualBoundingBoxLeft`, please adapt for here. Since these are reference pages, we repeat the text virtually verbatim.

2021-12-22 09:56 UTC, vlwkaos commented on files/en-us/web/api/textmetrics/index.md
> +
Okay, I will work on it

2022-01-05 01:13 UTC, jpmedley approved these changes
Thank you and sorry for the delay. I've been out of the office.

2022-01-05 01:13 UTC, merged