DRAFT: aria-roles work
mdn/content pull request #11350
Opened 2021-12-20 19:17 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-12-26 22:12 UTC, ericwbailey approved these changes

2021-12-26 22:13 UTC, ericwbailey commented
@estelle The content looks good to me, but I'm seeing some merge conflicts that need fixing.

2021-12-26 22:13 UTC, ericwbailey requested changes
The content looks good to me, but I'm seeing some merge conflicts that need fixing.

2022-01-13 00:13 UTC, estelle commented
file was hand edited. Will close this and open two new PRs. https://github.com/mdn/content/pull/11965

2022-01-13 00:13 UTC, closed without merging