fix: link to The Service Worker Cookbook
mdn/content pull request #11396
Opened 2021-12-22 16:38 UTC by sherwino

#### Summary
This PR updates the link to the "The Service Worker Cookbook", an additional resource at the bottom of the docs.

The original domain `https://serviceworke.rs/` leads to a parked domain. 

Linked to an updated article written by Jake Archibald called "The Offline Cookbook", but the original site was an interactive site that seems like it is not being hosted at the moment.

#### Motivation
Was upset that the cookbook link lead to a parked domain.

#### Supporting details

- Original source code of the site shows the repo being active in 2019 https://github.com/mozilla/serviceworker-cookbook/

- Looked at cached version of site here: https://web.archive.org/web/20200313222303/https://serviceworke.rs/

#### Related issues
(Should I open an issue, and or try to re-host this resource?) 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2021-12-22 17:15 UTC, jpmedley requested changes

2021-12-22 17:15 UTC, jpmedley commented on files/en-us/web/api/serviceworker/index.md
> +- [The Offline (Service Worker) Cookbook](https://web.dev/offline-cookbook/)
```suggestion
- [The Offline Cookbook](https://web.dev/offline-cookbook/)(service workers)
```

2021-12-22 17:15 UTC, jpmedley commented on files/en-us/web/api/serviceworker/index.md
> +- [The Offline (Service Worker) Cookbook](https://web.dev/offline-cookbook/)
Please preserve the title.

2021-12-22 19:41 UTC, wbamberg commented
See also https://github.com/mdn/content/pull/10697 . FWIW I think your PR here is the right thing to do, and maybe some day we could transfer the original content of https://serviceworke.rs/ to MDN, as suggested in https://github.com/mozilla/serviceworker-cookbook/issues/312.

2021-12-23 14:38 UTC, jpmedley commented on files/en-us/web/api/serviceworker/index.md
> +- [The Offline (Service Worker) Cookbook](https://web.dev/offline-cookbook/)
This is not an idle suggestion. You shouldn't change someone else's title. You either need to edit the text to not use the title or you need to clarify it some other way, which is what I've done here.

2021-12-23 16:12 UTC, sherwino commented on files/en-us/web/api/serviceworker/index.md
> +- [The Offline (Service Worker) Cookbook](https://web.dev/offline-cookbook/)
You're entirely right, I shouldn't be changing the original title, it is misleading. Committed your suggestion, thank you.

2021-12-23 16:16 UTC, sherwino commented
> See also #10697 . FWIW I think your PR here is the right thing to do, and maybe some day we could transfer the original content of https://serviceworke.rs/ to MDN, as suggested in [mozilla/serviceworker-cookbook#312](https://github.com/mozilla/serviceworker-cookbook/issues/312).

That was going to be my next endeavor, to see how we could get that content back online, but I see that the community is already discussing the options.

In essence this PR is just an attempt to add a resource that isn't a broken link, and since Jake Archibald is one of the people that has published the most resources on the topic I thought it was a good alternative. 

The other option to replacing the broken link, is just removing it right?

2021-12-23 16:47 UTC, jpmedley approved these changes

2021-12-23 16:59 UTC, merged