GeolocationPosition.timestamp is time acquired
mdn/content pull request #11675
Opened 2022-01-03 01:05 UTC by hamishwillee

Fixes #11669

As noted in the spec, the timestamp is from when the device got the position, not when the object was created.

2022-01-03 01:07 UTC, hamishwillee commented
For a follow up PR .... This API refers to [DOMTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp). That is a typedef for a `unsigned long long`. It is removed from the listed WebIDL spec, but the [High Resolution time](https://www.w3.org/TR/hr-time-3/#the-epochtimestamp-typedef) spec notes that this has been renamed to `EpochTimeStamp`.

The question is, do we do a follow on to rename this to `EpochTimeStamp`, and should we move it in the tree under a high resolution time API? My hesitation is that there was some discussion that typedefs do not really "exist" for the purposes of users, and perhaps we should instead just note what the thing is in every case. I don't want to though, since this is used in many places.

Opinions @wbamberg ? It would be very easy to _just fix this case_ by removing the object name (and perhaps just indicating that it is an `unsigned long long`

2022-01-03 21:40 UTC, sideshowbarker commented on files/en-us/web/api/geolocationposition/timestamp/index.md
> +This is a value in in milliseconds (excluding leap seconds), relative to 01 January, 1970 00:00:00 UTC.
```suggestion
An {{domxref("EpochTimeStamp")}} object instance indicating the time that the position was acquired.
This is a value in in milliseconds (excluding leap seconds), relative to 01 January, 1970 00:00:00 UTC.
```

2022-01-03 21:41 UTC, sideshowbarker approved these changes

2022-01-08 04:32 UTC, wbamberg commented
> For a follow up PR .... This API refers to [DOMTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp). That is a typedef for a `unsigned long long`. It is removed from the listed WebIDL spec, but the [High Resolution time](https://www.w3.org/TR/hr-time-3/#the-epochtimestamp-typedef) spec notes that this has been renamed to `EpochTimeStamp`.
> 
> The question is, do we do a follow on to rename this to `EpochTimeStamp`, and should we move it in the tree under a high resolution time API? My hesitation is that there was some discussion that typedefs do not really "exist" for the purposes of users, and perhaps we should instead just note what the thing is in every case. I don't want to though, since this is used in many places.
> 
> Opinions @wbamberg ? It would be very easy to _just fix this case_ by removing the object name (and perhaps just indicating that it is an `unsigned long long`

I'm not sure :). I think I agree with you that having a single place where we define a timestamp typedef is likely to be the most useful thing for readers. So pragamtically I'm +1 on that. But I'm not sure where we currently stand on not wanting to have typedefs, and haven't really seen any written discussion of it let alone conclusions.

We *have* had some discussions about wanting to remove (some) dictionaries, but even there I'm not sure we have a clear rule. For example in https://github.com/mdn/content/pull/8846 I thought it better to keep the dictionary, as the docs work better with it than without it.

Maybe it's worth starting a discussion about it? I can also bring it up in the MDN editorial meeting on Monday.

For this PR specifically it looks like we'll also need a new page for `EpochTimeStamp` (and perhaps make DOMTimeStamp into a redirect to that new page).

2022-01-10 18:47 UTC, wbamberg commented
We talked about this in the MDN editorial meeting and everyone felt that having a dedicated page for typedefs was a good idea, even though this felt like a bit of an edge case.

We don't expect there are many pages like this, and we are deprecating similar things like [`DOMString`](https://developer.mozilla.org/en-US/docs/Web/API/DOMString), in which there's not really anything the typedef adds over just "string". But the case of DOMTimeStamp/EpochTimeStamp there is more to say so it is worth representing it as its own thing.

Also cc-ing @teoli2003 , as this links up with the DOM cleanup he is currently working on.

2022-01-11 05:27 UTC, hamishwillee commented
Thanks for the update @wbamberg ! I've added a doc for `EpochTimeStamp` and cross linked. Note that I didn't get rid of `DOMTimeStamp`. That term is likely still used for the same thing in other specs, so until we're sure it has disappeared we shouldn't do redirects etc.

This needs a new review please.

2022-01-11 19:17 UTC, wbamberg requested changes
I had a couple of comments. 
@teoli2003 , my comments are only about the new timestamp page, not about geolocation (which was the original impetus for this PR). Since  Hamish is out for a little while and this is I think part of your DOM work, would you like to work with me to finish this off? If you agree with my comments I'm happy to push the changes needed, or you could if you like.

2022-01-11 19:17 UTC, wbamberg commented on files/en-us/web/api/epochtimestamp/index.md
> +This was previously known as {{domxref("DOMTimeStamp")}}.
I think we should delete the page for DOMTimeStamp, and make it redirect here.

2022-01-11 19:17 UTC, wbamberg commented on files/en-us/web/api/epochtimestamp/index.md
> +> Where possible {{domxref("DOMHighResTimeStamp")}} should be used instead.
This is an unhelpful note for web developers. As a web developer I can't choose to use `DOMHighResTimeStamp` rather than `EpochTimeStamp` - I just have to use whichever one the API gives me. So there's nothing I can do about this note except feel bad.

2022-01-11 21:54 UTC, hamishwillee commented on files/en-us/web/api/epochtimestamp/index.md
> +> Where possible {{domxref("DOMHighResTimeStamp")}} should be used instead.
Yoiks. As you say.

2022-01-11 21:55 UTC, hamishwillee commented on files/en-us/web/api/epochtimestamp/index.md
> +> Where possible {{domxref("DOMHighResTimeStamp")}} should be used instead.
```suggestion
```

2022-01-11 22:00 UTC, hamishwillee commented on files/en-us/web/api/epochtimestamp/index.md
> +This was previously known as {{domxref("DOMTimeStamp")}}.
I was unsure - `DOMTimeStamp` originally referred to itself as a timestamp definition where specific details were covered in other specs (I think this was in WebIDL spec). It was removed from that spec. It was separately redefined in the high res time spec to be this epoctimestamp, with precise meaning. So my concern was that the redefinition might only work for this specific spec definition and not the definition in other specs. 

If you and @teoli2003 both agree, sure.

2022-01-12 01:14 UTC, wbamberg commented on files/en-us/web/api/epochtimestamp/index.md
> +This was previously known as {{domxref("DOMTimeStamp")}}.
Yes, I see your point. I'll defer to teoli on this.

2022-01-30 23:25 UTC, hamishwillee commented on files/en-us/web/api/epochtimestamp/index.md
> +This was previously known as {{domxref("DOMTimeStamp")}}.
@teoli2003 Ping!

2022-02-04 03:49 UTC, hamishwillee commented on files/en-us/web/api/epochtimestamp/index.md
> +This was previously known as {{domxref("DOMTimeStamp")}}.
@wbamberg As @teoli2003 has not replied, is there anyone else you'd trust to break deadlock? I still think it safer to leave as is and just merge.

2022-02-05 04:50 UTC, wbamberg approved these changes
OK, let's merge it! Thanks Hamish.

2022-02-05 04:51 UTC, merged