constructor page and main slug
mdn/content pull request #11817
Opened 2022-01-07 15:19 UTC by romulocintra

#### Summary

MDN Docs for https://github.com/tc39/proposal-intl-duration-format

#### Supporting details

- https://bugzilla.mozilla.org/show_bug.cgi?id=1648139
- https://bugs.chromium.org/p/v8/issues/detail?id=11660
- https://bugs.webkit.org/show_bug.cgi?id=214794

#### Related issues

https://github.com/tc39/ecma402-mdn/issues/22

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-23 00:02 UTC, wbamberg commented
@romulocintra , sorry to be so slow getting to this PR. It looks like this isn't implemented anywhere yet, so I'm not sure we are ready to have docs on MDN for it (also it's hard, for example, for me to check that the examples work properly).

Perhaps it would be best to reopen this PR when it is implemented in at least one browser?

2022-03-23 10:47 UTC, romulocintra commented
> @romulocintra , sorry to be so slow getting to this PR. It looks like this isn't implemented anywhere yet, so I'm not sure we are ready to have docs on MDN for it (also it's hard, for example, for me to check that the examples work properly).
> 
> Perhaps it would be best to reopen this PR when it is implemented in at least one browser?

Converted it to Draft, as soon we have an implementation will re-open it. thanks @wbamberg 

cc @sffc

2023-03-09 08:46 UTC, teoli2003 requested changes
Nice job!

I'm so excited to see this work getting closer to being ready to be merged as soon as a browser implements this feature. So, I went ahead with a first pass of reviews.

To save you time, I crafted suggestions for most comments:

- These are primarily typographic corrections.
- I also fixed some details to prevent our linters (Markdownlint, Prettier) from complaining.
- I removed `Tags:` as we removed them from the whole of MDN since the first version of this PR.
- I added `page-type:` instead, as this is what replaced them.

There will be a second pass later, but that way, all these typographic thingies won't get in the way.

Thanks a lot for your work.

2023-03-09 08:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/durationformat/index.md
> +        - "`auto`"
```suggestion
        - `"always"`
        - `"auto"`
```

2023-03-09 08:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/durationformat/index.md
> +        - "`numeric`"
```suggestion
        - `"long"`
        - `"short"`
        - `"narrow"`
        - `"numeric"`
```

2023-03-09 08:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/durationformat/index.md
> +        - "`auto`"
```suggestion
        - `"always"`
        - `"auto"`
```

2023-03-09 08:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/durationformat/index.md
> +        - "`numeric`"
```suggestion
        - `"long"`
        - `"short"`
        - `"narrow"`
        - `"numeric"`
```

2023-03-09 08:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/durationformat/index.md
> +        - "`auto`"
```suggestion
        - `"always"`
        - `"auto"`
```

2023-03-30 06:11 UTC, Josh-Cena approved these changes
This is implemented in Safari 16.4, and these docs look comparable to other `Intl` pages in terms of structure and content, so I think it's near ready to go.

2023-03-30 07:46 UTC, teoli2003 approved these changes

2023-03-30 07:47 UTC, teoli2003 commented
@romulocintra When you bring this PR out of draft (meaning you think it is ready), we can merge it. Note that in case, we can always continue work in follow-ups.

2023-03-30 09:14 UTC, merged

2023-03-30 09:14 UTC, teoli2003 commented
\o/

2023-03-30 09:15 UTC, romulocintra commented
> \o/

Thank you for following along, this was quite long journey thank you again

2023-03-30 09:20 UTC, Elchi3 commented
Is there no `supportedLocalesOf` here like there is for the other Intl APIs?

2023-03-30 09:22 UTC, romulocintra commented
> Is there no `supportedLocalesOf` here like there is for the other Intl APIs?

Yes, good catch, there is I'll prepare PR upcoming days for it - https://tc39.es/proposal-intl-duration-format/#sec-Intl.DurationFormat.supportedLocalesOf