Add other members for BeforeInstallPrompt event.
mdn/content pull request #11906
Opened 2022-01-11 04:01 UTC by amusaber950

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-06 09:44 UTC, teoli2003 requested changes
Thanks a lot!

The constructor page is not too far from our standard for landing, but the two members need more work.

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/BeforeInstallPromptEvent/index.md
> +title: BeforeInstallPromptEvent.BeforeInstallPromptEvent()
This should be:
```suggestion
title: BeforeInstallPromptEvent()
```

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/BeforeInstallPromptEvent/index.md
> +The **`BeforeInstallPromptEvent()`** constructor creates a new {{domxref("BeforeInstallPromptEvent")}} object which is fired at the {{domxref("Window.onbeforeinstallprompt")}} handler before a user i
Extraneous _<_
```suggestion
The **`BeforeInstallPromptEvent()`** constructor creates a new {{domxref("BeforeInstallPromptEvent")}} object which is fired at the {{domxref("Window.onbeforeinstallprompt")}} handler before a user is prompted to _install_ a web site to a home screen on mobile.
```

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/BeforeInstallPromptEvent/index.md
> +new BeforeInstallPromptEvent(type, int);
No final semi-colon:
```suggestion
new BeforeInstallPromptEvent(type, int)
```

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/BeforeInstallPromptEvent/index.md
> +  - :
We are missing the description, as well the one of int.

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/BeforeInstallPromptEvent/index.md
> +Fill in a simple example that nicely shows a typical usage of the API, then perhaps some more complex examples (see our guide on how to add [code examples](/en-US/docs/MDN/Contribute/Structures/Code_
This is the default block! We need an example.

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/platforms/index.md
> +The **`platforms`** property of the {{domxref("BeforeInstallPromptEvent")}} interface
Missing description here!

This is a stub, and we need it to be documented or removed of the PR, before merging.

2022-02-06 09:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/userChoice/index.md
> +
Same this page is a stub and we either want it to be filled, or removed from this PR.

2022-03-11 07:54 UTC, teoli2003 commented
@amusaber950 Do you think that you will be able to complete the missing part? If not, no worry, but I think I will close this PR then.

2022-04-11 03:33 UTC, sideshowbarker commented
@teoli2003, should we close this one?

2022-04-11 06:00 UTC, teoli2003 commented
Closing for lack on response. We will happily consider a new PR with the missing parts.

2022-04-11 06:00 UTC, closed without merging