Document result for Invalid Date
mdn/content pull request #11953
Opened 2022-01-12 13:40 UTC by sharils

#### Summary
Document the behaviour of valueOf based on ECMA 262 

#### Motivation
I had to read ECMA 262 to figure out what valueOf returns for an Invalid Date and hope this change helps other developers to skip reading the spec.

#### Supporting details
21.4.4.44 Date.prototype.valueOf ( ) https://tc39.es/ecma262/#sec-date.prototype.valueof

#### Related issues
N/A

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-01-13 16:56 UTC, Elchi3 requested changes
Thanks, good addition! 👍 
I made a minor suggestion mainly to link NaN.

2022-01-13 16:56 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/valueof/index.md
> +The number of milliseconds between 1 January 1970 00:00:00 UTC and the given date or NaN for Invalid Date.
```suggestion
The number of milliseconds between 1 January 1970 00:00:00 UTC and the given date, or {{jsxref("NaN")}} in case of an invalid date.
```

2022-01-14 14:04 UTC, sharils commented
> Thanks, good addition! 👍 I made a minor suggestion mainly to link NaN.

Thanks, this is better.

2022-01-14 14:10 UTC, Elchi3 approved these changes
Thanks and congratulations on landing your first change here

2022-01-14 14:10 UTC, merged