Add missing `showPicker()` method
mdn/content pull request #11951
Opened 2022-01-12 13:13 UTC by beaufortfrancois

Following with https://github.com/mdn/content/pull/11753, this PR adds a missing `showPicker()` method.

2022-01-12 16:54 UTC, jpmedley requested changes
This makes the verb tense consistent with the other items in the list.

2022-01-12 16:54 UTC, jpmedley commented on files/en-us/web/api/htmlinputelement/index.md
> +        Show a browser picker for date, time, color, and files.
```suggestion
        Shows a browser picker for date, time, color, and files.
```

2022-01-13 11:05 UTC, beaufortfrancois commented
@jpmedley Done. Thanks!

2022-01-13 14:48 UTC, jpmedley approved these changes

2022-01-13 14:48 UTC, merged