Adding documentation to Gamepad vibrationActuator and playEffect
mdn/content pull request #11967
Opened 2022-01-13 00:51 UTC by gbaptista

#### Summary

Adding documentation to `Gamepad.vibrationActuator` and `GamepadHapticActuator.playEffect()` following the current [Gamepad Haptics API proposal](https://docs.google.com/document/d/1jPKzVRNzzU4dUsvLpSXm1VXPQZ8FP-0lKMT-R_p-s6g/edit#) implemented in browsers and providing examples of its usage.

#### Motivation

`vibrationActuator` and `playEffect` are available features on browsers, and besides the proposal document and some random issues on Github, there's no documentation available about them.

#### Supporting details

- [Gamepad Haptics API proposal](https://docs.google.com/document/d/1jPKzVRNzzU4dUsvLpSXm1VXPQZ8FP-0lKMT-R_p-s6g/edit#)
- [Vibrate feature for Gamepad #19](https://github.com/w3c/gamepad/issues/19#issuecomment-321424335)
#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-01-18 15:18 UTC, jpmedley requested changes
Hi,

Thank you for your submission. These are the cleanest drafts I've seen in some time. Nice Work!

I found a few things that need to change. I appreciate your time.

Joe

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +gamepadHapticActuatorInstance.playEffect(type, params).then(function(result) { /* ... */ });
```suggestion
playEffect(type, params);
```

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +gamepadHapticActuatorInstance.playEffect(type, params).then(function(result) { /* ... */ });
https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections#concise_syntax_blocks

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +  - : A string representing the desired effect. This can vary depending on the hardware type, possible values are "dual-rumble" or "vibration".
```suggestion
  - : A string representing the desired effect. This can vary depending on the hardware type. Possible values are "dual-rumble" or "vibration".
```

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +  - : A string representing the desired effect. This can vary depending on the hardware type, possible values are "dual-rumble" or "vibration".
>This can vary depending on the hardware type.

Are you saying that either vibration or dual-rumble aren't available on some devices?

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +> **Note:** Repeated calls to `playEffect()` override the previous calls if they are still ongoing.
```suggestion
> **Note:** A new call to `playEffect()` overrides a previous ongoing call.
```

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +> **Note:** Repeated calls to `playEffect()` override the previous calls if they are still ongoing.
my issue with the previous wording is that it implies multiples where none are possible. For example, a call can't override 'previous calls' because (if I'm understanding the logic correct) override means there can be only one effect going at a time. If you don 't see what I'm getting at, please ask.

2022-01-18 15:18 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +A promise that resolves with a value of `true` when the playEffect has successfully completed.
```suggestion
A promise that resolves with `true` when the playEffect successfully completes.
```

2022-02-12 15:16 UTC, gbaptista commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +  - : A string representing the desired effect. This can vary depending on the hardware type, possible values are "dual-rumble" or "vibration".
My understanding is:

A Gamepad may not have a haptic actuator. If the gamepad has a haptic actuator, it will be either a "vibration" or a "dual-rumble" type.

The type of the haptic actuator defines what kind of effects are supported. The possible effects may be interchangeable in the future, regardless of actuator type, but that's not specified in the spec today.

The [excerpts](https://docs.google.com/document/d/1jPKzVRNzzU4dUsvLpSXm1VXPQZ8FP-0lKMT-R_p-s6g/edit#) that led me to this interpretation:

> _Two types of haptic actuators are defined. A "vibration" actuator is a haptic feedback device that supports vibration. This type of actuator is appropriate for gamepads with a single vibration motor for rumble effects. It can also be used for vibration actuators that only vibrate part of the gamepad (eg, a single trigger or button). A "dual-rumble" actuator represents the typical low-frequency/high-frequency rumble configuration found on most modern gamepads._

> _In the initial version of the API, only dual-rumble effects are supported. It may be desirable to allow dual-rumble effects to be played back on a "vibration"-type actuator, but how this might be accomplished is outside the scope of this specification._

Does it make sense?

2022-02-14 16:57 UTC, jpmedley commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +  - : A string representing the desired effect. This can vary depending on the hardware type, possible values are "dual-rumble" or "vibration".
I updated the suggestion. Please take a look.

2022-02-14 17:09 UTC, gbaptista commented on files/en-us/web/api/gamepadhapticactuator/playeffect/index.md
> +  - : A string representing the desired effect. This can vary depending on the hardware type, possible values are "dual-rumble" or "vibration".
Perfect!

2022-02-14 17:52 UTC, jpmedley approved these changes
Thank you for your help and patience.

2022-02-15 14:43 UTC, merged