Make the PWA code more modern and readable
mdn/content pull request #1207
Opened 2021-01-12 10:08 UTC by ninofiliu

https://github.com/mdn/pwa-examples/pull/15 has just been merged: it updates the js13kgames example web app, used in the PWA guides, so that

- it uses modern syntax (fat arrows instead of functions, consts and lets over vars, ...)
- it fixes lint issues (variables not used, non-uniform indentation, ...)
- it is more readable, mainly through the rewrite of chained promises into async/await

This PR updates the MDN guides that reference these example app with the new code, in other words the code has already been reviewed, this PR only copy-pasted it at the right places and excaped the `<` and `>`

2021-01-31 15:31 UTC, Ryuno-Ki commented
@chrisdavidmills Friendly ping

2021-01-31 15:43 UTC, Ryuno-Ki requested changes

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/app_structure/index.html
> +    if (r) return r;
Personally, I feel more „safe” with curly braces, even if the code branch consists of only one line. (Not sure, whether the linter will flag this).

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +for (let i = 0; i < games.length; i++) {
Is there a reason why you don't use `&lt;` here?

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    await cache.addAll(contentToCache);
That was `return`ed before (I think, `return await` is not needed, since async functions always return a Promise by definition).

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    if (r) return r;
Same as above (regarding curly braces).

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +  console.log('[Service Worker] Install');
That's new.

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    const cache = await caches.open(cacheName);
Where's `cacheName` defined?

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +      if (key === cacheName) return;
Same as before (regarding curly braces).

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +      await caches.delete(key);
That used to be `return`ed.

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">const button = document.getElementById('notifications');
I think, the `notranslate` is automatically added by Yari and can be dropped here.

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">const cacheName = 'js13kPWA-v1';
Same regarding `notranslate`.

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">self.addEventListener('install', (e) =&gt; {
Same regarding `notranslate`.

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">self.addEventListener('fetch', (e) =&gt; {
Same regarding `notranslate`

2021-01-31 15:43 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +    if (r) return r;
Same regarding curly braces

2021-01-31 15:43 UTC, Ryuno-Ki commented
@ninofiliu I went over this PR and left some comments. Chris might find some more.

2021-02-01 09:24 UTC, chrisdavidmills commented
I've just not found the time to review this. Sorry @ninofiliu !

@Ryuno-Ki it seems like you've given this a fairly thorough review, thanks so much! I've removed myself from the reviewers list to give you the sole credit for doing this. Are you ok with that, or do you think I still need to look at it?

2021-02-01 18:40 UTC, Ryuno-Ki commented
> Are you ok with that, or do you think I still need to look at it?

I noticed that you're pretty busy and tried to lift some weights from your shoulders. Then, the pedantic in me took over ^^"

I think, we will be faster with me reviewing this code. If something comes up after merge, we can open another PR to address it :-)

2021-02-01 18:51 UTC, chrisdavidmills commented
> > Are you ok with that, or do you think I still need to look at it?
> 
> I noticed that you're pretty busy and tried to lift some weights from your shoulders. Then, the pedantic in me took over ^^"
> 
> I think, we will be faster with me reviewing this code. If something comes up after merge, we can open another PR to address it :-)

That's really great. Thank you so much for your help, @Ryuno-Ki !

2021-02-08 16:12 UTC, Ryuno-Ki commented
@ninofiliu Friendly ping :)

2021-02-08 16:57 UTC, ninofiliu commented
@Ryuno-Ki yep I'll get back to this once I'm done with other things! dw I didn't forget about this

2021-02-08 17:23 UTC, Ryuno-Ki commented
Glad to hear that!
If you don't mind, I'll send another reminder in about one week's time.

2021-03-04 13:31 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/app_structure/index.html
> +    if (r) return r;
fixed in https://github.com/mdn/content/pull/1207/commits/dbf380c5ed178013e656f541f484d502e8c4b1a1

I'm resolving all similar convos except for this one

2021-03-04 13:33 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +for (let i = 0; i < games.length; i++) {
Nope I just forgot, thanks for catching that! https://github.com/mdn/content/pull/1207/commits/afafdbb467f2c9cedeff9a209551d7f01c541582

2021-03-04 13:36 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    await cache.addAll(contentToCache);
Yes but that's precisely what what confusing about the previous syntax, we returned the promised to await it, but we don't do anything with the resolved value

With this refactoring, the install event awaits for the caching of assets, but we don't return anything we won't use, which is clearer imho

Btw [addAll returns undefined](https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll#return_value) so this is a strictly ISO refactoring

2021-03-04 13:36 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +  console.log('[Service Worker] Install');
oops thanks for cacthing that https://github.com/mdn/content/pull/1207/commits/6b8652e12fc509f31eb47c756a58ed230633255f

2021-03-04 13:37 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    const cache = await caches.open(cacheName);
here https://github.com/mdn/content/pull/1207/files#diff-6741f36163fc2d2ceb45ea870dcfba5bfe5d8f273505c9d260ec782364e5ad7bR68

2021-03-04 13:39 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +      await caches.delete(key);
Same, it was confusing to return a promise just to await it and do nothing with the returned value - this way we only await for the promise

2021-03-04 13:40 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">const button = document.getElementById('notifications');
While I rebased to fix conflicts, I removed them!

2021-03-04 13:40 UTC, ninofiliu commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +<pre class="brush: js notranslate">const button = document.getElementById('notifications');
Resolving all similar convos

2021-03-04 13:41 UTC, ninofiliu commented
@Ryuno-Ki sorry for the delay, here's the changes you requested! I rebased to fix conflicts, only the last three commits are new

2021-03-04 22:27 UTC, Ryuno-Ki commented
@ninofiliu I went over the comments so far (you can mark all with a :+1: as resolved), but have not enough brain power to review the code at the moment.
I'll leave this as unread for me, so I can pick it up tomorrow morning (CET timezone).

2021-03-05 07:20 UTC, Ryuno-Ki approved these changes
Let's get this in!

In case you want to improve on the code (instead of modernising it), I let some hints on what to pick up.

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/app_structure/index.html
> +    if (r) { return r; }
:clap:

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/offline_service_workers/index.html
> +    if (r) { return r; }
:raised_hands:

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +  &lt;img src='data/img/placeholder.png' data-src='data/img/SLUG.jpg' alt='NAME'&gt;
Here, the logic differs (`src` vs. `data-src`).
I'm assuming, it adds lazy-loading. Since that's to be encouraged, I'll accept the change. I want to highlight it, though.

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +    .replace(/SLUG/g, games[i].slug)
While this would work, it is a repeated object lookup. You could have a line (follow-up PR?) above `let entry` which reads `const game = games[i]` to avoid this.

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +  content += entry;
Depending on this size of the `games` array, this could lead to memory pressure.
An alternative would be to use `Array.prototype.map` to get `entry`, and join them into `content`.

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +  content += entry;
That being said, it replicates the old logic, so it won't block a PR for me.
If you think about making a follow-up PR, I'd be pleased to see this covered :)

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +  const notifTitle = games[randomItem].name;
Like mentioned before, this will cause repeated object lookups. A better way might be to assign `games[randomItem]` to a variable and use this instead.
(Not relevant for this PR, but might be handy in a follow-up one).

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +    gamesImages.push(`data/img/${games[i].slug}.jpg`);
You're replicating the old logic here, so that's fine.
But `gamesImages` could as well be the result of an `games.map()` :)
(Follow-up PR?)

2021-03-05 07:20 UTC, Ryuno-Ki commented on files/en-us/web/progressive_web_apps/structural_overview/index.html
> +    if (r) { return r; }
:muscle:

2021-03-05 07:20 UTC, merged

2021-03-05 07:21 UTC, Ryuno-Ki commented
Thank you so, so much, @ninofiliu! It's great to have you onboard at mdn/content :tada: