Fix "auto" subsection link
mdn/content pull request #123
Opened 2020-11-21 22:37 UTC by gdsimoes

The "auto" subsection didn't have an id attribute so the link was broken.

2020-11-23 09:06 UTC, chrisdavidmills commented
Hi @gdsimoes !

So, by "the link", you're referring to the fragment link slightly above the values list?

To be honest, I'd suggest that you fix this by just getting rid of the link, not adding an ID to the description term. We don't commonly have IDs in our property value lists like this, and the link is not really very useful — it's not as if the `auto` description is hard to find from the location of the link.

2020-11-24 04:57 UTC, gdsimoes commented
Hello @chrisdavidmills !

I created a new commit to get rid of the link. As you might have guessed, I am a newbie at this so I don't know how to remove the previous commit. Should I create a new pull request?

2020-11-24 10:42 UTC, chrisdavidmills commented
Hi @gdsimoes !

Your update looks good. And no, you don't need to create a new pull request. Any further pushes you make to this existing pull request will update it's previous state, adding the new changes on top.

So all you need to do now is remove the ` id="auto"` that you previously added, and we'll be good to go.

2020-11-24 10:42 UTC, chrisdavidmills requested changes
Change requested in above comment.

2020-11-25 05:18 UTC, gdsimoes commented
Hi @chrisdavidmills !

I removed the `id="auto"` as you said, and now I believe everything is correct. Thank you for your patience!

2020-11-25 09:49 UTC, chrisdavidmills approved these changes
That is perfect. Thanks so much for your contribution!

2020-11-25 09:49 UTC, merged