Clarifying the behavior of webRequest.filterResponseData
mdn/content pull request #12349
Opened 2022-01-22 15:46 UTC by rebloor

#### Summary
Provides clarification that the stream filter gives the an extension complete control over web request data, and must, at a minimum, implement an event to pass through the stream data.

#### Motivation
To clarify the behavior of stream data following Bug [1738877](https://bugzilla.mozilla.org/show_bug.cgi?id=1738877) Warn on badly used browser.webRequest.filterResponseData.

#### Metadata
This PR…

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-01-23 13:41 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/streamfilter/index.md
> +You can think of the stream filter as sitting between the networking stack and the browser's rendering engine. The filter is passed HTTP response data as it's received from the network. It can examin
Just like the other page, this new addition is too specific. The rest of this section goes in detail on how the filter can be used. The purpose of this paragraph is to succinctly explain the filter's role. And note that "must have ondata listener to process the stream" can also be read as not having the listener will avoid processing of the stream, i.e. leave the stream unmodified. That's not the case.

If anything, I'd write a message along the lines of the following:

> The filter has full control over the response body, and the default behavior without any listeners or `write` calls is to have a never-closing stream without content.

2022-01-23 23:06 UTC, rebloor commented
Thanks for the feedback @Rob--W, hopefully, I have addressed all your point.

2022-01-24 11:12 UTC, Rumyra approved these changes

2022-01-24 11:12 UTC, Rumyra commented
Approved so you can merge when you're ready :)

2022-01-24 11:14 UTC, Rob--W commented
Please don't merge until I have completed my review.

It has happened before that a PR was merged while there were unresolved issues, what can I do to stop that from happening?

2022-01-24 20:39 UTC, Rob--W requested changes

2022-01-24 20:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +var filter = browser.webRequest.filterResponseData(details.requestId);
This example is not complete without the source of `details.requestId`.

Wrap the logic in a webRequest event listener, or at least prepend a comment that explains where `details` comes from.

I see that the other example below uses `let` instead of `var`, so for consistency let's do that too.

2022-01-24 20:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/streamfilter/index.md
> +- {{WebEXTAPIRef("webRequest.StreamFilter.ondata", "ondata")}} when some response data has been received by the filter and is available to be examined or modified.
Remove trailing space.

2022-01-26 01:33 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/streamfilter/index.md
> +- {{WebEXTAPIRef("webRequest.StreamFilter.ondata", "ondata")}} when some response data has been received by the filter and is available to be examined or modified.
Done

2022-01-26 01:34 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +var filter = browser.webRequest.filterResponseData(details.requestId);
Added a comment about the source of `details` and changed `var` to `let`.

2022-02-06 21:37 UTC, rebloor commented
@Rob--W ping

2022-02-07 00:48 UTC, Rob--W commented
Thanks for the ping.

I started a review, but Github is currently having issues that prevents me from submitting more comments. I'll resume my review in two days.

2022-02-07 00:49 UTC, Rob--W reviewed
Test

2022-02-07 00:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +This example shows a minimal implementation that passes through the stream data and closes the filter stream when the stream finishes receiving data. The code would be called from a {{WebExtAPIRef("w
typo "listner"; provides -> -provided?

2022-02-07 06:46 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +This example shows a minimal implementation that passes through the stream data and closes the filter stream when the stream finishes receiving data. The code would be called from a {{WebExtAPIRef("w
Fix the spelling error, however, "provides" is correct

2022-02-07 06:47 UTC, rebloor commented
> I started a review, but Github is currently having issues that prevents me from submitting more comments. I'll resume my review in two days.

How annoying, I'll look forward to further comments in a day or two.

2022-02-07 21:22 UTC, Rob--W approved these changes
Just one small change, and then it's good to merge. Thanks!

2022-02-07 21:22 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +  console.log(`filter.ondata received ${e.data.byteLength} bytes`);
```suggestion
  console.log(`filter.ondata received ${event.data.byteLength} bytes`);
```

2022-02-11 15:51 UTC, merged