fix: fixable flaws in Glossary P-X
mdn/content pull request #1236
Opened 2021-01-12 21:53 UTC by nschonni

2021-01-12 21:59 UTC, nschonni commented on files/en-us/glossary/state_machine/index.html
> +<p><img alt="" src="https://s14.postimg.org/wqu45yc9d/statemachine1.png"></p>
Not sure if it should have tried to pull this image locally or now

2021-01-12 21:59 UTC, nschonni commented on files/en-us/glossary/xinclude/index.html
> +<p>Note also that if you wish to allow xml:base, you will need the <a href="/en-US/docs/Archive/Add-ons/Code_snippets/XML/base_function">xml:base function</a>, and the line beginning <code>var href =
Manually adjusted after searching for Archive content

2021-01-12 21:59 UTC, nschonni commented on files/en-us/glossary/xlink/index.html
> +<p>XLink is used in <a href="/en-US/docs/Web/SVG">SVG</a>, <a href="/en-US/docs/Web/MathML">MathML</a>, and other important standards.</p>
Manually adjusted since the "fix" missed adding the "docs/Web" part of the URL

2021-01-12 21:59 UTC, nschonni commented on files/en-us/glossary/xlink/index.html
> + <li><a href="/en-US/docs/Web/XML">XML</a></li>
Manually adjusted all these since the content is mostly gone

2021-01-13 10:58 UTC, chrisdavidmills requested changes
These look mostly good. The only bit of feedback I have here is that xref macro calls should have their slug segments separated by a dot, not a slash, e.g. {{domxref("NavigatorID/userAgent")}} should be {{domxref("NavigatorID.userAgent")}}.

The macro automatically replaces the dot with a slash when creating the URL for the resulting link, and we visually want it to display with a dot, not a slash, on the link text.

2021-01-13 17:11 UTC, nschonni commented
@chrisdavidmills that was the "fix" that Yari did on it's own. i've added the override to give the dotted name as the display parameter, or do you want me to just undo the change

2021-01-14 09:33 UTC, chrisdavidmills commented
> @chrisdavidmills that was the "fix" that Yari did on it's own. i've added the override to give the dotted name as the display parameter, or do you want me to just undo the change

Adding the override would be good for now, yes. I'll raise a yari issue to get this fixed, as it shouldn't be doing that.

2021-01-20 10:16 UTC, chrisdavidmills approved these changes

2021-01-20 10:16 UTC, merged