Update option doc with styling information
mdn/content pull request #12446
Opened 2022-01-27 09:45 UTC by frankie303

#### Summary and Motivation

I realized the lack of information about styling of `option` element and added a small explanation with related link.

This PR…
-->
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-01-27 23:43 UTC, wbamberg requested changes
Thanks for your PR, @frankie303 !

It's definitely good to say something about styling here, but it should be in its own section headed "Styling with CSS", placed after "Attributes" and before "Examples". See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#styling_with_css for example.

2022-01-27 23:43 UTC, wbamberg commented on files/en-us/web/html/element/option/index.md
> +Styling the **`<option>`** element is highly limited. Options don't inherit the font set on the parent. In Firefox, only [`color`](/en-US/docs/Web/CSS/color) and [`background-color`](/en-US/docs/Web/
Link text like "here" is not accessible, so it would be better to use descriptive text, like "our guide to advanced form styling".

2022-01-29 10:48 UTC, frankie303 commented on files/en-us/web/html/element/option/index.md
> +Styling the **`<option>`** element is highly limited. Options don't inherit the font set on the parent. In Firefox, only [`color`](/en-US/docs/Web/CSS/color) and [`background-color`](/en-US/docs/Web/
Thanks @wbamberg for your comments! I updated it.

2022-01-31 23:41 UTC, wbamberg approved these changes
👍 nice, thanks for the update @frankie303 !

2022-01-31 23:42 UTC, merged