Update Serial API for new-style event pages
mdn/content pull request #12539
Opened 2022-01-31 16:15 UTC by Elchi3

This PR updates the Serial API for new-style event pages. (see the [template](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_event_subpage_template))

Commands used:

```
yarn content move Web/API/SerialPort/onconnect Web/API/SerialPort/connect_event
yarn content move Web/API/SerialPort/ondisconnect Web/API/SerialPort/disconnect_event
yarn content delete Web/API/Serial/onconnect --redirect=/en-US/docs/Web/API/SerialPort/connect_event 
yarn content delete Web/API/Serial/ondisconnect --redirect=/en-US/docs/Web/API/SerialPort/disconnect_event
```

As discussed in https://github.com/mdn/browser-compat-data/pull/13925, `SerialPort` bubbles to `Serial` and so I documented these two events only under `SerialPort` and the `Serial` page just contains them as links but not as sub pages to avoid duplication.

2022-02-02 03:47 UTC, wbamberg requested changes
This looks fine, except that the examples are AFAICT for `Serial`, not `SerialPort`, and as we discussed, the `event.port` thing is odd.

2022-02-02 03:47 UTC, wbamberg commented on files/en-us/web/api/serialport/connect_event/index.md
> +Bubbles to {{domxref("Serial")}} (`event.port` is available representing the {{domxref("SerialPort")}}).
As we said, it's weird that this is an `Event` but has a `port` property.

2022-02-02 03:47 UTC, wbamberg commented on files/en-us/web/api/serialport/connect_event/index.md
> +navigator.serial.addEventListener('connect', event => {
This looks like an example for `Serial` not `SerialPort`.

2022-02-02 03:47 UTC, wbamberg commented on files/en-us/web/api/serialport/disconnect_event/index.md
> +Bubbles to {{domxref("Serial")}} (`event.port` is available representing the {{domxref("SerialPort")}}).
Same comment as for `connect`.

2022-02-02 03:47 UTC, wbamberg commented on files/en-us/web/api/serialport/disconnect_event/index.md
> +navigator.serial.addEventListener('disconnect', event => {
Again, same comment as for `connect`.

2022-02-02 08:26 UTC, teoli2003 commented
Thinking out loud about bubbling.

If I understand well, the hierarchy here is: (- means "contains", not "inherits")

(`Worker`)`Navigator` - `Serial` - `SerialPort`.

So an event will be thrown to `SerialPort`, then bubble to `Serial`, and then to (Worker)Navigator. I see they are listed in Serial, but not on (Worker)Navigator.

I think this may be a too large list if we do the same in Navigator. But maybe we could have in (Worker)Navigator:

=== Events ===
_Events bubbling from `Serial` may be dispatched to this object._ (We don't need the detailed list there)

And in Serial:

_If not caught, these events will bubble up the tree (to `Navigator` or `WorkerNavigator`)._

(Bubbling in the DOM Tree would have: _If not caught, these events will bubble up the DOM Tree_)

I think we need to know if an event will bubble if not caught on a specific object.

2022-02-02 08:27 UTC, teoli2003 commented on files/en-us/web/api/serialport/connect_event/index.md
> +Bubbles to {{domxref("Serial")}} (`event.port` is available representing the {{domxref("SerialPort")}}).
This is needed if it bubbles up to `Navigator`or `Serial`, so that the event handler knows which port it relates to.

2022-02-02 08:36 UTC, teoli2003 commented
I would add that it is not trivial that non-caught bubbling events on `Serial` will bubble to `Navigator` (or `WorkerNavigator`)

2022-02-02 11:48 UTC, Elchi3 commented on files/en-us/web/api/serialport/connect_event/index.md
> +Bubbles to {{domxref("Serial")}} (`event.port` is available representing the {{domxref("SerialPort")}}).
It is weird and I think I got this wrong.  In fact, I think the spec is wrong. I filed https://github.com/WICG/serial/pull/159

See also https://web.dev/serial/#connection-disconnection which says that this used to be a `SerialConnectionEvent` with a `port` property. That's no longer the case though.

2022-02-02 15:52 UTC, Elchi3 commented on files/en-us/web/api/serialport/connect_event/index.md
> +navigator.serial.addEventListener('connect', event => {
I've now made two examples to show both.

2022-02-03 11:18 UTC, Elchi3 commented
Thanks @wbamberg and @teoli2003, ready for re-review. Corrected the bubbling section and added examples for showing both, bubbling to `Serial` and non-bubbling with `SerialPort`.

2022-02-03 19:03 UTC, wbamberg approved these changes
👍 lgtm, thanks Florian!

2022-02-03 19:04 UTC, teoli2003 approved these changes

2022-02-03 19:18 UTC, merged