Update AbstractRanges
mdn/content pull request #12532
Opened 2022-01-31 10:47 UTC by teoli2003

#### Summary
This is part of the DOM project ( #9740 )

It updates `AbstractRange` to the latest standard.

Note this is an abstract class, so more information will be in the descendant of these classes.

2022-02-01 00:05 UTC, wbamberg requested changes
Thanks @teoli2003 ! Just a few copy-edit type things.

2022-02-01 00:05 UTC, wbamberg commented on files/en-us/web/api/abstractrange/index.md
> +  - : A Boolean value which is `true` if the range is _collapsed_. A collapsed range is a rangte whose start position and end position are the same, resulting in a zero-character-long range.
```suggestion
  - : A Boolean value which is `true` if the range is _collapsed_. A collapsed range is a range whose start position and end position are the same, resulting in a zero-character-long range.
```

2022-02-01 00:05 UTC, wbamberg commented on files/en-us/web/api/abstractrange/index.md
> +  - : An integer value indicating the offset, in characters, from the beginning of the node's contents to the last character of the contents referred to  by the range object. This value must be less
```suggestion
  - : An integer value indicating the offset, in characters, from the beginning of the node's contents to the last character of the contents referred to by the range object. This value must be less than the length of the node indicated in `startContainer`.
```

2022-02-01 00:05 UTC, wbamberg commented on files/en-us/web/api/abstractrange/collapsed/index.md
> +let isCollapsed = range.collapsed
Some of these have  semicolons at the end and some don't I think if these are in "Examples" they should probably all have semicolons.

2022-02-01 07:52 UTC, teoli2003 commented on files/en-us/web/api/abstractrange/collapsed/index.md
> +let isCollapsed = range.collapsed
Added.

2022-02-01 07:56 UTC, teoli2003 commented
Good catch for the semi-colons in one-line example!

2022-02-02 03:37 UTC, wbamberg commented on files/en-us/web/api/abstractrange/index.md
> +In this example, the start of the specified range is found within the text node below the section's heading, which means that the new `DocumentFragment` will need to contain an {{HTMLElement("Heading
```suggestion
In this example, the start of the specified range is found within the text node below the section's heading, which means that the new `DocumentFragment` will need to contain an {{HTMLElement("Heading_Elements", "h2")}} and, below it, a text node.
```

2022-02-02 18:27 UTC, wbamberg approved these changes
👍 thanks !

2022-02-02 18:27 UTC, merged