Extend Web/CSS/Class_selectors
mdn/content pull request #12558
Opened 2022-01-31 22:42 UTC by WinterSilence

#### Summary

Added example discovering how merges properties of classes declared in attribute "class".

#### Motivation

This note helps to juniors avoid a popular mistake.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-01-31 23:33 UTC, wbamberg requested changes
Thanks for your PR, @WinterSilence ! I had a couple of suggestions.

2022-01-31 23:33 UTC, wbamberg commented on files/en-us/web/css/class_selectors/index.md
> +If the property is declared in several classes of element, then using value of the last declared class in CSS. The order of the class names in the "class" attribute is not important in this case.
```suggestion
If an element a `class` attribute containing multiple classes, and the CSS has conflicting rules for each class, then the rule that is applied is the last rule given in the CSS. The order of the classes in the `class` attribute is not important in this case.
```

something like this is clearer?

2022-01-31 23:33 UTC, wbamberg commented on files/en-us/web/css/class_selectors/index.md
>  {{EmbedLiveSample('Examples')}}
```suggestion
{{EmbedLiveSample('Examples', '600', '260')}}
```

(let's make the example iframe a bit taller, so we can see these new lines of output)

2022-02-01 00:02 UTC, WinterSilence commented on files/en-us/web/css/class_selectors/index.md
> +If the property is declared in several classes of element, then using value of the last declared class in CSS. The order of the class names in the "class" attribute is not important in this case.
@wbamberg this doc using term "style properties" instead "rules"

2022-02-01 00:13 UTC, wbamberg commented on files/en-us/web/css/class_selectors/index.md
> +If the property is declared in several classes of element, then using value of the last declared class in CSS. The order of the class names in the "class" attribute is not important in this case.
I think "conflicting rules" is more comprehensible here, but if you have an alternative that seems better I'm happy to hear it.

2022-02-01 00:28 UTC, WinterSilence commented on files/en-us/web/css/class_selectors/index.md
> +If the property is declared in several classes of element, then using value of the last declared class in CSS. The order of the class names in the "class" attribute is not important in this case.
@wbamberg me too, but not here - need create new  PR and replace "style properties" to "rules" globally to not confuse readers.

2022-02-02 00:22 UTC, wbamberg commented on files/en-us/web/css/class_selectors/index.md
> +If an element a `class` attribute containing several classes, and they defines same property/rule, then his value set by latest class declared in the CSS. The order of the class names in the `class`
Again, this sentence is very hard to understand. I do think my original suggestion is fine here.

2022-02-02 01:59 UTC, WinterSilence commented on files/en-us/web/css/class_selectors/index.md
> +If an element a `class` attribute containing several classes, and they defines same property/rule, then his value set by latest class declared in the CSS. The order of the class names in the `class`
@wbamberg your version not correct:

> conflicting rules

it's not conflict

> each class

not each

>  very hard to understand

Yes. therefore, the text is provided with a simple example.

2022-02-05 03:30 UTC, estelle commented on files/en-us/web/css/class_selectors/index.md
> +If an element a `class` attribute containing several classes, and they defines same property/rule, then his value set by latest class declared in the CSS. The order of the class names in the `class`
```suggestion
The order of the class names in a `class` attribute containing multiple space-separated classes has no impact on [specificity](/en-US/docs/Web/CSS/Specificity) or the [cascade](/en-US/docs/Web/CSS/Cascade).
```

2022-02-05 03:31 UTC, estelle commented on files/en-us/web/css/class_selectors/index.md
> +If an element a `class` attribute containing several classes, and they defines same property/rule, then his value set by latest class declared in the CSS. The order of the class names in the `class`
hi @WinterSilence. Feel free to commit my suggested rewrite if that is what you were trying to say.

2022-02-05 09:30 UTC, WinterSilence commented on files/en-us/web/css/class_selectors/index.md
> +If an element a `class` attribute containing several classes, and they defines same property/rule, then his value set by latest class declared in the CSS. The order of the class names in the `class`
@estelle it's too not true - class order impact on specificity, but cascade have high priority

2022-02-15 13:15 UTC, closed without merging