DRAFT: New page: radiogroup role
mdn/content pull request #12573
Opened 2022-02-01 03:52 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-06 20:25 UTC, ericwbailey requested changes
A few requests here, and a third apology for the delay 😓

2022-02-06 20:25 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +When using HTML's native radio button, [`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio),  the radio group is defined by giving each of radio buttons in the group the same [`name`](/
```suggestion
When using HTML's native radio button, [`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio), the radio group is defined by giving each of radio buttons in the group the same [`name`](/en-US/docs/Web/HTML/Element/input#attr-name). Once a radio group is established, selecting any radio button in that group automatically deselects any currently-selected radio button in the same group.
```

2022-02-06 20:25 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +User interactions for radio groups must replicate the user interaction of a user entering into a group of same-named HTML radio buttons. Keyboard events for tabs, space, and arrow keys must be captur
How should focus be managed? I think that can be a new paragraph following this one.

2022-02-06 20:25 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +The `radiogroup` role is a group of radio buttons.
Can we update this to be a little more clear about what a radio button is, compared to a radio input? I think that nuance might be lost on some readers.

2022-02-10 04:41 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +The `radiogroup` role is a group of radio buttons.
I made the `radio` look like radio, and then in the rest of the document updated all the radio input references to be clearly inputs. I didn't put it in the first line b/c the first line is just a summary, not an explanation.

2022-02-10 04:44 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +User interactions for radio groups must replicate the user interaction of a user entering into a group of same-named HTML radio buttons. Keyboard events for tabs, space, and arrow keys must be captur
linking to https://usability.yale.edu/web-accessibility/articles/focus-keyboard-operability for now. Will be writing a focus management MDN soon.

2022-02-13 21:55 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  <ul id="radioGroup">
generally you wouldn't want or need to put radio buttons into a list.  

doing so can produce duplicate numbering announcements. Radio buttons will automatically be communicated as "x of y" when associated with eachother within a radio group or if using native HTML's `name` element to group the form controls.  

Being a child of list items means that there would be the potential for a user to hear the "x of y" announcement in relation to the current list item as well as the current radio button.

this comment applies to the HTML version of this pattern as well.

2022-02-16 05:42 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  <ul id="radioGroup">
Would changing the `ul` to `<ul  id="radioGroup" role="presentation">` or `<ul  id="radioGroup" role="group">` suffice, because for HTML developers i definitely want to use a list because it is a list of options and want to avoid using bad HTML practices as much as possible.

2022-02-16 11:55 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  <ul id="radioGroup">
going the `role=presentation` route would essentially be the same as not using the list at all, and could be achieved by simply using `div` or `p` elements (which is the preferred markup here).

putting a `role=group` on the `ul` inside of a `radiogroup` would put an unnamed group within the radio group... so that'd achieve the suppression of the list semantics, but it would be unnecessarily / incorrectly using ARIA to do so.

so if you were going to do either of the two, the former would be the better choice.  but i'd submit using HTML unnecessarily (e.g., using list markup to then immediately mark it as presentational) is a bad practice.

a list is a grouping of related items.  a radiogroup (or even just a group) of associated radio buttons already achieves the semantic grouping, making it unnecessary to use list markup as well.

As mentioned, you could simply use `<div>` or `<p>` elements to present each radio button on its own line.  That would be the correct markup here.

2022-03-01 13:32 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  - : Identifies the element that provides an error message for the radiogroup, if there is an error. That message should be hidden while not relevant.
noticed that sometimes the role is written as `radiogroup` and then others it's written as 'radio group'.

wasn't sure if one or the other was preferred, but thought maybe `radiogroup` would be preferred since the page is about the ARIA role, and not necessarily the concept of radio groups?  Though the page does go over them both.

2022-03-08 01:56 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +When using HTML's native input radio button, [`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio), the radio group is defined by giving each of input radio buttons in the group the same
"While this will associate the radio buttons together, to expose a grouping of radio buttons as a `radiogroup` explicitly set the ARIA role."

2022-03-08 02:02 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  - : Indicates that one `radio` within the group must have `aria-checked="true"` set before the form may be submitted.
The required state is specified on the `radiogroup` rather than one of the `radio` elements, unlike when using HTML radio buttons where the [`required`](/en-US/docs/Web/HTML/Attributes/required) attribute is set directly on a radio {{HTMLElement('input')}} elements.

2022-03-08 02:15 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +<fieldset>
In this {{HTMLElement('fieldset')}} example, while `role=radiogroup` is not necessary, to have this grouping explicitly announced as `radiogroup`, include the ARIA role.

2022-03-08 03:15 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +Make sure to also change the {{CSSXRef('cursor')}} to a pointer when hovering over the radio button to help people identify the labels and radios as interactive elements.
removed. thank you.

2022-03-08 03:24 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/radiogroup_role/index.md
> +  - : Identifies the element that provides an error message for the radiogroup, if there is an error. That message should be hidden while not relevant.
made it clearer throughout. thank you.

2022-03-08 11:34 UTC, scottaohara reviewed
Looks good!

2022-03-13 22:07 UTC, ericwbailey approved these changes

2022-03-13 22:07 UTC, merged