AbortController: Correct code sample
mdn/content pull request #12603
Opened 2022-02-01 20:39 UTC by deahauhem

#### Summary

Code snippet did not appear to reflect actual code in a way that appeared to break  the connection between the new controller and its signal.

#### Motivation

The code sample did not seem to make sense, so I consulted the linked code sample and discovered the snippet did not reflect the sample.
#### Supporting details

https://github.com/mdn/dom-examples/tree/master/abort-api
#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-02-01 23:32 UTC, wbamberg requested changes
Thanks for your PR!

Just one comment.

2022-02-01 23:32 UTC, wbamberg commented on files/en-us/web/api/abortcontroller/index.md
>    controller = new AbortController();  // Set new controller for this request.
I think we can (and should) delete this line.

2022-02-02 05:26 UTC, deahauhem commented on files/en-us/web/api/abortcontroller/index.md
>    controller = new AbortController();  // Set new controller for this request.
I think we might want to instead delete line 42 instead? The snippet isn't clear on this but it looks like if AbortedController has alredy aborted, it would prevent fetch from happening a second time?

2022-02-02 19:46 UTC, wbamberg requested changes
Yes, this looks much better!

2022-02-02 19:46 UTC, wbamberg commented on files/en-us/web/api/abortcontroller/index.md
>    console.log('Download aborted');
```suggestion
  if (controller) {
    controller.abort();
    console.log('Download aborted');
  }
```

...maybe?

2022-02-02 22:24 UTC, deahauhem commented on files/en-us/web/api/abortcontroller/index.md
>    console.log('Download aborted');
Agreed!

2022-02-02 23:30 UTC, wbamberg approved these changes
👍 thank you @deahauhem !

2022-02-02 23:30 UTC, merged