More HTTPStatus codes added
mdn/content pull request #12601
Opened 2022-02-01 19:34 UTC by Harshil-Jani

#### Summary

HTTP response status codes.
- 102 Processing 
- 207 Multi-Status
- 208 Already Reported
- 226 IM Used 
- 421 Misdirected Request
- 423 Locked
- 424 Failed Dependency 
were missing in the list. So they were added.
#### Motivation

This will be my very first contribution towards MDN. I used it as a major resource of learning so now with this I want to be part of the MDN network and help it grow more effectively
#### Supporting details

#### Related issues

Fixes #12591 

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-02 00:15 UTC, Muradalsaaideh commented
> <!-- 👀 Thanks for opening a PR! Read comments like this one to get your PR merged faster. -->
> #### Summary
> <!-- ✍️ In a sentence or two, describe your changes -->
> HTTP response status codes.
> - 102 Processing 
> - 207 Multi-Status
> - 208 Already Reported
> - 226 IM Used 
> - 421 Misdirected Request
> - 423 Locked
> - 424 Failed Dependency 
> were missing in the list. So they were added.
> #### Motivation
> <!-- ❓ Why are you making this change? Help us understand how your changes help readers. -->
> This will be my very first contribution towards MDN. I used it as a major resource of learning so now with this I want to be part of the MDN network and help it grow more effectively
> #### Supporting details
> <!-- 🔗 Link to supporting information, such as bug trackers, source control, release notes, and vendor docs. -->
> 
> #### Related issues
> <!-- 🔨 If applicable, use "Fixes #XYZ" -->
> Fixes #12591 
> 
> #### Metadata
> <!-- ✅ Check a box if applicable, like this: [x]
> 
> This PR…
> -->
> - [x] Adds a new document
> - [ ] Rewrites (or significantly expands) a document
> - [ ] Fixes a typo, bug, or other error
> 
> <!-- 👷‍♀️ After submitting, review the results of the "Checks" tab! -->
> 

e889efc4e3a59db1525f4001ac6be3189bef5968

2022-02-02 00:16 UTC, Muradalsaaideh commented
> > <!-- 👀 Thanks for opening a PR! Read comments like this one to get your PR merged faster. -->
> > #### Summary
> > <!-- ✍️ In a sentence or two, describe your changes -->
> > HTTP response status codes.
> > - 102 Processing 
> > - 207 Multi-Status
> > - 208 Already Reported
> > - 226 IM Used 
> > - 421 Misdirected Request
> > - 423 Locked
> > - 424 Failed Dependency 
> > were missing in the list. So they were added.
> > #### Motivation
> > <!-- ❓ Why are you making this change? Help us understand how your changes help readers. -->
> > This will be my very first contribution towards MDN. I used it as a major resource of learning so now with this I want to be part of the MDN network and help it grow more effectively
> > #### Supporting details
> > <!-- 🔗 Link to supporting information, such as bug trackers, source control, release notes, and vendor docs. -->
> > 
> > #### Related issues
> > <!-- 🔨 If applicable, use "Fixes #XYZ" -->
> > Fixes #12591 
> > 
> > #### Metadata
> > <!-- ✅ Check a box if applicable, like this: [x]
> > 
> > This PR…
> > -->
> > - [x] Adds a new document
> > - [ ] Rewrites (or significantly expands) a document
> > - [ ] Fixes a typo, bug, or other error
> > 
> > <!-- 👷‍♀️ After submitting, review the results of the "Checks" tab! -->
> > 
> 
> e889efc4e3a59db1525f4001ac6be3189bef5968

e889efc4e3a59db1525f4001ac6be3189bef5968

2022-02-07 16:14 UTC, teoli2003 commented
Before reviewing in detail, @hamishwillee and @elchi3, what is your opinion about adding these as they are part of the (fairly common) WebDAV specs and not the web _stricto sensu_.

I'm torn here.

2022-08-28 07:04 UTC, bhaveshraj336 commented
@teoli2003 I can make any changes needed ?
The PR is been on hold from last 6 months?

2022-08-28 07:08 UTC, teoli2003 commented
We are waiting for answers from @hamishwillee and @elchi3 here.

2022-09-28 00:09 UTC, estelle commented
pinging @hamishwillee and @Elchi3

2022-10-03 00:29 UTC, hamishwillee commented on files/en-us/web/http/status/208/index.md
> +| Specification                         | Status   | Comments           |
Use spec URLs

2022-10-03 01:04 UTC, hamishwillee commented
@teoli2003 @estelle Sorry to be late to the party. FWIW I agree with @Elchi3 

Specifically, I use MDN for first place to look up this kind of information and I think this is a good contribution (thanks @Harshil-Jani). 

But I'd like not to have those spec tables in the source. Is it possible to specify a "spec_url" in frontmatter yet? I couldn't find an example of this in content.

I'm also not sure about omitting the compatibility section. My concern here is that readers don't necessarily understand that it is missing because there is no compatibility story to tell. Not, not so worried about this case, but see case in aside below.

@teoli2003 I assume you are going to review this following the feedback that we think this is good, but if you want me to then let me know.

---

Bigger picture aside ...

W.r.t. browser compatibility we have the same problem with some HTTP headers in that "browser support" is nonsensical. How we indicate this seems to be inconsistent - there are plenty of cases where we just say "true". It would be good to agree an approach and use it here.

The obvious thought is that if something has no compatibility story then it shouldn't be in BCD, and that we therefore should push the spec urls into page metadata. I dislike this because there is no way to know if something is missing or deliberately omitted from BCD. Also BCD is good at managing the spec data and having it managed in multiple places sux.

So if it were practical and politically possible, my preference would be to work out a way to indicate "not applicable" for version compatibility and still keep the specs in BCD.

2022-10-25 06:00 UTC, hamishwillee commented
@teoli2003 I put a comment above, but I think this is still waiting on you.

2023-01-03 01:05 UTC, hamishwillee commented
OK, I'm going to ping @teoli2003 one last time. If not, next time I come here I'm going to do the work to get this in.

2023-01-16 09:43 UTC, teoli2003 commented on files/en-us/web/http/status/208/index.md
> +| Specification                         | Status   | Comments           |
```suggestion
{{Specifications}}
```

2023-01-16 09:44 UTC, teoli2003 commented on files/en-us/web/http/status/208/index.md
> +browser-compat: http.status.208
```suggestion
browser-compat: http.status.208
spec-url: https://www.rfc-editor.org/rfc/rfc5842.html#section-7.1
```

2023-01-16 09:49 UTC, teoli2003 commented
Ok, I got a look at this, and I'll add a few commits to get specs and compatibility in. As these are not in bcd, there is no compatibility per se, but I'll put a sentence explaining why.

Then I'll hand it to Hamish for a last review before landing this.

2023-01-16 12:39 UTC, teoli2003 approved these changes
This is now ok for me. Let's get a last review from Hamish then land this.

2023-01-23 06:05 UTC, hamishwillee commented on files/en-us/web/http/status/207/index.md
> +The HTTP **`207 Multi Status`** response code indicates that there might be mixture of responses. We use {{HTTPStatus(204)}} if all the operations succededs or else if all fails we can use {{HTTPStat
@teoli2003 I fixed the typo and English  here, but I'm not sure what "multi status" means below.

```suggestion
The HTTP **`207 Multi Status`** response code indicates that there might be mixture of responses.
We use {{HTTPStatus(204)}} if all the operations succeed and {{HTTPStatus(403)}} if all operations fail.
If some operations succeed and others fail then we use Multi Status.
```

2023-01-23 06:10 UTC, hamishwillee commented on files/en-us/web/http/status/207/index.md
> +If you perform a destructive operation like {{HTTPMethod("POST")}}, {{HTTPMethod("DELETE")}} etc. against more than one resource and the operations against each individual resource does not share a c
I thought each operation was atomic so if you deleted a resource it would succeed or fail in entirety. I assume this is not the case. Is this wording correct?

```suggestion
If you perform a destructive operation like {{HTTPMethod("POST")}}, {{HTTPMethod("DELETE")}} etc. against more than one resource and the operations against each individual resource do not not share a common outcome then the response can be `207`.
```

2023-01-23 06:11 UTC, hamishwillee commented on files/en-us/web/http/status/208/index.md
> +The HTTP **`208 Already Reported`** response code is used inside DAV: propstat response element. This uses Bindings, so to avoid mapping of internal members of multiple binding to a collection inside
@teoli2003 Is this sufficient? As a lay reader I do not know anything about DAV, Bindings, internal members etc. So this is "spec language" to me.

2023-01-23 06:11 UTC, hamishwillee commented on files/en-us/web/http/status/102/index.md
> +slug: Web/HTTP/Status/102
@wbamberg While we're here, is there an agreed set of HTTP page types yet?

2023-01-23 06:12 UTC, hamishwillee commented on files/en-us/web/http/status/226/index.md
> +The HTTP **`226 IM Used`** response code is used when the server has fulfilled a {{HTTPMethod("GET")}} Request for the resource but the response is a representation of the result of one or more insta
```suggestion
The HTTP **`226 IM Used`** response code is used when the server has fulfilled a {{HTTPMethod("GET")}} request for the resource but the response is a representation of the result of one or more instance manipulations applied by combining with previous or future responses as specific instances.
```

2023-01-23 06:12 UTC, hamishwillee commented on files/en-us/web/http/status/226/index.md
> +The HTTP **`226 IM Used`** response code is used when the server has fulfilled a {{HTTPMethod("GET")}} Request for the resource but the response is a representation of the result of one or more insta
I don't know what this means. Is it sufficient?

2023-01-23 06:13 UTC, hamishwillee commented on files/en-us/web/http/status/421/index.md
> +The HTTP **`421 Misdirected Request`** client error response code indicates that the request was directed at a server that is not able to produce a response. This might be possible if a connection is
```suggestion
The HTTP **`421 Misdirected Request`** client error response code indicates that the request was directed to a server that is not able to produce a response. This might be possible if a connection is reused or if an alternative service is selected.
```

2023-01-23 06:15 UTC, hamishwillee commented on files/en-us/web/http/status/421/index.md
> +The HTTP **`421 Misdirected Request`** client error response code indicates that the request was directed at a server that is not able to produce a response. This might be possible if a connection is
@teoli2003 What is a client error response code? I.e. I know that a response comes from a server in response to a request - so all responses are from servers? Or is this somehow internally generated?

Basically I am not sure who provides this response, or how it might happen.

2023-01-23 06:18 UTC, hamishwillee commented on files/en-us/web/http/status/423/index.md
> +The HTTP **`423 Locked`** client error response code indicates that either the source or the destination of a method is locked. It should contain some conditions such that the accessible resources ar
I understand that you might send a request to either get or modify a resource and get this response back indicating that the resource cannot be returned/modified because it is locked. Is that correct?

Further, that you're saying that some other information should be provided to indicate what is required to unlock the resource. Is that right?

I think you need an example because I don't understand what the response message might look like from this.

2023-01-23 06:20 UTC, hamishwillee requested changes
@teoli2003 I've added some comments. I'm not sure of the right level for these responses. Generally though when I read the existing documents I can determine when I would expect the response and what it means - and some of these I'm not sure. But I haven't read this part of the spec in detail so it needs some "judgement call" from you or @Elchi3 

PS SOrry I didn't come up with this earlier - earlier I was just agreeing that we want this kind of doc.

2023-01-23 06:21 UTC, hamishwillee commented on files/en-us/web/http/status/102/index.md
> +spec-urls: https://www.rfc-editor.org/rfc/rfc2518.html#section-10.1
Thanks for fixing up all the spec sections!

2023-01-23 14:57 UTC, wbamberg commented on files/en-us/web/http/status/102/index.md
> +slug: Web/HTTP/Status/102
-> https://github.com/mdn/content/issues/22761, but it is waiting for https://github.com/mdn/content/issues/22761#issuecomment-1384085784 to be resolved. I think that should not block this PR though, we can add these pages without page types now and then set page types when we update all of HTTP.

2023-02-07 10:08 UTC, teoli2003 commented on files/en-us/web/http/status/226/index.md
> +The HTTP **`226 IM Used`** response code is used when the server has fulfilled a {{HTTPMethod("GET")}} Request for the resource but the response is a representation of the result of one or more insta
I have revamped this article to give context.

2023-02-07 12:05 UTC, teoli2003 commented on files/en-us/web/http/status/423/index.md
> +The HTTP **`423 Locked`** client error response code indicates that either the source or the destination of a method is locked. It should contain some conditions such that the accessible resources ar
I have revamped this part and added an example. I didn't go into details as we don't document the whole of WebDAV: enough to understand what is going on and the purpose here, but not enough to implement a WebDAV server or client.

2023-02-08 09:12 UTC, teoli2003 commented on files/en-us/web/http/status/208/index.md
> +The HTTP **`208 Already Reported`** response code is used inside DAV: propstat response element. This uses Bindings, so to avoid mapping of internal members of multiple binding to a collection inside
I have revamped this article to give more context and simplify it.

2023-02-08 09:39 UTC, teoli2003 commented on files/en-us/web/http/status/207/index.md
> +The HTTP **`207 Multi Status`** response code indicates that there might be mixture of responses. We use {{HTTPStatus(204)}} if all the operations succededs or else if all fails we can use {{HTTPStat
I have revamped the page. Example of return status are useless here (it was far from being exhaustive anyway)

2023-02-08 11:07 UTC, teoli2003 commented on files/en-us/web/http/status/421/index.md
> +The HTTP **`421 Misdirected Request`** client error response code indicates that the request was directed at a server that is not able to produce a response. This might be possible if a connection is
I revamped this one too.

2023-02-08 11:12 UTC, teoli2003 commented
@hamishwillee 

I went again through this PR. The difficulty here is that it adds status code used in very different contexts
- Some are part of the basic HTTP semantics, like `102`
- Others are part of WebDAV and its extensions.

For the latter, I've rewritten them with the following intention:
- We should make it explicit that these are for WebDAV and not for regular HTTP (and web developers unless interacting with such servers, should never bother with them.
- I link to the glossary page about WebDAV and give minimum information (like an example) without going into too many details about the protocol: we are not documenting WebDAV here, only giving enough context so that a dev will understand what's going on there. For example, I don't describe the XML structure of the body of a WebDAV, but I use it in an example several times (as it was necessary to have an idea of the body of a response).

I hope this makes these new articles more useful.

2023-02-10 00:53 UTC, hamishwillee commented on files/en-us/web/http/status/208/index.md
> +The HTTP **`208 Already Reported`** response code is used in a {{HTTPStatus("207")}} (`207 Multi-Status`) response to save space and avoid conflicts: if the same resource is requested several times (
```suggestion
The HTTP **`208 Already Reported`** response code is used in a {{HTTPStatus("207")}} (`207 Multi-Status`) response to save space and avoid conflicts.
If the same resource is requested several times (for example as part of a collection), with different paths, only the first one is reported with {{HTTPStatus("200")}}. 
Responses for all other bindings will report with this `208` status code, so no conflicts are created and the response stays shorter.
```

2023-02-10 00:54 UTC, hamishwillee commented on files/en-us/web/http/status/226/index.md
> +In the context of delta encodings, the HTTP **`226 IM Used`** status code is set by the server to indicate that it returns a _delta_ to the {{HTTPMethod("GET")}} request it received.
```suggestion
In the context of delta encodings, the HTTP **`226 IM Used`** status code is set by the server to indicate that it is returning a _delta_ to the {{HTTPMethod("GET")}} request that it received.
```

2023-02-10 00:56 UTC, hamishwillee commented on files/en-us/web/http/status/424/index.md
> +The HTTP **`424 Failed Dependency`** client error response code indicates that the method could not be performed on the resource because the requested action depended on another action and that actio
```suggestion
The HTTP **`424 Failed Dependency`** client error response code indicates that the method could not be performed on the resource because the requested action depended on another action, and that action failed.
```

2023-02-10 01:04 UTC, hamishwillee commented on files/en-us/web/http/status/226/index.md
> +Delta encoding consists in sending back to {{HTTPMethod("GET")}} requests differences (called _deltas_) from a given base document. The client uses the `A-IM:` HTTP header to indicate which differenc
@teoli2003 The English here is hard to parse. Do you mean that you send a get request and get back a response that you can reconstuct if you know a base document it refers to?

I think you might mean:

```suggestion
With delta encoding a server responds to {{HTTPMethod("GET")}} requests with differences (called _deltas_) relative to a given base document (rather than the current document). The client uses the `A-IM:` HTTP header to indicate which differencing algorithm to use and the `If-None-Match:` header to hint the server about the last version it got. The server generates a delta, sending it back in an HTTP response with the `226` status code and containing the `IM:` (with the name of the algorithm used) and `Delta-Base:` (with the {{HTTPHeader("ETag")}} matching the base document associated to the delta) HTTP headers.
```

2023-02-10 01:04 UTC, hamishwillee commented
@teoli2003 Looks great/good strategy. I've done some minor subedits and there is one point for clarification left.

2023-02-10 06:00 UTC, teoli2003 commented on files/en-us/web/http/status/226/index.md
> +Delta encoding consists in sending back to {{HTTPMethod("GET")}} requests differences (called _deltas_) from a given base document. The client uses the `A-IM:` HTTP header to indicate which differenc
Yes, exactly.

2023-02-10 06:49 UTC, hamishwillee approved these changes
Thanks very much @Harshil-Jani and @teoli2003 . Looks good to me!

2023-02-10 06:50 UTC, merged