Adding none as a keyword value for max logical sizing
mdn/content pull request #12797
Opened 2022-02-07 11:02 UTC by Anurella

Fixes #12703. Changed keyword value of max-block-size and max-inline-size from auto to none, auto is not a valid value for max logical sizing but works great for min logical sizing.

2022-02-07 14:19 UTC, teoli2003 requested changes
Good catch! Thanks! Either a value of an early version of the spec or a bad cut & paste.

2 NITs (not important things) to fix: 2 extraneous lines added to remove

2022-02-07 15:26 UTC, teoli2003 requested changes
Thanks. You added by error a modification to .gitignore. Still this and we are good to merge!

2022-02-07 15:26 UTC, teoli2003 commented on .gitignore
>  yarn-debug.log*
.gitignore shouldn't be modified by this PR.

2022-02-07 19:49 UTC, teoli2003 commented on .gitignore
>  yarn-debug.log*
I think you deleted a CR too much and it got taken.

2022-02-08 13:14 UTC, schalkneethling commented
I reckon @teoli2003 has got this covered. Thank you for your contribution @Anurella 🎉

2022-02-08 15:49 UTC, teoli2003 approved these changes
I've committed my proposal fixing the .gitignore thing. Let's merge this.

2022-02-08 15:51 UTC, merged

2022-02-08 15:51 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: