Added SVGBoundingBoxOptions
mdn/content pull request #128
Opened 2020-11-25 02:37 UTC by MendyBerger

mdn/sprints/issues/3914

This is the first time I write actual content to MDN so any type of feedback (grammar, format, etc) would be greatly appreciated.

I think that we also need to add `SVGBoundingBoxOptions` to `browser-compat-data`.

2020-11-25 19:45 UTC, Ryuno-Ki commented
Dear Mendy,

let me draw your attention to this line of the BETA.md:

> When you make a legitimate change to the content repo and it gets accepted, you'll also have to go in and make that change on the wiki if you want to see it live.

The alternative would be to wait until the end of the Beta phase (beginning of December), since then content should be synced (in my understanding).
In another issue, it was mentioned, that the staff team is on vacation this week, so please be a bit patient.

Thanks for your contribution!

2020-11-25 20:10 UTC, MendyBerger commented
@Ryuno-Ki I figured since we are close enough to December that I'll make the changes here.

Thanks for letting me know that the team is on vacation, I wasn't aware of that, I guess the PR will have to wait

2020-11-30 11:59 UTC, chrisdavidmills requested changes
Thanks @MendyBerger , this is looking pretty good. A couple of queries/nitpicks:

1. I'd like to see the default values wrapped in `<code>` elements so they show in code font.
2. I'm pretty sure that these values are boolean values, not Boolean objects, so in each case, "{{jsxref("Boolean")}}" should be changed to "boolean value" ?

2020-11-30 12:01 UTC, chrisdavidmills commented
And @Ryuno-Ki is correct — you will also need to add this content to the wiki page version too, to stop it from being lost. The content is served from this repo as of December 14th.

2020-11-30 14:42 UTC, Ryuno-Ki commented
>     1. I'd like to see the default values wrapped in `<code>` elements so they show in code font.

I'm sure, you meant to wrap it because it „represents a fragment of code”, not because of the look of it (e.g. the semantics are important) :-)

2020-11-30 14:52 UTC, chrisdavidmills commented
> > ```
> > 1. I'd like to see the default values wrapped in `<code>` elements so they show in code font.
> > ```
> 
> I'm sure, you meant to wrap it because it „represents a fragment of code”, not because of the look of it (e.g. the semantics are important) :-)

Pedantry much appreciated. Yes, you are totally right ;-)

2020-12-01 15:36 UTC, MendyBerger commented
> 1. I'd like to see the default values wrapped in `<code>` elements so they show in code font.

Updated

2020-12-01 15:37 UTC, MendyBerger commented
> 2. I'm pretty sure that these values are boolean values, not Boolean objects, so in each case, "{{jsxref("Boolean")}}" should be changed to "boolean value" ?

I'm a bit confused, I see that some pages do use "{{jsxref("Boolean")}}" for Boolean values
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

2020-12-05 11:00 UTC, chrisdavidmills commented
> > 1. I'm pretty sure that these values are boolean values, not Boolean objects, so in each case, "{{jsxref("Boolean")}}" should be changed to "boolean value" ?
> 
> @chrisdavidmills I'm a bit confused, I see that some pages do use "{{jsxref("Boolean")}}" for Boolean values
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
> https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

This is possibly my fault. I used to think that the two were synonymous, but I got pulled up a while ago by a Firefox engineer about it — in most cases, you are not feeding in an actual `Boolean` object as the argument — you are feeding in a simple string value.

The spec is not actually very clear about this, for example see https://dom.spec.whatwg.org/#event-listener-capture.

But I think just saying boolean value is simpler and likely to cause less confusion.

2020-12-09 00:11 UTC, MendyBerger commented
> And @Ryuno-Ki is correct — you will also need to add this content to the wiki page version too, to stop it from being lost. The content is served from this repo as of December 14th.

Will the changes be merged with the wiki or overridden?

2020-12-09 10:47 UTC, chrisdavidmills commented
> > And @Ryuno-Ki is correct — you will also need to add this content to the wiki page version too, to stop it from being lost. The content is served from this repo as of December 14th.
> 
> @chrisdavidmills one more question, will the changes here be merged with the wiki or overridden?

In the beta period, the `content` repo is overwritten with the wiki content roughly about once per day. This is why we are telling people to make any changes we make here in the wiki as well just for now, so work is not lost.

After the December 14th launch date of course, this will no longer be an issue ;-)

2020-12-16 13:37 UTC, peterbe commented
The migration has now happened. @MendyBerger is the PR ready?

2020-12-16 15:20 UTC, MendyBerger commented
> The migration has now happened. @MendyBerger is the PR ready?

Yes, think I've addressed all concerns raised

2020-12-16 17:03 UTC, sideshowbarker requested changes

2020-12-16 17:03 UTC, sideshowbarker commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +     <dd>A boolean value indicating that the fill should be included in the bounding box, defaults to <code>true.</code></dd>
```suggestion
     <dd>A boolean value indicating that the fill should be included in the bounding box, defaults to <code>true</code>.</dd>
```

2020-12-16 17:03 UTC, sideshowbarker commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +     <dd>A boolean value indicating that the stroke should be included in the bounding box, defaults to <code>false.</code></dd>
```suggestion
     <dd>A boolean value indicating that the stroke should be included in the bounding box, defaults to <code>false</code>.</dd>
```

2020-12-16 17:03 UTC, sideshowbarker commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +     <dd>A boolean value indicating that the markers should be included in the bounding box, defaults to <code>false.</code></dd>
```suggestion
     <dd>A boolean value indicating that the markers should be included in the bounding box, defaults to <code>false</code>.</dd>
```

2020-12-16 17:03 UTC, sideshowbarker commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +     <dd>A boolean value indicating that the bounding box should be clipped, defaults to <code>false.</code></dd>
```suggestion
     <dd>A boolean value indicating that the bounding box should be clipped, defaults to <code>false</code>.</dd>
```

2020-12-16 18:58 UTC, MendyBerger commented
Thanks @sideshowbarker for catching it, fixed it

2020-12-16 19:41 UTC, sideshowbarker approved these changes

2020-12-21 08:20 UTC, nschonni commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +<h3 id="Return_value">Parameters</h3>
```suggestion
<h3 id="Parameters">Parameters</h3>
```

2020-12-21 08:24 UTC, chrisdavidmills commented on files/en-us/web/api/svggraphicselement/getbbox/index.html
> +<h3 id="Return_value">Parameters</h3>
Fixed by my last update. I think we can merge this now!

2020-12-21 08:24 UTC, chrisdavidmills approved these changes

2020-12-21 08:24 UTC, merged