Improve code examples: for..of
mdn/content pull request #12814
Opened 2022-02-08 00:02 UTC by tshemsedinov

#### Summary
- Remove async IIFE (now we have top-level await everywhere)
- Prefer `const` as for..of variable
- Improve code style consistency

#### Motivation
Improve code examples to use MDN as a reference in my university lectures.

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-02-08 03:45 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    with `const`, `let`, or `var` (prefer `const`).
I'm not sure about this addition. You prefer `const` if the variable is not to be modified in the loop, and `let` otherwise right?

2022-02-08 12:56 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    with `const`, `let`, or `var` (prefer `const`).
@hamishwillee what I want to say:
1. `var` is ok just for legacy code
2. `let` is allowed but not desirable because it allow mutations in loop body
3. `const` is preferable in almost all cases except some rare optimizations

2022-02-17 00:39 UTC, wbamberg requested changes
Thanks for this PR, @tshemsedinov ! Some of these style changes are important IMO, especially `var`->`const`. Some of them I think are a bit more subjective, but on the whole I agree with pretty much all of them. I had a few complaints, but if we can address them I'm happy to merge this.

I do think, though, that for MDN we really need to be addressing code style issues with tooling across the whole site, rather than a bit at a time through manual PRs. The site is just too big, and our volume of PRs is just too high, for manual fixes to be sustainable.

We have [an open issue about enforcing Prettier (and hopefully ESLint) for our code samples](https://github.com/mdn/content/issues/10402), and I hope we will get to that soonish.

If there are particular areas of MDN for which you want to update the code style, it might be worth talking to us about the scope of that (maybe in a [discussion](https://github.com/mdn/content/discussions)?) so we can figure out how to resource reviews for it. But I don't think we can update the entire site in this way.

I don't want to discourage you because I think these are good improvements, we just need to figure out an efficient way to make them.

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const double = (number) => number * 2;
It's intentional not to use arrow functions here, because we've not yet introduced them.

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const isLong = (city) => city.length > 8;
It's intentional not to use arrow functions here, because we've not yet introduced them.

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const removedCities = cities.pop();
This would be `removedCity`, presumably, because it's a single item?

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +reset.addEventListener('click', () => {
This is internal code (not shown to users) so it's OK to use arrow functions.

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md
> +const o = {
+1 to var->const changes!

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    with `const`, `let`, or `var` (prefer `const`).
I don't think we should include "(prefer `const`)" here. We generally would recommend people to use const where they can, but I don't think there is sense in repeating this every time it comes up.

We should have code samples consistently using `const` though.

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +const LIMIT = 3;
this doesn't seem to be used?

2022-02-17 00:39 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +for await (const num of asyncIterable) {
Putting this in the console (Firefox 98) it doesn't work:

> Uncaught SyntaxError: for await (... of ...) is only valid in async functions and async generators

...while the original IIFE version does.

2022-02-17 13:17 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    with `const`, `let`, or `var` (prefer `const`).
```suggestion
    with `const`, `let`, or `var`.
```

2022-02-17 13:20 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +const LIMIT = 3;
Oh, It looks like I dropped part of this example rebasing... I'll add it back in following commit

2022-02-17 13:23 UTC, tshemsedinov commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const removedCities = cities.pop();
```suggestion
const cities = ['Manchester', 'Liverpool'];
const removedCity = cities.pop();
```

2022-02-17 13:23 UTC, tshemsedinov commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +console.log(removedCities);   // "Liverpool"
```suggestion
console.log(removedCity);   // "Liverpool"
```

2022-02-17 13:24 UTC, tshemsedinov commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const isLong = (city) => city.length > 8;
```suggestion
function isLong(city) {
  return city.length > 8;
}
```

2022-02-17 13:30 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +}
```suggestion
(async () => {
  for await (const num of asyncGenerator()) {
    console.log({ num });
  }
})();
```

2022-02-17 13:32 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +}
```suggestion
(async () => {
  for await (const num of generator()) {
    console.log(num);
  }
})();
```

2022-02-17 13:33 UTC, tshemsedinov commented on files/en-us/learn/javascript/first_steps/arrays/index.md
> +const double = (number) => number * 2;
```suggestion
function double(number) {
  return number * 2;
}
```

2022-02-17 13:36 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    console.log(num);
```suggestion
(async () => {
  try {
    for await (const num of generatorWithRejectedPromises()) {
      console.log(num);
```

2022-02-17 13:36 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +}
```suggestion
  } catch (e) {
    console.log('caught', e);
  }
})();
```

2022-02-17 13:38 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +}
```suggestion
  } catch (e) {
    console.log('caught', e);
  }
})();
```

2022-02-17 13:40 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +    with `const`, `let`, or `var` (prefer `const`).
Removed

2022-02-17 14:10 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/statements/for-await...of/index.md
> +        return Promise.resolve({ value, done });
```suggestion
        const done = i === LIMIT;
        const value = done ? undefined : i++;
        return Promise.resolve({ value, done });
```

2022-02-17 14:46 UTC, tshemsedinov commented
@wbamberg Thanks! Everything resolved, lost part of code with `asyncIterable` example returned. In future it will be good to have automated tools and concentrate on more complex code improvements, like we have in mentioned `asyncIterable` example: https://github.com/tshemsedinov/content/blob/patch-1/files/en-us/web/javascript/reference/statements/for-await...of/index.md#iterating-over-async-iterables

2022-02-17 19:22 UTC, wbamberg approved these changes
Looks great! Thanks for the updates.

2022-02-17 19:23 UTC, merged