FF98 HTMLElement.outerText updates
mdn/content pull request #12821
Opened 2022-02-08 06:49 UTC by hamishwillee

FF98 supports [`HTMLElement.outerText`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/outerText), which was recently added to the spec. This updates the docs to provide a better example of how it is used and note that is its now standard. Also adds release note, and some tidy up of `innerText`

Related docs work tracked in #12576

2022-02-08 18:05 UTC, ddbeck requested changes, later dismissed
A couple little suggestions and a question for you.

(I know you didn't introduce it, but I feel like if we're not confident enough to say rendered without quotes, then we shouldn't be saying it. 😆)

2022-02-11 02:50 UTC, hamishwillee commented on files/en-us/web/api/htmlelement/innertext/index.md
> -
Yes, according to https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections#properties . This was the result of https://github.com/mdn/content/discussions/5992

Note, following having done a few of these, I think explicitly listing as setter and getter _if they differ_ would have been good.

2022-02-11 03:37 UTC, hamishwillee commented on files/en-us/web/api/htmlelement/outertext/index.md
> +```
Me either, but it seems silly to try and reinvent the obvious structure. I have added an attribution. Happy to create a new example if you have an idea for a better example.

2022-02-14 03:14 UTC, hamishwillee commented
@ddbeck Would appreciate a new look at this please.

2022-02-14 18:27 UTC, ddbeck commented on files/en-us/web/api/htmlelement/innertext/index.md
> -
Hmm, yes, but then we'd have to remember to do it, circumstantially. Thanks for mentioning it though (I'm putting in my notes about more rigorously specifying page types).

2022-02-14 18:29 UTC, ddbeck commented on files/en-us/web/api/htmlelement/outertext/index.md
> +```
Yeah, I was hoping I would have a better idea by the time I finished writing my request. I did not. 😆

2022-02-14 18:30 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-02-14 18:30 UTC, ddbeck commented on files/en-us/web/api/htmlelement/index.md
> +  - : Represents the "rendered" text content of a node and its descendants.
Ugh, I missed one. I'm going to apply this and merge.

```suggestion
  - : Represents the "rendered" text content of a node and its descendants.
```

2022-02-14 18:31 UTC, ddbeck reviewed
Oh wait, it won't let me apply the change. Would you pick that up and then we can merge?

2022-02-14 23:47 UTC, merged

2022-02-14 23:48 UTC, hamishwillee commented
THanks @ddbeck - merged. FYI only the reason you couldn't merge the suggestion is that you had not modified it to remove the quotation marks - github was telling me that I couldn't merge it because it didn't change the content.

2022-02-15 10:07 UTC, ddbeck commented
Oh that's what I get for looking at it at the end of the day. Thanks, Hamish!