Improve fetch examples: syntax and consistency
mdn/content pull request #12939
Opened 2022-02-12 10:01 UTC by Fr3ud

### **Summary**

- Change `let` to `const` where possible
- Use one-line arrow functions is possible
- Improve code indentation and alignment, fix other style consistency issues

### **Motivation**

Improving code examples.

### **Metadata**

- [ ]  Adds a new document
- [ ]  Rewrites (or significantly expands) a document
- [x]  Fixes a typo, bug, or other error

2022-02-14 17:04 UTC, jpmedley requested changes

2022-02-15 19:39 UTC, Fr3ud commented on files/en-us/web/api/fetch/index.md
> +        CONNECT, TRACE or TRACK.
Done. I highlighted the methods with `code` tags and added single quotes.

2022-02-16 15:35 UTC, jpmedley approved these changes
Thank you for your help.

2022-02-16 15:35 UTC, merged

2022-02-16 21:15 UTC, Fr3ud commented
> Thank you for your help.
Glad to be of help!