Examples code re-written with response.body stream converted to string.
mdn/content pull request #12941
Opened 2022-02-12 14:08 UTC by igorbalden

#### Summary
Edited code examples, to convert sequence of two .then() functions, to a single one.

#### Motivation
According to the examples the developer can access all 'response' properties in the first .then(), 
and the response.body data in the second .then(), separately.
With the suggested code the whole 'response' object is available in the first .then() block.
That is all response properties, together with the response.body.

#### Supporting details
Lots of developers do not use fetch API because of this exact issue.
They can not access together response properties and data in one code block.
The examples code confuses users, as it is obvious by the stackoverflow.com questions.

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-13 16:15 UTC, domenic commented
This seems strange to me. Either use async/await entirely (no `.then()`), or avoid `async`/`await` entirely (like the existing code does).

2022-02-13 19:57 UTC, igorbalden commented
There is no problem mixing .then(), with async/await syntax. It's only a matter of style.
Anyway, here they are examples in both 'single' styles:
1.  .then()
    We have to return the Promise in the first .then(),
    else we won't be able to catch all errors in a single catch();

  function fetchit() {
    fetch('https://some/resource')
    .then(response => {
      return Promise.resolve(response.json())
      .then(data => {
        console.log(response)
        console.log(data);
      })
    })
    .catch(error => {
      console.log(error)
    });
  }

2.  async/await 
    Again we may catch all errors in a single catch();

  async function fetchit() {
    try {
      const response = await fetch('https://some/resource');
      const data = await response.json();
      console.log(response)
      console.log(data)
    } catch(error) {
      console.log(error)
    };
  }

I still believe that the mixed style version is the most convenient of all, and must be included.

Would you like me to rewrite the "Using fetch" page, to include all these examples?

2022-02-13 22:54 UTC, sideshowbarker commented
Thanks for opening this PR. I agree this article has a lot of room for improvement, so I’m glad to see it getting some attention.

>  The examples code confuses users, as it is obvious by the stackoverflow.com questions.

Yes, I read many questions posted to the Stack Overflow `[fetch-api]` tag, and I agree there’s a lot of developer confusion about how to write basic code using the Fetch API.

> Either use async/await entirely (no `.then()`), or avoid `async`/`await` entirely (like the existing code does).

I tend to agree with Domenic on this. In terms of developer confusion, I think showing developers a mix of `.then()` and `async`/`await` in a basic code example is potentially confusing for developers. I can imagine some newer developers thinking it means that *must* write `fetch()` code in that mixed style for some reason.

> There is no problem mixing .then(), with async/await syntax.

I don’t think anybody was suggesting there’s a problem with how it executes. But it seems fair to say it’s not typical.

> It's only a matter of style.

True — but our existing style in MDN is generally not to mix them. Personally, I see some value in the mixed approach, and I understand why you’d prefer it, and I can imagine there are other experienced developers who would prefer it too — developers who know what they’re doing and choose to do it that way. But with an MDN article like this, we’re kind of optimizing for the developers who may not yet know well what they’re doing — and so we somewhat need to try to keep thing as simple a possible, and not introduce anything that might further confuse anybody new.

> Would you like me to rewrite the "Using fetch" page, to include all these examples?

IMHO, it’s probably sufficient to just show one example of the async/await approach after the “_A basic fetch request is really simple to set up. Have a look at the following code:”_ line, to follow the existing `.then()`-based approach there.

2022-02-14 10:49 UTC, igorbalden commented
Tnx @domenic , @sideshowbarker for your guidance.
Pushed on more commit. 
Edited all examples in .then() syntax, 
and added one example of sync/await.

2022-02-14 17:43 UTC, jpmedley requested changes

2022-02-14 17:43 UTC, jpmedley commented on files/en-us/web/api/fetch_api/using_fetch/index.md
> +  return response;
What's your reason for remving `json()` from this example, while adding it to the next example.

2022-02-14 17:43 UTC, jpmedley commented on files/en-us/web/api/fetch_api/using_fetch/index.md
> +A {{domxref("fetch()")}} promise will reject with a {{jsxref("TypeError")}} when a network error is encountered or CORS is misconfigured on the server-side, although this usually means permission iss
```suggestion
A {{domxref("fetch()")}} promise will reject with a {{jsxref("TypeError")}} when a network error is encountered or CORS is misconfigured on the server side, although this usually means permission issues or similar. A 404 does not constitute a network error, for example. An accurate check for a successful `fetch()` would include checking that the promise resolved, then checking that the {{domxref("Response.ok")}} property has a value of true. The code would look something like this:  
```

2022-03-30 03:57 UTC, wbamberg commented
I'm closing this PR. The changes make the examples harder to understand and it's not obvious to me why we should in general prefer the style shown here.

2022-03-30 03:57 UTC, closed without merging