Make the ARIA spec URL in SpecData be the current spec URL
mdn/content pull request #12955
Opened 2022-02-13 06:52 UTC by sideshowbarker

The practice we’ve been following in general for spec URLs is to use the URL for whatever the current spec is — that is, the URL for the “Living” spec (aka “Editor’s Draft”).

So this change brings the ARIA spec URL in line with that practice — while adding an “ARIA 1.1” spec reference (for the latest W3C Rec).

See https://github.com/mdn/content/pull/12940 for an example of a problem that’s caused by the fact our existing docs reference the (now-obsolete and no longer maintained or updated) ARIA 1.1 Rec rather than the current ARIA spec.

2022-02-13 06:58 UTC, teoli2003 commented
I'm fine with this change, but shouldn't we get this spec link from the bcd repo that itself checks it with the w3c/browser-spec repo? (I would like to get rid of `SpecName`, `Spec2`and `SpecData.json` for this very same reason).

Pinging @estelle for her insight.

2022-02-14 06:45 UTC, sideshowbarker commented
Update: As an alternative to this PR, I’ve opened https://github.com/mdn/yari/pull/5277. If/when that gets merged:

- we’d be able to put `{{Specifications}}` into all the Specifications sections for the ARIA-attribute docs, an it’d just work
- we’d finally be able to get rid of the `SpecName`, `Spec2` macros, and the `SpecData.json` file

The way the https://github.com/mdn/yari/pull/5277 change works is that the code:

1. Checks if the article metadata has a `title` that starts with `aria-`.
2. If so, then instead of doing a BCD query to get the spec URL, it automatically generates a spec URL based on the `title`.

The reason that works is:

1. Every MDN ARIA article `title` is identical to the name of ARIA attribute it documents; e.g., `aria-keyshortcuts`.
2. The https://w3c.github.io/aria/ anchor for a particular ARIA attributes is always just the name of an attribute; for example, https://w3c.github.io/aria/#aria-keyshortcuts
3. So we can generate the spec URLs with just concatenating `https://w3c.github.io/aria` with the `title` values.

2022-02-14 13:37 UTC, ddbeck requested changes
(Review status here is less "request changes" and more "wait for further updates".)

As mentioned in https://github.com/mdn/yari/pull/5277#issuecomment-1039087145, I think https://github.com/mdn/yari/issues/4704—providing a generic spec URL field in front matter—is the way to go, which would support us in de-emphasizing SpecData. I'm going to see if this is something we can implement in short order. If it is, I propose we go ahead with that; if we can't, I'll reconsider this PR and https://github.com/mdn/yari/5277. Feel free to @ me if I haven't followed up on this in a few days.

2022-02-15 08:01 UTC, sideshowbarker commented
Superseded now by https://github.com/mdn/yari/pull/5284

2022-02-15 08:01 UTC, closed without merging