Refactored Example code.
mdn/content pull request #12954
Opened 2022-02-13 06:29 UTC by SenorGato

As seen here -> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#sending_a_synchronous_response  

The preceding code did not work, and the code from the async does.  Its also cleaner.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-13 23:52 UTC, rebloor requested changes

2022-02-13 23:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.md
> +  console.log(`content script sent a message: ${request.content}`);
```suggestion
  console.log(`A content script sent a message: ${request.content}`);
```

2022-02-13 23:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.md
> +  sendResponse({response: "response from background script"});
```suggestion
  sendResponse({response: "Response from background script"});
```

2022-02-14 17:51 UTC, rpl requested changes

2022-02-14 17:51 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.md
> +}
This looks like a left over, it doesn't seem to belong in the code snippet.

2022-02-14 17:51 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/sendmessage/index.md
> +  console.log(`A content script sent a message: ${request.content}`);
at line 102, the content script seems to be sending an object with a `"greeting"` property (and not a property named `"content"`).

2022-02-14 19:57 UTC, SenorGato reviewed
This seems to make sense to me.

2022-07-18 04:31 UTC, rebloor approved these changes

2022-08-10 17:03 UTC, rpl approved these changes
lgtm, besides a few formatting related tweaks and a `let` changed into a `const` the new version is equivalent to the previous version.

2022-08-10 17:06 UTC, merged