Javascript performance link fix
mdn/content pull request #13158
Opened 2022-02-20 16:49 UTC by JustAdams

#### Summary

Corrected link to javascript performance page in multiple pages under Performance, and removed unnecessary period at the end.

#### Motivation

Readers were unable to access the Javascript Performance page.

#### Metadata
This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2022-02-20 22:29 UTC, hamishwillee commented on files/en-us/learn/performance/business_case_for_performance/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
Thanks, but I don't think this is quite right - either the link or link text is wrong.

What I think is that the link is correct but the ext is wrong. It should just be "JavaScript performance" in all cases. On the page https://developer.mozilla.org/en-US/docs/Learn/Performance/javascript_performance this would be a self-link. That will create a "flaw" which you can ignore.

2022-03-11 07:40 UTC, teoli2003 requested changes

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/business_case_for_performance/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/css/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/html/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/javascript_performance/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/measuring_performance/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/multimedia/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/video/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:40 UTC, teoli2003 commented on files/en-us/learn/performance/why_web_performance/index.md
> +- [JavaScript performance best practices](/en-US/docs/Learn/Performance/javascript_performance)
```suggestion
- [JavaScript performance](/en-US/docs/Learn/Performance/javascript_performance)
```

2022-03-11 07:43 UTC, teoli2003 commented
I went ahead and made the suggested change that I agree with @hamishwillee is correct. A last round of review and I think this is good to go.

2022-03-11 07:43 UTC, teoli2003 approved these changes

2022-03-11 07:44 UTC, merged