Add an example for passing an object of params
mdn/content pull request #13154
Opened 2022-02-20 15:01 UTC by codebam

Works with any existing URL object

#### Summary

This example shows how to build a new URL with an object of search parameters from an existing URL that has search parameters

#### Motivation

There was no example for this online and I think it's likely a common use case

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-22 15:51 UTC, jpmedley requested changes

2022-02-22 15:51 UTC, jpmedley commented on files/en-us/web/api/urlsearchparams/urlsearchparams/index.md
> +This example shows how to build a new URL with an object of search parameters from an existing URL that has search parameters
```suggestion
This example shows how to build a new URL with an object of search parameters from an existing URL that has search parameters.
```

2022-02-23 09:15 UTC, codebam commented on files/en-us/web/api/urlsearchparams/urlsearchparams/index.md
> +This example shows how to build a new URL with an object of search parameters from an existing URL that has search parameters
Done, thanks

2022-02-23 15:06 UTC, jpmedley approved these changes

2022-02-23 15:06 UTC, merged