Add spec URLs for web/api subtree
mdn/content pull request #13198
Opened 2022-02-22 02:45 UTC by sideshowbarker

Part of https://github.com/mdn/content/issues/13126

2022-02-24 06:33 UTC, sideshowbarker commented
This is now just blocked on https://github.com/mdn/yari/pull/5314

2022-05-13 06:24 UTC, queengooborg commented
It looks like the PR that was blocking this has been merged -- would you like to give this a rebase @sideshowbarker?

2022-05-13 07:45 UTC, sideshowbarker commented
> It looks like the PR that was blocking this has been merged -- would you like to give this a rebase @sideshowbarker?

Yup, thanks for the heads-up — now rebased

2022-05-13 07:50 UTC, queengooborg reviewed
Thanks for rebasing!  Just got a couple of questions regarding some of the other changes in this PR:

2022-05-13 07:50 UTC, queengooborg commented on files/en-us/web/api/aescbcparams/index.md
> +spec-urls: https://w3c.github.io/webcrypto/#dfn-AesCbcParams
I'm noticing a lot of changes to existing spec URLs in this pull request -- while the changes look good to me, would they be better in a separate PR to keep the scope of this PR concise?

2022-05-13 07:50 UTC, queengooborg commented on files/en-us/web/api/css_object_model/css_declaration/index.md
> -  - Reference
I'm also noticing some tag changes, are these something we should keep separate?

2022-05-13 08:12 UTC, sideshowbarker commented on files/en-us/web/api/aescbcparams/index.md
> +spec-urls: https://w3c.github.io/webcrypto/#dfn-AesCbcParams
> I'm noticing a lot of changes to existing spec URLs in this pull request -- while the changes look good to me, would they be better in a separate PR to keep the scope of this PR concise?

Yup, thanks — opened https://github.com/mdn/content/pull/15982 for that

2022-05-13 08:12 UTC, sideshowbarker commented on files/en-us/web/api/css_object_model/css_declaration/index.md
> -  - Reference
> I'm also noticing some tag changes, are these something we should keep separate?

Yup, thanks — pulled those out

2022-05-13 08:28 UTC, queengooborg requested changes
LGTM, thank you!  Just got a couple of suggestions for synchronizing with BCD:

2022-05-13 08:28 UTC, queengooborg commented on files/en-us/web/api/cryptokeypair/index.md
> +spec-urls: https://w3c.github.io/webcrypto/
```suggestion
spec-urls: https://w3c.github.io/webcrypto/#keypair
```

2022-05-13 08:28 UTC, queengooborg commented on files/en-us/web/api/document/rootelement/index.md
> +spec-urls: https://svgwg.org/svg2-draft/struct.html#__svg__SVGDocument__rootElement
```suggestion
browser-compat: api.Document.rootElement
```

2022-05-13 08:28 UTC, queengooborg commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +spec-urls: https://w3c.github.io/gamepad/#gamepad-interface
```suggestion
browser-compat: api.Gamepad
```

2022-05-13 08:28 UTC, queengooborg commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
Can't reach the line below this, but we should probably simplify the macro call here?

2022-05-13 08:28 UTC, queengooborg commented on files/en-us/web/api/mediastream_recording_api/index.md
Ditto for `{{Compat}}` call!

2022-05-13 08:51 UTC, sideshowbarker commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> Can't reach the line below this, but we should probably simplify the macro call here?

Yup, thanks — fixed all those

2022-05-13 08:54 UTC, queengooborg approved these changes
Thanks for the quick changes, LGTM!

2022-05-13 08:54 UTC, merged