Fixed syntax highlighting in some WebGL examples
mdn/content pull request #132
Opened 2020-11-26 06:40 UTC by MendyBerger

Issue mdn/sprints/issues/3730

2020-11-30 11:54 UTC, chrisdavidmills requested changes
One query for you.

2020-11-30 11:54 UTC, chrisdavidmills commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
This is mostly looking good @MendyBerger. One query — all the other examples you've changed either add syntax highlighting classes or remove `<code>`, but this one is adding `<code>` in. Should this change be reverted?

2020-12-01 15:19 UTC, MendyBerger commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
It was intentional, having only `pre` without a language or `code` makes the text tiny (just 13px), since this one is not of any particular language I just added a `code` tag.

2020-12-01 21:05 UTC, peterbe commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
You should not include the `<code>`. At least you shouldn't have to. It gets injected by the builder. 
The correct syntax is:
```html
<pre class="brush: js">JAVASCRIPT CODE HERE</pre>
```
Or, you can, if you prefer:
```html
<pre class="brush: js">
JAVASCRIPT CODE HERE
</pre>
```
Note that you should never need to put the `notranslate`. It gets injected automatically too. 

If it's note JavaScript, but some stuff you want monospaced, you get the same results as if it was `class="brush: js"` but without the color highlighting. 

It's actually a flaw to put in `<code>` in there. 

If you press the "Show flaws" button on 
http://localhost:3000/en-us/docs/web/api/webgl_api/matrix_math_for_the_web#_flaws
you'll see that it says:
<img width="567" alt="Screen Shot 2020-12-01 at 4 04 32 PM" src="https://user-images.githubusercontent.com/26739/100796664-f7f20b00-33ee-11eb-9249-478f7b9859e3.png">

2020-12-01 21:05 UTC, peterbe commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
Mind you, the Wiki is different and I don't actually know what you have to put in there to make it look right.

2020-12-13 20:32 UTC, MendyBerger commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
@peterbe I see that the content repo is full of both `<code>` and `notranslate`, and when I turn on show flaws I don't see anything related to `code`, can it be that the content repo has different rules from the wiki?

2020-12-15 19:24 UTC, peterbe commented on files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.html
> +<pre class="notranslate"><code>
I'm not entirely sure I understand the question. 
But going forward, you should not need to add `notranslate` to the `class="..."` in `<pre>` tags. And you should not use `<code>` tags inside the `<pre>` tag. 
What's confusing is that, after it renders, that's exactly what happens. ...but by the machines instead of the humans. So basically what I'm saying is; don't do what the machines do for you :)

2020-12-17 04:12 UTC, MendyBerger commented
@peterbe I reverted this one change as it's not that important and I'm not exactly sure how to make it look right

2020-12-21 20:00 UTC, Rumyra commented
Just a thought - reverting sounds like a good option as I've noticed a few 'tiny code' examples & syntax boxes since the move. I would imagine this has more to do with new css than changing html conventions for in page code. However I have made an assumption here and haven't investigated yet...

2020-12-21 20:43 UTC, MendyBerger commented
@Rumyra just to clarify, do you believe that reverting the whole PR would be best?

2020-12-22 13:20 UTC, Rumyra commented
Oh goodness no @MendyBerger - apologies I was referring to noticing syntax boxes 'tiny code' of which there are none here... I'm going to have a quick look at this, but it all seems good to me 👍

2020-12-22 14:23 UTC, Rumyra approved these changes
Checked out and all the syntax highlighting looks good to me 👍 thanks @MendyBerger

2020-12-22 15:45 UTC, MendyBerger commented
Thanks @Rumyra!

2020-12-23 12:34 UTC, chrisdavidmills approved these changes

2020-12-23 12:34 UTC, merged