FF98 Relnotes, Experimental Features: hyphenate-character available by default
mdn/content pull request #13209
Opened 2022-02-22 15:24 UTC by dipikabh

#### Summary

In FF98, the `layout.css.hyphenate-character.enabled` preference is set to true by default.

- [Experimental Features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features): Removed "Property: hyphenate-character" entry from the CSS section.
- [Release Notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/98): Added information about hyphenate-character in the CSS section as it is now available by default and not behind a preference setting.

#### Supporting details

https://bugzilla.mozilla.org/show_bug.cgi?id=1751024

#### Related issues

Other related doc updates for this: https://github.com/mdn/content/issues/12580

2022-02-22 18:59 UTC, ddbeck requested changes
One little suggestion for you. Thank you!

2022-02-22 18:59 UTC, ddbeck commented on files/en-us/mozilla/firefox/releases/98/index.md
> +- The {{cssxref("hyphenate-character")}} property can be used to set a string that is used instead of a hyphen character (`-`) at the end of a hyphenation line break. (See {{bug(1751024)}} for more d
```suggestion
- The {{cssxref("hyphenate-character")}} property can be used to set a string that is used instead of a hyphen character (`-`) at the end of a hyphenation line break ({{bug(1751024)}}).
```

I think just linking to the bug (or being very minimalist with something like "see bug 123") is more conventional for the release notes and MDN generally.

2022-02-23 09:22 UTC, dipikabh commented
@ddbeck Thanks for reviewing!
The suggestion makes sense. I have updated the text.

2022-02-24 16:04 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-02-24 16:04 UTC, merged