Adding navigator.requestMIDIAccess page
mdn/content pull request #13212
Opened 2022-02-22 16:22 UTC by Rumyra

#### Summary

Adding `navigator.requestMIDIAccess()` page and updating navigator page to add method

#### Motivation

#### Supporting details

#### Related issues

Part of https://github.com/mdn/content/issues/12792

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-22 17:03 UTC, jpmedley requested changes

2022-02-24 12:31 UTC, Rumyra commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +The **`requestMIDIAccess()`** method of the {{domxref('Navigator')}} interface.
```suggestion
The **`requestMIDIAccess()`** method of the {{domxref('Navigator')}} interface
```

2022-02-24 12:34 UTC, Rumyra commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +  - : If the user or system denies the application from creating a [MIDIAccess](/en-US/docs/Web/API/MIDIAccess) object with the requested options, or if the document is not allowed to use the feature
```suggestion
  - : If the user or system denies the application from creating a [MIDIAccess](/en-US/docs/Web/API/MIDIAccess) object with the requested options, or if the document is not allowed to use the feature (for example in the case of an iframe without the correct [feature policy](/en-US/docs/Web/HTTP/Feature_Policy)).
```

2022-02-24 12:35 UTC, Rumyra commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +The **`Navigator.requestMIDIAccess()`** method
Which bit are you referring to @jpmedley - the sidebar?

2022-02-24 12:36 UTC, Rumyra commented
Thanks for the review @jpmedley 👍 appreciated - only one query from me :)

2022-02-24 17:38 UTC, jpmedley approved these changes

2022-02-25 13:55 UTC, dipikabh requested changes
Hi @Rumyra, I've suggested a few edits for your consideration.

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +This method prompts the user for access to MIDI devices available to their system. If the user grants permission then the {{jsxref('Promise')}} resolves and a [`MIDIAccess`](/en-US/docs/Web/API/MIDIA
```suggestion
The **`requestMIDIAccess()`** method of the {{domxref('Navigator')}} interface
returns a {{jsxref('Promise')}} representing a request for access to Musical Instrument Digital Interface (MIDI) devices on a user's system. This method is part of the [Web MIDI API](/en-US/docs/Web/API/Web_MIDI_API).

This method prompts the user for access to MIDI devices available to their system. If the user grants permission, the {{jsxref('Promise')}} resolves and a [`MIDIAccess`](/en-US/docs/Web/API/MIDIAccess) object is returned. This method provides a means for accessing, enumerating, and manipulating MIDI devices.
```

- **acronym**: I've expanded MIDI since this is its first occurrence on this page.
- **which**: I've suggested a split of the second sentence to avoid ambiguity about what 'which' is referring to. I've also moved part of the split sentence to second paragraph.
- **word usage**: Please check if "provides" conveys the intended meaning better than "defines".
- **list order and comma**: minor suggestion for updating list to "accessing, enumerating, and manipulating" and added comma before the last 'and' in in the list

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +      - : A {{jsxref('Boolean')}} value which, if set to `true`, allows the ability to send and receive system exclusive (sysex) messages. Default is `false`.
```suggestion
      - : A {{jsxref('Boolean')}} value that, if set to `true`, allows the ability to send and receive system exclusive (sysex) messages. The default value is `false`.
```

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +      - : A {{jsxref('Boolean')}} value which, if set to `true`, allows the system to utilize any installed software synthesizers. Default is `false`.
```suggestion
      - : A {{jsxref('Boolean')}} value that, if set to `true`, allows the system to utilize any installed software synthesizers. The default value is `false`.
```

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +  - : If the underling system raises any errors.
Do you mean 'underlying'?

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +  - : If the user or system denies the application from creating a [MIDIAccess](/en-US/docs/Web/API/MIDIAccess) object with the requested options, or if the document is not allowed to use the feature
```suggestion
  - : If the user or system denies the application from creating a [MIDIAccess](/en-US/docs/Web/API/MIDIAccess) object with the requested options, or if the document is not allowed to use the feature (for example, an iframe without the correct [feature policy](/en-US/docs/Web/HTTP/Feature_Policy)).
```

2022-02-25 13:55 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +In the following example the {{domxref("Navigator.requestMIDIAccess()")}} method returns the {{domxref("MIDIAccess")}} object, which gives access to information about the input and output MIDI ports.
```suggestion
In the following example, the {{domxref("Navigator.requestMIDIAccess()")}} method returns the {{domxref("MIDIAccess")}} object, which gives access to information about the input and output MIDI ports.
```

2022-02-25 15:26 UTC, Rumyra commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +This method prompts the user for access to MIDI devices available to their system. If the user grants permission then the {{jsxref('Promise')}} resolves and a [`MIDIAccess`](/en-US/docs/Web/API/MIDIA
* I think we keep 'Musical Instrument Digital Interface' for the api landing page (https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API). It makes the explanation here very convoluted.
* The API provides the means for enumerating etc the MIDI devices - but I don't want to repeat 'Web MIDI API' so suggestion for this is welcome
* It provides - something is returned by the method 👍 
* Yeh we do do a comma before 'and' I don't like it tho 😆

2022-02-25 16:27 UTC, dipikabh commented on files/en-us/web/api/navigator/requestmidiaccess/index.md
> +This method prompts the user for access to MIDI devices available to their system. If the user grants permission then the {{jsxref('Promise')}} resolves and a [`MIDIAccess`](/en-US/docs/Web/API/MIDIA
> * I think we keep 'Musical Instrument Digital Interface' for the api landing page (https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API). It makes the explanation here very convoluted.
>
👍  
>
>  * The API provides the means for enumerating etc the MIDI devices - but I don't want to repeat 'Web MIDI API' so suggestion for this is welcome
> 
In that case, your original sentence was correct! Sorry for this confusion. Only a comma would be needed before 'which':
"This method is part of the [Web MIDI API](/en-US/docs/Web/API/Web_MIDI_API), which defines a means for enumerating, manipulating, and accessing MIDI devices."

If we all are to stick to the same style guide (Oxford), I guess it would be nice to have the comma before the 'and' 🙂.
>
>
>     * It provides - something is returned by the method 👍
> 
>     * Yeh we do do a comma before 'and' I don't like it tho 😆

Hope you'll be adding the comma after "If the user grants permission"

2022-03-02 14:19 UTC, Rumyra commented
@dipikabh I've address all the feedback - let me know what you think. If it's good you can approve it and press the big green button :D

2022-03-02 17:53 UTC, dipikabh approved these changes

2022-03-02 18:02 UTC, merged

2022-03-03 11:38 UTC, Rumyra commented
Thanks @dipikabh 👍