Add compat table process doc
mdn/content pull request #13235
Opened 2022-02-23 18:28 UTC by ddbeck

#### Summary

Document selection criteria and process for browsers in compat tables

#### Motivation

Mostly, to be transparently answer https://github.com/mdn/content/issues/12742, but also to make the whole process a bit less opaque and ad hoc.

This mostly recapitulates the process we last completed with the Deno project.

#### Related issues

* https://github.com/mdn/content/issues/12742
* https://github.com/mdn/browser-compat-data/pull/14629

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-23 18:35 UTC, ddbeck commented
@Rumyra click "details" for the Netlify deploy-preview in the checks list above, to see a fully built version of this.

2022-03-02 16:12 UTC, Rumyra requested changes

2022-03-02 16:12 UTC, Rumyra commented on meta/content/en/governance/browser-compatability.md
> +MDN uses browser compatibility to generate browser compatibility tables (plus some other site content). MDN uses the data as provided, including:
```suggestion
MDN uses browser compatibility data to generate browser compatibility tables (plus some other site content). MDN uses the data as provided, including:
```

2022-03-02 16:12 UTC, Rumyra commented on meta/content/en/governance/browser-compatability.md
> +Whether your your recommendation is selected, deferred, or rejected, we'll follow up in the GitHub discussion with next steps.
```suggestion
Whether your recommendation is selected, deferred, or rejected, we'll follow up in the GitHub discussion with next steps.
```

2022-03-02 16:14 UTC, Rumyra commented
@ddbeck I reviewed - it all looks good to me. One thing was I couldn't seem to access a preview of the page via Details -> Netlify - there are preview links there, but not one for the bcd page 🤔 unless I'm missing something

2022-03-02 16:38 UTC, ddbeck commented
> @ddbeck I reviewed - it all looks good to me. One thing was I couldn't seem to access a preview of the page via Details -> Netlify - there are preview links there, but not one for the bcd page 🤔 unless I'm missing something

Shows here for me: https://deploy-preview-13235--mdn-contributor-docs.netlify.app/governance/browser-compatability/ Does it not work for you?

2022-03-03 13:53 UTC, Rumyra commented
> Shows here for me: https://deploy-preview-13235--mdn-contributor-docs.netlify.app/governance/browser-compatability/ Does it not work for you?

It does @ddbeck - I think I wasn't checking the right bcd link from the left navigation 🙈

2022-03-04 13:47 UTC, Rumyra approved these changes

2022-03-04 13:47 UTC, merged