FF98 Relnotes, Experimental Features: <dialog> available by default
mdn/content pull request #13232
Opened 2022-02-23 17:03 UTC by dipikabh

#### Summary

In FF98, the `dom.dialog_element.enabled` preference is set to true by default.

- [Experimental Features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features): Removed "Element: <dialog>" entry from the HTML section.
- [Release Notes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/98): Added information about <dialog> in the HTML section as it is now available by default and not behind a preference setting.

#### Motivation

#### Supporting details

https://bugzilla.mozilla.org/show_bug.cgi?id=1733536

#### Related issues

Other related doc updates: https://github.com/mdn/content/issues/12578

2022-02-24 05:11 UTC, sideshowbarker commented on files/en-us/mozilla/firefox/releases/98/index.md
> +- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default. ({{bug(1733536)}})
```suggestion
The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default. ({{bug(1733536)}})
```

2022-02-24 18:49 UTC, ddbeck commented on files/en-us/mozilla/firefox/releases/98/index.md
> +- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default. ({{bug(1733536)}})
```suggestion
- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default ({{bug(1733536)}}). 
```

for consistency with the other PR where we discussed this sort of thing?

2022-02-24 18:50 UTC, ddbeck requested changes

2022-02-24 18:50 UTC, ddbeck commented on files/en-us/mozilla/firefox/releases/98/index.md
> +- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default. ({{bug(1733536)}})
```suggestion
- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default ({{bug(1733536)}}). 
```

for consistency with the other PR where we discussed this sort of thing?

2022-02-28 10:21 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/98/index.md
> +- The HTML {{HTMLElement("dialog")}} element and its associated DOM APIs provide support for HTML-based modal dialog boxes. This element is now available by default. ({{bug(1733536)}})
Yes, of course. Thanks for reviewing @ddbeck!

2022-02-28 15:10 UTC, ddbeck approved these changes
Thank you! 🎉

2022-02-28 15:10 UTC, merged