JS Learn: update client-side APIs, part 5
mdn/content pull request #13268
Opened 2022-02-25 01:51 UTC by wbamberg

Part of https://github.com/mdn/content/issues/10337, the project to modernize the JS Learning Area.

This is the fifth PR that updates the final module, [Client-side web APIs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs). It makes minor updates to the fifth article, [Drawing graphics](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics).

Many of the changes here are to reflect some juggling of example code in mdn/learning-area, especially to have JS in separate files. So this PR has a corresponding PR in mdn/learning-area: both PRs should be merged together, and changes in one will need corresponding changes in the other one. For that reason I'm marking it draft, although it is ready for review.

2022-03-09 14:23 UTC, Elchi3 requested changes

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/0_canvas_start) directory. It contains three files
0_canvas_start is just a folder with an index.html. Maybe you want 1_canvas_template here? (but that contains 5 files). Something is off.


```suggestion
1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template) directory. It contains three files:
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. First of all, take a copy of your newly coded canvas template (or make a local copy of the [1_canvas_template](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/get
```suggestion
1. First of all, take a copy of your newly coded canvas template (or make a local copy of the [1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template) directory if you didn't follow the above steps).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [2_canvas_rectangles](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/2_canvas_rectangles/).
```suggestion
> **Note:** The finished code is available on GitHub as [2_canvas_rectangles](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/2_canvas_rectangles/).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +Let's start the section off by making a fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/1_canv
```suggestion
Let's start the section off by making a fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template)), in which to draw the new example.
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [3_canvas_paths](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/3_canvas_paths/).
```suggestion
> **Note:** The finished code is available on GitHub as [3_canvas_paths](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/3_canvas_paths/).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +Canvas also has features for drawing text. Let's explore these briefly. Start by making another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/master
```suggestion
Canvas also has features for drawing text. Let's explore these briefly. Start by making another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template/)) in which to draw the new example.
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [4_canvas_text](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/4_canvas_text/).
```suggestion
> **Note:** The finished code is available on GitHub as [4_canvas_text](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/4_canvas_text/).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. As before, make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/1_canvas_template/)
```suggestion
1. As before, make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template/)) in which to draw the new example.
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [5_canvas_images](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/5_canvas_images/).
```suggestion
> **Note:** The finished code is available on GitHub as [5_canvas_images](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/5_canvas_images/).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. Make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/1_canvas_template)) and open i
```suggestion
1. Make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template)) and open it in your code editor.
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [6_canvas_for_loop](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/loops_animation/6_canvas_for_loop/).
```suggestion
> **Note:** The finished code is available on GitHub as [6_canvas_for_loop](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/loops_animation/6_canvas_for_loop/).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. Make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/1_canvas_template)) and open i
```suggestion
1. Make another fresh copy of our canvas template ([1_canvas_template](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template)) and open it in your code editor.
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [7_canvas_walking_animation](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/loops_animation/7_canvas_walking
```suggestion
> **Note:** The finished code is available on GitHub as [7_canvas_walking_animation](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/loops_animation/7_canvas_walking_animation).
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +The example can be found on GitHub as [8_canvas_drawing_app](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/loops_animation/8_canvas_drawing_app), and you can play
```suggestion
The example can be found on GitHub as [8_canvas_drawing_app](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/loops_animation/8_canvas_drawing_app), and you can play with it live below:
```

2022-03-09 14:23 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. To start with, make a local copy of [threejs-cube/index.html](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/threejs-cube/index.html) in a new folder, then save
```suggestion
1. To start with, make a local copy of [threejs-cube/index.html](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/threejs-cube/index.html) in a new folder, then save a copy of [metal003.png](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/threejs-cube/metal003.png) in the same folder. This is the image we'll use as a surface texture for the cube later on.
```

2022-03-09 23:52 UTC, wbamberg commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/0_canvas_start) directory. It contains three files
> 0_canvas_start is just a folder with an index.html. Maybe you want 1_canvas_template here? (but that contains 5 files). Something is off.

Yeah.... I just pushed https://github.com/mdn/learning-area/pull/463/commits/5ba2ca4a478110dd702096611f21229cd92a2460 to learning-area which should I hope fix this.

2022-03-10 07:31 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/1_canvas_template) directory. It contains three file
```suggestion
1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/main/javascript/apis/drawing-graphics/getting-started/0_canvas_start) directory. It contains three files:
```

2022-03-10 07:32 UTC, Elchi3 commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +1. First make a local copy of the [0_canvas_start](https://github.com/mdn/learning-area/blob/master/javascript/apis/drawing-graphics/getting-started/0_canvas_start) directory. It contains three files
Ah okay, yes, this makes sense. I'm just adding a commit here then that undos my wrong suggestion as we still want 0_canvas_start here and not 1_canvas_template.

2022-03-10 14:17 UTC, Elchi3 approved these changes

2022-03-10 16:51 UTC, merged