A typo
mdn/content pull request #13274
Opened 2022-02-25 11:17 UTC by mili91

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-02-25 18:44 UTC, jpmedley requested changes

2022-02-25 18:44 UTC, jpmedley commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, be in several windows, iframes or even workers.
```suggestion
  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, and be in several windows, iframes or even workers.
```

2022-02-25 18:55 UTC, Sly-Ozc-34 commented
1

2022-02-25 18:57 UTC, Sly-Ozc-34 commented
Sly

2022-02-25 19:12 UTC, wbamberg commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, be in several windows, iframes or even workers.
That doesn't make sense. What this paragraph wants to say (I think) is "can be accessed from several browsing contexts (i.e. windows, tabs, or even other workers)". So "being" was intentional here, although it's a terribly clumsy expression. See also the first para of the linked page:

> The SharedWorker interface represents a specific kind of worker that can be accessed from several browsing contexts, such as several windows, iframes or even workers. 

This is actually wrong though, isn't it? Because a worker isn't a browsing context. So perhaps it would be better to say:

> "can be accessed from several browsing contexts (i.e. windows, tabs, or iframes) or even other workers".

2022-02-25 19:44 UTC, jpmedley commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, be in several windows, iframes or even workers.
That last one sounds better to me.

2022-03-01 01:32 UTC, wbamberg commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, be in several windows, iframes or even workers.
```suggestion
  - : Represents a specific kind of worker that can be accessed from several {glossary("browsing context", "browsing contexts")}} (i.e. windows, tabs, or iframes) or even other workers
```

2022-03-01 01:36 UTC, wbamberg commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be accessed from several {glossary("browsing context", "browsing contexts")}} (i.e. windows, tabs, or iframes) or even other workers.
```suggestion
  - : Represents a specific kind of worker that can be accessed from several {{glossary("browsing context", "browsing contexts")}} (i.e. windows, tabs, or iframes) or even other workers.
```

2022-03-01 03:29 UTC, wbamberg approved these changes
👍 thank you!

2022-03-01 03:30 UTC, wbamberg commented on files/en-us/web/api/web_workers_api/index.md
> +  - : Represents a specific kind of worker that can be _accessed_ from several {{glossary("browsing context", "browsing contexts")}}, be in several windows, iframes or even workers.
@jpmedley , I pushed the change as suggested. If you approve, we can merge this. Thanks!

2022-03-11 07:33 UTC, teoli2003 approved these changes

2022-03-11 07:35 UTC, teoli2003 commented
@jpmedley When you have some time, can you check this here? (Trying to get easy PRs off the backlog)

2022-03-14 13:53 UTC, jpmedley approved these changes

2022-03-14 13:53 UTC, merged