Fixed a typo
mdn/content pull request #13445
Opened 2022-03-03 12:13 UTC by Wilson-Emmanuel

Summary
I removed a wrongly placed word to make a statement more easily understandable.
I also added a word to make the flow seamless.

Motivation
I could not understand the sentence in my first read due to the typo. 
Correcting it makes it easier for other readers to understand the statement without any disruption.

 Supporting details
[](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#html_ordered_lists)

Related issues
N/A

Metadata
N/A

This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [:white_check_mark ] Fixes a typo, bug, or other error

2022-03-04 01:08 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element, and trying to
Thanks! This fixes the clear grammatical error, but I'm still confused by what the paragraph is trying to tell us. 

First thing is that if you run this on chrome it makes no sense, because the `s` modifier isn't supported (off spec). So you have a statement that you need to modifier but the case without the modifier is the one that is selected. On Firefox this does work.

What I think this is saying is that "Normally you can match case insensitively, but for ordered lists, you can't - you have to match case sensitively, which implies you need to use the case sensitive modifier. Is that correct?

2022-03-04 03:34 UTC, Wilson-Emmanuel commented on files/en-us/web/css/attribute_selectors/index.md
> +The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element, and trying to
Thank you for your review. I think your understanding is as good as mine. At first, I could not understand the paragraph clearly because even the "case sensitive" modifier does not work on Chrome. But it worked when tested it on Firefox, which is actually in line with table on "Browser compatibility" section.

So, I believe the paragraph is correct (except for the typo, which I fixed), but the confusion comes from the sample used. In the sample, "the case without the modifier is the one that is selected", which is NOT in line with the statements in the paragraph. 

I believe they executed the sample on a browser that does not support the "case sensitive" modifier, probably Chrome.
Do you think the result of the sample should be explained more? Perhaps, include a case a where the "case sensitive" modifier is selected?

2022-03-05 17:51 UTC, NiedziolkaMichal commented on files/en-us/web/css/attribute_selectors/index.md
> +The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element, and trying to
I think with proposed change paragraph is clear, but example brings confusion. Maybe it would be better to make it:
```
/* List types require the case sensitive flag due to a quirk in how HTML treats the type attribute. */
ol[type="a" s] {
  list-style-type: lower-alpha;
  background: red;
}

ol[type="A" s] {
  list-style-type: upper-alpha;
  background: lime;
}
```
Because of that, background will stay white for browsers not supporting s flag. HTML could also be changed to:
```
<ol type="A">
  <li>List with lime background when s flag is supported</li>
</ol>
```
What do you think?

2022-03-05 18:15 UTC, Wilson-Emmanuel commented on files/en-us/web/css/attribute_selectors/index.md
> +The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element, and trying to
This also makes sense but the issue is the LIve sample changes based on the viewer's browser. Trying viewing this link on Chrome and Firefox. Chrome does not support the "case sensitive" modifier with the "type" attribute. 
Correcting the error would involve removing the hosted live sample or changing it with css so it would display correctly in all browsers.

https://pr13445.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Attribute_selectors/_sample_.html_ordered_lists.html

2022-03-07 00:12 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element, and trying to
I ignored the comment and just tested this. What this shows is that both Chrome and Firefox do a case insensitive match if the `s` flag is not specified _for this example_. However chrome does not support the `s` flag and will completely ignore any match if `s` is specified. So the comment definitely doesn't reflect observed behaviour.

Then I did what I should have done in the first place - [looked at the spec](https://drafts.csswg.org/selectors/#attribute-case). According to this the case sensitivity can be forced with `i` and `s`, but otherwise depends on the document languages. So again, the statement is simply wrong.

2022-03-07 00:13 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +Using attribute selectors on {{HTMLElement("ol", "Ordered lists")}} is the same as for other elements: the case sensitivity of the selection depends on the document language.
OK, I've completely updated this, following testing, as discussed in https://github.com/mdn/content/pull/13445#discussion_r820310186

@Wilson-Emmanuel @NiedziolkaMichal Seem reasonable?

@dipikabh Any thoughts on this?

2022-03-07 11:52 UTC, NiedziolkaMichal commented on files/en-us/web/css/attribute_selectors/index.md
> +Using attribute selectors on {{HTMLElement("ol", "Ordered lists")}} is the same as for other elements: the case sensitivity of the selection depends on the document language.
No, that's not true. I didn't find information about this in WHATWG specification, but on Chrome & Firefox attribute type is treated differently than others.
Try out this code and you will see that only the first division has red background.
```
<style>
	*[type=R] {
		background-color: red;
	}
	*[typealt=R] {
		background-color: red;
	}
</style>
<div type="r">First Line</div>
<div typealt="r">Second Line</div>
```

2022-03-08 05:23 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +Using attribute selectors on {{HTMLElement("ol", "Ordered lists")}} is the same as for other elements: the case sensitivity of the selection depends on the document language.
```suggestion
The HTML specification requires the {{htmlattrxref("type", "input")}} attribute to be matched case-insensitively due to it primarily being used in the {{HTMLElement("input")}} element.
```

2022-03-08 05:27 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +  <li>Red background if case-insensitive matching for current document language.</li>
```suggestion
  <li>Red background if case-insensitive matching (default for the type selector).</li>
```

2022-03-08 05:33 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +Using attribute selectors on {{HTMLElement("ol", "Ordered lists")}} is the same as for other elements: the case sensitivity of the selection depends on the document language.
Thanks @NiedziolkaMichal , I have reverted that section about the requirement for case-insensitivity back to the original - because it does match the observed behavior. 

The other original text "trying to use attribute selectors to with the {{htmlattrxref("type", "ol")}} attribute of an {{HTMLElement("ol", "ordered list")}} doesn't work without the [case-sensitive](#case-sensitive) modifier." Is clearly wrong, since it does work. So I have retained the new sentences below. Make sense?

>  That list contains 46 attributes, while there are defined 160 attributes in total. I believe it's worth to mention it in the document.

The original statement that kicked this off was about ordered lists being different. My thinking is that what we have shown above is that they are not - they follow the spec. 

So perhaps this whole "[HTML ordered lists](https://pr13445.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/Attribute_selectors#html_ordered_lists)" section should be modified to "Case sensitivity" and expanded out as an example.

But lets get this bug fixed first.

2022-03-08 11:58 UTC, NiedziolkaMichal commented on files/en-us/web/css/attribute_selectors/index.md
> +Using attribute selectors on {{HTMLElement("ol", "Ordered lists")}} is the same as for other elements: the case sensitivity of the selection depends on the document language.
Well, type attribute in ordered list surely doesn't work as expected, without case-sensitive modifier. Value of property list-style-type is determined based on value of attribute type and it's letter case.
These are CSS rules that WHATWG specification presents:
```
ol[type="1"], li[type="1"] { list-style-type: decimal; }
ol[type=a s], li[type=a s] { list-style-type: lower-alpha; }
ol[type=A s], li[type=A s] { list-style-type: upper-alpha; }
ol[type=i s], li[type=i s] { list-style-type: lower-roman; }
ol[type=I s], li[type=I s] { list-style-type: upper-roman; }
ul[type=none i], li[type=none i] { list-style-type: none; }
ul[type=disc i], li[type=disc i] { list-style-type: disc; }
ul[type=circle i], li[type=circle i] { list-style-type: circle; }
ul[type=square i], li[type=square i] { list-style-type: square; }
```
Without case-sensitive modifier, it is not possible to choose proper list-style-type and that's what deleted sentence tries to say.

2022-03-10 13:08 UTC, dipikabh requested changes
Hi @hamishwillee, thanks for rewriting and expanding the example. It improves the clarity of the content markedly! 🎉 

In the example "Result" frame, I have suggested replacing "flag" with "modifier" to maintain consistency with the verbiage in the preceding paragraph where these modifiers are introduced.

In the original example, the CSS had two instances of the `s` modifier:
ol[type="a" s] {
  list-style-type: lower-alpha;
  background: lime;
}

ol[type="A" s] {
  list-style-type: upper-alpha;
  background: lime;
}

Unfortunately, both specified the same `background` color, so I am not sure which one took precedence. Is this a scenario worth explaining in addition to the current improvements?

2022-03-11 00:49 UTC, hamishwillee commented on files/en-us/web/css/attribute_selectors/index.md
> +Note that if the modifiers are not supported by the user agent, then the selector will not match.
No. 

If you specify the modifier then modifier is an intrinsic and inseparable part of the selection process. If the modifier is not understood then there can't be a match - there is no fallback to "just the bit I normally do" (e.g. case insensitive or whatever).

That's what the sentence says. 

The

2022-03-11 01:30 UTC, hamishwillee commented
Thanks for the feedback @dipikabh - I've accepted the changes and responded to the question.

> Unfortunately, both specified the same background color, so I am not sure which one took precedence. Is this a scenario worth explaining in addition to the current improvements?

No, because precedence in CSS is always the same: the last occurring most-specific selector wins.

2022-03-11 09:49 UTC, dipikabh approved these changes
Thanks @hamishwillee. Looks good! 🎉

2022-03-11 09:54 UTC, merged

2022-03-14 00:38 UTC, hamishwillee commented
Thanks all for the bug report, help, advice, and review :-)