Draft: Major Update: treegrid role
mdn/content pull request #13474
Opened 2022-03-04 02:36 UTC by estelle

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-22 01:20 UTC, ericwbailey requested changes

2022-03-22 01:20 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +When creating an accessible treegrid, moving focus among rows and cells of the grid with a keyboard must be implemented. Moving focus into the grid may result in the first cell or the first row being
```suggestion
Being able to move focus among rows and cells of the grid with a keyboard must be implemented in order to create an accessible treegrid. Moving focus into the grid may result in the first cell or the first row being focused. Whether focus goes to the next adjacent cell or the row depends on its content requirements, with some treegrids not providing focus to rows.
```

2022-03-22 01:31 UTC, ericwbailey requested changes

2022-03-22 01:59 UTC, ericwbailey requested changes

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +
```suggestion

```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +If the `treegrid` allows the user to choose just one item for an action, then it is known as a "single-select" treegrid. In single-select treegrids, the item with focus also has a selected state set
```suggestion
### Single and multi-select treegrids

If the `treegrid` allows the user to choose just one item for an action, then it is known as a **single-select** treegrid. In single-select treegrids, the item with focus also has a selected state set with [`aria-selected`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected). 
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +In cases where a child `row` or `rowgroup` is not nested within the `treegrid` in the DOM, the [`aria-owns`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns) attribute, referencing all of the
```suggestion
### Orphan rows

In cases where a child `row` or `rowgroup` is not nested within the `treegrid` in the DOM, the [`aria-owns`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns) attribute, referencing all of the IDs of the non-descendant children must be set on the `treegrid` element. If rows or cells are included in a treegrid via `aria-owns`, they will be presented to assistive technologies after the DOM descendants of the `treegrid` element unless the grid's actual DOM descendants are also included in the `aria-owns` attribute.
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +If some rows or columns are not in the DOM and are dynamically loaded when scrolling, [`aria-colcount`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colcount), [`aria-rowcount`](/en-US/docs/Web
```suggestion
### Treegrids with dynamically loaded content

If some rows or columns are not in the DOM and are dynamically loaded when scrolling, [`aria-colcount`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colcount), [`aria-rowcount`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-rowcount), [`aria-colindex`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-colindex) and [`aria-rowindex`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-rowindex) come into play. The `aria-colcount` and `aria-rowcount` properties get set on the `treegrid`. The values being the total number of columns and rows of the fully loaded grid, respectively. The indexes for each row and column get set on individual cells, not on the `treegrid` element.
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +The element with the role of `treegrid` must have an accessible name. If an appropriate label is visible in the content, provide the name via [`aria-labelledby`](/en-US/docs/Web/Accessibility/ARIA/At
```suggestion
### A treegrid's accessible name, description, and focus

The element with the role of `treegrid` must have an accessible name. If an appropriate label is visible in the content, provide the name via [`aria-labelledby`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby). In other words, if there is an element in the user interface that serves as a label for the treegrid, include `aria-labelledby` as an attribute on the element with the role of `treegrid`, and set the value of the attribute to the `id` of the labelling element or elements. If no visible label is present, use [`aria-label`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) instead. Not both.
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +If the treegrid provides sort functions, the [`aria-sort`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort) attribute is included on relevant header cell elements, not on the grid itself.
```suggestion
### Treegrid sorting

If the treegrid provides sort functions, the [`aria-sort`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort) attribute is included on relevant header cell elements, not on the grid itself. 
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +If the `treegrid` has an attached [`menu`](/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role/) that opens when Right clicked, include [`aria-haspopup="true"`](/en-US/docs/Web/Accessibility/ARIA/Attr
```suggestion
### Treegrid menus

If the `treegrid` has an attached [`menu`](/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role/) that opens when right clicked, include [`aria-haspopup="true"`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup) on the the `treegrid` element. This informs assistive technologies that the `treegrid` has an associated popup. The ability for both keyboard and pointer device users to open and set focus in the menu must be added with JavaScript.
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +By default, treegrids are assumed to be editable. If a tree grid is not editable, use the [`aria-readonly`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-readonly) attribute to inform assistive
```suggestion
### Read-only treegrids

By default, treegrids are assumed to be editable. If a tree grid is not editable, use the [`aria-readonly`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-readonly) attribute to inform assistive technologies the `treegrid` is readonly. The attribute value, when set on the element with the `treegrid` role, propagates down to all  `columnheader`, `rowheader`, and `gridcell` elements. That global value can be overriden for individual `gridcell` elements by including `aria-readonly` on individual tree grid element descendants.
```

2022-03-22 01:59 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +<table>
```suggestion
<table>
```

2022-03-28 22:49 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/treegrid_role/index.md
> +<table>
I had used tables because the right cells had multiple lines, and markdown has limitations, but they didn't need to. converted to dl.

2022-03-31 02:08 UTC, ericwbailey approved these changes
Thanks!

2022-03-31 02:08 UTC, merged