Update splice docs
mdn/content pull request #1351
Opened 2021-01-15 13:17 UTC by tasawar-hussain

Make the description more readable and understandable

2021-01-19 06:08 UTC, sideshowbarker approved these changes

2021-01-19 06:08 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/splice/index.html
> +<h3 id="Remove_2_elements_before_index_2">Remove 2 elements bfore index 2</h3>
```suggestion
<h3 id="Remove_2_elements_before_index_2">Remove 2 elements before index 2</h3>
```

2021-01-19 06:09 UTC, sideshowbarker requested changes

2021-01-19 06:09 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/splice/index.html
> +<h3 id="Remove_2_elements_before_index_2">Remove 2 elements bfore index 2</h3>
```suggestion
<h3 id="Remove_2_elements_before_index_2">Remove 2 elements before index 2</h3>
```

2021-02-24 03:59 UTC, sideshowbarker approved these changes

2021-02-24 04:02 UTC, merged

2021-02-24 04:02 UTC, sideshowbarker commented
Tasawar, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

2021-02-25 04:21 UTC, wbamberg commented
I'm not sure about this. This example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#remove_2_elements_from_index_2 seems to be removing 2 elements *starting at* index 2:

```js
let myFish = ['parrot', 'anemone', 'blue', 'trumpet', 'sturgeon']
let removed = myFish.splice(2, 2)
myFish        // [ "parrot", "anemone", "sturgeon" ]
```

I'm not sure "Remove 2 elements *before* index 2" is a correct way to describe this. "Remove 2 elements *starting from* index 2" might be an improvement though.

Or am I confused here?

2021-02-25 05:38 UTC, sideshowbarker commented
> I'm not sure "Remove 2 elements _before_ index 2" is a correct way to describe this. "Remove 2 elements _starting from_ index 2" might be an improvement though.
> 
> Or am I confused here?

You’re not confused. I should’ve been more careful in reviewing this. I’ve opened https://github.com/mdn/content/pull/2679 with a fix.