Update: Internal implemenation of array.sort()
mdn/content pull request #13681
Opened 2022-03-09 08:04 UTC by anandsr21harshit

#### Summary

This piece will help the reader understand how arra.sort() works internally. As a beginner, we have question on how sort() function is comparing two values and then add it to array.

#### Motivation

I know many sorting algorithims and how they work. But there was no explanation of how array.sort() works internally in JavaScript. It just said that based on return value of compareFunction ( <0 , >0 , === 1) it will sort. But element element implementation was not there. Mainly because sort() does not have fixed implementation. Still I have added a code snippet that will help reader to understand in depth

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-09 08:09 UTC, teoli2003 requested changes

2022-03-09 08:09 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +// compare: 8 25
I think we should add a sentence making it clear that this is a possible result (For example, Firefox is more performant than this).

2022-03-09 08:18 UTC, anandsr21harshit commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +// compare: 8 25
Are you saying that this can be one result among different possible results?

2022-03-09 08:25 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +// compare: 8 25
Exactly:
![Capture d’écran 2022-03-09 à 09 25 32](https://user-images.githubusercontent.com/1466293/157401860-4ab657da-726e-45f7-b04e-f38a8a69c616.png)

2022-03-09 08:27 UTC, anandsr21harshit commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +// compare: 8 25
Great. I'll update my content then

2022-03-09 08:35 UTC, anandsr21harshit commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +// compare: 8 25
I have updated the content

2022-03-09 08:41 UTC, teoli2003 requested changes
We are almost ready to merge this.

2022-03-09 08:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +The above result is one of the possible result. You will get the above output on Mozilla, while Chrome and Edge will give different result. However, the final sorted array will be same on every brows
```suggestion
The above result is one of the possible results. You will get the above output on Firefox, while Chrome and Edge will give different results. However, the final sorted array will be the same on every browser.
```

2022-03-09 08:43 UTC, sideshowbarker commented
It’s not clear to me how much can usefully be said about the characteristics implementations of `sort` in JavaScript runtimes — or why we want to even try. What’s the use case for trying to state this information in MDN? In what specific ways might it help web developers in practice?

Some specific feedback I got from asking about this in the TC39 Matrix room:

> I'd rather just say "the sort implementation can vary among engines, so there is no guarantee about the order array elements are compared or how many times `compareFn` is called"

On the face of it, that seems at least like a more useful statement than what’s proposed in this PR. Is there some reason to say anything more than that.

Other feedback:

> I find mentioning the array length to be confusing, since in the general case sort algorithms are expected to be O(n*log(n)) or O(n²) (regardless of what JS engines do)

2022-03-31 04:59 UTC, teoli2003 commented
Most of the time you don't care about the algorithmic complexity of the algorithms, but sometimes (especially when combining algorithms) you really want to avoid O(n^2). Unfortunately, there are no boundaries in the JS spec so each implementation is different and although there tend to use efficient algorithms we can't really know what they do.

So I think now that adding this will be a nightmare to maintain and we should do this everywhere, which we won't.

To the OP: thanks for the PR, but I will close it.

2022-03-31 04:59 UTC, closed without merging