changed gif image
mdn/content pull request #13739
Opened 2022-03-10 18:21 UTC by maridoroshuk

#### Summary

Changed gif image in accordance to text (Closes issue #13702) 
#### Motivation

> The image shows a [Higher-order curves](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Higher-order_curves) while the text describes a [Quadratic curves](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Quadratic_curves). This thing can create confusion in the readers.
#### Supporting details

#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-03-10 22:46 UTC, rebloor commented
@maridoroshuk I'm assuming I've been added here because of the changes to move the Examples/Browser compatibility sections. However, were these changes intended as they're not mentioned in the description? I'm probably not the best person to comment on the grocery change.

2022-03-10 22:47 UTC, rebloor requested changes

2022-03-10 22:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/browsingdata/remove/index.md
> +## Browser compatibility
This section needs to be moved below the {{WebExtExamples}} who is well here and on the other pages.

2022-03-11 06:20 UTC, maridoroshuk commented
> @maridoroshuk I'm assuming I've been added here because of the changes to move the Examples/Browser compatibility sections. However, were these changes intended as they're not mentioned in the description? I'm probably not the best person to comment on the grocery change.

@rebloor  Yes, sorry! It has to be my oher PR (https://github.com/mdn/content/pull/13651)

2022-03-11 06:30 UTC, rebloor commented
@maridoroshuk thanks, I see your other PR has been merged, could you do a new one to keep the examples together

2022-03-11 06:34 UTC, closed without merging