Resolve #13749
mdn/content pull request #13877
Opened 2022-03-15 04:13 UTC by timeowilliams

#### Summary

Added statement about how the capture process within event lifecycles is optional. 

#### Motivation

To allow readers of the documentation get a better grasp of the three stages and what is/not optional. 

#### Supporting details

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#bubbling_and_capturing_explained
https://github.com/mdn/content/issues/13749

#### Related issues

Fixes #13749 

#### Metadata

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-15 04:32 UTC, teoli2003 commented
@Ondevai, can you review this?

2022-03-18 21:07 UTC, wbamberg requested changes
Thanks for your PR! I think it would be better to have this after https://github.com/mdn/content/blob/056aed1117e3660f334bf3269cf9eb84ca90b7b6/files/en-us/learn/javascript/building_blocks/events/index.md?plain=1#L630-L635 , which talks about bubbling being the default.

I think it could also be more precise, something like:

> In modern browsers, by default, event handlers are *not* registered for the capturing phase. To register an event handler for the capturing phase, instead of the bubbling phase, pass the `useCapture` argument or the `capture` option to [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

2022-03-26 07:04 UTC, timeowilliams reviewed
Addressing requested changes

2022-03-26 17:47 UTC, wbamberg commented
Thanks for the update!

This section:

>  In modern browsers, by default, all event handlers are registered for the bubbling phase. So in our current example, when you select the video, the event bubbles from the <video> element outwards to the <html> element. Along the way:
>
> * It finds the click handler on the video element and runs it, so the video first starts playing.
> * It then finds the click handler on the videoBox element and runs that, so the video is hidden as well.

...is talking about the bubbling phase. By splicing stuff about capturing in, it doesn't make sense any more.

I think the part about enabling capturing should go *after* this, like:

>  In modern browsers, by default, all event handlers are registered for the bubbling phase. So in our current example, when you select the video, the event bubbles from the <video> element outwards to the <html> element. Along the way:
>
> * It finds the click handler on the video element and runs it, so the video first starts playing.
> * It then finds the click handler on the videoBox element and runs that, so the video is hidden as well.
>
> In modern browsers, by default, event handlers are _not_ registered for the capturing phase. To register an event handler for the capturing phase, instead of the bubbling phase, pass the `useCapture` argument or the `capture option` to [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

Also, when your edit says "**Generally*  when event handlers are added to HTML code" - what work is "Generally" doing here? Usually when I see this word I think it means "usually but not always", and in documentation this makes me think, "when isn't it?" and if the documentation doesn't go on to explain that case, then I am left confused.

2022-03-26 17:48 UTC, wbamberg requested changes
Changes requested in https://github.com/mdn/content/pull/13877#issuecomment-1079742220.

2022-07-12 06:52 UTC, sideshowbarker commented
@timeowilliams This seems to be waiting on your response to https://github.com/mdn/content/pull/13877#issuecomment-1079742220

2022-08-26 23:53 UTC, wbamberg commented
Closing in favour of https://github.com/mdn/content/pull/20013.

2022-08-26 23:53 UTC, closed without merging