Add more info on "manual" redirect mode
mdn/content pull request #1391
Opened 2021-01-16 20:46 UTC by jchimene

2021-01-18 12:37 UTC, Rumyra requested changes

2021-01-18 12:37 UTC, Rumyra commented on files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
>          <code>follow</code> (before Chrome 47 it defaulted to <code>manual</code>).</dd>
As per spec unless otherwise stated redirect will be follow https://fetch.spec.whatwg.org/#concept-request-redirect-mode

Also we don't tend to use inline styling:

```suggest
<dt><code>redirect</code></dt>
<dd>How to handle a <code>redirect</code> response:
    <ul>
        <li><code>follow</code>: Automatically follow redirects. Unless otherwise stated the redirect mode is set to <code>follow</code></li>
        <li><code>error</code>: Abort with an error if a redirect occurs.</li>
        <li><code>manual</code>: Caller intends to process the response in another context.<br>See <a class="external" href="https://fetch.spec.whatwg.org/#requests">WHATWG fetch standard</a> for more information.</li>
    </ul>
N.B. Before Chrome 47 redirect mode defaulted to <code>manual</code>.</dd>
```

2021-01-18 12:37 UTC, Rumyra commented on files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
>          <code>follow</code> (before Chrome 47 it defaulted to <code>manual</code>).</dd>
It might be nice to add a note about this in the browser compat data too https://github.com/mdn/browser-compat-data/blob/master/api/WindowOrWorkerGlobalScope.json#L619

2021-01-18 17:47 UTC, jchimene commented on files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
>          <code>follow</code> (before Chrome 47 it defaulted to <code>manual</code>).</dd>
Thanks for the edits

2021-01-18 18:37 UTC, jchimene commented on files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
>          <code>follow</code> (before Chrome 47 it defaulted to <code>manual</code>).</dd>
@Rumyra : Why change `redirect` to `redirect mode` . I base this question on the formal parameter name.

2021-01-18 19:29 UTC, closed without merging

2021-01-18 21:52 UTC, jchimene commented
I've screwed something up. I'm closing this pull request. It's using the wrong branch . I'll finish this in the other PR

@Rumyra Please see this comment about 'redirect` 
https://github.com/mdn/content/pull/1469#discussion_r559796204

We also had an Element discussion about editing the compat table:
https://matrix.to/#/!cGYYDEJwjktUBMSTQT:mozilla.org/$sYGTBw1YnJSGJ6eCHpwFc4Sy_JjRQZrqlw57V6suI6A?via=mozilla.org&via=matrix.org&via=ungleich.ch

In case you can't see the Element thread:
> but if it’s something about browser support for manual redirect mode, my recommendation for resolving it is: 
> Don’t mention any details about browser support for manual redirect mode in MDN
> the less we say about manual redirect mode in MDN, the better

I really apologize for screwing up the PR continuity, esp. for this extended discussion.

2021-01-19 15:04 UTC, Rumyra commented
Haha - I'm going round in circles with the other pr now 😆 all good @jchimene