Edit grammar
mdn/content pull request #13989
Opened 2022-03-17 17:47 UTC by gitwinst

The first change makes it clear immediately that readers should direct their attention to the next example. Previously, if you were reading quickly it was easy to skim over this direction because it was at the end of the sentence, creating a few seconds of confusion.

The second change fixes an awkward construction.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-03-17 18:19 UTC, dipikabh requested changes
Thanks @gitwinst! These changes look good.

I have added suggestions for two more changes.

2022-03-17 18:19 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In the next example we can see how `inline` elements behave. The `<span>` elements in the first paragraph are inline by default and so do not force line breaks.
```suggestion
In the next example, we can see how `inline` elements behave. The `<span>` elements in the first paragraph are inline by default and so do not force line breaks.
```

2022-03-17 18:19 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +**In the example below, we have used various shorthands and longhands to create borders. Play around with the different properties to check that you understand how they work. The MDN pages for the bo
```suggestion
In the example below, we have used various shorthands and longhands to create borders. Play around with the different properties to check that you understand how they work. The MDN pages for the border properties give you information about the different styles of border you can choose from.
```
I believe this paragraph does not need emphasis.

2022-03-17 22:19 UTC, gitwinst commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In the next example we can see how `inline` elements behave. The `<span>` elements in the first paragraph are inline by default and so do not force line breaks.
I like it! I originally thought about adding a comma too but I ignored my own intuition :)

2022-03-18 08:15 UTC, dipikabh commented
Hello @gitwinst, I see my two comments as resolved. I hope you'll commit and push those changes.

2022-03-18 15:50 UTC, gitwinst commented
Hey @dipikabh, thank you for flagging this, I didn't realize that resolving =/= committing! Your edits are now committed :)

2022-03-18 16:13 UTC, dipikabh approved these changes
Thanks @gitwinst!

Congratulations on landing your first contribution here - welcome aboard! 🎉

2022-03-18 16:13 UTC, merged