Fix and modernise touch events example
mdn/content pull request #13993
Opened 2022-03-18 01:52 UTC by hamishwillee

The [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#results) example did not work. This fixes it as suggested by @wbamberg in https://github.com/mdn/content/issues/13590#issuecomment-1064765288

- [ ] fix the argument to EmbedLiveSample and fix the size of the iframe so it's big enough for the example
- [ ] remove the LiveSampleLink macro call and the JSFiddle link
- [ ] update the example to have an "Initialize" button, like the JSFiddle version
- [ ] update the code to be modern JS style
- [ ] add a note about how to enable touch event simulation for desktop browsers

Fixes #13590

@wbamberg The example works. I "think" I got the const/let right :-)

2022-03-18 04:56 UTC, wbamberg requested changes, later dismissed
Thanks for the update Hamish!

This was a bit of a "surface" review, I didn't really dig into the logic of it. But it seems to work fine as far as I could test it, and it is quite a neat example. And it is a lot better than it was!

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
Also, there's a lot of code in here to handle multitouch, but I can't get this to work. Is that a hardware thing?

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
```suggestion
  for (const touch of touches) {
```

(plus all the corresponding changes inside the loop)

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +    let idx = ongoingTouchIndexById(touches[i].identifier);
```suggestion
    const idx = ongoingTouchIndexById(touches[i].identifier);
```

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +    let idx = ongoingTouchIndexById(touches[i].identifier);
You can also replace the `ongoingTouchIndexById` function with the one-liner:

```js
ongoingTouches.findIndex(ongoingTouch => ongoingTouch.identifier === touch.identifier);
```

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
```suggestion
  for (const touch of touches) {
```

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +    let idx = ongoingTouchIndexById(touches[i].identifier);
...and the same comment here as before

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
```suggestion
  for (const touch of touches) {
```

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +    let idx = ongoingTouchIndexById(touches[i].identifier);
Also same comment as beforew.

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  let color = "#" + r + g + b;
```suggestion
  const color = "#" + r + g + b;
```

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +> You can test this on desktop versions of Firefox by enabling "touch simulation" in [Responsive Design Mode](/en-US/docs/Tools/Responsive_Design_Mode#toggling_responsive_design_mode), and then press
I think we should also point to https://developer.chrome.com/docs/devtools/device-mode/, which seems to be Chrome's version, and which I've confirmed works.

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +You can also [try it out on jsFiddle here](https://jsfiddle.net/Darbicus/z3Xdx/10/).
I would remove this link. We don't control the contents of it and I don't think it adds anything.

2022-03-18 04:56 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  let newEvt = document.createEvent("MouseEvents");
```suggestion
  const newEvt = document.createEvent("MouseEvents");
```

2022-03-21 23:50 UTC, hamishwillee commented on files/en-us/web/api/touch_events/index.md
> +  const el = document.getElementById("canvas");
Why? Both seem to work and MDN is completely inconsistent.

2022-03-21 23:57 UTC, wbamberg commented on files/en-us/web/api/touch_events/index.md
> +  const el = document.getElementById("canvas");
Fair enough. I always try to use single quotes, and it's what our guidelines say: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#use_expanded_syntax. But there's not a lot of value in trying to make this happen manually, we need Prettier for this kind of thing.

2022-03-22 00:12 UTC, hamishwillee commented on files/en-us/web/api/touch_events/index.md
> +  const el = document.getElementById("canvas");
Thanks! I've done it anyway, just wanted to confirm reason. If that's what guidelines and prettier does, then great.

2022-03-22 00:21 UTC, hamishwillee commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
@wbamberg I think it is worth keeping the console logging code - it is useful/interesting to watch in desktop. Whereas I don't like the in-page log because it doesn't scroll/expand nicely. I think I'll leave this bit alone - if you feel strongly, then perhaps as a post process.

2022-03-22 00:21 UTC, hamishwillee commented on files/en-us/web/api/touch_events/index.md
> +  for (let i = 0; i < touches.length; i++) {
As above, I'd rather keep the console logging.

2022-03-22 01:07 UTC, hamishwillee commented
@wbamberg OK, I have fixed the bits that I want to :-)

The console logging and in-page logging are inconsistent (as you point out). I would be happy to change all the console logging to go into the in-page log if you like or move everything into the console (and recommend users look at console logging on desktop, which is where most developers are).

There must be a way to make the log fixed length and scroll, so I'd do that.

Happy to take direction on which, but I don't want to strip the logging out.

I am slightly tempted to remove the intialize button too. We added it to make simulation case easier - but you don't "need" it for the example, and it isn't hard to say "just reload the page".

2022-03-22 03:35 UTC, wbamberg commented
> @wbamberg OK, I have fixed the bits that I want to :-)
> 
> The console logging and in-page logging are inconsistent (as you point out). I would be happy to change all the console logging to go into the in-page log if you like or move everything into the console (and recommend users look at console logging on desktop, which is where most developers are).

Yes, it makes sense to put all the logging in either one or the other. It's hard to imagine the current situation where `touchstart` and `touchmove` are in one, and `touchend` is in the other. It makes no sense. The trouble with `touchmove` is it fires so often that the log is swamped, but I don't suppose that really matters.

I think I'm generally pro in-page logging.

> There must be a way to make the log fixed length and scroll, so I'd do that.

You should be able to fix the log layout problem with some CSS like:

```css
#log {
  height: 100px;
  overflow: scroll;
}
```

> I am slightly tempted to remove the intialize button too. We added it to make simulation case easier - but you don't "need" it for the example, and it isn't hard to say "just reload the page".

Yes, I agree with that.

> P.S. I did update the logs to use template literals instead, so at least it isn't quite so old fashioned.

Also if we keep the in-page logging please remove the innerHTML:

```js
function log(msg) {
  const container = document.getElementById('log');
  container.textContent = `${ msg } \n${ container.textContent }`;
}
```

...works just as well, and we do have an open issue about innerHTML: https://github.com/mdn/content/issues/13496.

2022-03-22 06:38 UTC, hamishwillee commented
@wbamberg Re https://github.com/mdn/content/pull/13993#issuecomment-1074690620 - sure! I'm back on Friday and will look at this then. Much appreciated.

2022-03-25 00:30 UTC, hamishwillee commented
@wbamberg All done, as discussed 
- logs kept but moved into the log container (some minor changes made to where logging occurs).
- write to log using textContent rather than innerHTML.
-  Remove initialize button

2022-03-25 00:46 UTC, wbamberg approved these changes
👍 thank you @hamishwillee ! This is so much better in so many ways.

2022-03-25 00:46 UTC, merged