Fix typo null as the bottom of proto chain
mdn/content pull request #14033
Opened 2022-03-18 16:34 UTC by MirzayevOrzu

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-18 16:38 UTC, teoli2003 commented
I think the original text is correct: the parent of `Object` is `null`. Though the use of _top_ for a prototype chain is a bit unfortunate.

2022-03-18 16:54 UTC, MirzayevOrzu commented
Maybe phrase "on top of" can also be removed as it would become "which sits just above null on the prototype chain."

2022-03-18 17:03 UTC, teoli2003 requested changes

2022-03-18 17:03 UTC, teoli2003 commented on files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Nearly all objects in JavaScript are instances of {{jsxref("Object")}} which sits just above `null` on the top of a prototype chain.
I agree that the notion of _top_ is not good, but then we can't speak of below and above.

What about:
```suggestion
Nearly all objects in JavaScript are instances of {{jsxref("Object")}} which has `null` as its prototype.
```

2022-05-03 23:12 UTC, wbamberg commented on files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Nearly all objects in JavaScript are instances of {{jsxref("Object")}} which has `null` as its prototype.
```suggestion
Nearly all objects in JavaScript are instances of {{jsxref("Object")}}, which has `null` as its prototype.
```

2022-05-03 23:13 UTC, wbamberg approved these changes
👍 thanks!

2022-05-04 04:48 UTC, teoli2003 approved these changes

2022-05-04 04:48 UTC, merged

2022-05-04 04:48 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: