Web/JavaScript/Reference/Statements/import: spec link for import calls
mdn/content pull request #14037
Opened 2022-03-18 19:38 UTC by SamB

#### Summary

The page describes import calls ("dynamic imports"), but didn't link to anywhere near the relevant spec section.

Hopefully, this change will fix that 😉.

#### Motivation
When a page describes multiple aspects of a keyword and the spec doesn't have internal cross-references for those, we should link to sections regarding each aspect.

It could be argued that this page should only talk about the statement, however!

  * I'm trying to do a drive-by contribution here, and I can't believe that "it'll only take a moment" to split the page.

  * It might not really be a good idea just because it seems logical.

  * I assume it would need a new browser-compat-data <i>&lt;insert-smart-person-word-here&gt;</i>, with a new *name*. As you know, 
    >There are only two hard things in Computer Science: cache invalidation and naming things.
    > -- Phil Karlton
    So yeah, can't convince myself to try that, either.

So if you want to split the page and/or make a new bcd thingy, you can go ahead and do that; I'm not going to do it for you.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-18 19:41 UTC, SamB commented
Hmm. Looks like the CI spuriously skipped actually rendering the page, so I'm not actually sure if it works or not.

2022-03-18 19:48 UTC, SamB commented
Unfortunately, we end up with a duplicate spec this way. I had figured, based on <https://github.com/mdn/yari/discussions/5347>, that something unexpected would happen when mixing the `browser-compat` and `spec-urls` front matter ... so I adjusted my expectations, and consequently something unexpected did happen :-).

2022-03-18 19:52 UTC, SamB commented on files/en-us/web/javascript/reference/statements/import/index.md
> +  - https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-imports
I guess we need to drop this line to avoid duplicate spec links ☹.
```suggestion
```

2022-03-18 19:59 UTC, SamB commented
Okay, it looks good now, but I was confused for a while because the "deploy-preview" step had apparently cancelled already but the preview was still showing the duplicate link. Then a moment later it suddenly updated ... even in pre-existing preview tab ...

2022-03-18 20:34 UTC, wbamberg requested changes
Thanks for this PR!

Can we not add this spec to the existing BCD key? The BCD `spec_urls` key is allowed to be an array. I'd much rather do this than split the spec URLs across BCD and front matter.

If you don't want to do this, please let me know and I will.

2022-05-10 09:03 UTC, sideshowbarker commented
@SamB This PR seems to be waiting for your response to @wbamberg’s comment at https://github.com/mdn/content/pull/14037#pullrequestreview-914842770

2022-05-13 19:26 UTC, closed without merging

2022-05-13 19:52 UTC, wbamberg commented
Thanks you @sideshowbarker !

2022-05-14 18:08 UTC, Deeznuts190 commented
Gary Holeman Sr



On Tue, May 10, 2022, 4:03 AM Michael[tm] Smith ***@***.***>
wrote:

> @SamB <https://github.com/SamB> This PR seems to be waiting for your
> response to @wbamberg <https://github.com/wbamberg>’s comment at #14037
> (review)
> <https://github.com/mdn/content/pull/14037#pullrequestreview-914842770>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/content/pull/14037#issuecomment-1122125130>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYUC5ZNWYPIKGJNEZHR2HXDVJIQ7VANCNFSM5RCXTIRA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>