Update FocusEvent pages
mdn/content pull request #14127
Opened 2022-03-21 11:59 UTC by danburzo

#### Summary

I've made the following updates: 

* Note that focusin/focusout follow their non-bubbling counterparts;
* Note that focusin/focusout don't (yet) have an event handling property;
* Add the description of the FocusEvent.relatedTarget property on all events;
* Link to HTMLElement.focus() / .blur() methods from the similarly-named event pages.
* Adds a section to FocusEvent that describes the difference in the order of events between the spec and current browser implementations, and points to it from the focusin/focusout pages.

Fixes #14084. 

#### Motivation

I propose these changes to make the FocusEvent pages more useful to readers so that it matches what they will experience in browsers.

#### Supporting details

* [UIEvents spec]()
* 

#### Related issues

Fixes #14084. 

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-03-21 14:29 UTC, jpmedley requested changes

2022-03-21 15:04 UTC, danburzo commented on files/en-us/web/api/element/blur_event/index.md
> +      <td>The element receiving focus, if any.</td>
Yes, when the focus moves outside the web page — for example, if you were to open the DevTools and focus the Console prompt — the `focusout` event would have `relatedTarget: null`. Ditto when you click on an element on the page that's not focusable.  The [page for `relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget) documents these scenarios.

2022-03-21 15:06 UTC, danburzo commented on files/en-us/web/api/element/focus_event/index.md
> +      <td>The element losing focus, if any.</td>
Similarly to the scenarios described above, when the page first gets a focused element, or you return the focus from outside the page, `relatedTarget` will be null.

2022-03-21 15:07 UTC, danburzo commented on files/en-us/web/api/element/focusin_event/index.md
> +      <td>The element losing focus, if any.</td>
Same answer as for the `focus` event.

2022-03-21 15:07 UTC, danburzo commented on files/en-us/web/api/element/focusout_event/index.md
> +      <td>The element receiving focus, if any.</td>
Same answer as for the `blur` event.

2022-03-22 13:50 UTC, jpmedley requested changes

2022-03-22 13:50 UTC, jpmedley commented on files/en-us/web/api/element/blur_event/index.md
> +      <td>The element receiving focus, if any.</td>
```suggestion
      <td>The element receiving focus, if any. (Follow the link for details.)</td>
```

2022-03-22 18:26 UTC, danburzo commented on files/en-us/web/api/element/blur_event/index.md
> +      <td>The element receiving focus, if any.</td>
How about:

... | ...
--- | ---
Secondary target | [`relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget) points to the element receiving focus, if any.

Or, more explicitly:

... | ...
--- | ---
Secondary target | The element receiving focus, if any. (See [`Focus.relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget) for details.)

(I'm trying to bring the link closer to the instructions to follow it.)

2022-03-23 15:10 UTC, danburzo commented on files/en-us/web/api/element/blur_event/index.md
> +      <td>The element receiving focus, if any.</td>
I went for the latter.

2022-09-02 10:49 UTC, Rumyra commented
@danburzo from what I can see the changes suggested have been made - can you confirm?

If you resolve conflicts we should be able to get this pr through 👍

2022-09-13 20:30 UTC, danburzo commented
@Rumyra I've adapted my proposed changes to the new structure for FocusEvent pages. 

Substantial new things:

- The description for `FocusEvent.relatedTarget` is now specific to each event, but does not repeat the cases where `relatedTarget` might be null, which can be consulted on the property's page.
- I've removed mentions of the `onfocusin` / `onfocusout` event handling properties, which are not currently specced (see [whatwg/html#4542](https://github.com/whatwg/html/issues/4542))

2022-09-28 00:15 UTC, estelle commented
@jpmedley Is this ok to merge?

2022-09-29 13:06 UTC, jpmedley approved these changes

2022-09-29 13:06 UTC, merged