HTTP Header: Clear-Site-Data - update link to latest spec
mdn/content pull request #1417
Opened 2021-01-18 06:07 UTC by hamishwillee

2021-01-18 09:31 UTC, Elchi3 requested changes

2021-01-18 09:31 UTC, Elchi3 commented on files/en-us/web/http/headers/clear-site-data/index.html
> +   <td><a href="https://www.w3.org/TR/clear-site-data/">Clear Site Data</a></td>
I think we try to avoid to link to TR specs. They become outdated often.
The TR version would be the "Latest published version" and the github.io version is the "Latest Editor’s Draft" which is often more desirable.

2021-01-18 09:31 UTC, Elchi3 commented on files/en-us/web/http/headers/clear-site-data/index.html
> +   <td>W3C Working Draft, 30 November 2017</td>
This will not age well as the spec gets updated. 
I try to remove this and the status column altogether going forward (the all docs under JavaScript/ which have this already, e.g. [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toLocaleString#specifications)).

2021-01-19 01:29 UTC, hamishwillee commented on files/en-us/web/http/headers/clear-site-data/index.html
> +  <thead>
@Elchi3 I've modified to use the single column spec format (as per your comment https://github.com/mdn/content/pull/1417/files#r559426104) however I'm not sure how I can avoid linking to the TR spec as per https://github.com/mdn/content/pull/1417/files#r559424680. 

Also, the spec be added to https://github.com/mdn/yari/blob/master/kumascript/macros/SpecData.json ?

2021-01-19 11:27 UTC, Elchi3 requested changes

2021-01-19 11:27 UTC, Elchi3 commented on files/en-us/web/http/headers/clear-site-data/index.html
> +      <td><a href="https://www.w3.org/TR/clear-site-data/">Clear Site Data</a> (Latest published version)</td>
```suggestion
      <td><a href="https://w3c.github.io/webappsec-clear-site-data">Clear Site Data</a> (Latest Editor's Draft)</td>
```

2021-01-19 11:27 UTC, Elchi3 commented on files/en-us/web/http/headers/clear-site-data/index.html
> +  <thead>
Thanks, looks better.

I wouldn't add it to specdata. We're trying to move away from it. See https://github.com/mdn/content/issues/1146

2021-01-19 21:40 UTC, hamishwillee commented
Thanks @Elchi3 - I've committed your suggestion. Thanks for pointing me to #1146 - including spec info in the BCD looks great; though of course there are a whole bunch of things that aren't and never will be in BCD that are still relevant to docs (and in particular this is true of HTTP headers where the definition of "supported" is unclear).

2021-01-20 10:11 UTC, Elchi3 approved these changes
Thanks @hamishwillee!
(Great feedback on the spec proposal too!)

2021-01-20 10:11 UTC, merged