Add a page for HTMLMediaElement.preservesPitch
mdn/content pull request #14183
Opened 2022-03-22 18:05 UTC by wbamberg

This comes out of https://github.com/mdn/content/issues/3783#issuecomment-1074513476.

We should also add `spec_url` to the BCD.

2022-03-22 18:19 UTC, wbamberg commented
BCD update -> https://github.com/mdn/browser-compat-data/pull/15474

2022-03-23 06:26 UTC, teoli2003 requested changes

2022-03-23 06:26 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/index.md
> +  - : Is a {{jsxref('Boolean')}} that determines if the pitch of the sound will be preserved. If set to `false`, the pitch will adjust to the speed of the audio..
It doesn't return the wrapper object but a boolean value (We have plenty of these errors with DOMString and Boolean all over the place, we fix them little by little for the moment)

```suggestion
  - : Is a boolean value that determines if the pitch of the sound will be preserved. If set to `false`, the pitch will adjust to the speed of the audio.
```

2022-03-23 06:26 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/preservespitch/index.md
> +```
We don't have a _Syntax_ section any more for properties. (See the [template](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_property_subpage_template))

```suggestion
```

2022-03-23 06:26 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/preservespitch/index.md
> +### Value
```suggestion
## Value
```

2022-03-23 06:58 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/preservespitch/index.md
> +
```suggestion
```

I'm removing an extraneous empty line.

2022-03-23 06:59 UTC, teoli2003 approved these changes
👍

2022-03-23 07:01 UTC, merged