Added documentation for the priority hints interface
mdn/content pull request #14213
Opened 2022-03-23 13:33 UTC by pmeenan

#### Summary
Added documentation for the [priority hints](https://wicg.github.io/priority-hints/) attributes and properties. This touches the `iframe`, `image`, `script` and `link` elements (HTML and DOM API) as well as the `Request` object for the `fetch` API.

For the HTML elements, it adds a `fetchpriority` attribute for hinting at the importance of a given element fetch. For the fetch API, it exposes a `priority` property on the Request object (for the same purpose).

#### Motivation
[Priority hints](https://wicg.github.io/priority-hints/) was recently spec'd and is shipping [enabled by default in Chrome 101](https://chromestatus.com/feature/5273474901737472) (after running several origin trials over the last few years).

#### Supporting details
Spec: https://wicg.github.io/priority-hints/
Chrome status: https://chromestatus.com/feature/5273474901737472

#### Related issues
Part of the contributions for #14208

#### Metadata
- [x] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-26 18:44 UTC, ericwbailey commented
A little above my paygrade. Mind taking a look, @sideshowbarker?

2022-03-27 00:44 UTC, sideshowbarker commented
> Mind taking a look, @sideshowbarker?

Yup, will do

2022-03-28 17:18 UTC, jpmedley requested changes

2022-03-28 19:22 UTC, pmeenan commented
@jpmedley thanks for the detailed feedback.  Should all be addressed now.  It looks like the API docs template also doesn't have a "usage notes" section so I rolled the notes into the "values" section (along with adding the bit about it being browser-specific).

2022-03-29 13:36 UTC, jpmedley approved these changes

2022-03-29 13:36 UTC, merged