Rewrites Site definition
mdn/content pull request #14356
Opened 2022-03-27 00:11 UTC by NiedziolkaMichal

#### Summary

I have added a lot more informations about how "site" is determined and also wrote that scheme may or may not be part of the site.

#### Motivation

#### Supporting details

[web.dev same-site page](https://web.dev/same-site-same-origin/#site)

#### Related issues

#13612 

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-29 22:10 UTC, wbamberg requested changes, later dismissed
Thanks for your PR! I agree that this is a good change to make but I think in some ways this entry is going to be hard for people to understand. It might be helpful to:
- start with an informal definition of "site"
- explain why we need a more formal one
- explain what the more formal one is.

Something like:

******

Informally, a site is a website, which is a collection of web pages, served from the same domain, and maintained by a single organization.

Browsers sometimes need to distinguish precisely between different sites. For example, the browser must only send [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) cookies to the same site that set them.

For this more precise definition a site is determined by the _registrable domain_ portion of the domain name. The registrable domain consists of an entry in the [Public Suffix List](https://publicsuffix.org/list/) plus the portion of the domain name just before it. This means that, for example, "theguardian.co.uk", "sussex.ac.uk", and "bookshop.org" are all registrable domains.

According to this definition, "support.mozilla.org" and "developer.mozilla.org" are part of the same site, because "mozilla.org" is a registrable domain.

In some contexts the scheme is also considered when differentiating sites. This would make "http://vpl.ca" and "https://vpl.ca" different sites. Including the scheme is useful in particular because it prevents an insecure (http) site= from being treated as the same site as a secure (https) site. This is sometimes called a "schemeful same-site". This stricter definition is applied in the rules for handling [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) cookies.

*****

...or something with this rough organization anyway.

2022-03-29 22:10 UTC, wbamberg commented on files/en-us/glossary/site/index.md
> +The _site_ is part of a domain name, that identifies a single entity, by considering only public suffix and part of the domain just before it. Typically a public suffix consists only of {{Glossary("T
I think it's going to be confusing to many people to start of by saying "The _site_ is part of a domain name". It might be mire accurate to say that the site is _determined by_ part of the domain name.

2022-03-29 22:10 UTC, wbamberg commented on files/en-us/glossary/site/index.md
> +Depending on the document, a used scheme may also be part of a _site_. According to this definition, `https://mozilla.org` and `http://mozilla.org` are `cross-site` just because protocol differs. To
Is it depending on the document? I would have thought it depended on the application (i.e. the purpose for which the browser is deciding whether 2 URLs are same-site).

2022-03-29 22:20 UTC, NiedziolkaMichal commented on files/en-us/glossary/site/index.md
> +Depending on the document, a used scheme may also be part of a _site_. According to this definition, `https://mozilla.org` and `http://mozilla.org` are `cross-site` just because protocol differs. To
By document I ment WHATWG standard. Application is surely a better word to describe it.

2022-03-29 22:22 UTC, NiedziolkaMichal commented
Thank you for feedback, your definition is much better. Could you make a commit, replacing my changes with yours?

2022-03-29 23:56 UTC, wbamberg commented
> Thank you for feedback, your definition is much better. Could you make a commit, replacing my changes with yours?

Thank you @NiedziolkaMichal ! Could you please check that I haven't mangled what you wanted to express here?

2022-03-30 11:07 UTC, NiedziolkaMichal commented
I have, it's perfect.

2022-03-30 16:30 UTC, ddbeck requested changes
I'm proposing a few minor fixes, mostly to use just one way to format phrases and domains and URLs. Otherwise, I like how this looks! 👍

2022-03-30 16:30 UTC, ddbeck commented on files/en-us/glossary/site/index.md
> +For this more precise definition a site is determined by the _registrable domain_ portion of the domain name. The registrable domain consists of an entry in the [Public Suffix List](https://publicsuf
```suggestion
For this more precise definition a site is determined by the _registrable domain_ portion of the domain name. The registrable domain consists of an entry in the [Public Suffix List](https://publicsuffix.org/list/) plus the portion of the domain name just before it. This means that, for example, `theguardian.co.uk`, `sussex.ac.uk`, and `bookshop.org` are all registrable domains.
```

2022-03-30 16:30 UTC, ddbeck commented on files/en-us/glossary/site/index.md
> +According to this definition, "support.mozilla.org" and "developer.mozilla.org" are part of the same site, because "mozilla.org" is a registrable domain.
```suggestion
According to this definition, `support.mozilla.org` and `developer.mozilla.org` are part of the same site, because `mozilla.org` is a registrable domain.
```

2022-03-30 16:30 UTC, ddbeck commented on files/en-us/glossary/site/index.md
> +In some contexts the scheme is also considered when differentiating sites. This would make "http://vpl.ca" and "https://vpl.ca" different sites. Including the scheme prevents an insecure (http) site
```suggestion
In some contexts, the scheme is also considered when differentiating sites. This would make `http://vpl.ca` and `https://vpl.ca` different sites. Including the scheme prevents an insecure (HTTP) site from being treated as the same site as a secure (HTTPS) site. A definition that considers the scheme is sometimes called a _schemeful same-site_. This stricter definition is applied in the rules for handling [SameSite](/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) cookies.
```

2022-03-30 16:30 UTC, ddbeck commented on files/en-us/glossary/site/index.md
> +These are the same site because the registrable domain of _mozilla.org_ is the same:
```suggestion
These are the same site because the registrable domain of `mozilla.org` is the same:
```

2022-03-30 16:43 UTC, wbamberg commented
I never know how to format things like this. But happy with your suggestions :).

2022-03-30 18:22 UTC, ddbeck approved these changes
Thank you @NiedziolkaMichal and @wbamberg—this is a really nice update. Plus I now have an actual clue about how a same site works.

2022-03-30 18:23 UTC, merged

2022-03-31 23:27 UTC, hamishwillee commented
Yes, this is a really excellent update.