Added explanation of indexOf method in "Useful string methods" page
mdn/content pull request #14350
Opened 2022-03-26 21:33 UTC by deepug9787

#### Summary

#### Motivation

#### Supporting details

#### Related issues

Fixes #14266 

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-03-28 22:00 UTC, wbamberg requested changes
Thanks for your PR, @deepug9787 ! Looks good but a few little things to take care of.

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +You can search for and find the position of a substring inside a larger string using the {{jsxref("String.prototype.indexOf()", "indexOf()")}} method. This method takes two {{glossary("parameters")}}
```suggestion
You can find the position of a substring inside a larger string using the {{jsxref("String.prototype.indexOf()", "indexOf()")}} method. This method takes two {{glossary("parameter", "parameters")}} – the substring that you want to search for, and an optional parameter that specifies the starting point of the search.
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +If the string contains the substring, it returns the index of the first occurrence of the substring, and `-1` otherwise.
```suggestion
If the string contains the substring, `indexOf()` returns the index of the first occurrence of the substring. If the string does not contain the substring,  `indexOf()` returns `-1`.
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +let tagline = "MDN - Resources for developers, by developers";
```suggestion
const tagline = 'MDN - Resources for developers, by developers';
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +console.log(tagline.indexOf("developers")); // 20
```suggestion
console.log(tagline.indexOf('developers')); // 20
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +console.log(tagline.indexOf("x")); // -1
```suggestion
console.log(tagline.indexOf('x')); // -1
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +So now that you know how to find the first occurrence of a substring, how do you go about finding the subsequent occurrences? You can do that by passing in a value that's greater than the index of th
```suggestion
So now that you know how to find the first occurrence of a substring, how do you go about finding subsequent occurrences? You can do that by passing in a value that's greater than the index of the previous occurrence as the second parameter to the method.
```

2022-03-28 22:00 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +console.log(secondOccurence); // 35
```suggestion
const firstOccurrence = tagline.indexOf('developers');
const secondOccurrence = tagline.indexOf('developers', firstOccurrence + 1);

console.log(firstOccurrence); // 20
console.log(secondOccurrence); // 35
```

2022-03-29 04:58 UTC, deepug9787 commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +If the string contains the substring, it returns the index of the first occurrence of the substring, and `-1` otherwise.
@wbamberg Thanks for the feedback.

I'm not sure whether the suggested change is consistent with the rest of the content on the page. For instance, there is a line under the ["Testing if a string contains a substring"](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods#testing_if_a_string_contains_a_substring) section that says:

"It returns true if the string contains the substring, and false otherwise."

2022-03-30 23:24 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +If the string contains the substring, it returns the index of the first occurrence of the substring, and `-1` otherwise.
As a rule I think "It" is a bad word in technical documentation because you always have to think about what it refers to. It's worse the further it is from the original thing, but for clarity IMO it's usually clearer to repeat the name of the thing that to use "it", even when it seems a bit clumsy to do so. In the case you linked of `includes()` I would also prefer to use the name of the method, like:

"The `includes()` method returns true if the string contains the substring, and false otherwise."

As for splitting the sentence into two: the sentence here is longer and has a more complex structure than the one for `includes()`. In particular there's significant distance between "otherwise" and the thing it is referring to "If the string contains the substring" that (IMO) it is clearer to have two sentences.

2022-03-31 12:11 UTC, deepug9787 commented on files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
> +If the string contains the substring, it returns the index of the first occurrence of the substring, and `-1` otherwise.
Thanks for clearing that up, @wbamberg

2022-03-31 16:50 UTC, wbamberg approved these changes
👍 thanks for your contribution, @deepug9787 , this looks great!

2022-03-31 16:50 UTC, merged