Fix grammar issue
mdn/content pull request #14364
Opened 2022-03-27 04:24 UTC by Script47

#### Summary

Fix grammar issue within the `console.log` statement.

#### Motivation

Grammar is important.

#### Supporting details

N/A

#### Related issues

N/A

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-03-27 05:42 UTC, teoli2003 requested changes

2022-03-27 05:42 UTC, teoli2003 commented on files/en-us/web/api/geolocation/clearwatch/index.md
> +    console.log('Congratulation, you reached the target');
I think the plural is also better here:
```suggestion
    console.log('Congratulations, you reached the target');
```

2022-03-27 09:51 UTC, OnkarRuikar commented on files/en-us/web/api/geolocation/clearwatch/index.md
> +    console.log('Congratulation, you reached the target');
No fixed time in the past has been specified. I think present perfect suits well here.
```suggestion
    console.log('Congratulations, you've reached the target!');
```

2022-03-27 11:06 UTC, teoli2003 commented on files/en-us/web/api/geolocation/clearwatch/index.md
> +    console.log('Congratulation, you reached the target');
Oh yes, you are right OnkaRuikar!

2022-03-30 01:46 UTC, jpmedley approved these changes

2022-03-30 06:19 UTC, teoli2003 approved these changes

2022-03-30 06:19 UTC, merged