KeyframeEffect: added more code for better understanding of the context
mdn/content pull request #14404
Opened 2022-03-28 14:27 UTC by OnkarRuikar

https://developer.mozilla.org/en-US/docs/Web/API/KeyframeEffect#examples

## Summary
Added more code to the example for better understanding of the context in which the interface is used.

As per the BCD table the interface is not experimental anymore.

#### Motivation
Just creating an object was not giving enough understanding of it's use in the Example section.

#### Metadata

- [x] Fixes a typo, bug, or other error

2022-03-28 21:19 UTC, wbamberg requested changes
Thank you @OnkarRuikar ! It would be great (IMO) to make these into live samples, but this is already much better. I had a few little comments.

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/index.md
> +  rabbitDownAnimation.play();
The code in this example is indented.

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/index.md
> + let rabbitDownKeyframes = new KeyframeEffect(
```suggestion
const rabbitDownKeyframes = new KeyframeEffect(
```

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/index.md
> + let whiteRabbit = document.getElementById("rabbit");
```suggestion
const whiteRabbit = document.getElementById('rabbit');
```

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/index.md
> +  let rabbitDownAnimation = new Animation(rabbitDownKeyframes, document.timeline);
```suggestion
const rabbitDownAnimation = new Animation(rabbitDownKeyframes, document.timeline);
```

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/keyframeeffect/index.md
> +let whiteRabbit = document.getElementById("rabbit");
```suggestion
const whiteRabbit = document.getElementById('rabbit');
```

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/keyframeeffect/index.md
> +let rabbitDownKeyframes = new KeyframeEffect(
```suggestion
const rabbitDownKeyframes = new KeyframeEffect(
```

2022-03-28 21:19 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/keyframeeffect/index.md
> +let rabbitDownAnimation = new Animation(rabbitDownKeyframes, document.timeline);
```suggestion
const rabbitDownAnimation = new Animation(rabbitDownKeyframes, document.timeline);
```

2022-03-29 02:15 UTC, OnkarRuikar commented
@wbamberg  tanks for the suggestions! I've committed the changes.

2022-03-29 02:20 UTC, wbamberg commented on files/en-us/web/api/keyframeeffect/index.md
> +  rabbitDownAnimation.play();
```suggestion
// Play rabbit animation
rabbitDownAnimation.play();
```

2022-03-29 02:20 UTC, wbamberg approved these changes
👍 thank you @OnkarRuikar !

2022-03-29 04:41 UTC, merged