FF100 Remove HTTP Large-Allocation Header
mdn/content pull request #14423
Opened 2022-03-29 04:09 UTC by hamishwillee

This is part of FF100 docs for removal of the [Large-Allocation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Large-Allocation) HTTP header in https://bugzilla.mozilla.org/show_bug.cgi?id=1598759

It includes the release note and updates to add deprecation tagging etc.

Other docs work can be tracked in #14407

2022-03-29 10:20 UTC, Rumyra requested changes

2022-03-29 10:20 UTC, Rumyra commented on files/en-us/web/http/headers/large-allocation/index.md
> +It not implemented in current versions of any browser, but is harmless to send to any browser.
```suggestion
It's not implemented in current versions of any browser, but is harmless to send to any browser.
```

2022-03-29 10:20 UTC, Rumyra commented on files/en-us/web/http/headers/large-allocation/index.md
> +    be disabled with the "dom.largeAllocation.forceEnable" boolean preference in about:config.
```suggestion
    be disabled with the `dom.largeAllocation.forceEnable` boolean preference in about:config.
```

2022-03-29 10:20 UTC, Rumyra commented
Just a couple of nits

2022-03-30 10:42 UTC, Rumyra approved these changes

2022-03-30 10:43 UTC, merged

2022-03-30 10:43 UTC, Rumyra commented
Brill - thanks @hamishwillee

2022-03-31 23:58 UTC, hamishwillee commented
Awesome - thanks for the nit fixes.