Replace Deprecated_Header in navigator.platform doc and adjust navigator.userAgentData.platform note wording
mdn/content pull request #14452
Opened 2022-03-30 02:16 UTC by sideshowbarker

Related to https://github.com/mdn/content/issues/14429, this PR includes two commits:

- 4db8611c2e Adjust wording of note about navigator.userAgentData.platform
- f73b2d9534 Replace Deprecated_Header in navigator.platform doc

Given that `navigator.userAgentData.platform` is currently only supported in Blink, we should not be strongly “recommending” it; so 4db8611c2e drops the “recommended” and instead just points out that `navigator.userAgentData.platform` exists as an alternative — while changing the _“not yet supported by some major browsers”_ wording to instead more accurately state it’s _“not yet supported by **most** browsers”_.

And given that `navigator.platform` is not formally deprecated by the spec, f73b2d9534 replaces the `Deprecated_Header` macro and its boilerplate text with some more-appropriate alternative pseudo-boilerplate text that’s intentionally broadly worded in such as way as to not be specific to just the `navigator.platform` case but instead worded for the general case where we want to warn web developers to avoid using a particular feature.

cc @hsivonen

2022-03-30 02:33 UTC, wbamberg approved these changes
Since [I complained about this already](https://github.com/mdn/content/pull/12017#issuecomment-1013617301), I'm happy to see this! Approving but leaving open in case @hsivonen has a comment.

2022-03-30 02:33 UTC, wbamberg commented on files/en-us/web/api/navigator/platform/index.md
> +> **Warning:** Use of this feature is discouraged. It may have known problems, or it may be a feature that works as expected now, but for which in the future behavior may change in a way that will br
```suggestion
> **Warning:** Use of this feature is discouraged. It may have known problems, or it may be a feature that works as expected now, but which in the future may change in a way that will break code that relies on it continuing to work in the same way it does now. Or it may be a feature which a specification has marked as deprecated or obsolete. Avoid using it, and update existing code if possible; see the [compatibility table](#browser_compatibility) to guide your decision.
```

2022-03-30 06:51 UTC, hsivonen commented
Thanks. I suggest dropping both instances of the word "yet".

2022-03-30 07:55 UTC, sideshowbarker commented on files/en-us/web/api/navigator/platform/index.md
> +> **Note:** An alternative to this property is {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}}. However, {{domxref("NavigatorUAData.platform", "navigator.userAgentData.pla
```suggestion
> **Note:** An alternative to this property is {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}}. However, {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}} is not supported by most browsers, and the specification which defines it has not been adopted by any standards group (specifically, it is not part of any specification published by the W3C or WHATWG).
```

2022-03-30 07:57 UTC, sideshowbarker commented
> Thanks. I suggest dropping both instances of the word "yet".

👍 Made it so in 57fdcf0

2022-03-30 07:59 UTC, sideshowbarker commented
Marking this as Draft so that we make sure not to merged it until we also get resolution on some of the details discussed in https://github.com/mdn/content/issues/14429#issuecomment-1082715527

2022-03-30 08:17 UTC, hsivonen commented
On further thought, instead of just suggesting the code be updated while also mentioning a Blink-specific API for also doing the discouraged thing it would make sense to mention that in general, Web developers should feature-detect relevant things when applicable and not care about the platform as a general rule.

2022-03-31 08:16 UTC, sideshowbarker commented
OK, in light of the spec change at https://github.com/whatwg/html/pull/7762, I’ve gone ahead and completely re-worked this patch to instead do the following:

- Drop the `Deprecated_Header` macro.
- Add admonishments that `navigator.platform` should be avoided in favor of feature detection.
- Relegate mention of (equally-bad) `navigator.userAgentData.platform` to just being a **See also**.
- Add an example of the single known good case where using `navigator.platform` isn’t completely bad.

Related BCD change: https://github.com/mdn/browser-compat-data/pull/15599

> On further thought, instead of just suggesting the code be updated while also mentioning a Blink-specific API for also doing the discouraged thing it would make sense to mention that in general, Web developers should feature-detect relevant things when applicable and not care about the platform as a general rule.

In the updated patch, I added some language which tries to give that advice.

So @hsivonen and @wbamberg, you could both review the updated patch, I’d appreciate it.

2022-03-31 08:22 UTC, hsivonen commented on files/en-us/web/api/navigator/platform/index.md
> +That is, check `navigator.platform` for a match on the substring `"Mac"`, or an exact match for the string `"iPhone"`, and then based on whether or not there’s a match, choose the modifier key that y
Minor nit: s/for a match on the substring `"Mac"`/for starting with `"Mac"`/

2022-03-31 08:29 UTC, sideshowbarker commented on files/en-us/web/api/navigator/platform/index.md
> +That is, check `navigator.platform` for a match on the substring `"Mac"`, or an exact match for the string `"iPhone"`, and then based on whether or not there’s a match, choose the modifier key that y
Thanks — pushed an update with that fix.

2022-03-31 08:52 UTC, teoli2003 commented
@sideshowbarker @hsivonen Feel free to ask for my review when this is ready to land. That way I know you are done and we can abide by our rule that this is not landed by the author of the PR.

2022-03-31 08:58 UTC, sideshowbarker commented
> @sideshowbarker @hsivonen Feel free to ask for my review when this is ready to land. That way I know you are done and we can abide by our rule that this is not landed by the author of the PR.

Thanks — will do

2022-03-31 11:50 UTC, hsivonen reviewed
Thanks. I can't actually pick the "Approve" option, because I'm not an official reviewer for this repo.

2022-03-31 11:50 UTC, hsivonen commented on files/en-us/web/api/navigator/platform/index.md
> +A string identifying the platform on which the user’s browser is running; for example: "`MacIntel`", "`Win32`", "`Linux x86_64`", "`Linux x86_64`".
Looks like this preserves the backticks inside quotes pattern from the old text, but it should probably be the other way round. r+ either way, since, as noted, it was already this way here.

2022-03-31 12:15 UTC, sideshowbarker commented on files/en-us/web/api/navigator/platform/index.md
> +A string identifying the platform on which the user’s browser is running; for example: "`MacIntel`", "`Win32`", "`Linux x86_64`", "`Linux x86_64`".
Thanks — I’ve made that fix.

And thanks much for the review and for having taken the time to raise the issue here, and put together the spec patch. I think the result is that this MDN article has ended up being much better than it would have been otherwise — much more more what it really should be for developers.

2022-03-31 12:17 UTC, sideshowbarker commented
@teoli2003 Having gotten @hsivonen’s r+ on this, I think it’s ready to merge. I still hope @wbamberg can take a look at it post-merge and if there’s anything he notices that we missed, I’ll be happy to do a follow-up PR

2022-03-31 12:36 UTC, teoli2003 requested changes
Just a tiny change on the first line to make it coherent with the whole of MDN.

2022-03-31 12:36 UTC, teoli2003 commented on files/en-us/web/api/navigator/platform/index.md
> +Returns a string identifying the platform on which the user’s browser is running.
```suggestion
The **`platform`** property read-only property of the {{domxref("Navigator")}} interface returns a string identifying the platform on which the user’s browser is running.
```

2022-03-31 13:17 UTC, teoli2003 approved these changes
I'm merging. We can do more changes in follow-up PRs if needed.

Thanks, @hsivonen, @sideshowbarker and @wbamberg to have this sorted out! 🎉

2022-03-31 13:17 UTC, merged

2022-03-31 22:25 UTC, hamishwillee commented on files/en-us/web/api/navigator/platform/index.md
> -> **Note:** The recommended alternative to this property is {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}}. However, {{domxref("NavigatorUAData.platform", "navigator.user
@sideshowbarker @teoli2003 Does it make sense to remove the info/links to  `NavigatorUAData.platform`?

I understand the desire to point to feature detection, and the reasoning why `navigator.platform` shouldn't be deprecated. 

But despite the spec change to `navigator.platform` my take is that you would be much better off using `NavigatorUAData.platform`. The user hints are more fully designed and specified - and while they aren't on all platforms, neither is the value of `navigator.platform` reliable on any platform.

2022-03-31 23:37 UTC, sideshowbarker commented on files/en-us/web/api/navigator/platform/index.md
> -> **Note:** The recommended alternative to this property is {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}}. However, {{domxref("NavigatorUAData.platform", "navigator.user
> @sideshowbarker @teoli2003 Does it make sense to remove the info/links to `NavigatorUAData.platform`?

I think it doesn’t make sense to remove it completely — which is why I moved it to being a See Also — but I think given the current state of things, it doesn’t make sense to give it as much prominence as it had.

I think giving it that amount of prominence made sense when we had `navigator.platform` marked as Deprecated — because in that case, we actually had people asking, OK, if this is deprecated, then what’s the alternative?

But as the fact that https://github.com/mdn/content/issues/14429 was raised kind of shows, we create a different problem when when we give this particular alternative the kind of prominence we were giving it — especially if we say it’s recommended.

> But despite the spec change to `navigator.platform` my take is that you would be much better off using `NavigatorUAData.platform`. The user hints are more fully designed and specified

One thing we need to recognize is the people who work on on-Blink/Chrome browsers projects are not super happy if MDN promotes the use of some feature to developers when the current reality of that feature is that in practice it’s a Blink-only feature — even when that feature has a well-intentioned actively-maintained spec.

But it doesn’t matter how good the spec is if other browser projects aren’t implementing and it and aren’t even showing interest. And in the specific case of Client Hints, there was even at one time some discussion about having https://mozilla.github.io/standards-positions/ list is a Harmful.

It’s now marked “non-harmful” there but anyway we need to recognize that the Mozilla engineering team does not seem to be any interest in ever implementing Client Hints.

And while the Safari/WebKit team also doesn’t seem opposed to ever implementing Client Hints (see https://lists.webkit.org/pipermail/webkit-dev/2020-May/thread.html#31195), working on actually implementing doesn’t seem to be any significant priority for them — to the point that they haven’t even bothered to list it at https://webkit.org/status/.

> my take is that you would be much better off using `NavigatorUAData.platform`

After looking through a lot of `navigator.platform` usages in Stack Overflow questions and answers in GitHub code, I can say that in nearly all cases where people are using `navigator.platform` in code, they are not using it for good reasons — and the kinds of things they are doing are things that want to discourage developers from doing.

The same goes for in ways in which somebody might use `NavigatorUAData.platform` — the underlying problem with both properties is that it’s fundamentally a bad idea to try to be finding out information about the user’s environment rather than only relying on feature detection.

I am aware of only one single case in which it makes sense to try and get information about the user’s platform — and that’s the deciding-on-which-modifier-key-to-advise-to-the-user case which I added an example for in the patch here.

Other than that one case, I’m not aware of even a single other best-practice case of something to do in code based on finding out information about the user’s platform — whether by using `navigator.platform` or with Client Hints.

> and while they aren't on all platforms, neither is the value of `navigator.platform` reliable on any platform.

The key big differences are that `navigator.platform` is actually implemented in every browser engine (even if its reliability may vary), and `navigator.platform` is part of a standard that’s gone through the process of getting agreement and endorsements among multiple browser projects.

2022-03-31 23:56 UTC, hamishwillee commented on files/en-us/web/api/navigator/platform/index.md
> -> **Note:** The recommended alternative to this property is {{domxref("NavigatorUAData.platform", "navigator.userAgentData.platform")}}. However, {{domxref("NavigatorUAData.platform", "navigator.user
Thanks for the detailed explanation. I can get on board with it being a "see also".

2022-04-01 06:14 UTC, hsivonen commented
Thanks!