Minor typo fix
mdn/content pull request #14499
Opened 2022-03-31 07:12 UTC by KRicky13

#### Summary
Fixes a minor doc typo under `Parameters`

#### Motivation
First PR and to improve readability of doc

#### Supporting details
N/A

#### Related issues
N/A

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-03-31 07:19 UTC, teoli2003 requested changes
Good catch. A small addition and we can land this.

2022-03-31 07:19 UTC, teoli2003 commented on files/en-us/web/api/atob/index.md
>      base64 encoded data.
I think a dash is needed there too.
```suggestion
    base64-encoded data.
```

2022-05-03 23:46 UTC, wbamberg approved these changes
👍 thanks!

2022-05-04 04:45 UTC, teoli2003 approved these changes

2022-05-04 04:45 UTC, merged

2022-05-04 04:46 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

2022-05-05 06:52 UTC, KRicky13 commented
Woohoo! Thanks all for reviewing and approving. How exciting!