Update hashchange event to new structure
mdn/content pull request #14515
Opened 2022-03-31 14:57 UTC by Elchi3

This is a first attempt to reorganize content for WindowEventHandlers. It is using the `hashchange` event as an example.
BCD discussion that lead to this: https://github.com/mdn/browser-compat-data/pull/15477

What this does:

- Makes Window/hashchange_event the main page for the `hashchange` event
- Updates Window/hashchange_event to the new format
- Redirects windowEventHandlers/onhashchange to window/hashchange_event
- Adds a section called "Event targets" to Window/hashchange_event mentioning the other 3 targets this event can be called on:
  - HTMLBodyElement
  - HTMLFrameSetElement
  - SVGSVGElement
- Updates the interface pages HTMLBodyElement, HTMLFrameSetElement and SVGSVGElement to have an "Event handler" section that says there are events from Window available. (and removes the onhashchange event handler on these pages)

cc @teoli2003 and @queengooborg to take a look at this approach.

2022-04-01 09:48 UTC, foolip commented on files/en-us/web/api/htmlbodyelement/index.md
> +The following events are available via `WindowEventHandlers`.
Can we remove mentions of `WindowEventHandlers` throughout? It's a mixin, and referring to it doesn't quite explain why it's possible to listened for an event whose target is `Window` on `HTMLBodyElement`.

The weirdness is shown by this example:
```js
document.body.onhashchange = () => console.log('this callback is called')
document.body.addEventListener('hashchange', () => console.log('this callback is NOT called'))
window.location.hash = '#ha'
```

Only "this callback is called" will be logged.

Maybe we can describe the event handler properties as "aliases" of the same on `Window`, and not that `addEventListener` doesn't work?

2022-04-01 10:42 UTC, Elchi3 commented on files/en-us/web/api/htmlbodyelement/index.md
> +The following events are available via `WindowEventHandlers`.
This is so weird. wow. Thanks for explaining what is going on here, I had no idea. I tried to reword this in https://github.com/mdn/content/pull/14515/commits/eed1d95b9365097d9a93a4b11d9e1da259e234d9. I hope I understood you correctly.

2022-04-04 09:56 UTC, teoli2003 requested changes
I try to improve the formulation, but maybe I'm too verbose now.

2022-04-04 09:56 UTC, teoli2003 commented on files/en-us/web/api/htmlbodyelement/index.md
> +The {{domxref("HTMLElement")}} events are inherited and the following {{domxref("Window")}} event handler properties are also available on `HTMLBodyElement` as aliases.
So I wasn't able to understand it during the first reading, but @Elchi3 explained it to me.

So I'm proposing two changes:
```suggestion
The {{domxref("HTMLElement")}} events are inherited and the following {{domxref("Window")}} event handler properties (of the `onXYZ` form) are also available on `HTMLBodyElement` as aliases. Even set here, they do apply to the `Window` object.
```

2022-04-04 09:56 UTC, teoli2003 commented on files/en-us/web/api/htmlbodyelement/index.md
> +
```suggestion
> **Note:** Using `addEventListener()` on this object will not work for these events, as they are really dispatched at the {{domxref("window")}} object.
```

2022-04-04 12:27 UTC, Elchi3 commented on files/en-us/web/api/htmlbodyelement/index.md
> +
Alternative: 

```suggestion
> **Note:** Using `addEventListener()` on `HTMLBodyElement` will not work for the `onXYZ` event handlers listed here. It is advised to use the events on the {{domxref("window")}} object instead.
```

2022-04-04 12:29 UTC, teoli2003 commented on files/en-us/web/api/htmlbodyelement/index.md
> +
I like the alternative with a small nit: _advise to listen to the events_ instead of _to use_.

2022-04-04 12:31 UTC, Elchi3 commented on files/en-us/web/api/htmlbodyelement/index.md
> +The {{domxref("HTMLElement")}} events are inherited and the following {{domxref("Window")}} event handler properties are also available on `HTMLBodyElement` as aliases.
Alternative:

```suggestion
The {{domxref("HTMLElement")}} events are inherited. The following {{domxref("Window")}} `onXYZ` event handler properties are also available as aliases targeting the `window` object. It is advised to call them on the `window` object directly rather than on `HTMLBodyElement`.
```

2022-04-04 12:33 UTC, Elchi3 commented
I made another suggestion to advice the reader to use the window object for these events instead.

2022-04-04 12:39 UTC, Elchi3 commented on files/en-us/web/api/htmlbodyelement/index.md
> +
Yes, thanks! Updated.

2022-04-04 13:09 UTC, teoli2003 approved these changes
Approving this so this doesn't get stuck (even if not all changes have been committed yet)

2022-04-04 14:22 UTC, merged