Move CSS system color keywords to their own page
mdn/content pull request #14647
Opened 2022-04-04 12:08 UTC by teoli2003

Part of https://github.com/openwebdocs/project/issues/92 (revamp our color guide and reference).

This PR moves the system-related color keywords into their own page (taking them off the `<color>` page).

Note:
- There is much more work to be done on the `<color>` page, I intentionally limited this PR by moving the color keywords only.
- We don't have BCD info for these, so I didn't add a _Browser compatibility_ section to it (I'll see if I have time to come back to this during this project, but this is secondary).

2022-04-13 09:13 UTC, dipikabh requested changes

2022-04-13 09:13 UTC, dipikabh commented on files/en-us/web/css/color_value/system_color_keywords/index.md
> +slug: Web/CSS/color_value/System_color_keywords
```suggestion
slug: Web/CSS/color_value/system_color_keywords
```
To match casing in slug here: "https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color_keywords"

2022-04-13 09:13 UTC, dipikabh commented on files/en-us/web/css/color_value/system_color_keywords/index.md
> +## Firefox non-standard System Color Extensions
```suggestion
## Firefox non-standard system color extensions
```

2022-04-13 09:13 UTC, dipikabh commented on files/en-us/web/css/color_value/system_color_keywords/index.md
> +Firefox also support some non-standard extensions to the system color keyword set.
```suggestion
Firefox also supports some non-standard extensions to the system color keyword set. 
```

2022-04-13 09:13 UTC, dipikabh commented on files/en-us/web/css/color_value/system_color_keywords/index.md
> +- `-moz-MenuBarHoverText
```suggestion
- `-moz-MenuBarHoverText`  {{non-standard_inline}}
```

2022-04-13 09:13 UTC, dipikabh commented on files/en-us/web/css/color_value/system_color_keywords/index.md
> +- [`<color>`](/en-US/docs/Web/CSS/color_value) the data type these keywords belong to.
```suggestion
- [`<color>`](/en-US/docs/Web/CSS/color_value) data type these keywords belong to.
```

2022-04-19 21:12 UTC, dipikabh approved these changes
Looks good! 👍 Thank you.

2022-04-19 21:12 UTC, merged

2022-04-20 00:13 UTC, alialh600pp commented
`files/en-us/mozilla/add-ons/webextensions/api/scripting/injectionresult/index.md`