Scripting API documentation
mdn/content pull request #14725
Opened 2022-04-05 22:57 UTC by rebloor

#### Summary
To add the documentation for the new Scripting API, including:

- scripting.executeScript (pending)
- scripting.insertCSS (draft included)
- scripting.removeCSS (pending)
- scripting.getRegisteredContentScripts (pending)
- scripting.registerContentScripts (pending)
- scripting.unregisterContentScripts (pending)
- scripting.updateContentScripts (pending)

#### Related issues
Addresses the requirements of these Bugzilla tickets:

– [1736579](https://bugzilla.mozilla.org/show_bug.cgi?id=1736579) Implement `scripting.insertCSS()` 	
– [1736580](https://bugzilla.mozilla.org/show_bug.cgi?id=1736580) Implement `scripting.removeCSS()` 	
– [1736581](https://bugzilla.mozilla.org/show_bug.cgi?id=1736581) Implement `scripting.getRegisteredContentScripts()` 	
– [1736582](https://bugzilla.mozilla.org/show_bug.cgi?id=1736582) Initial implementation of `scripting.registerContentScripts()` 	
– [1736584](https://bugzilla.mozilla.org/show_bug.cgi?id=1736584) Implement `scripting.unregisterContentScripts()` 	
– [1736585](https://bugzilla.mozilla.org/show_bug.cgi?id=1736585) Implement `scripting.updateContentScripts()`

#### Metadata
This PR…

- [x] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-06 11:40 UTC, Rob--W commented
At the moment, only insertCSS / removeCSS have been added, while the PR claims to be adding docs for the full namespace.
And the PR is also in a draft state.

Am I expected to already start reviewing, or do you want to finish the draft first?

2022-04-06 16:23 UTC, rebloor commented
> Can someone add me as a reviewer please? (I landed these APIs) Thanks.

@Rob--W any ideas, he doesn't come up when search in the reviewers section

2022-04-06 18:41 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```js
@willdurand could you suggest suitable example?

2022-04-13 12:56 UTC, willdurand reviewed
Some comments (first pass).

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/optional_permissions/index.md
> +- `scripting` (Manifest V3 or hidher)
```suggestion
- `scripting` (Manifest V3 or higher)
```

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +- `scripting` (Manifest V3 or hidher)
```suggestion
- `scripting` (Manifest V3 or higher)
```

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result of the script is the last evaluated statement, which is similar the results that would be seen if you executed the script in the [Web Console](/en-US/docs/Tools/Web_Console) (not any `cons
```suggestion
The result of the script is the last evaluated statement, which is similar to the results that would be seen if you executed the script in the [Web Console](/en-US/docs/Tools/Web_Console) (not any `console.log()` output). For example, consider a script like this:
```

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result of the script is the last evaluated statement, which is similar the results that would be seen if you executed the script in the [Web Console](/en-US/docs/Tools/Web_Console) (not any `cons
> (not any `console.log()` output)

What does that mean?

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +executing.then(onExecuted, onError);
async/await would make the code more readable IMO but I don't know what the guidelines are.

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +  file: "/content-script.js",
I don't think we support `file`, instead it should be:

```suggestion
  files: ["content-script.js"],
```

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +  file: "/content-script.js",
Also I think the `target` is mandatory.

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +const executing = browser.tabs.executeScript({
Shouldn't we document the `scripting` namespace?

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```js
At the very least, I think we should have the following props:

```js
const script = {
    id: "a-script",
    js: ["script.js"],
    matches: ["http://*/*/file_sample.html"],  
    persistAcrossSessions: false,
};
```

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +This example updates a script file called `script.js`:
I think it rather updates a _registered content script_ called `"a-script"`.

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +      - : `boolean`. Whether the content script persists into future sessions.
I think we have to declare this prop and set it to `false` in FF for now, until we have full support for `persistAcrossSessions` ([Bug 1751436](https://bugzilla.mozilla.org/show_bug.cgi?id=1751436)).

2022-04-13 12:56 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/scriptinjection/index.md
> +- `funcfunc`
```suggestion
- `func`
```

2022-04-13 14:20 UTC, Rob--W requested changes
I have done a full pass for review, but expect that I'll need another full pass after your update in response to review feedback.

I've only commented in some places, but you should consistently apply this feedback to all docs:

- Mark properties as optional if they are not required.
- You're using `tabs[0].id` in several examples, but `tabs` is not a thing. Use `tab.id` instead).
- The return value of all APIs is a promise that resolves to a value. Several articles simply state "returns [description]` followed by `Returns a Promise`. Let's always document that it returns a promise.
- Remove the "callback" parameter. All async APIs always support a callback if not specified. Until relatively recently, Chrome did not support promises, just callbacks, hence their confusing signature / docs. For more info, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#callbacks_and_promises and https://developer.chrome.com/docs/extensions/mv3/promises/
- In examples, use async/await instead of .then

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/scriptinjection/index.md
> +title: scripting.ScriptInjection
Merge with executescript/index.md.

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/scriptinjection/index.md
> +  - : `string`. An array of path of the JS or CSS files to inject, relative to the extension's root directory. Exactly one of `files` and `func` must be specified.
```suggestion
  - : `string`. An array of path of the JS files to inject, relative to the extension's root directory. Exactly one of `files` and `func` must be specified.
```

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/scriptinjection/index.md
> +  - : {{WebExtAPIRef("manifest.InjectionTarget")}}. Details specifying the target to inject the script into.
```suggestion
  - : {{WebExtAPIRef("scripting.InjectionTarget")}}. Details specifying the target to inject the script into.   
```

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/scriptinjection/index.md
> +- `args`
Shouldn't `args`, `files` and `func` be marked as optional, even though exactly one of files/func is required?

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +  - : {{WebExtAPIRef("scripting.ContentScriptFilter")}}. A filter to identify the dynamic content scripts to unregistered. If not specified, all dynamic content scripts are unregistered.
```suggestion
  - : `array` of {{WebExtAPIRef("scripting.ContentScriptFilter")}}. A filter to identify the dynamic content scripts to unregistered. If not specified, all dynamic content scripts are unregistered.
```

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +    - `persistAcrossSessions`
This flag is part of RegisteredContentScript.

The type should just be "an array of RegisteredContentScript", similar to how `registerContentScripts` is documented.

2022-04-13 14:20 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +This example updates a script file called `script.js`:
Let's make this example more meaningful:

1. Register a script first.
2. Update the script by changing matches from example.com to `["https://example.com/*", "https://example.net/*"]` to show that one can change the set of URLs where the script is injected.

2022-04-13 17:01 UTC, rebloor commented
Thanks for the feedback @Rob--W. I'm waiting on @willdurand to provide updated examples.
Regarding "Mark properties as optional if they are not required." thought I had done this, are all the examples I missed marked?

2022-04-13 19:25 UTC, Rob--W commented
> Thanks for the feedback @Rob--W. I'm waiting on @willdurand to provide updated examples

In one of the commits I referred to unit tests in Firefox's source code (via Searchfox). Does that help or do you actually need the full code snippet to proceed?

> Regarding "Mark properties as optional if they are not required." thought I had done this, are all the examples I missed marked? 

I didn't mark them all, but I will do that at the next full review pass.

2022-04-17 18:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```js
It would be helpful if you could check and confirm/suggest examples. Given that you're closer to this and I'm not actively developing code I'd like to focus on the remaining MV3 documentation. If you can't help out, please let me know.

2022-04-17 18:46 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : `boolean`. Specifies if this content script persists into future sessions. Defaults to `false`. This is NOT supported.
@Rob--W but persistent scripts are going to be supported for the MV3 developer preview, correct? Therefore we should delete the "This is NOT supported." given that none of this is usable until we have the MV3 developer preview

2022-04-17 19:03 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/contentscriptfilter/index.md
> +> **Note:** This API is based on Chromium's [`chrome.scripting`](https://developer.chrome.com/extensions/scripting#type-ContentScriptFilter) API. This documentation is derived from [`scripting.json`]
All occurrences removed in https://github.com/mdn/content/pull/14725/commits/24258f349815a6be05896c2160132f3b74c8f5f7

2022-04-17 19:09 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/contentscriptfilter/index.md
> +<div class="hidden"><pre>// Copyright 2015 The Chromium Authors. All rights reserved.
Removed in https://github.com/mdn/content/pull/14725/commits/8dfb7bad09a824a241f6acfaec572736acecee24

2022-04-19 03:12 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that is fulfilled with {{WebExtAPIRef("scripting.InjectionResult")}}. The array's values represent the result of the script
@Rob--W I don't follow, so this doesn't return InjectionResult? Also, I'm struggling to find an example where content returned from a promise is in line. Are you aware of any examples?

2022-04-19 03:13 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +If any error occurs, the promise is rejected with an error message.
@Rob--W could you be more explicit about what you think should be said about the era returned?

2022-04-19 22:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +Returns an array of {{WebExtAPIRef("scripting.RegisteredContentScript")}}.
Fixed in https://github.com/mdn/content/pull/14725/commits/d821ffdb90cb8876316952492e937a3b7719e3e2

2022-04-19 22:59 UTC, rebloor commented
@Rob--W  https://github.com/mdn/content/pull/14725/commits/d821ffdb90cb8876316952492e937a3b7719e3e2 addresses:

- The return value of all APIs is a promise that resolves to a value. Several articles simply state "returns [description]followed by Returns a Promise`. Let's always document that it returns a promise.
- Remove the "callback" parameter. All async APIs always support a callback if not specified. Until relatively recently, Chrome did not support promises, just callbacks, hence their confusing signature / docs. For more info, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#callbacks_and_promises and https://developer.chrome.com/docs/extensions/mv3/promises/

2022-04-20 00:03 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +Registers one or more content scripts. If there are errors during script parsing and file validation, or if the IDs specified exist, no scripts are registered.
Moved to returned value section

2022-04-20 00:04 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `excludeMatches`{{optional_inline}}
Properties are now in alphabetical order in all cases, as they should be

2022-04-20 01:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/injectionresult/index.md
> +title: scripting.InjectionResult
I've not found examples of return values documented in line, can you point me at one?

2022-04-27 10:32 UTC, willdurand commented
@rebloor @Rob--W I just landed https://bugzilla.mozilla.org/show_bug.cgi?id=1762366 so we could document this option as well, thanks!

2022-04-27 18:50 UTC, rebloor commented
@willdurand I have added `injectImmediately`, however, could you clarify "but not necessarily prior to page load", it seems a little vague

2022-04-30 11:40 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
Note for myself: we'll have to take [our decision into account](https://bugzilla.mozilla.org/show_bug.cgi?id=1759117#c2) and document the difference here. In Firefox, `run_at` will apply to both `js` and `css` when both are passed and we won't unconditionally inject css at `document_start`.

2022-05-03 13:37 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : `boolean`. Specifies if this content script persists into future sessions. Defaults to `false`. This is NOT supported.
@rebloor yes it will eventually be supported but Firefox requires this property to be set to `false` unconditionally currently. Its value defaults to `true` on Chromium browsers.

2022-05-04 09:13 UTC, willdurand reviewed
Some more feedback, sorry for the delay!

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/removecss/index.md
> +});
```suggestion
const tabs = await browser.tabs.query({ active: true });

const style = "* { background: #c0ffee }";

await browser.scripting.insertCSS({
  target: { tabId: tabs[0].id },
  css: style,
});

browser.action.onClicked.addListener(() => {
  await browser.scripting.removeCSS({
    target: { tabId: tabs[0].id },
    css: style,
  });
});
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +  - : `array` of {{WebExtAPIRef("scripting.ContentScriptFilter")}}. A filter to identify the dynamic content scripts to unregistered. If not specified, all dynamic content scripts are unregistered.
`scripts` is actually an object of type `ContentScriptFilter`.

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +This example unregisters a script the ID `a-script`:
```suggestion
This example unregisters a content script that was previously registered with ID `a-script`:
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +await browser.scripting.unregisterContentScripts([scriptFilter]);
```suggestion
await browser.scripting.unregisterContentScripts({
  ids: ["a-script"],
});
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +)
```suggestion
await browser.scripting.updateContentScripts(
  scripts         // object
)
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +- `scripts`
`scripts` is an array of `RegisteredContentScript`

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that fulfills with an array of {{WebExtAPIRef("scripting.RegisteredContentScript")}}. If any error occurs, the promise fulfi
It's similar to another sentence I've seen previously and I am confused: why is this described in the "return value" section? `scripting.updateContentScripts()` returns a promise that either resolves or rejects but when it resolves, there is no return value.

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +This example updates a script file called `a-script.js`:
```suggestion
This example updates a content script that was previously registered with ID `a-script` by setting `allFrames` to `true`:
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +await browser.scripting.updateContentScripts([aScript]);
```suggestion
await browser.scripting.updateContentScripts([
  {
    id: "a-script",
    allFrames: true,
  },
]);
```

2022-05-04 09:13 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +- `scripts`
For updates, all but the `id` properties are optional in `RegisteredContentScript`.

2022-05-04 09:49 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/index.md
> +Alternatively, you can get these permissions temporarily, only for the active tab and only in response to an explicit user action, by asking for the [`"activeTab"` permission](/en-US/docs/Mozilla/Add
FWIW, the `"scripting"` permission would still be required.

2022-05-04 23:14 UTC, rebloor reviewed
Hopefully, this addresses all feedback

2022-05-04 23:19 UTC, rebloor commented
@willdurand github won't let me request a re-review, so here is a manual request

2022-05-05 07:32 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```js
yes

2022-05-05 09:21 UTC, willdurand reviewed
Some more comments/suggestions to have a bit more consistency across all the pages. Thanks!

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/index.md
> +  - : Details of an injection target for CSS.
```suggestion
  - : Details of an injection target.
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The scripts you inject are called [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).
 
The scripts you inject are called [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +    console.error(`${err}`);
```suggestion
    console.error(`failed to insert CSS: ${err}`);
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +      target: { tabId: tab.id },
```suggestion
      target: {
        tabId: tab.id,
      },
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +    console.error(`${err}`);
```suggestion
    console.error(`failed to insert CSS: ${err}`);
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +      target: { tabId: tab.id },
```suggestion
      target: {
        tabId: tab.id,
      },
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +This example inserts CSS loaded from a file packaged with the extension:
```suggestion
This example inserts CSS loaded from a file (packaged with the extension) called `"content-style.css"`:
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that fulfills with an array of {{WebExtAPIRef("scripting.RegisteredContentScript")}}. If there are errors during script pars
```suggestion
A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that fulfills with an array of {{WebExtAPIRef("scripting.RegisteredContentScript")}}. If there are errors during script parsing and file validation, or if the IDs specified do not exist, no scripts are registered and the promise is rejected.
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +This example registers a script file called `script.js`:
```suggestion
This example registers a content script that will inject the file `"script.js"`:
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +await browser.scripting.registerContentScripts([aScript]);
```suggestion
const aScript = {
  id: "a-script",
  js: ["script.js"],
  matches: ["https://example.com/*"],
};

await browser.scripting.registerContentScripts([aScript]);
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
@rebloor any idea where we could document the difference? This has to do with the `css` array described a few lines above. Chrome documents it as such:

> The list of CSS files to be injected into matching pages. These are injected in the order they appear in this array, before any DOM is constructed or displayed for the page.

We don't because we do not unconditionally inject CSS "before any DOM is constructed or displayed for the page"

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).
 
This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).
 
This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +  - : `array` of {{WebExtAPIRef("scripting.RegisteredContentScript")}}. A list of scripts to register.
is this correct? (no name before the colon)

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/removecss/index.md
> +This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).

This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/removecss/index.md
> +});
```suggestion
// Assuming some style has been injected previously with the following code:
//
// await browser.scripting.insertCSS({
//   target: {
//     tabId: tab.id,
//   },
//   css: "* { background: #c0ffee }",
// });
//
// We can remove it when a user clicked an extension button like this:
browser.action.onClicked.addListener(async tab => {
  try {
    await browser.scripting.removeCSS({
      target: {
        tabId: tab.id,
      },
      css: "* { background: #c0ffee }",
    });
  } catch (err) {
    console.error(`failed to remove CSS: ${err}`);
  }
});
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).

This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/unregistercontentscripts/index.md
> +let removing = browser.scripting.unregisterContentScripts(
```suggestion
await browser.scripting.unregisterContentScripts(
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```suggestion
 To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).

This is an asynchronous function that returns a [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +Updates registered content scripts. If there are errors during script parsing and file validation, or if the IDs specified do not exist, no scripts are updated.
```suggestion
Updates already registered content scripts. If there are errors during script parsing and file validation, or if the IDs specified do not exist, no scripts are updated.
```

2022-05-05 09:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +]);
```suggestion
await browser.scripting.registerContentScripts([
  {
    id: "a-script",
    js: ["script.js"],
    matches: ["*://example.org/*"],
  },
]);

// Update content script registered before to allow execution in all frames:
await browser.scripting.updateContentScripts([
  {
    id: "a-script",
    allFrames: true,
  },
]);
```

2022-05-05 17:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```js
Thanks

2022-05-05 18:01 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registercontentscripts/index.md
> +  - : `array` of {{WebExtAPIRef("scripting.RegisteredContentScript")}}. A list of scripts to register.
Perhaps I'm missing something, but this is following the standard formatting

2022-05-05 18:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
We sometimes document differences between the browsers as part of the browser compatibility data. However, if this relates to the effect of this property it might not get noticed in the compatibility data section. So, might be better to add something here (for the `css` property I assume. Perhaps something like "In Chrome, CSS is injected before any DOM is constructed or display for the page. By contrast, in Firefox injection occurs after the DOM is constructed."

2022-05-06 13:21 UTC, willdurand reviewed
Some more error handling in the examples, one example that should be removed and a general comment about this API being available in Manifest Version 2 in Firefox.

That looks good (I did this review using the preview links). IMO we're almost done here.

2022-05-06 13:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```
please remove this example, it is already covered in the one above.

2022-05-06 13:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +This example updates a registered content script with ID `a-script` by setting `allFrames` to `true`:
```suggestion
This example updates a content script registered with ID `a-script` by setting `allFrames` to `true`:
```

2022-05-06 13:21 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +]);
```suggestion
try {
  await browser.scripting.registerContentScripts([
    {
      id: "a-script",
      js: ["script.js"],
      matches: ["*://example.org/*"],
    },
  ]);

  // Update content script registered before to allow execution in all frames:
  await browser.scripting.updateContentScripts([
    {
      id: "a-script",
      allFrames: true,
    },
  ]);
} catch (err) {
  console.error(`failed to register or update content scripts: ${err}`);
}
```

2022-05-06 13:30 UTC, willdurand commented
I would also like to discuss how we can document the following differences in Firefox:

- we respect `runAt` for both JS **and** CSS when registering a content script, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1759117 (Chrome unconditionally applies CSS at `document_start`)
- we do not support `persistAcrossSessions: true` yet (the default in Chrome), see: https://bugzilla.mozilla.org/show_bug.cgi?id=1751436. As such, we require `persistAcrossSessions: false` to be passed to `scripting.registerContentScripts()`
- we do not support `world: 'MAIN'`, see https://bugzilla.mozilla.org/show_bug.cgi?id=1736575

2022-05-06 16:19 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +> **Note:** This method is available in Manifest V3 or higher.
```suggestion
> **Note:** This method is available in Manifest V3 or higher. It's also available in Manifest V2 from Firefox version 102.
```

2022-05-06 16:20 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +This example returns the registered scripts with the ID `a-script`:
```suggestion

```

2022-05-06 16:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
@willdurand sorry, I'm now a little unclear. Are you saying that chrome doesn't respect `runAt`? Could you suggest wording for the additional note?

2022-05-06 16:28 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/getregisteredcontentscripts/index.md
> +```
```suggestion
```

2022-05-06 16:31 UTC, rebloor commented
@willdurand thanks, I've merged in your suggestions, i'll review your three points of difference and how to document them on Monday

2022-05-10 15:25 UTC, willdurand reviewed
Let's remove `InjectionResult`

2022-05-10 15:25 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/injectionresult/index.md
> +title: scripting.InjectionResult
I talked to @Rob--W and we should do that. Let me send some suggestions. Please remove this page.

2022-05-10 15:25 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that fulfills with an array of {{WebExtAPIRef("scripting.InjectionResult")}}. The array's values represent the result of the
```suggestion
A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that fulfills with an array of `InjectionResult` objects, which represent the result of the injected script in every injected frame. If any error occurs, the promise is rejected.

Each `InjectionResult` object has the following properties:

- `frameId`
  - : `number`. The frame ID associated with the injection.
- `result`{{optional_inline}}
  - : `any`. The result of the script execution.
- `error`{{optional_inline}}
  - : `object`. When the injection fails, details of the failure errors.
    - `message`
      - : `string`. A message explaining why the injection failed.
```

2022-05-10 18:45 UTC, rebloor commented
Thanks @willdurand I have completed the removal of InjectionResult. I've pinged you on one outstanding item. @Rob--W is everything OK from your point of you, can you clear the "change requested"?

2022-05-10 18:45 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
@willdurand just in case you missed it :-)

2022-05-11 06:23 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
ha sorry yeah, definitely missed that one.

Chrome uses the value in `runAt` for `js` only, `css` is always injected early ("before any DOM is constructed or displayed for the page"). I think what we have right now is fine, though.

We'll add some more information using the compat data.

2022-05-11 08:15 UTC, willdurand commented
About my comment above:
 
> we do not support `persistAcrossSessions: true` yet (the default in Chrome), see: [bugzilla.mozilla.org/show_bug.cgi?id=1751436](https://bugzilla.mozilla.org/show_bug.cgi?id=1751436). As such, we require `persistAcrossSessions: false` to be passed to `scripting.registerContentScripts()`

and
 
> we do not support `world: 'MAIN'`, see [bugzilla.mozilla.org/show_bug.cgi?id=1736575](https://bugzilla.mozilla.org/show_bug.cgi?id=1736575)

could be documented in the [browser compat data](https://github.com/mdn/browser-compat-data). Did you start a PR for that?

As for:

> we respect `runAt` for both JS **and** CSS when registering a content script, see: [bugzilla.mozilla.org/show_bug.cgi?id=1759117](https://bugzilla.mozilla.org/show_bug.cgi?id=1759117) (Chrome unconditionally applies CSS at `document_start`)

Maybe that could documented in the browser compat data as well? There is a bug on the Chromium tracker and @Rob--W said that would likely be implemented: https://bugs.chromium.org/p/chromium/issues/detail?id=1271527

2022-05-11 09:24 UTC, rebloor commented
> could be documented in the [browser compat data](https://github.com/mdn/browser-compat-data). Did you start a PR for that?
Yes, https://github.com/mdn/browser-compat-data/pull/15872

2022-05-12 08:39 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +> **Note:** This method is available in Manifest V3 or higher. It's also available in Manifest V2 from Firefox version 102.
About this method being supported in MV2 from Firefox version 102. This is true for everything that we documented here, the whole `scripting` namespace is available in FF 102+.

2022-05-12 08:39 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +  // Update content script registered before to allow execution in all frames:
```suggestion
  // Update content script registered before to allow execution
  // in all frames:
```

(a bit more readable in the preview IMO)

2022-05-12 17:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +> **Note:** This method is available in Manifest V3 or higher. It's also available in Manifest V2 from Firefox version 102.
I've updated all the notes,

2022-05-12 18:03 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
@willdurand could you provide the appropriate feedback on https://github.com/mdn/browser-compat-data/pull/15872?

2022-05-12 18:29 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/updatecontentscripts/index.md
> +  // Update content script registered before to allow execution in all frames:
Updated

2022-05-12 22:19 UTC, Rob--W requested changes
I have suggested a whole bunch of edits that you can directly include by clicking on the interface in Github (and then pull locally), which are mostly an edit to make the types of array properties more accurate.

Most of the changes are straightforward, but the changes in `executescript/index.md` are less trivial (and may require copy-editing)

Besides that I have also suggested edits to clarify the role of host permissions,
and a rephrase of the MV3 requirement, which needs to be applied universally to each file. I didn't offer a suggested edit for that because you probably want to copy-edit before applying the change to every file.

Finally, please add scripting as generally available in the release notes of 102 https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/102/index.md. We recently enabled that in 102 (https://bugzilla.mozilla.org/show_bug.cgi?id=1766615).

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/index.md
> +This API requires the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) permission and [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manife
```suggestion
This API requires the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) permission and [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) for the target in the tab into which JavaScript or CSS is injected.
```

As mentioned in the executeScript docs, the permissions are generally only required for the target. Chrome as a special case currently requires permissions for the tab, but that may change.

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/injectiontarget/index.md
> +  - : `string`. Array of the IDs of the frames to inject into.
```suggestion
  - : `array` of `string`. Array of the IDs of the frames to inject into. 
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/injectiontarget/index.md
> +  - : `boolean`. Whether the CSS is inject into all frames within the tab. Defaults to `false`. Cannot be `true` if `frameIds` is specified.
```suggestion
  - : `boolean`. Whether the script or CSS is injected into all frames within the tab. Defaults to `false`. Cannot be `true` if `frameIds` is specified.
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the page's URL, either explicitly as a [host permi
```suggestion
To use this API you must have the `"scripting"` [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) and permission for the target's URL, either explicitly as a [host permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or using the [activeTab permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission).
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/insertcss/index.md
> +      - : `string`. The path of a CSS files to inject, relative to the extension's root directory. Either `files` or `css` must be specified.
```suggestion
      - : `array` of `string`. The path of a CSS files to inject, relative to the extension's root directory. Either `files` or `css` must be specified. 
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : `string`. Array of pages that this content script is excluded from but would otherwise be injected into.
```suggestion
  - : `array` of `string`. Array of pages that this content script is excluded from but would otherwise be injected into.
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : `string`. Array of path to JavaScript files in the extension package to inject into matching pages. Scripts are injected in the order they appear in this array.
```suggestion
  - : `array` of `string`. Array of path to JavaScript files in the extension package to inject into matching pages. Scripts are injected in the order they appear in this array.
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : `string`. Array of the pages this content script is injected into. Must be specified for {{WebExtAPIRef("scripting.registerContentScripts()")}}.
```suggestion
  - : `array` of `string`. Array of the pages this content script is injected into. Must be specified for {{WebExtAPIRef("scripting.registerContentScripts()")}}.
```

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +  - : {{WebExtAPIRef("extensionTypes.RunAt")}}. Specifies when JavaScript files are injected into the web page. The default value is `document_idle`.
```suggestion
  - : {{WebExtAPIRef("extensionTypes.RunAt")}}. Specifies when JavaScript files are injected into the web page. The default value is `document_idle`. In Firefox, `runAt` also affects the point where the CSS is inserted. In Chrome, `runAt` does not affect the CSS insertion point.
```

My suggestion probably needs to be rephrased, but the message is right.

2022-05-12 22:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/removecss/index.md
> +      - : `string`. The path of a CSS files to inject, relative to the extension's root directory. Either `files` or `css` must be specified and must match the stylesheet inserted through {{WebExtAPI
```suggestion
      - : `array` of `string`. The path of a CSS files to inject, relative to the extension's root directory. Either `files` or `css` must be specified and must match the stylesheet inserted through {{WebExtAPIRef("scripting.insertCSS()")}}.
```

2022-05-12 23:21 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +- `scripting` (Manifest V3 or higher)
```suggestion
- `scripting`
```

2022-05-12 23:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +> **Note:** This method is available in Manifest V3 or higher. It's also available in Manifest V2 from Firefox version 102.
I went for the note update, checked the BCD and eliminated the Safari reference where appropriate.

2022-05-12 23:39 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/registeredcontentscript/index.md
> +- `runAt`{{optional_inline}}
@willdurand I assume Rob's suggestion and the change below adds the information needed

2022-05-13 11:52 UTC, Rob--W approved these changes
Looks good. One edit (method -> API for the note in the scripting API article) plus a request for release changes of 102:

> Finally, please add scripting as generally available in the release notes of 102 https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/102/index.md. We recently enabled that in 102 (https://bugzilla.mozilla.org/show_bug.cgi?id=1766615).

2022-05-13 11:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/index.md
> +> **Note:** **Note:** This method is available in Manifest V3 or higher in Chrome and Firefox 101. In Safari and Firefox 102+, this method is also available in Manifest V2.
```suggestion
> **Note:** **Note:** This API is available in Manifest V3 or higher in Chrome and Firefox 101. In Safari and Firefox 102+, this API is also available in Manifest V2.
```

2022-05-13 16:43 UTC, merged

2022-05-14 05:57 UTC, queengooborg commented
This shouldn't have been merged just yet as the build test failed.  In one of the files, there was only two hyphens rather than three, so Yari couldn't parse meta tags.