DRAFt: New Document: spinbutton role
mdn/content pull request #14764
Opened 2022-04-06 23:59 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-19 14:16 UTC, dipikabh requested changes
Hi @estelle, I've done a readthrough of this document - just a readability and language check. I hope my suggestions have not introduced any technical inaccuracy - please feel free to redo the suggestion if it is not accurate.

2022-04-19 14:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +### Prefer HTML
```suggestion
### Prefer semantic HTML
```

2022-04-19 14:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +When not using the HTML {{HTMLElement('input')}} element to create your spinbutton, include the {{htmlattrxref('tabindex')}} attribute to make the spinbutton focusable. `spinbutton` is user-interacti
```suggestion
When not using the HTML {{HTMLElement('input')}} element to create your spinbutton, include the {{htmlattrxref('tabindex')}} attribute to make the spinbutton focusable. The `spinbutton` role is user-interactive, and therefore, requires being able to receive focus. Focus should be placed on the spinbutton input and not on the associated buttons that increment and decrement the spinbutton value.
```

2022-04-19 14:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +An accessible name is **required**. If the spinbuttons's role is applied to an HTML {{HTMLElement('input')}} element, the accessible name can come from the associated {{HTMLElement('label')}}. Otherw
```suggestion
An accessible name is **required**. If the `spinbutton` role is applied to an HTML {{HTMLElement('input')}} element, the accessible name can come from the associated {{HTMLElement('label')}}. Otherwise, use [`aria-labelledby`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) if a visible label is present or  [`aria-label`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) if a visible label is not present.
```

2022-04-19 14:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +When `aria-valuetext` is an important feature for a spinbutton, consider using {{HTMLElement('select')}} with {{HTMLElement('option')}} elements instead. The `<select>` doesn't provide for a  every o
The second sentence is not clear.

2022-04-19 14:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +The `aria-valuetext` value must be updated as the `value` or `aria-valuenow` is updated. While there is no equivalent HTML attribute for `<input type="range">`, you can include `aria-valuetext` on an
```suggestion
The `aria-valuetext` value must be updated as the value or `aria-valuenow` is updated. While there is no equivalent HTML attribute for `<input type="range">`, you can include `aria-valuetext` on any {{htmlelement('input')}} type. ARIA attributes are supported on semantic HTML elements.
```

2022-04-19 19:25 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +  - : Assistive technologies often present the value of `aria-valuenow` as a number. If this would not be accurate, use `aria-valuetext` to provide the spinbutton with a more understandable value.
this would change the meaning.

2022-04-19 23:29 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +When `aria-valuetext` is an important feature for a spinbutton, consider using {{HTMLElement('select')}} with {{HTMLElement('option')}} elements instead. The `<select>` doesn't provide for a  every o
no kidding! what was I trying to say?

2022-04-28 19:02 UTC, dipikabh commented
Hi @estelle, I think these comments are pending. Everything else looks good.

- https://github.com/mdn/content/pull/14764#discussion_r853027513 (suggestion for changing heading to "Comparing the spinbutton role with other range options"  to avoid "The" in the beginning of the heading)
- https://github.com/mdn/content/pull/14764#discussion_r853068909 - I've added a new suggestion/question
- https://github.com/mdn/content/pull/14764#discussion_r853075053 - can we rewrite the description for `aria-label` as:
Defines a string value that labels the spinbutton element. This provides an accessible name to the element when no visible label is available.
- https://github.com/mdn/content/pull/14764#discussion_r853089814
- https://github.com/mdn/content/pull/14764#discussion_r853101520

2022-04-28 20:55 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +### The `spinbutton` role compared other range options
Changed to "ARIA range options" as it's not a comparison but an intro, so compare wasn't really the right word in the first place

2022-04-28 20:59 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +#### Common attributes
It is a subsection of the range options section, which is a level 3 header.

2022-04-28 21:05 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +| Page Up and Page Down | (Optional) decrease the value by a set amount greater than or equal to one step |
yes! good catch.

2022-04-28 21:07 UTC, estelle commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> + - : Defines a string value that label the spinbutton element providing an accessible name when no visible label is available to provide the required accessible name.
It now reads " Defines a string value providing the accessible name when no visible label is available to provide the required accessible name via {{HTMLElement('label')}} or `aria-labelledby`."

2022-04-28 21:34 UTC, estelle commented
rebase failed. Closing and opening a new PR

2022-04-28 21:34 UTC, closed without merging