Add web.dev/fast
mdn/content pull request #14793
Opened 2022-04-07 21:23 UTC by TheJaredWilcurt

#### Summary

Add link

#### Motivation

Since MDN is just linking to other resources, this is a reputable and detailed link that should be included on web optimization.

#### Metadata

* [ ] Adds a new document
* [ ] Rewrites (or significantly expands) a document
* [ ] Fixes a typo, bug, or other error

2022-04-08 06:38 UTC, teoli2003 requested changes
Just a rewording to give the actual title

2022-04-08 06:38 UTC, teoli2003 commented on files/en-us/web/guide/performance/index.md
> +- [Web.dev Guide](https://web.dev/fast/)
```suggestion
- [Fast load times](https://web.dev/fast/) on _web.dev_
```

2022-04-09 04:21 UTC, estelle submitted a review, later dismissed
The list is a list of tools. Web.dev/fast is a guide, not a tool. This would be a good addition as a "see also" as a reference to where you can find additional tools, but web.dev/fast should not be listed in the tools list.

2022-05-31 09:24 UTC, dipikabh commented
Hello @TheJaredWilcurt, as pointed out by Estelle, could you move "[Fast load times](https://web.dev/fast/) on _web.dev_" out of the list of tools and move it to a new section "See Also"? We should then be able to close this PR. Thanks!

2022-06-01 09:25 UTC, dipikabh approved these changes

2022-06-01 09:29 UTC, teoli2003 approved these changes

2022-06-01 09:29 UTC, merged