Create hexadecimal color syntax page
mdn/content pull request #14813
Opened 2022-04-08 13:51 UTC by teoli2003

As part of openwebdocs/project#92, this creates the hexadecimal color syntax page, and update the `color()` page to simplify it a bit and link to it.

2022-04-08 22:27 UTC, wbamberg commented
With a page types hat on, what kind of page is this? It's not a page describing a property, or a data type, or a functional notation. Or is it a guide page? If so it looks strangely like a reference page.

In https://github.com/mdn/content/discussions/5162#discussion-3374795 we have listed a possible set of CSS page types.

2022-04-09 05:57 UTC, teoli2003 commented
@wbamberg Ha! Like for every project, the devil is in the detail! Good catch.

This is definitively a reference page. `<color>` is a rare case, as far as I know. Data types are usually of two types:

1. a list of keywords and functions, separated by characters. Keywords don't have their own subpage (usually, except maybe for the 5-6 global ones), while functions have.
2. a unit (like `160deg`) that doesn't have a subpage either

The `<color>` type seems unique. It has a long list of functions (~10), a huge list of keywords (>200, the color keywords, the system keywords, `currentColor`, and `transparent`), and this hexadecimal notation (that has 4 different syntaxes).

To make it useful for the reader I'm going for a short description of each function and the hex notation on the `<color>` page and linking them to a subpage. I'm trying to keep the same structure as for a function for this page, but I have a different one for the [color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color_keywords) one.

So I think this one should have a type `css-function` (that we may want to rename for clarity). For color keywords, I may want to see if I can give the same structure but I'm not sure. I see in the list you linked `css-keyword` as a page type. Do we have a fixed structure for this? (I wasn't able to find one case) Maybe I should update the color keywords page to match it (if possible).

I'll have a closer look next week.

2022-04-11 14:58 UTC, teoli2003 commented
After thinking a bit about this, I think this is a css-function, even if the syntax is different.

2022-04-22 03:05 UTC, wbamberg requested changes

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +  - : The _red_ component of the color, in case-insensitive hexadecimal number betwen `0` and `ff` (255)). If there is only one number, it is duplicated: `1` means `11`.
```suggestion
  - : The _red_ component of the color, as a case-insensitive hexadecimal number between `0` and `ff` (255)). If there is only one number, it is duplicated: `1` means `11`.
```

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +  - : The _green_ component of the color, in case-insensitive hexadecimal number betwen `0` and `ff` (255)). If there is only one number, it is duplicated: `c` means `cc`.
```suggestion
  - : The _green_ component of the color, as a case-insensitive hexadecimal number between `0` and `ff` (255)). If there is only one number, it is duplicated: `c` means `cc`.
```

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +  - : The _blue_ component of the color, in case-insensitive hexadecimal number betwen `0` and `ff` (255)). If there is only one number, it is duplicated: `9` means `99`.
```suggestion
  - : The _blue_ component of the color, as a case-insensitive hexadecimal number between `0` and `ff` (255)). If there is only one number, it is duplicated: `9` means `99`.
```

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +  - : The _alpha_ component of the color, indicating its transparency, in case-insensitive hexadecimal number betwen `0` and `ff` (255)). If there is only one number, it is duplicated: `e` means `ee`
```suggestion
  - : The _alpha_ component of the color, indicating its transparency, as a case-insensitive hexadecimal number between `0` and `ff` (255)). If there is only one number, it is duplicated: `e` means `ee`. `0` represents a fully transparent color, and `ff`a fully opaque one.
```

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +```css hidden
Probably a matter of opinion, but I wouldn't hide these (especially not the CSS that sets the color). It's nice to be able to see the actual CSS that's doing the work.

I wouldn't hide the HTML either in this case, there's not much of it and I like being able to see all the code. But that's definitely more arguable.

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +{{Specifications}}
Will there be a spec_url in BCD for this?

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +## Value
Usually "Value" is an H3 under "Syntax".

2022-04-22 03:05 UTC, wbamberg commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +The **hexadecimal color syntax** is a notation allowing to describe a [sRGB](/en-US/docs/Glossary/RGB) color using its primary color components (red, green, blue) written as hexadecimal numbers, as w
```suggestion
The **hexadecimal color syntax** is a notation for describing an [sRGB](/en-US/docs/Glossary/RGB) color using its primary color components (red, green, blue) written as hexadecimal numbers, as well as its transparency. It can be used everywhere a [`<color>`](/en-US/docs/Web/CSS/color_value) type is allowed.
```

2022-04-22 03:09 UTC, wbamberg commented
> @wbamberg Ha! Like for every project, the devil is in the details! Good catch.
> 
> This is definitively a reference page. `<color>` is a rare case, as far as I know. Data types are usually of two kinds:
> 
>     1. a list of keywords and functions, separated by characters. Keywords don't have their own subpage (usually, except maybe for the 5-6 global ones), while functions have.
> 
>     2. a unit (like `160deg`) that doesn't have a subpage either
> 
> 
> The `<color>` type seems unique. It has a long list of functions (~10), a huge list of keywords (>200, the color keywords, the system keywords, `currentColor`, and `transparent`), and this hexadecimal notation (that has 4 different syntaxes).
> 
> To make it useful for the reader I'm going for a short description of each function and the hex notation on the `<color>` page and linking them to a subpage. I'm trying to keep the same structure as for a function for this page, but I have a different one for the [color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color_keywords) one.
> 
> So I think this one should have a type `css-function` (that we may want to rename for clarity). For color keywords, I may want to see if I can give the same structure but I'm not sure. I see in the list you linked `css-keyword` as a page type. Do we have a fixed structure for this? (I wasn't able to find one case) 

For example, https://developer.mozilla.org/en-US/docs/Web/CSS/inherit. I think we only have a few of these.

> Maybe I should update the color keywords page to match it (if possible).
> 
> I'll have a closer look next week.

I'm surprised to call it a function. I'd naively expect a function would need to have the `()` notation. Maybe there's some terrible "miscellany" type we'll need. For JS we ended up defining "js-language-feature" which tbh feels like an admission of defeat :).

2022-04-22 06:28 UTC, teoli2003 commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +{{Specifications}}
Yes, it landed in mdn/browser-compat-data#15762

2022-04-22 06:31 UTC, teoli2003 commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +## Value
Fixed.

2022-04-22 06:32 UTC, teoli2003 commented on files/en-us/web/css/color_value/hexadecimal_rgb/index.md
> +```css hidden
Fixed.

2022-04-22 06:36 UTC, teoli2003 commented
I fixed the comments, as well as resolved the conflict.

2022-04-22 20:07 UTC, wbamberg approved these changes
👍 thank you @teoli2003 !

2022-04-22 20:07 UTC, merged