FF100 WebAssembly Exceptions - JS API
mdn/content pull request #14925
Opened 2022-04-12 07:59 UTC by hamishwillee

FF100 is shipping WebAssembly exceptions: https://bugzilla.mozilla.org/show_bug.cgi?id=1759217

This is the JavaScript API. 
Other docs work can be tracked in #14392

2022-04-26 10:13 UTC, hamishwillee commented
@teoli2003 I know this is a bit rough :-). Its complete-ish in terms of what it is. I'm hoping to get some kind of independent sanity check on this before I provide more bigger picture stuff.

2022-04-27 15:16 UTC, dipikabh requested changes
Hi @hamishwillee, leaving some edit suggestions for your consideration after a quick proofread.

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/index.md
> +The code below below calls [`WebAssembly.instantiateStreaming`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) to import the  **example.wasm** file, passing in
```suggestion
The code below below calls [`WebAssembly.instantiateStreaming`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) to import the **example.wasm** file, passing in an "import object" (`importObject`) that includes a new {{jsxref("WebAssembly.Tag")}} named `tag_to_import`.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/index.md
> +However because we have the tag we use [`Exception.protoytpe.is()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/is) to check it's the right one, and because it is correc
```suggestion
However, because we have the tag, we use [`Exception.protoytpe.is()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/is) to check that it's the right one, and because it is correct, we call [`Exception.protoytpe.getArg()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/getArg) to read the value of "42".
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/getarg/index.md
> +> **Note:** It is not enough that the tag has an identical sequence of data types — it must have the same _identity_ (be the same tag).
```suggestion
> **Note:** It is not enough that the tag has an identical sequence of data types — it must have the same _identity_ (be the same tag) as was used to create the exception.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/is/index.md
> +We can also demonstrate that this exception will not match another tag, event if is created with the same parameters.
```suggestion
We can also demonstrate that this exception will not match another tag even if the tag is created with the same parameters.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/is/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +If WebAssembly code needs to provide a stack trace it must call a JavaScript function to create the exception, passing `options.traceStack=true` parameter in the [constructor](/en-US/docs/Web/JavaScr
```suggestion
If WebAssembly code needs to provide a stack trace, it must call a JavaScript function to create the exception, passing `options.traceStack=true` parameter in the [constructor](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/Exception).
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +It exports a method `run1` that can be called by external code to call $throwExnWithStack (and hence the JavaScript function)
```suggestion
This imports a tag, which it refers to as `$tagname` internally and imports a function that it refers to as `$throwExnWithStack`.
It exports the method `run1` that can be called by external code to call `$throwExnWithStack` (and hence the JavaScript function)
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +Passing in `{traceStack: true}` tells the WebAssembly virtual machine that it should attached the stack to the exception that it is throwing.
```suggestion
Passing in `{traceStack: true}` tells the WebAssembly virtual machine that it should attach the stack to the exception that it is throwing.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/index.md
> +When creating a [`WebAssembly.Exception`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception) the tag defines data-types and order of the values carried by the exception.
```suggestion
When creating a [`WebAssembly.Exception`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception), the tag defines data types and order of the values carried by the exception.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/index.md
> +If the tag was used to throw an exception that propagated to JavaScript we could use the tag to inspect its values.
```suggestion
If the tag was used to throw an exception that propagated to JavaScript, we could use the tag to inspect its values.
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/tag/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/type/index.md
> +This is the same as the `type` object that was originally passed into the [`Tag()` constructor](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Tag/Tag)
```suggestion
This is the same as the `type` object that was originally passed into the [`Tag()` constructor](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Tag/Tag).
```

2022-04-27 15:16 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/webassembly/tag/type/index.md
> +- [WebAssembly](/en-US/docs/WebAssembly) overview page
```suggestion
- [WebAssembly](/en-US/docs/WebAssembly) overview
```

2022-04-29 03:21 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/exception/index.md
> +  - : An array of one or more data fields comprising the payload the exception.
```suggestion
  - : An array of one or more data fields comprising the payload of the exception.
```

2022-04-29 03:31 UTC, hamishwillee commented
Thanks @dipikabh - much appreciated! I accepted all the comments (though a couple with very minor revisions). 

Did it "make sense"?

2022-04-29 13:32 UTC, dipikabh approved these changes
It looks good, @hamishwillee 👍! Thanks for the fixes

2022-04-29 13:32 UTC, merged

2022-05-02 00:29 UTC, hamishwillee commented
Thanks for the review. I hope we can get eyes on this from the WASM team at some point too.

2022-05-02 21:43 UTC, eqrion reviewed
Hi @hamishwillee, apologies for the delay. I just skimmed through this and added some comments. It looks generally good to me! I'm not a technical writer, so feel free to take what you can from it.

2022-05-02 21:43 UTC, eqrion commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/exception/index.md
> +The `options.traceStack` property can be set true (by default it is `false`) to indicate that WebAssembly code that throws the exception may populate the exception's [`stack`](/en-US/docs/Web/JavaScr
> The `options.traceStack` property can be set true (by default it is `false`) to indicate that WebAssembly code that throws the exception may populate the exception's [`stack`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/stack) property with a stack track.

When the `traceStack` option is true, the resulting WA.Exception returned by this constructor may have the `stack` property set. The WA.Exception does not need to be thrown in order for the `stack` property to be set.

nit: stack track should be stack trace

2022-05-02 21:43 UTC, eqrion commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/getarg/index.md
> +Tags that are neither imported into or exported from the WebAssembly code are internal, and their associated runtime exceptions cannot be queried using this method!
> associated runtime exceptions

'runtime exception' makes me think of WebAssembly.RuntimeError, which is unrelated to WebAssembly.Exception. It might make sense to replace 'runtime exception' with WebAssembly.Exception to be precise here.

2022-05-02 21:43 UTC, eqrion commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +The virtual machine can then attach a stack trace to the exception when it is thrown.
As mentioned earlier, the stack trace is attached when the WA.Exception is constructed, not when it is thrown.

Most exceptions are thrown at the same moment they are constructed so I'm being sort-of pedantic.

2022-05-03 07:34 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/exception/index.md
> +The `options.traceStack` property can be set true (by default it is `false`) to indicate that WebAssembly code that throws the exception may populate the exception's [`stack`](/en-US/docs/Web/JavaScr
Thanks @eqrion 
1. I'll fix the nit. 
2. I understand that the `WA.Exception` _may_ get the stack trace on return from the constructor. My question is what must be shared between the module and the JavaScript for this to happen? Or by example assume I have a JS function that creates  `WA.Exception`. This is imported into a module and called from within the module. 
  My assumption is that (if the option is the exception is set correctly) the stack trace would be added in this case.
  But what if the tag used in this exception was not imported into WASM would the stack trace still be added?
  Hope that makes sense.

2022-05-03 07:43 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/exception/index.md
> +The `options.traceStack` property can be set true (by default it is `false`) to indicate that WebAssembly code that throws the exception may populate the exception's [`stack`](/en-US/docs/Web/JavaScr
PS I changed this to

> The `options.traceStack` property can be set `true` (by default it is `false`) to indicate that a WASM stack trace may be added to the exception's [`stack`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception/stack) property.

2022-05-03 07:46 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/getarg/index.md
> +Tags that are neither imported into or exported from the WebAssembly code are internal, and their associated runtime exceptions cannot be queried using this method!
Yes. I will fix this.

2022-05-03 07:48 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/webassembly/exception/stack/index.md
> +The virtual machine can then attach a stack trace to the exception when it is thrown.
I don't think you are at all :-).

2022-05-03 08:05 UTC, hamishwillee commented
Thanks @eqrion - hope you had a great holiday. I've fixed up these points in #15640

This is exactly the type of review required. The docs are supposed to be a human readable version of the spec, but they still shouldn't ever be factually wrong.

I'm working on a guide as well, but have to catch up on other issues first - so maybe a week or two before I'm back on that. At that point I will integrate your comments from the issue about how runtimes work. 
Essentially though I think it is as I expected - this can be used by individuals, but generally it sounds like someone writing C++ tools will standardize their exceptions.

2022-05-03 11:48 UTC, eqrion commented
> 
> I'm working on a guide as well, but have to catch up on other issues first - so maybe a week or two before I'm back on that. At that point I will integrate your comments from the issue about how runtimes work. Essentially though I think it is as I expected - this can be used by individuals, but generally it sounds like someone writing C++ tools will standardize their exceptions.

Yeah, this feature (like most other wasm features) really are intended to be used by generated code from some toolchain. There's no reason a developer couldn't use this feature directly, but it's very verbose and tedious. If you're interested in a toolchain that uses the feature, I'd take a look at emscripten's wasm exception handling support [1], althought there's not much documentation there.

[1] https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-proposal

2024-06-13 23:23 UTC, hamishwillee commented
Weirdly this just showed up in my feed again. Got all excited, because FYI I created the docs infrastructure for https://emscripten.org/docs/