Adding some improvement and linking for Fetch API page
mdn/content pull request #14923
Opened 2022-04-12 05:39 UTC by benyaminl

Adding some improvement to example of https://developer.mozilla.org/en-US/docs/Web/API/fetch#examples, and linking to other section that has the example. 
Related to https://github.com/mdn/content/issues/14858#issuecomment-1094502686

#### Summary

This change improve the example of the fetch() page, so new comer/veteran that move from XHR to fetch can get glimps of how to use fetch fast without moving between pages. 

#### Motivation

Adding more detail for example, and linking to other resource that MDN already has, so people can easily learn by example and simplify user to find the other document that support the example. 

For some section that I add using headings of the example with long names, to make sure Search Engine easily index fetch() page with common search term, so MDN will end up at top of the list while people using the common search term.(in theory) 

#### Supporting details

None 
#### Related issues

Fixes #14858 
#### Metadata

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-25 12:47 UTC, dipikabh requested changes
Hello @benyaminl, I have reviewed the text for language and readability. A lot of content seems to be similar to whats already there in [Using the Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). You might want to open a separate PR to enhance the explanations on that page instead of adding duplicates here.

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +#### Example fetch Request for FormData or application/x-www-form-urlencoded
```suggestion
### Uploading form data using a fetch() request
```
- You've mentioned the reason for long heading names but the long headings might not work out if have `<h3>` tags in the right-hand TOC in the future
- Adding a title for this example will require to also add headings for the other two examples that were there before these additions.

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +Example, we have a end point API/Form/Script that accept [application/x-www-form-urlencoded](/en-US/docs/Web/HTTP/Methods/POST#example), for contact us, that require us to submit 3 parameter, name, e
I've edited the text for readability and clarity. Is this what you mean?

```suggestion
Consider that we have an endpoint API or a form that accepts [application/x-www-form-urlencoded](/en-US/docs/Web/HTTP/Methods/POST#example) to contact us. It requires us to submit three values: name, email, and a message. We can create the body using [URLSearchParams](/en-US/docs/Web/API/URLSearchParams#examples) to follow [application/x-www-form-urlencoded](/en-US/docs/Web/HTTP/Methods/POST#example) by passing it into the body options on fetch parameter, as shown below:
```
This part is not clear, could you explain or rewrite: "to follow [application/x-www-form-urlencoded](/en-US/docs/Web/HTTP/Methods/POST#example) by passing it into the body options on fetch parameter"

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    method: "POST", // we chane the method to post
```suggestion
    method: "POST", // sends POST request
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    body: new URLSearchParams({ // and this is the body
```suggestion
    body: new URLSearchParams({
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    headers: { // This is so the server know that we send x-www-form-urlencoded, but not required sometimes as nowdays server/API endpoint are smart enough
```suggestion
    headers: { 
```
This type of information should ideally be in the "Syntax" section when explaining the parameters

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +// So we can show it into our HTML, take example we have div#thank-you
```suggestion

```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    // if not will result error
```suggestion

```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +// fetch only throw an error for NETWORKS ERROR but not for HTTP errors such as 4xx or 5xx responses
```suggestion

```
The explanations should ideally be outside the example

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    alert("Oops, something error");
```suggestion
    alert("An error was encountered.");
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +How do we check if our data sent to server correctly? Well we can add check on response, for more, look to [Checking that fetch was successful](/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that
```suggestion
To check if our data was sent to the server correctly, see [Checking that fetch was successful](/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful)
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +#### Example fetch Request for JSON or application/json and Uploading files
This example is similar to what is already in the [Uploading JSON data](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data) section and is not adding more value. I think we should omit this example here to avoid duplicates and to avoid maintenance in two places.
You could consider opening a separate PR in case you want to improve the example in the [Uploading JSON data](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data) section.

```suggestion
### Uploading JSON data using a fetch() request
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +For JSON, we only need to change the body to JSON and headers options to set content type to JSON, eg :
```suggestion
For uploading JSON data, we only need to change the body to JSON and set the `headers` content type to `application/json`.
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +// this is just example url
```suggestion

```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    method: "POST", // we chane the method to post
```suggestion
    method: "POST", 
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    body: JSON.stringify({ // and this is the body as JSON
```suggestion
    body: JSON.stringify({
```

2022-04-25 12:47 UTC, dipikabh commented on files/en-us/web/api/fetch/index.md
> +    headers: { // This is so the server know that we send application/json, but not required sometimes as nowdays server/API endpoint are smart enough
```suggestion
    headers: {  
```

2022-07-12 06:56 UTC, sideshowbarker commented
@benyaminl This PR is waiting on your responses to review comments.

2022-08-08 16:51 UTC, dipikabh commented
Hello @benyaminl, we’re closing this PR because of the inactivity and action/response on the feedback. Let us know if you are still interested in working on it. We appreciate your understanding.

2022-08-08 16:51 UTC, closed without merging