Fix links devtools 2
mdn/content pull request #14966
Opened 2022-04-13 14:15 UTC by teoli2003

This is a second part after mdn/content#14927.

This fixes all remaining /en-US/Tools/... links that don't have a fragment (#xyz-djdjd)

2022-04-13 16:19 UTC, dipikabh requested changes
Hi @teoli2003, this is a partial review. I'll go through the remaining files in the next batch.

2022-04-13 16:19 UTC, dipikabh commented on files/en-us/learn/html/howto/author_fast-loading_html_pages/index.md
> +- [Paint Flashing Tool](https://firefox-source-docs.mozilla.org/devtools-user/paint_flashing_tool/index.html)
This gives a 404 Not Found error and I dont see any results for Paint Flashing Tool in Firefox docs

2022-04-13 16:19 UTC, dipikabh commented on files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.md
> +In Firefox: Open the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about:debugging/index.html) page, click the This Firefox option, click the Load Temporary Add-on button, t
```suggestion
In Firefox: Open the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html) page, click the This Firefox option, click the Load Temporary Add-on button, then select any file in your extension's directory.
```

2022-04-13 16:19 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/11/index.md
> +  - : Provides a convenient, easy-to-use source code editor that you can use in your add-ons. This is the same editor used by [Scratchpad](https://firefox-source-docs.mozilla.org/devtools-user/scratc
404 Not Found error on that link

2022-04-13 16:19 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/13/index.md
> +- The [Scratchpad](https://firefox-source-docs.mozilla.org/devtools-user/scratchpad/index.html) now has an option in the Help menu to take you to the MDN documentation about Scratchpad.
This too might need to be updated/removed

2022-04-13 16:19 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/39/index.md
> +- [WebIDE now supports Cordova projects](https://firefox-source-docs.mozilla.org/devtools-user/webide/working_with_cordova_apps_in_webide/index.html)
404 error on that link

2022-04-13 16:28 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/31/index.md
>  - [%c formatting to style console messages](/en-US/docs/Tools/Web_Console#styling_messages)
I have not dealt with links that have a # yet. It will be in the next (and likely last) PR.

2022-04-13 18:08 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/31/index.md
>  - [%c formatting to style console messages](/en-US/docs/Tools/Web_Console#styling_messages)
Yeah, sorry, you did mention it in your PR description.

2022-04-13 18:39 UTC, dipikabh requested changes
This is for the remaining files. Similar issues as in the previous batch.

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/41/index.md
> +- [Added command to GCLI to display CSP info](https://firefox-source-docs.mozilla.org/devtools-user/gcli/display_security_information/index.html)
The GCLI link leads to a 404..

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/47/index.md
> +  - [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about:debugging/index.html) dashboard for workers
```suggestion
  - [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html) dashboard for workers
```

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/6/index.md
> +- The new [Scratchpad](https://firefox-source-docs.mozilla.org/devtools-user/scratchpad/index.html) tool provides a handy place to experiment with JavaScript code.
404

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/62/index.md
> +- The [Developer Toolbar/GCLI](https://firefox-source-docs.mozilla.org/devtools-user/gcli/index.html) (accessed with `Shift` + `F2`), **has been removed** from Firefox ({{bug(1461970)}}). Both the De
404

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/68/index.md
> +- The preference that controls the visibility of internal extensions (system add-ons and hidden extensions) on the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about:debugg
```suggestion
- The preference that controls the visibility of internal extensions (system add-ons and hidden extensions) on the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html) page has been changed from `devtools.aboutdebugging.showSystemAddons` to `devtools.aboutdebugging.showHiddenAddons` ({{bug(1544372)}}).
```

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/68/index.md
> +- The "Enable add-on debugging" checkbox has been removed from the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about:debugging/index.html) page ({{bug(1544813)}}).
```suggestion
- The "Enable add-on debugging" checkbox has been removed from the [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html) page ({{bug(1544813)}}).
```

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/69/index.md
> +- For our mobile web developers, we have migrated remote debugging from the old WebIDE into a re-designed [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about:debugging/index
```suggestion
- For our mobile web developers, we have migrated remote debugging from the old WebIDE into a re-designed [about:debugging](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html), making the experience of debugging [GeckoView](https://hacks.mozilla.org/2019/06/geckoview-in-2019/) on remote devices via USB much better ({{bug(1462208)}}).
```

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/72/index.md
> +- The [Scratchpad](https://firefox-source-docs.mozilla.org/devtools-user/scratchpad/index.html) feature has been removed ({{bug(1519103)}}).
404

2022-04-13 18:39 UTC, dipikabh commented on files/en-us/web/api/service_worker_api/using_service_workers/index.md
> +- You can navigate to [`about:debugging`](https://firefox-source-docs.mozilla.org/devtools-user/about:debugging/index.html) to see what SWs are registered and update/remove them.
```suggestion
- You can navigate to [`about:debugging`](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html) to see what SWs are registered and update/remove them.
```

2022-04-14 04:43 UTC, teoli2003 commented
Thanks for the thorough review. I'm dealing with the comment in 3 phases:
1. Erroneous links (mostly the `\_colon\_` instead of `:` in url (and one url with fragment): I committed the proposal.
2. 404 in Firefox/releases: these are tools that don't exist anymore: I will remove the link but keep the sentence.
3. 404 outside Firefox/releases: I will like to remove the entry/sentence as these tools are no more an option.

Point 1 is already committed, points 2 and 3 will have their own commit. I will re-request a review once this  is done.

2022-04-14 05:22 UTC, teoli2003 commented on files/en-us/learn/css/howto/css_faq/index.md
> +Style rules that are syntactically correct may not apply in certain situations. You can use [DOM Inspector](https://firefox-source-docs.mozilla.org/devtools-user/add-ons/dom_inspector/index.html)'s _
The DOM Inspector has been removed, transformed as an add-on, then dropped. A style pane has been created elsewhere. Let's link to this one.

```suggestion
Style rules that are syntactically correct may not apply in certain situations. You can use [Rules view](https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_css/index.html) of  _CSS Pane_ of the Inspector to debug problems of this kind, but the most frequent instances of ignored style rules are listed below.
```

2022-04-14 05:25 UTC, teoli2003 commented
I think I have resolved all cases (besides the # ones that are for another PR). Re-requesting review.

2022-04-14 08:35 UTC, dipikabh approved these changes
I think it all looks good now. Thanks for taking up these updates!!

2022-04-14 08:35 UTC, merged