Update index.md
mdn/content pull request #15032
Opened 2022-04-15 19:11 UTC by sgadiyar06

Updated the current LTS and latest version of Node.js

#### Summary

Updating the LTS version and the latest version of Node

#### Motivation

Keeping it up to date

#### Supporting details

Current LTS and latest version are obtained from the node [website](https://nodejs.org/en/)

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-04-15 20:10 UTC, teoli2003 requested changes
I think that such a sentence is unmaintainable. We should rephrase this paragraph to be date-independent. Mentioning ever-moving version number is not really useful, and almost always wrong.

2022-04-17 13:53 UTC, sgadiyar06 commented
Is it better to remove the version numbers altogether in this case?

2022-04-17 18:03 UTC, teoli2003 requested changes

2022-04-17 18:03 UTC, teoli2003 commented on files/en-us/learn/server-side/express_nodejs/introduction/index.md
> +Node was initially released, for Linux only, in 2009. The NPM package manager was released in 2010, and native Windows support was added in 2012. At time of writing the current LTS release is Node v1
I think this is better.

```suggestion
Node was initially released, for Linux only, in 2009. The NPM package manager was released in 2010, and native Windows support was added in 2012. Delve into [Wikipedia](https://en.wikipedia.org/wiki/Node.js#History) if you want to know more.
```

2022-04-17 18:16 UTC, teoli2003 approved these changes
👍

2022-04-17 18:18 UTC, merged

2022-04-17 18:18 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: