Fixing external link anchor to specification
mdn/content pull request #15055
Opened 2022-04-16 19:15 UTC by simonvarey

#### Summary
I fixed the anchor on the link to the CSS2 specification on https://developer.mozilla.org/en-US/docs/Web/CSS/frequency to `#frequencies`.

#### Motivation
The link to the CSS2 specification links to the anchor `#q19.0` which does not exist. 

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-04-16 19:21 UTC, teoli2003 requested changes

2022-04-16 19:21 UTC, teoli2003 commented on files/en-us/web/css/frequency/index.md
> +> **Note:** This data type was initially introduced in [CSS Level 2](https://www.w3.org/TR/CSS2/aural.html#frequencies) for the now-obsolete [aural](/en-US/docs/Web/CSS/@media/aural) [media type](/en
Thanks! This comment doesn't bring anything; we should remove the whole note.
```suggestion
```

2022-04-17 04:06 UTC, wbamberg approved these changes, later dismissed
👍 thank you for the fix, @simonvarey !

2022-04-18 14:08 UTC, simonvarey commented
@teoli2003 Would it be worth adding a note just that no CSS property is using this property at the moment? Someone stumbling across this page might wonder what the property is for.

2022-04-18 14:15 UTC, teoli2003 approved these changes

2022-04-18 14:16 UTC, teoli2003 approved these changes

2022-04-18 14:17 UTC, teoli2003 commented
> @teoli2003 Would it be worth adding a note just that no CSS property is using this property at the moment? Someone stumbling across this page might wonder what the property is for.

It isn't necessary, the browser compat section is clear about it.

2022-04-18 14:17 UTC, merged