Client-side_javascript_frameworks: fixed typos
mdn/content pull request #15064
Opened 2022-04-17 03:04 UTC by OnkarRuikar

## Summary
Fixed typos. Rephrased statements to correct the meaning or to simplify them.

#### Metadata
- [x] Fixes a typo, bug, or other error

2022-04-19 21:06 UTC, dipikabh requested changes
The changes look good, @OnkarRuikar! Just a comma needs to be dropped.

2022-04-19 21:06 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +Thanks to Vue, we didn't have to write our own functions for building the UI; the framework will handle that for us in an optimized, efficient way. Our only role here was to describe to Vue what each
```suggestion
Thanks to Vue, we didn't have to write our own functions for building the UI; the framework will handle that for us in an optimized, efficient way. Our only role here was to describe to Vue what each item should look like. Developers who are familiar with Vue can quickly work out what is going on when they join our project. Vue is not alone in this: using a framework improves team as well as individual efficiency.
```

2022-04-20 02:29 UTC, OnkarRuikar commented
@dipikabh done!

2022-04-20 12:28 UTC, dipikabh approved these changes

2022-04-20 12:29 UTC, merged

2022-04-20 12:29 UTC, dipikabh commented
Thank you! 👍