WebAPI: Update Method pages to modern structure (part 9)
mdn/content pull request #15062
Opened 2022-04-17 02:51 UTC by OnkarRuikar

Continuing #14857 

## Summary
Updating the method pages to follow the current templates:
https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections#constructors_and_methods
https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_method_subpage_template

Changes Include:
- fix syntax section
- changing section titles to suggested titles in the template
- change `{{DOMxRef("DOMString")}}` to `string`
- remove extra spaces in between words and extra trailing spaces
- other small corrections

### Metadata
- [x] Fixes a typo, bug, or other error

2022-04-17 04:04 UTC, wbamberg reviewed
Awesome work @OnkarRuikar . I had one question about some weirdness in the `DataTransfer` API.

2022-04-17 04:04 UTC, wbamberg commented on files/en-us/web/api/datatransfer/setdragimage/index.md
> +- _imgElement
```suggestion
- `imgElement`
```

Not sure it's in scope for this PR, but several of the methods in this API have this pattern. Also, it should be "Parameters" not "Arguments" - but again perhaps that's in in scope for this PR.

2022-04-17 04:26 UTC, OnkarRuikar commented on files/en-us/web/api/datatransfer/setdragimage/index.md
> +- _imgElement
fixed in the commit

2022-04-17 04:53 UTC, OnkarRuikar commented
@wbamberg  As per the syntax section the parameter names do not have any decoration so `_imgElement_` and `` `imgElement` `` are both invalid. A CSS rule takes care of making param names bold. So, I think there is no need for us to do it in markdown.
```css
.main-page-content dl dt {
  margin-top: 2rem;
  margin-bottom: .5rem;
  font-weight: var(--font-body-strong-weight);
}
```

Good catch on `Arguments`. It'll be handled in upcoming PRs.

I can include removing decorations from parameter names in the PR series. But if we add too many things, the reviews and overall process will become slow. And there are ~2300 method pages. 😯 If we focus on one type of correction in a PR series then hundreds of files can be pulled in a PR. I don't know how is the workload on your side. I leave the decision of dealing everything in a single pass or separate things over multiple passes.

Honestly, for every API authors have used their own imagination writing syntax sections. I have discussed the bottleneck on my side with Jean here: https://github.com/mdn/content/pull/15042#issuecomment-1100585638

2022-04-18 05:56 UTC, teoli2003 requested changes

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/console/trace/index.md
> +trace(objct1, /* ..., */ objectN)
```suggestion
trace(object1, /* ..., */ objectN)
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/cookiestore/set/index.md
> +set(name,value)
```suggestion
set(name, value)
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/credentialscontainer/store/index.md
> +store(Credential)
```suggestion
store(Credentials)
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/mozcleardataat/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/mozgetdataat/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/mozsetdataat/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/moztypesat/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/getdata/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/addelement/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:56 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/setdata/index.md
>  ### Arguments
```suggestion
### Parameters
```

2022-04-18 05:58 UTC, teoli2003 commented on files/en-us/web/api/datatransfer/setdragimage/index.md
> +- _imgElement
It is ok to fix some of them here, but that's likely out-of-scope. We have plenty of these incoherences, and we should probably do another pass in the future.

2022-04-18 06:20 UTC, teoli2003 approved these changes
Thanks!

2022-04-18 06:20 UTC, merged

2022-04-18 19:30 UTC, wbamberg commented
> @wbamberg As per the syntax section the parameter names do not have any decoration so `_imgElement_` and `` `imgElement` `` are both invalid. A CSS rule takes care of making param names bold. So, I think there is no need for us to do it in markdown.

This seems to be another discrepancy with the JS docs, where code format for parameter names seems to be the most common approach (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters etc etc).

> 
> I can include removing decorations from parameter names in the PR series. But if we add too many things, the reviews and overall process will become slow. And there are ~2300 method pages. 😯 If we focus on one type of correction in a PR series then hundreds of files can be pulled in a PR. I don't know how is the workload on your side. I leave the decision of dealing everything in a single pass or separate things over multiple passes.
> 

I'm happy with an answer like "this isn't in scope for this PR". There are so many things to fix, we can't try to do them all at once, and what you have here is already a big improvement.

2022-04-19 03:39 UTC, OnkarRuikar commented
> I'm happy with an answer like "this isn't in scope for this PR". There are so many things to fix, we can't try to do them all at once

Let's handle fixing `### Parameters` section in next PR series. 

@wbamberg, @teoli2003 If you have such mass corrections in mind do let me know. For example, updating page tags, as per BCD, with 'deprecated', 'experimental', 'non-standard'. Currently, BCD and page tags are not in sync. I don't know how they are updated.

2022-04-19 04:18 UTC, wbamberg commented
> > I'm happy with an answer like "this isn't in scope for this PR". There are so many things to fix, we can't try to do them all at once
> 
> Let's handle fixing `### Parameters` section in next PR series.
> 
> For example, updating page tags, as per BCD, with 'deprecated', 'experimental', 'non-standard'. Currently, BCD and page tags are not in sync. I don't know how they are updated.

What I would much prefer to do here is to deprecate and eventually remove these tags in favour of the BCD values, and have the platform generate banners for these pages from that data: https://github.com/openwebdocs/project/issues/81. It's silly to duplicate the data.

2022-04-19 04:20 UTC, wbamberg commented
> If you have such mass corrections in mind do let me know.

I'm currently supposed to be working on a project to define "page type" front matter (https://github.com/openwebdocs/project/issues/91) and once we have these types defined there will be work to add them to add the pages they apply to (and also to remove tags that are currently used ti do a similar job).