refactor: keep tags lowercase
mdn/content pull request #15116
Opened 2022-04-19 07:52 UTC by abdirahmanjama

What? 
- Update content to highlight the typical convention of keeping tags lowercase. 

Why?

#### Summary

Update content to highlight the typical convention of keeping tags lowercase. 
 
This document introduces the concept of tags, it highlights the fact that devs can use both lowercase and uppercase due to the non-case sensitive nature of tags. But what approach should developers take? What are the best practices?

This is what this PR addresses. Lowercase tags are a convention. It is part of the current best practices in accordance with HTML5. 

#### Motivation

Make readers aware of best practices from the get-go. 
Enable them to inhibit this habit early on in their learning journey.

#### Supporting details

https://blog.tbhcreative.com/2015/08/10-best-practices-in-html.html#:~:text=9.,easier%20to%20read%20and%20maintain.

https://www.thoughtco.com/html5-tags-case-sensitive-3467997#:~:text=Lowercase%20Is%20an%20HTML5%20Convention,practices%20to%20HTML5%20and%20beyond.

#### Related issues

#### Metadata

- [ ] Rewrites a document slightly.
- [ ]

2022-04-19 20:55 UTC, dipikabh commented on files/en-us/web/html/index.md
> +An HTML element is set off from other text in a document by "tags", which consist of the element name surrounded by "`<`" and "`>`".  The name of an element inside a tag is case insensitive. That is,
```suggestion
However, the convention and recommended practice is to write tags in lowercase.
```
I would suggest to rewrite the sentence slightly plus to add a period at the end.

2022-04-19 20:59 UTC, dipikabh requested changes
Hello @abdirahmanjama, thanks for your first contribution here. That is indeed a good piece of info to add! I've pointed out a minor change.

2022-04-19 20:59 UTC, dipikabh commented on files/en-us/web/html/index.md
> +An HTML element is set off from other text in a document by "tags", which consist of the element name surrounded by "`<`" and "`>`".  The name of an element inside a tag is case insensitive. That is,
```suggestion
An HTML element is set off from other text in a document by "tags", which consist of the element name surrounded by "`<`" and "`>`".  The name of an element inside a tag is case insensitive. That is, it can be written in uppercase, lowercase, or a mixture. For example, the `<title>` tag can be written as `<Title>`, `<TITLE>`, or in any other way. However, the convention and recommended practice is to write tags in lowercase.
```
I would suggest to rewrite the sentence slightly (plus add a period at the end).

2022-04-20 00:02 UTC, estelle approved these changes

2022-04-20 12:22 UTC, dipikabh approved these changes

2022-04-20 12:22 UTC, merged

2022-04-20 12:23 UTC, dipikabh commented
Congratulations on landing your first PR, @abdirahmanjama! 🎉

2022-04-20 13:15 UTC, abdirahmanjama commented
Thank you! I look forward to working together more 🙌🚀