Fixes #15148 - updates article to match react 18
mdn/content pull request #15196
Opened 2022-04-21 13:18 UTC by himanshugarg

#### Summary
Updates article to match code generated on React 18

#### Motivation
| I want to publicly demonstrate my own skills to improve my chances of getting a job.

#### Supporting details
Thanks @OnkarRuikar for reporting

#### Related issues
Fixes #15148

#### Metadata
- [x] Fixes a typo, bug, or other error

2022-04-21 21:32 UTC, dipikabh requested changes
Hello @himanshugarg, thanks for these updates. I've done a quick language check and provided some improvement suggestions.

2022-04-21 21:32 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The first statement imports a logo from `'./logo.svg'`. Note the use of `./` at the beginning of the path, and the `.svg` extension at the end — these tell us that the file is local and that it is no
```suggestion
The first statement imports a logo from `'./logo.svg'`. Note the use of `./` at the beginning of the path and the `.svg` extension at the end — these tell us that the file is local and that it is not a JavaScript file. Indeed, the `logo.svg` file lives in our source directory.
```

2022-04-21 21:32 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
```suggestion
// or send to an analytics endpoint.
// Learn more here: https://bit.ly/CRA-vitals
```

2022-04-21 21:32 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The first two statements import the React and ReactDOM libraries because they are referenced later in the file. We don't write a path or extension when importing the `React` or `ReactDOM` modules — t
```suggestion
The first two statements import the `React` and `ReactDOM` libraries because they are referenced later in the file. We don't write a path or extension when importing these libraries because they are not local files. In fact, they are listed as dependencies in our `package.json` file. Be careful of this distinction as you work through this lesson!
```

2022-04-21 21:32 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +`src/index.css` holds global styles that are applied to our whole app. We can also see our `App` component imported here; it is made available for import thanks to the `export` statement at the botto
```suggestion
`index.css` holds global styles that are applied to our whole app. We can also see our `App` component imported here; it is made available for import thanks to the `export` statement at the bottom of `App.js`.
```

2022-04-21 21:32 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The [reportWebVitals()](https://create-react-app.dev/docs/measuring-performance) function allows you to measure the performance of your web page on the user's device, but it is not in scope for this
```suggestion
The [reportWebVitals()](https://create-react-app.dev/docs/measuring-performance) function allows you to measure the performance of your web page on the user's device; however, explaining that function is outside the scope of this article. You can delete line 5, as well as most of the code below it.
```
Please check that the suggested text conveys the intended meaning.

2022-04-21 22:44 UTC, wbamberg reviewed
The React docs in Learn are [specific about versions](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks#react_tutorials):

> Note: React tutorials last tested in May 2020, with React/ReactDOM 16.13.1 and create-react-app 3.4.1.

That's almost 2 years ago so we should certainly consider a systematic update to the latest version. I don't know if there are other updates than the ones in this PR though. https://github.com/mdn/content/issues/15044 seems like it might be relevant here.

Also, any updates to the pages should consider also updating the underlying example code in https://github.com/mdn/todo-react .

2022-04-22 00:53 UTC, himanshugarg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Many thanks for actually making the suggested changes. This one improves but differs from the auto-generated code. So I am leaving it unchanged. Thanks

2022-04-22 01:01 UTC, himanshugarg commented
Thanks @wbamberg for the review. Will make the remaining changes. But let me know if they don't have to a part of this PR. Thanks

2022-04-22 06:23 UTC, neilgoldman commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
I agree with [himanshugarg](https://github.com/himanshugarg). That comment is not their original content, it is supposed to match verbatim the template generated by create-react-app.

https://github.com/facebook/create-react-app/blob/main/packages/cra-template/template/src/index.js#L16

2022-04-22 06:44 UTC, neilgoldman commented
I'm in favor of this change, I created a similar issue which is linked above by @wbamberg (https://github.com/mdn/content/issues/15044 ). I can help with updating the underlying example code, but won't be able to contribute until tomorrow night or this weekend.

One additional suggestion, can we update[ the text in this part of react_components/index.md](https://github.com/mdn/content/blob/7e8dc5f669756403b9d0735fabaeae72e57fa6cb/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md?plain=1#L248)  as well?

From

> Next, we'll pass `DATA` to `<App />` as a prop, called `tasks`. The final line of `src/index.js` should read like this:
> 
> ```js
> ReactDOM.render(<App tasks={DATA} />, document.getElementById("root"));
> ```

To something like this?

> Next, we'll pass `DATA` to `<App />` as a prop, called `tasks`. Your `root.render` in `src/index.js` should read like this:
> 
> ```js
> root.render(
>   <React.StrictMode>
>     <App  tasks={DATA} />
>   </React.StrictMode>
> );

Sorry don't know how to do the suggest-changes feature on a file not included in this PR

2022-04-22 07:22 UTC, OnkarRuikar commented
A small suggestion. 
In `## In this module` sections, it would be great if we convert link to current document to just bold text:
```
[Getting started with React](/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started)

To

**Getting started with React**
```
Like it's been done here:
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#in_this_module

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line#in_this_module

Providing link to the same document makes no sense.

2022-04-22 19:29 UTC, wbamberg commented
> A small suggestion. In `## In this module` sections, it would be great if we convert link to current document to just bold text:
> 
> ```
> [Getting started with React](/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_getting_started)
> 
> To
> 
> **Getting started with React**
> ```
> 
> Like it's been done here: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#in_this_module
> 
> https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line#in_this_module
> 
> Providing link to the same document makes no sense.

According to @hamishwillee , even though the self-link gives you a flaw, this is a flaw in the flaw-checker, and we should in fact have the self-link but have the MDN platform code suppress it actually being a link when it builds the pages (IIRC). I can see the point of this, because it means we can just copy-paste the same blob of links into every article, it's a real pain having to make each one different. (of course in a sensible world we would generate the whole list of links for pages like this, but we don't inhabit a sensible world yet.)

For the sake of this PR I don't mind either way :).

2022-04-25 00:31 UTC, hamishwillee commented
> For the sake of this PR I don't mind either way :).

Me either. It would be nice if the flaw checker could be fixed.

2022-09-02 10:56 UTC, schalkneethling commented
Hey @himanshugarg, apologies for letting this one sit so long. As a first step to getting this ready to land, please have at the conflict mentioned in `files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md` - Thanks!

2022-09-06 08:48 UTC, himanshugarg commented
Hello @schalkneethling, thanks for your time on this. I have fixed the conflicts. There are other pages that might need syncing for React 18 which is what probably delayed this PR. Would it work if I took up those in another PR? Thanks

2022-09-08 20:15 UTC, schalkneethling commented
> Hello @schalkneethling, thanks for your time on this. I have fixed the conflicts. There are [other pages that might need syncing](https://github.com/mdn/content/pull/15196#pullrequestreview-949283728) for React 18. Would it work if I took up those in another PR? Thanks

Hey there! My apologies for being slow to respond. I will get back to you as soon as possible.

2022-09-13 22:12 UTC, schalkneethling reviewed
@himanshugarg just a couple of minor notes. Thanks so much.

2022-09-13 22:12 UTC, schalkneethling commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Line 7 calls React's `ReactDOM.createRoot()` function with the DOM element inside which we want the component to be rendered, in this case the element with an ID of `root`. If you look inside `public
I quite like how the [latest beta docs for React](https://beta.reactjs.org/apis/react-dom/client/createRoot#create-root) explain what `createRoot` does and returns:

> React will create a root for the `domNode`, and take over managing the DOM inside it.

2022-09-13 23:02 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> -The second statement imports a logo from `'./logo.svg'`. Note the use of `./` at the beginning of the path, and the `.svg` extension at the end — these tell us that the file is local and that it is n
@schalkneethling The new React transform has been backported to older React versions as well.

2022-09-27 14:04 UTC, himanshugarg commented
Reopening after automatic close due to fork sync.

2022-10-05 12:08 UTC, dipikabh approved these changes
Thanks, @himanshugarg for your work and patience on this 🙏 👍 !
Looks like there are no outstanding issues or comments as of now, so let's land this. If there's anything unresolved, let's take up those comments in a new PR.

2022-10-05 12:08 UTC, merged