Add syntax and description to @layer
mdn/content pull request #15215
Opened 2022-04-21 22:50 UTC by dipikabh

#### Summary

- As a follow up after updating the @import page in https://github.com/mdn/content/pull/15205, this PR updates the @layer page to add "Syntax" and Description" sections for consistency.
- Also reorganised the content for better content flow.

This PR…
-->
- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-22 20:25 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Rules within a cascade layer cascade together, giving more control over the cascade to web developers. Any styles not in a layer are gathered together and placed into an anonymous layer that comes af
```suggestion
Rules within a cascade layer cascade together, giving more control over the cascade to web developers. Any styles not in a layer are gathered together and placed into an anonymous layer that comes after all the declared layers. This means that any styles declared outside of a layer will override styles declared in a layer, regardless of specificity.
```

2022-04-22 20:29 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Another way to create a cascade layer is by using {{cssxref("@import")}}. In this case, the rules would be in the imported stylesheet.
should we remind readers that imports have to come first in a stylesheet?

2022-04-23 01:42 UTC, estelle reviewed
just a couple of questions

2022-04-25 13:26 UTC, dipikabh commented
> just a couple of questions

Thanks for the review, @estelle. I have addressed the comments.

2022-04-28 01:09 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +@import url layer( layer-name );
Should the @import be in the @layer page?
And, if it is, should it come first as @import is supposed to come before, or precede, any other styles.

2022-04-28 02:00 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Rules within a cascade layer cascade together, giving more control over the cascade to web developers. Any styles not in a layer are gathered together and placed into an anonymous layer that comes af
```suggestion
Rules within a cascade layer cascade together, giving more control over the cascade to web developers. Any styles not in a layer are gathered together and placed into a single anonymous layer that comes after all the declared layers, named and anonymous. This means that any styles declared outside of a layer will override styles declared in a layer, regardless of specificity.
```

2022-04-28 02:00 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Rules within a cascade layer cascade together, giving more control over the cascade to web developers. Any styles not in a layer are gathered together and placed into an anonymous layer that comes af
want to make sure people understand there can be multiple anonymous layers.

2022-04-28 02:02 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Or multiple layers can be defined at once, as shown below:
```suggestion
Multiple layers can be defined at once, as shown below:
```

2022-04-28 02:08 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +This creates an _anonymous cascade layer_. This layer functions in the same way as named layers; however, rules cannot be assigned to it later.
```suggestion
This creates an _anonymous cascade layer_. This layer functions in the same way as named layers; however, rules cannot be assigned to it later. The order of precedence for anonymous layers is the order in which layers are declared, named or not, and lower than styles declared outside of a layer.
```

2022-04-28 02:08 UTC, estelle commented on files/en-us/web/css/@layer/index.md
> +Another way to create a cascade layer is by using {{cssxref("@import")}}. In this case, the rules would be in the imported stylesheet. Remember that the `@import` at-rule must precede all other types
I think it's enough to keep this and remove import from the syntax box at the start of this document.

2022-04-28 02:10 UTC, estelle requested changes
Looks good. let's get rid of the @import in the ## Syntax.

2022-05-02 10:18 UTC, dipikabh commented on files/en-us/web/css/@layer/index.md
> +@import url layer( layer-name );
Removed @import from the Syntax

2022-05-02 10:30 UTC, dipikabh commented
> Looks good. let's get rid of the @import in the ## Syntax.

Thanks @estelle. I've incorporated the suggested changes.

2022-05-07 01:19 UTC, estelle approved these changes

2022-05-07 01:19 UTC, merged