Update redirected URLs from `https` -> `http` (part 18)
mdn/content pull request #15267
Opened 2022-04-23 02:16 UTC by OnkarRuikar

Extending #14055

## Summary

Updated redirected URLs. Redirecting from `https` to `http`.

#### Metadata
- [x] Fixes a typo, bug, or other error

2022-04-23 05:55 UTC, teoli2003 requested changes
So this one is trickier:
- We prefer not to have redirects
- But we don't like http links. 
So we want to have https links that doesn't redirect.
In case there aren't any, we prefer having an https link that redirect to an http link because, when they will fix their website to support https correctly, the link will be automatically fixed while the http one will not.

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +5. [Separating Axis Theorem](http://programmerart.weebly.com/separating-axis-theorem.html)
HTTP links are a hazard. Let's keep the HTTPS one. At some point the site will be updated.
```suggestion
5. [Separating Axis Theorem](https://programmerart.weebly.com/separating-axis-theorem.html)
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/games/tutorials/2d_breakout_game_phaser/randomizing_gameplay/index.md
> +Be sure to check the ever growing list of [examples](http://phaser.io/examples) and the [official documentation](https://phaser.io/docs/), and visit the [HTML5 Gamedevs forums](https://www.html5gamed
```suggestion
Be sure to check the ever-growing list of [examples](https://phaser.io/examples) and the [official documentation](https://phaser.io/docs/), and visit the [HTML5 Gamedevs forums](https://www.html5gamedevs.com/forum/14-phaser/) if you ever need any help.
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> +[Phaser](https://phaser.io/) is a framework for building desktop and mobile HTML5 games. It's quite new, but growing rapidly thanks to the passionate community involved in the development process. Yo
```suggestion
[Phaser](https://phaser.io/) is a framework for building desktop and mobile HTML5 games. It's quite new, but growing rapidly thanks to the passionate community involved in the development process. You can check it out [on GitHub](https://github.com/photonstorm/phaser) where it's open sourced, read the [online documentation](https://phaser.io/docs/) and go through the big collection of [examples](https://phaser.io/examples). The Phaser framework provides you with a set of tools that will speed up development and help handle generic tasks needed to complete the game, so you can focus on the game idea itself.
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/mdn/guidelines/video/index.md
> +  [They scan](http://sensible.com/dont-make-me-think/).
The link seems to be a commercial one. Let's just remove it.
```suggestion
  _They scan._
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/1.5/what_s_new_in_1.5_alpha/index.md
> +This page is based largely on [http://www.squarefree.com/burningedg...eases/1.1.html](http://www.squarefree.com/burningedge/releases/) (thanks Jesse).
```suggestion
This page is based largely on [https://www.squarefree.com/burningedg...eases/](https://www.squarefree.com/burningedge/releases/) (thanks Jesse).
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/web/accessibility/understanding_colors_and_luminance/index.md
> +Today, the proliferation of easily available web fonts of all sizes and weights has complicated the issue. The emerging WCAG 3.0 standard on visual contrast is known as the [Advanced Perceptual Contr
```suggestion
Today, the proliferation of easily available web fonts of all sizes and weights has complicated the issue. The emerging WCAG 3.0 standard on visual contrast is known as the [Advanced Perceptual Contrast Algorithm (APCA)](https://www.myndex.com/APCA/), and takes into account font weights and sizes in a variable manner, relative to the predicted contrast value.
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/web/guide/audio_and_video_delivery/cross-browser_audio_basics/index.md
> +- [Media Event Inspector](http://jplayer.org/HTML5.Media.Event.Inspector/)
```suggestion
- [Media Event Inspector](https://jplayer.org/HTML5.Media.Event.Inspector/)
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/web/http/configuring_servers_for_ogg_media/index.md
> +By default, [`ffmpeg2theora`](http://v2v.cc/~j/ffmpeg2theora/) uses one key frame every 64 frames (or about every 2 seconds at 30 frames per second), which works pretty well.
```suggestion
By default, [`ffmpeg2theora`](https://v2v.cc/~j/ffmpeg2theora/) uses one key frame every 64 frames (or about every 2 seconds at 30 frames per second), which works pretty well.
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/web/http/link_prefetching_faq/index.md
> +Browsers based on Mozilla 1.2 (or later) as well as browsers based on Mozilla 1.0.2 (or later) support prefetching. This includes Firefox and Netscape 7.01+. Camino builds as of March 2003 are based
```suggestion
Browsers based on Mozilla 1.2 (or later), as well as browsers based on Mozilla 1.0.2 (or later), support prefetching. This includes Firefox and Netscape 7.01+. Camino builds as of March 2003 are based on Mozilla 1.0.1, and therefore do not support prefetching. [Test](https://browserspy.dk/prefetch.php) your browser to see if it supports Link Prefetching.
```

2022-04-23 05:55 UTC, teoli2003 commented on files/en-us/web/svg/index.md
> +- [SVG art gallery](http://www1.plurib.us/svg_gallery/)
```suggestion
- [SVG art gallery](https://www1.plurib.us/svg_gallery/)
```

2022-04-23 06:09 UTC, OnkarRuikar commented
>   In case there aren't any, we prefer having an https link that redirect to an http link because, when they will fix their website to support https correctly, the link will be automatically fixed while the http one will not.

I see. Mostly they go from `https` to `http` because they don't want to pay for the certificate anymore. This way when they renew the certificate the URL will stop redirecting.

Counter argument can be made that, taking users from `https` to `http` on same domain is considered deceptive. It'll look bad for those domains.

2022-04-23 06:14 UTC, teoli2003 commented
> I see. Mostly they go from `https` to `http` because they don't want to pay for the certificate anymore. This way when they renew the certificate the URL will stop redirecting.

There are free certificates nowadays. (See https://letsencrypt.org/ )

2022-04-23 06:14 UTC, teoli2003 approved these changes
Approving, but waiting for Eric's review before merging.

2022-04-24 05:46 UTC, teoli2003 commented
I'm changing strategy here: I will merge this to prevent the rotting of the bug. If Eric finds any problem, we'll fix it in a follow-up.

2022-04-24 05:46 UTC, merged