fix: various typos
mdn/content pull request #15260
Opened 2022-04-22 19:16 UTC by nschonni

2022-04-22 19:24 UTC, nschonni commented on files/en-us/web/api/rtcrtpstreamstats/trackid/index.md
>  > **Note:** This value is _not_ the same as the value of
I'm thinking this file might be misnamed, since it appears to be `mediaTrackId` in BCD https://github.com/mdn/browser-compat-data/blob/0329680ac91974c0aaa6779b59b5d846612f19ae/api/RTCRtpStreamStats.json#L263

2022-04-23 02:59 UTC, OnkarRuikar commented on files/en-us/web/api/rtcrtpstreamstats/trackid/index.md
>  > **Note:** This value is _not_ the same as the value of
In specifications they've renamed it to `id` [[ref](https://w3c.github.io/webrtc-stats/#obsolete-rtcmediastreamstats-members)]. Sub class `RTCInboundRtpStreamStats` had `trackID` and it is also obsolete [[ref](https://www.w3.org/TR/webrtc-stats/#obsolete-rtcinboundrtpstreamstats-members)]. The API pages need update.

2022-04-23 02:59 UTC, OnkarRuikar commented on files/en-us/web/api/securitypolicyviolationevent/statuscode/index.md
> +  - Status code
```suggestion
  - statusCode
```

2022-04-23 04:56 UTC, teoli2003 requested changes
A few minor changes, but this is almost good to go.

2022-04-23 04:56 UTC, teoli2003 commented on files/en-us/games/publishing_games/game_promotion/index.md
> +If you want to learn more about the etiquette of contacting the press you should definitely check out [How To Contact Press](https://app.box.com/s/p0ft5zdolpi0ydkrykab) - a great guide from Pixel Pro
The link is gone.
```suggestion
If you want to learn more about the etiquette of contacting the press you should definitely check out [How To Contact Press](https://app.box.com/s/p0ft5zdolpi0ydkrykab) - a great guide from Pixel Prospector.
```

2022-04-23 04:56 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/27/index.md
> +- The {{htmlattrxref("typeMustMatch", "object")}} attribute on the {{HTMLElement("object")}} element is now supported ({{bug(827160)}}).
```suggestion
- The {{domxref("Object.typeMustMatch", "typeMustMatch")}} property of the {{HTMLElement("object")}} element is now supported ({{bug(827160)}}).
```

2022-04-23 04:56 UTC, teoli2003 commented on files/en-us/web/api/request/cache/index.md
> +    ({status: 504}) : // Workaround for chrome; which fails with a type error
```suggestion
    ({status: 504}) : // Workaround for chrome; which fails with a TypeError
```

2022-04-23 04:56 UTC, teoli2003 commented on files/en-us/web/api/rtcrtpstreamstats/trackid/index.md
>  > **Note:** This value is _not_ the same as the value of
The page is outdated. But as we remove dictionary-related pages, this one will be deleted. There is no need to update it here.

2022-04-24 06:11 UTC, teoli2003 approved these changes
👍

2022-04-24 06:12 UTC, merged