Document loopback redirect URL in identity API
mdn/content pull request #1530
Opened 2021-01-20 15:21 UTC by Rob--W

https://bugzilla.mozilla.org/show_bug.cgi?id=1635344

2021-01-20 15:21 UTC, Rob--W commented
I wanted to add @mixedpuppy as a reviewer but am somehow not able to.

2021-01-20 15:29 UTC, chrisdavidmills commented
> I wanted to add @mixedpuppy as a reviewer but am somehow not able to.

I think this is because Shane hasn't accepted the invitation to this repo's collaborators list. It is still listed as "pending". I can resend the invite if that would help.

2021-01-20 15:34 UTC, mixedpuppy commented
> > I wanted to add @mixedpuppy as a reviewer but am somehow not able to.
> 
> I think this is because Shane hasn't accepted the invitation to this repo's collaborators list. It is still listed as "pending". I can resend the invite if that would help.

I found the invite, but it seems like it no longer works.

2021-01-20 16:02 UTC, chrisdavidmills commented
> > > I wanted to add @mixedpuppy as a reviewer but am somehow not able to.
> > 
> > 
> > I think this is because Shane hasn't accepted the invitation to this repo's collaborators list. It is still listed as "pending". I can resend the invite if that would help.
> 
> I found the invite, but it seems like it no longer works.

No worries; I've just tried resending it; let me know if you still have trouble.

2021-01-20 17:18 UTC, Ryuno-Ki commented
> I found the invite, but it seems like it no longer works.

I had that, too. Normally, the invitation expires after seven days automatically.

2021-01-20 21:04 UTC, mixedpuppy requested changes
looks fine, just a comma

2021-01-20 21:04 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/identity/index.html
> +<p>{{WebExtAPIRef("identity.getRedirectURL()")}} returns a URL at a fixed domain name and a subdomain derived from the add-on's ID. Some OAuth servers (such as Google) only accept domains with a veri
`developers, `

2021-01-20 22:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/identity/index.html
> +<p>{{WebExtAPIRef("identity.getRedirectURL()")}} returns a URL at a fixed domain name and a subdomain derived from the add-on's ID. Some OAuth servers (such as Google) only accept domains with a veri
Thanks, done.

2021-01-21 00:26 UTC, mixedpuppy approved these changes

2021-01-21 10:48 UTC, merged