Make overview pages of modules consistent
mdn/content pull request #15315
Opened 2022-04-24 10:27 UTC by glmvc

#### Summary

made overview pages of modules in the learning area and the references more consistent:

- the word "Web" is most of the time written uppercase in the context of "the Web" - so i changed the lowercase ones across the articles
- renamed the "Conclusion" sections in the [Complete Beginner's Guide](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web) articles to "Summary" - like it's in the other modules of the learning area
- making "In this module" sections uniform
  - there was a discussion #13781 where linking to the current page is giving a flaw and it shouldn't be done
  - but due to the fact that it was done like this almost everywhere - i also adapted it like this in a few places
  - i thought that would make it easier to fix the problem overall and result in fewer edge cases...

#### Motivation

-> to keep things consistent
I have done this "consistency changes" now a few times in prs and it was always appreciated

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-25 13:57 UTC, dipikabh commented
Hello @glmvc, thanks for the PR. I'm afraid the "web" to "Web" change is not correct. Check this: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#capitalization.
Also because we follow sentence casing in headings: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#page_titles

I'll review the other changes shortly.

2022-04-27 20:04 UTC, dipikabh commented
> * renaming the "Conclusion" sections in the [Complete Beginner's Guide](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web) articles to "Summary" - like it's in the other modules of the learning area

I think it is better to leave the section headings as "Conclusion" in [Getting started with the Web](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web). If you notice, the "Conclusion" section only exists on the "HTML basics", "CSS basics", and "Javascript basics" pages and the content of these sections is very different from the "Summary" sections in the other modules of the learning area. In fact, changing those "Conclusion" headings to "Summary" might _almost_ be incorrect because we're not technically summarizing the concepts covered on the page, just concluding with the resultant web page after following the instructions.

2022-04-27 20:18 UTC, dipikabh requested changes

2022-04-27 20:18 UTC, dipikabh commented on files/en-us/learn/css/css_layout/index.md
> +  - : The CSS layout cookbook aims to bring together recipes for common layout patterns, things you might need to implement in your sites. In addition to providing code you can use as a starting poin
```suggestion
  - : The CSS layout cookbook aims to bring together recipes for common layout patterns, things you might need to implement in your sites. In addition to providing code you can use as a starting point in your projects, these recipes highlight the different ways layout specifications can be used and the choices you can make as a developer.
```

2022-04-27 20:18 UTC, dipikabh commented on files/en-us/learn/html/index.md
> +- [HTML (HyperText Markup Language) on MDN](/en-US/docs/Web/HTML)
```suggestion
- [HTML (HyperText Markup Language)](/en-US/docs/Web/HTML)
```
I don't think this qualifier is required here, especially because we're explaining it in the sentence immediately after

2022-04-27 20:18 UTC, dipikabh commented on files/en-us/web/html/index.md
> +## Reference
This is a nice update! :)

2022-04-29 18:53 UTC, glmvc commented
@dipikabh Thank you for reviewing this pr and helping out!

>  I'm afraid the "web" to "Web" change is not correct. ...

Also thanks for referring to the writing style guides - I somehow did not get the idea to check there before making changes - I am very sorry!  I have of course undone the affected changes. But I have changed the spelling of the article titles to sentence case - I hope this fits better now :)
Personally, I also like this spelling better, but I saw the other one more often in the learning area so I thought this one would be the preferred one. But now everything is clear to me thanks to the writing guides you referred.


> I think it is better to leave the section headings as "Conclusion" in [Getting started with the Web](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web). ...

I agree with you about the "Conclusion" sections, it was a too quick change on my part, without really thinking about it more carefully - also sorry. (I have of course undone that too)

2022-04-29 18:55 UTC, glmvc commented on files/en-us/learn/css/css_layout/index.md
> +  - : The CSS layout cookbook aims to bring together recipes for common layout patterns, things you might need to implement in your sites. In addition to providing code you can use as a starting poin
I copied this text section from [here](https://developer.mozilla.org/en-US/docs/Web/CSS#cookbook)
-> also removed the comma at the "Undo" commit - hope this fits for you.

2022-04-29 19:00 UTC, glmvc commented on files/en-us/learn/html/index.md
> +- [HTML (HyperText Markup Language) on MDN](/en-US/docs/Web/HTML)
On the [Learn/CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS#see_also) and [Learn/JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript#see_also) overview pages it's also written like this.

Should I change it there too?

2022-04-29 19:02 UTC, glmvc commented on files/en-us/web/html/index.md
> +## Reference
thanks! :)

2022-05-02 12:20 UTC, dipikabh commented on files/en-us/learn/html/index.md
> +- [HTML (HyperText Markup Language) on MDN](/en-US/docs/Web/HTML)
Yes, you're right. Let's add the "on MDN" qualifier here as well. 👍

2022-05-02 14:17 UTC, dipikabh approved these changes
Looks good. Thank you!

2022-05-02 14:18 UTC, merged