Honor product/company name cases - nitpicking (part 8)
mdn/content pull request #15337
Opened 2022-04-25 03:34 UTC by OnkarRuikar

## Summary
Continuing #14400 

Corrected following names:
- macOS

#### Metadata
- [x] Fixes a typo, bug, or other error

2022-04-25 05:39 UTC, teoli2003 requested changes

2022-04-25 05:39 UTC, teoli2003 commented on files/en-us/web/http/headers/user-agent/firefox/index.md
>  | Mac OS X version                    | Gecko user agent string                                                            |
There 3 Mac OS X left on this line and the next two.

2022-04-25 06:02 UTC, OnkarRuikar commented on files/en-us/web/accessibility/aria/web_applications_and_aria_faq/index.html
> +    Live region support requires Safari 5 with VoiceOver on iOS5 or macOS Lion</td>
```suggestion
    Live region support requires Safari 5 with VoiceOver on iOS5 or OS X Lion</td>
```

2022-04-25 06:02 UTC, OnkarRuikar commented on files/en-us/web/mathml/fonts/index.md
> +> **Note:** A deprecated version of STIX is preinstalled starting with macOS Lion and should ensure relatively good MathML rendering. Enhancement requests have been submitted to Apple to ship OpenTyp
```suggestion
> **Note:** A deprecated version of STIX is preinstalled starting with OS X Lion and should ensure relatively good MathML rendering. Enhancement requests have been submitted to Apple to ship OpenType MATH fonts in the default installation. If you have a developer account, these are problems 16841023 and 17021145.
```

2022-04-25 06:46 UTC, OnkarRuikar commented
@teoli2003 done!

2022-04-25 07:13 UTC, myshov requested changes
In the release docs of Firefox 48 and below I suggest keeping the old name for the historical purity. Because Mac OS X had not been renamed to macOS till release of Firefox 48.

2022-04-25 07:13 UTC, myshov commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> -Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/7.0.4 Mobile/16B91 Safari/605.1.15
The renaming of Mac OS X to macOS had not touched the user agent of Safari. So we need to keep the old name here and below

2022-04-25 07:13 UTC, myshov commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> -Note that [Firefox no longer officially supports Mac OS X on PowerPC](https://support.mozilla.org/kb/firefox-no-longer-works-mac-os-10-4-or-powerpc).
We need to keep the old name here because PowerPC was supported only Mac OS X but not macOS

2022-04-25 07:21 UTC, teoli2003 requested changes
See @myshov comments.

2022-04-25 07:23 UTC, OnkarRuikar commented
Done!

2022-04-25 08:10 UTC, myshov commented
@OnkarRuikar hey! There is still an old name in user agents and there is no changes to Firefox release docs till version 48.

2022-04-25 08:25 UTC, OnkarRuikar reviewed
Use OS X in earlier releases and user agents

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/1.5/index.md
> +- **Better support for macOS** (10.2 and greater) including profile migration from Safari and Mac Internet Explorer.
```suggestion
- **Better support for Mac OS X** (10.2 and greater) including profile migration from Safari and Mac Internet Explorer.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/1.5/what_s_new_in_1.5_alpha/index.md
> +  - : Changes made in the Preferences window now apply immediately, in line with typical behavior in other macOS and GNOME applications. This changes conforms with the Apple and GNOME Human Interface
```suggestion
  - : Changes made in the Preferences window now apply immediately, in line with typical behavior in other Mac OS X and GNOME applications. This changes conforms with the Apple and GNOME Human Interface Guidelines.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/14/index.md
> +- Added a keyboard shortcut to toggle commenting for the current selection (Ctrl-/ or Cmd-/ on macOS).
```suggestion
- Added a keyboard shortcut to toggle commenting for the current selection (Ctrl-/ or Cmd-/ on Mac OS X).
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/16/index.md
> +- There's now a handy developer toolbar you can access by going to Tools > Web Developer > Developer Toolbar, or by pressing Ctrl-Shift-V (Cmd-Opt-V on macOS). This toolbar offers a command line inte
```suggestion
- There's now a handy developer toolbar you can access by going to Tools > Web Developer > Developer Toolbar, or by pressing Ctrl-Shift-V (Cmd-Opt-V on Mac OS X). This toolbar offers a command line interface as well as buttons for quickly accessing useful tools. The graphical command line interface _GCLI_ is easy to expand and additional commands are expected in the future. Type "help" to get a list of supported commands.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/16/index.md
> +- Initial [Open Web App support](/en-US/docs/Web/Apps/Getting_Started) has been implemented in the desktop versions of Firefox (that is, on Windows, macOS, and Linux).
```suggestion
- Initial [Open Web App support](/en-US/docs/Web/Apps/Getting_Started) has been implemented in the desktop versions of Firefox (that is, on Windows, Mac OS X, and Linux).
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/22/index.md
> +- The macOS backend for **Ambient Light Events** has been implemented.
```suggestion
- The Mac OS X backend for **Ambient Light Events** has been implemented.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/3.6/updating_plug-ins/index.md
> +## macOS specific changes
```suggestion
## Mac OS X specific changes
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/3/index.md
> +- **Integration with macOS.** Firefox now supports [Growl](https://growl.github.io/growl/) for notifications of completed downloads and available updates.
```suggestion
- **Integration with Mac OS X.** Firefox now supports [Growl](https://growl.github.io/growl/) for notifications of completed downloads and available updates.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/3/xul_improvements_in_firefox_3/index.md
> +- On macOS, the [activetitlebarcolor](/en-US/docs/XUL/Attribute/activetitlebarcolor) and [inactivetitlebarcolor](/en-US/docs/XUL/Attribute/inactivetitlebarcolor) attributes of the root elements (`<wi
```suggestion
- On Mac OS X, the [activetitlebarcolor](/en-US/docs/XUL/Attribute/activetitlebarcolor) and [inactivetitlebarcolor](/en-US/docs/XUL/Attribute/inactivetitlebarcolor) attributes of the root elements (`<window>`, `<dialog>`, `<prefwindow>` and `<wizard>`) are available to customize the color of the windows' title bars.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/31/index.md
> +- Updated the default theme used for panels on macOS.
```suggestion
- Updated the default theme used for panels on Mac OS X.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/41/index.md
> +- On macOS and Windows, {{domxref("NavigatorOnLine.onLine", "Navigator.onLine")}} now changes regarding network connectivity (it always returned `true`, unless "Work offline" mode was selected) befor
```suggestion
- On OS X and Windows, {{domxref("NavigatorOnLine.onLine", "Navigator.onLine")}} now changes regarding network connectivity (it always returned `true`, unless "Work offline" mode was selected) before ({{bug(654579)}}).
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/44/index.md
> +- The Text2Speech API, part of Web Speech API, has now an macOS backend. But this is disabled by default ({{bug(1003452)}}).
```suggestion
- The Text2Speech API, part of Web Speech API, has now an OS X backend. But this is disabled by default ({{bug(1003452)}}).
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/47/index.md
> +- [Widevine](https://www.widevine.com/) Content Decryption Module provided by Google Inc. is available via the [Encrypted Media Extensions API](/en-US/docs/Web/API/Encrypted_Media_Extensions_API) for
```suggestion
- [Widevine](https://www.widevine.com/) Content Decryption Module provided by Google Inc. is available via the [Encrypted Media Extensions API](/en-US/docs/Web/API/Encrypted_Media_Extensions_API) for use with MP4 (only; see {{bug(1257716)}} for EME-with-WebM support) on Windows Vista and later and on Mac OS X enabling migration off Silverlight ({{bug(1265270)}}).
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/48/index.md
> +- Handling of dead keys on macOS has been changed to work the same as other platforms; they no longer fire a {{event("keypress")}} event when no text is generated when the focused element isn't edita
```suggestion
- Handling of dead keys on Mac OS X has been changed to work the same as other platforms; they no longer fire a {{event("keypress")}} event when no text is generated when the focused element isn't editable (when the focused element is editable, dead key causes composition events instead of keyboard events on Mac OS X). Also, like on other platforms, the value of {{domxref("KeyboardEvent.key")}} is now `"Dead"` for dead keypresses which don't generate text in other situations.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +Here, _x.y_ is the version of macOS (for instance, macOS 10.15). Starting in Firefox 87, Firefox caps the reported macOS version number to 10.15, so macOS 11.0 Big Sur and later will be reported as "
```suggestion
Here, _x.y_ is the version of Mac OS X (for instance, Mac OS X 10.15). Starting in Firefox 87, Firefox caps the reported Mac OS X version number to 10.15, so macOS 11.0 Big Sur and later will be reported as "10.15" in the User-Agent string.
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| macOS version                    | Gecko user agent string                                                            |
```suggestion
| Mac OS X version                    | Gecko user agent string                                                            |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| macOS on x86, x86_64, or aarch64 | Mozilla/5.0 (Macintosh; Intel macOS _x.y_; rv:10.0) Gecko/20100101 Firefox/10.0 |
```suggestion
| Mac OS X on x86, x86_64, or aarch64 | Mozilla/5.0 (Macintosh; Intel Mac OS X _x.y_; rv:10.0) Gecko/20100101 Firefox/10.0 |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| macOS on PowerPC                 | Mozilla/5.0 (Macintosh; PPC macOS _x.y_; rv:10.0) Gecko/20100101 Firefox/10.0   |
```suggestion
| Mac OS X on PowerPC                 | Mozilla/5.0 (Macintosh; PPC Mac OS X _x.y_; rv:10.0) Gecko/20100101 Firefox/10.0   |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| iPod        | Mozilla/5.0 (iPod touch; CPU iPhone OS 8_3 like macOS) AppleWebKit/600.1.4 (KHTML, like Gecko) **FxiOS/1.0** Mobile/12F69 Safari/600.1.4 |
```suggestion
| iPod        | Mozilla/5.0 (iPod touch; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) **FxiOS/1.0** Mobile/12F69 Safari/600.1.4 |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| iPhone      | Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like macOS) AppleWebKit/600.1.4 (KHTML, like Gecko) **FxiOS/1.0** Mobile/12F69 Safari/600.1.4     |
```suggestion
| iPhone      | Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) **FxiOS/1.0** Mobile/12F69 Safari/600.1.4     |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| iPad        | Mozilla/5.0 (Macintosh; Intel macOS 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15                       |
```suggestion
| iPad        | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15                       |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| Camino on Mac                  | Mozilla/5.0 (Macintosh; Intel macOS 10.5; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 Camino/2.2.1      |
```suggestion
| Camino on Mac                  | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 Camino/2.2.1      |
```

2022-04-25 08:25 UTC, OnkarRuikar commented on files/en-us/web/http/headers/user-agent/firefox/index.md
> +| SeaMonkey on Mac               | Mozilla/5.0 (Macintosh; Intel macOS 10.5; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1 |
```suggestion
| SeaMonkey on Mac               | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 SeaMonkey/2.7.1 |
```

2022-04-25 08:30 UTC, OnkarRuikar commented
> @OnkarRuikar hey! There is still an old name in user agents and there is no changes to Firefox release docs till version 48.

Thanks! I've reverted changes from those pages. Let me know if it's ok.

2022-04-25 08:35 UTC, myshov commented
@OnkarRuikar thanks! It looks great!

2022-04-26 06:21 UTC, teoli2003 approved these changes

2022-04-26 06:21 UTC, merged