Transform tables into definition lists
mdn/content pull request #15480
Opened 2022-04-28 14:57 UTC by teoli2003

_Exceptions_, or _Options_, or _Parameters_ are definition lists in the modern structure.

I found a bunch of them not following this rule, so I fixed.

There are a few minor fixes along the way, too.

2022-04-28 17:28 UTC, wbamberg requested changes
Thanks @teoli2003 ! Love to see these tables disappearing.

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/element/insertadjacenttext/index.md
> +  - : Thrown if the `position` specified is not a recognized value.
Not introduced by you, but `position` here should be `where` to match the param name (or the param name should be changed).

```suggestion
  - : Thrown if `where` is not a recognized value.
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/setsinkid/index.md
> +  - : Returned if the `deviceId` does not match any audo output device.
```suggestion
  - : Returned if the `deviceId` does not match any audio output device.
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbkeyrange/bound/index.md
> +  - : Thrown when one of the following conditions is met:<
```suggestion
  - : Thrown when one of the following conditions is met:
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbkeyrange/lowerbound/index.md
> +  - : Thrown if the value parameter passed was not a valid key.
```suggestion
  - : Thrown if the `value` parameter was not a valid key.
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbkeyrange/only/index.md
> +  - : Thrown if the value parameter passed was not a valid key.
```suggestion
  - : Thrown if the `value` parameter was not a valid key.
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbkeyrange/upperbound/index.md
> +  - : Thrown if the value parameter passed was not a valid key.
`value` is not the name of a parameter here.

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbobjectstore/clear/index.md
> +  - : Thrown if the transaction associated with this operation is in read-only [mode](/en-US/docs/Web/API/IDBTransaction#mode_constants).
This links to a thing that is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction#mode_constants - not sure what to do here?

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbobjectstore/createindex/index.md
> +        (see [locale-aware sortin](/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#locale-aware_sorting)).
```suggestion
        (see [locale-aware sorting](/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#locale-aware_sorting)).
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbobjectstore/createindex/index.md
>    - : An {{domxref("IDBIndexParameters")}} object, which can include the following
```suggestion
  - : An object which can include the following
```

(IDBIndexParameters is only referenced here)

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbobjectstore/createindex/index.md
> +        - `auto`</code>`: The platform default locale will be used (may be changed by user agent settings.)
```suggestion
        - `auto`: The platform default locale will be used (may be changed by user agent settings).
```

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbrequest/readystate/index.md
> +Every request starts in the `pending` state. The state changes to
There's another table in this page - out of scope for this PR?

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbtransaction/mode/index.md
>  An {{domxref("IDBTransactionMode")}} object defining the mode for isolating access to
```suggestion
An object defining the mode for isolating access to
```

(again apparently only appears here?)

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbtransaction/mode/index.md
> +    {{domxref("IDBDatabase.setVersion()")}}. Transactions of
This appears to not exist any more: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/10#indexeddb and is not documented anywhere on MDN. Still I'm not sure how to rework this bit so it makes sense.

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbversionchangeevent/newversion/index.md
> +A {{jsxref("Number")}} containing a 64-bit integer.
Isn't this one of these places where we say, it's not a wrapper object, but a primitive? So should this just be `number`?

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbversionchangeevent/oldversion/index.md
> +A {{jsxref("Number")}} containing a 64-bit integer.
Same comment here about wrapper objects.

2022-04-28 17:28 UTC, wbamberg commented on files/en-us/web/api/idbversionchangeevent/version/index.md
> +A {{jsxref("Number")}} containing a 64-bit integer.
And here.

2022-04-28 17:36 UTC, teoli2003 commented on files/en-us/web/api/idbversionchangeevent/newversion/index.md
> +A {{jsxref("Number")}} containing a 64-bit integer.
I may be mistaken, but I've understood "Number value" here: https://webidl.spec.whatwg.org/#es-unsigned-long-long

as the Number object. (The capitalization may have fooled me)

2022-04-28 17:44 UTC, wbamberg commented on files/en-us/web/api/idbversionchangeevent/newversion/index.md
> +A {{jsxref("Number")}} containing a 64-bit integer.
I have no idea really and don't have the appetite to test it this morning :) so am happy to keep it like this.

2022-05-02 07:14 UTC, teoli2003 commented on files/en-us/web/api/idbobjectstore/clear/index.md
> +  - : Thrown if the transaction associated with this operation is in read-only [mode](/en-US/docs/Web/API/IDBTransaction#mode_constants).
The mode constants have been deprecated (that is the capital-case constants have been deprecated, like `READONLY` but not the enums that lead to literals: `"read-only"`. They are listed in IDBTransaction.mode which is also not deprecated.

Linking to this instead.

2022-05-02 07:17 UTC, teoli2003 commented on files/en-us/web/api/idbrequest/readystate/index.md
> +Every request starts in the `pending` state. The state changes to
Removed.

2022-05-02 07:30 UTC, teoli2003 commented on files/en-us/web/api/idbfactory/databases/index.md
> +  - : Thrown if the method is called from an opaque origin.
I've linked to the StackOverflow article that has the most extensive info I found. We may need to incorporate this somewhere on MDN, but this is outside the scope of this PR.

Note that I found the link to the Stack Overflow entry in our own MDN article about the `Origin` HTTP header. That is good.

2022-05-02 07:31 UTC, teoli2003 commented
I think I have fixed all the review comments. (Thanks for them, @wbamberg )

2022-05-03 00:36 UTC, wbamberg commented on files/en-us/web/api/idbrequest/readystate/index.md
> +or `done`if the request has completed.|
```suggestion
or `done` if the request has completed.|
```

2022-05-03 00:41 UTC, wbamberg approved these changes
👍 thank you @teoli2003 !

2022-05-03 00:41 UTC, merged