Add content about USBDevice.forget()
mdn/content pull request #15490
Opened 2022-04-28 20:36 UTC by bershanskiy

#### Summary

This PR adds content about `HIDDevice.forget`, `SerialPort.forget`, `USBDevice.forget`.

#### Motivation

BCD already contains data about these interfaces, they either already shipped or are being shipped in Chrome soon, so it makes sense to document them as well.

#### Supporting details

 - USB: shipped in Chrome 101
   - [Testing steps](https://web.dev/usb/#revoke-access)
   - [Chrome status](https://chromestatus.com/feature/5640127995969536)
 - SerialPort: will ship in Chrome 103
   - [Chrome status](https://chromestatus.com/feature/5145811414417408)
   - [Intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/aBSGxh0LJVA)
 - HIDDevice: shipped in Chrome 100
   - [Chrome status](https://chromestatus.com/feature/5723581527883776)

#### Related issues

https://github.com/mdn/browser-compat-data/pull/15587
https://github.com/mdn/browser-compat-data/pull/15920
https://github.com/mdn/browser-compat-data/pull/15597

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-29 05:44 UTC, teoli2003 commented on files/en-us/web/api/hiddevice/forget/index.md
> +
Drive-by comment:

As there can be an `AbortError` {{domxref("DOMException")}} causing the promise to be rejected, there should be an _Exceptions_ section listing when this is happening.

2022-04-29 05:54 UTC, teoli2003 commented on files/en-us/web/api/hiddevice/forget/index.md
> +None
```suggestion
None.
```

2022-04-29 05:55 UTC, teoli2003 commented on files/en-us/web/api/usbdevice/forget/index.md
> +A {{jsxref("promise")}} which resolves `undefined`.
This looks like a weird sentence. Missing preposition?

2022-04-29 05:55 UTC, teoli2003 requested changes, later dismissed

2022-04-29 05:55 UTC, teoli2003 commented on files/en-us/web/api/serialport/forget/index.md
> +A {{jsxref("Promise")}}.
What does it resolve to?

2022-04-29 22:00 UTC, bershanskiy commented on files/en-us/web/api/hiddevice/forget/index.md
> +
Hi, thanks for the review and this comment especially!

There is a bit of difference/confusion in the spec and Chromium implementation, so here is a summary:
1. According to the spec, call to `HIDDevice.forget()` should always succeed and resolve with `Promise<undefined>`, but it can cause other methods to reject: `HIDDevice.sendReport()`, `HIDDevice.sendFeatureReport()`, and `HIDDevice.receiveFeatureReport()`. In Chromium `forget()` has a [path](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/modules/hid/hid_device.cc#L300) ending with `NotSupportedError`, but I do not think it is ever taken.
2. Specification and Chromium implementation disagree on the type of the error (spec uses `AbortError` while Chromium appears to use `InvalidStateError`). I will test more over the weekend.
   - According to [the specification `forget()` method steps](https://wicg.github.io/webhid/#dom-hiddevice-forget), all these pending promises should reject with `AbortError`. This is consistent with [the specified `close()` method steps](https://wicg.github.io/webhid/#ref-for-dom-hiddevice-close-2).
   - In Chromium, everything uses [InvalidStateError](https://github.com/chromium/chromium/commit/aedde69d0f67167086e02ca541ed0a98c80d3fd3).

2022-04-30 19:36 UTC, bershanskiy commented on files/en-us/web/api/hiddevice/forget/index.md
> +
Repro steps: the following code produces `InvalidStateError`
```
try {
  const device = (await navigator.hid.requestDevice({filters: []}))[0];
  await device.open();
  const promise = device.forget();
  device.sendReport(1, new Uint8Array([0,0]));
  await promise;
} catch(e) {
  console.log(e.name);
}
```

2022-05-01 05:47 UTC, teoli2003 commented on files/en-us/web/api/hiddevice/forget/index.md
> +
I guess that if there is a divergence between the spec and the Chromium implementation there should be an issue open in the spec repo, or in the Chromium repo that should shed light on the expected behavior. 

Maybe @nondebug can help us here…

2022-05-01 07:45 UTC, bershanskiy commented on files/en-us/web/api/hiddevice/forget/index.md
> +
> there should be an issue open in the spec repo

Yes, I'm working on it. I'm still figuring out the best name for the error to make all three APIs consistent (I think it is `AbortError`, but I'm still reading the specs, source code, and testing). I'll link the issues from here as soon as I open them.

2022-08-04 17:24 UTC, bershanskiy commented on files/en-us/web/api/hiddevice/forget/index.md
> +
I cycled back to it trying to reproduce and I think I was reading the spec wrongly, I was getting `InvalidState` exception because `forget()` was not actually interrupting any communications, the device was already forgotten by the time I call `device.sendReport`, displaying the correct behavior. I do not think `AbortError` is ever thrown because I don't see it in source, but I have no real way of testing for absence of an error... short of patching Chrome to stall instead of fulfilling requests and then trying to send something and interrupting it.

2022-09-02 21:30 UTC, Josh-Cena requested changes

2022-09-02 21:30 UTC, Josh-Cena commented on files/en-us/web/api/hiddevice/forget/index.md
> +await device.forget();
This example isn't useful. `device` is not defined, and we don't know what to do before or after `forget()`. Examples should showcase some real-world relevant usage—or we shouldn't have it at all. (Also, don't use top-level await—use an async function or `then()` instead)

2022-09-02 21:30 UTC, Josh-Cena commented on files/en-us/web/api/hiddevice/forget/index.md
> +HIDDevice.forget()
```suggestion
forget()
```

It's not a static method.

2022-09-02 21:30 UTC, Josh-Cena commented on files/en-us/web/api/serialport/forget/index.md
> +SerialPort.forget()
```suggestion
forget()
```

2022-09-02 21:30 UTC, Josh-Cena commented on files/en-us/web/api/usbdevice/forget/index.md
> +USBDevice.forget()
```suggestion
forget()
```

2022-10-05 11:56 UTC, bsmth commented
Hi @bershanskiy thanks for your submission. Do you plan on picking this one up again and addressing the reviews? There are some conflicts outstanding that need to be resolved.

Thank you :)

2022-10-11 15:21 UTC, bershanskiy commented
Hi, yes, I plan to fix the remaining issues and rebase some time this week.

2022-11-10 09:57 UTC, bsmth commented
Hi @bershanskiy 👋🏻 there's still some outstanding conflicts so this pull request might be closed if there is no further activity.

2022-11-11 21:02 UTC, bershanskiy commented
Hi @bsmth, I fixed merge conflicts and updated some content according to the reviews, does it look better now?

2022-11-15 10:38 UTC, Elchi3 requested changes

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/hiddevice/forget/index.md
> +slug: Web/API/HIDDevice/forget
```suggestion
slug: Web/API/HIDDevice/forget
page-type: web-api-instance-method
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/hiddevice/forget/index.md
> +```js
```suggestion
```js-nolint
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/hiddevice/forget/index.md
> +{{securecontext_header}}{{DefaultAPISidebar("WebHID API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebHID API")}}
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/serialport/forget/index.md
> +slug: Web/API/SerialPort/forget
```suggestion
slug: Web/API/SerialPort/forget
page-type: web-api-instance-method
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/usbdevice/forget/index.md
> +slug: Web/API/USBDevice/forget
```suggestion
slug: Web/API/USBDevice/forget
page-type: web-api-instance-method
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/serialport/forget/index.md
> +{{securecontext_header}}{{DefaultAPISidebar("Serial API")}}
```suggestion
{{securecontext_header}}{{APIRef("Serial API")}}
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/usbdevice/forget/index.md
> +The **`forget()`** method of the {{domxref("USBDevice")}} interface returns a {{jsxref("promise")}} that resolves when all pending operations are aborted, all open interfaces are released, the device
```suggestion
The **`forget()`** method of the {{domxref("USBDevice")}} interface returns a {{jsxref("Promise")}} that resolves when all pending operations are aborted, all open interfaces are released, the device session has ended, and the permission is reset.
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/serialport/forget/index.md
> +```js
```suggestion
```js-nolint
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/usbdevice/forget/index.md
> +```js
```suggestion
```js-nolint
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/usbdevice/forget/index.md
> +A {{jsxref("promise")}} which resolves with `undefined` once the device access permission is revoked.
```suggestion
A {{jsxref("Promise")}} which resolves with `undefined` once the device access permission is revoked.
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/serialport/forget/index.md
> +A {{jsxref("Promise")}} that resolves with `undefined` once the connection is closed and device is forgeotten (permission is reset).
```suggestion
A {{jsxref("Promise")}} that resolves with `undefined` once the connection is closed, the device is forgotten, and the permission is reset.
```

2022-11-15 10:38 UTC, Elchi3 commented on files/en-us/web/api/hiddevice/forget/index.md
> +A {{jsxref("Promise")}} that resolves with `undefined` once the connection is closed and device is forgeotten (permission is reset).
```suggestion
A {{jsxref("Promise")}} that resolves with `undefined` once the connection is closed, the device is forgotten, and the permission is reset.
```

2022-11-15 13:56 UTC, Elchi3 requested changes
Sorry, I only saw the missing experimental badge just now because the correct sidebar shows now.

2022-11-15 13:56 UTC, Elchi3 commented on files/en-us/web/api/hiddevice/forget/index.md
> +  - HIDDevice
```suggestion
  - HIDDevice
  - Experimental
```

2022-11-15 13:56 UTC, Elchi3 commented on files/en-us/web/api/serialport/forget/index.md
> +  - SerialPort
```suggestion
  - SerialPort
  - Experimental
```

2022-11-15 13:56 UTC, Elchi3 commented on files/en-us/web/api/usbdevice/forget/index.md
> +  - forget
```suggestion
  - forget
  - Experimental
```

2022-11-15 15:49 UTC, Elchi3 approved these changes
Thanks, I think this is good to go now! 👍

2022-11-15 16:11 UTC, bsmth commented on files/en-us/web/api/hiddevice/forget/index.md
> +## Examples
Nitpicking - singular example

```suggestion
## Example
```

2022-11-15 16:13 UTC, bsmth approved these changes
Looks good to me, also 👍🏻

2022-11-15 16:23 UTC, Josh-Cena commented on files/en-us/web/api/hiddevice/forget/index.md
> +In the following example we connect to a Nintendo Switch Joy-Con Right HID device, blink once and disconnect from it.
```suggestion
In the following example we connect to a Nintendo Switch Joy-Con Right HID device, blink once, and disconnect from it.
```

2022-11-15 16:23 UTC, Josh-Cena commented on files/en-us/web/api/hiddevice/forget/index.md
> +blink();
```suggestion
async function blink() {
  const devices = await navigator.hid.requestDevice({
    filters: [
      {
        vendorId: 0x057e, // Nintendo Co., Ltd
        productId: 0x2007, // Joy-Con Right
      },
    ],
  });
  const device = devices[0];
  await device.open();
  // Turn off
  await device.sendFeatureReport(reportId, Uint32Array.from([0, 0]));
  await waitFor(100);
  // Turn on
  await device.sendFeatureReport(reportId, Uint32Array.from([512, 0]));
  await new Promise((resolve) => setTimeout(resolve, 100));
  // Finally, disconnect from it
  await device.forget();
}
blink();
```

2022-11-15 16:23 UTC, Josh-Cena commented on files/en-us/web/api/serialport/forget/index.md
> +{{securecontext_header}}{{APIRef("Serial API")}}
```suggestion
---

{{securecontext_header}}{{APIRef("Serial API")}}
```

2022-11-15 16:23 UTC, Josh-Cena commented on files/en-us/web/api/hiddevice/forget/index.md
> +{{securecontext_header}}{{APIRef("WebHID API")}}
```suggestion
---

{{securecontext_header}}{{APIRef("WebHID API")}}
```

2022-11-15 16:23 UTC, Josh-Cena commented on files/en-us/web/api/usbdevice/forget/index.md
> +{{APIRef("WebUSB API")}}{{SeeCompatTable}}
```suggestion
---

{{APIRef("WebUSB API")}}{{SeeCompatTable}}
```

2022-11-15 16:25 UTC, Josh-Cena approved these changes
Editorially looks good enough to me, so I won't block it.

2022-11-15 16:29 UTC, bsmth commented
Thanks, all. I think we can merge shortly

2022-11-15 16:45 UTC, merged