MV3 background event pages updates
mdn/content pull request #15533
Opened 2022-04-29 18:30 UTC by rebloor

** do not merge until all manifest V3 content is ready **

#### Summary
MV3 background event pages updates, including:

- adding a new background script page to describe the content of a background script and how to convert persistent scripts to non-persistent
- modified the anatomy of a web extension page to remove information moved to the new background script page and updated the more informational link.
- updated the background manifest key page revising the more information link and clarifying the required and optional properties.
- updated more information links for background scripts to point to the new page on the content script page.
- updated menus.create to note that it requires ID when using mv3 or event pages in mv2
- added deprecation flags and notes for extension.lastError, extension.getBackgroundPage, and runtime.getBackgroundPage

#### Metadata

This PR…
-->
- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-04-29 19:42 UTC, mixedpuppy requested changes
I'm uncertain what our plan is around mentioning things in MV2 that are not released in MV2 yet.  You'll see a mention of that in the comments, but there are a couple places that made me think about this.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/extension/getbackgroundpage/index.md
>  Alias for {{WebExtAPIRef("runtime.getBackgroundPage()")}}.
getBackgroundPage is not deprecated and is not an alias.  

extension.getBackgroundPage is a synchronous function.  If the background script is running, the window is returned.  If it is not running, null is returned.

I've also noticed on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getBackgroundPage the note says an empty array is returned, which is wrong, null is returned.

For runtime.getBackgroundPage, if the background is non-persistent (event page) and the background is not running, it will start the background.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/extension/index.md
> +- {{WebExtAPIRef("extension.getBackgroundPage()")}} {{deprecated_inline}}
Not deprecated, it is available in both mv2 and mv3

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/getbackgroundpage/index.md
> +> **Warning:** This function is deprecated.
not deprecated.  also note my other review comment about runtime.getBackgroundPage starting the event page.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/index.md
> +- {{WebExtAPIRef("runtime.getBackgroundPage()")}} {{deprecated_inline}}
not deprecated

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +In manifest V2, background scripts or a page can be persistent or non-persistent. Non-persistent background scripts are recommended as they reduce the resource cost of your extension. In manifest V3,
I'm wondering if and how we indicate that event pages are not yet enabled in MV2 but will be in a future release.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If you have persistent background scripts or a page in manifest V2, [Convert to non-persistent](#convert_to_non-persistent) provides advice on transitioning them to non-persistent.
We may also want to note that new addons should only use event pages (when available) so they are prepared for the migration to MV3

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +In your extension, you include a background script using the  [`"background"`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background) key in `manifest.json`. For manifest V2 extensions,
In mv2 it defaults to true if omitted, in mv3 it defaults to false if omitted.  in mv3 an error is thrown if they try to set it to true.  not sure this needs explicit documentation, I just wanted to drop a note on the behavior.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Listen to {{WebExtAPIRef("runtime.onInstalled")}} to initialize an extension on installation. Use this event to set a state or for one-time initialization, such as a context menu.
"such as a context menu".  This is true for event pages when they are available.  However if it is done prior to that this would not work as expected.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Do not register listeners asynchronously, as they will not be properly triggered.
The example below isn't great due to using onInstalled, but the essence is correct.  They will be properly triggered if they are registered asynchronously, for as long as the background is running, however they will not persist and thus would not wake an event page when it idles.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Do not register listeners asynchronously, as they will not be properly triggered.
using window.onload or something like that may be a better example.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Extensions can remove listeners from their background scripts by calling {{WebExtAPIRef("runtime.onMessage")}} `removeListener`. If all listeners for an event are removed, the browser no longer loads
To me, this reads as if any listener is removed by runtime.onMessage.removeListener.  I might have said it like: "Extensions can remove listeners from their background scripts by calling `removeListener`, such as with {{WebExtAPIRef("runtime.onMessage")}}`removeListener`."

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +});
```
brower.runtime.onMessage.addListener(function messageListener(message, sender, reply) {
    brower.runtime.onMessage.removeListener(messageListener);
});
```

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +  // ERROR! Events must be registered synchronously from the start of
Technically it's not an error, but it is a listener that will only run when the addon is installed.  In any case,it's probably not what an addon dev wants to do.

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +```
I'd rather illustrate promise based use of APIs

```
document.getElementById('target').addEventListener('click', async () => {
  let backgroundPage = await window.runtime.getBackgroundPage();
  backgroundPage.backgroundFunction();
});
```

2022-04-29 19:42 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If using {{WebExtAPIRef("extension.getBackgroundPage")}} to call a function from the background page, update to {{WebExtAPIRef("runtime.getBackgroundPage")}} . The `runtime` method includes a callbac
"The `runtime` method includes a callback function to ensure the background script has loaded, or you may `await` the result"

2022-05-02 01:39 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +In manifest V2, background scripts or a page can be persistent or non-persistent. Non-persistent background scripts are recommended as they reduce the resource cost of your extension. In manifest V3,
We're relying on the browser compatibility data note under the background key's persistent property. While not ideal,  we could add a note here and create a ticket as a reminder to remove it later.

2022-05-02 02:13 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Do not register listeners asynchronously, as they will not be properly triggered.
Could you explicitly suggest a more suitable example, otherwise I'll look at this when all the other updates done.

2022-05-02 02:14 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Extensions can remove listeners from their background scripts by calling {{WebExtAPIRef("runtime.onMessage")}} `removeListener`. If all listeners for an event are removed, the browser no longer loads
Thanks, updated

2022-05-02 02:15 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +});
Thanks, updated

2022-05-02 02:17 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +  // ERROR! Events must be registered synchronously from the start of
Change to WARNING, OK?

2022-05-02 02:17 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +```
Thanks, updated

2022-05-03 18:23 UTC, mixedpuppy requested changes

2022-05-03 18:23 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +In manifest V2, background scripts or a page can be persistent or non-persistent. Non-persistent background scripts are recommended as they reduce the resource cost of your extension. In manifest V3,
ok

2022-05-03 18:23 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Do not register listeners asynchronously, as they will not be properly triggered.
probably something like:

```
window.onload = () => {
  // WARNING! This event is not peristed, and will not restart the event page.
  browser.bookmarks.onCreated.addListener(function() {
    // do something
  });
}

browser.tabs.onUpdated.addListener(() => {
  // This event is run in the top level scope of the event page, and will persist, allowing
  // it to restart the event page if necessary.
});
```

2022-05-03 18:23 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Listen to {{WebExtAPIRef("runtime.onInstalled")}} to initialize an extension on installation. Use this event to set a state or for one-time initialization, such as a context menu.
suggestion:

Use this event to set a state or for one-time initialization.  For addons with event pages, this is where stateful APIs, such as a context menu created using `browser.menus.create`, should be used.

"stateful APIs" isn't great, but it refers to things that only need to be created once and will retain state across the sleep/restart cycle of an event page and through a restart of firefox.  A context menu does that, as would content scripts added through the scripting api.

2022-05-10 18:11 UTC, mixedpuppy approved these changes
I've made some comments for things that should probably be added.  r+ with changes, if something doesn't make sense to add let me know.

2022-05-10 18:11 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +DOM-based timers, such as `window.setTimeout()` or `window.setInterval()`, are not honored in non-persistent background scripts if they trigger when the background page is dormant. Instead, use the a
`if they trigger when the background page is dormant`

Since they cannot actually trigger at all, it might be better stated as

`DOM-based timers will not remain active after the event page has idle'd.  Instead use the alarms API if you need the timer to wake the event page`

2022-05-10 18:11 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If using {{WebExtAPIRef("extension.getBackgroundPage")}} to call a function from the background page, update to {{WebExtAPIRef("runtime.getBackgroundPage")}} . The `runtime` method includes a callbac
There are different use cases for these, so I'm not certain we should tell people to switch to runtime.

If a content script or action must call a function, using runtime.getBackgroundPage will ensure an event page is running.  If the call is optional (only IF the event page is alive) then you can use extension.getBackgroundPage, which will return null if it is not running.

2022-05-10 21:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +Background scripts unload after a few seconds of inactivity. If any cleanup is required, listen to {{WebExtAPIRef("runtime.onSuspend")}}.
Done

2022-05-10 21:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +DOM-based timers, such as `window.setTimeout()` or `window.setInterval()`, are not honored in non-persistent background scripts if they trigger when the background page is dormant. Instead, use the a
Done

2022-05-10 21:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If using {{WebExtAPIRef("extension.getBackgroundPage")}} to call a function from the background page, update to {{WebExtAPIRef("runtime.getBackgroundPage")}} . The `runtime` method includes a callbac
Done

2022-05-13 00:58 UTC, mixedpuppy requested changes

2022-05-13 00:58 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If an extension uses message passing, ensure all ports are closed. The background script does not unload until all message ports have shut. Listening to the {{WebExtAPIRef("runtime.Port")}} `onDiscon
having open message ports will not prevent the event page from shutting down.  We will force close the ports. This is different from event pages in Chrome MV2, where open message ports do keep the event page running.  I might word it like:

Message ports cannot prevent an event page from shutting down.  If an extension uses message passing, the ports will be closed when the event page idles.  Listening to the {{WebExtAPIRef("runtime.Port")}} `onDisconnect` lets you discover when open ports are closing, however the listener will be under the same time constraints as runtime.onSuspend.

2022-05-13 01:00 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +  // ERROR! Events must be registered synchronously from the start of
ok

2022-05-13 16:26 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If an extension uses message passing, ensure all ports are closed. The background script does not unload until all message ports have shut. Listening to the {{WebExtAPIRef("runtime.Port")}} `onDiscon
Done

2022-05-13 16:39 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/background_scripts/index.md
> +If an extension uses message passing, ensure all ports are closed. The background script does not unload until all message ports have shut. Listening to the {{WebExtAPIRef("runtime.Port")}} `onDiscon
Thanks!

2022-05-13 16:50 UTC, mixedpuppy approved these changes

2022-05-14 02:58 UTC, merged