Improve and simplify texts and fix minor issues
mdn/content pull request #15538
Opened 2022-04-29 23:20 UTC by cadamini

#### Summary
I removed unnecessary information and shorted some texts.

#### Motivation
I read the article and wanted to understand the box models. I felt confronted with a lot of text that was not needed and made it hard to understand the content. Shorter sentences and using active voice will help readers to understand the content better. 

#### Supporting details
none

#### Related issues
none

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-04-29 23:34 UTC, cadamini reviewed
Great to see another technical writer reviewing my work. Please be honest with feedback. 🚀

2022-04-29 23:34 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
>  In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. These characteristics refer to how the box behaves in terms of page flow and in relation to other boxes on the page.
another idea

2022-04-29 23:34 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
>  In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. These characteristics refer to how the box behaves in terms of page flow and in relation to other boxes on the page.
```suggestion
In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type affects the behavior of the box in relation to page flow and other boxes on the page. Boxes have an **inner display type** and an **outer display type**. We'll start explaining the block box and inline box concept. And later, we'll tackle the inner and outer display type. 
```

2022-04-29 23:53 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
>  In the example below, we have a `<span>` inside a paragraph and have applied a `width`, `height`, `margin`, `border`, and `padding` to it. You can see that the width and height are ignored. The verti
```suggestion
In the example below, we have a `<span>` inside a paragraph. We have applied a `width`, `height`, `margin`, `border`, and `padding` to it. You can see that the width and height are ignored. The vertical margin, padding, and border are respected but don't change the relationship of other content to our inline box. The padding and border overlap other words in the paragraph. The horizontal padding, margins, and borders move other content away from the box.
```

2022-04-30 00:26 UTC, cadamini reviewed
I got confused once more, see comments what I'd change.

2022-04-30 00:26 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type affects the behavior of the box in relation to page flow and other boxes on the page. Boxes have an **inner
Not sure why 'broadly' was used.... and, outer display type used in line 61 is unknown to the reader....

```suggestion
In CSS the `display` property can define boxes of type block and inline. These block types affect the behavior of the box in relation to page flow and other boxes on the page. This is the outer display type.
```

2022-04-30 00:26 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type affects the behavior of the box in relation to page flow and other boxes on the page. Boxes have an **inner
I suggest to change the text in line 61 and below as well - reason: The user know the outer display type but nothing else:

```
## The inner display type

As mentioned above, boxes in CSS have an _outer_ display type. Boxes also have an _inner_ display type, which dictates how elements inside that box are laid out. By default, the elements inside a box are laid out in **[normal flow](/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow)**, which means that they behave just like any other block and inline elements.
We can change the inner display type by using `display` values like `flex`. The outer display type remains `block`. Any direct children of this box will become flex items and will be laid out according to the rules set out in the [Flexbox](/en-US/docs/Learn/CSS/CSS_layout/Flexbox) spec, which you'll learn about later on.
> **Note:** To read more about how boxes work in block and inline layout, take a look at the MDN guide to [Block and Inline Layout](/en-US/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow).
```

2022-04-30 18:31 UTC, cadamini commented
I think I am done :)

2022-04-30 18:38 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- **Margin box**: The margin is the outermost layer, wrapping the content, padding, and border as whitespace between this box and other elements, size it using {{cssxref("margin")}} and related prope
```suggestion
- **Margin box**: The margin is the outermost layer, wrapping the content, padding, and border as whitespace between this box and other elements; size it using {{cssxref("margin")}} and related properties.
```

2022-04-30 18:38 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +To turn on the alternative model for an element, set `box-sizing: border-box` on it.
```suggestion
To turn on the alternative model for an element, set `box-sizing: border-box` on it:
```

2022-04-30 18:39 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +The _actual_ space taken up by the box will be 350px wide and 150px high.
```suggestion
Now, the _actual_ space taken up by the box will be 350px wide and 150px high.
```

2022-04-30 18:40 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- Where both are negative, the margins will collapse and the smallest (furthest from zero) value will be used.
I don't like this list yet :/

2022-04-30 18:46 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- Where both are negative, the margins will collapse and the smallest (furthest from zero) value will be used.
```suggestion
Depending on whether margins are positive or negative on two elements whose margins touch, the results will be different:
- Two positive margins will combine to become one margin. Its size will be equal to the largest individual margin.
- Two negative margins will collapse and the smallest (furthest from zero) value will be used.
- If one margin is negative, its value will be _subtracted_ from the total.
```

2022-05-01 01:51 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +Below we have three different HTML elements, all of which have an outer display type of `block`.
```suggestion
The example below has three different HTML elements, all of which have an outer display type of `block`. 
```

2022-05-01 01:55 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +If you want to understand the thinking behind this, see [the CSS Tricks article on box-sizing](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/).
```suggestion
To understand the underlying idea, you can read [the CSS Tricks article on box-sizing](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/).in
```

2022-05-01 19:53 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +Now, the _actual_ space taken up by the box will be 350px wide and 150px high.
Just in case we do not want to repeat the example

```suggestion
If we assume the box has the same values as the CSS in the example above, the _actual_ space taken up by the box is now 350px wide and 150px high.
```

2022-05-03 23:34 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type affects the behavior of the box in terms of page flow and in relation to other boxes on the page. Boxes have
```suggestion
In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type refers to how the box behaves in terms of page flow and in relation to other boxes on the page. Boxes have an **inner display type** and an **outer display type**. First, we will explain what we mean by block box and inline box. We will then explain what is meant by an inner and outer display type.
```

2022-05-03 23:34 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In CSS we broadly have two types of boxes — **block boxes** and **inline boxes**. The type affects the behavior of the box in terms of page flow and in relation to other boxes on the page. Boxes have
original better describes the flow of the tutorial (we aren't starting with outer type)

2022-05-03 23:37 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +You can set the values of the {{cssxref("display")}} property to `block` or `inline`. This defines the type of box applied to an element and relates to the outer display type.
there are many other values of display

2022-05-03 23:52 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +## Aside: The inner display type
If we decide to break the page up in this new way, we need to add ## outer display type heading above (line #51)  and change this to ## inner display type (no "aside")

2022-05-03 23:53 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +You've learned above that boxes in CSS have an _outer_ display type. Boxes also have an _inner_ display type, which dictates how elements inside that box are laid out.
```suggestion
Boxes also have an _inner_ display type, which dictates how elements inside that box are laid out.
```

2022-05-04 23:28 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +You can set the values of the {{cssxref("display")}} property to `block` or `inline`. This defines the type of box applied to an element and relates to the outer display type.
I wanted to make clear what the display type is in CSS - the first time the display: x property is displayed in the article is line 80 - for flex (inner). Then, in line 91 for block. Maybe I can move it up and rephrase, see my next commit.

2022-05-04 23:41 UTC, cadamini commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +You can set the values of the {{cssxref("display")}} property to `block` or `inline`. This defines the type of box applied to an element and relates to the outer display type.
See https://github.com/mdn/content/pull/15538/commits/3b164aa5d67c9b6119475aa2cfe275b6cf26741f

2022-06-13 22:25 UTC, estelle requested changes
Thank you. Many are minor grammar changes. But, we likely should be updating this document to reflect CSS logical properties, which we should be encouraging people to use.

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- The box will extend in the inline direction to fill the space available in its container. In most cases the box will become as wide as its container, filling up 100% of the space available.
```suggestion
- The box will extend in the inline direction to fill the space available in its container. In most cases, the box will become as wide as its container, filling up 100% of the space available.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +You can change the inner display type for example by setting `display: flex;`. The element will still use the outer display type `block` but this changes the inner display type to `flex`. Any direct
```suggestion
You can change the inner display type for example by setting `display: flex;`. The element will still use the outer display type `block` but this changes the inner display type to `flex`. Any direct children of this box will become flex items and behave according to the [Flexbox](/en-US/docs/Learn/CSS/CSS_layout/Flexbox) specification.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +> **Note:** To read more about the values of display, and how boxes work in block and inline layout, take a look at the MDN guide to [Block and Inline Layout](/en-US/docs/Web/CSS/CSS_Flow_Layout/Bloc
```suggestion
> **Note:** To read more about the values of display, and how boxes work in block and inline layout, take a look at the MDN guide [Block and Inline Layout](/en-US/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow).  
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- A paragraph with a border added in CSS. The browser renders this as a block box. The paragraph starts on a new line and uses the entire available width.
```suggestion
- A paragraph with a border added in CSS. The browser renders this as a block box. The paragraph starts on a new line and extends the entire available width.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- A list, which is laid out using `display: flex`. This establishes flex layout for the items inside the container. The list itself is a block box and — like the paragraph — expands to the full conta
```suggestion
- A list, which is laid out using `display: flex`. This establishes flex layout for the children of the container, which are flex items. The list itself is a block box and — like the paragraph — expands to the full container width and breaks onto a new line.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- A block-level paragraph, inside which are two `<span>` elements. These elements would normally be `inline`, however, one of the elements has a class of block, and we have set it to `display: block`
```suggestion
- A block-level paragraph, inside which are two `<span>` elements. These elements would normally be `inline`, however, one of the elements has a class of "block" which gets set to `display: block`.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- The `<ul>` element that is set to `display: inline-flex` creates an inline box around some flex items.
```suggestion
- The `<ul>` element that is set to `display: inline-flex` creates an inline box containing some flex items.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +- **Content box**: The area where your content is displayed; size it using properties like {{cssxref("width")}} and {{cssxref("height")}}.
```suggestion
- **Content box**: The area where your content is displayed; size it using properties like  {{cssxref("inline-size")}} and {{cssxref("block-size")}} or {{cssxref("width")}} and {{cssxref("height")}}.
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +In the standard box model, if you give a box a `width` and a `height` attribute, this defines the width and height of the _content box_. Any padding and border is then added to that width and height
```suggestion
In the standard box model, if you give a box an `inline-size` and a `block-size` (or `width` and a `height`) attributes, this defines the inline-size and block-size (with and height in horizontal languages) of the _content box_. Any padding and border is then added to those dimensions to get the total size taken up by the box (see image below).
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +  width: 350px;
```suggestion
  width: 350px;
  inline-size: 350px;
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +  height: 150px;
```suggestion
  height: 150px;
  block-size: 150px;
```

2022-06-13 22:25 UTC, estelle commented on files/en-us/learn/css/building_blocks/the_box_model/index.md
> +Now, the _actual_ space taken up by the box will be 350px wide and 150px high.
```suggestion
Now, the _actual_ space taken up by the box will be 350px in the inline direction and 150px in the block direction.
```

2022-06-14 07:08 UTC, cadamini commented
> Thank you. Many are minor grammar changes. 

Thanks. Great corrections/additions 🌷 🚀 

> But, we likely should be updating this document to reflect CSS logical properties, which we should be encouraging people to use. Would you like to jump in and add properties like [border-block-start-width, border-block-end-width, border-inline-start-width, border-inline-end-width properties and border-block-width and border-inline-width shorthands](https://drafts.csswg.org/css-logical/#border-width) or should we file an issue to get this updated at a later date?

Please file an issue and schedule this update for a later date. I am not too familiar with those properties yet.

2022-06-16 22:47 UTC, estelle approved these changes
Thank you!

2022-06-16 22:50 UTC, merged

2022-06-17 22:36 UTC, slk333 commented
good job