Make Test your skills pages consistent
mdn/content pull request #15579
Opened 2022-05-01 10:38 UTC by glmvc

#### Summary

made "Test your skills!" pages of the Learn/HTML and Learn/CSS modules more consistent:
- add **tags** where they where missing / incomplete
- add **missing sidebar** in the background and borders skill test
- adapt **introduction sentences**
- adapt **note box** (under the introduction sentences) - the "However" part.
- adapt **headings** to fit the articles title and use numbers instead of written out numbers (i thought this is easier to read and also in the discourse forum easier and clearer to handle)
- adapt "Assessment or further help" sections to be uniform
- adapt the code example (interactive editor) sentences and "boxes"

#### Motivation

to keep things consistent - i have done this "consistency changes" now a few times in prs and it was always appreciated.

i made a few decisions based on how most test your skills pages (including the ones for Learn/JavaScript...) were structured and written (e.g. the boxes below the interactive editros were written most of the time in the "shorter way", but not for the Learn/CSS part)

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-02 21:36 UTC, estelle commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +The aim of this skill test is to assess whether you've understood  overflow in CSS covered in our [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content) article.
```suggestion
The aim of this skill test is to assess whether you've understood overflow in CSS covered in our [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content) article.
```

2022-05-02 21:38 UTC, estelle commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +The aim of this skill test is to assess whether you've understood overflow in CSS covered in our [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content) article.
```suggestion
The aim of this skill test is to assess whether you've understood overflow in CSS covered in [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content).
```

2022-05-02 21:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +The aim of this skill test is to assess whether you've understood our [CSS selectors](/en-US/docs/Learn/CSS/Building_blocks/Selectors) article.
```suggestion
The aim of this skill test is to assess whether you've understand [CSS selectors](/en-US/docs/Learn/CSS/Building_blocks/Selectors).
```

2022-05-02 21:40 UTC, estelle commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +The aim of this skill test is to assess whether you've understood overflow in CSS covered in our [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content) article.
Thinking a skills test is more about understanding a concept than a specific article. This suggestion may not actually be what you are looking for.

2022-05-02 21:41 UTC, estelle commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +The aim of this skill test is to assess whether you've understood our [Sizing items in CSS](/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS) article.
```suggestion
The aim of this skill test is to assess whether you understand [sizing items in CSS](/en-US/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS).
```

2022-05-02 21:42 UTC, estelle commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +This task has a box, which contains another box. Your task is to make the inner box 60% of the width of the outer box. The value of the {{cssxref("box-sizing")}} property is set to ```border-box```,
```suggestion
This task has a box, which contains another box. Your task is to make the inner box 60% of the width of the outer box. The value of the {{cssxref("box-sizing")}} property is set to `border-box`, which means that the total width includes any padding and border. You should also give the inner box padding of 10% using the width (or inline size) as the size from which that percentage is calculated.
```

2022-05-02 21:43 UTC, estelle commented on files/en-us/learn/css/building_blocks/tables_tasks/index.md
> +The aim of this skill test is to assess whether you've understood our [Styling tables](/en-US/docs/Learn/CSS/Building_blocks/Styling_tables) article.
```suggestion
The aim of this skill test is to assess whether you understand how to [style tables](/en-US/docs/Learn/CSS/Building_blocks/Styling_tables).
```

2022-05-02 21:43 UTC, estelle commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +The aim of this skill test is to assess whether you've understood our [Backgrounds and borders](/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders) article.
```suggestion
The aim of this skill test is to assess whether you understand [CSS backgrounds and borders](/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders).
```

2022-05-02 21:44 UTC, estelle commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +    - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
```suggestion
    - Details of what you have already tried and what you would like us to do, e.g. if you are stuck and need help or want an assessment.
```

2022-05-02 21:46 UTC, estelle commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +The aim of this skill test is to assess whether you've understood some of the CSS values and units covered in our [CSS Values and Units](/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) articl
```suggestion
The aim of this skill test is to assess whether you understand [CSS Values and Units](/en-US/docs/Learn/CSS/Building_blocks/Values_and_units).
```

2022-05-02 21:46 UTC, estelle commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +- The fourth should use RGB color but with the alpha channel set to ```0.2```.
```suggestion
- The fourth should use RGB color but with the alpha channel set to `0.2`.
```

2022-05-02 21:47 UTC, estelle commented on files/en-us/learn/css/building_blocks/writing_modes_tasks/index.md
> +The aim of this skill test is to assess whether you've understood writing modes and logical properties covered in our [Handling different text directions](/en-US/docs/Learn/CSS/Building_blocks/Handli
```suggestion
The aim of this skill test is to assess whether you understood how to [handle different text directions using writing modes and logical properties ](/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions).
```

2022-05-02 21:48 UTC, estelle commented on files/en-us/learn/css/css_layout/flexbox_skills/index.md
> +The aim of this skill test is to assess whether you've understood how flex items behave covered in our [Flexbox](/en-US/docs/Learn/CSS/CSS_layout/Flexbox) article. Below are four common design patter
```suggestion
The aim of this skill test is to assess whether you understand how [flex items](/en-US/docs/Learn/CSS/CSS_layout/Flexbox) behave. Below are four common design patterns which you might use Flexbox to create, your task is to build them.
```

2022-05-02 21:50 UTC, estelle commented on files/en-us/learn/css/css_layout/floats_skills/index.md
> +The aim of this skill test is to assess whether you've understood the CSS {{CSSxRef("float")}} and {{CSSxRef("clear")}} properties covered in our [Floats](/en-US/docs/Learn/CSS/CSS_layout/Floats) art
```suggestion
The aim of this skill test is to assess whether you understand CSS {{CSSxRef("float")}} and {{CSSxRef("clear")}} properties covered in [Floats](/en-US/docs/Learn/CSS/CSS_layout/Floats). You will be working through three small tasks which use different elements of the material you have just covered.
```

2022-05-02 21:52 UTC, estelle commented on files/en-us/learn/css/css_layout/multicol_skills/index.md
> +The aim of this skill test is to assess whether you've understood the CSS {{CSSxRef("column-count")}}, {{CSSxRef("column-width")}}, {{CSSxRef("column-gap")}}, {{CSSxRef("column-span")}} and {{CSSxRef
```suggestion
The aim of this skill test is to assess whether you understand [CSS multiple-column layout](/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout), including the {{CSSxRef("column-count")}}, {{CSSxRef("column-width")}}, {{CSSxRef("column-gap")}}, {{CSSxRef("column-span")}} and {{CSSxRef("column-rule")}} properties and values. You will be working through three small tasks which use different elements of the material you have just covered.
```

2022-05-02 21:52 UTC, estelle commented on files/en-us/learn/css/css_layout/position_skills/index.md
> +The aim of this skill test is to assess whether you've understood the CSS {{CSSxRef("position")}} property and values covered in our [Positioning](/en-US/docs/Learn/CSS/CSS_layout/Positioning) articl
```suggestion
The aim of this skill test is to assess whether you understand the CSS [Positioning](/en-US/docs/Learn/CSS/CSS_layout/Positioning). You will be working through two small tasks which use different elements of the material you have just covered.
```

2022-05-02 21:53 UTC, estelle reviewed
Lots of comments, but they are all minor edits that you may or may not agree with. Thank you!!!

2022-05-03 20:55 UTC, dipikabh requested changes
Thank you @glmvc for your efforts to keep the content consistent! Just like @estelle, I have added multiple comments, all involving minor edits.

For simplicity, consistency, and maintainability, I've suggested renaming all headings in "Test your skills" to "Task 1", "Task 2", and so on. The title of the page tells us what the task is about.

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/box_model_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for The box model 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for box model skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/box_model_tasks/index.md
> +The aim of this skill test is to assess whether you've understood our [CSS box model](/en-US/docs/Learn/CSS/Building_blocks/The_box_model) article.
```suggestion
The aim of this skill test is to assess whether you understand [CSS box model](/en-US/docs/Learn/CSS/Building_blocks/The_box_model).
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for The Cascade skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for the cascade skill test".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/images_tasks/index.md
> +## Images and form elements 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_tasks/index.md
> +The aim of this skill test is to assess whether you've understood universal property values for controlling inheritance covered in our [Cascade and inheritance](/en-US/docs/Learn/CSS/Building_blocks/
```suggestion
The aim of this skill test is to assess whether you understand universal property values for [controlling inheritance](/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance).
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_tasks/index.md
>      - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
```suggestion
    - Details of what you have already tried and what you would like us to do if you're stuck and need help or want an assessment.
```
The edits here would need to be replicated on other pages as well.

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/images_tasks/index.md
> +## Images and form elements 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/images_tasks/index.md
> +- Use attribute selectors to target the search field and button inside ```.myform```.
```suggestion
- Use attribute selectors to target the search field and button inside `.myform`.
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/images_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Images and form elements 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for images and form elements skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +## Overflow 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +## Overflow 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Overflow 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for overflow skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +## Selectors 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +## Selectors 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +## Selectors 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +## Selectors 4
```suggestion
## Task 4
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
>  In this task try the following:
```suggestion
In this task, try the following:
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +## Selectors 5
```suggestion
## Task 5
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/selectors_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Selectors 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for selectors skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +## Sizing 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +## Sizing 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +## Sizing 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Sizing 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for sizing skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/tables_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Tables skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for the tables skill test".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +## Backgrounds and borders 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +## Backgrounds and borders 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
>  In this task we want you to add background images, a border, and some other styling to a decorative box:
```suggestion
In this task, we want you to add background images, a border, and some other styling to a decorative box:
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +- Give the box a 5px lightblue border, and round the top left corner 20px and the bottom right corner 40px.
```suggestion
- Give the box a 5px lightblue border and round the top left corner 20px and the bottom right corner 40px.
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +## Values and units 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +## Values and units 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +In this task you need to set the size of various items of text:
```suggestion
In this task, you need to set the size of various items of text, as described below:
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +## Values and units 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
>  In this task you need to move the background image so that it is centered horizontally, and 20% from the top of the box.
```suggestion
In this task, you need to move the background image so that it is centered horizontally and is 20% from the top of the box.
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/values_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Values and units 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for values and units skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/writing_modes_tasks/index.md
> +## Writing modes and logical properties 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/writing_modes_tasks/index.md
> +## Writing modes and logical properties 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/writing_modes_tasks/index.md
> +## Writing modes and logical properties 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/writing_modes_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for Writing modes and logical properties 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for writing modes and logical properties skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/floats_skills/index.md
> +## Floats 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/floats_skills/index.md
> +## Floats 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/floats_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Floats 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for floats skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +## Grid 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +## Grid 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
>  In this example we already have a grid defined. By editing the CSS rules for the two child elements, cause them to span over several grid tracks each; the second item should overlay the first as in t
```suggestion
In this example, we already have a grid defined. By editing the CSS rules for the two child elements, cause them to span over several grid tracks each; the second item should overlay the first as in the image below.
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +## Grid 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +## Grid and Flexbox 4
```suggestion
## Task 4
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Grid 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for grid skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/multicol_skills/index.md
> +## Multicol 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/multicol_skills/index.md
> +## Multicol 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/multicol_skills/index.md
> +## Multicol 3
```suggestion
## Task 3
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/multicol_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Multicol 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for multicol skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/position_skills/index.md
> +## Positioning 1
```suggestion
## Task 1
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/position_skills/index.md
> +## Positioning 2
```suggestion
## Task 2
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/position_skills/index.md
>  In the below example if you scroll the box the sidebar scrolls with the content. Change it so that the sidebar stays in place and only the content scrolls.
```suggestion
In the example below, if you scroll the box the sidebar scrolls with the content. Change it so that the sidebar stays in place and only the content scrolls.
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/position_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Positioning 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for positioning skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/css/css_layout/rwd_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Responsive web design and media queries skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for responsive web design and media queries skill test".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/test_your_skills_colon__html_images/index.md
> +    - A descriptive title such as "Assessment wanted for HTML images 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for HTML images skill test 1".
```

2022-05-03 20:55 UTC, dipikabh commented on files/en-us/learn/html/multimedia_and_embedding/video_and_audio_content/test_your_skills_colon__multimedia_and_embedding/index.md
> +    - A descriptive title such as "Assessment wanted for Multimedia and embedding 1 skill test".
```suggestion
    - A descriptive title such as "Assessment wanted for multimedia and embedding skill test 1".
```

2022-05-04 17:46 UTC, glmvc commented on files/en-us/learn/css/building_blocks/sizing_tasks/index.md
> +This task has a box, which contains another box. Your task is to make the inner box 60% of the width of the outer box. The value of the {{cssxref("box-sizing")}} property is set to ```border-box```,
oh, I wanted to go trough and correct that because I saw it somewhere else - thank you for this catch!

2022-05-04 17:55 UTC, glmvc commented on files/en-us/learn/css/building_blocks/overflow_tasks/index.md
> +The aim of this skill test is to assess whether you've understood overflow in CSS covered in our [Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content) article.
I also thought about the intro sentences for a longer time, because they varied a lot....

I made the decision to change it this way, because in later modules like Learn/JavaScript for example, it was often done this way.

But I also think it's a lot better that way.

2022-05-04 17:58 UTC, glmvc commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +    - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
Should this change be adapted to all "Assessment and further help" sections?

2022-05-04 18:06 UTC, glmvc commented on files/en-us/learn/css/building_blocks/tables_tasks/index.md
> +Our finished table will look like the image below. There are a number of ways that you can achieve this, but I suggest following similar patterns as used in the tutorial to do the following things:
nice catch 👍

2022-05-04 18:45 UTC, glmvc commented on files/en-us/learn/css/building_blocks/test_your_skills_backgrounds_and_borders/index.md
> +    - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
I think your suggestion is better, but on second thought, I think we should leave it as it is for now.

I have once made such a unification for the assessments in Learn/HTML and Learn/CSS and there is also everywhere this variant....
So we would have to change it everywhere (in the assessments & test your skills).
I can of course do it if wanted, but I would do it in a separate pr and look more closely through this section again and possibly improve other things.

What do you think?

2022-05-04 18:49 UTC, glmvc commented on files/en-us/learn/css/building_blocks/cascade_tasks/index.md
>      - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
As I already mentioned to @estelle:

>I think your suggestion is better, but on second thought, I think we should leave it as it is for now.
>
>I have once made such a unification for the assessments in Learn/HTML and Learn/CSS and there is also everywhere this variant....
>So we would have to change it everywhere (in the assessments & test your skills).
>I can of course do it if wanted, but I would do it in a separate pr and look more closely through this section again and possibly improve other things.
>
>What do you think?

2022-05-04 20:39 UTC, glmvc commented
@estelle, @dipikabh,
Thank you for reviewing and helping me out - I am glad that someone helps me and makes the changes even better :)
I left a few **comments** on the suggestions where I wasn't quite sure.

I made a few more "consistent changes" based on the suggestions and because I went back through all the "test your skills" pages (to be exact in Learn/HTML and Learn/CSS, where the CSS layout modul is still missing, which I will make soon), and I have did the tests too to see if they are working as intended.
I hope these additional adjustments/changes fit for you.

ps: I'm sorry for the numerous commits, since I am quite new to git and github, I found out a bit later that you can add the suggestions to the batch. 🤯

2022-05-05 08:40 UTC, dipikabh commented on files/en-us/learn/css/css_layout/rwd_skills/index.md
> +    - A descriptive title such as "Assessment wanted for Responsive web design and media queries skill test".
I don't think capitalization is necessary while bringing it up in chat or discourse. Other than that, I think it is the same as the new title.

2022-05-05 08:59 UTC, dipikabh requested changes

2022-05-05 08:59 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/box_model_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for The box model skill test 1".
```suggestion
    - A descriptive title such as "Assessment wanted for the box model skill test 1".
```

2022-05-05 08:59 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/box_model_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for The box model skill test 1".
I think you left out this lower-case change and all the other similar ones pending my response. I feel we should not capitalize in the middle of the sentence in such instances and it would still be understood what module is being talked about. The sentence 'descriptive title such as' is only a suggestion/example and people could refer to it in their style (e.g., I might refer to this skill test in the discourse forum by enclosing the module title in quotes.) Hope that clarifies my suggestion.

2022-05-05 08:59 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_tasks/index.md
>      - Details of what you have already tried, and what you would like us to do, e.g. if you are stuck and need help, or want an assessment.
Great idea to open a separate PR 👍

2022-05-05 08:59 UTC, dipikabh commented on files/en-us/learn/css/css_layout/grid_skills/index.md
> +The aim of this skill test is to assess whether you've understood how a grid and grid items behave covered in our [Grids](/en-US/docs/Learn/CSS/CSS_layout/Grids) article. You will be working through
```suggestion
The aim of this skill test is to assess whether you understand how a [grid](/en-US/docs/Learn/CSS/CSS_layout/Grids) and grid items behave. You will be working through three small tasks that use different elements of the material you have just covered.

2022-05-06 19:00 UTC, glmvc commented on files/en-us/learn/css/building_blocks/box_model_tasks/index.md
> +    - A descriptive title such as "Assessment wanted for The box model skill test 1".
alright, thank you! I agree

2022-05-07 15:21 UTC, glmvc commented
Hi @dipikabh, I also improved the contrast in some interactive examples like it's mentioned in issue [#2054](https://github.com/mdn/interactive-examples/issues/2054)
Here I've changed the images to fit the improved contrast values in mdn/css-examples.

**important**: note that pr [#74](https://github.com/mdn/css-examples/pull/74) and pr [#75](https://github.com/mdn/css-examples/pull/75)  have to be ideally merged at the same time I think?

2022-06-03 17:50 UTC, glmvc commented
Hey @dipikabh,

I've resolved the failed checks. (1 image was not compressed)

This pr should ideally be merged at the same time with the following prs from mdn/css-examples:
- [Improve contrast of interactive examples](https://github.com/mdn/css-examples/pull/75)
- [Best practice value for alpha channel](https://github.com/mdn/css-examples/pull/74)

... because here are changes for them...

Sorry for the "crossover" with mdn/css-examples - afterwards this would have been something for a seperate pr 🤦‍♂️ 
Are you able to merge in mdn/css-examples? Or do we need to tell someone who can do it?

> Note this pr ([Make mailto anchor work inside iframe](https://github.com/mdn/learning-area/pull/495)) which is also pending, but there is **no change** here in this pr yet (because I'm waiting for suggestions).
> But it should not hold up this pr any longer, unless you say it is requested because it is only a very small change.

2022-06-07 16:48 UTC, dipikabh approved these changes
Thank you so much @glmvc for your work on this!

2022-06-07 16:49 UTC, merged

2022-06-08 17:59 UTC, glmvc commented
@dipikabh you're welcome :) thank you for helping out! 🎉