Adding Interface HTMLPortalElement plus subpages.
mdn/content pull request #1560
Opened 2021-01-21 11:33 UTC by rachelandrew

Reviewer @jpmedley 

Here is a pass at HTMLPortalElement, as mentioned there are a few complexities with this.

- The [spec](https://wicg.github.io/portals/) is behind the [explainer](https://github.com/WICG/portals#readme) so I've been working between the two to figure out what needs to be documented.
- We are missing BCD awaiting your thoughts on https://github.com/mdn/browser-compat-data/pull/8680
- As mentioned in my earlier email I think there are bits that need adding elsewhere. Glossary entries for things like Portal Browsing Context, which is a new thing. An addition to window `window.portalHost`.

Have a look, there are other Interfaces for Portals to document. Once we are happy with this one and any additions we need to make elsewhere for it to make sense, I'll do the others.

2021-01-25 19:59 UTC, jpmedley requested changes

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/onmessage/index.html
> +<p class="summary">The <strong><code>onmessage</code></strong> EventHandler of the {{domxref("HTMLPortalElement")}} interface is an <a href="/en-US/docs/Web/Guide/Events/Event_handlers">Event Handler
Is this the standard language we're using? I'd suggest something like this instead. Other paragraphs would need to match.

>The  `onmessage` event handler is a callback that is passed a {{domxref('Event')}} when a message is received from the embedding page.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/postmessage/index.html
> +<p>All pages will have a <code>window.portalHost</code> property. This property is non-null if the page is in a portal.</p>
There should be a page for this property. I can be in a separate PR.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/postmessage/index.html
> +    <p>Note: The <code>postMessage()</code> method only functions if the <code>portalHost</code> and portaled content are same origin, in order to prevent cross-site tracking. If the portaled content
```suggestion
    <p>Note:  To prevent cross-site tracking, the <code>postMessage()</code> method only functions if the <code>portalHost</code> and portaled content are on the same origin. If the portaled content is cross-origin no <code>message</code> events will be sent to <code>window.portalHost</code> and <code>window.portalHost.postMessage()</code> will not deliver any message.</p>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/postmessage/index.html
> +<p>The <a href="https://github.com/WICG/portals/tree/master/demos/portal-embed-demo">Portal Embed Demo</a> attached to the specification uses <code>postMessage</code> to pass information about the pl
```suggestion
<p>The <a href="https://github.com/WICG/portals/tree/master/demos/portal-embed-demo">Portal Embed Demo</a> attached to the specification uses <code>postMessage()</code> to pass information about the play state of the embedded content to the portal.</p>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/index.html
> +  <dd>A {{domxref("DOMString")}} that reflects the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute indicating which referrer policy to use when fetching the linked resource.</dd>
```suggestion
  <dd>A {{domxref("DOMString")}} that returns or sets the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute indicating which referrer policy to use when fetching the linked resource.</dd>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/index.html
> +  <dd>A {{domxref("USVString")}} that reflects the {{htmlattrxref("src", "portal")}} HTML attribute, containing the address of the content to be embedded.</dd>
```suggestion
  <dd>A {{domxref("USVString")}} that returns or sets the {{htmlattrxref("src", "portal")}} HTML attribute, containing the address of the content to be embedded.</dd>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/index.html
> +  <dd>Fired when a message is received by the object, and no exception is thrown.</dd>
As above, please rewrite to indicate that an `Event` object is passed.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/index.html
> +  <dd>Fired when a message is received by the object, but an exception is thrown.</dd>
Same here.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/onmessage/index.html
> +<p>The event fires when the embedding page sends a message to the portaled content, and no exception is thrown.</p>
If you take the previous suggestion, this paragraph wouldn't be needed.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/postmessage/index.html
> +<p class="summary">The <strong><code>postMessage()</code></strong> method of the {{domxref("HTMLPortalElement")}} interface enables messaging between the page embedding the {{htmlelement("portal")}}
```suggestion
<p class="summary">The <strong><code>postMessage()</code></strong> method of the {{domxref("HTMLPortalElement")}} interface sends messages from an embedding page to the page in a contained {{htmlelement("portal")}} element.
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/postmessage/index.html
> +<p class="summary">The <strong><code>postMessage()</code></strong> method of the {{domxref("HTMLPortalElement")}} interface enables messaging between the page embedding the {{htmlelement("portal")}}
I think the structure "sends...from...to" is a little clearer about what's happening.

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/referrerpolicy/index.html
> +<p>A {{domxref("DOMString")}} that reflects the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute indicating which referrer policy to use when fetching the linked resource. This is limited
```suggestion
<p>A {{domxref("DOMString")}} that returns or sets the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute indicating which referrer policy to use when fetching the linked resource. This is limited to one of the following values:</p>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/referrerpolicy/index.html
> +  <dd>Only send the origin of the document as the referrer in all cases. The document <code>https://example.com/page.html</code> will send the referrer <code>https://example.com/</code>.</dd>
```suggestion
  <dd>Send the origin of the document as the referrer in all cases. For example, the document <code>https://example.com/page.html</code> will send the referrer <code>https://example.com/</code>.</dd>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/src/index.html
> +<p class="summary">The <strong><code>src</code></strong> property of the {{domxref("HTMLPortalElement")}} interface reflects the {{htmlattrxref("src", "portal")}} HTML attribute. This contains the ad
```suggestion
<p class="summary">The <strong><code>src</code></strong> property of the {{domxref("HTMLPortalElement")}} interface returns or sets the {{htmlattrxref("src", "portal")}} HTML attribute. This contains the address of the content to be embedded.</p>
```

2021-01-25 19:59 UTC, jpmedley commented on files/en-us/web/api/htmlportalelement/referrerpolicy/index.html
> +<p class="summary">The <strong><code>referrerPolicy</code></strong> property of the {{domxref("HTMLPortalElement")}} interface reflects the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute
```suggestion
<p class="summary">The <strong><code>referrerPolicy</code></strong> property of the {{domxref("HTMLPortalElement")}} interface returns or sets the {{htmlattrxref("referrerPolicy", "portal")}} HTML attribute.</p>
```

2021-05-26 06:08 UTC, sideshowbarker commented
@rachelandrew This PR seems to be waiting on you to commit some review suggestions?

2021-05-26 06:23 UTC, rachelandrew commented
No it's not, it's on hold because priorities changed and so the functionality isn't in Chrome yet.

2021-09-13 11:30 UTC, Elchi3 commented
I think we should close this. It can be inspiration for a new PR some day but this has not aged well for a few aspects:

- Not in markdown
- Uses reference page style that is quite outdated by now (BCD not in frontmatter, old spec sections, old syntax blocks, ...)

2021-09-13 17:47 UTC, jpmedley commented
This appears to be stalled in Chromium development. I agree with closing it.

2021-09-15 05:44 UTC, closed without merging