cssFloat
mdn/content pull request #1567
Opened 2021-01-21 14:07 UTC by rachelandrew

Wrapping up my work on https://github.com/mdn/content/issues/344 this is the missing page for `cssFloat`.

Spec: https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-cssfloat

Reviewer: @jpmedley

2021-01-25 20:44 UTC, jpmedley requested changes

2021-01-25 20:44 UTC, jpmedley commented on files/en-us/web/api/cssstyledeclaration/index.html
> + <li>Via {{DOMxRef("ElementCSSInlineStyle.style")}}, which deals with the inline styles of a single element (e.g., <code>&lt;div style="..."&gt;</code>).</li>
This appears to be an interface mixin, meaning it would be accessed through `HTMLElement` and no coder would ever know about `ElementCSSInlineStyle`.  It also appears that Chrome currently doesn't use the mixin to attach this to `HTMLElement`. It's party of that class's IDL.

2021-01-26 09:00 UTC, rachelandrew commented on files/en-us/web/api/cssstyledeclaration/index.html
> + <li>Via {{DOMxRef("ElementCSSInlineStyle.style")}}, which deals with the inline styles of a single element (e.g., <code>&lt;div style="..."&gt;</code>).</li>
Fixable Flaws is doing this because there is a redirect in place for this. I'm not sure of the best approach to take.

2021-01-27 18:59 UTC, jpmedley commented on files/en-us/web/api/cssstyledeclaration/index.html
> + <li>Via {{DOMxRef("ElementCSSInlineStyle.style")}}, which deals with the inline styles of a single element (e.g., <code>&lt;div style="..."&gt;</code>).</li>
I guess leave it for now.

2021-01-27 18:59 UTC, jpmedley approved these changes

2021-01-27 18:59 UTC, merged