MV3 Content security policy
mdn/content pull request #15704
Opened 2022-05-05 03:08 UTC by rebloor

#### Summary
Updates to document the Manifest V3 changes to the content_security_policy manifest key along with related changes to the content security policy article.

#### Metadata

This PR…

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-05 13:33 UTC, MrBrain295 commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +Allow remote scripts from "https\://example.com":
```suggestion
Allow remote scripts from "https://example.com":
```

2022-05-11 19:13 UTC, mixedpuppy requested changes

2022-05-11 19:13 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +    </tr>
remove

2022-05-11 19:13 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +  "content_scripts": "script-src 'self' https://example.com; object-src 'self'"
change to an extension_page example

2022-05-11 19:13 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +  "content_scripts": "default-src 'self'"
change to extension_page

2022-05-13 00:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +    </tr>
Can I clarify, you made the content_script row?

2022-05-13 01:03 UTC, mixedpuppy requested changes

2022-05-13 01:03 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +    </tr>
We added it at one point, then later removed it (which I forgot). Same with isolated_world

2022-05-13 02:22 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +      </td>
Done

2022-05-13 02:23 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +  "content_scripts": "default-src 'self'"
Done

2022-05-13 17:27 UTC, mixedpuppy approved these changes

2022-05-13 18:05 UTC, merged