Add BackgroundFetchManager documents.
mdn/content pull request #1571
Opened 2021-01-21 15:21 UTC by jpmedley

This is a step in addressing #197

2021-01-25 15:59 UTC, Rumyra commented
I'm having a read through now @jpmedley - apologies for the delay 🙈

2021-01-25 16:56 UTC, Rumyra requested changes
Reviewed 🙌

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +<p class="summary">The <strong><code>BackgroundFetchManager</code></strong> interface of the {{domxref('Background Fetch','','',' ')}} API is a map where the keys are background fetch IDs and the val
Should this be Background Fetch API?

```suggest
<p class="summary">The <strong><code>BackgroundFetchManager</code></strong> interface of the {{domxref('Background Fetch API','','',' ')}} is a map where the keys are background fetch IDs and the values are {{domxref("BackgroundFetchRegistration")}} objects.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +my code block</pre>
```suggest
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +my code block</pre>
Does that remove those lines 🤔 - that's what I was aiming for

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +<p>The example below shows how to get an instance of {{domxref("BackgroundFetchManager")}} from a {{domxreff("ServiceWorkerRegistration")}} object and calls <code>fetch()</code> to download a video i
```suggest
<p>The example below shows how to get an instance of {{domxref("BackgroundFetchManager")}} from a {{domxref("ServiceWorkerRegistration")}} object and calls <code>fetch()</code> to download a video in the background.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/fetch/index.html
> +<p>A {{jsxreff("Promise")}} that resolves with a {{domxref("BackgroundFetchRegistration")}} object.</p>
```suggest
<p>A {{jsxref("Promise")}} that resolves with a {{domxref("BackgroundFetchRegistration")}} object.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/fetch/index.html
> +<p>The following examples shows how to use `fetch()` to create a {{domxref("BackgroundFetchRegistration")}}. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetc
You know what - I did this just a couple of days ago - one day we will have back ticks and I will be happy 😆 

``` suggest
<p>The following examples shows how to use <code>fetch()</code> to create a {{domxref("BackgroundFetchRegistration")}}. With an active {{domxref('ServiceWorker', 'service worker')}}, use the {{domxref('ServiceWorkerRegistration.backgroundFetch')}} property to access the <code>BackgroundFetchManager</code> object and call its <code>fetch()</code> method.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +<p>A {{jsxref("Promise")}} that resolves with resolves with a {{domxref("BackgroundFetchRegistration")}} or {{jsxref("undeffined")}}.</p>
```suggest
<p>A {{jsxref("Promise")}} that resolves with a {{domxref("BackgroundFetchRegistration")}} or {{jsxref("undefined")}}.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +<p>The following examples shows how to use `get()` to retrieve a {{domxref("BackgroundFetchRegistration")}}. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetc
```suggest
<p>The following examples shows how to use <code>get()</code> to retrieve a {{domxref("BackgroundFetchRegistration")}}. With an active {{domxref('ServiceWorker', 'service worker')}}, use the {{domxref('ServiceWorkerRegistration.backgroundFetch')}} to access the <code>BackgroundFetchManager</code> object and call its <code>get()</code> method.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +false
Remove this line

```suggest
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +None.
```suggest
<p>None.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +None.
```suggest
<p>None.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +<p>A {{jsxref("Promise")}} that resolves with an array off strings.</p>
```suggest
<p>A {{jsxref("Promise")}} that resolves with an {{jsxref('Array')}} of {{jsxref('String', 'strings')}}.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +<p>The following examples shows how to retrieve the IDs of all registered background fetches. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetch')}} property
```suggest
<p>The following example shows how to retrieve the IDs of all registered background fetches. With an active {{domxref('ServiceWorker', 'service worker')}}, use the {{domxref('ServiceWorkerRegistration.backgroundFetch')}} property to access the <code>BackgroundFetchManager</code> object and call its <code>get()</code> method.</p>
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +</ul>
Remove

```suggest
```

2021-01-25 16:56 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +false
Remove

```suggest
```

2021-01-27 15:39 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/fetch/index.html
> +<p>A {{jsxreff("Promise")}} that resolves with a {{domxref("BackgroundFetchRegistration")}} object.</p>
I'm not spotting the difference between what I have and what you suggested.

2021-01-27 15:49 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/fetch/index.html
> +<p>The following examples shows how to use `fetch()` to create a {{domxref("BackgroundFetchRegistration")}}. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetc
Done.

2021-01-27 15:50 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +<p>A {{jsxref("Promise")}} that resolves with resolves with a {{domxref("BackgroundFetchRegistration")}} or {{jsxref("undeffined")}}.</p>
Fixed.

2021-01-27 15:55 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +<p>The following examples shows how to use `get()` to retrieve a {{domxref("BackgroundFetchRegistration")}}. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetc
Fixed.

2021-01-27 15:56 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/get/index.html
> +false
Done.

2021-01-27 15:58 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +<p>A {{jsxref("Promise")}} that resolves with an array off strings.</p>
Done.

2021-01-27 16:02 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +<p>The following examples shows how to retrieve the IDs of all registered background fetches. With an active service worker, use the {{domxref('ServiceWorkerRegistration.backgroundFetch')}} property
Done.

2021-01-27 16:02 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +</ul>
Done.

2021-01-27 16:02 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/getids/index.html
> +false
Done.

2021-01-27 16:12 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +<p class="summary">The <strong><code>BackgroundFetchManager</code></strong> interface of the {{domxref('Background Fetch','','',' ')}} API is a map where the keys are background fetch IDs and the val
Fixed.

2021-01-27 16:14 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/fetch/index.html
> +<p>A {{jsxreff("Promise")}} that resolves with a {{domxref("BackgroundFetchRegistration")}} object.</p>
Fixed.

2021-01-27 16:16 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +<p>The example below shows how to get an instance of {{domxref("BackgroundFetchManager")}} from a {{domxreff("ServiceWorkerRegistration")}} object and calls <code>fetch()</code> to download a video i
Fixed.

2021-01-27 16:19 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +my code block</pre>
The suggestion button is here:
![image](https://user-images.githubusercontent.com/8204171/106020176-539be600-6078-11eb-83f5-9d2f8f1e0b93.png)

2021-01-27 16:29 UTC, jpmedley commented
>I'm having a read through now @jpmedley - apologies for the delay 🙈

I'm not really in a place to criticize right now.

Please take another look.

2021-01-29 11:52 UTC, Rumyra commented on files/en-us/web/api/backgroundfetchmanager/index.html
> +my code block</pre>
I've been using the syntax - but probably the button may have helped here

2021-01-29 11:54 UTC, Rumyra approved these changes

2021-01-29 11:54 UTC, merged