follow-up of https://github.com/mdn/yari/pull/6183 - Node version bump - GH Actions failing
mdn/content pull request #15820
Opened 2022-05-09 14:35 UTC by SphinxKnight

#### Summary
GitHub actions seem to fail because of Node version prerequisite. This intends to follow https://github.com/mdn/yari/pull/6183

#### Motivation

https://github.com/mdn/content/runs/6353422641?check_suite_focus=true

#### Supporting details

https://github.com/mdn/content/runs/6353422641?check_suite_focus=true

#### Related issues

Not an issue but https://github.com/mdn/translated-content/pull/5520

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

None of the above: CI / pipeline / tooling related PR

2022-05-09 16:57 UTC, nschonni commented
I'd probably suggest jumping to Node 16, since that is the latest LTS release

2022-05-09 17:13 UTC, SphinxKnight commented
> I'd probably suggest jumping to Node 16, since that is the latest LTS release

The intent is to be on par with https://github.com/mdn/yari/pull/6183

2022-05-09 18:41 UTC, caugner approved these changes

2022-05-11 08:19 UTC, Guyzeroth approved these changes

2022-05-11 08:39 UTC, caugner requested changes
Node version should also be updated here:

- [package.json](https://github.com/mdn/content/blob/d03e90a1bf415f4c0ff2ebc6b4f6fcec6530e517/package.json#L6-L8)
- [README.md](https://github.com/mdn/content/blob/d03e90a1bf415f4c0ff2ebc6b4f6fcec6530e517/README.md?plain=1#L75-L76)

2022-05-13 07:13 UTC, teoli2003 commented
I think this can be closed now. Reopen if I'm mistaken.

2022-05-13 07:13 UTC, closed without merging