Clarify "Converting mistakes into errors" example
mdn/content pull request #15873
Opened 2022-05-10 16:03 UTC by Cfeusier

#### Summary
I updated the example of how strict mode handles 'accidental' global variable initialization. The previous example mentioned a 'misspelled variable,' but there was none present in the example. This PR _adds_ a variable declaration that is then misspelled to generate the strict mode error, which clarifies the example.

#### Motivation
These changes clarify the code example. Now, the example matches the content in the relevant paragraph.

#### Supporting details
None

#### Related issues
N/A

#### Metadata
This PR…
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

Thanks for your awesome resources!

2022-05-10 18:02 UTC, MrBrain295 reviewed
`var` is being gradually removed and should be replaced with `const` or `let`.

2022-05-10 22:33 UTC, Cfeusier commented
@MrBrain295 I changed `var` to `let`, since the `const` would error if declared without initialization.

2022-05-11 02:35 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/strict_mode/index.md
> +                      // misspelling of variable name
The missing "a" is not that apparent. Readers may struggle to spot the bug.
```suggestion
                      // misspelling of "Variable" word
```

2022-05-11 02:46 UTC, Cfeusier commented on files/en-us/web/javascript/reference/strict_mode/index.md
> +                      // misspelling of variable name
@OnkarRuikar agreed. 

`// misspelling of "mistypeVariable"` would be even more explicit? Let me know what you think and I'll commit your suggestion.

2022-05-11 03:09 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/strict_mode/index.md
> +                      // misspelling of variable name
I think pinpointing "Variable" would be to the point.

2022-05-11 05:54 UTC, teoli2003 commented on files/en-us/web/javascript/reference/strict_mode/index.md
> +                      // misspelling of "Variable" word
```suggestion
                      // misspelling of "mystypeVariable" (lack of an "a")
```

2022-05-11 05:55 UTC, teoli2003 requested changes
This is much better! I had to read it several times to  understand it, so I think we should be more explicit.

2022-05-11 14:35 UTC, Cfeusier commented
I integrated the suggestion from @teoli2003 -- much clearer now. Thanks!

2022-05-11 14:43 UTC, teoli2003 approved these changes
👍

2022-05-11 14:45 UTC, merged

2022-05-11 14:45 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: