Fix extra semicolon breaks replaceSync example
mdn/content pull request #15888
Opened 2022-05-10 23:55 UTC by whaaaley

#### Summary

Just removing a semicolon that breaks replaceSync. The second rule won't get parsed because of the semicolon.

#### Motivation

Testing out CSSOM api. Example didn't work. Upon further investigation the CSS was incorrect.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-10 23:58 UTC, whaaaley commented
Here's some screenshots just for some proof.

With semicolon:
![image](https://user-images.githubusercontent.com/7419947/167743106-63539ca1-bb21-4965-99b4-c3c9295ecf7e.png)

Without:
![image](https://user-images.githubusercontent.com/7419947/167743138-9d58f960-dbdd-428d-854f-2378412da342.png)

2022-05-11 02:08 UTC, OnkarRuikar commented
I think we need to update [cssstylesheet/replace/index.md:44](https://cs.github.com/mdn/content/blob/216626229a0a5ae5e4f810148a89976caf363dd9/files/en-us/web/api/cssstylesheet/replace/index.md#L44) and [cssstylesheet/replace/index.md:49](https://cs.github.com/mdn/content/blob/216626229a0a5ae5e4f810148a89976caf363dd9/files/en-us/web/api/cssstylesheet/replace/index.md#L49) as well.

2022-05-11 04:53 UTC, wbamberg requested changes
Thank you for the PR, @whaaaley ! I had a couple of comments, and as @OnkarRuikar  says, it would be great to fix `replace()` too.

2022-05-11 04:53 UTC, wbamberg commented on files/en-us/web/api/cssstylesheet/replacesync/index.md
>  let stylesheet = new CSSStyleSheet();
While you are here, this could be `const`.

2022-05-11 04:53 UTC, wbamberg commented on files/en-us/web/api/cssstylesheet/replacesync/index.md
> +stylesheet.replaceSync('body { font-size: 1.4em } p { color: red; }');
```suggestion
stylesheet.replaceSync('body { font-size: 1.4em; } p { color: red; }');
```

?

2022-05-11 13:22 UTC, whaaaley commented on files/en-us/web/api/cssstylesheet/replacesync/index.md
> +stylesheet.replaceSync('body { font-size: 1.4em } p { color: red; }');
👍

2022-05-11 14:08 UTC, wbamberg approved these changes
👍 thank you @whaaaley !

2022-05-11 14:12 UTC, merged