Update File code examples
mdn/content pull request #15909
Opened 2022-05-11 13:06 UTC by alattalatta

#### Summary
Updates `File` interface properties' code examples.

#### Motivation
Tried to use newer JavaScript language features including `const`, arrow functions, and `for...of` loops.

Changed examples using `alert()` and `console.log()` to be more "interactive" with `{{EmbedLiveSample}}`.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-11 20:07 UTC, wbamberg requested changes
Thank you @alattalatta, this looks great! I had a few comments.

2022-05-11 20:07 UTC, wbamberg commented on files/en-us/web/api/file/name/index.md
> +  <ul id="output"></ul>
If you select more than 2 files, then the whole iframe gets a scrollbar, which is quite ugly.

It would be better I think to:

- make the whole example a bit taller
- with CSS, give the ul something like:
  ```css
  ul {
    height: 100px;
    overflow: scroll;
  }

...maybe?

2022-05-11 20:07 UTC, wbamberg commented on files/en-us/web/api/file/type/index.md
> +document.getElementById('filepicker').addEventListener('change', (event) => {
```suggestion
const picker = document.getElementById('filepicker');
picker.addEventListener('change', event => {
```

(as before)

2022-05-11 20:07 UTC, wbamberg commented on files/en-us/web/api/file/webkitrelativepath/index.md
> +document.getElementById('filepicker').addEventListener('change', (event) => {
```suggestion
const picker = document.getElementById('filepicker');
picker.addEventListener('change', event => {
```

2022-05-12 14:01 UTC, alattalatta commented on files/en-us/web/api/file/name/index.md
> +  <ul id="output"></ul>
Hm, strange, for me it takes 4 or more files. But I agree with your direction.

In that case, would it be better to apply `overflow: scroll` to `#output`s of other examples as well?

2022-05-12 17:23 UTC, wbamberg approved these changes
This doesn't make the output scroll, but I'd be happy to add that in a follow-up if you think it is worth doing.

Otherwise it's definitely much better than what we had before, so 👍 . Thank you @alattalatta !

2022-05-12 17:23 UTC, merged