New page: important
mdn/content pull request #15970
Opened 2022-05-12 22:24 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-13 05:14 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +title: important
Drive-by comment:

Shouldn't we add the bang to the title? `!important`

2022-05-17 01:11 UTC, estelle commented on files/en-us/web/css/important/index.md
> +title: important
i was going to ask "how do you do that". If I include the ! I get an error.

Need to know:
* which, if any,  {{}} should be included for side nav.
* is there a way to change the URL and title to !important?

2022-05-17 01:26 UTC, hamishwillee commented on files/en-us/web/css/important/index.md
> +title: important
@estelle You might try quoting the title (untested): `title: '!important'`

No idea about the url.

2022-05-17 08:21 UTC, OnkarRuikar commented on files/en-us/web/css/important/index.md
> +When it comes to important declarations, the [cascade origin and layer orders](/en-US/docs/Web/CSS/Cascade) are reversed.  By default, declarations in an author (web developer) style sheets override
```suggestion
When it comes to important declarations, the [cascade origin and layer orders](/en-US/docs/Web/CSS/Cascade) are reversed. By default, declarations in a website author's style sheets override declarations in a user’s style sheet, which override declarations in the user-agent’s default style sheet.
```

2022-05-17 08:23 UTC, OnkarRuikar commented on files/en-us/web/css/important/index.md
> +title: important
> change the URL to !important

`!` is a valid character in URLs and file names

2022-05-17 18:03 UTC, estelle commented on files/en-us/web/css/important/index.md
> +title: important
```suggestion
title: '!important'
```

2022-05-18 06:38 UTC, teoli2003 requested changes
I learned a lot reading this. Amazing work. I found some sentences difficult to understand, at least for a non-native speaker, so I have tried to shorten them and to use a simpler grammar when possible.

I probably added some new grammar errors, so you'll likely need an extra pass.

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +The important flag, comprised of a `!` delimiter and `important` keyword, when added to a declaration in a selector block, makes the declaration an important declaration.
```suggestion
A `!` delimiter followed by the `important` keyword sets the **important** flag on a declaration. The `!important` flag alters the rules selecting declarations inside the [cascade](/en-US/docs/Web/CSS/Cascade). A declaration that is not _important_ is called _normal_.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +
```suggestion
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +To create an important declaration, add the "important flag", comprised of the delimiter token `!` followed by the `important` keyword, after the value in the declaration. While white space is allowe
```suggestion
To mark a declaration important, add the _important flag_ (`!important`) after the value in the declaration. While white space is allowed between the delimiter and the keyword, the flag is generally written as `!important` without any white space.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +The important flag must come after the property value pair declaration value, preceded by at least one space. The `!important` or `! important` must be the last tokens in the declaration. In other wo
```suggestion
The `!important` flag comes after the value of the property value pair declaration, preceded by at least one space. The `!important` flag must be the last token in the declaration. In other words, there can be white space and comments between the flag and the declaration's ending semi-colon, but nothing else.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +When it comes to important declarations, the [cascade origin and layer orders](/en-US/docs/Web/CSS/Cascade) are reversed. By default, declarations in a website author's style sheets override declarat
```suggestion
When it comes to `!important` declarations, the [cascade origin and layer orders](/en-US/docs/Web/CSS/Cascade) are reversed. Without the important flag, declarations in the author's style sheets override declarations in a user's style sheet, which override declarations in the user-agent's default style sheet.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +When a declaration is important, the order of precedence is reversed. The user-agent important declarations override all user important declarations. All user important declarations override all impo
```suggestion
When a declaration is `!important`, the order of precedence is reversed. Declarations marked as `!important` in the user-agent style sheets override all `!important` declarations in the user style sheets. Similarly, all `!important` declarations in the user style sheets override all `!important` declarations in the author's style sheets. Finally, all `!important` declarations take precedence over all animations.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Reversing the precedence order for important declarations ensures users with special needs, such as personalized color schemes or large fonts, can override author styles when needed with important de
```suggestion
Reversing the precedence order for `!important` declarations ensures users with special needs, such as personalized color schemes or large fonts, can override author styles when needed by marking some declarations in their user's style sheet as `!important`. It also guarantees malicious extensions can't override `!important` user-agent styles, which might break functionality or negatively impact security.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Does anything have precedence over important declarations? Yes. [Transitions](/en-US/docs/Web/CSS/CSS_Transitions). CSS transitions are a way to control the speed at which the property changes from o
```suggestion
Does anything have precedence over important declarations? Yes, [transitions](/en-US/docs/Web/CSS/CSS_Transitions). CSS transitions are a way to control the speed at which the property changes from one value to another. While transitioning from one value to another, a property will not match a specific important declaration.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +In this example, the color and background color will transition to the hovered state over two seconds. Even though the default states are normal and hover states are important declarations, the trans
```suggestion
In this example, the `color` and `background-color` properties will transition to the hovered state over two seconds. Even though default states are normal declarations and hover states are `!important` declarations, the transition does happen.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Within each of the three origins - author, user, and user-agent - normal declarations in unlayered styles override layered style declarations, with the last declared having precedence over the layers
```suggestion
Within each of the three origins for style sheets – author, user, and user-agent – normal declarations in unlayered styles override layered style declarations, with the last declared having precedence over the layers declared before it. Important declarations reverse the order of precedence: `!important` declarations in the first layer take precedence over `!important!` declarations in the next layer, and so on. Also, all the `!important` declarations have precedence over `!important` declarations made outside of any layer.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +When it comes to the [`style` attribute](/en-US/docs/Web/HTML/Global_attributes/style), inline normal styles take precedence over all normal declarations, no matter the origin and inline important st
```suggestion
Inline styles are styles defined using the [`style`](/en-US/docs/Web/HTML/Global_attributes/style) attributes. They can also be normal or important. Inline _normal_ styles take precedence over all _normal_ declarations, no matter the origin. Inline _important_ styles take precedence over all other _important_ author styles, no matter the layer, but important styles from user's or user-agent's style sheets and transitions override them.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +While `!important` is not part of determining specificity, it is related.  Important declarations override all other declarations from the same [origin and cascade layer](/en-US/docs/Web/CSS/Cascade)
```suggestion
While `!important` is not part of determining specificity, it is related. Important declarations override all other declarations from the same [origin and cascade layer](/en-US/docs/Web/CSS/Cascade).
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +This is a case of over-specifying a selector. No matter how high the selector  [specificity](/en-US/docs/Web/CSS/Specificity) match of a normal declaration, an important declaration from the same ori
```suggestion
This example displays a case of over-specifying a selector. No matter how high the selector [specificity](/en-US/docs/Web/CSS/Specificity) matches a normal declaration, an `!important` declaration from the same source and cascade layer will always have precedence. In this case, the paragraph will always be red.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +When two important declarations are applied to the same element, with the same origin and layer, the declaration with a greater specificity will be applied.
```suggestion
When two `!important` declarations from the same origin and layer apply to the same element, browsers select and use the declaration with the highest specificity.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Declaring a shorthand property to be `!important` sets all of sub-properties `!important`. To two following selector style blocks are equivalent:
```suggestion
Declaring a shorthand property to be `!important` defines all of the longhand properties as`!important`. To two following selector style blocks are equivalent:
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +This is one of the several reasons avoiding `!important` is generally recommended.
```suggestion
This example shows one of the several reasons avoiding `!important` is generally recommended.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Avoid using `!important` to override specificity. When intentionally creating important declarations for UI requirements, comment your CSS to explain to maintainers why a feature must not be overridd
```suggestion
Avoid using `!important` to override specificity. When intentionally creating `!important` declarations for UI requirements, comment in your CSS code to explain to maintainers why they should not override that feature.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +If working to override styles with high scecificity that are not under your control, such as styles in a 3rd party plugin declared with an [id selector](/en-US/docs/Web/CSS/ID_selectors), consider im
```suggestion
Even when working to override high-specificity styles not under your control, such as styles in a 3rd party plugin declared with an [id selector](/en-US/docs/Web/CSS/ID_selectors), you don't need to use `!important`. Consider instead importing the 3rd party stylesheet script into a [named or anonymous layer](/en-US/docs/Web/CSS/@layer) as your first cascade layer, instead of using `!important`. As long as the external styles do not include `!important` declarations, your styles will take precedence over the widget styles, no matter the specificity.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +If needing to override external stylesheet containing important declarations, create a cascade layer of importnant overrides and declare that layer first.
```suggestion
If you need to override an external stylesheet containing `!important` declarations, create a cascade layer containing the needed overrides, and declare that layer first.
```

2022-05-18 06:38 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +Important styles from a user stylesheet take precedence over author important declarations, meaning adding an important flag to a site's styles will not prevent individual users with special requirem
```suggestion
Important styles from a user stylesheet take precedence over the author style sheet's `!important` declarations, meaning adding an `!important` flag to a site's styles will not prevent individual users with special requirements, such as large fonts, from being able to override your styles by adding`!important` styles in their own user's style sheet.
```

2022-05-18 06:40 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +
I don't think this section heading is necessary. We always start reference articles with a description.

```suggestion
```

2022-05-18 08:04 UTC, estelle commented on files/en-us/web/css/important/index.md
> +The important flag, comprised of a `!` delimiter and `important` keyword, when added to a declaration in a selector block, makes the declaration an important declaration.
still need to say "makes the declaration an important declaration."

2022-05-18 08:07 UTC, teoli2003 commented on files/en-us/web/css/important/index.md
> +The important flag, comprised of a `!` delimiter and `important` keyword, when added to a declaration in a selector block, makes the declaration an important declaration.
Better?

```suggestion
A `!` delimiter followed by the `important` keyword marks the declaration as important. The `!important` flag alters the rules selecting declarations inside the [cascade](/en-US/docs/Web/CSS/Cascade). A declaration that is not _important_ is called _normal_.
```

2022-05-18 15:23 UTC, OnkarRuikar commented on files/en-us/web/css/important/index.md
> +This is a case of over-specifying a selector. No matter how high the selector  [specificity](/en-US/docs/Web/CSS/Specificity) match of a normal declaration, an important declaration from the same ori
typo
```suggestion
This is a case of over-specifying a selector. No matter how high the selector [specificity](/en-US/docs/Web/CSS/Specificity) match of a normal declaration, an important declaration from the same origin and cascade layer will always have precedence. In this case, the paragraph will always be red.
```

2022-05-18 16:20 UTC, teoli2003 approved these changes
👍 Great article.

2022-05-18 16:20 UTC, merged