update caching based on RFC9111
mdn/content pull request #16009
Opened 2022-05-13 17:59 UTC by Jxck

#### Summary

It's been a long since #10027 but it's the rest of task updating caching section align with RFC9111 (new RFC not published yet).

#### Motivation

updating http caching section align with cache-control section and new RFC9111

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

#### Related issues

#8668

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-13 18:01 UTC, Jxck commented
hope @sideshowbarker fixing my writing and @mnot reviewing technical details.

2022-05-16 08:00 UTC, sideshowbarker requested changes

2022-05-16 08:24 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Also, since Private Cache requires `private`, you may think that Shared Cache requires `public`, but this is not quite true. Shared Cache will store a response without `public` as long as `max-age` i
```suggestion
Also, since the private cache requires `private`, you may think that the shared cache requires `public` — but that is not quite true. A shared cache will store a response without needing `public` as long as `max-age` is given.
```

2022-05-16 08:25 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +There are several advantages to reusability. First, since there is no need to deliver the request to the origin server, then the closer the client and cache are, the faster the response will be. The
```suggestion
There are several advantages to reusability. First, since there is no need to deliver the request to the origin server, then the closer the client and cache are, the faster the response will be. The most-typical example is when the browser itself stores a cache for browser requests.
```

2022-05-16 08:27 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +If the response has an `Authorization` header, it cannot be stored in either the private cache or the shared cache, even if it has `max-age` — and `public` can be used to allow such a case). But if y
```suggestion
If the response has an `Authorization` header, it cannot be stored in either the private cache or the shared cache, even if it has `max-age` — and `public` can be used to allow such a case. But if you are not using basic authentication and do not have an `Authorization` header, then there is no need to add `public`; it’s just a waste of bytes in that case.
```

2022-05-16 08:28 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +The shared cache is located between the client and the server and can store responses that can be shared among users. And shared caches can be further sub-classified into proxy caches and managed cac
```suggestion
The shared cache is located between the client and the server and can store responses that can be shared among users. And shared caches can be further sub-classified into **proxy caches** and **managed caches**.
```

2022-05-16 08:29 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +In addition to the function of access control, some proxies implement caching to reduce traffic out of the network. This is usually not managed by the service developer, so it must be controlled by a
```suggestion
In addition to the function of access control, some proxies implement caching to reduce traffic out of the network. This is usually not managed by the service developer, so it must be controlled by appropriate HTTP headers and so on. However, in the past, outdated proxy-cache implementations — such as implementations that do not properly understand the HTTP Caching standard — have often caused problems for developers.
```

2022-05-16 08:31 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +On the other hand, if a TLS bridge proxy decrypts all communications in a person-in-the-middle manner by installing a certificate from a CA managed by the organization on the PC, and performs access
```suggestion
On the other hand, if a TLS bridge proxy decrypts all communications in a person-in-the-middle manner by installing a certificate from a CA managed by the organization on the PC, and performs access control, etc. — it is possible to see the contents of the response and cache it. However, since CT (certificate transparency) has become widespread in recent years, and some browsers only allow certificates issued with an SCT (signed certificate timestamp), this method requires the application of an enterprise policy. In such a controlled environment, there is no need to worry about the proxy cache being "out of date and not updated".
```

2022-05-16 08:32 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +#### Managed cache
```suggestion
#### Managed caches
```

2022-05-16 08:32 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +### Private cache
```suggestion
### Private caches
```

2022-05-16 08:32 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +#### Proxy cache
```suggestion
#### Proxy caches
```

2022-05-16 08:34 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +For example, the HTTP Caching specification normally does not have way to explicitly delete a cache — but with a managed cache, the stored response can be deleted at any time through dashboard operat
```suggestion
For example, the HTTP Caching specification normally does not have a way to explicitly delete a cache — but with a managed cache, the stored response can be deleted at any time through dashboard operations, API calls, restarts,  and so on. That allows for a more proactive caching strategy.
```

2022-05-16 08:35 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +It is also possible to ignore the standard HTTP Caching spec protocols in favor of explicit manipulation. For example, the following can be specified to opt-out of a private cache or proxy cache, whi
```suggestion
It is also possible to ignore the standard HTTP Caching specification protocols in favor of explicit manipulation. For example, the following can be specified to opt-out of a private cache or proxy cache, while using your own strategy to cache only in a managed cache.
```

2022-05-16 08:36 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Note that some CDNs provide their own headers that are effective only for that CDN (for example, `Surrogate-Control`). Currently, work is underway to standardize the `CDN-Cache-Control` header to sta
```suggestion
Note that some CDNs provide their own headers that are effective only for that CDN (for example, `Surrogate-Control`). Currently, work is underway to define a `CDN-Cache-Control` header to standardize those.
```

2022-05-16 08:37 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +## Type of caches
```suggestion
## Types of caches
```

2022-05-16 08:39 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +## Heuristic cache
```suggestion
## Heuristic caching
```

2022-05-16 08:49 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +It is commonn misunderstanding to assume that if you do not give a `Cache-Control`, it will not be stored. If you do not want such a store, you must explicitly deny it with a `Cache-Control`. Rather,
```suggestion
Heuristic caching is a workaround that came in being before `Cache-Control` support became widely, and basically all responses should explicitly specify a `Cache-Control` header.
```

2022-05-16 08:51 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +If both `Expires` and `Cache-Contro: max-age` are available, `max-age` is defined to be preferred. So it is not necessary to provide `Expires` now that HTTP/1.1 is widely used.
```suggestion
If both `Expires` and `Cache-Control: max-age` are available, `max-age` is defined to be preferred. So it is not necessary to provide `Expires` now that HTTP/1.1 is widely used.
```

2022-05-16 08:53 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +For example, got English content returned with an `Accept-Language: en` header and cached, it is undesirable to then reuse that cached response for requests that have an `Accept-Language: ja` request
```suggestion
For example, for English content returned with an `Accept-Language: en` header and cached, it is undesirable to then reuse that cached response for requests that have an `Accept-Language: ja` request header. In this case, you can cause the responses to be cached separately — based on language — by adding "`Accept-Language`" to the value of the `Vary` header.
```

2022-05-16 08:54 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Also, if you are providing content optimization (for example, for responsive design) based on the user agent, you may be tempted to include "`User-Agent`" in the value of the `Vary` header. However,
```suggestion
Also, if you are providing content optimization (for example, for responsive design) based on the user agent, you may be tempted to include "`User-Agent`" in the value of the `Vary` header. However, the `User-Agent` request header generally has a very large number of variations, which drastically reduces the chance that the cache will be reused. So if possible, instead consider a way to vary behavior based on feature detection rather than based on the `User-Agent` request header.
```

2022-05-16 08:55 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Validation is done by using conditional request that includes an `If-Modified-Since` or `If-None-Match` request header.
```suggestion
Validation is done by using a **conditional request** that includes an `If-Modified-Since` or `If-None-Match` request header.
```

2022-05-16 08:57 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +If that response is stale, the client takes the value of `ETag` response header for the cached response, and puts it into the `If-None-Match` request header, to ask the server if the resource has bee
```suggestion
If that response is stale, the client takes the value of the `ETag` response header for the cached response, and puts it into the `If-None-Match` request header, to ask the server if the resource has been modified:
```

2022-05-16 08:58 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +> **Note:** ETag or Last-Modified ?
```suggestion
> **Note:** ETag or Last-Modified?
```

2022-05-16 08:59 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +> During cache revalidation, if both `ETag` and `Last-Modified` are present, `ETag` takes precedence.
```suggestion
> **Note:** The choose between `ETag` and `Last-Modified`, consider the following:
> During cache revalidation, if both `ETag` and `Last-Modified` are present, `ETag` takes precedence.
```

2022-05-16 09:01 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +> So considering the overall HTTP ecosystem, it is preferable to provide both `ETag` and `Last-Modified`.
```suggestion
> **Note:** When evaluating how to use `ETag` and `Last-Modified`, consider the following:
> During cache revalidation, if both `ETag` and `Last-Modified` are present, `ETag` takes precedence.
> Therefore, if you are only considering caching, you may think that `Last-Modified` is unnecessary.
> However, `Last-Modified` is not just useful for caching; instead, it is a standard HTTP header that is also used by content-management (CMS) systems to display the last-modified time, by crawlers to adjust crawl frequency, and for other various purposes.
> So considering the overall HTTP ecosystem, it is preferable to provide both `ETag` and `Last-Modified`.
```

2022-05-16 09:03 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +`max-age=0` means that the response is immediately stale, and `must-revalidate` means that it must not be reused without revalidation once it is stale — so the semantics seem to be the same.
```suggestion
`max-age=0` means that the response is immediately stale, and `must-revalidate` means that it must not be reused without revalidation once it is stale — so in combination, the semantics seem to be the same as `no-cache`.
```

2022-05-16 09:05 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +As a workaround to outdated implementations that ignore `no-store`, you may see kitchen-sink headers such as the following being used.
```suggestion
As a workaround for outdated implementations that ignore `no-store`, you may see kitchen-sink headers such as the following being used.
```

2022-05-16 09:09 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +## Caching pattern
```suggestion
## Common caching patterns
```

2022-05-16 09:11 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Note that number `41` has a longest `max-age` (1 year), but with `public`.
```suggestion
Note that number `41` has the longest `max-age` (1 year), but with `public`.
```

2022-05-16 09:14 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +> **Note:** immutable and QPACK
```suggestion
> **Note:** When consider the use of `immutable` and QPACK: 
```

2022-05-16 09:15 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +> **Note:** When consider the use of `immutable` and QPACK:
```suggestion
> **Note:** When evaluating the use of `immutable` and QPACK: 
```

2022-05-16 09:16 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +### HTML Main resources
```suggestion
### Primary resources
```

2022-05-16 09:18 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +### Additional managed cache
```suggestion
### More about the managed cache
```

2022-05-16 09:19 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Caching main resources is difficult because, using standard directives from the HTTP Caching spec, there’s no way to actively delete cache contents when content is updated on the server.
```suggestion
Caching primary resources is difficult because, using standard directives from the HTTP Caching spec, there’s no way to actively delete cache contents when content is updated on the server.
```

2022-05-16 09:19 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +For example, a CDN that allows cache purging via an API or dashboard operation would allow for a more aggressive caching strategy by storing the main resource and explicitly purging the relevant cach
```suggestion
For example, a CDN that allows cache purging via an API or dashboard operation would allow for a more aggressive caching strategy by storing the primary resource and explicitly purging the relevant cache only when an update occurs on the server.
```

2022-05-16 09:21 UTC, sideshowbarker commented on files/en-us/web/http/caching/index.md
> +Caching primary resources is difficult because, using standard directives from the HTTP Caching spec, there’s no way to actively delete cache contents when content is updated on the server.
```suggestion
Caching primary resources is difficult because, using just standard directives from the HTTP Caching specification, there’s no way to actively delete cache contents when content is updated on the server.
```

2022-05-16 09:22 UTC, sideshowbarker approved these changes
Amazingly great work as usual

2022-05-16 09:37 UTC, merged