chore: Add Markdownlint cleanup job
mdn/content pull request #16036
Opened 2022-05-15 01:06 UTC by nschonni

GitHub Action to create daily PR fixes for auto-fixable Markdownlint issues

2022-05-15 05:36 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +          markdownlint "**/*.md" --fix
We don't want it to spend time on `node_modules`.
```suggestion
          markdownlint "./files/**/*.md" "./meta/**/*.md" --fix
```

2022-05-15 05:36 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +            Auto-fix cleanup PR using Markdown CLI.
Can we append unfixable issues to the body?
Like:
> ./files/en-us/web/index.md:2 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "### Title"]

Is it possible to pipe the output to a lint.log file and attach file contents to the PR body.

2022-05-15 05:59 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          markdownlint "**/*.md" --fix
There is no npm/yarn install before this is run, so there is no need. The better why though, if you're running locally is to use `-i node_modules` to ignore the folder

2022-05-15 06:14 UTC, OnkarRuikar commented
On the first day the filter "**/*.md" will create PR of a lot of files. There are 11,335 `.md` files to process.

If we target only files that merged on the day, the process will take less time and there will be less files to review. This will stop new markdown bugs coming in and we can start linting all the remaining files in batches from the start. One day entire content will be lint free.

We can do this something like this:
```bash
# get the number of commits in a day
$ number=$(git rev-list --count --since=yesterday --before=today HEAD)
$ echo $number
15

# get list of the files modified in last 15 commits
$  list=$(git diff --name-only HEAD~$number..HEAD)

$ logs=$(markdownlint $list --fix)

# append the $logs to the PR body
```
Some [search and replace PRs](https://github.com/mdn/content/pull/15973) modify a lot of files. So we can limit the number to say 30.

2022-05-15 17:32 UTC, nschonni commented
I've been cleaning these up for awhile, there were only ~40 changed files when I tested it on my repo https://github.com/nschonni/mdn-content/pull/105

2022-05-15 18:34 UTC, nschonni commented
https://github.com/mdn/content/pull/16075 are the only outstanding issues currently

2022-05-16 04:18 UTC, OnkarRuikar commented
You are right. I accidentally ran it with default config and got ~700 files updated. 😬
As per the current https://github.com/mdn/content/blob/main/.markdownlint.json config all the files are clean.

Also the processing all the files didn't take much time. Looks like it keeps track of modified files and directories.
So, using the filter ` "**/*.md"` is ok.

We need to include issues, in PR body, that the linter couldn't fix and need manual work.
```
$ logs=$(markdownlint "**/*.md" --fix)

# append the $logs to the PR body
```

2022-05-24 03:45 UTC, nschonni commented
BTW, I have been looking at the "append log to body", but it hasn't been simple and I don't know if I'll be able to resolve it

2022-07-20 16:14 UTC, nschonni commented
Yes, I think using the script would make sense. If the other one lands, I'll adjust this one, but I didn't want either to block the other

2022-08-23 14:34 UTC, teoli2003 requested changes

2022-08-23 14:34 UTC, teoli2003 commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixiable issues found
Nit:
```suggestion
            No unfixable issues found
```

2022-08-23 15:00 UTC, teoli2003 approved these changes
LGTM. I would like a dev review before merging this as I'm not an expert in these workflows, but we definitively would like to make a try with this one.

2022-08-23 18:31 UTC, Josh-Cena commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
Can we use @mdn-bot as committer/author instead?

2022-08-23 19:34 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
The Author and/or committer can be overridden https://github.com/peter-evans/create-pull-request#action-inputs

2022-08-23 20:52 UTC, Josh-Cena commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
Yeah, it's more of a question of "should" instead of "can" 😄

2022-08-24 06:28 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +          branch: daily-markdownlint-fix
```suggestion
          branch: daily-markdownlint-fix
          delete-branch: true
```
They've recommended to delete the branch after PR close/merge.

Their document doesn't mention anything about rebasing the exiting branch that has a merged PR already. Ideally everyday we want a fresh branch from main, i.e. `git checkout -b daily-markdownlint-fix main`

2022-08-24 06:44 UTC, teoli2003 commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
Yes, it would be nice to have a bot as the author, it makes clear that it is an automatic process.

2022-08-24 06:45 UTC, teoli2003 commented on .github/workflows/markdown-lint-fix.yml
> +          branch: daily-markdownlint-fix
Let's delete the branch afterward. And yes, let's start with a clean branch from main. Rebasing & co seems error-prone.

If we close the PR without merging, will it delete the branch?

2022-08-24 07:33 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +          branch: daily-markdownlint-fix
> If we close the PR without merging, will it delete the branch?

I strongly believe this happens only when the action decides to close the pull request itself(because recent commit reverted all the changes and there is no diff between main and the branch) or when auto merge is set and after the auto merge.

The action won't delete the branch after humans merge the PR. I think this needs to be handled in a separate task before this one.
For example:
```
- name: Cleanup
    run: |
      echo "deleting the branch daily-markdownlint-fix"
      git branch -D daily-markdownlint-fix
```
This will give us fresh runs everyday instead of appending commits to the same branch.

2022-08-24 07:58 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +          title: "Daily Markdownlint auto-cleanup"
```suggestion
          title: "Daily Markdownlint auto-cleanup"
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
```
Makes the @mdn-bot the author.

2022-08-24 08:03 UTC, OnkarRuikar commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
The latest user who creates the schedule trigger is the author by default. [[ref](https://github.com/orgs/community/discussions/25067#discussioncomment-3246381)]

To make @mdn-bot the author see https://github.com/mdn/content/pull/16036#discussion_r953475633

2022-08-24 08:14 UTC, OnkarRuikar commented
This is an interesting workflow. I have a few queries about how this is going to work:
- At what time will it trigger? Midnight `UTC-8 Los Angeles` time?
- Do we want auto merge on this like dependabot PRs? Or we are going to merge manually?
- What should happen the next day if we fail to merge the PR within 24 hours? Create a brand new PR? or Append to the existing one?
- Do we want to reuse the `daily-markdownlint-fix` branch everyday? Or Delete and create a brand new branch everyday?

2022-08-24 08:34 UTC, teoli2003 commented
>     * At what time will it trigger? Midnight `UTC-8 Los Angeles` time?

This is not critical, but it looks like a good time. Night in the US, and about 10 my time.

>     * Do we want auto merge on this like dependabot PRs? Or we are going to merge manually?

I think we should start by merging this manually. If it goes well, we can, later do what is done with the daily yari update and merge it automatically.


>     * In [their example](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md) they've said:
>       > When you merge the pull request make sure to choose the [`Rebase and merge`](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) option. This will make the fork's commits match the commits on the upstream.

Squash and merge should be the default, like for any other PR on mdn/content.
      
>       Which option are we suppose to use for this one?
> 
>     * What should happen the next day if we fail to merge the PR within 24 hours? Create a brand new PR? or Append to the existing one?

I like what dependabot is doing: closing the old PR and opening a new one.

>     * Do we want to reuse the `daily-markdownlint-fix` branch everyday? Or Delete and create a brand new branch everyday?

I'm a bit afraid of reusing a branch: it could be in a strange state. What does dependabot does? It works pretty well and we should do the same.

2022-08-24 10:02 UTC, caugner requested changes

2022-08-24 10:02 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
I think it's okay to use `@mdn-bot` as author (though committer is not quite correct), but the default (`GitHub <noreply@github.com>`) wouldn't hurt either.

2022-08-24 10:04 UTC, caugner commented
> What should happen the next day if we fail to merge the PR within 24 hours? Create a brand new PR? or Append to the existing one?

Quote from https://github.com/peter-evans/create-pull-request#action-behaviour:

> If a pull request already exists it will be updated if necessary. Local changes in the Actions workspace, or changes on the base branch, can cause an update. If no update is required the action exits silently.

2022-08-24 11:59 UTC, Josh-Cena commented on .github/workflows/markdown-lint-fix.yml
> +          branch: daily-markdownlint-fix
We should set up automatically deleting HEAD.

2022-08-24 16:23 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          branch: daily-markdownlint-fix
That is better handled by the GitHub setting https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches.
If it is closed without merging, the branch will be overridden the next time the job runs.

2022-08-24 16:24 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
These are generally a bad idea from an accessibility lens

2022-08-24 16:33 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          yarn --frozen-lockfile
I actually removed that from that job because the `cache:` is built into the setup-node. I've now leveraged that here too, but couldn't before Markdownlint became an actual dependency, and didn't catch that when I switched it to the script

2022-08-24 18:16 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          body: |
I think the autolabeler will tag the affected pages, but if there is a specific meta tag that might be missing it could be added

2022-08-24 18:17 UTC, nschonni commented
I've added the MDN-bot as the `committer` rather than the `author`. That way the author of the PR will remain the bot if it's triggered by the cron job, but the user if it's manually triggered by a member to generate the PR ad-hoc

2022-08-24 19:00 UTC, Josh-Cena commented on .github/workflows/markdown-lint-fix.yml
> +          commiter: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
Just to be sure, committer automatically becomes the PR author, right?

2022-08-24 19:02 UTC, Josh-Cena approved these changes
LGTM, we can play with this

2022-08-25 04:43 UTC, teoli2003 commented
Yes, let's try this.

2022-08-26 08:37 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +          commiter: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
Afaik it would need to be `committer` (with two `t`).

2022-08-26 08:41 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +            No unfixable issues found
You could put the emoji at the end of the line, if that makes it any better.

In either case, I feel like the double negation ("No unfixable ...") is confusing. But then again, it won't be me reviewing those PRs, so I don't really mind.

2022-08-29 14:04 UTC, nschonni commented
@caugner you still have a blocking review on this

2022-08-31 19:26 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
@caugner did you want me to change this to `author` like in https://github.com/mdn/content/pull/20022? I haven't seen a run of that action yet, so I'm not sure which bet is right

2022-09-05 15:54 UTC, teoli2003 commented
Is anything blocking this? (I would prefer to merge this near the beginning of the week rather than close to the weekend)

2022-09-05 15:56 UTC, Josh-Cena commented
None, just waiting on @caugner to re-review

2022-09-05 16:17 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
@nschonni Yes, I think it would be best to use the same `author` (and don't override `committer`), for consistency.

Here's the PR triggered by the last run on Friday: https://github.com/mdn/content/pull/20266

2022-09-05 16:32 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
OK, I've swapped it for `author`

2022-09-06 18:47 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +            Auto-fix cleanup PR using Markdown CLI.
A good compromise would be to link to the run that triggered the PR: `https://github.com/mdn/content/actions/runs/${GITHUB_RUN_ID}`

2022-09-06 18:53 UTC, caugner approved these changes
LGTM, just one last suggestion to link directly to the log of the action run.

2022-09-06 18:53 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +            Please review the last action run of https://github.com/mdn/content/actions/workflows/markdown-lint-fix.yml
```suggestion
            Please review the run log: https://github.com/mdn/content/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true#step:5:1
```

2022-09-06 20:57 UTC, caugner approved these changes

2022-09-07 03:25 UTC, merged