Re-written content in device api fundamentals
mdn/content pull request #1603
Opened 2021-01-22 05:05 UTC by 3agpot

Many little changes (typos, sentence restructuring, paragraph revisions), primarily targeted at making the content easier to read and comprehend.

2021-01-23 04:53 UTC, sideshowbarker requested changes
Really nice copy-editing pass overall. I have just a couple nits and few quibbles with some of the wording changes.

2021-01-23 04:53 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p><em>WebXR is not a rendering technology and does not provide features for managing 3D data or rendering it to the display.</em> This is an important fact to keep in mind. While WebXR manages the t
```suggestion
<p><em>WebXR is not a rendering technology and does not provide features for managing 3D data or rendering it to the display.</em> This is an important fact to keep in mind. While WebXR manages the timing, scheduling, and the various points of view relevant when drawing the scene, it does <em>not</em> know how to load and manage models, nor how to render and texture them, and so forth. That part is entirely up to you. Fortunately, WebGL and the various WebGL-based frameworks and libraries are available to make it much easier to deal with all of that.</p>
```
…otherwise that *While* part is gonna be a sentence fragment…

2021-01-23 04:53 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>WebVR was considered an experimental API designed to help specification writers determine the best approaches for creating a virtual reality API on the Web. The advancements of WebVR support in th
```suggestion
<p>WebVR was considered an experimental API designed to help specification writers determine the best approaches for creating a virtual reality API on the Web. Browser implementors added WebVR support to browsers, allowing web developers to experiment. But soon it became clear that to finish an API for virtual reality on the web, it would make more sense to start a new specification than to try to "fix" WebVR.</p>
```
Replacing *As browser developers built support for WebVR and allowed developers to experiment, it became clear* with *The advancements of WebVR support in the browsers allowed developers to experiment. But soon it became clear* does not seem to me to be an improvement. Please consider  my suggestion instead.

2021-01-23 04:53 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ramps up to about 200° to 220° wide. Why is the FOV wider with two eyes, but no
```suggestion
<p>A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ends up being about 200° to 220° wide. Why is the FOV wider with two eyes, but not double the single-eye FOV? It's because the two eyes' FOVs overlap a lot. That overlap gives us depth perception, which is around 115° wide. Outside the overlap area, our vision falls back to monocular.</p>
```
*ramps up to* here doesn’t strike me a particularly idiomatic. It sorta makes it seem a lot more exciting than it actually is. Please consider my suggestion, or some other mundane wording.

2021-01-23 04:53 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>Generally, the applications only define and manage the horizontal FOV. For more details, see {{SectionOnPage("/en-US/docs/Web/API/WebXR_Device_API/Rendering", "The optics of 3D")}}.</p>
```suggestion
<p>Generally, applications only define and manage the horizontal FOV. For more details, see {{SectionOnPage("/en-US/docs/Web/API/WebXR_Device_API/Rendering", "The optics of 3D")}}.</p>
```
…otherwise using *the* here makes it sound like we’re referring back to some earlier mention of “applications” — but there is no earlier mention.

2021-01-23 05:11 UTC, 3agpot commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p><em>WebXR is not a rendering technology and does not provide features for managing 3D data or rendering it to the display.</em> This is an important fact to keep in mind. While WebXR manages the t
I think that's what I wanted to do initially. I have no idea how this slipped through. Thanks for spotting this.

2021-01-23 05:13 UTC, 3agpot commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>WebVR was considered an experimental API designed to help specification writers determine the best approaches for creating a virtual reality API on the Web. The advancements of WebVR support in th
I like your wording more, because it's more specific as to who is adding support to what. Thanks.

2021-01-23 05:15 UTC, 3agpot commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>A human eye is able to take in a FOV of around 135°. Assuming a person has two healthy eyes, the total field of view ramps up to about 200° to 220° wide. Why is the FOV wider with two eyes, but no
"ends up" might be a better fit for technical documentation content. Perhaps I was getting to excited abou WebXR :)

2021-01-23 05:17 UTC, 3agpot commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>Generally, the applications only define and manage the horizontal FOV. For more details, see {{SectionOnPage("/en-US/docs/Web/API/WebXR_Device_API/Rendering", "The optics of 3D")}}.</p>
Spot on. My miss again. These articles can often completely obscure the meaning.

2021-01-23 06:34 UTC, sideshowbarker requested changes
Sorry to pile on suggestions, but I noticed a few more nits that I missed in my first pass at reviewing this. Please take a look. With these changes applied, I think we’ll be good to go.

2021-01-23 06:34 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>WebXR, with the <a href="/en-US/docs/Web/API/WebXR_Device_API">WebXR Device API</a> at its core, provides the functionality needed to bring both augmented and virtual reality (AR and VR) to the we
```suggestion
<p>WebXR, with the <a href="/en-US/docs/Web/API/WebXR_Device_API">WebXR Device API</a> at its core, provides the functionality needed to bring both augmented and virtual reality (AR and VR) to the web. Together, these technologies are referred to as <strong>mixed reality (MR)</strong> or <strong>cross reality (XR)</strong>. Mixed reality is a large and complex subject, with much to learn and many other APIs to bring together to create an engaging experience for users.</p>
```
I suggest we just drop the part about *new trend*. I realize you didn’t add it — it was there already. But when doing copy-editing passes, things like that are something to look out for and remove. To be clear: the general problem with having something like that in MDN is that nothing’s going to be a “new trend” forever — maybe it’s not even still “new” now, and certainly it’s not going to be a “new trend” a year from now, or three years from now. But we’re going to have this MDN article for that long, and even longer. So we should avoid keeping anything in MDN that’s going to end up looking (quaintly) dated later — avoid having anything that we know we’d end up needing to remove at some point later.

2021-01-23 06:34 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>That led to the birth of WebXR. The fundamental difference is that WebXR supports not only virtual reality, but also augmented reality which blends virtual objects with the user's ambient environm
```suggestion
<p>That led to the birth of WebXR. The fundamental difference is that WebXR supports not only virtual reality, but also augmented reality, which blends virtual objects with the user's ambient environment.</p>
```

2021-01-23 06:34 UTC, sideshowbarker commented on files/en-us/web/api/webxr_device_api/fundamentals/index.html
> +<p>The drawing shown here demonstrates the concept of FOV: blue wedge for the left eye, red wedge for the right eye. The light brown overlapping area is where the viewer has binocular vision and can
```suggestion
<p>The drawing shown here demonstrates the concept of FOV: blue wedge for the left eye, red wedge for the right eye. The light brown overlapping area is where the viewer has binocular vision and can perceive depth. If you look carefully, you'll see that each eye sees the die slightly differently, and the combined view blends the two into a 3D shape.</p>
```

2021-01-24 05:57 UTC, 3agpot commented
No problem. Thanks for spotting these. We share a mutual goal of making this documentation as clear as possible!

2021-01-24 06:34 UTC, sideshowbarker approved these changes

2021-01-24 06:34 UTC, merged

2021-01-24 06:35 UTC, sideshowbarker commented
👍 It’s really nice to see incremental refinements getting made at this level of detail.