Add Caution base on Lighthouse changes
mdn/content pull request #16043
Opened 2022-05-15 04:48 UTC by aneeshikmat

#### Summary

Add Caution for FMP and Lighthouse

#### Motivation

When I read how to optimize performance, I care how to improve it, but since its ignore from Lighthouse and the LCP is the measurable now, I added to keep the reader understand what happen and where he will go...

#### Supporting details

https://web.dev/first-meaningful-paint/

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-16 17:36 UTC, estelle commented on files/en-us/glossary/first_meaningful_paint/index.md
> +> **Caution:** First Meaningful Paint (FMP) is deprecated in Lighthouse 6.0. In practice FMP has been overly sensitive to small differences in the page load, leading to inconsistent (bimodal) results
```suggestion
> **Warning:** First Meaningful Paint (FMP) is deprecated in Lighthouse 6.0.  Moving forward, consider using [Largest Contentful Paint](https://wicg.github.io/largest-contentful-paint/) instead.
```

2022-05-16 17:39 UTC, estelle requested changes
Thank you for your contribution. I suggested some edits to incorporate your suggested content additions into the "glossary definition followed by warning if needed" format.

2022-05-16 17:39 UTC, estelle commented on files/en-us/glossary/first_meaningful_paint/index.md
FMP is very sensitive to small differences in the page load. This can lead to inconsistent (bimodal) results. The metric's definition relies on browser-specific implementation details, which means it can't be standardized and hand not been implemented in all web browsers.

2022-05-17 02:39 UTC, aneeshikmat commented on files/en-us/glossary/first_meaningful_paint/index.md
Thank you @estelle

2022-05-17 06:52 UTC, OnkarRuikar commented on files/en-us/glossary/first_meaningful_paint/index.md
> +FMP is very sensitive to small differences in the page load. This can lead to inconsistent (bimodal) results. The metric's definition relies on browser-specific implementation details, which means it
```suggestion
FMP is very sensitive to small differences in the page load. This can lead to inconsistent (bimodal) results. The metric's definition relies on browser-specific implementation details, which means it can't be standardized and has not been implemented in all web browsers.
```

2022-05-18 18:49 UTC, estelle approved these changes

2022-05-18 18:49 UTC, merged