Update File System Access API Documentation
mdn/content pull request #1606
Opened 2021-01-22 08:52 UTC by troyappel

- Fix typos in code examples
- Remove redundant language from API overview
- Fix misformatted header names

2021-01-22 11:23 UTC, Rumyra commented
Assigning to myself as the original author... review on it's way 👍

2021-01-24 14:31 UTC, sideshowbarker requested changes
Nits

2021-01-24 14:31 UTC, sideshowbarker commented on files/en-us/web/api/file_system_access_api/index.html
> +<p>These handles represent the file or directory on the user's system. You must first gain access to them by showing the user a file or directory picker. The methods which allow this are {{domxref('w
```suggestion
<p>These handles represent the file or directory on the user's system. You must first gain access to them by showing the user a file or directory picker. The methods which allow this are {{domxref('window.showOpenFilePicker')}} and {{domxref('window.showDirectoryPicker')}}. Once these are called, the file picker presents itself and the user selects either a file or directory. Once this happens successfully, a handle is returned. You can also gain access to file handles via the {{domxref('DataTransferItem.getAsFileSystemHandle()')}} method of the {{domxref('HTML Drag and Drop API')}}.</p>
```

2021-01-24 14:31 UTC, sideshowbarker commented on files/en-us/web/api/file_system_access_api/index.html
> +<p>The handle provides its own functionality and there are a few differences depending on whether a file or directory was selected (see the below <a href="#interfaces">interfaces</a> section for spec
```suggestion
<p>The handle provides its own functionality and there are a few differences depending on whether a file or directory was selected (see the <a href="#interfaces">interfaces</a> section for specific details). You then can access file data, or information (including children) of the directory selected.</p>
```

2021-01-24 14:31 UTC, sideshowbarker commented on files/en-us/web/api/file_system_access_api/index.html
> +<p>There is also save functionality, using the {{domxref('FilesystemWritableFileStream')}} interface. Once the data you'd like to save is in a format of {{domxref('Blob')}}, {{domxref('USVString')}}
```suggestion
<p>There is also “save” functionality, using the {{domxref('FilesystemWritableFileStream')}} interface. Once the data you'd like to save is in a format of {{domxref('Blob')}}, {{domxref('USVString')}} or {{jsxref('ArrayBuffer', 'buffer')}}, you can open a stream and save the data to a file. This can be the existing file or a new file.</p>
```

2021-01-24 14:31 UTC, sideshowbarker commented on files/en-us/web/api/file_system_access_api/index.html
> +<p>The below asynchronous function opens the save file picker, which returns a {{domxref('FileSystemFileHandle')}} once a file is selected. A writable stream is then created using the {{domxref('File
```suggestion
<p>The following asynchronous function opens the save file picker, which returns a {{domxref('FileSystemFileHandle')}} once a file is selected. A writable stream is then created using the {{domxref('FileSystemFileHandle.createWritable()')}} method.</p>
```

2021-02-24 04:01 UTC, sideshowbarker approved these changes

2021-02-24 04:04 UTC, sideshowbarker commented
Thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

2021-02-24 04:04 UTC, merged