fix: amend that `URL` can be passed to `fetch`
mdn/content pull request #1607
Opened 2021-01-22 09:32 UTC by philipp-tailor

Based on the current `resource` list I implemented some code which assumed that a `fetch` could only be passed a `Request` object or a string. My code ended up being buggy because of usages of some sites' usage of `fetch`, where a `URL` instance is passed.

This change mentions the possibility of a `URL` instance being passed as `resource` parameter to `fetch`.

Admittedly I did not research whether that's defined in the standard, just a real-world implementation detail. I also don't know whether it works because `fetch` calls `.toString()` or accesses `.href` on the `URL` instance. Based on the lack of knowledge on my side, I kept it short to not misinform. I'd still have found the mention helpful.

Maybe someone else can fill in the details of how / why that works.

2021-01-22 14:08 UTC, evilpie commented
Per spec the parameter of [fetch](https://fetch.spec.whatwg.org/#fetch-method) is [`typedef (Request or USVString) RequestInfo;`](https://fetch.spec.whatwg.org/#requestinfo).

2021-01-22 14:14 UTC, philipp-tailor commented
Not sure it helps, but this are some example pages which are passing `URL` instance as resource parameter to `fetch`: [stripe](http://stripe.com/), [mango](https://shop.mango.com/). Seems to be supported in Chrome, Safari, Firefox. 
`URL` is returning a `USVString` as  .href` attribute, or when calling `.toString()`.

2021-01-23 05:35 UTC, sideshowbarker commented
> Per spec the parameter of [fetch](https://fetch.spec.whatwg.org/#fetch-method) is [`typedef (Request or USVString) RequestInfo;`](https://fetch.spec.whatwg.org/#requestinfo).

I’ll look at that part of the spec myself more too, but for now, also paging in @annevk.

Anne, this is about https://developer.mozilla.org/en-US/docs/web/api/windoworworkerglobalscope/fetch#parameters. In particular, it’s about the part that documents what the *input* parameter (called *resource* in this MDN article) for `fetch()` calls can be — both what the spec says it must be, but also what browsers permit it to be in practice (even if the spec doesn’t permit it).

2021-01-23 05:52 UTC, sideshowbarker commented
> Seems to be supported in Chrome, Safari, Firefox.
> `URL` is returning a `USVString` as `.href` attribute, or when calling`.toString()`.
> …
> I also don't know whether it works because `fetch` calls `.toString()` or accesses `.href` on the `URL` instance.

OK, as far as what the spec says, I find:

https://fetch.spec.whatwg.org/#dom-global-fetch
> The <dfn class="dfn-paneled idl-code" data-dfn-for="WindowOrWorkerGlobalScope" data-dfn-type="method" data-export="" data-lt="fetch(input, init)|fetch(input)" id="dom-global-fetch"><code>fetch(<var>input</var>, <var>init</var>)</code></dfn> method steps are:
> …
> Let <var>requestObject</var> be the result of invoking the initial value of <code class="idl"><a data-link-type="idl" href="#request" id="ref-for-request①③">Request</a></code> as constructor with <var>input</var> and <var>init</var> as arguments. If this throws an exception, <a data-link-type="dfn" href="https://heycam.github.io/webidl/#reject" id="ref-for-reject">reject</a> <var>p</var> with it and return <var>p</var>.

…and:

https://fetch.spec.whatwg.org/#dom-request
> The <dfn class="dfn-paneled idl-code" data-dfn-for="Request" data-dfn-type="constructor" data-export="" data-lt="Request(input, init)|constructor(input, init)|Request(input)|constructor(input)" id="dom-request"><code>new Request(<var>input</var>, <var>init</var>)</code></dfn> constructor steps are:
> …
> If _input_ is a string, then:
> …
> Otherwise:
> 1. Assert: _input_ is a `Request` object.
> 2. Set <var>request</var> to <var>input</var>’s <a data-link-type="dfn" href="#concept-request-request" id="ref-for-concept-request-request②">request</a>.

So, there in the Fetch spec itself, I don’t see any logic for recognizing the _input_ parameter as anything other than a string or `Request` object. Certainly don’t see any explicit logic there for recognizing a `URL` object and doing anything with it. So it does seems like there’s some non-spec magic here in implementations that they’re using to stringily the `URL` object.

Or maybe there’s some magic in the spec that I’m overlooking,

2021-01-23 07:39 UTC, annevk commented
Things that take a string (including USVString) invoke JS's `ToString` per IDL, which for URL (per its IDL) invokes the `href` getter steps.

2021-01-23 21:48 UTC, sideshowbarker requested changes

2021-01-23 21:48 UTC, sideshowbarker commented on files/en-us/web/api/windoworworkerglobalscope/fetch/index.html
> +      <li>A {{domxref("URL")}} object.</li>
```suggestion
      <li>A {{domxref("URL")}} object, or any other object with a <a href="https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file#stringifiers">stringifier</a> that produces a URL value for a resource that can be fetched.</li>
```

2021-01-23 22:06 UTC, sideshowbarker commented
> Things that take a string (including USVString) invoke JS's `ToString` per IDL, which for URL (per its IDL) invokes the `href` getter steps.

Aha — thanks

Given that, I’ve suggested a change to the patch in this PR branch such that the wording would be:

> A URL object, or any other object with a <a href="https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file#stringifiers">stringifier</a> that provides the URL for the resource you want to fetch.</li>

2021-01-25 08:59 UTC, philipp-tailor commented
Thank you everyone for diving deep to improve this article. Very appreciated that you didn't reject my change based on me not having done that myself. Feels like everyone just wants to improve the docs for the future, which is great! 👏🏼  I know I've learned something from your efforts already. 🙇🏼 

@sideshowbarker I committed the revised message as you suggested.

2021-02-01 03:42 UTC, sideshowbarker approved these changes

2021-02-01 03:42 UTC, merged

2021-02-01 03:43 UTC, sideshowbarker commented
Thanks much (and sorry for the delay in getting back to re-review this), and congrats on landing your first docs change here — welcome aboard 🎉