TextEncoderStream
mdn/content pull request #1612
Opened 2021-01-22 11:16 UTC by rachelandrew

Adding the TextEncoderStream interface and subpages.

Reviewer: @jpmedley

2021-01-28 15:20 UTC, jpmedley requested changes

2021-01-28 15:20 UTC, jpmedley commented on files/en-us/web/api/textencoderstream/index.html
> +  <li><a href="https://streams.spec.whatwg.org/demos/">Examples of streaming structured data and HTML</a></li>
Can you please show actual examples in line?

2021-01-28 15:20 UTC, jpmedley commented on files/en-us/web/api/textencoderstream/readable/index.html
> +<p>Returning a {{domxref("ReadableStream")}} from a <code>TextEncoderStream</code>.</p>
Please use a complete sentence.

2021-01-28 15:20 UTC, jpmedley commented on files/en-us/web/api/textencoderstream/writable/index.html
> +<p class="summary">The <strong><code>writable</code></strong> read-only property of the {{domxref("TextEncoderStream")}} interface  returns a {{domxref("WritableStream")}}.</p>
```suggestion
<p class="summary">The <strong><code>writable</code></strong> read-only property of the {{domxref("TextEncoderStream")}} interface returns a {{domxref("WritableStream")}}.</p>
```

2021-01-29 11:50 UTC, rachelandrew commented on files/en-us/web/api/textencoderstream/index.html
> +  <li><a href="https://streams.spec.whatwg.org/demos/">Examples of streaming structured data and HTML</a></li>
as discussed, I think these are more useful.

2021-01-29 15:11 UTC, rachelandrew commented on files/en-us/web/api/textencoderstream/index.html
> +  <li><a href="https://streams.spec.whatwg.org/demos/">Examples of streaming structured data and HTML</a></li>
and as mentioned on the other one checked this approach with Chris who is happy with this. Ultimately if Google want me to spend time building fully worked examples that's cool (and quite fun!) however it will then impact the number of APIs I can document. So it seems as if, where there are solid examples, linking to them means we can cover more stuff in my time.

2021-02-02 18:32 UTC, jpmedley approved these changes

2021-02-02 18:32 UTC, merged