Fix placement of periods
mdn/content pull request #16279
Opened 2022-05-20 22:49 UTC by de-oz

#### Summary

Firstly, a period is moved outside the link, as it shouldn't be a part of it. Secondly, a period is removed from the end of the list item under the "Setting values" subsection to make it consistent with other adjacent list items. Also the blank line between the two sentences contained in that list item is removed to match the display on the actual website. Lastly, a period at the end of the first list item under the "See also" section is also removed for the sake of consistency. Note that the last mentioned problem is present on many pages, for the most part there are no periods at the end of the list items across the website below the "See also" section, but there are also many cases where a period is inconsistently included in the same way as here. Please let me know if that should be fixed or left as it is.

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-21 02:05 UTC, OnkarRuikar commented
I think we need to remove `;` and `.` from numbered lists as well.

2022-05-23 14:38 UTC, jpmedley requested changes
Thank you for your help. If you'll indulge us a bit more, a slightly different solution is called for.

2022-05-23 22:01 UTC, de-oz commented on files/en-us/web/api/htmlelement/dataset/index.md
> +  converted into `data-example="null"`
Done!

2022-05-23 22:33 UTC, de-oz commented
I've completed the requested changes. Additionally I noticed and removed spaces around equals sign between a tag attribute and its value.

2022-05-24 14:02 UTC, jpmedley approved these changes

2022-05-24 14:08 UTC, merged