Options description of toLocaleString()
mdn/content pull request #16295
Opened 2022-05-21 08:30 UTC by SaurabhCha

Issue with "Number.prototype.toLocaleString()": needs description of all the options #11174
Issue: There's no description of all the options.
Link: https://github.com/mdn/content/issues/11174

Changes: I have added all the options which are available for it.

#### Summary

Add available options after research and trying everything myself.

#### Motivation

It will allow users to see all the possible option values which weren't available earlier.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-21 08:33 UTC, SaurabhCha commented
@teoli2003 Please review the PR.
And also please let me know if anything else is required. Thanks.

2022-05-25 19:24 UTC, wbamberg submitted a review, later dismissed
Thanks for the PR, @SaurabhCha ! I think this should appear under the "Parameters" heading of the "Syntax" section, as they do for the constructor page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters .

2022-05-29 15:22 UTC, SaurabhCha commented
@wbamberg Thank you for letting me know! I will make the changes.

2022-05-31 17:44 UTC, SaurabhCha commented
Hi @wbamberg, I have made the required changes. Please let me know if anything else is required. Thanks!

2022-06-02 10:14 UTC, teoli2003 requested changes
This is really good and almost ready to be merged. I've added a few minor requests. Sorry for the delay.

2022-06-02 10:14 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
> -
The empty line here is necessary. Can you re-add it?

2022-06-02 10:14 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
>  entirely implementation dependent.
I would add an entry for `locales` like `options`:
```suggestion
entirely implementation-dependent.

- `locales` {{optional_inline}}
  - : A string containing the {{Glossary("locale")}} to convert too.
```

2022-06-02 10:14 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
>  `options` arguments, the locale used and the form of the string returned are
On line 29 above replace _arguments_ by _parameters_.

2022-06-02 10:14 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
>  `options` argument:
We use parameter (and no more argument)
```suggestion
`options` parameter:
```

2022-06-02 16:29 UTC, SaurabhCha commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
> -
Added. Thanks

2022-06-02 16:32 UTC, SaurabhCha commented
@teoli2003 I have made the changes. Please let me know if I missed anything or other changes are required. Thanks.

2022-06-02 20:29 UTC, teoli2003 approved these changes

2022-06-09 02:01 UTC, SaurabhCha commented
Hi @wbamberg, are any changes required?

2022-06-10 06:31 UTC, teoli2003 approved these changes
Let's merge this. Any more changes, if needed, can be done in follow-up PRs.

2022-06-10 06:34 UTC, merged

2022-06-10 06:34 UTC, teoli2003 commented
Overriding the test failure as this is not touching redirects at all.

Thanks a lot!

2022-06-11 05:59 UTC, wbamberg commented
Sorry to be slow reviewing this. This PR doesn't format the Markdown DL correctly:

<img width="730" alt="Screen Shot 2022-06-10 at 10 59 17 PM" src="https://user-images.githubusercontent.com/432915/173175304-85227209-5f91-438a-9a3b-231080580b38.png">

...so will need a follow-up.

2022-06-11 06:10 UTC, wbamberg commented
Never mind, it looks like https://github.com/mdn/content/pull/17176 fixed it already. :)