Created the file for Execution Context.
mdn/content pull request #16337
Opened 2022-05-22 16:25 UTC by ayushikolay

#### Summary
Concepts of Hoisting will be answered easily because all are based on the Execution Context.

#### Motivation
 To clear the concepts for the beginners 

#### Supporting details

#### Related issues

#### Metadata
 ✅ Fundamental Concept
- [ ] Adds a new document

2022-05-23 05:56 UTC, OnkarRuikar reviewed
Use of `var` is discouraged. 
Also refer https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables#when_to_use_const_and_when_to_use_let

2022-05-23 05:56 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
```suggestion
const n = 2;
```

2022-05-23 05:56 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +  var ans = num * num;
```suggestion
  const ans = num * num;
```

2022-05-23 05:56 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +var square4 = square(4);
```suggestion
const square4 = square(4);
```

2022-05-23 06:26 UTC, ayushikolay commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
I am using let in place of const. Is it valid?

2022-05-23 06:33 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
If you are not assigning any value to a variable after the declaration then keep it `const`.
[Refer the guidelines](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#declaring_variables)

2022-05-23 06:43 UTC, ayushikolay commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
Thank you, Since I was unable to apply your changes. I make it by myself. Please check.

2022-05-23 12:45 UTC, ayushikolay commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
@OnkarRuikar Can you please approve the same if it seems to be fine?

2022-05-23 13:23 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +var n = 2;
@ayushikolay final review and merge will be done by code owners: @dipikabh or @teoli2003.

2022-05-23 13:48 UTC, teoli2003 requested changes
I found it very difficult to read + I adapted it to our structure.

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +title: Execution Context
```suggestion
title: Execution context
```

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +slug: Glossary/Execution Context
```suggestion
slug: Glossary/Execution_context
```

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +
I don't think this brings much in the understanding of an execution context.

```suggestion
```

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +2. Function(s) are scanned and are made available(Memory Creation Phase).
Let's keep hoisting in its glossary entry, and keep the entry here for execution context:
```suggestion

## See also

- {{glossary("Hoisting")}} 
```

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +
```suggestion
const n = 2;  // n is available to the global execution context

function square(num) { // the square function creates its own execution context, when num is declared
  const ans = num * num; // ans is only available to the function execution context
  return ans;
}

const square2 = square(n); // square2 is available to the global execution context
const square4 = ans; // ans is undefined as it was defined in another execution context

```

2022-05-23 13:48 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +Everything in JavaScript happens/executes inside **Execution Context**.
We want a _definition_  of an execution context here.
```suggestion
An **execution context** is the environment in which Javascript code executes. It contains the information that links a variable name with the actual variable storing data, either inside the execution context, if they are declared in it, or outside it if not. The binding of the {{jsxref("this")}} reference is also done in the execution context.

When running, the JavaScript engine initially creates the _global execution context_, then a new context is created for each function or `eval` call.

Variables created using `let` and constants are available in the _current_ execution context only, while variables created using `var` are _hoisted_ to the _global_ execution context and available everywhere, when not hidden by another declaration.
```

2022-05-24 03:57 UTC, wbamberg commented
I'd be interested to know how this relates to https://developer.mozilla.org/en-US/docs/Glossary/Scope , as much of the content of this article seems to be about something I'd call scope.

2022-05-24 05:36 UTC, teoli2003 commented
Execution context is basically scope + the way `this` is bound.

You are right we should make this clearer and link both pages.

2022-05-24 06:36 UTC, teoli2003 requested changes

2022-05-24 06:36 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +An **execution context** is the environment in which Javascript code executes. It contains the information that links a variable name with the actual variable storing data, either inside the executio
```suggestion
An **execution context** is the environment in which Javascript code executes. It consists of the {{glossary("scope")}}, the information that links a variable name with the actual variable storing data, and of the binding of the {{jsxref("this")}} reference, the object `this` refers to.
```

2022-05-24 06:36 UTC, teoli2003 commented on files/en-us/glossary/Execution Context/index.md
> +- {{glossary("Hoisting")}}
```suggestion
- {{glossary("Hoisting")}} 
- {{glossary("Scope")}}
```

2022-05-24 06:37 UTC, teoli2003 commented
Note that the name of the file must not have a space in it, but a `_` instead.

2022-05-24 06:56 UTC, OnkarRuikar commented on files/en-us/glossary/Execution Context/index.md
> +An **execution context** is the environment in which Javascript code executes. It contains the information that links a variable name with the actual variable storing data, either inside the executio
> the information that links a variable name with the actual variable storing data

Can we say "the information that links a variable name to the location storing the data"?

2022-05-24 12:36 UTC, ayushikolay commented
Hi @teoli2003, I tried to explain the whole execution context with the help of diagrams. But, unfortunately, I am unable to create a sub-table. If you go through the changes you will get to know(Please don't see the Preview first) what I have tried to explain.
Can you please make the necessary changes so that it can also be visible in the preview?

2022-05-24 18:59 UTC, wbamberg commented on files/en-us/glossary/Execution_Context/index.md
> +Variables created using `let` and constants are available in the _current_ execution context only, while variables created using `var` are _hoisted_ to the _global_ execution context and available ev
> Variables created using `let` and constants are available in the _current_ execution context only

Is this a statement about scope or about execution context?

```js
function f() {
  {
    let x = 1;
    x++;
  }
  console.log(x);  // error
}

f();
```

Please forgive me if I am confused, but from my reading you only get one execution context in this function, but you get 2 scopes, and of course the variable here is only available in the block scope, not the whole function.

> variables created using `var` are _hoisted_ to the _global_ execution context and available everywhere, when not hidden by another declaration.

Again forgive me if I am confused but this does not seem to be correct?

```
f();
console.log(x); // error

function f() {
  var x = 1;
  console.log(x);
}
```

2022-05-24 19:17 UTC, ayushikolay commented
@wbamberg, I have tried to explain it diagrammatically. Please don't go through the preview. First, go through the edit section.

2022-07-02 09:54 UTC, Josh-Cena reviewed
Conceptually, the content is _correct_, but I have to admit I'm not educated enough to tell if it sufficiently explains every aspect of execution context. For example, I'll be more interested in knowing how `this` is bound in different scenarios than the underlying memory management. (We are here to document the language, not the implementation, so the technical details don't matter. We can even adopt the spec's "Environment Record" model.)

Also, should this be "glossary" or "guide"/"references"? I'm inclined to put this under tutorials > advanced.

2022-08-12 15:20 UTC, ayushikolay commented
@Josh-Cena : I am thinking about the 'this' part and trying to figure it out.
But, just giving example of Hoisting.

Let's take the example of Hoisting:
1. Variable declarations are scanned and are made undefined(if it is var, otherwise it will thrown reference error).
2. Function declarations are scanned and are made available

It is due to the Execution Context, the variable name and function is hoisted because of allocation in memory due to Execution Context.

I hope this is fine. Thinking about 'this' as as well.

Also, you can put this under tutorials > advanced.

2022-08-12 16:51 UTC, ayushikolay commented
If you want to get clear understanding then please put a debugger in the functions and the entire code. You will see the whole phase of Execution Context.

Code:
var x = 1;
a();
b();
console.log(x);

function a() {
    var x = 10;
    console.log(x);
}

function b() {
    var x = 100;
    console.log(x);
}

2022-08-14 09:46 UTC, ayushikolay commented
> Conceptually, the content is _correct_, but I have to admit I'm not educated enough to tell if it sufficiently explains every aspect of execution context. For example, I'll be more interested in knowing how `this` is bound in different scenarios than the underlying memory management. (We are here to document the language, not the implementation, so the technical details don't matter. We can even adopt the spec's "Environment Record" model.)
> 
> Also, should this be "glossary" or "guide"/"references"? I'm inclined to put this under tutorials > advanced.

@Josh-Cena , the value of `this` is window, in the Global Context. But, it's value may be different in every function call.

2022-09-28 00:26 UTC, estelle commented on files/en-us/glossary/Execution_Context/index.md
> +<img width="557" alt="Screenshot 2022-08-14 at 2 13 02 PM" src="https://user-images.githubusercontent.com/41745320/184529394-3a29808a-562c-4668-a2d3-d87e150e1e94.png">
the alternative text cannot be the image file name. It should be concise text explaining what the image conveys should the image not load or should the user otherwise not be able to see the image.

All the images in this file need better `alt` attribute content.

2022-09-28 00:27 UTC, estelle commented on files/en-us/glossary/Execution_Context/index.md
> +
```suggestion
```

2022-09-28 19:49 UTC, ayushikolay commented on files/en-us/glossary/Execution_Context/index.md
> +<img width="557" alt="Screenshot 2022-08-14 at 2 13 02 PM" src="https://user-images.githubusercontent.com/41745320/184529394-3a29808a-562c-4668-a2d3-d87e150e1e94.png">
@estelle Thank you!

2022-10-14 15:40 UTC, dipikabh commented
- This PR seems like an excellent example where one of the reviewers can take up the responsibility for getting this PR closer to landing by assigning themselves as an "Assignee".

- A consensus is needed about where this content should live. Going by the glossary page for [Hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting), it looks like "Execution context" too can be a page in glossary.

2022-10-14 16:02 UTC, dipikabh requested changes

2022-10-14 16:02 UTC, dipikabh commented on files/en-us/glossary/Execution_Context/index.md
> +#### Example:
```suggestion
## Examples
```

2022-10-14 16:10 UTC, dipikabh commented on files/en-us/glossary/Execution_Context/index.md
> +### Components of Execution Context:
Consider changing the four headings below to normal text and state them as numbered steps, something like:

```suggestion
The components of execution context include:
1. Memory component
2. Code component
3. Deletion of execution context
```
...and then describe each component

Headings should not contain punctuations and should not be complete sentences

2022-10-14 16:17 UTC, Josh-Cena requested changes
Theoretically, I would be the one championing this PR because I should have the most domain knowledge; practically, I'm not really willing to because (a) the editorial style diverges too much from the MDN style and I'm not really willing to invest much time fixing every single bit (I would be better off closing this and re-writing everything myself) (b) I think it doesn't touch on the most important aspect, which is the language model. It focuses too much on the technical details of how it's implemented in the engine, but too little on what actually counts as the execution context. I have already asked for more information, specifically about this `this` context, which everyone agrees should be the core concern here if we are to address https://github.com/mdn/content/issues/5006. Unless I see significant changes to both writing style and content (possibly with the help of someone else), I will be blocking this PR; but I'm happy to re-review it at any time.

2022-10-14 23:38 UTC, estelle commented
I think a nice "glossary" entry would be line 1-32, with the addition of the see also, line 84+. The rest of this doc is good, but TMI for a brief glossary post and should probably be in an article about execution context, which is important.

2022-10-15 00:00 UTC, Josh-Cena commented
Yes, I'll prefer the bulk of this to be _somewhere_ (I can check later) in the JS docs

2022-10-30 16:58 UTC, Josh-Cena commented
Hi @ayushikolay, thanks for the PR and the effort put into this! Unfortunately, the page's style, typography, and content still deviates too much from our conventions. The editors' time is limited and we cannot help you fix every single place where we think it's off. The changes are minor, but with tens of them, the effort to review this doesn't scale. It looks like others are okay to close this one—as such, I will be the one to push the button. Hope you can continue to pick something that's more approachable to work on.

2022-10-30 16:58 UTC, closed without merging