fix fixable flaws in web/api/webrtc_api/
mdn/content pull request #1639
Opened 2021-01-22 20:05 UTC by peterbe

Note, I had to use the https://github.com/mdn/yari/pull/2660 branch to be able get this to work. 
The command I used, in `yari`, was:
```
BUILD_FIX_FLAWS=true BUILD_FOLDERSEARCH=web/api/webrtc_api yarn build
```

2021-01-22 20:09 UTC, peterbe commented
@nschonni if you have a minute can you check too?

2021-01-22 20:23 UTC, jpmedley requested changes

2021-01-22 20:23 UTC, jpmedley commented on files/en-us/web/api/webrtc_api/connectivity/index.html
> + <dd>A host candidate is one for which its {{domxref("RTCIceCandidate/address", "ip")}} address is the actual, direct IP address of the remote peer.</dd>
```suggestion
 <dd>A host candidate is one for which its IP {{domxref("RTCIceCandidate.address", "address")}} is the actual, direct IP address of the remote peer.</dd>
```

2021-01-22 20:23 UTC, jpmedley commented on files/en-us/web/api/webrtc_api/signaling_and_video_calling/index.html
> +<p>Once the <code>RTCPeerConnection</code> has been created, we request access to the user's camera and microphone by calling {{domxref("MediaDevices.getUserMedia()")}}, which is exposed to us throug
```suggestion
<p>Once the <code>RTCPeerConnection</code> has been created, we request access to the user's camera and microphone by calling {{domxref("MediaDevices.getUserMedia()")}}, which is exposed to us through the {{domxref("MediaDevices/getUserMedia")}} method. When this succeeds, fulfilling the returned promise, our <code>then</code> handler is executed. It receives, as input, a {{domxref("MediaStream")}} object representing the stream with audio from the user's microphone and video from their webcam.</p>
```

2021-01-22 20:23 UTC, jpmedley commented on files/en-us/web/api/webrtc_api/taking_still_photos/index.html
> +<p>You can, if needed, restrict the set of permitted video sources to a specific device or set of devices. To do so, call {{domxref("MediaDevices/enumerateDevices")}}. When the promise is fulfilled w
```suggestion
<p>You can, if needed, restrict the set of permitted video sources to a specific device or set of devices. To do so, call {{domxref("MediaDevices.enumerateDevices")}}. When the promise is fulfilled with an array of {{domxref("MediaDeviceInfo")}}  objects describing the available devices, find the ones that you want to allow and specify the corresponding {{domxref("MediaTrackConstraints.deviceId", "deviceId")}} or <code>deviceId</code>s in the {{domxref("MediaTrackConstraints")}} object passed into {{domxref("MediaDevices.getUserMedia", "getUserMedia()")}}.</p>
```

2021-01-22 20:23 UTC, jpmedley commented on files/en-us/web/api/webrtc_api/taking_still_photos/index.html
> + <li>{{domxref("MediaDevices/getUserMedia")}}</li>
```suggestion
 <li>{{domxref("MediaDevices.getUserMedia")}}</li>
```

2021-01-22 20:42 UTC, nschonni approved these changes

2021-01-22 20:42 UTC, nschonni commented on files/en-us/web/api/webrtc_api/build_a_phone_with_peerjs/build_the_server/index.html
> +<p><img alt="A cream background with the words 'phone a friend' in bold, dark green font as the heading. 'Connecting...' is immediately below that and 'please use headphones!' below that. Following o
Yup, looks like the "bad" characters are striped off now. Not sure if replacing them vs. removing entirely, but all these ones are all junk names anyway

2021-01-22 21:41 UTC, peterbe commented
So, unfortunately, we're still suffering from https://github.com/mdn/yari/issues/2520
The code that fixes the value in `{{domxref(...THIS...)}}` isn't working as it should. 
But as pointed out here: https://github.com/mdn/yari/pull/2551#pullrequestreview-569561937 we need to treat `domxref` differently from other xref macros. Annoying. 

@jpmedley I manually fixed the places where it should have been a `.` instead of the `/`. And then I just directly committed your suggestions.

2021-01-26 15:17 UTC, peterbe commented
@jpmedley ping r?

2021-02-03 17:10 UTC, peterbe commented
@jpmedley ping

2021-02-04 15:08 UTC, jpmedley requested changes

2021-02-04 15:08 UTC, jpmedley commented on files/en-us/web/api/webrtc_api/connectivity/index.html
> + <dd>A host candidate is one for which its {{domxref("RTCIceCandidate.address", "ip")}} address is the actual, direct IP address of the remote peer.</dd>
```suggestion
 <dd>A host candidate is one for which its {{domxref("RTCIceCandidate.address", "ip address")}} is the actual, direct IP address of the remote peer.</dd>
```

2021-02-04 16:59 UTC, peterbe commented
This now too rotten and too many merge conflicts. I looked at a couple of pages and the diffs were way too difficult for me to spend the time on.

2021-02-04 16:59 UTC, closed without merging