Major: re-wrote code descriptions
mdn/content pull request #16500
Opened 2022-05-22 21:20 UTC by seumoo

- Changed "var" to "let".
- Re-wrote code descriptions using lists, referencing source files, adding additional comments in code samples.
- Additional code sample was added to explain invocation. Sample code was tested  via developer console from the live sample the doc provides. 
- This is an initial draft to make the code example clearer - may need additional revamping.

#### Summary
Re-wrote code descriptions to be clearer. Added in additional code samples to explain invocation and comments. 

#### Motivation
The original doc was not formatted well and a bit confusing. It's not obvious how the samples worked and streaming wasm was hard to understand.

#### Supporting details
None

#### Related issues
None

#### Metadata
- [x] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-22 21:39 UTC, seumoo commented
My code comments says:
"content for index 1 is null; content for index 2 is null"

The indexes should be 0 and 1 instead 😞

2022-05-23 05:03 UTC, OnkarRuikar commented
I think we need to include https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/table2.wat also in the example. As it is a readable code and can be show in a code snippet on the page.

2022-05-23 19:32 UTC, seumoo commented
> I think we need to include https://github.com/mdn/webassembly-examples/blob/master/js-api-examples/table2.wat also in the example. As it is a readable code and can be shown in a code snippet on the page.

I agree! I will add this Wasm code to the page and move it's description as well.

2022-05-23 23:18 UTC, wbamberg requested changes
Thanks for your PR, @seumoo ! I had a few suggestions.

2022-05-23 23:18 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
>  ```
Again this is tricky because we're doing two things here:
- instantiating the module
- logging the results

It would be very nice to be able to talk about what the WebAssembly module does before the console.log statements. So perhaps we should split this code block too?

````
Next, we load and instantiate a WebAssembly module using the {{jsxref("WebAssembly.instantiateStreaming()")}} method:

```js
const instantiating = WebAssembly.instantiateStreaming(fetch('table2.wasm'), importObject);
```

The `table2.wasm` module contains two functions, one returning 42 and one returning 83. It stores the functions in elements 0 and 1 of the imported table.

Once the module is instantiated we can call the functions in the table:

```js
instantiating.then( obj => {
  console.log(tbl.length);
  console.log(tbl.get(0)());    // 42
  console.log(tbl.get(1)());    // 83
});
```

````
?

2022-05-23 23:18 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
> +The content for indexes 1 and 2 are now callable [Exported WebAssembly Functions](/en-US/docs/WebAssembly/Exported_functions), which are called to change the index's content values. To call the wasm
I don't think the functions "change the index's content values" - they just return the values to the caller. So when you do `console.log(tbl.get(0)());` you're calling the function at index 0 and logging the thing it returned. 

As far as I can tell this is not really any different from anywhere else you might store a function, for example:

```
function hello() {
   return "hello!";
}

const array = [hello];

console.log(array[0]()); // "hello!"
```

....and it's just equivalent to:

```
function hello() {
   return "hello!";
}

const array = [hello];
const helloFunction = array[0];

console.log(helloFunction()); // "hello!"
```

In just the same way, we could replace this example code:

```js
console.log(tbl.get(0)());
```

...with this:

```js
const fn1 = tbl.get(0);
console.log(fn1());
```

So I think if we want to make a point of the caller adding `()`, we might just say something like:

```
The items at indexes 0 and 1 of the table are functions, so to call them, note that we must add the function invocation operator after the `get()` call.
```

2022-05-24 02:05 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
> +elements. The WebAssembly Table is created and accessed in JavaScript while also visible and callable inside a wasm instance.
Makes sense. I've updated the suggestion.
Nitpick: As per https://webassembly.org/ , the abbreviation has capital "W" in it. So, unless it's a file extension we need to use "Wasm" everywhere. thoughts?

2022-05-24 02:13 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
> +elements. The WebAssembly Table is created and accessed in JavaScript while also visible and callable inside a wasm instance.
Yeah. I wasn't sure about the capitalization, but it seems like "Wasm" is better. I prefer "WebAssembly" just because "Wasm" is so ugly. But I can appreciate that that's a personal thing :).

2022-05-24 02:19 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
> +In `table2.html`, a `WebAssembly.Table()` is instantiated with the following:
> we create a `Table` is instantiated with the following code

Doesn't sound right.

How about this?
```suggestion
In `table2.html`, we create a `Table` using following code: 
```

2022-05-24 02:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/webassembly/table/table/index.md
> +In `table2.html`, a `WebAssembly.Table()` is instantiated with the following:
Almost! But you need a "the" in between "using" and "following" :).

2022-05-28 19:04 UTC, seumoo commented
I revised the doc based on all comments. For some reason, some comments were on different commit branches with read-only access. Thank you for all the feedback and clear explanations!

2022-06-23 19:30 UTC, wbamberg approved these changes
👍 thank you for your contribution @seumoo , and I'm so sorry to take such a long time to re-review this.

2022-06-23 19:30 UTC, merged