Update index.md
mdn/content pull request #16607
Opened 2022-05-23 15:34 UTC by scramlo

The current iteration of this document is misleading to developers regarding the use of `will-change` My updated version utilizes the latest definition and warning used in the `will-change` [MDN spec](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change).

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-02 14:19 UTC, dipikabh requested changes
Thanks! You might want to make these changes on https://developer.mozilla.org/en-US/docs/Web/CSS/will-change page as well.

2022-06-02 14:19 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +The CSS [`will-change`](/en-US/docs/Web/CSS/will-change) property hints to browsers how an element is expected to change. Browsers may set up optimizations before an element is actually changed. Thes
```suggestion
The CSS [`will-change`](/en-US/docs/Web/CSS/will-change) property hints to browsers how an element is expected to change. Browsers may set up optimizations before an element is actually changed. These kinds of optimizations can increase the responsiveness of a page by doing potentially expensive work before it is actually required.
```

2022-06-02 14:19 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +> **Warning:** `will-change` is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems.
```suggestion
> **Warning:** `will-change` is intended to be used as a last resort to try to deal with existing performance problems. It should not be used to anticipate performance problems.
```

2022-06-08 21:14 UTC, estelle commented on files/en-us/learn/performance/css/index.md
> +> **Warning:** `will-change` is intended to be used as a last resort to try to deal with existing performance problems. It should not be used to anticipate performance problems.
```suggestion
> **Note:** `will-change` is intended to be used as a last resort to try to deal with existing performance problems. It should not be used to anticipate performance problems.
```

2022-06-08 21:14 UTC, estelle approved these changes

2022-06-09 09:13 UTC, dipikabh approved these changes

2022-06-09 09:13 UTC, merged

2022-06-09 09:14 UTC, dipikabh commented
Congratulations @scramlo on landing your first PR in MDN Web Docs! 🎉 Welcome aboard.