Update Node Iterator Docs
mdn/content pull request #16639
Opened 2022-05-24 21:39 UTC by tshibley

#### Summary
Small update, just moving the parameters into the correct section + adding the return value for the `createNodeIterator` docs

#### Motivation
Just fixing a small section issue

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-25 01:56 UTC, OnkarRuikar commented on files/en-us/web/api/document/createnodeiterator/index.md
> +### Return value
```suggestion
### Return value

```

2022-05-25 01:58 UTC, OnkarRuikar commented on files/en-us/web/api/document/createnodeiterator/index.md
> +The `Document.createNodeIterator()` creator method returns a newly created [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
```suggestion
The `Document.createNodeIterator()` method returns a newly created [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
```

2022-05-25 05:33 UTC, teoli2003 requested changes
Thanks. Some small changes and we can merge this.

2022-05-25 05:33 UTC, teoli2003 commented on files/en-us/web/api/document/createnodeiterator/index.md
> +The `Document.createNodeIterator()` method returns a newly created [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
```suggestion
The **`Document.createNodeIterator()**` method returns a new [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
```

2022-05-25 05:36 UTC, OnkarRuikar commented on files/en-us/web/api/document/createnodeiterator/index.md
> +The `Document.createNodeIterator()` method returns a newly created [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
**`Document.createNodeIterator()`** 
bold and code got mixed

2022-05-25 05:40 UTC, teoli2003 commented on files/en-us/web/api/document/createnodeiterator/index.md
> +The `Document.createNodeIterator()` method returns a newly created [`NodeIterator`](/en-US/docs/Web/API/NodeIterator) object.
Ooops, fixed.

2022-05-26 06:33 UTC, teoli2003 approved these changes
👍

2022-05-26 06:42 UTC, merged

2022-05-26 06:42 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: