<input type="date"> remove "major problem" note from Handling browser support section
mdn/content pull request #16653
Opened 2022-05-25 07:50 UTC by techeverri

#### Summary

The browser support for `<input type="date">` shows supported everywhere except Internet Explorer. So having a note that says "As mentioned, the major problem with date inputs is browser support" doesn't make sense.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#handling_browser_support

#### Motivation

What's described should be consistent with the browsers compatibility table

🔗 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#browser_compatibility

<img width="814" alt="image" src="https://user-images.githubusercontent.com/3720424/170209676-1c484713-a31b-46de-aceb-cec13fdbb730.png">

I don't see a "major problem" in the compatibility section hence I propose removing that sentence

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-25 08:54 UTC, teoli2003 commented
As browser support is no more a problem, shouldn't we remove the whole paragraph, _Handling browser support_?

2022-05-25 09:46 UTC, plvaldes commented
The [Using date inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#using_date_inputs) section also mentions the limited browser support. And in general, if you go through the docs, there is a few warnings about the possibility of the browser not supporting the `<input type="date">`, which can be a bit misleading

2022-05-25 10:06 UTC, techeverri commented
> As browser support is no more a problem, shouldn't we remove the whole paragraph, _Handling browser support_?

I think describing what to expect when using for example Internet Explorer and how to work around it makes sense. I would suggest to keep "Handling browser support"

> The [Using date inputs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#using_date_inputs) section also mentions the limited browser support. And in general, if you go through the docs, there is a few warnings about the possibility of the browser not supporting the `<input type="date">`, which can be a bit misleading

I agree, we should remove any reference that implies that the feature doesn't have good browser support because that is not consistent with the browser compatibility table since the feature is supported in most browsers.

2022-05-25 17:56 UTC, wbamberg commented
> As browser support is no more a problem, shouldn't we remove the whole paragraph, _Handling browser support_?

I guess it depends how much we still care about IE. Unfortunately (but justifiably) AFAIK current consensus is still to care, so I guess we need to keep this section.

2022-05-25 17:57 UTC, wbamberg requested changes
Thanks @techeverri ! Nice update. I had a few suggestions to keep the flow of the doc after these changes

2022-05-25 17:57 UTC, wbamberg commented on files/en-us/web/html/element/input/date/index.md
> +Date inputs sound convenient — they provide an easy interface for choosing dates, and they normalize the data format sent to the server regardless of the user's locale.
This sentence, especially "sound convenient" only really makes sense when set against the next sentence - there's an implicit "...but..." being set up which is no longer paid off.

I would either omit this sentence or change it like this:

```suggestion
Date inputs provide an easy interface for choosing dates, and they normalize the data format sent to the server regardless of the user's locale.
```

2022-05-25 17:57 UTC, wbamberg commented on files/en-us/web/html/element/input/date/index.md
> +In this section, we'll look at basic and then more complex uses of `<input type="date">`, and offer advice on mitigating browser support issues later (see [Handling browser support](#handling_browser
Similarly:

```suggestion
In this section, we'll look at basic and then more complex uses of `<input type="date">`.
```

2022-05-25 23:54 UTC, techeverri commented
Suggestions applied. Thanks for the review @wbamberg 👍

2022-05-26 00:53 UTC, wbamberg approved these changes
👍 looks great, thank you @techeverri !

2022-05-26 00:53 UTC, merged