Removed var as per ES6 format.
mdn/content pull request #16692
Opened 2022-05-26 18:28 UTC by PrajwalBorkar

#### Summary

#### Motivation

Replacing usage of var with const or let as appropriate
#### Supporting details

[[https://docs.google.com/spreadsheets/d/1sl6gT8o-7yRPymZprwn6PNBRLQ6KNsKPFILLntsL7gk/edit#gid=0](https://github.com/mdn/content/pull/url)](url)
#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-05-26 18:43 UTC, wbamberg requested changes
Thanks for your PR! I had a couple of comments.

Also, please don't use "Fixes #16662" in the description, as that will auto-close the issue, while this is only part of the fix.

2022-05-26 18:43 UTC, wbamberg commented on files/en-us/web/api/authenticatorassertionresponse/index.md
> +    let assertionResponse = credentialInfoAssertion.response;
```suggestion
    const assertionResponse = credentialInfoAssertion.response;
```

I think?

2022-05-26 18:43 UTC, wbamberg commented on files/en-us/web/api/audiotrack/enabled/index.md
> +  const audioTrackCommentary;
```suggestion
  let audioTrackMain;
  let audioTrackCommentary;
```

(you need to initialize `const` declarations right away.)

2022-05-29 21:34 UTC, rdotterer09 commented
-----BEGIN PGP PUBLIC KEY BLOCK----- 

Version: BCPG C# v1.7.0.0 

 

mI0EYpOu/AEEAL9AdcL31kjx1AbaGM192ac24LGufzMUEeZ4HOGIEsaC289pGb5X 

v6hTVyv1x0BCRP5Oo5X+8SzQukHum8RIpaG7pGJUlbZpKXjcYdQOY7Rddp54+w/H 

QPVswQqK6G5slm4UjONAMjjF4Nfsy6WrF2CoZc/1DcuQ/LkwxuNETdX9ABEBAAG0 

RTI4OTk5MDM0NTgyMTc2NzUxMjg2NjM3ODk0NDI1NTYxMjA0MTE2NTYxMjAzNSA8 

cmRvdHRlcmVyMDlAZ21haWwuY29tPoicBBABAgAGBQJik678AAoJEE1nDVrwIvQr 

+eIEAJiVeBVo5ledTWEhA1CXCxqb1hECZgfrBYAVJZBZKvBCJbuwlC1hwCRuDmzq 

G8eI6mcFNXL/WdMhfqgHnIAOsLEycXyQzcnV7h6GO5kMcOHmAU9KMOHAUPgf06u8 

I5hogL0YU86t475teoS17v0Z2bwTAlBlr5DW4XTLZZ4gKVPo 

=LISa 

-----END PGP PUBLIC KEY BLOCK-----

2022-05-30 05:28 UTC, teoli2003 approved these changes
👍

2022-05-30 17:27 UTC, wbamberg approved these changes
👍 thank you @PrajwalBorkar !

2022-05-30 17:27 UTC, merged

2022-05-30 17:31 UTC, PrajwalBorkar commented
> 👍 thank you @PrajwalBorkar !

I will fix the remaining issues also from the sheet.😄