Update index.md
mdn/content pull request #16719
Opened 2022-05-27 10:06 UTC by LIXiangChen

Added a note from https://www.w3.org/TR/css-font-loading-3/#font-face-load

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-27 17:16 UTC, wbamberg requested changes
Thanks for your PR, @LIXiangChen ! I had a suggestion, what do you think?

2022-05-27 17:16 UTC, wbamberg commented on files/en-us/web/api/fontface/load/index.md
> +
This bit seems strange now: "loads a font based on current object's constructor-passed requirements, including a location or source buffer" - "source buffer" I suppose means binary data, but then in the next paragraph we say it **does nothing** if it was given binary data.

What do you think about:

```suggestion
The **`load()`** method of the {{domxref("FontFace")}} interface requests and loads a font whose `source` was specified as a URL. It returns a {{jsxref('Promise')}} that resolves with the current `FontFace` object.

If the `source` for the font face was specified  as binary data, or the font {{domxref("FontFace/status", "status")}} property of the font face is anything other than `unloaded`, then this method does nothing.
```

Does that seem accurate to you?

2022-05-28 02:54 UTC, LIXiangChen commented on files/en-us/web/api/fontface/load/index.md
> +
Of course no problem. I didn't know if I had the right to make changes to the original text, so I simply added a paragraph copied from the W3C.

2022-05-28 02:56 UTC, wbamberg commented on files/en-us/web/api/fontface/load/index.md
> +
You can absolutely suggest changes to the text, we do it all the time :).

2022-05-28 02:57 UTC, wbamberg commented on files/en-us/web/api/fontface/load/index.md
>  ## Syntax
```suggestion
If the `source` for the font face was specified  as binary data, or the font {{domxref("FontFace/status", "status")}} property of the font face is anything other than `unloaded`, then this method does nothing.

## Syntax
```

2022-05-28 03:37 UTC, wbamberg approved these changes
👍 thank you, @LIXiangChen !

2022-05-28 03:40 UTC, merged