Move compat data into browser-compat key (webextensions subtree)
mdn/content pull request #16738
Opened 2022-05-28 09:34 UTC by sideshowbarker

Similar to https://github.com/mdn/content/pull/16737, but just for the `mozilla/add-ons/webextensions` subtree, this change, for these reasons:

- consistency with handling of BCD features in other existing docs
- streamlining out unnecessary repetition of BCD feature names
- in keeping with the principle of making use of frontmatter metadata to store data — BCD feature names - rather than having the BCD feature names in the prose body of documents

...this takes BCD feature names out of the arguments to the `Compat` macro, and moves those BCD feature names into the value of the `browser-compat` frontmatter metadata key.

I separated out these changes to the `webextensions` subtree into a different PR than https://github.com/mdn/content/pull/16737 because I’m not as familiar with the contents of these docs, so it seem prudent to ensure the changes get specific review from Web Extensions reviewers.

2022-05-30 03:37 UTC, rebloor requested changes

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/clipboard/index.md
> +{{WebExtExamples("h2")}}
This is something we started doing on an ad hoc basis some time ago, moving the examples above the compatibility table so the examples are more visible. So, as we making a change here:
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/commands/index.md
> +{{WebExtExamples("h2")}}
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/find/index.md
> +{{WebExtExamples("h2")}}
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/menus/index.md
>  {{WebExtExamples("h2")}}
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/pkcs11/index.md
> +{{WebExtExamples("h2")}}
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/search/index.md
> +{{WebExtExamples("h2")}}
```suggestion
{{WebExtExamples("h2")}}

{{Compat}}
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +{{Compat}}
`browser_style` refers to a property which is part of the [action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action), [browser_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action), [page_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action), [sidebar_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action), and [options_ui](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui)) manifest keys. It has no compatibility data of its own.
Perhaps we should replace the macro with:
```suggestion
For browser compatibility information refer to the browser compatibility sections of the [action](en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action#browser_compatibility), ([browser_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#browser_compatibility), [page_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action#browser_compatibility), [sidebar_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action#browser_compatibility), and [options_ui](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui#browser_compatibility) manifest keys.
```

2022-05-30 03:37 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +browser-compat: webextensions.browser_style
```suggestion
```

2022-06-01 21:45 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +For browser compatibility information refer to the browser compatibility sections of the [action](en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action#browser_compatibility), ([browser_actio
```suggestion
For browser compatibility information refer to the browser compatibility sections of the [action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action#browser_compatibility), [browser_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#browser_compatibility), [page_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action#browser_compatibility), [sidebar_action](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action#browser_compatibility), and [options_ui](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui#browser_compatibility) manifest keys.
```

2022-06-02 03:09 UTC, rebloor approved these changes

2022-06-02 03:10 UTC, merged

2022-06-02 03:10 UTC, rebloor commented
@sideshowbarker sorry for the delay, I have approved unmerged. Thanks!

2022-06-02 04:56 UTC, sideshowbarker commented
> @sideshowbarker sorry for the delay, I have approved and merged. Thanks!

Cheers — thanks!