Patch 3
mdn/content pull request #16747
Opened 2022-05-29 00:12 UTC by allan-bonadio

#### Summary
Made examples 2 & 3 more clear.
Found a number of other small things that could be improved or clarified.

#### Motivation
- First sentence described a detail rather than help with the main description.
- clarified syntax code
- clarified that finally() returns an identical promise
- removed some text that was just confusing

#### Supporting details

#### Related issues

#### Metadata
- [ ] Adds a new document
- [ x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-29 06:26 UTC, teoli2003 requested changes
This is already very good. I added some suggestions/corrections.

2022-05-29 06:26 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +The **`finally()`** method is called on a {{jsxref("Promise")}}.
```suggestion
The **`finally()`** method of a {{jsxref("Promise")}} schedules a function, the _callback function_, to be called when the promise is settled. Like `then()` and `catch()`, it immediately returns an equivalent {{jsxref("Promise")}} object, allowing to chain calls to a promise methods, an operation called _composition.
```

2022-05-29 06:26 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +   // will run after p is settled (fulfilled or rejected)
```suggestion
   // Code that will run after p is settled (fulfilled or rejected)
```

2022-05-29 06:26 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +with that value instead.
This change is incorrect I think. What about
```suggestion
Returns an equivalent {{jsxref("Promise")}} with its `finally` handler set to the specified function.
```

2022-05-29 06:26 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +- A `finally` call will chain through an equivalent to the orignal promise.
```suggestion
- A `finally` call will chain through an equivalent to the original promise.  
```

2022-06-01 03:31 UTC, OnkarRuikar reviewed
Got to to click complete. Ignore if not relevant anymore.

2022-06-05 23:57 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +p.finally(function onFinally() {
I went with the arrow function

2022-06-06 00:01 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +The **`finally()`** method is called on a {{jsxref("Promise")}}.
changed to almost the same

2022-06-06 00:01 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +   // will run after p is settled (fulfilled or rejected)
I adopted that wording, better

2022-06-06 00:03 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +with that value instead.
done

2022-06-06 00:04 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +- A `finally` call will chain through an equivalent to the orignal promise.
doh!  done

2022-06-06 00:04 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
>  p.finally(onFinally);
done

2022-06-06 00:05 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +p.finally(function onFinally() {
I changed it to an arrow function as per suggestion above

2022-06-06 00:06 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +   // will run after p is settled (fulfilled or rejected)
... will run after promise is settled...

2022-06-06 00:07 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +    will return a promise which will be resolved with `77`),
yeah, that's better wording.  used it.

2022-06-06 00:09 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +    promise which will be resolved with `2`.
done

2022-06-06 01:46 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +    (which will, again, return a promise which will be rejected with `88`),
done.  It's good I'm learning the lingo.

2022-06-06 01:47 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +    `Promise.reject(3).finally(() => {})` will return a promise
done

2022-06-06 01:50 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +> `finally` callback will reject the promise, which will, in that case,
will reject the returned promise with the reason `99`.

2022-06-06 01:51 UTC, allan-bonadio commented on files/en-us/web/javascript/reference/global_objects/promise/finally/index.md
> +    which will be rejected with `3`.
yup

2022-06-06 03:37 UTC, teoli2003 commented
Hi! Thanks for updating the PR. I don't exactly what's going on, but I don't see your changes. Have you pushed them here?

2022-06-07 18:06 UTC, allan-bonadio commented
> Hi! Thanks for updating the PR. I don't exactly what's going on, but I don't see your changes. Have you pushed them here?

sorry, never did a PR on github before.  Too many buttons and distractions, kindof confusing.  I updated the wrong branch.  Now it should be right.

2022-06-10 06:08 UTC, teoli2003 approved these changes
No worry, Git and GitHub feel different at the beginning, but work well once we are used to them.

This looks good to me. If we find more changes to be done, we can do this in follow-up PRs.

This is much better.

2022-06-10 06:08 UTC, merged

2022-06-10 06:09 UTC, teoli2003 commented
\o/