Abhiram patch
mdn/content pull request #16755
Opened 2022-05-29 05:42 UTC by gullapalli9482

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-05-29 05:44 UTC, gullapalli9482 commented
Hope I've followed the procedure properly

2022-05-29 05:57 UTC, teoli2003 requested changes
Thanks a lot. I have one open point (a `let` that may be a `const`), and a few adaptation of structure, but we are close to be able to land this.

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/learn/javascript/first_steps/a_first_splash/index.md
> +At this point we have a nicely implemented `checkGuess()` function, but it won't do anything because we haven't called it yet. Ideally we want to call it when the "Submit guess" button is pressed, an
Constructor is clearly wrong here.

```suggestion
At this point, we have a nicely implemented `checkGuess()` function, but it won't do anything because we haven't called it yet. Ideally, we want to call it when the "Submit guess" button is pressed, and to do this we need to use an **event**. Events are notifications about actions that happen in the browser — a button being clicked, a page loading, a video playing, etc. — in response to which we can run blocks of code. The parts of the browser that listen out for the event happening are called **event listeners**, and the blocks of code that run in response to the event firing are called **event handlers**.
```

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/getchanneldata/index.md
> +const nowBuffering = myArrayBuffer.getChannelData(channel);
The modern way of describing a syntaxvfor a method is this:
```suggestion
getChannelData(channel);
```

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/getchanneldata/index.md
> +   let nowBuffering = myArrayBuffer.getChannelData(channel);
I think this should be a `const`. Can you confirm/infirm this, @wbamberg ?

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/length/index.md
>  ```
No syntax section for properties. (Value below should be at level 2, not 3.

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/length/index.md
> +    let nowBuffering = myArrayBuffer.getChannelData(channel);
See above

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/numberofchannels/index.md
No syntax section for properties.

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/numberofchannels/index.md
> +    let nowBuffering = myArrayBuffer.getChannelData(channel);
See above.

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/samplerate/index.md
No syntax section for properties.

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/samplerate/index.md
> +    let nowBuffering = myArrayBuffer.getChannelData(channel);
See above

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffersourcenode/audiobuffersourcenode/index.md
> +const audioBufferSourceNode = new AudioBufferSourceNode(context, options)
```suggestion
new AudioBufferSourceNode(context, options)
```

2022-05-29 05:57 UTC, teoli2003 commented on files/en-us/web/api/audiobuffersourcenode/buffer/index.md
> +   let nowBuffering = myArrayBuffer.getChannelData(channel);
See above.

2022-05-29 09:42 UTC, gullapalli9482 commented on files/en-us/web/api/audiobuffer/length/index.md
>  ```
I didn't actually understand what you are trying to convey.

2022-05-29 21:11 UTC, rdotterer09 commented on files/en-us/web/api/audiobuffersourcenode/buffer/index.md
> +   let nowBuffering = myArrayBuffer.getChannelData(channel);
why are you trying to add audio to this contract?

2022-05-30 05:31 UTC, teoli2003 commented on files/en-us/web/api/audiobuffer/length/index.md
>  ```
We don't have a syntax section for properties (like we have for methods). You should:
1. Remove the whole `## Syntax` section (line 19-25)
2. Change the `### Value` line to `## Value`

Thank you!

2022-05-30 05:34 UTC, teoli2003 commented
There were some merge conflicts I resolved. I think this fixed most of the _Syntax_ sections that had to be removed. 😄

2022-05-30 15:58 UTC, gullapalli9482 commented
Is there something left for me to add on, if so please do let me know?

2022-05-30 16:51 UTC, wbamberg requested changes
Thanks for the update. There are still a few `let` declarations that should be `const`, and we should not remove "Syntax" for methods, only for properties.

> Hope I've followed the procedure properly

Please carefully review the instructions in https://github.com/mdn/content/issues/16662#issue-1248441427: if you want to work on this issue, please request access to the spreadsheet and put your name, in the spreadsheet, beside pages you are fixing. If you don't do this it becomes really difficult to coordinate the work: other people won't know that you are working on those pages, and they will waste their time filing PRs to fix pages that you have already fixed. Thanks!

2022-05-30 16:51 UTC, wbamberg commented on files/en-us/web/api/audiobuffer/getchanneldata/index.md
> -```
This is a method, not a property. For methods we **do** have a syntax section, @teoli2003 's comment about removing syntax sections only applies to properties.

2022-05-30 16:51 UTC, wbamberg commented on files/en-us/web/api/audiobuffer/numberofchannels/index.md
> +    let nowBuffering = myArrayBuffer.getChannelData(channel);
```suggestion
    const nowBuffering = myArrayBuffer.getChannelData(channel);
```

2022-05-30 16:51 UTC, wbamberg commented on files/en-us/web/api/audiobuffersourcenode/buffer/index.md
> +   let nowBuffering = myArrayBuffer.getChannelData(channel);
```suggestion
   const nowBuffering = myArrayBuffer.getChannelData(channel);
```

2022-05-30 16:51 UTC, wbamberg commented on files/en-us/web/api/audiobuffersourcenode/buffer/index.md
> +  let source = audioCtx.createBufferSource();
```suggestion
  const source = audioCtx.createBufferSource();
```

2022-05-30 16:53 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/a_first_splash/index.md
> +At this point, we have a nicely implemented `checkGuess()` function, but it won't do anything because we haven't called it yet. Ideally, we want to call it when the "Submit guess" button is pressed,
For this project I think it would be much better not to keep PRs limited to the `var`->`const`/`let` changes, and not to include any additional changes.

2022-05-30 17:09 UTC, gullapalli9482 commented on files/en-us/web/api/audiobuffer/getchanneldata/index.md
> -```
Done

2022-05-30 17:21 UTC, wbamberg approved these changes
👍 thank you @gullapalli9482 , this looks great!

2022-05-30 17:24 UTC, gullapalli9482 commented
I'll be adding the pull request to the google sheet once all reviews are done.

2022-05-30 17:37 UTC, wbamberg commented
> I'll be adding the pull request to the google sheet once all reviews are done.

Thank you @gullapalli9482 !

2022-05-31 16:41 UTC, gullapalli9482 commented
Anything else to be added @teoli2003

2022-06-01 06:23 UTC, teoli2003 approved these changes

2022-06-01 06:25 UTC, teoli2003 approved these changes

2022-06-01 06:59 UTC, merged