Support StorageArea.onChanged
mdn/content pull request #16873
Opened 2022-06-01 23:50 UTC by rebloor

#### Summary
This change addresses [Bug 1758475](https://bugzilla.mozilla.org/show_bug.cgi?id=1758475) *Support StorageArea.onChanged (onChanged on storage.local/sync/managed)*. While undertaking the change, noted the addition of the `session` storage area in Chrome, so added that. Also noted that the presentation of the methods in the storage areas referenced  `StorageArea` rather than the storage area name, so updated. In addition, made various edits.

BCD data in [Support for StorageArea.onChanged and Session #16450](https://github.com/mdn/browser-compat-data/pull/16450)

#### Metadata
This PR…
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-10 20:24 UTC, Rob--W requested changes

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/local/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
"if they have been implemented" can be removed from this local documentation.

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
> +When values are set, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.managed.onChanged")}} events fire.
Remove this. The storage is read-only, and the event is only provided for compatibility with the StorageArea interface.

In practice, Firefox never fires managed.onChanged because it reads the values on startup, and doesn't monitor the configuration for changes.

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/session/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
Remove "if they have been implemented". This is covered by the BCD table.

It's not necessary to mention onChanged at every `set` method; the event is fired whenever the storage is modified, whether with set, remove or clear.

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +browser.storage.StorageArea.onChanged.addListener(callback)
browser.storage.StorageArea -> storageArea, preceded by `let storageArea = browser.storage.local; // or sync, managed, session`

Or simply spell out:

```js
// local can also be sync, managed or session
browser.storage.local.onChanged.addListener(callback)
Etc...
```

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +    - `areaName`
areaName does not exist on StorageArea.onChanged

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +> **Note:** This API is based on Chromium's [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/#event-onChanged) API. This documentation is derived from [`storage.json`
```suggestion
> **Note:** This API is based on Chromium's [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/#event-StorageArea-onChanged) API. This documentation is derived from [`storage.json`](https://chromium.googlesource.com/chromium/src/+/master/extensions/common/api/storage.json) in the Chromium code.
```

2022-06-10 20:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +function logStorageChange(changes, area) {
```suggestion
function logStorageChange(changes) {
```

Remove area

2022-06-11 16:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/local/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
```suggestion
  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.local.onChanged")}} events fire.
```

2022-06-11 16:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
> +When values are set, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.managed.onChanged")}} events fire.
@Rob--W the Chrome documentation suggests that these events fire – should this be documented as a compatibility item?

2022-06-11 16:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/session/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
@Rob--W I was thinking it makes sense to mention these events on the basis that we don't know what order someone's reading the documentation in.

2022-06-11 16:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/session/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
```suggestion
  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you store a value, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.session.onChanged")}} events fire.
```

2022-06-11 17:03 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +browser.storage.StorageArea.onChanged.addListener(callback)
```suggestion
// local can also be sync, managed, or session
browser.storage.local.onChanged.addListener(callback)
```

2022-06-11 17:04 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +      - : `string`. The name of the storage area (`"local"`, `"managed"`, '"session"', or `"sync"`) where the changes occurred.
```suggestion
```

2022-06-11 17:06 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/sync/index.md
> +  - : Stores one or more items in the storage area. If the item exists, its value is updated. When you set a value, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebE
```suggestion
  - : Stores one or more items in the storage area. If the item exists, its value is updated.
```

2022-06-11 17:09 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
> +When values are set, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.managed.onChanged")}} events fire.
```suggestion

When values are set, if they have been implemented, the {{WebExtAPIRef("storage.onChanged")}} and {{WebExtAPIRef("storage.StorageArea.onChanged", "storage.managed.onChanged")}} events fire.
```

2022-06-11 17:19 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
> +## Events
@Rob--W Given your comments in https://github.com/mdn/content/pull/16873#discussion_r894854722 should I remove this too?

2022-06-11 17:32 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.md
> +## Events
Let's keep it. While Firefox doesn't monitor for changes, Chrome does, so the event is defined.

2022-06-11 17:38 UTC, Rob--W requested changes
Please mention the new StorageArea.onChanged event in the release notes of Firefox 101

2022-06-11 17:38 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +browser.storage.StorageArea.onChanged.removeListener(listener)
```suggestion
browser.storage.local.onChanged.removeListener(listener)
```

2022-06-11 17:38 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +browser.storage.StorageArea.onChanged.hasListener(listener)
```suggestion
browser.storage.local.onChanged.hasListener(listener)
```

2022-06-11 17:59 UTC, rebloor commented
Release notes done!

2022-06-11 18:25 UTC, rebloor commented
@Rob--W now with release notes!

2022-06-11 18:26 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/101/index.md
> +- Adds the [`session` module](https://w3c.github.io/webdriver-bidi/#module-session) including a partial implementation for the commands to globally subscribe ([`session.subscribe`](https://w3c.github
```suggestion
- Adds the [`session` module](https://w3c.github.io/webdriver-bidi/#module-session) including a partial implementation for the commands to globally subscribe ([`session.subscribe`](https://w3c.github.io/webdriver-bidi/#command-session-subscribe)) to and unsubscribe ([`session.unsubscribe`](https://w3c.github.io/webdriver-bidi/#command-session-unsubscribe)) from events, and the ability to create a direct WebDriver BiDi session ([`session.new`](https://w3c.github.io/webdriver-bidi/#command-session-new)) when not using WebDriver classic.
```

2022-06-11 18:27 UTC, Rob--W approved these changes

2022-06-11 18:27 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/101/index.md
> +- Addition of the {{WebExtAPIRef("storage.StorageArea.onChanged")}} event that enables you to listen for changes in content in the `local`,  `session`, and `sync` storage areas ({{bug(1758475)}}).
```suggestion
- Addition of the {{WebExtAPIRef("storage.StorageArea.onChanged")}} event that enables you to listen for changes in content in the `local` and `sync` storage areas ({{bug(1758475)}}).
```

storage.session has not been implemented yet.

2022-06-12 16:34 UTC, merged