Add wasm-unsafe-eval to CSP
mdn/content pull request #16943
Opened 2022-06-03 16:55 UTC by rebloor

#### Summary
This change add details about support for WebAssembly in the default extension CSP and addition of the 'wasm-unsafe-eval` directive to the `content_security_policy` manifest key for use in MV3 extensions.

#### Related issues
Find the documentation requested in [Bug 1766027](https://bugzilla.mozilla.org/show_bug.cgi?id=1766027) Decide on including 'wasm-unsafe-eval' in the default CSP of MV3 extensions

#### Metadata

This PR…
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-04 15:11 UTC, Rob--W requested changes

2022-06-04 15:11 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +  "extension_page": "wasm-unsafe-eval"
FYI this syntax is incorrect (as is the one that you used in the "default" CSP).

`script-src 'wasm-unsafe-eval'` would be the bare minimum.
This is however useless, since it doesn't allow regular scripts.
So in practice the most sensible minimum is

```
script-src 'self' 'wasm-unsafe-eval'
```

2022-06-04 15:11 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +Not applicable, use of WebAssembly is permitted by the [default CSP](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#default_content_security_policy).
The `wasm-unsafe-eval` directive is applicable to MV2 and MV3. It is recommended to use it if needed. It being part of the default CSP is just meant for backwards-compatibility. It may make sense to call out that it is included in the default CSP of MV2 extensions in Firefox for backwards-compatibility, but that it is still recommended to include it if the extension uses WebAssembly.

2022-06-04 15:11 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +- Allow a Manifest V3 extension to take advantage of [WebAssembly](/en-US/docs/WebAssembly) by including the `wasm-unsafe-eval` directive.
```suggestion
- Allow the extension to take advantage of [WebAssembly](/en-US/docs/WebAssembly) by including the `wasm-unsafe-eval` source in the `script-src` directive.
```

2022-06-04 15:11 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/102/index.md
> +- The 'wasm-unsafe-eval' directive has been added to the [content_security_policy](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) manifest key to enable a Manifest V
```suggestion
- With the introduction of support for the 'wasm-unsafe-eval' CSP keyword in Firefox ({{bug(1740263)}}), Manifest V3 extensions are now required to specify this keyword in the [content_security_policy](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) manifest key to use [WebAssembly](/en-US/docs/WebAssembly). For backwards-compatibility, Manifest V2 extensions can still use WebAssembly without the keyword ({{bug(1766027))}}).
```

2022-06-10 20:33 UTC, Rob--W requested changes
Almost ready.

2022-06-10 20:33 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +In Firefox 102 and later, `wasm-unsafe-eval` can be included in the [`content_security_policy`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) manifest.json key for
```suggestion
Since Firefox 102 and Chrome 103, `wasm-unsafe-eval` can be included in the [`content_security_policy`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) manifest.json key to enable the use of WebAssembly in extensions.
```

This is not MV3 specific. MV2 does have an exception in Firefox, which you've documented below.

2022-06-10 20:33 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +Extensions wishing to use [WebAssembly](/en-US/docs/WebAssembly) require `wasm-unsafe-eval`.
```suggestion
Extensions wishing to use [WebAssembly](/en-US/docs/WebAssembly) require `'wasm-unsafe-eval'` to be specified in the `script-src` directive.
```

wasm-unsafe-eval must be within single quotes, everywhere. And within backticks for code formatting.

2022-06-11 15:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +
```suggestion
```

2022-06-11 15:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +Manifest V2 extensions in Firefox can use WebAssembly without `wasm-unsafe-eval` in their CSP for backward compatibility. However, this behavior isn't guaranteed; see {{bug(1770909)}}. Extensions usi
```suggestion
Manifest V2 extensions in Firefox can use WebAssembly without `'wasm-unsafe-eval'` in their CSP for backward compatibility. However, this behavior isn't guaranteed; see {{bug(1770909)}}. Extensions using WebAssembly are therefore encouraged to declare `'wasm-unsafe-eval'` in their CSP.
```

2022-06-11 15:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +For Chrome, extensions cannot use WebAssembly in version 101 or earlier. In 102, extensions can use WebAssembly (the same behavior as Firefox 101 and earlier). From version 103, extensions can use We
```suggestion
For Chrome, extensions cannot use WebAssembly in version 101 or earlier. In 102, extensions can use WebAssembly (the same behavior as Firefox 101 and earlier). From version 103, extensions can use WebAssembly if they include `'wasm-unsafe-eval'` in the `content_security_policy` in the manifest key.
```

2022-06-11 16:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +- Allow the extension to take advantage of [WebAssembly](/en-US/docs/WebAssembly) by including the `wasm-unsafe-eval` source in the `script-src` directive.
```suggestion
- Allow the extension to take advantage of [WebAssembly](/en-US/docs/WebAssembly) by including the `'wasm-unsafe-eval'` source in the `script-src` directive.
```

2022-06-11 16:28 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +For backward compatibility, Manifest V2 extensions can use web assembly without the use of `wasm-unsafe-eval`. However, if the extension uses WebAssembly, inclusion of `wasm-unsafe-eval` is recommend
```suggestion
For backward compatibility, Manifest V2 extensions can use web assembly without the use of `'wasm-unsafe-eval'`. However, if the extension uses WebAssembly, the inclusion of `'wasm-unsafe-eval'` is recommended. See [WebAssembly
```

2022-06-11 16:30 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +This doesn't load the requested resource: it fails silently, and any object that you expect to be present from the resource is not be found. There are two main solutions to this:
```suggestion
This doesn't load the requested resource: it fails silently, and any object that you expect to be present from the resource is not found. There are two main solutions to this:
```

2022-06-11 16:34 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#webassembly) on the Content Security Policy page for more information.
```suggestion
For backward compatibility, Manifest V2 extensions can use web assembly without the use of `'wasm-unsafe-eval'`. However, if the extension uses WebAssembly, the inclusion of `'wasm-unsafe-eval'` is recommended. See [WebAssembly](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#webassembly) on the Content Security Policy page for more information.
```

2022-06-11 17:29 UTC, Rob--W approved these changes
A few changes and then it's good for merging.

2022-06-11 17:29 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +- Allow the extension to use `eval()` and similar features, by including `unsafe-eval` in the {{CSP("script-src")}} directive.
```suggestion
- Allow the extension to use `eval()` and similar features, by including `'unsafe-eval'` in the {{CSP("script-src")}} directive.
```

2022-06-11 17:29 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/content_security_policy/index.md
> +For backward compatibility, Manifest V2 extensions can use web assembly without the use of `'wasm-unsafe-eval'`. However, if the extension uses WebAssembly, the inclusion of `'wasm-unsafe-eval'` is r
```suggestion
For backward compatibility, Manifest V2 extensions can use WebAssembly without the use of `'wasm-unsafe-eval'`. However, if the extension uses WebAssembly, the inclusion of `'wasm-unsafe-eval'` is recommended. See [WebAssembly](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#webassembly) on the Content Security Policy page for more information.
```

2022-06-11 17:29 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/102/index.md
> +- With the introduction of support for the 'wasm-unsafe-eval' CSP keyword in Firefox ({{bug(1740263)}}), Manifest V3 extensions are now required to specify this keyword in the [content_security_polic
```suggestion
- With the introduction of support for the 'wasm-unsafe-eval' CSP keyword in Firefox ({{bug(1740263)}}), Manifest V3 extensions are now required to specify this keyword in the [content_security_policy](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy) manifest key to use [WebAssembly](/en-US/docs/WebAssembly). For backwards-compatibility, Manifest V2 extensions can still use WebAssembly without the keyword ({{bug(1766027)}}).
```

2022-06-11 17:45 UTC, rebloor commented
Thanks @Rob--W

2022-06-11 17:45 UTC, merged