Correct and expand documentation for the ImageDecoder API.
mdn/content pull request #16951
Opened 2022-06-03 22:15 UTC by dalecurtis

#### Summary
Corrects and expands the documentation for the ImageDecoder API.

#### Motivation
Helps developers and users understand the API better.

#### Supporting details
https://w3c.github.io/webcodecs/
https://w3c.github.io/webcodecs/samples/

I'm an author of the ImageDecoder API :)

#### Related issues
n/a

#### Metadata

- [x] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-04 05:43 UTC, teoli2003 requested changes
Thank you for the improvement, this is much better.

I've done technical suggestions to match our guidelines (and fix a few extra errors).

Unfortunately, there are a few places where the GitHub UI prevented me from directly adding the suggestion to the right place.

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/close/index.md
> +The **`close()`** method of the {{domxref("ImageDecoder")}} interface ends all pending work and releases system resources. Subsequent calls to `decode()` will throw an `InvalidStateError` exception.
Exceptions should not be described in the intro, but in a specific section:
```suggestion
The **`close()`** method of the {{domxref("ImageDecoder")}} interface ends all pending work and releases system resources.
```

and the exception section should be between _Return value_ and _Examples_ and be:
```

### Exceptions

- `InvalidStateError` {{domxref("DOMException")}}
  - : Thrown if the decoder is already closed.
 
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/imagedecoder/index.md
> +      - : A string containing the [MIME type](https://en.wikipedia.org/wiki/Media_type) of the image file to be decoded.
We have an internal link.

```suggestion
      - : A string containing the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the image file to be decoded.
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
>  ## Properties
On line 12, please change the incorrect `{{DefaultAPISidebar("WebCodecs API")}}` to `{{APIRef("WebCodecs API")}}`. Thank you.

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +  - : Indicates if the provided [mime type](https://en.wikipedia.org/wiki/Media_type) is supported for unpacking and decoding.
Create a new separate section (`## Static methods`) for static methods.

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +Given an {{HTMLElement("canvas")}} element:
```suggestion
Given a {{HTMLElement("canvas")}} element:
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +title: ImageDecoder.isTypeSupported
```suggestion
title: ImageDecoder.isTypeSupported()
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +{{securecontext_header}}{{DefaultAPISidebar("WebCodecs API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebCodecs API")}}
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +  - : Returns a {{jsxref("DOMString")}} reflecting the [mime type](https://en.wikipedia.org/wiki/Media_type) configured during construction.
```suggestion
  - : Returns a {{jsxref("DOMString")}} reflecting the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) configured during construction.
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +  - : Indicates if the provided [mime type](https://en.wikipedia.org/wiki/Media_type) is supported for unpacking and decoding.
```suggestion
  - : Indicates if the provided [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) is supported for unpacking and decoding.
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/imagedecoder/index.md
>  - `init`
On line 12, please change the incorrect {{DefaultAPISidebar("WebCodecs API")}} to {{APIRef("WebCodecs API")}}. Thank you.

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/decode/index.md
>      - `frameIndex`{{Optional_Inline}}
On line 13, please change the incorrect {{DefaultAPISidebar("WebCodecs API")}} to {{APIRef("WebCodecs API")}}. Thank you.

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/completed/index.md
>  {{securecontext_header}}{{DefaultAPISidebar("WebCodecs API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebCodecs API")}}
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/complete/index.md
>  {{securecontext_header}}{{DefaultAPISidebar("WebCodecs API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebCodecs API")}}
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/close/index.md
>  {{securecontext_header}}{{DefaultAPISidebar("WebCodecs API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebCodecs API")}}
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +The **`ImageDecoder.isTypeSupported()`** static method checks if a given [mime type](https://en.wikipedia.org/wiki/Media_type) can be decoded by the user agent.
```suggestion
The **`ImageDecoder.isTypeSupported()`** static method checks if a given [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) can be decoded by the user agent.
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +  - : The [mime type](https://en.wikipedia.org/wiki/Media_type) to check for decoding support.
```suggestion
  - : The [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) to check for decoding support.
```

2022-06-04 05:43 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/reset/index.md
>  {{securecontext_header}}{{DefaultAPISidebar("WebCodecs API")}}
```suggestion
{{securecontext_header}}{{APIRef("WebCodecs API")}}
```

2022-06-06 17:29 UTC, dalecurtis commented on files/en-us/web/api/imagedecoder/imagedecoder/index.md
> +      - : A string containing the [MIME type](https://en.wikipedia.org/wiki/Media_type) of the image file to be decoded.
Done in all cases.

2022-06-06 17:31 UTC, dalecurtis commented on files/en-us/web/api/imagedecoder/index.md
>  ## Properties
Resolved here and everywhere else.

2022-06-06 17:41 UTC, dalecurtis commented
Thanks for the review. I think I addressed everything. I'll make a pass over the ImageTrack and ImageTrackList in a follow-up change.

2022-06-07 05:17 UTC, teoli2003 requested changes
Sorry, I missed the WebIDL types in my first pass. (I try to avoid to do multiple passes, but this was an oversight)

A few small changes and we can merge this!

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/imagedecoder/index.md
> +      - : A {{domxref("USVString")}} containing the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the image file to be decoded.
Sorry, I missed this one. We are retiring `DOMString`, `USVString` and `CSSOMString` as these names are invisible for a web dev, in the console for example.

(By retiring, I mean the pages will be deleted by the end of the week).
```suggestion
      - : A string containing the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the image file to be decoded.
```

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +  - : Returns a {{domxref("DOMString")}} reflecting the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) configured during construction.
```suggestion
  - : Returns a string reflecting the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) configured during construction.
```

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/index.md
> +  - : Returns a {{jsxref("boolean")}} indicating whether encoded data is completely buffered.
```suggestion
  - : Returns a boolean value indicating whether encoded data is completely buffered.
```

It returns a boolean value `true` or `false` and not a `Boolean` wrapper object.

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +  - : A {{domxref("DOMString")}} containing the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) to check for decoding support.
```suggestion
  - : A string containing the [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) to check for decoding support.
```

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/istypesupported/index.md
> +A {{jsxref("promise")}} that resolves with a {{jsxref("boolean")}} indicating whether images with a format of `type` can be decoded by the API.
```suggestion
A {{jsxref("promise")}} that resolves with a boolean value indicating whether images with a format of `type` can be decoded by the API.
```

2022-06-07 05:17 UTC, teoli2003 commented on files/en-us/web/api/imagedecoder/type/index.md
> +A {{domxref("DOMString")}} containing the configured [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types).
```suggestion
A string containing the configured [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types).
```

2022-06-08 17:53 UTC, dalecurtis commented
Thanks, committed all your suggestions! Thanks for making them inline.

2022-06-10 07:07 UTC, teoli2003 approved these changes
👍

2022-06-10 07:09 UTC, merged

2022-06-10 07:09 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: