updated syntax
mdn/content pull request #16963
Opened 2022-06-04 05:31 UTC by gullapalli9482

#### Summary

Resolves issue #16662 
#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-04 15:44 UTC, wbamberg requested changes
Thank you @gullapalli9482 !

2022-06-04 15:44 UTC, wbamberg commented on files/en-us/web/api/convolvernode/normalize/index.md
> -  var audioData = ajaxRequest.response;
Line 41 in this file, which I can't select for comment, can be:
`let soundSource, concertHallBuffer;`

....although I would prefer to write:

```
let soundSource;
let concertHallBuffer;
```

2022-06-04 15:44 UTC, wbamberg commented on files/en-us/web/api/cssstyledeclaration/length/index.md
> +const myDiv = document.getElementById('div1'); const divStyle = myDiv.style; const len = divStyle.length; // 6
not strictly in scope but can we have separate lines here:

```suggestion
const myDiv = document.getElementById('div1');
const divStyle = myDiv.style;
const len = divStyle.length; // 6
```

2022-06-04 17:01 UTC, gullapalli9482 commented on files/en-us/web/api/convolvernode/normalize/index.md
> -  var audioData = ajaxRequest.response;
My bad, this is the disadvantage of editing files in the terminal, ubuntu terminal has a bad background color. I'll make sure to check the files multiple times before committing them.

2022-06-04 19:35 UTC, wbamberg commented on files/en-us/web/api/cssstylesheet/insertrule/index.md
> +      let prop = rule[j];
```suggestion
      const prop = rule[j];
```

Sorry I missed this one!

2022-06-05 01:15 UTC, gullapalli9482 commented
Are there any other files to be modified?

2022-06-05 03:39 UTC, wbamberg commented on files/en-us/web/api/convolvernode/normalize/index.md
> +  const audioData = ajaxRequest.response;
Line 41 in this file should also use `let`.

2022-06-05 03:47 UTC, wbamberg approved these changes
👍 looks great, @gullapalli9482 , thank you!

2022-06-05 03:49 UTC, wbamberg commented
By the way, you don't (IMO) have to merge main back into your branch unless you have conflicting files (and GitHub will tell you if you do have conflicting files).

2022-06-05 03:49 UTC, merged