line 174 need add "are".
mdn/content pull request #16968
Opened 2022-06-04 10:02 UTC by KimberlyYen

#### Summary

Second, setting out actionable steps leads to new questions you'll need to answer. Usually 
there  ***are***
turn out to be more questions than we originally thought. (For example, should I learn how to do all this myself, ask someone to do it for me, or use third-party services?)

#### Motivation

Adjust the grammar

#### Supporting details

No.
#### Related issues

No.
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-04 10:55 UTC, teoli2003 requested changes

2022-06-04 10:55 UTC, teoli2003 commented on files/en-us/learn/common_questions/thinking_before_coding/index.md
> +Second, setting out actionable steps leads to new questions you'll need to answer. Usually there are turn out to be more questions than we originally thought. (For example, should I learn how to do a
The sentence is not clear for me either, but your fix is not grammatically correct. What about:
```suggestion
Second, setting out actionable steps leads to new questions you'll need to answer. Usually, more questions than originally thought turn out. (For example, should I learn how to do all this myself, ask someone to do it for me, or use third-party services?)
```

2022-06-04 15:34 UTC, wbamberg commented
I like the original sentence better than either of these, but if it is hard to understand I think we could just delete the whole sentence ("more than you originally thought" is implicit in "new questions").

2022-06-06 21:46 UTC, estelle commented
The original is the clearest. closing.

2022-06-06 21:46 UTC, closed without merging