Updated syntax as per ES6
mdn/content pull request #17065
Opened 2022-06-07 14:52 UTC by PrajwalBorkar

#### Summary

Replaced var with const or let as appropriate.
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662 
#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-07 22:48 UTC, wbamberg requested changes
Thank you @PrajwalBorkar , nice work. Just a few comments.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/attributes/index.md
> +       const output = "";
```suggestion
       let output = "";
```

...output gets reassigned at line 60.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/closest/index.md
> +    const el = this;
The changes you've made in this file are in the "Polyfill" section. Please don't update polyfills in this project.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/getattributenames/index.md
> +    const attributes = this.attributes;
This is also a change to the polyfill.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/mouseenter_event/index.md
> +const leaveEventCount = 0;
```suggestion
let enterEventCount = 0;
let leaveEventCount = 0;
```

...these are reassigned at 104 and 110.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/mouseleave_event/index.md
> +const leaveEventCount = 0;
```suggestion
let enterEventCount = 0;
let leaveEventCount = 0;
```

...also reassigned.

2022-06-07 22:48 UTC, wbamberg commented on files/en-us/web/api/element/scrollwidth/index.md
>      divTwo = document.getElementById('anotherDiv');
```suggestion
    const buttonOne = document.getElementById('aButton');
    const buttonTwo = document.getElementById('anotherButton');
    const divOne = document.getElementById('aDiv');
    const divTwo = document.getElementById('anotherDiv');
```

(not strictly needed, but much better to have one declaration per line.)

2022-06-08 06:41 UTC, PrajwalBorkar commented on files/en-us/web/api/element/closest/index.md
> +    const el = this;
Ok from now onwards I will skip the Polyfill section. Should I revert this change?

2022-06-08 06:44 UTC, PrajwalBorkar commented on files/en-us/web/api/element/getattributenames/index.md
> +    const attributes = this.attributes;
Should I undo this changes also?

2022-06-21 23:04 UTC, wbamberg approved these changes
👍 nice work @PrajwalBorkar !

2022-06-21 23:04 UTC, merged