Specificity
mdn/content pull request #17089
Opened 2022-06-08 04:10 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-09 19:08 UTC, dipikabh requested changes
Hi @estelle, thank you for this work!
I've done a readthrough. Might need other look after your fixes.

2022-06-09 19:08 UTC, dipikabh commented on files/en-us/web/css/specificity/index.md
> +The last selector has four type components. While it has the highest integer value, no matter how many type components are included, even if there were 150, type components never have precedence over
```suggestion
The last selector has four _TYPE_ components. While it has the highest integer value, no matter how many type components are included, even if there were 150, type components never have precedence over _CLASS_ selectors. The column values are compared from left to right when column values are equal.
```

2022-06-09 19:08 UTC, dipikabh commented on files/en-us/web/css/specificity/index.md
> +When multiple declarations have equal specificity, the last declaration found in the CSS is applied to the element. Specificity only applies when the same element is targeted by multiple declarations
This should be converted to text that's specific to the example. Like, "In this example, both the declarations have equal specificity, so the last declaration found in the CSS is applied to the element."

It might be better to move this para elsewhere on the page where specificity is being defined: "Specificity only applies when the same element is targeted by multiple declarations in a cascade layer or origin. As per CSS rules, [directly targeted elements](#directly_targeted_elements_vs._inherited_styles) will always take precedence over rules which an element inherits from its ancestor."

2022-06-09 19:08 UTC, dipikabh commented on files/en-us/web/css/specificity/index.md
> +> **Note:** Specificity only matters for declarations of the same importance and same origin and cascade layer. If matching selectors are in different origins, the [cascade](/en-US/docs/Web/CSS/Casca
This looks like it could be moved closer to the intro paras

2022-06-09 22:49 UTC, estelle reviewed
Slight changes to review suggestions

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +If declarations from the same origin and cascade layer conflict, if one property value has the `!important` flag set, the important declaration is applied no matter the specificity. When conflicting
```suggestion
If declarations from the same origin and cascade layer conflict and one property value has the `!important` flag set, the important declaration is applied no matter the specificity. When conflicting declarations from the same origin and cascade layer with the `!important` flag are applied to the same element, the declaration with a greater specificity is applied. 
```

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +As a special case for increasing specificity duplicating weights from the _CLASS_ or _ID_ columns. Duplicating simple selectors will increase specificity when overriding very specific selectors over
```suggestion
As a special case for increasing specificity, you can duplicate weights from the _CLASS_ or _ID_ columns. Duplicating simple selectors will increase specificity when overriding very specific selectors over which you have no control. 
```

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +When unable to remove `!important` flags from an authors style sheet, the only solution to overriding the important styles is by using `!important`. Creating a [cascade layer](../@layer/) of importan
```suggestion
If you're unable to remove `!important` flags from an authors style sheet, the only solution to overriding the important styles is by using `!important`. Creating a [cascade layer](../@layer/) of important declaration overrides is an excellent solution. Two ways of doing this include:
```

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +The specificity of the selector of the important style within the layer can be low, as long as it matches the element you are trying to override. Normal layers should be declared outside the layer as
```suggestion
The specificity of the selector of the important style within the layer can be low, as long as it matches the element you are trying to override. Normal layers should be declared outside the layer because layered styles have lower precedence than unlayered styles.
```

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +### Basic example
```suggestion
In the following CSS, we have three selectors targeting {{HTMLElement('input') elements to set a color. For a given input, the specificity weight of the color declaration having precedence is the matching selector with the greatest weight:

2022-06-09 22:49 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +The last selector has four type components. While it has the highest integer value, no matter how many type components are included, even if there were 150, type components never have precedence over
```suggestion
The last selector has four _TYPE_ components. While it has the highest integer value, no matter how many elements and pseudo-elements are included, even if there were 150, TYPE components never have precedence over _CLASS_ components. The column values are compared starting from left to right when column values are equal.
```

2022-06-09 22:57 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +Specificity is considered **after** determining [cascade origin and importance](/en-US/docs/Web/CSS/Cascade). In other words, for competing property declarations, specifity is only relevant and compa
fixed

2022-06-09 23:57 UTC, estelle commented
Thanks for the excellent review. I think it's ready.

2022-06-12 05:46 UTC, teoli2003 requested changes
This is very good. It reads very easily. A few points:
- I fixed the test failure (missing `}}` at the end of a macro
- I made proposals for fixing some typographic details
- I have one question, the only place I found the prose not clear. The only place we can actually improve the content itself 😃 

I think this is very close to being merged!

Thanks, @estelle, the article will rock!

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +> Note: Browsers consider specificity **after** determining [cascade origin and importance](/en-US/docs/Web/CSS/Cascade). In other words, for competing property declarations, specificity is relevant
We need to put _Note:_ in bold. This also triggers Yari to add the right class to the HTML generated from Markdown.

I also fixed a minor grammar error.

```suggestion
> **Note:** Browsers consider specificity **after** determining [cascade origin and importance](/en-US/docs/Web/CSS/Cascade). In other words, for competing property declarations, specificity is relevant and compared only between selectors from the one [cascade origin and layer](/en-US/docs/Web/CSS/@layer) that has precedence for the property. Order of appearance becomes relevant when the selector specificities of the competing declarations in the cascade layer with precedence are equal.
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +Combinators, such as {{CSSxRef("Adjacent_sibling_combinator", "+")}}, {{CSSxRef("Child_combinator", "&gt;")}}, {{CSSxRef("General_sibling_combinator", "~")}}, [" "](/en-US/docs/Web/CSS/Descendant_com
I'm not sure I understand here: _may make a selector more specific but don't add any value to the the specificity weight_. Okay, but how does they make a selector more specific?

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +The negation pseudo-class, {{CSSxRef(":not", ":not()")}},  itself has no weight. Neither does the {{CSSxRef(":is", ":is()")}} pseudo-class. The parameters in these selectors, however, do. The values
Nit:
```suggestion
The negation pseudo-class, {{CSSxRef(":not", ":not()")}}, itself has no weight. Neither does the {{CSSxRef(":is", ":is()")}} pseudo-class. The parameters in these selectors, however, do. The values of both come from the parameter in the list of parameters that has the highest specificity. The [`:not()` and `:is()` exceptions](#the-is-and-not-exceptions) are discussed below.
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> + [id="myElement] p {
I'm not 100% sure, but I think it should be:
```suggestion
 [id="myElement"] p {
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +    [id="myElement] p {
```suggestion
    [id="myElement"] p {
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +The `h1` elements will be purple because when declarations have the same specificity, the last declared selector has precedence.
```suggestion
The `<h1>` elements will be purple because when declarations have the same specificity, the last declared selector has precedence.
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +- "Specificity" in "Cascade and inheritance"](/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2
```suggestion
- "Specificity" in "Cascade and inheritance"](/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2)
```

2022-06-12 05:46 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> +- Specificity Calculator: An interactive website to test and understand your own CSS rules - <https://specificity.keegan.st/>
```suggestion
- [Specificity Calculator](https://specificity.keegan.st/): An interactive website to test and understand your own CSS rules
```

2022-06-12 21:52 UTC, teoli2003 commented on files/en-us/web/css/specificity/index.md
> -spec-urls: https://drafts.csswg.org/selectors/#specificity-rules
If you remove this line you must remove the _Specifications_ section at the botton.

While removing it?

2022-06-13 18:24 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> +Combinators, such as {{CSSxRef("Adjacent_sibling_combinator", "+")}}, {{CSSxRef("Child_combinator", "&gt;")}}, {{CSSxRef("General_sibling_combinator", "~")}}, [" "](/en-US/docs/Web/CSS/Descendant_com
edited to read "more specific in what is selected"

2022-06-13 18:25 UTC, estelle commented on files/en-us/web/css/specificity/index.md
> -spec-urls: https://drafts.csswg.org/selectors/#specificity-rules
put it back in

2022-06-13 18:38 UTC, teoli2003 approved these changes
\o/

2022-06-13 21:18 UTC, estelle commented
@dipikabh Thanks for the review. I am not seeing any more comments, but it's blocking me from merging.

2022-06-14 07:57 UTC, dipikabh approved these changes
Thank you, @estelle!

2022-06-14 07:57 UTC, merged