Updated syntax as per ES6
mdn/content pull request #17107
Opened 2022-06-08 15:20 UTC by PrajwalBorkar

#### Summary

Replaced var with const or let as appropriate.
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662 
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-08 21:32 UTC, sideshowbarker commented
Can you please describe what testing you’ve done with these changes in order to ensure they haven’t broken anything?

The changes made in https://github.com/mdn/content/pull/16969 broke multiple pages. And the changes made in https://github.com/mdn/content/pull/17007 also introduced at least one error (see https://github.com/mdn/content/pull/17050).

2022-06-08 22:46 UTC, wbamberg requested changes
Thanks for your PR, @PrajwalBorkar ! Let me know if you have any questions about these.

2022-06-08 22:46 UTC, wbamberg commented on files/en-us/web/api/htmlcanvaselement/mozfetchasstream/index.md
>  ctx = canvas.getContext('2d');
```suggestion
const ctx = canvas.getContext('2d');
```

2022-06-08 22:46 UTC, wbamberg commented on files/en-us/web/api/htmlcanvaselement/toblob/index.md
>        url = URL.createObjectURL(blob);
```suggestion
  const newImg = document.createElement('img');
  const url = URL.createObjectURL(blob);
```

2022-06-08 22:46 UTC, wbamberg commented on files/en-us/web/api/htmlcanvaselement/toblob/index.md
>  ctx = canvas.getContext('2d');
```suggestion
const ctx = canvas.getContext('2d');
```

2022-06-08 22:46 UTC, wbamberg commented on files/en-us/web/api/htmldialogelement/close/index.md
> +      const dialog = document.getElementById('favDialog');
This example should also be updated at https://github.com/mdn/dom-examples/blob/master/htmldialogelement-basic/index.html.

2022-06-08 22:52 UTC, wbamberg commented
> Can you please describe what testing you’ve done with these changes in order to ensure they haven’t broken anything?
> 
> The changes made in #16969 broke multiple pages. And the changes made in #17007 also introduced at least one error (see #17050).

I think in many cases here the only realistic testing is review, and that's true with any code changes to non-live examples, unfortunately. I'm trying to take the time to review these PRs as well as I can but mistakes can of course appear.

Realistically I think the only alternative is to rewrite them as live samples, which is not a practical amount of work (and in many cases, like Gamepad, is not practical at all).

If you think this project is misguided though I'm happy to discuss it. My main concern tbh is that so many of our example code is bad in so many different ways, that updating just this aspect seems terribly inadequate. But again, rewriting them all is a massive amount of work, and I feel like fixing this `var` problem across the board is worth doing.

2022-06-09 02:37 UTC, sideshowbarker commented
> I think in many cases here the only realistic testing is review…
>
> If you think this project is misguided though I'm happy to discuss it. My main concern tbh is that so much of our example code is bad in so many different ways, that updating just this aspect seems terribly inadequate. But again, rewriting them all is a massive amount of work, and I feel like fixing this `var` problem across the board is worth doing.

I don’t think it’s misguided. I think it’s worth doing. But I don’t agree at all that the only realistic testing is review.

I was not questioning the project — my intention was instead just exactly what I asked, which was to hear from the PR author what process was used before this PR was submitted to verify that the changes in the PR don’t introduce any errors.

It doesn’t seem good to give contributors the impression that it’s not important for them to check their changes very carefully themselves before submitting PRs — because whoever reviews their changes will do that work for them.

It seems important for all contributors to take responsibility themselves for doing their best to verify that changes they’re making aren’t introducing any errors.

2022-06-09 03:28 UTC, wbamberg commented
> > I think in many cases here the only realistic testing is review…
> > If you think this project is misguided though I'm happy to discuss it. My main concern tbh is that so much of our example code is bad in so many different ways, that updating just this aspect seems terribly inadequate. But again, rewriting them all is a massive amount of work, and I feel like fixing this `var` problem across the board is worth doing.
> 
> I don’t think it’s misguided. I think it’s worth doing. But I don’t agree at all that the only realistic testing is review.
> 
> I was not questioning the project — my intention was instead just exactly what I asked, which was to hear from the PR author what process was used before this PR was submitted to verify that the changes in the PR don’t introduce any errors.
> 
> It doesn’t seem good to give contributors the impression that it’s not important for them to check their changes very carefully themselves before submitting PRs — because whoever reviews their changes will do that work for them.
> 
> It seems important for all contributors to take responsibility themselves for doing their best to verify that changes they’re making aren’t introducing any errors.

Fair enough. There's nothing here I don't agree with. When I said "the only realistic testing is review" I didn't just mean review by me, I meant review by the PR author too. I didn't mean to imply that authors should not do their best to check PRs before filing.

2022-06-09 06:52 UTC, PrajwalBorkar commented
> Can you please describe what testing you’ve done with these changes in order to ensure they haven’t broken anything?
> 
> The changes made in #16969 broke multiple pages. And the changes made in #17007 also introduced at least one error (see #17050).

I'm using my knowledge of js and online docs to make the changes. Also reviewing past PRs related to this to not make any mistakes again. Also thanks to @wbamberg for reviewing the code and giving great feedback about the changes I made. I have no idea why the code broke as I'm not an expert. I'm trying to make the changes carefully up to my knowledge.

2022-06-09 07:08 UTC, PrajwalBorkar commented
> > I think in many cases here the only realistic testing is review…
> > If you think this project is misguided though I'm happy to discuss it. My main concern tbh is that so much of our example code is bad in so many different ways, that updating just this aspect seems terribly inadequate. But again, rewriting them all is a massive amount of work, and I feel like fixing this `var` problem across the board is worth doing.
> 
> I don’t think it’s misguided. I think it’s worth doing. But I don’t agree at all that the only realistic testing is review.
> 
> I was not questioning the project — my intention was instead just exactly what I asked, which was to hear from the PR author what process was used before this PR was submitted to verify that the changes in the PR don’t introduce any errors.
> 
> It doesn’t seem good to give contributors the impression that it’s not important for them to check their changes very carefully themselves before submitting PRs — because whoever reviews their changes will do that work for them.
> 
> It seems important for all contributors to take responsibility themselves for doing their best to verify that changes they’re making aren’t introducing any errors.

To test the code I tried the compliers online but are not giving any error where it should give. @sideshowbarker If you know any way to verify the code or resource to test the code then share with us. As a contributor, I'm taking the responsibility to carefully submit PR but in some tricky cases, the feedback will be needed. Imo without code review it will be difficult to submit the PRs as we can make mistakes as a beginner. If anyone is expert here I think they can work on these issues or at least review the code as it is big work to do.

2022-06-09 07:16 UTC, PrajwalBorkar commented on files/en-us/web/api/gamepad/axes/index.md
> +    const gp = navigator.webkitGetGamepads()[0];
I made the changes [here](https://github.com/mdn/content/pull/17107/commits/d5d79b1a1a0fbd6519fe8f4fe4f33a7f93e7b6a0) please review

2022-06-09 07:21 UTC, PrajwalBorkar commented on files/en-us/web/api/gamepad/buttons/index.md
> +    const gp = navigator.webkitGetGamepads()[0];
Made the changes [here](https://github.com/mdn/content/pull/17107/commits/bce297aae05e99916e736e90c3e3d0e6e5c9e866)

2022-06-09 07:23 UTC, PrajwalBorkar commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +const b = 0;
So what changes should be made?

2022-06-09 07:27 UTC, PrajwalBorkar commented on files/en-us/web/api/htmldialogelement/close/index.md
> +      const dialog = document.getElementById('favDialog');
I have not forked that repo will do now. Should I just make PR there or create a new issue because I don't

2022-06-09 22:42 UTC, wbamberg commented on files/en-us/web/api/htmldialogelement/close/index.md
> +      const dialog = document.getElementById('favDialog');
Please just make a new PR there, you don't need an issue. But @ me in the PR so I can review :).

2022-06-09 23:11 UTC, wbamberg requested changes
Thank you for the updates @PrajwalBorkar ! I realised that in this case we also need to initialize those `a` and `b` variables.

2022-06-10 07:24 UTC, wbamberg approved these changes
👍 thank you @PrajwalBorkar , looks great!

2022-06-10 07:24 UTC, merged

2022-06-10 07:27 UTC, PrajwalBorkar commented on files/en-us/web/api/htmldialogelement/close/index.md
> +      const dialog = document.getElementById('favDialog');
Yeah , created [PR](https://github.com/mdn/dom-examples/pull/114)