Fix multiple issues with FinalizationRegistry content
mdn/content pull request #17126
Opened 2022-06-09 04:43 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #13695

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-09 06:45 UTC, teoli2003 requested changes
Thanks a lot.

I think there are extra things that should be updated. What do you think?

2022-06-09 06:45 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
> +`true` if at least one cell was unregistered; `false` if no cell was unregistered.
```suggestion
A boolean value that is `true` if at least one cell was unregistered, `false` if no cell was unregistered.
```

2022-06-09 06:45 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
> +`true` if at least one cell was unregistered; `false` if no cell was unregistered.
In addition to the boolean value, I think there are cases where `undefined` can be returned, am I wrong?

2022-06-09 06:45 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
I think we have cases where the `{{jsxref("TypeError")}}` exception is raised. We likely want an `### Exceptions` section.

2022-06-09 06:45 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/register/index.md
>  - `target`
I think we have cases where the `{{jsxref("TypeError")}}` exception is raised. We likely want an `### Exceptions` section.

2022-06-09 06:50 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
> +`true` if at least one cell was unregistered; `false` if no cell was unregistered.
[Can't find it in spec](https://tc39.es/ecma262/#sec-finalization-registry.prototype.unregister). It either returns a boolean, or throws a `TypeError`.

2022-06-09 06:51 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
Makes sense—when I work on these docs there are a lot of sections missing mentions of exceptions. Is there a convention for how this should be structured? Or just an h3 section.

2022-06-09 07:02 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
Yes, we should add them as we do for API, with a definition list in that section: https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_method_subpage_template#exceptions

Something like: https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/continue#exceptions

And yes, there are a lot of exceptions not listed (both under JS and API), I would like to make a full check once, but I don't have the time. Getting the exception list, with causes, complete under JavaScript/ and API/ is hard, though as they are buried inside the prose, or the algorithm, of the specifications.

2022-06-09 07:03 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/finalizationregistry/unregister/index.md
> +A `TypeError` is thrown if `unregisterToken` is not an object.
```suggestion
- {{jsxref("TypeError")}}
  - : Thrown when `unregisterToken` is not an object.
```

2022-06-10 05:35 UTC, teoli2003 approved these changes
Thank you very much. I've listed the three conditions for an exception as a list (we usually do this).

Let's merge this. If we discover more problems we always can fix them in follow-ups!

2022-06-10 05:35 UTC, merged