Enhancements to CSP page
mdn/content pull request #1713
Opened 2021-01-25 12:40 UTC by shaialon

- Violation reporting.
- CSP scanning.

2021-01-27 13:38 UTC, Elchi3 requested changes
Welcome to mdn/content and thanks for your contribution! I've made some suggestions but LGTM otherwise.
Bonus points if you follow up and also update https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only with this information.

Also, I think CSP report-sample should be documented as it looks missing to me.

2021-01-27 13:38 UTC, Elchi3 commented on files/en-us/web/http/csp/index.html
> +  <dd>The directive whose enforcement caused the violation. Some browsers may provide different values, such as Chrome providing <code>style-src-elem</code>/<code>style-src-attr</code>, even when the
```suggestion
  <dd>The directive whose enforcement caused the violation. Some browsers may provide different values, such as Chrome providing <code>style-src-elem</code>/<code>style-src-attr</code>, even when the actual enforced directive was <code>style-src</code>.</dd>
```

2021-01-27 13:38 UTC, Elchi3 commented on files/en-us/web/http/csp/index.html
> +  <li><a href="https://cspscanner.com/">CSP Scanner</a> - Improve your
On this one I like @chrisdavidmills to comment. I was looking for our editorial guidelines about linking to commercial sites and I think they are now here: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Editorial

Chris, what do you think?

2021-01-27 14:33 UTC, shaialon commented on files/en-us/web/http/csp/index.html
> +  <li><a href="https://cspscanner.com/">CSP Scanner</a> - Improve your
Thanks @Elchi3 . Just for emphasis:
**CSP scanner** is a free utility for educational purposes (as site/ extension) and can be used by anyone - much like the Google CSP evaluator above, with some extra functionality.

CSP scanner is sponsored by [RapidSec](https://rapidsec.com/), which does have commercial intent ,  yet the scanner remains open to anyone - including RapidSec competitors' users.

I believe that this is standard practice in such cases.

2021-01-27 17:01 UTC, Ryuno-Ki commented on files/en-us/web/http/csp/index.html
> +  <li><a href="https://cspscanner.com/">CSP Scanner</a> - Improve your
Could you add a `class="external"` to external links? That would help us add some design elements in the future :-)

2021-01-27 19:05 UTC, shaialon commented on files/en-us/web/http/csp/index.html
> +  <li><a href="https://cspscanner.com/">CSP Scanner</a> - Improve your
@Ryuno-Ki Sure thing, added 👍

2021-01-27 19:33 UTC, Ryuno-Ki commented on files/en-us/web/http/csp/index.html
> +  <li><a href="https://cspscanner.com/">CSP Scanner</a> - Improve your
Thanks!

2021-01-27 23:09 UTC, shaialon commented
@Elchi3 I think we are all good. Submitted for re-review.

2021-01-28 10:01 UTC, Elchi3 commented
Thanks for your quick follow-up, @shaialon 👍 
I appreciate you elaborating on the link addition and explaining what your service does 🚀 

I still like to hear from Chris about our editorial guideline, so that I know for my future reviews.

2021-01-29 11:47 UTC, chrisdavidmills commented
> I still like to hear from Chris about our editorial guideline, so that I know for my future reviews.

I think this one is OK — it is a free tool, and actually useful and relevant.

2021-01-29 11:47 UTC, chrisdavidmills approved these changes

2021-01-29 11:57 UTC, Elchi3 approved these changes
okidoki! Thanks Chris! 👍

2021-01-29 11:58 UTC, merged