Clarify Clipboard availability
mdn/content pull request #17207
Opened 2022-06-12 16:10 UTC by alattalatta

#### Summary
Clarifies that the quarks listed in the page is for Firefox only. Also removes a note describing "clipboard" as a general term.

#### Motivation
> In addition, {{domxref("Clipboard.read", "read()")}} and {{domxref("Clipboard.write", "write()")}} are disabled by default ...

Yes, but only in Firefox. I have no idea about WebExtensions, but based on the compat table and the Mozilla blog post link, I think it's just for Firefox as well?

Now I have a question whether it's worth it to dedicate three paragraphs to Firefox only but in this PR I decided not to go too far.

Also for the deleted note, I believe it doesn't belong here.

#### Supporting details
The compat table.

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-14 04:12 UTC, alattalatta commented on files/en-us/web/api/clipboard/index.md
> -
I highly doubt this note belongs here, in the `Clipboard` interface document. The best as a separate glossary entry "clipboard", better in the [Clipboard API overview page](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), not here. Description of a _general term_ doesn't really contribute anything to an _API interface_ documentation.

2022-06-27 12:10 UTC, Rumyra requested changes

2022-06-27 12:15 UTC, Rumyra commented
Hi @alattalatta , thanks so much for you patience - looking at this again I think the approach should be:

* Make sure the note about clipboard is on the overview page
* In the 'Clipboard availability' section actually remove the last three paragraphs and say 'See the browser compatibility section below for more information' and also 'The `clipboard` interface is also available in Web Extensions, which you can find out more about here' with a link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard

2022-07-05 12:49 UTC, Rumyra approved these changes

2022-07-05 12:50 UTC, Rumyra commented
This looks great @alattalatta - thank you so much!

2022-07-05 12:50 UTC, merged