Updated syntax
mdn/content pull request #17237
Opened 2022-06-13 17:18 UTC by PrajwalBorkar

#### Summary

Updated syntax as per ES6.
#### Motivation

#### Supporting details

#### Related issues

Resolving issue #16662 
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-13 17:19 UTC, PrajwalBorkar commented
Please review for changes.

2022-06-19 09:53 UTC, teoli2003 requested changes

2022-06-19 09:53 UTC, teoli2003 commented on files/en-us/web/api/idbobjectstore/deleteindex/index.md
> +  let db = this.result;
No need for `let` as it already defined at line 63.

2022-06-19 09:54 UTC, PrajwalBorkar commented
There are some files that have var but missing in the sheet and should also be updated?

2022-06-19 09:58 UTC, PrajwalBorkar commented
There are some files which are not in sheet but contains var so I have updated that also. Please check once. Should I update the missing files in the sheet in future also?

2022-06-19 10:00 UTC, teoli2003 commented
Yes, if you find extra files, add them to the spreadsheet.

2022-06-19 10:00 UTC, teoli2003 approved these changes

2022-06-19 10:00 UTC, merged

2022-06-19 10:01 UTC, PrajwalBorkar commented
> Yes, if you find extra files, add them to the spreadsheet.

Ok will add this one and upcoming files.