Fix syntax error thrown by a live sample
mdn/content pull request #17246
Opened 2022-06-14 02:15 UTC by OnkarRuikar

2022-06-14 04:43 UTC, teoli2003 commented on files/en-us/web/svg/attribute/transform/index.md
I would keep it valid JS. 

What about:
> The `translate(x y)` transform function moves the object by `x` and `y`. If `y` is not provided, it is assumed to be `0`.

Then for the example:
```js
xnew = xold + x;
ynew = yold + y;
```

(Sorry couldn't make a proposal easy to accept.

2022-06-14 04:44 UTC, teoli2003 requested changes
Let's keep put the example as valid JS, and not use the square brackets and `<>` that are not well known.

2022-06-14 06:26 UTC, OnkarRuikar commented on files/en-us/web/svg/attribute/transform/index.md
But it is not a part of the live sample. Making it JS gets it included in `{{EmbedLiveSample('Translate', '100%', 200)}}` then it throws a new error: 
> Uncaught ReferenceError: xold is not defined

I've seen such code blocks get included in live samples undesirably at many places in mdn/content. And they produce side effects which are, most of the times, hard to recognize.
Is there a tag available on code blocks to avoid them getting included in live samples? like:
````
```js no-include
xnew = xold + x;
```
````

I don't know how the live samples get hosted on https://yari-demos.prod.mdn.mozit.cloud. May be during yari production build?
If there is no such mechanism available, then can we implement a tag which will exclude such code blocks from live samples?

2022-06-14 06:29 UTC, teoli2003 commented on files/en-us/web/svg/attribute/transform/index.md
I'm cc/ing @wbamberg who knows better how this work.

2022-06-20 17:52 UTC, wbamberg commented on files/en-us/web/svg/attribute/transform/index.md
Also I don't think we should add new bits of syntax to code blocks (like `no-include`) without really careful consideration. These things add complexity to the platform and to the authoring interface, and MDN is complicated enough already.

I do think we will need something for Prettier, to stop it complaining about code blocks that are intentionally formatted in a different way (to illustrate an error for example) and possibly also for ESLint, to stop it complaining about code blocks that illustrate errors. But we should think carefully before adding things like this.

2022-06-21 02:58 UTC, OnkarRuikar commented
Applied both the changes suggested by @wbamberg.

2022-06-21 22:57 UTC, wbamberg approved these changes
Thank you @OnkarRuikar !

I hadn't seen @teoli2003 's https://github.com/mdn/content/issues/16255#issuecomment-1134894671 when I commented - I agree it would be fine to do that too. I think the reason I like `plain` is that this is really pseudocode: it's not JS that you might want to use anywhere, it's just showing the algorithm. But treating it as JS would be OK too.

But I'm happy with this :).

2022-06-22 05:52 UTC, teoli2003 approved these changes

2022-06-22 05:53 UTC, merged