Minor: updated language to reflect change to .md
mdn/content pull request #17289
Opened 2022-06-14 22:13 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-15 04:49 UTC, teoli2003 requested changes
Even if we technically support HTML files,  the whole site is now in Markdown. I don't think we need to complexify the prose here to explain something that will lead to PRs being rejected.

And: good catch! we completely forgot about this file! Much needed!

2022-06-15 04:49 UTC, teoli2003 commented on README.md
> +  `files/en-us/web/`, make it a Markdown file.
Even if HTML files are still supported, we have converted the whole website to MD.
```suggestion
- Documents must be authored in Markdown.
```

2022-06-15 04:49 UTC, teoli2003 commented on README.md
> +(or `index.html`) file.
```suggestion
1. Create one or more new document folders, each with their own `index.md` file.
```

2022-06-15 04:55 UTC, teoli2003 commented
@schalkneethling There is a failing test here: the action doesn't find `markdownlint-cli`. I would ignore it, but I think this need to be fixed? Before opening an issue, is this something new? Or only applied to a few files?

2022-06-15 10:55 UTC, schalkneethling commented
> @schalkneethling There is a failing test here: the action doesn't find `markdownlint-cli`. I would ignore it, but I think this need to be fixed? Before opening an issue, is this something new? Or only applied to a few files?

@teoli2003 It does not find it, but then goes ahead and installs it, there actual error is on the next line:

```
npm WARN exec The following package was not found and will be installed: markdownlint-cli
README.md:370:47 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1] # this here
```

2022-06-16 04:44 UTC, teoli2003 approved these changes
Thank you, @estelle

2022-06-16 04:44 UTC, merged