Point es6-shim getGlobal to the specific line
mdn/content pull request #17337
Opened 2022-06-16 07:24 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #10470. I hope this can reduce the confusion.

Also reverted back from `const` to `var` because this is verbatim-copied from the original code. Let me know if we still want to use `const`.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-16 07:29 UTC, zloirock commented
It will fail in some cases. See https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/global.js

2022-06-16 07:34 UTC, Josh-Cena commented
Should we point to core-js then? We seem to use core-js links in more places.

2022-06-16 08:12 UTC, zloirock commented
As you wish. I just pointed out that `es6-shim` is not the best option here.

2022-06-16 08:13 UTC, Josh-Cena commented
Yes—I'm not sure about the editors' opinions on this, so just asking :)

2022-06-28 02:53 UTC, Josh-Cena commented
@wbamberg What do you think here? Should we change the link and the code example to `core-js`'s, or do we just apply the current change?

2022-06-30 03:15 UTC, wbamberg commented
@Josh-Cena , I'd be happy to use core-js here instead, if you want to make that change :).

2022-06-30 03:23 UTC, Josh-Cena commented
@zloirock One thing I'm unsure of: why is it necessary to check for `it` twice in `it && it.Math == Math && it`? I think I'm overlooking something.

2022-06-30 03:26 UTC, zloirock commented
@Josh-Cena the first `it` is `null` check - `typeof null` is `object`. The second usage of `it` is returned result if the previous expression is `true`.

2022-06-30 03:29 UTC, Josh-Cena commented
If it's `null`—the `check` would short-circuit and return a falsy value `null` already, and if it's not `null`—neither should the second round of check be falsy, right?

2022-07-02 13:17 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +if (typeof globalObject.setTimeout !== 'function') {
You can check `typeof setTimeout` without `globalObject`, so I don't think that it's a good example. However, I'm not sure that it's in the scope of this issue.

2022-07-02 16:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +if (typeof globalObject.setTimeout !== 'function') {
Let's just remove it—we are showing `globalThis` anyway.

2022-07-02 16:48 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +if (typeof globalObject.setTimeout !== 'function') {
For me, it's for operations with global variables that are more complex than a simple check. For example,
```js
if (!globalObject.Promise) {
  Object.defineProperty(globalObject, 'Promise', {
    value: function Promise () {
      // your Promise implementation
    },
    enumerable: false,
    configurable: true,
    writable: true
  });
}

2022-07-02 16:54 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +if (typeof globalObject.setTimeout !== 'function') {
Thanks, that's very useful inspiration—decided to use `Intl` instead of `Promise` so it looks more realistic.

2022-08-11 13:54 UTC, Josh-Cena commented
👋 Anyone to review this?

2022-08-24 22:57 UTC, Josh-Cena commented
Trying to summon @wbamberg again since this one is quite small

2022-08-25 00:02 UTC, wbamberg requested changes
Sorry to be slow @Josh-Cena .

2022-08-25 00:02 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +Prior to `globalThis`, the only reliable cross-platform way to get the global object for an environment was `Function('return this')()`. However, this causes [CSP](/en-US/docs/Web/HTTP/CSP) violation
I think it would be helpful to have a few words on the overall use case here (which I guess is to provide an implementation of `Intl` is one isn't available).

2022-08-25 00:05 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  check(typeof globalThis === 'object' && globalThis) ||
And this line just checks that it's supported.

2022-08-25 00:12 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  check(typeof globalThis === 'object' && globalThis) ||
This is describing before `globalThis` even became a proposal (or at least, before it was given that name), so yeah, we need a more ancient example.

2022-08-25 09:54 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
Now, without `globalThis`, it will not work in cases of ES-only environments (no one of the variables above) in modules context (IIFE `this` is `undefined`), where for security reasons disabled `eval` / `Function`. It's not a big problem to create such environment, for example, with NodeJS `vm`.

2022-08-25 15:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
That's right—the purpose of this example is to illustrate what happens without `globalThis`. I did dig into the history of `internals/global.js` and it was something like this a long time ago: https://github.com/zloirock/core-js/blob/b4e8c0b09bbe23db8d8784df03ef0b8f3ff04170/packages/core-js/internals/global.js

2022-08-25 18:28 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +Prior to `globalThis`, the only reliable cross-platform way to get the global object for an environment was `Function('return this')()`. However, this causes [CSP](/en-US/docs/Web/HTTP/CSP) violation
```suggestion
Prior to `globalThis`, the only reliable cross-platform way to get the global object for an environment was `Function('return this')()`. However, this causes [CSP](/en-US/docs/Web/HTTP/CSP) violations in some settings, so authors would use a piecewise definition like this (slightly adapted from the [original core-js source](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/global.js)):
```

(sorry to be pedantic) let's put a bit more distance between this example and the original, since it is substantively different with the omission of `globalThis`.

2022-08-25 18:30 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +Prior to `globalThis`, the only reliable cross-platform way to get the global object for an environment was `Function('return this')()`. However, this causes [CSP](/en-US/docs/Web/HTTP/CSP) violation
Looks great

2022-08-25 18:32 UTC, wbamberg approved these changes
👍 thanks for your patience @Josh-Cena !

2022-08-25 18:33 UTC, merged

2022-08-25 19:06 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
And after that, someone wrote me an issue about such an environment.

Someone could try to use the code from this example as a universal way of getting the global object and theoretically, it could fail in this specific and rare case. So I think changing "prior to `globalThis` ..." to something else could be better.

2022-08-25 19:17 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
The only thing I've modified from the core-JS source is removal of the `globalThis` mention. In a runtime without `globalThis`, is there anything better than this?

2022-08-25 19:29 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
I mean that someone could try this code everywhere as something universal - in environments without `globalThis` and in environments with.

2022-08-25 19:35 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/globalthis/index.md
> +  Function('return this')();
Oh well, it was kind of the same code before—let's hope no one uses it as a polyfill (they shouldn't!) If you want to add a warning box making it explicit, feel free to.