Fix sectioning flaw
mdn/content pull request #17343
Opened 2022-06-16 11:19 UTC by teoli2003

h3 level cannot be used inside a note:

1. They don't show up in the generated document; they are not achieving the intended goals.
2. They generate a sectioning flaw.

This PR transform them into bold text, not ideal but better.

2022-06-16 11:42 UTC, dipikabh requested changes
Hi @teoli2003, I don't know how but I see that heading on MDN outside the note.
![Screenshot 2022-06-16 at 1 34 15 PM](https://user-images.githubusercontent.com/23019147/174062255-d1f77c47-ae31-461f-88c3-65fd962401f7.png)

In any case, I have added a few suggestions. Let me know what you think.

2022-06-16 11:42 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +> **Top macros**
```suggestion
> - **macros**
```
- added the indenting hyphen to make it the same as other heads like 'title' and 'tags'
- I guess 'top' is not needed since it is understood because we're talking about the front matter

2022-06-16 11:42 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +> **Page front matter**
```suggestion

```

For some reason, on the MDN website, I see this as H3 heading outside the note.
I suggest we move it outside the note as an H2. That way, the TOC in the right will read:

> Page Front matter
> Constructor
> Properties
> Methods.
...and so on

2022-06-16 11:42 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
```suggestion
## Page front matter
```

2022-06-16 12:16 UTC, teoli2003 commented
> Hi @teoli2003, I don't know how but I see that heading on MDN outside the note. ![Screenshot 2022-06-16 at 1 34 15 PM](https://user-images.githubusercontent.com/23019147/174062255-d1f77c47-ae31-461f-88c3-65fd962401f7.png)
> 
> In any case, I have added a few suggestions. Let me know what you think.
Yeah, react moves such headers at random places…

2022-06-16 12:18 UTC, teoli2003 commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +> **Page front matter**
I'm ok with this, but the initial intention was to have the YAML header (page front matter) and the Top macros separated.

So I think we should aim for:
> YAML Headers
> Top Macros
> Constructor
> Properties
> Methods.
...and so on

2022-06-16 12:19 UTC, teoli2003 commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +> **Page front matter**
(Page front matter is the tool Yari uses, but they are a YAML headers and we could change tool without touching the content)

2022-06-16 12:22 UTC, teoli2003 commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
I incorporated this change (with the title YAML header) in the next commit.

2022-06-17 12:33 UTC, dipikabh requested changes
I get it now, thanks! It definitely makes more sense to separate the two - front matter and macros (H2).

However, how about we stick with the easier-to-understand "Page front matter" heading (also because that's how we've been referring to it all this while). We could add a sentence saying that they are YAML headers.

So along the lines of what you proposed, the TOC will be:

> Page front matter
> Top macros
> Constructor
> Properties
> Methods.
> ...and so on

2022-06-17 12:33 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +> The YAML at the top of the page is used to define "page metadata". The values should be updated appropriately for the particular interface.
```suggestion

```
Suggesting to move this out of the note

2022-06-17 12:33 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
>  > There are five macro calls at the top of the template by default. You should update or delete them according to the advice below:
```suggestion

```

2022-06-17 12:33 UTC, dipikabh commented on files/en-us/mdn/structures/page_types/api_reference_page_template/index.md
> +
```suggestion
## Top macros

By default, there are five macro calls at the top of a template. You should update or delete them according to the advice below.
```

2022-06-17 13:44 UTC, dipikabh approved these changes
Thank you @teoli2003 for your work on sorting out this page! 🎉

2022-06-17 13:45 UTC, merged