Significant language and style improvement
mdn/content pull request #17389
Opened 2022-06-17 21:01 UTC by peterhauke

Rewrite paragraph beginning with "Asynchronous programming is a technique ..." to clarify the meaning
Corrected the end of the paragraph beginning with "Here, makeGreeting() is a synchronous function ..." to clarify what "function returns" means

#### Summary

#### Motivation

To correct and simplify the language and clarify two confusing paragraphs.
#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-21 15:48 UTC, dipikabh requested changes
Hello @peterhauke, thanks for this PR!

A lot of changes are a matter of style and not grammatically incorrect. We advise to make changes only where there is an actual error that changes the meaning of the text. That said, some of the punctuation edits are needed as well as rephrasing in some sentences to improve clarity.

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +This program generates a number of large prime numbers, using a very inefficient algorithm, when the user clicks the "Generate primes" button. The user can set the number of primes to generate, which
```suggestion
The program below uses a very inefficient algorithm to generate multiple large prime numbers when a user clicks the "Generate primes" button. The user can control the number of primes to generate, which of course, affects how long the operation will take.
```
- Replaced one of the two 'number' with 'multiple' to avoid confusion
- I don't see a problem with using the word 'control'. It is not incorrect.

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +Click "Generate primes". Depending on how fast your computer is, it will probably take a few seconds before the program displays the "Finished!" message.
```suggestion
Try clicking "Generate primes". Depending on how fast your computer is, it will probably take a few seconds before the program displays the "Finished!" message.
```
The original is not incorrect, just a matter of style

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +The next example is just like the last one, except we added a text box for you to type in. This time, click "Generate primes" and then try typing in the text box.
```suggestion
The next example is just like the last one, except we added a text box for you to type in. This time, click "Generate primes", and try typing in the text box immediately after.
```

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +You'll find that while our `generatePrimes()` function is running, our program is completely unresponsive: you can't type anything, or click anything, or do anything else.
```suggestion
You'll find that while our `generatePrimes()` function is running, our program is completely unresponsive: you can't type anything, click anything, or do anything else.
```

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
>  - start a long-running operation by calling a function
```suggestion
1. Start a long-running operation by calling a function.
```
these points are linked to each other in a sequential order, so changing them to numbered list

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
>  - be notified with the result of the operation, when it eventually completes.
```suggestion
2. Have that function start the operation and return immediately, so that our program can still be responsive to other events.
3. Notify us with the result of the operation when it eventually completes.
```

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +That's what asynchronous functions can do, and the rest of this module explains how they are implemented in JavaScript.
```suggestion
That's precisely what asynchronous functions can do. The rest of this module explains how they are implemented in JavaScript.
```

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +The description we just saw of asynchronous functions might remind you of event handlers, and if it does, you'd be right. Event handlers are really a form of asynchronous programming: you provide a f
```suggestion
The description we just saw of asynchronous functions might remind you of event handlers, and if it does, you'd be right. Event handlers are really a form of asynchronous programming: you provide a function (the event handler) that will be called, not right away, but whenever the event happens. If "the event" is "the asynchronous operation has completed", then that event could be used to notify the caller about the result of an asynchronous function call.
```
Nothing incorrect with 'right away'

2022-06-21 15:48 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +Some early asynchronous APIs used events in this way. The {{domxref("XMLHttpRequest")}} API enables you to make HTTP requests to a remote server using JavaScript. Since this can take a long time, it'
```suggestion
Some early asynchronous APIs used events in just this way. The {{domxref("XMLHttpRequest")}} API enables you to make HTTP requests to a remote server using JavaScript. Since this can take a long time, it's an asynchronous API, and you get notified about the progress and eventual completion of a request by attaching event listeners to the `XMLHttpRequest` object.
```
The original sentence is better with 'just' for emphasis.

2022-06-21 21:31 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +In this article, we explain what asynchronous programming is, why we need it, and briefly discuss some of the ways asynchronous functions have historically been implemented in JavaScript.
Yes, of course, I agree. The future tense is a style issue and I should have left it as it was.

2022-06-21 21:50 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
>  Many functions provided by browsers, and especially the most interesting ones, can potentially take a long time, and are therefore asynchronous. For example:
Yes, I missed that. That's better.

2022-06-21 22:09 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +Here, `makeGreeting()` is a **synchronous function**, because the caller has to wait for the function to finish its work and return before the caller can continue.
I am wondering about the following:

to finish its work and return a value before the caller can continue.

2022-06-21 22:18 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +This program generates a number of large prime numbers, using a very inefficient algorithm, when the user clicks the "Generate primes" button. The user can set the number of primes to generate, which
I was thinking about controlling a program while it was executing (with a slider, for example).

I agree, control is not incorrect.

2022-06-21 22:21 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +The next example is just like the last one, except we added a text box for you to type in. This time, click "Generate primes" and then try typing in the text box.
Yes, much clearer.

2022-06-21 22:35 UTC, peterhauke commented
Thanks for the review. Very insightful. Much appreciated.

2022-06-22 13:49 UTC, dipikabh commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +This program generates a number of large prime numbers, using a very inefficient algorithm, when the user clicks the "Generate primes" button. The user can set the number of primes to generate, which
I see what you're saying with the use of the word 'control', but I guess it is apparent from the code example that there is no slider. How about replacing that sentence with:
"The higher the number a user specifies, the longer the operation will take."

2022-06-22 13:52 UTC, dipikabh commented
Thanks @peterhauke for the changes and your comments. I have added my response to some your suggestions.

2022-06-22 14:30 UTC, peterhauke commented on files/en-us/learn/javascript/asynchronous/introducing/index.md
> +This program generates a number of large prime numbers, using a very inefficient algorithm, when the user clicks the "Generate primes" button. The user can set the number of primes to generate, which
Yes, that is more simple and makes much more sense. I added "of primes" in the new commit as that is the title of the input field, giving:

The higher the number of primes a user specifies, the longer the operation will take.

2022-06-22 15:19 UTC, dipikabh approved these changes
Thank you! 👍

2022-06-22 15:19 UTC, merged