Split dynamic import into its own page
mdn/content pull request #17402
Opened 2022-06-18 07:04 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #10550

#### Supporting details

#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-18 07:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +browser-compat: javascript.operators.import
I suppose this also needs work from BCD to split the compat table?

2022-06-18 07:15 UTC, teoli2003 requested changes
Yes, it is a good idea. I've added a few comments and suggestions.

2022-06-18 07:15 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +The `import()` call is a syntax that closely resembles a function call, but `import` itself is a keyword, not a function. You cannot alias it like `const myImport = import`, which will throw a `Synta
```suggestion
The `import()` call is a syntax that closely resembles a function call, but `import` itself is a keyword, not a function. You cannot alias it like `const myImport = import`, which will throw a {{jsxref("SyntaxError")}}.
```

2022-06-18 07:15 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +
You should add some sentences to explain that this is the _dynamic import_ (vs the _static import_) as you use the distinction later in the page.

2022-06-18 07:15 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/import/index.md
> +There is also a function-like dynamic [**`import()`**](/en-US/docs/Web/JavaScript/Reference/Operators/import), which does not require scripts of `type="module"`.
No need for bold here.
```suggestion
There is also a function-like dynamic [`import()`](/en-US/docs/Web/JavaScript/Reference/Operators/import), which does not require scripts of `type="module"`.
```

2022-06-18 07:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +browser-compat: javascript.operators.import
Yes, we need a new file there: https://github.com/mdn/browser-compat-data/tree/main/javascript/operators

2022-06-18 07:42 UTC, teoli2003 commented
Looks good to me. Let's wait until the PR for bcd is created before formally reviewing and merging this.

2022-06-18 07:51 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +browser-compat: javascript.operators.import
https://github.com/mdn/browser-compat-data/pull/16720

2022-06-18 07:52 UTC, Josh-Cena commented
I also noticed `import.meta` is in "statements & declarations" instead of "expressions & operators". I will follow-up since that one requires BCD refactor as well.

2022-06-20 12:11 UTC, queengooborg commented
BCD PR has now been merged!

2022-06-20 12:20 UTC, teoli2003 commented
Thank you

2022-06-20 12:20 UTC, teoli2003 approved these changes

2022-06-20 12:20 UTC, merged