Remove a dead link
mdn/content pull request #17409
Opened 2022-06-18 16:49 UTC by okyanusoz

#### Summary

This PR fixes a deadlink in https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder.

Note: If anyone's able to find the correct link, please feel free to comment.

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ x] Fixes a typo, bug, or other error

2022-06-19 19:01 UTC, cw118 commented on files/en-us/web/api/mediarecorder/index.md
> +> **Note:** Some lines have been omitted for brevity.
I may be wrong but I was able to find the example at https://github.com/mdn/dom-examples/tree/master/media/web-dictaphone :)

2022-06-20 13:22 UTC, teoli2003 requested changes

2022-06-20 13:22 UTC, teoli2003 commented on files/en-us/web/api/mediarecorder/index.md
> +> **Note:** Some lines have been omitted for brevity.
Yes, please. Use the link found by @cw118 (Thank you!)

```suggestion
> **Note:** This code sample is inspired by the Web Dictaphone demo. Some lines have been omitted for brevity; [refer to the source](https://github.com/mdn/dom-examples/tree/master/media/web-dictaphone) for the complete code.
```

2022-06-23 08:02 UTC, okyanusoz commented on files/en-us/web/api/mediarecorder/index.md
> +> **Note:** Some lines have been omitted for brevity.
Done!

2022-06-23 08:03 UTC, teoli2003 approved these changes
👍

2022-06-23 08:04 UTC, merged