Add spec-url for CSS `:local-link`
mdn/content pull request #17445
Opened 2022-06-20 00:10 UTC by binyamin

See mdn/browser-compat-data#15253

#### Summary

Added spec-url for the CSS `:local-link` pseudo selector.

#### Motivation

This PR clears up confusion regarding the `:local-link` CSS feature.

#### Supporting details

- **MDN URL**: https://developer.mozilla.org/en-US/docs/Web/CSS/:local-link
- **Spec URL**: https://drafts.csswg.org/selectors/#local-link-pseudo

#### Related issues

- mdn/browser-compat-data#15253
- mdn/browser-compat-data#13029

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-20 04:56 UTC, teoli2003 requested changes

2022-06-20 04:56 UTC, teoli2003 commented on files/en-us/web/css/_colon_local-link/index.md
>  browser-compat: css.selectors.local-link
If we set `spec-url`, we should remove `browser-compat`
```suggestion
```

For all-false property we need to remove `{{Compatibility}}` and put a sentence instead like:

_This feature is a proposal integrated into the specification. Currently, no browser supports it._

2022-06-20 15:38 UTC, binyamin commented on files/en-us/web/css/_colon_local-link/index.md
> +spec-url: https://drafts.csswg.org/selectors/#local-link-pseudo
I just realized that this links to the _draft_ spec, and not the _published_ spec. Fixed.
```suggestion
spec-url: https://www.w3.org/TR/selectors-4/#the-local-link-pseudo
```

2022-06-20 15:39 UTC, teoli2003 commented on files/en-us/web/css/_colon_local-link/index.md
> +spec-url: https://drafts.csswg.org/selectors/#local-link-pseudo
We always link to the draft specs. The _published_ specs are useless. No browser looks at them.

2022-06-20 16:24 UTC, binyamin commented on files/en-us/web/css/_colon_local-link/index.md
> +spec-url: https://drafts.csswg.org/selectors/#local-link-pseudo
Huh. Seems ironic, but okay.

2022-06-21 06:36 UTC, teoli2003 approved these changes
I went ahead and fixed my review comments.

2022-06-21 06:43 UTC, merged

2022-06-21 06:43 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: