Adjusting description
mdn/content pull request #17522
Opened 2022-06-21 22:01 UTC by aardrian

#### Summary
Removed use of "semantic", tweaked description, linked `<menuitem>` for broader context.

#### Motivation
The use of "semantic" is [creating confusion](https://github.com/w3c/aria-practices/issues/353#issuecomment-1162386109) on what this element actually does. While in here I tweaked the overall description.

#### Supporting details
Links to other sources in this comment: https://github.com/w3c/aria-practices/issues/353#issuecomment-1162386109

#### Metadata
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-21 23:25 UTC, scottaohara requested changes

2022-06-21 23:25 UTC, scottaohara commented on files/en-us/web/html/element/menu/index.md
> +The **`<menu>`** [HTML](/en-US/docs/Web/HTML) element is treated by browsers (and exposed through the accessibility tree) as no different than a {{HTMLElement("ul")}}. It represents an unordered list
I think it would be better to merge your proposal with the original text, which is also found in the html spec

2022-06-21 23:43 UTC, aardrian commented on files/en-us/web/html/element/menu/index.md
> +The **`<menu>`** [HTML](/en-US/docs/Web/HTML) element is treated by browsers (and exposed through the accessibility tree) as no different than a {{HTMLElement("ul")}}. It represents an unordered list
Noted. Laptop closed for night, will revisit tomorrow.

2022-06-22 16:20 UTC, aardrian commented on files/en-us/web/html/element/menu/index.md
> +The **`<menu>`** [HTML](/en-US/docs/Web/HTML) element is treated by browsers (and exposed through the accessibility tree) as no different than a {{HTMLElement("ul")}}. It represents an unordered list
@schalkneethling Since `<menu>` is _not_ the same as `<ul role="menu">`, you would still need to add the `menu` role.

So it comes down to _if_ you want to use a list as the basis for an ARIA-powered menu or toolbar control, then you can make the case that `<menu role="menu">` is easier for developers to parse (visually, with styles, with script, etc.) than `<ul role="menu">`. It has no effect on users which element you use in that context though.

2022-06-22 16:22 UTC, aardrian commented on files/en-us/web/html/element/menu/index.md
> +The **`<menu>`** [HTML](/en-US/docs/Web/HTML) element is treated by browsers (and exposed through the accessibility tree) as no different than a {{HTMLElement("ul")}}. It represents an unordered list
@scottaohara added 'semantic' back into the definition to your point that the WHATWG HTML spec says it.

2022-06-22 17:41 UTC, scottaohara approved these changes

2022-06-22 20:05 UTC, schalkneethling approved these changes
Thanks, @aardrian 🎉

2022-06-22 20:05 UTC, merged