TextDecoderStream
mdn/content pull request #1760
Opened 2021-01-26 14:35 UTC by rachelandrew

Adds the `TextDecoderStream` API.

Discussed in Matrix where to put the table of encodings, used by both this API and `TextDecoder`. As it is specified in the Encoding Standard we decided to place it under the Encoding API.

The only update to `TextEncoder` was to move that table from the constructor and link to it, and deal with the fixable flaws on that constructor page while I was at it.

Reviewer: @jpmedley

2021-01-28 00:25 UTC, jpmedley requested changes

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoder/textdecoder/index.html
> +    <em>label</em> of the encoder.  This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid label</a>
```suggestion
    <em>label</em> of the encoder.  This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid label</a>.
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/encoding/index.html
> +  specific encoder.</p>
```suggestion
<p class="summary">The <strong><code>encoding</code></strong> read-only property of the {{domxref("TextDecoderStream")}} interface returns a {{DOMxRef("DOMString")}} containing the name of the encoding algorithm used by the specific encoder.</p>
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/encoding/index.html
> +  specific encoder.</p>
I had to remove the indentation anyway, so I put the whole paragraph on one line (which seems to be MDN's preference.)

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/fatal/index.html
> +<p>The two possible values of error mode are <code>fatal</code> or <code>replacement</code>, the default being <code>replacement</code>.</p>
What does `replacement` mean?

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/fatal/index.html
> +<p>A {{jsxref("boolean")}} which will return <code>true</code> if the error mode is set to <code>fatal</code>, otherwise it returns <code>false</code>.</p>
```suggestion
<p>A {{jsxref("boolean")}} which will return <code>true</code> if the error mode is set to <code>fatal</code>. Otherwise it returns <code>false</code>.</p>
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/ignorebom/index.html
> +  - API
```suggestion
  - API
  - Encoding API
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/ignorebom/index.html
> +  - API
I should have thought of this above. They include the name of the API in the tags. Please do this throughout.

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/index.html
> +<p class="summary">The <strong><code>TextDecoderStream</code></strong> interface of the {{domxref('Encoding API','','',' ')}} is used to convert a stream of strings into bytes in the UTF-8 encoding.
```suggestion
<p class="summary">The <strong><code>TextDecoderStream</code></strong> interface of the {{domxref('Encoding API','','',' ')}} converts a stream of strings into bytes in the UTF-8 encoding. It is the streaming equivalent of {{domxref("TextDecoder")}}.</p>
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/index.html
> +</ul>
You should check this with Chris. I think we'd rather have the examples in this. This gives MDN more control over them and cuts off the possibility of a broken link.

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/readable/index.html
> +<p>Returning a {{domxref("ReadableStream")}} from a <code>TextDecoderStream</code>.</p>
```suggestion
<p>This example shows how to return a {{domxref("ReadableStream")}} from a <code>TextDecoderStream</code>.</p>
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/textdecoderstream/index.html
> +  <dd>A {{domxref("DOMString")}} defaulting to <code>utf-8</code>. This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid label</a>.</dd>
```suggestion
  <dd>A {{domxref("DOMString")}} defaulting to <code>utf-8</code>. This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid encoding</a>.</dd>
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/textdecoderstream/index.html
> +  <dd>A {{domxref("DOMString")}} defaulting to <code>utf-8</code>. This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid label</a>.</dd>
Should this be any _supported_ encoding?

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/textdecoderstream/index.html
> +  <dd>Is a <code>TextDecoderOptions</code> dictionary with the property:
```suggestion
  <dd>A <code>TextDecoderOptions</code> dictionary with the property:
```

2021-01-28 00:25 UTC, jpmedley commented on files/en-us/web/api/textdecoderstream/textdecoderstream/index.html
> +<p>The following example demonstrates how to decode binary data retrieved from a {{jsxref("fetch")}}. THe data will be intepreted as UTF-8, as no <code>label</code> has been passed.</p>
```suggestion
<p>The following example demonstrates how to decode binary data retrieved from a {{jsxref("fetch")}} call. The data will be interpreted as UTF-8, as no <code>label</code> has been passed.</p>
```

2021-01-28 06:55 UTC, rachelandrew commented on files/en-us/web/api/encoding_api/encodings/index.html
> +title: Encoding API Encodings
yeah - I had the same thought, at least it is descriptive!

2021-01-28 06:59 UTC, rachelandrew commented on files/en-us/web/api/textdecoderstream/index.html
> +</ul>
It seems to make sense on the main interface page. It's complex to have good examples for these (because you need something to stream content as well as retrieve it) so linking to the fully worked examples on the main page seems a good plan. I could start building our own but it would be time-consuming and they would need to be on Glitch or somewhere anyway.

I think having links to well built examples plus snippets as I have done on the constructor and property pages is a good midway point for this stuff.

cc @chrisdavidmills

2021-01-28 07:01 UTC, rachelandrew commented on files/en-us/web/api/textdecoderstream/textdecoderstream/index.html
> +  <dd>A {{domxref("DOMString")}} defaulting to <code>utf-8</code>. This may be <a href="/en-US/docs/Web/API/Encoding_API/Encodings">any valid label</a>.</dd>
it's the label for an encoding though, as per spec. https://encoding.spec.whatwg.org/#label

2021-01-29 15:08 UTC, rachelandrew commented on files/en-us/web/api/textdecoderstream/index.html
> +</ul>
checked this with Chris who agreed with my suggestion.

2021-02-05 13:49 UTC, rachelandrew commented on files/en-us/web/api/textdecoderstream/fatal/index.html
> +<p>The two possible values of error mode are <code>fatal</code> or <code>replacement</code>, the default being <code>replacement</code>.</p>
added some text to explain.

2021-02-09 14:34 UTC, jpmedley approved these changes

2021-02-09 14:41 UTC, merged