Updated Syntax
mdn/content pull request #17646
Opened 2022-06-25 11:05 UTC by PrajwalBorkar

#### Summary

Replaced var with const or let as appropriate & updated spreadsheet as some files contain Var missing in the list.
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-25 11:16 UTC, PrajwalBorkar commented
Does anyone know how to resolve this error? I'm getting this when I try to make changes in repo.
![Screenshot (69)](https://user-images.githubusercontent.com/48290911/175771128-e00e8f21-6798-4950-8e4f-861b4153d01b.png)

2022-06-26 03:25 UTC, teoli2003 commented on files/en-us/web/api/mssitemodeevent/index.md
> +declare const MSSiteModeEvent: {
This is not JavaScript.

```suggestion
declare var MSSiteModeEvent: {
```

2022-06-26 03:28 UTC, teoli2003 requested changes
One example is not real JS, let's fix it.

2022-06-26 03:28 UTC, teoli2003 commented on files/en-us/web/api/navigator/productsub/index.md
>  <script>
Let's transform this into JS:
```suggestion
```

2022-06-26 03:28 UTC, teoli2003 commented on files/en-us/web/api/navigator/productsub/index.md
>  </script>
```suggestion
console.log(prodsub()); // Returns: 20010725
```

Please delete lines 32-34

2022-06-26 07:08 UTC, teoli2003 approved these changes
👍

2022-06-26 07:10 UTC, merged