Updated Syntax
mdn/content pull request #17669
Opened 2022-06-26 11:19 UTC by PrajwalBorkar

#### Summary

Replaced var with const or let as appropriate & updated spreadsheet as 40 files containing Var were missing in the list.
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-26 11:51 UTC, teoli2003 requested changes

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/network_information_api/index.md
> +let type = connection.effectiveType;
We don't need the prefixes. According to the bcd table, they were never implemented as such anyway.
```suggestion
let type = navigator.connection.effectiveType;
```

Please fix line 41 too, as well as the next example.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/networkinformation/effectivetype/index.md
>  ```js
We don't have a syntax section on property pages anymore.
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/networkinformation/effectivetype/index.md
>  ```
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/networkinformation/effectivetype/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/entries/index.md
> +folet entry of list.entries()) {
This is wrong.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/entries/index.md
> +let kid3 = document.createElement("span");
These should be `const`.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/entries/index.md
> +let list = node.childNodes;
This should be a `const`.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/keys/index.md
> +let---
```suggestion
---
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/keys/index.md
> +let kid3 = document.createElement("span");
These should be `const`.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/keys/index.md
> +for(let key of list.keys()) {
`for...of` can have `const`. See [SO](https://stackoverflow.com/questions/58483101/for-of-loop-should-i-use-const-or-let).

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/values/index.md
> +let---
No let here.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/values/index.md
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/values/index.md
> +let list = node.childNodes;
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/nodelist/values/index.md
> +for(let value of list.values()) {
for...of: const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/notification/dir/index.md
> +const---
```suggestion
---
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/notification/vibrate/index.md
> +const---
```suggestion
---
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/getcontext/index.md
> +let gl = offscreen.getContext("webgl");
const please.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/index.md
> +let gl = offscreen.getContext('webgl');
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/index.md
> +let bitmapOne = offscreen.transferToImageBitmap();
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/index.md
> +let bitmapTwo = offscreen.transferToImageBitmap();
const please.

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/index.md
> +  let gl = canvas.getContext("webgl");
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/transfertoimagebitmap/index.md
> +let gl = offscreen.getContext("webgl");
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/offscreencanvas/width/index.md
> +let offscreen = new OffscreenCanvas(256, 256);
const please

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
>                                   buildShoppingCartDetails());
```suggestion
const request = new PaymentRequest(buildSupportedPaymentMethodData(),
                                   buildShoppingCartDetails());
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
>                                             checkoutObject);
```suggestion
          const request = new PaymentRequest(buildSupportedPaymentMethodData(),
                                             checkoutObject);
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentaddress/languagecode/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentaddress/languagecode/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequest/id/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequest/id/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequest/shippingtype/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequest/shippingtype/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/instrumentkey/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/instrumentkey/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/methoddata/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/methoddata/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/modifiers/index.md
>  ```js
```suggestion
```

2022-06-26 11:51 UTC, teoli2003 commented on files/en-us/web/api/paymentrequestevent/modifiers/index.md
>  ### Value
```suggestion
## Value
```

2022-06-26 12:19 UTC, PrajwalBorkar commented on files/en-us/web/api/nodelist/values/index.md
I updated to let because [here](https://github.com/mdn/content/blob/main/files/en-us/web/api/nodelist/foreach/index.md#example) it was same

2022-06-26 12:19 UTC, PrajwalBorkar commented on files/en-us/web/api/nodelist/keys/index.md
> +let kid3 = document.createElement("span");
Please check this [file](https://github.com/mdn/content/blob/main/files/en-us/web/api/nodelist/foreach/index.md#example) also

2022-06-26 12:22 UTC, PrajwalBorkar commented on files/en-us/web/api/nodelist/values/index.md
> +let list = node.childNodes;
I have updated it as per other files if this needs to be changed then we can change [here](https://github.com/mdn/content/blob/main/files/en-us/web/api/nodelist/foreach/index.md#example) also

2022-06-26 12:24 UTC, PrajwalBorkar commented on files/en-us/web/api/notification/vibrate/index.md
> +const---
Sorry for these errors

2022-06-26 12:27 UTC, PrajwalBorkar commented on files/en-us/web/api/offscreencanvas/getcontext/index.md
> +let gl = offscreen.getContext("webgl");
Should I change [here](https://github.com/mdn/content/blob/main/files/en-us/web/api/offscreencanvas/offscreencanvas/index.md#examples) also

2022-06-26 12:30 UTC, PrajwalBorkar commented on files/en-us/web/api/offscreencanvas/transfertoimagebitmap/index.md
> +let gl = offscreen.getContext("webgl");
Please review [here](https://github.com/mdn/content/blob/main/files/en-us/web/api/offscreencanvas/offscreencanvas/index.md#examples) also

2022-06-26 17:56 UTC, teoli2003 requested changes
We are almost there!

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/network_information_api/index.md
> +  let type = connection.effectiveType;
```suggestion
  type = connection.effectiveType;
```

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/networkinformation/downlinkmax/index.md
> +     connectionType = navigator.connection.effectiveType;
```suggestion
    connectionType = navigator.connection.effectiveType;
```

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/nodelist/entries/index.md
> +for(let entry of list.entries()) {
```suggestion
for(const entry of list.entries()) {
```

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/notification/close/index.md
> +  const n = new Notification(theTitle,options);
```suggestion
  const n = new Notification(theTitle, options);
```

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/notification/requestpermission/index.md
> +    let notification = new Notification("Hi there!");
```suggestion
    const notification = new Notification("Hi there!");
```

2022-06-26 17:56 UTC, teoli2003 commented on files/en-us/web/api/notification/requestpermission/index.md
> +        let notification = new Notification("Hi there!");
```suggestion
        const notification = new Notification("Hi there!");
```

2022-06-27 06:24 UTC, teoli2003 approved these changes
Thank you! There are plenty of other fixes we could do to these examples. (I've seen cases where we could have used template literals, others where we should have used `for...of`, …) But let's keep this PR contained.

2022-06-27 06:24 UTC, merged

2022-06-27 06:25 UTC, PrajwalBorkar commented
> We are almost there!

Please check this [file] (https://github.com/mdn/content/blob/main/files/en-us/web/api/nodelist/foreach/index.md#example).  [here](https://github.com/mdn/content/blob/main/files/en-us/web/api/offscreencanvas/offscreencanvas/index.md#examples) also These files also contain the same syntax which should be changed because I referred to these files in some cases and u requested to change that.

2022-06-27 06:27 UTC, PrajwalBorkar commented
> Thank you! There are plenty of other fixes we could do to these examples. (I've seen cases where we could have used template literals, others where we should have used `for...of`, …) But let's keep this PR contained.

There are couple of files which contains the wrong syntax which I have linked in unresolved conversation.

2022-06-27 06:29 UTC, teoli2003 commented
@PrajwalBorkar Can you create a follow-up with these? This PR was getting too long and difficult to follow.

2022-06-27 06:30 UTC, PrajwalBorkar commented
Okay, I will link this issue to the new PR.