Updated syntax
mdn/content pull request #17698
Opened 2022-06-27 11:56 UTC by PrajwalBorkar

#### Summary

Resolving remaining issues from PR #17669 @teoli2003 
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662 
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-27 12:08 UTC, teoli2003 requested changes
One tiny change and we can merge this.

2022-06-27 12:09 UTC, teoli2003 approved these changes

2022-06-30 03:36 UTC, Josh-Cena commented on files/en-us/web/api/network_information_api/index.md
> +      preloadVideo = false;
```suggestion
    preloadVideo = false;
```

2022-06-30 03:39 UTC, Josh-Cena commented on files/en-us/web/api/network_information_api/index.md
>      preloadVideo = false;
This entire code block can be a one-liner `const preloadVideo = navigator.connection?.effectiveType !== 'slow-2g';` which is arguably even more readable.

2022-06-30 04:23 UTC, teoli2003 commented on files/en-us/web/api/network_information_api/index.md
>      preloadVideo = false;
Yes, I think that the example in Network Information API should be "vertically" re-read. I think there are plenty of other things to fix, like for example using `for...of`. Let's keep this for a follow-up!

2022-06-30 04:23 UTC, merged