Add mention of module/block scope in closures
mdn/content pull request #17722
Opened 2022-06-28 04:33 UTC by Josh-Cena

#### Summary

Fix #3587 (with a minor reprise of the scope management issue; I don't know how we can better fix this. We can reopen if that requires further action.)
Fix #9075

#### Motivation

In addition to adding module/block, I'm also converting `var` to `let`/`const`. This is tricky because some `var` here is for illustration purposes, so it has to be done with caution. I decided to keep `var` statements in the section about "common mistake" here, because with `let` declarations, this becomes a non-problem, but the solutions here still seem intriguing for pre-ES6 archeology purposes.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-06-28 05:34 UTC, sideshowbarker submitted a review, later dismissed

2022-06-28 05:56 UTC, teoli2003 requested changes

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/glossary/scope/index.md
>  The current context of execution. The context in which {{glossary("value","values")}} and **expressions** are "visible" or can be referenced. If a **{{glossary("variable")}}** or other expression is
```suggestion
The **scope** is the current context of execution, in which {{glossary("value","values")}} and _expressions_ are "visible" or can be referenced. If a _{{glossary("variable")}}_, or another expression, is not in the current scope, then it is unavailable for use. Scopes can also be layered in a hierarchy, so that child scopes have access to parent scopes, but not vice versa.
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/glossary/scope/index.md
> +- **Function Scope**: The scope created with a **{{glossary("function")}}**.
```suggestion
- Global scope: The default scope for all code running in script mode.
- Module scope: The scope for code running in module mode.
- Function scope: The scope created with a {{glossary("function")}}.
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/glossary/scope/index.md
> +A **{{glossary("function")}}** creates a scope, so that (for example) a variable defined exclusively within the function cannot be accessed from outside the function or within other functions. For in
```suggestion
- Block scope: The scope created with a pair of curly braces (a [block](/en-US/docs/Web/JavaScript/Reference/Statements/block)).

A {{glossary("function")}} creates a scope, so that (for example) a variable defined exclusively within the function cannot be accessed from outside the function or within other functions. For instance, the following is invalid:
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/glossary/scope/index.md
> +In addition, variables declared with [`let`](/en-US/docs/Web/JavaScript/Reference/Statements/let) or [`const`](/en-US/docs/Web/JavaScript/Reference/Statements/const) can have an additional scope:
```suggestion
In addition, variables declared with [`let`](/en-US/docs/Web/JavaScript/Reference/Statements/let) or [`const`](/en-US/docs/Web/JavaScript/Reference/Statements/const) can live in an additional scope:
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
>      alert(name); // use variable declared in the parent function
Let's avoid `alert`:
```suggestion
    console.log(name); // use variable declared in the parent function
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +Run the code using [this JSFiddle link](https://jsfiddle.net/xAFs9/3/) and notice that the `alert()` statement within the `displayName()` function successfully displays the value of the `name` variab
```suggestion
Run the code using [this JSFiddle link](https://jsfiddle.net/3dxck52m/) and notice that the `console.log()` statement within the `displayName()` function successfully displays the value of the `name` variable, which is declared in its parent function. This is an example of _lexical scoping_, which describes how a parser resolves variable names when functions are nested. The word _lexical_ refers to the fact that lexical scoping uses the location where a variable is declared within the source code to determine where that variable is available. Nested functions have access to variables declared in their outer scope.
```

(We really should convert jsfiddle into internal examples (Live samples or interactive samples).

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
>  - Local Scope (Own scope)
```suggestion
- Local scope (Own scope)
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
>  - Global Scope
```suggestion
- Enclosing scope (can be block, function, or module scope)
- Global scope
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +    document.getElementById(item.id).onfocus = function () {
Let's use an arrow function here:
```suggestion
    document.getElementById(item.id).onfocus = () => {
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +  return function () {
```suggestion
  return () => {
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +If you don't want to use more closures, you can use the [`let`](/en-US/docs/Web/JavaScript/Reference/Statements/let) or [`const`](/en-US/docs/Web/JavaScript/Reference/Statements/const) keyword introd
Version numbers (especially ES6, ES2015 that are 7+ years old) are useless for developers. Let's simplify:
```suggestion
If you don't want to use more closures, you can use the [`let`](/en-US/docs/Web/JavaScript/Reference/Statements/let) or [`const`](/en-US/docs/Web/JavaScript/Reference/Statements/const) keyword:
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +  this.getName = function () {
```suggestion
  this.getName = () => {
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +  this.getMessage = function () {
```suggestion
  this.getMessage = () => {
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +MyObject.prototype.getName = function () {
```suggestion
MyObject.prototype.getName = () => {
```

2022-06-28 05:56 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +MyObject.prototype.getMessage = function () {
```suggestion
MyObject.prototype.getMessage = () => {
```

2022-06-28 07:54 UTC, Josh-Cena commented on files/en-us/web/javascript/closures/index.md
> +    document.getElementById(item.id).onfocus = function () {
The example here is showing pre-ES6 syntax and pitfalls, so I decided to keep it as-is. Anyone who doesn't use `var` after ES6 (i.e. hopefully everyone) won't be running into this.

2022-06-28 08:10 UTC, Josh-Cena commented on files/en-us/web/javascript/closures/index.md
> +Run the code using [this JSFiddle link](https://jsfiddle.net/xAFs9/3/) and notice that the `alert()` statement within the `displayName()` function successfully displays the value of the `name` variab
True, we would do more systematic work in the future on this, I hope?

2022-06-28 08:10 UTC, teoli2003 commented
Fine not to use ES6+ syntax in these cases.

2022-06-28 12:22 UTC, MrBrain295 commented on files/en-us/glossary/scope/index.md
> +- Function scope: The scope created with a {{glossary("function")}}.
```suggestion
- Function scope: A scope created with a {{glossary("function")}}.
```

2022-06-28 12:22 UTC, MrBrain295 commented on files/en-us/glossary/scope/index.md
> +- Block scope: The scope created with a pair of curly braces (a [block](/en-US/docs/Web/JavaScript/Reference/Statements/block)).
```suggestion
- Block scope: A scope created with a pair of curly braces (a [block](/en-US/docs/Web/JavaScript/Reference/Statements/block)).
```

2022-06-28 12:45 UTC, Josh-Cena commented on files/en-us/glossary/scope/index.md
> +- Function scope: The scope created with a {{glossary("function")}}.
The colon makes it tricky. The following are good:

- A function scope is a scope created...
- "Function scope" is the scope created...

But the following doesn't sound assertive enough as a definition:

- "Function scope" is a scope created...

In particular, "the" (IMO) gives me a sense of "necessary and sufficient". Since we don't have the "a" article before "function scope" and we are making definitions here, "the" seems fine to me.

2022-06-28 12:51 UTC, MrBrain295 commented on files/en-us/glossary/scope/index.md
> +- Function scope: The scope created with a {{glossary("function")}}.
Ok

2022-07-02 09:34 UTC, teoli2003 requested changes
I made a (last) pass and I think we are close to getting this landed. Thanks!

2022-07-02 09:34 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +In ES6, JavaScript introduced the `let` and `const` declarations, which, among other things like [temporary dead zones](/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz), al
```suggestion
In ES6, JavaScript introduced the `let` and `const` declarations, which, among other things like [temporal dead zones](/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz), allow you to create block-scoped variables.
```

2022-07-02 09:34 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
>      document.body.style.fontSize = size + 'px';
What about:
```suggestion
    document.body.style.fontSize = `${size}px`;
```

2022-07-02 09:34 UTC, teoli2003 commented on files/en-us/web/javascript/closures/index.md
> +  if (true) {
`if (true)` is an idiom to avoid. (I remember missing a top mark at uni because I forgot one)

Would this work?
```suggestion
  {
```

2022-07-02 09:36 UTC, Josh-Cena commented on files/en-us/web/javascript/closures/index.md
> +  if (true) {
I was trying to make this more non-trivial... I would go with `Math.random() > 0.5`, then.

2022-07-02 10:00 UTC, teoli2003 approved these changes

2022-07-02 10:00 UTC, merged