Correct possible code errors for example 7
mdn/content pull request #17731
Opened 2022-06-28 11:04 UTC by darren2pro

#### Summary

There was a mild syntax error when I tested the code for example 7 in this page. The bugs and my fixes are described below.

- Bug1: Re-declare the variable `e`
    - Fix: Change the variable name to `event`
- Bug2: Assign to constant variable `row`
    - Fix: Change the declaration keyword to `var`
#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-28 14:20 UTC, teoli2003 requested changes
I agree that we should use `event` instead of `e` (as `e` is the parameter name), but `row` seems correct to me.

2022-06-28 16:36 UTC, teoli2003 commented on files/en-us/web/api/document_object_model/examples/index.md
> +  var row = thead.insertRow(-1);
I didn't see line 323, `let` is fine then.

2022-06-29 01:24 UTC, darren2pro commented on files/en-us/web/api/document_object_model/examples/index.md
> +  var row = thead.insertRow(-1);
@teoli2003 done! Thank you

2022-06-29 04:55 UTC, teoli2003 approved these changes

2022-06-29 04:56 UTC, merged

2022-06-29 04:56 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: