fix: missing semicolon and `function` keyword
mdn/content pull request #17780
Opened 2022-06-29 18:09 UTC by sentyaev

#### Summary

Fixes missing semicolon and `function` keyword in "A complete traps list example" code sample.

#### Motivation

Fix typo.

#### Supporting details

--
#### Related issues

--
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-30 01:42 UTC, Josh-Cena requested changes
Hi—this code is correct, and we prefer the method syntax these days. Could you refactor the other code to this syntax instead?

2022-06-30 07:49 UTC, sentyaev commented
> Hi—this code is correct, and we prefer the method syntax these days. Could you refactor the other code to this syntax instead?

Sure! np
@Josh-Cena I'm thinking to also make variable names in this code block more consistent with the rest of this file code samples. This code block has Hungarian notation for variable name, so I'm going to change it to be JS'y names.

2022-06-30 08:23 UTC, teoli2003 commented
Yes, please, feel free to remove variables named using Hungarian notation.

2022-06-30 11:03 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/proxy/index.md
> +    if (descriptor && 'value' in descriptor) { target.setItem(key, descriptor.value); }
```suggestion
    if (descriptor && 'value' in descriptor) {
      target.setItem(key, descriptor.value);
    }
```

2022-06-30 19:58 UTC, sentyaev commented
@Josh-Cena I think it's done. Ping me in case you thing more changes needed.

2022-07-01 01:37 UTC, Josh-Cena approved these changes
Thanks, the change looks good to me.

Congratulations on your first contribution here—welcome aboard!

2022-07-01 01:37 UTC, merged