fix: var-> const
mdn/content pull request #17800
Opened 2022-06-30 02:35 UTC by OnkarRuikar

One `var value` declaration left unchanged.
We can simplify the code with modern constructs.

2022-06-30 03:00 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/index.md
> +  entries.forEach((entry, i) => {
Personal opinion: if we are to use `forEach()`, we can merge the two like `performance.getEntries().forEach(...)`.

2022-06-30 03:48 UTC, OnkarRuikar commented on files/en-us/web/api/performanceentry/index.md
> +  entries.forEach((entry, i) => {
I think for an example making it a separate variable is more readable than clubbing everything on one line.

2022-06-30 03:50 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/index.md
> +  entries.forEach((entry, i) => {
Makes sense.

2022-06-30 08:08 UTC, teoli2003 requested changes

2022-06-30 08:08 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/index.md
>      if (supported) {
I think this is better as it does what it reads in Englsih.
```suggestion
    if (prop in entry) {
```

2022-06-30 08:18 UTC, teoli2003 requested changes

2022-06-30 08:18 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/index.md
>    }
The parenthesis is missing (that would lead to a syntax error).
```suggestion
  })
```

2022-06-30 08:18 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/index.md
>  }
Let's add the call so a cut & paste will work directly:
```suggestion
}

print_PerformanceEntries();
```

2022-06-30 08:50 UTC, teoli2003 approved these changes

2022-06-30 08:50 UTC, merged

2022-07-01 01:40 UTC, OnkarRuikar commented on files/en-us/web/api/performanceentry/index.md
> +    print_PerformanceEntry(entry);
It's been fixed in #17811.