Reorganize documentation for MathML global attributes
mdn/content pull request #17812
Opened 2022-06-30 09:23 UTC by fred-wang

- Add a new article for the
  [math-depth](https://w3c.github.io/mathml-core/#the-math-script-level-property)
  property, which is used to implement the global attribute `scriptlevel`
  in MathML Core.
- Remove all per-element references to
  [global attributes](https://w3c.github.io/mathml-core/#global-attributes)
  from MathML element pages as well as the  Gecko-specific notes for
  `mathvariant`. Instead, they are moved to dedicated pages about global
  attributes.
- Introduce a new `mathml/global_attributes/` directory, based on
  HTML's one. For now, most of the links for these attributes point to
  equivalent pages for HTML. New articles are created for MathML-specific
  global attributes.

Note that the specifications and browser compatibility data for these new
articles are currently missing.

#### Summary

Reorganize documentation for MathML global attributes, moving them to dedicated pages instead of duplicating on each MathML element article. This also introduces CSS `math-depth` article for the sake of documenting `scriptlevel`.

#### Motivation

In the past, some attributes could be applied to a large class of MathML elements but not necessarily to all of them. This has changed with MathML Core where these generic attributes are now clearly defined as [global attributes](https://w3c.github.io/mathml-core/#global-attributes). Additionally, many attributes have now been taken from HTML (such as `nonce` or `on*` or `data-*`) and need to be documented.

#### Supporting details

https://w3c.github.io/mathml-core/#global-attributes

#### Related issues

#### Metadata

- [x] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-06-30 09:37 UTC, teoli2003 commented
Hi!

I have a generic question: what is the implementation status of MathML-Core?

2022-06-30 10:12 UTC, fred-wang commented
short answer: implemented in Chromium under a flag, and some alignment has been done on the Gecko/WebKit side.

2022-07-01 00:13 UTC, estelle commented
Do we have MathML page types? cc: @wbamberg?

2022-07-01 00:17 UTC, estelle commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +  - `true`, which means `normal`.
this should likely be in a ## Values section.

2022-07-01 00:20 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathbackground/index.md
> +
an example of how it is used would be good and what value syntaxes are valid. Perhaps a link to color values.

2022-07-01 00:21 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathcolor/index.md
> +
same comment as above. Should people be opting for CSS instead of these attributes? If yes, adding a note to not use this attribute would be good too

2022-07-01 00:50 UTC, wbamberg commented
> Do we have MathML page types? cc: @wbamberg?

According to https://github.com/mdn/content/issues/15539, although MathML does have specialised page types, it's not P1, so isn't slated to get page types defined yet. But I'd be happy for someone to define them of course.

2022-07-01 05:13 UTC, fred-wang commented
@estelle Thanks for the review. I believe I've addressed all the feedback.

I'm not sure I know what page types are, but ideally I'd like to have a sidebar similar to https://developer.mozilla.org/en-US/docs/Web/HTML where elements and global attributes are accessible from the sidebar. Probably out of the scope for this commit. For now, I added a link to global attributes from the MathML attributes page.

2022-07-01 22:44 UTC, estelle reviewed
a few more spots could use values and examples. I have a few questions too which I had reading this, so think addressing those may help the newbie (like me.)

Thanks!

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +The **`scriptlevel`** [global attribute](/en-US/docs/Web/MathML/Global_attributes) sets the [math-depth](/en-US/docs/Web/CSS/math-depth) of a MathML element. If `<U>` is an unsigned [integer](/en-US/
```suggestion
The **`scriptlevel`** [global attribute](/en-US/docs/Web/MathML/Global_attributes) sets the [math-depth](/en-US/docs/Web/CSS/math-depth) of a MathML element. 

## Values

If `<U>` is an unsigned [integer](/en-US/docs/Web/CSS/integer) (i.e. with prefix sign symbol removed) then the accepted values are:
```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +The **`scriptlevel`** [global attribute](/en-US/docs/Web/MathML/Global_attributes) sets the [math-depth](/en-US/docs/Web/CSS/math-depth) of a MathML element. If `<U>` is an unsigned [integer](/en-US/
likely needs more than just the header, but I don't know mathML at all.

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathbackground/index.md
> +
```suggestion

> **Note:** Use CSS for styling MathML whenever possible. The `mathbackground` attribute should only be included for applications that are not CSS-aware and will be overridden by the CSS `background-color` property value, if set.

```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/css/math-depth/index.md
> +{{Compat}}
If there are any other CSS properties that are math-related, a ## See also would be fantastic.

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/attribute/index.md
> +This is an alphabetical list of MathML attributes. More details for each attribute are available on particular [element pages](/en-US/docs/Web/MathML/Element)
```suggestion
This is an alphabetical list of MathML attributes. More details for each attribute are available on relevant [MathML element pages](/en-US/docs/Web/MathML/Element)
```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +- `true`, which means `normal`.
```suggestion
- `true`
  -: Sets the display style to `normal`.
```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +- `false`, which means `compact`.
```suggestion
- `false`
   -: Sets the display style to `compact`.
```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +- All [global attributes](/en-US/docs/Web/MathML/Global_attributes).
if there is a CSS styles that has similar effect, please add it.

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/href/index.md
> +
Can we include an example or two?

## Examples

```html
<math href="x">
<maction href="y">
````

Per below, href is valid on all elements, so including a non-math element helps impress that note from the next section.

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathcolor/index.md
> +
```suggestion

> **Note:** Use CSS for styling MathML whenever possible. The `mathcolor` attribute should only be included for applications that are not CSS-aware and will be overridden by the CSS `color` property , if set.

```

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathcolor/index.md
> +
Does `mathcolor` impact border-color like CSS `color` does?

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathsize/index.md
> +
values and example would be good.

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +The **`mathvariant`** [global attribute](/en-US/docs/Web/MathML/Global_attributes)  attribute defines logical classes of token elements. Each class provides a collection of typographically-related sy
Is there a way to make this more understandable for the newbie? An example and value might help, as might a screen shot maybe?

2022-07-01 22:44 UTC, estelle commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +The **`scriptlevel`** [global attribute](/en-US/docs/Web/MathML/Global_attributes) sets the [math-depth](/en-US/docs/Web/CSS/math-depth) of a MathML element. If `<U>` is an unsigned [integer](/en-US/
maybe an example too.

2022-07-01 22:59 UTC, wbamberg commented
> @estelle Thanks for the review. I believe I've addressed all the feedback.
> 
> I'm not sure I know what page types are, but ideally I'd like to have a sidebar similar to https://developer.mozilla.org/en-US/docs/Web/HTML where elements and global attributes are accessible from the sidebar. Probably out of the scope for this commit. For now, I added a link to global attributes from the MathML attributes page.

Page types are just a piece of metadata, represented as a `"page-type"` front matter key, which says what kind of page something is: for example if it documents a WebAPI instance method, or an HTML element, or a CSS property. We will use them to build sidebars and also to define the kind of content a given page ought to include. I guess MathML would at least have `mathml-element` and `mathml-attribute`.

2022-07-02 05:09 UTC, teoli2003 commented
> > @estelle Thanks for the review. I believe I've addressed all the feedback.
> > I'm not sure I know what page types are, but ideally I'd like to have a sidebar similar to https://developer.mozilla.org/en-US/docs/Web/HTML where elements and global attributes are accessible from the sidebar. Probably out of the scope for this commit. For now, I added a link to global attributes from the MathML attributes page.
> 
> Page types are just a piece of metadata, represented as a `"page-type"` front matter key, which says what kind of page something is: for example if it documents a WebAPI instance method, or an HTML element, or a CSS property. We will use them to build sidebars and also to define the kind of content a given page ought to include. I guess MathML would at least have `mathml-element` and `mathml-attribute`.

Yes, I would have:
- `mathml-element`
- `mathml-global-attribute`
- `mathml-attribute`

And the two common to every area:
- `guide`
- `landing`

2022-07-04 06:20 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/mathcolor/index.md
> +
Yes `mathcolor` sets the `color` property via a [presentational hint](https://html.spec.whatwg.org/#presentational-hints) so all the feature of `color` apply too. Do you mean we should be more explicit about it?  I only explicitly mentioned "fraction bars or radical symbols" below as they are specific to math.

2022-07-04 07:47 UTC, fred-wang commented
@estelle Thanks. I believe this is ready for another round of review!

2022-07-08 12:36 UTC, teoli2003 requested changes
Thanks a lot, @fred-wang . I had a few comments/changes, but this is very close to being ready to merge.

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathsize/index.md
> +{{Specifications}}
```suggestion
## Notes on MathML versions




## Specifications

{{Specifications}}

- In MathML 3 and earlier versions, keywords `small`, `normal`, and `big` as
  well as the MathML3-specific syntax for lengths was supported.
  Since MathML Core, the syntax matches CSS
  {{cssxref("&lt;length-percentage&gt;")}} values.

* This attribute was designed for MathML applications that are not CSS-aware.
  Since MathML Core, the use of equivalent CSS is recommended instead.
```

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +are by convention italic, no special classes are used by default.
NIT:
```suggestion
With the exception of [`mi`](/en-US/docs/Web/MathML/Element/mi) elements with a single character,
which are by convention italic, no special classes are used by default.
```

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +* `mathvariant` values other than `normal` were designed for backward compatibility. Authors are encouraged to instead directly use the corresponding Unicode characters from the [Mathematical Alphanu
```suggestion
## Notes on MathML versions

> **Note:** `mathvariant` values other than `normal` were designed for backward compatibility. Authors are encouraged to instead directly use the corresponding Unicode characters from the [Mathematical Alphanumeric Symbols](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols).
```

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +
Same question as before: this looks like an implementation detail with no impact on developers.

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +- Some `mathvariant` values are only implemented starting with Gecko 28.0 (Firefox 28.0 / Thunderbird 28.0 / SeaMonkey 2.25) and require appropriate [math fonts](/en-US/docs/Web/MathML/Fonts).
```suggestion
```

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +
Taken from below:

```suggestion
On Firefox, some `mathvariant` values are only implemented starting with Firefox 28 and require appropriate [math fonts](/en-US/docs/Web/MathML/Fonts).
```

2022-07-08 12:36 UTC, teoli2003 commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +* MathML Core relies on `math-depth` to implement the `scriptlevel` attribute, but implementations of older MathML versions may follow a different approach to implement similar side-effect on the `fo
Here again, isn't this an implementation detail?

2022-07-08 12:56 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +/*
Right, it seems I forgot to put the examples.

2022-07-08 13:01 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +- `add(<integer>)`
I don't understand what you mean here? How do we know there is a "specified integer" if it's removed from the syntax?

2022-07-08 13:03 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +- `<integer>`
Done.

2022-07-08 13:06 UTC, fred-wang commented on files/en-us/web/mathml/element/maction/index.md
>  - selection
OK, but I think it should be a separate thing when we rewrite the element pages.

2022-07-08 13:09 UTC, fred-wang commented on files/en-us/web/mathml/element/mfenced/index.md
>  ## Attributes
Yes, the plan was to do more changes to element article in separate PR as it's already big. Although it's true we would be temporarily losing that info...

2022-07-08 13:10 UTC, fred-wang commented on files/en-us/web/mathml/element/mi/index.md
> -## Attributes
Yes no more attributes.

2022-07-08 13:11 UTC, fred-wang commented on files/en-us/web/mathml/element/mi/index.md
>  ```html
`mathvariant` is a global attribute, I guess we can remove the example indeed. Can we do that in an "update all mathml elements" PR instead?

2022-07-08 13:14 UTC, fred-wang commented on files/en-us/web/mathml/element/mstyle/index.md
>  ## Attributes
Yes, both of these attributes are now global. Checking this page, it needs a lot of refresh, so let's do that in separate PR?

2022-07-08 13:16 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +* MathML Core relies on `math-style` to implement the `displaystyle` attribute, but implementations of older MathML versions may follow a different approach to implement similar behavior.
So the idea is that browsers will expose this via a CSS property and so developers can potentially directly get/set that property via other APIs... which won't work with legacy engines.

2022-07-08 13:19 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +
Yes, same answer.

2022-07-08 13:20 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +* MathML Core relies on `math-depth` to implement the `scriptlevel` attribute, but implementations of older MathML versions may follow a different approach to implement similar side-effect on the `fo
Same.

2022-07-08 13:38 UTC, teoli2003 approved these changes

2022-07-08 13:38 UTC, teoli2003 commented
Let's merge this!

2022-07-08 13:38 UTC, merged

2022-07-21 15:15 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/mathvariant/index.md
> +
Handled in https://github.com/mdn/content/pull/18599

2022-07-21 15:15 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/scriptlevel/index.md
> +* MathML Core relies on `math-depth` to implement the `scriptlevel` attribute, but implementations of older MathML versions may follow a different approach to implement similar side-effect on the `fo
Handled in https://github.com/mdn/content/pull/18599

2022-07-21 15:17 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +{{cssinfo}}
Still TODO:
https://developer.mozilla.org/en-US/docs/Web/CSS/math-depth

2022-07-21 15:18 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +{{CSSSyntax}}
Still TODO:
https://developer.mozilla.org/en-US/docs/Web/CSS/math-depth

2022-07-21 15:19 UTC, fred-wang commented on files/en-us/web/mathml/element/maction/index.md
>  - selection
Still TODO.

2022-07-21 15:20 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/displaystyle/index.md
> +* MathML Core relies on `math-style` to implement the `displaystyle` attribute, but implementations of older MathML versions may follow a different approach to implement similar behavior.
Done in https://github.com/mdn/content/pull/18599

2022-07-22 06:08 UTC, fred-wang commented on files/en-us/web/mathml/element/maction/index.md
>  - selection
https://github.com/mdn/content/pull/18629

2022-07-22 08:58 UTC, fred-wang commented on files/en-us/web/mathml/element/mstyle/index.md
>  ## Attributes
Article rewritten in https://github.com/mdn/content/pull/18639

2022-07-22 09:20 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +{{cssinfo}}
This one (and the compat/spec data) will hopefully be fixed by https://github.com/mdn/browser-compat-data/pull/17071

2022-07-22 09:22 UTC, fred-wang commented on files/en-us/web/css/math-depth/index.md
> +{{CSSSyntax}}
This does not work for math-style either. I've opened issue https://github.com/mdn/content/issues/18641

I think we can now forget about this PR, all the review comments have been addressed or moved to other places.