Fix JavaScript Reference Content
mdn/content pull request #17814
Opened 2022-06-30 12:27 UTC by awxiaoxian2020

Fixes #17789 .

I copy the original html and use `h2m` for conversion.

2022-06-30 12:42 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +The **`values()`** method returns a new `Array Iterator` object that contains the values for each index in the array.
Should either be `_array iterator_` or ``array `Iterator` ``. I'm not sure if it's specifically referring to any kind of array iterator.

2022-06-30 13:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +| {{SpecName('ESDraft', '#sec-%typedarray%.prototype.values', '%TypedArray%.prototype.values()')}} |
```suggestion
{{Specifications}}
```

2022-06-30 13:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +}
```suggestion
const arr = new Uint8Array([10, 20, 30, 40, 50]);
const values = arr.values();
for (const n of values) {
  console.log(n);
}
```

2022-06-30 13:07 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +var eArr = arr.values();
```suggestion
const arr = new Uint8Array([10, 20, 30, 40, 50]);
const values = arr.values();
```

Don't apply this directly; need to change the content below accordingly as well.

2022-06-30 14:44 UTC, awxiaoxian2020 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +var eArr = arr.values();
Done. Please have a review @Josh-Cena

2022-07-01 02:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +The **`values()`** method returns a new `Array Iterator` object that contains the values for each index in the array.
I was mainly saying that `Array Iterator` should be avoided because any inline code should refer to text you would actually write in your own code, but `Array Iterator` is not a valid JavaScript segment. Maybe just removing the backticks here is fine.

2022-07-02 07:55 UTC, teoli2003 requested changes

2022-07-02 07:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +console.log(values.next().value); // 50
Are you sure this is correct? I get this in Firefox Nightly:
![Capture d’écran 2022-07-02 à 09 49 14](https://user-images.githubusercontent.com/1466293/176991857-cf6b8c27-eed6-4f8d-951f-d75066be101e.png)

2022-07-02 07:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> -browser-compat: javascript.builtins.TypedArray.values
We need to keep the browser-compat key or both the _Specifications_ and _Browser compatibility_ sections will be broken.

2022-07-02 07:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +The **`values()`** method returns a new `Array Iterator` object that contains the values for each index in the array.
This way:
```suggestion
The **`values()`** method returns a new _array iterator_ object that contains the values for each index in the array.
```

2022-07-02 07:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +A new **`Array Iterator`** object.
The original was correct. No bold is needed (uses italics if you want to stress a text) and no backticks as this is not real code (that can be cut & pasted)
```suggestion
A new _array iterator_ object.
```

2022-07-02 07:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> -- [Polyfill of `TypedArray.prototype.values` in `core-js`](https://github.com/zloirock/core-js#ecmascript-typed-arrays)
Why remove this link?

2022-07-02 08:01 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +console.log(values.next().value); // 50
The behavior is good in Chrome stable.

2022-07-02 08:20 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/values/index.md
> +console.log(values.next().value); // 50
That was it, thanks!

![Capture d’écran 2022-07-02 à 10 20 10](https://user-images.githubusercontent.com/1466293/176992840-7086c524-a082-42e3-80e9-294ea53d0282.png)

2022-07-03 06:54 UTC, teoli2003 approved these changes
👍

2022-07-03 06:54 UTC, merged