Updated Syntax
mdn/content pull request #17820
Opened 2022-06-30 17:24 UTC by PrajwalBorkar

#### Summary

Replaced var with const or let as appropriate & updated spreadsheet as some files containing Var were missing in the list.
#### Motivation

#### Supporting details

#### Related issues

Resolving #16662 
#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-01 07:36 UTC, teoli2003 requested changes
In addition, we should remove Request.* and Response.* files from this PR. Both are part of the Fetch API and examples are extracted from the files at https://github.com/mdn/fetch-examples. This means for them we have to use the _vertical approach_ described by @wbamberg [there](https://github.com/orgs/mdn/discussions/143#discussioncomment-3049373). We need to update the examples there to match modern JS as described in this [discussion](https://github.com/orgs/mdn/discussions/143) and then retrofit the results into the different relevant pages on MDN (at least `Request.*` and `Response.*`). To do so efficiently, we will need a separate, self-contained, PR both here and on the other repository.

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/range/collapse/index.md
>  referenceNode = document.getElementsByTagName("div").item(0);
Not used before so:
```suggestion
const referenceNode = document.getElementsByTagName("div").item(0);
```

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/range/compareboundarypoints/index.md
> +let compare;
```suggestion
```

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/range/compareboundarypoints/index.md
>  range = document.createRange();
```suggestion
const range = document.createRange();
```

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/range/compareboundarypoints/index.md
>  sourceRange = document.createRange();
```suggestion
const sourceRange = document.createRange();
```

Please add a `const`on line 63 too.

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/range/intersectsnode/index.md
> +const bool = range.intersectsNode(document.getElementsByTagName("p").item(0));
I don't like `bool` as a variable name:
```suggestion
const intersectingNode = range.intersectsNode(document.getElementsByTagName("p").item(0));
```

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/request/headers/index.md
>  myHeaders.append('Content-Type', 'image/jpeg');
```suggestion
headers.append('Content-Type', 'image/jpeg');
```

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
You can't use `const` here (it is not a `for...of`):
```suggestion
  for (let i=0; i < resources.length; i++) {
```

(If you prefer you can update the loop to be a `for...of`, we will have to do it at some point anyway)

2022-07-01 07:36 UTC, teoli2003 commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < list.length; i++) {
You can't use `const` here (it is not a `for...of`):
```suggestion
  for (let i=0; i < list.length; i++) {
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/readablestream/cancel/index.md
> +  const bytesReceived = 0;
```suggestion
  let bytesReceived = 0;
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/readablestream/cancel/index.md
> +  const buffer = '';
```suggestion
  let buffer = '';
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/readablestream/cancel/index.md
> +  const matchFoundAt = -1;
```suggestion
  let matchFoundAt = -1;
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/request/headers/index.md
>  myContentType = myRequest.headers.get('Content-Type'); // returns 'image/jpeg'
```suggestion
const myContentType = myRequest.headers.get('Content-Type'); // returns 'image/jpeg'
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
```suggestion
  for (let i=0; i < resources.length; i++) {
```
or we can use `for...of` here

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < list.length; i++) {
```suggestion
  for (let i=0; i < list.length; i++) {
```

2022-07-01 07:38 UTC, OnkarRuikar commented on files/en-us/web/api/response/arraybuffer/index.md
>    source = audioCtx.createBufferSource();
```suggestion
 const source = audioCtx.createBufferSource();
```

2022-07-01 08:02 UTC, PrajwalBorkar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
Can u write one for..of example so I can change in other files also?

2022-07-01 09:25 UTC, OnkarRuikar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
If you want you can convert to `for..of` later in separate PRs to keep this simple. @teoli2003 wdyt?

Regarding  "we should remove Request.* and Response.* files from this PR." suggested by teoli2003,  if you have trouble removing those files from the PR or rebasing the branch let us know. Committing original contents in a new commit will also work.

2022-07-01 09:30 UTC, PrajwalBorkar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
Yes, I didn't understand exactly that remove files from PR issue so I will not include them in this. Also for..of loop files are in previous merged PR also so it will be better to make a separate one for that.Thanks for suggestion :)

2022-07-01 09:59 UTC, teoli2003 commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
And yes, we can do the `for...of` thing at a later stage.

2022-07-01 10:10 UTC, PrajwalBorkar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
> > I didn't understand exactly that remove files from PR issue
> 
> He meant revert the changes in all `files/en-us/web/api/request/*` and `files/en-us/web/api/response/*` files. We'll merge this PR without them.
> 
> Then update the original source files first https://github.com/mdn/fetch-examples/blob/master/fetch-request/index.html in `mdn/fetch-examples` repo. Then submit a new PR to update corresponding code snippets in `mdn/content` repo.

Okay so should I manually revert the changes from request & response files or there is an easy way to do this?

2022-07-01 11:26 UTC, OnkarRuikar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
What tool are you using in your local dev? git, GitHub Desktop, VSCode?

If you know git then do:
```
git pull 

git log

# copy the commit no before your first commit into this `no-var` branch.
# git reset --soft <commit to reset to>
git reset --soft 4e4ec5dbe15ae4883201057aaab8833dd33b7a05

git status
# you'll see all the modified files as non staged

#revert all the unwanted files

git commit -S -am "Updates Syntax"

git push --force
```

If you are not comfortable with this then safest way is to paste original content back into those files and create a new commit.

2022-07-01 11:32 UTC, PrajwalBorkar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
Reverted changes please review.

2022-07-01 11:35 UTC, PrajwalBorkar commented on files/en-us/web/api/resource_timing_api/using_the_resource_timing_api/index.md
> +  for (const i=0; i < resources.length; i++) {
Now I have to open PR by updating this [file](https://github.com/mdn/fetch-examples/blob/master/fetch-request/index.html) right?

2022-07-01 14:21 UTC, OnkarRuikar commented on files/en-us/web/api/response/status/index.md
> +var---
```suggestion
---
```

2022-07-01 15:32 UTC, PrajwalBorkar commented
> Then submit a new PR to update corresponding code snippets in `mdn/content` repo.

What changes to do in this PR?

2022-07-02 10:29 UTC, teoli2003 commented
We need to remove the changes to `Response.*` and `Request.*` from this PR.
All changes to fetch-related interfaces should be in a separate PR so that we can check that mdn/fetch-examples code is in sync with them.

2022-07-03 06:50 UTC, PrajwalBorkar commented
> We need to remove the changes to `Response.*` and `Request.*` from this PR. All changes to fetch-related interfaces should be in a separate PR so that we can check that mdn/fetch-examples code is in sync with them.

To clarify my doubt I have to make just a separate new PR which contains the chnages that I reverted from this PR.

2022-07-04 16:01 UTC, teoli2003 commented
> To clarify my doubt I have to make just a separate new PR which contains the changes that I reverted from this PR. Other than this do I need to check anything in fetch/example code?

Mostly.
Also when we use snippets from mdn/fetch-examples, we should update them so that they match what is there. I created a PR, and we got it merged earlier today, so mdn/fetch-examples is in a good shape and we wont't copy the snippet ten times)

2022-07-04 16:55 UTC, PrajwalBorkar commented
> So to land this PR, we still need to revert the changes in two files.

I have already reverted the changes of request and response files from this and made a new PR. Any other changes required?

2022-07-05 12:10 UTC, teoli2003 approved these changes
Let's merge this then.

2022-07-05 12:11 UTC, merged