deleted var
mdn/content pull request #17855
Opened 2022-07-01 10:13 UTC by gullapalli9482

#### Summary

#### Motivation

#### Supporting details

#### Related issues

Resolves issue #16662 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-01 10:24 UTC, teoli2003 approved these changes
👍

2022-07-02 06:03 UTC, AnilSeervi reviewed
There are still places* where you can use `const`

Suggested changes*

2022-07-02 06:03 UTC, AnilSeervi commented on files/en-us/web/api/performanceresourcetiming/redirectstart/index.md
>        var value = perfEntry[properties[i]];
```suggestion
      const value = perfEntry[properties[i]];
```

2022-07-02 06:03 UTC, AnilSeervi commented on files/en-us/web/api/performanceresourcetiming/redirectend/index.md
>        var value = perfEntry[properties[i]];
```suggestion
      const value = perfEntry[properties[i]];
```

2022-07-02 06:03 UTC, AnilSeervi commented on files/en-us/web/api/performanceresourcetiming/connectend/index.md
>        var value = perfEntry[properties[i]];
```suggestion
      const value = perfEntry[properties[i]];
```

2022-07-02 06:55 UTC, teoli2003 requested changes

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/connectend/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/connectstart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/fetchstart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/redirectend/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/redirectstart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/requeststart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/responseend/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/responsestart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/secureconnectionstart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 06:55 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/workerstart/index.md
>      if (supported) {
`supported` is used only there. I find this easier to read:
```suggestion
    if (properties[i] in perfEntry) {
```

2022-07-02 13:25 UTC, teoli2003 approved these changes
Thank you!

2022-07-02 13:25 UTC, merged