Fix width measurement
mdn/content pull request #17886
Opened 2022-07-02 10:22 UTC by SuperKenVery

> positive numbers indicating a distance going left from the given alignment point

Therefore, we should directly add `textMetrics.actualBoundingBoxRight` and `textMetrics.actualBoundingBoxLeft`. When the text is partly out of the left boundary, textMetrics.actualBoundingBoxLeft is positive. When the text doesn't touch the left boundary, the value is negative. 

When the text doesn't touch the left boundary, the original algorithm will report wrong answer. (Although I don't know if there will be a situation like this, but I think making it always right is better.)

#### Summary

Fix width measurement
#### Motivation

The original one might report wrong answer. 
#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-02 10:26 UTC, teoli2003 commented
What if one or two of the values are negative?

2022-07-03 08:38 UTC, Josh-Cena commented
From the description—`actualBoundingBoxRight` is the right offset from the alignment point; `actualBoundingBoxLeft` is going to the left. If the box is going across the alignment point, both metrics are positive. And I don't think they can both be negative.

2022-07-06 01:33 UTC, SuperKenVery commented
> What if one or two of the values are negative?

When one of the values is negative ---- that's exactly what I'm trying to handle, and the original code (I think) failed to handle. 

@Josh-Cena When both are positive, the original algorithm **does** provide a correct answer. What I'm trying to deal with is when one of them is negative.

2022-07-06 06:25 UTC, teoli2003 requested changes

2022-07-06 06:40 UTC, Josh-Cena commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
This is not a Euclidean space, though. `actualBoundingBoxLeft` is positive to the _left_ of the aligning point, while `actualBoundingBoxRight` is positive to the _right_.

<img width="400" src="https://user-images.githubusercontent.com/55398995/177485353-ef4691d6-e22d-47ab-a04b-fa28b4184450.jpeg" />

2022-07-06 06:41 UTC, Josh-Cena commented
> When both are positive, the original algorithm **does** provide a correct answer. What I'm trying to deal with is when one of them is negative.

Yes, I was saying that your code _provides_ the right answer, because the signs of the two bounds are actually opposite 😄

2022-07-06 06:43 UTC, teoli2003 commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
So we have to take the opposite of BoxLeft if I follow your sketch:
```suggestion
console.log(Math.abs(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft));
```

2022-07-06 06:46 UTC, teoli2003 commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
I'll bet that the `Math.abs()` was originally there but removed by somebody believing both values were always positive.

2022-07-06 06:46 UTC, Josh-Cena commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
Aye, that looks correct.

2022-07-06 08:02 UTC, SuperKenVery commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
Right! :tada:  These are exactly what I went through 4 days ago :smile: 

Although, as @Josh-Cena pointed out, I don't think `textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft` could be negative either, for that would mean the `right boundary` is on the left of the `left boundary`. 

Therefore, I think my code is still correct. I don't think the `Math.abs()` is needed. 

>I'll bet that the Math.abs() was originally there but removed by somebody believing both values were always positive.

Well... There were **originally** 2 `Math.abs()`s, which is in my deletion. And then there was my code, without any intermediate version by someone else. I didn't actually get what you mean :thinking: 

BTW why is :tada: named tada...

2022-07-06 08:17 UTC, teoli2003 commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
> Well... There were **originally** 2 `Math.abs()`s, which is in my deletion. And then there was my code, without any intermediate version by someone else. I didn't actually get what you mean 🤔
I mean before the original 2 `Math.abs()`. This was more of a rhetorical comment.

2022-07-06 08:24 UTC, SuperKenVery commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
@teoli2003  So are our explanations acceptable? If so, I'll resolve this conversation. 

@Josh-Cena 
你的意思就是说它是拟声词？我觉得`party-popper`就很好理解嘛。


跑题的快乐哈哈哈哈哈 :tada:

2022-07-06 08:30 UTC, Josh-Cena commented on files/en-us/web/api/textmetrics/index.md
> +console.log(textMetrics.actualBoundingBoxRight + textMetrics.actualBoundingBoxLeft);
> 你的意思就是说它是拟声词？

More like interjection like "hey!" or "oops", but yeah, that's the idea.

2022-07-06 08:45 UTC, teoli2003 approved these changes
I think this is indeed good to go. @Josh-Cena, if you agree, can you merge this?

2022-07-06 08:48 UTC, Josh-Cena approved these changes
LGTM

2022-07-06 08:48 UTC, merged