Add `const` var declaration to FileSystemFileHandle sample code
mdn/content pull request #17930
Opened 2022-07-03 19:21 UTC by ZhangYiJiang

#### Summary

Add `const` variable declaration in sample code

#### Motivation

This prevents the variable from leaking from the function scope 

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-04 05:08 UTC, Josh-Cena commented on files/en-us/web/api/filesystemfilehandle/index.md
>    const fileData = await fileHandle.getFile();
Should we return this, or at least add a comment below that we are supposed to use this? Currently this is unused.

2022-07-05 12:24 UTC, teoli2003 commented on files/en-us/web/api/filesystemfilehandle/index.md
>    const fileData = await fileHandle.getFile();
Yes, we should return something. What about:
```suggestion
  return await fileHandle.getFile();
```

2022-07-05 12:25 UTC, teoli2003 requested changes
In addition to the return value, should we put the definition of `pickerOpts` inside the function?

2022-07-18 05:36 UTC, teoli2003 approved these changes
👍

2022-07-18 05:36 UTC, merged