Add "chrome_update"
mdn/content pull request #17992
Opened 2022-07-05 17:00 UTC by bershanskiy

#### Summary

Chromium-based browsers call `"browser_update"` a different name, `"chrome_update"`.

#### Motivation

#### Supporting details

[Chrome docs](https://developer.chrome.com/docs/extensions/reference/runtime/#type-OnInstalledReason)
Chromium source code:
 - [out/Debug/gen/extensions/common/api/runtime.cc](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/extensions/common/api/runtime.cc;l=272;drc=da646affa40e760be86f075dd5f0e7a0b7ebc766;bpv=1;bpt=1)
 - [out/Debug/gen/extensions/common/api/runtime.cc](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/extensions/common/api/runtime.cc;l=289;drc=da646affa40e760be86f075dd5f0e7a0b7ebc766;bpv=1;bpt=1)
#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-05 17:08 UTC, bershanskiy commented
The main motivation behind this change is that readers (e.g., me) don't look at hidden `notes` in BCD tables and get confused.

2022-07-05 21:41 UTC, rebloor requested changes

2022-07-05 21:41 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/oninstalledreason/index.md
> +- `"browser_update"` or `"chrome_update"`
For clarity I would suggest:
```suggestion
- `"browser_update"` or, for Chrome, `"chrome_update"`
```

2022-07-10 22:58 UTC, rebloor approved these changes
Thanks

2022-07-10 22:58 UTC, merged