Update definition and add an example
mdn/content pull request #18015
Opened 2022-07-06 04:33 UTC by galopyz

#### Summary

I have clarified the definition of literal notation and constructor of RegExp and added an example. I have also shortened some paragraphs regarding the usage of RegExp. 

#### Motivation

Fixing an Issue with RegExp literal notation parameter explanation #17641, which had a misleading definition regarding regular expression literal notation and constructor. Using terms such as "do not use quotations" is misleading and confusing to the reader because it has nothing to do with syntax. 

#### Supporting details

#### Related issues

Fixes  #17641

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-06 08:41 UTC, teoli2003 requested changes

2022-07-06 08:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +- **The constructor function** takes either a string or a `RegExp` Object as first parameter and a string of optional flags as second parameter.
```suggestion
- The _literal notation_ takes a pattern between two slashes, followed by optional flags, after the second slash.
- The _constructor function_ takes either a string or a `RegExp` object as its first parameter and a string of optional flags as its second parameter. 
```

2022-07-06 08:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +The literal notation results in compilation of the regular expression when the expression is evaluated. On the other hand, the constructor of the `RegExp` object, `new RegExp('ab+c')`, results in run
_runtine compilation_ is likely unclear for people needing this explanation. We should either define it or link to a (glossary) entries explaining the different kinds of compilation.

2022-07-06 08:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Use a string as the first argument to the RegExp constructor when you want to [build the regular expression from dynamic input](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Building_a_r
```suggestion
Use a string as the first argument to the `RegExp()` constructor when you want to [build the regular expression from dynamic input](#Building_a_regular_expression_from_dynamic_inputs).
```

2022-07-06 08:41 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +order.match(new RegExp('\\b(' + breakfasts.join('|') + ')\\b', 'g'));
Maybe using a literal template, though it may be complicated with regular expressions. (It may be a good extra example 😈 )

2022-07-06 08:43 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +The literal notation results in compilation of the regular expression when the expression is evaluated. On the other hand, the constructor of the `RegExp` object, `new RegExp('ab+c')`, results in run
We should add a paragraph explaining that RegExps are _compiled_ at all.

2022-07-06 13:25 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +order.match(new RegExp('\\b(' + breakfasts.join('|') + ')\\b', 'g'));
Thank you for the great tips. So should I add a literal template version right before the constructor one?

2022-07-06 14:40 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +order.match(new RegExp('\\b(' + breakfasts.join('|') + ')\\b', 'g'));
Yeah, looks good (I won't have strong motivations to refactor it to the latter myself, but [my linter](https://eslint.org/docs/latest/rules/prefer-template) will :P)

2022-07-06 15:13 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +The literal notation results in compilation of the regular expression when the expression is evaluated. On the other hand, the constructor of the `RegExp` object, `new RegExp('ab+c')`, results in run
How about I add this paragraph with a [source](https://www.gnu.org/software/libc/manual/html_node/POSIX-Regexp-Compilation.html)?
 "Before you can actually match a regular expression, you must compile it. This is not true compilation—it produces a special data structure, not machine instructions. But it is like ordinary compilation in that its purpose is to enable you to “execute” the pattern fast."

2022-07-06 17:45 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +The literal notation results in compilation of the regular expression when the expression is evaluated. On the other hand, the constructor of the `RegExp` object, `new RegExp('ab+c')`, results in run
Instead of using a source, I added a paragraph regarding why regular expressions are compiled.

2022-07-06 18:08 UTC, galopyz commented
I have added changes to RegExp constructor as well.

2022-07-06 18:10 UTC, galopyz reviewed
Make edits to improve the article.

2022-07-06 18:15 UTC, galopyz commented
This is my first time doing changes, so please be patient with me.

I have reviewed all the changes by adding suggestions to batch. Does this mean I have to make a commit again with those changes? Or do those changes automatically affect right before the merge? 
Thank you.

2022-07-06 18:25 UTC, Josh-Cena commented
The commit has got into the branch; it's all good now. 


You're doing a great job so far, so don't worry!

2022-07-06 18:44 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
I am not too sure. But I got it from https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions and https://www.gnu.org/software/libc/manual/html_node/POSIX-Regexp-Compilation.html. They both say about efficiency. But let me know if these are not good sources.

2022-07-07 00:44 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
```suggestion
Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. More about the process can be found [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/compilation-and-reuse-in-regular-expressions) and [here](https://www.gnu.org/software/libc/manual/html_node/POSIX-Regexp-Compilation.html) There are two ways to compile and get a `RegExp` object. 
```

2022-07-07 00:48 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
I have added some links where any reader can find more information regarding the process. I think these provide great information, but if there is any problem, I can try to find resources from other places as well.

2022-07-07 01:31 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
I will avoid using link texts like "here"—"can be found in the dotnet docs or libc docs" is better.

Are there JS runtime-related sources? For example, I also found this inspiring: https://v8.dev/blog/regexp-tier-up. I also know that JSC uses JSCRE and V8 uses Irregexp as the RegExp engine, which may have some relevant sources.

(Of course, these are not blockers of the PR, just for my own curiosity...)

2022-07-07 02:25 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
Thank you. I have added your source as well. 

I am not very familiar with how Javascript works under the hood, yet. I just started learning less than 6 months ago. 

However, if you or anybody else has any other helpful resource to dig into, I am happy to put it here.

2022-07-07 02:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
> [V8 docs](https://v8.dev/blog/regexp-tier-up)

That's more of a supplementary material and not documentation—don't worry too much. Let's only keep the dotnet link since that seems the most relevant.

2022-07-07 03:23 UTC, galopyz commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +Before regular expressions can be used, they have to be compiled. This process allows them to perform matches more efficiently. There are two ways to compile and get a `RegExp` object.
Sounds great.

2022-07-07 03:28 UTC, Josh-Cena approved these changes
I think this is good enough as-is. Not sure if we want the content duplicated in two places, though.

2022-07-07 07:17 UTC, teoli2003 approved these changes
LGTM!

2022-07-07 07:17 UTC, merged