deleted var
mdn/content pull request #18042
Opened 2022-07-06 13:49 UTC by Abhiram-Gullapalli

#### Summary

#### Motivation

#### Supporting details

#### Related issues

Resolves issue #16662 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-06 13:50 UTC, Abhiram-Gullapalli commented
I'll be adding more commits to this pull request. Please do not merge it until then @teoli2003.

2022-07-06 14:03 UTC, teoli2003 approved these changes
👍

2022-07-06 14:06 UTC, teoli2003 commented
> I'll be adding more commits to this pull request. Please do not merge it until then @teoli2003.
In these cases, mark it as "draft pull request" when you create it.
![Capture d’écran 2022-07-06 à 16 05 33](https://user-images.githubusercontent.com/1466293/177569265-5d44dce5-bcd7-4a2f-a62b-6b4c622e9c99.png)
That way, no risk of an error.

Please re-request review when this one is ready.

2022-07-06 14:11 UTC, Abhiram-Gullapalli commented
sure

2022-07-07 05:36 UTC, teoli2003 requested changes

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/serviceworkerglobalscope/notificationclick_event/index.md
> +      const client = clientList[i];
That was correct, but this is a use case for `for...of`:
```suggestion
    for (const client of clientList) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/serviceworkerglobalscope/notificationclick_event/index.md
> +      const client = clientList[i];
```suggestion
    for (const client of clientList) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/sharedworkerglobalscope/connect_event/index.md
> +      cosnt workerResult = 'Result: ' + (e.data[0] * e.data[1]);
```suggestion
      const workerResult = 'Result: ' + (e.data[0] * e.data[1]);
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/sourcebufferlist/index.md
> +  const sourceBuffer = sourceBufferList[i];
```suggestion
for (const sourceBuffer of sourceBufferList) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesis/index.md
> +cosnt pitch = document.querySelector('#pitch');
```suggestion
const voiceSelect = document.querySelector('select');
const pitch = document.querySelector('#pitch');
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesis/index.md
> +let voices = [];
```suggestion
const voices = [];
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesis/voiceschanged_event/index.md
>    for(i = 0; i < voices.length ; i++) {
```suggestion
  for(let i = 0; i < voices.length ; i++) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesis/voiceschanged_event/index.md
>    for(i = 0; i < voices.length ; i++) {
```suggestion
  for(let i = 0; i < voices.length ; i++) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesiserrorevent/error/index.md
>    for(i = 0; i < voices.length ; i++) {
```suggestion
  for(let i = 0; i < voices.length ; i++) {
```

2022-07-07 05:36 UTC, teoli2003 commented on files/en-us/web/api/speechsynthesiserrorevent/index.md
>    for(i = 0; i < voices.length ; i++) {
```suggestion
  for(let i = 0; i < voices.length ; i++) {
```

2022-07-07 15:35 UTC, teoli2003 approved these changes
👍

2022-07-07 15:35 UTC, merged