var -> const
mdn/content pull request #18080
Opened 2022-07-07 16:17 UTC by Josh-Cena

#### Summary

Part of #16614

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-07 17:03 UTC, teoli2003 requested changes
One error, and one question and we are good to merge this.

2022-07-07 17:03 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/break/index.md
> +    if (i === 3) {
Should we add a second part using an arrow function? Or is the `function` expression clear enough?

(and use some randomly generated value instead of the 3)

2022-07-08 03:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/break/index.md
> +    if (i === 3) {
I think the function expression is clear enough, and the point here is more about syntax than about semantics so the `3` is fine to me as well.

2022-07-08 04:23 UTC, teoli2003 approved these changes
Thank you!

2022-07-08 04:23 UTC, merged