fix: syntax errors in JS example sections
mdn/content pull request #18186
Opened 2022-07-10 15:58 UTC by lionralfs

#### Summary
Hey everyone!

I've come across [this](https://github.com/orgs/mdn/discussions/143) modernization effort for JS code samples and decided to test the feasibility of using ESLint to automate some of the work. However, I've quickly noticed that around 500 code samples in the `files/en-us/web/api/` directory contain syntax errors (ESLint reports parsing errors). I then started to fix some of them, which is the state of this PR. Before proceeding to fix the remaining errors I wanted to ask for some maintainer input on whether this is worth pursuing.

I've purposely not commited my ESLint setup, but if you want to try it for yourself, this is how I did it:

1. `npm install --save-dev eslint eslint-plugin-markdown`
2. Modify `.eslintrc.js`:
```js
module.exports = {
  extends: [
    // "plugin:json/recommended"
    "plugin:markdown/recommended",
  ],
  parserOptions: {
    ecmaVersion: "latest",
    // allows top-level await among other things
    sourceType: "module",
  },
  env: {
    es6: true,
    browser: true,
    node: true,
  },
};
```
3. `npx eslint "files/en-us/web/api/**/*.md"`

Obviously this is not a perfect setup but it already highlights some existing issues with the code samples.

This PR…

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-10 16:07 UTC, Josh-Cena commented
Ahhh, I'm also looking into `eslint-plugin-markdown`. Glad someone is on the same page! Yes, please do go ahead—these PRs are easy to review so just keep it at around ~50 files changed. (It would be a problem if we have 100 syntax errors in our code...)

2022-07-10 16:33 UTC, lionralfs commented
So you would prefer PRs in batches of 50 changed files? I've just checked and ~380 files have at least one syntax (parsing) error.

2022-07-10 16:36 UTC, Josh-Cena commented
Ah, let's spread them across 4 PRs then—about 100 lines of diff per page would be the best.

2022-07-10 16:45 UTC, teoli2003 approved these changes

2022-07-10 16:47 UTC, lionralfs commented
Just FYI: I'm planning to add a few more fixes to this PR before I open a new one

2022-07-10 16:47 UTC, teoli2003 commented
Yes, our idea is to have a linter running periodically (or automatically, we'll see). For this to work, we need to run it once (like you do), find the errors, and fix them.

Then we can run it weekly, and the weekly PR will be small enough to be reviewed quickly.

2022-07-10 16:48 UTC, teoli2003 commented
> Just FYI: I'm planning to add a few more fixes to this PR before I open a new one

You are welcome.

2022-07-10 17:29 UTC, lionralfs commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
Not necessarily a syntax fix but this stops the parser from complaining since `delete` is an operator.

2022-07-10 17:34 UTC, Josh-Cena commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
Yep—we do the same for `generator.return()`. See also https://github.com/orgs/mdn/discussions/149

2022-07-10 17:36 UTC, lionralfs commented
Some things I'm noticing:

- Sometimes, the language mode is set incorrectly (html/js). For pseudocode, I've removed it completely
- Some variable names are problematic in certain contexts, for example: the parser doesn't like [default](https://github.com/mdn/content/blob/82457a4f638e415ef4aa91ebdfe0d003d6a0b54a/files/en-us/web/api/window/prompt/index.md?plain=1#L26) in ESM contexts. Probably relevant for further work (see comment above regarding automated linting)

2022-07-10 17:40 UTC, teoli2003 commented on files/en-us/web/api/window/open/index.md
>  <script type="text/javascript">
I think we should keep it `js` and remove the `<script>` element (3 times in this file)

2022-07-10 17:44 UTC, Josh-Cena commented
> Some variable names are problematic in certain contexts, for example: the parser doesn't like default in ESM contexts. 

We should rename those variables.

2022-07-10 17:47 UTC, lionralfs commented on files/en-us/web/api/window/open/index.md
>  <script type="text/javascript">
As those code blocks still include html, would you use a `js` code block followed by a `html` one?

2022-07-10 17:52 UTC, teoli2003 commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
No, we don't update these. We will change the type from `js` to `jssyntax` very soon. Meanwhile, we should ignore this one.

2022-07-10 17:54 UTC, teoli2003 commented on files/en-us/web/api/window/open/index.md
>  <script type="text/javascript">
Yes, please.

2022-07-10 17:54 UTC, Josh-Cena commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
Ugh... Maybe until we reach a resolution for https://github.com/orgs/mdn/discussions/148...

2022-07-10 17:59 UTC, teoli2003 commented
> > Some variable names are problematic in certain contexts, for example: the parser doesn't like default in ESM contexts.
> 
> We should rename those variables.

Yes, variables (or pseudo-variables in syntax sections) that have problematic names should be replaced: people often cut and past these, and then modify (actually declaring the variable with the same name, etc.)

2022-07-10 17:59 UTC, teoli2003 requested changes
(See comments above)

2022-07-10 19:08 UTC, lionralfs commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
I'm not sure whether you agreed on this change or want me to revert it. I'd appreciate an update

2022-07-10 19:38 UTC, teoli2003 commented on files/en-us/web/api/xranchor/delete/index.md
> +anchor.delete()
> Ugh... Maybe until we reach a resolution for https://github.com/orgs/mdn/discussions/148...

Yes, let's keep the original until this discussion is done (and the syntax section in the meta-docs).

2022-07-10 19:42 UTC, teoli2003 approved these changes
Thanks a lot. I'm really happy with the idea to use ESLint to find and fix syntax errors.

2022-07-10 19:42 UTC, merged

2022-07-17 06:58 UTC, OnkarRuikar commented
> I've purposely not commited my ESLint setup..

@lionralfs it would be great if you commit just the setup(no .md files) on a feature branch in your fork and share with us.

We need to have discussion about which [rules to disable](https://eslint.org/docs/latest/rules/). For example, we need to disable `no-undef`, `no-console`, `no-alert` etc.(this will save us from annotating hundreds of code blocks to disable the rules individually).
The idea is when we'll reach zero .md files flagged in content(after fixing them) then we can commit the ESLint setup along with our agreed config file.

2022-07-17 07:01 UTC, Josh-Cena commented
We'll start by fixing syntax errors so that ESLint can work at all—and then negotiating with the parser about what to parse and what to report. For example I still strongly believe

````md
```js
const a = 1;
// OR
const a = 2;
```
````

Is strictly better than two code blocks or using two identifiers, just to make the parser happy. Making this work probably requires tweaking the parser a bit.

2022-07-17 07:05 UTC, Josh-Cena commented
Oh btw, I think we can have `parserOptions` and `env` right now in the main branch's config—just not the plugins and rules sections. When I'm writing random test scripts I often come across ESLint parser errors like "class is a reserved word" because the parser is malconfigured.

2022-07-17 10:06 UTC, lionralfs commented
I've pushed my ESLint setup to my fork: [lionralfs:eslint-config](https://github.com/lionralfs/content/tree/eslint-config)
This also includes an `.eslintignore` file which I've been using to skip over certain .md files with more complicated syntax errors.
I've been documenting what I've skipped in various comments/PR description and will most likely compile them into a single list when I'm done with the remaining errors (which should only be 1 more PR).

2022-07-17 11:45 UTC, lionralfs commented
Ok so here we go. PR #18442 is the fifth and last (for now) PR to fix syntax/parsing errors.

As promised, I'll document all encountered issues that I've skipped here:

<details><summary>List of remaining syntax/parsing errors<summary>
<p>

- [`delete()`](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/xranchor/delete/index.md?plain=1#L22)
  - see comments from PR (#18186)
- ["chunked" code](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webvr_api/using_the_webvr_api/index.md)
  - The code sections/examples on this page are written in a specific way where a large block of code is intertwined with text paragraphs, obviously syntax-breaking
  - This is not the only page where examples are written like this, I'll refer to this style of writing as "chunked" from now on
- [glsl?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webglrenderingcontext/texparameter/index.md?plain=1#L23-L26)
  - See comment in this PR
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md?plain=1#L152-L156)
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/lighting_in_webgl/index.md?plain=1#L97-L102)
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/creating_3d_objects_using_webgl/index.md?plain=1#L142-L146)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/textures_from_code/index.md?plain=1#L87-L89)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/scissor_animation/index.md?plain=1#L62-L64)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/raining_rectangles/index.md?plain=1#L62-L64)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/hello_vertex_attributes/index.md?plain=1#L77-L79)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/hello_glsl/index.md?plain=1#L75-L77)
- ["chunked" code](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/web_speech_api/using_the_web_speech_api/index.md?plain=1#L289-L320)
- ["code diff"](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/web_crypto_api/non-cryptographic_uses_of_subtle_crypto/index.md?plain=1#L101-L104)
- [loose `catch` blocks all throughout this file](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/web_audio_api/web_audio_spatialization_basics/index.md)
- ["chunked" code](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/web_audio_api/visualizations_with_web_audio_api/index.md)
- [method without surrounding class](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/web_audio_api/using_audioworklet/index.md?plain=1#L243-L260)
  - multiple times in this file
- ["chunked" code](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/web_audio_api/simple_synth/index.md?plain=1#L225-L337)
- [method without surrounding class](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/usbdevice/opened/index.md?plain=1#L36-L52)
- [`delete(name)`](https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/urlsearchparams/delete/index.md?plain=1#L24)
- [loose `catch` block](https://github.com/mdn/content/blob/229c5118ecd20b83cae1ed4a23095b79d4ad17ec/files/en-us/web/api/transformstreamdefaultcontroller/error/index.md?plain=1#L36-L40)
- [delete(property)](https://github.com/mdn/content/blob/229c5118ecd20b83cae1ed4a23095b79d4ad17ec/files/en-us/web/api/stylepropertymap/delete/index.md?plain=1#L24)
- ["chunked" code](https://github.com/mdn/content/blob/574eca928f91ca13a749087b0d5f0f79891bf49b/files/en-us/web/api/streams_api/using_readable_streams/index.md?plain=1#L120-L147)
- [methods outside of class](https://github.com/mdn/content/blob/574eca928f91ca13a749087b0d5f0f79891bf49b/files/en-us/web/api/shadowroot/index.md?plain=1#L70-L80)
- [`{{deprecated_inline}}` inside code block](https://github.com/mdn/content/blob/574eca928f91ca13a749087b0d5f0f79891bf49b/files/en-us/web/api/rtcpeerconnection/getstats/index.md?plain=1#L72)
- ["raw" objects](https://github.com/mdn/content/blob/f9dab96c26a54f0e908a84386d2d0c210275e5cd/files/en-us/web/api/readablestreambyobreader/read/index.md?plain=1#L52-L70)
  - These result in `Parsing error: Unexpected token :`
- [method outside of class](https://github.com/mdn/content/blob/c20472c75b68a2fff9e3c50d2473280082d10a0c/files/en-us/web/api/readablebytestreamcontroller/error/index.md?plain=1#L51-L53)
- [`class` as arg name](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/paintworklet/registerpaint/index.md?plain=1#L28)
- [`return` outside of function](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/mediastream_image_capture_api/index.md?plain=1#L40-L48)
- ["raw" objects](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/mediadevices/getusermedia/index.md?plain=1#L96-L195)
  - These result in `Parsing error: Unexpected token :`
- ["chunked" code](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/media_streams_api/taking_still_photos/index.md?plain=1#L63-L176)
- ["chunked" code](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/indexeddb_api/checking_when_a_deadline_is_due/index.md?plain=1#L39-L219)
- [`delete(key)`](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/idbobjectstore/delete/index.md?plain=1#L31)
- [`delete()`](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/idbcursor/delete/index.md?plain=1#L33)
- [`continue()`](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/idbcursor/continue/index.md?plain=1#L27-L30)
- [`delete(name)`](https://github.com/mdn/content/blob/ba3e4381c62930da17634376fb1e33b5cae3e55c/files/en-us/web/api/headers/delete/index.md?plain=1#L31)
- [`delete(name)`](https://github.com/mdn/content/blob/ba3e4381c62930da17634376fb1e33b5cae3e55c/files/en-us/web/api/formdata/delete/index.md?plain=1#L21-L23)
- [`delete(font)`](https://github.com/mdn/content/blob/ba3e4381c62930da17634376fb1e33b5cae3e55c/files/en-us/web/api/fontfaceset/delete/index.md?plain=1#L19-L21)
- [method outside of class](https://github.com/mdn/content/blob/5ca7492d11f2fdc9ec850c990b24b624c0bd4ac6/files/en-us/web/api/elementinternals/states/index.md?plain=1#L25-L35)
- [`with` in strict mode](https://github.com/mdn/content/blob/93b5961fdb979339430649f6b5e4982404077fb9/files/en-us/web/api/element/replacewith/index.md?plain=1#L64-L66)
- [`with` in strict mode](https://github.com/mdn/content/blob/93b5961fdb979339430649f6b5e4982404077fb9/files/en-us/web/api/element/remove/index.md?plain=1#L51-L53)
- [`with` in strict mode](https://github.com/mdn/content/blob/93b5961fdb979339430649f6b5e4982404077fb9/files/en-us/web/api/element/prepend/index.md?plain=1#L86-L88)
- [`with` in strict mode](https://github.com/mdn/content/blob/93b5961fdb979339430649f6b5e498 [...]