Replaced hasOwnProperty with hasOwn
mdn/content pull request #18190
Opened 2022-07-10 20:16 UTC by maurer2

#### Summary
Hello, I replaced `hasOwnProperty` with `hasOwn` as suggested here https://github.com/orgs/mdn/discussions/143 (number 6)

#### Motivation
Improves legibility of code samples.

#### Supporting details
Discussion: https://github.com/orgs/mdn/discussions/143

This PR…
- [ ] Rewrites (or significantly expands) a document

2022-07-11 05:50 UTC, teoli2003 commented
Thanks a lot! Your PR is very valuable.

Before doing a formal review, thanks to your PR, I raised a question [there](https://github.com/orgs/mdn/discussions/143#discussioncomment-3118634). I think there is an extra pattern we should fix at the same time.

Once it is settled, we'll move forward with this PR.

2022-07-11 17:32 UTC, zloirock commented on files/en-us/web/javascript/reference/statements/var/index.md
> +Object.hasOwn(globalThis, 'x') // true
Missed `;` that's present in all the rest code of the example.

2022-07-12 07:37 UTC, teoli2003 requested changes
This looks good. I think there is one case where we can simplify further and get rid of `hasOwnProperty`/`hasOwn`, and simplify even more!

2022-07-12 20:01 UTC, maurer2 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md
>            for (let k in jobs) {
Okay, make sense. Thanks. I implemented the change.

2022-07-13 04:55 UTC, teoli2003 approved these changes
👍

2022-07-13 05:22 UTC, merged