fix: syntax errors in JS example sections (v2)
mdn/content pull request #18191
Opened 2022-07-10 20:29 UTC by lionralfs

#### Summary
Followup PR to #18186 

This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-10 20:33 UTC, lionralfs commented on files/en-us/web/api/webxr_device_api/startup_and_shutdown/index.md
>  ```
Not sure if this is the best way to highlight what the example is trying to illustrate

2022-07-10 20:56 UTC, rubiesonthesky commented on files/en-us/web/api/webxr_device_api/startup_and_shutdown/index.md
>  ```
Would it make more sense to use descriptive variable names here? For example:

`const xr1` -> `const nativeXr`
`const xr2` -> `const polyfilledXr`
`const xr3` -> `const xr`

2022-07-11 01:35 UTC, Josh-Cena commented on files/en-us/web/api/webxr_device_api/startup_and_shutdown/index.md
>  ```
Agreed

2022-07-11 01:36 UTC, Josh-Cena commented on files/en-us/web/api/webxr_device_api/performance/index.md
> +const vertexList = "...";
This is turning "obviously incorrect" code into "less obviously incorrect" code. This entire page seems incomplete—not sure what to do about it.

2022-07-11 05:09 UTC, teoli2003 commented on files/en-us/web/api/web_speech_api/using_the_web_speech_api/index.md
> +const colors = [ 'aqua' , 'azure' , 'beige', 'bisque', 'black', 'blue', 'brown', 'chocolate', 'coral' /* ... */ ];
Or (I don't have strong feelings):
```suggestion
const colors = [ 'aqua' , 'azure' , 'beige', 'bisque', 'black', 'blue', 'brown', 'chocolate', 'coral' /* , ... */ ];
```

2022-07-11 05:14 UTC, teoli2003 commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
```suggestion
```js
```

2022-07-11 05:15 UTC, teoli2003 commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
> +```glsl
Same here. We should remove the types: `vec4`, and `float` (twice)

2022-07-11 05:22 UTC, teoli2003 commented on files/en-us/web/api/webglactiveinfo/index.md
> +```glsl
This sounds like WebIDL: let's remove the whole block, it doesn't bring anything.

2022-07-11 05:22 UTC, teoli2003 commented on files/en-us/web/api/webglrenderingcontext/texparameter/index.md
>  texParameteri(target, GLenum pname, GLint param)
```suggestion
```js
texParameterf(target,  pname,  param)
```

(It will be a `jssyntax` in the future, as soon as the PR allowing it in Prism lands.

2022-07-11 05:22 UTC, teoli2003 commented on files/en-us/web/api/webxr_device_api/performance/index.md
> +    let vertexList = "...";
If it is a list. I think it should be:
```suggestion
    let vertexList = [/* ... */];
```

2022-07-11 05:22 UTC, teoli2003 commented on files/en-us/web/api/webxr_device_api/performance/index.md
> +const vertexList = "...";
```suggestion
const vertexList = [/*...*/];
```
?

2022-07-11 15:55 UTC, lionralfs commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
> +```glsl
This feels wrong since it's still not JavaScript but removing the types makes it "valid" JavaScript and prevents the parser from complaining.

2022-07-11 15:57 UTC, lionralfs commented on files/en-us/web/api/url_pattern_api/index.md
> +```
This was full of the following error:

`Identifier 'pattern' has already been declared`

My proposed solution is to split up the fenced code blocks

2022-07-11 15:59 UTC, lionralfs commented on files/en-us/web/api/url_pattern_api/index.md
> +  new RegExp('[\\(\\)]'); // ok
The only change in this file that is semantically different from the rest. In my opinion the example still conveys it's point without declaring variables.

2022-07-11 16:00 UTC, lionralfs commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +new URLPattern(pattern, /* (optional) */ baseURL);
Open to alternative suggestions

2022-07-11 16:02 UTC, Josh-Cena commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +new URLPattern(pattern, /* (optional) */ baseURL);
We can split it into `new URLPattern(pattern)` and `new URLPattern(pattern, baseURL)`, as we do for other optional parameters. But in general don't worry too much about Syntax code blocks.

2022-07-11 16:40 UTC, lionralfs commented
I'll use this comment to document some of the errors/intricacies I've come across but skipped for now:

- [delete()](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/xranchor/delete/index.md?plain=1#L22)
  - see comments from previous PR (#18186)
- ["chunked" code](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webvr_api/using_the_webvr_api/index.md)
  - The code sections/examples on this page are written in a specific way where a large block of code is intertwined with text paragraphs, obviously syntax-breaking
  - This is not the only page where examples are written like this, I'll refer to this style of writing as "chunked" from now on
- [glsl?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webglrenderingcontext/texparameter/index.md?plain=1#L23-L26)
  - See comment in this PR
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md?plain=1#L152-L156)
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/lighting_in_webgl/index.md?plain=1#L97-L102)
- [return outside of function](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/tutorial/creating_3d_objects_using_webgl/index.md?plain=1#L142-L146)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/textures_from_code/index.md?plain=1#L87-L89)
- [js hidden?](https://github.com/mdn/content/blob/876997a9908e3013b1ca460d3228cf8f9fa50205/files/en-us/web/api/webgl_api/by_example/scissor_animation/index.md?plain=1#L62-L64)

2022-07-11 16:56 UTC, teoli2003 commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
> +```glsl
If it is not JS, we shouldn't tag it as JavaScript. I think plain triple-ticks would be enough (I don't think there is glsl Prisme syntax highlighter)

2022-07-11 16:57 UTC, teoli2003 commented on files/en-us/web/api/url_pattern_api/index.md
> +```
Agreed!

2022-07-11 16:59 UTC, teoli2003 commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +new URLPattern(pattern, /* (optional) */ baseURL);
This is what we do in syntax boxes. BNF-structures like the brackets were not understood by developers when we asked them.

```suggestion
new URLPattern(pattern);
new URLPattern(pattern, baseURL);
```

2022-07-11 17:01 UTC, teoli2003 commented on files/en-us/web/api/usbendpoint/index.md
> +  const alternate = alternates[0];
I think you called it `alternatives` at line 67 but `alternates` at line 69… Shouldn't they be the same name?

2022-07-11 17:01 UTC, lionralfs commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
> +```glsl
glsl is being used [here](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_model_view_projection) for syntax highlighting

source: https://github.com/mdn/content/blob/0294e8ed09353dda85fadb4d261ee7f8b12eb4d5/files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md?plain=1#L128-L136

2022-07-11 17:02 UTC, lionralfs commented on files/en-us/web/api/usbendpoint/index.md
> +  const alternate = alternates[0];
Good catch

2022-07-12 01:14 UTC, Josh-Cena commented
@teoli2003 It would be an issue, but we can (a) disable the linter on that block (b) split it (c) tell the linter to re-parse at `// OR` and similar comments. The (c) probably means forking the linter and doing our own magic, but that's not unacceptable (I've done something similar since I've played with Markdown infrastructure quite a lot).

RE: `glsl`, my stance is we should give the code block a language whenever we can. Prism itself does have glsl highlighting—whether Yari includes that bundle is another problem.

2022-07-12 05:16 UTC, teoli2003 commented
If Prism has it, we should add it and update Yari to use it (There is a list of languages it "loads").

2022-07-12 05:19 UTC, Josh-Cena commented
For sure. I have yet to see a non-obscure language that Prism doesn't have a component for...

2022-07-12 09:20 UTC, teoli2003 requested changes

2022-07-12 09:20 UTC, teoli2003 commented on files/en-us/web/api/url_pattern_api/index.md
> +  new RegExp('[\\(\\)]'); // ok
I think we should keep the `const var`: this is js and should be highlighted as such, but it isn't a fully fledge JS extract. We may need to find a way to distinguish between a snippet, a whole example, a simple list of independent js lines, … to apply different linting rules, but I'm not convinced we can do this now, or even how we want to do this.

We always should privilege readers and usability over purity for our toolchain.

2022-07-12 09:20 UTC, teoli2003 commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +```
I would put `const pattern =`… in front of each case.

Or `const pattern1 =` and varying the 1.

2022-07-12 09:20 UTC, teoli2003 commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
We resolved to keep glsl.

2022-07-12 09:20 UTC, teoli2003 commented on files/en-us/web/api/webgl_api/webgl_model_view_projection/index.md
> +```glsl
We resolve to keep glsl.

2022-07-12 09:25 UTC, Josh-Cena commented on files/en-us/web/api/url_pattern_api/index.md
> +  new RegExp('[\\(\\)]'); // ok
We do in a lot of places remove the redundant `const var` part. e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atanh#using_math.atanh I don't think it sacrifices any readability—if anything it only makes the most important part stand out more. Also here we are demonstrating the constructor _itself_ throws so omission of `const var` is totally fine.

2022-07-12 10:12 UTC, B4L1T0 commented
Isi in pulsa daya dulu
6282179830489
Itu no contak ny

Dikirim dari iPhone saya

> Pada 12 Jul 2022, pukul 16.51, Jean-Yves Perrier ***@***.***> menulis:
> 
> ﻿
> So one comment left to address and this is good to go.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2022-07-12 17:54 UTC, lionralfs commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +```
The first one was already using `let pattern = ...` so I've adoped `let` and went with your suggestion of naming the variables `pattern[1..4]`

2022-07-12 19:21 UTC, teoli2003 approved these changes
👍 
Thanks a lot, we learned a lot thanks to this PR.

2022-07-12 19:25 UTC, merged