Intl.NumberFormat - flyby fixes
mdn/content pull request #18258
Opened 2022-07-12 04:56 UTC by hamishwillee

Minor fixes to [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) docs

2022-07-12 04:57 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +- `TypeError`
Seems to require start and end range - logically this would be expected: https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/proposed.html#sec-intl.numberformat.prototype.formatrangetoparts

2022-07-12 04:57 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +  - : Either `startRange` or `endRange` is undefined.
```suggestion
  - : Thrown when either `startRange` or `endRange` is undefined.
```

2022-07-12 04:58 UTC, teoli2003 requested changes, later dismissed
Thank you!

2022-07-12 04:58 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +- `TypeError`
I like to have a link here.
```suggestion
- {{jsxref("TypeError")}}
```

2022-07-12 05:29 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +- `TypeError`
Thanks! I'm going to change to draft until I've finished the first pass. Will move back later today when it is ready for review.

2022-07-12 06:06 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/resolvedoptions/index.md
> +The **`Intl.NumberFormat.prototype.resolvedOptions()`** method returns a new object with properties reflecting the [locale and number formatting options](/en-US/docs/Web/JavaScript/Reference/Global_O
FYI This is the main change to this doc - it adds a link to the **actual** formatting options (as well as the final object - which isn't all that interesting when you're wondering what the options it might return are)

2022-07-12 06:07 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/pluralrules/index.md
> +- {{jsxref("Intl/PluralRules/selectRange", "Intl.PluralRules.prototype.selectRange()")}} {{experimental_inline}}
Note, I'm querying this in https://github.com/mdn/browser-compat-data/pull/16923 - it _looks like_ having FF in preview "counts" as support, in which case this would no longer be experimental.

2022-07-12 09:14 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +The specific string formatting version supported is the ECMA-262 "StringNumericLiteral" grammar, which also allows non-base-10 numbers like hexadecimal and binary.
I think this should be in the "parameters" section. Also, in the [`BigInt` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt) page I went with the description "Strings are parsed as if they are source text for integer literals". We can do something similar here.

2022-07-12 09:18 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
Now that string formatting is in, maybe we can remove or de-emphasize this? Using BigInts just to preserve precision is really subpar compared to strings since decimals are tricky.

2022-07-12 09:22 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +Possible values for the `type` property include:
I don't have strong opinions, but should this be here or in "return value" section? Usually, even if the options are long, we put everything in "parameters", so for the sake of symmetry we should do it for return value as well.

2022-07-15 06:36 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
@Josh-Cena I'm not sure. The spec implies to me that they want to treat the strings as "pass through" formatting, and avoid having them used for any kind of calculation. To me that implies that if you are doing anything mathematical you probably still want to work with BigInts for now and the Decimal type when/if it makes it properly into the language.

Appreciate your thoughts on this.

2022-07-15 06:46 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
Ah—I was pointing to the case where you are using the literal, not doing any calculations. The example here is a literal. And yes, if you want to do _any_ calculations you'll still need BigInts.

2022-07-18 02:13 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +You can also pass through very large strings to be formatted as an arbitrary-precision decimal string (if you're _performing calculations) on the data you will still need to work with `BigInt`):
```suggestion
You can also pass through very large strings to be formatted as an arbitrary-precision decimal string (if you're _performing calculations on the data you will still need to work with `BigInt`):
```

2022-07-18 02:14 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +{{jsxref("Number")}} values in JavaScript suffer from loss of precision if they are too big or too small, making the text representation inaccurate.
@Josh-Cena UPdated this bit. What I've tried to do is make it clear that BigInt is needed for calculations - the fact that it does not lose precision is an "aside". Then go on to recommend strings for pass-through formatting.

Happy to take alternatives as a suggestion.

2022-07-18 02:14 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +You can also pass through very large strings to be formatted as an arbitrary-precision decimal string (if you're _performing calculations on the data you will still need to work with `BigInt`):
```suggestion
You can also pass through very large strings to be formatted as an arbitrary-precision decimal string (if you're performing calculations on the data you will still need to work with `BigInt`):
```

2022-07-18 02:16 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
Two separate code blocks should be seen as standalone, so we can use `const numberFormat = ...` in both.

2022-07-18 02:16 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +This allows, among other things, the general syntax for decimal strings `#.#E#`, and non-base-10 numbers like hexadecimal and binary.
```suggestion
Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "StringNumericLiteral" grammar).
These support, among other things, the general syntax for decimal strings `#.#E#`, and non-base-10 numbers like hexadecimal and binary.
```

2022-07-18 02:17 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +{{jsxref("Number")}} values in JavaScript suffer from loss of precision if they are too big or too small, making the text representation inaccurate.
This looks good 👍

2022-07-18 02:18 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +- cannot include a numeric literal separator, such as an underscore ("_").
```suggestion
- cannot include a numeric literal separator (`_`).
```

This is the only one.

2022-07-18 02:19 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "StringNumericLiteral" grammar).
```suggestion
Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "[StringNumericLiteral](https://tc39.es/ecma262/#prod-StringNumericLiteral)" grammar).
```

Since we are using spec terms anyway

2022-07-18 02:21 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "StringNumericLiteral" grammar).
@Josh-Cena I agree "parameters" is the right place for information on the string format. Given the differences with string conversion of a Number I've tried to capture
1. That you can use it for Exponent formats.
2. All those caveats you pointed to in the spec. 

I would prefer to be completely canonical  (e.g. we state support for "#.#E#" but that doesn't necessarily mean we support #e# say (exponentials) and many other mathematical symbols). This is a good start though because at least we have some of the differences.

I kept mention of ECMA-262 because this is not canonical - so someone might want to go to the spec.

2022-07-18 02:22 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "StringNumericLiteral" grammar).
I hate it, but you're right.

2022-07-18 02:28 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +Strings are parsed as _**string** numeric literals_ (as defined by the ECMA-262 "StringNumericLiteral" grammar).
Yeah, I think this is good enough—not many would need to dig into the corners of what it accepts.

2022-07-18 03:25 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
The problem is that in some cases you get people copy pasting this stuff into a browser window one after the other. I'll change though, because the approach is inconsistently applied, and while common in Learn is not seen often/ever in Reference.

2022-07-18 03:25 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +numberFormat = new Intl.NumberFormat("en-US");
```suggestion
let numberFormat = new Intl.NumberFormat("en-US");
```

2022-07-18 03:27 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +  In this case the value is converted to +0.
@Josh-Cena The spec actually says the value is a "0𝔽" - what's that - just "positive 0" for the purposes of formatting? Or to put it another way, is +0 OK here?

2022-07-18 03:28 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/pluralrules/index.md
> +- {{jsxref("Intl/PluralRules/selectRange", "Intl.PluralRules.prototype.selectRange()")}} {{experimental_inline}}
But I wouldn't block this for merging, as it is true until that BCD goes in, at which point I will revert this if needed

2022-07-18 03:31 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +```
Another day calling for redeclarations in Firefox console 😄

2022-07-18 03:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +  In this case the value is converted to +0.
Yep, +0 is OK. "𝔽" denotes a "number value" (i.e. IEEE 754), so it has the distinction between +0 and -0.

2022-07-18 05:11 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +Possible values for the `type` property include:
Yes we should. Done.

2022-07-18 06:07 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +        `"adlm"`, `"ahom"`, `"arab"`, `"arabext"`, `"bali"`, `"beng"`, `"bhks"`, `"brah"`, `"cakm"`,
FYI this page has lots of changes to move the " inside the code markup. This makes sense because it highlights what is entered (a string in most cases). Where a string is not entered (e.g. when the value is `false` say) then that is what is highlighted.

2022-07-18 06:08 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +        `"adlm"`, `"ahom"`, `"arab"`, `"arabext"`, `"bali"`, `"beng"`, `"bhks"`, `"brah"`, `"cakm"`,
Yes—I've fixed a lot of similar issues.

2022-07-18 06:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +let numberFormat = new Intl.NumberFormat("en-US");
```suggestion
const numberFormat = new Intl.NumberFormat("en-US");
```

2022-07-18 06:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +let numberFormat = new Intl.NumberFormat("en-US");
```suggestion
const numberFormat = new Intl.NumberFormat("en-US");
```

2022-07-18 06:10 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +        `"adlm"`, `"ahom"`, `"arab"`, `"arabext"`, `"bali"`, `"beng"`, `"bhks"`, `"brah"`, `"cakm"`,
Thanks @Josh-Cena . Perhaps a good time to merge this if you are OK with it. I'll do further updates as a PR on top.

2022-07-18 06:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +The code below shows how to format the roubles currency for a Russian locale:
(Can't comment on an unchanged line)

In the example below, the result is anglicized for some reason. The actual output should be `654 321,99 ₽`

2022-07-18 06:13 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +          `"dollar"`,
```suggestion
        - `"symbol"` to use a localized currency symbol such as € — this is the default value;
        - `"narrowSymbol"` to use a narrow format symbol ("$100" rather than "US$100");
        - `"code"` to use the ISO currency code;
        - `"name"` to use a localized currency name such as `"dollar"`.
```

2022-07-18 06:14 UTC, Josh-Cena approved these changes
Content-wise this looks good to me—I can see it addresses a few existing issues in the content so I won't block its merge, but I do have a few editorial suggestions (see random comments above).

2022-07-18 06:29 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/format/index.md
> +The code below shows how to format the roubles currency for a Russian locale:
Thanks. Fixed.

2022-07-18 06:30 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +          `"dollar"`,
I'm going to fix these with full stops or whatever everything else does for consistency.

2022-07-18 06:37 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/resolvedoptions/index.md
> +  - : The value provided for this properties in the `options` argument, if present, or the value requested using the Unicode extension key "`nu`" or filled in as a default.
Move quotes? (Same for below)

2022-07-18 06:37 UTC, hamishwillee commented
Thanks @Josh-Cena - random fixes have been updated. I want to tidy up some other bits, but best to do that after

2022-07-18 06:38 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/formatrangetoparts/index.md
> +  - : The object is the end part of the range
```suggestion
  - : The object is the end part of the range.
```

2022-07-18 06:38 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/resolvedoptions/index.md
> +  - : The value provided for this properties in the `options` argument, if present, or the value requested using the Unicode extension key "`nu`" or filled in as a default.
Yes
```suggestion
  - : The value provided for this properties in the `options` argument, if present, or the value requested using the Unicode extension key `"nu"` or filled in as a default.
```

2022-07-18 06:38 UTC, merged

2022-07-18 06:39 UTC, hamishwillee commented
@Josh-Cena Merged, to prevent you discovering any more issues :-). Don't worry, you'll get an opportunity to comment on the next lot too :-0

2022-07-18 06:44 UTC, Josh-Cena commented
Aw, no problem