Clarified XMLHttpRequestEventTarget.onerror usage
mdn/content pull request #1826
Opened 2021-01-27 21:26 UTC by ChaunceyHoover

Clarified that the event `onerror` is only called when _network_ level errors happen, not _application_ level. The verbiage could be confusing for people not familiar with how `onerror` works.

I think this is an important clarification that needs to be added since people who may be newer to JavaScript might see `onerror` and think that will be the event that gets called if their application receives a 4xx or 5xx status error code. I am embarrassed to say, but I spent longer than I care to admit before I knew this was the case. I would like to make sure nobody else has to go through a similar issue, which is why I proposed this edit.

https://stackoverflow.com/a/10584491 for credit to who clarified this for me.

2021-02-01 03:00 UTC, sideshowbarker requested changes

2021-02-14 20:22 UTC, ChaunceyHoover reviewed
Thank you for the correction. Your verbiage and grammar makes the sentence look better.

2021-02-15 07:57 UTC, sideshowbarker approved these changes

2021-02-15 07:58 UTC, merged

2021-02-15 07:59 UTC, sideshowbarker commented
Chauncey, Thanks much, and congrats on landing your first docs change here — welcome aboard 🎉