Deprecate MathML attributes scriptmize and scriptsizemultiplier
mdn/content pull request #18273
Opened 2022-07-12 13:27 UTC by fred-wang

#### Summary

Deprecate MathML attributes scriptmize and scriptsizemultiplier and document change in Firefox 103.

#### Motivation

These attributes have been removed from Firefox 103, not implemented in any other browsers and not part of MathML Core.

#### Supporting details

https://bugzilla.mozilla.org/show_bug.cgi?id=1772697
https://w3c.github.io/mathml-core/#style-change-mstyle

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x ] Fixes a typo, bug, or other error

2022-07-12 13:45 UTC, teoli2003 requested changes
(More of a question)

2022-07-12 13:45 UTC, teoli2003 commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
Shouldn't we have mdn/browser-compat-data for this?

It would be nice to add a _Specifications_ and a _Browser_compatibility_ page like we do for the rest of MDN.

2022-07-15 07:10 UTC, fred-wang commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
So it looks like https://github.com/mdn/browser-compat-data/blob/main/mathml/elements/mstyle.json has some data already, let's add the section

2022-07-15 07:14 UTC, fred-wang commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
mmh, and Specifications and a Browser_compatibility sections are already present above actually (try to show more context). These Gecko-specific notes are very long...

2022-07-15 07:21 UTC, teoli2003 commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
@queengooborg I think these notes (https://pr18273.content.dev.mdn.mozit.cloud/en-US/docs/Web/MathML/Element/mstyle#gecko-specific_notes ) should be in bcd. Any advice on how to format/list them?

2022-07-17 22:31 UTC, queengooborg commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
Yes, browser compatibility data should definitely be placed in BCD rather than on the pages itself.  There is a lot of information in these notes, some of which could be applied to existing subfeatures (`scriptminsize` and `scriptsizemultiplier`).  I think that some of these should be split into multiple statements with `partial_implementation` in BCD, for example the first note about lack of complete implementation before Firefox 6.

2022-07-19 18:59 UTC, fred-wang commented on files/en-us/web/mathml/element/mstyle/index.md
> +- Starting with Gecko 103.0 {{geckoRelease("103.0")}}, support for attributes `scriptsizemultiplier` and `scriptminsize` has been removed.
I removed the notes from MDN and open https://github.com/mdn/browser-compat-data/pull/17043 for BCD.

2022-07-21 18:10 UTC, teoli2003 approved these changes
👍

2022-07-21 18:10 UTC, merged