fix: syntax errors in JS example sections (v3)
mdn/content pull request #18307
Opened 2022-07-13 10:20 UTC by lionralfs

#### Summary

Followup to PR #18186 and #18191 

This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-13 10:24 UTC, lionralfs commented on files/en-us/web/api/svgrect/the__x__property/index.md
> +```go
This entire code block seems to be taken from svgo: https://github.com/ajstarks/svgo/blob/1546f124cd8b0cba8d505fa2ddb110c211670c59/svg.go#L317-L321

2022-07-16 10:49 UTC, lionralfs commented on files/en-us/web/api/trustedscripturl/index.md
> +console.log(sanitize); /* a TrustedScriptURL object */
Good catch, you're absolutely right. One backspace too much 😅

2022-07-16 11:30 UTC, lionralfs commented on files/en-us/web/api/serial/index.md
> +  const usbVendorId = 0xABCD;
Taken from this example block [in the WebUSB spec](https://wicg.github.io/webusb/#enumeration):

```js
device = await navigator.usb.requestDevice({ filters: [{
    vendorId: 0xABCD,
    classCode: 0xFF, // vendor-specific
    protocolCode: 0x01
}]});
```

2022-07-16 11:32 UTC, lionralfs commented on files/en-us/web/api/serialport/index.md
> +await port.open({ baudRate: 9600 /* pick your baud rate */ });
Pretty sure the example code was copied from [the spec](https://wicg.github.io/serial/#open-method)

I've taken the example value for the `baudRate` from the [web.dev](https://web.dev/serial/) explainer

2022-07-16 12:15 UTC, lionralfs commented on files/en-us/web/api/publickeycredential/index.md
> +  challenge: new Uint8Array([21, 31, 105 /* 29 more random bytes generated by the server */]),
Taken from the [spec example](https://w3c.github.io/webauthn/#sctn-sample-registration)

2022-07-16 12:52 UTC, teoli2003 requested changes
A few nits that I will commit soon. 

I find this really amazing: so many small errors fixed really quickly.

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/resizeobserver/resizeobserver/index.md
>        for (let entry of entries) {
nit
```suggestion
      for (const entry of entries) {
```

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.md
> +  .then(offer => pc.setLocalDescription(offer))
nit
```suggestion
  .then((offer) => pc.setLocalDescription(offer))
```

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.md
> +  .then(offer => pc.setLocalDescription(offer))
```suggestion
  .then((offer) => pc.setLocalDescription(offer))
```

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.md
>    .catch(err => {
nit
```suggestion
  .catch((err) => {
```

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/shadowroot/mode/index.md
> +  element2.shadowRoot.innerHTML("Opened shadow") // The shadow is open, we can access it from outside
While we are at it:
```suggestion
  element2.shadowRoot.textContent("Opened shadow") // The shadow is open, we can access it from outside
```

2022-07-16 12:52 UTC, teoli2003 commented on files/en-us/web/api/sourcebuffer/abort/index.md
>  sourceBuffer.addEventListener('updateend', function (_) {
The underscore is likely correct, but looked very weird to me.
```suggestion
sourceBuffer.addEventListener('updateend', function (ev) {
```

2022-07-16 12:53 UTC, teoli2003 approved these changes

2022-07-16 12:56 UTC, merged