Suggest proper pseudo-class for keyboard focus
mdn/content pull request #18321
Opened 2022-07-13 15:05 UTC by Groschenroman

The section [Focusable element must have focus styling](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard#focusable_element_must_have_focus_styling) speaks about keyboard focus but suggests the adapt the styles using the `:focus` pseudo class. This however would modify the UI not just for keyboard access but also for tap, click and other means of interaction. `:focus-visible` however can help making this very distinction and hence should be promoted here.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-19 22:41 UTC, estelle requested changes

2022-07-19 22:41 UTC, estelle commented on files/en-us/web/accessibility/understanding_wcag/keyboard/index.md
> +Any element that can receive keyboard focus should have visible styling that indicates when the element is focused. You can do this with the [`:focus-visible`](/en-US/docs/Web/CSS/:focus-visible) CSS
The original was correct. While you can information about ALSO including `:focus-visible`, we should not remove information about `:focus`.  Especially since we're not at 100% support for focus-visible yet.

2022-07-20 05:29 UTC, hidde commented on files/en-us/web/accessibility/understanding_wcag/keyboard/index.md
> +Any element that can receive keyboard focus should have visible styling that indicates when the element is focused. You can do this with the [`:focus-visible`](/en-US/docs/Web/CSS/:focus-visible) CSS
Agreed! Besides, there are also non keyboard users that benefit from focus styles. so recommending `:focus-visible` as a default would go too far.

2022-07-25 08:58 UTC, Groschenroman commented on files/en-us/web/accessibility/understanding_wcag/keyboard/index.md
> +Any element that can receive keyboard focus should have visible styling that indicates when the element is focused. You can do this with the [`:focus-visible`](/en-US/docs/Web/CSS/:focus-visible) CSS
Good idea. Adding it in addition serves both purposes then. Thank you!

2022-07-26 00:43 UTC, estelle approved these changes
thank you

2022-07-26 00:43 UTC, merged