ABBR: remove title
mdn/content pull request #18409
Opened 2022-07-16 06:20 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-16 21:04 UTC, estelle commented on files/en-us/web/html/element/abbr/index.md
> +When including an abbreviation or acronym, provide a full expansion of the term in plain text on first use, along with the `<abbr>` to mark up the abbreviation. This informs the user what the abbrevi
```suggestion
When including an abbreviation or acronym, provide a full expansion of the term in plain text on first use, along with the `<abbr>` to mark up the abbreviation. This informs the user what the abbreviation or acronym means. 
```

2022-07-16 21:05 UTC, estelle commented on files/en-us/web/html/element/abbr/index.md
> +- To define an abbreviation which may be unfamiliar to the reader, present the term using `<abbr>` and inline text providing the definition. Include a `title` attribute if the inline definition is no
```suggestion
- To define an abbreviation which may be unfamiliar to the reader, present the term using `<abbr>` and inline text providing the definition. Include a `title` attribute only when the inline expansion or definition is not available. 
```

2022-07-16 21:06 UTC, estelle commented on files/en-us/web/html/global_attributes/title/index.md
> +The `title` attribute may also be used to controls in [data tables](/en-US/docs/Web/HTML/Element/table).
```suggestion
The `title` attribute may also be used to label controls in [data tables](/en-US/docs/Web/HTML/Element/table). 
```

2022-07-17 06:28 UTC, teoli2003 requested changes
Thank you! A few nits and some questions!

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.md
> +If providing the expansion in addition to the abbreviation makes little sense, and the abbreviation or acronym is a fairly shortened term, provide the full expansion of the term as the value of  {{ht
```suggestion
If providing the expansion in addition to the abbreviation makes little sense, and the abbreviation or acronym is a fairly shortened term, provide the full expansion of the term as the value of {{htmlattrxref("title")}} attribute:
```

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.md
> +const htmlSolution = '<p><abbr>NASA</abbr>, the National Aeronautics and Space Administration, sure does some exciting work.</p>';
I'm curious, will screen readers read this as N – A – S – A or as Nasa?

If they do the first, how should we mark up our content to prevent this?

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/attributes/index.md
> +This page lists reference pages covering all the <abbr>WAI-ARIA</abbr> attributes discussed on <abbr>MDN</abbr>.
Strictly speaking, MDN is no more an abbreviation for Mozilla Developer Network, like IBM is no more an abbreviation for International Business Machines.

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/toolbar_role/index.md
> +[Toolbar example from <abbr>W3C</abbr>,  the World Wide Web Consortium](https://www.w3.org/TR/wai-aria-practices-1.2/examples/toolbar/toolbar.html)
```suggestion
[Toolbar example from <abbr>W3C</abbr>, the World Wide Web Consortium](https://www.w3.org/TR/wai-aria-practices-1.2/examples/toolbar/toolbar.html)
```

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/web/html/element/abbr/index.md
> +Some browsers add a dotted underline to the content of the element. Others add a dotted underline while converting the contents to small caps. Others, like Internet Explorer, do not style it differen
Let's not add mention to Internet Explorer, it is dead.
```suggestion
Some browsers add a dotted underline to the content of the element. Others add a dotted underline while converting the contents to small caps. Others may not style it differently than a {{HTMLElement("span")}} element. To control this styling, use {{cssxref('text-decoration')}} and {{cssxref('font-variant')}}. 
```

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/web/html/element/abbr/index.md
> +
```suggestion
```

2022-07-17 06:28 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/title/index.md
I think we should list the `<abbr>`case here, too.

2022-07-19 19:48 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/index.md
> +This page lists reference pages covering all the <abbr>WAI-ARIA</abbr> attributes discussed on <abbr>MDN</abbr>.
```suggestion
This page lists reference pages covering all the <abbr>WAI-ARIA</abbr> attributes discussed on MDN.
```

2022-07-19 21:00 UTC, teoli2003 approved these changes
👍

2022-07-19 21:00 UTC, merged