fix: syntax errors in JS example sections (v4)
mdn/content pull request #18424
Opened 2022-07-16 17:25 UTC by lionralfs

#### Summary

Followup to PR #18186, #18191 and #18307

Skipped issues:
- [`class` as arg name](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/paintworklet/registerpaint/index.md?plain=1#L28)
- [`return` outside of function](https://github.com/mdn/content/blob/037d908f7b56048898a3becb835dc3bfb9199700/files/en-us/web/api/mediastream_image_capture_api/index.md?plain=1#L40-L48)

This PR…
-->
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-16 17:38 UTC, lionralfs commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
>  });
Since the paragraph was already referring to a button click event, I've included it in the code, to avoid "`return` outside of function"

2022-07-16 17:39 UTC, lionralfs commented on files/en-us/web/api/navigator/getusermedia/index.md
>  }
Not sure about this

2022-07-16 17:41 UTC, lionralfs commented on files/en-us/web/api/ovr_multiview2/index.md
> +gl.drawElements(/* ... */);  // draw will be broadcasted to the layers of colorTex and depthStencilTex.
Could probably be optimized, but I don't know enough WebGL to know what to put here

2022-07-16 17:41 UTC, lionralfs commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +  let preAuthSuccess = true;
The [spec](https://www.w3.org/TR/payment-handler/#canmakepayment-example) is doing the same thing

2022-07-16 17:43 UTC, lionralfs commented on files/en-us/web/api/paymentresponse/retry/index.md
> +    while (validate(payResponse)) {
Not sure if this entire code block is even needed, as a more comprehensive example immediately follows it

2022-07-16 18:34 UTC, teoli2003 reviewed
Looks good, a few nits.

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/mediastreamtrack/mute_event/index.md
> +musicTrack.onunmute = event => {
While we are at it:
```suggestion
musicTrack.onunmute = (event) => {
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/mediastreamtrack/unmute_event/index.md
> +musicTrack.mute = event => {
```suggestion
musicTrack.mute = (event) => {
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/mediatracksupportedconstraints/logicalsurface/index.md
>    let supportedConstraints = navigator.mediaDevices.getSupportedConstraints();
```suggestion
  const supportedConstraints = navigator.mediaDevices.getSupportedConstraints();
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/mediatracksupportedconstraints/logicalsurface/index.md
>    let displayMediaOptions = {
```suggestion
  const displayMediaOptions = {
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/controller/index.md
No example, let's remove this.
```suggestion
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/controller/index.md
>  ```
```suggestion
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/mediagroup/index.md
```suggestion
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/htmlmediaelement/mediagroup/index.md
```suggestion
```

2022-07-16 18:34 UTC, teoli2003 commented on files/en-us/web/api/idbtransaction/commit/index.md
> +transaction.onerror = event => {
While we are editing this line:
```suggestion
transaction.onerror = (event) => {
```

2022-07-16 20:21 UTC, lionralfs commented on files/en-us/web/api/elementinternals/form/index.md
> +  #internals;
"Parsing error: Private field '#internals' must be declared in an enclosing class"
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

> It is a syntax error to refer to # names from out of scope. It is also a syntax error to refer to private fields that were not declared before they were called, or to attempt to remove declared fields with delete.

2022-07-16 20:25 UTC, lionralfs commented on files/en-us/web/api/history_api/example/index.md
>  const ajaxRequest = new (function () {
This is a larger refactoring:
- moving variable declarations to the top
- renaming variables to avoid Hungarian notation
- formatting via prettier

2022-07-16 20:49 UTC, teoli2003 requested changes
A few details, and I can't merge this tomorrow when I wake up 😄 

Well done! Our code examples are getting much better: better readability, better code&paste, … There still is a lot of work to do, but we are moving in the right direction. Thank you!

2022-07-16 20:49 UTC, teoli2003 commented on files/en-us/web/api/history_api/example/index.md
> +        );
```suggestion
    function filterURL(url, viewMode) {
        return (
            url.replace(searchRegex, "") +
            (
                "?" +
                url
                    .replace(hostRegex, "&")
                    .replace(viewRegex, viewMode ? "&" + viewKey + "=" + viewMode : "")
                    .slice(1)
            ).replace(endQstMarkRegex, "")
        );
```

2022-07-16 20:49 UTC, teoli2003 commented on files/en-us/web/api/history_api/example/index.md
> +        );
The original was ugly, and as there was some Hungarian notation left:
```suggestion
        for (const link of document.links) {
            link.onclick = processLink;
        );
```

2022-07-16 20:49 UTC, teoli2003 commented on files/en-us/web/api/history_api/example/index.md
> +        : (onload = init);
Ok, this is a trick for compatibility with very old IE versions, as they had `attachEvent` instead of `addEventListener`. Time to update it (Modern JS+Web platform code is so much more legible nowadays)

```suggestion
    window.addEventListener("load", init, false);
```

2022-07-16 21:12 UTC, lionralfs commented on files/en-us/web/api/history_api/example/index.md
> +        );
Whoops, good catch

2022-07-16 23:02 UTC, rubiesonthesky commented on files/en-us/web/api/msmanipulationevent/index.md
> +```
Isn't this Typescript? Same for next interface. I'm wondering should these be here as it's not really a example but just typing for this event.

2022-07-17 04:36 UTC, teoli2003 commented on files/en-us/web/api/navigator/getusermedia/index.md
>  }
I don't know if it really is JSON, but it surely looks like it. It will work for us.

2022-07-17 04:39 UTC, teoli2003 commented on files/en-us/web/api/msmanipulationevent/index.md
> +```
No, this is WebIDL, this is likely the only place this WebIDL is stored nowadays.

2022-07-17 04:41 UTC, teoli2003 approved these changes
👍

2022-07-17 04:41 UTC, merged