webRequest API blocked requests clarification
mdn/content pull request #18524
Opened 2022-07-19 18:38 UTC by rebloor

#### Summary
Adds a note about the details returned by `webRequest.onErrorOccurred` when Firefox Tracking Protection blocks a request. Provides the content requested in [Bug 1779770](https://bugzilla.mozilla.org/show_bug.cgi?id=1779770).

#### Metadata

This PR…
- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-15 21:05 UTC, mixedpuppy requested changes
I think that an additional place to document this is in the onErrorOccurred part (below flow image) on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

Maybe something like (last sentence added):

[onErrorOccurred](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onErrorOccurred) can be fired at any time during the request. Also, note that sometimes the sequence of events may differ from this: for example, in Firefox, on an [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) upgrade, the onBeforeRedirect event will be triggered immediately after onBeforeRequest.  onErrorOccurred will also be fired if Firefox Tracking Protection blocks a request.

2022-08-16 00:12 UTC, mixedpuppy approved these changes

2022-08-16 00:12 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/index.md
> +{{WebExtAPIRef("webRequest.onErrorOccurred", "onErrorOccurred")}} can fire at any time during the request. Also, note that sometimes the sequence of events may differ from this. For example, in Firef
Lets link Firefox Tracking Protection the same way it is later in this patch.

2022-08-16 02:04 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/index.md
> +{{WebExtAPIRef("webRequest.onErrorOccurred", "onErrorOccurred")}} can fire at any time during the request. Also, note that sometimes the sequence of events may differ from this. For example, in Firef
Done

2022-08-16 02:04 UTC, merged