Rewrite loose equality description
mdn/content pull request #18565
Opened 2022-07-21 01:34 UTC by Josh-Cena

#### Summary

#### Motivation

It is so hard to understand (which is understandable, since it's hell complicated). I hope this rewrite makes it clearer.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-21 05:18 UTC, teoli2003 requested changes
I think we should explicitly note that `NaN` != `NaN`. But else, looks good!

2022-07-21 05:18 UTC, teoli2003 commented on files/en-us/web/javascript/equality_comparisons_and_sameness/index.md
> +    - Number: return `true` only if both operands have the same value. `+0` and `-0` are treated as the same value. If either operand is `NaN`, return `false`.
```suggestion
    - Number: return `true` only if both operands have the same value. `+0` and `-0` are treated as the same value. If either operand is `NaN`, return `false`; so `NaN` is never equal to `NaN`.
```

2022-07-21 05:18 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/equality/index.md
> +    - Number: return `true` only if both operands have the same value. `+0` and `-0` are treated as the same value. If either operand is `NaN`, return `false`.
```suggestion
    - Number: return `true` only if both operands have the same value. `+0` and `-0` are treated as the same value. If either operand is `NaN`, return `false`; so, `NaN` is never equal to `NaN`.
```

2022-07-21 05:22 UTC, teoli2003 approved these changes
👍

2022-07-21 05:24 UTC, merged

2022-07-22 00:26 UTC, hamishwillee commented on files/en-us/web/javascript/equality_comparisons_and_sameness/index.md
> +    - Object: return `true` only if both operands reference the same object.
FYI, bullets all indented 1 too many. 3 indents in numbered list, 2 in bullet list.

2022-07-22 00:28 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/equality/index.md
> +The equality operators (`==` and `!=`) use the [`IsLooselyEqual` Abstract Operation](https://tc39.es/ecma262/#sec-islooselyequal) to compare two operands. This can be roughly summarized as follows:
"is roughly"

2022-07-22 00:31 UTC, hamishwillee commented
FWIW  A couple of comments "after the fact"

- this is so much better. Love it.
- I don't like links to the spec in the text, because these are movable. That's why we keep that stuff in the BCD 
- I would have liked to have seen a link to the terms falsy and truthy here somewhere. Perhaps I missed them.

2022-07-22 02:37 UTC, Josh-Cena commented
> I don't like links to the spec in the text, because these are movable

Actually, spec links are stable—even if they change the title, the anchor links will be "redirected". So I won't be particularly worried about that

> I would have liked to have seen a link to the terms falsy and truthy here somewhere

We didn't really mention falsy/truthy here: it would more be a topic in, say, `if...else`. I would probably elaborate on the equality reference page later, and I'll consider that.

2022-07-22 02:40 UTC, Josh-Cena commented on files/en-us/web/javascript/equality_comparisons_and_sameness/index.md
> +    - Object: return `true` only if both operands reference the same object.
Interesting, I see your point—I'll keep that in mind. I just hit tabs in my editor. Once we start using Prettier it should all be auto-formatted.

2022-07-22 04:06 UTC, teoli2003 commented on files/en-us/web/javascript/equality_comparisons_and_sameness/index.md
> +    - Object: return `true` only if both operands reference the same object.
The Daily Markdonwlint PR should detect and fix this.