Comment out ellipsis in code blocks
mdn/content pull request #18567
Opened 2022-07-21 02:34 UTC by OnkarRuikar

Ellipsis in markdown code blocks are syntax errors.

In order to have smooth transition to Prettier and ESLint the PR comments out such bare ellipses. Refer the https://github.com/mdn/content/pull/18171#issuecomment-1179670484 for more context.

2022-07-21 05:04 UTC, teoli2003 requested changes

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/functions/arrow_functions/index.md
> +obj.c(); // prints 10, Object { }
```suggestion
obj.b(); // prints undefined, Window { /* … */ } (or the global object)
obj.c(); // prints 10, Object { /* … */ }
```

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/functions/arrow_functions/index.md
> +    console.log(this.a, typeof this.a, this); // undefined 'undefined' Window { } (or the global object)
```suggestion
    console.log(this.a, typeof this.a, this); // undefined 'undefined' Window { /* … */ } (or the global object)
```

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/functions/get/index.md
> +    x: …, get x() { }
```suggestion
    x: /* … */, get x() { /* … */ }
```

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/functions/set/index.md
> +  `{ x: …, set x(v) { } }` are forbidden )
```suggestion
  `{ x: /* … */ , set x(v) { /* … */ } }` are forbidden )
```

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
> +    console.log(it, ' is not an iterable object…');
```suggestion
    console.error(`${it} is not an iterable object.');
```

2022-07-21 05:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
> +// 123 is not an iterable object…
```suggestion
// 123 is not an iterable object.
```

2022-07-21 05:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/functions/set/index.md
> +  `{ x: …, set x(v) { } }` are forbidden )
`/* … */` indicates optionalness, but here `…` means it _has to_ be substituted with a value

2022-07-21 05:14 UTC, Josh-Cena commented
@teoli2003 @OnkarRuikar Sorry I was not closely following this process before. I have a question about semantics.

The goal of this update is to make code blocks syntactically valid. However some changes don't really make the code any more valid. For example:

```diff
- const a = ...;
+ const a = /* … */;
```

Instead, I think it actually makes the point less clear. What about using `…` without enclosing it in comments in places where we deliberately indicate "omission" instead of "optional content"? For example, "this object will be logged in console as `{ … }` looks better than `{ /* … */ }`, because there's indeed no comments logged!

2022-07-21 05:19 UTC, Josh-Cena commented
(Also, I'm skeptical about replacing `...` with `…` in code blocks, though I don't have strong opinions. It doesn't read great with a monospace font.)

2022-07-21 05:19 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
> +    console.log(it, ' is not an iterable object…');
So let's keep it the original way?

2022-07-21 05:21 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
> +    console.log(it, ' is not an iterable object…');
Yeah

2022-07-22 14:02 UTC, OnkarRuikar commented
> const a = ...;

Are we going to lint inline code(e.g. \`const a = 9\` as well? 
* If no, then `const a = ...;` won't matter as long as it conveys the meaning.
* If yes, and for code blocks ```` ```js ````, what should be the replacement?

***

```diff
- console.log(foo); // { … }
+ console.log(foo); // { /* … */ }
```

I got these as review suggestions. You guys decide and, if needed, I'll correct it in all the pages.

2022-07-23 08:14 UTC, teoli2003 approved these changes

2022-07-23 08:14 UTC, merged