Minor JavaScript technologies overview rewrite
mdn/content pull request #18586
Opened 2022-07-21 12:21 UTC by Josh-Cena

#### Summary

#### Motivation

Fix some outdated content.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-22 00:33 UTC, hamishwillee commented on files/en-us/web/javascript/language_resources/index.md
> +**ECMAScript** is the scripting language that forms the basis of [JavaScript](/en-US/docs/Web/JavaScript). ECMAScript standardized by the [ECMA International](https://www.ecma-international.org/) sta
```suggestion
**ECMAScript** is the scripting language that forms the basis of [JavaScript](/en-US/docs/Web/JavaScript). ECMAScript is standardized by the [ECMA International](https://www.ecma-international.org/) standards organization in the **ECMA-262 and ECMA-402 specifications**.
```

2022-07-22 00:34 UTC, sideshowbarker approved these changes
LGTM, with copy edits and comments to consider

2022-07-22 00:34 UTC, sideshowbarker commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +Non-browser environments (like Node.js) often do not have DOM APIs because they don't interact with a document, but they still usually implement many web APIs, such as [`fetch()`](/en-US/docs/Web/API
```suggestion
Non-browser environments (like Node.js) often do not have DOM APIs — because they don't interact with a document — but they still usually implement many web APIs, such as [`fetch()`](/en-US/docs/Web/API/fetch) and [`setTimeout()`](/en-US/docs/Web/API/setTimeout).
```

2022-07-22 00:34 UTC, sideshowbarker commented on files/en-us/web/javascript/language_resources/index.md
> +**ECMAScript** is the scripting language that forms the basis of [JavaScript](/en-US/docs/Web/JavaScript). ECMAScript standardized by the [ECMA International](https://www.ecma-international.org/) sta
```suggestion
**ECMAScript** is the scripting language that forms the basis of [JavaScript](/en-US/docs/Web/JavaScript). ECMAScript is standardized by the [ECMA International](https://www.ecma-international.org/) standards organization in the **ECMA-262 and ECMA-402 specifications**.
```

2022-07-22 00:34 UTC, sideshowbarker commented on files/en-us/web/javascript/language_resources/index.md
> +The specifications are published on a yearly basis. The latest published version of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf) and
```suggestion
Snapshots of the specifications are published on a yearly basis. The current committee-approved snapshot of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf) and [HTML form](https://262.ecma-international.org/13.0/). ECMA-262 and ECMA-402 are continuously maintained and kept up to date by the specification editors; https://tc39.es/ecma262/ and https://tc39.es/ecma402/ host the latest, up-to-date versions.
```
I don’t feel strongly about the particular wording here — but I do feel that however it’s worded, it should be clear that https://tc39.es/ecma262/ and https://tc39.es/ecma402/ are in fact the latest versions of the spec, and that the ECMA-published versions are just snapshots (which are implicitly always out of date).

In other words, I think we want to try to make it clear to readers that they should be reading the https://tc39.es/ecma262/ and https://tc39.es/ecma402/ versions and really should not be reading the ECMA-published versions (because they otherwise might be missing a bug fix or typo fix, or some other refinement, etc., made to the spec/source after the current ECMA-approved version was published

Also, unless I’m missing something about the semantics of putting angle brackets around the tc39.es URLs, it doesn’t seem necessary…

2022-07-22 00:37 UTC, hamishwillee commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used in
These kinds of definitions leave me thinking - "are these really the same thing"? 

Either way:

```suggestion
The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used interchangeably, but "ECMAScript" is the term for the language standard.
```

2022-07-22 00:38 UTC, hamishwillee commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +- Built-in objects and functions ({{jsxref("JSON")}}, {{jsxref("Math")}}, [Array](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) methods, {{jsxref("parseInt")}}, {{jsxref("decodeURI")}},
```suggestion
- Built-in objects and functions, including: ({{jsxref("JSON")}}, {{jsxref("Math")}}, [Array](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) methods, {{jsxref("parseInt")}}, {{jsxref("decodeURI")}}, etc.)
```

2022-07-22 00:41 UTC, hamishwillee commented on files/en-us/web/javascript/language_resources/index.md
> +The specifications are published on a yearly basis. The latest published version of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf) and
Is there some kind of moving link we can use for this to stop it going out of date? Or some way we can grab BCD data for this?

2022-07-22 00:42 UTC, hamishwillee approved these changes
Looks great. I've added some comments. Not merging as @teoli2003 would probably be a better factual reviewer.

2022-07-22 02:43 UTC, Josh-Cena commented on files/en-us/web/javascript/language_resources/index.md
> +The specifications are published on a yearly basis. The latest published version of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf) and
That's also my worry. The PDF form is auto-updating, but I don't know any for the HTML form. I personally just read https://tc39.es/ecma262/.

2022-07-22 02:44 UTC, Josh-Cena commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used in
Actually, 20 years ago, they are probably not the same thing! (Considering things like JScript were still around as well) I don't know the full history here but I thought "today" makes it more rigorous.

2022-07-22 02:49 UTC, Josh-Cena commented on files/en-us/web/javascript/language_resources/index.md
> +The specifications are published on a yearly basis. The latest published version of ECMA-262 can be found in [PDF form](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf) and
I agree—this seems better.

> Also, unless I’m missing something about the semantics of putting angle brackets around the tc39.es URLs, it doesn’t seem necessary…

Some Markdown renderers render it as plain text unless you explicitly mark it as a link. Seems to not be the case for us.

2022-07-22 03:18 UTC, hamishwillee commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used in
20 years ago is the dark past. I'll leave it to you, but I would remove it. Actually, I'd even prefer this

```suggestion
The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used interchangeably.
```

2022-07-22 03:36 UTC, Josh-Cena commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used in
The stress is actually on the fact that "ECMAScript" is the standard while JavaScript is more colloquial. I've reworded it a bit.

2022-07-22 04:51 UTC, teoli2003 requested changes

2022-07-22 04:51 UTC, teoli2003 commented on files/en-us/web/javascript/language_resources/index.md
> +Below are the historical editions:
This whole table below was strange and still is.

Either we list all editions in date order (or reverse), or we get rid of it.

I'd say, we get rid of it: it doesn't bring much (Web devs don't really care about the ES version, only if they can use it or not, and violate the _timeless_ principle: if we don't maintain it, it becomes naturally outdated (what is current will stop been current).

2022-07-22 04:52 UTC, Josh-Cena commented on files/en-us/web/javascript/language_resources/index.md
> +Below are the historical editions:
Once we remove the table, this page will become too thin—shall we merge it with technologies overview?

2022-07-22 05:14 UTC, teoli2003 commented on files/en-us/web/javascript/language_resources/index.md
> +Below are the historical editions:
Yes, I think so.

2022-07-22 06:03 UTC, teoli2003 requested changes

2022-07-22 06:03 UTC, teoli2003 commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +https://esdiscuss.org/            | ECMAScript spec discussion; historical mailing-list archives (until March 2021)
```suggestion
- [ECMAScript Language Specification repo](https://github.com/tc39/ecma262)
- [ECMAScript Internationalization API Specification repo](https://github.com/tc39/ecma402)
- [ECMAScript proposals repo](https://github.com/tc39/proposals)
- [ECMAScript conformance test suite repo](https://github.com/tc39/test262)
- [TC39 meeting notes](https://github.com/tc39/notes)
- [ECMAScript spec discussion; current mailing list](https://es.discourse.group/)
- [ECMAScript spec discussion; historical mailing-list archives (until March 2021)](https://esdiscuss.org/)
```

2022-07-22 06:31 UTC, teoli2003 approved these changes
👍

2022-07-22 06:31 UTC, merged

2022-07-25 02:48 UTC, hamishwillee commented on files/en-us/web/javascript/javascript_technologies_overview/index.md
> +The core language of JavaScript is standardized by the ECMA TC39 committee as a language named [ECMAScript](/en-US/docs/Web/JavaScript/Language_Resources). ECMAScript and JavaScript are often used in
Thanks. Update works for me.