fix arrow-body-style (ESLint rule) violations
mdn/content pull request #18665
Opened 2022-07-22 20:05 UTC by lionralfs

#### Summary
Another modernization PR for embedded JS in `Web/API`. This was mainly automated with ESLint's `--fix` for the [`arrow-body-style`](https://eslint.org/docs/latest/rules/arrow-body-style) rule, using the 'as-needed' configuration option.

Surprisingly, these are the only problems in `Web/API`.

#### Motivation
See Nr. 4 here: https://github.com/orgs/mdn/discussions/143

> Use [implicit return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#function_body) (a.k.a. concise body) with arrow functions where possible. [ES6/2015]

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-22 20:06 UTC, lionralfs commented on files/en-us/web/api/readablestream/index.md
> +)
This hurts readability imo. Up for discussion

2022-07-22 20:07 UTC, lionralfs commented on files/en-us/web/api/web_locks_api/index.md
> +);
Same here

2022-07-22 22:38 UTC, lionralfs commented on files/en-us/web/api/readablestream/index.md
> +)
Whoops, that was me 😅 The parentheses should go around `stream` in line 86. Good catch

2022-07-23 04:48 UTC, teoli2003 requested changes
I'm partially convinced here.

I agree:
- `(param) =>` is always better than `param =>`
-  to omit `return` and the braces on one-liners (when possible), especially on chained `then()`. This is clearly more readable.

I'm not convinced that omitting the `return` in multiline cases improves legibility. In fact, I think this is the opposite.

I would happily approve this PR, without the multiline cases.

2022-07-23 06:19 UTC, Josh-Cena commented on files/en-us/web/api/web_locks_api/index.md
> +);
What about:

```js
navigator.locks.request(
  'my_resource',
  // Lock is acquired.
  (lock) => p,
  // Now lock will be held until either resolve() or reject() is called.
);
```

2022-07-23 06:20 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkerglobalscope/pushsubscriptionchange_event/index.md
>  }, false);
This is what Prettier says:

```js
self.addEventListener(
  "pushsubscriptionchange",
  (event) => {
    event.waitUntil(
      swRegistration.pushManager
        .subscribe(event.oldSubscription.options)
        .then((subscription) =>
          fetch("register", {
            method: "post",
            headers: {
              "Content-type": "application/json",
            },
            body: JSON.stringify({
              endpoint: subscription.endpoint,
            }),
          }),
        ),
    );
  },
  false,
);
```

2022-07-23 06:25 UTC, Josh-Cena commented on files/en-us/web/api/layoutshiftattribution/index.md
> +    );
@teoli2003 This is the one you are referring to, right? Because the other one (with `fetch`, commented above) seems fine to me.

2022-07-23 06:43 UTC, teoli2003 commented on files/en-us/web/api/web_locks_api/index.md
> +);
I prefer @Josh-Cena's version.

2022-07-23 06:47 UTC, teoli2003 commented on files/en-us/web/api/layoutshiftattribution/index.md
> +    );
Weird, I thought there were more. But yes, in this case, I would keep the original.

2022-07-23 07:10 UTC, Josh-Cena approved these changes
I shouldn't have mixed all the formatting work with this single ESLint fix... But I think this is good to go now. Running Prettier is going to be a huge task in the future.

2022-07-23 07:56 UTC, teoli2003 approved these changes

2022-07-23 07:56 UTC, teoli2003 commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +    console.log(`Error: ${error}`);
Drive-by fix:
```suggestion
    console.error(`Error: ${error}`);
```

2022-07-23 07:56 UTC, teoli2003 commented on files/en-us/web/api/scheduler/posttask/index.md
>    console.log('Feature: NOT Supported');
Drive-by:
```suggestion
  console.error('Feature: NOT Supported');
```

2022-07-23 08:01 UTC, merged