Avif 85
mdn/content pull request #1871
Opened 2021-01-29 05:04 UTC by hamishwillee

- Fix flaws in Image types doc (broken links, wrong macros, bad notecards)
- Change preference info to indicate AVIF supported by FF86

2021-01-29 05:24 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> +     <strong>Supported:</strong> Chrome, Opera, Firefox.</p>
FYI only, the preference is still mentioned below in the main section.

2021-01-29 05:26 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> +<h3 id="APNG_Animated_Portable_Network_Graphics"><a id="apng">APNG</a> (Animated Portable Network Graphics)</h3>
FYI all the ids here are set to lower case. This allows the `{{anch}}` macro everywhere else to still link to this page. I'm tempted to move the anchor above the heading, but this is minimum change just for everything to work.

2021-01-29 08:39 UTC, chrisdavidmills requested changes
Couple of small bits for you to consider here, otherwise fine!

2021-01-29 08:39 UTC, chrisdavidmills commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
This should be `{{domxref("HTMLImageElement.Image()")}}` so that the link text shows up correctly. Or in fact, the original one worked OK (not sure why, maybe it has a redirect on it?)

2021-01-29 08:39 UTC, chrisdavidmills commented on files/en-us/web/media/formats/image_types/index.html
> +   <td>Chrome 85, Opera 71, and Firefox 86 (From Firefox 77 to 85 requires the preference <code>image.avif.enable</code> set <code>true</code>).</td>
maybe "(Firefox 77 to 85 require..." or "(versions 77 to 85 require"? Wording seems a little odd here.

2021-02-01 00:35 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
@peterbe Here the flaw fixer automatically modified `{{domxref("Image()")}}` to `{{domxref("HTMLImageElement/Image")}}`. While the link works, it is not "as correct" as `{{domxref("HTMLImageElement.Image()")}}`, which also shows the right text for the item. Is this an error in the flaw tool? [i.e. do you want me to post an issue or is this already known]

2021-02-01 00:35 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> +   <td>Chrome 85, Opera 71, and Firefox 86 (From Firefox 77 to 85 requires the preference <code>image.avif.enable</code> set <code>true</code>).</td>
Yoiks. Yes. Fixed.

2021-02-01 00:38 UTC, hamishwillee commented
OK @chrisdavidmills. Fixed. Ready for your re-review :-)

2021-02-01 00:48 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
Actually maybe I'm wrong here and this was my error. No longer certain sorry.

2021-02-01 08:15 UTC, chrisdavidmills approved these changes
I'm happy with this now; cheers @hamishwillee

2021-02-01 08:35 UTC, merged

2021-02-02 15:35 UTC, peterbe commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
Yeah. We have an open bug about that. I actually have a PR draft to fix it. I'm struggling to finish the work because it's so sad that it has to be so weird.

2021-02-02 21:49 UTC, hamishwillee commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
@peterbe  FWIW Kudos for your persistence then. I know I whine about things that are missing in our tooling, but I LOVE the flaw checkers, and I think it's great how each time I use them something else gets easier.

2021-02-03 17:44 UTC, peterbe commented on files/en-us/web/media/formats/image_types/index.html
> + <li>The {{domxref("HTMLImageElement/Image")}} constructor and the {{domxref("HTMLImageElement")}} interface</li>
Now you've swooned me. I'll get https://github.com/mdn/yari/pull/2551 back onto my top priorities.