Better explanation of declaration vs. statement
mdn/content pull request #18724
Opened 2022-07-24 06:05 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #17860

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-24 06:56 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/statements/index.md
> +You can always transform a declaration to a statement by wrapping it in braces — this makes it part of a [block statement](/en-US/docs/Web/JavaScript/Reference/Statements/block).
`const a = 1;` still remains a deceleration we are not changing it. we just want to wrap it in a block.

```suggestion
To get around this, you can wrap the declaration in braces — this makes it part of a [block statement](/en-US/docs/Web/JavaScript/Reference/Statements/block).
```

2022-07-24 07:47 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/index.md
> +  var i = 0;
Even `var i;` would be correct? (If I understand correctly)

2022-07-24 07:47 UTC, teoli2003 requested changes

2022-07-24 07:47 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/const/index.md
> +Unlike `var`, `const` begins [_Declarations_, not _Statements_](/en-US/docs/Web/JavaScript/Reference/Statements#difference_between_statements_and_declarations). That means you cannot use a lone `cons
typo

```suggestion
Unlike `var`, `const` begins [_declarations_, not _dtatements_](/en-US/docs/Web/JavaScript/Reference/Statements#difference_between_statements_and_declarations). That means you cannot use a lone `const` declaration as the body of a block (which makes sense, since there's no way to access the variable).
```

2022-07-24 07:47 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/let/index.md
> +Unlike `var`, `let` begins [_Declarations_, not _Statements_](/en-US/docs/Web/JavaScript/Reference/Statements#difference_between_statements_and_declarations). That means you cannot use a lone `let` d
```suggestion
Unlike `var`, `let` begins [_declarations_, not _statements_](/en-US/docs/Web/JavaScript/Reference/Statements#difference_between_statements_and_declarations). That means you cannot use a lone `let` declaration as the body of a block (which makes sense, since there's no way to access the variable).
```

2022-07-24 07:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/index.md
> +  var i = 0;
Yeah

2022-07-24 07:51 UTC, Josh-Cena commented
At the time of writing upper-case `_Declaration_` is specifically referring to the non-terminal in the spec. But I guess no need for that level of detail now.

2022-07-24 09:00 UTC, OnkarRuikar commented
Just being curious...

We can call following a one line block as well:
```
{ let a =2; }
```

Is there a separate, easy to explain, word/term for one lines below if/else/while etc. :
```
let a;
if(true)
  a = 2;   // is there way to refer such blocks specifically? 'single-statement context'?


if(false)
  { a = 0; }  // I'm not talking about this one
```

2022-07-24 09:04 UTC, Josh-Cena commented
Yeah, the error uses the term "single-statement context" so I guess that's it. The `a = 2` in `if (true) a = 2` is definitely _not_ a block since a block is specifically for the brace-enclosed thing.

2022-07-25 01:13 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/index.md
> +Statements and declarations are technical terms used in the formal syntax of JavaScript — colloquially, we would sometimes use them interchangeably. However, there's a noticeable difference in their
Minimally: "The terms "statement" and "declaration" are ...."

To my taste (entirely up to you):

```suggestion
The terms "statement" and "declaration" have a precise meaning in the formal syntax of JavaScript that affects where they may be placed in code.
For example, in most control-flow structures, the body only accepts statements — such as the two arms of an [`if...else`](/en-US/docs/Web/JavaScript/Reference/Statements/if...else):
```

2022-08-02 17:13 UTC, Josh-Cena commented
@teoli2003 In case this fell off your radar—it's still waiting for a re-stamp

2022-08-03 06:55 UTC, teoli2003 approved these changes
LGTM

2022-08-03 06:55 UTC, merged