Mediacapture sidebar
mdn/content pull request #18760
Opened 2022-07-25 04:39 UTC by hamishwillee

This does two things.
1. BlobEvent is part of Media Recorder API, but was wrongly put in "Media Capture and Streams. This fixes up the BlobEvent and its parts. Also the sidebar
2. Replaces `{{APIRef("Media Capture and Streams")}}` in heaps of pages with `{{DefaultAPISidebar("Media Capture and Streams")}}`. I still don't really get the difference, but the second one "works".

2022-07-25 14:20 UTC, jpmedley requested changes

2022-07-25 14:20 UTC, jpmedley commented on files/en-us/web/api/blobevent/timecode/index.md
> +The **`timecode`** read only property of the {{domxref("BlobEvent")}} interface indicates the difference between the timestamp of the first chunk in data, and the timestamp of the first chunk in the
```suggestion
The **`timecode`** read only property of the {{domxref("BlobEvent")}} interface indicates the difference between the timestamp of the first chunk of data, and the timestamp of the first chunk in the first `BlobEvent` produced by this recorder.
```

2022-07-26 13:58 UTC, jpmedley approved these changes

2022-07-26 13:59 UTC, merged

2022-07-26 14:30 UTC, teoli2003 commented
>     2. Replaces `{{APIRef("Media Capture and Streams")}}` in heaps of pages with `{{DefaultAPISidebar("Media Capture and Streams")}}`. I still don't really get the difference, but the second one "works".

This is not correct, `{{DefaultAPISidebar}}` is for overview pages, `{{APIRef}}` for all the others. `{{APIRef}}` will list properties/methods of the current interface while `{{DefaultAPISidebar}}` only lists top level ones.

I dream of merging both, but we don't have the dev bandwidth to even dream of improving the sidebar situation in 2022.

2022-07-26 22:48 UTC, hamishwillee commented
@teoli2003 I can fix/revert this on Friday BUT the reason I did this was that {{APIRef}} did not display any sidebar locally for me in this case. I have just reverified that - you can test using https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia - since {{DefaultAPISidebar}} "worked" I assume it was the preferred macro - whoops.

Is APIRef populated from GroupData too? Or to put it another way, how does this work, so how can I fix it?

> I dream of merging both, but we don't have the dev bandwidth to even dream of improving the sidebar situation in 2022.

IMO our sidebar situation is a disgrace. We don't even get the basics right - re keeping the current context. But I've given up.

2022-07-27 06:13 UTC, teoli2003 commented
> IMO our sidebar situation is a disgrace. We don't even get the basics right - re keeping the current context. But I've given up.

Agreed, but we can't do anything for this: basic PRs are not even reviewed for weeks/months on the Yari side.

2022-07-27 06:14 UTC, teoli2003 commented
Yes, the problem was that there was no `GroupData.json` entry for _Media Recorder API_.

I'll happily review one (or do it if you don't have time).

2022-07-29 00:45 UTC, hamishwillee commented
@teoli2003 I don't think that is **the** problem since:
- getUserMedia is in {{APIRef("Media Capture and Streams")}} not  `Media Recorder API`. Actually it appears in both media capture and streams and also in the WebRTC.
- [BlobEvent](https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent) **is** in Media Recorder API, has {{APIRef("Media Recorder API")}}, and DOES display the API ref.
- When I add groupdata for Media Recorder API the sidebar on BlobEvent disappears!!!!!

There is more to this. Let's continue the discussion in PR: #18910