docs: community docs
mdn/content pull request #18787
Opened 2022-07-25 19:39 UTC by schalkneethling

Adds community docs to the `mdn` folder

2022-07-26 06:37 UTC, OnkarRuikar commented on files/en-us/mdn/community/contributing/getting-started/index.md
> +> If unsure what to do, you are always welcome to [ask for help](https://github.com/mdn/mdn-community/).
```suggestion
> If unsure what to do, you are always welcome to [ask for help](https://chat.mozilla.org/#/room/#mdn:mozilla.org).
```
Chat room is a better place to ask simple queries.

2022-07-26 06:53 UTC, OnkarRuikar commented on files/en-us/mdn/community/contributing/getting-started/index.md
> +We have created a [contributors task board](https://github.com/orgs/mdn/projects/25/views/1) to help you find contribution opportunities that will meaningfully impact the project. The board has an ov
`https://github.com/orgs/mdn/projects/25/views/1` is not visible to non members at the moment.

Only `https://github.com/orgs/mdn/projects/8/views/1` is.

2022-07-26 10:52 UTC, schalkneethling commented on files/en-us/mdn/community/contributing/getting-started/index.md
> +We have created a [contributors task board](https://github.com/orgs/mdn/projects/25/views/1) to help you find contribution opportunities that will meaningfully impact the project. The board has an ov
Yup, that will be opened up soon.

2022-07-26 10:53 UTC, schalkneethling commented on files/en-us/mdn/community/contributing/getting-started/index.md
> +> If unsure what to do, you are always welcome to [ask for help](https://github.com/mdn/mdn-community/).
Thank you for the suggestions, we are still thinking about how we can best manage this going forward.

2022-07-27 11:30 UTC, Rumyra approved these changes

2022-07-27 11:43 UTC, dipikabh approved these changes

2022-07-27 12:07 UTC, Rumyra requested changes

2022-07-27 12:07 UTC, Rumyra commented on files/en-us/mdn/community/contributing/getting-started/index.md
> +slug: MDN/Community/Contributing/Getting_started
```suggestion
slug: MDN/Community/Contributing/Getting-started
```

2022-07-27 12:10 UTC, Rumyra commented
Hmm seems like there's a lot of slug/folder inconsistencies... I'll check out this branch to fix

2022-07-27 12:24 UTC, merged