Update accessibility notes
mdn/content pull request #18841
Opened 2022-07-27 07:32 UTC by CarlSchwan

#### Summary

Update the accessibility section to mention that the dialog element is no longer not recommended, following an update of
See the updates at https://www.scottohara.me/blog/2019/03/05/open-dialog.html

#### Motivation
So that people who don't click on the linked article think that the element is still not supported correctly.

#### Supporting details
- https://www.scottohara.me/blog/2019/03/05/open-dialog.html
- https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/
- https://www.mozilla.org/en-US/firefox/98.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-27 10:33 UTC, teoli2003 requested changes
Either this is still not recommended and the paragraph has to say, or it is usable and the whole paragraph should go.

@estelle ?

2022-07-27 14:27 UTC, CarlSchwan commented
> Either this is still not recommended and the paragraph has to say, or it is usable and the whole paragraph should go.
> 
> @estelle ?

Maybe it should say that if devs want to support versions prior to Firefox 98 and Safari 15.4, they should use the a11y-dialog lib and in the other case just `<dialog>`?

2022-07-27 19:01 UTC, estelle commented
There are still many people who don't have Safari 15.4 or later (4.1% of browsers are Safari 15.3 or earlier).

When we do update this, we should remove all the content in the section, but add new a11y concerns, as I assume there are many, including ensuring consideration of the most appropriate place to set focus and modal v. non modal.

2022-07-27 19:20 UTC, estelle commented
Maybe:

> To ensure accessibility for users of Safari versions below 15.4, consider using a polyfill such as [a11y-dialog](https://a11y-dialog.netlify.app/) as earlier implementations of `<dialog>` had [usability issues with some forms of assistive technology](https://www.scottohara.me/blog/2019/03/05/open-dialog.html). 

> When implementing a dialog, it is important to consider the most appropriate place to set user focus, including the to [`autofocus`](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute if appropriate. 

Ensure the “Escape” key closes the dialog. If multiple dialogs are open, Escape should only close the last shown dialog. 

The <dialog> element is equivalent to [role="dialog"](/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) with the modal dialog behaving similar to setting  [aria-modal="true"](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal). Ensure your implementation of dialog doesn't break expected default behaviors and following proper labeling recommendations.

2022-07-28 17:20 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +When implementing a dialog, it is important to consider the most appropriate place to set user focus, including the to [autofocus](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute if appro
```suggestion
When implementing a dialog, it is important to consider the most appropriate place to set user focus, including using the [autofocus](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute if appropriate.
```

2022-07-28 17:21 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +Ensure the “Escape” key closes the dialog. If multiple dialogs are open, Escape should only close the last shown dialog.
```suggestion
Ensure the <kbd>Escape</kbd> key closes the dialog. If multiple dialogs are open, escape should only close the last shown dialog.
```

2022-07-28 17:23 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +The <dialog> element is equivalent to [role="dialog"](/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) with the modal dialog behaving similar to setting [aria-modal="true"](/en-US/docs/Web/Acces
```suggestion
The `<dialog>` element is equivalent to [role="dialog"](/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) with modal dialogs behaving similar to having [aria-modal="true"](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) set. 

Ensure your dialog implementation doesn't break expected default behaviors and follows proper labeling recommendations.
```

2022-07-28 17:24 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +To ensure accessibility for users of Safari versions below 15.4, consider using a polyfill such as [a11y-dialog](https://a11y-dialog.netlify.app/) as earlier implementations of <dialog> had [usabilit
```suggestion
To ensure accessibility for users of Safari versions below 15.4, consider using a polyfill such as [a11y-dialog](https://a11y-dialog.netlify.app/) as earlier implementations of `<dialog>` had [usability issues with some forms of assistive technology](https://www.scottohara.me/blog/2019/03/05/open-dialog.html).
```

2022-07-28 19:14 UTC, scottaohara submitted a review, later dismissed
a number of suggested further revisions to be more aligned with what the browser gives developers for free with the dialog element.  some of the previous content was written in a way where it seemed like developers would need to still implement these features for the dialog element.  While understandable that people may need to polyfill the element, we don't want to confuse people to think they need to do these things outside of using / creating their own polyfill.

2022-07-28 19:14 UTC, scottaohara commented on files/en-us/web/html/element/dialog/index.md
> +The <dialog> element is equivalent to [role="dialog"](/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) with the modal dialog behaving similar to setting [aria-modal="true"](/en-US/docs/Web/Acces
```suggestion
The `<dialog>` element is exposed by browsers similarly to custom dialogs using the ARIA [role="dialog"](/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) attribute. `<dialog>` elements invoked by the `showModal()` method will have an implicit [aria-modal="true"](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal), where as `<dialog>` elements invoked by the `show()` method, or rendered by use of the `open` attribute or changing the default `display` of a `<dialog>` will be exposed as `[aria-modal="false"]`.  It is recommended to use the appropriate `showModal()` or `show()` method to render dialogs.
```

2022-07-28 23:05 UTC, estelle approved these changes

2022-07-29 05:37 UTC, teoli2003 approved these changes

2022-08-02 02:09 UTC, merged