DRAFT: DO NOT REVIEW. Use strict equality when comparing with a number
mdn/content pull request #18850
Opened 2022-07-27 12:21 UTC by teoli2003

We want to use _strict equality_ as much as possible (instead of the usual regular `==` equality).

2022-07-27 14:31 UTC, Josh-Cena commented on files/en-us/web/api/event/eventphase/index.md
> +      e.eventPhase === 3 ? 'bubbling' : 'error';
I would suggest:

```js
const level = ['none', 'capturing', 'target', 'bubbling'][e.eventPhase] ?? 'error';
```

Looks just as readable to me...

2022-07-27 14:33 UTC, Josh-Cena commented on files/en-us/web/api/videoframe/index.md
> +      const insert_keyframe = (frame_counter % 150) === 0;
```suggestion
      const insert_keyframe = frame_counter % 150 === 0;
```

2022-07-27 14:33 UTC, Josh-Cena commented on files/en-us/web/api/webcodecs_api/index.md
> +      const insert_keyframe = (frame_counter % 150) === 0;
```suggestion
      const insert_keyframe = frame_counter % 150 === 0;
```

2022-07-27 14:33 UTC, Josh-Cena commented on files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md
> +  return (value & (value - 1)) === 0;
```suggestion
  return value & (value - 1) === 0;
```

2022-07-27 14:34 UTC, Josh-Cena commented on files/en-us/web/api/websockets_api/writing_websocket_server/index.md
> +                if (msglen === 126) {
This is C#.

2022-07-27 14:34 UTC, Josh-Cena commented on files/en-us/web/html/element/input/date/index.md
> +} catch(e) {
```suggestion
} catch (e) {
```

2022-07-27 14:35 UTC, Josh-Cena commented on files/en-us/web/html/element/input/date/index.md
> +  } else if (month === 'April' | month === 'June' | month === 'September' | month === 'November') {
```suggestion
  } else if (['April', 'June', 'September', 'November'].includes(month)) {
```

2022-07-27 14:37 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +  element.value = isoString.substring(0, (isoString.indexOf("T")|0) + 6|0);
```suggestion
  element.value = isoString.substring(0, isoString.indexOf("T") + 6);
```

2022-07-27 14:37 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +} catch(e) {
```suggestion
} catch (e) {
```

2022-07-27 14:37 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +  while (daySelect.firstChild){
```suggestion
  while (daySelect.firstChild) {
```

2022-07-27 14:38 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +  if (month === 'January' || month === 'March' || month === 'May' || month === 'July' || month === 'August' || month === 'October' || month === 'December') {
```suggestion
  if (['January', 'March', 'May', 'July', 'August', 'October', 'December'].includes(month)) {
```

2022-07-27 14:38 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +  } else if (month === 'April' || month === 'June' || month === 'September' || month === 'November') {
```suggestion
  } else if (['April', 'June', 'September', 'November'].includes(month)) {
```

2022-07-27 14:40 UTC, Josh-Cena requested changes
(I really need to batch my review comments)

2022-07-27 14:48 UTC, teoli2003 commented on files/en-us/web/api/event/eventphase/index.md
> +      e.eventPhase === 3 ? 'bubbling' : 'error';
Yep!

2022-07-27 15:01 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/equality/index.md
> +"1" == 1;            // true
```suggestion
"1" == 1;             // true
```

2022-07-27 15:03 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
>  )
```js
a.flatMap((n) => (n < 0 ? [] : n % 2 === 0 ? [n] : [n - 1, 1]));
```

For what it's worth, Prettier wants to collapse everything... You may want to do

```js
a.flatMap((n) =>
  n < 0 ? [] : n % 2 === 0 ? [n] : [n - 1, 1]
);
```

2022-07-27 18:28 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
>  )
I decided to avoid nested ternary.

2022-07-28 01:40 UTC, Josh-Cena commented on files/en-us/web/html/element/input/datetime-local/index.md
> +// Define UI widget
```suggestion
// Obtain UI widgets
```

2022-07-28 01:41 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/flatmap/index.md
> +  return (n % 2 === 0) ? [n] : [n - 1, 1];
```suggestion
  return n % 2 === 0 ? [n] : [n - 1, 1];
```

2022-07-28 05:28 UTC, Josh-Cena approved these changes

2022-07-28 05:28 UTC, merged