no more vars in Web/API (2)
mdn/content pull request #18864
Opened 2022-07-27 21:36 UTC by lionralfs

#### Summary

Replaces `var` in Web/API with `const` where applicable and `let` otherwise.
Mostly automated via my ESLint setup, using the rules `no-var` and `prefer-const`

#### Motivation

* See #16662
* See https://github.com/mdn/content/discussions/10389
* See https://github.com/orgs/mdn/discussions/143

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-27 21:38 UTC, lionralfs commented on files/en-us/web/api/cssstylesheet/insertrule/index.md
> +          let openBracketPos = i, closeBracketPos = -1;
I should probably revert these, as they are in a polyfill section mentioning Internet Explorer 5–8.

2022-07-27 22:13 UTC, lionralfs commented on files/en-us/web/api/cssstylesheet/insertrule/index.md
> +          let openBracketPos = i, closeBracketPos = -1;
Might also consider something similar to `example-bad`. Relevant discussion here: https://github.com/eslint/eslint-plugin-markdown/issues/208

2022-07-27 22:36 UTC, lionralfs commented on files/en-us/web/api/document/lastmodified/index.md
> +const
Sure. I'll also rename them

2022-07-27 22:39 UTC, lionralfs commented on files/en-us/web/api/document/registerelement/index.md
> +const Mytag = document.registerElement('my-tag');
I think this should stay the way it is, the following section reads:

> Now the new tag is registered in the browser. The `Mytag` variable holds a
> constructor that you can use to create a `my-tag` element in the document as
> follows:
> 
> ```js
> document.body.appendChild(new Mytag());
> ```

2022-07-28 04:52 UTC, teoli2003 requested changes

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/baseaudiocontext/currenttime/index.md
> +const AudioContext = window.AudioContext || window.webkitAudioContext;
```suggestion
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/baseaudiocontext/destination/index.md
> +const AudioContext = window.AudioContext || window.webkitAudioContext;
```suggestion
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/baseaudiocontext/listener/index.md
> +const AudioContext = window.AudioContext || window.webkitAudioContext;
```suggestion
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/baseaudiocontext/samplerate/index.md
> +const AudioContext = window.AudioContext || window.webkitAudioContext;
```suggestion
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/biquadfilternode/detune/index.md
> +const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
```suggestion
const audioCtx = new AudioContext();
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/biquadfilternode/frequency/index.md
> +const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
```suggestion
const audioCtx = new AudioContext();
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/biquadfilternode/q/index.md
> +const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
```suggestion
const audioCtx = new AudioContext();
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/biquadfilternode/type/index.md
> +const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
```suggestion
const audioCtx = new AudioContext();
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/biquadfilternode/gain/index.md
> +const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
```suggestion
const audioCtx = new AudioContext();
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/bluetooth/getavailability/index.md
> +const readerPromise = Bluetooth.getAvailability();
```suggestion
getAvailability()
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/bluetooth/getdevices/index.md
> +const readerPromise = Bluetooth.getDevices();
```suggestion
getDevices()
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/bluetoothremotegattdescriptor/characteristic/index.md
>  ```js
```suggestion
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/bluetoothremotegattdescriptor/characteristic/index.md
>  ### Returns
```suggestion
## Value
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/canvascapturemediastreamtrack/canvas/index.md
> +const canvasElt = document.getElementsByTagName("canvas")[0];
```suggestion
const canvasElt = document.getQuerySelector("canvas");
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/canvascapturemediastreamtrack/requestframe/index.md
> +const canvasElt = document.getElementsByTagName("canvas")[0];
```suggestion
const canvasElt = document.getQuerySelector("canvas");
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/clipboarditem/gettype/index.md
> +const blob = clipboardItem.getType(type);
```suggestion
getType(type)
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/contactsmanager/getproperties/index.md
> +const contactProperties = ContactsManager.getProperties();
```suggestion
getProperties()
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/cssstyledeclaration/msgetpropertyenabled/index.md
> +const retVal = style.msGetPropertyEnabled(name);
```suggestion
msGetPropertyEnabled(name)
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/cssstyledeclaration/msputpropertyenabled/index.md
> +const retval = style.msPutPropertyEnabled(propertyName, true);
```suggestion
msPutPropertyEnabled(name, boolean)
```

2022-07-28 04:52 UTC, teoli2003 commented on files/en-us/web/api/datatransferitem/getasfilesystemhandle/index.md
> +const handle = DataTransferItem.getAsFileSystemHandle();
```suggestion
getAsFileSystemHandle()
```

2022-07-28 10:37 UTC, lionralfs commented on files/en-us/web/api/canvascapturemediastreamtrack/canvas/index.md
> +const canvasElt = document.getElementsByTagName("canvas")[0];
```suggestion
const canvasElt = document.querySelector("canvas");
```
?

2022-07-28 10:40 UTC, lionralfs commented on files/en-us/web/api/canvascapturemediastreamtrack/requestframe/index.md
> +const canvasElt = document.getElementsByTagName("canvas")[0];
```suggestion
const canvasElt = document.querySelector("canvas");
```

2022-07-28 11:35 UTC, teoli2003 approved these changes
👍

2022-07-28 11:35 UTC, merged