Update index.md file for Object.create classical inhertiace example
mdn/content pull request #18880
Opened 2022-07-28 05:58 UTC by gtalin

Update classical inheritance example. Use setPrototypeOf property. Which is a more advisable property to use rather than re-assignment of prototype.

#### Summary
It is frowned upon to re-assign an object prototype like it is done in the classical inheritance example. 
Instead `Object.setPrototypeOf` should be used.

#### Motivation

Seeing a lot of conflicting information can be confusing for beginners. So it is good to mention different ways of doing something along with specifying the best practice for the same. 

#### Supporting details
[Supporting link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#building_longer_inheritance_chains)

#### Related issues
NA

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-07-28 06:28 UTC, Josh-Cena requested changes
The introduction to this code block says:

> Below is an example of how to use `Object.create()` to achieve classical inheritance. This is for a single inheritance, which is all that JavaScript supports.

Which no longer makes sense after this re-write. Maybe we can keep the original code, but tell people that it's a really bad thing to do? This is the reference page for `Object.create()` anyway, and all code examples should be relevant.

Would also be great if you can do a quick self-review and make sure everything still reads coherently.

2022-07-28 06:33 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +// In class terms, the above is equivalent to using `extends`
There's too much comment in between. We are better off using a normal paragraph.

2022-07-28 09:51 UTC, gtalin commented
> The introduction to this code block says:
> 
> > Below is an example of how to use `Object.create()` to achieve classical inheritance. This is for a single inheritance, which is all that JavaScript supports.
> 
> Which no longer makes sense after this re-write. Maybe we can keep the original code, but tell people that it's a really bad thing to do? This is the reference page for `Object.create()` anyway, and all code examples should be relevant.
> 
> Would also be great if you can do a quick self-review and make sure everything still reads coherently.

I will undo the changes I made to the code and add a paragraph below the code mentioning it is not a good idea to use `Object.create()` for such a case.

2022-07-28 10:07 UTC, zloirock reviewed
I'm just curious, why do you think that `Object.setPrototypeOf` is better than `Object.create` in this case? Even here, on [the MDN `Object.setPrototypeOf` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf), is a warning and recommendation to use `Object.create` instead of `Object.setPrototypeOf`.

2022-07-28 11:23 UTC, gtalin commented
> I'm just curious, why do you think that `Object.setPrototypeOf` is better than `Object.create` in this case? Even here, on [the MDN `Object.setPrototypeOf` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf), is a warning and recommendation to use `Object.create` instead of `Object.setPrototypeOf`.

I don't think `Object.create` is bad. What I was saying is re-assignment of prototype that we're doing is bad.  The [MDN Inheritance page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain) mentions it is a bad idea to re-assign prototype. 

I think what [the MDN `Object.setPrototypeOf` page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf) is saying in terms of using `Object.create()` is different from our context. It mentions creating an object  by using some other object as its prototype.
Something like the following example:

```js
obj = {
  hello() {
     console.log(`this.foo is ${this.foo}`);
   }
}
let objWProto = Object.create(obj);
// objWProto created with obj as prototype
Object.getPrototypeOf(objWProto); // {hello: ƒ}
const o = new Object();
Object.getPrototypeOf(o); // {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}
```

The page mentions
> if you are concerned about performance, you should avoid setting the `[[Prototype]]` of an object. Instead, create a new object with the desired `[[Prototype]]` using [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create).

2022-07-28 11:27 UTC, Josh-Cena commented
@zloirock It's more of an ergonomics point than a performance point. People often forget to re-assign `constructor` and lead to broken semantics. In Inheritance and the Prototype Chain I went with the convenient path of recommending mutating prototypes, but maybe in hindsight that encourages terrible performance.

2022-07-28 11:56 UTC, zloirock commented
For the ergonomic reason is better to use classes.

Or, if they are not available, for the ergonomic reason, assign to `.prototype` object literal with `__proto__` - here, at least, it's possible to define methods in the object literal:
```js
Child.prototype = {
  __proto__: Parent.prototype,
  constructor: Child,
  method() { /* ... */ } 
}
```

`Object.setPrototypeOf` is bad for performance, `__proto__` (at least in old engines, maybe now it's fixed) also is bad for performance and deoptimize functions where it's used.

Also, `Object.setPrototypeOf` and `__proto__` are not available in old engines (like IE10) and can't be polyfilled. However, who uses them?

Personally, I prefer `Object.create` and use `Object.setPrototypeOf` only in cases where it's not possible workaround it.

It's the `Object.create` page and this example shows how works inheritance with the usage of `Object.create`  - I think that it should not be replaced, maximum makes sense to add a link to an example of inheritance with the usage of `Object.setPrototypeOf`.

2022-07-28 12:01 UTC, Josh-Cena commented
Yes, that would also be my stance. Since we're on the `Object.create` page, better demonstrate that.

(Worth noting that `constructor` is non-enumerable and that's quite important.)

2022-07-28 13:51 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +It is because `Rectangle.prototype = Object.create(Shape.prototype);` causes prototypal re-assignment because of which `[[prototype]]` of `Rectangle` loses link to its `constructor`.
Reassignment of `.prototype` property does not cause reassignment `[[Prototype]]` of `Rectangle` - `Object.setPrototypeOf` [do it](https://tc39.es/ecma262/#sec-ordinarysetprototypeof).

2022-07-28 13:57 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +It is because `Rectangle.prototype = Object.create(Shape.prototype);` causes prototypal re-assignment because of which `[[prototype]]` of `Rectangle` loses link to its `constructor`.
At least `[[prototype]]` -> `.prototype` or `[[prototype]] of Rectangle` -> `Rectangle instances`.

2022-07-29 09:19 UTC, gtalin commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +It is because `Rectangle.prototype = Object.create(Shape.prototype);` causes prototypal re-assignment because of which `[[prototype]]` of `Rectangle` loses link to its `constructor`.
What I was trying to say is that `Rectangle` will lose access to its constructor. 
I'll be able to explain what I am saying better with an example. 
If we continue with the `Shape` and `Rectangle` example, then with`Object.create()` 

```js
Rectangle.prototype = Object.create(Shape.prototype);
console.log(Rectangle.prototype)
// Shape {}
//  [[Prototype]]: Object
const rect = new Rectangle()
console.log(rect.__proto__)
// Shape {}
//  [[Prototype]]: Object
//    move: ƒ (x, y)
//    constructor: ƒ Shape()
//    [[Prototype]]: Object
console.log(Object.getPrototypeOf(rect)) // same as above
```

Now the same thing with `Object.setPrototypeOf()`

```js
Object.setPrototypeOf(Rectangle.prototype, Shape.prototype);
console.log(Rectangle.prototype)
// Shape {constructor: ƒ}
//  constructor: ƒ Rectangle()
//  [[Prototype]]: Object
const rect = new Rectangle()
console.log(rect.__proto__) // same as above
console.log(Object.getPrototypeOf(rect)) // same as above
```

2022-07-29 09:29 UTC, gtalin commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +// In class terms, the above is equivalent to using `extends`
Removed the comments. Have kept the code intact and have added a paragraph in the end mentioning it's not best practice to use `Object.create()` in such a situation.

2022-07-29 09:30 UTC, zloirock commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +It is because `Rectangle.prototype = Object.create(Shape.prototype);` causes prototypal re-assignment because of which `[[prototype]]` of `Rectangle` loses link to its `constructor`.
And in both cases "`[[prototype]]` of `Rectangle`" (`Rectangle.__proto__`) is not affected.

2022-07-29 09:55 UTC, gtalin commented on files/en-us/web/javascript/reference/global_objects/object/create/index.md
> +It is because `Rectangle.prototype = Object.create(Shape.prototype);` causes prototypal re-assignment because of which `[[prototype]]` of `Rectangle` loses link to its `constructor`.
That is correct. Thanks for the clarification. I will rectify it to `prototype` rather than `[[Prototype]]`.  Since `Rectangle.prototype` is the property that is changing. Which is in turn affecting the `constructor`.

2022-08-02 17:45 UTC, Josh-Cena commented
After thinking about it for a few days, I've changed my stance and I think it's in the interest of MDN to (a) point out the pitfalls with `Object.create()` (e.g. forgetting to bind `constructor` or accidentally making it enumerable) (b) point out the ill performance of `Object.setPrototypeOf` (c) give a fully correct demonstration of how to overwrite `prototype` via `Object.create()`, like how Babel does it. This involves multiple pages so I'll send another PR later (a bit busy these days), after which I'll close this one.

2022-09-19 04:59 UTC, Josh-Cena commented
Hi! I've opened https://github.com/mdn/content/pull/20693 myself which I believe is a better fix. I will close this for housekeeping. Feel free to post reviews under that PR.

2022-09-19 04:59 UTC, closed without merging