Page for the new :modal pseudo-class
mdn/content pull request #18892
Opened 2022-07-28 13:01 UTC by dipikabh

#### Summary

- Added new page for the `:modal `pseudo class
- Updated the existing Pseudo classes page to:
   - Arrange the categories alphabetically
   - Add a category for "Element display state pseudo classes" (https://www.w3.org/TR/selectors-4/#display-state-pseudos)
   - Add `:modal` to the alphabetical index

#### Motivation

The new pseudo class has been implemented (made available) in FF103

#### Supporting details

Bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1768535
Spec: https://www.w3.org/TR/selectors-4/#modal-state

#### Related issues

Doc issue tracker: https://github.com/mdn/content/issues/17470

#### Metadata

- [X] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-07-28 20:24 UTC, estelle requested changes

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  position: absolute;
```suggestion
  border: 5px solid red;
```

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  top: 10%;
```suggestion
```

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  left: 10%;
```suggestion
```

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  background-color: yellow;
```suggestion
  background-color: yellow;
  box-shadow: 3px 3px 10px rgba(0 0 0 / 0.5);
```

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  position: absolute;
by default, the dialog is position fixed. we don't want to encourage changing that. With fixed, the dialog stays in the middle of the page even if the user scrolls. With absolute, it can scroll off the screen. In a modal dialog, nothing other than the dialog can have focus; that's why fixed is kind of important.

2022-07-28 20:24 UTC, estelle commented on files/en-us/web/css/_colon_modal/index.md
> +  top: 10%;
no longer doing absolute, and i think 10% is 10% of the dialog height, so it only moves a few pixels. adding border and shadow instead.

2022-07-28 20:28 UTC, estelle commented on files/en-us/web/css/pseudo-classes/index.md
> +  - : Matches an input element that is displaying placeholder text, for example from the HTML5 `placeholder` attribute.
also textarea i think

2022-07-28 20:33 UTC, estelle commented on files/en-us/web/css/pseudo-classes/index.md
> +  - : Matches when UI elements are in an indeterminate state.
```suggestion
  - : Matches UI elements when they are in an indeterminate state.
```

2022-07-28 20:37 UTC, estelle commented on files/en-us/web/css/pseudo-classes/index.md
> +  - : Matches an element with valid contents. For example an input element with type 'email' which contains a validly formed email address.
```suggestion
  - : Matches an element with valid contents. For example an input element with type 'email' which contains a validly formed email address or an empty value if the control is not required.
```

2022-07-28 20:46 UTC, estelle commented on files/en-us/web/css/pseudo-classes/index.md
> +
on line 85, i think :dir needs to be updated to :dir()

2022-07-29 05:40 UTC, teoli2003 commented on files/en-us/web/css/pseudo-classes/index.md
> +  - : Matches an input element that is displaying placeholder text, for example from the HTML5 `placeholder` attribute.
HTML5 is a taboo word nowadays.
```suggestion
  - : Matches an input element that is displaying placeholder text, for example, from the HTML `placeholder` attribute.
```

2022-08-01 10:57 UTC, dipikabh commented
> on line 85, i think `:dir` needs to be updated to `:dir()` and `:lang` to `:lang()` a few lines after that.
> 
> I don't know if we want to include a section on the @ page pseudo classes:
> 
> [:blank](https://developer.mozilla.org/en-US/docs/Web/CSS/:blank) [:first](https://developer.mozilla.org/en-US/docs/Web/CSS/:first) [:left](https://developer.mozilla.org/en-US/docs/Web/CSS/:left) [:right](https://developer.mozilla.org/en-US/docs/Web/CSS/:right) :recto :verso

I updated `:dir` and `:lang` to `:dir()` and `:lang()`. Thanks for catching this!

I guess I am going to leave adding a section for `@page` pseudo classes for now. They are not clearly defined in the spec and are not in one of the categories. Although we have them documented, `:first`, `:left` and `:right`are not in spec. `:blank` is listed under the input pseudo-class category - same as in the spec. In any case, https://developer.mozilla.org/en-US/docs/Web/CSS/@page page has them listed (just not in the Pseudo-classes landing page).

2022-08-01 20:06 UTC, estelle approved these changes

2022-08-01 20:06 UTC, merged