Contradicting statements
mdn/content pull request #19061
Opened 2022-08-02 16:03 UTC by Chaitanya7666

#### Summary

If **settled** can be used to refer to both resolved and rejected, then what is the use of having a handler for rejection? I feel that this line is contradicting with previous explanations of a promise being resolved and rejected.
#### Motivation

* I had been learning about JS promises from the MDN docs. 
* I felt that this line is contradicting with the previous explanations of resolve and rejected in the same lesson. Hence, I wanted to propose this change so that it would be helpful to everyone.
#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-02 17:11 UTC, Josh-Cena requested changes
The original statement is correct. A promise has three states: pending, fulfilled, and rejected. A settled promise is not pending, i.e. fulfilled or rejected. "Resolved" is _not_ one of the promise states: it's a process, not a state. What needs to be changed is everywhere we say "the resolved handler"—there's only ever the "fulfilled handler".

We have a correct description here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#description

2022-08-03 03:02 UTC, Chaitanya7666 commented
Thanks for your explanation @Josh-Cena . I have quick follow-up question. If *Settled* indicates both success and failure then it means that either of **then** or **catch** handler will be invoked if a promise is resolved, Is that right?

However, I don't understand what you mean by this, 'What needs to be changed is everywhere we say "the resolved handler"—there's only ever the "fulfilled handler".'. Are you asking me to change something or you are just saying it for me to understand it well?

2022-08-03 03:07 UTC, Josh-Cena commented
A promise can have many handlers queued up.

```js
somePromise.then(h1, h2).catch(h3).then(h4)
```

When `somePromise` fulfills, `h1` is called. When it rejects, `h2` is called. Whether `h3` gets called depends on whether `h1` or `h2` rejects. Whether `h4` gets called depends on whether `h1` or `h2` fulfills. Handlers are always _chained_ and it's the promise implementation's duty to call the respective handler when the current promise's state changes from pending to settled.

> Are you asking me to change something or you are just saying it for me to understand it well?

I was saying that because I saw this:

> If settled can be used to refer to both resolved and rejected, then what is the use of having a handler for rejection? I feel that this line is contradicting with previous explanations of a promise being resolved and rejected.

It is often wrong to be comparing "resolved" with "rejected"—"rejected" can only be compared with "fulfilled". "Resolved" is an entirely different concept. Everywhere where we compare them, we should seek to convert "resolve" to "fulfill".

2022-08-03 15:55 UTC, Chaitanya7666 commented
It's clear to me now. Thank you! I can understand that my proposed changes are not correct and I am closing this pull request.

2022-08-03 15:55 UTC, closed without merging