Inert in global attribute - fix for "Add inert attribute” #19075 on MDN repos.
mdn/content pull request #19090
Opened 2022-08-03 04:17 UTC by Isaac108

Added the inert description. Along with a small page detailing its uses. More work is probably required for the page to be up to the elite standards as with the other attributes on the page, but I believe this is a good start.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-03 04:23 UTC, teoli2003 commented
Can you remove from this PR the unrelated pages? Thank you!

2022-08-03 04:27 UTC, Isaac108 commented
> 

Yep,, got it.

2022-08-03 05:03 UTC, teoli2003 requested changes, later dismissed
Thank you!

In addition to these comments, we should have a small examples, as well as:
- a _Specifications_ section (using the `{{Specifications}}` macro
- a _Browser compatibility_ section (using the `{{Compat}}` macro
- a _See also_ section.

Is there already an entry in mdn/browser-compatibility-data ? If not, we need to add it there, and to add a YAML header here.

2022-08-03 05:03 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +•prevent events from assistive technologies
```suggestion
Specifically, it prevents the following actions to happens:

- It prevents the {{domxref("Element/click_event", "click")}} event from being thrown when the user clicks on the element.
- It prevents the {{domxref("Element/focus_event", "focus")}} event to be raised, by preventing the focus to be given to the element.
- It prevents assistive technologies raised on this element.
```

2022-08-03 05:04 UTC, teoli2003 commented
This will fixes #19075

2022-08-03 05:05 UTC, teoli2003 commented
Also, for the example, it should be possible to adapt the live example found [there](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert).

2022-08-03 05:47 UTC, Josh-Cena commented on files/en-us/web/html/global_attributes/inert/index.md
> +
@teoli2003 note, after we start using Prettier, Prettier will enforce an empty line after the front matter. I suggest we start accepting empty lines here.

2022-08-03 12:31 UTC, schalkneethling commented on files/en-us/web/html/global_attributes/index.md
> +  - : A boolean value which makes the browser disregard user input events for the element. Useful where clicking events are present.
```suggestion
  - : A boolean value that makes the browser disregard user input events for the element. Useful when click events are present.
```

2022-08-04 05:00 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +
They are fixed by the DailyMarkdownLint scripts.

2022-08-04 05:15 UTC, Josh-Cena commented on files/en-us/web/html/global_attributes/inert/index.md
> +
When you search for `---\n\n` you'll see a lot of files with empty lines here—I think it's usually better to add an empty line.

2022-08-06 00:09 UTC, bkardell commented on files/en-us/web/html/global_attributes/index.md
> +  - : A boolean value that makes the browser disregard user input events for the element. Useful when click events are present.
I realize these are very brief, but maybe this is too brief?  What about like "A boolean value that indicates that the element (and all of its flat tree descendants) are not currently relevant and should act as if it were not present for purposes of user interaction (including hiding it from accessibility technology)"

2022-08-06 00:11 UTC, bkardell commented on files/en-us/web/html/global_attributes/inert/index.md
> +- It prevents assistive technologies raised on this element.
Not sure what this means? It is hidden from the a11y tree

2022-08-16 17:21 UTC, caugner submitted a review, later dismissed

2022-08-16 17:21 UTC, caugner commented on files/en-us/web/html/global_attributes/index.md
> +- [`inert`](/en-US/docs/Web/HTML/Global_attributes/id)
Shouldn't it link to `Global_attributes/inert`?

```suggestion
- [`inert`](/en-US/docs/Web/HTML/Global_attributes/inert)
```

2022-08-17 06:28 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +
I'm fine this, then.

2022-08-17 06:30 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +- It prevents assistive technologies raised on this element.
What about:
```suggestion
- It hides the element and its content from assistive technologies by excluding them from the accessibility tree.
```

2022-08-17 06:30 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/index.md
> +- [`inert`](/en-US/docs/Web/HTML/Global_attributes/id)
Yes, of course.

2022-08-17 06:37 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +slug: Web/HTML/Global_attributes/inputmode
```suggestion
slug: Web/HTML/Global_attributes/inert
```

2022-08-17 06:45 UTC, teoli2003 commented on files/en-us/web/html/global_attributes/inert/index.md
> +- It prevents assistive technologies raised on this element.
I went ahead and committed this, but we can still work on line 25, if you want.

2022-10-10 21:18 UTC, Josh-Cena commented on files/en-us/web/html/global_attributes/inert/index.md
> +- It hides the element and its content from assistive technologies by excluding them from the accessibility tree.
```suggestion
Specifically, it does the following:

- It prevents the {{domxref("Element/click_event", "click")}} event from being thrown when the user clicks on the element.
- It prevents the {{domxref("Element/focus_event", "focus")}} event from being raised, by preventing the element from gaining focus.
- It hides the element and its content from assistive technologies by excluding them from the accessibility tree.
```

2022-10-10 21:19 UTC, Josh-Cena commented
Seems we have BCD. Is this ready?

2022-11-07 07:35 UTC, sideshowbarker commented
> Seems we have BCD. Is this ready?

yeah, seems like it’s ready to go — though at https://github.com/mdn/content/pull/19090#discussion_r991645879 I see one pending commit suggestion

2022-11-07 10:55 UTC, caugner reviewed
No objections from me, but I'll leave the content review to others.

2022-11-21 17:38 UTC, queengooborg commented
Hey @teoli2003, are you still planning on reviewing this PR?

2022-11-21 21:25 UTC, estelle approved these changes

2022-11-21 21:26 UTC, merged

2022-11-21 21:26 UTC, estelle commented
Congratulations on your first MDN merged PR. Thank you for your contribution.