DO NOT REVIEW – Use arrow functions for anonymous functions
mdn/content pull request #19109
Opened 2022-08-03 13:10 UTC by teoli2003

When possible, use arrow functions for anonymous functions.

2022-08-04 04:56 UTC, Josh-Cena requested changes

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +rect2.bind("EnterFrame", function() {
```suggestion
rect2.bind("EnterFrame", function () {
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/techniques/3d_on_the_web/webvr/index.md
>    if(posState.hasPosition) {
```suggestion
  if (posState.hasPosition) {
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/techniques/async_scripts/index.md
> +script.onload = script.onerror = () => { URL.revokeObjectURL(url); };
```suggestion
script.onload = script.onerror = () => URL.revokeObjectURL(url);
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/techniques/control_mechanisms/other/index.md
>  }, this);
I have no idea what the `this` is supposed to do...

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -};
Is this removed on purpose?

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -Ball.Game = function(game) {};
Should this be removed?

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> +this.hole = this.add.sprite(Ball._WIDTH * 0.5, 90, 'hole');
Frankly I don't know what the `this` here is, but I hope it still works.

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> +  if (this.levels[lvl -2 ]) {
```suggestion
  if (this.levels[lvl - 2]) {
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/commands/getall/index.md
>    });
```suggestion
  commands.forEach(console.log);
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/extension/onrequest/index.md
> +  () => {/* … */} // function
```suggestion
  () => {/* … */}  // function
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/extension/onrequestexternal/index.md
> +  () => { } // function
```suggestion
  () => {/* … */}  // function
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/extension/sendrequest/index.md
> +  (response) => { } // optional function
```suggestion
  (response) => {/* … */}  // optional function
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/menus/create/index.md
> +  () => { }  // optional function
```suggestion
  () => {/* … */}   // optional function
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onmessage/index.md
>    });
```suggestion
  }).then((results) => results.length > 0);
```

2022-08-04 04:56 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/sharing_objects_with_page_scripts/index.md
> +     get: exportFunction(() => {             // getters must be exported like regular functions
```suggestion
     get: exportFunction(() => {                  // getters must be exported like regular functions
```

2022-08-05 06:21 UTC, teoli2003 commented on files/en-us/games/techniques/control_mechanisms/other/index.md
>  }, this);
It will act as a `true` if not undefined.
I think we should do this:
```suggestion
}, true);
```

2022-08-05 06:23 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -};
This becomes the constructor.

2022-08-05 06:23 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -Ball.Game = function(game) {};
This become the constructor.

(Maybe we should transform this in a `class`

2022-08-05 06:27 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> +this.hole = this.add.sprite(Ball._WIDTH * 0.5, 90, 'hole');
I think `this` is the `Ball` instance.

2022-08-05 08:25 UTC, Josh-Cena commented on files/en-us/games/techniques/control_mechanisms/other/index.md
>  }, this);
Yes, I think it's intended to be `true`. Most code these days should be running in strict mode.

2022-08-06 08:40 UTC, Josh-Cena commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
> +const timer = 0;
```suggestion
let timer = 0;
```

2022-08-06 08:42 UTC, Josh-Cena commented on files/en-us/games/techniques/audio_for_web_games/index.md
>    source.start(context.currentTime+delay, relativeTime+delay);
```suggestion
  const delay = tempo - remainder * tempo;
  source.start(context.currentTime + delay, relativeTime + delay);
```

2022-08-06 08:44 UTC, Josh-Cena commented on files/en-us/games/techniques/control_mechanisms/other/index.md
>  }, this);
@teoli2003 There's another occurrence of `this` directly below which isn't reachable through the diff. Let's change both of them.

2022-08-06 08:46 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
>  };
@teoli2003 Let's make this an actual class. This is not correct because constructors must be either functions or classes, but not objects with a property called `constructor`.

2022-08-06 08:47 UTC, teoli2003 commented on files/en-us/games/techniques/control_mechanisms/other/index.md
>  }, this);
Fixed.

2022-08-06 08:55 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
>  };
@Josh-Cena I will revert this file: this is using Phaser2 that is outdated, so trying to make this work to save a couple of `function` keywords is pointless:
- the whole article needs to be rewritten for Phaser3 anyway
- no docs for Phaser2 are easy to find
- `function` for constructor are "fine" (until we use "class")

2022-08-06 08:57 UTC, Josh-Cena commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
>  };
Sure!

2022-08-06 09:00 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
>  };
Reverted.

2022-08-06 09:00 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -};
Reverted.

2022-08-06 09:00 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> -Ball.Game = function(game) {};
Reverted

2022-08-06 09:01 UTC, teoli2003 commented on files/en-us/games/tutorials/html5_gamedev_phaser_device_orientation/index.md
> +this.hole = this.add.sprite(Ball._WIDTH * 0.5, 90, 'hole');
Still open, but we didn't change this, so I propose to keep it this way (when it will move to Phaser3 it will be fixed, or better explained)

2022-08-06 09:06 UTC, Josh-Cena commented on files/en-us/games/techniques/3d_on_the_web/webvr/index.md
>    gHMD.setFieldOfView(testFOV,testFOV,0.01,10000.0);
```suggestion
  gHMD.setFieldOfView(testFOV, testFOV, 0.01, 10000.0);
```

2022-08-06 09:11 UTC, Josh-Cena approved these changes
LGTM!

2022-08-06 09:11 UTC, merged