Update .isAlpha() express validator.
mdn/content pull request #19103
Opened 2022-08-03 11:03 UTC by vphatfla

First names and last names should only contain alphabet letters. Using isAlphanumeric() is incorrect.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-03 11:59 UTC, teoli2003 requested changes

2022-08-03 11:59 UTC, teoli2003 commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
I'm not sure this is good. _My_ first name contains non-alphabetic characters, and I know plenty of people with non-alphabetic characters in their last names.

`isAlphanumeric()` is incorrect, but `isAlpha()` doesn't solve this.

2022-08-06 11:31 UTC, Josh-Cena commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ 😄

We should not have any of these validations

2022-08-08 00:55 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
@teoli2003 @Josh-Cena  You make a good point - sadly Elon Musk won't be able to check in baby "X Æ A-12" in the library.  But wouldn't all of you be happier if all those pointless extra characters were removed from you names ? :-). 

I put in `isAlphanumeric()` to show the use of the validator - almost any validator would have done here. I agree it is a "bad lesson" for programmers, but unless you feel strongly about this I'd rather leave it as is.

2022-08-08 00:56 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
Note, I would be very happy to add a note that this is not a good thing to do!

2022-08-08 07:03 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
This applies to your request : https://www.youtube.com/watch?v=TkR9QWuoyJ8 :-)

2022-08-08 07:05 UTC, hamishwillee commented
Thanks very much for highlighting this issue  @vphatfla 

I'll "fix" it by adding a note rather than altering the method used.

2022-08-08 07:05 UTC, closed without merging

2022-08-08 13:40 UTC, vphatfla commented on files/en-us/learn/server-side/express_nodejs/forms/create_author_form/index.md
> +        .isAlpha().withMessage('First name has non-alphanumeric characters.'),
Thanks @hamishwillee, adding a note would be very useful. :-)

2022-08-09 00:25 UTC, hamishwillee commented
DOne!