DO NOT REVIEW – Use arrow functions
mdn/content pull request #19115
Opened 2022-08-03 15:03 UTC by teoli2003

When possible, we want to use arrow functions for anonymous functions

2022-08-05 08:56 UTC, Josh-Cena requested changes
Whew, finally made it through... I have a feeling there are some `this` issues that we didn't catch, because I already spotted one!

2022-08-05 08:56 UTC, Josh-Cena commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
This would no longer create the `this` binding, which is passed below.

2022-08-05 08:56 UTC, Josh-Cena commented on files/en-us/web/api/event/preventdefault/index.md
> +  );
```js
warningTimeout = setTimeout(() => {
  warningBox.parentNode.removeChild(warningBox);
  warningTimeout = -1;
}, 2000);
```

2022-08-05 08:56 UTC, Josh-Cena commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +  els[j].addEventListener("click", processEvent = (e) => {/* do something */}, false);
This looks like a really weird example...

2022-08-05 08:56 UTC, Josh-Cena commented on files/en-us/web/api/file_api/using_files_from_web_applications/index.md
> +    reader.onload = ((aImg) => { return (e) => { aImg.src = e.target.result; }; })(img);
```suggestion
    reader.onload = ((aImg) => (e) => { aImg.src = e.target.result; })(img);
```

2022-08-05 08:56 UTC, Josh-Cena commented on files/en-us/web/api/history_api/example/index.md
> +const ajaxRequest = new (() => {
This is a constructor. _Maybe_ extract it to a separate declaration?

2022-08-06 06:20 UTC, teoli2003 commented on files/en-us/web/api/datatransferitem/webkitgetasentry/index.md
>            scanFiles(entry, directoryContainer);
```suggestion
      entries.forEach((entry) => {
        scanFiles(entry, directoryContainer);
```

2022-08-06 06:23 UTC, teoli2003 commented on files/en-us/web/api/domtokenlist/foreach/index.md
>      pre.textContent += `(${value} ${key})/${this}\n`;
I think both `classes` and `listObj` are the same, so I use the parameter here.
```suggestion
    pre.textContent += `(${value} ${key})/${listObj}\n`;
```

2022-08-06 06:23 UTC, teoli2003 commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
Fixed below (please double check)

2022-08-06 06:25 UTC, teoli2003 commented on files/en-us/web/api/event/preventdefault/index.md
> +  );
Fixed.

2022-08-06 06:44 UTC, teoli2003 commented on files/en-us/web/api/history_api/example/index.md
> +const ajaxRequest = new (() => {
The whole example is difficult to understand, not sure I want to go in this rabbit hole now. I'm just reverting.
```suggestion
const ajaxRequest = new (function () {
```

2022-08-06 06:48 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +  els[j].addEventListener("click", processEvent = (e) => {/* do something */}, false);
I'm removing cases 3 and 4, it is very very edge cases. Nobody write code like this (or at least should) and I think this is far, far from any real world usage.

2022-08-06 06:49 UTC, teoli2003 commented
>  I have a feeling there are some `this` issues that we didn't catch, because I already spotted one!

I'm making an extra pass to double-check this, and request a review when I'm done.

2022-08-06 07:04 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +const Something = (element) => {
This is a constructor, I'm reverting it to:
```suggestion
const Something = function (element) {
```

2022-08-06 07:04 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +const Something = (element) => {
Same here:
```suggestion
const Something = function (element) {
```

2022-08-06 07:07 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
>  }.bind(someString));
We need to revert here, I think the bind will not work with an arrow function.
```suggestion
myButton.addEventListener('click', function () {
  console.log(this); // Expected Value: 'Data'
}.bind(someString));
```

2022-08-06 07:08 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +  this.handleEvent = (event) => {
```suggestion
  this.handleEvent = function (event) {
```

2022-08-06 07:09 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +  this.onclick1 = (event) => {
```suggestion
  this.onclick1 = function (event) {
```

2022-08-06 07:09 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +  this.onclick2 = (event) => {
```suggestion
  this.onclick2 = function (event) {
```

2022-08-06 07:09 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
> +my_element.addEventListener('click', (e) => {
```suggestion
my_element.addEventListener('click', function (e) {
```

2022-08-06 07:10 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/eventtarget/index.md
>    this._secret = e.detail;
```suggestion
  myEventTarget._secret = e.detail;
```

2022-08-06 07:13 UTC, teoli2003 commented on files/en-us/web/api/file_api/using_files_from_web_applications/index.md
>    fileElem = document.getElementById("fileElem");
```suggestion
const fileSelect = document.getElementById("fileSelect");
const fileElem = document.getElementById("fileElem");
```

2022-08-06 07:42 UTC, teoli2003 commented on files/en-us/web/api/htmlinputelement/stepup/index.md
>  let button = document.getElementById('theButton')
```suggestion
const button = document.getElementById('theButton');
```

2022-08-06 07:53 UTC, teoli2003 commented
I made a pass for `this` and found:

- A case in a polyfill. I deleted the polyfill.
- Several cases in `addEventListener()` that were demonstrating the binding of `this`. I reverted these.
- One actual case of `this` that I fixed.

2022-08-06 08:00 UTC, Josh-Cena commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
@teoli2003 I don't think that fixes it—we have explicitly passed `"arg"` as the `thisArg`, so in the original example, it would log `arg` as the value of `this` inside the function. Can't say how useful that is in practice, but that's the point of this example.

2022-08-06 08:02 UTC, Josh-Cena commented on files/en-us/web/api/document/getelementsbyclassname/index.md
>  });
```suggestion
const testDivs = Array.prototype.filter.call(
  testElements,
  (testElement) => testElement.nodeName === 'DIV',
);
```

2022-08-06 08:02 UTC, Josh-Cena commented on files/en-us/web/api/event/composedpath/index.md
> +document.querySelector('html').addEventListener('click',(e) => {
```suggestion
document.querySelector('html').addEventListener('click', (e) => {
```

2022-08-06 08:03 UTC, teoli2003 commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
Let's revert to a function then?

2022-08-06 08:05 UTC, Josh-Cena commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
The text above talks about "problem-cases below" but they are non-existent. A rephrase needed.

2022-08-06 08:07 UTC, Josh-Cena commented on files/en-us/web/api/file_api/using_files_from_web_applications/index.md
> +    reader.onload = ((aImg) => (e) => { aImg.src = e.target.result; })(img);
```suggestion
    reader.onload = (e) => { aImg.src = e.target.result; };
```

Closure no longer needed with lexical declarations

2022-08-06 08:10 UTC, teoli2003 commented on files/en-us/web/api/eventtarget/addeventlistener/index.md
Sentence removed

2022-08-06 08:11 UTC, Josh-Cena commented on files/en-us/web/api/htmlcanvaselement/mozfetchasstream/index.md
>  }
For these sorts of examples, what about `netutilCallback = () => (result) => ...`? It's definitely readable to me, but I don't represent general readers...

2022-08-06 08:13 UTC, Josh-Cena commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
Yes, let's revert it.

2022-08-06 08:14 UTC, Josh-Cena commented on files/en-us/web/api/htmlcanvaselement/mozfetchasstream/index.md
>  }
Actually we can talk about that later, when we can enable the `arrow-body-style` rule.

2022-08-06 08:18 UTC, teoli2003 commented on files/en-us/web/api/htmlcanvaselement/mozfetchasstream/index.md
>  }
I've not consistently changed these and accepted both ways. As you are saying, we can decide this at some point and uniformize then.

2022-08-06 08:19 UTC, teoli2003 commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +  (value, key, listObj) => {
Done.

2022-08-06 08:32 UTC, Josh-Cena commented on files/en-us/web/api/domtokenlist/foreach/index.md
> +    pre.textContent += `(${value} ${key})/${listObj}\n`;
```suggestion
    pre.textContent += `(${value} ${key})/${this}\n`;
```

2022-08-06 08:36 UTC, Josh-Cena approved these changes
I think this is good now!

2022-08-06 08:37 UTC, merged