DO NOT REVIEW – Use arrow functions for anonymous functions
mdn/content pull request #19110
Opened 2022-08-03 14:07 UTC by teoli2003

When possible, it is better to use arrow functions instead of anonymous functions

2022-08-03 15:25 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/loopstart/index.md
> +      (e) => {`Error with decoding audio data: ${e.err}`});
I dunno... `console.error`?

2022-08-03 15:25 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/playbackrate/index.md
> +      (e) => {`Error with decoding audio data: ${e.err}`});
This should be logged?

2022-08-03 15:28 UTC, Josh-Cena commented
GitHub is lagging for me, can't view the rest of the files😥 Will try tomorrow

2022-08-03 16:07 UTC, teoli2003 commented
> GitHub is lagging for me, can't view the rest of the files😥 Will try tomorrow

Same problem for me.

2022-08-03 17:46 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/createmediastreamdestination/index.md
> +      const b = document.querySelector("button");
Yes, but this should be in a follow-up PR. (Else it is a bit of rabbit hole)

2022-08-04 05:14 UTC, Josh-Cena requested changes
Fixing all this code is really disheartening...

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/loop/index.md
> +      (e) => {`Error with decoding audio data: ${e.err}`});
```suggestion
      (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/loopend/index.md
> +      (e) => {`Error with decoding audio data: ${e.err}`});
```suggestion
      (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/loopstart/index.md
> +      (e) => {console.error(`Error with decoding audio data: ${e.err}`)});
```suggestion
      (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiobuffersourcenode/playbackrate/index.md
> +      (e) => {console.error(`Error with decoding audio data: ${e.err}`)});
```suggestion
      (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiocontext/createmediastreamdestination/index.md
> +        const blob = new Blob(chunks, { 'type' : 'audio/ogg; codecs=opus' });
```suggestion
        const blob = new Blob(chunks, { type: 'audio/ogg; codecs=opus' });
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiocontext/resume/index.md
>    if(audioCtx.state === 'running') {
```suggestion
  if (audioCtx.state === 'running') {
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiocontext/resume/index.md
>    } else if(audioCtx.state === 'suspended') {
```suggestion
  } else if (audioCtx.state === 'suspended') {
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiocontext/suspend/index.md
>    if(audioCtx.state === 'running') {
```suggestion
  if (audioCtx.state === 'running') {
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/audiocontext/suspend/index.md
>    } else if(audioCtx.state === 'suspended') {
```suggestion
  } else if (audioCtx.state === 'suspended') {
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorassertionresponse/authenticatordata/index.md
>  });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorassertionresponse/index.md
>  });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorassertionresponse/signature/index.md
>  });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorassertionresponse/userhandle/index.md
>  });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorattestationresponse/attestationobject/index.md
>    });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorattestationresponse/gettransports/index.md
>    });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorattestationresponse/index.md
>    });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorresponse/index.md
>  });
```js
navigator.credentials.get({ publicKey: options })
  .then((credentialInfoAssertion) => {
    const assertionResponse = credentialInfoAssertion.response;
    // send assertion response back to the server
    // to proceed with the control of the credential
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/authenticatorresponse/index.md
>    });
```suggestion
  })
  .catch((err) => console.error(err));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/baseaudiocontext/createconvolver/index.md
> +    }, (e) => {`Error with decoding audio data: ${e.err}`});
```suggestion
    }, (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/baseaudiocontext/createscriptprocessor/index.md
> +    (e) => {`Error with decoding audio data: ${e.err}`});
```suggestion
    (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/baseaudiocontext/decodeaudiodata/index.md
> +      (err) => { console.error(`Error with decoding audio data: ${err.err}`); });
```suggestion
      (err) => console.error(`Error with decoding audio data: ${err.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/bluetooth/requestdevice/index.md
>  });
```suggestion
.catch((error) => console.error(`Something went wrong. ${error}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cache/add/index.md
>      })
```suggestion
    caches.open('v1').then((cache) => cache.add('/sw-test/index.html'))
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cache/match/index.md
>          });
```suggestion
        return caches.open(OFFLINE_CACHE).then((cache) => cache.match(OFFLINE_URL));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cache/put/index.md
>  });
```suggestion
}).catch(() => caches.match('/sw-test/gallery/myLittleVader.jpg'));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cachestorage/has/index.md
>      });
```suggestion
    caches.open('v1').then((cache) => cache.addAll(myAssets));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cachestorage/index.md
>        });
```suggestion
      }).catch(() => caches.match('/sw-test/gallery/myLittleVader.jpg'));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/cachestorage/match/index.md
>        });
```suggestion
      }).catch(() => caches.match('/sw-test/gallery/myLittleVader.jpg'));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/convolvernode/normalize/index.md
> +    }, (e) => {`Error with decoding audio data${e.err}`});
```suggestion
    }, (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 05:14 UTC, Josh-Cena commented on files/en-us/web/api/convolvernode/buffer/index.md
> +    }, (e) => {`Error with decoding audio data${e.err}`});
```suggestion
    }, (e) => console.error(`Error with decoding audio data: ${e.err}`));
```

2022-08-04 06:46 UTC, teoli2003 commented
> Fixing all this code is really disheartening...

Yes, Modernizing JS is a significant project. At least it usually doesn't regress and once it is done, it is done.

2022-08-05 09:05 UTC, Josh-Cena approved these changes
I think this is good now. Let's go!

2022-08-05 09:05 UTC, merged