`cos()` - New CSS functional notation
mdn/content pull request #19119
Opened 2022-08-03 17:32 UTC by ramiy

#### Summary
Document the CSS `cos()` functional notation.

#### Motivation
[Safari/webkit already supports](https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/) this CSS function. [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1190444) will follow soon.

#### Supporting details
https://drafts.csswg.org/css-values/#trig-funcs

#### Related issues

#### Metadata
- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-03 18:03 UTC, estelle commented on files/en-us/web/css/cos/index.md
> +For example, when creating a 100x100 box based on external parameters, in this case `cos(0deg)`. Thus `cos(0deg)` will return `1` making the box `100px` width and `100px` height.
It would be super helpful if this intro gave a reason why we would do this and not simply declare 100px in the first sentence.

2022-08-03 18:08 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +For example, when creating a 100x100 box based on external parameters, in this case `cos(0deg)`. Thus `cos(0deg)` will return `1` making the box `100px` width and `100px` height.
What wording do you suggest using instead?

2022-08-03 20:29 UTC, estelle commented on files/en-us/web/css/cos/index.md
> +For example, when creating a 100x100 box based on external parameters, in this case `cos(0deg)`. Thus `cos(0deg)` will return `1` making the box `100px` width and `100px` height.
Maybe if we switch the example to one that explains a more concrete use case, it will help.
How about if we answer this question: https://stackoverflow.com/questions/54874997/maintain-width-and-height-of-rotated-square-divs-in-css-grid-responsive-solutio/54875824#54875824

> For example, if you rotate a 100x100 square 45 degrees, the diamond it creates will be wider and taller than the original square. To shrink the diamond into the box allotted for the original square, you would have to scale the diamond using this formula: height = width = 100px / cos(45deg) = 100 / 0.707. You need to also adjust the transform-origin and add a small translation to correct the position:

2022-08-04 09:28 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +For example, when creating a 100x100 box based on external parameters, in this case `cos(0deg)`. Thus `cos(0deg)` will return `1` making the box `100px` width and `100px` height.
Example updated. Please review.

2022-08-04 18:10 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +For example, when creating a 100x100 box based on external parameters, in this case `cos(0deg)`. Thus `cos(0deg)` will return `1` making the box `100px` width and `100px` height.
@estelle

2022-08-08 10:31 UTC, ramiy commented
@estelle @teoli2003

2022-08-16 19:28 UTC, teoli2003 commented
Sorry, for the non-response here; I'm a bit in a hurry with a few things. But I have not forgotten you.

2022-08-17 08:59 UTC, teoli2003 requested changes
This is great, we are very close to be able to merge this!

2022-08-17 08:59 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +- `A`
```suggestion
The `cos(angle)` function accepts only one expression as its argument.

- `angle`
```

2022-08-17 08:59 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +width: calc( cos(e / 2) * 100px );
Do we need the spaces before and after the parenthesis? I don't think so (the spaces between some operators are mandatory, though):
```suggestion
width: calc(cos(45deg) * 100px);
width: calc(cos(0.125turn) * 100px);
width: calc(cos(0.785398163rad) * 100px);

/* Single <number> values */
width: calc(cos(63.673) * 100px);
width: calc(cos(2 * 0.125) * 100px);

/* Other values */
width: calc(cos(pi) * 100px);
width: calc(cos(e / 2) * 100px);
```

2022-08-17 08:59 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +  - : The argument specified as a {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. If `A` is `infinite`, the result is `NaN`.
```suggestion
  - : A {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. If `angle` is `+Infinity`, `-Infinity`, or `NaN`, the result is `NaN`.
```

2022-08-17 08:59 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +### Keep rotated element size
If there is only an example, we don't need a level-3 heading.
```suggestion
## Example

The `cos()` function can be used to keep the size of a rotated box.
```

2022-08-17 09:47 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +### Keep rotated element size
This change will require updating `{{EmbedLiveSample('keep_rotated_element_size', '100%', '200px')}}` to `{{EmbedLiveSample('example', '100%', '200px')}}`

2022-08-17 09:48 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +- `A`
This is not correct, the argument can be either an angle or a number. we can change this to `value` or `arg`.

2022-08-17 09:49 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +### Keep rotated element size
Yes.

2022-08-17 09:51 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +- `A`
I also see that [calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#syntax) is using `expression`.

2022-08-17 10:19 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +- `A`
This is not the CSS type, the number is a mathematical angle.

2022-08-17 10:21 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +  - : The argument specified as a {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. If `A` is `infinite`, the result is `NaN`.
We also need to clarify the unit (radians, likely) the `<number>` represents. Obvious for mathematicians, not necessary for web developers.

2022-08-17 10:44 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +- `A`
I know, but its confusing.

2022-08-17 12:06 UTC, ramiy commented on files/en-us/web/css/cos/index.md
> +  - : The argument specified as a {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. If `A` is `infinite`, the result is `NaN`.
I added the following:

When specifying unitless numbers they are interpreted as a number of radians, representing an `<angle>`.

2022-08-17 12:18 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +  - : The argument specified as a {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. When specifiing unitless numbers they are interpreted as a number of radians, representing an {{css
```suggestion
  - : The argument specified as a {{cssxref("&lt;number&gt;")}} or an {{cssxref("&lt;angle&gt;")}}. When specifying unitless numbers they are interpreted as a number of radians, representing an {{cssxref("&lt;angle&gt;")}}. If `A` is `infinity`, `-infinity`, or `NaN`, the result is `NaN`.
```

2022-08-17 12:23 UTC, teoli2003 commented on files/en-us/web/css/cos/index.md
> +The `cos(angle)` function accepts only one expression as its argument.
We don't use the term _argument_ but the term _parameter_ on MDN.

2022-08-17 13:59 UTC, teoli2003 approved these changes
👍

2022-08-17 13:59 UTC, merged

2022-08-17 13:59 UTC, teoli2003 commented
Thank you!