CSS Math Functions - Group items and add headings
mdn/content pull request #19122
Opened 2022-08-03 19:18 UTC by ramiy

#### Summary
The [current list of CSS math functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions) is a long list of functions that make no sense. This PR groups similar functions and adds sub-headings, based on [the spec](https://www.w3.org/TR/css-values-4/#math) headings.

#### Motivation
Simplify the navigation and group similar functions by topic.

#### Supporting details
Spec: https://www.w3.org/TR/css-values-4/#math

10. Mathematical Expressions
10.1. Basic Arithmetic: `calc()`
10.2. Comparison Functions: `min()`, `max()`, and `clamp()`
10.3. Stepped Value Functions: `round()`, `mod()`, and `rem()`
10.4. Trigonometric Functions: `sin()`, `cos()`, `tan()`, `asin()`, `acos()`, `atan()`, and `atan2()`
10.5. Exponential Functions: `pow()`, `sqrt()`, `hypot()`, `log()`, `exp()`
10.6. Sign-Related Functions: `abs()`, `sign()`
10.7. Numeric Constants: `e`, `pi`

#### Metadata
- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-03 19:52 UTC, teoli2003 requested changes

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Basic Arithmetic
We use _sentence case_ in headings.

```suggestion
### Basic arithmetic
```

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Comparison Functions
```suggestion
### Comparison functions
```

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Stepped Value Functions
```suggestion
### Stepped value functions
```

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Trigonometric Functions
```suggestion
### Trigonometric functions
```

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Exponential Functions
```suggestion
### Exponential functions
```

2022-08-03 19:52 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Sign-Related Functions
```suggestion
### Sign-related functions
```

2022-08-03 19:53 UTC, teoli2003 approved these changes

2022-08-03 19:53 UTC, teoli2003 commented
Good idea. Thank you very much!

2022-08-03 19:55 UTC, merged

2022-08-03 20:31 UTC, estelle commented on files/en-us/web/css/css_functions/index.md
> +### Sign-related functions
is this supposed to be sine, sin, or sign?

2022-08-04 04:39 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +### Sign-related functions
Sign is correct. This is about the absolute value and sign function. Not the sine function (`sin()`).