SVGStyleElement.media docs (plus other minor fixes)
mdn/content pull request #19172
Opened 2022-08-05 02:08 UTC by hamishwillee

This adds missing docs for the `SVGStyleElement.media` element. It is part of the tidy I am doing for https://github.com/mdn/content/issues/18775

Note this is in draft temporarily while I explore whether the setter is supposed to work in:

2022-08-05 03:48 UTC, hamishwillee commented on files/en-us/web/api/svgstyleelement/media/index.md
> +{{EmbedLiveSample("Disabling a style defined in the SVG")}}
```suggestion
{{EmbedLiveSample("Examples")}}
```

2022-08-08 06:07 UTC, hamishwillee commented
@teoli2003 Do you think you might be able to review this?

2022-08-09 07:36 UTC, teoli2003 requested changes
A few nits and bikeshedding changes… Probably more a matter of personal taste.

One question: you use `innerText`. I usually use `textContent`. I have no idea why I do this: any specific reason why you use the former?  (I think `innerText` is defined on `Element` and `textContent` on `Node`, but I don't know of any other differences.

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/disabled/index.md
>  const svg = document.getElementsByTagName("svg")[0];
Nit: (I don't like the `[0]`) so using `querySelector` as used below simplifies this.
```suggestion
const svg = document.querySelector("svg");
```

(I'm not annoyed by `getElementById()` as there is only one value returned.

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +  - : A string corresponding to the [`title` attribute](/en-US/docs/Web/SVG/Element/style#title) of the given element.
```suggestion
  - : A string corresponding to the [`title` attribute](/en-US/docs/Web/SVG/Element/style#title) of the given element.
```
```suggestion
  - : A string corresponding to the [`title`](/en-US/docs/Web/SVG/Element/style#title) attribute of the given element.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +To dynamically create an SVG style element (`SVGStyleElement`) you need to use [`Document.createElementNS()`](/en-US/docs/Web/API/Document/createElementNS), specifying a `style` element in the SVG na
```suggestion
To dynamically create an SVG style element ([`SVGStyleElement`](/en-US/docs/Web/API/SVGStyleElement)), you need to use [`Document.createElementNS()`](/en-US/docs/Web/API/Document/createElementNS), specifying a `style` element in the SVG namespace.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +> **Note:** [`Document.createElement()`](/en-US/docs/Web/API/Document/createElement) can't be used to create SVG style elements (it returns an `HTMLStyleElement`).
nit
```suggestion
> **Note:** [`Document.createElement()`](/en-US/docs/Web/API/Document/createElement) can't be used to create SVG style elements (it returns an [`HTMLStyleElement`](/en-US/docs/Web/API/HTMLStyleElement)).
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +const svg = document.getElementsByTagName("svg")[0];
nit
```suggestion
const svg = document.querySelector("svg");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +const style = svg.getElementsByTagName("style")[0];
```suggestion
const svg = document.querySelector("svg");
const style = svg.querySelector("style");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +const svg = document.getElementsByTagName("svg")[0];
```suggestion
const svg = document.querySelector("svg");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +The HTML contains an SVG definition for a [`<circle>`](/en-US/docs/Web/SVG/Element/circle) with a [`<style>`](/en-US/docs/Web/SVG/Element/style) element, along with an [HTML `<button>`](/en-US/docs/W
```suggestion
The HTML contains an SVG definition for a [`<circle>`](/en-US/docs/Web/SVG/Element/circle) with a [`<style>`](/en-US/docs/Web/SVG/Element/style) element, along with an HTML [`<button>`](/en-US/docs/Web/HTML/Element/button) element that will be used to enable and disable the style, and an HTML [`<textarea>`](/en-US/docs/Web/HTML/Element/button) element for logging the property values.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +const svg = document.getElementsByTagName("svg")[0];
```suggestion
const svg = document.querySelector("svg");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +  log.value += `style.media: ${style.media} (frame width: ${window.innerWidth})\n`; // 'all' by default
```suggestion
  log.value = `style.media: ${style.media} (frame width: ${window.innerWidth})\n`; // 'all' by default
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/index.md
> +   button.innerText = buttonText;
I think we can group these two lines without losing readability:
```suggestion
   button.innerText = style.disabled ? 'Enable' : 'Disable';
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/disabled/index.md
>  ```js
Line 69, I think we can group both lines in one, without losing readability:

```
   button.innerText = style.disabled ? 'Enable' : 'Disable';
```

(Sorry, I hate that GitHub doesn't allow us to comment/suggest anywhere in a file).

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/media/index.md
> +The **`SVGStyleElement.media`** property is a media query string corresponding to the [`media` attribute](/en-US/docs/Web/SVG/Element/style#media) of the given SVG style element.
```suggestion
The **`SVGStyleElement.media`** property is a media query string corresponding to the [`media`](/en-US/docs/Web/SVG/Element/style#media) attribute of the given SVG style element.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/media/index.md
> +For example `"screen, print"`, or `all` (the default).
```suggestion
For example `"screen, print"`, or `"all"` (the default).
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/media/index.md
> +The value is initialized with the string specified in the corresponding style's [`media` attribute](/en-US/docs/Web/SVG/Element/style#media).
```suggestion
The value is initialized with the string specified in the corresponding style's [`media`](/en-US/docs/Web/SVG/Element/style#media) attribute.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/media/index.md
> +on the media query "all and (min-width: 600px)".
```suggestion
The HTML contains an SVG definition for a [`<circle>`](/en-US/docs/Web/SVG/Element/circle) with a [`<style>`](/en-US/docs/Web/SVG/Element/style) element that is conditional on the media query `"all and (min-width: 600px)"`.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/media/index.md
> +const svg = document.getElementsByTagName("svg")[0];
```suggestion
const svg = document.querySelector("svg");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/sheet/index.md
> +const svg = document.getElementsByTagName("svg")[0];
```suggestion
const svg = document.querySelector("svg");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/title/index.md
> +The **`SVGStyleElement.title`** property is is a string corresponding to the [`title` attribute](/en-US/docs/Web/SVG/Element/style#title) of the given SVG style element.
```suggestion
The **`SVGStyleElement.title`** property is is a string corresponding to the [`title`](/en-US/docs/Web/SVG/Element/style#title) attribute of the given SVG style element.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/title/index.md
> +The value is initialized with the string specified in the corresponding style's [`title` attribute](/en-US/docs/Web/SVG/Element/style#title).
```suggestion
The value is initialized with the string specified in the corresponding style's [`title`](/en-US/docs/Web/SVG/Element/style#title) attribute.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/title/index.md
> +const style = svg.getElementsByTagName("style")[0];
```suggestion
const svg = document.querySelector("svg");
const style = svg.querySelector("style");
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/api/svgstyleelement/type/index.md
> +The value reflects the associated [SVG `<style>` element's `type` attribute](/en-US/docs/Web/SVG/Element/style#type).
```suggestion
The value reflects the associated SVG `<style>` element's [`type`](/en-US/docs/Web/SVG/Element/style#type) attribute.
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/svg/element/style/index.md
>      *Value type*: [**\<string>**](/en-US/docs/Web/SVG/Content_type#string); *Default value*: *none*; *Animatable*: **no**
```suggestion
    *Value type*: [**`<string>`**](/en-US/docs/Web/SVG/Content_type#string); *Default value*: *none*; *Animatable*: **no**
```

2022-08-09 07:36 UTC, teoli2003 commented on files/en-us/web/svg/element/style/index.md
>      *Value type*: [**\<string>**](/en-US/docs/Web/SVG/Content_type#string); *Default value*: `all`; *Animatable*: **no**
```suggestion
    *Value type*: [**`<string>`**](/en-US/docs/Web/SVG/Content_type#string); *Default value*: `all`; *Animatable*: **no**
```

2022-08-12 03:54 UTC, hamishwillee commented on files/en-us/web/api/svgstyleelement/disabled/index.md
>  ```js
SOunds good. Changed all instances of this, and using textContent.

2022-08-12 04:04 UTC, hamishwillee commented on files/en-us/web/api/svgstyleelement/index.md
> +const svg = document.getElementsByTagName("svg")[0];
Just FMI are you suggesting this is better because:
- the code is easier to read?
- We only one one tag and `getElementsByTagName()` returns all of them?
- The code is static, so we only need the static value and not the dynamic list from `getElementsByTagName()`?
- `querySelector("svg")` is a better and more flexible API they users need to get used to?

I'm happy with this, just wondering your justification. My reason for using `getElementsByTagName()` was simply that I wanted to make it obvious in this case I was searching for the svg tag.

2022-08-12 04:33 UTC, hamishwillee commented
Hi @teoli2003 

> you use innerText. I usually use textContent. I have no idea why I do this: any specific reason why you use the former? (I think innerText is defined on Element and textContent on Node, but I don't know of any other differences.

There are significant differences when _reading_ a value, but not much as far as I can tell when writing - at least [according to our docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext).
I didn't really think on this. For consistency I have changed all the changes here to use textContent.

Thanks for your detailed review. Should be good to look at again now.

2022-08-12 06:10 UTC, teoli2003 approved these changes
👍

2022-08-12 06:11 UTC, merged