DO NOT REVIEW Use arrow functions for anonymous functions where possible (part #6)
mdn/content pull request #19186
Opened 2022-08-05 09:50 UTC by teoli2003

Arrow functions are shorter and easier to read (but doesn't bind `this`).

2022-08-05 13:19 UTC, Josh-Cena commented
Waaa, 170 files...

2022-08-05 13:31 UTC, teoli2003 commented
Sorry, I mixed my count. I try to stay at 100.

2022-08-05 13:49 UTC, Josh-Cena requested changes
Some of the suggested changes apply to a bunch of files; worth a search & replace

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +  return [ { supportedMethods: 'https://example.com/pay' } ];
```suggestion
  return [{ supportedMethods: 'https://example.com/pay' }];
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
>            })
Here's what Prettier says:

```js
new PaymentRequest(buildSupportedPaymentMethodData(), {
  total: { label: "Stub", amount: { currency: "USD", value: "0.01" } },
})
  .canMakePayment()
  .then((result) => {
    if (result) {
      // Real payment request
      const request = new PaymentRequest(
        buildSupportedPaymentMethodData(),
        checkoutObject,
      );
      request.show().then((paymentResponse) => {
        // Here we would process the payment.
        paymentResponse.complete("success").then(() => {
          // Finish handling payment
        });
      });
    }
  });
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                   buildShoppingCartDetails());
Plz don't align by spaces. Just make a new line.

```js
let request = new PaymentRequest(
  buildSupportedPaymentMethodNames(),
  buildShoppingCartDetails(),
);
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                   buildShoppingCartDetails());
Ditto; put the arguments on separate lines

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +   { total:
Putting the property name on the same line as the opening brace is weird. See my suggestion for formatting above

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/performanceelementtiming/element/index.md
> +  const entries = list.getEntries().forEach((entry) => {
```suggestion
  list.getEntries().forEach((entry) => {
```

Same goes for every occurrence below. You can also use `for...of` if you wish.

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/performanceobserverentrylist/getentries/index.md
> +observe_all.observe({ entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server'] });
```suggestion
observe_all.observe({
  entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server'],
});
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach((entry) => print_perf_entry(perfEntries[i]));
```suggestion
  perfEntries.forEach((entry) => print_perf_entry(entry));
```

Or:

```suggestion
  perfEntries.forEach(print_perf_entry);
```

No strong opinions about either. Just need to sync your choice with all other occurrences.

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +observe_all.observe({ entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server'] });
```suggestion
observe_all.observe({
  entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server'],
});
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/permissions/index.md
> +navigator.permissions.query({name:'geolocation'}).then((result) => {
```suggestion
navigator.permissions.query({ name: 'geolocation' }).then((result) => {
```

Also needs to be ported to occurrences below

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
> +    if (connection !== newConnection && connection?.state !== 'closed') {
Note: testing for `condition`'s truthiness is necessary here. Otherwise `undefined` will pass this test.

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
> +    this.onmessage = (message) => {
This `this` is essentially `window` I think. Better make that obvious.

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/publickeycredential/isuserverifyingplatformauthenticatoravailable/index.md
> +    if (available){
```suggestion
    if (available) {
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/pushevent/data/index.md
> +    clients?.openWindow('https://example.blog.com/2015/03/04/something-new.html');
```suggestion
    clients.openWindow?.('https://example.blog.com/2015/03/04/something-new.html');
```

Also, support seems good; do we even need this optional test?

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/pushevent/index.md
> +  const data = event.data?.json() || {};
```suggestion
  const data = event.data?.json() ?? {};
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/pushevent/index.md
> +    clients?.openWindow('https://example.blog.com/2015/03/04/something-new.html');
Same here

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/queuemicrotask/index.md
> +    fetch(url).then(function (res) => res.arrayBuffer()).then(function (data) => {
What's this? 😄

```suggestion
    fetch(url).then(res) => res.arrayBuffer()).then((data) => {
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/reporterror/index.md
> +    console.error(error.filename);
```suggestion
  console.error(error.filename);
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/request/blob/index.md
> +const myBlob = new Blob([JSON.stringify(obj, null, 2)], { type : 'application/json' });
```suggestion
const myBlob = new Blob(
  [JSON.stringify(obj, null, 2)],
  { type : 'application/json' },
);
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/request/blob/index.md
>   });
```suggestion
  body: myBlob,
});
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/request/cache/index.md
> +    if (dt < (Date.now() - 86_400_000)) {
```suggestion
    if (dt < Date.now() - 86_400_000) {
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/request/cache/index.md
> +    if (dt < (Date.now() - 300_000)) // If it's older than 5 minutes
```suggestion
    if (dt < Date.now() - 300_000) // If it's older than 5 minutes
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/serviceworker/index.md
> +    }).catch ((error) => {
```suggestion
    }).catch((error) => {
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkercontainer/getregistration/index.md
> +  if (registration){
```suggestion
  if (registration) {
```

2022-08-05 13:49 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkercontainer/register/index.md
> +    console.error(`Service worker registration failed: ${error});
```suggestion
    console.error(`Service worker registration failed: ${error}`);
```

2022-08-05 17:08 UTC, teoli2003 commented on files/en-us/web/api/permissionstatus/state/index.md
> +    console.log(`geolocation permission status has changed to ${this.state}`);
Honestly, it may work. But I don't like to use `this` outside classes (and a few special cases).
Good catch!
```suggestion
    console.log(`geolocation permission status has changed to ${permissionStatus.state}`);
```

2022-08-05 17:16 UTC, teoli2003 commented on files/en-us/web/api/queuemicrotask/index.md
> +MyElement.prototype.loadData = function (url) => {
```suggestion
MyElement.prototype.loadData = function (url) {
```

2022-08-05 17:20 UTC, teoli2003 commented on files/en-us/web/api/queuemicrotask/index.md
> +    fetch(url).then(function (res) => res.arrayBuffer()).then(function (data) => {
I don't know what happened here.

2022-08-06 13:28 UTC, lionralfs commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +  .catch((ex1) => {
Might as well rename this, right?

```suggestion
  .catch((err) => {
```

2022-08-06 13:28 UTC, lionralfs commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach((entry) => print_perf_entry(perfEntries[i]));
Could also do:

```suggestion
  perfEntries.forEach(print_perf_entry);
```

Not as bad for a unary function as the common pitfall `.map(parseInt)`.

2022-08-06 13:28 UTC, lionralfs commented on files/en-us/web/api/rtcpeerconnection/setconfiguration/index.md
>  })
Perhaps:

```suggestion
myPeerConnection.createOffer({"iceRestart": true}).then(
  (offer) => myPeerConnection.setLocalDescription(offer)
)
```

Same for the next few cases.

2022-08-06 13:30 UTC, Josh-Cena commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach((entry) => print_perf_entry(perfEntries[i]));
I specifically removed it (see edit history) because it's a potential refactoring hazard and "point-free" style isn't always the most readable.

2022-08-06 13:50 UTC, lionralfs commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach((entry) => print_perf_entry(perfEntries[i]));
Oh. Didn't notice the edit history. But yeah, I can live with that

2022-08-07 06:16 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
>            })
I used this.

2022-08-07 06:18 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                   buildShoppingCartDetails());
Done.

2022-08-07 06:18 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                   buildShoppingCartDetails());
Done

2022-08-07 06:26 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +   { total:
Fixed

2022-08-07 06:36 UTC, teoli2003 commented on files/en-us/web/api/performanceelementtiming/element/index.md
> +  const entries = list.getEntries().forEach((entry) => {
Done

2022-08-07 06:39 UTC, teoli2003 commented on files/en-us/web/api/permissions/index.md
> +navigator.permissions.query({name:'geolocation'}).then((result) => {
Fixed

2022-08-07 06:41 UTC, teoli2003 commented on files/en-us/web/api/presentation_api/index.md
> +    if (connection !== newConnection && connection?.state !== 'closed') {
Reverted

2022-08-07 06:43 UTC, teoli2003 commented on files/en-us/web/api/presentation_api/index.md
> +    this.onmessage = (message) => {
Fixed

2022-08-07 07:08 UTC, teoli2003 commented on files/en-us/web/api/pushevent/data/index.md
> +    clients?.openWindow('https://example.blog.com/2015/03/04/something-new.html');
Yes, done

2022-08-07 07:08 UTC, teoli2003 commented on files/en-us/web/api/pushevent/index.md
> +    clients?.openWindow('https://example.blog.com/2015/03/04/something-new.html');
Done

2022-08-07 07:18 UTC, teoli2003 commented
There would be many more improvement to these pages, but I think this will be for another pass…

2022-08-07 16:28 UTC, lionralfs commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach(print_perf_entry);
I thought we didn't wanna use point free style, see https://github.com/mdn/content/pull/19186#discussion_r939528840

Also still needs to be synced to other occurences (which still use `prefEntries[i]`)

2022-08-08 06:00 UTC, teoli2003 commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach(print_perf_entry);
Let's be coherent.

2022-08-08 06:06 UTC, teoli2003 commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +  perfEntries.forEach(print_perf_entry);
I fixed the 4 files, with an explicit parameter.

2022-08-08 06:07 UTC, teoli2003 commented
This is good for another (hopefully last) pass.

2022-08-08 06:26 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                 buildShoppingCartDetails());
Let's fix the indent here

2022-08-08 06:26 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +}))
```suggestion
new PaymentRequest(supportedPaymentMethods, { 
  total: { label: 'Stub', amount: { currency: 'USD', value: '0.01' } }
})
```

2022-08-08 06:27 UTC, Josh-Cena commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +  });
```suggestion
  });
```

2022-08-08 06:29 UTC, Josh-Cena commented on files/en-us/web/api/performanceobserverentrylist/getentriesbyname/index.md
> +    perfEntries.forEach((entry) => print_perf_entry(entry));
```suggestion
  perfEntries.forEach((entry) => print_perf_entry(entry));
```

2022-08-08 06:31 UTC, Josh-Cena commented on files/en-us/web/api/permissionstatus/change_event/index.md
>    };
This uses `this`

2022-08-08 06:31 UTC, Josh-Cena commented on files/en-us/web/api/permissionstatus/index.md
>    };
This uses `this`

2022-08-08 06:33 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
> +    availability.onchange = () => { handleAvailabilityChange(this.value); };
This uses `this`

2022-08-08 06:33 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
> +    if (connection && connection !== newConnection && connection.state !== 'closed' {
Missing `)`

2022-08-08 06:37 UTC, Josh-Cena commented on files/en-us/web/api/pushsubscriptionoptions/applicationserverkey/index.md
>  ```css
```suggestion
```js
```

2022-08-08 06:38 UTC, Josh-Cena commented on files/en-us/web/api/queuemicrotask/index.md
>        .catch((e) => setTimeout(() => { throw e; })); // report exceptions
This is a polyfill. Do we need this?

2022-08-08 06:39 UTC, Josh-Cena commented on files/en-us/web/api/report/index.md
> +    report.body.forEach((keyValue, key) => {
This is a for...in enumeration and is not convertible like this

2022-08-08 06:42 UTC, Josh-Cena commented on files/en-us/web/api/rtcpeerconnection/setremotedescription/index.md
>    });
```suggestion
  .then(() => createMyStream());
```

2022-08-08 06:44 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkercontainer/index.md
> +    console.log(`This page is now controlled by: ${navigator.serviceWorker.controller}`);
`controller` is an object

2022-08-08 06:46 UTC, teoli2003 commented on files/en-us/web/api/payment_request_api/using_the_payment_request_api/index.md
> +                                 buildShoppingCartDetails());
Fixed

2022-08-08 06:48 UTC, teoli2003 commented on files/en-us/web/api/permissionstatus/change_event/index.md
>    };
Fixed

2022-08-08 06:48 UTC, teoli2003 commented on files/en-us/web/api/permissionstatus/index.md
>    };
Fixed

2022-08-08 07:02 UTC, teoli2003 commented on files/en-us/web/api/presentation_api/index.md
> +    availability.onchange = () => { handleAvailabilityChange(this.value); };
Fixed

2022-08-08 07:02 UTC, teoli2003 commented on files/en-us/web/api/presentation_api/index.md
> +    if (connection && connection !== newConnection && connection.state !== 'closed' {
Fixed

2022-08-08 07:05 UTC, teoli2003 commented on files/en-us/web/api/queuemicrotask/index.md
>        .catch((e) => setTimeout(() => { throw e; })); // report exceptions
Polyfill removed (we don't host polyfill as we can't maintain them). We link to them.

2022-08-08 07:10 UTC, teoli2003 commented on files/en-us/web/api/serviceworkercontainer/index.md
> +    console.log(`This page is now controlled by: ${navigator.serviceWorker.controller}`);
Fixed

2022-08-08 07:13 UTC, teoli2003 commented on files/en-us/web/api/report/index.md
> +    report.body.forEach((keyValue, key) => {
I kept the for...in (with const)

2022-08-08 09:54 UTC, Josh-Cena commented on files/en-us/web/api/performance_timeline/using_performance_timeline/index.md
> +    const perfEntries = list.getEntries();
`perfEntries` is re-assigned below

2022-08-08 09:59 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
>  ```html
```suggestion
In the `controller.html` file:

```html
```

2022-08-08 10:02 UTC, Josh-Cena commented on files/en-us/web/api/pushmanager/register/index.md
> +  console.error(`Error getting a new endpoint: ${JSON.stringify(e)}`);
Really weird to stringify here: nothing on the error is enumerable so it should log nothing. Let's just do this:

```suggestion
  console.error(`Error getting a new endpoint: ${e.error}`);
```

2022-08-08 10:04 UTC, Josh-Cena commented on files/en-us/web/api/pushmanager/unregister/index.md
> +  console.error(`Error unregistering the endpoint: ${JSON.stringify(e)}`);
Same as above

2022-08-08 10:07 UTC, Josh-Cena commented on files/en-us/web/api/report/index.md
> +    });
```suggestion
    }
```

2022-08-08 10:07 UTC, Josh-Cena commented on files/en-us/web/api/report/index.md
> +The `reports` parameter contains an array of all the reports in the observer's report queue. We loop over each report using a basic [`for...of`](/en-US/docs/Web/JavaScript/Reference/Statements/for...
Not a for...of?

2022-08-08 10:09 UTC, Josh-Cena commented on files/en-us/web/api/rtcpeerconnection/addtrack/index.md
>    })
```suggestion
  .then(() => navigator.mediaDevices.getUserMedia(mediaConstraints))
```

2022-08-08 10:10 UTC, Josh-Cena commented on files/en-us/web/api/rtcpeerconnection/createanswer/index.md
>  })
```suggestion
pc.createAnswer().then((answer) => pc.setLocalDescription(answer))
```

2022-08-08 10:10 UTC, Josh-Cena commented on files/en-us/web/api/rtcpeerconnection/createoffer/index.md
>    })
```suggestion
  myPeerConnection.createOffer()
    .then((offer) => myPeerConnection.setLocalDescription(offer))
```

2022-08-08 10:12 UTC, Josh-Cena commented on files/en-us/web/api/rtcpeerconnection/setremotedescription/index.md
>  });
```suggestion
myPeerConnection
  .setRemoteDescription(description)
  .then(() => createMyStream());
```

2022-08-08 10:13 UTC, Josh-Cena commented on files/en-us/web/api/rtcrtpsender/replacetrack/index.md
> +      console.log(`Found sender: ${sender}`);
This is an object

2022-08-08 10:16 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkercontainer/index.md
> +    console.log(`Service worker registration succeeded: ${registration}`);
Revert this?

2022-08-08 10:17 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkercontainer/register/index.md
> +    console.log(`Service worker registration succeeded: ${registration}`);
Same here: I'm not sure what `registration` serializes to but I suppose not something as great as an expandable object

2022-08-08 10:39 UTC, teoli2003 commented on files/en-us/web/api/report/index.md
> +The `reports` parameter contains an array of all the reports in the observer's report queue. We loop over each report using a basic [`for...of`](/en-US/docs/Web/JavaScript/Reference/Statements/for...
```suggestion
The `reports` parameter contains an array of all the reports in the observer's report queue. We loop over each report using a [`forEach()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) loop, then iterate over each entry of in the report's body using a [`for...in`](/en-US/docs/Web/JavaScript/Reference/Statements/for...in) structure, displaying each key/value pair inside a list item.
```

2022-08-08 13:04 UTC, teoli2003 commented
I think I have handled all review comments here.

2022-08-08 13:24 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
>      if (!!presId) {
```suggestion
    if (presId) {
```

2022-08-08 13:26 UTC, Josh-Cena commented on files/en-us/web/api/presentation_api/index.md
> +  list.connections.map((connection) => {
```suggestion
  list.connections.forEach((connection) => {
```

2022-08-08 14:48 UTC, Josh-Cena approved these changes
Yup—I was just AFK for dinner (at 10pm). All boxes are ticked for me.

2022-08-08 14:51 UTC, Josh-Cena commented
Tangentially related @teoli2003 I noticed when you click "commit suggestion" in the GitHub UI these days the change is not always committed and it sometimes is just silently marked as resolved without changes. I've caught that a few times.

2022-08-08 14:51 UTC, merged