Use arrow functions for anonymous functions where possible (part #7)
mdn/content pull request #19190
Opened 2022-08-05 12:50 UTC by teoli2003

Arrow functions are shorter and easier to read (but don't bind `this`).

2022-08-05 13:55 UTC, Josh-Cena requested changes
This one is ez!

2022-08-05 13:55 UTC, Josh-Cena commented on files/en-us/web/api/setinterval/index.md
>  (function loop(){
```suggestion
(function loop() {
```

2022-08-05 13:55 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
> +setTimeout(function () {myArray.myMethod()}, 2.0*1000); // prints "zero,one,two" after 2 seconds
```suggestion
setTimeout(function () {
  myArray.myMethod();
}, 2.0 * 1000); // prints "zero,one,two" after 2 seconds
```

2022-08-05 13:55 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
> +setTimeout(function () {myArray.myMethod('1')}, 2.5*1000); // prints "one" after 2.5 seconds
```suggestion
setTimeout(function () {
  myArray.myMethod('1')'
}, 2.5 * 1000); // prints "one" after 2.5 seconds
```

2022-08-05 13:55 UTC, Josh-Cena commented on files/en-us/web/api/storagemanager/persist/index.md
> +navigator.storage.persist().then((persistent) => { /* … */ })
```suggestion
navigator.storage.persist()
```

2022-08-05 13:55 UTC, Josh-Cena commented on files/en-us/web/api/storagemanager/persisted/index.md
> +navigator.storage.persisted().then((persistent) => { /* … */ })
```suggestion
navigator.storage.persisted()
```

2022-08-05 17:05 UTC, teoli2003 commented on files/en-us/web/api/setinterval/index.md
>      alert(arguments.length > 0 ? this[sProperty] : this);
Good catch, let's use myArray instead of this.
```suggestion
    alert(arguments.length > 0 ? myArray[sProperty] : myArray);
```

2022-08-05 17:07 UTC, teoli2003 commented
> This one is ez!

Yes, there are plenty of easy cases. I'm happy because overall, we have made a great deal of progress modernizing our JS snippets.

2022-08-06 07:58 UTC, teoli2003 commented
@Josh-Cena When you have time, can you have a last look here? I think I fixed all your comments. (I'm trying to avoid keeping these PRs open too long, as I hate to perform merges)

Thank you!

2022-08-06 08:22 UTC, Josh-Cena commented on files/en-us/web/api/setinterval/index.md
>  };
Unfortunately this defeats the purpose of this example, which is to demonstrate how `setTimeout` may change the `this` context. Let's revert this change.

2022-08-06 08:23 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
>  };
Same here: I suggest reverting it.

2022-08-06 08:23 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
> +setTimeout(function () {
This can actually be an arrow! Same for below

2022-08-06 08:23 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
> +const myBoundMethod = ((sProperty) => {
This should be reverted

2022-08-06 08:24 UTC, Josh-Cena commented on files/en-us/web/api/sourcebuffer/index.md
> +     console.log(mediaSource.readyState); // ended
```suggestion
      console.log(mediaSource.readyState); // ended
```

2022-08-06 12:57 UTC, lionralfs commented on files/en-us/web/api/serviceworkerglobalscope/activate_event/index.md
> +      if (cacheAllowlist.includes(cacheName)) {
```suggestion
      if (!cacheAllowlist.includes(cacheName)) {
```

2022-08-08 06:14 UTC, teoli2003 commented on files/en-us/web/api/serviceworkerglobalscope/fetch_event/index.md
> +        console.log(`Found response in cache: ${response}`);
That's a good point. I've been over-zealous with variadic parameters, I think.

2022-08-08 06:29 UTC, teoli2003 commented on files/en-us/web/api/setinterval/index.md
>  };
Done

2022-08-08 06:29 UTC, teoli2003 commented on files/en-us/web/api/settimeout/index.md
>  };
Done

2022-08-08 07:33 UTC, teoli2003 commented on files/en-us/web/api/settimeout/index.md
> +setTimeout(function () {
Yes, but this is what is explained just below at line 192, isn't it?

2022-08-08 07:34 UTC, teoli2003 commented on files/en-us/web/api/settimeout/index.md
> +const myBoundMethod = ((sProperty) => {
Done

2022-08-08 07:34 UTC, teoli2003 commented
@josh-cena: I think I fixed all the comments (except one where I think it shouldn't).

2022-08-08 09:31 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkerregistration/index.md
> +      console.log(`A new service worker is being installed: ${installingWorker}`);
`installingWorker` is an object

2022-08-08 09:35 UTC, Josh-Cena commented on files/en-us/web/api/settimeout/index.md
> +  myArray.myMethod('1')'
```suggestion
  myArray.myMethod('1');
```

2022-08-08 14:52 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkerglobalscope/fetch_event/index.md
> +        console.log('Response from network is: ', response);
```suggestion
        console.log('Response from network is:', response);
```

2022-08-08 14:53 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkerglobalscope/fetch_event/index.md
> +        console.log('Found response in cache: ', response);
```suggestion
        console.log('Found response in cache:', response);
```

2022-08-08 14:53 UTC, Josh-Cena commented on files/en-us/web/api/serviceworkerregistration/index.md
> +      console.log(A new service worker is being installed:', installingWorker);
```suggestion
      console.log('A new service worker is being installed:', installingWorker);
```

2022-08-08 14:54 UTC, Josh-Cena approved these changes
LGTM!

2022-08-08 14:54 UTC, merged