fix: add missing alt
mdn/content pull request #19205
Opened 2022-08-05 22:17 UTC by muchafm

Here are some propositions for some missing alt descriptions

2022-08-06 00:28 UTC, estelle requested changes
Thank you for adding alt attributes. I had some feedback for some pages; didn't comment on each, rather just the first one in each page.

2022-08-06 00:28 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the recalculate style step" src="recalculate-style.png" />
```suggestion
        <img alt="Recalcute: Yes" src="recalculate-style.png" />
```

2022-08-06 00:28 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the recalculate style step" src="recalculate-style.png" />
While it's questionable to use images for text, the alt for text should just read the text, and in this case the color is saying yes this step happens or no it doesn't. So those are the two things that need to be conveyed here and in the rest of this table.  Could say "recalculate happens" and other steps later "doesn't happen". Maybe using "recalculates" & "doesn't recalculate" is better than "recaculate: yes" and "recaculate: no"

2022-08-06 00:28 UTC, estelle commented on files/en-us/web/css/font-stretch/index.md
> +      <td><img alt="Example use of font-strech property on the letter e in League Mono Variable set at 50%" src="screenshot_2018-06-06_example_page.png" /></td>
We should probably file an issue since the 62.5% is larger than the 75% so I think it may be using the wrong image. Likely, we could use live code instead if markdown permits it. 

If keeping as is, "League Mono Variable letter e is narrower and shorter than default with font-stretch property set at 50%" provides the "what does this image convey" of alt attributes.

2022-08-06 00:28 UTC, estelle commented on files/en-us/web/css/layout_cookbook/media_objects/index.md
> +![Example of a media object with profile image on the left side and lorem ipsum text on the right side](media-object.png)
```suggestion
![Example of a media object with profile image on the left side and lorem ipsum text to the right filling up 80% of the space](media-object.png)
```

2022-08-06 00:28 UTC, estelle commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/theme/index.md
> +        <p><img alt="Example showing a browser's header area with a red background" src="theme-accentcolor.png" /></p>
```suggestion
        <p><img alt="Browser chrome is red with white text. Browsers tabs are lighter red, also with white text. URL bar is very light red with black text" src="theme-accentcolor.png" /></p>
```

2022-08-06 00:28 UTC, estelle commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/theme/index.md
> +        <p><img alt="Example showing a browser's header area with a red background" src="theme-accentcolor.png" /></p>
If you were describing the important bits to someone who can't see the image, how would you describe the image. 

Similar for all alt attributes on this page.

2022-08-06 13:46 UTC, muchafm commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the recalculate style step" src="recalculate-style.png" />
I see, thank for the feedback and explanations, I will modify this.

2022-08-06 13:46 UTC, muchafm commented on files/en-us/web/css/font-stretch/index.md
> +      <td><img alt="Example use of font-strech property on the letter e in League Mono Variable set at 50%" src="screenshot_2018-06-06_example_page.png" /></td>
I'm going to open an issue and at the same time take your feedback and change the alt descriptions.

2022-08-06 13:47 UTC, muchafm commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/theme/index.md
> +        <p><img alt="Example showing a browser's header area with a red background" src="theme-accentcolor.png" /></p>
ok, I will change them all, thank you some much for your feedback!

2022-08-08 05:08 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the recalculate style step" src="recalculate-style.png" />
```suggestion
        <img alt="recalculate: yest " src="recalculate-style.png" />
```

2022-08-08 05:09 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the layout step" src="layout-faint.png" /> <img alt="box representing the paint step" src="paint.png" />
```suggestion
        <img alt="box representing the layout step" src="layout-faint.png" /> <img alt="box representing the paint step" src="paint.png" />
```
```suggestion
        <img alt="does not re-layout" src="layout-faint.png" /> <img alt="does repaint" src="paint.png" />
```

2022-08-08 05:11 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the recalculate style step" src="recalculate-style.png" />
```suggestion
        <img alt="Does recalculate styles" src="recalculate-style.png" />
```

2022-08-08 05:11 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the layout step" src="layout-faint.png" />
```suggestion
        <img alt="box representing the layout step" src="layout-faint.png" />
```
```suggestion
        <img alt="No layout" src="layout-faint.png" />
```

2022-08-08 05:12 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the paint step" src="paint-faint.png" />
```suggestion
        <img alt="No repaint" src="paint-faint.png" />
```

2022-08-08 05:13 UTC, estelle commented on files/en-us/web/performance/animation_performance_and_frame_rate/index.md
> +        <img alt="box representing the layout step" src="layout.png" /> <img alt="box representing the paint step" src="paint.png" />
```suggestion
        <img alt="Does calculate layout" src="layout.png" /> 
        <img alt="Does repaint" src="paint.png" />
```

2022-08-08 16:00 UTC, muchafm commented on files/en-us/web/css/font-stretch/index.md
> +      <td><img alt="Example use of font-strech property on the letter e in League Mono Variable set at 50%" src="screenshot_2018-06-06_example_page.png" /></td>
I have opened an new issue [here](https://github.com/mdn/content/issues/19290#issue-1332077409) and linked your comment, I hope it's ok :)

2022-08-08 19:14 UTC, estelle approved these changes
Yay! Thank you.

2022-08-08 19:44 UTC, estelle approved these changes

2022-08-08 19:44 UTC, merged

2022-08-08 20:00 UTC, muchafm commented
@estelle Thank you for your reviews, your help and patience !