DO-NOT-REVIEW: Use arrow functions for anonymous functions where possible (part #9) [Last part!]
mdn/content pull request #19253
Opened 2022-08-07 09:25 UTC by teoli2003

Arrow functions are shorter and easier to read (but don't bind `this`).

This is the last part (we skipped the Learning Area though)

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/getallresponseheaders/index.md
>    if (this.readyState === this.HEADERS_RECEIVED) {
```suggestion
  if (request.readyState === this.HEADERS_RECEIVED) {
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/getresponseheader/index.md
>    if (this.readyState === this.HEADERS_RECEIVED) {
```suggestion
  if (client.readyState === client.HEADERS_RECEIVED) {
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/html_in_xmlhttprequest/index.md
>    console.log(this.responseXML.title);
```suggestion
  console.log(xhr.responseXML.title);
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/html_in_xmlhttprequest/index.md
>      if (this.readyState === 4 && !done) {
```suggestion
    if (xhr.readyState === 4 && !done) {
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/html_in_xmlhttprequest/index.md
>        callback(!!(this.responseXML && this.responseXML.title && this.responseXML.title === "&&<"));
```suggestion
      callback(!!(xhr.responseXML && xhr.responseXML.title && xhr.responseXML.title === "&&<"));
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/send/index.md
> +  if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
```suggestion
  if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +If you want to know ifthe current page has changed, refer to the article about {{domxref("document.lastModified")}}.
```suggestion
If you want to know if the current page has changed, refer to the article about {{domxref("document.lastModified")}}.
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +// Let's test the file "yourpage.html"…
```suggestion
// Let's test the file "yourpage.html"
```
```suggestion
// Let's test the file "yourpage.html"…
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +(modified, visit) => {
What happened here

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/events/creating_and_triggering_events/index.md
> +textarea.addEventListener('input', () => {
This should stay, see the comment:
> Note: Optionally, we've also leveraged the "function expression" (instead of the "arrow function expression") so "this" will represent the element

```suggestion
textarea.addEventListener('input', function() {
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/guide/audio_and_video_delivery/buffering_seeking_time_ranges/index.md
> +      document.getElementById('progress-amount').style.width =`{audio.currentTime * 100 / duration * 100}%`;
```suggestion
      document.getElementById('progress-amount').style.width = `{audio.currentTime * 100 / duration * 100}%`;
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/guide/audio_and_video_delivery/cross-browser_audio_basics/index.md
> +  const clickPosition = (e.pageX  - this.offsetLeft) / this.offsetWidth;
```suggestion
  const clickPosition = (e.pageX  - progress.offsetLeft) / progress.offsetWidth;
```

I think?

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/guide/audio_and_video_delivery/cross_browser_video_player/index.md
> +  const pos = (e.pageX  - rect.left) / this.offsetWidth;
```suggestion
  const rect = progress.getBoundingClientRect();
  const pos = (e.pageX  - rect.left) / progress.offsetWidth;
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/guide/audio_and_video_delivery/index.md
> +const lastsource = sources[sources.length-1];
```suggestion
const lastsource = sources[sources.length - 1];
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/guide/audio_and_video_delivery/video_player_styling_basics/index.md
> +  const pos = (e.pageX  - this.offsetLeft - this.offsetParent.offsetLeft) / this.offsetWidth;
```suggestion
  const pos = (e.pageX  - progress.offsetLeft - progress.offsetParent.offsetLeft) / progress.offsetWidth;
```

2022-08-07 18:38 UTC, lionralfs commented on files/en-us/web/html/element/input/button/index.md
> +const height = canvas.height = window.innerHeight-85;
```suggestion
const height = canvas.height = window.innerHeight - 85;
```

2022-08-07 19:01 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +(modified, visit) => {
I reverted the change, and I guess a bad copy/paste
```suggestion
```

2022-08-07 21:56 UTC, lionralfs commented on files/en-us/webassembly/understanding_the_text_format/index.md
> +  const tbl = new WebAssembly.Table({initial:2, element:"anyfunc"});
```suggestion
  const tbl = new WebAssembly.Table({ initial: 2, element: "anyfunc" });
```

2022-08-08 15:58 UTC, Josh-Cena requested changes

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests/index.md
> +{{deprecated_header()}}
```suggestion
{{deprecated_header}}
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests/index.md
> +    <meta charset=UTF-8>
```suggestion
    <meta charset="UTF-8">
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/synchronous_and_asynchronous_requests/index.md
> +        alert(`Worker said: ${event.data});
```suggestion
        alert(`Worker said: ${event.data}`);
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +- using only XHR
I've always believed AJAX is parallel to FormData while XHR is one way to achieve AJAX. Saying "`XMLHttpRequest` can be used when using only XHR" sounds a bit weird. But well, I don't know web :P

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +  <head>
Whoa, the diff here is not reviewable.

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
>  function getHeaderTime () {
```suggestion
function getHeaderTime() {
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/css/font/index.md
> +  radios = document.forms[0].elements[radioName];
```suggestion
  const radios = document.forms[0].elements[radioName];
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/cross_browser_video_player/index.md
> +  }
This looks quite legacy. Also has the possibility of executing multiple times.

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/video_player_styling_basics/index.md
> +    }
```suggestion
    if (dir === '+' && currentVolume < 1) {
       video.volume += 0.1;
    } else if (dir === '-' && currentVolume > 0) {
       video.volume -= 0.1;
    }
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/cross_browser_video_player/index.md
> +  }
```suggestion
  if (dir === '+' && currentVolume < 1) {
    video.volume += 0.1;
  } else if (dir === '-' && currentVolume > 0) {
    video.volume -= 0.1;
  }
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/video_player_styling_basics/index.md
> +    else video.muted = false;
```suggestion
    video.muted = currentVolume <= 0;
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/webaudio_playbackrate_explained/index.md
>    },false);
```suggestion
  }, false);
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/html/element/p/index.md
> +  [event.target.innerText, event.target.dataset.toggleText = [event.target.dataset.toggleText, event.target.innerText];
```suggestion
  [event.target.innerText, event.target.dataset.toggleText] =
    [event.target.dataset.toggleText, event.target.innerText];
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +  Array.prototype.slice.call(this.rows)
```suggestion
  Array.from(this.rows)
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +    }, this);
```js
    .forEach((e) => this.appendChild(this.removeChild(e)));
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
>  });
```suggestion
document.querySelector('table').tBodies[0].sort(
  (a, b) => a.textContent.localeCompare(b.textContent),
);
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  const splitUpString = (str) => return str.replace(/[A-Z]/g,"z$1").split(/z(?=[A-Z])/g);
```suggestion
  const splitUpString = (str) => str.replace(/[A-Z]/g,"z$1").split(/z(?=[A-Z])/g);
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  };
```suggestion
  const splitUpString = (str) => String(str).split(camelCaseExpression);
```

Also note that it's taking advantage of `var` being not block-scoped. You have to make a `let splitUpString` at the top level.

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  ? (str) => ("" + str).split(new RegExp("(?<=[A-Z])"=)
```suggestion
  ? (str) => String(str).split(new RegExp("(?<=[A-Z])"=)
```

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/svg/attribute/visibility/index.md
> +  document.querySelector("svg > path:nth-of-type(2)").classList.toggle("invisible");
`querySelector()` was invoked on the selected `button`

2022-08-08 15:58 UTC, Josh-Cena commented on files/en-us/web/svg/scripting/index.md
> +const svgDoc=document.embeds["name_of_svg"].getSVGDocument();
```suggestion
const svgDoc = document.embeds["name_of_svg"].getSVGDocument();
```

2022-08-09 03:08 UTC, Josh-Cena commented on files/en-us/web/api/worker/postmessage/index.md
>    myWorker.postMessage([first.value,second.value]);
```suggestion
  myWorker.postMessage([first.value, second.value]);
```

2022-08-09 03:14 UTC, Josh-Cena commented on files/en-us/web/guide/ajax/getting_started/index.md
> +  makeRequest('test.php',userName);
```suggestion
  makeRequest('test.php', userName);
```

2022-08-09 03:17 UTC, Josh-Cena commented on files/en-us/web/svg/scripting/index.md
> +        alert(this.message)
```suggestion
        alert(this.message);
```

2022-08-09 07:45 UTC, teoli2003 commented on files/en-us/web/svg/attribute/visibility/index.md
> +  document.querySelector("svg > path:nth-of-type(2)").classList.toggle("invisible");
```suggestion
const button = document.querySelector("button");
button.addEventListener("click", (evt) => {
  button.querySelector("svg > path:nth-of-type(1)").classList.toggle("invisible");
  button.querySelector("svg > path:nth-of-type(2)").classList.toggle("invisible");
```

2022-08-09 07:46 UTC, teoli2003 commented on files/en-us/web/svg/attribute/visibility/index.md
> +  document.querySelector("svg > path:nth-of-type(2)").classList.toggle("invisible");
Fixed

2022-08-09 07:52 UTC, teoli2003 commented on files/en-us/web/api/xrview/isfirstpersonobserver/index.md
> +requestAnimationFrame((frame) => {
This one was tricky. The `requestSession` returns a promise. Then `rAF` can be called on the session.

The original example was wrong.
See https://developer.mozilla.org/en-US/docs/Web/API/XRSession/requestAnimationFrame for another wxample

2022-08-09 07:57 UTC, teoli2003 commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  };
Fixed.

2022-08-09 08:50 UTC, teoli2003 commented on files/en-us/web/guide/audio_and_video_delivery/cross_browser_video_player/index.md
> +  }
I cleaned the code so that it doesn't use the prefix anymore.

Note that `requestFullscreen()` doesn't return a `Promise<void>,` so I didn't use it.

2022-08-09 08:51 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +  <head>
I removed the polyfill that is useless: that upset a bit the diff.

2022-08-09 08:51 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +    for (let i = 0; i < mqL.length | 0; i = i + 1 | 0) {
```suggestion
    for (let i = 0; i < mqL.length; i++) { 
```

2022-08-09 08:52 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +addEventListener("resize", setTimeout.bind(0,() => {
```suggestion
addEventListener("resize", () => setTimeout(() => {
```

2022-08-09 08:52 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +  <head>
The rest of the changes are the removal of the Hungarian notation.

2022-08-09 08:52 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +    for (let i = 0; i < mqL.length | 0; i = i + 1 | 0) {
```suggestion
    for (let i = 0; i < mqL.length; i++) {
```

2022-08-09 08:58 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +- using only XHR
I rewrote somewhat the article. AJAX should not be mentioned in it anymore.

2022-08-09 09:15 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +        const XHRSubmit = (function () {
This shouldn't be wrapped in a function? It used to be top-level

2022-08-09 09:33 UTC, Josh-Cena commented on files/en-us/web/guide/audio_and_video_delivery/cross_browser_video_player/index.md
> +  if (document.document.fullscreenElement !== null) {
```suggestion
  if (document.fullscreenElement !== null) {
```

?

2022-08-09 09:35 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  };
```suggestion
  splitUpString = (str) => String(str).split(camelCaseExpression);
```

2022-08-09 09:37 UTC, Josh-Cena commented on files/en-us/web/http/browser_detection_using_the_user_agent/index.md
> +  ? (str) => String(str).split(new RegExp("(?<=[A-Z])"=)
```suggestion
  ? (str) => String(str).split(new RegExp("(?<=[A-Z])"))
```

2022-08-09 09:51 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +          req.submittedData = oData;
```suggestion
          req.submittedData = data;
```

2022-08-09 09:51 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +                data.segments.length > 0 ? `?${dat.segments.join("&")}` : "",
```suggestion
                data.segments.length > 0 ? `?${data.segments.join("&")}` : "",
```

2022-08-09 09:52 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +        const XHRSubmit = (function () {
When I click Edit file, I don't see this line 357 anymore. I think this is fixed.

2022-08-09 09:53 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +          // console.log("AJAXSubmit - The form is now serialized. Submitting...");
```suggestion
          // console.log("XHRSubmit - The form is now serialized. Submitting...");
```

2022-08-09 09:58 UTC, Josh-Cena approved these changes
Reviewing the diff is giving me a stomachache...

All clear now. LGTM

2022-08-09 09:59 UTC, merged