General fixes to Storage Access API
mdn/content pull request #19267
Opened 2022-08-08 02:31 UTC by hamishwillee

This adds specifications tables from BCD for the Storage Access API docs which were previously just text and adds better cross linking. It also removes the experimental tagging for the pages - the BCD shows more than 2 engine implementations.
The rest is just layout improvements. Nothing controversial in any of this.

Note, this was originally going to be a fix to #18637. However that proved non-trivial - I'll add my reasoning to that issue.

2022-08-08 05:43 UTC, teoli2003 requested changes

2022-08-08 05:43 UTC, teoli2003 commented on files/en-us/web/api/document/hasstorageaccess/index.md
> +{{APIRef}}
It reads from the tags, but this is a kind of magic and we want to get rid of the tags in the middle term, so let's add it as an argument.
```suggestion
{{APIRef("Storage Access API"}}
```

2022-08-08 05:43 UTC, teoli2003 commented on files/en-us/web/api/document/requeststorageaccess/index.md
>  {{APIRef}}
```suggestion
{{APIRef("Storage Access API"}}
```

2022-08-08 05:43 UTC, teoli2003 commented on files/en-us/web/api/document/requeststorageaccess/index.md
> +1. If the browser is not processing a user gesture, reject(see {{Glossary("Transient activation")}}).
```suggestion
1. If the browser is not processing a user gesture, reject (see {{Glossary("Transient activation")}}).
```

2022-08-08 06:14 UTC, hamishwillee commented on files/en-us/web/api/document/hasstorageaccess/index.md
> +{{APIRef}}
Thanks @teoli2003 makes sense. 

Though IMO it might make even more sense if this was inferred from specific page metadata and the page type  rather than a tag. Maybe one day :-)

2022-08-08 06:36 UTC, teoli2003 approved these changes
👍

2022-08-08 06:39 UTC, merged

2022-08-08 06:39 UTC, hamishwillee commented
Thanks!

2022-08-09 08:00 UTC, fiji-flo commented
@hamishwillee please double check that tests. This wasn't passing and failed and got merged, which failed our production deployment. No worries though.

2022-08-09 08:46 UTC, hamishwillee commented
Sorry!