FF86 Release notes for AVIF addition
mdn/content pull request #1929
Opened 2021-02-01 03:54 UTC by hamishwillee

Adds release notes about 
- addition of basic AVIF support. 
- Update of HTTP header ACCEPT for HTML files following AVIF support.

2021-02-01 08:34 UTC, chrisdavidmills requested changes
cheers @hamishwillee ; couple of small requests for change, but nothing major

2021-02-01 08:34 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/releases/86/index.html
> +      <li><a href="/en-US/docs/Web/Media/Formats/Image_types#avif">AVIF</a> is a new image format with excellent compression and no patent restrictions developed by the Alliance for Open Media.</li>
maybe provide a link to the Alliance for Open Media? Sounds interesting, and people would want to know more about it.

2021-02-01 08:34 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/releases/86/index.html
> +  <li>The default HTTP {{HTTPHeader("ACCEPT")}} header for <em>images</em> changed to: <code>image/avif,image/webp,*/*</code> (following addition of support for the <a href="/en-US/docs/Web/Media/For
bug number?

2021-02-01 23:11 UTC, hamishwillee commented
Thanks @chrisdavidmills , suggestions integrated. Read for rechecking.

2021-02-16 19:45 UTC, chrisdavidmills approved these changes
This now looks good; thanks @hamishwillee !

2021-02-16 19:45 UTC, merged