Fixes titles for consistency and sentence casing
mdn/content pull request #19336
Opened 2022-08-09 22:37 UTC by dipikabh

#### How to access

You get the 'Modules' drop-down in the 'Reference' section in the CSS sidebar.

#### Current status

The 'Modules' pages include more or less the following sections and subsections based on whether or not they are applicable for the page (examples: [CSS Images](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images) and [CSS Display](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Display)):

```
- Reference
  - Properties
  - At-rules
  - Functions
  - Data types
- Guides
- Specifications
- Browser compatibility
- See also
```

The subsections under 'Reference' also match the categories in the CSS sidebar (screenshot below).

![Screenshot 2022-08-10 at 12 06 34 AM](https://user-images.githubusercontent.com/23019147/183771867-58e62ebf-bb32-4923-91b6-2a13b9e24854.png)
====
 
- On some pages, the section title "Properties" is "CSS Properties". 
- On some pages, the section title "Alt-rules" is "CSS Alt-rules".  

#### What this PR fixes
- Updates the section titles to ensure consistency: "Properties", "Alt-rules", "Data types"
- Updates casing of page and section titles to follow sentence casing
- Moves glossary entries and external resources to "See also" section
- Rewrites some sentences to remove the occurrence of the first person "I"

#### Question
Should the "Types" drop-down in the sidebar be called "Data types"?

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2022-08-10 02:45 UTC, wbamberg requested changes, later dismissed
Thanks @dipikabh ! I had a few comments and some questions. I wasn't always sure whether we should capitalize things like "Grid Layout". I expect we are not very consistent here.

> Should the "Types" drop-down in the sidebar be called "Data types"?

Yes, maybe. I don't feel very strongly though.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_box_model/index.md
> +### Properties for controlling the paddings of a box
```suggestion
### Properties for controlling the padding for a box
```

?

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +By adding `column-count` or `column-width` to an element, that element becomes a _multi-column container_, or a _multicol container_, for short. The columns are anonymous boxes and described as colum
I think the original is perhaps better here? Especially the additional comma.

"Our hamster is called Edward, or Ed for short"

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_columns/index.md
> +In the following example, the {{cssxref("column-count")}} property has been applied to the element with a class of container. As the value of `column-count` is `3`, the content is arranged into 3 col
I would prefer the original here - there is only one size. But my English is very intuitive so I might be wrong!

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +How overflowing columns are handled depends on if the media context is fragmented, such as print, or continuous, such as a web page.
Why if and not whether? I would have used whether.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_columns/spanning_columns/index.md
> +In the current level 1 specification, there are only two allowable values for `column-span`. The value `none` is the initial value and means the item does not span, remaining within a column. The val
```suggestion
In the current level 1 specification, there are only two allowable values for `column-span`. The value `none` is the initial value and means the item does not span, remaining within a column. The value `all` means the item spans all of the columns. This means that, for example, you cannot cause an item to span two out of three columns.
```

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_columns/styling_columns/index.md
> +In this next example, a 5px-dotted rule with a color of rebeccapurple has been created using the longhand values.
```suggestion
In this next example, a 5px-dotted rule with a color of `rebeccapurple` has been created using the longhand values.
```

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_display/index.md
> +### Flex
```suggestion
### Flexbox
```

?

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flexible_box_layout/backwards_compatibility_of_flexbox/index.md
> +title: Backwards compatibility of flexbox
```suggestion
title: Backwards compatibility of Flexbox
```

I think perhaps we should capitalize Flexbox.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Relationship of flexbox to other layout methods](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Relationship_of_Flexbox_to_Other_Layout_Methods)
```suggestion
- [Relationship of Flexbox to other layout methods](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Relationship_of_Flexbox_to_Other_Layout_Methods)
```

...also here.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Typical use cases of flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox)
```suggestion
- [Typical use cases of Flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox)
```

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Backwards compatibility of flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox)
```suggestion
- [Backwards compatibility of Flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox)
```

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox/index.md
> +title: Typical use cases of flexbox
```suggestion
title: Typical use cases of Flexbox
```

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flow_layout/flow_layout_and_writing_modes/index.md
> +## Writing Modes specification
Not sure why we capitalize "Writing Modes" here but not in the title.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_flow_layout/flow_layout_and_writing_modes/index.md
> +## Different writing mode from parent
Possibly "Nested writing modes"? idk though. But the current title is a bit clumsy.

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Relationship of grid Layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
```suggestion
- [Relationship of Grid Layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
```

? not sure. It seems odd to capitalize Layout and not grid. And this page title capitalizes both: "CSS Grid Layout and accessibility".

2022-08-10 02:45 UTC, wbamberg commented on files/en-us/web/css/css_selectors/index.md
> +## Pseudo selectors
```suggestion
## Pseudo classes and pseudo elements
```

2022-08-10 04:00 UTC, teoli2003 commented on files/en-us/web/css/css_box_model/index.md
> +### Properties for controlling the paddings of a box
```suggestion
### Properties controlling the paddings for a box
```
?

2022-08-10 04:03 UTC, teoli2003 commented on files/en-us/web/css/css_flow_layout/flow_layout_and_writing_modes/index.md
> +## Writing Modes specification
```suggestion
## Writing modes specification
```

2022-08-10 04:04 UTC, teoli2003 commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Relationship of grid Layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
I would have written _grid layout_.

2022-08-10 04:05 UTC, teoli2003 commented on files/en-us/web/css/css_selectors/index.md
> +## Pseudo selectors
_pseudo-classes and pseudo-elements_

There is no such thing as _pseudo selectors_

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_display/index.md
> +- [Backwards compatibility of flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox)
Should we get rid of this document?

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_flexible_box_layout/backwards_compatibility_of_flexbox/index.md
> +title: Backwards compatibility of flexbox
I disagree. I know we do it all over the place on MDN, but I don't know why.

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_flexible_box_layout/backwards_compatibility_of_flexbox/index.md
> +title: Backwards compatibility of flexbox
Well, I guess since we do it all over the place, we should capitalize it for consistency. But maybe we should change all the occurrences?

The spec is "CSS Flexible Box Layout Module". There are 4 occurrences of flexbox in the spec that aren't at the beginning of a sentence. 3 are lowercase, and 1 is capital.

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Flexbugs](https://github.com/philipwalton/flexbugs): a community-curated list of Flexbox browser bugs and workarounds
we might want to delete this soon. it hasn't been updated in 2 years.

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_flow_layout/in_flow_and_out_of_flow/index.md
> +In this example, there is a `div` and then two paragraphs. Background color has been added to the paragraphs, and the `div` is floated left. The `div` is now out of flow.
```suggestion
In this example, there is a `div` and then two paragraphs. A background color has been added to the paragraphs, and the `div` is floated left. The `div` is now out of flow.
```

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_generated_content/index.md
> +- Pseudo-elements: {{cssxref("::before")}}, {{cssxref("::after")}}, {{cssxref("::marker")}}
i think it also works with ::placeholder and ::file-selector-button

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_grid_layout/css_grid_layout_and_accessibility/index.md
> +title: CSS Grid Layout and accessibility
again, could be wrong....

`CSS grid layout and accessibility`

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Relationship of grid Layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
```suggestion
- [Relationship of grid layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
```

2022-08-10 04:23 UTC, estelle commented on files/en-us/web/css/css_shapes/index.md
> +- [How To Use CSS Shapes in Your Web Design](https://webdesign.tutsplus.com/tutorials/how-to-use-css-shapes-in-your-web-design--cms-27498)
these four articles have a mixture of casings. should we make them consistent?

2022-08-10 08:31 UTC, Josh-Cena commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +By adding `column-count` or `column-width` to an element, that element becomes a _multi-column container_, or a _multicol container_, for short. The columns are anonymous boxes and described as colum
The two commas in the original sentence make it look like an appositive on first parse. In this case I would change one to an em-dash to break that symmetry: "By adding `column-count` or `column-width` to an element, that element becomes a _multi-column container_ — or _multicol container_ for short." (In fact, Grammarly also suggests removing it.)

2022-08-10 08:45 UTC, teoli2003 commented on files/en-us/web/css/css_flexible_box_layout/backwards_compatibility_of_flexbox/index.md
> +title: Backwards compatibility of flexbox
I'm a strong proponent of using as few capitals as possible.

2022-08-10 08:47 UTC, teoli2003 commented on files/en-us/web/css/css_columns/index.md
> +**CSS Multi-Column Layout** is a module of CSS that adds support for multi-column layouts. Support is included for establishing the number of columns in a layout, as well as how content should flow f
Let's not use the spec name the article is not about it but about the _CSS multi-column layout_.

2022-08-10 08:48 UTC, teoli2003 commented on files/en-us/web/css/css_display/index.md
> +- [Backwards compatibility of flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox)
Yes, please!

2022-08-10 09:50 UTC, dipikabh commented on files/en-us/web/css/css_box_model/index.md
> +### Properties for controlling the paddings of a box
"Properties for controlling the padding for a box" seems good. Thanks!

2022-08-10 09:57 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +In the following example, the {{cssxref("column-count")}} property has been applied to the element with a class of container. As the value of `column-count` is `3`, the content is arranged into 3 col
I think what we mean is "the content is arranged into three columns of the same size."

2022-08-10 10:30 UTC, dipikabh commented on files/en-us/web/css/css_flexible_box_layout/backwards_compatibility_of_flexbox/index.md
> +title: Backwards compatibility of flexbox
I agree with fewer capitalizations and capitalizing only if the spec says it like in the module name. For middle-of-the-sentence capitalized occurrences, I think we should change them all.

2022-08-10 10:31 UTC, dipikabh commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Relationship of flexbox to other layout methods](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Relationship_of_Flexbox_to_Other_Layout_Methods)
Discussion in previous comment..

2022-08-10 10:37 UTC, dipikabh commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Relationship of grid Layout to other layout methods](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout)
Yes, I missed to lower case this

2022-08-10 12:24 UTC, dipikabh commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +### Property shorthand
I want to drop the beginning 'The' in the title. If I try 'columns shorthand' or 'columns property shorthand', both look odd because everything is in lower case and we're not styling the word columns in title.
How about "Shorthand for columns property"?

2022-08-10 12:29 UTC, dipikabh commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +title: Handling overflow in multicol
I'll leave this as 'multicol' because that's a specific term they're using to refer to multi-column layout spec/module.

"Multiple-column Layout, usually referred to as multicol..." - in [Basic concepts of multicol](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Basic_Concepts_of_Multicol)

2022-08-10 12:35 UTC, teoli2003 commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +### Property shorthand
> "Shorthand for columns property"?
Sounds odd as the `columns` property is the shorthand...

```suggestion
### Shorthand for column properties: columns
```

2022-08-10 12:37 UTC, teoli2003 commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +title: Handling overflow in multicol
(There is a capitalization problem in _Basic concepts of multicol_: layout should not have a capital case)

Note that I'm curious to measure the SEO impact of multicol instead of multi-column in the titles. Do people find this page?

2022-08-10 12:37 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +title: CSS Multi-Column Layout
As you'll see from the "Modules" drop-down in CSS sidebar, all the module names are initial upper case, perhaps following the names of the modules from the spec. So all those page titles have not been changed to lower case.

Interestingly, for this particular module, the [spec](https://drafts.csswg.org/css-multicol/) uses lower case 'column', but as per the English casing rules in general, both hyphenated words should be uppercase. So I really don't know; I kinda defied the spec in this case. :)

2022-08-10 12:39 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +title: CSS Multi-Column Layout
Update - please see next comment

2022-08-10 12:42 UTC, teoli2003 commented on files/en-us/web/css/css_columns/index.md
> +title: CSS Multi-Column Layout
I think we should be coherent: lowercase in the title, in the prose and in the sidebar. It is because we are not coherent that we have this mix right now.

We use _sentence case_ in titles (and sidebars) so no capitals after CSS.

2022-08-10 12:42 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +- [Handling overflow in multicol](/en-US/docs/Web/CSS/CSS_Columns/Handling_Overflow_in_Multicol)
Keeping this as-is

2022-08-10 12:43 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +- [Handling content breaks in multicol](/en-US/docs/Web/CSS/CSS_Columns/Handling_content_breaks_in_multicol)
multicol has been defined here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Basic_Concepts_of_Multicol

2022-08-10 12:45 UTC, dipikabh commented on files/en-us/web/css/css_columns/using_multi-column_layouts/index.md
> +The **CSS Multi-Column Layout Module** extends the _block layout mode_ to allow the easy definition of multiple columns of text. People have trouble reading text if lines are too long; if it takes to
Thanks. Yes, I am updating this now even though I don't like it.

2022-08-10 12:45 UTC, teoli2003 commented on files/en-us/web/css/css_columns/index.md
> +**CSS Multi-Column Layout** is a module of CSS that adds support for multi-column layouts. Support is included for establishing the number of columns in a layout, as well as how content should flow f
Yes, the specs are not coherent at all.

2022-08-10 12:45 UTC, teoli2003 commented on files/en-us/web/css/css_columns/index.md
> +**CSS Multi-Column Layout** is a module of CSS that adds support for multi-column layouts. Support is included for establishing the number of columns in a layout, as well as how content should flow f
And these page names are not the spec names anyway.

2022-08-10 12:48 UTC, dipikabh commented on files/en-us/web/css/css_display/index.md
> +- [Backwards compatibility of flexbox](/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox)
You mean delete the "Backwards compatibility of flexbox" page? If yes, I can open a separate PR to delete it and remove the link here.

2022-08-10 12:51 UTC, dipikabh commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Flexbugs](https://github.com/philipwalton/flexbugs): a community-curated list of Flexbox browser bugs and workarounds
Would it help to keep the link around only to be able to refer to the work that was done in the past or is it not helpful at all now?

2022-08-10 13:05 UTC, dipikabh commented on files/en-us/web/css/css_shapes/index.md
> +- [How To Use CSS Shapes in Your Web Design](https://webdesign.tutsplus.com/tutorials/how-to-use-css-shapes-in-your-web-design--cms-27498)
I checked with the linked article and kept the same casing here. We can though, for the aesthetics of our page, decide to follow our casing style no matter what style they've used.

2022-08-10 13:06 UTC, dipikabh commented on files/en-us/web/css/css_shapes/index.md
> +- [How To Use CSS Shapes in Your Web Design](https://webdesign.tutsplus.com/tutorials/how-to-use-css-shapes-in-your-web-design--cms-27498)
I am struggling with 'CSS Shapes'. Does it always have to be initial capitalized?

2022-08-10 13:39 UTC, dipikabh commented
Thank you @wbamberg, @estelle, and @teoli2003 for the review! I have incorporated most of the suggestions or left a comment. I touched a few more pages that caught my attention.

The casing in titles is definitely inconsistent and is made more confusing how the modules are named in the spec. I guess, in general, we stick to the spec or module name in initial uppercase and in all other references to the word in a sentence, such as 'shape', 'box', 'grid', we follow the normal sentence casing.

Interestingly, the Guides drop-down in CSS sidebar (screenshot below) already has all titles in correct casing and minus the 'CSS' everywhere. I used it as a guide for some of the page titles.
****
![Screenshot 2022-08-10 at 3 34 26 PM](https://user-images.githubusercontent.com/23019147/183914981-f2cc6930-4e39-4310-b89e-a487d60e7cd1.png)
--

2022-08-10 13:44 UTC, dipikabh commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +By adding `column-count` or `column-width` to an element, that element becomes a _multi-column container_, or a _multicol container_, for short. The columns are anonymous boxes and described as colum
Thanks for your suggestion, @Josh-Cena. I looked at your comment after I'd pushed my fixes.

2022-08-10 14:19 UTC, teoli2003 requested changes
This is an amazing piece of work, @dipikabh ! I'm all for more consistency. I have a few final points to address (some are merely questions), and then, from my point of view, this will be good to land.

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +### Shorthand for columns property
This is incorrect.

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_columns/index.md
> +- [Handling content breaks in multicol](/en-US/docs/Web/CSS/CSS_Columns/Handling_content_breaks_in_multicol)
I agree with Estelle, we really should remove it from MDN.

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_display/index.md
> +### Flexbox
```suggestion
### Flexible box layout
```

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_display/index.md
> +### Grid
```suggestion
### Grid layout
```

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_flexible_box_layout/index.md
> +- [Flexbugs](https://github.com/philipwalton/flexbugs): a community-curated list of Flexbox browser bugs and workarounds
No, historical information is not useful, as well as outdated ones. We should get rid of it.

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_fragmentation/index.md
This looks strange to have this empty…

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +In this article, we took a very quick look through the Grid Layout specification. Have a play with the code examples, and then move onto [the next part of this guide](/en-US/docs/Web/CSS/CSS_Grid_Lay
We didn't walk through the spec. We walk through the feature.
```suggestion
In this article, we took a very quick look at the possibilities of grid layouts. Play with the code examples, and then move on to [the next part of this guide](/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout), where we will start to dig into the detail of CSS Grid Layout.
```

2022-08-10 14:19 UTC, teoli2003 commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Masonry layout](/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout) {{Experimental_Inline}}
I just noticed this now. Shouldn't we have the slugs coherent too?
Like: moving _Masonry layout_ (and many others) to /en-US/docs/Web/CSS/Grid_layout/Masonry_layout

It could be a separate PR.

2022-08-11 13:37 UTC, dipikabh commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +### Property shorthand
Thanks for making this technically accurate, @teoli2003! I am going to drop ": columns" bit though.

2022-08-11 13:46 UTC, dipikabh commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +title: Handling overflow in multicol
In the version of the Basic concepts file I have for that page, I don't see layout in capital case. Did you mean it is in upper case in the landing page for [CSS Multi-column Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns)? I guess the page titles are following the module names defined in the spec.

I strongly agree with you @teoli2003 about _not using_ "multicol" in titles because the assumption of using the word is that the reader would have seen the Basic concepts page where multicol is defined as the short form for multi-column layout.

2022-08-11 14:08 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +- [Handling overflow in multicol](/en-US/docs/Web/CSS/CSS_Columns/Handling_Overflow_in_Multicol)
I've updated this to remove multicol now 🤯 (https://github.com/mdn/content/pull/19336#discussion_r943505279)

2022-08-11 14:23 UTC, dipikabh commented on files/en-us/web/css/css_grid_layout/index.md
> +- [Masonry layout](/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout) {{Experimental_Inline}}
Yeah, definitely a separate PR. With so many titles updated in this PR, the slugs will definitely need to be revised.

2022-08-11 14:29 UTC, dipikabh commented on files/en-us/web/css/css_columns/basic_concepts_of_multicol/index.md
> +### Shorthand for columns property
Fixed as per your suggestion in previous comment

2022-08-11 14:29 UTC, dipikabh commented on files/en-us/web/css/css_columns/index.md
> +- [Handling content breaks in multicol](/en-US/docs/Web/CSS/CSS_Columns/Handling_content_breaks_in_multicol)
I think I'll have to open a separate PR that.

2022-08-13 05:23 UTC, teoli2003 commented on files/en-us/web/css/css_fragmentation/index.md
Maybe we should remove the H2 Reference and brings the H3 as H2 (Properties, …). This would make the ToC more useful too.

But in another PR.

2022-08-13 05:38 UTC, teoli2003 commented
> I'll open a separate PR for removing multicol and changing flexbox to lower case.

👍

> > [#19336 (comment)](https://github.com/mdn/content/pull/19336#discussion_r941995120)
> 
> You mean delete the "Backwards compatibility of flexbox" page? If yes, I can open a separate PR to delete it and remove the link here.
Yes, it was meant to describe how to write a website with the pre-experimental flexible box layout. Nobody uses them anymore: either devs use the modern flexbox layout or no flexbox.

> 
> > And these page names are not the spec names anyway. ([#19336 (comment)](https://github.com/mdn/content/pull/19336#discussion_r942405072))
> 
> I don't get this. From the impression I got, all pages that can be accessed from Modules drop-down in CSS sidebar are all initial caps and not in sentence casing and all have the prefix CSS, as in "[CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations)". And the first sentence in the page mentions that title as the name of the module, which matches the name of the module, along with casing, as in the spec. In that regard, this deviation from following sentence casing for the page titles is to match the module name. Is that incorrect. Should the titles follow sentence casing nevertheless and drop the "CSS" (linked to next question)?
> 
> > Like: moving Masonry layout (and many others) to /en-US/docs/Web/CSS/Grid_layout/Masonry_layout

We don't document specs per se. That means we divide CSS into logical collections of features. We and the spec people need these groups, and the spec people have done an amazing job in performing the grouping, so we are using their hints extensively. But, we are not tight to follow their grouping. This means:
- If it makes more sense to go for smaller groups, larger groups, or different groups, we can (I'm not saying we should, but we are not bound to the CSS grouping)
- We don't document CSS features not implemented, so if there is a new CSS spec that is not implemented, we will not create the entry. We may make exceptions here as sometimes, a non-implemented spec is a big topic among devs, and having it on MDN already may be useful (e.g., Masonry ?). We have to be cautious as, usually, it means the specs will change, and we need to update the docs to prevent them from becoming outdated (and not merely incomplete like most of the rest of our docs).
- We don't need to follow the spec casing or wording. They are often incoherent between specs, and inside a single spec. So we should follow _our_ conventions in casing and not the specs: they are our grouping and not spec names. To answer your question, we shouldn't deviate from our convention and use sentence casing in the sidebar too.


> Do you mean removing the 'CSS' prefix from the slugs as well as all from the page titles? This somewhat ties in with my previous question.
Yes, it can be in a follow-up PR (or far far later)

2022-08-16 04:41 UTC, estelle commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +title: Handling overflow in multicol
i really don't think we should be using "multicol". If we do, we have to define it in each page we use it.

2022-08-16 04:44 UTC, estelle commented on files/en-us/web/css/css_columns/handling_overflow_in_multicol/index.md
> +title: Handling overflow in multicol
NVM. I saw the note below after I wrote this.

2022-08-16 04:47 UTC, estelle commented
Everything @teoli2003 said. Great job!

2022-08-16 09:26 UTC, teoli2003 approved these changes

2022-08-17 08:08 UTC, dipikabh commented
Thanks, @estelle.

Thanks for approving, @teoli2003! I intend to take up the changes discussed here in separate PRs.
Could you also merge this PR? (or is it showing as 'Merging is blocked' for you?)

2022-08-17 08:26 UTC, teoli2003 commented
As Will is out today, and the only divergence was the _flexbox_ capitalization, I will override his request review. The open points can be dealt in a follow-up PR.

2022-08-17 08:26 UTC, teoli2003 commented
As Will is out today, and the only divergence was the _flexbox_ capitalization, I will override his request review. The open points can be dealt in a follow-up PR.

2022-08-17 08:27 UTC, merged

2022-08-17 09:05 UTC, dipikabh commented
Thank you, @teoli2003 🙏