Link to ECMAScript epoch from Date.now()
mdn/content pull request #19355
Opened 2022-08-10 09:37 UTC by codyatwork

#### Summary

Replaces the text "January 1, 1970 00:00:00 UTC" on the `Date.now()` page with a link to the ECMAScript epoch.
#### Motivation

This allows the reader to easily find more information about the epoch and makes this page consistent with [`Date.prototype.getTime()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime). I noticed this inconsistency when I was looking at both pages to see if these functions return the same kind of timestamp and had to click through to the epoch page to be sure that they were referencing the same time.
#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-10 09:46 UTC, teoli2003 requested changes, later dismissed

2022-08-10 09:46 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
We need to know the epoch here without going on another page.

```suggestion
milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps), January 1st 1970 at midnight UTC.
```

2022-08-10 09:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
"ECMAScript epoch" is not a spec term either. May be better if we simply use "Unix epoch"?

2022-08-10 10:01 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
or just "epoch".

2022-08-12 12:24 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
@teoli2003 I just dug up https://github.com/mdn/content/pull/17096. Shall we merge that one and then update this (and also the `#the_ecmascript_epoch_and_timestamps` section) to use the glossary entry?

2022-08-12 12:36 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
#17096 is on my stack, but I've never got back to it. Goal for next week. Let's wait for it to land than reevaluate this one.

2022-08-16 16:19 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/now/index.md
> +milliseconds elapsed since the [ECMAScript epoch](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps).
Actually, blaming this line takes me to https://github.com/mdn/content/issues/12715, which makes me think "Unix epoch" can be confusing. I'm not sure "epoch" is something that conveys any specificity either.

2022-11-07 08:45 UTC, sideshowbarker commented
I guess this is blocked on https://github.com/mdn/content/pull/17096?

2022-11-07 13:39 UTC, Josh-Cena commented
Yes, it is

2022-11-21 20:54 UTC, Josh-Cena commented
I've opted for the term "epoch" instead of "ECMAScript epoch". (In the end I did not use any content from #17096.) It's a pretty minor change, but would be helpful to get a second pair of eyes. @wbamberg?

2022-11-23 04:56 UTC, wbamberg approved these changes
👍 thank you @Josh-Cena !

2022-11-23 04:57 UTC, merged