Fanyak alt text add 2
mdn/content pull request #19354
Opened 2022-08-10 09:19 UTC by fanyak

#### Summary

Add missing alt texts for images catalogued [here](https://docs.google.com/spreadsheets/d/1cDHee6mwDMlY6zANEmg8MjR8tL-wrCS86uawpWZ4XbA/edit#gid=0)

#### Motivation

The changes are meant to improve accessibility.  The content of images that don't have alt text is inaccessible.

#### Supporting details

Changes where motivated by the discussion [here](https://github.com/orgs/mdn/discussions/168#discussioncomment-3361122)

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-11 11:35 UTC, Rumyra requested changes

2022-08-11 11:35 UTC, Rumyra commented on files/en-us/games/techniques/3d_collision_detection/bounding_volume_collision_detection_with_three.js/index.md
> +![A Knot object, a large Sphere object and a small Sphere object in 3-D space. Three vectors are drawn on the small Sphere. The vectors point in the directions of the three axes that define the space
```suggestion
![A knot object, a large sphere object and a small sphere object in 3-D space. Three vectors are drawn on the small sphere. The vectors point in the directions of the three axes that define the space. Text at the bottom reads: Drag the ball around.](screen_shot_2015-10-20_at_15.19.16.png)
```

2022-08-11 11:35 UTC, Rumyra commented on files/en-us/games/techniques/3d_collision_detection/bounding_volume_collision_detection_with_three.js/index.md
> +![A Knot object, a Sphere object and a Cube object in 3-D space. The Knot and the Sphere are encompassed by a virtual bounding box. The Cube is intersecting the bounding box of the Sphere. Text at th
```suggestion
![A knot object, a sphere object and a cube object in 3-D space. The knot and the sphere are encompassed by a virtual bounding box. The cube is intersecting the bounding box of the sphere. Text at the bottom reads: Drag the cube around. Press Esc to toggle B-Boxes.](screen_shot_2015-10-19_at_12.10.06.png)
```

2022-08-11 11:35 UTC, Rumyra commented on files/en-us/games/techniques/3d_collision_detection/bounding_volume_collision_detection_with_three.js/index.md
> +![A Knot object, a large Sphere object and a small Sphere object in 3-D space. Three vectors are drawn on the small Sphere. The vectors point in the directions of the three axes that define the space
These look great @fanyak we just don't need to capitalise the objects :)

2022-08-11 11:48 UTC, fanyak commented
@Rumyra thank you for the help!

2022-08-16 04:00 UTC, estelle approved these changes
Awesome. Thanks!

2022-08-16 10:04 UTC, Rumyra approved these changes

2022-08-16 10:04 UTC, merged