Added: alt attribute to few images
mdn/content pull request #19366
Opened 2022-08-10 13:37 UTC by Chaitanya7666

#### Summary

* I have added `alt` attributes to a handful of items in the content

#### Motivation

* Adding the `alt` attribute to the image displays the value of `alt` attribute when the respective `image fails to load` rather than leaving the space blank.

#### Supporting details

@estelle has collected the list of images from the documentation that do not have the `alt` attribute. [link to the spreadsheet](https://docs.google.com/spreadsheets/d/1cDHee6mwDMlY6zANEmg8MjR8tL-wrCS86uawpWZ4XbA/edit#gid=0)
#### Related issues

N/A
#### Metadata

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-10 22:41 UTC, estelle commented on files/en-us/glossary/main_axis/index.md
> +![This image shows three HTML elements arranged one below the other as their flex-direction is set to column so that the main-axis of the container element of the arranged items runs vertically i.e.
```suggestion
![This image shows three HTML elements arranged one below the other as their flex-direction is set to column so that the main-axis of the container element of the arranged items runs vertically i.e. from top to bottom](basics2.png)
```
```suggestion
![Three flex items taking up the full width of the container, displayed one below the other in code order.  Flex-direction is set to column. The main axis is vertical i.e. from top to bottom](basics2.png)
```

2022-08-10 22:58 UTC, estelle requested changes
A few suggested edits. Thanks.

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/main_axis/index.md
> +![This image shows three HTML elements arranged one below the other as their flex-direction is set to column so that the main-axis of the container element of the arranged items runs vertically i.e.
Screen readers inform the user it's an image before reading alt text, so it's best practice to not include 'image'.

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/session_hijacking/index.md
> +![This image shows how an attacker is trying to bypass the session between a regular user and the server to exploit the user's session](session_hijacking_3.jpg)
```suggestion
![The attacker sniff accesses a legitimate session id from a user interacting with a web server, then uses that session identifier to spoof the session between the regular user and the server to exploit the user's session and access the server directly.](session_hijacking_3.jpg)
```

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/session_hijacking/index.md
> +![This image shows how an attacker is trying to bypass the session between a regular user and the server to exploit the user's session](session_hijacking_3.jpg)
the fact that the session IDs are the same is the important thing the sighted user will learn from this image, so that should be conveyed in the alt attribute.

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/sql_injection/index.md
> +[![This image is a pie chart which represents that SQL injection is responsible for 50% of vulnerabilities followed by Cross Site Scripting which is responsible for 42% of vulnerabilities](sql_inj_xs
```suggestion
[![Pie chart of most common vulnerabilities: SQL injection is responsible for 50% of vulnerabilities, Cross Site Scripting is responsible for 42% of vulnerabilities, sourc code disclosure is 7%.](sql_inj_xss.gif)](https://cdn.acunetix.com/wp_content/uploads/2010/09/sql_inj_xss.gif)
```

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/sql_injection/index.md
> +[![This image is a pie chart which represents that SQL injection is responsible for 50% of vulnerabilities followed by Cross Site Scripting which is responsible for 42% of vulnerabilities](sql_inj_xs
You want to include most or all of the text of an image that conveys information.

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/sql_injection/index.md
> +![This image is a screenshot of the login page of an application with username field and password field](updates_loginscreen.png)
```suggestion
![Screenshot of the login form with username and password fields](updates_loginscreen.png)
```

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/state_machine/index.md
> +![This is the image of a Deterministic Finite State Machine where the machine transitions from state 1 to state 2 for input X and it transitions from state 1 to state 3 for input Y](statemachine1.png
```suggestion
![The machine transitions from state 1 to state 2 for input X and from state 1 to state 3 for input Y](statemachine1.png)
```

2022-08-10 22:58 UTC, estelle commented on files/en-us/glossary/state_machine/index.md
> +![This is the image of a Non-Deterministic Finite State Machine where the machine remains in state 1 for input X and it transitions from state 1 to state 2 for the same input X](statemachine2.png)
```suggestion
![The machine may remain in state 1, transitioning to itself, or may transition from state 1 to state 2 for input X](statemachine2.png)
```

2022-08-11 03:43 UTC, Chaitanya7666 commented on files/en-us/glossary/sql_injection/index.md
> +[![This image is a pie chart which represents that SQL injection is responsible for 50% of vulnerabilities followed by Cross Site Scripting which is responsible for 42% of vulnerabilities](sql_inj_xs
```suggestion
[![Pie chart of most common vulnerabilities: SQL Injection is responsible for 50% of vulnerabilities, Cross Site Scripting is responsible for 42% of vulnerabilities, Source Code Disclosure is responsible for 7% of vulnerabilities.](sql_inj_xss.gif)](https://cdn.acunetix.com/wp_content/uploads/2010/09/sql_inj_xss.gif)
```

2022-08-11 06:36 UTC, estelle commented on files/en-us/glossary/session_hijacking/index.md
> +![The attacker sniff accesses a legitimate session id from a user interacting with a web server, then uses that session identifier to spoof the session between the regular user and the server to expl
```suggestion
![The attacker sniffs and accesses a legitimate session id from a user interacting with a web server, then uses that session identifier to spoof the session between the regular user and the server to exploit the user's session and access the server directly.](session_hijacking_3.jpg)
```

2022-08-11 06:36 UTC, estelle approved these changes

2022-08-11 06:36 UTC, merged