Remove improper uses of var in Learn/
mdn/content pull request #19370
Opened 2022-08-10 15:57 UTC by teoli2003

This is the last bit of `var`s to remove!

2022-08-10 15:58 UTC, teoli2003 commented on files/en-us/learn/html/introduction_to_html/advanced_text_formatting/index.md
> +const htmlSolution = '<dl>\n <dt>Bacon</dt>\n <dd>The glue that binds the world together.</dd>\n <dt>Eggs</dt>\n <dd>The glue that binds the cake together.</dd>\n <dt>Coffee</dt>\n <dd>The drink that
This was declared below, but I wanted to have them before their first use.

2022-08-10 22:03 UTC, wbamberg commented on files/en-us/learn/server-side/express_nodejs/mongoose/index.md
> +//C reate a SomeModel model just by requiring the module
```suggestion
// Create a SomeModel model just by requiring the module
```

2022-08-10 22:25 UTC, wbamberg requested changes
Lots of changes, and this is hard to review! Just a few comments though.

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/server-side/express_nodejs/routes/index.md
> +  res.send(`NOT IMPLEMENTED: Author create GET`);
Very minor point, but this change is not needed I think?

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/server-side/express_nodejs/routes/index.md
> +  res.send('NOT IMPLEMENTED: Genre detail: ${req.params.id}`);
```suggestion
  res.send(`NOT IMPLEMENTED: Genre detail: ${req.params.id}`);
```

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +          destroy: () => node.removeEventListener('focus', onFocus); // this will be executed when the node is removed from the DOM
I think the semi-colon here is wrong?

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +          destroy: () => node.removeEventListener('focus', onFocus); // this will be executed when the node is removed from the DOM
I think the semi-colon here is wrong?

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +      $: totalTodos = todos.length;
I don't understand this line, but I guess the semi-colon here is OK?

2022-08-10 22:25 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md
> +  for (let i = 0; i < heroes.length; i++) {
for...of while we are here?

2022-08-11 04:21 UTC, teoli2003 commented on files/en-us/learn/server-side/express_nodejs/routes/index.md
> +  res.send(`NOT IMPLEMENTED: Author create GET`);
Yes, this is strange, I don't know why I did it. I shouldn't. It was not my intend.
```suggestion
  res.send('NOT IMPLEMENTED: Author create GET');
```

2022-08-11 04:23 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md
> +  for (let i = 0; i < heroes.length; i++) {
```suggestion
  for (const hero of heroes) {
```

2022-08-11 04:25 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +          destroy: () => node.removeEventListener('focus', onFocus); // this will be executed when the node is removed from the DOM
Oh yes, it is an object!
```suggestion
          destroy: () => node.removeEventListener('focus', onFocus) // this will be executed when the node is removed from the DOM
```

2022-08-11 04:26 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +          destroy: () => node.removeEventListener('focus', onFocus); // this will be executed when the node is removed from the DOM
Removed

2022-08-11 04:29 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_reactivity_lifecycle_accessibility/index.md
> +      $: totalTodos = todos.length;
Technically, `$:` is a JS label. Svelte official docs use semi-colons:

![Capture d’écran 2022-08-11 à 06 27 27](https://user-images.githubusercontent.com/1466293/184064870-5c46b61f-1494-41a2-9a86-05109b8c041a.png)

2022-08-11 13:27 UTC, wbamberg approved these changes
👍 thank you @teoli2003 !

2022-08-11 13:27 UTC, merged