Update index.md
mdn/content pull request #19377
Opened 2022-08-10 18:23 UTC by P1GAS

#### Summary
Fix expected result, make code more readable

#### Motivation
Make code more readable and don't be misled

This PR…
-->
- [ ] Make expected result correct
- [ ] Rewrite code to make it more readable

2022-08-10 21:38 UTC, wbamberg requested changes
Thanks for your PR, @P1GAS !

I agree that we could clarify this example and make it more "real".

But this change is not quite right. I think the existing page is expecting that each assignment is being made on the original value of the variable.

For example, here:

```js
// Boolean + Number -> addition
baz += 1 // 2

// Boolean + Boolean -> addition
baz += false // 2
```

...in the second addition assignment, it says `baz` is boolean, but after the first one it is a number.

Similarly, your change here:

```js
baz += false // 2
```

...seems to be because you previously incremented `baz`, but that's inconsistent with the later one:

```js
let foo = 'foo'

// String + Boolean -> concatenation
foo += false // "foofalse"

// String + String -> concatenation
foo += 'bar' // "foobar"
```

...why isn't the last value here "foofalsebar"?

I think it would be best to make it very clear that these are all self-contained examples, perhaps by having separate code blocks for them? For example:

```js
let bar = 5;

// Number + Number -> addition
bar += 2; // 7
```

```js
let bar = 5;

// Number + String -> concatenation
bar += 'foo'; // "5foo"
```
...etc

2022-08-11 14:57 UTC, P1GAS commented
Hello @wbamberg! I have changed the code, could you check it again?

2022-08-15 18:00 UTC, wbamberg requested changes
Thank you for the update @P1GAS . But this isn't the change I asked for. I suggested making each assignment a separate self-contained example. Is there a reason you don't think this is a good idea?

2022-08-15 18:17 UTC, P1GAS commented
I think that's a good idea. I have another view similar to yours. What if we create 3 blocks with every variable

2022-08-15 21:20 UTC, wbamberg commented
> @wbamberg I didn't understand you previously. I think that's a good idea. I have another view similar to yours. What if we create 3 blocks for every variable
> 

Yes, this looks good to me too. But please use `const` rather than `let` here, and semicolons at the ends of lines.

2022-08-15 21:25 UTC, teoli2003 commented
> > @wbamberg I didn't understand you previously. I think that's a good idea. I have another view similar to yours. What if we create 3 blocks for every variable
> 
> Yes, this looks good to me too. But please use `const` rather than `let` here, and semicolons at the ends of lines.

These must be let as the operator `+=` is used. But I agree for the semi-colon.

2022-08-15 21:29 UTC, wbamberg commented
> > > @wbamberg I didn't understand you previously. I think that's a good idea. I have another view similar to yours. What if we create 3 blocks for every variable
> > 
> > 
> > Yes, this looks good to me too. But please use `const` rather than `let` here, and semicolons at the ends of lines.
> 
> These must be let as the operator `+=` is used. But I agree for the semi-colon.

Doh, sorry! Yes of course.

2022-08-16 11:15 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/addition_assignment/index.md
> +x += y; // x = x + y
```suggestion
x += y // x = x + y
```

2022-08-18 19:16 UTC, wbamberg approved these changes
👍 looks good to me, thank you @P1GAS !

2022-08-18 19:16 UTC, merged