Avoid classical for if for...of when looping all object of an Array-like object
mdn/content pull request #19402
Opened 2022-08-11 07:18 UTC by teoli2003

Classical `for` loops are error-prone (setting the right condition, not mixing indices…) and difficult to read when used to loop on all elements of an Array-like structure.

This PR changes some occurrences to use the modern `for…of`, or `.forEach()` in some occurrences.

Note that:
- I use `for…of` if I don't need the index
- I use `.forEach()` when I do, or on an object where `for…of` may not work.
- There were a couple of cases where the loop copied an Array into a new one; I used `Array.from()` instead.

2022-08-11 07:25 UTC, zloirock commented on files/en-us/web/api/vrdisplaycapabilities/index.md
> +    displays.foreach((display, i) => {
Typo.

2022-08-11 07:48 UTC, teoli2003 commented on files/en-us/web/api/vrdisplaycapabilities/index.md
> +    displays.foreach((display, i) => {
Oh yes, I do this one so often…
```suggestion
    displays.forEach((display, i) => {
```

2022-08-12 03:07 UTC, Josh-Cena requested changes

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/webglrenderingcontext/vertexattribpointer/index.md
>  for (let i = 0; i < vertices.length; i++) {
This looks like a `forEach`?

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/webrtc_api/signaling_and_video_calling/index.md
>    }
```suggestion
  connectionArray.find((conn) => conn.username === target).send(msgString);
```

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/websockets_api/writing_websocket_servers/index.md
> +const decoded = encoded.from((elt, i) => elt ^ mask[i % 4]); // Perform an XOR on the mask
This is actually pseudocode where all-caps seem more idiomatic. Related: https://github.com/mdn/content/issues/18196 I think we should just make it actually usable JS. Also need to update the `**DECODED**` below.

Also, pretty sure it's `%SomeTypedArray%.from(encoded, ...)`?

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/webvr_api/using_vr_controllers_with_webvr/index.md
>        listItem.innerHTML = `<strong>Display ${i+1}</strong><br>` +
```suggestion
      listItem.innerHTML = `<strong>Display ${i + 1}</strong><br>` +
```

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/webxr_device_api/inputs/index.md
> +});
```js
const primaryInputSource =
  xrSession.inputSources.find((src) => src.handedness === user.handedness) ??
  xrSession.inputSources[0];
```

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/window/speechsynthesis/index.md
>    }
```suggestion
  utterThis.voice = voices.find((v) => v.name === selectedOption);
```

2022-08-12 03:07 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/sending_and_receiving_binary_data/index.md
> +});
This needs to be `Uint8Array.from()`

2022-08-13 05:16 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/sending_and_receiving_binary_data/index.md
> +});
```suggestion
const longInt8View = Uint8Array.from(array, (element, i) => i % 256);
```

2022-08-13 05:18 UTC, teoli2003 commented on files/en-us/web/api/webrtc_api/signaling_and_video_calling/index.md
>    const isUnique = true;
I hesitated, but you are right. It isn't used, so let's get rid of it.

2022-08-13 05:19 UTC, teoli2003 commented on files/en-us/web/api/web_audio_api/using_audioworklet/index.md
>        let sampleCount = input[channelNum].length;
Yes, removed

2022-08-13 05:21 UTC, Josh-Cena commented on files/en-us/web/api/websockets_api/writing_websocket_servers/index.md
> +If the MASK bit was set (and it should be, for client-to-server messages), read the next 4 octets (32 bits); this is the masking key. Once the payload length and masking key is decoded, you can read
```suggestion
If the MASK bit was set (and it should be, for client-to-server messages), read the next 4 octets (32 bits); this is the masking key. Once the payload length and masking key is decoded, you can read that number of bytes from the socket. Let's call the data `ENCODED`, and the key `MASK`. To get `DECODED`, loop through the octets (bytes a.k.a. characters for text data) of `ENCODED` and XOR the octet with the (i modulo 4)th octet of `MASK`. In pseudo-code (that happens to be valid JavaScript):
```

2022-08-13 05:39 UTC, teoli2003 commented on files/en-us/web/api/websockets_api/writing_websocket_servers/index.md
> +### Reading and unmasking the Data
```suggestion
### Reading and unmasking the data
```

2022-08-13 05:39 UTC, teoli2003 commented on files/en-us/web/api/websockets_api/writing_websocket_servers/index.md
> +If the MASK bit was set (and it should be, for client-to-server messages), read the next 4 octets (32 bits); this is the masking key. Once the payload length and masking key is decoded, you can read
yeah, I didn't have the impression it was pseudo-code from the start.

2022-08-13 05:47 UTC, Josh-Cena commented on files/en-us/web/api/web_audio_api/using_audioworklet/index.md
> +      for (let i = 0; i < input[channelNum].lengt; i++) {
```suggestion
      for (let i = 0; i < input[channelNum].length; i++) {
```

2022-08-13 05:47 UTC, Josh-Cena approved these changes
LGTM

2022-08-13 05:48 UTC, merged