Avoid classical for if for...of when looping all object of an Array-like object (part #2)
mdn/content pull request #19405
Opened 2022-08-11 10:01 UTC by teoli2003

Classical `for` loops are error-prone (setting the right condition, not mixing indices…) and difficult to read when used to loop on all elements of an Array-like structure.

This PR changes some occurrences to use the modern `for…of`, or `.forEach()` in some occurrences.

Note that:
- I use `for…of` if I don't need the index
- I use `.forEach()` when I do, or on an object where `for…of` may not work.
- There were a couple of cases where the loop copied an Array into a new one; I used `Array.from()` instead.

2022-08-11 18:29 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/duration/index.md
> +  methods.forEach((meth) => {
Ok, ok, ok, done 😉

2022-08-12 03:16 UTC, Josh-Cena requested changes
Not a thorough review; would go over this again after the initial reviews are addressed

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentries/index.md
> +    checkPerformanceEntry(entry);
Is `checkPerformanceEntry` a fictitious function?

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentries/index.md
> +  perf.forEach((entry, i) => {
I don't think we actually need the `perf` variable now that we use `forEach`. Just do `performance.getEntries().forEach(...)`

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/duration/index.md
> +  methods.forEach((meth) => {
`method`? (Same for the line below)

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/duration/index.md
> +  properties.forEach((property) => {
I can at least say that `prop` is a pretty well-understood abbreviation

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performancenavigationtiming/dominteractive/index.md
> +    console.log(`DOM interactive = ${p.interactive}`);
Not sure, just flagging this change

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +  for (const entry of entries) {
```suggestion
  for (const entry of performance.getEntriesByType("resource")) {
```

2022-08-12 03:16 UTC, Josh-Cena commented on files/en-us/web/api/texttrack/mode/index.md
>    };
```suggestion
  for (const cue of track.cues) {
    cue.pauseOnExit = true;
  }
```

2022-08-12 09:11 UTC, teoli2003 commented on files/en-us/web/api/performance/getentries/index.md
> +    checkPerformanceEntry(entry);
It isn't. It is on some pages, not on others. I'll add it on all.

2022-08-12 09:58 UTC, teoli2003 commented on files/en-us/web/api/performancenavigationtiming/dominteractive/index.md
> +    console.log(`DOM interactive = ${p.interactive}`);
Strange, there were several of these. It is `domInteractive` (I think it was wrong on the one I copied…)

2022-08-12 10:56 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/duration/index.md
> +  properties.forEach((property) => {
I use `method`, so I kept `property` for symmetry.

2022-08-12 10:57 UTC, teoli2003 commented on files/en-us/web/api/performanceentry/duration/index.md
> +  methods.forEach((meth) => {
Fixed

2022-08-13 05:10 UTC, teoli2003 commented on files/en-us/web/api/performance/getentriesbyname/index.md
> -  p = performance.getEntries({name : "Begin", entryType: "mark"});
I've added it back

2022-08-13 05:12 UTC, teoli2003 commented on files/en-us/web/api/performance/getentriesbytype/index.md
> -  p = performance.getEntries({name : "Begin", entryType: "mark"});
Readded

2022-08-13 05:14 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/workerstart/index.md
> -                "workerStart"];
No, bad copy and paste (I wonder if we need to keep this a loop and not only present the property demonstrated on the page.

2022-08-13 05:51 UTC, Josh-Cena commented on files/en-us/web/api/pointer_events/pinch_zoom_gestures/index.md
> + for (const i in evCache) {
Don't use for...in on arrays

2022-08-13 05:51 UTC, Josh-Cena commented on files/en-us/web/api/pointer_events/multi-touch_interaction/index.md
> + for (const i in cache) {
Don't use for...in on arrays

2022-08-13 05:52 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/workerstart/index.md
> +    console.log(`… ${property} = ${property in PerfEntry ? value : "NOT supported"}`);
```suggestion
    console.log(`… ${property} = ${property in perfEntry ? value : "NOT supported"}`);
```

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/transfersize/index.md
> +function logSizes(perfEntry){
```suggestion
function logSizes(perfEntry) {
```

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/transfersize/index.md
> +  console.log(`decodedBodySize = ${"decodedBodySize" in perfEntry ? perfEntry.decodedBodySize : "NOT supported"}`);
What about

```suggestion
  console.log(`decodedBodySize = ${perfEntry.decodedBodySize ?? "NOT supported"}`);
```

The only difference is if the key actually exists but has value `undefined`. Looks impossible to happen in this case.

The same suggestion applies to everywhere else we are using `in` test.

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/responsestart/index.md
> +    console.log(`… ${property} = ${property in PerfEntry ? value : "NOT supported"}`);
```suggestion
    console.log(`… ${property} = ${property in perfEntry ? value : "NOT supported"}`);
```

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/secureconnectionstart/index.md
> +    console.log(`… ${property} = ${property in PerfEntry ? value : "NOT supported"}`);
```suggestion
    console.log(`… ${property} = ${property in perfEntry ? value : "NOT supported"}`);
```

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/responseend/index.md
> +    console.log(`… ${property} = ${property in PerfEntry ? value : "NOT supported"}`);
```suggestion
    console.log(`… ${property} = ${property in perfEntry ? value : "NOT supported"}`);
```

And a lot of other occurrences

2022-08-13 05:57 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/nexthopprotocol/index.md
> +  console.log(`nextHopProtocol = ${value ? perfEntry.nextHopProtocol: "NOT supported"}`);
This looks asymmetric to what we are doing everywhere else.

```js
  console.log(`nextHopProtocol = ${perfEntry.nextHopProtocol ?? "NOT supported"}`);
```

2022-08-13 05:58 UTC, teoli2003 commented on files/en-us/web/api/pointer_events/pinch_zoom_gestures/index.md
> + for (const i in evCache) {
Replaced with a forEach, but I don't find it very beautiful, I don't know why.

2022-08-13 06:15 UTC, Josh-Cena commented on files/en-us/web/api/pointer_events/pinch_zoom_gestures/index.md
>       break;
Actually this entire thing is

```js
const index = evCache.findIndex((cachedEv) => cachedEv.pointerId === ev.pointerId);
evCache[index] = ev;
```

2022-08-13 06:15 UTC, Josh-Cena commented on files/en-us/web/api/pointer_events/pinch_zoom_gestures/index.md
>       break;
Ditto here:

```js
const index = evCache.findIndex((cachedEv) => cachedEv.pointerId === ev.pointerId);
evCache.splice(index, 1);
```

2022-08-13 06:30 UTC, teoli2003 commented on files/en-us/web/api/pointer_events/pinch_zoom_gestures/index.md
>       break;
Oh! `findIndex()` is the one I missed.

2022-08-13 06:54 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/transfersize/index.md
> +  console.log(`decodedBodySize = ${"decodedBodySize" in perfEntry ? perfEntry.decodedBodySize : "NOT supported"}`);
Yes! This is much better.

2022-08-13 07:13 UTC, teoli2003 commented on files/en-us/web/api/performanceresourcetiming/connectstart/index.md
> +  for (const property of properties) {
```suggestion

  for (const property of properties) {
```

2022-08-13 07:42 UTC, teoli2003 commented on files/en-us/web/api/report/index.md
> +    for (const key in report.body) {
@Josh-Cena Is this `for…in` ok. It is not a recent change.

2022-08-19 07:26 UTC, teoli2003 commented
@Josh-Cena I think this one is good to do.

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentries/index.md
> +      log(`Entry[${i}]`);
Should this still be `console.log`? (Can't find where `log` is defined)

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbyname/index.md
>    }
```suggestion
    });
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbyname/index.md
> +  performance.getEntries({name : "Begin", entryType: "mark"})
```suggestion
  performance.getEntries({ name: "Begin", entryType: "mark" })
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbytype/index.md
> +  performance.getEntries({name : "Begin", entryType: "mark"})
```suggestion
  performance.getEntries({ name: "Begin", entryType: "mark" })
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbytype/index.md
>    }
```suggestion
    });
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance_timeline/using_performance_timeline/index.md
>    for (let i=0 ; i < n; i++) {
```suggestion
function doWork(n) {
  for (let i = 0; i < n; i++) {
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/duration/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance_timeline/using_performance_timeline/index.md
> +  observeMark.observe({entryTypes: ['mark']});
```suggestion
  observeMark.observe({ entryTypes: ['mark'] });
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance_timeline/using_performance_timeline/index.md
> +  observeAll.observe({entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server']});
```suggestion
  observeAll.observe({
    entryTypes: ['frame', 'mark', 'measure', 'navigation', 'resource', 'server'],
  });
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performance_timeline/using_performance_timeline/index.md
> +    perfEntries.forEach((entry) =>  {
The `perfEntries` variable can be removed

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/entrytype/index.md
> +  entriesNamedBegin = performance.getEntriesByName("begin")
```suggestion
  performance.getEntriesByName("begin")
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/name/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/starttime/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceentry/tojson/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performancenavigationtiming/redirectcount/index.md
> +    perfEntries.forEach((p, i) => {
```suggestion
    .forEach((p, i) => {
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +function logSizes(entry){
```suggestion
function logSizes(entry) {
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/encodedbodysize/index.md
> +function logSizes(entry){
```suggestion
function logSizes(entry) {
```

2022-08-23 12:39 UTC, Josh-Cena commented on files/en-us/web/api/performanceresourcetiming/redirectend/index.md
> +for (const property of properties) {
```suggestion
  for (const property of properties) {
```

2022-08-23 12:41 UTC, teoli2003 commented on files/en-us/web/api/performance/getentries/index.md
> +      log(`Entry[${i}]`);
That's an extract of another example. Let's use `console.log()` here instead.

2022-08-23 12:51 UTC, teoli2003 commented on files/en-us/web/api/performance/getentries/index.md
> +      log(`Entry[${i}]`);
Fixed (except in one file that was defining log())

2022-08-23 13:08 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentries/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 13:08 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbyname/index.md
> +      lconsole.og(`Mark and Begin entry[${i}]:`);
```suggestion
      console.log(`Mark and Begin entry[${i}]:`);
```

2022-08-23 13:08 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbytype/index.md
> +    console.log(`…${method} = ${supported ? obj[method] : "Not supported"}`);
```suggestion
    console.log(`…${method} = ${supported ? JSON.stringify(obj[method]()) : "Not supported"}`);
```

2022-08-23 13:08 UTC, Josh-Cena commented on files/en-us/web/api/performance/getentriesbytype/index.md
> +      lconsole.og(`Begin[${i}]`);
```suggestion
      console.log(`Begin[${i}]`);
```

2022-08-25 09:27 UTC, teoli2003 commented
@Josh-Cena When you have time, can you double-check this PR. I think I have fixed all the review comments.

2022-08-26 03:53 UTC, Josh-Cena commented
Sorry for being a little slow. My academic life is picking up and I don't always have access to a computer this week. This PR has a lot of moving parts and reviewing takes some mental energy. I'll try putting aside some time tomorrow.

2022-08-26 05:16 UTC, teoli2003 commented
> Sorry for being a little slow. My academic life is picking up and I don't always have access to a computer this week. This PR has a lot of moving parts and reviewing takes some mental energy. I'll try setting aside some time tomorrow.

No worry, I guessed your academic life started again. Take your time.

2022-08-30 12:15 UTC, teoli2003 commented on files/en-us/web/api/touch_events/multi-touch_interaction/index.md
> +    tpCache.forEach((tp, i) => {
I like this: it should work, and `findLastIndex` is likely optimized so it may be even quicker (but not slower).

Note that this is a recent addition (ES2022) and the last of four major browsers (Firefox) has supported it only since last Tuesday.

Creating a commit for this.

2022-09-02 21:01 UTC, Josh-Cena approved these changes
Sorry for being so slow to get to this. This looks great to me (had to go through a lot of code that looks almost the same...)

2022-09-02 21:03 UTC, merged