Issue19425
mdn/content pull request #19463
Opened 2022-08-12 14:04 UTC by thedivloop

#### Summary

Replaced squirrelfont by dafont source websites.
It seems squirrelfont has issues on the download button of several fonts including the 2 used in the example.

#### Motivation

Now the reader can follow the steps with no 404 page case.

#### Supporting details

#### Related issues

Fixes #19425 

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-12 14:31 UTC, thedivloop commented
> * Link points to the page it's already on

The only place it points back to the same page is in the bottom under "In this module" Styling web forms. Shall the link be remove? I haven't touched that part.

2022-08-16 12:40 UTC, Rumyra commented
Hi @thedivloop thanks for updating the links - the example on the page is here https://github.com/mdn/learning-area/tree/main/html/forms/postcard-example - could you update the fonts there as well for consistency? Thanks

2022-08-16 12:41 UTC, Rumyra requested changes

2022-08-30 13:49 UTC, Rumyra approved these changes

2022-08-30 13:49 UTC, merged