Fixes formatting in wsg and adds a code example guideline
mdn/content pull request #19466
Opened 2022-08-12 14:13 UTC by dipikabh

#### Summary

This PR is essentially to update the writing 'code example' guidelines in our writing style guide. Added the following as per @estelle's suggestion:
"In general, the code example should not only demonstrate the syntax of the feature and how it is used, but also highlight the purpose and situations in which a web developer might want or need to use the feature."

This PR also fixes some of the following issues in the writing style guide:
- Removes the unnecessary indent characters `>`.
- Changes some H4s to bullet points because we're recommending in the style guide to not go lower than three heading levels.
- Changes some H4s to H3s by removing the parent H3.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [X] Fixes a typo, bug, or other error

2022-08-12 14:26 UTC, teoli2003 requested changes
A nit and this is good to go.

2022-08-12 14:26 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- **Avoid using macros within headings.** (Except for certain macros that are specifically designed to be used in headings).
We don't have such macro anymore.

```suggestion
- **Avoid using macros within headings.** Ever.
```

2022-08-15 09:51 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- **Avoid using macros within headings.** (Except for certain macros that are specifically designed to be used in headings).
I combined this with the previous point as "**Don't use styles, classes, or macros within headings.**

2022-08-15 10:05 UTC, dipikabh commented
Thanks @teoli2003 for reviewing these changes 🙏!

2022-08-15 10:06 UTC, teoli2003 approved these changes
👍 (You are lucky I saw it today, it is a bank holiday here :-) )

2022-08-15 10:06 UTC, merged