Add MathML tutorial
mdn/content pull request #19467
Opened 2022-08-12 14:47 UTC by fred-wang

#### Summary

An introduction to basic MathML constructions.
This only introduces the "first steps" module but
more advanced topics may be added in the future.

#### Motivation

Chromium is expected to ship MathML soon, and it is likely that
developers read the documentation as suggested in the
Intent-to-ship thread [1]. Although we've been updating existing
MDN documentation it may still be difficult for people new to MathML
to learn about it. This PR addresses that by following the same
structure as HTML, CSS and JavaScript tutorials.

#### Supporting details

[1] https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA

#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-12 14:49 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/fractions_and_roots/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:49 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/fractions_and_roots/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:50 UTC, fred-wang commented
I'll be off for one week but I wanted to make people aware of that. Probably more tweaks are needed (like copying some examples to https://github.com/mdn/learning-area).

cc @bkardell @teoli2003

2022-08-12 14:50 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/fractions_and_roots/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:50 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/getting_started/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:52 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:53 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:54 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:56 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:56 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 14:57 UTC, MrBrain295 commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +<html>
```suggestion
<html lang="en-US">
```

2022-08-12 16:06 UTC, Josh-Cena commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +> HTML elements [`<sub>`](/en-US/docs/Web/HTML/Element/sup) and
```suggestion
> HTML elements [`<sup>`](/en-US/docs/Web/HTML/Element/sup) and
```

2022-08-12 19:16 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +> HTML elements [`<sub>`](/en-US/docs/Web/HTML/Element/sup) and
fixed, but tried to keep the order sub/sup.

2022-08-13 04:06 UTC, Josh-Cena commented
@fred-wang Thank you so much for this PR! I'm excited. I've run the formatter on these files. Some general points:

- `_` for italic and `-` for bullet points
- The style guide says no typography in headings—not even inline code (yeah...)
- The prose should not be wrapped. Some may have a line break after every full stop—but we never break within a sentence.

The content is great. I learned a lot.

2022-08-13 07:42 UTC, fred-wang commented
Thanks @Josh-Cena ! One silly question: how I can run the formatter myself?

2022-08-13 07:44 UTC, Josh-Cena commented
I don't think we have tooling in the repo itself yet. I'm using [Prettier](https://www.npmjs.com/package/prettier)—you can run `npm i -g prettier`, and then `prettier -w  files/en-us/learn/mathml/`. Or if you are using VS Code, you can also right click and select "format document".

2022-08-13 08:19 UTC, fred-wang commented
@bkardell mentioned that using "display mode" (which is a LaTeX term) is a bit confusing since in CSS you have a property called display and it has inline|block, and even MathML Core has the display attribute which is inline|block and not inline|display. So I tweaked the text to not use inline/display modes.

2022-08-13 08:35 UTC, fred-wang commented
An additional question / remark that is recurrent for MathML articles: the content does not seem to show up in the sidebar. Not sure what is missing to make that happen.

2022-08-16 12:32 UTC, Rumyra commented
Hi @fred-wang - the `{{LearnSidebar}}` which these pages use is here: https://github.com/mdn/yari/blob/main/kumascript/macros/LearnSidebar.ejs

It can be updated with these pages once they are merged. Maybe between Accessibility and Tools & Testing?

2022-08-24 16:46 UTC, fred-wang commented
@Rumyra Thanks, I uploaded a tentative PR at https://github.com/mdn/yari/pull/6953 ; but not sure how I can test that.

2022-09-01 12:21 UTC, caugner commented
@fred-wang If you have addressed all the review threads, you can re-request a review using the arrow symbol on the top-right:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/495429/187912431-5d8f5c77-e443-4db1-8bc6-2840e3b10121.png">

2022-09-01 12:33 UTC, fred-wang commented
@caugner Thanks, done.

2022-09-02 14:16 UTC, Rumyra requested changes

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/fractions_and_roots/index.md
> +```
I don't think we need to show the whole html page in this example - everything in `<math>` is fine and reads easier - same for the next example

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +We continue the review of basic math notations and focuses on building MathML elements with scripts.
```suggestion
We continue the review of basic math notations and focus on building MathML elements with scripts.
```

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +Below is the rendering of the above example in your browser. You should notice that:
Move the image below this line and break it so:

Below is the rendering of the above example in your browser.
_Image here_
You should notice that:

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +This is again similar to [HTML's article](/en-US/docs/Learn/HTML/Tables/Basics#allowing_cells_to_span_multiple_rows_and_columns). The `<mtd>` element accepts the `columnspan` and `rowspan` attributes
```suggestion
This is again similar to [HTML tables](/en-US/docs/Learn/HTML/Tables/Basics#allowing_cells_to_span_multiple_rows_and_columns). The `<mtd>` element accepts the `columnspan` and `rowspan` attributes to indicate that the cell spans multiples rows and columns. Below the inner matrix spans two columns of the outer matrix:
```

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/three_famous_mathematical_formulas/index.md
> +![Screenshot of the PDF output generated by XeLaTeX](xelatex-output.png)
Is this ok to use copyright wise? Should it have an attribution?

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/index.md
> +Mathematical Markup Language — or {{glossary("MathML")}} — is the markup language used to write mathematical formulas in Web pages using fractions, scripts, radicals, matrices, integrals, series, etc
```suggestion
Mathematical Markup Language — or {{glossary("MathML")}} — is the markup language used to write mathematical formulas in web pages using fractions, scripts, radicals, matrices, integrals, series, etc. Although it was originally designed as an independent XML language, MathML is generally embedded inside {{Glossary('HTML')}} documents and can be seen as an extension of HTML.
```

2022-09-02 14:16 UTC, Rumyra commented on files/en-us/learn/mathml/index.md
> +This topic contains the following modules, in a suggested order for working through them. You should definitely start with the first one.
There's only one module so this line doesn't make to much sense

2022-09-02 14:16 UTC, Rumyra commented
Thanks @fred-wang this looks really good! I've had a read through and added some suggestions 👍

2022-09-02 14:48 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/index.md
> +> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program s
Sounds good to me, but just not this is copied from other tutorials:

```
fred@igalia-fwang:~/src-obj/mdn/content/files/en-us/learn$ find -type f | xargs grep 'If you are working on a computer/tablet/other device'
./accessibility/index.md:> **Note:** If you are working on a computer/tablet/other devices where you don't have the ability to create your own files, you can try out most of the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./forms/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./css/building_blocks/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./css/first_steps/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./css/css_layout/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./css/styling_text/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./javascript/building_blocks/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./javascript/first_steps/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./javascript/asynchronous/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you can try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com).
./javascript/objects/index.md:> **Note:** If you are working on a computer/tablet/other devices where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./html/tables/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./html/introduction_to_html/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
./html/multimedia_and_embedding/index.md:> **Note:** If you are working on a computer/tablet/other device where you don't have the ability to create your own files, you could try out (most of) the code examples in an online coding program such as [JSBin](https://jsbin.com/) or [Glitch](https://glitch.com/).
```

2022-09-02 14:51 UTC, fred-wang commented on files/en-us/learn/mathml/index.md
> +This topic contains the following modules, in a suggested order for working through them. You should definitely start with the first one.
Right, this is copied from other tutorials, the plan is to add more module later but we can remove that for now if that's confusing.

2022-09-02 14:56 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/three_famous_mathematical_formulas/index.md
> +![Screenshot of the PDF output generated by XeLaTeX](xelatex-output.png)
All these math formulas are public domain, I wrote the LaTeX source file and generated the PNG image with XeLaTeX (open source tool) so AFAIK no attribution is needed, unless I'm missing something...

2022-09-02 15:45 UTC, bkardell commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +> **Note:** The MathML elements `<msub>` and `<msup>` are different from the HTML elements [`<sub>`](/en-US/docs/Web/HTML/Element/sub) and [`<sup>`](/en-US/docs/Web/HTML/Element/sup). They allow to u
"They allow to use" needs help - perhaps "They allow the use of" or "They allow authors to provide"

2022-09-02 15:53 UTC, bkardell commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +So far our example has actually been rendered with the [`display="block"`](/en-US/docs/Learn/MathML/First_steps/Getting_started#the_display_attribute) attribute. Let's detach it from the `<math>` ele
I think "Let's detach it" is somewhat confusing - it sounds like a DOM operation on an existing tree rather than simply not including it in the first place. I feel like this could be more intuitively phrased as something like "Let's look at the same example, as rendered without the [`display="block"`](/en-US/docs/Learn/MathML/First_steps/Getting_started#the_display_attribute) attribute." or something?

Probably could use a second opinion on that I guess - @Rumyra ?

2022-09-02 15:59 UTC, bkardell commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +The MathML tabular elements are similar to the ones for [HTML tables](/en-US/docs/Learn/HTML/Tables): the `<mtable>` element represents a table, the `<mtr>` element represents a row and the `<mtd>` e
Super minor, I guess, but is it worth saying "mathematical table" and "mathematical row"? Also, even more minor - should we put the word data in here for cells? `td` in html is a "table data cell" - I've heard over the years "I get tr means table row, but why td?"

2022-09-02 16:11 UTC, bkardell commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +> **Warning:** The [`<mtable>` article](/en-US/docs/Web/MathML/Element/mtable) provides more advanced layout options via special attributes such as alignment or spacing. This is inherited from the or
s/that was supposed to work in engines that are not CSS-aware/These originated before CSS equivalents and were originally designed and intended for renderers which were not-CSS aware.

2022-09-02 16:19 UTC, bkardell commented on files/en-us/learn/mathml/first_steps/text_containers/index.md
> +- The `<mi>` element, which represents a symbolic name or arbitrary text that should be rendered as an identifier. Examples: `<mi>x</mi>` (variable), `<mi>cos</mi>` (function name) and `<mi>π</mi>` (
I wonder if it is worth rearranging this to move "identifier" forward and quote it similarly to what happens in `<mn>` in the next line... I feel like it is helpful to learning and remembering element names if you can easily attach them to some meaning/device - "math identifier" "math number" "math operator".

 The `<mi>` element represents an "identifier" which could be a symbolic name or arbitrary text. Examples: `<mi>x</mi>` (variable), `<mi>cos</mi>` (function name) and `<mi>π</mi>` (symbolic constant).

2022-09-02 16:23 UTC, bkardell commented
I also left some review comments - most of them very minor and probably even debtable/opinionated.  Other than that, lgtm!

2022-09-03 05:34 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/text_containers/index.md
> +- The `<mi>` element, which represents a symbolic name or arbitrary text that should be rendered as an identifier. Examples: `<mi>x</mi>` (variable), `<mi>cos</mi>` (function name) and `<mi>π</mi>` (
OK done, this text was taken from the MathML3 spec and is duplicated in MathML Core/Full btw.

2022-09-03 05:38 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +The MathML tabular elements are similar to the ones for [HTML tables](/en-US/docs/Learn/HTML/Tables): the `<mtable>` element represents a table, the `<mtr>` element represents a row and the `<mtd>` e
I tweaked to say "mathematical table", but not sure it's necessary to be verbose and say "mathematical table row" or "mathematical table data cell". In this paragraph we assume the reader is already familiar with HTML table (or can read the doc) so this is just saying "it's the same but with a prefixed m". The explanation is now:

> The MathML tabular elements are similar to the ones for [HTML tables](/en-US/docs/Learn/HTML/Tables): the `<mtable>` element represents a mathematical table, it has `<mtr>` elements as its children (representing rows), each of them having `<mtd>` elements as its children (representing cells).

2022-09-03 05:38 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/tables/index.md
> +> **Warning:** The [`<mtable>` article](/en-US/docs/Web/MathML/Element/mtable) provides more advanced layout options via special attributes such as alignment or spacing. This is inherited from the or
Done.

2022-09-03 05:38 UTC, fred-wang commented on files/en-us/learn/mathml/first_steps/scripts/index.md
> +So far our example has actually been rendered with the [`display="block"`](/en-US/docs/Learn/MathML/First_steps/Getting_started#the_display_attribute) attribute. Let's detach it from the `<math>` ele
Done.

2022-09-03 05:41 UTC, fred-wang commented
@bkardell  @Rumyra Thanks for your feedback. I believe I've addressed all (most?) of them. Please take a look again, thanks!

2022-09-05 09:58 UTC, teoli2003 approved these changes

2022-09-05 10:31 UTC, fred-wang commented
Thanks @teoli2003 

It seems this is still blocked on @Rumyra's approval. I believe the only change not address is the question about the copyright, which I explained is not a concern.

2022-09-05 11:23 UTC, Rumyra commented on files/en-us/learn/mathml/first_steps/three_famous_mathematical_formulas/index.md
> +![Screenshot of the PDF output generated by XeLaTeX](xelatex-output.png)
👍

2022-09-05 11:24 UTC, Rumyra approved these changes

2022-09-05 11:24 UTC, merged

2022-09-06 12:47 UTC, caugner commented
@fred-wang FYI The MathML tutorial is not mentioned in the [Topics covered](https://developer.mozilla.org/en-US/docs/Learn#topics_covered) section of the [Learn web development](https://developer.mozilla.org/en-US/docs/Learn) page yet.

The [Web performance](https://developer.mozilla.org/en-US/docs/Learn/Performance) guide, on the other hand, is listed there but not yet in the sidebar.

2022-09-06 12:50 UTC, fred-wang commented
@caugner Thanks, will check that.

2022-09-06 13:11 UTC, fred-wang commented
I opened https://github.com/mdn/content/pull/20349