Fix code block tags
mdn/content pull request #19542
Opened 2022-08-14 10:09 UTC by rubiesonthesky

#### Summary

Fixes some incorrect code block tags. 

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-14 10:19 UTC, Josh-Cena reviewed
Let's say: "plain" for code blocks that should be other languages (just aren't enabled), and no language tag for code blocks that actually does not represent any code? In Yari there's a comment saying marking "plain" is really subpar.

2022-08-14 10:20 UTC, Josh-Cena commented on files/en-us/web/http/headers/content-security-policy/index.md
> +    > ```plain
Why isn't this HTTP? Ditto for a few ones below

2022-08-14 12:44 UTC, Josh-Cena commented
That's just my own little wishful convention that I'm not sure anyone else follows. But rest assured that "plain" shouldn't be encouraged.

2022-08-19 17:13 UTC, jpmedley requested changes
Good work here, there's just one punctuation change.

2022-08-19 17:13 UTC, jpmedley commented on files/en-us/web/http/proxy_servers_and_tunneling/index.md
> +The auto-config file should be saved to a file with a `.pac` filename extension, `proxy.pac`.
```suggestion
The auto-config file should be saved to a file with a `.pac` filename extension,: `proxy.pac`.
```

2022-08-19 17:13 UTC, jpmedley commented on files/en-us/web/http/proxy_servers_and_tunneling/index.md
> +The auto-config file should be saved to a file with a `.pac` filename extension, `proxy.pac`.
I don't believe MDN has a policy on situations such as this. I agree with your change. I personally dislike it when a sentence straddles an example.

2022-08-19 17:13 UTC, jpmedley commented on files/en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file/index.md
> +The auto-config file should be saved to a file with a .pac filename extension, `proxy.pac`.
```suggestion
The auto-config file should be saved to a file with a .pac filename extension: `proxy.pac`.
```

2022-08-22 15:39 UTC, jpmedley approved these changes

2022-08-22 15:39 UTC, merged