Fix description of regex flags
mdn/content pull request #19540
Opened 2022-08-14 08:19 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #1454 (finally!)
Fix #19524 — flags are changed to accessor properties in ES6.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-14 09:04 UTC, Phosra commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +title: get RegExp.prototype.sticky
Ooh, I have not seen `get` used in any MDN titles yet... isn't such an introduction pending the discussion about prototype accessors vs own properties?

2022-08-14 09:04 UTC, Phosra commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
I suspect that the term "getter-only" may not be friendly towards beginners. Any thoughts on this?

2022-08-14 09:05 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +title: get RegExp.prototype.sticky
No, `get` is already used in `@@species`. I think it makes sense to update these.

2022-08-14 09:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
The fact that no-one complains up till now probably means these pages are non-starter from the beginning, so I guess it's fine. Most would read the guide anyway.

2022-08-14 09:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/unicode/index.md
> +- When [`lastIndex`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) is automatically advanced (such as when calling [`exec()`](/en-US/docs/Web/JavaScript/Reference/Global_Objec
`lastIndex` still returns the UTF-16 index. It just may advance by 2 in case of a surrogate pair.

2022-08-15 00:00 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
How is "getter-only" different from read-only? i.e. it is far more common to see something like:

> The `RegExp.prototype.sticky` is a read-only property returns `true` ...

And in the parent doc you'd have the `{{readonly_inline}}` macro

2022-08-15 00:03 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/dotall/index.md
> +title: get RegExp.prototype.dotAll
I have never seen `get` used in a title in MDN. 

Generally JavaScript has been treated as a little bit special in that it remains closer to spec language that the web api docs.  In my strong opinion this might be fine, but it should be raised as a discussion and agreed, not added by magic.

@wbamberg might have an opinion

2022-08-15 00:05 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/dotall/index.md
> +title: get RegExp.prototype.dotAll
Further, if we're going to change the rules, then they should be changed across the docset and reflected in the template guidance for javascript thingies.

It is possible this has been done of course, and I just missed it.

2022-08-15 00:10 UTC, Phosra commented on files/en-us/web/javascript/reference/global_objects/regexp/dotall/index.md
> +title: get RegExp.prototype.dotAll
> Further, if we're going to change the rules, then they should be changed across the docset and reflected in the template guidance for javascript thingies.
> 
> It is possible this has been done of course, and I just missed it.

See <https://github.com/mdn/content/pull/19540#discussion_r945255442>

2022-08-15 00:41 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +title: get RegExp.prototype.sticky
Was that broadly agreed in `@@species` or did it just just sneak in? 

I have no care factor about what syntax we use, but it shouldn't appear by magic - it should be discussed (and not just in one PR). If agreed it should be updated in the contributor docs so that we're all on the same page. IN addition, we should identify all the cases that need updating and do them as a project.

If there was extensive discussion and this is all documented and well understood. Apologies. Don't know how I missed it.

I made a similar comment above - just linking so no need to respond in both places https://github.com/mdn/content/pull/19540#discussion_r945361015

2022-08-15 02:27 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
Not much. "Read-only" is for data properties, "getter-only" is for accessor properties; but when you use them they are pretty much interchangeable.

2022-08-15 02:36 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +title: get RegExp.prototype.sticky
`@@species` seems to just have been like that from the start. Plus we just don't have an agreed-upon notation for _any_ property. (cf https://github.com/mdn/mdn-community/discussions/153)

I really don't have strong opinions about whether we prefix getter-only properties with `get`, but this seems like a really low-bar change compared to marking up instance properties. If others feel like the change is too bold I can revert it for now.

2022-08-15 02:56 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
I'm just not sure it is a useful distinction. If it isn't, then better to make things consistent. If it is, then great - but we need to agree how and document that approach.

Can you add it a discussion o how you want things to be and why? Then we can discuss and update the guides.

2022-08-15 02:59 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
Let's discuss in https://github.com/mdn/mdn-community/discussions/195. If others also feel strongly about this change I can revert it (at best aligning with what we do with other getter-only properties like `%TypedArray%.p.length`) so we can get the important pieces in.

2022-08-15 03:05 UTC, hamishwillee commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +`RegExp.prototype.sticky` is a getter-only property that returns `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that it matches only from the index indicated by the {{jsx
Absolutely.

2022-08-26 03:37 UTC, Josh-Cena commented
I've hopefully made the content a little clearer and reverted the title changes. I intend to re-propose this sometime in the future when I have more energy.

2022-08-27 16:04 UTC, Josh-Cena commented
Minor ping for @wbamberg in case you have any feedback on this ^^ The wording change here is pretty important and it's a shame to be delayed so long (the issue has remained for a year and a half)

2022-08-30 03:15 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/regexp/dotall/index.md
> +title: get RegExp.prototype.dotAll
Yeah, I agree with Hamish that we should do this in an agreed and organized way. Without that I'm -1 on `get` here.

2022-08-30 04:43 UTC, wbamberg requested changes
Mostly copy-edits, though I had a bigger comment on the sticky page. But it's a use-it-or-not-as-you-wish type of thing.

2022-08-30 04:43 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +The set accessor of `sticky` is `undefined`. You cannot change this property directly.
I found this quite hard going and only really understood it after reading https://2ality.com/2020/01/regexp-lastindex.html. 

I think that as most of it is contrasting sticky and global regexes, it might be worth explicitly signposting that - it's really buried a bit half way through para 2. I did actually have a go at this:

```
## Description

`RegExp.prototype.sticky` has the value `true` if the `y` flag was used; otherwise, `false`. The `y` flag indicates that the regex attempts to match the target string only from the index indicated by the {{jsxref("RegExp.lastIndex", "lastIndex")}} property (and unlike a global regex, does not attempt to match from any later indexes).

The set accessor of `sticky` is `undefined`. You cannot change this property directly.

### Sticky and global regexes

Sticky regexes and [global](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) regexes both start matching at `lastIndex`, but:

- When the [`exec()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) method is called on a sticky regex, if the regex fails to match at `lastIndex`, then the regex immediately returns `null` and resets `lastIndex` to 0.

- When the [`exec()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) method is called on a global regex, if the regex fails to match at `lastIndex`, then the regex tries to match from the next character, and so on until a match is found or the end of the string is reached.

For both sticky and global regexes:

- When the match succeeds, `lastIndex` is advanced to the end of the match.
- When `lastIndex` is out of bounds of the currently matched string, `lastIndex` is reset to 0.

For the [`exec()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) method, a regex that's both sticky and global behaves the same as a sticky and non-global regex. However, due to many other methods special-casing the behavior of global regexps, the global flag is, in general, orthogonal to the sticky flag. For more information about how each individual regex-related method (such as [`String.prototype.match()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) and [`String.prototype.replace()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)) interact with the sticky and global flags, see their respective pages.
```

Feel free to ignore this if you think I have mangled the sense of it though.

I also consistently used "regex" and "regexes" instead of "regexps" which is hard to read, and linked only the first occurrences of terms like `lastIndex`.

I still think the last paragraph is a bit problematic - as a reader I don't know really what I am supposed to do with something like "due to many other methods special-casing the behavior of global regexps, the global flag is, in general, orthogonal to the sticky flag". But I also don't know what to do about it.

It's also not ideal that the first of the linked pages here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match  - doesn't mention sticky, and the second -  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace - sends me to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@replace.

2022-08-30 04:45 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/source/index.md
> +The **`source`** accessor property is a string containing the source text of the regexp object, without the two forward slashes on both sides or any flags.
Yeah... It's a really tough one to decide. "Regexes" is a bit awkward so I usually use "regexps" instead.

2022-08-30 04:48 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +The set accessor of `sticky` is `undefined`. You cannot change this property directly.
Indeed. In my past string/regex refactors, I have consistently pointed the string methods to their regex counterparts if the latter exist. I think I would do an exhaustive comparison for all methods.

2022-08-30 05:01 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/regexp/source/index.md
> +The **`source`** accessor property is a string containing the source text of the regexp object, without the two forward slashes on both sides or any flags.
I guess this is subjective :) but I think "regexps" is worse. Internally pronouncing "exps" hurts my brain.

2022-08-30 21:07 UTC, wbamberg approved these changes
👍 thank you @Josh-Cena !

2022-08-30 21:07 UTC, merged