Document import assertions
mdn/content pull request #19588
Opened 2022-08-15 13:01 UTC by Josh-Cena

#### Summary

#### Motivation

Fix #19220

#### Supporting details

#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-15 13:02 UTC, Josh-Cena commented
Pending: some more sources to the HTML specification, especially around JSON modules. I don't know the HTML spec that well

2022-08-15 16:47 UTC, Josh-Cena commented
cc @jpmedley in case this needs some attention from V8 since they are the only ones implementing this so far.

2022-08-15 17:02 UTC, jpmedley commented
I'm not up to speed on this. I've asked my team for help.

2022-09-07 04:55 UTC, teoli2003 requested changes
Note that bcd data may be incomplete, hence some comments here

2022-09-07 04:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
If I look at the bcd table, all engines listed there support the `options` parameter, don't they?

2022-09-07 04:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the appendices of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The follow keys are recognized:
```suggestion
  - : An object containing import options, which correspond to the appendices of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
```

2022-09-07 04:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +title: import assertions
Capitalization looks strange here. 
```suggestion
title: Import assertion
```

2022-09-07 04:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/statements/import/index.md
> +The import statement may also be followed by a series of appendices after the `"module-name"`. They include:
_series of appendices_ is unclear to me.

2022-09-07 04:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/trailing_commas/index.md
> +Trailing commas are only allowed in [dynamic imports](/en-US/docs/Web/JavaScript/Reference/Operators/import) if the runtime also implements the second `options` parameter.
Again here, according to the bcd, all support `options`.

2022-09-07 04:56 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
Yes, this is for older versions, not engines that don't support them at all. It's still relatively new.

2022-09-07 05:00 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/index.md
> +The import statement may also be followed by a series of appendices after the `"module-name"`. They include:
There's also [a proposal for `with`](https://github.com/tc39/proposal-import-reflection). I'm trying to generalize, but I don't think there's a universal term, since none of these are in the main spec yet (and whatever we choose is likely to become mainstream discourse!). Maybe an "afterthought"?

2022-09-07 05:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/index.md
> +The import statement may also be followed by a series of appendices after the `"module-name"`. They include:
I changed it to "afterthought".

2022-09-07 06:37 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
Ha! I didn't check bcd PRs… 

I think that _trailing commas_ and `options` are two different (sub-) features. Even if it is likely, there is no guarantee that other engines will implement them simultaneously. (So I think we should update bcd too)

Also, there is no conceptual link between both features, so this would simplify the prose. We could have something as simple as:
```suggestion
As this syntax mimics function calls, [trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) {{experimental_inline}} are allowed.
```

(The badge will draw attention to the bcd table below and can be removed when the syntax won't be experimental anymore, that is implemented inside 2 engines at least)

2022-09-07 12:23 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
I don't really believe someone would only implement trailing commas without implementing `options`. The current grammar forbids trailing commas (see https://github.com/tc39/proposal-dynamic-import/issues/67), and it's only through adding a second parameter that makes trailing commas actually seem worth it. If you are an engine implementer and you are changing the parser anyway, why not do everything in one? (You can even make it only parsable but throws at runtime.) Otherwise you would end up with a parser that neither adheres to ES2022 nor the import-assertions proposal.

2022-09-07 12:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
Imagine we are in 5 years. How would know somebody looking at the bcd table know that support for the `options` also means support for trailing commas

Or how will you add the table on the trailing commas page to say when supports for trailing commas on `import` have been added?

2022-09-07 22:35 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
I just noticed there's a `javascript.grammar.trailing_commas` section in BCD. In this case I would add a BCD entry, yes. However, I think the content is good as-is—it reduces the cognitive overload of someone trying to understand when's okay to use trailing comma and when's not.

2022-10-12 15:47 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +export { exports } from "module-name" assert {};
```suggestion
import { exports } from "module-name" assert {};
```

2022-10-31 06:16 UTC, Josh-Cena commented
Let's still see if someone from Google (or from Mozilla!) can get to look at this.

2022-11-04 00:47 UTC, hamishwillee commented
@teoli2003 @wbamberg Can we get a review on this? 

If desired I can comment on whether it makes sense to me, but not on whether it is correct/complete.

2022-11-06 04:39 UTC, Josh-Cena commented
@hamishwillee I'd very appreciate it if you can comment on whether it makes sense, from the perspective of a reader 😄

2022-11-06 23:56 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +[Trailing commas](/en-US/docs/Web/JavaScript/Reference/Trailing_commas) are only allowed if the runtime also supports `options`. Check [browser compatibility](#browser_compatibility).
Remember you'll need this experimental inline if the feature is present in BCD.

Note I am also assuming this statement is correct as per the spec - which will need to say something like "trailing commas are only allowed if there is more than one option specified to the keyword."

2022-11-06 23:58 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
1. I don't know that an afterthought is. I went to the linked item and I am still no wiser. Needs to be clear somewhere.
2. Not sure what you can do about it, but I find it confusing that we have two things called `import`.

2022-11-07 00:02 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
Or to put it another way, if you remove the text ", which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement" it is easier to work out is going on.

2022-11-07 00:06 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
>  If your file is not run as a module (if it's referenced in an HTML file, the script tag must have `type="module"`), you will not be able to use static import declarations, but the asynchronous dynami
Would be good to chop this up while we're here.
```suggestion
If your file is not run as a module (if it's referenced in an HTML file, the script tag must have `type="module"`), you will not be able to use static import declarations.
The asynchronous dynamic import syntax will always be available, allowing you to import modules into non-module environments.
```

2022-11-07 00:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
I made this a bit more generic, because there are other proposals that add more stuff after the `import`—like [evaluator attributes](https://github.com/tc39/proposal-import-assertions#follow-up-proposal-evaluator-attributes):

```js
import foo from "mod" with { transformA: "value" };
```

I don't know what to call `assert` and `with` collectively. Afterthoughts? Attributes? Appendices?

2022-11-07 00:11 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
> 2\. I find it confusing that we have two things called `import`.

I wasn't happy with the dynamic import's title either (although I created that page). I will change it to `import()`.

2022-11-07 00:23 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +  - : An object containing import options, which correspond to the afterthoughts of the [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. The following key is recognized:
> I don't know what to call assert and with collectively. Afterthoughts? Attributes? Appendices?

Of those, attributes is best - but I still don't like it. I was thinking "options" or "additional options". If it works, "constraints", "modifiers", "additional specifiers". The problem with afterthoughts is that an afterthought is something almost incidental, and these are significant.

2022-11-07 00:25 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +The `options` parameter allows different kinds of import options. For example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
So here you've used "options" instead of afterthought right?

2022-11-07 00:27 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/export/index.md
> +`export from` supports all afterthoughts that `import` supports — for example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
Depends on what you end up deciding.

```suggestion
`export from` supports all the same options that `import()` supports — for example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
```

2022-11-07 00:27 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +The `options` parameter allows different kinds of import options. For example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
“Afterthoughts" is the syntax (`assert`, `with`, etc.); "options" is what they represent. Maybe that sounds a bit arbitrary?

2022-11-07 00:29 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** The grammar does not allow a line break between the `"module-name"` specifier and the `assert` keyword, to avoid syntactical ambiguity in the following valid code where `assert` is a vari
```suggestion
> **Note:** The grammar does not allow a line break between the `"module-name"` specifier and the `assert` keyword, in order to avoid syntactical ambiguity in the following valid code where `assert` is a variable name via [automatic semicolon insertion](/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion):
```

2022-11-07 00:30 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
Note, prefer not to use i.e. if possible. Note, don't merge this suggestion, just used for highlighting
```suggestion
On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (such as a browser or Xxxx). For example, the response may look like this:
```

2022-11-07 00:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
I used "i.e." here because we are talking about "on the web", so hosts must be browsers.

2022-11-07 00:36 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was JSON modules. Consider the following statement:
I would be explicit here about the problem "at very high level". The paragraph further down which explains the problem is not clear, but I think you mean:

```suggestion
Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that JSON modules are not parsed as code if served incorrectly.

Consider the following statement:
```

2022-11-07 00:38 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was JSON modules. Consider the following statement:
Sounds much better. Thanks!

2022-11-07 00:39 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +JSON modules are identified by the `application/json` [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). When the host sees this MIME type instead of `text/javascript` (for JavaScript sourc
This para is confusing - it takes a long time to get to "the mime type served might be wrong". Also type emaple.com.

2022-11-07 00:41 UTC, hamishwillee commented on files/en-us/web/javascript/reference/operators/import/index.md
> +The `options` parameter allows different kinds of import options. For example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
It does to me. If you go through and replace afterthoughts with _options_ or _import/export options_ does it read more naturally to you?

2022-11-07 00:42 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
Can't they be node scripts? The point about "i.e." is that screen readers don't handle the text well (I'm told).

2022-11-07 00:42 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +JSON modules are identified by the `application/json` [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). When the host sees this MIME type instead of `text/javascript` (for JavaScript sourc
A very important mission of this page is to explain why assertions can't change how a module is interpreted—on the web, interpretation is always done through MIME types. This has been a recurring confusion of the import-assertions proposal.

2022-11-07 00:50 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/import/index.md
> +The `options` parameter allows different kinds of import options. For example, [import assertions](/en-US/docs/Web/JavaScript/Reference/Statements/import/assert):
I ended up using "attributes" because "options" still sounds weird, given they are written as separate things.

2022-11-07 00:53 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
Here we are talking about MIME types, so no, not Node (Node uses file extensions, so this section is irrelevant in general). I wonder how screen readers pronounce it? I won't consider "ai ee the browser" an entirely bad pronunciation—I do that myself 😄

2022-11-07 00:55 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Instead, you must provide an assertion. To validate the module's type (via MIME type), you use the assertion key called `type`. To validate that the module is a JSON module, the value is `"json"`.
This is all a bit confusing to me - i.e. when it fails and why. What I think you're saying is that:
- Top example imports a json file with json mime type. This fails because even though it is correctly identified and parsed as JSON, the `import` makes the browser think it should be code.
- If this was served as code it would be imported as code, and that would be wrong too.
- So the solution is to use an assert to say that this file must be json and it is OK to import it. Now if the file is served as json everything will work because the browser knows that this is your intent. If it is served as code the import will fail because - which is safe.

Is that right?

2022-11-07 00:57 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
No idea. The problem came up as an accessibility issue in some reviews of my work. So I'm just sharing the load.

I think the word "host" might be the problem. I'm so used to seeing "user-agent" to mean browser.

2022-11-07 00:58 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +This likely does nothing unless your host reads that key. The assertion:
```suggestion
This likely does nothing unless your host understands that key. The assertion:
```

2022-11-07 00:58 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice twice, once with the assertion and once without, and neither import fails, then they would result
```suggestion
- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the exact same module without re-executing it.
```

2022-11-07 00:59 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Instead, you must provide an assertion. To validate the module's type (via MIME type), you use the assertion key called `type`. To validate that the module is a JSON module, the value is `"json"`.
On the web:

- The content type and the assertion must match, JavaScript-to-JavaScript, JSON-to-JSON.
- A mismatched assertion always fails.
- A missing assertion implicitly means `assert { type: "javascript" }`.

This means:

- Import without assertion cannot import anything other than JavaScript—JSON would fail as well.
- Import with `assert { type: "json" }` cannot import anything other than JSON.

> This fails because even though it is correctly identified and parsed as JSON, the `import` makes the browser think it should be code.

Yeah I think you get it. The `import` without assertions is always JavaScript (i.e. code).

> If this was served as code it would be imported as code, and that would be wrong too.

If it's served with `text/javascript` it would actually succeed, because it's undistinguishable from a normal JS module. This is why browsers don't allow you to omit the assertion when importing JSON—that basically prevents the entire security system from working.

2022-11-07 01:02 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +On the web, each import statement would result in a HTTP request. The response is then prepared into a JavaScript value and made available to the program by the host (i.e. the browser). For example,
"User-agent" is more about the user-facing aspect; "host" is more about the JS-facing aspect. A host for a JavaScript interpreter; a user agent for an end user.

2022-11-07 01:06 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the
The sentence still feels a little awkward. I think it is because I don't know what you mean by "without re-executing it." - or more precisely what importing the same module twice means - i.e. it could be that a browser will overwrite a previous import or something.

Are you saying that the browser will ignore the assertion for caching - i.e. it will be like it sees the same import statement twice, so it will ignore the second import?

2022-11-07 01:08 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** JSON modules only have one default export. You cannot do named imports from them (e.g. `import { name } from "data.json"`).
```suggestion
> **Note:** JSON modules only have one default export. You cannot do named imports from them (such as `import { name } from "data.json"`).
```

2022-11-07 01:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the
Yes. Importing the same module twice always results in the exact same object:

```js
import default1, { named as named1 } from "mod";
import default2, { named as named2 } from "mod";

console.assert(default1 === default2);
console.assert(named1 === named2);
```

The same happens if one of them has an assertion:

```js
import default1 from "mod" assert { type: "json" };
import default2 from "mod";

console.assert(default1 === default2);
```

I do notice that we lack some references about module semantics in general, but I have a lot to fix in the JS docs at the moment...

2022-11-07 01:09 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** JSON modules only have one default export. You cannot do named imports from them (e.g. `import { name } from "data.json"`).
```suggestion
> **Note:** JSON modules only have one default export. You cannot do named imports from them (like `import { name } from "data.json"`).
```

2022-11-07 01:23 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the
OK. Maybe:

```suggestion
- Is not used by the host to cache the module. (A host will only store only one copy of the module in the cache, whether or not the assert is specified).
```

2022-11-07 01:25 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the
Shall we keep both? The "import twice" part is IMO important for illustration.

```suggestion
- Is not used by the host to cache the module. A host will only store only one copy of the module in the cache, whether or not the assert is specified. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the exact same module without re-executing it.
```

2022-11-07 01:26 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Instead, you must provide an assertion. To validate the module's type (via MIME type), you use the assertion key called `type`. To validate that the module is a JSON module, the value is `"json"`.
Yes, I get it. I'm pretty sure your text all says this too. It just feels quite hard to read. I'll think about it a bit more.

2022-11-07 02:26 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +- Is not used by the host to cache the module. If a module with the same specifier is imported twice, once with the assertion and once without, and neither import fails, then they would result in the
Hmmm, better than without.

The problem is that I don't understand what the last "it" refers to in "then they would result in the exact same module without re-executing it".

2022-11-08 06:31 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that JSON modules are not parsed as code if served incorrectly.
@Josh-Cena  On re-reading, I am not sure that this line is correct. My thinking is that json being parsed as code is fine. What we don't want it something something pretending to be json to be parsed as code. Isn't that the security problem. Or are they both issues?

```suggestion
Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that code modules served incorrectly as JSON are not executed, as this is a security hole.
```

2022-11-08 06:40 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that JSON modules are not parsed as code if served incorrectly.
JSON being "executed as code" doesn't sound like a problem, barring if it makes sense (a piece of JSON text is not valid JS syntax, especially if it's enclosed in braces—that would be a block statement). I assume you mean "JSON being evaluated with the privilege of JS code"? This means if you have `assert { type: "javascript" }` (I don't think it exists), it's _probably_ fine if the module ended up being a JSON module. The problem is that, sans import assertions, all import statements implicitly have the privilege of JS code, including JSON modules that should probably have less privilege. The idea is to secure against this case:

- An endpoint serves a JSON module with `application/json`, and you import this.
- One day, the endpoint is compromised (or it was bogus in the first place), and it starts serving a different module which is JS with `text/javascript`, and you continue to import it.

You assumed the code is evaluated without any side-effects and provides you the data you need, while in fact you allowed arbitrary code to be executed. I agree the original wording is incorrect: it's not "JSON modules are parsed as code", it's "what you believe to be JSON modules actually ended up being parsed as code". What about:

```suggestion
Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that JSON modules are always being parsed as JSON, and are never executed with the privilege of JS code if the request target's response changes.
```

2022-11-08 06:42 UTC, Josh-Cena commented
This is hard to get right... I spent a few months wrapping my head around this feature until it clicked.

2022-11-08 06:46 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions fix this problem by allowing the author to explicitly specify how a module should be validated. For example, the import statement above would actually fail in a browser:
" — and the former is generally a safer thing to do" - I think you are saying "it is safter to parse anything as JSON than as code". Is that right?

Anyway, I think the structure is hard to read, so here is the first part of a suggestion to change it. The idea is to start as you have ...

```suggestion
Modules are identified and parsed only according to their served [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)  — the URL file extension cannot be used to identify a file's type. 

In this case the type is `application/json`, which tells the host browser that the file is JSON and must be parsed as JSON.
If MIME type in the server response was incorrectly set to `text/javascript` (for JavaScript source), the file would be executed as code.
If the "json" file actually contained malicious code, the fact that the `import` executes the file as code could pose a serious security threat.
 
Import assertions fix this problem by allowing the author to explicitly specify how a module should be validated. For example, here we add the assertion that tells the host that this file must contain json. If it doesn't we'll get the following error:
```

_You'd then replace the error below with the one for a mismatched json._ so it would go like this:

```js
import data from "https://example.com/data.json" assert { type: "json" };
```

This does NOT change how the module is interpreted. The host already knows to parse the module as JSON or code given the MIME type. It only uses the assertion to do _after-the-fact_ checking that the `data.json` module is, in fact, a JSON module. For example, if the response header changes to `Content-Type: text/javascript` instead, the program will fail:

...


Last of all you have a note about the default assertion being code - which is why having JSON without an assert fails.


What do you think?

2022-11-08 06:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions fix this problem by allowing the author to explicitly specify how a module should be validated. For example, the import statement above would actually fail in a browser:
This sounds much better! I have some minor changes to make so I'll not directly commit it, but I'll definitely go with your structure

2022-11-08 07:03 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that JSON modules are not parsed as code if served incorrectly.
Hmmm. Now I see why you were happy with the original text. I get it - I'm just wondering if the leap from "if the request target's response changes." to the concept that your response has been hijacked is too great. 

I like the nuance that it is host code setting the expectation of the file type. Something like:

```suggestion
Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that modules that are expected to be JSON are always parsed as JSON (in other words, to ensure that they are never executed with the privilege of JS code even if the server response changes to indicate that the file contains code).
```

2022-11-08 07:05 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions fix this problem by allowing the author to explicitly specify how a module should be validated. For example, the import statement above would actually fail in a browser:
Cool, I'll leave you with it. I'll be back Friday.

2022-11-08 07:06 UTC, hamishwillee commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions fix this problem by allowing the author to explicitly specify how a module should be validated. For example, the import statement above would actually fail in a browser:
PS and I can see some ways you might want to following your other comments - e.g.

> If the "json" file actually contained malicious code, the fact that the `import` executes the file as code could pose a serious security threat.

might be better as something that says. "If the server was hijacked to send the file with ..."

2023-01-02 17:00 UTC, Elchi3 requested changes
Thanks @Josh-Cena! Great work. Some suggestions.

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +tags:
This page needs a page type, I guess.

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +The **import assertion** feature tell the host to do after-the-fact checks about a module's metadata, making the host optionally throw if the assertion fails. It's supported in [`import`](/en-US/docs
```suggestion
The **import assertion** feature tells the host to do after-the-fact checks about a module's metadata, making the host optionally throw if the assertion fails. It's supported in [`import`](/en-US/docs/Web/JavaScript/Reference/Statements/import) declarations, [`export...from`](/en-US/docs/Web/JavaScript/Reference/Statements/export#re-exporting_aggregating) declarations, and dynamic [`import()`](/en-US/docs/Web/JavaScript/Reference/Operators/import).
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** Assertions can be attached to any kind of `import`/`export from` statement, including default import, namespace import, etc.
Is this note-worthy? Doesn't seem like a pitfall to watch out for or the like.

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +  - : One assertion key. Can be an identifier or a string literal — similar to what you can use in an [object literal](/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer), except for n
```suggestion
  - : An assertion key. Can be an identifier or a string literal — similar to what you can use in an [object literal](/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer), except for number literals and computed properties.
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +  - : One assertion value. Must be a string literal.
```suggestion
  - : An assertion value. Must be a string literal.
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary motivation was to ensure that modules that are expected to be JSON are always parsed as J
```suggestion
Import assertions allow hosts to do additional checks about the module that has just been loaded. The primary use case is to ensure that modules that are expected to be JSON are always parsed as JSON (in other words, to ensure that they are never executed with the privilege of JS code).
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** The actual assertion value does not correspond to the MIME type. It's separately specified by the WHATWG specification.
Link to the spec?

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +This does NOT change how the module is interpreted. The host already knows to parse the module as JSON given the MIME type. It only uses the assertion to do _after-the-fact_ checking that the `data.j
I think it is better to always use proper emphasis for accessibility/screen readers. 
```suggestion
This does **not** change how the module is interpreted. The host already knows to parse the module as JSON given the MIME type. It only uses the assertion to do _after-the-fact_ checking that the `data.json` module is, in fact, a JSON module. For example, if the response header changes to `Content-Type: text/javascript` instead, the program will fail:
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion bag.
bag? block?

```suggestion
The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion block.
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +import data from "https://example.com/module.js" assert { this: "looks good" };
I think "this" is always a bit weird as a key. It has special meaning in JS.

```suggestion
import data from "https://example.com/module.js" assert { version: "2.0.0" };
```

2023-01-02 17:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +This likely does nothing unless your host understands that key. The assertion:
```suggestion
This likely does nothing unless your host understands what do to with a `version` key. The assertion:
```

2023-01-02 17:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** Assertions can be attached to any kind of `import`/`export from` statement, including default import, namespace import, etc.
I added a note because the syntax box only shows one possibility but not the rest. This is more of a note of the syntax above.

2023-01-02 17:50 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** The actual assertion value does not correspond to the MIME type. It's separately specified by the WHATWG specification.
I would need someone who's familiar with HTML to point that out to me 😄 I did note that in https://github.com/mdn/content/pull/19588#issuecomment-1214986547

2023-01-02 19:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** The actual assertion value does not correspond to the MIME type. It's separately specified by the WHATWG specification.
I think it might be https://html.spec.whatwg.org/multipage/webappapis.html#module-type-allowed ?

2023-01-02 19:04 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +> **Note:** Assertions can be attached to any kind of `import`/`export from` statement, including default import, namespace import, etc.
I think it could be without the note box. I just always feel this tweet when there are too many note boxes.
https://twitter.com/ddbeck/status/1509925868021420042/photo/1 :)

2023-01-04 06:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion bag.
I think "bag" is better. It's used in the proposal text itself, and we commonly call options objects "bags", because they can contain arbitrary keys that implementations read while the language doesn't explicitly care about.

2023-01-04 09:30 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion bag.
I haven't heard "bag" before in this context. Maybe "object" is better? "bag" doesn't seem to be a regular technical term to me

2023-01-09 09:00 UTC, Elchi3 commented on files/en-us/web/javascript/reference/statements/import/assert/index.md
> +The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion bag.
```suggestion
The assertion syntax is designed to be extensible — although only `type` is known to be supported, you can put arbitrary keys in the assertion options object.
```

2023-02-04 18:14 UTC, Josh-Cena commented
Import assertions [got downgraded to stage 2](https://docs.google.com/presentation/d/1HbWhyo4tSnpv4vMZqCa2YQvi_mKdpDi4JWWBtSUQqQY/edit#slide=id.p) due to https://github.com/tc39/proposal-import-assertions/issues/125. I guess that gives us some more time before documentation because it won't be implemented by other engines anyway.

2023-02-05 22:44 UTC, hamishwillee commented
> Import assertions [got downgraded to stage 2](https://docs.google.com/presentation/d/1HbWhyo4tSnpv4vMZqCa2YQvi_mKdpDi4JWWBtSUQqQY/edit#slide=id.p) due to https://github.com/tc39/proposal-import-assertions/issues/125. I guess that gives us some more time before documentation because it won't be implemented by other engines anyway.

Do we need to do any intermediate "fix up"? My initial thinking was no, since the BCD says "non standard" so people should be using with care anyway. But on reflection, it is perhaps worth adding a note to chrome 91 BCD (i.e. to both the import assertion [lines shown here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility) to note that this was downgraded and likely to change.

Why? Because presumably at some point this will standardize, and that that point we'll need to do something to indicate that this older version is not the same version as the standard. Having a note now might help make this clear later.

Up to you.

2023-02-05 22:47 UTC, Josh-Cena commented
If it's shipped in one browser and noted as an experimental feature, I don't think we need any immediate fixup since things are expected to change anyway. It's lucky we don't have content yet. We can watch until a good alternative has been proposed.

2023-03-29 19:36 UTC, Josh-Cena commented
This feature is now called "import-attributes" and the assertion invariant has been removed. The new keyword is `with` instead of `assert`. This PR would be on hold until new implementations land.

2023-06-17 11:12 UTC, Josh-Cena commented
Instead of letting this PR sit around forever, I'm going to close this and open a new PR when the new syntax and semantics get shipped in browsers. There will be significant changes from the currently documented behavior.

2023-06-17 11:12 UTC, closed without merging