Optimize function type example
mdn/content pull request #19595
Opened 2022-08-15 15:36 UTC by tshemsedinov

#### Summary

- Removes some dead code or outdated code
- Optimize logical cases
- Optimize code style (e.g. early return, remove unused conditions)

#### Test cases

You can compare previous and new functions with following cases to see identical behaviour:

```js
class Person {}

const values = [
  5,
  5n,
  new Number(5),
  false,
  null,
  undefined,
  Symbol.iterator,
  {},
  [1, 2, 3],
  () => {},
  async () => {},
  new Date(),
  new Set(),
  new Map(),
  new WeakMap(),
  class {},
  Person,
  new Person(),
  ArrayBuffer,
  new ArrayBuffer(16),
  /abc/g,
];

console.log(values.map(type));
```

Both returns:

```js
[
  'number',        'bigint',
  'Number',        'boolean',
  'null',          'undefined',
  'symbol',        'Object',
  'Array',         'Function',
  'AsyncFunction', 'Date',
  'Set',           'Map',
  'WeakMap',       'class',
  'class',         'Person',
  'Function',      'ArrayBuffer',
  'RegExp'
]
```

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-15 15:40 UTC, Josh-Cena requested changes
`Symbol.toStringTag` is known to be more robust than `constructor.name`. For instance:

```js
[][Symbol.iterator]().constructor.name // "Object"
[][Symbol.iterator]()[Symbol.toStringTag] // "Array Iterator"
```

I agree with the other changes here—in particular using `includes()` and `startsWith()`. Could you add the comments, curly braces, and `Symbol.toStringTag` back?

2022-08-15 15:44 UTC, Josh-Cena commented
I wrote this function myself, and I quite pride myself in the code's quality. I'm curious where there's dead or redundant code.

2022-08-15 15:55 UTC, Josh-Cena requested changes
Writing secure and hard-to-spoof code is not easy, so here are some more tips.

2022-08-15 15:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  return value.constructor.name;
What if `value` is `{ constructor: { name: { something: "terrible" } } }`? Your code would not return a string in this case, and that's not nice. It also doesn't guard against the empty string case, which will happen for mixin classes `const withSomething = (cls) => class extends cls {...}`. In this case we'd rather return `"object"` than an empty string.

2022-08-15 15:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  if (value.toString().startsWith('class')) return 'class';
What if the object specifies `{ [Symbol.toPrimitive]() { return "good"; }, toString() { throw new Error("bad"); } }`? This would still work with literally all built-in operations, but would fail this case. We don't want that. This is why `String(value)` is better than `vale.toString()`. Also, here we need to use `typeof value === "function" && Function.prototype.toString.call(value)` to avoid all possibilities of stringification being overridden. I was wrong with my original `Object.getPrototypeOf(value) === Function.prototype` as well because I forgot about derived classes.

2022-08-15 15:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> -    typeof value[Symbol.toStringTag] === "string"
Just FYI, because we want to bring it back: the `in` test is important before actually accessing it. With proxies there's an observable difference: the proxy may unconditionally trap all property `get`, since most built-in operation would first query if the property actually exists. For example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with#using_with_with_a_proxy_to_create_a_dynamic_namespace So in this case, we also want to store it to a temp variable, to avoid firing two `get` requests. Ditto for the `value.constructor.name` below—that was my mistake of being too lazy..

2022-08-15 15:58 UTC, tshemsedinov commented
@Josh-Cena I thought of `toStringTag` as never being used, because my test cases gives the same result with it and without it, but I probably did not take into account all cases, I will expand the test to see more cases.

2022-08-15 16:00 UTC, Josh-Cena commented
`Symbol.toStringTag` was literally invented to give the type name of the object (used in `Object.prototype.toString`), which is why it's better in all cases.

2022-08-15 16:01 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  if (value.toString().startsWith('class')) return 'class';
Agree, it's a pity that we don’t have unittests for examples, it’s hard to refactor without it. Maybe we can prepare CI to extract cases and run tests and invent a way to describe test cases in article?

2022-08-15 19:14 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  if (value === null) return 'null';
```suggestion
  if (value === null) {
    return 'null';
  }
```

2022-08-15 19:14 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  if (!['object', 'function'].includes(type)) return type;
```suggestion
  // Primitive types
  const type = typeof value;
  if (!['object', 'function'].includes(type)) {
    return type;
  }
```

2022-08-15 19:14 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  if (value.toString().startsWith('class')) return 'class';
```suggestion
  // If litaral starts from class keyword
  if (String(value).startsWith('class')) {
    return 'class';
  }
```

2022-08-15 19:15 UTC, tshemsedinov commented on files/en-us/web/javascript/reference/operators/typeof/index.md
> +  return value.constructor.name;
```suggestion
  // Symbol.toStringTag often contains object's class name
  const tag = value[Symbol.toStringTag];
  if (typeof tag === 'string') {
    return tag;
  }
  // Constructor name, for example:
  // Array, GeneratorFunction, Number, DomainClass
  const { name } = value.constructor;
  return typeof name === 'string' ? name : type;
```

2022-08-15 19:16 UTC, tshemsedinov commented
See extended test cases above. And here is a table of both functions output:

| case                     | previous            | new                 |
| ---                      | ---                 | ---                 |
| `5                     ` | `number           ` | `number           ` |
| `5n                    ` | `bigint           ` | `bigint           ` |
| `new Number(5)         ` | `Number           ` | `Number           ` |
| `false                 ` | `boolean          ` | `boolean          ` |
| `null                  ` | `null             ` | `null             ` |
| `undefined             ` | `undefined        ` | `undefined        ` |
| `Symbol.iterator       ` | `symbol           ` | `symbol           ` |
| `{}                    ` | `Object           ` | `Object           ` |
| `[]                    ` | `Array            ` | `Array            ` |
| `() => {}              ` | `Function         ` | `Function         ` |
| `async () => {}        ` | `AsyncFunction    ` | `AsyncFunction    ` |
| `function* () {}       ` | `GeneratorFunction` | `GeneratorFunction` |
| `Promise.resolve()     ` | `Promise          ` | `Promise          ` |
| `new Date()            ` | `Date             ` | `Date             ` |
| `new Set()             ` | `Set              ` | `Set              ` |
| `new Map()             ` | `Map              ` | `Map              ` |
| `new WeakMap()         ` | `WeakMap          ` | `WeakMap          ` |
| `class {}              ` | `class            ` | `class            ` |
| `class Person {}       ` | `class            ` | `class            ` |
| `MixPerson             ` | `Function         ` | `class            ` |
| `new MixPerson()       ` | `Person           ` | `Person           ` |
| `ArrayBuffer           ` | `Function         ` | `Function         ` |
| `new ArrayBuffer(16)   ` | `ArrayBuffer      ` | `ArrayBuffer      ` |
| `/abc/g                ` | `RegExp           ` | `RegExp           ` |
| `[][Symbol.iterator]() ` | `Array Iterator   ` | `Array Iterator   ` |
| `something: 'terrible' ` | `object           ` | `object           ` |
| `throw new Error('bad')` | `Object           ` | `Object           ` |

2022-08-15 19:22 UTC, tshemsedinov commented
@Josh-Cena Now I see a single difference between implementations: following case
```
class Person {}
const mixinClass = (C) => class extends C {};
const MixPerson = mixinClass(Person);
```
previous implementation will classify `MixPerson` as `Function` while new implementation as `class`.

2022-08-16 02:14 UTC, Josh-Cena commented
Yep, that was a oversight of my old implementation. Thanks for catching that!

2022-08-16 10:39 UTC, tshemsedinov commented
@Josh-Cena Thank you too! There are no future implementations without previous ones. I'm a lecturer at three universities and going to send my students and everybody from my free video lectures here to help with MDN codebase improvements. If you have TODO lists please send a link, if not, perhaps your recommendations and directions will be helpful for them.

2022-08-16 11:08 UTC, Josh-Cena approved these changes
I made some refactors. I think this is good to go now. Thanks!

In the future, if you want to look to improve the code quality, I strongly suggest you look into our web API code examples. I'm actively maintaining the JS examples so it's less likely they are outdated. For one example—

2022-08-16 11:10 UTC, Josh-Cena commented
@teoli2003 is currently coordinating work on modernizing JS in web APIs. (Ref https://github.com/mdn/mdn-community/discussions/143) I'm sure he knows the problem space better than I do.

2022-08-16 11:12 UTC, merged

2022-08-16 11:27 UTC, tshemsedinov commented
@Josh-Cena do we have somewhere formal code style in eslint config format or at least as a document? There is an easy way to add eslint/prettier to check and even auto-fix js inside md files. It would be great to run it in Github actions.

2022-08-16 11:28 UTC, Josh-Cena commented
We don't have ESLint or Prettier for the time being. The best way is just to look around. It doesn't matter much—we'll review the code.