Prefer ternary or logical operator
mdn/content pull request #19675
Opened 2022-08-17 19:59 UTC by rubiesonthesky

#### Summary

Use ternary and nullish coalescing operator when it makes sense + some things left out from #19672

#### Motivation

Continues modernization efforts by @teoli2003  and @Josh-Cena 

#### Supporting details

#### Related issues

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-18 03:17 UTC, Josh-Cena requested changes

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +  this.color = collision ? "green" : "blue";
```suggestion
  const colliding = distance < circle1.radius + circle2.radius;
  this.color = colliding ? "green" : "blue";
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
> +  clearY = imgH > CanvasYSize ? imgH : CanvasYSize;
```suggestion
  clearX = Math.max(imgW, CanvasXSize);
  clearY = Math.max(imgH, CanvasYSize);
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
> +    if (x > (CanvasXSize)) {
```suggestion
    if (x > CanvasXSize) {
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
> +    if (x > (CanvasXSize-imgW)) {
```suggestion
    if (x > CanvasXSize - imgW) {
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/domtokenlist/toggle/index.md
> +  span.textContent = result ? `'c' added; classList is now "${classes}".` : `'c' removed; classList is now "${classes}".`;
```suggestion
  span.textContent = `'c' ${result ? "added" : "removed"}; classList is now "${classes}".`;
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/formdata/using_formdata_objects/index.md
> +  const oOutput = document.querySelector("div");
Could you try to do some more refactors here? e.g. get rid of the `o` prefix here, and move this line to outside the event listener. Also, using `querySelector("div")` looks like a refactor hazard—may want to change the example to an `<output>` instead.

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/namednodemap/getnameditem/index.md
> +pre.textContent = `The 'test' attribute contains ${attrMap.getNamedItem("test").value}\n${endString}`;
```suggestion
pre.textContent = `The 'test' attribute contains ${attrMap.getNamedItem("test").value}
And 'boum' has ${attrMap["boum"] ? "been" : "not been"} found.`;
```

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/paymentrequest/show/index.md
> +    await (allValid ? response.complete("success") : response.complete("fail"));
The original looks better to me... This is imperative code anyway.

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/webgl_api/by_example/detect_webgl/index.md
> +    paragraph.textContent = isSupported
If `gl` is falsy it won't be `instanceof` anything, so let's just use `gl instanceof WebGLRenderingContext` here

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
Unrelated but `xrReferenceSpace` seems unused...

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/css/filter-function/index.md
> +  const dataUnit = slider.getAttribute('data-unit');
This should just be called `unit`

2022-08-18 03:17 UTC, Josh-Cena commented on files/en-us/web/http/proxy_servers_and_tunneling/proxy_auto-configuration_pac_file/index.md
> +  return useDirect ? "DIRECT" : "PROXY w3proxy.mozilla.org:8080; DIRECT";
FWIW I like the original better. This file is all about conditional returns, and using ternaries means adding more branches is hard in the future

2022-08-18 05:15 UTC, teoli2003 requested changes

2022-08-18 05:15 UTC, teoli2003 commented on files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
>  const CanvasYSize = 200;
Can you remove the leading capital to these 2 variables? Thank you!

2022-08-18 05:15 UTC, teoli2003 commented on files/en-us/web/api/streams_api/using_readable_byte_streams/index.md
>    /* Return random number bytes in this call of socket */
While we are at it. Change from `/* … */` to `//`

2022-08-18 17:24 UTC, teoli2003 commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
@elchi3 will be able to tell us what's going with `xrReferenceSpace`.

2022-08-18 17:26 UTC, teoli2003 commented on files/en-us/web/api/streams_api/using_readable_byte_streams/index.md
>      return
nit
```suggestion
    return;
```

2022-08-18 17:26 UTC, teoli2003 commented on files/en-us/web/api/streams_api/using_readable_byte_streams/index.md
>      return
nit
```suggestion
    return;
```

2022-08-18 17:26 UTC, teoli2003 commented on files/en-us/web/api/streams_api/using_readable_byte_streams/index.md
>      return
```suggestion
    return;
```

2022-08-18 17:27 UTC, teoli2003 approved these changes
LGTM

2022-08-22 20:12 UTC, Josh-Cena commented on files/en-us/web/api/canvas_api/tutorial/basic_animations/index.md
> +The HTML includes the {{HTMLElement("canvas")}} in which the image is scrolled. Note that the width and height specified here must match the values of the `CanvasXZSize` and `canvasYSize` variables i
```suggestion
The HTML includes the {{HTMLElement("canvas")}} in which the image is scrolled. Note that the width and height specified here must match the values of the `canvasXSize` and `canvasYSize` variables in the JavaScript code.
```

2022-08-22 20:12 UTC, Josh-Cena commented on files/en-us/web/api/streams_api/using_readable_byte_streams/index.md
>      return
```suggestion
    return;
```

2022-08-22 20:13 UTC, Josh-Cena commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
Did we reach resolution on this?

2022-08-23 04:46 UTC, teoli2003 commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
Pinging @Elchi3

2022-08-23 07:22 UTC, Elchi3 commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
(I didn't write this section)

I think it is a code snipped taken from a larger example, so it is not complete in itself. (writing **short** example code for APIs that require setup / context creation [WebGL/WebXR/etc] isn't trivial).

So, I guess it is fine to leave `xrReferenceSpace` there unused as the reader should see this as piecemeal in context of more code. We could improve this but I guess that would be out of scope for this PR

2022-08-23 07:26 UTC, teoli2003 commented on files/en-us/web/api/xrrigidtransform/position/index.md
> +  xrReferenceSpace = immersiveSession
> I think it is a code snipped taken from a larger example, so it is not complete in itself. (writing **short** example code for APIs that require setup / context creation [WebGL/WebXR/etc] isn't trivial).

Yes, and this will be something we will have to solve to activate ESLint everywhere on MDN. But one step after the other!

Thank you!

2022-08-23 12:13 UTC, Josh-Cena approved these changes
LGTM

2022-08-23 12:21 UTC, merged