PREFIXING: remove vendor prefixes
mdn/content pull request #19673
Opened 2022-08-17 18:47 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-17 18:54 UTC, teoli2003 requested changes

2022-08-17 18:54 UTC, teoli2003 commented on files/en-us/glossary/vendor_prefix/index.md
> +Web developers included prefixed features on production Web sites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new feat
```suggestion
Web developers included prefixed features on production websites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new features. Including prefixed features also harmed smaller browsers who ended up having to add other browsers' prefixes to load popular websites.
```

2022-08-17 18:54 UTC, teoli2003 commented on files/en-us/glossary/vendor_prefix/index.md
> +window.requestAnimationFrame = window.requestAnimationFrame;
No need to declare it, not even a need to have `window.` in front of it.
```suggestion
requestAnimationFrame(callback);
```

2022-08-18 09:00 UTC, dipikabh requested changes
Thanks for updating this information, @estelle!

2022-08-18 09:00 UTC, dipikabh commented on files/en-us/glossary/vendor_prefix/index.md
> +Historically, vendors have also used prefixes for experimental APIs. If an entire interface was experimental, then the interface's name was prefixed (but not the properties or methods within). If an
```suggestion
Historically, browser vendors have also used prefixes for experimental APIs. If an entire interface was experimental, then the interface's name was prefixed (but not the properties or methods within). If an experimental property or method was added to a standardized interface, then the individual method or property was prefixed.
```

2022-08-18 09:28 UTC, teoli2003 commented on files/en-us/glossary/vendor_prefix/index.md
>  - [Vendor prefix](https://en.wikipedia.org/wiki/CSS_hack#Browser_prefixes) on Wikipedia
Should we rename this page?

2022-08-18 16:49 UTC, estelle commented on files/en-us/glossary/vendor_prefix/index.md
> +If you encounter the above code in a code base, you can safely remove all but the first line. All browsers support [`requestAnimationFrame`](/en-US/docs/Web/API/window/requestAnimationFrame#browser_c
```suggestion
If you encounter the above code in a code base, you can safely remove all but the first line. All browsers support [`requestAnimationFrame`](/en-US/docs/Web/API/window/requestAnimationFrame#browser_compatibility) without vendor prefixes, and without `window`:
```

2022-08-18 17:31 UTC, teoli2003 approved these changes
LGTM

2022-08-18 23:53 UTC, estelle commented on files/en-us/glossary/vendor_prefix/index.md
> +Web developers included prefixed features on production websites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new featu
```suggestion
Web developers included prefixed features on production websites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new features. Including prefixed features also harmed smaller browser vendors who ended up having to add other browsers' prefixes to load popular websites.
```

2022-08-18 23:54 UTC, estelle commented on files/en-us/glossary/vendor_prefix/index.md
> +Web developers included prefixed features on production websites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new featu
```suggestion
Web developers included prefixed features on production websites, despite their experimental nature. This made it more difficult for browser vendors to ensure compatibility while working on new features. Including prefixed features also harmed smaller browser vendors who ended up having to add other browsers' prefixes in order to render popular websites.
```

2022-08-19 08:54 UTC, dipikabh approved these changes
Looks good, thank you!

2022-08-19 08:54 UTC, merged