Remove CSS prefix
mdn/content pull request #19716
Opened 2022-08-19 00:25 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-19 00:58 UTC, wbamberg requested changes
Just a couple of typos.

2022-08-19 00:58 UTC, wbamberg commented on files/en-us/learn/css/howto/css_faq/index.md
> +The rules are more complicated when the selector has multiple parts. A more detailed explanation about how selector specificity is calculated can be found in the [CSS specifity documentation](/en-US/
```suggestion
The rules are more complicated when the selector has multiple parts. A more detailed explanation about how selector specificity is calculated can be found in the [CSS specificity documentation](/en-US/docs/Web/CSS/Specificity).
```

2022-08-19 00:58 UTC, wbamberg commented on files/en-us/learn/css/howto/css_faq/index.md
> +The use of such properties on production websites is not recommended — they have already created a huge web compatibility mess. For example, many developers only use the `-webkit-` prefixed version o
```suggestion
The use of such properties on production websites is not recommended — they have already created a huge web compatibility mess. For example, many developers only use the `-webkit-` prefixed version of a property when the non-prefixed version is fully supported across all browsers. This means a feature relying on that property not work in non-webkit-based browsers, when it could. This became a great enough problem that other browsers implement `-webkit-` prefixed aliases to improve web compatibility, as specified in the [Compatibility Living Standard](https://compat.spec.whatwg.org/).
```

2022-08-19 05:07 UTC, teoli2003 requested changes

2022-08-19 05:07 UTC, teoli2003 commented on files/en-us/web/api/css/supports/index.md
> +result = CSS.supports(`(transform-style: preserve) or (-moz-transform-style: preserve) or(-webkit-transform-style: preserve)`);
```suggestion
result = CSS.supports(`(transform-style: preserve) or (-moz-transform-style: preserve) or (-webkit-transform-style: preserve)`);
```

2022-08-19 05:07 UTC, teoli2003 commented on files/en-us/web/css/@supports/index.md
> +@supports (transform-style: preserve) or (-moz-transform-style: preserve) or(-webkit-transform-style: preserve) {}
```suggestion
@supports (transform-style: preserve) or (-moz-transform-style: preserve) or (-webkit-transform-style: preserve) {}
```

2022-08-19 05:07 UTC, teoli2003 commented on files/en-us/web/css/@supports/index.md
> +@supports (transform-style: preserve-3d) or ((-moz-transform-style: preserve-3d) or(-webkit-transform-style: preserve-3d))) {}
```suggestion
@supports (transform-style: preserve-3d) or ((-moz-transform-style: preserve-3d) or (-webkit-transform-style: preserve-3d))) {}
```

2022-08-22 21:31 UTC, Josh-Cena commented on files/en-us/learn/css/howto/css_faq/index.md
> +These properties, called _prefixed properties_, are extensions to the CSS standard. They were used to allow use of experimental and non-standard features in browsers without polluting the regular nam
```suggestion
These properties, called _prefixed properties_, are extensions to the CSS standard. They were once used to allow using experimental and non-standard features in browsers without polluting the regular namespace, preventing future incompatibilities to arise when the standard is extended.
```

2022-08-22 21:31 UTC, Josh-Cena commented on files/en-us/learn/css/howto/css_faq/index.md
> +The use of such properties on production websites is not recommended — they have already created a huge web compatibility mess. For example, many developers only use the `-webkit-` prefixed version o
```suggestion
The use of such properties on production websites is not recommended — they have already created a huge web compatibility mess. For example, many developers only use the `-webkit-` prefixed version of a property when the non-prefixed version is fully supported across all browsers. This means a design relying on that property would not work in non-webkit-based browsers, when it could. This became a problem great enough that other browsers were pushed to implement `-webkit-` prefixed aliases to improve web compatibility, as specified in the [Compatibility Living Standard](https://compat.spec.whatwg.org/).
```

2022-08-23 04:41 UTC, teoli2003 commented on files/en-us/web/api/css/supports/index.md
> +result = CSS.supports(`(transform-style: preserve) or (-moz-transform-style: preserve) or (-webkit-transform-style: preserve)`);
nit: literal string is no more needed as it is on one line now.
```suggestion
result = CSS.supports("(transform-style: preserve) or (-moz-transform-style: preserve) or (-webkit-transform-style: preserve)");
```

2022-08-23 04:41 UTC, teoli2003 approved these changes

2022-08-24 22:22 UTC, estelle commented
@wbamberg The typo fix was committed. Please re-review when you have a chance. thanks.

2022-08-25 00:04 UTC, wbamberg approved these changes
👍 thanks!

2022-08-25 00:04 UTC, merged