Remove CSS vendor prefixes
mdn/content pull request #19715
Opened 2022-08-19 00:10 UTC by estelle

I had some issues with github today, but this should be OK.

[Remove prefix: supported without prefix](https://github.com/mdn/content/commit/53fa629e3b73f87dd657d122587b4cc6354e4167)
[Remove prefix: prefix should NOT be in syntax box](https://github.com/mdn/content/commit/ce2764c3aeaf8b3c6d3647125a6517f91a7d70c8)
[Remove prefix: all browsers support none value for user select](https://github.com/mdn/content/commit/fd5870832795e9e3f8a3edf8596c8ab7b235d0c1)
[IE is -ms-](https://github.com/mdn/content/commit/5b4ac2db1c73ee5247531a3d10a825aea8b157eb)
#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-19 05:34 UTC, teoli2003 requested changes

2022-08-19 05:34 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
>  - Mozilla uses `-moz-`
```suggestion
- Firefox uses `-moz-`
```

2022-08-19 05:34 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
>  - Chrome/Opera/Safari use `-webkit-`
```suggestion
- Chrome/Edge/Opera/Safari use `-webkit-`
```

2022-08-19 05:34 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
> +- Internet Explorer uses `-ms-`
```suggestion

More prefixes were used in the past: Internet Explorer and early versions of Edge used `-ms-`, and old versions of Opera used `-o`.
```

2022-08-19 05:34 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
> +The second line has a `-moz-` prefix. Also no longer needed. The third one has no prefix. This third version shows the final version of the syntax supported in all evergreen browsers.
```suggestion
The second line has a `-moz-` prefix, which is also no longer needed. The third one has no prefix. This third version shows the final version of the syntax supported in all evergreen browsers.
```

2022-08-19 11:47 UTC, dipikabh requested changes
Some tiny improvement suggestions

2022-08-19 11:47 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
> +While the transform propert does not require a prefix, you may encounter this old CSS in a codebase. The first line shows a {{cssxref("transform")}} property with a `-webkit-` prefix — this was neede
```suggestion
While the `transform` property does not require a prefix, you may encounter this old CSS in a codebase. The first line shows the {{cssxref("transform")}} property with a `-webkit-` prefix — this was needed to make transforms work in older versions of Safari and Chrome until the prefix-free feature was supported.
```

2022-08-19 11:47 UTC, dipikabh commented on files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.md
>  Prefixed features were never supposed to be used in production websites — they are subject to change or removal without warning, and cause cross browser issues. This is particularly a problem when de
```suggestion
Prefixed features were never supposed to be used in production websites — they are subject to change or removal without warning and cause cross-browser issues. This is particularly a problem, for example, when developers decide to use only the `-webkit-` version of a property, which implied that the site won't work in other browsers. This actually happened so much that other browser vendors implemented `-webkit-` prefixed versions of several CSS properties. While browsers still support some prefixed property names, property values, and pseudo classes, now experimental features are put behind flags so that web developers can test them during development.
```

2022-08-19 11:47 UTC, dipikabh commented on files/en-us/web/css/user-select/index.md
>  > **Note:** `user-select` is not an inherited property, though the initial `auto` value makes it behave like it is inherited most of the time. WebKit/Chromium-based browsers _do_ implement the proper
Please check if the suggested change reflects what was originally intended

```suggestion
> **Note:** `user-select` is not an inherited property, though the initial `auto` value makes it behave like it is inherited most of the time. WebKit/Chromium-based browsers _do_ implement the property as inherited, which violates the behavior described in the spec, and this will bring some issues. Until now, Chromium has chosen to [fix the issues](https://chromium.googlesource.com/chromium/src/+/b01af0b296ecb855aac95c4ed335d188e6eac2de) to make the final behavior meet the specifications.
```

2022-08-19 11:47 UTC, dipikabh commented on files/en-us/web/css/user-select/index.md
> +> **Note:** `-webkit-user-select: all;` doesn't work in Safari; use only "none" or "text", or else it will allow typing in the `<html>` container. See the [browser compatability table](#browser-compa
```suggestion
> **Note:** `-webkit-user-select: all;` doesn't work in Safari; use only "none" or "text", or else it will allow typing in the `<html>` container. See the [browser compatability table](#browser-compatibility) for up-to-date information.
```

2022-08-19 19:13 UTC, teoli2003 approved these changes

2022-08-22 08:10 UTC, dipikabh approved these changes
Thank you!

2022-08-22 08:11 UTC, merged