[CSS] chore: GH issues 18758 contain property should mention 'inline-size'
mdn/content pull request #19736
Opened 2022-08-19 14:10 UTC by bsmth

This PR adds some details for `inline-size` value for the `contain` property.

__Notes:__
Opening as draft as I would like to clarify:
- [ ] equivalent to strict containment -> is this `size layout paint style` or `layout paint inline-size`

#### Related issues

- https://github.com/mdn/content/issues/18758

2022-08-20 00:57 UTC, sideshowbarker approved these changes
Looks great to me, with one suggestion

2022-08-20 04:34 UTC, teoli2003 commented on files/en-us/web/css/contain/index.md
> +  - : Indicates that the internal layout of the element is isolated from the rest of the page.
(Overall looks good). I'm not sure that _isolated_ is well-known. What about:
```suggestion
  - : Indicates that the internal layout of the element is isolated from the rest of the page, that is, nothing outside the element affects its internal layout, and vice versa.
```
That way the term _isolated_ is introduced to the reader, with a definition.

2022-08-21 14:39 UTC, dipikabh requested changes
Tiny nits

2022-08-21 14:39 UTC, dipikabh commented on files/en-us/web/css/contain/index.md
> +  - : Indicates that size containment is applied to the element. The size of the element can be computed in isolation, ignoring the child elements. Cannot be combined with `inline-size`.
```suggestion
  - : Indicates that size containment is applied to the element. The size of the element can be computed in isolation, ignoring the child elements. This value cannot be combined with `inline-size`.
```

2022-08-21 14:39 UTC, dipikabh commented on files/en-us/web/css/contain/index.md
> +  - : Indicates that inline size containment is applied to the element. The inline size of the element can be computed in isolation, ignoring the child elements. Cannot be combined with `size`.
```suggestion
  - : Indicates that inline size containment is applied to the element. The inline size of the element can be computed in isolation, ignoring the child elements. This value cannot be combined with `size`.
```

2022-08-22 07:20 UTC, bsmth commented on files/en-us/web/css/contain/index.md
> +  - : Indicates that the internal layout of the element is isolated from the rest of the page.
very good, thanks 👍🏻

2022-08-22 10:13 UTC, caugner reviewed
Looks like this PR has two unrelated changes:
1. Updating the `contain` page.
2. Adding `CSS Containment 3` to `SpecData.json`.

Is this intended?

2022-08-22 10:30 UTC, bsmth commented
Hi @caugner thanks for checking. 
>     1. Updating the `contain` page.
The clarifications on the opening paragraph help with overall context on the purpose of the contain property, in my opinion. Does this look okay to you?

>     2. Adding `CSS Containment 3` to `SpecData.json`.

I assumed this needed attention, but this is [no longer maintained](https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/howto/json_structured_data/index.md#specdata-specification-information). I have reverted in https://github.com/mdn/content/pull/19736/commits/7577e7140c0ae1d7e8e3c216f85cfa266eef4b1a

2022-08-22 11:10 UTC, caugner commented
> Does this look okay to you?

I was only looking at the PR, because changes to certain files (including SpecData.json) add `@mdn/core-dev` as a reviewer. I'll leave it to the others to review the content change. 🙂 

> I assumed this needed attention, but this is [no longer maintained](https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/howto/json_structured_data/index.md#specdata-specification-information). I have reverted in [7577e71](https://github.com/mdn/content/commit/7577e7140c0ae1d7e8e3c216f85cfa266eef4b1a)

TIL that SpecData.json is deprecated (I didn't know). 😄

2022-08-22 12:42 UTC, dipikabh approved these changes
LGTM! Thanks @bsmth  🎉

2022-08-22 12:42 UTC, merged

2022-08-22 13:00 UTC, bsmth commented
Thanks, all 🎉