Removed 5 from HTML
mdn/content pull request #19745
Opened 2022-08-19 19:25 UTC by estelle

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-19 19:32 UTC, teoli2003 requested changes
A few details, and this is good to be merged.

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +HTML provies the necessary components for rich, interactive game development. Technologies like `<canvas>`, WebGL, `<audio>`, and `<video>`, along with JavaScript implementations support tasks that p
```suggestion
HTML provides the necessary components for rich, interactive game development. Technologies like `<canvas>`, WebGL, `<audio>`, and `<video>`, along with JavaScript implementations, support tasks that provide similar, if not the same, features as native code. The Gamepad API allows developers and designers to access and use gamepads and other game controllers.
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/file_drag_and_drop/index.md
> +- [ HTML Living Standard: Drag and Drop](https://html.spec.whatwg.org/multipage/interaction.html#dnd)
```suggestion
- [HTML Living Standard: Drag and Drop](https://html.spec.whatwg.org/multipage/interaction.html#dnd)
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/index.md
> +- [ HTML Living Standard: Drag and Drop](https://html.spec.whatwg.org/multipage/interaction.html#dnd)
```suggestion
- [HTML Living Standard: Drag and Drop](https://html.spec.whatwg.org/multipage/interaction.html#dnd)
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/index.md
> +The `blur()` and `focus()` methods are inherited from {{domxref("HTMLElement")}}. They were originally defined on`HTMLAnchorElement` in DOM Level 2 HTML and earlier specifications.
I think we can get rid of this historical information…
```suggestion
The `blur()` and `focus()` methods are inherited from {{domxref("HTMLElement")}}.
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/input_event/index.md
> +For `<input>` elements with `type=checkbox` or `type=radio`, the `input` event should fire whenever a user toggles the control, per [the HTML Living Standard specification](https://html.spec.whatwg.o
```suggestion
For `<input>` elements with `type=checkbox` or `type=radio`, the `input` event should fire whenever a user toggles the control, per the [HTML Living Standard specification](https://html.spec.whatwg.org/multipage/input.html#the-input-element:event-input-2). However, historically this has not always been the case. Check compatibility, or use the {{domxref("HTMLElement/change_event", "change")}} event instead for elements of these types.
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/htmltextareaelement/index.md
> +The two properties `tabIndex` and `accessKey` are inherited from {{domxref("HTMLElement")}}. They were originally defined on `HTMLTextAreaElement` in DOM Level 2 HTML and earlier specifications.
```suggestion
The two properties `tabIndex` and `accessKey` are inherited from {{domxref("HTMLElement")}}.
```

2022-08-19 19:32 UTC, teoli2003 commented on files/en-us/web/api/htmltextareaelement/index.md
> +The two methods `blur()` and `focus()` are inherited from {{domxref("HTMLElement")}}. They were originally defined on `HTMLTextAreaElement` in DOM Level 2 HTML and earlier specifications.
```suggestion
The two methods `blur()` and `focus()` are inherited from {{domxref("HTMLElement")}}.
```

2022-08-19 20:28 UTC, estelle commented on files/en-us/web/api/htmlanchorelement/index.md
> +The `blur()` and `focus()` methods are inherited from {{domxref("HTMLElement")}}. They were originally defined on`HTMLAnchorElement` in DOM Level 2 HTML and earlier specifications.
It's on the HTMLAnchorElement page, so I left it.

2022-08-19 20:32 UTC, estelle commented
Thanks, @teoli2003. There were 3 suggestions that I didn't commit. I realize it's historical data, and generally no need to keep historical information, but did want to point out why I kept it, and leave it up to you if you still think it is not necessary. I am fine either way.

2022-08-20 06:04 UTC, teoli2003 approved these changes

2022-08-20 06:07 UTC, merged