CanvasRenderingContext2D - add missing properties
mdn/content pull request #19859
Opened 2022-08-23 02:28 UTC by hamishwillee

Missing from `CanvasRenderingContext2D` API docs
- [ ] `letterSpacing`
- [ ] `fontKerning`
- [ ] `fontStretch`
- [ ] `fontVariantCaps`
- [ ] `textRendering`
- [ ] `wordSpacing`

2022-08-23 04:03 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +---
Note sure this is implemented anywhere. Chrome seems to indicate it is in https://bugs.chromium.org/p/chromium/issues/detail?id=1144619&q=fontStretch&can=1 (v89) but it doesn't seem to render right. The system does seem to know what it is though - ie if you don't specify fontStretch it still returns "normal"

2022-08-26 08:30 UTC, Elchi3 requested changes
How great `roundRect` is!! 🤯 Finally!

Great content work here, love it! I had some minor things and one example that doesn't work for me.

Also, I looked up if this is everything new in Canvas 2D and it seems that there is also a new `reset()` method. Would be cool to document it as well. Doesn't need to be in this PR, though.

2022-08-26 08:30 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +The property to the [`font-stretch`](/en-US/docs/Web/CSS/font-stretch) CSS property when used with keywords (percentage values are not supported).
```suggestion
The property corresponds to the [`font-stretch`](/en-US/docs/Web/CSS/font-stretch) CSS property when used with keywords (percentage values are not supported).
```

2022-08-26 08:30 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
This example doesn't show different text renderings to me (in Chrome).

[Like in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#examples), should a new FontFace be added to the document first?

let ff = new FontFace('myfont', url);
f.stretch = "condensed";
document.fonts.add(f);

document.fonts.ready.then(() => {
    ctx.font = '25px myfont';
    ctx.fontStretch = "condensed";
}

2022-08-26 08:30 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/letterspacing/index.md
> +- {{domxref("CanvasRenderingContext2D.wordSpacing")}}
Also refer to https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing ?

2022-08-26 08:30 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/wordspacing/index.md
> +- {{domxref("CanvasRenderingContext2D.letterSpacing")}}
Refer to https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing as well?

2022-08-26 08:30 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/roundrect/index.md
> +The difference here is that the second is drawn with a negative width.
```suggestion
The difference here is that the second is drawn with a negative width.
```

2022-08-28 23:48 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/letterspacing/index.md
> +The **`CanvasRenderingContext2D.letterSpacing`** property of the [Canvas API](/en-US/docs/Web/API/Canvas_API) specifies the spacing between letters when drawing text.
```suggestion
The **`CanvasRenderingContext2D.letterSpacing`** property of the [Canvas API](/en-US/docs/Web/API/Canvas_API) specifies the spacing between letters when drawing text.

This corresponds to the CSS [`letter-spacing`](/en-US/docs/Web/CSS/letter-spacing) property.
```

2022-08-28 23:49 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/letterspacing/index.md
> +- {{domxref("CanvasRenderingContext2D.wordSpacing")}}
Good catch. I meant to have this up in the description rather than here though, so done in https://github.com/mdn/content/pull/19859/files#r956800504

2022-08-28 23:51 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/wordspacing/index.md
> +
```suggestion

This corresponds to the CSS [`word-spacing`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing) property.

```

2022-08-28 23:51 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/wordspacing/index.md
> +- {{domxref("CanvasRenderingContext2D.letterSpacing")}}
Good point. Again, decided have this up in the top description.

2022-08-29 02:33 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
Thanks @Elchi3 
Yes, clearly the default font is not a variable font, so this can't work. So yes we need to add a font. Unfortunately I am completely stumped as to how to do this in a **live example** (and I think it is worth doing in a live example). 

I tried having the font in the same folder as the docs but I get 404 errors (it isn't served). I tried using links from the interactive examples, but they fail with CORS errors.

The "best" way to do this would be to use a CDN served font with appropriate allow headers. I tried this with fonts.gstatic.com but I can't find a woff file that contains variable fonts. For example, this doesn't vary:
```
let font_file = new FontFace('LeagueMonoVariable', 'url(https://fonts.gstatic.com/s/leaguespartan/v6/kJEqBuEW6A0lliaV_m88ja5TwvZwLZk.woff2');
font_file.load().then( () => {

  document.fonts.add(font_file);
  // font loaded successfully!
  const ctx = canvas.getContext('2d');
  ctx.font = '36px "LeagueMonoVariable"'

// Default (normal)
ctx.fillText(`Hello world (default: ${ctx.fontStretch})`, 5, 20);
...
```

What I'd like to do, because I think it would be generally useful, is use the [google font API](https://developers.google.com/fonts/docs/getting_started) with the font loading API. However passing in the URLs suggested for CSS just gives you link parsing errors.

Any ideas?


PS Our [CSS Font loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) docs are "very thin". Not enough examples, and some may be incorrect - for example https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load looks to me to not be adding the font to the document, and I think that is a precondition.
In general it isn't clear what you need to do - I THINK you load() the font, wait for it to complete, then add it to the document and wait for it to be ready, but none of that is demonstrated.

2022-08-29 04:38 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/contextlost_event/index.md
> +The **`contextlost`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired (with the `cancelable` attribute initialized to `true`) if the user agent detects that the canvas backing stor
```suggestion
The **`contextlost`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired (with the `cancelable` attribute initialized to `true`) if the user agent detects that the backing storage associated with a [`CanvasRenderingContext2D`](/en-US/docs/Web/API/CanvasRenderingContext2D) or [`OffscreenCanvasRenderingContext2D`](/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D) context is lost.
```

2022-08-29 04:41 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/contextlost_event/index.md
> +The code fragment below detects the context lost event.
@Elchi3 When a context is lost this event gets fired, `CanvasRenderingContext2D.isContextLost()` will return true. The user agent attempts to reset the context and then if it succeeds it fires `contextrestored` event.

1. According to [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#context-lost-steps)
   > Let shouldRestore be the result of firing an event named contextlost at canvas, with the cancelable attribute initialized to true.
   > If shouldRestore is false, then abort these steps.

   Can you advise on how an event being fired might "result" in some evaluation for shouldRestore ?

2. I'm assuming this example might need to be updated if there is something handling code needs to do. Otherwise is there any point in having this section?

2022-08-29 04:51 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/reset/index.md
> +
@Elchi3 Note, no example. Seems pointless. Do you see value in perhaps the basic example here https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D#basic_example with a buttton to call reset?

2022-08-29 11:54 UTC, Elchi3 requested changes

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/htmlcanvaselement/contextlost_event/index.md
> +The **`contextlost`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired (with the `cancelable` attribute initialized to `true`) if the user agent detects that the backing storage ass
```suggestion
The **`contextlost`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired if the user agent detects that the backing storage associated with a [`CanvasRenderingContext2D`](/en-US/docs/Web/API/CanvasRenderingContext2D) or [`OffscreenCanvasRenderingContext2D`](/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D) context is lost.

Contexts can be lost for several reasons like driver crashes or the application runs out of memory, etc.

The `cancelable` attribute of this event is `true`. You can cancel this event in order to cancel the future restoration of the context.
```

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/htmlcanvaselement/contextrestored_event/index.md
> +The **`contextrestored`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired if the user agent restores the backing storage for a [`CanvasRenderingContext2D`](/en-US/docs/Web/API/Canv
I would give a hint here that you still need to redraw and reinitialize everything if you want to get to the point where the user was before the crash.

```suggestion
The **`contextrestored`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired if the user agent restores the backing storage for a [`CanvasRenderingContext2D`](/en-US/docs/Web/API/CanvasRenderingContext2D) or [`OffscreenCanvasRenderingContext2D`](/en-US/docs/Web/API/OffscreenCanvasRenderingContext2D).

You can redraw, re-retrieve resources, and reinitialize the state of your context once you received this event.
```

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/htmlcanvaselement/contextrestored_event/index.md
> +}, false);
Maybe add a comment to make clear what to typically do here.

```suggestion
canvas.addEventListener('contextrestored', (e) => {
  console.log(e);
  // call to redrawCanvas() or similar
}, false);
```

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/reset/index.md
> +
I don't think it would be pointless to have an example.
Note that `reset()` resets the drawing state which is really useful. See https://html.spec.whatwg.org/multipage/canvas.html#drawing-state

If you set up a canvas with a variety of properties like fillstyle, strokestyle, font, transformations, clipping area etc etc. and then you do `drawSomethingNice()`. Cool! But now when you want to draw something entirely different there, you need to remember to reset all properties like fillstyle, strokestyle and so on to not have any of the settings from `drawSomethingNice()` in `drawSomethingElse()`. 

With `reset`, you can basically do this:
```
drawSomethingNice()
reset()
drawSomethingElse()
```

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/reset/index.md
> +
We should probably have more text also about all the things that reset does.

2022-08-29 11:54 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/iscontextlost/index.md
> +
have a short copy-pastable code snippet here? (people always love to copy code -- even the shortest, that's why I try to have example code everywhere in reference pages)

```
if (isContextLost) {
  console.log("Context got lost")
}

2022-08-30 01:17 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/contextrestored_event/index.md
> +The **`contextrestored`** event of the [Canvas API](/en-US/docs/Web/API/Canvas_API) is fired if the user agent restores the backing storage for a [`CanvasRenderingContext2D`](/en-US/docs/Web/API/Canv
Yes. That makes sense.

2022-08-30 01:19 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/contextrestored_event/index.md
> +}, false);
Thanks.

2022-08-30 01:27 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/index.md
> +  - : Fired if the user agent successfully restores a `CanvasRenderingContext2D` or an `OffscreenCanvasRenderingContext2D` context.
Sounds very reasonable.

2022-08-30 03:00 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/reset/index.md
> +
Thanks. Updated with more words and a non-trivial example

2022-08-30 03:19 UTC, hamishwillee commented on files/en-us/web/api/htmlcanvaselement/contextlost_event/index.md
> +The code fragment below detects the context lost event.
Fixed!

I'll ping you if the BCD PR gives me problems

2022-08-30 03:19 UTC, hamishwillee commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
@Elchi3 So I think we're good except for fontstretch, on which I am stumped for the above reasons.

2022-08-30 09:00 UTC, Elchi3 reviewed
Fantastic work! Found two more nits but all reviewed and ready to go except `fontStretch`.

2022-09-01 12:13 UTC, bsmth commented
Thanks @hamishwillee and @Elchi3 , looks great! 🙌🏻 

Is there anything else outstanding on this one? It looks ready to merge from my side.

2022-09-01 14:20 UTC, Elchi3 commented
I think this is good. It's just that we need to work a bit on `fontStretch` as it only really works with variable fonts. I would be okay with putting that work to a separate PR, though.

2022-09-01 14:22 UTC, bsmth commented
> I would be okay with putting that work to a separate PR, though.

Great, Hamish probably has the context on it, but I'm happy to pick that up as a follow-up.

2022-09-01 14:22 UTC, bsmth approved these changes
Thank you! 👍🏻

2022-09-01 14:24 UTC, Elchi3 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
@bsmth See these messages above^

2022-09-01 14:41 UTC, bsmth commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
Thanks, tracking this improvement in #20208

2022-09-01 14:44 UTC, Elchi3 approved these changes

2022-09-01 14:44 UTC, merged

2022-09-01 14:48 UTC, teoli2003 commented
The functions `DrawRect()` and `DrawCircle`start with capital letters, there shouldn't. @bsmth, can you create a follow-up PR?

2022-09-01 14:58 UTC, bsmth commented
> The functions `DrawRect()` and `DrawCircle`start with capital letters, they shouldn't. @bsmth, can you create a follow-up PR?

Well spotted @teoli2003, I've added cleanup PR here: https://github.com/mdn/content/pull/20210

2022-09-01 16:17 UTC, wbamberg commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +In this example we display the text "Hello World" using each of the supported values of the `fontStretch` property.
Re: using fancy fonts in live samples, please see https://github.com/mdn/yari/issues/5727.

2022-09-01 23:24 UTC, hamishwillee commented
Thanks guys! Yes, I'm still trying to get the variable fonts thing working as a live example (yes, I could do it as an interactive one, but I prefer live). The easy fix would be https://github.com/mdn/yari/issues/5727 but I am also trying to get Google Fonts to work here.