Ff104 easing function
mdn/content pull request #19896
Opened 2022-08-23 21:49 UTC by dipikabh

#### Summary

- `linear()` function is supported in FF104 behind a preference: `layout.css.linear-easing-function.enabled`.
- This PR updates the [`<easing-function>`](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function) page to add the `linear()` function.
- In addition to adding the `linear()` function to 'Syntax' and 'Description' sections, this PR makes the following changes:
    - Moves the beginning prose to the section on 'Cubic Bézier functions' because the same information was being repeated in two places.
    - Creates an H3 'Values' section after 'Syntax' (to be consistent with the order and style in other CSS reference pages) and moves the value descriptions from the function sections to the 'Values' section. 
- There is scope for explaining the `linear()` syntax better (input and output values, percentages) and adding valid and invalid examples to 'Examples' section like the ones for cubic-bezier() and steps(). I'll tackle this in the next round.

#### Supporting details

Bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1764126
Spec: https://drafts.csswg.org/css-easing-2/#the-linear-easing-function

#### Related issues and PRs

Doc tracker: https://github.com/mdn/content/issues/19709
PR for BCD update: https://github.com/mdn/browser-compat-data/pull/17527
PR for experimental feature update: https://github.com/mdn/content/pull/19671

#### Metadata

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-30 13:56 UTC, Rumyra requested changes, later dismissed

2022-08-30 13:56 UTC, Rumyra commented on files/en-us/web/css/easing-function/index.md
> +The are three types of easing functions:
```suggestion
There are three types of easing functions:
```

2022-09-01 09:15 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. A curving line extends from the origin to the X 1 Y 1 position, quickly rising a
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio' with a curved line quickly rising from the origin to the X 1 Y 1 position.](cubic-bezier-ease.png)
```

2022-09-01 09:18 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. A slightly curving line extends from the origin to the X 1 Y 1 position, with mo
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio' shows a shallow curve from the origin that straightens out as it approaches X1 Y1.](cubic-bezier-ease-in.png)
```

2022-09-01 09:20 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. A slightly curving line extends from the origin to the X 1 Y 1 position. The cur
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio' shows a symmetrical, 'S'-shaped curving line from the origin to the X1 Y1 position.](cubic-bezier-ease-in-out.png)
```

2022-09-01 09:22 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. A slightly curving line extends from the origin to the X 1 Y 1 position, startin
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio' shows a straight diagonal line that lightly curves as it gets close to X1 Y1.](cubic-bezer-ease-out.png)
```

2022-09-01 09:27 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. Two dots are present, the first at the X 0 Y 0 position, and the second at the X
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio'. There is a point at X0 Y0 and another at X1 Y1 with a line extending towards the Y axis.](steps-1-start.png)
```

2022-09-01 09:28 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. Two dots are present, the first at the X 0 Y 0 position, and the second at the X
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio'. There is a point at X0 Y0 with a line extending away from the Y axis and a point at X1 Y1.](steps-1-end.png)
```

2022-09-01 10:23 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +  ![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. Three dots are present, the first at the X 0 Y 0 position, the second at the X
```suggestion
  ![A 2D graph of 'Time ratio' to 'Output ratio'. There are points at X0 Y0, X0.5 Y0.5, and X1 Y1. The second and third points have lines towards the Y axis.](steps-2-start.png)
```

2022-09-01 10:34 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +  ![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. Five dots are present, the first at the X 0 Y 0 position, the second at the X
```suggestion
  ![A 2D graph of 'Time ratio' to 'Output ratio'. There are points in 0.25 steps on both axes from X0 Y0 to X1 Y1. The second, third, and fourth points have lines extending 0.25 units away from the Y axis.](step3both.png)
```

2022-09-01 10:37 UTC, bsmth commented on files/en-us/web/css/easing-function/index.md
> +![A graph with X and Y ranges from 0 to 1, with the X axis labeled 'Time ratio' and the Y axis labeled 'Output ratio'. A straight diagonal line extends from the origin to the X 1 Y 1 position.](cubic
```suggestion
![A 2D graph of 'Time ratio' to 'Output ratio'. A straight diagonal line extends from the origin to the X1 Y1 position.](cubic-bezier-linear.png)
```

2022-09-01 10:45 UTC, bsmth commented
minor: the bezier gif doesn't seem to load on the preview, looks okay on prod though 🤔 :

* https://pr19896.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Bezier_curve/b%C3%A9zier_2_big.gif
* https://developer.mozilla.org/en-US/docs/Glossary/Bezier_curve/b%C3%A9zier_2_big.gif

2022-09-01 14:15 UTC, dipikabh commented
Thanks @bsmth for taking the time to review (and shorten) all the alt texts! Hopefully this covers all of them on this page.

I was wondering though if the single quotes as in 'Time ratio' are needed in an alt text.

To your comment:
> minor: the bezier gif doesn't seem to load on the preview, looks okay on prod though 🤔 :
> 
>     https://pr19896.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Bezier_curve/b%C3%A9zier_2_big.gif
>     https://developer.mozilla.org/en-US/docs/Glossary/Bezier_curve/b%C3%A9zier_2_big.gif

🤷‍♀️ maybe the local build does not support gifs?

2022-09-01 14:36 UTC, bsmth commented
> I was wondering though if the single quotes as in 'Time ratio' are needed in an alt text.

Feel free to remove / reword 👍🏻 

>maybe the local build does not support gifs?

Yeah it looks like this will work when deployed, the asset URL looks correct

2022-09-01 15:54 UTC, bsmth approved these changes
Looks good 👍🏻

2022-09-01 16:03 UTC, bsmth commented
Merging, thank you 🙌🏻

2022-09-01 16:03 UTC, merged