Update BCD info, part 39
mdn/content pull request #19911
Opened 2022-08-24 04:43 UTC by OnkarRuikar

Adding to #19185 

The PR updates BCD info in WebAPI docs.

Simple headers are done. Now files with inline badges left.

2022-08-24 16:46 UTC, jpmedley requested changes
Thank you for picking up some of our busy work. This looks pretty good, but I have one nit. We are gradually trying to remove the `{{SeeCompatTable}}` macros. 

FYI, our macro engine is case insensitive so there's no need to correct macro names.

2022-08-24 16:46 UTC, jpmedley commented on files/en-us/web/api/elementinternals/role/index.md
> +{{APIRef("DOM")}}{{SeeCompatTable}}
```suggestion
{{APIRef("DOM")}}
```

2022-08-24 16:46 UTC, jpmedley commented on files/en-us/web/api/elementinternals/role/index.md
> +{{APIRef("DOM")}}{{SeeCompatTable}}
We have been removing this macro for some time now. Please change this throughout.

2022-08-24 16:46 UTC, jpmedley commented on files/en-us/web/api/gamepadpose/index.md
> +{{SecureContext_Header}}{{APIRef("Gamepad API")}}{{SeeCompatTable}}
```suggestion
{{SecureContext_Header}}{{APIRef("Gamepad API")}}
```

2022-08-24 16:46 UTC, jpmedley commented on files/en-us/web/api/hid/index.md
> +{{SecureContext_Header}}{{APIRef("WebHID API")}}{{SeeCompatTable}}
```suggestion
{{SecureContext_Header}}{{APIRef("WebHID API")}}
```

2022-08-24 16:46 UTC, jpmedley commented on files/en-us/web/api/hid/index.md
> +{{SecureContext_Header}}{{APIRef("WebHID API")}}{{SeeCompatTable}}
Please remove any others that are in the docs you touched.

2022-08-24 16:50 UTC, teoli2003 commented on files/en-us/web/api/elementinternals/role/index.md
> +{{APIRef("DOM")}}{{SeeCompatTable}}
Why are we removing them? These are experimental features, isn't it?

I've not heard about this.

2022-08-24 17:55 UTC, jpmedley commented on files/en-us/web/api/elementinternals/role/index.md
> +{{APIRef("DOM")}}{{SeeCompatTable}}
Some experimental features are added to existing interfaces. This makes it hard to use in a consistently meaningful way. The inline macros you have been so kind as to add are better.

2022-08-25 06:23 UTC, OnkarRuikar commented
I've removed all the `{{SeeCompatTable}}` macros from this PR.

@jpmedley
> We are gradually trying to remove the `{{SeeCompatTable}}` macros.

1. Do we want to remove `{{Deprecated_Header}}` and `{{Non-standard_Header}}` macros as well?
2. Does this apply to the entire MDN Web Docs or just Web API pages? For example an experimental CSS page: https://developer.mozilla.org/en-US/docs/Web/CSS/masonry-auto-flow
3. Why gradually? Are we following any criteria/procedure to remove the `{{SeeCompatTable}}` macro? I mean we can simply remove them.

> Please remove any others that are in the docs you touched.

May I remove not just mine but all the `{{SeeCompatTable}}` macros. It will be easier that way and can be done with less effort as the script is ready.

2022-08-26 05:01 UTC, teoli2003 commented
We are not removing the `{{SeeCompatMacro}}`.

We are synchronizing info in BCD and MDN.

2022-08-26 05:28 UTC, OnkarRuikar commented
I am confused now. 😵‍💫

What I gathered from Joe's comments is that we are not adding new `{{SeeCompatTable}}` macro calls anymore and removing them when a feature is no longer experimental. Thus one day there will be no `SeeCompatTable` calls in the entire repo. Correct me.

To avoid confusions do we want to rename it to: `{{Experimental_Header}}`?

Let me know I what changes are required from me to land this PR.

2022-08-26 05:29 UTC, teoli2003 commented
> I am confused now. 😵‍💫
> 
> What I gathered from Joe's comments is that we are not adding new `{{SeeCompatTable}}` macro calls anymore and removing them when a feature is no longer experimental. Thus one day there will be no `SeeCompatTable` calls in the entire repo. Correct me.
> 
> To avoid confusions do we want to rename it to: `{{Experimental_Header}}`?
> 
> Let me know I what changes are required from me to land this PR.

We are adding `{{SeeCompatData}}` to every experimental feature. As far as I know, there has been no discussion about removing the macro. (I've edited the previous post to be more explicit)

2022-08-26 05:37 UTC, teoli2003 requested changes
Here is what is needed to have this PR synchronized with BCD data.

2022-08-26 05:37 UTC, teoli2003 commented on files/en-us/web/api/featurepolicy/index.md
>  {{APIRef("Feature Policy")}}
```suggestion
{{APIRef("Feature Policy")}}{{SeeCompatMacro}}
```

2022-08-26 05:37 UTC, teoli2003 commented on files/en-us/web/api/filesystemwritablefilestream/index.md
> +{{SecureContext_Header}}{{APIRef("File System Access API")}}
```suggestion
{{SecureContext_Header}}{{APIRef("File System Access API")}}{{SeeCompatData}}
```

2022-08-26 05:37 UTC, teoli2003 commented on files/en-us/web/api/encodedvideochunk/index.md
> +{{APIRef("WebCodecs API")}}
```suggestion
{{APIRef("WebCodecs API")}}{{SeeCompatData}}
```

2022-08-30 07:09 UTC, teoli2003 commented
We are waiting for an answer from @jpmedley here.

We are only mirroring the flags that are on mdn/browser-compat-data, so that they are the same and we can, in the future maintain their synchronization.

2022-08-31 05:39 UTC, teoli2003 commented
So this is the last PR so that mdn/browser-compat-data and mdn/content are synchronized (wrt to these badges/banners). 

Now you only need to run your sync script once a week, usually on Wednesdays?

Am I right, @OnkarRuikar

2022-08-31 06:13 UTC, OnkarRuikar commented
> Now you only need to run your sync script once a week, usually on Wednesdays?

How frequently we want this to run?

Currently I've set it up to run within 24 hrs of a new BCD release. On every boot my machine looks for new version:
```
> curl https://raw.githubusercontent.com/mdn/browser-compat-data/main/package.json 2>&1 | grep -Po '(?<=version....)[\d\.]+'
5.2.0
```

With this our content will be more up-to-date than other dedicated browser compatibility websites(e.g. can i use).
We can also run it daily, without waiting for a release, like the markdownlint cron job, to be the most up-to-date...

2022-08-31 06:33 UTC, teoli2003 commented
Once a week, on Wednesdays: usually, the bcd package is produced on Tuesday and used by Yari on Wednesday afternoon. So if we update mdn/content in between, there are 0 discrepancies.

2022-09-02 05:35 UTC, teoli2003 approved these changes
👍

2022-09-05 05:09 UTC, teoli2003 commented
ping @jpmedley

2022-09-13 15:44 UTC, closed without merging