Update JS writing guidelines
mdn/content pull request #19929
Opened 2022-08-24 13:52 UTC by teoli2003

After a fruitful discussion at https://github.com/mdn/mdn-community/discussions/143,  we used the outcome to significantly update our code example at mdn/content.

We learned a lot from it.

To maintain MDN in this good state, we plan to extend automation (Prettier and ESLint), but we also need to write clearly the rules we are using.

This PR is (almost) a complete rewrite and reorganization of the JS writing guideline.

cc/ @Rumyra @dipikabh @wbamberg @elchi3 @Josh-Cena (and anybody else).

2022-08-24 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    if (actionList.length === 0) return 0;
This immediately stands out. It's opposite from what I (and I supposed we) had been trying to enforce in the past few months.

2022-08-24 14:10 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    if (actionList.length === 0) return 0;
The lack of braces or the hint to return early? (I have no strong feeling here)

2022-08-24 14:16 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    if (actionList.length === 0) return 0;
The lack of braces, yeah. My personal codings style doesn't add the braces, but I've found the vast majority thinking it's worth it, and I think we've added curlies in quite a few places.

2022-08-24 14:18 UTC, teoli2003 commented
> I won't be able to thoroughly review this till tonight, but reading the page preview, there are already a few points I'm passionate to bikeshed about 😄

This will be the ultimate bikeshedding PR. 🤣 No hurry. I want to leave enough opportunity for everybody to bikeshed.

2022-08-24 15:17 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On the other side, using a single convention is helpful: very quickly, readers get used to it and become able to parse the code quicker and better.
```suggestion
A single writing convention is helpful for consistency, and consistent code examples are easier to read and understand.
```

2022-08-24 15:20 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +How to align and indent JavaScript, where to add spaces, or where to split lines have always been controversial. We believe that these discussions are mostly pointless and very time-consuming.
```suggestion
Opinions on correct indentation, whitespace, or splitting long lines have always been controversial. Discussions on these topics are a distraction from creating and maintaining content.
```

2022-08-24 15:20 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +How to align and indent JavaScript, where to add spaces, or where to split lines have always been controversial. We believe that these discussions are mostly pointless and very time-consuming.
I would rephrase to mention that they're distracting rather than pointless :)

2022-08-24 15:38 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Prettier deals with formatting, but not with what is the best JavaScript feature to use or doesn't judge if a comment is helpful or not. That's why we have additional conventions.
Minor reword
```suggestion
Prettier is effective for code formatting but can't judge if a comment is helpful, for example, or recommend the best JavaScript feature for a specific task. This document describes other conventions that we follow for such cases beyond formatting. 
```

2022-08-24 15:40 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use the modern and well-supported JavaScript features in MDN Web Docs code examples.
I wonder if this section could be a list of __do__ and __don't__ ?

```md
__Do:__
* Use modern and well-supported
* Use new methods
...

__Don't:__
* Use experimental...
```

2022-08-24 15:44 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Both spacing and indentation are [enforced by Prettier](https://prettier.io/docs/en/index.html). In particular, follow the following rules:
Minor:

```suggestion
Both spacing and indentation are [enforced by Prettier](https://prettier.io/docs/en/index.html). The following rules are notable:
```

2022-08-24 15:55 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Add a comment if the code isn't obvious or self-documenting. A code is self-documenting, for example, when calling a function with an explicit name: `closeConnection();` doesn't need a comment `// Cl
There's probably some debate whether any code is self-documenting :)

````suggestion
Add a comment if the purpose or logic of the code isn't obvious. Comments are not necessary, for example, when functions have explicit names that describe what they're doing. This comment doesn't add much value for the reader and can be left out:

```js
closeConnection(); // Closing the connection
```

````

2022-08-24 15:57 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +JS-style comments are marked with `//`, in opposition to C-style comments enclosed between `/* … */`.
```suggestion
JS-style comments are marked with `//`, as opposed to C-style comments enclosed between `/* … */`.
```

2022-08-24 16:00 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +In general, use JS-style comments to comment code. There is a mark on each line, so it is easier to notice a commented-out line. In addition, this convention allows using `/* …*/` to comment out a se
```suggestion
In general, use JS-style comments to comment code. Writers must mark each line with `//`, so it's easier to notice commented-out code visually. In addition, this convention allows to comment out sections of code using `/* …*/` while debugging.
```

2022-08-24 16:10 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Skipping code is necessary to keep examples short. We should do it carefully, as developers want to copy & paste our example inside their code base. We should try to have our code samples be valid Ja
```suggestion
Skipping redundant code is necessary to keep examples short. Still, writers should do it thoughtfully as developers frequently copy & paste examples into their code, and all of our code samples should be valid JavaScript.
```

2022-08-24 16:12 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +In JavaScript, you should put the ellipses (`…`) in a comment. When possible, indicate what action somebody reusing this snippet is expected to add. Don't write:
```suggestion
In JavaScript, you should put the ellipses (`…`) in a comment. When possible, indicate what action somebody reusing this snippet is expected to see. Don't write:
```

2022-08-24 16:12 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Using a comment will be more explicit, preventing errors when a developer copies & pasties the example:
yum, pasties 🥐 

```suggestion
Using a comment will be more explicit, preventing errors when a developer copies & pastes the example:
```

2022-08-24 16:13 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +To do so, you use `/* … */` in the parameter list. It is an exception to the rule only to use JS-style comments (`//`).
sounds good, an example would be great here 👍🏻

2022-08-24 16:20 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Having good variable names is essential to understanding code. Use short identifiers, and avoid non-common abbreviations. Ideally, a variable name should be between 3 to 10-character long. (This is a
```suggestion
Having good variable names is essential to understanding code. We advise using short identifiers and avoiding uncommon abbreviations. Good variable names are usually between 3 to 10-character long, but as a hint only. For example, `accelerometer` is more descriptive than abbreviating to `acclmtr` for the sake of character length.
```

2022-08-24 16:24 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The example below uses `let` where it should prefer `const`. The code will work, but we want to avoid this usage in MDN Web Docs code examples.
```suggestion
- The example below uses `let` where it should be `const`. The code will work, but we want to avoid this usage in MDN Web Docs code examples.
```

2022-08-24 16:27 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If needed (if the line is too long), Prettier will nest the conditional operators:
```suggestion
If needed (if the line is too long), Prettier will add line breaks with indentation to conditional operators:
```

2022-08-24 16:29 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- There is _a space_ between a control statement keyword (`if` or `ekse`) and its opening parenthesis.
```suggestion
- There is _a space_ between a control statement keyword (`if` or `else`) and its opening parenthesis.
```

2022-08-24 16:31 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Pay attention! When you declare a local variable for a case, you need to use braces to define a scope:
```suggestion
- __When you declare a local variable__ for a case, you need to use braces to define a scope:
```

2022-08-24 16:32 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +[Prettier](https://prettier.io/docs/en/index.html) enforces this format.
```suggestion
[Prettier](https://prettier.io/docs/en/index.html) enforces the following conventions.
```

2022-08-24 16:34 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +String literals can be enclosed with single quotes, like "A string", with double quotes, like `"A string"`. Which type of literal to use is the subject of never-ending discussions.
```suggestion
String literals can be enclosed with single quotes, like `'A string'`, or with double quotes, like `"A string"`.
```

2022-08-24 16:37 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +The `Object.hasOwnProperties()` is problematic and has been deprecated in favor of `Object.hasOwn()`. Use the latter.
```suggestion
The `Object.hasOwnProperties()` method has been deprecated in favor of `Object.hasOwn()`.
```

2022-08-24 16:42 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. More, it is modal to the whole window, which is annoying. Do not use it. U
```suggestion
- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is a modal to the whole window, which is annoying. Instead, use `console.log()` or `console.error()`, the {{HTMLElement("dialog")}} element, or a dedicated UI element in your example.
```

2022-08-24 16:47 UTC, bsmth commented
Thanks a lot @teoli2003, nicely done 🙌🏻  I've left quite a few comments there for clarity only. No bikeshedding comments from me on JS conventions / style that Prettier doesn't pick up, looks good to me. 

Q: Some of the line lengths for the `.md` file itself gets quite long and has multiple sentences. Are we going to be running prettier on the md docs, too?

2022-08-24 16:59 UTC, wbamberg commented
I don't think we should describe anything that is handled by Prettier. We should just say "we use Prettier to format code samples" and describe any extra config, if there is any. Re-describing Prettier features is extra work for us to write and maintain and extra work for readers to understand. I think in general the ethos of Prettier is not "here are rules you have to adhere to" but "type it any way you want and we will fix it up for you".

Relatedly, very long guidance pages on MDN are a problem, so we should aim to keep them concise. For example, this:

> Opinions on correct indentation, whitespace, or splitting long lines have always been controversial. Discussions on these topics are a distraction from creating and maintaining content.
>
> A single writing convention is helpful for consistency, and consistent code examples are easier to read and understand.
>
> We have decided to use [Prettier](https://prettier.io/) as a code formatter to avoid off-topic discussions and keep code style consistent. We plan to run Prettier automatically on our code snippets and enforce consistency throughout MDN. Reviewers may ask you to follow Prettier conventions, but we plan for CI to format your code example through automated Prettier runs regardless.
>
> Prettier is effective for code formatting but can't judge if a comment is helpful, for example, or recommend the best JavaScript feature for a specific task. This document describes other conventions that we follow for such cases beyond formatting.
>
> To learn more about the formatting conventions that are applied, read the [Prettier documentation](https://prettier.io/docs/en/index.html).

...we could just say "We use [Prettier](https://prettier.io/) to automatically format JavaScript code samples". We could optionally give a bit of guidance about how people can run Prettier locally (i.e. editor extensions).

In particular I'm not sure about:

> Reviewers may ask you to follow Prettier conventions

As a reviewer I don't want to memorise Prettier rules and ask people to update their PRs to follow them. I think this really goes against the idea of Prettier.

2022-08-24 17:14 UTC, Josh-Cena commented
That's also what I'm gonna say a few hours later. About the "maintainer ask you to format" though, I might end up pushing to the branch myself, but before we have it automated I definitely want to gate the incoming code's quality.

2022-08-24 17:25 UTC, teoli2003 commented
I will remove the rules enforced by Prettier tomorrow.

2022-08-25 05:27 UTC, teoli2003 commented
I removed all the rules enforced by Prettier, and shortened the intro about it.

2022-08-25 05:28 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    if (actionList.length === 0) return 0;
I removed this exception. The only exception is for statements like `break`, `continue`, and `return`.

2022-08-25 07:19 UTC, bsmth approved these changes
Thanks, I'm going to approve this one, but I presume it shouldn't be merged until Prettier formatting is at least a working manual process across all files in the repo. 👍🏻

2022-08-25 08:37 UTC, teoli2003 commented
Yes, I want to check if there is a consensus before merging this. Let's leave enough time for people to review (and bikeshed).

(I don't think we should gate on Prettier being automated, the automation will clean what goes through meanwhile)

2022-08-26 08:45 UTC, dipikabh requested changes
Starting to look at this now. I'll resume later in the day.

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +## Principles
```suggestion
## General guidelines for JavaScript code examples

This section explains the general guidelines to keep in mind while writing JavaScript code examples. The later sections will cover more specific details
```
- I would not change this heading. Firstly, 'Principles' is not descriptive and does not give any idea about what will be covered. Secondly, there are similar 'General guidelines...' sections in [HTML](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML), [CSS](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/CSS), and [Shell](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/Shell) pages.
- Taking this opportunity to add some text between the ## and ### headings. 🙂

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Opinions on correct indentation, whitespace, or splitting long lines have always been controversial. Discussions on these topics are a distraction from creating and maintaining content.
```suggestion
Opinions on correct indentation, whitespace, and line lengths have always been controversial. Discussions on these topics are a distraction from creating and maintaining content.
```

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +We have decided to use [Prettier](https://prettier.io/) as a code formatter to avoid off-topic discussions and keep code style consistent.
```suggestion
On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
```

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +To learn more about the formatting conventions that are applied, read the [Prettier documentation](https://prettier.io/docs/en/index.html).
```suggestion
To learn more about the formatting conventions used on MDN Web Docs, read the [Prettier documentation](https://prettier.io/docs/en/index.html).
```

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Modern JavaScript features
```suggestion
### Using modern JavaScript features
```
- to make it similar to the previous "## Choosing a format"

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use new methods once every major browser supports them. You can use new syntax once every major browser supports them and two years have elapsed.
```suggestion
Use new methods only after every major browser supports them and new syntax after every major browser supports it and two years have elapsed.
```
- Rephrasing to skip the repetition of "You can" from the previous sentence

2022-08-26 08:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't use experimental features. In all cases, readability is more important than shaving a few characters.
```suggestion
Don't use experimental features. In all cases, readability is more important than shaving off a few characters.
```

2022-08-26 15:16 UTC, dipikabh requested changes
@teoli2003 Thank you for work in revamping this!! 🙌

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- [`async`](/en-US/docs/Web/JavaScript/Reference/Statements/async_function)/[`await`](/en-US/docs/Web/JavaScript/Reference/Operators/await).
```suggestion
- [Promises](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), including the `finally()` method
- [`async`](/en-US/docs/Web/JavaScript/Reference/Statements/async_function)/[`await`](/en-US/docs/Web/JavaScript/Reference/Operators/await)
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +In addition to these JS language features, there are few guidelines related to Web APIs.
```suggestion
In addition to these JavaScript language features, we reccomend a few guidelines related to Web APIs to keep in mind.
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If all browser supports a feature, don't prefix it.
```suggestion
If all browsers support a feature, don't prefix it.
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +should be
```suggestion
The above snippet should be:
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Do not use {{DOMxRef("Element.innerHTML")}} to insert purely textual content into an element, use {{DOMxRef("Node.textContent")}} instead. The property `innerHTML` leads to security problems if the
```suggestion
- Do not use {{DOMxRef("Element.innerHTML")}} to insert purely textual content into an element; use {{DOMxRef("Node.textContent")}} instead. The property `innerHTML` leads to security problems if a developer doesn't control the parameter. The more we as writers avoid using it, the fewer security flaws are created when a developer copies and pastes our code.
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is a modal to the whole window, which is annoying. Instead, u
```suggestion
- The `alert()` function is unreliable. It doesn't work in live examples on MDN Web Docs that are inside an {{HTMLElement("iframe")}}. Moreover, it is a modal to the whole window, which is annoying. Instead, use `console.log()` or `console.error()`, the {{HTMLElement("dialog")}} element, or a dedicated UI element in your example code.
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- When logging a message, use `console.log()`. When logging an error, use `console.error()`.
```suggestion
- When logging a message, use `console.log()`.
- When logging an error, use `console.error()`.
```

2022-08-26 15:16 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- [JavaScript language reference](/en-US/docs/Web/JavaScript/Reference) - browse through our JavaScript reference pages to check out some good, concise, meaningful CSS snippets.
```suggestion
[JavaScript language reference](/en-US/docs/Web/JavaScript/Reference) - browse through our JavaScript reference pages to check out some good, concise, meaningful CSS snippets.
```

2022-08-26 18:54 UTC, wbamberg reviewed
Here's a pile more comments for you @teoli2003 ! I don't have many complaints with the substance of these though :).

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use the modern and well-supported JavaScript features in MDN Web Docs code examples.
This sentence doesn't seem to add anything, given the sentences that follow it.

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't use experimental features. In all cases, readability is more important than shaving a few characters.
Again I think we need to explain what "experimental" means here.

And this:

> In all cases, readability is more important than shaving a few characters.

...seems quite out of place wrt "modern features", it's surely just generic good style, and covered later on?

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use new methods once every major browser supports them. You can use new syntax once every major browser supports them and two years have elapsed.
What is the difference between "methods" and "syntax"? And why is there a difference here? And what is the set of modern browsers?

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't put everything on one line:
Prettier will take care of this, right?

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgJ4BimYAFAJT7D6RQDOEANnAHSsQDmlAOiAAScVtwCEg6gG58AX2kgANCAgAHXNCbJQAQwBO+iAHcACgYTaUu1sd3FtKgEb7dYANZwYAZV2E4ADI4UHDIqDZMcM6uHl7eam7BPMgw+uhRIHCETnAAJrl5AbpQPOi6PHCkEPqEujC4JcgguugwEMogABYwhKwA6p048EwJYHDelkM4AG5DxE1gTI4gwZH6MKauPLVhERkAVkwAHt5J7ACK6BDwu6yRKgn6a01OujmsHWr6wTB9OLkwTrIAAcAAYHkZIn1XGoml84GtpqEVABHK7wTbqKzNJgAWhCeTyHX0cDROBJm3KOyQ4TuGUihBwKTS9LOcEu11CNL2Khgbz+AKBSAATLzXDhWEkAMIQQjUzJMACsHXQkQAKm8rLT7iBpukAJJQAqwbxgb4aACCRu8MGI7FukTkciAA

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  Shortening the `if` statement renders the example easier to understand:
...but Prettier will not insert the brackets if they are omitted:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgJ4CycMAFhACYAUJACgIYBOzhAlPsADpT58zbHigAZHAGcY+ALz4cUHDAbEW7LgG5+gnKnx1huaBOkA6ADYIA5lTmz5ABm6sK6VgMfaoO-AHo-fAA5CHw4VlYIVgAafAB3OHxIWEV0OF8A-EAyAn4AX34QaJAIAAdjKElkUDZIuPUESpRmCzjmYkqigCN2MABrCgBlDjgJKDhkVGbJOC6e-pgBkuFFa2QYVjSiuEJOuBoaPbFmKGt0Zms4ADEowmYYXBPkEGZ0GAhCkEoYQgsAdUplHBJEswHABg1lDgAG7KYhPMCSDogRTTVgwRjsay3CZTGYgABWkgAHgMVlYAIroCDwHEWaZFJasVFPTrMXYWD4lViKGC-HA0KjIAAcjgZkWmv3YJSeXKB4Sh4yKAEcqfAMaVGs9JABaMZ7PYfVwqnCuDHnbFISZ0vHTQg4NYbG1kuCU6njS24oowNl8gWUZAAJi97BwFhWAGEIIQLSAgQBWD7oaYAFTZjSt9JAULSAEkoAdYAMwNyygBBfMDGDEKy06a5XJAA

....it's the bracket-omission, not the line breaking, that we need to call out (assuming we want this exception, which IDK).

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Anyway, both spacing and indentation are [enforced by Prettier](https://prettier.io/docs/en/index.html).
I thought we were omitting things that were covered by Prettier?

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> -  console.log('Hello');
This is wordy compared to almost all our current practice about commenting "expected output". I'm not convinced it is helpful to comment the fact that `console.log()` writes to the browser JS console. Also it's very common for us to have the comment after the line in cases like this, or on the next line.

e.g.

```js
console.log(filterItems(fruits, 'ap')); // ['apple', 'grapes']
console.log(filterItems(fruits, 'an')); // ['banana', 'mango', 'orange']
```

is it really the proposal to change this to:

```js
// Output the string '['apple', 'grapes']' to the browser's JS console
console.log(filterItems(fruits, 'ap'));

// Output the string '[banana', 'mango', 'orange']' to the browser's JS console
console.log(filterItems(fruits, 'an'));
```

? I don't think this is an improvement.

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- For collections, don't put the type (list, array, queue) in the name. Use the content name in the plural form. For example, for an array of cars, use `cars` and not `carArray` or `carList`. That wa
I think while this is great guidance for real code it is tricky for code samples in documentation, which often want to show the abstract form of a feature outside a particular application.

It's extremely common practice, again, for us to do things like:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#array-like_objects
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#find_all_prime_numbers_in_an_array

(these are the first two pages I chose, and both do it)

I'm not sure that changing all these is a good use of our time.

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +[Conditional (or ternary) operators](/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) should be used when returning a value.
I don't really understand this. There are lots of ways of returning a value, surely we shouldn't use ternary operators for all of them? I assume this wants to say that we should use ternary operators in preference to something like:

```js
let x;
if (condition) {
  x = 1;
else {
  x = 2;
} 
```

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When possible, put on a single line, as shown below:
Prettier takes care of this:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBnGBDGAV20wF5MAKPAczkwD5yBGADgEoAdKTTAfkwDkeACaFUMAVx5JBAWwCWUCACcBAbhAAaEBAAOMedGzJQeZcogB3AApmExlHlSW8AT2PaARsrxgA1hgAyniycAAyinDIAGZO2HBePv5Bur6K1MgwyoQJIHCynnDCwkVheFDUhDRwAGIqsgQGFcggeIQwEFogABYwsqgA6t3y8NipYHCB9iPyAG4jri1g2B4givHKMNY+1A0xcbkAVtgAHoHp6ACKhBDw+6jx2qnKGy2eeIWoXbrKijAD8mEMG6yBYAAYnhZ4gMfLoWj84BtZlFtABHG7wbZ6BytbAAWigcCKRS6yjg6PkZO2ND2SFiD1y8QUmWyjIucGutyidIO2nwngBQJBSAATHyfPJUOkAMIQWS0vLYACsXWIcAAKh8HPTHiBZjkAJJQEqwQJgX76ACCxsCMFc6Hu8QAvk6gA

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Always use the ["strict" equality](/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) and inequality operators over the traditional equality and inequality operators.
"Always" but then we have an exception below. Maybe "Prefer" is better?

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Not writing the parameter list is called _optional catch binding_ and has been available in every browser since 2019.
This doesn't seem relevant.

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +String literals can be enclosed with single quotes, like `'A string'`, or with double quotes, like `"A string"`. Which one to use is enforced by Prettier, so don't worry about which one to use.
I'm not sure what this adds, as a guideline...

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +pets[pets.length] = "cat";
:-o who would do a thing like this?!

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +);
```suggestion
const array1 = [1, 2, 3, 4];
let sum = array1.reduce((a, b) => a + b);
```

(Prettier will do this anyway)

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Use the method definition syntax:
I would expect this to be in "objects" above, where we talk about using `class` (and actually have an example of this syntax).

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When both techniques are possible, we don't have any preference.
I have a preference for using async/await for promise chaining.

2022-08-26 18:54 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is a modal to the whole window, which is annoying. Instead, u
We might want to say: in live samples, use "a dedicated UI element". I think using `console.log` in live samples is problematic. We should also probably link to live samples from here.

(actually I think it would be cool if live samples had a built-in "dedicated UI element" instead of making people reimplement it. Maybe we should look into this...)

2022-08-27 02:58 UTC, Josh-Cena commented
Oh well, I'll wait for the comments above to be resolved before looking at this to prevent duplication...

2022-08-27 04:18 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Anyway, both spacing and indentation are [enforced by Prettier](https://prettier.io/docs/en/index.html).
I missed this one…
```suggestion
```

2022-08-27 04:24 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Having good variable names is essential to understanding code. Use short identifiers, and avoid non-common abbreviations. Ideally, a variable name should be between 3 to 10-character long. (This is a
I'm mixing both suggestions here:

```suggestion
Good variable names are essential to understanding code.

- Use short identifiers, and avoid non-common abbreviations. Good variable names are usually between 3 to 10-character long, but as a hint only. For example, `accelerometer` is more descriptive than abbreviating to `acclmtr` for the sake of character length.
```

2022-08-27 04:26 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When possible, like iterating through all collection elements, avoid using the classical `for (;;)` loop; prefer `for...of` or `.forEach()`.
```suggestion
When iterating through all collection elements, avoid using the classical for (;;) loop; prefer for...of or .forEach().
```

2022-08-27 04:28 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +String literals can be enclosed with single quotes, like `'A string'`, or with double quotes, like `"A string"`. Which one to use is enforced by Prettier, so don't worry about which one to use.
```suggestion
String literals can be enclosed within single quotes, as in `'A string'`, or within double quotes, as in `"A string"`. Don't worry about which one to use; Prettier keeps it consistent.
```

2022-08-27 04:31 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +pets[pets.length] = "cat";
Believe it or not, it is listed at several places on the web, like: https://www.samanthaming.com/tidbits/87-5-ways-to-append-item-to-array/

2022-08-27 04:32 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Queues are collection following the [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)) principle. When using a JS `Array` as a queue, use the [`push()`](/en-US/docs/Web/JavaScript
This sounds strange to me as _queues is plural, and collection singular.

@dipikabh, what about:
```suggestion
Queues are collections that follow the [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)) principle. When using a JS `Array` as a queue, use the [`push()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) method to add an item and the [`shift()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift) method to remove the first item. Do not use an index.
```

2022-08-27 04:33 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Stacks are collection following the [LIFO](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) principle. When using a JS `Array` as a stack, use the [`push()`](/en-US/docs/Web/JavaScript/Refer
Ditto
```suggestion
Stacks are collections that follow the [LIFO](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) principle. When using a JS `Array` as a stack, use the [`push()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) method to add an item and the [`pop()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop) method to remove the last item. Do not use an index.
```

2022-08-27 04:36 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Use the method definition syntax:
@wbamberg, The reason I move this down here is this is not a JavaScript guideline but a Web API one. `.innerHTML` and `.textContent` are part of the DOM.

Maybe, in the future, we'll want to expand this section (we need to assess what Web APIs we want to avoid in our examples) and maybe move it to its specific page (_Web APIs to avoid_ or similar)

2022-08-27 04:48 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When both techniques are possible, we don't have any preference.
That's an interesting point.

I also would if there wasn't still a limitation about not having any `async` at the top level (outside a module)

I think it is worth discussing. To keep all the discussions together, can you propose this in [mdn discussion](https://github.com/orgs/mdn/discussions/143) as a new suggested answer? That's how I determined if there was a consensus or not about the different features. Thank you, @wbamberg!

> Top-level await is supported only in the [ECMAScript](https://en.wikipedia.org/wiki/ECMAScript) module, and [Node.js](https://nodejs.org/) and [Express](https://expressjs.com/) use [CommonJS](https://en.wikipedia.org/wiki/CommonJS) modules. However, support for the ECMAScript module has been added in Node.js. So, instead of using require to fetch the modules, I use import in the entire app. CommonJS does not support top-level await.

2022-08-27 04:49 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If all browser supports a feature, don't prefix it.
```suggestion
If all major browser (Chrome, Edge, Firefox, and Safari) supports a feature, don't prefix it.
```

2022-08-27 05:03 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use new methods once every major browser supports them. You can use new syntax once every major browser supports them and two years have elapsed.
I made a difference between _methods_ and _syntax_ because I had the feeling that the adoption of a new method (like a new `Array` method or `hasOwn()` is really quick once the major browsers support it. 

For new "syntaxes", like a new for loop (`for…of` for example), I have the impression that, even if supported by all the major browsers, developers need more time to understand them, get used to them, and finally adopt them broadly.

It is a feeling not backed by hard data.

> And what is the set of modern browsers?

Likely a bit western-world-centric, but Chrome, Edge, Firefox, and Safari, both on desktop and mobile. These cover the three engines and, in the West, a good deal of the market (and others less known browsers almost all use one of these engines).

A feature supported by the three engines, and these browsers, for 2 years, will cover a good deal of the world's users I excluded IE users and ignored those that can't update, even with an evergreen browser: as we are norm-setters, I think this is enough (and transpilers exist to help with most other use cases)

2022-08-27 05:05 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Add a comment if the purpose or logic of the code isn't obvious. Comments are not necessary, for example, when functions have explicit names that describe what they're doing. This comment doesn't add
I'm resolving this one as there is no change suggested (both lines are identical).

2022-08-27 05:14 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Variable names
I tried to follow a logical flow of what developers would need to now:

1. I started with the general syntax
2. Comments because they are important
3. Variables names and operator-related rules
4. Control statements (loops and if…else)
5. The triad, `Array`, `String`, `Object`
6. More advanced topics, like `Functions and Classes` and `asynchronous calls`.

I'm not sure an alphabetic would bring something here: the titles are a bit arbitrary, so readers won't know in advance the section name they are looking for and will need to scan the ToC anyway. _A contrario_ it will make the linear reading of the document less logical as you don't go from basic features used everytime to less common ones: rules about classes will be found before rules about strings, and rules about `Array`, `String` and `Object` would be scattered all over the document.

2022-08-27 05:18 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  ```
👍  Fixed.

2022-08-27 05:20 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +```
Agreed.

```suggestion
```

2022-08-27 05:31 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +[Conditional (or ternary) operators](/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) should be used when returning a value.
Yes, this is the intention.

```suggestion
When you want to store to a variable a literal value depending on a condition, use a [Conditional (or ternary) operators](/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator), don't use an `if...else` statement. This rule also applies when returning a value. Write:

```js example-good
let x = condition ? 1 : 2;
```

Do not write:

```js example-bad
let x;
if (condition) {
  x = 1;
else {
  x = 2;
} 
```

2022-08-27 05:33 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When possible, put on a single line, as shown below:
You're right. I'm removing this example.

2022-08-27 05:36 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Always use the ["strict" equality](/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) and inequality operators over the traditional equality and inequality operators.
😄 
```suggestion
Prefer the ["strict" equality](/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) and inequality operators over the traditional equality and inequality operators.
```

2022-08-27 05:38 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
I agree.

2022-08-27 05:39 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Not writing the parameter list is called _optional catch binding_ and has been available in every browser since 2019.
Agreed, it felt odd when I wrote it.
```suggestion
```

2022-08-27 05:51 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +pets[pets.length] = "cat";
(And I'm pretty sure to have found one case, but I don't remember where)

2022-08-27 05:53 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +## Functions and classes
I have to read the section again (I find it odd that there is no mention of classes).

The reason why I grouped both is that, in JavaScript, classes are syntactic sugar over functions.

2022-08-27 13:49 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Use the method definition syntax:
I was referring to " Use the method definition syntax:" in https://pr19929.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript#functions_and_classes .

2022-08-27 15:08 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When both techniques are possible, we don't have any preference.
Right—top level await is not at all well supported and could be confusing when it doesn't work. I would say promise chaining at the top level but use async functions where we can (but preferably not async IIFEs because those look... ugly)

2022-08-27 15:12 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use new methods once every major browser supports them. You can use new syntax once every major browser supports them and two years have elapsed.
I don't know. I find them equivalent. For example, async functions are a lifesaver to every developer. I also find new _syntax_ easier to adopt—if you use TypeScript, you are going to transpile/downlevel anyway, so it "just works" even when you are targeting Node (I write Node programs more than I write web apps). OTOH people rarely add polyfills for Node packages, so methods/APIs may not always work.

2022-08-27 15:14 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't use experimental features. In all cases, readability is more important than shaving a few characters.
Right. For example, I won't be anticipating any serious developer today to ship an application untranspiled. In this case using brand-new syntax (even not stage 4!) sounds perfectly fine to me, as long as transpilers like tsc and Babel support it.

2022-08-27 15:18 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +JS-style comments are marked with `//`, as opposed to C-style comments enclosed between `/* … */`.
I don't think there's such thing as "JS-style comment". Both comments are equally popular. There's only "single-line comment" and "block comment", the latter some call "C-style" (which is very aged).

2022-08-27 15:43 UTC, Josh-Cena requested changes
Here is my pile of comments. There are also some formatting changes but I'll leave those towards the end.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
Add a mention of multiline comments? I think in the past you've refactored a few `/* */` multiline comments to use `//`. I don't have strong opinions. One place where I'll use `/*` though is to indicate console output, especially where formatting is important. We probably want to use JSDoc here and there as well (it's a pretty good practice).

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Avoid using articles and possessives. For example, use `car` instead of `myCar` or `aCar`.
`myCar` sounds a bit dumb, but `myArray` or `myFunction` is pretty common. The purpose is to demonstrate that the name is arbitrary. I've also written `aCar` myself—the purpose is to write code as if it's prose. (I admit that's a bit arbitrary in itself)

I think putting it in the guideline is fair since we want to avoid _overuse_, but just pointing out potential exceptions.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Use lowerCamelCasing. Do not use `_`. Use concise, human-readable, and semantic names where appropriate. For example, use `currencyName` rather than `currency_name`.
I think `camelCase` refers to the lowercase variant. The uppercase one is `PascalCase`?

We may also want to mention that this applies to primitive values, since objects and classes are discussed in the following section, and that in certain cases `ALL_CAPS` is acceptable?

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    function Person(name, year) {
```suggestion
    constructor(name, year) {
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    function Person(name, year) {
```suggestion
    constructor(name, year) {
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When you want to store to a variable a literal value depending on a condition, use a [Conditional (or ternary) operators](/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator), don't u
```suggestion
When you want to store to a variable a literal value depending on a condition, use a [conditional (ternary) operator](/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) instead of an `if...else` statement. This rule also applies when returning a value. Write:
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Prefer the ["strict" equality](/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) and inequality operators over the traditional equality and inequality operators.
```suggestion
Prefer the [strict equality](/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) (triple equals) and inequality operators over the loose equality (double equals) and inequality operators.
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If you need to use `==` or `!=`, consider adding a comment to explain why you need it (i.e., the type of coercion you want to perform in the code).
Mention that `== null` is the _only_ acceptable case. (Yes, ONLY) TypeScript will fail on all other cases (and developers care about TypeScript-friendliness a lot these days).

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When iterating through all collection elements, avoid using the classical for (;;) loop; prefer for...of or .forEach().
```suggestion
When iterating through all collection elements, avoid using the classical `for (;;)` loop; prefer `for...of` or `.forEach()`.
```

Also add a note to explain that for non-arrays you need to check if it actually works? `for...of` requires the variable to be iterable and `forEach()` requires that method to be actually present.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +The example below does not follow the recommended guidelines for the initialization (it is a `var`…).
```suggestion
The example below does not follow the recommended guidelines for the initialization (it implicitly creates a global variable and will fail in strict mode).
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +> **Note:** Consider not using a `for` loop at all. If you are using an [`Array`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) (or even a [`String`](/en-US/docs/Web/JavaScript/Reference
```suggestion
> **Note:** Consider not using a `for` loop at all. If you are using an [`Array`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) (or a [`String`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) for some operations), consider using more semantic iteration methods instead, like [`map()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [`every()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every), [`findIndex()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex), [`find()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), [`includes()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), and many more.
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  case `chicken`:
Use normal quotes (also mention in the strings section to not overuse template literals?)

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
>    console.error(e);
Explicitly mention that `console.error()` is preferred over `console.log()`. Also, only use `try...catch` if there are _recoverable_ errors—let everything else bubble through.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Stacks are collection following the [LIFO](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) principle. When using a JS `Array` as a stack, use the [`push()`](/en-US/docs/Web/JavaScript/Refer
Please don't mention using arrays as stacks and queues (especially queues)—they are really inefficient. It also seems out-of-the-place for a style guide, since that's literally how you _ought to_ be using stacks/queues.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Use short identifiers, and avoid non-common abbreviations. Good variable names are usually between 3 to 10-character long, but as a hint only. For example, `accelerometer` is more descriptive than
Also mention that we should avoid placeholders like `foo` and aim for examples that look relevant to real life.

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +function notVeryObviousName() {
```suggestion
function doIt() {
```

2022-08-27 15:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When using anonymous functions inside a method that requires a function as a parameter, when you do not need to bind `this`, use an arrow function to make the code shorter and cleaner.
```suggestion
When using anonymous functions as a callback (a function passed to another method invocation) and you do not need to access `this`, use an arrow function to make the code shorter and cleaner.
```

2022-08-27 15:48 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  case `chicken`:
This is a typo. My intend was to use normal quotes.

2022-08-29 08:08 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +JS-style comments are marked with `//`, as opposed to C-style comments enclosed between `/* … */`.
Fixed.

2022-08-29 08:14 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Use lowerCamelCasing. Do not use `_`. Use concise, human-readable, and semantic names where appropriate. For example, use `currencyName` rather than `currency_name`.
Fixed

2022-08-29 08:15 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Use lowerCamelCasing. Do not use `_`. Use concise, human-readable, and semantic names where appropriate. For example, use `currencyName` rather than `currency_name`.
I prefer to avoid mentioning ALL_CAPS. (I don't think it is really needed)

2022-08-29 08:16 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    function Person(name, year) {
Fixed.

2022-08-29 08:20 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Stacks are collection following the [LIFO](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) principle. When using a JS `Array` as a stack, use the [`push()`](/en-US/docs/Web/JavaScript/Refer
Let's shorten indeed.

2022-08-29 08:36 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
>    console.error(e);
Using `console.error()` instead of `console.log()` is mentioned under Web APIs (even if it is a Web APIs copied in the Node APIs, which is good, it is not part of JavaScript itself).

('m adding the info about recoverable errors, that's a good point)

2022-08-29 09:13 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When using anonymous functions inside a method that requires a function as a parameter, when you do not need to bind `this`, use an arrow function to make the code shorter and cleaner.
Fixed.

2022-08-29 09:25 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If you need to use `==` or `!=`, consider adding a comment to explain why you need it (i.e., the type of coercion you want to perform in the code).
Fixed

2022-08-29 09:36 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> -  console.log('Hello');
Yes, you are right. The former (all in one line) is clearly what I would do, too.

The example is not good (as it uses `console.log()`), and we have to clarify that sometimes it is ok to put on one line.

2022-08-29 09:40 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use the modern and well-supported JavaScript features in MDN Web Docs code examples.
Removed

2022-08-29 09:43 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is a modal to the whole window, which is annoying. Instead, u
Fixed.

And I agree having a dedicated UI element for live examples would be great. I'll even dream of uniformizing the way we log stuff in our mdn/dom-examples & co repositories (one time a `<p>` is used, another a `<textarea>`, a `<pre>` or an `<output>`, directly or via a `log()` function or even a `Log()` class.

2022-08-29 09:45 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +You can use new methods once every major browser supports them. You can use new syntax once every major browser supports them and two years have elapsed.
I removed the distinction: the condition is the (four) major browsers support it now.

2022-08-29 09:59 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
I added a mention and examples of comments.

I've not added the two exceptions for using `/* */` (console.log, JSDocs) because I think we can speak about these with concrete examples in follow-up PRs, if needed.

2022-08-29 11:49 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Avoid using articles and possessives. For example, use `car` instead of `myCar` or `aCar`.
I added a comment about the existence of exceptions.

2022-08-29 11:57 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  Shortening the `if` statement renders the example easier to understand:
Good catch! Fixed in next commit.

2022-08-29 11:58 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't put everything on one line:
Yes, I rewrote this part to focus on the braces and completely ignore the formatting, enforced by Prettier.

2022-08-29 12:00 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Queues are collection following the [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)) principle. When using a JS `Array` as a queue, use the [`push()`](/en-US/docs/Web/JavaScript
This section has been removed (for another reason), this is no longer relevant.

2022-08-29 12:01 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Stacks are collection following the [LIFO](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) principle. When using a JS `Array` as a stack, use the [`push()`](/en-US/docs/Web/JavaScript/Refer
No longer relevant.

2022-08-29 12:11 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- For collections, don't put the type (list, array, queue) in the name. Use the content name in the plural form. For example, for an array of cars, use `cars` and not `carArray` or `carList`. That wa
I've added a sentence to allow for exceptions so that new occurrences should not get in.

To fix the existing occurrences, I'm not too worried:
- if we stop adding new ones, it would already be better
- don't underestimate the power of the community. (There are about 180 pages affected; it doesn't look like a lot compared to what we already fixed.

2022-08-29 12:34 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
Fixed.

2022-08-29 12:46 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> -  console.log('Hello');
I rewrote the section to avoid `console.log` in the good example and added a new section about the output of logs, letting us add the comment on the same line.

2022-08-29 12:48 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +## Functions and classes
You were right, I removed classes (they are handled under Objects)

2022-08-29 13:05 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +To do so, you use `/* … */` in the parameter list. It is an exception to the rule only to use JS-style comments (`//`).
Added.

2022-08-29 13:16 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Use the method definition syntax:
Sorry, I mixed the lines (so many comments 😄 ). Yes, you are right. Moving this up.

2022-08-29 13:20 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Pay attention! When you declare a local variable for a case, you need to use braces to define a scope:
I rephrased it, thanks.

Note that we don't use `__` for bold, but `**` (and we use `_` for italics, and not `*`)

2022-08-29 13:24 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    if (actionList.length === 0) return 0;
I still don't think this should be an exception. Let's say we want to turn the ESLint `curly` rule on. There isn't an option to enforce this kind of style.

2022-08-29 13:30 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Don't use experimental features. In all cases, readability is more important than shaving a few characters.
So I'm replacing mentions of modern browsers and experimental features by saying that it must be supported by Chrome, Edge, Firefox, and Safari.

I agree that large project use transpilers, but not everybody use them. Professional developers are likely to do it, but students or anybody writing a quick script at home are less likely to set up a toolchain.

I think we should avoid friction for learners, too. That's why I think we should restrict the feature we use in examples to features available in the latest versions of browsers.

Commit incoming.

2022-08-29 13:37 UTC, Josh-Cena requested changes

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
Add an example of when the output gets long? My own convention is to put the message after the `console.log` line.

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Short comments are usually better, so try to keep them in one line of 120 characters. If this is not possible, use `//` at the beginning of each line:
```suggestion
Short comments are usually better, so try to keep them in one line of 70 characters. If this is not possible, use `//` at the beginning of each line:
```

On an average laptop screen (1440px), each code block is about 70 cols wide on MDN.

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When defining an object class, use _CamelCase_ (starting with a capital letter, also known as PascalCase) for the class name and _camelCase_, starting with a lowercase letter, for the object property
```suggestion
When defining a class, use _PascalCase_ (starting with a capital letter) for the class name and _camelCase_ (starting with a lowercase letter) for the object property and method names.
```

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +The `Object.hasOwnProperties()` method has been deprecated in favor of `Object.hasOwn()`.
```suggestion
The `Object.prototype.hasOwnProperty()` method has been deprecated in favor of `Object.hasOwn()`.
```

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Where possible, use the `function` declaration to define functions over function expressions:
```suggestion
Where possible, use the `function` declaration to define functions over function expressions.
```

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +}
```suggestion
const x = () => {
  // …
};
```

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +In addition to these JavaScript language features, we reccomend a few guidelines related to Web APIs to keep in mind.
```suggestion
In addition to these JavaScript language features, we recommend a few guidelines related to Web APIs to keep in mind.
```

2022-08-29 13:37 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live example on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is modal to the whole window, which is annoying. In static co
```suggestion
- The `alert()` function is unreliable. It doesn't work in live examples on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is modal to the whole window, which is annoying. In static code examples, , use `console.log()` or `console.error()`. In [live examples](/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples), avoid `console.log()` and `console.error()` as they are not displayed. Use a dedicated UI element.
```

2022-08-29 13:41 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When both techniques are possible, we don't have any preference.
I will write to use async/await when possible and to keep in mind that if the code is intended to be used anywhere (at the top level), it isn't possible.

Let me think about how to phrase this.

2022-08-29 14:11 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When both techniques are possible, we prefer using the simpler `async`/`await` syntax. Unfortunately, it isn't possible everywhere. Especially, you can't use `await` at the top-level JavaScript, thou
```suggestion
When both techniques are possible, we prefer using the simpler `async`/`await` syntax. Unfortunately, you can't use `await` at the top level unless you are in an ECMAScript module. CommonJS modules used by Node.js are not ES modules. If your example is intended to be used everywhere, avoid top-level `await`.
```

2022-08-29 14:13 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
I'm adding a longer example. I'm not convinced we should also list the block comments usage here; it sounds like a very edgy case.

2022-08-29 14:14 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
Yeah, I'm fine with not making an explicit exception.

2022-08-29 16:43 UTC, Josh-Cena requested changes
Mostly nits this time

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
Prettier has options and the default options can change. We still need to establish our opinion on a few controversial ones, like semicolons (yes), double quotes (yes), space between object literal braces (yes), arrow function parens (yes), trailing commas (all), etc.

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Use braces with control statement.
```suggestion
### Use braces with control flow statements
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Even if, control statements like `if`, `for`, `while` don't mandate for the use of braces when the content is made of one single statement, always use braces. Write:
```suggestion
- While control flow statements like `if`, `for`, and `while` don't require the use of braces when the content is made of one single statement, you should always use braces. Write:
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Add a comment if the purpose or logic of the code isn't obvious, to describe the intention of the code makes the example clearer, as shown below:
This sentence doesn't read fluently for me

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +for (let i = 0; i < 4; i++ ){
```suggestion
for (let i = 0; i < 4; i++) {
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +for (let i = 0; i < 4; i++ ){
```suggestion
for (let i = 0; i < 4; i++) {
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +closeConnection()
```suggestion
closeConnection();
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- For collections, avoid adding the type (list, array, queue) in the name. Use the content name in the plural form. For example, for an array of cars, use `cars` and not `carArray` or `carList`. Ther
```suggestion
- For collections, avoid adding the type (list, array, queue) in the name. Use the content name in the plural form. For example, for an array of cars, use `cars` and not `carArray` or `carList`. There may be exceptions, like when you want to show the abstract form of a feature without the context of a particular application.
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- If a variable will not be reassigned, prefer `const`, like so:
We should consistently use bullets or consistently not

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  Avoid old idioms when forcing a value to a type. In particular, avoid `+val` to force a value to a number and `"" + val` to force it to a string. Use `Number()` and `String()`, without new, instead
Indentation looks unnecessary

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Control statements
Maybe move the "curly" point above to here?

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Keep in mind, that only _recoverable_ errors should be caught and handled. All non-recoverable errors should be let through and bubble up the call stack.
```suggestion
Keep in mind that only _recoverable_ errors should be caught and handled. All non-recoverable errors should be let through and bubble up the call stack.
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
Add a sentence like this?

> Don't overuse template literals: if there are no substitutions, use a normal string literal instead.

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When using anonymous functions inside as a callback (a function passed to another method invocation) and you do not need to access `this`, use an arrow function to make the code shorter and cleaner.
```suggestion
When using anonymous functions as a callback (a function passed to another method invocation) and you do not need to access `this`, use an arrow function to make the code shorter and cleaner.
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Consider avoiding using arrow function to assign a function to an identifier. In particular, don't use arrow functions for methods. Use named functions with the keyword `function`:
```suggestion
Consider avoiding using arrow function to assign a function to an identifier. In particular, don't use arrow functions for methods. Use function declarations with the keyword `function`:
```

We could also mention concise bodies as exceptions? If we can write `const x = () => ({ foo })` I'd rather not turn it into a method or declaration.

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  return e.id
```suggestion
  return e.id;
```

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- [Promises](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), including the `finally()` method
The `finally()` seems a bit out of place here. It's not even that controversial or hard to understand, and we rarely use it anyway.

2022-08-29 16:43 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +let s = d/t;
```suggestion
let s = d / t;
```

2022-08-29 16:47 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +The `Object.prototype.hasOwnProperty()` method has been deprecated in favor of `Object.hasOwn()`.
Mention that we want to use shorthand. `{ name, age }` instead of `{ name: name, age: age }`.

2022-08-30 04:22 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
What about not listing this in this document but linking to the [config file](https://github.com/mdn/content/blob/main/.prettierrc.json) instead? That way, we don't complexify this place.

In addition, we could explicitly mark the default values.

cc/ @Josh-Cena, @wbamberg.

```suggestion
On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep the code style consistent (and to avoid off-topic discussions). You can consult our [configuration file](https://github.com/mdn/content/blob/main/.prettierrc.json) to learn about the current rules.
```

2022-08-30 04:23 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
> What about not listing this in this document but linking to the [config file](https://github.com/mdn/content/blob/main/.prettierrc.json) instead? That way, we don't complexify this place.

+1

2022-08-30 04:27 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
Makes sense to me

2022-08-30 04:28 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- [Promises](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), including the `finally()` method
Fixed

2022-08-30 04:29 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  Avoid old idioms when forcing a value to a type. In particular, avoid `+val` to force a value to a number and `"" + val` to force it to a string. Use `Number()` and `String()`, without new, instead
Removed.

2022-08-30 04:32 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +
Added

2022-08-30 04:37 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +The `Object.prototype.hasOwnProperty()` method has been deprecated in favor of `Object.hasOwn()`.
Mentioned

2022-08-30 09:16 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Control statements
Moved.

2022-08-30 09:23 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep code style consistent (and to avoid off-topic discussions).
We only list non-default values in it right now, but we can add default values explicitly so that:
- we communicate we chose this value consciously
- we avoid being surprised by thousands of changes if Prettier changes its default. (We may still want to change it too, but we will do it in an ordered way)

Committing the sentence.

2022-08-30 09:31 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Add a comment if the purpose or logic of the code isn't obvious, to describe the intention of the code makes the example clearer, as shown below:
Fixed.

2022-08-30 09:47 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- If a variable will not be reassigned, prefer `const`, like so:
Good point!

Now it uses a bullet list when several items are in a section. (And no bullet list if only one is)

2022-08-30 13:39 UTC, Rumyra approved these changes

2022-08-30 13:42 UTC, dipikabh requested changes
Some tiny nits

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Variable names
I think the disconnect here is because of how we think readers will consume this information. To me, these guidelines are more like a reference/dictionary where readers will come to check out specific style info. IMO, readers will not necessary read this material from top to bottom. Understanding one section is not dependent on understanding the content of prior sections. I feel the readers will glance the TOC and go to a specific section. With that perspective, placing 'Arrays' and 'Functions' for example, in an alphabetic order is okay. I don't think the H2 titles are that arbitrary.
(It would really help when we also have H3 titles in TOC!!)

However, if the belief is that most readers will read this article in its entirety in a linear fashion, then a logical flow might help. However, the order of sections in a logical flow can be subjective. Somebody else might suggest a slightly different logical flow.

Since we are not really explaining the concepts themselves, just how we present them on MDN, I think it might be better to go with an unbiased and predictable ordering - that is, alphabetically. But again, we need to know how readers really use this information "most of the time" rather than guessing.

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  If you add a `break`, it will be unreachable. Do not write:
```suggestion
  If you add a `break` statement, it will be unreachable. Do not write:
```
Can we replace 'it' here to say what will be unreachable?

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Put `default` as the last case, and don't end it with a `break`. If you need to do it differently, add a comment explaining why.
```suggestion
- Use `default` as the last case, and don't end it with a `break` statement. If you need to do it differently, add a comment explaining why.
```

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Remember that, when you declare a local variable for a case, you need to use braces to define a scope:
```suggestion
- Remember that when you declare a local variable for a case, you need to use braces to define a scope:
```

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Use variable names like shown here:
```suggestion
- Do not use the [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) naming convention. Do not prefix the variable name with its type. For example, write `bought = car.buyer !== null` rather than `bBought = oCar.sBuyer != null` or `name = "John Doe"` instead of `sName = "John Doe"`.
- For collections, avoid adding the type such as list, array, queue in the name. Use the content name in the plural form. For example, for an array of cars, use `cars` and not `carArray` or `carList`. There may be exceptions, like when you want to show the abstract form of a feature without the context of a particular application.
- For primitive values, use _camelCase_, starting with a lowercase character. Do not use `_`. Use concise, human-readable, and semantic names where appropriate. For example, use `currencyName` rather than `currency_name`.
- Avoid using articles and possessives. For example, use `car` instead of `myCar` or `aCar`. There may be exceptions, like when describing a feature in general without a practical context.
- Use variable names as shown here:
```

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +If all major browser (Chrome, Edge, Firefox, and Safari) supports a feature, don't prefix it. Write:
```suggestion
If all major browsers (Chrome, Edge, Firefox, and Safari) support a feature, don't prefix the feature. Write:
```

2022-08-30 13:42 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `alert()` function is unreliable. It doesn't work in live examples on MDN that are inside an {{HTMLElement("iframe")}}. Moreover, it is modal to the whole window, which is annoying. In static c
```suggestion
- The `alert()` function is unreliable. It doesn't work in live examples on MDN Web Docs that are inside an {{HTMLElement("iframe")}}. Moreover, it is modal to the whole window, which is annoying. In static code examples, use `console.log()` or `console.error()`. In [live examples](/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples), avoid `console.log()` and `console.error()` because they are not displayed. Use a dedicated UI element.
```
note the two commas after "In static code examples"

2022-08-30 13:52 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +### Variable names
I don't think I've seen a style guide organized in alphabetical order. The first time you read it, you definitely go through every single point to get a grasp. In the future, you can simply use <kbd>Ctrl</kbd><kbd>F</kbd> to navigate. (Or H3 headings in TOC)

2022-08-30 14:06 UTC, Josh-Cena requested changes

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  let var3 = var4 = "Apapou";
```suggestion
  let var3 = var4 = "Apapou"; // var4 is implicitly created as a global variable; fails in strict mode
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
}
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
}
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +let x = condition ? 1 : 2;
```suggestion
const x = condition ? 1 : 2;
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  let name = 'Chris';
```suggestion
  const name = 'Chris';
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  let name = 'Chris';
```suggestion
  const name = 'Chris';
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +When adding items to an array, use [`push()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) and not direct assignment. Let's consider the following array:
```suggestion
When adding items to an array, use [`push()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) and not direct assignment. Consider the following array:
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +let object = {};
```suggestion
const object = {};
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    };
```suggestion
    }
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
}
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
}
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
}
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- Where possible, use the `function` declaration to define functions over function expressions.
```suggestion
- Where possible, use the function declaration over function expressions to define functions.
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  let sum = array1.reduce((a, b) => a + b);
```suggestion
  const sum = array1.reduce((a, b) => a + b);
```

2022-08-30 14:06 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +  let sum = array1.reduce(function (a, b) {
```suggestion
  const sum = array1.reduce(function (a, b) {
```

2022-08-30 15:31 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- In examples, but rarely in production code, we often use `console.log()`, `console.error()`, or similar functions to output messages. In such cases, you can put a comment after the function with th
I've rewritten it. Commit incoming.

2022-08-31 07:27 UTC, dipikabh approved these changes
Thank you @teoli2003 for your work on updating this document! 🙌

2022-08-31 08:47 UTC, bsmth approved these changes
Thanks a lot 👍🏻

2022-08-31 14:56 UTC, Josh-Cena requested changes
Almost LGTM! There is a syntax error and some typos so I'll continue to block it, but should be quick.

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +Prettier formats all the code and keeps the style consistent. Nevertheless, there are a few additional rules that you need to follow.
There's only one subheading here and frankly I can't think of any extensions. Maybe merge it with the previous H2 heading?

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +// The imaginary function that follows has some unusual limitation that I want to call out.
This line is long and wraps on average laptops. Maybe:

```suggestion
// The imaginary function that follows has some unusual
// limitations that I want to call out.
```

(Also a grammar fix)

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +};
```suggestion
array.forEach((value, /* index, array */) => {
  // …
});
```

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    case `chicken`:
Use normal quotes

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +    }
```suggestion
  try {
    console.log(getResult());
  } catch {
    console.error("An error happened!");
  }
```

2022-08-31 14:56 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +- The `Object.prototype.hasOwnProperty()` method has been deprecated in favor of `Object.hasOwn()`.
```suggestion
- The [`Object.prototype.hasOwnProperty()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) method has been deprecated in favor of [`Object.hasOwn()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn).
```

2022-08-31 15:13 UTC, Josh-Cena approved these changes
I've committed the "critical" pieces myself. I still have a few review comments above; feel free to address them as you like before merging.

2022-08-31 15:25 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep the code style consistent (and to avoid off-topic discussions). You can consult our [configuration file](https://g
```suggestion
On MDN Web Docs, we use [Prettier](https://prettier.io/) as a code formatter to keep the code style consistent (and to avoid off-topic discussions). You can consult our [configuration file](https://github.com/mdn/content/blob/main/.prettierrc.json) to learn about the current rules, and read the [Prettier documentation](https://prettier.io/docs/en/index.html).
```

2022-08-31 15:26 UTC, Josh-Cena approved these changes
Looks great!

2022-08-31 16:30 UTC, wbamberg approved these changes
👍 thank you for looking after this monster PR!

2022-08-31 16:43 UTC, merged

2022-08-31 16:43 UTC, teoli2003 commented
Thank you all!

I'm merging this.

Note that the document is not set in stone, and we can open PRs or issues to discuss changes. We don't want to revert/change everything every month, but we surely have not thought of all edge cases, or some of the details will appear not a good idea.

🎉