Update return value for BeforeInstallEventPrompt.prompt()
mdn/content pull request #19927
Opened 2022-08-24 13:24 UTC by Vogel612

#### Summary

Updates the return value information for the `prompt()` method on `BeforeInstallEventPrompt` to reflect the current state of play in Edge and Chrome. I have not verified the behaviour on other browsers,

#### Motivation

The return value documentation did not match the actual behaviour "in the wild".

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-24 14:14 UTC, teoli2003 commented
I don't find a spec to compare.

@jpmedley Can you help us find somebody who can tell us what the return type is (and if it changed at some point)?  (And if there is a spec somewhere, it will be a bonus, and we could add it to bcd) (Thanks!)

2022-08-24 14:19 UTC, Elchi3 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPrompt", "BeforeInstallPrompt.platform")}} {{experimental_inline}}).
Looking at the example code and at the [old spec](https://www.w3.org/TR/2018/WD-appmanifest-20180220/#dom-promptresponseobject) & [new spec](https://wicg.github.io/manifest-incubations/#dom-promptresponseobject), it seems that `platform` isn't part of the promise object. 

"It contains one member, userChoice, which states the user's chosen outcome."

2022-08-24 15:02 UTC, Vogel612 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPrompt", "BeforeInstallPrompt.platform")}} {{experimental_inline}}).
Considering that I didn't base this on the spec, but what I encountered in chrome (and edge), I'm not surprised that the behaviour mismatches the spec. As mentioned in the PR comment I did not verify the behaviour on any other browsers to see which of them adheres to the spec.

2022-08-24 15:06 UTC, Vogel612 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPrompt", "BeforeInstallPrompt.platform")}} {{experimental_inline}}).
```diff
The `outcome` is either **`"accepted"`** or **`"dismissed"`** (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.userChoice")}} {{experimental_inline}}).
The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.platform")}} {{experimental_inline}})
```

2022-08-24 15:27 UTC, Vogel612 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPrompt", "BeforeInstallPrompt.platform")}} {{experimental_inline}}).
Based off the example already available on the page, running an "abridged"

```js
window.addEventListener("beforeinstallprompt", (e) => {
  e.preventDefault();
  e.prompt().then(r => { console.log('Result of the prompt: ' + r); });
}
```

results in:

```none
Result of the prompt: > {outcome: 'dismissed', platform: ''}
outcome: "dismissed"
platform: ""
[[Prototype]]: Object
```

I am running on Google Chrome version 104.0.5112.101

2022-08-24 17:30 UTC, jpmedley commented
> I don't find a spec to compare.
> 
> @jpmedley Can you help us find somebody who can tell us what the return type is (and if it changed at some point)? (And if there is a spec somewhere, it will be a bonus, and we could add it to bcd) (Thanks!)

[Here's the spec](https://wicg.github.io/manifest-incubations/index.html#beforeinstallpromptevent-interface).

I don't know how this can be returning anything other than an empty promise. The [source code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/app_banner/before_install_prompt_event.cc;l=83;bpv=0;bpt=0) does not show that it's resolving with anything. I checked code history. This has not changed since the feature's initial commit in 2015.

Is the 'in the wild' instance using a framework or wrapper of some kind?

2022-08-24 17:51 UTC, Vogel612 commented
> I don't know how this can be returning anything other than an empty promise.

14 lines down the return is not a `ScriptPromise()` (as in the linked line 83 and the following line 92), but a promise over the `user_choice_`. The blame points to [commit 69eeb5b](https://source.chromium.org/chromium/chromium/src/+/69eeb5b901d805ec2411212d52f1e8d935d58092) claiming to fix [bug 965939](https://bugs.chromium.org/p/chromium/issues/detail?id=965939), resulting in changed behaviour in 2019.

2022-08-24 18:06 UTC, jpmedley commented
I misread where the end of function was. Sorry about that. 

This is per the spec, so I'll need to add a note to the compat data. This was fixed in Chrome 76.

2022-08-24 18:18 UTC, Vogel612 commented
That just leaves open the wrinkle of the member `platform` within the `PromptResponseObject` that does not seem to be present in the spec ...

2022-08-26 06:24 UTC, Elchi3 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPrompt", "BeforeInstallPrompt.platform")}} {{experimental_inline}}).
Thanks, it is strange that it wasn't indicated in the IDL file! I see Joe filed that with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1356264

2022-08-26 06:25 UTC, Elchi3 commented
> That just leaves open the wrinkle of the member `platform` within the `PromptResponseObject` that does not seem to be present in the spec, yet [appears in the IDL](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/app_banner/app_banner_prompt_result.idl;bpv=0;bpt=0)

Yes, I think we should mark this as non-standard Chrome behavior then.

2022-08-26 06:28 UTC, Elchi3 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.platform")}} {{experimental_inline}})
```suggestion
The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.platform")}} {{nonstandard_inline}})
```

2022-08-26 06:44 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +The `platform` is the selected platform (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.platform")}} {{experimental_inline}})
Given that `BeforeInstallPromptEvent.userChoice` is not documented and the link (c.f. {{jsxref("BeforeInstallPromptEvent", "BeforeInstallPromptEvent.userChoice")}} is… unusual.

I would like to suggest:
```suggestion
A {{jsxref("Promise")}} resolving to an information object containing:
- `outcome` that
  - :  A string, either `"accepted"` or `"dismissed"`, reflecting the{{jsxref("BeforeInstallPromptEvent.userChoice")}} property {{experimental_inline}}).
-`platform`
  - : A string containing the selected platform, reflecting the {{jsxref("BeforeInstallPromptEvent.platform")}} property {{nonstandard_inline}}).
```

2022-08-26 21:40 UTC, teoli2003 requested changes, later dismissed

2022-08-26 21:40 UTC, teoli2003 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +  A string containing the selected platform, reflecting the {{jsxref("BeforeInstallPromptEvent.platform")}} property.
This is incorrect. We use definition lists in that case here. See our [writing guidelines](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#definition_lists).
```suggestion
- `outcome` {{experimental_inline}}  
  - : A string, either `"accepted"` or `"dismissed"`, reflecting the {{jsxref("BeforeInstallPromptEvent.userChoice")}} property.

- `platform` {{nonstandard_inline}}  
  - : A string containing the selected platform, reflecting the {{jsxref("BeforeInstallPromptEvent.platform")}} property.
```

2022-08-29 10:20 UTC, Elchi3 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +- `outcome` {{experimental_inline}}
Actually, this should be `userChoice` (as the spec defines). The compat table should then talk about the non-standard Chrome name. Joe does this in https://github.com/mdn/browser-compat-data/pull/17541#issuecomment-1228726912

```suggestion
- `userChoice` {{experimental_inline}}  
```

2022-08-29 13:37 UTC, Vogel612 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +- `outcome` {{experimental_inline}}
But then if we document the spec and not the actual behaviour, the `platform` should be omitted.
Maybe a superior alternative then would be to introduce a new page named `BeforeInstallPromptEvent.AppBannerPromptOutcome` and reference to there instead?

This would of course require adjustments in the BCD so the implementation status there could be documented properly...

2022-08-29 13:58 UTC, Elchi3 commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +- `outcome` {{experimental_inline}}
Usually non-standard extensions or alternate names appear on the same MDN page.
I think it would be good to give it some more explanation like we do here for moz-opaque: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#attributes (indicating that there is a non-standard name "outcome" for this but, if possible, to use the standardized name "userChoice" instead.)

For platform, it I think it is fine to leave it there with the indication that it's non-standard.

2022-08-31 14:16 UTC, Elchi3 approved these changes
Thanks for investigating this with us! 👍 
Let's hope that browsers implement the standards one day. Creating docs will be a lot easier then :)

2022-08-31 14:17 UTC, merged