Add properties order in transform info.
mdn/content pull request #19960
Opened 2022-08-25 07:27 UTC by khamer1410

Add info about properties order in transform.

#### Summary

Add info about the importance of the order when using Z translation

#### Motivation

I found that my code is not working and debugg it by reading an external article. I believe this should be in the MDN doxs

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-25 08:46 UTC, teoli2003 requested changes

2022-08-25 08:46 UTC, teoli2003 commented on files/en-us/web/css/transform-function/translatez/index.md
> +Note that `perspecitve` must be placed before `translateZ` - other way around it won't work.
I think this is better:
```suggestion
> **Note:** As the composition of transforms isn't commutative, the order you write the different functions is significant. In particular, in general, you want `perspective()` to be placed before `translateZ()`.
```

2022-09-19 10:38 UTC, khamer1410 commented
Sorry, I missed the notification. Committed suggestion, feel free to edit and merge as You want.

2022-10-03 10:51 UTC, teoli2003 approved these changes
👍

2022-10-03 10:52 UTC, merged

2022-10-03 10:52 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: