CSS Font Loading API fixes - FF104
mdn/content pull request #19990
Opened 2022-08-26 07:32 UTC by hamishwillee

Fixes to CSS Font Loading API following addition of worker support in FF104 (https://bugzilla.mozilla.org/show_bug.cgi?id=1072107).

I think this is all good. But need to test the worker global scope example code.

2022-09-02 07:30 UTC, hamishwillee commented on files/en-us/web/api/fontface/load/index.md
> +document.fonts.add(font_file);
FYI this fixes broken example. This was also reason I did not understand the API.

2022-09-02 10:29 UTC, caugner approved these changes
Partial approval for `GroupData.json`, LGTM.

2022-09-06 08:03 UTC, hamishwillee commented
OK. FYI, the second example in the top level https://pr19990.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CSS_Font_Loading_API does not fully work in FF but does according to Chrome and our docs - raised in 
https://bugzilla.mozilla.org/show_bug.cgi?id=1789367

The top level docs now at least somewhat useful. I plan to do one more iteration through the other docs.

2022-09-06 08:05 UTC, hamishwillee commented on files/en-us/web/api/fontfacesetloadevent/index.md
> +Events are fired when font loading starts ([`loading`](/en-US/docs/Web/API/FontFaceSet/loading_event)), loading completes ([`loadingdone`](/en-US/docs/Web/API/FontFaceSet/loadingdone_event)) or there
@teoli2003 Can you look at the events here and at https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/loading_event - specifcally, how is https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/loading_event supposed to indicate that it is a FontFaceSetLoadEvent ?

2022-09-09 07:03 UTC, hamishwillee commented on files/en-us/web/api/fontfaceset/delete/index.md
> +Font faces that were added to the set using the CSS {{cssxref("@font-face")}} rule remain connected to the corresponding CSS, and cannot be deleted.
There is a technical term in the spec "[CSS connected](https://andreubotella.com/csswg-auto-build/css-font-loading-3/#document-font-face-set)" which essentially means a font created using an `@font-face` creates a matching `FontFace`. That is not available for you to touch with the API and you can't add it etc.

BUT what isn't clear is what "the same" means. I THINK it means a `FontFace` with the same family name. But it might now. SHouldn't block this, as the text is no worse.

2022-09-09 07:38 UTC, teoli2003 requested changes
Mostly nits or applying code guidelines. We should run Prettier on these pages afterwards as some indentation is strange and manually fixing it is too long.

I have a pet peeve: I avoid starting paragraphs with _It is_ or _This is_ as, especially when scanning quickly the page, readers won't have the context for _it_ or _this_.

I still need to answer your question here, and we'll make a quick second pass afterward as there are quite a few files and I may have missed some extra nits.

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +document.fonts.add(font_file);
```suggestion
const fontFile = new FontFace('30px "Inconsolata"', 'url(https://fonts.gstatic.com/s/inconsolata/v31/QlddNThLqRwH-OJ1UHjlKENVzlm-WkL3GZQmAwPyya15.woff2) format("woff2")', {stretch: '50% 200%'});

document.fonts.add(fontFile);
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +
```suggestion
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +
```suggestion
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/canvasrenderingcontext2d/fontstretch/index.md
> +// let font_file = new FontFace('League Spartan', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2) format("woff2")');
```suggestion
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +Font faces are created using the [`FontFace` constructor](/en-US/docs/Web/API/FontFace/FontFace), which takes as arguments: the font family, the font source, and optional descriptors.
```suggestion
Font faces are created using the [`FontFace` constructor](/en-US/docs/Web/API/FontFace/FontFace), which takes as parameters: the font family, the font source, and optional descriptors.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +});
```suggestion
// Define a FontFace
const font = new FontFace('myfont', 'url(myfont.woff)');

// Add to the document.fonts (FontFaceSet)
document.fonts.add(font);

// Load the font
font.load();

// Wait until the fonts are all loaded
document.fonts.ready.then( () => {
  // Use the font to render text (for example, in a canvas) 
});
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +document.fonts.add(font);
```suggestion
// Define a FontFace
const font = new FontFace('myfont', 'url(myfont.woff)', {
  style: 'italic',
  weight: '400',
  stretch: 'condensed'
});

// Add to the document.fonts (FontFaceSet)
document.fonts.add(font);
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +
```suggestion
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +mycanvas.height = 75;
```suggestion
const canvas = document.getElementById("js-canvas");
canvas.width = 650;
canvas.height = 75;
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +let bitterFontFace = new FontFace('FontFamily Bitter', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2)');
```suggestion
const bitterFontFace = new FontFace('FontFamily Bitter', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2)');
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +log.textContent+=`Bitter font: ${bitterFontFace.status}\n`;  // > Bitter status: unloaded
```suggestion
log.textContent += `Bitter font: ${bitterFontFace.status}\n`;  // > Bitter font: unloaded
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +  log.textContent+=`Bitter font: ${bitterFontFace.status}\n`;  // > Bitter status: loaded
```suggestion
  log.textContent += `Bitter font: ${bitterFontFace.status}\n`;  // > Bitter font: loaded
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +  const ctx = mycanvas.getContext('2d')
```suggestion
  const ctx = canvas.getContext('2d')
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +const ctx = mycanvas.getContext('2d')
```suggestion
const canvas = document.getElementById("js-canvas");
canvas.width = 650;
canvas.height = 75;
const ctx = canvas.getContext('2d')
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +let oxygenFontFace = new FontFace('FontFamily Oxygen', 'url(https://fonts.gstatic.com/s/oxygen/v5/qBSyz106i5ud7wkBU-FrPevvDin1pK8aKteLpeZ5c0A.woff2)');
```suggestion
const oxygenFontFace = new FontFace('FontFamily Oxygen', 'url(https://fonts.gstatic.com/s/oxygen/v5/qBSyz106i5ud7wkBU-FrPevvDin1pK8aKteLpeZ5c0A.woff2)');
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +log.textContent+=`Oxygen status: ${oxygenFontFace.status}\n`;
```suggestion
log.textContent += `Oxygen status: ${oxygenFontFace.status}\n`;
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +  log.textContent+=`Bitter font: ${oxygenFontFace.status}\n`;  // > Oxygen font: loaded
```suggestion
  log.textContent += `Bitter font: ${fonts}\n`;  // > Oxygen font: loaded
  log.textContent += `Bitter font: ${oxygenFontFace.status}\n`;  // > Oxygen font: loaded
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +  });
```suggestion
  log.textContent += `loading_event: ${event.fontfaces.length}\n`;
});
document.fonts.addEventListener('loadingerror', (event) => { 
  log.textContent += `loadingerror_event: ${event.fontfaces.length}\n`;
});
document.fonts.addEventListener('loadingdone', (event) => { 
  log.textContent += `loadingdone_event: ${event.fontfaces.length}\n`;
  event.fontfaces.forEach( (value) => {
    log.textContent += `  fontface: ${value.family}\n`;
  });
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +  log.textContent+=(`\nFontFaces in document: ${document.fonts.size}.\n`);
```suggestion
  log.textContent += (`\nFontFaces in document: ${document.fonts.size}.\n`);
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +      log.textContent+=`  ${property}: ${fontFace[property]}\n`;
```suggestion
    log.textContent += 'FontFace:\n';
    for (const property in fontFace) {
      log.textContent += `  ${property}: ${fontFace[property]}\n`;
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +    for (const property in fontFace) {
Why not `for…of` ?

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/document/fonts/index.md
> +This is part of the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API).
```suggestion
This feature is part of the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API).
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/ascentoverride/index.md
> +This is equivalent to the {{cssxref("@font-face/ascent-override")}} descriptor of {{cssxref("@font-face")}}.
```suggestion
This property is equivalent to the {{cssxref("@font-face/ascent-override")}} descriptor of {{cssxref("@font-face")}}.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/ascentoverride/index.md
> +This is the height above the baseline that CSS uses to lay out line boxes in an inline formatting context
```suggestion
The **`ascentOverride`** property of the {{domxref("FontFace")}} interface returns and sets the ascent metric for the font,
the height above the baseline that CSS uses to lay out line boxes in an inline formatting context.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/ascentoverride/index.md
> +This take the same values as the {{cssxref("@font-face/ascent-override")}} descriptor.
This sounds weird. What about:
```suggestion
This property accepts the same values as the {{cssxref("@font-face/ascent-override")}} descriptor.
```

or something similar

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/family/index.md
> +This is equivalent to the {{cssxref("@font-face/font-family", "font-family")}} descriptor of {{cssxref("@font-face")}}.
```suggestion
This property is equivalent to the {{cssxref("@font-face/font-family", "font-family")}} descriptor of {{cssxref("@font-face")}}.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/featuresettings/index.md
> +It is equivalent to the {{cssxref("font-feature-settings")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("font-feature-settings")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/fontface/index.md
> +  - : A descriptor string does not match the grammar of the corresponding {{cssxref("@font-face")}} descriptor, or the specified binary source cannot be loaded.
```suggestion
  - : Thrown when a descriptor string does not match the grammar of the corresponding {{cssxref("@font-face")}} descriptor, or the specified binary source cannot be loaded.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/index.md
> +The interface defines the source of a font face, either a URL to an external resource or a buffer, and font properties such as the style, weight, and so on.
```suggestion
This interface defines the source of a font face, either a URL to an external resource or a buffer, and font properties such as `style`, `weight`, and so on.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/load/index.md
>  let font_file = new FontFace('FontFamily Style Bitter', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2)');
```suggestion
const fontFile = new FontFace('FontFamily Style Bitter', 'url(https://fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2)');
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/load/index.md
> +document.fonts.add(font_file);
```suggestion
document.fonts.add(fontFile);
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/stretch/index.md
> +It is equivalent to the {{cssxref("@font-face/font-stretch", "font-stretch")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("@font-face/font-stretch", "font-stretch")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/style/index.md
> +It is equivalent to the {{cssxref("@font-face/font-style", "font-style")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("@font-face/font-style", "font-style")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/unicoderange/index.md
> +It is equivalent to the {{cssxref("@font-face/unicode-range", "unicode-range")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("@font-face/unicode-range", "unicode-range")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/variationsettings/index.md
> +It is equivalent to the {{cssxref("@font-face/font-variation-settings", "font-variation-settings")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("@font-face/font-variation-settings", "font-variation-settings")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontface/weight/index.md
> +It is equivalent to the {{cssxref("@font-face/font-weight", "font-weight")}} descriptor.
```suggestion

This property is equivalent to the {{cssxref("@font-face/font-weight", "font-weight")}} descriptor.
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/fontfaceset/index.md
> +It is available as {{domxref("Document.fonts")}}, or `self.fonts` in [web workers](/en-US/docs/Web/API/Web_Workers_API).
```suggestion
This property is available as {{domxref("Document.fonts")}}, or `self.fonts` in [web workers](/en-US/docs/Web/API/Web_Workers_API).
```

2022-09-09 07:38 UTC, teoli2003 commented on files/en-us/web/api/workerglobalscope/fonts/index.md
> +This is part of the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API).
```suggestion
This property is part of the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API).
```

2022-09-09 09:35 UTC, teoli2003 commented on files/jsondata/GroupData.json
> +        "WorkerGlobalScope.fonts"],
```suggestion
        "WorkerGlobalScope.fonts"
      ],
```

2022-09-12 00:52 UTC, hamishwillee commented on files/en-us/web/api/fontface/ascentoverride/index.md
> +This take the same values as the {{cssxref("@font-face/ascent-override")}} descriptor.
FWIW this should have been "This **takes** the same values" which is fine. I like your working more though.

2022-09-12 00:56 UTC, hamishwillee commented on files/en-us/web/api/fontface/fontface/index.md
> +    - [`ascentOverride`](/en-US/docs/Web/API/FontFace/ascentOverride)
@teoli2003 Note that this is a constructor doc so normally you wouldn't link the parameters to the properties of the parent as I have done here.

But in this case the properties are set in _exactly_ the same way as the constructor - i.e. you can set using the constructor or get/set using the properties. So IMO this is a useful thing to do - it is more useful than just pointing to the `@font-face` as we have done in the dt.

2022-09-12 00:57 UTC, hamishwillee commented on files/en-us/web/api/fontface/load/index.md
>  font_file.load().then(() => {
```suggestion
fontFile.load().then(() => {
```

2022-09-12 01:25 UTC, hamishwillee commented on files/en-us/web/api/css_font_loading_api/index.md
> +    for (const property in fontFace) {
Because I want to list both the key and value in the next line. `For in` gives me the key, from which I can get the value, whereas `for-of` would just give me the values.
Of course my understanding of JavaScript is limited so maybe this is not the right way.

2022-09-12 02:02 UTC, hamishwillee commented
Thanks for your review @teoli2003 . I've run prettier/markdownlint and fixed a few more nits. I think good to go now.

2022-09-12 07:27 UTC, teoli2003 requested changes

2022-09-12 07:29 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +});
The idea is to avoid `for...in` as much as possible with collections (that is, not objects). (There is no preference between `for...of` and `forEach()` when both are available and suitable)

2022-09-13 02:22 UTC, hamishwillee commented on files/en-us/web/api/fontface/fontface/index.md
> +  document.body.classList.add("fonts-loaded");
@teoli2003 There were other examples where the person clearly didn't understand that you MUST `add()` the font before it can be used.

That cost me a lot of time because I assumed there were cases where the `add` was optional.  So spelling it out here is not a bad thing.

I'm going to leave this one but I won't close the comment. If you feel strongly feel free to commit it yourself.

2022-09-13 02:34 UTC, hamishwillee commented on files/en-us/web/api/css_font_loading_api/index.md
> +});
Ah, but fontFace is an object - not a collection. If you try that code it tells you the method `forEach()` is not present.  I think this is OK.

2022-09-13 05:08 UTC, teoli2003 commented on files/en-us/web/api/css_font_loading_api/index.md
> +});
My bad, I mixed `FontFaceSet` that is the type of `document.fonts.values()` and the type of `fontFace`.

Sorry.

2022-09-13 05:16 UTC, teoli2003 approved these changes
I've run prettier on GroupData.json to make the test happy (it will soon be automatic)

2022-09-13 07:21 UTC, hamishwillee commented
@teoli2003 Thanks very much - really appreciate all the help and fixes!

2022-09-13 07:21 UTC, merged