Compare `Accept-Post` header with `Accept`
mdn/content pull request #20007
Opened 2022-08-26 18:04 UTC by slavcodev

#### Summary

This seems to be a typo, but in any case it may be more clear, since both headers works with media types.

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2022-08-26 18:12 UTC, teoli2003 requested changes

2022-08-26 18:12 UTC, teoli2003 commented on files/en-us/web/http/headers/accept-post/index.md
> +> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}}, except that it has no notion of preference (i.e. "accept-params" or "q" arguments are not sig
In fact both work. But there is an underlying reason for not accepting `q` arguments: `Accept-Post` is a response header, while the two others are request headers. Let's be even more precise:

```suggestion
> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}} or {{HTTPHeader("Accept-Language")}}, except that it has no notion of preference (i.e., no `q` arguments). This is because `Accept-Post` is a response header while the others are request headers.
```

What do you think?

2022-08-26 18:44 UTC, slavcodev commented on files/en-us/web/http/headers/accept-post/index.md
> +> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}}, except that it has no notion of preference (i.e. "accept-params" or "q" arguments are not sig
The English is not my primary language, and it's hard to say. however, I feel like `Accept-Language` does not make sense because earlier in the text is used "specifies a **media** range`"

2022-08-26 18:48 UTC, teoli2003 requested changes

2022-08-26 18:48 UTC, teoli2003 commented on files/en-us/web/http/headers/accept-post/index.md
> +> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}}, except that it has no notion of preference (i.e. "accept-params" or "q" arguments are not sig
You are right. I missed this!

```suggestion
> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}}, except that it has no notion of preference (i.e., no `q` arguments). This is because `Accept-Post` is a response header while `Accept` is a request header.
```

2022-08-26 23:02 UTC, teoli2003 approved these changes
👍

2022-08-26 23:03 UTC, merged

2022-09-06 11:59 UTC, Asif7777-ship commented on files/en-us/web/http/headers/accept-post/index.md
> -> **Note:** The `Accept-Post` header specifies a media range in the same way as {{HTTPHeader("Accept")}}, except that it has no notion of preference (i.e. "accept-params" or "q" arguments are not sig
@Asif7777