Add `inset` to the positioned layout properties
mdn/content pull request #20008
Opened 2022-08-26 20:07 UTC by sevignator

#### Summary

The `inset` CSS property is missing from the list on this page. It's a relatively new shorthand property for `top`, `right`, `bottom` and `left`.

#### Motivation

This property isn't all that well-known given that it's fairly new. But it's incredibly useful when styling pseudo-elements, plus it is unique to Positioned layouts.

#### Supporting details

https://developer.mozilla.org/en-US/docs/Web/CSS/inset

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-26 21:48 UTC, teoli2003 requested changes

2022-08-26 21:48 UTC, teoli2003 commented on files/en-us/web/css/css_positioning/index.md
> +- {{cssxref("inset")}}
There are a few more. Let's add them:
```suggestion
- {{cssxref("inset")}}, and the related shorthand property, {{cssxref("inset-inline")}} and its associated longhand properties, {{cssxref("inset-inline-start")}} and {{cssxref("inset-inline-end")}}, as well as the shorthand {{cssxref("inset-block")}} and its associated longhand properties, {{cssxref("inset-block-start")}} and {{cssxref("inset-block-end")}}
```

2022-08-26 23:22 UTC, sevignator commented on files/en-us/web/css/css_positioning/index.md
> +- {{cssxref("inset")}}
Excellent suggestion, thanks! I added them to the list as simple bullet points (the relationship between them should be obvious enough by their name alone).

2022-08-27 19:41 UTC, teoli2003 approved these changes

2022-08-27 19:41 UTC, merged