Rework event bubbling and capture
mdn/content pull request #20013
Opened 2022-08-26 22:30 UTC by wbamberg

Fixes https://github.com/mdn/content/issues/13749.

This attempts to clarify the description of event bubbling and capture, especially to make it clearer that capture is the non-default option.

2022-08-26 23:01 UTC, teoli2003 requested changes, later dismissed
Really happy to see this article fixed (I'll need a second to double check, but I think this is mostly good.

2022-08-26 23:01 UTC, teoli2003 commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +Why bother with both capturing and bubbling? Well, in the bad old days when browsers were much less cross-compatible than they are now, Netscape only used event capturing, and Internet Explorer used
```suggestion
Why bother with both capturing and bubbling? In the bad old days, when browsers were much less cross-compatible than now, Netscape only used event capturing, and Internet Explorer used only event bubbling. When the W3C decided to try to standardize the behavior and reach a consensus, they ended up with this system that included both, which is what modern browsers implement.
```

2022-08-26 23:26 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> -    <source src="https://raw.githubusercontent.com/mdn/learning-area/master/javascript/building-blocks/events/rabbit320.mp4" type="video/mp4">
> Why removing this line?

Just to keep the example code as simple as possible.

> Also is the url correct? Isn't it possible to have only `rabbit320.mp4` (or `.webm`) like the link two lines below?

Unfortunately not: https://github.com/mdn/yari/issues/5727

2022-08-26 23:33 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +The standard [`Event`](/en-US/docs/Web/API/Event) object has a function available on it called [`stopPropagation()`](/en-US/docs/Web/API/Event/stopPropagation) which, when invoked on a handler's even
I don't think "Still" is right here: it implies that the primary point of `stopPropagation` would be the first part, and the part after "Still" is secondary, which is backwards. I guess you want to split this sentence?

```suggestion
The [`Event`](/en-US/docs/Web/API/Event) object has a function available on it called [`stopPropagation()`](/en-US/docs/Web/API/Event/stopPropagation) which, when called inside an event handler, prevents the event from bubbling up to any other elements.
```

2022-08-26 23:34 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +In this case, the order of messages is reversed: the `<body>` event handler fires first, followed by the `<div>` event handler, followed by the `<button>` event handler:
I don't think this change is an improvement. "fires first, and next by" doesn't make sense.

2022-08-26 23:38 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +This is because the video is inside the `<div>` — it is part of it — so clicking the video actually runs _both_ the event handlers.
I think "both the event handlers" is fine, but either of the other two are fine as well. Of the two I prefer "both event handlers".

2022-08-26 23:40 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +This is because the video is inside the `<div>` — it is part of it — so clicking the video actually runs _both_ the event handlers.
```suggestion
The video is inside the `<div>` — it is part of it — so clicking the video runs _both_ the event handlers, causing this behavior.
```

...I think would be better, otherwise "running the event handlers" and "causing the behavior" could be two separate things.

2022-08-26 23:41 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +This can be a very annoying behavior, but there is a way to prevent it!
```suggestion
As we saw in the last section, event bubbling can sometimes create problems, but there is a way to prevent it.
```

?

2022-11-15 10:19 UTC, Elchi3 approved these changes
Thank you, Will! 👍

2022-11-15 10:20 UTC, merged

2022-11-15 15:09 UTC, wbamberg commented
Thank you for fixing this up and dragging it over the line!