fix: MD037 space in emphasis
mdn/content pull request #20024
Opened 2022-08-27 04:37 UTC by nschonni

There are a bunch of asterisks inside HTML elements that trip up this rule, so it can be fully turned on right now

2022-08-27 07:33 UTC, teoli2003 requested changes

2022-08-27 07:33 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
How does Yari's Markdown-2-HTML converter work with these, and not Markdownlint?

2022-08-27 07:33 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +HTML's `<input type="number">` implicitly has the `role` of `spinbutton`. HTML's `<input type="date">` has 3 nested spin buttons, one each for month, day, and year. When using semantic HTML form elem
Same here

2022-08-27 07:33 UTC, teoli2003 commented on files/en-us/web/html/element/iframe/index.md
> +Each embedded browsing context has its own [session history](/en-US/docs/Web/API/History) and [document](/en-US/docs/Web/API/Document). The browsing context that embeds the others is called the *pare
We don't want to use `*` for italics or `__` for bold.

```suggestion
Each embedded browsing context has its own [session history](/en-US/docs/Web/API/History) and [document](/en-US/docs/Web/API/Document). The browsing context embedding the others is called the **parent browsing context**. The **topmost browsing context** — the one with no parent — is usually the browser window, represented by the {{domxref("Window")}} object.
```

2022-08-27 07:36 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
I'm not convinced we should explain to every author such tricks to avoid extremely rare errors.

For the moment, I'm not convinced we should turn MD037 on.

2022-08-27 17:49 UTC, nschonni commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
This one isn't turning on the rule, as mentioned in the description, there are issues in the stuff in the HTML tables and DIV license blocks

2022-08-27 17:50 UTC, nschonni commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
I've now escaped the second one too, but before there was an emphasis like section between the 2 `aria-*`. Alternately, they could just be wrapped in a code tag

2022-08-27 17:51 UTC, nschonni commented on files/en-us/web/html/element/iframe/index.md
> +Each embedded browsing context has its own [session history](/en-US/docs/Web/API/History) and [document](/en-US/docs/Web/API/Document). The browsing context that embeds the others is called the *pare
These were emphasis sections, but are now bold. Is that intended?

2022-08-29 05:51 UTC, teoli2003 commented on files/en-us/web/html/element/iframe/index.md
> +Each embedded browsing context has its own [session history](/en-US/docs/Web/API/History) and [document](/en-US/docs/Web/API/Document). The browsing context that embeds the others is called the *pare
```suggestion
Each embedded browsing context has its own [session history](/en-US/docs/Web/API/History) and [document](/en-US/docs/Web/API/Document). The browsing context that embeds the others is called the _parent browsing context_. The _topmost_ browsing context — the one with no parent — is usually the browser window, represented by the {{domxref("Window")}} object.
```

2022-08-29 05:52 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
I think we should wrap them in a code tag; they are code.

2022-08-29 05:52 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +HTML's `<input type="number">` implicitly has the `role` of `spinbutton`. HTML's `<input type="date">` has 3 nested spin buttons, one each for month, day, and year. When using semantic HTML form elem
Code tag.

2022-08-29 06:07 UTC, nschonni commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwis
```suggestion
HTML's `<input type="range">` implicitly has the `role` of `slider`. Do not use `aria-valuemax` or `aria-valuemin` attributes on `<input type="range">` elements; use `min` and `max` instead. Otherwise, any global `aria-*` attributes and any other `aria-*` attributes applicable to the slider role.
```

2022-08-29 06:07 UTC, nschonni commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +HTML's `<input type="number">` implicitly has the `role` of `spinbutton`. HTML's `<input type="date">` has 3 nested spin buttons, one each for month, day, and year. When using semantic HTML form elem
```suggestion
HTML's `<input type="number">` implicitly has the `role` of `spinbutton`. HTML's `<input type="date">` has 3 nested spin buttons, one each for month, day, and year. When using semantic HTML form elements for their intended purposes, do not use `aria-valuemax` or `aria-valuemin` attributes; use `min` and `max` instead. Otherwise, any global `aria-*` attributes and any other `aria-*` attributes are applicable to the `spinbutton` role.
```

2022-08-29 06:13 UTC, teoli2003 approved these changes
Thank you!

2022-08-29 06:13 UTC, merged