Max-Forward Header Added
mdn/content pull request #20028
Opened 2022-08-27 05:46 UTC by bhaveshraj336

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-27 09:52 UTC, teoli2003 requested changes

2022-08-27 09:52 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +The **`Max-Forwards`** request HTTP header is used only with the TRACE method,to limit the number of proxies that request goes through.A Integer Value is given to these Header.If a TRACE Request is r
```suggestion
The **`Max-Forwards`** request HTTP header is used with the [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method to limit the number of nodes (usually proxies) that request goes through. Its value is an integer value indicating the _maximum amount_ of nodes it must visit. At each node, the value is decremented and the `TRACE` request is forwarded to the next node, until the destination is reached, or the received value of `Max-Forwards` is zero. The request is then forwarded back, except for some headers, as the body of a `200 OK` response.

If the `Max-Forwards` header is not present in a `TRACE` request, a node will assume that there is no maximum number of forwards.
```

2022-08-27 09:52 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +Max-Forwards: <Integer-Value>
```suggestion
Max-Forwards: <integer>

```

2022-08-27 09:52 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +
```suggestion
```

2022-08-27 09:52 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +
```suggestion
```

2022-08-27 09:52 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +- Other similar headers: {{HTTPHeader("TE")}}, {{HTTPHeader("Accept-Encoding")}}, {{HTTPHeader("Accept-Language")}}
```suggestion
- The HTTP [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method
```

2022-08-27 19:28 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +The **`Max-Forwards`** request HTTP header is used with the [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method to limit the number of nodes (usually proxies) that request goes through. Its value is
```suggestion
The **`Max-Forwards`** request HTTP header is used with the [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method to limit the number of nodes (usually proxies) that request goes through. Its value is an integer value indicating the _maximum amount_ of nodes it must visit. At each node, the value is decremented and the `TRACE` request is forwarded to the next node, until the destination is reached, or the received value of `Max-Forwards` is zero. The request is then sent back, except for some headers, as the body of a `200 OK` response.

```

2022-08-27 19:29 UTC, teoli2003 approved these changes

2022-08-27 19:32 UTC, teoli2003 requested changes
The name of the file is wrong, it is missing a _s_: it is _max-forwards_.

2022-08-27 19:32 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +slug: Web/HTTP/Headers/Accept
```suggestion
slug: Web/HTTP/Headers/Max-Forwards
```

2022-08-27 19:32 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +browser-compat: http.headers.Accept
```suggestion
browser-compat: http.headers.Max-Forwards
```

2022-08-27 19:33 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +
```suggestion

```

2022-08-27 19:33 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +
```suggestion
```

2022-08-27 19:33 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forward/index.md
> +- The HTTP [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method
```suggestion
- The HTTP [`TRACE`](/en-US/docs/Web/HTTP/Methods/TRACE) method

```

2022-08-28 05:41 UTC, bhaveshraj336 commented
@teoli2003 can you plz let me know how can I change the name without creating a new pull request?

2022-08-28 05:56 UTC, teoli2003 commented
It is easy. See: https://docs.github.com/en/repositories/working-with-files/managing-files/moving-a-file-to-a-new-location

2022-08-28 06:00 UTC, bhaveshraj336 commented
@teoli2003 Thanks 
I have done the changes ?

2022-08-28 06:02 UTC, bhaveshraj336 commented
@teoli2003 so could you merge now?

2022-08-28 06:04 UTC, teoli2003 approved these changes

2022-08-28 06:04 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forwards/index.md
> +```
```suggestion
```

```

2022-08-28 06:07 UTC, merged

2022-08-28 06:07 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada:

2022-08-28 06:08 UTC, bhaveshraj336 commented
@teoli2003  BTW why its not updated on the site?

2022-08-28 06:08 UTC, bhaveshraj336 commented
@teoli2003  Thank you for helping me out .

2022-08-28 06:12 UTC, bhaveshraj336 commented
@teoli2003  will i also need to update the main headers page?

2022-08-28 06:13 UTC, teoli2003 commented
Yes, please, this would be helpful!

2022-08-28 06:14 UTC, teoli2003 commented
> @teoli2003 BTW why its not updated on the site?

The site is regenerated about once a day, so it will be easier today (we are Sunday, I don't know if it will), or tomorrow night.

2022-08-28 06:15 UTC, bhaveshraj336 commented
> > @teoli2003 BTW why its not updated on the site?
> 
> The site is regenerated about once a day, so it will be easier today (we are Sunday, I don't know if it will), or tomorrow night.
and what's the BCD flaw?

2022-08-28 06:18 UTC, teoli2003 commented
> > > @teoli2003 BTW why its not updated on the site?
> > 
> > 
> > The site is regenerated about once a day, so it will be easier today (we are Sunday, I don't know if it will), or tomorrow night.
> > and what's the BCD flaw?

We don't have the BCD information at mdn/browser-compat-data about Max-Forwards. I will probably create a follow-up PR to fix it, but I didn't want to hold this PR.

2022-08-28 06:20 UTC, bhaveshraj336 commented
Oh Thats Great
Thanks again 😄