fix: MD042 no empty links
mdn/content pull request #20026
Opened 2022-08-27 04:44 UTC by nschonni

Some of the macro values come up as empty links to markdown parsers, so attempt to escape a bracket.

2022-08-27 04:51 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/regexp/@@split/index.md
> +- {{jsxref("RegExp.prototype.@@match()", "RegExp.prototype[@@match]\()")}}}
That looks quite weird. I don't really want to think about this into the future. (Never really occurred to me that it's ambiguous with a link, although makes a lot of sense)

2022-08-27 07:04 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/@@split/index.md
> +- {{jsxref("RegExp.prototype.@@match()", "RegExp.prototype[@@match]\()")}}}
I think we should ditch the macro in these cases. I will surely forget about the `\` the next time I read these links.

2022-08-27 07:09 UTC, teoli2003 requested changes

2022-08-27 07:09 UTC, teoli2003 commented on files/en-us/mdn/community/pull_requests/index.md
> +- Read the contributor documentation and how to write documentation first to try to answer the question yourself before filing a pr.
@schalkneethling  This should link to some real place, isn't it?

2022-08-27 07:09 UTC, teoli2003 commented on files/en-us/web/accessibility/aria/roles/progressbar_role/index.md
> +Authors **may** set aria-valuemin and aria-valuemax to indicate the minimum and maximum progress indicator values. Otherwise, their implicit values follow the same rules as HTML's `<input type="range
```suggestion
Authors _may_ set `aria-valuemin` and `aria-valuemax` to indicate the minimum and maximum progress indicator values. Otherwise, their implicit values follow the same rules as HTML's [`<input type="range">`](/en-US/docs/Web/HTML/Element/input/range):
```

2022-08-27 07:09 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_reference_page_template/index.md
> +- [`eventname1`](#\)
I don't understand why Markdownlint is not happy with this.

2022-08-27 07:11 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/49/index.md
> +- The ES2015 {{jsxref("RegExp.prototype.@@match()", "RegExp.prototype[@@match]\()")}}, {{jsxref("RegExp.prototype.@@replace()", "RegExp.prototype[@@replace]\()")}}, {{jsxref("RegExp.prototype.@@searc
```suggestion
- The ES2015 {{jsxref("RegExp.prototype.@@match()", "RegExp.prototype[@@match]\()")}}, {{jsxref("RegExp.prototype.@@replace()", "RegExp.prototype[@@replace]\()")}}, {{jsxref("RegExp.prototype.@@search()", "RegExp.prototype[@@search]\()")}}, and {{jsxref("RegExp.prototype.@@split()", "RegExp.prototype[@@split]\()")}} methods, and {{jsxref("RegExp.@@species", "RegExp[@@species]")}} getter have been implemented ({{bug(887016)}}).
```

2022-08-27 08:18 UTC, nschonni commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_reference_page_template/index.md
> +- [`eventname1`](#\)
A link that is just an anchor without an ID is still and empty link

2022-08-27 08:19 UTC, nschonni commented on files/en-us/mozilla/firefox/releases/49/index.md
> +- The ES2015 {{jsxref("RegExp.prototype.@@match()", "RegExp.prototype[@@match]\()")}}, {{jsxref("RegExp.prototype.@@replace()", "RegExp.prototype[@@replace]\()")}}, {{jsxref("RegExp.prototype.@@searc
Looks like my replace was bad, so I've flipped this back to draft

2022-08-29 19:36 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/49/index.md
> +<!-- markdownlint-disable MD042 -->
IMO disable comments should be used very, very sparsely. Here we can convert them to actual Markdown links instead.

2022-08-29 19:36 UTC, nschonni commented
@teoli2003 in the end, it seems like Yari didn't like the escaping, so I used disable directives instead

2022-08-29 19:50 UTC, nschonni commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_reference_page_template/index.md
> +- [`eventname1`](#\)
Instead of escaping, I swapped to using the `#eventname1` for the placeholder

2022-08-30 06:33 UTC, teoli2003 commented on files/en-us/mdn/community/pull_requests/index.md
> +- Read the contributor documentation and how to write documentation first to try to answer the question yourself before filing a pr.
cc/ @dipikabh that can help us here too.

2022-08-30 06:34 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/49/index.md
> +<!-- markdownlint-disable MD042 -->
Agreed, we should avoid using `{{jsxref}}` in these cases.

2022-08-30 06:35 UTC, teoli2003 commented on files/en-us/web/api/webgl2renderingcontext/drawbuffers/index.md
> +- {{domxref("WebGL2RenderingContext.clearBuffer", "WebGL2RenderingContext.clearBuffer[fiuv]()")}}
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 requested changes
We shouldn't need a magic comment anywhere in this PR. Avoid the `{{domxref}}` or `{{jsxref}}`macro instead.

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/api/webgl2renderingcontext/index.md
>  - {{domxref("WebGL2RenderingContext.uniform()", "WebGL2RenderingContext.uniform[1234][uif][v]()")}}
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/api/webglrenderingcontext/getuniformlocation/index.md
>  - {{domxref("WebGLRenderingContext.getUniform", "getUniform()")}}
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/api/webglrenderingcontext/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/api/webglrenderingcontext/uniform/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/api/webglrenderingcontext/vertexattribpointer/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/bigint64array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/biguint64array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/float32array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/float64array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/int16array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/int32array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/int8array/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/map/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/@@match/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/@@replace/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/@@search/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/@@split/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/regexp/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/set/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/string/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/iterator/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/match/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/matchall/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/replace/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/search/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/split/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/symbol/toprimitive/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:39 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/typedarray/entries/index.md
> +<!-- markdownlint-disable MD042 -->
Avoid using the magic comment, and replace `{{domxref}}`

2022-08-30 06:47 UTC, nschonni commented
I'm not going to go back and de-macro all these files. Someone can cherry pick the other fixes if they're interested

2022-08-30 06:47 UTC, closed without merging