Add committer to interfacedata-updater workflow
mdn/content pull request #20022
Opened 2022-08-27 04:10 UTC by teoli2003

This PR attempts to fix the apparently random committer used when the scripts/update-interface-data via interface-updater github workflow runs.

It adds a _committer_ name.

See https://github.com/mdn/content/pull/20014#issuecomment-1229085180 for the report of the oddity.

2022-08-29 12:53 UTC, caugner requested changes

2022-08-29 12:53 UTC, caugner commented on .github/workflows/interfacedata-updater.yml
> +        committer: mdn-content-bot <noreply@developer.mozilla.org>
The committer is already `GitHub <noreply@github.com>`, but the `author` isn't. So let's set the author to the same value as the committer:

```suggestion
        author: GitHub <noreply@github.com>
```

See:

```
commit 851c97e9efce9636f466b8aa9d2bbc04c4ea21bc (HEAD -> interfacedata-update, upstream/interfacedata-update)
Author: Josh-Cena <Josh-Cena@users.noreply.github.com>
Commit: GitHub <noreply@github.com>

    Update InterfaceData based on WebRef
```

2022-08-29 13:00 UTC, caugner approved these changes

2022-08-30 12:33 UTC, teoli2003 commented
Let's land this.

2022-08-30 12:33 UTC, merged

2022-09-04 01:21 UTC, yin1999 commented
Hey all, maybe using `github-actions[bot] github-actions[bot]@users.noreply.github.com` is a better option. For the committer will be different from the PR's creator while we are using `GitHub <noreply@github.com>` (see: 35b42668da5a200496a7f2214f6729fab392367e).