fix: MD049 consistent emphasis style
mdn/content pull request #20103
Opened 2022-08-29 22:51 UTC by nschonni

Second batch of asterisks to underscore for emphasis style. There is some edge cases with this style sometimes when you're trying to do emphasis inside a word

2022-08-29 23:13 UTC, wbamberg requested changes
Looks great. I suggested a couple of grammar fixes (for errors that you did not introduce, but that are in lines you touched).

2022-08-29 23:13 UTC, wbamberg commented on files/en-us/web/svg/attribute/begin/index.md
> +_This example is embed in an iFrame. If you want to activate the key events, you have to click on it first._
```suggestion
_This example is embedded in an iFrame. If you want to activate the key events, you have to click on it first._
```

2022-08-29 23:13 UTC, wbamberg commented on files/en-us/web/svg/attribute/end/index.md
> +_This example is embed in an iFrame. If you want to activate the key events, you have to click on it first._
```suggestion
_This example is embedded in an iFrame. If you want to activate the key events, you have to click on it first._
```

2022-08-29 23:52 UTC, nschonni commented on files/en-us/web/svg/attribute/begin/index.md
> +_This example is embed in an iFrame. If you want to activate the key events, you have to click on it first._
```suggestion
_This example is embedded in an iFrame. If you want to activate the key events, you have to click on it first._
```

2022-08-30 00:44 UTC, wbamberg approved these changes
👍 nice!

2022-08-30 00:44 UTC, merged