fix: MD024 Multiple headings with same content
mdn/content pull request #20118
Opened 2022-08-30 06:01 UTC by nschonni

Took a pass with tightening it up to allow only non-sibling duplicate headings

2022-08-30 06:32 UTC, teoli2003 requested changes
I'm happy to see this one coming to life!

A few changes here or there, but this is close to being merged! 

Thank you!

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/api/element/outerhtml/index.md
>  Getting the value of an element's `outerHTML` property:
I would add an `###` here (and for the other examples) and keep HTML and CSS as `####`.

That way, the different examples are labeled with `###`

This is what we did elsewhere.

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/api/gamepad/axes/index.md
> +An array of {{domxref("double") }} values.
Number is the primitive type.

```suggestion
An array of numbers.
```

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/api/gamepad/id/index.md
> +A {{jsxref("String")}}.
It isn't a `String` (the object wrapper), it really is a primitive string.

```suggestion
A string primitive.
```

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> -
Why removing this one?

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/api/serviceworkerglobalscope/fetch_event/index.md
```suggestion
```

2022-08-30 06:32 UTC, teoli2003 commented on files/en-us/web/css/css_container_queries/index.md
> +### `container-type` property
No markdown/HTML in a heading. (Side change)

```suggestion
### The container-type property
```

2022-08-30 16:19 UTC, caugner commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> -
Also, `### Potential risks` seemed to have been a subsection of this.

2022-08-30 16:20 UTC, caugner commented on files/en-us/web/css/css_container_queries/index.md
> +### `container-type` property
Wonder if markdownlint has a rule for this?

2022-08-30 16:21 UTC, caugner approved these changes
Config change LGTM

2022-08-30 16:24 UTC, nschonni commented on files/en-us/web/css/css_container_queries/index.md
> +### `container-type` property
@teoli2003 there are others in the file that use code fences as well, which is why this is a duplicate. Is this something new from the contributing guide?

2022-08-30 16:28 UTC, nschonni commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> -
There is a detailed section at https://github.com/mdn/content/pull/20118/files#diff-2601f01715acc290cff3cec28a3e85a81dbef5a6e226a2989e14e53726808601R317
It's possible that both are required, but then the heading levels need to be fixed, as there are currently 2 H2 Security headings

2022-09-03 06:22 UTC, teoli2003 commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> -
Agreed. This one makes sense, then.

2022-09-03 06:23 UTC, teoli2003 requested changes
There is still a comment about `element.outerHTML` to fix.

2022-09-05 05:14 UTC, teoli2003 approved these changes
👍

2022-09-05 05:14 UTC, merged