Mention Weak data structures in memory management
mdn/content pull request #20147
Opened 2022-08-31 03:31 UTC by Josh-Cena

#### Summary

#### Motivation

We don't document these APIs in the guide, while they can be.

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2022-08-31 07:23 UTC, teoli2003 requested changes

2022-08-31 07:23 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +JavaScript engines typically offer flags that expose the memory model. For example, Node.js offers additional options and tools that expose the underlying V8 mechanisms for configuring and debugging
```suggestion
JavaScript engines typically offer flags that expose the memory model. For example, Node.js offers additional options and tools that expose the underlying V8 mechanisms for configuring and debugging memory issues. This configuration may not be available in browsers and even less on web pages.
```

2022-08-31 07:23 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +[`WeakMap`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) and [`WeakSet`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet) are data structures whose APIs closely mirror the
We need to define what _weak_ means (or to link to a definition)

2022-08-31 07:23 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +One important characteristic of `WeakMap` and `WeakSet` is that they are not iterable. This is because the keys aren't actual references, but [ephemerons](https://www.jucs.org/jucs_14_21/eliminating_
The link is very interesting, but the definition of ephemerons is kind of buried in it. Let's add a glossary entry, maybe combined or included inside one about "weak"?

2022-08-31 07:23 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +- [Kangax article on how to register event handler and avoid memory leaks (2010)](<https://docs.microsoft.com/en-us/previous-versions/msdn10/ff728624(v=msdn.10)>)
I think this article is outdated: we are pushing devs away from doing old IE stuff, so maybe we should look at another link speaking about avoiding memory leaks with JavaScript.

2022-08-31 12:20 UTC, Josh-Cena commented on files/en-us/web/javascript/memory_management/index.md
> +JavaScript engines typically offer flags that expose the memory model. For example, Node.js offers additional options and tools that expose the underlying V8 mechanisms for configuring and debugging
By "web pages", do you mean JavaScript programmatic API? Because it sounds the same as "browser" to me.

2022-09-01 07:28 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +JavaScript engines typically offer flags that expose the memory model. For example, Node.js offers additional options and tools that expose the underlying V8 mechanisms for configuring and debugging
By browsers I understand: a browser choose a memory model (for use on all pages, _maybe as a config value_), by web pages, I mean "A web page (not the browser) can choose the memory model.

2022-09-01 14:26 UTC, Josh-Cena commented on files/en-us/web/javascript/memory_management/index.md
> +- [Kangax article on how to register event handler and avoid memory leaks (2010)](<https://docs.microsoft.com/en-us/previous-versions/msdn10/ff728624(v=msdn.10)>)
I don't know any good sources on this. I'm inclined to remove this section since all necessary links are already present in the main body.

2022-09-01 14:56 UTC, Josh-Cena commented on files/en-us/web/javascript/memory_management/index.md
> +One important characteristic of `WeakMap` and `WeakSet` is that they are not iterable. This is because the keys aren't actual references, but [ephemerons](https://www.jucs.org/jucs_14_21/eliminating_
I'm reluctant to add a glossary entry because it's quite hard to define properly and probably won't be interesting to web developers. I'll add the explanation on this page.

2022-09-04 07:07 UTC, teoli2003 approved these changes

2022-09-04 07:07 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +Currently, all modern engines ship a mark-and-sweep garbage-collector. All improvements made in the field of JavaScript garbage collection (generational/incremental/concurrent/parallel garbage collec
```suggestion
Currently, all modern engines ship a mark-and-sweep garbage collector. All improvements made in the field of JavaScript garbage collection (generational/incremental/concurrent/parallel garbage collection) over the last few years are implementation improvements of this algorithm, but not improvements over the garbage collection algorithm itself nor its reduction of the definition of when "an object is no longer needed".
```

2022-09-04 07:07 UTC, teoli2003 commented on files/en-us/web/javascript/memory_management/index.md
> +`WeakMap` and `WeakSet` got the name from the concept of _weakly held_ values. If `x` is weakly held by `y`, it means that although you can access the value of `x` via `y`, the mark-and-sweep algorit
```suggestion
`WeakMap` and `WeakSet` got the name from the concept of _weakly held_ values. If `x` is weakly held by `y`, it means that although you can access the value of `x` via `y`, the mark-and-sweep algorithm won't consider `x` as reachable if nothing else _strongly holds_ to it. Most data structures, except the ones discussed here, strongly holds to the objects passed in so that you can retrieve them at any time. The keys of `WeakMap` and `WeakSet` can be garbage-collected (for `WeakMap` objects, the values would then be eligible for garbage collection as well) as long as nothing else in the program is referencing the key. This is ensured by two characteristics:
```

2022-09-04 07:10 UTC, merged