Update PULL_REQUEST_TEMPLATE
mdn/content pull request #20249
Opened 2022-09-02 14:48 UTC by bsmth

__Description:__
This PR removes the checklist items which are rendered as tasks in new pull requests on GitHub.

I've also made some minor rewording and tried to simplify the instructions for authors. Happy to take some feedback on that.

2022-09-02 15:58 UTC, Rumyra requested changes

2022-09-02 15:58 UTC, Rumyra commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
```suggestion
### Related issues or other prs

<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
<!-- 🔨 If there are related pull requests, use "Related #123" -->
<!-- 🔨 If this depends on another pull request, use "Depends on #123" -->
```

2022-09-02 15:58 UTC, Rumyra commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Related/depends on prs might need a different section, but I didn't want to 'over' section

2022-09-02 17:16 UTC, bsmth commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Good idea, I've added that with minor rewording in https://github.com/mdn/content/pull/20249/commits/eae2994a502778a6178d773eae2ff615f322cd77

2022-09-02 17:31 UTC, Josh-Cena commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Mention that if it's part of a big project, don't use "fixes"?

2022-09-02 18:54 UTC, bsmth commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
What does big project mean in this context? A parent task for multiple isolated PRs?

2022-09-02 18:56 UTC, Josh-Cena commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Yeah, for example, updating `alt`, getting rid of `var`, etc. I'm a bit ambivalent on this, because it's not _that_ common, but it happens anyway.

2022-09-02 19:02 UTC, bsmth commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Oh I see, if it contributes some work towards an issue, it wouldn't be fully fixed/closed, that's true.

We could clarify "if it fully resolves a GitHub issue" or similar.

2022-09-02 19:06 UTC, Josh-Cena commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
Yeah, sounds good.

2022-09-02 19:09 UTC, bsmth commented on .github/PULL_REQUEST_TEMPLATE
> +<!-- 🔨 If this closes a GitHub issue, use "Fixes #123" -->
done in https://github.com/mdn/content/pull/20249/commits/ae2d5dccdc4f096167e360558c0be640dcbb8e23 ✅

2022-09-05 09:22 UTC, Rumyra approved these changes

2022-09-05 09:22 UTC, merged