style: convert HTML tables
mdn/content pull request #20258
Opened 2022-09-02 20:14 UTC by nschonni

Convert some of the simple tables that didn't have things like lists or PRE sections to markdown tables

2022-09-02 20:30 UTC, wbamberg commented
We intentionally didn't convert these because they are not readable in Markdown. See https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#gfm_table_maximum_width .

2022-09-02 21:34 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/4/index.md
> +| {{cssxref("resize")}}        | Lets you control the dimensions in which an element may be resized.                      |
There are some that look trivial enough and I'd be willing to try, e.g. this one

2022-09-03 05:56 UTC, teoli2003 requested changes

2022-09-03 05:56 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/4/index.md
> +| {{cssxref("resize")}}        | Lets you control the dimensions in which an element may be resized.                      |
If I remember well (@wbamberg will know for sure), we limited some table conversions because of the line length of the result.

Often large tables lead to a very poor reading experience, and we are replacing them when possible.

In particular, this one (and other 2-column tables in this PR) should be replaced by definition lists.

I think we should start by doing this.

2022-09-21 02:37 UTC, wbamberg commented
As noted in https://github.com/mdn/content/pull/20258#issuecomment-1235873397, it's intentional not to have Markdown tables in at least most of these cases. If people want to try using `<dl>` instead and it seems appropriate, that's great, but it would probably be better to make it a different PR.

2022-09-21 02:37 UTC, closed without merging