chore: remove preview.yml
mdn/content pull request #20328
Opened 2022-09-05 18:55 UTC by nschonni

This job seems to be a stub of .github/workflows/pr-check_scripts.yml that wasn't implemented

2022-09-06 19:01 UTC, caugner requested changes
No objection against removing this workflow, just one nit.

2022-09-06 19:01 UTC, caugner commented on .github/workflows/preview.yml
> -          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink/index.json > /dev/null
Can we move over these two calls into the Check scripts workflow (start job)?

2022-09-06 20:48 UTC, caugner approved these changes

2022-09-07 03:31 UTC, teoli2003 approved these changes

2022-09-07 03:31 UTC, merged