chore: migrate to markdownlint-cli2
mdn/content pull request #20330
Opened 2022-09-05 19:51 UTC by nschonni

Now that we have a custom rule that is used, it's helpful to migrate to the new config that allows declaring the rules in the config.
I added some comments around the rules, since this file allows that.
This config is compatible with the VScod plug-in, so you get the custom rule errors in the IDE

2022-09-05 21:47 UTC, MrBrain295 commented on .markdownlint-cli2.jsonc
> +    // algorythim currently
```suggestion
    // algorithm currently
```

2022-09-06 18:30 UTC, caugner requested changes
Switching from markdownlint-cli to markdownlint-cli2 looks good to me.

2022-09-06 18:30 UTC, caugner commented on .markdownlint-cli2.jsonc
> +{
Does this warrant updating the JSON check workflow (if prettier supports `*.jsonc`)?

https://github.com/mdn/content/blob/cb22605df3ea99dda17c1dc6fcee2ed5b687e4a5/.github/workflows/pr-check_json.yml#L7-L8

2022-09-06 18:30 UTC, caugner commented on .markdownlint-cli2.jsonc
> +    // Some Callouts currently include headings that don't follow this rule
As the rule names are not self-explanatory, I would suggest repeating their description here:

```suggestion
    // MD001 - Heading levels should only increment by one level at a time.
    // -> Disabled, as some callouts include headings.
```

2022-09-06 18:30 UTC, caugner commented on .markdownlint-cli2.jsonc
> +    // algorithm currently
```suggestion
    // MD051 - Link fragments should be valid.
    // -> Disabled, as yari generates link fragments by replacing spaces with underscores, not dashes.
```

2022-09-06 20:56 UTC, caugner approved these changes

2022-09-07 01:19 UTC, nschonni commented
FYI @OnkarRuikar @teoli2003

2022-09-07 03:21 UTC, merged

2022-09-07 05:03 UTC, Josh-Cena commented
@nschonni After pulling the new changes, my VS Code keeps displaying this at the bottom, and I can neither dismiss the entire panel nor switch to "terminal":

<img width="998" alt="image" src="https://user-images.githubusercontent.com/55398995/188792806-90aba078-49cb-4949-b6a6-bc63088a9f0e.png">

Could you investigate? Thanks!

2022-09-07 05:06 UTC, nschonni commented
have you run Yarn recently to pull in the custom rule?

2022-09-07 05:08 UTC, Josh-Cena commented
Yes, I did. It's installed, but locally. The VS Code extension is only searching in its own bundle, though. I found a setting called `markdownlint.customRules`, but I can't spend too much time on this before going to bed. It's only coming up after this PR.

2022-09-07 06:04 UTC, nschonni commented
Ah, I haven't tried this on my Mac since this landed. I'll check later and see if I get the same. 
Quick hack would be to comment out that rule in the `.markdownlint-cli2.jsonc` temporarily.
Adding the settings and suggested extensions probably is a good discussion to spin up

2022-09-07 06:25 UTC, teoli2003 commented
We want to add settings and suggested extensions on a meta-docs page. I would be glad to see this going forward.

2022-09-07 06:57 UTC, nschonni commented
Just tried it on my Mac and there is no issue. I'm running

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 19.6.0
Sandboxed: No

2022-09-07 06:58 UTC, nschonni commented
I had some user level customRules for the Microsoft Docs Authoring Pack, but I cleared them out to see if it made any difference

2022-09-07 08:10 UTC, OnkarRuikar commented
> We want to add settings and suggested extensions on a meta-docs page. I would be glad to see this going forward.

We definitely need to suggest the [markdownlint VSCode plugin](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint):

![vscodePlugin](https://user-images.githubusercontent.com/87750369/188822099-ef888cb4-4c9d-42c2-bbc4-74737a2e5088.png)

I ran `yarn` on the latest code. Then after installing the plugin it worked out of the box. It uses the same `.markdownlint-cli2.jsonc` config file that we added for the cli2 tool.
Note it's flagging our custom rules and the `Quick Fix...` option also works! :+1:  

***
Also, the screenshot shows `yarn lint:md` worked without any error. I am using Linux.

2022-09-07 12:40 UTC, Josh-Cena commented
Ah, it only works for me after reloading my VS Code. I guess I was too tired last night. Thanks y'all!