Update index.md
mdn/content pull request #20404
Opened 2022-09-07 20:49 UTC by v1nce

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-box-reflect is supposed to be emulated by using element (see warning panel on page webkit-box-reflect ) This is not easy to do. I came up with this solution : 
 duplicate image using element 
 position it :after current image (this does not work, so I got to use a container)
 use absolute positionning
 flip it (scaleY(-1))
 use margin-top as an offset
 use a mask image and a gradient for a shaded reflection

I think this is a decent emulation of -webkit-box-reflect that should be shared.

### Description

Firefox lacks -webkit-box-reflect 

### Motivation

Give the reader a starter about how to emulate it using "element"

### Additional details

if someone came with a better solution that works with class instead of id, I'll be glad to hear about it

### Related issues and pull requests

2022-09-08 05:16 UTC, estelle commented on files/en-us/web/css/element/index.md
> +Firefox does not support -webkit-box-reflect. You can emulate it -to some extent- using element.
This needs to be elaborated on. using element? not sure what you are trying to say.

2022-09-08 05:27 UTC, estelle requested changes
I think this should likely be on the box-reflect page, not the element page.

all images need alt attributes, even if decorative and therefore empty.

2022-09-08 05:27 UTC, estelle commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
all images need to include alt text.

2022-09-08 05:27 UTC, estelle commented on files/en-us/web/css/element/index.md
> +    -webkit-box-reflect: below 20px -webkit-gradient(linear, left bottom, left top, from(rgba(255,255,255,1)), color-stop(40%, transparent) , to(transparent));
Should use un-prefixed gradient syntax. See https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient. If you are trying to target only browsers that support -webkit-box-reflect, use @supports. 

```css
@supports (-webkit-box-reflect) {
   #pictureWReflection {
     /* valid, modern code here. no vendor prefix */
   }
}
```

2022-09-08 05:27 UTC, estelle commented on files/en-us/web/css/element/index.md
> + transform:scaleY(-1);
include a space betwee the `:` and the value.
this code needs to be commented or explained.

2022-09-08 05:31 UTC, estelle commented on files/en-us/web/css/element/index.md
> +<span id="#container">
container is a very generic term. maybe `reflectionContainer` or some indicator of the function. Also, better to use a class name than an id so the reflection is reusable, and then maybe the id for just the `background-image` css.

2022-09-08 05:31 UTC, Josh-Cena commented
I would format this myself before it's ready to be merged since the formatting looks quite awkward.

2022-09-08 20:53 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
I'm using it in a web app so no need for an alt.

2022-09-08 20:54 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +    -webkit-box-reflect: below 20px -webkit-gradient(linear, left bottom, left top, from(rgba(255,255,255,1)), color-stop(40%, transparent) , to(transparent));
I don't know if un-prefixed syntax will wok.

2022-09-08 21:07 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +<span id="#container">
I disagree. The webkit version is a no-brainer where you could use class for every instance. Firefox workaround will need an id for every image that will need reflection. I don't see any interest in mixing class for the container and id for the element. Just be straight/honest to the people and tell them right away firefox version is inferior because it needs an id per image.

Unless someone can think of a better implementation that does not need it.

2022-09-10 05:24 UTC, estelle commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
MDN is for all developers. it's not about **your** web app.

2022-09-10 06:02 UTC, teoli2003 requested changes
I  have a few more comments and a fundamental question about the page this example is on.

Also, we will need to run Prettier on this page before merging this to fix all the alignment inconsistencies and oddities. (I hope we can activate it soon, but we still have work here)

2022-09-10 06:07 UTC, teoli2003 commented on files/en-us/web/css/element/index.md
> +     src="/media/cc0-images/grapefruit-slice-332-332.jpg">
As this is not a live example and this image not stored here, we should use a placeholder name:
```suggestion
     src="pictureToReflect.jpg">
```

2022-09-10 19:32 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +Firefox does not support -webkit-box-reflect. You can emulate it -to some extent- using element.
yes I meant -moz-element.

2022-09-10 19:33 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
I wanted to keep the exemple as minimal as possible to show what's important.

2022-09-10 19:40 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +### Emulating -webkit-box-reflect
You're probably right. It should be on -webkit-box-reflect.

2022-09-12 08:36 UTC, teoli2003 commented on files/en-us/web/css/element/index.md
> +Firefox does not support -webkit-box-reflect. You can emulate it -to some extent- using element.
```suggestion
In browsers not supporting {{cssxref("-webkit-box-reflect")}}, can achieve the same outcome using `element`. 
```

2022-09-12 08:37 UTC, teoli2003 commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
```suggestion
<img alt="A reflected image of …" id="pictureWReflection"
```

2022-09-13 21:17 UTC, v1nce commented on files/en-us/web/css/element/index.md
> +<img id="pictureWReflection"
Alt is not mandatory. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
So add it if you want. But I won't.

2022-09-20 21:21 UTC, estelle commented
This PR isn't going to move forward with the contributor arguing with rather than learning from the feedback. Closing.

2022-09-20 21:21 UTC, closed without merging