style: run prettier on webassembly
mdn/content pull request #20405
Opened 2022-09-07 21:12 UTC by nschonni

Mostly spacing after the metadata, but manually adjusted some list spacing after it added extra line breaks

2022-09-07 21:31 UTC, Josh-Cena commented on files/en-us/webassembly/c_to_wasm/index.md
> +       null // arguments
Could you run it with `"trailingComma": "all"`? (Or prepare a PR to add it to the config)

2022-09-07 21:37 UTC, nschonni commented on files/en-us/webassembly/c_to_wasm/index.md
> +       null // arguments
updated the config, since it doesn't look like it affects the current JSON/YML that is already clean

2022-09-07 22:18 UTC, Josh-Cena commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Count the amount of leading zeros in a numbers binary representation.
This doesn't create a dl—not every element has a `:`. Just use a normal ul.

2022-09-07 22:23 UTC, nschonni commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Count the amount of leading zeros in a numbers binary representation.
Right, I could use a `<-- -->` above this to split the list into a UL then a DL. Looking at the rest of the page it seemed like it was supposed to be DL elements, but the ones in here hadn't been stubbed out

2022-09-07 22:28 UTC, Josh-Cena commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Count the amount of leading zeros in a numbers binary representation.
That would be a bit weird, since we would have a ul and a dl sitting side-by-side. Maybe we could add a very brief intro for each of the operations above as well?

2022-09-08 01:07 UTC, nschonni commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Count the amount of leading zeros in a numbers binary representation.
I stubbed in some DDs from the article opening paragraphs.

2022-09-08 23:41 UTC, hamishwillee commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Count the amount of leading zeros in a numbers binary representation.
I like that. The benefit of a DL is the auto creation of an anchor in the page.

2022-09-08 23:43 UTC, hamishwillee approved these changes
Lots to love, nothing to hate.

I'm approving but leaving open as there were comments from others.

How can I run this locally? I'm thinking of updating the learn express and django docs, but I want to make sure I run the same thing for both the docs and the source code.

2022-09-08 23:49 UTC, nschonni commented
> How can I run this locally? I'm thinking of updating the learn express and django docs, but I want to make sure I run the same thing for both the docs and the source code.

Currently you can run with `yarn prettier -w files/en-us/learn/server-side/django/`. If the default ignore lands in https://github.com/mdn/content/pull/20397 it will be a little different, and you'd need to op the folder in with the `.prettierignore`

2022-09-09 00:06 UTC, Josh-Cena commented
@hamishwillee the express guide is a bit more involved, because there are a lot of "code pieces" that are not valid grammar standalone. Both the linter and the formatter choke on them, and I don't know what to do about them yet. If you could figure out a way to make every code block parsable JavaScript it would be great.

2022-09-09 01:29 UTC, hamishwillee commented
THanks @nschonni @Josh-Cena . I might wait until the default ignore goes in.

Re code pieces that are not valid grammar "we will see". I think I need to start by running prettier on the source code (following yari prettier rules) then copying in, and slowly working through to something that no longer chokes our tools.

2022-09-09 04:44 UTC, teoli2003 commented on .prettierrc.json
> +  "trailingComma": "all"
I want to be sure we have a consensus on this, and I'm fairly confident we can have it. This has a consequence much wider than this PR, and I wouldn't want it to be reversed later, leading to undoing what has been requested here.

Can you create a PR with just this change so that we get a wide set of reviewers approving it?

Then, we can rebase this one and merge it.

2022-09-09 04:44 UTC, teoli2003 requested changes
The .prettier should be in its own PR, so that we can track that we have a consensus.

2022-09-09 05:27 UTC, nschonni commented
@Josh-Cena I've backed out the trailing comma config changes and fixes. I'll let you submit a separate PR to introduce that

2022-09-09 08:09 UTC, teoli2003 approved these changes
This looks great to me. Thanks, @nschonni. (Approving, but leaving it to the others to merge it)

2022-09-09 08:10 UTC, teoli2003 commented on files/en-us/webassembly/reference/numeric/index.md
> +  - : Used for performing a bitwise right-rotate.
Maybe, but I think this is out of the scope for this PR, as this may lead to a discussion on its own.

2022-09-09 08:27 UTC, teoli2003 commented
> @Josh-Cena I've backed out the trailing comma config changes and fixes. I'll let you submit a separate PR to introduce that

Created: mdn/content#20405 (and we'll be able to check if we have a consensus in it)

2022-09-10 06:43 UTC, nschonni commented
I don't think there are any other blockers on this one. The trailing commas can be fixed later if the config PR lands

2022-09-10 06:49 UTC, teoli2003 commented
Agreed.

2022-09-10 06:49 UTC, merged