Fixes to drag operations page
mdn/content pull request #20403
Opened 2022-09-07 20:47 UTC by wbamberg

### Description

Rewrite the page to use `addEventListener` rather than HTML event attributes, and have a better example in "Specifying drop targets". This PR replaces https://github.com/mdn/content/pull/20048.

But also a bit of yak-shaving:
- remove some Firefox-only stuff (`:-moz-drag-over` and XUL(!))
- sentence case for headings

I used Prettier so it has also reformatted other code samples. I hope that is OK.

### Motivation

Better practice code samples.

### Related issues and pull requests
Relates to https://github.com/mdn/content/pull/20048.

2022-09-08 05:51 UTC, teoli2003 requested changes
A few nit, and a problem at `doDrop`

2022-09-08 05:51 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
nit:
```suggestion
draggableElement.addEventListener("dragstart", (event) => {
  event.dataTransfer.setData("text/plain", "This text may be dragged");
});
```

2022-09-08 05:51 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
```suggestion
```js
const draggableElement = document.querySelector('p[draggable="true"]');
draggableElement.addEventListener("dragstart", (event) => {
  event.dataTransfer.setData("text/plain", "This text may be dragged");
});
```

2022-09-08 05:51 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
>    }
This is weird, it does nothing… `data` is declared in the scope, and not used…

2022-09-08 05:51 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
>    }
I wonder if there is a `return data;` missing for `doDrop`, and a scoping problem.

2022-09-08 22:24 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
This is interesting and I'm not sure what the right thing to do is. I wrote:

```js
draggableElement.addEventListener("dragstart", (event) => event.dataTransfer.setData("text/plain", "This text may be dragged"));
```

(which is fine AFAIK) but which Prettier auto-formatted to:

```js
draggableElement.addEventListener("dragstart", (event) =>
  event.dataTransfer.setData("text/plain", "This text may be dragged")
);
```

So if we want to rely on Prettier auto-formatting, then we should not make your suggested change.

2022-09-08 23:09 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
>    }
All I wanted to do in this PR was fix the events and a bit of yak-shaving, not rewrite all these existing examples.

This is not a real (runnable) example, so it's unclear what it's supposed to be doing. The simplest thing to do here is:

```js
  if (types.length) {
    const data = event.dataTransfer.getData(types[0]);
    // use this type of data
  }
```

...but ESLint won't like that.

I'm not sure what a realistic thing for this example to be doing with the data it's getting. The example is also asking for the internal Mozilla `"application/x-moz-file"` type.

So, fixing this properly is a deep dive into this API. I don't think it is worth it in this PR.

2022-09-09 09:57 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
If you had written:

```
draggableElement.addEventListener("dragstart", (event) => { event.dataTransfer.setData("text/plain", "This text may be dragged");});
```

The results would have been:
```
draggableElement.addEventListener("dragstart", (event) => {
  event.dataTransfer.setData("text/plain", "This text may be dragged");
});
```

So the question here is not Prettier formatting, but do we add braces when there is only one operation and no (real) return value (ok, it returns something, but not useful here). We recommend using _consise body_ (or _implicit return_) with arrow functions when possible, but is this the case?

(We skipped this question while reviewing the JS guidelines)

2022-09-09 09:59 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
>    }
I think adding the comment is enough for now. (When we would like to use ESlint we'll need to revisit it, but we are not close to this yet):
```suggestion
  if (types.length) {
    const data = event.dataTransfer.getData(types[0]);
    // Use this type of data…
  }
```

2022-09-09 15:08 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
> If you had written:
> 
> ```
> draggableElement.addEventListener("dragstart", (event) => { event.dataTransfer.setData("text/plain", "This text may be dragged");});
> ```
> 
> The results would have been:
> 
> ```
> draggableElement.addEventListener("dragstart", (event) => {
>   event.dataTransfer.setData("text/plain", "This text may be dragged");
> });
> ```
> 
> So the question here is not Prettier formatting, but do we add braces when there is only one operation and no (real) return value (ok, it returns something, but not useful here)? We recommend using _consise body_ (or _implicit return_) with arrow functions when possible, but is this the case?

Do you mean, is it possible? Of course it is.

But it doesn't matter whether we use the return or not. If my code had been:

```js
const myItemsWithALongEnoughName = [1, 2, 3, 4];
const filteredWithALongEnoughName = myItemsWithALongEnoughName.filter((item) => item < 3);

console.log(filteredWithALongEnoughName);
```

...then Prettier would do:

```js
const myItemsWithALongEnoughName = [1, 2, 3, 4];
const filteredWithALongEnoughName = myItemsWithALongEnoughName.filter(
  (item) => item < 3
);

console.log(filteredWithALongEnoughName);
```

It's just wrapping lines.

So the question is: do we say you can't use the concise form if it would give you a line long enough for Prettier to wrap? I don't think we should do this, because it goes against the idea of using Prettier, which is basically: you don't have to worry about what Prettier will do, or have any knowledge of its config.

2022-09-09 15:09 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
So I think we should allow (maybe even encourage) people to use to use the concise form if it's allowed, and allow Prettier's wrapping if Prettier decides to wrap.

2022-09-09 16:07 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
>    }
There are probably hundreds if not thousands of cases like this in static example code blocks. For instance, just above:

```js
const link = event.dataTransfer.getData("URL");
```

2022-09-12 10:49 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.md
> +);
No strong feelings here.

2022-09-12 10:49 UTC, teoli2003 approved these changes

2022-09-12 10:49 UTC, merged