More clearly explain catch binding scope
mdn/content pull request #20428
Opened 2022-09-08 13:49 UTC by Josh-Cena

### Description

Mention an Annex B feature, as well as highlighting that there should be zero duplicate names.

### Motivation

### Additional details

### Related issues and pull requests

2022-09-08 14:04 UTC, teoli2003 commented
If it is not implemented anywhere, we should not document it. We document implementations, not specs.

2022-09-08 14:05 UTC, Josh-Cena commented
Annex B is implemented by all browsers, so for web developers it'll always work, just deprecated.

2022-09-08 14:09 UTC, teoli2003 submitted a review, later dismissed

2022-09-08 14:09 UTC, teoli2003 commented on files/en-us/web/javascript/reference/deprecated_and_obsolete_features/index.md
> +This is listed in Annex B of the spec and hence may not be implemented everywhere. Avoid any name conflicts between the `catch`-bound identifier and variables declared in the `catch` block.
If it is implemented everywhere, this is not relevent? Isn't it?

2022-09-08 14:11 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/deprecated_and_obsolete_features/index.md
> +This is listed in Annex B of the spec and hence may not be implemented everywhere. Avoid any name conflicts between the `catch`-bound identifier and variables declared in the `catch` block.
Also, it's also stated in the intro of this section:

> Programmers should not use or assume the existence of these features and behaviors when writing new ECMAScript code.

So even when it always works, you should write code as if it doesn't work.

2022-09-22 16:06 UTC, Josh-Cena commented
Oops, didn't mean to dismiss, but this needs a re-review anyway...

2022-10-29 21:51 UTC, Josh-Cena commented
Pinging @teoli2003 again to decide what to do here, since I have another pending PR to improve the `var` pages.

2023-05-03 07:07 UTC, Josh-Cena commented
@teoli2003 This has been around forever, so maybe we can decide what is needed?

2023-05-22 17:16 UTC, Josh-Cena commented
I am (semi-)randomly bringing in another JS reviewer to hopefully get some more feedback...

2023-05-23 17:22 UTC, wbamberg requested changes
Some semi-random comments 🤣

2023-05-23 17:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +  - : An optional [identifier or pattern](#the_exception_variable) to hold the caught exception for the associated `catch` block. If the `catch` block does not utilize the exception's value, you can
```suggestion
  - : An optional [identifier or pattern](#the_exception_variable) to hold the caught exception for the associated `catch` block. If the `catch` block does not use the exception's value, you can omit the `exceptionVar` and its surrounding parentheses, as `catch {...}`.
```

2023-05-23 17:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +  - : An optional [identifier or pattern](#the_exception_variable) to hold the caught exception for the associated `catch` block. If the `catch` block does not utilize the exception's value, you can
Maybe just me, but I found "as `catch {...}`" very confusing, it seemed like `{...}` was some special syntax rather than just a depiction of the body of the catch block. Maybe because it was on the same line, or because it read as presented as an alternative to `catch(e)` rather than the whole thing. I don't have an alternative except just omitting the example, which (IMO) would be clearer.

2023-05-23 17:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +If you don't need the exception value, it could be omitted along with the enclosing parentheses.
```suggestion
If you don't need the exception value, you can omit it along with the enclosing parentheses.
```

2023-05-23 17:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
This seems like it's just repeating what's said above. Especially things like:

> The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.

looks like substantive documentation, not illustrative example.

2023-05-23 17:22 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
In general I wonder a bit about this sequence of three examples (in the old page as well as the new):
- Unconditional catch block
- Conditional catch blocks
- Re-throwing errors

So the first of these just looks like " a catch block", and the second I think "so what, you can use conditional code in a catch block, why wouldn't you be able to". The payoff ISTM is re-throwing errors, which is such a common usage that I wonder if it would be better to rework this to lead with (and in fact only include) that:

```
### Re-throwing errors

A common pattern is to (handle some errors and re-throw the others)
```

...I don't know if that would sit better in "Examples" or "Description". Examples maybe.  I wish again that we had H3s in the ToC.

2023-05-24 03:27 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +  - : An optional [identifier or pattern](#the_exception_variable) to hold the caught exception for the associated `catch` block. If the `catch` block does not utilize the exception's value, you can
```suggestion
  - : An optional [identifier or pattern](#the_exception_variable) to hold the caught exception for the associated `catch` block. If the `catch` block does not use the exception's value, you can omit the `exceptionVar` and its surrounding parentheses.
```

2023-05-24 03:29 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
> so what, you can use conditional code in a catch block, why wouldn't you be able to

The point of this example is not to illustrate a capability, but to mimic a pattern in other languages. For example, in Java you can do this:

```java
try {
  doSomething();
} catch (TypeError e) {
  handle(e);
} catch (RangeError e) {
  handle(e);
}
```

There have been many proposals to implement the same pattern in JavaScript, but others believe that `if...else` within the `catch` block is sufficient.

2023-05-24 03:33 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
I understand it's slightly repetitive, but I think it's fine to describe the same concept again in the context of an example.

2023-05-24 04:36 UTC, wbamberg approved these changes
👍

2023-05-24 04:36 UTC, merged

2023-05-24 04:48 UTC, Josh-Cena commented
Thanks @wbamberg!

2023-05-25 17:53 UTC, wbamberg commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
> The point of this example is not to illustrate a capability, but to mimic a pattern in other languages.

Although I merged this: if the intention here is to contrast with languages which have this feature, then it ought to say that. Many people reading these docs will not have experience of other languages, and although I do, it is rusty enough for me not to understand the point of this example. If real people (i.e. me) don't understand the point of the example, it's a little dismissive to, well, dismiss it.

2023-05-25 17:54 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/statements/try...catch/index.md
> +The `catch` block specifies an identifier (`e` in the example above) that holds the value of the exception; this value is only available in the {{Glossary("Scope", "scope")}} of the `catch` block.
I will add it to https://github.com/mdn/content/pull/26973, which is enabled by this PR.