fix: doc about instanceof keyword
mdn/content pull request #2048
Opened 2021-02-03 15:56 UTC by RaisinTen

Hello! I was reading the docs and thought about fixing the grammar here. :)

2021-02-03 17:22 UTC, Aayushap1 approved these changes

2021-02-04 09:20 UTC, Rumyra requested changes

2021-02-04 09:20 UTC, Rumyra commented on files/en-us/web/javascript/data_structures/index.html
> +<p>Keep in mind the only valuable purpose of <code>typeof</code> operator usage is checking the Data Type. If we wish to check any Structural Type derived from Object it is pointless to use <code>typ
```suggestion
<p>Keep in mind the only valuable purpose of <code>typeof</code> operator usage is checking the Data Type. If we wish to check any Structural Type derived from Object it is pointless to use <code>typeof</code> for that, as we will always receive <code>"object"</code>. The proper way to check what sort of Object we are using is the {{jsxref("Operators/instanceof", "instanceof")}} keyword. But even in that case there might be misconceptions.</p>
```

Thanks @RaisinTen - I don't think we need the word 'indeed' at all here :)

2021-02-04 10:05 UTC, RaisinTen commented on files/en-us/web/javascript/data_structures/index.html
> +<p>Keep in mind the only valuable purpose of <code>typeof</code> operator usage is checking the Data Type. If we wish to check any Structural Type derived from Object it is pointless to use <code>typ
@Rumyra thanks for reviewing. I committed your suggestion. PTAL.

2021-02-04 10:10 UTC, Rumyra approved these changes
Thanks so much @RaisinTen ☺️

2021-02-04 10:11 UTC, merged