fix: make code work again
mdn/content pull request #20525
Opened 2022-09-10 18:21 UTC by MarcoASilva

### Description

1. fix complete example code
2. add some styles 2.1 show buttons as a list
2.2 turn button color green when pressed

### Motivation

Tried code from MDN and it didn't work

2022-09-10 19:09 UTC, teoli2003 requested changes
Yes, the `forEach` doesn't work on an object. I have a few questions on some other changes.

2022-09-10 19:09 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    const controller = controllers[i];
Never use `for...in` with arrays and objects (as extra methods or properties can be added). While `forEach` doesn't work with objects, it is better to do this.
```suggestion
  controllers.entries().forEach((controller, i) => {
```

2022-09-10 19:09 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +      b.style.color = pressed ? "#42f593" : "#2e2d33";
As we set a class name on the next line, this should be in the CSS.

2022-09-10 19:09 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +      // Can be null if disconnected during the session
```suggestion
    // gamepad is null if disconnected during the session
    if (gamepad) {
```

2022-09-10 19:09 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    : "block";
What is this for?

2022-09-10 19:09 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +  document.querySelector("#noDevices").style.display = "block";
What is this for?

2022-09-25 16:11 UTC, MarcoASilva commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +      b.style.color = pressed ? "#42f593" : "#2e2d33";
I didn't find a css code snippet on this mdn page, where css class defs should be placed?

2022-09-25 16:14 UTC, MarcoASilva commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    : "block";
Displaying a text to the user informing no devices were found

2022-09-25 16:15 UTC, MarcoASilva commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    : "block";
Up to now nothing is showed (empty/blank page) if no controllers are connected or no buttons were pressed

2022-09-25 16:16 UTC, MarcoASilva commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +  document.querySelector("#noDevices").style.display = "block";
Just removed, as L304 is showing a text to the user when no gamepads were found

2022-09-25 16:26 UTC, MarcoASilva commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    const controller = controllers[i];
As controllers is an object (map of gamepads by id) I used `Object.entries`

2023-03-30 04:50 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +      b.style.color = pressed ? "#42f593" : "#2e2d33";
Yes, as the CSS is not here, let's keep this that way.

2023-03-30 04:50 UTC, teoli2003 commented on files/en-us/web/api/gamepad_api/using_the_gamepad_api/index.md
> +    : "block";
👍

2023-03-30 04:50 UTC, teoli2003 approved these changes
👍

2023-03-30 04:51 UTC, merged