HTML code style: No trailing slash, add note about prettier
mdn/content pull request #20528
Opened 2022-09-10 19:28 UTC by rubiesonthesky

### Description

- Remove section about trailing slash, it's conflicting with Prettier https://github.com/mdn/content/issues/20523
  It seems that there was already comment about if the section is relevant or not.
- Add section about format, copied from Javascript code style page
- Added heading "Complete HTML document"
  This is not so clear change, but I feel it's highly confusing that there are "general guidelines" and then it's said that these only affect small subset of examples. When I first reading this page, it seemed to say that these general guidelines do not affect if you are just having snippet of code. This change can be dropped off from this PR, if it does not fit.

2022-09-10 19:36 UTC, teoli2003 requested changes
I will only ask about it in our Editorial meeting to be sure, so meanwhile, I'm "Requesting changes" to be sure it is not merged by error.

I don't think there will be any opposition from the content peers, but we never now.

2022-09-12 16:45 UTC, Rumyra commented
None from me - looks good - thanks @rubiesonthesky & @teoli2003

2022-09-12 16:49 UTC, teoli2003 commented
Thanks!

2022-09-12 16:49 UTC, teoli2003 approved these changes

2022-09-12 16:49 UTC, merged

2022-09-26 12:04 UTC, hsivonen commented
I find it sad that the course of action here is to change MDN instead of changing Prettier. HTML permitting the no-op slashes means that the HTML spec doesn't ask people to waste time modifying their Appendix C-era markup, but I think the history of this aspect of the spec doesn't support the position of _adding_ slashes as a matter of automated formatting. To the extent readers write code manually without the same tool, the slashes interact poorly with another HTML feature: unquoted attribute values ([demo](https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10809)). Prettier itself doesn't trip over this: It adds a space before the slash and _also_ adds quotes, even though either one would be sufficient. The result looks like what was needed to make Netscape 4 tolerate Appendix C, which makes the result have code smell of obsolete practices. Similar energy as recommending the "Web-safe" intersection of the Windows and Mac 256-color palettes.

2022-09-27 06:30 UTC, OnkarRuikar commented
I think we better open a [community discussion](https://github.com/mdn/mdn-community/discussions) quickly before we have all valuable inputs scattered over PRs, and before people spending time and energy doing the same debate over multiple PRs.

Ping @schalkneethling

2022-09-27 14:56 UTC, wbamberg commented
> I think we better open a [community discussion](https://github.com/mdn/mdn-community/discussions) quickly before we have all valuable inputs scattered over PRs, and before people spending time and energy doing the same debate over multiple PRs.
> 
> Ping @schalkneethling

-> https://github.com/mdn/mdn-community/discussions/242 I hope I have done a reasonable job of capturing the issue there.