fix: add missing extension for PR template
mdn/content pull request #20526
Opened 2022-09-10 18:22 UTC by nschonni

## Description

Add missing extension and fix minor Markdownlint issues now that it is parsed as MD

## Motivation

I don't always use these, but it looks like it was added some time ago, but isn't currently being picked up with the missing extension

## Additional details

## Related issues and pull requests

2022-09-10 19:16 UTC, Josh-Cena commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- markdownlint-disable-file MD041-->
Can we simply disable Markdownlint for this file? The comment will be displayed to all authors, and that's not very helpful.

2022-09-10 19:18 UTC, teoli2003 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- markdownlint-disable-file MD041-->
Yes, let's disable Markdonwlint for this file. It isn't really part of MDN proper and doesn't abide to the MDN style guide.

2022-09-10 19:29 UTC, nschonni commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- markdownlint-disable-file MD041-->
Feel free to do a new PR without the disable

2022-09-11 14:56 UTC, teoli2003 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- markdownlint-disable-file MD041-->
```suggestion
```

2022-09-11 14:58 UTC, teoli2003 requested changes
We don't want to add a magic comment here; we want to disable Markdownlint for this file as it is not part of MDN proper and doesn't have to follow the same rules.

2022-09-11 17:27 UTC, nschonni commented
As mentioned on other PRs, @teoli2003 @Josh-Cena you two don't seem to like disable comments, but I'm not going to spend effort to work around your dislike of them

2022-09-11 17:35 UTC, Josh-Cena commented
Just add the `.github` folder to https://github.com/mdn/content/blob/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec/.markdownlint-cli2.jsonc#L160?

2022-09-12 16:01 UTC, caugner approved these changes

2022-09-21 02:33 UTC, wbamberg commented
Closing in favour of https://github.com/mdn/content/pull/20940, hopefully.

2022-09-21 02:33 UTC, closed without merging