style: run prettier on web/m-x
mdn/content pull request #20549
Opened 2022-09-11 06:11 UTC by nschonni

Not run on code fences

2022-09-11 09:00 UTC, teoli2003 requested changes

2022-09-11 19:48 UTC, Josh-Cena commented on files/en-us/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +</mrow>
What about no line breaking here at all, like what we did in the JS section? Prettier does not indent HTML tags in Markdown because different renderers have different rules.

2022-09-11 19:50 UTC, teoli2003 commented on files/en-us/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +</mrow>
I think no-line-breaking would be better here than no indentation.

2022-09-13 04:31 UTC, nschonni commented on files/en-us/web/svg/element/feconvolvematrix/index.md
> +) / [divisor](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementDivisorAttribute) + [bias](https://www.w3.org/TR/SVG11/filters.html#feConvolveMatrixElementBiasAttribute) \* ALPHA<sub>X,
It seems like this rendering is intentionally not a code fence with all the HTML mixed in
![image](https://user-images.githubusercontent.com/1297909/189809103-64576d9f-ae33-4c02-aecf-a68762f33dea.png)
It's the same with or without the formatting

2022-09-13 04:40 UTC, Josh-Cena commented on files/en-us/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +
This is typeset as an inline formula. You can't put it on its own paragraph. Just write it in one line, like:

```html
i.e., If a and b are the legs and c is the hypotenuse then <math><mrow><msup><mi>a</mi><mn>2</mn></msup><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup><mo>=</mo><msup><mi>c</mi><mn>2</mn></msup></mrow></math>.
```

2022-09-13 04:41 UTC, nschonni commented on files/en-us/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +</mrow>
I added a line above and then prettier didn't reformat it, but it does look like this is an inline formula in the sentence

2022-09-13 04:50 UTC, Josh-Cena commented on files/en-us/web/svg/attribute/transform/index.md
> +The `matrix(<a> <b> <c> <d> <e> <f>)` transform function specifies a transformation in the form of a transformation matrix of six values. `matrix(a,b,c,d,e,f)` is equivalent to applying the transform
Calling this out: it's trying to format text within the `<math>` tag (specifically, `_` to `*`). I don't know why it does that since it's obviously in HTML.

2022-09-13 04:52 UTC, Josh-Cena commented on files/en-us/web/svg/tutorial/basic_transformations/index.md
> +<math display="block"><semantics><mrow><mo>{</mo><mtable rowspacing="0.5ex"><mtr><mtd><msub><mi>x</mi><mstyle mathvariant="normal"><mrow><mi>newCoordSys</mi></mrow></mstyle></msub><mo>=</mo><mi>a</mi
Same here

2022-09-15 02:24 UTC, nschonni commented on files/en-us/web/svg/attribute/transform/index.md
> +The `matrix(<a> <b> <c> <d> <e> <f>)` transform function specifies a transformation in the form of a transformation matrix of six values. `matrix(a,b,c,d,e,f)` is equivalent to applying the transform
I tried to see if adding a line before it would make Prettier ignore it, but not dice. If you look at the output of the preview, it looks like they output the same MathML rendering

2022-09-15 02:29 UTC, Josh-Cena commented on files/en-us/web/svg/attribute/transform/index.md
> +The `matrix(<a> <b> <c> <d> <e> <f>)` transform function specifies a transformation in the form of a transformation matrix of six values. `matrix(a,b,c,d,e,f)` is equivalent to applying the transform
The MathML is the same, but the TeX within `semantics` is different.

2022-09-16 00:58 UTC, nschonni commented on files/en-us/web/svg/tutorial/basic_transformations/index.md
> +<math display="block"><semantics><mrow><mo>{</mo><mtable rowspacing="0.5ex"><mtr><mtd><msub><mi>x</mi><mstyle mathvariant="normal"><mrow><mi>newCoordSys</mi></mrow></mstyle></msub><mo>=</mo><mi>a</mi
I've reverted this

2022-09-16 00:59 UTC, nschonni commented on files/en-us/web/svg/attribute/transform/index.md
> +The `matrix(<a> <b> <c> <d> <e> <f>)` transform function specifies a transformation in the form of a transformation matrix of six values. `matrix(a,b,c,d,e,f)` is equivalent to applying the transform
I've reverted this again

2022-09-16 01:00 UTC, nschonni commented on files/en-us/web/svg/attribute/xml_colon_space/index.md
> +    For example, the string "a b" (three spaces between "a" and "b") separates "a" and "b" more than "a b" (one space between "a" and "b").
Turns out that Markdown is still collapsing down the multiple spaces when rendering, even in the code fence. I've tried replacing it with NBSPs, which at least renders correctly, but prettier still tries to fix https://github.com/prettier/prettier/issues/13485

2022-10-30 18:45 UTC, closed without merging