style: run prettier on web/g-j
mdn/content pull request #20548
Opened 2022-09-11 06:09 UTC by nschonni

Not run on code fences

2022-09-11 09:21 UTC, teoli2003 requested changes

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/guide/houdini/index.md
> +> they don't need to be passed as function arguments.
```suggestion

The CSS `paint()` function is an additional function supported by the {{cssxref("image")}} type.
It takes parameters that include the name of the worklet,
plus additional parameters needed by the worklet.
The worklet also has access to the element's custom properties:
they don't need to be passed as function arguments.
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/guide/mobile/mobile-friendliness/index.md
> +![Screen shot of the Alaska Air desktop site on the left, and an iPhone showing the mobile version of the same page](alaska_air_mobile_and_desktop-300x225.png)\_
```suggestion
![Screen shot of the Alaska Air desktop site on the left, and an iPhone showing the mobile version of the same page](alaska_air_mobile_and_desktop-300x225.png)
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/html/attributes/rel/index.md
> +  - : Relevant to {{htmlelement('form')}}, {{htmlelement('a')}}, and {{htmlelement('area')}}, creates a top-level browsing context that is not an auxiliary browsing context if the hyperlink would cre
```suggestion
  - : Relevant to {{htmlelement('form')}}, {{htmlelement('a')}}, and {{htmlelement('area')}}, creates a top-level browsing context that is not an auxiliary browsing context if the hyperlink would create either of those to begin with (i.e., has an appropriate `target` attribute value). In other words, it makes the link behave as if [`window.opener`](/en-US/docs/Web/API/Window/opener) were null and `target="_parent"` were set.
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/html/element/marquee/index.md
> +  - : Sets the interval between each scroll movement in milliseconds. The default value is 85. Note that any value smaller than 60 is ignored and the value 60 is used instead, unless`truespeed`is spe
```suggestion
  - : Sets the interval between each scroll movement in milliseconds. The default value is 85. Note that any value smaller than 60 is ignored and the value 60 is used instead unless `truespeed` is specified.
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/html/element/marquee/index.md
> +  - : By default,`scrolldelay`values lower than 60 are ignored. If`truespeed`is present, those values are not ignored.
```suggestion
  - : By default, `scrolldelay` values lower than 60 are ignored. If`truespeed`is present, those values are not ignored.
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/html/element/thead/index.md
> +  - : This attribute defines the background color of each cell of the column. It accepts a 6-digit hexadecimal color or a named color. Alphatransparency is not supported.
```suggestion
  - : This attribute defines the background color of each column cell. It accepts a 6-digit hexadecimal color or a named color. Alpha transparency is not supported.
```

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forwards/index.md
> +---
What a weird diff… What's going here?

2022-09-11 09:21 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.md
> +> Invoking the `AsyncGeneratorFunction` constructor as a function (without using the `new` operator) has the same effect as invoking it as a constructor.
```suggestion

Invoking the `AsyncGeneratorFunction` constructor as a function (without using the `new` operator) has the same effect as invoking it as a constructor.
```

2022-09-11 09:48 UTC, teoli2003 commented on files/en-us/web/http/headers/max-forwards/index.md
> +---
That's fine then.

2022-09-11 16:58 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/number/number/index.md
> +When `Number` is called as a constructor (with [`new`](<(/en-US/docs/Web/JavaScript/Reference/Operators/new)>)), it creates a {{jsxref("Number")}} object, which is **not** a primitive.
```suggestion
When `Number` is called as a constructor (with [`new`](/en-US/docs/Web/JavaScript/Reference/Operators/new)), it creates a {{jsxref("Number")}} object, which is **not** a primitive.
```

2022-09-11 17:02 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          This option can be also be set through the `options` property `collation`.
This change makes it collapse with the last bullet. It also happens with quite a few other lists. We need to add a line break before and then re-format.

2022-09-11 17:23 UTC, nschonni commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          This option can be also be set through the `options` property `collation`.
```suggestion

        This option can be also be set through the `options` property `collation`.
```

2022-09-11 19:43 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          > property takes precedence.
```md
          - `zhuyin` (Chinese)

          > **Note:** This option can also be set through the `co` Unicode
          > extension key; if both are provided, this `options`
          > property takes precedence.
```

Otherwise it's a subitem of the `li`. Probably needs a re-format.

2022-09-11 19:44 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +          page.
```md
        - `"lookup"`

        For information about this option, see the {{jsxref("Global_Objects/Intl", "Intl", "#Locale_negotiation", 1)}} page.
```

Also needs a reformat

2022-09-11 19:45 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md
> +      **Defaults to `false`.**
```md
    - other attributes of its descriptor cannot be changed (however, if it's a data descriptor with `writable: true`, the `value` can be changed, and `writable` can be changed to `false`).

    **Defaults to `false`.**
```

2022-09-11 19:48 UTC, teoli2003 reviewed
I found a few extra fixes, but we are close to land this I think

2022-09-11 19:48 UTC, teoli2003 commented on files/en-us/web/html/element/marquee/index.md
> +  - : By default, `scrolldelay` values lower than 60 are ignored. If`truespeed`is present, those values are not ignored.
```suggestion
  - : By default, `scrolldelay` values lower than 60 are ignored. If `truespeed` is present, those values are not ignored.
```

2022-09-11 19:48 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +          page.
```suggestion

        For information about this option, see the
        {{jsxref("Global_Objects/Intl", "Intl", "#Locale_negotiation", 1)}}
        page.
```

2022-09-11 19:48 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md
> +      **Defaults to `false`.**
```suggestion

    **Defaults to `false`.**
  
```

2022-09-11 19:51 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +          page.
This would probably need a re-format even after committing the change, because this `li` is now multi paragraph and it would have extra empty lines around.

2022-09-12 12:55 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          > property takes precedence.
```suggestion

        > **Note:** This option can also be set through the `co` Unicode
        > extension key; if both are provided, this `options`
        > property takes precedence.
```

2022-09-12 12:57 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md
> +      **Defaults to `false`.**
```suggestion

    **Defaults to `false`.**
```

2022-09-12 12:57 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md
> +      **Defaults to `false`.**
Fixed.

2022-09-12 13:00 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/listformat/listformat/index.md
> +          page.
```suggestion

        For information about this option, see the
        {{jsxref("Global_Objects/Intl", "Intl", "#Locale_negotiation", 1)}}
        page.
```

2022-09-12 13:06 UTC, teoli2003 approved these changes

2022-09-12 13:06 UTC, merged