Add section to all array methods about sparse arrays
mdn/content pull request #20568
Opened 2022-09-12 00:28 UTC by Josh-Cena

### Description

This begins a new journey of me aligning ALL array pages. The first one I'm doing is to consistently note how these methods interact with empty slots.

### Motivation

### Additional details

### Related issues and pull requests

2022-09-21 03:00 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/every/index.md
> +console.log([1, , 3].every((x) => x !== undefined)); // true
So I'm half way through reviewing this and it looks great, but I'm not sure about this example. It seems only to show that it doesn't treat empty slots as `undefined`, not that it ignores them. Wouldn't something like:

```js
console.log([2, , 2].every((x) => x === 2)); // true 
```

...be clearer?

I think I will have similar comments for some of the other examples, like the one for `filter()`, so thought it was worth bringing up now.

2022-09-22 21:19 UTC, Josh-Cena commented
FWIW it's hard for me to tell which examples are illustrative enough and I can use some help from a second pair of eyes.

2022-09-23 19:03 UTC, wbamberg requested changes
Thanks @Josh-Cena , this is great. Lots of comments but I have been very picky and many of them are more like suggestions.

2022-09-23 19:03 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/tolocalestring/index.md
> +The `toLocaleString()` method does not special case [sparse arrays](/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays). Empty slots are visited as if they have value `undefined`.
Unlike [the description for `join`](https://pr20568.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join#description), we don't actually describe the behaviour for `null` or `undefined` here.

2022-09-23 19:03 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/tostring/index.md
> +Following the behavior of `join()`, `toString()` treats empty slots the same as `undefined` and produces an extra separator:
Like `join()`, `toString()` treats empty slots the same as `undefined` and produces an extra separator:
```

2022-09-23 19:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/findlastindex/index.md
> -### Find index using arrow function
Yes... It doesn't really make sense now.

2022-09-23 19:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/index.md
> +### Creating an array using the result of a match
Yeah. I don't know either. I'm okay to remove this. I think it demonstrates how some built-in operations return arrays; an interesting thing about the `exec()` array is that there are extra properties.

2022-09-23 19:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/join/index.md
> +console.log([1, , 3].join()); // '1,,3'
```suggestion
console.log([1, , 3].join()); // '1,,3'
console.log([1, undefined, 3].join()); // '1,,3' 
```

2022-09-23 19:12 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/some/index.md
> +console.log([1, , 3].some((x) => x === undefined)); // false
```suggestion
console.log([1, , 3].some((x) => x === undefined)); // false
console.log([1, , 1].some((x) => x !== 1)); // false
console.log([1, undefined, 1].some((x) => x !== 1)); // true
```

2022-09-23 19:13 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/splice/index.md
> +console.log(arr); // [1, empty, 3]
```suggestion
const arr = [1, 3, 4, , 6];
console.log(arr.splice(1, 2)); // [empty, 3]
console.log(arr); // [1, 4, empty, 6]
```

2022-09-23 19:22 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/group/index.md
> +console.log([1, , 3].group((x) => x)); // { 1: [1], undefined: [undefined], 3: [3] }
Ummm, looks the same to me...

2022-09-23 19:27 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/splice/index.md
> +The `splice()` method skips empty slots. If the deleted portion is [sparse](/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays), the returned array is sparse as well, with empty slots
Thanks for pointing out. Now I don't understand it either 😄

2022-09-23 19:27 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/tostring/index.md
> +Following the behavior of `join()`, `toString()` treats empty slots the same as `undefined` and produces an extra separator:
I'm using "Following the behavior of", because it's not just "like" `join()`—it _is_ `join()`.

2022-09-23 19:50 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/index.md
> +### Creating an array using the result of a match
I don't think it is needed for this PR but think it should be removed unless you would like to keep it. It doesn't look very relevant and this is already a huge page.

2022-09-23 20:46 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/group/index.md
> +console.log([1, , 3].group((x) => x)); // { 1: [1], undefined: [undefined], 3: [3] }
Fair enough.

2022-09-23 20:54 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/index.md
> +### Creating an array using the result of a match
Let's keep it till the next refactor. I'll continue to iterate on these array pages.

2022-09-23 21:10 UTC, wbamberg approved these changes
👍 all right, thank you @Josh-Cena for this excellent improvement!

2022-09-23 21:10 UTC, merged

2022-09-23 21:14 UTC, Josh-Cena commented
Welcome! There's quite a lot to do for these array pages...