Document that host permissions can be used instead of the "tabs" permission
mdn/content pull request #2057
Opened 2021-02-03 17:56 UTC by Rob--W

Documentation for change from https://bugzilla.mozilla.org/show_bug.cgi?id=1679688

Fixes #1732.

2021-02-04 19:04 UTC, rpl requested changes
@Rob--W thanks for chasing down the many multiple places where we should mention this ability.

Besides the few comments below, I do have one more comment:
In the [host permissions section of the permissions doc page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) that we are linking in most of the changes in this PR there is a list of the extra privileges that an host permission does grant (the list that follows `The extra privileges include:`) and I was expecting an addition to that list in this PR.

I'm missing it or isn't yet part of the changes in this PR? (imho we should add an entry for this new ability in that list).

2021-02-04 20:11 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> +    <li>Access to these properties by host permissions is supported since Firefox 86 and Chrome. In Firefox 85 and earlier, the "tabs" permission was required instead.</li>
I am conscious of the space change, and for consistency two space changes are better than one. I'm editing the line anyway, so I didn't mind introducing the extra space

2021-02-04 20:31 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> +    <li>Access to these properties by host permissions is supported since Firefox 86 and Chrome. In Firefox 85 and earlier, the "tabs" permission was required instead.</li>
Support for it was added in Chrome at some point, several years ago.

I just bisected and apparently it was in Chrome 50.

2021-02-05 11:17 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> +    <li>Access to these properties by host permissions is supported since Firefox 86 and Chrome. In Firefox 85 and earlier, the "tabs" permission was required instead.</li>
I also prefer two spaces indentation, but I'm not sure it is worth it if the rest of the file is not consistently using the same convention. anyway it is not really a big deal.

2021-02-05 11:26 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> +    <li>Access to these properties by host permissions is supported since Firefox 86 and Chrome. In Firefox 85 and earlier, the "tabs" permission was required instead.</li>
thanks for tracking that down.

2021-02-05 11:27 UTC, rpl approved these changes
lgtm, thanks Rob!

2021-02-09 16:59 UTC, merged