Run Prettier on HTML code fences, part 7
mdn/content pull request #20667
Opened 2022-09-13 14:06 UTC by OnkarRuikar

Adding to #20638

The PR focuses only on HTML code fences.

Idea is to gradually prettify all the CSS code fences before the full automation.

2022-09-13 19:47 UTC, teoli2003 requested changes

2022-09-13 19:47 UTC, teoli2003 commented on files/en-us/web/api/svgtransformlist/index.md
> +  </script>
This is weird. I think the original should be kept, at least for the moment.

2022-09-13 23:45 UTC, OnkarRuikar commented on files/en-us/web/api/selection/rangecount/index.md
>  <table>
Good catch!
I’ve fixed this in a separate commit. To make multiline suggestion on Github hold mouse click on the blue icon and drag down to select required lines.

2022-09-13 23:46 UTC, OnkarRuikar commented on files/en-us/web/api/svgtransformlist/index.md
> +
```suggestion
```

2022-09-14 12:11 UTC, teoli2003 approved these changes

2022-09-14 12:12 UTC, merged