chore: Opt-in cleaned folders and CI for Prettier
mdn/content pull request #20674
Opened 2022-09-13 14:49 UTC by nschonni

These were removed from the Huskier PR, so resubmitting to review separately

2022-09-13 14:53 UTC, nschonni commented
After this or with this one, we could add the prettier call to the Auto PR fix job

2022-09-14 07:58 UTC, caugner approved these changes
LGTM, but the only problem I see is that those "already fixed" files don't get auto-fixed via lint-staged yet, so the failing test may be a surprise for contributors.

2022-09-14 08:04 UTC, teoli2003 commented
We want to discuss the plan to move forward with Prettier once everybody returns from the all-hand Mozilla trip (for some), and holidays (for others).

Meanwhile, we can fix content to match the output of Prettier, getting experience with the limitations of the tool (weirdness with inline elements, CDATA and MathML code "minimization", a few oddities with CSS, …), but we shouldn't move forward with automation before the plan has been discussed on mdn/mdn-community/discussions and agreed.

2022-09-14 14:35 UTC, nschonni commented
> LGTM, but the only problem I see is that those "already fixed" files don't get auto-fixed via lint-staged yet, so the failing test may be a surprise for contributors.

When these folders are opted back in, lint-stage/husky will autofix any regressions going forward

2022-10-24 14:06 UTC, nschonni commented
Gave this a rebase, and updated the globs for the global job and scripts to run for prettier changes. Still green with the now opted in folders

2023-02-01 18:33 UTC, nschonni commented
@queengooborg @bsmth noticed that #24046 landed. Maybe you're ready to look at this now

2023-02-03 09:21 UTC, bsmth commented on .prettierignore
> +!/files/en-us/games/**/*.md
What do you think about getting rid of the leading slash for these paths? e.g.

```
!files/en-us/games/**/*.md
```

2023-02-03 09:22 UTC, bsmth commented on .prettierignore
> +!/files/en-us/webassembly/**/*.md
Q: Have `/related`, `/web`, `/games` and `/webassembly` had a full pass already?

2023-02-03 09:25 UTC, bsmth commented on .github/workflows/pr-check_markdownlint.yml
> +        uses: tj-actions/changed-files@v29.0.5
I think we had consistent problems with this action that weren't resolved after fixes landed in that repo. We [moved to this approach](https://github.com/mdn/content/blob/221a88897598f0ad73f3e80c4a6211992264dcf5/.github/workflows/pr-check_markdownlint.yml#L17-L29) although I dislike copy pasting it everywhere. Added some [initial thoughts on it here](https://github.com/mdn/translated-content/pull/4191#discussion_r1095532187).

2023-02-03 20:03 UTC, nschonni commented on .prettierignore
> +!/files/en-us/webassembly/**/*.md
yeah, I did them awhile ago before this PR. It's also checked by the green CI here

2023-02-03 20:04 UTC, nschonni commented on .prettierignore
> +!/files/en-us/games/**/*.md
I kept if consistent because the `/` is needed for the root path, and the absolute gives an explicit match

2023-02-03 20:04 UTC, nschonni commented on .github/workflows/pr-check_markdownlint.yml
> +        uses: tj-actions/changed-files@v29.0.5
Right, this was from before that switch over, I'll take a look at the other one and use the new matcher

2023-02-06 09:46 UTC, bsmth commented on .prettierignore
> +!/files/en-us/games/**/*.md
OK good to know. If this is the preferred way, we should continue with that convention when adding other paths (note to self & @queengooborg).

2023-02-07 07:14 UTC, nschonni commented
@teoli2003 let me know when to rebase this, as I'm picking up conflicts with all the PRs your landing right now

2023-02-10 17:23 UTC, nschonni commented
@queengooborg @teoli2003 @bsmth note the failure from a previously cleaned up folder. We need this CI backing or things will continue to creep back in.

2023-02-11 03:45 UTC, queengooborg requested changes
There are some additional changes included in this PR that aren't entirely about just opting into using Prettier to scan the files, such as adding the slashes into the `.prettierignore`, sorting entries in other workflows and renaming jobs.

Additionally, I think that we can combine the Markdownlint and Prettier command runs into a single workflow job.

2023-02-11 03:45 UTC, queengooborg commented on .github/workflows/pr-check_markdownlint.yml
> +          yarn prettier -c ${files_to_lint}
```suggestion
      - name: Lint markdown files
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          yarn markdownlint-cli2 ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Prettier markdown files
        run: yarn prettier -c ${{ steps.changed-files.outputs.all_changed_files }}
```

2023-02-11 04:05 UTC, nschonni commented
> There are some additional changes included in this PR that aren't entirely about just opting into using Prettier to scan the files, such as adding the slashes into the `.prettierignore`, sorting entries in other workflows and renaming jobs.

I've minimized the diff on the other job to just add the trigger on `.prettier*` changes. For the slash discussion, i've "unresolved the previous discussion about that one so it's visible again


> Additionally, I think that we can combine the Markdownlint and Prettier command runs into a single workflow job.

I added your suggestion, then I realized there was a bug from when I had changed from the old "diff files" action to the current one, so I rebased, but kept the collasped single job

2023-02-11 04:08 UTC, queengooborg commented
> I've minimized the diff on the other job to just add the trigger on .prettier* changes.

Thank you, much appreciated!

> For the slash discussion, i've "unresolved the previous discussion about that one so it's visible again

Sounds good!  I opened up #24338 to add them into our config; just waiting on review for it!

> added your suggestion, then I realized there was a bug from when I had changed from the old "diff files" action to the current one, so I rebased, but kept the collasped single job

👍

2023-02-11 04:33 UTC, nschonni commented
@queengooborg I cherry-picked your ignore changes from https://github.com/mdn/content/pull/24338 and fixed an issue on one of the ignores. I fixed the single unrelated failing file, but it would get fixed by the auto-PR job after this anyway

2023-05-19 23:41 UTC, queengooborg approved these changes
Since there was only six files left in need of formatting, I've gone ahead and just formatted them now so we can get this landed!

2023-05-19 23:43 UTC, merged