Clarify overscroll-behaviour for iframe elements
mdn/content pull request #20706
Opened 2022-09-14 06:06 UTC by temach

### Description

Clarify that using overscroll-property on iframe elements does not have an effect.

### Motivation

It might seem that overscroll-property can solve scroll-chaining for iframes, but iframes with scroll bars are not *scroll container elements*, so this property does not apply. This was surprising and I wasted a lot of time to find out why.

### Additional details

[firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1683128) and [chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=813094).

### Related issues and pull requests

2022-09-16 00:03 UTC, wbamberg requested changes
Thanks for your PR!

It's definitely worth noting this, but I don't think it needs **Note** styling or references to those bugs.

2022-09-16 00:03 UTC, wbamberg commented on files/en-us/web/css/overscroll-behavior/index.md
> +> **Note:** This property does not stop scroll chaining for iframes, see [firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1683128) and [chrome issue](https://bugs.chromium.org/p/chromium/
This 
```suggestion
Note that this property only applies to {{Glossary("Scroll_container", "scroll containers")}}. In particular, since an [`<iframe>`](/en-US/docs/Web/HTML/Element/iframe) is not a scroll container, this property cannot be used to stop scroll chaining for iframes.
```

2022-09-20 22:07 UTC, estelle approved these changes
Thanks!

2022-09-22 21:26 UTC, wbamberg approved these changes
👍 thank you!

2022-09-22 21:26 UTC, merged