docs: changed "deadbeef" to "cafebabe"
mdn/content pull request #20701
Opened 2022-09-14 04:03 UTC by naz

### Description

Changed use of resource hash example from "deadbeef" to "cafebabe".

### Motivation

My imagination is a bit too graphic and can imagine there are more people like me out there who might get triggered. Changed the sample to something a bit more positive ^_^

### Additional details

Reference of other hexspeak phrases - https://en.wikipedia.org/wiki/Hexspeak

2022-09-14 22:10 UTC, LPardue commented
If this is going to be changed, I think it would be better to use a more inclusive value than the one currently suggested.

2022-09-15 18:40 UTC, Josh-Cena commented
I won't argue that "CAFEBABE" doesn't age well today, but "CAFEBABE" and "DEADBEEF" are the only well-known hexspeaks. Changing it to something else would make it not much more meaningful than "12B9B0A1".

2022-09-15 18:48 UTC, LPardue commented
The argument to include hexspeak at all is weak. This is an article about HTTP caching and ETags can contain any value specified in https://www.rfc-editor.org/rfc/rfc9110#name-etag, it isn't constrained to hex. The fact the current string doesn't include a `0x` prefix means the page is just confusing and distracting.

[RFC 9110 includes examples](https://www.rfc-editor.org/rfc/rfc9110#section-8.8.3-5) of ETag. MDN already has [many examples of ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), I suggest reusing one of those.

2022-09-15 19:31 UTC, wbamberg requested changes
Thanks for your PR, @naz !

I agree, there's no reason we need to use hexspeak here.

2022-09-15 19:31 UTC, wbamberg commented on files/en-us/web/http/caching/index.md
> +As an example, if a hash value is used for the `ETag` header and the hash value of the `index.html` resource is `cafebabe`, the response will be as follows:
```suggestion
As an example, if a hash value is used for the `ETag` header and the hash value of the `index.html` resource is `33a64df5`, the response will be as follows:
```

2022-09-15 19:31 UTC, wbamberg commented on files/en-us/web/http/caching/index.md
> +If-None-Match: "cafebabe"
```suggestion
If-None-Match: "33a64df5"
```

2022-09-15 23:52 UTC, naz commented
Sorry, didn't mean to star a holy war :sweat_smile: It's nice to use cool names whenever possible to make things memorable. In here I don't think having any of the hexspeak phrases would benefit to the technical value of the document. Will change the values to a random hex proposed by @wbamberg :+1:

2022-09-16 00:01 UTC, schalkneethling commented
Thank you for your contribution, and welcome to the community @naz 🎉

2022-09-16 00:02 UTC, LPardue commented
Thanks @naz

2022-09-16 00:06 UTC, wbamberg commented on files/en-us/web/http/caching/index.md
> +ETag: "cafebabe"
```suggestion
ETag: "33a64df5"
```

2022-09-16 00:13 UTC, wbamberg approved these changes
👍 no worries @naz , and thanks for your PR!

2022-09-16 00:13 UTC, merged