Update some links from RFC 7234 to RFC 9111
mdn/content pull request #20747
Opened 2022-09-15 00:14 UTC by LPardue

### Description

There were some specific links to RFC 7234, these can be updated.

### Motivation

There are new revisions of HTTP specs.

### Additional details

### Related issues and pull requests

2022-09-15 05:56 UTC, teoli2003 requested changes

2022-09-15 05:56 UTC, teoli2003 commented on files/en-us/web/http/headers/cache-control/index.md
> +- [RFC 9110 – HTTP Caching](https://httpwg.org/specs/rfc9111.html#calculating.freshness.lifetime)
There is an incoherence here between the label _RFC 9110 – HTTP Caching_ and the link (a deep link to RFC 9111)

I think this is the correct link:
```suggestion
- [RFC 9111 – HTTP Caching](https://httpwg.org/specs/rfc9111.html)
```

2022-10-10 21:14 UTC, Josh-Cena commented
Hi @LPardue could you confirm with https://github.com/mdn/content/pull/20747#discussion_r971555542?

2022-10-11 00:23 UTC, LPardue commented on files/en-us/web/http/headers/cache-control/index.md
> +- [RFC 9110 – HTTP Caching](https://httpwg.org/specs/rfc9111.html#calculating.freshness.lifetime)
whoops, yes good catch, your suggestion is correct and we should go with that

2022-10-11 00:23 UTC, LPardue commented
thanks for the ping. The suggestion is correct, please commit it at your pleasure.

2022-10-11 06:36 UTC, teoli2003 approved these changes

2022-10-11 06:38 UTC, merged