ci: run Prettier for Markdown auto-prs and checks
mdn/content pull request #20752
Opened 2022-09-15 02:02 UTC by nschonni

Add pretttier to the global Markdown linting CI jobs and auto PR.
This is primarily an no-op, but I've also left the `embedded-lanague-formatting` off, so the code fences are cleaned run.

2022-10-24 13:43 UTC, caugner requested changes

2022-10-24 13:43 UTC, caugner commented on .github/workflows/markdown-lint-fix.yml
> +      - name: Markdownlint check markdown files
Isn't the older name more accurate, because *now* we're running both prettier and markdownlint?

And/or would it make sense to split it up into two steps like here:
https://github.com/mdn/content/blob/7e0fda217661a3901ca1079ac825602d82fc3bca/.github/workflows/markdown-lint.yml#L32-L39

2022-11-11 17:40 UTC, nschonni commented on .github/workflows/markdown-lint-fix.yml
> +      - name: Markdownlint check markdown files
I changed back the name

2023-03-02 14:09 UTC, nschonni commented
Closing in favour of https://github.com/mdn/content/pull/20674

2023-03-02 14:09 UTC, closed without merging