DRAFT: Cascade Layer building block tutorial
mdn/content pull request #20755
Opened 2022-09-15 06:08 UTC by estelle

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +  3. **Origin:** Sort rules by author, user, or user-agent origin and by importance
```suggestion
  3. **Origin:** Sort rules by author, user, or user-agent origin and by importance
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +  4. **Layers:** Within each origin importance bucket, sort by cascade layer. The layer order for normal declarations is from first layer created to last, followed by unlayered normal styles. This or
```suggestion
  4. **Layers:** Within each origin importance bucket, sort by cascade layer. The layer order for normal declarations is from first layer created to last, followed by unlayered normal styles. This order is inverted for important styles.
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +For each step, only the declarations "still in the running” move on to "compete” in the next step. If only one declaration is in the running, the following steps are moot.
```suggestion
For each step, only the declarations "still in the running” move on to "compete" in the next step. If only one declaration is in the running, the following steps are moot.
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +There are three [cascade origin types](/en-US/docs/Web/CSS/cascade#origin_types): user-agent stylesheets, user stylesheets, and author stylesheets. The browser sorts each declaration by origin and im
```suggestion
There are three [cascade origin types](/en-US/docs/Web/CSS/Cascade#origin_types): user-agent stylesheets, user stylesheets, and author stylesheets. The browser sorts each declaration by origin and importance into size origin buckets. There are eight levels of precedence: the six origin buckets, properties that are transitioning, and properties that are animating. The order of precedence goes from normal user-agent styles, which have the lowest precedence, to styles within currently applied animations, to important user-agent styles, and styles being transitioned, which have the highest precedence:
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +For each property, the declaration that "wins” is the one from the origin with precedence based on the weight (normal or important). Ignoring layers for the moment, the value from the origin with gre
```suggestion
For each property, the declaration that "wins" is the one from the origin with precedence based on the weight (normal or important). Ignoring layers for the moment, the value from the origin with the greatest precedence gets applied. If the winning origin has more than one property declaration for an element, the [specificity](/en-US/docs/Web/CSS/Specificity) of the selectors for those competing property values are compared. Specificity is never compared between selectors from different origins. This will be reiterated a few times as this fundamental concept really needs to be understood.
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +In the below example, we have two links: The first has no author styles applied, so all user-agent styles are applied. The second has [`text-decoration`](/en-US/docs/Web/CSS/text-decoration) and [`co
```suggestion
In the below example, we have two links: The first has no author styles applied, so all user-agent styles are applied. The second has [`text-decoration`](/en-US/docs/Web/CSS/text-decoration) and [`color`](/en-US/docs/Web/CSS/color) set by author styles even though the selector in the author stylesheet has a specificity of `0-0-0`. The reason author styles "win" is because when there are conflicting styles from different origins (layers aren't in play yet), the rules from the origin with precedence are applied, no matter what the specificity is in the origin that doesn’t have precedence.  
```
```suggestion
In the below example, we have two links: The first has no author styles applied, so all user-agent styles are applied. The second has [`text-decoration`](/en-US/docs/Web/CSS/text-decoration) and [`color`](/en-US/docs/Web/CSS/color) set by author styles even though the selector in the author stylesheet has a specificity of `0-0-0`. The reason author styles "win" is because when there are conflicting styles from different origins (layers aren't in play yet), the rules from the origin with precedence are applied, no matter what the specificity is in the origin that doesn’t have precedence.  
```

2022-09-16 06:39 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +We now understand "cascade origin precedence,” but what is "cascade layer precedence”? We will answer that question by addressing what cascade layers are, how they are ordered, and how styles are ass
```suggestion
We now understand "cascade origin precedence," but what is "cascade layer precedence"? We will answer that question by addressing what cascade layers are, how they are ordered, and how styles are assigned to cascade layers. We'll cover regular layers, nested layers, and anonymous layers. Let's first discuss what cascade layers are and what issues they solve.
```

2022-09-19 14:02 UTC, dipikabh commented
Thanks, @estelle! 🙌
I'll start reviewing this now.

2022-09-20 16:00 UTC, dipikabh requested changes
Finishing part 1 here. I'll resume looking at the remaining bit shortly.

2022-09-20 20:15 UTC, estelle commented
thanks. if i missed something, please link to the comment as right now it is looking all good to me. thanks.

2022-09-20 20:28 UTC, dipikabh requested changes
This is the remaining review. I think some sections can do well with some more sub-headings to define a structure for the content because otherwise it is too verbose - I can do that in the next round.

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +We then declare our fifth layer, which is our second anonymous layer.
```suggestion
We then declared the fifth layer, which is the second anonymous layer.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +We now have a total of five layers, `layout, <anonymous(01)>, theme, utilities, <anonymous(02)>` – in that order - with a sixth, implicit layer of unlayered styles containing `body` and `main` color
```suggestion
So that's how there's a total of five layers, : `layout`, `<anonymous(01)>`, `theme`, `utilities`, and `<anonymous(02)>` – in that order - with a sixth, implicit layer of unlayered styles containing `body` and `main` color declarations.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +If we add some CSS, reusing an existing layer name, the CSS gets appended to the already existing layer. It does not create a new layer:
```suggestion
If we add some CSS by reusing an existing layer name, the CSS gets appended to the already existing layer. It does not create a new layer.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Try moving the last line, the `@layer site, page;` to make it the first line. What happens?
```suggestion
Try moving the last line, `@layer site, page;`, to make it the first line. What happens?
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The [`@import`](/en-US/docs/Web/CSS/@import) rule allows users to import style rules from other style sheets either directly into a CSS file or into a {{htmlelement('style')}}. Generally, when import
```suggestion
The [`@import`](/en-US/docs/Web/CSS/@import) rule allows users to import style rules from other style sheets either directly into a CSS file or into a {{htmlelement('style')}} element. Generally, when importing stylesheets, the `@import` statement must be defined before any CSS styles within the stylesheet or `<style>` block. An exception to the "@import must come first" rule is that `@import` may be preceded by an `@layer` at-rule that creates one or more layers without assigning any styles.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +You can import more than one CSS file into a single layer. The following imports two separate files into a single `social` layer:
```suggestion
You can import more than one CSS file into a single layer. The following declaration imports two separate files into a single `social` layer:
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +There is no equivalent, yet, for the {{HTMLElement('link')}} method of linking stylesheets. Creating a `layer` attribute is being considered, but, as of this writing (September 2022), there is no spe
```suggestion
There is no equivalent of the {{HTMLElement('link')}} method of linking stylesheets. Use `@import` to import a stylesheet into a layer when you can’t use `@layer` within the stylesheet.
```
We need to avoid time-specific verbiage.

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Do you have to worry if a 3rd party stylesheet you're importing into a new layer has layers? No. The layers become nested layers. Nested layers are layers within a named or anonymous layer.
```suggestion
Nested layers are layers within a named or anonymous layer. If you're importing a third party stylesheet that has layers into a new layer, you don't need to worry. The imported layers become nested layers. 
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Nested layers are created the same ways as described for regular layers above. They can be created using `@layer` followed by the names of one or more layers; the nested layer being a period-separate
```suggestion
Nested layers are created using the same methods as described for regular layers. They can be created using `@layer` followed by the names of one or more layers, the nested layer being a period-separated list of layer names.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +If you nest a `@layer` block at-rule inside `@layer` block at-rule, with or without a name, the nested block becomes a nested layer. Similarly, when a stylsheet is imported with an `@import` declarat
```suggestion
If you nest a `@layer` block at-rule inside another `@layer` block at-rule, with or without a name, the nested block becomes a nested layer. Similarly, when a stylsheet is imported with an `@import` declaration containing the `layer` keyword or `layer()` function, the styles get assigned to that named or anonymous layer. If that import contains layers, those layers become nested layers within that anonymous or named layer.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +In the first line we imported `components-lib.css` into the `components` layer. If that file included any layers, named or not, those layers are nested layers withing the components layer. Named laye
```suggestion
In the first line, we imported `components-lib.css` into the `components` layer. If that file contains any layers, named or not, those layers become nested layers within the `components` layer. Named layers can be added via `components.layerName`. As mentioned before, unnamed layers cannot be accessed.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The second line imports `dialog.css` into the `dialog` layer, which is a sub-layer of `components`. `dialog` gets created as the last layer within the `components` layer, unless `components-lib.css`
```suggestion
The second line imports `dialog.css` into the `dialog` layer, which is a sub-layer of `components`. `dialog` gets created as the last layer within the `components` layer, unless `components-lib.css` already had a `dialog` layer. If `components-lib.css` had layers, all the layers become nested layers. If one of the layers was `dialog`, that layer is now accessible via `components.dialog`, and styles from `dialog.css` are appended to it.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +This would create a single layer named `example` containing some declarations and five nested layers --  `example.layout`, `example.<anonymous(01)>`, `example.theme`, `example.utilities`, and `exampl
```suggestion
This would create a single layer named `example` containing some declarations and five nested layers -  `example.layout`, `example.<anonymous(01)>`, `example.theme`, `example.utilities`, and `example.<anonymous(02)>`.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Layer order matters. A lot. In the same way the cascade sorts by origin and importance, the cascade sorts each CSS declaration by origin layer and importance as well.
```suggestion
Layer order matters. A lot. In the same way as the cascade sorts by origin and importance, the cascade sorts each CSS declaration by origin layer and importance.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The layer order precedence is the order in which layers are created. If the author styles have two declared layers, (assuming there are no layers in C.css), the order of precedence is as follows:
```suggestion
The layer order precedence is the order in which layers are created. If the author styles have two declared layers, and assuming there are no layers in `C.css`, the order of precedence would be as follows:
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +In this example, there are two named layers, unlayered styles, an inline styles.
```suggestion
In this example, there are two named layers, unlayered styles and inline styles.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The two styles declared only within layers are `font-style`, with normal importance, and `font-weight` with an `!important` flag. For normal styles, the B layer, declared last, overrides styles in th
```suggestion
The two styles declared only within layers are `font-style`, with normal importance, and `font-weight` with an `!important` flag. For normal styles, the B layer, declared last, overrides styles in the earlier declared layer A. For normal styles, later layers have precedence over earlier layers. The order of precedence is reversed for important styles. For the important `font-weight` declarations, layer A, being declared first, has precedence over the last declared layer B.
```

2022-09-20 20:28 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +You can reverse the layer order by changing the first line from `@layer A, B;`, to `@layer B, A;`. Try that. Which styles get changed by this, and which stay the same? Why?
```suggestion
You can reverse the layer order by changing the first line from `@layer A, B;` to `@layer B, A;`. Try that. Which styles get changed by this, and which stay the same? Why?
```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +For each step, only the declarations "still in the running” move on to "compete" in the next step. If only one declaration is in the running, the following steps are moot.
```suggestion
For each step, only the declarations "still in the running" move on to "compete" in the next step. If only one declaration is in the running, the following steps are moot.
```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### Origin and specificity
```suggestion

### Origin and specificity

```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### Origin and specificity
```suggestion

### Origin and specificity

```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +In the example below, there are two links. The first has no author styles applied, so all user-agent styles are applied. The second has [`text-decoration`](/en-US/docs/Web/CSS/text-decoration) and [`
```suggestion
In the example below, there are two links. The first has no author styles applied, so all user-agent styles are applied. The second has [`text-decoration`](/en-US/docs/Web/CSS/text-decoration) and [`color`](/en-US/docs/Web/CSS/color) set by author styles even though the selector in the author stylesheet has a specificity of [`0-0-0`](/en-US/docs/Web/CSS/Specificity#selector_weight_categories). The reason why author styles "win" is because when there are conflicting styles from different origins (layers aren't in play yet), the rules from the origin with precedence are applied, irrespective of the specificity in the origin that doesn't have precedence.
```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Specificity conflicts can escalate quickly. A web developer may create a "quick fix” by adding an `!important` flag. While this may feel like a easy solution, it often just moves the specificity war
```suggestion
Specificity conflicts can escalate quickly. A web developer may create a "quick fix" by adding an `!important` flag. While this may feel like a easy solution, it often just moves the specificity war from normal to important declarations.
```

2022-09-21 07:06 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +- Within each layer, a team can create nested layers. For example, a component library can be added to a separate layer creating an additional origin and removing any need for competing specificity.
```suggestion
- Within each layer, a team can create nested layers. For example, a component library can be added to a separate layer creating an additional origin and removing any need for competing specificity. Alternatively, the component team can include each component in a separate nested layer. The ability to nest layers is very useful for component library, framework, and third-party widget developers.

```

2022-09-21 18:12 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +There is no equivalent of the {{HTMLElement('link')}} method of linking stylesheets. Use `@import` to import a stylesheet into a layer when you can’t use `@layer` within the stylesheet.
```suggestion
There is no equivalent of the {{HTMLElement('link')}} method of linking stylesheets. Use `@import` to import a stylesheet into a layer when you can't use `@layer` within the stylesheet.
```

2022-09-21 18:15 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +In this example, there are two named layers, unlayered styles and inline styles.
```suggestion
In this example, there are two named layers, unlayered styles, and inline styles.
```

2022-09-22 18:13 UTC, dipikabh requested changes

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +
there were a lot of key rules that were highlighted here. Can we summarize them in a list in one place, something like:
- Important inline styles override all layered and unlayered normal and important author styles. There is no way for author styles to override important inline styles.
- For normal non-inline styles, unlayered styles have precedence.
and so on..

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +
```suggestion
### Precedence order of regular cascade layers
```
adding this here so that the next h3 heading "Precedence order of nested layers" is not a lone h3

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### Precedence order of nested layers
```suggestion
### Precedence order of nested cascade layers
```

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The cascade precedence order for nested layers is similar to regular layers, but contained within the layer. The precendence order is based on order of nested layer creation. Non-nested styles in the
```suggestion
The cascade precedence order for nested layers is similar to that of regular layers, but contained within the layer. The precedence order is based on the order of nested layer creation. Non-nested styles in a layer have precedence over nested normal styles, with the precedence order reversed for important styles. Specificity weight between nested layers does not matter, though it does matter for conflicting styles within a nested layer.
```

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +The following creates and adds styles to the `components` layer and `components.narrow` nested layer, and creates and appends styles to a new `components.wide` layer:
```suggestion
The following creates and adds styles to the `components` layer and `components.narrow` nested layer and creates and appends styles to a new `components.wide` layer:
```

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Because unlayered normal styles have precedence over layered normal styles, and, within a layer, non-nested styles have precedence over normal nested styles, `red` wins.
```suggestion
Because unlayered normal styles have precedence over layered normal styles, and within a layer, non-nested styles have precedence over normal nested styles, `red` wins over the other `theme` colors. 
```

2022-09-22 18:13 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +With important styles, layered styles take precendence over unlayered styles, with important styles in earlier declared layers having precedence over later declared layers. The order of nested layer
```suggestion
With important styles, layered styles take precedence over unlayered styles, with important styles in earlier declared layers having precedence over later declared layers. In this example, the order of nested layer creation is `components.narrow`, then `components.wide`, so important styles in `components.narrow` have precedence over important styles in `components.wide`, meaning `sans-serif` wins.
```

2022-09-22 18:41 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### Precedence order of regular cascade layers
```suggestion

### Precedence order of regular cascade layers

```

2022-09-22 20:51 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### @layer with layer names
I changed all three h3s

2022-09-22 21:12 UTC, estelle commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +
Look for "To summarize:" to see the summary list (that section is new)

2022-09-23 08:48 UTC, dipikabh requested changes
Very few things remaining and then it is good to go

2022-09-23 08:48 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +#### Issues nested cascade layers can solve
```suggestion
### Issues nested cascade layers can solve
```

2022-09-23 08:48 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +### Precedence order of regular cascade layers
```suggestion

```
duplicate heading

2022-09-23 08:48 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +- There is no way for author styles to override important inline styles (other than transitioning them, which is temporary).
```suggestion
- The order of layers is the order in which the layers are created.
- Once created, there is no way to change the layer order.
- Layer precedence or normal styles is the order in which the layers are created.
- Unlayered normal styles have precedence over normal layered styles.
- Layer precedence or important styles is reversed, with earlier created layers having precedence.
- All layered important styles have precedence over unlayered important (and normal) styles.
- Normal inline styles take precedence over all normal styles, layered or not.
- Important inline styles take precedence over all other styles, with the exception of styles being transitioned.
- There is no way for author styles to override important inline styles (other than transitioning them, which is temporary).
```

2022-09-23 08:48 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +
Thanks for adding this!

2022-09-25 08:34 UTC, estelle commented
i think we're good to go. Thank you for all your reviews.

2022-09-26 08:33 UTC, dipikabh approved these changes
Thanks for this work, @estelle! 🙌

2022-09-26 08:34 UTC, merged

2022-09-26 10:12 UTC, nschonni commented
@estelle FYI, if you re-run `yarn` to install the latest dependencies, Husky/Lint-staged should fix up those annoying line ending issues when you commit. Mentioning because it did it for me when I fixed a minor typo in the file 😄