Remove meta site
mdn/content pull request #20775
Opened 2022-09-15 18:00 UTC by bsmth

This PR removes the meta site and **migrates older content** across from the following pages:

```bash
meta
├── legacy
│   ├── adding-images.md            # DONE -> modified media (video) guide
│   ├── archiving.md                # DELETED -> looks obsolete so have omitted
│   ├── code-examples.md            # DONE -> modified Code_examples.md page
│   ├── compat-tables.md            # DONE -> modified Compatibility_tables.md page
│   ├── deployment-timeline.md      # DONE -> modified PR how-to page
│   ├── documentation-priorities.md # DONE -> added new page, we should revisit this!
│   ├── external-content.md         # DELETED -> we can revisit according to review comments
│   └── reuse.md                    # DONE -> modified Attrib_copyright_license.md page
└── writing
    └── style
        └── external-links.md       # DONE -> content already exists in contrib guidelines
```

__Redirects:__
I have replaced occurrences of links to `mdn-contributor-docs.mozilla.org` and **manually** removed a redirect in `files/en-us/_redirects.txt`. Please check that this looks okay!

__Notes:__
Continuing on the work from https://github.com/mdn/content/pull/20534

__TODO:__
- [x] merge `code-examples.md` with `Writing_guidelines/Page_structures/Code_examples`
- [x] merge `compat-tables.md` with `Writing_guidelines/Page_structures/Compatibility_tables`
- [x] merge `reuse.md` with `Attrib_copyright_license`
- [x] BCD specific things are now on the bcd repo -> point to docs there
- [x] Remove documentation priorities document
- [x] announce these pages are going
- [x] remove list of deployment times for repos with no automation yet
- [x] Redirect `https://mdn-contributor-docs.mozilla.org` to `https://developer.mozilla.org/en-US/docs/MDN`

2022-09-15 22:07 UTC, nschonni commented on files/en-us/_redirects.txt
> -/en-US/docs/MDN/Contribute/Documentation_priorities	https://mdn-contributor-docs.mozilla.org/legacy/documentation-priorities/
Should it go to `/en-US/docs/MDN/Community/Documentation_priority` like you used below

2022-09-15 22:09 UTC, nschonni commented
https://github.com/mdn/content/blob/main/netlify.toml can also probably go, if you update the web hooks.

2022-09-19 13:18 UTC, bsmth commented on files/en-us/_redirects.txt
> -/en-US/docs/MDN/Contribute/Documentation_priorities	https://mdn-contributor-docs.mozilla.org/legacy/documentation-priorities/
I've renamed the page slug to `Documentation_priorities` to match the original, so this change in the redirects looks fine to me.

2022-09-19 13:19 UTC, bsmth commented
> https://github.com/mdn/content/blob/main/netlify.toml can also probably go, if you update the web hooks.

done in https://github.com/mdn/content/pull/20775/commits/6b319ff474c7025b43f81a7d2bcc4eac9755b829

2022-09-19 16:40 UTC, dipikabh requested changes
Thanks for this work, @bsmth! 🙌 
Pointed out a few nits that could be fixed in the images_media file. I'll resume looking at the other files shortly.

2022-09-19 16:40 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/images_media/index.md
> +3. Run `filecheck` on each image which will complain if something's wrong.
```suggestion
3. Run `filecheck` on each image, which might complain if something's wrong.
```

2022-09-19 18:10 UTC, schalkneethling commented
Thanks so much for this work @bsmth and everyone involved 🙌

2022-09-20 09:57 UTC, dipikabh commented
There seems to be a duplicate of my review comments from yesterday! 🤷‍♀️

About:
> │   ├── code-examples.md            # DONE -> added new code examples page

We might not need to add a new page because this info already exists here: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples

2022-09-20 10:45 UTC, bsmth commented
> We might not need to add a new page (for `code-examples.md` and `compat-tables.md`)

Very good, I'll take a look at incorporating this info into existing pages.

2022-09-20 10:56 UTC, dipikabh requested changes, later dismissed

2022-09-20 10:56 UTC, dipikabh commented on files/en-us/mdn/community/pull_requests/index.md
> +The same tool can also be used to [see if `translated-content` is live](https://whatsdeployed.io/s/16d/mdn/translated-content) after merging a pull request in the [`transpated-content` repository](ht
Need to check with others if we use this tool and whether we should recommend it to contributors.

2022-09-20 10:56 UTC, dipikabh commented on files/en-us/mdn/community/pull_requests/index.md
> +After your pull request is merged, it can take up to 48 hours before merged changes are live on the [production site](https://developer.mozilla.org/), but it's usually quicker.
```suggestion
After your pull request on mdn/content repository is merged, it can take up to 48 hours before merged changes are live on the [production site](https://developer.mozilla.org/), but it's usually quicker.
```

2022-09-20 10:56 UTC, dipikabh commented on files/en-us/mdn/community/pull_requests/index.md
> +- Once deployment has occurred, it can take up to 24 hours for the CDN to invalidate caches and serve new content.
This spot can probably be used to publish deployment times for other repos. Something like:

```
To view your changes on other `mdn` repositories, you can expect the following timelines:
- mdn/browser-compat-data is build and released every Tuesday. You can expect to see your merged changes on MDN Web Docs on Wednesday.
- mdn/data - <todo>
- mdn/interactive examples - <todo>
```

2022-09-20 11:08 UTC, dipikabh commented
> │   ├── documentation-priorities.md # DONE -> added new page, we should revisit this!

This is covered here https://developer.mozilla.org/en-US/docs/MDN/Community/Issues/Issue_triage so a new page is not needed but the page itself needs to be reevaluated.

Not sure if we need a new page for this info: files/en-us/mdn/writing_guidelines/page_structures/external_content/index.md

2022-09-20 13:57 UTC, bsmth commented on files/en-us/mdn/community/pull_requests/index.md
> +The same tool can also be used to [see if `translated-content` is live](https://whatsdeployed.io/s/16d/mdn/translated-content) after merging a pull request in the [`transpated-content` repository](ht
Thanks, well spotted

2022-09-20 14:02 UTC, bsmth commented
> This is covered here https://developer.mozilla.org/en-US/docs/MDN/Community/Issues/Issue_triage so a new page is not needed but the page itself needs to be reevaluated.

Actually these are two separate documents

* Issue Triage (how to work on issues, references docs prio)
* Documentation Prio (how to tell which docs are high prio)

2022-09-20 18:51 UTC, Rumyra commented
This is amazing @bsmth thank you!!

Just a couple of things after a quick glance:

* BCD specific things are now on the bcd repo, the compatibility table page should just be about the macro and frontmatter
* We have content specific pages for issues and prs in the community section because they differ slightly from other repos in the org (the triage page in meta docs was content specific) - these are pretty much what we are defining now, but the info in the meta page should be captured
* I think we should do away with document priority actually - it'd be nice if all docs were equal (there's more to unpack here)
* Make sure redirects are in place (seems so and we're redirecting redirects but the yari tool should cover that)

2022-09-20 18:52 UTC, Rumyra commented
Also I love how all the tests are failing now - seems we've done good work here 👍

2022-09-22 12:51 UTC, bsmth commented on files/en-us/mdn/community/pull_requests/index.md
> +- Once deployment has occurred, it can take up to 24 hours for the CDN to invalidate caches and serve new content.
@dipikabh what was the outcome here? What should I put in place of the TODOs?

2022-09-22 14:34 UTC, dipikabh commented on files/en-us/mdn/community/pull_requests/index.md
> +- Once deployment has occurred, it can take up to 24 hours for the CDN to invalidate caches and serve new content.
I don't have a definitive answer here. Let's not add this info now. We'll revisit it via another PR.

2022-09-22 14:43 UTC, bsmth commented on files/en-us/mdn/community/pull_requests/index.md
> +- Once deployment has occurred, it can take up to 24 hours for the CDN to invalidate caches and serve new content.
Good idea, let me remove this list and create an issue to track this separately 👍🏻

2022-10-06 08:22 UTC, bsmth commented on files/en-us/mdn/community/pull_requests/index.md
> +- Once deployment has occurred, it can take up to 24 hours for the CDN to invalidate caches and serve new content.
Done in https://github.com/mdn/content/pull/20775/commits/dc084f51d415b504850e93ff6396f9d44efccfbd

2022-10-06 08:48 UTC, bsmth commented on files/en-us/mdn/community/pull_requests/index.md
> +The same tool can also be used to [see if `translated-content` is live](https://whatsdeployed.io/s/16d/mdn/translated-content) after merging a pull request in the [`transpated-content` repository](ht
removed in https://github.com/mdn/content/pull/20775/commits/52a822bf918badb8b6a337c444eae79164146fa3

2022-10-06 11:23 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/external_content/index.md
> +slug: MDN/Writing_guidelines/Page_structures/External_content
I seemed to have missed this new addition, sorry. You did mention it here:

> │   ├── external-content.md         # DONE -> added new external content page

Couple of points:
- I don't think this is really external content, just other repos under `mdn`. I don't think we should add a page for this content AND it should certainly not be under 'Page structures'. If at all, we can later document how `mdn/content` relies or is connected to other repos like `mdn/learning-area`, `mdn/interactive-examples`, etc. Because then that list would also mention `mdn/browser-compat-data`.
- If it is just about listing macros used for some content creation, we could add the missing information to the [Commonly used macros](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros) page. For example, a line about `\{{EmbedInteractiveExample}}` macro could be added to the [Code samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros#code_samples) section?
- We have the [How to use structured data](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/JSON_Structured_data) page that mentions `GroupData.json` and `\{{InheritanceDiagram}}` macro.

2022-10-06 11:24 UTC, dipikabh requested changes
Sorry, I missed looking at an addition. Let me know what you think.

2022-10-06 11:43 UTC, dipikabh approved these changes
Thanks, @bsmth for your work on this project! 🙌

2022-10-06 11:56 UTC, dipikabh commented
Should we redirect https://mdn-contributor-docs.mozilla.org to https://developer.mozilla.org/en-US/docs/MDN?

2022-10-06 11:57 UTC, bsmth commented
> Should we redirect https://mdn-contributor-docs.mozilla.org to https://developer.mozilla.org/en-US/docs/MDN?

We can do, indeed. Let me update the request for infra to do this

2022-10-12 08:01 UTC, bsmth commented
> Should we redirect https://mdn-contributor-docs.mozilla.org to https://developer.mozilla.org/en-US/docs/MDN?

A redirect is now active for this. We will merge this PR shortly and proceed with decommissioning the Netlify builds & site.

2022-10-12 12:04 UTC, bsmth commented
Merging this one now

2022-10-12 12:04 UTC, merged