Added colorspace to 2d context attributes
mdn/content pull request #20782
Opened 2022-09-15 20:40 UTC by dawei-wang

Added colorSpace to 2d context attributes 
Fixes mdn/content#15995

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-09-15 21:26 UTC, wbamberg requested changes
Thanks for your PR, @dawei-wang !

I think it would be good to list possible values for this attribute, as we do here, for example, for `contextType` above. From https://html.spec.whatwg.org/multipage/canvas.html#predefinedcolorspace, it looks like the values are "srgb" or "display-p3".

- The list of possible values can just be an unordered list and values should be quoted, as we do for `contextType` in this page.
- It looks like this is an optional attribute and "srgb" is the default. We should indicate optionality using the `{{optional_inline}}` macro call, as we do for instance for contextAttributes in this page. We should note next to the item for "srgb" that it is the default.
- It would be helpful to have a link to more detail on the color spaces. Unfortunately we don't seem to have resources for this on MDN, but maybe https://en.wikipedia.org/wiki/SRGB and https://en.wikipedia.org/wiki/DCI-P3 would do?

2022-09-16 01:09 UTC, dawei-wang commented
I have added possible values, indicated that this is an optional attribute, and links to more detail on the color spaces. I think that this is ready to be merged.

2022-09-16 01:28 UTC, wbamberg commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
> +        - `"display-p3"`
```suggestion
        - `"srgb"` selects the [sRGB color space](https://en.wikipedia.org/wiki/SRGB). This is the default value.
        - `"display-p3"` selects the [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3).
```

2022-09-16 01:29 UTC, wbamberg commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
> +- Available colorspaces: [sRGB color space](https://en.wikipedia.org/wiki/SRGB) and [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3)
```suggestion
- Available colorspaces: [sRGB color space](https://en.wikipedia.org/wiki/SRGB) and [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3).
```

2022-09-16 01:34 UTC, wbamberg approved these changes
👍 thank you @dawei-wang !

2022-09-16 01:35 UTC, merged