Redo examples in DOM introduction
mdn/content pull request #20795
Opened 2022-09-16 07:23 UTC by wbamberg

Fixes https://github.com/mdn/content/issues/20591, fixes https://github.com/mdn/content/issues/12415.

This PR replaces the existing example with two examples that show different basic DOM patterns.

2022-09-16 19:43 UTC, wbamberg commented
Maybe it's better to hide the CSS? Not sure, I'm not generally a fan of hiding code, but it is quite extraneous here.

2022-09-17 17:12 UTC, Josh-Cena commented
Yeah... The CSS looks really orthogonal to the DOM example IMO.

2022-09-19 21:24 UTC, wbamberg commented
> Yeah... The CSS looks really orthogonal to the DOM example IMO.

It is orthogonal, of course, but I'm very resistant to hiding code in examples even when it is not relevant, because it just seems, well, obscurantist. Like, people will see this and not understand how the layout is working, or copy it and not understand why the layout is not the same.

But yeah, I'm totally undecided here.

2022-09-19 21:33 UTC, Josh-Cena commented
It's like asking "how did they make the CSS interactive example editor?" Well the answer is: it's _somewhere_, but it's part of the infrastructure, not part of the content, so you should seek answer outside of the rendered webpage. It's just the case that the CSS is collocated with other displayed code here—that doesn't promote it from plumbing code to something of our interest.

2022-09-19 23:26 UTC, wbamberg commented
> It's like asking "how did they make the CSS interactive example editor?" 

I don't think it is like that. The interactive example editor is part of the page UI, not part of the example. Just like, the font used for headings in the page is part of the page UI. But the stuff inside the example iframe is part of the example code.

It _is_ like the output pane of the interactive example, and in those cases we do show CSS.

2022-09-19 23:43 UTC, hamishwillee commented
@wbamberg FWIW I wouldn't worry about it here. Yes the CSS is distracting in the [Adding a child element](https://pr20795.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Document_Object_Model/Introduction#adding_a_child_element)  example, but is not IMO so much as to be a "critical flaw".

It would be good to agree a systemic solution though. Hiding the content is one approach, but is not ideal for the reasons you have given. Don't know if it works in yari, but maybe a toggle would be a reasonable solution to the case:

----

#### CSS

The CSS below is hidden as it is not particularly relevant to this example.
<details>
  <summary>Click toggle to view CSS</summary>

```css
.container {
  display: flex;
  gap: 0.5rem;
  flex-direction: column;
}
button {
  width: 100px;
}
div.parent {
  border: 1px solid black;
  padding: 5px;
  width: 100px;
  height: 100px;
}
div.child {
  border: 1px solid red;
  margin: 10px;
  padding: 5px;
  width: 80px;
  height: 60px;
  box-sizing: border-box;
}
```
</details>

2022-09-20 02:35 UTC, wbamberg commented
> @wbamberg FWIW I wouldn't worry about it here. Yes the CSS is distracting in the [Adding a child element](https://pr20795.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Document_Object_Model/Introduction#adding_a_child_element) example, but is not IMO so much as to be a "critical flaw".
> 
> It would be good to agree a systemic solution though. Hiding the content is one approach, but is not ideal for the reasons you have given. Don't know if it works in yari, but maybe a toggle would be a reasonable solution to the case:
> #### CSS
> 
> The CSS below is hidden as it is not particularly relevant to understanding this example.
> Click toggle to view CSS

Yes, I wondered about this too. I like this idea but it's tricky because:

1. either you redefine `hidden` to mean this, which would break lots if places where people really do want to hide code blocks
2. or you define `hidden-by-default` or something, which adds more complexity to the authoring interface

Maybe (2) is OK though?

2022-09-20 03:12 UTC, hamishwillee commented
I was thinking of this being manual exactly as I defined it. But I like the idea of 2 even more because we could standardize the text and behaviour.

2022-09-20 04:27 UTC, wbamberg commented
> > It's like asking "how did they make the CSS interactive example editor?"
> 
> I don't think it is like that. The interactive example editor is part of the page UI, not part of the example. Just like, the font used for headings in the page is part of the page UI. But the stuff inside the example iframe is part of the example code.
> 
> It _is_ like the output pane of the interactive example, and in those cases we do show CSS.

Actually, on second thoughts, you are right, with the CSS interactive examples we do hide some of the CSS that participates in the examples (and HTML and sometimes JS). But the CSS examples are weird (in a good way IMO): they isolate one aspect of the "page" and change just that, to show its effect, hiding everything else. We're not trying to show a complete example, and it's pretty obvious that you couldn't just copy the one line of CSS and recreate the entire example.

2022-09-20 04:30 UTC, Josh-Cena commented
Hmmm, I never saw the live examples as "work out of the box when you paste to your editor" either. I always thought of them as lightweight demos that I don't have to PR another repo to implement.

2022-09-20 15:10 UTC, jpmedley requested changes

2022-09-20 15:10 UTC, jpmedley commented on files/en-us/web/api/document_object_model/introduction/index.md
> +In this example, inside a container {{HTMLElement("div")}}, we have a {{HTMLElement("textarea")}} and two {{HTMLElement("button")}} elements. When the user clicks the first button we set some text in
```suggestion
This example uses a {{HTMLElement("div")}} element containing a {{HTMLElement("textarea")}} and two {{HTMLElement("button")}} elements. When the user clicks the first button we set some text in the `<textarea>`. When the user clicks the second button we clear the text. We use:
```

2022-09-20 15:10 UTC, jpmedley commented on files/en-us/web/api/document_object_model/introduction/index.md
> +In this example, inside a container {{HTMLElement("div")}}, we have another {{HTMLElement("div")}} element and two {{HTMLElement("button")}} elements. When the user clicks the first button we create
```suggestion
This example uses a {{HTMLElement("div")}} element containing a {{HTMLElement("div")}} and two {{HTMLElement("button")}} elements. When the user clicks the first button we create a new element and add it as a child of the `<div>`. When the user clicks the second button we remove the child element. We use:
```

2022-09-20 16:57 UTC, jpmedley approved these changes

2022-09-20 16:57 UTC, merged