`pow()` - New CSS functional notation
mdn/content pull request #20838
Opened 2022-09-17 21:26 UTC by ramiy

### Description
Document the CSS `pow()` functional notation.

### Motivation
I'm documenting all the exponential CSS functions.

### Additional details
https://www.w3.org/TR/css-values-4/#exponent-funcs

### Related issues and pull requests
* Syntaxes - https://github.com/mdn/data/pull/593

2022-09-20 04:13 UTC, wbamberg requested changes
Thank you @ramiy !

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +spec-urls: https://www.w3.org/TR/css-values-4/#exponent-funcs
As with https://github.com/mdn/content/pull/20826 - if you intend to add spec URLs into BCD you should not also add it here AFAIK.

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +The **`pow()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) is an exponential function that returns the value of a base raised to the power of a number.
```suggestion
The **`pow()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) returns the value of a base raised to the power of a number.
```

("is an exponential function" seems like a tautology here)

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +The {{CSSxRef("exp")}} function is a special case of `pow()` where the value of the base is `e`.
I think this should link to a definition of `e`.

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +  - : A {{cssxref("&lt;number&gt;")}} representing the exponent number.
As for https://github.com/mdn/content/pull/20826: per spec, these are not numbers, but calculations that resolve to numbers, so I guess `pow(min(0, 1))` is allowed.

Would be good for the Syntax section to include a form like this.

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +Returns a {{cssxref("&lt;number&gt;")}} representing `base` taken to the power of a `number`.
```suggestion
Returns a {{cssxref("&lt;number&gt;")}} representing `base` taken to the power of `number`.
```

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +## Example
```suggestion
## Examples
```

2022-09-20 04:13 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +The `pow()` function can be useful for strategies like CSS Modular Scale, which relates all the font-sizes on a page to each other by a fixed ratio.
Great to see a concrete use case. Maybe make it a live sample, like:

````

### Modular scale for heading sizes

The `pow()` function can be useful for strategies like CSS Modular Scale, which relates all the font-sizes on a page to each other by a fixed ratio.

#### HTML

```html
<h1>Part 1</h1>

<h2>Chapter 1</h2>

<h3>Section 1</h3>

<h4>Subsection 1</h4>
```

#### CSS

```css
:root {
  --h1: calc(1rem * pow(1.5, 4));
  --h2: calc(1rem * pow(1.5, 3));
  --h3: calc(1rem * pow(1.5, 2));
  --h4: calc(1rem * pow(1.5, 1));
  --h5: calc(1rem * pow(1.5, 0));
  --h6: calc(1rem * pow(1.5, -1));
}

h1 {
  font-size: var(--h1);
}

h2 {
  font-size: var(--h2);
}

h3 {
  font-size: var(--h3);
}

h4 {
  font-size: var(--h4);
}
```

#### Result

{{EmbedLiveSample("Modular scale for heading sizes", "", 500)}}
````

2022-09-20 18:38 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +spec-urls: https://www.w3.org/TR/css-values-4/#exponent-funcs
Fixed!

2022-09-20 18:52 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +The {{CSSxRef("exp")}} function is a special case of `pow()` where the value of the base is `e`.
My PR on calc constants (`e`, `pi` etc.) is waiting to be merged.

2022-09-20 19:27 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +The {{CSSxRef("exp")}} function is a special case of `pow()` where the value of the base is `e`.
Thanks! Then I think we should block this PR on that one (otherwise we'll have to go back and fix this one anyway).

2022-09-20 20:04 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +The `pow()` function can be useful for strategies like CSS Modular Scale, which relates all the font-sizes on a page to each other by a fixed ratio.
Added an example based on the examples we added in CSS trigonometric functions.

2022-09-20 21:09 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +## Example
Sorry for you to have conflicting feedback. "Examples" is what we should have even when there is only one (it means among other things that our page structure is consistent).

2022-09-21 00:21 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +### Formal syntax
Formal syntax is an H2 (usually) as in https://developer.mozilla.org/en-US/docs/Web/CSS/alpha-value#formal_syntax.

2022-09-21 00:25 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +## Example
This should be "Examples", have an H3 with a descriptive title, and H4 headings for HTML, CSS, and Result, as described in https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#formatting_live_samples and as the outline in https://github.com/mdn/content/pull/20838#discussion_r974867903 has.

Sorry to be pedantic, but we want reference docs to be consistent so they're easier to navigate and digest.

2022-09-21 01:12 UTC, estelle commented on files/en-us/web/css/pow/index.md
> +The **`pow()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) is an exponential function that returns the value of a base raised to the power of a number.
Exponentional function is used on MDN, and should be linked to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#exponential_functions

2022-09-21 09:00 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +## Example
I understand, thank you for taking the time to search & attach the guidelines. I also need to create a separate PR to fix all the other page I created.

2022-09-21 12:23 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +The **`pow()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) is an exponential function that returns the value of a base raised to the power of a number.
This term is used in the spec - https://w3c.github.io/csswg-drafts/css-values-4/#exponent-funcs

2022-09-21 16:43 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +### Formal syntax
Sorry you are right. We seem to use H3 for functional notations and H2 for every other type of CSS page  ¯\_(ツ)_/¯. We should sort that out but for now yes, let's keep it as H3 here.

2022-09-21 21:30 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +### Formal syntax
We pretty consistently use H2 for properties and for data types, but H3 for functions. The desired structure of CSS pages in general is a bit contested at the moment, so for now I think we ought to keep what we have, which means using H3 here.

2022-09-21 22:56 UTC, wbamberg requested changes
Thank you @ramiy ! Just a few comments left here.

Do you have a PR in for the BCD? If not perhaps we should block merging on that.

2022-09-21 22:56 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +  - : A calculation which resolves to a {{cssxref("&lt;number&gt;")}}, representing the exponent number.
```suggestion
  - : A calculation which resolves to a {{cssxref("&lt;number&gt;")}}, representing the exponent.
```

2022-09-21 22:56 UTC, wbamberg commented on files/en-us/web/css/pow/index.md
> +## Scale headings by fixed ratio
```suggestion
### Scale headings by fixed ratio
```

2022-09-22 17:00 UTC, wbamberg approved these changes
👍 thank you @ramiy !

2022-09-22 18:15 UTC, merged

2022-09-23 02:38 UTC, ramiy commented
> Thank you @ramiy ! Just a few comments left here.
> 
> Do you have a PR in for the BCD? If not perhaps we should block merging on that.

**WebKit**: [Implement the CSS exponent functions: pow(), sqrt(), hypot() ](https://bugs.webkit.org/show_bug.cgi?id=203312) (Oct. 2021)