fix(typos): repeated words
mdn/content pull request #20848
Opened 2022-09-18 05:19 UTC by OnkarRuikar

Adds to https://github.com/mdn/content/pull/20751

Fixes repeated words/clauses.

2022-09-18 07:12 UTC, nschonni commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +{{EmbedLiveSample("A_fillStyle_example", 160, "canvas_fillstyle.png")}}
Don't think you can drop parameters on the macros as they are positional

2022-09-18 07:12 UTC, nschonni commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +![Three coordinate grids. The grid lines are actual pixels on the screen. The top left corner of each grid is labeled (0). In the first grid, a rectangle from (2,1) to (5) is filled in light-red colo
This is modifying x,y coordinates to a single axis

2022-09-18 07:13 UTC, nschonni commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +To fix this, you have to be very precise in your path creation. Knowing that a `1.0` width line will extend half a unit to either side of the path, creating the path from (3.5,1) to (3.5) results in
Coordinates again

2022-09-18 07:13 UTC, nschonni commented on files/en-us/web/api/websockets_api/index.md
> +- [jsonrpc-bidirectional](https://github.com/bigstepinc/jsonrpc-bidirectional): Asynchronous RPC which, on a single connection, may have functions exported on the server and, at the same time, on the
The "and" after the comma should be the one kept

2022-09-18 14:47 UTC, Josh-Cena requested changes
Apart from the obviously wrong changes mentioned above, I have some more wording suggestions.

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
> +By diffusing the light on the object we can give it its own color — we'll choose a nice familiar blue.
```suggestion
By diffusing the light on the object, we can give it its own color — we'll choose a nice familiar blue.
```

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/glossary/call_stack/index.md
> +- If the stack takes up more space than it was assigned, then this results in a "stack overflow" error.
```suggestion
- If the stack takes up more space than it was assigned, a "stack overflow" error is thrown.
```

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/learn/accessibility/index.md
> +Learning some HTML, CSS, and JavaScript is useful if you want to become a web developer. Beyond mechanical use, it's important to learn how to use these technologies **responsibly** so that all reade
The original is both correct and reads better than the modified one.

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/learn/learning_and_getting_help/index.md
> +Once you know what you need to do, and how long you think it'll take, then you can start writing out a plan to follow to achieve your goal. It can be as simple as:
```suggestion
Once you know what you need to do and how long you think it'll take, you can start writing out a plan to achieve your goal. It can be as simple as:
```

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/web/api/subtlecrypto/importkey/index.md
> +A JSON Web Key looks something like this (it is an EC private key):
Original is better

2022-09-18 14:47 UTC, Josh-Cena commented on files/en-us/web/html/element/img/index.md
> +Due to a [VoiceOver bug](https://bugs.webkit.org/show_bug.cgi?id=216364), VoiceOver does not correctly announce SVG images as image. Include [`role="img"`](/en-US/docs/Web/Accessibility/ARIA/Roles/im
```suggestion
Due to a [VoiceOver bug](https://bugs.webkit.org/show_bug.cgi?id=216364), VoiceOver does not correctly announce SVG images as images. Include [`role="img"`](/en-US/docs/Web/Accessibility/ARIA/Roles/img_role) to all `<img>` elements with SVG source files to ensure assistive technologies correctly announce the SVG as image content.
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/learn/accessibility/index.md
> +Learning some HTML, CSS, and JavaScript is useful if you want to become a web developer. Beyond mechanical use, it's important to learn how to use these technologies **responsibly** so that all reade
```suggestion
Learning some HTML, CSS, and JavaScript is useful if you want to become a web developer. Beyond mechanical use, it's important to learn how to use these technologies **responsibly** so that all readers might use your creations on the web. To help you achieve this, this module will cover general best practices (which are demonstrated throughout the [HTML](/en-US/docs/Learn/HTML), [CSS](/en-US/docs/Learn/CSS), and [JavaScript](/en-US/docs/Learn/JavaScript) topics), [cross browser testing](/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing), and some tips on enforcing accessibility from the start. We'll cover accessibility in special detail.
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +{{EmbedLiveSample("A_fillStyle_example", 160, "canvas_fillstyle.png")}}
```suggestion
{{EmbedLiveSample("A_fillStyle_example", 160, 160, "canvas_fillstyle.png")}}
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +![Three coordinate grids. The grid lines are actual pixels on the screen. The top left corner of each grid is labeled (0). In the first grid, a rectangle from (2,1) to (5) is filled in light-red colo
```suggestion
![Three coordinate grids. The grid lines are actual pixels on the screen. The top left corner of each grid is labeled (0,0). In the first grid, a rectangle from (2,1) to (5,5) is filled in light-red color. In the second grid, (3,1) to (3,5) is joined with a 1-pixel thick royal blue line. The royal-blue line is centered on a grid line, extends from 2.5 to 3.5 on the x access, halfway into the pixels on either side of the graph line, with a light blue background on either side extending from 2 to 4 on the x-access. To avoid the light blue blur extension of the line in the second coordinate grid, the path in, the third coordinate grid is a royal-blue from line (3.5,1) to (3.5,5). The 1 pixel line width ends up completely and precisely filling a single pixel vertical line.](canvas-grid.png)
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +To fix this, you have to be very precise in your path creation. Knowing that a `1.0` width line will extend half a unit to either side of the path, creating the path from (3.5,1) to (3.5) results in
```suggestion
To fix this, you have to be very precise in your path creation. Knowing that a `1.0` width line will extend half a unit to either side of the path, creating the path from (3.5,1) to (3.5,5) results in the situation in the third image—the `1.0` line width ends up completely and precisely filling a single pixel vertical line.
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/web/api/subtlecrypto/importkey/index.md
> +A JSON Web Key looks something like this (it is an EC private key):
```suggestion
A JSON Web Key looks something like this (this is an EC private key):
```

2022-09-19 01:21 UTC, OnkarRuikar commented on files/en-us/web/api/websockets_api/index.md
> +- [jsonrpc-bidirectional](https://github.com/bigstepinc/jsonrpc-bidirectional): Asynchronous RPC which, on a single connection, may have functions exported on the server and, at the same time, on the
```suggestion
- [jsonrpc-bidirectional](https://github.com/bigstepinc/jsonrpc-bidirectional): Asynchronous RPC which, on a single connection, may have functions exported on the server and, and the same time, on the client (client may call server, server may also call client).
```

2022-09-19 01:22 UTC, OnkarRuikar commented on files/en-us/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
> +Obtaining crisp lines requires understanding how paths are stroked. In the images below, the grid represents the canvas coordinate grid. The squares between gridlines are actual on-screen pixels. In
```suggestion
Obtaining crisp lines requires understanding how paths are stroked. In the images below, the grid represents the canvas coordinate grid. The squares between gridlines are actual on-screen pixels. In the first grid image below, a rectangle from (2,1) to (5,5) is filled. The entire area between them (light red) falls on pixel boundaries, so the resulting filled rectangle will have crisp edges.
```

2022-09-19 01:34 UTC, OnkarRuikar commented
Thank you guys! I had fixed the coordinates related changes in local and forgot to push. :(
I've applied the review suggestions now.

I used `/(\b[\w ]+\b)[ \[\],;\)]+(\b\1\b)/gi` with `skipCode:true` in the markdownlint plugin to find these. There are way more valid cases, so I think this can't be automated.

2022-09-19 04:41 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/42/index.md
> +- Non-standard properties like `-moz-margin-start` are now aliases of their standard counterpart ({{cssxref('margin-inline-start')}}, …). Previously, it was the opposite. This affects the value retur
```suggestion
- Non-standard properties like `-moz-margin-start` are now aliases of their standard counterpart ({{cssxref('margin-inline-start')}}, …). Previously, it was the opposite. This affects the value returned by {{domxref('CSSStyleDeclaration.cssText')}} and iteration of the properties in a style rule, which both use the canonical form ({{bug(1118103)}}).
```

2022-09-19 04:41 UTC, Josh-Cena approved these changes
Looks great to me. Thanks!

2022-09-19 04:43 UTC, merged