`<calc-constant>` - New CSS data type
mdn/content pull request #20856
Opened 2022-09-18 12:19 UTC by ramiy

### Description
Document the CSS `<calc-constant>` data type.

### Motivation
This data type will help us document the new CSS constants - `e` | `pi` | `infinity` | `-infinity` | `NaN`

2022-09-20 14:15 UTC, bsmth commented on files/en-us/web/css/calc-constant/index.md
> +The **`<calc-constant>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) represents a well-known constants, such as `e` and `π`.
```suggestion
The **`<calc-constant>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) represents well-known constants such as `e` and `π`.
```

2022-09-20 19:23 UTC, wbamberg commented
You can include a formal syntax section using something like:

```
## Formal syntax

{{csssyntax}}
```

2022-09-28 23:47 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +tags:
```suggestion
page-type: css-type
tags:
```

2022-10-06 17:57 UTC, wbamberg requested changes
Thanks for your PR, @ramiy ! I wasn't sure whether @bsmth was on this one, but since it's been quiet for a little while...

I think this page needs an H3 "Values" immediately before the H3 "Formal syntax". This "Values" should be a Markdown `<dl>` listing all the values this type can be, in alphabetical order.

I think that would make this bit:

```
- `e` is the base of the natural logarithm, approximately equal to `2.7182818284590452354`.
- `pi` is the ratio of a circle's circumference to its diameter, approximately equal to `3.1415926535897932`.
```

...redundant.

I also think all of the bit at the start, from "Rather than" to the H2 "Syntax", should go in an H2 "Description". But see also my comment on that section: we don't just want to copy/paste the spec into MDN.

2022-10-06 17:57 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +The syntax of `<calc-constant>` extends the syntax of {{CSSxRef("&lt;calc-value&gt;")}}.
I'm not sure what this is saying. "extends" would imply that valid `<calc-value>` values are valid `<calc-constant>` values, but they are not, are they?

Can you instead say something like: "The `<calc-constant` type defines a number of numeric constants that can be used in the `calc()` functional notation"?

2022-10-06 17:57 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +> **Note:** While not technically numbers, these keywords act as numeric values, similar to `e` and `pi`. Thus to get an infinite length, for example, requires an expression like `calc(infinity * 1px
This seems to be a direct quote from the spec: https://w3c.github.io/csswg-drafts/css-values-4/#calc-constants. We don't generally do that, we're not adding any value there.

Things we might want to express:
- this type defines some mathematical constants for use in CSS math functions: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions
- they can only be used in these math functions
- they are case-insensitive (except `NaN`? I didn't really understand this bit)

2022-10-06 21:24 UTC, estelle reviewed
A few suggestions to reduce the reading level required and make clearer that NaN has to be written case exact.

2022-10-06 21:24 UTC, estelle commented on files/en-us/web/css/calc-constant/index.md
> +The **`<calc-constant>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) represents well-known constants such as `e` and `π`.
```suggestion
The **`<calc-constant>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) represents well-defined constants such as `e` and `π`.
```

"well-known" may make people feel bad if they don't know them.

2022-10-06 21:24 UTC, estelle commented on files/en-us/web/css/calc-constant/index.md
> +As usual for CSS keywords, these are ASCII case-insensitive. Thus, `calc(InFiNiTy)` is perfectly valid. However, `NaN` must be serialized with this canonical casing.
```suggestion
As usual for CSS keywords, most CSS constants are ASCII case-insensitive. Thus, `calc(InFiNiTy)` is perfectly valid. There is an exception: `NaN` must be written exactly as `NaN`, with the "Not a Number" canonical casing.
```

This needs to be easier to read than the spec ;)

2022-10-06 21:24 UTC, estelle commented on files/en-us/web/css/calc-constant/index.md
> +- `Nan`
```suggestion
- `NaN`
```

2022-10-06 21:24 UTC, estelle commented on files/en-us/web/css/calc-constant/index.md
> +  - : A value representing Not-A-Number.
```suggestion
  - : A value representing Not-a-Number.
```

2022-10-06 21:29 UTC, estelle commented
Should we include a like to the definitions of pi, infinity, e, and NaN, either in the content or in the see also?

2022-10-13 12:27 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +> **Note:** While not technically numbers, these keywords act as numeric values, similar to `e` and `pi`. Thus to get an infinite length, for example, requires an expression like `calc(infinity * 1px
Good feedback. I've updated the text and moved it to a separate section.

2022-10-13 17:11 UTC, wbamberg requested changes
Thank you @ramiy . This looks good, but I had a few comments here and there.

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +While not technically numbers, css constants act as numeric values, similar to `e` and `pi`. Thus to get an infinite length, for example, requires an expression like `calc(infinity * 1px)`.
```suggestion
While not technically numbers, CSS constants act as {cssxref("number")}} values. Thus to get an infinite {{cssxref("length")}}, for example, requires an expression like `calc(infinity * 1px)`.
```

"similar to `e` and `pi`" is odd - aren't `e` and `pi` just values of this? So they are not "similar to" it, they are it. Or am I confused?

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +CSS constants are ASCII case-insensitive. Thus, `calc(InFiNiTy)` is perfectly valid.
Why _ASCII_ case insensitive? Why not just case-insensitive?

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +There is only one exception, `NaN` is case-sensitive and it must be written exactly as `NaN`. Both `nan` and `NAN` are not valid constants.
```suggestion
There is only one exception: `NaN` is case-sensitive and must be written exactly as `NaN`. Both `nan` and `NAN` are invalid constants.
```

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +```
I'm sorry not to have picked up on this before so I won't insist on it, but: usually I think "Examples" is to show real usage examples of the thing, not syntax illustrations. These sections would do better at the end of the `## Description`, and it would be better to have an example here where we are using these values in some CSS.

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +The `<calc-constant>` type defines a number of numeric constants that can be used in CSS math functions.
```suggestion
The `<calc-constant>` type defines a number of numeric constants that can be used in [CSS math functions](/en-US/docs/Web/CSS/CSS_Functions#math_functions).
```

2022-10-13 17:11 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +  - : An infinite length, used to indicate the largest/smallest possible value.
```suggestion
  - : An infinite value, used to indicate the largest/smallest possible value.
```

(not a necessarily a length?)

2022-10-14 15:55 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +```
https://developer.mozilla.org/en-US/docs/Web/CSS/number#examples
https://developer.mozilla.org/en-US/docs/Web/CSS/integer#examples
https://developer.mozilla.org/en-US/docs/Web/CSS/string#examples
https://developer.mozilla.org/en-US/docs/Web/CSS/image#examples

I prefer this PR to focus on `<calc-constant>`. If you want to change this, let's do it in a separate PR dedicated on unifying this across all the data-type pages.

2022-10-14 18:45 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Not sure about this request. Each topic has a separate heading because it talk about a different aspect. From a users experience perspective, visitors can skip different topics. I prefer to leave the headings.

2022-10-14 20:38 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
It's not at all necessary for every aspect in a description to have a heading, especially when the parts are as short as this. In this case:

- "Used only in calculations"  is not a good heading. Headings should describe the content below them - they are meta-content. They don't describe the thing being documented. Like say "Syntax" - it doesn't tell you what the syntax is, it tells you where to find the syntax. If you can't find a heading that describes the content, just have the content
- "CSS data types" is also not a good heading. It's not obvious to me how that heading connects up with the content at all.
- "Case sensitivity" is a fine heading

So I'd be OK to keep that last one but the others are not worth keeping IMO.

2022-10-14 20:43 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
> * "CSS data types" is also not a good heading. It's not obvious to me how that heading connects up with the content at all.

How about "Constant data types"?

2022-10-16 19:05 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Sorry, I don't really think this is great either. AIUI the content here is saying essentially: `<calc-constant>` values act like `<number>` values. "Constant data types" doesn't tell me that this is what that section is going to tell me.

Please, just remove the H3 heading here.

2022-10-16 19:08 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +CSS constants are case-insensitive. Thus, `calc(infinity)`, `calc(INFINITY)` and `calc(InFiNiTy)` are all perfectly valid. It applies on `e` and `pi too.
> It applies on `e` and `pi too.

I don't think you should say this. You already said "CSS constants are case-insensitive", and that obviously applies to all of them. If you mention `e` and `pi` here, then another value is added, we have to remember to update this list, and if we forget, people will get confused.

If you feel it's important to do something like this, try:

```suggestion
CSS constants are case-insensitive. Thus, `calc(pi)`, `calc(E)` and `calc(InFiNiTy)` are all valid.
```

...which I think makes it a bit clearer that these are supposed to be illustrative not exhaustive.
(you also don't need "perfectly").

2022-10-16 19:31 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
You provided a lot of very good modification requests for this PR, and I implemented all of them. But I disagree with you on this specific issue.

Since you said that short parts don't require headings, I enlarged the details included in each sections . We can debate what should be the heading of each part, but in my opinion, we shouldn't remove the headings.

2022-10-16 22:38 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
@ramiy , it's not our style always to have a heading for every separate topic inside the description. Chosen more or less at random:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#description
- https://developer.mozilla.org/en-US/docs/Web/javascript/reference/operators/import#description
- https://developer.mozilla.org/en-US/docs/Web/javascript/reference/operators/exponentiation#description
- https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description
- https://developer.mozilla.org/en-US/docs/Web/CSS/animation#description
- https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace#description

(I'm sure there are cases where we do have very short H3 sections in a Description, but it is not the most common practice on MDN.)

> Since you said that short parts don't require headings, I enlarged the details included in each sections .

Adding more content to justify having H3 headings is just backwards. We should write content at the level that's right for our readers, and structure it in the way that's appropriate.

I understand that you don't agree with my feedback.

>  I implemented all of them. 

Actually, you haven't. I asked for the "Examples" to be fixed and you pushed back on that, citing other pages that have the same error. I'm happy to fix those in a different PR, although I would have preferred for it to be fixed here.

2022-10-18 12:29 UTC, bsmth commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Hi @ramiy @wbamberg do you have any objection if I take a shot at this section? I can open a PR into Ramiy's branch (`ramiy:patch-5`), maybe it helps get this one closed out

2022-10-18 14:30 UTC, bsmth commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
@ramiy please see my revision here: https://github.com/ramiy/content/pull/1

2022-10-19 09:21 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
@bsmth Thank you for taking the time to review the PR and suggest new changes.

I reviewed your PR. It looks like you moved the content from the "Description" area to the intro area, removing all the H3 headings. How is that different from what @wbamberg suggested?

We disagree on one issue, **whether or not to display H3 headings**.

In my opinion, without the H3 titles we mix different topics together. At least with the titles, the user can understand what he should be considering when using those constants.

We have 3 simple topics we want to emphasize:

- **Where to use constants ?** only inside math functions.
- **What is their data type ?** two numeric constants and two degenerate numeric constants - quote from the spec.
- **Whether they are case sensitive ?** only NaN is case-sensitive.

2022-10-19 09:34 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Now that I'm thinking about it, we can move the entire "**Description > CSS data types**" section to "**Syntax > Return value**" to match the other math functions.

It basically describes the data type returned by the different constants.

2022-10-21 15:32 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
It's not a function though, so it doesn't have a return value.

2022-10-23 07:38 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Sounds reasonable, commit reverted.

2022-10-23 07:41 UTC, ramiy commented on files/en-us/web/css/calc-constant/index.md
> +```
I moved the "Valid values" / "Invalid values" code blocks from the "Examples" section to "Case sensitivity" section.

2022-10-24 10:03 UTC, bsmth commented on files/en-us/web/css/calc-constant/index.md
> +### Case sensitivity
Hi @ramiy, I agree with @wbamberg here on the H3 headings. I will make some changes directly to this branch to help get this PR merged.

2022-10-24 11:09 UTC, bsmth commented
@wbamberg would you mind taking another look?

2022-10-24 11:15 UTC, ramiy commented
@bsmth I added your changes to this PR and then added few more stuff. You ran over them...

2022-10-24 11:23 UTC, ramiy commented
@wbamberg Please use [GitHub suggestions](https://egghead.io/lessons/github-add-suggestions-in-a-github-pr-review). Let'sl discuss them here before merging to the PR.

2022-10-24 11:38 UTC, bsmth commented
Hi @ramiy, myself and Will are in agreement about removing the section headings. Please refer to the template [page structure for documenting CSS properties](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_property_page_template) under our writing guidelines.

**The changes required for this PR to land** are that the headings should be removed and the content under these headings should be incorporated elsewhere in the document.

* "Where constants can be used?" - can be under syntax
* "Returned data type"- they do not have a return type, but a hint for `<number>` types can be added to the intro
* "Case sensitivity" - can be under syntax

For a hint on making these changes, [have a look at my previous commit](https://github.com/mdn/content/pull/20856/commits/1b25fb8faadc208922ece2b5042fd0ec5c2352a9).

2022-10-24 12:06 UTC, ramiy commented
Moving those sections to the intro / syntax mixes different aspects.

I think it will be better to leave all the content in "Description", removing all the H3 headings - just like Will initially suggested.

2022-10-24 12:25 UTC, bsmth commented
Hi Ramiy,

> leave all the content in "Description", removing all the H3 headings

Yes that would help us to get your changes merged, thank you

2022-10-24 13:24 UTC, bsmth approved these changes
Thanks Ramiy 👍🏻 

@wbamberg do you want to have another look?

2022-10-24 15:52 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +- `rotate(1rad * pi);` won't work. You need to use `rotate(calc(1rad * pi));`
```suggestion
These constants can't be used in any CSS function, only in math functions:

- `rotate(1rad * pi);` won't work. You need to use `rotate(calc(1rad * pi));`
```

2022-10-24 16:44 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +
```suggestion

```

2022-10-25 21:45 UTC, wbamberg commented on files/en-us/web/css/calc-constant/index.md
> +- `rotate(1rad * pi);` won't work, {{CSSxRef("transform-function/rotate", "rotate()")}} is not a math function, use `rotate(calc(1rad * pi));`
```suggestion
- `rotate(1rad * pi);` won't work because {{CSSxRef("transform-function/rotate", "rotate()")}} is not a math function. Use `rotate(calc(1rad * pi));`
```

2022-10-25 21:50 UTC, ramiy commented
Ok, looks good. Let's merge.

2022-10-25 22:25 UTC, wbamberg approved these changes
Thanks for your contribution @ramiy !

2022-10-25 22:25 UTC, merged

2022-10-26 07:36 UTC, bsmth commented
Thanks all for the contribution & reviews