chore: update links to imsc repository
mdn/content pull request #20871
Opened 2022-09-19 00:10 UTC by schalkneethling

Update links from imsc to imsc-examples

fix #20870

2022-09-19 09:41 UTC, Elchi3 requested changes, later dismissed

2022-09-19 09:41 UTC, Elchi3 commented on files/en-us/related/imsc/using_the_imscjs_polyfill/index.md
>  {{EmbedGHLiveSample("imsc/imscjs-demo/imscjs-demo.html", '100%', 320)}}
Th embed needs to be updated, too. Currently the iframe is a 404.

2022-09-22 14:11 UTC, bsmth commented on files/en-us/related/imsc/using_the_imscjs_polyfill/index.md
>  {{EmbedGHLiveSample("imsc/imscjs-demo/imscjs-demo.html", '100%', 320)}}
I think the GitHub pages deploy might be broken or need a retrigger:

* https://github.com/mdn/imsc-examples/blob/main/imscjs-simple-sample/imscjs-simple-sample.html
* should be https://mdn.github.io/imsc-examples/imscjs-simple-sample/imscjs-simple-sample.html ?

2022-09-23 12:17 UTC, bsmth approved these changes
Looks good, thanks 👍🏻

2022-09-23 12:20 UTC, merged