update: Nav menu background colors
mdn/content pull request #20903
Opened 2022-09-19 20:59 UTC by AurelianSpodarec

### Description
 I've replaced the colors because the yellow and red are harsh on the eyes.

I kept the language of the color simple, and I believe there wouldn't be any issue to identify the property of the color. 'hotpink' is pink, 'dodgerblue' is blue and orange is orange.

### Motivation

The currently used colors that display in the nav example are harsh on the eyes when you first scroll to that part of the site. You get greeted with a harsh yellow. When you activate the button, you get a harsh red... I think more subtle colors are more appropriate.

2022-09-19 23:20 UTC, estelle requested changes
The new colors don't work well either.

2022-09-19 23:20 UTC, estelle commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: dodgerblue;
while the contrast passes, black on blue is hard to read. How about `palegoldenrod`?

2022-09-19 23:20 UTC, estelle commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: hotpink;
There is not enough contrast to meet WCAG AA color contrast guidelines. Red with white didn't pass either. How about darkred?

2022-09-20 00:18 UTC, AurelianSpodarec commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: dodgerblue;
Hmmm. That's interesting actually. I'm on a mac right now with f.lux software on my screen and `palegoldenrod` is a bit blending with the white and harder to see for me.

However, on my windows machine, with low DPI and non retina, that color is 100% fine - also with f.lux. 

Yeah, I agree, indeed black on blue is hard to read.

How about:

```
background: green;
color: white;
```

This seems to pass WAVE Chrome plugin accessibility at least

2022-09-20 00:20 UTC, AurelianSpodarec commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: hotpink;
Yeah, `darkred` seems to work well ^^

2022-09-20 00:23 UTC, estelle commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: dodgerblue;
the palegoldenrod, being a light color, should have black text on it, not white.
the dark red should have white text.

2022-09-20 00:36 UTC, AurelianSpodarec commented on files/en-us/learn/css/styling_text/styling_links/index.md
> +  background: dodgerblue;
Yeah, that seems to work.

Also, btw on the side note, I'm still pretty new to this, but I think I also found possibly another access-ability issue here https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba - if you try to look at the 'rgba' its in blue and I can't visually see what's written there. I feel like that blue should be lighter, as the current color makes my eyes unable to see it and I have no issues with my eyes. 

Though I'm not sure where to find that blue color. I've checked a few repos and can't seem to find it.

2022-10-09 12:32 UTC, AurelianSpodarec commented
Hey, are the latest changes good?

2022-11-01 16:32 UTC, Josh-Cena commented
Pinging @estelle

2022-11-15 02:27 UTC, estelle approved these changes
Apologies for the delay in approving this. I didn't see the ping. Thank you for the contribution.

2022-11-15 02:27 UTC, merged