CSS `pow()` function - Add BCD browser compatibility
mdn/content pull request #21043
Opened 2022-09-24 16:30 UTC by ramiy

### Description

Add BCD browser compatibility to CSS `pow()` function.

### Motivation

Now that BCD was merged, we can update the `pow()` functions on MDN.

### Related issues and pull requests

BCD data: https://github.com/mdn/browser-compat-data/pull/17869

2022-09-26 09:56 UTC, dipikabh requested changes
Thanks! Just a few nits

2022-09-26 09:56 UTC, dipikabh commented on files/en-us/web/css/pow/index.md
> +Returns a {{CSSxRef("&lt;number&gt;")}} representing base<sup>number</sup>, a `base` taken to the power of `number`.
```suggestion
Returns a {{CSSxRef("&lt;number&gt;")}} representing `base<sup>number</sup>`, that is, `base` raised to the power of `number`.
```

2022-09-26 09:56 UTC, dipikabh commented on files/en-us/web/css/pow/index.md
> +  - : A calculation which resolves to a {{CSSxRef("&lt;number&gt;")}}, representing the base.
```suggestion
  - : A calculation that resolves to a {{CSSxRef("&lt;number&gt;")}}, representing the base.
```

2022-09-26 09:56 UTC, dipikabh commented on files/en-us/web/css/pow/index.md
> +  - : A calculation which resolves to a {{CSSxRef("&lt;number&gt;")}}, representing the exponent.
```suggestion
  - : A calculation that resolves to a {{CSSxRef("&lt;number&gt;")}}, representing the exponent.
```

2022-09-26 17:56 UTC, ramiy commented on files/en-us/web/css/pow/index.md
> +Returns a {{CSSxRef("&lt;number&gt;")}} representing base<sup>number</sup>, a `base` taken to the power of `number`.
Committed only the text change. The code block will display the `sup` element instead of styling the inner element.

2022-09-28 08:54 UTC, dipikabh approved these changes
Thank you!

2022-09-28 08:54 UTC, merged