contain-intrinsic-* missing properties
mdn/content pull request #21110
Opened 2022-09-27 04:54 UTC by hamishwillee

This adds docs for `contain-intrinsic-block-size` and `contain-intrinsic-inline-size` and cross links for all the contain intrinsic docs. Also tags them as "experimental" as the is just one public implementation (chromium).

Other docs work for this can be tracked in #20876

2022-09-27 05:58 UTC, sideshowbarker commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +Size containment allows a user agent to layout an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (th
```suggestion
Size containment allows a user agent to lay out an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (thereby improving user experience).
```

2022-09-27 06:00 UTC, sideshowbarker commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +Size containment allows a user agent to layout an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (th
```suggestion
Size containment allows a user agent to lay out an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (thereby improving user experience).
```

2022-09-27 06:00 UTC, sideshowbarker approved these changes

2022-09-28 09:33 UTC, dipikabh requested changes
Just a few nits. In normal text, I think it should it be the non-hyphenated 'block size'.

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +In a horizontal [writing mode](/en-US/docs/Web/CSS/writing-mode) like standard English this is the vertical dimension (height); for a vertical writing mode it is the horizontal dimension.
```suggestion
The **`contain-intrinsic-block-size`** [CSS](/en-US/docs/Web/CSS) [logical property](/en-US/docs/Web/CSS/CSS_Logical_Properties) defines the block size of an element that a browser can use for layout when the element is subject to [size containment](/en-US/docs/Web/CSS/CSS_Containment#size_containment).

Block size is the size of an element in the dimension perpendicular to the flow of text within a line. In a horizontal [writing mode](/en-US/docs/Web/CSS/writing-mode) like standard English, block size is the vertical dimension (height); in a vertical writing mode, block size is the horizontal dimension.
```
- changed passive to active voice
- replaced the pronoun 'it' for clarity
please check suggestions for technical accuracy

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +contain-intrinsic-block-size: unset;
should there be an entry for 'revert-layer'?

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +The following values may be specified for an element.
```suggestion
The following values can be specified for the intrinsic block size of an element:
```

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +  - : A remembered value of the "normally rendered" element block-size if one exists and the element is skipping its contents (for example, when it is offscreen); otherwise the specified `<length>`.
```suggestion
- `none`
  - : The element has no block size.
- `<length>`
  - : The element has the specified block size, expressed using the ({{cssxref("&lt;length&gt;")}}) data type.
- `auto <length>`
  - : When the element does not have any content (for example, when it is offscreen), the element takes on a remembered block size value of a "normally rendered" element. If a "normally rendered" element did not exist previously, the element has the specified `<length>` block size.
```

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +Size containment allows a user agent to layout an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (th
```suggestion
Size containment allows a user agent to lay out an element as though it had a fixed size. This prevents unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (thereby improving user experience).
```
just splitting the long sentence

2022-09-28 09:33 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +The remembered value is not used if the child elements are being rendered (if size containment is enabled, the `<length>` will be used).
```suggestion
By default, size containment treats elements as though they had no contents and may collapse the layout in the same way as if the contents had no width or height.
The `contain-intrinsic-block-size` property allows authors to specify an appropriate value to be used as the block-size for layout.

The `auto <length>` value allows the block-size of an element to be stored if the element is ever "normally rendered" (with its child elements) and then used instead of the specified value when the element does not have any content.
This allows offscreen elements with [`content-visibility: auto`](/en-US/docs/Web/CSS/content-visibility) to benefit from size containment without developers having to be precise in their estimates of element size.
The remembered value is not used if the child elements are being rendered; if size containment is enabled, the `<length>` value will be used.
```

2022-09-28 09:55 UTC, dipikabh requested changes

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +
Can we have an "Examples" section?

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-height/index.md
>  The **`contain-intrinsic-length`** [CSS](/en-US/docs/Web/CSS) property sets the height of an element that will be used for layout when it is subject to [size containment](/en-US/docs/Web/CSS/CSS_Cont
```suggestion
The **`contain-intrinsic-length`** [CSS](/en-US/docs/Web/CSS) property sets the height of an element that a browser can use for layout when the element is subject to [size containment](/en-US/docs/Web/CSS/CSS_Containment#size_containment).
```

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +The **`contain-intrinsic-inline-size`** [CSS](/en-US/docs/Web/CSS) [logical property](/en-US/docs/Web/CSS/CSS_Logical_Properties) defines the inline-size of an element that will be used for layout wh
```suggestion
The **`contain-intrinsic-inline-size`** [CSS](/en-US/docs/Web/CSS) [logical property](/en-US/docs/Web/CSS/CSS_Logical_Properties) defines the inline-size of an element that a browser can use for layout when the element is subject to [size containment](/en-US/docs/Web/CSS/CSS_Containment#size_containment).
```

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +
All suggestions in the `contain-intrinsic-block-size` page can be applied to the text below

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/css_logical_properties/index.md
> +
Can intrinsic-width and intrinsic-height also be added here?

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-size/index.md
>  The **`contain-intrinsic-size`** [CSS](/en-US/docs/Web/CSS) [shorthand property](/en-US/docs/Web/CSS/Shorthand_properties) sets the size of an element that will be used for layout when it is subject
```suggestion
The **`contain-intrinsic-size`** [CSS](/en-US/docs/Web/CSS) [shorthand property](/en-US/docs/Web/CSS/Shorthand_properties) sets the size of an element that a browser will use for layout when the element is subject to [size containment](/en-US/docs/Web/CSS/CSS_Containment#size_containment).
```

2022-09-28 09:55 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-width/index.md
>  The **`contain-intrinsic-width`** [CSS](/en-US/docs/Web/CSS) property sets the width of an element that will be used for layout when it is subject to [size containment](/en-US/docs/Web/CSS/CSS_Contai
```suggestion
The **`contain-intrinsic-width`** [CSS](/en-US/docs/Web/CSS) property sets the width of an element that a browser will use for layout when the element is subject to [size containment](/en-US/docs/Web/CSS/CSS_Containment#size_containment).
```

2022-10-03 01:40 UTC, hamishwillee commented on files/en-us/web/css/css_logical_properties/index.md
> +
No, because they are not logical properties.

2022-10-03 01:47 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +In a horizontal [writing mode](/en-US/docs/Web/CSS/writing-mode) like standard English this is the horizontal dimension (width); for a vertical writing mode it is the vertical dimension.
```suggestion
Inline-size is the size of the element in the dimension parallel to the flow of text within a line.
In a horizontal [writing mode](/en-US/docs/Web/CSS/writing-mode) like standard English, inline size is the horizontal dimension (width); for a vertical writing mode, inline size is the vertical dimension.
```

2022-10-03 01:48 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +The following values may be specified for an element.
```suggestion
The following values can be specified for the intrinsic inline size of an element:
```

2022-10-03 01:55 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +The following values may be specified for an element.
This is fine, but I don't see it as "better" because the context is completely clear from everything else about the page.  I generally prefer to say less unless extra words will help. 

That said, I accept comments unless I actively disagree and this is a matter of taste.

2022-10-03 02:20 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +  - : A remembered value of the "normally rendered" element block-size if one exists and the element is skipping its contents (for example, when it is offscreen); otherwise the specified `<length>`.
Thanks, but I am not sure about this.
- There is a difference between intrinsic block size and block size, so we can't just remove "intrinsic" above.
- The changes you made for `auto` are wrong, but that doesn't mean than the original is optimal or right. What happens here is that if the element ever leaves size containment and is able to render its elements it does so, and the size is stored/"remembered". This is used only when the element is "skipping its contents", which is in effect when it is offscreen and not about to enter the viewport. I have tried tidy this below. Feel free to suggest again.


```suggestion
- `none`
  - : The element has no intrinsic block size.
- `<length>`
  - : The element has the specified block size, expressed using the ({{cssxref("&lt;length&gt;")}}) data type.
- `auto <length>`
  - : When the element is in size containment and skipping its contents (for example, when it is offscreen and `content-visibility: auto` is set) the block size used is remembered from the actual size of the element when it was last able to render its child elements. If the element has has never rendered its child elements and has no remembered value, or if it is not skipping its contents, the block size is the specified `<length>`.
```

2022-10-03 02:27 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +  - : A remembered value of the "normally rendered" element inline-size if one exists and the element is skipping its contents (for example, when it is offscreen); otherwise the specified `<length>`.
```suggestion
- `auto <length>`
  - : When the element is in size containment and skipping its contents (for example, when it is offscreen and `content-visibility: auto` is set) the inline size is remembered from the actual size of the element when it was last able to render its child elements.
    If the element has never rendered its child elements and hence has no remembered value for the normally rendered element size, or if it is not skipping its contents, the inline size is the specified `<length>`.
```

2022-10-03 02:30 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +
Thanks. I think I have captured them.

2022-10-03 04:34 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +contain-intrinsic-block-size: unset;
@dipikabh Good question. Probably.

The short answer is that I cheated and just copied the data from contain-size.

Looking at the docs there is nothing in the `contain-*` that tells you that these apply so I looked at the ones that supposedly do and they say "can be applied to any CSS property". On that basis I will also added revert-layer and initial in all cases. If there are more cases than those, they are not marked up with the text in MDN.

2022-10-03 04:35 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +contain-intrinsic-block-size: unset;
```suggestion
contain-intrinsic-block-size: revert-layer;
contain-intrinsic-block-size: unset;
```

2022-10-03 04:36 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-inline-size/index.md
> +contain-intrinsic-inline-size: unset;
```suggestion
contain-intrinsic-inline-size: revert;
contain-intrinsic-inline-size: revert-layer;
contain-intrinsic-inline-size: unset;
```

2022-10-03 06:36 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-size/index.md
> +### Setting the intrinsic size
@dipikabh With respect to your comment above about missing Examples, of course you are right that they are desirable. I was hoping to get this in and let someone else who is better with CSS do a better example :-)

That said, I have tried just this one case and if it is heading in the right track for a minimal example then I'll expand it a bit. What do you think of the example below (partial - mostly after "does it seem helpful").

What this does is allow a user to toggle the visibility and contains-intrinsic-size of an element that has content. What it can be extended to show (i.e. when I update the words) is how the intrinsic size collapses to nothing if it is not set, however this does not apply if the item is visible unless it is in size containment. Still a little bit of work to go.

2022-10-04 05:27 UTC, hamishwillee commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +Size containment allows a user agent to layout an element as though it had a fixed size, preventing unnecessary reflows by avoiding the re-rendering of child elements to determine the actual size (th
Fixed by another one.

2022-10-04 09:14 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +The following values may be specified for an element.
Sure, agree! Thank you :)

2022-10-04 09:15 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-block-size/index.md
> +  - : A remembered value of the "normally rendered" element block-size if one exists and the element is skipping its contents (for example, when it is offscreen); otherwise the specified `<length>`.
This is definitely better, thank you!

2022-10-04 09:26 UTC, dipikabh commented on files/en-us/web/css/contain-intrinsic-size/index.md
> +### Setting the intrinsic size
Sounds good to me. I can very much relate to "let someone else who is better with CSS do a better example" :)

2022-10-04 09:40 UTC, dipikabh approved these changes
LGTM, @hamishwillee! Thank you 👍

2022-10-04 09:40 UTC, merged