Add section to all array methods about genericness
mdn/content pull request #21137
Opened 2022-09-28 00:49 UTC by Josh-Cena

### Description

Like https://github.com/mdn/content/pull/20568, this time for generic array methods.

### Motivation

We mention this property on some pages but not all of them, and quite inconsistently. This may be part of https://github.com/mdn/mdn-community/discussions/148

### Additional details

### Related issues and pull requests

2022-09-29 22:56 UTC, wbamberg requested changes
Very nice.

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/index.md
> +Array.prototype.join.call({ 0: "a", 1: "b", length: 2 }, "+"); // 'a+b'
You've done this in the other pages and I think it's worth doing here too, much more readable with a separate variable:

```suggestion
const arrayLike = {
  0: "a",
  1: "b",
  length: 2
};
Array.prototype.join.call(arrayLike, "+"); // 'a+b'
```

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/lastindexof/index.md
> +// -1
Maybe worth:

```suggestion
const arrayLike = {
  length: 3,
  0: 2,
  1: 3,
  2: 2,
};
console.log(Array.prototype.lastIndexOf.call(arrayLike, 2));
// 2
console.log(Array.prototype.lastIndexOf.call(arrayLike, 5));
// -1
```

?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/push/index.md
>  ### Using an object in an array-like fashion
This seems a lot like the example you just added, do we still need it?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/reduceright/index.md
> +console.log(Array.prototype.reduceRight.call(arrayLike, (x, y) => x + y));
```suggestion
console.log(Array.prototype.reduceRight.call(arrayLike, (x, y) => x - y));
```

(just a suggestion, so it gives a different answer to `reduce`. Otherwise why bother using it?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/reverse/index.md
> +console.log(Array.prototype.pop.call(arrayLike));
This looks like an example for `pop` not `reverse`?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/pop/index.md
> +The `pop()` method reads the `length` property of `this`. If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before). Otherwise, the property at `length - 1`
Sorry I don't understand this.

> If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before).

If length is 0, how could it have been "negative or `undefined` before"? Before what?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/shift/index.md
> +The `shift()` method reads the `length` property of `this`. If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before). Otherwise, the property at `0` is retu
Again, I don't understand this.

> If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before).

If length is 0, how could it have been "negative or `undefined` before"? Before what?

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/slice/index.md
> +console.log(Array.prototype.slice.call(arrayLike));
This seems like a slightly weird example. More often surely `slice` is called with arguments, and the sparse array seems like a bit of a distraction too.

2022-09-29 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/at/index.md
> +The `at()` method is [generic](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods). It only expects the `this` value to have a `length` property and integer-keyed propert
This seems repetitive and redundant, given "Array methods are always generic" in https://pr21137.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array.

I think personally we would do would be better to omit it, except when there are specific things to note about it. But I won't insist on this if you don't agree.

2022-09-30 00:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/at/index.md
> +The `at()` method is [generic](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods). It only expects the `this` value to have a `length` property and integer-keyed propert
I think it's better if we can put it on every page—_maybe_ one day it will no longer be the case that all array methods are generic (though I doubt it). Not many people read the Array landing page either, and it's better if we can make every page self-contained, or at least include a cross-linking (which is the main purpose here).

2022-09-30 00:55 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/at/index.md
> -This is not to suggest there is anything wrong with using the square bracket notation. For example `array[0]` would return the first item. However instead of using {{jsxref('Array.prototype.length','
Same ^^

2022-09-30 00:57 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/index.md
> +Array.prototype.join.call({ 0: "a", 1: "b", length: 2 }, "+"); // 'a+b'
```suggestion
const arrayLike = {
	0: "a",
	1: "b",
	length: 2,
};
console.log(Array.prototype.join.call(arrayLike, "+")); // 'a+b'
```

2022-09-30 00:59 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/pop/index.md
> +The `pop()` method reads the `length` property of `this`. If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before). Otherwise, the property at `length - 1`
I really struggle to explain this... This is explained in `array/index.md`:

> The `length` property is [converted to a number](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_coercion), truncated to an integer, and then clamped to the range between 0 and 2<sup>53</sup> - 1. `NaN` becomes `0`, so even when `length` is not present or is `undefined`, it behaves as if it has value `0`.

Maybe I should say "if the normalized length is 0"?

2022-09-30 00:59 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/push/index.md
>  ### Using an object in an array-like fashion
This seems to be a more real-world-relevant example than the fleshed-out one above, so yes, I'll prefer to keep both.

2022-09-30 01:00 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/reverse/index.md
> +console.log(Array.prototype.pop.call(arrayLike));
Sorry, copy&paste error 😄

```suggestion
console.log(Array.prototype.reverse.call(arrayLike));
```

2022-09-30 01:01 UTC, Josh-Cena commented
Thanks for being so careful with the examples @wbamberg You can tell I was not feeling the greatest when writing this stuff.

2022-09-30 01:08 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/slice/index.md
> +console.log(Array.prototype.slice.call(arrayLike));
In fact, `slice()` is a very common way to create a copy, especially because it preserves empty slots. But yes, I should add a more relevant example as well.

2022-09-30 01:21 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/pop/index.md
> +The `pop()` method reads the `length` property of `this`. If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before). Otherwise, the property at `length - 1`
Proposed an improvement in https://github.com/mdn/content/pull/21137/commits/90206f2256dd67142e4d78d4208b41607386d371

2022-10-05 23:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/pop/index.md
> +The `pop()` method reads the `length` property of `this`. If the length is 0, `length` is set to `0` again (whereas it may be negative or `undefined` before). Otherwise, the property at `length - 1`
I think this is better but I don't love "normalized length" on its own, because "normalize" to me can mean all kinds of things.

I think it would be better to do something like this if you had a `#### Normalizing the length property` in https://pr21137.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#generic_array_methods, just before the paragraph about "The length property is [converted to a number](https://pr21137.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_coercion)...".

You would also need something like `#### Array-like objects`  before the paragraph starting "The term [array-like object](https://pr21137.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Guide/Indexed_collections#working_with_array-like_objects)".

Then you can link "[normalized length]" to that "Normalizing the length property" fragment, and the connection should be really direct for people.

But this is just a suggestion, if you don't like it I'm happy to merge this PR as it is.

2022-10-07 05:27 UTC, Josh-Cena commented
Added two headings; let's see if this is better.

2022-10-07 21:08 UTC, wbamberg approved these changes
This looks great @Josh-Cena , thank you for your patience with my pedantry :).

2022-10-07 21:08 UTC, merged

2022-10-07 21:10 UTC, Josh-Cena commented
Thanks for all the review! 😉