fix: adjacent code spans
mdn/content pull request #21160
Opened 2022-09-28 18:47 UTC by nschonni

Was looking around at `` ` ` `` because I saw some downstream in the translations repo.
Some cases:
- missing possessive
- bad tupples from HTML conversion
- commas swallowed into code block
- missing commas

2022-09-29 01:41 UTC, rebloor requested changes

2022-09-29 01:41 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.md
> +The following snippet attempts to download an example file, also specifying a filename and location to save it in, and the `uniquify`'s `conflictAction` option.
The addition of a possessive isn't grammatically correct here, the original "… also specifying … the `uniquify` `conflictAction` option." was correct. If you were going to apply a possessive you would need to remove the article e.g. "… also specifying … `uniquify`'s `conflictAction` option." But a better solution to clarify this and similar cases would be to reword along the lines of "… also specifying … the `conflictAction` option of `uniquify`."

2022-10-01 19:43 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.md
> +The following snippet attempts to download an example file, also specifying a filename and location to save it in, and the `uniquify`'s `conflictAction` option.
```suggestion
The following snippet attempts to download an example file, also specifying a filename and location to save it in, and `uniquify`'s `conflictAction` option.
```

2022-10-05 00:09 UTC, wbamberg requested changes
Thanks for the PR!

I'm not in general keen on possessives on identifiers. In some cases here the change broke the sense of what the original author intended, and in others I've made suggestions that seemed to me to make it read better.

2022-10-05 00:09 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/promise/promise/index.md
> +The `resolutionFunc`'s `value` parameter can be another promise object, in which case the promise gets dynamically inserted into the [promise chain](/en-US/docs/Web/JavaScript/Reference/Global_Object
```suggestion
The `value` parameter passed to `resolutionFunc` can be another promise object, in which case the promise gets dynamically inserted into the [promise chain](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#chained_promises). The `rejectionFunc` has semantics close to the [`throw`](/en-US/docs/Web/JavaScript/Reference/Statements/throw) statement, so `reason` is typically an [`Error`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) instance. If either `value` or `reason` is omitted, the promise is fulfilled/rejected with `undefined`.
```

2022-10-05 00:09 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/regexp/dotall/index.md
> +- [Polyfill of `dotAll`'s `RegExp` flag in `core-js`](https://github.com/zloirock/core-js#ecmascript-string-and-regexp)
```suggestion
- [Polyfill of the `dotAll` flag in `core-js`](https://github.com/zloirock/core-js#ecmascript-string-and-regexp)
```

2022-10-05 00:09 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/regexp/sticky/index.md
> +- [Polyfill of `sticky`'s `RegExp` flag in `core-js`](https://github.com/zloirock/core-js#ecmascript-string-and-regexp)
```suggestion
- [Polyfill of the `sticky` flag in `core-js`](https://github.com/zloirock/core-js#ecmascript-string-and-regexp)
```

2022-10-05 00:09 UTC, wbamberg commented on files/en-us/webassembly/javascript_interface/compilestreaming/index.md
> +- If the `source`'s `Result` has an error (e.g. bad MIME type), the promise rejects an error.
I don't understand what this is supposed to mean. What is `Result` here?

2022-10-05 00:51 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/theme_experiment/index.md
> +In the `manifest.json` file, `--reload-button-color` is then mapped to the name to be used in the `theme`'s `colors` property:
```suggestion
In the `manifest.json` file, `--reload-button-color` is then mapped to the name to be used in the `colors` property of `theme`:
```

2022-10-07 16:20 UTC, rebloor approved these changes

2022-10-07 16:21 UTC, rebloor commented
I am happy with the web extension related changes. However, I would suggest following the advice from @wbamberg and remove all possessives.

2022-10-30 19:51 UTC, nschonni commented
@Josh-Cena looks like the check-files is working! Failure is for an actual unrelated issue that the autofix PR should address

2022-10-30 19:52 UTC, nschonni commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_components/index.md
> +2. The child component can now modify the value of the parent's filter variable, so we no longer need the `onclick` prop. Modify the `<script>` element of your  `FilterButton` like this:
```suggestion
2. The child component can now modify the value of the parent's filter variable, so we no longer need the `onclick` prop. Modify the `<script>` element of your `FilterButton` like this:
```

2022-11-15 02:35 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md
> +Next, we use a couple of [`if ()`](/en-US/docs/Web/JavaScript/Reference/Statements/if...else) statements to check whether the `startDate` and `endDate` elements have had values filled in on them. If
A little iffy about this one. Should we use `form control` instead? or explain where these elements are (the var is referenced in the js, but not introduced before that or after i dont' think)

2022-11-15 02:36 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/video_and_audio_apis/index.md
> +- We set the outer `.timer` element to have flex: 5, so it takes up most of the width of the controls bar. We also give it {{cssxref("position")}}`: relative`, so that we can position elements inside
```suggestion
- We set the outer `.timer` element to have `flex: 5`, so it takes up most of the width of the controls bar. We also give it {{cssxref("position")}}`: relative`, so that we can position elements inside it conveniently according to its boundaries, and not the boundaries of the {{htmlelement("body")}} element.
```

2022-11-15 02:37 UTC, estelle commented on files/en-us/learn/server-side/express_nodejs/forms/create_genre_form/index.md
> +Next, we have the pug code for our HTML form that uses the `POST` method to send the data to the server, and because the `action` is an empty string, will send the data to the same URL as the page.
```suggestion
Next, we have the pug code for our HTML form that uses `method="POST"` to send the data to the server, and because the `action` is an empty string, will send the data to the same URL as the page.
```
that way they know "method" is not just a word but actually an attribute.

2022-11-15 02:41 UTC, estelle commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_conditional_rendering/index.md
> +The checkbox `<input>` listens for `change` events.
```suggestion
The `<input>` of `type="checkbox"` listens for `change` events.
```

2022-11-15 02:51 UTC, estelle commented on files/en-us/web/css/box-shadow/index.md
>      If both values are `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```suggestion
- `<offset-x>`
  - : The {{cssxref("&lt;length&gt;")}} value specifies the horizontal distance. Negative values place the shadow to the left of the element. 
- `<offset-y>`
  - : The {{cssxref("&lt;length&gt;")}} values specifies the vertical distance. Negative values place the shadow above the element. 
    If both `<offset-x>` and `<offset-y>` are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```

2022-11-15 02:51 UTC, estelle commented on files/en-us/web/css/box-shadow/index.md
>      If both values are `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
The comma might make people think the syntax takes a comma, so just in case....

2022-11-15 02:55 UTC, estelle commented on files/en-us/web/css/filter/index.md
> -    If both values are `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
this was left in in the box-shadow example. Maybe it should be a note here.

```If both the `offset-x` and `offset-y` values are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```

2022-11-15 02:57 UTC, estelle reviewed
looks good. Just a few comments. Not approving but not holding up a merge either.

2022-11-15 03:01 UTC, nschonni commented
Thanks @estelle , feel free to commit any of your fixes

2022-11-23 19:25 UTC, wbamberg approved these changes
👍

2022-11-23 19:39 UTC, wbamberg commented on files/en-us/web/css/box-shadow/index.md
> +    If both `<offset-x>` and `<offset-y>` are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```suggestion

    If both `<offset-x>` and `<offset-y>` are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```

2022-11-23 19:44 UTC, wbamberg commented on files/en-us/web/css/filter/index.md
> -    If both values are `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
It is tricky because we can't put it next to the entries for `offset-x` and `offset-y` without putting it in one or the other. I think it is better (contextually) to have it in the `<dd>` for `offset-y` than somewhere else entirely. But I just made it a new paragraph.

2022-11-23 19:59 UTC, nschonni commented on files/en-us/web/css/box-shadow/index.md
> +  - : The {{cssxref("&lt;length&gt;")}} value specifies the horizontal distance. Negative values place the shadow to the left of the element.
```suggestion
  - : The {{cssxref("&lt;length&gt;")}} value specifies the horizontal distance. Negative values place the shadow to the left of the element.
```

2022-11-23 19:59 UTC, nschonni commented on files/en-us/web/css/box-shadow/index.md
> +  - : The {{cssxref("&lt;length&gt;")}} values specifies the vertical distance. Negative values place the shadow above the element.
```suggestion
  - : The {{cssxref("&lt;length&gt;")}} values specifies the vertical distance. Negative values place the shadow above the element.
```

2022-11-23 21:04 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md
> +Next, we use a couple of [`if ()`](/en-US/docs/Web/JavaScript/Reference/Statements/if...else) statements to check whether the `startDate` and `endDate` elements have had values filled in on them. If
```suggestion
Next, we use a couple of [`if ()`](/en-US/docs/Web/JavaScript/Reference/Statements/if...else) statements to check whether the form controls with the `id`s `startDate` and `endDate` have had values filled in on them. If they do, we append their values to the URL, specified in `begin_date` and `end_date` URL parameters respectively.
```

2022-11-23 21:06 UTC, estelle commented on files/en-us/web/css/filter/index.md
> +  - : The vertical offset for the shadow, specified as a {{cssxref("&lt;length&gt;")}} value. Negative values place the shadow above the element.
```suggestion
  - : The vertical offset for the shadow, specified as a {{cssxref("&lt;length&gt;")}} value. Negative values place the shadow above the element. If both the `offset-x` and `offset-y` values are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
```

2022-11-23 21:06 UTC, estelle reviewed
text suggestions for my previous comments

2022-11-23 22:13 UTC, merged