Make system-color a proper data type page
mdn/content pull request #21207
Opened 2022-09-30 19:08 UTC by wbamberg

This PR makes ["System color kewords"](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/system_color_keywords) into a proper reference page for the `<system-color>` type, as discussed in https://github.com/mdn/content/issues/15540#issuecomment-1116284998 and following comments.

This will also fix the link in the formal syntax for the `<color>` data type: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#formal_syntax.

This PR depends on https://github.com/mdn/browser-compat-data/pull/17924.

2022-10-03 00:12 UTC, hamishwillee commented on files/en-us/web/css/system-color/index.md
> +{{EmbedLiveSample("Using system colors")}}
This is all good except it would be good to provide links/hints on how to set forced color mode - even better (if possible) would be to make pressing the button force the mode.

Otherwise not much point this being a live example.

I'm going to merge anyway, because this is excellent.

2022-10-03 00:13 UTC, hamishwillee approved these changes
Good for me, modulo comment. Did you want to wait on the BCD to go in first before merging @wbamberg ?

2022-10-03 19:41 UTC, wbamberg commented
> Good for me, modulo comment. Did you want to wait on the BCD to go in first before merging @wbamberg ?

Thanks Hamish. The BCD PR just merged but I'm going to wait for a couple of days for it to percolate through to the page, and hope noone makes any merge conflicts in the meantime: 🤞 .

2022-10-03 22:00 UTC, hamishwillee commented on files/en-us/web/css/system-color/index.md
> +{{EmbedLiveSample("Using system colors")}}
Works for me/don't have any better ideas :-)

2022-10-04 12:18 UTC, dipikabh requested changes
Just tiny nits

2022-10-04 12:18 UTC, dipikabh commented on files/en-us/web/css/system-color/index.md
> +In this example we have a button that normally gets its contrast using the {{cssxref("box-shadow")}} property. In forced colors mode, `box-shadow` is forced to `none`, so the example uses the `forced
```suggestion
The button in this example gets its contrast using the {{cssxref("box-shadow")}} property. In the `forced-colors` mode, `box-shadow` is forced to `none`. The example uses the `forced-colors` media feature to ensure that there is a border of the appropriate color (`ButtonBorder` in this case).
```

2022-10-04 14:51 UTC, wbamberg commented on files/en-us/web/css/system-color/index.md
> +In this example we have a button that normally gets its contrast using the {{cssxref("box-shadow")}} property. In forced colors mode, `box-shadow` is forced to `none`, so the example uses the `forced
`forced-colors` (with code styling and a hyphen) is the name of the media feature, but "forced colors mode" is the name of the abstract feature. So I think "In forced colors mode" is correct here.

2022-10-05 10:20 UTC, dipikabh approved these changes
Thank you! 👍

2022-10-05 10:21 UTC, merged