style: run prettier on non-code fences
mdn/content pull request #21224
Opened 2022-10-01 17:55 UTC by nschonni

Ran accross the full repo, so it includes much of https://github.com/mdn/content/pull/20549, but I've undone the MathML and other changes that stalled the other PR for now

2022-10-01 18:29 UTC, schalkneethling commented
Thanks, @nschonni I will take a look as soon as I can. There is one conflicting file at the moment.

2022-10-10 16:54 UTC, Josh-Cena requested changes
Incomplete reviews. I suggest reverting HTML changes

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/accessibility/aria/attributes/aria-keyshortcuts/index.md
> +  >tress reliever to relax!
Not sure everyone likes this change

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/accessibility/aria/roles/suggestion_role/index.md
> +  >.
Same here; maybe revert the HTML changes for now since there are a lot of controversies around them?

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/api/svgtransformlist/index.md
> +    tfmList.appendItem(scale); } ]]>
Needs revert

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/api/webglrenderingcontext/checkframebufferstatus/index.md
> +        operations.
```suggestion
        Used as a destination for drawing, rendering, clearing, and writing operations.
```

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/api/webglrenderingcontext/framebufferrenderbuffer/index.md
> +        operations.
```suggestion
        Used as a destination for drawing, rendering, clearing, and writing operations.
```

2022-10-10 16:54 UTC, Josh-Cena commented on files/en-us/web/api/webglrenderingcontext/getframebufferattachmentparameter/index.md
> +        operations.
```suggestion
        Used as a destination for drawing, rendering, clearing, and writing operations.
```

2022-10-10 17:49 UTC, rebloor reviewed
No issue with the changes on the web extension pages. However, as also noted by @Josh-Cena, some of the HTML changes are a bit weird.

2022-10-10 18:59 UTC, nschonni commented
OH, I realized what happened with the HTML. I had to disable the `prettierignore` when I was running it, then the lint-staged fixed the code fences on commit, even though the run was with `--embedded-language-formatting`. I'm rebasing it now

2022-10-10 19:41 UTC, Josh-Cena reviewed
I'm slightly confused by the PR title since surely there still are some code blocks formatted; maybe you intend to revert those as well?

Most stuff looks good to me.

2022-10-10 19:41 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +  "HEAD" /* use HEAD when you only need the headers! */,
```suggestion
  "HEAD", // use HEAD when you only need the headers
```

2022-10-10 19:41 UTC, Josh-Cena commented on files/en-us/web/svg/content_type/index.md
> +    _IRI_s are used in the {{SVGAttr("xlink:href")}} attribute. Some attributes allow both \_IRIs_ and text strings as content. To disambiguate a text string from a relative IRI, the functional notat
What's this change about?

2022-10-10 19:41 UTC, Josh-Cena commented on files/en-us/web/svg/element/image/index.md
> +SVG files displayed with `<image>` are [treated as an image](/en-US/docs/Web/SVG/SVG_as_an_Image): external resources aren't loaded, {{cssxref(":visited")}} styles [aren't applied](/en-US/docs/Web/CS
Note, the page is 404, I don't know what it's intended to be linked to

2022-10-10 19:48 UTC, nschonni commented on files/en-us/web/svg/content_type/index.md
> +    _IRI_s are used in the {{SVGAttr("xlink:href")}} attribute. Some attributes allow both \_IRIs_ and text strings as content. To disambiguate a text string from a relative IRI, the functional notat
The earlier internal _ don't work, so I shifted that one so the escape isn't needed now

2022-10-10 19:48 UTC, nschonni commented on files/en-us/web/svg/element/image/index.md
> +SVG files displayed with `<image>` are [treated as an image](/en-US/docs/Web/SVG/SVG_as_an_Image): external resources aren't loaded, {{cssxref(":visited")}} styles [aren't applied](/en-US/docs/Web/CS
Updated the link based on the slug now

2022-10-30 16:28 UTC, Josh-Cena commented on files/en-us/web/api/xmlhttprequest/using_xmlhttprequest/index.md
> +ifHasChanged("yourpage.html", function (modified, visit) {
```suggestion
ifHasChanged("yourpage.html", (modified, visit) => {
```

2022-10-30 16:39 UTC, Josh-Cena approved these changes

2022-10-30 16:48 UTC, Josh-Cena commented
LGTM @nschonni If you could resolve the conflicts it would be great

2022-10-30 18:12 UTC, nschonni commented
@Josh-Cena rebased

2022-10-30 18:14 UTC, Josh-Cena approved these changes

2022-10-30 18:14 UTC, merged