Add CSS scroll-timeline* properties
mdn/content pull request #21277
Opened 2022-10-04 03:15 UTC by hamishwillee

FF103 added support for the following CSS properties behind a pref `layout.css.scroll-linked-animations.enabled`: 
- [ ] scroll-timeline-name 
- [ ] scroll-timeline-axis 
- [ ] scroll-timeline (shorthand)

This adds documentation.

Other docs work can be tracked in #21069

2022-10-04 03:19 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline/index.md
> +### Setting a scroll timeline
This example was modified from the one in [animation-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline). That example works in Chrome but no Firefox, which does not yet fully support the `scroll()` or the (what I think is deprecated) `@scroll-timeline` rule.

What I did was remove the `@scroll-timeline` named `squareTimeline` which previously provided the timeline,  and instead apply `scroll-timeline-name: squareTimeline;` to the container. This same name is still referenced so I thought that this was all that needed to happen. However it does not work! Need to get advice before this can be merged.

2022-10-07 01:54 UTC, hamishwillee commented on files/en-us/web/css/animation-timeline/index.md
>    animation-duration: 3s;
Not clear why you need `animation-duration` when a timeline is provided by the scrollbar.

2022-10-07 02:46 UTC, hamishwillee commented on files/en-us/web/css/@scroll-timeline/index.md
> +{{CSSRef}}{{Deprecated_header}}
Should we just delete this document altogether? It is implemented in chrome so people might be using it, but it is non standard and will shortly be superseded on all platforms

2022-10-09 22:21 UTC, dipikabh requested changes
Thanks for these updates, @hamishwillee! Just a few minor suggestions.

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline-axis/index.md
> +The position is set as absolute so the element rotates in-place.
```suggestion
The position is set as absolute, so the element rotates in place.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline-axis/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```suggestion
Without this element, there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline-axis/index.md
> +Scroll the bottom/horizontal bar to see the animation.
```suggestion
Scroll the horizontal bar at the bottom to see the animation.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline-name/index.md
> +Scroll to see the animation.
```suggestion
Scroll the vertical bar to see the animation.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +The **`scroll-timeline`** [CSS](/en-US/docs/Web/CSS) [shorthand property](/en-US/docs/Web/CSS/Shorthand_properties) defines a name that can be used to identify the source element of a scroll-timeline
```suggestion
The **`scroll-timeline`** [CSS](/en-US/docs/Web/CSS) [shorthand property](/en-US/docs/Web/CSS/Shorthand_properties) defines a name that can be used to identify the source element of a scroll timeline, along with the scrollbar axis that should provide the timeline.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +The name can be referenced in an [`animation-timeline`](/en-US/docs/Web/CSS/animation-timeline) declaration; indicated the element and hence the scroll bar that will be used to control the progress o
seems to be incomplete: "declaration; indicated"

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +The `scroll-timeline` property is equivalent to setting both [`scroll-timeline-name`](/en-US/docs/Web/CSS/scroll-timeline-name) and [`scroll-timeline-axis`](/en-US/docs/Web/CSS/scroll-timeline-axis)
```suggestion
The `scroll-timeline` property is equivalent to setting both [`scroll-timeline-name`](/en-US/docs/Web/CSS/scroll-timeline-name) and [`scroll-timeline-axis`](/en-US/docs/Web/CSS/scroll-timeline-axis) properties in a single declaration.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +/* scroll-timeline-name and scroll-timeline-axis */
```suggestion
/* values for both scroll-timeline-name and scroll-timeline-axis */
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +/* none and scroll-timeline-axis */
```suggestion
/* none keyword for scroll-timeline-name and value for scroll-timeline-axis */
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +Allowed values for `<scroll-timeline-name>` are:
Is there is a way to avoid repeating the value descriptions here to reduce maintenance effort in future? What if we don't list the definitions here but point to respective property pages?

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +A scroll timeline named `squareTimeline` is defined using the `scroll-timeline-name` property on the element with id `container`.
```suggestion
In this example, a scroll timeline named `squareTimeline` is defined using the `scroll-timeline-name` property on the element with the id `container`.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +The height of the container is set to 300px and we also set the container to create a vertical scrollbar it it overflows (below we will use CSS on the "stretcher" element to ensure that it does overf
double "it" typo here

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```suggestion
Without this element, there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +Scroll to see the animation.
```suggestion
Scroll the vertical bar to see the animation.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/animation-timeline/index.md
> +For an animation that depends on the position of a scroll bar this name will be defined in a {{cssxref("scroll-timeline-name")}} or {{cssxref("scroll-timeline")}} property applied to the element that
```suggestion
For an animation that depends on the position of a scrollbar, this name will be defined by the {{cssxref("scroll-timeline-name")}} or {{cssxref("scroll-timeline")}} property that is applied to the element that contains the scrollbar.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/animation-timeline/index.md
> +The animation timeline can also be set using the {{cssxref("animation")}} shorthand property.
```suggestion
The animation timeline can also be set by using the {{cssxref("animation")}} shorthand property.
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/animation-timeline/index.md
> +## Exampless
```suggestion
## Examples
```

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/animation-timeline/index.md
> +The height of the container is set to 300px and we also set the container to create a vertical scrollbar it it overflows (below we will use CSS on the "stretcher" element to ensure that it does overf
the double "it" typo

2022-10-09 22:21 UTC, dipikabh commented on files/en-us/web/css/animation-timeline/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```suggestion
Without this element, there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
```

2022-10-09 22:50 UTC, hamishwillee commented on files/en-us/web/css/@scroll-timeline/index.md
> +{{CSSRef}}{{Deprecated_header}}
Thanks. I'm in two minds. The argument to remove is that this is non standard, deprecated, and the result of a removed draft specification - i.e. should never have been in the wild. The argument to keep is that it is in chrome. Perhaps a compromise would be when the proper API is in one browser.

2022-10-09 22:52 UTC, hamishwillee commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +The scroll timeline can then be associated with a particular [CSS Animation](/en-US/docs/Web/CSS/CSS_Animations) by setting the `animation-timeline` property to the `scroll-timeline-name`.
> Should this entry in 'Experimental Features' also mention that the scroll-timeline shorthand property replaces the @scroll-timeline at-rule – just for the benefit of anybody using it in chrome?

I don't think so. Not the right place - this is "experimental features in Firefox".

2022-10-09 22:56 UTC, hamishwillee commented on files/en-us/web/css/animation-timeline/index.md
> +The height of the container is set to 300px and we also set the container to create a vertical scrollbar it it overflows (below we will use CSS on the "stretcher" element to ensure that it does overf
```suggestion
The height of the container is set to 300px and we also set the container to create a vertical scrollbar it overflows (below we will use CSS on the "stretcher" element to ensure that it does overflow).
```

2022-10-09 22:57 UTC, hamishwillee commented on files/en-us/web/css/animation-timeline/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
I don't see this comma as helpful.

2022-10-09 23:01 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline-axis/index.md
> +The height and width of the container are set to 200px and we also set the container to create scrollbars it it overflows (below we will use CSS on the "stretcher" element to ensure that it does over
```suggestion
The height and width of the container are set to 200px and we also set the container to create scrollbars if it overflows (below we will use CSS on the "stretcher" element to ensure that it does overflow).
```

2022-10-09 23:01 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline-axis/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
Choosing not to take this.

2022-10-09 23:02 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline-name/index.md
> +scroll-timeline: custom_name_for_timeline;
Ooops - good catch (hiding head in shame)

2022-10-09 23:02 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline-name/index.md
> +scroll-timeline: custom_name_for_timeline;
```suggestion
scroll-timeline-name: none;
scroll-timeline-name: custom_name_for_timeline;
```

2022-10-09 23:03 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline-name/index.md
> +The height of the container is set to 300px and we also set the container to create a vertical scrollbar it it overflows (below we will use CSS on the "stretcher" element to ensure that it does overf
```suggestion
The height of the container is set to 300px and we also set the container to create a vertical scrollbar if it overflows (below we will use CSS on the "stretcher" element to ensure that it does overflow).
```

2022-10-09 23:04 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline/index.md
> +The height of the container is set to 300px and we also set the container to create a vertical scrollbar it it overflows (below we will use CSS on the "stretcher" element to ensure that it does overf
```suggestion
The height of the container is set to 300px and we also set the container to create a vertical scrollbar if it overflows (below we will use CSS on the "stretcher" element to ensure that it does overflow).
```

2022-10-09 23:04 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline/index.md
> +Without this element there would be no scrollbar, and hence no scroll timeline to associate with the animation timeline.
Choosing to ignore.

2022-10-09 23:23 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline/index.md
> +The name can be referenced in an [`animation-timeline`](/en-US/docs/Web/CSS/animation-timeline) declaration; indicated the element and hence the scroll bar that will be used to control the progress o
Thanks!

```suggestion
The name can be referenced in an [`animation-timeline`](/en-US/docs/Web/CSS/animation-timeline) declaration in order to indicate the element, and hence the scrollbar, that will be used to control the progress of the animation.
```

2022-10-09 23:38 UTC, hamishwillee commented on files/en-us/web/css/scroll-timeline/index.md
> +  - : Scrollbar in the horizontal axis of the scroll container.
Thanks. That makes sense. Does this work for you?

```suggestion
A `<scroll-timeline-name>` value followed by a `<scroll-timeline-axis>` value may be applied to the container element in any order.
At least one value must be applied.

Allowed values are:

-  `<scroll-timeline-name>` 
  - : The name used to identify the timeline.
    See [`scroll-timeline-name`](/en-US/docs/Web/CSS/scroll-timeline-name).
- `<scroll-timeline-axis>`
  - :  The axis of the element that provides the scrollbar used for the timeline.
    The default is the scrollbar in the block axis.
    See [`scroll-timeline-axis`](/en-US/docs/Web/CSS/scroll-timeline-axis).
```

2022-10-09 23:40 UTC, hamishwillee commented
Hi @dipikabh 

Thanks for your thorough review - more than just a "few" suggestions :-) Much appreciated.

I have accepted most of them. Just one open issue my side as a result of your comments: https://github.com/mdn/content/pull/21277/files#r990857875

2022-10-10 13:23 UTC, dipikabh commented on files/en-us/web/css/scroll-timeline/index.md
> +  - : Scrollbar in the horizontal axis of the scroll container.
Yes, this is much better. Thank you :)

2022-10-10 13:23 UTC, dipikabh approved these changes
Looks good, thanks a lot! 👍

2022-10-10 13:23 UTC, merged