clarify surprising return value
mdn/content pull request #21328
Opened 2022-10-06 09:35 UTC by Boldewyn

### Description

`document.fonts.check()` returns `true` for non-existing or nonsensical font names. Cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1252821#c3 and https://drafts.csswg.org/css-font-loading/Overview.bs for the details.

### Motivation

The continued return value of `true` is surprising for people being confronted with `document.fonts.check()`, if they want to use it to test for anything else than their own fonts.

### Additional details

### Related issues and pull requests

2022-10-06 14:32 UTC, Josh-Cena commented on files/en-us/web/api/fontfaceset/check/index.md
> +will print `true`. This somewhat counterintuitive behavior prevents user tracking by locally installed fonts, though.
```suggestion
The method returns `true` if the font list contains system or non-existing fonts. This prevents user tracking by locally installed fonts.
```

The "return value" needs to be succinct. If you wish, you may add an example below.

2022-10-06 15:11 UTC, Boldewyn commented on files/en-us/web/api/fontfaceset/check/index.md
> +will print `true`. This somewhat counterintuitive behavior prevents user tracking by locally installed fonts, though.
Thank you! I’ve updated the patch with your text and added an additional example.

2022-10-06 15:19 UTC, Josh-Cena commented
Interestingly, this doesn't match the behavior in my Chrome, although it does in Firefox:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/55398995/194352259-61f3920e-5801-449d-a19c-7f55e85074e7.png">

Is there some user preference?

2022-10-06 15:25 UTC, Boldewyn commented
Apparently this is a bug in Chrome, as the spec author noted and a later commentator annotated: https://bugs.chromium.org/p/chromium/issues/detail?id=591602#c12
What is the procedure to continue in this case? Unfortunately the spec is still a working draft, so a moving target. Current state: https://github.com/w3c/csswg-drafts/blob/main/css-font-loading-3/Overview.bs#L921-L923

2022-10-06 15:45 UTC, Josh-Cena commented
I would leave this to the other reviewers. I think a BCD entry at most would suffice. The content, editorial wise, LGTM

2022-10-06 16:30 UTC, wbamberg requested changes
I hope you don't mind the drive-by copy-edits.

> Apparently this is a bug in Chrome, as the spec author noted and a later commentator annotated: https://bugs.chromium.org/p/chromium/issues/detail?id=591602#c12 What is the procedure to continue in this case? Unfortunately the spec is still a working draft, so a moving target. Current state: https://github.com/w3c/csswg-drafts/blob/main/css-font-loading-3/Overview.bs#L921-L923

I think this should be a note in the browser compat, under "chrome": https://github.com/mdn/browser-compat-data/blob/370b0e34d822aa52995468480bce626137bc58d0/api/FontFaceSet.json#L137 .

2022-10-07 08:07 UTC, Boldewyn commented on files/en-us/web/api/fontfaceset/check/index.md
> +```
Good two suggestions! Thank you!

2022-10-07 21:12 UTC, wbamberg approved these changes
Thank you @Boldewyn , and thanks also for opening the BCD PR.

I'm happy with this but leaving it open for @Josh-Cena 's review :).

2022-10-07 21:14 UTC, Josh-Cena approved these changes
LGTM (I only make random drive-by reviews for non-JS stuff)

2022-10-07 21:16 UTC, merged