`hypot()` - New CSS functional notation
mdn/content pull request #21374
Opened 2022-10-07 21:00 UTC by ramiy

### Description
Document the CSS `hypot()` functional notation.

### Motivation
I'm documenting all the exponential CSS functions.

### Additional details
https://www.w3.org/TR/css-values-4/#exponent-funcs

### Related issues and pull requests
* BCD - https://github.com/mdn/browser-compat-data/pull/17871
* Syntaxes - https://github.com/mdn/data/pull/593

2022-10-11 11:42 UTC, dipikabh requested changes

2022-10-11 11:42 UTC, dipikabh commented on files/en-us/web/css/hypot/index.md
> +  - : A calculation which resolves to a {{CSSxRef("&lt;number&gt;")}}, {{CSSxRef("&lt;dimension&gt;")}}, or {{CSSxRef("&lt;percentage&gt;")}}.
```suggestion
  - : A calculation that resolves to a {{CSSxRef("&lt;number&gt;")}}, {{CSSxRef("&lt;dimension&gt;")}}, or {{CSSxRef("&lt;percentage&gt;")}}.
```

2022-10-11 11:42 UTC, dipikabh commented on files/en-us/web/css/hypot/index.md
> +Returns a {{CSSxRef("&lt;number&gt;")}}, {{CSSxRef("&lt;dimension&gt;")}}, or {{CSSxRef("&lt;percentage&gt;")}} (based on the inputs) which is the square root of the sum of squares of its parametrs.
```suggestion
Returns a {{CSSxRef("&lt;number&gt;")}}, {{CSSxRef("&lt;dimension&gt;")}}, or {{CSSxRef("&lt;percentage&gt;")}} (based on the inputs), which is the square root of the sum of squares of its parameters.
```

2022-10-11 11:42 UTC, dipikabh commented on files/en-us/web/css/hypot/index.md
> +- If a single parameter provided, the result is the absolute value of its input. `hypot(2em)` and `hypot(-2em)` both resolve to `2em`.
```suggestion
- If any of the inputs is `infinite`, the result is `+∞`.
- If a single parameter is provided, the result is the absolute value of its input. `hypot(2em)` and `hypot(-2em)` both resolve to `2em`.
```

2022-10-11 20:03 UTC, ramiy commented
@dipikabh Thank you for the suggestions.

2022-10-13 12:04 UTC, dipikabh approved these changes
Thank you!

2022-10-13 12:04 UTC, merged