CSS Functions - Update descriptions
mdn/content pull request #21376
Opened 2022-10-07 22:05 UTC by ramiy

### Description
Unify the numerous function descriptions.

### Motivation
Sort out the page, I think it's a bit messy.

2022-10-07 22:34 UTC, wbamberg reviewed
Thanks for your PR, @ramiy !

I think including things like "A transform function that..." is very repetitive and redundant, given that they are appearing in a section called "Transform functions".

2022-10-12 15:17 UTC, dipikabh commented
Hello @ramiy, I agree with Will's comment. That initial repetitive phrase in the descriptions is redundant, especially when the heading already mentions the type of function.
Consider starting all descriptions with the verb instead, such as "Translates an element horizontally.", "Rotates an element around the horizontal axis.", "Returns the smallest of a list of values." and so on. It looks like the original description was okay as is in most of the instances. Other descriptions can be rephrased to follow this pattern for consistency.

2022-11-21 16:26 UTC, dipikabh commented
Hello @ramiy, hope you're well. Pinging to check if there are any blockers for incorporating the feedback. This should be a quick one to land.

2022-11-24 10:23 UTC, ramiy commented
Hi @dipikabh, no blockers, I will update the PR.

Haven't had much free time lately. A lot of work and the free time I spent with the family.

I will try to make some time to finish all the remaining PRs.

2022-11-25 17:01 UTC, dipikabh commented
> Hi @dipikabh, no blockers, I will update the PR.
> 
> Haven't had much free time lately. A lot of work and the free time I spent with the family.

Family time is important, glad you got the chance to spend time with them.
Appreciate you making the requested changes here! Thank you.

2022-11-25 17:26 UTC, dipikabh requested changes

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Translate an element in 3D space.
```suggestion
- {{CSSxRef("transform-function/translateX", "translateX()")}}
  - : Translates an element horizontally.
- {{CSSxRef("transform-function/translateY", "translateY()")}}
  - : Translates an element vertically.
- {{CSSxRef("transform-function/translateZ", "translateZ()")}}
  - : Translates an element along the z-axis.
- {{CSSxRef("transform-function/translate", "translate()")}}
  - : Translates an element on the 2D plane.
- {{CSSxRef("transform-function/translate3d", "translate3d()")}}
  - : Translates an element in 3D space.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Rotate an element around a fixed axis in 3D space.
```suggestion
  - : Rotates an element around the horizontal axis.
- {{CSSxRef("transform-function/rotateY", "rotateY()")}}
  - : Rotates an element around the vertical axis.
- {{CSSxRef("transform-function/rotateZ", "rotateZ()")}}
  - : Rotates an element around the z-axis.
- {{CSSxRef("transform-function/rotate", "rotate()")}}
  - : Rotates an element around a fixed point on the 2D plane.
- {{CSSxRef("transform-function/rotate3d", "rotate3d()")}}
  - : Rotates an element around a fixed axis in 3D space.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Scale an element up or down in 3D space.
```suggestion
  - : Scales an element up or down horizontally.
- {{CSSxRef("transform-function/scaleY", "scaleY()")}}
  - : Scales an element up or down vertically.
- {{CSSxRef("transform-function/scaleZ", "scaleZ()")}}
  - : Scales an element up or down along the z-axis.
- {{CSSxRef("transform-function/scale", "scale()")}}
  - : Scales an element up or down on the 2D plane.
- {{CSSxRef("transform-function/scale3d", "scale3d()")}}
  - : Scales an element up or down in 3D space.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Skew an element on the 2D plane.
```suggestion
  - : Skews an element in the horizontal direction.
- {{CSSxRef("transform-function/skewY", "skewY()")}}
  - : Skews an element in the vertical direction.
- {{CSSxRef("transform-function/skew", "skew()")}}
  - : Skews an element on the 2D plane.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Describe a 3D transformation as a 4×4 homogeneous matrix.
```suggestion
  - : Describes a homogeneous 2D transformation matrix.
- {{CSSxRef("transform-function/matrix3d", "matrix3d()")}}
  - : Describes a 3D transformation as a 4×4 homogeneous matrix.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Set the distance between the user and the z=0 plane.
```suggestion
  - : Sets the distance between the user and the z=0 plane.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Performe basic arithmetic calculations on numerical values.
```suggestion
  - : Performs basic arithmetic calculations on numerical values.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Calculate the central of a minimum, central, and maximum values.
```suggestion
  - : Calculates the smallest of a list of values.
- {{CSSxRef("max")}}
  - : Calculates the largest of a list of values.
- {{CSSxRef("clamp")}}
  - : Calculates the central of a minimum, central, and maximum values.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Calculate a remainder (with the same sign as the dividend) when dividing one number by another.
```suggestion
  - : Calculates a rounded number based on a rounding strategy.
- {{CSSxRef("mod", "mod()")}} {{Experimental_Inline}}
  - : Calculates a modulus (with the same sign as the divisor) when dividing one number by another.
- {{CSSxRef("rem", "rem()")}} {{Experimental_Inline}}
  - : Calculates a remainder (with the same sign as the dividend) when dividing one number by another.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Calculate a trigonometric inverse tangent of two-numbers in a plane.
```suggestion
- {{CSSxRef("sin")}} {{Experimental_Inline}}
  - : Calculates the trigonometric sine of a number.
- {{CSSxRef("cos")}} {{Experimental_Inline}}
  - : Calculates the trigonometric cosine of a number.
- {{CSSxRef("tan")}} {{Experimental_Inline}}
  - : Calculates the trigonometric tangent of a number.
- {{CSSxRef("asin")}} {{Experimental_Inline}}
  - : Calculates the trigonometric inverse sine of a number.
- {{CSSxRef("acos")}} {{Experimental_Inline}}
  - : Calculates the trigonometric inverse cosine of a number.
- {{CSSxRef("atan")}} {{Experimental_Inline}}
  - : Calculates the trigonometric inverse tangent of a number.
- {{CSSxRef("atan2")}} {{Experimental_Inline}}
  - : Calculates the trigonometric inverse tangent of two-numbers in a plane.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Calculate `e` raised to the power of a number.
```suggestion
  - : Calculates the base raised to the power of a number.
- {{CSSxRef("sqrt")}} {{Experimental_Inline}}
  - : Calculates the square root of a number.
- {{CSSxRef("hypot")}} {{Experimental_Inline}}
  - : Calculates the square root of the sum of the squares of its arguments.
- {{CSSxRef("log")}} {{Experimental_Inline}}
  - : Calculates the logarithm of a number.
- {{CSSxRef("exp")}} {{Experimental_Inline}}
  - : Calculatex `e` raised to the power of a number.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Calculate the sign (positive or negative) of the number.
```suggestion
  - : Calculates the absolute value of a number.
- {{CSSxRef("sign")}} {{Experimental_Inline}}
  - : Calculates the sign (positive or negative) of the number.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Increase the sepia of an image.
```suggestion
  - : Increases the image gaussian blur.
- {{CSSxRef("filter-function/brightness", "brightness()")}}
  - : Brightens or darkens an image.
- {{CSSxRef("filter-function/contrast", "contrast()")}}
  - : Increases or decreases the image contrast.
- {{CSSxRef("filter-function/drop-shadow", "drop-shadow()")}}
  - : Applies a drop shadow behind an image.
- {{CSSxRef("filter-function/grayscale", "grayscale()")}}
  - : Converts an image to grayscale.
- {{CSSxRef("filter-function/hue-rotate", "hue-rotate()")}}
  - : Changes the overall hue of an image.
- {{CSSxRef("filter-function/invert", "invert()")}}
  - : Inverts the colors of an image.
- {{CSSxRef("filter-function/opacity", "opacity()")}}
  - : Adds transparency to an image.
- {{CSSxRef("filter-function/saturate", "saturate()")}}
  - : Changes the overall saturation of an image.
- {{CSSxRef("filter-function/sepia", "sepia()")}}
  - : Increases the sepia of an image.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
>    - : Allows a color to be specified in a particular, specified colorspace (rather than the implicit sRGB colorspace that most of the other color functions operate in).
```suggestion
  - : Allows a color to be set in the specified colorspace (instead of the implicit sRGB colorspace that most of the other color functions operate in).
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
>    - : Used to express CMYK colors in a device-independent way.
```suggestion
  - : Defines CMYK colors in a device-independent way.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +The {{CSSxRef("&lt;image&gt;")}} CSS [data type](/en-US/docs/Web/CSS/CSS_Types) represents graphical representation of images or a gradients.
```suggestion
The {{CSSxRef("&lt;image&gt;")}} CSS [data type](/en-US/docs/Web/CSS/CSS_Types) provides graphical representation of images or gradients.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +CSS counter functions are generally used with the {{CSSxRef("content")}} property, although in theory may be used wherever a {{CSSxRef("&lt;string&gt;")}} is supported.
```suggestion
CSS counter functions are generally used with the {{CSSxRef("content")}} property, although in theory, they may be used wherever a {{CSSxRef("&lt;string&gt;")}} is supported.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Define the counter styles inline, directly as the value of a property.
```suggestion
  - : Returns a string representing the current value of the named counter if there is one.
- {{CSSxRef("counters")}}
  - : Enables nested counters, returning a concatenated string representing the current values of the named counters, if there are any.
- {{CSSxRef("symbols")}}
  - : Defines the counter styles inline, directly as the value of a property.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Enable annotations, like circled digits or inverted characters. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `nalt`, like `nalt 2`.
```suggestion
- {{CSSxRef("font-variant-alternates/stylistic", "stylistic()")}}
  - : Enables stylistic alternates for individual characters. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `salt`, like `salt 2`.
- {{CSSxRef("font-variant-alternates/styleset", "styleset()")}}
  - : Enables stylistic alternatives for sets of characters. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `ssXY`, such as `ss02`.
- {{CSSxRef("font-variant-alternates/character-variant", "character-variant()")}}
  - : Enables specific stylistic alternatives for characters. It is similar to `styleset()`, but doesn't create coherent glyphs for a set of characters; individual characters will have independent and not necessarily coherent styles. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `cvXY`, such as `cv02`.
- {{CSSxRef("font-variant-alternates/swash", "swash()")}}
  - : Enables [swash](https://en.wikipedia.org/wiki/Swash_%28typography%29) glyphs. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType values `swsh` and `cswh`, such as `swsh 2` and `cswh 2`.
- {{CSSxRef("font-variant-alternates/ornaments", "ornaments()")}}
  - : Enables ornaments such as [fleurons](https://en.wikipedia.org/wiki/Fleuron_%28typography%29) and other dingbat glyphs. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `ornm`, such as `ornm 2`.
- {{CSSxRef("font-variant-alternates/annotation", "annotation()")}}
  - : Enables annotations such as circled digits or inverted characters. The parameter is a font-specific name mapped to a number. It corresponds to the OpenType value `nalt`, such as `nalt 2`.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +The {{CSSxRef("&lt;basic-shape&gt;")}} CSS [data type](/en-US/docs/Web/CSS/CSS_Types) represents graphical shape. It is used in the {{CSSxRef("clip-path")}}, {{CSSxRef("offset-path")}}, and {{CSSxRef
```suggestion
The {{CSSxRef("&lt;basic-shape&gt;")}} CSS [data type](/en-US/docs/Web/CSS/CSS_Types) represents a graphical shape. It is used in the {{CSSxRef("clip-path")}}, {{CSSxRef("offset-path")}}, and {{CSSxRef("shape-outside")}} properties.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Accept an SVG path string to enable a shape to be drawn.
```suggestion
  - : Defines a circle shape.
- {{CSSxRef("basic-shape/ellipse","ellipse()")}}
  - : Defines an ellipse shape.
- {{CSSxRef("basic-shape/inset","inset()")}}
  - : Defines an inset rectangle shape.
- {{CSSxRef("basic-shape/polygon","polygon()")}}
  - : Defines a polygon shape.
- {{CSSxRef("path")}}
  - : Accepts an SVG path string to enable a shape to be drawn.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Use custom property value instead of any part of a value of another property.
```suggestion
  - : Uses the attributes defined on HTML element.
- {{CSSxRef("env")}}
  - : Uses the user-agent defined as environment variable.
- {{CSSxRef("url")}}
  - : Uses a file from the specified URL.
- {{CSSxRef("var")}}
  - : Uses the custom property value instead of any part of a value of another property.
```

2022-11-25 17:26 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +  - : Represent a repeated fragment of the track list, allowing a large number of columns or rows that exhibit a recurring pattern.
```suggestion
  - : Clamps a given size to an available size according to the formula `min(maximum size, max(minimum size, argument))`.
- {{CSSxRef("minmax")}}
  - : Defines a size range greater-than or equal-to _min_ and less-than or equal-to _max_.
- {{CSSxRef("repeat")}}
  - : Represents a repeated fragment of the track list, allowing a large number of columns or rows that exhibit a recurring pattern.
```

2022-12-15 15:00 UTC, dipikabh approved these changes
Thanks a lot @ramiy!

2022-12-15 15:00 UTC, merged