Incorrect generalization of NaN
mdn/content pull request #21392
Opened 2022-10-08 12:36 UTC by GhostCore07

Resolves #21390

2022-10-08 15:30 UTC, Josh-Cena requested changes
Just curious, are there other cases where you can escape NaN? Can't think of any on top of my head

2022-10-08 15:30 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/nan/index.md
> +- If `NaN` is involved in any mathematical operation, the result is also usually `NaN`. (See [counterexample](#silently-escaping-nan) below.)
```suggestion
- If `NaN` is involved in a mathematical operation, the result is usually also `NaN`. (See [counter-example](#silently_escaping_nan) below.)
```

2022-10-08 15:30 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/nan/index.md
> +In some cases simply testing for NaN at the end of a calculation is not enough to rule out the possibility that a previous calculation resulted in a NaN.
```suggestion
In some cases, simply testing for `NaN` at the end of a calculation is not enough to rule out the possibility that a previous calculation resulted in a `NaN`.
```

2022-10-08 16:03 UTC, Josh-Cena reviewed
After a quick glance over the spec, I'm convinced that this is the only special case (factoring in `Math` methods). In this case it would be interesting to note on the exponentiation operator page as well. The spec also has this to say:

> The result of _base_ `**` _exponent_ when base is 1<sub>𝔽</sub> or -1<sub>𝔽</sub> and exponent is +∞<sub>𝔽</sub> or -∞<sub>𝔽</sub>, or when base is 1<sub>𝔽</sub> and exponent is `NaN`, differs from [IEEE 754-2019](https://tc39.es/ecma262/#sec-bibliography). The first edition of ECMAScript specified a result of `NaN` for this operation, whereas later revisions of IEEE 754 specified 1<sub>𝔽</sub>. The historical ECMAScript behaviour is preserved for compatibility reasons.

Which seems interesting to note.

2022-10-08 16:03 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/nan/index.md
> +In some cases, simply testing for `NaN` at the end of a calculation is not enough to rule out the possibility that a previous calculation resulted in a `NaN`.
```suggestion
`NaN` propagates through mathematical operations, so it's usually sufficient to test for `NaN` once at the end of calculation to detect for error conditions. The only case where `NaN` gets silently escaped is when using [exponentiation](/en-US/docs/Web/JavaScript/Reference/Operators/Exponentiation) with an exponent of `0`, which immediately returns `1` without testing the base's value.
```

2022-10-10 15:20 UTC, Josh-Cena commented
@GhostCore07 Do you intend to address the review at some point? (Because you did apply the suggestions.) If not we can still merge it and I can follow up, or I can directly commit to your branch.

2022-10-11 22:12 UTC, GhostCore07 reviewed
The changes are appropriate in my opinion.

2022-10-11 22:14 UTC, GhostCore07 commented
> @GhostCore07 Do you intend to address the review at some point? (Because you did apply the suggestions.) If not we can still merge it and I can follow up, or I can directly commit to your branch.

Sorry if I missed a step, I wasn't sure if applying the suggestions was enough or I had to also apply a comment. Since it still says 1 pending reviewer I wasn't sure if any additional action was needed by me yet.

2022-10-12 13:38 UTC, Josh-Cena commented
Ah, I'm asking in https://github.com/mdn/content/pull/21392#pullrequestreview-1135238540 if you are willing to add this information to the `**` operator page.

2022-10-13 15:26 UTC, Josh-Cena approved these changes
Thanks! I've committed some changes myself. Congratulations on your first contribution here—welcome aboard!

2022-10-13 15:30 UTC, merged