Web AP methods/props sorted to static/instance headings - BC
mdn/content pull request #21443
Opened 2022-10-10 07:37 UTC by hamishwillee

Follow on from #21353

This is the Web API items starting with B and C

Moved to have consistent headings and ordering.

2022-10-10 08:09 UTC, teoli2003 requested changes

2022-10-10 08:09 UTC, teoli2003 commented on files/en-us/web/api/cssrule/index.md
> +## Instance properties common to all CSSRule instances
```suggestion
## Instance properties
```

2022-10-10 08:55 UTC, teoli2003 approved these changes

2022-10-10 08:58 UTC, merged

2022-10-10 22:17 UTC, hamishwillee commented on files/en-us/web/api/cssrule/index.md
> +## Instance properties common to all CSSRule instances
Thanks. I didn't mess with the ones that were formatted with some special text. I figured once we start linting on these we can catch the problematic cases.

2022-10-11 06:46 UTC, teoli2003 commented on files/en-us/web/api/cssrule/index.md
> +## Instance properties common to all CSSRule instances
There were 2 of them, one was ok to change, and I kept the other as the whole page structure was incorrect. When we lint them, we'll find these, as you say.