Legacy: remove old when supported statements
mdn/content pull request #21519
Opened 2022-10-13 01:57 UTC by estelle

Removed or edited several occurrences of discussions about future support when a feature is actually already well supported.

2022-10-13 05:48 UTC, teoli2003 requested changes

2022-10-13 05:48 UTC, teoli2003 commented on files/en-us/learn/forms/html5_input_types/index.md
> +Clicking a color control generally displays the operating system's default color picking functionality for you to actually make your choice with.
```suggestion
Clicking a color control generally displays the operating system's default color-picking functionality for you to choose.
```

2022-10-13 05:48 UTC, teoli2003 commented on files/en-us/web/html/element/input/range/index.md
> +By default, browsers render range inputs as a slider with the knob sliding left and right.
```suggestion
By default, browsers render range inputs as sliders with the knob sliding left and right.
```

2022-10-13 05:48 UTC, teoli2003 commented on files/en-us/web/html/element/input/range/index.md
> +In the meantime, to create a vertical range, wherein the knob slides up and down, set the CSS {{cssxref('appearance')}} property to `slider-vertical` and include the non-standard `orient` attribute f
```suggestion
To create a vertical range, wherein the knob slides up and down, set the CSS {{cssxref('appearance')}} property to `slider-vertical` and include the non-standard `orient` attribute for Firefox. The CSS {{cssxref('transform')}} property can also be used to {{cssxref('rotate'}} the slider.
```

2022-10-13 21:27 UTC, estelle commented on files/en-us/web/html/element/input/range/index.md
> +In the meantime, to create a vertical range, wherein the knob slides up and down, set the CSS {{cssxref('appearance')}} property to `slider-vertical` and include the non-standard `orient` attribute f
The first example is the height/width way, so I felt I need to keep that first paragraph, otherwise showing that example, which allegedly will be the way to do it, would have come out of left field.  So I'll merge this and delete that.

2022-10-13 21:32 UTC, estelle commented
I removed both the height/width (not supported anywhere) and the rotate (requires additional hacking to save the space required).

2022-10-14 06:21 UTC, teoli2003 commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range, wherein the knob slides up and down, set the CSS {{cssxref('appearance')}} property to `slider-vertical` and include the non-standard `orient` attribute for Firefox.
```suggestion
To create a vertical range, wherein the knob slides up and down, set the CSS {{cssxref('appearance')}} property to `slider-vertical` and include the non-standard `orient` attribute for Firefox.
```

2022-10-14 06:21 UTC, teoli2003 approved these changes

2022-10-14 06:23 UTC, merged