Update tabs.onUpdated index.md extraParameters
mdn/content pull request #21524
Opened 2022-10-13 09:47 UTC by danielbWork

Replaced extraParameters with filter

### Description

Changed "extraParameters" to "filter" also removed some unneeded square brackets "[]"

### Motivation

filter is a much more appropriate name and the brackets are just a typo.

### Additional details

If possible we should update the comparability name as well

### Related issues and pull requests

2022-10-13 16:04 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md
> +browser.tabs.onUpdated.addListener(listener, filter)
```suggestion
browser.tabs.onUpdated.addListener(listener)
browser.tabs.onUpdated.addListener(listener, filter)
```

2022-10-13 16:36 UTC, danielbWork commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md
> +browser.tabs.onUpdated.addListener(listener, filter)
I don't think we should do this, with other pages with optional parameters such as webrequest events we just at most add a comment

2022-10-13 16:40 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md
> +browser.tabs.onUpdated.addListener(listener, filter)
Ah ok, not familiar with web extension conventions. This is the JS/WebAPI convention.

2022-10-13 19:40 UTC, danielbWork commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md
> +browser.tabs.onUpdated.addListener(listener, filter)
It's all good thanks for the suggestion

2023-03-29 18:27 UTC, Josh-Cena commented
@danielbWork To get this merged, we also need a PR in BCD.

@mdn/yari-content-mozilla-add-ons Would someone from the team review this change?

2023-04-01 23:55 UTC, Rob--W requested changes
Before merging, please commit the suggested change, and update the BCD data:

BCD data, rename `extraParameters` to `filter` at: https://github.com/mdn/browser-compat-data/blob/22e0f5f1707f29f0c646ea89f5ba5ea7734fa48a/webextensions/api/tabs.json#L2937

Strangely, the BCD only shows "extraParameters" with nothing more, even though the BCD has another entry. I think that the "properties" key need to be removed (https://github.com/mdn/browser-compat-data/blob/22e0f5f1707f29f0c646ea89f5ba5ea7734fa48a/webextensions/api/tabs.json#L2957), and its content be unindented by two spaces to get it to render in the "Browser Compatibility" section at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Tabs/onUpdated#browser_compatibility

2023-04-01 23:55 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/onupdated/index.md
> +browser.tabs.onUpdated.addListener(listener, filter)
```suggestion
browser.tabs.onUpdated.addListener(
  listener,  // function
  filter     // optional object
)
```

To avoid the impression of the parameter being required, let's explicitly mark it as optional.

For similar examples of this convention, see:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onBeforeNavigate#syntax
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#syntax
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest#syntax

2023-05-25 23:29 UTC, Rob--W approved these changes

2023-05-25 23:51 UTC, merged