Add missing sidebars
mdn/content pull request #21542
Opened 2022-10-14 03:46 UTC by OnkarRuikar

2022-10-14 03:53 UTC, wbamberg requested changes
Thank you @OnkarRuikar !

2022-10-14 03:53 UTC, wbamberg commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +{{QuicklinksWithSubPages("Web/API/BeforeInstallPromptEvent")}}{{SeeCompatTable}}
This ought to be APIRef I think. All sidebars under Web/API should either be DefaultAPISidebar or APIRef.

2022-10-14 04:53 UTC, OnkarRuikar commented on files/en-us/web/api/beforeinstallpromptevent/prompt/index.md
> +{{QuicklinksWithSubPages("Web/API/BeforeInstallPromptEvent")}}{{SeeCompatTable}}
I see. Used `APIRef`.

2022-10-15 04:20 UTC, wbamberg approved these changes
👍 thank you!

2022-10-15 04:20 UTC, merged