Web/HTML: Add/correct sidebars
mdn/content pull request #21617
Opened 2022-10-18 04:13 UTC by OnkarRuikar

The PR
- adds missing sidebar to microformats page
- replaces `QuickLinksWithSubpages` with `ListSubpages`. The quicklinks macro is adding a lot of uncollapsible stuff to the sidebars making them less reader friendly. With `ListSubpages` macro the sidebars are conscise.
- fixes syntax errors in json code blocks
- fixes typos

2022-10-20 05:39 UTC, teoli2003 commented
Why not using HTMLRef? If there is a problem with it, shouldn't we fix it instead?

2022-10-20 05:52 UTC, OnkarRuikar commented
> Why not using HTMLRef? If there is a problem with it, shouldn't we fix it instead?

HTMLRef is a list of only all the HTML elements. But these pages are not element pages. These are sort of miscellaneous pages that is why I used simple ListSubPages macro.

Let me know if you want these pages to be added to HTMLRef macro.

2022-10-20 06:15 UTC, OnkarRuikar commented
> We probably want to extend HTMLRef to be somewhat more like CSSRef,

We can combine `HTMLSidebar` into `HTMLRef` to have only one.

***
#### About `{{QuickLinksWithSubpages}}` macro

We need to make sub levels collapsible. And need to make the depth configurable.
At the moment, in some cases, it creates less useful sidebars: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

2022-10-20 06:18 UTC, teoli2003 commented
> We can combine `HTMLSidebar` into `HTMLRef` to have only one.

This looks like a good idea. Extending HTMLSidebar and getting rid of HTMLRef. Let's wait for @wbamberg's insight, though. That way, the sidebar will be the same for all of HTML.

2022-10-20 22:44 UTC, wbamberg commented
Thanks for asking. Like most rabbit holes I guess it depends deep we want to go!

There are as you say two sidebar macros for HTML: [HTMLRef](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLRef.ejs) and [HTMLSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/HTMLSidebar.ejs).

Actually I think HTMLSidebar is pretty good. It has at the top level:

- "Tutorials" which links to the Learn stuff on HTML
- "Reference" which lists all element and attribute pages (so it already includes elements)
- "Documentation" - this one I would scrap. Including a section labelled "Documentation" in a docs site is a joke, and it only contains two links: one doesn't exist any more and the other is "Contribute", which none of our other sidebars do.

It doesn't AFAICS include the 9 pages you've edited here. These mostly look like a random set of guide pages, except <https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types> which looks like an attribute page in disguise.

It would be good to extend HTMLSidebar so it contains links to these pages, perhaps as a new top-level bit called "Guides" that lists them. (An alternative might be to try to integrate these pages into Learn, but this is much more work and arguably Learn is a different kind of content from guides/tutorials.)

- The easy thing would be a new top-level bit of HTMLSidebar called "Guides" that lists them.
- Much harder but perhaps more organized would be to figure out how to integrate them into Learn.

I don't think HTMLRef is a very useful sidebar. It doesn't add much to the element list in HTMLSidebar. It does add:

- a list of "related elements" based on tagging. I don't think this is very useful. See for example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr - it's not at all obvious that most viewers of `<abbr>` will be most interested in the listed elements, and (I think) it's better for sidebars to stay consistent across page navigations.

- collecting elements by their initial letter. This is maybe nice-ish but I don't think it is worth keeping.

So if it were me, I would:

- add a top-level section to HTMLSidebar, "Guides" that lists these new pages. Optionally move https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types and make it into an attribute page. Or file an issue to do it as a follow-up.
- remove "Documentation" from HTMLSidebar
- change all the HTML elements to use HTMLSidebar instead of HTMLRef
- delete HTMLRef

2022-10-21 07:03 UTC, teoli2003 commented
I think this is a good plan. Once `{{HTMLSidebar}}` is extended, we could morph this PR into removing `{{HTMLRef}}`.

@OnkarRuikar Do you want to update `{{HTMLSidebar}}` in mdn/yari?

2022-10-21 08:22 UTC, OnkarRuikar commented
> @OnkarRuikar Do you want to update `{{HTMLSidebar}}` in mdn/yari?

I am working on it.

> Optionally move [developer.mozilla.org/en-US/docs/Web/HTML/Link_types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) and make it into an attribute page.

We simply need to remove the page as it is a duplicate of https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel . Any extra info can be added to `Attributes/rel` page.
I'll do it in a separate PR.

2022-10-21 17:07 UTC, wbamberg commented
> > @OnkarRuikar Do you want to update `{{HTMLSidebar}}` in mdn/yari?
> 
> I am working on it.
> 
> > Optionally move [developer.mozilla.org/en-US/docs/Web/HTML/Link_types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) and make it into an attribute page.
> 
> We simply need to remove the page as it is a duplicate of https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel .

Oh wow. So we have Web/HTML/Global_attributes/, which contains some attributes, and whose contents is included in the sidebar. But we also have Web/HTML/Attributes/, which contains some other attributes, whose contents is not reachable from anywhere obvious. Not to mention of course the many attributes that don't have their own pages at all.

What an unholy mess. We should abandon "Global attributes" and just have "Attributes" imo - every attribute anyway needs to say which elements it can be used with, so "global" can just be a value of that, not a top-level organizing principle.

I know, I know, this is all in https://github.com/openwebdocs/project/issues/114 which we are not ready for.

2022-10-22 10:19 UTC, teoli2003 commented
I think we shouldn't have HTML/Attributes with anything else than global attributes: There is no guarantee that the same attribute (that is not a global attribute) has the same semantic on two elements. Having SVG/Attributes/ is what caused the SVG mess we are in: you have attributes pages witch conditions: "If you are on <xyz>, this attributes means…"If you are on <rst>, this attribute means…"

We should have Global_attributes or Atributes/_global attr name_ for global attributes and HTML/Elements/_element_/_attr_ for non-global attributes.

2022-10-24 07:26 UTC, OnkarRuikar commented
> We should have Global_attributes or Atributes/_global attr name_ for global attributes and HTML/Elements/_element_/_attr_ for non-global attributes.

- `\web\html\global_attributes\class` sounds better.
- `\web\html\attributes\class` doesn't convey we are covering only global attributes under `\HTML\Attributes`.


The scheme `\web\html\elements\element\*` will create a lot of combinations and duplicate content, e.g. `\web\html\elements\form_element\disabled`.
How about we keep the current structure `\web\html\attributes\disabled` and strictly include only the attributes that have common meaning across all the involved elements? If an attribute has same name but different meaning then we don't cover it in `\web\html\attributes\*`.

2022-10-24 08:31 UTC, teoli2003 commented
I think we should have this debate as an mdn/mdn-community, and likely find a way to decouple the sidebar updates here from this decision. We could have both for the moment or only the global attribute page listed.

2022-10-24 09:12 UTC, OnkarRuikar commented
> We could have both for the moment or only the global attribute page listed.

I say for now we get the sidebar changes done with both of them included. And update the macros in the pages.
The community discussion will take a month or so. Then we'll move/edit many pages based on the decision. After that there will be the final update to the sidebar.

2022-10-29 04:08 UTC, OnkarRuikar commented
The beefed up `{{HTMLSidebar}}` macro is now live. For this PR I've updated all the root level documents under `Web/HTML` to use it.

There are 139 pages that needs `HTMLRef` -> `HTMLSidebar` update. Let me know how do you want to handle it? batch size etc.

***

Also, do we want to add `/en-US/docs/Web/HTML/Link_types` to the `HTMLSidebar`? This is the only root level page that is not in the sidebar.

2022-10-30 03:28 UTC, wbamberg commented
> The beefed up `{{HTMLSidebar}}` macro is now live. For this PR I've updated all the root level documents under `Web/HTML` to use it.
>

🎉 
 
> There are 139 pages that needs `HTMLRef` -> `HTMLSidebar` update. Let me know how do you want to handle it? batch size etc.

If there will be Prettier noise, batches of 50 perhaps? Otherwise I'd say one batch is fine.

> Also, do we want to add `/en-US/docs/Web/HTML/Link_types` to the `HTMLSidebar`? This is the only root level page that is not in the sidebar.

Based on https://github.com/mdn/content/pull/21617#issuecomment-1286629027, I'd say no. But we should have an issue to merge it with `rel` (assuming @teoli2003 is +1 on this).

2022-10-30 03:28 UTC, wbamberg requested changes

2022-10-30 03:28 UTC, wbamberg commented on files/en-us/web/html/attributes/index.md
> +{{HTMLSidebar("Attributes")}}
I *think* that this is redundant, given https://github.com/mdn/yari/pull/7085. If so:

- we should update the macro to remove that stuff,
- in the meantime we should stop passing the argument.

2022-10-30 03:28 UTC, wbamberg commented on files/en-us/web/html/element/index.md
> +{{HTMLSidebar("HTML_Elements")}}
...here too

2022-10-30 03:28 UTC, wbamberg commented on files/en-us/web/html/element/index.md
> +HTML provides a number of elements which can be used together to create forms which the user can fill out and submit to the Website or application. There's a great deal of further information about t
```suggestion
HTML provides a number of elements which can be used together to create forms which the user can fill out and submit to the website or application. There's a great deal of further information about this available in the [HTML forms guide](/en-US/docs/Learn/Forms).
```

2022-10-30 03:28 UTC, wbamberg commented on files/en-us/web/html/microformats/index.md
> +An author of a webpage can add microformats to their HTML. For example if they wanted to identify themselves they could use a [h-card](https://microformats.org/wiki/h-card) such as:
I would have "an h-card" because you (or at least I) pronounce "h" like "aitch".

2022-10-30 03:41 UTC, OnkarRuikar commented on files/en-us/web/html/attributes/index.md
> +{{HTMLSidebar("Attributes")}}
Looks like the PR doesn't handle foldable entries(details tags).
The param keeps the sub tree opened. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) vs [PR](https://pr21617.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Attributes).

2022-10-30 03:43 UTC, OnkarRuikar commented on files/en-us/web/html/microformats/index.md
> +An author of a webpage can add microformats to their HTML. For example if they wanted to identify themselves they could use a [h-card](https://microformats.org/wiki/h-card) such as:
```suggestion
An author of a webpage can add microformats to their HTML. For example if they wanted to identify themselves they could use an [h-card](https://microformats.org/wiki/h-card) such as:
```

2022-11-02 04:28 UTC, wbamberg commented on files/en-us/web/html/attributes/index.md
> +{{HTMLSidebar("Attributes")}}
You're right of course, sorry. I hadn't realised that these are not pages in the sidebar. I still don't like it (they should be pages in the sidebar) but in the context of this sidebar the argument is correct.

2022-11-02 04:28 UTC, wbamberg approved these changes
🎉 thank you @OnkarRuikar !

2022-11-02 04:28 UTC, merged