relnote(106) Add details for semantics MathML rendering changes
mdn/content pull request #21627
Opened 2022-10-18 12:10 UTC by bsmth

Changes in MathML rendering for `<semantics>` element in Fx 106:

>By default, only the first child of the <semantics> element is rendered while the others have their CSS `display` set to `none`.

### Related issues

- [ ] Parent issue: https://github.com/mdn/content/issues/20919

2022-10-19 04:03 UTC, fred-wang commented
I think we need to say something similar for `<maction>`.

2022-10-20 14:17 UTC, dipikabh requested changes

2022-10-20 14:17 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/106/index.md
> +  The rendering algorithm is described in more details in the [`<semantics>`](/en-US/docs/Web/MathML/Element/semantics#sect1) page ({{bug(1588733)}}).
```suggestion
- The [`<semantics>`](/en-US/docs/Web/MathML/Element/semantics) and [`<maction>`](/en-US/docs/Web/MathML/Element/maction) MathML elements now only render the first child element by default ({{bug(1588733)}}).
```
Removed the last bits - we probably don't need to include that info here. I guess the links to the two pages are enough should the readers want to see more details/spec.

2022-10-20 14:19 UTC, bsmth commented on files/en-us/mozilla/firefox/releases/106/index.md
> +  The rendering algorithm is described in more details in the [`<semantics>`](/en-US/docs/Web/MathML/Element/semantics#sect1) page ({{bug(1588733)}}).
OK great, let's do that

2022-10-20 17:53 UTC, dipikabh approved these changes
Thanks! 👍

2022-10-20 17:53 UTC, merged