relnote(106) Add details of HTMLMetaElement.media DOM API
mdn/content pull request #21659
Opened 2022-10-19 15:21 UTC by bsmth

DOM API support for `HTMLMetaElement.media` added in Fx 106. Access to get and set:

```html
<meta content="#ffffff" media="(max-width: 600px)" name="theme-color" />
```

### Related issues

- [x] Parent issue: https://github.com/mdn/content/issues/20928

2022-10-20 13:54 UTC, dipikabh requested changes
Tiny nits

2022-10-20 13:54 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/106/index.md
> +  Meta elements with `media` properties allows the browser to use the `content` value in conjunction with `theme-color` to set the page or UI colors for a given media query ({{bug(1706179)}}).
```suggestion
- The [`HTMLMetaElement.media`](/en-US/docs/Web/API/HTMLMetaElement/media) property is now supported. This property enables you to set different theme colors based on `media` values (e.g. `max-width: 600px`).
  Meta elements with `media` properties allow the browser to use the `content` value in conjunction with `theme-color` to set the page or UI colors for a given media query ({{bug(1706179)}}).
```

2022-10-20 17:54 UTC, dipikabh approved these changes
👍

2022-10-20 17:54 UTC, merged

2022-10-24 07:28 UTC, bsmth commented
Thank you!