Clarify and organize first few sections
mdn/content pull request #21668
Opened 2022-10-19 20:43 UTC by klu22

Made them more concise and focused, especially the introduction. Improved phrasing.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-10-19 23:55 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
```suggestion
Most people in North America or Western Europe use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the latest versions of the first three, as these browsers receive regular updates. For Edge and IE, you probably want to test the last couple of versions; these should all go in the A grade tier.
```

2022-10-20 00:06 UTC, wbamberg requested changes
Thank you @klu22 ! Quite often I'm sceptical about these copy-editing PRs, but this one looks like a great improvement, I agree with pretty much all your suggested changes 👍 .

2022-10-20 00:06 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
```suggestion
```

(fix for markdownlint)

2022-10-20 00:43 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "comm
```suggestion
Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "commonly used among the target audience".
```

2022-10-20 00:43 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  3. C grade: Rare/unknown browsers — don't test, but assume they are capable. Serve the full site, which should work, at least with the fallbacks provided by our defensive coding.
You deleted the paragraph about defensive coding so this seems out of context. I suggest restoring that paragraph about graceful degradation.

2022-10-20 00:43 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
This is far too America-centric for an opening paragraph—it's only supposed to be an example. If you find the original opening too informal, I suggest rewording it but at least keeping the same idea that we are "making educated guesses".

2022-10-20 00:43 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
Edge is practically the same as Chrome, so it should be fine if you don't test it at all.

2022-10-20 00:43 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
Agreed on all points; I just lumped Edge with IE to preserve the original grouping, and think it would be a good idea to change it, now that you mention it, given how much more modern Edge is than IE.

2022-10-20 00:45 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Browser support stats can make your . For example:
Good point, will amend

2022-10-20 01:03 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "comm
This is a regional difference--periods go inside quotes in American English, but outside quotes in British English. I don't know whether MDN is read by more British English users or American English users.

2022-10-20 01:04 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  3. C grade: Rare/unknown browsers — don't test, but assume they are capable. Serve the full site, which should work, at least with the fallbacks provided by our defensive coding.
Defensive coding is irrelevant to this paragraph, which is about choosing which browsers to test.

2022-10-20 01:06 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
The bulk of MDN readers are based in either North America or Western Europe, and those who aren't are free to find information about their respective region. As you say, it's only supposed to be an example, not a comprehensive list of most-used browsers by region. 

I disagree that "making educated guesses" should be kept. Making educated guesses is merely a means to an end (the end being determining which browsers and devices one should test), and telling someone "make educated guesses" doesn't tell them anything new.

2022-10-20 01:07 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "comm
Periods don't go into the quotes if the quote is not a full sentence. I'm okay with (though I also won't write):

> He said, "I love you."

2022-10-20 02:02 UTC, klu22 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Most people in North America or Western America use either Windows or Mac desktops or laptops, where the main browsers are Chrome, Firefox, Safari, IE, and Edge. You probably want to just test the la
On second thought: an extra opening sentence seems redundant, given the section heading.

I'll preface the first sentence with "For example" and leave it at that. Flow is extremely important to me.

2022-10-20 02:36 UTC, klu22 reviewed
I agree with the proposed changes, except where noted in the relevant conversations under the edit suggestions. Thanks for the feedback guys.

2022-10-20 03:19 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "comm
According to a whacky regex test over the corpus of MDN, we seem to use `".` much more commonly than `."` (>2000 times to >500 times). Still, it may be because more than half of my life's academic English training had been in Oxford English and it's just stuck with me subconsciously—I'm fine if you want to keep it this way. We can have an editorial consensus later since we have a lot of stylistic conventions to settle.

2022-10-20 04:46 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +Since it's impossible to test every combination of browser and device, it's enough that you ensure your site works on the most important ones. In practical applications, "important" often means "comm
Overall on MDN we're not very prescriptive on fine style guide points like this. I would say in general, that if the [writing style guide](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide) isn’t explicit on a point, and if it’s not really obviously right or wrong one way or the other (to the point where it affects comprehension, I mean), then it doesn’t matter much, and it’s not really worthwhile to change docs from one to the other.

For our docs, clarity, helpfulness, and correctness are much more important than fine style guide points.

2022-10-22 00:15 UTC, wbamberg requested changes
I do want to have the preceding sentence here, to emphasise that this is audience-relative:

> Deciding which browsers to test is a matter of educated guesses, and should be based on understanding of your user's demographics. 

Otherwise I'm 👍 with these changes.

2022-10-23 07:43 UTC, klu22 reviewed
I've added an intro sentence along those lines; I also changed the section title from "Determine [...]" to "Predict [...]" as I feel the latter fits the theme of educated guesses more.

2022-11-08 05:55 UTC, Josh-Cena approved these changes
Editorial-wise, looks good to me. @wbamberg you may merge if the content is fine to you as well.

2022-11-08 05:55 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +You can classify browsers and devices by the amount of support you intend to give, e.g.:
```suggestion
You can classify browsers and devices by the amount of support you intend to give. For example:
```

2022-11-23 05:49 UTC, wbamberg approved these changes

2022-11-23 05:52 UTC, merged