CANVAS: a11y/Update
mdn/content pull request #21669
Opened 2022-10-19 21:05 UTC by estelle

remove IE. Add alt text to all examples needing it

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-10-19 21:12 UTC, Josh-Cena requested changes

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +Inside the canvas tags, put fallback content. This will be shown if the user's browser doesn't support canvas, and information for screen readers.
```suggestion
You should put some fallback content inside the canvas tags. This should describe the canvas content to users of browsers that don't support canvas, or users of screen readers.
```

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +The above message should provide useful fallback content to the canvas content. For example, if you were rendering a constantly updating graph of stock prices, the fallback content could be a static
```suggestion
The fallback should provide useful alternative content to the canvas content. For example, if you are rendering a constantly updating graph of stock prices, the fallback content could be a static image of the latest stock graph, with `alt` text saying what the prices are in text or a list of links to individual stock pages.
```

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +
Seems duplicated from the note above.

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** The finished code is available on GitHub as [4_canvas_text](https://github.com/mdn/learning-area/tree/main/javascript/apis/drawing-graphics/getting-started/4_canvas_text).
```suggestion
> **Note:** The finished code is available on GitHub as [4_canvas_text](https://github.com/mdn/learning-area/tree/main/javascript/apis/drawing-graphics/getting-started/4_canvas_text).
```

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +   ```
````suggestion
2. Update the inner HTML to reflect the image:

   ```html
    <canvas class="myCanvas">
      <p>A man walking.</p>
    </canvas>
   ```

````

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +4. Now let's create a new {{domxref("HTMLImageElement")}} object, set its {{htmlattrxref("src", "img")}} to the image we want to load and add an `onload` event handler that will cause the `draw()` fu
```suggestion
4. Now let's create a new {{domxref("HTMLImageElement")}} object, set its {{htmlattrxref("src", "img")}} to the image we want to load, and add an `onload` event handler that will cause the `draw()` function to fire when the image is loaded:
```

(There are three actions here, which is why the comma is necessary)

2022-10-19 21:12 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +   ```js
```suggestion
    ```js
```

2022-10-19 23:44 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +
It is slightly redundant, but as alternative text is vital in the case of text in canvas, it is ok to be slightly redundant. the case here is different: all the other examples use inner text. this one is using aria-label because it is text.

2022-10-20 00:28 UTC, Josh-Cena reviewed
Looks great to me, some little suggestions

2022-10-20 00:28 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +You should put some fallback content inside the canvas tags. This should describe the canvas content to users of browsers that don't support canvas, or users of screen readers.
```suggestion
You should put some fallback content inside the `<canvas>` tags. This should describe the canvas content to users of browsers that don't support canvas, or users of screen readers.
```

2022-10-20 00:28 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +> **Note:** Canvas content is not accessible to screen readers. Include descriptive text as the value of the [`aria-label`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) attribute directl
```suggestion
> **Note:** Canvas content is not accessible to screen readers. Include descriptive text as the value of the [`aria-label`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) attribute directly on the canvas element itself or include fallback content placed within the opening and closing `<canvas>` tags. Canvas content is not part of the DOM, but nested fallback content is.
```

2022-10-20 00:28 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/drawing_graphics/index.md
> +Canvas content is not accessible to screen readers. Text painted to the canvas is not available to the DOM, but must be made available to be accessible. In this example, we include the text as the va
```suggestion
Canvas content is not accessible to screen readers. Text painted to the canvas is not available to the DOM, but must be made available to be accessible. In this example, we include the text as the value for `aria-label`.
```

2022-10-20 03:38 UTC, estelle commented
thanks!

2022-10-20 03:41 UTC, Josh-Cena approved these changes
Great, thanks for the update!

2022-10-20 03:46 UTC, Josh-Cena commented
Markdownlint is slightly unhappy. 🙃 I don't know how this should be fixed

2022-10-20 19:02 UTC, merged