Remove legacy browsers support
mdn/content pull request #21721
Opened 2022-10-21 21:26 UTC by estelle

Removed unnecessary mentions of IE and old versions of other browsers.

2022-10-22 02:00 UTC, wbamberg requested changes

2022-10-22 02:00 UTC, wbamberg commented on files/en-us/web/api/canvas_api/tutorial/basic_usage/index.md
> +The `<canvas>` element, like {{HTMLElement("img")}} tag in that, like for {{HTMLElement("video")}}, {{HTMLElement("audio")}}, or {{HTMLElement("picture")}} elements, must be made accessible by provid
```suggestion
The `<canvas>` element, like {{HTMLElement("img")}}, {{HTMLElement("video")}}, {{HTMLElement("audio")}}, and {{HTMLElement("picture")}} elements, must be made accessible by providing fallback text, to be displayed when the media doesn't load or the user is unable to experience it as intended. You should always provide fallback content, captions, and alternative text, as appropriate for the media type.
```

2022-10-22 02:00 UTC, wbamberg commented on files/en-us/web/api/document/index.md
> +  - : In majority of modern browsers, this method does nothing.
```suggestion
  - : This method does nothing.
```

(That's what it says in the page for [`clear()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/clear) anyway. Or "In modern browsers...")

2022-10-22 02:00 UTC, wbamberg commented on files/en-us/web/api/element/getattribute/index.md
> +string_. The implementation of `getAttribute()` in XUL (Gecko) followed this and returned an empty string. You may encounter a {{domxref("element.hasAttribute()")}} call to check for an attribute's e
```suggestion
string_. 
```

2022-10-22 02:00 UTC, wbamberg commented on files/en-us/web/api/element/getattribute/index.md
> +Essentially all web browsers return `null` when
```suggestion
All modern web browsers return `null` when
```

2022-10-22 02:00 UTC, wbamberg commented on files/en-us/web/html/element/button/index.md
> -<table>
Some of this still seems to be current: for example on macOS it looks like clicking a button does not give it focus on current Firefox, and the linked Safari issue is WONTFIX.

We could maybe replace the table with just some text like "On macOS, with Firefox and Safari, clicking a button does not give it focus".

I don't know what the current situation is regarding the mobile table.

2022-10-22 02:02 UTC, Josh-Cena commented on files/en-us/learn/javascript/first_steps/variables/index.md
> +For these reasons and more, we recommend that you use `let` in your code, rather than `var`. There is no longer any reason to use `var`, as it has been supported since Internet Explorer 11.
```suggestion
For these reasons and more, we recommend that you use `let` in your code, rather than `var`. There is no longer any reason to use `var`, as it has been supported by all browsers for more than 7 years.
```

2022-10-22 02:50 UTC, estelle commented on files/en-us/web/html/element/button/index.md
> -<table>
My thought is it is better to not have the table than to have a 5 year old table, and since FF on macOS does do focus, https://codepen.io/estelle/pen/vYjoayw, I thought it best to delete the table.

2022-10-22 02:51 UTC, estelle commented on files/en-us/web/html/element/button/index.md
> -<table>
Just tested safari; still doesn't.

2022-10-22 02:59 UTC, estelle commented on files/en-us/web/html/element/button/index.md
>  Whether clicking on a {{HTMLElement("button")}} causes it to (by default) become focused varies by browser and OS. The results for {{HTMLElement("input")}} of `type="button"` and `type="submit"` are
```suggestion
Whether clicking on a {{HTMLElement("button")}} or {{HTMLElement("input")}} button types causes it to (by default) become focused varies by browser and OS. Most browsers do give focus to a button being clicked, but [Safari does not, by design](https://bugs.webkit.org/show_bug.cgi?id=22261).
```

2022-10-22 03:00 UTC, estelle commented on files/en-us/web/html/element/button/index.md
> -<table>
edited.

2022-10-24 19:22 UTC, jpmedley requested changes, later dismissed

2022-10-24 19:22 UTC, jpmedley commented on files/en-us/web/api/canvas_api/tutorial/basic_usage/index.md
> +The `<canvas>` element, like {{HTMLElement("img")}}, {{HTMLElement("video")}}, {{HTMLElement("audio")}}, and {{HTMLElement("picture")}} elements, must be made accessible by providing fallback text, t
```suggestion
The `<canvas>` element, like the {{HTMLElement("img")}}, {{HTMLElement("video")}}, {{HTMLElement("audio")}}, and {{HTMLElement("picture")}} elements, must be made accessible by providing fallback text to be displayed when the media doesn't load or the user is unable to experience it as intended. You should always provide fallback content, captions, and alternative text, as appropriate for the media type.
```

2022-10-25 04:39 UTC, teoli2003 requested changes
Two small improvements.

2022-10-25 04:39 UTC, teoli2003 commented on files/en-us/learn/performance/multimedia/index.md
> +- **JPEG-XR** — created by Microsoft and was only available in Internet Explorer and EdgeHTML based Edge. It didn't support progressive display and the image decoding was not hardware accelerated and
```suggestion
- **JPEG-XR** — created by Microsoft and was only available in Internet Explorer and EdgeHTML-based Edge. It didn't support progressive display, and the image decoding was not hardware accelerated and, therefore, resource-intensive on the browser's main thread. Progressive JPEG above the fold is rendered progressively (hence the name), meaning the user saw a low-resolution version that gained clarity as the image downloaded, rather than the image loading at full resolution top-to-bottom or even rendering once completely downloaded.
```

2022-10-25 04:39 UTC, teoli2003 commented on files/en-us/web/api/element/getattribute/index.md
> +string_.
```suggestion
All modern web browsers return `null` when the specified attribute does not exist on the specified element.
```

2022-10-25 08:15 UTC, teoli2003 approved these changes

2022-10-25 14:55 UTC, wbamberg approved these changes
👍

2022-10-26 04:12 UTC, merged