Grouping scattered parts into proper sections
mdn/content pull request #21749
Opened 2022-10-22 22:08 UTC by akaabdullahmateen

### Description

- Fixed minor spelling, grammar, and formatting mistakes
- Renamed sub-headings to be more appropriate
- Grouped description of examples with source code
- Moved live samples into a separate results section

### Motivation

This pull request is an attempt to make the documentation consistent so that related articles share the same structure and vocabulary. The concerned guide in this pull request: [Understanding CSS z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index), consisting of a landing page, four articles, and three examples are now structured as follows:

#### Landing page

- Introduction (general introductory text without any heading)
- Articles (links to articles in this guide)
- Examples (links to examples in this guide)

#### Articles

- Introduction (general introductory text without any heading)
- Example
- Result
- See also

#### Examples

- Introduction (general introductory text without any heading)
- Description
- Example
- Result
- See also

### Other changes

- For the same purpose, _block_ and _element_ was being used alternately. I replaced occurrences of _block_ with _element_ wherever appropriate.
- There was a large note in [The stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) that contained most of the description of the example. Notes should be reserved for _indirectly related content_ not _necessary descriptions_. I moved the content inside note to be in description of the example.
- `z-index` and `div` was sometimes marked up as code and other times as plain text. I marked up all occurrences of `z-index` and `div` as code fragments, wherever appropriate.

### Related issues and pull requests

#21373

2022-10-28 20:22 UTC, jpmedley reviewed
Nice work! I have a few suggestions.

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +Actually, as you can see in the example below, the background and border of the non-positioned element (DIV #4) is completely unaffected by floating elements, but the content is affected. This happen
```suggestion
As you can see in the example below, the background and border of the non-positioned element (DIV #4) is completely unaffected by floating elements, but the content is affected. This happens according to standard float behavior. This behavior can be shown with an added rule to the above list:
```

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of DIV #5 has no effect since it is not a positioned element.
```suggestion
In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of div #5 has no effect since it is not a positioned element.
```

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of DIV #5 has no effect since it is not a positioned element.
We typically make 'div' lower case. Please fix this in your other changes.

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1/index.md
> +The only stacking context is the root context. Without `z-index`es, elements are stacked in order of occurrence.
```suggestion
The only stacking context is the root context. Without `z-index` values, elements are stacked in order of occurrence.
```

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1/index.md
> +The only stacking context is the root context. Without `z-index`es, elements are stacked in order of occurrence.
Not an absolute rule, but I avoid mixing typefaces within the same word. It just looks better.

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1/index.md
> +If DIV #2 is assigned a positive (non-zero and non-auto) `z-index` value, it is rendered above all the other DIVs.
"z-index" and the like are not actually code and so do not need to be in special formatting. I think what you're doing here is making the pages consistent. 

I'm not asking that you change these. I'm just asking that you be aware of this in the future.

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
> +    - DIV #4 (`z-index: 10`)
Again, not code. I am asking that you redo these as:

>`z-index`: 2

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +This last example shows problems that arise when mixing several positioned elements in a multi-level HTML hierarchy and when `z-index`es are assigned using class selectors.
```suggestion
This last example shows problems that arise when mixing several positioned elements in a multi-level HTML hierarchy and when `z-index` values are assigned using class selectors.
```

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +Let's take as an example a three-level hierarchical menu made from several positioned `div`s. Second-level and third-level `div`s appear when hovering or clicking on their parents. Usually this kind
```suggestion
Let's take as an example a three-level hierarchical menu made from several positioned `div` elements. Second-level and third-level `div` elements appear when a user hovers or clicks on their parents. Usually this kind of menu is script-generated either client-side or server-side, so style rules are assigned with a class selector instead of the id selector.
```

2022-10-28 20:22 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
> +    - DIV #4 (`z-index: 10`)
Do this in the next page as well, please.

2022-10-28 22:40 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +Let's take as an example a three-level hierarchical menu made from several positioned `div`s. Second-level and third-level `div`s appear when hovering or clicking on their parents. Usually this kind
@jpmedley Wow! Thanks for all these helpful suggestions! I will revisit this thread tomorrow and fix the concerned problems. Thanks once again; I really learnt a lot :smile:

2022-10-28 22:44 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +The `z-index` property can be specified with an integer value (positive, zero, or negative), which represents the position of the element along an imaginary z-axis. If you are not familiar with this
:+1: Also, what should be the preferred way to enclose terms? _single quotation marks_ (`''`) or _double quotation marks_ (`""`).

2022-10-28 22:50 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of DIV #5 has no effect since it is not a positioned element.
I do not know how to embed diff code like you did, but there is in fact a DIV 5 hiding in the HTML:

```html
<div id="sta1">
  <strong>DIV #5</strong>
  <br />no positioning <br />z-index: 8;
</div>
```

2022-10-28 22:51 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/index.md
> +This means that CSS style rules allow you to position boxes on layers in addition to the default rendering layer (layer 0). The position on an imaginary z-axis of each layer is expressed as an intege
:+1:  Great!

2022-10-28 22:52 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_and_float/index.md
> +Actually, as you can see in the example below, the background and border of the non-positioned element (DIV #4) is completely unaffected by floating elements, but the content is affected. This happen
I will keep in mind to eliminate redundant phrases next time. Thanks for the suggestions! :+1:

2022-10-28 22:58 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of DIV #5 has no effect since it is not a positioned element.
It makes perfect sense to keep **div** lower case (to highlight that it is in fact referring to the element `div`); but there is one more factor affecting this. In the HTML code, the concerned `div` have text content (for example: `DIV #5`). To convert `DIV #5` to `div #5`, I will have to change these text labels as well.

Again, I do not know how to embed diff code, but this is what I mean:

### Before

```html
<div id="sta1">
  <strong>DIV #5</strong>
  <br />no positioning <br />z-index: 8;
</div>
```

### After

```html
<div id="sta1">
  <strong>div #5</strong>
  <br />no positioning <br />z-index: 8;
</div>
```

2022-10-28 22:59 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1/index.md
> +The only stacking context is the root context. Without `z-index`es, elements are stacked in order of occurrence.
I love this! And I also hate mixing typefaces.

2022-10-28 23:00 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_1/index.md
> +If DIV #2 is assigned a positive (non-zero and non-auto) `z-index` value, it is rendered above all the other DIVs.
Got it!

2022-10-28 23:03 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
> +    - DIV #4 (`z-index: 10`)
Got it! So basically, I change all occurrences of **`z-index: n`** to **`z-index`: n**. And, in the text, wherever I marked up **z-index** as code (unless it is a reference to the actual CSS `z-index` property itself), I convert it back to plain text.

2022-10-28 23:03 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +This last example shows problems that arise when mixing several positioned elements in a multi-level HTML hierarchy and when `z-index`es are assigned using class selectors.
:+1:

2022-10-31 14:16 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +The `z-index` property can be specified with an integer value (positive, zero, or negative), which represents the position of the element along an imaginary z-axis. If you are not familiar with this
I couldn't find a preferred way in the [style guide](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines). I'd say just be consistent within a single page.

2022-10-31 14:18 UTC, jpmedley commented on files/en-us/web/css/css_positioning/understanding_z_index/adding_z-index/index.md
> +In this example, the layers' stacking order is rearranged using `z-index`. The `z-index` of DIV #5 has no effect since it is not a positioned element.
That's a good point. Resolving this.

I don't know what you mean by 'I do not know how to embed diff code'.

2022-10-31 14:21 UTC, jpmedley approved these changes
Thank you for your patience. This this looks good to go.

2022-10-31 14:23 UTC, jpmedley submitted a review, later dismissed
Actually, I shouldn't have said ok yet. It looks like you're still doing stuff to this. Generally, the review for typos pass should be the last step. Please let me know when you're done.

2022-11-02 00:00 UTC, akaabdullahmateen commented
@jpmedley  I am extremely sorry that I was not able to complete it in time. I had some fever since last few days and was in admitted in hospital. I am back home now so I will work on it soon. Thank you for your patience all the help you did for me.

2022-11-07 16:31 UTC, Rumyra approved these changes

2022-11-08 08:25 UTC, bsmth commented
I'm taking a look for another final set of eyes on this 👀

2022-11-08 09:03 UTC, bsmth requested changes
Thanks a lot for the additions, there's a few suggestions open for you. In case you're not familiar, you can [commit the suggestions directly](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) on GitHub.

2022-11-09 00:14 UTC, akaabdullahmateen commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
> +  - DIV #2 (`z-index: 2`)
@bsmth Yes!!!! Already on it :smile:

2022-11-09 08:54 UTC, bsmth commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_2/index.md
> +  - DIV #2 (`z-index: 2`)
> Can someone explain what does this "Outdated" label mean on suggestions?

Of course; someone has left a review on some file and this file has changed in the meantime, so the review comment might be outdated. 

In this case, I made [some suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) and [applied them to your branch](https://github.com/mdn/content/pull/21749/commits/7a768536d0560a609ad24f1462060b55d7e7324c) to save some time.

I will take a look at your updates shortly.

2022-11-09 13:58 UTC, bsmth approved these changes
Thanks @akaabdullahmateen 🙌🏻

2022-11-09 14:01 UTC, merged