Document PerformanceMark constructor
mdn/content pull request #21821
Opened 2022-10-25 14:06 UTC by Elchi3

### Description

This PR adds docs for the constructor of https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMark.

### Motivation

I'm working on https://github.com/openwebdocs/project/issues/62.

### Additional details

Wait, why does it have a constructor when there is `performance.mark()`? 😱 
When using the constructor, the mark isn't added to the browser's performance timeline!

### Related issues and pull requests

No BCD PR for the `mdn_url` yet. Will file one soon. Promised.

2022-10-25 17:25 UTC, wbamberg requested changes

2022-10-25 17:25 UTC, wbamberg commented on files/en-us/web/api/performancemark/index.md
> +**`PerformanceMark`** is an _abstract_ interface for {{domxref("PerformanceEntry")}} objects with an {{domxref("PerformanceEntry.entryType","entryType")}} of "`mark`".
What is an abstract interface? Also I'm not sure about all the italics in here.

2022-10-25 17:25 UTC, wbamberg commented on files/en-us/web/api/performancemark/performancemark/index.md
> +browser-compat: api.PerformanceMark.PerformanceMark
It looks like this is supported in Firefox, contrary to BCD.

2022-10-25 17:25 UTC, wbamberg commented on files/en-us/web/api/performancemark/performancemark/index.md
> +    {{domxref("PerformanceTiming")}} interface, {{jsxref("SyntaxError")}} is
Should we document that in "Exceptions"?

2022-10-25 17:25 UTC, wbamberg commented on files/en-us/web/api/performancemark/performancemark/index.md
> +      - : {{domxref("DOMHighResTimeStamp")}} to use as the mark time.
Should specify the defaults for optional arguments (especially for `startTime`).

2022-10-26 11:44 UTC, Elchi3 commented on files/en-us/web/api/performancemark/performancemark/index.md
> +browser-compat: api.PerformanceMark.PerformanceMark
Nice! I've sent https://github.com/mdn/browser-compat-data/pull/18087

2022-10-26 11:55 UTC, Elchi3 commented on files/en-us/web/api/performancemark/index.md
> +**`PerformanceMark`** is an _abstract_ interface for {{domxref("PerformanceEntry")}} objects with an {{domxref("PerformanceEntry.entryType","entryType")}} of "`mark`".
I have no idea why it would be abstract. Removed that and the italics.

2022-10-26 11:57 UTC, Elchi3 commented
Thanks for the review, Will! I mostly copied the new contstructor page from https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark. So, I applied your feedback to both, the new constructor page and performance.mark().

2022-10-26 17:08 UTC, wbamberg approved these changes
👍 thank you Florian!

2022-10-26 17:09 UTC, merged