Document PerformanceMark/PerformanceMeasure.detail
mdn/content pull request #21823
Opened 2022-10-25 14:51 UTC by Elchi3

### Description

This PR adds details! 🥁💤 

### Motivation

https://github.com/openwebdocs/project/issues/62

### Additional details

Spec: https://w3c.github.io/user-timing/#performancemark & https://w3c.github.io/user-timing/#performancemeasure

### Related issues and pull requests

Will submit a BCD PR for the mdn_urls later.

2022-10-25 19:00 UTC, Josh-Cena commented on files/en-us/web/api/performancemeasure/detail/index.md
> +performance.measure("dog", {detail: "labrador", start: 0, end: 12345 });
```suggestion
performance.measure("dog", { detail: "labrador", start: 0, end: 12345 });
```

2022-10-26 16:25 UTC, jpmedley requested changes
Looking good. I have a few suggestions though.

2022-10-26 16:25 UTC, jpmedley commented on files/en-us/web/api/performancemark/detail/index.md
> +The read-only **`detail`** property returns arbitrary metadata that has been included in the mark upon construction (either when using {{domxref("Performance.mark","performance.mark()")}} or the {{do
```suggestion
The read-only **`detail`** property returns arbitrary metadata that was included in the mark upon construction (either when using {{domxref("Performance.mark","performance.mark()")}} or the {{domxref("PerformanceMark.PerformanceMark","PerformanceMark()")}} constructor).
```

2022-10-26 16:25 UTC, jpmedley commented on files/en-us/web/api/performancemark/detail/index.md
> +The following example shows the use of the `detail` property.
```suggestion
The following example demonstrates the `detail` property.
```

2022-10-26 16:25 UTC, jpmedley commented on files/en-us/web/api/performancemeasure/detail/index.md
> +The read-only **`detail`** property returns arbitrary metadata that has been included in the mark upon construction (when using {{domxref("Performance.measure","performance.measure()")}}.
```suggestion
The read-only **`detail`** property returns arbitrary metadata that was included in the mark upon construction (when using {{domxref("Performance.measure","performance.measure()")}}.
```

2022-10-26 16:25 UTC, jpmedley commented on files/en-us/web/api/performancemeasure/detail/index.md
> +Returns the value it is set to (from `markOptions` of {{domxref("Performance.measure","performance.measure()")}}).
```suggestion
Returns the value it was set to (from `markOptions` of {{domxref("Performance.measure","performance.measure()")}}).
```

2022-10-26 16:25 UTC, jpmedley commented on files/en-us/web/api/performancemeasure/detail/index.md
> +The following example shows the use of the `detail` property.
```suggestion
The following example demostrates the `detail` property.
```

2022-10-26 20:36 UTC, jpmedley approved these changes

2022-10-26 20:36 UTC, merged