XMLHttpRequest: add note not supported in service workers
mdn/content pull request #2185
Opened 2021-02-09 00:42 UTC by hamishwillee

Not supported in service workers. While this is now going to be clear in the BCD (see https://github.com/mdn/browser-compat-data/pull/8853) at the top of the page you have "Available in web workers" - so adding this note makes it clear that it is not available in "all web workers".

Also fixes flaws.

@peterbe Not sure what is happening with the AvailableInWorker macro going forward, but if this still exists, would be great if this could have ability to add replacement or appendable text.

2021-02-09 00:43 UTC, hamishwillee commented on files/en-us/web/api/xmlhttprequest/index.html
> +   use <a class="internal" href="/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest#open()"><code>open()</code></a> instead. See the documentation for <code>open()</code>.</dd>
This suggests using `nsIXMLHttpRequest#open()` from JavaScript, but that is archived. Is there an alternative that should be used?

2021-02-09 01:31 UTC, peterbe commented
> @peterbe Not sure what is happening with the AvailableInWorker macro going forward, but if this still exists, would be great if this could have ability to add replacement or appendable text.

Not sure I understand the question. Would you mind starting a new issue on mdn/yari specifically for the macro outside the context of this content PR?

2021-02-09 17:40 UTC, jpmedley requested changes

2021-02-09 17:40 UTC, jpmedley commented on files/en-us/web/api/xmlhttprequest/index.html
> +   use <a class="internal" href="/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest#open()"><code>open()</code></a> instead. See the documentation for <code>open()</code>.</dd>
@chrisdavidmills Review of this PR landed in my queue, but I don't know FF. Can you answer his question?

2021-02-09 18:40 UTC, chrisdavidmills commented on files/en-us/web/api/xmlhttprequest/index.html
> +   use <a class="internal" href="/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest#open()"><code>open()</code></a> instead. See the documentation for <code>open()</code>.</dd>
The entry is saying that `openRequest()` is a non-standard method that can be used to open requests from native/internal code, whereas to initialize a request from JS code, you would use the standard `open()` method.

So the link should point to `/en-US/docs/Web/API/XMLHttpRequest/open`, and you can just get rid of the "See the documentation for open()." bit too.

2021-02-12 01:10 UTC, hamishwillee commented on files/en-us/web/api/xmlhttprequest/index.html
> +   use <a class="internal" href="/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIXMLHttpRequest#open()"><code>open()</code></a> instead. See the documentation for <code>open()</code>.</dd>
Thanks. Done.

2021-02-12 01:12 UTC, hamishwillee commented
@chrisdavidmills This is ready for review. Most of it is flaw fixing - the most important bit is a simple note about worker support. This note is just a "hint" at the top - the more detailed information is already in BCD.

2021-02-12 07:34 UTC, chrisdavidmills approved these changes
All look good to me; let's get this merged.

2021-02-12 07:34 UTC, merged