Make User Timing overview page more overviewy
mdn/content pull request #21853
Opened 2022-10-26 17:21 UTC by Elchi3

### Description

This PR wants to make the https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API overview page better, or rather, less verbose and more overviewy. 

### Motivation

I'd like a better understanding what an overview page is exactly and what it should contain, so I'm re-arranging this one.
I want it to be distinct from the "[Using ...](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API/Using_the_User_Timing_API)" page.

### Additional details

So, to me, the structure of an overview page is this:

- Intro sentence that describes the purpose of the whole API and what to do with it
- Ideally a short example that is very typical for this API
- Lists of all the guide pages for this API
- Lists of all the reference pages of this API
- Other important info
- Maybe a compat table, but this is tricky
- See also

It is all very short and not rich in text. I see it as a cheatsheet or as a helper to navigate through all pages for this API.

It is a bit sad we don't have any styled page components. So I think my choices are lists (done here), or tables (ugly in md). I think tables arrange content nicely sometimes ([example](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming#events_exposed)), however I didn't feel like using them here. Let me know if you have other ideas.

### Related issues and pull requests

What are your favorite overview pages?

2022-10-26 22:44 UTC, wbamberg commented
FWIW I think these pages have quite a well-defined structure, and a template even, at https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template.

I think they have:
- a moderately short intro
- an H2 "Interfaces" that lists the interfaces the API defines
- an H2 "Specifications" section. I think this is quite important because these pages usually map to a single specification which in this case is https://w3c.github.io/user-timing/.

BCD I agree is problematic and I don't know what is best here. Different pages do different things. See https://github.com/mdn/content/discussions/4920 .

I agree that the current page is much too chatty and a lot of it should be in "Using the...".

2022-10-27 12:47 UTC, Elchi3 commented
> FWIW I think these pages have quite a well-defined structure, and a template even, at https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template.

Ah, thanks for the pointer!

> * an H2 "Interfaces" that lists the interfaces the API defines

I think I've shortened this quite a lot now so that it briefly lists what you can do with the two main interfaces. Actually, I think listing things you can to do with the interfaces at hand seems useful and more practical than listing things under "interfaces" and "Extension to other interfaces" (per the template) which seems like less practical info and like more like API design concerns. 
If I come to an overview page for an API, I think I want answers for: What is this API? What sort of tasks can I get done with it? So, on this overview page there are a few headings for tasks you can do, and then there are reference page pointers to the interfaces/methods/things that allow you to do a task. 

> * an H2 "Specifications" section. I think this is quite important because these pages usually map to a single specification which in this case is https://w3c.github.io/user-timing/.

Added a Specifications section with a link to the spec. Wasn't sure how to have generate a spec table for the whole API (and not a particular feature).
 
> BCD I agree is problematic and I don't know what is best here. Different pages do different things. See #4920 .

I didn't add any BCD table. Seems fine given it is well supported.

> I agree that the current page is much too chatty and a lot of it should be in "Using the...".

👍

2022-10-27 15:11 UTC, jpmedley requested changes, later dismissed
Florian,

This is _really_ clean of typos. Since this PR is about improving the piece over all, I thought you might be interested in a few language improvements. 

Joe

2022-10-27 15:11 UTC, jpmedley commented on files/en-us/web/api/user_timing_api/index.md
> +- {{domxref("PerformanceEntry.entryType","entryType")}}: set to "`measure`".
Please make the same changes as above.

2022-10-27 15:11 UTC, jpmedley commented on files/en-us/web/api/user_timing_api/index.md
> +- [`performance.getEntriesByName("myMeasure", "measure")`](/en-US/docs/Web/API/Performance/getEntriesByName) gets all measure with the name "myMeasure".
```suggestion
- [`performance.getEntriesByName("myMeasure", "measure")`](/en-US/docs/Web/API/Performance/getEntriesByName) gets all measures with the name "myMeasure".
```

2022-10-27 16:24 UTC, Elchi3 commented on files/en-us/web/api/user_timing_api/index.md
> +- {{domxref("PerformanceEntry.entryType","entryType")}}: set to "`mark`".
Yeah, I was confused by how this is written, too. I think that this meant to describe how inherited properties are qualified and therefore it uses "set to". I guess if we want to describe the interface, then we should describe it completely and not just what inheritance does.

2022-10-27 16:31 UTC, jpmedley commented on files/en-us/web/api/user_timing_api/index.md
> +- {{domxref("PerformanceEntry.entryType","entryType")}}: set to "`mark`".
I think you might be overthinking it. Consider where it would be used. If I have a collection of marks, I might need to distinguish between a mark and a measure. Do I need to know that it acquired this state through some form of inheritance?

2022-10-27 23:19 UTC, hamishwillee commented
@wbamberg Re https://github.com/mdn/content/pull/21853#issuecomment-1292743695

> FWIW I think these pages have quite a well-defined structure, and a template even, at https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template.

FWIW I think I've been guilty of copying the "big overview" pattern with user guide material. Sometimes it feels like it makes sense - or alternatively, that spawning a "Using guide" for a simple example feels like pointless indirection. 

What I find interesting about the template is that you should almost be able to generate the overview as defined from the API data used to create the sidebar.

2022-10-28 12:02 UTC, Elchi3 commented on files/en-us/web/api/user_timing_api/index.md
> +- {{domxref("PerformanceEntry.entryType","entryType")}}: set to "`mark`".
Updated.

2022-11-03 10:31 UTC, Elchi3 commented
Will and I think that this page isn't needed, because all you really need is an overview of all the Performance APIs and a guide that explains how to use them (together, and not separately). So, I think this PR is an improvement but it is likely we will redirect this page to https://developer.mozilla.org/en-US/docs/Web/API/Performance_API once we made that main Performance API page better (https://github.com/mdn/content/pull/21984). 

I'm going ahead and merge this, so we have the improvements in, in case we decide to keep this page (or if parts of it are still useful later).

2022-11-03 10:32 UTC, Elchi3 commented
Ah well, turns out I need 1 approving review. :)

2022-11-10 23:46 UTC, wbamberg commented
> What I find interesting about the template is that you should almost be able to generate the overview as defined from the API data used to create the sidebar.

Oh I just saw this. Yes. I want this to be one of our infra goals. Not all the overview but lots of it.

2022-11-10 23:47 UTC, wbamberg approved these changes
> Ah well, turns out I need 1 approving review. :)

👍

2022-11-10 23:47 UTC, merged