Add alt text
mdn/content pull request #21940
Opened 2022-10-29 23:45 UTC by dawei-wang

Add alt text to element-box-diagram.png
Relates to mdn/content#21616

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-02 18:36 UTC, estelle commented on files/en-us/web/api/element/getboundingclientrect/index.md
> +![Image showing returned value](element-box-diagram.png)
What is the return value?

2022-11-02 18:38 UTC, estelle requested changes
The alt attribute is a description of the image for those who cant see the image. It doesn't need to say "image", but it does need to provide all the contextually important information conveyed in the image.

2022-11-04 21:07 UTC, dawei-wang commented on files/en-us/web/api/element/getboundingclientrect/index.md
> +![Image showing returned value](element-box-diagram.png)
A  DOMRect object
I have updated the alt text

2022-11-07 14:56 UTC, estelle approved these changes

2022-11-07 14:57 UTC, merged