add docs for the Navigation API
mdn/content pull request #21960
Opened 2022-10-31 11:37 UTC by chrisdavidmills

### Description

This PR adds reference documentation for the [Navigation API](https://wicg.github.io/navigation-api/).

### Motivation

Readers will want information about this new API.

### Additional details

Further details can be found in my [Navigation API research](https://docs.google.com/document/d/1akJu6wbYXwX95FqrdhSiC8tlWDfuQ3FHIZk47prBJOI/edit#) document.

### Related issues and pull requests

Fixes #21909

2022-11-01 05:57 UTC, domenic reviewed
Overall this looks great!

One thing I think will be especially helpful to document is the contrast with the existing history and location APIs. Probably that is best done on the individual API sub-pages, though.

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +{{securecontext_header}}{{seecompattable}}{{DefaultAPISidebar("Navigation API")}}
I don't think there are any secure context restrictions on the feature.

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely.
Note that canceling traversals is not yet implemented anywhere, although we've updated the explainer and spec since we have an implementation in progress. I'm not sure whether that's necessary to mention here, or elsewhere, or not at all.

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +When the `initiate()` handler function's promise fulfills, the `Navigate` object's {{domxref("Navigation/navigatesuccess_event", "navigatesuccess")}} event fires, allowing you to run cleanup code aft
```suggestion
When the `intercept()` handler function's promise fulfills, the `Navigate` object's {{domxref("Navigation/navigatesuccess_event", "navigatesuccess")}} event fires, allowing you to run cleanup code after a successful navigation has completed. If it rejects, meaning the navigation has failed, {{domxref("Navigation/navigateerror_event", "navigateerror")}} fires instead, allowing you to gracefully handle the failure case. There is also a {{domxref("NavigationTransition.finished", "finished")}} property on the `NavigationTransition` object, which fullfills or rejects at the same time as the aforementioned events are fired, providing another path for handling the success and failure cases if it is needed.
```

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +Setting state is a bit more nuanced. You can't retrieve the state value and then update it directly — the copy stored on the entry will not change. Instead, you need to update it while performing a {
```suggestion
Setting state is a bit more nuanced. You can't retrieve the state value and then update it directly — the copy stored on the entry will not change. Instead, you need to update it while performing a {{domxref("Navigation.navigate", "navigate()")}} or {{domxref("Navigation.reload", "reload()")}} — each one of these optionally takes an options object parameter, which includes a `state` property containing the new state to set on the history entry. When these navigations commit, the state change will be automatically applied.
```

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +(I'M REALLY NOT SURE IF THIS SECTION ON STATE IS ACCURATE. I AM KINDA GUESSING AT THE "AUTOMATIC BEHAVIOR" MENTIONED ABOVE, AND WHEN UPDATECURRENTENTRY() SHOULD BE USED. NONE OF THE MATERIAL I'VE FOU
This part is indeed subtle. Some resources you may have seen:

- https://developer.chrome.com/docs/web-platform/navigation-api/#state (including the subsection)
- https://github.com/wicg/navigation-api#setting-the-current-entrys-state-without-navigating

Basically, we want the well-lit path to be that state updates are part of navigations/reloads. But there are some scenarios where you need to update state disconnected from any navigation, and that's what updateCurrentEntry() is for.

So I wouldn't talk about it as "automatic" vs. "manual", but more as "part of navigation/reload" vs. "independent from navigation/reload".

2022-11-01 05:57 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +    // Exit early if this navigation shouldn't be intercepted,
```suggestion
  // Exit early if this navigation shouldn't be intercepted, 
```

2022-11-01 07:19 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +{{securecontext_header}}{{seecompattable}}{{DefaultAPISidebar("Navigation API")}}
OK, removed in next commit.

2022-11-01 07:22 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely.
I've updated it to 

> **Note:** In future implementations you will be able to call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely. This is specced out, but not currently implemented anywhere.

We can always update it when the implementation lands. Let me know.

2022-11-01 07:39 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +(I'M REALLY NOT SURE IF THIS SECTION ON STATE IS ACCURATE. I AM KINDA GUESSING AT THE "AUTOMATIC BEHAVIOR" MENTIONED ABOVE, AND WHEN UPDATECURRENTENTRY() SHOULD BE USED. NONE OF THE MATERIAL I'VE FOU
Ah, brilliant, this makes more sense now. Thanks!

2022-11-01 07:40 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely.
Ah, sorry, it's a bit more subtle than that. Canceling ([most](https://github.com/wicg/navigation-api#appendix-types-of-navigations)) push/reload/replace navigations is possible today. It's the traverse navigations which are still a future feature.

You can see the diff, which represents what's not possible yet but will be soon, in https://github.com/WICG/navigation-api/commit/a430943e9e82c9288120f2201dabf588f126a273

2022-11-02 11:04 UTC, chrisdavidmills commented
@domenic all interface landing pages now created; see preview URLs in https://github.com/mdn/content/pull/21960#issuecomment-1296964628.

2022-11-04 05:59 UTC, domenic reviewed
Looking great!

A few comments I left are applicable across more than one document; I didn't note them each time. Also some comments about adding more detail might not make sense at this point, if each method/property is going to end up with its own page.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +The **`NavigateEvent`** interface of the {{domxref("Navigation API")}} is the event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fires when [any type of navigation
Nit: it's weird how "Navigation API" shows up in code font. Maybe `domxref` isn't appropriate? Not sure.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the URL being navigated to.
This actually returns a NavigationDestination object, containing various info including but not limited to the URL.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the type of the navigation, which is one of `push`, `reload`, `replace`, or `traverse`.
Should these strings be marked up with quotes, e.g. `"push"`?

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns an {{domxref("AbortSignal")}}, which will become aborted if the navigation is cancelled (e.g. by the user pressing the browser's "Stop" button).
Maybe also mention the case where another navigation starts and thus cancels the ongoing one.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +  - : Intercepts this navigation, turning it into a same-document navigation to the {{domxref("NavigateEvent.destination", "destination")}} URL. It can accept a handler that defines what the navigati
```suggestion
  - : Intercepts this navigation, turning it into a same-document navigation to the {{domxref("NavigateEvent.destination", "destination")}} URL. It can accept a handler that defines what the navigation handling behavior should be, plus options to control autofocus and scroll behavior as desired.
```

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigateevent/index.md
> +  - : Intercepts this navigation, turning it into a same-document navigation to the {{domxref("NavigateEvent.destination", "destination")}} URL. It can accept a handler that defines what the navigati
It feels like the options it takes probably should be called out by name somehow? Not sure what the usual MDN style is for documenting option bags.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigation/index.md
> +The Navigation API only creates history entries created directly in the application document (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate list o
It isn't limited to same-document, so saying "application document" doesn't seem right.

It also can create history entries outside (e.g. `navigation.navigate("https://other.example/")`), so I think maybe s/creates/exposes.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigation/index.md
> +  - : Fired when a successful navigation has completed.
Maybe more detail on what "fails" / "successful" mean?

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigation/index.md
> +- {{domxref("Navigation.back", "back()")}}
Is there a way to document the options each of these take? Or I guess that would be done on the sub-pages?

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigationcurrententrychangeevent/index.md
> +  - : Returns the {{domxref("NavigationHistoryEntry")}} that has changed.
I wouldn't necessarily say that it changed. It's rather the one we came from.

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigationcurrententrychangeevent/index.md
> +  const data = navigation.currentEntry.getState()
```suggestion
  const data = navigation.currentEntry.getState();
```

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigationdestination/index.md
> +  - : Returns `true` if the navigation is to the same `document` as the current {{domxref("Window.document")}} value, or `false` otherwise.
Instead of `document`, link to https://developer.mozilla.org/en-US/docs/Web/API/Document ?

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigationdestination/index.md
> +  - : Returns the available `state` associated with the destination {{domxref("NavigationHistoryEntry")}}, or navigation operation (e.g. {{domxref("Navigation.navigate()", "navigate()")}}) as appropr
I'm not sure `state` should be in code, since there's no actual state property.

Also maybe it's worth mentioning that it'll be a [clone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm).

2022-11-04 05:59 UTC, domenic commented on files/en-us/web/api/navigationtransition/index.md
> +The **`NavigationTransition`** interface of the {{domxref("Navigation API")}} represents an ongoing navigation, that is, a navigation that hasn't yet reached the {{domxref("Navigation/navigatesuccess
Probably `navigatesuccess` and `navigateerror` instead of just `success` and `error`?

2022-11-04 07:53 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely.
Ah! I see. I've updated it again, to 

> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely in most cases. This works today for most push, reload, and replace navigations; cancellation of traverse navigations is not yet implemented.

I'll keep it simple for now here, and then link to your explainer text when it is published.

2022-11-04 07:57 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +The **`NavigateEvent`** interface of the {{domxref("Navigation API")}} is the event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fires when [any type of navigation
I've always found this slightly odd, but this seems to be how things are done around here. The current way to fix it would be to use a plain link rather than a macro, but of course, then you lose the flexibility of updating all the links by rewriting one macro, if the URL schema changes.

What really needs to happen is for the macro to be rewritten so that it doesn't add the code font if the link text ends in " API", or similar.

2022-11-04 08:06 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the URL being navigated to.
D'oh; I don't know what happened there; I've updated this, and other related descriptions. Thanks!

2022-11-04 08:12 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the type of the navigation, which is one of `push`, `reload`, `replace`, or `traverse`.
If I remember rightly, that doesn't fit with the MDN style, although I can understand why you'd suggest it. For now, I've updated it to say that this is "a string equal to", to make it more obvious.

2022-11-04 08:14 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns an {{domxref("AbortSignal")}}, which will become aborted if the navigation is cancelled (e.g. by the user pressing the browser's "Stop" button).
Added, thanks!

2022-11-04 08:14 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Intercepts this navigation, turning it into a same-document navigation to the {{domxref("NavigateEvent.destination", "destination")}} URL. It can accept a handler that defines what the navigati
Fixed in next commit, cheers.

2022-11-04 08:20 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Intercepts this navigation, turning it into a same-document navigation to the {{domxref("NavigateEvent.destination", "destination")}} URL. It can accept a handler that defines what the navigati
We include detailed descriptions of each option on the individual member page, but I've updated this so that the actual property names are included — could same someone a few seconds if they just want to quickly look up a property name and land on this page.

2022-11-04 08:30 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +  - : Fired when a successful navigation has completed.
Added in the individual member pages.

2022-11-04 08:30 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +- {{domxref("Navigation.back", "back()")}}
Yup, done on the subpages.

2022-11-04 08:31 UTC, chrisdavidmills commented on files/en-us/web/api/navigationcurrententrychangeevent/index.md
> +  - : Returns the {{domxref("NavigationHistoryEntry")}} that has changed.
Good call; updated.

2022-11-04 08:33 UTC, chrisdavidmills commented on files/en-us/web/api/navigationcurrententrychangeevent/index.md
> +  const data = navigation.currentEntry.getState()
Fixed, ta.

2022-11-04 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigationdestination/index.md
> +  - : Returns `true` if the navigation is to the same `document` as the current {{domxref("Window.document")}} value, or `false` otherwise.
Good call; changed.

2022-11-04 08:46 UTC, chrisdavidmills commented on files/en-us/web/api/navigationdestination/index.md
> +  - : Returns the available `state` associated with the destination {{domxref("NavigationHistoryEntry")}}, or navigation operation (e.g. {{domxref("Navigation.navigate()", "navigate()")}}) as appropr
I've updated the code style of state in a few places where it isn't appropriate, and updated all `getState()` descriptions to specify that they return a clone of the state

2022-11-04 08:47 UTC, chrisdavidmills commented on files/en-us/web/api/navigationtransition/index.md
> +The **`NavigationTransition`** interface of the {{domxref("Navigation API")}} represents an ongoing navigation, that is, a navigation that hasn't yet reached the {{domxref("Navigation/navigatesuccess
Updated

2022-11-04 08:49 UTC, chrisdavidmills commented
@domenic thanks for all the great review comments. I've answered them all, and added all the member pages for the `Navigate` interface.

2022-11-07 11:27 UTC, chrisdavidmills commented
Hi @domenic ! I've now created all of the pages for the Navigation API. The preview URLs are her: https://github.com/mdn/content/pull/21960/#issuecomment-1296964628

There are a lot of pages here; I don't think you need to go through everything with a fine toothcomb. I've used the same narrative and examples as I have on pages you've already seen. And If something is wrong in one place, it'll be the same in other places.

I think my main concerns are:

* I wonder if some of the examples are a bit weak, but then again it'll be nice to get this published, and we can improve examples over time.
* I wanted to include a solid definition of the different navigation types, e.g. see https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigateEvent/navigationType#value. Does my description sound OK?

2022-11-08 06:47 UTC, domenic commented
This generally looks great! Your description of navigation types sounds perfect.

Only a couple minor things I noticed clicking around:

- https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigateEvent/canIntercept says "missing spec data"

- https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Navigation/forward and pages like it (e.g. https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Navigation/navigatesuccess_event) have very confusing "Syntax" sections, because they are missing `navigation.`. I.e. I would expect `navigation.forward(options)`, not `forward(options)`.

- https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigationHistoryEntry/dispose_event would benefit from describing the scenarios where disposal happens in more detail. They are:
  - Forward history entries are cleared, e.g. as in the example at https://github.com/wicg/navigation-api#notifications-on-entry-disposal
  - The user clears their history using browser settings or UI
  - You go over the 50-page history limit (not specified anywhere, but widely implemented; see e.g. https://www.google.com/search?q=history+length+limit+50)

2022-11-08 07:22 UTC, chrisdavidmills commented
Thanks @domenic! Some answers to your points:

> https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigateEvent/canIntercept says "missing spec data"

Ah yeah, this is because the BCD additions I made for the Navigation API haven't been merged yet. The data was mostly there already, but I needed to added this one.

> https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Navigation/forward and pages like it (e.g. https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Navigation/navigatesuccess_event) have very confusing "Syntax" sections, because they are missing navigation.. I.e. I would expect navigation.forward(options), not forward(options).

This is an interesting point. I've done it just like Syntax is shown in all the other MDN pages. I can see why you'd say this, but I guess the trouble is that we are just talking about the syntax of the particular method, and not its parent object...if you did this you'd be getting into the realm of a code example rather than pure syntax. And the code example, later on, shows the actual usage. I have passed this feedback on to see what the MDN powers that be think.

> https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigationHistoryEntry/dispose_event would benefit from describing the scenarios where disposal happens in more detail.

Good call; adding this in the next commit.

2022-11-09 01:27 UTC, wbamberg requested changes
This is only part of the review, but since this is a big PR I thought it would be better to do it in pieces.

Next I will look at the `Navigation` interface.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +As the user navigates through your application, each new location navigated to results in the creation of a navigation history entry. Each history entry is represented by a distinct {{domxref("Naviga
```suggestion
As the user navigates through your application, each new location navigated to results in the creation of a navigation history entry. Each history entry is represented by a distinct {{domxref("NavigationHistoryEntry")}} object instance. These contain several properties such as the entry's key, URL, and state information. You can get the entry that the user is currently on right now using {{domxref("Navigation.currentEntry")}}, and an array of all existing history entries using {{domxref("Navigation.entries()")}}. Each `NavigationHistoryEntry` object has a {{domxref("NavigationHistoryEntry/dispose_event", "dispose")}} event, which fires when the entry is no longer part of the browser history. For example, if the user navigates back three times, then navigates forward to somewhere else, those three history entries will be disposed of).
```

I think it is worth including the interface name in the links, hence `Navigation.currentEntry` rather than just `currentEntry`.

I wasn't at all clear on what "key" means here, but maybe not worth going into that now.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
I don't know what "created directly by the application" means. Does it include (e.g.) links within the same origin? They don't seem to be "created directly by the application" but are also not cross-origin. And I'm not sure either tbh what "iframe navigations" are and how they are not covered by cross-origin navigations. Maybe I am just being ignorant here.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +In some cases however, a state change will be independent from a navigation or reload — for example when a page contains an expandable/collapsible {{htmlelement("details")}} element. In this case, yo
```suggestion
In some cases however, a state change will be independent from a navigation or reload — for example when a page contains an expandable/collapsible {{htmlelement("details")}} element. In this case, you might want to store the expanded/collapsed state in your history entry, so you can restore it when the user returns to the page or restarts their browser. Cases like this are handled using {{domxref("Navigation.updateCurrentEntry()")}}. The {{domxref("Navigation/currententrychange_event", "currententrychange")}} will fire when the current entry change is complete.
```

(I think it is helpful to show the interface this is on.)

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +There are a few perceived limitations with the Navigation API, which may or may not be limiting depending on how your app is set up. Find out about these by reading [Modern client-side routing: the N
Is there a reason not to have this on MDN?

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +  - : Allows control over all navigation actions for the current `window` in one central place, including initiating navigations programmatically, introspecting navigation history entries, and managi
```suggestion
  - : Allows control over all navigation actions for the current `window` in one central place, including initiating navigations programmatically, examining navigation history entries, and managing navigations as they happen.
```

(again, unless "introspecting" is important.)

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +- {{domxref("Navigation")}}
I think these should be listed in alphabetical order.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +  - : Event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fires when [any type of navigation](https://github.com/WICG/navigation-api#appendix-types-of-navigations)
Again it would be great to have "any type of navigation" documented on MDN.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +## Extensions to the `Window` interface
FWIW the template wants to call this heading "Extensions to other interfaces" (https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template#extensions_to_other_interfaces) which I also like because it makes headings consistent.

2022-11-09 01:27 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +{{Specifications}}
There's only one spec so it's unfortunate that we have two spec entries here. I guess that's because we have 2 BCD queries. We are in a bit of a mess wrt BCD and spec URLs, especially regarding API overview pages. But maybe it would be better to use a spec-url front matter key? Although tbh I'm not sure if that will work to override the BCD ones, or if you will just end up with three of them...

2022-11-09 01:27 UTC, wbamberg commented on files/jsondata/GroupData.json
> +    },
I'm not sure why we are adding this API. For the performance doc revamp we decided to treat all the perf APIs as a single group (https://github.com/openwebdocs/project/issues/62#issuecomment-1303278689), and this would conflict with that approach.

2022-11-09 05:16 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
Oh, and `{{domxref("History API")}}` gives us code formatting which we should only have for identifiers. So either a normal Markdown link, or pass the extra runes to domxref to stop code formatting.

2022-11-09 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +- {{domxref("NavigateEvent.intercept", "intercept()")}} allows you to control what happens when the navigation is initiated using a callback handler function, which should return a promise. For examp
Fixed in the next commit

2022-11-09 07:59 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** You can also call {{domxref("Event.preventDefault", "preventDefault()")}} to stop the navigation entirely in most cases. This works today for most push, reload, and replace navigations; c
I've added a link to the `navigationType` page where those types are explained, and cleaned up the language a bit. I think I still need to say that traverse navigations are not yet cancellable. I'll have to update it when it lands.

2022-11-09 08:12 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
This is a difficult one ; I've tried rewriting it to :

> The Navigation API only exposes history entries created directly by the application's top-level context (e.g. not navigations inside embedded {{htmlelement("iframe")}}s), providing an accurate list of all previous history entries just for your app. This makes traversing the history a much less fragile proposition than the older {{domxref("History API")}}.

I deleted the bit about cross-origin, because I'm really not sure about it, but the iframes bit makes the point well enough, I feel.

2022-11-09 08:21 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
The cross-origin bit is kind of important.

Example:

- Navigate to `https://a.example.com/`, then `https://a.example.com/1`.
- Then navigate to `https://b.example.com/`, `https://b.example.com/1` in the same tab.
- `navigation.entries().length === 2`, because we only look at the same-origin entries on `b.example.com`. We don't look at the cross-origin ones on `a.example.com`.
- Similarly, if you call `navigation.back()` once to get to `https://b.example.com/`, then `navigation.canGoBack` is false, since there's no same-origin entry backwards.

In contrast, with the old history API, cross-origin entries do appear. E.g. `history.length === 4`, and `history.back()` works even when you're on the `https://b.example.com/` entry.

2022-11-09 08:32 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +There are a few perceived limitations with the Navigation API, which may or may not be limiting depending on how your app is set up. Find out about these by reading [Modern client-side routing: the N
Laziness, I guess ;-) I've added in a cut down version of it.

2022-11-09 08:35 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +- {{domxref("Navigation")}}
I kind of did, but decided to put the event objects at the end in a separate alphabetical list.

2022-11-09 08:36 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +## Extensions to the `Window` interface
If there's a convention to follow, then I'm fine to follow it. Updated.

2022-11-09 08:38 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +## Extensions to the `Window` interface
Lol, I think I wrote a bunch of that stuff, back in the day ;-)

2022-11-09 08:43 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +{{Specifications}}
I don't know what you mean by "spec-url front matter key".

I could just include a single browser compact entry, as it would still provide an idea.

2022-11-09 08:43 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
> +    },
I didn't deliberately add this. I think it crept in as the result of a merge conflict fix. I'll remove it again.

2022-11-09 08:48 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
Thanks for the explanation @domenic ; added back in.

2022-11-09 08:58 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +  - : Event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fires when [any type of navigation](https://github.com/WICG/navigation-api#appendix-types-of-navigations)
I would hesitate to do this for now, as that section is quite long and has some complex details in it, and I don't think it'd make sense to maintain it in two places. 

@domenic , is this something you'd like to see on MDN, or would you prefer to keep it in the explainer for now?

2022-11-09 18:57 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +{{Specifications}}
You can include an item in the front matter YAML for the page like: https://github.com/mdn/content/blob/737906473648cfdc3622a7efb4414949ec2ff7fc/files/en-us/web/css/display-inside/index.md?plain=1#L12

...I think that will then be used for the specifications section instead of BCD (?). I hope so anyway.

> I could just include a single browser compact entry, as it would still provide an idea.

If the `spec-urls` thing works as expected it would be better, because the BCD entry will presumably link to a fragment inside the spec, while in an overview page we really want to just link to the spec AFAICT.

2022-11-09 18:58 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +- {{domxref("Navigation")}}
It's a minor point, but I do think consistent alpha order is the best option.

2022-11-09 23:39 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
So, sorry again if I'm being ignorant, but: is it correct then to say that it includes only entries that are same-domain with the current entry?

So e.g.

- I start a new tab on developer.mozilla.org -> 1 entry
- I navigate to https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade -> 2 entries
- I navigate to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors -> 3 entries
- I navigate to https://support.mozilla.org/en-US/products/mdn-plus -> 1 entry (the support.mozilla.org one)
- I navigate to https://support.mozilla.org/en-US/contribute -> 2 entries (the support.mozilla.org ones)
- I go back twice, to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors -> 3 entries (the developer.mozilla.org ones)

That's what I see. So "created directly by the application's top-level context" reads weirdly to me. I might think: in the cases above "the application" didn't "directly create" the navigation, the user did, by clicking a link. In particular I might think "created directly by the application" means "created as a result of a `navigate()` call".

So is it correct to say just "The Navigation API only exposes history entries for the top-level browsing context and that have the same origin as the current page, providing an accurate list of all previous history entries just for your app. This makes traversing the history a much less fragile proposition than the older {{domxref("History API")}}." ?

2022-11-09 23:42 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
> And when you say "So either a normal Markdown link, or pass the extra runes to domxref to stop code formatting.", what do you mean by that? I never came across a way to do that in domxref when I was at Mozilla, and I was wondering about it just the other day ;-)

See: https://github.com/mdn/yari/blob/43d4672746860ed27d5d504eafd00ae377da0434/kumascript/macros/DOMxRef.ejs#L13-L14

So you need something like `{{domxref(name, linkText, "", "joy division oven gloves")}}`

2022-11-10 00:48 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
> is it correct then to say that it includes only entries that are same-domain with the current entry?

Same [origin](https://url.spec.whatwg.org/#concept-url-origin); not same-[domain](https://url.spec.whatwg.org/#concept-domain). But basically yes.

> The Navigation API only exposes history entries for the top-level browsing context

This is not correct. It exposes history entries for the current frame. It doesn't matter whether that frame is top level or not.

Note that this is different than the classic history API. You can see this given the following scenario: https://domenic.github.io/jake-diagram-generator/#IWN1cnJlbnQgPSAxCnRvcAogIDAtMjogL3QtYSB8IGRvYzEKICAzOiAvdC1hI2ZvbyB8IGRvYzEKICA0OiAvdC1iCmZyYW1lc1swXQogIDA6IC9pLTAtYQogIDEtMzogL2ktMC1iCmZyYW1lc1sxXQogIDAtMTogL2ktMS1hCiAgMi0zOiAvaS0xLWIK

The classic history API exposes one entry for each step. (Sort of. You can't directly introspect the entries; you can only see `history.length`, and what happens if you do `history.back()` etc.) The navigation API exposes only your frame's entries: so, for `top`, it exposes [`/t-a`, `/t-a#foo`, `/t-b`]; for `frames[0]` it exposes [`/i-0-a`, `/i-0-b`]; and for `frames[1]` it exposes [`/i-1-a`, `/i-1-b`].

This might be worth its own subsection, perhaps? With an example like this one? Dunno.

2022-11-10 04:48 UTC, wbamberg requested changes
OK, here are comments on the `Navigation` interface!

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/navigate_event/index.md
> +  if (shouldNotIntercept(event)) return;
According to the code style guidelines we should have braces here: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript#use_braces_with_control_flow_statements_and_loops.

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/navigate_event/index.md
> +  if (shouldNotIntercept(navigateEvent)) return;
Again, according to the code style guidelines we should have braces here: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript#use_braces_with_control_flow_statements_and_loops.

Since this pattern is repeated a few times I won't point it out every time.

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/navigateerror_event/index.md
> +> **Note:** The event object is of type {{domxref("ErrorEvent")}}.
See https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_event_subpage_template#event_type for how we handle event types.

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/navigatesuccess_event/index.md
> +This means that all promises returned by your `intercept()` handler are fulfilled. This is equivalent to the {{domxref("NavigationTransition.finished")}} promise fulfilling.
> This means that all promises returned by your `intercept()` handler are fulfilled.

Not sure I understand this. What if I didn't run an `intercept()` handler? Is this event not fired?

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/reload/index.md
> +- either one of the above promises rejects, meaning that the navigation has failed for some reason.
```suggestion
An object with the following properties:

- `committed`
  - : A {{jsxref("Promise")}} which will fulfill when the visible URL has changed and a new {{domxref("NavigationHistoryEntry")}} has been created.
- `finished`
  - : A {{jsxref("Promise")}} which will fulfill when all promises returned by the `intercept()` handler are fulfilled. This is equivalent to the {{domxref("NavigationTransition.finished")}} promise fulfilling, when the {{domxref("Navigation/navigatesuccess_event", "navigatesuccess")}} event fires.
 
Either one of these promises rejects if the navigation has failed for some reason.
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/reload/index.md
> +Usage of info and state
```suggestion
### Using info and state
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/transition/index.md
> +    which can be used to track it.
```suggestion
The **`transition`** read-only property of the {{domxref("Navigation")}} interface returns a {{domxref("NavigationTransition")}} object representing the status of an in-progress navigation, which can be used to track it.
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/transition/index.md
> +A {{domxref("NavigationTransition")}} object, or `null` in no navigation is currently in progress.
```suggestion
A {{domxref("NavigationTransition")}} object, or `null` if no navigation is currently in progress.
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/transition/index.md
> +  await navigation.transition.finished;
Same comment about top-level await.

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/traverseto/index.md
> +{{domxref("Navigation")}} interface navigates to a specific {{domxref("NavigationHistoryEntry")}} by {{domxref("NavigationHistoryEntry.key", "key")}}.
```suggestion
The **`traverseTo()`** method of the {{domxref("Navigation")}} interface navigates to the {{domxref("NavigationHistoryEntry")}} identified by the given {{domxref("NavigationHistoryEntry.key", "key")}}.
```

(I think?)

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/traverseto/index.md
> +traverseTo(key, options)
```suggestion
traverseTo(key)
traverseTo(key, options)
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/traverseto/index.md
> +- either one of the above promises rejects, meaning that the navigation has failed for some reason.
```suggestion
An object with the following properties:

- `committed`
  - : A {{jsxref("Promise")}} which will fulfill when the visible URL has changed and a new {{domxref("NavigationHistoryEntry")}} has been created.
- `finished`
  - : A {{jsxref("Promise")}} which will fulfill when all promises returned by the `intercept()` handler are fulfilled. This is equivalent to the {{domxref("NavigationTransition.finished")}} promise fulfilling, when the {{domxref("Navigation/navigatesuccess_event", "navigatesuccess")}} event fires.
 
Either one of these promises rejects if the navigation has failed for some reason.
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/updatecurrententry/index.md
> +    in cases where the state change will be independent from a navigation or reload.
```suggestion
The **`updateCurrentEntry()`** method of the {{domxref("Navigation")}} interface updates the `state` of the {{domxref("Navigation.currentEntry","currentEntry")}}; used in cases where the state change will be independent from a navigation or reload.
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/updatecurrententry/index.md
> +updateCurrentEntry(options)
```suggestion
updateCurrentEntry()
updateCurrentEntry(options)
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/updatecurrententry/index.md
> +`undefined`.
```suggestion
None (`undefined`).
```

2022-11-10 04:48 UTC, wbamberg commented on files/en-us/web/api/navigation/updatecurrententry/index.md
> +You could use something like the following to update the open/closed state of a {{htmlelement("details")}} element so that the state can be restored when reloading the page, or navigating back from s
```suggestion
You could use something like the following to update the open/closed state of a {{htmlelement("details")}} element so that the state can be restored when reloading the page or navigating back from somewhere else.
```

2022-11-10 06:44 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +- {{domxref("Navigation")}}
OK, updated in next commit

2022-11-10 06:49 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +{{Specifications}}
I've tried it, and the result is that we end up with three spec URLs listed rather than two. I could see this totally making sense if the `spec-urls` override the URLs taken from the `browser-compat` entries, but it is additive.

I'll leave my content as-is, for now.

2022-11-10 06:58 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
> So you need something like {{domxref(name, linkText, "", "joy division oven gloves")}}

Ah ha, it works! So now I know what to do for future instances like this. thanks @wbamberg . And I love the Half-Man Half-Biscuit reference.

2022-11-10 07:13 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
So for the note, taking into account previous discussions, I've now changed it to 

> Note: The Navigation API only exposes history entries created in the current browsing context that have the same origin as the current page (e.g. not navigations inside embedded [<iframe>](http://localhost:5042/en-US/docs/Web/HTML/Element/iframe)s, or cross-origin navigations), providing an accurate list of all previous history entries just for your app. This makes traversing the history a much less fragile proposition than the older [History API](http://localhost:5042/en-US/docs/Web/API/History_API).

Does this work? I'd rather not talk about frames, as I fear that this might make developers think about code running just in <iframe>s or <frames>. And document is not correct either, because the document will change if a different distinct page is navigated to...

I'd also rather not expand this to a big separate section if we can avoid it, as I think it might potentially confuse things further.

2022-11-10 07:38 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +The **`Navigation`** interface of the {{domxref("Navigation API")}} allows control over all navigation actions for the current `window` in one central place, including initiating navigations programm
Fixed both of these in the next commit; I've fixed all of code formatting for the API links, on all pages.

2022-11-10 07:40 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate list of all pre
I've updated the text to the same as the note on the overview.

I agree with "with"; I've added that in both places.

2022-11-10 07:42 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +    which can be used to track it. Returns `null` in no navigation is currently in progress.
Fixed here, and on the relevant member page.

2022-11-10 07:46 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +### `Navigation` events
OK, got it. I've fixed this here, and on other class pages that list events.

2022-11-10 07:47 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +  - : Fired when [any type of navigation](https://github.com/WICG/navigation-api#appendix-types-of-navigations) is initiated, allowing you to intercept as required.
Same comment as before.

2022-11-10 08:18 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +  await navigation.back().finished;
Heh, I did wonder if this would come back to bite me. Bit of a naughty shortcut really. I've gone through these docs and made sure that all example snippets are wrapped in async functions where appropriate.

2022-11-10 08:18 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/index.md
> +await navigation.navigate('/another_url').finished;
fixed

2022-11-10 08:18 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/back/index.md
> +  await navigation.back( { info: "swipe-right" } ).finished;
fixed

2022-11-10 08:22 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/back/index.md
> +  ...
well, it is supposed to indicate that in a real code example, more code would probably go here. I think it is ok for that purpose. One thing I noticed Jean-Yves doing when he reviewed another PR was adding a comment syntax — // ... — so that it was more obvious that this isn't part of the actual syntax. I think I'll stick to that convention going forward. I'll update this one and others

2022-11-10 08:23 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/back/index.md
> +  ...
Hrm, actually in this case I'll remove it, but in others I'll stick to the aforementioned convention

2022-11-10 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/cangoback/index.md
> +}
Back and forward are two sides of the same coin; I think it's part of the same example and it's not too long, so I want to leave it in.

2022-11-10 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/cangoforward/index.md
> +}
same comment as above

2022-11-10 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/forward/index.md
> +}
same as before

2022-11-10 08:39 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate_event/index.md
> +The **`navigate`** event of the {{domxref("Navigation")}} interface is fired when [any type of navigation](https://github.com/WICG/navigation-api#appendix-types-of-navigations) is initiated, allowing
same comment from me as before, too

2022-11-10 08:58 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate_event/index.md
> +> **Note:** The event object is of type {{domxref("NavigateEvent")}}.
Ah, nice one. I've updated all the event pages to suit.

2022-11-10 08:58 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/currententrychange_event/index.md
> +> **Note:** The event object is of type {{domxref("NavigationCurrentEntryChangeEvent")}}.
Updated

2022-11-10 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate_event/index.md
> +  if (shouldNotIntercept(event)) return;
Ah, good call. I've gone through and fixed this in all places it appears.

2022-11-10 09:16 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate_event/index.md
> +  if (shouldNotIntercept(navigateEvent)) return;
fixed 'em all.

2022-11-10 09:16 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigateerror_event/index.md
> +> **Note:** The event object is of type {{domxref("ErrorEvent")}}.
fixed

2022-11-10 09:22 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigatesuccess_event/index.md
> +This means that all promises returned by your `intercept()` handler are fulfilled. This is equivalent to the {{domxref("NavigationTransition.finished")}} promise fulfilling.
Yeah, that was a bit confusingly-phrased. I've updated it to 

> In the case of an intercepted navigation, this would occur after any promises returned by your {{domxref("NavigateEvent.intercept", "intercept()")}} handler are fulfilled. The {{domxref("NavigationTransition.finished")}} promise will also fulfill at the same time.

2022-11-10 09:22 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/transition/index.md
> +  await navigation.transition.finished;
yup, fixed 'em

2022-11-10 09:38 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/transition/index.md
> +A {{domxref("NavigationTransition")}} object, or `null` in no navigation is currently in progress.
Fixed.

2022-11-10 09:40 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/currententrychange_event/index.md
> +This event will fire for same-document navigations (e.g. {{domxref("Navigation.back", "back()")}} or {{domxref("Navigation.traverseTo", "traverseTo()")}}), replacements (i.e. a {{domxref("Navigation.
fixed

2022-11-10 17:09 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +{{Specifications}}
Fair enough. I wish this stuff worked better.

2022-11-10 17:14 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
This is much, much clearer to me :)

2022-11-10 17:20 UTC, wbamberg commented on files/en-us/web/api/navigation/back/index.md
> +  ...
Yes, fair enough in that case, but as you say we should wrap it in comments otherwise at some point a linter will complain about it.

2022-11-10 17:23 UTC, wbamberg commented on files/en-us/web/api/navigation/cangoback/index.md
> +and `false` if it is not.
I also like the style of not breaking inside paragraphs. I don't want to ask you to go and reformat loads of pages, but yes, for future reference. @hamishwillee does reformat pages that do this when he makes unrelated changes to them though :).

2022-11-10 23:58 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
It's unfortunate that MDN is still referencing the outdated concept of browsing context, but maybe that's not an issue we need to solve in this PR...

2022-11-11 07:08 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +> **Note:** The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate lis
@domenic Ah, I wasn't aware that this was now out of date. At some point I'd love to explore what we should be saying instead.

2022-11-11 18:28 UTC, wbamberg commented on files/en-us/web/api/navigation/navigate/index.md
> +      - : Developer-defined information to be stored in the associated {{domxref("NavigationHistoryEntry")}} once the navigation is complete, retrievable via {{domxref("NavigationHistoryEntry.getStat
Am I right that this must be structured-clonable?

```js
const element = document.querySelector("h1");
navigation.navigate("https://example.org", {state: element});
// Failed to execute 'navigate' on 'Navigation': HTMLHeadingElement object could not be cloned.
```

If so, this should be explained everywhere we can do this, like `reload()`, and also as an exception in `### Exceptions` below.

But it seems like `info` does not have to be structured-clonable?

2022-11-14 07:08 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate/index.md
> +      - : Developer-defined information to be stored in the associated {{domxref("NavigationHistoryEntry")}} once the navigation is complete, retrievable via {{domxref("NavigationHistoryEntry.getStat
Yeah, I think you are right. Following the links in the spec, I eventually came across this algorithm, which I think is relevant here: https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal

And yeah, if you read the navigate algorithm here, it looks like info doesn't follow that same algorithm, and can be anything: https://wicg.github.io/navigation-api/#dom-navigation-navigate

I'll update just the navigate page for now so you can see what it feels like. If that looks good, I'll update the others.

2022-11-14 07:14 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate/index.md
> +      - : Developer-defined information to be stored in the associated {{domxref("NavigationHistoryEntry")}} once the navigation is complete, retrievable via {{domxref("NavigationHistoryEntry.getStat
OK, added. Let me know what you think.

2022-11-14 22:45 UTC, wbamberg commented on files/en-us/web/api/navigation/navigate/index.md
> +      - : Developer-defined information to be stored in the associated {{domxref("NavigationHistoryEntry")}} once the navigation is complete, retrievable via {{domxref("NavigationHistoryEntry.getStat
Looks great to me!

2022-11-15 16:24 UTC, chrisdavidmills commented on files/en-us/web/api/navigation/navigate/index.md
> +      - : Developer-defined information to be stored in the associated {{domxref("NavigationHistoryEntry")}} once the navigation is complete, retrievable via {{domxref("NavigationHistoryEntry.getStat
@wbamberg OK, added that info to the other relevant pages too.

Do you have any other comments about this PR? What you've reviewed so far has been amazingly useful

2022-11-16 06:06 UTC, wbamberg reviewed
This is for `NavigationHistoryEntry`. Sorry to be slow getting through them.

2022-11-16 06:06 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/getstate/index.md
> +let current = navigation.currentEntry;
```suggestion
const current = navigation.currentEntry;
```

(could have a more thorough/helpful example showing state getting set).

2022-11-16 06:06 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/id/index.md
> +{{domxref("NavigationHistoryEntry")}} interface returns the `id` of the history entry. This is a unique, UA-generated value that always represents the history entry, useful to correlate a history ent
I think it might be helpful explicitly to explain how this is different from `key`.

2022-11-16 06:06 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/id/index.md
> +A string representing the `id` of the destination {{domxref("NavigationHistoryEntry")}}.
```suggestion
A string representing the `id` of the {{domxref("NavigationHistoryEntry")}}.
```

2022-11-16 06:06 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/id/index.md
> +let current = navigation.currentEntry;
```suggestion
const current = navigation.currentEntry;
```

2022-11-16 06:06 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/index.md
> +  - : Returns the index of the history entry in the history entries list (i.e. returned by {{domxref("Navigation.entries()")}}), or `-1` if the entry does not appear in the list.
```suggestion
  - : Returns the index of the history entry in the history entries list (that is, the list returned by {{domxref("Navigation.entries()")}}), or `-1` if the entry does not appear in the list.
```

2022-11-16 15:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index.md
> +The Navigation API only exposes history entries created directly by the application (i.e. not {{htmlelement("iframe")}} navigations or cross-origin navigations), providing an accurate list of all pre
Good call; updated in the next commit.

And don't worry about the speed of review — I appreciate that this is a really big one.

2022-11-16 15:46 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index.md
> +async function initHomeBtn() {
Good point. I've updated those snippets

2022-11-16 15:59 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index.md
> +}
This is a nice little example, but I kinda think it is overkill for what I'm trying to show here. I've assumed we are dealing with an SPA, as this is what this API is for. So realistically you would be dealing with the same page all the time, just with different content in injected into the main content container. The idea is that you are getting the key of the currentEntry when the current entry is the home page, and setting up the event listener so that the home button will always navigate back to that history entry.

I've updated the code comments to make them less confusing ("different page" did imply that we are loading a different page ;-) ), and I've added a skeleton navigation handler to indicate further that these are single-page navigations.

2022-11-16 16:00 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index/index.md
> +{{domxref("NavigationHistoryEntry")}} interface returns the index of the history entry in the history entries list (i.e. returned by {{domxref("Navigation.entries()")}}), or `-1` if the entry does no
updated!

2022-11-16 16:03 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index/index.md
> +A number representing the `index` of the destination {{domxref("NavigationHistoryEntry")}}, or `-1`.
changed

2022-11-16 16:21 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/id/index.md
> +A string representing the `id` of the destination {{domxref("NavigationHistoryEntry")}}.
updated

2022-11-16 16:21 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/id/index.md
> +{{domxref("NavigationHistoryEntry")}} interface returns the `id` of the history entry. This is a unique, UA-generated value that always represents the history entry, useful to correlate a history ent
Done. I've done the same thing in reverse on the key page too.

2022-11-16 16:24 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index.md
> +  - : Returns the index of the history entry in the history entries list (i.e. returned by {{domxref("Navigation.entries()")}}), or `-1` if the entry does not appear in the list.
changed

2022-11-16 18:18 UTC, wbamberg commented on files/en-us/web/api/navigationhistoryentry/index.md
> +}
Yes, this is clearer (to me anyway). FWIW you don't need this bit:

```js
async function handleNavigate(url) {

  // Navigate to a different view, but the button will always work.
  await navigation.navigate(url).finished;

  // ...
}
```

...because `navigate` will intercept normal links as well, as it does in the demo. You could put the comment `// Navigate to a different view, but the button will always work.` just in the intercept handler:

```suggestion
function initHomeBtn() {
  // Get the key of the first loaded entry
  // so the user can always go back to this view.
  const {key} = navigation.currentEntry;
  backToHomeButton.onclick = () => {
    navigation.traverseTo(key);
  }
}

// Intercept navigate events, such as link clicks, and
// replace them with single-page navigations
navigation.addEventListener("navigate", event => {
  event.intercept({
      async handler() {
        // Navigate to a different view,
        // but the "home" button will always work.
      }
  });
});
```

...just a suggestion though

2022-11-17 01:22 UTC, wbamberg reviewed
OK, there are for `NavigationEvent`. Again apologies for being slow to get through them. I'd hoped to finish today but that isn't looking very likely.

2022-11-17 01:22 UTC, wbamberg commented on files/en-us/web/api/navigateevent/scroll/index.md
> +```js
As for https://pr21960.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/NavigateEvent#handling_scrolling_using_scroll, it would be great to have a sentence or two explaining this.

2022-11-17 01:22 UTC, wbamberg commented on files/en-us/web/api/navigateevent/signal/index.md
> +The general idea here is that the `signal` property can be passed to an associated {{domxref("fetch()")}} operation so that if the navigation is cancelled, it can be safely aborted, avoiding wasting
```suggestion
The general idea here is that the `signal` property can be passed to an associated {{domxref("fetch()")}} operation so that if the navigation is cancelled, the `fetch` operation can be safely aborted, avoiding wasting bandwidth on fetches that are no longer needed.
```

("it" is ambiguous here)

2022-11-17 01:22 UTC, wbamberg commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
Predictably :) I think it would be good to have this list on MDN.

2022-11-17 02:46 UTC, domenic commented on files/en-us/web/api/navigateevent/info/index.md
> +{{domxref("NavigateEvent")}} interface returns the `info` data value passed by the initiating navigation operation (e.g. {{domxref("Navigation.back()")}}, or {{domxref("Navigation.navigate()")}}), or
Sorry, that part of the spec is wrong; it's undefined. I'm working on fixing it as part of https://github.com/whatwg/html/pull/8502

2022-11-17 02:47 UTC, domenic commented on files/en-us/web/api/navigateevent/canintercept/index.md
> +{{domxref("NavigateEvent")}} interface returns `true` if the navigation can be intercepted, or `false` otherwise (e.g. you can't intercept a cross-origin navigation).
The full explanation for this case goes beyond this, and requires reading the whole table at https://github.com/wicg/navigation-api#appendix-types-of-navigations . That's why the non-normative (for web developers) part of the spec uses the vague phrase "generally speaking", because it's too complex to summarize quickly.

2022-11-17 02:48 UTC, domenic commented on files/en-us/web/api/navigateevent/intercept/index.md
> +    // likely still call .preventDefault() to stop it completely).
Often, yes. See the full table at https://github.com/wicg/navigation-api#appendix-types-of-navigations to know what situations `canIntercept` (can call `intercept()`) is true, vs. `cancelable` (can call `preventDefault()`) is true.

2022-11-17 04:30 UTC, wbamberg commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the type of the navigation, which is one of `push`, `reload`, `replace`, or `traverse`.
We don't have a defined style for this AFAIK, but I do like the practice of using quotes for strings.

2022-11-17 04:34 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +1. The current specification doesn't trigger {{domxref("Navigation.navigate_event", "navigate")}} on a page's first load. This might be fine for sites that use Server Side Rendering (SSR)—your server
```suggestion
1. The current specification doesn't trigger a {{domxref("Navigation.navigate_event", "navigate")}} event on a page's first load. This might be fine for sites that use Server Side Rendering (SSR)—your server could return the correct initial state, which is the fastest way to get content to your users. But sites that leverage client-side code to create their pages may need an additional function to initialize the page.
```

(because with "trigger `navigate`" it's not super obvious this is an event (`navigate` is used a lot in this API)).

2022-11-17 04:35 UTC, wbamberg commented on files/en-us/web/api/navigation_api/index.md
> +There are a few perceived limitations with the Navigation API, which may or may not be limiting depending on how your app is set up. Find out about these by reading [Modern client-side routing: the N
Looks great but I added a tiny copy-edit suggestion.

2022-11-17 04:39 UTC, domenic commented on files/en-us/web/api/navigation_api/index.md
> +  - : Event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fires when [any type of navigation](https://github.com/WICG/navigation-api#appendix-types-of-navigations)
Sorry, I just found this comment. As I expressed in https://github.com/mdn/content/pull/21960#discussion_r1024662993, I think keeping the spec as the main source of truth here would be better.

2022-11-17 05:00 UTC, queengooborg commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
While I agree that de-duplicating data is great, especially when it comes to maintenance, I think that Will's suggestion to add the data to MDN is more than reasonable.  Inherently, tracking the list in MDN will help us better track changes to the spec if/when they occur.  I don't expect it to change often enough that keeping MDN and the spec repo in sync should be a significant burden (and if it is, maybe the spec is getting updated too frequently).  Additionally, if the spec's described behavior changes after browsers update to match the new behavior, we need to track this in MDN (BCD specifically) so that we can relay the information to developers, otherwise developers may be surprised when their website isn't working as expected in older/newer browsers (or worse, they don't notice, assuming there's no issue at all).

2022-11-17 05:17 UTC, domenic commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
OK, well, it's up to you. I don't really understand what your criterion is for when you duplicate the spec vs. when you summarize it, but I hope you have a good system in place for monitoring spec changes.

2022-11-17 19:34 UTC, wbamberg commented
@chrisdavidmills , I've been through everything here at least once and commented. I've been back through things you have addressed and they look good. There are still some thing from the last few days' reviews that are outstanding - I will take another look when they're done or if you want to talk about them any more that's fine too of course.

2022-11-17 20:27 UTC, dontcallmedom commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
re monitoring spec changes (in specific lists / specific sections), this might be a useful service to suggest in reffy/webref land - I don't expect webref would extract information of that level of details, but setting up a per-section change notification system sounds like something we could probably set up if we have customers for it.

2022-11-18 04:15 UTC, wbamberg commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
I've raised this question with the MDN maintainers and if the consensus is not to include this I'm happy with that. But I'm not aware of any existing consensus or guideline that this level of spec detail should be off-limits to MDN.

I think @queengooborg makes a good point that if it can affect developers, and it's subject to change, isn't it a good thing for us to talk about it, so they know when it changes.

> I hope you have a good system in place for monitoring spec changes

We could certainly do better here. @dontcallmedom , that sounds like a very good idea. We'd need processes on the MDN side to respond to notifications and the capacity to actually do something about it.

2022-11-18 22:15 UTC, hamishwillee commented on files/en-us/web/api/navigateevent/canintercept/index.md
> +{{domxref("NavigateEvent")}} interface returns `true` if the navigation can be intercepted, or `false` otherwise (e.g. you can't intercept a cross-origin navigation).
FWIW As a reader the normative information is what I want first; a general summary that will apply for most circumstances - because most of the time I'm reading for the gist.

But I would absolutely also want more precision on the most common cases as @wbamberg has done for http, https and file. If it can't be cannonical as a list, I'd note that "there are a number of other cases listed in the specification, covering X, Y, Z".

2022-11-20 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index/index.md
> +let current = navigation.currentEntry;
updated

2022-11-20 07:49 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/key/index.md
> +let current = navigation.currentEntry;
updated

2022-11-20 07:50 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/url/index.md
> +let current = navigation.currentEntry;
updated

2022-11-20 08:01 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/dispose_event/index.md
> +- The 50-page history limit is exceeded. This is not specified anywhere, but it is widely implemented. See the discussion in [How to Manipulate history.length and set it to more than 50](https://stac
I think your concern is valid; I did a search and could find no other mention of this anywhere else. I have deleted the SO reference and made the text a bit vaguer and more non-committal.

2022-11-20 08:03 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/getstate/index.md
> +A value representing the state. This can be any type.
updated!

2022-11-20 08:12 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/getstate/index.md
> +{{domxref("NavigationHistoryEntry")}} interface returns a clone of the available state associated with this history entry.
I've done both; I'll also make this change on `NavigationDestination.getState()`

2022-11-20 08:20 UTC, chrisdavidmills commented on files/en-us/web/api/navigationhistoryentry/index.md
> +}
Good call; I've updated these examples to use your listing suggestion. Thanks Will!

2022-11-20 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/canintercept/index.md
> +{{domxref("NavigateEvent")}} interface returns `true` if the navigation can be intercepted, or `false` otherwise (e.g. you can't intercept a cross-origin navigation).
I've rewritten this to provide some examples, using some of Will's text, but I've also linked out to the spec for full information. This is one of those cases in which I don't think it's worth trying to repeat the full explanation on MDN. I think most web devs won't need it.

2022-11-20 08:39 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/info/index.md
> +{{domxref("NavigateEvent")}} interface returns the `info` data value passed by the initiating navigation operation (e.g. {{domxref("Navigation.back()")}}, or {{domxref("Navigation.navigate()")}}), or
Yeah, I think I read `undefined` in the explainer somewhere. I've updated the syntax section to match, as that said `false` ;-)

2022-11-20 08:40 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +  - : Returns the `info` data value passed by the initiating navigation operation (e.g. {{domxref("Navigation.back()")}}, or {{domxref("Navigation.navigate()")}}), or `undefined` if no `info` data wa
See previous comment.

2022-11-20 08:41 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/formdata/index.md
> +{{domxref("NavigateEvent")}} interface returns the {{domxref("FormData")}} object representing the submitted data in the case of a `POST` form submission, or `null` otherwise.
Thanks; I've updated this.

2022-11-20 08:41 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +The **`NavigateEvent`** interface of the {{domxref("Navigation API", "Navigation API", "", "nocode")}} is the event object for the {{domxref("Navigation/navigate_event", "navigate")}} event, which fi
Perhaps, but I'd like to do this as part of a future PR

2022-11-20 08:43 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +> **Note:** Previous to the Navigation API being available, to do something similar you'd have to listen for all click events on links, run `e.preventDefault()`, perform the appropriate {{domxref("Hi
Ha, clumsy writing. Updated!

2022-11-20 08:54 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/index.md
> +```js
Good call; I've added a paragraph to explain it.

2022-11-20 08:56 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/info/index.md
> +Any data type representing the `info` value, or `false` if none was passed.
`undefined`, but I've updated the description.

2022-11-20 09:01 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/intercept/index.md
> +intercept(options)
Updated

2022-11-20 09:05 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/intercept/index.md
> +    - `handler`
I've put `focusReset` and `scroll` as optional, as that seems to make sense.  If you are going to include an options object, then you really ought to include a `handler`, otherwise it just doesn't do anything. But looking at the spec, it doesn't seem like the call fails if you don't include any options.

2022-11-20 09:08 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/intercept/index.md
> +      - : Defines the navigation's focus behavior. Once the promise returned by your handler function resolves, by default the browser will focus the first element with the {{htmlattrxref("autofocus"
Updated.

2022-11-20 09:09 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/intercept/index.md
> +      - : Defines the navigation's focus behavior. By default the browser will handle scrolling, for example by scrolling to the relevant fragment identifier if the URL contains a fragment, or restor
Updated.

2022-11-20 09:09 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/intercept/index.md
> +`undefined`.
changed

2022-11-20 09:10 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/scroll/index.md
> +```js
added

2022-11-20 09:11 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/signal/index.md
> +The general idea here is that the `signal` property can be passed to an associated {{domxref("fetch()")}} operation so that if the navigation is cancelled, it can be safely aborted, avoiding wasting
Good call; updated.

2022-11-20 09:17 UTC, chrisdavidmills commented on files/en-us/web/api/navigateevent/userinitiated/index.md
> +> **Note:** The table found at [Appendix: types of navigations](https://github.com/WICG/navigation-api#appendix-types-of-navigations) shows which navigation types are user-initiated.
As per other comments; I'm happy to consider this addition at a later date, but I'd rather do it in a future PR, and get this one merged. I'm a bit on the fence about moving it; it is useful info, but it is complex and long-winded, and I'm not convinced that repeating it on MDN is the best use of my time, especially at this fairly nascent stage in the technology's lifespan, where it might possibly get tweaked a bit as more people start using the URL and providing more feedback.

2022-11-20 09:21 UTC, chrisdavidmills commented on files/en-us/web/api/navigation_api/index.md
> +1. The current specification doesn't trigger {{domxref("Navigation.navigate_event", "navigate")}} on a page's first load. This might be fine for sites that use Server Side Rendering (SSR)—your server
Yup, good call. Updated!

2022-11-20 09:31 UTC, chrisdavidmills commented
> @chrisdavidmills , I've been through everything here at least once and commented. I've been back through things you have addressed and they look good. There are still some thing from the last few days' reviews that are outstanding - I will take another look when they're done or if you want to talk about them any more that's fine too of course.

Thanks @wbamberg ; I really appreciate the effort you've made in giving this a thorough review. I've answered all your most recent comments, and also gone back and found a bunch of ones I missed last time round. Let me know if you feel that I've missed anything.

2022-11-20 17:57 UTC, wbamberg approved these changes
👍 thank you for your patience Chris!

2022-11-20 17:57 UTC, merged

2022-11-20 18:29 UTC, chrisdavidmills commented
@wbamberg woo hoo!

2022-11-21 00:06 UTC, domenic commented on files/en-us/web/api/navigateevent/intercept/index.md
> +    - `handler`
Actually, all these properties are optional. Calling `intercept()` with no options is perfectly valid, and is quite useful if you just want to intercept a cross-document navigation and convert it into a same-document one. It'd also be reasonable to do just `intercept({ scroll: "manual" })` or similar.