Rewrite Performance API overview
mdn/content pull request #21984
Opened 2022-11-01 15:11 UTC by Elchi3

### Description

This PR updates https://developer.mozilla.org/en-US/docs/Web/API/Performance_API to give readers a better overview over what are all the Performance APIs. I'm still discussing the content structure with Will, so right now this is a draft for me and Will to look at.

### Motivation

Will motivates me!

### Additional details

No.

### Related issues and pull requests

None right now.

2022-11-02 03:42 UTC, wbamberg requested changes
Thanks Florian! Happy to discuss this.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +It provides high resolution points in time ({{domxref("DOMHighResTimeStamp")}}) and a performance timeline for benchmarking.
```suggestion
```

I don't think it's useful to lead off with DOMHighResTimeStamp, and the first sentence is just fine as it is IMO.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +The various timing APIs (see below) identify the bottlenecks of the web applications. They all appear as an entry ({{domxref("PerformanceEntry")}}) on the performance timeline. Performance observers
I would have a bit of description (it's called "Concepts and usage" in the template: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_landing_page_template#concepts_and_usage and I would be OK to use that) covering things like:

- `PerformanceEntry` represents a single performance measurement. It has a name, a duration, a start time, and a type. The specs define various types of entry, which capture different aspects of web app performance and which all inherit from `PerformanceEntry`. The spec also defines two performance entry types, `PerformanceMark` and `PerformanceMeasure`, for creating custom performance measurements.
- `Performance` enables you to explicitly add record custom performance entries, to clear performance entries, and to retrieve performance entries.
- `PerformanceObserver` enables to to listen for various types of performance entry.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +![UML diagram of Performance APIs](diagram.svg)
I think it would be easier to read this diagram with an arrangement like:

<img width="345" alt="Screen Shot 2022-11-01 at 8 27 12 PM" src="https://user-images.githubusercontent.com/432915/199388749-4353fbf7-b0b5-48a6-9348-958f43c0e778.png">

Also, PerformanceServerTiming does not inherit from PerformanceResourceTiming, it is a property of PerformanceResourceTiming: https://www.w3.org/TR/server-timing/#extension-to-the-performanceresourcetiming-interface.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +## Performance API reference docs
I would call this "Interfaces" per the template, and just list all the interfaces here in alphabetical order, with a 1-sentence description of each.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +### High resolution time
Given that we're treating this as a single API, I don't think this spec-centric presentation is very helpful. It also means `Performance` is broken into pieces across H3 headings. Why would devs care which spec defines which `Performance` methods?

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +- [Using the Resource Timing API](/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API)
This I guess will need revising :).

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +<div class="index">
I don't think this multi-column presentation is very helpful: even if our implementation of it was less broken, I think a single column is way more scannable.

2022-11-02 03:42 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +The various timing APIs (see below) identify the bottlenecks of the web applications. They all appear as an entry ({{domxref("PerformanceEntry")}}) on the performance timeline. Performance observers
I think the inheritance diagram you have is helpful in that context.

2022-11-02 10:49 UTC, Elchi3 commented on files/en-us/web/api/performance_api/index.md
> +- [Using the Resource Timing API](/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API)
I left this for now. This will need updating once we renovated the guide(s).

2022-11-02 18:01 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +Each performance metric is represented by a single {{domxref("PerformanceEntry")}}. It has a `name`, a `duration`, a `startTime`, and a `type`. All performance metrics extend the `PerformanceEntry` i
```suggestion
Each performance metric is represented by a single {{domxref("PerformanceEntry")}}. A performance entry has a `name`, a `duration`, a `startTime`, and a `type`. All performance metrics extend the `PerformanceEntry` interface and qualify it further.
```

2022-11-02 18:09 UTC, wbamberg reviewed
I like it!

2022-11-02 18:09 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +Each performance metric is represented by a single {{domxref("PerformanceEntry")}}. It has a `name`, a `duration`, a `startTime`, and a `type`. All performance metrics extend the `PerformanceEntry` i
```suggestion
Each performance metric is represented by a single {{domxref("PerformanceEntry")}}. A performance entry has a `name`, a `duration`, a `startTime`, and a `type`. All performance metrics extend the `PerformanceEntry` interface and qualify it further.
```

2022-11-02 18:09 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +The main {{domxref("Performance")}} interface is available for each global using {{domxref("performance_property", "self.performance")}} and enables you to add record custom performance entries, to c
```suggestion
The main {{domxref("Performance")}} interface is available for each global using {{domxref("performance_property", "self.performance")}} and enables you to add custom performance entries, to clear performance entries, and to retrieve performance entries.
```

2022-11-02 18:09 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +The {{domxref("PerformanceObserver")}} interface enables to to listen for various types of performance entry as they are recorded.
```suggestion
The {{domxref("PerformanceObserver")}} interface enables you to listen for various types of performance entry as they are recorded.
```

2022-11-02 18:09 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +![UML diagram of Performance APIs](diagram.svg)
`PerformanceServerTiming` is not a type of `PerformanceEntry`: https://www.w3.org/TR/server-timing/#the-performanceservertiming-interface. You could show it as a property of `PerformanceResourceTiming`, but I would just omit it.

2022-11-02 18:09 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +  - : Surfaces server metrics that are sent with the response in the {{HTTPHeader("Server-Timing")}} HTTP header.
This is a weirdly random order. I think I know why you've not gone for strict alpha (wanting to make the core interfaces more obvious) but I think alpha is better even so.

2022-11-03 10:10 UTC, Elchi3 commented on files/en-us/web/api/performance_api/index.md
> +  - : Surfaces server metrics that are sent with the response in the {{HTTPHeader("Server-Timing")}} HTTP header.
Yes, sorry, I was experimenting, but you are probably right, let's make it alphabetical.

2022-11-03 10:18 UTC, Elchi3 commented on files/en-us/web/api/performance_api/index.md
> +![UML diagram of Performance APIs](diagram.svg)
Given I got this wrong twice, I omitted it now :)

2022-11-03 17:34 UTC, wbamberg commented on files/en-us/web/api/performance_api/index.md
> +  - : Surfaces server metrics that are sent with the response in the {{HTTPHeader("Server-Timing")}} HTTP header.
I have a whole thing about why alphabetical order is almost always better unless page titles are unpredictable (e.g. with guides).

2022-11-03 17:35 UTC, wbamberg approved these changes
👍 very nice. I think we might want to not have whole pages for some of these interfaces (like `EventCounts`) but we can worry about that later.

2022-11-03 17:35 UTC, merged