Make wording more accurate and concise
mdn/content pull request #21998
Opened 2022-11-02 05:07 UTC by klu22

Made some minor stylistic changes as well.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-11-02 05:16 UTC, Josh-Cena requested changes

2022-11-02 05:16 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/await/index.md
> +Again, `await` is only valid inside `async` functions and at the top levels of modules. Since `async` functions are themselves asynchronous and return promises, an `await` expression inside an `async
The original sentence is more coherent. Modules are also async because they are always asynchronously linked and evaluated.

2022-11-02 05:16 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/await/index.md
> +You can use the `await` keyword on its own (outside of an async function) in the top level of a [module](/en-US/docs/Web/JavaScript/Guide/Modules). This means that modules with child modules that use
The non-blocking part is important. The module graph does not block on one await.

2022-11-03 19:35 UTC, klu22 commented on files/en-us/web/javascript/reference/operators/await/index.md
> +Again, `await` is only valid inside `async` functions and at the top levels of modules. Since `async` functions are themselves asynchronous and return promises, an `await` expression inside an `async
Agreed. When I made that edit, it slipped my mind that modules themselves are async. Reverted to the previous version.

2022-11-03 19:35 UTC, klu22 commented on files/en-us/web/javascript/reference/operators/await/index.md
> +You can use the `await` keyword on its own (outside of an async function) in the top level of a [module](/en-US/docs/Web/JavaScript/Guide/Modules). This means that modules with child modules that use
Agreed, fixed

2022-11-05 00:58 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/operators/await/index.md
> +You can use the `await` keyword on its own (outside of an async function) in the top level of a [module](/en-US/docs/Web/JavaScript/Guide/Modules). This means that modules with child modules that use
```suggestion
You can use the `await` keyword on its own (outside of an async function) at the top level of a [module](/en-US/docs/Web/JavaScript/Guide/Modules). This means that modules with child modules that use `await` will wait for the child modules to execute before they themselves run, all while not blocking other child modules from loading.
```

2022-11-05 00:58 UTC, Josh-Cena approved these changes
This does sound better. Thanks!

2022-11-05 01:01 UTC, merged