Add special shortcut _execute_action
mdn/content pull request #22018
Opened 2022-11-02 23:05 UTC by rebloor

### Description

Adds details about the special shortcut `_execute_action` which became available to MV3 Extensions with the introduction of the action API and manifest key.

### Related issues and pull requests

Addresses the outstanding documentation needs of [Bug 1706398](https://bugzilla.mozilla.org/show_bug.cgi?id=1706398) Implement "action" API / manifest key.

2022-11-02 23:19 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    - `"_execute_action"`: simulate a click on the extension's action, opening its popup if it has one
@Rob--W This file appears to be orphaned. menu.create includes the information directly and menu.update makes reference to menu.create. Should I delete this page (with an appropriate redirect)?

2022-11-02 23:20 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/menus/create/index.md
@Rob--W was your feedback to remove the list from here and simply rely on a link to the special shortcut documentation?

2022-11-03 00:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/create/index.md
>          Clicking the item will still trigger the {{WebExtAPIRef("menus.onClicked")}} event, but there's no guarantee of the ordering here: the command may be executed before `onClicked` fires.
This documentation is incorrect. When the command is supported, the onClicked event is not fired. When it's not recognized, the event is fired, which the extension can use to implement a fallback if they like.

This behavior changed in Fx 91 in the bug associated with this PR.

This review comment applies to menus.create and update.

2022-11-03 00:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    - `"_execute_action"`: simulate a click on the extension's action, opening its popup if it has one
Yes.

2022-11-03 00:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/commands/index.md
> +    <th>Manifiest V3</th>
```suggestion
    <th>Manifest V3</th>
```
Typo

2022-11-03 00:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/popups/index.md
> +You can define a keyboard shortcut that opens the popup using the `"_execute_browser_action"` and `"_execute_page_action"` shortcuts in Manifest V2 and `"_execute_action"`and, where supported, `"_exe
```suggestion
You can define a keyboard shortcut that opens the popup using the `"_execute_browser_action"` and `"_execute_page_action"` shortcuts in Manifest V2 and `"_execute_action"`and, where supported, `"_execute_page_action"` shortcuts in Manifest V3. See the documentation for the special shortcuts in manifest.json key [`commands`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#special_shortcuts).
```

2022-11-03 00:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/create/index.md
The main point was to link a central place with detailed documentation, which you have done. Deletion of the list is not strictly necessary.

One change that may be considered is the addition of "(MV2)" to `_execute_browser_action` and "(MV3)" to `_execute_action` (across all 3 pages where this concise list appears).

2022-11-03 16:14 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/commands/index.md
> +    <th>Manifiest V3</th>
Fixed

2022-11-03 16:14 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/user_interface/popups/index.md
> +You can define a keyboard shortcut that opens the popup using the `"_execute_browser_action"` and `"_execute_page_action"` shortcuts in Manifest V2 and `"_execute_action"`and, where supported, `"_exe
Fixed

2022-11-03 16:33 UTC, Rob--W requested changes

2022-11-03 16:33 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    When specified, clicking the item does not trigger the {{WebExtAPIRef("menus.onClicked")}} event; instead, the pop-up is opened. When not specified, clicking the item triggers {{WebExtAPIRef("men
```suggestion
    When the given command is recognized by the browser, clicking the item does not trigger the {{WebExtAPIRef("menus.onClicked")}} event; instead, the associated action is triggered, such as opening the pop-up. When not specified or not recognized, clicking the item triggers {{WebExtAPIRef("menus.onClicked")}} and can be used to implement fallback behavior.
```

Suggested change of message; rephrase as needed.

The issue with the previous wording was that it seemed to suggest that if someone were to specify `command: "bogus"`, that the `onClicked` listener would not be triggered. That's inaccurate. The listener is only not triggered if the command is recognized.

2022-11-03 16:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    - `"_execute_action"`: simulate a click on the extension's action, opening its popup if it has one
Did you install the dependencies? The error seems to suggest that `yari-tool` is not available.

According to https://github.com/mdn/content/pull/16945, the binaries are provided by `@mdn/yari`.

2022-11-03 20:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    - `"_execute_action"`: simulate a click on the extension's action, opening its popup if it has one
I assumed so (as I've been running `yarn start` for a while). However, reinstalling has resolved the issue. Thanks.

2022-11-03 20:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/menus/createproperties/index.md
> +    When specified, clicking the item does not trigger the {{WebExtAPIRef("menus.onClicked")}} event; instead, the pop-up is opened. When not specified, clicking the item triggers {{WebExtAPIRef("men
Please check my update

2022-11-03 21:34 UTC, Rob--W approved these changes

2022-11-03 21:46 UTC, merged