16 interactive examples
mdn/content pull request #22132
Opened 2022-11-07 16:37 UTC by NiedziolkaMichal

Adds newly created interactive examples.
In each case I have added `EmbedInteractiveExample` just under first line of content, so feel free to move it if you like.

2022-11-07 16:54 UTC, NiedziolkaMichal commented
I removed `min`, `max` & `step` examples, which rely on upcoming BOB update.

2022-11-07 22:18 UTC, dipikabh requested changes
Thanks for this work, @NiedziolkaMichal! I have suggested different placements for the interactive examples. A few of them are also 404-ing.

2022-11-07 22:18 UTC, dipikabh commented on files/en-us/web/html/attributes/accept/index.md
>  The accept property is an attribute of the {{HTMLElement("input/file", "file")}} {{htmlelement("input")}} type. It was supported on the {{htmlelement("form")}} element, but was removed in favor of {{
```suggestion
{{EmbedInteractiveExample("pages/tabbed/attribute-accept.html", "tabbed-shorter")}}

## Overview

The accept property is an attribute of the {{HTMLElement("input/file", "file")}} {{htmlelement("input")}} type. It was supported on the {{htmlelement("form")}} element, but was removed in favor of {{HTMLElement("input/file", "file")}}.
```
- This is an alternative to separate the prose section from the "Try it" section - to put the prose under the heading "Overview".
- The preferable format would be to move the interactive example right before the `## Examples` section.

2022-11-07 22:18 UTC, dipikabh commented on files/en-us/web/html/attributes/autocomplete/index.md
> +
- there is a 404 error
- this can be moved to just before the `## Values` section.

2022-11-07 22:18 UTC, dipikabh commented on files/en-us/web/html/attributes/capture/index.md
>  Values include `user` and `environment`. The capture attribute is supported on the {{HTMLElement("input/file", "file")}} input type.
```suggestion
## Values

Values include `user` and `environment`. The capture attribute is supported on the {{HTMLElement("input/file", "file")}} input type.
```

The interactive example should be moved to right before the `## Examples` section.

2022-11-07 22:18 UTC, dipikabh commented on files/en-us/web/html/attributes/disabled/index.md
>  If the `disabled` attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won'
```suggestion
{{EmbedInteractiveExample("pages/tabbed/attribute-disabled.html", "tabbed-standard")}}

## Overview

If the `disabled` attribute is specified on a form control, the element and its form control descendants do not participate in constraint validation. Often browsers grey out such controls and it won't receive any browsing events, like mouse clicks or focus-related ones.
```

2022-11-07 22:38 UTC, NiedziolkaMichal commented
Thanks a lot for taking your time to show me where exactly should every example be located. When you have a moment, please take a look if now everything is in the right place.

@schalkneethling Could you update interactive examples infrastructure, so recent commits can be added to content repo?

2022-11-08 15:25 UTC, dipikabh commented
> Thanks a lot for taking your time to show me where exactly should every example be located. When you have a moment, please take a look if now everything is in the right place.

Thanks, Michal! The fixes regarding the placements look good. The 404 errors for some of the interactive examples still exist. Are these waiting to be merged in the interactive-examples repository? I did not find open PRs for them there.

2022-11-08 15:31 UTC, NiedziolkaMichal commented
They are already merged, for example this is [image-orientation](https://github.com/mdn/interactive-examples/pull/2317).
The problem is, automatic deployment of new interactive examples is [broken](https://github.com/mdn/bob/issues/913). [https://interactive-examples.mdn.mozilla.net/](https://interactive-examples.mdn.mozilla.net/) needs to be manually synchronized with repository and I think only Schalk is able to do it.

2022-11-18 16:15 UTC, NiedziolkaMichal commented
@dipikabh All examples are now deployed & visible. Could you recheck please?

2022-11-22 14:10 UTC, dipikabh approved these changes
Thank you @NiedziolkaMichal!

2022-11-22 14:11 UTC, merged