adding content for ContentVisibilityAutoStateChangedEvent
mdn/content pull request #22154
Opened 2022-11-08 10:20 UTC by chrisdavidmills

### Description

This PR adds content for the `ContentVisibilityAutoStateChangedEvent` interface and its related event.

See my research sheet for more details: https://docs.google.com/document/d/1UobZG27MYj2jsV5m4mEAYyHbs59EJ2_3RDHuwYZLGEY/edit#

### Motivation

Readers will want to know about this new API

### Additional details

### Related issues and pull requests

2022-11-08 19:17 UTC, vmpstr reviewed
This looks good from the technical perspective

2022-11-08 19:17 UTC, vmpstr commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +  - Visibility
Content Visibility? Not sure how tags work, but this is related to CSS content-visibility property, not the CSS visibility property

2022-11-09 07:24 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +  - Visibility
Yeah, good point; I'll update the tags.

2022-11-09 07:26 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +This occurs when:
OK; updated

2022-11-09 08:11 UTC, sideshowbarker approved these changes
Looks great to me, with some minor suggestions to consider (all just punctuation changes/additions)

2022-11-09 08:11 UTC, sideshowbarker commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +The **`contentvisibilityautostatechanged`** global event fires on any element with {{cssxref("content-visibility", "content-visibility: auto")}} set on it when its rendering requirements change, i.e.
```suggestion
The **`contentvisibilityautostatechanged`** global event fires on any element with {{cssxref("content-visibility", "content-visibility: auto")}} set on it when its rendering requirements change; i.e. its content starts or stops [skipping its contents](https://www.w3.org/TR/css-contain-2/#skips-its-contents).
```

2022-11-09 08:49 UTC, teoli2003 requested changes

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +}
`init` is not called
```suggestion
canvasElem.addEventListener('contentvisibilityautostatechanged', stateChanged);
canvasElem.style.contentVisibility = "auto";
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/contentvisibilityautostatechangedevent/index.md
> +  - Web
```suggestion
tags:
  - Constructor
  - Experimental
  - Reference
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/contentvisibilityautostatechangedevent/index.md
> +new ContentVisibilityAutoStateChangedEvent(type, init)
We avoid `init`, used in the spec and inherited from the initialization methods. We use `options` instead:
```suggestion
new ContentVisibilityAutoStateChangedEvent(type, options)
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/contentvisibilityautostatechangedevent/index.md
> +- `init` {{optional_inline}}
```suggestion
- `options` {{optional_inline}}
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/contentvisibilityautostatechangedevent/index.md
> +  - : An init object that contains the following properties:
```suggestion
  - : An object that contains the following properties:
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +function stopCanvasUpdates(canvas) { ... }
We need to comment the ellipses: this makes the code more correct (and will work well when we will start using ESLint).

```suggestion
// Call this when the canvas updates need to start.
function startCanvasUpdates(canvas) {
  // … 
}

// Call this when the canvas updates need to stop.
function stopCanvasUpdates(canvas) {
  // …
}
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/contentvisibilityautostatechangedevent/index.md
> +  ...
```suggestion
  // …
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +  - Web
```suggestion
  - Experimental
  - Interface
  - Reference
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +The **`ContentVisibilityAutoStateChangedEvent`** interface of the [CSS Containment Module Level 2](https://www.w3.org/TR/css-contain-2/#content-visibility-auto-state-changed) is the event object for
Rather than linking to the spec, we should link to the relevant overview page.

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +- The element appears in or disappears from, the viewport, or a user-agent defined margin around the viewport (the spec recommends 50% of the viewport dimensions, to give the app time to prepare for
```suggestion
- The element appears in or disappears from the viewport or a user-agent-defined margin around the viewport (50% of the viewport dimensions to give the app time to prepare for when the element visibility changes).
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +- {{domxref("ContentVisibilityAutoStateChangedEvent.skipped", "ContentVisibilityAutoStateChangedEvent")}} {{ReadOnlyInline}}
```suggestion
- {{domxref("ContentVisibilityAutoStateChangedEvent.skipped", "skipped")}} {{ReadOnlyInline}}
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +}
```suggestion
canvasElem.addEventListener('contentvisibilityautostatechanged', stateChanged);
canvasElem.style.contentVisibility = "auto";
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +function stopCanvasUpdates(canvas) { ... }
```suggestion
// Call this when the canvas updates need to start.
function startCanvasUpdates(canvas) {
  // …
}

// Call this when the canvas updates need to stop.
function stopCanvasUpdates(canvas) {
  // …
}
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/skipped/index.md
> +A boolean—returns `true` if the user agent is skipping the element's rendering, or `false` otherwise.
```suggestion
A boolean. Returns `true` if the user agent is skipping the element's rendering or `false` otherwise.
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/skipped/index.md
> +}
```suggestion
canvasElem.addEventListener('contentvisibilityautostatechanged', stateChanged);
canvasElem.style.contentVisibility = "auto";
```

2022-11-09 08:49 UTC, teoli2003 commented on files/en-us/web/api/contentvisibilityautostatechangedevent/skipped/index.md
> +```
```suggestion
// Call this when the canvas updates need to start.
function startCanvasUpdates(canvas) {
  // …
}

// Call this when the canvas updates need to stop.
function stopCanvasUpdates(canvas) {
  // …
}
```
```

2022-11-09 08:49 UTC, teoli2003 commented on files/jsondata/GroupData.json
> +    },
I would rather create a CSS Containment entry, with `ContentVisiblityAutoStateChangedEvent`as interface, `Element: contentvisibilityautostatechanged` under events and a link to the [overview](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Containment) page.

2022-11-09 10:10 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +The **`contentvisibilityautostatechanged`** global event fires on any element with {{cssxref("content-visibility", "content-visibility: auto")}} set on it when its rendering requirements change, i.e.
Good call; this will be done in the next commit

2022-11-09 10:10 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +title: contentvisibilityautostatechanged event
Thanks for helping me figure out that conundrum. I have moved it in the next commit

2022-11-09 10:16 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +- The element appears in or disappears from, the viewport, or a user-agent defined margin around the viewport (the spec recommends 50% of the viewport dimensions, to give the app time to prepare for
change made; note that I've moved these definitions to the CSS containment page, as well as adding a section on skip contents

2022-11-09 10:17 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechanged_event/index.md
> +- The element or its contents are selected or stop being selected, for example manually by dragging over the text with mouse cursor, or by some other highlight operation as described in [Selecting hi
removed

2022-11-09 10:18 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +The **`ContentVisibilityAutoStateChangedEvent`** interface of the [CSS Containment Module Level 2](https://www.w3.org/TR/css-contain-2/#content-visibility-auto-state-changed) is the event object for
done

2022-11-09 10:18 UTC, chrisdavidmills commented on files/en-us/web/api/contentvisibilityautostatechangedevent/index.md
> +- The element appears in or disappears from, the viewport, or a user-agent defined margin around the viewport (the spec recommends 50% of the viewport dimensions, to give the app time to prepare for
removed

2022-11-09 10:40 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
> +    },
"CSS Containment" makes more sense, so I've updated it to that. I'm not sure how I'd link to the overview page, given that it's in the CSS tree, not the API tree. If I just put in "CSS Containment", it doesn't work. How can I do that?

2022-11-09 10:42 UTC, chrisdavidmills commented
Thanks for the great comments, @teoli2003 ! I think I've answered them all; not much outstanding now.

2022-12-05 08:15 UTC, teoli2003 approved these changes
👍

2022-12-05 08:17 UTC, teoli2003 commented
(I resolved the conflict. If I made a mistake, feel free to make a follow-up PR)

2022-12-05 08:19 UTC, merged