20987 initial CSS container queries updates
mdn/content pull request #22186
Opened 2022-11-09 12:08 UTC by bsmth

This PR is a first pass for improving the documentation for CSS container queries.
I expect there to be some further follow-ups to add more details and (live/interactive) examples where necessary or other pages that I've missed here.

### Highlights

__Updates:__

- `css_container_queries` most of the updates occur in this doc including
  - summaries of the properties with examples of their usage
  - new diagrams
  - links to new properties & related docs
- `length`: added information to this document about "container query length units" which allow you to specify a length relative to the dimensions of a query container.
- media queries page: added references to container queries with a new diagram explaining media queries

__Additions:__

- `@container` at-rule
- `container-name` property
- `container-type` property
- `container` shorthand property (simplifies container name and type to one declaration)

2022-11-10 00:25 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +    <img src="image.png" alt="An awesome picture of a cat" />
```suggestion
    <img src="image.png" alt="An awesome cat" />
```

2022-11-10 00:26 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +    <img src="image.png" alt="An awesome picture of a cat" />
just trying to teach better alt text writing ;)

2022-11-10 00:29 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +    <img src="image.png" alt="An awesome picture of a cat" />
```suggestion
    <img src="image.png" alt="A mostly white cat with a black heart on the forehead." />
```

2022-11-10 04:50 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +An optional `<container-name>` can be provided which filters the set of query containers considered to just those with a matching query container name.
```suggestion
An optional case-sensitive `<container-name>` can be provided which filters the set of query containers considered to just those with a matching query container name.
```

2022-11-10 05:21 UTC, estelle requested changes
Reviewed the at-rule. Still working on it.

2022-11-10 05:21 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +### Descriptors
The syntax goes beyond this. This page is missing stringing together conditions, keywords of AND, OR, NOT, and `style()` conditions

2022-11-10 05:21 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +- `width`
missing the `height` feature.

2022-11-10 05:21 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +@container sidebar (min-width: 400px) {
let's make this more complex and include `style()`

2022-11-10 05:21 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +  - : The orientation of the container, either `landscape` or `portrait`.
if it's an exact square, which does it match?

2022-11-10 05:21 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +  - : The block size of the container expressed as a `<length>` value.
We should link to logical dimensions, but https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties is not a good page. Maybe https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#block_and_inline_dimensions?

2022-11-10 05:59 UTC, estelle reviewed
Review for `container-name`: (still working on this)

I don't yet fully understand containers, so will have to do a thorough re-pass once all these edits are made, and once i have read all your work, grok it, and can really catch omissions, nuances, and mistakes. In the meantime:

* the the previous comment for the list of features that need to be addressed in explaining how to write a valid name.
* This page is missing the possible values of `<custom-ident>` (described in the previous comment) and `none`.

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +The **container-name** [CSS](/en-US/docs/Web/CSS) property is used to give a name to a [containment context](/en-US/docs/Web/CSS/CSS_Container_Queries#naming_containment_contexts) used in a [containe
does it give the name or provide the name?

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +The **container-name** [CSS](/en-US/docs/Web/CSS) property is used to give a name to a [containment context](/en-US/docs/Web/CSS/CSS_Container_Queries#naming_containment_contexts) used in a [containe
it's one OR MORE names.

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +page-type: guide
```suggestion
page-type: css-property
```

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +  - Property
are we still adding:

```css
- recipe:css-property
```

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +title: Container name
```suggestion
title: container-name
```

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +  - container
```suggestion
  - container queries
```

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +The **container-name** [CSS](/en-US/docs/Web/CSS) property is used to give a name to a [containment context](/en-US/docs/Web/CSS/CSS_Container_Queries#naming_containment_contexts) used in a [containe
`The **container-name** [CSS](/en-US/docs/Web/CSS) property specifies a list of query container names that are used by the [@container](/en-US/docs/Web/CSS/@container) at-rule....`

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +The most common way that container queries are applied to elements is to use the nearest containment context as the query container.
huh?

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +When a containment context is given a name, it can be specifically referenced using the {{Cssxref("@container")}} at-rule.
`When containment contexts are given a name, they can be referenced ...` not editing the second half of the sentence, but let's pluralize the the first half since i think people wont realize that more than one element can have the same name and the at-rule can be applied to many elements.

2022-11-10 05:59 UTC, estelle commented on files/en-us/web/css/container-name/index.md
> +- CSS {{Cssxref("contain")}} property
```suggestion
- CSS {{Cssxref("contain")}} shorthand property
```

2022-11-10 06:14 UTC, estelle reviewed
Review for container-type property: 
I don't understand what the `container-type` property does yet; there may be something I am not grokking yet, but reading this page didn't answer my questions. I need to re-review later, after edits are done to other pages so I have better content. I do think the example needs to be overhauled.

2022-11-10 06:14 UTC, estelle commented on files/en-us/web/css/container-type/index.md
> +title: Container type
```suggestion
title: container-type
```

2022-11-10 06:14 UTC, estelle commented on files/en-us/web/css/container-type/index.md
> +  - : Establishes a query container for container size queries on both the inline and block axis.
```suggestion
  - : Establishes a query container for container size queries on both the inline and block axis in both the [inline and block](/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts#block_and_inline_dimensions) dimensions.
```

2022-11-10 06:14 UTC, estelle commented on files/en-us/web/css/container-type/index.md
> +> **Note:** to understand what happens when you apply layout, style, and size containment to a box, see the documentation for {{cssxref("contain")}}.
```suggestion
> **Note:** to understand what happens when you apply layout, style, and size containment to a box, see the {{cssxref("contain")}} property.
```

2022-11-10 06:14 UTC, estelle commented on files/en-us/web/css/container-type/index.md
> +You can then target that container by adding the name to the container query:
This example teaches me nothing. Also, I don't think this sentence applies.

2022-11-10 06:14 UTC, estelle commented on files/en-us/web/css/container-type/index.md
> +- CSS {{Cssxref("contain")}} property
```suggestion
- CSS {{Cssxref("contain")}} shorthand property
```

2022-11-10 06:28 UTC, estelle requested changes
done for tonight.

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +title: Container shorthand
```suggestion
title: container
```

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +page-type: css-property
```suggestion
page-type: css-shorthand-property
```

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +  - Property
Not sure if we're still using this:

```
  - recipe:css-shorthand-property
```

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +The **container** [CSS](/en-US/docs/Web/CSS) property is shorthand usage for giving a name to a [containment context](/en-US/docs/Web/CSS/CSS_Container_Queries#naming_containment_contexts) used in a
```suggestion
The **container** [shorthand](/en-US/docs/Web/CSS/Shorthand_properties) [CSS](/en-US/docs/Web/CSS) property establishes the element as a query container and specifies the name or name for the [containment context](/en-US/docs/Web/CSS/CSS_Container_Queries#naming_containment_contexts) used in a [container query](/en-US/docs/Web/CSS/CSS_Container_Queries).
```

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +container: <container-name> <container-type>;
```suggestion
container: <container-name> / <container-type>;
```

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +container: <container-name> <container-type>;
This syntax looks like syntax. The previous properties don't have this.

2022-11-10 06:28 UTC, estelle commented on files/en-us/web/css/container/index.md
> +  container: sidebar inline-size;
```suggestion
  container: sidebar / inline-size;
```

2022-11-10 13:05 UTC, bsmth commented
Thanks for the review @estelle, going to take a look through the suggestions shortly 👀

2022-11-11 13:59 UTC, bsmth commented on files/en-us/web/css/@container/index.md
> +### Descriptors
> The word `descriptor` is something different 

The spec [describes them as descriptors](https://www.w3.org/TR/css-contain-3/#container-descriptor-table) but I agree the syntax is not the same

```css
/* descriptor: font-family */
@font-face {
  font-family: "Trickster";
}

/* descriptor: width */
@container (width > 400px) {
  /* styles */
}
```

2022-11-11 14:02 UTC, bsmth commented
Tracking review suggestions:

## `@container`

- [ ] The "descriptors" are not descriptor. They are query features.
- [ ] We're missing the `height` feature.
- [ ] People don't fully understand inline and block direction, so that needs to be linked (not a give).
- [ ] The container condition is not limited to feature query; only single feature query example and syntax is shown
- [ ] The `style()` option of the container query is not discussed
- [ ] Query modifiers are missing
- [ ] stringing multiple conditions with modifiers is missing
- [ ] No information is provided on the container name syntax 
     * a custom ident is case sensitive
     * can not be a keyword that may conflict or the word `default`
     * can start with --, which is a different kind of ident, but i forget the name 
     * is not quoted

2022-11-14 12:55 UTC, bsmth commented on files/en-us/web/css/container-name/index.md
> +  - Property
Good question, this might be a good follow-up

2022-11-14 15:46 UTC, bsmth commented on files/en-us/web/css/container/index.md
> +  - Property
noted this one [as above](https://github.com/mdn/content/pull/22186/files#r1018673764)

2022-11-14 16:36 UTC, estelle approved these changes

2022-11-14 16:36 UTC, merged

2022-11-14 16:40 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +![A webpage with a card component demonstrating the difference between media and conrainer queries.](container-query-diagram.png)
what are those differences? The person reading this alt can't see them.

2022-11-14 16:41 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +To use container queries, you need to declare a **containment context** on an element so that the browser knows we might want to query the dimensions of this container later.
you or we, not both.

2022-11-14 16:43 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +    <img src="image.png" alt="An awesome picture of a cat" />
better alt please.

2022-11-14 18:09 UTC, bsmth commented
Thanks @estelle 

__Note:__
This one was merged early, there are unaddressed review comments that I'll carry over to a new PR.

2022-11-15 10:08 UTC, bsmth commented on files/en-us/web/css/container-name/index.md
> +  - Property
According to @hamishwillee 

>these do nothing - I have certainly being removing those in the cases I have seen them.

2022-11-18 01:06 UTC, hamishwillee commented on files/en-us/web/css/container-name/index.md
> +  - Property
That is correct. The tags which do something are property, method, deprecated, experimental, non-standard. Before my time, but in the far past macros existed to autogenerate lists - but these have been gone for a very long time, and the others aren't used. 

I want all of tje relevent info to go into unique page metadata and we delete the remaining tags.