Performance API: toJSON methods
mdn/content pull request #22223
Opened 2022-11-10 18:18 UTC by Elchi3

### Description

This PR improves (or creates) docs for the 10 `toJSON` method pages in the Performance API docs. I tried to make them consistent.

### Motivation

https://github.com/openwebdocs/project/issues/62

### Additional details

It is not easy to be consistent.

### Related issues and pull requests

I will create a BCD PR to add mdn_urls for the two new pages.

2022-11-10 18:42 UTC, Josh-Cena commented
Drive by: I'd also try to mention that `JSON.stringify` automatically calls `toJSON`?

Also not sure if "a JSON object" is a well-understood term, since JSON for me means a serialization format. Maybe "JSON-serializable object"?

2022-11-10 18:57 UTC, wbamberg commented
> Drive by: I'd also try to mention that `JSON.stringify` automatically calls `toJSON`, so you often don't need to call this explicitly (like how we frame it on `toString` pages)

Yes, I wondered before if the examples could use `console.log(JSON.stringify(thing))` instead of (or as well as) `console.log(thing.toJSON())` to show this.

> 
> Also not sure if "a JSON object" is a well-understood term, since JSON for me means a serialization format. Maybe "JSON-serializable object"?

2022-11-10 19:27 UTC, Elchi3 commented
Maybe below all of these  blocks: 

>  This would log a JSON object like so:
>  ```json
>  {
>  "name": "cache",
>  "duration": 0,
>  "description": "hit-front"
> }
> ```

Have a sentence like:

> To get a JSON string, you can use [`JSON.stringify(entry)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) directly; it will call `toJSON()` automatically.

2022-11-10 21:33 UTC, wbamberg commented
> Maybe below all of these blocks:
> 
> > This would log a JSON object like so:
> > ```json
> > {
> > "name": "cache",
> > "duration": 0,
> > "description": "hit-front"
> > }
> > ```
> 
> Have a sentence like:
> 
> > To get a JSON string, you can use [`JSON.stringify(entry)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) directly; it will call `toJSON()` automatically.

I think that would be great :).

2022-11-10 22:02 UTC, wbamberg requested changes
Thank you @Elchi3 !

2022-11-11 17:29 UTC, wbamberg approved these changes
👍

2022-11-11 17:29 UTC, merged