Document changes to action.openPopup API
mdn/content pull request #22267
Opened 2022-11-13 14:07 UTC by oliverdunk

### Description

Updates the documentation for the `action.openPopup` API following changes across browsers, including the Firefox changes in https://phabricator.services.mozilla.com/D139796.

I've removed the note about user gesture requirements from the main body since this does not apply in any other browser (see https://docs.google.com/document/d/1xzuw1dMuf5Lub8UPME2zjxyp3nCKXk-3jtSY2kdI-FQ/edit?usp=sharing for Chrome) or Safari. Instead I've added it as a compatibility note in https://github.com/mdn/browser-compat-data/pull/18202.

All browsers now also support a `windowId` parameter so I've added documentation for that.

### Motivation

I've been working on this API recently and want to make sure the documentation is an up to date point of reference.

### Additional details

- Announcement in WebKit release notes: https://webkit.org/blog/12522/release-notes-for-safari-technology-preview-142/
- Chrome proposal: https://docs.google.com/document/d/1xzuw1dMuf5Lub8UPME2zjxyp3nCKXk-3jtSY2kdI-FQ/edit?usp=sharing
- Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1755763

### Related issues and pull requests

Depends on: https://github.com/mdn/browser-compat-data/pull/18202

2022-11-13 21:53 UTC, Rob--W requested changes
We found quite some interesting behaviors and edge cases during the development of this feature. Did you already check and rule out their relevance for the documentation?

2022-11-13 21:53 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/openpopup/index.md
> +  options // object
```suggestion
  options // optional object
```

2022-11-13 21:53 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/openpopup/index.md
> -You can only call this function from inside the handler for a [user action](/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).
Don't remove it entirely, but reword it so that it is clear that sometimes user interaction is required. You can mention specific browsers and versions, and point to the BCD (browser compatibility table) if desired.

2022-11-13 21:53 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/openpopup/index.md
> +- `details`
```suggestion
- `details` {{optional_inline}}
```

2022-11-15 17:28 UTC, rebloor approved these changes
Changes plus suggested changes, good with me. Thanks @oliverdunk

2023-05-24 10:46 UTC, oliverdunk commented
Sorry for the delay on this. I haven't had a chance to look over the feedback yet but will try to do it soon.

2023-08-28 21:33 UTC, oliverdunk commented
> @oliverdunk let me know if you don't have time to complete this, I'd be happy to finish it up

Thanks for the ping! I've tried to address the feedback - feel free to also make any changes on the branch that make sense.

> We found quite some interesting behaviors and edge cases during the development of this feature. Did you already check and rule out their relevance for the documentation?

We could probably add a lot more of the different inconsistencies as mentioned in https://github.com/w3c/webextensions/issues/160#issuecomment-1127042759. I've left that for now since it seems like a rabbit hole to try and document (and hopefully we'll fix some of them) but happy for anyone else to add on :)

2023-08-29 17:53 UTC, rebloor commented
@Rob--W I can't merge this while it still has your request for changes on it. The specific items you mentioned have been addressed. As this is now nine months old, perhaps we can address any need for documentation of the nuances separately?

2023-08-29 20:50 UTC, Rob--W approved these changes
Fine by me!

2023-08-29 21:38 UTC, merged