20987 container queries part2
mdn/content pull request #22292
Opened 2022-11-14 19:10 UTC by bsmth

This is a follow-up PR that addresses some leftover review comments from https://github.com/mdn/content/pull/22186

* 'you' v 'we' consistency
* improve alt texts for images
* correction on available containment types

2022-11-15 02:24 UTC, estelle requested changes
mostly minor suggestions, with one "the end of this sentence is missing". Looks good.

2022-11-15 02:24 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +Specifically, this query will apply a larger font size for the card title if the container is wider than `700px`:
Tip for the future: generally for responsive stuff we want to show examples with relative units (like `vw` or `rem`) rather than absolute units (like `px`).

2022-11-15 02:24 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +It's possible to give a containment context a name using the {{Cssxref("container-name")}} property to target a specific container.
```suggestion
It's possible to give a containment context a name using the {{Cssxref("container-name")}} property. Once named, the name can be used in a `@container` query so as to target a specific container.
```
I think that is what you meant.

2022-11-15 08:32 UTC, bsmth commented on files/en-us/web/css/container-name/index.md
> +This is useful if you want to separate
good catch, tnx

2022-11-15 08:32 UTC, bsmth commented on files/en-us/web/css/css_container_queries/index.md
> +Specifically, this query will apply a larger font size for the card title if the container is wider than `700px`:
very good 👍🏻

2022-11-15 10:41 UTC, bsmth commented on files/en-us/web/css/container-name/index.md
> +This is useful if you want to separate
```suggestion
This is useful if you want to target the same container with multiple container queries where either condition could be true:
```

2022-11-17 09:43 UTC, bsmth commented
Hi @estelle, I've addressed the comments, thanks. Do you want to have another quick look?

2022-11-18 13:29 UTC, estelle commented on files/en-us/web/css/css_container_queries/index.md
> +![A media query based on the viewport's width and a container query based on the width of a container context.](container-query-diagram.png)
```suggestion
![A media query based on the viewport's width, which is the full width of the browser, and a container query based on the width of a container context, which is the width of the container element.](container-query-diagram.png)
```

2022-11-18 13:31 UTC, estelle approved these changes

2022-11-18 13:49 UTC, bsmth commented on files/en-us/web/css/css_container_queries/index.md
> +![A media query based on the viewport's width and a container query based on the width of a container context.](container-query-diagram.png)
Thanks!

2022-11-18 15:15 UTC, merged