fix grammatical issues in other_form_controls
mdn/content pull request #22319
Opened 2022-11-15 17:53 UTC by yashikabhargava

### Description
fixed minor grammatical issues in other form controls.

2022-11-15 18:14 UTC, dipikabh requested changes
Hello @yashikabhargava, thanks for your PR. I have indicated a few other changes to improve the grammar.

2022-11-15 18:14 UTC, dipikabh commented on files/en-us/learn/forms/other_form_controls/index.md
> +Drop-down controls are a simple way to let users select from many options without taking up much space in the user interface. HTML has two forms of drop-down content: the **select box**, and the **au
```suggestion
Drop-down controls are a simple way to let users select from many options without taking up much space in the user interface. HTML has two types of drop-down controls: the **select box** and the **autocomplete box**. The interaction is the same in both the types of drop-down controls — after the control is activated, the browser displays a list of values the user can select from.
```

2022-11-15 18:14 UTC, dipikabh commented on files/en-us/learn/forms/other_form_controls/index.md
> +- The {{htmlattrxref("low","meter")}} and {{htmlattrxref("high","meter")}} values divide the range into three parts:
```suggestion
- The {{htmlattrxref("low","meter")}} and {{htmlattrxref("high","meter")}} values divide the range into the following three parts:
```

2022-11-15 18:14 UTC, dipikabh commented on files/en-us/learn/forms/other_form_controls/index.md
> +Such a bar is created using a {{HTMLElement("meter")}} element. This is for implementing any kind of meter, for example a bar showing the total space used on a disk, which turns red when it starts to
```suggestion
Such a bar is created by using the {{HTMLElement("meter")}} element. This is for implementing any kind of meter; for example, a bar showing the total space used on a disk, which turns red when it starts to get full.
```

2022-11-16 09:22 UTC, bsmth approved these changes
Thanks both. I'll leave this up to Dipika for a final look before merging 👍🏻

2022-11-16 13:57 UTC, dipikabh approved these changes
Thank you for the fixes!

2022-11-16 13:57 UTC, merged