Refine _blank implicit noopener
mdn/content pull request #2236
Opened 2021-02-10 08:36 UTC by kiding

An anchor tag with its target to _blank has noopener by default. As mentioned in https://github.com/mdn/browser-compat-data/pull/7642, this behavior is now part of the standard.

This PR removes the vendor/version-specific wordings, and adds links to the browser compatibility. The idea is that those who stumble upon the `Window.opener` document could easily end up at the corresponding compatibility data.

2021-02-10 09:30 UTC, rachelandrew commented on files/en-us/web/html/element/a/index.html
> + <p><strong>Note:</strong> Setting <code>target="_blank"</code> on <code>&lt;a&gt;</code> elements implicitly provides the same <code>rel</code> behavior as setting <code>rel="noopener"</code>. See <
While here can you update this to use the new notecard style?

https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#.note.notecard

2021-02-10 09:31 UTC, rachelandrew requested changes
the way we style notes has changed, so if you could update that while in here that would be fantastic.

2021-02-10 17:09 UTC, kiding commented on files/en-us/web/html/element/a/index.html
> + <p><strong>Note:</strong> Setting <code>target="_blank"</code> on <code>&lt;a&gt;</code> elements implicitly provides the same <code>rel</code> behavior as setting <code>rel="noopener"</code>. See <
Done! → b4a5f8f9a285511e4b09d6e5778018cae84f4a5e

2021-02-11 06:49 UTC, rachelandrew approved these changes
thanks :)

2021-02-11 06:49 UTC, merged