Redirect links to new article location
mdn/content pull request #22381
Opened 2022-11-17 23:23 UTC by estelle

Article has been moved; redirect links to the new location and update content to better reflect where the link goes.

2022-11-18 05:23 UTC, dipikabh commented on files/en-us/web/media/images/index.md
> +  - : This changes how browsers load images so their aspect ratios are calculated by the browser early on and can later be used to reserves the display size of an image before it's loaded.
```suggestion
  - : This changes how browsers load images so their aspect ratios are calculated by the browser early on and can later be used to reserve the display size of an image before it's loaded.
```

2022-11-18 05:25 UTC, dipikabh requested changes

2022-11-18 05:25 UTC, dipikabh commented on files/en-us/web/media/images/index.md
> +  - : This changes how browsers load images so their aspect ratios are calculated by the browser early on and can later be used to reserves the display size of an image before it's loaded.
```suggestion
  - : This changes how browsers load images so their aspect ratios are calculated by the browser early on and can later be used to reserve the display size of an image before it's loaded.
```

2022-11-18 20:57 UTC, estelle commented
That can be done in a different PR. This PR was just to get rid of links to a page that no longer exists.

2022-11-21 15:42 UTC, dipikabh approved these changes
Thanks!

2022-11-21 15:42 UTC, merged