Minor: add links for `inert`
mdn/content pull request #22467
Opened 2022-11-22 00:40 UTC by estelle

THe `inert` global attribute page was just recently added. 
added link.
added to "see also"

2022-11-22 02:21 UTC, wbamberg requested changes

2022-11-22 02:21 UTC, wbamberg commented on files/en-us/web/api/htmlelement/inert/index.md
> +- {{domxref("HTMLInputElement.disabled", "disabled")}}
This link is to a page that doesn't exist, is that intentional?

2022-11-22 22:18 UTC, estelle commented on files/en-us/web/api/htmlelement/inert/index.md
> +- {{domxref("HTMLInputElement.disabled", "disabled")}}
I grabbed that from [/Web/API/HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement), not realizing it didn't exist, so fixing that with https://github.com/mdn/content/pull/22485 😄

2022-11-23 01:22 UTC, wbamberg approved these changes
👍 thank you!

2022-11-23 01:22 UTC, merged