[#22377] Amend Font section text to follow GPDR recommendations
mdn/content pull request #22543
Opened 2022-11-25 17:55 UTC by hh-shiung

### Description

Addresses issue #22377. Amends text to recommend using local fonts.

### Motivation

#22377 

### Additional details

* [English news](https://info.gwdg.de/news/en/googlefonts-dsgvo-complient-integration/)
* [German court record](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/)
* [Article: Google Fonts & GDPR](https://blog.runcloud.io/google-fonts-gdpr/)
* [Article: Google Fonts and GDPR](https://cookie-script.com/blog/google-fonts-and-gdpr)

### Related issues and pull requests

Fixes #22377

2022-11-26 01:52 UTC, wbamberg reviewed
Thanks for your PR, @hh-shiung !

2022-11-26 01:52 UTC, wbamberg commented on files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +For more details about using Google Fonts, see [this page](https://developers.google.com/fonts/docs/getting_started).
I think it is strange to start with the GDPR thing, without any intro about what Google Fonts is.

Words like "recent" will not age will in our docs, and I expect most of our visitors won't understand the rewis.io link, although it is better then nothing, perhaps.

I suggest something like:

> As with images, many fonts are protected by licenses, meaning you can't freely use them in your site. [Google Fonts](https://developers.google.com/fonts) is a web service owned by Google that provides access to many fonts which you can use freely. You can visit the site and find a font which you like.
>
> Once you have found a font, there are two main ways you can use it:
> 1. add a reference in your code to load the font from Google's servers
> 2. download the font file to your own system, host the font yourself, and reference your local copy in your website's code.
>
> Note that the first of these options may be incompatible with the European Union's data privacy regulation [GDPR](https://gdpr.eu/what-is-gdpr/), because requesting fonts will expose the user's IP address. If you think this might be a problem for you, you should choose the second option.

But, it looks like there are several places in our docs where we talk about Google Fonts, and we need to check them all if we are to fix this problem.

2023-01-13 15:40 UTC, Elchi3 commented on files/en-us/learn/getting_started_with_the_web/what_will_your_website_look_like/index.md
> +For more details about using Google Fonts, see [this page](https://developers.google.com/fonts/docs/getting_started).
@hh-shiung Are you planning to come back to this PR and address this review feedback?

2023-01-13 15:41 UTC, Elchi3 requested changes
Still outstanding review feedback

2023-05-05 08:44 UTC, bsmth commented
Hi @hh-shiung - I'm closing this PR due to inactivity and unaddressed review comments, let us know if you would like to come back to it - we can re-open it if you pick it up again. Thank you :)

2023-05-05 08:44 UTC, closed without merging