Update PerformanceResourceTiming pages, part 2
mdn/content pull request #22577
Opened 2022-11-28 15:04 UTC by Elchi3

### Description

This PR updates the three content size related properties of the `PerformanceResourceTiming` interface.
- `decodedBodySize`
- `encodedBodySize`
- `transferSize`

### Motivation

https://github.com/openwebdocs/project/issues/62

### Additional details

For `decodedBodySize` and `encodedBodySize` I created example code that checks if content was compressed. For `transferSize` I created example code that checks if a local cache was hit. Let me know if these make sense.

### Related issues and pull requests

Part 1 was done in https://github.com/mdn/content/pull/22503

2022-11-28 18:12 UTC, jpmedley requested changes

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +The **`decodedBodySize`** read-only property returns the size (in octets) received from the fetch (HTTP or cache) of the message body, after removing any applied content-codings. If the resource is r
```suggestion
The **`decodedBodySize`** read-only property returns the size (in octets) received from the fetch (HTTP or cache) of the message body after removing any applied content-codings. If the resource is retrieved from an application cache or local resources, it returns the size of the payload after removing any applied content-codings.
```

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +The **`decodedBodySize`** read-only property returns the size (in octets) received from the fetch (HTTP or cache) of the message body, after removing any applied content-codings. If the resource is r
Is "content-codings" a key or attribute of some kind? It should be "content codings" or `content-codings`.

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +Or using {{domxref("Performance.getEntriesByType()")}}, which only shows `resource` performance entries present in the browser's performance timeline at the time you call this method:
This is a sentence fragment and I'm not sure what's it's trying to tell me.

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +If the value of the `decodedBodySize` property is `0`, the resource might be a cross-origin request. To allow seeing cross-origin content size information, the {{HTTPHeader("Timing-Allow-Origin")}} H
```suggestion
If the value of the `decodedBodySize` property is `0`, the resource might be a cross-origin request. To expose cross-origin content size information, the {{HTTPHeader("Timing-Allow-Origin")}} HTTP response header needs to be set.
```

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +If the value of the `decodedBodySize` property is `0`, the resource might be a cross-origin request. To allow seeing cross-origin content size information, the {{HTTPHeader("Timing-Allow-Origin")}} H
What do you think of this wording? If you change it here, you should reword throughout.

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/encodedbodysize/index.md
> +The **`encodedBodySize`** read-only property represents the size (in octets) received from the fetch (HTTP or cache), of the payload body,
```suggestion
The **`encodedBodySize`** read-only property represents the size (in octets) received from the fetch (HTTP or cache), of the payload body
```

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/encodedbodysize/index.md
> +Or using {{domxref("Performance.getEntriesByType()")}}, which only shows `resource` performance entries present in the browser's performance timeline at the time you call this method:
Sentence fragment again.

2022-11-28 18:12 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/transfersize/index.md
> +Or using {{domxref("Performance.getEntriesByType()")}}, which only shows `resource` performance entries present in the browser's performance timeline at the time you call this method:
Sentence fragment.

2022-11-29 10:32 UTC, Elchi3 commented on files/en-us/web/api/performanceresourcetiming/decodedbodysize/index.md
> +The **`decodedBodySize`** read-only property returns the size (in octets) received from the fetch (HTTP or cache) of the message body, after removing any applied content-codings. If the resource is r
I changed this to "content encoding" which I think is the more common term.

2022-11-29 15:33 UTC, jpmedley requested changes
I understand now that the phrases starting with 'Or' were introducing the next example. I changed them from sentence fragments to sentences.

2022-11-29 15:33 UTC, jpmedley commented on files/en-us/web/api/performanceresourcetiming/transfersize/index.md
> +Example using a {{domxref("PerformanceObserver")}}, which notifies of new `resource` performance entries as they are recorded in the browser's performance timeline:
```suggestion
Here's an example using a {{domxref("PerformanceObserver")}}, which notifies of new `resource` performance entries as they are recorded in the browser's performance timeline:
```

2022-11-29 15:49 UTC, jpmedley approved these changes
Thank you for your patience.

2022-11-29 15:49 UTC, merged