adds pt-BR localization for files/jsondata/L10n-*.json #8749
mdn/content pull request #22590
Opened 2022-11-28 22:16 UTC by josielrocha

### Description

Part of [mdn/translated-content#8749](https://github.com/mdn/translated-content/issues/8749)

### Motivation

### Additional details

### Related issues and pull requests

2022-11-28 23:10 UTC, nathipg commented on files/jsondata/L10n-SVG.json
> +    "pt-BR": "Qualquer número de elementos de animação, elementos descritivos, elementos {{SVGElement(\"mask\")}}, {{SVGElement(\"clipPath\")}}, {{SVGElement(\"marker\")}}, {{SVGElement(\"script\")}}
```suggestion
    "pt-BR": "Qualquer número de elementos de animação, elementos descritivos, elementos {{SVGElement(\"mask\")}}, {{SVGElement(\"clipPath\")}}, {{SVGElement(\"marker\")}}, {{SVGElement(\"script\")}}, e {{SVGElement(\"style\")}}, juntamente com zero ou um elemento {{SVGElement(\"meshgradient\")}}.",
```

2022-11-28 23:14 UTC, nathipg requested changes
Thank you! I made a suggestion, could you look it, please?

2022-11-28 23:20 UTC, nathipg commented
@mdn/yari-content-pt-br OK

2022-11-28 23:43 UTC, nathipg approved these changes

2022-11-29 00:54 UTC, wbamberg approved these changes
👍 looks great, thank you!

2022-11-29 00:55 UTC, merged