Chore: Add details to contrib doc about delete with redirect
mdn/content pull request #22630
Opened 2022-11-30 11:45 UTC by bsmth

Adding details in the contrib doc that you can add a redirect while deleting, e.g.:

```bash
yarn content delete /slug/to/delete --redirect /slug/to/redirect
```

2022-11-30 19:21 UTC, wbamberg reviewed
This is very helpful! I always have to look it up.

But we should consider being stronger here: in general if you delete a document you should _always_ redirect somewhere, or people will get 404s. So we should probably present using `--redirect` as the normal practice, then say later on that `--redirect` is optional (but strongly recommended).

(n fact if I could wave a wand I would make redirect the default and make people pass `--no-redirect` if they don't want it)

wdyt?

2022-12-01 13:46 UTC, bsmth commented
> We should probably present using `--redirect` as the normal practice, then say later on that `--redirect` is optional (but strongly recommended).
> 
> wdyt?

Agreed, added this as the default example with warning admonitions in 45181833fa49f432ea481b97f393d15c89ade422

2022-12-01 22:33 UTC, hamishwillee commented on CONTRIBUTING.md
> +> **Note** You can click the **Source on GitHub** link at the bottom of an MDN page to jump directly to the page source on GitHub.
Perhaps worth keeping the normal note formatting for consistency with normal editing?
```suggestion
> **Note:** You can click the **Source on GitHub** link at the bottom of an MDN page to jump directly to the page source on GitHub.
```

2022-12-01 22:35 UTC, hamishwillee commented on CONTRIBUTING.md
> +Moving one or more documents, or an entire tree of documents is made easier with the `yarn content move` command that takes care of the details:
Just a thought. 
```suggestion
Moving one or more documents (or an entire tree of documents), is made easier with the "move" command, which takes care of the details:
```

2022-12-01 22:37 UTC, hamishwillee commented on CONTRIBUTING.md
> +> If you need to add a redirect without moving a file, ask the MDN Web Docs team first.
1. These things are separate - "not editing the file" and "adding a redirect without moving a file". IMO on the first one should be in the warning. 
2. The note "If you need to add a redirect without moving a file, ask the MDN Web Docs team first." - Why? Just use the redirect command.

2022-12-01 22:40 UTC, hamishwillee commented on CONTRIBUTING.md
> +   > You must add a redirect when deleting documents.
```suggestion
   > You should always add a redirect when deleting documents. If there is no obvious alternative, redirect to the nearest "parent" of the deleted topic.
```

2022-12-01 22:41 UTC, hamishwillee commented on CONTRIBUTING.md
> +   > If you choose add a redirect manually, see [Redirecting a document](#redirecting-a-document) to specify a URL per document.
```suggestion
   > If you forget to redirect when deleting a file, you can do it afterwards: see [Redirecting a document](#redirecting-a-document).
```

2022-12-01 22:42 UTC, hamishwillee commented on CONTRIBUTING.md
> +However, you may need to after [deleting a document](#deleting-a-document) without the `--redirect` flag or when fixing a broken link.
Probably best to use the (hopefully) less likely option first

```suggestion
However, you may need to do so when fixing a broken link, or after [deleting a document](#deleting-a-document) without the `--redirect` flag.
```

2022-12-02 10:31 UTC, bsmth commented
Thanks, @hamishwillee, looking through your comments now 👀

2022-12-02 10:31 UTC, bsmth commented on CONTRIBUTING.md
> +   > You must add a redirect when deleting documents.
Good, tnx

2022-12-02 10:35 UTC, bsmth commented on CONTRIBUTING.md
> +> If you need to add a redirect without moving a file, ask the MDN Web Docs team first.
The yarn commands don't cover all cases, so it's sometimes necessary to edit the redirects file directly. It might be better to leave out the second point and just say "Don't edit the file manually, use commands"

2022-12-02 10:42 UTC, bsmth commented on CONTRIBUTING.md
> +Moving one or more documents, or an entire tree of documents is made easier with the `yarn content move` command that takes care of the details:
Agree at first, but we're using `yarn content <command-name>` everywhere else, so I'm keeping it consistent

2022-12-04 21:26 UTC, dipikabh requested changes
Thanks for updating this page, @bsmth. Just a few nits that might need updating.

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +> **Note**
```suggestion
> **Note:**
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +This moves the file and fixes up redirects automatically:
```suggestion
Moving one or more documents (or an entire tree of documents) is made easier with the `yarn content move` command.
This command moves the file and fixes up redirects automatically. You can use this command as shown below:
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +> **Warning**
```suggestion
> **Warning:**
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +> Don't manually delete directories from the repository: the `delete` command handles other necessary changes such as updating the `_wikihistory.json` file.
```suggestion
Similar to moving files, you can delete documents or a tree of documents easily by using the `yarn content delete` command. 

> **Warning:**
> Don't delete files or directories from the repository manually; the `yarn content delete` command handles the necessary changes such as updating the `_wikihistory.json` file.

You can use this command as shown below:
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +If the slug of the page you wish to delete contains special characters, include it in quotes:
```suggestion
If the slug of the page you wish to delete contains special characters, include it in quotes. For example:
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +If the document has child documents (i.e. it represents a document tree), you must specify the `-r, --recursive` option or the command will fail.
```suggestion
If the document has child documents (i.e., the document represents a document tree), you must specify the `-r, --recursive` option, else the command will fail.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +Say you want to delete the entire `/en-US/Learn/Accessibility` tree and redirect all the deleted documents to `Web/Accessibility`:
```suggestion
Say you want to delete the entire `/en-US/Learn/Accessibility` tree and redirect all the deleted documents to `Web/Accessibility`. You can perform the following steps:
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
>  1. Starting from a fresh branch:
```suggestion
1. Start from a fresh branch.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +2. Run the `yarn content delete` command and redirect all deleted documents:
```suggestion
2. Run the `yarn content delete` command and redirect all deleted documents.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +   > If you forget to redirect when deleting a file, you can do it afterwards: see [Redirecting a document](#redirecting-a-document).
```suggestion
   > **Warning:**
   > You should always add a redirect when deleting documents. If there is no obvious alternative, redirect to the nearest "parent" of the deleted topic.
   > If you forget to redirect when deleting a file, you can do it afterwards. See the [Redirecting a document](#redirecting-a-document) section.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +3. Commit all of the changes and push your branch to the remote:
```suggestion
3. Commit all of the changes and push your branch to the remote.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +2. Add a redirect with `yarn content add-redirect`. The target page can a page on MDN or an external URL:
```suggestion
2. Add a redirect with `yarn content add-redirect`. The target page can be a page on MDN or an external URL:
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +You may do this using the `yarn content add-redirect` command:
```suggestion
You may do this by using the `yarn content add-redirect` command.
```

2022-12-04 21:26 UTC, dipikabh commented on CONTRIBUTING.md
> +However, you may need to do so when fixing a broken link, or after [deleting a document](#deleting-a-document) without the `--redirect` flag.
```suggestion
However, you may need to do so when fixing a broken link or after [deleting a document](#deleting-a-document) without the `--redirect` flag.
```

2022-12-05 09:20 UTC, bsmth commented on CONTRIBUTING.md
> +> **Note**
Having it like `> **Note**` renders a note admonition on GitHub:

![image](https://user-images.githubusercontent.com/43580235/205599950-8cb8a537-995b-4750-a4dc-2617a2b8316a.png)

These markdown files will just be read on GitHub, so I think it's okay to deviate from the rest of the conventions we have under `./files/*`, what do you think?

2022-12-05 09:20 UTC, bsmth commented on CONTRIBUTING.md
> +> **Warning**
Same as above

2022-12-08 05:27 UTC, dipikabh approved these changes
Leaving a question about the Note/Warning tags. This is otherwise good to go. Thanks a lot, @bsmth!

2022-12-08 05:27 UTC, merged