New page: validityState.valueMissing
mdn/content pull request #22691
Opened 2022-12-03 02:03 UTC by estelle

Fixes https://github.com/mdn/content/issues/22557

2022-12-06 08:59 UTC, teoli2003 requested changes

2022-12-06 08:59 UTC, teoli2003 commented on files/en-us/web/api/validitystate/valuemissing/index.md
> +```
I think we should display the value in a field, so that devs can experience when the value is changed:

```suggestion
```html
<p>
  <label>
    Enter a username:
    <input type="text" name="username" id="username" required />
  </label>
</p>
<p>
  <label>
    Is the username missing:
    <output id="usernameOutput">Yes</output>
  </label>
</p>
<p>
  <label >
    Enter your password:
    <input type="password" name="password" id="password" required />
  </label>
</p>
<p>
  <label>
    Is the password missing:
    <output id="passwordOutput">Yes</output>
  </label>
</p>
```

```css
input:invalid {
  border: red solid 3px;
}
```

```js
console.log("start");
const usernameElt = document.querySelector("#username");
const usernameOutput = document.querySelector("#usernameOutput");
const passwordElt = document.querySelector("#password");
const passwordOutput = document.querySelector("#passwordOutput");

console.log(usernameElt.validity.valueMissing);
// Check if the required password field is missing
usernameElt.addEventListener("change", (event) => {
  console.log("bkgj");
  usernameOutput.value = usernameElt.validity.valueMissing?"Yes":"No";
});

passwordElt.addEventListener("change", (event) => {
  passwordOutput.value = passwordElt.validity.valueMissing?"Yes":"No";
});
```
```

2022-12-06 19:40 UTC, estelle commented on files/en-us/web/api/validitystate/valuemissing/index.md
> +```
I think it is actually best to not have any examples. valueMissing should only be checked on submit. so anything other than that would be showing an anti-pattern.

2022-12-07 15:29 UTC, teoli2003 approved these changes

2022-12-07 15:29 UTC, merged