specify data type of websocket message event
mdn/content pull request #22695
Opened 2022-12-03 12:06 UTC by jingkaimori

### Description

Specify data type of `messageEvent.data` in websocket interface.

### Motivation

Specify type so readers can avoid type errors on this interface

### Additional details

related chapter on whatwg: [WebSockets](https://websockets.spec.whatwg.org/#eventdef-websocket-message)

### Related issues and pull requests

2023-03-27 20:49 UTC, Josh-Cena commented on files/en-us/web/api/websocket/message_event/index.md
> +      - {{domxref("Blob")}} if `binaryType` is `"blob"`.
```suggestion
  - : The data sent by the message emitter. This field may be one of types below depending on type of websocket message and {{domxref("WebSocket.binaryType")}}.
    - If the received socket message is a string, then this field is a string.
    - If the received socket message is binary type, then the type of this field will be inferred from `binaryType` of this socket:
      - {{jsxref("ArrayBuffer")}} if `binaryType` is `"arraybuffer"`,
      - {{domxref("Blob")}} if `binaryType` is `"blob"`.
```

2023-03-27 20:50 UTC, Josh-Cena commented
Pinging @wbamberg for review

2023-03-29 05:59 UTC, Josh-Cena commented
(Also, I guess this information should be added to the `data` reference page itself rather than this overview page)

2023-03-31 00:15 UTC, wbamberg requested changes
Thanks for your PR, @jingkaimori !

I had some copy-edit suggestions, but also I wasn't sure how someone can figure out the type of the message, although I can see it in the RFC.

2023-03-31 00:15 UTC, wbamberg commented on files/en-us/web/api/websocket/message_event/index.md
> +  - : The data sent by the message emitter. This field may be one of types below depending on type of websocket message and {{domxref("WebSocket.binaryType")}}.
```suggestion
  - : The data sent by the message emitter. The type of this property depends on the type of the WebSocket message and the value of {{domxref("WebSocket.binaryType")}}.
```
...but how do we know the type of the WebSocket message? It seems to be visible as the `opcode` value in https://datatracker.ietf.org/doc/html/rfc6455#section-5.2, but I couldn't see how this is visible in the JS API.

2023-03-31 00:15 UTC, wbamberg commented on files/en-us/web/api/websocket/message_event/index.md
> +    - If the received socket message is binary type, then the type of this field will be inferred from `binaryType` of this socket:
```suggestion
    - If the message type is "text", then this field is a string.
    - If the message type is "binary" type, then the type of this property can be inferred from the `binaryType` of this socket:
```

2023-03-31 15:39 UTC, Josh-Cena commented on files/en-us/web/api/websocket/message_event/index.md
> +  - : The data sent by the message emitter. The type of this property depends on the type of the WebSocket message and the value of {{domxref("WebSocket.binaryType")}}.
Could you move this information to the `data` page? This description here should only be a one-line overview.

2023-04-06 07:24 UTC, dontcallmedom commented on files/en-us/web/api/websocket/message_event/index.md
> +  - : The data sent by the message emitter. This field may be one of types below depending on type of websocket message and {{domxref("WebSocket.binaryType")}}.
I'm not sure who is "we" in the above; as a developer, you would know by e.g. testing `typeof data === 'string'` (and if it isn't, then you would check `binaryType` to figure how the binary data is represented). The browser is responsible for mapping the protocol bits to the JS surface.

(in reality, in most cases there is a tight coupling between the JS consumer and the emitter, so the developer may simply know the type from out of band coordination)

2023-04-08 17:57 UTC, wbamberg commented on files/en-us/web/api/websocket/message_event/index.md
> +  - : The data sent by the message emitter. This field may be one of types below depending on type of websocket message and {{domxref("WebSocket.binaryType")}}.
Thank you @dontcallmedom , of course, that makes sense.

2023-04-08 17:58 UTC, wbamberg commented on files/en-us/web/api/websocket/message_event/index.md
> +  - : The data sent by the message emitter. The type of this property depends on the type of the WebSocket message and the value of {{domxref("WebSocket.binaryType")}}.
@jingkaimori , could you also make this change please? Then I think we should be able to merge this PR.

2023-04-12 21:47 UTC, wbamberg approved these changes
👍 thank you @jingkaimori !

2023-04-12 21:47 UTC, merged