Matched descriptions with a similar article
mdn/content pull request #22716
Opened 2022-12-04 11:22 UTC by akaabdullahmateen

### Description

The articles [`:nth-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) and [`:nth-last-child`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child) are both very similar in nature. Both should have had almost same description for its functional notation. However, some information present in one article was not in other.

2022-12-04 20:28 UTC, dipikabh requested changes
Thanks @akaabdullahmateen! Just a tiny change required.

2022-12-04 20:28 UTC, dipikabh commented on files/en-us/web/css/_colon_nth-child/index.md
> +    It can be read as the `An+B`-th element of a list. The index of the first element, counting from the start, is `1`. The values `A` and `B` must both be {{cssxref("&lt;integer&gt;")}}s.
```suggestion
    It can be read as the `An+B`-th element of a list. The values `A` and `B` must both be {{cssxref("&lt;integer&gt;")}}s.
```
`n` in this case start from 0, as stated in the last bullet point here

2022-12-04 21:28 UTC, akaabdullahmateen commented on files/en-us/web/css/_colon_nth-child/index.md
> +    It can be read as the `An+B`-th element of a list. The index of the first element, counting from the start, is `1`. The values `A` and `B` must both be {{cssxref("&lt;integer&gt;")}}s.
@dipikabh Thanks for pointing out!

2022-12-05 08:35 UTC, akaabdullahmateen commented
I am ridiculously bad at using GitHub, so I ended up creating two separate pull requests for the two pages, rather than creating a single pull request with changes to both pages.

Please check out the other very similar pull request: #22715

2022-12-12 22:55 UTC, dipikabh approved these changes
Thank you, @akaabdullahmateen!

2022-12-12 22:55 UTC, merged