Add new screen capture constraints and options
mdn/content pull request #22733
Opened 2022-12-05 06:47 UTC by chrisdavidmills

### Description

This PR adds a bunch of content covering new constraints and options from the screen capture API. You can see what's been added in my research document, at https://docs.google.com/document/d/1HUZMVu_hGTUdkThLhqrUDMBKqvFS5YNRs0xGEHIYaMY/edit#heading=h.frl8u3cowbcx

### Motivation

### Additional details

### Related issues and pull requests

2022-12-06 23:48 UTC, dipikabh commented
Hi @wbamberg, hope it is okay to leave the review for this PR to you

2022-12-07 09:52 UTC, beaufortfrancois reviewed
Thank you @chrisdavidmills!

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/capturecontroller/setfocusbehavior/index.md
> +  - : Thrown if the capture stream has been stopped, or if enough time has elapsed after the {{domxref("MediaDevices.getDisplayMedia()")}} `Promise` fulfills that the focus behavior has been finalize
Calling setFocusBehavior() also throws after the getDisplayMedia() returned promise resolves, if the user shared a screen (not a tab or a window).

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/mediatrackconstraints/displaysurface/index.md
> +if (displaySurface === "monitor" || displaySurface ==="window") {
I'm not sure we want to replace "application" with "window" there. If so, you may want to update the paragraph above that still uses "application" then.

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +setting for the noise suppression feature; if it can't be met, then the request will
Exact values are **not** allowed in getDisplayMedia calls. They are in applyConstraints calls.

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/mediatracksettings/suppresslocalaudioplayback/index.md
> +    video: {},
This line is not needed as default value for video is true.

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/mediatracksettings/suppresslocalaudioplayback/index.md
> +  let supportedConstraints = navigator.mediaDevices.getSupportedConstraints();
Nit: Use `const` instead of `let`.

2022-12-07 09:52 UTC, beaufortfrancois commented on files/en-us/web/api/mediatracksupportedconstraints/suppresslocalaudioplayback/index.md
> +  let supportedConstraints = navigator.mediaDevices.getSupportedConstraints();
Ditto

2022-12-07 10:25 UTC, chrisdavidmills commented on files/en-us/web/api/capturecontroller/setfocusbehavior/index.md
> +  - : Thrown if the capture stream has been stopped, or if enough time has elapsed after the {{domxref("MediaDevices.getDisplayMedia()")}} `Promise` fulfills that the focus behavior has been finalize
OK, updating this in my next commit. Since the number of different circumstances for throwing an `InvalidState` error got to three, I've split them out into a bulleted list to make them easier to read.

2022-12-07 10:28 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/displaysurface/index.md
> +if (displaySurface === "monitor" || displaySurface ==="window") {
Ah, good spot; I missed that mention of "application". I've updated it to "window" to match the code snippet, as the "application" value was removed from the spec. I'm not sure if it has been removed from browsers yet, but I thought this would be good defensive writing for either eventuality.

2022-12-07 10:53 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +setting for the noise suppression feature; if it can't be met, then the request will
I've had a go at updating this section, but I do find these constraint object values rather confusing. You'll have to let me know if you think I'm any closer to getting it right. This also makes me think of two other issues:

* We ought to look at the other screen capture-specific constraints, and see if they are correct in terms of not using `exact`.
* I ought to put the note about `exact` not being permitted in getDisplayMedia calls somewhere in the main http://localhost:5042/en-US/docs/Web/API/MediaTrackConstraints page, so it is more visible. But probably not on every individual constraint page.
What do you think?

2022-12-07 10:55 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksettings/suppresslocalaudioplayback/index.md
> +    video: {},
OK, removed.

2022-12-07 10:57 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksupportedconstraints/suppresslocalaudioplayback/index.md
> +    video: {},
updated

2022-12-07 10:57 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksupportedconstraints/suppresslocalaudioplayback/index.md
> +  let supportedConstraints = navigator.mediaDevices.getSupportedConstraints();
updated

2022-12-07 11:05 UTC, chrisdavidmills commented
@beaufortfrancois OK, fixes pushed; thanks for all the comments! There are a couple that I think require a bit more input from you, but overall this is getting close.

2022-12-07 11:44 UTC, beaufortfrancois commented on files/en-us/web/api/mediatrackconstraints/displaysurface/index.md
> +window—meaning that there's possibly a non-content backdrop—it can use code similar
I'm not sure which non-content backdrop appears in a single window?

2022-12-07 11:44 UTC, beaufortfrancois commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> +  systemAudio: "exclude"
You may want to update the explanation text as well then.

2022-12-07 11:44 UTC, beaufortfrancois commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +setting for the noise suppression feature; if it can't be met, then the request will
Maybe the getDisplayMedia page as well? See https://w3c.github.io/mediacapture-screen-share/#dfn-floor-value:~:text=While%20min%20and%20exact%20constraints%20produce%20TypeError

2022-12-07 12:18 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/displaysurface/index.md
> +window—meaning that there's possibly a non-content backdrop—it can use code similar
Good point; I've changed it so that it only applies to a fullscreen/monitor capture.

2022-12-07 12:28 UTC, chrisdavidmills commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> +  systemAudio: "exclude"
Good point; explanation updated.

2022-12-07 12:42 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +setting for the noise suppression feature; if it can't be met, then the request will
Good call. I've checked, and it is kind of covered on that page, in the TypeError entry in the Exceptions section, but I've added in a line explicitly to say that min and exact are not allowed.

I've also followed my plan as outlined above.

2022-12-07 12:44 UTC, chrisdavidmills commented
@beaufortfrancois OK, more fixes made. Thanks again!

2022-12-07 12:47 UTC, beaufortfrancois commented
LGTM! Thank you!

2022-12-15 00:02 UTC, wbamberg commented
Related BCD PR -> https://github.com/mdn/browser-compat-data/pull/18264.

2022-12-15 03:26 UTC, wbamberg requested changes
Sorry for the delay, Chris!

2022-12-15 03:26 UTC, wbamberg commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
>  > **Note:** Some properties are not widely implemented and might not be used by the engine. `cursor`, for example, [has limited support](/en-US/docs/Web/API/MediaTrackConstraints#browser_compatibilit
`cursor` doesn't appear in the linked table. (In general I don't really like notes like this. People always need to check the compat tables.)

2022-12-19 09:24 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
> +        "MediaTrackSupportedConstraints"
I was kinda trying to reduce the amount of verbiage in the sidebar, as I felt it looked a bit horrible ;-)

But I appreciate that what I did doesn't really work.

I have added the separate `MediaTrackSupportedConstraints.*` pages back in, in my next commit.

Some notes:

1. I've not included `*.restrictOwnAudio` pages, as `restrictOwnAudio` is not part of this PR; I don't think it is supported yet.
2. I've removed `MediaTrackSupportedConstraints.cursor` and `MediaTrackConstraints.cursor`; those URLs redirect to the parent class page, as they don't exist any more. I'm not really sure why.

2022-12-19 09:25 UTC, chrisdavidmills commented on files/en-us/web/api/screen_capture_api/index.md
> +- {{domxref("MediaTrackConstraints.suppressLocalAudioPlayback")}}
See above; not part of this PR, I don't think it is supported yet

2022-12-19 09:26 UTC, chrisdavidmills commented on files/en-us/web/api/capturecontroller/setfocusbehavior/index.md
> +`Undefined`.
Change made in next commit.

2022-12-19 09:29 UTC, chrisdavidmills commented on files/en-us/web/api/mediadevices/getdisplaymedia/index.md
> +getDisplayMedia(options)
Makes sense; added in next commit

2022-12-19 09:33 UTC, chrisdavidmills commented on files/en-us/web/api/mediadevices/getdisplaymedia/index.md
> +  - : An optional object specifying requirements for the returned {{domxref("MediaStream")}}. The options for `getDisplayMedia()` work in the same as the [constraints](/en-US/docs/Web/API/MediaDevice
I tried to fix this for ages when I was originally writing this, and gave up ;-)

I just had another look, and realized that it was because the note following the `<dl>` was indented. Fixed in next commit.

2022-12-19 09:33 UTC, chrisdavidmills commented on files/en-us/web/api/mediadevices/getdisplaymedia/index.md
> +    - `video`
fixed, ta.

2022-12-19 10:21 UTC, chrisdavidmills commented on files/en-us/web/api/mediadevices/getdisplaymedia/index.md
> +      - : A boolean; a value of `true` indicates that the returned {{domxref("MediaStream")}} will contain a video track. Be aware that, since `getDisplayMedia()` requires a video track, the returned
Changes made. as requested. Yup, it is quite confusing. I don't have a good answer for your question.

2022-12-19 10:24 UTC, chrisdavidmills commented on files/en-us/web/api/mediadevices/getdisplaymedia/index.md
> +    - `audio` {{optional_inline}}
Done; I think I've worked these out correctly...

2022-12-19 10:25 UTC, chrisdavidmills commented on files/en-us/web/api/screen_capture_api/index.md
> +  - : A Boolean value, which is `true` if the audio being captured is not played out of the user's local speakers.
Agreed; changed.

2022-12-19 10:27 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +`true`/`false`, or a [`ConstrainBoolean`](/en-US/docs/Web/API/MediaTrackConstraints#constrainboolean) object.
Agreed, that is a bit less confusing. Updated.

2022-12-19 10:28 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +If, instead, the value is given as a [`ConstrainBoolean`](/en-US/docs/Web/API/MediaTrackConstraints#constrainboolean) object
Updated wording to suit.

2022-12-19 10:28 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +object with an `ideal` field, that field's Boolean value indicates an ideal
Updated

2022-12-19 10:35 UTC, chrisdavidmills commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +See {{SectionOnPage("/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints", "Example: Constraint exerciser")}} for an example.
macro removed. I've also updated the example section to include a one-line example,

2022-12-19 10:38 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksettings/suppresslocalaudioplayback/index.md
> +    videoElem.srcObject = await navigator.mediaDevices.getDisplayMedia(displayMediaOptions);
It can also be a `MediaTrackConstraints` object.

2022-12-19 10:38 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksupportedconstraints/suppresslocalaudioplayback/index.md
> +A Boolean value which is `true` if the {{domxref("MediaTrackConstraints.suppressLocalAudioPlayback", "suppressLocalAudioPlayback")}} constraint is supported by the device and user agent.
Updated

2022-12-19 10:39 UTC, chrisdavidmills commented on files/en-us/web/api/mediatracksupportedconstraints/suppresslocalaudioplayback/index.md
> +The below function sets up the constraints object specifying the options for the call to {{domxref("MediaDevices.getDisplayMedia", "getDisplayMedia()")}}. It adds the `suppressLocalAudioPlayback` con
update made

2022-12-19 10:40 UTC, chrisdavidmills commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> +The `video` and `audio` objects pased in to the options object can also hold additional constraints particular to those media tracks. See [Properties of shared screen tracks](/en-US/docs/Web/API/Medi
Updated

2022-12-19 10:54 UTC, chrisdavidmills commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
>  > **Note:** Some properties are not widely implemented and might not be used by the engine. `cursor`, for example, [has limited support](/en-US/docs/Web/API/MediaTrackConstraints#browser_compatibilit
This is a bad example, it looks like `cursor` has been removed, as a number of the cursor-related pages no longer exist. I've changed it to use `displaySurface`. 

Question - the live sample should update automatically, right? I've completely forgotten how they work ;-)

2022-12-19 10:56 UTC, chrisdavidmills commented
Thanks for the review @wbamberg ! I think I've addressed everything

2022-12-19 19:02 UTC, wbamberg approved these changes
👍 thank you for the updates, Chris!

2022-12-19 19:02 UTC, merged

2022-12-19 19:31 UTC, chrisdavidmills commented
Woo hoo! Thanks @wbamberg!