Add documentation for SecurityInfo.secretKeyLength
mdn/content pull request #22760
Opened 2022-12-05 22:32 UTC by gregorypappas

### Description

Add documentation for the SecurityInfo.secretKeyLength property.

### Motivation

Needs to be documented.

### Additional details

https://bugzilla.mozilla.org/show_bug.cgi?id=1778473

### Related issues and pull requests

Relates to mdn/browser-compat-data#18371

2023-01-13 03:46 UTC, gregorypappas commented
@rebloor Hi, would you be able to review this? Thanks!

2023-01-13 16:47 UTC, rebloor commented
@gregorypappas this duplicates my PR for the same change ([#23423](https://bugzilla.mozilla.org/show_bug.cgi?id=1778473)). If you would like to add the release note to this one, it might be quicker than waiting for a review on mine.

2023-01-13 16:49 UTC, rebloor requested changes

2023-01-13 16:49 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/securityinfo/index.md
> +  - : `String`. The length (in bits) of the TLS secret key.
Are you sure it's a string? I'm sure when I checked, it said number
```suggestion
  - : `String`. The length of the secret key in bits.
```

2023-01-13 17:38 UTC, gregorypappas commented
@rebloor Done.

2023-01-16 02:03 UTC, rebloor approved these changes

2023-01-16 02:03 UTC, merged

2023-01-16 02:04 UTC, rebloor commented
Thanks @gregorypappas