22118 108 release notes
mdn/content pull request #22797
Opened 2022-12-07 16:39 UTC by dletorey

### Description

Added release note for `font-variant-emoji`

### Motivation

Working on documenting https://bugzilla.mozilla.org/show_bug.cgi?id=1461589

### Additional details

### Related issues and pull requests

https://github.com/mdn/content/issues/22118

#### Pull Requests

- [Content](https://github.com/mdn/content/pull/22794)
- [BCD](https://github.com/mdn/browser-compat-data/pull/18381)

2022-12-08 17:47 UTC, dipikabh requested changes
Hi @dletorey, reviewed only the release note file here since the other files are part of https://github.com/mdn/content/pull/22794.

2022-12-08 17:47 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/108/index.md
> +- [`font-variant-emoji`](/en-US/docs/Web/CSS/font-variant-emoji) property is now supported, which allows a web author to set a default presentation style for displaying emojis.
```suggestion
- The [`font-variant-emoji`](/en-US/docs/Web/CSS/font-variant-emoji) property is now supported via the `layout.css.font-variant-emoji.enabled` preference, which is set to `false` by default. This property allows you to set a default presentation style for displaying emojis ({{bug(1461589)}}).
```

2022-12-14 21:50 UTC, dipikabh approved these changes
Thank you!

2022-12-14 22:08 UTC, dipikabh commented
So this PR is good and ready to land. I am wondering if you should push another commit here with only the release file and all other files removed. Otherwise we might have to watch for the order of merging this PR and https://github.com/mdn/content/pull/22794. We wouldn't want any conflicts or overwrites.

2022-12-15 09:03 UTC, bsmth commented on files/en-us/web/css/font-variant-alternates/index.md
> -- {{cssxref("@font-feature-values")}}
I think `cssxref` is still being used. Should we revert this change and use the macro for the additions?

2022-12-15 09:04 UTC, bsmth commented on files/en-us/web/css/font-variant-caps/index.md
> +- [`font-variant-position`](/en-US/docs/Web/CSS/font-variant-position)
Same here and in `files/en-us/web/css/font-variant-east-asian/index.md` below

2022-12-15 09:07 UTC, bsmth commented on files/en-us/mozilla/firefox/releases/108/index.md
> +- The [`font-variant-emoji`](/en-US/docs/Web/CSS/font-variant-emoji) property is now supported via the `layout.css.font-variant-emoji.enabled` preference, which is set to `false` by default. This pro
If it's not enabled by default, then I think we should be adding this to the [experimental features](https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/experimental_features/index.md) page.

2022-12-15 10:07 UTC, merged