Implement font-variant-emoji #22118
mdn/content pull request #22794
Opened 2022-12-07 16:18 UTC by dletorey

### Description

Created the `font-variant-emoji` page documented and added an example

Created links in `font-variant` shorthand, `font-variant-alternates`, `font-variant-caps`, `font-variant-east-asian`, `font-variant-ligatures`, `font-variant-numeric` and `font-variant-position` properties.

Also added values fo `font-variant-position` to `font-variant`

Updated all the cssxref macro in these pages to be markdown links (based on @hamishwillee's advice) to make links work in github as well as mdn.

### Motivation

Documenting the firefox release for {`font-variant-emoji`](https://github.com/mdn/content/issues/22118)

### Additional details

- [Bugzilla URL](https://bugzilla.mozilla.org/show_bug.cgi?id=1461589)
- [W3 Draft URL](https://drafts.csswg.org/css-fonts-4/#font-variant-emoji-prop)
- [Related BCD Pull Request](https://github.com/mdn/browser-compat-data/pull/18381)

### Related issues and pull requests

Fixes #22118

2022-12-08 07:40 UTC, estelle commented
Can we include a section on accessibility concerns? https://uxdesign.cc/emojis-in-accessibility-how-to-use-them-properly-66b73986b803 includes some good points. For example, repeated emojis lead to a bad user experience for screen reader users.

2022-12-08 07:57 UTC, Josh-Cena commented
> make links work in github as well as mdn.

I'm surprised—the link doesn't work on GitHub anyway, because it's not a FQDN. All it does is to make it "look like" a link, which I'm not sure is any better. We should never be reading the rendered text on GitHub. At the same time it makes the source longer with a lot of redundant text. (I'm starting to see the value in using xref macros myself)

2022-12-08 17:13 UTC, dipikabh requested changes
Looks good overall, @dletorey! Few things will need updating (plus Estelle's comment).

"See also" should follow sentence casing as in other titles. You seemed to have touched a set of pages where it was incorrect 🙂.

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant/index.md
> +  - : Sets the value of the [`font-variant-ligatures`](/en-US/docs/Web/CSS/font-variant-ligatures) to `none` and the values of the other longhand property as `normal`, their initial value.
```suggestion
  - : Sets the value of the [`font-variant-ligatures`](/en-US/docs/Web/CSS/font-variant-ligatures) as `none` and the values of the other longhand properties as `normal`, their initial value.
```

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant/index.md
> +  - : Specifies the keywords related to the [`font-variant-ligatures`](/en-US/docs/Web/CSS/font-variant-ligatures) longhand property. The possible values are: `common-ligatures`, `no-common-ligatures
```suggestion
  - : Specifies the keywords related to the [`font-variant-ligatures`](/en-US/docs/Web/CSS/font-variant-ligatures) longhand property. The possible values are `common-ligatures`, `no-common-ligatures`, `discretionary-ligatures`, `no-discretionary-ligatures`, `historical-ligatures`, `no-historical-ligatures`, `contextual`, and `no-contextual`.
```
Sorry, the edit suggestions are unrelated to your changes. It is not apparent, but I removed the ":" after "are". It would be great if you can remove the ":" after "are" from the other descriptions here as well.

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant/index.md
> +  - : Specifies the keywords related to the [`font-variant-east-asian`](/en-US/docs/Web/CSS/font-variant-east-asian) longhand property. The possible values are: `jis78`, `jis83`, `jis90`, `jis04`, `s
```suggestion
  - : Specifies the keywords related to the [`font-variant-east-asian`](/en-US/docs/Web/CSS/font-variant-east-asian) longhand property. The possible values are `jis78`, `jis83`, `jis90`, `jis04`, `simplified`, `traditional`, `full-width`, `proportional-width`, and `ruby`.
```

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant-east-asian/index.md
>  ## See Also
```suggestion
## See also
```

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant-caps/index.md
>  ## See Also
```suggestion
## See also
```

2022-12-08 17:13 UTC, dipikabh commented on files/en-us/web/css/font-variant-alternates/index.md
>  ## See Also
```suggestion
## See also
```

2022-12-08 18:01 UTC, dipikabh commented
@dletorey, adding a note here for you to check my comment in the BCD PR for this property: https://github.com/mdn/browser-compat-data/pull/18381#issuecomment-1343095301

2022-12-14 12:11 UTC, dletorey commented on files/en-us/web/css/font-variant/index.md
> +  - : Specifies the keywords related to the [`font-variant-ligatures`](/en-US/docs/Web/CSS/font-variant-ligatures) longhand property. The possible values are: `common-ligatures`, `no-common-ligatures
On it

2022-12-14 12:21 UTC, dletorey commented on files/en-us/web/css/font-variant/index.md
> +- [`font-variant-position`](/en-US/docs/Web/CSS/font-variant-position)
yeah that makes sense

2022-12-14 15:16 UTC, dletorey commented
> Can we include a section on accessibility concerns? https://uxdesign.cc/emojis-in-accessibility-how-to-use-them-properly-66b73986b803 includes some good points. For example, repeated emojis lead to a bad user experience for screen reader users.

I have added an accessibilty concerns section to the page.

2022-12-14 15:32 UTC, dletorey commented
> @dletorey, adding a note here for you to check my comment in the BCD PR for this property: [mdn/browser-compat-data#18381 (comment)](https://github.com/mdn/browser-compat-data/pull/18381#issuecomment-1343095301)

Fixed this and [created a new Pull Request](https://github.com/mdn/browser-compat-data/pull/18426)

2022-12-14 22:28 UTC, dipikabh requested changes

2022-12-14 22:28 UTC, dipikabh commented on files/en-us/web/css/font-variant-emoji/index.md
> +Do not use emojis to replace words as your understanding of the meaning may differ from the users. Use commonly known emojis that and consider that emojis will have different meanings in different cu
Thank you for adding this content!!

How about replacing the sub-sections with bullet points and moving the link to the "See also" section? 

```suggestion
## Accessibility concerns

While the use of emojis may seem fun, you should consider their impact on accessibility, specifically for users with visual and cognitive impairments. Consider the following factors while using emojis:

- Display on screen-readers: Screen-readers will read out the alt text of an emoji. Keep this in mind to consider the position of an emoji in the content. Repeated and overuse of emojis will have a detrimental effect on screen-reader users. It is better to use emojis than emoticons; emoticons will be read out as punctuation characters.

- Contrast with background: When using emojis, consider their colors and how that will work with the background color, especially if you have background colors that can change, such as light/dark modes.

- Intent of use: Do not use emojis to replace words because your understanding of the emoji meaning may differ from that of the users'. Also consider that emojis might have different meanings in different cultures and geographies. Our recommendation is to preferably limit usage to commonly known emojis.
```

2022-12-14 22:28 UTC, dipikabh commented on files/en-us/web/css/font-variant-emoji/index.md
> +- [font-variant-numeric](/en-US/docs/Web/CSS/font-variant-numeric)
```suggestion
- [font-variant-numeric](/en-US/docs/Web/CSS/font-variant-numeric)
- [Emojis and accessibility: How to use them properly](https://uxdesign.cc/emojis-in-accessibility-how-to-use-them-properly-66b73986b803)
```

2022-12-14 22:29 UTC, dipikabh commented on files/en-us/web/css/font-variant-emoji/index.md
> +Do not use emojis to replace words as your understanding of the meaning may differ from the users. Use commonly known emojis that and consider that emojis will have different meanings in different cu
Please feel free to suggest alternate/better bullet point lead-ins

2022-12-15 10:10 UTC, dletorey commented on files/en-us/web/css/font-variant-emoji/index.md
> +- [font-variant-numeric](/en-US/docs/Web/CSS/font-variant-numeric)
I like this idea of moving the link to _See also_ section

2022-12-15 13:15 UTC, dipikabh approved these changes
Looks good, thank you 👍

2022-12-15 13:15 UTC, merged