@import must occur at top of stylesheet
mdn/content pull request #22824
Opened 2022-12-08 18:00 UTC by mikepierce

Specified that @import rules have to come before any declarations in the stylesheet, as per https://www.w3.org/TR/CSS1/

### Description

Added stipulation that @import must occur at the top of a stylesheet

### Motivation

So readers know they can't @import at the bottom of their stylesheet

2022-12-08 20:36 UTC, estelle commented
`\@import` can be preceded by `\@charset`  and `\@layers`

2022-12-08 20:40 UTC, dipikabh requested changes
Hi @mikepierce, welcome to the MDN Web Docs project and community! 🎉 Thanks for opening this pull request to improve the content. 🙌 

Please see my edit suggestions to your changes.

2022-12-08 20:40 UTC, dipikabh commented on files/en-us/web/css/@import/index.md
> +The **`@import`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to import style rules from other stylesheets. An `@import` rule _must_ occur at the top of stylesheet befor
```suggestion
The **`@import`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to import style rules from other valid stylesheets. An `@import` rule _must_ be defined at the top of stylesheet, before any other at-rule and style declaration, else it will be ignored.
```

(Referring https://drafts.csswg.org/css-cascade-5/#at-import)

Although the [Description](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description) section mentions the following along with the appropriate qualifiers, I think it is nice to emphasize it in the intro para:
"Imported rules must come before all other types of rules, except [@charset](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset) rules and layer creating [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) statements."

2022-12-08 20:44 UTC, dipikabh commented on files/en-us/web/css/@import/index.md
> +The **`@import`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to import style rules from other stylesheets. An `@import` rule _must_ occur at the top of stylesheet befor
As Estelle has pointed out, maybe change the phrase "before any other at-rule and style declaration" to "before any other at-rule (except [@charset](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset) and [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)) and style declaration"

2022-12-12 13:59 UTC, dipikabh requested changes
Tiny nit as mentioned in previous review

2022-12-12 13:59 UTC, dipikabh commented on files/en-us/web/css/@import/index.md
> +The **`@import`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to import style rules from other valid stylesheets. An `@import` rule _must_ be defined at the top of style
```suggestion
The **`@import`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to import style rules from other valid stylesheets. An `@import` rule _must_ be defined at the top of stylesheet, before any other at-rule (except [@charset](/en-US/docs/Web/CSS/@charset) and [@layer](/en-US/docs/Web/CSS/@layer)) and style declaration, else it will be ignored.
```

2022-12-14 02:41 UTC, dipikabh approved these changes
Thank you and congratulations on landing your first changes on MDN! 🎉

2022-12-14 02:43 UTC, merged