fix CSSRuleList item() example
mdn/content pull request #22833
Opened 2022-12-09 03:29 UTC by Ahmed-Hakeem

### Description

Fixed the provided example since it doesn't contain item method, and added the difference between accessing item using this method and using regular property accessor

2022-12-09 13:04 UTC, Elchi3 requested changes
Thanks for your PR! A few suggestions.

(Much like DOMStringList, this interface is a legacy feature, see https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)

2022-12-09 13:38 UTC, Ahmed-Hakeem commented
> Thanks for your PR! A few suggestions.
> 
> (Much like DOMStringList, this interface is a legacy feature, see https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)

Thank you for your suggestions❤️, how about making a PR to add this hint to the CSSRulesList page, and others .... or extending this PR with this hint

2022-12-09 13:50 UTC, Elchi3 commented
> Thank you for your suggestions❤️, how about making a PR to add this hint to the CSSRulesList page, and others .... or extending this PR with this hint

You're welcome. If you like you can extend this PR! I made a PR to DOMStringList recently: https://github.com/mdn/content/pull/22750

2022-12-09 13:58 UTC, Ahmed-Hakeem commented
> > Thank you for your suggestions❤️, how about making a PR to add this hint to the CSSRulesList page, and others .... or extending this PR with this hint
> 
> 
> 
> You're welcome. If you like you can extend this PR! I made a PR to DOMStringList recently: https://github.com/mdn/content/pull/22750

Sure

2022-12-11 07:13 UTC, sideshowbarker commented on files/en-us/web/api/cssrulelist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:13 UTC, sideshowbarker commented on files/en-us/web/api/cssrulelist/item/index.md
> +In the following example we assume that the `myRules` list has three items only.
```suggestion
In the following example, we assume that the `myRules` list has three items only.
```

2022-12-11 07:14 UTC, sideshowbarker commented on files/en-us/web/api/cssstyledeclaration/index.md
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:15 UTC, sideshowbarker commented on files/en-us/web/api/cssstyledeclaration/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:15 UTC, sideshowbarker commented on files/en-us/web/api/domtokenlist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:16 UTC, sideshowbarker commented on files/en-us/web/api/filelist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:16 UTC, sideshowbarker commented on files/en-us/web/api/htmlcollection/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:16 UTC, sideshowbarker commented on files/en-us/web/api/htmlselectelement/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:17 UTC, sideshowbarker commented on files/en-us/web/api/medialist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:17 UTC, sideshowbarker commented on files/en-us/web/api/mimetypearray/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:17 UTC, sideshowbarker commented on files/en-us/web/api/namednodemap/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:17 UTC, sideshowbarker commented on files/en-us/web/api/nodelist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/plugin/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/pluginarray/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/speechgrammarlist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/speechrecognitionresult/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/speechrecognitionresultlist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:18 UTC, sideshowbarker commented on files/en-us/web/api/stylesheetlist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:19 UTC, sideshowbarker commented on files/en-us/web/api/touchlist/index.md
> +> **Note:** This interface is a legacy type that existed because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156)
```suggestion
> **Note:** This interface is a legacy type that exists because of a [historical accident](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only).
```

2022-12-11 07:21 UTC, sideshowbarker approved these changes

2022-12-12 10:59 UTC, Elchi3 requested changes
I think it is wrong to call these interfaces legacy:
- CSSStyleDeclaration
- DOMTokenList
- HTMLSelectElement
- MediaList
- NodeList
- SpeechGrammarList
- SpeechRecognitionResultList
- SpeechRecognitionResult

I'm also not sure if it should be called "historical accident". That seems to add unnecessary judgement.

2022-12-13 02:35 UTC, Ahmed-Hakeem commented
> I think it is wrong to call these interfaces legacy:
> 
> * CSSStyleDeclaration
> * DOMTokenList
> * HTMLSelectElement
> * MediaList
> * NodeList
> * SpeechGrammarList
> * SpeechRecognitionResultList
> * SpeechRecognitionResult
> 
> I'm also not sure if it should be called "historical accident". That seems to add unnecessary judgement.

How about 
"This interface was a [try to achieve unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and is only continues to be supported in order not to break code that's already using it. Modern APIs use types that wrap around ECMAScript array types instead, so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only)."

2022-12-13 11:16 UTC, Elchi3 commented
That sounds better. Slightly corrected version:

"This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continues to be supported to not break code that's already using it. Modern APIs use types that wrap around ECMAScript array types instead, so you can treat them like ECMAScript arrays, and at the same time impose additional semantics on their usage (such as making their items read-only)."

2022-12-14 10:28 UTC, Elchi3 commented
Thanks for the rewording. I'm still not quite sure if this note should be added to all interfaces in this PR.
I still have doubts about these:

> * CSSStyleDeclaration
> * DOMTokenList
> * HTMLSelectElement
> * MediaList
> * NodeList
> * SpeechGrammarList
> * SpeechRecognitionResultList
> * SpeechRecognitionResult

Maybe @sideshowbarker has thoughts.

2022-12-14 10:38 UTC, sideshowbarker commented
I'll take a look again

2022-12-14 12:29 UTC, sideshowbarker commented
> Thanks for the rewording. I'm still not quite sure if this note should be added to all interfaces in this PR. I still have doubts about these:
> 
> > * CSSStyleDeclaration
> > * DOMTokenList
> > * HTMLSelectElement
> > * MediaList
> > * NodeList
> > * SpeechGrammarList
> > * SpeechRecognitionResultList
> > * SpeechRecognitionResult
> 
> Maybe @sideshowbarker has thoughts.

I haven’t managed to make time to look at the relevant specs yet, but regardless I think it anyway be good to have @domenic take a look at this too

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/cssstyledeclaration/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
I think this class does too much other stuff to add this warning for. If we were defining it today, we'd separate out the other functionality from the list stuff, but since they're mixed together, I think it'd be a mistake to speak about this as legacy-ish.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/domtokenlist/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
Similarly I think this does too many additional non-Array-like things to get this note.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/htmlselectelement/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
The fact that this has indexed access is almost incidental; I think this note is strange here.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/medialist/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
It's weird to say that this is an attempt to create an unmodifiable list, when in fact it's very modifiable (via appendMedium()/deleteMedium()). It's definitely legacy though; it's just like an observable array but worse.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/namednodemap/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
Probably this one does too much to get this note.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/plugin/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
Does too much other stuff.

2022-12-17 10:19 UTC, domenic commented on files/en-us/web/api/speechgrammarlist/index.md
> +> **Note:** This interface was an [attempt to create an unmodifiable list](https://stackoverflow.com/questions/74630989/why-use-domstringlist-rather-than-an-array/74641156#74641156) and only continue
Seems borderline; unsure.

2022-12-17 16:14 UTC, Ahmed-Hakeem commented
Thanks much, @domenic  for taking time reviewing this, we can modify the note to mention that this not the only reason behind creating these interfaces, but Let's stick with removing it from these pages, and aggregating all your suggestions @Elchi3 @sideshowbarker @domenic  we will remove this note from : 

- CSSStyleDeclaration
- DOMTokenList
- HTMLSelectElement
- MediaList
- NodeList
- SpeechGrammarList
- SpeechRecognitionResult
- NamedNodeMap
- Plugin


Does this note fit SpeechRecognitionResultList?.... what do you think @Elchi3 ?

2022-12-17 16:35 UTC, Ahmed-Hakeem commented
If I got your points well we should add PluginArray to this list as well

2022-12-18 08:29 UTC, sideshowbarker commented
Thanks @domenic and thanks @Ahmed-Hakeem for your work and perseverance on this one.

@Elchi3 I believe this is ready to go now

2022-12-18 13:41 UTC, Ahmed-Hakeem commented
> Thanks @domenic and thanks @Ahmed-Hakeem for your work and perseverance on this one.
> 
> 
> 
> @Elchi3 I believe this is ready to go now

It's my pleasure ❤️

2022-12-19 10:50 UTC, Elchi3 approved these changes
Thanks everyone!

2022-12-19 10:51 UTC, merged