webextensions csp: note about AMO remote csp policy
mdn/content pull request #22982
Opened 2022-12-15 16:48 UTC by wesinator

### Description

This PR adds a note to the webextensions CSP documentation about the AMO policy which restricts remote CSP in Firefox addons (during the addons review process).
https://extensionworkshop.com/documentation/publish/add-on-policies/#development-practices
https://extensionworkshop.com/documentation/develop/build-a-secure-extension/

### Motivation

Reviewers check addons for external/remote locations in the manifest csp field, and reject if it is present. 

Adding this note in the MDN documentation makes developers aware of this policy in the docs, and may save both addon developers and reviewers time. 

### Additional details

### Related issues and pull requests

#20437

2023-05-21 23:33 UTC, rebloor requested changes
@wesinator apologies, not sure why this one slipped under my radar. I suggested one small change, as best practice for accessibility is to add links under descriptive text (not just "here").

2023-05-21 23:33 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_security_policy/index.md
> +> **Note:** If your modified CSP allows remote script injection, your extension will get rejected from addons.mozilla.org (AMO) during review. See details about security best practices [here](https:/
```suggestion
> **Note:** If your modified CSP allows remote script injection, your extension will get rejected from addons.mozilla.org (AMO) during the review. For more information, see details about [security best practices](https://extensionworkshop.com/documentation/develop/build-a-secure-extension/).
```

2023-05-24 01:43 UTC, rebloor approved these changes

2023-06-15 10:04 UTC, bsmth approved these changes
Thanks, @rebloor and @wesinator - going to merge shortly 👍🏻

2023-06-15 10:04 UTC, merged