Update content
mdn/content pull request #23026
Opened 2022-12-17 21:18 UTC by rohini-ranjanR

Removing `in-flow` and `all` values issue #23012.

### Description
Removing `in-flow` and `all` values as it was not mentioned in https://w3c.github.io/csswg-drafts/css-box-4/#margin-trim

### Motivation

### Additional details

### Related issues and pull requests

Fixes #23012

2022-12-18 01:49 UTC, Josh-Cena commented
We need the new property values here, like `block`, `inline`, etc. Right now there's only one value which doesn't make sense.

2022-12-18 22:08 UTC, rohini-ranjanR commented
Can I add these in place of `in-flow` and `all`

`block`

-  Computes to 'block-start block-end'

`inline`
- Computes to 'inline-start inline-end'

2022-12-28 19:40 UTC, wbamberg commented
> Can I add these in place of `in-flow` and `all`
> 
> `block`
> 
>     * Computes to 'block-start block-end'
> 
> 
> `inline`
> 
>     * Computes to 'inline-start inline-end'

Thank you for the update! We also need block-start, inline-start, inline-end, block-end.

You can see the alllowed values in the specification: https://w3c.github.io/csswg-drafts/css-box-4/#margin-trim.

2022-12-28 23:08 UTC, dipikabh commented
Hello @rohini-ranjanR, thank you for your contribution.

There are a couple of changes that would need to be done to really fix https://github.com/mdn/content/issues/23012:
- Remove the outdated values
- Document the new values. Ideally, the descriptions should be more explanatory than a copy&paste from the specification. 
- Update other impacted sections such as [Examples](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim#examples) to remove the outdated values and add code examples for the new values.

Please let us know if you would be interested in taking up this work.

2022-12-29 08:08 UTC, rohini-ranjanR commented
Hello, @dipikabh
Yes, I would like to work on this task.

2022-12-29 12:28 UTC, dipikabh commented
That sounds great, @rohini-ranjanR! You can push your changes/commits to this PR for this work.

Let me know if you have any questions or need any help with the documentation process.

2022-12-30 18:06 UTC, dipikabh requested changes
Thanks @rohini-ranjanR! I've left some edit comments.
I just realized that these new values are not yet implemented in any browser and this documentation is being updated ahead of its time.

2022-12-30 18:06 UTC, dipikabh commented on files/en-us/web/css/margin-trim/index.md
> +  - : Margins of last block child with the container's edge will be truncated to zero.
```suggestion
  - : Margin of last block child with the container's edge is trimmed to zero.
```

2022-12-30 18:06 UTC, dipikabh commented on files/en-us/web/css/margin-trim/index.md
> +  - : Container truncate the margins provided to the inline children where they adjoin the container's edge, without affecting spacing at the beginning and end of the       row.
```suggestion
  - : Margins provided to the inline children where they adjoin the container's edges are trimmed to zero without affecting the spacing at the beginning and end of the row.
```

2022-12-30 18:06 UTC, dipikabh commented on files/en-us/web/css/margin-trim/index.md
> +  - : Margins between the container's edge and the first inline child will be truncated to zero.
```suggestion
  - : Margin between the container's edge and the first inline child is trimmed to zero.
```

2022-12-30 18:06 UTC, dipikabh commented on files/en-us/web/css/margin-trim/index.md
> +  - : Margin between the container's edge and the last inline child will be truncated to zero.
```suggestion
  - : Margin between the container's edge and the last inline child is trimmed to zero.
```

2022-12-30 18:06 UTC, dipikabh commented on files/en-us/web/css/margin-trim/index.md
> +Similarly, to remove left margins with the container's edge:
```suggestion
Similarly, to remove left margin with the container's edge:
```

2022-12-30 20:12 UTC, rohini-ranjanR commented
I have a doubt about the line 'The margin-trim property allows the container to trim the margins of its children where they adjoin the container's edges.' code line 20 do they should be updated to 'The margin-trim property allows to trim the margins of its children where they adjoin the container's edges. '

2023-01-03 20:12 UTC, dipikabh approved these changes
Thanks for the updates, @rohini-ranjanR!

2023-01-03 20:12 UTC, merged