fix grammatical issues in what_is_accessibility
mdn/content pull request #23041
Opened 2022-12-18 16:27 UTC by yashikabhargava

### Description
fixed minor grammatical issues in what is accessibility.

2022-12-18 17:20 UTC, Josh-Cena requested changes

2022-12-18 17:20 UTC, Josh-Cena commented on files/en-us/learn/accessibility/what_is_accessibility/index.md
> +Building accessible sites benefit everyone:
Original is correct

2022-12-18 17:20 UTC, Josh-Cena commented on files/en-us/learn/accessibility/what_is_accessibility/index.md
> +- Easily understood the content, such as text written using plain-language standards.
Original is correct. "Easily understood" is a modifier for "content".

2022-12-18 17:20 UTC, Josh-Cena commented on files/en-us/learn/accessibility/what_is_accessibility/index.md
> +- Are my UI buttons accessible using the keyboard and on-touch interfaces?
Original is correct. If you find it weird to join an adverbial phrase with a prepositional phrase, consider this:

```suggestion
- Are my UI buttons accessible to both keyboard and touch interface users?
```

2022-12-19 16:52 UTC, yashikabhargava commented on files/en-us/learn/accessibility/what_is_accessibility/index.md
> +- Easily understood the content, such as text written using plain-language standards.
Yes, now I understood it. Will undo the change.

2022-12-19 16:54 UTC, yashikabhargava commented on files/en-us/learn/accessibility/what_is_accessibility/index.md
> +- Are my UI buttons accessible using the keyboard and on-touch interfaces?
Thank you for the suggestion.

2022-12-21 06:23 UTC, Josh-Cena approved these changes
Thanks

2022-12-21 06:23 UTC, merged