Sectiononpage replace
mdn/content pull request #23059
Opened 2022-12-19 12:58 UTC by bsmth

This PR removed the deprecated `SectionOnPage` macro in favor of regular markdown links with anchors.

Aside from the cleanup, fixed some anchors to point to newer section titles.

__Related issues and pull requests:__
- [x] https://github.com/mdn/yari/issues/6117#issuecomment-1348477156

2022-12-22 05:29 UTC, wbamberg commented on files/en-us/web/api/document/exitfullscreen/index.md
> +> [Examples](/en-US/docs/Web/API/Element/requestFullscreen#examples).
In many of these cases the replacement loses context, especially when the section name is something super-generic like "Examples". For example here the original was:

> Note: For a more complete example, see the [Examples](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#examples) in [Element.requestFullscreen()](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen).

...while here we get:

> Note: For a more complete example, see the [Examples](https://pr23059.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Element/requestFullscreen#examples).

2022-12-22 05:32 UTC, wbamberg requested changes
See https://github.com/mdn/content/pull/23059#pullrequestreview-1227140613 - in many cases here the new version loses context and is less useful.

I'm not sure if there is a better option than just mimicking what was there before, but I think that would be OK.

2022-12-28 10:17 UTC, bsmth commented
> In many cases here the new version loses context and is less useful. 
> I'm not sure if there is a better option than just mimicking what was there before, but I think that would be OK.

You're right, I'm happy to update the link text where appropriate in this PR if you think it's worth it.

2023-01-11 06:15 UTC, yin1999 commented
Should we use some formats like this: 

```md
[`article title` > `heading`](<url to a specific section>)
```

2023-01-11 09:54 UTC, bsmth commented
> it would be nice to have more describing text.

I'll take a look at this again shortly to improve it 👀

2023-01-11 12:38 UTC, bsmth commented
> Should we use some formats like this:
> 
> ```lisp
> [`article title` > `heading`](<url to a specific section>)
> ```

In some cases I've used `[<API>, <subheading>](<URL to section>)` based on judgement calls of the context of the content and what we use elsewhere. See https://github.com/mdn/content/pull/23059/commits/b3fd8ca9cf31f3cf97eb9c9e79f809eeacd07c9e

* `[AudioTrackList events](/en-US/docs/Web/API/AudioTrackList#events)` or
* `[<Topic>, <subheading>](<URL to section>)`

I think this is in better shape, but of course open to feedback.

2023-01-11 17:00 UTC, dipikabh requested changes
Partial review here - done with 15/130 :)

2023-01-11 17:27 UTC, dipikabh requested changes
64/130 - a lot of this bunch has links to the "Constraint exerciser" example

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/htmlimageelement/sizes/index.md
> +[Using media queries, Syntax](/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax) for
```suggestion
the [media queries syntax](/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#syntax) for
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/htmlmediaelement/load/index.md
> +[Multimedia and embedding, Video and audio content](/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#using_multiple_source_formats_to_improve_compatibility) page.
```suggestion
[Video and audio content](/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#using_multiple_source_formats_to_improve_compatibility) page.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/htmlselectelement/selectedoptions/index.md
> +- [Forms, Drop-down controls](/en-US/docs/Learn/Forms/Other_form_controls#drop-down_controls)
```suggestion
- [Drop-down controls](/en-US/docs/Learn/Forms/Other_form_controls#drop-down_controls) in forms
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/intersectionobserver/rootmargin/index.md
> +See [How intersection is calculated](/en-US/docs/Web/API/Intersection_Observer_API#how_intersection_is_calculated)
```suggestion
See [how intersection is calculated](/en-US/docs/Web/API/Intersection_Observer_API#how_intersection_is_calculated)
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/intersectionobserver/thresholds/index.md
>  learn how thresholds work.
```suggestion
Learn how [thresholds](/en-US/docs/Web/API/Intersection_Observer_API#thresholds) work.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/intersectionobserverentry/intersectionratio/index.md
> +[Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes).
```suggestion
the [Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes) section.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/intersectionobserverentry/isintersecting/index.md
> +[Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes).
```suggestion
the [Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes) section.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/intersectionobserverentry/target/index.md
> +[Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes).
```suggestion
the [Handling intersection changes](/en-US/docs/Web/API/Intersection_Observer_API/Timing_element_visibility#handling_intersection_changes) section.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/media_capture_and_streams_api/constraints/index.md
> +The last significant piece of the puzzle: code that displays, for the user's reference, a list of the constrainable properties which their browser supports. Each property is a link to its documentati
```suggestion
The last significant piece of the puzzle: code that displays, for the user's reference, a list of the constrainable properties which their browser supports. Each property is a link to its documentation on MDN for the user's convenience. See [examples](/en-US/docs/Web/API/MediaDevices/getSupportedConstraints#examples) in MediaDevices.getSupportedConstraints() for details on how this code works.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/media_capture_and_streams_api/taking_still_photos/index.md
> +- [Canvas tutorial, Using frames from a video](/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#using_frames_from_a_video)
```suggestion
- [Using frames from a video](/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#using_frames_from_a_video) in the Canvas tutorial
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediadevices/index.md
> +  - : Returns an object conforming to {{domxref("MediaTrackSupportedConstraints")}} indicating which constrainable properties are supported on the {{domxref("MediaStreamTrack")}} interface. See [Medi
```suggestion
  - : Returns an object conforming to {{domxref("MediaTrackSupportedConstraints")}} indicating which constrainable properties are supported on the {{domxref("MediaStreamTrack")}} interface. See [Media Streams API](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints) to learn more about constraints and how to use them.
```
we can link to the specific section but the display text could still be the parent page

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/autogaincontrol/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See the [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/aspectratio/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See the [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/channelcount/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See the [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/deviceid/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See the [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/displaysurface/index.md
> +See [Media Streams API, How constraints are defined](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#how_constraints_are_defined) for an explanation of how to define constraints.
```suggestion
See [how constraints are defined](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#how_constraints_are_defined).
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/echocancellation/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See the [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example.
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/framerate/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
same edit for this and the next three

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/logicalsurface/index.md
> +See [Media Streams API, How constraints are defined](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#how_constraints_are_defined) for an explanation of how to define constraints.
```suggestion
See [how constraints are defined](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#how_constraints_are_defined).
```

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/noisesuppression/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```suggestion
See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
```
same as the earlier one

2023-01-11 17:27 UTC, dipikabh commented on files/en-us/web/api/mediatrackconstraints/samplerate/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example.
same edit to be applied for all the few next ones

2023-01-11 18:33 UTC, dipikabh requested changes
That's all the files...

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/localdescription/index.md
> +See [WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) for details on this algorithm and why it's used.
```suggestion
See the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.md
> +For a more detailed example, see [Signaling and video calling, Starting negotiation](/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#starting_negotiation).
```suggestion
For a more detailed example, see the [Starting negotiation](/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#starting_negotiation) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/pendinglocaldescription/index.md
> +[WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions).
```suggestion
the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/pendingremotedescription/index.md
> +[WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions).
```suggestion
the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/remotedescription/index.md
> +[WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) for details on this algorithm and why it's used.
```suggestion
the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/restartice/index.md
> +[Lifetime of a WebRTC session, ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) and
```suggestion
the [ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) section and
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/setconfiguration/index.md
> +  In this situation, one might call `setConfiguration()` to switch to new regional ICE servers, then initiate an [Lifetime of a WebRTC session, ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lif
```suggestion
  In this situation, one might call `setConfiguration()` to switch to new regional ICE servers, then initiate an [ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart).
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/setlocaldescription/index.md
> +> [WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) for more details on this process.
```suggestion
> the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for more details on this process.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/setremotedescription/index.md
> +> [WebRTC connectivity, Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) for more details on this process.
```suggestion
> the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for more details on this process.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/signalingstate/index.md
> +See [Lifetime of a WebRTC session, Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) for more details about the signaling process.
```suggestion
See the [Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) section for more details about the process.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/rtcpeerconnection/track_event/index.md
> +By the time this event is delivered, the new track has been fully added to the peer connection. See [WebRTC API, Track event types](/en-US/docs/Web/API/RTCTrackEvent#track_event_types) for details.
```suggestion
By the time this event is delivered, the new track has been fully added to the peer connection. See the [Track event types](/en-US/docs/Web/API/RTCTrackEvent#track_event_types) section for details.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> +Before starting a project that will require sharing of audio, be sure to check the [MediaDevices.getDisplayMedia(), Browser compatibility](/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_com
```suggestion
Before starting a project that will require sharing of audio, be sure to check the [browser compatibility](/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility) to see if the browsers you wish compatibility with have support for audio in captured screen streams.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/setinterval/index.md
> +[`setTimeout`, Reasons for delays longer than specified](/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified) for examples.
```suggestion
the [Reasons for delays longer than specified](/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified) section for examples.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/webrtc_api/connectivity/index.md
> +For now, see [Lifetime of a WebRTC session, ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart).
```suggestion
Learn about the [ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) process.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/webxr_device_api/fundamentals/index.md
> +Generally, applications only define and manage the horizontal FOV. For more details, see [WebXR Device API, The optics of 3D](/en-US/docs/Web/API/WebXR_Device_API/Rendering#the_optics_of_3d).
```suggestion
Generally, applications only define and manage the horizontal FOV. For more details, see the [The optics of 3D](/en-US/docs/Web/API/WebXR_Device_API/Rendering#the_optics_of_3d) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/xrviewerpose/index.md
> +This code is derived from [WebXR Device API, Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame).
```suggestion
This code is derived from the section [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame).
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/api/xrwebgllayer/index.md
> +This snippet, taken from [WebXR Device API, Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame), shows how the `XRWebGLLayer` is obtained from the {{domxref("XR
```suggestion
This snippet, taken from the section [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame), shows how the `XRWebGLLayer` is obtained from the {{domxref("XRSession")}} object's rendering state and is then bound as the current rendering WebGL framebuffer by calling the WebGL {{domxref("WebGLRenderingContext.bindFrameBuffer", "bindFrameBuffer()")}} function.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/css/border-color/index.md
> +You can find more information about border colors in [CSS colors, Borders](/en-US/docs/Web/HTML/Applying_color#borders).
```suggestion
You can find more information about border colors in [CSS colors](/en-US/docs/Web/HTML/Applying_color#borders_2).
```
- intentionally left the display text to be the page and not the section name
- there seem to be two border links on the page. updated here to the section being referred to

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/css/css_colors/applying_color/index.md
> +  - : Configures a shadow effect to apply to text. Among the options for the shadow is the shadow's base color (which is then blurred and blended with the background based on the other parameters). S
```suggestion
  - : Configures a shadow effect to apply to text. Among the options for the shadow is the shadow's base color (which is then blurred and blended with the background based on the other parameters). See the [Text drop shadows](/en-US/docs/Learn/CSS/Styling_text/Fundamentals#text_drop_shadows) section to learn more.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/css/max-block-size/index.md
> +Any time you would normally use `max-height` or `max-width`, you should instead use `max-block-size` to set the maximum "height" of the content (even though this may not be a vertical value) and `max
```suggestion
Any time you would normally use `max-height` or `max-width`, you should instead use `max-block-size` to set the maximum "height" of the content (even though this may not be a vertical value) and `max-inline-size` to set the maximum "width" of the content (although this may instead be vertical rather than horizontal). See [writing-mode examples](/en-US/docs/Web/CSS/writing-mode#examples), which show the different writing modes in action.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/html/element/input/index.md
> +  - : (**Not** a Boolean attribute!) The [`autocomplete`](/en-US/docs/Web/HTML/Attributes/autocomplete) attribute takes as its value a space-separated string that describes what, if any, type of auto
```suggestion
  - : (**Not** a Boolean attribute!) The [`autocomplete`](/en-US/docs/Web/HTML/Attributes/autocomplete) attribute takes as its value a space-separated string that describes what, if any, type of autocomplete functionality the input should provide. A typical implementation of autocomplete recalls previous values entered in the same input field, but more complex forms of autocomplete can exist. For instance, a browser could integrate with a device's contacts list to autocomplete `email` addresses in an email input field. See [`autocomplete`](/en-US/docs/Web/HTML/Attributes/autocomplete#values) for permitted values.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/html/element/input/time/index.md
> +The `value` of the `time` input is always in 24-hour format that includes leading zeros: `hh:mm`, regardless of the input format, which is likely to be selected based on the user's locale (or by the
```suggestion
The `value` of the `time` input is always in 24-hour format that includes leading zeros: `hh:mm`, regardless of the input format, which is likely to be selected based on the user's locale (or by the user agent). If the time includes seconds (see [Using the step attribute](#using_the_step_attribute)), the format is always `hh:mm:ss`. You can learn more about the format of the time value used by this input type in the [Time strings](/en-US/docs/Web/HTML/Date_and_time_formats#time_strings) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/html/element/input/week/index.md
> +A string representing the value of the week/year entered into the input. The format of the date and time value used by this input type is described in [HTML date and time formats, Week strings](/en-U
```suggestion
A string representing the value of the week/year entered into the input. The format of the date and time value used by this input type is described in the [Week strings](/en-US/docs/Web/HTML/Date_and_time_formats#week_strings) section.
```

2023-01-11 18:33 UTC, dipikabh commented on files/en-us/web/media/formats/image_types/index.md
> +> Additionally, their use for favicons has subsided in favor of using a PNG file and the {{HTMLElement("link")}} element, as described in [Providing icons for different usage contexts](/en-US/docs/We
```suggestion
> Additionally, their use for favicons has subsided in favor of using a PNG file and the {{HTMLElement("link")}} element, as described in the section [Providing icons for different usage contexts](/en-US/docs/Web/HTML/Element/link#providing_icons_for_different_usage_contexts).
```

2023-01-12 08:13 UTC, bsmth commented on files/en-us/web/api/console/debug/index.md
> +    [Console API, Using string substitutions](/en-US/docs/Web/API/console#using_string_substitutions) for a
This one is the other way around, it's the 'Using string substitutions section' on the Console page.

2023-01-12 17:02 UTC, bsmth commented
Thanks @dipikabh - I've addressed your comments if you want to have another scan over this!

2023-01-13 01:53 UTC, dipikabh approved these changes
The updates look okay to me. Thanks!

2023-01-14 07:26 UTC, wbamberg reviewed
Lots of picky comments, feel free to accept or not, or discuss.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/localdescription/index.md
> +See the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/negotiationneeded_event/index.md
> +For a more detailed example, see the [Starting negotiation](/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#starting_negotiation) section.
```suggestion
For a more detailed example, see [Starting negotiation](/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#starting_negotiation).
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/pendinglocaldescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/pendingremotedescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/remotedescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/restartice/index.md
> +the [ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) section and
```suggestion
[ICE restart](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) and
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/setlocaldescription/index.md
> +> the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for more details on this process.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/setremotedescription/index.md
> +> the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for more details on this process.
As above.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/signalingstate/index.md
> +See the [Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) section for more details about the process.
```suggestion
See [Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) for more details about the process.
```

(Or "See \[Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) in our WebRTC session lifetime guide")

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcpeerconnection/track_event/index.md
> +By the time this event is delivered, the new track has been fully added to the peer connection. See the [Track event types](/en-US/docs/Web/API/RTCTrackEvent#track_event_types) section for details.
```suggestion
By the time this event is delivered, the new track has been fully added to the peer connection. See [Track event types](/en-US/docs/Web/API/RTCTrackEvent#track_event_types) for details.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcrtpstreamstats/index.md
> +  - : Renamed to {{domxref("RTCRtpStreamStats.kind", "kind")}} in the specification in February 2018. See [Browser Compatibility](/en-US/docs/Web/API/RTCRtpStreamStats/kind#browser_compatibility) to
I think we can just delete this whole thing. Per BCD, only Firefox supports it and they changed the name in v63.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/rtcrtpstreamstats/index.md
> +  - : Renamed to {{domxref("RTCRtpStreamStats.kind", "kind")}} in the specification in February 2018. See [Browser Compatibility](/en-US/docs/Web/API/RTCRtpStreamStats/kind#browser_compatibility) to
(I mean, delete the whole "Obsolete fields" section.

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/screen_capture_api/using_screen_capture/index.md
> +Before starting a project that will require sharing of audio, be sure to check the [browser compatibility](/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility) to see if the browse
```suggestion
Before starting a project that will require sharing of audio, be sure to check the [browser compatibility](/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility) for `getDisplayMedia()` to see if the browsers you wish compatibility with have support for audio in captured screen streams.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/setinterval/index.md
> +the [Reasons for delays longer than specified](/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified) section for examples.
```suggestion
[Reasons for delays longer than specified](/en-US/docs/Web/API/setTimeout#reasons_for_delays_longer_than_specified) for examples.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/webxr_device_api/fundamentals/index.md
> +Generally, applications only define and manage the horizontal FOV. For more details, see the [The optics of 3D](/en-US/docs/Web/API/WebXR_Device_API/Rendering#the_optics_of_3d) section.
```suggestion
Generally, applications only define and manage the horizontal FOV. For more details, see [The optics of 3D](/en-US/docs/Web/API/WebXR_Device_API/Rendering#the_optics_of_3d).
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/xrviewerpose/index.md
> +This code is derived from the section [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame).
```suggestion
This code is derived from [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame) in our "Movement and motion" WebXR example.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/xrwebgllayer/index.md
> +This snippet, taken from the section [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame), shows how the `XRWebGLLayer` is obtained from the {{domxref("XRSessio
```suggestion
This snippet, taken from [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame) in our "Movement and motion" WebXR example, shows how the `XRWebGLLayer` is obtained from the {{domxref("XRSession")}} object's rendering state and is then bound as the current rendering WebGL framebuffer by calling the WebGL {{domxref("WebGLRenderingContext.bindFrameBuffer", "bindFrameBuffer()")}} function.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/api/xrwebgllayer/index.md
> +- [WebXR Device API, Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame)
```suggestion
- [Drawing a frame](/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion#drawing_a_frame) in our "Movement and motion" WebXR example
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/css/css_colors/applying_color/index.md
> +  - : Configures a shadow effect to apply to text. Among the options for the shadow is the shadow's base color (which is then blurred and blended with the background based on the other parameters). S
```suggestion
  - : Configures a shadow effect to apply to text. Among the options for the shadow is the shadow's base color (which is then blurred and blended with the background based on the other parameters). See [Text drop shadows](/en-US/docs/Learn/CSS/Styling_text/Fundamentals#text_drop_shadows) to learn more.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/css/css_colors/applying_color/index.md
> +See [Color syntax](/en-US/docs/Web/CSS/color_value#syntax) for a list of all available color keywords.
https://developer.mozilla.org/en-US/docs/Web/CSS/named-color is a better target for this.

Although technically these are not all the _keywords_ - for example `currentcolor` is a keyword but not a named color. But this section seems anyway to be talking only about named colors, although it calls them keywords. Perhaps it would be better to rename it to "Named colors".

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/css/max-block-size/index.md
> +Any time you would normally use `max-height` or `max-width`, you should instead use `max-block-size` to set the maximum "height" of the content (even though this may not be a vertical value) and `max
```suggestion
Any time you would normally use `max-height` or `max-width`, you should instead use `max-block-size` to set the maximum "height" of the content (even though this may not be a vertical value) and `max-inline-size` to set the maximum "width" of the content (although this may instead be vertical rather than horizontal). See [`writing-mode` examples](/en-US/docs/Web/CSS/writing-mode#examples), which show the different writing modes in action.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/html/element/input/time/index.md
> +The `value` of the `time` input is always in 24-hour format that includes leading zeros: `hh:mm`, regardless of the input format, which is likely to be selected based on the user's locale (or by the
```suggestion
The `value` of the `time` input is always in 24-hour format that includes leading zeros: `hh:mm`, regardless of the input format, which is likely to be selected based on the user's locale (or by the user agent). If the time includes seconds (see [Using the step attribute](#using_the_step_attribute)), the format is always `hh:mm:ss`. You can learn more about the format of the time value used by this input type in [Time strings](/en-US/docs/Web/HTML/Date_and_time_formats#time_strings).
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/html/element/input/week/index.md
> +A string representing the value of the week/year entered into the input. The format of the date and time value used by this input type is described in the [Week strings](/en-US/docs/Web/HTML/Date_and
```suggestion
A string representing the value of the week/year entered into the input. The format of the date and time value used by this input type is described in [Week strings](/en-US/docs/Web/HTML/Date_and_time_formats#week_strings).
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/media/formats/codecs_parameter/index.md
> +          The following table lists permitted values; see [Digital video concepts, Chroma subsampling](/en-US/docs/Web/Media/Formats/Video_concepts#chroma_subsampling) for additional information abou
```suggestion
          The following table lists permitted values; see [Chroma subsampling](/en-US/docs/Web/Media/Formats/Video_concepts#chroma_subsampling) in our "Digital video concepts" guide for additional information about this topic and others.
```

2023-01-14 07:26 UTC, wbamberg commented on files/en-us/web/media/formats/image_types/index.md
> +> Additionally, their use for favicons has subsided in favor of using a PNG file and the {{HTMLElement("link")}} element, as described in the section [Providing icons for different usage contexts](/e
```suggestion
> Additionally, their use for favicons has subsided in favor of using a PNG file and the {{HTMLElement("link")}} element, as described in [Providing icons for different usage contexts](/en-US/docs/Web/HTML/Element/link#providing_icons_for_different_usage_contexts).
```

2023-01-16 15:34 UTC, bsmth commented on files/en-us/web/api/intersectionobserver/rootmargin/index.md
> +See [how intersection is calculated](/en-US/docs/Web/API/Intersection_Observer_API#how_intersection_is_calculated)
I like the suggestion

2023-01-16 15:34 UTC, bsmth commented on files/en-us/web/api/intersectionobserver/rootmargin/index.md
> +bounds. [How intersection is calculated](/en-US/docs/Web/API/Intersection_Observer_API#how_intersection_is_calculated)
```suggestion
bounds. [How intersections are calculated](/en-US/docs/Web/API/Intersection_Observer_API#how_intersection_is_calculated)
```

2023-01-16 15:37 UTC, bsmth commented on files/en-us/web/api/paymentrequest/merchantvalidation_event/index.md
> +For more information, see [Payment processing concepts, Merchant validation](/en-US/docs/Web/API/Payment_Request_API/Concepts#merchant_validation).
```suggestion
For more information, see [Merchant validation](/en-US/docs/Web/API/Payment_Request_API/Concepts#merchant_validation).
```

2023-01-16 15:37 UTC, bsmth commented on files/en-us/web/api/paymentrequest/merchantvalidation_event/index.md
> +- [Payment processing concepts, Merchant validation](/en-US/docs/Web/API/Payment_Request_API/Concepts#merchant_validation)
```suggestion
- [Merchant validation](/en-US/docs/Web/API/Payment_Request_API/Concepts#merchant_validation)
```

2023-01-16 15:39 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/currentremotedescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
```suggestion
[Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page.
```

2023-01-16 15:39 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/localdescription/index.md
> +See the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
```suggestion
See [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page for details on this algorithm and why it's used.
```

2023-01-16 15:40 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/pendinglocaldescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section.
```suggestion
[Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page.
```

2023-01-16 15:40 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/remotedescription/index.md
> +the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for details on this algorithm and why it's used.
```suggestion
[Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page for details on this algorithm and why it's used.
```

2023-01-16 15:41 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/setlocaldescription/index.md
> +> the [Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) section for more details on this process.
```suggestion
> t[Pending and current descriptions](/en-US/docs/Web/API/WebRTC_API/Connectivity#pending_and_current_descriptions) in the WebRTC Connectivity page for more details on this process.
```

2023-01-16 15:42 UTC, bsmth commented on files/en-us/web/api/rtcpeerconnection/signalingstate/index.md
> +See the [Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) section for more details about the process.
```suggestion
See [Signaling](/en-US/docs/Web/API/WebRTC_API/Session_lifetime#signaling) in our WebRTC session lifetime page.
```

2023-01-16 15:46 UTC, bsmth commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example that allows you to play with media tr
Good, I think this was a leftover

2023-01-16 15:47 UTC, bsmth commented on files/en-us/web/api/mediatrackconstraints/suppresslocalaudioplayback/index.md
> +See [Media Streams API, Example: Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) for an example that allows you to play with media tr
```suggestion
The [Constraint exerciser](/en-US/docs/Web/API/Media_Capture_and_Streams_API/Constraints#example_constraint_exerciser) example shows how to use media track constraints.
```

2023-01-16 15:58 UTC, bsmth commented on files/en-us/web/api/rtcrtpstreamstats/index.md
> +  - : Renamed to {{domxref("RTCRtpStreamStats.kind", "kind")}} in the specification in February 2018. See [Browser Compatibility](/en-US/docs/Web/API/RTCRtpStreamStats/kind#browser_compatibility) to
done in 44d482c64ccb3790ed8ae0e36526da39c2525977

2023-01-16 15:58 UTC, bsmth commented on files/en-us/web/css/css_colors/applying_color/index.md
> +See [Color syntax](/en-US/docs/Web/CSS/color_value#syntax) for a list of all available color keywords.
imoproved in 44d482c64ccb3790ed8ae0e36526da39c2525977

2023-01-16 17:27 UTC, wbamberg approved these changes
👍 thank you for your patience, @bsmth !

2023-01-16 17:27 UTC, merged

2023-01-16 17:39 UTC, bsmth commented
Thanks, all 🙌🏻