Move “Transferable objects” out of Glossary and into Web/API tree
mdn/content pull request #23109
Opened 2022-12-21 10:56 UTC by sideshowbarker

See https://github.com/mdn/content/issues/23099#issuecomment-1359834232.  If this content were to remain the Glossary, that would continue to prevent us from being able to refine it further — because, as noted, glossary entries are meant to be brief, and this content is already much too long to be appropriate for having in the Glossary.

2022-12-21 14:10 UTC, Elchi3 requested changes
hm, I think this needs a page type. Probably "guide".
It is a bit sad we have no tree for these sort of docs. I guess it is okay to move it to the top-level tree for now but I wish there was a better place.

2022-12-22 04:20 UTC, wbamberg commented
> hm, I think this needs a page type. Probably "guide". It is a bit sad we have no tree for these sort of docs. I guess it is okay to move it to the top-level tree for now but I wish there was a better place.

I do agree that the glossary entry is too long and don't have a magic solution for where this page should be, but I feel pretty strongly it should not be here. We have an IA, such as it is, and infrastructure, such as it is, that's supposed to make things navigable, and it depends on things being in particular places. In this case it expects Web/API guide to be under the "API overview" (more or less, specification) that defines the thing being discussed in the guide. That way it should get a sidebar with (in theory) related elements.

Maybe it could go under https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API, since the spec referenced there defines transferable? https://html.spec.whatwg.org/multipage/structured-data.html#transferable-objects.

2022-12-22 04:45 UTC, sideshowbarker commented
> Maybe it could go under [developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API), since the spec referenced there defines transferable? [html.spec.whatwg.org/multipage/structured-data.html#transferable-objects](https://html.spec.whatwg.org/multipage/structured-data.html#transferable-objects).

I have no strong opinion about where it should live — and would not object to somebody doing the work to integrate it into https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API as a new section.

That said, I think there’s value to having the “Transferable objects” content as a separate article on its own, the way it is now — rather than instead just being some section of another (already big) article.

> We have an IA, such as it is, and infrastructure, such as it is, that's supposed to make things navigable, and it depends on things being in particular places.

If our IA as currently designed isn’t able to elegantly accommodate cases of content like this, then it seems like one thing that should be on the table for consideration is, figuring out if there’s a way to refine the IA to fit cases like this one.

2022-12-22 05:05 UTC, wbamberg commented
> > Maybe it could go under [developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API), since the spec referenced there defines transferable? [html.spec.whatwg.org/multipage/structured-data.html#transferable-objects](https://html.spec.whatwg.org/multipage/structured-data.html#transferable-objects).
> 
> I have no strong opinion about where it should live — and would not object to somebody doing the work to integrate it into https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API as a new section.
> 
> That said, I think there’s value to having the “Transferable objects” content as a separate article on its own, the way it is now — rather than instead just being some section of another (already big) article.

I didn't mean it should be part of the https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API page, but that it should be a separate page under there, which is where we keep guides for APIs (see for example something like https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace, which is a guide page under https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/).

> > We have an IA, such as it is, and infrastructure, such as it is, that's supposed to make things navigable, and it depends on things being in particular places.
> 
> If our IA as currently designed isn’t able to elegantly accommodate cases of content like this, then it seems like one thing that should be on the table for consideration is, figuring out if there’s a way to refine the IA to fit cases like this one.

I agree! But that's a hard problem and while we are not ready for it we should work with what we have rather than degrade it further.

2022-12-22 09:12 UTC, sideshowbarker commented
> I didn't mean it should be part of the [developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API) page, but that it should be a separate page under there,

d’oh — sorry, yes, I see now you said that clearly before, but I just hadn’t read it carefully

I’ve updated the patch in this PR to move it to https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Transferable_objects

2022-12-22 22:48 UTC, wbamberg commented
Or, and this might be better, move it under https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API , since workers seem like the main place this is relevant. Note that this is also where we put https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm , which is also congruent to this page, and that the "see also" links in https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects#see_also are almost all the web worker things.

Sorry I should have thought of this sooner.

2022-12-23 03:18 UTC, sideshowbarker commented
> Or, and this might be better, move it under [developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) , since workers seem like the main place this is relevant.

Perfect — yes, agreed

Just now pushed an update which moves it to https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects

> Sorry I should have thought of this sooner

No worries — I should’ve spent more time thinking about it too (and reckon I would’ve arrived at the same realization if I’d taken the time to think more)

2022-12-28 11:31 UTC, Elchi3 approved these changes
Thank you both, Mike and Will! 👍

2022-12-28 11:31 UTC, merged

2023-01-03 00:48 UTC, hamishwillee commented
Late to the party, but this is great. I've been (un)happily extending that list in the glossary topic for a while, but not considered a better place for it. 

There really isn't a perfect location because you don't have to transfer in a worker context - as Will  noted you can use this in a structured clone in the main thread too. This is good though, because I think it is where people might find it.

@sideshowbarker Did the work get done to move this into the sidebar?

2023-01-03 02:13 UTC, sideshowbarker commented
> @sideshowbarker Did the work get done to move this into the sidebar?

No — not as far as I know, at least

2023-01-03 03:30 UTC, wbamberg commented
> @sideshowbarker Did the work get done to move this into the sidebar?
> 

No, I was going to make that a follow-up but forgot 🤦 .

Quick advertisement - if we had a `weight` front matter key we would not have to do this any more, the sidebar macro could automatically scoop up subpages and list them as guides.

2023-01-03 03:59 UTC, hamishwillee commented
> Quick advertisement - if we had a [weight front matter key](https://github.com/orgs/mdn/discussions/124) we would not have to do this any more, the sidebar macro could automatically scoop up subpages and list them as guides.

@sideshowbarker Perhaps :-). PR to add sidebar in https://github.com/mdn/content/pull/23331