Add omnibox.onDeleteSuggestion
mdn/content pull request #23136
Opened 2022-12-22 15:29 UTC by rebloor

### Description

Adds documentation for `omnibox.onDeleteSuggestion` along with some minor edits to the `omnibox` page. (BCD previously updated in  Add deletable, onDeleteSuggestion, improve accuracy of version_added [#18372](https://github.com/mdn/browser-compat-data/pull/18372)) 

### Related issues and pull requests

Addresses the documentation requirements of [Bug 1478095](https://bugzilla.mozilla.org/show_bug.cgi?id=1478095) Implement `onDeleteSuggestion`

2023-01-30 15:03 UTC, rebloor commented
@rpl are you able to review this?

2023-02-17 17:26 UTC, Rob--W requested changes
TODO:

- [ ] Document `deletable` property at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox/SuggestResult (Chrome docs: https://developer.chrome.com/docs/extensions/reference/omnibox/#property-SuggestResult-deletable, Firefox source: https://searchfox.org/mozilla-central/rev/9de332d5c8faac58dc1232b8a6383ce6cb1400f4/browser/components/extensions/schemas/omnibox.json#58-62)
- [ ] apply suggested edits from this review
- [ ]

2023-02-17 17:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/omnibox/ondeletesuggestion/index.md
> +  - : `String`. The description of the deleted suggestion.
```suggestion
  - : `string`. The description of the deleted suggestion.
```

2023-02-17 17:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/omnibox/ondeletesuggestion/index.md
> +The listener function passes one parameter: a string `text`.
```suggestion
```

2023-02-17 17:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/omnibox/ondeletesuggestion/index.md
> +  console.log(`The user deleted: ${deletedSuggestionInfo.text}`);
```suggestion
function logDeletedSuggestion(text) {
  console.log(`The user deleted: ${text}`);
```

2023-02-17 17:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/omnibox/ondeletesuggestion/index.md
> +Fired whenever the user deletes a suggestion.
```suggestion
Fired whenever the user deletes a suggestion.
A suggestion can be deleted when {{WebExtAPIRef("omnibox.SuggestResult","SuggestResult")}}`.deletable` is set to true.
```

2023-02-19 18:22 UTC, Rob--W approved these changes

2023-02-19 22:38 UTC, merged