Cookie Store API
mdn/content pull request #2316
Opened 2021-02-12 13:54 UTC by rachelandrew

Adding the Cookie Store API overview page, and the Interface for `CookieStore`.

Spec: https://wicg.github.io/cookie-store/

Reviewer @jpmedley 

Notes for review:

This is the interface I mentioned which had a lot of dictionaries. As discussed I have documented these as objects and values and not mentioned dictionaries. Let me know if this works ok.

Once I've done the other interfaces I'll come up with some examples for the overview page. I'll look at the other interfaces once you've taken a look at this one.

I have added the spec to the Yari data but it isn't showing up yet.

2021-02-12 14:28 UTC, mera-pakistani-mera-fakhat approved these changes

2021-02-17 17:45 UTC, jpmedley requested changes

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/getall/index.html
> +<p>A {{jsxref("Promise")}} that resolves with a list of cookie values for the given name or options.</p>
```suggestion
<p>A {{jsxref("Promise")}} that resolves with a list of cookies for the given name or options.</p>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/index.html
> +<p class="summary">The <strong><code>CookieStore</code></strong> interface of the {{domxref('Cookie Store API')}} provides methods for getting and setting cookies in an asynchronous fashion.</p>
```suggestion
<p class="summary">The <strong><code>CookieStore</code></strong> interface of the {{domxref('Cookie Store API')}} provides methods for getting and setting cookies asynchronously from either a page or a service worker.</p>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/index.html
> +<p>The <code>CookieStore</code> is accessed via attributes in the global scope in a {{domxref("Window")}} or {{domxref("ServiceWorkerGlobalScope")}} context, therefore there is no constructor.</p>
```suggestion
<p>The <code>CookieStore</code> is accessed via attributes in the global scope in a {{domxref("Window")}} or {{domxref("ServiceWorkerGlobalScope")}} context. Therefore there is no constructor.</p>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/index.html
> +</dl>
Copy description edits to here.

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/onchange/index.html
> +<p class="summary">The <strong><code>onchange</code></strong> EventHandler of the {{domxref("CookieStore")}} interface is an event handler that fires when a change is made to any cookie.</p>
```suggestion
<p class="summary">The <strong><code>onchange</code></strong> EventHandler of the {{domxref("CookieStore")}} interface fires when a change is made to any cookie.</p>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +<p class="summary">The <strong><code>set()</code></strong> method of the {{domxref("CookieStore")}} interface sets a cookie using a name and value or an object should more options needs to be passed.
```suggestion
<p class="summary">The <strong><code>set()</code></strong> method of the {{domxref("CookieStore")}} interface sets a cookie using a name and value or an object should more options need to be passed.</p>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +<p class="summary">The <strong><code>set()</code></strong> method of the {{domxref("CookieStore")}} interface sets a cookie using a name and value or an object should more options needs to be passed.
I edited the mistake, but this should really use whatever text you wrote on the other pages.

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +
```suggestion

 <p><code>set()</code> requires either the <code>name</code> and <code>value</code> argument or the <code>options</code> argument.</p>
 
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +      <dd>A {{domxref("DOMTimeStamp")}} containing the expiry date of the cookie.</dd>
```suggestion
      <dd>A {{domxref("DOMTimeStamp")}} containing the expiration date of the cookie.</dd>
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +          <li><code>none</code></li>
Copy the definitions here. Also, I think these might need to be in quotes.

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +      <dd>An <code>enum</code> with one of the following <a href="/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite">SameSite</a> values:
```suggestion
      <dd>One of the following <a href="/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite">SameSite</a> values:
```

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +      <dd>An <code>enum</code> with one of the following <a href="/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite">SameSite</a> values:
Enum is an IDL concept not a JavaScript concept. Please remove throughout.

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +  <dd>Thrown if the origin is classed as an opaque origin, and unable to be serialized.</dd>
>unable to be serialized

This makes it sound like someone might want to save the whole site. What does this mean?

2021-02-17 17:45 UTC, jpmedley commented on files/en-us/web/api/cookiestore/set/index.html
> +<p>Setting a cookie by passing an object with <code>name</code>, <code>value</code>, <code>expires</code>, and <code>domain</code>.</p>
```suggestion
<p>The following example sets a cookie by passing an object with <code>name</code>, <code>value</code>, <code>expires</code>, and <code>domain</code>.</p>
```

2021-02-18 07:59 UTC, rachelandrew commented on files/en-us/web/api/cookie_store_api/index.html
> +<p>The existing method of getting and setting cookies involves working with {{domxref("document.cookie")}} as a string of <code>key=value</code> pairs. In addition to this being cumbersome and error
I'd seen both and went with my choice, we were talking about revising API docs in the meeting. I'm not sure there is any kind of word list, which might be useful especially as now it is pretty easy to search and replace out the "losing" format to make things more consistent.

2021-02-18 08:01 UTC, rachelandrew commented on files/en-us/web/api/cookie_store_api/index.html
> +<p>The <code>document.cookie</code> interface is synchronous, single-threaded, and blocking. When writing a cookie you must wait for the browser to update the string of cookies. In addition, the reli
I don't quite understand this comment but it's a bit of a long sentence anyway, I'll revise it and see if it helps.

2021-02-18 08:48 UTC, rachelandrew commented on files/en-us/web/api/cookiestore/get/index.html
> +      <li><code>none</code></li>
Have done, I think the info on the SameSite page I linked to is about as succinct as it can get so have used that, but also linked to the web.dev article in a note as I think that is useful webdev additional info.

2021-02-18 09:39 UTC, rachelandrew commented on files/en-us/web/api/cookie_store_api/index.html
> +<p>The <code>document.cookie</code> interface is synchronous, single-threaded, and blocking. When writing a cookie you must wait for the browser to update the string of cookies. In addition, the reli
actually, not sure we need to mention the fact they can't block the event loop. I mean, they can't, but given they can't access document anyway it doesn't really matter.

2021-02-18 09:58 UTC, rachelandrew commented on files/en-us/web/api/cookiestore/set/index.html
> +  <dd>Thrown if the origin is classed as an opaque origin, and unable to be serialized.</dd>
Not sure how you got to "save the whole site" from serialized? I'd have thought the concept of serialization was understood by most JS developers (in fact devs of any language). If the origin can't be serialized to something sensible looking, this can't be trusted.

The classification of opaque origin is somewhat tricky to define (there is an amazing thread here of some spec authors trying to do so https://github.com/w3c/wpub/issues/321) however, as described in this thread it is really about whether the origin can be trusted, so maybe that is all that needs to be said.

2021-02-18 16:23 UTC, jpmedley approved these changes

2021-02-19 14:42 UTC, merged