Update with correct method description
mdn/content pull request #2320
Opened 2021-02-12 16:19 UTC by nicksteele

`navigator.credentials.get` does not allow for the creation of credentials, but rather the assertion of existing ones. To create a credential, one must use `navigator.credentials.create`, and creation is not possible across origins.

2021-02-15 15:38 UTC, mirunacurtean approved these changes

2021-02-16 07:32 UTC, sideshowbarker requested changes

2021-02-16 07:32 UTC, sideshowbarker commented on files/en-us/web/http/headers/feature-policy/publickey-credentials-get/index.html
> +<p><span class="seoSummary">The HTTP {{HTTPHeader("Feature-Policy")}} header <code>publickey-credentials-get</code> directive controls whether the current document is allowed to access <a href="/en-U
```suggestion
<p><span class="seoSummary">The HTTP {{HTTPHeader("Feature-Policy")}} header <code>publickey-credentials-get</code> directive controls whether the current document is allowed to access the <a href="/en-US/docs/Web/API/Web_Authentication_API">Web Authentication API</a> to retrieve public-key credentials; i.e, via {{DOMxRef("CredentialsContainer.get", "navigator.credentials.get({publicKey: ..., ...})")}}.</span></p>
```

(I realize the corrections in this suggestion are for the existing content prior to the fix you made — but we might as well fix those things too, as long as we’re already in here touching this.)

2021-02-24 03:17 UTC, sideshowbarker approved these changes

2021-02-24 03:24 UTC, merged

2021-02-24 03:25 UTC, sideshowbarker commented
Nick, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉