Restore :current pseudo class
mdn/content pull request #23242
Opened 2022-12-28 20:11 UTC by estelle

2022-12-28 20:13 UTC, estelle commented on files/en-us/web/api/console/timelog/index.md
> +None ({{jsxref("undefined")}}).
```suggestion
If no label parameter included:

```
default: 1042ms
```

If an existing `label` is included:

```
timer name: 1242ms
```
```

2023-01-03 17:38 UTC, jpmedley commented on files/en-us/web/css/_colon_current/index.md
> +The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents the element, or an ancestor of the element
```suggestion
The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents the element or an ancestor of the element, that is currently being displayed. For example in a video with captions which are being displayed by [WebVTT](/en-US/docs/Web/API/WebVTT_API).
```

2023-01-03 17:44 UTC, jpmedley requested changes, later dismissed

2023-01-03 17:44 UTC, jpmedley commented on files/en-us/web/css/_colon_current/index.md
> +The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents the element, or an ancestor of the element
The phrase 'element or an ancestor of the element' are elements in a series. Elements in a series only require commas when there are three or more. Also, 'or an ancestor of the element' is restrictive and therefore should have no comma.

(I had to dig out the grammar book on this one. Let me know if I've overlooked anything.)

2023-01-03 22:04 UTC, dipikabh commented on files/en-us/web/css/_colon_current/index.md
> +The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents the element, or an ancestor of the element
That is the correct rule for comma with conjunctions! 🙂

2023-01-03 22:12 UTC, dipikabh requested changes
A few more changes needed in addition to @jpmedley's

2023-01-03 22:12 UTC, dipikabh commented on files/en-us/web/css/_colon_current/index.md
> +The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents the element, or an ancestor of the element
```suggestion
The **`:current`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector is a time-dimensional pseudo-class that represents an element or the ancestor of an element that is currently being displayed. For example, this pseudo-class can be used to represent a video that is being displayed with captions by [WebVTT](/en-US/docs/Web/API/WebVTT_API).
```
also dropping the comma before 'that'

2023-01-05 03:40 UTC, dipikabh approved these changes
LGTM

2023-01-05 04:40 UTC, merged