Update index.md
mdn/content pull request #23264
Opened 2022-12-29 20:32 UTC by David263

See Issue #23197.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2022-12-29 20:35 UTC, David263 commented
I think I've done my part. I see a button that says "Close with comment" but I won't push it. I don't know what it means to "close", but it doesn't sound good.

2022-12-29 20:35 UTC, David263 commented
Is the pull request complete?

2022-12-29 20:36 UTC, David263 commented
Hello?

2022-12-29 20:43 UTC, Josh-Cena commented
Yes, you are all set for the PR 👍

2022-12-29 21:34 UTC, Josh-Cena commented
@David263 Unfortunately I could not get your code to work. Here's my test code:

```html
<output></output>
<script>
  function yieldForFrame() {
    return new Promise((resolve) => {
      requestAnimationFrame(resolve);
    });
  }

  async function main() {
    document.querySelector("output").innerText = "some text";
    await yieldForFrame();
    await yieldForFrame();
    alert("Pausing with screen showing 'some text'.");
  }
  main();
</script>
```

It works, but it works very inconsistently. I can almost always get it to work as intended in Firefox and Safari, but on Chrome it usually pauses with a white screen.

Also, I find the two `yieldForFrame` calls a bit hacky. I can only guess you are trying to give the browser a bit more time to repaint, but even with two calls, it doesn't work in Chrome.

2022-12-29 21:58 UTC, David263 commented
I confirm that my code doesn't work on Chrome. I found that adding one more await of yieldForFrame() works repeatably. But I am puzzled. It looks like a bug in Chrome.

As to the two awaits that are currently in my example, the first is a dummy call that does nothing. It is part of the functionality of requestAnimationFrame, which is intended to be called "for real" only from inside the callback passed to the first call to requestAnimationFrame. In other words, the hack is in the very definition of requestAnimationFrame.

But as to why it requires three calls and not two calls for Chrome, I find unexpected. We need to get expert input for this issue, as requestAnimationFrame is apparently not working the same on Chrome as on other browsers.

2023-01-03 17:58 UTC, jpmedley requested changes
Thank you for submitting this. 

I'd like @Rumyra to weigh in on this PR. The use cases you highlighted would be better served by [`requestIdleCallback()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#browser_compatibility) if not for the fact that Safari still doesn't support it. Fortunately, this can be  enabled in the 16.3 Technology Preview ([caniuse](https://caniuse.com/requestidlecallback)). Given that, I'm not crazy about adding this information now. This will be out of date very soon and in my experience it will be years before anyone thinks to remove it. It might be better to add information referring readers to `requestIdleCallback()` for such use cases.

2023-01-03 17:58 UTC, jpmedley commented on files/en-us/web/api/window/requestanimationframe/index.md
> +In this example, an async function waits for the DOM to update and the screen to repaint. Because in an event loop, all [microtasks](/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide) are always proce
```suggestion
In this example, an async function waits for the DOM to update and the screen to repaint. Because in an event loop, all [microtasks](/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide) are always processed before other tasks in queue, use `requestAnimationFrame()` to yield to the browser for a repaint before continuing with the `alert()` call, which is going to block further code execution.
```

2023-02-21 13:45 UTC, David263 commented
I've accidentally come back to this page, and I see that merging is blocked and I'm not sure what I am supposed to do, if anything. I do not understand how GitHub works (and it's not because I haven't tried to learn--it is fiendishly difficult to understand).

2023-02-21 15:36 UTC, Josh-Cena commented
It's okay—the editors are trying to get more sources on how exactly it works, because as we've noted, there's some browser inconsistency here.

2023-04-01 10:59 UTC, David263 commented
I have never quite understood GitHub. What do I do in response to the message "This pull request has merge conflicts that must be resolved before it can be merged."?

2023-04-01 17:47 UTC, teoli2003 commented
![Capture d’écran 2023-04-01 à 19 46 51](https://user-images.githubusercontent.com/1466293/229306509-e36b4740-b464-4f19-81d9-1388ed080015.png)


Press this button and correct (that is chose between the old and new version of the file)

2023-04-01 18:03 UTC, David263 commented
I responded to the error message "This pull request has merge conflicts that must be resolved before it can be merged" by doing my best to merge two alternatives into one file.

2023-04-01 18:05 UTC, David263 commented
I clicked Commit Merged. Did I do it right?

2023-04-01 18:05 UTC, David263 commented
I clicked Commit Merged. Did I do it right?

2023-04-01 18:06 UTC, teoli2003 commented
Yes, you did.

2023-10-26 12:34 UTC, bsmth commented
Hi @David263 there are some merge conflicts and review comments outstanding. Do you still intend to come back to this one?

2023-10-26 16:05 UTC, David263 commented
I thought I had completed this, sorry. The truth is that I don't understand the git or GitHub process, even though I've studied it and even taken a tutorial in it. Is it because I'm 77 years old? I did fine in my 40 year software career, even using source control systems without any problem. But somehow I can't figure out how to do pulls and pushes and stuff like that. Can someone here help:, or does GitHub itself offer technical support?

2023-12-07 10:34 UTC, closed without merging

2023-12-07 12:30 UTC, David263 commented
I don't think you misunderstood. 
requestAnimationFrame is indeed meant for use in manual animation, when CSS animation isn't enough. However, it is also the only way to force a repaint in the browser, AFAIK. For this reason, this use case should be mentioned, because it can be useful. If you know of another way to force a repaint, you might mention it. Either way, reopening this issue and doing the edit might be a good idea.