Add docs for Payment Handler API
mdn/content pull request #23270
Opened 2022-12-30 09:42 UTC by chrisdavidmills

### Description

This PR adds documentation for the [Payment Handler API](https://w3c.github.io/payment-handler/).

See my [research document](https://docs.google.com/document/d/1iwCOrpw7hSlEDlONs167VPfufd_poPe0hBbSAO6xaFQ/edit#) for details of exactly what has been done here. 

### Motivation

### Additional details

### Related issues and pull requests

2022-12-31 16:54 UTC, rsolomakhin reviewed
Great work! 👍

2023-01-02 08:59 UTC, chrisdavidmills commented on files/en-us/web/api/canmakepaymentevent/index.md
> +The **`CanMakePaymentEvent`** interface of the {{domxref("Payment Handler API", "Payment Handler API", "", "nocode")}} is the event object for the {{domxref("ServiceWorkerGlobalScope.canmakepayment_e
Ah, I get it. I've updated this (in my next commit) in all the places it is mentioned, using wording along these lines:

> ...fired on a payment app's service worker to check whether it is ready to handle a payment. Specifically, it is fired when the merchant website calls {{domxref("PaymentRequest.PaymentRequest", "new PaymentRequest()")}}.

I think I was a bit confused by this functionality because it seemed strange to me that an event is being used to trigger a check rather than an action based on a result, but I guess firing to signify that the check is required is still an action based on a result.

2023-01-02 09:03 UTC, chrisdavidmills commented on files/en-us/web/api/canmakepaymentevent/respondwith/index.md
> +  - : A {{jsxref("Promise")}} that resolves with a boolean value. At the time of writing, the value is always `true`.
Ha, updated! I've used the final snippet you suggested, Yes, we can totally use fat arrows on MDN. In fact, I'll have a look through these docs and update it where I've used the `function` keyword.

2023-01-02 09:34 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +  supportedMethods: 'https://bobpay.xyz/pay'
Yeah, makes sense. I've updated all instances.

2023-01-02 09:44 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +The `supportedMethods` property specifies one or more URLs representing the payment methods supported by the merchant.
Gotcha, I've updated the text, and added this in as an additional example.

2023-01-02 10:07 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +In supporting browsers, the Payment Request API starts off the process of installing payment apps that can use the payment methods by requesting a [payment method manifest](TBD) file from each URL. T
Ah ha, thanks for the clarification here. I was getting a bit confused by when exactly the payment app is installed. In my next commit, I've made the change suggested above, but I've also made some significant changes to the rest of the explanation, to explain this whole part of the process a bit more clearly. Please can you have anoither read of this section and let me know if it works?

2023-01-02 10:18 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +A payment method manifest should be called `payment-manifest.json`, and be structured like this:
Cool, this text is useful, so I've added it in (with a little tweaking).

I've also made it clear that you are not tied to that exact name for the manifest.

2023-01-02 10:39 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +- `supported_origins` tells the browser where to find other payment apps that it is permitted to use to handle the BobPay payment if needed.
I made those changes, but I also thought it would be good to add another sentence clarifying how the browser uses the supported origins. I ended up with this:

> - `supported_origins` tells the browser what other payment apps are permitted to handle the BobBucks payment if needed. If they are already installed on the device, they will be presented to the user as alternative payment options alongside the default application.

Does that work?

2023-01-02 10:43 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +From that manifest, the browser gets the URL of the [web app manifest](/en-US/docs/Web/Manifest) of the supported payment app, which should be called `manifest.json` and look something like this:
I've updated it so that it is clear that they can be called whatever you like.

2023-01-02 10:46 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +- {{domxref("PaymentManager.userHint")}} is used to provide a hint for the browser to display along with the payment app's name and icon in the Payment Handler UI.
Noted. We'll keep an eye on this; I'm happy to update the docs when required.

2023-01-02 11:03 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +- {{domxref("PaymentManager.enableDelegations()")}} is used to delegate responsibility for providing various parts of the required payment information to the payment app rather than collecting it fro
I've made the change to the paragraph, similar to suggested, but I think on the `enableDelegations()` page it might be good to walk through an actual example, like you have done above. However, I need a bit more info here — where do you pass `enableShipping: true` into the API? I couldn't find mention of that on existing MDN docs, or in the Payment Request/Handler specs.

2023-01-02 11:03 UTC, chrisdavidmills commented on files/en-us/web/api/paymentmanager/enabledelegations/index.md
> +The **`enableDelegations()`** method of the {{domxref("PaymentManager")}} interface delegates responsibility for providing various parts of the required payment information to the payment app rather
Yup, fixed this one as well.

2023-01-02 11:04 UTC, chrisdavidmills commented on files/en-us/web/api/paymentmanager/index.md
> +  - : Delegates responsibility for providing various parts of the required payment information to the payment app rather than collecting it from within the merchant website.
There were only those three mentions. I've fixed them all up.

2023-01-03 14:28 UTC, rsolomakhin commented on files/en-us/web/api/payment_handler_api/index.md
> +- `supported_origins` tells the browser where to find other payment apps that it is permitted to use to handle the BobPay payment if needed.
Yes, that's perfect! 👍

2023-01-03 14:36 UTC, rsolomakhin commented on files/en-us/web/api/payment_handler_api/index.md
> +- {{domxref("PaymentManager.enableDelegations()")}} is used to delegate responsibility for providing various parts of the required payment information to the payment app rather than collecting it fro
I'm so sorry about the confusion! That was my fault. I should've written **`requestShipping: true`** instead.

The `requestShipping: true` is passed into the 3rd parameter of the `new PaymentRequest()` constructor, like so:

```js
new PaymentRequest(methods, details, {requestShipping: true});
```

The `requestShipping: true` option will be placed back into the spec in [the pull request to re-enable shipping address](https://github.com/w3c/payment-request/pull/996/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R465).

2023-01-03 14:54 UTC, rsolomakhin reviewed
Great work! 👍 

LGTM from my perspective, although I do not hold permissions for the "Approve" button.

2023-01-03 14:54 UTC, rsolomakhin commented on files/en-us/web/api/payment_handler_api/index.md
> +The Payment Handler API adds an additional mechanism to prepare for handling a payment. The {{domxref("ServiceWorkerGlobalScope.canmakepayment_event", "canmakepayment")}} event is fired on a payment
Perfection! 👩‍🍳

2023-01-03 14:54 UTC, rsolomakhin commented on files/en-us/web/api/payment_handler_api/index.md
> +This starts the payment flow, which causes the browser to Just-In-Time (JIT) install the web app, registering the service worker specified in [`serviceworker`](/en-US/docs/Web/Manifest/serviceworker)
This text can be confusing when trying to understand the timing of when the browser shows the UI or launches an app, because it first talks about browser-provided UI and next goes into details of `PaymentRequest.show()`.  However, it is `PaymentRequest.show()` that triggers showing any UI. The browser does not show any UI before `PaymentRequest.show()` is called.

It may be easier to understand if `PaymentRequest.show()` is mentioned first.

Here is a possible rephrasing. Please feel free to change it any way that you feel fit.

```suggestion
When the {{domxref("PaymentRequest.show()")}} method is invoked by the merchant app in response to a user gesture, the browser uses the information found in each manifest to present the payment apps to the user in the browser-provided Payment Request UI ([`name`](/en-US/docs/Web/Manifest/name), [`icons`](/en-US/docs/Web/Manifest/icons)).

If there are multiple payment app options, a list of options is presented to the user for them to choose one. Selecting one payment app will start the payment flow, which causes the browser to Just-In-Time (JIT) install the web app if necessary, registering the service worker specified in [`serviceworker`](/en-US/docs/Web/Manifest/serviceworker) so it can handle the payment.

If there is only one payment app option, the {{domxref("PaymentRequest.show()")}} method will launch this payment app, JIT-installing it if necessary. (This is an optimization to avoid presenting the user with a list that contains only one payment app choice.)
```

2023-01-03 19:00 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +- {{domxref("PaymentManager.enableDelegations()")}} is used to delegate responsibility for providing various parts of the required payment information to the payment app rather than collecting it fro
No worries! We still have `requestShipping` documented on MDN, so this makes sense. I've added an example explanation to the `enableDelegations()` page, and I think it reads pretty well.

2023-01-03 19:00 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +The Payment Handler API adds an additional mechanism to prepare for handling a payment. The {{domxref("ServiceWorkerGlobalScope.canmakepayment_event", "canmakepayment")}} event is fired on a payment
w00t!

2023-01-03 19:08 UTC, chrisdavidmills commented on files/en-us/web/api/payment_handler_api/index.md
> +This starts the payment flow, which causes the browser to Just-In-Time (JIT) install the web app, registering the service worker specified in [`serviceworker`](/en-US/docs/Web/Manifest/serviceworker)
Makes sense, thanks. I think we've nailed this now. I mostly used your text with a few tweaks.

2023-01-03 19:13 UTC, chrisdavidmills commented
@sideshowbarker hi Mike! I've had this one pretty thoroughly tech reviewed. Do you think you can take a quick look and marge it if you are happy if you get the time? I appreciate you are probably scrambling in the new year.

2023-01-04 02:46 UTC, sideshowbarker requested changes

2023-01-04 02:46 UTC, sideshowbarker commented on files/en-us/web/api/payment_handler_api/index.md
> +When the {{domxref("PaymentRequest.show()")}} method is invoked by the merchant app in response to a user gesture, the browser uses the information found in each manifest to present the payment apps
```suggestion
When the {{domxref("PaymentRequest.show()")}} method is invoked by the merchant app in response to a user gesture, the browser uses the [`name`](/en-US/docs/Web/Manifest/name) and [`icons`](/en-US/docs/Web/Manifest/icons information found in each manifest to present the payment apps to the user in the browser-provided Payment Request UI ).
```

2023-01-04 02:46 UTC, sideshowbarker commented on files/en-us/web/api/payment_handler_api/index.md
> +The promise returned by `respondWith()` resolves with a boolean to signal that it is ready to handle a payment request (`true`), or not (`false`).
```suggestion
The promise returned by `respondWith()` resolves with a boolean to signal that it is ready to handle a payment request: (`true`), or not (`false`).
```

2023-01-04 02:46 UTC, sideshowbarker commented on files/en-us/web/api/payment_handler_api/index.md
> +  - : Fired on a payment app's {{domxref("ServiceWorkerGlobalScope")}} when it has been successfully registered to signal that it is ready to handle payments.
```suggestion
  - : Fired on a payment app's {{domxref("ServiceWorkerGlobalScope")}} when it has been successfully registered, to signal that it is ready to handle payments.
```

2023-01-04 02:46 UTC, sideshowbarker commented on files/en-us/web/manifest/serviceworker/index.md
> +          <li><code>false</code>: The HTTP cache will not be used for the main script or its imports. All service worker script resources will be updated from the network. Equivalent to <code>updateV
```suggestion
          <li><code>true</code>: The HTTP cache will be queried for imports, but the main script will always be updated from the network. If no fresh entry is found in the HTTP cache for the imports, they're fetched from the network. Equivalent to <code>updateViaCache: imports</code>.</li>
          <li><code>false</code>: The HTTP cache will not be used for the main script or its imports. All service worker script resources will be updated from the network. Equivalent to <code>updateViaCache: none</code>.</li>
```

2023-01-04 02:50 UTC, sideshowbarker approved these changes

2023-01-04 02:55 UTC, merged