Document COEP:credentialless
mdn/content pull request #23344
Opened 2023-01-03 12:21 UTC by ArthurSonzogni

### Description

This PR adds documentation for `Cross-Origin-Embedder-Policy`: `credentialless` value.

### Motivation

This is part of the HTML specification + FETCH.
It is implemented by:
- Chrome: 96.
- Firefox: Nightly + origin trial.

### Additional details

In a follow-up, I am also going to fix the [Iframe.credentialless](https://github.com/mdn/content/pull/23097) documentation. I need refer to COEP:credentialless.

### Related issues and pull requests

Chrome status:
- https://chromestatus.com/feature/4918234241302528

Firefox status:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1731778

Past PR about COEP:
- https://github.com/mdn/content/pull/8871
- https://github.com/mdn/content/pull/23275

2023-01-03 12:51 UTC, ArthurSonzogni commented
This is mainly about adding this paragraph:


> ![image](https://user-images.githubusercontent.com/4759106/210360247-67bc019d-a497-4add-8c7b-fd31f2a3d8b1.png)

+ @sefeng211 / @smaug----  who implemented/reviewed COEP:credentialless: FYI. If needed, please let me know if this PR should wait for COEP credentialless to be enabled by default, or if you have comments.

+ @chrisdavidmills FYI.

2023-01-03 17:46 UTC, chrisdavidmills reviewed
@ArthurSonzogni looking pretty good from an editorial perspective, thanks! Just a few small review comments.

2023-01-03 17:46 UTC, chrisdavidmills commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
>  You can only access certain features like {{jsxref("SharedArrayBuffer")}} objects or {{domxref("Performance.now()")}} with unthrottled timers, if your document has a COEP header with the value `requi
Update this line to mention `credentialless` too?

```suggestion
You can only access certain features like {{jsxref("SharedArrayBuffer")}} objects or {{domxref("Performance.now()")}} with unthrottled timers, if your document has a COEP header with a value of `require-corp` or `credentialless` set.
```

2023-01-04 08:54 UTC, ArthurSonzogni commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +### Avoiding COEP:require-corp blockage with CORS
Agreed,  I removed it, and tweak the message below in:
https://github.com/mdn/content/pull/23344/commits/f954d6cadeed4b7fb4964d7e6cfe93eb2fa427f5

2023-01-04 10:17 UTC, chrisdavidmills commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +### Avoiding COEP:require-corp blockage with CORS
Looking good.

2023-01-04 11:54 UTC, Elchi3 requested changes

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/api/performance/measureuseragentspecificmemory/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
This is meant to be a real code example and not a syntax box 
"require-corp | credentialless" is not real code.

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/api/performance/now/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Same here

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/api/window/postmessage/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Same here

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +Cross-Origin-Embedder-Policy: unsafe-none | require-corp | credentialless
This is a syntax box. It is fine here.

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
"require-corp | credentialless" shouldn't be here. Decide for one of them.

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/http/headers/cross-origin-opener-policy/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Same

2023-01-04 11:54 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/sharedarraybuffer/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Same

2023-01-04 12:07 UTC, ArthurSonzogni commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +Cross-Origin-Embedder-Policy: unsafe-none | require-corp | credentialless
ACK

2023-01-04 12:10 UTC, chrisdavidmills commented on files/en-us/web/api/performance/measureuseragentspecificmemory/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Apologies; I should have called that out, I wasn't sure if it was real syntax or not.

2023-01-04 12:13 UTC, ArthurSonzogni commented on files/en-us/web/api/performance/measureuseragentspecificmemory/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Thanks! Done.

2023-01-04 12:13 UTC, ArthurSonzogni commented on files/en-us/web/api/performance/now/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Done.

2023-01-04 12:13 UTC, ArthurSonzogni commented on files/en-us/web/api/window/postmessage/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Done

2023-01-04 12:13 UTC, ArthurSonzogni commented on files/en-us/web/http/headers/cross-origin-opener-policy/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Done.

2023-01-04 12:13 UTC, ArthurSonzogni commented on files/en-us/web/http/headers/cross-origin-embedder-policy/index.md
> +Cross-Origin-Embedder-Policy: require-corp | credentialless
Done.

2023-01-04 12:22 UTC, Elchi3 approved these changes
Thanks! 👍

2023-01-04 12:22 UTC, merged