Add docs for AudioContext.setSinkId and friends
mdn/content pull request #23352
Opened 2023-01-03 17:08 UTC by chrisdavidmills

### Description

This PR adds documentation for `AudioContext.setSinkId()` and friends.

See my [research document](https://docs.google.com/document/d/14O9z_Tg_75nt80vublPHAXdk6n7yHsukmvDE4-xHIGE/edit#) for exact details on what has been done.

### Motivation

### Additional details

### Related issues and pull requests

2023-01-03 20:26 UTC, jpmedley requested changes, later dismissed
Chris,

Happy new year! I hope everything's good in your world.

This looks pretty good. There are a few typos, but I also made a few suggestions where you can say the same thing with fewer words.

2023-01-03 20:26 UTC, jpmedley commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +In our [SetSinkId test example](https://set-sink-id.glitch.me/), we create a simple audio graph that generates a three-second burst of white noise via an {{domxref("AudioBufferSourceNode")}}, which w
```suggestion
In our [SetSinkId test example](https://set-sink-id.glitch.me/), we create a simple audio graph that generates a three-second burst of white noise via an {{domxref("AudioBufferSourceNode")}}, which we also run through a {{domxref("GainNode")}} to quiet things down a bit. We also provide the user with a dropdown menu to allow them to change the audio output device.
```

2023-01-03 20:26 UTC, jpmedley commented on files/en-us/web/api/audiosinkinfo/index.md
> +If a new {{domxref("AudioContext")}} is created with a `sinkId` value provided of `{ type: 'none' }`, calling {{domxref("AudioContext.sinkId")}} later in the code will return a `AudioSinkInfo` object
```suggestion
If a new {{domxref("AudioContext")}} is created with a `sinkId` value of `{ type: 'none' }`, calling {{domxref("AudioContext.sinkId")}} later in the code will return a `AudioSinkInfo` object containing `type: 'none'`. This is currently the only value available.
```

2023-01-04 06:30 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +In addition, this feature may be blocked by a [`speaker-selection`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/speaker-selection) [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy) se
Not a `<meta>` tag, but they can be set in the `<iframe>` `allow` attribute. I'll update this to link to the general Permissions Policy page that covers both methods, and not just talk about "on your server"

2023-01-04 06:32 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  - : If the sink ID is set as a string value (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} contructor option
I'm not committing this one; here I'm talking about a specific option that can be used in a constructor, not the whole constructor.

2023-01-04 06:32 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  - : If the sink ID is set as an options object (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} contructor opt
Same here

2023-01-04 06:41 UTC, chrisdavidmills commented
Happy new year to you too @jpmedley ! I'm all good and I hope you are too. Thanks for the review!

2023-01-04 07:52 UTC, beaufortfrancois reviewed
Thank your for starting documenting this feature @chrisdavidmills!

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +To use this method, the user must grant `'speaker-selection'` permission via the [Permissions API](/en-US/docs/Web/API/Permissions_API), or via a {{domxref("MediaDevices.getUserMedia()")}} call.
As you can see in https://wpt.fyi/results/permissions/all-permissions.html?label=experimental&label=master&aligned, the `"speaker-selection"` permission is not implemented by any browser for now. Therefore I'd remove this and simply say that you get more audio outputs available when the user grants access to the microphone via `getUserMedia()`. WDYT?

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +In addition, this feature may be blocked by a [`speaker-selection`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/speaker-selection) [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy).
I'm not sure about this either.

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +  - : Thrown if the browser does not have the `speaker-selection` permission granted, as discussed in the article introduction above.
I think* it should be reworded to avoid using the `speaker-selection`.

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
We may want to stop all tracks after.
Note that `video: true` is not necessary as well.

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     devices.forEach((device) => {
Using `devices.filter(...)` may be clearer. Your call.

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     select.addEventListener('change', async () => {
Nit: You don't need `async` if you don't `await`.

2023-01-04 07:52 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  } else if(typeof audioCtx.sinkId === 'object') {
This may not be future proof. How about checking it's an object, its key "type", and its value "none" to assume it is not playing?

2023-01-04 08:53 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +To use this method, the user must grant `'speaker-selection'` permission via the [Permissions API](/en-US/docs/Web/API/Permissions_API), or via a {{domxref("MediaDevices.getUserMedia()")}} call.
Ah, good call. I thought about this a bit, and ended up updating it to:

> To use this method, the developer needs access to audio device information. If required, the user can be prompted to grant the required permission via a {{domxref("MediaDevices.getUserMedia()")}} call.

You might need it for it to work, full stop - when I tried it, I got no device info returned at all without granting the permission. I don't think this needs more specific explanation here, as I explain how to do it below.

2023-01-04 08:54 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +In addition, this feature may be blocked by a [`speaker-selection`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/speaker-selection) [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy).
It is only supported in Firefox at the moment, but I thought this was a good statement for future-proofing. I do say "may".

2023-01-04 08:56 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +  - : Thrown if the browser does not have the `speaker-selection` permission granted, as discussed in the article introduction above.
Good call. I've updated it to 

> Thrown if the browser does not have permission to access audio devices.

2023-01-04 09:37 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
Ah, of course — we're only concerned with audio here! Will update.

2023-01-04 09:56 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     devices.forEach((device) => {
Yeah, I think it is clearer to separate the filtering from the looping. In my code, I've ended up with

```
const audioOutputs = devices.filter(
   (device) => device.kind === 'audiooutput' && device.deviceId !== 'default'
);
  
audioOutputs.forEach((device) => {
  const option = document.createElement('option')
  option.value = device.deviceId;
  option.textContent = device.label;
  select.appendChild(option);
});
```

2023-01-04 10:02 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     select.addEventListener('change', async () => {
Ah yeah, but I think it would be better to instead put the `await` keywords in here, so that it is more obvious we are dealing with async code, so that's what I've done. If we removed `async`, it might make people forget that `setSinkId()` returns a Promise.

2023-01-04 10:12 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  } else if(typeof audioCtx.sinkId === 'object') {
You've got a good point here. I changed the `else if` clause to `typeof audioCtx.sinkId === 'object' && audioCtx.sinkId.type === 'none'`

2023-01-05 09:38 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +To use this method, the user must grant `'speaker-selection'` permission via the [Permissions API](/en-US/docs/Web/API/Permissions_API), or via a {{domxref("MediaDevices.getUserMedia()")}} call.
What do you think "To set the audio output device to a device different than the default one" instead of "To use this method"? Something, that would say that setSinkId **can** be used but it requires getUserMedia to get access to sink ids that are not `""`.

2023-01-05 09:42 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +In addition, this feature may be blocked by a [`speaker-selection`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/speaker-selection) [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy).
Oh you're right in Firefox! The permission policy is there. Not the permission ;(

2023-01-05 09:43 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     select.addEventListener('change', async () => {
Yep!

2023-01-05 09:43 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
How about stopping tracks?

2023-01-07 12:04 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +To use this method, the user must grant `'speaker-selection'` permission via the [Permissions API](/en-US/docs/Web/API/Permissions_API), or via a {{domxref("MediaDevices.getUserMedia()")}} call.
Yeah, I think this makes sense. Updated in my next commit.

2023-01-09 07:22 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
I've tried adding this to my code, and it seems to work fine:

```
const stream = await navigator.mediaDevices.getUserMedia({ audio: true });

...

// Stop audio track, as we don't need it running now the permission has been granted
const audioTracks = await stream.getAudioTracks();
audioTracks.forEach(track => track.stop());
```

Is this what you meant?

2023-01-09 07:31 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
Yes. Except `getAudioTracks()` is not returning a promise. 
You can do 
```js
stream.getAudioTracks().forEach((track) => track.stop());
```

2023-01-09 07:44 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +     await navigator.mediaDevices.getUserMedia({audio: true, video: true});
Ah, I misread the docs on that one! Perfect, this is more compact too, and still pretty readable. Updated in the code.

2023-01-09 15:23 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +       selectDiv.innerHTML = '';
I think it is still needed — my idea here is that if the user decides to press the "Get media devices" button again (maybe they have new audio output devices available and want to make them available in the dropdown), it removes the existing select element and builds a new one. Without that line, you can end up with loads of dropdowns. It's quick and dirty, but it works.

2023-01-09 15:33 UTC, chrisdavidmills commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +       selectDiv.innerHTML = '';
OK, sorry, I understand you now ;-) I'm going to leave it in, because it is only one line, and I think removing it might cause more confusion than it avoids. Usually on MDN, when lines are missed out the style is to put in some suspension dots and space, along the lines of 

```

// ...

```

Which would take more space than just leaving it in.

2023-01-10 12:29 UTC, beaufortfrancois commented on files/en-us/web/api/audiocontext/setsinkid/index.md
> +       selectDiv.innerHTML = '';
No problem! This PR looks good to me. Hopefully it will be merged soon so that I can link to it from https://github.com/GoogleChrome/developer.chrome.com/pull/4833

2023-01-11 07:32 UTC, beaufortfrancois commented
QQ: @chrisdavidmills Can we add a link to https://developer.chrome.com/blog/audiocontext-setsinkid/?

2023-01-11 07:58 UTC, chrisdavidmills commented
> QQ: @chrisdavidmills Can we add a link to https://developer.chrome.com/blog/audiocontext-setsinkid/?

Yes. I'll do that later on this morning.

2023-01-17 23:21 UTC, jpmedley commented
@beaufortfrancois Is your review done?

2023-01-18 05:46 UTC, beaufortfrancois commented
Yes

2023-01-23 07:39 UTC, chrisdavidmills commented
@sideshowbarker same with this one ;-)

2023-01-23 08:15 UTC, teoli2003 requested changes
I have a few (minor) corrections, I would like to see addressed. I think this is almost good to be merged.

2023-01-23 08:15 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/audiocontext/index.md
> +          - : An object representing different options for a sink ID. Currently this takes a single property, `type`, with a value of `none`. Setting this parameter causes the audio to be processed w
I would like to avoid using spec-only names,  here `AudioSinkOptions`. I think this is better:

```suggestion
    - `sinkId` {{optional_inline}} {{Experimental_Inline}}
      - : Specifies the sink ID of the audio output device to use for the `AudioContext`. This can take one of the following value types:
        - A string representing the sink ID, retrieved for example via the `deviceId` property of the {{domxref("MediaDeviceInfo")}} objects returned by {{domxref("MediaDevices.enumerateDevices()")}}.
        - An object representing different options for a sink ID. Currently, this takes a single property, `type`, with a value of `none`. Setting this parameter causes the audio to be processed without being played through any audio output device.
```

2023-01-23 08:15 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/sinkchange_event/index.md
> +  if(typeof audioCtx.sinkId === 'object' && audioCtx.sinkId.type === 'none') {
NIT
```suggestion
  if (typeof audioCtx.sinkId === 'object' && audioCtx.sinkId.type === 'none') {
```

2023-01-23 08:15 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +- {{domxref("AudioSinkInfo")}} object
I think this is slightly better (I didn't agree on the meaning of three here, as these are not enumerated values)

```suggestion
This property returns one of the following values, depending on how the sink ID was set:

- An empty string
  - : If a sink ID has not explicitly been set, the default system audio output device will be used, and `sinkId` will return an empty string.
- A string
  - : If the sink ID is set as a string value (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} contructor option), `sinkId` will return that same string value.
- An {{domxref("AudioSinkInfo")}} object
```

2023-01-23 08:15 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  }
NIT
```suggestion
  if (audioCtx.sinkId === '') {
    console.log('Audio playing on default device');
  } else if (typeof audioCtx.sinkId === 'object' && audioCtx.sinkId.type === 'none') {
    console.log('Audio not playing on any device');
  } else {
    console.log(`Audio playing on device ${ audioCtx.sinkId }`);
  }
```

2023-01-23 10:14 UTC, chrisdavidmills commented
Thanks @teoli2003. I agreed with your changes and committed them all.

2023-01-23 10:44 UTC, teoli2003 approved these changes

2023-01-23 12:57 UTC, chrisdavidmills commented
@jpmedley this one still says you are requesting changes, but I think I answered all your comments. Can you approve to clear it?

2023-01-25 06:42 UTC, chrisdavidmills commented
@teoli2003 are you able to merge this one, now you've approved it?

2023-01-25 06:51 UTC, teoli2003 approved these changes
I found two typos.

2023-01-25 06:51 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  - : If the sink ID is set as a string value (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} contructor option
```suggestion
  - : If the sink ID is set as a string value (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} constructor option), `sinkId` will return that same string value.
```

2023-01-25 06:51 UTC, teoli2003 commented on files/en-us/web/api/audiocontext/sinkid/index.md
> +  - : If the sink ID is set as an options object (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} contructor opt
```suggestion
  - : If the sink ID is set as an options object (using {{domxref("AudioContext.setSinkId", "setSinkId()")}}, or the `sinkId` {{domxref("AudioContext.AudioContext", "AudioContext()")}} constructor option), `sinkId` will return an {{domxref("AudioSinkInfo")}} object reflecting the same values set in the initial options object.
```

2023-01-25 06:52 UTC, merged

2023-01-25 07:49 UTC, chrisdavidmills commented
Super, cheers @teoli2003 !