Fix Iframe.Credentialless documentation.
mdn/content pull request #23351
Opened 2023-01-03 14:22 UTC by ArthurSonzogni

### Description

I would like to apply some minor edit to the original PR introducing `Iframe.credentialless`:
https://github.com/mdn/content/pull/23097/files
@chrisdavidmills kindly offered me reviewing his original document and PR, but I missed it, being on vacation during Christmas.

### Motivation
- Previously, the document explained `This context does not have access to the parent context's shared storage and credentials`. This might be a bit misleading, because in the context of an iframe, the parent often refers to the document embedded in the iframe. It is unrelated here.  It would be better to explain the document don't have access to the network/cookies/storage partition associated with the document's origin.
- In a few location, make it clear the new context is local to the top-level document.
- Add a references to `COEP:credentialless`.

### Additional details
- https://wicg.github.io/anonymous-iframe/

### Related issues and pull requests
- https://github.com/mdn/content/pull/23097/files

2023-01-03 14:24 UTC, ArthurSonzogni commented
@chrisdavidmills and @sideshowbarker. What do you think of this?

2023-01-03 18:10 UTC, chrisdavidmills reviewed
A few language nitpicks from me, but mostly looking good. Thanks @ArthurSonzogni !

2023-01-03 18:10 UTC, chrisdavidmills commented on files/en-us/web/api/window/credentialless/index.md
> +This context doesn't not have access to its network, cookies, and storage data associated with its origin. It uses a new context local to the top-level document lifetime. In return, the {{httpheader(
```suggestion
This context doesn't have access to the network, cookies, and storage data associated with its origin. It uses a new context local to the top-level document lifetime. In return, the {{httpheader("Cross-Origin-Embedder-Policy")}} (COEP) embedding rules can be lifted, so documents with COEP set can embed third-party documents that do not.
```

2023-01-03 18:10 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +  - : Set to `true` to make the `<iframe>` credentialless, meaning that its content will be loaded in a new, ephemeral context. It doesn't not have access to the network, cookies and storage data ass
```suggestion
  - : Set to `true` to make the `<iframe>` credentialless, meaning that its content will be loaded in a new, ephemeral context. It doesn't have access to the network, cookies, and storage data associated with its origin. It uses a new context local to the top-level document lifetime. In return, the {{httpheader("Cross-Origin-Embedder-Policy")}} (COEP) embedding rules can be lifted, so documents with COEP set can embed third-party documents that do not. See [IFrame credentialless](/en-US/docs/Web/Security/IFrame_credentialless) for more details.
```

2023-01-04 01:45 UTC, sideshowbarker requested changes

2023-01-04 01:45 UTC, sideshowbarker commented on files/en-us/web/api/htmliframeelement/credentialless/index.md
> +Those contexts do not have access to their network, cookies and storage data associated with their origin. Instead, they use new ones, local to the top-level document lifetime. It means any data stor
```suggestion
Those contexts do not have access to their network, cookies and storage data associated with their origin. Instead, they use new ones, local to the top-level document lifetime. It means any data stored won't be accessible anymore after the user navigates away from the page or reloads it.
```

2023-01-04 01:45 UTC, sideshowbarker commented on files/en-us/web/api/htmliframeelement/credentialless/index.md
> +In return the {{httpheader("Cross-Origin-Embedder-Policy")}} (COEP) embedding rules can be lifted, so documents with COEP set can embed third-party documents that do not. See [IFrame credentialless](
```suggestion
In return, the {{httpheader("Cross-Origin-Embedder-Policy")}} (COEP) embedding rules can be lifted, so documents with COEP set can embed third-party documents that do not. See [IFrame credentialless](/en-US/docs/Web/Security/IFrame_credentialless) for a deeper explanation.
```

2023-01-04 01:45 UTC, sideshowbarker commented on files/en-us/web/security/iframe_credentialless/index.md
> +This results in the documents inside the credentialless `<iframe>` being loaded using new, ephemeral contexts — those contexts don't have access to the data associated with their origins, for example
```suggestion
This results in the documents inside the credentialless `<iframe>` being loaded using new, ephemeral contexts — those contexts don't have access to the data associated with their origins; for example [cookies](/en-US/docs/Web/HTTP/Cookies) and [localStorage](/en-US/docs/Web/API/Window/localStorage). The credentialless storage is partitioned out separately with storage keys modified by a nonce ("number used once") value, set once per top-level document. So a cookie set in one credentialless `<iframe>` will be accessible only from other same-origin credentialless `<iframe>`s embedded below the same top-level document.
```

2023-01-04 01:46 UTC, sideshowbarker approved these changes

2023-01-04 01:48 UTC, merged

2023-01-04 01:49 UTC, sideshowbarker commented
Arthur, nice work on this update, and congrats on landing your first direct docs change here — welcome aboard 🎉

2023-01-04 08:57 UTC, ArthurSonzogni commented
Thank you!

2023-02-11 07:35 UTC, noman-land commented on files/en-us/web/security/index.md
> +  - : Iframe credentialless provides a mechanism for developers to load third-party resources in {{htmlelement("iframe")}}s using a new, ephemeral context. This context doesn't have access to the net
Hello, I came across this documentation and this bit confused me. I believe there may be a typo here:

"and storage data associated with **is** origin"

Perhaps this should be "with **its** origin"?

2023-02-11 08:52 UTC, sideshowbarker commented on files/en-us/web/security/index.md
> +  - : Iframe credentialless provides a mechanism for developers to load third-party resources in {{htmlelement("iframe")}}s using a new, ephemeral context. This context doesn't have access to the net
@noman-land 

> "and storage data associated with **is** origin"
> 
> Perhaps this should be "with **its** origin"?

Yes — thanks much for catching that.

Can you create a PR with that fix? If not, that’s fine — I could create a PR for it myself, if you’d prefer.

2023-02-11 15:58 UTC, noman-land commented on files/en-us/web/security/index.md
> +  - : Iframe credentialless provides a mechanism for developers to load third-party resources in {{htmlelement("iframe")}}s using a new, ephemeral context. This context doesn't have access to the net
Will do today!

2023-02-13 00:13 UTC, noman-land commented on files/en-us/web/security/index.md
> +  - : Iframe credentialless provides a mechanism for developers to load third-party resources in {{htmlelement("iframe")}}s using a new, ephemeral context. This context doesn't have access to the net
Submitted PR here: https://github.com/mdn/content/pull/24371