docs(CSS): Move out src docs from dl to sub-doc
mdn/content pull request #23375
Opened 2023-01-04 12:00 UTC by bsmth

Opening as draft to get early feedback on the changes.

__Changes:__
The content of the dl for `src` under files/en-us/web/css/@font-face/index.md was too extensive and should be moved out into the sub-document for readability.

Alongside this, the `src` page has some potential improvements to examples and prose.

Fixes #23341

2023-01-04 20:07 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +src: local("some font"); /* Quoted name containing space */
do you want to make it single quote so people know they can do both?

2023-01-04 20:08 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +src: url(path/to/font.otf) tech(color-SVG);
if tech() isn't understood, does it fail? 
Suggestions: make the fontfile slightly different so users know these are difference files. 
```suggestion
src: url(path/to/fontCOLRv1.otf) tech(color-COLRv1);
src: url(path/to/fontCOLRsvg.otf) tech(color-SVG);
```
as an example

2023-01-04 20:16 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +  - : Specifies an external reference consisting of a {{cssxref("&lt;url&gt;")}}, followed by optional hints using the `format()` and `tech()` component values that specify the format and font techno
```suggestion
  - : Specifies an external reference consisting of a {{cssxref("&lt;url&gt;")}}, followed by optional hints using the `format()` and `tech()` component values that specify the format and font technology of the resource referenced by the URL. The `format()` and `tech()` components are a comma-separated list of strings of known [font formats](#font_formats) and technologies. If a user agent doesn't support the font technology or formats, it skips downloading the font resource. If no format or technology hints are supplied, the font resource is always downloaded.
```

2023-01-04 21:29 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +    If omitted, the browser will always download the resource and then detect the format.
```suggestion
    If omitted, the browser will download the resource and then detect the format.
```

It won't download if it already downloaded one it groks.

2023-01-04 21:36 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +    Possible values are described in [Font formats](#font-formats).
is this "possible" or "current" or other? basically, is the table below a definitive list, a current definitive list, or just the ones we know about?

2023-01-04 21:37 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +  - : An optional declaration that follows the `url()` value that provides a hint for the user agent on the font technology.
```suggestion
  - : An optional declaration that follows the `url()` value that provides a hint for the user agent on the [font technology](#font_technologies).
```

2023-01-04 21:38 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +    Quoting the font name is optional.
case sensitive?

2023-01-04 21:41 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +If multiple `src` descriptors are set, only the last declared rule that is able to load a resource is applied.
This is important. It means that the browser may download multiple font files even if there is a local file on the device, and that the local version may not be used if the last src doesn't include a local. Should we give advice about this line?

2023-01-04 21:42 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +> Some browsers will ignore the whole descriptor if any item is invalid, even if only one item is invalid.
is this still true, or was this an old IE thing?

2023-01-04 21:44 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +The following table shows the valid values and their corresponding font formats.
```suggestion
The following table shows the valid font keywords and their corresponding font formats.
```

2023-01-04 21:49 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +> **Note:** `format(svg)` stands for [SVG fonts](/en-US/docs/Web/SVG/Tutorial/SVG_fonts), and `tech(color-SVG)` stands for [OpenType fonts with SVG table](https://learn.microsoft.com/en-us/typography
Suggestion: put this not above this table, below the previous table that it relates to.

2023-01-04 21:52 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +| Keyword             | Description                                                                                   |
Is there a resource we can link to explaining this stuff in more detail, either here or in the see also?

2023-01-04 21:57 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +  font-weight: bold;
```suggestion
p.bold {
  font-weight: bold;
```

2023-01-04 21:59 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +}
```suggestion
/* Font-family is inherited, but bold fonts are used: */
p.bold {
  font-weight: bold;
}
```

2023-01-04 22:00 UTC, estelle commented on files/en-us/web/css/@font-face/src/index.md
> +    url('FuturaMedium.woff') format("woff"),
do you want to include using a #subsection of a font?

2023-01-04 22:02 UTC, estelle reviewed
I added some questions and suggestions. I hope it helps.

2023-01-05 23:01 UTC, hamishwillee commented on files/en-us/web/css/@font-face/src/index.md
> +src: url(path/to/font.otf) tech(color-SVG);
@estelle Just dropping by ...

> if tech() isn't understood, does it fail?

If `tech()` or anything else is not understood then the spec requires that the particular item in the list is dropped, but the rest of the items are parsed. So in theory it shouldn't _fail_ but instead select the next item in the list. 
But earlier versions of most browsers will fail the whole line - the version at which things start to work properly is captured in the BCD Line: "Drop invalid item (not src string)".

For this reason, even though the spec would like just one `src` with all options, you probably have to have multiple src lines with the full src-in-one-line as the last declaration (because the last valid src is the one that gets used). Tried to capture this in https://github.com/mdn/content/pull/23085

This is covered in the note in the description shown below. @bsmth I wonder if we can reference the BCD in the note. Leaving with you.

> Note: Values within descriptors that the browser considers invalid are ignored. Some browsers will ignore the whole descriptor if any item is invalid, even if only one item is invalid. This may affect design of fallbacks.

2023-01-06 03:50 UTC, dipikabh requested changes
Thanks for taking up this chore! I have just a few quick suggestions for now.

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +    Possible values are described in [Font formats](#font-formats).
```suggestion
    Possible values are described in the [Font formats](#font_formats) section below.
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +    Quoting the font name is optional.
```suggestion
    Enclosing the font name in quotes is optional.
```
Enclosing or specifying

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +If the font file is a container for multiple fonts, a fragment identifier is included to indicate which sub-font should be used:
```suggestion
If the font file is a container for multiple fonts, a fragment identifier is included to indicate the sub-font that should be used, as shown below:
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +To check if a font technology is supported by a browser within CSS, use the {{cssxref("@supports", "@supports")}} rule.
```suggestion
To check if a font technology is supported by a browser within CSS, use the {{cssxref("@supports", "@supports")}} at-rule.
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +The first is a regular font face, and the second is a bold version of the same font family.
```suggestion
The example below shows how to define two font faces with the same font family. The `font-family` is named `MainText`. The first font face has a regular font, and the second one is a bold version of the same font family.
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
>  /* a regular font face: */
```suggestion
/* Defining a regular font face */
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +/* Defining a different bold font face for the same family: */
```suggestion
/* Defining a different bold font face for the same family */
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +/* using the regular font face: */
```suggestion
/* Using the regular font face */
```

2023-01-06 03:50 UTC, dipikabh commented on files/en-us/web/css/@font-face/src/index.md
> +/* using the bold font face: */
```suggestion
/* Using the bold font face */
```

2023-01-06 11:22 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +src: local("some font"); /* Quoted name containing space */
Good idea

2023-01-06 13:10 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +If multiple `src` descriptors are set, only the last declared rule that is able to load a resource is applied.
Good, added in 1de84f2e274257db9147e273c1cd8f90eb991100

2023-01-06 13:10 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +> **Note:** `format(svg)` stands for [SVG fonts](/en-US/docs/Web/SVG/Tutorial/SVG_fonts), and `tech(color-SVG)` stands for [OpenType fonts with SVG table](https://learn.microsoft.com/en-us/typography
done in 1de84f2e274257db9147e273c1cd8f90eb991100

2023-01-06 13:10 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +    url('FuturaMedium.woff') format("woff"),
done in 1de84f2e274257db9147e273c1cd8f90eb991100

2023-01-06 13:11 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +> Some browsers will ignore the whole descriptor if any item is invalid, even if only one item is invalid.
See Hamish's comment in https://github.com/mdn/content/pull/23375#discussion_r1062967018

2023-01-06 13:12 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +src: local("some font"); /* Quoted name containing space */
added in 1de84f2e274257db9147e273c1cd8f90eb991100, but I think Prettier will revert this if we let it run over this page again

2023-01-10 10:50 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +| Keyword             | Description                                                                                   |
I can't find anything nice and concise that covers all of these ([the spec](https://www.w3.org/TR/css-fonts-4/#font-tech-definitions) btw).

2023-01-10 13:50 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +    Quoting the font name is optional.
It follows [the usual matching algorithm](https://w3c.github.io/csswg-drafts/css-fonts-3/#font-family-casing) for `<font-face-name>` which is not case sensitive. I can add this to the bullet if that helps

2023-01-11 06:34 UTC, estelle approved these changes

2023-01-11 13:50 UTC, bsmth commented on files/en-us/web/css/@font-face/src/index.md
> +    Possible values are described in [Font formats](#font-formats).
This is a current definitive list, so only these values are possible (and likely not to change any time soon).

2023-01-11 15:57 UTC, dipikabh approved these changes
Great work, thank you @bsmth.

2023-01-11 15:57 UTC, merged

2023-01-11 15:58 UTC, bsmth commented
Thanks @dipikabh and @estelle 🙌🏻