Scroll snap: see also sections
mdn/content pull request #23391
Opened 2023-01-05 03:07 UTC by estelle

2023-01-05 03:19 UTC, estelle commented on files/en-us/web/css/scroll-snap-type-x/index.md
> +
```suggestion
```

2023-01-07 02:09 UTC, dipikabh requested changes
Thanks, @estelle! Suggested a few edits.

2023-01-07 02:09 UTC, dipikabh commented on files/en-us/glossary/snap_positions/index.md
> +Defining snap positions on the scroll container was introduced in the [CSS Scroll Snap specification](/en-US/docs/Web/CSS/CSS_Scroll_Snap).
```suggestion

```
Added this to previous para

2023-01-07 04:23 UTC, estelle commented on files/en-us/web/css/scroll-snap-type-y/index.md
> +> **Note:** The CSS [scroll-snap-type](/en-US/docs/Web/CSS/scroll-snap-type) is the modern specification that defines this functionality.
I prefer to leave it where it is. there are two large red boxes above line 19. I think that area is too busy, and the note will be more likely to be read if it is in the main reading area.

2023-01-09 20:35 UTC, dipikabh approved these changes
Looks good. Thanks for the updates, @estelle!

2023-01-09 20:37 UTC, dipikabh commented
Markdownlint is complaining about:
"Warning: files/en-us/glossary/snap_positions/index.md:12 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]

2023-01-10 01:36 UTC, merged