docs(CSS): Anchor elements are not referring to '<a>' but to the anchoring element
mdn/content pull request #23416
Opened 2023-01-05 16:47 UTC by bsmth

We had some changes land recently that pointed to anchor elements (`<a>`) where the docs are actually referring to "relative-selector-anchor-elements" -> https://drafts.csswg.org/selectors/#relative-selector-anchor-elements

From the spec:

| CSS | Description|
|---|---|
| `E:has(rs1, rs2)` | an E element, 					if there exists an element that matches 					either of the relative selectors rs1 or rs2, 					when evaluated with E as the anchor elements

Fixes #22917

2023-01-05 22:08 UTC, estelle commented on files/en-us/web/css/css_selectors/index.md
> +  - : A selector that represents an element relative to one or more [anchor elements](/en-US/docs/Web/CSS/Pseudo-classes) (the element that a pseudo-class is attached to) preceded by a combinator. Re
Good catch. However, this isn't a good definition. Let me marinate on a good suggestion (it's not coming to me at the moment). Please don't merge as is.

2023-01-05 22:13 UTC, estelle commented on files/en-us/web/css/css_selectors/index.md
> +  - : A selector that represents an element relative to one or more [anchor elements](/en-US/docs/Web/CSS/Pseudo-classes) (the element that a pseudo-class is attached to) preceded by a combinator. Re
```suggestion
  - : A selector representing an element relative to one or more anchor elements preceded by a combinator. Relative selectors that don't begin with an explicit [combinator](#combinators) have an implied [descendant combinator](/en-US/docs/Web/CSS/Descendant_combinator).
```

Let's start with this, then add a glossary for` anchor` element perhaps. The /en-US/docs/Web/CSS/Pseudo-classes defines it well, but that's not a good link here (user has to search the entire page to find what they're looking for), and a relative selector doesn't need to include a pseudoclass, so meh.

2023-01-05 22:16 UTC, estelle commented on files/en-us/web/css/css_selectors/index.md
> +    **Examples:** `+ div#topic > #reference {...}`, `> .icon {...}`, `dt:has(+ img) {...}`
```suggestion
    **Examples:** `+ div#topic > #reference {...}`, `> .icon {...}`, `dt:has(+ img) ~ dd {...}`
```

2023-01-05 22:18 UTC, estelle requested changes
Good catch. Let's revert the changes. I think it's better to not add a link if it's not a link directly to the definition

2023-01-06 09:04 UTC, bsmth commented on files/en-us/web/css/css_selectors/index.md
> +  - : A selector that represents an element relative to one or more [anchor elements](/en-US/docs/Web/CSS/Pseudo-classes) (the element that a pseudo-class is attached to) preceded by a combinator. Re
Good idea

> add a glossary for anchor element perhaps

Should we do this in this PR or a follow-up?

2023-01-06 10:31 UTC, bsmth commented
Thanks @estelle, incorporated your suggestions 👍🏻

2023-01-07 19:21 UTC, estelle approved these changes

2023-01-07 19:21 UTC, merged