Snaphome
mdn/content pull request #23428
Opened 2023-01-06 05:33 UTC by estelle

## Deprecated module page:

* Added [Deprecated inline](https://github.com/mdn/content/commit/32b49ce39e5298ee31ed574d50f1b5472d02c3cd) to deprecated properties (only one isn't deprecated)

## Current module page

* [Added glossary section](https://github.com/mdn/content/commit/d12713ba0dc9d383e24da8b5f1b92153db1f4277)
* [Removed BCD](https://github.com/mdn/content/commit/d12713ba0dc9d383e24da8b5f1b92153db1f4277) as other module overviews don't have a note about BCD
* [added see also](https://github.com/mdn/content/commit/66e3d4cf7a801791e63c556639a2422fc251e353) with external links 
* [Reorganized spec landing page](https://github.com/mdn/content/commit/ee3b95750fabb2a4efba7176bf7380734d9a49d3)

 ## Guide 

* [expand guide and add gotchas](https://github.com/mdn/content/commit/31bcabbf2dfc38c87b65cf95b62ea0e9eeda6a8a)
* Added two important notes

2023-01-10 05:00 UTC, dipikabh requested changes
Thanks for these updates, @estelle. I've suggested some edits for your consideration.

2023-01-10 20:18 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/index.md
> +The {{cssxref("scroll-snap-align")}} property is set on every child of the scroll container, defining each child's snap position or lack thereof. The {{cssxref("scroll-snap-stop")}} property enables
i tried doing a happy medium. Just enough to explain why someone would want to click on the links in the page, but not enough to replace a guide. Our interop 2022 listed improving the description on this page as a task. https://github.com/openwebdocs/project/issues/137 - the "scroll snap landing page needs better content" part. This PR addresses that..

2023-01-11 03:36 UTC, dipikabh commented on files/en-us/web/css/css_scroll_snap/index.md
> +The {{cssxref("scroll-snap-align")}} property is set on every child of the scroll container, defining each child's snap position or lack thereof. The {{cssxref("scroll-snap-stop")}} property enables
The scroll snap landing page does have a link to the page that explains the "Basic concepts". If only we had a template we could refer/point to 🙂

2023-01-11 03:37 UTC, dipikabh approved these changes

2023-01-11 03:37 UTC, merged