added level #2  HTML
mdn/content pull request #23438
Opened 2023-01-06 17:16 UTC by zuzexx

### Description

I added a few more level 2 divs, in order to better illustrate the example.

### Motivation

The example is more understandable, based on the description above the code.

### Related issues and pull requests

#23274

2023-01-06 22:36 UTC, dipikabh requested changes
Hello @zuzexx, the author in the issue is referring to the list in the [Description](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_context_example_3#description) section, under the sentence "To better understand the situation, here is the stacking context hierarchy:". This list contains the three dots for illustration purposes.

Even if you try to improve the code snippets, I believe the list with three dots, which is causing the confusion, still exists.

Could you make corresponding updates to the list to remove the three dots and also to match your new example?

2023-01-06 23:10 UTC, zuzexx commented
I can do the changes. Just that I understand correctly, you want me to change the three dots between level 2 divs to the appropriate amount of divs so that it reflects the new example?

2023-01-10 05:05 UTC, dipikabh commented
> I can do the changes. Just that I understand correctly, you want me to change the three dots between level 2 divs to the appropriate amount of divs so that it reflects the new example?

Yes, that's correct!

2023-01-10 05:19 UTC, dipikabh requested changes
Perhaps, we don't need to remove the ellipsis. We can clarify the use of ellipsis in the description.

How about updating the following line as:

line 28: "To better understand the situation, the following example illustrates the stacking context hierarchy (the three dots "..." represent multiple repetition of the previous line):

2023-01-10 05:19 UTC, dipikabh commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +    - LEVEL #2 (`z-index`: 1)
```suggestion

```
let's keep the ellipsis

2023-01-10 05:19 UTC, dipikabh commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +  - LEVEL #1
```suggestion

```
let's keep the ellipsis

2023-01-10 05:37 UTC, zuzexx commented on files/en-us/web/css/css_positioning/understanding_z_index/stacking_context_example_3/index.md
> +  - LEVEL #1
Ok, thank you for clarification. I will get to it once I come home.

2023-01-11 03:41 UTC, dipikabh approved these changes
Thank you, @zuzexx! 👍

2023-01-11 03:41 UTC, merged