Eliminate white space counted as message length
mdn/content pull request #23451
Opened 2023-01-07 07:47 UTC by guest271314

When separators=(',', ':') is not passed to json.dumps() parameter the length for input from JavaScript (which is serialized to a JSON-like format by the application) port.postMessage(new Array(174763)); is read in Python as

1048578

which is greater than 1024*1024. Essentially space character formatting were being encoded as part of the length of the JSON.

When the length should be 

873816

when formatting space characters are excluded from the JSON.

Solved by passing separators=(',', ':') for “compact encoding” json — JSON encoder and decoder — Python 3.11.1 documentation.

Now we can write 1MB with

port.postMessage(new Array(209715));

from JavaScript and omit including and counting formatting space characters as part of encoded message length.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-07 19:37 UTC, Josh-Cena requested changes, later dismissed

2023-01-07 19:37 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    encodedContent = json.dumps(messageContent, separators=(',', ':')).encode('utf-8')
```suggestion
    encoded_content = json.dumps(message_content, separators=(',', ':')).encode('utf-8')
```

2023-01-07 19:47 UTC, guest271314 commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    encodedContent = json.dumps(messageContent, separators=(',', ':')).encode('utf-8')
Updated.

2023-01-07 19:55 UTC, Josh-Cena commented
Could you update the examples repo PR as well?

2023-01-07 20:00 UTC, guest271314 commented
> Could you update the examples repo PR as well?

We're working that out now https://github.com/mdn/webextensions-examples/pull/510. Not sure what the hesitancy is. The script in its current form is not so clearly, yet still broken. Feel free provide your feedback there too.

2023-01-07 20:04 UTC, Josh-Cena commented
The motivation is convincing and the code is also clear. I don't have enough domain knowledge to review it, but everything LGTM at a glance from an engineering perspective.

2023-01-11 18:22 UTC, Rob--W requested changes
Please address the issue below together with the feedback in https://github.com/mdn/webextensions-examples/pull/510.

2023-01-11 18:22 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    encoded_content = json.dumps(message_content, separators=(',', ':')).encode('utf-8')
This is probably a copy-paste error, `.encode('utf-8')` should be omitted from the Python 2 version of the code snippet (it should be kept in the Python 3 version).

2023-01-12 00:10 UTC, guest271314 commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    encoded_content = json.dumps(message_content, separators=(',', ':')).encode('utf-8')
> This is probably a copy-paste error, `.encode('utf-8')` should be omitted from the Python 2 version of the code snippet (it should be kept in the Python 3 version).



I think this is an opportune occasion to address the fact that Python 2 is deprecated https://github.com/mdn/webextensions-examples/pull/490 and `python` is not found on some Linux distributions https://github.com/mdn/webextensions-examples/issues/506#issuecomment-1369453081. We have to explicitly use `python3` or install a package to link `python` to `python3`. 

```
$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```

2023-01-12 14:41 UTC, guest271314 commented
@Rob--W Kindly review the changes made.

2023-01-12 18:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    # We want the most compact representation because the browser rejects # messages that exceed 1 MB.
```suggestion
    # We want the most compact representation because the browser rejects
    # messages that exceed 1 MB.
```

2023-01-12 18:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    # Python 3.x version
Remove these two lines and unindent.

2023-01-12 18:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> -# than text, mode.
Keep this comment. This is useful information. This should actually have been part of the example on webextensions-examples. I'd approve a new PR that adds it.

2023-01-12 18:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md
> +    encoded_content = json.dumps(message_content, separators=(',', ':')).encode('utf-8')
For clarity we could change the shebang from `python` to `python2` where python2 is used.

On some Linux/macOS distros the default Python interpreter if any is Python 3. Python 2 has been sunset 3 years ago...

2023-01-13 15:29 UTC, Rob--W requested changes
Some of the requested changes from my previous review haven't been made yet.

2023-01-14 16:15 UTC, guest271314 commented
@Rob--W Did I miss any of your requested changes?

2023-01-14 19:19 UTC, Rob--W approved these changes
Looks good, thanks. For consistency I'd also use `/usr/bin/env -S python2 -u`, but that's a pre-existing issue.

2023-01-14 19:26 UTC, guest271314 commented
> Looks good, thanks. For consistency I'd also use `/usr/bin/env -S python2 -u`, but that's a pre-existing issue.

Yes, that would be optimal to avoid ambiguity. Why are we even still deploying examples using `python2` when Python 2.X is officially deprecated per Python?

2023-01-14 19:30 UTC, guest271314 commented
> Looks good, thanks. For consistency I'd also use `/usr/bin/env -S python2 -u`, but that's a pre-existing issue.

Updated.

2023-01-14 19:58 UTC, merged