Update array sort mention sort stability
mdn/content pull request #2345
Opened 2021-02-14 13:29 UTC by jadjoubran

Closes mdn/content#2299

2021-02-16 07:16 UTC, sideshowbarker requested changes
I don’t think the explanation and example added in this patch are sufficient for helping web developers understand what stable sorting is. I suggest giving this one another try, with the goal of producing something more like https://v8.dev/features/stable-sort.

A particular problem with this patch as currently written is that it describes the sorting behavior as relating to *“objects that compare equal”* and that the objects *“compare equally because they have the same rating”*. 

That’s confusing language because it sounds like what we’re saying is, the objects themselves are equal to each other somehow — which of course they’re not.

It seems like rather than referring to objects at all, it would be better to refer to what the objects represent — the way that in https://v8.dev/features/stable-sort, each object represents a different dog, and each dog has a name and rating.

That way we could stick to language like “sorting the dogs based on their rating”, and talk about “dogs that have the same rating”.

And for the example, it also seems kind of necessary to have an array of more than just two items — and to have two views of how it gets sorted, the way that the https://v8.dev/features/stable-sort example does: first based on name, and then based on rating.

Otherwise, without a bigger and more complex array, and without “before sorting” view and at least one “after sorting” view, it’ll not be clear to readers what the difference is between stable and unstable sorting.

Specifically, the thing that makes https://v8.dev/features/stable-sort really clear is the contrast between the “unstable” example where it shows Ghost appearing in the sorted array before Choco, and the “stable” example where i shows Ghost appearing in the sorted array after Choco.

2021-02-24 03:19 UTC, sideshowbarker commented
@jadjoubran Please let us know if you plan on getting back to update this

2021-02-24 07:26 UTC, jadjoubran commented
Hey @sideshowbarker, sorry for not replying earlier.
Yes I do plan on fixing it, it's on my todo list, waiting for some free time to be able to rewrite it

2021-03-07 14:34 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +<pre class="brush: js notranslate">
Nitpick: the `notranslate` can be removed because it will be added automatically on build.

2021-03-07 15:21 UTC, Ryuno-Ki requested changes
Some small tweaks and then it looks okay from my perspective.

2021-03-07 15:21 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +var students = [
We switched to using `let` or `const` instead of `var` when possible.
Can you replace `var` with `const` here and move the line up (to be on the same line as `<pre class="brush: js">`?

Otherwise, the rendered markup will show an empty line at the beginning.

2021-03-08 02:12 UTC, sideshowbarker requested changes

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +This means that objects that compare equal, will appear in the same order before and after sorting. For example, say you had a list of students alongside their grades. Note that the list of students
The “objects that compare equal” language here needs to be replaced — for the reason I stated in my earlier review comment at https://github.com/mdn/content/pull/2345#pullrequestreview-590936105:

> A particular problem with this patch as currently written is that it describes the sorting behavior as relating to *“objects that compare equal”* and that the objects *“compare equally because they have the same rating”*. 
>
> That’s confusing language because it sounds like what we’re saying is, the objects themselves are equal to each other somehow — which of course they’re not.
> 
> It seems like rather than referring to objects at all, it would be better to refer to what the objects represent — the way that in https://v8.dev/features/stable-sort, each object represents a different dog, and each dog has a name and rating.
>
> That way we could stick to language like “sorting the dogs based on their rating”, and talk about “dogs that have the same rating”.

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +	{ name: "Devlin", grade: 15 },
```suggestion
  { name: "Alex",   grade: 15 },
  { name: "Devlin", grade: 15 },
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +	{ name: "Devlin", grade: 15 }, // original maintained for similar grade (stable sorting)
```suggestion
  { name: "Alex",   grade: 15 }, // original maintained for similar grade (stable sorting)
  { name: "Devlin", grade: 15 }, // original maintained for similar grade (stable sorting)
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +Since version 10 (or EcmaScript 2019), the <a href="https://tc39.es/ecma262/#sec-array.prototype.sort">specification</a> dictates that <code>Array.prototype.sort</code> is stable.<br />
Please use `<p>…</p>` tags to mark up paragraphs.

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +After sorting this array by <code>grade</code> in ascending order:
```suggestion
<p>After sorting this array by <code>grade</code> in ascending order:</p>
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +<code>students</code> will have the following value:
```suggestion
…<code>students</code> will then have the following value:  
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +It's important to note that students that have the same grade (for example, Alex and Devlin), will remain in the same order as before calling the sort. This is what a stable sorting algorithm guarant
```suggestion
<p>It's important to note that students that have the same grade (for example, Alex and Devlin), will remain in the same order as before calling the sort. This is what a stable sorting algorithm guarantees.</p>
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +Before version 10 (or EcmaScript 2019), sort stabiliy was not guaranteed, meaning that you could end up with the following:
```suggestion
<p>Before version 10 (or EcmaScript 2019), sort stabiliy was not guaranteed, meaning that you could end up with the following:</p>
```

2021-03-08 02:12 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +	{ name: "Alex",   grade: 15 }, // original order not maintained
```suggestion
  { name: "Devlin", grade: 15 }, // original order not maintained
  { name: "Alex",   grade: 15 }, // original order not maintained
```

2021-03-08 08:02 UTC, jadjoubran commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +Since version 10 (or EcmaScript 2019), the <a href="https://tc39.es/ecma262/#sec-array.prototype.sort">specification</a> dictates that <code>Array.prototype.sort</code> is stable.<br />
Makes sense, I'm used to writing markdown which is why I forgot

2021-03-08 08:07 UTC, jadjoubran commented
Thanks for the review!

2021-03-08 08:52 UTC, jadjoubran commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +This means that objects that compare equal, will appear in the same order before and after sorting. For example, say you had a list of students alongside their grades. Note that the list of students
I removed it because I could not find another way of explaining it without presenting the example first, let me know if you have other ideas

2021-03-16 05:16 UTC, sideshowbarker approved these changes

2021-03-16 05:25 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.html
> +This means that objects that compare equal, will appear in the same order before and after sorting. For example, say you had a list of students alongside their grades. Note that the list of students
> I removed it because I could not find another way of explaining it without presenting the example first, let me know if you have other ideas

Thanks, yeah — I think that part wasn’t strictly necessary, and the text reads fine now without it

2021-03-16 05:26 UTC, sideshowbarker commented
@Ryuno-Ki — this is now just waiting on your re-review and approval

2021-04-07 06:54 UTC, jadjoubran commented
Hey @Ryuno-Ki, kind reminder if it's possible to check this one. Thanks!

2021-04-20 19:34 UTC, Ryuno-Ki approved these changes
Looks great!

I'm sorry for the delay. Let's get this in!

2021-04-20 19:34 UTC, merged

2021-04-20 19:35 UTC, Ryuno-Ki commented
@jadjoubran Thank you for your contribution!