Fix typos
mdn/content pull request #23480
Opened 2023-01-09 03:07 UTC by OnkarRuikar

2023-01-09 06:45 UTC, Josh-Cena requested changes
Some other changes work on texts that are already grammatically correct, but I don't have strong opinions about changing them.

2023-01-09 06:45 UTC, Josh-Cena commented on files/en-us/learn/javascript/client-side_web_apis/fetching_data/index.md
> +- Fewer data is downloaded on each update, meaning less wasted bandwidth. This may not be such a big issue on a desktop on a broadband connection, but it's a major issue on mobile devices and in coun
"Fewer" is for countable nouns. If you believe "data" is plural in this context then it should be "fewer data _are_", but I don't think "less data is" is incorrect anyway.

2023-01-09 06:45 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
> +You could also try using ESLint and Prettier too — try deliberately removing a load of the whitespace from one of your files and try Prettier on it to clean it up, or introduce a syntax error into on
```suggestion
You could also try using ESLint and Prettier too — try deliberately removing a load of the whitespace from one of your files and running Prettier on it to clean it up, or introduce a syntax error into one of your JavaScript files and see what errors ESLint gives you when you try to use Parcel to build it again.
```

2023-01-09 07:00 UTC, OnkarRuikar commented on files/en-us/learn/javascript/client-side_web_apis/fetching_data/index.md
> +- Fewer data is downloaded on each update, meaning less wasted bandwidth. This may not be such a big issue on a desktop on a broadband connection, but it's a major issue on mobile devices and in coun
It's [weird how such technical terms evolve](https://en.wikipedia.org/wiki/Data_(word)#Usage_in_English). Considering https://developers.google.com/style/word-list#data I am reverting the change.
```suggestion
- Less data is downloaded on each update, meaning less wasted bandwidth. This may not be such a big issue on a desktop on a broadband connection, but it's a major issue on mobile devices and in countries that don't have ubiquitous fast internet service.
```

2023-01-09 07:38 UTC, OnkarRuikar commented
`inside of` - https://english.stackexchange.com/a/61931

`some of the` - https://ell.stackexchange.com/a/64630
`of the` would be correct iff we mention the items in the discussion. If don't mention the specific items in the discussion then only `some` is sufficient.

2023-01-13 00:41 UTC, dipikabh commented
As requested by @bsmth, looking at this now

2023-01-13 00:45 UTC, dipikabh requested changes
Just a tiny nit, @OnkarRuikar. All other changes look good.

2023-01-13 00:45 UTC, dipikabh commented on files/en-us/web/accessibility/aria/roles/feed_role/index.md
> +A `feed` is a type of [`list`](/en-US/docs/Web/Accessibility/ARIA/Roles/list_role), the containing role for a scrollable [`articles`](/en-US/docs/Web/Accessibility/ARIA/Roles/article_role) where scro
```suggestion
A `feed` is a type of [`list`](/en-US/docs/Web/Accessibility/ARIA/Roles/list_role), the containing role for scrollable [`articles`](/en-US/docs/Web/Accessibility/ARIA/Roles/article_role) where scrolling may cause articles to be added to the top or end of the list. The role enables assistive technology to use the browse mode reading cursor to both read and scroll through a stream of rich content that may continue scrolling infinitely by loading more content as the user reads. Examples include an RSS feed, news feeds, social media feeds like Facebook, Instagram or Twitter, or even a list of related products on an e-commerce page. These streams can be limited or infinite, loading more content as the user scrolls. Implementing the `feed` pattern allows a screen reader to reliably read and trigger the loading of feed content while in reading mode.
```

2023-01-13 20:47 UTC, dipikabh approved these changes
Thanks 👍

2023-01-14 09:36 UTC, OnkarRuikar commented
> This pull request has merge conflicts that must be resolved before it can be merged.

done

2023-01-16 09:32 UTC, bsmth approved these changes
Looks good, thanks @OnkarRuikar 👍🏻 

@Josh-Cena it looks like your suggestions have been addressed. Any objections to merging?

2023-01-17 21:08 UTC, Josh-Cena approved these changes

2023-01-17 21:08 UTC, merged