Fix spellings
mdn/content pull request #23504
Opened 2023-01-10 02:03 UTC by OnkarRuikar

The PR fixes spellings flagged by cSpell.

2023-01-11 06:36 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-posinset/index.md
> +<h2 id="periodic-table">Periodic table of chemical elements</h2>
does this conform to our recommended ID names?

2023-01-11 06:47 UTC, OnkarRuikar commented on files/en-us/web/accessibility/aria/attributes/aria-posinset/index.md
> +<h2 id="periodic-table">Periodic table of chemical elements</h2>
Yes it does. [We use hyphens](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML#class_and_id_names)`-` and not underscores`_`.

2023-01-11 09:31 UTC, Rebstorm commented on files/en-us/web/accessibility/aria/attributes/aria-posinset/index.md
> +<h2 id="periodic-table">Periodic table of chemical elements</h2>
Meanwhile I think the lint rule is a good idea, I think it might be a different PR. I dont want to know how often the rule has been broken :scream:

2023-01-13 01:11 UTC, dipikabh requested changes
Some suggestions and questions for you, @OnkarRuikar

2023-01-13 01:11 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +- Attempting to serialize {{jsxref("BigInt")}} values will throw. However, if the BigInt has a `toJSON()` method (through monkey patching: `BigInt.prototype.toJSON = ...`), that method can provide th
```suggestion
- Attempting to serialize the values that {{jsxref("BigInt")}} will throw. However, if `BigInt` has a `toJSON()` method (using monkey patching: `BigInt.prototype.toJSON = ...`), that method can provide the serialization result. This constraint ensures that a proper serialization (and, very likely, its accompanying deserialization) behavior is always explicitly provided by the user.
```
- This may be outside the scope of this pull request but this sentence needs to be rewritten: "Attempting to serialize {{jsxref("BigInt")}} values will throw."

2023-01-13 01:50 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +- Attempting to serialize {{jsxref("BigInt")}} values will throw. However, if the BigInt has a `toJSON()` method (through monkey patching: `BigInt.prototype.toJSON = ...`), that method can provide th
A "BigInt" is a type and used like an adjective, so the revision sounds weird...

2023-01-13 05:42 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +- Attempting to serialize {{jsxref("BigInt")}} values will throw. However, if the BigInt has a `toJSON()` method (through monkey patching: `BigInt.prototype.toJSON = ...`), that method can provide th
> * This may be outside the scope of this pull request but this sentence needs to be rewritten: "Attempting to serialize {{jsxref("BigInt")}} values will throw."

Agree. Apart from tense, the API want us to provide our own toJSON (and parse) method for BigInt values.
How about this?
```suggestion
- Attempt to serialize a {{jsxref("BigInt")}} value throws a TypeError. However, if the BigInt object has a `toJSON()` method, which can be added by monkey patching (`BigInt.prototype.toJSON = ...`), then that method provides the serialization result. This constraint forces developers to provide their own serialization for BigInt values. Corresponding deserialization can be provided using the [reviver function](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver) argument to `JSON.parse()` method.
```

2023-01-13 05:52 UTC, OnkarRuikar commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
>  `JSON.stringify()` converts a value to JSON notation representing it:
> Is this okay?

```suggestion
`JSON.stringify()` converts a value to the JSON notation that the value represents. Values are stringified in the following manner:
```

2023-01-13 20:37 UTC, dipikabh approved these changes
Thanks for the improvements, @OnkarRuikar!
I can merge this if you're not expecting any more reviews.

2023-01-13 22:41 UTC, merged