At-rule functions
mdn/content pull request #23523
Opened 2023-01-10 19:21 UTC by ramiy

### Description

A page with all the available CSS [at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) functions.

### Motivation

CSS data-types have functions. They are documented in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

CSS at-rule have functions too, they are not documented yet. This PR adds a new page containing those functions.

### Additional details

Back in 2020, when we used the old platform before the migration to GitHub markdown, [I created the first page](https://github.com/mdn/sprints/issues/3838) listing all the available "[CSS functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions)". It contains dozens of data-type-functions in one place.

In 2023, I want to create the same page with all the available at-rule-functions in one place. Hopefully, spec writers will add new at-rule-functions in the future.

2023-01-13 21:30 UTC, dipikabh commented
Hi @ramiy, I've started reviewing your pull request. I have a couple of questions/observations related to the other page https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions:

- Should the title "CSS Functional Notation" instead be "CSS data type functions" or "CSS type functions" to be more explicit?
- Not all the functions listed on this page appear in the sidebar under the "Functions" menu. Shouldn't they?
- The landing pages - both for type functions and at-rule functions - should themselves be accessible from the sidebar. The landing page for the data types https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types also cannot be currently reached from the side bar.

2023-01-13 22:03 UTC, dipikabh requested changes
Hi @ramiy, I've added a few edits and suggestions.

2023-01-13 22:03 UTC, dipikabh commented on files/en-us/web/css/at-rule-functions/index.md
> +  - : Evaluates browser supports based on specified font format for layout and rendering.
```suggestion
The {{CSSxRef("@supports")}} at-rule checks for a browser's support for the specified CSS feature and then applies the CSS styling.

- {{CSSxRef("@supports", "@supports selector()")}}
  - : Applies CSS rules after checking browser's support for the specified selector syntax.
- {{CSSxRef("@supports", "@supports font-tech()")}}
  - : Applies CSS rules after checking browser's support for the specified font technology.
- {{CSSxRef("@supports", "@supports font-format()")}}
  - : Applies CSS rules after checking browser's support for the specified font format.
```

2023-01-13 22:03 UTC, dipikabh commented on files/en-us/web/css/at-rule-functions/index.md
> +  - : Defines XML namespace from a specified source.
```suggestion
The {{CSSxRef("@namespace")}} at-rule is used to specify XML namespaces to be used in a CSS stylesheet.

- {{CSSxRef("@namespace", "@namespace url()")}}
  - : Defines XML namespace from the specified URL.
- {{CSSxRef("@namespace", "@namespace src()")}}
  - : Defines XML namespace from the specified source.
```

2023-01-13 22:03 UTC, dipikabh commented on files/en-us/web/css/at-rule-functions/index.md
> +The {{CSSxRef("@container")}} at-role specify styles to a containment context.
```suggestion
The {{CSSxRef("@container")}} at-rule is used to specify styles for a containment context.
```

2023-01-15 09:03 UTC, ramiy commented on files/en-us/web/css/at-rule-functions/index.md
> +slug: Web/CSS/At-rule-functions
Tried to use "At-rule_functions" but got an error... I reverted to "At-rule-functions"

2023-01-16 17:36 UTC, dipikabh approved these changes
Thanks for the updates.

2023-01-16 17:36 UTC, dipikabh commented
I've left a comment about the slug change.

Any thoughts about this: https://github.com/mdn/content/pull/23523#issuecomment-1382412991?

2023-01-16 17:37 UTC, merged

2023-01-17 10:10 UTC, ramiy commented
@dipikabh I'm currently updating the CSS functions page. When I create the PR, I'll ping you. We will discuses about all the issues in a separate PR. This PR is all about at-rule functions...