webRequestFilterResponse permissions
mdn/content pull request #23699
Opened 2023-01-16 18:16 UTC by rebloor

### Description

Add details for the `"webRequestfilterResponse"` and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.

### Motivation

Address of the documentation requirements of [Bug 1809235](https://bugzilla.mozilla.org/show_bug.cgi?id=1809235)

### Related issues and pull requests

PR for related BCD changes to be provided.

2023-01-18 17:09 UTC, rpl requested changes

2023-01-18 17:09 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
typo: "WebRequestfilterResponse" => "WebRequestFilterResponse"

2023-01-18 17:09 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
I'll prefer to split out the part that mention the other permission specific to "webRequestFilterResponse.serviceWorkerScript", for a couple of reasons:
- that is required for both MV3 and MV2 extensions
- explicitly opt-ing in to use `webRequest.filterResponseData` for a service worker script request should not be something we should suggest all extensions using `webRequest.filterResponseData` to do, on the contrary I think we should mention that the additional permission should only be requested for extension that specifically need that feature, and avoided otherwise 

It may be even worth considering to add also mentioning that requesting `webRequestFilterResponse.serviceWorkerScript` into an addon submitted to AMO may require that submission to go through additional scrutiny, let's see what @wagnerand things about this, if we explicitly add that part would also request @wagnerand sign-off on it.

We may also wont to mention that as for the `webRequest.filterResponseData` API method, the `webRequestFilterResponse` and `webRequestFilterResponse.serviceWorkerScript` are only supported by Firefox.

2023-01-19 01:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
@rpl I'm slightly confused, given that there is a comment on the bug that says "once this bug will be landed, an MV3 extension that wants to use webRequest.filterResponseData will have to request both "webRequestFilterResponse" and "webRequestFilterResponse.serviceWorkerScript".

2023-01-19 13:31 UTC, wagnerand commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
Do we have notes on higher scrutiny for any other APIs as well? It might be a good idea to start doing this at some point, but maybe in a more complete way. But I don't have a strong opinion either way, it probably doesn't hurt mentioning this is in a sentence. Providing explanation and rationale why you should or should not do something is always good.

2023-01-19 17:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
Fixed

2023-01-20 11:59 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
> @rpl I'm slightly confused, given that there is a comment on the bug that says "once this bug will be landed, an MV3 extension that wants to use webRequest.filterResponseData will have to request both "webRequestFilterResponse" and "webRequestFilterResponse.serviceWorkerScript".

@rebloor my apologies, I just re-looked to that comment on bugzilla and that was actually a typo, the comment was missing a "on intercepted requests originated for service worker scripts", that is when an MV3 extensions would need both (while an MV2 one would only really need "webRequestFilterResponse.serviceWorkerScript" in practice),

I'm going to edit the comment on bugzilla to make sure that if we will be looking back to it then it isn't going to still be misleading.

2023-01-20 12:05 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +- In a Manifest V3 extension, you must have the `"webRequestBlocking"`, `"webRequestfilterResponse"`, and `"webRequestFilterResponse.serviceWorkerScript"` API permissions.
> Do we have notes on higher scrutiny for any other APIs as well? It might be a good idea to start doing this at some point, but maybe in a more complete way.

we can definitely consider to followup about that, maybe `proxy` API may be another one that we may want consider adding a similar warning.

In this particular case I'm mainly interesting to avoid pushing the extension developers to assume they would better always request both even if they are not sure they actual need the serviceWorkerScript one, and so mentioning that `"webRequestFilterResponse.serviceWorkerScript"` may make an AMO submission to go through additional scrutiny sounds like a reasonable way to still be able to mention the permission for completeness but disincentive it to be requested without any use case that actually requires it.

2023-01-20 12:20 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +From Firefox 110, to use this API:
@rebloor Given that `webRequest` and `webRequestBlocking` are required in all versions, maybe we could start by saying that to get access to this API `"webRequest"` and `"webRequestBlocking"` permission are always required, without specifying any Firefox versions range, and then followup mentions for the additional requirements in separate paragraphs:

In Firefox >= 110, MV3 extensions must also request the `"webRequestFilterResponse"` permission (in addition to the other mandatory ones mentioned earlier) to be able to successfully call `webRequest.filterResponseData` on the intercepted webRequest.

In Firefox >= 95, to be allowed to use `webRequest.filterResponseData` on intercepted requests related to service workers script being loaded, the additional `"webRequestFilterResponse.serviceWorkerScript` is also required

2023-01-20 12:20 UTC, rpl commented on files/en-us/mozilla/firefox/releases/110/index.md
> +- The `"webRequestFilterResponse"` and `"webRequestFilterResponse.serviceWorkerScript"` [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions) have bee
Technically `"WebRequestFilterResponse.serviceWorkerScript"` isn't something we introduced in 110 (it was introduced in 95 as mentioned earlier), and so we may omit that from the release notes and just mention `webRequestFilterResponse`.

2023-01-20 17:22 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/webrequest/filterresponsedata/index.md
> +From Firefox 110, to use this API:
Thanks for the clarification, updated

2023-01-20 17:23 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/110/index.md
> +- The `"webRequestFilterResponse"` and `"webRequestFilterResponse.serviceWorkerScript"` [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions) have bee
Updated and added `"WebRequestFilterResponse.serviceWorkerScript"` to the 95 release note.

2023-01-30 14:59 UTC, rebloor commented
@rpl have my updates satisfied your "change requested"?

2023-02-17 17:12 UTC, rpl approved these changes

2023-02-17 17:18 UTC, rebloor commented
Thanks @rpl

2023-02-17 17:19 UTC, merged