Syntax guide - update re multiple line syntax blocks
mdn/content pull request #2376
Opened 2021-02-15 23:33 UTC by hamishwillee

This attempts to reflect discussion in https://github.com/mdn/content/issues/2202

Note, I have no idea how you're supposed to find the doc https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections

2021-02-15 23:33 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  slice(start)
Should we return Array ?

2021-02-15 23:34 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  <pre class="brush: js"><var>responseStr</var> = <var>element</var>.querySelector(<var>selector</var>);</pre>
See previous line - do we really mark everything up with `var`?

2021-02-16 11:11 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  slice(start)
Not for the moment

2021-02-16 11:25 UTC, Elchi3 requested changes
Thanks, great to see us moving in this direction 👍 Some changes requested.

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  slice(start,end)
```suggestion
  slice(start, end)
```

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  <pre class="brush: js"><var>responseStr</var> = <var>element</var>.querySelector(<var>selector</var>);</pre>
This example looks quite confusing to me. I'm not sure what to make of it.
Wouldn't this be the correct syntax: `queryselector(selector)` ?

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +<pre class="brush: js">var <var>observer</var> = new IntersectionObserver(<var>callback</var>, <var>options</var>);</pre>
```suggestion
<pre class="brush: js">new IntersectionObserver(<var>callback</var>, <var>options</var>);</pre>
```

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +<p>or this (from {{DOMxRef("WindowOrWorkerGlobalScope.fetch")}}):</p>
Can we avoid using a mixin example here? That just adds complexity that isn't needed to explain this.

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
>  void <var>ctx</var>.drawImage(<var>image</var>, <var>sx</var>, <var>sy</var>, <var>sWidth</var>, <var>sHeight</var>, <var>dx</var>, <var>dy</var>, <var>dWidth</var>, <var>dHeight</var>);</pre>
```suggestion
<pre class="brush: js">drawImage(<var>image</var>, <var>dx</var>, <var>dy</var>);
drawImage(<var>image</var>, <var>dx</var>, <var>dy</var>, <var>dWidth</var>, <var>dHeight</var>);
drawImage(<var>image</var>, <var>sx</var>, <var>sy</var>, <var>sWidth</var>, <var>sHeight</var>, <var>dx</var>, <var>dy</var>, <var>dWidth</var>, <var>dHeight</var>);</pre>
```

2021-02-16 11:25 UTC, Elchi3 commented on files/en-us/mdn/structures/syntax_sections/index.html
> +<p>For specific cases where it is seen as beneficial, a separate <strong>Formal syntax</strong> section may be declared using ththe formal notification.</p>
```suggestion
<p>For specific cases where it is seen as beneficial, a separate <strong>Formal syntax</strong> section may be declared using the formal notification.</p>
```

2021-02-16 14:16 UTC, Elchi3 commented
Oh, one more thing: this needs an entry in the MDN contribution changelog.

2021-02-19 00:24 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  <pre class="brush: js"><var>responseStr</var> = <var>element</var>.querySelector(<var>selector</var>);</pre>
@Elchi3 I didn't even consider we should roll this out to the single line case. Makes a lot of sense, but just to make sure everyone is looped in I have added https://github.com/mdn/content/issues/2202#issuecomment-781725210 - will come back to this once people have had a chance to review.

2021-02-19 00:36 UTC, hamishwillee commented
Thanks for the review. I will revisit this after people have had a chance to comment on https://github.com/mdn/content/pull/2376#discussion_r578840238

@chrisdavidmills says he will take care of the contribution changelog - presumably after this goes in.

2021-02-19 12:01 UTC, chrisdavidmills commented
> Thanks for the review. I will revisit this after people have had a chance to comment on [#2376 (comment)](https://github.com/mdn/content/pull/2376#discussion_r578840238)
> 
> @chrisdavidmills says he will take care of the contribution changelog - presumably after this goes in.

I've submitted a draft PR for this at https://github.com/mdn/content/pull/2475

2021-02-23 01:51 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +<p>or this (from {{DOMxRef("Document.hasStorageAccess")}}):</p>
FYI this replaces the mixin case. It isn't very interesting though.

2021-02-23 01:53 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +<pre class="brush: js">match(<var>request</var>, <var>options</var>)</pre>
FYI it feels like for the single line case at least we're losing a little information. For example here we now no longer know that a promise is returned.

2021-02-23 01:54 UTC, hamishwillee commented
@Elchi3 Should be good for a re-review now. The main update being consistent application of the same style to the single-line case.

2021-02-23 15:28 UTC, peterbe requested changes
I'm a bit out of my element here. I'm not confident enough on the "policies" for the content and stuff. Sorry. 

However, found some other nits. 

Also, I'm hesitant with this use of `<var>`. It will entirely disappear in the final rendered HTML. The Yari builder will look at the `<pre>` tag much like a user does when using a mouse cursor. It just takes the visible text (none of the markup) and sends it into `PrismJS` for conversion to syntax highlighted HTML. 

And once we move to Markdown, I'm not sure but I suspect we'll have even less power over the syntax-highlighted code blocks. I do hope we can someday have something for code snippets so you can extra highlight specific line numbers.

2021-02-23 15:28 UTC, peterbe commented on files/en-us/mdn/guidelines/writing_style_guide/index.html
> +<p>Use the {{HTMLElement("code")}} tags to mark up function names, variable names, and method names. For example: "the <code>frenchText()</code> function".</p>
I don't think that's an appropriate hyperlink. (referring to the use of the `HTMLElement`). You just need to say:
```suggestion
<p>Use the &lt;code&gt; tags to mark up function names, variable names, and method names. For example: <code>the &lt;code&gt;frenchText()&lt;/code&gt; function</code>.</p>
```
(man, this would be easier if it was just Markdown)

2021-02-23 15:28 UTC, peterbe commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  &lt;pre class="brush: js"&gt;slice()
[All statements must end with semicolons (";").](http://localhost:3000/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#general_javascript_guidelines)
So the 3 lines of JS in this example should have a trailing semi-colon.

2021-02-23 17:28 UTC, Ryuno-Ki commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  &lt;pre class="brush: js"&gt;slice()
Nit: there's Automatic Semicolon Injection (ASI) in JavaScript.
So „should”, not „must” :)

2021-02-23 18:13 UTC, peterbe commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  &lt;pre class="brush: js"&gt;slice()
I don't know what you're trying to add with that comment @Ryuno-Ki 
This JS code is sample JS code about writing JS in code snippets. There exists a best practice document. So in a sense, the right word is "must" :)

2021-02-23 19:47 UTC, Ryuno-Ki commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  &lt;pre class="brush: js"&gt;slice()
> All statements must end with semicolons (";"). We require them in all of our code samples even though they're technically optional in JavaScript because we feel that it leads to code that is clearer and more precise about where each statement ends.

I was referring to the „technically optional” bit.

2021-02-23 20:22 UTC, hamishwillee commented on files/en-us/mdn/guidelines/writing_style_guide/index.html
> +<p>Use the {{HTMLElement("code")}} tags to mark up function names, variable names, and method names. For example: "the <code>frenchText()</code> function".</p>
Fair enough. Fixed. Yes, bring on the markdown!

2021-02-23 20:23 UTC, hamishwillee commented on files/en-us/mdn/structures/syntax_sections/index.html
> +  &lt;pre class="brush: js"&gt;slice()
FWIW I did think about this and had _decided_ to omit them. But worth keeping in line with guidelines. Fixed.

2021-02-23 20:27 UTC, hamishwillee commented
@peterbe  ( and @Ryuno-Ki ) Thanks for your reviews

> Also, I'm hesitant with this use of `<var>`. It will entirely disappear in the final rendered HTML. The Yari builder will look at the <pre> tag much like a user does when using a mouse cursor. It just takes the visible text (none of the markup) and sends it into PrismJS for conversion to syntax highlighted HTML.

I have removed all the `var`. While your arguments about yari and markdown are all compelling, the main reason is that they no longer serve a purpose - we've removed all the bits that this was supposed to differentiate. All that is left is the arguments, and they are "by definition" variable/user-defined.

2021-02-24 13:43 UTC, Elchi3 approved these changes

2021-02-24 14:38 UTC, peterbe approved these changes

2021-02-24 21:26 UTC, merged

2021-02-24 21:27 UTC, hamishwillee commented
Self merging following approvals. FYI @chrisdavidmills we can iterate if you have further comments.

I have one; I would love a return type :-)

2021-02-25 09:19 UTC, chrisdavidmills commented
@hamishwillee nah, this is good; I'm happy with it as it stands. I'm still not convinced about the return type in the syntax...