Add Discord to contact informations
mdn/content pull request #23789
Opened 2023-01-20 15:31 UTC by OnkarRuikar

Mention discord server in places where we mentioned community discussions and matrix chat.

/cc @schalkneethling

2023-01-20 15:50 UTC, OnkarRuikar commented
Changes have been made considering Discord as the main choice for direct communication with the team/community.

If we want Discourse can be replaced by [Discord forum channels](https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ):
![code_help_forums](https://user-images.githubusercontent.com/87750369/213742988-6758c490-e423-40a1-927c-fc934c853d42.png)

2023-01-24 02:55 UTC, hamishwillee commented on CONTRIBUTING.md
> +You can chat with us on [community Discord server](https://discord.gg/apa6Rn7uEj) or [file an issue](https://github.com/mdn/content/issues).
```suggestion
You can chat with us on the [community Discord server](https://discord.gg/apa6Rn7uEj) or [file an issue](https://github.com/mdn/content/issues).
```

2023-01-24 02:55 UTC, hamishwillee commented on README.md
> +You can communicate with the MDN Web Docs team and community through discussions on [community Discord server](https://discord.gg/apa6Rn7uEj), [GitHub discussions](https://github.com/mdn/mdn-communit
```suggestion
You can communicate with the MDN Web Docs team and community through discussions on the [community Discord server](https://discord.gg/apa6Rn7uEj), [GitHub discussions](https://github.com/mdn/mdn-community/discussions), or using our forums on [Discourse](https://discourse.mozilla.org/c/mdn/236).
```

2023-01-24 02:55 UTC, hamishwillee commented on REVIEWING.md
> +   change is explained. Ping our team on [MDN Web Docs community Discord server](https://discord.gg/apa6Rn7uEj) to ask for help if you are still not sure, or
```suggestion
   change is explained. Ping our team on the [MDN Web Docs community Discord server](https://discord.gg/apa6Rn7uEj) to ask for help if you are still not sure, or
```

2023-01-24 02:56 UTC, hamishwillee commented on files/en-us/learn/javascript/first_steps/what_went_wrong/index.md
> +- If you come across any errors in your code that you aren't sure how to fix after reading this article, you can get help! Ask for help on [community Discord server](https://discord.gg/apa6Rn7uEj). T
```suggestion
- If you come across any errors in your code that you aren't sure how to fix after reading this article, you can get help! Ask for help on the [community Discord server](https://discord.gg/apa6Rn7uEj). Tell us what your error is, and we'll try to help you. A listing of your code would be useful as well.
```

2023-01-24 02:57 UTC, hamishwillee commented on files/en-us/mdn/community/contributing/getting_started/index.md
> +[GitHub discussions](https://github.com/mdn/mdn-community/)
```suggestion
Join us on the [Community Discord server](https://discord.gg/apa6Rn7uEj) and [GitHub discussions](https://github.com/mdn/mdn-community/)
```

2023-01-24 02:58 UTC, hamishwillee commented on files/en-us/mdn/community/contributing/getting_started/index.md
> +> If unsure what to do, you are always welcome to [ask for help on community Discord server](https://discord.gg/apa6Rn7uEj).
```suggestion
> If unsure what to do, you are always welcome to [ask for help on the community Discord server](https://discord.gg/apa6Rn7uEj).
```

2023-01-24 02:58 UTC, hamishwillee commented on files/en-us/mdn/community/contributing/getting_started/index.md
> +> If you have any questions or concerns about anything discussed here, please [contact us on community Discord server](https://discord.gg/apa6Rn7uEj) or [open a discussion](https://github.com/mdn/mdn
```suggestion
> If you have any questions or concerns about anything discussed here, please [contact us on the community Discord server](https://discord.gg/apa6Rn7uEj) or [open a discussion](https://github.com/mdn/mdn-community/discussions/categories/content).
```

2023-01-24 02:58 UTC, hamishwillee commented on files/en-us/mdn/community/contributing/translated_content/index.md
> +> **Note:** If you want to contribute to one of the existing active locales get in touch with one of the active members listed below, or contact us for help on [community Discord server](https://disc
```suggestion
> **Note:** If you want to contribute to one of the existing active locales get in touch with one of the active members listed below, or contact us for help on the [community Discord server](https://discord.gg/apa6Rn7uEj).
```

2023-01-24 03:02 UTC, hamishwillee requested changes, later dismissed
I've added a bunch of comments - unless it was intentional isn't it "THE community Discord server"? If so, fix everywhere.

Looking at all these links we have the following comms channels
- discourse
- chat rooms
- Discord
- MDN discussions
- Etc.

That seems like a stupidly long list. In any case, I'd create a "Communication channels" or "Support" section somewhere and change most of these links to "If you want to discuss this further see". Up to you, but that will ease long term maintenance.

I'd put Discord at the bottom because it is the ~least usable~ one that is going to be hardest to search as a FAQ.

2023-01-24 03:22 UTC, OnkarRuikar commented
> In any case, I'd create a "Communication channels" or "Support" section somewhere and change most of these links to

That is a good idea! Clearly these are way too many pages to change contact info every time. When we hit 5k users mark on the server we'll get custom invite link(without numbers) like `https://discord.gg/mdn-web-docs`.
I'll create a separate page for all contact info.

> I'd put Discord at the bottom because it is the least usable one that is going to be hardest to search as a FAQ for long term storage of "answers", or possibly describe alongside each what sorts of discussions they are intended for.

But discord is going to have fastest response time and more activity becasue all other channel(matrix, twitter, mastodon etc.) members have joined it. Waiting on @schalkneethling for deciding priority of channels.

2023-01-24 05:25 UTC, hamishwillee commented
> But discord is going to have fastest response time and more activity because all other channel(matrix, twitter, mastodon etc.) members have joined it. Waiting on @schalkneethling for deciding priority of channels.

This may make sense. In most communities in which I'm a member permanent discussions are valued for their reusability/searchability - in particular over slack which you have to pay for to store the data. It may be that we don't care about historical data though, so we'll funnel everyone to discord.

There is a lot to be said for "just one channel" for comms.

2023-01-24 05:38 UTC, OnkarRuikar commented
> It may be that we don't care about historical data though, so we'll funnel everyone to discord.

For historical data, I think we have GitHub discussions we mostly take big decisions there.

With current setup discussions are happening in different places, and certainly we are not keeping track of that data. We do need to assert that which channel is for what purpose.

2023-01-24 10:28 UTC, OnkarRuikar commented on CONTRIBUTING.md
> +You can chat with us on [community Discord server](https://discord.gg/apa6Rn7uEj) or [file an issue](https://github.com/mdn/content/issues).
going to create a new page for all the links

2023-01-24 10:32 UTC, bsmth commented
>I'd create a "Communication channels" or "Support" section somewhere and change most of these links to "If you want to discuss this further see". Up to you, but that will ease long term maintenance.

I agree with this, we should take stock of places we list the different communication channels and I would `+1` on a single page that summarizes how to get in touch via these channels and their purpose.

2023-01-25 12:11 UTC, OnkarRuikar commented
I've made the changes. Added a dedicated page named [Communication channels](https://pr23789.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Community/Communication_channels), and updated content documents to refer to it. Let me know how it looks.

2023-01-25 12:44 UTC, bsmth commented on files/en-us/mdn/community/communication_channels/index.md
> +Chat rooms are for queries, clarifications, sharing information, and meetings.
Adding one or two sentences for context 👍🏻

```suggestion
Chat rooms are for queries, clarifications, sharing information, and meetings.
They are also a great place to get to know other community members, share your work, and get help with your contributions.
If you have a question or want to get in touch with us about something, feel free to join us.
```

2023-01-25 12:51 UTC, bsmth commented on files/en-us/mdn/community/communication_channels/index.md
> +
Minor hint on the timing as it shows it's fresh

```suggestion
As of January 2023, MDN Web Docs opened up a Discord server to the public.
This server is a great place to see what staff and members of the community are doing on a daily basis and to find out how you can get involved.

```

2023-01-25 12:52 UTC, bsmth commented on files/en-us/mdn/community/communication_channels/index.md
> +
```suggestion
The Matrix chat rooms are an alternative to the Discord server.

```

2023-01-25 12:57 UTC, bsmth commented on files/en-us/mdn/community/communication_channels/index.md
> +[GitHub Discussions](https://github.com/mdn/mdn-community/discussions) are for conducting polls and for issues that needs a discussion to agree upon a course of action or define an actionable piece o
```suggestion
[GitHub Discussions](https://github.com/mdn/mdn-community/discussions) are for conducting polls and for issues that needs a discussion to agree upon a course of action or define an actionable piece of work.
You can use GitHub discussions if you think the answer to your question might be helpful for other people to find in the future.
See [the discussion guidelines](/en-US/docs/MDN/Community/Discussions) before you create a new submission.
```

2023-01-25 12:59 UTC, bsmth commented on files/en-us/mdn/community/contributing/getting_started/index.md
> +> If unsure what to do, you are always welcome to ask for help on the [communication channels](/en-US/docs/MDN/Community/Communication_channels).
```suggestion
> If you're unsure what to do, you can always ask for help in one of [our communication channels](/en-US/docs/MDN/Community/Communication_channels).
```

2023-01-25 13:01 UTC, bsmth commented on files/en-us/mdn/community/roles_teams/index.md
> +  - There is a subteam for the different topic areas — accessibility, Add-ons, CSS, HTML, HTTP, JavaScript, SVG, Web API, and WebAssembly. For example, there's `@yari-content-css` and `@yari-content-
TIL

2023-01-25 13:05 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/howto/document_an_http_header/index.md
> +- If in doubt, ask the MDN Web Docs team on the [MDN Web Docs chat rooms](/en-US/docs/MDN/Community/Communication_channels#chat_rooms) whether or not it makes sense to write about the header you have
```suggestion
- If in doubt, [ask the MDN Web Docs team](/en-US/docs/MDN/Community/Communication_channels) whether or not it makes sense to write about the header you have chosen.
```

2023-01-25 13:09 UTC, bsmth approved these changes
Thanks, @OnkarRuikar, I like the changes, well done. Going to ask for another `+1` in our daily later in case there's anything we need to change on the Communication Channels page.

2023-01-25 13:22 UTC, OnkarRuikar commented on files/en-us/mdn/community/communication_channels/index.md
> +Chat rooms are for queries, clarifications, sharing information, and meetings.
> Adding one or two sentences for context 👍🏻

```suggestion
Chat rooms are for queries, clarifications, sharing information, and meetings.
They are also great places to get to know other community members, share your work, and get help for your contributions.
If you have a question or want to get in touch with us about something, feel free to join us.
```

2023-01-25 13:32 UTC, OnkarRuikar commented on files/en-us/mdn/community/pull_requests/index.md
> +If anyone has engaged in behavior that is potentially illegal or makes you or someone else feels unsafe, unwelcome, or uncomfortable, you are encouraged to [report it](https://www.mozilla.org/en-US/a
> I think the original is correct here :)

My bad didn't read the full sentence :( Rephrasing it to make it direct.
```suggestion
If you or someone else has experienced behavior that is potentially illegal or makes you feel unsafe, unwelcome, or uncomfortable, we encourage you to [report it](https://www.mozilla.org/en-US/about/governance/policies/participation/reporting/).
```

2023-01-25 14:36 UTC, akasyagroup commented on files/en-us/mdn/community/pull_requests/index.md
> +If anyone has engaged in behavior that is potentially illegal or makes you or someone else feels unsafe, unwelcome, or uncomfortable, you are encouraged to [report it](https://www.mozilla.org/en-US/a
@akasyaagroup.com

2023-01-25 16:37 UTC, dipikabh commented
Thanks @OnkarRuikar for these updates! I'll take a quick look.

2023-01-25 17:43 UTC, dipikabh requested changes
I've left a few edits/suggestions on the new Communication channels page :)

2023-01-25 17:43 UTC, dipikabh commented on files/en-us/mdn/community/communication_channels/index.md
> +See [the Discussion guidelines](/en-US/docs/MDN/Community/Discussions) before you create a new submission.
I began with a few edits and ended up rewriting a whole lot. Let me know what you think.

```suggestion
[GitHub Discussions](https://github.com/mdn/mdn-community/discussions) on MDN Web Docs is the place to look out for any project-wide [announcements](https://github.com/mdn/mdn-community/discussions/categories/announcements). 

Use GitHub discussions to post your questions and propose your suggestions. Choose the appropriate [discussion category](https://github.com/mdn/mdn-community#github-discussions) when starting a thread. Your answered questions can be really useful for other people looking for similar information in the future.

We strongly recommend you to use GitHub Discussions to share the work you're planning to do and that you think will need a consensus on the course of action. You can also use GitHub Discussions for brainstorming your ideas to define an actionable piece of work, especially when the changes have a wide-ranging impact.

Check out the MDN-specific [discussion guidelines](/en-US/docs/MDN/Community/Discussions) before you create a new submission.
```

2023-01-25 17:43 UTC, dipikabh commented on files/en-us/mdn/community/communication_channels/index.md
> +The forums can be used for discussing code problems, assessment with the skill tests, assessments that appear on the Learn web development section on MDN, and if you want someone to take a look at yo
```suggestion
You can use the forums listed below for discussing code problems. You can also request feedback here on your progress with the assessments in the [MDN learning area](https://developer.mozilla.org/en-US/docs/Learn).
```

2023-01-25 17:43 UTC, dipikabh commented on files/en-us/mdn/community/communication_channels/index.md
> +Each localization team has its own [methods of communication](/en-US/docs/MDN/Community/Contributing/Translated_content).
```suggestion
Each localization team has its own [method of communication](/en-US/docs/MDN/Community/Contributing/Translated_content).
```

2023-01-25 17:43 UTC, dipikabh commented on files/en-us/mdn/community/communication_channels/index.md
> +## Bugs and issues
This is not a communication channel per se and should not be listed here. I think for this guidance, folks will need to refer to https://developer.mozilla.org/en-US/docs/MDN/Community/Issues. But this is a good list, maybe we can move it to https://developer.mozilla.org/en-US/docs/MDN/Community/Issues#reporting_an_issue?

2023-01-25 17:43 UTC, dipikabh commented on files/en-us/mdn/community/communication_channels/index.md
> +For nonpublic communication email the [mdn-admins list](mailto:mdn-admins@mozilla.org).
```suggestion
For any nonpublic communication, send an email to [mdn-admins](mailto:mdn-admins@mozilla.org).
```

2023-01-26 01:49 UTC, OnkarRuikar commented on files/en-us/mdn/community/communication_channels/index.md
> +There are various communication channels using which community can contact MDN Web Docs staff and participate in discussions.
```suggestion
The community can use one of the many communication channels described here to contact the MDN Web Docs staff, ask questions and participate in discussions.
```

2023-01-26 02:00 UTC, OnkarRuikar commented on files/en-us/mdn/community/communication_channels/index.md
> +## Chat rooms
> Should we order these channels in the order of recommended use? So say, the 'Discord server' first, 'GitHub Discussions' next, and so on? Possibly move Matrix toward the end of the list?

I've grouped them by type(chat, github, forums, email etc.) and sorted based on frequency of use/importance.
![references](https://user-images.githubusercontent.com/87750369/214739985-9f8c3824-3dd4-40f2-97cb-34f36cfdbf68.png)
Looks like our current stance is that discord is in experimentation phase and we are not leaving matrix till everything goes well with discord. So they are on same recommendation level.
Discord has many features so it'll definitely going to be prominent in future.

2023-01-26 02:38 UTC, OnkarRuikar commented on files/en-us/mdn/community/communication_channels/index.md
> +## Bugs and issues
done

2023-01-26 14:25 UTC, OnkarRuikar commented
Do you think we need to update the website footer? if yes, how?
![references](https://user-images.githubusercontent.com/87750369/214860069-eb38f63e-224e-45b2-a77b-cc089a4ec2f1.png)

The footer is using Matrix chat at the moment.

2023-01-26 17:00 UTC, dipikabh commented
> Do you think we need to update the website footer?

Probably too early to update. We're not sunsetting Matrix update. Let's see how Discord plays out with the community over the coming months.

>  if yes, how?

The code is most likely in yari

2023-01-26 17:02 UTC, dipikabh approved these changes
The updates look good. Thanks a lot @OnkarRuikar for your contribution to add the new page!

2023-01-26 17:04 UTC, merged

2023-01-26 21:53 UTC, hamishwillee commented
> I believe all of Hamish's comments have been addressed.

Yes, this looks excellent. Thanks @OnkarRuikar.