Add landing page for the Launch Handler API
mdn/content pull request #23832
Opened 2023-01-23 09:55 UTC by chrisdavidmills

### Description

https://github.com/mdn/content/pull/22957 added documentation for the different parts of the [Web App Launch Handler API](https://wicg.github.io/web-app-launch/), but it didn't include a landing page to tell the complete story of the API, and tie all of the different parts together. This PR does just that.

### Motivation

### Additional details

### Related issues and pull requests

2023-01-23 16:26 UTC, jpmedley requested changes
Chris,

I have just a few nits. Otherwise this looks good.

Joe

2023-01-23 16:26 UTC, jpmedley commented on files/en-us/web/api/launch_handler_api/index.md
> +The **Launch Handler API** allows developers to control how a [progressive web app](/en-US/docs/Web/Progressive_web_apps) (PWA) is launched — for example if it uses an existing window or creates a ne
```suggestion
The **Launch Handler API** allows developers to control how a [progressive web app](/en-US/docs/Web/Progressive_web_apps) (PWA) is launched—for example if it uses an existing window or creates a new one, and how the app's target launch URL is handled.
```

2023-01-23 16:26 UTC, jpmedley commented on files/en-us/web/api/launch_handler_api/index.md
> +The **Launch Handler API** allows developers to control how a [progressive web app](/en-US/docs/Web/Progressive_web_apps) (PWA) is launched — for example if it uses an existing window or creates a ne
I don't know if MDN uses the Chicago Manual of Style, but this is how that book consistently treats m-dashes, even though it doesn't have a rule for them that I can find.

2023-01-23 16:26 UTC, jpmedley commented on files/en-us/web/api/launch_handler_api/index.md
> +  - : The most recently interacted with browsing context in a web app window is chosen to handle the launch. The target launch URL is made available in the {{domxref("LaunchParams.targetURL", "target
```suggestion
  - : The most recently interacted with browsing context in a web app window is chosen to handle the launch. Specify the target launch URL in the {{domxref("LaunchParams.targetURL", "targetURL")}} property of the {{domxref("LaunchParams")}} object passed into the {{domxref("LaunchQueue.setConsumer", "window.launchQueue.setConsumer()")}}'s callback function. As you'll see below, this allows you to set custom launch handing functionality for your app.
```

2023-01-23 16:26 UTC, jpmedley commented on files/en-us/web/api/launch_handler_api/index.md
> +  - : The behavior is up to the user agent to decide what works best for the platform. For example, <code>navigate-existing</code> might make more sense on mobile, where single app instances are comm
```suggestion
  - : The user agent decides what works best for the platform. For example, <code>navigate-existing</code> might make more sense on mobile, where single app instances are commonplace, whereas <code>navigate-new</code> might make more sense in a desktop context. This is the default value used if provided values are invalid.
```

2023-01-23 16:26 UTC, jpmedley commented on files/en-us/web/api/launch_handler_api/index.md
> +When `focus-existing` is used as a value, you can include code inside the {{domxref("LaunchQueue.setConsumer", "window.launchQueue.setConsumer()")}}'s callback function to provide custom handling of
```suggestion
When `focus-existing` is used, you can include code inside the {{domxref("LaunchQueue.setConsumer", "window.launchQueue.setConsumer()")}}'s callback function to provide custom handling of the {{domxref("LaunchParams.targetURL", "targetURL")}}
```

2023-01-23 16:35 UTC, chrisdavidmills commented on files/en-us/web/api/launch_handler_api/index.md
> +The **Launch Handler API** allows developers to control how a [progressive web app](/en-US/docs/Web/Progressive_web_apps) (PWA) is launched — for example if it uses an existing window or creates a ne
I appreciate that's the typographically "correct" way to use em-dashes, but I've always added spaces at either side because I think it looks better on small copy on the web. I don't think we've ever really had an MDN standard style for this.

2023-01-23 16:37 UTC, chrisdavidmills commented
Thanks @jpmedley ; some really good change suggestions here, which I've committed, and one quibble ;-)

2023-01-23 18:33 UTC, jpmedley approved these changes

2023-01-23 18:34 UTC, jpmedley commented
This has some unsuccessful checks. Can't merge yet.

2023-01-23 18:48 UTC, chrisdavidmills commented
@jpmedley I've rerun the checks, and it is passing now.

2023-01-24 12:44 UTC, tomayac reviewed
Non-owner LGTM with some suggestions.

2023-01-24 12:44 UTC, tomayac commented on files/en-us/web/api/launch_handler_api/index.md
> +If not specified, the default `client_mode` value is auto. Available values are:
```suggestion
If not specified, the default `client_mode` value is `auto`. Available values are:
```

2023-01-24 12:44 UTC, tomayac commented on files/en-us/web/api/launch_handler_api/index.md
> +  - : The most recently interacted with browsing context in a web app window is chosen to handle the launch. Specify the target launch URL in the {{domxref("LaunchParams.targetURL", "targetURL")}} pr
```suggestion
  - : The most recently interacted with browsing context in a web app window is chosen to handle the launch. This will populate the target launch URL in the {{domxref("LaunchParams.targetURL", "targetURL")}} property of the {{domxref("LaunchParams")}} object passed into the {{domxref("LaunchQueue.setConsumer", "window.launchQueue.setConsumer()")}}'s callback function. As you'll see below, this allows you to set custom launch handing functionality for your app.
```

This happens automatically, it's not the developer who needs to fill this info.

2023-03-02 15:48 UTC, Elchi3 commented
@tomayac Do you still want to respond to Chris' question?

Otherwise I guess we should get this merged, don't we?

2023-03-02 16:31 UTC, Elchi3 approved these changes
Alright, off we go, thanks everyone! 👍

2023-03-02 16:31 UTC, merged

2023-03-06 07:28 UTC, chrisdavidmills commented
Nice one, thanks folks!