fix: remove ending periods from non-sentence list items
mdn/content pull request #23845
Opened 2023-01-23 20:15 UTC by de-oz

### Description

Removed periods from the list items which do not represent complete sentences under the `See also` heading.

2023-01-23 22:31 UTC, hamishwillee commented
I don't have a problem with this, but where is the style guide it is meeting? https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide

2023-01-24 08:03 UTC, de-oz commented
> I don't have a problem with this, but where is the style guide it is meeting?
> 
> I.e. in https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide I see mostly instruction to use punctuation. For me consistency is more important than punctuation, but following this guide is most important of all.

This PR was based on consistency rather than the style guide, as usually on MDN list items under the `See also` section do not include periods if they aren't complete sentences and only contain links.  If both including a period and omitting it in such cases are acceptable, then I guess this PR can be closed, but if not, please let me know how this inconsistency should be handled.

2023-01-24 08:17 UTC, hamishwillee commented
> please let me know how this inconsistency should be handled.

Of course. @Rumyra Can we have direction on whether see also links bullet lists should have punctuation or not. Then we can update the style guide (or at least know the rule). FWIW I would prefer no punctuation, because often these will be single words or heading names that are not naturally complete sentences.

2023-02-23 18:42 UTC, dipikabh commented
Hi @hamishwillee and @de-oz, hopefully the guidelines for 'See also' and the punctuation to be used with the links will soon be out. Stay tuned.

2023-03-12 23:32 UTC, hamishwillee commented
Hi @dipikabh, Did final rules get agreed here?

2023-03-13 05:23 UTC, teoli2003 commented
The short answer is yes. The final PR to get them in the meta docs is waiting for a last round of approval to mark consensus (your approval to show you adhere to the soon-confirmed consensus is welcome): https://github.com/mdn/content/pull/25191

2023-03-13 05:55 UTC, hamishwillee commented
Yes, I had a couple of reservations (mostly matters of "taste"), but it is a significant improvement.

Looks like see also are mostly bulleted lists, where items are phrases with punctuation. So this PR would not be accepted. There is some inconsistency between the instructions and representative examples so I'll wait until it merges before proceeding with this.

Thanks!

2023-03-23 20:24 UTC, dipikabh requested changes
Edited two files to make the list items follow the new ["See also" section guidelines](https://github.com/mdn/content/pull/25191).

In general, the following structure is being followed:
`<link text>: Description phrase(no punctuation)`
The description phrase is optional.

So yes, removing periods here is correct (because they're not complete sentences) but also rephrase the list item so that the link text is at the beginning.

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
> +- The interface defining it, {{domxref("HTMLCanvasElement")}}
```suggestion
- {{domxref("HTMLCanvasElement")}}: Interface used to define the getContext() method
```

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
>    {{domxref("WebGLRenderingContext")}} and {{domxref("WebGL2RenderingContext")}} and
```suggestion
- {{domxref("CanvasRenderingContext2D")}},
  {{domxref("WebGLRenderingContext")}}, {{domxref("WebGL2RenderingContext")}}, {{domxref("ImageBitmapRenderingContext")}}: Available rendering contexts
```

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
> +- Available color spaces: [sRGB color space](https://en.wikipedia.org/wiki/SRGB) and [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3)
```suggestion
- [sRGB color space](https://en.wikipedia.org/wiki/SRGB) on Wikipedia
- [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3) on Wikipedia
```

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/height/index.md
> +- The interface defining it, {{domxref("HTMLCanvasElement")}}
```suggestion
- {{domxref("HTMLCanvasElement")}}: Interface used to define the `HTMLCanvasElement.height` property
```
would be nice to replace the pronoun 'it' to be more specific

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/height/index.md
>  - The other property controlling the size of the canvas,
```suggestion
- {{domxref("HTMLCanvasElement.width")}}: Other property used to control the size of the canvas
```

2023-03-23 20:24 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/height/index.md
> +  {{domxref("HTMLCanvasElement.width")}}
```suggestion

```

2023-03-24 16:29 UTC, dipikabh requested changes
Suggested a few more edits, including some untouched list items

2023-03-24 16:29 UTC, dipikabh commented on files/en-us/web/api/htmlcanvaselement/getcontext/index.md
> +- [display-p3 color space](https://en.wikipedia.org/wiki/DCI-P3) on Wikipedia
There is an issue with the ordering of the items here.

These two should probably be at the top:
- HTMLCanvasElement
- OffscreenCanvas.getContext()

Followed by these two, perhaps as a single item:
- CanvasRenderingContext2D.getContextAttributes(), WebGLRenderingContext.getContextAttributes()

2023-03-24 16:29 UTC, dipikabh commented on files/en-us/web/api/htmlmediaelement/seekable/index.md
>  - [Media Source Extensions API](/en-US/docs/Web/API/Media_Source_Extensions_API)
```suggestion
- [Media Source API](/en-US/docs/Web/API/Media_Source_Extensions_API)
```

2023-03-24 16:29 UTC, dipikabh commented on files/en-us/web/api/htmlmediaelement/texttracks/index.md
> +- [`addtrack`](/en-US/docs/Web/API/VideoTrackList/addtrack_event),
```suggestion
- {HTMLElement("audio")}}, {{HTMLElement("video")}}
- {{DOMxRef("AudioTrack")}}, {{DOMxRef("AudioTrackList")}}
- {{DOMxRef("VideoTrack")}}, {{DOMxRef("VideoTrackList")}}
- [`addtrack`](/en-US/docs/Web/API/VideoTrackList/addtrack_event),
```

2023-03-26 08:13 UTC, de-oz commented on files/en-us/web/api/htmlmediaelement/canplaytype/index.md
>  - [Guide to media types and formats on the web](/en-US/docs/Web/Media/Formats)
OK, I'm going to make a separate PR for that.

2023-03-27 14:48 UTC, dipikabh approved these changes
Thanks a lot 👍

2023-03-27 14:48 UTC, merged

2023-03-27 22:49 UTC, hamishwillee commented
Thanks. Great to get this in. Now I just have to make my review and writing habits match our agreed bullet list format :-)