Fix chapter order to match sidebar
mdn/content pull request #23846
Opened 2023-01-23 20:18 UTC by dawei-wang

Fix mdn/content#23536

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-01-23 20:58 UTC, dawei-wang commented on files/en-us/learn/css/building_blocks/organizing/index.md
> +}
```suggestion
.box {background-color: #567895; }
h2 {background-color: black; color: white; }
```

2023-01-23 20:58 UTC, dawei-wang commented on files/en-us/learn/css/building_blocks/organizing/index.md
> +}
Undo prettier change

2023-01-24 02:52 UTC, dipikabh requested changes
Thanks for fixing this, @dawei-wang! I've added a suggestion.

For future reference, it would be helpful if you can comment on the issue that you're interested to work on. We can then assign the issue to you. This will help other interested contributors who might be looking for issues to work on (and prevent duplicate effort if they know an issue is already claimed).

2023-01-24 02:52 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
>  Pseudo-classes are keywords that start with a colon:
How about saying:

```suggestion
Pseudo-classes are keywords that start with a colon. For example, `:hover` is a pseudo-class.
```
And lines 51-54 can be removed.

2023-01-24 02:52 UTC, dipikabh commented on files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
>  Pseudo-elements behave in a similar way. However, they act as if you had added a whole new HTML element into the markup, rather than applying a class to existing elements. Pseudo-elements start with
Similarly here, how about:

```suggestion
Pseudo-elements behave in a similar way. However, they act as if you had added a whole new HTML element into the markup, rather than applying a class to existing elements.

Pseudo-elements start with a double colon `::`. `::before` is an example of a pseudo-element.
```

and then remove lines 86-89.

2023-01-24 19:47 UTC, dawei-wang commented on files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
```suggestion
```

2023-01-24 19:47 UTC, dawei-wang commented on files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
```suggestion
```

2023-01-24 19:53 UTC, dawei-wang commented on files/en-us/learn/css/building_blocks/selectors/pseudo-classes_and_pseudo-elements/index.md
```suggestion
```
```

2023-01-24 20:20 UTC, dipikabh approved these changes
Thank you! 👍

2023-01-24 20:20 UTC, merged