Add more examples to illustrate CSS var() usage
mdn/content pull request #23860
Opened 2023-01-24 05:33 UTC by tlylt

### Description
Address the confusion with CSS variable in #11382 with two examples.

The first example illustrates the point that var() can invoke variables defined in the later part of the same file.
The second example responds to the queries, specifically:
- Does setting a custom property in one css file allow it's use in other cases files on the same page?
  - Answer: Yes
- should the custom properties be defined in the first css file loaded?
  - Answer: Not necessarily

### Motivation
Add helpful examples

### Additional details
Some simple testing done around CSS var:
- https://tlylt.github.io/web-examples/cssvar/index.html

Other docs:
- https://blog.logrocket.com/css-variables-scoping/
- https://css-tricks.com/a-complete-guide-to-custom-properties/#h-credit

### Related issues and pull requests
Fixes #11382

2023-02-02 21:52 UTC, dipikabh requested changes
Thanks for adding these examples, @tlylt!

2023-02-02 21:52 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +    <!-- Background color will be pink -->
```suggestion

```
1. Instead of adding this as a comment, can we add the explanation after the html code snippet to say what the result will be and why (the variable is inside the `:root` selector, which has a global scope)?
2. Would be nice to reorder the code snippets to first show the HTML one and then the two CSS ones - for consistency with other pages.
3. Ideally, the example should begin with a description of what it will demo 🙂

[Formatting live samples]((https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#formatting_live_samples) )

2023-02-03 14:37 UTC, tlylt commented on files/en-us/web/css/var/index.md
> +    <!-- Background color will be pink -->
Hi @dipikabh, thank you for your comments. I did it the current way following the existing examples on the page. I probably can turn these examples into live-examples, do you think that would be better?

2023-02-03 17:49 UTC, dipikabh requested changes
Sorry, I forgot to indicate that the HTML CSS subsections under Examples will have their section headings.

2023-02-03 17:49 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +    <!-- Background color will be pink -->
Yes and I realize that the existing examples are not following the guidelines. For this pull request, at the minimum, it would be nice to remove the comment and have it as an explanation after the result frame. And reorder CSS after HTML.

It would be great if you can turn them into live samples!

2023-02-03 17:49 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +```css
```suggestion
#### CSS

```css
```

2023-02-03 17:49 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +```css
```suggestion
### Using a custom property set in another file

#### CSS

```css
```

2023-02-03 17:49 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +
```suggestion

#### HTML

```

2023-02-05 15:48 UTC, tlylt commented on files/en-us/web/css/var/index.md
> +    <!-- Background color will be pink -->
Thanks! Have updated accordingly.

2023-02-06 18:56 UTC, dipikabh requested changes
Thanks a lot for adding the live samples, even for the existing examples! I've added a few clarifying statements in the Result explanation.

2023-02-06 18:56 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink.
```suggestion
Here, the value of the `background-color` property has been set via the custom property `--main-bg-color`. So the background color of the HTML body will be pink.
```

2023-02-06 18:56 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink.
```suggestion
In this example, the custom property `--main-bg-color` has been set on the `:root` selector, which has a global scope. So, even though the custom property is set later, the background color of the HTML body will be pink. 
```

2023-02-06 18:56 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink.
```suggestion
The background color of the HTML body will be pink in this case even though the custom property is declared in another file. This is because of the global scope of the `:root` selector.
```

2023-02-06 18:56 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +Since `--main-bg-color` isn't set, the body's `color` will fall back to `--backup-bg-color`. As `--backup-bg-color` isn't set either, it will fall back to white.
`--backup-bg-color` set to teal in `:root`. Shouldn't background color be teal and not white?

2023-02-06 23:41 UTC, tlylt commented on files/en-us/web/css/var/index.md
> +Since `--main-bg-color` isn't set, the body's `color` will fall back to `--backup-bg-color`. As `--backup-bg-color` isn't set either, it will fall back to white.
Thanks for checking! I was confused by the previous example, setting `background-color` instead of `color` here fixes the issue. And yes it should be teal.

2023-02-06 23:49 UTC, tlylt commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink.
Hi @dipikabh, I am not too sure about the part where:
>  which has a global scope. So, even though the custom property is set later,

Setting the custom property on a "local scope" will work as well (e.g. setting it on "body" instead of ":root"). E.g. the following:

```css
body {
  background-color: var(--main-bg-color);
}

body {
  --main-bg-color: pink;
}
```

I tried checking the specs and the best explanation I can find for this is that:
> Custom properties are ordinary properties, so they can be declared on any element, are resolved with the normal inheritance and cascade rules
https://www.w3.org/TR/css-variables-1/#example-f8770692:~:text=Custom%20properties%20are%20ordinary%20properties%2C%20so%20they%20can%20be%20declared%20on%20any%20element%2C%20are%20resolved%20with%20the%20normal%20inheritance%20and%20cascade%20rules

My logical explanation would be that the custom property will be evaluated when needed, and when it's needed, all declarations in the same file is already available. This is similar to what is said [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#:~:text=The%20value%20is%20computed%20where%20it%20is%20needed)
> The value is computed where it is needed

Do you have any advice/comment on this? (affects the "Using a custom property set in another file" part as well)

2023-02-07 16:00 UTC, dipikabh requested changes

2023-02-07 16:00 UTC, dipikabh commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink.
Thanks for highlighting this nuance. I'm suggesting edits to resolve this.

2023-02-07 23:16 UTC, tlylt commented on files/en-us/web/css/var/index.md
> +The background color of the HTML body will be pink in this case even though the custom property is declared in another file. This is because of the global scope of the `:root` selector.
```suggestion
The background color of the HTML body will be pink in this case even though the custom property is declared in another file.
```

2023-02-08 02:44 UTC, dipikabh approved these changes
Thanks a lot for your time and effort on this! 🙌

2023-02-08 02:44 UTC, merged