Adding CookieStoreManager interface
mdn/content pull request #2393
Opened 2021-02-16 12:15 UTC by rachelandrew

Adds the `CookieStoreManager` interface, which allows Service Workers to subscribe to cookie events.

Spec: https://wicg.github.io/cookie-store/#CookieStoreManager

The API overview page is part of PR https://github.com/mdn/content/pull/2316

reviewer @jpmedley

2021-03-17 07:58 UTC, rachelandrew commented
@jpmedley this one has been hanging around a while, could you take a look?

2021-03-22 14:10 UTC, jpmedley requested changes

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
If the URL has to match the scope exactly, what is the point of passing the URL?

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +<p>In this example the {{domxref("ServiceWorkerRegistration")}} represented by <code>registration</code> is subscribing to change events on the cookie name <code>cookie1</code> with a scope of <code>
```suggestion
<p>In this example the {{domxref("ServiceWorkerRegistration")}} represented by <code>registration</code> is subscribing to change events on the cookie named <code>"cookie1"</code> with a scope of <code>"/path1"</code>.</p>
```

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/unsubscribe/index.html
> +  - unsubscribe()
```suggestion
  - unsubscribe
```

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/unsubscribe/index.html
> +  - unsubscribe()
I have it on my list to update mdn-helper so that it doesn't dump "()".

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/unsubscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
Same question here.

2021-03-22 14:10 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/unsubscribe/index.html
> +<p>In this example the {{domxref("ServiceWorkerRegistration")}} represented by <code>registration</code> is unsubscribing from change events on the cookie name <code>cookie1</code> with a scope of <c
```suggestion
<p>In this example the {{domxref("ServiceWorkerRegistration")}} represented by <code>registration</code> is unsubscribing from change events on the cookie named <code>"cookie1"</code> with a scope of <code>"/path1"</code>.</p>
```

2021-03-23 11:49 UTC, rachelandrew commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
The steps are detailed here https://wicg.github.io/cookie-store/#CookieStoreManager-subscribe

Assume to make sure you are acting on the registration you think you are, but I don't have a use case.

2021-03-24 13:52 UTC, jpmedley commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
Can you please find out.

2021-03-30 10:18 UTC, rachelandrew commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
have done, waited until today so the email didn't hit the Google long weekend so I'll update this when I find out.

2021-04-05 09:12 UTC, rachelandrew commented on files/en-us/web/api/cookiestoremanager/subscribe/index.html
> +  <dd>Thrown if the url passed in <code>subscriptions</code> does not match the service worker registration's {{domxref("ServiceWorkerRegistration.scope","scope")}}.</dd>
Had a reply from one of the spec authors, as below. I'll add something into the docs regarding this:

> "The subscription URL argument may potentially be of narrower scope than the service worker registration scope. If specified to a narrower scope, It will only receive change events for cookies found for that scope. For an example:

> // Subscription
registration.cookies.subscribe([{name: 'cookie-name', url: '/cookie/path/'}]);

> // Will receive a cookie change event for subscription.
cookieStore.set({name: 'cookie-name', value: 'cookie-value', path: '/cookie/path/'})

> // Will not receive a cookie change event for subscription.
cookieStore.set({name: 'cookie-name', value: 'cookie-value', path: '/different/cookie/path/'})

2021-04-06 09:29 UTC, rachelandrew commented
@jpmedley I added an additional example and some clarification (also fixed the syntax to remove the var as you have done with others).

2021-04-06 14:27 UTC, jpmedley approved these changes

2021-04-06 14:50 UTC, merged