Document the FormData constructor submitter parameter
mdn/content pull request #23950
Opened 2023-01-28 06:59 UTC by jenseng

### Description

Document the FormData constructor submitter parameter. 

Also add a "Submit button" glossary page and link to it from various places to help facilitate a consistent and complete understanding of what a submit button is :)

### Motivation

This is a new feature which should be landing in major browsers soon, so it would be useful to have it documented.

### Additional details

Spec: https://xhr.spec.whatwg.org/#interface-formdata
Spec PR (merged): https://github.com/whatwg/xhr/pull/366
Chromium implementation: https://chromium-review.googlesource.com/c/chromium/src/+/4189297
WebKit implementation: https://github.com/WebKit/WebKit/pull/9188
Gecko implementation: https://phabricator.services.mozilla.com/D167576

### Related issues and pull requests

Fixes #23917

2023-01-28 07:02 UTC, jenseng commented
Here's what the example looks like in bleeding edge WebKit w/ submitter support:

![safari-submitter](https://user-images.githubusercontent.com/109489/215252120-e1e3d068-411b-4769-af94-789db05acf65.png)

2023-01-30 16:35 UTC, jenseng commented
cc @annevk

2023-01-30 16:43 UTC, jpmedley requested changes, later dismissed

2023-01-30 17:10 UTC, jenseng commented on files/en-us/web/api/formdata/formdata/index.md
> +  - : A {{Glossary("submit button")}} that is a member of the `form`. If the `submitter` has a `name` attribute or is an `{{HtmlElement('input/image', '&lt;input type="image"&gt;')}}`, it will be inc
This might be misleading, as that could be understood to mean the `value` attribute. While the `name` + `value` are included for a `<button>` or `<input type="submit">`, that's not the case for an `<input type="image">` (i.e. `value` is unused and instead you get two entries for the x/y coordinate).

Maybe we could say something like `..., its value(s) will be included ...`, wdyt?

2023-01-30 17:16 UTC, jenseng commented on files/en-us/web/api/formdata/formdata/index.md
> +  - : A {{Glossary("submit button")}} that is a member of the `form`. If the `submitter` has a `name` attribute or is an `{{HtmlElement('input/image', '&lt;input type="image"&gt;')}}`, it will be inc
Or we could split it into two sentences, like on the `Submit button` page. Or perhaps keep the original wording but have `will be included` link directly to the relevant `Form data entries` heading on the `Submit button` page.

2023-01-31 15:23 UTC, jpmedley commented on files/en-us/web/api/formdata/formdata/index.md
> +  - : A {{Glossary("submit button")}} that is a member of the `form`. If the `submitter` has a `name` attribute or is an `{{HtmlElement('input/image', '&lt;input type="image"&gt;')}}`, it will be inc
I changed the wording slightly.

2023-01-31 17:01 UTC, jenseng commented on files/en-us/web/api/formdata/formdata/index.md
> +  - : A {{Glossary("submit button")}} that is a member of the `form`. If the `submitter` has a `name` attribute or is an `{{HtmlElement('input/image', '&lt;input type="image"&gt;')}}`, it will be inc
Hmm, that's still not quite accurate, as name-less image inputs will add entries to the form data set. e.g. clicking `<input type="image" />` will yield something like `x=123&y=234`

How this wording tweak, which also adds an example for the common case?

```
A {{Glossary("submit button")}} that is a member of the `form`. If the `submitter`
has a `name` attribute or is an `{{HtmlElement('input/image', '&lt;input type="image"&gt;')}}`,
its data [will be included](...) in the form data set (e.g. `buttonName=buttonValue`).
```
`will be included` would link directly to the relevant explainer on the `Submit button` page.

2023-03-09 20:43 UTC, jenseng commented
Rebased and made some wording tweaks, also added some more links. LMK what you think @jpmedley, thanks!

2023-03-09 21:23 UTC, jenseng commented
Added a entry for the firefox 111 release when this is landing

2023-03-13 14:52 UTC, Elchi3 commented on files/en-us/glossary/submit_button/index.md
> +  - HTML
MDN doesn't do tags anymore. (This changed after this PR was opened initially, sorry).

```suggestion
```

2023-03-14 13:21 UTC, Elchi3 approved these changes
Thank you! Great work 👍

2023-03-14 13:23 UTC, merged