move Web/API/Element/openOrClosedShadowRoot
mdn/content pull request #23989
Opened 2023-01-30 16:46 UTC by tlylt

### Description
Move content of openOrClosedShadowRoot into `dom` namespace (according to suggestions in #23711)
- redirect is added
- a `dom` page is added as previously there's no such page
- content in the `openOrClosedShadowRoot` is edited to reflect the description of the `dom.openOrClosedShadowRoot` method
- add a note about Firefox's `Element.openOrClosedShadowRoot`

### Motivation
Fix BCD and related issues for openOrClosedShadowRoot

### Additional details
Content is based on 
- https://developer.chrome.com/docs/extensions/reference/dom/
- https://chromium.googlesource.com/chromium/src/+/fe6e27d68a44c714dcce906749390378ede7d423

### Related issues and pull requests
Fixes #23711

2023-01-31 01:57 UTC, rebloor requested changes

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +
Remove - we don't have this section in the descriptions of the webextensions APIs
```suggestion
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/index.md
> +Use the `chrome.dom` API to access special DOM APIs for Extensions.
To align with this with the way webextension APIs are described on MDN:
```suggestion
Access special extension only DOM features.
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/index.md
> +  - : Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach the shadow root, it will return null.
```suggestion
  - : Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach to the shadow root, it returns null.
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +
Remove, this only makes sense when it was documented as a web API
```suggestion
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +
Also delete, not relevant now it's documented as a webextension api
```suggestion
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach the shadow root, it will return `null`.
```suggestion
Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach to the shadow root, it returns `null`.
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +> root to an existing element.
```suggestion
> root to an element.
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +A {{DOMxRef("ShadowRoot")}} object instance, regardless if its
```suggestion
A {{DOMxRef("ShadowRoot")}} object instance, regardless of whether its
```

2023-01-31 01:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +> property represents the shadow root hosted by the element, regardless if its
```suggestion
> property represents the shadow root hosted by the element, regardless of whether its
```

2023-01-31 02:40 UTC, wbamberg commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +page-type: web-api-instance-property
```suggestion
```

(this isn't a Web API any more)

2023-01-31 03:13 UTC, tlylt commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach the shadow root, it will return `null`.
Will it be confusing to say "the element doesn't attach **to** the shadow root"?

It seems like in the docs shadowRoot is [attached to](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#:~:text=The%20Element.attachShadow()%20method%20attaches%20a%20shadow%20DOM%20tree%20to%20the%20specified%20element%20and%20returns%20a%20reference%20to%20its%20ShadowRoot.) an element......I'm not sure if the opposite is equivalent. What do you think?

2023-02-06 01:25 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/openorclosedshadowroot/index.md
> +Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach the shadow root, it will return `null`.
In which case this may be clearer:
```suggestion
Gets the open shadow root or the closed shadow root hosted by the specified element. If the shadow root isn't attached to the element, it will return `null`.
```

2023-02-06 01:26 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/dom/index.md
> +  - : Gets the open shadow root or the closed shadow root hosted by the specified element. If the element doesn't attach the shadow root, it will return null.
As suggested below
```suggestion
  - : Gets the open shadow root or the closed shadow root hosted by the specified element. If the shadow root isn't attached to the element, it will return `null`.
```

2023-02-07 02:11 UTC, rebloor approved these changes
Thanks @tlylt looks good.

2023-02-07 02:14 UTC, merged

2023-02-20 01:37 UTC, eliykat commented
Hi @tlylt, apologies if this is not the correct place for this question, but I noticed this change recently and I'm unsure what it means for existing code.

Does this change in namespace reflect a breaking change in the actual API, that is, any existing code that uses the `myElement.openOrClosedShadowRoot` API now needs to be updated to call `browser.dom.openOrClosedShadowRoot(myElement)` instead? (If so, from what FF version does this take effect?) I assume this isn't the case because it's still listed as backwards compatible to FF 63, but the example code snippet otherwise suggests this, so I wanted to make sure. Thanks for your help.

2023-02-20 02:31 UTC, tlylt commented
> Does this change in namespace reflect a breaking change in the actual API, that is, any existing code that uses the `myElement.openOrClosedShadowRoot` API now needs to be updated to call `browser.dom.openOrClosedShadowRoot(myElement)` instead? (If so, from what FF version does this take effect?) I assume this isn't the case because it's still listed as backwards compatible to FF 63, but the example code snippet otherwise suggests this, so I wanted to make sure. Thanks for your help.

Hi @eliykat, because I don't really develop web extensions so I might not be able to provide the most accurate information on this (as it's difficult for me to test). From my search when working on this PR, it seems to be that:
- the `openOrClosedShadowRoot` method is available in the context of web extensions, first implemented in Firefox and then in Chrome
- In Firefox it's available under the `dom` namespace and hence `dom.openOrClosedShadowRoot`
- In Chrome, it's available under the `chrome.dom` namespace, and hence `chrome.dom.openOrClosedShadowRoot`
- The `openOrClosedShadowRoot` may or may not be exactly the same in these two browsers, but they share the same name
- This PR and the BCD PR simply fix the problem that this method was originally written under web APIs, which is not true as it is only available to web extensions. In terms of the signature and the use of this API, I don't think there are any changes.

That's all I can tell. Hope that helps!