snagging changes
mdn/content pull request #241
Opened 2020-12-15 14:23 UTC by rachelandrew

A few changes, adding more description of parameters, to work done while still in the wiki.

cc: @jpmedley

2020-12-15 16:37 UTC, jpmedley requested changes

2020-12-15 16:37 UTC, jpmedley commented on files/en-us/web/api/csstransformcomponent/tomatrix/index.html
> +
Is there an explanation anywhere off exactly how the transforms are different?

2020-12-15 16:37 UTC, jpmedley commented on files/en-us/web/api/csstransformcomponent/tostring/index.html
> +<p class="summary">The <strong><code>toString()</code></strong> method of the {{domxref("CSSTransformComponent")}} interface returns a string in the form of a CSS Transforms function.</p>
I believe that MDN's instructions for stringifiers are wrong. Here's the IDL spec's description: https://heycam.github.io/webidl/#idl-stringifiers

2020-12-15 16:37 UTC, jpmedley commented on files/en-us/web/api/csstransformcomponent/tostring/index.html
> +  <p>This will use the value of <code>is2D</code> to return either a 2D or 3D transform. For example if the component represents {{domxref("CSSRotate")}} and <code>is2D</code> is false then the strin
If I'm right about stringifier, this paragraph can go on the interface page.

2021-01-15 17:23 UTC, rachelandrew commented on files/en-us/web/api/csstransformcomponent/tostring/index.html
> +  <p>This will use the value of <code>is2D</code> to return either a 2D or 3D transform. For example if the component represents {{domxref("CSSRotate")}} and <code>is2D</code> is false then the strin
I think I have done what was wanted there though this all got a bit messy with conflicts, let me know if it is still not correct.

2021-01-19 20:07 UTC, jpmedley approved these changes

2021-01-19 20:07 UTC, merged