currentColor: add definition and links
mdn/content pull request #24111
Opened 2023-02-02 19:03 UTC by estelle

currentColor is used, but the definition is nearly impossible to find, and many people don't know what it is. So, surfacing it. Also, it has special meaning in `color`, so defining it there.

Also, note I used `currentColor` and not `currentcolor` intentionally. Setting camel case enables screen readers to read it in a more helpful way. 

And always remember to #camelCaseHashTagsWhereNormallyThereAreWordBreaks.

2023-02-02 20:53 UTC, dipikabh requested changes
I took a look even though you have it in DRAFT mode. The two mentions of 'currentcolor' (all lowercase) in the first para (line 24) would also need to be updated?

2023-02-02 20:53 UTC, dipikabh commented on files/en-us/web/css/color/index.md
> +  - : Normally sets the color to the element's `color` property value, but when set as the value of `color` it is treated as `inherit`.
```suggestion
  - : Sets the color of the element's `color` property value. However, if set as the value of `color`, `currentColor` is treated as `inherit`.
```

should 'to' be 'of'?

2023-02-03 00:07 UTC, estelle commented on files/en-us/web/css/color/index.md
> +  - : Normally sets the color to the element's `color` property value, but when set as the value of `color` it is treated as `inherit`.
should be "to".

2023-02-03 00:08 UTC, estelle commented on files/en-us/web/css/color/index.md
> +  - : Sets the color to the element's `color` property value. However, if set as the value of `color`, `currentColor` is treated as `inherit`.
```suggestion
  - : Sets the color to the element's `color` property value. However, if set as the value of `color`, `currentcolor` is treated as `inherit`.
```

2023-02-03 00:11 UTC, estelle commented
I got two bits of feedback:

> `PascalCase` or `camelCase` always help me when strings are smooooshed. i prefer `camelCase`.

and

> Interesting question.  I turned on NVDA to read your post, and it announced them exactly the same (no difference to my ear).

so i think we need to further discuss, and not make the change starting with this PR ;)

2023-02-03 17:57 UTC, dipikabh approved these changes

2023-02-03 17:58 UTC, merged