CSS Module: backgrounds and borders
mdn/content pull request #24123
Opened 2023-02-03 04:50 UTC by estelle

Also includes box shadow, border image, and collapsing borders between table cells.

The list of related border properties are in the logical properties spec.

2023-02-06 20:46 UTC, dipikabh requested changes
Thanks, @estelle. Looks good overall.

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +title: Backgrounds and borders
```suggestion
title: CSS backgrounds and borders
```

I guess we're keeping the 'CSS' bit like in the 'animations' and 'composting and blending' landing pages.

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +
```suggestion
The **CSS backgrounds and borders** module provides properties for adding borders, rounded corners, and box shadows to elements.

You can add different types of border styles, including borders made of images of any image type, from raster images to CSS gradients. Borders can be square or rounded, and a different radius can be set for each corner. Elements can be rounded whether or not they have a visible border.

Box shadows include inset and outset shadow, single or multiple shadows, and solid or allowed to fade to transparent. An outer box-shadow casts a shadow as if the border-box of the element were opaque. An inner box-shadow casts a shadow as if everything outside the padding edge were opaque. The shadow can be solid or include a spread distance with the shadow color transitioning to transparent.

The properties in this module also let you define whether cells inside a {{HTMLElement("table")}} should have shared or separate borders.

```
This is more a stylistic edit. The first sentence mentions borders, corners, and box shadows. So I have followed up the first sentence with the related sentences in the same order. Moved the table bit to the end.
Also rephrased some sentences to avoid repetition of 'this module'.

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +This sample of borders, backgrounds, and box shadows consists of centered background images made of linear and radial gradients and a series of box shadows that make the border appear to "pop." The f
```suggestion
This sample of borders, backgrounds, and box shadows consists of centered background images made of linear and radial gradients. A series of box shadows make the border appear to "pop". The element on the left has a border image set. The element on the right has a rounded dotted border.
```
Splitting the long sentence

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +The background images are defined with {{cssxref("background-image")}}. The images are centered with {{cssxref("background-position")}}. Different values of the {{cssxref("background-clip")}} propert
```suggestion
The background images are defined with {{cssxref("background-image")}}. The images are centered with {{cssxref("background-position")}}. Different values of the {{cssxref("background-clip")}} property for the multiple background images are used to make the background images stay within the content box. The background color gets clipped to the padding box preventing the background from appearing through the transparent sections for the {{cssxref("border-image")}} and the {{cssxref("border-style", "dotted")}} {{cssxref("border")}}. The rounded corners in the element on the right are created using the {{cssxref("border-radius")}} property. A single {{cssxref("box-shadow")}} declaration is used to set all the shadows, both inset and outset. To see the code for this sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/compositing_and_blending/index.md?plain=1).
```

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +  - : Explains how borders, along with other box model properties, impact the CSS box model.
Do you want to move this right after 'Learn CSS: background and borders' so that all learn links are together?

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +  - : Learn how to implement decorative images using CSS background images.
```suggestion
  - : Explains how to implement decorative images using CSS background images.
```
for consistency with other descriptions in this list

Could we add a similar phrasing to the animations page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations#guides

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +- {{cssxref("border-block-end-color")}} CSS property
The 'CSS' in 'CSS property' seems a bit repetitive. Can it be dropped?

If yes, then probably these would need to be updated as well: https://developer.mozilla.org/en-US/docs/Web/CSS/Compositing_and_Blending#related_concepts and https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations#related_concepts

```suggestion
- {{cssxref("border-block-end-color")}} property
```

2023-02-06 20:46 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +- The [`drop-shadow()`](/en-US/docs/Web/CSS/filter-function/drop-shadow) filter function, used by the {{cssxref("filter")}} and {{cssxref("backdrop-filter")}} properties, applies a drop shadow effect
```suggestion
- The [`drop-shadow()`](/en-US/docs/Web/CSS/filter-function/drop-shadow) filter function that applies a drop shadow effect to the input image. The function is used by the {{cssxref("filter")}} and {{cssxref("backdrop-filter")}} properties.
```

2023-02-06 22:27 UTC, estelle commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +  - : Explains how borders, along with other box model properties, impact the CSS box model.
This one is more tangentially related to this module, which is why I didn't put it second.

2023-02-06 22:43 UTC, estelle commented
Thanks for the review!

2023-02-08 02:50 UTC, dipikabh requested changes, later dismissed

2023-02-08 02:50 UTC, dipikabh commented on files/en-us/web/css/css_backgrounds_and_borders/index.md
> +- {{cssxref("text-shadow")}} CSS property
```suggestion
- {{cssxref("border-block-start-color")}} property
- {{cssxref("border-inline-end-color")}} property
- {{cssxref("border-inline-start-color")}} property
- {{cssxref("border-block-end-style")}} property
- {{cssxref("border-block-start-style")}} property
- {{cssxref("border-inline-end-style")}} property
- {{cssxref("border-inline-start-style")}} property
- {{cssxref("border-block-end-width")}} property
- {{cssxref("border-block-start-width")}} property
- {{cssxref("border-inline-end-width")}} property
- {{cssxref("border-inline-start-width")}} property

- {{cssxref("border-start-start-radius")}} property
- {{cssxref("border-start-end-radius")}} property
- {{cssxref("border-end-start-radius")}} property
- {{cssxref("border-end-end-radius ")}} property

- {{cssxref("box-sizing")}} property
- {{cssxref("box-decoration-break")}} property
- {{cssxref("text-shadow")}} property
```

2023-02-08 03:00 UTC, dipikabh approved these changes
Thank you! LGTM.

2023-02-08 03:00 UTC, merged