Update index.md
mdn/content pull request #24147
Opened 2023-02-03 22:13 UTC by boxcleverliam

### Description

Improved the description of how the submit method may be masked by a badly named element.

### Motivation

The existing language "this method" is incorrect. Perhaps "this usage" or "this form control" would be correct.
Adding the error message that happens helps users to understand the meaning of this "masking".

2023-02-06 09:49 UTC, teoli2003 commented
What about:

"A form control with its `name` or `id` set to `submit` will mask…"

I think it is simpler than the construction with _If…_ followed by a second clause that needs to reference the first one.

2023-02-07 20:34 UTC, jpmedley requested changes, later dismissed
Tightening the language a bit.

2023-02-07 20:34 UTC, jpmedley commented on files/en-us/web/api/htmlformelement/submit/index.md
> +of `submit`.
```suggestion
of `submit`, this will mask the form's submit method. Trying to call `document.forms["myform"].submit();`
throws an error `.submit is not a function` because in this case `submit` refers to the form control which has a `name` or `id` of `submit`.
```

2023-03-29 19:34 UTC, Josh-Cena commented
@boxcleverliam what do you think about the suggested change here? Could you make a commit to address them?

2023-05-03 17:50 UTC, Josh-Cena approved these changes
I'm going to merge this. Thanks @boxcleverliam and welcome to MDN :)

2023-05-03 17:50 UTC, merged