CSS Module: basic UI
mdn/content pull request #24152
Opened 2023-02-04 01:34 UTC by estelle

Rewrite of the CSS module page for CSS Basic User Interface module

2023-02-04 02:11 UTC, dawei-wang commented on files/en-us/web/css/css_basic_user_interface/index.md
> +Basic user interface properties can be used to improve user experience and accessibility by providing visual cues to elements that are being intereacted with, including styling mouse cursors and keyb
```suggestion
Basic user interface properties can be used to improve user experience and accessibility by providing visual cues to elements that are being interacted with, including styling mouse cursors and keyboard directional focus navigation, and styling caret cursors when an editable element has focus. The module provides for providing outlines to focused (or not) elements without impacting an element's [box model](/en-US/docs/Learn/CSS/Building_blocks/The_box_model#what_is_the_css_box_model) dimensions and styling. This UI module also enables the styling of user interface controls.
```

2023-02-07 08:50 UTC, teoli2003 commented on files/en-us/web/css/css_basic_user_interface/index.md
> +  - https://www.w3.org/TR/css-ui-3/
We never add old versions of the specs (unless the new is incremental, which is not the case here).

cc/ @Elchi3 or @wbamberg for confirmation
```suggestion
```

2023-02-07 08:58 UTC, teoli2003 requested changes

2023-02-07 08:58 UTC, teoli2003 commented on files/en-us/web/css/css_basic_user_interface/index.md
> +To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/CSS_Basic_User_Interface/index.md).
We shouldn't say to "view the source" on GitHub and link to a **Markdown** file with much more than the source. Readers will likely be lost, especially as beginners will be the most likely to check these features.

@wbamberg Could we use `{{EmbedGHLiveSample}}` so that:
- the code is only in one place
- the code is still displayed on this page

2023-02-07 09:00 UTC, teoli2003 commented on files/en-us/web/css/css_basic_user_interface/index.md
> +- {{CSSxRef("outline")}} shorthand
I don't understand the positioning of the shorthand.

2023-02-07 09:03 UTC, teoli2003 commented on files/en-us/web/css/css_basic_user_interface/index.md
> -- {{CSSxRef("box-sizing")}}
Box-sizing has been moved to its separate module between Levels 3 and 4.

How do we handle such cases? Should we add it (or the CSS module about it) to the _See also_ section. It seems this implies some relation between `box-sizing` and this module.

2023-02-07 18:06 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +- {{CSSxRef("outline")}} shorthand
the value on line 107 is not part of the shorthand.

2023-02-07 18:08 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/CSS_Basic_User_Interface/index.md).
We do not want to show the code on the page.

2023-02-07 18:08 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +  - https://www.w3.org/TR/css-ui-3/
one is level 3, the other is level 4

2023-02-07 18:09 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> -- {{CSSxRef("box-sizing")}}
it will be in the correct spec module landing page

2023-02-07 20:29 UTC, wbamberg commented on files/en-us/web/css/css_basic_user_interface/index.md
> +To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/CSS_Basic_User_Interface/index.md).
I agree `{{EmbedGHLiveSample}}` is a good fit here.

> We do not want to show the code on the page.

If I understand @teoli2003 correctly, by "this page" he means the page(s) linked to from "view the source", not the MDN page that the reader is seeing.

2023-02-08 08:34 UTC, teoli2003 commented on files/en-us/web/css/css_basic_user_interface/index.md
> +- {{CSSxRef("outline")}} shorthand
What about:
```suggestion
- {{CSSxRef("outline")}}, shorthand for:
  - {{CSSxRef("outline-color")}}
  - {{CSSxRef("outline-style")}}
  - {{CSSxRef("outline-width")}}
```

2023-02-09 01:38 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +  - https://www.w3.org/TR/css-ui-3/
I was just copying existing landing pages, like https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text.

2023-02-09 01:39 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/CSS_Basic_User_Interface/index.md).
Working on getting those pages up in css-examples, then i can update here.

2023-02-09 01:39 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +- {{CSSxRef("outline")}} shorthand
I like it!

2023-02-09 01:40 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +- {{CSSxRef("caret")}} shorthand
```suggestion

- {{CSSxRef("caret")}} shorthand
  - {{CSSxRef("caret-color")}}
  - {{CSSxRef("caret-shape")}}
```

2023-02-09 23:09 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +Previously, the {{CSSxRef("box-sizing")}} and {{CSSxRef("text-overflow")}} CSS properties were part of the basic user interface module, but were moved to the [CSS box sizing](/en-US/docs/Web/CSS/CSS_
It is now neither here nor in the see also. But if it should be on the page, it should be here.

2023-02-09 23:28 UTC, estelle commented on files/en-us/web/css/css_basic_user_interface/index.md
> +To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/content/blob/main/files/en-us/web/css/CSS_Basic_User_Interface/index.md).
```suggestion
To see the code for this basic user interface sample, [view the source on Github](https://github.com/mdn/css-examples/blob/main/modules/basicUI.html).
```

2023-02-10 16:37 UTC, estelle commented
I think we're good to go @teoli2003

2023-02-10 17:00 UTC, teoli2003 approved these changes
Yes! And I really _love_ the examples you are adding!

2023-02-10 17:00 UTC, merged