WIP: Updating content that storage is always partitioned
mdn/content pull request #24250
Opened 2023-02-07 12:52 UTC by HannahPeuckmann

### Description

Updating the outdated documents that deal with Storage Access API/ storage access grants. Storage is always partitioned and storage access grants are limited to access to cookies now.

### Motivation

The documentation about the Storage Access API and automatic storage access grants are outdated since the implementation changed in Fx109. The outdated documentation led to confusion because developers expected to see the old behavior. 

### Additional details

Release notes: https://www.mozilla.org/en-US/firefox/109.0/releasenotes/
Meta bug: [Bug 1758737 - [meta] Always Partition Storage](https://bugzilla.mozilla.org/show_bug.cgi?id=1758737)

### Related issues and pull requests

2023-02-21 16:14 UTC, Trikolon reviewed
Thanks for the MDN updates! This will make storage access a bit less confusing I hope.
Your patch changes a couple of mentions of storage to "cookies". While I don't think that's strictly required (the spec still talks about storage and cookies being the only "storage" affected by the storage access api), but it might help developers understand better that we only mean cookies.

I can't officially r+ or r- on this repo so just leaving some comments.

2023-02-27 09:21 UTC, HannahPeuckmann commented on files/en-us/web/privacy/state_partitioning/index.md
> -### Network Partitioning
Trying to implement the idea from @Trikolon to have a "Static Partitioning section" with "Network Partitioning" and "Storage Partitioning"

2023-02-28 15:03 UTC, Trikolon reviewed
Thanks for the great work! I think we can update the PR to request review now.

I'm still not super happy that now there is a bit of a disconnect between the spec talking about storage (cookies being the only storage affected) and the MDN article talking about cookies. Maybe we can discuss this with @bvandersloot-mozilla when he's back.

2023-03-01 10:05 UTC, HannahPeuckmann commented
> Thanks for the great work! I think we can update the PR to request review now.
> 
> I'm still not super happy that now there is a bit of a disconnect between the spec talking about storage (cookies being the only storage affected) and the MDN article talking about cookies. Maybe we can discuss this with @bvandersloot-mozilla when he's back.

Yes, let's do so, the opinion from @bvandersloot-mozilla will be valuable!

2023-04-13 14:32 UTC, dipikabh requested changes
Hi @HannahPeuckmann, I've left one feedback.

About getting more review feedback, @bvandersloot-mozilla seems to be on PTO until May (from their slack status). If there is a related spec, would it be possible to reach out to the authors/contributors for a review or with specific questions? If not, then maybe we just publish with the current changes.

2023-04-13 14:32 UTC, dipikabh commented on files/en-us/web/privacy/state_partitioning/index.md
> +### Static Partitioning
Hi @HannahPeuckmann, one feedback I have is around the section titles. We use sentence casing on MDN. So  it would be good to fix all instances.

```suggestion
### Static partitioning
```

2023-04-13 15:37 UTC, teoli2003 submitted a review, later dismissed
A few more comments to fix. But overall it is a significant improvement.

2023-04-13 15:37 UTC, teoli2003 commented on files/en-us/web/api/storage_access_api/index.md
> +These cookie blocking policies are known to break embedded cross-origin content that requires access to its first-party storage. As an example, federated logins often require access to authentication
```suggestion
These cookie-blocking policies are known to break embedded cross-origin content that requires access to its first-party storage. As an example, federated logins often require access to authentication cookies available in a first-party context, and will require the user to sign in on each site separately (or altogether break) if those cookies are not available. In the case of breakage, site owners have often encouraged users to add their site as an exception or to disable the policy entirely. Consequently, users who wish to continue interacting with embedded content must relax significantly their blocking policy for resources loaded from all embedded origins and possibly across all websites.
```

2023-04-13 15:37 UTC, teoli2003 commented on files/en-us/web/privacy/state_partitioning/index.md
> +#### Dynamically Partitioned APIs
```suggestion
#### Dynamically-partitioned APIs
```

2023-04-13 15:37 UTC, teoli2003 commented on files/en-us/web/privacy/state_partitioning/index.md
> +| Access to unpartitioned cookies is granted through a **heuristic**                                                       | Storage access automatically granted for First-Party isolation "b.example"
Can we link to the "heuristic"? Is it unique for every browser or unspecified and each can decide which one to implement?

2023-04-13 15:37 UTC, teoli2003 commented on files/en-us/web/privacy/state_partitioning/index.md
> +#### Storage Partitioning
```suggestion
#### Storage partitioning
```

2023-04-13 15:37 UTC, teoli2003 commented on files/en-us/web/privacy/state_partitioning/index.md
> +tracking, Firefox partitions accessible storage by top-level site. This
We should be browser-agnostic here. Or explain what the other browsers are doing, too.

2023-05-16 13:58 UTC, dipikabh approved these changes
Thank you. It's looking good, @HannahPeuckmann, just a few nits.

2023-05-16 13:58 UTC, dipikabh commented on files/en-us/web/api/storage_access_api/index.md
> +> **Note:** The [browser compatibility section](#browser_compatibility) provides an overview about the support staus of the Storage Access API.
This not is not needed because "Browser compatibility" is a standard section on the reference pages

```suggestion

```

2023-05-16 13:58 UTC, dipikabh commented on files/en-us/web/api/storage_access_api/index.md
> +The **Storage Access API** provides a way for embedded, cross-origin content to gain unrestricted access to the cookies that it would typically only have access to in a first-party context (We refer
```suggestion
The **Storage Access API** provides a way for embedded, cross-origin content to gain unrestricted access to the cookies that it would typically only have access to in a first-party context. (We refer to storage and cookies that an origin has access to when being in a first-party context as the origin's _first-party_ storage).
```

2023-05-17 06:42 UTC, HannahPeuckmann commented on files/en-us/web/api/storage_access_api/index.md
> +> **Note:** The [browser compatibility section](#browser_compatibility) provides an overview about the support staus of the Storage Access API.
My changes to the storage_access_api doc are obsolete now, there is already an update in main that took care of the issues I am addressing in this pull request.

2023-05-17 06:47 UTC, HannahPeuckmann commented on files/en-us/web/api/storage_access_api/index.md
> +The Storage Access API provides a way for embedded, cross-origin content to gain unrestricted access to the cookies that it would normally only have access to in a first-party context (We refer to st
My changes to this doc are obsolete since there is a change in main that takes care of what I have bee addressing with my changes.

2023-05-17 06:51 UTC, HannahPeuckmann commented on files/en-us/web/privacy/state_partitioning/index.md
> +Generally Firefox partitions accessible storage by top-level site. However, this boundary is dynamic for cookies and access
I've tried to have it sound less Firefox-centric now. Should I also link to the compatibility section?

2023-05-17 06:54 UTC, HannahPeuckmann commented on files/en-us/web/api/document/requeststorageaccess/index.md
> +The **`requestStorageAccess()`** method of the {{domxref("Document")}} interface returns a {{jsxref("Promise")}}. If that promise resolves the requesting origin will have unrestricted access to its f
Most of my changes to this doc are obsolete as well since there is a change in main that takes care of what I have been addressing with my changes.

2023-06-13 17:07 UTC, merged