CSS Module landing page: filter effects
mdn/content pull request #24261
Opened 2023-02-07 21:42 UTC by estelle

2023-02-14 01:36 UTC, dipikabh requested changes
Thanks, @estelle! I don't see the sample in action and a few more comments

2023-02-14 01:36 UTC, dipikabh commented on files/en-us/web/css/filter_effects/index.md
> +The **CSS filter effects** module defines a way of processing an element's rendering before it is displayed in the document.
```suggestion
The properties in the **CSS filter effects** module let you define a way of processing an element's rendering before the element is displayed in the document. Examples of such effects include blurring and changing the intensity of the color of an element.
```

2023-02-14 01:36 UTC, dipikabh commented on files/en-us/web/css/filter_effects/index.md
> +Play with the various sliders to apply filter effects to the image below:
I am not seeing any changes in the image when I move the sliders (chrome, firefox)

2023-02-14 01:36 UTC, dipikabh commented on files/en-us/web/css/filter_effects/index.md
> +- SVG {{cssxref("color-interpolation-filters")}} property
how about 

```suggestion
- {{cssxref("color-interpolation-filters")}} SVG property
```

2023-02-14 01:36 UTC, dipikabh commented on files/en-us/web/css/filter_effects/index.md
> +  - https://drafts.fxtf.org/filter-effects-1
these links are showing as "Unknown specification" in the table

2023-02-14 05:45 UTC, teoli2003 commented on files/en-us/web/css/filter_effects/index.md
> +  - https://drafts.fxtf.org/filter-effects-1
There should be only one, and I think it should be: https://drafts.fxtf.org/filter-effects/

2023-02-14 22:45 UTC, estelle commented on files/en-us/web/css/filter_effects/index.md
> +  - https://drafts.fxtf.org/filter-effects-1
```suggestion
  - https://drafts.fxtf.org/filter-effects
```

2023-02-14 23:35 UTC, estelle commented on files/en-us/web/css/filter_effects/index.md
> +Play with the various sliders to apply filter effects to the image below:
https://github.com/mdn/css-examples/pull/116 fixes it. fingers crossed

2023-02-14 23:39 UTC, estelle commented on files/en-us/web/css/filter_effects/index.md
> +  - https://drafts.fxtf.org/filter-effects
```suggestion
  - https://drafts.fxtf.org/filter-effects-2/
```

2023-02-15 00:53 UTC, estelle commented on files/en-us/web/css/filter_effects/index.md
> +  - https://drafts.fxtf.org/filter-effects-1
https://drafts.fxtf.org/filter-effects/ doesn't have backdrop-filter, neither does -1. And -2 doesn't have filter functions, so we need both here.

2023-02-16 02:27 UTC, dipikabh approved these changes

2023-02-16 02:33 UTC, dipikabh commented
- PR test is failing here:
    > error: FixableError: files/en-us/web/css/filter_effects/george_floyd_memorial_sm.jpg can be removed, because it is not mentioned in files/en-us/web/css/filter_effects/index.md

- The updates look good to me, so approved. I guess the changes in css-examples will take a while to show up.

- Not a blocker for this pull request, but in general, I am not feeling so sure about the heading “Related concepts” any more. The list of properties, data types, functions in the "Related concepts" section are “Related” to the current module page but they're not really “concepts”. A concept topic would be something guide’y. The list in this section, on the other hand, are just links to related reference pages.
Would it be better to call the heading “Related references”?

2023-02-16 07:09 UTC, merged