Fix broken "Using the User Timing API" link
mdn/content pull request #2429
Opened 2021-02-17 19:29 UTC by MasonM

On https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API, the "Using the User Timing API" link is broken

2021-02-17 19:34 UTC, sideshowbarker requested changes

2021-02-17 19:34 UTC, sideshowbarker commented on files/en-us/web/api/user_timing_api/index.html
> +<p>This document provides an overview of the <code>mark</code> and <code>measure</code> {{domxref("PerformanceEntry.entryType","performance event types")}} including the four <code>User Timing</code>
```suggestion
<p>This document provides an overview of the <code>mark</code> and <code>measure</code> {{domxref("PerformanceEntry.entryType","performance event types")}} including the four <code>User Timing</code> methods that extend the {{domxref("Performance")}} interface. For more details and example code regarding these two performance event types and the methods, see <a href="/en-US/docs/Web/API/User_Timing_API/Using_the_User_Timing_API">Using the User Timing API</a>.</p>
```

2021-02-17 19:52 UTC, sideshowbarker approved these changes

2021-02-17 19:52 UTC, merged

2021-02-17 19:53 UTC, sideshowbarker commented
Mason, thanks much for catching this and fixing it, and congrats on landing your first docs change here — welcome aboard 🎉

2021-05-10 05:32 UTC, jculver050 commented
Close