Add missing MediaList subpages
mdn/content pull request #24386
Opened 2023-02-13 14:27 UTC by teoli2003

This is part of openwebdocs/project#152

Although supported by all three major engines, several methods, and properties, of the basic `MediaList` instance were not documented. This PR adds them.

Note that I have added non-live examples only as the result is not visual (and very complex as the stylesheet of the Live Sample gets in the way).

2023-02-13 21:57 UTC, dawei-wang reviewed
Various typos

2023-02-13 21:57 UTC, dawei-wang commented on files/en-us/web/api/medialist/deletemedium/index.md
> +The `deleteMedium()` method of the {{DOMxRef("MediaList")}} interface removed the media typquerye given in parameter from the list.
```suggestion
The `deleteMedium()` method of the {{DOMxRef("MediaList")}} interface removed the media type query given in parameter from the list.
```

2023-02-13 21:57 UTC, dawei-wang commented on files/en-us/web/api/medialist/index.md
> +  - : A getter that returns a string representing a media query as text, given the media query's index value inside the `MediaList`. This methods can also be called using the bracket (`[]`) syntax.
```suggestion
  - : A getter that returns a string representing a media query as text, given the media query's index value inside the `MediaList`. This method can also be called using the bracket (`[]`) syntax.
```

2023-02-13 21:57 UTC, dawei-wang commented on files/en-us/web/api/medialist/length/index.md
> +The read-only **`length`** property of the {{DOMxRef("MediaList")}} interface returns the number of media queries in the list
```suggestion
The read-only **`length`** property of the {{DOMxRef("MediaList")}} interface returns the number of media queries in the list.
```

2023-02-13 21:57 UTC, dawei-wang commented on files/en-us/web/api/medialist/appendmedium/index.md
> +The `appendMedium()` method of the {{DomxRef("MediaList")}} interface add a media query to the list. If the media query is already in the collection, this method does nothing.
```suggestion
The `appendMedium()` method of the {{DomxRef("MediaList")}} interface adds a media query to the list. If the media query is already in the collection, this method does nothing.
```

2023-02-13 21:57 UTC, dawei-wang commented on files/en-us/web/api/medialist/deletemedium/index.md
> +`MediaList` associated with the first stylesheet applied to the current document.
```suggestion
The following removes the media query `print` from the
`MediaList` associated with the first stylesheet applied to the current document.
```

2023-02-14 00:18 UTC, wbamberg requested changes
Thanks @teoli2003 ! A few little comments. Obviously, @dawei-wang 's comments are good too 👍 .

2023-02-14 00:18 UTC, wbamberg commented on files/en-us/web/api/medialist/item/index.md
> +If there is no entry for the given index, and using the bracket (`[]`) syntax, `undefined` is returned.
```suggestion
If the bracket (`[]`) syntax is used and there is no entry for the given index, `undefined` is returned.
```

(just a suggestion that IMO reads a little better)

2023-02-14 05:22 UTC, teoli2003 commented on files/en-us/web/api/medialist/deletemedium/index.md
> +The `deleteMedium()` method of the {{DOMxRef("MediaList")}} interface removed the media typquerye given in parameter from the list.
```suggestion
The `deleteMedium()` method of the {{DOMxRef("MediaList")}} interface removes from this `MediaList` the given media query.
```

2023-02-14 17:24 UTC, wbamberg approved these changes
👍 thank you!

2023-02-14 17:24 UTC, merged