Add DocumentFragment.getElementById()
mdn/content pull request #24449
Opened 2023-02-15 08:27 UTC by teoli2003

This is part of openwebdocs/project#152

Added the missing method, and slightly improved its counterpart on Document.

2023-02-15 19:37 UTC, wbamberg commented
Taking a look.

2023-02-15 20:40 UTC, dawei-wang reviewed
A couple of grammatical edits

2023-02-15 20:40 UTC, dawei-wang commented on files/en-us/web/api/document/getelementbyid/index.md
> +  - : The ID of the element to locate. The ID is case-sensitive string which is unique within the document; only one element should have any given ID.
```suggestion
  - : The ID of the element to locate. The ID is a case-sensitive string which is unique within the document; only one element should have any given ID.
```

2023-02-15 20:40 UTC, dawei-wang commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +Durian is initially the only entry of this list. The other list items have been
```suggestion
Durian is initially the only entry in this list. The other list items have been
```

2023-02-17 01:16 UTC, wbamberg requested changes

2023-02-17 01:16 UTC, wbamberg commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +### HTML
These are kind of picky comments, because this example does work fine and illustrate what it wants to. So please feel free to ignore, or use whatever parts you want to.

The behavior of this example isn't very easy to understand, and there is a lot of code to read - almost 100 lines.

I think with examples like this where we are basically showing state changes, it's better to make them more interactive, so the reader can see the current state and move on to the next state. Otherwise by the time the page is loaded, the whole story is told and I have to piece together what happened.

So maybe consider:
- 3 buttons:
    - one labeled something like "Find elements" that looks for find Apple and Durian in the document fragment and document, and logs the results
    - one labeled "Add fragment to document" that adds the fragment
    - one labeled "Reset" that reloads the iframe, so the reader can try again

That way it's easier to understand the initial state and how the state changes when we add the fragment.

It's also I think preferable to include explanatory text in prose, outside the example, rather than inside (for example, it means people who have dark theme for readability will get the benefit of that.

Finally, the code that logs the results is quite verbose:

```js
output.append(document.createElement("br"));
output.append(
  document.createTextNode(
    `Found Apple in the fragment? ${
      fragment.getElementById("Apple") ? "Yes" : "No"
    }`
  )
```

...and this contributes to this example looking long. This is really just framework code (i.e. it's not an essential part of the example) so it is distracting. In similar cases I make the output a `<pre>` and just do:

```js
output.textContent +=  `Found Apple in the fragment? ${
      fragment.getElementById("Apple") ? "Yes" : "No"
    }\n`
```

(e.g. https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#bubbling_example)

2023-02-17 01:16 UTC, wbamberg commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +- {{domxref("DocumentFragment.querySelector()")}} and {{domxref("DocumentFragment.querySelectorAll()")}}for selectors via queries like `'div.myclass'`
```suggestion
- {{domxref("DocumentFragment.querySelector()")}} and {{domxref("DocumentFragment.querySelectorAll()")}} for selectors via queries like `'div.myclass'`
```

2023-02-17 08:52 UTC, teoli2003 commented on files/en-us/web/api/document/getelementbyid/index.md
> +_Elements not in the document_ are not searched by `getElementById()`. When creating an element and assigning it an ID, you have to insert the element into the document tree with {{domxref("Node.inse
```suggestion
Elements not in the document are not searched by `getElementById()`. When creating an element and assigning it an ID, you have to insert the element into the document tree with {{domxref("Node.insertBefore()")}} or a similar method before you can access it with `getElementById()`:
```

2023-02-17 08:52 UTC, teoli2003 commented on files/en-us/web/api/document/getelementbyid/index.md
> +In _non-HTML documents, the DOM implementation must have information that says which attributes are of type ID. Attributes with the name "id" are not of type ID unless so defined in the document's DT
```suggestion
In non-HTML documents, the DOM implementation must have information on which attributes are of type ID. Attributes with the name "id" are not of type ID unless so defined in the document's DTD. The `id` attribute is defined to be of ID type in the common cases of [XHTML](/en-US/docs/Glossary/XHTML), XUL, and others. Implementations that do not know whether attributes are of type ID or not are expected to return `null`.
```

2023-02-20 10:45 UTC, teoli2003 commented
Note to self here: I need to improve the example per Will's comment.

2023-03-27 08:56 UTC, teoli2003 commented
@wbamberg Is the example better this way?

2023-03-29 02:58 UTC, wbamberg commented
I'm not sure what this example is supposed to say. In the old example, I think, we did:

1. Create Durian in the doc, and a fragment containing Apple: now Durian is in the doc, and Apple is in a fragment
2. Append the fragment to the doc: now Apple and Durian are both in the doc, and neither are in the fragment

So I think this is showing me:

- that I can use `documentFragment.getElementById()` to find elements in the fragment
- that once I've added the fragment to the document, the elements are no longer in the fragment(?)

But in this version, we don't call `documentFragment.getElementById()` at all, we:

1. Create Cherry in the doc
2. On "Add fragment to document", create a fragment and add it to the doc

So after (1), we only have Cherry, after it we have Cherry and Apple. This doesn't show me anything about `documentFragment.getElementById()`.

2023-03-29 03:19 UTC, wbamberg commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +```
````suggestion
```html
<button id="find">Find elements</button>
<button id="add">Add fragment to document</button>
<button id="reset">Reset example</button>
<div id="basket">
  Basket content:
  <ul>
    <li id="Cherry">Cherry</li>
  </ul>
</div>

Console:
<pre id="log"></pre>
```

```css hidden
#basket {
  margin: 10px 0;
}
````

(just a suggestion, but I think it would look much nicer to have the buttons in a row at the top, in the order in which we expect people might click them)

2023-03-29 03:19 UTC, wbamberg commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +This example creates a list with one element, `Cherry`, while a `Find elements` button will look for `Apple` and `Cherry` and logs it. The button `Add fragment to document` will insert four extra ele
Like I say, I'm not sure what this example is intended to show.

But I think it is worth spelling things out:
- what the example contains
- what users can do
- what they will see
- why they will see it

For example, from the previous version of this we could say something like:

> The document contains a list of fruit. Initially this list contains a single item "Durian". We create a `DocumentFragment` object containing four more fruits, "Apple", "Orange", "Banana", and "Melon".
>
> If you click "Find elements", we use `getElementById()` to look for "Durian" and "Apple" in both the document and the fragment. We find "Durian" in the document and "Apple" in the fragment.
>
> If you click "Add fragment to document", we add the fragment to the list in the document.
>
> Now, if you click "Find elements" again, we find both "Durian" and "Apple" in the document, and neither of them in the fragment. This is because appending a fragment to a document moves the fragment's nodes into the DOM, leaving behind an empty `DocumentFragment`.

2023-03-29 03:19 UTC, wbamberg commented on files/en-us/web/api/documentfragment/getelementbyid/index.md
> +});
```suggestion
const resetButton = document.getElementById("reset");
  document.location.reload();
});
```

This is what I usually do here.

2023-03-29 07:40 UTC, teoli2003 commented
Yes, I forgot about the fragment (!).

So I rewrote the example:
- The buttons are on a single line at the top in the order of expected click
- There is a pseudo-console at the bottom listing the results of the different `getElementById()` calls. There is no button to log, it is called after a click on the buttons. (It is always up-to-date)
- I have two lists: one is the ul and the other is the fragment viewer.

The code is shorter (but logging is still a significant part of it)

2023-03-29 17:03 UTC, wbamberg approved these changes
This looks great to me, thank you! I had a suggestion to expand the description a bit.

2023-03-29 17:38 UTC, merged

2023-03-29 17:38 UTC, teoli2003 commented
Thank you for the thorough reviews!