Add Request.signal
mdn/content pull request #24465
Opened 2023-02-15 16:24 UTC by teoli2003

This is part of openwebdocs/project#152

I added:
- a new `Request.signal`
- an entry in the list of properties on `Request`.

The example is not live as it would need a server.

2023-02-15 20:21 UTC, dawei-wang reviewed
A couple of typos

2023-02-15 20:21 UTC, dawei-wang commented on files/en-us/web/api/request/signal/index.md
> +The read-only **`signal`** property of the {{DOMxRef("Request")}} interface return the {{domxref("AbortSignal")}} associated with the request.
```suggestion
The read-only **`signal`** property of the {{DOMxRef("Request")}} interface returns the {{domxref("AbortSignal")}} associated with the request.
```

2023-02-15 20:21 UTC, dawei-wang commented on files/en-us/web/api/request/signal/index.md
> +// Creatae a request we this controller's AbortSignal object
```suggestion
// Create a request with this controller's AbortSignal object
```

2023-02-16 04:49 UTC, wbamberg requested changes
Looks great except for the comments already made by @dawei-wang :)

(let me know of you would prefer me to just push the suggestions and merge the PR, in cases like this.)

2023-02-16 04:56 UTC, Josh-Cena commented on files/en-us/web/api/request/signal/index.md
> +req.signal.addEventListener("signal",  () => { console.log('abort'); }
```suggestion
req.signal.addEventListener("signal", () => {
  console.log("abort");
});
```

2023-02-16 05:59 UTC, teoli2003 commented
> (let me know of you would prefer me to just push the suggestions and merge the PR, in cases like this.)

I like to see the grammar errors (or typos) so I can learn from them. But no worry either way.

2023-02-16 06:31 UTC, wbamberg approved these changes

2023-02-16 06:32 UTC, merged