Add WorkerNavigator.mediaCapabilities
mdn/content pull request #24484
Opened 2023-02-16 10:50 UTC by teoli2003

Part of openwebdocs/project#152

- Adds `WorkerNavigator.mediaCapabilities`
- List it in `WorkerNavigator`
- Remove bogus syntax box in `Navigator.mediaCapabilities`

2023-02-16 23:13 UTC, hamishwillee requested changes

2023-02-16 23:13 UTC, hamishwillee commented on files/en-us/web/api/navigator/mediacapabilities/index.md
> +The read-only **`mediaCapabilities`** property of the {{domxref("Navigator")}} interface
The original format is better, and is used in a standard way across MDN.
There is a link to the parent in the breadcrumb too.

2023-02-16 23:13 UTC, hamishwillee commented on files/en-us/web/api/workernavigator/mediacapabilities/index.md
> +The **`mediaCapabilities`** read-only property of the {{domxref("WorkerNavigator")}} interface
Same as above - context of the interface is clear from the breadcrumb. 

I don't _think_ we ever distinguish these in the text, or need to.

2023-02-17 05:33 UTC, teoli2003 commented on files/en-us/web/api/navigator/mediacapabilities/index.md
> +The read-only **`mediaCapabilities`** property of the {{domxref("Navigator")}} interface
```suggestion
The **`Navigator.mediaCapabilities`** read-only property
```

2023-02-17 05:34 UTC, teoli2003 commented on files/en-us/web/api/workernavigator/mediacapabilities/index.md
> +The **`mediaCapabilities`** read-only property of the {{domxref("WorkerNavigator")}} interface
```suggestion
The read-only **`WorkerNavigator.mediaCapabilities`** property
```

2023-02-20 01:19 UTC, hamishwillee approved these changes
Looks great.

2023-02-20 01:19 UTC, merged