docs(CSS): Clarify style() container query support, simplify examples
mdn/content pull request #24481
Opened 2023-02-16 08:46 UTC by bsmth

Fixes #24458

__Changes:__
* Simplify examples:
  * use `.post` instead of `.container` for disambiguation as "container" is overused
  * Remove images for simplicity
* Remove `style()` queries from examples
* Use `.svg` for illustration instead og `.png`

2023-02-16 08:47 UTC, bsmth commented on files/en-us/web/css/@container/index.md
> +Given the following HTML example which is a card component with a title, and some text:
```suggestion
Given the following HTML example which is a card component with a title and some text:
```

2023-02-17 03:50 UTC, dipikabh requested changes
Thanks for these updates and simplifications, @bsmth!
I've added some edit suggestions.

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
> +
How about removing this section altogether for now and documenting the style container queries only after they're supported in browsers?

Perhaps a note can be added along with the value description for `<container-condition>` that only size-based container queries are supported at the moment.

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
> +Given the following HTML example which is a card component with a title and some text:
How about:

```suggestion
Consider the following example of a card component with a title and some text:
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
>  A container context can be created using the `container-type` property:
```suggestion
A container context can be created using the `container-type` property, as shown below:
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
> +The following example will apply styles to the `.card` element if it's in a container that is wider than 400px:
Edit suggestion to indicate that this is still part of the same example:

```suggestion
You can then use the `@container` at-rule to apply styles to an element with the `.card` class if the element is in a container that's wider than `400px`.
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
>  ```
This does not seem to be used in this example. Is this needed here?
Maybe it can be removed since it will be demo'd in the next example section on "Named container contexts".

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
>  First create a container context using `container-type`, add the `container-name` property.
```suggestion
First, create a container context using the `container-type` and `container-name` properties.
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
>  You can then target that container by adding the name to the container query:
```suggestion
Next, target that container by adding the name to the container query:
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
> +The following query evaluates to true and applies a style to child elements if the container named `card` is wider than 400px and it has an ancestor container that has a width greater than 800px:
```suggestion
The following query evaluates to true and applies the declared style if the container named `summary` is wider than `400px` and has an ancestor container wider than `800px`:
```

would it be the child element? I guess it the style would be applied to whatever selector is declared in `<stylesheet>`.

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/css_container_queries/index.md
> +If a container has less available space in the surrounding context, you can hide certain elements or use smaller fonts, for example.
```suggestion
Container queries enable you to apply styles to an element based on the size of the element's container. If, for example, a container has less space available in the surrounding context, you can hide certain elements or use smaller fonts.
Container queries are an alternative to [media queries](/en-US/docs/Web/CSS/Media_Queries), which apply styles to elements based on viewport size or other device characteristics.

```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/css_container_queries/index.md
> +Take the following example which is a card component for a blog post with a title and some text:
```suggestion
Consider the following example of a card component for a blog post with a title and some text:
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/css_container_queries/index.md
> +An {{cssxref("@container")}} at-rule allows you to write a container query.
```suggestion
Next, use the {{cssxref("@container")}} at-rule to define a container query.
```

2023-02-17 03:50 UTC, dipikabh commented on files/en-us/web/css/css_container_queries/index.md
> +If there is a smaller container, the card title will be smaller, and if there is a larger container with more space available, the card title will be larger.
```suggestion
If the container with the card is narrower than `700px`, the font of the card title will be small, and if the card is in a container that's wider than `700px`, the font of the card title will be bigger.
```

2023-02-17 08:07 UTC, bsmth commented on files/en-us/web/css/@container/index.md
> +
Yeah let's remove, I agree.

2023-02-17 08:08 UTC, bsmth commented on files/en-us/web/css/@container/index.md
> +The following query evaluates to true and applies a style to child elements if the container named `card` is wider than 400px and it has an ancestor container that has a width greater than 800px:
good 👍🏻

2023-02-17 08:23 UTC, bsmth commented on files/en-us/web/css/@container/index.md
>  - `<stylesheet>`: A set of CSS declarations.
Good idea, applied in 6b8794e71358eadd9d07c814ccd6c85b40f9435c

2023-02-17 09:08 UTC, bsmth commented on files/en-us/web/css/@container/index.md
>  ```
You do need it, I've updated the example in cb9f2cde8b7dd34f1e991b604f851d3adf4cb860 to include it so it's more explicit.

2023-02-17 09:09 UTC, bsmth commented on files/en-us/web/css/css_container_queries/index.md
> +![A webpage with three card components displayed in different layouts depending on their container's size.](container-query.svg)
```suggestion
![A media query based on the viewport's width, which is the full width of the browser, and a container query based on the width of a container context, which is the width of the container element.](container-query.svg)
```

2023-02-17 09:10 UTC, bsmth commented
Thanks, Dipika 🙌🏻. I've addressed your comments if you want to have another look 👀

2023-02-17 21:32 UTC, dipikabh approved these changes
Thanks! Looks good to me 👍

2023-02-17 21:32 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
> +You can then use the `@container` at-rule to apply styles to an element with the `.card` class if the element is in a container that's narrower than `650px`.
Simplifying the second sentence for readability:

```suggestion
A container context can be created using the `container-type` property, in this case using the `inline-size` value on the `.post` class.
You can then use the `@container` at-rule to apply styles to the element with the `.card` class in a container that's narrower than `650px`.
```

2023-02-17 21:32 UTC, dipikabh commented on files/en-us/web/css/@container/index.md
>  ### Named container contexts
```suggestion
### Creating named container contexts
```

2023-02-17 21:35 UTC, merged

2023-02-20 09:09 UTC, bsmth commented
Thank you 🙌🏻