Add jsondata l10n translation for ko
mdn/content pull request #24525
Opened 2023-02-18 03:49 UTC by SnowMarble

[ mdn/translated-content#8749](https://github.com/mdn/translated-content/issues/8749) for ko

2023-02-24 03:51 UTC, yin1999 commented
/cc @mdn/yari-content-ko

2023-03-03 07:52 UTC, SnowMarble commented
@hochan222 안녕하세요, 이 pr은 어떻게 리뷰받아야 하는지 알 수 있을까요?

2023-03-03 08:05 UTC, hochan222 commented
@SnowMarble 님 안녕하세요! 팀멘션인데 제가 알림을 놓쳤었네요. 이번주 내로 리뷰 드리겠습니다 :)

2023-03-03 08:09 UTC, SnowMarble commented
넵 알겠습니다. 편한 시간에 천천히 해주세요

2023-03-04 12:50 UTC, hochan222 requested changes
LGTM for `ko-locale` :)

고생 많으셨습니다!

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-CSS.json
> +    "ko": "가상 클래스",
```suggestion
    "ko": "의사 클래스",
```

Pseudo를 "의사"하고 "가상"중에 어느것으로 번역하는 것이 좋을지 고민이 됩니다. 다른 이유가 없다면 현재 MDN 한국 페이지에서 많이 사용되고 있는 의사를 사용하는것이 좋아 보입니다.

현재 MDN 한국 문서에는 의사 클래스(34 files)가 가상 클래스(10 files)보다 더 많이 사용되고 있습니다. (의사 요소(24 files) vs 가상 요소(6 files))

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-Common.json
> +    "ko": "가이드",
```suggestion
    "ko": "안내서",
```

https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-subtitle 에 따라 안내서로 변경 부탁드립니다! (참고: https://github.com/mdn/translated-content/issues/11093#issuecomment-1411005106)

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-Common.json
> +    "ko": "이 문서는 아직 한국어로 번역되지 않았습니다. 저희와 함께 끝낼 수 있도록 도와주세요!",
May I know where these json files are used? Also, I wonder where this phrase is used. The only relevant section I know of is the page below.

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/22424891/222901351-ec5c95e3-f753-4119-81e8-707b9cac6971.png">

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-Common.json
> +    "ko": "이 문서는 아직 한국어로 번역되지 않았습니다. 저희와 함께 끝낼 수 있도록 도와주세요!",
```suggestion
    "ko": "이 문서는 아직 한국어로 번역되지 않았습니다. 저희와 함께 번역을 끝낼 수 있게 도와주세요!",
```

조금 더 자연스럽게 "번역을"을 추가하면 좋을 것 같아요!

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-SVG.json
> +    "ko": "임의의 순서로 다음 요소 중 임의의 개수:",
```suggestion
    "ko": "순서에 상관없는 다음 요소 중 임의의 개수:",
```

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-SVG.json
> +    "ko": "임의의 순서로 문자 데이터와 임의의 개수의 다음 요소:",
```suggestion
    "ko": "순서에 상관없는 문자 데이터와 임의의 개수의 다음 요소:",
```

2023-03-04 12:50 UTC, hochan222 commented on files/jsondata/L10n-SVG.json
> +    "ko": "조건적 처리 속성",
```suggestion
    "ko": "조건부 처리 속성",
```

보통 이런 상황에서 부를 많이 사용해서 제안드립니다!

2023-03-04 13:54 UTC, SnowMarble commented on files/jsondata/L10n-CSS.json
> +    "ko": "가상 클래스",
"의사"가 더 일반적으로 쓰이는것 같습니다. 👍👍

2023-03-04 14:58 UTC, yin1999 commented on files/jsondata/L10n-Common.json
> +    "ko": "이 문서는 아직 한국어로 번역되지 않았습니다. 저희와 함께 끝낼 수 있도록 도와주세요!",
They are [used in macros](https://github.com/search?q=repo%3Amdn%2Fyari%20TranslationCTA&type=code). Just search them in mdn/yari.

2023-03-04 17:53 UTC, hochan222 commented on files/jsondata/L10n-Common.json
> +    "ko": "이 문서는 아직 한국어로 번역되지 않았습니다. 저희와 함께 끝낼 수 있도록 도와주세요!",
This is what it means to migrate. I should have searched for yari first. Thank you for your reply.

`const filePath = path.join(CONTENT_ROOT, "jsondata", `${name}.json`);`

2023-03-04 17:55 UTC, hochan222 approved these changes
LGTM for `ko-locale`.

2023-03-06 16:33 UTC, bsmth approved these changes
Thanks, all. I'm going to merge this shortly, well done 🙌🏻

2023-03-06 16:33 UTC, merged

2026-07-17 05:07 UTC, skebadulla92-sys reviewed
Video