adding cookiechangeevent
mdn/content pull request #2455
Opened 2021-02-18 16:51 UTC by rachelandrew

Adds CookieChangeEvent, part of the Cookie Store API

Spec: https://wicg.github.io/cookie-store/#CookieChangeEvent

Reviewer: @jpmedley 

Joe, this is the one I mentioned on our call which extends event. It also needs BCD (I think the service worker version also needs BCD). Should I go ahead and add that?

2021-02-18 17:46 UTC, jpmedley commented
>It also needs BCD (I think the service worker version also needs BCD). Should I go ahead and add that?

I'm checking on a way that you won't need to. I'll get back to you.

2021-02-18 18:31 UTC, jpmedley requested changes

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent()</code></strong> constructor creates a new {{domxref("CookieChangeEvent")}} object which is the event type for <code>CookieChange</code> events
```suggestion
<p class="summary">The <strong><code>CookieChangeEvent()</code></strong> constructor creates a new {{domxref("CookieChangeEvent")}} object which is the event type passed to {{domxref("ServiceWorkerRegistration.oncookiechange()")}} and {{domxref("CookieStore.onchange()")}}. This constructor is called by the browser when a change event occurs.</p>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent</code></strong> interface of the {{domxref('Cookie Store')}} API dispatches events against {{domxref("CookieStore")}} objects when any cookie ch
```suggestion
<p class="summary">The <strong><code>CookieChangeEvent</code></strong> interface of the {{domxref('Cookie Store')}} API is the event type passed to {{domxref("ServiceWorkerRegistration.oncookiechange()")}} and {{domxref("CookieStore.onchange()")}} when any cookie changes have occured. A cookie change consists of a cookie and a type (either "changed" or "deleted".)</p>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent()</code></strong> constructor creates a new {{domxref("CookieChangeEvent")}} object which is the event type for <code>CookieChange</code> events
What did the spec author say about the constructor?

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +  <dt><code>eventInitDict</code>{{Optional_Inline}}</dt>
This macro is reserved for when the web developer has to chose whether to use an argument. In this case, something else determines whether this is present. What determines whether it's present? This is another question for the spec author.

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/deleted/index.html
> +<p class="summary">The <strong><code>deleted</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns the cookie that has been deleted by a <code>deleted</code> ch
```suggestion
<p class="summary">The <strong><code>deleted</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns the cookie that has been deleted by the given `CookieChangeEvent` instance.</p>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +  <dd>A {{jsxref("boolean")}} indicating whether the cookie is to be used in secure contexts only.</dd>
Copy the edit to deleted.

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent</code></strong> interface of the {{domxref('Cookie Store')}} API dispatches events against {{domxref("CookieStore")}} objects when any cookie ch
>{{domxref('Cookie Store')}} API

"API" is typically part of the overview title and hence inside the link macro.

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p>Cookies changes which will cause the <code>CookieChangeEvent</code> to be dispatched are:</p>
```suggestion
<p>Cookie changes that will cause the <code>CookieChangeEvent</code> to be dispatched are:</p>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p>Cookies changes which will cause the <code>CookieChangeEvent</code> to be dispatched are:</p>
I believe this is a difference between Am and Br English. 'That' is used with a restrictive clause and no comma. 'Which' is used with a non-restrictive clause and preceded by a comma.

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <p>A cookie which is replaced due to the insertion of another cookie with the same name, domain, and path, is ignored and does not trigger a change event.</p>
```suggestion
  <p>A cookie that is replaced due to the insertion of another cookie with the same name, domain, and path, is ignored and does not trigger a change event.</p>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>Creates a new <code>CookieChangeEvent</code> which is the event type for <code>CookieChange</code> events.</dd>
```suggestion
  <dd>Creates a new <code>CookieChangeEvent</code>.</dd>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>The <code>changed</code> property returns an object containing the changed cookie.</dd>
```suggestion
  <dd>Returns an object containing the changed cookie.</dd>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>The <code>deleted</code> property returns an object containing the deleted cookie.</dd>
```suggestion
  <dd>Returns an object containing the deleted cookie.</dd>
```

2021-02-18 18:31 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p>In this example when the cookie is set the event listener logs the event to the console. This is a <code>CookieChangeEvent</code> object with the {{domxref("CookieChangeEvent.changed","changed")}}
```suggestion
<p>In this example when the cookie is set, the event listener logs the event to the console. This is a <code>CookieChangeEvent</code> object with the {{domxref("CookieChangeEvent.changed","changed")}} property containing an object representing the cookie that has just been set.</p>
```

2021-02-19 12:52 UTC, rachelandrew commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent()</code></strong> constructor creates a new {{domxref("CookieChangeEvent")}} object which is the event type for <code>CookieChange</code> events
I'm going to ping them today.

2021-02-19 12:54 UTC, rachelandrew commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>The <code>changed</code> property returns an object containing the changed cookie.</dd>
I was making these a full sentence, because elsewhere you asked me to make things like this a complete sentence. Could you let me know what the rule is? I prefer what you have there, but elsewhere you told me not to use sentence fragments so I stopped doing so.

2021-02-19 14:41 UTC, rachelandrew commented
> > It also needs BCD (I think the service worker version also needs BCD). Should I go ahead and add that?
> 
> I'm checking on a way that you won't need to. I'll get back to you.

I also think the other interfaces are only showing up as in Chrome in BCD, they are definitely also in Edge (as I'd expect) as my demo works in Edge.

2021-02-20 09:52 UTC, rachelandrew commented
@jpmedley heard back from one of the editors and it looks as if my understanding that this is internal only is correct:

> My understanding is that the CookieChangeEvent constructor and the ExtendableCookieChangeEvent constructor are not intended for authors to call them from the webpage or ServiceWorker. They are not meant to be created and dispatched manually. The regular use case is intended to be that this event is returned by the event listener.

2021-02-22 14:45 UTC, jpmedley commented
Can you call the constructors even though you're not supposed to?

2021-02-22 16:08 UTC, jpmedley commented
I'm think now that they shouldn't be documented. I'm convinced that mdn/content could forever be playing wack-a-mole to keep these off the site. I'm pinging some folks about this and will get back to you. I won't let it hold up the PR.

2021-02-23 09:42 UTC, rachelandrew commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +  <dt><code>eventInitDict</code>{{Optional_Inline}}</dt>
I think this is probably part of the email discussions we are having so leaving for now.

2021-02-24 16:52 UTC, jpmedley requested changes
Rachel,

I owe you a favor. These changes are things I should have caught the first time around.

2021-02-24 16:52 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +
I've suggested a note the `ExtendableCookieChangeEvent` being for testing. Make to place here whatever language we agree upon.

2021-02-24 16:52 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +<p class="summary">The <strong><code>changed</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns the cookie that has been changed by the given <code>CookieCha
This like the `ExtendableCookieChangeEvent` also returns an array. Please update this PR with whatever changes you make to #2613.

2021-03-31 15:49 UTC, jpmedley requested changes

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +<p class="summary">The <strong><code>changed</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns any cookies that have been changed by the given <code>CookieC
```suggestion
<p class="summary">The <strong><code>changed</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns an array of the cookies that have been changed.</p>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +<p class="summary">The <strong><code>changed</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns any cookies that have been changed by the given <code>CookieC
Event objects are reflections of activity, not initiators of them.

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +  <dd>A {{jsxref("boolean")}} indicating whether the cookie from a site with a secure context (HTTPS rather than HTTP).</dd>
```suggestion
  <dd>A {{jsxref("boolean")}} indicating whether the cookie is from a site with a secure context (HTTPS rather than HTTP).</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +      <dd>Cookies will only be sent in a first-party context and not be sent along with requests initiated by third party websites.</dd>
```suggestion
      <dd>Cookies will only be sent in a first-party context and not be sent with requests initiated by third party websites.</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +      <dd>Cookies will only be sent in a first-party context and not be sent along with requests initiated by third party websites.</dd>
I've opened a [PR to keep this text consistent](https://github.com/mdn/content/pull/3713).

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +      <dd>Cookies are not sent on normal cross-site subrequests (for example to load images or frames into a third party site), but are sent when a user is navigating to the origin site (i.e. when fo
```suggestion
      <dd>Cookies are not sent on normal cross-site subrequests (for example to load images or frames into a third party site), but are sent when a user is navigating within the origin site (i.e. when following a link).</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +      <dd>An array containing a changed cookie.</dd>
A changed cookie or one or more changed cookies? (Did I ask this before?)

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/changed/index.html
> +<pre class="syntaxbox notranslate">var <var>array</var> = <var>CookieChangeEvent</var>.changed;</pre>
```suggestion
<pre class="syntaxbox notranslate">var array = CookieChangeEvent.changed;</pre>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +<pre class="syntaxbox">var <var>CookieChangeEvent</var> = new CookieChangeEvent(<var>type</var>,<var>eventInitDict</var>);</pre>
```suggestion
<pre class="syntaxbox">var CookieChangeEvent = new CookieChangeEvent(type,eventInitDict);</pre>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/deleted/index.html
> +<pre class="syntaxbox notranslate">var <var>array</var> = <var>CookieChangeEvent</var>.deleted;</pre>
```suggestion
<pre class="syntaxbox notranslate">var array = CookieChangeEvent.deleted;</pre>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/deleted/index.html
> +      <dd>Cookies will only be sent in a first-party context and not be sent along with requests initiated by third party websites.</dd>
```suggestion
      <dd>Cookies will only be sent in a first-party context and not be sent with requests initiated by third party websites.</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/deleted/index.html
> +      <dd>Cookies are not sent on normal cross-site subrequests (for example to load images or frames into a third party site), but are sent when a user is navigating to the origin site (i.e. when fo
```suggestion
      <dd>Cookies are not sent on normal cross-site subrequests (for example to load images or frames into a third party site), but are sent when a user is navigating within the origin site (i.e. when following a link).</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +<p class="summary">The <strong><code>CookieChangeEvent</code></strong> interface of the {{domxref('Cookie Store API')}} is the event type passed to {{domxref("CookieStore.onchange()")}} when any cook
```suggestion
<p class="summary">The <strong><code>CookieChangeEvent</code></strong> interface of the {{domxref('Cookie Store API')}} is the event type passed to {{domxref("CookieStore.onchange()")}} when any cookie changes have occured. A cookie change consists of a cookie and a type (either "changed" or "deleted").</p>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>Returns an object containing the changed cookie.</dd>
```suggestion
  <dd>Returns an array containing the changed cookie.</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/index.html
> +  <dd>Returns an object containing the deleted cookie.</dd>
```suggestion
  <dd>Returns an array containing the deleted cookie.</dd>
```

2021-03-31 15:49 UTC, jpmedley commented on files/en-us/web/api/cookiechangeevent/deleted/index.html
> +<p class="summary">The <strong><code>deleted</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns any cookies that have been deleted by the given <code>CookieC
```suggestion
<p class="summary">The <strong><code>deleted</code></strong> read-only property of the {{domxref("CookieChangeEvent")}} interface returns an array of the cookies that have been deleted by the given <code>CookieChangeEvent</code> instance.</p>
```

2021-04-01 08:33 UTC, rachelandrew commented on files/en-us/web/api/cookiechangeevent/cookiechangeevent/index.html
> +      <dd>An array containing a changed cookie.</dd>
I think you did, and I thought I had updated it. I got this PR in a mess and checked the branch out again so I think I didn't copy the change back. Have done so now.

2021-04-01 16:27 UTC, jpmedley approved these changes

2021-04-01 16:27 UTC, merged