Media elements/devices select output - a little cross linking
mdn/content pull request #24619
Opened 2023-02-20 04:10 UTC by hamishwillee

This just cross links to some permission policy docs where useful. This was review for #24387 - but docs are in a reasonably state IMO.

2023-02-20 04:41 UTC, hamishwillee commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
> +## Security requirements
@Elchi3 FYI I added "Security requirements" sections to all of these because they are gated by secure context, and in this particular case `selectAudioOutput` also permissions API, permissions policy and transient user activation.

There are quite a lot of security sections across docs, but they have many names - Security, Security requirements, Security considerations, Security and privacy etc. We should settle on one and roll it out everywhere.

2023-02-20 04:42 UTC, hamishwillee commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
> +## Security requirements
PS If you want to sanity check this, the spec is here: https://w3c.github.io/mediacapture-output/#dom-htmlmediaelement-sinkid.

2023-02-20 06:41 UTC, hamishwillee commented on files/en-us/web/api/audio_output_devices_api/index.md
> +Audio devices may arbitrarily connect and disconnect.
This paragraph is "non normative" in the spec. If I had more time to play with I'd probably put this in an example instead. Is this OK to live with?

2023-02-20 13:33 UTC, Elchi3 commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
> +## Security requirements
Yeah, I like "Security requirements" when talking about what developers have to do in order to get the feature working. 

"Security considerations" on the other hand sounds more like something the developer has to pay attention to in their code in order to stay secure.

2023-02-20 13:51 UTC, Elchi3 requested changes
LGTM overall. Some typos

2023-02-20 13:51 UTC, Elchi3 commented on files/en-us/web/api/audio_output_devices_api/index.md
> +### Extensions to other interfaces
Not sure what "other" refers to here, I guess it can go.

```suggestion
### Extensions to interfaces
```

2023-02-20 13:51 UTC, Elchi3 commented on files/en-us/web/api/audio_output_devices_api/index.md
> +User permission to set the output device is also implicitly granted if the user has already granted permission to use a media input device in the same group, using [`MediaDevices.getUserMedia()`](/en
```suggestion
User permission to set the output device is also implicitly granted if the user has already granted permission to use a media input device in the same group, using [`MediaDevices.getUserMedia()`](/en-US/docs/Web/API/MediaDevices/getUserMedia).
```

2023-02-20 13:51 UTC, Elchi3 commented on files/en-us/web/api/audio_output_devices_api/index.md
> +- The user must explicitly grant permission to use the audio output device though a user-agent specific mechanism, or have previously granted permission.
```suggestion
- The user must explicitly grant permission to use the audio output device through a user-agent specific mechanism, or have previously granted permission.
```

2023-02-20 13:51 UTC, Elchi3 commented on files/en-us/web/api/audio_output_devices_api/index.md
> +  - : This property returns the unique ID of the audio device being used for output, or an empty string the default user agent device is being used.
```suggestion
  - : This property returns the unique ID of the audio device being used for output, or an empty string if the default user agent device is being used.
```

2023-02-20 13:51 UTC, Elchi3 commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
> +- The user must explicitly grant permission to use the audio output device though a user-agent specific mechanism, or have previously granted permission.
```suggestion
- The user must explicitly grant permission to use the audio output device through a user-agent specific mechanism, or have previously granted permission.
```

2023-02-20 22:32 UTC, hamishwillee commented on files/en-us/web/api/audio_output_devices_api/index.md
> +### Extensions to other interfaces
@Elchi3 FYI Normally you have a heading interfaces, followed by sub headings for "interface 1, 2, and so on", followed last of all by the extensions to other interfaces. So this makes sense in the context of an API that has interfaces as well. I just copied the templates.

2023-02-20 22:33 UTC, hamishwillee commented on files/en-us/web/api/mediadevices/selectaudiooutput/index.md
> +## Security requirements
OK. I will keep that in mind. At some point when you have progressed this project further we should make it common across the docs. I can help :-)

2023-02-20 22:34 UTC, hamishwillee commented
Thanks @Elchi3 - accepted all your fixes.

2023-02-21 10:51 UTC, Elchi3 approved these changes
Great work! 👍

2023-02-21 10:52 UTC, merged