Adding search.query and search.search disposition
mdn/content pull request #24668
Opened 2023-02-21 01:16 UTC by rebloor

### Description

Adds documentation for the `search.query` function and the addition of the `disposition ` property to `search.search`.

### Motivation

Addresses the documentation requirements of [Bug 1804357](https://bugzilla.mozilla.org/show_bug.cgi?id=1804357) Implement chrome.search.

### Additional details

BCD for this change was previously submitted in [#18903](https://github.com/mdn/browser-compat-data/pull/18903)

2023-02-21 01:16 UTC, rebloor commented
FYI @gregorypappas

2023-02-21 07:09 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +The results are displayed in the current tab, a new tab, or a new window according to the `disposition` property or in the tab specified in the `tabId` property. If neither is specified, the results
This is wrong, search.search defaults to NEW_TAB when no tabId or disposition is supplied.
https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/search.json#84

2023-02-21 07:09 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +      - : `string`. The location where the search results are displayed. Valid values are `CURRENT_TAB`, `NEW_TAB`, and `NEW_WINDOW`. Defaults to `CURRENT_TAB`. Cannot be specified with `tabId`.
This is wrong, search.search defaults to NEW_TAB when no tabId or disposition is supplied.
https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/search.json#84

2023-02-21 07:09 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +A search using the default search engine with the results shown in the current tab (default):
This is wrong, search.search defaults to NEW_TAB when no tabId or disposition is supplied.
https://searchfox.org/mozilla-central/source/browser/components/extensions/schemas/search.json#84

2023-02-21 07:43 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +A search using the default search engine with the results shown in the current tab (default):
Thanks @gregorypappas I've fixed all of these

2023-02-21 07:55 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +A search using the default search engine with the results shown in the current tab (default):
Thanks, your changes look good. Unfortunately I'm not very good at using Github so I'm not sure how to mark my comments as 'old' or 'fixed'.

2023-02-21 21:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +A search using the default search engine with the results shown in the current tab (default):
@gregorypappas just click resolve conversation :-)

2023-02-21 23:14 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +A search using the default search engine with the results shown in the current tab (default):
I don't have permission unfortunately
> [You can resolve a conversation in a pull request if you opened the pull request or if you have write access to the repository where the pull request was opened.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations)

2023-02-26 21:02 UTC, rebloor commented
@zombie would you have a moment to review?

2023-03-02 15:33 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/111/index.md
> +- {{WebExtAPIRef("search.search")}} has been added, providing search API compatibility with Chromeum-based browsers, and the `disposition` property added to {{WebExtAPIRef("search.query")}} enabling
Thanks @gregorypappas

2023-03-03 13:30 UTC, Rob--W requested changes
The `search.search` and `search.query` methods are almost identical from the functionality perspective. The main difference is that `search.query` is cross-browser, and that `search.query` is Firefox-only and has been around for much longer AND that `search.query` offers the ability to initiate a search query with a non-default search engine (via the `engine`) property.

Could you document a comparison between the two to help readers with deciding which method to choose?

2023-03-03 18:16 UTC, Rob--W approved these changes

2023-03-03 18:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/search/search/index.md
> +      - : `string`. The name of the search engine. If the search engine name doesn't exist, the function throws an error. If this property is omitted, the default search engine is used.
Returns a rejected promise instead of (synchronously) throwing an error.

```suggestion
      - : `string`. The name of the search engine. If the search engine name doesn't exist, the function rejects the call with an error. If this property is omitted, the default search engine is used.
```

2023-03-03 21:16 UTC, merged