Document OES_draw_buffers_indexed
mdn/content pull request #24707
Opened 2023-02-21 14:56 UTC by Elchi3

### Description

This documents the WebGL extension https://registry.khronos.org/webgl/extensions/OES_draw_buffers_indexed/

### Motivation

https://github.com/openwebdocs/project/issues/152 is a project in which Open Web Docs is trying to provide docs for all web platform features supported in all three major engines (Webkit, Gecko, Chromium).

### Additional details

None.

2023-02-21 19:34 UTC, dawei-wang reviewed
A few typos

2023-02-21 19:34 UTC, dawei-wang commented on files/en-us/web/api/oes_draw_buffers_indexed/blendfuncseparateioes/index.md
> +See {{DOMxRef("OES_draw_buffers_indexed.blendFunciOES()")}} for setting RBG and alpha together and {{DOMxRef("WebGLRenderingContext.blendFuncSeparate()")}} for the WebGL 1 version of this method.
```suggestion
See {{DOMxRef("OES_draw_buffers_indexed.blendFunciOES()")}} for setting RGB and alpha together and {{DOMxRef("WebGLRenderingContext.blendFuncSeparate()")}} for the WebGL 1 version of this method.
```

2023-02-22 08:19 UTC, teoli2003 requested changes
A few nits and this is good to go!

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/blendequationseparateioes/index.md
> +The `blendEquationSeparateiOES()` method of the `OES_draw_buffers_indexed` WebGL extension sets the RGB blend equation and alpha blend equation separately for a particular draw buffer.
```suggestion
The `blendEquationSeparateiOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension sets the RGB and alpha blend equations separately for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/blendfuncioes/index.md
> +The `blendFunciOES()` method of the `OES_draw_buffers_indexed` WebGL extension defines which function is used when blending pixels for a particular draw buffer.
```suggestion
The `blendFunciOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension defines which function is used when blending pixels for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/blendfuncseparateioes/index.md
> +The `blendFuncSeparateiOES()` method of the `OES_draw_buffers_indexed` WebGL extension defines which function is used when blending pixels for RGB and alpha components separately for a particular dra
```suggestion
The `blendFuncSeparateiOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension defines which function is used when blending pixels for RGB and alpha components separately for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/colormaskioes/index.md
> +The `colorMaskiOES()` method of the `OES_draw_buffers_indexed` WebGL extension sets which color components to enable or to disable when drawing or rendering for a particular draw buffer. It's the ind
```suggestion
The `colorMaskiOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension sets which color components to enable or to disable when drawing or rendering for a particular draw buffer. It's the indexed version of WebGL 1's {{domxref("WebGLRenderingContext.colorMask()")}} method.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/disableioes/index.md
> +The `disableiOES()` method of the `OES_draw_buffers_indexed` WebGL extension enables blending for a particular draw buffer.
```suggestion
The `disableiOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension enables blending for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/enableioes/index.md
> +The `enableiOES()` method of the `OES_draw_buffers_indexed` WebGL extension enables blending for a particular draw buffer.
```suggestion
The `enableiOES()` method of the {{DOMxRef("OES_draw_buffers_indexed")}} WebGL extension enables blending for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/index.md
> +The **`OES_draw_buffers_indexed`** extension is part of the [WebGL API](/en-US/docs/Web/API/WebGL_API) and enables use of different blend options when writing to multiple color buffers simultaneously
```suggestion
The **`OES_draw_buffers_indexed`** extension is part of the [WebGL API](/en-US/docs/Web/API/WebGL_API) and enables the use of different blend options when writing to multiple color buffers simultaneously.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/index.md
> +  - : Sets both the RGB blend equation and alpha blend equation for a particular draw buffer.
```suggestion
  - : Sets both the RGB and alpha blend equations for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/index.md
> +  - : Sets the RGB blend equation and alpha blend equation separately for a particular draw buffer.
```suggestion
  - : Sets the RGB and alpha blend equations separately for a particular draw buffer.
```

2023-02-22 08:19 UTC, teoli2003 commented on files/en-us/web/api/oes_draw_buffers_indexed/blendequationioes/index.md
> +The `blendEquationiOES()` method of the `OES_draw_buffers_indexed` WebGL extension sets both the RGB blend equation and alpha blend equation for a particular draw buffer.
```suggestion
The `blendEquationiOES()` method of the `OES_draw_buffers_indexed` WebGL extension sets both the RGB blend and alpha blend equations for a particular draw buffer.
```

2023-02-22 09:37 UTC, teoli2003 approved these changes
👍 Thank you!

2023-02-22 09:37 UTC, merged