Feature detection: Replace table with subsections
mdn/content pull request #24729
Opened 2023-02-22 06:05 UTC by ferdnyc

### Description

The table of common JavaScript feature-detection methods was not (IMHO) particularly readable, squashed into too-narrow columns even at maximum width. Using vertically-stacked sections instead of table rows gives the content room to breathe.

### Motivation

Improve readability of explanations and code examples (including enabling syntax highlighting, not available inside the table).

### Additional details

* As an added benefit, the Note box regarding double-negation (`!!`) is now located immediately after the example code it refers to, instead of being placed below the entire table.
* For flow reasons, the mention of undetectable features (linking to Modernizr's list) is now part of the introduction to the JS section (before the patterns) instead of at the end.

### Related issues and pull requests

None.

2023-02-22 07:09 UTC, teoli2003 requested changes
See the first comment that explains the rationale of using a list instead of headings here. We may need a second path of review once we are happy with the structure.

2023-02-22 07:09 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
I agree the table was not great, but one problem we have now is that the next header _matchMedia_ is at the same level as the former content of the table.

Let's try to use a list:
````suggestion
- member in object
  - : Check whether a particular method or property (typically an entry point into using the API or other feature you are detecting) exists in its parent `Object`.

  Our earlier example used this pattern to detect [Geolocation](/en-US/docs/Web/API/Geolocation_API) support by testing the [`navigator`](/en-US/docs/Web/API/Navigator) object for a `geolocation` member:

  ```js
  if ("geolocation" in navigator) {
    // Access navigator.geolocation APIs
  }
  ```

- Property on element
- : Create an element in memory using {{domxref("Document.createElement()")}} and then check if a property exists on it.

  This example shows a way of detecting <a href="/en-US/docs/Web/API/Canvas_API">Canvas</a> support:

  ```js
  function supports_canvas() {
    return !!document.createElement('canvas').getContext;
  }

  if (supports_canvas()) {
    // Create and draw on canvas elements
  }
  ```

  > **Note:** The double `NOT` in the above example (`!!`) is a way to force a return value to become a "proper" boolean value, rather than a {{glossary("Truthy")}}/{{glossary("Falsy")}} value that may skew the results.

````

2023-02-22 07:09 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +Create an element in memory using {{domxref("Document.createElement()")}}, set a property to a certain value, then check to see if the value is retained. See the feature test in <a href="https://dive
(Continuing)
```suggestion
- Method on element return value

  - : Create an element in memory using {{domxref("Document.createElement()")}} and then check if a method exists on it. If it does, check what value it returns. See the feature test in [Dive into HTML Video Format detection](https://diveinto.html5doctor.com/detect.html#video-formats) for an example of this pattern.

#### Property on element retains value

Create an element in memory using {{domxref("Document.createElement()")}}, set a property to a specific value, then check to see if the value is retained. See the feature test in [Dive into HTML \<input> type detection](https://diveinto.html5doctor.com/detect.html#input-types) for an example of this pattern.
```

(The list will look better in the preview and in production, as this is one of the few extensions to GitHub-flavored Markdown that MDN uses)

2023-02-22 07:15 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> I agree the table was not great, but one problem we have now is that the next header _matchMedia_ is at the same level as the former content of the table.

Yeah, I did spot that. I had originally set up the headings as level _5_ (with an intro H4 before), which avoided **that** issue. But H5s are clearly styled for a specific purpose @ MDN (they're all-capsed, for starters), so I dropped them back to H4s. Headings did seem a little heavy for each item.

I'm comfortable with the list! It seems like a good solution. _Anything_ but that awful table is an improvement, IMHO.

2023-02-22 07:17 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
So let's commit these (I'll do it) and we will see how it looks.

2023-02-22 07:18 UTC, teoli2003 commented
Side comment: we don't like tables on MDN (they look even more awful on mobile devices), and we try to remove them little by little (but that's not always easy).

2023-02-22 07:20 UTC, teoli2003 commented
Mmmh, I made a mistake, let's correct this.

2023-02-22 07:26 UTC, teoli2003 commented
The structure looks good now. Let's do a 2nd pass, focusing on the text.

2023-02-22 07:31 UTC, teoli2003 requested changes
I modified the titles to be clearer (as it is not a table anymore they can be a bit longer)

2023-02-22 07:31 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- member in object
```suggestion
- Members of an object
```

2023-02-22 07:31 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element
```suggestion
- Properties of an element
```

2023-02-22 07:31 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +    This example shows a way of detecting <a href="/en-US/docs/Web/API/Canvas_API">Canvas</a> support:
```suggestion
    This example shows a way of detecting the [Canvas API](en-US/docs/Web/API/Canvas_API) support:
```

2023-02-22 07:31 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Method on element return value
```suggestion
- Specific return values of a method on an element
```

2023-02-22 07:31 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element retains value
```suggestion
- Retention of specific values for a property of an element
```

2023-02-22 07:34 UTC, teoli2003 commented
I let you apply the changes, and do other modifications if you see some. Then, re-request a review and I'll double-check and merge this. Thanks a lot!

2023-02-22 07:46 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +    This example shows a way of detecting <a href="/en-US/docs/Web/API/Canvas_API">Canvas</a> support:
Hm, not sure about "...the Canvas API support" — I'd go with either "Canvas API support" (no 'the') or "support for the Canvas API".

2023-02-22 07:51 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element retains value
Hm. How about "Retention of assigned value for a property of an element"? If it's an element we created, the fact that we're looking for _the value we set_ is arguably the more central point, vs. it being a specific value.

Alternate wording: "Retention of assigned property value by an element"

2023-02-22 07:52 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +    This example shows a way of detecting <a href="/en-US/docs/Web/API/Canvas_API">Canvas</a> support:
```suggestion
    This example shows a way of detecting [Canvas API](en-US/docs/Web/API/Canvas_API) support:
```

2023-02-22 07:54 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +    This example shows a way of detecting <a href="/en-US/docs/Web/API/Canvas_API">Canvas</a> support:
I went with the "no-'the'" version.

2023-02-22 08:01 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element retains value
Feel free to update it.

2023-03-02 19:48 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element retains value
```suggestion
- Retention of assigned property value by an element
```

2023-03-02 19:50 UTC, ferdnyc commented on files/en-us/learn/tools_and_testing/cross_browser_testing/feature_detection/index.md
> +- Property on element retains value
I applied the alternate wording I'd included above.

2023-03-03 05:20 UTC, teoli2003 approved these changes
👍  Yeah!

2023-03-03 05:21 UTC, merged