Update invalid examples in @charset index.md
mdn/content pull request #24769
Opened 2023-02-22 21:10 UTC by afholderman

### Description

The "invalid" definitions are identical to the initial valid one.

Note: If these docs are run through a linter it may be causing this issue. This may require an ignore of some sort if that is the case.

### Motivation

Currently the examples are confusing
### Additional details

### Related issues and pull requests

2023-02-22 22:20 UTC, teoli2003 requested changes

2023-02-22 22:20 UTC, teoli2003 commented on files/en-us/web/css/@charset/index.md
>  ```css
We need to ban the linter to fix this.

```suggestion
```css-nolint
```

2023-03-01 05:39 UTC, estelle approved these changes

2023-03-01 05:46 UTC, teoli2003 approved these changes
👍

2023-03-01 05:46 UTC, merged