Add documentation for CharacterData members
mdn/content pull request #2477
Opened 2021-02-19 12:59 UTC by g105b

The pages for all CharacterData members were missing. I am pushing the basic documentation that describes the properties, methods and their parameters.

2021-02-19 17:16 UTC, jpmedley requested changes
This looks better than the number of requested changes might suggest. It's accurate and the API itself is complete. Thank you for thinking to check the tags on the existing page.

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/deletedata/index.html
> +  <dd>is an integer representing the number of bytes from the start of the data to remove from.</dd>
```suggestion
  <dd>An integer representing the number of bytes to remove from the start of the data.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/deletedata/index.html
> +  <dd>is an integer representing the number of bytes to remove.</dd>
```suggestion
  <dd>An integer representing the number of bytes to remove.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/insertdata/index.html
> +  the existing data.
This second sentence seems redundant. Can you tell me more about what you're trying to get across?

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/insertdata/index.html
> +  <dd>The data to insert to the given CharacterData.</dd>
```suggestion
  <dd>The data to insert to the given <code>CharacterData</code>.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/insertdata/index.html
> +  <dd>The data to insert to the given CharacterData.</dd>
Interfaces and member names  should be inside <code> elements. Please do a global search and make sure I didn't miss one.

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/replacedata/index.html
> +</p>
Please rewrite this without reference to another method. This site is a reference work like a dictionary. Though it's sometimes necessary to explain one thing in terms of another, try to avoid it when you can.

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/replacedata/index.html
> +  <dd>The number of characters from the offset to replace with the provided data.</dd>
```suggestion
  <dd>The number of characters to replace with the provided data.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/replacedata/index.html
> +  <dd>The number of characters from the offset to replace with the provided data.</dd>
Doesn't seem like it adds anything, particularly when I already got this information from the previous definition.

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/replacedata/index.html
> +  <dd>The data to insert into the given CharacterData.</dd>
```suggestion
  <dd>The data to insert into the given <code>CharacterData</code>.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/substringdata/index.html
> +  <var>characterData</var>.substringData(<var>offset</var>, <var>count</var>)
```suggestion
  <var>domString</var> = <var>characterData</var>.substringData(<var>offset</var>, <var>count</var>)
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/substringdata/index.html
> +  <dd>The number of characters to extract.</dd>
```suggestion
  <dd>The number of characters to return.</dd>
```

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/substringdata/index.html
> +  <dd>The number of characters to extract.</dd>
'Extract' makes it sound like the data is removed from the existing string.

2021-02-19 17:16 UTC, jpmedley commented on files/en-us/web/api/characterdata/substringdata/index.html
> +<p>{{jsxref("undefined")}}.</p>
```suggestion
<p>A {{jsxref("DOMString")}}.</p>
```

2021-02-21 19:05 UTC, g105b commented
Thanks, I'll make these changes tomorrow. I based my changes off of existing API docs, so I guess improving the originals will be my next PR.

2021-02-22 09:48 UTC, g105b commented
@jpmedley thank you for your feedback. I've made the changes you requested.

2021-02-23 14:53 UTC, jpmedley approved these changes
Thank you for your help.

2021-02-23 14:53 UTC, merged