main
mdn/content pull request #24906
Opened 2023-02-26 13:37 UTC by Codophilia

### Description
Fixed some examples(Live Samples)

### Motivation

### Additional details

### Related issues and pull requests

2023-02-26 19:16 UTC, queengooborg requested changes
It looks like your changes contain additional (and unwanted) changes, such as reverting link changes and adding back tags.  Could you revert those changes, please?

2023-02-26 20:10 UTC, Codophilia reviewed
Unwanted **Guides** in links are removed.

2023-02-26 20:22 UTC, queengooborg submitted a review, later dismissed

2023-02-26 20:22 UTC, queengooborg commented on files/en-us/web/html/element/a/index.md
> +  - Web
Tags should be removed as well!

```suggestion
```

2023-02-26 20:28 UTC, queengooborg commented
Thank you, I'll pass it off to another for the final review!

2023-02-26 22:12 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +#### Result
Nope, this is now too shallow - not as deep as its parent.

2023-02-26 22:12 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +#### Result
```suggestion
##### Result
```

2023-02-26 22:13 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +{{EmbedLiveSample('Inaccessible, weak link text')}}
This should be at deeper level than its parent.
Also spaces between heading and content.

```suggestion
##### Result

{{EmbedLiveSample('Inaccessible, weak link text')}}
```

2023-02-26 22:14 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +{{EmbedLiveSample('Strong link text')}}
Spacing and nesting levels 
```suggestion
##### Result

{{EmbedLiveSample('Strong link text')}}
```

2023-02-26 22:14 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +{{EmbedLiveSample('Link that opens a new tab/window')}}
```suggestion
##### Result

{{EmbedLiveSample('Link that opens a new tab/window')}}
```

2023-02-26 22:14 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +{{EmbedLiveSample('Link to a non-HTML resource')}}
```suggestion
##### Result

{{EmbedLiveSample('Link to a non-HTML resource')}}
```

2023-02-26 22:16 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +{{EmbedLiveSample('Linking to telephone numbers')}}
Space between heading and content. The nesting level is fine though - parent is 3, so this is 4.

```suggestion
#### Result

{{EmbedLiveSample('Linking to telephone numbers')}}
```

2023-02-26 22:16 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
> +#### Result
Space between heading and content.
```suggestion

#### Result
```

2023-02-26 22:17 UTC, hamishwillee approved these changes
Looks good. Thank you.

2023-02-26 22:21 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
>  > **Note:** You can use `href="#top"` or the empty fragment (`href="#"`) to link to the top of the current page, [as defined in the HTML specification](https://html.spec.whatwg.org/multipage/browsing
Make linter happy
```suggestion
{{EmbedLiveSample('Linking to an element on the same page')}}

> **Note:** You can use `href="#top"` or the empty fragment (`href="#"`) to link to the top of the current page, [as defined in the HTML specification](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier).
```

2023-02-26 22:21 UTC, hamishwillee commented on files/en-us/web/html/element/a/index.md
>  `tel:` link behavior varies with device capabilities:
Make linter happy
```suggestion
{{EmbedLiveSample('Linking to telephone numbers')}}

`tel:` link behavior varies with device capabilities:
```

2023-02-27 23:53 UTC, merged

2023-02-27 23:53 UTC, hamishwillee commented
Thanks @Mehrm0 !