Add a new color customization How-to page to PWA docs
mdn/content pull request #24925
Opened 2023-02-27 15:07 UTC by captainbrosset

### Description

This PR is just one step within the larger PWA docs refresh project: https://github.com/mdn/mdn/issues/280

One of the steps we need to do in this larger project is create a new sidebar, which this PR does not do. @wbamberg is working on in https://github.com/mdn/yari/pull/8238.

This PR adds one new How to page to the PWA docs about customizing the theme and background colors of an app.

### Motivation

In the PWA docs refresh project, we agreed to create a new How to section that will contain 10 to 20 new pages about many of the features that PWAs can use. Customizing colors is an important one because choosing these colors thoughtfully can create a more coherent and engaging experience.

### Related issues and pull requests

* Parent project: https://github.com/mdn/mdn/issues/280
* Related PR: https://github.com/mdn/content/pull/24709

2023-02-27 21:30 UTC, dawei-wang reviewed
Minor typo

2023-02-27 21:30 UTC, dawei-wang commented on files/en-us/web/progressive_web_apps/how_to/colors/index.md
> +Note that on certain browsers like Safari on macOS, or Chrome on Android, the `theme-color` meta element value is used to style the browser chrome
```suggestion
Note that on certain browsers like Safari on macOS, or Chrome on Android, the `theme-color` meta element value is used to style the browser.
```

2023-02-28 09:46 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/colors/index.md
> +Note that on certain browsers like Safari on macOS, or Chrome on Android, the `theme-color` meta element value is used to style the browser chrome
Oh, I see how this can be confusing in this context. The word chrome means two things here:

1. The Google Chrome browser.
2. The UI of any browser.

I meant the latter here, but because the former is also mentioned earlier, it's kind of weird. I'll change it to "browser interface" probably.

2023-03-09 10:51 UTC, captainbrosset commented
@estelle and @wbamberg: here is a new How-to PWA PR for you to take a look when you have some time. Thanks!

2023-03-14 21:15 UTC, estelle reviewed
suggested edits and a question about whether we should be using the same value for both themecolor and background color. If the same, let's explain why that is good design practice. If not, let's change the value for background, and define both the theme and background in the second example.

Did you want to include a creampuff screen shot example?

2023-03-14 21:15 UTC, estelle commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +Note that on certain browsers like Safari on macOS, or Chrome on Android, the `theme-color` meta element value is used to style the browser UI too.
```suggestion
The [<meta>](/en-US/docs/Web/HTML/Element/meta) element, used to provide document metadata in terms of [name](/en-US/docs/Web/HTML/Element/meta#name)-value pairs, can also be used to set the theme color on a per-page basis. 

The [`theme-color`](/en-US/docs/Web/HTML/Element/meta/name/theme-color) value for the `name` attribute defines the theme color for the page on which it is set. This is different from the `theme_color` manifest member which you define only once, globally for your app.

with the name attribute giving the metadata name, and the [content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#content) attribute giving the value.

If both are set, the `theme-color` meta value overrides the `theme_color` manifest member. This lets you define a global color for your app, and override it on individual pages.

Note that for certain browsers, like Safari on macOS and Chrome on Android, the `theme-color` meta element value sets the theme color for the browser UI as well.
```

2023-03-14 21:15 UTC, estelle commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +When building Progressive Web Apps (PWAs), it's important to not only consider the appearance of the content your app displays but also the way the app appears on the user's device once the app is in
```suggestion
When building Progressive Web Apps (PWAs), it's important to not only consider the appearance of your app's content, but also the way the app appears on the user's device once the app is installed. One way to customize the window in which your app appears is by using the [`theme_color`](/en-US/docs/Web/Manifest/theme_color) and [`background_color`](/en-US/docs/Web/Manifest/background_color) [web app manifest](/en-US/docs/Web/Manifest) members.
```

2023-03-14 21:15 UTC, estelle commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +By using the `theme_color` and `background_color` members in your PWA manifest, you can create a more polished experience for your users. These small details can help make your PWA feel more like an
```suggestion
By defining the `theme_color` and `background_color` members in your PWA manifest, you can create a more polished experience for your users. These small details can help make your PWA feel more like an OS-native app, and more familiar to your users.
```

2023-03-14 22:23 UTC, wbamberg requested changes
This looks great to me, with the exception of the manifest.json errors :). But I think as a how-to this is excellent, short and focused.

2023-03-14 22:23 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +  "background_color: "peachpuff"
```suggestion
  "background_color": "peachpuff"
```

2023-03-14 22:23 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +  "theme_color: "peachpuff"
```suggestion
  "theme_color": "peachpuff"
```

2023-03-15 05:42 UTC, estelle commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +Note that on certain browsers like Safari on macOS, or Chrome on Android, the `theme-color` meta element value is used to style the browser UI too.
htmlattrxref is being deprecated i think

2023-03-16 16:48 UTC, estelle approved these changes
Looks great.

2023-03-16 16:48 UTC, estelle commented on files/en-us/web/progressive_web_apps/how_to/customize_your_app_colors/index.md
> +The [`theme-color`](/en-US/docs/Web/HTML/Element/meta/name/theme-color) value for the [`name`](/en-US/docs/Web/HTML/Element/meta/name) attribute of the {{htmlelement("meta")}} HTML element can be use
```suggestion
The [`theme-color`](/en-US/docs/Web/HTML/Element/meta/name/theme-color) value for the [`name`](/en-US/docs/Web/HTML/Element/meta/name) attribute of the {{htmlelement("meta")}} HTML element can be used to define a theme color per webpage. This is different from the `theme_color` manifest member which you define only once, globally, for your app.
```

2023-03-16 17:27 UTC, wbamberg approved these changes
🎉

2023-03-16 17:27 UTC, merged