CSS filter function: contrast()
mdn/content pull request #24990
Opened 2023-03-02 00:20 UTC by estelle

Includes 3 new examples.

2023-03-02 08:40 UTC, teoli2003 requested changes
This looks good. Two small changes.

2023-03-02 08:40 UTC, teoli2003 commented on files/en-us/web/css/filter-function/contrast/index.md
> +- [CSS filter effects](/en-us/docs/Web/CSS/filter_effects/) module
Fixing capitalization of slug (removing the flaw)
```suggestion
- [CSS filter effects](/en-US/docs/Web/CSS/Filter_Effects/) module
```

2023-03-02 08:40 UTC, teoli2003 commented on files/en-us/web/css/filter-function/contrast/index.md
>  ### Setting contrast using numbers and percentages
This should be under Examples

2023-03-03 00:55 UTC, estelle commented on files/en-us/web/css/filter-function/contrast/index.md
>  ### Setting contrast using numbers and percentages
I dont' think so. I didn't edit that part, but it's definitely explaining the parameter, not the examples that follow.

2023-03-03 02:15 UTC, estelle commented on files/en-us/web/css/filter-function/contrast/index.md
>  ### Setting contrast using numbers and percentages
i changed the parameter to values and changed the examples to pairs of values.

2023-03-03 06:29 UTC, teoli2003 commented on files/en-us/web/css/filter-function/contrast/index.md
> +- [CSS filter effects](/en-US/docs/Web/CSS/Filter_Effects/) module
```suggestion
- [CSS filter effects](/en-US/docs/Web/CSS/Filter_Effects) module
```

2023-03-03 06:29 UTC, teoli2003 approved these changes
👍

2023-03-03 06:32 UTC, merged