Revamp the storage quota and eviction documentation
mdn/content pull request #25019
Opened 2023-03-02 18:14 UTC by captainbrosset

### Description

This PR is an almost complete rewrite of the storage quota and eviction page ([current version](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria)).

The current page has a number of problems listed in issue #23557. As a summary: it is very Firefox-specific, and contains outdated information.

### Motivation

I find that web developers do not trust browsers with their data very easily. Data storage management in browsers has evolved quite a lot over the years, and keeps evolving all the time. It is getting easier to build a storage-heavy app these days.

Unfortunately, the documentation out there on the web isn't doing a great job at reassuring people, and a lot of native vs. web decisions are influence by this particular point.

### Related issues and pull requests

Fixes #23557.

2023-03-02 20:07 UTC, captainbrosset commented
@petele as the author of the web.dev article about web storage, I would love your input on this if you have some time.

2023-03-02 21:36 UTC, dawei-wang reviewed
A few grammatical edits

2023-03-02 21:36 UTC, dawei-wang commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +If, for any reasons, developers need persistent storage (e.g., when building a web app that relies on critical data that isn't persisted anywhere else), they can do so by using the {{domxref("Storage
```suggestion
If, for any reason, developers need persistent storage (e.g., when building a web app that relies on critical data that isn't persisted anywhere else), they can do so by using the {{domxref("StorageManager.persist()")}} method of the {{domxref("Storage_API", "Storage API", "", "nocode")}}.
```

2023-03-02 21:36 UTC, dawei-wang commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In Firefox, when a site chooses to use persistent storage, the user is notified with a UI popup their permission is requested.
```suggestion
In Firefox, when a site chooses to use persistent storage, the user is notified with a UI popup that their permission is requested.
```

2023-03-02 21:36 UTC, dawei-wang commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Note that research from the Chrome team shows that data is very rarely deleted by the browser (source: [Persistent storage](https://web.dev/persistent-storage/) at web.dev). If a user uses a website
```suggestion
Note that research from the Chrome team shows that data is very rarely deleted by the browser (source: [Persistent storage](https://web.dev/persistent-storage/) at web.dev). If a user uses a website regularly, there is very little chance that its stored data, even in best-effort mode, will get evicted by the browser.
```

2023-03-03 11:54 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +  Learn/JavaScript/Client-side_web_APIs/Browser_storage_limits_and_eviction_criteria
```suggestion
slug: Learn/JavaScript/Client-side_web_APIs/Browser_storage_limits_and_eviction_criteria
```

2023-03-03 13:01 UTC, estelle reviewed
Looks good. I have two questions and a few grammar suggestions.

2023-03-03 13:01 UTC, estelle commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +When an origin's data is evicted by the browser, all of its data, not parts of it, is deleted at the same time. If the origin had stored data by using IndexedDB and the Cache API for example, then bo
```suggestion
When an origin's data is evicted by the browser, all of its data, not parts of it, is deleted at the same time. If the origin had stored data by using IndexedDB and the Cache API for example, then both types of data are deleted.
```

2023-03-06 09:40 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +  Learn/JavaScript/Client-side_web_APIs/Browser_storage_limits_and_eviction_criteria
Not sure what I should do here. This change was created automatically when I used the redirect command.

2023-03-06 09:47 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +| [Origin Private File System Access API (OPFS)](https://developer.chrome.com/articles/file-system-access/#accessing-the-origin-private-file-system) | OPFS provides a file system that's private to th
Yes, that's a good idea, I'll create an issue.

2023-03-06 09:49 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +| [Origin Private File System Access API (OPFS)](https://developer.chrome.com/articles/file-system-access/#accessing-the-origin-private-file-system) | OPFS provides a file system that's private to th
Oh, we already have OPFS documented! https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#origin_private_file_system
I'll update the link here.

2023-03-06 10:19 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In private browsing mode (also called _Incognito_ in Chrome, and _InPrivate_ in Edge), stored data is deleted when the private window is closed.
I don't know for sure. It does seem to be shared in my quick test in Edge. Not sure if all browsers work the same way. It's probably best to keep this note high-level enough to apply to all browsers. The point here is that data does not persist in this mode. I'll attempt something.

2023-03-07 15:29 UTC, captainbrosset commented
@asutherland if you have some time, please do take a look at this PR and leave comments for anything that seems unclear or incorrect.

2023-03-09 16:41 UTC, captainbrosset commented
@ayuishii are you able to take a look at this PR and make sure it seems correct from the blink side of things please? I would really appreciate it. Thanks!

2023-03-09 23:11 UTC, ayuishii reviewed
Wow, thank you so much for this revamp. I really appreciate it! I have a few questions.

1. I notice that language for `per origin` is used in this doc. With the [storage partitioning](https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/#what-is-storage-partitioning) effort, this will be additionally keyed by if it is from a third-party context. In spec we call this a [storage key](https://storage.spec.whatwg.org/#storage-key). I'm not sure if its important to clarify that the quota limits are per StorageKey for Chromium or if this choice for origin was intentional with that in mind.

2. We anticipate some minor [updates](https://crbug.com/1382847) to the quota eviction logic. We don't anticipate the general LRU logic to change, but whats that best way to communicate updates when this occurs?

Besides this, I think the chromium logic is accurately represented. Thanks again!

2023-03-09 23:11 UTC, ayuishii commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +This eviction mechanism only applies to origins that are not persistent and skips over origins that have requested the user for persistent data by using {{domxref("StorageManager.persist()")}}).
WDYT about  something like: `.... and skips over origins that have been granted data persistence...`?
Only because Chromium and sounds like Safari as well, doesn't necessarily grant persistent when requested.

2023-03-10 08:50 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +This eviction mechanism only applies to origins that are not persistent and skips over origins that have requested the user for persistent data by using {{domxref("StorageManager.persist()")}}).
Sounds great, making the change.

2023-03-10 08:54 UTC, captainbrosset commented
>     1. I notice that language for `per origin` is used in this doc. With the [storage partitioning](https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/#what-is-storage-partitioning) effort, this will be additionally keyed by if it is from a third-party context. In spec we call this a [storage key](https://storage.spec.whatwg.org/#storage-key). I'm not sure if its important to clarify that the quota limits are per StorageKey for Chromium or if this choice for origin was intentional with that in mind.

Great to know. My plan, then, is to mention that Chrome may further partition an origin's data in certain cases, but to keep the rest of the article unchanged. I feel like talking about storage per origin is relatively simple to understand, and if it's what happens in 90% of the cases, then that makes things easier. 

>     2. We anticipate some minor [updates](https://crbug.com/1382847) to the quota eviction logic. We don't anticipate the general LRU logic to change, but whats that best way to communicate updates when this occurs?

Hm, I think it's ok to keep the article as it is now, and then whenever those updates land, and if they're substantial enough, then revisit this article. Now, doing so in a timely manner might be challenging. That's a problem on MDN, that docs can become outdated quickly. I'll subscribe to the bug to keep track of it, but also on your end, if you know of any changes that should be reflected in the docs, can you please file an issue and let me know? 

> Besides this, I think the chromium logic is accurately represented. Thanks again!

Thanks so much for the quick review!

2023-03-10 08:57 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In some cases, however, browsers can decide to further separate the data stored by an origin in different partitions. For example, Chrome uses [Storage Partitioning](https://developer.chrome.com/en/d
@ayuishii I made a new section to explain the _per origin_ thing and added this paragraph about storage partitioning. Let me know if you think it's correct.

2023-03-10 08:59 UTC, captainbrosset commented
@wbamberg could you please take a look at this PR please? I'm specifically interested in your thoughts regarding the placement of this article. 
It was originally inside the IndexedDB docs, which isn't correct because it applies to other technologies too. So I moved it to another place that seems more correct, because it's next to Client-side_storage.
That said, my article doesn't appear in the learn sidebar, and I don't know if I should just add an entry for it there.

2023-03-10 18:19 UTC, wbamberg commented
> @wbamberg could you please take a look at this PR please? I'm specifically interested in your thoughts regarding the placement of this article. It was originally inside the IndexedDB docs, which isn't correct because it applies to other technologies too. So I moved it to another place that seems more correct, because it's next to Client-side_storage. That said, my article doesn't appear in the learn sidebar, and I don't know if I should just add an entry for it there.

It is OK having it in Learn/JavaScript, but it's not ideal IMO. Learn as the name suggests is for people learning aspects of web development, and it is quite introductory, especially wrt Web APIs.

My initial reaction is that the underlying problem here is that MDN doesn't have a good place for Web/API docs that cut across individual Web/APIs (or even worse, across domains), and this bites us again and again. But in this case I wonder if you could keep the page as either a  part of, or a guide underneath, https://developer.mozilla.org/en-US/docs/Web/API/Storage_API  ? There seems to be quite a bit of overlap between this page and that one.

2023-03-10 18:25 UTC, ayuishii reviewed
> Hm, I think it's ok to keep the article as it is now, and then whenever those updates land, and if they're substantial enough, then revisit this article. Now, doing so in a timely manner might be challenging. That's a problem on MDN, that docs can become outdated quickly. I'll subscribe to the bug to keep track of it, but also on your end, if you know of any changes that should be reflected in the docs, can you please file an issue and let me know?

Agreed, I think this is great for now. We will file issues when we've made any updates.

Thanks again for your work!

2023-03-10 18:25 UTC, ayuishii commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In some cases, however, browsers can decide to further separate the data stored by an origin in different partitions. For example, Chrome uses [Storage Partitioning](https://developer.chrome.com/en/d
Thanks for the addition! LGTM

2023-03-10 20:49 UTC, asutherland reviewed
Thank you so much for your hard work on this.  This is a great improvement and I look forward to referring users and developers alike to the revised page!

2023-03-10 20:49 UTC, asutherland commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In some cases, however, browsers can decide to further separate the data stored by an origin in different partitions. For example, Chrome uses [Storage Partitioning](https://developer.chrome.com/en/d
Note that Firefox also partitions third-party iframe's [storage keys](https://storage.spec.whatwg.org/#storage-keys) so that it is additionally keyed by the top-level origin.

(Also, at least for cookies, I believe Webkit has been double-keying/partitioning for an extremely long time.)

I do agree that the storage key seems is probably out of scope for this document.

2023-03-10 20:49 UTC, asutherland commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers can store up to 10 MiB of local storage, and 10 MiB of session storage per origin.
I think this is supposed to be 5 for both, not 10.  This is what you had in your [article](https://patrickbrosset.com/articles/2023-01-17-web-storage/) and what's defined for the endpoints [in the storage spec](https://storage.spec.whatwg.org/#storage-endpoints) and [internally for Firefox](https://searchfox.org/mozilla-central/rev/983c039377d4e97b381e13f4c3c1680360e6f3e2/modules/libpref/init/StaticPrefList.yaml#4019-4029).

2023-03-10 20:49 UTC, asutherland commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In Firefox, the maximum storage space an origin can use is calculated as 50% of the total disk space where the profile of the user is stored, capped at 8 TiB.
As [you correctly characterized in the related issue](https://github.com/mdn/content/issues/23557#issuecomment-1451690995), the 50% is only if the user granted persistent storage via navigator.storage.persist(), and 10% is the normal number.

A possibility of rephrasing this sentence and the next:

> In Firefox, the maximum storage space an origin can use in best-effort mode is calculated as 10% of the total disk space where the profile of the user is stored, capped at 8 TiB.  In persistent mode the percentage is raised to 50%.

> For example, if the device has a 500 GiB hard drive, Firefox will allow an origin in best-effort mode to store up to 50 GiB of data.  In persistent mode, 250 GiB of data is allowed to be stored.

2023-03-10 20:54 UTC, asutherland commented
Quoting @wbamberg
> But in this case I wonder if you could keep the page as either a part of, or a guide underneath, https://developer.mozilla.org/en-US/docs/Web/API/Storage_API ? There seems to be quite a bit of overlap between this page and that one.

Oh, interesting!  I'm not sure I was aware that page got into overlapping issues; I'd only been referencing the page being updated here, but the Storage_API page is very nice too!

One thing to note for the Storage_API page is that although "box" was the correct term in the past, a decision was made to move to "bucket" to avoid colliding with CSS/layout's use of "box".

2023-03-13 09:20 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers use different storage management systems for different types of data. For example, in most browsers today, Web Storage and cookies are not managed by the same system that's used to manage In
Good point, removing this section (which I also just realized now, was duplicated)

2023-03-13 09:22 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers use different storage management systems for different types of data. For example, Web Storage and cookies are not managed by the same system that's used to manage IndexedDB and Cache in mos
Yeah, I agree that we should remove this. It doesn't really help readers understand storage better, and will rot quickly with browsers implementation changing.

2023-03-13 09:24 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Safari and most Chromium-based browsers, such as Chrome or Edge, automatically handle the permission request, and do not show any prompts to the user.
Oh, that's great to know. I didn't have this understanding. I will use your phrasing.

2023-03-13 09:37 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +> **Note:** The quotas documented below only apply to non private browser windows. In a private browser window, quotas are calculated differently and are usually much lower.
I see. In general I don't think mentioning the inner workings of browsers is very useful, since they keep on changing and it can be super complex. But sometimes they can help understand a feature better, or they can explain a different behavior in some cases.

In this particular case, the way browsers implement storage in PB windows is probably not needed. But because some browsers have lower quotas in PB, it makes sense to keep a high-level note, to help readers understand why they're seeing a different behavior between PB and non-PB.

I'll rephrase this to make it more future-proof.

2023-03-13 09:49 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers can store up to 10 MiB of local storage, and 10 MiB of session storage per origin.
Yeah, that's also what I originally thought. I did a test where I was storing long strings of `a` characters to local storage and that test successfully showed that localStorage and sessionStorage were both limited to 5.

However, after talking to Nathan Memmott on the Chromium Slack, I realized that strings were stored in UTF-16.

I then did the same test with a string of `£` characters (2 bytes) and, there again, the test showed that I could only store 5*1024*1024 of them. Meaning that the quota was actually 10, not 5. And my `a` strings were just stored in UTF-16, where each `a` char also took 2 bytes.

This is at least what happens in Blink.

2023-03-13 09:55 UTC, captainbrosset commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +In Firefox, the maximum storage space an origin can use is calculated as 50% of the total disk space where the profile of the user is stored, capped at 8 TiB.
Oh that's right. Thanks for flagging this.

2023-03-13 10:01 UTC, captainbrosset commented
> I wonder if you could keep the page as either a part of, or a guide underneath, https://developer.mozilla.org/en-US/docs/Web/API/Storage_API ? There seems to be quite a bit of overlap between this page and that one.

Great suggestion!
I think it would make sense to update the Storage_API page a bit to avoid the overlap and to link to the new page in this PR. I'll give it a try and ask for review on this.

2023-03-13 10:37 UTC, captainbrosset commented
> Oh, interesting! I'm not sure I was aware that page got into overlapping issues; I'd only been referencing the page being updated here, but the Storage_API page is very nice too!

I'm trying to update the Storage_API page and I'm wondering about this part:

```
Site storage—the data stored for a website which is managed by the Storage Standard—includes:

- [IndexedDB databases](/en-US/docs/Web/API/IndexedDB_API)
- [Cache API data](/en-US/docs/Web/API/Cache)
- [Service Worker registrations](/en-US/docs/Web/API/Service_Worker_API)
- [Web Storage API data](/en-US/docs/Web/API/Web_Storage_API) managed using {{domxref("window.localStorage")}}
- History state information saved using {{domxref("History.pushState()")}}
- [Notification data](/en-US/docs/Web/API/Notifications_API)
- Other kinds of site-accessible, site-specific data that may be maintained
```

From what @asutherland said before, while Firefox manages localStorage this way, it may not be the case in other browsers. I wonder if it's worth going into too much detail here or if this will be a pain to maintain as implementations quickly change.

Maybe rephrasing to something like this would help: "The data stored for a website which is managed by the Storage Standard usually includes IndexedDB databases and Cache API data, but may include other kind of site-accessible data such as Web Storage API data."

> One thing to note for the Storage_API page is that although "box" was the correct term in the past, a decision was made to move to "bucket" to avoid colliding with CSS/layout's use of "box".

I will rename it.

2023-03-13 10:43 UTC, captainbrosset commented
@asutherland the Storage_API page also says:

> This origin, however, has a lower quota than the other two do. It may be a less-visited site, or one known to have lower data storage requirements.

meaning that different origins may have different quotas. However, that's not what the other page I'm working on says. Is this outdated? Should it be removed you think?

2023-03-13 16:17 UTC, asutherland commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers can store up to 10 MiB of local storage, and 10 MiB of session storage per origin.
The check is the same in Firefox/Gecko.  But I think it's misleading to call that 10 MiB, because in Gecko (and it sounds like in Blink), our quota measurement and enforcement is on the string length of 5 * 1024 * 1024 code units across all keys and values, not on the actual disk usage.  Because JS uses 16-bit code units, this ends up being capable of storing 10 MiB of data.  But I think phrasing it "10 MiB" is going to lead to people making the wrong inference that they can put 10 * 1024 * 1024 code units worth of data in there.

I would suggest it's more appropriate to go into additional nuance here or to keep the 5 MiB number which is less likely to mislead.  Especially because it's easy for browsers to [accidentally](https://bugzilla.mozilla.org/show_bug.cgi?id=1681300) impose [USVString](https://mdn1.moz.one/en-US/docs/Web/API/USVString) semantics on LocalStorage values where illegal unicode sequences are replaced with U+fffd.  (Although the [Storage interface is defined in terms of DOMString](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface).)

2023-03-13 16:20 UTC, asutherland commented
Quoting @captainbrosset in https://github.com/mdn/content/pull/25019#issuecomment-1465894144
> Maybe rephrasing to something like this would help: "The data stored for a website which is managed by the Storage Standard usually includes IndexedDB databases and Cache API data, but may include other kind of site-accessible data such as Web Storage API data."

This seems good.  Especially since, in Firefox, things like history state data and notification data are not tracked by quota, but notification data could start being tracked by quota in the future.  (At least under the current standardization effort that allows quota to vary based on implementation overhead; if we move to explicitly specified usage, notifications couldn't count until we enhance the spec.)

2023-03-13 16:24 UTC, asutherland commented
Quoting @captainbrosset  in https://github.com/mdn/content/pull/25019#issuecomment-1465902388
> > This origin, however, has a lower quota than the other two do. It may be a less-visited site, or one known to have lower data storage requirements.
> 
> meaning that different origins may have different quotas. However, that's not what the other page I'm working on says. Is this outdated? Should it be removed you think?

Currently in Firefox that's not possible and (apart from navigator.storage.persist()), we're probably fairly far off from Firefox establishing per-origin quota limits based on interaction or frecency.  (And I can't speak to other browsers' beyond the docs I've previously linked in the motivating issue.)

2023-03-13 20:52 UTC, nathanmemmott commented on files/en-us/learn/javascript/client-side_web_apis/browser_storage_limits_and_eviction_criteria/index.md
> +Browsers can store up to 10 MiB of local storage, and 10 MiB of session storage per origin.
Looking at it some more, it looks like it compares the [string length * 2](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/storage/storage_area_map.cc;l=11;drc=792356842a46bf11d6db111d205a151b3ab0b467;bpv=1;bpt=1) to [10 MiB](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/dom_storage/storage_area.mojom;l=53?q=third_party%2Fblink%2Fpublic%2Fmojom%2Fdom_storage%2Fstorage_area.mojom), so effectively 5 * 1024 * 1024 code units as @asutherland said. Still this means you can only store half the amount of unicode characters over U+10000, but this might not be an important detail.

2023-03-14 09:07 UTC, captainbrosset commented
@wbamberg I moved the page as you suggested. It's now a guide in the Storage_API sidebar. In doing this, I also edited the Storage_API page which was very spec-focused and wasn't really describing what happened in browsers. It should be more correct now, and also shorter, with links to my new quota article.

Let me know what you think.

2023-03-14 22:10 UTC, wbamberg requested changes
Thanks for all the work on this!

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +To learn more, see [How browsers separate data from different websites? on the Browser storage quotas and eviction criteria page](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#
```suggestion
To learn more, see [How browsers separate data from different websites?](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#how_browsers_separate_data_from_different_websites)
```

(just a suggestion)

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +```javascript
```suggestion
```js
```

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +You can change an origin's storage bucket mode by using the {{domxref("StorageManager.persist", "navigator.storage.persist()")}} method, which requires the `"persistent-storage"` {{domxref("Permissio
FWIW feel free to use Markdown links for these cases where domxref is like this.

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +```javascript
```suggestion
```js
```

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +To learn more, see [Does browser-stored data persist? on the Browser storage quotas and eviction criteria page](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#does_browser-store
```suggestion
To learn more, see [Does browser-stored data persist?](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#does_browser-stored_data_persist).
```

(just a suggestion. Mostly it's a bit hard to distinguish section/page titles from prose "... on the ... page" when it's all a link.)

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +For more information about how much data an origin can store, see [How much data can be stored? on the Browser storage quotas and eviction criteria page](/en-US/docs/Web/API/Storage_API/Storage_quota
```suggestion
For more information about how much data an origin can store, see [How much data can be stored?](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#how_much_data_can_be_stored).
```

ditto. An alternative if you wanted both could be:

> see [How much data can be stored?](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#how_much_data_can_be_stored) on the [Browser storage quotas and eviction criteria](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria) page

...which I think is more readable.

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +Data eviction is the process by which a user agent deletes an origin's stored data. This can happen when the device used to store the data is running low on storage space for example.
```suggestion
Data eviction is the process by which a user agent deletes an origin's stored data. This can happen, for example,  when the device used to store the data is running low on storage space.
```

2023-03-14 22:10 UTC, wbamberg commented on files/en-us/web/api/storage_api/index.md
> +To learn more, see [When is data evicted? on the Browser storage quotas and eviction criteria page](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#when_is_data_evicted).
same comment again here.

2023-03-15 09:01 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +## Does browser-stored data persist?
Yeah, I'm not a big fan of question headings too. I did it because my motivation for working on this page was that web devs keep asking these exact questions. So I thought these headings would work great for them.

2023-03-15 13:39 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Note that it might not actually be possible for the origin to reach this quota because it is calculated based on the **total** disk space, not the currently available disk space. This is done for sec
Total disk space means the maximum capacity of the hard drive in your device. Basically, what it says on the box. Maybe you're using a computer that was delivered to you with a 1TB hard drive but, between the OS, various applications, and your files, you're already using 750GB of the total space. The quota is still calculated based on the 1TB max size, even if an origin wont' be able to actually use it.
Does that help understand? What do you think would make this clearer in the docs?

2023-03-15 13:41 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
It seems like it, although the bug is still open, and to be honest, I'm still confused by this group quota. Maybe @asutherland can help us understand whether we should delete this paragraph, or whether there's a way to modify it so it makes more sense to web developers.

2023-03-15 13:42 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +In browsers based on the [Chromium open-source project](https://www.chromium.org/Home/), including Chrome and Edge, an origin can store up to 60% of the total disk space.
Yes, both. I'll clarify in the docs.

2023-03-15 13:44 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +- Proactively, for origins that aren't used regularly, which happens only in Safari.
No when an origin's quota is reached, an error is thrown when the origin attempts to store more, but the existing data isn't deleted.
I will rephrase the section you quoted to avoid misunderstanding.

2023-03-15 13:46 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +- Proactively, for origins that aren't used regularly, which happens only in Safari.
In fact I can remove this part. I added a section at the end about this already "How is data evicted?".

2023-03-15 13:49 UTC, captainbrosset commented on files/en-us/web/api/storage_api/index.md
> +To learn more, see [Does browser-stored data persist? on the Browser storage quotas and eviction criteria page](/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#does_browser-store
I agree. This was vaguely inspired by a discussion with Dipika about how to create consistent links.

2023-03-15 16:28 UTC, asutherland commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
I've commented on that bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1305665#c3 to provide greater context.  The group limit remains a real thing that will cap origin storage at 10GiB and potentially cause problems for multiple origins under the same site.

I think the paragraph is likely important  and useful for now.  I can imagine the general use cases for a user reading this page to be:
- I am proactively thinking about quota and I want to understand the limits I may run into and when/how/why my data may be cleared.  In this case, I might skim over the paragraph but say "ah, okay, Firefox is going to limit me to 10 GiB".
- QA or a user in the wild is asking me why my app broke, I had them run navigator.storage.estimate() in a devtools console and it came back at ~10GiB/10GiB and I'm trying to figure out why it's those numbers.  In that case, I would be ctrl-f-ing for 10 or skimming the page to look for a number like that.

I think in both cases it's useful information.  I agree it would be better if we didn't need this paragraph, but that's a problem with the current state of things, not the paragraph.  There is higher level work related to private browsing mode support that will eventually lead to the group limit being removed which is close enough that I'm not sure we want the 10 GiB limit permanently folded into other parts of the document, but far enough off that it would be premature to remove the paragraph.  (Noting that https://bugzilla.mozilla.org/show_bug.cgi?id=1305665 will be marked fixed then and is already marked dev-doc-needed.)

2023-03-15 19:03 UTC, wbamberg commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
So does this mean that contra the previous stuff in this section  (e.g. " if the device has a 500 GiB hard drive, Firefox will allow an origin in best-effort mode to store up to 50 GiB of data. In persistent mode, 250 GiB of data is allowed to be stored") actually Firefox has a max of 10GiB, and that this is shared with other origins in the same eTLD+1 domain?

If so then I think it might be better to say something along the lines of: 

> In Firefox, the maximum allowed storage space for an origin is whichever is the smaller of:
> - 10% of the total disk size in best-effort mode, or 50% of the total disk size in persistent mode
> - a 10GiB quota which is also shared with any other origins that are part of the same eTLD+1 domain

I suppose that means folding it into other parts of the document, but it would need updating anyway, and this is much clearer (to me).

2023-03-15 19:05 UTC, wbamberg commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Note that it might not actually be possible for the origin to reach this quota because it is calculated based on the **total** disk space, not the currently available disk space. This is done for sec
That was what I guessed but I was thrown by "total disk **space**" instead of "total disk **size**". I think of "space" as being the part that's unoccupied, and size as being the whole thing, occupied and available.

Could we say "total disk size" everywhere?

2023-03-15 19:07 UTC, wbamberg commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +## Does browser-stored data persist?
Ha, thank you for doing this! I think your reasoning makes sense.

2023-03-15 20:52 UTC, wbamberg commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
I also filed this: https://github.com/mdn/content/pull/25351 since we use "eTLD+1" in a few places on MDN. I'm not sure it's the best explanation though.

2023-03-16 16:05 UTC, asutherland commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
The 10 GiB group quota is not applied to origins for which persistent storage has been granted via navigator.storage.persist(), so that would need to be accounted for.

2023-03-20 15:39 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Firefox has a second quota called _group limit_ that applies to all origins that are part of the same eTLD+1 domain. For example: `mozilla.org`, `www.mozilla.org`, and `joe.blogs.mozilla.org` are thr
Thanks for the details Andrew, and for the suggest Will. I'm making a change now.

2023-03-20 15:41 UTC, captainbrosset commented on files/en-us/web/api/storage_api/storage_quotas_and_eviction_criteria/index.md
> +Note that it might not actually be possible for the origin to reach this quota because it is calculated based on the **total** disk space, not the currently available disk space. This is done for sec
sounds good!

2023-03-20 16:12 UTC, wbamberg approved these changes
Thank you for the updates, I think this looks great.

2023-03-21 12:46 UTC, captainbrosset commented
Thanks @wbamberg, knowing that you approved this, and that both Firefox and Chromium storage experts participated actively, I feel pretty good about merging this. So I'll go ahead and press the big green button now. Thanks all for your help on this. I'm excited for this to, potentially, become the de-facto resource for web developers on this topic. Let's all collectively try to keep it as up to date as we can.

2023-03-21 12:46 UTC, merged