Filter function: brightness()
mdn/content pull request #25057
Opened 2023-03-03 22:14 UTC by estelle

This is the 3rd in the series. Revamped based on SC call feedback.

2023-03-15 21:39 UTC, dipikabh requested changes
Apologize for the delay, @estelle. I've added my feedback.

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +{{EmbedLiveSample('With_the_backdrop-filter_property','100%','280')}}
```suggestion

#### Result

{{EmbedLiveSample('Applying_brightness_using_the_backdrop_filter_property', '100%', '280')}}

In this example, the colors in the area behind the `<p>` element shift linearly. If the `backdrop-filter` property was set to `brightness(0%)`, the `<div>` area with the `<p>` element would have been black and hidden the image behind. At `brightness(100%)`, the `<div>` area color would be the same as the input `#d4d5b2`, and the image behind would be completely transparent. With the brightness set to `150%` as in this example, the colors in the image behind are getting hidden by the brightness of the `<div>` element.`
```

- How about unhiding the html code? That way readers will be able to view the source `<p>` element on which the property and the function are being applied.
- I've added some explanation after the result to explain what would happen with other brightness values. Feel free to rewrite for technical accuracy.
- I edited the original phrase "linearly shifting the colors of area behind the `<p>`" to "the colors in the area behind the `<p>` element shift linearly". Can this be rephrased for better conveying what's happening, especially only in the part overlapping the image?
- An issue for another time - I did not find documentation for `/ contain` on the [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) property page although it is used in one of the interactive examples.

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +### With the filter property
```suggestion
### Applying brightness using the filter property
```

Since this is a simpler example, I would suggest to make it first of the three examples. In the previous one, the reader will have to contend with `brightness` as well as `backdrop-filter` property and that can be tricky.

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +This example applies a `brightness()` filter via the `filter` CSS property linearly color shifting the entire element, including content, border, and background image.
```suggestion
In this example, a `brightness()` filter is applied to the entire element, including content, border, and background image via the [`filter`](/en-US/docs/Web/CSS/filter) CSS property. The result shows three variations of different brightness values.
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +  filter: contrast(200%);
```suggestion
  filter: brightness(200%);
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +{{EmbedLiveSample('With_the_filter_property','100%','280')}}
because of my edit suggestion to the title...

```suggestion
{{EmbedLiveSample('Applying_brightness_using_the_filter_property','100%','280')}}
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +### With url() SVG brightness filter
```suggestion
### Applying brightness using the url() SVG brightness filter
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +The SVG {{SVGElement("filter")}} element is used to define custom filter effects that can then be referenced by {{htmlattrxref("id")}}. The `<filter>`'s {{SVGElement("feComponentTransfer")}} primitiv
```suggestion
The SVG {{SVGElement("filter")}} element is used to define custom filter effects that can then be referenced by {{htmlattrxref("id")}}. The `<filter>` element's {{SVGElement("feComponentTransfer")}} primitive enables pixel-level color remapping.

In this example, to create a filter that darkens the content on which it is applied by 25% (i.e., 75% of the original brightness), the `slope` attribute is set to `0.75`. We can then reference the filter by `id`.
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +This example shows three images: the image with a `brightness()` filter function applied, the image with a similar SVG brightness function applied, and the original image for comparison:
```suggestion
In the images below, the first one has a `brightness()` filter function applied, the second one has a similar SVG brightness function applied, and the third is the original image for comparison.
```

2023-03-15 21:39 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +  - {{cssxref("filter-function/sepia", "sepia()")}}
Not touching this "See also" yet. But leaning towards - listing the filter-functions in the same list item and moving the module link to the end.

2023-03-15 23:55 UTC, estelle commented on files/en-us/web/css/filter-function/brightness/index.md
> +- [CSS filter effects](/en-US/docs/Web/CSS/filter_effects/) module
```suggestion
- [CSS filter effects](/en-US/docs/Web/CSS/filter_effects) module
```

2023-03-15 23:58 UTC, estelle commented on files/en-us/web/css/filter-function/brightness/index.md
> +{{EmbedLiveSample('With_the_backdrop-filter_property','100%','280')}}
`contain` is a value of the `background-size` property. `background` is a shorthand.

2023-03-20 13:45 UTC, dipikabh requested changes

2023-03-20 13:45 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +The **`brightness()`** [CSS](/en-US/docs/Web/CSS) {{cssxref("&lt;filter-function&gt;")}} applies a linear multiplier value on the element or input image, making the image appear brighter or darker.
```suggestion
The **`brightness()`** [CSS](/en-US/docs/Web/CSS) {{cssxref("&lt;filter-function&gt;")}} applies a linear multiplier value on an element or an input image, making the image appear brighter or darker.
```

2023-03-20 13:57 UTC, dipikabh requested changes
Just two remaining items - [unhiding the html code](https://github.com/mdn/content/pull/25057#discussion_r1137784098) and [moving the example up](https://github.com/mdn/content/pull/25057#discussion_r1137786195), that is, the example "using the filter property" before the example "using the backdrop-filter property".

Plus code fencing is missing in two places

2023-03-20 13:57 UTC, dipikabh commented on files/en-us/web/css/filter-function/brightness/index.md
> +</div>
the closing code fence for this html markdown is missing

2023-03-21 01:20 UTC, dipikabh approved these changes
Thanks for the improvements to this page 👍

2023-03-21 01:24 UTC, merged