docs(meta): Add See also section guidelines to writing style guide
mdn/content pull request #25191
Opened 2023-03-09 03:06 UTC by dipikabh

### Motivation

This [discussion](https://github.com/orgs/mdn/discussions/339) describes the existing inconsistencies across the See also sections and the proposed set of guidelines to follow from here on.

### Details of changes

- In the Writing style guide:
1. With the non-implementation of exposing H3 headings in the page TOC on the right, added a mini TOC in each of the three H2 sections "General writing guidelines", "Writing style", and "Page components".
2. Upgraded "Shortened URLs (shortlinks)" from H4 to H3 and also edited the section a bit.
3. Added the "See also section" section per the proposal in the [discussion](https://github.com/orgs/mdn/discussions/339).
4. Updated the "See also" section of the Writing style guide to comply with the new guidelines.

- In the template files:
Updated the "See also" section to refer to the guidelines in the writing style guide.

### TO DO

- [ ] Organize sub-sections in the writing style guide alphabetical order.
- [ ] Update "See also" sections in the pages used as examples in the [discussion](https://github.com/orgs/mdn/discussions/339).

2023-03-09 03:22 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- Preferred style guides: If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/)
This list still doesn't follow the new See also guide (which says titles-only), does it? ^^ I slightly prefer the original style (without a list), and I would rather change the title to "Further reading" if "See also" implies some kind of structure.

2023-03-09 08:51 UTC, teoli2003 approved these changes
Approving = expression of _my_ agreement on the new rules (But we want to wait for other reviewers' expression of approval before merging)

2023-03-10 20:37 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- Preferred style guides: If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/)
Yeah, you're right. This "See also" section in the writing style guide is still description-heavy and kinda non-compliant with the proposed guidelines. So, good catch! I guess I missed to make it titles-only in trying to first convert the subsections into a bulleted list. But before I fix that now, I would need clarifications about your other comments:

> I slightly prefer the original style (without a list)

Did you mean in this particular case or in general for the "See also" sections elsewhere?

> I would rather change the title to "Further reading" if "See also" implies some kind of structure.

Is this specific to content in this section or in general?

Are you saying that you'd like to keep the [See also section in the writing style guide](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#see_also) as is but rename the heading to "Further reading"?

The "See also" section in the style guide should be able to exemplify the guidelines recommended in the style guide. So it would be nice to make it a bulleted list of links and retain the title.

2023-03-10 20:38 UTC, dipikabh commented
Thank you, @teoli2003!

2023-03-10 21:25 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- Preferred style guides: If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/)
Yes, my comment specifically refers to this page's See also—I agree with the guideline. I think the previous prose-like content is easy to read and also contains useful information, so making it a bulleted list seems like a net loss, apart from exemplification purposes.

2023-03-13 05:48 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
I'm going to be the minority, but I prefer "succinct where possible". Consider `@layer` linked here - as a reader and a writer, `import` tells me enough, while to me the fact that `!important` is a flag seems a little unnecessary. I mean if I know what it is then I know its a flag, and if I don't then having that information won't change my desire to click or not click it. 

![image](https://user-images.githubusercontent.com/5368500/224617295-1d73a662-b83c-47c3-90c0-83abcc6efeb5.png)

Phrases where they tell you something useful are excellent, but fewer words is better.

2023-03-13 05:48 UTC, hamishwillee approved these changes
Despite my comment https://github.com/mdn/content/pull/25191/files#r1133465543 , this is a heap better and more consistent. Approving.

2023-03-13 05:53 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
PS, and this does not match the guide. The see also section here says use bulleted list, but bulleted list says that we use bulleted list with phrase and punctuation. Here we have no punctuation.

Upshot, we should fix the example of "how to do it right" so that it does it right :-)

2023-03-14 00:43 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- Preferred style guides: If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/)
Thanks, I see your point. I've updated the section title in this case to "Further reading".

Retaining the existing descriptive info for links and not getting rid of all of it is, in general, good advice. So now there is a guideline on how to retain that info, wherever it may already exist. Please see comment below.

2023-03-14 00:44 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
Thanks for the feedback, Hamish.

- I've actually incorporated this now (I agree). I've removed the guideline about adding a descriptor for the keyword. :)

- I've added an updated version of this `@layer` example to clarify what it would look like (though I've yet to update all other examples demo'ed in the [discussion](https://github.com/orgs/mdn/discussions/339#discussioncomment-5115472).). It is also the example we're linking to in the style guide in the "See also" guideline section.

- Also, I've updated the "bulleted list" guideline in the style guide. Only complete sentences end in period. If the list item is a phrase, it will not end in a period, which is what the above `@layer` "See also" is following ([6af59ab](https://github.com/mdn/content/pull/25191/commits/6af59ab5db5cf2f58e1a40b246af18529df1b53a))

2023-03-14 00:47 UTC, dipikabh commented
After feedback from @Josh-Cena and @hamishwillee (I agree with both the comments), here's a slight tweak to the original proposal:
/cc @teoli2003 

- In case of links to reference pages, let's drop the descriptor such as keyword or property ([commit](https://github.com/mdn/content/pull/25191/commits/5bec41729dd62538da6a7823936f3b28ef4da064#diff-1ee380f9d3780e1a6b57d0fad79e98efad3d4cb206803d61554ed5a30431951c))
- In cases where there is already descriptive text, let's not remove it all. Some of it is good information. Instead, added a guideline on how to present that descriptive info:
   - `<link text>`: description phrase(no punctuation)

>   - Keep the descriptive text surrounding the link minimal. In case of a description, add it after the link text and a colon. Word the description as a phrase with no ending punctuation. Keep all linked text at the beginning to aid in scanning the list of links.
>   - **Correct**: `:checked"`, `:indeterminate`: CSS selectors for styling checkboxes

2023-03-14 01:27 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
@dipikabh I like what you've done in https://github.com/mdn/content/pull/25191#issuecomment-1467177466

I'm a little concerned with the use of the term "phrase" -it has many definitions, and a phrase can be a sentence.
Consider using the terms "single word", "incomplete sentence" and/or "topic title" or similar (i.e. a topic title might be a complete sentence, but normally we won't want to put a full stop after it - though it does not harm.

FWIW My preference (when I control the rules an open source doc set): 
1. If it is a sentence, capitalize the first letter
2. No full stops by default -  for either a sentence or a partial sentence.
3. Try avoid multiple sentences in bullet points. But if there are multiple sentences, these should be fully punctuated, including the final sentence.

This ensures that in the majority of cases there are no full stops, which is more consistent, and looks better in cases when you have lists with mixed sentences and partial sentences. The purist in me says use full punctuation everywhere, but this does not look as good, and is annoying to enforce when no one does so any more. Just my two bits.

2023-03-14 10:38 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/) or the [Chicago Manual of
Maybe we should use this instead of the AMZ link:

```suggestion
If you have questions about usage and style not covered here, we recommend referring to the [Microsoft Writing Style Guide](https://docs.microsoft.com/style-guide/welcome/) or the [Chicago Manual of Style](https://www.chicagomanualofstyle.org).
```

2023-03-14 10:52 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- [Merriam-Webster's Concise Dictionary of English Usage, 1st Edition](https://www.amazon.com/Merriam-Websters-Concise-Dictionary-English-Usage/dp/B004L2KNI2) (book link on amazon.com): Scholarly but
Not sure about this one, but Google Books looks like a good source:

```suggestion
- [Merriam-Webster's Concise Dictionary of English Usage, 1st Edition](https://www.google.com/books/edition/Merriam_Webster_s_Dictionary_of_English/2yJusP0vrdgC) (Google Books): Scholarly but user-friendly, evidence-based advice; very good for non-native speakers, especially for preposition usage
```

2023-03-14 10:58 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- [Style: The Basics of Clarity and Grace, 4th Edition](https://www.amazon.com/Style-Basics-Clarity-Grace-4th/dp/0205830765/) by Joseph Williams and Gregory Colomb (book link on amazon.com)
Another minor one instead of direct link to AMZ:

```suggestion
- [Style: The Basics of Clarity and Grace, 4th Edition](https://www.google.com/books/edition/Style/77BwcgAACAAJ) by Joseph Williams and Gregory Colomb (Google Books)
```

2023-03-14 20:02 UTC, dipikabh commented
Thanks. @bsmth. I've incorporated your feedback (https://github.com/mdn/content/pull/25191/commits/9120313d43a376149b772195dcd68321a78d03a7)

2023-03-14 21:39 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
Thanks @dipikabh - I've noted the only "annoyance" here https://github.com/mdn/content/commit/b178e108e96911f600ca51da1c62bccab5324952#r104453682

But looks fine to me! Thanks.

2023-03-15 03:22 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +In general, present the links in a See also section in a [bulleted list](#lists) format with each item in the list as a phrase. In the [Learn web development](/en-US/docs/Learn) area on MDN, however,
Thanks for sharing, @hamishwillee. I hope the response answers your concern.

I'll be opening another PR to address some of the examples I had brought up in the original discussion. We can tweak/clarify the guidelines further, if needed, as we go along.

2023-03-15 09:52 UTC, bsmth approved these changes
Thanks, @dipikabh - no other comments for me after you resolved the outdated ones. Thanks for the lift! 🎉

2023-03-16 16:03 UTC, Josh-Cena requested changes
The text looks alright to me, but its implications as manifested in the examples (https://github.com/mdn/content/pull/25380#discussion_r1138936169) worry me. So I'd like to discuss over the examples and get them merged before approving this one. In particular, any non-structured description text is going to make the list much harder to maintain and keep consistent across related pages.

2023-03-22 00:35 UTC, dipikabh commented
Thank you all for your feedback and the brainstorming to iron out the guidelines for "See also". The main points in the style guide can be viewed here: [See also guidelines](https://pr25191.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#see_also_section). @hamishwillee rightly pointed out what we say in the [bulleted lists section](https://pr25191.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#lists) should be in sync with the lists in "See also" and that's been clarified as well, hopefully.

It would be good to land this soon so we can start using the guidelines 🙂. 
cc: @Josh-Cena @hamishwillee @teoli2003

2023-03-22 11:42 UTC, Josh-Cena approved these changes
LGTM. Thanks for the work!

2023-03-22 11:42 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- If the links can be grouped by a theme, add a lead-in sentence to describe the list of links. End the lead-in sentence with a colon.
Is there an example for this?

2023-03-22 19:45 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- If the links can be grouped by a theme, add a lead-in sentence to describe the list of links. End the lead-in sentence with a colon.
This needed to be removed because of the updated guideline just before it. (https://github.com/mdn/content/pull/25191/commits/1e8d353a896a21ef910e92b96235220d7db0acb7)

2023-03-23 13:48 UTC, dipikabh commented
Thanks for the approvals and support, everyone. Merging this now.

As always, if there are still any points we want to clarify further or feel the need to add to guidelines, especially after we start complying with the guidelines (there might be more varied instances in the existing "See also" sections), we can do so in subsequent follow-up PRs.

2023-03-23 13:48 UTC, merged

2023-03-23 21:32 UTC, Josh-Cena commented
@dipikabh I was trying to apply the guideline on external see also links. I have several questions:

- Should we consistently include the author and source of the article?
- If we are quoting a chapter from a book or a section from a post, should the link text be the chapter/section title itself or something like "[Section X from XYZ](), by Aaaa (January 1, 1970)"?
- Should a live-updated book in a GitHub repo get a date?

It may help to give a few more examples on external links. For example, here are a few I attempted:

- [JavaScript Data Structures and Algorithms](https://github.com/trekhleb/javascript-algorithms) by Oleksii Trekhleb
- [Event loops](https://html.spec.whatwg.org/multipage/webappapis.html#event-loops) in the HTML standard
- [The Node.js Event Loop, Timers, and process.nextTick()](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick) in the Node.js documentation
- [JavaScript modules](https://v8.dev/features/modules) on v8.dev by Addy Osmani and Mathias Bynens (June 18, 2018)
- [ES modules: A cartoon deep-dive](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/) on Mozilla Hacks by Lin Clark (March 28, 2018)
- [ES6 in Depth: Modules](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/) on Mozilla Hacks by Jason Orendorff (August 14, 2015)
- [Chapter 16: Modules](https://exploringjs.com/es6/ch_modules.html) from Exploring ES6, Book by Axel Rauschmayer

2023-03-26 22:47 UTC, hamishwillee commented
> ...
> * Should we consistently include the author and source of the article?

These are all good questions, for which I believe we have no rules yet. 

FWIW I would normally do a list like the one above as follows:

- [JavaScript Data Structures and Algorithms](https://github.com/trekhleb/javascript-algorithms) (github.com/trekhleb)
- [Event loops](https://html.spec.whatwg.org/multipage/webappapis.html#event-loops) in the HTML standard
- [The Node.js Event Loop, Timers, and process.nextTick()](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick) in the Node.js documentation
- [JavaScript modules](https://v8.dev/features/modules) (v8.dev)
- [ES modules: A cartoon deep-dive](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/) (hacks.mozilla.org)
- [ES6 in Depth: Modules](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/) (hacks.mozilla.org)
- [Exploring ES6, Chapter 16: Modules](https://exploringjs.com/es6/ch_modules.html) by Axel Rauschmayer

Why?
- For blogs dev sites, the site url tells you the "value" if you know the site - the author does not usually tell me anything extra to help me know if the link is likely to be useful.
- For a book, I think it is good manners to do the book name and author - for a well know book the author matters.
- Naming the spec is sufficient, but generally on MDN we try avoid direct linking to spec sections for documentation.
- Not so sure on dates. In theory they are useful for noting that content is "old", but it depresses me to see a whole set of links with old dates, but still doesn't tell me that they are good or not.

All that said, I do not feel strongly about this. It just appeals to my minimalist tendencies.