New CSS Module: CSS color adjustment
mdn/content pull request #25211
Opened 2023-03-10 00:25 UTC by estelle

This module was not previously documented.

2023-03-10 07:04 UTC, teoli2003 requested changes
I made some adjustments, fixing the flaws that Yari is reporting. One question is still open, though.

2023-03-10 07:04 UTC, teoli2003 commented on files/en-us/web/css/css_color_adjustment/index.md
> +  - {{cssxref("stroke")}}
These are SVG attributes used as CSS properties. We document them under SVG/Atributes (not sure if it the right way to do in the long term, but that's the current usage), so we cannot use `{{cssxref}}`. Yari automagically fix them and raises a flaw.
```suggestion
  - [`fill`](/en-US/docs/Web/SVG/Attribute/fill)
  - [`flood-color`](/en-US/docs/Web/SVG/Attribute/flood-color)
  - [`lighting-color`](/en-US/docs/Web/SVG/Attribute/lighting-color)
  - {{cssxref("outline-color")}}
  - {{cssxref("scrollbar-color")}}
  - [`stop-color`](/en-US/docs/Web/SVG/Attribute/stop-color)
  - [`stroke`](/en-US/docs/Web/SVG/Attribute/stroke)
```

2023-03-10 17:16 UTC, dipikabh requested changes
Just one comment :)

2023-03-10 17:16 UTC, dipikabh commented on files/en-us/web/css/css_color_adjustment/index.md
> +title: CSS Color Adjustment
```suggestion
title: CSS color adjustment
```

2023-03-10 19:40 UTC, estelle commented on files/en-us/web/css/css_color_adjustment/index.md
> +- {{cssxref("color-adjust")}} shorthand
i did notice this. we don't have a color adjust page yet it seems. I was going to create the page in a different PR

2023-03-10 19:41 UTC, estelle commented on files/en-us/web/css/css_color_adjustment/index.md
> +  - {{cssxref("stroke")}}
Thank you. I didn't notice that!

2023-03-11 06:28 UTC, teoli2003 commented on files/en-us/web/css/css_color_adjustment/index.md
> +- {{cssxref("color-adjust")}} shorthand
👍

2023-03-11 06:33 UTC, teoli2003 commented
> Just one comment :)

We need to fix slugs, titles, and links to them for all modules. It is impredictable right now, which makes authoring painful.

2023-03-11 06:33 UTC, teoli2003 approved these changes

2023-03-13 15:15 UTC, dipikabh approved these changes
Thanks!

2023-03-13 15:15 UTC, merged