Update web app manifest page and add missing `file_handlers` member
mdn/content pull request #25222
Opened 2023-03-10 09:48 UTC by captainbrosset

### Description

This PR offers a minor edit pass to the web app manifest page. It was a bit outdated and I thought could be made more current and clearer.

This PR also contains ref docs for `file_handlers` which is a manifest member that allows installed PWAs to become handlers for files at the operating system level.

### Motivation

This is part of the parent PWA docs revamp project: https://github.com/mdn/mdn/issues/280

In this project, we're rewriting the PWA docs entirely. And part of it is to make sure the manifest ref docs are correct too.

### Additional details

For more information about `file_handlers`:

- Docs
  -https://developer.chrome.com/articles/file-handling/
  -https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files
- Feature tracking
  - https://chromestatus.com/feature/5721776357113856

### Related issues and pull requests

We need this BCD PR to be merged too: https://github.com/mdn/browser-compat-data/pull/19096

2023-03-10 11:35 UTC, tomayac reviewed
LGTM with some refinement nits.

2023-03-10 11:35 UTC, tomayac commented on files/en-us/web/manifest/file_handlers/index.md
> +The `file_handlers` member specifies an array of objects that represent types of files that an installed [Progressive web app (PWA)](/en-US/docs/Web/Progressive_web_apps) should handle.
```suggestion
The `file_handlers` member specifies an array of objects that represent types of files that an installed [progressive web app (PWA)](/en-US/docs/Web/Progressive_web_apps) can handle.
```

2023-03-10 11:35 UTC, tomayac commented on files/en-us/web/manifest/file_handlers/index.md
> +For example, a PWA can register to handle files that match the `text/plain` [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). Once installed, the operating system will use the
```suggestion
For example, a PWA can register to handle files that match the `text/plain` [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). Once installed, the operating system might use the PWA to handle text files.
```

2023-03-10 11:35 UTC, tomayac commented on files/en-us/web/manifest/file_handlers/index.md
> +        A required, non-empty, array of objects that map MIME types to file extensions that the PWA handles. For example: <code>{ "audio/wav": [".wav"] }</code> defines that the PWA should handle fil
```suggestion
        A required, non-empty, array of objects that map MIME types to arrays of file extensions that the PWA can handle. For example: <code>{ "audio/wav": [".wav"] }</code> defines that the PWA can handle files that have the <code>audio/wave</code> MIME type and a <code>.wav</code> file extension.
```

2023-03-10 11:35 UTC, tomayac commented on files/en-us/web/manifest/file_handlers/index.md
> +    if (launchParams.files && launchParams.files.length === 1) {
```suggestion
    if (launchParams.files && launchParams.files.length) {
```

This way the code still works and you imply there could be more than one file.

2023-03-14 22:57 UTC, estelle reviewed
the PWA content you're creating is fantastic. A few comments, questions, and suggestions

2023-03-14 22:57 UTC, estelle commented on files/en-us/web/manifest/index.md
> +PWAs are web apps that can be installed on a device without an app store. Unlike browser or home screen bookmarks, installed PWAs can work offline, use regular [Web APIs](/en-US/docs/Web/API), and in
```suggestion
PWAs are web apps that can be installed on a device without an app store. Unlike browser or home screen bookmarks, installed PWAs can work offline, can use regular [Web APIs](/en-US/docs/Web/API) while offline, and can be fully integrated into the operating system they're installed on.
```

2023-03-14 22:57 UTC, estelle commented on files/en-us/web/manifest/index.md
> +A PWA's manifest includes its name, icon(s), description, and ways that the PWA appears and integrates in the operating system where it's installed.
```suggestion
A PWA's manifest includes its [name]((/en-US/docs/Web/Manifest/name), [icon(s)](/en-US/docs/Web/Manifest/icons), [description](/en-US/docs/Web/Manifest/description), and ways that the PWA [appears](/en-us/web/progressive_web_apps/how_to/customize_your_app_colors) and integrates into the operating system where it's installed.
```

2023-03-14 22:57 UTC, estelle commented on files/en-us/web/manifest/index.md
> +A web application manifest contains a single JSON object where the top-level keys are called _members_. The members that a web application manifest can contain are listed below. Click on each one to
thank you! This definition was so needed.

2023-03-14 22:57 UTC, estelle commented on files/en-us/web/manifest/index.md
> +In some browsers and operating systems, a splash screen is displayed when an installed PWA is launched. This splash screen is auto-generated from members in the web app manifest, specifically:
```suggestion
In some browsers and operating systems, a splash screen is displayed when an installed PWA is launched. This splash screen is automatically generated with its appearance defined by members in the web app manifest, specifically:
```

2023-03-14 22:58 UTC, estelle commented on files/en-us/web/manifest/index.md
> +A PWA's manifest includes its name, icon(s), description, and ways that the PWA appears and integrates in the operating system where it's installed.
we should link to the how tos once created.

2023-03-15 01:30 UTC, estelle commented on files/en-us/web/manifest/index.md
> +A web application manifest contains a single JSON object where the top-level keys are called _members_. The members that a web application manifest can contain are listed below. Click on each one to
```suggestion
A web application manifest contains a single JSON object where the top-level keys are called _members_. The following are members that a web application manifest can contain:
```

2023-03-16 14:18 UTC, captainbrosset commented on files/en-us/web/manifest/index.md
> +A PWA's manifest includes its name, icon(s), description, and ways that the PWA appears and integrates in the operating system where it's installed.
Although our How-to pages do not have any sidebars yet. So if we link to them from visible content today, that means people will end up on page that they can't "escape" from easily (no consistent sidebar to come back to the general manifest page). Won't that be a problem?

2023-03-16 14:20 UTC, captainbrosset commented on files/en-us/web/manifest/index.md
> +In some browsers and operating systems, a splash screen is displayed when an installed PWA is launched. This splash screen is auto-generated from members in the web app manifest, specifically:
I don't think there was ever a spashscreen on desktop operating systems, there also doesn't appear to be one on iOS devices. The only place that I think ever had a splashscreen was Android. But testing just now on an emulator, I don't it exists anymore. It might have been there in previous versions, but has apparently been removed. I'll try to ask around and see if I can find out what happened there.

2023-03-16 14:50 UTC, captainbrosset commented on files/en-us/web/manifest/file_handlers/index.md
> +The `file_handlers` member is used by the browser when the PWA is installed to register the application in the operating system's file association registry.
Done.

2023-03-16 17:26 UTC, wbamberg commented on files/en-us/web/manifest/index.md
> +A PWA's manifest includes its name, icon(s), description, and ways that the PWA appears and integrates in the operating system where it's installed.
Yes, I agree that's a problem. Can we defer cross-links like this until we have the pieces and nav all in place? We can do a last pass through everything and fix up things like this then.

2023-03-16 23:37 UTC, estelle commented on files/en-us/web/manifest/index.md
> +In some browsers and operating systems, a splash screen is displayed when an installed PWA is launched. This splash screen is auto-generated from members in the web app manifest, specifically:
found references https://stackoverflow.com/questions/3877049/iphone-web-app-splash-screen-delay, - the "apple-touch-startup-image" - good to know i am not off my rocker

2023-03-17 00:22 UTC, estelle reviewed
Looks good. Two nits, and waiting to hear back if we should get rid of the splash page section.

2023-03-20 13:39 UTC, captainbrosset commented on files/en-us/web/manifest/index.md
> +In some browsers and operating systems, a splash screen is displayed when an installed PWA is launched. This splash screen is auto-generated from members in the web app manifest, specifically:
Thanks for finding this. If I understand correctly, iOS devices do generate splash screens using `link` tags in your HTML.

I have also asked on the Chromium Slack. While I haven't heard back anything super conclusive yet, it does seem that splash screens also exist on Android devices.

I will apply your suggested change in this PR, but my goal isn't to document how to make a PWA splash screen here. This would actually make a good new How-to page.

2023-03-27 18:43 UTC, wbamberg requested changes

2023-03-27 18:43 UTC, wbamberg commented on files/en-us/web/manifest/file_handlers/index.md
> +Each object in the file handler array must contain the following values (`action` and `accept` are required):
```suggestion
An array of objects. Each object in the array must contain the following values (`action` and `accept` are required):
```

2023-03-27 18:43 UTC, wbamberg commented on files/en-us/web/manifest/file_handlers/index.md
> +        A non-empty array of objects that map MIME types to arrays of file extensions that the PWA can handle. For example: <code>{ "audio/wav": [".wav"] }</code> defines that the PWA can handle file
`accept` isn't an "array of objects" though, it is an object isn't it? I would write this to be more descriptive of the syntax, like:

> An object. For each property in the object:
> - The property key is a MIME type
> - The property value is an array of strings representing file extensions associated with that MIME type.
>
> Each property declares that the associated `action` URL can handle files with the given MIME type and any of the corresponding extensions.

I'm not super happy with including an example in here but I can see how it's helpful. But it would be more readable if it were presented as a block rather than inline:

> For example, the following value indicates that the PWA can ... :
> 
> ```json
> "accept": {
>   "audio/wav": [".wav"]
> }
> ```

2023-03-28 07:44 UTC, captainbrosset commented on files/en-us/web/manifest/index.md
> +PWAs are web applications, written using web technologies, that can be installed on a device without an app store. Unlike browser or home screen bookmarks, installed PWAs can work offline, can use re
Fully agreed. Making the change now.

2023-03-28 07:48 UTC, captainbrosset commented on files/en-us/web/manifest/file_handlers/index.md
> +For example, a PWA can be registered to handle files that match the `text/plain` [MIME type](/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). Once installed, the operating system might u
I like it. Making the change.

2023-03-28 07:49 UTC, captainbrosset commented on files/en-us/web/manifest/file_handlers/index.md
> +        A string containing the URL to navigate to when a file is handled. This URL should be within the <a href="/en-US/docs/Web/Manifest/scope">scope</a> of the PWA.
All PWAs have a scope, whether they define it by using the `scope` member or not. I'll attempt to make this clearer here.

2023-03-28 08:28 UTC, captainbrosset commented on files/en-us/web/manifest/file_handlers/index.md
> +        A non-empty array of objects that map MIME types to arrays of file extensions that the PWA can handle. For example: <code>{ "audio/wav": [".wav"] }</code> defines that the PWA can handle file
Using a code block would require writing the HTML syntax for it `<pre class="..."><code>...` since this is all inside of a big HTML table. Perhaps it's better to leave the example out? We've got an example section just below anyway.

2023-03-28 16:04 UTC, wbamberg approved these changes
👍 looks great, Patrick!

2023-03-28 16:04 UTC, merged