Response.json() possible exceptions
mdn/content pull request #25237
Opened 2023-03-10 21:53 UTC by majidzeno

### Description

- Documentation for the possible exceptions that can occur when using the Response.json()

### Motivation

- Help developers handle errors more effectively.
### Additional details

- Issue #[13208](https://github.com/mdn/content/issues/13208)

### Related issues and pull requests

- Fixes #[13208](https://github.com/mdn/content/issues/13208)

2023-03-11 05:46 UTC, teoli2003 commented on files/en-us/web/api/response/json/index.md
> +
```suggestion

```

2023-03-15 22:11 UTC, majidzeno commented
@wbamberg any updates here?

2023-03-17 17:54 UTC, wbamberg commented
Thanks for your PR, @majidzeno !

I appreciate that you want this to be reviewed, but please don't do this:

> @wbamberg any updates here?

> @estelle can you review this PR 🙏 ? to close https://github.com/mdn/content/issues/13208

We get a lot of PRs to review, and the review team gets notified about every PR filed. We will get to them as soon as we can.

Pinging people individually like this just adds extra noise into our notifications and makes it harder, not easier, for us to review PRs in a timely fashion.

2023-03-17 21:19 UTC, majidzeno commented
@wbamberg Thank you for letting me know, and I'm sorry for any inconvenience I may have caused. I understand now I appreciate your feedback and will make sure not to do that again in the future. Thanks again for your time and consideration in reviewing my PR 🙏

2023-03-31 21:50 UTC, wbamberg requested changes
Sorry to be so slow to look at this, @majidzeno .

I think it would be best to keep this PR on hold until we have underlying docs for "disturbed or locked", and then update it to link to those docs.

2023-03-31 21:50 UTC, wbamberg commented on files/en-us/web/api/response/json/index.md
> +- `TypeError`
Please see https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_method_subpage_template for the formatting guidelines about documenting exceptions. In particular, they're in a description list (https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#definition_lists) and for JS exceptions should link to the JS page (e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError).

2023-03-31 21:50 UTC, wbamberg commented on files/en-us/web/api/response/json/index.md
> +  - Here is an example of how a TypeError can be thrown when using `response.json()`:
Please see https://github.com/mdn/content/issues/13208#issuecomment-1492638882 - I think it would be better to document the rules and possible errors here in one place, then link there, especially since this error is going to be common across many `Response` APIs.

Perhaps it would be best to hold this PR until we have something written up about that, and then update all the APIs?

2023-03-31 21:50 UTC, wbamberg commented on files/en-us/web/api/response/json/index.md
> +    ```
I don't think we should include these examples here. These are really just generic examples about "how to catch exceptions" and don't tell us anything about the conditions in which the exceptions happen, which is the main focus of this section.

2023-03-31 21:50 UTC, wbamberg commented on files/en-us/web/api/response/json/index.md
> +  - Other exceptions that can be thrown by `response.json()` include those that are thrown by JSON.parse() when attempting to parse the response body as JSON. These exceptions include {{jsxref("TypeE
That link only lists `SyntaxError`, which is already covered above, and that's also the only error I can see in the spec for JSON.parse(): https://tc39.es/ecma262/multipage/structured-data.html#sec-json.parse.

2024-06-05 12:50 UTC, Josh-Cena commented
Closing since it's a long time and the related sections aren't updated yet.

2024-06-05 12:50 UTC, closed without merging