Remove HTMLAttrxRef macro, part 3
mdn/content pull request #25268
Opened 2023-03-12 06:56 UTC by OnkarRuikar

- Continuing https://github.com/mdn/content/pull/25213

The PR converts two param instances to `HTML/Element` links.

2023-03-12 07:43 UTC, teoli2003 requested changes
A lot of MD links are inside HTML blocks and should be `<a>` elements. I have not pointing all of them, though.

(I will do a second pass afterwards)

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/input/tel/index.md
> +        [`size`](/en-US/docs/Web/HTML/Element/input#size)
This won't work; it is inside an html block. (We need `<a>`s)

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/input/text/index.md
> +        [`size`](/en-US/docs/Web/HTML/Element/input#size)
Ditto

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/input/time/index.md
> +        [`step`](/en-US/docs/Web/HTML/Element/input#step)
Ditto

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/input/url/index.md
> +        [`size`](/en-US/docs/Web/HTML/Element/input#size)
Ditto

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/input/week/index.md
> +        [`step`](/en-US/docs/Web/HTML/Element/input#step)
Ditto

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/object/index.md
> +        [`usemap`](/en-US/docs/Web/HTML/Element/object#usemap) attribute, <a href="/en-US/docs/Web/HTML/Content_categories#interactive_content">interactive content</a>;
Ditto

2023-03-12 07:43 UTC, teoli2003 commented on files/en-us/web/html/element/video/index.md
> +        [`controls`](/en-US/docs/Web/HTML/Element/video#controls) attribute: interactive
Ditto (I may have missed many – Can you double check?)

2023-03-12 08:35 UTC, teoli2003 requested changes
Fixing the anchors to the same page.

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/area/index.md
> +    This attribute is required only if the [`href`](/en-US/docs/Web/HTML/Element/area#href) attribute is used.
```suggestion
    This attribute is required only if the [`href`](#href) attribute is used.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/area/index.md
> +    Use this attribute only if the [`href`](/en-US/docs/Web/HTML/Element/area#href) attribute is present.
```suggestion
    Use this attribute only if the [`href`](#href) attribute is present.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/area/index.md
> +  - : For anchors containing the [`href`](/en-US/docs/Web/HTML/Element/area#href) attribute, this attribute specifies the relationship of the target object to the link object.
```suggestion
  - : For anchors containing the [`href`](#href) attribute, this attribute specifies the relationship of the target object to the link object.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/area/index.md
> +    The default relationship, if no other is given, is void. Use this attribute only if the [`href`](/en-US/docs/Web/HTML/Element/area#href) attribute is present.
```suggestion
    The default relationship, if no other is given, is void. Use this attribute only if the [`href`](#href) attribute is present.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/area/index.md
> +    Use this attribute only if the [`href`](/en-US/docs/Web/HTML/Element/area#href) attribute is present.
```suggestion
    Use this attribute only if the [`href`](#href) attribute is present.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/ol/index.md
> +  - the {{CSSxRef("line-height")}} property, to simulate the deprecated [`compact`](/en-US/docs/Web/HTML/Element/ol#compact) attribute
```suggestion
  - the {{CSSxRef("line-height")}} property, to simulate the deprecated [`compact`](#compact) attribute
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/source/index.md
> +    A list of source sizes that describes the final rendered width of the image represented by the source. Each source size consists of a comma-separated list of media condition-length pairs. This in
```suggestion
    A list of source sizes that describes the final rendered width of the image represented by the source. Each source size consists of a comma-separated list of media condition-length pairs. Before laying the page out, the browser uses this information to determine which image is defined in [`srcset`](#srcset) to use. Please note that `sizes` will have its effect only if width dimension descriptors are provided with `srcset` instead of pixel ratio values (200w instead of 2x for example).
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/thead/index.md
> +    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](/en-US/docs/Web/HTML/Element/thead#char) and [`charoff`](/en-US/docs/Web/HTML/Element/
```suggestion
    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](#char) and [`charoff`](#charoff) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/thead/index.md
> +  - : This attribute is used to set the character to align the cells in a column on. Typical values for this include a period (.) when attempting to align numbers or monetary values. If [`align`](/en
```suggestion
  - : This attribute is used to set the character to align the cells in a column on. Typical values for this include a period (.) when attempting to align numbers or monetary values. If [`align`](#align) is not set to `char`, this attribute is ignored.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/meter/index.md
> +Note that in this example the [`min`](/en-US/docs/Web/HTML/Element/meter#min) attribute is omitted. This is allowed, as it will default to `0`.
```suggestion
Note that in this example the [`min`](#min) attribute is omitted. This is allowed, as it will default to `0`.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/dir/index.md
> +  - The {{Cssxref('line-height')}} property, useful to simulate the deprecated [`compact`](/en-US/docs/Web/HTML/Element/dir#compact) attribute.
```suggestion
  - The {{Cssxref('line-height')}} property, useful to simulate the deprecated [`compact`](#compact) attribute.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/link/index.md
> +    It must be present only if the [`rel`](/en-US/docs/Web/HTML/Element/link#rel) contains a value of `icon` or a non-standard type such as Apple's `apple-touch-icon`.
```suggestion
    It must be present only if the [`rel`](#rel) contains a value of `icon` or a non-standard type such as Apple's `apple-touch-icon`.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/link/index.md
> +  - : The value of this attribute shows the relationship of the current document to the linked document, as defined by the [`href`](/en-US/docs/Web/HTML/Element/link#href) attribute.
```suggestion
  - : The value of this attribute shows the relationship of the current document to the linked document, as defined by the [`href`](#href) attribute.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/link/index.md
> +    [Link type values](/en-US/docs/Web/HTML/Attributes/rel) for the attribute are similar to the possible values for [`rel`](/en-US/docs/Web/HTML/Element/link#rel).
```suggestion
    [Link type values](/en-US/docs/Web/HTML/Attributes/rel) for the attribute are similar to the possible values for [`rel`](#rel).
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/link/index.md
> +    > **Note:** Instead of `rev`, you should use the [`rel`](/en-US/docs/Web/HTML/Element/link#rel) attribute with the opposite [link type value](/en-US/docs/Web/HTML/Attributes/rel).
```suggestion
    > **Note:** Instead of `rev`, you should use the [`rel`](#rel) attribute with the opposite [link type value](/en-US/docs/Web/HTML/Attributes/rel).
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/details/index.md
> +You can use CSS to style the disclosure widget, and you can programmatically open and close the widget by setting/removing its [`open`](/en-US/docs/Web/HTML/Element/details#open) attribute. Unfortuna
```suggestion
You can use CSS to style the disclosure widget, and you can programmatically open and close the widget by setting/removing its [`open`](#open) attribute. Unfortunately, at this time, there's no built-in way to animate the transition between open and closed.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/th/index.md
> +The **`<th>`** [HTML](/en-US/docs/Web/HTML) element defines a cell as header of a group of table cells. The exact nature of this group is defined by the [`scope`](/en-US/docs/Web/HTML/Element/th#scop
```suggestion
The **`<th>`** [HTML](/en-US/docs/Web/HTML) element defines a cell as the header of a group of table cells. The exact nature of this group is defined by the [`scope`](#scope) and [`headers`](#headers) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/th/index.md
> +    - `char` (with text only): The content is aligned to a character inside the `<th>` element with minimal offset. This character is defined by the [`char`](/en-US/docs/Web/HTML/Element/th#char) and
```suggestion
    - `char` (with text only): The content is aligned to a character inside the `<th>` element with minimal offset. This character is defined by the [`char`](#char) and [`charoff`](#charoff) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/th/index.md
> +    > - To achieve the same effect as the `char` value, give the {{cssxref("text-align")}} property the same value you would use for the [`char`](/en-US/docs/Web/HTML/Element/th#char).
```suggestion
    > - To achieve the same effect as the `char` value, give the {{cssxref("text-align")}} property the same value you would use for the [`char`](#char).
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/th/index.md
> +    > **Note:** Do not use this attribute as it is obsolete in the latest standard: use the [`scope`](/en-US/docs/Web/HTML/Element/th#scope) attribute instead.
```suggestion
    > **Note:** Do not use this attribute as it is obsolete in the latest standard: use the [`scope`](#scope) attribute instead.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/th/index.md
> +  - : The content in the cell element is aligned to a character. Typical values include a period (.) to align numbers or monetary values. If [`align`](/en-US/docs/Web/HTML/Element/th#align) is not se
```suggestion
  - : The content in the cell element is aligned to a character. Typical values include a period (.) to align numbers or monetary values. If [`align`](#align) is not set to `char`, this attribute is ignored.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/table/index.md
> +  - : This integer attribute defines, in pixels, the size of the frame surrounding the table. If set to 0, the [`frame`](/en-US/docs/Web/HTML/Element/table#frame) attribute is set to void.
```suggestion
  - : This integer attribute defines, in pixels, the size of the frame surrounding the table. If set to 0, the [`frame`](#frame) attribute is set to void.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/tbody/index.md
> +    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](/en-US/docs/Web/HTML/Element/tbody#char) and [`charoff`](/en-US/docs/Web/HTML/Element/
```suggestion
    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](#char) and [`charoff`](#charoff) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/tbody/index.md
> +  - : This attribute is used to set the character to align the cells in a column on. Typical values for this include a period (`.`) when attempting to align numbers or monetary values. If [`align`](/
```suggestion
  - : This attribute is used to set the character to align the cells in a column on. Typical values for this include a period (`.`) when attempting to align numbers or monetary values. If [`align`](#align) is not set to `char`, this attribute is ignored.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/tbody/index.md
> +Notice that each major is placed in a separate `<tbody>` block, the first row of which contains a single {{HTMLElement("th")}} element with a [`colspan`](/en-US/docs/Web/HTML/Element/th#colspan) attr
```suggestion
Notice that each major is placed in a separate `<tbody>` block, the first row of which contains a single {{HTMLElement("th")}} element with a [`colspan`](#colspan) attribute that spans the entire width of the table. That heading lists the name of the major contained within the `<tbody>`.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/tfoot/index.md
> +    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](/en-US/docs/Web/HTML/Element/tfoot#char) and [`charoff`](/en-US/docs/Web/HTML/Element/
```suggestion
    - `char`, aligning the textual content on a special character with a minimal offset, defined by the [`char`](#char) and [`charoff`](#charoff) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/tfoot/index.md
> +    > - To achieve the same effect as the `char` value, in CSS, you can use the value of the [`char`](/en-US/docs/Web/HTML/Element/tfoot#char) as the value of the {{cssxref("text-align")}} property.
```suggestion
    > - To achieve the same effect as the `char` value, in CSS, you can use the value of the [`char`](#char) as the value of the {{cssxref("text-align")}} property.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/meta/index.md
> +- If the [`charset`](/en-US/docs/Web/HTML/Element/meta#charset) attribute is set, the `<meta>` element is a _charset declaration_, giving the character encoding in which the document is encoded.
```suggestion
- If the [`name`](#name) attribute is set, the `<meta>` element provides _document-level metadata_, applying to the whole page.
- If the [`http-equiv`](#http-equiv) attribute is set, the `<meta>` element is a _pragma directive_, providing information equivalent to what can be given by a similarly-named HTTP header.
- If the [`charset`](#charset) attribute is set, the `<meta>` element is a _charset declaration_, giving the character encoding in which the document is encoded.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/meta/index.md
> +> **Note:** the attribute [`name`](/en-US/docs/Web/HTML/Element/meta#name) has a specific meaning for the `<meta>` element, and the [`itemprop`](/en-US/docs/Web/HTML/Global_attributes/itemprop) attri
```suggestion
> **Note:** the attribute [`name`](#name) has a specific meaning for the `<meta>` element, and the [`itemprop`](/en-US/docs/Web/HTML/Global_attributes/itemprop) attribute must not be set on the same `<meta>` element that has any existing [`name`](#name), [`http-equiv`](#http-equiv) or [`charset`](#charset) attributes.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/meta/index.md
> +  - : This attribute contains the value for the [`http-equiv`](/en-US/docs/Web/HTML/Element/meta#http-equiv) or [`name`](/en-US/docs/Web/HTML/Element/meta#name) attribute, depending on which is used.
```suggestion
  - : This attribute contains the value for the [`http-equiv`](#http-equiv) or [`name`](#name) attribute, depending on which is used.
```

2023-03-12 08:35 UTC, teoli2003 commented on files/en-us/web/html/element/meta/index.md
> +      - The number of seconds until the page should redirect to another - only if the [`content`](/en-US/docs/Web/HTML/Element/meta#content) attribute contains a non-negative integer followed by the
```suggestion
      - The number of seconds until the page should be reloaded - only if the [`content`](#content) attribute contains a non-negative integer.
      - The number of seconds until the page should redirect to another - only if the [`content`](#content) attribute contains a non-negative integer followed by the string '`;url=`', and a valid URL.
```

2023-03-13 03:27 UTC, OnkarRuikar commented
> A lot of MD links are inside HTML blocks and should be <a> elements.

There were ~90 of them very sneaky ones. I used ```(?<=<td>)(([\s\S](?!/td))*?)\[`(.*)`\]\((.*)\)``` to find them and\
 `$1<a href="$4"><strong>$3</strong></a>` to replace them.

2023-03-13 03:48 UTC, OnkarRuikar commented
I'v converted all the remaining macro calls in the repo. Lets make this the last PR.

2023-03-13 07:09 UTC, teoli2003 approved these changes
Let's get this in! It looks good enough!

2023-03-13 07:09 UTC, merged

2023-03-13 07:45 UTC, OnkarRuikar commented
> Let's get this in! It looks good enough!

:tada:  Getting rid of macros is not easy. :(

2023-03-13 08:01 UTC, teoli2003 commented
Yep, and that's why we do this little by little.

We already went from >1200 macros to about 100 macros.