Add page for prefers-reduced-transparency
mdn/content pull request #25289
Opened 2023-03-13 10:37 UTC by CanadaHonk

### Description

Added missing page for the `prefers-reduced-transparency` media query (similar to `prefers-reduced-motion`, etc).

### Motivation

The page is missing/does not exist, but exists for all other media queries in CSS Media Queries Level 5.

### Additional details

Spec: https://www.w3.org/TR/mediaqueries-5/#descdef-media-prefers-reduced-transparency

2023-03-13 10:57 UTC, teoli2003 commented
Thank you! Does any browser implement this yet?

2023-03-13 10:59 UTC, CanadaHonk commented
Not yet, but `prefers-reduced-data` exists from the same spec without any implementation. BCD already exists for this FYI. Also interested in getting it in Firefox hopefully soon.

2023-03-13 11:04 UTC, CanadaHonk commented
Oh, looks like the BCD data was added but later removed?
Added in: https://github.com/mdn/browser-compat-data/pull/5720
Removed in: https://github.com/mdn/browser-compat-data/pull/6854 (?)

2023-03-13 11:18 UTC, teoli2003 commented
Our policy is to wait at least for it to be implemented behind a flag (i.e., until it has a bcd entry). [There have been exceptions that were erroneous decisions, most of them dating from the time we were a wiki]

To save this valuable piece of work, we should mark this PR "on-hold" (a GitHub label we set) and reactivate it as soon as it lands somewhere.

We do this for several other features. Hopefully, this won't be too long.

2023-03-13 11:19 UTC, CanadaHonk commented
Sure, makes sense, thanks.

2023-03-13 22:26 UTC, hamishwillee commented
When the time comes, usually there is a corresponding HTTP client hint. If so, worth cross linking. For example: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Reduced-Motion

2023-03-13 22:29 UTC, CanadaHonk commented
Thanks for the heads up! One does indeed exist: https://wicg.github.io/user-preference-media-features-headers/#sec-ch-prefers-reduced-transparency

Also, the patch I wrote for adding `prefers-reduced-transparency` to Firefox is approved so should hopefully be in Nightly in the next few days behind a pref 🎉

2023-03-13 22:31 UTC, hamishwillee commented
@CanadaHonk Nice. Feel free to ping us when that goes in so we can review this ... all the fun work of adding back into BCD has to happen too.

2023-03-14 05:04 UTC, teoli2003 commented
We discussed yesterday in our editorial meeting how to deal with PRs we want to keep until a feature lands, like this one. We decided to mark them as Draft (in addition to the `on hold` label). The idea is that reviewers scanning the open PRs doesn't hit this PR each time they scan the list. I will convert it (it doesn't change anything practically, it is only bookkeeping for us)

2023-03-14 17:13 UTC, CanadaHonk commented
Firefox 113 now supports this behind a pref (`layout.css.prefers-reduced-transparency.enabled`) - created a BCD PR for it - https://github.com/mdn/browser-compat-data/pull/19135

2023-03-14 17:54 UTC, teoli2003 commented
As soon as it lands (on BCD), we'll be able to reactivate this PR :-)

2023-03-30 12:23 UTC, CanadaHonk commented
Landed in BCD so this should be good to review now :)

2023-03-30 12:26 UTC, teoli2003 commented on files/en-us/web/css/@media/prefers-reduced-transparency/index.md
> +> **Note:** No browser currently implements this feature so the following example will not work.
Neither this

2023-03-30 12:26 UTC, CanadaHonk commented on files/en-us/web/css/@media/prefers-reduced-transparency/index.md
> +> **Note:** This feature is not supported by any user agent and its specifics are subject to change.
It's behind an off by default pref in 113 so I think it's best to keep?

2023-03-30 15:14 UTC, dipikabh commented
113 will be out only in May (https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates). I think we should still keep this on hold and as Draft.

I have added a doc issue for this (as we do for tracking our other doc requirements from bugzilla).

2023-03-30 15:18 UTC, CanadaHonk commented
Sure.

2023-05-08 00:02 UTC, dipikabh requested changes
Hello @CanadaHonk, we can now move this PR out of draft for Fx113.

I've suggested some edits. (I've made some similar language edits to the `prefers-reduced-motion` feature in https://github.com/mdn/content/pull/26630).

Thanks a lot for adding this page! 🙌

2023-05-08 00:26 UTC, dipikabh commented on files/en-us/web/css/@media/prefers-reduced-transparency/index.md
> +- CSS [prefers-reduced-motion](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query
- [Using media queries](/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

2023-05-08 00:27 UTC, dipikabh commented on files/en-us/web/css/@media/prefers-reduced-transparency/index.md
> +- CSS [prefers-reduced-motion](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query
We can also add another link here:

```suggestion
- CSS [prefers-reduced-motion](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query
- [Using media queries](/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)
```

2023-05-08 00:29 UTC, dipikabh requested changes

2023-05-08 00:29 UTC, dipikabh commented on files/en-us/web/css/@media/prefers-reduced-transparency/index.md
> +- CSS [prefers-reduced-motion](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query
We can also add this link here:

```suggestion
- CSS [prefers-reduced-motion](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) media query
- [Using media queries](/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)
```

2023-05-11 20:26 UTC, CanadaHonk commented
Thanks for the review, updated all said (apologies for the delay).

2023-05-12 00:53 UTC, dipikabh approved these changes

2023-05-12 00:54 UTC, dipikabh commented
Thanks a lot @CanadaHonk for the updates! Much appreciate your work on this feature! 🙏

2023-05-12 00:54 UTC, merged