Document missing AudioWorkletGlobalScope.* pages
mdn/content pull request #25293
Opened 2023-03-13 13:52 UTC by teoli2003

Part of openwebdocs/project#152

I needed to create the base interface page `WorkletGlobalScope` so we had no red links left in the `AudioWorkletGlobalScope`.

`PaintWorkletGlobalScope` is missing, but I didn't want to fall in this rabbit hole today.

2023-03-13 23:40 UTC, dawei-wang reviewed
A few typos

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/currentframe/index.md
> +The {{domxref("AudioWorkletProcessor")}} has accesses to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```suggestion
The {{domxref("AudioWorkletProcessor")}} has access to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/currentframe/index.md
> +The main script load the processor, create an instance of {{domxref("AudioWorkletNode")}}, passing the name of the processor to it, and connect the node to an audio graph. We should see the output of
```suggestion
The main script loads the processor, creates an instance of {{domxref("AudioWorkletNode")}}, passes the name of the processor to it, and connects the node to an audio graph. We should see the output of {{domxref("console.log()")}} calls in the console:
```

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/currenttime/index.md
> +The {{domxref("AudioWorkletProcessor")}} has accesses to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```suggestion
The {{domxref("AudioWorkletProcessor")}} has access to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/currenttime/index.md
> +The main script load the processor, create an instance of {{domxref("AudioWorkletNode")}}, passing the name of the processor to it, and connect the node to an audio graph. We should see the output of
```suggestion
The main script loads the processor, creates an instance of {{domxref("AudioWorkletNode")}}, passes the name of the processor to it, and connects the node to an audio graph. We should see the output of {{domxref("console.log()")}} calls in the console:
```

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/samplerate/index.md
> +The {{domxref("AudioWorkletProcessor")}} has accesses to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```suggestion
The {{domxref("AudioWorkletProcessor")}} has access to the specific {{domxref("AudioWorkletGlobalScope")}} properties:
```

2023-03-13 23:40 UTC, dawei-wang commented on files/en-us/web/api/audioworkletglobalscope/samplerate/index.md
> +The main script load the processor, create an instance of {{domxref("AudioWorkletNode")}}, passing the name of the processor to it, and connect the node to an audio graph. We should see the output of
```suggestion
The main script loads the processor, creates an instance of {{domxref("AudioWorkletNode")}}, passes the name of the processor to it, and connects the node to an audio graph. We should see the output of {{domxref("console.log()")}} calls in the console:
```

2023-03-14 15:47 UTC, Elchi3 requested changes
Some requests for the new page for WorkletGlobalScope. 

The AudioWorkletGlobalScope sub pages look fine (I think the example is the same as on the main page, so I'm not double checking this in all details).

Overall I have the feeling this is quite unstable spec-wise still, so I don't think we are in a position to explain it in all details yet because those details are still being figured out.

2023-03-14 15:47 UTC, Elchi3 commented on files/en-us/web/api/workletglobalscope/index.md
> +The **`WorkletGlobalScope`** interface is an abstract class common to all global scope associated with worklets.
I was wondering if there is `self` in `WorkletGlobalScope` but seems like there isn't.  https://html.spec.whatwg.org/multipage/worklets.html#worklets-idempotent (the whole worklets chapter has more info about `WorkletGlobalScope`. Some of it might be useful to mention on this page, but it seems it is an unstable spec, so unsure what to add exactly.)

```suggestion
The **`WorkletGlobalScope`** interface is an abstract class that specific worklet scope classes inherit from. Each `WorkletGlobalScope` defines a new global environment.
```

2023-03-14 15:47 UTC, Elchi3 commented on files/en-us/web/api/workletglobalscope/index.md
> +{{APIRef("HTM DOM")}}
The spec says secure context only. Add a banner?

2023-03-14 16:07 UTC, teoli2003 commented on files/en-us/web/api/workletglobalscope/index.md
> +{{APIRef("HTM DOM")}}
Oh yes! I missed this one. (Hopefully, they'll be added soon automatically)

```suggestion
{{APIRef("HTM DOM")}}{{SecureContext_Header}}
```

2023-03-14 16:09 UTC, teoli2003 commented
At some point, we should have a guide explaining what a _global scope_ is and how it works (that is, how to access properties and methods on the current global scope, `self`, or the case of `window`…)

2023-03-14 16:36 UTC, Elchi3 approved these changes

2023-03-14 16:36 UTC, merged