CSS Modules: css colors
mdn/content pull request #25329
Opened 2023-03-15 02:34 UTC by estelle

2023-03-20 16:29 UTC, dipikabh requested changes

2023-03-20 16:29 UTC, dipikabh commented on files/en-us/web/css/css_colors/index.md
> +To view a new color, along with the color value written in [red-green-blue](/en-US/docs/Web/CSS/color_value/rgb), [hexadecimal](/en-US/docs/Web/CSS/hex-color), [hue, saturation, and lightness](/en-US
```suggestion
The box below contains a color syntax converter. When you choose a color and an opacity, it shows the corresponding values of the color in [red-green-blue](/en-US/docs/Web/CSS/color_value/rgb) (RGB), [hexadecimal](/en-US/docs/Web/CSS/hex-color) (HEX), [hue, saturation, and lightness](/en-US/docs/Web/CSS/color_value/hsl) (HSL), and [hue, whiteness, and blackness](/en-US/docs/Web/CSS/color_value/hwb) (HWB) CSS color formats.
To view a new color, click the color box next to "Select a color" and choose a color from the [color picker](/en-US/docs/Web/HTML/Element/input/color). Close the color picker and change the opacity of the color using the "Select an opacity" [slider](/en-US/docs/Web/HTML/Element/input/range). Notice the values for RGB, HEX, HSL, and HWB for the colors and opacity you choose.
```

2023-03-20 19:25 UTC, estelle commented on files/en-us/web/css/css_colors/index.md
> +To see the code for this color syntax converter, [view the source on Github](https://github.com/mdn/css-examples/blob/main/modules/colors.html).
I changed it to reflect what is shown above the demo and how to change it below the demo. Is that better?

2023-03-20 19:33 UTC, estelle commented on files/en-us/web/css/css_colors/index.md
> +This color syntax converter shows the values of the currently selected color in [red-green-blue](/en-US/docs/Web/CSS/color_value/rgb) (RGB), [hexadecimal](/en-US/docs/Web/CSS/hex-color) (HEX), [hue,
```suggestion
This color syntax converter shows the values of the currently selected color in [red-green-blue](/en-US/docs/Web/CSS/color_value/rgb) (RGB), [hexadecimal](/en-US/docs/Web/CSS/hex-color) (HEX), [hue, saturation, and lightness](/en-US/docs/Web/CSS/color_value/hsl) (HSL), and [hue, whiteness, and blackness](/en-US/docs/Web/CSS/color_value/hwb) (HWB) CSS color formats. The RGB, HEX, HSL, and HWB color values, while written differently, all represent the same color value.
```

2023-03-20 20:11 UTC, dipikabh requested changes
Suggested a few edits

2023-03-21 01:16 UTC, dipikabh approved these changes
Thanks 👍

2023-03-21 01:17 UTC, merged