autocorrect is supported by the textarea too
mdn/content pull request #2534
Opened 2021-02-20 19:12 UTC by oliviertassinari

You can very this affirmation on https://codepen.io/oliviertassinari/pen/wvoqYoY, here the outcome after you type `<im`.

<img width="318" alt="Screenshot 2021-02-20 at 20 10 58" src="https://user-images.githubusercontent.com/3165635/108606021-d6823900-73b7-11eb-8546-213c4ee6f30b.png">

On Safari 12, iOS 14.4. I have used the description used in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocorrect.

2021-02-21 00:38 UTC, sideshowbarker requested changes

2021-02-21 00:38 UTC, sideshowbarker commented on files/en-us/web/html/element/textarea/index.html
> + <dd>A Safari extension, the <code>autocorrect</code> attribute is a string which indicates whether or not to activate automatic correction while the user is editing this field. Permitted values are:
```suggestion
 <dd>A string which indicates whether or not to activate automatic spelling correction and processing of text substitutions (if any are configured) while the user is editing this <code>textarea</code>. Permitted values are:</p></dd>
```

2021-02-21 00:38 UTC, sideshowbarker commented on files/en-us/web/html/element/textarea/index.html
> +  <dd>Enable automatic correction of typos, as well as processing of text substitutions if any are configured.</dd>
```suggestion
  <dd>Enable automatic spelling correction and text substitutions.</dd>
```

2021-02-21 00:38 UTC, sideshowbarker commented on files/en-us/web/html/element/textarea/index.html
> +  <dd>Disable automatic correction and text substitutions.</dd>
```suggestion
  <dd>Disable automatic spelling correction and text substitutions.</dd>
```

2021-02-24 03:31 UTC, sideshowbarker approved these changes

2021-02-24 03:52 UTC, merged

2021-02-24 03:52 UTC, sideshowbarker commented
Olivier, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

2021-02-24 14:25 UTC, oliviertassinari commented
@sideshowbarker Thanks for handling the extra work I have created by opening this PR :)