Fixed a few typos.
mdn/content pull request #25395
Opened 2023-03-16 20:43 UTC by paulmcfe

### Description

Fixed a few typos.

### Motivation

These docs should be grammatically ans well as factually correct.

### Additional details

### Related issues and pull requests

2023-03-16 20:50 UTC, dipikabh requested changes
Hello @paulmcfe, welcome to the MDN project!

Your changes look good. I have suggested a few more edits.

2023-03-16 20:50 UTC, dipikabh commented on files/en-us/web/css/transition-duration/index.md
> +You may specify multiple durations; each duration will be applied to the corresponding property as specified by the {{ cssxref("transition-property") }} property, which acts as a master list. If ther
```suggestion
You may specify multiple durations; each duration will be applied to the corresponding property as specified by the {{ cssxref("transition-property") }} property, which acts as a master list. If the number of specified durations is less than in the master list, the user agent repeats the list of durations. If the number of specified durations is more than in the master list, the list is truncated to the right size. In both the cases, the CSS declaration stays valid.
```

2023-03-16 21:02 UTC, paulmcfe commented on files/en-us/web/css/transition-duration/index.md
> +You may specify multiple durations; each duration will be applied to the corresponding property as specified by the {{ cssxref("transition-property") }} property, which acts as a master list. If ther
These edits are great: they make the text easier to read and understand. I would only say that "In both the cases" sounds off to me. I'd leave it as "In both cases".

2023-03-20 21:34 UTC, dipikabh commented on files/en-us/web/css/transition-duration/index.md
> +You may specify multiple durations; each duration will be applied to the corresponding property as specified by the {{ cssxref("transition-property") }} property, which acts as a master list. If ther
Great, you can then push a new commit with these changes (minus the last "the").

2023-03-20 21:36 UTC, dipikabh commented
Thanks for your patience, @paulmcfe. If you can just commit the edits, I can approve and merge the pull request.

2023-03-21 01:22 UTC, dipikabh approved these changes
Thanks 👍

2023-03-21 01:23 UTC, merged