Ff112 remove mutable db
mdn/content pull request #25405
Opened 2023-03-17 04:35 UTC by hamishwillee

FF112 permanently removes `IDBMutableFile`, `IDBFileRequest`, `IDBFileHandle`, `IDBDatabase.createMutableFile()` from FF in https://bugzilla.mozilla.org/show_bug.cgi?id=1500343

These had been behind a pref in 102 and had been seeing very little use for some years prior. They also are not used in other browsers for similar timeframes. There is no BCD. They are also went through several renames and have been confusing to users. 
For these reasons, I have removed the entries as suggested by @teoli2003 here https://github.com/mdn/content/issues/25360#issuecomment-1471376700 rather than waiting the customary 2 years (i.e. we _know_ no one is relying on these, so there is no real value in keeping them).

This removes all the entries for `IDBMutableFile`, `IDBFileRequest`, `IDBFileHandle`, `IDBDatabase.createMutableFile()`. It also removes all mention in normal text. In release notes it keeps the mentions, but removes any links. 
The redirect is to the top level http://localhost:5042/en-US/docs/Web/API/IndexedDB_API page.

Related docs work can be tracked in #25360

2023-03-20 15:54 UTC, rebloor approved these changes
Looks good for the webextension changes.

2023-03-20 23:03 UTC, hamishwillee commented
@wbamberg Do you think you could have a quick check of this.

2023-03-21 04:35 UTC, teoli2003 requested changes
A nit, and this is good for me.

(I'm happy to see this go, I spent some time last year to untangle what happened here over the years)

2023-03-21 04:35 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/102/index.md
> +- The Non-standard interfaces `IDBMutableFile`, `IDBFileHandle`, `IDBFileRequest`, and the method `IDBDatabase.createMutableFile()` have been disabled by default in preparation for removal in a futur
Nit
```suggestion
- The non-standard interfaces `IDBMutableFile`, `IDBFileHandle`, `IDBFileRequest`, and the method `IDBDatabase.createMutableFile()` have been disabled by default in preparation for removal in a future release ([Firefox bug 1764771](https://bugzil.la/1764771)).
```

2023-03-21 05:55 UTC, hamishwillee commented
Awesome. A happy day then @teoli2003 !

2023-03-21 06:13 UTC, teoli2003 approved these changes
👍

2023-03-21 06:14 UTC, merged