Fix possible L values for oklab() and oklch()
mdn/content pull request #25419
Opened 2023-03-17 13:27 UTC by teoli2003

Fix #25416

L values are between 0 and 1 not 0 and 100 (or a %-age).

2023-03-18 01:54 UTC, estelle commented
I don't think this is accurate. We might need to get a deciding opinion.

There is a note:

> Usually when percentage values have a numeric equivalent in CSS, 100% is equal to the number 1. This case is notable in that 100% is equal to the number 100 for the L value and 0.4 for the a and b values.

and the spec reads:


> The first argument specifies the CIE Lightness, L. This is a number between 0% or 0 (representing black) and **100% or 100** (representing white), Values less than 0% or 0 must be clamped to 0% at parsed-value time; values greater than 100% or 100 are clamped to 100% at parsed-value time.

2023-03-18 01:56 UTC, estelle requested changes
Originally I thought the edit was incorrect, but editing as it is in fact correct, the following note needs to be removed.:

> Usually when percentage values have a numeric equivalent in CSS, 100% is equal to the number 1. This case is notable in that 100% is equal to the number 100 for the L value and 0.4 for the a and b values.

The spec does read:

> The first argument specifies the CIE Lightness, L. This is a number between 0% or 0 (representing black) and **100% or 100** (representing white), Values less than 0% or 0 must be clamped to 0% at parsed-value time; values greater than 100% or 100 are clamped to 100% at parsed-value time.

and

> Percent reference range 	for L: 0% = 0.0, 100% = 100.0
for a and b: -100% = -125, 100% = 125


But that is under lch() and lab(), not OKlch or OKlab. So, yup, we need to make this edit AND get rid of the note. 

In Edge, the two green values are not working. 

```css
[data-color="green"] {
  background-color: oklab(100% -100% 0.4);
}
[data-color="green-b"] {
  background-color: oklab(100% -100% 0.6);
}
```
but works if written as:

```css
[data-color="green"] {
  background-color: oklab(100% -0.4 0.4);
}
[data-color="green-b"] {
  background-color: oklab(100% -0.4 0.6);
}
```
Should we file a bcd issue, or am i missing something and the original is incorrectly written?

2023-03-18 05:22 UTC, teoli2003 commented
Notes removed.

Yes, Edge behavior should be added in BCD. I can't test on Edge, though. Given Edge is based on Chromium, I'm  a bit surprised to have something not working on Edge but on Chrome or Opera...

2023-03-20 15:07 UTC, dipikabh requested changes
Some quick fix suggestions for descriptions of other values

2023-03-20 16:16 UTC, estelle approved these changes
Thanks! 🎉

2023-03-20 20:20 UTC, dipikabh approved these changes
Thank you 👍

2023-03-20 20:20 UTC, merged