Add missing 'instant' scroll behavior option value
mdn/content pull request #25467
Opened 2023-03-20 00:29 UTC by darko-r

### Description
ScrollBehavior has three possible values ("auto", "instant" and "smooth"), but only two are presented ("auto", and "smooth"), this commit adds the third one.

### Motivation
Make all allowed values presented.

### Additional details
Page that already has the same info: [Element.scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo)

https://drafts.csswg.org/cssom-view/#enumdef-scrollbehavior

2023-03-20 03:39 UTC, yarusome commented
[`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) also has a description for `ScrollBehavior` that needs updating.

2023-03-20 17:31 UTC, darko-r commented
> [`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) also has a description for `ScrollBehavior` that needs updating.

Thanks @yarusome, added that one too.

2023-03-20 20:18 UTC, wbamberg requested changes

2023-03-20 20:18 UTC, wbamberg commented on files/en-us/web/api/element/scroll/index.md
> +      - : Specifies whether the scrolling should animate smoothly (`smooth`), happen instantly in a single jump (`instant`), or let the browser choose (`auto`, default).
This is not quite grammatical: "Specifies whether the scrolling should ... let the browser choose (`auto`, default)."

Also it would be clearer if we put these options in a bulleted list. And can we be more helpful than "let the browser choose"? It seems that in the case of `auto`, behavior depends on the computed value of [`scroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior). 

Perhaps we could say something like:

```suggestion
      - : Determines whether scrolling is instant or animates smoothly. This option is a string which must take one of the following values:
          - `smooth`: scrolling should animate smoothly
          - `instant`: scrolling should happen instantly in a single jump
          - `auto`: scroll behavior is determined by the computed value of {{cssxref("scroll-behavior")}}
```

2023-03-21 00:21 UTC, darko-r commented
Suggestion applied, it is much clearer now. Thanks for the review @wbamberg.

2023-03-21 18:27 UTC, darko-r commented
Thanks @wbamberg for letting me know I forgot to update other pages. Change applied to other files.

2023-03-21 22:49 UTC, wbamberg approved these changes
👍 looks great, thank you @darko-r !

2023-03-21 22:49 UTC, merged