Add CSSFontPaletteValuesRule.*
mdn/content pull request #25476
Opened 2023-03-20 13:59 UTC by teoli2003

### Description

Created the pages for `CSSFontPaleteValuesRule.*` pages

### Motivation

openwebdocs/project#152

### Additional details

I also added some extra See also entries to their CSS counterparts.

2023-03-20 15:51 UTC, dipikabh requested changes
Primarily a language review

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +A string, that can be one of the following colors:
```suggestion
A string that can be one of the following color values:
```

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +  - : Matches the palette corresponding to the index. The first palette corresponds to `"0"`.
```suggestion
- `light`
  - : Matches the first palette in the font file that is marked as applicable to a light background, that is, _close to white_. If there is no palette in the font or if no palette has the required metadata, the value is equivalent to `"0"`, that is, the first palette in the font.
- `dark`
  - : Matches the first palette in the font file that is marked as applicable to a dark background, that is, _close to black_. If there is no palette in the font or if no palette has the required metadata, the value is equivalent to `"0"`, that is, the first palette in the font.
- a string containing an index (like `"0"`, `"1"`, …)
  - : Matches the palette corresponding to the index. The first palette corresponds to `"0"`.
```

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +
It would be nice to have an H3 heading describing the example. HTML, CSS, JavaScript, Result would then be H4. Also `EmbedLiveSample` would need to be updated if an example title is added here.

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +A string, listing the different font families the rule can be applied to, separated by spaces.
```suggestion
A string containing a space-separated list of the font families on which the rule can be applied
```

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rul
```suggestion
This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rules lives in the last stylesheet added to the document, the palette will be the second {{domxref("CSSRule")}} returned by the \_last: stylesheet in the document (`document.styleSheets[document.styleSheets.length-1].cssRules`). So, `rules[1]` returns a {{domxref("CSSFontPaletteValuesRule")}} object, from which we can access `fontFamily`.
```
I am guessing "\_last:" needs to be fixed
Also, as in CSSFontPaletteValuesRule/basePalette, a title for the example can be added.

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/index.md
> +This example uses the CSS found as an example on the {{cssxref("@font-palette-values")}} page. The first {{domxref("CSSRule")}} returned will be a `CSSFontFaceRule`.
```suggestion
This example uses the same CSS as in the example on the {{cssxref("@font-palette-values")}} page. The first {{domxref("CSSRule")}} returned will be a `CSSFontFaceRule`.
```

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/overridecolors/index.md
> +A string containing a comma-separated list of pairs of color indices and colors.
```suggestion
A string containing a comma-separated list of color index and color pair
```

2023-03-20 15:51 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/overridecolors/index.md
> +The read-only **`overrideColors`** property of the {{domxref("CSSFontPaletteValuesRule")}} interface is a string containing a list of pairs of color indices and the color that are to be used instead,
```suggestion
The read-only **`overrideColors`** property of the {{domxref("CSSFontPaletteValuesRule")}} interface is a string containing a list of color index and color pair that are to be used instead. It is specified in the same format as the corresponding {{cssxref("@font-palette-values/override-colors", "override-colors")}} descriptor.
```

2023-03-20 17:45 UTC, dawei-wang commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rul
```suggestion
This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rules live in the last stylesheet added to the document, the palette will be the second {{domxref("CSSRule")}} returned by the \_last: stylesheet in the document (`document.styleSheets[document.styleSheets.length-1].cssRules`). So, `rules[1]` returns a {{domxref("CSSFontPaletteValuesRule")}} object, from which we can access `name`.
```

2023-03-24 09:04 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rul
Fixed

2023-03-24 09:07 UTC, teoli2003 commented
I fixed all review comments; this is ready for a 2nd pass.

Note the single flaw left will be fixed in #25570 when the missing page is added.

2023-03-24 14:53 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +
That's great, thank you. Taking a look.

2023-03-24 14:56 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +This example rules in the last stylesheet added to the document, returned by the \_last: stylesheet in the document (`document.styleSheets[document.styleSheets.length-1].cssRules)`. So, `rules[2]` re
This seems to have been missed. The first sentence sounds incomplete.
Does it need to be "This example adds rules..."?

Also, I am not sure what "_last: stylesheet" means.

2023-03-24 15:29 UTC, dipikabh requested changes
Thanks for the updates!

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +### Read the associated base palette
```suggestion
### Reading the base palette value associated with a rule
```
changing to the gerund form of the verb

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +- {{cssxref("@font-palette-values/base-palette", "base-palette")}} descriptor
```suggestion
- {{cssxref("@font-palette-values")}}
- {{cssxref("@font-palette-values/base-palette", "base-palette")}}
```
There was a change in the guidelines. Not adding the word after the link anymore.

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +### Read the associated font family
```suggestion
### Reading the font families associated with a rule
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +The read-only **`fontFamily`** property of the {{domxref("CSSFontPaletteValuesRule")}} interface lists the font families the rule can be applied to. The font families must be _named_ families; _gener
```suggestion
The read-only **`fontFamily`** property of the {{domxref("CSSFontPaletteValuesRule")}} interface lists the font families to which the rule can be applied. The font families must be _named_ families; _generic_ families like `courier` are not valid.
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +{{EmbedLiveSample("Read the associated font family", "100", "40")}}
```suggestion
{{EmbedLiveSample("reading_the_font_families_associated_with_a_rule", "100", "40")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +- {{cssxref("@font-palette-values/font-family", "font-family")}} descriptor
```suggestion
- {{cssxref("@font-palette-values")}}
- {{cssxref("@font-palette-values/font-family", "font-family")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/index.md
> +### Read associated font family using CSSOM
```suggestion
### Reading the associated font family using CSSOM
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/index.md
> +{{EmbedLiveSample("Read associated font family using CSSOM", "100", "40")}}
```suggestion
{{EmbedLiveSample("reading_the_associated_font_family_using_CSSOM", "100", "40")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +- {{cssxref("@font-palette-values/font-family", "font-family")}} descriptor
```suggestion
- {{cssxref("@font-palette-values")}}
- {{cssxref("@font-palette-values/font-family", "font-family")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/index.md
> +- {{cssxref("@font-palette-values")}}
Should a link to [CSSOM](https://developer.mozilla.org/en-US/docs/Glossary/CSSOM) also be added here?

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +## Read the at-rule's name
```suggestion
## Reading the name of the at-rule
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +{{EmbedLiveSample("Read the at-rule's name", "100", "40")}}
```suggestion
{{EmbedLiveSample("Reading the name of the at-rule", "100", "40")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +- {{cssxref("@font-palette-values")}} at-rule
```suggestion
- {{cssxref("@font-palette-values")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/overridecolors/index.md
> +### Read the overriden colors
```suggestion
### Reading the overridden colors
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/overridecolors/index.md
> +{{EmbedLiveSample("Read the overriden colors", "100", "125")}}
```suggestion
{{EmbedLiveSample("Reading the overridden colors", "100", "125")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/overridecolors/index.md
> +- {{cssxref("@font-palette-values/override-colors", "override-colors")}} descriptor
```suggestion
- {{cssxref("@font-palette-values")}}
- {{cssxref("@font-palette-values/override-colors", "override-colors")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/css/@font-palette-values/base-palette/index.md
>  - {{cssxref("font-palette/", "font-palette")}} property
```suggestion
- {{cssxref("@font-palette-values/font-family", "font-family")}}
- {{cssxref("@font-palette-values/override-colors", "override-colors")}}
- {{cssxref("font-palette/", "font-palette")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/css/@font-palette-values/font-family/index.md
>  - {{cssxref("font-palette/", "font-palette")}} property
```suggestion
- {{cssxref("@font-palette-values/font-family", "font-family")}}
- {{cssxref("@font-palette-values/override-colors", "override-colors")}}
- {{cssxref("font-palette/", "font-palette")}}
```

2023-03-24 15:29 UTC, dipikabh commented on files/en-us/web/css/@font-palette-values/index.md
>  - {{cssxref("@font-palette-values/override-colors", "override-colors")}} descriptor
```suggestion
- {{cssxref("@font-palette-values/font-family", "font-family")}}
- {{cssxref("@font-palette-values/base-palette", "base-palette")}}
- {{cssxref("@font-palette-values/override-colors", "override-colors")}}
```

2023-03-24 15:45 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +{{EmbedLiveSample("Read the associated base palette", "100", "255")}}
Spaces are transformed in underscore by the macro.

2023-03-24 15:48 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/index.md
> +- {{cssxref("@font-palette-values")}}
I don't think so, the link is added at the top of the sidebar. (´APIRef("CSSOM")`)

2023-03-24 15:50 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +- {{cssxref("@font-palette-values/font-family", "font-family")}} descriptor
```suggestion
- {{cssxref("@font-palette-values")}}
- {{cssxref("@font-palette-values/font-family", "font-family")}}
```

2023-03-24 15:51 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/fontfamily/index.md
> +- {{cssxref("@font-palette-values/font-family", "font-family")}} descriptor
Fixed

2023-03-27 07:48 UTC, teoli2003 commented on files/en-us/web/api/cssfontpalettevaluesrule/basepalette/index.md
> +This example rules in the last stylesheet added to the document, returned by the \_last: stylesheet in the document (`document.styleSheets[document.styleSheets.length-1].cssRules)`. So, `rules[2]` re
Rephrased

2023-03-27 14:28 UTC, dipikabh requested changes
Taking cue from your fix, replacing all "\_last:" occurrences with "last".

2023-03-27 14:28 UTC, dipikabh commented on files/en-us/web/api/cssfontpalettevaluesrule/name/index.md
> +This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rul
```suggestion
This example first defines an {{cssxref("@import")}} and an {{cssxref("@font-palette-values")}} at-rule. Then it reads the {{cssxref("@font-palette-values")}} rule and displays its name. As these rules live in the last stylesheet added to the document, the palette will be the second {{domxref("CSSRule")}} returned by the last stylesheet in the document (`document.styleSheets[document.styleSheets.length-1].cssRules`). So, `rules[1]` returns a {{domxref("CSSFontPaletteValuesRule")}} object, from which we can access `name`.
```

2023-03-27 14:33 UTC, dipikabh approved these changes

2023-03-27 14:47 UTC, merged

2023-03-27 14:47 UTC, dipikabh commented
Thank you for adding these pages, @teoli2003! 🙌