1916 svg image crossorigin
mdn/content pull request #2547
Opened 2021-02-21 19:49 UTC by Ryuno-Ki

This PR will likely need some iterations before it can be merged.
I applied fixable flaws on the files I touched.
I'd need especially help on how to reference BCD tables using Compat macro.
Also, I'm not absolutely sure how much duplication is acceptable between SVG crossorigin and HTML crossorigin.

2021-02-21 19:49 UTC, Ryuno-Ki commented
Requesting review from @peterbe for technical questions and @chrisdavidmills for editorial ones.

2021-02-22 09:52 UTC, chrisdavidmills requested changes
Thanks for the hard work here @Ryuno-Ki !

Few comments for you to consider, plus some answers to your questions.

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p class="seoSummary">The crossorigin attribute, valid on the {{ SVGElement("image") }} elements, provides support for <a href="/en-US/docs/Web/HTTP/CORS">CORS</a>, defining how the element handles c
"elements" -> "element"

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>The <code>crossorigin</code> content attribute on media elements is a CORS settings attribute.</p>
This line seems to repeat some of the information available in the above paragraph. Delete?

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>These attributes are enumerated, and have the following possible values:</p>
So the table is a list of the values the `crossorigin` attribute can take? In which case, this sentence should be rewritten to account for this. At the moment it is just confusing.

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>It follows the same processing rules as {{htmlattrxref("crossorigin")}}.</p>
"as" -> "as the HTML attribute" ?

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>{{HTMLSidebar}}{{draft}}</p>
The HTML sidebar is not relevant here. It looks like the closest we have in the SVG docs is {{SVGRef}}, which isn't very good either, but is less confusing than this. I'd change it to that for now, and then we can look at creating a better sidebar in the future.

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>{{Compat("svg.elements.image.crossorigin")}}</p>
OK, this is a bit of a tricky one. The call you need to access this particular bit of data is `{{Compat("api.SVGImageElement.crossOrigin")}}`. You literally just read down the chain of objects inside the JSON. This causes the browser compat data table to appear in the page.

However, when you put this in the page, you get a flaw error that says "In api.SVGImageElement.crossOrigin under key __compat can't find document: /en-US/docs/Web/API/SVGImageElement/crossOrigin". This is because the https://developer.mozilla.org/en-US/docs/Web/API/SVGImageElement/crossOrigin page doesn't exist on MDN.

Ideally, you should create data for the actual SVG element attribute, and not reference the API property equivalent. Probably somewhere like this — https://github.com/mdn/browser-compat-data/blob/master/svg/elements/image.json.

2021-02-22 09:52 UTC, chrisdavidmills commented on files/en-us/web/svg/element/image/index.html
> +  <li>{{SVGAttr("crossorigin")}}: A CORS settings attribute.</li>
Definition seems a bit vague. How about "Definines how the element handles crossorigin/CORS requests" ?

2021-02-22 09:54 UTC, chrisdavidmills commented
I don't think we need to involve Peter here, so I've removed his review tag.

FYI, there is no problem here with repeating some of the information form the HTML `crossorigin` page, as long as it is relevant and accurate.

2021-02-22 10:03 UTC, chrisdavidmills commented
I don't think we need to involve Peter here, so I've removed his review tag.

FYI, there is no problem here with repeating some of the information form the HTML `crossorigin` page, as long as it is relevant and accurate.

2021-02-22 19:21 UTC, peterbe commented
> Requesting review from @peterbe for technical questions 

What is the question for me?

2021-02-22 20:12 UTC, Ryuno-Ki commented
My comments vanished :O 

I think, I had a question regarding linking / walking the BCD table.
Chris spoilered the answer for this particular case in https://github.com/mdn/content/pull/2547/files#r580111551 - but I'd like to understand where / how it traverses the BCD object. Is this something Yari caches somehow? Or installed as dependency (as JSON?).

2021-02-22 20:29 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>The <code>crossorigin</code> content attribute on media elements is a CORS settings attribute.</p>
`CORS settings attribute` seem to have some meaning. I noticed that on the [HTML crossorigin page](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) as well (where it appears once inside the `seoSummary` and again in the paragraph after).

2021-02-22 20:30 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>These attributes are enumerated, and have the following possible values:</p>
I agree. Again, taken from the HTML version (so an update might be apt there, too).

2021-02-22 20:41 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>{{Compat("svg.elements.image.crossorigin")}}</p>
I replaced the reference and left a HTML comment.
If this PR is still pending by tomorrow, I try to gather some data to add an entry to BCD.

2021-02-22 20:42 UTC, Ryuno-Ki commented on files/en-us/web/svg/element/image/index.html
> +  <li>{{SVGAttr("crossorigin")}}: A CORS settings attribute.</li>
I went with another phrase.

2021-02-22 20:43 UTC, Ryuno-Ki commented
The question regarding the `seoSummary` paragraph is still pending, blocking this PR from merge.
There is a second one regarding BCD. If I got that correctly, the table would auto-update once BCD releases a new version with an update.

2021-02-23 08:11 UTC, chrisdavidmills requested changes
OK, so one more minor request change regarding the `seoSummary` stuff.

The BCD information update looks fine for now. This is nearly there now!

2021-02-23 08:11 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/crossorigin/index.html
> +<p>The <code>crossorigin</code> content attribute on media elements is a CORS settings attribute.</p>
I'd still fold it into the previous paragraph. It looks like we've got two definitions, one after the other, for the same thing.

2021-02-23 20:47 UTC, Ryuno-Ki commented
Filled https://github.com/mdn/browser-compat-data/issues/9238 with BCD to keep track on updating the data there, too.

2021-02-24 09:11 UTC, chrisdavidmills approved these changes
Great, this is looking good now; thanks @Ryuno-Ki !

2021-02-24 09:11 UTC, merged