Reference for stage 4 change-array-by-copy
mdn/content pull request #25488
Opened 2023-03-20 23:15 UTC by Josh-Cena

### Description

This feature was recently merged into the spec: https://github.com/tc39/ecma262/pull/2997

It's already implemented by latest Chrome.

### Motivation

### Additional details

### Related issues and pull requests

2023-04-05 07:37 UTC, teoli2003 requested changes

2023-04-05 07:37 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/@@species/index.md
> +> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [inves
"New array methods" will not age well. They are new now, but in a few years, they won't be new.

2023-04-05 19:26 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/@@species/index.md
> +> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [inves
The thing I want to emphasize is that there's a time after which the committee stops using `@@species`, otherwise there's no way to explain the arbitrary inconsistency. Is there a better phrasing?

2023-04-06 11:49 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/array/@@species/index.md
> +> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [inves
Tentative:
```suggestion
> **Warning:** The existence of `@@species` allows the execution of arbitrary code and may create security vulnerabilities. It also makes specific optimizations much harder. Engine implementers are [investigating whether to remove this feature](https://github.com/tc39/proposal-rm-builtin-subclassing). Avoid relying on it if possible. Modern array methods, such as {{jsxref("Array/toReversed", "toReversed()")}}, do not use `@@species` and always return a new `Array` base class instance.
```

2023-04-06 14:19 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/@@species/index.md
> +> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [inves
Thanks—I like "Modern". However, the previous sentences are duplicated across all `@@species` pages, so it would take a separate PR to update them, if one feels strongly.

2023-04-09 00:02 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/@@species/index.md
> +> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [inves
```suggestion
> **Warning:** The existence of `@@species` allows execution of arbitrary code and may create security vulnerabilities. It also makes certain optimizations much harder. Engine implementers are [investigating whether to remove this feature](https://github.com/tc39/proposal-rm-builtin-subclassing). Avoid relying on it if possible. Modern array methods, such as {{jsxref("Array/toReversed", "toReversed()")}}, do not use `@@species` and always return a new `Array` base class instance.
```

2023-04-09 07:23 UTC, teoli2003 approved these changes
👍

2023-04-09 07:23 UTC, merged