Fixed a sentence
mdn/content pull request #25536
Opened 2023-03-22 13:23 UTC by deepug9787

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-23 23:53 UTC, estelle requested changes

2023-03-23 23:53 UTC, estelle commented on files/en-us/web/css/css_grid_layout/relationship_of_grid_layout/index.md
> +So not only do we now have the ability to create a grid with a dynamic number of flexible tracks, we can also have the items laid out
The original was written when this was a new feature. I suggest we get rid of the "now" new language.

2023-03-27 02:55 UTC, joziasmartini commented
Hey @estelle, remove this trailing space after the sentence to unblock the merge.

![image](https://user-images.githubusercontent.com/31961274/227829454-36867f8c-496a-46a7-b948-044c18d13364.png)

2023-03-28 05:50 UTC, teoli2003 commented
@deepug9787 You should fix the sentence as Estelle requested, too.

2023-04-02 13:35 UTC, deepug9787 commented
@teoli2003 If you notice, that sentence is actually a conclusion of a section titled "A flexible number of tracks", which explains how we can achieve a flexbox-like wrapping functionality using the `auto-fit` and` minmax()` function in grid. So the "now" in that sentence refers to the result of the steps we've taken in that section to achieve the desired functionality, and not the current state of browser support for those grid features. 

Could you please confirm whether you want me to fix the sentence as @estelle requested?

2023-05-09 20:40 UTC, estelle commented on files/en-us/web/css/css_grid_layout/relationship_of_grid_layout/index.md
> +So not only do we now have the ability to create a grid with a dynamic number of flexible tracks, we can also have the items laid out on the grid aligned by rows and columns.
```suggestion
With grid layout, we can create a grid with a dynamic number of flexible tracks and have the items laid out on the grid aligned by rows and columns.
```

2023-05-09 20:41 UTC, estelle approved these changes

2023-05-09 20:41 UTC, merged