Add a Performance guide for Server Timing
mdn/content pull request #25575
Opened 2023-03-23 16:14 UTC by Elchi3

### Description

Adds a guide page for Server Timing.

Ideally, https://github.com/mdn/content/pull/25508 lands first because then I can:

- add this guide to group data
- update the main performance page to link to this guide

(If it doesn't land first then I will update #25508 to include this page.)

### Motivation

Part of https://github.com/openwebdocs/project/issues/62

### Additional details

None.

2023-03-23 18:36 UTC, dawei-wang reviewed
A couple of grammar suggestions

2023-03-23 18:36 UTC, dawei-wang commented on files/en-us/web/api/performance_api/server_timing/index.md
> +The `Server-Timing` header may expose potentially sensitive application and infrastructure information. Consider to control which metrics are returned when and to whom on the server side. For example
```suggestion
The `Server-Timing` header may expose potentially sensitive application and infrastructure information. Consider controlling which metrics are returned when and to whom on the server side. For example, you could only show metrics to authenticated users and nothing to the public.
```

2023-03-23 18:36 UTC, dawei-wang commented on files/en-us/web/api/performance_api/server_timing/index.md
> +To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your ser
```suggestion
To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your server uses Node.js, the performance measurement APIs will look very familiar to the Performance API in browsers as the Node.js performance module is a subset of the W3C Web Performance APIs as well as additional APIs for Node.js-specific performance measurements. See the [Node.js performance documentation] (https://nodejs.org/api/perf_hooks.html#performance-measurement-apis) for more information.
```

2023-03-23 20:42 UTC, dawei-wang reviewed
linting

2023-03-23 20:42 UTC, dawei-wang commented on files/en-us/web/api/performance_api/server_timing/index.md
> +To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your ser
```suggestion
To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your server uses Node.js, the performance measurement APIs will look very familiar to the Performance API in browsers as the Node.js performance module is a subset of the W3C Web Performance APIs as well as additional APIs for Node.js-specific performance measurements. See the [Node.js performance documentation](https://nodejs.org/api/perf_hooks.html#performance-measurement-apis) for more information.
```

2023-04-27 00:02 UTC, wbamberg reviewed
This is generally great. One optional comment.

It is would be good if https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing described the syntax of this header in a helpful way.

I mean it could say something like:

> This header contains one or more metrics, separated by commas. Each metric has a name, an optional duration, and an optional description. These components are separated by semi-colons.
>
> The duration component consists of the string `"dur"`, followed by `"="`, followed by the value, like `"dur=23.2"`.
>
> The description component consists of the string `"desc"`, followed by `"="`, followed by the value, like `"desc=DB lookup"`.

Somewhere it might be worth spelling out that these components map to `PerformanceServerTiming` values like:

- "name" -> `PerformanceServerTiming.name`
- "dur" -> `PerformanceServerTiming.duration`
- "desc" -> `PerformanceServerTiming.description`

2023-05-16 13:39 UTC, dipikabh requested changes
Thanks for adding this guide, @Elchi3!

I've added a few edit suggestions
(for some reason, the preview links are not working)

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +Server Timing is part of the Performance API and allows servers to communicate metrics about the request-response cycle to the user agent. This allows you to collect and act on server-side metrics in
- How about rephrasing "This allows" to clarify what "This" is and I am guessing we mean "enables" here instead of "allows"

```suggestion
Server timing is a part of the Performance API and allows servers to communicate metrics about the request-response cycle to the user agent. You can collect this information and act on server-side metrics in the same way as all the other metrics processed with the Performance API.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +The {{HTTPHeader("Server-Timing")}} HTTP header is used to surface any backend server timing metrics. For example, you might want to send database read/write operation times, CPU time, file system ac
```suggestion
The {{HTTPHeader("Server-Timing")}} HTTP header is used to surface any backend server timing metrics. For example, you might want to send database read/write operation times, CPU time, and file system access.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +You can send metrics with or without values. They can optionally contain a description. It is advised to keep names, description and data as short as possible to minimize the HTTP overhead.
```suggestion
You can send metrics with or without values. The metrics can optionally contain a description. It is advised to keep names, descriptions, and data as short as possible to minimize the HTTP overhead.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +Example `Server-Timing` headers:
should this be a heading "Examples"? or if not heading, something like this:

```suggestion
Examples of `Server-Timing` headers:
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +// Two metrics with value
```suggestion
// Two metrics with values
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your ser
Splitting the long sentence. This part seems to be missing something "as well as additional APIs for Node.js-specific performance measurements."

```suggestion
To calculate real server-side metrics, consult the documentation of your server-side CMS, framework, or programming language for how to measure performance within the backend application. If your server uses Node.js, the performance measurement APIs will look very familiar to the Performance API in browsers. This is because the Node.js performance module is a subset of the W3C Web Performance APIs as well as additional APIs for Node.js-specific performance measurements. See the [Node.js performance documentation](https://nodejs.org/api/perf_hooks.html#performance-measurement-apis) for more information.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +Note that there is no clock synchronization between the server, the client and any intermediate proxies. This means that if your server sends timestamps or a `startTime` it might not meaningfully map
```suggestion
Note that there is no clock synchronization between the server, the client, and any intermediate proxies. This means that if your server sends timestamps or a `startTime`, the value might not meaningfully map to the {{domxref("PerformanceEntry.startTime", "startTime")}} of the client's timeline.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +Once you have calculated your desired metrics, the server needs to send the `Server-Timing` header in its response. See the {{HTTPHeader("Server-Timing")}} reference page for how to send the header i
```suggestion
Once you have calculated your desired metrics, the server needs to send the `Server-Timing` header in its response. See the {{HTTPHeader("Server-Timing")}} reference page for an example of how to send the header in Node.js.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +The server timing metrics usually appear in the developer tools of the browser, but they are also stored as {{domxref("PerformanceServerTiming")}} performance entries which allows you to access them
```suggestion
The server timing metrics usually appear in the developer tools of the browser, but they are also stored as {{domxref("PerformanceServerTiming")}} performance entries that you can access like other [performance data](/en-US/docs/Web/API/Performance_API/Performance_data). However, there are no `"server-timing"` entries on their own. The `PerformanceServerTiming` objects are observable from `"navigation"` and `"resource"` performance entries. You access the server metrics from the {{domxref("PerformanceResourceTiming.serverTiming")}} property, which is an array of `PerformanceServerTiming` objects.
```

2023-05-16 13:39 UTC, dipikabh commented on files/en-us/web/api/performance_api/server_timing/index.md
> +The `Server-Timing` header may expose potentially sensitive application and infrastructure information. Consider controlling which metrics are returned when and to whom on the server side. For exampl
```suggestion
The `Server-Timing` header may expose potentially sensitive application and infrastructure information. Therefore, you need to control when the metrics are returned and to whom on the server side. For example, you could show metrics only to authenticated users and nothing to the public.
```

2023-05-17 10:25 UTC, Elchi3 commented
Thanks so much for your review @dipikabh and @wbamberg! I applied the fantastic suggestions and also updated the `Server-Timing` page to be more useful.

2023-05-17 16:44 UTC, dipikabh approved these changes
LGTM. Thanks for the updates!

2023-05-17 16:55 UTC, wbamberg approved these changes
👍 thank you @Elchi3 !

2023-05-17 16:55 UTC, merged