Document WebGLContextEvent()
mdn/content pull request #25622
Opened 2023-03-25 10:26 UTC by teoli2003

### Description

Add documentation for:

- `WebGLContextEvent()`

### Motivation

openwebdocs/project#152

### Additional details

- Detected thanks to this fix in the mdn-gaps tool: dontcallmedom/mdn-gaps#2 

### Related issues and pull requests

- BCD PR to add the missing `mdn_url` entry: mdn/browser-compat-data#TBD

2023-03-25 18:12 UTC, dawei-wang reviewed
minor grammar edit

2023-03-25 18:12 UTC, dawei-wang commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +  - : An object that, _in addition of the properties defined in {{domxref("Event/Event", "Event()")}}_, has the following properties:
```suggestion
  - : An object that, _in addition to the properties defined in {{domxref("Event/Event", "Event()")}}_, has the following properties:
```

2023-03-27 10:47 UTC, Elchi3 requested changes
Some nits, looks great otherwise

2023-03-27 10:47 UTC, Elchi3 commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +    - `status` {{Optional_inline}}
```suggestion
    - `statusMessage` {{Optional_inline}}
```

2023-03-27 10:47 UTC, Elchi3 commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +> **Note:** A web developer doesn't typically need to call this constructor, as the browser creates these objects itself when firing events.
I think we usually use "You" to talk to all readers, not just web developers. Also, I think people would come to this page because they want to trigger a context event manually. For that, there is a dedicated function available, so mention it here.

```suggestion
> **Note:** You typically don't need to call this constructor; the browser creates these objects automatically when WebGL context events get fired. To manually trigger a `webglcontextlost` event, use {{domxref("WEBGL_lose_context.loseContext()")}}.
```

2023-03-27 10:47 UTC, Elchi3 commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +  - : A string with the name of the event.
```suggestion
  - : A string indicating the type of the event.
```

2023-03-27 10:47 UTC, Elchi3 commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +    It is case-sensitive and browsers set it to `webglcontextcreationerror`, `webglcontextlost`, or `weblcontextrestored`.
```suggestion
    It is case-sensitive and should be one of `webglcontextcreationerror`, `webglcontextlost`, or `weblcontextrestored`.
```

2023-03-27 10:47 UTC, Elchi3 commented on files/en-us/web/api/webglcontextevent/webglcontextevent/index.md
> +      - : A string with some additional status information. It defaults to the empty string (`""`).
```suggestion
      - : A string with additional status information. It defaults to the empty string (`""`).
```

2023-03-27 10:56 UTC, Elchi3 approved these changes

2023-03-27 10:56 UTC, merged