FF87 removing -moz media features
mdn/content pull request #2567
Opened 2021-02-22 09:43 UTC by rachelandrew

Part of #2515 removes links to features, and adds a release note.

2021-02-28 06:04 UTC, mathewhodson commented
I don't think this needs to be added to the release notes, because according to https://bugzilla.mozilla.org/show_bug.cgi?id=787521 these were disabled in web content a while ago.

2021-03-15 20:55 UTC, chrisdavidmills requested changes
Dammnit, I wrote a review of this one, but then somehow didn't end up submitting it. Sorry about that @rachelandrew

2021-03-16 16:38 UTC, chrisdavidmills commented on files/en-us/web/css/mozilla_extensions/index.html
> - <li>{{CSSxRef("@media/-moz-mac-graphite-theme", "-moz-mac-graphite-theme")}}{{gecko_minversion_inline("1.9.2")}}</li>
Actually, let's not worry about this one.

2021-03-16 16:38 UTC, chrisdavidmills approved these changes
Done a bit of copy editing, and now this one is ready to go in.

2021-03-16 16:39 UTC, merged