Express Tute: NVM to install node rather than packagers/installers
mdn/content pull request #25693
Opened 2023-03-28 06:18 UTC by hamishwillee

This updates the Express dev environment setup to suggest using nvm or nvm-windows to setup your node and npm environment. Previously it suggested using installers and package managers.

Why? Well, I wish I knew about package managers when I started, because they make upgrading a lot easier. I think most developers end up using them, and they are really no harder than using installers.

In addition, they make the instructions easier, because less will have to change next time we update versions of node to a new LTS.

Note that I kept the links to info about package managers/installers, so people can still try that. 

This is a precursor to updates for async behaviour that have been tested in https://github.com/mdn/express-locallibrary-tutorial/pull/170

2023-03-28 06:38 UTC, teoli2003 requested changes

2023-03-28 06:38 UTC, teoli2003 commented on files/en-us/learn/server-side/express_nodejs/development_environment/index.md
> +At time of writing the LTS version of nodejs is 18.15.0.
```suggestion
At the time of writing, the LTS version of nodejs is 18.15.0.
```

2023-03-28 06:38 UTC, teoli2003 commented on files/en-us/learn/server-side/express_nodejs/development_environment/index.md
> +Once you have set NVM to use a particular ndoe version, you can test that node is installed is to run the "version" command in your terminal/command prompt and check that a version string is returned
This is the only place (I think) where you used capitalized NVM and it looks a bit odd:
```suggestion
Once you have set `nvm` to use a particular  version, you can test that node is installed is to run the "version" command in your terminal/command prompt and check that a version string is returned:
```

2023-03-28 21:34 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/development_environment/index.md
> +Once you have set NVM to use a particular ndoe version, you can test that node is installed is to run the "version" command in your terminal/command prompt and check that a version string is returned
Thanks very much. I did a slight variation.

2023-03-28 21:35 UTC, hamishwillee commented
Thanks very much for review. Accepted changes. Ready again.

2023-03-29 04:12 UTC, teoli2003 approved these changes
👍

2023-03-29 04:12 UTC, merged