Update index.md
mdn/content pull request #25784
Opened 2023-03-30 19:33 UTC by jo777750

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-03-31 06:10 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +<h3>Heading 4</h3>
Please  change `<h3>Heading 4</h3>` to `<h4>Heading 4</h4>`

2023-04-02 06:51 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +h1 {
Can you group `h1` and `h3` as they are the same?

2023-04-02 06:56 UTC, teoli2003 requested changes
I made a first pass of review.

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +   color: var(--colorPrimary); /* font color is  yellow */
Fix indentation
```suggestion
  color: var(--colorPrimary); /* font color is  yellow */
```

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +
No blank line here.
```suggestion
```

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +
No blank line here
```suggestion
```

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +Using [CSS](/en-US/docs/Web/CSS) {{cssxref('@property')}} [at-rule](/en-US/docs/Web/CSS/At-rule):
As there are 2 examples now, we need to use an H3 heading (`###`) with a title, as well as a short description of the example. It is not obvious what the purpose of the example is.

Once we have a title we can add an `{{EmbedLiveSample}}` macro and tests in the page if it actually works.

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +}
Missing blank line:
```suggestion
}

```

2023-04-02 06:56 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +   color: var(--colorPrimary); /* font color is magenta */
Wrong identation. Please run Prettier locally (`npx -w prettier files/en-us/web/css/@property/index.md`) or fix the indentation (2 spaces not 3)

2023-04-02 09:35 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +h1 {
Yes , can I paste the new code here?

2023-04-02 16:00 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +Using [CSS](/en-US/docs/Web/CSS) {{cssxref('@property')}} [at-rule](/en-US/docs/Web/CSS/At-rule):
how can I add a title or if you can add title it will be helpful for me in future..Thanks

2023-04-02 16:02 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +   color: var(--colorPrimary); /* font color is  yellow */
Done

2023-04-02 17:38 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +   color: var(--colorPrimary); /* font color is magenta */
Done, fixed indentation

2023-04-02 18:34 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +Using [CSS](/en-US/docs/Web/CSS) {{cssxref('@property')}} [at-rule](/en-US/docs/Web/CSS/At-rule):
This not done

2023-04-02 18:35 UTC, teoli2003 commented on files/en-us/web/css/@property/index.md
> +h1 {
This is not done

2023-04-03 03:49 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +h1 {
h1 and h3 now have different functionalities with one being a default one and the other a fallback one so they are not the same

2023-04-03 03:53 UTC, jo777750 commented on files/en-us/web/css/@property/index.md
> +Using [CSS](/en-US/docs/Web/CSS) {{cssxref('@property')}} [at-rule](/en-US/docs/Web/CSS/At-rule):
already provided the following info:
### Normal and Fallback working example for @property CSS tag

Here we try to show as to how CSS is applied in default condition using @property tag and how fallback happens to default case in case the value of @property tag is invalid.

2023-04-05 17:26 UTC, closed without merging