Added warning media and container queries
mdn/content pull request #25874
Opened 2023-04-03 12:40 UTC by advitiya7

### Description

A note has been added with a little explanation

### Motivation

### Additional details

### Related issues and pull requests

fixes #25226

2023-04-03 12:46 UTC, advitiya7 commented
@estelle  @sideshowbarker i have added the neccesary changes please check thanks

2023-04-03 17:20 UTC, dawei-wang reviewed
A few typos

2023-04-03 17:20 UTC, dawei-wang commented on files/en-us/web/css/using_css_custom_properties/index.md
> +> **Note:** Variables do not work inside media queries and container queries.The {{cssxref("var", "var()")}} function can be used in place of any part of a value in any property on an element.The {{c
```suggestion
> **Note:** Variables do not work inside media queries and container queries. The {{cssxref("var", "var()")}} function can be used in place of any part of a value in any property on an element. The {{cssxref("var", "var()")}} function cannot be used as property names, selectors, or anything else besides property values. So, we can't use it in a media query or container query.
```

2023-04-03 17:46 UTC, dawei-wang commented
@advitiya7 no worries. The changes look good. By the way, there is an extra blank line on line 18.

2023-04-03 18:27 UTC, dawei-wang commented
Try removing line 17 or line 18 from the TouchEvent/touches doc. Sorry I didn't clarify which file earlier.

2023-04-03 18:31 UTC, advitiya7 commented
@dawei-wang i have removed the blank line

2023-04-03 18:34 UTC, dawei-wang commented
Looks good to me

2023-04-03 18:36 UTC, advitiya7 commented
> 

can you merge this PR?

2023-04-03 18:59 UTC, teoli2003 requested changes

2023-04-03 18:59 UTC, teoli2003 commented on files/en-us/web/api/touchevent/touches/index.md
> -
This is unrelated and shouldn't be removed.

2023-04-03 19:05 UTC, advitiya7 commented on files/en-us/web/api/touchevent/touches/index.md
> -
@teoli2003 i am really sorry i dont know what to do now and this came up with it can you please guide me what do i need to do?

2023-04-03 23:19 UTC, hamishwillee commented on files/en-us/web/api/touchevent/touches/index.md
```suggestion

```suggestion
> **Note:** Touches inside the array are not necessarily ordered by order of occurrences (the
i-th element in the array being the i-th touch that happened). You cannot assume a specific order. To determine the order of occurrences of the touches, use the `touch` object IDs.
```
```

2023-04-03 23:22 UTC, hamishwillee commented on files/en-us/web/api/touchevent/touches/index.md
> -
@advitiya7 He's saying that this change has nothing to do with the rest of the PR, and is probably incorrect. The solution is to put it back, which I have done.

@teoli2003 I'm not reviewing this otherwise, so back to you.

2023-04-04 01:47 UTC, advitiya7 commented on files/en-us/web/api/touchevent/touches/index.md
> -
Should i just delete this PR and make a new one? I might have messed this up and i am really sorry for that.

2023-04-04 04:23 UTC, advitiya7 commented
@teoli2003 please check the changes have been made
@hamishwillee thankyou for the doing the change can you please tell me how did you do it?
 thanks

2023-04-04 04:33 UTC, teoli2003 approved these changes
👍

2023-04-04 04:33 UTC, merged

2023-04-04 04:47 UTC, hamishwillee commented
@advitiya7 You can see what I did in the commits tab - https://github.com/mdn/content/pull/25874/commits

Essentially I was going to add a line to the PR using a "suggestion" - you can see how to do that here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

But I stuffed it up and omitted the some backticks. So I had to edit the page itself and add back the text in the right place. That is what the second commit I created does.

2023-04-04 04:55 UTC, advitiya7 commented
> @advitiya7 You can see what I did in the commits tab - https://github.com/mdn/content/pull/25874/commits
> 
> Essentially I was going to add a line to the PR using a "suggestion" - you can see how to do that here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request
> 
> But I stuffed it up and omitted the some backticks. So I had to edit the page itself and add back the text in the right place. That is what the second commit I created does.

thanks @hamishwillee i will check that