added clear message of the data encoded by using float32array
mdn/content pull request #25878
Opened 2023-04-03 15:08 UTC by MohitMaheshwari1711

### Description

Missing encoding of the waveform. Because the parameter is a Float32Array, one can reasonably assume that the encoding is f32 (that is, PCM data amplitude in [-1:1]). However it would be better to confirm this in writing instead of leaving developers to their guess. There's also no mention of planar/non-planar encoding, which is necessary to do anything with the data retrieved (unless the signal has a single channel).

Added text - "The time-domain data is encoded in `f32` format with the amplitude of samples in [-1:1]" for the following urls for clarity :

- https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatFrequencyData
- https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatTimeDomainData

### Motivation

Better clarity for users going through the docs

### Related issues and pull requests

Issue :- #25571

2023-04-04 07:39 UTC, teoli2003 commented
@padenot Can you confirm the format is `f32` (and not something different like `f32-planar`, …

(There will be some additional work to be done afterwards, but let's wait for the answer here)

2023-04-04 09:11 UTC, padenot commented
As noted, planar and interleaved arrangements are equivalent if there is only a single channel of audio, and here there's always a single channel of audio ([reference from the spec]):

> When the current time-domain data are computed, the input signal must be [down-mixed](https://webaudio.github.io/web-audio-api/#channel-up-mixing-and-down-mixing) to mono as if [channelCount](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcount) is 1, [channelCountMode](https://webaudio.github.io/web-audio-api/#dom-audionode-channelcountmode) is "[max](https://webaudio.github.io/web-audio-api/#dom-channelcountmode-max)" and [channelInterpretation](https://webaudio.github.io/web-audio-api/#dom-audionode-channelinterpretation) is "[speakers](https://webaudio.github.io/web-audio-api/#dom-channelinterpretation-speakers)".

Nothing prevents sample to exceed `[-1.0, 1.0]` in the time domain version of the function. For the frequency domain, the numbers are not really limited, number can be -Infinity when the input is silent, or over 1.0 if the input has peaks that exceed `[-1.0, 1.0]`.

[reference from the spec]: https://webaudio.github.io/web-audio-api/#time-domain-down-mixing

2023-04-05 05:17 UTC, MohitMaheshwari1711 commented
Hey @teoli2003 

Do let me know if we need to make any further changes for the same

2023-04-05 07:03 UTC, teoli2003 requested changes
Yes: as there are no constrains about being inside [-1; 1], we shouldn't mention this. Also mentioning `f32` is not useful as the distinction between planar and interleaved is moot in the case of a single channel)

2023-04-05 07:03 UTC, teoli2003 commented on files/en-us/web/api/analysernode/getfloatfrequencydata/index.md
> +The **`getFloatFrequencyData()`** method of the {{domxref("AnalyserNode")}} Interface copies the current frequency data into a {{jsxref("Float32Array")}} (the time-domain data is encoded in f32 forma
```suggestion
The **`getFloatFrequencyData()`** method of the {{domxref("AnalyserNode")}} Interface copies the current frequency data into a {{jsxref("Float32Array")}} array passed into it. Each array value is a _sample_, the magnitude of the signal at a particular time.
```

2023-04-05 07:03 UTC, teoli2003 commented on files/en-us/web/api/analysernode/getfloattimedomaindata/index.md
> +The **`getFloatTimeDomainData()`** method of the {{ domxref("AnalyserNode") }} Interface copies the current waveform, or time-domain, data into a {{jsxref("Float32Array")}} (the time-domain data is e
```suggestion
The **`getFloatTimeDomainData()`** method of the {{ domxref("AnalyserNode") }} Interface copies the current waveform, or time-domain, data into a {{jsxref("Float32Array")}} array passed into it. Each array value is a _sample_, the magnitude of the signal at a particular time.
```

2023-04-05 08:33 UTC, teoli2003 approved these changes

2023-04-05 08:34 UTC, merged

2023-04-05 08:34 UTC, teoli2003 commented
Thanks Paul for the clarification!

2023-04-05 11:38 UTC, djee-ms commented
Ok but then that change doesn't clarify much in my opinion once the range has been removed. Unless we explain what is mentioned above in comments that the samples are typically in [-1:1] range but can get beyond that, and/or link some spec, the added sentence doesn't tell me much as a developer. At the very least, since "samples" is highlighted, I assume this means that there's a formal definition to it somewhere, which might gives more hint, and so it would be welcome to link that definition here so that developers can easily come to the conclusion that data is _typically_ in [-1:1] range (the "classic" PCM float32 sample format found in most audio contexts).