Remove erroneous slash in URL
mdn/content pull request #26005
Opened 2023-04-07 18:03 UTC by teoli2003

No slash needed before the anchor.

2023-04-08 18:26 UTC, wbamberg commented on files/en-us/web/api/featurepolicy/getallowlistforfeature/index.md
> +An [allowlist](/en-US/docs/Web/HTTP/Permissions_Policy#allowlists) for the
But this is a bit misleading isn't it?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy#allowlists looks like it is a string, containing "one or more of the following values contained in parentheses, separated by spaces". But the return value from this method seems to be an array of strings: https://w3c.github.io/webappsec-permissions-policy/#the-policy-object.

2023-04-26 13:39 UTC, Elchi3 commented on files/en-us/web/api/featurepolicy/getallowlistforfeature/index.md
> +An [allowlist](/en-US/docs/Web/HTTP/Permissions_Policy#allowlists) for the
```suggestion
An array of strings containing the serialized allowlisted origins for the feature. If a wildcard (`*`) is used, the array will contain `*`. 
```

2023-04-26 13:42 UTC, Elchi3 requested changes
I think Will is right, the better fix would be to correct the return value.

2023-04-26 14:45 UTC, teoli2003 commented on files/en-us/web/api/featurepolicy/getallowlistforfeature/index.md
>  specified feature.
```suggestion
```

2023-04-26 14:46 UTC, teoli2003 commented on files/en-us/web/api/featurepolicy/getallowlistforfeature/index.md
> +An array of strings containing the serialized allowlisted origins for the feature. If a wildcard (`*`) is used, the array will contain `*`.
```suggestion
An array of strings containing the serialized list of allowed origins for the feature. If a wildcard (`*`) is used, the array will contain `*`. 
```

2023-04-26 14:46 UTC, teoli2003 commented
I reworded a bit your proposal, @Elchi3.

2023-04-26 15:24 UTC, Elchi3 approved these changes
LGTM!

2023-04-26 15:24 UTC, merged