New page: CSS filter functions guide
mdn/content pull request #26096
Opened 2023-04-10 18:56 UTC by estelle

Creates a new filter functions page. Will create a link CSS filter effects module pages after this goes live.

2023-04-11 20:40 UTC, dipikabh requested changes
Great stuff, @estelle! Thanks for adding this content. 
I've reviewed till "Applying multiple filters". I'll look at the remaining tomorrow.

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The default value listed is the value that creates no effect. While they create no effect, they are the initial interpolation value, provide an example of how the value can be set, and provide a guag
```suggestion
The minimum value allowed is included for filter functions that have a minimum value. Including a value less than the minimum value for any filter function invalidates the entire property declaration, not just the invalid function in the comma-separated list.

A maximum effect value can be exceeded. Including a value greater than the listed maximum value is valid, but it does not increase the effect over the listed maximum value. In other words, the effect on the element will look the same as when the maximum effect value is set. For example, setting `sepia(400%)` in the [Basic example](#basic_example) will produce the same effect as `sepia(100%)`, the maximum value.

The default value is a value that creates no effect. While they create no effect, they are the initial interpolation value and offer an example of how the value can be set. They provide a gauge between the minimum value allowed and the maximum effect value.
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The `filter` and `backdrop-filter` properties take as their value a filter function list, containing one or more {{CSSXref("filter-function")}}s, the default keyword `none`, or an SVG filter using `u
```suggestion
The `filter` and `backdrop-filter` properties accept a filter function list, which may contain one or more `<filter-function>`s, the default keyword `none`, or an SVG filter using the `url()` syntax.
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +If you haven't ever hovered over a black-and-white or sepia image and the full-color image came into view instantly, here's your chance!
```suggestion
If you hover over the sepia image below, you'll see the full-color image come into view instantly!

The image is set to be sepia by specifying the value of the `filter` property as the [`sepia()`](/en-US/docs/Web/CSS/filter-function/sepia) filter function. The filter is removed on [`:hover`](/en-US/docs/Web/CSS/:hover) and [`:focus`](/en-US/docs/Web/CSS/:focus) by setting `filter: none`. 
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The image is set to be sepia by default by including the [`sepia()`](/en-US/docs/Web/CSS/filter-function/sepia) filter function as the value of the `filter` property. The filter is removed on [`:hove
```suggestion
In the {{HTMLElement("img")}} element, [`tabindex`](/en-US/docs/Web/HTML/Global_attributes/tabindex) is set to `0` to enable focus without altering the tabbing order for keyboard users because `<img>` is not an interactive element.
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +### Basic example
How about the following to be more explicit:

```suggestion
### Applying sepia filter effect
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +## Applying filter effects
```suggestion
## Examples
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +While the basic example used only the a sepia filter, we are not limited to a single filter. The `filter` and `backdrop-filter` properties accept a space-separated list of filters which are applied i
This info seems important to also list in the "Filter effect properties" section.

```suggestion
While the sepia filter example uses a single `filter` property, you can set more than one filter. The `filter` and `backdrop-filter` properties accept a space-separated list of filters, which are applied in the order declared.
```

2023-04-11 20:40 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +This example applies two filters — a [`hue-rotate()`](/en-US/docs/Web/CSS/filter-function/hue-rotate) and a [`blur()`](/en-US/docs/Web/CSS/filter-function/blur) — via the `backdrop-filter` CSS proper
```suggestion
This example applies two filters — [`hue-rotate()`](/en-US/docs/Web/CSS/filter-function/hue-rotate) and [`blur()`](/en-US/docs/Web/CSS/filter-function/blur) — via the `backdrop-filter` property. The paragraph color shifts to the area behind the {{HTMLElement("p")}} element.
```

2023-04-12 06:26 UTC, estelle commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +## Applying filter effects
I want to keep the original. While there are many examples, the point of the examples is to show how to apply filter effects; so want to keep the purpose of the less, rather than the method of teaching, as the title.

2023-04-12 15:23 UTC, estelle commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +Have you ever hovered over a black-and-white or sepia image and the full-color image came into view instantly? Have you ever encountered a background image with a small blurred-out section that makes
```suggestion
Have you ever hovered over a black-and-white or sepia image and the full-color image came into view instantly? Have you ever encountered a background image with a small blurred-out section that makes the text on top more legible? In the past, these manipulations used to require image editing software, time, and HTTP requests.
```

2023-04-13 02:23 UTC, dipikabh requested changes
done with reviewing the second half

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +As filters are applied in sequential order, we are not limited to using filter functions just once. In this example, we include the [`drop-shadow()`](/en-US/docs/Web/CSS/filter-function/drop-shadow)
```suggestion
As filters are applied in sequential order, you can use filter functions more than once. In this example, the [`drop-shadow()`](/en-US/docs/Web/CSS/filter-function/drop-shadow) filter has been used four times, each time with a different `<shadow>` value.
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +In the first Manadala example, four drop shadows are applied to a line-drawn SVG. The same SVG, with the filter removed with `filter: none`, is included for comparison.
```suggestion
In the first Manadala example, four drop shadows are applied to a line-drawn SVG. The same SVG, with the filter removed with `filter: none`, is shown in the side for comparison.
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +### Filter function order
To maintain the 'ing' form in the title heading like the previous H3 ones:

```suggestion
### Specifying the filter function order
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +In this example, we include both a magenta drop shadow and a `180deg` hue rotation on the level-one heading, but these filters are applied in different order:
```suggestion
In this example, both `magenta` drop shadow and `180deg` hue rotation are applied on the level-one heading. The example shows the effect when these filters are applied in different orders.
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +> **Note:** The hexadecimal rgb color `#191970` is equal to `hsl(240deg 63.5% 26.9%)` while `#252500` is `hsl(60deg 100% 7.3%)`. The [color rotation takes place in the sRGB color space](/en-US/docs/W
```suggestion
The same filters are applied to both lines of text but in a different order. In the first line, the hue of the text is altered before the shadow is applied; so the shadow is `magenta`. In the second line, the drop shadow is added to the dark blue text, and then the hue of both the text and the shadow are altered.

No filter effect is applied to the third line to show the original effect as a comparison. So the third line stays as `midnightblue` or `#191970`. The `hue-rotate(180deg)` filter changes the text in the first two lines to `#252500`.

> **Note:** The hexadecimal rgb color `#191970` is equal to `hsl(240deg 63.5% 26.9%)`, while `#252500` is `hsl(60deg 100% 7.3%)`. The [color rotation takes place in the sRGB color space](/en-US/docs/Web/CSS/color_value#interpolation), which is why the hue has been changed as expected while not maintaining the same values for saturation and lightness.
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +### Blur example
```suggestion
### Blurring an image
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +In both cases, the blur radius value, defined as a {{cssxref("&lt;length&gt;")}} in CSS and a pixel equivalent {{cssxref("&lt;number&gt;")}} in SVG, defines the value of the standard deviation to the
```suggestion
In both the cases, the blur radius value, specified as a {{cssxref("&lt;length&gt;")}} in CSS and as a pixel equivalent {{cssxref("&lt;number&gt;")}} in SVG, defines the value of the standard deviation to the Gaussian function. In other words, it defines the number of pixels on the screen that blend into each other; a larger value creates more blur.
```

2023-04-13 02:23 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +- [Applying SVG effects to HTML content](/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content)
```suggestion
- {{cssxref("mask")}}
- {{cssxref("background-blend-mode")}}, {{cssxref("mix-blend-mode")}}
- [CSS filter effects](/en-US/docs/Web/CSS/Filter_Effects)
- SVG {{SVGElement("filter")}} element, SVG {{SVGAttr("filter")}} attribute in [SVG](/en-US/docs/Web/SVG)
- [Applying SVG effects to HTML content](/en-US/docs/Web/SVG/Applying_SVG_effects_to_HTML_content)
```

2023-04-13 07:18 UTC, teoli2003 commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +slug: Web/CSS/filter_effects/Using_filter_effects
```suggestion
slug: Web/CSS/Filter_Effects/Using_filter_effects
```

2023-04-13 07:19 UTC, teoli2003 commented on files/en-us/web/css/filter_effects/index.md
> +- [Using CSS filter effects](/en-US/docs/Web/CSS/filter_effects/using_filter_effects)
Fixing the flaw
```suggestion
- [Using CSS filter effects](/en-US/docs/Web/CSS/Filter_Effects/Using_filter_effects)
```

2023-04-14 13:38 UTC, dipikabh requested changes

2023-04-14 13:38 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The CSS filter effects module provides 10 [`<filter-function>`](/en-US/docs/Web/CSS/filter#functions) functions, as well as the ability to define an almost endless array of effects using SVG filters
```suggestion
The CSS filter effects module provides 10 [`<filter-function>`](/en-US/docs/Web/CSS/filter#functions) functions, as well as the ability to define an almost endless array of effects using SVG filters applied via a `url()` reference.
```

2023-04-14 13:38 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The default value is a value that creates no effect. While these values create no effect, they are the initial interpolation value and offer an example of how the value can be set. These default valu
```suggestion
The default value is a value that creates no effect. While these values create no effect, they provide the initial interpolation values and offer an example of how the value can be set. These default values provide a gauge between the minimum value allowed and the maximum effect value.
```

2023-04-14 13:38 UTC, dipikabh commented on files/en-us/web/css/filter_effects/using_filter_effects/index.md
> +The same filters are applied to both lines of text but in a different order. In the first line, the hue of the text is altered before the shadow is applied; so the shadow is `magenta`. In the second
```suggestion
The same filters are applied to both the lines of text but in a different order. In the first line, the hue of the text is altered before the shadow is applied, so the shadow is `magenta`. In the second line, the drop shadow is added to the dark blue text, and then the hue of both the text and the shadow are altered.
```

2023-04-14 13:41 UTC, dipikabh approved these changes

2023-04-14 13:45 UTC, merged

2023-04-14 13:45 UTC, dipikabh commented
Thanks @estelle 👍