Caching note - sending both ETag and If-Modified ..
mdn/content pull request #26108
Opened 2023-04-11 07:19 UTC by hamishwillee

Fixes #26064 using a slightly modified form of the comment provided by @Jxck .

The difference is that the note starts with direction for the user "send both headers", and then explains why. Generally this is a better way to write because people scanning the material get the point first.

2023-04-11 07:21 UTC, hamishwillee commented on files/en-us/web/http/caching/index.md
This just rearranges the origianl suggestion by Jxck

> **Note:** When evaluating how to use `ETag` and `Last-Modified`, consider the following:
> during cache revalidation, if both `If-Modified-Since` and `If-None-Match` are present, then `If-None-Match` takes precedence for the validator.
> If you are only considering caching, you may think that `Last-Modified` is unnecessary.
> However, `Last-Modified` is not just useful for caching; it is a standard HTTP header that is also used by content-management (CMS) systems to display the last-modified time, by crawlers to adjust crawl frequency, and for other various purposes.
> So considering the overall HTTP ecosystem, it is better to provide both `ETag` and `Last-Modified`.
> This is why RFC9110 prefers that server should send both `ETag` and `Last-Modified` for a `200` response if possible.

2023-04-11 07:59 UTC, teoli2003 requested changes
One sentence sounded strange, but else it is 👍

2023-04-11 07:59 UTC, teoli2003 commented on files/en-us/web/http/caching/index.md
> +> **Note:** RFC9110 prefers that servers should send both `ETag` and `Last-Modified` for a `200` response if possible.
```suggestion
> **Note:** RFC9110 prefers that servers send both `ETag` and `Last-Modified` for a `200` response if possible.
```

2023-04-14 01:27 UTC, hamishwillee commented
Thanks. Accepted your change @teoli2003 - ready for re-review

2023-04-14 05:34 UTC, teoli2003 approved these changes
👍

2023-04-14 05:34 UTC, merged

2024-04-30 00:27 UTC, bigbigDreamer commented
https://github.com/jshttp/fresh/pull/38

In the process of discussing retrospectives, a "fresh" PR (Pull Request) is also included as one of the changes.