Adds ExtendableCookieChangeEvent
mdn/content pull request #2613
Opened 2021-02-23 11:43 UTC by rachelandrew

This is the Service Worker version of `CookieChangeEvent` so it may require changed based on what we decide with that one.

https://wicg.github.io/cookie-store/#ExtendableCookieChangeEvent

Reviewer: @jpmedley

2021-02-24 16:12 UTC, jpmedley requested changes

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +  <dd>Returns an object containing the deleted cookie.</dd>
I just thought of this question. Does the spec say whether the returned array will ever contain more than one cookie? I've seen arrays that behave that way in other APIs. If the spec doesn't say either way, please ping the spec authors.

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +<p>In service workers a subscription, associated with the service worker's registration, is required in order to listen for changes.</p>
```suggestion
```

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +<p>In service workers a subscription, associated with the service worker's registration, is required in order to listen for changes.</p>
See the net suggestion.

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +<p>In the below example we use {{domxref("CookieStoreManager.getSubscriptions()")}} to get a list of existing subscriptions. We unsubscribe from existing subscriptions using {{domxref("CookieStoreMan
```suggestion
<p>In the below example we use {{domxref("CookieStoreManager.getSubscriptions()")}} to get a list of existing subscriptions. (In service workers, a subscription is required in order to listen for events.) We unsubscribe from existing subscriptions using {{domxref("CookieStoreManager.unsubscribe()")}}, then subscribe to the cookie with a name of 'COOKIE_NAME' using {{domxref("CookieStoreManager.subscribe()")}}. If that cookie is changed, the event listener logs the event to the console. This will be an <code>ExtendableCookieChangeEvent</code> object, with the {{domxref("ExtendableCookieChangeEvent.changed","changed")}} or {{domxref("ExtendableCookieChangeEvent.deleted","deleted")}} property containing the modified cookie.</p>
```

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
```suggestion
  console.log(event.changed[0]);
```

2021-02-24 16:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/deleted/index.html
> +  console.log(event.deleted);
```suggestion
  console.log(event.deleted[0]);
```

2021-02-24 16:45 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +
The only difference between this and `CookieChangeEvent` seems to be the objects that get the callback. This begs the question, why does this one have the word 'extendable' in its name? Another question for the spec authors.

2021-02-25 07:01 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +</dl>
I'd tend to use the See Also section for additional general information, this is very specific to just one property and value. 

As a developer, if I were reading that and didn't really grok SameSite cookies from the info I'd see the link. I might not go to look at the bottom of the page to see if there was a link there. I kind of see "See also" as being, "hey you read all the way down to the bottom of this page, you must be really interested in this, here is some more stuff!"

2021-02-25 07:03 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +
It extends ExtendableEvent https://w3c.github.io/ServiceWorker/#extendableevent

Whereas CookieChangeEvent extends Event.

2021-02-25 08:39 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/index.html
> +  <dd>Returns an object containing the deleted cookie.</dd>
That seems to be the intention behind making it an array (and I am not sure why I didn't make that clear in the docs as my test example is testing length ..) the explainer mentions batching events.

2021-02-25 08:40 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
or would it be better here to keep it as returning the array, and just make sure the info is clear (as that is actually what is returned).

2021-02-25 15:21 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
I can't answer that without knowing why `changed` is an array.

2021-02-25 15:44 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
as answered above, the intention behind making it an array appears to be that there could be multiples, the explainer mentions batching events.

2021-02-25 15:44 UTC, rachelandrew commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
Son I think updating that to mention it will be an array of one or more changed cookies.

2021-03-01 16:54 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +  console.log(event.changed);
Sorry for the delay. I've been giving this some extra thought.

I now think neither option is correct. My first thought was that users of reference material don't always read straight through. Some will read the text for what they want then go back to work. Others will just look at the code sample. That alone suggests that it needs to communicate that it's an array. Logging the whole array would only communicate what's going on if someone actually ran the code, which may or may not happen.

The real problem is that neither option really communicates the batched nature of this. We may need something a little more involved than `console.log()`. I don't have any ideas just now.

2021-03-22 14:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/changed/index.html
> +<p class="summary">The <strong><code>changed</code></strong> read-only property of the {{domxref("ExtendableCookieChangeEvent")}} interface returns the cookie that has been changed by the given <code
Please make it clear that this is an array.

2021-03-22 14:12 UTC, jpmedley commented on files/en-us/web/api/extendablecookiechangeevent/deleted/index.html
> +<p class="summary">The <strong><code>deleted</code></strong> read-only property of the {{domxref("ExtendableCookieChangeEvent")}} interface returns the cookie that has been deleted by the given <code
Same here.

2021-03-24 13:54 UTC, jpmedley approved these changes

2021-03-24 13:54 UTC, merged