fix: grammatical issues in testing_strategies
mdn/content pull request #26349
Opened 2023-04-21 19:12 UTC by yashikabhargava

### Description

Fixed minor grammatical issues in testing_strategies.

2023-04-22 05:38 UTC, teoli2003 requested changes

2023-04-22 05:38 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +A quick online search tells you that most people in North America and Western Europe use Windows or Mac desktops/laptops, where the main browsers are Chrome, Firefox, Safari, and Edge. You'd probably
There many other use of A grade, … in this section. This should be unified.

2023-04-22 05:38 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  2. B grade: IE for Windows, Opera Mini
Remove IE.

2023-04-22 18:00 UTC, yashikabhargava commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +A quick online search tells you that most people in North America and Western Europe use Windows or Mac desktops/laptops, where the main browsers are Chrome, Firefox, Safari, and Edge. You'd probably
Yes, I missed some of those. Fixing it.

2023-04-22 18:02 UTC, yashikabhargava commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  2. B grade: IE for Windows, Opera Mini
I'm sorry, I did not get it. Do I need to remove IE from line 65?

2023-04-24 06:49 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  2. B grade: IE for Windows, Opera Mini
Yes, please. IE is dead; we should not recommend testing for it anymore.

2023-04-24 14:32 UTC, yashikabhargava commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
>  2. B grade: IE for Windows, Opera Mini
Okay, got it.

2023-04-25 05:59 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
```suggestion
```

2023-04-25 06:00 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md
> +2. B-grade: IE 8 and 9 for Windows, Opera Mini.
```suggestion
1. A-grade: Chrome and Firefox for Windows/Mac, Safari for Mac, and Edge (last two versions of each), iOS Safari for iPhone/iPad, Android stock browser (last two versions) on phone/tablet, Chrome, and Firefox for Android (last two versions) on phone tablet. Accessibility passing common tests.
2. B-grade: Opera Mini.
```

2023-04-25 06:01 UTC, teoli2003 approved these changes
:+1

2023-04-25 06:02 UTC, merged