CSS functions that are not value functions.
mdn/content pull request #26348
Opened 2023-04-21 19:08 UTC by estelle

addresses the concerns from https://github.com/mdn/content/issues/20611

2023-04-21 19:40 UTC, dipikabh commented
Taking a look at this shortly

2023-04-21 20:24 UTC, dipikabh requested changes
Added a suggestion

2023-04-21 20:24 UTC, dipikabh commented on files/en-us/web/css/css_functions/index.md
> +> **Note:** These CSS value functions are used as property values. The four [functional pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes) are not value functions, so are n
- Can we group the pseudo-classes as suggested below? 
- Note the extra trailing space at the end

```suggestion
> **Note:** The CSS value functions are used as property values and should not be confused with pseudo-classes. The [functional pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes), [linguistic pseudo-classes](/docs/Web/CSS/Pseudo-classes#linguistic_pseudo-classes), and several [tree-structural pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#tree-structural_pseudo-classes) require parameter values, but they're not value functions. The [conditional at-rules](/en-US/docs/Web/CSS/At-rule#conditional_group_rules) are also not value functions; the parentheses are used for groupings.
```

2023-04-22 05:41 UTC, teoli2003 commented on files/en-us/web/css/css_functions/index.md
> +> **Note:** The CSS value functions are used as property values and should not be confused with pseudo-classes. The [functional pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-cl
```suggestion
> **Note:** The CSS value functions are used as property values and should not be confused with pseudo-classes. The [functional pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes), [linguistic pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#linguistic_pseudo-classes), and several [tree-structural pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes#tree-structural_pseudo-classes) require parameter values, but they're not value functions. The [conditional at-rules](/en-US/docs/Web/CSS/At-rule#conditional_group_rules) are also not value functions; the parentheses are used for groupings.
```

2023-04-23 12:18 UTC, dipikabh approved these changes
Looks good, thanks 👍

2023-04-23 12:18 UTC, merged