Repurpose the "Animatable CSS properties" page
mdn/content pull request #26364
Opened 2023-04-22 13:10 UTC by yarusome

### Description

This PR:

  1. Reuses the existing "Animatable CSS properties" page to adds contents to explain the common animation types;
  2. Has *not* edited the following affected pages that link to this page:
     - `web/css/animation`,
     - `web/css/css_transitions/using_css_transitions`,
     - `web/css/transition-property`;
  3. Does *not* remove the to-be-deprecated `{{CSSAnimatedProperties}}` macro.

### Motivation

See https://github.com/orgs/mdn/discussions/367.

### Additional details

Most contents are reproduced from the relevant section in the Web Animations spec:
https://w3c.github.io/csswg-drafts/web-animations-1/#animating-properties

### Related issues and pull requests

Fixes #17768.

2023-04-22 16:26 UTC, yarusome commented on files/en-us/web/css/css_animated_properties/index.md
> +> **Note:** The interpolation method for each CSS data type is described in its "Interpolation" section (e.g. {{CSSXref("&lt;length&gt;", "", "#interpolation")}}).
I'm hesitant to add "accumulation" here because no page seems to list the accumulation method yet, even if it's explicitly defined for some data types.

2023-04-22 16:26 UTC, yarusome commented on files/en-us/web/css/css_animated_properties/index.md
> +For unregistered custom properties, the animation type is discrete.
This section is a simplistic description based on [Web Animations](https://w3c.github.io/csswg-drafts/web-animations-1/#custom-properties), and the [Animation Behavior](https://drafts.css-houdini.org/css-properties-values-api/#animation-behavior-of-custom-properties) and the [Computed Value-Time Behavior](https://drafts.css-houdini.org/css-properties-values-api/#calculation-of-computed-values) sections of CSS Properties and Values API.

2023-04-22 16:32 UTC, yarusome commented
cc @teoli2003

2023-04-24 07:42 UTC, teoli2003 requested changes
A few changes needed (We'll need to check the output of the PR companion to check the output of the definition list)

2023-04-24 07:42 UTC, teoli2003 commented on files/en-us/web/css/css_animated_properties/index.md
> +Same as by computed value except that if the two lists have differing numbers of items, they are first repeated to the least common multiple number of items. Each item is then combined by computed va
We should likely use a definition list here. We'll need to check that it looks well in the preview, a sometimes they can be tricky to set up (and I'm using the GitHub UI right now).
```suggestion
- Not animatable
- : The property is not animatable. It is not processed when listed in an animation keyframe and is unaffected by transitions.
  > **Note:** An animation effect targeting only properties that are not animatable will still exhibit the usual behavior for an animation effect (e.g., firing the {{DOMXref("Element/animationstart_event", "animationstart")}} event).

- Discrete
- : The property's values are not additive, and interpolation swaps from the start value to the end value at `50%`. Specifically, denoting by `p` the progress value:

  - If `p < 0.5`, then `V_result = V_start`;
  - If `p ≥ 0.5`, then `V_result = V_end`.

- By computed value
- : Corresponding individual components of the computed values are combined using the indicated procedure for that value type.

  If the number of components or the types of corresponding components do not match, or if any component value uses discrete animation and the two corresponding values do not match, then the property values combine as discrete.

- Repeatable list
- : Same as by computed value except that if the two lists have differing numbers of items, they are first repeated to the least common multiple numbers of items. Each item is then combined by computed value. If a pair of values cannot be combined or any component value uses discrete animation, then the property values combine as discrete.
```

2023-04-24 14:03 UTC, yarusome commented
I finally fixed the definition list after finding the format in the [guide](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#definition_lists).

2023-04-24 14:35 UTC, teoli2003 approved these changes
👍

2023-04-24 14:36 UTC, merged