add clip to overflow-inline
mdn/content pull request #26396
Opened 2023-04-24 23:38 UTC by estelle

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-04-24 23:47 UTC, dipikabh commented
I'll take a look at this shortly.

2023-04-25 00:41 UTC, yarusome commented on files/en-us/web/css/overflow-inline/index.md
> +   - : Overflow content is clipped at the element's overflow clip edge that is defined using the {{CSSXref("overflow-clip-margin")}} property.
```suggestion
  - : Overflow content is clipped at the element's overflow clip edge that is defined using the {{CSSXref("overflow-clip-margin")}} property.
```

2023-04-25 00:41 UTC, yarusome commented on files/en-us/web/css/overflow-inline/index.md
> +  <li>
```suggestion

  <li>
```

2023-04-25 15:53 UTC, dipikabh requested changes
Thanks, @estelle. Added some changes to the "See also" section and pointed some nits for other updates.

2023-04-25 15:53 UTC, dipikabh commented on files/en-us/web/css/overflow-inline/index.md
> +    <code>overflow-inline: hidden</code> — hides the text outside the box
```suggestion
    <code>overflow-inline: hidden</code> (hides the text outside the box)
```

2023-04-25 15:53 UTC, dipikabh commented on files/en-us/web/css/overflow-inline/index.md
> +    <code>overflow-inline: scroll</code> — always adds a scrollbar
```suggestion
    <code>overflow-inline: scroll</code> (always adds a scrollbar)
```

2023-04-25 15:53 UTC, dipikabh commented on files/en-us/web/css/overflow-inline/index.md
> +    <code>overflow-inline: clip</code> — hides the text outside the box beyond the <code>overflow-clip-margin</code>
```suggestion
    <code>overflow-inline: clip</code> (hides the text outside the box beyond the overflow clip edge)
```

2023-04-25 19:57 UTC, estelle commented on files/en-us/web/css/overflow-inline/index.md
>  - [Writing Modes](/en-US/docs/Web/CSS/CSS_Writing_Modes)
> do we need the link to [logical properties landing page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) here?

I don't think so.

2023-04-26 11:33 UTC, dipikabh approved these changes
Thanks 👍

2023-04-26 11:33 UTC, merged