Module landing page: scrollbar styles
mdn/content pull request #26400
Opened 2023-04-25 02:03 UTC by estelle

part of https://github.com/openwebdocs/project/issues/147

2023-04-25 02:06 UTC, dipikabh commented
I'll take a look at this tomorrow 👍

2023-04-25 04:46 UTC, teoli2003 requested changes, later dismissed

2023-04-25 04:46 UTC, teoli2003 commented on files/en-us/web/css/css_scrollbars/index.md
> +- [CSS scroll snap module](/en-US/docs/web/CSS/CSS_Scroll_Snap)
Capitalization matters (see flaws)
```suggestion
- [CSS Scroll Snap module](/en-US/docs/Web/CSS/CSS_Scroll_Snap)
```

2023-04-25 04:46 UTC, teoli2003 commented on files/en-us/web/css/css_scrollbars/index.md
> +- [CSS overflow module](/en-US/docs/web/CSS/CSS_overflow)
```suggestion
- [CSS Overflow module](/en-US/docs/Web/CSS/CSS_Overflow)
```

2023-04-25 04:46 UTC, teoli2003 commented on files/en-us/web/css/css_scrollbars/index.md
> +- {{Experimental_Inline}} The CSS scroll timeline {{cssxref('scroll-timeline-name')}} and {{cssxref('scroll-timeline-axis')}} properties, along with the {{cssxref('scroll-timeline')}} shorthand, to c
```suggestion
- {{{cssxref('scroll-timeline-name')}}, {{cssxref('scroll-timeline-axis')}}, and {{cssxref('scroll-timeline')}} 
```

2023-04-25 18:01 UTC, dipikabh requested changes
Added my comments

2023-04-25 19:28 UTC, estelle commented on files/en-us/web/css/css_scrollbars/index.md
> +The **CSS scrollbars styling** module defines properties that provide visual styling of scrollbars, including controls for their color and width.
```suggestion
The **CSS scrollbars styling** module defines properties that provide visual styling of scrollbars, including controls for the color and width of scrollbar tracks, the background of the scrollbar, and the color of scrollbar thumbs, the draggable handle of the scrollbar.
```

2023-04-26 11:51 UTC, dipikabh requested changes
Thanks for the updates. Added two follow-up changes

2023-04-26 11:51 UTC, dipikabh commented on files/en-us/web/css/css_scrollbars/index.md
> +The **CSS scrollbars styling** module defines properties that provide visual styling of scrollbars, including controls for the color and width of scrollbar tracks, the background of the scrollbar, an
```suggestion
The **CSS scrollbars styling** module defines properties that you can use for visual styling of scrollbars. You can  customize the width of the scrollbar as required. You can also customize the color of the scrollbar _track_, which is the background of the scrollbar, and the color of the scrollbar _thumb_, which is the draggable handle of the scrollbar.
```
I guess the width definition is for the scrollbar and not just for the track?

2023-04-26 11:51 UTC, dipikabh commented on files/en-us/web/css/css_scrollbars/index.md
>    - css.properties.scrollbar-color
Can we put both back in? Adding BCD entry for one can raise questions about the support for the other property.

2023-04-26 18:34 UTC, estelle commented on files/en-us/web/css/css_scrollbars/index.md
>    - css.properties.scrollbar-color
i would prefer to have neither. If we put them both in, it is huge. I'll remove them again ;)
<img width="532" alt="Screen Shot 2023-04-26 at 11 33 12 AM" src="https://user-images.githubusercontent.com/69888/234670415-ba6a22a6-7366-411a-89a7-064da079b223.png">

2023-04-26 20:45 UTC, dipikabh requested changes, later dismissed

2023-04-26 20:45 UTC, dipikabh commented on files/en-us/web/css/css_scrollbars/index.md
> +The **CSS scrollbars styling** module defines properties that you can use for visual styling of scrollbars. You can  customize the width of the scrollbar as required. You can also customize the color
```suggestion
The **CSS scrollbars styling** module defines properties that you can use for visual styling of scrollbars. You can customize the width of the scrollbar as required. You can also customize the color of the scrollbar _track_, which is the background of the scrollbar, and the color of the scrollbar _thumb_, which is the draggable handle of the scrollbar.
```

2023-04-26 20:50 UTC, dipikabh approved these changes

2023-04-26 20:50 UTC, merged