Add new and update existing popover api docs
mdn/content pull request #26413
Opened 2023-04-25 14:01 UTC by chrisdavidmills

### Description

The [Popover API](https://html.spec.whatwg.org/multipage/popover.html) is going to be available in Chrome 114. I've had this confirmed by the relevant engineers, and it is also reflected by the platform status entry: https://chromestatus.com/feature/5463833265045504.

See my [research document](https://docs.google.com/document/d/1ryC_4hvkLom0E7aaNnAB82_Ki5Rb_cKgrOJGSBU9fuw/edit#) for further details of what has been added in this PR.

@keithamus already did a bunch of fabulous work towards getting this documented. I've updated a few of your pages mate, to tweak wording and add some examples, but what was there was already pretty good. Nice job.

### Motivation

### Additional details

### Related issues and pull requests

2023-04-27 20:53 UTC, wbamberg commented
Looking at this today.

2023-04-28 00:50 UTC, wbamberg requested changes
This is for the Popover API overview page.

2023-04-28 00:50 UTC, wbamberg commented on files/en-us/web/api/popover_api/index.md
> +See our [Nested popover menu example](https://mdn.github.io/dom-examples/popover-api/nested-popovers/) for an example. You'll notice that quite a few event handlers have been used to display and hide
```suggestion
See our [Nested popover menu example](https://mdn.github.io/dom-examples/popover-api/nested-popovers/) for an example. You'll notice that quite a few event handlers have been used to display and hide the subpopover appropriately during mouse and keyboard access, and also to hide both menus when an option is selected from either. Depending on how you handle loading of new content , either in an SPA or multi-page website, some of all of these may not be necessary, but they have been included in this demo for illustrative purposes.
```

2023-04-28 12:21 UTC, keithamus commented on files/en-us/web/api/htmlelement/popover/index.md
> +  - Only one popover can be shown at a time — showing a second popover when one is already shown will hide the first one.
It might be worth adding additional clarification here; if there are nested popover elements, or in certain situations when an invoker is within another popover, then there _can_ be multiple popovers open. An example use case could be nested menus.

2023-04-28 19:06 UTC, mfreed7 reviewed
This looks awesome! Thanks for putting it all together. I've left a number of comments, but overall this looks good. I'd hit "Approve" if I had the permissions.

2023-04-28 19:06 UTC, mfreed7 commented on files/en-us/web/api/toggleevent/index.md
>  {{APIRef("UI Events")}}
So the `toggle` event is "coalesced" meaning if multiple of them are fired before the event loop has a chance to cycle, only a single `toggle` event will be fired. (Spec is [here](https://html.spec.whatwg.org/multipage/popover.html#queue-a-popover-toggle-event-task).) And in that case, the interpretation of the `oldState` and `newState` parameters is... interesting.

I say this for your information. It might be too much information to include on MDN. Then again, a developer encountering this behavior might wish it was here.

The example is:

```javascript
p.addEventListener('toggle',()=>{});
p.showPopover();
p.hidePopover();
// `toggle` only fires once
```

(I didn't verify the above example, but it should be true.)

2023-04-28 19:06 UTC, mfreed7 commented on files/en-us/web/css/_doublecolon_backdrop/index.md
> +When multiple elements have been placed into the top layer, the backdrop is drawn immediately beneath the frontmost such element, and on top of the older elements.
Technically, **each** element in the top layer has its own `::backdrop` pseudo element, and all are rendered.

2023-04-28 19:06 UTC, mfreed7 commented on files/en-us/web/api/popover_api/index.md
> +There is an exception to the rule about not displaying multiple auto popovers at once — when they are nested inside one another. In such cases, multiple popovers are allowed to both be open at the sa
I think this could use a bit more detail about **how** popovers can be nested. There are three ways:

1. Direct DOM descendants:

```html
<div popover>Parent
  <div popover> Child </div>
</div>
```

2. Via invoking elements:

```html
<div popover> Parent
  <button popovertarget=foo>Click me</button>
</div>

<div popover id=foo> Child </div>
```

3. Via the `anchor` attribute:

```html
<div popover id=foo> Parent </div>

<div popover anchor=foo> Child </div>
```

2023-05-01 14:31 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +  return HTMLElement.prototype.hasOwnProperty("popover");
Yup, that was the thought here.

2023-05-01 14:33 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +This example illustrates the use of {{domxref("Element.matches()")}} to programmatically check whether a popover is currently showing ({{cssxref(":popover-open")}} selects only showing popovers). Thi
Because I wanted to illustrate the usage of all three methods ;-)

2023-05-01 14:54 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +You can see how the previous code snippet renders in our [Basic declarative popover example](https://mdn.github.io/dom-examples/popover-api/basic-declarative/).
Really good call Will, thanks! I've added source links for all of them, in my next commit.

2023-05-01 15:11 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +See our [Toggle help UI example](https://mdn.github.io/dom-examples/popover-api/toggle-help-ui/) to see the popover JavaScript properties, feature detection, and `togglePopover()` method in action.
I totally agree with adding the help text, but I don't want to omit the button entirely because it is central to demonstrate adding the declarative attributes with JS. I've added the help text in a separate PR, which I'll @-mention you in

2023-05-01 15:14 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +Anoher common pattern in JavaScript is dismissing popovers automatically after a certain amount of time. You might for example want to create a system of "toast" notifications, where you have multipl
I totally agree. New heading added, and previous heading updated.

2023-05-01 15:18 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/popover/index.md
> +  - Only one popover can be shown at a time — showing a second popover when one is already shown will hide the first one.
Good call, thanks Keith. I've added this in my next commit.

2023-05-01 15:20 UTC, chrisdavidmills commented on files/en-us/web/api/htmlbuttonelement/popovertargetaction/index.md
> +  - : The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; If the popover is showing, it will be hidden.
Thanks; I've updated this on both the button and input DOM object pages.

2023-05-01 15:42 UTC, chrisdavidmills commented on files/en-us/web/api/htmlbuttonelement/popovertargetaction/index.md
> +The **`popoverTargetAction`** property of the {{domxref("HTMLButtonElement")}} interface gets and sets the action to be performed (`"hide"`, `"show"`, or `"toggle"`) on a popover element being contro
This is a really good point; I have made sure that the default action is made clear in the main landing page, property pages, and equivalent HTML attribute sections

2023-05-01 15:47 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/hidepopover/index.md
> +When `hidePopover()` is called on an showing element with the [`popover`](/en-US/docs/Web/HTML/Global_attributes/popover) attribute, a {{domxref("HTMLElement/beforetoggle_event", "beforetoggle")}} ev
Cool, fixed

2023-05-01 15:51 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/hidepopover/index.md
> +    }
OK, I've updated the examples on the `showPopover()` and `hidePopover()` pages to just show / hide, not toggle.

2023-05-01 15:54 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/popover/index.md
> +  - Multiple popovers can be shown at a time.
updated.

2023-05-01 16:20 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/togglepopover/index.md
>  {{ APIRef("HTML DOM") }}{{SeeCompatTable}}
Ah crap, I missed that one! Thanks for the info; I've added it to the page now.

2023-05-01 16:26 UTC, mfreed7 commented on files/en-us/web/api/popover_api/index.md
> +Finally, animation needs a special mention, as a lot of people are going to want to animate popovers between hosing and hiding. As it stands, [a few updates to CSS behavior](https://open-ui.org/compo
I don't know why, but I laughed out loud for a while with this one. So yeah, thanks. 😄

2023-05-01 16:39 UTC, chrisdavidmills commented on files/en-us/web/api/toggleevent/index.md
>  {{APIRef("UI Events")}}
I think this is worth including, but I've included it on the pages for the HTMLElement beforetoggle/toggle events, as I think it is more useful there. Added.

2023-05-01 16:44 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_backdrop/index.md
> +When multiple elements have been placed into the top layer, the backdrop is drawn immediately beneath the frontmost such element, and on top of the older elements.
I've modified the wording on this page a bit to try to make this more precise, in the next commit. Let me know if you think it's better now.

2023-05-01 16:49 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +There is an exception to the rule about not displaying multiple auto popovers at once — when they are nested inside one another. In such cases, multiple popovers are allowed to both be open at the sa
Yup, good call. I've added this.

2023-05-01 17:06 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +## Concepts and usage
Yup, agreed. In the next commit I've broken it out into a separate page.

2023-05-01 17:45 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +See our [Toggle help UI example](https://mdn.github.io/dom-examples/popover-api/toggle-help-ui/) to see the popover JavaScript properties, feature detection, and `togglePopover()` method in action.
See https://github.com/mdn/dom-examples/pull/216

2023-05-01 21:44 UTC, wbamberg requested changes
OK, I've now read the rest of it.

2023-05-01 21:44 UTC, wbamberg commented on files/en-us/web/api/htmlinputelement/popovertargetaction/index.md
> +{{Specifications}}
I don't understand why the spec table isn't showing up for this.

2023-05-01 21:44 UTC, wbamberg commented on files/en-us/web/api/popover_api/index.md
> +## Concepts and usage
Looks so good like this!

2023-05-01 21:44 UTC, wbamberg commented on files/en-us/web/api/htmlelement/toggle_event/index.md
> +- If the popover/`<details>` element is currently showing/open, then `event.oldState` will be `open` and `event.newState` will be `closed`.
Also, I can't comment below but it appears as if, when this event is fired on a `<detais>` element, the object is just an `Event`, and it is only a `ToggleEvent` when the element is a popover. See https://codepen.io/willbamberg/pen/oNaGBQZ?editors=1011. I think we'll need to explain that here (and in `beforetoggle` I assume).

2023-05-01 21:44 UTC, wbamberg commented on files/en-us/web/api/toggleevent/index.md
> +It is the event object for the {{domxref("HTMLElement.beforetoggle_event", "beforetoggle")}} and {{domxref("HTMLElement.toggle_event", "toggle")}} events, which fire on popovers when their state chan
But (I think) only for those events when the target is a popover. So maybe something like:

```suggestion
It is the event object for the {{domxref("HTMLElement.beforetoggle_event", "beforetoggle")}} and {{domxref("HTMLElement.toggle_event", "toggle")}} events when the event target is a popover.
```

2023-05-02 06:15 UTC, chrisdavidmills commented on files/en-us/glossary/top_layer/index.md
> +- {{cssxref("@layer")}}
Hrm, I thought from what I'd read that the top layer was effectively an auto-generated cascade layer, but I'm not so sure now. I've deleted the last two links to be on the safe side.

2023-05-02 06:16 UTC, chrisdavidmills commented on files/en-us/web/api/element/requestfullscreen/index.md
> +> **Note:** It is possible to put a {{domxref("Popover_API", "popover", "", "nocode")}} element (for example `<div popover>...</div>`) into fullscreen mode. However, if you try to call `requestFullsc
OK; removed

2023-05-02 06:20 UTC, chrisdavidmills commented on files/en-us/web/api/htmldialogelement/showmodal/index.md
> +> **Note:** It is possible to create a {{htmlelement("dialog")}} element that is also a {{domxref("Popover_API", "popover", "", "nocode")}}, i.e. `<dialog popover>...</dialog>`. However, if you try t
OK, removed. In both this case and `requestFullscreen()`, I've linked the word "popover" to the Popover API landing page, so that readers can find out more info if they are confused as to what a popover is.

2023-05-02 06:45 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/toggle_event/index.md
> +- If the popover/`<details>` element is currently showing/open, then `event.oldState` will be `open` and `event.newState` will be `closed`.
OK, I agree with the wording in the bullets, so I've updated those. 

For the difference between toggle on `<details>` and toggle on all other elements, I've actually made the decision to remove all mention of `<details>` on this page, and instead just add notes to this, and the `HTMLDetailsElement.toggle_event` pages, explaining that there are two versions, and what the difference is between them. I thought this made more sense, as they are two separate implementations.

And none of this applies to `beforetoggle`; that was specified purely for the Popover API and has nothing to do with `<details>`. You can see that from the definitions at https://html.spec.whatwg.org/multipage/indices.html#event-beforetoggle

2023-05-02 08:04 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/index.md
> +This example illustrates the use of {{domxref("Element.matches()")}} to programmatically check whether a popover is currently showing ({{cssxref(":popover-open")}} selects only showing popovers). Thi
OK, fair point. I've rewritten the example text to do just that and make it sound like two alternatives, rather than one which is rendered obsolete by the other.

2023-05-02 08:35 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/togglepopover/index.md
> +  - : A boolean, which causes `togglePopover()` to behave like {{domxref("HTMLElement.showPopover", "showPopover()")}} or {{domxref("HTMLElement.hidePopover", "hidePopover()")}}:
Good call; I've added wording to cover this.

2023-05-02 09:05 UTC, chrisdavidmills commented on files/en-us/web/api/toggleevent/index.md
> +It is the event object for the {{domxref("HTMLElement.beforetoggle_event", "beforetoggle")}} and {{domxref("HTMLElement.toggle_event", "toggle")}} events, which fire on popovers when their state chan
Yes, but the `<details>` version seems to be a different, unrelated implementation. I've updated the text slightly differently, adding a note to explain that `ToggleEvent` is not related to that version of `toggle`, and how they differ.

2023-05-02 15:04 UTC, mfreed7 commented on files/en-us/web/api/htmlelement/toggle_event/index.md
> +- If the popover/`<details>` element is currently showing/open, then `event.oldState` will be `open` and `event.newState` will be `closed`.
The intention for the events fired on `<details>` is that they’re identical to the new stuff for popover. That hasn’t been implemented in browsers yet though. So I’m not sure how MDN likes to handle that situation. But the eventual goal is to align them, in spec and implementation. I guess it’s best to wait for that to become reality though, before documenting it.

I do like the suggestion on wording. The reason we went with `oldState` and `newState` was to clear up ambiguity about timing. Sometimes the event comes before the change and sometimes after, so old/new tells you which way the transition went, whenever it happened.

2023-05-02 15:06 UTC, mfreed7 commented on files/en-us/web/api/htmlelement/togglepopover/index.md
> +  - : A boolean, which causes `togglePopover()` to behave like {{domxref("HTMLElement.showPopover", "showPopover()")}} or {{domxref("HTMLElement.hidePopover", "hidePopover()")}}:
Side note: there’s a spec PR up now to change the exceptions for `showPopover` and `hidePopover` so they don’t throw if the popover is already in the desired state.

2023-05-02 15:07 UTC, mfreed7 commented on files/en-us/web/api/toggleevent/index.md
> +It is the event object for the {{domxref("HTMLElement.beforetoggle_event", "beforetoggle")}} and {{domxref("HTMLElement.toggle_event", "toggle")}} events, which fire on popovers when their state chan
See my comment above.

2023-05-02 15:31 UTC, chrisdavidmills commented on files/en-us/web/api/htmlelement/toggle_event/index.md
> +- If the popover/`<details>` element is currently showing/open, then `event.oldState` will be `open` and `event.newState` will be `closed`.
Yeah, I think it will make sense to wait until that's reality. But we can always make more updates at a later date. When the time comes let Rachel know, so it gets added to my work spreadsheet ;-)

2023-05-02 15:39 UTC, mfreed7 commented on files/en-us/web/api/htmlelement/togglepopover/index.md
> +  - : A boolean, which causes `togglePopover()` to behave like {{domxref("HTMLElement.showPopover", "showPopover()")}} or {{domxref("HTMLElement.hidePopover", "hidePopover()")}}:
The `force` parameter was basically added to make it parallel to [this API](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle). And the change to `showPopover/hidePopover` was because people thought exceptions were too much, partly because querying for state (`.matches(':popover-open')`) was cumbersome. But you're right - these two APIs now overlap a lot.

2023-05-02 15:42 UTC, mfreed7 commented on files/en-us/web/css/_doublecolon_backdrop/index.md
> +When multiple elements have been placed into the top layer, the backdrop is drawn immediately beneath the frontmost such element, and on top of the older elements.
Totally clear now - thanks!

2023-05-02 15:46 UTC, chrisdavidmills commented on files/en-us/glossary/top_layer/index.md
> +- {{cssxref("@layer")}}
OK, thanks. I'll do some more reading in that area to make sure I don't get confused again.

2023-05-02 16:54 UTC, wbamberg approved these changes
OK, thanks for all the updates, Chris! Looks great. It seems like there will be some follow-up around the events and the behavior of `showPopover`/`hidePopover` but I agree this should wait for implementations.

I'm approving but not merging yet in case any of the other reviewers have more comments, but I'm happy for this to be merged.

2023-05-03 09:45 UTC, chrisdavidmills commented
> OK, thanks for all the updates, Chris! Looks great. It seems like there will be some follow-up around the events and the behavior of `showPopover`/`hidePopover` but I agree this should wait for implementations.
> 
> I'm approving but not merging yet in case any of the other reviewers have more comments, but I'm happy for this to be merged.

Thanks @wbamberg ! Can you please merge it as soon as you see this ? I've got thumbs up from the Chrome folks to release.

2023-05-03 14:59 UTC, merged

2023-05-03 15:01 UTC, chrisdavidmills commented
@wbamberg hoorah, cheers man!