Update ValidityState docs
mdn/content pull request #26431
Opened 2023-04-26 10:18 UTC by teoli2003

### Description

Adds missing pages for:

- `ValidityState.customError`
- `ValidityState.valid`

### Motivation

Part of openwebdocs/project#153

### Additional details

I also did minor fixes to the other `ValidityState` pages to bring them closer to the current standard. (I didn't work on extra examples there, though)

### Related issues and pull requests

BCD PR (to fix `mdn_url` entries): mdn/browser-compat-data#19500
Fixes #26522

2023-04-26 12:25 UTC, Elchi3 requested changes, later dismissed
Thanks Jean-Yves! Some work to do here.

2023-04-26 12:25 UTC, Elchi3 commented on files/en-us/web/api/validitystate/valid/index.md
> +The read-only **`valid`** property of the [`ValidityState`](/en-US/docs/Web/API/ValidityState) interface indicates if the value of an {{HTMLElement("input")}}, after having been edited by the user, c
```suggestion
The read-only **`valid`** property of the [`ValidityState`](/en-US/docs/Web/API/ValidityState) interface indicates if the value of an {{HTMLElement("input")}} element meets all its validation constraints, and is therefore considered to be valid.
```

2023-04-26 12:25 UTC, Elchi3 commented on files/en-us/web/api/validitystate/valid/index.md
> +If true, the element matches the {{cssxref(":valid")}} CSS pseudo-class; the {{cssxref(":invalid")}} CSS pseudo-class otherwise.
```suggestion
If `true`, the element matches the {{cssxref(":valid")}} CSS pseudo-class; otherwise the {{cssxref(":invalid")}} CSS pseudo-class applies.
```

2023-11-30 15:57 UTC, bsmth commented
Hey @teoli2003 - do you plan to come back to this one?

2023-11-30 16:31 UTC, teoli2003 commented
Yes, but never get to the top of my notification list. I really need to block a day for "finish what is open".

2023-12-20 12:51 UTC, teoli2003 commented on files/en-us/web/api/validitystate/customerror/index.md
> +<input type="email" id="original" /> <input type="email" id="confirmation" />
Done in [5ff1189](https://github.com/mdn/content/pull/26431/commits/5ff11893345e9237dfcac5378b94dac5020f5242)

2023-12-20 13:41 UTC, teoli2003 commented on files/en-us/web/api/validitystate/customerror/index.md
> +requestAnimationFrame(displayLog);
The `displayLog` function logs the message. It needs to be called periodically (here every frame, but we could do it less often) to update the log.

I didn't want to put it into the event handler because the event handler sets the message so, it doesn't need to read `customError` to know one has been set.

I've not found a simple example that would be less artificial.

2023-12-20 13:42 UTC, teoli2003 commented on files/en-us/web/api/validitystate/customerror/index.md
> +In the following example, we set a custom error when both emails don't match. A log is written when this is the case, and a different message is displayed when there is no custom errors. When there i
The example is a bit artificial, as the function detects the error only to log a message. I've not found an idea of a simple example that would be better.

2024-02-22 10:08 UTC, bsmth commented
@teoli2003 what's the plan with this one? Do you need a reviewer :) shall I take a look?

2024-05-06 10:26 UTC, teoli2003 commented
Hi! Yes I'd need a reviewer.

2024-05-14 08:36 UTC, bsmth commented
Assigned myself so I don't forget. I'll take a look through soon 👀

2024-06-18 17:26 UTC, estelle commented
@bsmth @teoli2003 bumping to the top of your notifications list ;)

2024-06-21 08:57 UTC, bsmth commented
> @bsmth @teoli2003 bumping to the top of your notifications list ;)

Thanks, I've started and then put this off a few times but I'll try to look again today 😄

2024-06-21 09:22 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +<pre id="log"></pre>
What about the [example from the spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#the-constraint-validation-api:custom-validity-error-message):

https://codepen.io/bsmth/pen/abrYEJd

2024-06-21 09:23 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +requestAnimationFrame(displayLog);
```suggestion
function check(input) {
  if (input.value == "good") {
    input.setCustomValidity('"' + input.value + '" is not a feeling.');
  } else {
    // Reset the custom error message
    input.setCustomValidity("");
  }
}

function validateInput() {
  document.getElementById("feelingInput").reportValidity();
}
```

2024-06-21 09:23 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +<pre id="log"></pre>
```suggestion
<input type="text" id="feelingInput" placeholder="How are you feeling?" oninput="check(this)">
<button onclick="validateInput()">Check input</button>
```

2024-06-21 09:40 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +In the following example, we set a custom error when both emails don't match. A log is written when this is the case, and a different message is displayed when there is no custom errors. When there i
If you think the suggestion below is good, we could say something like:

>In the example below, `setCustomValidity` sets a custom error message for a field when the input is invalid. If you click the "Check input" button, we call `reportValidity`, which displays a validation message if the input value doesn't match the constraints. If you enter the text "good" and check the form validity, the field is marked invalid until the custom error message is cleared (set to an empty string).

2024-06-21 09:42 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +In the following example, we set a custom error when both emails don't match. A log is written when this is the case, and a different message is displayed when there is no custom errors. When there i
Linking to https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation#constraint_validation_process maybe

2024-06-21 09:43 UTC, bsmth commented
@teoli2003 some comments for you to have a look at 👀 back over to you!

2024-06-27 10:16 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +In the following example, we set a custom error when both emails don't match. A log is written when this is the case, and a different message is displayed when there is no custom errors. When there i
```suggestion
In the example below, `setCustomValidity` sets a custom error message for a field when the input is invalid. If you click the "Check input" button, we call `reportValidity`, which displays a validation message if the input value doesn't match the constraints. If you enter the text "good" and check the form validity, the field is marked invalid until the custom error message is cleared (set to an empty string). 
```

2024-07-01 20:20 UTC, estelle commented on files/en-us/web/api/validitystate/customerror/index.md
> +<pre id="log"></pre>
I didn't think we use onEvent attributes on MDN. Do we?

2024-07-11 20:50 UTC, estelle reviewed
made this comment a while ago, but never submitted it.

2024-07-15 04:53 UTC, Josh-Cena commented
@bsmth are you championing this PR, or is @estelle doing it?

2024-07-15 08:33 UTC, bsmth commented
> @bsmth are you championing this PR, or is @estelle doing it?

I'm fine with self-assigning it to get it over the finish line. Is that okay @estelle? I'm going to apply the suggestions shortly.

2024-07-15 09:08 UTC, bsmth commented on files/en-us/web/api/validitystate/customerror/index.md
> +<pre id="log"></pre>
Good call, fixed in 94ee94117fd1df4f761aa36ba7029919275dce43

2024-07-15 15:42 UTC, bsmth approved these changes
Thanks a lot! Going to merge this one now to get these long-standing improvements in!

2024-07-15 15:42 UTC, merged