Change the description for code blocks in Writing style guideline
mdn/content pull request #26500
Opened 2023-04-30 05:56 UTC by yarusome

### Description

This PR changes the description for using code blocks in headings.

### Motivation

See #26481.

### Additional details

### Related issues and pull requests

Fixes #26481.

2023-04-30 06:38 UTC, Josh-Cena commented
I don't feel comfortable saying "should". There's a lot of existing content without code and I don't want to do anything about them—I think they are fine as-is. As another point, as I'm writing a static checker for Markdown, I find titles being plain text very handy for checking the IA. As such I think it should remain "permissible" but neither "recommended" nor "mandated".

2023-04-30 08:06 UTC, yarusome commented
@Josh-Cena The issue here is the inconsistency across various pages (see, e.g., the two pages in the linked issue). It's OK to live with either all codes wrapped or unwrapped, but the mixture is quite confusing.

If sticking to no wrapping, another problem raised in the linked issue is the incorrect uppercasing for functions' and variables' names.

2023-04-30 08:10 UTC, teoli2003 approved these changes
This approval is a vote to check if we have a consensus among maintainers. I like this idea as it uniformizes the way of doing it. Note that I would also be ok with _However, use backticks_ or _However, you must use_.

2023-04-30 14:10 UTC, Josh-Cena requested changes
Why would inconsistency in typography be so undesirable? We already have some places where we give writers room for their own discretion (e.g. adding commas after "e.g."/"i.e."; whether to put commas/periods inside or outside quotes...) I don't feel like forcing a choice here is particularly useful. Plus we cannot use code formatting in H1 titles anyway, so it's still not consistent in the end.

My approval for allowing code formatting in headings at all was out of the intention to remove ambiguity (i.e. I want to have the freedom to do so where necessary). However, where there's no necessity, I enjoy the visual uniformity of having plain text headings.

2023-04-30 23:56 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- **Don't use inline styles, classes, or macros within headings.** However, you should use backticks to indicate code terms (e.g. "Using `FooBar` interface").
I think this was deliberately "can", because there are many many cases where we do not.

@wbamberg Sidebars automatically code style the short names of properties, but WebAPI titles in page are not marked up  - e.g. [HTMLElement.accessKey](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/accessKey). 
Personally I prefer markup of code entities in titles, particularly in guide.
Has this been discussed anywhere?

2023-05-01 00:05 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/writing_style_guide/index.md
> +- **Don't use inline styles, classes, or macros within headings.** However, you should use backticks to indicate code terms (e.g. "Using `FooBar` interface").
Ah and now I see https://github.com/mdn/content/issues/26481#issuecomment-1528341065

2023-05-05 05:27 UTC, yarusome commented
@Josh-Cena I also agree with the only-for-disambiguation and visual-uniformity-of-plain-text arguments, but once the need for disambiguation arises, don't code spans break the very uniformity in the latter argument?

2023-05-05 08:31 UTC, closed without merging