Split pictureInPictureElement to avoid mixin page
mdn/content pull request #2653
Opened 2021-02-24 11:06 UTC by Elchi3

Same story as #2395

Split things up to avoid the DocumentOrShadowRoot mixin page.

2021-02-24 14:05 UTC, chrisdavidmills requested changes
Some comments for you; thanks for doing this @Elchi3 !

2021-02-24 14:05 UTC, chrisdavidmills commented on files/en-us/web/api/picture-in-picture_api/index.html
>  <h3 id="Properties_on_the_DocumentOrShadowRoot_interface">Properties on the DocumentOrShadowRoot interface</h3>
The heading here still mentions `DocumentOrShadowRoot`, and I think there might be another mention somewhere else in this doc too.

2021-02-24 14:05 UTC, chrisdavidmills commented on files/en-us/web/api/shadowroot/index.html
> + <dd>Returns the {{DOMxRef('HTMLVideoElement')}} within the shadow tree that is currently being presented in picture-in-picture mode.</dd>
As mentioned before, shouldn't the return value be `Element`?

2021-02-24 14:05 UTC, chrisdavidmills commented on files/en-us/web/api/shadowroot/pictureinpictureelement/index.html
> +      <td>{{SpecName('HTML WHATWG','#dom-documentorshadowroot-pictureinpictureelement', 'pictureInPictureElement')}}</td>
The spec link doesn't 404, but it doesn't seem to get to the correct fragment/heading.

2021-02-24 14:56 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
As you can see in the commit message I ran `yarn content move Web/API/DocumentOrShadowRoot/pictureInPictureElement Web/API/Document/pictureInPictureElement` and have not touched anything else. I'm not fiddling with redirects manually! :)

Strangely the production site has a redirect place, pictureInPictureEnabled -> pictureInPictureElement.
See https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled

Probably this is from wiki redirects and is wrong. I don't want to manually fiddle with this redirect in this PR, though. What do you advise me to do?

2021-02-24 15:04 UTC, chrisdavidmills commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Maybe @fiji-flo could comment here. How is best to fix this incorrect redirect?

2021-03-01 10:45 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Can we solve this in a separate issue or do you think it blocks this PR?

2021-03-01 11:06 UTC, fiji-flo commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Sorry, I missed this. This looks correct in terms of what should be generated.
```
/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureElement
```
I guess this redirect shouldn't have been in place.

2021-03-01 11:07 UTC, fiji-flo commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
```suggestion
/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureEnabled
```

This should validate and work.

2021-03-01 11:09 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Is it okay to manually remove it then? (here or in a separate PR?)

2021-03-01 11:11 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Okay, thank you :)

2021-03-01 11:12 UTC, fiji-flo commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
@Elchi3 I'd suggest we apply this. I'll look if we just ported this from Kuma or if there's something wrong in yari. But it's a nice catch. We should add tooling to "fix" wrong redirects.

2021-03-01 11:13 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
I couldn't agree more, thanks for your detailed look @fiji-flo 👍

2021-03-01 12:59 UTC, fiji-flo commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
@Elchi3 I meant applying my suggested change in this PR (I think the _apply this_ was a bit generic).

2021-03-01 14:39 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/DocumentOrShadowRoot/pictureInPictureEnabled	/en-US/docs/Web/API/Document/pictureInPictureElement
Oh, I thought I applied it but I can't apparently. It says "The diff has recently been updated. Refresh and try again" which doesn't disappear if I refresh. Let me apply it manually then.

2021-03-02 12:35 UTC, Elchi3 commented
Redirect updated!

2021-03-02 12:50 UTC, fiji-flo approved these changes
👌

2021-03-03 10:42 UTC, chrisdavidmills approved these changes
Looking good, let's get this merged. Nice work @Elchi3 !

2021-03-03 10:42 UTC, merged