fix(RemotePlayback): use APIRef + add GroupData for overview page
mdn/content pull request #26541
Opened 2023-05-02 18:18 UTC by caugner

### Description

Uses the APIRef sidebar for all "RemotePlayback" pages, and adds a GroupData item for the DefaultAPISidebar on the overview page.

### Motivation

Makes sure the following pages have a sidebar:

  /en-US/docs/Web/API/Remote_Playback_API
  /en-US/docs/Web/API/RemotePlayback/cancelWatchAvailability
  /en-US/docs/Web/API/RemotePlayback
  /en-US/docs/Web/API/RemotePlayback/prompt
  /en-US/docs/Web/API/RemotePlayback/state
  /en-US/docs/Web/API/RemotePlayback/watchAvailability

### Additional details

### Related issues and pull requests

Part of https://github.com/mdn/content/issues/22441.

2023-05-02 18:40 UTC, wbamberg requested changes
Thanks!

Apart from the inline comments, I guess we should add `{{DefaultAPISidebar("Remote Playback API")}}` to https://developer.mozilla.org/en-US/docs/Web/API/Remote_Playback_API ?

2023-05-02 18:40 UTC, wbamberg commented on files/jsondata/GroupData.json
> +        "RemotePlayback: disconnect"
These should not list members of interfaces that appear in "interfaces", it's for members that are part of other interfaces, which in this case seems to be the extensions to `HTMLMediaElement`: https://w3c.github.io/remote-playback/#extensions-to-htmlmediaelement.

2023-05-02 18:40 UTC, wbamberg commented on files/en-us/web/api/remoteplayback/cancelwatchavailability/index.md
> +{{APIRef}}
```suggestion
{{APIRef("Remote Playback API")}}
```

(same goes for all the others in this PR)

2023-06-01 08:56 UTC, bsmth commented
Removing myself from review while this is in a draft state, feel free to add me again if you want me to take a look when it's ready :)

2023-07-20 06:10 UTC, caugner commented
Closing, as I don't have capacity to work on this in the near future. But I appreciate Will's review. 🙌

2023-07-20 06:10 UTC, closed without merging