Note about incognito cooking store, support and identification
mdn/content pull request #26606
Opened 2023-05-05 17:26 UTC by rebloor

### Description

Addresses [feedback](https://github.com/mdn/browser-compat-data/pull/19446#pullrequestreview-1413326321) provided as part of a BCD update to the cookies.CookieStore property details [#19446](https://github.com/mdn/browser-compat-data/pull/19446)

2023-05-08 12:25 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +Windows in different browsing modes may use different cookie stores. For examole, a private browsing/incognito mode window, for instance, uses a separate cookie store from a non-incognito/private win
```suggestion
Windows in different browsing modes may use different cookie stores. For example, a private browsing/incognito mode window, for instance, uses a separate cookie store from a non-incognito/private window.
```

2023-05-08 12:25 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +> - Chromium-based browsers return the cookie stores but don't support the `incognito` property, so don't explicitly identify the cookie stores as belonging to an incognito browsing window.
Not sure what this line is supposed to mean.
The only way to identify private cookies in Chrome is to check the cookieStoreId ("1" string is incognito).

2023-05-08 12:25 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +Windows in different browsing modes may use different cookie stores. For examole, a private browsing/incognito mode window, for instance, uses a separate cookie store from a non-incognito/private win
This paragraph gives the impression that there is a 1:1 relation between cookie stores and windows. In Firefox the "container tab" feature can result in different cookie stores within the same (non-private browsing) window. Could you emphasize that so that devs don't assume that there is only one cookie store in a window?

This relates to https://github.com/mdn/content/issues/8267

2023-05-09 03:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +> - Chromium-based browsers return the cookie stores but don't support the `incognito` property, so don't explicitly identify the cookie stores as belonging to an incognito browsing window.
@Rob--W Unfortunately, my mental note to ask about this didn't turn into an actual note. I don't seem to be able to find anything documenting this elsewhere, so can you please confirm my change understands you correctly.

2023-05-15 11:27 UTC, Rob--W requested changes

2023-05-15 11:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_the_cookies_api/index.md
> +  > Firefox identifies these stores using the `incognito` property in {{WebExtAPIRef("cookies.CookieStore")}}. Chromium-based browsers also return private (incognito) browsing mode stores but don't s
```suggestion
- Private browsing mode stores, which stores cookies created during a private browsing session. These stores and any cookies they contain are removed when the related private browsing window closes.
  > **Note:**
  > Only visible if {{WebExtAPIRef("extension.isAllowedIncognitoAccess()")}} returns true. Safari doesn't support access to private cookies yet.
```

I removed most of this, since getAllCookieStores already has the info and describes how to tell them apart. I added new info that wasn't there before.

2023-05-15 11:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +> How cookie store details for private browsing/incognito mode windows are returned varies between browsers:
Instead of this note, add to `incognito` below:
> The `incognito` property is not supported in Chrome. As an alternative, incognito stores in Chrome can be identified by their `id` being "1".


... and mark that property as optional so that Chrome and Safari are covered.

2023-05-15 11:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +Windows in different browsing modes may use different cookie stores. For example, a private browsing/incognito mode window uses a separate cookie store from a non-incognito/private window. Also, a wi
Could you link to the other article you touched in this PR? It seems to offer plenty of details that aren't here.

2023-05-15 16:57 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/cookiestore/index.md
> +Windows in different browsing modes may use different cookie stores. For example, a private browsing/incognito mode window uses a separate cookie store from a non-incognito/private window. Also, a wi
Done

2023-05-15 18:15 UTC, Rob--W approved these changes
Thanks.

2023-05-16 09:25 UTC, merged