25150 add new srcset usage example
mdn/content pull request #26618
Opened 2023-05-06 15:31 UTC by adarshajit

### Description

This PR adds an new example of using `srcset` attribute on the `<img>` tag. 

### Motivation

Earlier on the page, the reader is told:

> If providing higher-density versions of an image for high-DPI (Retina) display, use [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset) on the <img> element instead. This lets browsers opt for lower-density versions in data-saving modes, and you don't have to write explicit media conditions.

But in "The srcset attribute" section, the example used to demonstrate how to include alternate images based on pixel density only uses srcset in the <source> elements and src in the <img> element.

### Additional details

NIL

### Related issues and pull requests

Fixes #25150

2023-05-06 20:50 UTC, schalkneethling commented
Hey @adarshajit 👋 Thank you for your pull request. Before I start a review, please refer to at the Markdown lint error that the CI is raising. Thanks.

```
Finding: files/en-us/web/html/element/picture/index.md !node_modules !.github !tests
Linting: 1 file(s)
Warning: files/en-us/web/html/element/picture/index.md:[14](https://github.com/mdn/content/actions/runs/4902351202/jobs/8756077877?pr=26618#step:6:15)3 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
Summary: 1 error(s)
```

2023-05-11 18:31 UTC, schalkneethling requested changes
Hey, @adarshajit. I have added a few comments and suggestions. Let me know what you think. Thank you for your contribution and patience.

2023-05-11 18:31 UTC, schalkneethling commented on files/en-us/web/html/element/picture/index.md
> +This is an example on how to use `srcset` with a `<picture>` tag:
How about we reword it to the following?

```suggestion
The following example demonstrates how to use the `srcset` attribute with the `<source>` element to specify a high-density and standard-resolution image:
```

On a side note, on line 112 there is a small typo that would be great to fix in this pull request.

Currently:
```markdown
The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer list of possible images _based on size_.
```

Correct:
```markdown
The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer a list of possible images _based on size_.
```

2023-05-16 22:24 UTC, schalkneethling commented
Hey, @adarshajit, no rush, but if any of my suggestions are unclear, please let me know. Thanks!

2023-05-23 21:54 UTC, schalkneethling requested changes
Hey @adarshajit, thank you for your patience and for sticking with this one as we figure out the best way to document this. I have made some suggestions for you to consider and also asked Brian to take a look.

2023-05-23 21:54 UTC, schalkneethling commented on files/en-us/web/html/element/picture/index.md
> +Please note that sizes will have its effect only if width dimension descriptors are provided with srcset instead of pixel ratio values (200w instead of 2x for example).
We can remove all of this as there is no mention of the `sizes` attribute on this page.

2023-05-23 21:54 UTC, schalkneethling commented on files/en-us/web/html/element/picture/index.md
> +The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer a list of possible images _based on size_.
This is not something you added or changed, but I am not sure "based on size" is entirely accurate. You can specify different images using a width descriptor but also a pixel density descriptor. Pixel density is not really related to size. You can have a mobile phone with a high-density display just as you can have a laptop with a high-density display. @bsmth, what do you think?

2023-05-23 21:54 UTC, schalkneethling commented on files/en-us/web/html/element/picture/index.md
>  </picture>
Looking at some of the other content on this page, I am rethinking the code examples. As the main use case for the `picture` element is art direction and offering different image formats, it might be a good idea to either use the code from the interactive example at the top of the page (this one demonstrates art direction):

```html
<picture>
    <source srcset="/media/cc0-images/surfer-240-200.jpg"
            media="(orientation: portrait)">
    <img src="/media/cc0-images/painted-hand-298-332.jpg" alt="">
</picture>
```

Or the following, which demonstrates how you can offer different image formats and fallback to PNG:

```html
<picture>
  <source srcset="trevor-gerzen-r_XS7sml57o-unsplash.avif" type="image/avif" />
  <source srcset="trevor-gerzen-r_XS7sml57o-unsplash.webp" type="image/webp" />
  <img
    src="trevor-gerzen-r_XS7sml57o-unsplash.png"
    width="1223"
    height="815"
    alt="A beautiful sunset in the background with two surfers paddling into the surf in the foreground"
  />
</picture>
```

The nice thing about the second example is that when combined with the interactive example, the page demonstrated the two attributes unique to the `source` element, namely `media` and `type`. The rest of the attributes (`srcset`, `sizes`, `width`, and `height`) can also be used on the `img` element, as shown in the example you added further down. What do you think?

2023-05-29 21:02 UTC, jfrech commented on files/en-us/web/html/element/picture/index.md
> +The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer a list of possible images _based on size_.
I would have read it to mean "based on the size in true pixels which is the best fit". So changing "based on size" to e.&hairsp;g. "based on required resolution" would have my blessing.

2023-06-29 12:11 UTC, bsmth commented
hi @adarshajit - thanks for the submission. I'll take a look at your changes shortly 👀

2023-06-29 12:17 UTC, bsmth commented on files/en-us/web/html/element/picture/index.md
> +  <img src="logo.png" alt="MDN Web Docs logo" height="320" width="320" />
Re-adding Schalk's suggestion here:
```suggestion
  <source srcset="logo.png, 
                  logo@1.5x.png 1.5x" />
  <img src="logo.png" height="320" width="320" alt="logo" />
```

with this rationale:

>The reason for the above suggestion is to show that the <img> element acts as a fallback for browsers that do not support the <source> element. In this example, the <source> element specifies two images. One that will be used for high-definition displays and another for all others. Seeing that both the source of the <img> element and the first entry in the srcset attribute use the same file format, the addition of the size (-320 and -768) is not needed and might cause confusion for some readers.

I also added the height and width attributes so that we keep with best practices. Let me know what you think.

2023-06-29 12:56 UTC, bsmth commented on files/en-us/web/html/element/picture/index.md
> +The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer a list of possible images _based on size_.
Schalk is right here, it's not just image size, it's also pixel density.

```suggestion
The [srcset](/en-US/docs/Web/HTML/Element/source#srcset) attribute is used to offer a list of possible images based on size or the display's pixel density.
```

See:

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions
* https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element

2023-06-29 14:32 UTC, bsmth commented on files/en-us/web/html/element/picture/index.md
> +Please note that sizes will have its effect only if width dimension descriptors are provided with srcset instead of pixel ratio values (200w instead of 2x for example).
I think it's okay to mention sizes here if we're mentioning `srcset`. I'm going to mark this as resolved for now

2023-06-29 14:51 UTC, bsmth commented on files/en-us/web/html/element/picture/index.md
>  - a _pixel density descriptor_, followed by an `x` (such as `2x`) to serve a high-res image for high-DPI screens.
I think as a follow-up to this PR, there's a couple of things to note:

* You can't mix with and pixel density descriptors
* missing pixel density descriptor implies `1x`.
* duplicate descriptor values are not allowed (`2x` & `2x`, `100w` & `100w`)

But we also have a doc about this here:

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions

2023-07-20 07:44 UTC, bsmth commented
> Please take a look when you have some time.

Thanks a lot, I'll take another look shortly 👀

2023-10-24 10:30 UTC, bsmth approved these changes
Thanks a lot for the submission @adarshajit - I think we can merge this one 👍🏻

2023-10-24 10:30 UTC, merged