browser_style deprecated in MV3
mdn/content pull request #26642
Opened 2023-05-08 08:06 UTC by rebloor

### Description

Provides documentation for [Bug 1827910](https://bugzilla.mozilla.org/show_bug.cgi?id=1827910) "Deprecate browser_style in MV3"

2023-05-15 11:03 UTC, Rob--W requested changes
Are you able to create a sample in mdn/webextensions-examples that shows how to migrate from MV2 + browser_style to MV3? Or should I provide these and let you link it from here?

2023-05-15 17:12 UTC, rebloor commented
@Rob--W

> Are you able to create a sample in mdn/webextensions-examples that shows how to migrate from MV2 + browser_style to MV3? Or should I provide these and let you link it from here?

I'd be happy to do this. However, I suspect I might need quite a bit of your time to devise and fine-tune the example. Also, do we have a plan for how to include MV2 and MV3 examples?

2023-05-18 11:42 UTC, Rob--W requested changes
I commented in action specifically because it is even more special; please update the `page_action`, `options_ui`, `sidebar_action` to remove the repetition of what `browser_style` does, and refer to the `/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles` page instead. And emphasize that browser_style support will be dropped.

The default changing from true to false is merely a transition tool, it is very much the intention to turn off support.

2023-05-18 11:42 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +> Support for `browser_style` in Manifest V3 has been deprecated and, from Firefox 115, `options_ui.browser_style` and `sidebar_action.browser_style` default to `false`. `page_action.browser_style`,
```suggestion
> Support for `browser_style` in Manifest V3 has been deprecated and will be removed in the near future. Starting from Firefox 115, the default value of `options_ui.browser_style` and `sidebar_action.browser_style` changes from `true` to `false`. By Firefox 118, `browser_style:true` will no longer be supported in Manifest Version 3 extensions.
```

Can probably be improved, but the main message is that it's deprecated and should not be used. Details are at https://bugzilla.mozilla.org/show_bug.cgi?id=1827910#c1

2023-05-18 11:42 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +> If your Manifest V3 extension depends on the `browser_style: true` styles, bundle this stylesheet in the extension: [extension.css](https://hg.mozilla.org/mozilla-central/raw-file/a445f1762c895000b
```suggestion
> If your Manifest V3 extension depends on the `browser_style: true` styles, follow the [Manifest V3 migration guide for `browser_style`](#manifest_v3_migration).
```

2023-05-18 11:42 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
>  > **Note:** See [Firefox bug 1465256](https://bugzil.la/1465256) for removal of this unnecessary requirement.
```suggestion
```

Bug is WONTFIX.

2023-05-18 11:42 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +    If you cannot identify the dependencies, includ the content of [extension.css](https://hg.mozilla.org/mozilla-central/raw-file/a445f1762c895000bcdabd9d95697522359d41ed/browser/components/extensio
```suggestion
    If you cannot identify the dependencies, include the content of [extension.css](https://hg.mozilla.org/mozilla-central/raw-file/a445f1762c895000bcdabd9d95697522359d41ed/browser/components/extensions/extension.css) with the extension and delete all parts that aren't relevant, usually the `body` and `body *` blocks as most extensions don't use the `browser-style` class.
```

2023-05-18 11:42 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/action/index.md
> +          the <code>browser_style</code> property.
The `action` API is MV3-only, so we can be more firm here. Delete most of the content here in favor of:

```suggestion
          Do not set `browser_style` to true. See [Manifest v3 migration for `browser_style`](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles#manifest_v3_migration).
```

Oddly, `browser_style` is documented as supported in all browsers in the BCD. It should be marked as unsupported there except desktop Firefox (and when we drop support, we'll update the BCD as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1830711)

2023-05-19 04:21 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/action/index.md
> +          the <code>browser_style</code> property.
I have been "firm" in all instances, given that even though we continue to support MV2 we wouldn't necessarily want someone developing an MV2 extension from scratch to make their life harder (when there is a need to migrate to MV3) by including this feature.

2023-05-19 04:29 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/action/index.md
> +          the <code>browser_style</code> property.
Also updated BCD

2023-05-20 15:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/action/index.md
> +        <br />{{optional_inline}}
All other keys are also optional. For consistency, add this label to the other `action` keys.

2023-05-20 15:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/browser_action/index.md
> +        <br />{{optional_inline}}
All other keys are optional, add the optional label to `browser_action` keys for consistency.

2023-05-20 15:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/sidebar_action/index.md
> +        <br />{{optional_inline}}
For consistency, add optional to every other key except for `default_panel`.

2023-05-20 15:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/user_interface/browser_styles/index.md
> +> Support for `browser_style` in Manifest V3 is deprecated. Starting from Firefox 115, the default value of `options_ui.browser_style` and `sidebar_action.browser_style` changes from `true` to `false
```suggestion
> Support for `browser_style` in Manifest V3 is deprecated. Starting from Firefox 115, the default value of `options_ui.browser_style` and `sidebar_action.browser_style` changes from `true` to `false`. In Firefox 118, `"browser_style": true` will no longer be supported in Manifest V3 extensions.
```

2023-05-20 15:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/options_ui/index.md
>              href="https://acorn.firefox.com/latest/acorn.html"
This recommendation does not make sense in the context of `browser_style`. That page provides the resources (assets) to mimic the latest browser styles, but that is completely independent of the browser_style styles.

Let's keep the references to the "browser styles" article, and expand the article with a section that references acorn for people interested in that.

2023-05-20 18:51 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/options_ui/index.md
>              href="https://acorn.firefox.com/latest/acorn.html"
This comment here also applies to sidebar_action and page_action, which has similar text.

2023-05-20 18:52 UTC, Rob--W approved these changes
r+, with the requested change to page_action and sidebar_action applied.

2023-05-22 09:52 UTC, Rob--W approved these changes
While you've already mentioned the changed default, there is no mention of it in the release notes. Could you mention that the default of `options_ui.browser_style` and `sidebar_action.options_ui` changed from true to false for Manifest Version 3 extensions (and reference the browser_styles article with the deprecation guidelines)? If you'd like that can also be a follow-up PR. That release note should be associated with https://bugzilla.mozilla.org/show_bug.cgi?id=1830710

In any case, this is good to merge.

2023-05-22 17:10 UTC, Rob--W approved these changes

2023-05-22 17:10 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/114/index.md
> +- Support for [`browser_style`](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles) in the manifest keys [`action`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action
```suggestion
- Support for [`browser_style`](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles) in the manifest keys [`action`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action), [`options_ui`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui), [`page_action`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action), and [`sidebar_action`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) is deprecated for Manifest V3 extensions ([Firefox bug 1827910](https://bugzil.la/1827910)). See [Manifest v3 migration](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles#manifest_v3_migration) for information about transitioning from `browser_style` in Manifest V3 extensions.
```

I dropped `browser_action`, because a MV3 extension cannot use browser_action (only `action`).

2023-05-22 17:14 UTC, merged