Add RTCAudioSourceStats
mdn/content pull request #26667
Opened 2023-05-09 07:50 UTC by hamishwillee

This adds docs for the `RTCAudioSourceStats`. Note that there is "surrounding" documentation still to do. This should however be able to go in now.

This is part of delivery for #26146

2023-05-11 03:39 UTC, wbamberg requested changes
Thanks! I think this looks good., Are we planning to ditch RTCStats?

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/kind/index.md
> +Along with the {{domxref("RTCAudioSourceStats.type", "type")}}, this uniquely identifies the type of statistics as a {{domxref("RTCAudioSourceStats")}} object when iterating the {{domxref("RTCStatsRe
```suggestion
Along with the {{domxref("RTCAudioSourceStats.type", "type")}}, this identifies the object as an {{domxref("RTCAudioSourceStats")}} object when iterating the {{domxref("RTCStatsReport")}} returned by {{domxref("RTCRtpSender.getStats()")}} or {{domxref("RTCPeerConnection.getStats()")}}.
```

(not sure what "uniquely" means here)

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/trackidentifier/index.md
> +A string containing the value of the associated [`MediaStreamTrack.id`](/en-US/docs/Web/API/MediaStreamTrack/id)
```suggestion
A string containing the value of the associated [`MediaStreamTrack.id`](/en-US/docs/Web/API/MediaStreamTrack/id).
```

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/type/index.md
> +The type of `media-source` uniquely identifies the type of statistics as either {{domxref("RTCAudioSourceStats")}} or {{domxref("RTCVideoSourceStats")}} when iterating the {{domxref("RTCStatsReport")
Again I wasn't sure about uniquely here. But it's not a big deal.

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/type/index.md
> +The {{domxref("RTCAudioSourceStats")}} dictionary's property **`type`** is a string with value `media-source`.
I wish we were consistent (not just here, but everywhere) with whether to use quotes for string values, like `"media-source"`.

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/id/index.md
> +Using the `id`, you can correlate this statics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref("RT
```suggestion
Using the `id`, you can correlate this statistics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref("RTCDataChannel")}}.
```

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/id/index.md
> +Using the `id`, you can correlate this statics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref("RT
```suggestion
Using the `id`, you can correlate this statistics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref("RTCDataChannel")}}.
```

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +The level is averaged over some small implementation-dependent interval
```suggestion
The level is averaged over some small implementation-dependent interval.
```

2023-05-11 03:39 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +A number between 0 and 1 (linear), where 1.0 represents 0 dBov ([decibels relative to full scale (DBFS)](https://en.wikipedia.org/wiki/DBFS)), 0 represents silence, and 0.5 represents approximately 6
I don't understand this but that's OK.

2023-05-12 00:05 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +A number between 0 and 1 (linear), where 1.0 represents 0 dBov ([decibels relative to full scale (DBFS)](https://en.wikipedia.org/wiki/DBFS)), 0 represents silence, and 0.5 represents approximately 6
Yes, these are odd audio engineer units. I don't fully understand them either, so what I have done is linked to some references that can help people move forward.

2023-05-12 00:07 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +  - : A string that contains the id value of the `MediaStreamTrack` associated with audio source.
Yes. Thank you.

2023-05-12 00:08 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/kind/index.md
> +Along with the {{domxref("RTCAudioSourceStats.type", "type")}}, this uniquely identifies the type of statistics as a {{domxref("RTCAudioSourceStats")}} object when iterating the {{domxref("RTCStatsRe
That's because "uniquely" wasn't necessary. Thanks for the catch.

2023-05-12 00:11 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/type/index.md
> +The {{domxref("RTCAudioSourceStats")}} dictionary's property **`type`** is a string with value `media-source`.
That would be good. Make a rule, add it to the guide, and I'll follow it.

Despite what I did here, I think using quotes in this instance makes sense. The place I don't think it makes sense to add quotes is in definition lists, where the string represents a possible value.

2023-05-12 00:11 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/type/index.md
> +The type of `media-source` uniquely identifies the type of statistics as either {{domxref("RTCAudioSourceStats")}} or {{domxref("RTCVideoSourceStats")}} when iterating the {{domxref("RTCStatsReport")
No, you're right.

```suggestion
The type of `media-source` identifies the type of statistics as either {{domxref("RTCAudioSourceStats")}} or {{domxref("RTCVideoSourceStats")}} when iterating the {{domxref("RTCStatsReport")}} returned by {{domxref("RTCRtpSender.getStats()")}} or {{domxref("RTCPeerConnection.getStats()")}}.
```

2023-05-12 00:16 UTC, hamishwillee commented on files/en-us/web/api/rtcstats/index.md
> +  - {{domxref("RTCVideoSourceStats")}} Wxxxx.
@wbamberg Yes, I do plan to ditch `RTCStats` but I thought I'd add all the new dictionaries first, and update this as I went along. Then at the end I'd remove this.

I will fix this text up. Good catch.

2023-05-12 00:27 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +const audioLevel = audioSourceStats.audioLevel;
Not sure. But or safety, I quite like this syntax, and it least makes the potential issue obvious.

```suggestion
const audioLevel = audioSourceStats?.audioLevel;
```

2023-05-12 00:49 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +browser-compat: api.RTCStatsReport.type_media-source.audioLevel
Note, BCD is not planning on supporting dictionaries, so this is the correct compat data.

2023-05-12 00:51 UTC, hamishwillee commented
@wbamberg Thanks for the review. Accepted your changes. Also just updated BCD for all these to use the key where the information is

The RTCStats will be removed at the end when I have populated all the stats classes - it is easier/safer to do it this way.

Read for re-review.

2023-05-12 03:08 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +browser-compat: api.RTCStatsReport.type_media-source.audioLevel
that's a very strange BCD item! But OK.

2023-05-12 03:08 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +const audioLevel = audioSourceStats.audioLevel;
Yes, I almost suggested this.

2023-05-12 03:08 UTC, wbamberg approved these changes
👍 thank you!

2023-05-12 03:08 UTC, merged

2023-05-12 03:09 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/audiolevel/index.md
> +browser-compat: api.RTCStatsReport.type_media-source.audioLevel
Yes. The whole disconnect is horrible. But it should be more or less OK for users.