Add Baseline (compatibility) glossary entry
mdn/content pull request #26676
Opened 2023-05-09 17:24 UTC by ddbeck

### Description

This adds a glossary entry for the Baseline term (and, soon, iconography) for forthcoming web platform feature compatibility status summaries.

cc: @Rumyra, @atopal, @LeoMcA since they've previewed much of this and have additional context

### Motivation

In the not-too-distant future, some MDN pages will have Baseline status information. These statuses are not (yet) widely recognized or self-explanatory; this glossary entry will provided a reader-facing description of the status summary, its origins, and how a reader might affect its contents.

### Additional details

### Related issues and pull requests

- https://github.com/mdn/yari/pull/8772
- https://github.com/web-platform-dx/feature-set#readme

2023-05-09 17:25 UTC, ddbeck commented on files/en-us/glossary/baseline/compatibility/index.md
> +🟡 If you see a yellow badge showing that a feature is not yet Baseline, then do more research and testing with your site's users before relying on that feature, or wait for it to become Baseline.
I'm happy to update this after the fact, but there's no (merged) assets to use yet.

2023-05-09 17:32 UTC, Rumyra requested changes

2023-05-09 17:32 UTC, Rumyra commented on files/en-us/glossary/baseline/compatibility/index.md
> +A Baseline feature—such as an API, a set of CSS properties, or a JavaScript syntax—is known to work consistently in the current and previous major versions of several well-known browsers (Chrome, Edg
```suggestion
A Baseline feature - such as an API, a set of CSS properties, or a JavaScript syntax - is known to work consistently in the current and previous major versions of several well-known browsers (Chrome, Edge, Firefox, and Safari).
```

2023-05-09 17:34 UTC, Rumyra commented on files/en-us/glossary/baseline/compatibility/index.md
> +A Baseline feature—such as an API, a set of CSS properties, or a JavaScript syntax—is known to work consistently in the current and previous major versions of several well-known browsers (Chrome, Edg
Not sure if this was intended, but assumed not 👍

2023-05-09 17:47 UTC, Rumyra approved these changes

2023-05-09 17:47 UTC, merged

2023-05-09 17:48 UTC, estelle commented on files/en-us/glossary/baseline/index.md
> -- [CSS Box Alignment](/en-US/docs/Web/CSS/CSS_Box_Alignment#types_of_alignment) on MDN
It is a value in box alignment and.  See Glossary/Fallback_Alignment 
See also CanvasRenderingContext2D.textBaseline. 
It's also in vertical align in tables and (should likely not be mentioned)

2023-05-10 10:49 UTC, ddbeck commented on files/en-us/glossary/baseline/index.md
> -- [CSS Box Alignment](/en-US/docs/Web/CSS/CSS_Box_Alignment#types_of_alignment) on MDN
@estelle these changes are an artifact of moving the contents of the entry and creating a disambiguation page. The Glossary/Baseline/Typography entry still contains the link to CSS Box Alignment