CSS: scroll snap module
mdn/content pull request #26735
Opened 2023-05-11 21:25 UTC by estelle

Part of https://github.com/openwebdocs/project/issues/147

* brief description
* demonstration example
* properties
* guides
* associated properties
* glossary terms

2023-05-13 02:00 UTC, dipikabh requested changes
Thanks @estelle for making these updates and adding "the example"!

I've added some edit suggestions.

2023-05-13 20:30 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
> +
```suggestion

```

2023-05-13 20:32 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
> +Scroll snap defines scroll snap positions, which enforce the scroll positions that a scroll container's {{Glossary("scrollport")}} may end at, or "snap to," after a scrolling operation has completed.
> * Not sure what "app-like experience" is referring to

It was there so i left it there.

2023-05-13 20:34 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
>  The example below demonstrates scroll snapping along the vertical axis, which is defined by `scroll-snap-type`. Additionally, `scroll-snap-align` is used on all the `<section>` element children dicta
stop is correct

2023-05-13 20:35 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
> +- {{cssxref("scroll-snap-type")}}: Using this property, you can define whether or not the scrollable viewport can be snapped to, whether snapping is required or optional, and the axis on which the sn
```suggestion

- {{cssxref("scroll-snap-type")}}: Using this property, you can define whether or not the scrollable viewport can be snapped to, whether snapping is required or optional, and the axis on which the snapping should occur.
```

2023-05-14 00:27 UTC, estelle commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
>  The key properties for the scroll snap feature are:
> * I prefer the previous bulleted list style to list the related properties here. The bulleted list also makes the presentation on this page slightly different from the usual definition list on a property reference page.

This is the guide, not the module landing page. Does this comment still hold true?

2023-05-15 18:04 UTC, dipikabh commented on files/en-us/web/css/css_scroll_snap/basic_concepts/index.md
>  The key properties for the scroll snap feature are:
Yes :)

2023-05-15 18:15 UTC, dipikabh approved these changes
Just one fix needed. Otherwise this looks good. Thank you 👍

2023-05-15 21:32 UTC, merged