New PWA best practices guide
mdn/content pull request #26800
Opened 2023-05-16 14:09 UTC by captainbrosset

### Description

This PR contains a new PWA guide focused on providing high-level best practices for people looking to build the best PWAs possible.

### Motivation

We are in the process of re-writing the PWA docs on MDN with @estelle and @wbamberg and have already written a number of guides and how-to tutorials.

We feel like there should also be a Best Practices article in there. That's what this PR does.

### Additional details

N/A

### Related issues and pull requests

https://github.com/mdn/mdn/issues/280

2023-05-16 18:56 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +## Adapt to all browsers, devices, form-factors, and input types
I thought this title was a bit unwieldy. Then I thought, does it make sense to separate "Adapt to all browsers" and "Adapt to all devices"? Because e.g. feature detection, as documented in https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Feature_detection, say, is really about browser support, while say responsive design and input methods is more about device support.

Also, there's a separate section on "progressive enhancement" below, which to me is hand-in-hand with feature detection (as it also is in https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement), so why not cover that in here as well?

So we could have:

```
## Adapt to all browsers

- cross-browser testing
- progressive enhancement/feature detection

## Adapt to all devices

- responsive design
- input methods
```

...but maybe there's too much overlap here and it would be better to have them in one section. Either way it would be nice to have progressive enhancement in here though.

2023-05-16 18:56 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +## Make it installable
I don't think we should include this here, or at least not in this way. I think of "best practices" as things that are not definitionally essential but which are needed for the thing to be actually good. We even say this at the start:

> This article provides a list of best practices to help you make sure your PWA is as good as it can be.

But being installable is part of being a PWA - if it's not installable it isn't a PWA.

I think this matters because we want to be very clear to people what the basic criteria are for being a PWA, and putting it here blurs this.

If we want to talk about installability here we might want to mention it separately, at the start, as a basic criterion.

I feel somewhat similar about the "custom offline" section.

2023-05-17 05:25 UTC, estelle reviewed
some feedback....

Main feedback is to indicate that these are PWA requirements not just best practices

2023-05-19 12:30 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +## Adapt to all browsers, devices, form-factors, and input types
Thanks, both, for the feedback. I've reworked this section and will push a commit soon. I went with Will's proposal to split into 2 separate things (browsers, devices).

2023-05-19 12:35 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +## Make it installable
That's a good point. In fact, I felt this confusion a little bit myself while writing this part. I'll remove this part.

Regarding the custom offline page, I can see where you're coming from. But right now, nothing prevents a web app to be considered as a PWA if it doesn't have a custom offline experience. In fact `addEventListener("fetch", e => {})` makes a valid service worker. And Chrome is experimenting with removing the requirement on service workers (and will provide the offline page automatically).
So I still think it's good for people to realize that making their own offline page is something that will make a big different for user retention/engagement.

2023-05-19 13:17 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Users of installed apps expect them to continue working even when their device is offline, or when connected to a slow or unreliable network.
Well, it's not really a requirement in fact. You can create a PWA, today, that's considered installable by browsers, but that does not work offline. 
It's very important best practice, but it's a strict technical requirement.

I'm definitely applying your suggested rephrasing for the first sentence though.

2023-05-19 13:19 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Making your PWA installable makes it behave more like a platform-specific app, with its own icon, standalone window, and own entry in the places where users expect to find apps on their device. It's
I'm removing this whole section, as per Will, because this is indeed a strict technical requirement. Not a best practice.

2023-05-19 13:19 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Making your app installable also allows you to distribute it through app stores.
Dito.

2023-05-19 17:45 UTC, wbamberg approved these changes
👍 looks great.

2023-05-22 18:57 UTC, estelle requested changes
Looks good. Just a few minor word change suggestions / grammar stuff

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Your PWA is based on Web technologies which means that, on top of being installable on devices, it can run in web browsers too. To ensure compatibility, it's essential to [test your app](/en-US/docs/
```suggestion
Your PWA is based on Web technologies. This means that, on top of being installable on devices, PWAs can run in web browsers too. To ensure compatibility, it's essential to [test your app](/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing) across various browsers and operating systems.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +With Progressive Enhancement, you focus on making the core functionalities of your app work universally first, by using the simplest technology for them, and then enhance the experience on supporting
```suggestion
With Progressive Enhancement, you focus on making the core functionalities of your app work universally first by using the simplest technology, then enhancing the experience for supporting devices.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +For example, handling form submissions with the HTML {{htmlelement("form")}} element means that the form will work on all browsers, including those that don't support JavaScript. You can then progres
```suggestion
For example, handling form submissions with the HTML {{htmlelement("form")}} element means that the form will work on all browsers, including those that don't support JavaScript. You can then progressively enhance the form by adding client-side validation and JavaScript-based submission handling for a better experience on compatible devices.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Similar to how testing your app across various browsers is important, testing across devices also ensures that your app is accessible to the broadest audience.
```suggestion
Similar to how testing your app across various browsers is important, testing across devices ensures your app is accessible to the broadest audience.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +[Responsive design](/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design) is crucial for PWAs to ensure that content is accessible on any screen size. Users should be able to access all features and co
```suggestion
[Responsive design](/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design) is crucial for PWAs to ensure the content is accessible on any screen size. Users should be able to access all features and content regardless of their device's screen size. By rearranging content at different viewport sizes, you can prioritize important data and actions.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Ensure users can interact with your application no matter how they access your content. Support keyboard and mouse, as well as touch or stylus input methods. Make sure all features of your applicatio
```suggestion
Ensure users can interact with your application no matter how they access your content. Support keyboard and mouse, as well as touch or stylus input methods. Make sure all your application features can be accessed through any input method.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Finally, use [semantic HTML elements](/en-US/docs/Glossary/Semantics#semantics_in_html) rather than recreating your own buttons or form elements since as semantic HTML elements support all input meth
```suggestion
Finally, use [semantic HTML elements](/en-US/docs/Glossary/Semantics#semantics_in_html) rather than recreating your own buttons or form elements as semantic HTML elements support all user input methods right out of the box.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +To go further and provide an app-like experience, your PWA should function when the user is offline. This means that the user can continue using some, preferably all, of your app's functionality even
```suggestion
To go further and provide an app-like experience, your PWA should function when the user is offline. This means that the user can continue using some, and preferably all, of your app's functionality even when they are offline.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Consider the following scenario: the user composes a long email, presses "Send", and then loses network connectivity. Because your app works offline, the email will be saved locally and sent automati
```suggestion
Consider the following scenario: the user composes a long email and presses "Send", not realizing they have lost network connectivity. Because your app works offline, the email will be saved locally and sent automatically when the device is back online.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Learn more about offline operation in [Offline and background operation](/en-US/docs/Web/Progressive_web_apps/Guides/Offline_and_background_operation).
```suggestion
Learn more about [offline and background operations](/en-US/docs/Web/Progressive_web_apps/Guides/Offline_and_background_operation).
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Learn more about offline operation in [Offline and background operation](/en-US/docs/Web/Progressive_web_apps/Guides/Offline_and_background_operation).
this is an MDN link writing thing

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Deep links are hyperlinks that point to specific pages within your app's domain. For example your app's home page might be available at `https://example.com/`, but you can also link to a specific pro
```suggestion
Deep links are hyperlinks that point to specific pages within your app's domain. For example, your app's home page might be available at `https://example.com/`, but you can also link to a specific product page at `https://example.com/products/123`.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Making different sections of your app available via unique URLs allows users to bookmark, navigate directly, and share specific content within your app. It also allows search engines to index your ap
```suggestion
Making different sections of your app available via unique URLs allows users to bookmark, navigate directly to, and share specific content within your app. It also allows search engines to index your app's content and make it discoverable through web searches.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Users have different expectations for installed apps than they do for websites. Users anticipate websites to need time to load and navigate, particularly on poor network connections. However, they ex
```suggestion
Users have different expectations for installed apps than they do for websites. Users anticipate websites to need time for loading and navigation, particularly on poor network connections. However, they expect installed apps to be always fast and responsive.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Users have different expectations for installed apps than they do for websites. Users anticipate websites to need time to load and navigate, particularly on poor network connections. However, they ex
maybe also "instantly" infront of "responsive"
```suggestion
Users have different expectations for installed apps than they do for websites. Users anticipate websites to need time for loading and navigation, particularly on poor network connections. However, they expect installed apps to be always fast and instantly responsive.
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +There are tools, APIs, and best practices that help measure and improve performance. To learn more, see [Web performance](/en-US/docs/Web/Performance).
```suggestion
There are tools, APIs, and best practices that help measure and improve performance. To learn more, see [web performance](/en-US/docs/Web/Performance).
```

2023-05-22 18:57 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Learn how to make your app accessible in [Accessibility](/en-US/docs/Web/Accessibility).
```suggestion
Learn how to make your app accessible in [accessibility](/en-US/docs/Web/Accessibility).
```

2023-05-22 19:10 UTC, estelle commented on files/en-us/web/progressive_web_apps/guides/best_practices/index.md
> +Your PWA is based on Web technologies which means that, on top of being installable on devices, it can run in web browsers too. To ensure compatibility, it's essential to [test your app](/en-US/docs/
or

```suggestion
Your PWA is based on Web technologies. This means that, on top of being installable on devices, PWAs can also run in web browsers. To ensure compatibility, it's essential to [test your app](/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing) across various browsers and operating systems.
```

2023-05-22 20:46 UTC, captainbrosset commented
Thank you @estelle, I committed your suggestions.

2023-05-22 21:36 UTC, estelle approved these changes
Yay! 🎉

2023-05-22 21:36 UTC, merged