PWA How-to: trigger installation from a PWA
mdn/content pull request #26842
Opened 2023-05-18 21:15 UTC by wbamberg

This PR adds a How-to for triggering the installation process from inside the app, using `beforeinstallprompt`. Having dug into this event a bit for https://github.com/mdn/content/pull/26828 I thought I might as well write the how-to up.

A couple of questions:
- arguably we might want to make this "how to customize app install" and include stuff about customizing the prompt itself. But I didn't do that partly because these seem like quite distinct things to want to do, and partly because this bit is done and we can merge it, and the other stuff isn't.
- I wrote a mini-PWA to test this out. It made me wonder if we should have mini-examples in mdn/pwa-examples for how-to guides. It's nice having working code to back this stuff up.
- I wasn't sure about `appinstalled`, or if there is more to be said there. I was a bit surprised actually that although I call `preventDefault()` I still get the icon in the URL bar.

2023-05-25 17:21 UTC, captainbrosset requested changes

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +By default, if the user visits your website, and the browser determines that the site is [installable as a PWA](/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#installability), th
"the browser shows an install prompt containing the app's name and icon": it might be good to find a more general way to describe this since browsers are free to implement whatever they want for this, and I know Chrome has been experimenting with showing screenshots in there too.
So I think MDN shouldn't give the impression that it's only name and icon, because it could change tomorrow to include more.

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +However, you can implement your own in-app UI to ask the user if they want to install your app, which will trigger the install prompt. The benefit of this is that you can provide more context about y
Another benefit is that an in-app custom install experience is often easier to discover too. Users don't always see the super small install button in the address bar. It would be good to mention this too here.

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +We're setting its [`hidden`](/en-US/docs/Web/HTML/Global_attributes/hidden) attribute, because if the user visits the site with a browser that can't install it, we don't want the install UI to be vis
```suggestion
We're setting the button's [`hidden`](/en-US/docs/Web/HTML/Global_attributes/hidden) attribute, because if the user visits the app with a browser that can't install it, we don't want the install UI to be visible. Next, we'll see how to make then button visible only on browsers that support installing PWAs locally.
```

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +As soon as the browser has determined that it can install your site, it fires the {{domxref("Window.beforeinstallprompt_event", "beforeinstallprompt")}} event in the global {{domxref("Window")}} scop
```suggestion
As soon as the browser has determined that it can install your app, it fires the {{domxref("Window.beforeinstallprompt_event", "beforeinstallprompt")}} event in the global {{domxref("Window")}} scope.
```

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +In our main app code, we will listen for this event:
```suggestion
In your main app code, we will listen for this event:
```

So far the article has used "you/your" to talk to the user. So it feels a bit out of place to start using "we/our" here.

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +- Take a reference to the event object that's passed into the handler. This is an instance of {{domxref("BeforeInstallPromptEvent")}}, and is what will enable us to prompt the user to install our app
```suggestion
- Take a reference to the event object that's passed into the handler. This is an instance of {{domxref("BeforeInstallPromptEvent")}}, and is what will enable you to prompt the user to install your app.
```

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +- Reveal our in-app install UI.
```suggestion
- Reveal our in-app install UI by removing the `install` attribute on the button.
```

Feel free to ignore, but I thought the extra detail added clarity.

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +The `installPrompt` variable was initialized with the `BeforeInstallPromptEvent` object in our `beforeinstallprompt` event handler. If `installPrompt` hasn't been initialized, for any reason, we do n
The rest of the article uses we/our. I'm fine either way, I just think we should be consistent.

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +  disableInAppInstallPrompt();
Should we use the outcome to call this only if its value is `accepted`?

2023-05-25 17:21 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +window.addEventListener("appinstalled", () => {
TIL. I had no idea this existed! That's a great tip to hide the install button.

2023-05-25 17:33 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +By default, if the user visits your website, and the browser determines that the site is [installable as a PWA](/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#installability), th
Yeah, I meant "minimally name and icon" but could be clearer here.

2023-05-25 21:03 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +By default, if the user visits your website, and the browser determines that the site is [installable as a PWA](/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#installability), th
I just added "at a minimum" here but would accept some different/better wording.

2023-05-25 21:06 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +The `installPrompt` variable was initialized with the `BeforeInstallPromptEvent` object in our `beforeinstallprompt` event handler. If `installPrompt` hasn't been initialized, for any reason, we do n
https://github.com/mdn/content/pull/26842/commits/dea50ab2e8625ffb4d8cb70bccc3ab5dd3633b66 includes changes to try to make it consistent.

It felt most natural to use "you" at the start, when we are talking about what "you" can do with this, and then "we" once we are talking about the actual code walkthrough.

2023-05-25 21:07 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/how_to/trigger_install_prompt/index.md
> +  disableInAppInstallPrompt();
I have kept this, mostly because Chrome just fires `beforeinstallprompt` again anyway once the prompt is dismissed, so it didn't accomplish anything.

2023-05-30 15:48 UTC, captainbrosset approved these changes
Looks good, thanks Will!

I just thought of something else to add here. But it's probably fine to merge this as is and then land a new PR to add the new section.

It'd be good to add a new section detailing how to hide the in-app install button when the user launches the app after it got installed. If the user installs the app and then, later, opens it from the dock or taskbar, you don't want the button to be displayed then.

There are 2 techniques that I know of: using the `start_url` of the manifest to pass a query string parameter liked `?is_installed=true` and using this at runtime to hide the button. Or using `matchMedia` to check if the display mode is `standalone`, which would mean that the app isn't running in the browser.

2023-05-31 07:09 UTC, captainbrosset commented
> I did experiment with this, and what I found was that the install button wasn't displayed when the app was installed, I think because `beforeinstallprompt` didn't fire (which is what I would have expected, because why would the browser offer to install something that's already installed?).

Oh good point, I somehow had forgotten that you're only showing the button on that event. All good then.

2023-05-31 07:09 UTC, merged