scripting.executeScript: result serialization incompatibility
mdn/content pull request #26857
Opened 2023-05-19 14:44 UTC by maxnikulin

### Description

Explicitly say that Firefox and Chrome use different serialization algorithms to pass return value of `scripting.executeScript()` WebExtensions method.

### Motivation

Despite current description of script result has a link to the Chrome incompatibilities page, wording is confusing. The phrase does not suggest that another serialization method is implemented in Chrome. Explicit mention of JSON serialization along with structured clone should warn readers about corner cases.

2023-05-24 04:33 UTC, rebloor approved these changes

2023-05-24 04:33 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result values must be [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) in Firefox while [JSON serialization algorithm](/en-US/docs/Web/JavaScript/Reference/G
```suggestion
The result values must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) in Firefox or [JSON serialization algorithm](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) object in Chrome. See [Data cloning algorithm](/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#data_cloning_algorithm) in the Chrome incompatibilities article for more information).
```

2023-05-24 15:52 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result values must be [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) in Firefox while [JSON serialization algorithm](/en-US/docs/Web/JavaScript/Reference/G
Thank you for review. I would avoid the term "object" since result may be a primitive value as a number or `true`/`false`.  Please, consider the following variant:

The script result must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) value in Chrome. The [Chrome incompatibilities](/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities) article discusses it in more details in the [Data cloning algorithm](/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#data_cloning_algorithm) section.

However I do not mind to use second sentence as in your suggestion (with removed closed parenthesis at the end).

2023-05-25 07:23 UTC, willdurand commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result values must be [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) in Firefox while [JSON serialization algorithm](/en-US/docs/Web/JavaScript/Reference/G
sounds good to me

2023-05-25 10:41 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The result values must be [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) in Firefox while [JSON serialization algorithm](/en-US/docs/Web/JavaScript/Reference/G
I have added a commit with my variant

2023-05-25 15:38 UTC, rebloor requested changes
@maxnikulin you seem to have introduced errors in the link URLs

2023-05-25 15:59 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The script result must be a [structured cloneable](https://github.com/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](https://github.com/en-US
> @maxnikulin you seem to have introduced errors in the link URLs

Thanks. I am trying to get some impression of GitHub web UI. I did not expect that pasting formatted text may convert relative link hrefs to absolute ones.

2023-05-25 16:06 UTC, rebloor requested changes

2023-05-25 16:06 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The script result must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](/en-US/docs/Web/JavaScript/Reference/Globa
```suggestion
The script result must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) value in Chrome. The [Chrome incompatibilities](/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities) article discusses this difference in more detail in the [Data cloning algorithm](/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#data_cloning_algorithm) section.
```

2023-05-25 16:07 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The script result must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](/en-US/docs/Web/JavaScript/Reference/Globa
Sorry, missed on of the link issues.

2023-05-25 16:25 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/api/scripting/executescript/index.md
> +The script result must be a [structured cloneable](/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) value in Firefox or a [JSON-serializable](/en-US/docs/Web/JavaScript/Reference/Globa
> Sorry, missed one of the link issues.

My bad, I did not noticed it as well

2023-05-25 16:35 UTC, rebloor approved these changes

2023-05-25 16:35 UTC, merged

2023-05-25 16:36 UTC, rebloor commented
Thanks @maxnikulin