HTTP header "Digest": set status to "deprecated", fixed legacy description
mdn/content pull request #26885
Opened 2023-05-21 21:03 UTC by jfrech

Legacy description based off of [draft 7](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-07).

2023-05-21 23:04 UTC, hamishwillee commented on files/en-us/web/http/headers/digest/index.md
>  {{HTTPSidebar}}
This is the way deprecation is normally added. We'll keep your note because it is more informative.
```suggestion
{{HTTPSidebar}}{{Deprecated_Header}}
```

2023-05-21 23:16 UTC, hamishwillee commented
Thanks very much. This is great but we'll want to do more. From the [current spec](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers#name-since-draft-ietf-httpbis-digest):

> Introduced `Repr-Digest` and `Want-Repr-Digest`, and deprecated `Digest` and `Want-Digest`. Use of Structured Fields. 1993, 1919

So we want to deprecate `Want-Digest` and add `Repr-Digest` and `Want-Repr-Digest`. Do you want to take a shot at that?

Note that there are a couple of macros we use to indicate deprecation - I added one above for the header, but in lists of headers and whatever you can use `{{Deprecated_Inline}}`.

If `Repr-Digest is a representation header we'll want to add it here too: https://developer.mozilla.org/en-US/docs/Glossary/Representation_header

@teoli2003 The deprecated macro should really be able to include the information in @jfrech warning block. Can we modify the macro to allow specification of what the deprecation cause/replacement is?

2023-05-29 17:10 UTC, jfrech commented
@hamishwillee In e. g. [`Sec-CH-UA-Full-Version`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Full-Version), deprecation replacement is indicated by a **Note**. I only used a **Warning** since e. g. [`Accept-CH-Lifetime`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH-Lifetime) notes a draft removal as a **Warning**.  
So a more specific way to note prior feature existence and/or recommended newer alternatives may indeed be nice to have.

2023-05-29 18:16 UTC, jfrech commented
@hamishwillee May I double-check my interpretation of the spec with you?  

I read it to claim the `Repr-` to be the *Selected Representation*, fully dependent on Content Negotiation which takes `Content-Type` into account. Does this mean `Content-Digest` is of no use whatsoever if the "actual message content" (cf. https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-12#section-2) is not selectable as a representation (e.&hairsp;g. MDN's source files only being selectable as HTML)?

2023-05-29 20:44 UTC, jfrech commented
@hamishwillee Should we remove "Content-Location" from the [glossary](https://developer.mozilla.org/en-US/docs/Glossary/Representation_header)? After all, it does not describe the representation sent by the associated HTTP message.

2023-05-29 23:41 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +A **representation header** is an {{glossary("HTTP_header", "HTTP header")}} that describes the particular _representation_ of the target resource sent in an HTTP message body.
Why "target"? 
My thinking here is that a representation header may be present in both request and response messages. So you can have a representation header without any resource in the message body. 

```suggestion
A **representation header** is an {{glossary("HTTP_header", "HTTP header")}} that describes the particular _representation_ of a resource.
```

2023-05-29 23:43 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +Whilst representations are different forms of resources, representations can themselves also be transmitted in different forms: E.&hairsp;g. HTTP/1.1's {{HTTPHeader("Transfer-Encoding")}} does *not*
```suggestion
Whilst representations are different forms of resources, representations can themselves also be transmitted in different forms.
For example, HTTP/1.1's {{HTTPHeader("Transfer-Encoding")}} does *not* affect the representation, whereas e.g. {{HTTPHeader("Content-Range")}} does.  
```

2023-05-29 23:45 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +If sent as a response to a `HEAD` request, they describe the body content representation that _would_ be selected if the resource was requested with a `GET` request.
Given it says "representation headers may be present in both HTTP request and response messages, I wonder if we need  an example in a request?

2023-05-29 23:46 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +Representation headers include: {{HTTPHeader("Content-Type")}}, {{HTTPHeader("Content-Encoding")}}, {{HTTPHeader("Content-Language")}}, {{HTTPHeader("Content-Location")}}, {{HTTPHeader("Content-Range
```suggestion
Representation headers include: {{HTTPHeader("Content-Type")}}, {{HTTPHeader("Content-Encoding")}}, {{HTTPHeader("Content-Language")}}, {{HTTPHeader("Content-Location")}}, {{HTTPHeader("Content-Range")}}, {{HTTPHeader("Repr-Digest")}}, and {{HTTPHeader("Digest")}} {{Deprecated_Inline}}.
```

2023-05-29 23:48 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +- {{HTTPHeader("Content-Digest")}}, {{HTTPHeader("Repr-Digest")}}, {{HTTPHeader("Want-Content-Digest")}}, {{HTTPHeader("Want-Repr-Digest")}}
Deprecated things are "less important" and should IMO go last.

```suggestion
- {{HTTPHeader("Content-Digest")}}, {{HTTPHeader("Repr-Digest")}}, {{HTTPHeader("Want-Content-Digest")}}, {{HTTPHeader("Want-Repr-Digest")}}
- {{HTTPHeader("Digest")}} {{Deprecated_Inline}}, {{HTTPHeader("Want-Digest")}} {{Deprecated_Inline}}
```

2023-05-30 00:06 UTC, hamishwillee commented
> g. [`Sec-CH-UA-Full-Version`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Full-Version), deprecation replacement is indicated by a **Note**. I only used a **Warning** since e. g. [`Accept-CH-Lifetime`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH-Lifetime) notes a draft removal as a **Warning**.

Yes, it would be great to be able to include deprecation replacement info in the macro itself, allowing just one note to be used to indicate deprecation. Let's see if we can get traction here: https://github.com/mdn/yari/issues/8969.

I'm going to change to a note. This is purely my taste - there is no real rule as far as I know.

2023-05-30 00:07 UTC, hamishwillee commented on files/en-us/web/http/headers/digest/index.md
> +> **Warning:** This header was removed from the specification in [draft 8](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-08). Use {{HTTPHeader("Repr-Digest")}} instead. For
```suggestion
> **Note:** This header was removed from the specification in [draft 8](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-08).
> Use {{HTTPHeader("Repr-Digest")}} instead.
> For `id-*` digest algorithms, use {{HTTPHeader("Content-Digest")}}.
```

2023-05-30 00:07 UTC, hamishwillee commented on files/en-us/web/http/headers/want-digest/index.md
> +> **Warning:** This header was removed from the specification in [draft 8](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-08). Use {{HTTPHeader("Want-Repr-Digest")}} instead.
```suggestion
> **Note:** This header was removed from the specification in [draft 8](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-08). Use {{HTTPHeader("Want-Repr-Digest")}} instead. For `id-*` digest algorithms, use {{HTTPHeader("Want-Content-Digest")}}.
```

2023-05-30 00:18 UTC, hamishwillee commented on files/en-us/web/http/headers/digest/index.md
> +The **`Digest`** response or request HTTP header provides the other side with a {{Glossary("digest")}} of the _selected representation_ or _content_. It can be requested by using the {{HTTPHeader("Wa
The "or content" seems redundant. The content is a selected representation. Would this be better?

```suggestion
The **`Digest`** response or request HTTP header provides a {{Glossary("digest")}} of the _selected representation_ of the requested/provided resource.
It can be requested by using the {{HTTPHeader("Want-Digest")}} header.
```

2023-05-30 00:19 UTC, hamishwillee commented on files/en-us/web/http/headers/digest/index.md
> +  - : The result of applying the digest algorithm to the resource representation and encoding (for non-`id-*` digest algorithm values) the result.
```suggestion
  - : The result of applying the digest algorithm to the resource representation and encoding the result (for non-`id-*` digest algorithm values).
```

2023-05-30 00:19 UTC, hamishwillee commented on files/en-us/web/http/headers/digest/index.md
> +    The choice of digest algorithm also determines the encoding to use: for example SHA-256 uses base64 encoding whilst unixsum is represented by a decimal integer.
```suggestion
    The choice of digest algorithm also determines the encoding to use: for example SHA-256 uses base64 encoding, whilst unixsum is represented by a decimal integer.
```

2023-05-30 00:22 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +{{HTTPSidebar}}{{SeeCompatTable}}
```suggestion
{{HTTPSidebar}}{{SeeCompatTable}}

The **`Want-Repr-Digest`** request or response header states the wish for a {{HTTPHeader("Repr-Digest")}} header.
```

2023-05-30 00:26 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.html
> +The **`Content-Digest`** response or request header provides a {{Glossary("digest")}} of the _actual message content_, the preimage of computing the _selected representation_ (e.&hairsp;g. [Range Req
Avoid "e.g.". You'll see it a bit, but we tend to expand out to For example because screen readers do a poor job with these kinds of abbreviation. We also use highlighting sparingly.

```suggestion
The **`Content-Digest`** response or request header provides a {{Glossary("digest")}} of the actual message content, the preimage of computing the _selected representation_.
For example, [Range Requests](/en-US/docs/Web/HTTP/Range_requests) or [Content Encoding](/en-US/docs/Web/HTTP/Content_negotiation).  
```

2023-05-30 00:28 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.html
> +Note that the selected representation is independent of wire transmission (e.&hairsp;g. HTTP/1.1's {{HTTPHeader("Transfer-Encoding")}}). Note furthermore that the actual message content is independen
```suggestion
Note that the selected representation is independent of wire transmission, such as HTTP/1.1's {{HTTPHeader("Transfer-Encoding")}}).
Note furthermore that the actual message content is independent of [Content Negotiation](/en-US/docs/Web/HTTP/Content_negotiation): this means that if a target resource is available in two different MIME types (say), their corresponding {{HTTPHeader("Repr-Digest")}}s without using [Range Requests](/en-US/docs/Web/HTTP/Range_requests) may *both* not match `Content-Digest`, since the "true" content source is never sent.  
```

2023-05-30 00:30 UTC, hamishwillee commented on files/en-us/web/http/headers/want-content-digest/index.html
> +The **`Want-Content-Digest`** request or response header states the wish for a {{HTTPHeader("Content-Digest")}} header.
Is this really a response header? (asking, not stating). I should check spec, but I have other things on my queue today.

> 
```suggestion
The **`Want-Content-Digest`** request header indicates a desire for the response to include a {{HTTPHeader("Content-Digest")}} header.
```

2023-05-30 00:31 UTC, hamishwillee commented on files/en-us/web/http/headers/want-content-digest/index.html
> +{{HTTPSidebar}}{{SeeCompatTable}}
```suggestion
{{HTTPSidebar}}{{SeeCompatTable}}

The **`Want-Content-Digest`** request or response header states the wish for a {{HTTPHeader("Content-Digest")}} header.
```

2023-05-30 00:33 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.html
> +{{HTTPSidebar}}{{SeeCompatTable}}
```suggestion
{{HTTPSidebar}}{{SeeCompatTable}}

The **`Repr-Digest`** response or request header is the `Repr-` analogue to {{HTTPHeader("Content-Digest")}}.

**`Repr-Digest`** takes on an [RFC8941 dictionary](https://www.rfc-editor.org/rfc/rfc8941#section-3.2) whose keys are digest algorithms and whose values for `sha-256` and `sha-512` are [byte sequences](https://www.rfc-editor.org/rfc/rfc8941#section-3.3.5) (colon-wrapped standard base64 with padding).

## Digest algorithms

Only two digest algorithms are currently registered and not considered insecure: `sha-512` and `sha-256`.  
The registered insecure digest algorithms are: `md5`, `sha` (SHA-1), `unixsum`, `unixcksum`, `adler` (ADLER32) and `crc32c`
```

2023-05-30 00:33 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +The **`Want-Repr-Digest`** request or response header states the wish for a {{HTTPHeader("Repr-Digest")}} header.
Is this really a response header (as well)? (asking, not stating). I should check spec, but I have other things on my queue today.

```suggestion
The **`Want-Content-Digest`** request header indicates a desire for the response to include a {{HTTPHeader("Content-Digest")}} header.
```

2023-05-30 00:34 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +
Examples? Are there options to this - in the same way as `Want-Digest`?

2023-05-30 00:35 UTC, hamishwillee commented on files/en-us/web/http/headers/want-digest/index.md
>  <table class="properties">
These tables need to appear in your new documents, as do the Syntax and directive boxes. See https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/HTTP_header_page_template

2023-05-30 00:38 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.html
> +The **`Content-Digest`** response or request header provides a {{Glossary("digest")}} of the actual message content, the preimage of computing the _selected representation_.
1. See my comment above about the page template.
2. I do not understand this term. I.e. what is "the preimage ...". I think you are suggesting that that there is some notional "default representation" or "data representation" that we refer to as the "content". So this is the digest of the resource if you don't specify the representation you want? Is that right? We should use common English to explain the differences between this and the representation.

2023-05-30 00:45 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.html
> +The **`Content-Digest`** response or request header provides a {{Glossary("digest")}} of the actual message content, the preimage of computing the _selected representation_.
@jfrech 

So the way I read the spec - now I have done so - is that this is the digest of the actual message content and has nothing to do with the selected representation, unless the selected representation is the actual message content. 

In other words, say you have a resource that is sent across a bunch of messages. This is the digest of just this part of the message. It allows you to verify the integrity of each part of the message independently. 

Does that make sense? So it isn't a "preimage" or whatever

2023-05-30 00:52 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.html
> +The **`Repr-Digest`** response or request header is the `Repr-` analogue to {{HTTPHeader("Content-Digest")}}.
So no, based on https://github.com/mdn/content/pull/26885/files#r1209609608 this is not true.

The `Content-Digest` is a digest of _each_ message payload, independent of whether or not the data is part of a multi-part message. It allows integrity checking of a single message, in the same way as a CRC might on a packet.
The `Repr-Digest` is  a Digest of the whole resource, which might be sent across multiple messages. This allows the whole resource to be checked for integrity at the end, after all the parts have been recieved and been reassembled. So if your representation can be sent in a single message, then it might match the `Content-Digest`.

Wihtout digging, I see the `Repr` versions as pretty much the same as the original versions, but with better names that allow them to be differentiated from Content-Digest. 

See comment above about page templates. This one is not bad, but needs syntax block etc.

2023-05-30 00:55 UTC, hamishwillee commented
> @hamishwillee May I double-check my interpretation of the spec with you?
> 
> I read it to claim the `Repr-` to be the _Selected Representation_, fully dependent on Content Negotiation which takes `Content-Type` into account. Does this mean `Content-Digest` is of no use whatsoever if the "actual message content" (cf. https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-12#section-2) is not selectable as a representation (e. g. MDN's source files only being selectable as HTML)?

But as per the notes I just added, I think you understand `Content-Digest` to mean "a digest of some default representation of the content". My interpretation is that it means "message-specific digest". That may make your question meaningless. Have a think and then get back to me.

2023-05-30 01:18 UTC, hamishwillee commented
@jfrech Can you please rename the markdown files from index.html to index.md - these are the ones for which no report is being generated: https://github.com/mdn/content/pull/26885#issuecomment-1556319186

2023-05-30 13:36 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +A **representation header** is an {{glossary("HTTP_header", "HTTP header")}} that describes the particular _representation_ of the target resource sent in an HTTP message body.
I also changed "the particular _representation_" to "one particular _representation_".

2023-05-30 13:52 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +If sent as a response to a `HEAD` request, they describe the body content representation that _would_ be selected if the resource was requested with a `GET` request.
Both a positive and negative example may make sense: something akin to:
### positive example
```http
PUT /api/transact HTTP/1.1
Want-Content-Digest: sha-256
Content-Type: text/json
...
```
```http
HTTP/1.1 201 Created
Content-Digest: sha-256=:2IBI7hQn83oTCgB3Z/6apOl91WGoctRfRj/F9gkvVo8=:
Content-Encoding: br
Repr-Digest: sha-256=:W8oN3H3CmE/CBpV6ZPNozV2AIDzzQpWL7CCOXyDyDzI=:
...
```
### negative example
```http
GET /api/last-transaction HTTP/1.1
Accept: text/json, text/xml
Content-Digest: sha-256=:125+ms4/wPK0vMKM3oy9j4zu8HmPTmr7YVla229fhFc=:
...
```
```http
HTTP/1.1 406 Not Acceptable
Content-Digest: sha-256=:2IBI7hQn83oTCgB3Z/6apOl91WGoctRfRj/F9gkvVo8=:
...
```

2023-05-30 13:52 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +If sent as a response to a `HEAD` request, they describe the body content representation that _would_ be selected if the resource was requested with a `GET` request.
But I still wonder when it makes sense for the server to respond with `Want-Content-Digest`.

2023-05-30 14:03 UTC, jfrech commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +The **`Want-Repr-Digest`** request or response header states the wish for a {{HTTPHeader("Repr-Digest")}} header.
Yes; I am currently also not quite sure what its use would be:
> Senders can indicate their interest in Integrity fields and hashing
> algorithm preferences using the Want-Content-Digest or Want-Repr-
> Digest fields. These can be used in **both requests and responses**.

Cf. [draft-12, 4. Integrity preference fields](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-12#name-integrity-preference-fields) (emphasis mine)

2023-05-30 14:21 UTC, jfrech commented on files/en-us/web/http/headers/want-digest/index.md
>  <table class="properties">
Done in a18af4f1aec639ae6e0208ab966f0e31e43dff10; do you agree these header names are not forbidden?

2023-05-30 15:15 UTC, jfrech commented on files/en-us/web/http/headers/digest/index.md
> +The **`Digest`** response or request HTTP header provides the other side with a {{Glossary("digest")}} of the _selected representation_ or _content_. It can be requested by using the {{HTTPHeader("Wa
I did have a think; see further down.

2023-05-30 15:16 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.html
> +The **`Repr-Digest`** response or request header is the `Repr-` analogue to {{HTTPHeader("Content-Digest")}}.
I did have a think; see further down.

2023-05-30 15:17 UTC, jfrech commented
> (...) Have a think and then get back to me.

I had a think and now do agree with you. I thought `Content-` was stronger, but this is not the case.

2023-05-30 15:25 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +For example, the same data might be formatted as a particular media type such as XML or JSON<!--,--> or localized to a particular written language or geographical region<!--, and/or compressed or oth
@hamishwillee This is a tad tricky: the deprecated "Digest" header depended on e.&hairsp;g. "Content-Encoding". But "selected representation" in the "Repr-Digest"-sense does not depend on "Content-Encoding"; "Content-Digest", however, does.

2023-05-30 15:29 UTC, jfrech commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +
Cf. 4aa860481ca

2023-06-02 01:06 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +If sent as a response to a `HEAD` request, they describe the body content representation that _would_ be selected if the resource was requested with a `GET` request.
Yes, these kinds of examples make sense to me. And no, I don't understand when a server could ever response with Want-Content-Digest. I doubt its like those client hints where a server can specify a preference for future headers from the client.

If we can't prove it isn't a valid use case, I'd still just not cover this.

2023-06-02 01:16 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.html
> +The **`Want-Repr-Digest`** request or response header states the wish for a {{HTTPHeader("Repr-Digest")}} header.
Thanks for checking. I've emailed the spec authors.

2023-06-02 01:18 UTC, hamishwillee commented on files/en-us/web/http/headers/want-digest/index.md
>  <table class="properties">
Yes. Most new ish forbidden header names are prefixed with Sec, and there is nothing I see in the spec to indicate this is forbidden.

2023-06-02 01:33 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +If sent as a response to a `HEAD` request, they describe the body content representation that _would_ be selected if the resource was requested with a `GET` request.
Added in 72ee7b6a3b59f2f2ae41b848046c092390a48fd3.

2023-06-02 01:39 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +Whilst representations are different forms of resources, representations can themselves also be transmitted in different forms: an HTTP message frames (cf. e.&hairsp;g. HTTP/1.1's {{HTTPHeader("Trans
Can you globally purge the use of `&hairsp;`?

We might add a comment here about the fact that in some case `<!--, and/or compressed or otherwise encoded for transmission-->` is relevant?

2023-06-02 01:43 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +Whilst representations are different forms of resources, representations can themselves also be transmitted in different forms: an HTTP message frames (cf. e.&hairsp;g. HTTP/1.1's {{HTTPHeader("Trans
P.S. It doesn't quite "fit", but could perhaps be a "Note" since it is related, but also an aside.

2023-06-02 01:45 UTC, hamishwillee commented on files/en-us/glossary/representation_header/index.md
> +## Examples
Actually, I was wrong sorry. We try and avoid having examples in glossary docs. We try to keep the glossary as short as possible. These examples should exist, if they do not, in the reference pages - e.g. want-repr-digest.

2023-06-02 01:52 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.md
> +For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
I would reproduce them. This is arguable of course. I just like making a tiny bit easier for readers. You could still say "this is the same set as in Repr-Digest"

2023-06-02 01:52 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +## Examples
It didn't fit in the glossary. See bc31ed5466175c2e3f10fb759779cb43ddfecca2.

2023-06-02 01:54 UTC, hamishwillee commented on files/en-us/web/http/headers/want-content-digest/index.md
> +For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
Duplicate?

2023-06-02 01:54 UTC, jfrech commented on files/en-us/glossary/representation_header/index.md
> +For example, the same data might be formatted as a particular media type such as XML or JSON<!--,--> or localized to a particular written language or geographical region<!--, and/or compressed or oth
Ok.

2023-06-02 01:54 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.md
> +```http
So the request and response examples you put in the glossary would go better here - expanding out what a user might see. Ditto for the others.

2023-06-02 01:56 UTC, hamishwillee commented
@jfrech I think we're getting there. I'll see if I can get @teoli2003 to do subsequent review as he is more expert than me. He's been a little silent this last week or two so might be on holiday.

2023-06-02 02:03 UTC, jfrech commented on files/en-us/web/http/headers/want-repr-digest/index.md
> +```http
I put them in "Repr-Digest" (bc31ed5466175c2e3f10fb759779cb43ddfecca2), since I feel like the three others are variants.

2023-06-02 02:33 UTC, jfrech commented on files/en-us/web/http/headers/content-digest/index.md
> -`Content-Digest` would have the same value as {{HTTPHeader("Repr-Digest")}} if a representation was sent in a single message.
@hamishwillee My problem with "would have the same value as" is that first of all *sameness* could only apply in the dictionary sense and furthermore, e.&hairsp;g.
```http
Content-Digest: sha512=:z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==:
Content-Digest: sha256=:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=:
```
both describe the empty file yet there is (by design) no known notion of *sameness*.

2023-06-02 02:35 UTC, jfrech commented on files/en-us/web/http/headers/want-content-digest/index.md
> +For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
I don't think so; there are four files in total:
```
patch-1 $ grep -riI 'For permissible digest'
files/en-us/web/http/headers/want-repr-digest/index.md:For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
files/en-us/web/http/headers/content-digest/index.md:For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
files/en-us/web/http/headers/want-content-digest/index.md:For permissible digest algorithms see {{HTTPHeader("Repr-Digest")}}.
```

2023-06-02 03:35 UTC, hamishwillee commented on files/en-us/web/http/headers/want-repr-digest/index.md
> +```http
We tend to duplicate the reciprocal pairs; so you might have the same example in both. But hold off doing anything until Teoli comments. I might not be up to date on current patterns in this area.

2023-06-02 03:35 UTC, hamishwillee commented on files/en-us/web/http/headers/content-digest/index.md
> -`Content-Digest` would have the same value as {{HTTPHeader("Repr-Digest")}} if a representation was sent in a single message.
Fair enough! Reword as you think appropriate.

2023-06-08 18:34 UTC, jfrech commented
I will want to squash first before merging with master. @hamishwillee should I do?

2023-06-09 00:29 UTC, hamishwillee commented
We'll squash as part of the merge :-)

I guess @teoli2003 is still on holiday. If we get no response by Wednesday next week I'll do another review and merge.

2023-06-09 00:32 UTC, hamishwillee requested changes

2023-06-09 00:32 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.md
> +The **`Repr-Digest`** response or request header provides a {{Glossary("digest"}} of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource. It is in
Remove all cases of `e.hairsp;`

2023-06-09 00:46 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.md
> +> **Note:** In contrast to earlier drafts of the specification, the standard-base64-encoded digest bytes are wrapped in colons (`:`, ASCII 0x3A) as part of the [dictionary syntax](https://www.rfc-edi
Does not match the template https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/HTTP_header_page_template

Unless absolutely necessary, do not link the spec. It's our job to show how the API is used "for humans".

```suggestion

`Repr-Digest` directives dictionaries, with keys being names of digest algorithms and values being the digest in bytes, wrapped in colons (`:`, ASCII 0x3A).

```http-nolint
# Secure digest algorithms
Repr-Digest sha512=:calculated_digest:
Repr-Digest: sha-256=:calculated_digest:

# Insecure digest algorithms
Repr-Digest md5=:calculated_digest:
Repr-Digest sha=:calculated_digest:
Repr-Digest unixsum=:calculated_digest:
Repr-Digest unixcksum=:calculated_digest:
Repr-Digest adler=:calculated_digest:
Repr-Digest crc32c=:calculated_digest:
```

> 
(or an integer digest for legacy digest algorithms).
The 
> **Note:** Legacy digest algorithms (in earlier drafts of the specification), use an integer digest and do nor wrap it in colons.
```

2023-06-09 01:00 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.md
> +> It is often better to not to emit a `Repr-Digest` at all than to emit one that specifies an insecure digest algorithm.
FYI, I updated this to try put in format acceptable to the template. Let's see what @teoli2003 says.

2023-06-10 19:17 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.md
> +The **`Repr-Digest`** response or request header provides a {{Glossary("digest"}} of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource. It is in
Did you mean to replace my subphrase?

2023-06-10 19:20 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.md
> +> It is often better to not to emit a `Repr-Digest` at all than to emit one that specifies an insecure digest algorithm.
Your statement is incorrect: e. g. "unixcksum" is not a byte array dictionary value.

2023-06-10 19:22 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.md
> +> **Note:** In contrast to earlier drafts of the specification, the standard-base64-encoded digest bytes are wrapped in colons (`:`, ASCII 0x3A) as part of the [dictionary syntax](https://www.rfc-edi
I think it is much more human-readable if one does not say "a dictionary" (which is very ambiguous) but rather "an RFC8941 dictionary" which specifically states which syntactical form of a dictionary is at play here.

Furthermore, half-correctly and vaguely describing the dictionary as you have done benefits no one.

2023-06-16 01:31 UTC, hamishwillee commented on files/en-us/web/http/headers/repr-digest/index.md
> +The **`Repr-Digest`** response or request header provides a {{Glossary("digest"}} of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource. It is in
No. 

What I am saying here is that I don't see the benefit of ``e.hairsp;g.` over `e.g.`

2023-06-16 02:07 UTC, hamishwillee commented
@jfrech Other than the linter nits I think I've taken this as far as I want to. @teoli2003 should be around soon, and hopefully will take this to the end.

2023-07-17 05:57 UTC, teoli2003 requested changes
A few extra points, but overall this looks good and close to be ready

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/glossary/representation_header/index.md
> +Whilst representations are different forms of resources, representations can themselves also be transmitted in different forms: an HTTP message frames (cf. e.&hairsp;g. HTTP/1.1's {{HTTPHeader("Trans
```suggestion
While representations are different forms of resources, representations can themselves also be transmitted in various forms: an HTTP message frames (cf., e.g., HTTP/1.1's {{HTTPHeader("Transfer-Encoding")}}), a particular stream of octets (cf., e.g., {{HTTPHeader("Content-Range")}}) derived from the _selected representation_.
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/glossary/representation_header/index.md
> +- pertaining to particular forms of the selected representation: {{HTTPHeader("Content-Digest")}}, {{HTTPHeader("Want-Content-Digest")}}
```suggestion
- {{HTTPHeader("Content-Digest")}}, {{HTTPHeader("Want-Content-Digest")}}
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/content-digest/index.md
> +"content" in this setting refers to a particular octet representation of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource.
```suggestion
In this setting, _content_ refers to a particular octet representation of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource.
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +The **`Repr-Digest`** response or request header provides a {{Glossary("digest"}} of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource. It is in
```suggestion
The **`Repr-Digest`** response or request header provides a {{Glossary("digest"}} of the [selected representation](https://www.rfc-editor.org/rfc/rfc9110#section-6.4) of the target resource. It is invariant under e.g., {{HTTPHeader("Content-Encoding")}} or {{HTTPHeader("Content-Range")}}, which do affect the {{HTTPHeader("Content-Digest")}}. Furthermore, [Content Negotiation](/en-US/docs/Web/HTTP/Content_negotiation) can result in different selected representations with different representation digests.
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +> **Note:** In contrast to earlier drafts of the specification, the standard-base64-encoded digest bytes are wrapped in colons (`:`, ASCII 0x3A) as part of the [dictionary syntax](https://www.rfc-edi
I wonder if we should have a glossary entry for RFC8941 dictionary: I don't like to send readers to the spec (that are difficult to understand) to grasp the syntax.

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +### Example: HTTP response where `Repr-Digest` and `Content-Digest` coincide
```suggestion
### HTTP response where `Repr-Digest` and `Content-Digest` coincide
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +### Example: HTTP responses where {{HTTPHeader("Repr-Digest")}} and {{HTTPHeader("Content-Digest")}} diverge
```suggestion
### HTTP responses where {{HTTPHeader("Repr-Digest")}} and {{HTTPHeader("Content-Digest")}} diverge
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +### Example: Successful HTTP request-response employing {{HTTHeader("Want-Repr-Digest")}}, {{HTTHeader("Repr-Digest")}}, {{HTTHeader("Content-Digest")}}
```suggestion
### Successful HTTP request-response employing {{HTTHeader("Want-Repr-Digest")}}, {{HTTHeader("Repr-Digest")}}, {{HTTHeader("Content-Digest")}}
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/repr-digest/index.md
> +### Example: Unsuccessful HTTP request-response employing {{HTTHeader("Repr-Digest")}}
```suggestion
### Unsuccessful HTTP request-response employing {{HTTHeader("Repr-Digest")}}
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/want-content-digest/index.md
> +> **Note:** In contrast to earlier drafts of the specifications, the weighting is *not* declared via [q-values](/en-US/docs/Glossary/Quality_values).
```suggestion
> **Note:** In contrast to earlier drafts of the specifications, the weighting is _not_ declared via [q-values](/en-US/docs/Glossary/Quality_values).
```

2023-07-17 05:57 UTC, teoli2003 commented on files/en-us/web/http/headers/want-repr-digest/index.md
> +> **Note:** In contrast to earlier drafts of the specifications, the weighting is *not* declared via [q-values](/en-US/docs/Glossary/Quality_values).
```suggestion
> **Note:** In contrast to earlier drafts of the specifications, the weighting is _not_ declared via [q-values](/en-US/docs/Glossary/Quality_values).
```

2024-01-09 11:23 UTC, bsmth commented
Hi @jfrech - thanks a lot for the submission. There are some review comments outstanding above, would you like to come back to this one? @teoli2003 has indicated that ["this looks good and close to be ready"](https://github.com/mdn/content/pull/26885#pullrequestreview-1532019996), so it would be great to have your work land eventually.

2024-03-28 00:46 UTC, wbamberg commented
@bsmth , except for https://github.com/mdn/content/pull/26885#discussion_r1264900105, @teoli2003 has provided suggestions for all his comments. Perhaps we could just accept them all and merge this, and let https://github.com/mdn/content/pull/26885#discussion_r1264900105 go?

2024-03-28 15:15 UTC, bsmth commented
> @bsmth , except for [#26885 (comment)](https://github.com/mdn/content/pull/26885#discussion_r1264900105), @teoli2003 has provided suggestions for all his comments. Perhaps we could just accept them all and merge this and let [#26885 (comment)](https://github.com/mdn/content/pull/26885#discussion_r1264900105) go?

That sounds fine (I see we added the awaiting resp label `on Dec 8, 2023`) let's try to get the improvements merged, in that case. I don't think the author is active on GitHub anymore by the looks of it.

2024-03-28 18:02 UTC, wbamberg commented
OK, @bsmth , I have fixed the macro invocation errors and the front matter linting errors. There are still reviewdog comments but _I think_ we can ignore them.

I haven't tried to properly review the PR content but from the existing reviews it seems close and surely better than what we have at the moment. Maybe we can give @hamishwillee and @teoli2003 a couple of days to re-review, and if there's no response merge it then?

2024-03-29 15:13 UTC, jfrech commented
@wbamberg It looks like the linter only complained about ordering, which you seemed to have abided by. Resolving its conversations.

2024-03-29 15:14 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.md
> -### HTTP response where `Repr-Digest` and `Content-Digest` coincide
Is markup not allowed in headers or is this edit of your own taste? Looking at <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers>, HTTP headers seem to be marked up as inline code.

2024-03-29 16:35 UTC, wbamberg commented on files/en-us/web/http/headers/repr-digest/index.md
> -### HTTP response where `Repr-Digest` and `Content-Digest` coincide
Markup is allowed. tbh all that happened here was that I removed the macro calls from some of the headers, which also removed the code style, then I removed it here just to be consistent. I don't mind either way, and if you'd like to put the code style back (not the macros though) I am happy with that.

2024-03-29 19:18 UTC, jfrech commented on files/en-us/web/http/headers/repr-digest/index.md
> -### HTTP response where `Repr-Digest` and `Content-Digest` coincide
Done in bf6ba95d087150a1b413dd1363b28069b9bc8bc8.

2024-04-04 22:12 UTC, hamishwillee approved these changes
I'm away so I can't give it my full attention, but it looks good to me on scan (and it's had a lot of eyes on it).

2024-04-08 18:54 UTC, teoli2003 approved these changes
👍

2024-04-08 18:54 UTC, merged