Remove never-supported MathML features
mdn/content pull request #2691
Opened 2021-02-25 15:53 UTC by ddbeck

This removes some stuff related to the removal of never-implemented features from BCD: https://github.com/mdn/browser-compat-data/pull/6958.

This is my first time cleaning up after a feature removal directly. Open to suggestions on how to handle this sort of thing going forward.

2021-02-25 18:43 UTC, chrisdavidmills requested changes
Looks mostly good @ddbeck ! Just a couple of points:

1. `<mglyph>` and `<mlabeledtr>` are both still listed on /en-US/docs/Web/MathML/Element
2. Did you use the correct tool for deleting documents (see https://github.com/mdn/content/blob/main/README.md#deleting-a-document)? I would've expected some changes to the wikihistory file too.

2021-03-02 07:28 UTC, chrisdavidmills requested changes
Nice work @ddbeck . This looks nearly there now; just a couple more small comments, which should be pretty quick to wrap up.

2021-03-02 07:28 UTC, chrisdavidmills commented on files/en-us/web/mathml/element/mtable/index.html
>   <dd>Specifies the width of table columns.</dd>
The corresponding `<dd>` should be removed here too, right?

2021-03-02 07:28 UTC, chrisdavidmills commented on files/en-us/web/mathml/attribute/index.html
>    <tr id="minsize">
General comment on this file. The commit says that a mention or mentions of the `side` atttibute is removed, but I don't see anything being touched that looks like that. Just a heads up in case something was missed.

2021-03-03 10:31 UTC, ddbeck commented on files/en-us/web/mathml/attribute/index.html
>    <tr id="minsize">
Good catch! I double-checked and this is OK. `side` was removed from BCD, but it didn't have any consequence in the content. But I copied the list of attributes from the BCD PR and forgot to omit that one.

2021-03-03 10:32 UTC, ddbeck commented on files/en-us/web/mathml/element/mtable/index.html
>   <dd>Specifies the width of table columns.</dd>
Yes! Fixed with a17039154.

2021-03-03 10:35 UTC, chrisdavidmills approved these changes
I think that just about does it then. Super work here @ddbeck , thanks a lot. Let's get this merged.

2021-03-03 10:35 UTC, merged