feat(glossary): add sidebar to Glossary pages
mdn/content pull request #26985
Opened 2023-05-26 10:05 UTC by bsmth

### Description

This PR adds the glossary sidebar to sub-pages

### Motivation

This should improve discoverability and allow readers to find other terms

2023-05-26 12:24 UTC, Josh-Cena requested changes
Instead of adding this unmaintainable chunk, we should add a new macro to Yari. The current implementation is not performant as the sidebar height grows with the section's size (and this section is meant to grow steadily). We should implement the sidebar as automatically categorized by initial letter and collapsed under `<details>`.

2023-06-02 12:32 UTC, bsmth commented
> we should add a new macro to Yari

Yes, this is better. I was hoping to avoid adding more macros, but this is an exception.

>We should implement the sidebar as automatically categorized by initial letter and collapsed under <details>.

The linked PR does a 1:1 implementation of the current Glossary sidebar, there will be generic sidebar improvements coming soon (filtering). If this PR lands, I would look into collapsing alphabetically like you suggested, but this will be a follow-up for now.

2023-06-08 13:17 UTC, Rumyra approved these changes

2023-06-08 13:17 UTC, Rumyra approved these changes

2023-06-08 13:19 UTC, merged