RTCStatsReport - make this the center of statistics docs
mdn/content pull request #27028
Opened 2023-05-29 07:25 UTC by hamishwillee

We're flattening the [`RTCStats`](https://developer.mozilla.org/en-US/docs/Web/API/RTCStats) hierarchy and making the entry points clearer. This updates [RTCStatsReport](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) to include the list of types it might return and information about the map methods.

I have individually documented the map methods. I don't think we can just link to map because the versions in which these are implemented would then not be documentable in the context of RTCStatsReport BCD.

If this gets in, next step would be to purge RTCStats. Then start filling out the other dictionaries.

2023-05-29 07:26 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +- {{domxref("RTCStatsReport.[@@iterator]()")}} {{ReadOnlyInline}}
@wbamberg I can't get link to the `@@iterator` method to work so I did not submit a doc for this. The only example I could fine was MediaKeyStatusMap and that doesn't work either - i.e. breaks the build.

2023-05-29 07:30 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +### The statistic types
Note that this is the current set of statistics. I took it from https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_Statistics_API stripping out all the ones that are not in the spec.

@wbamberg From what I can tell the WebRTC stats API has gone though so much churn in recent times that there is no point trying to keep any of the legacy information. We should just try to update it to what it is now, and proceed further with that baseline.

2023-05-29 07:31 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +### Iterate report from an RTCPeerConnection using forEach loop
FWIW all the examples are similar because they are all ways of iterating the map and checking against type. We should revisit this later with a few more interesting examples - looking at real statistics - that would show off things like taking averages as I did in the peer connection stats.

Don't want to do that until I have a better idea of what you can do with stats.

2023-05-29 07:32 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/keys/index.md
> +The keys in the `RTCStatsReport` are unique string `id` values, which represent the monitored statistics objects from which the statistics are derived.
FYI I wasn't sure how to do this (everywhere) refer to keys, and values as per map and then explain what they are, or refer to them as ids and statistics dictionaries. My feeling is that this approach is slightly better.

2023-05-29 07:35 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/keys/index.md
> +This example shows how to iterate through a statistics report by calling `next()` on the iterator returned by `keys()`.
Note that this example is a little contrived. Yes you can do it, but as we're only using the keys to get the values, you might as well iterate the values or entries.

As far as I can tell the ids aren't all that useful unless you're comparing a particular statistic across a timeslice.

2023-05-29 07:35 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/has/index.md
> +
Note, decision not to create an example here. I could contrive one with an ID, but seems a bit pointless.

2023-05-29 07:36 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/foreach/index.md
> +Otherwise the method is the same as {{jsxref("Map.prototype.forEach()")}}.
I put this line in here, but either it should go in all or none of the items. Hoping reviewer might have an opinion.

2023-05-29 17:09 UTC, wbamberg commented
> A question - this is in `RTCStatsReport` is shown in WebRTC API home page AND https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_Statistics_API -. Is this second doc of any use? It has no sidebar, and I will move most things into `RTCStatsReport`?

What do you think about converting this to a "Analyzing WebRTC statistics" guide page? It doesn't make sense at all as an API overview page.

2023-05-30 01:37 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +- {{domxref("RTCStatsReport.[@@iterator]()")}} {{ReadOnlyInline}}
Fixed this.

2023-05-30 02:33 UTC, hamishwillee commented on files/en-us/web/api/analyzing_webrtc_statistics/index.md
> +---
@wbamberg This is the old WebRTC Statistics API page moved to the title you suggested. I tidied up the table and there is a lot more work that can and should be done. This is "less crap" than it was. But we will need to create a more complete guide later, after having done all the dictionaries.

This PR should merge first.

2023-05-30 04:20 UTC, hamishwillee commented on files/en-us/web/api/rtcoutboundrtpstreamstats/qpsum/index.md
> +browser-compat: api.RTCStatsReport.type_outbound-rtp.qpSum
@wbamberg This isn't actually supported by any browser, so in theory we should remove it. However it contains info that would be painful to recover if anyone does end up supporting this API. I assume all we can do is add "remove qpSum" to the description and hope it gets noticed if someone decides to redocument this?

Not, this pass is just to get rid of the `RTCStats` mentions. I will properly clean up all these dictionaries after this merges.

2023-05-30 04:21 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatestats/index.md
>  ## Examples
Note, example below is completely wrong. Need to remove as part of proper tidy.

2023-05-30 05:40 UTC, hamishwillee commented
This also removes `RTCStats` dictionary and all mentions. I started to look at removing `RTCRtpStreamStats` (another interim class), but only got as far as adding top level items for that into `RTCInboundRtpStreamStats`. I think that would be a good next step, but this PR is getting quite big. Probably best to review and then look at each of the stats dictionaries separately.

2023-06-02 04:26 UTC, wbamberg requested changes
I haven't reviewed all the dictionaries in this PR but given the ones I have reviewed, I think I will have similar comments.

Overall this looks like a good approach to me.

I said somewhere that we might consider keeping substantive documentation of the RTCStats-common properties (id, type, timestamp) in RTCStatsReport, and linking to it from the dictionary pages for those properties. But maybe not worth it.

The other thing is that the details of these dictionaries seems quite out of date in relation to the spec, but I'm guessing that is out of sync for this PR.

2023-06-02 04:26 UTC, wbamberg commented on files/en-us/web/api/rtcicecandidatestats/index.md
> +## Instance properties
The set here does not match the properties in https://w3c.github.io/webrtc-stats/#icecandidate-dict*.

2023-06-02 04:26 UTC, wbamberg commented on files/en-us/web/api/rtcicecandidatestats/index.md
>  - {{domxref("RTCIceCandidateStats.transportId", "transportId")}} {{optional_inline}}
Not optional per spec (candidateType also, but I can't comment on that).

2023-06-02 04:26 UTC, wbamberg commented on files/en-us/web/api/rtcicecandidatestats/index.md
> +- {{domxref("RTCIceCandidateStats.id", "id")}}
I don't know why these look like broken links in the preview.

2023-06-02 07:10 UTC, hamishwillee commented
@wbamberg Thanks for the review. I'll give your comments a proper look at on Monday. For now:

> I said somewhere that we might consider keeping substantive documentation of the RTCStats-common properties (id, type, timestamp) in RTCStatsReport, and linking to it from the dictionary pages for those properties. But maybe not worth it.

It is certainly a pain in the neck having all the duplication. However when we're done I expect those docs need never change again for the `RTCStats` derived stuff. I'm OK with the work given how boilerplate it is. 

> The other thing is that the details of these dictionaries seems quite out of date in relation to the spec, but I'm guessing that is out of sync for this PR.

Yes. For this PR I just wanted to:
1. Flatten the hierarchy and as part of that remove `RTCStats`
2. Add in the common `RTCStats` docs.

You are absolutely right that lots of things will be out of sync with the spec. I aim to go through all the dicts individually and update in their own PRs.

2023-06-02 07:12 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatestats/index.md
> +## Instance properties
Yes. Annoying, but if I fix all these up we're looking at a humungous review. I want to do these iteratively. So. ...  just the addition of the RTCStats stuff.

2023-06-02 07:14 UTC, hamishwillee commented on files/en-us/web/api/analyzing_webrtc_statistics/index.md
> +browser-compat: api.RTCStatsReport
That is a fair statement. I wasn't sure, and was planning to look at this when all the docs were complete, and build a stats guide from that.

But the more I think about it, that might leave us in a rubbish state for some time, so deleting makes sense.

2023-06-02 07:15 UTC, hamishwillee commented on files/en-us/web/api/analyzing_webrtc_statistics/index.md
> +## Commonly used statistics
Yes. Will delete this page.

2023-06-02 07:16 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatepairstats/index.md
> +The statistics can be obtained by iterating the {{domxref("RTCStatsReport")}} returned by {{domxref("RTCPeerConnection.getStats()")}} until you find a report with the [`type`](#type) of `candidate-pa
We do

2023-06-02 07:18 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatepairstats/index.md
>    - : Provides an informative value representing the available inbound capacity of the network by reporting the total number of bits per second available for all of the candidate pair's incoming {{Gl
```suggestion
  - : Provides a value representing the available inbound capacity of the network by reporting the total number of bits per second available for all of the candidate pair's incoming {{Glossary("RTP")}} streams. This does not take into account the size of the {{Glossary("IP")}} overhead, nor any other transport layers such as {{Glossary("TCP")}} or {{Glossary("UDP")}}.
```

2023-06-02 07:21 UTC, wbamberg commented on files/en-us/web/api/rtcicecandidatestats/index.md
> +## Instance properties
Yeah, I realised as I went on that it makes sense to do this in a different PR (or multiple different PRs).

2023-06-02 07:25 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/entries/index.md
> +}
So use for ... of on the returned  `entries()` ? Sure - makes a lot of sense.

2023-06-02 07:26 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/foreach/index.md
> +Otherwise the method is the same as {{jsxref("Map.prototype.forEach()")}}.
Yes, maplike actually seems to mean "a readonly Map" in this case, as far as a I can tell. It is kind of useful to have specific pages though in order to show the compatibility.

2023-06-02 07:29 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +The statistics report is a read-only [`Map`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)-like object: an ordered dictionary, where the properties are `id` strings that uniquely identify
Yes. The id is not inferrable though, so it is only useful once you have a report you want to compare over time. I will think on this.

2023-06-02 07:29 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +All the dictionary types have an `id` property, a string that uniquely identifies the object that was inspected to produce the current dictionary, a `type` string that can be used to identify the par
Yes. And as you noted, we might expand on these here.

2023-06-02 07:30 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +### The statistic types
Good. We agree.

2023-06-05 01:33 UTC, hamishwillee commented on files/jsondata/GroupData.json
>          "/docs/Web/API/WebRTC_API/adapter.js",
Removing the Analyzing docs - we don't need it in current form.
```suggestion
        "/docs/Web/API/WebRTC_API/Using_DTMF",
        "/docs/Web/API/WebRTC_API/adapter.js",
```

2023-06-05 01:56 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/get/index.md
> +    Ids are unique strings that identify the monitored object from which the corresponding statistics are derived.
I do/should.

2023-06-05 01:57 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/get/index.md
> +    Ids are unique strings that identify the monitored object from which the corresponding statistics are derived.
```suggestion
  - : A string indicating the ID of the element to return from the `RTCStatsReport` object.
    IDs are unique strings that identify the monitored object from which the corresponding statistics are derived.
```

2023-06-05 02:06 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/has/index.md
> +  - : A string containing the id of the statistics dictionary to test for in the `RTCStatsReport` object.
I think you're right and this is a distinction worth making. I prefer the term "statistics object" over "an object whose statistics might be present ...". Both are correct, and it's a little less of a mouthful.

```suggestion
  - : A string containing the ID of a statistics object that might be present in this `RTCStatsReport`.
```

2023-06-05 02:08 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +- [`RTCStatsReport.[@@iterator]()`](/en-US/docs/Web/API/RTCStatsReport/@@iterator) {{ReadOnlyInline}}
No good reason

```suggestion
- [`RTCStatsReport.[@@iterator]()`](/en-US/docs/Web/API/RTCStatsReport/@@iterator)
```

2023-06-05 02:12 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +    });
Good idea. I did think about this and decide it was useful to show iterating the object - but we do that in the following example too, so being specific here is good.

2023-06-05 02:13 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +This example logs video-related statistics for the local {{domxref("RTCRtpReceiver")}} responsible for receiving streamed media.
```suggestion
This example logs shows how you might log video-related statistics for the local {{domxref("RTCRtpReceiver")}} responsible for receiving streamed media.
```

2023-06-05 02:13 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +  });
As above, I'd like on of these cases to show iterating all the values.

2023-06-05 02:14 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +The code follows a the same pattern as the previous example, but iterates using a `for...of`-loop on the {{domxref("RTCStatsReport.values()")}}, and filters on the `type` of `outbound-rtp`.
```suggestion
The code follows a similar pattern to the previous example, but iterates using a `for...of`-loop on the {{domxref("RTCStatsReport.values()")}}, and filters on the `type` of `outbound-rtp`.
```

2023-06-05 02:16 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatestats/index.md
>  ## Examples
Actually, as it is wrong I am going to remove it here and replace with TBD. Otherwise I might not re-notice it when I come back to it.

2023-06-05 02:23 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatestats/index.md
>  - {{domxref("RTCIceCandidateStats.transportId", "transportId")}} {{optional_inline}}
Thanks. As stated, will update these all individually and properly later. But worth fixing as you already spotted the specific error.
```suggestion
- {{domxref("RTCIceCandidateStats.transportId", "transportId")}}
```

2023-06-05 02:28 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatepairstats/index.md
> +Check the [compatibility table](#browser_compatibility) for details on which browsers support them and in which versions.
I'll leave this open, but do not plan to fix in this PR.

2023-06-05 02:37 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatestats/index.md
> +- {{domxref("RTCIceCandidateStats.id", "id")}}
I can't either. I think they are correct. They match the pattern of https://developer.mozilla.org/en-US/docs/Web/API/RTCAudioSourceStats which does work and is live.

2023-06-05 02:40 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/entries/index.md
> +{{Specifications}} <!-- https://webidl.spec.whatwg.org/#dfn-maplike -->
I did the second option, as that was what Vinyl wanted. So this will be fixed when that BCD gets reviewed.

2023-06-05 03:27 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +The **`RTCStatsReport`** interface of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides a statistics report for a {{domxref("RTCPeerConnection")}}, {{domxref("RTCRtpSender")}}, or {{domxref("
Feels repetitive, since this is in the description, but I accept the argument that it makes the interface you see immediately afterwards more digestible. I don't particularly like the way we separate Description out, for exactly this reason.

> I wish we had some definition for map-like that we could link to, even if just a glossary definition.

We can create a glossary if we can find someone to explain how map-like differs from "Map". I _suspect_ it just means that the object has exactly the same characteristics and API as Map, but is not derived from it, and is typically specialized in terms of the objects it can work with.

However there might be some nuance to this. Is there someone you think we might ask?

2023-06-05 03:56 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/entries/index.md
> +}
Or no example at all? That's what I did with @@iterator

2023-06-05 05:07 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/size/index.md
> +The **`size`** read-only property of the {{domxref("RTCStatsReport")}} interface returns the number of `id`/`statistics-object` (key/value) pairs in the current report.
I think perhaps "items" and an explanation. The items are ids + statistics objects. It is true there is a 1:1 relationship, so it doesn't matter very much, but items is more accurate. I'll modify.

2023-06-05 06:42 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatepairstats/id/index.md
> +The **`id`** property of the {{domxref("RTCIceCandidatePairStats")}} dictionary is a string that uniquely identifies the object for which this object provides statistics.
I like it. I already had such a section but it was too small. I've slightly expanded it and put in its own section.

2023-06-05 06:46 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +### Common instance properties
@wbamberg OK, so this adds a specific section in description about the instance properties, as you suggested in https://github.com/mdn/content/pull/27028/files#r1213871272

It makes clear that you probably use `type` to find your stat of interest, and can subsequently use the `id` to track change. 
This could do with an example, but it is pretty hard to test stuff. So for now I have not done one.

If I was to, I might expand the example here: https://developer.mozilla.org/en-US/docs/Web/API/RTCAudioSourceStats#examples
Showing how you calculate the audio level across a timeslice.

2023-06-05 06:48 UTC, hamishwillee commented on files/en-us/web/api/rtcicecandidatepairstats/index.md
>  ## Instance properties
Will fix these when I go through each dictionary individually

2023-06-05 07:25 UTC, hamishwillee commented
Thanks for that. I think we're ready for another round of re-review.

2023-06-05 21:52 UTC, wbamberg commented on files/en-us/web/api/rtcstatsreport/index.md
> +The **`RTCStatsReport`** interface of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides a statistics report for a {{domxref("RTCPeerConnection")}}, {{domxref("RTCRtpSender")}}, or {{domxref("
We talked about maplike and setlike today, and think it could be a Q3 project to explain them consistently, and find a place to talk about them.

For "someone we might ask", I'd say: let's make PRs to add glossary entries, and hope the reviewers know what to do :). I think we can cobble together something coherent, given https://webidl.spec.whatwg.org/#dfn-maplike.

2023-06-05 21:54 UTC, wbamberg approved these changes
👍 thank you @hamishwillee , very nice work.

2023-06-05 21:54 UTC, merged

2023-06-06 05:22 UTC, hamishwillee commented on files/en-us/web/api/rtcstatsreport/index.md
> +The **`RTCStatsReport`** interface of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides a statistics report for a {{domxref("RTCPeerConnection")}}, {{domxref("RTCRtpSender")}}, or {{domxref("
It turns out we can https://github.com/mdn/content/pull/27160

2023-06-06 05:22 UTC, hamishwillee commented
Thanks so much for the review. I appreciate it is not much fun! :-(