Update index.md
mdn/content pull request #27100
Opened 2023-06-01 12:21 UTC by adriananin

Typo in the description of the animation-name property, it read "An animation-name value is not required to be declared in the animation shorthand property. If no name exists, there is no animation to apply on any of the properties." 

instead of

 "An animation-name value is required to be declared in the animation shorthand property. If no name exists, there is no animation to apply on any of the properties."

### Description

Removed a typo in the description of the animation-name property, I removed the word "not"

### Motivation

The typo made the definition wrong and could mess up someone's understanding

### Additional details

### Related issues and pull requests

2023-06-02 01:40 UTC, estelle commented on files/en-us/web/css/animation/index.md
> +An `animation-name` value is required to be declared in the `animation` shorthand property. If no name exists, there is no animation to apply on any of the properties.
```suggestion
While an animation name must be set for an animation to be applied, all values of the `animation` shorthand are optional, and default to the initial value for each long-hand `animation` component. The initial value of `animation-name` is `none`, meaning if no `animation-name` value is declared in the `animation` shorthand property, there is no animation to apply on any of the properties.
```

2023-06-02 01:44 UTC, estelle requested changes
Thank you for your edit suggestion.

The animation name is not required. `animation: linear` is valid, but just resets all the longhand properties, other than animation-timing-function, to their initial values. If the original is confusing, it should be changed, but the edit is not pedantically accurate. I made a suggested edit. Does that make things clearer?

2023-06-02 01:44 UTC, estelle requested changes
Thank you for your edit suggestion.

The animation name is not required. `animation: linear` is valid, but just resets all the longhand properties, other than animation-timing-function, to their initial values. If the original is confusing, it should be changed, but the edit is not pedantically accurate. I made a suggested edit. Does that make things clearer?

2023-06-02 11:04 UTC, adriananin commented
> 

yes it does, thanks

2023-06-09 19:31 UTC, estelle approved these changes
Thank you. Also, congratulations on your first merged MDN content PR. Welcome to the team!

2023-06-09 19:31 UTC, merged