Adding  note for compound selector use cases
mdn/content pull request #27124
Opened 2023-06-03 04:47 UTC by 0h4crying0utloud

This is a confusing part of the combinator and it was a surprise to see how it actually worked. 

It comes up more when using SCSS transpilation since its more common to throw around the `&` to refer to the hierarchy.  
For example, the following may look like it will match when an element with class `.bar` follows another element that matches `.bar` when both are children of `.foo` but it does not. 

```css
.foo {
  .bar {
    & ~ & { ... }
  }
}
```

### Description
I added a note and example for how this combinator handles compound selectors as it seemed non-obvious and important to understand. 

### Motivation
I came to MDN to find this clarity on how compound selectors were handled by the combinator. I would like to save others some time. 

### Additional details

n/a

### Related issues and pull requests

n/a

2023-06-09 19:22 UTC, estelle commented on files/en-us/web/css/general_sibling_combinator/index.md
> +/* Will NOT match `span` as a sibling of `p` when both are decendants of `.foo` */
```suggestion
/* Will NOT match `span` as a sibling of `p` when both are descendants of `.foo` */
/* Will match  `span` descendant of `.foo` if that `.foo` is a sibling of `p` both nested in an ancestor `.foo` */
```

2023-06-09 19:24 UTC, estelle reviewed
We should say what it will match.... so made a suggestion

2023-06-10 02:21 UTC, dipikabh requested changes
Thanks for adding clarifying content and example to explain the result for compound selectors.

I've made some restructuring and rewording suggestions for simplifying the text and to follow our template.

2023-06-10 02:21 UTC, dipikabh commented on files/en-us/web/css/general_sibling_combinator/index.md
> +```
Making a few suggestions here. @estelle feel free to chime in about what you think and please also check if my edits are technically accurate.

1. We might want to update the syntax from:

```css
former_element ~ target_element { style properties }
```

to:

```css
compound_selector1 ~ compound_selector2 { style properties }
```
2. Let's keep the original example as is and move it under an H3 heading called "Using the combinator with simple selectors". Existing "CSS", "HTML", "Result" will become H4. (would be ideal if we follow the order "HTML", then "CSS", and then "Result").

3. Create another H3 under "Examples" and call it "Using the combinator with compound selectors".

4. All the content proposed in the PR is related to the example. Let's move it under "Using the combinator with compound selectors" with the changes suggested below.

5. I've suggested simplifying the proposed text. I'd recommend moving the comments out of the code snippet and use them as explanation in the text.

6. I've borrowed the first para from the spec.

```suggestion
### Using the combinator with compound selectors

Elements represented by the two compound selectors share the same parent in the document tree. The element represented by the first compound selector precedes (not necessarily immediately) the element represented by the second one.

The example below shows that the second compound selector must match the parent of the first compound selector. 

#### HTML

```html
<h1>Dream big</h1>
<span>And yet again this is a red span!</span>
<div class="foo">
  <p>Here is another paragraph.</p>
  <span>A blue span</span>
  <div class="foo">
      <span>A green span</span>
  </div>
</div>
```

#### CSS

```css
.foo p ~ .foo span {
  color: green;
}

.foo p ~ span {
  color: blue;
}
```

#### Result

{{EmbedLiveSample("Using the combinator with compound selectors", "auto", 300)}}

In the above HTML, the two siblings of `.foo p`  are `span` and `.foo span`.

When the second compound selector is `span`, it selects the `span` element that is a sibling of `p` and both are descendants of `.foo`.

When the second compound selector is `.foo span`, it selects the `span` element that's a descendant of `.foo` if that `.foo` is a sibling of `p`; essentially, both are nested in an ancestor of `.foo`.

```

2023-06-10 02:21 UTC, dipikabh commented on files/en-us/web/css/general_sibling_combinator/index.md
> +}
this can be removed and moved under a new heading as per the above comment

2023-06-10 02:21 UTC, dipikabh commented on files/en-us/web/css/general_sibling_combinator/index.md
> +</div>
this can be removed and moved under a new heading as per the above comment

2023-06-16 20:42 UTC, dipikabh commented
Hello @0h4crying0utloud, let me know if you have any comments or questions on the suggested changes. Thanks.

2023-09-13 14:50 UTC, dipikabh commented
Closing this pull request due to lack of activity. I'll create a new one, as the original proposal to clarify how compound selectors work, along with the recommended changes, is relevant for inclusion in our docs.

2023-09-13 14:51 UTC, dipikabh commented
Closing this pull request due to lack of activity. I'll create a new one, as the original proposal to clarify how compound selectors work, along with the recommended changes, is relevant for inclusion in our docs.

2023-09-13 14:51 UTC, closed without merging