Adding information about the decoding attribute
mdn/content pull request #27166
Opened 2023-06-06 14:35 UTC by chrisdavidmills

### Description

I noticed that the information on the HTML/SVG `decoding` attribute was somewhat lacking. This PR adds a bit more information and description, to make it clearer what it actually does.

This set of docs could ideally also do with a clear example or two to demonstrate the effect of the different values. I'm currently trying to research and come up with something that demonstrates it in a simple manner.

### Motivation

### Additional details

### Related issues and pull requests

2023-06-14 18:28 UTC, tunetheweb commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +Instead, you can use the {{domxref("HTMLImageElement.decode()")}} method to solve this problem. It provides a way to asynchronously decode an image, pausing inserting it into the DOM until it is full
```suggestion
A better way is to use the {{domxref("HTMLImageElement.decode()")}} method to solve this problem. It provides a way to asynchronously decode an image, delaying inserting it into the DOM until it is fully downloaded and decoded, thereby avoiding the empty image problem described above. This is particularly useful if you're dynamically swapping an existing image for a new one. This also prevents other, unrelated, paints outside of this code from being held up while the image is decoding.
```

Then add this code example (again, can't suggest this so you'll need to add manually):

>```js
>async function loadImage(url, elem) {
>  return new Promise((resolve, reject) => {
>    elem.onload = () => resolve(elem);
>    elem.onerror = reject;
>    elem.src = url;
>  });
>}
>
>const img = new Image();
>await loadImage("img/logo.png", img);
>await img.decode();
>document.body.appendChild(img);
>const p = document.createElement('p');
>p.textContent = "Image is fully loaded!"
>document.body.appendChild(p);
>```
 
For the `async` use case however, the attribute may be more useful.

2023-06-14 18:28 UTC, tunetheweb commented on files/en-us/web/api/htmlimageelement/index.md
> +  - : Provides a hint to the browser as to whether it should perform image decoding synchronously or asynchronously.
Personally I think the old text is more useful:

```suggestion
  - : An optional string representing a hint given to the browser on how it should decode the image. If this value is provided, it must be one of the possible permitted values: `sync` to decode the image synchronously, `async` to decode it asynchronously, or `auto` to indicate no preference (which is the default). Read the {{domxref("HTMLImageElement.decoding", "decoding")}} page for details on the implications of this property's values.
```

2023-06-14 18:28 UTC, tunetheweb commented on files/en-us/web/api/svgimageelement/decoding/index.md
> +The **`decoding`** property of the {{domxref("SVGImageElement")}} interface provides a hint to the browser as to whether it should perform image decoding synchronously or asynchronously.
Same comments for this doc as above.

2023-06-14 18:28 UTC, tunetheweb commented on files/en-us/web/html/element/img/index.md
> +    In reality, `decoding` is not very useful. The decode time will be so small for most images — and it's rare for the image paint to be ready in the exact same frame and therefore be waiting for th
It's probably incorrect to say decoding times are small. That may not be the case on very slow devices. Let's concentrate instead that it happens at a different presentation time.

```suggestion
    In reality, using `decoding` on static `<img>` elements is often not very useful. For `<img>` elements, the image will likely be initially rendered as an empty image while it is fetched (from the network or from the cache), and then handled independently anyway. Therefore it is often almost impossible to notice differences in these settings. It is perhaps more useful `<img>` elements inserted via the JavaScript API.
```

Can you link JavaScript API text?

2023-06-14 18:28 UTC, tunetheweb commented on files/en-us/web/svg/attribute/decoding/index.md
> +## Example
If accepting the above changes then review this too.

2023-06-19 08:46 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +In the below example, you'll likely get an empty image shown on the page as the image is downloaded. Setting `decoding` won't prevent that.
Implemented basically as-is, but with a few tweaks. I changed the example to use `async` instead of `sync`, as the added sentence seems to imply that's what it should be.

2023-06-19 08:54 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +In the below example, you'll likely get an empty image shown on the page as the image is downloaded. Setting `decoding` won't prevent that.
Ah, on second thoughts, I've changed the first code example back to using `sync`, as your examples basically builds on top of the first one, then I've moved the "using `decoding=async` may avoid holding up other content from displaying if the decoding time is long" note to below everything else, as it makes sense to me to handle the sync case first, then talk about the async case.

2023-06-19 08:55 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
Added

2023-06-19 09:04 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +Instead, you can use the {{domxref("HTMLImageElement.decode()")}} method to solve this problem. It provides a way to asynchronously decode an image, pausing inserting it into the DOM until it is full
It seemed weird putting a `decode()` example on the `decoding` page, so I've added it to the `decode()` page instead. We do link to it so the reader can find it.

2023-06-19 10:41 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/decoding/index.md
> +## Example
Equivalent changes made on the `SVG`/`SVGImageElement` pages too.

2023-06-19 13:50 UTC, tunetheweb reviewed
Two more suggestions, based on my latest testing that there is a measurable (even if difficult to directly observe with the human eye) blocking with `sync` on all three browsers.

Will also let you know when my post on this is published in case you want to reference it (likely later this week).

2023-06-19 13:50 UTC, tunetheweb commented on files/en-us/web/html/element/img/index.md
> +    In reality, using `decoding` on static `<img>` elements is often not very useful. It is likely that they'll be initially rendered as empty images while the image files are fetched (either from th
```suggestion
  - : This attribute provides a hint to the browser as to whether it should perform image decoding along with rendering the other DOM content in a single presentation step that looks more "correct" (`sync`), or render and present the other DOM content first and then decode the image and present it later (`async`). In practice, `async` means that the next paint does not wait for the image to decode.

    It is often difficult to perceive differences in using `decoding` on static `<img>` elements. It is likely that they'll be initially rendered as empty images while the image files are fetched (either from the network or from the cache) and then handled independently anyway, so the "syncing" of content updates is less apparent. However, the blocking of rendering while decoding happens, while often quite small, can be measured—even if it is difficult to observe with the human eye. Using different `decoding` types can result in more noticeable differences when dynamically inserting `<img>` elements into the DOM via JavaScript — see {{domxref("HTMLImageElement.decoding")}}.
```

2023-06-19 13:50 UTC, tunetheweb commented on files/en-us/web/svg/attribute/decoding/index.md
> +In reality, using `decoding` on static `<image>` elements is often not very useful. It is likely that they'll be initially rendered as empty images while the image files are fetched (either from the
```suggestion
The `decoding` attribute, valid on {{SVGElement("image")}} elements, provides a hint to the browser as to whether it should perform image decoding synchronously or asynchronously.

This attribute provides a hint to the browser as to whether it should perform image decoding along with rendering other content in a single presentation step that looks more "correct" (`sync`), or render and present the other content first and then decode the image and present it later (`async`). In practice, `async` means that the next paint does not wait for the image to decode.

It is often difficult to perceive differences in using `decoding` on static `<img>` elements. It is likely that they'll be initially rendered as empty images while the image files are fetched (either from the network or from the cache) and then handled independently anyway, so the "syncing" of content updates is less apparent. However, the blocking of rendering while decoding happens, while often quite small, can be measured—even if it is difficult to observe with the human eye. Using different `decoding` types can result in more noticeable differences when dynamically inserting `<image>` elements into the DOM via JavaScript — see {{domxref("SVGImageElement.decoding")}}.
```

2023-06-20 07:58 UTC, chrisdavidmills commented
Thanks @tunetheweb! I've accepted your suggestions and then made a few tweaks. I think we should definitely wait for you to publish your post, and then link to it from these articles.

In particular, where you say 

> However, the blocking of rendering while decoding happens, while often quite small, _can_ be measured — even if it is difficult to observe with the human eye.

Would be good to follow up with that link, so readers can find a bunch more context about the measuring.

2023-07-04 21:35 UTC, tunetheweb reviewed
Think these are the last changes I'd suggest from my side.

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Chromium defaults to `"sync
```suggestion
  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Firefox defaults to `"async"`, Chromium defaults to `"sync"`  as does Safari except in a small number of circumstances.
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +For images that are downloaded before being inserted into the DOM, using the {{domxref("HTMLImageElement.decode()")}} method is a better way to assure atomic presentation without holding up other con
Let's tone this down slightly:

```suggestion
The `decoding` property provides a hint to the browser as to whether it should perform image decoding along with other tasks in a single step (`"sync"`), or allow other content to be rendered before this completes. (`"async"`). In reality, the differences between the two `decoding` values for APIs is often difficult to perceive and where there are differences, there is often a better way.

For images that are inserted into the DOM in the viewport, `"async"` can result in flashes of unstyled content, while `"sync"` can result in small amounts of jank. Using the {{domxref("HTMLImageElement.decode()")}} method is usualy a better way to assure atomic presentation without holding up other content.

For images inserted into the DOM outside of the viewport, the image will often be decoded off the main thread in modern browsers before being scrolled into view and there will be no noticeable difference using either value.
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +- The {{htmlelement("img")}} element `decoding` attribute.
```suggestion
- The {{domxref("HTMLImageElement.decode()")}} method
- The {{htmlelement("img")}} element `decoding` attribute.
- [What does the image decoding attribute actually do?](https://www.tunetheweb.com/blog/what-does-the-image-decoding-attribute-actually-do/) on tunetheweb.com (2023)
- 
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/svgimageelement/decode/index.md
> +This is particularly useful if you're dynamically swapping an existing image for a new one, and also prevents unrelated paints outside of this code from being held up while the image is decoding.
Can you add a reference to the "See also" section (can't suggest in this PR as not edited code):

```md
- [What does the image decoding attribute actually do?](https://www.tunetheweb.com/blog/what-does-the-image-decoding-attribute-actually-do/) on tunetheweb.com (2023)
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/svgimageelement/decoding/index.md
> +  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Chromium defaults to `"sync
```suggestion
  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Firefox defaults to `"async"`, Chromium defaults to `"sync"`  as does Safari except in a small number of circumstances.
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/svgimageelement/decoding/index.md
> +For images that are downloaded before being inserted into the DOM, using the {{domxref("HTMLImageElement.decode()")}} method is a better way to assure atomic presentation without holding up other con
```suggestion
The `decoding` property provides a hint to the browser as to whether it should perform image decoding along with other tasks in a single step (`"sync"`), or allow other content to be rendered before this completes. (`"async"`). In reality, the differences between the two `decoding` values for APIs is often difficult to perceive and where there are differences, there is often a better way.

For images that are inserted into the DOM in the viewport, `"async"` can result in flashes of unstyled content, while `"sync"` can result in small amounts of jank. Using the {{domxref("HTMLImageElement.decode()")}} method is usualy a better way to assure atomic presentation without holding up other content.

For images inserted into the DOM outside of the viewport, the image will often be decoded off the main thread in modern browsers before being scrolled into view and there will be no noticeable difference using either value.
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/api/svgimageelement/index.md
> +  - : Represents a hint given to the browser on how it should decode the image. If this value is provided, it must be one of the possible permitted values: `sync` to decode the image synchronously, `
```suggestion
  - : Represents a hint given to the browser on how it should decode the image. If this value is provided, it must be one of the possible permitted values: `"sync"` to decode the image synchronously, `"async"` to decode it asynchronously, or `"auto"` to indicate no preference (which is the default).
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/html/element/img/index.md
> +    It is often difficult to perceive any noticeable effect when using `decoding` on static `<img>` elements. They'll likely be initially rendered as empty images while the image files are fetched (e
Can you add a reference to the "See also" section (can't suggest in this PR as not edited code):

```md
- [What does the image decoding attribute actually do?](https://www.tunetheweb.com/blog/what-does-the-image-decoding-attribute-actually-do/) on tunetheweb.com (2023)
```

2023-07-04 21:35 UTC, tunetheweb commented on files/en-us/web/svg/attribute/decoding/index.md
> +- [SVGImageElement: decoding property](/en-US/docs/Web/API/SVGImageElement/decoding)
```suggestion
- [SVGImageElement: decoding property](/en-US/docs/Web/API/SVGImageElement/decoding)
- [What does the image decoding attribute actually do?](https://www.tunetheweb.com/blog/what-does-the-image-decoding-attribute-actually-do/) on tunetheweb.com (2023)
```
```

2023-07-05 10:50 UTC, chrisdavidmills commented on files/en-us/web/html/element/img/index.md
> +    It is often difficult to perceive any noticeable effect when using `decoding` on static `<img>` elements. They'll likely be initially rendered as empty images while the image files are fetched (e
I think in "See also" works fine in the SVG `decoding` attribute page, but in the case of the HTML `<img>` element page, most of it is not about `decoding`. Therefore in that case I've put the link to your article in the `decoding` text.

2023-07-05 11:03 UTC, chrisdavidmills commented on files/en-us/web/api/svgimageelement/decoding/index.md
> +For images that are downloaded before being inserted into the DOM, using the {{domxref("HTMLImageElement.decode()")}} method is a better way to assure atomic presentation without holding up other con
I have used your new text, but tweaked it a bit.

2023-07-05 11:08 UTC, chrisdavidmills commented on files/en-us/web/api/svgimageelement/decoding/index.md
> +  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Chromium defaults to `"sync
I've basically used your text here, but I've split them into a bulleted list so they are easier to follow.

2023-07-05 11:15 UTC, chrisdavidmills commented on files/en-us/web/api/svgimageelement/decode/index.md
> +This is particularly useful if you're dynamically swapping an existing image for a new one, and also prevents unrelated paints outside of this code from being held up while the image is decoding.
I've just put the link to your article in the "See also" list in this case. I think it works fine there.

2023-07-05 11:17 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +For images that are downloaded before being inserted into the DOM, using the {{domxref("HTMLImageElement.decode()")}} method is a better way to assure atomic presentation without holding up other con
I've used your version, with a few tweaks

2023-07-05 11:18 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decoding/index.md
> +  - : No preference for the decoding mode; the browser decides what is best for the user. This is the default value, but different browsers have different default values — Chromium defaults to `"sync
Updated, but turned into bullets to make it easier to read.

2023-07-05 11:32 UTC, chrisdavidmills commented on files/en-us/web/api/htmlimageelement/decode/index.md
>  would add the image to the DOM in a {{domxref("Window/load_event", "load")}} event handler, such as by using
I've done that, but I've also removed one of the links because the two links to event handler information went to the same place and it felt repetitive, and also move it to below the code example in a note. The way it was situated sounded like it was referring to the code below it, which isn't the case.

2023-07-05 11:43 UTC, tunetheweb commented
LGTM! Thanks for updating, and for working through all the feedback. It bugged me for years that this attribute was so little understood. Hopefully between these updates and my recent blog post that you've linked here this will be better understood now.

2023-07-05 12:34 UTC, chrisdavidmills commented
> LGTM! Thanks for updating, and for working through all the feedback. It bugged me for years that this attribute was so little understood. Hopefully between these updates and my recent blog post that you've linked here this will be better understood now.

Nice one @tunetheweb, I've enjoyed the collaboration on this one. It feels really good whenever you manage to fill in the blanks for a misunderstood web feature.

2023-08-08 17:22 UTC, Rumyra commented on files/en-us/web/api/svgimageelement/decode/index.md
> +returning a {{jsxref('Promise')}} that resolves image is decoded and it is safe to append
'with a decoded image'? Just not sure this reads entirely correctly

2023-08-08 17:27 UTC, Rumyra requested changes
Only one sentence I'm unsure of

Also are we linking here https://developer.mozilla.org/en-US/docs/Glossary/Jank where neccessary?

2023-08-09 15:16 UTC, chrisdavidmills commented on files/en-us/web/api/svgimageelement/decode/index.md
> +returning a {{jsxref('Promise')}} that resolves image is decoded and it is safe to append
I've updated it with "that resolves once the image is decoded", and updated the return value section to make it clearer what the return value is (it actually fulfills with `undefined` according to the spec, but it is to be taken as a signal that decoding is complete.)

2023-08-09 15:23 UTC, chrisdavidmills commented
> Only one sentence I'm unsure of
> 
> Also are we linking here https://developer.mozilla.org/en-US/docs/Glossary/Jank where necessary?

Thanks @Rumyra! Weird sentence fixed, and jank links added.

2023-08-10 09:35 UTC, Rumyra approved these changes

2023-08-10 09:35 UTC, merged

2023-08-10 09:35 UTC, Rumyra commented
Awesome - thanks @chrisdavidmills