webext permissions: activeTab and menu for a subframe
mdn/content pull request #27219
Opened 2023-06-08 11:47 UTC by maxnikulin

### Description

Clarify `aciveTab` permission effect on `executeScript` when context menu is opened for a subframe.

### Motivation

Developers may expect that acquiring the `activeTab` permission though add-on's context menu item gives access to the frame where the menu is opened, but actually content script may be injected into the top tab page.

My confusion led to creation of the #27098 wrong pull request.

2023-06-09 10:09 UTC, maxnikulin commented
> Flaws (1)
>
>    macros:
>        /en-US/docs/Web/API/URL/createObjectURL redirects to /en-US/docs/Web/API/URL/createObjectURL_static

https://github.com/mdn/content/blob/d3b92dff059a74d95a6b1d64908b6992d57b21fd/files/en-us/web/api/blob/index.md?plain=1#L155 contains `{{DOMxRef("URL.createObjectURL")}}` as well. Should `{{DOMxRef("URL.createObjectURL()")}}` be used instead? Is the linter unhappy that I put "Blob" as link description?

> External URLs (1)
>
>    https://bugzil.la/1411641 (1 time) (Note! This may be a new URL eyes)

This page already contains a bugzil.la link, so I am surprised by this warning.

Perhaps added fragment is too heavy loaded with links. Should I remove some of them?

2023-06-15 02:32 UTC, rebloor commented
@Rob--W as this content appears to relate to a comment to left (https://bugzilla.mozilla.org/show_bug.cgi?id=1411641#c41) would you have a moment to check the technical accuracy before I look at the language?

2023-06-15 02:40 UTC, rebloor commented
@maxnikulin regarding the linter feedback. In both cases these are informational. The first one tells you that `{{DOMxRef("URL.createObjectURL")}}` passes through redirect to find the correct page. And the second is just advice that you are adding an external link.

2023-06-15 23:42 UTC, Rob--W commented
> Developers may expect that acquiring the `activeTab` permission though add-on's context menu item gives access to the frame where the menu is opened, but actually content script may be injected into the top tab page.

This is a reasonable expectation. I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1838753 (and linked it to the other Bugzilla report you've filed before).

As for this documentation PR. There are several technically distinct parts that are grouped together in one large paragraph. I'll comment on them separately:

> You may face limitations of the `activeTab` permission trying to inject [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frames")}}.

This piece of information is useful. But I would put the message near the existing bullet point, at https://github.com/mdn/content/blob/839d682cac996a347ea2422edc41ea73dfa73c92/files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md?plain=1#L155

(side note: this does not mention the scripting API. For details, see "At runtime, into specific tabs" at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#loading_content_scripts )

> When the {{webextAPIref("menus/onClicked", "menus.onClicked")}} event is fired in response to a [context menu](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items) opened inside a frame, the extension receives access to the **top-level frame** of the tab. As a result, the frame specified by the `frameId` field of {{webextAPIref("menus/OnClickData", "menus.OnClickData")}} may be inaccessible for injection of scripts and styles by {{webextAPIref("scripting/executeScript", "scripting.executeScript")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS")}} or by their {{webextAPIref("tabs", "tabs")}} counterparts.

This is specific to the activeTab permission & context menus API. This does not need a separate mention if we document that `activeTab` only grants access to the tab and same-origin frames.

> Running script in a [cross-origin](/en-US/docs/Web/Security/Same-origin_policy#cross-origin_network_access) frame may require [host permissions](#host_permissions). Support of special cases like [`data:` URI](/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) or {{DOMxRef("URL.createObjectURL", "Blob")}} frames in respect to content scripts is not uniform across browsers, see the Firefox [bug #1411641 comment 41](https://bugzil.la/1411641#c41) for some details.

This has nothing to do with activeTab. This would fit better in the content scripts documentation, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#loading_content_scripts

2023-06-19 11:08 UTC, maxnikulin commented
> > Running script in a [cross-origin](/en-US/docs/Web/Security/Same-origin_policy#cross-origin_network_access) frame may require [host permissions](#host_permissions). Support of special cases like [`data:` URI](/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) or {{DOMxRef("URL.createObjectURL", "Blob")}} frames in respect to content scripts is not uniform across browsers, see the Firefox [bug #1411641 comment 41](https://bugzil.la/1411641#c41) for some details.
> 
> This has nothing to do with activeTab. This would fit better in the content scripts documentation, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#loading_content_scripts

@Rob--W, I agree with this idea. My plan:

1. Create new section "Permissions, restrictions, and limitations"
   https://github.com/mdn/content/blob/839d682cac996a347ea2422edc41ea73dfa73c92/files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md?plain=1#L43
    making "Restricted domains" its subsection.
2. Move notes (converting them to regular paragraphs) related to permission to first subsection of the new section
   https://github.com/mdn/content/blob/839d682cac996a347ea2422edc41ea73dfa73c92/files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md?plain=1#L17
3. Add a link to "activeTab", mention the `scripting` permission.
4. Add a subsection for frames having special URIs based on the sentence cited above. I can add more links to browser bugs, but I am unsure if it is necessary.

> > You may face limitations of the `activeTab` permission trying to inject [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frames")}}.
> 
> This piece of information is useful. But I would put the message near the existing bullet point, at
> 
> https://github.com/mdn/content/blob/839d682cac996a347ea2422edc41ea73dfa73c92/files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md?plain=1#L155

I would not insist, however originally I decided to keep the bullet list concise and to provide details in discussion paragraphs below.

> (side note: this does not mention the scripting API. For details, see "At runtime, into specific tabs" at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#loading_content_scripts )

The "Host permission" section has the same issue, but expecting possible objections related to context menu case I decided to keep changes minimal.

> > When the {{webextAPIref("menus/onClicked", "menus.onClicked")}} event is fired in response to a [context menu](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items) opened inside a frame, the extension receives access to the **top-level frame** of the tab. As a result, the frame specified by the `frameId` field of {{webextAPIref("menus/OnClickData", "menus.OnClickData")}} may be inaccessible for injection of scripts and styles by {{webextAPIref("scripting/executeScript", "scripting.executeScript")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS")}} or by their {{webextAPIref("tabs", "tabs")}} counterparts.
> 
> This is specific to the activeTab permission & context menus API. This does not need a separate mention if we document that `activeTab` only grants access to the tab and same-origin frames.

My idea is to stress on the case of cross-origin context menu either here in permissions or in the `menus.onClicked` docs. An alternative (links are omitted):

The `acitveTab` permission enables scripting access to the top level tab's frame and same origin frames. Running scripts or adding styles to cross-origin frames may require additional host permissions. It includes a case when a context menu is opened inside a frame. Even the frame specified as `frameId` in the argument of a `menus.onClicked` event listener may be inaccessible. The intention is to avoid escalation of privileges by creating a frame with arbitrary web page and running some action in its context. Limitations imposed by browsers are not uniform, for example Firefox blocks access to frames created by page scripts. On the other hand only Firefox mv2 add-ons are allowed to run context scripts in static cross-origin frames. Of course, restrictions and limitations related to particular sites and URI schemes applies as well.

Should I add "Content scripts" edits to this pull request or it is better to create a dedicated one?

2023-06-21 06:51 UTC, Rob--W commented
Feel free to update this PR with what you have in mind. Your objective is not tied to one article, and having one PR would make it easier to get the message to the right audience when needed.

Try to be clear and concise, so that the main message doesn't get lost in the sea of words.

2023-06-21 17:42 UTC, rebloor reviewed
Some suggestions for your consideration

2023-06-21 17:42 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +  -  using {{webextAPIref("scripting/executeScript", "scripting.executeScript()")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS()")}} when combined with the `scripting` permission
```suggestion
  - using {{webextAPIref("scripting/executeScript", "scripting.executeScript()")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS()")}} when combined with the `scripting` permission (in Chrome Manifest V3 only.)
```

2023-06-21 17:42 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +  -  using {{webextAPIref("tabs/executeScript", "tabs.executeScript()")}} and {{webextAPIref("tabs/insertCSS", "tabs.insertCss()")}} (mv2 only)
```suggestion
  - using {{webextAPIref("tabs/executeScript", "tabs.executeScript()")}} and {{webextAPIref("tabs/insertCSS", "tabs.insertCss()")}}. (Manifest V2 only)
```

2023-06-21 17:42 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +  -  using {{webextAPIref("scripting/executeScript", "scripting.executeScript()")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS()")}} when combined with the `scripting` permission
```suggestion
  - using {{webextAPIref("scripting/executeScript", "scripting.executeScript()")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS()")}} when combined with the `scripting` permission (in Chrome Manifest V3 only.)
```

2023-06-21 17:42 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +  -  using {{webextAPIref("tabs/executeScript", "tabs.executeScript()")}} and {{webextAPIref("tabs/insertCSS", "tabs.insertCss()")}} (mv2 only)
```suggestion
  - using {{webextAPIref("tabs/executeScript", "tabs.executeScript()")}} and {{webextAPIref("tabs/insertCSS", "tabs.insertCss()")}}. (Manifest V2 only)
```

2023-06-21 17:42 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +You may face limitations of the `activeTab` permission trying to inject [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frame
```suggestion
You may encounter limitations with the `activeTab` permission when injecting [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frames")}}. When the {{webextAPIref("menus/onClicked", "menus.onClicked")}} event is fired in response to a [context menu](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items) opened inside a frame, the extension receives access to the **top-level frame** of the tab. As a result, the frame specified by the `frameId` field of {{webextAPIref("menus/OnClickData", "menus.OnClickData")}} may be inaccessible for injection of scripts and styles by {{webextAPIref("scripting/executeScript", "scripting.executeScript")}} and {{webextAPIref("scripting/insertCSS", "scripting.insertCSS")}} or by their {{webextAPIref("tabs", "tabs")}} counterparts. Running script in a [cross-origin](/en-US/docs/Web/Security/Same-origin_policy#cross-origin_network_access) frame may require [host permissions](#host_permissions). Support of special cases like [`data:` URI](/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) or {{DOMxRef("URL.createObjectURL", "Blob")}} frames in respect to content scripts is not uniform across browsers, see the Firefox [bug #1411641 comment 41](https://bugzil.la/1411641#c41) for some details.
```

2023-06-22 12:07 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +  -  using {{webextAPIref("tabs/executeScript", "tabs.executeScript()")}} and {{webextAPIref("tabs/insertCSS", "tabs.insertCss()")}} (mv2 only)
Is it OK to insert full stop if the middle of an item without capitalizing first letter and without adding another dot at the end? I am unsure concerning proper punctuation. Should not all list items be rewritten using complete sentences?

2023-06-22 16:15 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +You may face limitations of the `activeTab` permission trying to inject [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frame
I am sorry, I did not finish edits yesterday. The final part has been moved to the article on content script. I am still in doubts if the remaining part should be moved above into the list describing the privileges. For while I have tried to make it a bit shorter. The updated variant is based on my https://github.com/mdn/content/pull/27219#issuecomment-1596986757

2023-06-22 16:17 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +You may face limitations of the `activeTab` permission trying to inject [content scripts](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into web pages with {{HTMLElement("iframe", "frame
I do not mind to revert last change and to take your variant

2023-06-29 16:10 UTC, maxnikulin commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +The `acitveTab` permission enables scripting access to the top level tab's page and same origin frames. Running scripts or modifying styles inside [cross-origin](/en-US/docs/Web/Security/Same-origin_
@Rob--W, I may try to move this paragraph to make it a part of the list item above. It would be easy to revert such change.

2023-08-09 20:37 UTC, Rob--W requested changes

2023-08-09 20:37 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md
> -> **Note:** Content scripts are only executed if the extension is granted [host permissions](/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) for the domain.
With this removed, it may still be worth keeping a reference to the new section, to emphasize that scripts are only executed if access is granted.

2023-10-30 02:06 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md
@Rob--W did you mean something like this:
```suggestion
However, they can only do this when [granted host permission](#permissions).
```

2023-12-11 13:15 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md
This looks good.

2023-12-11 16:01 UTC, Rob--W approved these changes

2023-12-11 16:01 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/index.md
> +Just like the scripts loaded by normal web pages, content scripts can read and modify the content of their pages using the standard DOM APIs. However, they can only do this when [granted host permiss
"when granted host permission" - is that proper English? At my first review pass I read "permissions" (plural), but I just noticed that the text label itself is singular. How about this:

```suggestion
Just like the scripts loaded by normal web pages, content scripts can read and modify the content of their pages using the standard DOM APIs. However, they can only do this when [host permissions to the web page's origin have been granted](#permissions).
```

2023-12-11 17:22 UTC, merged

2023-12-11 17:23 UTC, rebloor commented
Thanks for your help @maxnikulin