docs(css): Add docs for audio pseudo-classes
mdn/content pull request #27237
Opened 2023-06-09 15:11 UTC by bsmth

This PR adds pages for the following pseudo-classes:

- `:buffering`
- `:muted`
- `:seeking`
- `:stalled`
- `:volume-locked`

Also updates:

- `:paused`
- `:playing`

2023-06-09 16:43 UTC, estelle reviewed
lots of feedback....

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_paused/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_playing/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_seeking/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_stalled/index.md
> +- {{cssxref(":volume-locked")}}
```suggestion
- {{cssxref(":volume-locked")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_volume-locked/index.md
> +- {{cssxref(":stalled")}}
```suggestion
- {{cssxref(":stalled")}}
- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +An element is considered as buffering when that element cannot continue playing because it is trying to load media data but does not yet have enough data to begin playback.
```suggestion
An element is considered as buffering when that element cannot continue playing because it is trying to load media data but does not yet have enough data to begin or continue playback.
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +}
```suggestion
:buffering {
  outline: 5px solid red;
}

audio:buffering {
  outline: 5px solid blue;
}
```

You never want to change box model properties, in this case `border-width` on states, as the page/content will jump when the state changes to longer be buffering. This is true for all the examples - as all of these are temporary states.

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +Muted is different from {{cssxref(":volume-locked")}} in that the page author can specify whether a media element can be muted or un-muted.
Link the `muted or un-muted` to the API that would be used to lock audio

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +:muted {
make the example useful, maybe `:muted + .sound {fill: red;}`. Audio isn't necessarily visible. Or maybe change to video

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_playing/index.md
> +An element is considered to be playing if it is currently playing the media resource, or if it has temporarily stopped for reasons other than user intent (such as waiting for data to be loaded).
```suggestion
An element is considered `:playing` if it is currently playing the media resource or has temporarily stopped for reasons other than user intent (such as waiting for data to be loaded, including when the media is buffering).
```

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +An element is considered as buffering when that element cannot continue playing because it is trying to load media data but does not yet have enough data to begin playback.
how is buffering different from stalled? I would add a sentence and link to that page as people will not know about the other.

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_paused/index.md
> +A resource is paused if the user explicitly paused it, or if it is in a non-activated or other non-playing state, like "loaded, hasn't been activated yet".
if it is paused because of buffering or being stalled, is it paused? address that.

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_stalled/index.md
> +> If `:stalled` matches an element, `:playing` will also match that element.
add v. buffering

2023-06-09 16:43 UTC, estelle commented on files/en-us/web/css/_colon_volume-locked/index.md
> +The **`:volume-locked`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector represents an element that is capable of making sound, such as {{htmlelement("audio")}}
link to a resource that explains volume locking.

2023-06-09 16:44 UTC, estelle commented
The pseudo class page and selectors page also need updating, but i assume that is a different PR

2023-06-12 11:02 UTC, bsmth commented on files/en-us/web/css/_colon_volume-locked/index.md
> +The **`:volume-locked`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) selector represents an element that is capable of making sound, such as {{htmlelement("audio")}}
This is browser / OS specific. Added some hints in https://github.com/mdn/content/pull/27237/commits/3a9ec8ace6665e3eaa5a502d0288f1faf534c034

2023-06-12 11:02 UTC, bsmth commented on files/en-us/web/css/_colon_playing/index.md
> +An element is considered to be playing if it is currently playing the media resource, or if it has temporarily stopped for reasons other than user intent (such as waiting for data to be loaded).
added some context in https://github.com/mdn/content/pull/27237/commits/3a9ec8ace6665e3eaa5a502d0288f1faf534c034

2023-06-12 11:03 UTC, bsmth commented on files/en-us/web/css/_colon_muted/index.md
> +:muted {
Changed to `video` in https://github.com/mdn/content/pull/27237/commits/3a9ec8ace6665e3eaa5a502d0288f1faf534c034

2023-06-12 11:03 UTC, bsmth commented on files/en-us/web/css/_colon_muted/index.md
> +Muted is different from {{cssxref(":volume-locked")}} in that the page author can specify whether a media element can be muted or un-muted.
Added in https://github.com/mdn/content/pull/27237/commits/3a9ec8ace6665e3eaa5a502d0288f1faf534c034

2023-06-29 19:19 UTC, estelle requested changes
most of the edits are really minor. Adding a comma before `or` when there are 3 or more in a list, adding a comma after e.g., and the lowercase in URLs (my bad).

I changed the visual examples to video from audio, as audio may not be visible, but video always is. If you want to use audio, i suggest using `audio[controls]`, because that makes the audio visible.

the only "change" is take a look at where i say it says the same thing 3 times. Maybe it's ok as is, but maybe it can be reduced.

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +User agents may set media `muted` value according to use preferences (e.g. remembering the last set value across sessions, on a per-site basis or otherwise).
```suggestion
User agents may set media `muted` value according to use preferences (e.g., remembering the last set value across sessions, on a per-site basis, or otherwise).
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +An element that is `:volume-locked` cannot be muted, un-muted or have its volume changed via JavaScript because of an operating system or user agent preference.
```suggestion
An element that is `:volume-locked` cannot be muted, un-muted, or have its volume changed via JavaScript because of an operating system or user agent preference.
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_playing/index.md
> +> An element that matches `:buffering` or `:stalled` will also match `:playing`.
saying the same thing 3 times.

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_volume-locked/index.md
> +User agents may set media [`muted`](/en-US/docs/Web/API/HTMLMediaElement/muted) or [`volume`](/en-US/docs/Web/API/HTMLMediaElement/volume) values according to user preferences (e.g. remembering the l
```suggestion
User agents may set media [`muted`](/en-US/docs/Web/API/HTMLMediaElement/muted) or [`volume`](/en-US/docs/Web/API/HTMLMediaElement/volume) values according to user preferences (e.g., remembering the last set value across sessions, on a per-site basis, or otherwise).
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_volume-locked/index.md
> +An element that is `:volume-locked` cannot be muted, un-muted or have its volume changed via JavaScript because of an operating system or user agent preference.
This isn't fully clear to me. Is this suggested edit accurate? 

```suggestion
An element that is `:volume-locked` cannot be muted, un-muted, or have its volume changed via JavaScript. The locked status is an operating system or user agent preference.
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_muted/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_paused/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_playing/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_seeking/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_stalled/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_volume-locked/index.md
> +- [CSS selectors](/en-US/docs/Web/CSS/CSS_Selectors)
```suggestion
- [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors)
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_buffering/index.md
> +audio:buffering {
```suggestion
video:buffering {
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_seeking/index.md
> +audio:seeking {
``` suggestion
video:seeking {
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_seeking/index.md
> +  border: 5px solid red;
```suggestion
  outline: 5px solid red;
```

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_seeking/index.md
> +  border: 5px solid blue;
```suggestion
  outline: 5px solid blue;
```
You don't want to add a box model change to a state change as it will recalculate and repaint, a jank and general perf issue

2023-06-29 19:19 UTC, estelle commented on files/en-us/web/css/_colon_stalled/index.md
> +  border: 5px solid red;
```suggestion
  outline: 5px solid red;
```

2023-06-30 13:41 UTC, bsmth commented on files/en-us/web/css/_colon_volume-locked/index.md
> +An element that is `:volume-locked` cannot be muted, un-muted or have its volume changed via JavaScript because of an operating system or user agent preference.
It's hard to get documentation about this to clearly state that, but indeed, that's what happens as far as I can tell. A user sets through their OS / browser settings preferences like "mute auto-playing video" and the webpage cannot override this.

2023-06-30 13:43 UTC, bsmth commented on files/en-us/web/css/_colon_playing/index.md
> +> An element that matches `:buffering` or `:stalled` will also match `:playing`.
Let me get rid of the note 👍🏻

2023-06-30 13:47 UTC, bsmth commented on files/en-us/web/css/_colon_playing/index.md
> +> An element that matches `:buffering` or `:stalled` will also match `:playing`.
done in ac48da911f380d51e29166cc4f4ade8c6de9918b

2023-06-30 13:47 UTC, bsmth commented
>I changed the visual examples to video from audio, as audio may not be visible, but video always is. If you want to use audio, i suggest using audio[controls], because that makes the audio visible.

__Sounds__ good, thanks for the review 👍🏻

2023-07-11 19:58 UTC, estelle commented on files/en-us/web/css/_colon_playing/index.md
> +An element is considered to be playing if it is currently playing the media resource, or if it has temporarily stopped for reasons other than user intent (such as `:buffering` or `:stalled`).
```suggestion
An element is considered to be playing if it is currently playing the media resource, or if it has temporarily stopped for reasons other than user intent (such as {{cssxref(":buffering")}} or {{cssxref(":stalled")}}).
```

2023-07-11 19:59 UTC, estelle commented on files/en-us/web/css/_colon_stalled/index.md
> +> If `:stalled` matches an element, `:playing` will also match that element.
```suggestion
> If `:stalled` matches an element, {{cssxref(":playing")}} will also match that element.
```

2023-07-11 20:00 UTC, estelle approved these changes

2023-07-11 20:01 UTC, merged