Update privacy landing page
mdn/content pull request #27268
Opened 2023-06-12 06:48 UTC by chrisdavidmills

### Description

The MDN [Security](https://developer.mozilla.org/en-US/docs/Web/Security) and [Privacy](https://developer.mozilla.org/en-US/docs/Web/Privacy) pages are not currently finished, have missing details, and don't really present a cohesive story of what the key topics are in this area. This PR intends to provide an update to these pages.

Note - this is nowhere near finished yet, do not review for now

### Motivation

### Additional details

### Related issues and pull requests

2023-06-23 12:44 UTC, chrisdavidmills commented
@dipikabh this one is ready for review now.

2023-06-26 14:15 UTC, couci commented
@fkiriakos07 fyi these are the finished articles on the work you've seen, let me know if there is any flags

2023-06-26 14:48 UTC, couci commented
@chrisdavidmills thanks for working on this.  Some comments as I scrolled through it:
On privacy
- on the original notes there was a mention for privacy by design principles, I can't seem to be able to place it on the PR. If we decided to keep it, we can also mention Mozilla's lean practices https://www.mozilla.org/en-US/about/policy/lean-data/
- on the original notes there was a mention for password reset mechanism but I don't see a section about it, only about how to set passwords. Was that taken out, maybe I missed it?

2023-06-27 01:15 UTC, dipikabh requested changes
I've taken a partial look and leaving some edit suggestions. I'll resume tomorrow.

2023-06-27 01:15 UTC, dipikabh commented on files/en-us/web/security/index.md
> +Good security is essential for good privacy — you could go over to our [Privacy on the web](/en-US/docs/Web/Privacy) guide and follow all the advice listed there, but acting with integrity and having
```suggestion
- **Security** is the act of keeping private data and systems protected against unauthorized access. This includes both company (internal) data and user and partner (external) data.

- **Privacy** refers to the act of giving users the right to control how their data is collected, stored, and used, and not using it irresponsibly. For example, you should clearly communicate to users of your sites the data you are collecting, with whom it will be shared, and how it will be used. Users must be given a chance to consent to your privacy policy, have access to their data you have stored, and delete their data if they no longer wish you to have it.

Good security is very essential for good privacy. You could follow all the advice listed in our [Privacy on the web](/en-US/docs/Web/Privacy) guide, but acting with integrity and having a solid privacy policy are futile if your site is not secure and attackers can just steal data anyway.
```
- swapped "developers" with "you" to maintain consistency across sentences

2023-06-27 01:15 UTC, dipikabh commented on files/en-us/web/security/index.md
> +In general, documents from one origin cannot make requests to other origins. This makes sense, as you don't want sites to be able to interfere with one another and access things they shouldn't do. It
"In general, documents from one origin cannot make requests to other origins."
Can we add an example for this?

```suggestion
In general, documents from one origin cannot make requests to other origins. This makes sense because you don't want sites to be able to interfere with one another and access things they shouldn't. It does make sense to relax this restriction in some circumstances; for example, you might have multiple sites that interact with each other, and you may want these sites to request resources from one another, such as using [`fetch()`](/en-US/docs/Web/API/fetch).
```

2023-06-27 01:15 UTC, dipikabh commented on files/en-us/web/security/index.md
> +### Same-origin policy
should we rename this to 

```suggestion
### Same-origin policy and CORS
```

2023-06-27 01:15 UTC, dipikabh commented on files/en-us/web/security/index.md
> +This can be permitted using [Cross-Origin Resource Sharing (CORS)](/en-US/docs/Web/HTTP/CORS), an HTTP-header based mechanism that allows a server to indicate any origins (domain, scheme, or port) ot
```suggestion
This can be permitted using [Cross-Origin Resource Sharing (CORS)](/en-US/docs/Web/HTTP/CORS), an HTTP-header-based mechanism that allows a server to indicate any origins (domain, scheme, or port) other than its own from which a browser should permit loading resources.
```

2023-06-27 12:25 UTC, fkiriakos07 commented on files/en-us/web/privacy/index.md
> +In this article, we define privacy and important related terms, examine browser features that automatically protect user privacy, and look at what users can do to create privacy-respecting web conten
nit pick: this is also a bit long, would it make sense to break it down to bullet points?

2023-06-27 12:38 UTC, fkiriakos07 commented on files/en-us/web/privacy/index.md
> +So-called "powerful" web API features that provide access to potentially sensitive data and operations are available only in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), which basical
do you mean HTTPS-only?

2023-06-27 12:57 UTC, fkiriakos07 commented on files/en-us/web/security/index.md
> +- Use an alternative client-side storage mechanism such as [Web Storage](/en-US/docs/Web/API/Web_Storage_API) to persist data. This does have the downside that the data is stored per-origin, so it ca
it might be worth it to point out the different types of web storage and their security implications, we usually prefer developers to use sessionStorage since data stored in localStorage is persistent between sessions.

2023-06-27 13:02 UTC, fkiriakos07 commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
another common method of leaking query string parameters in GET requests is indexing and archiving services

2023-06-27 13:11 UTC, fkiriakos07 reviewed
content looks great, I added a couple of suggestions. Thanks.

2023-06-27 13:11 UTC, fkiriakos07 commented on files/en-us/web/security/index.md
> +Following on from the previous section, when you do allow feature and resource usage on your site, you should try to ensure that resources have not been tempered with.
```suggestion
Following on from the previous section, when you do allow feature and resource usage on your site, you should try to ensure that resources have not been tampered with.
```

2023-06-27 13:11 UTC, fkiriakos07 commented on files/en-us/web/security/index.md
> +## Sanitize form input
a very important method to protect against injections is to use output encoding (or escaping) when displaying user input on the application. I think it's worth adding a section about it, https://owasp.org/www-project-proactive-controls/v3/en/c4-encode-escape-data

2023-06-27 17:34 UTC, dipikabh requested changes
This is the review for the Security page. I'll come back for looking at the Privacy page in a bit.

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +- The flipside of this is educating your users against phishing, which is the act of sending a user an email, SMS, etc. containing a link to a site that looks like a site they use every day, but isn'
- "The flipside of this is educating": can we clarify "this" here
- breaking up the sentence to have the phishing definition in an independent sentence

```suggestion
- The flipside of this is educating your users against phishing. The technique of phishing is used by attackers where they send a user an email, SMS, etc. that contains a link to a site. When users click on the link, it takes them to a site that looks like a site they use every day but isn't. The phishing link is combined with a message designed to trick users into entering their username and password with the intention of stealing and using this data for malicious purposes. Some phishing sites can be very sophisticated and hard to distinguish from the real website. You should, therefore, educate your users to not trust random links in emails and text messages. If users receive a message along the lines of "Urgent, you need to log in now to resolve an issue", they should go to the site directly in a new tab and try logging into the website directly rather than clicking the link in the email/message. Or they could phone or email you to discuss the message they received.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +- Manage user login sessions with unique [session IDs](https://en.wikipedia.org/wiki/Session_ID), and automatically log out after periods of inactivity.
```suggestion
- Manage user login sessions with unique [session IDs](https://en.wikipedia.org/wiki/Session_ID) and automatically logging out users after periods of inactivity.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
```suggestion
As a general rule, you shouldn't include sensitive data in URLs; if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `POST` requests rather than `GET` requests to avoid this. Our article on [Referer header policy: Privacy and security concerns](/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns) describes in more detail the privacy and security risks associated with the [Referer HTTP header](/en-US/docs/Web/HTTP/Headers/Referer) and offers advice on mitigating those risks.
```
that needs a fix in the page title as well

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +> **Note**: Steering away from transmitting sensitive data in URLs via `GET` requests can help protect against {{glossary("CSRF", "cross-site request forgery")}} and [replay attacks](https://en.wikip
for some reason, this note is not rendering in a blue box

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +CSP allows you to add a layer of security by for example only allowing images or scripts to be loaded from specific trusted origins. This helps to detect and mitigate certain types of attacks, includ
```suggestion
CSP allows you to add a layer of security by, for example, allowing images or scripts to be loaded only from specific trusted origins. This helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ({{Glossary("Cross-site_scripting", "XSS")}}) and data injection attacks. These attacks involve a range of malicious activities, including data theft, site defacement, and distribution of malware.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +Consider using tools like [Content Security Policy](/en-US/docs/Web/HTTP/CSP) (CSP) and [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy) to enforce a set of feature and resource usage on
```suggestion
Consider using tools like [Content Security Policy](/en-US/docs/Web/HTTP/CSP) (CSP) and [Permissions policy](/en-US/docs/Web/HTTP/Permissions_Policy) to enforce a set of feature and resource usage on your site that makes it harder to introduce vulnerabilities.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +Permissions policy works in a similar way, except that it is more concerned with allowing or blocking access to specific "powerful features" (as mentioned earlier).
```suggestion
Permissions policy works in a similar way, except that it is more concerned with allowing or blocking access to specific "powerful features" ([as mentioned earlier](#secure_contexts_and_feature_permissions)).
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +> **Note:** Such policies are very useful to help keep sites secure, especially when you are using a lot of third party code on your site. Be careful however — if you block usage of a feature that a
```suggestion
> **Note:** Such policies are very useful to help keep sites secure, especially when you are using a lot of third party code on your site. However, keep in mind that if you block usage of a feature that a third-party script relies on to work, you may end up breaking your site's functionality.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
> +In [clickjacking](/en-US/docs/Glossary/Clickjacking), a user is fooled into clicking on a UI element that performs some action other than what the user expects. This can be a risk inherent in embedde
```suggestion
In [clickjacking](/en-US/docs/Glossary/Clickjacking), a user is fooled into clicking on a UI element that performs an action different from what the user expects. This can be a risk inherent in embedded third-party content (make sure you trust what is being embedded into your site), and it can also be combined with phishing.
```

2023-06-27 17:34 UTC, dipikabh commented on files/en-us/web/security/index.md
>  - [Security Blog](https://blog.mozilla.org/security/)
```suggestion
- [Mozilla security blog](https://blog.mozilla.org/security/)
```

2023-06-28 03:08 UTC, dipikabh requested changes

2023-06-28 03:08 UTC, dipikabh commented on files/en-us/web/privacy/index.md
> +- How the user is able to view the data you have collected from them, and delete it if they want to.
I would reword these a bit differently - to remove the question word from the beginning

```suggestion
- Data that you collect
- Ways in which you use the data
- Parties with whom you tend to share the data, if at all, and a declaration that you will ask for user consent before sharing
- Duration for which you keep the data for before it is deleted
- Ways in which users can view the data you have collected from them and a way for them to delete it if they want to
```

2023-06-28 03:08 UTC, dipikabh commented on files/en-us/web/privacy/index.md
> +### Don't collect more data than you need
This and the next two might need to be changed to H4
```suggestion
#### Don't collect more data than you need
```

2023-07-12 17:52 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +In general, documents from one origin cannot make requests to other origins. This makes sense, as you don't want sites to be able to interfere with one another and access things they shouldn't do. It
The `fetch()` thing mentioned at the end of the paragraph is a pretty good example.

2023-07-12 19:12 UTC, chrisdavidmills commented
> @chrisdavidmills thanks for working on this. Some comments as I scrolled through it: On privacy
> 
>     * on the original notes there was a mention for privacy by design principles, I can't seem to be able to place it on the PR. If we decided to keep it, we can also mention Mozilla's lean practices https://www.mozilla.org/en-US/about/policy/lean-data/
> 
>     * on the original notes there was a mention for password reset mechanism but I don't see a section about it, only about how to set passwords. Was that taken out, maybe I missed it?

@couci I decided to not include these after all. I've checked, and they are not mentioned in the curriculum. I will include a link to the lean data principles; they are pretty nice.

2023-07-13 07:59 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +Modern browsers already have a wealth of features to protect users' privacy on the web, but that's not enough. To create a trustworthy, privacy-respecting experience, developers need to educate their
One of Dipika's edits already improved this paragraph, so I think we are all good here.

2023-07-13 08:00 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +In this article, we define privacy and important related terms, examine browser features that automatically protect user privacy, and look at what users can do to create privacy-respecting web conten
Yes, good idea. I've broken this into bullets in the next commit.

2023-07-13 08:02 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +So-called "powerful" web API features that provide access to potentially sensitive data and operations are available only in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), which basical
This already got fixed, I think by one of your later suggestions. So all good here.

2023-07-13 08:12 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +- Use an alternative client-side storage mechanism such as [Web Storage](/en-US/docs/Web/API/Web_Storage_API) to persist data. This does have the downside that the data is stored per-origin, so it ca
Good idea. In the next commit, I've added to this bullet to point out the two different variants and the difference between them, and recommend `sessionStorage`.

2023-07-13 09:06 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
@fkiriakos07 have you got a link to share that provides more context around this? I tried searching, but couldn't really find anything useful, so I wasn't sure what to write here.

2023-07-13 09:19 UTC, fkiriakos07 commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
I couldn't find lot of interesting resources too, maybe here: https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url.

Maybe we can point out that in addition to leaking the parameters in the referrer header, the GET URLs can also be indexed by public web crawlers, HTTP proxies and archiving tools such as the internet archive, https://web.archive.org/

2023-07-13 09:29 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +Browsers control usage of several "powerful features" in a couple of different ways. By "powerful features", we mean things like a site generating system notifications, using a user's web cam to get
I've implemented these changes, sort of, but not in quite the same way you did here - "clogging up their browser/system" and "creating {{glossary("denial of service", "Denial of Service")}} (DoS) attacks" is the same point, so splitting these bits up wasn't correct.

2023-07-13 09:32 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +## Store client-side data responsibly
Logically, yes, probably. However, that would leave the right-hand TOC looking a bit empty, and I thought it would be good to have the different sections listed there, hence me leaving the heading levels like this

2023-07-13 09:40 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +It is a good idea to prepare for this, by limiting the amount of tracking activities you rely on, and/or implementing desired information persistence in other ways. For example:
I've done this one, but in a slightly different way. It is really more about preparing for complete removal of cross-site cookies, than limiting usage. The latter has already happened.

2023-07-13 09:43 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +- Use an alternative client-side storage mechanism such as [Web Storage](/en-US/docs/Web/API/Web_Storage_API) to persist data. This does have the downside that the data is stored per-origin, so it ca
"such as using the" sounded a bit awkward. I've done this one slightly differently.

2023-07-13 09:44 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +## Protect user identity and manage logins
As mentioned earlier, I want to keep these as h2s so they are more visible.

2023-07-13 09:46 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +- When collecting user login information, enforce strong passwords so that your user's account details cannot be easily guessed. Weak passwords are one of the main causes of security breaches. In add
This should have been "our article on"; I've done this in the next commit.

2023-07-13 09:57 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
Ah, now I understand, thanks! I've put this stuff under a new heading and added information about the archiving risks.

2023-07-13 10:16 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +- The flipside of this is educating your users against phishing, which is the act of sending a user an email, SMS, etc. containing a link to a site that looks like a site they use every day, but isn'
I've implemented quite a lot of these changes but done it in a slightly different way. The two key issues you brought up have been fixed.

2023-07-13 10:18 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +- Manage user login sessions with unique [session IDs](https://en.wikipedia.org/wiki/Session_ID), and automatically log out after periods of inactivity.
I've just added "users" after "log out", in this case. Your rewording sounded at odds with the start of the sentence.

2023-07-13 10:21 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +As a general rule, you shouldn't include sensitive data in URLs — if a third party intercepts the URL (for example via the {{httpheader("Referer")}} header), they could steal that information. Use `P
I've done all of this, except that I've used a color rather than a semi-colon in the first sentence - the second article is really a lead-on from the first article, not a separate point.

2023-07-13 10:25 UTC, chrisdavidmills commented on files/en-us/web/security/index.md
> +> **Note**: Steering away from transmitting sensitive data in URLs via `GET` requests can help protect against {{glossary("CSRF", "cross-site request forgery")}} and [replay attacks](https://en.wikip
Ah, it was because the colon was outside the asterisks; it's pretty picky about the syntax order. Fixed now!

2023-07-13 10:26 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +## Privacy defined
I've decided to do with "Defining privacy terms and concepts"

2023-07-13 10:28 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +### What is privacy?
I've gone with "Privacy and its relationship with security"

2023-07-13 10:35 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +- **Privacy** refers to the act of giving users the right to control how their data is collected, stored, and used, and not using it irresponsibly. For example, developers should make it very clear t
I've done a lot of updates here, but in a slightly different way.

2023-07-13 10:37 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +- **Security** is the act of keeping private data and systems protected against unauthorized access. This includes both company (internal) data, and user and partner (external) data. It is no use hav
Updated

2023-07-13 10:39 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +## What do browsers do automatically?
Changed

2023-07-13 10:43 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +So-called "powerful" web API features that provide access to potentially sensitive data and operations are available only in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), which basical
updated

2023-07-13 10:45 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +For example, one change that was agreed upon and rolled out across all browsers was an update to the {{httpheader("Set-Cookie")}} header [`SameSite`](/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesites
done

2023-07-13 10:50 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +The [privacy sandbox project](https://developer.chrome.com/en/docs/privacy-sandbox/) is a series of proposals to satisfy cross-site use cases without requiring third-party cookies or other tracking m
This isn't really accurate, as most of these features aren't in Chrome yet. Instead I've put "Google's privacy sandbox project..."

2023-07-13 10:51 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +## What does a developer need to do?
updated

2023-07-13 11:05 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +## Collect data ethically
As discussed before, I'd prefer these to be H2s, so that they show up in the right hand nav.

2023-07-13 11:07 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +3. Delete the data once you have finished with it
Titles and bullets updated

2023-07-13 11:08 UTC, chrisdavidmills commented on files/en-us/web/privacy/index.md
> +### Don't collect more data than you need
As discussed previously, no.

2023-07-13 12:55 UTC, fkiriakos07 commented
Hello @chrisdavidmills , changes look good, thank you.

2023-07-17 19:51 UTC, dipikabh commented on files/en-us/web/security/index.md
> +Browsers control usage of several "powerful features" in a couple of different ways. By "powerful features", we mean things like a site generating system notifications, using a user's web cam to get
Got it. Thanks

2023-07-17 20:35 UTC, dipikabh approved these changes
Just few nits, but this is good to land. Thank you for your work on this! 🙏

2023-07-17 20:35 UTC, dipikabh commented on files/en-us/web/security/index.md
> +- When collecting user login information, enforce strong passwords so that your user's account details cannot be easily guessed. Weak passwords are one of the main causes of security breaches. In add
Oops, yeah. Sorry about that and thanks for catching it.

2023-07-17 20:35 UTC, dipikabh commented on files/en-us/web/security/index.md
> +- You should also educate your users about **phishing**. Phishing is the act of sending a user a message (for example an email or SMS) containing a link to a site that looks like a site they use ever
```suggestion
- You should also educate your users about **phishing**. Phishing is the act of sending a message to a user (for example, an email or an SMS) containing a link to a site that looks like a site they use every day but isn't. The link is accompanied by a message designed to trick users into entering their username and password on the site so it can be stolen and then used by an attacker for malicious purposes.
```

2023-07-17 20:35 UTC, dipikabh commented on files/en-us/web/security/index.md
> +  > **Note:** Some phishing sites can be very sophisticated and hard to distinguish from the real thing. You should therefore educate your users to not trust random links in emails and SMS messages.
```suggestion
  > **Note:** Some phishing sites can be very sophisticated and hard to distinguish from the real website. You should therefore educate your users to not trust random links in emails and SMS messages. If they receive a message along the lines of "Urgent, you need to log in now to resolve an issue", they should go to the site directly in a new tab and try logging in directly rather than clicking the link in the message. Or they could phone or email you to discuss the message they received.
```

2023-07-17 20:35 UTC, dipikabh commented on files/en-us/web/security/index.md
> +> **Note**: Steering away from transmitting sensitive data in URLs via `GET` requests can help protect against {{glossary("CSRF", "cross-site request forgery")}} and [replay attacks](https://en.wikip
Good catch, thanks!

2023-07-17 20:35 UTC, dipikabh commented on files/en-us/web/privacy/index.md
> +3. Delete the data once you have finished with it
Thank you

2023-07-20 09:15 UTC, merged

2023-07-20 09:15 UTC, chrisdavidmills commented
@dipikabh And this one now merged too; soooopah!