Devtools as optional permission
mdn/content pull request #27282
Opened 2023-06-13 00:10 UTC by rebloor

### Description

Addresses the documentation needs of [Bug 1606862](https://bugzilla.mozilla.org/show_bug.cgi?id=1606862) Make devtools an optional permission.

2023-06-23 14:07 UTC, Rob--W requested changes

2023-06-23 14:07 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.md
> +- `devtools`
```suggestion
- `devtools` (implicitly granted when the [`devtools_page`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/devtools_page)) manifest key is present)
```

The devtools APIs are only available when `devtools_page` is present. I'm not sure if it should be listed here. Here is a suggested edit to emphasize when it applies.

Note that the permission merely exists for optional_permissions, and as a consequence it's also available under `permissions`.

2023-06-26 02:23 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/devtools/index.md
> +To use this API you must request `"devtools"` in the [`permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) or [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebEx
Extension workshop changes in https://github.com/mozilla/extension-workshop/pull/1635

2023-06-26 11:56 UTC, Rob--W approved these changes

2023-06-26 11:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/devtools/index.md
> +> NOTE: The "devtools" optional permission is only supported by Firefox and not ([Chromium issue 1143015](https://crbug.com/1143015)).
```suggestion
> NOTE: The "devtools" optional permission is only supported by Firefox and not Chrome ([Chromium issue 1143015](https://crbug.com/1143015)).
```

2023-06-26 11:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md
> +> **Note:** This page describes the devtools APIs in Firefox 55. Although the APIs are based on the [Chrome devtools APIs](https://developer.chrome.com/docs/extensions/mv3/devtools/), Firefox does no
This document mentions Firefox 54/55, which is ages ago. Could you remove the version specific mentions from this article in a follow-up (separate PR so that these can be reviewed independently)?

2023-06-26 11:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md
> +This manifest key implicitly sets the `"devtools"` permission, which triggers [an install-time permission warning about devtools](https://support.mozilla.org/en-US/kb/permission-request-messages-fire
```suggestion
This manifest key implicitly sets the `"devtools"` permission, which triggers [an install-time permission warning about devtools](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_extend-developer-tools-to-access-your-data-in-open-tabs). To avoid this warning, mark the feature as optional by listing the `"devtools"` permission in the [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) manifest key. Setting the optional permission can be particularly helpful when introducing devtools features in an update, as it prevents the extension from being disabled (in Chrome) or blocked from updating (in Firefox).
```

Nice!

2023-06-27 00:09 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md
> +> **Note:** This page describes the devtools APIs in Firefox 55. Although the APIs are based on the [Chrome devtools APIs](https://developer.chrome.com/docs/extensions/mv3/devtools/), Firefox does no
Will do

2023-06-29 03:14 UTC, Rob--W commented
@rebloor Why was this closed without merging?

2023-06-29 04:37 UTC, rebloor commented
@Rob--W by accident

2023-08-10 09:56 UTC, bsmth commented
Hi, looks like we're ready to land this one, shall I merge when CI is done?

2023-08-10 11:34 UTC, rpl approved these changes
r+wc (not a big deal but one small tweak requested in the previous pass from Rob doesn't seem to have been applied).

@rebloor would you mind to confirm if we want to apply that tweak in this PR before merging it?

2023-08-10 11:34 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md
> +> **Note:** This page describes the devtools APIs in Firefox 55. Although the APIs are based on the [Chrome devtools APIs](https://developer.chrome.com/docs/extensions/mv3/devtools/), Firefox does no
@rebloor it looks like this PR is basically ready to be merged, but I noticed the mention to Firefox 55 has not been removed, do we want to remove it by updating this PR before merging it or in a separate PR?

2023-08-10 15:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md
> +> **Note:** This page describes the devtools APIs in Firefox 55. Although the APIs are based on the [Chrome devtools APIs](https://developer.chrome.com/docs/extensions/mv3/devtools/), Firefox does no
@rpl the work to take care of the reference to 55 is in https://github.com/mdn/content/pull/28132 and it's related PRs.

2023-08-10 15:55 UTC, merged