Add WGSLLanguageFeatures content
mdn/content pull request #27295
Opened 2023-06-13 10:56 UTC by chrisdavidmills

### Description

Chrome 115 adds the [`WGSLLanguageFeatures`](https://gpuweb.github.io/gpuweb/#gpuwgsllanguagefeatures) feature of WebGPU. See https://chromestatus.com/feature/5149681044160512.

This PR adds content for the following items:

* The `GPU.wgslLanguageFeatures` property
* The `WGSLLanguageFeatures` class

### Motivation

### Additional details

### Related issues and pull requests

2023-06-15 16:54 UTC, toji reviewed
LGTM! It's a little unfortunate that we don't even have a speculative feature name to make better examples with, but I think this is the best that can be done with the feature considering it's lack of actual use cases at the moment.

2023-06-15 16:54 UTC, toji commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +We have not listed the exact set of WGSL language extensions available to be used in WebGPU, as it will vary between implementations and physical devices, and will change over time. For a list, refer
This is an amusing way of saying "There are none", but I understand where it's coming from in terms of forward compatibility. :grin:

2023-06-19 16:59 UTC, toji commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +We have not listed the exact set of WGSL language extensions available to be used in WebGPU, as it will vary between implementations and physical devices, and will change over time. For a list, refer
I'm not aware of anything coming down the pipe in the really near term. Pinging @dneto0 to see if he has any estimates to give on when we might first see this used.

2023-06-20 07:28 UTC, chrisdavidmills commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +We have not listed the exact set of WGSL language extensions available to be used in WebGPU, as it will vary between implementations and physical devices, and will change over time. For a list, refer
Cool, thanks.

2023-06-21 21:47 UTC, dipikabh requested changes
I've added some edit suggestions

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +You should note that not all WGSL language extensions will be available to WebGPU in all browsers that support it. If you are hoping to take advantage of a specific extension in a WebGPU app, thoroug
does this need to go in a `Note:` box?

```suggestion
Note that not all WGSL language extensions are available to WebGPU in all browsers that support the API. We recommend you thoroughly test the extension you choose to use in a WebGPU app.
```
Nothing's wrong with the current style, the edit suggestion is to simplify the wording and change to active voice

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +We have not listed the exact set of WGSL language extensions available to be used in WebGPU, as it will vary between implementations and physical devices, and will change over time. For a list, refer
how about the following take:

```suggestion
The available WGSL language extensions that can be used in WebGPU can vary across implementations and physical devices and may also change over time. For a complete list, refer to [WGSL language extensions](https://gpuweb.github.io/gpuweb/wgsl/#language-extension) in the WGSL specification.
```

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +The following properties are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects (the below links are to the {{jsxref("Set")}} global object referenc
```suggestion
The following property is available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects (the property link is to the {{jsxref("Set")}} global object reference page):
```
Can we omit this "(the below links are to the {{jsxref("Set")}} global object reference pages)"?

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +The following methods are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects (the below links are to the {{jsxref("Set")}} global object reference p
```suggestion
The following methods are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects (the links below are to the {{jsxref("Set")}} global object reference pages).
```

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +  - : Calls a provided callback function once for each value present in the set, in insertion order.
```suggestion
- {{jsxref("Set.prototype.has()", "has()")}} {{Experimental_Inline}}
  - : Returns a boolean asserting whether or not an element with the given value is present in the set.
- {{jsxref("Set.prototype.values()", "values()")}} {{Experimental_Inline}}
  - : Returns a new iterator object that yields **values** for each element in the set in insertion order.
- {{jsxref("Set.prototype.keys()", "keys()")}} {{Experimental_Inline}}
  - : An alias for {{jsxref("Set.prototype.values()", "values()")}}.
- {{jsxref("Set.prototype.entries()", "entries()")}} {{Experimental_Inline}}
  - : Returns a new iterator object that contains **an array of `[value, value]`** for each element in the set in insertion order.
- {{jsxref("Set.prototype.forEach()", "forEach()")}} {{Experimental_Inline}}
  - : Calls the provided callback function once for each value present in the set in insertion order.
```

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/gpu/wgsllanguagefeatures/index.md
> +You should note that not all WGSL language extensions will be available to WebGPU in all browsers that support it. If you are hoping to take advantage of a specific extension in a WebGPU app, thoroug
same comment as on the other page: Web/API/WGSLLanguageFeatures

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +- The [WebGPU API](/en-US/docs/Web/API/WebGPU_API)
```suggestion
- [WebGPU API](/en-US/docs/Web/API/WebGPU_API)
```

2023-06-21 21:47 UTC, dipikabh commented on files/en-us/web/api/gpu/wgsllanguagefeatures/index.md
> +- The [WebGPU API](/en-US/docs/Web/API/WebGPU_API)
```suggestion
- [WebGPU API](/en-US/docs/Web/API/WebGPU_API)
```

2023-06-26 07:18 UTC, chrisdavidmills commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +You should note that not all WGSL language extensions will be available to WebGPU in all browsers that support it. If you are hoping to take advantage of a specific extension in a WebGPU app, thoroug
OK, I accepted your change and did a little bit more tweaking in my next commit, plus I've put it in a note box and make it consistent across both docs.

2023-06-26 07:23 UTC, chrisdavidmills commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +We have not listed the exact set of WGSL language extensions available to be used in WebGPU, as it will vary between implementations and physical devices, and will change over time. For a list, refer
Again, committed but then tweaked. I thought it was still important to still say that we made a conscious decision to not list them here.

2023-06-26 07:28 UTC, chrisdavidmills commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +The following properties are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects (the below links are to the {{jsxref("Set")}} global object referenc
Yeah, I ended up using pretty much your wording, and getting rid of the parens. they were just awkward, and didn't really add much.

2023-06-26 07:28 UTC, chrisdavidmills commented on files/en-us/web/api/gpu/wgsllanguagefeatures/index.md
> +You should note that not all WGSL language extensions will be available to WebGPU in all browsers that support it. If you are hoping to take advantage of a specific extension in a WebGPU app, thoroug
Updated, as per above comment

2023-06-26 07:30 UTC, chrisdavidmills commented
@dipikabh comments worked through, and changes made. Thanks for the review!

2023-06-26 15:44 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +You should note that not all WGSL language extensions will be available to WebGPU in all browsers that support it. If you are hoping to take advantage of a specific extension in a WebGPU app, thoroug
Looks good, thanks

2023-06-26 15:48 UTC, dipikabh approved these changes
Thanks for the updates! One small nit about adding a colon in two places, otherwise good to go 👍

2023-06-26 15:48 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +The following property is available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects.
```suggestion
The following property is available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects:
```

2023-06-26 15:48 UTC, dipikabh commented on files/en-us/web/api/wgsllanguagefeatures/index.md
> +The following methods are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects.
```suggestion
The following methods are available to all read-only [setlike](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) objects:
```

2023-06-27 06:40 UTC, merged