Update index.md
mdn/content pull request #27304
Opened 2023-06-13 17:33 UTC by postmeback

Added example for fallback content

"Fixes #27300"

2023-06-13 17:54 UTC, postmeback commented
Requesting any maintainer to help me with `prettier` configuration.

2023-06-15 02:19 UTC, estelle requested changes

2023-06-15 02:19 UTC, estelle commented on files/en-us/web/html/element/object/index.md
> +></object>
```suggestion
<img src="path/image.jpg" alt="useful image description" />
</object>
```

2023-06-15 02:19 UTC, estelle commented on files/en-us/web/html/element/object/index.md
> +
```suggestion
If the video in the example fails to load, the user will be provided with an image as fallback content. The {{HTMLElement("img")}} tag is used to display an image. We include the `src` attribute set to the path to the image we want to embed. We also include the `alt` attribute, which provides the image with an accessible name. If the image also fails to load, the content of the `alt` attribute will be displayed.

```

2023-06-15 02:19 UTC, estelle commented on files/en-us/web/html/element/object/index.md
> +  height="140"
```suggestion
  height="140">
```
this issue was caused by running prettier :|

2023-06-15 02:19 UTC, estelle commented on files/en-us/web/html/element/object/index.md
> +
Thank you for your PR. The fallback content should be within the `object` example, not as a separate fallback section. The issue raised was about providing a fallback for when the resource defined by the `object` attribute fail to load, not if the image fails to load ;)

We try not to include "onEvent" on MDN, opting for addEventListener instead, just to demonstrate best practices.

2023-06-15 02:20 UTC, estelle commented on files/en-us/web/html/element/object/index.md
> +></object>
I think https://github.com/mdn/content/issues/27300 was about adding fallback content for the object, not an example of fallback content in general. So, suggested changes

2023-06-15 16:31 UTC, estelle approved these changes
Thanks! 🎉

2023-06-15 16:31 UTC, merged