navigator.scheduling.isInputPending
mdn/content pull request #27381
Opened 2023-06-18 08:26 UTC by behnammodi

### Description

Add a small doc about `navigator.scheduling.isInputPending`

### Motivation

There is no document related to the feature

### Additional details
null

### Related issues and pull requests
null

2023-06-19 15:09 UTC, Elchi3 requested changes
Thanks for your PR! I see there is the following IDL in the spec, https://wicg.github.io/is-input-pending/#dom-scheduling:

```webidl
partial interface Navigator {
  readonly attribute Scheduling scheduling;
};
```

and 

```WebIDL
[Exposed=Window] interface Scheduling {
   boolean isInputPending(optional isInputPendingOptions = {});
};
```

In terms of MDN pages, this would mean to create three pages:

Web/API/Navigator/scheduling 
Web/API/Scheduling
Web/API/Scheduling/isInputPending

This PR creates Web/API/Navigator/scheduling but documents the `isInputPending` method which should be documented under Web/API/Scheduling/isInputPending.

Does that make sense to you? Can you create all three pages?

2023-06-19 15:30 UTC, behnammodi commented
@Elchi3 Yes, thank you for review, I will create them

2023-06-19 20:03 UTC, behnammodi commented
I have created `web/api/scheduling/isInputPending/index.md` file and moved all previous content into it

I have created 2 other files:
`web/api/navigator/scheduling/index.md`
and 
`web/api/scheduling/index.md`

I am trying to find more useful content for there 2 files.

2023-06-20 08:47 UTC, Elchi3 commented
Maybe you can look around how similar APIs were documented.

For example, the Ink API has a very similar structure. The 3 pages are:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/ink
https://developer.mozilla.org/en-US/docs/Web/API/Ink
https://developer.mozilla.org/en-US/docs/Web/API/Ink/requestPresenter

Does that help?

2023-06-22 19:57 UTC, behnammodi commented
@Elchi3 Yes, I attempted to mimic, and I hope it will turn out well

2023-06-26 12:56 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isInputPending/index.md
The build fails because the folder name isn't all lower-case.
You need to rename/move this: `isInputPending/index.md `-> `isinputpending/index.md`.

2023-06-26 13:13 UTC, Elchi3 requested changes

2023-06-26 13:13 UTC, Elchi3 commented on files/en-us/web/api/scheduling/index.md
> +The **`scheduling`** read-only property of the {{domxref("Navigator")}} interface returns an {{domxref("Scheduling")}} object for the current document.
```suggestion
The **Scheduling`** object provides methods and properties to control scheduling tasks within the current document. 
```

2023-06-26 13:13 UTC, Elchi3 commented on files/en-us/web/api/scheduling/index.md
> +An {{domxref('Scheduling')}} object.
We need no Value section here but rather a section listing "Instance methods" (with the only method being isInputPending). See https://developer.mozilla.org/en-US/docs/Web/API/Ink#instance_methods for an example

2023-06-26 13:13 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isInputPending/index.md
> +`navigator.scheduling.isInputPending` is an experimental feature that is part of the JavaScript Scheduling API. It allows you to check whether there are pending input events in the event queue, indic
```suggestion

{{SeeCompatTable}}{{APIRef("Scheduling API")}}

The `isInputPending()` method allows you to check whether there are pending input events in the event queue, indicating that the user has interacted with the page or the system is about to dispatch such events.
```

2023-06-26 13:13 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isInputPending/index.md
> +This feature can be useful in scenarios where you want to check if there are any pending input events before performing a long-running operation or updating the UI. By checking the value of navigator
```suggestion
This method can be useful in scenarios where you want to check if there are any pending input events before performing a long-running operation or updating the UI. By checking the value of `navigator.scheduling.isInputPending`, you can avoid blocking the main thread when the user is interacting with the page.
```

2023-06-26 13:13 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isInputPending/index.md
> +## Value
```suggestion
### Return value
```

2023-06-26 13:16 UTC, behnammodi commented on files/en-us/web/api/scheduling/index.md
> +The **`scheduling`** read-only property of the {{domxref("Navigator")}} interface returns an {{domxref("Scheduling")}} object for the current document.
Should I keep the last backtick? 
```
The **Scheduling`**
```

2023-06-26 13:20 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isInputPending/index.md
> +The `navigator.scheduling.isInputPending` property returns a Boolean value, indicating whether there are pending input events or not. It can have one of the following three possible values:
```suggestion
The `navigator.scheduling.isInputPending` method returns a Boolean value, indicating whether there are pending input events or not. It can have one of the following three possible values:
```

2023-06-26 13:20 UTC, Elchi3 commented on files/en-us/web/api/scheduling/index.md
> +The **`scheduling`** read-only property of the {{domxref("Navigator")}} interface returns an {{domxref("Scheduling")}} object for the current document.
Sorry it should use backticks, fixed my suggestion

2023-06-26 13:51 UTC, Elchi3 reviewed
This PR now has two files for isInputPending (and content on one file got improved already). We need the lower-cased folder and the corrected content.

2023-06-26 15:01 UTC, behnammodi commented
> This PR now has two files for isInputPending (and content on one file got improved already). We need the lower-cased folder and the corrected content.

Fixed

2023-06-26 16:06 UTC, behnammodi commented on files/en-us/web/api/scheduling/index.md
> +An {{domxref('Scheduling')}} object.
Should I replace it with something like:

```
## Instance methods

- {{domxref("Scheduling.isInputPending", "isInputPending()")}} {{Experimental_Inline}}
  - : Returns a {{jsxref("Boolean")}}
```

2023-06-26 16:28 UTC, Elchi3 commented on files/en-us/web/api/scheduling/index.md
> +An {{domxref('Scheduling')}} object.
Yes exactly!

2023-06-26 16:29 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isinputpending/index.md
> +The property is read-only.
I think this line should be deleted.

2023-06-26 17:05 UTC, behnammodi commented on files/en-us/web/api/scheduling/isinputpending/index.md
> +The property is read-only.
Deleted

2023-06-26 17:05 UTC, behnammodi commented on files/en-us/web/api/scheduling/index.md
> +An {{domxref('Scheduling')}} object.
Done

2023-06-28 14:17 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isinputpending/index.md
> +`navigator.scheduling.isInputPending` is an experimental feature that is part of the JavaScript Scheduling API. It allows you to check whether there are pending input events in the event queue, indic
```suggestion
The `isInputPending()` method allows you to check whether there are pending input events in the event queue, indicating that the user has interacted with the page or the system is about to dispatch such events.
```

2023-06-28 14:19 UTC, Elchi3 commented on files/en-us/web/api/scheduling/isinputpending/index.md
> +The `navigator.scheduling.isInputPending` property returns a Boolean value, indicating whether there are pending input events or not. It can have one of the following three possible values:
```suggestion
The `navigator.scheduling.isInputPending()` method returns a Boolean value, indicating whether there are pending input events or not. It can have one of the following three possible values:
```

2023-06-28 14:20 UTC, Elchi3 commented on files/en-us/web/api/scheduling/index.md
> +The **`scheduling`** read-only property of the {{domxref("Navigator")}} interface returns an {{domxref("Scheduling")}} object for the current document.
```suggestion
The **`Scheduling`** object provides methods and properties to control scheduling tasks within the current document.
```

2023-06-28 14:25 UTC, Elchi3 commented
Thanks! Almost ready! We just need to add the navigator.scheduling property to the list of navigator properties https://developer.mozilla.org/en-US/docs/Web/API/Navigator#standard_properties

(https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/index.md)

2023-06-28 15:50 UTC, behnammodi commented
> Thanks! Almost ready! We just need to add the navigator.scheduling property to the list of navigator properties https://developer.mozilla.org/en-US/docs/Web/API/Navigator#standard_properties
> 
> (https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/index.md)

I will handle it rest of them

2023-06-28 16:04 UTC, behnammodi commented
> Thanks! Almost ready! We just need to add the navigator.scheduling property to the list of navigator properties https://developer.mozilla.org/en-US/docs/Web/API/Navigator#standard_properties
> 
> (https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/index.md)

Done, I think it is ready to merge

2023-06-29 09:38 UTC, Elchi3 commented on files/en-us/web/api/navigator/index.md
> +  - : Returns an {{domxref("Scheduling")}} object for the current document.
```suggestion
  - : Returns a {{domxref("Scheduling")}} object for the current document.
```

2023-06-29 09:53 UTC, Elchi3 approved these changes
Thank you @behnammodi 👍

2023-06-29 09:53 UTC, merged