Add AbortSignal.any
mdn/content pull request #27424
Opened 2023-06-20 00:59 UTC by Jamesernator

### Description

This adds MDN docs for the [AbortSignal.any](https://dom.spec.whatwg.org/#dom-abortsignal-any).

### Motivation

This is a new API.

### Additional details

Spec is [here](https://dom.spec.whatwg.org/#dom-abortsignal-any). A change has been made to an example on the main `AbortSignal` page also.

# Note

I'm unsure of where to add the relevant `{{Specifications}}` link. Checking the page the local server just shows `{{Specifications}}` where the specifications box should be (other pages seem to work fine).

Fixes #30095

2023-06-20 03:02 UTC, hamishwillee commented
@Jamesernator MDN document things once there is a browser with an release implementation - existence in a specification is not enough. Do you know of a browser that supports this?

The reason the specifications and browser compatibility are not working is that there is no front matter key like:
```
browser-compat: api.AbortSignal.any_static
```

The browser compatibility data needs to be updated with the same key and data for the supported browser versions: https://github.com/mdn/browser-compat-data/blob/main/api/AbortSignal.json

2023-06-24 01:17 UTC, Jamesernator commented
Ah yes this is new in Chrome Dev, admittedly I assumed it was already shipping in browsers as Node has already shipped it.

2023-06-26 04:36 UTC, hamishwillee commented
@Jamesernator Actually it being in node/deno is good enough to justify doing the docs, but we should also do the browser compatibility data too.

2023-08-29 11:50 UTC, bsmth commented
Hi @Jamesernator - just dropping a note that there are some merge conflicts that need to be resolved here if you'd like to come back to this.

__notes:__
- https://github.com/shaseley/abort-signal-any (explainer)

2023-09-12 01:07 UTC, Jamesernator commented
The merge conflict is resolved, I've also added the compat data in [a PR to browser-compat-data](https://github.com/mdn/browser-compat-data/pull/20692).

2023-11-16 13:52 UTC, skyclouds2001 commented
the issue https://github.com/mdn/content/issues/30095 suggest this contribute, maybe it is a good idea to add a `fixes` to the issue?

2023-11-16 14:55 UTC, teoli2003 requested changes
A few details and this is good to go. Good job!

2023-11-16 14:55 UTC, teoli2003 commented on files/en-us/web/api/abortsignal/any_static/index.md
> +  // do something with downloaded content
```suggestion
  // Do something with downloaded content:
  // …
```

2023-11-16 14:55 UTC, teoli2003 commented on files/en-us/web/api/abortsignal/index.md
> +- {{domxref("AbortSignal.any()")}}
```suggestion
- {{domxref("AbortSignal/any_static", "AbortSignal.any()")}}
```

2023-11-16 14:55 UTC, teoli2003 commented on files/en-us/web/api/abortsignal/any_static/index.md
> +This example demonstrates combining both a signal from an {{domxref("AbortController")}}, and a timeout signal from {{domxref("AbortSignal.timeout")}}.
```suggestion
This example demonstrates combining both a signal from an {{domxref("AbortController")}}, and a timeout signal from {{domxref("AbortSignal/timeout_statis", "AbortSignal.timeout")}}.
```

2023-11-16 14:55 UTC, teoli2003 commented
I have added the "Fixes #xyz" in the description.

2023-11-17 14:02 UTC, skyclouds2001 commented on files/en-us/web/api/abortsignal/any_static/index.md
> +An `AbortSignal` instance with the {{domxref("AbortSignal.aborted")}} property set to `true`, and {{domxref("AbortSignal.reason")}} set to the specified or default reason value.
```suggestion
An `AbortSignal` instance with the {{domxref("AbortSignal.reason", "reason")}} property set to the specified or default reason value.
```

note that `AbortSignal.aborted` should initial to be `false`, only when any of the passing `signals` is already aborted, the `AbortSignal.aborted` will be `true`

2023-11-17 14:02 UTC, skyclouds2001 commented on files/en-us/web/api/abortsignal/any_static/index.md
> +### Using AbortSignal.any()
```suggestion
### Using `AbortSignal.any()`
```

2023-11-17 14:21 UTC, skyclouds2001 commented on files/en-us/web/api/abortsignal/any_static/index.md
> +});
```suggestion
const cancelDownloadButton = document.getElementById("cancelDownloadButton");

const userCancelController = new AbortController();
cancelDownloadButton.addEventListener("click", () => {
  userCancelController.abort();
});
```

the `button` should be `cancelDownloadButton`

2023-11-18 05:19 UTC, Jamesernator commented on files/en-us/web/api/abortsignal/any_static/index.md
> +An `AbortSignal` instance with the {{domxref("AbortSignal.aborted")}} property set to `true`, and {{domxref("AbortSignal.reason")}} set to the specified or default reason value.
Yes this section is was nonsense, I copied `AbortSignal.abort` as a template and forgot to change this section.

I've updated this section to be similar to [Promise.any](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any) instead.

2023-11-18 16:28 UTC, skyclouds2001 commented
Just a usage suggestion to Github, when others give a review, you can click the `commit suggestion` button to directly commit the review to your pull request, rather then do the commit yourself instead

![image](https://github.com/mdn/content/assets/95597335/91522d08-e4c9-4e8a-8b27-7f33165404d6)

also, you can go to the `files` panel and use the `add suggestion to batch` button to merge multpile reviews in a single commit

2023-11-20 09:03 UTC, teoli2003 approved these changes
👍

2023-11-20 09:03 UTC, merged