fix(docs): update form screenshots as per latest web browser.
mdn/content pull request #27436
Opened 2023-06-20 12:49 UTC by abhishekrnjn

### Description

Update Browser Screenshots to recent versions in Form Examples. 

### Motivation

Docs will get updated to current version of browser screenshots

### Related issues and pull requests

Fixes #26951

2023-06-20 17:13 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +_The following screenshot shows default, focused and disabled text input types in Firefox 114 and Safari on macOS and in Chrome 114 and Edge 114 on Windows 11._
Drive-by comment/suggestion: Stating the browser and OS versions here creates the dependency to always maintain/update the text and screenshot going forward. How about we remove the version numbers?

```suggestion
_The following screenshot gives you an idea of how the text input field looks in its various states – by default, when it has focus, and when it is marked disabled – across Firefox and Safari on macOS and in Chrome and Edge on Windows._
```

I would even argue if adding this screenshot here is really helpful (why do we need to show both Chrome and Edge) and perhaps we should remove the screenshot and the accompanying text altogether. But if it has to be retained, I think we should make the text generic as suggested above to reduce maintenance.

2023-06-26 07:48 UTC, hamishwillee commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +_The following screenshot shows default, focused and disabled text input types in Firefox 114 and Safari on macOS and in Chrome 114 and Edge 114 on Windows 11._
@dipikabh Thanks very much. My take on this is that in a learn topic it is useful to explain what the controls look like and how they might differ. However given that all browsers do focus, disabled, default somewhat similarly I'm not sure that showing all of the different browsers is worth it. Further, 
- this is going to be an ongoing maintenance issue- will have to do this again in a number of releases.
- there are a bunch of other images further down in the doc.

How about we replace all the images with images from one browser, which we don't identify, and have words to describe what you're seeing. So "mocked up", something like:

----

The screenshot below shows a text input in default, focused, and disabled states. Most browsers indicate focus with a focus ring around the control and the disabled state using grey text or a faded/semi-opaque control.

![image](https://github.com/mdn/content/assets/5368500/6c210ead-01c1-4dd8-a795-300a3021b9a1)

----

And do something similar for the other controls.

Thoughts?

2023-06-29 08:01 UTC, abhishekrnjn commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +_The following screenshot shows default, focused and disabled text input types in Firefox 114 and Safari on macOS and in Chrome 114 and Edge 114 on Windows 11._
So from discussion, what i understand is
- we need screenshot of default, focused and disabled state from only one browser (will prefer Chrome on macOS).
- screenshot and text changes need to be done for all the images present in doc.
These changes i can do.

2023-07-10 00:22 UTC, hamishwillee commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +_The following screenshot shows default, focused and disabled text input types in Firefox 114 and Safari on macOS and in Chrome 114 and Edge 114 on Windows 11._
Yes, except:

> screenshot and text changes need to be done for all the images present in doc.

All sections where you're showing off a feature with UI should have an image - even if there is not an image in the section currently (so not necessarily "update the current pics" - there might be more.

Yes, just one browser. Might be worth saying on the first use that these are from macOS but other browsers use similar highlighting techniques.

2023-07-14 00:04 UTC, hamishwillee requested changes
Just adding "request for changes" as per https://github.com/mdn/content/pull/27436#discussion_r1257580872

2023-09-13 02:16 UTC, dipikabh requested changes, later dismissed
Hello @abhishekrnjn, thanks a lot for making these updates as suggested. I've added a few edits.

Apologies for the delay on reviewing these changes.

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +_Screenshots used in this document are taken in Chrome 115 on macOS. There could be little changes when these fields/buttons are displayed in different browser with different versions, but basic high
```suggestion
The screenshots used in this document were taken in the Chrome browser on macOS. There may be minor variations in these fields/buttons across different browsers, but the basic highlighting technique remains similar._
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +The following screenshot shows default, focused and disabled checkboxes. Default and disabled checkboxes are in checked state where as focused checkbox is in unchecked state with focus ring around it
```suggestion
The following screenshot shows checkboxes in the default, focused, and disabled states. Checkboxes in the default and disabled states appear checked, whereas in the focused state, the checkbox is unchecked, with focus ring around it.
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +The following screenshot shows default and disabled radio buttons in checked state along with focused radio button in unchecked state.
```suggestion
The following screenshot shows default and disabled radio buttons in the checked state, along with focused a radio button in the unchecked state.
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +![Radio buttons in chrome 115 on macOS](radios.png)
```suggestion
![Default, focused and disabled Radio buttons in chrome 115 on macOS](radios.png)
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +The following examples show default, focused, and disabled button input types.
```suggestion
The following screenshot shows a button in the default, focused, and disabled states. In the focused state, there is a focus ring around the button, and in the disabled state, the button is greyed out.
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +![Default, focused and disabled button input types in chrome 115 on macOS](buttons.png)
```suggestion
![Default, focus, and disabled button states in chrome 115 on macOS](buttons.png)
```

2023-09-13 02:16 UTC, dipikabh commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +![File picker widget in chrome 115 on macOS](filepickers.png)
```suggestion
The following screenshot shows the file picker widget in the default, focus, and disabled states when no file is selected.

![File picker widget in default, focus, and disabled states in chrome 115 on macOS](filepickers.png)
```

2023-09-15 08:42 UTC, abhishekrnjn commented
Hello @dipikabh, I have made minor changes in suggestions, rest suggestions looks correct to me. 
Shall i commit these suggested changes?

2023-09-19 05:04 UTC, hamishwillee approved these changes
@abhishekrnjn So what would normally happen is that you would look at @dipikabh suggestions and merge those you think are better than what they replace, or discuss why not. I've reviewed those and made only one minor typo fix and merged.

This is good to go in. IMO it is a good update - it is a lot less complex while retaining all the essential information. Thank you very much for working on this (and @dipikabh for the reviews).

Note, I'm merging this because the review team is short staffed and I know @dipikabh has other responsibilities this week.

2023-09-19 05:05 UTC, merged

2023-09-19 12:10 UTC, dipikabh commented
Thanks for your review support as well @hamishwillee on this. Thank you for committing the suggestions 👍