Add a guide to PWA caching strategies
mdn/content pull request #27442
Opened 2023-06-20 18:02 UTC by wbamberg

...

2023-06-20 22:11 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +```
Here's a thing I don't understand. Even if you precache as an installation dependency, it's possible (although unlikely) that the cache might be cleared (either by the user or by the browser) under your feet. If that happens, and you have cache-only, is this catastrophic for your app? If so, would it be better to omit this one and start with cache-first?

2023-06-20 22:16 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cachedResponse || fetchedResponse;
I'm a bit confused about the async stuff here.

Part of the point of this pattern AIUI is that you can return the cached value before the network request has succeeded/failed, isn't it?

But you have to clone the response before you return it, because you can't clone a response that's been consumed. I'm a bit confused about the async stuff here. Part of the point of this pattern AIUI is that you can return the cached value before the network request has succeeded/failed, isn't it?

Is there a better way to express this using `await`?

2023-06-26 17:00 UTC, captainbrosset requested changes

2023-06-26 17:00 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +```
Realistically, I don't know that many PWAs will want a cache-only strategy. In the end, the user is in charge, and they can delete the cache whenever they want. So if your app never tries the network ever again, the app will be broken beyond repair, unless you ctrl+shift+R to force reload from the network (or use devtools to unregister the SW).

To me pre-cache is just a first step for other strategies (cache-first). First, you put your assets in cache, and then you intercept requests to these assets in the fetch handler, and respond with the cached version. If, for any reason, this doesn't work (perhaps because the user emptied the cache), then you go to the network again and then cache.

2023-06-26 17:00 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return !url.pathname.endsWith(".json");
Maybe add a comment here saying that, only for this example, we only consider non .json requests as cachable.
Again, for the sake of people who just copy/paste code without reading the docs before it :)

2023-06-26 17:00 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +A PWA should clean up any old versions of its cache in the service worker's {{domxref("ServiceWorkerGlobalScope.activate_event", "activate")}} event: when this event fires, the service worker can be
Since all other sections have code samples, maybe add a code sample here too?

2023-06-26 17:23 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +```
>  So if your app never tries the network ever again, the app will be broken beyond repair, unless you ctrl+shift+R to force reload from the network (or use devtools to unregister the SW).

Yeah, that's exactly what I was thinking. So showing cache-only is perhaps going to mislead people, and we should start with cache-first.

2023-06-26 23:20 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +When a service worker is installed, the browser fires an event called {{domxref("ServiceWorkerGlobalScope.install_event", "install")}} in the service worker's global scope. At this point the service
We should probably add a note that installing the SW is different from installing the PWA. The SW can be installed without the user ever installing your app as a PWA.

2023-06-27 00:18 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +Note that in the `install` event handler, we pass the result of the caching operation into the event's {{domxref("ExtendableEvent.waitUntil", "waitUntil()")}} method. This means that if caching fails
"it can be assured that the resource exists in the cache." - unless the cache is later deleted.

The wording around "so conversely" is a little hard to parse - I think something like "conversely, if the installation succeeds, ...."

2023-06-27 00:20 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cache.addAll(precachedResources);
It is pretty cool that you can just tell the cache to do the fetching - these being either requests or URLs. Might be worth noting that, since I was looking for some kind of fetch operation and then addition.

2023-06-27 00:24 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cache.addAll(precachedResources);
Note also this returns a promise, which makes sense because you later wait on the event to complete. However there is quite a lot going on here you might want to talk about. Certainly consider linking to https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil since this is not a "normal" event and that has some useful info in it.

2023-06-27 00:25 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cache.addAll(precachedResources);
Ignore, reading top down.

2023-06-27 00:36 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +In this strategy, the service worker precaches some resources in its `install` event handler:
It might be just me, but I interpreted "Cache only" initially as a strategy for _the whole PWA_. What you actually are describing is a strategy for **some** resources in a PWA that might implement multiple strategies. I was therefore going to "correct" this line to "most resources".

Worth pointing out?

2023-06-27 00:39 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +```
Yes ^^^^. 

I would rename this strategy to Precaching. If you make it clear that this is part of a strategy as per https://github.com/mdn/content/pull/27442/files#r1242991321 it might then require very little modification.

2023-06-27 00:46 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +If the resource is not cachable, we only use the network, as before. The definition of "cachable" is specific to the PWA, but again includes the idea that the resource should not change for this vers
```suggestion
If the resource is not cachable, we only use the network, as before. The definition of "cachable" is specific to the PWA, but again includes the idea that the resource should not change for this version of the app. In this example, everything except requests for JSON data are treated as cachable.
```

2023-06-27 00:51 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +### Stale while revalidate
Is this a well understood name for the concept? It doesn't feel like it tells me what this does.  If not, perhaps something like "Cache first with cache refresh"

2023-06-27 01:02 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cachedResponse || fetchedResponse;
> Part of the point of this pattern AIUI is that you can return the cached value before the network request has succeeded/failed, isn't it?

FWIW This was my concern too, and I don't think this is fixed by the suggestion above ^^^. I also wonder if for some reason the cache.match took forever you'd have to wait on that. 

Could you shove both the promise into [Promise.any()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any) and return the result of the promise as soon as it arrives?

2023-06-27 01:04 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +This is useful for requests for which it is important to get the most fresh response possible, but for which a cached resource is better than nothing. A messaging app's list of recent messages might
I would move this up above the code with the intro - just a preference to state the value of a strategy before explaining how it works.

2023-06-27 01:09 UTC, hamishwillee commented
Looks great. Thoughts:
1. Are there any other strategies you might list, even if you don't outline them in detail?
2. Make the point that a PWA might use a mix of the strategies for different content it manages
3. Make the point that you can't rely on cached data being present.
4. Another strategy in HTTP caches is max-age - is there something similar that can be used in Cache? I.e. "use cache if valid" 
5. Are there any hooks other than install and fetch()? I.e. what if i did want to manage my cache more proactively, and regularly do a prefetch on out of date content?

2023-06-27 03:20 UTC, wbamberg commented
> Looks great. Thoughts:
> 
>     1. Are there any other strategies you might list, even if you don't outline them in detail?

I didn't really want this to be "list every possible strategy". There are some docs like this and it seemed confusing to me. I think ultimately people have to use the strategy that makes sense for them, and we can just list the core that seem most useful.

>     2. Make the point that a PWA might use a mix of the strategies for different content it manages

I say this in the last para of the intro:

> This means that whether and when you should cache a resource is very dependent on the resource in question, and a PWA will typically adopt different strategies for different resources. In this guide we'll look at some common caching strategies for PWAs, and see which strategies make sense for which resources.

Perhaps it is worth reiterating in https://pr27442.content.dev.mdn.mozit.cloud/en-US/docs/Web/Progressive_web_apps/Guides/Caching#caching_strategies?

>     3. Make the point that you can't rely on cached data being present.

You mean, because the cache might have been cleared? Yes, I think I should make this stronger (and actually retire cache-only as it looks like an antipattern).

>     4. Another strategy in HTTP caches is max-age - is there something similar that can be used in Cache? I.e. "use cache if valid"

Not AFAIK. Perhaps @captainbrosset would know?

>     5. Are there any hooks other than install and fetch()? I.e. what if i did want to manage my cache more proactively, and regularly do a prefetch on out of date content?

Actually there are at least a couple that might be worth mentioning. I didn't because I couldn't really see how to fit them but perhaps I should:
- caching on user request: like if we provide a "read it later" button, or an offline option for maps. Then the main.js could fetch (possibly using https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API if the download is big) and then cache the result.
- caching with something like https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API, where the SW could periodically fetch and cache content

Thanks a lot for the comments, v helpful. It's an interesting subject I think.

2023-06-27 03:55 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +### Stale while revalidate
Yes, this is unfortunately what everyone calls it: https://developer.chrome.com/docs/workbox/caching-strategies-overview/#stale-while-revalidate.

2023-06-27 06:17 UTC, hamishwillee commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +### Stale while revalidate
Given how awful that name is I would rename to  `Cache first with refresh` and in the body have "this is also referred to as stale while revalidate"  in order to help search engines.

Your call though. I like the caching topic too.

2023-06-27 07:54 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +When a service worker is installed, the browser fires an event called {{domxref("ServiceWorkerGlobalScope.install_event", "install")}} in the service worker's global scope. At this point the service
Agreed!

2023-06-27 08:00 UTC, captainbrosset commented
> > 4. Another strategy in HTTP caches is max-age - is there something similar that can be used in Cache? I.e. "use cache if valid"

> Not AFAIK. Perhaps @captainbrosset would know?

Sorry I don't.

2023-06-27 22:56 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +```
OK I have pushed https://github.com/mdn/content/pull/27442/commits/7df4572a0baa322a52372eba7cab4977538f098d, which does 2 related things:
- add a new section on "when to cache" that talks about precaching as well as other times you might cache. I kept it fairly short though and didn't include code here as I want to keep the code together in the "caching strategies" section.
- retired "cache only" and basically folded the precaching stuff into "cache first"

2023-06-27 22:57 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +function isCachable(request) {
I think this is redundant now.

2023-06-27 22:57 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +When a service worker is installed, the browser fires an event called {{domxref("ServiceWorkerGlobalScope.install_event", "install")}} in the service worker's global scope. At this point the service
Oh, also added in https://github.com/mdn/content/pull/27442/commits/7df4572a0baa322a52372eba7cab4977538f098d.

2023-06-27 23:16 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +### Stale while revalidate
-> https://github.com/mdn/content/pull/27442/commits/64c618d0fe3400f0c9bbc5c20d98c331579e38ab

2023-06-27 23:18 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +This is useful for requests for which it is important to get the most fresh response possible, but for which a cached resource is better than nothing. A messaging app's list of recent messages might
-> https://github.com/mdn/content/pull/27442/commits/bdb4c6c4905eb3e201716a537926f614c7345925

2023-06-27 23:35 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +In this strategy, the service worker precaches some resources in its `install` event handler:
In https://github.com/mdn/content/pull/27442/commits/cac85eb2e1b8a78b0ba488c64d757b7dbd6f7b67 I added a para at the start of this section that hopefully clarifies things.

2023-06-28 04:24 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  return cachedResponse || fetchedResponse;
OK, I updated the implementation along the lines suggested by Patrick and done some testing, and it seems to work :) -> https://github.com/mdn/content/pull/27442/commits/4e9ee84cab6d1844fc4d4ce132f5c5c8dd5c1fe2.

>> Part of the point of this pattern AIUI is that you can return the cached value before the network request has succeeded/failed, isn't it?
>
> FWIW This was my concern too, and I don't think this is fixed by the suggestion above ^^^.

I think it is addressed (in both versions), because if we get a cache hit we return the cached response without waiting for `fetchResponsePromise`. I experimented with a version of this that had some logging!

```js
// main.js
fetchIngredients.addEventListener("click", async () => {
  try {
    const response = await fetch("ingredients.json");
    const ingredients = await response.json();
    console.log(`app received response to ingredients.json`);
  } catch (e) {
    console.log("error:");
    console.log(e);
  }
});
```

```js
// sw.js
async function cacheFirstWithRefresh(request) {
  const fetchResponsePromise = fetch(request).then(async (networkResponse) => {
    console.log(`sw received network response to ${request.url}`);
    if (networkResponse.ok) {
      const cache = await caches.open("MyCache_1");
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  });

  const cached = await caches.match(request);
  if (cached) {
    console.log(`sw: from cache: ${request.url}`);
    return cached;
  } else {
    console.log(`sw: from network: ${request.url}`);
    return fetchResponsePromise;
  }
}

self.addEventListener("fetch", (event) => {
  event.respondWith(cacheFirstWithRefresh(event.request));
});
```

So the first time I press the button, there is no resource in the cache (it's not precached) and in the console I get:

<img width="500" alt="Screen Shot 2023-06-27 at 9 10 13 PM" src="https://github.com/mdn/content/assets/432915/b7f04d06-a8a2-4fbb-affe-e9bbdbba6359">


This makes sense:

- `sw: from network: https://localhost:4443/ingredients.json`: we have to return the network resource, because the cache is empty
- `sw received network response to https://localhost:4443/ingredients.json`: the app has to wait till the response is received before it can get the JSON. At the point the SW can clone and cache it
- `app received response to ingredients.json`: the app finally gets the JSON

Next time, the response is in the cache, so the SW sends back the cached version and fetches a fresh one:

<img width="500" alt="Screen Shot 2023-06-27 at 9 11 44 PM" src="https://github.com/mdn/content/assets/432915/f9057412-dded-4781-b703-61477bb34cd9">

...so this time, the app gets the JSON before the response has been received.

At least that's what I think is going on! I'm not sure if this is very reliable way to test it though.

> I also wonder if for some reason the cache.match took forever you'd have to wait on that.

Yes, it's an assumption that cache access is usually much faster than network access. There are caching strategies that are supposed to deal with slow caches, but they seemed a little niche to me.

> Could you shove both the promise into [Promise.any()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any) and return the result of the first promise as soon as it fulfills?

Not quite, because [`match()`](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match) doesn't reject on a cache miss, it returns `undefined` (and in that case, you want to return the network response).

I suppose you could just return the network version if the cache call hasn't resolved. I'm not sure it's worth the complexity though...

2023-06-28 04:39 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +Note that in the `install` event handler, we pass the result of the caching operation into the event's {{domxref("ExtendableEvent.waitUntil", "waitUntil()")}} method. This means that if caching fails
-> https://github.com/mdn/content/pull/27442/commits/b49133322674428d48fb2eb9faba3fdb62c81343.

2023-06-28 04:41 UTC, wbamberg commented
I think I've addressed everything except https://github.com/mdn/content/pull/27442#discussion_r1242490549, which I should probably do but am anxious it will involve a lot of explaining about lifecycles and versions.

2023-06-28 04:48 UTC, wbamberg commented
Oh, and I should probably add a bit on prefetch?

2023-06-28 09:50 UTC, captainbrosset approved these changes

2023-06-28 09:50 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +In the `install` event handler, we pass the result of the caching operation into the event's {{domxref("ExtendableEvent.waitUntil", "waitUntil()")}} method. This means that if caching fails for any r
```suggestion
In the `install` event handler, we pass the result of the caching operation into the event's {{domxref("ExtendableEvent.waitUntil", "waitUntil()")}} method. This means that if caching fails for any reason, the installation of the service worker fails: conversely, if installation succeeded, the service worker can be sure that the resource was added to the cache.
```

(to make sure readers don't mistake this for the installation of the PWA).

2023-06-28 09:50 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +The drawback of "cache first" is that once a response is in the cache, it is never refreshed until a new version of the app is installed.
```suggestion
The drawback of "cache first" is that once a response is in the cache, it is never refreshed until a new version of the service worker is installed.
```

Sure, new versions of a PWA require a new version of the SW to be installed. But it's possible to just change 1 bit in the SW and the browser will go and fetch it, and install it again. So, I think it's more correct to just talk about the SW here, not the entire app.

2023-06-28 09:50 UTC, captainbrosset commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  if (isCachable(event.request)) {
To get the point across even better, we might want to rename isCachable to something else. Maybe isMessageListRequest.
And then in the function's body, change the test to something else. Maybe something that checks that the URL matches some message API name or something.
This would better match your description above the code snippet.

2023-06-28 09:51 UTC, captainbrosset commented
> I think I've addressed everything except [#27442 (comment)](https://github.com/mdn/content/pull/27442#discussion_r1242490549), which I should probably do but am anxious it will involve a lot of explaining about lifecycles and versions. Maybe I will take a look at that tomorrow.
> 
> Oh, and I should probably add a bit on prefetch?

I've approved this PR, with a few minor comments. I'm fine if you want to do this here in this PR or in a follow-up PR. Feel free to merge now if you want. It's already a useful set of information.

2023-06-28 17:22 UTC, wbamberg commented on files/en-us/web/progressive_web_apps/guides/caching/index.md
> +  if (isCachable(event.request)) {
I've done this slightly differently in https://github.com/mdn/content/pull/27442/commits/dfb782de5464383da286df38728f8a4afd1cdbdd.

2023-06-28 17:23 UTC, wbamberg commented
Thank you! I'm going to merge this, because that should enable me to update the nav, and will try to get to the extra stuff in a follow-up.

2023-06-28 17:24 UTC, merged

2023-06-30 01:51 UTC, hamishwillee commented
@wbamberg Really good final result. Thank you.