docs(learn): point to 'server-side learn pathway' in web server intro
mdn/content pull request #27452
Opened 2023-06-21 07:47 UTC by bsmth

Rewording this paragraph to specify that specialized off-the-shelf solutions exist for web servers, basic intro to server-side learn pathway is next steps.

Fixes #27438

2023-06-21 09:01 UTC, Josh-Cena requested changes

2023-06-21 09:01 UTC, Josh-Cena commented on files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
> +There are many off-the-shelf application server technologies specialized for different purposes, so it's hard to suggest any particular one. Some application servers are designed to host and manage b
Server-side programming uses an application server and builds business logic with it. Here we are suggesting you should not, say, build your own Nginx. I think the OP is looking for guides on these.

2023-06-21 10:02 UTC, bsmth commented on files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
> +There are many off-the-shelf application server technologies specialized for different purposes, so it's hard to suggest any particular one. Some application servers are designed to host and manage b
The original is talking about blogs, wiki and e-commerce, so I would infer it's talking about Wordpress, Shopify etc. without mentioning any.

Let me ask for more info on the issue, but I think this edit is still good as a clean up.

2023-06-23 02:17 UTC, hamishwillee commented on files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
> +There are many off-the-shelf application server technologies specialized for different purposes, so it's hard to suggest any particular one. Some application servers are designed to host and manage b
Yes, much better. The first sentence feels awkward. If we can address the "server from scratch" case it would be good, whether or not we have correctly guessed what the poster wants to achieve from their rant. I think there are two ideas here. Perhaps put into separate paragraphs.

Just a suggestion, but more to my taste because of the structure.

```suggestion
It is impossible to suggest a single off-the-shelf application server that will be the right solution for every possible use case. Some application servers are designed to host and manage blogs, wikis, or e-commerce solutions, while others are more generic. If you're building a dynamic website, take the time to research your requirements and find the technology that best fits your needs.

Most website developers won't need to create an application server from scratch, because there are so many off-the-shelf solutions, many of which are highly configurable.
But if you do need to create your own server, then you will probably want to use a server framework, leveraging its existing code and libraries, and extending just the parts that you need in order to meet your use case.
Only a relatively small number of developers should need to develop a server completely from scratch: for example, in order to meet tight resource constraints on an embedded system.
If you'd like to experiment with building a server, take a look through the resources in the [Server-side website programming](/en-US/docs/Learn/Server-side) learning pathway.
```

2023-06-26 09:05 UTC, bsmth commented on files/en-us/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
> +There are many off-the-shelf application server technologies specialized for different purposes, so it's hard to suggest any particular one. Some application servers are designed to host and manage b
Thanks, Hamish, I've committed your suggestion. No response yet on the original ticket, but I think these changes are good.

2023-06-26 16:26 UTC, Josh-Cena approved these changes
TBH I don't feel like I have enough expertise to say exactly what I want, so I have no intention to block this.

2023-06-27 01:43 UTC, hamishwillee approved these changes
Thanks @bsmth @Josh-Cena .

Let's go with this - it is certainly no worse, and IMO a bit better. If the original poster wants to provide more information we can talk then.

2023-06-27 01:43 UTC, merged