docs(css): Create page for font-feature-settings descriptor of the @font-face rule
mdn/content pull request #27513
Opened 2023-06-23 23:09 UTC by dipikabh

### Description

This PR adds the missing page for the `font-feature-settings` descriptor of the [`@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) rule.
In addition, there are minor edits on other descriptors of `@font-face`.

### Motivation

Interop coverage (https://github.com/mdn/mdn/issues/416)

### Additional details

- Spec: https://drafts.csswg.org/css-fonts/#font-rend-desc
- WPT:
Source: https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/font-feature-settings-descriptor-01.html
Live test: http://wpt.live/css/css-fonts/font-feature-settings-descriptor-01.html

### To dos

- [ ] Update BCD

2023-06-24 05:23 UTC, wbamberg requested changes
Thanks @dipikabh , just a few comments, I hope they are helpful.

2023-06-24 05:23 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +  - : Represents a comma separated list of a string and an optional integer or keyword value. When rendering text, the list of OpenType feature-tag and value are passed to the text layout engine to e
I don't think this is quite right. `<feature-tag-value>` is not a comma-separated list, it's a since item in the comma-separate list that makes up the value: the formal syntax is like `<feature-tag-value>#`, where the `#` denotes that it's a comma-separated list.

So it's more like: `<feature-tag-value>`is a space-separated tuple consisting of a tag name and a value, where the name is a string and the value is one of: an integer 0 or higher, the keyword `"on"`, and the keyword `"off"`.

If we want to talk about the comma-separated value bit (and we should) it might be better to have a para before `### Values` like: "This descriptor is specified as either the keyword `normal` or a comma-separated list of `<feature-tag-value>` values."

2023-06-24 05:23 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +    The optional value is a positive integer or the keyword `on` or `off`. The keywords `on` and `off` are synonyms for `1` and `0`, respectively. If no value is set, the default is `1`. For non-Bool
This is not rendering as 2 paragraphs - I think it might be best to have three paras: one for the overall structure, one for the syntax of the tag name, one for the syntax of the value.

Also it would be good for https://docs.microsoft.com/typography/opentype/spec/features_pt to link to the fragment for that setting, which I think would be https://learn.microsoft.com/en-ca/typography/opentype/spec/features_pt#tag-salt.

Also AFAIK we usually use lowercase "boolean"..

Also I found "the value is a switch" to be a bit obscure. "the value switches the feature on or off" might be clearer?

2023-06-24 05:23 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +### Setting font features in a @font-face rule
Could we have a live sample for this? An easy way to make one might be to use the one for [`font-variant-alternates`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates) but use `font-feature-settings` to switch swashes on instead.

2023-06-26 21:46 UTC, dipikabh commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +  - : Represents a comma separated list of a string and an optional integer or keyword value. When rendering text, the list of OpenType feature-tag and value are passed to the text layout engine to e
That's a good catch! Thanks. I did want to say a comma-separated list of `<feature-tag-value>` values. Thanks for all the other suggestions. I've fixed them. I've also incorporated the changes in the corresponding property [font-feature-settings](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings#values).

2023-06-26 21:47 UTC, dipikabh commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +    The optional value is a positive integer or the keyword `on` or `off`. The keywords `on` and `off` are synonyms for `1` and `0`, respectively. If no value is set, the default is `1`. For non-Bool
Thank you, all valid feedback. I've incorporated the changes.

2023-06-26 21:52 UTC, dipikabh commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +### Setting font features in a @font-face rule
Done! Thanks for the hint. Only thing is that for now (to see the example working), I've copied the montecarlo font file from `font-variant-alternates`. I'll figure out if I can upload the font file to https://github.com/mdn/shared-assets/tree/main/fonts instead.

2023-06-26 22:04 UTC, dipikabh commented
Thanks for the review, @wbamberg! The feedback was certainly helpful and valid. I've also fixed your comments on the related [font-feature-settings](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings#values) property page. Let me know if you think any more changes are required.

2023-06-26 22:56 UTC, wbamberg approved these changes
This looks great, thank you for the updates. I had one wording suggestion, but r+ anyway so you can merge after making the change, if you agree to it.

2023-06-26 22:56 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-feature-settings/index.md
> +    The tag name is always a {{cssxref("&lt;string&gt;")}} of four ASCII characters. If the tag name has more or less characters or if it contains characters outside the `U+20` – `U+7E` code point ra
```suggestion
    The tag name is always a {{cssxref("&lt;string&gt;")}} of four ASCII characters. If the tag name has more or fewer characters or if it contains characters outside the `U+20` – `U+7E` code point range, the descriptor is invalid.
```

(sorry, missed this one last time)

2023-06-27 14:35 UTC, dipikabh commented on files/en-us/web/css/font-feature-settings/index.md
> +    The tag name is always a {{cssxref("&lt;string&gt;")}} of four ASCII characters. If the tag name has more or less characters or if it contains characters outside the `U+20` – `U+7E` code point ra
```suggestion
    The tag name is always a {{cssxref("&lt;string&gt;")}} of four ASCII characters. If the tag name has more or fewer characters or if it contains characters outside the `U+20` – `U+7E` code point range, the descriptor is invalid.
```

2023-06-27 14:37 UTC, merged

2023-06-27 14:37 UTC, dipikabh commented
Thanks, Will!