Initial work on HTML perf doc first draft
mdn/content pull request #27558
Opened 2023-06-26 07:05 UTC by chrisdavidmills

### Description

This PR is intended to improve the HTML and CSS performance docs that sit inside the learning area. Currently, the [CSS doc](https://developer.mozilla.org/en-US/docs/Learn/Performance/CSS) is OK but is missing a few sections, and the [HTML doc](https://developer.mozilla.org/en-US/docs/Learn/Performance/HTML) is just a list of links to other docs with no context, so not very helpful at all. 

### Motivation

### Additional details

### Related issues and pull requests

2023-07-06 14:43 UTC, chrisdavidmills commented
@dipikabh @couci HTML and CSS performance updates now ready to review.

2023-07-07 10:23 UTC, chrisdavidmills commented
@dipikabh @couci HTML and CSS performance updates now ready to review.

2023-07-13 02:53 UTC, dipikabh requested changes
Thanks @chrisdavidmills. This is part 1 review - I've looked at the HTML file.

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +To provide different resolution versions of the same image depending on the device's resolution and viewport size, you can use the `srcset` and `sizes` attributes.
- Should we link them to their MDN pages? 
- Also should it be attributes or properties?

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +`srcset` provides the intrinsic size of the source images along with their filenames, and `sizes` provides media queries alongside image slot widths that need to be filled in each case. The browser t
should 480w.jpg be 480w.jpg?

```suggestion
`srcset` provides the intrinsic size of the source images along with their filenames, and `sizes` provides media queries alongside image slot widths that need to be filled in each case. The browser then decides which images makes sense to load for each slot. As an example, if the screen width is `600px` or less, then `max-width: 600px` is true, and therefore, the slot to fill is said to be `480px`. In this case, the browser will likely choose to load the 480w.jpg file (480px-wide image). This helps with performance because browsers don't load larger images than they need.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +The {{htmlelement("source")}} elements contain media queries inside `media` attributes. If a media query returns true, the image referenced in its `<source>` element's `srcset` attribute is loaded. F
```suggestion
The {{htmlelement("source")}} elements contain media queries inside `media` attributes. If a media query returns true, the image referenced in its `<source>` element's `srcset` attribute is loaded. In the above example, if the viewport width is `799px` or less, the `narrow-banner-480w.jpg` image is loaded. Also note how the `<picture>` element includes an `<img>` element, which provides a default image to load in the case of browsers that don't support `<picture>`.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +> **Note:** note the use of the `srcset` element here. As shown in the previous section, you can provide different resolutions for each different image source.
I don't think this needs to be a note

```suggestion
Note the use of the `srcset` attribute in this example. As shown in the previous section, you can provide different resolutions for each image source.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +- Note how here we are also specifying different video formats inside different `<source>` elements, with each format being identified via its MIME type inside the `type` attribute. Browsers will loa
```suggestion
There are, however, some key differences between providing sources for images and videos:

- In the above example, we are using `src` rather than `srcset`; you can't specify different resolutions for videos via `srcset`.
- Instead, you specify different resolutions inside the different `<source>` elements.
- Note how we are also specifying different video formats inside different `<source>` elements, with each format being identified via its MIME type inside the `type` attribute. Browsers will load the first one they come across that they support, where the media query test returns true.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +You can also lazy load video content, using the `preload` attribute. For example:
```suggestion
You can also lazy load video content by using the `preload` attribute. For example:
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +It is very common for content to be embedded in web pages from other sources. This is most commonly done when displaying advertising on a site to generate revenue — the ads are usually generated by a
```suggestion
It is very common for content to be embedded in web pages from other sources. This is most commonly done when displaying advertising on a site to generate revenue — the ads are usually generated by a third-party company of some kind and embedded onto your page. Other uses might include:
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +- Displaying third party content related to the organization's main site, such as a social media posts feed.
```suggestion
- Displaying third-party content related to the organization's main site, such as a social media posts feed.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +This is most commonly done using {{htmlelement("iframe")}} elements, although other less commonly used embedding elements do exist, such as {{htmlelement("object")}} and {{htmlelement("embed")}}. We'
```suggestion
Embedding content is most commonly done using {{htmlelement("iframe")}} elements, although other less commonly used embedding elements do exist, such as {{htmlelement("object")}} and {{htmlelement("embed")}}. We'll concentrate on `<iframe>`s in this section.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +The most important, and key piece of advice is — "don't use embeded `<iframe>`s unless you absolutely have to". If you are creating a page with multiple different panes of information on it, it might
```suggestion
The most important and key piece of advice for using `<iframe>`s is: "Don't use embedded `<iframe>`s unless you absolutely have to". If you are creating a page with multiple different panes of information on it, it might sound organizationally sensible to break those up into separate pages and load them into different `<iframe>`s. However, this has a number of problems associated with it in terms of performance and otherwise:
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +- Each `<iframe>` would also need to load any shared data and media files in separately — you can't share cached assets across different page embeds (again, unless the embedded pages are from the sam
```suggestion
- Loading the content into an `<iframe>` is much more expensive than loading the content as part of the same direct page — not only does it require extra HTTP requests to load the content, but the browser also needs to create a separate page instance for each one. Each one is effectively a separate web page instance embedded in the top-level web page.
- Following on from the previous point, you'll also need to handle any CSS styling or JavaScript manipulation separately for each different `<iframe>` (unless the embedded pages are from the same origin), which becomes much more complex. You can't target embedded content with CSS and JavaScript applied to the top-level page, or vice versa. This is a sensible security measure that is fundamental to the web. Imagine all the problems you might run into if third-party embedded content could arbitrarily run scripts against any page it was embedded in!
- Each `<iframe>` would also need to load any shared data and media files separately — you can't share cached assets across different page embeds (again, unless the embedded pages are from the same origin). This can lead to a page using much more bandwidth than you might expect.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +> **Note:** If you control the content and it is relatively simple, you could consider using base-64 encoded content in the `src` attribute to populate the `<iframe>`, or even insert raw HTML into th
Can we move this external link to "See also"?

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +#### Lazy loading IFrames
```suggestion
#### Lazy loading iframes
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +  height="400"></iframe>
```suggestion
  height="400">
</iframe>
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +See [It's time to lazy-load offscreen iframes!](https://web.dev/iframe-lazy-loading/) for more information.
Can we move this external link to "See also"?

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +5. The styled result is then painted to the screen.
```suggestion
1. The HTML is generally parsed first, in the order in which it appears on the page.
2. Any found CSS is parsed to understand the styles that need to be applied to the page. During this time, linked assets such as images and web fonts start to be fetched.
3. Any found JavaScript is parsed, evaluated, and run against the page. By default, this blocks parsing of the HTML that appears after the {{htmlelement("script")}} elements that refer to the JavaScript.
4. Slightly later on, the browser works out how each HTML element should be styled, given the CSS applied to it.
5. The styled result is then painted to the screen.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +There are various HTML features that allow you to modify how resource loading happens, to improve performance. We'll explore some of these now.
```suggestion
There are various HTML features that allow you to modify how resource loading happens to improve performance. We'll explore some of these now.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +Parsing and executing JavaScript blocks the parsing of subsequent DOM content, and therefore increases the time to that content being rendered and usable by the users of the page. A small script won'
```suggestion
Parsing and executing JavaScript blocks the parsing of subsequent DOM content. This increases the time for that content to be rendered and be usable by the users of the page. A small script won't make much difference, but consider that modern web applications tend to be very JavaScript-heavy.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +If we put this `<script>` element before the `<p>` element in the source order (for example in the {{htmlelement("head")}} element), the page will throw an error (Chrome for example reports "Uncaught
```suggestion
If we put this `<script>` element before the `<p>` element in the source order (for example, in the {{htmlelement("head")}} element), the page will throw an error (Chrome for example reports "Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')" to the console). This occurs because the script relies on the `<p>` element to work, but at the point the script is parsed, the `<p>` element does not exist on the page. It has not yet been rendered.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +However, this doesn't solve the problem of waiting for the script to load. Better performance can be achieved by adding the `async` attribute to the `<script>` elements:
```suggestion
However, this doesn't solve the problem of waiting for the script to load. Better performance can be achieved by adding the `async` attribute to the `<script>` element:
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +Another JavaScript load handling tip is to split your script up into code modules and load each part when required, rather than putting all your code into one giant script and loading it all to begin
```suggestion
Another JavaScript load handling tip is to split your script up into code modules and load each part when required, instead of putting all your code into one giant script and loading it all at the beginning. This is done using [JavaScript modules](/en-US/docs/Web/JavaScript/Guide/Modules). Read the linked article for a detailed guide.
```

2023-07-13 02:53 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +**Note:** There are other [`rel` values](/en-US/docs/Web/HTML/Attributes/rel) that are also designed to speed up various aspects of page loading, for example `dns-prefetch`, `preconnect`, `moduleprel
```suggestion
> **Note:** You can use `rel="preload"` to preload CSS and JavaScript files as well.

> **Note:** There are other [`rel`](/en-US/docs/Web/HTML/Attributes/rel) values that are also designed to speed up various aspects of page loading: `dns-prefetch`, `preconnect`, `modulepreload`, `prefetch`, and `prerender`. Go to the linked page and find out what they do.
```

2023-07-13 14:01 UTC, chrisdavidmills commented on files/en-us/learn/performance/html/index.md
> +> **Note**: There is an argument to be made for simplifying your HTML structure and [minifying](<https://en.wikipedia.org/wiki/Minification_(programming)>) your source code, so that rendering and dow
Nah, same problem as in the JS perf PR: colon outside the asterisks. Fixed in the next commit!

2023-07-13 14:05 UTC, chrisdavidmills commented on files/en-us/learn/performance/html/index.md
> +To provide different resolution versions of the same image depending on the device's resolution and viewport size, you can use the `srcset` and `sizes` attributes.
I've added links to these attributes. They are definitely attributes. Properties (usually) refer to either CSS properties, or properties or a JavaScript object.

2023-07-13 14:08 UTC, chrisdavidmills commented on files/en-us/learn/performance/html/index.md
> +> **Note:** If you control the content and it is relatively simple, you could consider using base-64 encoded content in the `src` attribute to populate the `<iframe>`, or even insert raw HTML into th
I don't think it is important or useful enough to stand alone as a link. But it is quite useful in context here.

2023-07-14 17:46 UTC, dipikabh requested changes
Finished looking at the CSS file :). Thanks for adding all this content, @chrisdavidmills! It is a major improvement to the sparse pages.

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +
Can we add an H3 here, something like "Considering properties to animate"? There's currently only one H3 under "Handling animations"

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +To further improve performance, animation work can be moved off the main thread and onto the device's GPU (also referred to as compositing). Elements whose animation will be moved onto the GPU includ
Do developers need to do something to move the animations to the GPU? There's both "can be" and "will be"

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +- Certain elements that are rendered in their own layer, including [`<video>`](/en-US/docs/Web/HTML/Element/video), [`<canvas>`](/en-US/docs/Web/HTML/Element/canvas) and [`<iframe>`](/en-US/docs/Web/
```suggestion
- Those animated with 3D transforms such as [`transform: translateZ()`](/en-US/docs/Web/CSS/transform) and [`rotate3d()`](/en-US/docs/Web/CSS/transform-function/rotate3d).
- Those with certain other properties animated such as [`position: fixed`](/en-US/docs/Web/CSS/position).
- Those with [`will-change`](/en-US/docs/Web/CSS/will-change) applied (see the section below).
- Certain elements that are rendered in their own layer, including [`<video>`](/en-US/docs/Web/HTML/Element/video), [`<canvas>`](/en-US/docs/Web/HTML/Element/canvas), and [`<iframe>`](/en-US/docs/Web/HTML/Element/iframe).
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +Animation on the GPU can result in improved performance, especially on mobile. However, as with many things in life, it is not always that simple. Read [CSS GPU Animation: Doing It Right](https://www
we're getting philosophical :)

```suggestion
Animation on the GPU can result in improved performance, especially on mobile. However, moving animations to GPU is not always that simple. Read [CSS GPU Animation: Doing It Right](https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/) (smashingmagazine.com, 2016) for a very useful and detailed analysis.
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +The CSS [`will-change`](/en-US/docs/Web/CSS/will-change) property hints to browsers how an element is expected to change. Browsers may set up optimizations before an element is actually changed. Thes
- Changing the order of sentences here - I think this is the intended flow of thought, not sure though if it is correct. - I think another sentence is needed here at the end to say how `will-change` can help with this - '...so the browser will not perform pre-optimization'?

```suggestion
Browsers may set up optimizations before an element is actually changed. These kinds of optimizations can increase the responsiveness of a page by doing potentially expensive work before it is required. The CSS [`will-change`](/en-US/docs/Web/CSS/will-change) property hints to browsers how an element is expected to change. 
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
>  Browsers are optimized to handle CSS animations, and handle animating properties that do not trigger a reflow (and therefore also a repaint) very well. To improve performance, the node being animated
should this section be deleted since now this is covered under "Handling animations"?

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +In general, think carefully about the fonts you use on your site. Some font files can be very large (multiple megabytes). While it can be tempting to use lots of fonts for visual excitment, this can
```suggestion
In general, think carefully about the fonts you use on your site. Some font files can be very large (multiple megabytes). While it can be tempting to use lots of fonts for visual excitement, this can slow down loading significantly and cause your site to look like a mess. You probably only need about two or there fonts, and you could get away with less if you choose to use [web safe fonts](/en-US/docs/Learn/CSS/Styling_text/Fundamentals#web_safe_fonts).
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +It can therefore be benefitical to use `rel="preload"` to load important fonts early, so they will be available more quickly when they are actually needed:
```suggestion
It can therefore be beneficial to use `rel="preload"` to load important fonts early, so they will be available more quickly when they are actually needed:
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +- Using the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API) to customize your font loading behavior via JavaScript.
```suggestion
This is more likely to be beneficial if your `font-family` declaration is hidden inside a large external stylesheet, and won't be reached until significantly later in the parsing process. It is a tradeoff however — font files are quite large, and if you preload too many of them, you may delay other resources.

You can also consider:

- Using [`rel="preconnect"`](/en-US/docs/Web/HTML/Attributes/rel/preconnect) to make an early connection with the font provider. See [Preconnect to critical third-party origins](https://web.dev/font-best-practices/#preconnect-to-critical-third-party-origins) for details.
- Using the [CSS Font Loading API](/en-US/docs/Web/API/CSS_Font_Loading_API) to customize the font loading behavior via JavaScript.
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +However, if you know you are going to use a specific set of glyphs (for example in headings, or spercific punctuation characters only), you could limit the number of glyphs the browser has to downloa
```suggestion
### Loading only the glyphs you need

When choosing a font for body copy, it is harder to be sure of the glyphs that will be used in it, especially if you are dealing with user-generated content and/or content across multiple languages.

However, if you know you are going to use a specific set of glyphs (for example, glyphs for headings or specific punctuation characters only), you could limit the number of glyphs the browser has to download. This could be done in a brute-force way by creating a font file that only contains the required subset.
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +The [CSS containment](/en-US/docs/Web/CSS/CSS_containment) module aims to provide performance improvements by allowing the browser to isolate parts of the page from one another and make optimizations
```suggestion
By using the properties defined in the [CSS containment](/en-US/docs/Web/CSS/CSS_containment) module, you can enable the browser to isolate different parts of a page and optimize their rendering independently from one another. This allows for improved performance in rendering individual sections. As an example, you can specify to the browser to not render parts until they are visible in the viewport.
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +This causes the intial page load to be much faster.
moving this up to previous para
```suggestion

```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +A second property, {{cssxref("contain-intrinsic-size")}}, is also available, which allows you to provide a placeholder size for the containers while they are under the effects of containment. This me
```suggestion
A second property, {{cssxref("contain-intrinsic-size")}}, is also available, which allows you to provide a placeholder size for the containers while they are under the effects of containment. This means that the containers will take up space even if their contents have not yet been renderered, allowing containment to do its performance magic without the risk of scroll bar shift and jank as elements render and come into view. This makes the initial page load to be much faster.
```

2023-07-14 17:46 UTC, dipikabh commented on files/en-us/learn/performance/html/index.md
> +To do this, you need to [measure the performance](/en-US/docs/Learn/Performance/Measuring_performance) of your site. As the previous link shows, there are several different ways to measure performanc
```suggestion
To do this, you need to [measure the performance](/en-US/docs/Learn/Performance/Measuring_performance) of your site. As this link shows, there are several different ways to measure performance, some involving sophisticated [performance APIs](/en-US/docs/Web/API/Performance_API/). The best way to get started, however, is to learn how to use tools such as built-in browser [network](/en-US/docs/Learn/Performance/Measuring_performance#network_monitor_tools) and [performance](/en-US/docs/Learn/Performance/Measuring_performance#performance_monitor_tools) tools, to examine the parts of the page that are taking a long time to load and need optimizing.
```

2023-07-15 12:33 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +  The above example provides default styles, styles that will only be loaded when the document is being printed, and styles that will be loaded only by devices with narrow screens. By default, the br
I've handled this, but in a different way

2023-07-15 12:36 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +When developing a website, it is important to consider how the browser is handling your CSS, and optimize it to mitigate any performance issues that it is causing. For example, you should optimize fo
updated

2023-07-15 12:39 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +      </td>
updated, on both articles.

2023-07-15 12:41 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +
No, I think it's OK without.

2023-07-15 12:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +
No; the current first section fits first in terms of info progression. I think I'll link to a definition on first mention.

2023-07-15 13:55 UTC, chrisdavidmills commented on files/en-us/learn/performance/html/index.md
Yes; done.

2023-07-15 13:56 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +- **Remove unnecessary styles**: This may sound obvious, but it is surprising how many developers forget to clean up rules and declarations that were added in their stylesheets during development and
Updated

2023-07-15 13:58 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +- **Minify and compress your CSS**: Loading times can be reduced by minifying your CSS (meaning removing all the whitespace in the file that is only there for human readability), and making sure that
Updated

2023-07-15 14:12 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +Next, animation performance relies heavily on what properties you are animating. Certain properties, when animated, trigger a reflow (and therefore also a repaint) and should be avoided. These includ
I've linked reflow and repaint to glossary entries

2023-07-15 14:25 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +
Good call; I've gone with "Choosing which properties to animate"

2023-07-15 14:35 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +To further improve performance, animation work can be moved off the main thread and onto the device's GPU (also referred to as compositing). Elements whose animation will be moved onto the GPU includ
I've rewritten the paragraph to provide an explanation:

> To further improve performance you should consider moving animation work off the main thread and onto the device's GPU (also referred to as compositing). This is done by choosing specific types of animations that the browser will automatically send to the GPU to handle; these include:

2023-07-15 14:37 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
>  Browsers are optimized to handle CSS animations, and handle animating properties that do not trigger a reflow (and therefore also a repaint) very well. To improve performance, the node being animated
Ack, I meant to delete this, then forgot. Removed now!

2023-07-15 14:41 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +In general, think carefully about the fonts you use on your site. Some font files can be very large (multiple megabytes). While it can be tempting to use lots of fonts for visual excitment, this can
updated

2023-07-15 14:42 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +The [CSS containment](/en-US/docs/Web/CSS/CSS_containment) module aims to provide performance improvements by allowing the browser to isolate parts of the page from one another and make optimizations
updated

2023-07-15 14:45 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +A second property, {{cssxref("contain-intrinsic-size")}}, is also available, which allows you to provide a placeholder size for the containers while they are under the effects of containment. This me
updated

2023-07-15 14:49 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +
This is because the code example `<div>`s have no top margin set on them. We could perhaps consider adding a rule along the lines of `li > .code-example { margin-top: 2rem }` to fix it, so it doesn't affect code blocks except when they are inside list items.

2023-07-15 14:52 UTC, chrisdavidmills commented
@dipikabh thanks so much for all the great comments; they should all be answered now.

2023-07-17 15:10 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +
Thanks

2023-07-17 15:36 UTC, dipikabh approved these changes
Thank you, @chrisdavidmills. The updates are looking good. Just very few nits but this is good to go. Leaving a +1, please feel free to merge.

2023-07-17 15:36 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +To further improve performance you should consider moving animation work off the main thread and onto the device's GPU (also referred to as compositing). This is done by choosing specific types of an
```suggestion
To further improve performance, you should consider moving animation work off the main thread and onto the device's GPU (also referred to as compositing). This is done by choosing specific types of animations that the browser will automatically send to the GPU to handle; these include:
```

2023-07-17 15:36 UTC, dipikabh commented on files/en-us/learn/performance/css/index.md
> +- 3D transform animations (for example [`transform: translateZ()`](/en-US/docs/Web/CSS/transform) and [`rotate3d()`](/en-US/docs/Web/CSS/transform-function/rotate3d)).
```suggestion
- 3D transform animations such as [`transform: translateZ()`](/en-US/docs/Web/CSS/transform) and [`rotate3d()`](/en-US/docs/Web/CSS/transform-function/rotate3d)).
```
to keep the style of presenting examples similar across bullet points

2023-07-17 19:37 UTC, dipikabh approved these changes
I had missed looking at the Glossary pages. Minor updates needed.

2023-07-17 19:37 UTC, dipikabh commented on files/en-us/glossary/reflow/index.md
> +- [Understanding Reflow and Repaint in the browser](https://dev.to/gopal1996/understanding-reflow-and-repaint-in-the-browser-1jbg) on dev.to, 2020
```suggestion
- [Understanding Reflow and Repaint in the browser](https://dev.to/gopal1996/understanding-reflow-and-repaint-in-the-browser-1jbg) on dev.to (2020)
```

2023-07-17 19:37 UTC, dipikabh commented on files/en-us/glossary/render_blocking/index.md
> +**Render-blocking** refers to any part of the process of loading a website when it blocks the rendering of the user interface. Render-blocking is bad for web performance because it increases the leng
```suggestion
**Render-blocking** refers to any part of the process of loading a website when it blocks the rendering of the user interface. Render-blocking is bad for web performance because it increases the length of time until users can interact with the site. This can mean increased time before users can view the site content or interact with controls.
```

2023-07-17 19:37 UTC, dipikabh commented on files/en-us/glossary/render_blocking/index.md
> +- [What Are Render-Blocking Resources & How to Fix Render Blocking Issues](https://speckyboy.com/render-blocking/), Speckyboy, 2018
```suggestion
- [What Are Render-Blocking Resources & How to Fix Render Blocking Issues](https://speckyboy.com/render-blocking/) on Speckyboy (2018)
```

2023-07-17 19:37 UTC, dipikabh commented on files/en-us/glossary/repaint/index.md
> +- [Understanding Reflow and Repaint in the browser](https://dev.to/gopal1996/understanding-reflow-and-repaint-in-the-browser-1jbg) on dev.to, 2020
```suggestion
- [Understanding Reflow and Repaint in the browser](https://dev.to/gopal1996/understanding-reflow-and-repaint-in-the-browser-1jbg) on dev.to (2020)
```

2023-07-20 08:45 UTC, chrisdavidmills commented on files/en-us/glossary/render_blocking/index.md
> +**Render-blocking** refers to any part of the process of loading a website when it blocks the rendering of the user interface. Render-blocking is bad for web performance because it increases the leng
"increases the length of time" ... "increased time" felt a bit repetitious. I've handled this a different way.

2023-07-20 08:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +- 3D transform animations (for example [`transform: translateZ()`](/en-US/docs/Web/CSS/transform) and [`rotate3d()`](/en-US/docs/Web/CSS/transform-function/rotate3d)).
updated

2023-07-20 08:48 UTC, chrisdavidmills commented on files/en-us/learn/performance/css/index.md
> +### Choosing which properties to animate
I've gone for just "Choosing properties to animate"

2023-07-20 08:58 UTC, merged

2023-07-20 08:59 UTC, chrisdavidmills commented
@dipikabh and another one merged! Thanks!