docs(API): remove list of IDB tools, point to storage APIs instead
mdn/content pull request #27565
Opened 2023-06-26 16:09 UTC by bsmth

This PR removes a list of tools relating to IndexedDB, and prefers internal links to related concepts. The rationale for removal is that the external tools and libraries are difficult to maintain, especially when it comes to assessing and assuring quality for our readers.

2023-06-26 16:32 UTC, wbamberg requested changes
Great PR, but I had some comments about using the js13kGames tutorial :).

2023-06-26 16:32 UTC, wbamberg commented on files/en-us/web/performance/fundamentals/index.md
> +On the same note, notice that locally-cached, static resources can be loaded much faster than dynamic data fetched over high-latency, low-bandwidth mobile networks. Network requests should never be o
Let's not link to the js13kGames tutorial as it is about to be retired or at least greatly rewritten.

We could link to https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Offline_and_background_operation, or we could hold this PR until https://github.com/mdn/content/pull/27442 lands.

2023-06-26 16:32 UTC, wbamberg commented on files/en-us/web/performance/index.md
> +- [PWA](/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers)
Same.

2023-06-26 16:32 UTC, wbamberg commented on files/en-us/web/api/indexeddb_api/index.md
> +- Combine IndexedDB for storing data offline with Service Workers for storing assets offline, as outlined in [Making PWAs work offline with Service workers](/en-US/docs/Web/Progressive_web_apps/Tutor
The js13kGames doesn't use IndexedDB. I think all we can do here is remove this bullet.

2023-06-27 15:07 UTC, bsmth commented on files/en-us/web/api/indexeddb_api/index.md
> +- Combine IndexedDB for storing data offline with Service Workers for storing assets offline, as outlined in [Making PWAs work offline with Service workers](/en-US/docs/Web/Progressive_web_apps/Tutor
Done in https://github.com/mdn/content/pull/27565/commits/9ad1ab3890d829d7b5a36837afabaeef3a295e47

2023-06-27 15:07 UTC, bsmth commented on files/en-us/web/performance/index.md
> +- [PWA](/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers)
Done in https://github.com/mdn/content/pull/27565/commits/9ad1ab3890d829d7b5a36837afabaeef3a295e47

2023-06-27 15:07 UTC, bsmth commented on files/en-us/web/performance/fundamentals/index.md
> +On the same note, notice that locally-cached, static resources can be loaded much faster than dynamic data fetched over high-latency, low-bandwidth mobile networks. Network requests should never be o
I think it's a good idea to link to 'Offline and background operation' here, adding that.

2023-06-28 07:22 UTC, wbamberg approved these changes
👍 thank you!

2023-06-28 07:22 UTC, merged