New module: CSS cascade module
mdn/content pull request #27588
Opened 2023-06-27 07:49 UTC by estelle

Module page did not exist. So, created it.

Fixes https://github.com/openwebdocs/project/issues/165

2023-07-07 23:03 UTC, dipikabh commented
Sorry for the delay on this, @estelle. Taking a look now.

2023-07-07 23:29 UTC, dipikabh requested changes

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +The **CSS cascade and inheritance** module defines the rules for assigning property values, cascading, and inheritance. This module specifies the rules for finding the specified value for all propert
how about slight rephrasing to show the relationship

```suggestion
The **CSS cascade and inheritance** module defines the rules for assigning values to properties by way of cascading and inheritance. This module specifies the rules for finding the specified value for all properties on all elements.
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +One of the fundamental design principles of CSS is cascading, which allows several style sheets to influence the presentation of a document. CSS property-value declarations define how a document is r
```suggestion
One of the fundamental design principles of CSS is cascading of rules. It allows several style sheets to influence the presentation of a document. CSS property-value declarations define how a document is rendered. Multiple declarations may set different values for the same element and property combination, but only one value can be applied to any CSS property. The CSS cascade module defines how these conflicts are resolved.
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +### at-rules
```suggestion
### At-rules
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +- [Cascade origin and importance](/en-US/docs/Web/CSS/Cascade)
These need to be covered under "Related concepts" or "Guides" section below.
- "Cascade origin and importance" is getting covered under "Guides" by "Introducing the CSS Cascade"
- "Specificity" can be moved to "Guides"

```suggestion

```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +  - [quthor origin](/en-US/docs/Web/CSS/Cascade#author_stylesheets)
```suggestion
  - [author origin](/en-US/docs/Web/CSS/Cascade#author_stylesheets)
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +- [CSS page module](/en-US/docs/Web/CSS/CSS_paged_media)
```suggestion
- [CSS paged media module](/en-US/docs/Web/CSS/CSS_paged_media)
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +### Definitions
Can we remove this section and move all its content to the "Related concepts" section - for consistency with other module landing pages

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +  - : Guide to the cascade algorithm that defines how user agents combine property values originating from different sources
```suggestion
  - : Guide to the cascade algorithm that defines how user agents combine property values originating from different sources.
```

2023-07-07 23:29 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +  - : A guide to CSS inheritance
```suggestion
  - : A guide to CSS inheritance.
```

2023-07-10 01:30 UTC, estelle commented on files/en-us/web/css/css_cascade/index.md
> +- [Cascade origin and importance](/en-US/docs/Web/CSS/Cascade)
moved important to keywords and the two others to definitions.

2023-07-10 01:30 UTC, estelle commented on files/en-us/web/css/css_cascade/index.md
> +### Definitions
these aren't "related". They're in this spec.

2023-07-10 23:40 UTC, dipikabh approved these changes
Leaving two questions for your consideration and also a +1 as it is in good shape overall. Thank you!

2023-07-10 23:40 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +### Keywords
Should we call this section "Keyword values" to be more specific

2023-07-10 23:40 UTC, dipikabh commented on files/en-us/web/css/css_cascade/index.md
> +### Definitions
How about calling this section "Key concepts"?

2023-07-10 23:45 UTC, estelle commented on files/en-us/web/css/css_cascade/index.md
> +### Definitions
```suggestion
### Key concepts and definitions
```

2023-07-10 23:45 UTC, merged