New pages: CSS selectors and combinators and CSS selector structure
mdn/content pull request #27601
Opened 2023-06-27 18:55 UTC by estelle

Two new pages:
* CSS selectors and combinators 
* CSS selector structure

Along with link updates to CSS_selectors and those two pages.

Part of the larger project - https://github.com/openwebdocs/project/issues/164

2023-06-29 05:30 UTC, yarusome commented
It could be helpful to explicitly mention that characters can be escaped by using backslashes (see [spec](https://www.w3.org/TR/selectors/#case-sensitive)). This usually happens when class names or attribute names contain special characters such as `#`, `.`, and `>`, with a recent example from mdn/yari#9177.

2023-06-29 20:09 UTC, estelle commented
> It could be helpful to explicitly mention that characters can be escaped by using backslashes (see [spec](https://drafts.csswg.org/selectors/#case-sensitive)). This usually happens when class names or attribute names contain special characters such as `#`, `.`, and `>`, with a recent example from [mdn/yari#9177 (comment)](https://github.com/mdn/yari/issues/9177#issuecomment-1609340251).

We definitely need to include this information in the attribute and class selector pages. These pages provide a brief  overview to the selector types, without implementation details

2023-07-07 02:15 UTC, dipikabh commented
Taking a look at this now

2023-07-07 04:05 UTC, dipikabh requested changes
Thanks, @estelle! I've done a quick readthrough. 

- The [CSS selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) page would need to be updated as well to mention it as a module. Also, it does not appear in the Modules drop-down in the side bar.
- The structure of a selector was also covered here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#structure_of_a_selector. We should remove this section to avoid duplication of information.

2023-07-07 06:30 UTC, estelle commented
> Thanks, @estelle! I've done a quick readthrough.
> 
> * The [CSS selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) page would need to be updated as well to mention it as a module. Also, it does not appear in the Modules drop-down in the side bar.
> * The structure of a selector was also covered here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#structure_of_a_selector. We should remove this section to avoid duplication of information.

This is part of a much larger project. I am completely rewriting the CSS selectors module page (part of the module project), but those pages aren't all done and I don't want to subject anyone to a behemoth of a PR. https://github.com/mdn/content/pull/27590

I mentioned it at the last SC meeting, but I should have added it to all the PRs as not all reviewers attend our content meetings.

2023-07-07 06:31 UTC, estelle commented on files/en-us/web/css/css_selectors/selector_structure/index.md
> +- [CSS pseudo-elements module](/en-US/docs/Web/CSS/CSS_pseudo)
this link is created in https://github.com/mdn/content/pull/27590/. There are now two modules: selectors and pseudo.

2023-07-07 06:38 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +The [CSS selector module](/en-US/docs/Web/CSS/CSS_selectors) defines over 60 [pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes). Pseudo-classes are [simple selectors](#simple-selector), prefixed wi
it will be. These two new pages are sub pages of the new CSS Selectors module landing page.

2023-07-07 06:40 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +- [CSS Specificity](/en-US/docs/Web/CSS/Specificity)
That page is being rewritten.

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selector_structure/index.md
> +These selectors can be combined into a comma-separated [selector list](#selector-list). If any selector in a [non-forgiving selector](/en-US/docs/Web/CSS/Selector_list##valid_and_invalid_selector_lis
people don't get this. Want to include it here in case people don't actually read on.

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +* {
this is a quick overview to get people to sub pages, not an in-depth guide.

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +## Combinators
prefer original

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +h2 + p ~ p {
In this example, they're all simple selectors combined with combinators....

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +> **Note:** In contrast to pseudo-elements, {{CSSxRef("pseudo-classes")}} can be used to style an element based on its _state_.
it's the next line, so i think it's ok to keep here, and i prefer to keep here as it's regarding what you can do with pseudo-classes not elements, so better here.

2023-07-07 06:48 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +Not all CSS selectors are defined in the [CSS selectors module](/en-US/docs/Web/CSS/). CSS pseudo-element selectors are defined in a [CSS pseudo-element module](/en-US/docs/Web/CSS/CSS_pseudo).
this is (or will be) correct

2023-07-07 21:52 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +* {
Okay

2023-07-07 22:00 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +> **Note:** In contrast to pseudo-elements, {{CSSxRef("pseudo-classes")}} can be used to style an element based on its _state_.
We don't say what pseudo-elements can be used for in comparison (and we can't here because they're in the next section). The fact that pseudo-classes can be used to select elements based on their state is already mentioned in the definition. I'm wondering if we need this note here at all.

2023-07-07 22:01 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +
I guess we can remove this section because we're not displaying the BCD info?

2023-07-07 22:09 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/page_type_key/index.md
> +- `css-selector`: a [basic selector](/en-US/docs/Web/CSS/CSS_Selectors/Selectors_and_combinators#basic_selectors), like the [class selector](/en-US/docs/Web/CSS/Class_selectors).
```suggestion
- `css-selector`: a [basic selector](/en-US/docs/Web/CSS/CSS_selectors/Selectors_and_combinators#basic_selectors), like the [class selector](/en-US/docs/Web/CSS/Class_selectors).
```

2023-07-07 22:09 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selector_structure/index.md
> +- [CSS pseudo-elements module](/en-US/docs/Web/CSS/CSS_pseudo)
Ah! I get it now 👍

2023-07-07 22:31 UTC, dipikabh requested changes
Thanks @estelle, I went through your responses and resolved a few comments. There's still a few minor edits remaining to be committed from the previous review. I added 2 more minor link updates in this round.
Additionally - I left a comment about a note that could be removed, a BCD section that can be removed, and [a question](https://github.com/mdn/content/pull/27601#discussion_r1255205327) about if we want to add multiple values for the spec-urls key.

2023-07-07 22:31 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selector_structure/index.md
> +- [CSS pseudo-elements module](/en-US/docs/Web/CSS/CSS_pseudo)
```suggestion
- [CSS pseudo-elements](/en-US/docs/Web/CSS/CSS_pseudo) module
```

2023-07-07 22:31 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +Not all CSS selectors are defined in the [CSS selectors module](/en-US/docs/Web/CSS/). CSS pseudo-element selectors are defined in a [CSS pseudo-element module](/en-US/docs/Web/CSS/CSS_pseudo).
In that case, my previous edit here was incorrect. It should be:

```suggestion
Not all CSS selectors are defined in the [CSS selectors module](/en-US/docs/Web/CSS/). CSS pseudo-element selectors are defined in the [CSS pseudo-elements](/en-US/docs/Web/CSS/CSS_pseudo) module.
```

2023-07-07 22:31 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +The [CSS selector module](/en-US/docs/Web/CSS/CSS_selectors) defines over 60 [pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes). Pseudo-classes are [simple selectors](#simple-selector), prefixed wi
Maybe this suggestion got missed

2023-07-07 22:31 UTC, dipikabh commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +- [CSS Specificity](/en-US/docs/Web/CSS/Specificity)
The casing in the slug would still need an update here

2023-07-07 23:03 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +
this is really weird. I added all of these to the batch yesterday, several times, but it didn't take. I thought it had. It showed that it had. All of these I am now committing i thought i committed yesterday. There must be a ghost in my laptop.

2023-07-07 23:06 UTC, estelle commented on files/en-us/web/css/css_selectors/selectors_and_combinators/index.md
> +> **Note:** In contrast to pseudo-elements, {{CSSxRef("pseudo-classes")}} can be used to style an element based on its _state_.
```suggestion
The [CSS selectors](/en-US/docs/Web/CSS/CSS_selectors) module defines over 60 [pseudo-classes](/en-US/docs/Web/CSS/Pseudo-classes). Pseudo-classes are [simple selectors](#simple-selector), prefixed with a colon (`:`), that allow the selection of elements based on state information that is not contained in the document tree. {{CSSxRef("pseudo-classes")}} can be used to style an element based on its _state_.
For example, the {{cssxref(":target")}} simple selector targets element of a URL containing a fragment identifier, and the [`a:visited`](/en-US/docs/Web/CSS/:visited) [compound selector](/en-US/docs/Web/CSS/CSS_Selectors/Selector_structure#compound_selector) matches all {{HTMLElement("a")}} elements that have been visited by a user.

The pseudo-classes can be categorized as [element display state](/en-US/docs/Web/CSS/Pseudo-classes#element_display_state_pseudo-classes), [input](/en-US/docs/Web/CSS/Pseudo-classes#input_pseudo-classes), [linguistic](/en-US/docs/Web/CSS/Pseudo-classes#linguistic_pseudo-classes), [location](/en-US/docs/Web/CSS/Pseudo-classes#location_pseudo-classes), [resource state](/en-US/docs/Web/CSS/Pseudo-classes#resource_state_pseudo-classes), [time-dimensional](/en-US/docs/Web/CSS/Pseudo-classes#time-dimensional_pseudo-classes), [tree-structural](/en-US/docs/Web/CSS/Pseudo-classes#tree-structural_pseudo-classes), [user action](/en-US/docs/Web/CSS/Pseudo-classes#user_action_pseudo-classes), and [functional](/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes).

Multiple pseudo-classes can be combined to create [compound selectors](#compound-selector). When combining a pseudo-class into a compound selector with a type or universal selector, the pseudo-class must follow the type selector or universal selector, if present.
```

2023-07-07 23:08 UTC, estelle commented
Really weird. A bunch of edits that I was confident I committed yesterday, and didn't show in this stream, were not committed. Not sure what happened. Apologies for having you review an only partially reviewed PR. This stream is now showing that there are no unresolved commits. I hope that sticks.

2023-07-10 23:34 UTC, dipikabh commented
> Really weird. A bunch of edits that I was confident I committed yesterday, and didn't show in this stream, were not committed. Not sure what happened. Apologies for having you review an only partially reviewed PR. This stream is now showing that there are no unresolved commits. I hope that sticks.

Oh! No worries, I think it all looks good now. Thanks for attending to the remaining ones!

2023-07-10 23:34 UTC, dipikabh approved these changes

2023-07-10 23:34 UTC, merged