Implementation of action.getUserSettings
mdn/content pull request #27608
Opened 2023-06-27 23:44 UTC by rebloor

### Description

Add documentation for changes made in [Bug 1814905](https://bugzilla.mozilla.org/show_bug.cgi?id=1814905) Implement chrome.action.getUserSettings

2023-06-27 23:45 UTC, rebloor commented
FYI @gregorypappas

2023-06-28 02:43 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the browser action's icon is visible on the browser window's top-level toolbar (i.e., whether the extension has been 'pinned' by the user).
Hmm...Not sure this description is totally accurate. I don't have a suggestion for what it should say exactly, but can offer you some notes on how this property works:

- isOnToolbar communicates the user's intent, not necessarily whether the action button is visible or not. For example, a user can pin the action icon, then resize the browser window to be so small that the widget overflows back into the extensions panel and therefore stops being visible. I believe this is the correct behavior. Firefox and Chromium are identical in this regard.   
- Firefox in particular has multiple toolbars where the user may place the widget. The action widget may be placed in the area where tabs are located (`tabstrip`), in the area where the address bar and navigation buttons are located (`navbar`), or in the area where bookmarks are located (`personaltoolbar`). If a user places the action widget in the personaltoolbar, and the personaltoolbar is configured to only show on new tabs, the action widget will be invisible most of the time. Nonetheless, `isOnToolbar` will be `true`.

2023-06-28 04:02 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the browser action's icon is visible on the browser window's top-level toolbar (i.e., whether the extension has been 'pinned' by the user).
Thanks, @gregorypappas. So, arguably this property is poorly named as what it's telling you whether the extension's action icon has been pinned to the toolbar, not whether it's visible or "on" for toolbas. `isPinnedToToolbar` might have been a better name. Updating the text.

2023-06-28 04:25 UTC, gregorypappas reviewed
lgtm!

2023-06-28 04:29 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the browser action's icon is visible on the browser window's top-level toolbar (i.e., whether the extension has been 'pinned' by the user).
> This property is poorly named 

Definitely.

> `isPinnedToToolbar` might have been a better name. 

Agreed. Unfortunately we have to stick with the current name for compat reasons.

2023-06-28 09:19 UTC, Rob--W requested changes

2023-06-28 09:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +let gettingUserSettings = await browser.action.getUserSettings()
```suggestion
let userSettings = await browser.action.getUserSettings();
```

The "gettingXXX" convention is strange, but used to refer to a Promise. In this case, we have a concrete return value.

2023-06-28 09:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +  if (settings.isOnToolbar) {
```suggestion
function gotSettings(userSettings) {
  if (userSettings.isOnToolbar) {
```

Using the same names as the documentation for clarity.

2023-06-28 09:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +> **Note:** This API is based on Chromium's [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/#method-getTitle) API. This documentation is derived from [`browser_action.
```suggestion
> **Note:** This API is based on Chromium's [`chrome.action`](https://developer.chrome.com/docs/extensions/reference/action/#method-getUserSettings) API.
```

1. browserAction doesn't have this method.
2. Link should point to getUserSettings.

2023-06-28 09:19 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the browser action's icon to the browser's toolbar.
Could you also add an extra sentence to clarify that the value being true doesn't necessarily imply that it's visible?

- some popup windows don't show an action button
- small windows don't have enough space to show a button
- Firefox-specific: like Greg mentioned, the button may be placed in an area that is not always visible. See `default_area` at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/action

2023-06-28 10:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the browser action's icon to the browser's toolbar.
@Rob--W I'm wondering whether this is the right place to explain the pinned behavior of the action button. I am thinking it make more sense to update https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_action and add a link?

2023-06-28 11:07 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the browser action's icon to the browser's toolbar.
Sounds good to me!

2023-07-04 04:16 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the browser action's icon to the browser's toolbar.
@Rob--W after looking into the idea of updating the user interface article, the differences between Firefox, Chrome, and Safari are such that I don't think it's a small project. Therefore updated this with some generic language, which is hopefully OK, and will raise a separate issue with regard to the UI section content.

2023-07-05 10:05 UTC, gregorypappas commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the action's icon to the chrome. This setting does not indicate whether the action icon is visible in the chrome. The icon's visibility depends on the
The use of the term chrome here is correct, but will this potentially confuse readers? Do most people know that chrome refers to the browser UI? I will defer to @Rob--W on this

2023-07-12 11:35 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the action's icon to the chrome. This setting does not indicate whether the action icon is visible in the chrome. The icon's visibility depends on the
Let's use "browser's toolbar" rather than "chrome". They're both slightly vague, but "toolbar" is not that ambiguous and already part of the API name.

2023-07-12 11:38 UTC, Rob--W approved these changes
I expect that follow-ups to my feedback are straightforward and don't need another review, so I'll already sign off.

2023-07-14 16:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/action/getusersettings/index.md
> +      - : `boolean`. Whether the user has pinned the action's icon to the chrome. This setting does not indicate whether the action icon is visible in the chrome. The icon's visibility depends on the
```suggestion
      - : `boolean`. Whether the user has pinned the action's icon to the browser UI. This setting does not indicate whether the action icon is visible. The icon's visibility depends on the size of the browser window and the layout of the browser UI.
```

2023-07-14 16:57 UTC, rebloor commented
Thanks @Rob--W I settled for "browse UI" given that in Firefox the icon can be placed in UI areas that aren't strictly a "toolbar"

2023-07-14 17:02 UTC, merged