Added Note for the synchoronous Nature of the Web Storage API
mdn/content pull request #27699
Opened 2023-07-01 18:55 UTC by Biki-das

Fix #27686

I have added the info as a Note, if anyone feels they have a better way to add this , please let me know

cc @Josh-Cena

2023-07-03 07:54 UTC, Biki-das commented
@Josh-Cena please review!

2023-07-03 08:01 UTC, Josh-Cena commented
Sorry I'm not a WebAPI reviewer. You can just wait for your assigned reviewer.

2023-07-04 06:29 UTC, Biki-das commented
@Elchi3 please review!

2023-07-04 07:48 UTC, Biki-das commented
@teoli2003 could you give some feedback on this?

2023-07-04 07:51 UTC, Josh-Cena commented
Please stop pinging people. Reviewers have priorities and they will get to yours when they have time.

2023-07-04 08:08 UTC, Biki-das commented
> Please stop pinging people. Reviewers have priorities and they will get to yours when they have time.

😅sorry !

2024-03-11 13:51 UTC, bsmth requested changes
Thank you! A couple of comments:

* Let's move this to line 31 before the first note
* There are too many note blocks in a row here, let's use regular (2 or 3) paras.
* Consistently use backticks for `localStorage` etc.

2024-03-11 13:52 UTC, Biki-das commented
@bsmth thanks for dropping the review, i will apply the requested changes as required

2024-03-11 14:19 UTC, Biki-das commented
@bsmth  updated with the new changes

2024-03-11 16:03 UTC, bsmth commented on files/en-us/web/api/web_storage_api/index.md
> +> **Note:** Asynchronous alternatives, such as [IndexedDB](/en-US/docs/Web/API/IndexedDB_API), may be more suitable for scenarios where performance is a concern or when dealing with larger datasets.
```suggestion
Both `sessionStorage` and `localStorage` in Web Storage are synchronous in nature. This means that when data is set, retrieved, or removed from these storage mechanisms, the operations are performed synchronously, blocking the execution of other JavaScript code until the operation is completed. This synchronous behavior can potentially affect the performance of the web application, especially if there is a large amount of data being stored or retrieved.

Asynchronous alternatives, such as [IndexedDB](/en-US/docs/Web/API/IndexedDB_API), may be more suitable for scenarios where performance is a concern or when dealing with larger datasets. These alternatives allow for non-blocking operations, enabling smoother user experiences and better performance in web applications.
```

2024-03-11 16:05 UTC, bsmth commented
> @bsmth thanks for dropping the review, i will apply the requested changes as required for the `There are too many note blocks in a row here, let's use regular (2 or 3) paras`. what i did is individually dividing and created note block is that what you want? could you brief on this .

Sorry, I meant we can use regular paragraphs instead of note (`> **note:**`) blocks. I've left a suggestion above for you, otherwise it's looking good to me, thanks!

2024-03-11 16:25 UTC, Biki-das commented
@bsmth thanks for clarifying, i have pushed the changes!

2024-03-14 08:44 UTC, bsmth approved these changes
I'm happy with this in the current state. Thanks a lot for your patience and well done on the contribution!

2024-03-14 08:44 UTC, merged