HTML `<search>` element
mdn/content pull request #27727
Opened 2023-07-03 22:42 UTC by ramiy

### Description

On March 2023, a new HTML `<search>` element was [added to the HTML specification](https://html.spec.whatwg.org/multipage/grouping-content.html#the-search-element).

### Related issues

* Safari: https://bugs.webkit.org/show_bug.cgi?id=254327
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1824121
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1294294, https://bugs.chromium.org/p/chromium/issues/detail?id=1277435

2023-07-04 07:21 UTC, Josh-Cena commented
cc @domenic

2023-07-04 10:41 UTC, ramiy commented
Markdown lint - Multiple headings with the same content [Context: `### Result`]

In other HTML element articles there are multiple headings with the same content, [see the header tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header).

2023-07-04 10:57 UTC, Josh-Cena commented
@ramiy The typical structure is to use H4 headings.

```md
## Examples

### Doing something

#### HTML

#### Result

### Doing something else

#### HTML

#### Result
```

2023-07-07 22:56 UTC, estelle requested changes
Thank you for contributing this `<search>` element content. i made a few suggestions, and a fix for the prettier issues.

2023-07-07 22:56 UTC, estelle commented on files/en-us/web/html/element/search/index.md
> +JavaScript search functionality in a web application. No form element to perform a server-side submission, but for semantics a search element represents search and filtering capabilities.
```suggestion
This example demonstrates potential DOM content when dynamically including JavaScript search functionality in a web application. When search functionality is implemented entirely with JavaScript, if no form is submitted, neither a {{HTMLElement("form")}} element nor a submit {{HTMLElement("button")}} is required. For semantics, the `<search>` element is included to contain the search and filtering capabilities.
```

2023-07-07 22:56 UTC, estelle commented on files/en-us/web/html/element/search/index.md
> +### Result
```suggestion
#### Result
```

2023-07-07 22:56 UTC, estelle commented on files/en-us/web/html/element/search/index.md
> +{{EmbedLiveSample('Web app search')}}
```suggestion
{{EmbedLiveSample('Web app search')}}

> **Note:** Remember that some users don't have JavaScript, and none of your users have JavaScript running until the JavaScript is successfully downloaded, parsed, and executed, ensure your users can access the content of your site with JavaScript disabled.
```

2023-07-07 22:56 UTC, estelle commented on files/en-us/web/html/element/search/index.md
> +A page with two search features. The first is a global site search located on the header. The second is a search and filter based on the page context, in our example a car search.
```suggestion
This example demonstrates a page with two search features. The first is a global site search located on the header. The second is a search and filter based on the page context, in our example a car search.
```

2023-07-07 22:56 UTC, estelle commented on files/en-us/web/html/element/search/index.md
> +### Result
```suggestion
#### Result
```

2023-07-10 01:35 UTC, estelle approved these changes
Thanks! 🎉

2023-07-10 01:35 UTC, merged