FF115 Update to link rel=modulepreload
mdn/content pull request #27738
Opened 2023-07-04 06:59 UTC by hamishwillee

This updates the [`rel="modulepreload"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/modulepreload) with additional information about how the feature is used and how it differs from normal preload. 

Also cross links from the preload page.

2023-07-04 07:04 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The main differences are that `modulepreload` puts the results into the module map, and that the fetch operation follows the normal rules for modules, in particular with respect to the use of `crosso
This is a bit "thin" because I've had trouble understanding exactly how JavaScript modules are treated differently for modules w.r.t cors fetches. I think it is just that they are crossorigin=anonymous by default and otherwise you have to set usercredentials to send credentials. But I don't "grok" it. Advice welcome.

2023-07-04 07:05 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/preload/index.md
> +> **Note:** Use [`<link rel="modulepreload">`](/en-US/docs/Web/HTML/Attributes/rel/modulepreload) instead if you are working with [JavaScript modules](/en-US/docs/Web/JavaScript/Guide/Modules).
I "think" there is no benefit for using `modulepreload` except for modules. So this example is still valid, but have provided a crosslink.

2023-07-04 07:07 UTC, hamishwillee commented
@Josh-Cena We probably should also add a note in our modules guide, since this can make quite a difference (as can "preload"). Perhaps in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html ?

If not, where?

2023-07-04 07:12 UTC, Josh-Cena commented
By my understanding, this is a pure performance optimization and doesn't change JS evaluation semantics—right? In this case, I think a one-sentence mention about its existence in your proposed section should be enough.

2023-07-06 23:56 UTC, hamishwillee commented on files/en-us/web/javascript/guide/modules/index.md
> +> **Note:** Modules and their dependencies can be preloaded by specifying them in [`<link>`](/en-US/docs/Web/HTML/Element/link) elements with [`rel="modulepreloaded"`](/en-US/docs/Web/HTML/Attributes
> By my understanding, this is a pure performance optimization and doesn't change JS evaluation semantics—right? In this case, I think a one-sentence mention about its existence in your proposed section should be enough.

@Josh-Cena Your understanding is correct :-). Here is note.

2023-07-07 07:43 UTC, chrisdavidmills requested changes
@hamishwillee sounds mostly pretty good; just a few comments.

2023-07-07 07:43 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The main differences are that `modulepreload` puts the results into the module map, and that the fetch operation follows the normal rules for modules, in particular with respect to the use of `crosso
Hrm, I'm really not sure of the answer here. What you've written makes sense, based on what I've seen previously with using `crossorigin` for fonts and stuff. Maybe link to the section on `crossorigin` on the 'preload' page for more info?

2023-07-07 07:43 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The destination of the preloaded module, which indicates how the resource is to be used, is optional and defaults to `"script"`.
I'm not convinced that this "destination" term is very helpful. It makes it sound like it refers to a location the resource will be put, like an `href` or something, whereas actually, it is referring to the type of resource the link points to. This is more the kind of language we've used in other pages.

I do appreciate that the spec uses "destination", but hey.

2023-07-07 07:43 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +An error is fired on the element if any other destination is set.
What kind of error?

2023-07-07 07:43 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +</html>
One thing that I'd maybe add here is some kind of statement saying that preloading assets is a balancing act. It can improve performance/time to usable by making critical assets available earlier in the rendering process, but at the same time, you can't just preload everything as a magic bullet to make the loading time go away. If you preload too many things, you might actually harm performance because the browser will be forced to use its finite resources on preloading rather than other valuable tasks.

The preload page probably needs this too.

BTW, https://developer.chrome.com/blog/modulepreload/ provides a useful summary of the differences between the preload and modulepreload values. Did you read that?

2023-07-07 07:43 UTC, chrisdavidmills commented on files/en-us/web/javascript/guide/modules/index.md
> +> This can significantly reducing load time when the modules are used.
This feels a bit misleading to me - the loading time is not reduced; you are just telling the browser to fetch this resource earlier/with a higher priority.

2023-07-10 02:14 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The main differences are that `modulepreload` puts the results into the module map, and that the fetch operation follows the normal rules for modules, in particular with respect to the use of `crosso
Unfortunately the `crossorigin` on the preload page is useless for this purpose. I've taken way to much time and unpacked this. Re-written.

2023-07-10 02:18 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The destination of the preloaded module, which indicates how the resource is to be used, is optional and defaults to `"script"`.
You're right. I did consider this, and erred on the spec term. I'll change.

2023-07-10 02:35 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The **`modulepreload`** keyword, for the [`rel`](/en-US/docs/Web/HTML/Attributes/rel) attribute of the {{HTMLElement("link")}} element, provides a declarative way to preemptively fetch a [module scri
FYI spec just says evaluation, which is a bit "wishy washy". My understanding is that things in the module map are already compiled. You really have to have parsed at least in order to find the dependencies.

2023-07-10 02:36 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +When using `modulepreload` the fetch request mode is always [`cors`](/en-US/docs/Web/API/Request/mode#cors), and the [`crossorigin`](/en-US/docs/Web/HTML/Attributes/crossorigin) property is used to d
FYI, this is the clarification of cors behaviour for modules.

2023-07-10 02:37 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +An error is fired on the element if any other destination is set.
An Event, with name error. Updated.

2023-07-10 03:10 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/preload/index.md
> +> **Note:** Use [`<link rel="modulepreload">`](/en-US/docs/Web/HTML/Attributes/rel/modulepreload) instead if you are working with [JavaScript modules](/en-US/docs/Web/JavaScript/Guide/Modules).
This is good.

2023-07-10 03:11 UTC, hamishwillee commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +</html>
Thanks - found that this morning. It is useful, and I wish I had found it earlier.
I have mined it for the explanation of what "more" it is that module preload does. I also decided it is a good "See also", because it does contain a few things I don't want to say particularly about the differences. 

This is addressed for modulepreload in https://github.com/mdn/content/pull/27738/commits/30545425ae955da3186e5ee674fc768f08bd5ec4 

I don't intend to update `preload` at this point.

2023-07-10 03:23 UTC, hamishwillee commented on files/en-us/web/javascript/guide/modules/index.md
> +> This can significantly reducing load time when the modules are used.
Hmmmm. I think it is correct, though it depends on how you define "load". 

Whatever modules you have specified are already in the module map, parsed and compiled. IMO that is "loaded", though not executed. 
Further, it isn't just "earlier" + priority, it is **less time** because it _can be_ in parallel. It doesn't have to be, but there would be little point in preloading a resource without preloading its dependencies. FYI the basic example I reference  in the other doc the time is almost halved. 

Agree? This was the nuance I was after, but happy enough to change to "can reduce the time to execution".

2023-07-10 03:24 UTC, hamishwillee commented
THanks @chrisdavidmills - updated with counter comments too. I think it is better for your review, and ready for another.

2023-07-10 07:52 UTC, chrisdavidmills commented on files/en-us/web/javascript/guide/modules/index.md
> +> This can significantly reducing load time when the modules are used.
OK, sounds good. 

You just need to update "significantly reducing" to "significantly reduce"

2023-07-10 08:00 UTC, chrisdavidmills approved these changes
Nice one @hamishwillee . One more small language change needed, but approving so as not to hold you up.

2023-07-10 08:00 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/rel/modulepreload/index.md
> +The **`modulepreload`** keyword, for the [`rel`](/en-US/docs/Web/HTML/Attributes/rel) attribute of the {{HTMLElement("link")}} element, provides a declarative way to preemptively fetch a [module scri
I think this is better.

2023-07-10 09:10 UTC, hamishwillee commented on files/en-us/web/javascript/guide/modules/index.md
> +> This can significantly reducing load time when the modules are used.
Thanks. Brain fried.

```suggestion
> This can significantly reduce load time when the modules are used.
```

2023-07-10 09:11 UTC, merged

2023-07-10 09:11 UTC, hamishwillee commented
Thanks @chrisdavidmills - really appreciate the help.