fix(CSS): mention containment context as containing block
mdn/content pull request #27744
Opened 2023-07-04 08:37 UTC by OnkarRuikar

- Fixes: https://github.com/mdn/content/issues/27529

2023-07-04 18:03 UTC, dipikabh requested changes
Thanks, @OnkarRuikar. I've left a few suggestions.

2023-07-04 18:03 UTC, dipikabh commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
Same comment about the link here. Also, we might not 

```suggestion
  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to either its closest [containing block](/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) with `layout`, `paint`, `strict`, or `content` values for `contain` or its initial containing block established by the {{glossary("viewport")}}, except when one of its ancestors has a `transform`, `perspective`, or `filter` property set to something other than `none` (see the [CSS Transforms Spec](https://www.w3.org/TR/css-transforms-1/#propdef-transform)), or the [`will-change`](/en-US/docs/Web/CSS/will-change) property is set to `transform`, in which case that ancestor behaves as the containing block. (Note that there are browser inconsistencies with `perspective` and `filter` contributing to containing block formation.) Its final position is determined by the values of `top`, `right`, `bottom`, and `left`.
```

2023-07-05 04:21 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to either its closest [positioned](#types_of_position
> should the link to CSS containment be changed to the Containing block page, section Identifying the containing block?

The [identifying containing block section](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) on that page covers all the possibilities not just containment. So if we do that then we don't have to write all the cases here:
```suggestion
  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to either its closest [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block). Its final position is determined by the values of `top`, `right`, `bottom`, and `left`.
```
If you are willing to simplify like this then let's do it.

2023-07-05 04:27 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
From the answer above the simplification would be:
```suggestion
  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block). Its final position is determined by the values of `top`, `right`, `bottom`, and `left`.
```
Same logic that sections is thorough and covers every aspect we don't have to repeat any info from there.

2023-07-05 16:45 UTC, dipikabh commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to either its closest [positioned](#types_of_position
Yes, this edit seems reasonable and its better to have details in one place to reduce maintenance.

Only question I have here is if its technically accurate to replace the options of 'closest positioned ancestor, closest containing block, and initial containing block' with only 'closest containing block'. Does that cover all the scenarios and does it make it obvious to the readers that all those scenarios are covered?

2023-07-05 16:51 UTC, dipikabh commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
- I have the same question here as in the previous comment wrt 'closest positioned ancestor, closest containing block, and initial containing block'.
- The text here refers to "`transform`, `perspective`, or `filter` property set to something other than `none`", whereas in the [Identifying the containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) section, point 4 only refers to two of them:
"A `transform` or `perspective` value other than `none`."
Perhaps this point in "Identifying the containing block" section needs to be updated?
- +1 to moving 'browser inconsistency' note to "Identifying the containing block" section

2023-07-05 17:09 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to either its closest [positioned](#types_of_position
> Only question I have here is if its technically accurate to replace the options of 'closest positioned ancestor, closest containment* block, and initial containing block' with only 'closest containing block'. 

The section [identifying the containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block), that we are trying use here, covers these same cases and calls it a 'containing block'. So it has already been established.

> Does that cover all the scenarios and does it make it obvious to the readers that all those scenarios are covered?

It is covering more scenarios than these section. And we are trying to make it complete (e.g. https://github.com/mdn/content/pull/27739). \
Counter argument would be if we don't refer to that section then users may come complaining those scenarios are not covered here. :P

2023-07-05 17:13 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
> * The text here refers to "`transform`, `perspective`, or `filter` property set to something other than `none`", whereas in the [Identifying the containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) section, point 4 only refers to two of them:
>   "A `transform` or `perspective` value other than `none`."
>   Perhaps this point in "Identifying the containing block" section needs to be updated?

:O The 4.iii section does cover `filter` property: ```A `filter` value other than `none` or a `will-change` value of `filter` ```

2023-07-05 17:22 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest [containing block](https://de
```suggestion
  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest [containing block](/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block). Its final position is determined by the values of `top`, `right`, `bottom`, and `left`.
```

2023-07-05 17:22 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest [containing block](https://de
```suggestion
  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its closest [containing block](/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block). Its final position is determined by the values of `top`, `right`, `bottom`, and `left`.
```

2023-07-05 17:27 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
> * +1 to moving 'browser inconsistency' note to "Identifying the containing block" section

Done in commit [add the note to containing clock page](https://github.com/mdn/content/pull/27744/commits/ce8256b2a7d4340a669e77069bca5f9e05e31c09).

2023-07-06 17:13 UTC, dipikabh approved these changes
Thanks, @OnkarRuikar, for these updates!

2023-07-06 17:13 UTC, dipikabh commented on files/en-us/web/css/containing_block/index.md
> +> **Note:** There are browser inconsistencies with `perspective` and `filter` contributing to containing block formation.
This looks fine. Thanks for moving it out from `position` page.

One small comment about overcrowding of notes - (this is a scope creep, maybe we can fix it in another PR) - the previous note (defining initial containing block) does not sound like a note. It should be part of regular prose. It can be moved as the first sentence in the "Identifying the containing block" section.

2023-07-06 17:13 UTC, dipikabh commented on files/en-us/web/css/position/index.md
> +  - : The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned either relative to the closest [containment context](/en-US/do
> The 4.iii section does cover filter property:

My bad, I missed this.

2023-07-06 17:13 UTC, merged