Update index.md
mdn/content pull request #27765
Opened 2023-07-04 18:30 UTC by dv3lah

If the direction of ul or ol element is set to rtl the padding will be padding-right, not padding left. So it's good to mention that.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-07-04 20:39 UTC, dipikabh requested changes
Thanks for this contribution, @dv3lah.

I have suggested a slight edit to enhance clarity.

2023-07-04 20:39 UTC, dipikabh commented on files/en-us/learn/css/styling_text/styling_lists/index.md
> +- The {{htmlelement("ul")}} and {{htmlelement("ol")}} elements have a top and bottom {{cssxref("margin")}} of `16px` (`1em`) and a {{cssxref("padding-left")}} of `40px` (`2.5em`) or {{cssxref("paddin
```suggestion
- The {{htmlelement("ul")}} and {{htmlelement("ol")}} elements have a top and bottom {{cssxref("margin")}} of `16px` (`1em`) and a {{cssxref("padding-left")}} of `40px` (`2.5em`). If the directionality attribute [`dir`](/en-US/docs/Web/HTML/Global_attributes/dir) is set to right-to-left (`rtl`) for `ul` and `ol` elements, in that case {{cssxref("padding-right")}} comes into effect and its default value is `40px` (`2.5em`) .
```

2023-07-05 05:11 UTC, dv3lah commented
Done, thank you!

2023-07-05 18:45 UTC, dipikabh approved these changes
Thank you, @dv3lah.

2023-07-05 18:45 UTC, dipikabh commented
Welcome to the MDN Web Docs project! 🎉

2023-07-05 18:45 UTC, merged

2023-07-05 20:02 UTC, dv3lah commented
Thank you!