CSS Module: shadow parts
mdn/content pull request #27909
Opened 2023-07-13 00:41 UTC by estelle

New css module: shadow parts.
Pseudo elements links to this and this links to pseudo-elements, both new, so link will be red.
I wrote an "in action" but don't know how to make it interactive and fun, so not included yet (https://codepen.io/estelle/pen/rNQpELX)

2023-07-13 23:46 UTC, dipikabh requested changes
Thanks for adding this module page, @estelle!

We might also want to add a link to this module page in [shadow host](https://developer.mozilla.org/en-US/docs/Glossary/Shadow_tree) glossary.

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +The **CSS shadow parts** module defines the {{CSSXref("::part", "::part()")}} pseudo-element on shadow hosts, allowing shadow hosts to expose selected shadow tree elements to the outside page for sty
- split the sentence - how about this rephrasing
- also added a link to 'shadow tree' glossary because all these shadow DOM-related terms are referred there and a food intro to the shadow DOM concept. (and additionally, we have [Using shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) in "See also") 

```suggestion
The **CSS shadow parts** module defines the {{CSSXref("::part", "::part()")}} pseudo-element that can be set on a [shadow host](/en-US/docs/Glossary/Shadow_tree). Using this pseudo-element, you can enable shadow hosts to expose the selected element in the shadow tree to the outside page for styling purposes.
```

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +By default, elements in a shadow tree are only styleable from within that shadow root. The CSS shadow parts module enables including a [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute
- Can we explain the context of `template` descendants here?

```suggestion
By default, elements in a shadow tree can be styled only within their respective shadow roots. The CSS shadow parts module enables including a [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute on {{HTMLElement("template")}} descendants, exposing the shadow tree node to external styling via the `::part()` pseudo-element.
```

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +### HTML Attributes
```suggestion
### HTML attributes
```

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +  - : Overview of the different APIs that make enable creating reusable custom elements, or web components.
```suggestion
  - : Overview of the different APIs that enable creating reusable custom elements or web components.
```

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +- [Templates: styling outside of the current scope](https://web.dev/learn/html/template/#styling-outside-of-the-current-scope) on web.dev (2023)
```suggestion
- [Templates: Styling outside of the current scope](https://web.dev/learn/html/template/#styling-outside-of-the-current-scope) on web.dev (2023)
```

2023-07-13 23:46 UTC, dipikabh commented on files/en-us/web/css/css_shadow_parts/index.md
> +  - {{CSSXref("::slotted")}}
I noticed that the style used in these pages (though they're not module landing pages) was similar to the pseudo-elements page I reviewed yesterday - that is, an example code snippet, no heading and then a syntax code snippet with "Syntax" heading

2023-07-14 04:19 UTC, estelle commented on files/en-us/web/css/css_shadow_parts/index.md
> +By default, elements in a shadow tree can be styled only within their respective shadow roots. The CSS shadow parts module enables including a [`part`](/en-US/docs/Web/HTML/Global_attributes#part) at
```suggestion
By default, elements in a shadow tree can be styled only within their respective shadow roots. The CSS shadow parts module enables including a [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute on {{HTMLElement("template")}} descendants that make up the custom element, exposing the shadow tree node to external styling via the `::part()` pseudo-element.
```

2023-07-14 04:20 UTC, estelle commented on files/en-us/web/css/css_shadow_parts/index.md
> +  - {{CSSXref("::slotted")}}
i'll add that to my list of chores ;)

2023-07-14 04:26 UTC, estelle commented on files/en-us/web/css/css_shadow_parts/index.md
> +  - {{CSSXref("::slotted")}}
https://github.com/mdn/content/issues/27938

2023-07-14 13:20 UTC, dipikabh approved these changes
Thank you! 🎉

2023-07-14 13:20 UTC, merged