Document HTMLAllCollection
mdn/content pull request #27974
Opened 2023-07-16 09:07 UTC by Josh-Cena

### Description

Fix https://github.com/mdn/content/issues/25178

First time writing Web API docs. Please advise.

### Motivation

### Additional details

### Related issues and pull requests

2023-07-28 23:17 UTC, wbamberg requested changes
Thank you @Josh-Cena !

I had some comments, and questions. I suppose it's questionable how much time we should put into perfecting these pages on this deprecated and terrible API.

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/index.md
> +The **`HTMLAllCollection`** interface represents a collection of _all_ of the document's elements, accessible by order (like an array) and by ID (like a regular object). It is returned by the {{domxr
Probably worth a short para about how this is almost identical to `HTMLCollection` (the spec is hilarious here):

> the main differences are that it allows a staggering variety of different (ab)uses of its methods to all end up returning something, and that it can be called as a function as an alternative to property access.

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/index.md
> +  - : Returns the specific node whose ID or, as a fallback, name matches the string specified by `name`. Matching by name is only done as a last resort, only in HTML, and only if the referenced eleme
```suggestion
  - : Returns the first [element](https://developer.mozilla.org/en-US/docs/Web/API/Element) in the collection whose [`id`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) or `name` attribute match the given string name, or `null` if no element matches.
```

(I copied this from the preamble to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection/namedItem. Mainly, the existing para was too long and a bit vague (i.e. terms like "as a last resort", what does that mean?).

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/index.md
> +In addition to the methods above, an `HTMLAllCollection` can be accessed by integer indices and string property names. HTML IDs may contain `:` and `.` as valid characters, which would necessitate us
```suggestion
In addition to the methods above, elements in an `HTMLAllCollection` can be accessed by integer indices and string property names. The HTML `id` attribute may contain `:` and `.` as valid characters, which would necessitate using bracket notation for property access. `collection[i]` is equivalent to `collection.item(i)`, where `i` can be an integer, a string containing an integer, or a string representing an `id`.
```

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/index.md
> +For historical reasons, `document.all` is an object that in many ways behaves like `undefined`. Specifically:
```suggestion
For historical reasons, `document.all` is an object that in the following ways behaves like `undefined`:
```

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/item/index.md
> +The **`item()`** method of the {{domxref("HTMLAllCollection")}} interface returns the element located at the specified offset into the collection, or the node with the specified id or name.
```suggestion
The **`item()`** method of the {{domxref("HTMLAllCollection")}} interface returns the element located at the specified offset into the collection, or the node with the specified value for its `id` or `name` attribute.
```

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/item/index.md
> +  - : An integer representing the position of the {{domxref("Element")}} to be returned. Elements appear in an `HTMLAllCollection` in the same order in which they appear in the document's source. If
I'm not sure what "a string that's not a valid integer" means. Does it mean, a string that can't be converted to an integer? If so should this be something like:

```suggestion
  - : If this parameter is an integer, or a string that can be converted to an integer, then it represents the position of the {{domxref("Element")}} to be returned. Elements appear in an `HTMLAllCollection` in the same order in which they appear in the document's source. If the parameter is a string can't be converted to an integer, it will be interpreted as the `name` or `id` of the element to be returned.
```

?

2023-07-28 23:17 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/nameditem/index.md
> +The **`namedItem()`** method of the {{domxref("HTMLAllCollection")}} interface returns the first {{domxref("Element")}} in the collection whose `id` or `name` attribute match the specified name, or `
```suggestion
The **`namedItem()`** method of the {{domxref("HTMLAllCollection")}} interface returns the first {{domxref("Element")}} in the collection whose `id` or `name` attribute matches the specified name, or `null` if no element matches.
```

2023-07-29 00:07 UTC, Josh-Cena commented on files/en-us/web/api/htmlallcollection/index.md
> +  - : Returns the specific node at the given zero-based `index` into the list. Returns `null` if the `index` is out of range.
Element. When you see "node" it's copied from `HTMLCollection`, which is wrong anyway.

2023-07-29 00:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlallcollection/index.md
> +  - : Returns the specific node whose ID or, as a fallback, name matches the string specified by `name`. Matching by name is only done as a last resort, only in HTML, and only if the referenced eleme
Again, the current para is copied from the `HTMLCollection` landing page. It's all a bit messy, isn't it...

2023-07-29 01:22 UTC, wbamberg commented on files/en-us/web/api/htmlallcollection/index.md
> +  - : Returns the specific node whose ID or, as a fallback, name matches the string specified by `name`. Matching by name is only done as a last resort, only in HTML, and only if the referenced eleme
Yeah, the old DOM docs are pretty bad.

2023-08-05 02:09 UTC, wbamberg approved these changes
👍 thank you @Josh-Cena !

2023-08-05 02:09 UTC, merged