Fix issue 6272: clarify why to set image width and height
mdn/content pull request #28113
Opened 2023-07-21 20:30 UTC by wbamberg

...

2023-07-21 22:15 UTC, estelle commented
Drive by comment: The preventing jank section on https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia#rendering_strategy_preventing_jank_when_loading_images covers this topic really well

2023-07-24 19:59 UTC, wbamberg commented
> Drive by comments: The preventing jank section on https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia#rendering_strategy_preventing_jank_when_loading_images covers this topic well. Also, if using `<figure>` around a blockquote, I would explain why that was used. Alternatively, use a `<blockquote>` with a `<p>` and `<footer>` for the quote and citation, respectively.

Thanks, I used that markup because it was what the interactive example had, and also what the spec recommended. But I see the example was just changed in https://github.com/mdn/interactive-examples/pull/2562.

It would be good to update the guidance in the page about attribution of blockquotes, or this will probably come back.

Anyway, I updated the markup, and redid the images too - I like the side-by-side comparison much better.

2023-07-25 04:00 UTC, estelle requested changes
a few suggestions

2023-07-25 04:00 UTC, estelle commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +You can find your image's width and height in a number of ways. For example on the Mac you can use <kbd>Cmd</kbd> + <kbd>I</kbd> to get the info display up for the image file. Returning to our exampl
```suggestion
You can find your image's width and height in a number of ways. For example, on the Mac you can use <kbd>Cmd</kbd> + <kbd>I</kbd> to get the display information for the image file. Returning to our example, we could do this:
```

2023-07-25 04:00 UTC, estelle commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +There's a very good reason to do this. The HTML for your page and the image are separate resources, fetched by the browser as separate HTTP(S) requests. As soon as the browser has received the HTML,
```suggestion
There's a very good reason to do this. The HTML for your page and the image are separate resources, fetched by the browser as separate HTTP(S) requests. As soon as the browser has received the HTML, it will start to display it to the user. If the images haven't yet been received (and this will often be the case, as image file sizes are often much larger than HTML files), then the browser will render only the HTML, and will update the page with the image as soon as it is received.
```

2023-07-25 04:00 UTC, estelle commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +Moving the text like this is extremely distracting to users, especially if they have already started to read it.
```suggestion
This "jank", the moving or already rendered content, is extremely distracting to users, especially if they have already started reading or otherwise interacting with the page.
```

OK as is, but we may want to add the "jank" term, which is what this performance faux-pas is commonly called.

2023-07-25 04:00 UTC, estelle commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +For an excellent article on the history of this feature, see [Setting Height And Width On Images Is Important Again](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-aga
```suggestion
For an excellent article on the history of this feature, see [Setting height and width on images is important again](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/).
```
Our writing guidelines read:

 > Use sentence casing in the link text even if it is different from the linked page title or section title.
 
 I am assuming that is for external links, but can't seem to find the reference at the moment to double check.

2023-07-25 04:00 UTC, estelle commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +Moving the text like this is extremely distracting to users, especially if they have already started to read it.
maybe link the word jank to https://developer.mozilla.org/en-US/docs/Learn/Performance/Multimedia#rendering_strategy_preventing_jank_when_loading_images, or add this article to the # see also

2023-07-26 22:45 UTC, wbamberg commented on files/en-us/learn/html/multimedia_and_embedding/images_in_html/index.md
> +Moving the text like this is extremely distracting to users, especially if they have already started to read it.
I would like to keep this as it is, since it is the critical point here and I would like to keep the sentence as simple as possible.

2023-07-29 00:22 UTC, estelle approved these changes

2023-07-29 03:05 UTC, merged