Set code languages for various files (part 1)
mdn/content pull request #28145
Opened 2023-07-24 07:04 UTC by queengooborg

This PR sets the code language for various codeblocks that don't have one set, which will help us enforce setting a language on all codeblocks.  This is the first part.

2023-07-24 15:57 UTC, bsmth commented on files/en-us/learn/javascript/first_steps/variables/index.md
> +> > let myName = "Bob";
This one looks weird, it's just above https://pr28145.content.dev.mdn.mozit.cloud/en-US/docs/Learn/JavaScript/First_steps/Variables#updating_a_variable

2023-07-24 18:22 UTC, Josh-Cena requested changes, later dismissed
Hi @queengooborg, confusing as it sounds, "plain" is actually a marker for "it should have a language but the language it should be isn't supported so we use a placeholder". In Yari, "plain" is "planned for deprecation":

https://github.com/mdn/yari/blob/1374a7400b50610ea2a4dd1f6545cd613d360966/build/syntax-highlight.ts#L77

I'm on mobile, but I bet you can find past discussions on the content repo about this.

2023-07-24 18:35 UTC, queengooborg commented
I'm -1 on deprecating "plain" as a language to apply to code blocks.

As I have been going through these files, I've found numerous instances where a language wasn't selected for syntax highlighting, even though it should be.  There's probably a bunch marked as "plain" that shouldn't be as well, but by requiring a language to be specified, we can perform a simple search to find such instances in our documents and fix them.  Additionally, enforcing some language to be set forces the author to think about what language the code block should be set to, so that we can catch issues early on.  (Take note on how many code blocks I have specified a language other than "plain" for in this PR.)

2023-07-24 19:49 UTC, queengooborg commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +```url
There is a `url` key actually!  

<img width="149" alt="image" src="https://github.com/mdn/content/assets/5179191/8e48fe97-8bb2-4e9a-83fe-b3a6e14d850c">

We load it in as `uri` (note the "i" instead of "l"), though- - should we change `url` to `uri`?

2023-07-24 19:54 UTC, queengooborg commented on files/en-us/learn/javascript/first_steps/variables/index.md
> +> > let myName = "Bob";
This is a very strange section.  I decided to stick with `plain` as this section shows the use of Chrome's console, but is this section really needed...?

2023-07-25 08:33 UTC, bsmth commented on files/en-us/learn/forms/basic_native_form_controls/index.md
> +```url
>There is a url key actually!

oh yeah! https://github.com/PrismJS/prism/blob/master/components/prism-uri.js

OK interesting, we're loading it in Yari already as uri (which we can alias to URL, but that's not a big deal).

One thing though, it looks like it's correctly parsing the URI but not applying styles 🤔 

![image](https://github.com/mdn/content/assets/43580235/73dcc510-5170-4aa0-8057-9bcdaf909cd2)

Regarding this PR, I'm fine with `uri` here, what do you reckon?

2023-07-26 21:29 UTC, queengooborg commented
Good catch, @rubiesonthesky -- per our guidelines, we shouldn't be including the output of commands in Shell code blocks anyways.  I'll submit a follow-up PR to fix this!

2023-08-02 16:49 UTC, queengooborg commented
Still looking to get review on this PR so we can land it soon!

2023-08-02 16:57 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
Use `js-nolint` for code in this page because they are essentially syntax blocks

2023-08-02 16:57 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/conditionals/index.md
> +```plain
```suggestion
```js-nolint
```

2023-08-02 16:57 UTC, Josh-Cena commented on files/en-us/learn/javascript/first_steps/variables/index.md
> +> ```js-nolint
```suggestion
> ```plain
```

(As discussed above)

2023-08-02 16:57 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component/index.md
> +```plain
If we use `svelte` for `on:keydown={(e) => e.key === 'Escape' && onCancel()}`, then this should be `vue`

2023-08-02 17:03 UTC, queengooborg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component/index.md
> +```plain
Oops, fixed the Svelte snippet to use `plain`!

2023-08-02 17:22 UTC, Josh-Cena reviewed
Almost there!

2023-08-02 17:22 UTC, Josh-Cena commented on files/en-us/web/api/fileentrysync/index.md
> +```js
This is webidl; either use webidl or plain

2023-08-02 17:22 UTC, Josh-Cena commented on files/en-us/web/api/fileentrysync/index.md
> +```js
Same here

2023-08-02 17:22 UTC, Josh-Cena commented on files/en-us/web/api/mousescrollevent/index.md
> +```plain
This is webidl, so not sure if it should be plain (not complaining too much because this page is not great anyway)

2023-08-02 17:22 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
The syntax blocks here and below should be `js-nolint` too

2023-08-02 17:25 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
```suggestion
```js-nolint
```

2023-08-02 17:25 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
```suggestion
```js-nolint
```

2023-08-02 17:25 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
```suggestion
```js-nolint
```

2023-08-02 17:25 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/looping_code/index.md
> +```plain
```suggestion
```js-nolint
```

2023-08-02 17:29 UTC, Josh-Cena approved these changes
LGTM. Let's get it in!

2023-08-02 17:32 UTC, merged