Add link to microtask_guide
mdn/content pull request #2815
Opened 2021-03-02 21:31 UTC by jchimene

ref #1584

2021-03-02 22:02 UTC, sideshowbarker requested changes

2021-03-02 22:02 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/promise/index.html
> +<p>See the <a target="_blank" href="/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide" title="Microtask_guide">Microtask guide</a> to learn more about how these methods use the Microtask queue and ser
```suggestion
<p>See the <a target="_blank" href="/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide" title="Microtask_guide">Microtask guide</a> to learn more about how these methods use the Microtask queue and services.</p>
```

2021-03-02 22:06 UTC, sideshowbarker commented
The link is a good addition but to me at least it doesn’t seem sufficient for resolving the issue described in https://github.com/mdn/content/issues/1584:

> It should be clearly mentioned that then and catch call adds Microtask to Microtask Queue.

That is, it seems like @krp12345 is saying the above should be explained in the prose of the article.

2021-03-03 00:05 UTC, jchimene commented
> The link is a good addition but to me at least it doesn’t seem sufficient for resolving the issue described in #1584:
> 
> > It should be clearly mentioned that then and catch call adds Microtask to Microtask Queue.
> 
> That is, it seems like @krp12345 is saying the above should be explained in the prose of the article.

That's a fair point. I'm not sure how to do that in the context of this section framework (dl,dt,dd) without duplicating the `microtask_guide`. It's difficult for me to see how to further describe how then/catch/finally enqueue Microtasks without also describing the Event Loop, et. al., which seems to be the purpose of the `microtask_guide` page. 
How about "These methods generate entries on the Microtask queue, as opposed to the Task queue. The declared functions are called during the Microtask processing loop. See <a> for more."

2021-03-16 05:29 UTC, sideshowbarker approved these changes

2021-03-16 05:30 UTC, merged

2021-03-16 05:30 UTC, sideshowbarker commented
Sorry for not having gotten back to this one before now

2021-03-16 06:08 UTC, krp12345 commented
Thanks @sideshowbarker  and @jchimene . I am closing the issue.