Update documentation for forced colors mode
mdn/content pull request #2819
Opened 2021-03-03 02:38 UTC by dlibby-

Updates the list of properties that are forced.

Adds guidance around system color usage and the fact that they are respected in forced colors mode.

Explains that forced colors are chosen based on element, not role.

Adds an example of using a system color (previous example wouldn't have worked without `forced-color-adjust: none`).

2021-03-03 02:41 UTC, dlibby- commented
@alisonmaher @melanierichards @minorninth, please take a first pass review (@ericwbailey feel free to hold off on review for now, but if you do want to review immediately, any feedback is welcome!)

2021-03-03 03:05 UTC, ericwbailey commented
Thanks for the head's up, @dlibby-. If you don't mind @ mentioning me again when you'd like a review, I'd appreciate it.

2021-03-03 17:55 UTC, alisonmaher reviewed
This looks great, thanks for working on this @dlibby-.

Something that I noticed was that on the forced-color-adjust page, it suggests that Edge has shipped that with an alternate name (since we shipped with both). However, we don't mention -ms-high-contrast in the forced-colors page.

I'm not sure which is the right answer, but it would probably be good to keep them consistent.

2021-03-03 17:59 UTC, alisonmaher commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, user-specified values (if any) or browser-specified values are
It might be helpful to mention that the colors are forced at used value time, similar to the updated spec text: https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties.

Also, I don't believe that the second sentence regarding user-specified values applies anymore given that this is no longer implemented using revert.

2021-03-03 18:05 UTC, alisonmaher reviewed
Sorry, I'm not sure why these didn't post with my original comment.

2021-03-03 18:05 UTC, alisonmaher commented on files/en-us/web/css/@media/forced-colors/index.html
> + <li>{{cssxref("background-color")}}</li>
It might make sense to move these to a separate section below, similar to the updated spec (along with the added scrollbar-color.)

2021-03-03 18:05 UTC, alisonmaher commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is specified on an element, none of the forced color values will apply, and author style will be applied as normal.</p>
This should probably say something like "when forced-color-adjust is set to none" (same on the line above).

2021-03-03 18:05 UTC, alisonmaher commented on files/en-us/web/css/color_value/index.html
> + <p>Foreground or text color of controls</p>
To keep things consistent with the other system colors, perhaps this should be switched to "Text or foreground color", although just saying "Foreground color" might be simpler since I believe text should fall into that category.

2021-03-05 02:05 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> + <li>{{cssxref("background-color")}}</li>
Not sure if I got this right, based on the line you highlighted, but I did update to more closely match the spec's organization of the properties.

2021-03-05 02:06 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is specified on an element, none of the forced color values will apply, and author style will be applied as normal.</p>
Indeed, thanks!

2021-03-05 02:06 UTC, dlibby- commented on files/en-us/web/css/color_value/index.html
> + <p>Foreground or text color of controls</p>
Good point, I do think that is clearer.

2021-03-05 02:06 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, user-specified values (if any) or browser-specified values are
I tried to put together a description of used value in layman's terms. Let me know what you think!

2021-03-05 19:11 UTC, alisonmaher commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, browser-specified values are used instead. This does not affect
> This does not affect the style cascade, but is accomplished by the browser using the browser-specified values instead of the cascaded values when painting colors.

- The comma before "but" shouldn't be necessary.
- Up to you, but something along these lines might be slightly clearer: "The browser-specified values do not affect the style cascade; the values are instead forced by the browser at paint time."

2021-03-05 19:11 UTC, alisonmaher commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author style will be applied as normal.</p>
"author styles" instead of "author style"

2021-03-05 19:11 UTC, alisonmaher commented on files/en-us/web/css/color_value/index.html
> + <p>Text or foreground color in application content or documents</p>
Should the rest of these be updated to just "Foreground color", as well?

2021-03-05 19:58 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, browser-specified values are used instead. This does not affect
Yes, that is a good improvement, thanks!

2021-03-05 19:58 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author style will be applied as normal.</p>
Fixed.

2021-03-05 19:59 UTC, dlibby- commented on files/en-us/web/css/color_value/index.html
> + <p>Text or foreground color in application content or documents</p>
Yes, I that is a good clarification. Per discussion, left the link and mark related ones as specific to 'Text' since they are somewhat specialized.

2021-03-05 20:01 UTC, alisonmaher approved these changes

2021-03-05 22:24 UTC, melanierichards requested changes
Thanks @dlibby-! Added a couple minor suggestions.

2021-03-05 22:24 UTC, melanierichards commented on files/en-us/web/css/@media/forced-colors/index.html
> + <dd>Indicates that forced colors mode is active. The browser provides the color palette to authors through the <a href="/en-US/docs/Web/CSS/color_value#System_Colors">CSS system color</a> keywords a
Should we add a little bit here (or elsewhere in the doc) to describe when `prefers-color-scheme` gets triggered? At a minimum maybe link out to https://www.w3.org/TR/css-color-adjust-1/#forced?

2021-03-05 22:24 UTC, melanierichards commented on files/en-us/web/css/@media/forced-colors/index.html
>  <p><span class="seoSummary">The <strong><code>forced-colors</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> <a href="/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features">media
Should we update "a forced colors mode" to "a forced colors mode such as Windows High Contrast"? It's mentioned later on in the doc but might be good to lead with, for devs who have been trained to seek out guidance on HC specifically.

2021-03-05 22:24 UTC, melanierichards commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p><strong>Note:</strong> user agents choose system colors based on elements, <em>not</em> their roles. As an example, adding role="button" to a div will not cause an element's color to be forced to
```suggestion
<p><strong>Note:</strong> user agents choose system colors based on native element semantics, <em>not</em> on added ARIA roles. As an example, adding <code>role="button"</code> to a div will not cause an element's color to be forced to <code>ButtonText</code></p>
```

2021-03-05 22:24 UTC, melanierichards commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal.</p>
We should mention that text backplates are removed as well.

2021-03-05 22:24 UTC, melanierichards commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal.</p>
I guess we should add a generic section on that too :)

2021-03-09 01:17 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> + <dd>Indicates that forced colors mode is active. The browser provides the color palette to authors through the <a href="/en-US/docs/Web/CSS/color_value#System_Colors">CSS system color</a> keywords a
Good point - added a sentence and link.

2021-03-09 01:17 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p><strong>Note:</strong> user agents choose system colors based on elements, <em>not</em> their roles. As an example, adding role="button" to a div will not cause an element's color to be forced to
Thanks! I like that phrasing much better!

2021-03-09 01:17 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal.</p>
Added a paragraph on backplates and the fact that they are removed when adjustment is turned off.

2021-03-12 01:44 UTC, melanierichards approved these changes
LGTM, thanks for the updates!

2021-03-12 02:03 UTC, dlibby- commented
@ericwbailey - ready for your review. PTAL when you get a chance, thanks!

2021-03-13 22:16 UTC, ericwbailey requested changes
Good stuff. I left some suggestions, but from a high level I would like to see an accessibility concerns subsection that gives guidance that forced colors should only be tweaks if the content isn't legible, and not a reason to create a whole separate forced colors design.

I'd also like it to stress that this can be the final thing someone might be able to use in order to keep using their computer, so its appearance and method of working is highly intentional.

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p><span class="seoSummary">The <strong><code>forced-colors</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> <a href="/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features">media
```suggestion
<p><span class="seoSummary">The <strong><code>forced-colors</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> <a href="/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features">media feature</a> is used to detect if the {{Glossary("user agent")}} has enabled a forced colors mode, where it enforces a user-chosen limited color palette on the page. An example of a forced colors mode is such as Windows High Contrast mode.</span></p>
```

Update this to simplify the sentence a bit.

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, browser-specified values are used instead. The browser-specifie
```suggestion
<p>In forced colors mode, the values of the following properties are treated as if they have no author-level values specified. That is, browser-specified values are used instead. The browser-specified values do not affect the style cascade; the values are instead forced by the browser at paint time.</p>
<p>These browser-specified values are selected from the set of system colors &emdash; this ensures a consistent contrast for common UI elements for users that have forced colors enabled.</p>
```

Two thoughts, two paragraphs. This is kind of an abstract thing to grok, so I want to make it as simple to read as possible.

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>The system colors that are forced for the above properties depend on the context of the element. For example the {{cssxref("color")}} property on button element will be forced to ButtonText, where
```suggestion
<p>The system colors that are forced for the above properties depend on the context of the element. For example the {{cssxref("color")}} property on button element will be forced to <code>ButtonText</code>. On normal text it will be forced to <code>CanvasText</code>. See the list of system colors for additional details of when each might be appropriate in various UI contexts.</p>
```

Shortened a sentence here as well. In addition can we link to the list of system colors if we're naming it?

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p><strong>Note:</strong> user agents choose system colors based on native element semantics, <em>not</em> on added ARIA roles. As an example, adding <code>role="button"</code> to a div will not caus
```suggestion
<p><strong>Note:</strong> user agents choose system colors based on native element semantics, <em>not</em> on added ARIA roles. As an example, adding <code>role="button"</code> to a div will <strong>not</strong> cause an element's color to be forced to <code>ButtonText</code></p>
```

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>There are two cases where the user agent does not force the values for the above properties &emdash; when a {{cssxref("forced-color-adjust")}} value of 'none' is applied to an element, or when a s
```suggestion
<p>There are two cases where the user agent does not force the values for the above properties &emdash; when a {{cssxref("forced-color-adjust")}} value of <code>none</code> is applied to an element, or when a system color is specified by the author.</p>
```

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal. Additionally, the backplate for text will be disab
```suggestion
<p>When forced-color-adjust is set to <code>none</code> on an element, none of the forced color values will apply, and author styles will be applied as normal. Additionally, the backplate for text will be disabled.</p>
```

2021-03-13 22:16 UTC, ericwbailey commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal. Additionally, the backplate for text will be disab
I'd like to see a sentence on the end of this paragraph that reinforces that this is something you should avoid manipulating at all costs, and only think about if the backplate is somehow obscuring legibility. 

I want to make it absolutely clear that disabling the backplate to art-direct a forced colors mode is not acceptable usage.

2021-03-16 00:13 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p><span class="seoSummary">The <strong><code>forced-colors</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> <a href="/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features">media
Done.

2021-03-16 00:13 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>The system colors that are forced for the above properties depend on the context of the element. For example the {{cssxref("color")}} property on button element will be forced to ButtonText, where
There was a previous link, but added another one here for convenience.

2021-03-16 00:14 UTC, dlibby- commented on files/en-us/web/css/@media/forced-colors/index.html
> +<p>When forced-color-adjust is set to 'none' on an element, none of the forced color values will apply, and author styles will be applied as normal. Additionally, the backplate for text will be disab
Folded this into an overall Accessibility concerns sections, let me know if it is strong enough.

2021-03-16 00:14 UTC, dlibby- commented
Thanks for the review! I think this is ready for another round.

2021-03-16 06:01 UTC, bauerlumb approved these changes

2021-03-16 15:24 UTC, ericwbailey approved these changes
Love it. Thank you so much for doing this.

2021-03-16 15:24 UTC, merged