Add prose and meta-docs for [LegacyNullToEmptyString]
mdn/content pull request #28213
Opened 2023-07-27 10:08 UTC by teoli2003

### Description

This PR adds relevant information to existing MDN pages about properties or method parameters prefixed with the WebIDL `[LegacyNullToEmptyString]`.

### Motivation

This is part of openwebdocs/project#159 where we want to uniformize and add more information stored in WebIDLs files. Standardizing them makes them easier to understand and MDN Web docs articles more precise.

### Additional details

_What does this extended attribute mean?_

This extended attribute alters how `null` values are converted to a string. The standard way is to convert `null` to the string `"null"`. When this extended attribute is present, the `null` object is converted to an empty string (`""`).

_What does this PR do?_
- It adds to all relevant properties a sentence explaining the set behaviour when set to the `null` value, with a tiny inline example.
- It adds to all such parameters a sentence explaining what the behaviour is when `null` is passed.
- Update the meta-docs, listing the standardized sentences.

### Related issues and pull requests

None.

2023-07-27 23:38 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +    _When set to the `null` value, that `null` value is converted to the empty string (`""`), unlike the common behavior with strings (that would have converted it to the `"null"` string): `elt.inner
I think it would be worth simplifying and shortening this:

```suggestion
    _When set to the `null` value, that `null` value is converted to the empty string (`""`). For example,  `elt.innerHTML = null` is equivalent to `elt.innerHTML = ""`._
```

So I'm not sure it's worth describing what _doesn't_ happen, just what does happen.

Also I think it's worth adding this meta-guidance (or at least a link to it) to our page templates, since that's the main place people go to figure out how to write reference pages.

2023-07-27 23:42 UTC, wbamberg commented on files/en-us/web/api/canvasrenderingcontext2d/createpattern/index.md
> +    A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`): both are synonymous of `"repeat"`.
```suggestion
    A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`): both are synonyms of `"repeat"`.
```

"synonyms of" or "synonymous with".

2023-07-27 23:42 UTC, wbamberg commented on files/en-us/web/api/domimplementation/createdocument/index.md
> +  null
Is there a fight between different Prettier versions going on here?

2023-07-28 04:45 UTC, teoli2003 commented on files/en-us/web/api/domimplementation/createdocument/index.md
> +  null
Checking. I have not edited this by hand.

2023-07-28 16:19 UTC, Josh-Cena commented on files/en-us/web/api/canvasrenderingcontext2d/createpattern/index.md
> +    A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`): both are synonymous of `"repeat"`.
Also, "null" should be `null`

2023-08-02 08:36 UTC, Rumyra requested changes, later dismissed

2023-08-02 08:36 UTC, Rumyra commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +Parameter' types may have special behaviors described using extended attributes (like `[LegacyNullToEmptyString]`). Here is the list of such attributes, and the addition you have to do in the prose:
```suggestion
Parameter types may have special behaviors described using extended attributes (like `[LegacyNullToEmptyString]`). Here is the list of such attributes, and the addition you have to do in the prose:
```

2023-08-02 08:37 UTC, Rumyra commented
All looks good to me! Agree with @wbamberg suggestions and one nit :)

2023-10-25 05:44 UTC, wbamberg commented
@teoli2003 , are you coming back to this, or should we close it for now?

2024-01-10 10:51 UTC, bsmth commented
Hi @teoli2003 shall we close this for now?

2024-01-10 11:04 UTC, teoli2003 commented on files/en-us/web/api/canvasrenderingcontext2d/createpattern/index.md
> +    A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`): both are synonymous of `"repeat"`.
```suggestion
    A [`null`](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`): both are synonyms of `"repeat"`.
```

2024-01-10 11:15 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +    _When set to the `null` value, that `null` value is converted to the empty string (`""`), unlike the common behavior with strings (that would have converted it to the `"null"` string): `elt.inner
I've added a link in the template.

2024-01-10 11:16 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +    _When set to the `null` value, that `null` value is converted to the empty string (`""`), unlike the common behavior with strings (that would have converted it to the `"null"` string): `elt.inner
```suggestion
    _When set to the `null` value, that `null` value is converted to the empty string (`""`), so `elt.innerHTML = null` is equivalent to `elt.innerHTML = ""`._
```

2024-01-10 12:27 UTC, teoli2003 commented
> Hi @teoli2003 shall we close this for now?

I have fixed all open points and rebased. Let's ask for a re-review.

2024-01-13 04:09 UTC, Josh-Cena commented on files/en-us/web/api/cssstyledeclaration/setproperty/index.md
> +    as the empty string. A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`).
```suggestion
    as the empty string. A [`null`](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`).
```

Also, shouldn't this be merged with the previous sentence? "If null or unspecified, it is treated the same as the empty string (`""`)"

2024-01-13 04:09 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +  - : Add the following sentence at the end of the parameter description: _A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`)._
```suggestion
  - : Add the following sentence at the end of the parameter description: _A [`null`](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`)._
```

2024-01-13 04:09 UTC, Josh-Cena commented on files/en-us/web/api/domimplementation/createdocument/index.md
> +    prefix and colon plus the local root element name, of the document to be created. A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`"
```suggestion
    prefix and colon plus the local root element name, of the document to be created. A [`null`](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`).
```

2024-01-13 04:09 UTC, Josh-Cena commented on files/en-us/web/api/window/open/index.md
> +    A ["null"](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`).
```suggestion
    A [`null`](/en-US/docs/Web/JavaScript/Reference/Operators/null) value is treated the same as the empty string (`""`).
```

2024-07-10 14:31 UTC, Josh-Cena approved these changes

2024-07-10 22:39 UTC, Josh-Cena commented
I'm open to merging this if no other feedback is given before end of week.

2024-07-12 01:40 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_property_subpage_template/index.md
> +Also, some WebIDL extended attributes with specific meanings can be associated with the type. There are standard ways to document them, consult [Ìnformation contained in a WebIDL file](/en-US/docs/MD
```suggestion
Also, some WebIDL extended attributes with specific meanings can be associated with the type. There are standard ways to document them; consult [Information contained in a WebIDL file](/en-US/docs/MDN/Writing_guidelines/Howto/Write_an_API_reference/Information_contained_in_a_WebIDL_file#type_of_the_property) for more information.
```

2024-07-12 01:40 UTC, Josh-Cena commented on files/en-us/web/api/element/outerhtml/index.md
> +When set to the `null` value, that `null` value is converted to the empty string (`""`), so `elt.outerHTML = null` is equivalent to `elt.innerHTML = ""`.
```suggestion
When set to the `null` value, that `null` value is converted to the empty string (`""`), so `elt.outerHTML = null` is equivalent to `elt.outerHTML = ""`.
```

2024-07-12 15:36 UTC, Josh-Cena commented
Going to merge now. Thanks everyone!

2024-07-12 15:36 UTC, merged