CycleTracker Tutorial Proofread: HTML and CSS
mdn/content pull request #28267
Opened 2023-07-30 03:54 UTC by TurekBot

### Description

Fixing a few small typographical mistakes, leaving the tutorial clearer and more internally consistent.

### Motivation

To smooth out any bumps that might otherwise give readers unnecessary pause.

I'm a technical writer by education, so I figured I'd lend a hand while I followed this tutorial. Previously, I filed [another PR](https://github.com/mdn/content/pulls?q=is%3Apr+author%3ATurekBot+CycleTracker) for this tutorial.

2023-07-31 15:39 UTC, bsmth commented
Hi @TurekBot - thanks for suggesting the changes. Taking a look now 👀

2023-07-31 15:42 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> -Our project is to create CycleTracker, a menstrual cycle tracker.
We don't accept whitespace-only changes, could you please revert this? There are some details in the writing guidelines: https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request

2023-07-31 15:45 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +Our static site HTML—with placeholder {{HTMLElement("link")}} and {{HTMLElement("script")}} elements for the yet-to-be-created external CSS and JavaScript files—is:
I think the original is easier to read here, could you revert this one also? The commas are better than dashes in this case.

2023-07-31 15:48 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +The {{HTMLelement("head")}} contains machine-readable information about the web application that—with the exception of the `<title>`, which may be displayed as the heading of the browser tab—is not v
Thanks for pointing it out. I think the original is easier to read. It's usually quite helpful to minimize the style changes such as changing commas to dashes or hyphens.

2023-07-31 15:50 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +To associate a {{HTMLelement("label")}} with a form control, each `<input>` has an [`id`](/en-US/docs/Web/HTML/Global_attributes/id) attribute matching the [`for`](/en-US/docs/Web/HTML/Attributes/for
I'm not sure about this one. The changes seem a little unnecessary to me.

2023-07-31 15:54 UTC, bsmth requested changes
Thanks a lot for the fixes. I've left some comments where I think the original is better. In general, it's always good to omit changes that don't have any semantic improvements to the content. This is due to the high volume of changes to review in this repository, and the additional overhead it adds for the more substantial changes. 

Thank you :)

2023-08-02 18:24 UTC, estelle commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +    <section id="past-periods">
The original is correct. The placeholder data is not included in the initial or final template - it's only included in the styling section.

2023-08-14 09:37 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +The {{HTMLelement("head")}} contains machine-readable information about the web application that—with the exception of the `<title>`, which may be displayed as the heading of the browser tab—is not v
Thanks, I think your first suggestion is good:

>The machine-readable information within the {{HTMLelement("head")}} of the web application is not visible to users, except for the <title>, which is displayed as the heading of the browser tab.

Shall we go with that instead?

2023-08-15 09:20 UTC, bsmth commented on files/en-us/web/progressive_web_apps/tutorials/cycletracker/html_and_css/index.md
> +The {{HTMLelement("head")}} contains machine-readable information about the web application that—with the exception of the `<title>`, which may be displayed as the heading of the browser tab—is not v
```suggestion
The {{HTMLelement("head")}} contains machine-readable information about the web application that's not visible to readers except for the `<title>`, which is displayed as the heading of the browser tab.
```

2023-08-15 09:23 UTC, bsmth approved these changes
Thanks @TurekBot - merging this one shortly, and welcome aboard. If you're looking for other ways to contribute, we have a [contributor task board](https://github.com/orgs/mdn/projects/25). Issues labeled with `good first issue` are a great place to start.

Thank you :)

2023-08-15 09:23 UTC, merged