proxy API compatibility details update
mdn/content pull request #28276
Opened 2023-07-30 23:47 UTC by rebloor

### Description

Fixes  #27512

2023-07-30 23:51 UTC, rebloor commented
@Rob--W did your request cover removing [proxy.register()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/register) and [proxy.unregister()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/unregister)?

2023-08-08 14:22 UTC, Rob--W requested changes

2023-08-08 14:22 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Firefox**: An extension cannot register a PAC file.
This is incorrect. As noted in the issue, both Firefox and Chrome can register PAC files, but in different ways. That's what I meant when I wrote "The only accurate part of this is that Firefox and Chrome's API differ."

2023-08-08 19:02 UTC, Rob--W commented
> @Rob--W did your request cover removing [proxy.register()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/register) and [proxy.unregister()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/unregister)?

Not specifically. But given their age and irrelevance, I wouldn't mind them being removed.

2023-08-08 23:20 UTC, rebloor commented
@Rob--W feedback addressed and proxy.register and proxy.register removed. Also see BCD update in Remove anachronistic proxy details ([#20513](https://github.com/mdn/browser-compat-data/pull/20513))

2023-08-25 15:58 UTC, Rob--W approved these changes

2023-08-27 16:58 UTC, merged