clipboarditem updates
mdn/content pull request #2829
Opened 2021-03-03 13:55 UTC by Rumyra

These include:

- Removal of draft from pages
- Updating constructor to include options and more info
- Adding `presentationStyle` property
- Adding additional members to interface page

https://github.com/mdn/content/issues/2514

2021-03-03 17:24 UTC, Rumyra commented
I know what's up - will fix 👍

2021-03-03 17:26 UTC, sideshowbarker commented
CI failure at https://github.com/mdn/content/pull/2829/checks?check_run_id=2022602955#step:7:72 says:

> error: The document's slug (Web/API/ClipboardItem/presentationStyle) doesn't match its disk folder name (en-us/web/api/clipboarditem/presentationStyle)

I guess the “doesn’t match” is that the linter expects the disk folder name to be all-lowercase: `presentationstyle`.

@mdn/core-yari-content if that’s in fact the problem, then it seems like the error message for this case could be improved to explicitly report something about the disk folder names needing to be all-lowercase…

2021-03-03 17:55 UTC, Rumyra commented
Yeh - I've seen this before - and you also have to do a github dance to fix because case 🤨

2021-03-03 19:43 UTC, jpmedley requested changes
@Rumyra,

Nice work!

@chrisdavidmills,

Since Chrome was leader on this API, I thought it was somewhat incumbent on me to take a pass at reviewing this.

Joe

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <p><strong>Note</strong>: Image format support varies by browser. See the browser compatibility table for the {{domxref("Clipboard")}} interface.</p>
I don't see this data on the `Clipboard` interface page. Is this being added to the BCD?

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <dt><code>ClipboardItemOptions {{optional_inline}}</code></dt>
```suggestion
  <dt><code>ClipboardItemOptions</code> {{optional_inline}}</dt>
```

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <dt><code>ClipboardItemOptions {{optional_inline}}</code></dt>
Making sure the rendered macro text isn't rendered as code.

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +<p>The below example requests a png image using the {{domxref("Fetch API")}}, and in turn, the {{domxref("Body.blob()", "responses' blob()")}} method, to create a new {{domxref("ClipboardItem")}} and
>write it to the clipboard, using the {{domxref("Clipboard API")}}.

 Can you be more specific?

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/gettype/index.html
> +<p class="summary"><span class="seoSummary">The <strong><code>getType()</code></strong> method of the {{domxref("ClipboardItem")}} interface returns a {{jsxref("Promise")}} that resolves with a {{dom
@garykac, your spec doesn't list the type of error thrown by `getType()`. We like to list the type of error on MDN. Is this non-normative, or not settled yet?

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/gettype/index.html
> +      <td>{{SpecName('Clipboard API','#dom-clipboarditem-gettype-type-type','ClipboardItem.getType()')}}</td>
@chrisdavidmills I don't know what Ruth's motivation is for changing this link. It's worth noting that one of our engineers suggested that we always prefer the links that begin with `#dom`. Since adopting that I've noticed that many of them follow such a regular pattern that I think I could automate constructing them.

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
```suggestion
 <dd>Returns an {{domxref("DOMTimeStamp")}} representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
```

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
From the spec:

>Let file-info be a new File object with name set to the name part of the HTML attribute contents, and lastModified set to the timestamp of the referenced file or 0 if the entry references a clipboard part.

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
@garykac, I might have gotten this wrong. I notice that many things named time stamp return a long long (frequently unsigned). Is the IDL supposed to say "DOMTimeStamp" instead of "long long"? If not, is "an absolute or relative number of milliseconds" the correct definition for this timestamp? Is there any significants to the fact that the timestamp in this interface is signed?

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/index.html
> +  <p><strong>Note:</strong> Neither <code>ClipboardItem.delayed</code> or <code>ClipboardItem.lastModified</code> have been implemented by any browsers at this time. Check the <a href="#browser_compa
```suggestion
  <p><strong>Note:</strong> Neither <code>ClipboardItem.delayed</code> nor <code>ClipboardItem.lastModified</code> have been implemented by any browsers at this time. Check the <a href="#browser_compatibility">compatibility table</a> for details.</p>
```

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/presentationstyle/index.html
> +  class="brush: js">var <em>presentationStyle</em> = <em>clipboardItem</em>.presentationStyle;</pre>
I've been seeing `<var>` used in stead of `<em>` in many places. It seems like these should be `<var>` since these are meant to note parts that would be variables in an actual script, and that element would make this markup syntactically correct.

2021-03-03 19:43 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/presentationstyle/index.html
> +<p>In the below example, we're returning all items on the clipboard via the {{domxref("clipboard.read()")}} method. Then logging the <code>presentationStyle</code> property.</p>
```suggestion
<p>In the below example, we're returning all items on the clipboard via the {{domxref("clipboard.read()")}} method, then logging the <code>presentationStyle</code> property.</p>
```

2021-03-03 19:48 UTC, chrisdavidmills commented
I am happy to defer to Joe for review on this (very busy this week). But let me know if there's anything specific you'd like me to look at.

2021-03-03 19:48 UTC, chrisdavidmills commented on files/en-us/web/api/clipboarditem/presentationstyle/index.html
> +  class="brush: js">var <em>presentationStyle</em> = <em>clipboardItem</em>.presentationStyle;</pre>
Yup, it should be `<var>` ideally.

2021-03-03 19:49 UTC, chrisdavidmills commented on files/en-us/web/api/clipboarditem/gettype/index.html
> +      <td>{{SpecName('Clipboard API','#dom-clipboarditem-gettype-type-type','ClipboardItem.getType()')}}</td>
I think previously it was just pointing to the def for the Interface, whereas Ruth was made it correct? I'm not bothered as long as it points to the right place.

2021-03-04 10:17 UTC, Rumyra commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
Oh thank you @jpmedley !

2021-03-04 10:43 UTC, Rumyra commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <p><strong>Note</strong>: Image format support varies by browser. See the browser compatibility table for the {{domxref("Clipboard")}} interface.</p>
It refers to the Chrome note under Clipboard -> read. However I'm inclined to remove this note - I could be getting into a rabbit hole of different browsers & different implemented MIME types, there's a huge amount of possible iterations...

2021-03-04 10:50 UTC, Rumyra commented on files/en-us/web/api/clipboarditem/presentationstyle/index.html
> +  class="brush: js">var <em>presentationStyle</em> = <em>clipboardItem</em>.presentationStyle;</pre>
Changed everywhere

2021-03-04 15:09 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <p><strong>Note</strong>: Image format support varies by browser. See the browser compatibility table for the {{domxref("Clipboard")}} interface.</p>
I can't speak to whether it should be in BCD. At some point, we will need to deal with that. Regardless this information needs to be easy to find from both here and `Clipboard.read()`.
@chrisdavidmills @Elchi3 Please advise.

2021-03-04 17:03 UTC, Rumyra commented on files/en-us/web/api/clipboarditem/clipboarditem/index.html
> +  <p><strong>Note</strong>: Image format support varies by browser. See the browser compatibility table for the {{domxref("Clipboard")}} interface.</p>
I'm going to think about this a little bit - so I may change my mind or come up with a solution... I'm going to write some things which may help with the previous comment:

As it stands browsers only support ClipboardItem data as an `image/png` type blob... (as far as `read` and `write` goes) FF & Safari support text too, as well as the promise resolve (but that's out of this convo scope)... how do we then uncomplicated this to the reader to show which MIME types are supported for which interfaces (clipboardItem) and methods (read & write).

🤔 OK... maybe the note should just reflect the png support and we consider again if implementations differ in the future. I would like to avoid a situation where maintenance of supported types is a pita ☺️

👍

2021-03-04 23:50 UTC, garykac commented on files/en-us/web/api/clipboarditem/gettype/index.html
> +<p class="summary"><span class="seoSummary">The <strong><code>getType()</code></strong> method of the {{domxref("ClipboardItem")}} interface returns a {{jsxref("Promise")}} that resolves with a {{dom
It should be normative, but it hasn't been discussed so it's missing from the spec.

Do we know which errors are returned by the current implementations?

2021-03-04 23:55 UTC, garykac commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
`long long` was likely copied from some other spec. Probably should have been `unsigned`. I'm comfortable making this change to the spec, but we'd have to check the implementations for compat.

`DOMTimeStamp` would probably be better but we'd have to raise that change more generally to get feedback.

Thanks for catching this.

2021-03-05 00:01 UTC, garykac commented on files/en-us/web/api/clipboarditem/index.html
> + <dd>Returns an integer representing the time at which the <strong><code>ClipboardItem</code></strong> was last modified.</dd>
I created a tracking bug for changing this to `DOMTimeStamp`: https://github.com/w3c/clipboard-apis/issues/138

2021-03-05 17:07 UTC, jpmedley commented on files/en-us/web/api/clipboarditem/gettype/index.html
> +<p class="summary"><span class="seoSummary">The <strong><code>getType()</code></strong> method of the {{domxref("ClipboardItem")}} interface returns a {{jsxref("Promise")}} that resolves with a {{dom
I don't. I don't have a convenient way to find out. 

We can leave it this way for now, I guess.

2021-03-05 17:11 UTC, jpmedley approved these changes
To Ruth and anyone else waiting on this. Thank you all for your patience.

2021-03-05 17:11 UTC, merged