ReadableStream.from() static method
mdn/content pull request #28316
Opened 2023-08-01 07:28 UTC by hamishwillee

This adds docs for the new `ReadableStream.from()` static method, added in FF117 in https://bugzilla.mozilla.org/show_bug.cgi?id=1772772

Related docs work can be tracked in #28282

2023-08-01 07:29 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Examples
Incomplete example - want to add some test for whether the method is supported. Also provide explanation of what it is doing. It is a little contrived.

2023-08-07 06:08 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +The method can be used to wrap iterable and async iterable objects as readable streams, including arrays, sets, arrays of promises, async generators, `ReadableStreams`, Node.js `readable` streams, an
FYI Under the hood, the way it works is much like the custom example here: https://pr28316.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/ReadableStream#convert_an_iterator_or_async_iterator_to_a_stream
- The result of iterating to `next()` is a promise (for a non-async iterator this will be already fulfilled or rejected)
- The code waits on the promise to resolve, then pushes the result to the stream's queues.

I could say that, and it might help explain how iterating an array of promises work. Or you could just accept that this works for any iterable or async iterable. Any thoughts on whether it could/should be said in some way?

2023-08-18 04:18 UTC, wbamberg requested changes

2023-08-18 04:18 UTC, wbamberg commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Convert an async iterator to a ReadableStream
We have a template structure for live samples: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples#traditional_live_samples. Although technically authors have a lot of flexibility in how to organize them, I'd prefer us to use a much more consistent approach, because it might make it possible for us to extract live samples and have them be usable in other contexts.

This would include having code blocks in a consistent order, with subheadings, and with prose in a consistent place (at the start of the example)

But maybe I'm fighting a losing battle here.

2023-08-18 04:18 UTC, wbamberg commented on files/en-us/web/api/readablestream/from_static/index.md
> +The code below uses a `for ... await` loop, as this method is the simplest.
It would be great to have some kind of real-world usage example. I find the whole readable streams thing so abstract. In particular it's obviously weird to create a readable stream from an array...so you can iterate it like an array. But I expect this would be quite hard to do (all the other stream examples I've seen look incredibly complicated to me).

2023-08-18 04:19 UTC, wbamberg commented
Thanks Hamish. I think it would be good if the examples here followed a more standard organization, and I don't think we should hide significant code. Otherwise this looks great.

2023-08-18 07:02 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Convert an async iterator to a ReadableStream
> But maybe I'm fighting a losing battle here.

@wbamberg I did it this way, in particular, because I understood that now the code blocks include their "type" the headings are not needed or wanted. With their removal I find the documentation easier to parse, because the isn't quite so much scrolling between the relevant bits.

If you tell me I must change, then I will, but I'm not keen :-)

2023-08-18 07:06 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +The code below uses a `for ... await` loop, as this method is the simplest.
You're not wrong - they are very abstract, which is why for [readable byte stream examples](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_byte_streams) I mocked the spec examples to pretend I had a read data socket.

In this case I couldn't find a real example in the spec or think of one myself. I mean I kind of can "I prefer readable streams to waiting on arrays of promises" so I do it this way. But it's not "really real".

Worth asking the spec authors?

2023-08-19 03:51 UTC, wbamberg commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Convert an async iterator to a ReadableStream
I can't really tell you you must change. I can say that unless examples are consistently organized then it won't be possible to include them in other contexts, and any tool which tries to do that will most likely throw them out (or maybe we will just throw out the explanatory prose, and hope the example still makes sense).

But I don't know if this use case is important enough to be worth the cost of imposing more constraints on authors. I think it is, but maybe others don't.

2023-08-21 01:01 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Convert an async iterator to a ReadableStream
I've added the sections in for the first example, unhiding the code that shows how logging works. In the second section I just have the JavaScript section: showing it once perhaps makes sense so there is no "magic" involved in the description, but showing it twice in the page when it is not central to the example seems unhelpful.

I "fairly" strongly feel that this use case is not workable, or even all that useful, and certainly not worth the constraint. Remember all the reasons we decided to remove the page inclusion macro - same problems. The "fairly" is because perhaps you have thought through some cases where content mismatch is not an issue.

I think these headings should be removed. But only after it's agree and https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Code_examples is updated :-)

2023-08-21 01:15 UTC, hamishwillee commented on files/en-us/web/api/readablestream/from_static/index.md
> +### Convert an async iterator to a ReadableStream
https://github.com/orgs/mdn/discussions/439

2023-08-21 02:04 UTC, wbamberg approved these changes
👍

2023-08-21 02:04 UTC, merged