New modue: CSS Scoping
mdn/content pull request #28354
Opened 2023-08-02 20:41 UTC by estelle

* add new CSS scoping module page
* Rewrite glossary "shadow tree"
* Add links from the other modules to this new page.
* Add links to this module from related selectors, attributes, and elements

2023-08-08 07:12 UTC, chrisdavidmills requested changes
Nice work @estelle; content all sounds good; I've left a few suggestions mostly on splitting larger paragraphs up a bit, and improving the reading flow.

2023-08-08 07:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_scoping/index.md
> +CSS styles are either global in scope or scoped to a {{Glossary("shadow tree")}}. Globally scoped styles apply to all the elements in the node tree, including custom elements in that tree, but do not
"shadow trees of which each custom element is composed" sounds a bit awkward. How about "shadow trees composing each custom element"?

2023-08-08 07:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_scoping/index.md
> +Within the CSS of a shadow tree, selectors can't see elements outside the tree and selectors outside of a shadow tree don't apply within. Custom elements have their own shadow trees. Each shadow tree
```suggestion
Within the CSS of a shadow tree, selectors don't select elements outside the tree, either in the global scope or in other shadow trees. Each custom element has its own shadow tree, which contains all the components that make up the custom element (but not the custom element, or "host", itself).

Sometimes it's useful to be able to style a host from inside the shadow tree context. The CSS scoping module makes this possible by defining selectors that:

- Enable a shadow tree to style its host.
- Enable external CSS to style elements within a shadow DOM (but only if the associated custom element is set up to accept external styles).
```

2023-08-08 07:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_scoping/index.md
> +> **Note:** Despite the name, the {{CSSXref(":scope")}} pseudo-class, which represents elements that are a reference point, or scope, for selectors to match against, is defined in the [CSS pseudo-cla
```suggestion
> **Note:** Despite the name, the {{CSSXref(":scope")}} pseudo-class, which represents elements that are a reference point (or scope) for selectors to match against, is defined in the [CSS pseudo-classes](/en-US/docs/Web/CSS/CSS_pseudo-classes) module. It is otherwise unrelated to the CSS scoping module, which is focused on scoping as it pertains to the Shadow DOM scoping mechanism.
```

2023-08-08 07:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_scoping/index.md
> +  - : Web components concepts and usage, with an introduction to the different technologies used to create reusable custom elements whose functionality is encapsulated away from the rest of the code.
```suggestion
  - : An introduction to the different technologies used to create reusable web components — custom elements whose functionality is encapsulated away from the rest of your code.
```

2023-08-08 17:32 UTC, estelle commented on files/en-us/glossary/shadow_tree/index.md
> +A shadow tree is a hidden set of standard DOM nodes which is attached to a standard DOM node that serves as a host. The hidden nodes are not directly visible using regular DOM functionality. They req
rewrote it.

2023-08-09 07:40 UTC, chrisdavidmills commented on files/en-us/glossary/shadow_tree/index.md
> +A shadow tree is a hidden set of standard DOM nodes which is attached to a standard DOM node that serves as a host. The hidden nodes are not directly visible using regular DOM functionality. They req
Better, but I got the editing bug this morning and rewrote it a bit more. I hope that's OK. I felt like it still needed to flow a bit better.

2023-08-09 07:44 UTC, chrisdavidmills approved these changes
Looks great, nice work @estelle. Approving, but leaving unmerged for now so you can have a look at my edits on the shadow tree glossary page and make sure you are happy with them first.

2023-08-10 00:37 UTC, merged