FF117 Expr.Featr. CSS Custom Highlights API
mdn/content pull request #28384
Opened 2023-08-04 04:33 UTC by hamishwillee

FF117 supports the  [CSS Custom Highlight API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Custom_Highlight_API) behind a preference/in preview. This adds an experimental feature note.

Other docs work can be tracked in #28291

2023-08-07 12:38 UTC, Elchi3 requested changes

2023-08-07 12:38 UTC, Elchi3 commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +The [`CSS::highlight`](/en-US/docs/Web/CSS/::highlight) pseudo-element is used to apply styles to a registered highlight.
```suggestion
The CSS [`::highlight`](/en-US/docs/Web/CSS/::highlight) pseudo-element is used to apply styles to a registered highlight.
```

2023-08-07 12:38 UTC, Elchi3 commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>111</td>
```suggestion
      <td>117</td>
```

2023-08-07 12:38 UTC, Elchi3 commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>111</td>
```suggestion
      <td>117</td>
```

2023-08-07 12:38 UTC, Elchi3 commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>111</td>
```suggestion
      <td>117</td>
```

2023-08-07 23:30 UTC, hamishwillee commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>111</td>
Duh! Thank you.

2023-08-07 23:31 UTC, hamishwillee commented
Thanks - accepted all.

2023-08-08 07:37 UTC, Elchi3 approved these changes

2023-08-08 07:37 UTC, merged