New CSS data-type: generic family
mdn/content pull request #28405
Opened 2023-08-05 00:36 UTC by estelle

Part of https://github.com/openwebdocs/project/issues/176

enumerated values are defined in https://drafts.csswg.org/css-fonts/#generic-family-value and https://drafts.csswg.org/css-fonts/#generic-font-families

2023-08-07 09:00 UTC, chrisdavidmills requested changes
@estelle looking good! I have made a few comments, but nothing major.

2023-08-07 18:43 UTC, estelle commented on files/en-us/web/css/generic-family/index.md
> +  - : The default user interface monospace font. See the definition of` monospace` above.
```suggestion
  - : The default user interface monospace font. See the definition of `monospace` above.
```

2023-08-07 18:44 UTC, estelle commented on files/en-us/web/css/generic-family/index.md
> +  line-height: 2;
```suggestion
  font-size: 1.5rem;
  line-height: 2;
```

2023-08-07 18:44 UTC, estelle commented on files/en-us/web/css/generic-family/index.md
> +{{EmbedLiveSample("Examples", "500", "250")}}
```suggestion
{{EmbedLiveSample("Examples", "500", "300")}}
```

2023-08-07 18:46 UTC, estelle commented on files/en-us/web/css/generic-family/index.md
> +  - : Glyphs have plain stroke endings, without ornamentation. Example sans-serif fonts include Open Sans, Fira Sans, Lucida Sans, Lucida Sans Unicode, Trebuchet MS, Liberation Sans, and Nimbus Sans
```suggestion
  - : A font without serifs; glyphs have plain stroke endings, without ornamentation. Example sans-serif fonts include Open Sans, Fira Sans, Lucida Sans, Lucida Sans Unicode, Trebuchet MS, Liberation Sans, and Nimbus Sans L.
```

2023-08-08 07:45 UTC, chrisdavidmills approved these changes
Yessssss, perfect. Approving!

2023-08-08 07:45 UTC, merged