Fix some low-hanging fruit in event subpage instructions.
mdn/content pull request #2842
Opened 2021-03-03 21:30 UTC by jpmedley

This is not an exhaustive update of the page. The link for the example event was to a deprecated page. In the process of updating that, I looked for other low hanging fruit. I hope you'll accept it in the spirit it was intended: not wanting perfect to be the enemy of good.

2021-03-03 21:32 UTC, jpmedley commented
By the way, because we've hidden compat tables for keys not present in the database, the example table on this page does not show up. https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_event_subpage_template

2021-03-04 00:05 UTC, nschonni commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.html
> +<h2 id="Browser_compatibility">Browser compatibility</h2>
This ID already exists on 42, which is why it has the number
```suggestion
<h2 id="Browser_compatibility_2">Browser compatibility</h2>
```

2021-03-04 06:56 UTC, chrisdavidmills requested changes
Some nice updates here, thanks @jpmedley . Just one comment from me to address, and one from @nschonni , and we should be done.

2021-03-04 06:56 UTC, chrisdavidmills commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.html
> +  <div>\{{APIRef("<em>GroupDataName</em>")}} — this generates the left hand reference sidebar showing quick reference links related to the current page. For example, every page in the <a href="/en-US
"jjson" -> "json"

2021-03-04 14:42 UTC, jpmedley commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.html
> +<h2 id="Browser_compatibility">Browser compatibility</h2>
If a contributor cuts and pasts this page, they would need to change this ID. To eliminate that requirement, I've changed the ID of the heading in line 42 instead.

2021-03-04 14:42 UTC, jpmedley commented on files/en-us/mdn/structures/page_types/api_event_subpage_template/index.html
> +  <div>\{{APIRef("<em>GroupDataName</em>")}} — this generates the left hand reference sidebar showing quick reference links related to the current page. For example, every page in the <a href="/en-US
Fixed.

2021-05-26 06:14 UTC, sideshowbarker approved these changes

2021-05-26 07:12 UTC, chrisdavidmills approved these changes
LGTM!

2021-05-26 07:12 UTC, merged