New CSS data type: <absolute-size>
mdn/content pull request #28461
Opened 2023-08-08 19:37 UTC by estelle

Part of the CSS fonts module (see https://github.com/openwebdocs/project/issues/176)

2023-08-09 17:53 UTC, dipikabh requested changes
Thanks for adding these pages, @estelle. I've added some edits/comments/questions.

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/absolute-size/index.md
> +
```suggestion
## Examples

### Comparing the <absolute-size> keyword values

```
We need to add an H3 under "Examples"
(this is just one of the templates where we added this guideline: [CSS property page template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_property_page_template#examples))

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/absolute-size/index.md
> +- CSS {{cssxref("font")}} and {{cssxref("font-size")}} properties
```suggestion

```
we can probably remove this point because the links are in intro para

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/absolute-size/index.md
> +{{EmbedLiveSample('Examples', '100%', 400)}}
```suggestion
{{EmbedLiveSample('Comparing the absolute-size keyword values', '100%', 400)}}
```
I hope that link will work

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +The **`<relative-size>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) describes relative size keywords. The `<relative-size>` values define a size relative to the computed s
```suggestion
The **`<relative-size>`** [CSS](/en-US/docs/Web/CSS) [data type](/en-US/docs/Web/CSS/CSS_Types) describes relative size keywords. The `<relative-size>` keywords define a size relative to the computed size of the parent element. This data type is used in the {{cssxref("font")}} shorthand and {{cssxref("font-size")}} properties.
```

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +The values of the `<relative-size>` keywords are relative to the current size the element would otherwise be. If the inherited size was defined using an {{cssxref("absolute-size")}}, the `<relative-s
```suggestion
The `<relative-size>` keywords are relative to the current size of the element. If the inherited size is defined using an {{cssxref("absolute-size")}} keyword, the `<relative-size>` value equates to the adjacent size in the [`<absolute-size>` table](/en-US/docs/Web/CSS/absolute-size#description). Otherwise, the relative increase or decrease in size is between 120% and 150%.
```
- can we explain or link to "inherited size"? How is inherited size related to current size?
- We don't refer to "adjacent size" in the table on `<absolute-size>` page, that makes the second sentence a bit unclear

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +```
The syntax can be moved to the "Syntax" section and "Formal syntax" should be deleted

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +  <li class="larger">font-size: larger;</li>
```suggestion
  <li class="smaller">font-size: smaller</li>
  <li>font-size is not specified</li>
  <li class="larger">font-size: larger</li>
```
We don't need the ending semi-colon in text display

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +
```suggestion
## Examples

### Comparing the <relative-size> keyword values
```

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +{{EmbedLiveSample('Examples', '100%', 100)}}
```suggestion
{{EmbedLiveSample('Comparing the relative-size keyword values', '100%', 100)}}
```

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/relative-size/index.md
> +- CSS {{cssxref("font")}} and {{cssxref("font-size")}} properties
```suggestion

```

2023-08-09 17:53 UTC, dipikabh commented on files/en-us/web/css/absolute-size/index.md
> +  <li class="xxx-large">font-size: xxx-large;</li>
```suggestion
  <li class="xx-small">font-size: xx-small</li>
  <li class="x-small">font-size: x-small</li>
  <li class="small">font-size: small</li>
  <li class="medium">font-size: medium</li>
  <li class="large">font-size: large</li>
  <li class="x-large">font-size: x-large</li>
  <li class="xx-large">font-size: xx-large</li>
  <li class="xxx-large">font-size: xxx-large</li>
```
I believe we don't need the semi-colons in text displays

2023-08-10 00:02 UTC, estelle commented on files/en-us/web/css/absolute-size/index.md
> +  <li class="xxx-large">font-size: xxx-large;</li>
we don't need them, but i find it much easier to read with the semi-colons

2023-08-10 00:06 UTC, estelle commented on files/en-us/web/css/absolute-size/index.md
> +The deprecated HTML `size` attribute, with a computed value between `1` and `7`, set the size of the font. The attribute value was either an integer between `1` and `7` or a relative value, preceded
The link is to a different size attribute, which is not deprecated. so, we can't and shouldn't link.

2023-08-10 00:17 UTC, estelle commented on files/en-us/web/css/absolute-size/index.md
> +### Comparing the <absolute-size> keyword values
```suggestion
### Comparing the keyword values
```

2023-08-10 00:31 UTC, estelle commented on files/en-us/web/css/relative-size/index.md
> +{{EmbedLiveSample('Comparing the relative-size keyword values', '100%', 100)}}
```suggestion
{{EmbedLiveSample('Comparing the keyword values', '100%', 100)}}
```

2023-08-10 00:31 UTC, estelle commented on files/en-us/web/css/absolute-size/index.md
> +{{EmbedLiveSample('Comparing the absolute-size keyword values', '100%', 400)}}
```suggestion
{{EmbedLiveSample('Comparing the keyword values', '100%', 400)}}
```

2023-08-10 00:31 UTC, estelle commented on files/en-us/web/css/relative-size/index.md
> +### Comparing the <relative-size> keyword values
```suggestion
### Comparing the keyword values
```

2023-08-10 00:34 UTC, estelle commented on files/en-us/web/css/absolute-size/index.md
> +  - : An absolute size 60% the size of `medium`. Mapped to `size="1"`.
These values are rarely used. The only reason they exist is because of the size attribute. i added "to the deprecated `size" to each

2023-08-10 00:35 UTC, estelle commented
Thanks for the review. I kept the links in the see also, the semi colons in the really long example, and the formal syntax because there is no bcd bringing the values in ... yet. and there may not be, so want to keep it (there are other values that do the same).

2023-08-10 16:27 UTC, dipikabh commented
> Thanks for the review. I kept the links in the see also, the semi colons in the really long example, and the formal syntax because there is no bcd bringing the values in ... yet. and there may not be, so want to keep it (there are other values that do the same).

Thanks for the updates! They're looking good.

The "Formal syntax" pulls in data from webref I believe using the `{{csssyntax}}` macro. If that macro is not yielding any data or up-to-date syntax (you can check in your local preview using the macro), I think we should move the syntax out to the "Syntax" section like on the [`<overflow>`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow_value#syntax) page. Some data type pages have both "Syntax" and "Formal syntax" sections ([`<color-interpolation-method>`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-method)) and a lot of the data type pages don't seem to have the "Formal syntax" section.

2023-08-10 20:05 UTC, estelle commented
Thanks. done. I also changed the presentation of the overflow to plain (was CSS, but it shouldn't be in a CSS style play section)

2023-08-15 18:32 UTC, dipikabh approved these changes
Thank you!

(makes me wonder if I should update the code fencing on [`<basic-shape>` page](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#shape_functions) from `css` to `plain`.)

2023-08-15 18:33 UTC, merged