Fix #28475
mdn/content pull request #28495
Opened 2023-08-10 14:56 UTC by Arisch24

Describe that all heading elements are block-level by default.

### Description

Add description for headings which are displayed as block-level

### Motivation

Better description for readers

### Additional details

### Related issues and pull requests

Fixes #28475

2023-08-10 16:59 UTC, dipikabh requested changes
Hello @Arisch24! Thanks for adding the clarifying text to fix the doc issue. I've suggested a rephrase and addition of a link to our glossary.

2023-08-10 16:59 UTC, dipikabh commented on files/en-us/web/html/element/heading_elements/index.md
> +The **`<h1>`** to **`<h6>`** [HTML](/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest. All heading elements are blo
suggesting a rephrase and adding some more info:

```suggestion
The **`<h1>`** to **`<h6>`** [HTML](/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest. By default, all heading elements create a [block-level ](/en-US/docs/Glossary/Block-level_content) box in the layout, starting on a new line and taking up the full width available in their containing block.
```

2023-08-11 01:11 UTC, Arisch24 commented on files/en-us/web/html/element/heading_elements/index.md
> +The **`<h1>`** to **`<h6>`** [HTML](/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest. All heading elements are blo
Noted with that @dipikabh. I will get on it right away.

2023-08-11 15:58 UTC, dipikabh approved these changes
Thank you, @Arisch24! Congrats on landing your first PR.

Welcome to the MDN project 🎉

2023-08-11 15:58 UTC, merged

2023-08-12 02:00 UTC, Arisch24 commented
Your welcome @dipikabh and thank you for the guidance.