feat: Adding information about billing address shipping address
mdn/content pull request #28509
Opened 2023-08-11 03:13 UTC by CBID2

### Description
This PR adds a note explaining how to distinguish between a user's address for shipping and billing purposes. 

### Motivation

Mentioning these tokens will help developers understand how to use the `autocomplete` attribute more effectively.
### Additional details

### Related issues and pull requests
Fixes #20180

2023-08-16 17:16 UTC, dipikabh requested changes
Thanks @CBID2 for adding the clarifying text.

Other than this fix, there is a larger issue of explaining sections, tokens, the order of the tokens in the `autocomplete` attribute page - if you fancy doing another PR for that.
(see https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete)

2023-08-16 17:16 UTC, dipikabh commented on files/en-us/web/html/attributes/autocomplete/index.md
> +    > - "`billing`": means the provided street address is where to send the receipt of the purchased product or service.
We don't necessarily need to add a note for this info. Let's add the following text after "`postal-code`":

```suggestion
  - "`shipping`"
     - : The street address to send the product. This can be combined with other tokens, such as "`shipping street-address`" and "`shipping address-level2`".
  - "`billing`"
     - : The street address to associate with the form of payment used. This can be combined with other tokens, such as "`billing street-address`" and "`billing address-level2`".
```

2023-08-16 22:52 UTC, CBID2 commented
> Thanks @CBID2 for adding the clarifying text.
> 
> Other than this fix, there is a larger issue of explaining sections, tokens, the order of the tokens in the `autocomplete` attribute page - if you fancy doing another PR for that. (see https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete)

Hey @dipikabh. Can you merge this PR first? It'll make it easier for me to make the other PR without having to worry about reverting commits on the other branch.

2023-08-17 03:32 UTC, dipikabh approved these changes
Thank you @CBID2 for adding this info 👍

2023-08-17 03:33 UTC, merged

2023-08-17 03:34 UTC, CBID2 commented
> Thank you @CBID2 for adding this info 👍 

You're welcome @dipikabh! :) I followed you on LinkedIn too! :)

2023-08-17 23:16 UTC, CBID2 commented
> Thank you @CBID2 for adding this info 👍

Hi @dipikabh, I raised the issue for the larger PR. I'm still struggling with what the exact problem is, so can you elaborate on it here please: https://github.com/mdn/content/issues/28636