Fixes issue #28346 - Table height attribute.
mdn/content pull request #28519
Opened 2023-08-11 10:09 UTC by rimjhp-06

### Description

Added warning for height attribute in the table element.

### Motivation

### Additional details

### Related issues and pull requests

2023-08-12 01:04 UTC, estelle reviewed
I am not sure `height` was ever an attribute for `table`. While it works, i can't seem to find it in the specs: HTML 1 did not have the table element. HTML 3.2 does have it, but it's not in 3.2, https://www.w3.org/TR/2018/SPSD-html32-20180315/#table. And it's not in 4.01 either: https://www.w3.org/TR/1999/REC-html401-19991224/struct/tables.html#edef-TABLE. 


Where did you find it listed and defined, if anywhere?

2023-08-12 12:36 UTC, rimjhp-06 commented
> I am not sure `height` was ever an attribute for `table`. While it works, i can't seem to find it in the specs: HTML 1 did not have the table element. HTML 3.2 does have it, but it's not in 3.2, https://www.w3.org/TR/2018/SPSD-html32-20180315/#table. And it's not in 4.01 either: https://www.w3.org/TR/1999/REC-html401-19991224/struct/tables.html#edef-TABLE.
> 
> Where did you find it listed and defined, if anywhere

I did not find the issue.

2023-08-12 14:00 UTC, Josh-Cena commented
@estelle see #28346

2023-08-12 14:02 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +  - : Warning: Some browser misinterpret this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net/zQNS4/1/)
```suggestion
  - : `<table>` does not support the `height` attribute. Some browser have a non-standard interpretation of this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net/zQNS4/1/)
```

2023-08-12 14:02 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +  - : Warning: Some browser misinterpret this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net/zQNS4/1/)
Also, do not use jsfiddle in this case. You should be linking to a descriptive source (because there's no normative text for this) explaining which browsers and why.

2023-08-13 05:54 UTC, estelle commented on files/en-us/web/html/element/table/index.md
> +- `height` {{Deprecated_inline}}
it's not really deprected, as it never officially existed. So, we shouldn't use the deprecated_inline macro. Instead, let's include the support for a never included in any spec  `height` attribute as a note rather than listing it in the list of attributes.

2023-08-21 16:11 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +    NOTE - : `<table>` does not support the `height` attribute. Some browser have a non-standard interpretation of this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net
```suggestion

> **Note:** `<table>` does not support the `height` attribute. Some browsers have a non-standard interpretation of this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net/zQNS4/1/)
```

And the JS fiddle does not provide "more info" because I expect it to be about browser compatibility.

2023-08-21 16:11 UTC, Josh-Cena requested changes
See above

2023-08-21 16:23 UTC, estelle commented on files/en-us/web/html/element/table/index.md
> +    NOTE - : `<table>` does not support the `height` attribute. Some browser have a non-standard interpretation of this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net
Here's a suggestion:

```suggestion
 
> **NOTE:** While no HTML specification includes `height` as a `<table>` attribute, some browsers support a non-standard interpretation of height. The unitless value sets a minimum absolute height in pixels. If set as a percent value, the minimum table height will be relative to the height of the parent container.
```
I prefer not linking to the fiddle for a myriad of reasons, but mainly no example showing this will pass my "let's link to this" because we are showing using non-standard practices. On MDN we only want to show models of what people should be doing. Any example with `height` is what people shouldn't be doing.

2023-08-21 16:33 UTC, rimjhp-06 commented on files/en-us/web/html/element/table/index.md
> +    NOTE - : `<table>` does not support the `height` attribute. Some browser have a non-standard interpretation of this attribute. For more info, visit [Setting height attribute](https://jsfiddle.net
Got your point.

2023-08-21 22:31 UTC, estelle commented on files/en-us/web/html/element/table/index.md
> +> **NOTE:** While no HTML specification includes `height` as a `<table>` attribute, some browsers support a non-standard interpretation of height. The unitless value sets a minimum absolute height in
```suggestion
> **NOTE:** While no HTML specification includes `height` as a `<table>` attribute, some browsers support a non-standard interpretation of height. The unitless value sets a minimum absolute height in pixels. If set as a percent value, the minimum table height will be relative to the height of the parent container.

```

2023-08-21 22:31 UTC, estelle approved these changes
Thank you. Congratulations on your first MDN content PR. Welcome to the team!

2023-08-21 23:24 UTC, Josh-Cena commented on files/en-us/web/html/element/table/index.md
> +> **NOTE:** While no HTML specification includes `height` as a `<table>` attribute, some browsers support a non-standard interpretation of height. The unitless value sets a minimum absolute height in
```suggestion
> **Note:** While no HTML specification includes `height` as a `<table>` attribute, some browsers support a non-standard interpretation of `height`. The unitless value sets a minimum absolute height in pixels. If set as a percent value, the minimum table height will be relative to the height of the parent container.
```

2023-08-21 23:25 UTC, Josh-Cena approved these changes
I assume the omission of "which browsers they are" is deliberate, in which case LGTM

2023-08-22 11:19 UTC, EzioMercer commented
I think it will be better to add this sentence at the end of warning: Use the CSS {{cssxref("height")}} property instead.

2023-08-22 16:37 UTC, merged

2023-08-23 19:48 UTC, EzioMercer commented
@estelle I think it's better to add this sentence after warning `Use the CSS {{cssxref("height")}} property instead` as was done for [width](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#width)