relnote(117): 'auto none' allowed for 'contain-intrinsic-size' CSS prop
mdn/content pull request #28522
Opened 2023-08-11 12:29 UTC by bsmth

The declaration `contain-intrinsic-size: auto none` is now supported.

__Docs:__

- [`contain-intrinsic-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size)

__Related issues and pull requests:__
- [ ] Parent issue https://github.com/mdn/content/issues/28292
- [ ] BCD - TODO

__Bugzilla:__
- https://bugzilla.mozilla.org/show_bug.cgi?id=1835813

__Resources:__
- https://phabricator.services.mozilla.com/D174583#inline-985747
- https://chromestatus.com/feature/6203168806928384
- https://wicg.github.io/display-locking/sample-code/contain-intrinsic-size-examples.html

2023-08-13 23:32 UTC, hamishwillee commented on files/en-us/mozilla/firefox/releases/117/index.md
> +- The `contain-intrinsic-size: auto none;` syntax is now supported which allows for using the last-remembered size of an element if possible and falls back to `contain-intrinsic-size: none` otherwise
```suggestion
- The `contain-intrinsic-size: auto none;` syntax is now supported, which allows for using the last-remembered size of an element if possible and falls back to `contain-intrinsic-size: none` otherwise.
```

2023-08-13 23:35 UTC, hamishwillee requested changes

2023-08-13 23:35 UTC, hamishwillee commented on files/en-us/mozilla/firefox/releases/117/index.md
> +- The `contain-intrinsic-size: auto none;` syntax is now supported, which allows for using the last-remembered size of an element if possible and falls back to `contain-intrinsic-size: none` otherwis
@bsmth Would be good to link to `contain-intrinsic-size` from the release note. Added just as a suggestion in case you want to do this in a different way.

```suggestion
- The [`contain-intrinsic-size: auto none;`](/en-US/docs/Web/CSS/contain-intrinsic-size) syntax is now supported, which allows for using the last-remembered size of an element if possible and falls back to `contain-intrinsic-size: none` otherwise.
```

Otherwise I think this is good. I am interested to see how you document the detail of "useful in layouts using proportional size" in the actual docs :-)

2023-08-14 11:34 UTC, bsmth commented on files/en-us/mozilla/firefox/releases/117/index.md
> +- The `contain-intrinsic-size: auto none;` syntax is now supported, which allows for using the last-remembered size of an element if possible and falls back to `contain-intrinsic-size: none` otherwis
> I am interested to see how you document the detail of "useful in layouts using proportional size" in the actual docs :-)

Yeah, same - I might need some help on this one. It applies to grid and multicol layouts, afaik (using fractions instead of concrete lengths).

2023-08-14 21:56 UTC, hamishwillee approved these changes
LGTM!

2023-08-14 21:56 UTC, merged