Adding clipboarditem to experimental notes
mdn/content pull request #2857
Opened 2021-03-04 14:10 UTC by Rumyra

https://github.com/mdn/content/issues/2514

2021-03-04 14:17 UTC, chrisdavidmills requested changes
Hola @Rumyra !

Nice bit of work here; just a couple of nitpicky bits for you to consider.

2021-03-04 14:17 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/experimental_features/index.html
> +<p>The {{domxref('ClipboardItem')}} interface of the {{domxref('Clipboard API')}} is now supported and {{domxref('Clipboard.write()')}} accepts a sequence of {{domxref('ClipboardItem','clipboard item
Small nit: "instead of previously implemented" > "instead of the previously implemented" ?

2021-03-04 14:17 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/experimental_features/index.html
> +   <th scope="col" style="vertical-align: bottom;">Release channel</th>
I'm sure these inline styles are not neccesary. We don't usually have these in tables, right?

2021-03-04 14:20 UTC, Rumyra commented on files/en-us/mozilla/firefox/experimental_features/index.html
> +   <th scope="col" style="vertical-align: bottom;">Release channel</th>
🤔 they run all the way through the file - I'm going to see what happens if I remove *all* of them 🙈

2021-03-04 14:23 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/experimental_features/index.html
> +   <th scope="col" style="vertical-align: bottom;">Release channel</th>
Hrm, weird! I've just played with the rendered page and tried toggling them on and off with the devtools, and they seem to make zero difference.

So feel free to remove them, provided that bit of cleanup doesn't take you too long.

2021-03-04 14:29 UTC, Rumyra commented on files/en-us/mozilla/firefox/experimental_features/index.html
> +   <th scope="col" style="vertical-align: bottom;">Release channel</th>
the `standard-table` class gives us the grey background which I think should be kept - however the `max-width` doesn't serve enough purpose to keep an inline style, so I've removed that 👍

2021-03-15 20:14 UTC, chrisdavidmills approved these changes
Looking great; thanks @Rumyra !

2021-03-15 22:41 UTC, merged