Update index.md
mdn/content pull request #28580
Opened 2023-08-16 10:21 UTC by cyberphor

### Description

Updates [Image Links](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#image_links) section to make it more clear the example shown uses a locally hosted image. 

### Motivation

I am suggesting this change after trying the example provided myself. I quickly realized the file wasn't on my computer. Therefore, I felt the example was a little misleading. 

### Additional details

None. 

### Related issues and pull requests

None.

2023-08-16 16:04 UTC, dipikabh requested changes
Thanks @cyberphor for adding the clarifying text!
I've added a few suggestions.

2023-08-16 17:59 UTC, estelle commented on files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
> +If you have an image you want to make into a link, use the {{htmlelement("a")}} element to wrap the local image file referenced with the {{htmlelement("img")}} element. The example below references a
I don't think this change is necessary. The first sentence requires no edits and should not include the word local. The `a` is used to create an element no matter where the image file is located.

If clarifying text is needed, in this case the  explanation could state the image is in the same directory as the HTML file. however, as best practices for file structure usually recommend storing images in an assets or images directory, maybe we should change the example to demonstrate these recommendations.

2023-08-16 18:21 UTC, cyberphor commented on files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
> +If you have an image you want to make into a link, use the {{htmlelement("a")}} element to wrap the local image file referenced with the {{htmlelement("img")}} element. The example below references a
Yes, after making the PR, I realized the word "local" was unnecessary. Yet, I still think some more context would be helpful (even if there was a sentence implying relative and absolute paths will be discussed later in the MDN material).

2023-08-17 03:46 UTC, dipikabh commented on files/en-us/learn/html/introduction_to_html/creating_hyperlinks/index.md
> +If you have an image you want to make into a link, use the {{htmlelement("a")}} element to wrap the local image file referenced with the {{htmlelement("img")}} element. The example below references a
I've made some suggestions here: https://github.com/mdn/content/pull/28580#discussion_r1296132975

2023-08-18 15:29 UTC, dipikabh approved these changes
Thanks @cyberphor!

Welcome to the MDN project 🎉

2023-08-18 15:29 UTC, merged