New page: font-display descriptor
mdn/content pull request #28592
Opened 2023-08-16 21:25 UTC by estelle

2023-08-17 14:45 UTC, dipikabh commented
We also have this page for the `font-display` descriptor: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display.
- Do you want to merge the info into the existing page?
- Also there's a matter of deciding where this descriptor should sit, with `@font-face` or `@font-feature-values`.

2023-08-18 01:36 UTC, dipikabh requested changes
Thanks for clarifying the difference between the `font-display` descriptor for `@font-feature-values` and `@font-face`. I've suggested some edits

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +The `font-display` descriptor for `@font-feature-values` determines the font display timeline by setting a default font-display value for `@font-face` rules for the same `font-family` name. When font
```suggestion
The `font-display` descriptor for `@font-feature-values` determines the font display timeline; it does so by setting a default `font-display` value for `@font-face` for the same `font-family` name. When `font-display` is omitted in `@font-face`, the user agent first looks for the `font-display` value that has been set via `@font-feature-values` for the relevant font-family. If no value is found, the user agent uses the `auto` value for `font-display`, in which case, the user agent determines the font display strategy.
```
- adding `;` to add a pause in the long sentence
- dropping 'at-rules` adjective to aid in readability

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +The font display timeline is based on a timer that begins the moment the user agent attempts to use a given downloaded font face. The timeline is divided into the three periods below which dictate th
```suggestion
The font display timeline is based on a timer that starts when the user agent attempts to use a specific downloaded font face. The timeline is divided into three periods, as listed below. These periods dictate the rendering behavior of any element that uses the font face.
```

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +- Font **swap** period: The swap period occurs after the block period, if any, if the font face has not yet been successfully loaded. Elements attempting to use the not-loaded font are rendered using
```suggestion
- Font **swap** period: The swap period occurs after the block period (if there is one) and if the font face has not yet been loaded successfully. Elements attempting to use the not-yet-loaded font are rendered using the next available fallback font face. The formerly invisible fallback font face is painted onto the screen. If the font loads successfully during the swap period, the text that was rendered in the fallback font is updated — or swapped — with the newly loaded font. This step triggers a repaint.
```

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +- Font **failure** period: If the font face has still not loaded when the swap period expires, or when the block period expires if there is no swap period (as is the case with `optional`), the user a
```suggestion
- Font **failure** period: If the font face has not loaded by the time the swap period expires or by the time the block period expires (if there is no swap period, as is the case with `optional`), the user agent treats the font as a failed load. As a result, the content becomes visible in the fallback font.
```

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +The `font-display` descriptor enables setting a default display policy for all `@font-face` rules, including those not under author control, such as third-party `@font-face` rules. This `font-display
```suggestion
The `font-display` descriptor allows you to set a default display policy for all `@font-face` rules, including those not under author control, such as third-party `@font-face` rules. When the `font-display` value is set via `@font-feature-values`, it becomes the default `font-display` value, and is applied to the entire font-family. However, any `font-display` value defined within individual `@font-face` blocks will override this default, but only for those blocks where the descriptor is defined.
```

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +{{cssinfo}}
Shall we remove this section? No data here currently

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +This `font-display` descriptor sets the default `font-display` for the "Leitura" font to `swap` for all `@font-face` at-rule blocks; noting their may be several `@font-face` block importing multiple
```suggestion
The `font-display` descriptor in this example sets the default `font-display` value for the "Leitura" font to `swap` for all the `@font-face` blocks. Now there might be several `@font-face` blocks importing multiple font files for a single font-family. If one of those `@font-face` blocks includes a `font-display` descriptor, the specified value will be used for that specific font file only. All other blocks not including a `font-display` descriptor will default to `swap` instead of the user-agent's standard default `auto`.
```

2023-08-18 01:36 UTC, dipikabh commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +- {{cssxref("css_fonts", "CSS fonts module")}}
```suggestion
- {{cssxref("@font-face/font-display", "font-display")}} descriptor for {{cssxref("@font-face")}} at-rule
- {{cssxref("css_fonts", "CSS fonts")}} module
```

2023-08-18 19:37 UTC, estelle commented on files/en-us/web/css/@font-feature-values/font-display/index.md
> +{{cssinfo}}
```suggestion
```

2023-08-19 14:12 UTC, dipikabh approved these changes
Thanks 👍

2023-08-19 14:12 UTC, merged