updated font-tech in @supports
mdn/content pull request #28597
Opened 2023-08-16 22:38 UTC by estelle

https://drafts.csswg.org/css-fonts/#color-font-tech-values

2023-08-16 22:41 UTC, estelle commented on files/en-us/web/css/@supports/index.md
> +| **Other <font-tech> values** |
```suggestion
| **Other `<font-tech>` values** |
```

2023-08-17 15:02 UTC, dipikabh requested changes

2023-08-17 15:02 UTC, dipikabh commented on files/en-us/web/css/@supports/index.md
> +The table below describes the font technologies (`<font-tech>`), including color font technologies (`<color-font-tech>`), font feature technologies (`<font-features-tech>`) and other available font t
```suggestion
The table below describes the font technologies (`<font-tech>`), including color font technologies (`<color-font-tech>`), font feature technologies (`<font-features-tech>`), and other available font technologies that can be queried using the `font-tech()` function:
```

2023-08-17 15:03 UTC, dipikabh approved these changes
Thanks, @estelle. Updates are good. I took the liberty of committing minor changes.

2023-08-17 15:04 UTC, merged