Document “AsyncGenerator” & “AsyncGeneratorFunction”
mdn/content pull request #2861
Opened 2021-03-04 20:00 UTC by DerekNonGeneric

Adds pages for the `AsyncGenerator` and `AsyncGeneratorFunction`
standard built-in global objects that had been missing from the
“Control abstraction objects” section.

Fixes: https://github.com/mdn/content/issues/2803

/cc @sideshowbarker @Ryuno-Ki @wbamberg

2021-03-04 21:46 UTC, Ryuno-Ki reviewed
I'm assigned the SVG team, so feel free to ignore comments you deem irrelevant (but it might be that others will bring them up again).
I focussed mainly on editorial bits here.
Not checked out and run locally.

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> + <dt>{{JSxRef("AsyncGenerator.prototype.next()")}}</dt>
I'm not sure, whether it'll have an effect, but why's `JSxRef` not lowercase here?

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> + <dd>Returns a {{jsxref("Promise")}} which will be rejected with an exception thrown from or uncaught from within the async generator function (also finishes the generator unless caught from within t
> with an exception thrown from or uncaught from within the async generator function

Doesn't roll so well here.
It feels like the sentence got too long, too.
Do you have an idea on how to rephrase?

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> +   <th scope="col">Specification</th>
I *think*, there are normally two more columns (even if cells remain empty), but don't take my word for it.

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  class="brush: js">new AsyncGeneratorFunction ([<var>arg1</var>[, <var>arg2</var>[, ...<var>argN</var>]],] <var>functionBody</var>)</pre>
A request might come up to drop the `var`s (in preparation of turning to Markdown for source).
If the `[arg1]` is meant to indicate an optional parameter, you might get the request to spread it out into several lines (each with another optional parameter), as `[arg1]` was often read as an Array containing `arg1`. (Let me know if you want to read up the discussion around it).

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dt><code>arg1, arg2, ... arg<em>N</em></code></dt>
Hm, strictly speaking, the commas are not part of the code.
```suggestion
  <dt><code>arg1</code>, <code>arg2</code>, ... <code>arg<em>N</em></code></dt>
```

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<div class="note">
This will need another class `notecard`.
```suggestion
<div class="notecard note">
```

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <p><strong>Note:</strong> {{jsxref("Statements/async_generator_function*", "async generator function")}}
This is now using an headline in the pattern.
```suggestion
  <h3>Note:</h3> 
  <p>{{jsxref("Statements/async_generator_function*", "async generator function")}}
```

2021-03-04 21:46 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<pre class="brush: js">var AsyncGeneratorFunction = Object.getPrototypeOf(async function*(){}).constructor;
We moved away from `var` declarations. Looks like you an use `const` here.

2021-03-04 22:09 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> + <dt>{{JSxRef("AsyncGenerator.prototype.next()")}}</dt>
I should have mentioned it in my initial comment, but this page was originally is based on [`…/global_objects/generator/index.html`](https://github.com/mdn/content/blob/5aa71dc0e462f41519819877a047d2237aeaddee/files/en-us/web/javascript/reference/global_objects/generator/index.html), so you will find it is the same over there as well. https://github.com/mdn/content/blob/5aa71dc0e462f41519819877a047d2237aeaddee/files/en-us/web/javascript/reference/global_objects/generator/index.html#L35-L42.

2021-03-04 22:15 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> + <dt>{{JSxRef("AsyncGenerator.prototype.next()")}}</dt>
That could also mean, that an update their (in another PR?) is required :)

We have so many stalled pages, that every helping hand is welcome!

2021-03-04 22:16 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  class="brush: js">new AsyncGeneratorFunction ([<var>arg1</var>[, <var>arg2</var>[, ...<var>argN</var>]],] <var>functionBody</var>)</pre>
> (Let me know if you want to read up the discussion around it).

Yes, please do share!

---

The reason why it is like this is since this page is originally based on [`…/global_objects/generatorfunction/index.html`](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/generatorfunction/index.html), so you will find it is the same over there as well. https://github.com/mdn/content/blob/5aa71dc0e462f41519819877a047d2237aeaddee/files/en-us/web/javascript/reference/global_objects/generatorfunction/index.html#L24-L27

2021-03-04 22:17 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  class="brush: js">new AsyncGeneratorFunction ([<var>arg1</var>[, <var>arg2</var>[, ...<var>argN</var>]],] <var>functionBody</var>)</pre>
#2202

2021-03-04 22:18 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dt><code>arg1, arg2, ... arg<em>N</em></code></dt>
Thanks, will take your suggestion. That should probably be fixed on the original page as well&hellip;

https://github.com/mdn/content/blob/5aa71dc0e462f41519819877a047d2237aeaddee/files/en-us/web/javascript/reference/global_objects/generatorfunction/index.html#L32

2021-03-04 22:21 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dt><code>arg1, arg2, ... arg<em>N</em></code></dt>
Yupp. I'd suggest to open a new PR for that, that can be reviewed in parallel.

2021-03-05 00:24 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> +   <th scope="col">Specification</th>
That does not appear to be the case from what I gather.

2021-03-05 00:28 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  class="brush: js">new AsyncGeneratorFunction ([<var>arg1</var>[, <var>arg2</var>[, ...<var>argN</var>]],] <var>functionBody</var>)</pre>
I would need some advice on what this is supposed to look like then. Suggestions are welcome if the intention is to go that route.

2021-03-05 00:41 UTC, DerekNonGeneric commented
Thanks for all the help so far @Ryuno-Ki &emdash; it should be in much better shape now!

Looking forward to seeing what the others think once they have a chance to take a look.

2021-03-05 00:42 UTC, DerekNonGeneric commented
Thanks for all the help so far @Ryuno-Ki — it should be in much better shape now!

Looking forward to seeing what the others think once they have a chance to take a look.

2021-03-05 06:56 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  class="brush: js">new AsyncGeneratorFunction ([<var>arg1</var>[, <var>arg2</var>[, ...<var>argN</var>]],] <var>functionBody</var>)</pre>
```js
new GeneratorFunction(functionBody)
new GeneratorFunction(arg1, functionBody)
new GeneratorFunction(arg1, arg2, functionBody)
```

2021-03-08 16:57 UTC, Rumyra commented
Currently having a look at this - it looks great thank you @DerekNonGeneric 

Going to be a bit of time as I think BCD and member pages need to be looked at... will keep it updated in this conversation 👍

2021-03-08 21:24 UTC, Ryuno-Ki reviewed
Look, a pending review (but only a small nitpick)

2021-03-09 17:02 UTC, Rumyra commented
I'm pushing updates to this branch now - with any luck it'll work 😬

2021-03-10 06:15 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +console.log((await asyncIterator.next()).value); // 20
I had not considered that top-level await could be problematic for examples due to browser compatibility (currently being behind a flag in Firefox nightly and all). Should we update this one here too?

```suggestion
asyncIterator.next().then(res => console.log(res.value)); // 20
```

2021-03-10 06:34 UTC, DerekNonGeneric commented
Thanks for the tidying up @Rumyra &mdash; it looks great! I like that you added an example that uses `for await`. 👍

> I'm inclined to merge this and create a new issue/issues for these however.

If it would be easier for you to keep track of the whole can of worms in a single PR (i.e., to ensure no content is duplicated), we can handle those in this PR if you would prefer. Feel free to continue work on this branch. Arguably we should at least add `next()`, `return()`, `throw()` pages in this PR to properly handle these two constructors. Up to you!

2021-03-12 16:45 UTC, Rumyra approved these changes
Thanks @DerekNonGeneric ☺️

2021-03-12 16:47 UTC, Rumyra commented
> Thanks for the tidying up @Rumyra — it looks great! I like that you added an example that uses `for await`. 👍
> 
> > I'm inclined to merge this and create a new issue/issues for these however.
> 
> If it would be easier for you to keep track of the whole can of worms in a single PR (i.e., to ensure no content is duplicated), we can handle those in this PR if you would prefer. Feel free to continue work on this branch. Arguably we should at least add `next()`, `return()`, `throw()` pages in this PR to properly handle these two constructors. Up to you!

Yes agreed - adding at least the methods to this PR would make it a nice rounded piece of work. We can do as previous and use the generator methods as a template

2021-03-13 13:49 UTC, DerekNonGeneric commented
> We can do as previous and use the generator methods as a template

I got that taken care of, which brought to light that the variable names in one of the examples needed updating.

---

I think this is all we need to get this merged now:
- [ ] a review of these new method pages
- [ ] getting that browser compat data PR merged

2021-03-16 16:10 UTC, Rumyra commented
These pages look great 🎉 

I've got a tiny edit, but also looked at the operator & statement pages which I think i might tackle tomorrow... I'll add them to this PR as we're still waiting for BCD

2021-03-24 17:57 UTC, ddbeck requested changes
Leaving a small suggestion here for you, @Rumyra.

Thanks to https://github.com/mdn/browser-compat-data/pull/9406, the BCD will go out in the next release (planned for tomorrow). But in https://github.com/mdn/browser-compat-data/pull/9592, I'm going to rename some features mentioned here. See my line comment for a fix.

Thank you!

2021-03-24 17:57 UTC, ddbeck commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<p>{{Compat("javascript.operators.async_function_star")}}</p>
```suggestion
<p>{{Compat("javascript.operators.generator_function")}}</p>
```

2021-03-25 12:21 UTC, Rumyra commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<p>{{Compat("javascript.operators.async_function_star")}}</p>
Thank you @ddbeck 💜

And actually makes much better sense :D

2021-05-26 07:04 UTC, sideshowbarker commented
@Rumyra Do you remember what this PR is waiting on? Glancing through the comments, it’s not clear to me at least…

2021-05-26 10:11 UTC, Rumyra commented
@sideshowbarker me :) The statement page still needs addressing - I'm just getting back to it now I'm back.

Here's a more clear checklist:

- [ ] Statement page
- [ ] Check interactive demos have been merged
- [ ] Update probably conflicts from bcd/frontmatter amends (these pages were made before those changes were)

2021-07-14 13:05 UTC, Rumyra commented
Soz I merged main into the latest commit and it's added a previous pr I made- I'll untangle after lunch 👍

2021-07-14 16:12 UTC, Rumyra commented
OK I think this is all ready to go - albeit being converted to markdown. Note I have removed the statement page as it's going to take a bit of work and was blocking this PR from going through. I will open an issue for it in https://github.com/mdn/content/projects/11 once we've got this going.

- I've merged main so hopefully we'll be conflict free 🤞
- Tidied up frontmatter and included new bcd & spec macros
- Interactive example has been tidied up here https://github.com/mdn/interactive-examples/pull/1784 (this needs to be merged before this pr so I'll keep it as draft for now)

This could do all do with a good review @wbamberg @Elchi3 @sideshowbarker 🙏

2021-07-14 18:35 UTC, wbamberg commented
About Markdown: it looks like there are 6 new files here:

files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html 
files/en-us/web/javascript/reference/global_objects/asyncgenerator/next/index.html 
files/en-us/web/javascript/reference/global_objects/asyncgenerator/return/index.html
files/en-us/web/javascript/reference/global_objects/asyncgenerator/throw/index.html 
files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html 
files/en-us/web/javascript/reference/operators/async_function_star_/index.html

...and updates to 3 existing ones:

files/en-us/web/javascript/reference/index.html
files/en-us/web/javascript/reference/operators/index.html 
files/en-us/web/javascript/reference/statements/index.html 

For the new files, I reckon it makes sense to convert to Markdown for this PR and land them they way, whether or not the rest of the JS docs are converted at that point. I'll try converting them and see what breaks.

For the existing files:

* if we can land this before the rest of the JS docs, we could keep them as HTML in this PR and they will get converted in the Markdown PR
* otherwise we could remove them from this PR entirely and file a follow-up for them, then this PR doesn't have to worry about Markdown timing at all

2021-07-14 22:41 UTC, wbamberg requested changes
I had quite a few comments, but some of them might be me not understanding this very well. 

There seems to be some systematic problem with a jsxref reference - I noted most of them but probably missed some, so it's worth checking them all.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/throw/index.html
> +<pre class="brush: js"><code><var>asyncGen</var>.throw(<var>exception</var>)</code></pre>
This should be just `<pre>` I think, with no internal markup.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>Note that <code>AsyncGeneratorFunction</code> is not a global object. It could be obtained by evaluating the following code.</p>
Is this the recommended or normal way to use this feature?

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dd>Names to be used by the function as formal argument names. Each must be a {{jsxref('String')}} that corresponds to a valid JavaScript identifier or a list of such strings separated with a comma
```suggestion
  <dd>Names to be used by the function as formal argument names. Each argument parameter must be a {{jsxref('String')}} that is a valid JavaScript identifier or a comma-separated list of such strings. For example: "<code>x</code>", "<code>theValue</code>", or "<code>a,b</code>".</dd>
```

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dd>A {{jsxref('String')}} containing the JavaScript statements comprising the function definition.
Do `eval()`-type warnings apply here? I found I couldn't execute the example in the console because of the CSP.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>{{jsxref("Statements/async_function*", "async generator function")}} objects created with the <code>AsyncGeneratorFunction</code> constructor are parsed when the function is created. This is less
`{{jsxref("Statements/async_function*", "async generator function")}` is giving me broken links here and I guess elsewhere in the page.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>{{jsxref("Statements/async_function*", "async generator function")}} objects created with the <code>AsyncGeneratorFunction</code> constructor are parsed when the function is created. This is less
Also if "async generator function" here is English, not an identifier (which I think it is) it should start with an uppercase letter.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>All arguments passed to the function are treated as the names of the identifiers of the parameters in the function to be created, in the order in which they are passed.</p>
Except for the final argument?

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>{{jsxref("Statements/async_function*", "async generator function")}} objects created with the <code>AsyncGeneratorFunction</code> constructor are parsed when the function is created. This is less
Is `{{jsxref("Statements/async_function*", "async function* expression")}` intended to have the same target as `{{jsxref("Statements/async_function*", "async generator function")}`?

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <h3>Note:</h3>
```suggestion
  <p><strong>Note:</strong></p>
```

(this is the syntax that the Markdown converter expects to see)

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <p>{{jsxref("Statements/async_generator_function*", "async generator functions")}} created with the <code>AsyncGeneratorFunction</code> constructor do not create closures to their creation contexts
Again "async generator functions" should be "Async generator functions" if it's not an identifier.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +<p>{{jsxref("Statements/async_function*", "async generator function")}} objects created with the <code>AsyncGeneratorFunction</code> constructor are parsed when the function is created. This is less
Also here and throughout this file,

`{{jsxref("Statements/async_function*", "async generator function")}`

should be

`{{jsxref("Statements/async_function*", "async generator function", "", "1")}`

to suppress code formatting, which isn't appropriate here. See https://github.com/mdn/yari/blob/main/kumascript/macros/jsxref.ejs#L10.

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<pre class="brush: js">async function* [<var>name</var>]([<var>param1</var>[, <var>param2[</var>, ..., <var>paramN</var>]]]) {
As I understand it we are not using this form of syntax any more. Instead we are using separate lines for the variations (cf https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/forEach#syntax).

2021-07-14 22:41 UTC, wbamberg commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<p>An <code>async function*</code> expression is very similar to and has almost the same syntax as a {{jsxref('Statements/async_function*', 'async function* statement', "", 1)}}. The main difference
Again, since "functions" is not an identifier this should be `{{jsxref("Functions", "functions", "", "1")}}`

2021-07-15 21:52 UTC, wbamberg commented
I've tried converting this to Markdown and found a couple of things worth changing, but it might be simpler to apply them after content reviews are done.

2021-07-29 11:37 UTC, Rumyra commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> +<p>The <code><strong>AsyncGenerator</strong></code> object is returned by an {{jsxref("Statements/async_function*", "async generator function")}} and it conforms to both the <a href="/en-US/docs/Web/
Yes this is the statement page, which I pulled from this PR because it's long and writing it was blocking this from going through.

>OK I think this is all ready to go - albeit being converted to markdown. Note I have removed the statement page as it's going to take a bit of work and was blocking this PR from going through. I will open an issue for it in https://github.com/mdn/content/projects/11 once we've got this going.

Updated the macros though

2021-07-29 19:11 UTC, Ryuno-Ki reviewed
I totally not got a notification for https://github.com/mdn/content/pull/2861#issuecomment-794166603 (but got sent to commits instead which I shrugged away).

I looked at the documentation with an engineer's point of view. There are some inconsistencies which you might want to pick up or leave them as is. Your call :-)

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <dd>A {{jsxref('String')}} containing the JavaScript statements comprising the function definition.
Most likely.
This reads like a pendant to `new Function()` to be, which poses security vulnerabilities (esp. when running untrusted code).

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +  <p>{{jsxref("Statements/async_generator_function*", "async generator functions")}} created with the <code>AsyncGeneratorFunction</code> constructor do not create closures to their creation contexts
What does global scope refers to here (in context of an ES module, for example. Would other modules see it, as in, it were defined on `window` as property)?

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +asyncGen.next().then(res => console.log(res.value)); // 20
Here you're only giving the console output, whereas before you also have shown the internal state.

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/global_objects/asyncgeneratorfunction/index.html
> +
Double blank line :eyes:

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +   <dt><code><var>paramN</var></code> {{optional_inline}}</dt>
In another file, you wrapped `N` in an `em` element.

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +   <dd>The name of an argument to be passed to the function. A function can have up to 255 arguments.</dd>
Why 255 (= 256-1 = 2^8-1)?
What happens if I exceed that number?

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<p>The following example defines an unnamed asynchronous generator function and assigns it to <code>x</code>. The function yields the square of its argument:</p>
Doesn't „unnamed” imply „asynchronous”?

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +<p>The following example defines an unnamed asynchronous generator function and assigns it to <code>x</code>. The function yields the square of its argument:</p>
`x` is a bad variable name. `square` might be better.
(I don't want to teach code newbies bad practices, so no offense).

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/async_function_star_/index.html
> +x(6).next().then(res => console.log(res.value)); // logs 36
You're using another comment style here as elsewhere.

2021-07-29 19:11 UTC, Ryuno-Ki commented on files/en-us/web/javascript/reference/operators/index.html
> + <dd>The <code>async function*</code> keywords defines an async generator function expression.</dd>
Is it plural (keywords) on purpose?

2021-07-29 19:11 UTC, Ryuno-Ki commented
I can see conflicting files here.

2021-07-30 01:00 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> +<pre class="brush: js">async function* createAsyncGenerator() {
`function* createAsyncGenerator` is the only way I have ever seen it and the other ways look strange to me.

2021-07-30 01:02 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/operators/index.html
> + <dd>The <code>async function*</code> keywords defines an async generator function expression.</dd>
`async` and `funtion` are two separate keywords, so yes, plural here please.

2021-07-31 11:35 UTC, Rumyra commented
Thanks! I'm working my way through all these comments 👍

>I can see conflicting files here.

There should be - things have changed, that'll be the last thing I look at 👍

2021-09-19 08:17 UTC, sideshowbarker commented
I’m not sure what this PR is waiting on currently, but it would be nice if we could get any remaining issues with it resolved and get it merged. In https://twitter.com/jcubic/status/1438938271761960968 someone who may be a potential contributor commented, _“it has a lot of Open PR, the last open (on the last page) it's from March”_ (with an implication being that having PRs around that have been open for ~6 months might scare off some other potential contributors).

2021-09-20 18:43 UTC, wbamberg commented
It looks like some review comments are not addressed yet, and after review it all needs to be converted to Markdown.

2021-09-20 19:22 UTC, DerekNonGeneric commented
@wbamberg, I was under the impression that @Rumyra was going to wrap things up here, but if she doesn't have the bandwidth to get it over the finish line at the moment, I am happy to do so. I know there were a lot of other tasks associated w/ getting this PR ready to land, so I will see if I can coordinate via Matrix in the next couple days to see what can be done on my end.

2021-09-20 19:23 UTC, Rumyra commented
I have a working branch for this pr addressing the reviews. Once that's complete I intend to convert to markdown. So I'm closing this pr in favour of smaller, markdown esc prs for these pages 👍

2021-09-21 12:20 UTC, closed without merging

2021-09-21 17:22 UTC, DerekNonGeneric commented on files/en-us/web/javascript/reference/global_objects/asyncgenerator/index.html
> +<p>The <code><strong>AsyncGenerator</strong></code> object is returned by an {{jsxref("Statements/async_function*", "async generator function", "", 1)}} and it conforms to both the <a href="/en-US/do
After reading the specification some more, I noticed that we may have made a copying error here when saying that it &ldquo;conforms to both the **iterable protocol** and **iterator protocol**&rdquo;, since it seems to actually conform to the **_async_ iterable protocol** and **_async_ iterator protocol**&hellip;

Refs: https://tc39.es/ecma262/#sec-asyncgenerator-objects

We should ensure that this is corrected in the PR that adds this page.

Unfortunately, it seems like MDN is missing pages for those protocols (previous links make no mention)&hellip;

/cc @Rumyra