promise support in Chrome clarification
mdn/content pull request #28643
Opened 2023-08-18 03:57 UTC by rebloor

### Description

Addresses the dev-doc-needed for [Bug 1711570](https://bugzilla.mozilla.org/show_bug.cgi?id=1711570) support promises on chrome namespace. Also includes miscellaneous edits.

2023-08-18 04:11 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +The rest of this section describes compatibility issues not captured in the tables.
@Rob--W @rpl I'm wondering whether we should consider moving all the items that can be to notes in the BCD, as quite a lot of them look as they could be. I think we could then consider merging the "differences" and "incompatibilities" pages. What do you think?

2023-08-31 17:15 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +The rest of this section describes compatibility issues not captured in the tables.
The BCD is not very readable or accessible. The purpose of this article is to give an overview of not necessarily API-specific differences that don't fit elsewhere. To answer the question "I am porting a Chrome extension to Firefox, what do I need to be aware of?" (or the other way around)

2023-08-31 17:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +The rest of this section describes compatibility issues not captured in the tables.
@Rob--W, so this is more a case of:
```suggestion
The rest of this section describes the main compatibility issues you should consider when building a cross-browser extension. Also, remember to check the browser compatibility tables, as they may contain additional compatibility information.
```

2023-08-31 20:45 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +The rest of this section describes compatibility issues not captured in the tables.
That looks good!

2023-09-01 15:31 UTC, Rob--W requested changes
Edge does not need to be mentioned separately; it's basically a Chrome clone.

2023-09-01 15:31 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Chrome:** Only `webRequest.onAuthRequired` supports asynchronous `webRequest.BlockingResponse` by supplying `'asyncBlocking'`.
```suggestion
- **In Chrome:** Only `webRequest.onAuthRequired` supports asynchronous `webRequest.BlockingResponse` by supplying `'asyncBlocking'`, through a callback instead of a Promise.
```

2023-09-01 15:31 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Firefox:** [`alert()`](/en-US/docs/Web/API/Window/alert), [`confirm()`](/en-US/docs/Web/API/Window/confirm), and [`prompt()`](/en-US/docs/Web/API/Window/prompt) are not supported in background
"Call"?

2023-09-01 15:31 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +  In Manifiest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) on most appropriate methods.
```suggestion
  In Manifest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) on most appropriate methods.
```

"Manifiest" should be spelled Manifest (this is done incorrectly in two other places)

2023-09-01 16:09 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +  - **In Chrome and Edge:** In Manifest V2, asynchronous APIs are implemented using callbacks. In Manifiest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/int
```suggestion
  - **In Chrome and Edge:** In Manifest V2, asynchronous APIs are implemented using callbacks. In Manifest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) on most appropriate methods. (cf. [Chrome bug 328932](https://crbug.com/328932))
```

2023-09-01 16:10 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Firefox:** [`alert()`](/en-US/docs/Web/API/Window/alert), [`confirm()`](/en-US/docs/Web/API/Window/confirm), and [`prompt()`](/en-US/docs/Web/API/Window/prompt) are not supported in background
```suggestion
- **In Firefox:** [`alert()`](/en-US/docs/Web/API/Window/alert), [`confirm()`](/en-US/docs/Web/API/Window/confirm), and [`prompt()`](/en-US/docs/Web/API/Window/prompt) are not supported in background pages.
```

2023-09-30 18:16 UTC, Rob--W approved these changes
Approved for merging, provided that all suggested changes are included. Feel free to copy-edit, but please request another review if the content is changed in substantial ways.

2023-09-30 18:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
>  > **Note:** However, this is _not_ part of the WebExtensions standard and may not be supported by all compliant browsers.
```suggestion
> **Note:** The `browser` namespace is supported by Firefox and Safari. Chrome does not offer the `browser` namespace, until [Chrome bug 798169](https://crbug.com/798169) is resolved.
```

Suggestion to reword, because there is actually cross-browser consensus on supporting the `browser` namespace; for details see the comments and links starting from https://github.com/w3c/webextensions/issues/113#issuecomment-1737533851.

2023-09-30 18:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
>  - **In Firefox**: Extensions must have the `"tabs"` permission.
Firefox and Chrome's behavior is the same here. Remove this whole section on `tabs.query`.

This was implemented by Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1679688.

2023-09-30 18:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Firefox:** As Firefox uses random UUIDs for `web_accessible_resources`, this property is unsupported.
```suggestion
- **In Firefox:** As Firefox uses random UUIDs for `web_accessible_resources`, this property is unsupported. Firefox extensions can fix their extension ID through the `browser_specific_settings.gecko.id` manifest key (see [browser_specific_settings.gecko](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#firefox_gecko_properties)).
```

Adding more details.

2023-10-01 22:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +  - **In Chrome:** In Manifest V2, asynchronous APIs are implemented using callbacks. In Manifest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-ove
```suggestion
  - **In Chrome:** In Manifest V2, asynchronous APIs are implemented using callbacks. In Manifest V3, support is provided for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) on most appropriate methods. (cf. [Chrome bug 328932](https://crbug.com/328932)) Callbacks are supported in Manifest V3 for backward compatibility, 
```

2023-10-01 22:56 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.md
> +- **In Chrome:** In Manifest V2, asynchronous APIs use callbacks to return values and {{WebExtAPIRef("runtime.lastError")}} to communicate errors.
```suggestion
- **In Chrome:** In Manifest V2, asynchronous APIs use callbacks to return values and {{WebExtAPIRef("runtime.lastError")}} to communicate errors. In Manifest V3, callbacks are supported for backward compatibility, along with support for [promises](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#promises) on most appropriate methods.
```

2023-10-02 00:51 UTC, merged