substantial revision to Intl.DurationFormat.format
mdn/content pull request #28708
Opened 2023-08-23 03:58 UTC by ben-allen

…normative changes related to fractionalDigits option, clarify usage in general

### Description

* Updated examples to reflect https://github.com/tc39/proposal-intl-duration-format/pull/150
* Made existing examples much more comprehensive/accurate

### Motivation

Recent normative changes have altered the behaviour of `fractionalDigits. Intl.DurationFormat.format() now defaults to displaying however many digits are necessary to display all components, rather than defaulting to 0 fractional digits displayed.

### Additional details

### Related issues and pull requests

Relates to https://github.com/tc39/proposal-intl-duration-format/pull/150

2023-08-23 04:37 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/format/index.md
> +</table>
No need for this table; it's already documented on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat/DurationFormat.

2023-08-23 04:38 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/format/index.md
> +// => "1 yr, 2 mths, 3 wks, 3 days, 4 hr, 5 min, 6 sec, 7 ms, 8 μs, 9 ns"
These arrows aren't recommended by our style guide; their absence is intentional.

2023-08-23 04:38 UTC, Josh-Cena requested changes
Hi @ben-allen thanks for the PR, but as a convention for `Intl` docs, the `format` pages are usually brief, and information about constructor options are included in the constructor page.

2023-08-23 09:02 UTC, ben-allen commented
Updated to remove most of the examples, redundant explanations, and => in comments

2023-08-23 16:29 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/durationformat/format/index.md
> -// "1y 2mo 3w 3d 4h 5m 6s 7ms 8μs 9ns"
Curious why these are removed?

2023-08-27 18:35 UTC, Josh-Cena reviewed
@ben-allen One remaining question (https://github.com/mdn/content/pull/28708#discussion_r1303273272) and then we can merge this. I think it's valuable to have comparisons of different styles under the en locale.

2023-08-28 13:43 UTC, Josh-Cena approved these changes
LGTM. Thanks for the update!

2023-08-28 14:08 UTC, merged