Glossary: argument to array
mdn/content pull request #28718
Opened 2023-08-23 18:52 UTC by estelle

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-08-23 18:55 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +- {{Glossary("parameter", "Difference between Parameter and Argument")}}
```suggestion
- {{Glossary("parameter", "Difference between parameter and argument")}}
```

2023-08-23 19:03 UTC, Josh-Cena commented on files/en-us/glossary/argument/index.md
> +The argument order within the function call should be the same order as the {{Glossary("parameter","parameters")}} in the function. When there are more arguments in a function call then parameters in
The "When there are more arguments in a function call then parameters in the function definition, the extra arguments are ignored." part is JavaScript-specific, which I don't think is appropriate. We should, however, explicitly document the correlation between parameters and arguments.

2023-08-23 19:03 UTC, Josh-Cena commented on files/en-us/glossary/array/index.md
> +Array in JavaScript look like this:
```suggestion
Arrays in JavaScript look like this:
```

2023-08-23 19:03 UTC, Josh-Cena commented on files/en-us/glossary/array/index.md
>  let catNamesArray = ["Jacqueline", "Sophia", "Autumn"];
```suggestion
// Arrays in JavaScript can hold different types of data
const myArray = [1, 2, 3, 4];
const catNamesArray = ["Jacqueline", "Sophia", "Autumn"];
```

2023-08-24 00:44 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +The argument order within the function call should be the same order as the {{Glossary("parameter","parameters")}} in the function. When there are more arguments in a function call then parameters in
```suggestion
The argument order within the function call should be the same as the {{Glossary("parameter","parameters")}} order in the function definition.
```

2023-08-28 22:45 UTC, hamishwillee commented
> Not sure why there are the extra commits, but they're not impacting the files changed, so i am going to pretend they aren't here

FYI This sometimes happens when you make changes in main rather than a branch, at the time that the changes have not merged. If you decide you have to clean it you can do a fetch and rebase on upstream.

2023-08-29 06:58 UTC, estelle commented
> > Not sure why there are the extra commits, but they're not impacting the files changed, so i am going to pretend they aren't here
> 
> FYI This sometimes happens when you make changes in main rather than a branch, at the time that the changes have not merged. If you decide you have to clean it you can do a fetch and rebase on upstream.

I spent at least 4 hours today fighting with git. i won in the end, but it was an epic battle.

2023-08-29 07:10 UTC, OnkarRuikar commented on files/en-us/glossary/ascii/index.md
> +**ASCII** (_American Standard Code for Information Interchange_) is a character encoding standard of 128 7-bit used by computers for converting letters, numbers, punctuation and control codes into di
```suggestion
**ASCII** (_American Standard Code for Information Interchange_) is a character encoding standard of 128 7-bit used by computers for converting letters, numbers, punctuation, and control codes into digital form.
```

2023-08-29 07:42 UTC, chrisdavidmills requested changes
Looking good @estelle. I've made a few suggestions, but overall this really improves these glossary entries.

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/arpa/index.md
> -**.arpa** (address and routing parameter area) is a {{glossary("TLD","top-level domain")}} used for Internet infrastructure purposes, especially reverse DNS lookup (i.e., find the {{glossary('domain
I don't disagree with any of the text that is here, but the whole entry seems slightly off. This is specifically about ARPA the TLD, whereas ARPA was also the Advanced Research Projects Agency, the original name for [DARPA](https://en.wikipedia.org/wiki/DARPA). Maybe add a little bit of text to point this out, or create separate entries for disambiguation purposes, something like ARPA_TLD and APRA_Agency?

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/array/index.md
> +Arrays in JavaScript look like this:
All your existing changes here look good. I'd also like you to do something about the sentences in the first paragraph — "Arrays are used to store multiple values in a single variable. This is compared to a variable that can store only one value." — which seem slightly off and possibly misleading.

How about "Arrays are used to store multiple values under a single variable name. A regular variable, on the other hand, can store only one value." ?

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/ascii/index.md
> +**ASCII** (_American Standard Code for Information Interchange_) is a character encoding standard of 128 7-bit used by computers for converting letters, numbers, punctuation and control codes into di
```suggestion
**ASCII** (_American Standard Code for Information Interchange_) is a 128-code point, 7-bit character encoding standard used by computers for converting letters, numbers, punctuation, and control codes into digital form.
```

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/ascii/index.md
> +ASCII has 128 code points. The first 33 points are non-printing control codes including the carriage return, line feed, tab, and several obsolete non-printable code stemming from its origin as telegr
```suggestion
The first 33 ASCII code points are non-printing control codes including the carriage return, line feed, tab, and several obsolete non-printable codes stemming from its origin of representing telegraph codes. The other 95 are printable characters, including digits (0-9), lowercase (a-z) and uppercase (A-Z) letters, and punctuation symbols.
```

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/ascii/index.md
> +Many computer systems instead use {{glossary("Unicode")}}, which has millions of code points, but the first 128 of these are the same as the ASCII set. Since 2007, {{Glossary("UTF-8")}} superseded it
```suggestion
Many computer systems instead use {{glossary("Unicode")}}, which has millions of code points, but the first 128 of these are the same as the ASCII set. {{Glossary("UTF-8")}} superseded ASCII on the Web in 2007.
```

2023-08-29 07:42 UTC, chrisdavidmills commented on files/en-us/glossary/mime/index.md
> +**MIME** "Multipurpose internet mail extensions" is a standard to describe documents in other forms besides ASCII text, e.g. audio, video, and images.
```suggestion
**MIME** (Multipurpose Internet Mail Extensions) is a standard to describe documents in other forms besides ASCII text, for example, audio, video, and images.
```

2023-08-29 15:40 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +The argument order within the function call should be the same as the {{Glossary("parameter","parameters")}} order in the function definition.
Added an example

2023-08-29 15:40 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +- {{Glossary("parameter", "Difference between parameter and argument")}}
i have to make this change in a different PR. My local git environment is somehow borked, and the issue has to do with this PR

2023-08-29 16:21 UTC, OnkarRuikar commented
>  My local git environment is somehow borked, and the issue has to do with this PR

@estelle looks like you created this branch on top of [`fontcss2`](https://github.com/estelle/content/pull/325) branch and not `main`. This happened because you had `fontcss2` checked out and then you ran `git checkout -b glosssary4` so those commits from `fontcss2` came along in this branch as well. But when you merged that PR a new merge commit `4327e3d` was created in the `main` branch. So your branch is diverging due to these two commits.

 I always use following command to avoid such accident:
```bash
# create a new branch from 'main' branch. Note the explicit use of 'main'.
git checkout -b glossary4 main
```

If you are feeling brave you can do following to win the battle against `git` :)
```
git checkout main

# sync local main with `mdn/content`
# here 'upstream' is my remote `git@github.com:mdn/content.git (push)` : https://github.com/estelle/content/blob/glossary4/CONTRIBUTING.md#forking-and-cloning-the-repository
git pull upstream main && git push

git checkout glossary4

# note down the complete commit hash of commit prior to the first `font-variant-css2 data type` commit
git log

# Undo all the commits in this PR and get all the changes as modified files
git rest --soft <noted-hash-above>

# put all the changes in a stash
git stash save "glossary4"

# get latest commits from main
git rebase main

# get this PR changes back
git stash apply 0

# check the diffs to see if no extra change is there
# then make one final commit 
git add .
git commit -m "Glossary: argument to ascii"

# force push the changes to GitHub
git push --force

# on this PR page you'll be left with only one commit containing all the changes done so far
```

2023-08-29 16:48 UTC, estelle commented on files/en-us/glossary/arpa/index.md
> +**.arpa** (address and routing parameter area) is a {{glossary("TLD","top-level domain")}} in the Domain Name System (DNS) used for Internet infrastructure purposes, especially reverse DNS lookup (i.
```suggestion
**.arpa** (address and routing parameter area) is a {{glossary("TLD","top-level domain")}} in the Domain Name System (DNS) used for Internet infrastructure purposes, especially reverse DNS lookup (i.e., find the {{glossary('domain name')}} for a given {{glossary("IP address")}}).

The name comes from **ARPA**, currently known as [DARPA](https://en.wikipedia.org/wiki/DARPA), the Defense Advanced Research Projects Agency. DARPA's is credited with developing precursors to the Internet ({{glossary("ARPANET")}}), GPS, artificial intelligence, and virtual reality. 

{{glossary("TLD")}} was designed at DARPA during a time when it was called ARPA, hence the `.arpa` domain name.
```

2023-08-29 17:10 UTC, estelle commented
THanks Onkar for https://github.com/mdn/content/pull/28718#issuecomment-1697769916. My local git is working again, and after all the headache yesterday i am not brave enough to try fixing it, but I have bookmarked your comment for next time.

2023-08-29 19:26 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +- {{Glossary("parameter", "Difference between parameter and argument")}}
```suggestion
- [Difference between parameter and argument](/en-US/docs/Glossary/Parameter#parameters_versus_arguments)
```

2023-08-30 15:43 UTC, chrisdavidmills approved these changes
Nice work @estelle! I've found a couple more nits, but approving so as not to hold you up.

2023-08-30 15:43 UTC, chrisdavidmills commented on files/en-us/glossary/argument/index.md
> +const argument2 = "Development;
Missing a closing quote here.

2023-08-30 15:43 UTC, chrisdavidmills commented on files/en-us/glossary/argument/index.md
> +  console.log(parameter2); // Output = "Development
And here.

2023-08-30 15:43 UTC, chrisdavidmills commented on files/en-us/glossary/argument/index.md
> +// This function takes a single value, so second argument passed is ignored
```suggestion
// This function takes a single value, so the second argument passed is ignored
```

2023-08-30 15:43 UTC, chrisdavidmills commented on files/en-us/glossary/arpa/index.md
> +The name comes from **ARPA**, currently known as [DARPA](https://en.wikipedia.org/wiki/DARPA), the Defense Advanced Research Projects Agency. DARPA's is credited with developing precursors to the Int
```suggestion
The name comes from **ARPA**, currently known as [DARPA](https://en.wikipedia.org/wiki/DARPA), the Defense Advanced Research Projects Agency. DARPA is credited with developing precursors to the Internet ({{glossary("ARPANET")}}), GPS, artificial intelligence, and virtual reality.
```

2023-08-30 16:09 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +const argument2 = "Development;
```suggestion
const argument2 = "Development";
```

2023-08-30 16:09 UTC, estelle commented on files/en-us/glossary/argument/index.md
> +  console.log(parameter2); // Output = "Development
```suggestion
  console.log(parameter2); // Output = "Development"
```

2023-08-30 16:29 UTC, merged