Update index.md about flex items
mdn/content pull request #28772
Opened 2023-08-26 16:02 UTC by yihuaxiang

clarify flex items behavior

2023-08-29 08:12 UTC, chrisdavidmills requested changes
Thank you for your contribution @yihuaxiang! It makes sense to explain what these defaults actually mean. I think the wording could be improved — I've provided a suggestion for each one.

2023-08-29 08:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +- The items keep same behavior in stretch and shrink (the {{cssxref("flex-basis")}} property is set to `auto`).
This does not sound quite right. I'd change it to something similar to the `auto` definition on the `flex-basis` reference page. How about this:

"The {{cssxref("flex-basis")}} property is set to `auto`. This means that, in each case, it will be equal to the flex item {{cssxref("width")}} in horizontal writing mode, and the flex item {{cssxref("height")}} in vertical writing mode. If the corresponding `width`/`height` is also set to `auto`, the `flex-basis` `content` value is used instead."

2023-08-29 08:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +- The items will keep in the same row, even if there are too many items (the {{cssxref("flex-wrap")}} property is set to `nowrap`).
This sounds better, but I'd suggest something like the following to improve the grammar:

"The {{cssxref("flex-wrap")}} property is set to `nowrap`. This means that the flex items will always remain in a single row or column, overflowing their container if their combined `width`/`height` exceeds the containing element `width`/`height`."

2023-09-18 11:48 UTC, chrisdavidmills reviewed
@yihuaxiang So, did you not agree with my suggestions for updating the text? You have resolved the comments, but not made the changes.

2023-09-18 12:01 UTC, yihuaxiang reviewed
👍

2023-09-18 12:37 UTC, yihuaxiang commented
> @yihuaxiang So, did you not agree with my suggestions for updating the text? You have resolved the comments, but not made the changes.

Yours is right and nice!

2023-09-18 13:54 UTC, chrisdavidmills approved these changes
@yihuaxiang Great, thank you for making the changes. This is now ready to merge.

Thank you for your contribution to MDN, and for being a valuable part of the community. 🤩

2023-09-18 13:57 UTC, merged