Align see also item text with target title
mdn/content pull request #28799
Opened 2023-08-28 13:36 UTC by Josh-Cena

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-08-31 19:29 UTC, dipikabh requested changes
Thanks, @Josh-Cena! Just a few nits

2023-08-31 19:29 UTC, dipikabh commented on files/en-us/web/javascript/guide/regular_expressions/assertions/index.md
> +- [Regular expressions guide](/en-US/docs/Web/JavaScript/Guide/Regular_expressions)
We can keep the description part unlinked and so then the link text will exactly match the title of the target page

```suggestion
- [Regular expressions](/en-US/docs/Web/JavaScript/Guide/Regular_expressions) guide
```

2023-08-31 19:29 UTC, dipikabh commented on files/en-us/web/javascript/reference/classes/index.md
> +- [Functions reference](/en-US/docs/Web/JavaScript/Reference/Functions)
```suggestion
- [Functions](/en-US/docs/Web/JavaScript/Reference/Functions) reference
```
...and also in other occurrences in this PR

2023-08-31 19:29 UTC, dipikabh commented on files/en-us/web/javascript/reference/errors/missing_parenthesis_after_argument_list/index.md
> +- [Functions guide](/en-US/docs/Web/JavaScript/Guide/Functions)
```suggestion
- [Functions](/en-US/docs/Web/JavaScript/Guide/Functions) guide
```
 same comment for other occurrences in this PR

2023-09-01 17:44 UTC, Josh-Cena commented
@dipikabh FYI, for consistency, I've made all guide articles have the "guide" suffix, and those without are references by default.

2023-09-07 01:21 UTC, dipikabh approved these changes
Thank you!

2023-09-07 01:22 UTC, merged