fix(css): cover auto ratio combo in aspect-ratio
mdn/content pull request #28805
Opened 2023-08-28 15:54 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/28798

2023-08-28 20:57 UTC, wbamberg requested changes
Thanks @OnkarRuikar ! I saw your message in Slack about images not showing up in guess the live sample not working in preview. Do we have any reason to believe it will work in the live page?

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +- `auto && ratio`
AFAIK, "Values" lists individual components of the property syntax, not combinations. So I think it would be better to describe what happens when both values are given after the syntac example, but before ### Values, as we do for example in https://developer.mozilla.org/en-US/docs/Web/CSS/margin#syntax.

So we could say, for instance, "This property is specified as one or both of the keyword `auto` or a `<ratio>`. If both are given, then..."

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +  - : If the element is a replaced element, like [`<img>`](/en-US/docs/Web/HTML/Element/img), then the preferred `ratio` is used till the content is loaded. After the content is loaded, the `auto` va
```suggestion
  - : If the element is a [replaced element](/en-US/docs/Web/CSS/Replaced_element), such as [`<img>`](/en-US/docs/Web/HTML/Element/img), then the given `ratio` is used until the content is loaded. After the content is loaded, the `auto` value is applied, so the natural aspect ratio of the loaded content is used.
```

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +    If the element is a non-replaced element then the preferred `ratio` is used.
```suggestion
    If the element is not a replaced element, then the given `ratio` is used.
```

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +In this example we are using two images. The first image doesn't have source.
```suggestion
In this example we are using two`<img>` elements. The first element does not have its `src` attribute set to an image file.
```

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +```css hidden
I don't think it's a good practice to hide code unless there's a really good reason for it. Really the point of live samples is to show code and result together, so not showing code is just confusing.

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +Following code sets `3/2` as preferred aspect ratio and `auto` value as a fallback.
```suggestion
The following code sets `3/2` as the preferred aspect ratio and `auto` as a fallback.
```

2023-08-28 20:57 UTC, wbamberg commented on files/en-us/web/css/aspect-ratio/index.md
> +Note how the first image without replaced content keeps the `3/2` aspect ratio. And the second image after the content is loaded uses the images natural aspect ratio.
```suggestion
Note how the first image without replaced content keeps the `3/2` aspect ratio, while the second image after the content is loaded uses the image's natural aspect ratio.
```

2023-08-29 07:01 UTC, OnkarRuikar commented
> Do we have any reason to believe it will work in the live page?

@wbamberg same implementation works for [CSS_layout/Normal_Flow ](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Normal_Flow) page. So I think this should work in prod environment. 

Issue with the review companion is [the image](https://pr28805.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/aspect-ratio/plumeria.jpg) is not getting deployed to `https://live.mdnplay.dev/` which looks like a prod server.

2023-08-29 16:21 UTC, wbamberg reviewed
Thanks for the updates! But now the whole CSS is marked hidden :).

2023-08-29 16:26 UTC, OnkarRuikar commented on files/en-us/web/css/aspect-ratio/index.md
> +```css hidden
```suggestion
```css
```
Haha! I moved remaining content upwards but forgot to remove the `hidden` tag.

2023-08-29 16:44 UTC, wbamberg approved these changes
👍 thank you @OnkarRuikar !

2023-08-29 16:44 UTC, merged