Align see also item text with target title (2)
mdn/content pull request #28800
Opened 2023-08-28 13:36 UTC by Josh-Cena

### Description

#28799

### Motivation

### Additional details

### Related issues and pull requests

2023-08-31 20:35 UTC, dipikabh requested changes
Thanks, @Josh-Cena. I've left a few questions, also because I am slightly unaware of the conventions followed on the JavaScript side.

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/generatorfunction/generatorfunction/index.md
> +- [`Function()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function)
The page title is "Function() constructor"

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/generatorfunction/generatorfunction/index.md
>  - [`function*` expression](/en-US/docs/Web/JavaScript/Reference/Operators/function*)
It almost seems that it might be better to call out what they are, especially when listed next to each other, than expect readers to decipher how "`function*`" is different from "`function*` expression" (why use an adjective for one and not for the other). So, they could look like this:

> - [`function*` declaration](/en-US/docs/Web/JavaScript/Reference/Statements/function*)
> - [`function*` expression](/en-US/docs/Web/JavaScript/Reference/Operators/function*)

(or if one is a statement and the other is an operator). Although the above might mean fixing the page titles to bring out that distinction.
Or without fixing the page titles, they could be listed as:

> - [`function*`](/en-US/docs/Web/JavaScript/Reference/Statements/function*) declaration
> - [`function*` expression](/en-US/docs/Web/JavaScript/Reference/Operators/function*)

WDYT?

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/proxy/proxy/apply/index.md
> +- [`Proxy()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy)
The page title is "Proxy() constructor". Same comment for other occurrences of this link in the PR.

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/reflect/has/index.md
> +- [`in`](/en-US/docs/Web/JavaScript/Reference/Operators/in)
Page title is "in operator"
```suggestion
- [`in` operator](/en-US/docs/Web/JavaScript/Reference/Operators/in)
```

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/regexp/exec/index.md
> +- [Regular expressions guide](/en-US/docs/Web/JavaScript/Guide/Regular_expressions)
```suggestion
- [Regular expressions](/en-US/docs/Web/JavaScript/Guide/Regular_expressions) guide
```
..and in similar occurrences below

2023-08-31 20:35 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/symbol/index.md
> +- [JavaScript data types and data structures](/en-US/docs/Web/JavaScript/Data_structures)
This link itself is correct because it matches the page title.

I have separate comment – the sidebar and slug for the page mention only the data structure part.

2023-08-31 21:47 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/@@iterator/index.md
> +- [`String.prototype[@@iterator]()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator)
No, this is pretty much literal text (we stylize `@@Iterator` as code everywhere and it's basically an alias for `Symbol.iterator`)

2023-08-31 21:48 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/length/index.md
> +- [`TypedArray.prototype.length`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/length)
`TypedArray.prototype.length` as a whole is the name of the code entity.

2023-08-31 21:53 UTC, Josh-Cena commented
@dipikabh about "`Function()`" vs "`Function()` constructor" and similarly "`in`" vs "`in` operator". I made a conscious choice to drop these "ceremonial" suffixes because they help to disambiguate meaning in titles but are redundant in see also items. The main point, however, is that including these suffixes means the item has a mix of code and non-code and makes it impossible to switch to a pure macro like `{{jsxref("Operators/in", "in")}}` and I very much prefer the expressivity of xrefs in see also.

2023-09-01 14:34 UTC, dipikabh commented
> about "Function()" vs "Function() constructor" and similarly "in" vs "in operator". I made a conscious choice to drop these "ceremonial" suffixes because they help to disambiguate meaning in titles but are redundant in see also items.

We'd be deviating from the guideline that the link text should match the page title or section title (this guidelines applies as much anywhere in content as in "See also"). We actually don't even need to make a call about whether or not to keep the suffix in the "See also" list; the link text should match the page title. I don't think we should create exceptions to this rule otherwise it will leave room in future for more PRs changing the same thing back and forth. (It does mean that the list item cannot be replaced by an xref in such cases.)

2023-09-01 17:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/generatorfunction/generatorfunction/index.md
>  - [`function*` expression](/en-US/docs/Web/JavaScript/Reference/Operators/function*)
@dipikabh, I think it's better to treat declaration as "the default". The "expression" page is really just to be pedantic and all technical information is on the declaration page.

2023-09-01 17:50 UTC, Josh-Cena commented
Okay, FYI: I've added the "constructor" suffix but opted to remove the "operator" suffix from all pages, because most pages don't have the suffix anyway.

2023-09-01 18:04 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/symbol/index.md
> +- [JavaScript data types and data structures](/en-US/docs/Web/JavaScript/Data_structures)
Yes, I believe the page's title was updated afterwards, and we didn't change the slug. Let's not change that in this PR.

2023-09-07 01:45 UTC, dipikabh approved these changes
Thank you 👍

2023-09-07 01:45 UTC, merged