Trusted Types API Overview
mdn/content pull request #2883
Opened 2021-03-05 15:56 UTC by rachelandrew

Overview page for the API: https://w3c.github.io/webappsec-trusted-types/dist/spec/

Reviewer: @jpmedley 

I added a bit of explanation about injection sinks and policies in the description, as they will be referred to a lot in the individual interfaces, but perhaps these should be (or also be) a Glossary entry?

2021-03-05 18:05 UTC, jpmedley requested changes

2021-03-05 18:05 UTC, jpmedley commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>Represents a string to insert into an injection sink that will parse it as an URL of an external script resource.</dd>
```suggestion
  <dd>Represents a string to insert into an injection sink that will parse it as an URL of a external script resource.</dd>
```

2021-03-05 18:05 UTC, jpmedley commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>A dictionary that holds author-defined functions for converting string values into trusted values.</dd>
```suggestion
```

2021-03-05 18:05 UTC, jpmedley commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>A dictionary that holds author-defined functions for converting string values into trusted values.</dd>
Did someone already create a page for this dictionary?

2021-03-05 18:05 UTC, jpmedley commented on files/en-us/web/api/trusted_types_api/index.html
> +<p>Read more details about this example, and discover other ways to sanitize input in the article <a href="https://web.dev/trusted-types/">Prevent DOM-based cross-site scripting vulnerabilities with
```suggestion
<p>Read more about this example, and discover other ways to sanitize input in the article <a href="https://web.dev/trusted-types/">Prevent DOM-based cross-site scripting vulnerabilities with Trusted Types</a>.</p>
```

2021-03-06 08:02 UTC, rachelandrew commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>Represents a string to insert into an injection sink that will parse it as an URL of an external script resource.</dd>
that seems odd "a external" rather than "an external"

2021-03-06 08:03 UTC, rachelandrew commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>A dictionary that holds author-defined functions for converting string values into trusted values.</dd>
Not that I know of, I'll document it as part of this API.

2021-03-08 14:53 UTC, jpmedley commented on files/en-us/web/api/trusted_types_api/index.html
> +  <dd>Represents a string to insert into an injection sink that will parse it as an URL of an external script resource.</dd>
Brain hiccup.

2021-03-08 14:53 UTC, jpmedley approved these changes

2021-03-08 14:54 UTC, merged