Fix 28866: Clarify polygon() syntax
mdn/content pull request #28873
Opened 2023-08-31 19:54 UTC by wbamberg

Fixes https://github.com/mdn/content/issues/28866.

This makes a few changes to the page for [`polygon()`](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/polygon), including:

- more informative summary
- more syntax examples to show you can use more than just percentages
- rewritten "Values" section to add links
- added "Formal syntax"
- turned GH sample into a live sample, which is a lot more readable
- made some minor changes to the example to (I hope) make it more understandable

2023-09-01 06:06 UTC, OnkarRuikar commented on files/en-us/web/css/basic-shape/polygon/index.md
> +clip-path: polygon(0px 0px, 200px 100px, 0px 200px);
```suggestion
shape-outside: polygon(0px 0px, 200px 100px, 0px 200px);
```

2023-09-01 07:23 UTC, wbamberg commented on files/en-us/web/css/basic-shape/polygon/index.md
> +clip-path: polygon(0px 0px, 200px 100px, 0px 200px);
We are not consistent here and don't have good guidelines, but I think it would be better to omit the property and just show the function syntax, as we do for example in [`minmax()`](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax) and [`repeat()`](https://developer.mozilla.org/en-US/docs/Web/CSS/repeat).

The property isn't part of the function syntax, after all.

2023-09-01 07:27 UTC, chrisdavidmills approved these changes
This looks really good @wbamberg. Certainly a significant improvement. Just a couple of small comments, nothing taxing, so approving.

2023-09-01 07:27 UTC, chrisdavidmills commented on files/en-us/web/css/basic-shape/polygon/index.md
> +clip-path: polygon(0 0, 50% 1rem, 100% 2vw, calc(100% - 20px) 100%, 0 100%);
It might also be nice to show an example syntax line with the `<fill-rule>` value included. Currently, you read it and kinda go "oh, where is that used then?"

2023-09-01 07:27 UTC, chrisdavidmills commented on files/en-us/web/css/basic-shape/polygon/index.md
> +clip-path: polygon(0px 0px, 200px 100px, 0px 200px);
I'd suggest adding say three `shape-outside` examples. You definitely need some because it is a little strange that the syntax section doesn't show it, but the example below then uses it. And if you just had a single `shape-outside` syntax line, the section would look imbalanced.

2023-09-01 13:16 UTC, wbamberg commented on files/en-us/web/css/basic-shape/polygon/index.md
> +clip-path: polygon(0 0, 50% 1rem, 100% 2vw, calc(100% - 20px) 100%, 0 100%);
Oh yes, good point about `fill-rule`.

2023-09-22 22:58 UTC, wbamberg commented
@chrisdavidmills , I paused this to file https://github.com/mdn/content/pull/28953, so we could get answers to some questions. Now we have them I have tried to make this page match the new template.

I know you approved this one already, but thought it was worth asking again since there are not completely trivial changes.

2023-09-25 10:29 UTC, chrisdavidmills requested changes
@wbamberg your previous changes look fine to me. In terms of updating to match the new function ref page template. You've still got

```
Syntax
  Values
```

But according to the template this should be

```
Syntax
  Parameters
  Return value
```

??

2023-09-25 17:53 UTC, wbamberg commented
> @wbamberg your previous changes look fine to me. In terms of updating to match the new function ref page template. You've still got
> 
> ```
> Syntax
>   Values
> ```
> 
> But according to the template this should be
> 
> ```
> Syntax
>   Parameters
>   Return value
> ```
> 
> ??

O god. Should be fixed in https://github.com/mdn/content/pull/28873/commits/9d6c5733b3c19597ec5084513a07de09dfcf0de4.

2023-09-26 15:38 UTC, chrisdavidmills approved these changes
LGTM; let's get this one in. Nice work @wbamberg!

2023-09-26 15:38 UTC, merged