Add glossary for camel/kebab/snake casing
mdn/content pull request #28906
Opened 2023-09-02 23:31 UTC by Josh-Cena

### Description

Fix https://github.com/mdn/content/issues/28882

### Motivation

### Additional details

### Related issues and pull requests

2023-09-03 16:57 UTC, wbamberg requested changes
Looks great. I had a few comments, but I'm open to discussions :).

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/glossary/camel_case/index.md
> +**Camel case** is a way of writing phrases without spaces, where the first letter of each word is capitalized, while the first letter of the entire compound word is either upper or lower case. The na
```suggestion
**Camel case** is a way of writing phrases without spaces, where the first letter of each word is capitalized, while the first letter of the entire compound word is either upper or lower case. The name comes from the similarity of the capital letters to the humps of a camel's back. It's often stylized as "camelCase" to remind the reader of its appearance.
```

? (I don't really understand English and am English, so quite often get these things wrong)

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/glossary/camel_case/index.md
> +Camel casing is often used as a variable naming convention. The following variables are in camel case: {{domxref("console")}}, {{domxref("crossOriginIsolated")}}, {{jsxref("encodeURIComponent")}}, {{
It seems a little perverse to call "console" camel case, but OK.

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/glossary/kebab_case/index.md
> +**Kebab case** is a way of writing phrases without spaces, where spaces are replaced with hyphens `-`, and the words are typically all lower case. The name comes from similarity of the words with mea
```suggestion
**Kebab case** is a way of writing phrases without spaces, where spaces are replaced with hyphens `-`, and the words are typically all lower case. The name comes from the similarity of the words to meat on a kebab skewer. It's often stylized as "kebab-case" to remind the reader of its appearance.
```

?

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/learn/html/howto/use_data_attributes/index.md
> +To get a `data` attribute through the `dataset` object, get the property by the part of the attribute name after `data-` (note that dashes are converted to {{Glossary("camel_case", "camelCase")}}).
As a general comment on these references, I would prefer we refer to these conventions consistently as "camel case", "kebab case" etc. Point being that:

- if a reader doesn't know what these mean, it is confusing to use "camelCase" and "kebab-case"
- if a reader does know what they mean, it doesn't really help

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +After the imports, we have a function named `App`. Whereas most of the JavaScript community prefers {{Glossary("camel_case", "lower camel case")}} names like `helloWorld`, React components use pascal
```suggestion
After the imports, we have a function named `App`. Whereas most of the JavaScript community prefers {{Glossary("camel_case", "lower camel case")}} names like `helloWorld`, React components use Pascal case (or upper camel case) variable names, like `HelloWorld`, to make it clear that a given JSX element is a React component, and not a regular HTML tag. If you were to rename the `App` function to `app`, your browser would show you an error.
```

Also maybe just linking "camel case" instead of "lower camel case", the first time, to give a hint that the second "camel case" is also explained at the link?

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +The event model is similar to the web events model, but a bit different — event listeners' properties are {{Glossary("camel_case", "camel-cased")}} (such as `onMessage` rather than `onmessage`), and
Perhaps here there is a case for the hyphen, so "camel-cased" is short for "put into camel case", i.e. it describes the action not the state.

But also note that this form was one of the original motivations for https://github.com/mdn/content/pull/28879.

2023-09-03 16:57 UTC, wbamberg commented on files/en-us/glossary/camel_case/index.md
> +When the first letter of the entire phrase is upper case, it is called _upper camel case_ or _Pascal case_. Otherwise, it is called _lower camel case_.
Since we link using "lower camel case", I wonder if it is worth a heading like "Lower and upper (or Pascal) camel case"? A bit of a clumsy name though.

2023-09-03 17:01 UTC, Josh-Cena commented on files/en-us/glossary/camel_case/index.md
> +**Camel case** is a way of writing phrases without spaces, where the first letter of each word is capitalized, while the first letter of the entire compound word is either upper or lower case. The na
Both are okay in both English styles, although "to" seems slightly more popular.

2023-09-03 17:02 UTC, Josh-Cena commented on files/en-us/glossary/camel_case/index.md
> +Camel casing is often used as a variable naming convention. The following variables are in camel case: {{domxref("console")}}, {{domxref("crossOriginIsolated")}}, {{jsxref("encodeURIComponent")}}, {{
Yeah, just showcasing the trivial case.

2023-09-03 17:02 UTC, Josh-Cena commented on files/en-us/glossary/camel_case/index.md
> +When the first letter of the entire phrase is upper case, it is called _upper camel case_ or _Pascal case_. Otherwise, it is called _lower camel case_.
I think linking to the glossary as a whole is okay. It's only 5 paragraphs long anyway.

2023-09-03 17:02 UTC, Josh-Cena commented on files/en-us/learn/html/howto/use_data_attributes/index.md
> +To get a `data` attribute through the `dataset` object, get the property by the part of the attribute name after `data-` (note that dashes are converted to {{Glossary("camel_case", "camelCase")}}).
```suggestion
To get a `data` attribute through the `dataset` object, get the property by the part of the attribute name after `data-` (note that dashes are converted to {{Glossary("camel_case", "camel case")}}).
```

2023-09-03 17:03 UTC, Josh-Cena commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +The event model is similar to the web events model, but a bit different — event listeners' properties are {{Glossary("camel_case", "camel-cased")}} (such as `onMessage` rather than `onmessage`), and
I think this is grammatically correct, although I'm not totally sure.

2023-09-03 17:04 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +After the imports, we have a function named `App`. Whereas most of the JavaScript community prefers {{Glossary("camel_case", "lower camel case")}} names like `helloWorld`, React components use pascal
I would prefer "lower camel case" as "Pascal case" is really a kind of camel case, making the sentence semantically off.

2023-09-03 17:05 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/html/index.md
> +Use semantic class/ID names, and separate multiple words with hyphens ({{Glossary("kebab_case", "kebab case")}}). Don't use {{Glossary("camel_case", "camelCase")}}. For example:
```suggestion
Use semantic class/ID names, and separate multiple words with hyphens ({{Glossary("kebab_case", "kebab case")}}). Don't use {{Glossary("camel_case", "camel case")}}. For example:
```

2023-09-03 17:05 UTC, Josh-Cena commented on files/en-us/mdn/writing_guidelines/writing_style_guide/code_style_guide/javascript/index.md
> +For function names, use {{Glossary("camel_case", "camelCase")}}, starting with a lowercase character. Use concise, human-readable, and semantic names where appropriate.
```suggestion
For function names, use {{Glossary("camel_case", "camel case")}}, starting with a lowercase character. Use concise, human-readable, and semantic names where appropriate.
```

2023-09-03 17:05 UTC, Josh-Cena commented on files/en-us/mozilla/add-ons/webextensions/api/contentscripts/register/index.md
> +    - property names use {{Glossary("camel_case", "camelCase")}}, rather than underscores ({{Glossary("snake_case", "snake case")}}) — for example, `excludeMatches`, not `exclude_matches`.
```suggestion
    - property names use {{Glossary("camel_case", "camel case")}}, rather than underscores ({{Glossary("snake_case", "snake case")}}) — for example, `excludeMatches`, not `exclude_matches`.
```

2023-09-03 17:05 UTC, Josh-Cena commented on files/en-us/related/imsc/index.md
> +- Whereas CSS properties use hyphens, like `font-size`, IMSC uses {{Glossary("camel_case", "camelCase")}}, like `tts:fontSize`.
```suggestion
- Whereas CSS properties use hyphens, like `font-size`, IMSC uses {{Glossary("camel_case", "camel case")}}, like `tts:fontSize`.
```

2023-09-03 17:05 UTC, Josh-Cena commented on files/en-us/web/api/document/getelementsbytagname/index.md
> +argument before proceeding. This is undesirable when trying to match {{Glossary("camel_case", "camelCase")}} SVG
```suggestion
argument before proceeding. This is undesirable when trying to match {{Glossary("camel_case", "camel case")}} SVG
```

2023-09-03 17:06 UTC, Josh-Cena commented on files/en-us/web/api/htmlelement/dataset/index.md
> +    when to capitalize the property's "{{Glossary("camel_case", "camelCased")}}" name.
```suggestion
    when to capitalize the property's "{{Glossary("camel_case", "camel-cased")}}" name.
```

2023-09-03 17:06 UTC, Josh-Cena commented on files/en-us/web/api/htmlelement/style/index.md
> +> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to _{{Glossary("camel_case", "camelCase")}}_: `background-attachment` becomes `background
```suggestion
> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to {{Glossary("camel_case", "camel case")}}: `background-attachment` becomes `backgroundAttachment`.
```

2023-09-03 17:06 UTC, Josh-Cena commented on files/en-us/web/api/mathmlelement/style/index.md
> +> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to _{{Glossary("camel_case", "camelCase")}}_: `background-attachment` becomes `background
```suggestion
> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to {{Glossary("camel_case", "camel case")}}: `background-attachment` becomes `backgroundAttachment`.
```

2023-09-03 17:06 UTC, Josh-Cena commented on files/en-us/web/api/svgelement/style/index.md
> +> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to _{{Glossary("camel_case", "camelCase")}}_: `background-attachment` becomes `background
```suggestion
> - If the property is made of several words, separated by dashes, the dashes are removed and it is converted to {{Glossary("camel_case", "camel case")}}: `background-attachment` becomes `backgroundAttachment`.
```

2023-09-03 17:07 UTC, Josh-Cena commented on files/en-us/web/svg/attribute/data-_star_/index.md
> +> **Note:** The {{domxref("HTMLElement.dataset")}} property is a {{domxref("DOMStringMap")}} that provides the attribute `data-test-value` via `SVGElement.dataset.testValue`. Hyphen characters (`-`,
```suggestion
> **Note:** The {{domxref("HTMLElement.dataset")}} property is a {{domxref("DOMStringMap")}} that provides the attribute `data-test-value` via `SVGElement.dataset.testValue`. Hyphen characters (`-`, `U+002D`) are removed and the next letter is capitalized, resulting in the {{Glossary("camel_case", "camel case")}} format.
```

2023-09-03 17:08 UTC, rebloor commented
@Josh-Cena Please make your suggestion in a review, not one at a time - the email pings are getting annoying

2023-09-03 17:10 UTC, Josh-Cena commented
Sorry about that! I thought the changes are sparse but ended up finding a lot of them. You may want to unsubscribe yourself since there's no substantial content changes. Unfortunately there isn't a way to unassign reviewers prior to submitting the PR, or else I won't have you subscribed in the first place :(

2023-09-03 21:37 UTC, wbamberg commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +After the imports, we have a function named `App`. Whereas most of the JavaScript community prefers {{Glossary("camel_case", "lower camel case")}} names like `helloWorld`, React components use pascal
OK, but still capitalize "Pascal" as it is a proper name? We capitalize it in the glossary page.

2023-09-03 21:39 UTC, wbamberg commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +The event model is similar to the web events model, but a bit different — event listeners' properties are {{Glossary("camel_case", "camel-cased")}} (such as `onMessage` rather than `onmessage`), and
I think it is OK, but given that this form made someone file a PR to change it, I would be tempted to reword like "written in {{camel case}}" so as to avoid the potential misunderstanding.

2023-09-03 22:05 UTC, hamishwillee commented on files/en-us/glossary/camel_case/index.md
> +**Camel case** is a way of writing phrases without spaces, where the first letter of each word is capitalized, while the first letter of the entire compound word is either upper or lower case. The na
```suggestion
**Camel case** is a way of writing phrases without spaces, where the first letter of each word is capitalized, except for the first letter of the entire compound word, which may be either upper or lower case. The name comes from the similarity of the capital letters to the humps of a camel's back. It's often stylized as "camelCase" to remind the reader of its appearance.
```

2023-09-03 22:08 UTC, hamishwillee commented on files/en-us/glossary/camel_case/index.md
> +Camel casing is often used as a variable naming convention. The following variables are in camel case: {{domxref("console")}}, {{domxref("crossOriginIsolated")}}, {{jsxref("encodeURIComponent")}}, {{
You could use "car" and "Car" since according to our rule either would be allowed.
```

2023-09-04 02:47 UTC, rebloor commented
Thanks @Josh-Cena

2023-09-08 00:35 UTC, hamishwillee commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +After the imports, we have a function named `App`. Whereas most of the JavaScript community prefers {{Glossary("camel_case", "lower camel case")}} names like `helloWorld`, React components use pascal
FWIW I would capitalize Pascal.

2023-09-08 00:36 UTC, hamishwillee commented on files/en-us/learn/javascript/building_blocks/events/index.md
> +The event model is similar to the web events model, but a bit different — event listeners' properties are {{Glossary("camel_case", "camel-cased")}} (such as `onMessage` rather than `onmessage`), and
I am making this change. There is nothing wrong with "camel case" or "camel-cased" too, but I don't want to go down this road again.

```suggestion
The event model is similar to the web events model, but a bit different — event listeners' properties are written in {{Glossary("camel_case", "camel case")}} (such as `onMessage` rather than `onmessage`), and need to be combined with the `addListener` function.
```

2023-09-08 00:38 UTC, hamishwillee commented
@wbamberg I'm OK with this "as is" now. Anything else you are waiting on?

2023-09-08 01:05 UTC, wbamberg approved these changes
> @wbamberg I'm OK with this "as is" now. Anything else you are waiting on?

No, totally happy with this now. Thanks @Josh-Cena (and @hamishwillee for getting it over the line).

2023-09-08 01:05 UTC, merged