fix(css): update 'drop-shadow()' page
mdn/content pull request #29013
Opened 2023-09-09 06:01 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/29005

It is helpful to document the required parameters first then the optional parameters. For usage in code no guideline exist about the order. Also Prettier has no opinion about this. We can show all allowed combinations of values in the "Syntax" section.

The PR does following changes:
- updates the syntax section to cover various scenarios
- uses ` {{optional_inline}}` badge. All non optional params are mandatory.
- adds playable example
- use standard-deviation instead of blur-radius. The drop-shadow and box-shadow implementations use different algorithms.

2023-09-12 18:15 UTC, dipikabh requested changes
Thanks @OnkarRuikar for adding these improvements to the page!

2023-09-12 18:15 UTC, dipikabh commented on files/en-us/web/css/box-shadow/index.md
> +    The presence of the `inset` keyword changes the shadow to one inside the frame (as if the content was debossed inside the box). Inset shadows are drawn inside the border (even transparent ones),
Starting the description to explain what it does or is used for

```suggestion
  - : Changes the shadow from an outer box-shadow to an inner box-shadow (as if the content is pressed into the box). Inset shadows are drawn inside the box's border (even if the border is transparent), and they appear above the background but below the content. By default, the shadow behaves like a drop shadow, giving the appearance that the box is elevated above its content. This is the default behavior when `inset` is not specified.
```

2023-09-13 01:11 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +drop-shadow(#e23 0.5rem 0.5rem 1rem)
- This was done according to the new proposed structure for the CSS function pages  https://github.com/mdn/content/pull/28953
Could you raise the concern there?

2023-09-13 01:21 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +- `offset-x`
> 2. Also, from what I understand from the spec, omission of a <length> value applies 0 to the offset-x, offset-y, not to the third value of <standard-deviation> because that is optional?

If not provided the there is no blur(sharp edged shadow) so the used value is `0`.

> 3. Perhaps order them as <color> first and then <length> to match the order in the syntax.

But optional params are not that important. Could you raise a concern of following syntax order in "Parameters" section [in the guide update PR](https://github.com/mdn/content/pull/28953)?

> 1. .. This will help to keep the parameter list more similar to the "Formal syntax".

Could you raise this concern too?

2023-09-13 01:42 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +div:nth-child(3) {
done

2023-09-13 17:36 UTC, wbamberg commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +- `offset-x`
> 1. Instead of the three entries for `offset-x`, `offset-y`, and `standard-deviation`, I propose we have a single entry as `<length>`. And its description can explain the meaning of 2 or 3 values for the parameter. This will help to keep the parameter list more similar to the "Formal syntax".
> 

I agree that if it's practical it's good to have synchronization between:
- the values used in the formal syntax
- the values used in the "Values" list
- the comment in the "Syntax" code block

Then someone can cross-reference from one to the other.

Especially, in this PR as it stands, things like:

    /* drop-shadow( <offset-x> <offset-y> <standard-deviation> ) */

...strongly imply that there is a `<offset-x>` data type, which there isn't.

If we want that synchronization, then the comments would need to say e.g.:

    /* drop-shadow( <length> <length> <length> ) */

...and the "Values" section could say, as Dipika says, something like:

```
- `<length>`
  - : Two `<length>` values must be given: the first is interpreted as ... and the second is interpreted as .... A third optional length value is interpreted as ...
```

2023-09-14 02:26 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +- `offset-x`
@wbamberg but this is less reader friendly:
```
/* drop-shadow( <length> <length> <length> ) */
drop-shadow(5px 5px 15px)
```

Can we use a comment as well something like following?
```
/* using three values x-offset, y-offset, and standard deviation */
/* drop-shadow( <length> <length> <length> ) */
drop-shadow(5px 5px 15px)
```

We'll have to update the guidelines for CSS function pages to say use terms used in "Formal Syntax" sections for "Parameters" and "Syntax" blocks.

2023-09-14 03:21 UTC, wbamberg commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +- `offset-x`
Sure, why not!

2023-09-14 15:43 UTC, dipikabh commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +div:nth-child(3) {
Thanks

2023-09-19 02:50 UTC, dipikabh commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +drop-shadow(#e23 0.5rem 0.5rem 1rem)
Following on from the PR for template for CSS functions, there can be two comments, one descriptive and the other showing a specific syntax use case.
1) So we can add the descriptive comments as suggested.
2) For the comment showing syntax use case, can we use terms as referred in the "Values" section? For example, use:
`/* drop-shadow( <length> <length> <length> ) */`.
Ideally, refrain from using `<standard-deviation>` in both "Syntax" and "Values" because it does not come up in "Formal syntax" and is a term/value that we have coined.

2023-09-19 04:08 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +- `offset-x`
done

2023-09-19 04:08 UTC, OnkarRuikar commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +drop-shadow(#e23 0.5rem 0.5rem 1rem)
done

2023-09-19 04:08 UTC, OnkarRuikar commented on files/en-us/web/css/box-shadow/index.md
done

2023-09-22 17:43 UTC, dipikabh commented on files/en-us/web/css/filter-function/drop-shadow/index.md
> +drop-shadow(#e23 0.5rem 0.5rem 1rem)
Thank you!

2023-09-22 18:26 UTC, dipikabh requested changes
Thanks, @OnkarRuikar. It is getting pretty close. Just a few more adjustments needed for the `box-shadow` page.

2023-09-22 18:26 UTC, dipikabh commented on files/en-us/web/css/box-shadow/index.md
> +    - The third optional {{cssxref("&lt;length&gt;")}} values is interpreted as `<blur-radius>`. The larger this value, the bigger the blur, so the shadow becomes bigger and lighter. Negative values
Suggesting the same style as on the `drop-shadow()` page

```suggestion
    - If two values are specified, they are interpreted as `<offset-x>` (horizontal offset) and `<offset-y>` (vertical offset) values. Negative `<offset-x>` value places the shadow to the left of the element. Negative `<offset-y>` value places the shadow above the element.\
      If not specified, the value of `0` is used for the missing length. If both `<offset-x>` and `<offset-y>` are set to `0`, the shadow is placed behind the element (and may generate a blur effect if `<blur-radius>` and/or `<spread-radius>` is set).
    - If three values are specified, the third value is interpreted as `<blur-radius>`. The larger this value, the bigger the blur, so the shadow becomes bigger and lighter. Negative values are not allowed. If not specified, it will be set to`0` (meaning that the shadow's edge will be sharp). The specification does not include an exact algorithm for how the blur radius should be calculated; however, it does elaborate as follows:
```

2023-09-22 18:26 UTC, dipikabh commented on files/en-us/web/css/box-shadow/index.md
> +    - The fourth optional {{cssxref("&lt;length&gt;")}} value is interpreted as `<spread-radius>`. Positive values will cause the shadow to expand and grow bigger, negative values will cause the shad
```suggestion
    - If four values are specified, the fourth value is interpreted as `<spread-radius>`. Positive values will cause the shadow to expand and grow bigger, negative values will cause the shadow to shrink. If not specified, it will be set to `0` (that is, the shadow will be the same size as the element).
```

2023-09-22 18:26 UTC, dipikabh commented on files/en-us/web/css/box-shadow/index.md
> +    0.3em 0.3em 1em rgba(200, 0, 0, 0.6);
This is looking great. Thanks!

2023-09-22 18:26 UTC, dipikabh commented on files/en-us/web/css/box-shadow/index.md
> +    - The fourth optional {{cssxref("&lt;length&gt;")}} value is interpreted as `<spread-radius>`. Positive values will cause the shadow to expand and grow bigger, negative values will cause the shad
While we're updating the value descriptions, can we also update this part just before "Values" to remove duplicate info:

> Specify a single box-shadow using:
>  - Two, three, or four `<length>` values.
>     - If only two values are given, they are interpreted as `<offset-x>` and `<offset-y>` values.
>     -  If a third value is given, it is interpreted as a `<blur-radius>`.
>     - If a fourth value is given, it is interpreted as a `<spread-radius>`.
>  - Optionally, the `inset` keyword.
>   - Optionally, a `<color>` value.
> 
> To specify multiple shadows, provide a comma-separated list of shadows.

- We should probably move the above text to the "Values" section.
- And update it to:
> You can create a single box-shadow by specifying two, three, or four `<length>` values, an optional `inset`, and an optional `<color>` value. To create multiple box-shadows, specify a comma-separated list of shadows for the `box-shadow` property.

2023-09-25 19:38 UTC, dipikabh approved these changes
Thanks for your work on these update, @OnkarRuikar 🙌

2023-09-25 19:38 UTC, merged