chore(learn): add details about grading tasks
mdn/content pull request #29139
Opened 2023-09-15 16:50 UTC by bsmth

__Changes:__
* main change in this PR: removed sections asking readers to open new topics with `Assessment {task_title}` in Learn area forum
* Added hints for grading tasks to Learn area index
* Tidy up of communication / community pages

2023-09-25 01:29 UTC, hamishwillee commented on files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md
>  {{PreviousMenu("Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper", "Learn/CSS/Building_blocks")}}
Deleted in another case. SHould assessments have a previous/next or not?

2023-09-25 01:32 UTC, hamishwillee commented on files/en-us/mdn/community/communication_channels/index.md
> +Chat rooms are for meeting other folks, asking questions and sharing information.
I see folk as a rare-ish word.
```suggestion
Chat rooms are for meeting other people, asking questions and sharing information.
```

2023-09-25 01:36 UTC, hamishwillee commented on files/en-us/mdn/community/index.md
> +    This section covers [Getting started](/en-US/docs/MDN/Community/Contributing/Getting_started), [Our repositories](/en-US/docs/MDN/Community/Contributing/Our_repositories), [Translated content](/e
```suggestion
    It covers [Getting started](/en-US/docs/MDN/Community/Contributing/Getting_started), [Our repositories](/en-US/docs/MDN/Community/Contributing/Our_repositories), [Translated content](/en-US/docs/MDN/Community/Contributing/Translated_content), and [Security vulnerability response steps](/en-US/docs/MDN/Community/Contributing/Security_vulnerability_response).
```

2023-09-25 01:41 UTC, hamishwillee commented on files/en-us/learn/accessibility/accessibility_troubleshooting/index.md
> -## Assessment or further help
>main change in this PR: removed sections asking readers to open new topics with Assessment {task_title} in Learn area forum

Just FMI, why? Is it because we don't plan to offer assessments?

2023-09-25 01:41 UTC, hamishwillee approved these changes
Looks good to me. Approving with a nit and question. Not merging as I expect others might have a comment too.

2023-10-18 09:47 UTC, bsmth commented on files/en-us/learn/css/building_blocks/a_cool_looking_box/index.md
>  {{PreviousMenu("Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper", "Learn/CSS/Building_blocks")}}
Well spotted, I removed this by accident. Replaced in e0f559b99bd5ea5ded108f4240e80d2087dad0f0

2023-10-18 11:43 UTC, bsmth commented on files/en-us/learn/accessibility/accessibility_troubleshooting/index.md
> -## Assessment or further help
There are a lot of requests for assessments in Discourse with no replies recently given the limited number of people helping out there, so for now we're guiding readers to the marking documents instead.

2023-10-18 18:07 UTC, estelle requested changes, later dismissed
This PR feels like an advertisement for Play. It adds the link to https://developer.mozilla.org/en-US/play 56 times. We would consider this spam if it was a link to any other resource. I feel uncomfortable merging this, especially without an indication of how a11y can't be tested in the tool and that forms cannot be submitted.

People need to be able to save their work. I am not sure if play can be saved. If not, please remove all 56 links that were just added to play. If yes, please just add a note on the forms and a11y ones to explain that none of these 1) open the dev tools to see a11y features, and 2) none of these (i don't think) all form submission, but....

2023-10-19 08:43 UTC, bsmth commented
> please remove all 56 links to https://developer.mozilla.org/en-US/play included in the PR

This is an incidental addition seeing as there is already an online code editor on MDN. I've removed in https://github.com/mdn/content/pull/29139/commits/43b59ccf0938e7762e418db49670a92b49c8a94f anyway 👍🏻

2023-10-19 14:55 UTC, dipikabh approved these changes
These updates look good to me. Thank you for tackling all the sections, @bsmth! 👍 

Just a very tiny nit: in "ask for help in one of our [Communication channels](/en-US/docs/MDN/Community/Communication_channels)", we can change the link text to sentence case. So "ask for help in one of our [communication channels](/en-US/docs/MDN/Community/Communication_channels)".

Leaving my +1 so you can merge it later.

2023-10-19 16:38 UTC, estelle approved these changes
Thank you!

2023-10-23 08:28 UTC, bsmth commented
Thanks all, merging shortly 👍🏻

2023-10-23 08:57 UTC, merged