Perceived performance update
mdn/content pull request #2918
Opened 2021-03-08 05:02 UTC by hamishwillee

Fixes #2812

This was repetitive and fairly hard to read (though makes some good points). I have somewhat restructured to improve. Could probably do with even more work, but I think this about right for the effort required.

2021-03-08 09:47 UTC, chrisdavidmills requested changes
Not bad for a cleanup, nice work @hamishwillee . I've got a few comments for you.

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +<p><span class="seoSummary"><strong><a href="/en-US/docs/Glossary/Perceived_performance">Perceived performance</a></strong> is a subjective measure of website performance, responsiveness and reliabil
"responsiveness and reliability" is missing an oxford comma.

Also, you've made this paragraph easier to read, but I feel like you've kind of removed the simple human explanation, which helped quite a lot in the original — "how fast a website seems to the user". It would be nice to add something back in, such as "In other words, how fast a website seems to the user."

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +  <p>Subjective time passes more quickly for users who are actively engaged, distracted, or entertained, than those who are waiting passively for something to happen. Where possible, actively engage
"Subjective time" sounds a bit strange. Maybe start this sentence "Time appears to pass more quickly for..."

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +<p>Similarly, it is better to display a "loading animation" as soon as a user clicks a link to perform a long running animation. This makes the site feel more responsive, and the user is informed tha
"long running animation"? Do you mean "operation" or somesuch?

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> -<p>These metrics have to do with initial load and render. It is also important to ensure the site feels fast once the user begins interacting with it. For this, <strong><a href="/en-US/docs/Glossary/
Couple of bits here:

1. remove comma after "time to interactive" link.
2. spacing needs sorting out in `<a href="/en-US/docs/Glossary/Long_task">long task </a>of`
3. "available for user interaction with delay" sounds confusing. What does that mean?

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +<h2 id="Perceived_performance">Performance metrics</h2>
ID needs to match the heading text, and be all lower-case

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +<p>There is no single metric or test that can be run on site to evaluate how a user "feels". However there are a number of metrics that can be "useful indicators":</p>
"on site" -> "on a site"

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +  <dd>The time until first significant rendering (e.g. of text, foreground or background image, canvas or SVG, etc.).Note that just because there's content, doesn't mean it's useful content or that t
sort out spacing — `etc.).Note`

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +  <dd>Measures the average time for pixels on the visible screen to be painted. It doesn't account for jitter, nor does it weight which content important to a user more highly.</dd>
"weight which content important to a user more highly" needs sorting out ;-)

2021-03-08 09:47 UTC, chrisdavidmills commented on files/en-us/learn/performance/perceived_performance/index.html
> +<h2 id="Improving_performance">Improving performance</h2>
lower case "i" in the ID value

2021-03-08 23:10 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> +<p>Similarly, it is better to display a "loading animation" as soon as a user clicks a link to perform a long running animation. This makes the site feel more responsive, and the user is informed tha
Yes - "operation". Fixed thanks.

2021-03-08 23:18 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> +<h2 id="Improving_performance">Improving performance</h2>
FYI lower casing the "i" is optional. It does not get reported as a flaw because the generated content automatically gets pushed lower case. It is a flaw if you LINK to the upper case version. 

That said, while I'm here I'll make them all lower case.

2021-03-08 23:18 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> +<h2 id="Perceived_performance">Performance metrics</h2>
See https://github.com/mdn/content/pull/2918/files#r589821012

2021-03-08 23:19 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> +  <dd>Measures the average time for pixels on the visible screen to be painted. It doesn't account for jitter, nor does it weight which content important to a user more highly.</dd>
Yuk. Removed that altogether.

2021-03-08 23:23 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> -<p>These metrics have to do with initial load and render. It is also important to ensure the site feels fast once the user begins interacting with it. For this, <strong><a href="/en-US/docs/Glossary/
I deleted all this crap yesterday, so no fix to do :-)

2021-03-08 23:24 UTC, hamishwillee commented on files/en-us/learn/performance/perceived_performance/index.html
> +<h2 id="Overview">Overview</h2>
@chrisdavidmills FYI, I did try to change this id to lower case "o" but that made the rendered heading disappear. I very much want the heading, so changed it back.

2021-03-09 00:25 UTC, hamishwillee commented
Thanks @chrisdavidmills - appreciate the tidy (got a bit sloppy on the detail while looking at the big picture).

Feedback integrated. I did a bit more tidy at the end of it too, and deleted most of the related glossary entry as further unnecessary duplication (IMO a glossary entry should be short and sweet unless it is the "main doc" on a topic).

2021-03-09 08:52 UTC, chrisdavidmills approved these changes
All looks great; let's get it merged! Nice work @hamishwillee

2021-03-09 08:52 UTC, merged