Update index.md
mdn/content pull request #29204
Opened 2023-09-19 10:06 UTC by PositiveUser

Added some inline deprecated and non-standard annotations.

After opening some pages, I noticed that some elements were deprecated and/or non-standard, but it wasn't always mentioned in [this article](https://developer.mozilla.org/en-US/docs/Web/MathML/Element)

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-09-19 16:12 UTC, Josh-Cena reviewed
Could you also update the MathML elements by category list below?

2023-09-19 16:12 UTC, Josh-Cena commented on files/en-us/web/mathml/element/index.md
> +- {{MathMLElement("mfenced")}} (Parentheses) {{non-standard_inline}}{{deprecated_inline}}
```suggestion
- {{MathMLElement("mfenced")}} (Parentheses) {{non-standard_inline}} {{deprecated_inline}}
```

2023-09-20 14:22 UTC, Josh-Cena commented
@PositiveUser Once you update the list below we can merge

2023-09-21 05:03 UTC, PositiveUser commented
It shows that one reviewer @fred-wang is pending

2023-09-21 05:23 UTC, fred-wang approved these changes
sorry for the delay. lgtm

2023-09-21 05:35 UTC, Josh-Cena requested changes
@PositiveUser You don't necessarily have to wait for Frédéric's review; I can merge yours as well. However, we do need the two lists to be consistent.

2023-09-21 17:26 UTC, PositiveUser reviewed
...

2023-09-21 17:35 UTC, PositiveUser commented
Would it have been better if I opened a new, proper pull request?

2023-09-21 18:22 UTC, Josh-Cena commented
On the page you edited, there are two lists: one called "[MathML elements A to Z](https://pr29204.content.dev.mdn.mozit.cloud/en-US/docs/Web/MathML/Element#mathml_elements_a_to_z)", one called "[MathML elements by category](https://pr29204.content.dev.mdn.mozit.cloud/en-US/docs/Web/MathML/Element#mathml_elements_by_category)". They contain exactly the same information, in different order. We need to keep the badges the same between them. It's okay if you want to open a new one, but you can also edit the existing one, by going to https://github.com/mdn/content/pull/29204/files and editing the file there.

2023-09-22 09:16 UTC, PositiveUser commented
I opened a new pull request for this. Closing this.

2023-09-22 09:16 UTC, closed without merging