Fix issue 22887: Rewrite web components guide
mdn/content pull request #29252
Opened 2023-09-22 22:00 UTC by wbamberg

.

2023-09-25 10:16 UTC, chrisdavidmills requested changes
Nice work @wbamberg; this is looking much improved, and it largely makes sense. I just had a few comments for you to respond to.

2023-09-25 10:16 UTC, chrisdavidmills commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +Note that to get the `attributeChangedCallback()` callback to fire when an attribute changes, you have to observe the attributes. This is done by specifying a `static get observedAttributes()` method
```suggestion
Note that to get the `attributeChangedCallback()` callback to fire when an attribute changes, you have to observe the attributes. This is done by specifying a `static get observedAttributes()` method inside the custom element class - this should return an array containing the names of the attributes you want to observe:
```

2023-09-25 21:42 UTC, wbamberg commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +A custom element could be implemented as a tree of standard HTML elements (or other custom elements), and the custom element then serves to encapsulate this implementation.
yeah, I didn't like that line much either but wasn't sure.

2023-09-25 22:39 UTC, wbamberg commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +- `connectedCallback()`: called each time the element is added to the document. The specification recommends delaying work until this callback.
I reworded the description of `connectedCallback` to clarify that this is talking about deferring work from the ctor. Hopefully it is better now.

Good point about the example: I thought that for consistency and flow it would be better to include a minimal example, so that's what I did.

2023-09-25 22:40 UTC, wbamberg commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +To make a custom element available in a page, call the {{domxref("CustomElementRegistry.define()", "define()")}} method of the {{domxref("CustomElementRegistry")}} interface, which is available as {{
Done, a bit differently (`{{domxref("window.customElements.define()", "define()")}}` doesn't like to a page).

2023-09-25 22:41 UTC, wbamberg commented
Thank for for the review Chris! Updates are in https://github.com/mdn/content/pull/29252/commits/f36ea5404010ea227677e9cbd54a03e15ab2af85.

2023-09-26 15:47 UTC, chrisdavidmills commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +- `connectedCallback()`: called each time the element is added to the document. The specification recommends delaying work until this callback.
Looks great.

2023-09-26 15:49 UTC, chrisdavidmills approved these changes
Perfect, cheers @wbamberg!

2023-09-26 15:49 UTC, merged