fix: Reword SSL to TLS
mdn/content pull request #29305
Opened 2023-09-26 14:16 UTC by SphinxKnight

### Description

SSL 3.0 has been deprecated in 2015. Though "SSL" and "TLS" are most of the time used in an exchangeable manner, MDN should promote up-to-date terminology so that readers (beginners and experts alike) have the right terminology pointers.

### Motivation

Do we use "CSS3" or "HTML5"?
Do we include IE in the BCD table?

### Additional details

I still left some occurrences across the repo when I wasn't 100% sure (notably the proxy stuff for WebExtensions/API/WebRequest) or when it was already "history" (aka: Fx release notes)

### Related issues and pull requests

None that I know of, I didn't look for them.

2023-09-26 16:26 UTC, chrisdavidmills requested changes
Hi @SphinxKnight ;-)

Nice to see you, and thanks for the fixes. I've checked each page, and everything seems pretty much fine. Just a couple of bits to fix.

2023-09-26 16:26 UTC, chrisdavidmills commented on files/en-us/learn/server-side/django/web_application_security/index.md
> +  - : TLS/HTTPS can be enabled on the web server in order to encrypt all traffic between the site and browser, including authentication credentials that would otherwise be sent in plain text (enablin
This new addition reads fine, but the bullet nesting around it seems wrong. Would it make sense to merge your addition with the previous bullet, and then indent the relevant items that it is referring to below?

2023-09-26 16:26 UTC, chrisdavidmills commented on files/en-us/web/security/insecure_passwords/index.md
> +To fix this issue, install and configure a [TLS](/en-US/docs/Glossary/TLS) certificate onto your server. There are various vendors offering free and paid certificates. If you are using a cloud platfo
```suggestion
To fix this issue, install and configure a [TLS](/en-US/docs/Glossary/TLS) certificate on your server. There are various vendors offering free and paid certificates. If you are using a cloud platform, it may have its own ways of enabling HTTPS.
```

(grammar just sounded a bit weird here)

2023-09-26 19:33 UTC, SphinxKnight commented
Thanks for the review and suggestions @chrisdavidmills :) It should be OK now (or I hope :x)

2023-09-26 23:01 UTC, estelle approved these changes
Thank you! 🎉

2023-09-27 17:28 UTC, chrisdavidmills approved these changes
Rock on; cheers @SphinxKnight ! \m/

2023-09-27 17:37 UTC, merged