Fixable flaws on the color_value page
mdn/content pull request #2930
Opened 2021-03-08 10:31 UTC by rachelandrew

Just a bunch of flaws on color_value that I spotted while working on another issue.

2021-03-08 21:48 UTC, ericwbailey requested changes
Just some nitpicks for formatting and empty elements.

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p></p>
```suggestion
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p></p>
```suggestion
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Background color for combo-boxes. Should be used with the <code>-moz-ComboboxText</code> foreground color. In versions prior to 1.9.2, use <code>-moz-Field</code> instead.</p>
```suggestion
 <p>Background color for combo-boxes. Should be used with the <code>-moz-ComboboxText</code> foreground color. In versions prior to 1.9.2, use <code>-moz-Field</code> instead.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Text color for combo-boxes. Should be used with the <code>-moz-Combobox</code> background color. In versions prior to 1.9.2, use <code>-moz-FieldText</code> instead.</p>
```suggestion
 <p>Text color for combo-boxes. Should be used with the <code>-moz-Combobox</code> background color. In versions prior to 1.9.2, use <code>-moz-FieldText</code> instead.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Background color for even-numbered rows in a tree. Should be used with the <code>-moz-FieldText</code> foreground color. In Gecko versions prior to 1.9, use <code>-moz-Field</code>. See also <co
```suggestion
 <p>Background color for even-numbered rows in a tree. Should be used with the <code>-moz-FieldText</code> foreground color. In Gecko versions prior to 1.9, use <code>-moz-Field</code>. See also <code>-moz-OddTreeRow</code>.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Background color for highlighted item in HTML {{HTMLElement("select")}}s. Should be used with the <code>-moz-html-CellHighlightText</code> foreground color. Prior to Gecko 1.9, use <code>-moz-Ce
```suggestion
 <p>Background color for highlighted item in HTML {{HTMLElement("select")}}s. Should be used with the <code>-moz-html-CellHighlightText</code> foreground color. Prior to Gecko 1.9, use <code>-moz-CellHighlight</code>.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Text color for highlighted items in HTML {{HTMLElement("select")}}s. Should be used with the <code>-moz-html-CellHighlight</code> background color. Prior to Gecko 1.9, use <code>-moz-CellHighlig
```suggestion
 <p>Text color for highlighted items in HTML {{HTMLElement("select")}}s. Should be used with the <code>-moz-html-CellHighlight</code> background color. Prior to Gecko 1.9, use <code>-moz-CellHighlightText</code>.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Text color in menu bars. Often similar to <code>MenuText</code>. Should be used on top of <code>Menu</code> background.</p>
```suggestion
 <p>Text color in menu bars. Often similar to <code>MenuText</code>. Should be used on top of <code>Menu</code> background.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Default platform hyperlink color.</p>
```suggestion
 <p>Default platform hyperlink color.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> Background color for odd-numbered rows in a tree. Should be used with the <code>-moz-FieldText</code> foreground color. In Gecko versions prior to 1.9, use <code>-moz-Field</code>. See also <cod
```suggestion
 <p>Background color for odd-numbered rows in a tree. Should be used with the <code>-moz-FieldText</code> foreground color. In Gecko versions prior to 1.9, use <code>-moz-Field</code>. See also <code>-moz-EvenTreeRow</code>.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p><br>
```suggestion
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
>    Used to access the color of text placed over the Windows 10 custom accent color in the start menu, taskbar, title bars, etc.</p>
```suggestion
 <p>Used to access the color of text placed over the Windows 10 custom accent color in the start menu, taskbar, title bars, etc.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> User's preference for the document background color.</p>
```suggestion
 <p>User's preference for the document background color.</p>
```

2021-03-08 21:48 UTC, ericwbailey commented on files/en-us/web/css/color_value/index.html
> + <p> User's preference for the text color.</p>
```suggestion
 <p>User's preference for the text color.</p>
```

2021-03-09 00:17 UTC, nschonni commented
Think a bit of this is covered in https://github.com/mdn/content/pull/2834, but i can rebase that if this lands first

2021-03-11 01:19 UTC, ericwbailey approved these changes

2021-03-11 01:20 UTC, ericwbailey commented
@rachelandrew, @nschonni: Approved, but not merged considering #2834.

2021-03-11 01:25 UTC, nschonni commented
@ericwbailey this one can land. I think it covers more in the specific file than my other PR. I'll just rebase that one after

2021-03-11 01:25 UTC, nschonni commented on files/en-us/web/css/color_value/index.html
> - <p>{{gecko_minversion_inline("1.9")}} Should be used for text in objects with <code>{{cssxref("-moz-appearance")}}: -moz-win-communications-toolbox;</code>.</p>
Actually, should this stay `-moz-appearance`?

2021-03-11 01:25 UTC, merged