Improved cookieStoreId documentation
mdn/content pull request #29337
Opened 2023-09-28 07:38 UTC by rebloor

### Description

Fixes #8267, including:

- "see" link back to the "working with" article for all mentions of cookeStoreId except those in the conceptual identities API.
- updates to the "working with" article, including:
  - adding a full list of APIs that can work with contextual containers
  - update the details about permissions

### Motivation

### Additional details

### Related issues and pull requests

2023-10-02 22:13 UTC, Rob--W requested changes

2023-10-02 22:13 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +To use the {{WebExtAPIRef("contextualIdentities")}} API you need to include the "contextualIdentities" [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) in your [manif
```suggestion
To use the {{WebExtAPIRef("contextualIdentities")}} API you need to include the "contextualIdentities" [permission](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions) in your [manifest.json](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json) file.
```

The mention of the "tabs" permission is out of place here, especially with the new structure of this section.

2023-10-02 22:13 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +If an API enables cookies to be modified then you need the "cookies" permission. For example, in {{WebExtAPIRef("tabs.query")}}, use of`cookieStoreId` does not require the "cookies" API as reading th
```suggestion
If an API enables cookies to be modified then you need the "cookies" permission. For example, in {{WebExtAPIRef("tabs.query")}}, use of`cookieStoreId` does not require the "cookies" API as reading the property doesn't affect the cookies in the containers. However, using {{WebExtAPIRef("tabs.create")}} requires the permission, because the opened tab can read and modify cookies in a container.
```

2023-10-03 01:17 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +To provide contextual identity features in an extension, you use {{WebExtAPIRef("contextualIdentities")}} to add, query, update, and delete contextual identities. When you create a contextual identit
@Rob--W "conceptual identity" was unintended

2023-10-24 18:18 UTC, Rob--W approved these changes
Approved provided that the requested changes have been made. Feel free to request another review if you want to.

2023-10-24 18:18 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +- {{WebExtAPIRef("tabs")}} where you can {{WebExtAPIRef("tabs.create","create")}} a tab to use a contextual identity's cookies store, {{WebExtAPIRef("tabs.tab","get")}} the cookie store ID for a tab,
```suggestion
- {{WebExtAPIRef("tabs")}} where you can {{WebExtAPIRef("tabs.create","create")}} a tab in a specific container tab, {{WebExtAPIRef("tabs.tab","get")}} the cookieStoreId for a tab, and {{WebExtAPIRef("tabs.query","query")}} tabs based on their associated cookie store.
```

cookieStoreId consists of container tabs, private browsing context and the default (non-private) browsing mode. `tabs.create` cannot be used to open a private browsing tab in a non-private window, or a non-private tab in a private window. Therefore I'm specifically pointing to "container tabs" in the tabs.create method.

2023-10-24 18:18 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +- {{WebExtAPIRef("userscripts.register")}} enables you to register a content script in the tabs belonging to one or more cookie store IDs.
```suggestion
- {{WebExtAPIRef("userscripts.register")}} enables you to register a content script restricted to documents associated with one or more specific cookieStoreIds.
```

2023-10-24 18:18 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +- {{WebExtAPIRef("webrequest")}} where all the events return the cookie store ID if the request is associated with a contextual identities tab.
```suggestion
- {{WebExtAPIRef("webrequest")}} where all the events return the cookieStoreId of the request.
```

Also for non-container tabs (and even non-tab requests such as service workers).

2023-10-24 18:18 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/work_with_contextual_identities/index.md
> +- {{WebExtAPIRef("contentscripts.register")}} enables you to register a content script in the tabs belonging to one or more cookie store IDs.
```suggestion
- {{WebExtAPIRef("contentscripts.register")}} enables you to register a content script restricted to documents associated with one or more specific cookieStoreIds.
```

2023-10-25 15:38 UTC, merged

2023-10-25 15:39 UTC, rebloor commented
Thanks @Rob--W release notes added and minor style changes (e.g. formatting `cookieStoreId`)