Link window.navigator.locale and Intl
mdn/content pull request #29347
Opened 2023-09-28 22:10 UTC by waldyrious

### Description

Add a link to `window.navigator.language` in the "See also" section of the `Intl` page, and vice versa.

### Motivation

These pages cover related content, so it's likely that people reading one of them will be interested in the other.

### Additional details

N/A

### Related issues and pull requests

N/A

2023-09-30 02:57 UTC, Josh-Cena requested changes
Could you add an example to both pages as well? This is probably one of the major use cases of `navigator.language`.

2023-09-30 14:16 UTC, waldyrious commented
Do you mean an example of using both in conjunction?

2023-09-30 16:46 UTC, Josh-Cena commented
Yep, basically `new Intl.DateTimeFormat(navigator.language)`.

2023-10-01 22:03 UTC, waldyrious commented
Makes sense! I'll try to work that example in.

2023-10-14 22:14 UTC, waldyrious commented
@Josh-Cena I've updated the branch with an example based on the one you suggested. I also took the opportunity to rebase the branch onto the latest `main`, and fix the commit message as you did to the PR title. Let me know what you think!

2023-10-15 03:22 UTC, Josh-Cena approved these changes
I removed the existing example because it's not illustrative at all of how the API is typically useful. The revised content looks great to me—thanks for working on it!

2023-10-15 03:24 UTC, Josh-Cena commented
BTW, there's also `navigator.languages`, which allows preference-based fallback. I'll hold off merging this after a week so you may revise and add more examples for that as well, but this is also good enough for merging, so just let me know if you intend to do some more improvements.

2023-10-15 16:29 UTC, waldyrious commented
> BTW, there's also navigator.languages, which allows preference-based fallback.

How would this be useful in the context of `Intl`? Is this meant to cover the case that some entries in `navigator.languages` may not correspond to locales supported by `Intl`?

In any case, I'm afraid such an example might end up being too complex to be didactically useful. IMO it's sufficient that `navigator.language` links to `navigator.languages` already. So unless you have a simple, clear example in mind that I could incorporate into the patch, I'd rather keep the PR focused on linking `Intl` and `navigator.language` :slightly_smiling_face:

2023-10-15 16:36 UTC, Josh-Cena commented
`Intl` accepts an array of locales too, meaning you can simply do `new Intl.DateTimeFormat(navigator.languages`, and the first supported language among the preferred ones will be selected.

2023-10-16 00:33 UTC, waldyrious commented
Oh, cool! But just to be sure, is it common/likely that `Intl` will lack support for specific languages reported in `navigator.languages`? :thinking:

2023-10-16 01:22 UTC, Josh-Cena commented
No, probably unlikely, but you can't be sure—for example, someone may be using Balinese as their system language.

2023-10-16 21:46 UTC, waldyrious commented
Done! Is that along the lines of what you had in mind?

2023-10-20 03:14 UTC, Josh-Cena approved these changes
Great job there, thanks a lot.

2023-10-20 03:14 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/index.md
> +The {{domxref("navigator.languages")}} property provides a sorted list of the user's preferred languages. This list can be passed directly to the `Intl` constructors to implement preference-based fal
```suggestion

Alternatively, the {{domxref("navigator.languages")}} property provides a sorted list of the user's preferred languages. This list can be passed directly to the `Intl` constructors to implement preference-based fallback selection of locales. The [locale negotiation](#locale_identification_and_negotiation) process is used to pick the most appropriate locale available:
```

2023-10-20 03:14 UTC, Josh-Cena commented on files/en-us/web/api/navigator/languages/index.md
> +### Listing the contents of `navigator.language` and `navigator.languages`
```suggestion
### Listing the contents of navigator.language and navigator.languages
```

2023-10-20 03:15 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/index.md
> +- {{domxref("navigator.language")}}
```suggestion
- {{domxref("navigator.language")}}
- {{domxref("navigator.languages")}}
```

2023-10-20 14:18 UTC, merged