Add page for HTMLSelectElement showPicker()
mdn/content pull request #29406
Opened 2023-10-01 20:16 UTC by lukewarlow

### Description

Add page for HTMLSelectElement showPicker()

### Motivation

Added as a requirement of the HTML PR.

### Additional details

HTML Spec PR: https://github.com/whatwg/html/pull/9754

ChromeStatus Entry: https://chromestatus.com/feature/5111537299881984

### Related issues and pull requests

Browser Compat Data PR: https://github.com/mdn/browser-compat-data/pull/20852

2023-11-16 13:17 UTC, lukewarlow commented
The Browser Compat Data PR has been merged.

2023-11-20 01:49 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +status:
FYI Only, added this status and `{{SeeCompatTable}}` because this is experimental until it is released in two browsers. Also added the experimental_inline macro (above)

2023-11-20 01:51 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +- `SecurityError` {{domxref("DOMException")}}
Spec seems to indicate that this will also fail if the item is not visible. Can you sanity check please. Should this not also be in the security section - because I presume that is why this exists?

```suggestion
- `NotSupportedError` {{domxref("DOMException")}}
  - : Thrown if the element associated with the picker is not being rendered.
- `SecurityError` {{domxref("DOMException")}}
```

2023-11-20 01:52 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +## Security
Name of the section is inconsistent in MDN, but current favourite is this. It is under discussion.

```suggestion
## Security Considerations
```

2023-11-20 01:53 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +The method is only allowed to be called in same-origin iframes; an exception is thrown if this is called in a cross-origin iframe.
FYI what lives in the security section is under discussion. But I think this is a fairly common restriction I have seen listed before.

2023-11-20 01:54 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +
Could we have an example of this being used? I'm thinking simple code like in the explainer:

```
<select id="select">
  <option>Item 1</option>
  <option>Item 2</option>
</select>
<button onclick="select.showPicker()">Show the select option picker</button>
```

2023-11-20 01:55 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +{{Specifications}}
For some reason this is not showing up. Don't know why because the compat table is.

2023-11-20 01:55 UTC, hamishwillee requested changes
Thanks for this. Looks great. A few questions/ comments such as https://github.com/mdn/content/pull/29406/files#r1398576219

2023-11-20 08:33 UTC, lukewarlow commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +- `SecurityError` {{domxref("DOMException")}}
Ah yeah good catch that was added to the spec after I wrote this PR.

2023-11-21 02:42 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +
@lukewarlow I'll leave this to you and rereview when you ping me!

2023-11-21 08:55 UTC, lukewarlow commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +
Yep no worries! I'm out of office this week so it'll be next week but I'll make the requested changes to get this landed.

2023-11-27 22:31 UTC, hamishwillee commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +
Excellent. I'm off after today until Friday week, so will review your changes then.

2023-11-29 15:17 UTC, lukewarlow commented on files/en-us/web/api/htmlselectelement/showpicker/index.md
> +{{Specifications}}
Seems to be working after a rebase.

2023-12-08 00:48 UTC, hamishwillee approved these changes
Thanks @lukewarlow 
1. I see use case information as helpful but not mandatory.
2. I've made a few subedit changes:
   - Headings are sentence case
   - "Usage" is probably OK here, but usually examples have specific titles about what they cover.
   - I hid the comment about live examples. It is useful if someone else comes along to edit this and decides to add the live example, but there is no expectation for readers.
   - I cross linked to the transient activation page and the input version of the method.
   - If you have any other questions about what I did feel free to ask.

This is good. Thanks so much for sorting it out.

2023-12-08 00:48 UTC, merged