Remove "or refreshes" example language from `overscroll-behavior: contain` docs
mdn/content pull request #29474
Opened 2023-10-04 18:29 UTC by zfox23

### Description

The current doc says:
> Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects **or refreshes**)...

The "or refreshes" part shouldn't be there, because native browser navigation isn't allowed when `overscroll-behavior: contain` is set.

### Motivation

This removes misleading information from `overscroll-behavior` documentation.

### Related issues and pull requests

Resolves: https://github.com/mdn/content/issues/29473 (there are more details in that issue)

2023-10-04 19:03 UTC, estelle commented on files/en-us/web/css/overscroll-behavior-block/index.md
> +  - : Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects), but no scroll chaining occurs to neighboring scrolling areas, e.g. underlying eleme
Should we add that `contain` disables pull-to-refresh while allowing swipe navigation, preventing a user's over-scrolling triggering navigation?

2023-10-04 20:07 UTC, theres-waldo commented on files/en-us/web/css/overscroll-behavior-block/index.md
> +  - : Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects), but no scroll chaining occurs to neighboring scrolling areas, e.g. underlying eleme
`contain` disables both pull-to-refresh and swipe navigation.

The reason [this spec example](https://drafts.csswg.org/css-overscroll/#example-64e64c20) says "only disable pull-to-refresh but allow swipe navigations" is that the property being set is `overscroll-behavior-y: contain;`, and swipe navigation is a horizontal gesture. So `overscroll-behavior-y: contain` will disable pull to refresh (which is a vertical gesture), which `overscroll-behavior-x` will remain at its default value of `auto` which allows swipe navigation.

2023-10-04 20:32 UTC, dipikabh requested changes
Thanks @zfox23 for opening the PR! LGTM. I've suggested some edit.

2023-10-04 20:32 UTC, dipikabh commented on files/en-us/web/css/overscroll-behavior-block/index.md
> +  - : Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects), but no scroll chaining occurs to neighboring scrolling areas, e.g. underlying eleme
Can we rephrase this a bit for more clarity? Also to be more specific, how about adding the bit about "pull-to-refresh" and "swipe navigation"? And if updating here, the same changes can be applied to other files in this PR.

```suggestion
  - : Default scroll overflow behavior (e.g., "bounce" effects) is observed inside the element where this value is set. However, no scroll chaining occurs on neighboring scrolling areas; for example, the underlying elements will not scroll. The `contain` value disables both pull-to-refresh and swipe navigation.
```

2023-10-05 13:58 UTC, zfox23 commented on files/en-us/web/css/overscroll-behavior-block/index.md
> +  - : Default scroll overflow behavior is observed inside the element this value is set on (e.g. "bounce" effects), but no scroll chaining occurs to neighboring scrolling areas, e.g. underlying eleme
Thank you all for the suggestions! It was super helpful for me to see how folks jumped in to improve this PR.

I've made another commit in an effort to address your comments. Please let me know if you approve of these changes.

2023-10-06 12:48 UTC, dipikabh approved these changes
LGTM. Thanks for improving these pages, @zfox23!

2023-10-06 12:48 UTC, merged