CSS list-style shorthand.
mdn/content pull request #29491
Opened 2023-10-05 02:09 UTC by estelle

Part of https://github.com/openwebdocs/project/issues/181

* added see also 
* added actual values to the list of values
* moved accessibility down to below examples
* reduced the explanation of an a11y example as the alternative method is the preferred method.
* links in a11y section

2023-10-09 12:07 UTC, chrisdavidmills requested changes
@estelle more great work, thanks! A few comments for you to mull over.

2023-10-09 12:07 UTC, chrisdavidmills commented on files/en-us/web/css/list-style/index.md
> +```
The visual impact here is potentially quite a big issue. 

Question - does something like

```css
li::marker {
  color: transparent;
}
```

hide the bullets without hiding the list from Safari's accessibility tree?

2023-10-12 21:25 UTC, estelle commented on files/en-us/web/css/list-style/index.md
> +  - : A `<counter-style>`, {{cssxref("string")}}, or `none`. If omitted in the shorthand, the default `disc` value is used. See {{cssxref("list-style-type")}}.
This is a shorthand property, so the links are just to the long-hand values that make up the shorthand and "none", which maybe shouldn't be there. It, like `symbols()` is a list-style-type value, not a value of list style>

Wondering if I should delete none?

2023-10-12 21:38 UTC, estelle commented
@chrisdavidmills Thank you for the review. I addressed the issues and questions you found. thank you. Ready for a re-review with one question: Should we remove none?

2023-10-13 06:57 UTC, chrisdavidmills commented on files/en-us/web/css/list-style/index.md
> +  - : A `<counter-style>`, {{cssxref("string")}}, or `none`. If omitted in the shorthand, the default `disc` value is used. See {{cssxref("list-style-type")}}.
Yeah, I think it is better to leave it, for the reasons you state.

2023-10-13 07:01 UTC, chrisdavidmills approved these changes
@estelle lovely; all comments addressed, and this page is now looking shipshape. Thanks!

2023-10-13 07:01 UTC, merged