refactor: optimize the readability of the code of baselines illustrated example
mdn/content pull request #29536
Opened 2023-10-07 14:46 UTC by AmyFoxFN

### Description
Optimize the readability of the code of baselines illustrated example

### Motivation

I feel confused when reading the old example code.

### Additional details

### Related issues and pull requests

2023-10-08 16:58 UTC, Josh-Cena requested changes

2023-10-08 16:58 UTC, Josh-Cena commented on files/en-us/web/api/textmetrics/index.md
> +  }
No need to check for `undefined`; we assume they all exist, and if one is not, we'd rather throw instead.

2023-10-08 16:58 UTC, Josh-Cena commented on files/en-us/web/api/textmetrics/index.md
> +    lineY = y - Math.abs(textMetrics[baseline]);
Use a ternary, like:

```js
  const lineY = baselinesBelowAlphabetic.includes(baseline)
    ? y + Math.abs(textMetrics[baseline])
    : y - Math.abs(textMetrics[baseline]);
```

This enables you to use `const` instead of `let`.

2023-10-10 17:32 UTC, AmyFoxFN commented on files/en-us/web/api/textmetrics/index.md
> +  }
I think the `undefined` check make sense, because , if let it go on, the `Math.abs(baselineMetricValue)` would be `NaN` and `lineY` would be `NaN`, when the behavior will be fuzzy.

2023-10-13 19:10 UTC, Josh-Cena approved these changes
Sure, thank you :)

2023-10-13 19:11 UTC, merged