Fix to File instance property
mdn/content pull request #29539
Opened 2023-10-08 04:40 UTC by skyclouds2001

### Description

`{{DOMxRef("Blob.size")}}` is incorrectly linked to `{{DOMxRef("Blob.prototype.size")}}`

`{{DOMxRef("Blob.prototype.type")}}` is incorrectly linked to `{{DOMxRef("File.prototype.type")}}`

dumplite page of `File.prototype.type`

### Motivation

remove the page of `File.prototype.type`, as `File` interface does not has a property member `type`, it simply inherits from `Blob` interface

also some updates to `File` summary of properties

### Additional details

https://w3c.github.io/FileAPI/#blob-section

![image](https://github.com/mdn/content/assets/95597335/db961bd4-27c3-4cc2-850a-ab1802377e3a)

https://w3c.github.io/FileAPI/#file-section

![image](https://github.com/mdn/content/assets/95597335/c29629da-2cc8-44c8-84be-324c90c6e99b)

### Related issues and pull requests

2023-10-08 16:53 UTC, Josh-Cena requested changes
Instead of simply deleting a page, you need to run the command locally: `yarn content delete Web/API/File/type --redirect Web/API/Blob/type`. Also, in web API, we don't use `*.prototype.*`—the link is simply `*.*`.

2023-10-13 14:55 UTC, skyclouds2001 commented
> Instead of simply deleting a page, you need to run the command locally: `yarn content delete Web/API/File/type --redirect Web/API/Blob/type`. Also, in web API, we don't use `*.prototype.*`—the link is simply `*.*`.

Done

2023-10-13 19:39 UTC, Josh-Cena approved these changes
LGTM, thanks

2023-10-13 19:42 UTC, Josh-Cena commented on files/en-us/web/api/file/type/index.md
> -> Client configuration (for instance, the Windows Registry) may result in unexpected values even for common types. **Developers are advised not to rely on this property as a sole validation scheme.**
@skyclouds2001: this information is now lost. Is it still relevant? If so, could you move it to `Blob.type` instead?

2023-10-14 03:48 UTC, skyclouds2001 commented on files/en-us/web/api/file/type/index.md
> -> Client configuration (for instance, the Windows Registry) may result in unexpected values even for common types. **Developers are advised not to rely on this property as a sole validation scheme.**
Good idea

2023-10-28 09:51 UTC, Elchi3 commented on files/en-us/web/api/blob/type/index.md
> +> It is assumed based on the file extension; a PNG image file renamed to .txt would give "_text/plain_" and not "_image/png_". Moreover, `file.type` is generally reliable only for common file types l
```suggestion
> It is assumed based on the file extension; a PNG image file renamed to .txt would give "_text/plain_" and not "_image/png_". Moreover, `blob.type` is generally reliable only for common file types like images, HTML documents, audio and video.
```

2023-10-28 09:53 UTC, Elchi3 approved these changes
Thanks @skyclouds2001 👍

2023-10-28 09:53 UTC, merged