Update index.md
mdn/content pull request #29533
Opened 2023-10-07 10:22 UTC by shreyasgosavi

Normal un-layered styles have higher precedece over normal-Layered style. Previously it was written that normal-unlayered styles have higer precesence over normal-important, which is incorrect since layers-styles marked with important have higher precedence than unlayered style.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-10-09 12:22 UTC, chrisdavidmills requested changes
@shreyasgosavi thanks a lot for your contribution to MDN! I think the original wording was correct but confusing. See below for more details, and a suggestion. It's great that you have helped us identify an issue here.

2023-10-09 12:22 UTC, chrisdavidmills commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Next up are any styles declared outside of layers. The styles in `C.css` were not imported into a layer and will override any conflicting styles from `firstLayer` and `secondLayer`. Normal styles not
I think the original wording was correct — it is saying that non-layer styles have higher precedence than normal-importance layered styles, and by "normal-importance", I think it means "not set as `!important`".

However, I do get that the wording is confusing. Can I suggest that you update it to something like this:

> Next up are any styles declared outside of layers. The styles in `C.css` were not imported into a layer and will override any conflicting styles from `firstLayer` and `secondLayer`. Styles not declared in a layer always have higher precedence than styles that _are_ declared inside a layer (with the exception of [`!important`](/en-US/docs/Web/CSS/important) styles).

What do you think?

2023-10-09 16:34 UTC, shreyasgosavi commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Next up are any styles declared outside of layers. The styles in `C.css` were not imported into a layer and will override any conflicting styles from `firstLayer` and `secondLayer`. Normal styles not
Hello  @chrisdavidmills  !! Thank you for your response ... I am still not getting the explanation for the original-one, but as you have suggested the changes which makes it more clear and easy to understand I am updating the request . 

Again thanks for your time .

2023-10-10 08:53 UTC, chrisdavidmills commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Next up are any styles declared outside of layers. The styles in `C.css` were not imported into a layer and will override any conflicting styles from `firstLayer` and `secondLayer`. Normal styles not
Great, thanks for the updates @shreyasgosavi!

I have taken this opportunity to make a few small grammar fixes to the same page, but your changes look good. I will now approve and merge.

2023-10-10 08:54 UTC, chrisdavidmills approved these changes
LGTM

2023-10-10 08:54 UTC, merged

2023-10-10 16:18 UTC, shreyasgosavi commented on files/en-us/learn/css/building_blocks/cascade_layers/index.md
> +Next up are any styles declared outside of layers. The styles in `C.css` were not imported into a layer and will override any conflicting styles from `firstLayer` and `secondLayer`. Normal styles not
Thanks Chris !!!