Add information about firefox default preferences
mdn/content pull request #2954
Opened 2021-03-08 22:51 UTC by hamishwillee

This adds back information about firefox preferences that can be used to set the default referrer-policy, which were removed in #2792. It contributes to #2516

My intent was to include this information in the BCD (https://github.com/mdn/browser-compat-data/pull/9303). However the position taken is that these preferences are not "compatibility information" and shouldn't be in BCD. If you agree with that position it isn't clear where the information should go.

@chrisdavidmills What I have done is put this in its own section Firefox preferences. That removes it from the BCD and makes it very clear that this is Firefox only. I am not particularly happy with this, but I don't want to throw away the information about there is no better place for it (?). Perhaps we could make this section "Browser preferences" and then anyone who wants to add info about other browsers could do so?

Anyway, I consider this "open for discussion"

2021-03-09 09:07 UTC, chrisdavidmills requested changes
Couple of bits to fix in terms of formatting. All in all, I think this is OK. I don't think we should debate endlessly what the optimal solution is here; let's put them here for now, and we can always move the information again later on if a better solution presents itself.

2021-03-09 09:07 UTC, chrisdavidmills commented on files/en-us/web/http/headers/referrer-policy/index.html
> +Firefox preferences can be used to configure the <em>default</em> referrer policy. The preference names are version specific:
Needs wrapping in a `<p>`

2021-03-09 09:07 UTC, chrisdavidmills commented on files/en-us/web/http/headers/referrer-policy/index.html
> +All of these settings take the same set of values: <code>0 = no-referrer</code>, <code>1 = same-origin</code>, <code>2 = strict-origin-when-cross-origin</code>, <code>3 = no-referrer-when-downgrade</
Needs wrapping in a `<p>`

Also, sentence ends in a colon, should be a full stop?

2021-03-15 05:34 UTC, hamishwillee commented on files/en-us/web/http/headers/referrer-policy/index.html
> +All of these settings take the same set of values: <code>0 = no-referrer</code>, <code>1 = same-origin</code>, <code>2 = strict-origin-when-cross-origin</code>, <code>3 = no-referrer-when-downgrade</
Thank you.

2021-03-15 05:36 UTC, hamishwillee commented
@chrisdavidmills Agreed. Thanks for the review - highlighted issues fixed.

2021-03-15 07:56 UTC, chrisdavidmills approved these changes
Perfect; thanks @hamishwillee !

2021-03-15 07:56 UTC, merged