fix(css): correct values in the example
mdn/content pull request #29598
Opened 2023-10-11 15:32 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/29503

`a` and `b` axis values should be in range `-0.4` to `0.4`.

2023-10-12 18:00 UTC, dipikabh requested changes
Thanks for these fixes, @OnkarRuikar. 

> `a` and `b` axis values should be in range `-0.4` to `0.4`.
Nothing wrong with the updated values but technically, `a` and `b` can be specified as percentages too, correct?

2023-10-12 18:00 UTC, dipikabh commented on files/en-us/web/css/color_value/oklab/index.md
> +- [OKLAB color wheel](https://observablehq.com/@shan/oklab-color-wheel)
```suggestion
- [A perceptual color space for image processing](https://bottosson.github.io/posts/oklab/) on bottosson.github.io (2023)
- [OKLAB color wheel](https://observablehq.com/@shan/oklab-color-wheel) on observablehq.com
```

2023-10-12 18:04 UTC, OnkarRuikar commented
> Thanks for these fixes, @OnkarRuikar.
> 
> > `a` and `b` axis values should be in range `-0.4` to `0.4`.
> 
> Nothing wrong with the updated values but technically, `a` and `b` can be specified as percentages too, correct?

Yes, 100% is 0.4.

2023-10-14 03:00 UTC, dipikabh commented
> It's hard to understand these new color spaces with rgb mindset. We really need to have 3d illustrations of theses color spaces on these pages. There is no image of oklab space on the Internet.

It is difficult, I agree. And the best we can do at the moment is to add links to closest relevant articles (we've already linked to the blog of the oklab creator). I looked for others and came across this: [An interactive review of Oklab](https://raphlinus.github.io/color/2021/01/18/oklab-critique.html) - it does not provide 3D illustrations, but might be useful to compare and understand differences between Oklab and other color spaces. WDYT about adding this resource as well to "See also"?

2023-10-14 03:00 UTC, dipikabh approved these changes
Thank you! 👍

2023-10-14 03:01 UTC, merged