29308 css length units in svg
mdn/content pull request #29599
Opened 2023-10-11 15:56 UTC by dletorey

### Description

- Added an example of of using level 3 CSS Length units to `svg` element in the `height` & `width` attributes.
- Added related relase not to 119

### Motivation

Working on [issue 29308](https://github.com/mdn/content/issues/29308)

### Related issues and pull requests

- [Bugzilla 1287054](https://bugzilla.mozilla.org/show_bug.cgi?id=1287054)

2023-10-11 17:28 UTC, zfox23 requested changes
thank you :)

2023-10-11 17:28 UTC, zfox23 commented on files/en-us/web/svg/element/svg/index.md
> +This example the `height` and `width` attributes, on the `svg` element, are set using the dynamic viewport values `vmin`
One suggestion in this text:
```suggestion
In this example, the `height` and `width` attributes on the `svg` element are set using the dynamic viewport value `60vmin`, equivalent to 60% of the viewport's width or height, whichever is smaller. 
```

Secondly, I like your comment about changing the iframe's dimensions to support the example. I think more people would read that text if it were up here, on a new line underneath _this_ text, such as:

>To change the iframe viewport's dimensions - thus impacting the dimensions of the `svg` - click and drag the iframe's dotted red border from its bottom right corner.

2023-10-11 17:28 UTC, zfox23 commented on files/en-us/web/svg/element/svg/index.md
> +### Using dynamic viewport lengths
```suggestion
### Using dynamic viewport units
```

2023-10-11 23:39 UTC, longsonr commented
I'm afraid this isn't really right. Firefox has supported CSS level 3 units on `<svg>` and some other elements such as `<rect>`, `<circle>`, `<ellipse>`, `<image>`, `<foreignObject>` and `<use>` for some time. What the bug does is support those units on all elements that were not previously supported for example `<line>`, `<filter>`, `<clipPath>` (and others). And it's not limited to width/height either, you can write `<line x1="10ch" y1="10vw" x2="20rem" y2="15vmin"/>` for example.

2023-10-11 23:41 UTC, longsonr commented
Oh and a level 3 length is anything in https://drafts.csswg.org/css-values-3/#viewport-relative-lengths, as opposed to a level 4 length which would be from the css-values-4 spec instead. level 4 is a superset of level 3.

2023-10-17 13:18 UTC, dletorey commented
> I'm afraid this isn't really right. Firefox has supported CSS level 3 units on `<svg>` and some other elements such as `<rect>`, `<circle>`, `<ellipse>`, `<image>`, `<foreignObject>` and `<use>` for some time. What the bug does is support those units on all elements that were not previously supported for example `<line>`, `<filter>`, `<clipPath>` (and others). And it's not limited to width/height either, you can write `<line x1="10ch" y1="10vw" x2="20rem" y2="15vmin"/>` for example.

Understood, working on it

2023-10-18 13:29 UTC, zfox23 requested changes
one grammar nit, and one suggestion for brevity

2023-10-18 13:33 UTC, zfox23 approved these changes
thank you!

2023-10-18 13:33 UTC, dletorey commented
> thank you!

That was super quick

2023-10-18 13:34 UTC, zfox23 commented
@longsonr i want to make sure that your comments are addressed. if you see this and are comfortable with the changes, please merge. otherwise, i'll merge tomorrow evening ☺️

2023-10-19 20:10 UTC, merged

2023-10-19 20:20 UTC, longsonr commented
This looks great. I'm happy with all changes.