Centering in CSS
mdn/content pull request #29609
Opened 2023-10-12 04:01 UTC by estelle

this page was super outdated. Added grid and  removed old text

2023-10-12 17:16 UTC, dipikabh requested changes
Thank you for adding the updated info, @estelle! I've suggested a few edits.

2023-10-12 17:16 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/center_an_element/index.md
> +Another method of centering one box inside another is to make the containing box a grid container and set {{cssxref("place-items", "place-items: center" )}} on it to center its items on both the bloc
```suggestion
Another method you can use for centering one box inside another is to first make the containing box a [grid container](/en-US/docs/Web/CSS/CSS_grid_layout/Basic_concepts_of_grid_layout#grid_container) and then set its {{cssxref("place-items")}} property to `center` to center align its items on both the block and inline axes.
```

2023-10-12 17:16 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/center_an_element/index.md
> +Alternatively, we could have set {{cssxref("place-content", "place-content: center;")}} on the container instead or set either {{cssxref("place-self", "place-self: center")}} or {{cssxref("margin", "
```suggestion
Instead of applying `place-items: center;` on the container, you can achieve the same centering by setting {{cssxref("place-content", "place-content: center;")}} on the container or by applying either {{cssxref("place-self", "place-self: center")}} or {{cssxref("margin", "margin: auto;")}} on the inner item itself.
```

2023-10-12 21:56 UTC, estelle commented
Thanks @dipikabh. The second page is causing issues with the linter. Will submit that in a different PR to not hold this one up.

2023-10-14 03:07 UTC, dipikabh requested changes

2023-10-14 03:07 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/center_an_element/index.md
> +To center a box within another box, first turn the containing box into a [flex container](/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox#the_flex_container) by settings its {{c
```suggestion
To center a box within another box, first turn the containing box into a [flex container](/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox#the_flex_container) by settings its {{cssxref("display")}} property to `flex`. Then set {{cssxref("align-items")}} to `center` for vertical centering (on the block axis) and {{cssxref("justify-content")}} to `center` for horizontal centering (on the inline axis). And that's all it takes to center one box inside another!
```

2023-10-14 03:09 UTC, dipikabh approved these changes
Thank you! 👍

2023-10-14 03:09 UTC, merged

2023-10-31 00:27 UTC, estelle commented
related to https://github.com/openwebdocs/project/issues/184