fix(css): remove unimplemented future values from text-overflow
mdn/content pull request #29626
Opened 2023-10-13 07:03 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/29466

As per BCD policy we can't add unimplemented features to the compatibility tables. No browser has implemented the features yet. As per the internal discussion removing the future unimplemented properties which are undergoing changes at the moment.

2023-10-13 15:07 UTC, dipikabh requested changes
Thanks, @OnkarRuikar. Suggested a slight nit. Thanks for the fix!

2023-10-13 15:07 UTC, dipikabh commented on files/en-us/web/css/text-overflow/index.md
>  The `text-overflow` property may be specified using one or two values. If one value is given, it specifies overflow behavior for the end of the line (the right end for left-to-right text, the left en
- We're missing a lead-in for the list that follows.
- Also, since it is just two items in the list, we can combine that info here.
```suggestion
The `text-overflow` property may be specified using one or two values. If one value is given, it specifies overflow behavior for the end of the line (the right end for left-to-right text, the left end for right-to-left text). If two values are given, the first specifies overflow behavior for the left end of the line, and the second specifies it for the right end of the line. The property accepts either a keyword value (`clip` or `ellipsis`) or a `<string>` value.
```

2023-10-13 15:07 UTC, dipikabh commented on files/en-us/web/css/text-overflow/index.md
>  - a `<string>`.
Can be removed as per previous edit suggestion
```suggestion
```

2023-10-13 17:49 UTC, OnkarRuikar commented on files/en-us/web/css/text-overflow/index.md
```suggestion
```

2023-10-14 03:03 UTC, dipikabh approved these changes
Thanks!

2023-10-14 03:03 UTC, merged