ARIA form role: exposed if it has an accessible name
mdn/content pull request #29636
Opened 2023-10-14 00:21 UTC by estelle

https://www.w3.org/TR/html-aria/#el-form

2023-10-16 10:03 UTC, chrisdavidmills requested changes
@estelle hrm, I feel like I've made a mountain out of a molehill with this one/ Let me know what you think.

2023-10-16 10:03 UTC, chrisdavidmills commented on files/en-us/web/html/element/form/index.md
> +The **`<form>`** [HTML](/en-US/docs/Web/HTML) element represents a document section containing interactive controls for submitting information. The form is not exposed as a landmark region unless it
This change looks correct to me, but I can't help wondering whether the average reader will have a clue what a landmark region is. Would it be even better to link to something that explains what it is and how to give it an accessible name, and/or provide more clues in the text, for example, something like

>  The form is not exposed to [screen readers](/en-US/docs/Glossary/Screen_reader) as a landmark region unless it has an [accessible name](/en-US/docs/Glossary/Accessible_name) provided via the `name` attribute.

?

Also, does a form always need a specific accessible name, or is this only needed in some circumstances, e.g. when you have multiple forms on a page? If there is only one form and the top-level heading for the pages clearly says this page contains a form, isn't it OK to not include this as long as the individual form elements are clearly labelled? 

 I feel like I'm being horribly picky now, but it seems to me like this statement needs to come with some advice on when this is necessary. And, if it is necessary to always include this, examples on the page and elsewhere need to be updated to align with this advice.

2023-10-16 15:39 UTC, closed without merging

2023-10-16 17:32 UTC, estelle commented
Thanks for the review. This PR was a mistake. I meant to add the sentence to the form role not form element. 
closed this and opened:
https://github.com/mdn/content/pull/29665

2023-10-17 06:25 UTC, chrisdavidmills commented
> Thanks for the review. This PR was a mistake. I meant to add the sentence to the form role not form element. closed this and opened: #29665

Ah, that makes more sense ;-)