DRAFT: CSS Counters Module
mdn/content pull request #29669
Opened 2023-10-16 19:54 UTC by estelle

* rewrite CSS counters module
* Update system descriptor

2023-10-19 01:31 UTC, dipikabh requested changes
Thanks for updating these pages, @estelle! 🙌 

I've added my edit suggestions as well as some questions.

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +  - : Defines a finite set of symbols are specified; iterating once through the list of symbols provided in the `symbols` descriptor. Once the system iterated through the symbols specified, the fallb
Last two sentences are not clear. Does the integer mark an item from the `symbols` list or the item in the content list? I've made some edits based on my understanding - please check for technical accuracy.

```suggestion
- `fixed` or `fixed <integer>`

  - : Defines a finite set of symbols, iterating once through the list of symbols provided in the `symbols` descriptor. Once the specified symbols have been iterated through, the fallback counter style is used. This keyword value is useful in cases where the counter style values are finite. At least one symbol must be specified in the `symbols` descriptor, otherwise the counter style is not valid. The `fixed` keyword can be followed by an optional {{cssxref("&lt;integer&gt;")}} value. If specified, the `<integer>` value indicates the item in the list that will get the first symbol from the list of symbols. If omitted, the default value of `integer` is `1`, which gives the first item in the list the first symbol.
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +  - : Cycles through the symbols provided in the `symbols` descriptor list of symbols repeatedly, doubling, tripling, etc. the symbols on each successive pass through the list. For example, if there
```suggestion
  - : Cycles through the symbols provided in the `symbols` descriptor list repeatedly, doubling, tripling, and so on, the symbols on each successive pass through the list. For example, if two symbols "◽" and "◾" are specified in the `symbols` descriptor, on each successive pass, they will become "◽◽" and "◾◾" and "◽◽◽" and "◾◾◾" and so on in subsequent passes. At least one symbol must be specified in the `symbols` descriptor, otherwise the counter style is not valid. This counter system works for positive counter values only.
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +  - : Allows authors to use extend the algorithm of another browser or author defined counter style by altering its other aspects. Any unspecified descriptors, and their values will be taken from the
```suggestion
  - : Extends the algorithm of another browser- or author-defined counter style by allowing the alteration of some aspects of the extended counter style. Any unspecified descriptors and their values are inherited from the extended counter style specified. If the counter style name specified with `extends` is not yet defined, the `decimal` counter style will be extended by default.
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
>      It must not contain a `symbols` or `additive-symbols` descriptor, or else the counter style rule is invalid. If one or more counter styles definitions form a cycle with their extends values, the
```suggestion
    It must not contain a `symbols` or `additive-symbols` descriptor, otherwise the counter style rule will be invalid. If one or more counter styles definitions form a cycle with their `extends` values, the browser will treat all the participating counter styles as extending from the `decimal` style.
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +The `fixed` value iterates through the list of symbols only once, starting the single cycle at the number indicated by the integer:
```suggestion
The `fixed` value iterates through the list of symbols only once, starting the single cycle at the list item number indicated by the `integer` value:
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +The `symbolic` value loops throught the list defined in the `symbols` descriptor, doubling and tripling the number of symbols for the second and third cycles through the list, respectively:
```suggestion
The `symbolic` value loops through the list defined in the `symbols` descriptor, doubling and tripling the number of symbols for the second and third cycles through the list, respectively:
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
>  #### CSS<br>
```suggestion
#### CSS
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +We included the [`start`](/en-US/docs/Web/HTML/Element/ol#start) attribute on the {{HTMLElement("ol")}} to demonstrate that counting doesn't need to start with `1` and the [`value`](/en-US/docs/Web/H
```suggestion
We use the [`start`](/en-US/docs/Web/HTML/Element/ol#start) attribute on the {{HTMLElement("ol")}} element to demonstrate that counting doesn't need to start at `1`. Additionally, we use the [`value`](/en-US/docs/Web/HTML/Element/li#value) attribute on the fifth {{HTMLElement("li")}} element to demonstrate that the counters you define using `@counter-style` behave just like native counters.
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
>  ### Extends example
```suggestion
### Extending a counter
```

2023-10-19 01:31 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
> +This example will use the algorithm, symbols, and other properties of [`lower-alpha`](/en-US/docs/Web/CSS/list-style-type#lower-alpha), one of the several native {{CSSXref("list-style-type")}} counte
```suggestion
This example uses the algorithm, symbols, and other properties of [`lower-alpha`](/en-US/docs/Web/CSS/list-style-type#lower-alpha), one of the several native {{CSSXref("list-style-type")}} counter values, but extends it by removing the period (`'.'`) after the counter representation and enclosing the characters in parentheses, as in  `(a)` and `(b)`.
```

2023-10-19 02:37 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- {{cssxref("counters", "counters()")}} function
i am working on that page now, so that PR should be in next week.

2023-10-19 19:01 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- [Ready-made counter styles](https://w3c.github.io/predefined-counter-styles/) via W3C
this page is W3C, so no date needed, or mention of github.

2023-10-19 19:25 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- [`<counter-style>`](/en-US/docs/Web/CSS/@counter-style#counter-style-name)
```suggestion
```

2023-10-19 19:29 UTC, estelle commented on files/en-us/web/css/@counter-style/system/index.md
> +The values include:
done.

2023-10-19 21:46 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +  - {{cssxref("@counter-style/symbols", "symbols")}}
this is the order in which they are generally declared. The first ones are required, the last one rarely used.

2023-10-19 21:53 UTC, estelle commented on files/en-us/web/css/@counter-style/system/index.md
>  system: extends decimal;
I added " unless you are overriding or extending the style type" to the @counter-style definition

2023-10-19 22:09 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- [Ready-made counter styles](https://w3c.github.io/predefined-counter-styles/) via W3C
added the `#builtins` but left of the date and github link as the W3C as the repo is actively maintained and the W3C org is the org, github is just the host

2023-10-19 22:10 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- {{domxref("CSSCounterStyleRule")}} interface
it was in the see also, but added it here too. I also keep finding it, and it's kind of useless, but maybe it will be useful someday.

2023-10-19 22:11 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- [Ready-made counter styles](https://w3c.github.io/predefined-counter-styles/) via W3C
oops, github ate my comments and then regurgitated them ;) I was wondering what happened.

2023-10-20 00:09 UTC, estelle commented on files/en-us/web/css/css_counter_styles/index.md
> +- [`<counter-style-name>`](/en-US/docs/Web/CSS/@counter-style#counter-style-name)
declaration list is not defined by this spec, but i did define it in one sentence on the page that uses it.
counter-style removed. good catch
counter style name does not have its own page.

2023-10-20 00:10 UTC, estelle commented
Thanks @dipikabh  for the excellent review. I think I captured all the issues.

2023-10-23 15:44 UTC, dipikabh requested changes
Thanks for the updates and clarifying notes. I've pointed a few last nits.

2023-10-23 15:44 UTC, dipikabh commented on files/en-us/web/css/@counter-style/system/index.md
>  system: extends decimal;
Thanks

2023-10-23 22:04 UTC, estelle commented
@dipikabh Thanks for the review. I think we're good to go.

2023-10-24 01:29 UTC, dipikabh approved these changes
Thank you!

2023-10-24 01:34 UTC, dipikabh requested changes
checking if this can resolve the lint error

2023-10-24 01:34 UTC, dipikabh commented on files/en-us/web/css/css_counter_styles/index.md
> +   - {{domxref("CSSCounterStyleRule")}} interface
```suggestion
- {{domxref("CSSCounterStyleRule")}} interface
```

2023-10-24 01:39 UTC, dipikabh approved these changes

2023-10-24 01:39 UTC, merged