CSS modules: Symbols descriptor and function
mdn/content pull request #29707
Opened 2023-10-18 17:38 UTC by estelle

update the symbols descriptor page and the symbols() function, as part of the css module rewrite.

2023-10-30 17:49 UTC, dipikabh requested changes
Thanks @estelle! Added a few edit suggestions.

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +If using an {{glossary("identifier")}} rather than a string for a symbol, be aware that {{glossary("ASCII")}} non-letters like `*`, `"` and `\` are not identifiers and must be quoted as a string or e
This should be added as a continuation of the `<symbol>` description. Also, how about adding it as a note instead?
```suggestion
  > **Note:** When using an {{glossary("identifier")}} for a symbol, note that {{glossary("ASCII")}} non-letters such as `*`, `"`, and `\` are not considered identifiers. They must be either quoted as a string or escaped.
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +  - : Represents a symbol used within the counter system. Each symbol in the list of symbols is a {{cssxref("&lt;string&gt;")}}, {{cssxref("&lt;image&gt;")}}, {{cssxref("&lt;custom-ident&gt;")}}.
Because they appear in "Formal syntax", can we also add a line about the type of values accepted by `<image>` (added as a suggestion below) and `<url>`?
```suggestion
  - : Specifies the symbol to use within the counter system. Each symbol in the list can be either a {{cssxref("&lt;string&gt;")}}, an {{cssxref("&lt;image&gt;")}}, or a {{cssxref("&lt;custom-ident&gt;")}}. The `<image>` value can, in turn, be specified as a {{cssxref("&lt;url&gt;")}} or {{cssxref("&lt;gradient&gt;")}}.
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +When the value of the {{cssxref('@counter-style/system', 'system')}} descriptor is `cyclic`, `numeric`, `alphabetic`, `symbolic`, or `fixed`, the `symbols` descriptor must be specified. When the `add
```suggestion
When the value of the {{cssxref('@counter-style/system', 'system')}} descriptor is `cyclic`, `numeric`, `alphabetic`, `symbolic`, or `fixed`, the `symbols` descriptor must be specified. For the `additive` system, use the {{cssxref('@counter-style/additive-symbols', 'additive-symbols')}} descriptor instead to specify the symbols.
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
>  While a space between quoted symbols is not required, it makes the CSS more legible. To use a quote as a symbol, either escape the quote character or enclose the character is using different quotes,
```suggestion
While a space between quoted symbols is not required, it makes CSS more readable. To use a quote as a symbol, either escape the quote character or enclose the character within different quotes, such as `"'"`.
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +If using identifiers rather than strings to define the symbols, be aware of the syntax of identifiers. As noted above, ASCII non-letters like `*` are not identifiers and must either be quoted in a st
Can we add a quick, short example of "Hex escape characters"? Something like "better to use the string `"\2A 1"` instead of `\2A  1` with two spaces.
```suggestion
When defining symbols with identifiers instead of strings, be sure to use identifier syntax rules. For example, as noted above, ASCII non-letters such as `*` are not identifiers and must be either quoted or escaped. Hex escape characters are followed by a space. This space may look like the space separating two identifiers, but it enables digits to follow hex-escaped characters. This means that two spaces must be included after a hex-escaped identifier to separate it from the next identifier. As your code tools might remove double spaces, it is safer to quote identifiers that need to be escaped or use strings.
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +- {{cssxref("list-style")}}, {{cssxref("list-style-image")}}, {{cssxref("list-style-position")}} properties
```suggestion
- List style properties: {{cssxref("list-style")}}, {{cssxref("list-style-image")}}, {{cssxref("list-style-position")}}
```

2023-10-30 17:49 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +
For a description of the example after line 52 `### Setting counter symbols`, we could say something like:
"In this example, the list of values for the `symbols` descriptor include letters (`A`, `D`, `E`), a number within quotes (`"1"`), and a hex-escape identifier within quotes (`"\24B7"`) for the character `Ⓑ`.

2023-10-30 22:52 UTC, estelle commented
Thanks @dipikabh. I think (hope) we're good to go!

2023-10-31 15:13 UTC, dipikabh requested changes

2023-10-31 15:14 UTC, dipikabh approved these changes
Thank you! 👍

2023-10-31 15:21 UTC, dipikabh requested changes
I just noticed the preview page. The DL will need fixing.

2023-10-31 15:21 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +  - : Specifies the symbol to use within the counter system. Each symbol in the list can be either a {{cssxref("&lt;string&gt;")}}, an {{cssxref("&lt;image&gt;")}}, or a {{cssxref("&lt;custom-ident&g
The formatting needs to be fixed. The DL is showing bullets.

2023-10-31 15:32 UTC, dipikabh commented on files/en-us/web/css/@counter-style/symbols/index.md
> +  - : Specifies the symbol to use within the counter system. Each symbol in the list can be either a {{cssxref("&lt;string&gt;")}}, an {{cssxref("&lt;image&gt;")}}, or a {{cssxref("&lt;custom-ident&g
Probably the Note indentation is messing up the DL formatting

2023-11-01 01:28 UTC, dipikabh approved these changes
👍

2023-11-01 01:28 UTC, merged