Add legacy support to beforeunload examples
mdn/content pull request #29703
Opened 2023-10-18 14:18 UTC by chrisdavidmills

### Description

I created https://github.com/mdn/content/pull/29595 to modernize the `beforeunload` event information on MDN and update the Chromium support information.

This seemed OK, but https://github.com/mdn/content/issues/29655 was then filed — the new demos created confusion for users of Chromium < 119 browsers.

As suggested by @caugner, I am raising this PR to fix this by adding legacy support to the examples.

### Motivation

### Additional details

### Related issues and pull requests

2023-10-18 16:27 UTC, caugner requested changes

2023-10-18 16:27 UTC, caugner commented on files/en-us/web/api/beforeunloadevent/index.md
> +  event.returnValue = true;
Returning true has more legacy support than setting `returnValue`, so probably a wiser choice? 

```suggestion
  return true;
```

2023-10-18 16:39 UTC, chrisdavidmills commented on files/en-us/web/api/beforeunloadevent/index.md
> +  event.returnValue = true;
The thing about the "return truthy value" option is that it only works with `onbeforeunload = func`, not with `addEventListener('beforeunload', func)`. I therefore decided that the `returnValue` option was a better, less confusing choice.

2023-10-19 13:58 UTC, xgqfrms commented on files/en-us/web/api/beforeunloadevent/index.md
> +  event.returnValue = true;
LGTM.

2023-10-27 17:16 UTC, caugner approved these changes

2023-10-30 11:07 UTC, merged