runtime.onInstalled use in event pages clarification
mdn/content pull request #29716
Opened 2023-10-19 02:12 UTC by rebloor

### Description

Add an explanation as to why stateful API should be included in the onInstalled for event pages. Fixed #17212

2023-10-24 18:00 UTC, Rob--W requested changes
I think that more details are needed before #17212 can be marked as resolved.

The Extension Workshop has a lot of detail on the persistence of menu items across restarts. The short version is that in Firefox, menu items are not persisted in persistent background pages (a persistent background page starts up once and doesn't terminate until the browser or extension unloads, so a top-level `create` call will always create the menu), and persisted in non-persistent background pages (aka event page; to avoid repeated attempts to create the menu item, it should be registered only once).

Can you clarify the documentation to reduce this confusion? E.g. by adding a NOTE and more details (maybe even a link to Extension workshop?) in the menus.create article on MDN.

2023-10-26 22:33 UTC, Rob--W requested changes

2023-10-26 22:33 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/create/index.md
> +> - in extensions using non-persistent background pages (an event page), menus persist. You call `menus.create` from within a {{WebExtAPIRef("runtime.onInstalled")}} listener. This avoids repeated at
```suggestion
> - in extensions using non-persistent background pages (an event page), menus persist across browser and extension restarts. You call `menus.create` (with a menu-specific ID) from within a {{WebExtAPIRef("runtime.onInstalled")}} listener. This avoids repeated attempts to create the menu item when the pages restart, which would occur with a top-level call.
> - In Chrome, menu items from persistent background pages are also persisted.
> - In Firefox, menu items from persistent background pages are never persisted. Call `menus.create` unconditionally from the top-level to make sure that the menu items are registered.
```

I swapped the bullet points and emphasized the difference between Chrome and Firefox.

2023-10-26 22:33 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/menus/index.md
> +In an extension using non-persistent [background pages](/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts) (Event pages), you call `menus.create` from within a {{WebExtAPIRef("runtime.onIn
The behavior is Firefox/Chrome-dependent.

2023-10-27 10:19 UTC, Rob--W approved these changes

2023-10-27 15:46 UTC, merged

2023-10-27 15:47 UTC, rebloor commented
Thanks @Rob--W