runtime.requestUpdateCheck() argument in example correction
mdn/content pull request #29715
Opened 2023-10-19 01:03 UTC by rebloor

### Description

Fixes #16798. Verified on Chrome (as this method isn't supported by Firefox):

![image](https://github.com/mdn/content/assets/7352080/ff27b484-fa5f-4b03-97d3-1b417718c4a5)

Also:

- swapped the order of examples and browser compatibility sections
- fixed minor stylistic and grammar issues

2023-10-24 17:51 UTC, Rob--W requested changes

2023-10-24 17:51 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/requestupdatecheck/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that is fulfilled with two arguments:
```suggestion
A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that is fulfilled with an object with the result of the update request.
```

The previous and current documentation is incorrect. It's a single object, not a number of positional parameters.

2023-10-24 17:51 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/requestupdatecheck/index.md
>  - `details` {{optional_inline}}
```suggestion
- `result` {{optional_inline}}
  - `status`
    - : A {{WebExtAPIRef('runtime.RequestUpdateCheckStatus')}} value — the result of the update check.
```

Changes:
- moved "status" under the object.
- renamed "details" to "result", consistent with Chrome's docs.

2023-10-24 17:51 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/requestupdatecheck/index.md
>  function onRequested(status, details) {
```suggestion
function onRequested(result) {
```

Github doesn't offer more context, more changes that you need to make before merging:

- Replace `status` with `result.status` (2x)
- Replace `details.version` with `result.version`

2023-10-25 19:17 UTC, Rob--W reviewed
The [rendered result](https://pr29715.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/requestUpdateCheck) looks very broken. Could you fix up the formatting?

2023-10-25 23:16 UTC, rebloor commented
@Rob--W On looking at this again it wasn't just the formatting that was wrong. Fixed

2023-10-26 09:28 UTC, Rob--W approved these changes

2023-10-26 17:39 UTC, merged