css counter descriptor: prefix
mdn/content pull request #29736
Opened 2023-10-20 01:54 UTC by estelle

part of https://github.com/openwebdocs/project/issues/181

2023-10-23 07:48 UTC, chrisdavidmills requested changes
@estelle fine work! I've left you some suggestions and comments.

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
> +/* <symbol> values: string, image, or identifier */
`<symbol> values` implies that multiple values can be added at the same time, but that's not the case according to the text description? In which case `<symbol> value` would be better?

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
> +The **`prefix`** descriptor takes as it's value a single `<symbol>`:
```suggestion
The **`prefix`** descriptor takes as its value a single `<symbol>`:
```

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
> +  - : Specifies a `<symbol>`, a {{cssxref("&lt;string&gt;")}}, {{cssxref("&lt;image&gt;")}}, or {{cssxref("&lt;custom-ident&gt;")}}, that is prepended to the marker representation.
I think this is now slightly less clear — it reads like `<symbol>` is the first item in the list of possibilities. To mitigate this issue, I would separate out the list with something more drastic, such as em-dashes.

```suggestion
  - : Specifies a `<symbol>` — a {{cssxref("&lt;string&gt;")}}, {{cssxref("&lt;image&gt;")}}, or {{cssxref("&lt;custom-ident&gt;")}} — that is prepended to the marker representation.
```

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
> +In this example, each counter number is prefixed by "Book " (with a space) and followed by a colon (`:`). The colon is added with the {{cssxref("@counter-style/suffix", "suffix")}} descriptor.
This example is really cool; I didn't know you could do this. I learned something today.

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
> +- Other {{cssxref("@counter-style")}} descriptors, including, {{cssxref("@counter-style/system","system")}}, {{cssxref("@counter-style/symbols", "symbols")}}, {{cssxref("@counter-style/additive-symbo
```suggestion
- Other {{cssxref("@counter-style")}} descriptors: {{cssxref("@counter-style/system","system")}}, {{cssxref("@counter-style/symbols", "symbols")}}, {{cssxref("@counter-style/additive-symbols", "additive-symbols")}}, {{cssxref("@counter-style/negative", "negative")}}, {{cssxref("@counter-style/suffix", "suffix")}}, {{cssxref("@counter-style/range", "range")}}, {{cssxref("@counter-style/pad", "pad")}}, {{cssxref("@counter-style/speak-as", "speak-as")}}, and {{cssxref("@counter-style/fallback", "fallback")}}
```

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/prefix/index.md
>  - {{cssxref("symbols", "symbols()")}}, the functional notation creating anonymous counter styles
```suggestion
- {{cssxref("symbols", "symbols()")}}: the functional notation for creating anonymous counter styles
```

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/suffix/index.md
> +The **`suffix`** descriptor of the {{cssxref("@counter-style")}} rule specifies content that will be appended at the end of the marker representation.
"appended" means "added to the end of", so this edit is not really needed. You could just follow the same style as you've used on the `prefix` page, and say "...that will be added to the end of..."

2023-10-23 07:48 UTC, chrisdavidmills commented on files/en-us/web/css/@counter-style/suffix/index.md
> +/* <symbol> values: string, image, or identifier  */
Same comment as for the `prefix` page. Would `<symbol> value` be better?

2023-10-23 22:09 UTC, estelle commented on files/en-us/web/css/@counter-style/suffix/index.md
> +The **`suffix`** descriptor of the {{cssxref("@counter-style")}} rule specifies content that will be appended at the end of the marker representation.
I added it for non-native English speakers, but changing to added is even better!

2023-10-23 22:09 UTC, estelle commented on files/en-us/web/css/@counter-style/suffix/index.md
> +The **`suffix`** descriptor of the {{cssxref("@counter-style")}} rule specifies content that will be appended at the end of the marker representation.
```suggestion
The **`suffix`** descriptor of the {{cssxref("@counter-style")}} rule specifies content that will be added to the end of the marker representation.
```

2023-10-23 22:10 UTC, estelle commented on files/en-us/web/css/@counter-style/prefix/index.md
> +/* <symbol> values: string, image, or identifier */
```suggestion
/* <symbol> value: string, image, or identifier */
```

2023-10-23 22:10 UTC, estelle commented on files/en-us/web/css/@counter-style/suffix/index.md
> +/* <symbol> values: string, image, or identifier  */
```suggestion
/* <symbol> value: string, image, or identifier  */
```

2023-10-23 22:11 UTC, estelle commented on files/en-us/web/css/@counter-style/suffix/index.md
> +/* <symbol> values: string, image, or identifier  */
dropped the "s"

2023-10-23 22:11 UTC, estelle commented
Thanks @chrisdavidmills !

2023-10-26 12:41 UTC, chrisdavidmills approved these changes
Yusss, this is perfect, great work @estelle! Let's get this merged.

2023-10-26 12:50 UTC, merged