Counter descriptor: pad
mdn/content pull request #29820
Opened 2023-10-24 20:55 UTC by estelle

part of https://github.com/openwebdocs/project/issues/181

2023-10-26 00:10 UTC, dipikabh requested changes
Thanks for these updates, @estelle!

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +Pad descriptor takes the minimum marker length as an integer and a symbol to be used for padding as the second parameter. A common usage of the pad descriptor is when you need your list to start numb
- What is meant by "constructed as normal"?
- With the `&&` in the syntax, `<symbol>` does not always have to be the second parameter?
```suggestion
Use the `pad` descriptor when you need the marker representations to be of a minimum length. If a marker representation is shorter than the specified pad length, then the marker representation will be padded with the specified padding symbol. Marker representations longer than the pad length are displayed without any additional padding.

The `pad` descriptor takes an `<integer>` for the minimum marker length and a `<symbol>` for the padding. A common use case of the `pad` descriptor is when you need a list to start numbering from `01` and go through `02`, `03`, `04`, and so on, instead of just `1`, `2`, `3`, and `4`. By specifying the `pad` descriptor as `pad: 2 "0"` in this case, the browser ensures to make the counter at least two characters long and adds a padding with `0` to reach the minimum two-character length where needed. Counters that are already two or more characters long in this example will be displayed normally, without padding.
```

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +This example extends the `decimal` {{cssxref("@counter-style/system","system")}}, to create a counter that is at least three characters long, padding shorter numbers with `0` until that minimum lengt
```suggestion
This example extends the `decimal` {{cssxref("@counter-style/system","system")}} to create a counter that is at least three characters long, padding shorter counters with `0` to reach that minimum length. A {{cssxref("@counter-style/suffix", "suffix")}} descriptor has been added to make the output more legible.
```

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +  pad: 3 "0";
How about we demo that the order does not matter
```suggestion
  pad: "0" 3;
```

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +  <li>etc.</li>
```suggestion
  <li>and so on</li>
```

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +- {{cssxref("symbol")}}
Is there going to be a new page for this data type?

2023-10-26 00:10 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
>  - {{cssxref("symbols", "symbols()")}}, the functional notation creating anonymous counter styles.
```suggestion
- {{cssxref("@counter-style")}} descriptors: {{cssxref("@counter-style/system","system")}}, {{cssxref("@counter-style/symbols", "symbols")}}, {{cssxref("@counter-style/additive-symbols", "additive-symbols")}}, {{cssxref("@counter-style/negative", "negative")}}, {{cssxref("@counter-style/prefix", "prefix")}}, {{cssxref("@counter-style/suffix", "suffix")}}, {{cssxref("@counter-style/range", "range")}}, {{cssxref("@counter-style/speak-as", "speak-as")}}, {{cssxref("@counter-style/fallback", "fallback")}}
- List style properties: {{Cssxref("list-style")}}, {{Cssxref("list-style-image")}}, {{Cssxref("list-style-position")}}
- {{cssxref("symbols", "symbols()")}} function to create anonymous counter styles
- [CSS counter styles](/en-US/docs/Web/CSS/CSS_counter_styles) module
```

2023-10-26 17:43 UTC, estelle commented on files/en-us/web/css/@counter-style/pad/index.md
> +  pad: 3 "0";
prefer to do that in text, rather than via example. Will add that.

2023-10-26 17:45 UTC, estelle commented on files/en-us/web/css/@counter-style/pad/index.md
> +- {{cssxref("symbol")}}
```suggestion
- [`<symbol>`](/en-US/docs/Web/CSS/@counter-style/symbols#symbol)
```

2023-10-26 17:51 UTC, estelle commented on files/en-us/web/css/@counter-style/pad/index.md
> +- {{cssxref("symbol")}}
The PR landed. Changed the value to where it is defined.

2023-10-26 17:52 UTC, estelle commented
@dipikabh Thanks for the review. Suggested edits are committed, I update the syntax with a reverse order, and the link to symbol now works (the description of symbol was merged earlier this week)

2023-10-27 03:12 UTC, dipikabh commented on files/en-us/web/css/@counter-style/pad/index.md
> +- {{cssxref("symbol")}}
Cool, thanks!

2023-10-27 03:14 UTC, dipikabh approved these changes
Thanks a lot for all the effort, @estelle. Great work 🙌

2023-10-27 03:14 UTC, merged