fix(css): enhance container-type property page
mdn/content pull request #29852
Opened 2023-10-27 13:54 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/29748

The PR
- adds more info about size containments in values section
- adds more details from the StackOverflow answer
- makes example complete and interactive

2023-10-31 09:01 UTC, chrisdavidmills requested changes
@OnkarRuikar great work here, thanks! I have left a few comments for you to consider.

2023-10-31 09:01 UTC, chrisdavidmills commented on files/en-us/web/css/container-type/index.md
> +{{EmbedLiveSample('Establishing_inline_size_containment', '100%', 300)}}
Nice work: the demo is instructive and easy to understand.

2023-11-01 03:47 UTC, OnkarRuikar commented on files/en-us/web/css/container-type/index.md
>    - : Establishes a query container for container size queries on both the inline and block axis in both the [inline and block](/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Basic_concepts_of
```suggestion
  - : Establishes a query container for container size queries in both the [inline and block](/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Basic_concepts_of_logical_properties_and_values#block_and_inline_dimensions) dimensions.
```

2023-11-01 03:49 UTC, OnkarRuikar commented on files/en-us/web/css/container-type/index.md
>    - : Establishes a query container for container size queries on both the inline and block axis in both the [inline and block](/en-US/docs/Web/CSS/CSS_logical_properties_and_values/Basic_concepts_of
done in [this](https://github.com/mdn/content/pull/29852/commits/37327c848608294b68a3731e24b866c3ca9c9774) commit.

2023-11-01 15:49 UTC, chrisdavidmills approved these changes
LGTM; thanks @OnkarRuikar !

2023-11-01 15:50 UTC, merged