feat: Editorial review: Add content for overlay and discrete animation features
mdn/content pull request #29943
Opened 2023-10-31 17:07 UTC by chrisdavidmills

### Description

This PR is for the editorial review of https://github.com/mdn/content/pull/29049, which was kindly tech-reviewed by @josepharhar

---

### Description

This PR adds content for multiple related features that go together to enable the creation of exit/entrance animations using simple CSS, or to put it another way, animating to/from `display: none` (this includes top layer elements like popovers), or animating elements when they have just been added to the DOM.

Specifically, these are:

- [`@starting-style`](https://chromestatus.com/feature/4515377717968896): Chrome 117
- [The `overlay` property](https://chromestatus.com/feature/5138724910792704): Chrome 117
- [Animating to/from `display: none` and `content-visibility: hidden`](https://chromestatus.com/feature/5154958272364544): Chrome 116
- [The `transition-behavior` property](https://chromestatus.com/feature/5071230636392448): Chrome 117

### Motivation

### Additional details

### Related issues and pull requests

2023-11-01 06:08 UTC, OnkarRuikar commented on files/en-us/web/css/content-visibility/index.md
> +### content-visibility animation example
This example doesn't demonstrate `transition-behavior: allow-discrete;`. The same code works in Firefox where `allow-discrete` hasn't been implemented.

For example refer https://codepen.io/web-dot-dev/pen/poQMLrN.  If you run the code pen example in both Chrome and Firefox you'll notice the difference.
I think explicitly toggling `content-visiblity` and `display` properties in keyframes is a workaround and doesn't demonstrate new `allow-discrete` feature.

2023-11-01 13:50 UTC, dipikabh commented
Hi @chrisdavidmills, I can take a look at this for an edit review.

2023-11-01 14:09 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}}. Therefore, for popovers to be animated `disp
I've added a note to make it clear that `transition-behavior: allow-discrete` is required for transitions (but not animations), both here and in the `<dialog>` element page:

> **Note:** When animating using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions), `transition-behavior: allow-discrete` needs to be set to enabled the above behavior. When animating with [CSS animations](/en-US/docs/Web/CSS/CSS_animations) the above behavior is available by default; an equivalent step is not required.

2023-11-01 14:49 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- You can't set `overlay` inside keyframes either. The best solution we found at this time to defer removal from the top layer was to use JavaScript — add/remove classes to animate the popover as req
Thanks so much for your help here @OnkarRuikar. It was a while ago, and I don't remember how I arrived at such a convoluted solution. But yes, you are right. This is much simpler. On the subject of the `::backdrop` animation, I think I was reluctant to include it because at the moment you can only animate it when opening, and not when closing. But on open is better than nothing.

In my next commit, I have updated this example to include the changes proposed here, as well as the backdrop opening animation. I've changed the surrounding text to suit. I've done this for the `<dialog>` keyframe animation too.

2023-11-01 14:52 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- _rules_
Good catch, thanks; updated.

2023-11-01 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +### content-visibility animation example
Correct - you don't explicitly enable discrete animations for keyframe animations; that's only needed for transitions. I can't remember the exact reason, but I think it has something to do with avoiding unintended side effects if discrete property transitions were just enabled all the time. We probably ought to explain why this is needed on the `transition-behavior` reference page.

@josepharhar, have I got this right?

2023-11-01 15:02 UTC, chrisdavidmills commented
> Hi @chrisdavidmills, I can take a look at this for an edit review.

@dipikabh that would be super awesome; thanks!

2023-11-01 16:18 UTC, OnkarRuikar commented on files/en-us/web/api/popover_api/using/index.md
> +- You can't set `overlay` inside keyframes either. The best solution we found at this time to defer removal from the top layer was to use JavaScript — add/remove classes to animate the popover as req
> at the moment you can only animate it when opening, and not when closing. But on open is better than nothing.

It is because the backdrop is immediately removed from the DOM so there nothing to animate after closing.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +- [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set on the `display` and `overlay` transitions. This effectively enables discrete transitions.
```suggestion
- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) at-rule
  - : Provide the set of starting values for properties set on the popover that you want to transition from when it is shown. By default, CSS transitions only occur when a property changes on a visible iterm from one value to another. They are not triggered on an element's first style, when `display` changes from `none` to a visible value. Setting the starting values with `@start-style` provides initial values to transition from when the element receives its first style update, thereby avoiding unexpected behavior.
- [`display`](/en-US/docs/Web/CSS/display) property
  - : Add `display` to the transitions list so that the popover will remain as `display: block` for the duration of the transition, ensuring the other transitions are visible.
- [`overlay`](/en-US/docs/Web/CSS/overlay) property
  - : Include `overlay` in the transitions list to ensure the removal of the popover from the top layer is deferred until the transition completes, again ensuring the transition is visible.
- {{cssxref("transition-behavior")}} property
  - : Set `transition-behavior: allow-discrete` on the `display` and `overlay` transitions to enable discrete transitions on these two properties that are not by default animatable.
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +The HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:
```suggestion
The HTML contains a {{htmlelement("div")}} element declared to be a popover via the global [`popover`](/en-US/docs/Web/HTML/Global_attributes/popover) HTML attribute. A {{htmlelement("button")}} element designated as the popover's toggle control:
```
as we use the popover attribute as the selector, want to highlight the attribute's existence again since we are so far from the initial inclusion in the document itself.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +}
can we just say `transition: 0.7s allow-discrete;` default to `all`? We should mention in the content if so or if not.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  background-color: rgba(0, 0, 0, 0);
```suggestion
  background-color: rgba(0 0 0 / 0);
```

`rgba()` is legacy. Use `rgb()` instead.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +    background-color: rgba(0, 0, 0, 0);
```suggestion
    background-color: rgb(0 0 0 / 0);
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  background-color: rgba(0, 0, 0, 0.25);
```suggestion
  background-color: rgb(0 0 0 / 0.25);
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to show animations for are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) — specifically, a horizontally scaling transfor
```suggestion
The two popover properties we want to transition in and out are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) — specifically, a horizontally scaling transform. We want the popover to fade in or out while growing or shrinking horizontally. To achieve this, we set a starting state for these properties on the default hidden state of the popover element (selected with the `[popover]` [attribute selector](/en-US/docs/Web/CSS/Attribute_selectors)) and an end state for the open state of the popover (selected via the [`:popover-open`](/en-US/docs/Web/CSS/:popover-open) pseudo-class). We also set the [`transition`](/en-US/docs/Web/CSS/transition) to set the properties to animate and the duration of the animation as the property values change when the popover gets displayed or hidden.
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +- Added `overlay` to the list of transitioned elements to make sure that the removal of the element from the top layer is deferred until the animation has been completed. This doesn't make a huge dif
```suggestion
- Added `overlay` to the list of transitioned elements to make sure that the removal of the element from the top layer is deferred until the animation has been completed. The effect of this may not be noticeable for basic animations such as this one, but in more complex cases, omitting this property can result in the element being removed from the overlay before the transition completes.
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +- Set `allow-discrete` on both the above transitions to enable discrete transitions.
```suggestion
- Set `allow-discrete` on both the above transitions to enable [discrete transitions](/en-US/docs/Web/CSS/CSS_animated_properties#discrete).
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +You'll note that we've also included a transition on the [`::backdrop`](/en-US/docs/Web/CSS/::backdrop) that appears behind the popover when it opens, to provide a nice darkening animation. `[popover
```suggestion
You'll note that we've also included a transition on the [`::backdrop`](/en-US/docs/Web/CSS/::backdrop) appearing behind the popover when it opens, providing a nice darkening animation.
```
I removed:

>The `[popover]:popover-open::backdrop` selector matches the backdrop pseudo-element when the popover is open.

as `::backdrop` matches the element too and we don't need to style some backdrops differently from others. that would be less than optimal UX, so we might not want to promote the idea.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +- You can't set `overlay` inside keyframes either, but we found we could get the animation example working OK by setting the animations as appropriate on the shown and closed states of the popover vi
```suggestion
- Don't include a `@starting-style` block. Instead, provide the starting values, including the initial `display` value, in the starting keyframe (Using the `0%` or `from` keyframes in the name [`@keyframes`](/en-US/docs/Web/CSS/@keyframes) animation definition.
- Discrete transitions are not enabled; there is no equivalent to `allow-discrete` inside keyframes.
- Exclude the `overlay` for the `@keyframes` block. In keyframe animations, the `display` value is not animated. Rather, the values of properties that are not animatable change to the value declared in the keyframe when encountered. This means the display value changes in the same keyframe as the animation completion, so `overlay` has no effect.
```

I don't know who we is or what "we found we could get the animation example working OK by setting the animations as appropriate on the shown and closed states of the popover via CSS." meant, so i added the likely CSS reason for your results in instead.

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +Let's look at an example. The HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:
```suggestion
### Example

In this example, the HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:

#### HTML
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +The CSS is as follows:
```suggestion
#### CSS
```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +
```suggestion
#### Result

```

2023-11-01 20:47 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  }
```suggestion
  0% {
    background-color: rgb(0 0 0 / 0);
  }

  100% {
    background-color: rgb(0 0 0 / 0.25);
  }
```

2023-11-01 21:07 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +This enables the easy creation of entry animations that were previously complex to achieve, such as animating elements when they are changed from `display: none` (this includes elements shown in the
```suggestion
This enables the creation of entry animations, such as the display of [popovers](/en-US/docs/Web/API/Popover_API) and modal {{htmlelement("dialog")}} elements, both displayed in the [top layer](/en-US/docs/Glossary/Top_layer), and other elements that are chang from `display: none` to being visible, including when an element is first added to the DOM.
```

2023-11-01 21:07 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** `@starting-style` is only relevant to CSS transitions. When animating from `display: none` or animating elements as they are first added to the DOM, [CSS animations](/en-US/docs/Web/CSS/C
```suggestion
> **Note:** `@starting-style` is only relevant to CSS transitions. When using [CSS animations](/en-US/docs/Web/CSS/CSS_animations) to animate elements from `display: none` or as they are added to the DOM,  `@starting-style` is not needed; instead, provide the starting style as an explicit starting keyframe (for example using `0%` or `from`). See [Using CSS animations](/en-US/docs/Web/CSS/CSS_animations/Using_CSS_animations) for an example.
```
link to a specific example (with #) in the Using_CSS_animations page

2023-11-01 22:17 UTC, dipikabh requested changes
@chrisdavidmills, I completed a read through of the "@starting-style" page. Sending some suggestions your way. Interesting CSS feature!

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +   to take effect, as the specificity is the same */
```suggestion
/* Include after the `div` rule */
```

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +We want to transition [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) on each `<div>` as it is added to the DOM, and then reverse the animation as it is remo
```suggestion
To animate [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) on each `<div>` as it is added to the DOM and then reverse the animation as it is removed from the DOM, we:
```

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to get `opacity`, `transform`, and `display` animating. Note that in the case of `display`, [`transition-b
```suggestion
- Specify the ending state of the properties we want to transition in the `div { ... }` rule.
- Specify the starting state from which to transition the properties within a `@starting-style` block.
- Specify the exit animation inside the `.fade-out` rule — this is the class that the JavaScript code assigns to the `<div>` elements when their close buttons are pressed. Besides setting the `opacity` and `transform` ending states, we also set [`display: none`](/en-US/docs/Web/CSS/display) on the `<div>`s; we want them to become immediately unavailable when removed from the UI.
- Specify the [`transition`](/en-US/docs/Web/CSS/transition) list within the `div { ... }` rule to animate `opacity`, `transform`, and `display`. Note that for `display`, [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) value is also set in the shorthand so that it will animate.
```

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +The final result looks like this:
or we can say how the readers can interact with the result frame and what they can expect

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +{{ EmbedLiveSample("Transitioning elements as they are added to and removed from the DOM", "100%", "400") }}
might need an update based on the title change

2023-11-01 22:17 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +- {{domxref("CSSStartingStyleRule")}}
We can move the domxref link before the external link

2023-11-01 22:38 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +### content-visibility animation example
My guess (without looking at the spec, which is ever so useful) is that animations already handle discrete animations: if you put `40% {display: table-cell;}` it will change to table cell when it reaches the 40% mark, and stay that way as long as the animation is applied and a different value is not set.

2023-11-02 09:47 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- You can't set `overlay` inside keyframes either. The best solution we found at this time to defer removal from the top layer was to use JavaScript — add/remove classes to animate the popover as req
Yup. I've added some extra wording to the example explanations to explain why.

2023-11-02 10:02 UTC, chrisdavidmills commented on files/en-us/web/api/cssstartingstylerule/index.md
> +- [Using dynamic styling information](/en-US/docs/Web/API/CSS_Object_Model/Using_dynamic_styling_information)
Agreed; I've added links to appropriate pages in my next commit.

2023-11-02 10:13 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}}. Therefore, for popovers to be animated `disp
There were some details I liked here, so I've added some of them, here and to the similar paragraph in the `<dialog>` element page. However, I've not made some of the changes, because they contain details specific to transitions or keyframe animations, and it starts to sound like the two are conflated. This paragraph is trying to be neutral and talk about animations in general, as the behavior change applies to both. The two further down discussed the specifics of keyframe animations and transitions.

2023-11-02 10:14 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}}. Therefore, for popovers to be animated `disp
I also think the example given is easier to read when not in the large paragraph format, so I've not made that change.

2023-11-02 10:14 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- When animating between `display` `block` and `none`, the value will flip to `none` at `100%` of the animation duration so it is visible throughout.
See above comment.

2023-11-02 10:16 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +> **Note:** When animating using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions), `transition-behavior: allow-discrete` needs to be set to enabled the above behavior. When animating with [CSS
Changes made. It does make sense to link it in both places.

2023-11-02 10:17 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +When animating popovers with transitions, the following are required:
Updated

2023-11-02 10:30 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set on the `display` and `overlay` transitions. This effectively enables discrete transitions.
Mostly good; I've made a few tweaks to fix a few small issues (like the default is what avoids unexpected behavior, not setting `@starting-style` rules; that overrides the default when you need to.)

2023-11-02 11:41 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +The HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:
Yup, good call. Changed.

2023-11-02 12:08 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +}
Ah, this is a really good point. I've added comments of the following kind to allow appropriate examples across the PR:

```css
/* Equivalent to  
    all 0.7s allow-discrete */
```

I've tested it, and it does work.

2023-11-02 12:19 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  background-color: rgba(0, 0, 0, 0);
Ack, dammnit. I have changed them all to the `rgb(0 0 0 / 0)` form.

2023-11-02 12:19 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    background-color: rgba(0, 0, 0, 0);
changed

2023-11-02 12:19 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  background-color: rgba(0, 0, 0, 0.25);
changed

2023-11-02 12:24 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to show animations for are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) — specifically, a horizontally scaling transfor
mostly good; I've used it and made a few tweaks.

2023-11-02 12:25 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Set `allow-discrete` on both the above transitions to enable discrete transitions.
updated

2023-11-02 12:26 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Added `overlay` to the list of transitioned elements to make sure that the removal of the element from the top layer is deferred until the animation has been completed. This doesn't make a huge dif
Updated

2023-11-02 12:27 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +You'll note that we've also included a transition on the [`::backdrop`](/en-US/docs/Web/CSS/::backdrop) that appears behind the popover when it opens, to provide a nice darkening animation. `[popover
ok, updated

2023-11-02 12:38 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- You can't set `overlay` inside keyframes either, but we found we could get the animation example working OK by setting the animations as appropriate on the shown and closed states of the popover vi
Yup, I'm totally aware that my previous text was crap and wishy-washy, and I do appreciate the help in trying to improve it ;-) But, I found your explanation confusing; it didn't make sense to me. `display` _is_ animated. And I got totally lost on the meaning of the second bit.  In the end, I used some of your suggestions, and arrived at the following second attempt:

---

- You don't provide a `@starting-style`; instead, you provide the starting values (including the initial `display` value) in an explicit starting keyframe (using `0%` or `from`).
- You don't need to explicitly enable discrete animations; there is no equivalent to `allow-discrete` inside keyframes.
- You don't need to set `overlay` inside keyframes either; the `display` animation handles the animation of the popover from shown to hidden.

2023-11-02 12:43 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Let's look at an example. The HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:
Yup, good call, helps to break it up a bit. I've added these subheadings as appropriate in the Popover and `<dialog>` element docs.

2023-11-02 13:01 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +The CSS is as follows:
OK, I've added these subsections to all of the pages. And I think they are easier to read as a result. I'll do this in all future example sections.

2023-11-02 13:01 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Let's look at an example. The HTML contains a {{htmlelement("div")}} element declared as a popover, and a {{htmlelement("button")}} element designated as the popover's toggle control:
oop, scratch that. I've removed them again, and instead added individual HTML/CSS/JavaScript/Result headings.

2023-11-02 13:01 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +
added

2023-11-02 13:01 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  }
changed

2023-11-02 13:02 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +We have defined keyframes that specify the desired entry and exit animations, and an entry animation for the backdrop only. Note that it wasn't possible to reproduce a keyframe animation for the back
done

2023-11-02 13:03 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The **`@starting-style`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to provide a set of starting values for properties set on an element that you want to transition fr
Good call; added.

2023-11-02 13:21 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This is needed because, by default, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are not triggered on elements' first style updates, or when the [`display`](/en-US/docs/Web/CSS/display) typ
I've used some of this. I thought my first sentence was ok as-is, but your second half provides some nice explanations.

2023-11-02 13:29 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This enables the easy creation of entry animations that were previously complex to achieve, such as animating elements when they are changed from `display: none` (this includes elements shown in the
Good ideas here; I tweaked it a bit, but mostly used it.

2023-11-02 13:34 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** `@starting-style` is only relevant to CSS transitions. When animating from `display: none` or animating elements as they are first added to the DOM, [CSS animations](/en-US/docs/Web/CSS/C
Good call; suggestion used, and specific URL to keyframe animation example inserted. Thanks for your review so far!

2023-11-02 13:36 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The **`@starting-style`** [CSS](/en-US/docs/Web/CSS) [at-rule](/en-US/docs/Web/CSS/At-rule) is used to provide a set of starting values for properties set on an element that you want to transition fr
I've used some of these suggestions and reduced some verbiage, but I feel that sentence needs to be whole, to get the meaning across properly.

2023-11-02 13:39 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This is needed because, by default, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are not triggered on elements' first style updates, or when the [`display`](/en-US/docs/Web/CSS/display) typ
Some suggestions used here, and also some suggestions from Etelle's review.

2023-11-02 13:43 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This enables the easy creation of entry animations that were previously complex to achieve, such as animating elements when they are changed from `display: none` (this includes elements shown in the
I love this idea. I've simply moved the follow-on paragraphs to the Description section. I think it works pretty well like this.

2023-11-02 13:45 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** `@starting-style` is only relevant to CSS transitions. When animating from `display: none` or animating elements as they are first added to the DOM, [CSS animations](/en-US/docs/Web/CSS/C
I've improved this in a slightly different way.

2023-11-02 13:48 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +  - : Is the set of CSS declarations providing the starting styles for the transition, when `@starting-style` is nested inside a particular ruleset.
This is certainly a lot shorter. Thanks for the suggestion; updated!

2023-11-02 13:51 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +There are two ways to use `@starting-style`. Let's consider an example where we want to animate a popover when it is shown (added to the top layer). In this case, the original rule specifying the sty
updated

2023-11-02 13:52 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +You can specify the starting styles in a separate rule contained within a standalone `@starting-style` block:
updated

2023-11-02 13:55 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** In the standalone case, you need to specify the `@starting-style` block after the original rule for it to take effect, as the specificity of each is the same. If `@starting-style` was spe
updated

2023-11-02 13:58 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +Alternatively, you can nest the starting styles inside the original rule:
updated

2023-11-02 13:59 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +{{csssyntax}}
The data was added and merged - see https://github.com/mdn/data/pull/688. So it should be displaying. I think we should leave it there for now.

2023-11-02 14:00 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The HTML contains a {{htmlelement("div")}} element declared as a popover using the [popover](/en-US/docs/Web/HTML/Global_attributes/popover) attribute, and a {{htmlelement("button")}} element designa
Updated

2023-11-02 14:01 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This example shows how a [popover](/en-US/docs/Web/API/Popover_API) can be animated using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions). Basic entry and exit animations are provided.
updated

2023-11-02 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +```
updated

2023-11-02 14:08 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The CSS for the example looks like this:
I usually do, but in this case, there is a lot of explanation. You generally need to be able to see the code for the explanation to be helpful; in cases where the explanation is large, I think it is more useful to look at the code first.

2023-11-02 14:09 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The two properties we want to animate are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) (specifically, a horizontally scaling transform): we want the popov
updated

2023-11-02 14:10 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +We then set a [`transition`](/en-US/docs/Web/CSS/transition) property to animate between the two, and include a starting state for the animation inside a [`@starting-style`](/en-US/docs/Web/CSS/@star
updated

2023-11-02 14:11 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden — which also means that its hidden sta
updated

2023-11-02 14:12 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +You'll note that we've also included a transition on the [`::backdrop`](/en-US/docs/Web/CSS/::backdrop) that appears behind the popover when it opens, to provide a nice darkening animation. `[popover
Nah, I've put it in a note block instead. But I have updated the wording as per your suggestions.

2023-11-02 14:14 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- [`overlay`](/en-US/docs/Web/CSS/overlay) is added to the list of transitioned elements to make sure that the removal of the element from the top layer is deferred until the animation has been compl
I've used a bunch of these suggestions.

2023-11-02 14:17 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The code renders as follows:
I don't think this is necessary. There is an explanation above to say what it does, and it is a button. It's pretty obvious that you've got to press it. And also, you don't need to reload the page to revert the state; it is a toggle button.

2023-11-02 14:17 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +### Transitioning elements as they are added to and removed from the DOM
Yup, shorter is better; updated

2023-11-02 14:18 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +In this example, we provide a button that appends new elements to a {{htmlelement("section")}} container when pressed. Each element is given a nested close button which, when pressed, removes the ele
Updated.

2023-11-02 14:21 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The JavaScript that handles the adding and removing looks like this:
updated

2023-11-02 14:23 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Use {{domxref("setTimeout")}} to delay the removal of the `<div>` from the DOM (via {{domxref("Element.remove()")}}) until after the animation has finished.
I'd prefer to keep it here, for he same reasons as discussed earlier.

2023-11-02 14:23 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +   to take effect, as the specificity is the same */
updated

2023-11-02 14:24 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +We want to transition [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) on each `<div>` as it is added to the DOM, and then reverse the animation as it is remo
Updated

2023-11-02 14:27 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to get `opacity`, `transform`, and `display` animating. Note that in the case of `display`, [`transition-b
Mostly applied

2023-11-02 14:29 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The final result looks like this:
I'm not sure what the above change is suggesting; it seems to be undoing some of your previous suggestions.

2023-11-02 14:30 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +{{ EmbedLiveSample("Transitioning elements as they are added to and removed from the DOM", "100%", "400") }}
Sure does; thank you m'aam.

2023-11-02 14:31 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- {{domxref("CSSStartingStyleRule")}}
ok, done!

2023-11-03 15:52 UTC, estelle reviewed
This is a review of "Using popover API"  (/en-us/web/api/popover_api/using)  and CSSStartingStyleRule (Web/API/CSSStartingStyleRule) pages. Just a few tweaks. Looks good and "approved".

As we're multiple reviewers coming back multiple times, I'll review and comment on each page when reviewed so we don't duplicate efforts and so i don't forget what I've done ;)

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/cssstartingstylerule/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
```suggestion
- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) module
```

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/
```suggestion
Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/Performance/How_browsers_work#building_the_accessibility_tree). Therefore, for popovers to be animated the {{cssxref("display")}} property needs to be animatable. [Supporting browsers](/en-US/docs/Web/CSS/display#browser_compatibility) animate `display` with a variation on the [discrete animation type](/en-US/docs/Web/CSS/CSS_animated_properties#discrete). Specifically, the browser will flip between `none` and another value of `display` so that the animated content is shown for `100%` of the animation duration. So, for example:
```
Prefer omitting "this is new" lingo as this will otherwise not be removed for likely 10 years (ie, i am spending this week removing "when flex is supported" weaved throughout the cookbook)

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Provides a set of starting values for properties set on the popover that you want to transition from when it is first shown. This is needed because, by default, CSS transitions only occur when
```suggestion
  - : Provides a set of starting values for properties set on the popover that you want to transition from when it is first shown. This is needed, to avoid unexpected behavior because, by default, CSS transitions only occur when a property changes from one value to another on a visible element; they are not triggered on elements' first style updates, or when the `display` type changes from `none` to another type.
```

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Set `transition-behavior: allow-discrete` on the `display` and `overlay` transitions to enable discrete transitions on these two properties that are not by default animatable.
```suggestion
  - : Set `transition-behavior: allow-discrete` on the `display` and `overlay` transitions (or on the {{cssxref("transition")}} shorthand) to enable discrete transitions on these two properties that are not by default animatable.
```

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +because the nesting selector cannot represent pseudo-elements. */
```suggestion
because the nesting selector (`&`) cannot represent pseudo-elements. */
```
so few people know what the nesting selector is we should likely show it

2023-11-03 15:52 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or
```suggestion
The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or shrinking horizontally. To achieve this, we set a starting state for these properties on the hidden state of the popover element (selected with the `[popover]` [attribute selector](/en-US/docs/Web/CSS/Attribute_selectors)) and an end state for the shown state of the popover (selected via the [`:popover-open`](/en-US/docs/Web/CSS/:popover-open) pseudo-class). We also set the [`transition`](/en-US/docs/Web/CSS/transition) property to define the properties to animate with an animation duration as the popover gets shown or hidden.
```
First edit: while it is the default state, people may be confused that it's only the original state we're talking about, not a 'back to hidden' state.
Last edit: or `and the animation's duration`.

2023-11-03 17:43 UTC, estelle reviewed
partially thru this page

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +    all 0.7s allow-discrete */
```suggestion
    transition: all 0.7s allow-discrete; */
```

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the el
```suggestion
This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the element. This example demonstrates how to use transitions to animate elements when they are added or removed from the DOM.
```

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +The static HTML looks like this:
in the css section of MDN, we include the headers and only include text before the code blocks if there is something to point out in the code blocks. otherwise, it's just the HTML, CSS, JS, and Result headers.

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +The JavaScript code that handles the addition and removal of the elements looks like this:
```suggestion
JavaScript enables the addition and removal of elements.
```

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +}
```suggestion
function randomColor() {
  function hexVal() {
    return Math.floor(Math.random() * 255);
  }

  return `rgb(${hexVal()} ${hexVal()} ${hexVal()})`;
}
```
or other shorter variable name so the code can appear on one line.
removed commas and put in spaces in the RGB() value

2023-11-03 17:43 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +    divElem.classList.add("fade-out");
do we need a class name? aren't we targeting all behaviors based on them being added or removed?

2023-11-03 23:51 UTC, estelle reviewed
Finished reviewing `@starting-style`. Moving on to the next pages.

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +Let's move on to the CSS:
```suggestion
The parts of the CSS relevant to this example include:
```
Then hide all the fonts, border, padding, etc.

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +  transform: scaleY(1);
```suggestion
 scaleY: 1 1;
```

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +    transform 0.7s,
```suggestion
    scale 0.7s,
```

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +    transform: scaleY(0);
```suggestion
    scale: 1 0;
```

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +  transform: scaleY(0);
```suggestion
  scale: 1 0;
```

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +To animate [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) on each `<div>` as it is added to the DOM and then reverse the animation as it is removed from the
```suggestion
To animate the [`opacity`](/en-US/docs/Web/CSS/opacity) and [`scale`](/en-US/docs/Web/CSS/scale) of each `<div>` as it is added to the DOM and then reverse the animation as it is removed from the DOM, we:
```
changed the above transforms to scale just so i could change this sentence; to dually use the properties also as adjectives

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the exit animation inside the `.fade-out` rule — this is the class that the JavaScript assigns to the `<div>` elements when their close buttons are pressed. Besides setting the `opacity` an
```suggestion
- Specify the exit animation inside the `.fade-out` rule — this is the class that the JavaScript assigns to the `<div>` elements when their close buttons are pressed. Besides setting the `opacity` and `scale` ending states, we also set [`display: none`](/en-US/docs/Web/CSS/display) on the `<div>`s — we want them to become immediately unavailable when removed from the UI.
```
is "we want them to become immediately unavailable when removed from the UI" a preference or a requirement?

2023-11-03 23:51 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to animate `opacity`, `transform`, and `display`. Note that for `display`, the [`transition-behavior: allo
```suggestion
- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to animate `opacity`, `scale`, and `display`. Note that for `display`, the [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) value is also set in the shorthand so that it will animate.
```

2023-11-04 00:18 UTC, estelle reviewed
Ending my first review of `content-visibility` before finishing the review. 

I would like to the new content moved to after the animation example. The ability to transition the property should be treated more like a caveat on this page. The way it presented conflates animation and transitions. As `allow-discrete` is not needed for animations; explaining how it can be animated with keyframe animation and then providing the `allow-discrete` caveat for transitions re-centers this page back onto content-visibility.

2023-11-04 00:18 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +This behavior is useful for creating entry/exit animations where you want to for example remove some content from the UI immediately with `content-visibility: hidden`, but have it animate (for exampl
```suggestion
This behavior is useful for creating entry/exit animations where you want to, for example, remove some content from the UI with `content-visibility: hidden`, but you want a smooth transition, such as a fade-out, rather than it disappearing immediately.
```
Does the element get removed from the DOM at the start or end of the transition? My remove of "remove some content from the UI immediately" has to do with my assumption that if you have a 40s delay on your transition, it's going to still be in the dom?

2023-11-04 00:30 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +The code renders as follows:
Okay

2023-11-04 00:40 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to get `opacity`, `transform`, and `display` animating. Note that in the case of `display`, [`transition-b
- `@starting-state` should be `@starting-style`?
- [`transition`](/en-US/docs/Web/CSS/transition) - this is linked to the display property page?

2023-11-04 00:46 UTC, dipikabh commented on files/en-us/web/css/@starting-style/index.md
> +The final result looks like this:
This is similar to my comment in the previous example near the "Result" frame about explicitly saying "Click the ... button" in the Result frame.

2023-11-04 00:55 UTC, dipikabh commented
Hi @chrisdavidmills, thanks for considering the suggestions and leaving your responses!
You might want to take a look at this https://github.com/mdn/content/pull/29943#discussion_r1382302542.

I came to resume reviewing the remaining files but the PR seems to be in good hands with Estelle taking a look. I'll step back and allow Estelle to continue with the review. Feel free to reach out if you need any help or a second pair of eyes on this.

2023-11-04 05:40 UTC, estelle reviewed
Review of using_css_animations.
I suggested a different example, one that shows that the display value is being set by the animation (not the default display value) and doesn't use JS.

2023-11-04 05:40 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +- When animating between `display` `none` and `block`, the value will flip to `block` at `0%` of the animation duration so it is visible throughout.
```suggestion
Not all properties are animatable. According to the specifications, [`display`](/en-US/docs/Web/CSS/display) and [`content-visibility`](/en-US/docs/Web/CSS/content-visibility) properties are two of these. When non-animatable properties are included in a keyframe, they are generally ignored. These two properties are an exception; they support a [discrete animation type](/en-US/docs/Web/CSS/CSS_animated_properties#discrete). 

Generally, in discrete animations, the animating property will flip between two values at the midpoint between the two keyframes setting values for that discretely animated property. These two values are an exception. When animating to or from `display: none` and to or from `content-visibility: hidden`, the browser will change to the visible value immediately at the start of the animation so that the animated content is shown for the entirety of the animation's duration.

This means, when animating an element between `display` `none` and `block` (or any other visible value), the value will flip to the visible value immediately after the expiration of the `animation-delay`, at the start of the animation duration, , when the `animationStart` event occurs, so it is visible throughout, whether the visible display value is at the `0%`, `100%`, or `27.5%` keyframe.
```

2023-11-04 05:40 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +- When animating between `display` `block` and `none`, the value will flip to `none` at `100%` of the animation duration so it is visible throughout.
```suggestion
Similarly, when animating between `display: block` (or any other visible display value) and `display: none`, the value will wait until the animation ends, staying visible through all the animation interactions if there is more than one, and only flipping to `none` when the `animationEnd` event occurs, so it is visible throughout.
```
I did not test this.

2023-11-04 05:40 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +- When animating between `display` `none` and `block`, the value will flip to `block` at `0%` of the animation duration so it is visible throughout.
what happens if animation-fill-mode is set?

2023-11-04 05:40 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +    display: block;
This does not show that its working since non-supporting browsers just ignore the display rules. How about this example: https://codepen.io/estelle/pen/JjxbbJL - it switched to inline when animating

2023-11-04 05:40 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +    display: block;
The codepen example doesn't have any JS, which i prefer for CSS explanations.

2023-11-05 12:07 UTC, OnkarRuikar commented on files/en-us/web/css/@starting-style/index.md
> +  transform: scaleY(1);
```suggestion
  scale: 1 1;
```

2023-11-05 13:05 UTC, OnkarRuikar commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +    display: block;
@estelle in your codepen demo I think `div:hover { }` should be `div:hover span {}`. Otherwise the blinking div is very annoying.

2023-11-05 13:52 UTC, OnkarRuikar commented on files/en-us/web/css/content-visibility/index.md
> +{{ EmbedLiveSample("content-visibility animation example", "100%", "250") }}
```suggestion
{{ EmbedLiveSample("content-visibility animation example", "100%", "350") }}
```

2023-11-05 14:01 UTC, OnkarRuikar commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +  }
```suggestion
  divElem.classList.toggle("showing");
```

2023-11-05 15:00 UTC, OnkarRuikar commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
Technically in this case we don't need `animation-fill-mode` `forward` or `both` (on line 450 and 454) because animation end states are same as opened or hidden popover. So we don't need to use `display` in keyframes.
Following code also works:
```css
@keyframes fade-in {
  0% {
    opacity: 0;
    transform: scaleX(0);
  }

  100% {
    opacity: 1;
    transform: scaleX(1);
  }
}

@keyframes fade-out {
  0% {
    opacity: 1;
    transform: scaleX(1);
    /* we do need this one cos it holds the popover visible till animation ends :) */
    display: block;
  }

  100% {
    opacity: 0;
    transform: scaleX(0);
  }
}
```

2023-11-06 10:46 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to get `opacity`, `transform`, and `display` animating. Note that in the case of `display`, [`transition-b
Heh, thank you for spotting those. Fixed now!

2023-11-06 10:47 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The final result looks like this:
Ah, OK. I think this is OK as-is.

2023-11-06 10:50 UTC, chrisdavidmills commented on files/en-us/web/api/cssstartingstylerule/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
Change made

2023-11-06 11:02 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/
Yup, I totally agree with you; I've made the change here, and elsewhere too.

2023-11-06 11:13 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Provides a set of starting values for properties set on the popover that you want to transition from when it is first shown. This is needed because, by default, CSS transitions only occur when
I agree that the position of this could be improved. I ended up going with this sentence structure:

> This is needed to avoid unexpected behavior. By default, CSS transitions only occur...

I've made this change here, and on all other pages where this occurs.

2023-11-06 11:16 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Set `transition-behavior: allow-discrete` on the `display` and `overlay` transitions to enable discrete transitions on these two properties that are not by default animatable.
Yup, good call. Change made on this page, and on the `<dialog>` element page where it also appears.

2023-11-06 11:38 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +because the nesting selector cannot represent pseudo-elements. */
Good call; added

2023-11-06 11:40 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or
Update made

2023-11-06 11:41 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +When animating a popover with CSS animations, there are some differences to note:
Updated

2023-11-06 11:41 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- You don't need to explicitly enable discrete animations; there is no equivalent to `allow-discrete` inside keyframes.
Updated

2023-11-06 11:43 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +Let's consider a scenario where we want to animate a [popover](/en-US/docs/Web/API/Popover_API) when shown (that is, when added to the top layer). The "original rule" specifying the styles for the op
Good spot, updated, thanks!

2023-11-06 11:43 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +Note the `@starting-style` block used to specify the starting style for the transition, and the inclusion of the `display` property in the trainsitions list, with `allow-discrete` set on it.
I checked; this already got fixed, so we are all good here.

2023-11-06 12:00 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +@starting-style { declarations } /* when nested within a ruleset */
I think you've got a good point here. I've looked at the `@supports` page, and tried to write something in the same style for `@starting-style`. Let me know what you think!

2023-11-06 12:02 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +By default, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are not triggered on an element's initial style update, or when its [`display`](/en-US/docs/Web/CSS/display) type changes from `none
Yup, that sounds good. I've used this wording in my next commit.

2023-11-06 12:04 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +`@starting-style` enables the creation of entry and exit transitions for elements displayed in the [top layer](/en-US/docs/Glossary/Top_layer) (such as [popovers](/en-US/docs/Web/API/Popover_API) and
Sure, makes sense. Updated.

2023-11-06 12:06 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** The `@starting-style` at-rule and the "original rule" have the same specificity. To ensure that starting styles get applied, include the `@starting-style` at-rule _after_ the "original ru
Updated!

2023-11-06 12:07 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To specify the starting style for the popover using the second method, you can nest the `@starting-style` block inside the "original rule", as shown below:
updated

2023-11-06 12:08 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +In this example, we want to animate two properties, [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) (specifically, a horizontally scaling transform), to make
Good spot. Updated.

2023-11-06 12:12 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- `display` is added to the list of transitioned elements to ensure the animated element is visible (set to `display: block`) throughout both the entry and exit animations. Without this, the exit ani
In the example, `display: block` is set by the browser default styles when the popover is shown. Nevertheless, your change makes sense, so I've done the update.

2023-11-06 12:20 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +  opacity: 0;
It is needed for the final state of the exit animation. I have added a code comment to state this. On this page and on the other pages where this example appears.

2023-11-06 12:24 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +}
In cases such as this where there are only a couple of non-example-relevant styles being used, I think it is fine to show them as they don't get in the way. If there were huge blocks of non-critical styles being used in the setup of the example, I would of course hide those. 

No change made.

2023-11-06 13:01 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +    all 0.7s allow-discrete */
Yup; good call. Changed in all places it appears.

2023-11-06 13:03 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the el
Updated.

2023-11-06 13:13 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The static HTML looks like this:
OK. I've removed the lead-in lines that don't really add anything.

2023-11-06 13:14 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The JavaScript code that handles the addition and removal of the elements looks like this:
Updated

2023-11-06 13:28 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +}
Good call. I was a bit concerned with `hexVal` because I thought people could interpret it as "hex value" in the CSS sense, rather than more generically as a hexadecimal number representation, which does make sense.

I've therefore gone for the more generic `randomNum`, which is still shorter and allows it all to fit on one line.

I've also changed the commas for spaces.

2023-11-06 13:29 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +/* Nesting is not supported for pseudo-elements
Updated

2023-11-06 13:31 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +The most interesting part is the `createColumn()` function. Notice how it creates a {{htmlelement("div")}} element and a {{htmlelement("button")}} element to close the `<div>` when pressed, then appe
Sure; updated.

2023-11-06 13:33 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +
Sure, this reads well. I've used it, with a bit of modification.

2023-11-06 13:48 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +### Animating a popover
Your example looks fine, but I have already added an appropriate example to the `<dialog>` reference pages. So I've a note to link to that rather than adding another new example here. The page is already pretty long.

2023-11-06 13:54 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +Let's move on to the CSS:
I removed that sentence in a previous edit because you said it was the kind of thing we don't normally include in the CSS section. 

I've hidden the first 4 rules of the block, as they weren't relevant to what I am explaining.

2023-11-06 14:00 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +  transform: scaleY(1);
OK; updated example to use `scale` rather than `transform: scaleY(1)`.

2023-11-06 14:00 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +    transform 0.7s,
changed

2023-11-06 14:00 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +  transform: scaleY(0);
changed

2023-11-06 14:02 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To animate [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) on each `<div>` as it is added to the DOM and then reverse the animation as it is removed from the
OK. Updated.

2023-11-06 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the exit animation inside the `.fade-out` rule — this is the class that the JavaScript assigns to the `<div>` elements when their close buttons are pressed. Besides setting the `opacity` an
Changed. 

I was thinking that we want to make sure those elements are not available to be interacted with once the close button is clicked, e.g. so the user can't accidentally click it again, which might cause problems.

2023-11-06 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the exit animation inside the `.fade-out` rule — this is the class that the JavaScript assigns to the `<div>` elements when their close buttons are pressed. Besides setting the `opacity` an
It's really a preference, but it is a good idea.

2023-11-06 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Specify the [`transition`](/en-US/docs/Web/CSS/display) list inside the `div { ... }` rule to animate `opacity`, `transform`, and `display`. Note that for `display`, the [`transition-behavior: allo
changed

2023-11-06 14:12 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +In the case of `content-visibility` however, the browser will flip between the two values so that the animated content is shown for `100%` of the animation duration. So for example:
I agree with removing the history stuff, so I've made that change. However, your other changes make it sound like `transition-behavior: allow-discrete` is required for animations and transitions, or at least don't make it clear that it is only required for transitions. so I've not made the other changes.

2023-11-06 14:23 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +This behavior is useful for creating entry/exit animations where you want to for example remove some content from the UI immediately with `content-visibility: hidden`, but have it animate (for exampl
This is a good question; I'm not sure. When testing it in the browser, the dev tools still show the content in the UI even after the animation has finished.

I think your text suggestion sounds good either way, so I've made it.

2023-11-06 14:59 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +- When animating between `display` `none` and `block`, the value will flip to `block` at `0%` of the animation duration so it is visible throughout.
I kind of did this, but handled it differently.

`animation-fill-mode` behaves the same as it does with any other animation - I've used the `forwards` value in my examples, so that it stays like it is at the end of the animation after it finishes.

2023-11-06 15:04 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +- When animating between `display` `block` and `none`, the value will flip to `none` at `100%` of the animation duration so it is visible throughout.
Explanation seems like overkill; I think mine is Ok as-is (provided of course if it is true!)

2023-11-06 15:06 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +{{ EmbedLiveSample("content-visibility animation example", "100%", "250") }}
300 seems fine, so I've gone for that.

2023-11-06 15:09 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +  }
Good call, updated! I only found out about the `toggle()` method very recently ;-)

2023-11-06 15:33 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
OK, so I've removed the `forwards` instances that aren't needed; that makes a lot of sense.

But I've left the `display` instances in place for now, as I'm confused as to why it works without them. I thought we'd need these, otherwise, the animation wouldn't show? You'd just see the off and on states as `display` goes from `none` to `block`?

In fact I'm pretty sure that is how it used to behave; I am wondering if the behavior has changed here since I first wrote these docs.  If not, then I'm fundamentally misunderstanding something quite major here.

I'll ask the Chrome engineers about it.

2023-11-07 03:29 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/
```suggestion
Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/Performance/How_browsers_work#building_the_accessibility_tree). Therefore, for popovers to be animated the {{cssxref("display")}} property needs to be animatable. [Supporting browsers](/en-US/docs/Web/CSS/display#browser_compatibility) animate `display` with a variation on the [discrete animation type](/en-US/docs/Web/CSS/CSS_animated_properties#discrete). Specifically, the browser will flip between `none` and another value of `display` so that the animated content is shown for `100%` of the animation duration. So, for example:
```

2023-11-07 03:29 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Add `display` to the transitions list so that the popover will remain as `display: block` for the duration of the transition, ensuring the other transitions are visible.
```suggestion
  - : Add `display` to the transitions list so that the popover will remain as `display: block`, or other visible `display` value, for the duration of the transition, ensuring the other transitions are visible.
```

2023-11-07 03:29 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Include `overlay` in the transitions list to ensure the removal of the popover from the top layer is deferred until the transition completes, again ensuring the transition is visible.
should we fit in "all" here? So people know it doesn't need to be an explicit inclusion.

2023-11-07 03:29 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +    display: block;
we could use my example, but change the "inline" to "flex" and center the text ONLY during the animation so it is apparent that the `display: flex` set in the animation is actually set.

2023-11-07 04:30 UTC, estelle reviewed
re-re-review of csstartingstyle and using the popover API. Submitting this review, then continuing on.

2023-11-07 04:30 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
By default, the popover and backdrop are not displayed unless they are open. With animations, if a property is animated but only one keyframe value is set with that property, the value goes from (or to) the initial value. In this case, that is display none at 0%

2023-11-07 04:30 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +[popover]:popover-open::backdrop {
you could use the `reverse` animation direction and just have one keyframe animation

2023-11-07 05:24 UTC, estelle reviewed
Re-review of @starting-style. Just minor tweaks. 
Committing and moving on to the next page.

2023-11-07 05:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden — which also means that its hidden sta
Should we invert the sentence? I find it confusing. What makes it mean that its hidden state has display none?

2023-11-07 05:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +- [`overlay`](/en-US/docs/Web/CSS/overlay) is added to the list of transitioned elements to ensure that the removal of the element from the top layer is deferred until the animation has been complete
```suggestion
- [`overlay`](/en-US/docs/Web/CSS/overlay) is added to the list of transitioned elements to ensure that the removal of the element from the top layer is deferred until the animation ends. This doesn't make a huge difference for simple animations such as this one, but in more complex cases, not doing this can result in the element being removed from the overlay too quickly, meaning the animation is not smooth or effective. Again, `transition-behavior: allow-discrete` is required in this case for the animation to occur.
```
if the animation is 0.6 iterations, it doesn't complete but it does end (i am so pedantic!!!)

2023-11-07 05:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +> **Note:** You can find an example that demonstrates transitioning a {{htmlelement("dialog")}} element and its backdrop as it is shown and hidden on the `<dialog>` reference page — see [Transitionin
👍

2023-11-07 05:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the el
```suggestion
This example contains a button, which, when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the element. This example demonstrates how to use transitions to animate elements when they are added to or removed from the DOM.
```

2023-11-07 05:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +- Removes the `<div>` after a 1000ms delay. The {{domxref("setTimeout")}} delays the removal of the `<div>` from the DOM (via {{domxref("Element.remove()")}}) until after the animation has finished.
```suggestion
- Removes the `<div>` after a 1000ms delay. The {{domxref("setTimeout")}} delays the removal of the `<div>` from the DOM (via {{domxref("Element.remove()")}}) after the animation has finished.
```

2023-11-07 05:35 UTC, estelle reviewed
content-visibility review. minor tweaks and a couple of questions that we may want to address.

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +In the case of `content-visibility` however, the browser will flip between the two values so that the animated content is shown for `100%` of the animation duration. So for example:
```suggestion
[Supporting browsers](#browser_compatibility) animate/transition `content-visibility` with a variation on the [discrete animation type](/en-US/docs/Web/CSS/CSS_animated_properties#discrete). 

Discrete animation generally means that the property will flip between two values, `50%` through the animation. In the case of `content-visibility`, however, the browser will flip between the two values to show the animated content for `100%` of the animation duration. So, for example:
```

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +When animating `content-visibility` with [CSS animations](/en-US/docs/Web/CSS/CSS_animations), you need to provide the starting `content-visibility` value in an explicit starting keyframe (for exampl
we should test to see if this is like display; as long as it's visible at any keyframe (say 72% to 88%), is it visible 100% of the time?

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) is used to provide a set of starting values for properties set on an element that you want to transition from when the element receives its
same edit as above. The first sentence is hard to grok.

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +  to provide a smooth animation effect.
provide or demonstrate?

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +  animation: hide 0.7s ease-out forwards;
if we did ` animation: show 0.7s reverse ease-out ` would this work? should we demonstrate that it's not always 0% to 100%, but in either direction?

2023-11-07 05:35 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +Finally, we use some JavaScript to apply the `.show` and `.hide` classes to the `<div>` as appropriate to apply the animations as it is toggled between shown and hidden.
```suggestion
Finally, we use JavaScript to apply the `.show` and `.hide` classes to the `<div>` as appropriate to apply the animations as it is toggled between shown and hidden states.
```

2023-11-07 06:42 UTC, estelle reviewed
review of css transition property.
very minor edits, but there are two edits for pre-existing content that i suggested

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +transition: all 0.5s ease-out allow-discrete;
```suggestion
transition: all 0.5s ease-out allow-discrete;
transition: 200ms linear 50ms;
```

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +transition: all 0.5s ease-out allow-discrete;
want to point out that `all` is not needed and delays are a thing.

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +transition: all 0.5s ease-out allow-discrete;
Line 61 and 63 need help.

```md
The `transition` property is specified as one or more single-property transitions, separated by commas, or `none` for no transitions. Each single-property transition describes the transition that should be applied to a single property (or the special value and default `all`). It includes:
```
if none is used, that is the only value that can be used. `all` (with or without the keyword present) can be used as the property of a single transition in the list of comma-separated transition, if it is the first value (and the subsequent single values override the other values withing that shorthand.

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +- zero or one value declaring whether to start transitions for properties whose animation behavior is [discrete](/en-US/docs/Web/CSS/CSS_animated_properties#discrete):
line 68, the keyword `all`, should have a note that if no value is included, it defaults to `all`.

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +> **Note:** See our [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) guide for more `transition` examples.
```suggestion
> **Note:** See [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) for more `transition` examples.
```

2023-11-07 06:42 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
```suggestion
- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) module
```

2023-11-07 06:45 UTC, estelle commented on files/en-us/web/css/transition-property/index.md
> +  font-size: 20px;
```suggestion
  font-size: 1.4rem;
```

2023-11-07 14:31 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +    display: block;
I suppose my issue really is that yes, your example does show a display animation being applied. But, I worry that it isn't very real world. People are far more likely to want to animate from `display: none` to `block` really, and use it as a means for showing/hiding panels, etc.

So, I've spent another absolute age messing around with this stuff today, and updated my example. I'm quite pleased with the end result — I've got two paragraphs, and a div in between that animates from display to block. You can see that the display value is animating because the space between the two paragraphs disappears when it gets to display: none.

My main concern is that the CSS is inelegant and a bit hackish:

```css
div {
  font-size: 1.6rem;
  padding: 20px;
  border: 3px solid red;
  border-radius: 20px;
  width: 480px;
  opacity: 0;
  display: none;
}

/* Animation classes */

div.fade-in {
  display: block;
  animation: fade-in 0.7s ease-in forwards;
}
```

I had to set display: none on the div's starting state so that it starts hidden, but then I has to set display: block on the faded-in state as well as applying the animation, otherwise the original display: none overrides the animation and it never displays.

I also thought about how to do it without JS, but I kept the JS in the end. Starting from display: none, there is nothing to hover to allow the animation to be applied via direct state change. I also tried to create an example where you hover an adjacent element to make the div appear and disappear, but I had all sorted of interesting problems trying to get that to work.

So, any suggestions on how to improve this example will be much appreciated.

2023-11-07 14:48 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
Ah, of course, yes. Thanks!

OK, so I've removed display from the entry animation keyframes, and kept it on both the exit animation keyframes. I know it works without the last one, but it feels good to me to be explicit.

I've also added a helpful comment, like the one @OnkarRuikar suggested in his version.

2023-11-07 14:49 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/
Updated.

2023-11-07 14:50 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Add `display` to the transitions list so that the popover will remain as `display: block` for the duration of the transition, ensuring the other transitions are visible.
added

2023-11-07 14:53 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Include `overlay` in the transitions list to ensure the removal of the popover from the top layer is deferred until the transition completes, again ensuring the transition is visible.
I see what you are saying, but we are talking specifically about the explicit features that are required. `all` isn't an explicit feature that is required, it is more like another way of representing `display` and `overlay` in the transitions list.

I did add comments to all of the transition code examples to show that you can use `all` with `allow-discrete` rather than listing them all separately. I think that will suffice.

2023-11-07 14:54 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Set a starting state for the transition inside the `@starting-style` block.
Updated

2023-11-07 14:55 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Added `display` to the list of transitioned elements so that the animated element is visible (set to `display: block`) throughout both the entry and exit animation. Without this, the exit animation
Changed!

2023-11-07 14:55 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Added `overlay` to the list of transitioned elements to make sure that the removal of the element from the top layer is deferred until the animation has been completed. The effect of this may not b
updated

2023-11-07 14:56 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- Set `allow-discrete` on both the above transitions to enable [discrete transitions](/en-US/docs/Web/CSS/CSS_animated_properties#discrete).
changed

2023-11-07 15:00 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +- You don't provide a `@starting-style`; instead, you provide the starting values (including the initial `display` value) in an explicit starting keyframe (using `0%` or `from`).
ok, makes sense; updated

2023-11-07 15:04 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +[popover]:popover-open::backdrop {
I'm not sure how feasible this is now that I've applied the changes @OnkarRuikar suggested in a previous comment. fade-in and fade-out are no longer direct opposites of one another. I'll leave it as-is.

2023-11-07 15:07 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To avoid unexpected behavior, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are by default not triggered on an element's initial style update, or when its [`display`](/en-US/docs/Web/CSS/dis
looking good. Updated.

2023-11-07 15:09 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To specify the starting style for the popover using the first method, you include a standalone `@starting-style` block in your CSS, as shown below:
Sounds reasonable. I've used it, with a slight tweak to make the sentence flow better:

> To specify the starting values of the popover's properties that will be animated using the first method

2023-11-07 15:12 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden — which also means that its hidden sta
I've tried to simplify it, as follows:

> However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden (with [`display: none`](/en-US/docs/Web/CSS/display)), some extra steps are required to ensure the animation works in both directions:

Any better?

2023-11-07 15:14 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- [`overlay`](/en-US/docs/Web/CSS/overlay) is added to the list of transitioned elements to ensure that the removal of the element from the top layer is deferred until the animation has been complete
Pedantry rules.

It is also shorter, so I've used it.

2023-11-07 15:15 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the el
Do you think your comma-fu can defeat me?

I think this is slightly more correct, so I've gone with it:

> This example contains a button which, when pressed, appends new elements to a {{htmlelement("section")}} container.

2023-11-07 15:17 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +- Removes the `<div>` after a 1000ms delay. The {{domxref("setTimeout")}} delays the removal of the `<div>` from the DOM (via {{domxref("Element.remove()")}}) until after the animation has finished.
Not quite right. I've updated it to this slightly different version:

> Removes the `<div>` after a 1000ms delay. The {{domxref("setTimeout")}} delays removal of the `<div>` from the DOM (via {{domxref("Element.remove()")}}) until after the animation ends.

2023-11-07 15:42 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +In the case of `content-visibility` however, the browser will flip between the two values so that the animated content is shown for `100%` of the animation duration. So for example:
Sounds good. Updated.

2023-11-07 15:52 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +When animating `content-visibility` with [CSS animations](/en-US/docs/Web/CSS/CSS_animations), you need to provide the starting `content-visibility` value in an explicit starting keyframe (for exampl
I'd say it is, yes. In the animation example I added to this page, you can see that the content is visible on the page throughout both the entry and exit animations. If it wasn't, the content wouldn't take up the space on the page.

2023-11-07 16:05 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) is used to provide a set of starting values for properties set on an element that you want to transition from when the element receives its
I'm not 100% sure which edit you mean, or which sentence you mean is hard to grok. I'm guessing you mean the first sentence of the first bullet, shown above, and I've attempted to improve it like so:

> [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) provides a set of starting values for properties that you want to transition from when the animated element is first shown.

Is that better?

2023-11-07 16:07 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +  to provide a smooth animation effect.
I've changed it to "create" ;-)

2023-11-07 16:11 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +  animation: hide 0.7s ease-out forwards;
I've just tried it, and no, it doesn't work. The show animation happens the first time, but then after that the content just appears and disappears with no animation.

2023-11-07 16:13 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +Finally, we use some JavaScript to apply the `.show` and `.hide` classes to the `<div>` as appropriate to apply the animations as it is toggled between shown and hidden.
updated

2023-11-07 16:35 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +- zero or one value declaring whether to start transitions for properties whose animation behavior is [discrete](/en-US/docs/Web/CSS/CSS_animated_properties#discrete):
I included just such a note earlier on.

2023-11-07 16:36 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +> **Note:** See our [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) guide for more `transition` examples.
done

2023-11-07 16:39 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
done

2023-11-07 16:41 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +  font-size: 20px;
changed

2023-11-07 17:18 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +This example contains a button, which when pressed, appends new elements to a {{htmlelement("section")}} container. Each element, in turn, contains a nested button, which when pressed, removes the el
that's even better than what ~~Estelle~~ **Grammarly** suggested!

2023-11-07 17:34 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden — which also means that its hidden sta
Yes. Perfect.

2023-11-08 07:14 UTC, estelle reviewed
more edits. I haven;t hit the dialog page yet, but if you could update it with the suggestions from the other pages before i get to it that would be awesome.

2023-11-08 07:14 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +- zero or one {{cssxref("&lt;custom-ident&gt;")}} value representing the property to which the transition should apply.
Should we do this change? Or add a "if zero values are provided, the default value is used. see formal syntax"? Or add the defaults to all of these bullet points?

```
- The [<custom-ident>] value representing the property to which the transition should apply.
- The [<easing-function>] value representing the easing function to use
- Up to two [<time>] values. The first value is parsed as the [transition-duration], the second value being the [transition-delay]. 
- A [<transition-behavior-value>] declaring whether to start transitions for properties whose animation behavior is [discrete] with `allow-discrete` or not, with `normal`.
```
or
```
- The [<custom-ident>] value representing the property to which the transition should apply. If omitted, value defaults to `all`.
- The [<easing-function>] value representing the easing function to use. If omitted, value defaults to `ease`.
- Up to two [<time>] values. The first value is parsed as the [transition-duration], the second value being the [transition-delay]. If omitted, the values default to `0s`, meaning the transition is immediate and lasts 0s, meaning the animation is not visible.
- A [<transition-behavior-value>] declaring whether to start transitions for properties whose animation behavior is [discrete] with `allow-discrete` or not, with `normal`. If omitted, defaults to `normal`.
```

2023-11-08 07:14 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +  - the keyword `normal`
actually, provided alternate suggestion

2023-11-08 07:14 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +> **Note:** See [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) for more `transition` examples.
omit this note and add to see also (keeping the module landing page)

2023-11-08 07:14 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +### Transitioning top layer elements
the goal of this page is teaching the shorthand. this example doesn't do that. I suggest removing this page from the PR. If you want to include this, create a new PR with an example that shows the pre- state of a transition and a post-state of a transition, you could even include different values in the pre and post to show that transitions in the reverse direction can have different values. You can even add a start-style to show that you can transition from and to something, and then when it reverts the "from" is not the same than the initial from, which is the start style, if that makes sense.

2023-11-08 07:57 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +Popovers are set to `display: none;` when hidden and `display: block;` when shown, as well as being removed from / added to the {{glossary("top layer")}} and the [accessibility tree](/en-US/docs/Web/
done

2023-11-08 07:58 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Provides a set of starting values for properties set on the popover that you want to transition from when it is first shown. This is needed to avoid unexpected behavior. By default, CSS transit
changed

2023-11-08 08:01 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    as the specificity is the same */
updated

2023-11-08 08:03 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +because the nesting selector (&) cannot represent pseudo-elements. */
changed

2023-11-08 08:08 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +Let's consider a scenario where we want to animate a [popover](/en-US/docs/Web/API/Popover_API) when shown (that is, when added to the top layer). The "original rule" specifying the styles for the op
updated

2023-11-08 08:08 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To specify the starting values of the popover's properties that will be animated using the first method, you include a standalone `@starting-style` block in your CSS, as shown below:
updated

2023-11-08 08:09 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +To specify the starting style for the popover using the nested method, you can nest the `@starting-style` block inside the "original rule", as shown below:
updated

2023-11-08 08:10 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +This example shows how a [popover](/en-US/docs/Web/API/Popover_API) can be animated using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions). Basic entry and exit animations are provided using th
updated. Although to be honest, I don't see why it's a problem at all having slight different text styles for things like this. It makes the docs less boring and robotized.

2023-11-08 08:11 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +
moved

2023-11-08 08:11 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +In this example, we want to animate two properties, [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) (specifically, a horizontally scaling transform), to make
done

2023-11-08 08:15 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +
Added.

2023-11-08 08:25 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +Discrete animation generally means that the property will flip between two values `50%` through the animation. In the case of `content-visibility`, however, the browser will flip between the two valu
changed, here, and in all the other articles.

2023-11-08 08:34 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +## Animating and transitioning content-visibility
I've gone for an easier solution here. I've just changed the existing title to an H3, and added a "Description" H2 above it. This way, the structure is correct, and any future description sections can be added in the right place beneath it.

I'd rather not start breaking up the content that's there, as I think it works together.

2023-11-08 08:41 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +- When animating between `content-visibility` `visible` and `hidden`, the value will flip to `hidden` at `100%` of the animation duration so it is visible throughout.
I've changed the form of this sentence here, and everywhere else it appears.

2023-11-08 08:42 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +In the CSS we initially set `content-visibility: hidden;` on the `<div>` to hide its content. We then set up `@keyframe` animations and attach them to classes to show and hide the `<div>`, animating
I've just changed "but also" to "and"

2023-11-08 08:46 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +## Animating display and content-visibility
Good call. I've changed this H2 -> H3, and all the sub-H3s to H4s

2023-11-08 08:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +There is an exception, however, which is when animating to/from `display: none` or `content-visibility: hidden` to a visible value. In this case, the browser will flip between the two values so that
I've gone for a slightly simpler edit. I think your text, while precise, is going to be harder to understand.

2023-11-08 08:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +### HTML
changed

2023-11-08 08:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +### CSS
changed

2023-11-08 08:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +### JavaScript
changed

2023-11-08 08:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +### Result
changed

2023-11-08 09:21 UTC, chrisdavidmills commented on files/en-us/web/css/display/index.md
> +- When animating between `display` `none` and `block`, the value will flip to `block` at `0%` of the animation duration so it is visible throughout.
changed

2023-11-08 09:21 UTC, chrisdavidmills commented on files/en-us/web/css/display/index.md
> +- When animating between `display` `block` and `none`, the value will flip to `none` at `100%` of the animation duration so it is visible throughout.
changed

2023-11-08 09:37 UTC, chrisdavidmills commented on files/en-us/web/css/display/index.md
> +This behavior is useful for creating entry/exit animations where you want to for example remove a container from the UI immediately with `display: none`, but have it fade out with [`opacity`](/en-US/
Fair enough, but I've gone for a smaller, simpler edit:

> This behavior is useful for creating entry/exit animations where you want to for example remove a container from the DOM with `display: none`, but have it fade out with [`opacity`](/en-US/docs/Web/CSS/opacity) rather than disappearing immediately.

2023-11-08 09:40 UTC, chrisdavidmills commented on files/en-us/web/css/display/index.md
> +When animating `display` with [CSS animations](/en-US/docs/Web/CSS/CSS_animations), you need to provide the starting `display` value in an explicit starting keyframe (for example using `0%` or `from`
changed

2023-11-08 09:43 UTC, chrisdavidmills commented on files/en-us/web/css/display/index.md
> +
I mostly used this, but "animateability"? No ;-)

I just said "transitions".

2023-11-08 09:51 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +## Transitioning display and content-visibility
Done

2023-11-08 09:51 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +It is important to note that `overlay` can _only_ be set by the browser — author styles cannot change the `overlay` value of any element. You can however add `overlay` to the [list of transition prop
changed

2023-11-08 09:58 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +
I'm pretty sure they are not, so I'm leaving them out.

2023-11-08 09:59 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +This example shows how a [popover](/en-US/docs/Web/API/Popover_API) can be animated using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions). Basic entry and exit animations are provided.
updated

2023-11-08 10:00 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +   to take effect, as the specificity is the same */
changed

2023-11-08 10:00 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +because the nesting selector cannot represent pseudo-elements. */
changed

2023-11-08 10:03 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +The two properties we want to animate are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform) (specifically, a horizontally scaling transform): we want the popov
done

2023-11-08 10:10 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +- `display` is added to the list of transitioned elements so that the animated element is visible (set to `display: block`) throughout both the entry and exit animation. Without this, the exit animat
good call; done.

2023-11-08 10:11 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +Further examples (including a `<dialog>` modal animation) can be found at [Animating elements to and from the top-layer](https://developer.chrome.com/blog/entry-exit-animations/#animating-elements-to
fair enough; removed.

2023-11-08 10:12 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +  transition-duration: 0.25s, 0.25s;
good point; updated

2023-11-08 10:13 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +See the next example for shorthand usage.
deleted

2023-11-08 10:21 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +
Done! I've made it consistent with overlay, but rewritten the CSS explanation so that it explains `transition-behavior` first.

2023-11-08 10:22 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style)
changed

2023-11-08 10:24 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +> **Note:** See our [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) guide for more `transition-property` examples.
ok, done

2023-11-08 10:36 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +  opacity: 0;
I don't want to sidetrack this PR too much by fixing this example, but I've just quickly changed it so that `background-color` is transitioned, and it generally looks a bit nicer. That's a more obvious button transition.

2023-11-08 10:52 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +- One single-property transition, which is structured as described below, except that the special value `all` is used in place of a property value. This specifies that the transition will be applied
Wow, I never knew that. I have updated the text to suit.

2023-11-08 10:56 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +- zero or one {{cssxref("&lt;custom-ident&gt;")}} value representing the property to which the transition should apply.
It's written differently now anyway. I'd rather not get too deep into rewriting this entire section, as it is mostly nothing to do with my PR.

2023-11-08 10:57 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +> **Note:** See [Using CSS transitions](/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions) for more `transition` examples.
done

2023-11-08 11:00 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +### Transitioning top layer elements
I've just removed this section for now.

2023-11-08 16:07 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
we should add a note about it then.

2023-11-09 08:00 UTC, chrisdavidmills commented
For consideration next week (from a conversation with Chrome engineering):

> Animating the display property is only necessary for exit animations, so that explains why the fade-in keyframes rule doesn't need to specify display. When the popover shows, the browser synchronously changes it from display:none to display:block. This distinction is less clear when using transitions instead of keyframes animations because you'd just say that the display property should be transitioned regardless of entry or exit.

Check to make sure what we've written agrees with this.

2023-11-13 08:52 UTC, estelle commented
Hopefully my next review is the final one. Keeping tabs of pages here: (checked when reviewed as publishable)

- [] [/en-US/docs/Web/API/CSSStartingStyleRule](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CSSStartingStyleRule)
- [] [/en-US/docs/Web/API/Popover_API/Using](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Popover_API/Using)
- [] [/en-US/docs/Web/CSS/@starting-style](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/@starting-style)
- [] [/en-US/docs/Web/CSS/CSS_animations/Using_CSS_animations](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_animations/Using_CSS_animations)
- [] [/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions)
- [] [/en-US/docs/Web/CSS/content-visibility](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/content-visibility)
- [] [/en-US/docs/Web/CSS/display](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/display)
- [] [/en-US/docs/Web/CSS/overlay](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/overlay)
- [] [/en-US/docs/Web/CSS/transition-behavior](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transition-behavior)
- [] [/en-US/docs/Web/CSS/transition-property](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transition-property)
- [] [/en-US/docs/Web/CSS/transition](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/transition)
- [] [/en-US/docs/Web/HTML/Element/dialog](https://pr29943.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/dialog)

2023-11-13 09:04 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +> **Note:** When animating using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions), [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set to enable the
```suggestion
> **Note:** When animating using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions), [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set to enable the above behavior. When animating with [CSS animations](/en-US/docs/Web/CSS/CSS_animations), the above behavior is available by default; an equivalent step is not required.
```

2023-11-13 09:08 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Add `display` to the transitions list so that the popover will remain as `display: block` (or another visible `display` value) for the duration of the transition, ensuring the other transitions
Optional: add that the display value, if other than block, should be in the `:popover-open` state, otherwise the default `display none;` will be overridden

2023-11-13 09:14 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or
Move (most of) this paragraph to before the line 339;  as a brief intro what we are going to do. Or just add a sentence on 339 to let the user know before the CSS what the CSS is about.

2023-11-13 09:17 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +    background-color: rgb(0 0 0 / 0.25);
this looks like it should make everything inert, including the toggle for the popover. Consider changing the color or lightening it.

2023-11-13 09:24 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden (with [`display: none`](/en-US/docs/We
```suggestion
Because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden (with [`display: none`](/en-US/docs/Web/CSS/display)), some extra steps are required to ensure the animation works in both directions:
```

2023-11-13 09:43 UTC, estelle commented on files/en-us/web/api/popover_api/using/index.md
> +
```suggestion
Because the popover is transitioning from `display: none` to `display: block, every time the popover opens, it transitions from the `@start-style` styles to the`[popover]:popover-open` styles. When the popover exits, it transitions from `[popover]:popover-open` state to the default `[popover]` state.
```
I think it's important to delineate that every time it opens it goes to start-style, not just the first time.

2023-11-13 09:48 UTC, estelle commented on files/en-us/web/css/@starting-style/index.md
> +```css
During our sync chat, we discussed adding a color to demonstrate that every time a popover opens it goes from start style to popover-oven, not just the first time.

adding background color, then something similar to 

```
Because the popover is transitioning from `display: none` to `display: block, every time the popover opens, it transitions from the `@start-style` styles to the`[popover]:popover-open` styles. When the popover exits, it transitions from `[popover]:popover-open` state to the default `[popover]` state.
```

is helpful. https://codepen.io/estelle/pen/BaMZOgR

2023-11-13 09:57 UTC, estelle commented on files/en-us/web/css/transition-property/index.md
> +  background-color: #ccc;
```suggestion
  background-color: #0001;
```
the intro says we're changing opacity, so changing opacity

2023-11-13 09:58 UTC, estelle commented on files/en-us/web/css/transition-property/index.md
> +  background-color: #eee;
```suggestion
  background-color: #0004;
```

2023-11-13 23:10 UTC, estelle reviewed
Review of html/dialog page

2023-11-13 23:10 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +When animating a `<dialog>` with CSS animations, there are some differences to note from transitions:
```suggestion
When animating a `<dialog>` with CSS keyframe animations, there are some differences to note from transitions:
```
(since we used animations and transitions interchangeably before)

2023-11-13 23:10 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +- You don't provide a `@starting-style`; instead, you provide the starting values (including the initial `display` value) in an explicit keyframe (using `0%` or `from`).
```suggestion
- You don't provide a `@starting-style`; instead, you provide the starting value in an explicit keyframe (using `0%` or `from`).
- Including the `display` value in a keyframe; this will be the display value for the entirety of the animation, or until another non-`none` display value is encountered.
```
I am pretty sure my edit is accurate. The display does not need to be in the 0 or from, but, rather, anywhere in the keyframe. And, if the display is flex at 42% and inline at 56%, i think it will switch to inline at 56.

2023-11-13 23:10 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +- You don't provide a `@starting-style`; instead, you provide the starting values (including the initial `display` value) in an explicit keyframe (using `0%` or `from`).
https://codepen.io/estelle/pen/JjxbbJL

2023-11-13 23:10 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +Note the keyframes defined to animate between the closed and shown states of the `<dialog>`, plus the fade-in animation for the `<dialog>`'s backdrop. The `<dialog>` animations include animating `dis
move to before the css

2023-11-13 23:10 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +Finally, the JavaScript serves to wire up the buttons to event handlers that show and close the `<dialog>`.
```suggestion
Finally, the JavaScript adds the event handlers to the buttons to enable showing and closing the `<dialog>`.
```

2023-11-14 07:56 UTC, ramiy reviewed
Consider using `CSSxRef` instead of simple links. I've attached several code suggestions.

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/cssstartingstylerule/index.md
> +The **`CSSStartingStyleRule`** interface of the [CSS Object Model](/en-US/docs/Web/API/CSS_Object_Model) represents a CSS [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) at-rule.
```suggestion
The **`CSSStartingStyleRule`** interface of the [CSS Object Model](/en-US/docs/Web/API/CSS_Object_Model) represents a CSS {{CSSxRef("@starting-style")}} at-rule.
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/cssstartingstylerule/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style)
```suggestion
- {{CSSxRef("@starting-style")}}
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/popover_api/using/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) at-rule
```suggestion
- {{CSSxRef("@starting-style")}} at-rule
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/popover_api/using/index.md
> +- [`display`](/en-US/docs/Web/CSS/display) property
```suggestion
- {{CSSxRef("display")}} property
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/popover_api/using/index.md
> +- [`overlay`](/en-US/docs/Web/CSS/overlay) property
```suggestion
- {{CSSxRef("overlay")}} property
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or
Also, use `{{CSSxRef("...")}}` for CSS properties.

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/css/@starting-style/index.md
> +To avoid unexpected behavior, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are by default not triggered on an element's initial style update, or when its [`display`](/en-US/docs/Web/CSS/dis
```suggestion
To avoid unexpected behavior, [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) are by default not triggered on an element's initial style update, or when its {{CSSxRef("display")}} type changes from `none` to another value. To enable first-style transitions, `@starting-style` rules are needed. They provide starting styles for elements that do not have a previous state, defining the property values to transition from.
```

2023-11-14 07:56 UTC, ramiy commented on files/en-us/web/css/@starting-style/index.md
> +In this example, the [popover](/en-US/docs/Web/API/Popover_API) can be animated using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions). Basic entry and exit animations are provided using the [`
```suggestion
In this example, the [popover](/en-US/docs/Web/API/Popover_API) can be animated using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions). Basic entry and exit animations are provided using the {{CSSxRef("transition")}} property.
```

2023-11-14 08:55 UTC, chrisdavidmills commented
Thanks for the suggestions @ramiy. I have accepted them all. However, because this PR review is so long and complex already, please don't add any more ;-)

Let's get this merged first, then I'd be happy to accept more suggestions of that kind in a new PR.

2023-11-14 09:02 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +  - : Add `display` to the transitions list so that the popover will remain as `display: block` (or another visible `display` value) for the duration of the transition, ensuring the other transitions
I'd rather leave it out from here, as I think it might confuse more than it helps. Also, given that display is animated in several places, maybe we could deal with such details just on the display page where I talk about animating display, rather than in several places.

2023-11-14 09:05 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +The two popover properties we want to transition are [`opacity`](/en-US/docs/Web/CSS/opacity) and [`transform`](/en-US/docs/Web/CSS/transform). We want the popover to fade in or out while growing or
In both cases, I've moved the whole paragraph up to the top. I think it works fine.

2023-11-14 09:22 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    background-color: rgb(0 0 0 / 0.25);
I've fixed this example differently, as I'd rather not mess with the styling. I've changed all instances to talk about displaying, not toggling. I've made sure all the examples use auto popovers, not manual, so the popover can be light-dismissed (by clicking outside it and pressing the <kbd>Esc</kbd> key). And I've changed the label of the button to "Show the popover".

You can still dismiss the popover by clicking the toggle button again, as it is a popover toggle by default. But now, even if people think the contents behind the popover are inert, it doesn't matter because that state can easily be escaped from.

2023-11-14 09:23 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +However, because the animated element is being promoted to the [top layer](/en-US/docs/Glossary/Top_layer) when shown and removed from the top layer when hidden (with [`display: none`](/en-US/docs/We
Updated

2023-11-14 12:10 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +
Agreed that we need to make this clear. I've added these notes in appropriate places. 

I've also added an explanatory section and an example to the `@starting-style` page to explain and demonstrate the behavior. I've linked the notes in other places to the example so it can be seen in action.

2023-11-14 12:12 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +```css
As mentioned earlier, I've added a note to explain what is happening, and further explanation and an example. I'd rather not mess with the styling of this example any further.

2023-11-14 12:13 UTC, chrisdavidmills commented on files/en-us/web/css/@starting-style/index.md
> +When the "Create new column" button is clicked, the `createColumn()` function is called. This creates a {{htmlelement("div")}} element with a randomly generated background color and a {{htmlelement("
updated

2023-11-14 12:16 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +  background-color: #ccc;
Updated description of example to say "color", not "opacity".

2023-11-14 12:16 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +  background-color: #eee;
see above comment.

2023-11-14 12:22 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +> **Note:** When animating using [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions), [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set to enable the
Updated, with a slight tweak. Saying "the above behavior" twice in quick succession seemed jarring, so I've changed the second instance to "This behavior"

2023-11-14 12:23 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +
done

2023-11-14 12:34 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +Note the `@starting-style` block used to define the transition starting styles, and the `display` and `overlay` properties included in the transition list, each with `allow-discrete` set on them. Not
I've used your first paragraph, but then edited it quite a bit. I didn't use the second one because I already included a note to cover this stuff, below the rendered example.

I don't want to mess with the colors in the example. Instead, I've linked to my new example in the @starting-style page that demonstrates the behavior.

2023-11-14 12:35 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +
This already happened in the comments above.

2023-11-14 12:38 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +The JavaScript serves to wire up the buttons to event handlers that show and close the `<dialog>`:
agreed; updated

2023-11-14 12:39 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +When animating a `<dialog>` with CSS animations, there are some differences to note from transitions:
updated

2023-11-14 12:45 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- You don't provide a `@starting-style`; instead, you provide the starting values (including the initial `display` value) in an explicit keyframe (using `0%` or `from`).
OK, updated.

2023-11-15 03:28 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +Each single-property transition describes the transition that should be applied to a single property or all properties. It includes:
```suggestion
Each single-property transition describes the transition that should be applied to a single property or `all` properties. It includes:
```

2023-11-15 03:30 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +  - the keyword `normal`
```suggestion
- zero or one value declaring whether to start transitions for properties whose animation behavior is [discrete](/en-US/docs/Web/CSS/CSS_animated_properties#discrete). The value, if present, is either the keyword `allow-discrete` or the keyword `normal`.
```

2023-11-15 03:33 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +In this case, {{cssxref("opacity")}} will transition with a duration of 400ms, but all other properties that change as the element changes state will transition with a duration of 200ms.
```suggestion
In this case, all the properties that change as the element changes state will transition with a duration of 200ms, except {{cssxref("opacity")}} , which will transition with a duration of 400ms.
```

2023-11-15 03:42 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +This is most significant in the cases of [`display`](/en-US/docs/Web/CSS/display), [`content-visibility`](/en-US/docs/Web/CSS/display), and [`overlay`](/en-US/docs/Web/CSS/overlay), the first two of
```suggestion
This is most significant in the cases of [`display`](/en-US/docs/Web/CSS/display), [`content-visibility`](/en-US/docs/Web/CSS/display), and [`overlay`](/en-US/docs/Web/CSS/overlay), which historically were not animatable. The ability of these elements to be transitioned means that it is fairly easy to create entry and exit animations, where an element is transitioned to and from a hidden state (which includes elements appearing in the [top layer](/en-US/docs/Glossary/Top_layer) such as [popovers](/en-US/docs/Web/API/Popover_API) or modal {{htmlelement("dialog")}} elements), or transitioned as soon as it is added to the DOM.
```
while the original is true, the "the first two" makes it sound like historically `overlay` was animateable. overlay has no history. readers don't know that. The only way it's animateable is if tb is set, so lets lump it all together, as historically, the property didn't exist, so was not animatable, so my edit is not wrong, while making the sentence shorter and doesn't create confusion.

2023-11-15 05:50 UTC, estelle requested changes
First half of transition-behavior. Changes are not minor. Will re-review when the example and subsequent content (which i did not review) are updated. Sorry.

2023-11-15 05:50 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +### Basic usage
Create a description section. Include the description of discrete animation type and the basic usage in the description instead of under examples. Something like:

> Properties with discrete animations change from one property value to the next 50% of the way thru the animation as defined by the transition-duration and transition-timing functions. When normally non-animatable properties are set to `allow-discrete`, the browser instantly transitions at either the start or end of the duration. For example, when transitioning `content-visibility` from `hidden` to `visible`, the value will flip to `visible` at `0%` of the animation duration so it is visible throughout. When transitioning `display` from `grid` to `none`, the value will flip to `none` at `100%` of the duration so it is visible throughout.

2023-11-15 05:50 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +  font-size: 1.2rem;
hide the html, font-size and padding.

2023-11-15 05:50 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +  transition:
use transition-behavior. That is what this page is.

2023-11-15 05:50 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +[popover]:popover-open::backdrop {
get rid of the backdrop. Make this example simple. also, popovers should not be modal, so this is not teaching best practices. If you want to transition backdrop, use dialog as an example. Or, remove from here, and create a different example.

2023-11-15 07:43 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +Each single-property transition describes the transition that should be applied to a single property or all properties. It includes:
I disagree with this change suggestion. In this case, "all" is part of English language, not a code term.

2023-11-15 07:45 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +  - the keyword `normal`
Sounds good; updated

2023-11-15 07:47 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +In this case, {{cssxref("opacity")}} will transition with a duration of 400ms, but all other properties that change as the element changes state will transition with a duration of 200ms.
updated

2023-11-15 07:49 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +This is most significant in the cases of [`display`](/en-US/docs/Web/CSS/display), [`content-visibility`](/en-US/docs/Web/CSS/display), and [`overlay`](/en-US/docs/Web/CSS/overlay), the first two of
Yup, agreed. Updated

2023-11-15 08:09 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +### Basic usage
Good call. I have added a Description section that covers this stuff. I have moved the large paragraph from the introduction to the description section, as it seemed to fit well there.

2023-11-15 08:11 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +  font-size: 1.2rem;
done

2023-11-15 08:14 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +  transition:
The "Basic usage" example explicitly shows the usage of the longhand property. The popover example then shows realistically how you'd actually use it. I don't see a problem with how this is currently presented.

2023-11-15 08:34 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +[popover]:popover-open::backdrop {
OK, backdrop is gone.

2023-11-15 19:35 UTC, estelle commented on files/en-us/web/css/overlay/index.md
> +
@chrisdavidmills I checked with Tab, the spec author: 

Me: Another question: the global CSS values are global, right? Even for overlay. 
Tab: Yes, every property accepts them

2023-11-15 22:53 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +  transition:
This is the transition-behavior page. We want to use the property that is the page topic in all the examples.

2023-11-15 22:57 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +### Basic usage
move "basic usage" to the description section.

2023-11-15 23:03 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +  transition: all 0.7s allow-discrete; */
```suggestion
  transition-property: opacity, transform, overlay, display;
  transition-duration: 0.7s;
  transition-behavior: allow-discrete; 
  /* Using the shorthand `transition` property, we would write:
    transition: 
      opacity 0.7s,
      transform 0.7s,
      overlay 0.7s allow-discrete,
      display 0.7s allow-discrete;
    or, even:
    transform: 0.7s allow-discrete;
  */
```
i have to insist that the property be used in the examples

2023-11-15 23:44 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
There links to these anchors need to be updated

2023-11-15 23:49 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +  - : Add `display` to the transitions list so that the `<dialog>` will remain as `display: block` for the duration of the transition, ensuring the other transitions are visible.
```suggestion
  - : Add `display` to the transitions list so that the `<dialog>` will remain as `display: block` (or other visible `display` value set on the dialog's open state) for the duration of the transition, ensuring the other transitions are visible.
```

2023-11-15 23:52 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +  - : Provides a set of starting values for properties set on the `<dialog>` that you want to transition from when it is first shown. This is needed to avoid unexpected behavior. By default, CSS tran
```suggestion
  - : Provides a set of starting values for properties set on the `<dialog>` that you want to transition from every time the dialog is opened. This is needed to avoid unexpected behavior. By default, CSS transitions only occur when a property changes from one value to another on a visible element; they are not triggered on elements' first style updates, or when the `display` type changes from `none` to another type.
```

2023-11-15 23:53 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +}
```suggestion
```

2023-11-16 08:08 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +
OK, thanks for checking this; added.

2023-11-16 08:14 UTC, chrisdavidmills commented on files/en-us/web/api/popover_api/using/index.md
> +    display: none;
Note added

2023-11-16 08:26 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +  transition: all 0.7s allow-discrete; */
OK, thanks. I'm fine with this suggestion as we are showing the shorthand equivalents in the comment. I've mostly used your suggestion, but with a bit of tweaking to the prose; I've also fixed the ultra-compact shorthand suggestion.

2023-11-16 08:33 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
I've grepped through the repo and can't find anywhere that links to this. Have you found a particular instance that is wrong?

2023-11-16 08:35 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +  - : Add `display` to the transitions list so that the `<dialog>` will remain as `display: block` for the duration of the transition, ensuring the other transitions are visible.
added

2023-11-16 08:38 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +  - : Provides a set of starting values for properties set on the `<dialog>` that you want to transition from when it is first shown. This is needed to avoid unexpected behavior. By default, CSS tran
added

2023-11-16 08:39 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +}
Sure; removed.

2023-11-16 15:49 UTC, OnkarRuikar commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
This example doesn't work in playground.

2023-11-16 15:49 UTC, OnkarRuikar commented on files/en-us/web/html/element/dialog/index.md
> +/*   Open state of the dialog */
```suggestion
/*   Open state of the dialog  */
```
To match other two spaced comments.

2023-11-16 19:58 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
line 192 (and the other link is a few lines lower) on this page

2023-11-16 20:42 UTC, estelle commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +This example demonstrates how [`display`](/en-US/docs/Web/CSS/display) and [`content-visibility`](/en-US/docs/Web/CSS/content-visibility) can be transitioned. This behavior is useful for creating ent
```suggestion
This example demonstrates how [`display`](/en-US/docs/Web/CSS/display) and [`content-visibility`](/en-US/docs/Web/CSS/content-visibility) can be transitioned. This behavior is useful for creating entry/exit animations where you want to for example remove a container from the DOM with `display: none`, but have it fade out with [`opacity`](/en-US/docs/Web/CSS/opacity), or some other exit animation, rather than disappearing immediately.
```
optional

2023-11-16 20:46 UTC, estelle commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) is used to provide a set of starting values for properties set on an element that you want to transition from when the element receives its
Every time you exit and then animate from `display: none;` the start style is used, because it is removed and put back into the dom. This covers that. With content-visibility, when it is animated the second time, does it start from start-styles each time? Or from the default state? If these two properties are different in this way, we should note that.

2023-11-16 21:15 UTC, estelle reviewed
review of transition behavior: I couldn't create a nested code comment, so my comment is the suggested edit

2023-11-16 21:15 UTC, estelle commented on files/en-us/web/css/transition-behavior/index.md
> +
This is my suggestion, but Github doesn't like nesting code in suggestions:

The `transition-behavior` property is only relevant when used in conjunction with other transition properties, notably {{cssxref("transition-property")}} and  {{cssxref("transition-duration")}}, as no transition occurs if no properties are animated over a non-zero duration of time.

```css
.card {
  transition-property: opacity, display;
  transition-duration: 0.25s;
  transition-behavior: allow-discrete;
}

.card.fade-out {
  opacity: 0;
  display: none;
}
```

The `transition-behavior` value can be included as part of a shorthand {{cssxref("transition")}} declaration. When included in the shorthand, when using or defaulting to `all` properties, the`allow-discrete` has no impact on regular animatable properties. The following CSS is equivalent to the longhand declarations above:

```css
.card {
  transition: all  0.25s allow-discrete;
}

.card.fade-out {
  opacity: 0;
  display: none;
}
```

2023-11-16 22:59 UTC, estelle commented on files/en-us/web/css/display/index.md
> +- [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set on `display` when it is transitioned to enable `display` transitions.
```suggestion
- [`transition-behavior: allow-discrete`](/en-US/docs/Web/CSS/transition-behavior) needs to be set on the {{cssxref("transition-property")}} declaration (or the {{cssxref("transition")}} shorthand) to enable `display` transitions.
```

2023-11-16 23:08 UTC, estelle commented on files/en-us/web/css/overlay/index.md
> +
```suggestion

The `overlay` property is only present in list of transitioned properties. As `overlay` is a user-agent controlled property, it is neither declared in the pre-transition or post-transition state.
```

We aren't including the overlay property as a property. We need to explain why. This is my attempt. You might have a better though.

2023-11-16 23:13 UTC, estelle commented on files/en-us/web/css/overlay/index.md
> +The **`overlay`** [CSS](/en-US/docs/Web/CSS) property specifies whether an element appearing in the [top layer](/en-US/docs/Glossary/Top_layer) (for example, a shown [popover](/en-US/docs/Web/API/Pop
```suggestion
The **`overlay`** [CSS](/en-US/docs/Web/CSS) property specifies whether an element appearing in the [top layer](/en-US/docs/Glossary/Top_layer) (for example, a shown [popover](/en-US/docs/Web/API/Popover_API) or modal {{htmlelement("dialog")}} element) is actually rendered in the top layer. This property is only relevant within a list of {{cssxref("transition-property")}} values, and only if `allow-discrete` is set as the {{cssxref("transition-behavior")}}.
```

2023-11-16 23:14 UTC, estelle commented on files/en-us/web/css/overlay/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
```suggestion
- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions) module
```

2023-11-16 23:20 UTC, estelle reviewed
content-visiblility page: Just an h3 title edit for an example (and the same edit in the rendering function call).

2023-11-16 23:20 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +### content-visibility animation example
```suggestion
### Animating content-visibility
```
it's in examples, so we don't need to add that to the header

2023-11-16 23:20 UTC, estelle commented on files/en-us/web/css/content-visibility/index.md
> +{{ EmbedLiveSample("content-visibility animation example", "100%", "300") }}
```suggestion
{{ EmbedLiveSample("Animating content-visibility", "100%", "300") }}
```

2023-11-17 00:13 UTC, estelle commented
see https://github.com/mdn/content/pull/29943#issuecomment-1807700427

2023-11-20 08:54 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
Ah, sorry about that; I managed to totally miss it. Fixed now.

2023-11-20 08:55 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +In the CSS, we include a `@starting-style` block that defines the transition starting styles for the `opacity` and `transform` properties, transition end styles on the `dialog[open]` state, and defau
Fixed; thanks!

2023-11-20 08:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +Note the `@starting-style` block used to specify the starting style for the transition, and the inclusion of the `display` property in the trainsitions list, with `allow-discrete` set on it.
fixed

2023-11-20 09:00 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +{{ EmbedLiveSample("Animating a popover", "100%", "200") }}
Ah, good catch; thanks! Fixed in next commit.

2023-11-20 09:01 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +{{ EmbedLiveSample("Animating a popover", "100%", "200") }}
fixed ;-)

2023-11-20 09:02 UTC, chrisdavidmills commented on files/en-us/web/css/transition-property/index.md
> +  transition-duration: 0.7s;
updated; thanks

2023-11-20 09:05 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +{{EmbedLiveSample("HTML-only_dialog", "100%", 200)}}
OK; can you file an issue to look at this separately? This is really a playground issue rather than an issue with my content update.

2023-11-20 09:06 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
added

2023-11-20 09:07 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +/*   Open state of the dialog */
updated

2023-11-20 09:08 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +This example demonstrates how [`display`](/en-US/docs/Web/CSS/display) and [`content-visibility`](/en-US/docs/Web/CSS/content-visibility) can be transitioned. This behavior is useful for creating ent
I don't think this is necessary; the text already says this is an example, rather than what always happens.

2023-11-20 13:00 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +
Ah, I see. So you are suggesting not putting this as an example, and moving it to the description section. Yup, sounds reasonable. Done.

2023-11-20 13:06 UTC, chrisdavidmills commented on files/en-us/web/css/transition-behavior/index.md
> +
Sounds good; added, with a few tweaks.

2023-11-20 13:09 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +
added

2023-11-20 13:11 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +The **`overlay`** [CSS](/en-US/docs/Web/CSS) property specifies whether an element appearing in the [top layer](/en-US/docs/Glossary/Top_layer) (for example, a shown [popover](/en-US/docs/Web/API/Pop
added

2023-11-20 13:11 UTC, chrisdavidmills commented on files/en-us/web/css/overlay/index.md
> +- [CSS transitions](/en-US/docs/Web/CSS/CSS_transitions)
added

2023-11-20 13:16 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +### content-visibility animation example
Good call. I've changed this heading, and all the links/references to it.

2023-11-20 13:16 UTC, chrisdavidmills commented on files/en-us/web/css/content-visibility/index.md
> +{{ EmbedLiveSample("content-visibility animation example", "100%", "300") }}
changed

2023-11-20 13:33 UTC, chrisdavidmills commented on files/en-us/web/css/css_transitions/using_css_transitions/index.md
> +- [`@starting-style`](/en-US/docs/Web/CSS/@starting-style) is used to provide a set of starting values for properties set on an element that you want to transition from when the element receives its
Heh, I'm really glad you brought this up. I tested `content-visibility`, and it turns out it doesn't need `@starting-style`s; `content-visibility` doesn't actually remove the content from the DOM. It transitions from the default state styles each time. You can see proof here:

https://content-visibility-transition-test.glitch.me/

(The source Glitch is at https://glitch.com/edit/#!/content-visibility-transition-test?path=index.html%3A36%3A8, in case you want to remix/play with it).

I'll make the necessary changes to all pages now, in a separate commit.

2023-11-20 15:20 UTC, estelle approved these changes
Squeeeeeeeeeeeee! 🎉

2023-11-20 15:36 UTC, dipikabh approved these changes

2023-11-20 15:37 UTC, merged