Update index.md
mdn/content pull request #29947
Opened 2023-10-31 20:31 UTC by j15k

Changed somedomain.com to example.com, removed (X)HTML slash from br in example.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-11-01 09:04 UTC, chrisdavidmills approved these changes
@j15k Thank you for the contribution! I agree with these changes, however, the automatic linter is failing because it is expecting XHTML-style empty elements. I'll talk to the other MDN folks to find out why this decision was made.

2023-11-01 10:01 UTC, j15k commented
On the home page, https://whatwg.org/ refers to https://whatwg.org/validator/ as [HTML checker](https://whatwg.org/validator/). The validator uses https://validator.w3.org/nu/ which reports, e.g.:

> Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

Also see: https://www.ditig.com/html-void-elements and https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags (where it says "Self-closing tags (`<tag />`) do not exist in HTML.")

2023-11-01 10:11 UTC, chrisdavidmills commented
This is quite 

> On the home page, https://whatwg.org/ refers to https://whatwg.org/validator/ as [HTML checker](https://whatwg.org/validator/). The validator uses https://validator.w3.org/nu/ which reports, e.g.:
> 
> > Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).
> 
> Also see: https://www.ditig.com/html-void-elements and https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags (where it says "Self-closing tags (`<tag />`) do not exist in HTML.")

I don't disagree with any of this. There was a big discussion about this issue a while ago: https://github.com/orgs/mdn/discussions/242#discussioncomment-4274011

The conclusion reached is that the MDN dev team wants to use prettier on the site for lining, therefore we are stuck with trailing slashed for now. There's not a lot I can do about this.

2023-11-01 10:41 UTC, j15k commented
Urghh, ... I did'nt want to hit that beehive. Messy. Alright, thanks for the update.

2023-11-01 11:41 UTC, chrisdavidmills commented
> Urghh, ... I did'nt want to hit that beehive. Messy. Alright, thanks for the update.

Yeah, it is a bit messy ;-(

Do you want me to make the linter changes and get the URL change merged? That is still a useful change.

2023-11-01 13:17 UTC, OnkarRuikar commented on files/en-us/web/html/element/address/index.md
> +  <a href="mailto:webmaster@example">contact webmaster</a>.<br>
```suggestion
  <a href="mailto:webmaster@example.com">contact webmaster</a>.<br>
```

2023-11-01 13:29 UTC, OnkarRuikar commented
Self closing with `/` is expected on MathML and SVG elements and has no effect on HTML void elements: [[ref](https://html.spec.whatwg.org/multipage/syntax.html#start-tags)]
> 6. Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/), which on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) marks the start tag as self-closing. On [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it does not mark the start tag as self-closing but instead is unnecessary and has no effect of any kind. For such void elements, it should be used only with caution — especially since, if directly preceded by an [unquoted attribute value](https://html.spec.whatwg.org/multipage/syntax.html#unquoted), it becomes part of the attribute value rather than being discarded by the parser.

2023-11-02 19:57 UTC, estelle requested changes
typo

2023-11-02 19:57 UTC, estelle commented on files/en-us/web/html/element/address/index.md
> +  <a href="http://www.exmple.com/contact">www.example.com</a>.<br>
```suggestion
  <a href="http://www.example.com/contact">www.example.com</a>.<br />
```

2023-11-03 13:00 UTC, caugner commented on files/en-us/web/html/element/address/index.md
> +  <a href="http://www.exmple.com/contact">www.example.com</a>.<br>
```suggestion
  <a href="http://www.example.com/contact">www.example.com</a>.<br>
```

2023-11-03 14:30 UTC, chrisdavidmills approved these changes
LGTM, let's merged this.

2023-11-03 14:32 UTC, chrisdavidmills commented
Ah, I see what's going on. I think you need to approve this one so we can merge it, @estelle.

2023-11-03 15:13 UTC, estelle approved these changes

2023-11-03 15:13 UTC, merged