fix KeyboardLayoutMap
mdn/content pull request #29957
Opened 2023-11-01 13:08 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-11-01 21:55 UTC, wbamberg reviewed
Thank you for the PR, @skyclouds2001 ! But there's more work needed in here. Changing the page type is good, but the page itself is written as if this is a property (e.g. it's described as a property, it doesn't have "Parameters" or "Return value", etc.).

Note that it's a bit unsettled how we should document members of maplike and setlike interfaces: sometimes we document the methods and properties fully (e.g. https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport/entries), sometimes we just list them in the interface main page and link to the `Map`/`Set` object (e.g. https://developer.mozilla.org/en-US/docs/Web/API/EventCounts). 

https://github.com/openwebdocs/project/issues/159 is supposed to help resolve this but it's not ready yet.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/map#map-like_browser_apis is also a helpful page to link to in places like this :).

2023-11-03 04:06 UTC, skyclouds2001 commented
> Thank you for the PR, @skyclouds2001 ! But there's more work needed in here. Changing the page type is good, but the page itself is written as if this is a property (e.g. it's described as a property, it doesn't have "Parameters" or "Return value", etc.).
> 
> Note that it's a bit unsettled how we should document members of maplike and setlike interfaces: sometimes we document the methods and properties fully (e.g. https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport/entries), sometimes we just list them in the interface main page and link to the `Map`/`Set` object (e.g. https://developer.mozilla.org/en-US/docs/Web/API/EventCounts).
> 
> [openwebdocs/project#159](https://github.com/openwebdocs/project/issues/159) is supposed to help resolve this but it's not ready yet.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/map#map-like_browser_apis is also a helpful page to link to in places like this :).

Yes, and this may relate to https://github.com/mdn/content/issues/6891

2023-12-09 03:42 UTC, skyclouds2001 commented on files/en-us/web/api/keyboardlayoutmap/entries/index.md
> +The **`entries()`** method of the {{domxref("KeyboardLayoutMap")}} interface returns a new [Iterator](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator) object that contains the `[key, val
```suggestion
The **`entries()`** method of the {{domxref("KeyboardLayoutMap")}} interface returns a new [Iterator](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator) object that contains the key/value pairs, in the same order as that provided by a {{jsxref("Statements/for...in", "for...in")}} loop (the difference being that a `for-in` loop enumerates properties in the prototype chain as well).
```

2023-12-09 06:14 UTC, teoli2003 requested changes
@skyclouds2001 This is a great catch and essential work, long due! Thank you!

As this PR defines the page structure for these maplike interfaces, it is essential to take some time to carefully review them, as these structures will be reused for the 5-6 other such interfaces (that need them). That way, we won't do this work each time.

A few additions that I would like to see:

- Adding a `spec-url` entry in the FrontMatter YAML, like for [`Hightlight.entries()`](https://developer.mozilla.org/en-US/docs/Web/API/Highlight/entries) – [`Hightlight`](https://developer.mozilla.org/en-US/docs/Web/API/Highlight) is a set-like object – that links to the `Set.entries()` definition. Same for all other pages, to their relevant definitions, of course. Ultimately, we should store it in BCD, but I don't see a need to couple both discussions – I know there is no consensus between BCD peers 😉  – and hold this PR more than necessary.
- An example for each method. They will be similar, except in how the object is created. `Highlight`'s methods have most of them written and are a good place to start.

Once this PR is merged, I think we should update the meta-documentation for these `setlike` and `maplike` pages, so we can refer writers when new such interfaces have to be added.

I'm really excited about this work. Thanks a lot for tackling this.

2023-12-09 13:28 UTC, skyclouds2001 commented on files/en-us/web/api/keyboardlayoutmap/has/index.md
> +The following example check whether the location- or layout-specific string associated with the keyboard code that corresponds to the 'W' key on an English QWERTY keyboard existed.
```suggestion
The following example checks whether the location- or layout-specific string associated with the keyboard code that corresponds to the 'W' key on an English QWERTY keyboard existes.
```

2023-12-10 06:30 UTC, teoli2003 commented on files/en-us/web/api/keyboardlayoutmap/entries/index.md
> +    console.log(`${code} keyboard code represents ${key} key`)
```suggestion
    console.log(`${code} keyboard code represents ${key} key`);
```

2023-12-18 08:44 UTC, teoli2003 approved these changes
This looks good to me. @skyclouds2001 Do you want to update the other set-like and map-like interfaces with similar pages?

If you want, I can prepare an issue with the list of such interfaces.

2023-12-18 08:44 UTC, merged

2023-12-18 11:51 UTC, skyclouds2001 commented
> This looks good to me. @skyclouds2001 Do you want to update the other set-like and map-like interfaces with similar pages?
> 
> If you want, I can prepare an issue with the list of such interfaces.

I'd love to do it!