Cookbook layout: contribute page
mdn/content pull request #29993
Opened 2023-11-02 17:58 UTC by estelle

Updated the how to contribute to the MDN cookbook. 
part of openwebdocs/project#184.

2023-11-09 00:00 UTC, dipikabh commented
Apologies, @estelle. I haven't been able to review this yet. Since I'll be out of office next week, I don't want to hold you up with a review in between if I start now. It might be best to have someone else take a look.

2023-11-12 02:30 UTC, mathewhodson commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +Also, add a link to the new recipe in the top-level [Layout Cookbook page](/en-us/web/css/layout_cookbook/).
The bot is reporting a link flaw because of the trailing slash.

2023-11-13 08:47 UTC, estelle commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +Also, add a link to the new recipe in the top-level [Layout Cookbook page](/en-us/web/css/layout_cookbook/).
```suggestion
Also, add a link to the new recipe in the top-level [Layout Cookbook page](/en-us/web/css/layout_cookbook).
```

2023-11-22 15:36 UTC, dipikabh commented
Am back and looking at this now 🙂

2023-11-22 16:57 UTC, dipikabh requested changes
Thanks for updating this page, @estelle. I've included some edit suggestions.

2023-11-22 16:57 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +Make a [PR](/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request) on the [CSS Examples repo](https://github.com/mdn/css-examples). This way, we can help you with any changes to the example tha
Shouldn't the PR link here point to the PRs in that repo? If we want, we can add a separate sentence about general guidelines for opening pull requests
```suggestion
Open a [pull request (PR)](https://github.com/mdn/css-examples/pulls) on the [CSS Examples repo](https://github.com/mdn/css-examples). This allows us to help you with any changes to the example that may be needed before you create your page. Plus, the example will need to be live to be included. This is why it makes sense to first create the code examples, and then the explanatory guide. In your PR, explain the pattern and what you are demonstrating.
```

2023-11-22 16:57 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +Once your example is merged, you can [open a pull request](/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request) to create a new page in the [Layout Cookbook directory](https://github.com/mdn/
```suggestion
After your example PR is merged, open a pull request to create a new page in the [Layout Cookbook directory](https://github.com/mdn/content/tree/main/files/en-us/web/css/layout_cookbook). See our [guidelines for opening a pull request](/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request).
```

2023-11-22 16:57 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +If you have any questions or want someone to take a look at your page, get in touch via any [communication channel](/en-US/docs/MDN/Community/Communication_channels).
```suggestion
If you have any questions or want someone to take a look at your page, get in touch via any of our [communication channels](/en-US/docs/MDN/Community/Communication_channels).
```

2023-11-22 20:20 UTC, estelle commented
Welcome back @dipikabh and thank you for the review.
I made all the suggested changes.

Thanks!

2023-11-22 23:41 UTC, dipikabh approved these changes
Thanks! A few more changes are needed. But its looking in good shape, so leaving my approval. Please feel free to merge after the updates.

2023-11-22 23:41 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +5. [Add your content to MDN](#5-create-your-page)
Checked these links in the local preview. The hyphens need to be underscores. Plus there is a period after the numbers in the headings

```suggestion
1. [Build a pattern](#1._build_a_pattern)
2. [Create a live example](#2._create_a_live_example)
3. [Create a downloadable version](#3._create_a_downloadable_version)
4. [Open a pull request](#4._open_a_pull_request_with_your_example)
5. [Add your content to MDN](#5._create_your_page)
```

2023-11-22 23:41 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +Open a [pull request (PR)](/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request) on the [CSS Examples repo](https://github.com/mdn/css-examples/pulls). This allows us to help you with any chan
- Removed extra line
- Updated this sentence "This is why it makes sense to first create the code examples and then the explanatory guide."
- Moving the PR link to the end
```suggestion
Open a pull request (PR) on the [CSS Examples repo](https://github.com/mdn/css-examples/pulls). This allows us to help you with any changes to the example that may be needed before you create your page. Plus, the example will need to be live to be included. This is why it makes sense to first create the code examples and then the explanatory guide. In your PR, explain the pattern and what you are demonstrating. See our [guidelines for opening a pull request](/en-US/docs/MDN/Community/Pull_requests#open_a_pull_request).
```

2023-11-22 23:41 UTC, dipikabh commented on files/en-us/web/css/layout_cookbook/contribute_a_recipe/index.md
> +After your example PR is merged, open a pull request to create a new page in the [Layout Cookbook directory](https://github.com/mdn/content/tree/main/files/en-us/web/css/layout_cookbook). See our [gu
Moving PR guideline link to the previous step
```suggestion
After your example PR is merged, open a pull request to create a new page in the [Layout Cookbook directory](https://github.com/mdn/content/tree/main/files/en-us/web/css/layout_cookbook).
```

2023-11-23 08:40 UTC, merged

2023-11-24 01:13 UTC, dipikabh commented
Argh, my bad for removing the required blank line! Thanks for fixing @teoli2003.