clarify webp image format support on safari
mdn/content pull request #30039
Opened 2023-11-05 05:09 UTC by jasonren0403

### Description

similar changes as #29353 

### Motivation

### Additional details

### Related issues and pull requests

2023-11-05 07:22 UTC, pepelsbey requested changes
Good catch! I’d go a bit further here though. This note sounds a bit complicated. The main point here is that image codecs support in Safari depends on OS version, not the browser version. It’s less relevant for iOS/iPadOS since Safari version strictly depends on OS version, but it becomes more obvious on macOS.

2023-11-07 05:14 UTC, jasonren0403 commented
> Good catch! I’d go a bit further here though. This note sounds a bit complicated. The main point here is that image codecs support in Safari depends on OS version, not the browser version. It’s less relevant for iOS/iPadOS since Safari version strictly depends on OS version, but it becomes more obvious on macOS.

I'm not quite familar with this field(and also poor English for documenting this), could you directly suggest what should be written here 🤔

2023-11-23 09:46 UTC, teoli2003 commented on files/en-us/web/media/formats/image_types/index.md
> +> **Note:** Despite Apple [announcing support for WebP in Safari 14](https://developer.apple.com/videos/play/wwdc2020/10663/?time=1174), Safari versions earlier than 16.0 don't display `.webp` images
I went ahead and crafted a potential note here:
```suggestion
> **Note:** On Safari for MacOS, WebP support depends on both Safari and MacOS versions. You need Safari 14 or later as well as MacOS Big Sur (11) or a more recent version.
```

2023-11-23 09:48 UTC, teoli2003 commented on files/en-us/web/media/formats/image_types/index.md
> +> **Note:** Despite Apple [announcing support for WebP in Safari 14](https://developer.apple.com/videos/play/wwdc2020/10663/?time=1174), Safari versions earlier than 16.0 don't display `.webp` images
@jasonren0403, have a look (and eventually commit the suggestion), then re-request review by @pepelsbey.

2023-11-23 11:19 UTC, pepelsbey commented on files/en-us/web/media/formats/image_types/index.md
> +> **Note:** Despite Apple [announcing support for WebP in Safari 14](https://developer.apple.com/videos/play/wwdc2020/10663/?time=1174), Safari versions earlier than 16.0 don't display `.webp` images
@teoli2003 officially, it’s macOS, starting with lowercase “m”.

2023-11-23 12:31 UTC, teoli2003 commented on files/en-us/web/media/formats/image_types/index.md
> +> **Note:** Despite Apple [announcing support for WebP in Safari 14](https://developer.apple.com/videos/play/wwdc2020/10663/?time=1174), Safari versions earlier than 16.0 don't display `.webp` images
Fixed. (I hate brands that doesn't start with a capital, but…)

2023-11-23 13:59 UTC, jasonren0403 commented on files/en-us/web/media/formats/image_types/index.md
> +> **Note:** Despite Apple [announcing support for WebP in Safari 14](https://developer.apple.com/videos/play/wwdc2020/10663/?time=1174), Safari versions earlier than 16.0 don't display `.webp` images
seems good 🤔

2023-11-23 14:24 UTC, pepelsbey approved these changes
LGTM! Thank you :)

2023-11-23 15:11 UTC, merged