fix(css): add color space info to gradient pages
mdn/content pull request #30047
Opened 2023-11-05 11:27 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/30027

2023-11-09 00:14 UTC, estelle commented on files/en-us/web/css/gradient/repeating-radial-gradient/index.md
> +### Interpolation in polor color space with hue interpolation methods
The title is kind of too long; especially if there is no content between the title and the example.

This example doesn't add anything for the person trying to learn about `repeating-radial-gradient`, which is the topic of the page. We can either remove this example from the page, or update it. Take a look at the other examples on the page for examples on how to tweak this.
Also, i think we can hide the HTML.  If we don't, we should the h4 headers.

2023-11-23 09:56 UTC, teoli2003 commented on files/en-us/web/css/gradient/repeating-radial-gradient/index.md
> +### Interpolation in polor color space with hue interpolation methods
@OnkarRuikar There is nothing called "polar color space" or "rectangular color space". These are coordinate systems.

It should be "polar coordinates", "rectangular coordinates" ("Cartesian coordinates" is the 3rd kind of coordinate system possible).

One way to work around long titles is to use only _Interpolation with hue interpolation methods_ and to add an introductory sentence to the example.

2023-11-23 09:57 UTC, teoli2003 requested changes
Fix "color space" -> "coordinates" where needed.

2023-11-23 15:07 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/repeating-radial-gradient/index.md
> +### Interpolation in polor color space with hue interpolation methods
> There is nothing called "polar color space" or "rectangular color space". These are coordinate systems.

Specs do use these terms https://drafts.csswg.org/css-color/#GM-chroma and https://drafts.csswg.org/css-color/#ex-premultiplied-lch

> One way to work around long titles is to use only Interpolation with hue interpolation methods and to add an introductory sentence to the example.

This sounds nice.

2023-11-23 15:08 UTC, OnkarRuikar commented
> Fix "color space" -> "coordinates" where needed.

Apart from above mentions MDN also uses these terms https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-method#syntax

2023-11-27 15:19 UTC, estelle requested changes
made some suggestions on the first example, which are valid for all other examples. Consider changing the colors for each example so we have different examples of long and short color arcs.

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +### Interpolation with hue interpolation methods
```suggestion
### Hue interpolation methods
```

or "Interpolating with hue"

including interpolation twice in a header seems excessive

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +{{EmbedLiveSample('Interpolation with hue interpolation methods', 240, 200)}}
if changed, change this too.

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter) so color goes straight from red to blue taking short arc on [color wheel](/en-US/docs/Glossary/C
```suggestion
The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the right uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +In this example for interpolation hsl color system is being used and hue is being interpolated.
```suggestion
In this example, the hsl color system is being used and hue is being interpolated.
```
link hsl and hue

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +The box on the top uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter) so color goes straight from red to blue taking short arc on [color wheel](/en-US/docs/Glossary/Co
same edits as the example above. Do you want to use different colors so we have two slightly different short and long examples?

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +### Interpolation with hue interpolation methods
same edit

2023-11-27 15:19 UTC, estelle commented on files/en-us/web/css/gradient/radial-gradient/index.md
> +### Interpolation with hue interpolation methods
same edits as above

2023-11-28 15:55 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +### Interpolation with hue interpolation methods
Using "Interpolating with hue".

2023-11-28 15:55 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +{{EmbedLiveSample('Interpolation with hue interpolation methods', 240, 200)}}
done

2023-11-28 16:06 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter) so color goes straight from red to blue taking short arc on [color wheel](/en-US/docs/Glossary/C
done

2023-11-28 16:12 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +In this example for interpolation hsl color system is being used and hue is being interpolated.
done

2023-11-28 16:14 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +The box on the top uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter) so color goes straight from red to blue taking short arc on [color wheel](/en-US/docs/Glossary/Co
Updated all the docs with above review comments. Examples with different colors would've made sense if the examples were on one page in same section. On separate pages readers won't even notice.

2023-11-28 16:15 UTC, OnkarRuikar commented on files/en-us/web/css/gradient/radial-gradient/index.md
> +### Interpolation with hue interpolation methods
Updated all the pages with above review comments.

2023-11-29 19:24 UTC, estelle approved these changes
Thanks!

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/conic-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs
```suggestion
The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on the [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the right uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/linear-gradient/index.md
> +In this example for interpolation [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```suggestion
In this example for interpolation, [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/radial-gradient/index.md
> +In this example for interpolation [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```suggestion
In this example for interpolation, [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/radial-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs
```suggestion
The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning the color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the right uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-conic-gradient/index.md
> +In this example for interpolation [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```suggestion
In this example for interpolation, [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-conic-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs
```suggestion
The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on the [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the right uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-linear-gradient/index.md
> +In this example for interpolation [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```suggestion
In this example for interpolation, [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-linear-gradient/index.md
> +The box on the top uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs/
```suggestion
The box on the top uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning the color goes from red to blue using the shorter arc on the [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the bottom uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-radial-gradient/index.md
> +In this example for interpolation [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```suggestion
In this example for interpolation, [hsl](/en-US/docs/Web/CSS/color_value/hsl) color system is being used and [hue](/en-US/docs/Web/CSS/hue) is being interpolated.
```

2023-11-29 19:24 UTC, estelle commented on files/en-us/web/css/gradient/repeating-radial-gradient/index.md
> +The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning color goes straight from red to blue using the shorter arc on [color wheel](/en-US/docs
```suggestion
The box on the left uses [shorter interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#shorter), meaning the color goes from red to blue using the shorter arc on [color wheel](/en-US/docs/Glossary/Color_wheel). The box on the right uses [longer interpolation](/en-US/docs/Web/CSS/hue-interpolation-method#longer), meaning the color goes from red to blue using the longer arc, traversing through greens, yellows, and oranges.
```

2023-11-29 19:26 UTC, estelle approved these changes

2023-11-30 07:02 UTC, teoli2003 approved these changes
👍

2023-11-30 07:02 UTC, merged