Color
mdn/content pull request #3005
Opened 2021-03-10 16:33 UTC by jpmedley

Checklist — To help your pull request get merged faster, please do following:

1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [ ] Link to any other resources that you think might be useful in reviewing your PR.

2021-03-10 20:19 UTC, rachelandrew commented on files/en-us/learn/css/first_steps/how_css_works/index.html
> +  color: blue; /* incorrect spelling of the color property */
this one is supposed to be incorrect - it's a demo :)

2021-03-10 20:19 UTC, rachelandrew commented on files/en-us/mdn/guidelines/writing_style_guide/index.html
> +<p>For questions of spelling, please refer to <a href="http://www.dictionary.com/">Dictionary.com</a>. The spelling checker for this site uses American English. Please do not use variant spellings (e
this is a note telling us to use the US spelling.

2021-03-10 20:20 UTC, rachelandrew commented on files/en-us/learn/css/first_steps/how_css_works/index.html
> +  color: blue; /* incorrect spelling of the color property */
```suggestion
  colour: blue; /* incorrect spelling of the color property */
```

2021-03-10 20:21 UTC, rachelandrew commented on files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.html
> +   <li><a class="external external-icon" href="https://github.com/mdn/webextensions-examples/tree/master/favorite-color">favorite-color</a></li>
this is a URL so probably shouldn't be caught unless it is also being changed

2021-03-10 20:23 UTC, rachelandrew commented on files/en-us/mozilla/add-ons/webextensions/internationalization/index.html
> +         <li><code>{ "colorLocalised": { "message": "color", "description": "Color." }, ... }</code></li>
seems a localization example, I think the UK spelling may be intentional.

2021-03-10 20:23 UTC, rachelandrew commented on files/en-us/mozilla/add-ons/webextensions/internationalization/index.html
> + <li>If the extension calls <code>getMessage("colorLocalised")</code>, it will return "color".</li>
also localization

2021-03-10 20:24 UTC, rachelandrew commented on files/en-us/tools/page_inspector/how_to/examine_and_edit_css/index.html
> +<p>A warning icon appears next to unsupported CSS properties or rules that have invalid values. This can help you understand why certain styles are not being applied. In the following example, a spel
also intentional as an example

2021-03-10 20:24 UTC, rachelandrew commented on files/en-us/mozilla/firefox/releases/54/index.html
> + <li>Transparent colors (i.e. those with an alpha channel of 0) were being serialized to the <a href="/en-US/docs/Web/CSS/color_value#transparent_keyword"><code>transparent</code> color keyword</a> i
URL

2021-03-10 20:25 UTC, rachelandrew commented on files/en-us/web/accessibility/information_for_web_authors/index.html
> + <li><a class="ex-ref" href="http://juicystudio.com/services/colorcontrast.php#contrast">Color contrast analyzer</a> by Juicy Studio
URL

2021-03-10 20:25 UTC, rachelandrew commented on files/en-us/web/accessibility/information_for_web_authors/index.html
> +  <p>How can a web author establish easily and quickly if the background color and foreground (text) color in use in his webpages have sufficient color contrast difference and sufficient color bright
URL

2021-03-10 20:28 UTC, rachelandrew requested changes
A few URLs and also intentional use of UK spelling have been caught here.

I'm also a little nervous about updated naming in code especially where it links to an example somewhere which presumably uses the UK spelling. Inconsistency is probably worse than Britishness.

2021-03-11 00:17 UTC, nschonni requested changes
There may be a few ones you caught in here, but there have been a few passes on these words already and most of this are changing intentional spellings that highlight issues or are names of tools/products

2021-03-11 00:17 UTC, nschonni commented on files/en-us/learn/css/first_steps/how_css_is_structured/index.html
> +<p><strong>Important</strong>: In CSS (and other web standards), it has been agreed that US spelling is the standard where there is language variation or uncertainty. For example, <code>color</code>
It's spelled here as an example of what not to do

2021-03-11 00:17 UTC, nschonni commented on files/en-us/learn/common_questions/design_for_all_types_of_users/index.html
> +<p><img alt="Color contrast on this page: excellent!" src="color-contrast.png"></p>
You can't change this without renaming the PNG itself

2021-03-15 17:11 UTC, jpmedley commented
Fixed overcorrection of "color". Please take another look.

2021-03-15 18:23 UTC, nschonni commented on files/en-us/learn/css/first_steps/how_css_is_structured/index.html
> +<p><strong>Important</strong>: In CSS (and other web standards), it has been agreed that US spelling is the standard where there is language variation or uncertainty. For example, <code>colour</code>
Thanks for fixing the one I broke 😆

2021-03-15 18:25 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.html
> +   <li><a class="external external-icon" href="https://github.com/mdn/webextensions-examples/tree/master/favorite-colour">favorite-colour</a></li>
This is the working link
```suggestion
   <li><a class="external external-icon" href="https://github.com/mdn/webextensions-examples/tree/master/favourite-colour">favorite-colour</a></li>
```

2021-03-15 18:28 UTC, nschonni commented on files/en-us/web/accessibility/information_for_web_authors/index.html
> +  <p>How can a web author establish easily and quickly if the background color and foreground (text) color in use in his webpages have sufficient color contrast difference and sufficient color bright
```suggestion
  <p>How can a web author establish easily and quickly if the background color and foreground (text) color in use in his webpages have sufficient color contrast difference and sufficient color brightness difference? <a class="ex-ref" href="http://juicystudio.com/services/colourcontrast.php#contrast">Color contrast analyzer</a> is an excellent tool for such task. Effective color contrast and effective color brightness difference have a <strong>decisive importance for reading</strong>, furthermore for people with partial color deficiency (see the excellent examples in <a class="ex-ref" href="https://www.lighthouseguild.org/healthcare-professionals/elearning/low-vision-resources/effective-color-contrast-and-making-text-legible/">Effective Color Contrast</a> by Lighthouse International). A study has established that <a class="ex-ref" href="https://msdn.microsoft.com/en-us/library/bb263953.aspx">about 8 percent of all men have some form of color deficiency</a>. Color contrast analyzer algorithm is based on the formula provided in <a class="ex-ref" href="https://www.w3.org/TR/AERT#colour-contrast">Techniques For Accessibility Evaluation And Repair Tools</a> from W3C.</p>
```

2021-03-15 18:29 UTC, nschonni commented on files/en-us/web/accessibility/seizure_disorders/index.html
> +	<li><a href="https://www.iso.org/obp/ui/#iso:std:iec:61966:-2-2:ed-1:v1:en">IEC 61966-2-2:2003(en)</a> Multimedia systems and equipment — color measurement and management — Part 2-2: color managemen
Original is correct, as it's the title of the document

2021-03-16 15:41 UTC, jpmedley commented on files/en-us/learn/css/first_steps/how_css_is_structured/index.html
> +<p><strong>Important</strong>: In CSS (and other web standards), it has been agreed that US spelling is the standard where there is language variation or uncertainty. For example, <code>colour</code>
😆

2021-03-16 15:51 UTC, jpmedley commented
@nschonni I think I got everything. (I hope.)

2021-03-16 16:46 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/implement_a_settings_page/index.html
> +   <li><a href="https://github.com/mdn/webextensions-examples/tree/master/favorite-colour">favorite-colour</a></li>
I think you need to do a find/replace to change all these back to "favourite-colour", since it's the name of the tool (and these links are broken). Probably the example code as well, as I'm not sure if it also depends on the spelling there

2021-03-16 16:46 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/native_manifests/index.html
> +<p>Given this JSON manifest, the <code>favorite-color-examples@mozilla.org</code> extension could access the data using code like this:</p>
I'm guessing the email address shouldn't be changed

2021-03-16 16:47 UTC, nschonni commented on files/en-us/web/accessibility/seizure_disorders/index.html
> +	<li><a href="https://www.iso.org/obp/ui/#iso:std:iec:61966:-2-2:ed-1:v1:en">IEC 61966-2-2:2003(en)</a> Multimedia systems and equipment — colour measurement and management — Part 2-2: colour managem
Think this one needs to be undone, since it's lowercase in the title now

2021-03-16 16:49 UTC, nschonni commented on files/en-us/web/accessibility/aria/forms/basic_form_hints/index.html
> +  setElementBordercolor(emailElement, valid); // sets the border to red if second arg is false
Not sure were this is defined originally, but I'm guessing it should stay camelCase if it can be renamed
```suggestion
  setElementBorderColor(emailElement, valid); // sets the border to red if second arg is false
```

2021-03-16 20:05 UTC, jpmedley commented
Ready for you again. Sorry for all the trouble.

2021-03-16 20:13 UTC, nschonni reviewed
Just flagged all the "favourite-colour" lines that I think need to revert, rest looks good

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/native_manifests/index.html
> +  &quot;name&quot;: &quot;favourite-color-examples@mozilla.org&quot;,
Not sure if this is a real email that needs to stay as-is

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/native_manifests/index.html
> +<p>Given this JSON manifest, the <code>favourite-color-examples@mozilla.org</code> extension could access the data using code like this:</p>
Not sure if this is a real email that needs to stay as-is

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.html
> +  "name": "favorite-color-examples@mozilla.org",
Not sure if this is a real email that needs to stay as-is

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.html
> +<p>Given this manifest, the "favorite-color-examples@mozilla.org" extension could access the data using code like this:</p>
Not sure if this is a real email that needs to stay as-is

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.html
> +   <li><a class="external external-icon" href="https://github.com/mdn/webextensions-examples/tree/master/favourite-colour">favorite-colour</a></li>
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/get/index.html
> +<p>This example tries to get the cookie named "favorite-color", associated with the URL for the currently active tab:</p>
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/get/index.html
> +    name: "favorite-color"
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/getall/index.html
> +<p>In the following snippet, we are making a call to get all of the cookies the browser currently has stored that have a name of "favorite-color". When the result is returned, we are printing the val
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/getall/index.html
> +  name: "favorite-color"
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/remove/index.html
> +<p>This example tries to remove the cookie named "favorite-color", whose URL matches the URL of the document hosted by the currently active tab:</p>
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/remove/index.html
> +    name: "favorite-color"
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/set/index.html
> +    name: "favorite-color",
Undo

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>The <a href="https://github.com/mdn/webextensions-examples">webextensions-examples</a> repository on GitHub includes the <a href="https://github.com/mdn/webextensions-examples/tree/master/favorite
Undo, breaks link

2021-03-16 20:13 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>To create an options page, write an HTML file defining the page. This page can include CSS and JavaScript files, like a normal web page. This page, from the <a href="https://github.com/mdn/webexte
Undo, breaks links

2021-03-17 14:00 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/native_manifests/index.html
> +  &quot;name&quot;: &quot;favourite-color-examples@mozilla.org&quot;,
It's an example. Unless it contains a link or a title from another property, it seems like it should follow rules for text.

2021-03-17 14:06 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.html
> +   <li><a class="external external-icon" href="https://github.com/mdn/webextensions-examples/tree/master/favourite-colour">favorite-colour</a></li>
Fixed.

2021-03-17 14:08 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/cookies/get/index.html
> +<p>This example tries to get the cookie named "favorite-color", associated with the URL for the currently active tab:</p>
This is defined by the example. Seems like it should follow the requirement to use US spelling.

2021-03-17 14:10 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>The <a href="https://github.com/mdn/webextensions-examples">webextensions-examples</a> repository on GitHub includes the <a href="https://github.com/mdn/webextensions-examples/tree/master/favorite
Fixed.

2021-03-17 14:11 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>To create an options page, write an HTML file defining the page. This page can include CSS and JavaScript files, like a normal web page. This page, from the <a href="https://github.com/mdn/webexte
Fixed.

2021-03-17 14:18 UTC, jpmedley commented
I've fixed the broken links. Why wouldn't identifiers in code examples use U.S. spelling?

2021-03-18 01:35 UTC, nschonni reviewed
I haven't gone through the demo code enough to say if the cookie name is expected in that code. Also don't know if that email address is a real Mozilla one or not

2021-03-18 01:35 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>To create an options page, write an HTML file defining the page. This page can include CSS and JavaScript files, like a normal web page. This page, from the <a href="https://github.com/mdn/webexte
Undo URL

2021-03-18 01:35 UTC, nschonni commented on files/en-us/mozilla/add-ons/webextensions/user_interface/options_pages/index.html
> +<p>The <a href="https://github.com/mdn/webextensions-examples">webextensions-examples</a> repository on GitHub includes the <a href="https://github.com/mdn/webextensions-examples/tree/master/favourit
Undo URL

2021-03-22 14:55 UTC, jpmedley commented
Please look again.

2021-04-01 00:41 UTC, sideshowbarker commented
@nschonni I think this one is waiting for your re-review

2021-04-01 00:42 UTC, sideshowbarker commented
> @nschonni I think this one is waiting for your re-review

and/or waiting for an approval from @rachelandrew

2021-04-20 19:54 UTC, Ryuno-Ki commented
Ping

2021-05-26 07:39 UTC, sideshowbarker commented
@jpmedley Do you still want to keep this PR open?

2021-06-03 18:27 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/managed/index.html
> +<p>Given this manifest, the "favorite-color-examples@mozilla.org" extension could access the data using code like this:</p>
@sideshowbarker Is this a real email address?

2021-06-03 18:43 UTC, jpmedley commented
Sorry for neglecting this. I just merged some conflict corrections. 

nschonni seems to want me to change a bunch of examples back to British spelling. Seems like, if it's not a URL or a title, it should follow the same rule as text: American spelling.

2021-06-12 23:23 UTC, sideshowbarker commented
> nschonni seems to want me to change a bunch of examples back to British spelling. Seems like, if it's not a URL or a title, it should follow the same rule as text: American spelling.

@jpmedley I guess the decision is up to you, but I also notice that this PR is blocked on resolution of the review comment from @rachelandrew at https://github.com/mdn/content/pull/3005#pullrequestreview-609136480

2021-06-14 18:16 UTC, jpmedley commented
Everything from @rachelandrew is outdated, meaning I think I covered it all. The ball is in Rachel's court.

2021-06-14 18:47 UTC, rachelandrew approved these changes
apologies - didn't realise I was blocking this, all looks good now.

2021-06-14 22:13 UTC, merged