Fix 30070
mdn/content pull request #30081
Opened 2023-11-07 05:14 UTC by wbamberg

Fixes https://github.com/mdn/content/issues/30070.

This PR fixes the organization of our XHR docs:
- creates a new API overview page for XHR
- moves various guide pages out from interface pages under that overview
- fixes all sidebars for XHR pages
- fixes links for moved guide pages

I have kept the overview page quite minimal, since we already have guide pages for this and it's really a legacy technology at this point.

I have chosen not to try to update any of the content in this PR because it would be a big task. But I think the content is probably quite out of date in many places.

2023-11-07 05:47 UTC, teoli2003 requested changes
Thanks a lot! This was long due, and I'm happy that you decided to tackle this problem.

I have a few comments/questions, not really requests, but I'm curious about the answers, so I set it to `Request changes` instead of `approve`.

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/index.md
Should we add a sentence or a note directing devs to consider the _Fetch API_ instead?

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest/index.md
>    - [Fetch API](/en-US/docs/Web/API/Fetch_API)
I'm not sure we should list _Fetch API_ inside _Using XMLHttpRequest_.

For consistency with _MDN tutorials covering `XMLHttpRequest`:_, I've added a colon:
```suggestion
- [Using XMLHttpRequest](/en-US/docs/Web/API/XMLHttpRequest_API/Using_XMLHttpRequest):

  - [HTML in XMLHttpRequest](/en-US/docs/Web/API/XMLHttpRequest_API/HTML_in_XMLHttpRequest)
  - [Fetch API](/en-US/docs/Web/API/Fetch_API)
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +The XMLHttpRequest API enables web apps to make HTTP requests to web servers and receive the responses programmatically using JavaScript. This in turn enables a website to update just part of a page
Not sure what the template is, but I would "boldify" _XMLHttpRequest API_ as it is a kind of definition.
```suggestion
The **XMLHttpRequest API** enables web apps to make HTTP requests to web servers and receive the responses programmatically using JavaScript. This in turn enables a website to update just part of a page with data from the server, rather than having to navigate to a whole new page. This practice is also sometimes known as {{glossary("Ajax")}}.
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +The [Fetch API](/en-US/docs/Web/API/Fetch_API) is the more flexible and powerful replacement for XMLHttpRequest. The Fetch API uses {{jsxref("Promise", "promises", "", "nocode")}} instead of events t
```suggestion
The [Fetch API](/en-US/docs/Web/API/Fetch_API) is the more flexible and powerful replacement for the XMLHttpRequest API. The Fetch API uses {{jsxref("Promise", "promises", "", "nocode")}} instead of events to handle asynchronous responses, integrates well with [service workers](/en-US/docs/Web/API/Service_Worker_API), and supports advanced aspects of HTTP such as [CORS](/en-US/docs/Web/HTTP/CORS). For these reasons, the Fetch API is usually used in modern web apps instead of {{domxref("XMLHttpRequest")}}.
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +2. Initialize it by calling {{domxref("XMLHttpRequest.open()")}}. At this point you provide the URL for the request, the [HTTP method](/en-US/docs/Web/HTTP/Methods) to use, and optionally, a username
```suggestion
2. Initialize it by calling {{domxref("XMLHttpRequest.open()")}}. At this point you provide the URL for the request, the [HTTP method](/en-US/docs/Web/HTTP/Methods) to use, and optionally, a username and a password.
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +3. Attach event handlers to get the result of the request. For example, the {{domxref("XMLHttpRequest.load_event", "load")}} event fires when the request has successfully completed, and the {{domxref
"fires" is active but used in the passive form? Shouldn't be "is fired" ? (or "is thrown")

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +For an in-depth guide to XMLHttpRequest, see [Using XMLHttpRequest](/en-US/docs/Web/API/XMLHttpRequest_API/Using_XMLHttpRequest).
```suggestion
For an in-depth guide to the XMLHttpRequest API, see [Using XMLHttpRequest](/en-US/docs/Web/API/XMLHttpRequest_API/Using_XMLHttpRequest).
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/sending_and_receiving_binary_data/index.md
> +See [FormData](/en-US/docs/Web/API/FormData).
```suggestion
See [`FormData`](/en-US/docs/Web/API/FormData).
```

2023-11-07 05:47 UTC, teoli2003 commented on files/en-us/web/guide/ajax/index.md
>  - The request is made and then (`onreadystatechange`) the execution is passed to `alertContents()`;
Should we move this whole guide under _XMLHttpRequest API_? (I'm still trying to empty `web/guide` so that we can start from fresh with the 4 doc realms (reference, guide, howtos, …)

2023-11-07 06:03 UTC, wbamberg commented on files/en-us/web/guide/ajax/index.md
>  - The request is made and then (`onreadystatechange`) the execution is passed to `alertContents()`;
That's an interesting question. The current Ajax guide is all about XHR, true, but it doesn't have to be (and shouldn't be). A better solution might be to update it to use Fetch (although even the Ajax terminology feels painfully old fashioned now). But of course that's a lot more work than just moving it. And at some point here we come up against the really hard problems like: what kind of guide content do we really want to have here, and how would we want to integrate it into a coherent whole? I mean, it seems like a good idea somewhere on MDN to have content on how to build a dynamic web app by fetching the content you need from the server, and that might want to connect with things like SPAs and and so on. Could it even live under PWAs?

2023-11-07 06:48 UTC, teoli2003 commented
I just found an extra (simple) problem to fix. There are a few links to Using FormData objects that are "broken" after this PR. (You'll find them in the flaws list in the PR Test comments:
![Capture d’écran 2023-11-07 à 07 46 56](https://github.com/mdn/content/assets/1466293/4a23b371-de16-45cb-a3b4-4f5e5971b1fd)

2023-11-07 06:49 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/5/index.md
> +- [`XMLHttpRequest`](/en-US/docs/Web/API/XMLHttpRequest) now [supports the `loadend` event](/en-US/docs/Web/API/_XMLHttpRequest_API/_Using_XMLHttpRequest#detecting_any_load_end_condition) for progres
```suggestion
- [`XMLHttpRequest`](/en-US/docs/Web/API/XMLHttpRequest) now [supports the `loadend` event](/en-US/docs/Web/API/_XMLHttpRequest_API/Using_XMLHttpRequest#detecting_any_load_end_condition) for progress listeners. This is sent after any transfer is finished (that is, after the `abort`, `error`, or `load` event). You can use this to handle any tasks that need to be performed regardless of success or failure of a transfer.
```

2023-11-07 18:39 UTC, wbamberg commented on files/en-us/web/api/xmlhttprequest/index.md
So like I say, I've not really touched content in this PR, except where I had to to fix the organization problems. Yes, I could spend a long time trying to bring the existing content up to date, but I really would prefer to get this particular change done.

2023-11-07 18:40 UTC, wbamberg commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +3. Attach event handlers to get the result of the request. For example, the {{domxref("XMLHttpRequest.load_event", "load")}} event fires when the request has successfully completed, and the {{domxref
I think both are OK to me, but happy to make the change.

2023-11-07 18:49 UTC, wbamberg commented
> I just found an extra (simple) problem to fix. There are a few links to _Using FormData objects_ that are "broken" after this PR.

Oh yeah, I failed to find these. I hate that we have to do this manually.

2023-11-08 06:00 UTC, teoli2003 commented on files/en-us/web/api/xmlhttprequest_api/index.md
> +3. Attach event handlers to get the result of the request. For example, the {{domxref("XMLHttpRequest.load_event", "load")}} event fires when the request has successfully completed, and the {{domxref
Fine for me.

2023-11-08 06:00 UTC, teoli2003 commented on files/en-us/web/guide/ajax/index.md
>  - The request is made and then (`onreadystatechange`) the execution is passed to `alertContents()`;
We can think about this in the future.

2023-11-08 06:02 UTC, teoli2003 commented on files/en-us/mozilla/firefox/releases/5/index.md
> +- [`XMLHttpRequest`](/en-US/docs/Web/API/XMLHttpRequest) now [supports the `loadend` event](/en-US/docs/Web/API/_XMLHttpRequest_API/Using_XMLHttpRequest#detecting_any_load_end_condition) for progress
```suggestion
- [`XMLHttpRequest`](/en-US/docs/Web/API/XMLHttpRequest) now [supports the `loadend` event](/en-US/docs/Web/API/XMLHttpRequest_API/Using_XMLHttpRequest#detecting_any_load_end_condition) for progress listeners. This is sent after any transfer is finished (that is, after the `abort`, `error`, or `load` event). You can use this to handle any tasks that need to be performed regardless of success or failure of a transfer.
```

2023-11-08 06:03 UTC, teoli2003 approved these changes

2023-11-08 06:04 UTC, wbamberg commented on files/en-us/mozilla/firefox/releases/5/index.md
> +- [`XMLHttpRequest`](/en-US/docs/Web/API/XMLHttpRequest) now [supports the `loadend` event](/en-US/docs/Web/API/_XMLHttpRequest_API/Using_XMLHttpRequest#detecting_any_load_end_condition) for progress
/me shakes fist at broken links

2023-11-08 06:06 UTC, merged