Editorial review: Topics api docs
mdn/content pull request #30107
Opened 2023-11-08 11:35 UTC by chrisdavidmills

### Description

https://github.com/mdn/content/pull/28196 contains the engineering technical review for my work on [Topics API](https://patcg-individual-drafts.github.io/topics/) docs, which has been completed and approved. Thank you to @samdutton for your thorough and detailed review work.

This is a new PR based on the same branch, which is intended to contain the editorial review for the same work.

---

### Background information

[The Topics API](https://patcg-individual-drafts.github.io/topics/) is an integral part of Google's [privacy sandbox](https://developer.chrome.com/docs/privacy-sandbox/) technologies. Many parts of this set are being made available by default in Chrome 115 (depending on a gradual ramp up to 100% of userbase over the 115 release period).

This PR provides documentation for the Topics API and its related HTTP headers and HTTP features.

See my [research document](https://docs.google.com/document/d/1gfp8Ey6nfGTo4cOlq1Knbhz0kSopbBUc69BF0JCSmq4/edit) for more details of exactly what changes are expected in the PR.

### Motivation

### Additional details

### Related issues and pull requests

2023-11-08 18:40 UTC, samdutton commented
Thanks for your thoroughness and patience, Chris!

2023-11-09 15:54 UTC, wbamberg commented
Hey Chris, I will take a look at this one.

2023-11-21 10:58 UTC, chrisdavidmills commented
@wbamberg see https://github.com/mdn/content/discussions/30428 for relevant discussion about representing standards positions in this PR.

2023-11-25 00:21 UTC, wbamberg reviewed
Comments on the main API overview page. As usual I think it would be good to farm a lot of the guide-y material into a separate page so this can be a relatively clean landing page.

I hope these comments are helpful! It's a surprisingly hard API to understand.

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +`chrome://flags/#privacy-sandbox-enrollment-overrides`
This and the linked page is totally Chrome-specific, isn't it? It would be better to say something like "Note that Chrome has specific requirements for developers wishing to use the Topics API" and link to documentation on Chrome's website.

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +Using the `fetch()` `browsingTopics` option:
```suggestion
Passing the `browsingTopics` option into `fetch()`:
```

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +- [Topics API header demo](https://topics-fetch-demo.glitch.me/): Demonstrates a `fetch()` request with a {{httpheader("Sec-Browsing-Topics")}} header can be used to observe and then access topics.
I wish we didn't have demos hosted on Glitch. I don't know how to see the source for these demos and we can't maintain them ourselves.

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +`chrome://flags/#privacy-sandbox-enrollment-overrides`
Also though, IMO it would be better to split this section into "Enrollment" and "Testing", where "Enrollment" links to the Chrome enrollment docs, and "Testing" talks about the flag, and also talks about setting the epoch length which you currently do under "Examples".

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +See [Run Chromium with command-line switches](https://www.chromium.org/developers/how-tos/run-chromium-with-flags/) for more information on how to do this.
As above, this would be better in a "Testing" section alongside the stuff about overriding enrollment.

2023-11-25 00:21 UTC, wbamberg commented on files/en-us/web/api/topics_api/index.md
> +Exactly how the top topics are chosen will likely vary across implementations. [Read about how Chromium does this](https://developer.chrome.com/docs/privacy-sandbox/topics/overview/#manually-curated)
"how the **top** topics are chosen will likely vary across implementations" implies to me that the algorithm for deciding which topics out of the set are "top" is implementation-specific, but it's not, is it? I thought we talked about how this is done in some detail.

So does this mean, "how to complete set of possible topics are defined will likely vary across implementations"? That seems like what the link at https://developer.chrome.com/docs/privacy-sandbox/topics/overview/#manually-curated is talking about.

2023-11-27 13:43 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +The Topics API provides a privacy-preserving way to implement IBA and other use cases such as content selection. First of all, the browser observes what sites users visit and infers their interests f
+1 to all that.

I like the more neutral phrasing.

2023-11-27 14:41 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +### How does the Topics API work?
Agree that Topics can appear simple on the surface, but is complex in the detail.

I think the [unofficial draft spec](https://patcg-individual-drafts.github.io/topics/#periodically-calculate-user-topics-header) is probably the best place to get a full understanding of Topics. 

Here's an overview of the process, building up to the "presence" requirement.

With regard to a caller having "a presence" see the references in the spec to [caller domains](https://patcg-individual-drafts.github.io/topics/#topics-history-entry-topics-caller-domains).

The browser records [topics history entries](https://patcg-individual-drafts.github.io/topics/#browsing-topics-types-topics-history-entry) in topics history storage (i.e. on the user's device). The topics history entry data structure is described here: [patcg-individual-drafts.github.io/topics/#browsing-topics-types-topics-history-entry](https://patcg-individual-drafts.github.io/topics/#browsing-topics-types-topics-history-entry).

(In the current Chrome implementation, topics calculation input data is the hostname of a page visited: [patcg-individual-drafts.github.io/topics/#determine-topics-calculation-input-data-header](https://patcg-individual-drafts.github.io/topics/#determine-topics-calculation-input-data-header).) In other words, the browser doesn't record topic IDs for a page visit: it records a topics history entry.

At the start of each new epoch, the browser calculates user topics: [patcg-individual-drafts.github.io/topics/#collect-page-topics-calculation-input-data-header](https://patcg-individual-drafts.github.io/topics/#collect-page-topics-calculation-input-data-header). The [top topics are calculated](https://patcg-individual-drafts.github.io/topics/#topics-for-caller-header), and one is chosen as the top topic. That topic is returned to the caller, but **only if the caller is in the list of caller domains for the topic** (see Topics for caller [step 8](https://patcg-individual-drafts.github.io/topics/#topics-for-caller-header:~:text=If-,topTopicWithCallerDomains%E2%80%99s,-caller%20domains%20contains): "If topTopicWithCallerDomains’s caller domains contains callerContext’s caller domain: ...")

The browser then runs an algorithm to choose the top topics. Chrome's current (new) implementation is described here: [developer.chrome.com/blog/topics-enhancements/#top-topics-selection](https://developer.chrome.com/blog/topics-enhancements/#top-topics-selection).

2023-11-27 14:42 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +Fitness, Fibre & textile arts and Shopping
Oops — yes.

2023-11-27 14:48 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +- Calculate top topics for that user for future epochs, based on those topics of interest.
+1.

Looking at it now, I don't think this makes sense: "Calculate top topics for that user for future epochs, based on those topics of interest." (See the description above of the process of the browser recording topics history entries, then calculating top topics from that, at the end of each epoch.)

2023-11-27 14:49 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +`chrome://flags/#privacy-sandbox-enrollment-overrides`
+1: this is Chrome-specific.

And yes to splitting.

2023-11-27 14:54 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +- [Topics API header demo](https://topics-fetch-demo.glitch.me/): Demonstrates a `fetch()` request with a {{httpheader("Sec-Browsing-Topics")}} header can be used to observe and then access topics.
Each demo has links to its code: 
• [glitch.com/edit/#!/topics-demo](https://glitch.com/edit/#!/topics-demo)
• [glitch.com/edit/#!/topics-fetch-demo](https://glitch.com/edit/#!/topics-fetch-demo)

You can view the source for a Glitch demo by using `https://glitch.com/edit/#!/` followed by the demo name.

Agree that ideally these wouldn't be hosted on Glitch.

2023-11-27 15:00 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +Exactly how the top topics are chosen will likely vary across implementations. [Read about how Chromium does this](https://developer.chrome.com/docs/privacy-sandbox/topics/overview/#manually-curated)
> "how the top topics are chosen will likely vary across implementations" implies to me that the algorithm for deciding which topics out of the set are "top" is implementation-specific, but it's not, is it? I thought we talked about how this is done in some detail.

The implementation of top-topics selection is indeed up to the user agent, and not specified [in the spec draft](https://patcg-individual-drafts.github.io/topics/#derive-top-5-topics-header). (Note that the Chrome implementation has changed recently: see [developer.chrome.com/blog/topics-enhancements/#top-topics-selection](https://developer.chrome.com/blog/topics-enhancements/#top-topics-selection). The spec will be updated in due course.)

2023-11-27 15:21 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +- Trigger the browser to record page views for the above sites, and infer topics of interest such as "Fitness", "Fibre & textile arts", and "Soccer" from their URLs.
On all three sites, there is an ad-tech1.example iframe that calls the Topics API. This means a [topics history entry](https://patcg-individual-drafts.github.io/topics/#browsing-topics-types-topics-history-entry) is created by the user's browser each time they visit a page on one of those sites. 

The topics history entry (in the current Chrome implementation) records the host of the page's URL. At the end of the epoch, topics are calculated from topics history entries (i.e. using the host for each entry).

It might be clearer to rephrase this in terms of triggering the browser to record an entry in topics history (not "page views").

I think "infer topics of interest such as "Fitness", "Fibre & textile arts", and "Soccer" from their URLs" is confusing, because this is done by the browser at the end of each epoch (not by ad-tech1.example, as you say elsewhere). This should be described separately.

2023-11-27 17:43 UTC, estelle commented on files/en-us/web/html/element/iframe/index.md
> +  - : Include this attribute to specify that observed topics should be sent in a {{httpheader("Sec-Browsing-Topics")}} header with the request for the `<iframe>`'s source. See the [Topics API](/en-US
Drive by comment (Im not reviewing this whole PR, just this page): 
Is this boolean? say so. If true, X...
Making a suggestion that is likely incorrect, but just to show what i mean...

```suggestion
  - : Boolean attribute that, if present, specifies that the observed topics should be sent in a {{httpheader("Sec-Browsing-Topics")}} header with the request for the `<iframe>`'s source. This attribute is not part of the [Topics API](/en-US/docs/Web/API/Topics_API), an [unofficial proposed draft specification](https://patcg-individual-drafts.github.io/topics/).
```
The linked [Topics API](/en-US/docs/Web/API/Topics_API) doesn't provide more details on how to use the attribute - just line 82 really; a reader shouldn't have to read the entire API to understand how to use an attribute. Please create content on that page (or elsewhere) for this attribute if we want to include it.

2023-12-06 14:36 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +The Topics API provides a privacy-preserving way to implement IBA and other use cases such as content selection. First of all, the browser observes what sites users visit and infers their interests f
OK, to fix this I have:

- used some of your text
- provided a link to the HTTP section definition of third-party cookies rather than repeat this kind of basic definition stuff here (I also improved this text in one of my other PRs recently)
- added the opposition banner at the top of the page and the standards position section near the bottom, as discussed in our [recent discussion thread](https://github.com/orgs/mdn/discussions/463). This is the same as I've done it in my [RWS PR](https://github.com/mdn/content/pull/30654). I've not put it on all other Topics-related pages in the PR, as it might change, and I'm not sure if I need to put it on all pages. Thoughts on that?

2023-12-06 14:53 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +### How does the Topics API work?
I'm going to read through the other comments first, then come back to this overarching one. I will admit, I struggled to understand this API too during the writing of this.

2023-12-06 14:53 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +Fitness, Fibre & textile arts and Shopping
deleted.

2023-12-07 09:29 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +`chrome://flags/#privacy-sandbox-enrollment-overrides`
Yup, totally agree with @wbamberg here. To address this, I have:

- Split the "Enrollment" and "Testing" instructions onto different sections as suggested. The "Testing" details are now on the new "Using..." page
- Added a note/banner at the top of the main landing page and "Using..." page to make it really clear and obvious that this is an extra requirement that is needed to use this API. I also added similar banners to the top of the reference pages for specific subfeatures that are blocked if enrollment is not done.
- Updated the separate enrollment page that I added inside the Privacy/Privacy sandbox section of the site to be much more general-sounding and not Chrome-specific. I want to keep a separate page for this, the idea being that eventually we may document multiple browser's instructions on how to enroll, which may differ from one another, so it would be good to capture these all in one central place.

2023-12-07 09:41 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +Using the `fetch()` `browsingTopics` option:
Good call. I've turned all the separate bits in the new "Using..." guide examples section into subheadings.

2023-12-07 09:58 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +See [Run Chromium with command-line switches](https://www.chromium.org/developers/how-tos/run-chromium-with-flags/) for more information on how to do this.
done

2023-12-07 10:09 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +Exactly how the top topics are chosen will likely vary across implementations. [Read about how Chromium does this](https://developer.chrome.com/docs/privacy-sandbox/topics/overview/#manually-curated)
I've moved this bit to the "Using..." guide, and linked to the chrome page for how it happens, rather than explaining it in detail, given that it work work differently per implementation.

2023-12-07 10:29 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +  - : Include this attribute to specify that observed topics should be sent in a {{httpheader("Sec-Browsing-Topics")}} header with the request for the `<iframe>`'s source. See the [Topics API](/en-US
I've done a bunch of rewriting that should help clarify somewhat how to use this. We are getting there slowly. I have clarified that it's a boolean on the iframe page.

2023-12-07 11:06 UTC, chrisdavidmills commented
OK, I have reworked this content quite significantly after considering all the comments made. I'm a bit concerned that, previously I felt like I understood this API, and now I don't feel so sure, and have outstanding questions once more.

I think it might be a good approach for @samdutton to first read the new state of the main landing page and "Using..." guide, have a look at the following questions, and see if he can provide clarification and tell me where I'm now going wrong. I'll then try another rewrite to hopefully clear things up before @wbamberg reviews it again.

I am a bit concerned that this might turn into a huge megathread, in which case maybe we could set up a call to discuss this rather than going back and forth in comments?

1. In the new "Using..." guide, I've tried to explain what is going on in a high-level fashion before then talking about what technically happens separately, afterwards. In the "High-level overview" section, points 2-4, I've talked in a very hand-wavy fashion about the browser calculating topics per epoch, then choosing top topics per epoch, then choosing one top topic which is then sent to the caller when the <iframe> is loaded. Does this make sense? I don't really know what to write about it for the best. What do developers need to know about this?

   Looking at this again, I think it would make more sense for me to put point 4 as a subbullet under point 1, as surely this happens when the site is loaded...then explain the ongoing process of calculating user topics and top topics separately below...but again, I'm not sure if that is correct.

2. In the "How are topics returned to the caller?" section, I've tried to explain what happens when an <iframe> containing one of the magical topics API features is loaded, when the HTTP headers are sent, and what they do. Does it sound right? 

   I'm particularly confused by how Observe-Browsing-Topics is used. I thought "observing a topic" was done on the client-side, when the <iframe> is first loaded. What does it mean for a topic to be "marked as observed" once the Observe-Browsing-Topics header is sent in response to a Sec-Browsing-Topics header being sent? What difference does that make?

3. I've started to change the text that describes technically how this works to talk about the one chosen top topic being sent to the caller via the Sec-Browsing-Topics, rather than multiple top topics, as this is implied earlier comments on this thread ("That topic is returned to the caller"). Is this correct? If so, I'll need to change the descriptions of all the  other API features to suit. 

   I'm also concerned about where `Document.browsingTopics` fits into this, as that is specifically defined as returning multiple topics that can then be sent to the caller in a manner of your choosing (i.e. fetch()) rather than a single topic. So why is this different?

4. I've described the different features that cause the browser to observe topics and send the top topic back to the caller as features that "enable the Topics API" (see the "What API features enable the Topics API?" section). does that make sense?

   I also wanted to check - you only need to use any one of these features, depending on what makes most sense for your particular codebase, right? You don't need to use a combination?

2024-01-10 12:49 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +The API returns topics within the most recent three epochs; one for each. The topic selected for each epoch is randomly selected from the user's top five topics for that epoch. Note that the top topi
> Why would this be? Because the user didn't visit sites belonging to 5 different topics?

> Isn't this contradicted by the next paragraph "Note also that ... there is a 5% chance that the topic will be replaced by a random topic "?

For a topic to be added to the topics history entries for a user for an epoch (https://patcg-individual-drafts.github.io/topics/#browsing-topics-types-topics-history-entry) it must be "observed" (in other words, a Topics caller must have a presence on a page, for which a topic is calculated, that the user visits).

The top five topics list (https://patcg-individual-drafts.github.io/topics/#derive-top-5-topics-header) is padded with random topics (as opposed to "real", observed topics), if less than five topics have been observed during an epoch.

In addition, for each epoch, there is a 5% chance that a random topic is returned, rather than the "real" top topic. However, this random topic will only be returned to a caller if the caller has observed that topic for the user.

> Is this the algorithm

Yes! (Just realised I outlined pretty much the same thing above...)

2024-01-10 12:51 UTC, samdutton commented on files/en-us/web/api/topics_api/index.md
> +- Trigger the browser to record page views for the above sites, and infer topics of interest such as "Fitness", "Fibre & textile arts", and "Soccer" from their URLs.
Any questions on this?

2024-01-11 09:50 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/index.md
> +- Trigger the browser to record page views for the above sites, and infer topics of interest such as "Fitness", "Fibre & textile arts", and "Soccer" from their URLs.
Thanks for the new comments @samdutton. After reading @wbamberg's comments and your responses last year, I did a significant rewrite of the content and wrote up my remaining points of confusion and questions in this comment: https://github.com/mdn/content/pull/30107#issuecomment-1845143549.

Would you be willing to have a read-through of the new state of the content, then maybe we can jump on a call to walk through it and discuss the remaining parts where I'm going wrong?

2024-02-22 01:09 UTC, wbamberg requested changes
This looks pretty great. I thought it was a lot more understandable, nice work.

2024-02-22 01:09 UTC, wbamberg commented on files/en-us/web/privacy/firefox_tracking_protection/index.md
> +</section>
I'm not sure what the rationale is for this change...

2024-02-22 15:52 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/using/index.md
> +3. Returns up to three **chosen topics** to `ad-tech1.example` (the chosen topics for the last three epochs), only if they appear in the list of caller domains for that topic, as stored in the topic'
Yes, that's correct. If a caller domain hasn't observed a topic, they can't have it returned to them. I've used your wording, as it made sense.

2024-02-22 16:17 UTC, chrisdavidmills commented on files/en-us/web/api/topics_api/using/index.md
> +Alternatively, the embedded `<iframe>` can call {{domxref("Document.browsingTopics()")}} to return a user's current chosen topic(s), which can then be returned to the ad tech platform in a subsequent
I think this is more of a "there might be situations as a result of your own personal dev circumstances where you can't modify the HTTP headers when communicating with the server."

I've changed it to "...where the headers cannot be modified." I don't know if this makes things any better...?

2024-02-22 16:22 UTC, chrisdavidmills commented on files/en-us/web/api/document/browsingtopics/index.md
> +The `browsingTopics()` method of the {{domxref("Document")}} interface returns a promise that fulfills with an array of objects representing the selected topics for the current user. It also triggers
Good call. I've added a note to cover it.

2024-02-22 16:24 UTC, chrisdavidmills commented on files/en-us/web/api/htmliframeelement/browsingtopics/index.md
> +The **`browsingTopics`** property of the {{domxref("HTMLIFrameElement")}} interface is a boolean specifying that that the selected topics for the current user should be sent with the request for the
I'm not sure really...I think I got it from an explainer somewhere, but yeah, it is a bit weird. I've updated it to "This reflects the `browsingtopics` HTML attribute."

2024-02-22 17:19 UTC, wbamberg commented on files/en-us/web/privacy/firefox_tracking_protection/index.md
> +</section>
Oh you mean like:

<img width="310" alt="Screen Shot 2024-02-22 at 9 16 40 AM" src="https://github.com/mdn/content/assets/432915/c98a5cfb-0716-458d-86f5-fd72fdcbb138">

? Yeah, that's not great. TBH I think the sidebar here - both in production and this PR - is barely usable and doesn't give any real idea of the organization of these docs. Not your fault though, given the state of the tools. I suppose we should file a Yari bug to ask the engineers to fix it.

2024-02-22 17:23 UTC, chrisdavidmills commented on files/en-us/web/privacy/firefox_tracking_protection/index.md
> +</section>
Yup. I'll file a bug now

2024-02-22 17:28 UTC, chrisdavidmills commented on files/en-us/web/privacy/firefox_tracking_protection/index.md
> +</section>
See https://github.com/mdn/yari/issues/10572

2024-02-22 17:44 UTC, wbamberg commented on files/en-us/web/api/topics_api/using/index.md
> +  ```
Yeah I wasn't particularly happy with my suggestion either :).

2024-02-22 17:55 UTC, wbamberg approved these changes
Looks great!

2024-02-22 17:55 UTC, merged

2024-02-23 09:28 UTC, chrisdavidmills commented
Yay, thanks @wbamberg!

2024-02-23 10:56 UTC, samdutton commented
Thanks all, for being so patient and thorough!

One thing we'll need to update:
developer.mozilla.org/en-US/docs/Web/API/Topics_API/Using#selecting_topics_of_interest_to_influence_ad_choice

The algorithm for top topics selection used by Chrome has been updated:
developers.google.com/privacy-sandbox/blog/topics-enhancements. With a
little tweaking, we could pretty much use that explanation as it is.

On Fri, 23 Feb 2024 at 09:28, Chris Mills ***@***.***> wrote:

> Yay, thanks @wbamberg <https://github.com/wbamberg>!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/content/pull/30107#issuecomment-1960989382>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABSDKRK32WQK6YEPIUGHU3YVBOLNAVCNFSM6AAAAAA7CXGMRCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQHE4DSMZYGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>