chore(docs): Document Embedlivesample identifier
mdn/content pull request #30102
Opened 2023-11-08 08:43 UTC by bsmth

The `{{Embedlivesample}}` macro currently has two ways of specifying which code blocks to combine into a "result" iframe, and only one of these ways is documented. This PR adds documentation for the "string identifier" method or marking fenced code blocks (HTML/CSS/JS) with an identifier in the info string using:

- ` ```{language} live-sample___{identifier} `

For example, in Markdown, this is used as follows:

````md
## Examples

### Styling a paragraph

In this example, we're using CSS to style paragraphs.

```html live-sample___paragraph-styling
<p>I'm not fancy.</p>
<p class="fancy">But I am!</p>
```

```html
<p>I'm another HTML block. I won't be included in the result.</p>
```

```css live-sample___paragraph-styling
p.fancy {
  color: red;
}
```

Only the `<p>` element with `class="fancy"` will get styled `red`:

{{EmbedLiveSample("paragraph-styling")}}
````

2023-11-08 15:41 UTC, dipikabh commented
Thanks for opening this PR, @bsmth 🙏! I'll take a look now.

2023-11-08 18:14 UTC, dipikabh requested changes
Thanks, @bsmth. This is good overall. I've added some edit suggestions.

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +If you're not using a particular language type (for example, if you are not using JavaScript) or if you are hiding it, then you should omit the corresponding heading.
```suggestion
If you're not using a particular language type (for example, if you are not using JavaScript) or if you are hiding the code block, then you should omit the corresponding heading.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this you can hide any code blocks that are not relevant with the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
```suggestion
### Hiding code

Sometimes you just want to display the static code block pertinent to the example rendered within a page. However, you still need the HTML, CSS, and JavaScript code blocks to render such an example.

To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +One common use case is to take existing code snippets already shown on MDN and turn them into live samples.
```suggestion
One common use case is to take existing code snippets already shown on MDN and turning them into live samples.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +This HTML creates a paragraph and some blocks to help us position and style a message.
```suggestion
This HTML creates a paragraph and some blocks to help us position and style a message. The `live-sample___hello-world` class has been added to the `html` language identifier for this code block.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +The CSS code styles the box as well as the text inside it.
```suggestion
The CSS code styles the box as well as the text inside it. The `live-sample___hello-world` class has been added to the `css` language identifier for this code block.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +This code attaches an event handler to the "Hello world!" text that makes an alert appear when it is clicked.
```suggestion
This JavaScript code attaches an event handler to the "Hello world!" text that makes an alert appear when it is clicked. The `live-sample___hello-world` class has been added to the `js` language identifier for this code block as well.
```

2023-11-08 18:14 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +The result of running the code blocks above via `\{{EmbedLiveSample('hello-world')}}`:
```suggestion
We get this output by running the code blocks above using the string identifier `hello-world` in the `\{{EmbedLiveSample('hello-world')}}` macro call:
```

2023-11-09 12:51 UTC, bsmth commented
Thank you for the comments, @dipikabh! 🙏🏻

2023-11-17 09:56 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +MDN supports turning code blocks in articles into running samples the reader can see in action. These are called _live samples_ and allows users to see what code output looks like. It also makes docu
Yes, this is great, tnx.

2023-11-17 10:00 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +The live sample system allows grouping of code blocks in different ways to effectively display the output. The next section describes these methods.
```suggestion
The live sample system allows grouping of code blocks in different ways to effectively display the output. The next section describes these methods.

```

2023-11-17 10:21 UTC, bsmth commented
Thanks @dipikabh - let's take a look again when you're back.

2023-11-17 12:42 UTC, pepelsbey commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
It’s probably not the right occasion to talk about this, but I just noticed that `css` or `html` bits that we add to fenced code blocks are called “classes”, which might be confusing. They’re not HTML classes, they’re rather [language IDs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting). As for the `hidden` bit, it’s not even a language ID, it’s something custom that we use.

We might want to separate those in the docs to clarify what’s language ID and what’s a custom command, attribute, or tag. Let me know if it makes sense, and I’ll start a discussion in some other, more proper place :)

2023-11-17 19:32 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
No that's a good clarification, language ID is good. I've also seen 'info string' which covers all cases, maybe we could use that instead?

2023-11-17 22:32 UTC, pepelsbey commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
Let’s maybe move this discussion out of the issue to some team call or a chat? :)

2023-11-20 19:32 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +Each [code block](/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#example_code_blocks) containing code for the output has a language identifier — `html`, `css`, or `js` — that specifies whet
```suggestion
Each [code block](/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#example_code_blocks) containing code for the output has a language identifier — `html`, `css`, or `js` — that specifies whether it's HTML, CSS, or JavaScript code. The language identifiers must be on the corresponding blocks of code, and a macro call (`EmbedLiveSample`) must be present in the page to display the output:
```

2023-11-20 19:32 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
That is an interesting point @pepelsbey and would be good to clarify in our docs and to use consistently. Thanks for spotting!

We use language ID and like @bsmth mentioned "info strings" in our guidelines for [Example code blocks](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#example_code_blocks) and further below on the same page in the section [Additional classes (info strings)](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#additional_classes_info_strings). The second section has a link to these [GitHub docs](https://github.github.com/gfm/#info-string):

> The first word of the [info string](https://github.github.com/gfm/#info-string) is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag.

Perhaps the section title "Additional classes (info strings)" itself should be updated to "Additional info strings"(outside the scope of this PR).

We can update a few instances (class vs language ID) on the pages touched via this PR.

2023-11-20 19:41 UTC, dipikabh approved these changes
This is looking good, @bsmth. Thanks for the updates.

 There's a few suggestions following Vadim's comment about saying "lang ID" vs "class". Leaving a +1 so you can merge after the changes.

2023-11-20 19:41 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +This HTML creates a paragraph and some blocks to help us position and style a message. The `live-sample___hello-world` class has been added to the `html` language identifier for this code block.
```suggestion
This HTML creates a paragraph and some blocks to help us position and style a message. The `live-sample___hello-world` string has been added to the `html` language identifier for this code block.
```

2023-11-20 19:41 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +The CSS code styles the box as well as the text inside it. The `live-sample___hello-world` class has been added to the `css` language identifier for this code block.
```suggestion
The CSS code styles the box as well as the text inside it. The `live-sample___hello-world` string has been added to the `css` language identifier for this code block.
```

2023-11-20 19:41 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +This JavaScript code attaches an event handler to the "Hello world!" text that makes an alert appear when it is clicked. The `live-sample___hello-world` class has been added to the `js` language iden
```suggestion
This JavaScript code attaches an event handler to the "Hello world!" text that makes an alert appear when it is clicked. The `live-sample___hello-world` string has been added to the `js` language identifier for this code block as well.
```

2023-11-20 19:41 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To group code blocks using a string identifier, add a class that begins with `live-sample___` to the code block's language identifier. Add a unique identifier to the class prefix in the format `live-
```suggestion
To group code blocks using a string identifier, add an info string that begins with `live-sample___` to the code block's language identifier. Add a unique identifier to the prefix in the format `live-sample___{IDENTIFIER}`. The `live-sample___` prefix along with the identifier helps the live sample system recognize and group code blocks correctly. For example, `live-sample___color-picker` uses `color-picker` as the identifier following the `live-sample___` prefix.
```

2023-11-20 19:41 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
```suggestion
To achieve this, you can hide any code blocks that are not relevant by adding the `hidden` info string to the language identifier. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
```

2023-11-22 09:21 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To group code blocks using a string identifier, add a class that begins with `live-sample___` to the code block's language identifier. Add a unique identifier to the class prefix in the format `live-
Thank you! I've modified it slightly, but it's looking better now

2023-11-22 09:26 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/live_samples/index.md
> +To achieve this, you can hide any code blocks that are not relevant by using the `hidden` class. If you do this, omit the `### HTML/CSS/JavaScript` headings for the hidden code blocks.
Thanks both! I would go for "info string" here for now. We can discuss separately later if you like.

* See also in CommonMark: https://spec.commonmark.org/0.28/#info-string

2023-11-22 12:02 UTC, pepelsbey approved these changes

2023-11-22 13:45 UTC, bsmth commented
Thanks, both. Going to merge now 🎉

2023-11-22 13:45 UTC, merged