[WIP] Replace `create-react-app` with Vite
mdn/content pull request #30177
Opened 2023-11-10 06:26 UTC by mxmason

## Description
As it says on the tin!

This PR is not complete, but I wanted to create something for reviewers to look at before it got too far. Also, since this work will be part of a body of significant changes, should we work off of a staging or development branch of some sort until we're ready to publish?

I'd be fine with turning this branch into the development branch for the overall update project, or with anything the maintainers would like me to do!

2023-11-10 09:35 UTC, chrisdavidmills commented
> This PR is not complete, but I wanted to create something for reviewers to look at before it got too far. Also, since this work will be part of a body of significant changes, should we work off of a staging or development branch of some sort until we're ready to publish?
> 
> I'd be fine with turning this branch into the development branch for the overall update project, or with anything the maintainers would like me to do!

Hi @mxmason, nice to see you on here!

So, we don't really have staging for MDN content; we just work off of a fork taken from main, and then merge it in. You will notice that the environment auto-generates preview URLs so we can see what the rendered content looks like without having to build the branch locally and render it: https://github.com/mdn/content/pull/30177#issuecomment-1805176283

In terms of process for this work, there are no hard and fast rules, but I'm happy to figure out a process that works for the both of us. I usually work with single giant PRs for my changes, but that is changing, as reviewers tend to find that unwieldy, plus it takes longer to produce the first draft to review.

One system that has worked in the past (which I did for the WebGPU reference docs) is to:

1. Create a separate PR for each unit of work (per page would probably work here), clearly labeled "DO NOT MERGE", and test and review each article separately.
2. When each component PR has been reviewed, updated, and approved, merge each one into a single final PR.
3. Do a final walkthrough of the pages to make sure they all work together in this PR (usually this is a good place to spot broken links and continuity errors), ad make final changes.
4. Merge the final PR

Would this work for you? The disadvantage here is that it is harder to check whether each subsequent page is consistent with the ones that came before. You just need to have the preview pages from the previous PRs open in separate tabs to refer to as you review each one. But, it is OK.

Or we could do a kind of hybrid approach, where either you do a couple of pages per PR, and/or maybe merge each approved PR into the next PR in the sequence as it is approved.

What option do you prefer? Or do you have another idea?

2023-11-13 08:37 UTC, chrisdavidmills commented
> Hello, @chrisdavidmills! 💜
> 
> Thanks for explaining our options. I figured you might not have a staging branch, but I thought I should ask. If it works for you, could we do an approach in which this branch (or a new one, I'm not fussed) is the trunk for all our content changes, and we merge subsequent PRs into it? Would your CI tools build previews for those, or does it only build if the PR is based on `main`?

Sure, this sounds good to me. As far as I know, the CI tools should build previews for all of those, yes.

> One example of what I'm thinking:
> 
>     1. I continue working on this page in this branch. You review & approve when it's ready
> 
>     2. I base my next PR off of this branch. You approve & review. I merge that branch down into this one
> 
>     3. I again base a PR off the updates done to this branch, and merge into this branch when those changes are done
> 
>     4. Repeat until we're ready for release, at which point we merge into main
> 
> 
> Does that make sense/is it doable? It sounds kind of like your final suggestion, but I wanna be super sure I understand :)

Yes, this sounds good to me. Let's do it!

2023-11-16 04:11 UTC, mxmason commented
Hello, @chrisdavidmills! I've done broad edits of this whole page, so I think we're ready for a review.

The content in this file hits the same points as before, with the largest changes being related to Vite, and the fact that Vite provides different boilerplate than create-react-app does. Some questions:

- Are we still ok with how much boilerplate we're asking folks to create and then throw away? It crossed my mind that MDN could host its own template repo for this lesson, and that repo could be cloned with a tool like `degit`. I'd be happy to do this, but would also understand if you think the effort of creating and maintaining our own template isn't worth it.
- We still have to capture a new "this is what the app should look like" screenshot asset for this page. I wanted to hold off on that until I confirmed that we do in fact want to keep this template
- While editing some of the old code samples here, I saw references to line numbers, but we don't provide line numbers in rendered markup :( am I missing any syntax that would allow this, or is this a shortcoming of the `yari` server? Do I need to make a pull request there, because I totally will 👀

2023-11-16 12:16 UTC, chrisdavidmills requested changes
Ok, that'll do for now for my first review. Quite a few comments here @mxmason, but barring a couple, nothing serious and mostly just grammar/language suggestions.

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Declare a new variable, `subject`, before the return statement and set its value to the string `'React'`. Like this:
Also, for tutorial steps, you might want to consider numbered and indenting. I think this is the style we've used elsewhere in the tutorial set.

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Add a prop of `subject` to the `<App />` component call, with a value of `Clarice`. When you are done, your code should look something like this:
```suggestion
Add a prop of `subject` to the `<App />` component call, with a value of `Clarice`. When you are done, it should look something like this:
```

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +    <App subject="Clarice" />
Just show this line; no need to show the whole file.

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
>  function App() {
I don't think you need to show what it looks like before the change. Just show the after view of it.

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +With this change, `subject` becomes undefined, so comment out the line `Hello, {subject}!` for now. Save your file and check your browser's JavaScript console. You should see something like this logg
In JSX, it is immediately not so obvious how to comment out a line of code. Maybe tell the reader to just delete that line for now, or show how to do it?

2023-11-16 12:16 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Now that `subject` is one of our props, let's utilize it in `App.jsx`. Change the `subject` constant so that, instead of defining it as the string `React`, you are reading the value of `props.subject
```suggestion
Now that `subject` is one of our props, let's utilize it in `App.jsx`. Update your code so that you are reading the `subject` value from `props.subject` rather than the string literal we defined previously. You can also delete the `console.log()` statement. Your code should look like this:
```

2023-11-16 12:21 UTC, chrisdavidmills commented
@mxmason and some responses to your questions:

> Are we still ok with how much boilerplate we're asking folks to create and then throw away? It crossed my mind that MDN could host its own template repo for this lesson. I'd be happy to do this, but would also understand if you think the effort of creating and maintaining our own template isn't worth it.

I think it Is fine. It really isn't very much boilerplate, and I think it is useful to give the reader the experience of using the command line and delivering into the code. Plus, if we created a template repo we'd have to decide where to put it, and that would create another thing we have to maintain.

> We still have to capture a new "this is what the app should look like" screenshot asset for this page. I wanted to hold off on that until I confirmed that we do in fact want to keep this template

Yup, capture away ;-)

> While editing some of the old code samples here, I saw references to line numbers, but we don't provide line numbers in rendered markup :( am I missing any syntax that would allow this, or is this a shortcoming of the yari server? Do I need to make a pull request there, because I totally will 👀

No, we don't use line numbers anymore. Old Kuma MDN used to do this, but I'm not sure if yari does. Also, I seem to remember line numbers being a pain because you'd inevitably change the code example, then have to remember to update all the line number references to suit. Absolute pain. Also, if your code blocks are big enough that you need line numbers to help readers navigate them, they are really too big.

2023-11-17 05:16 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +In order to use Vite, you need to have [Node.js](https://nodejs.org/en/) installed. As of Vite 5.0, at least Node version 18 or later is required, and it's a good idea to run the latest long term sup
Not super thrilled with this section. I want to say more about Node, but it was also hard to identify the right level of detail before it gets way too out-of-scope for this tutorial.

2023-11-17 05:19 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +With this in place, your app will open in your browser at `http://localhost:3000` every time you run `npm run dev`.
Ah, yes. Sorry about that! It didn't work for you because of a subtle syntax difference, which I've now noted in the article: the extra `--` to separate commands and args is only necessary when running _npm_ commands; it is not necessary if you're calling a program and passing an arg directly into it. Your "dev" command should be `"dev": "vite --open --port 3000"`

2023-11-17 05:25 UTC, mxmason reviewed
Thanks for your thorough review as always, @chrisdavidmills! The proverbial ball is in your court!

2023-11-17 05:25 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +In order to use Vite, you need to have [Node.js](https://nodejs.org/en/) installed. As of Vite 5.0, at least Node version 18 or later is required, and it's a good idea to run the latest long term sup
Not super thrilled with this section on Node I want to say more, but it was also hard to identify the right level of detail before it gets way too out-of-scope for this tutorial.

2023-11-17 05:25 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The npm package manager comes with a `create` command that allows you to create new projects from templates. We can use it to create a new app from Vite's standard React template. Make sure you `cd`
I replaced your suggestion of "hard drive" with "machine" here. Technically, very few computing devices these days have hard drives ;)

2023-11-17 05:25 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +## Practice with JSX
This section is now much more robust than before, and I think it moves through concepts in a better order if I do say so myself.

2023-11-17 05:27 UTC, mxmason commented
On replacing the "here's the app" screenshot: I have two candidates for you: one light mode and one dark mode. Let me know which one you like, or if you want a window at specific dimensions. I'll add whatever we settle on directly to the repo :)

![vite_ff_light](https://github.com/mdn/content/assets/13525251/28f02dc7-4b4a-4bbb-ac63-5d4cc374da01)
![vite_ff_dark](https://github.com/mdn/content/assets/13525251/ee829b0a-ac15-43fa-b52e-5f7e46bfe961)

2023-11-17 13:31 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +It's possible to [add React to an existing project](https://react.dev/learn/add-react-to-an-existing-project) by copying some [`<script>`](/en-US/docs/Web/HTML/Element/script) elements into an HTML f
@mxmason Ah, something just struck me as I was reviewing this — some bits have been written "you/your" and some bits have been written "we/our". It looks like you wrote it so that the former is generally used in general discussions, and the latter is generally used during tutorial instruction sections.

The usual style on MDN tends to be "you/your", so it might make sense for you to review it with this in mind, and change bits that make sense.

I don't think we should worry about changing article titles, as that would require us to modify the sidebar macro, which would be annoying ;-)

2023-11-17 14:19 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The final statement imports the CSS related to our App component. Note that there is no variable name and no `from` directive. This is called a [_side-effect import_](/en-US/docs/Web/JavaScript/Refer
Still needs actioning.

2023-11-17 14:20 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
>  ## Exploring our first React component — \<App/>
Stills needs actioning

2023-11-17 14:30 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +With this change, `subject` becomes undefined, so comment out the line `Hello, {subject}!` for now. Save your file and check your browser's JavaScript console. You should see something like this logg
It looks like this is still an issue in the new draft.

2023-11-17 14:31 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +In order to use Vite, you need to have [Node.js](https://nodejs.org/en/) installed. As of Vite 5.0, at least Node version 18 or later is required, and it's a good idea to run the latest long term sup
I think this level of detail is fine.

2023-11-17 14:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The npm package manager comes with a `create` command that allows you to create new projects from templates. We can use it to create a new app from Vite's standard React template. Make sure you `cd`
Aye, makes sense ;-)

2023-11-17 14:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +## Practice with JSX
Looks fabulous. I'll work through it again and see if I've got any comments on the new sections.

2023-11-17 14:35 UTC, chrisdavidmills commented
> Let me know which one you like

@mxmason for the screenshot update, I like the dark mode one best (I am a metalhead, so no surprise there). I think the width is fine, but you should consider taking it with a smaller window height, so all the content is visible but there is less blank space above and below the content.

2023-11-17 15:09 UTC, chrisdavidmills requested changes
@mxmason A few more comments for you, but only small things. This is looking great; we are nearly there now!

2023-11-17 15:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Now that `subject` is one of our props, let's utilize it in `App.jsx`. Un-comment the `Hello, {subject}!` line and change it to be `Hello, {props.subject}!` instead, then delete the `console.log()` s
```suggestion
Now that `subject` is one of our props, let's use it in `App.jsx`. Uncomment the `Hello, {subject}!` line and change it to `Hello, {props.subject}!`, then delete the `console.log()` statement. Your code should look like this:
```

2023-11-17 15:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +    <>
This code snippet doesn't match the text instructions. Get rid of the `const` and put the `props.subject` inside the `<h1>` instead.

2023-11-17 15:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +For additional practice, you might try adding a `greeting` prop to the `<App />` component and using it alongside the `subject` prop.
```suggestion
For additional practice, you could try adding an additional `greeting` prop to the `<App />` component call inside `main.jsx` and using it alongside the `subject` prop inside `App.jsx`.
```

2023-11-17 15:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +When you save, the app should now greet you with "Hello, Clarice!". If you return to `index.jsx`, edit the value of `subject`, and save, your text will change.
Oop, `index.jsx` should be `main.jsx`. There are a couple of instances to change.

2023-11-17 15:14 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +**Props** are a means of passing data into a React component. Their syntax is identical to that of attrributes, in fact: `prop="value"`. The distinction between them is subtle: attributes are passed
@chrisdavidmills I just spent time talking about attributes in the context of JSX. I don't think bringing "HTML" back here is helpful; nor is HTML the only relevant language with attributes

2023-11-17 15:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +**Props** are a means of passing data into a React component. Their syntax is identical to that of attrributes, in fact: `prop="value"`. The distinction between them is subtle: attributes are passed
Good call; I've updated my change suggestion to omit the instances of HTML

2023-11-20 05:38 UTC, mxmason reviewed
Back to you, @chrisdavidmills! Let me know what you think of the new screenshot!

2023-11-20 05:38 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +> **Note:** You _don't_ need the extra `--` here because we're passing arguments directly to `vite`, rather than to a pre-defined npm script.
🔍 How's this for the explanation about why `--` isn't necessary?

2023-11-20 05:38 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Back in `App.jsx`, let's revisit the `App()` function. Change the signature of `App()` so that it accepts `props` as a parameter and log `props` to the console so you can inspect it. Also delete the
🔍 Everything from here to "Let's use this `subject` prop..." has been slightly edited, hopefully to make the steps and results of those steps a little clearer

2023-11-20 05:38 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +        </button>
🔍 You mentioned possibly deleting this, but I think leaving it is fine. In the next lesson, we promptly ask the reader to delete and replace the contents of this file (and others)

2023-11-20 05:38 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +## Exploring our first React component — `<App />`
🔍  I decided to go with placing `<App />` in a code element for consistency. I don't _think_ I missed any other instances of things that belong in code.

2023-11-20 05:48 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +It's possible to [add React to an existing project](https://react.dev/learn/add-react-to-an-existing-project) by copying some [`<script>`](/en-US/docs/Web/HTML/Element/script) elements into an HTML f
Good point, @chrisdavidmills. I think I wrote the entire tutorial in this way 😵. If you think it's worthwhile to spend time cleaning up the way we (;-D) address the audience, I can do that, but I think it would require more changes to more parts of the tutorial than we previously anticipated. I wasn't expecting to need to update _most_ of the tutorial, beyond the parts that reference code from `create-react-app`

2023-11-20 07:47 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +It's possible to [add React to an existing project](https://react.dev/learn/add-react-to-an-existing-project) by copying some [`<script>`](/en-US/docs/Web/HTML/Element/script) elements into an HTML f
Yeah, true. In which case, just disregard this comment and carry on as you were. If we later decide that we want to reexplore this, we can always do it in a subsequent update without needing your attention on it.

2023-11-20 08:00 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +> **Note:** You _don't_ need the extra `--` here because we're passing arguments directly to `vite`, rather than to a pre-defined npm script.
Yup, perfect!

2023-11-20 08:03 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +> **Note:** You _don't_ need the extra `--` here because we're passing arguments directly to `vite`, rather than to a pre-defined npm script.
Screenshot looks good too.

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +> **Note:** If your text editor understands how to parse JSX (most modern editors do!), you can use its built-in commenting shortcut – `Ctrl + /` (on Windows) or `Cmd + /` (on macOS) to create commen
```suggestion
> **Note:** If your code editor understands how to parse JSX (most modern editors do!), you can use its built-in commenting shortcut — `Ctrl + /` (on Windows) or `Cmd + /` (on macOS) — to create comments more quickly.
```

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +Let's use this `subject` prop to fix the error in our app. Un-coment the `Hello, {subject}!` line and change it to `Hello, {props.subject}!`, then delete the `console.log()` statement. Your code shou
```suggestion
Let's use this `subject` prop to fix the error in our app. Uncomment the `<h1>Hello, {subject}!</h1>` line and change it to `<h1>Hello, {props.subject}!</h1>`, then delete the `console.log()` statement. Your code should look like this:
```

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +        </button>
Agreed, leaving it in is fine.

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +        <h1>Hello, {subject}</h1>
```suggestion
        <h1>Hello, {props.subject}!</h1>
```

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +### The export statement
```suggestion
### The `export` statement
```

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
>  ### The App component
```suggestion
### The `App()` function
```

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
>  ### The App component
Also, you should do a search and replace — whenever you are talking specifically about the App function, you should write it with parens — `App()`

2023-11-20 08:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +## Exploring our first React component — `<App />`
I did spot a couple; commented.

2023-11-20 08:26 UTC, chrisdavidmills requested changes
@mxmason couple more little comments for you. This is so close now!

2023-11-20 08:27 UTC, chrisdavidmills commented
@mxmason ooop, small reminder too — you still need to add a line to explain what Rollup is.

2023-11-21 01:15 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The final statement imports the CSS related to our `App` component. Note that there is no variable name and no `from` directive. This is called a [_side-effect import_](/en-US/docs/Web/JavaScript/Ref
@chrisdavidmills Rather than explain yet more things (not just Rollup, but also what a bundler _is_), I've opted for this instead. I'm happy to mention Rollup by name and explain the concept of a bundler if you feel strongly about it.

2023-11-21 01:44 UTC, mxmason reviewed
Once again to you, @chrisdavidmills

2023-11-21 01:44 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The `package.json` and `package-lock.json` files contain metadata about our project. These files are not unique to React applications: Vite populated `package.json` for us, and npm created `package-l
These paragraphs are a little more complete. I mention the `assets` directory within `src` and acknowledge the `package.json` lockfile, with some links.

2023-11-21 01:44 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The final statement imports the CSS related to our `<App />` component. Note that there is no variable name and no `from` directive. This is called a [_side-effect import_](/en-US/docs/Web/JavaScript
Rather than explain yet more things (not just Rollup, but also what a bundler _is_), I've opted for this instead. I'm happy to mention Rollup by name and explain the concept of a bundler if you feel strongly about it.

2023-11-21 01:44 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +We then call the `ReactDOM.createRoot()` function, which defines the root node of our application. This takes as an argument the DOM element inside which we want our React app to be rendered. In this
I replaced bare mentions of `App` with `App()` where appropriate, but because there is a blend of styles in this file, I thought this line might help to disambiguate `App()` (a function) from`<App />` (a component). Might be worth an additional note about how functions _are_ components, but I'm not sure how exactly you'd like to tackle that. The conceptual difference is subtle.

2023-11-21 09:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The `package.json` and `package-lock.json` files contain metadata about our project. These files are not unique to React applications: Vite populated `package.json` for us, and npm created `package-l
Looking good.

2023-11-21 09:35 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +The final statement imports the CSS related to our `<App />` component. Note that there is no variable name and no `from` directive. This is called a [_side-effect import_](/en-US/docs/Web/JavaScript
Nope, this is fine. I think you've made a good choice here. It isn't necessary to go into bundlers at all.

2023-11-21 09:36 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/index.md
> +We then call the `ReactDOM.createRoot()` function, which defines the root node of our application. This takes as an argument the DOM element inside which we want our React app to be rendered. In this
I did make a few tweaks to help this a bit, but I think what we have here is good. You might want to check my "Small App() related tweaks" commit just to make sure you are happy.

2023-11-21 09:39 UTC, chrisdavidmills approved these changes
@mxmason LGTM! Ready to go on to the next one ;-)

Let me know if you need me to do anything to get the process set up for the next stage.

2023-11-21 23:50 UTC, mxmason commented
So, @chrisdavidmills: I think we have hit an impasse with my proposed strategy for managing PRs: if I use this branch as a base for a new PR, the pull request will be opened against *my* fork, not against MDN's repo – you can see this [here](https://github.com/mxmason/mdn-content/compare/ej/react/vite...mxmason:mdn-content:ej/react-rewrite-2?expand=1). Can you create some kind of `react-rewrite` or other dev branch for us to work in? If not, I think we have to go with your suggestion of opening a bunch of unrelated PRs against `main`.

Whatever you'd like to do, that branch is basically ready for you to look at!

2023-11-22 09:02 UTC, chrisdavidmills commented
> So, @chrisdavidmills: I think we have hit an impasse with my proposed strategy for managing PRs: if I use this branch as a base for a new PR, the pull request will be opened against _my_ fork, not against MDN's repo – you can see this [here](https://github.com/mxmason/mdn-content/compare/ej/react/vite...mxmason:mdn-content:ej/react-rewrite-2?expand=1). Can you create some kind of `react-rewrite` or other dev branch for us to work in? If not, I think we have to go with your suggestion of opening a bunch of unrelated PRs against `main`.
> 
> Whatever you'd like to do, that branch is basically ready for you to look at!

OK, so here is a thought. We could do the same thing as I have been doing for my Google MDN work, in which I get the technical review done in one PR, then close that PR and open another one based on the same branch to do the editorial review in.

So, each time one of your new articles is reviewed and approved, I close the PR, open another one based on the same branch, and you carry on your work in that for the next article. Each PR would only contain the comments for a single article, saving all the confusion of having all comments in one PR.

What do you think?

2023-11-22 10:05 UTC, mxmason commented
Oh, I like that! I've never really worked on a branch after closing a PR so this wouldn't have crossed my mind. Let's do it!

2023-11-22 10:17 UTC, chrisdavidmills commented
> Oh, I like that! I've never really worked on a branch after closing a PR so this wouldn't have crossed my mind. Let's do it!

Great, I'll set this up then. I'll close this and create a fresh PR for you to continue working in.

2023-11-22 10:48 UTC, chrisdavidmills commented
> > Oh, I like that! I've never really worked on a branch after closing a PR so this wouldn't have crossed my mind. Let's do it!
> 
> Great, I'll set this up then. I'll close this and create a fresh PR for you to continue working in.

OK, scratch that. For some reason, your fork won't show up in the list of forks to compare against when I try to create a new PR based on it. I can't figure out why. This is really annoying.

So how about you create a new fork based on mdn/content and do the second article update in it (or more if it ends up being a small update), and then we'll keep this one open, and make a note on each subsequent one to not merge it until the previous one has been merged. Each time we merge one we'll update the next one against the base branch and make sure there are no conflicts before merging it, etc.?

2023-11-22 15:14 UTC, mxmason commented
Terrible of GitHub to do this to us! Your suggestion works for me. I'll realign my branch with main and open a PR in a few.

2023-12-21 10:59 UTC, merged