docs(CSS): Add color spaces, color models, examples using lch() and lab()
mdn/content pull request #30180
Opened 2023-11-10 14:32 UTC by bsmth

### Description

This PR adds a little more detail to "Applying color to HTML elements using CSS" guide and gives some hints on `<hue>` and working with color wheels etc.

### Motivation

As with https://github.com/mdn/content/pull/30074, we talk about `rgb()`, hex and named colors, but we omit some other functions that might be interesting.

__Related issues and pull requests:__

- [ ] https://github.com/mdn/content/pull/30074
- [ ] https://github.com/mdn/content/pull/29941

2023-11-15 14:18 UTC, pepelsbey commented on files/en-us/web/css/css_colors/applying_color/index.md
> +  grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr;
```suggestion
  grid-template-columns: repeat(6, 1fr);
```

It makes this a bit more readable.

2023-11-16 11:27 UTC, teoli2003 requested changes
A few grammar fixes.

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +The `hsl()` and `hwb()` functions we've used above use the sRGB color space and both use **cylindrical** models, and this why a `<hue>` angle let's you control the color's properties like on a [color
A few grammar fixes.

```suggestion
The `hsl()` and `hwb()` functions we've used above use the sRGB color space, and both use _cylindrical_ models; this is why a `<hue>` angle lets you control the color's properties like on a [color wheel](/en-US/docs/Glossary/Color_wheel).
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +The third row changes the `lab()` "b" axis, so we have a different resulting effect than `lch()` as we're actually gradually adding more yellow to the color rather than cycling through the entire col
```suggestion
The CIELAB and Oklab color spaces are based on human vision experiments and represent the entire range of colors that humans can see.
The primary purpose of these models is that they are uniform so that a given distance between any two points in the color space should appear equally different to a viewer.

For the CIELAB color space, you can use the `lab()` and `lch()` functions.
The `lch()` function uses lightness (L), chroma (C), and hue (H) and the Lab model uses lightness (L), red/green-ness, and yellow/blue-ness along the "a" and "b" axes (rectangular coordinates) in the color space.

The example below shows how the effect of these two functions where each row modifies a single component.
The first row shows changes to the `lch()` lightness value, while the second row changes the `lch()` hue component.
The third row changes the `lab()` "b" axis, so we have a different effect than `lch()` as we're gradually adding more yellow to the color rather than cycling through the entire color wheel:
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +If you already understand `lab()` and `lch()`, you can use these functions in a similar way:
"newer" will not age well.
```suggestion
Oklab is a color space that uses the same model type as CIELAB. Still, it is optimized based on data of visually similar colors, so the values are intended to be more accurate than CIELAB.
If you already understand `lab()` and `lch()`, you can use these functions in a similar way:
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +#### The color function
```suggestion
#### The `color()` function
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +For example, if we wanted to show the `display-p3 0 0 1` color which is outside of the sRGB gamut, you can use a [`@media`](/en-US/docs/Web/CSS/@media/color-gamut) at-rule for detecting if the client
```suggestion
This is useful to describe a color for high-definition devices with wider color [gamuts](/en-US/docs/Glossary/Gamut).
For example, if we wanted to show the `display-p3 0 0 1` color, which is outside of the sRGB gamut, you can use a [`@media`](/en-US/docs/Web/CSS/@media/color-gamut) at-rule for detecting if the client hardware supports colors in this range:
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +A set of standard color names are defined that let you use keywords instead of numeric representations if you choose this way of describing colors, although there must be a keyword representing the e
```suggestion
A set of standard color names is defined that lets you use keywords instead of numeric representations if you choose this way of describing colors, although there must be a keyword representing the exact color you want to use. Color keywords include the standard primary and secondary colors (such as `red`, `blue`, or `orange`), shades of gray (from `black` to `white`, including colors like `darkgray` and `lightgrey`), and a variety of other blended colors, including `lightseagreen`, `cornflowerblue`, and `rebeccapurple`.
```

2023-11-16 11:27 UTC, teoli2003 commented on files/en-us/web/css/css_colors/applying_color/index.md
> +As the value of luminance (or lightness) increases, the color transitions from the darkest possible to the brightest possible (from black to white).
```suggestion
Designers and artists often prefer to work using the [HSL](https://en.wikipedia.org/wiki/HSL_and_HSV) (Hue/Saturation/Luminosity) color method.
The `hsl()` CSS function is similar to the `rgb()` function in usage otherwise.

The diagram below shows an HSL color cylinder. Hue defines the color as an [`<angle>`](/en-US/docs/Web/CSS/angle) on a circular {{glossary("color wheel")}}.
Saturation is a percentage of how much of the way between being a shade of gray and having the maximum possible amount of the given hue.
As the value of luminance (or lightness) increases, the color transitions from the darkest to the brightest possible (from black to white).
```

2023-11-16 13:10 UTC, bsmth commented on files/en-us/web/css/css_colors/applying_color/index.md
> +The `hsl()` and `hwb()` functions we've used above use the sRGB color space and both use **cylindrical** models, and this why a `<hue>` angle let's you control the color's properties like on a [color
super, ty

2023-11-16 13:12 UTC, bsmth commented
> A few grammar fixes.

Great suggestions, thank you. Applied in https://github.com/mdn/content/pull/30180/commits/dc30e34bf4f710c32ff7130892329a4c290ac9c8

2023-11-16 13:26 UTC, bsmth commented on files/en-us/web/css/css_colors/applying_color/index.md
> +The example below shows how the effect of these two functions where each row modifies a single component.
```suggestion
The example below shows the effect of changing component values in the `lab()` and `lch()` functions where each row modifies a single component.
```

2023-11-16 13:37 UTC, bsmth commented on files/en-us/web/css/css_colors/applying_color/index.md
> +Oklab is a color space that uses the same model type as CIELAB. Still, it is optimized based on data of visually similar colors, so the values are intended to be more accurate than CIELAB.
```suggestion
Oklab is a color space that uses the same model type as CIELAB but is created using additional optimization stages, so the values are intended to be more accurate than CIELAB.
```

The dirty details:

>Now, OKLab was developed by generating pairs of colors (in CAM16-UCS) which had either the same Lightness, or the same Hue, or the same Chroma converting them to the new color space and then swapping the coordinate that was supposed to be the same in each pair and computing the difference using deltaE 2000.
>Numerical optimisation was then used to minimize the error. (https://www.w3.org/Graphics/Color/Workshop/slides/talk/lilley)

2023-11-16 15:06 UTC, teoli2003 approved these changes
👍

2023-11-16 15:16 UTC, bsmth commented
Thank you, merging shortly 👍🏻

2023-11-16 15:26 UTC, merged

2025-03-25 01:13 UTC, Moreau-take commented
> Thank you, merging shortly 👍🏻 

A merge every year from now and then.🤓