add {{availableInWorker}} to File System API
mdn/content pull request #30191
Opened 2023-11-10 19:48 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-11-13 13:14 UTC, bsmth reviewed
Just a note: FileSystemSyncAccessHandle looks like it's in dedicated workers only, I don't think we have a way to indicate this (https://fs.spec.whatwg.org/#api-filesystemsyncaccesshandle).

2023-11-13 13:15 UTC, bsmth approved these changes
Looks good to me, thank you! 🎉

2023-11-13 17:22 UTC, skyclouds2001 commented
> Just a note: FileSystemSyncAccessHandle looks like it's in dedicated workers only, I don't think we have a way to indicate this (https://fs.spec.whatwg.org/#api-filesystemsyncaccesshandle).

Yes, as I issue in https://github.com/mdn/yari/issues/10009, if {{availableInWorker}} could support to specific the type of the worker

2023-11-15 12:02 UTC, teoli2003 requested changes
Given the PR for yari is made, let's wait for it and update the parameter of `{{AvailableInWorkers}}` here.

2023-11-28 14:15 UTC, skyclouds2001 commented on files/en-us/web/api/file_system_api/index.md
>  ---
```suggestion
spec-urls: https://fs.spec.whatwg.org/
---
```

2023-12-07 23:17 UTC, hamishwillee commented
`{{AvailableInWorkers}}` should be applied at the end of the first section, not at the start like the other headers. This is not documented anywhere but is done consistently that way across most of the reference.

FWIW personally I disagree with this - all headers should be together up the top. But without broad agreement on that we should stick with what has already been done.

2024-01-09 09:32 UTC, bsmth approved these changes
Re-approving in case we don't want to wait for the blocking PR: https://github.com/mdn/yari/pull/10029

2024-01-09 14:31 UTC, teoli2003 commented
I don't know when Yari's people will return to the holiday period. It would be nice if we didn't need extra work here.

2024-03-31 15:37 UTC, skyclouds2001 commented
as https://github.com/mdn/yari/pull/10029 has been merged yet, the update to the {{AvailableInWorkers}} macros has done yet

2024-04-05 07:17 UTC, teoli2003 approved these changes
👍  Patience is a virtue. Really happy we can merge this now!

2024-04-05 07:23 UTC, merged