relnote(120): Zulu timezone for non-ISO `Date.parse` formats
mdn/content pull request #30235
Opened 2023-11-13 10:35 UTC by vinnydiehl

### Entry

(under the parent bullet point for the previous `Date.parse` fixes):

  - Timezone `'Z'` is now accepted for non-ISO formats (e.g. `Jan 1 1970 10:00Z`)

### Bugzilla

https://bugzilla.mozilla.org/show_bug.cgi?id=1852422

2023-11-13 22:46 UTC, hamishwillee commented
1. This is cool, but we should also update https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#non-standard_date_strings with information about this
2. If there are browser compatibility differences then it would be great to add https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#browser_compatibility
3. Ditto for #30234

@zfox23 I assigned to you because I saw you did the previous work.

@vinnydiehl FYI You may already have had this discussion with someone, but if you see a bug that has a docs implication, can you please add the keyword `dev-doc-needed`. This allows the MDN team to pick it up when we come to do the docs for a release - we ensure that the release note, browser compatibility and docs are done are up to date at that point. I did this for this issue #30234. When we are done we change that to `dev-doc-complete` so everyone knows the work is done. We normally also cross link the bug to the MDN tracking work - for me these look something like this: https://github.com/mdn/content/issues/29778

2023-11-14 06:22 UTC, vinnydiehl commented
> we should also update https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#non-standard_date_strings with information about this

I've checked the patterns already in there and there are some of them already in there which are out of date.

I can certainly add information about some of the new formats which are being supported. Does it matter that some of these formats only work in pre-release versions of Firefox right now?

Thanks for the heads up on the `dev-doc-needed` tags, I've gone through and tagged all of the bugs in these last 2 PRs.

2023-11-15 16:23 UTC, zfox23 commented
Thank you for your contribution :)

> > we should also update https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#non-standard_date_strings with information about this
> 
> I've checked the patterns already in there and there are some of them which are out of date.
> 
> I can certainly add information about some of the new formats which are being supported. Does it matter that some of these formats only work in pre-release versions of Firefox right now?

It would be _super_ helpful if you could please fix content that is out-of-date and add some of the newly-supported formats. It'd be great for you to include a comment in the JS code snippet that included data about the way the dates are parsed across browsers.

With respect to time and parsing time, keeping a BCD-like table of what happens in what browser given a specific date format is going to be a maintenance nightmare. In my opinion, the "This section contains implementation-specific behavior that can be inconsistent across implementations" note coupled with the comments in the example snippet are sufficient to keep folks on their toes about the _utter confusion_ that is the human concept of **"Time"**.

I will keep my eyes out for updates to this PR. Thanks again.

2023-11-17 17:17 UTC, zfox23 requested changes

2023-11-17 17:17 UTC, zfox23 commented on files/en-us/mozilla/firefox/releases/120/index.md
> +  - Timezone `'Z'` is now accepted for non-ISO formats (e.g. `Jan 1 1970 10:00Z`)
Pinging this PR , and also adding a suggestion to add the Bugzilla link:

```suggestion
  - Timezone `'Z'` is now accepted for non-ISO formats (e.g. `Jan 1 1970 10:00Z`) ([Firefox bug 1852422](https://bugzil.la/1852422))
```

@vinnydiehl, would you prefer to address the previous comments in this PR over the next couple of days pertaining to non-standard date strings, or would you prefer to merge this now and address those comments later?

2023-11-18 08:52 UTC, vinnydiehl commented
Hi Zach! Thanks for adding Bugzilla links on this and my other relnote.

Since the updates in the JS reference will not be necessarily limited to the changes in either of these relnotes, and involve existing points which are outdated, I think it'd be best to do the work in a separate PR. I've opened #30363 to track this work.

2023-11-20 15:09 UTC, zfox23 approved these changes

2023-11-20 15:17 UTC, merged