RTCTransportStats - create docs
mdn/content pull request #30231
Opened 2023-11-13 06:24 UTC by hamishwillee

This adds docs for `RTCTransportStats`

Currently draft while I work out exactly what the spec means.

2023-11-13 06:26 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +  - : A string containing the local certification <!-- For components where DTLS is negotiated -->
I'm trying to work out what this comment " For components where DTLS is negotiated " means. It likely means "only if the transport is DTLS, but it could mean "after the connection is negotiated".

2023-11-13 06:26 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +  - : A string Xxxx
FYI Xxxx in this means still thinking about it. In this case the text is often spec text.

2023-11-13 06:27 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +This example shows a function to return the transport statistics, or `null` if no statistics are provided.
Basic example. Not sure how realistic it is.

2023-12-12 05:29 UTC, wbamberg requested changes, later dismissed

2023-12-12 05:29 UTC, wbamberg commented on files/en-us/web/api/rtctransportstats/index.md
> +  - : A string indicating the [ICE `role`](/en-US/docs/Web/API/RTCIceTransport/role) of the underlying {{domxref("RTCDtlsTransport.iceTransport")}}: `controlling` or `controlled`.
"unknown" also seems to be a value? https://www.w3.org/TR/webrtc/#dom-rtcicerole

I would spell this out a bit more, like:

```suggestion
  - : A string indicating the [ICE `role`](/en-US/docs/Web/API/RTCIceTransport/role) of the underlying {{domxref("RTCDtlsTransport.iceTransport")}}. This can be any of the following:
      - `controlling`
      - `controlled`
      - `unknown`
```

2023-12-12 05:29 UTC, wbamberg commented on files/en-us/web/api/rtctransportstats/type/index.md
> +A value of `"transport"` indicates that the statistics available in the current step are those defined in {{domxref("RTCPeerConnectionStats")}}.
```suggestion
A value of `"transport"` indicates that the statistics available in the current step are those defined in {{domxref("RTCTransportStats")}}.
```

I think?

2023-12-15 00:17 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +  - : A string indicating the [ICE `role`](/en-US/docs/Web/API/RTCIceTransport/role) of the underlying {{domxref("RTCDtlsTransport.iceTransport")}}: `controlling` or `controlled`.
Yes, thanks. I took that from the ICE role, which will also need to be updated.

2023-12-15 01:14 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +Note that if remote endpoint is aware of the BUNDLE SDP feature, all {{domxref("MediaStreamTrack")}} and data channels are bundled onto a single transport at the completion of negotiation.
I've spelled it out.

2023-12-15 01:14 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +- `packetsSent` {{optional_inline}}
Done

2023-12-15 01:16 UTC, hamishwillee commented on files/en-us/web/api/rtctransportstats/index.md
> +    - [`failed`](/en-US/docs/Web/API/RTCDtlsTransport/state#failed)
FYI, I've split these all out into their own bullets for consistency with your other comment. Note that I had previously chosen not to do so because I thought people would go to the linked `RTCDtlsTransport.state` for the definition. Just to make it very clear, I have now linked the definitions where they exist.

2023-12-15 17:51 UTC, wbamberg approved these changes
👍 thank you!

2023-12-15 17:51 UTC, merged