remove KeyboardEvent.locale
mdn/content pull request #30305
Opened 2023-11-16 10:34 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-11-16 15:12 UTC, teoli2003 requested changes

2023-11-16 15:12 UTC, teoli2003 commented on files/en-us/web/api/keyboardevent/index.md
> +    > **Note:** This does not describe the locale of the data being entered. A user may be using one keyboard layout while typing text in a different language.
Nobody implemented this and nobody will. We should just delete it. (If somebody does in the future, the writing process will catch it anyway).

Can you delete the entry? (L164-168)

2023-11-17 08:54 UTC, skyclouds2001 commented on files/en-us/web/api/keyboardevent/index.md
> +    > **Note:** This does not describe the locale of the data being entered. A user may be using one keyboard layout while typing text in a different language.
Got it

2023-11-17 09:13 UTC, teoli2003 approved these changes
👍

2023-11-17 09:13 UTC, merged