add `TaskSignal.any`
mdn/content pull request #30314
Opened 2023-11-16 14:20 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2023-12-07 03:57 UTC, wbamberg requested changes
Thank you @skyclouds2001 !

2023-12-07 03:57 UTC, wbamberg commented on files/en-us/web/api/tasksignal/any_static/index.md
> +The **`TaskSignal.any()`** static method takes an iterable of abort signals and returns a {{domxref("TaskSignal")}}. The returned task signal is aborted when any of the abort signals is aborted. The
```suggestion
The **`TaskSignal.any()`** static method takes an iterable of {{domxref("AbortSignal")}} objects and returns a {{domxref("TaskSignal")}}. The returned task signal is aborted when any of the abort signals is aborted.

When the task signal is aborted, its {{domxref("AbortSignal.reason", "reason")}} property will be set to the reason of the first signal that is aborted.
```

(we should talk about `priority` below, don't need to cover it here as well)

2023-12-07 03:57 UTC, wbamberg commented on files/en-us/web/api/tasksignal/any_static/index.md
> +      - : A string which is one of `user-blocking`, `user-visible` and `background`, or an {{domxref("AbortSignal")}} (since {{domxref("TaskSignal")}} inherits from {{domxref("AbortSignal")}}, so a {
```suggestion
      - : One of the following:
        - A string which is one of `user-blocking`, `user-visible` and `background`.
        - A {{domxref("TaskSignal")}}.
```

(I think it can't be an `AbortSignal` (https://wicg.github.io/scheduling-apis/#dictdef-tasksignalanyinit) which makes sense because `AbortSignal` doesn't have a `priority`.)

2023-12-07 03:57 UTC, wbamberg commented on files/en-us/web/api/tasksignal/any_static/index.md
> +A `TaskSignal` instance, its {{domxref("AbortSignal.reason", "reason")}} property will be set to the reason of the first signal that is aborted, and its {{domxref("TaskSignal.priority", "priority")}}
```suggestion
A `TaskSignal` instance. It will be aborted when the first signal passed into `signals` is aborted. When this happens:

- Its {{domxref("AbortSignal.reason", "reason")}} property will be set to the reason of the signal that caused this signal to abort.

- Its {{domxref("TaskSignal.priority", "priority")}} property will be determined by the `priority` parameter:

  - If the `priority` parameter was a string, it will be the value of the string.
  - If the `priority` parameter was a `TaskSignal`, it will be the value of that signal's `priority`.
```

2023-12-10 12:00 UTC, skyclouds2001 commented on files/en-us/web/api/tasksignal/any_static/index.md
> +      - : A string which is one of `user-blocking`, `user-visible` and `background`, or an {{domxref("AbortSignal")}} (since {{domxref("TaskSignal")}} inherits from {{domxref("AbortSignal")}}, so a {
yes, my mistake here. the `priority` can not accept a `AbortSignal`

2023-12-11 22:34 UTC, wbamberg approved these changes
👍 thank you @skyclouds2001 !

2023-12-11 22:34 UTC, merged