Adds explanation in example for the use of clients global
mdn/content pull request #30329
Opened 2023-11-17 05:54 UTC by himanshugarg

### Description

Adds a one-liner to explain the clients global

### Motivation

Low hanging :mango: 

### Additional details

Thanks to @ChristopherWirtOfficial for reporting this and to @Josh-Cena for inputs.

### Related issues and pull requests

Fixes #10573 Issue with "Client.postMessage()": Page does not give a full code example, or enough context to create one

2023-11-17 09:27 UTC, skyclouds2001 commented on files/en-us/web/api/client/postmessage/index.md
>        const client = await clients.get(event.clientId);
```suggestion
      // Get the client
      const client = await self.clients.get(event.clientId);
```

see https://github.com/mdn/content/issues/10573#issuecomment-1816017198

* and i think it is not necessary to update comment, since we have mention `clients` property above yet

2023-11-17 17:37 UTC, wbamberg requested changes
Thank you for the PR, @himanshugarg , and also @skyclouds2001 for helping work this out.

I just had a formatting/editorial suggestion (I hope I have got it right, macro syntax a bit tricky without a preview!). @ChristopherWirtOfficial , does this work for you?

2023-11-17 17:37 UTC, wbamberg commented on files/en-us/web/api/client/postmessage/index.md
> +The code below sends a message from a service worker to a client. The client is fetched using the [get() method](/en-US/docs/Web/API/Clients/get) on [clients](/en-US/docs/Web/API/ServiceWorkerGlobalS
```suggestion
The code below sends a message from a service worker to a client. The client is fetched using the {{domxref("Clients.get()", "get()")}} method on {{domxref("ServiceWorkerGlobalScope.clients", "clients")}}, which is a global in service worker scope.
```

2023-11-18 03:28 UTC, wbamberg approved these changes
👍 thank you @himanshugarg !

2023-11-18 03:28 UTC, merged