Reference for stage 3 promise-with-resolvers
mdn/content pull request #30370
Opened 2023-11-18 21:20 UTC by Josh-Cena

### Description

Part of https://github.com/mdn/content/issues/30334

### Motivation

### Additional details

### Related issues and pull requests

2023-11-20 07:39 UTC, teoli2003 requested changes

2023-11-20 07:42 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +### Calling withResolvers() on a non-Promise constructor
We _allow_ them doesn't mean we _require_ them. My acceptance for code formatting in titles is solely on the ground of disambiguation. Where there's no ambiguity, I don't see the reason to have it—it makes static analysis harder and introduces more inconsistencies than it can fix in the short term.

2023-11-20 07:43 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +  let { promise, resolve, reject } = Promise.withResolvers();
These variables are re-assigned below.

2023-11-20 07:44 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +    }
I find them about the same? This is what for loops desugar to anyway. The following would be terser and perhaps more idiomatic, but it is not as accessible for everyone:

```suggestion
    let chunk;
    while ((chunk = stream.read())) {
      yield chunk;
    }
```

2023-11-20 07:46 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +`Promise.withResolvers()` is a generic method. It can be called on any constructor that implements the same signature as the `Promise()` constructor. For example, we can call it on a constructor that
We can call it (`Promise.withResolvers()`) on a constructor (i.e. the function is called with that constructor as `this`) that passes it (the constructor passes callbacks as parameters to the `executor`; maybe the "it" is confusing?) `console.log` (a function) as `reject` (the parameter).

2023-11-20 07:59 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +  let { promise, resolve, reject } = Promise.withResolvers();
Ha, I wasn't awake

2023-11-20 08:00 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +    }
I prefer a while loop to a for loop, but your one is better than mine.

2023-11-20 08:02 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +`Promise.withResolvers()` is a generic method. It can be called on any constructor that implements the same signature as the `Promise()` constructor. For example, we can call it on a constructor that
I understand now. Maybe:

_that passes TO it `console.log` as `reject`_

2023-11-20 08:03 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +    }
Okay! Glad you like my while loop.

2023-11-23 06:00 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/promise/withresolvers/index.md
> +`Promise.withResolvers()` is a generic method. It can be called on any constructor that implements the same signature as the `Promise()` constructor. For example, we can call it on a constructor that
```suggestion
`Promise.withResolvers()` is a generic method. It can be called on any constructor that implements the same signature as the `Promise()` constructor. For example, we can call it on a constructor that passes `console.log` as the `resolve` and `reject` functions to `executor`:
```

2023-11-23 07:50 UTC, teoli2003 approved these changes
👍

2023-11-23 07:51 UTC, merged