HTTP TRACE - missing field info
mdn/content pull request #30385
Opened 2023-11-19 23:28 UTC by hamishwillee

Fixes #30367

The original is copied from the spec and refers to "fields described below". But "below" just says "don't send sensitive information" so I have integrated that.

2023-11-20 06:38 UTC, teoli2003 commented on files/en-us/web/http/methods/trace/index.md
> +Note that the client must not content in the request, or generate fields that might include sensitive data, such as stored user credentials or cookies.
```suggestion
Note that the client must not send content in the request, or generate fields that might include sensitive data, such as stored user credentials or cookies.
```

2023-11-20 06:39 UTC, teoli2003 requested changes
A verb is missing.

2023-11-21 03:03 UTC, hamishwillee commented on files/en-us/web/http/methods/trace/index.md
> +Note that the client must not content in the request, or generate fields that might include sensitive data, such as stored user credentials or cookies.
Thank you!

2023-11-21 07:22 UTC, teoli2003 approved these changes
👍

2023-11-21 07:22 UTC, merged