feat: Editorial review for Shared Storage API docs
mdn/content pull request #30427
Opened 2023-11-21 09:16 UTC by chrisdavidmills

### Description

https://github.com/mdn/content/pull/28051 contains the engineering technical review for my work on the [Shared Storage API](https://wicg.github.io/shared-storage/) docs, which has been completed and approved. Thank you to @pythagoraskitty for your thorough and detailed review work.

This is a new PR based on the same branch, which is intended to contain the editorial review for the same work.

---

### Background information

The [Shared Storage API](https://wicg.github.io/shared-storage/) is an integral part of Google's [privacy sandbox](https://developer.chrome.com/docs/privacy-sandbox/) technologies. Many parts of this set are being made available by default in Chrome 117 (depending on a gradual ramp-up to 100% of userbase over the 117 release period).

This PR adds content for Shared Storage. See my [research document](https://docs.google.com/document/d/1bCSr2SvUCHzQUQgxgUjDigD-gyXG7f0ClimoNlhxFu8/edit) for information on exactly what features are being added.

### Motivation

### Additional details

### Related issues and pull requests

2023-11-23 15:58 UTC, dipikabh commented
Hi @chrisdavidmills, I can start taking a look at this now

2023-11-23 18:12 UTC, dipikabh requested changes
1 done 🙂. I'll come back shortly for the remaining.

2023-11-23 18:12 UTC, dipikabh commented on files/en-us/web/api/shared_storage_api/index.md
> +To use the Shared Storage API in your sites, you must specify it in the [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment). If you don't do this, none of the met
```suggestion
To use the Shared Storage API in your sites, you must specify it in the [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment). If you don't, the Shared Storage API methods won't run successfully.
```

2023-11-23 18:12 UTC, dipikabh commented on files/en-us/web/api/shared_storage_api/index.md
> +`chrome://flags/#privacy-sandbox-enrollment-overrides`
We usually include the flag info in BCD table. Any way to avoid including this in the main text?

```suggestion
You can test your Shared Storage API code locally without enrollment. To allow local testing, enable the following Chrome developer flag:

`chrome://flags/#privacy-sandbox-enrollment-overrides`
```

2023-11-23 18:12 UTC, dipikabh commented on files/en-us/web/api/shared_storage_api/index.md
> +For extensive demos, see [Shared Storage API demo site](https://shared-storage-demo.web.app/) (which also includes some Private Aggregation API examples).
```suggestion
For extensive demos, see the [Shared Storage API demo site](https://shared-storage-demo.web.app/), which also includes some Private Aggregation API examples.
```

2023-11-24 03:26 UTC, dipikabh requested changes
Completed reviewing a few more...

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/append/index.md
> +> **Note:** If the specified `key` isn't found in shared storage, the `append()` operation is equivalent to {{domxref("SharedStorage.set", "set()")}}, i.e. a new key/value pair is added to storage wi
```suggestion
> **Note:** If the specified `key` isn't found in the shared storage, the `append()` operation is equivalent to {{domxref("SharedStorage.set", "set()")}}, that is, a new key-value pair with the specified `key` is added to the shared storage.
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/append/index.md
> +- In both cases, the `Promise` rejects with a {{jsxref("TypeError")}} if:
```suggestion
- The `Promise` rejects with a {{jsxref("TypeError")}} if:
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/append/index.md
> +  .then(console.log("Value appended to integer list"));
should this be
```suggestion
  .then(() => console.log("Value appended to integer list"));
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/clear/index.md
> +{{domxref("SharedStorage")}} interface clears the current origin's shared storage, removing all data from it.
```suggestion
The **`clear()`** method of the {{domxref("SharedStorage")}} interface clears the current origin's shared storage, removing all data from it.
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/clear/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
similar edits as on append() page

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/clear/index.md
> +- [Shared Storage API](/en-US/docs/Web/API/Shared_storage_API)
```suggestion
- [Shared Storage API](/en-US/docs/Web/API/Shared_Storage_API)
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/set/index.md
> +{{domxref("SharedStorage")}} interface stores a new key/value pair in the current origin's shared storage or updates an existing one.
```suggestion
The **`set()`** method of the {{domxref("SharedStorage")}} interface either stores a new key-value pair in the current origin's shared storage or updates an existing one.
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/set/index.md
> +      - : A boolean value that, if set to `true`, will cause the set operation to abort if a key/value pair with the specified `key` already exists. The default value, `false`, will cause the set ope
`options` object has only one property - `ignoreIfPresent`
```suggestion
- `key`
  - : A string representing the key in the key-value pair that you want to add or update.
- `value`
  - : A string representing the value you want to add or update.
- `options` {{optional_inline}}
  - : An options object containing the following properties:
    - `ignoreIfPresent`
      - : A boolean value. The value `true` causes the set operation to abort if a key/value pair with the specified `key` already exists. The default value `false` causes the set operation to overwrite the previous value.
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/set/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
similar edit suggestions as on append() page

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/delete/index.md
> +- [Shared Storage API](/en-US/docs/Web/API/Shared_storage_API)
```suggestion
- [Shared Storage API](/en-US/docs/Web/API/Shared_Storage_API)
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/delete/index.md
> +{{domxref("SharedStorage")}} interface deletes an existing key/value pair from the current origin's shared storage.
```suggestion
The **`delete()`** method of the {{domxref("SharedStorage")}} interface deletes an existing key-value pair from the current origin's shared storage.
```

2023-11-24 03:26 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/delete/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
similar edit suggestions as on append() page

2023-11-26 19:38 UTC, dipikabh requested changes
Hi @chrisdavidmills, I've completed a readthrough of all files.
- All occurrences of this link need to be updated (storage --> Storage)
`[Shared Storage API](/en-US/docs/Web/API/Shared_storage_API)`
- Also, if you're updating `key/value` pairs, you might want to check all occurrences (key/value pairs --> key-value pairs)

2023-11-26 19:38 UTC, dipikabh commented on files/en-us/web/api/sharedstorageworkletglobalscope/sharedstorage/index.md
> +{{domxref("SharedStorageWorkletGlobalScope")}} interface contains a {{domxref("WorkletSharedStorage")}} object instance representing the shared storage for a particular origin, as it is exposed to a
Would it be correct to say:
```suggestion
The **`context`** read-only property of the
{{domxref("SharedStorageWorkletGlobalScope")}} interface contains a {{domxref("WorkletSharedStorage")}} object instance, which represents the shared storage for a particular origin as exposed to a worklet context.
```

2023-11-26 19:38 UTC, dipikabh commented on files/en-us/web/api/workletsharedstorage/keys/index.md
> +{{domxref("WorkletSharedStorage")}} interface returns an [async iterator](/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator) containing the keys for each item in a `WorkletSharedStora
```suggestion
{{domxref("WorkletSharedStorage")}} interface returns an [async iterator](/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator), which contains the keys for each item in a `WorkletSharedStorage` instance.
```

2023-11-26 19:38 UTC, dipikabh commented on files/en-us/web/api/workletsharedstorage/length/index.md
> +A {{jsxref("Promise")}} that fulfills with a number representing the number of key/value pairs currently in shared storage.
```suggestion
A {{jsxref("Promise")}} that fulfills with a number, which represents the total count of key-value pairs currently in the shared storage.
```

2023-11-26 19:38 UTC, dipikabh commented on files/en-us/web/api/workletsharedstorage/remainingbudget/index.md
> +The navigation budget is the number of bits of entropy permitted inside a {{htmlelement("fencedframe")}} as a result of {{domxref("WindowSharedStorage.selectURL()")}} calls, per origin, per 24-hour t
- There's no "fencedframe" HTML element page. Will this be added as part of fenced frame api?
```suggestion
The navigation budget is the number of entropy bits permitted inside a {{htmlelement("fencedframe")}} due to the {{domxref("WindowSharedStorage.selectURL()")}} calls per origin every 24 hours. This is not the same as the number of navigations; rather, it is based on the number of potential navigations in each call. Each time a `selectURL()` navigation occurs, the budget decreases by the logarithm (base 2) of the number of URL choices from the corresponding origin's budget.
```

2023-11-26 19:38 UTC, dipikabh commented on files/en-us/web/api/workletsharedstorage/remainingbudget/index.md
> +  - : Thrown if the worklet module has not yet been added with {{domxref("Worklet.addModule", "addModule()")}}, or if the calling site does not have the Shared Storage API included in a successful [p
```suggestion
  - : Thrown if the worklet module has not yet been added with {{domxref("Worklet.addModule", "addModule()")}} or if the calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
```

2023-11-27 11:42 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageoperation/index.md
> +The different output gate types are detailed below:
@dipikabh `{{InheritanceDiagram}}` draws an SVG diagram showing the inheritance relationship between this interface and its ancestors, based on the data available in [`InterfaceData.json`](https://github.com/mdn/content/blob/main/files/jsondata/InterfaceData.json). I think it only shows ancestors, not descendents.

If no diagram is rendered, then there is no inheritance to show, in which case it should just be removed. I'll keep this one open so I can do that in my local content repo, while implementing your suggestion at the same time.

2023-11-27 12:29 UTC, chrisdavidmills commented on files/en-us/web/api/windowsharedstorage/index.md
> +_`WindowSharedStorage` inherits properties from its parent interface, {{domxref("SharedStorage")}}._
Not particularly, but I believe this is the style we've used for these lines, for a number of years. 

So I'd like to keep this one as-is, unless of course the style guide for these lines has changed and I didn't know about it.

2023-11-27 12:43 UTC, chrisdavidmills commented on files/en-us/web/api/workletsharedstorage/index.md
> +_`WorkletSharedStorage` inherits properties from its parent interface, {{domxref("SharedStorage")}}._
See above comment.

2023-12-04 15:43 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +The **Shared Storage API** is a client-side storage mechanism that enables unpartitioned, cross-site data access in a privacy-preserving manner for specific use cases that require it.
I think a change was needed here, but the last sentence case of as a bit stating the obvious. I made an edit, and ended up with:

> The **Shared Storage API** is a client-side storage mechanism that enables unpartitioned, cross-site data access while preserving privacy (i.e. without relying on tracking cookies).

2023-12-04 15:49 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +The Shared Storage API provides a flexible solution to fulfill such use cases — aiming to provide the required data storage, processing, and sharing — but without sharing user data with parties that
I ended up with

> The Shared Storage API provides a flexible solution for such use cases. It aims to provide the required data storage, processing, and sharing capabilities without the ability to track and profile users.

2023-12-04 15:53 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +### Use cases
Yup, sounds like a good idea. I've done so.

2023-12-04 16:06 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +As mentioned above, to extract useful results from a shared storage worklet you need to use an **output gate**. In this example, we'll use the URL Selection output gate to read the user's experiment
Great! I've used this text, and linked the placeholder to the URL Selection output gate section.

2023-12-04 18:09 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +#### Add the worklet
Went with "#### Add the module to the shared storage worklet"

2023-12-04 18:13 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +Because the options object contains `resolveToConfig: true`, the returned {{jsxref("Promise")}} will resolve with a {{domxref("FencedFrameConfig")}} object, which can be set as the value of the {{dom
Ended up going with

> Because the options object contains `resolveToConfig: true`, the returned {{jsxref("Promise")}} will resolve with a {{domxref("FencedFrameConfig")}} object. This object can be set as the value of the {{domxref("HTMLFencedFrameElement.config")}} property, resulting in the chosen URL having its content displayed in the corresponding {{htmlelement("fencedframe")}} element:

2023-12-04 18:14 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageoperation/index.md
> +The different output gate types are detailed below:
OK, done in my next commit

2023-12-04 18:17 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageselecturloperation/index.md
> +The **`SharedStorageSelectURLOperation`** interface of the {{domxref("Shared Storage API", "Shared Storage API", "", "nocode")}} represents a URL Selection output gate operation.
Added!

2023-12-04 18:20 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageselecturloperation/index.md
> +> **Note:** It is possible to define and register multiple operations in the same shared storage worklet module script with different names; see {{domxref("SharedStorageOperation")}} for an example.
I think I did them all.

2023-12-04 18:24 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageworklet/index.md
> +`SharedStorageWorklet` has no properties or methods directly defined on it; it inherits the {{domxref("Worklet.addModule", "addModule()")}} method from the {{domxref("Worklet")}} interface, which is
Suggestion added, and I fixed the incompete sentence; it was sort of duplicating the purpose of the line below, so I melded them together.

2023-12-04 18:26 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorageworklet/index.md
> +- `SharedStorageWorklet` can only have a single module added to it, for privacy reasons. Even with a successful enrollment, repeated calls to `addModule()` on the same shared storage worklet will rej
Updated, with some tweaks

2023-12-04 18:28 UTC, chrisdavidmills commented on files/en-us/web/api/windowsharedstorage/index.md
> +  - : Executes a URL Selection operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
Suggestions implemented, links added.

2023-12-04 18:31 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorage/append/index.md
> +  - : A string that you want to append to the existing value.
Each pair has only one value, as such; I went with:

> A string that you want to append to the existing value of the key-value pair.

2023-12-04 18:35 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorage/append/index.md
> +  .then(console.log("Value appended to integer list"));
It works as-is. You can run something arbitrarily inside a then block without passing it in a function

2023-12-05 09:31 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorage/set/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
See above comment

2023-12-05 09:31 UTC, chrisdavidmills commented on files/en-us/web/api/sharedstorage/delete/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
See earlier comment

2023-12-05 09:55 UTC, chrisdavidmills commented
> * All occurrences of this link need to be updated (storage --> Storage)
>   `[Shared Storage API](/en-US/docs/Web/API/Shared_storage_API)`
> 
> * Also, if you're updating `key/value` pairs, you might want to check all occurrences (key/value pairs --> key-value pairs)

@dipikabh I've done both of these. For the second one, I've made sure the key/value --> key-value change has been made everywhere, but just in the shared storage api docs. Looking at the rest of MDN, it looks like key/value is still used everywhere. Are the changes made in this PR part of a larger effort to standardize on key-value everywhere?

2023-12-05 10:28 UTC, chrisdavidmills commented on files/en-us/web/api/workletsharedstorage/get/index.md
> +// documentation on Chrome blog
Good call. Done.

2023-12-05 10:30 UTC, chrisdavidmills commented on files/en-us/web/api/web_storage_api/index.md
> +Third-party code can be added to another site by injecting it with a {{htmlelement("script")}} element, or navigating an {{htmlelement("iframe")}} to a site that contains it. If you are a third-party
Used your wording, but fixed the typo and duplication.

2023-12-05 10:54 UTC, chrisdavidmills commented on files/en-us/web/api/windowsharedstorage/selecturl/index.md
> +{{domxref("WindowSharedStorage")}} interface executes a URL Selection operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
equivalent updates made

2023-12-05 11:07 UTC, chrisdavidmills commented on files/en-us/web/api/windowsharedstorage/selecturl/index.md
> +      - : A boolean value. If set to `true`, the fulfillment value of the {{jsxref("Promise")}} returned by `run()` will be a {{domxref("FencedFrameConfig")}} object that can be used to load content
I've made the same changes from previous suggestions in other files. They all fit pretty well.

2023-12-05 11:09 UTC, chrisdavidmills commented on files/en-us/web/api/workletsharedstorage/remainingbudget/index.md
> +The navigation budget is the number of bits of entropy permitted inside a {{htmlelement("fencedframe")}} as a result of {{domxref("WindowSharedStorage.selectURL()")}} calls, per origin, per 24-hour t
Correct; all the fanced frame related pages are being added as part of https://github.com/mdn/content/pull/27781, which I'm intending to create the second draft of straight after I've finished this one.

2023-12-05 11:26 UTC, chrisdavidmills commented on files/en-us/web/api/workletsharedstorage/remainingbudget/index.md
> +The navigation budget is the number of bits of entropy permitted inside a {{htmlelement("fencedframe")}} as a result of {{domxref("WindowSharedStorage.selectURL()")}} calls, per origin, per 24-hour t
For the change, I mostly used your suggestion, but tweaked it a bit:

> The navigation budget is the number of entropy bits permitted inside a {{htmlelement("fencedframe")}} due to the {{domxref("WindowSharedStorage.selectURL()")}} calls per origin every 24 hours. This is not the same as the number of navigations; rather, it is based on the number of potential navigations in each call. Each time a `selectURL()` navigation occurs, the corresponding origin's budget decreases by the logarithm (base 2) of the number of URL choices.

2023-12-05 14:55 UTC, dipikabh commented
> I've done both of these. 
Thank you!

> it looks like key/value is still used everywhere. Are the changes made in this PR part of a larger effort to standardize on key-value everywhere?
That's an interesting question. I came across key/value in this PR. My preference leans towards key-value and a quick search indicated that the hyphenated form has been used elsewhere, so I was okay to make the suggestion. It appears that both 'key-value' (88) and 'key/value' (96) are in use across our docs. To the best of my knowledge, there is no ongoing effort to standardize this usage.

I'll take a quick look again at the PR shortly and we should be able to get this one through today

2023-12-05 17:02 UTC, chrisdavidmills commented
> That's an interesting question. I came across key/value in this PR. My preference leans towards key-value and a quick search indicated that the hyphenated form has been used elsewhere, so I was okay to make the suggestion. It appears that both 'key-value' (88) and 'key/value' (96) are in use across our docs. To the best of my knowledge, there is no ongoing effort to standardize this usage.

Ah, so it is used in other places on the site too! OK, all good then. We should maybe agree on a standard for this one day, but it doesn't have to be today.

> I'll take a quick look again at the PR shortly and we should be able to get this one through today

Lovely, cheers!

2023-12-05 17:18 UTC, dipikabh commented on files/en-us/web/api/shared_storage_api/index.md
> +The URL will be chosen based on the experiment group stored in shared storage. To retrieve this value and choose a URL based on it, we need to define an operation in a {{domxref("SharedStorageWorklet
This is better, thanks! My bad for introducing an extra space there, thanks for catching it

2023-12-05 17:45 UTC, dipikabh commented on files/en-us/web/api/shared_storage_api/index.md
> +Because the options object contains `resolveToConfig: true`, the returned {{jsxref("Promise")}} will resolve with a {{domxref("FencedFrameConfig")}} object, which can be set as the value of the {{dom
Not a blocker, but perhaps it can be simplified like so:

> This object can be set as the value of the {{domxref("HTMLFencedFrameElement.config")}} property, resulting in the content of the chosen URL being displayed in the corresponding {{htmlelement("fencedframe")}} element:

2023-12-05 17:50 UTC, dipikabh commented on files/en-us/web/api/windowsharedstorage/index.md
> +_`WindowSharedStorage` inherits properties from its parent interface, {{domxref("SharedStorage")}}._
Ah, got it! Yeah, let's keep this as is then

2023-12-05 17:51 UTC, dipikabh commented on files/en-us/web/api/windowsharedstorage/index.md
> +  - : Executes a URL Selection operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
Thanks!

2023-12-05 17:53 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/append/index.md
> +  - : A string that you want to append to the existing value.
Looks good

2023-12-05 17:53 UTC, dipikabh commented on files/en-us/web/api/sharedstorage/clear/index.md
> +  - The calling site does not have the Shared Storage API included in a successful [privacy sandbox enrollment process](/en-US/docs/Web/Privacy/Privacy_sandbox/Enrollment).
Thanks!

2023-12-05 17:55 UTC, dipikabh commented on files/en-us/web/api/sharedstorageselecturloperation/run/index.md
> +      - : An object containing properties with names equal to event types, and values equal to URLs where reporting destinations are located, for example, `"click" : "my-reports/report1.html"`. These
Seems fine

2023-12-05 17:56 UTC, dipikabh commented on files/en-us/web/api/web_storage_api/index.md
> +Third-party code can be added to another site by injecting it with a {{htmlelement("script")}} element, or navigating an {{htmlelement("iframe")}} to a site that contains it. If you are a third-party
Oops, sorry for introducing typos

2023-12-05 18:03 UTC, dipikabh commented on files/en-us/web/api/windowsharedstorage/run/index.md
> +{{domxref("WindowSharedStorage")}} interface executes a run operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
How about this tweak by adding "that is" to aid in readability:

> The run() method
> of the {{domxref("WindowSharedStorage")}} interface executes a [run operation](https://github.com/en-US/docs/Web/API/SharedStorageRunOperation) that is registered in a module added to the current origin's {{domxref("SharedStorageWorklet")}}.

2023-12-05 18:05 UTC, dipikabh commented on files/en-us/web/api/sharedstorageoperation/index.md
> +The different output gate types are detailed below:
Thanks for the context on the `{{InheritanceDiagram}}` macro

2023-12-05 18:06 UTC, dipikabh commented on files/en-us/web/api/windowsharedstorage/selecturl/index.md
> +{{domxref("WindowSharedStorage")}} interface executes a URL Selection operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
Thanks!

2023-12-05 18:06 UTC, dipikabh commented on files/en-us/web/api/windowsharedstorage/selecturl/index.md
> +      - : A boolean value. If set to `true`, the fulfillment value of the {{jsxref("Promise")}} returned by `run()` will be a {{domxref("FencedFrameConfig")}} object that can be used to load content
Awesome, thank you!

2023-12-05 18:08 UTC, dipikabh commented on files/en-us/web/api/workletsharedstorage/remainingbudget/index.md
> +The navigation budget is the number of bits of entropy permitted inside a {{htmlelement("fencedframe")}} as a result of {{domxref("WindowSharedStorage.selectURL()")}} calls, per origin, per 24-hour t
This is better, thanks!

2023-12-05 18:15 UTC, dipikabh approved these changes
Hi @chrisdavidmills, thanks for the updates and addressing all the suggestions.

I like that you quote your edited text if it is different from the suggestion. It helps me quickly go through any outstanding changes I should look at. I've started following this style in my PRs as well 🙂.

I'm leaving a +1 here, but I'll it for you to merge in case you want to update the text for these two comments:
https://github.com/mdn/content/pull/30427#discussion_r1416063182
https://github.com/mdn/content/pull/30427#discussion_r1416086348

2023-12-06 09:53 UTC, chrisdavidmills commented on files/en-us/web/api/shared_storage_api/index.md
> +Because the options object contains `resolveToConfig: true`, the returned {{jsxref("Promise")}} will resolve with a {{domxref("FencedFrameConfig")}} object, which can be set as the value of the {{dom
Looks good; added. Thanks!

2023-12-06 09:55 UTC, chrisdavidmills commented on files/en-us/web/api/windowsharedstorage/run/index.md
> +{{domxref("WindowSharedStorage")}} interface executes a run operation registered in a module added to the {{domxref("SharedStorageWorklet")}} associated with the current origin.
Yup, sounds good; updated. I also made the same addition on the `selectURL()` page.

2023-12-06 10:19 UTC, chrisdavidmills commented
> I like that you quote your edited text if it is different from the suggestion. It helps me quickly go through any outstanding changes I should look at. I've started following this style in my PRs as well 🙂.

@dipikabh I've only recently started doing that as well; pretty useful huh.

I've addressed the further couple of minor changes you suggested, and now I think we're ready to merge. Thanks so much for the detailed review!

2023-12-06 10:19 UTC, merged