29787 text wrap
mdn/content pull request #30435
Opened 2023-11-21 16:21 UTC by dletorey

### Description

- Added the different values for `text-wrap`
- Added `text-wrap` to experimental features
- Added `text-wrap` 121 release note

### Motivation

Working on the following Issues:
- [Implement text-wrap:balance](https://github.com/mdn/content/issues/29787)
- [Enable CSS text-wrap: balance for all channels](https://github.com/mdn/content/issues/30338)

### Additional details

- [Implement CSS `text-wrap: balance`](https://bugzilla.mozilla.org/show_bug.cgi?id=1731541)
- [Enable CSS `text-wrap: balance` for all channels](https://bugzilla.mozilla.org/show_bug.cgi?id=1860446)

### Related issues and pull requests

- [BCD PR](https://github.com/mdn/browser-compat-data/pull/21311)

2023-11-21 17:43 UTC, pepelsbey commented on files/en-us/web/css/text-wrap/index.md
> +As `balance` is limited to a short number of lines then this should generally be used for headings, captions, and blockquotes.
It might be worth mentioning what “short” means. 6 in Chrome, 10 in Firefox, or something like that?

2023-11-21 17:53 UTC, zfox23 requested changes

2023-11-21 17:53 UTC, zfox23 commented on files/en-us/web/css/text-wrap/index.md
> +  - : Results in the same behavior as `wrap`, except that the algorithm does not consider subsequent lines when making break decisions. When editing text that has already been painted to the screen,
```suggestion
  - : Results in the same behavior as `wrap`, except that the algorithm does not consider subsequent lines when making break decisions. When editing text that has already been painted to the screen, subsequent lines should not be considered when making break decisions, so that, when editing text, any content before the cursor remains stable.
```

2023-11-21 17:53 UTC, zfox23 commented on files/en-us/web/css/text-wrap/index.md
> +The `pretty` value can have a negative effect on performance and should be used, for body copy (longer blocks of content), when layout is favourable over paint performance.
- comma change
- subjective parenthetical removal change
- a switch to [American-English](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#spelling)

```suggestion
The `pretty` value can have a negative effect on performance and should be only used for longer blocks of text when layout is favorable over paint performance.
```

2023-11-21 17:53 UTC, zfox23 commented on files/en-us/web/css/text-wrap/index.md
> +The `stable` value should be used on content that has a [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute. This ensures that the preceeding lines will remain stabl
```suggestion
The `stable` value should be used on content that has a [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute. This ensures that the preceding lines will remain stable while a user is editing the content.
```

2023-11-21 17:53 UTC, zfox23 commented on files/en-us/mozilla/firefox/releases/121/index.md
> +- The {{CSSXRef("text-wrap")}} property has now been added with support for the values `balance` and `stable`. The `balance` value is used for short blocks of content, such as headings, and will make
- subjective clause position improvement
- "added" -> "updated" (since `text-wrap` as a property has already been present)
- "will" -> "while"
- added "it" token

```suggestion
- The {{CSSXRef("text-wrap")}} property has been updated with support for the values `balance` and `stable`. The `balance` value is used for short blocks of content, such as headings, and will make sure that the content is balanced and easy to read when spread over multiple lines. The `stable` value makes sure that editable content does not reflow while the user is editing it ([Firefox bug 1731541](https://bugzil.la/1731541)).
```

2023-11-21 17:53 UTC, zfox23 commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +The [`text-wrap`](/en-US/docs/Web/CSS/text-wrap) CSS property values `balance` and `stable` allow the layout of content to be wrapped for short content in a balanced manner and for editable content w
Subjective improvements...still feels a bit awkward to me...might be worth breaking the short descriptions of these property values into two sentences. wdyt?

```suggestion
The [`text-wrap`](/en-US/docs/Web/CSS/text-wrap) CSS property values `balance` and `stable` allow the layout of short content to be wrapped in a balanced manner and for editable content to not reflow while the user is editing it, respectively.
```

2023-11-21 22:54 UTC, estelle submitted a review, later dismissed

2023-11-21 22:54 UTC, estelle commented on files/en-us/web/css/text-wrap/index.md
> +The `pretty` value can have a negative effect on performance and should be used, for body copy (longer blocks of content), when layout is favourable over paint performance.
This sentence may be difficult for someone not familiar with web performance to parse, especially a non-native English speaker. maybe "when the layout of the text is more important than [paint performance](link_to_article)"

2023-11-22 00:11 UTC, estelle commented on files/en-us/web/css/text-wrap/index.md
> +The `stable` value should be used on content that has a [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute. This ensures that the preceeding lines will remain stabl
contenteditable is enumerated, so
```suggestion
The `stable` value should be used on content that is [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute. This ensures that the previous lines remain stable while a user edits the content.
```
I am being pedantic, but `contenteditable` is both enumerated and inherited, meaning if present, it doesn't mean it's editable, and if omitted, it doesn't mean it isn't editable.

2023-11-22 09:51 UTC, dletorey commented on files/en-us/web/css/text-wrap/index.md
> +As `balance` is limited to a short number of lines then this should generally be used for headings, captions, and blockquotes.
This is mentioned in description of `balance` value. Should it be repeated?

2023-11-22 11:07 UTC, dletorey commented on files/en-us/web/css/text-wrap/index.md
> +The `pretty` value can have a negative effect on performance and should be used, for body copy (longer blocks of content), when layout is favourable over paint performance.
Updated this to **speed** rather than **paint performance** as mentioned in the spec.

2023-11-22 12:00 UTC, pepelsbey approved these changes

2023-11-22 13:20 UTC, zfox23 approved these changes

2023-11-22 20:32 UTC, estelle commented on files/en-us/web/css/text-wrap/index.md
> +  - : Results in the same behavior as `wrap`, except that the algorithm does not consider subsequent lines when making break decisions. When editing text that has already been painted to the screen,
This sounds like spec speak for what the browser is doing:
> When editing text that has already been painted to the screen, subsequent lines should not be considered when making break decisions
Is that browser behavior? If yes, combine the first two sentences; they're kind of saying the same thing. If this is about the developer, that needs to be a bit clearer. 
The last part, " so that, when editing text, any content before the cursor remains stable." suggest adding "the user"
>  so that, when the user is editing text, content before the cursor remains stable."

2023-11-22 20:35 UTC, estelle commented on files/en-us/web/css/text-wrap/index.md
> +The `stable` value should be used on content that is [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable) attribute. This ensures that the previous lines remain stable when use
```suggestion
The `stable` value should be used on content that is [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable). This ensures that the previous lines remain stable when users edit the content.
```

2023-11-28 16:30 UTC, dletorey commented on files/en-us/web/css/text-wrap/index.md
> +  - : Results in the same behavior as `wrap`, except that the algorithm does not consider subsequent lines when making break decisions. When editing text that has already been painted to the screen,
reworded this whole thing

2023-11-29 18:34 UTC, estelle reviewed
We need to add the spec https://drafts.csswg.org/css-text-4/#white-space-property to the `white-space` page, as this property is part of that now shorthand value. We shouldn't remove css-text-3, though, until the shorthand syntax / values are supported.

I think the newer version you wrote was much easier for non-native speakers, but I still wasn't 100% in love with the section under description. I suggested an alternative for that entire section.

2023-11-29 18:34 UTC, estelle commented on files/en-us/web/css/text-wrap/index.md
> +## Description
Maybe rewrite this entire section. Here is a take:

```suggestion
## Description

Inline-level content is laid out into lines, with line breaks breaking text across line boxes. There are two types of line breaks. A _forced line break_ occurs when a line is broken due to a newline character, the start or end of a block, or other explicit line-breaking controls such as when `{{cssxref("white-space")}}: pre` is set. A _soft line break_ is an unforced line break, such as when content naturally wraps to fit the content within its parent.

When wrapping is enabled, the `text-wrap` property defines how soft-wrap-opportunities within a line are prioritized. The value you choose depends on how many lines of text you anticipate styling, whether the text is `contenteditable`, and whether you need to prioritize appearance or performance.

When the styled content will be limited to a short number of lines, such as headings, captions, and blockquotes, `text-wrap: balance` can be added to balance the number of characters on each line, enhancing layout quality and legibility. As browsers limit the number of lines impacted by this property, this value's impact on performance is negligible.

For longer sections of text, `text-wrap: pretty` can be used. Note that `pretty` has a negative effect on performance, so it should be only used for longer blocks of text when the layout is more important than speed.

The `stable` value improves user experience when used on content that is [`contenteditable`](/en-US/docs/Web/HTML/Global_attributes/contenteditable). This value ensures that, as the user is editing text, the previous lines in the area being edited remain stable.
```

2023-12-11 12:27 UTC, dletorey commented on files/en-us/web/css/text-wrap/index.md
> +## Description
I have re-written this

2023-12-18 15:44 UTC, pepelsbey approved these changes
Thank you! Merging it for tomorrow’s release. We can address any questions that might still left in the next PRs.

2023-12-18 15:49 UTC, merged

2023-12-18 20:31 UTC, estelle commented
@pepelsbey Do not dismiss reviews, especially without any attempts to reach out to request a re-review.

2023-12-18 20:45 UTC, pepelsbey commented
@estelle I'm sorry but we needed this PR merged before tomorrow's Firefox 121 release. I asked @dletorey if your feedback was fully implemented and made the call. I hope you can still follow up on any potential issues left in a separate issue or PR. Thank you!

2023-12-18 20:48 UTC, Josh-Cena commented
@dletorey @pepelsbey @zfox23 and other Mozilla folks: to make sure this doesn't happen again, please split your content PR and FF release note PR. The non-moz folks would likely not block your release notes so you can chill a bit about content. I know Hamish always does this.

2023-12-18 20:57 UTC, pepelsbey commented
> please split your content PR and FF release note PR

Yes, I fully agree. But it won't solve the problem, unfortunately: when some features get released in Firefox, we update not only release notes but also content. We were hoping a few weeks would be enough to get this review done. It wasn't, so I had to merge it.

I think we might also consider an approach where we can merge less than ideal pages first and then start improving them later. Otherwise, it stops developers from getting this information from MDN. The new `text-wrap` values were implemented in other browsers a while ago.

2023-12-18 21:29 UTC, Josh-Cena commented
Any content that appears should be well-reviewed and agreed by parties involved. Reviewers not involving implicitly approve, but reviewers who explicitly disprove need to be given the chance for another round of review. This is one of the core reasons why we moved away from wiki: so we never have subpar pages getting into production :)

However, I agree we are missing an explicit timebox here. We need contributing guidelines for how long to wait for reviews.