Fixes #29367 | update `ServiceWorkerRegistration.scope` and `ServiceWorkerRegistration.updateViaCache` to reflect its relationship with `ServiceWorkerContainer.register()`
mdn/content pull request #30447
Opened 2023-11-22 07:55 UTC by skyclouds2001

### Description

see the issue for detail

### Motivation

### Additional details

### Related issues and pull requests

Fixes #29367

2023-12-07 04:00 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
> +The **`updateViaCache`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns the update via cache mode associated with the current service worker registration using t
```suggestion
The **`updateViaCache`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns the update via cache mode associated with the current service worker registration using the `updateViaCache` parameter specified when register the service worker by calling {{domxref('ServiceWorkerContainer.register()')}}. Requests for `importScripts` still go via the HTTP cache. `updateViaCache` offers control over this behavior.
```

2024-03-29 06:17 UTC, wbamberg requested changes
Thank you @skyclouds2001  and sorry to be so slow to review this. I had some suggestions, mostly around trying to explain things more clearly, but please let me know if you think I have mangled things.

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/index.md
> +  - : Returns a string indicating the service worker's registration scope associated with the current service worker registration.
```suggestion
  - :  A string representing a URL that defines a service worker's registration scope; that is, the range of URLs the service worker can control.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/scope/index.md
> +The **`scope`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns the service worker's registration scope associated with the current service worker registration us
```suggestion
The **`scope`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface is a string representing a URL that defines a service worker's registration scope; that is, the range of URLs a service worker can control. This is set using the `scope` parameter specified in the call to {{domxref('ServiceWorkerContainer.register()')}} which registered the service worker.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/scope/index.md
> +Returns the service worker's registration scope associated with the current service worker registration.
```suggestion
A string representing a URL that defines a service worker's registration scope.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
> +The **`updateViaCache`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns the update via cache mode associated with the current service worker registration using t
```suggestion
The **`updateViaCache`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns the value of the setting used to determine the circumstances in which the browser will consult the HTTP cache when it tries to update the service worker or any scripts that are imported via {{domxref("WorkerGlobalScope.importScripts", "importScripts()")}}.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
>  - `imports`, meaning the HTTP cache is not consulted for update of the service worker, but is consulted for `importScripts`.
```suggestion
- `imports`, meaning the HTTP cache is not consulted for updates to the service worker script, but is consulted for scripts imported using {{domxref("WorkerGlobalScope.importScripts", "importScripts()")}}. This is the default value.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
> +Returns the update via cache mode associated with the current service worker registration, can be one of the following values:
Returns one of the following values:

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
>  - `all`, meaning the HTTP cache is consulted in both cases
```suggestion
- `all`, meaning the HTTP cache is consulted for updates to the service worker script and for scripts imported using {{domxref("WorkerGlobalScope.importScripts", "importScripts()")}}.
```

2024-03-29 06:17 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/index.md
> +  - : Returns a service worker whose state is `installed`. This is initially set to `null`
```suggestion
  - : Returns a service worker whose state is `installed`. This is initially set to `null`.
```

2024-04-11 10:11 UTC, bsmth commented
@skyclouds2001 a couple of comments and suggestions from Will above if you have some time to take a look 👀 


Thank you :)

2024-04-11 10:19 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/index.md
> +  - :  A string representing a URL that defines a service worker's registration scope; that is, the range of URLs the service worker can control.
```suggestion
  - : Returns a string representing a URL that defines a service worker's registration scope; that is, the range of URLs the service worker can control.
```

2024-04-11 10:19 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/index.md
> +  - : Returns the value of the setting used to determine the circumstances in which the browser will consult the HTTP cache when it tries to update the service worker or any scripts that are imported
```suggestion
  - : Returns the value of the setting used to determine the circumstances in which the browser will consult the HTTP cache when it tries to update the service worker or any scripts that are imported via {{domxref("WorkerGlobalScope.importScripts", "importScripts()")}}. It can be one of the following: `imports`, `all`, or `none`.
```

2024-04-11 10:22 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/updateviacache/index.md
> +Returns the update via cache mode associated with the current service worker registration, can be one of the following values:
```suggestion
Returns one of the following values:
```

2024-04-11 10:23 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/scope/index.md
> +The **`scope`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface is a string representing a URL that defines a service worker's registration scope; that is, the range of U
```suggestion
The **`scope`** read-only property of the {{domxref("ServiceWorkerRegistration")}} interface returns a string representing a URL that defines a service worker's registration scope; that is, the range of URLs a service worker can control. This is set using the `scope` parameter specified in the call to {{domxref('ServiceWorkerContainer.register()')}} which registered the service worker.
```

2024-04-11 10:23 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/scope/index.md
> +A string representing a URL that defines a service worker's registration scope.
```suggestion
Returns a string representing a URL that defines a service worker's registration scope.
```

2024-04-15 16:45 UTC, wbamberg approved these changes
👍 thank you @skyclouds2001 !

2024-04-15 16:45 UTC, merged