Learn React update 2: The updatening
mdn/content pull request #30453
Opened 2023-11-22 15:57 UTC by mxmason

## Description

Continuing from #30177, this PR rewrites some content in the second page of the "Learn React" tutorial.

2023-11-22 16:02 UTC, mxmason reviewed
Hello, @chrisdavidmills. This is ready for you!

2023-11-22 16:02 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +export default App;
🔍 This line was added to the copied code because the terminal commands in the previous section had the user erase the file completely

2023-11-22 16:02 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +### A note on boolean attributes in JSX
🔍 I thought it would be best to turn this info into a proper section

2023-11-22 16:02 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +*:focus-visible {
🔍 Be not alarmed at how much this CSS code block has changed. With the exception of switching from `:focus` to `:focus-visible`, all the content is the same; I've just alphabetized all the rules within each block.

2023-11-23 09:42 UTC, pepelsbey reviewed
I noticed that in the “Implementing our styles” sections only 4 lines were intentionally changed (replacing `:focus` with `:focus-within`), but the number of changes in the diff is much higher because the CSS properties got sorted by some formatter. It’s a bit harder to review now.

2023-11-23 10:09 UTC, chrisdavidmills requested changes
@mxmason. OK, I've gone through this one, and it's mostly looking fine. Very little to report ;-)

2023-11-23 10:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +*:focus-visible {
Seems reasonable.

The only thing I noticed (and this is super picky) is that the code comments are inconsistent. `/* Todo item styles */` is not capitalized whereas the other comments are, and some comment blocks have end comments and some don't. I'd make the capitalization consistent at least ;-)

2023-11-23 10:13 UTC, chrisdavidmills commented
> I noticed that in the “Implementing our styles” sections only 4 lines were intentionally changed (replacing `:focus` with `:focus-within`), but the number of changes in the diff is much higher because the CSS properties got sorted by some formatter. It’s a bit harder to review now.

@pepelsbey I think it's fine in this case. The code was reviewed thoroughly during the previous app iteration, and the small changes look OK to me (see https://github.com/mdn/content/pull/30453#discussion_r1402326812 for the explanation of the reordering)

2023-11-23 21:40 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +```jsx
Oops, dunno what I was thinking. Will fix.

2023-11-23 22:17 UTC, mxmason reviewed
Back to you, @chrisdavidmills!

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +: >! {App.jsx,index.css}
Added a note above, as you suggested!

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +            <input id="todo-0" type="checkbox" defaultChecked />
🔍 Small adjustment: the explicit `={true}` is not in the later discussion of boolean attributes, so I've removed it here

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +The class `visually-hidden` has no effect yet, because we have not included any CSS. Once we have put our styles in place, though, any element with this class will be hidden from sighted users and st
🔍 Being super nit picky of myself, i've replaced "screen reader" with "assistive technology" when something applies to AT broadly

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +> **Note:** The `aria-pressed` attribute used in our earlier code snippet has a value of `"true"` because `aria-pressed` is not a true boolean attribute in the way `checked` is.
🔍 I've rewritten this a little bit. The "Because JSX is JavaScript..." sentence offers an explanation for the behavior you pointed out with `hidden`, and I reiterate it at the end of the section.

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +/* Resets */
🔍 I've normalized the comment casing and made sure each named section has a beginning and end fence

2023-11-23 22:17 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
>  > **Note:** If you need to check your code against our version, you can find a finished version of the sample React app code in our [todo-react repository](https://github.com/mdn/todo-react). For a r
❓  Would you like me to migrate the example implementation of the app to match these instructions as well?

2023-11-24 14:15 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +: >! {App.jsx,index.css}
Looking good, thanks!

2023-11-24 14:24 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +The class `visually-hidden` has no effect yet, because we have not included any CSS. Once we have put our styles in place, though, any element with this class will be hidden from sighted users and st
Good call.

2023-11-24 14:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +> **Note:** The `aria-pressed` attribute used in our earlier code snippet has a value of `"true"` because `aria-pressed` is not a true boolean attribute in the way `checked` is.
This is great work. I always forget the truthy strings detail, so it is good to have a remidner here.

2023-11-24 14:25 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
>  > **Note:** If you need to check your code against our version, you can find a finished version of the sample React app code in our [todo-react repository](https://github.com/mdn/todo-react). For a r
Yes please, that would be super helpful.

2023-11-24 14:32 UTC, chrisdavidmills requested changes
@mxmason VERY nearly there! Lovely work, this is looking great.

2023-11-24 14:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +Because JSX is JavaScript, there's a gotcha to be aware of with boolean attributes: writing `defaultChecked="true"` will set a _string_ value of `"true"` rather than a _boolean_ value. Strings are [t
```suggestion
Because JSX is JavaScript, there's a gotcha to be aware of with boolean attributes: writing `defaultChecked="true"` will set a _string_ value of `"true"` rather than a _boolean_ value. Non-empty strings are [truthy](/en-US/docs/Glossary/Truthy), so React will consider `defaultChecked` to be `true` and check the checkbox by default. This is not what we want, so we should avoid it.
```

2023-11-24 14:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +If you'd like, you can practice writing boolean attributes with another attribute you may have seen before: [`hidden`](/en-US/docs/Web/HTML/Global_attributes/hidden), which prevents elements from bei
```suggestion
If you'd like, you can practice writing boolean attributes with another attribute you may have seen before, [`hidden`](/en-US/docs/Web/HTML/Global_attributes/hidden), which prevents elements from being rendered on the page. Try adding `hidden` to the `<h1>` element in `App.jsx` to see what happens, then try explicitly setting its value to `{false}`. Note, again, that writing `hidden="false"` results in a truthy value so the `<h1>` _will not_ hide. Don't forget to remove this code when you're done.
```

2023-11-24 14:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +/* Resets */
Great! I noticed that `/* Todo item styles */` doesn't have a corresponding end fence (and now I feel really horrible and nitpicky)

2023-11-24 15:47 UTC, mxmason reviewed
Annnd back to you!

2023-11-24 15:47 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +/* Resets */
Oh nooo i swear I added that fence, must have gotten lost before i committed. Fixed now.

2023-11-24 15:47 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +Because JSX is JavaScript, there's a gotcha to be aware of with boolean attributes: writing `defaultChecked="false"` will set a _string_ value of `"false"` rather than a _boolean_ value. Non-empty st
🔍 I thought it made more sense to frame this warning with the string `"false"` instead of string `"true`

2023-11-24 15:54 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +Paste the following CSS code into `src/index.css`:
Oops, one more: I removed "what's currently there" because the file is empty ;)

2023-11-24 18:40 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +Because JSX is JavaScript, there's a gotcha to be aware of with boolean attributes: writing `defaultChecked="false"` will set a _string_ value of `"false"` rather than a _boolean_ value. Non-empty st
Yup, makes sense

2023-11-24 18:41 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/index.md
> +Paste the following CSS code into `src/index.css`:
Ha, good catch!

2023-11-24 18:42 UTC, chrisdavidmills approved these changes
@mxmason Ding ding, another level passed! Great work.

On to the next one ;-)

2023-11-28 08:06 UTC, chrisdavidmills commented
> heya @chrisdavidmills! In case you missed it in your notifications, just wanted to let you know that I've continued this work in some other PRs:
> 
>     * [DO NOT MERGE: MDN React Tutorials #3: Componentizing #30514](https://github.com/mdn/content/pull/30514), and
> 
>     * [MDN intro to client-side frameworks update: intro & framework main features #30515](https://github.com/mdn/content/pull/30515)

@mxmason Yup, I saw them, don't worry! I have just been busy on other things since I saw them. I'll make sure time to look at these today, so you are not blocked.

2023-12-21 11:11 UTC, merged