MDN client-side frameworks #1: Intro
mdn/content pull request #30515
Opened 2023-11-24 21:57 UTC by mxmason

## Description

As part of https://github.com/mdn/mdn/issues/474, this PR introduces some minor edits to the "Introduction to client-side frameworks" lesson

2023-11-24 22:05 UTC, mxmason reviewed
All yours, @chrisdavidmills! Wasn't sure if this one should be a do not merge, since its changes can stand alone (I think)

2023-11-24 22:05 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +- [`Node.textContent`](/en-US/docs/Web/API/Node/textContent)
🔍 I've capitalized all references to the `Node` interface because interfaces are proper nouns

2023-11-24 22:05 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +Static site generators have been around for quite a long time, and they've recently seen a wave of renewed interest and innovation. A handful of powerful options are now available, such as [Astro](ht
🔍 I've added Astro, a new-ish, popular, developer-experience-friendly framework that offers a combination of static generation and server-side render behaviors. The list is also now alphabetized.

2023-11-24 22:05 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +If you'd like to learn more about static site generators on the whole, check out Tatiana Mac's [Beginner's guide to Eleventy](https://www.tatianamac.com/posts/beginner-eleventy-tutorial-parti/). In t
🔍 Last I was aware, Tatiana uses both "they" and "she" pronouns with a preference for the former, so I've updated this line out of respect.

Unfortunately, it looks like Tatiana never completed this tutorial. Would you like to keep it? If MDN is ever interested in a course on static site generators, I'd be happy to write one ;).

2023-11-24 22:30 UTC, mxmason reviewed
One more! I decided that the changes to these files were small enough that they can go together, maybe

2023-11-24 22:30 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +```jsx
🔍 Our code blocks have better syntax highlights now!

2023-11-24 22:30 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +import { fireEvent, render, screen } from "@testing-library/react";
🔍 This test file is functionally the same. It now includes the `screen` function, which is the preferred way to query the DOM in testing-library.

2023-11-28 15:32 UTC, chrisdavidmills requested changes
@mxmason hey, nice work here! I have looked through it all, and mostly offered feedback by way of responses to your existing comments. I also noticed the following small bits:

First article:

- The functional version of your raw JS example at https://codepen.io/mxmason/pen/XWbPNmw needs updating to match the code changes you made in the doc.

Second article:

- Another line number reference - "The curly braces around `subject` on line 4". Maybe change to "The curly braces around `{subject}`" ?
- Another one - "We call this function on line 4, and set `count` to whatever its current value is, plus one". Maybe change it to "We call this function inside the `onClick` event handler, setting `count` to whatever its current value is, plus one" ?

2023-11-28 15:32 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +import { fireEvent, render, screen } from "@testing-library/react";
Sounds good!

2023-11-28 17:47 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +- [`Node.textContent`](/en-US/docs/Web/API/Node/textContent)
*Technically*, `Node.removeChild()` is an interface method. `document.createElement` and other document methods here are instance methods. If you look at MDN's [own documentation for `Node.removeChild()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild), they do capitalize the Node interface when talking about it: "Unlike `Node.cloneNode()`..."

2023-11-28 18:35 UTC, mxmason reviewed
Back to you, @chrisdavidmills! I've also updated [my CodePen](https://codepen.io/mxmason/pen/XWbPNmw) to use the `textContent` property instead of `createTextNode()`

2023-11-28 18:35 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +- [`Node.textContent`](/en-US/docs/Web/API/Node/textContent)
*Technically*, `Node.removeChild()` is an interface method. `document.createElement` and other document methods here are instance methods. If you look at MDN's [own documentation for `Node.removeChild()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild), they do capitalize the Node interface when talking about it: "Unlike `Node.cloneNode()`..."

2023-11-28 18:35 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.md
> +This expression represents an HTML [`<header>`](/en-US/docs/Web/HTML/Element/header) element with an [`<h1>`](/en-US/docs/Web/HTML/Element/Heading_Elements) element inside. The curly braces around `{
🧹 no more reference to a line number

2023-11-29 11:39 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +  span.textContent = name;
All looking good.

2023-11-29 11:52 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +- [`Node.textContent`](/en-US/docs/Web/API/Node/textContent)
It is an interface method, but it isn't a static method. For example, if you were to type `Node.removeChild()` in the devtools, you don't get access to `removeChild()` - it isn't available directly on the `Node` object in the browser.

You can however get access to `removeChild()` via say `document.body.removeChild()`, as all element objects inherit from `Node` somewhere along the chain.

As far as I am aware, generally links to all such methods are presented on MDN with a prefix of the object they are defined on, capitalized, i.e. `Node.removeChild()`, `Document.createElement()`... this is just how the macro that generates those links works.

Thinking about this some more, I think your change has merit, but I think it'd be even better if you also capitalized `document` and `eventTarget`, for consistency. Can we take that approach instead?

2023-11-29 11:54 UTC, chrisdavidmills approved these changes
@mxmason ok, I think this looks fine, pending the nitpick about the object capitalization. Let me know what you think on that one. 

I think we'll get this merged in the next round regardless, as you are right — this isn't dependant on the rest of your work.

2023-11-30 05:19 UTC, mxmason commented
Heya, @chrisdavidmills. I'd like to merge this as-is if you're ok with the way things are capitalized now. 

I also know I have other reviews to get to, but I've not been well today. I'll get back to you tomorrow, i hope!

2023-11-30 10:20 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.md
> +- [`Node.textContent`](/en-US/docs/Web/API/Node/textContent)
OK, I've edited it to implement my plan. I also added in links to `forEach()` and `setAttribute()`, and removed the link to `addEventListener()`, as that is not actually used in the section.

2023-11-30 10:30 UTC, merged