DO NOT MERGE: MDN React Tutorials #3: Componentizing
mdn/content pull request #30514
Opened 2023-11-24 19:29 UTC by mxmason

## Description

Following #30453 as part of mdn/mdn#474, this PR makes some modifications to the third page in our "Getting started with React" tutorial.

2023-11-24 19:41 UTC, mxmason reviewed
A gift just for you, @chrisdavidmills! This file has undergone some light editing apart from just changing `.js` to `.jsx`. I've tried to call out things of note.

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> -> **Note:** Components must always return something. If at any point in the future you try to render a component that does not return anything, React will display an error in your browser.
🔍 As of React 18, React components can implicitly or explicitly return `undefined` without throwing errors.

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +Once you're confident that your component is getting its props, you can replace every occurrence of `Eat` with your `name` prop by reading `props.name`. Remember: `props.name` is a JSX expression, so
🔍 Subtle syntactical nit in here: while `props` is a piece of code, it is also a _concept_ we're referring to in plain language ("your `name` prop", etc.), so I have taken the code syntax off when it seems like we're referring to props-the-concept and not props-the-symbol-in-a-program

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
>  ```
🔍 I changed these hard-coded examples so that `completed` is true when present and omitted otherwise, just to revisit that syntax. Later, when the reader gets `completed` from the `task` object, they practice the explicit assignment syntax.

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +**Note:** The `completed` prop is last here because it is a boolean with no assignment. This is purely a stylistic convention. The order of props does not matter because props are JavaScript objects,
🔍 

1. This section is now more robust. In my original writing, I did not mention the accessibility pitfall that comes with id attribute collision. Now, I mention it and have the reader see it for themself.
2. I added a note about prop order here. This stylistic choice is common in the wild, and it was hurting my feelings to have `completed` as a no-assignment boolean in the middle of a list of props ;)

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +const taskList = props.tasks?.map((task) => (
🔍 We explicitly called out optional chaining, but did not use it in all our code snippets. Now we do.

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +touch src/components/{Form,FilterButton}.jsx
🔍 I shortened this with brace expansion because it makes me feel cool ;)

2023-11-24 19:41 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +function Form() {
🔍 I removed `props` from the components' function signatures because `props` is not being used yet. If left in, readers with ESLint configured in their code editors will see some 
meddlesome warnings.

2023-11-29 11:03 UTC, chrisdavidmills requested changes
More fabulous work, thank you @mxmason! Some comments for you to chew on.

2023-12-01 05:23 UTC, mxmason reviewed
Back to you, @chrisdavidmills! 

I addressed your notes (I think), plus a couple of other small changes – removing `props` from the signature of `FilterButton` and wrapping `<FilterButton />` in code code markup in its heading, among other changes.

2023-12-01 05:23 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +With this component imported, you can replace all of the `<li>` elements in `App.jsx` with `<Todo />` component calls. Your `<ul>` should read like this:
I addressed this with a slight rewrite to the section.

2023-12-01 05:23 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +const taskList = props.tasks?.map((task) => (
When creating these snippets, I generally follow the wrapping done by my text editor, so shorter JSX expressions tend not to wrap and longer JSX expressions do wrap. I'm fine with manually wrapping this one if you want to

2023-12-01 05:23 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +With these fixes in place, clicking on the labels next to each checkbox will do what we expect – check and uncheck the checkboxes next to those labels.
🔍 Here's the note about the behavior restored by our unique id attributes

2023-12-01 05:23 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +Next, we'll pass `DATA` to `<App />` as a prop, called `tasks`. The final lines of `src/main.jsx` should read like this:
🔍 I went with "lines" here to address the problem of "line". Groundbreaking, I know.

2023-12-11 03:26 UTC, hamishwillee commented
@chrisdavidmills I'm removing myself as a reviewer - I know nothing about React.

2023-12-11 10:45 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_components/index.md
> +const taskList = props.tasks?.map((task) => (
You can leave it actually; I don't think it is worth the time spent.

2023-12-11 11:14 UTC, chrisdavidmills approved these changes
Lovely work @mxmason! I made a couple of very small tweaks to push this over the finish line; I thought you'd appreciate that rather than passing it back to you for another round.

With that, I'm approving this, and you can move on to the next one.

2023-12-21 11:23 UTC, merged