CSS counter() function
mdn/content pull request #30583
Opened 2023-11-27 22:59 UTC by estelle

2023-12-05 21:00 UTC, dipikabh requested changes
Thanks for these updates, @estelle!

I've added my suggestions along with a few recommendations for breaking up long sentences.

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +The **`counters()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) enables nested counters, returning a concatenated string representing the current values of the named and
- The sentence is too long and in the later half is somewhat not clear. Does the suggested text convey the intended meaning?
- Even in this suggestion, ", and can optionally be displayed in a specific list style." can perhaps be written as a separate sentence to clarify what is being referred to
```suggestion
The **`counters()`** [CSS](/en-US/docs/Web/CSS) [function](/en-US/docs/Web/CSS/CSS_Functions) enables the use of nested counters. It returns a string that concatenates the current values of the named and nested counters, if any are present, and can optionally be displayed in a specific list style.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +The `counters()` function is generally used within [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) {{cssxref("content")}}, but can be used, theoretically, anywhere a [`<string>`](/en-US/docs/We
```suggestion
The `counters()` function is generally used within [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) through the {{cssxref("content")}} property, but theoretically, it can be used wherever a [`<string>`](/en-US/docs/Web/CSS/string) value is supported.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +The `counters()` function has two forms: `counters(<name>, <string>)` and `counters(<name>, <string>, <style>)`. The generated text is the value of all counters with the given `<name.`, from outermos
```suggestion
The `counters()` function has two forms: `counters(<name>, <string>)` and `counters(<name>, <string>, <style>)`. The generated text is the value of all counters with the given `<name>`, arranged from the outermost to the innermost, and separated by the specified `<string>`. The counters are rendered in the `<style>` indicated, defaulting to `decimal` if no `<style>` is specified.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +  - : A {{cssxref("&lt;custom-ident&gt;")}} identifying the counters, which is the same case-sensitive name used for the {{cssxref("counter-reset")}} and {{cssxref("counter-increment")}} properties.
```suggestion
  - : A {{cssxref("&lt;custom-ident&gt;")}} identifying the counters, which is the same case-sensitive name used for the {{cssxref("counter-reset")}} and {{cssxref("counter-increment")}} properties. The name cannot start with two dashes and can't be `none`, `unset`, `initial`, or `inherit`. Alternatively, for inline, single-use counters, the {{cssxref("symbols")}} function can be used instead of a named counter in [browsers that support `symbols()`](/en-US/docs/Web/CSS/symbols#browser_compatibility).
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +  - : A counter style name or [`symbols()`](/en-US/docs/Web/CSS/symbols) function, where a counter style name is a numeric, alphabetic, or symbolic simple predefined counter style, a complex longhand
```suggestion
  - : A counter style name or a [`symbols()`](/en-US/docs/Web/CSS/symbols) function. The counter style name can be a simple predefined style such as numeric, alphabetic, or symbolic, a complex longhand predefined style such as East Asian or Ethiopic, or another [predefined counter style](/en-US/docs/Web/CSS/CSS_counter_styles). If omitted, the counter-style defaults to decimal.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +The return value is the a string containing all the values of all the counters in the element's CSS counters set named `<counter-name>` in the the counter style defined by `<counter-style>` (or decim
Very long sentence. Please consider splitting and rewriting
```suggestion
The return value is a string containing all the values of all the counters in the element's CSS counters set named `<counter-name>` in the counter style defined by `<counter-style>` (or decimal, if omitted), sorted in outermost-first to innermost-last order, joined by the `<string>` specified.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +> **Note:** See the {{cssxref("counter", "counter()")}} function, which omits the `<string>` a parameter, for non-concatenated counters.
```suggestion
> **Note:** For information about non-concatenated counters, see the {{cssxref("counter", "counter()")}} function, which omits the `<string>` as a parameter.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
>  ### default value compared to upper Roman
Should this be:
```suggestion
### Comparing default counter value to uppercase roman numerals
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
> +This example includes two `counters()` functions; one with `<counter-style>` set and the other defaulting to `decimal`.
```suggestion
This example includes two `counters()` functions: one with `<counter-style>` set and the other defaulting to `decimal`.
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counters/index.md
>  ### decimal-leading-zero compared to lower-alpha
Should this be:
```suggestion
### Comparing decimal-leading-zero counter value to lowercase letters
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counter/index.md
> +The `counter()` function is generally used within [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) {{CSSxRef("content")}} property values, but can theoretically be used anywhere a [`<string>`](/
Please apply the same edit here as suggested in counters() file

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counter/index.md
> +> **Note:** See also the {{cssxref("counters", "counters()")}} function which provides a third parameter, a string, to join the counter values when nesting counters.
This sentence can be flipped to say "To join..", "see..."

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counter/index.md
> +### Counter displayed three ways
How about:
```suggestion
### Displaying a counter using three styles
```

2023-12-05 21:00 UTC, dipikabh commented on files/en-us/web/css/counter/index.md
> +We include the `counter()` function with three different counter styles, including the default decimal value. We added padding to the list, providing space for the long `::marker` string.
```suggestion
We include the `counter()` function with three different counter styles, including the default decimal value. We've added padding to the list to provide space for the long `::marker` string.
```

2023-12-06 01:42 UTC, estelle commented on files/en-us/web/css/counter/index.md
> +> **Note:** See also the {{cssxref("counters", "counters()")}} function which provides a third parameter, a string, to join the counter values when nesting counters.
```suggestion
> **Note:** To join the counter values when nesting counters, use the {{cssxref("counters", "counters()")}} function, which provides an additional {{cssxref("string")}} parameter.
```

2023-12-06 01:52 UTC, estelle commented on files/en-us/web/css/counter/index.md
> +The `counter()` function is generally used within [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) {{CSSxRef("content")}} property values, but can theoretically be used anywhere a [`<string>`](/
```suggestion
The `counter()` function is generally used within [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) through the {{cssxref("content")}} property but, theoretically, it can be used wherever a [`<string>`](/en-US/docs/Web/CSS/string) value is supported.
```

2023-12-06 01:55 UTC, estelle commented on files/en-us/web/css/counters/index.md
> +{{EmbedLiveSample("decimal-leading-zero_compared_to_lower-alpha", "100%", 270)}}
```suggestion
{{EmbedLiveSample("Comparing decimal-leading-zero counter value to lowercase letters", "100%", 270)}}
```

2023-12-06 01:56 UTC, estelle commented
Thanks for the review, @dipikabh. I addressed all of your suggestions.

2023-12-06 10:12 UTC, teoli2003 approved these changes
👍

2023-12-07 02:33 UTC, dipikabh approved these changes
Thanks for the updates!

2023-12-07 02:33 UTC, merged