init documentation for ServiceWorkerGlobalScope/messageerror event
mdn/content pull request #30673
Opened 2023-12-01 04:58 UTC by skyclouds2001

### Description

init documentation for ServiceWorkerGlobalScope/messageerror event

### Motivation

### Additional details

see https://w3c.github.io/ServiceWorker/#dom-serviceworkerglobalscope-onmessageerror and https://w3c.github.io/ServiceWorker/#eventdef-serviceworkerglobalscope-messageerror

### Related issues and pull requests

2023-12-03 04:26 UTC, wbamberg requested changes
Thank you @skyclouds2001 !

2023-12-03 04:26 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  - : Represents, in [server-sent events](/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), the last event ID of the event source. This is an empty string.
I don't understand this. If this represents an ID, why is it an empty string?

2023-12-03 04:26 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  console.log("The client sent me a message failed");
```suggestion
  console.error("Message deserialization failed");
```

2023-12-03 04:26 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  console.log("The client sent me a message failed");
```suggestion
  console.error("Message deserialization failed");
```

2023-12-03 04:26 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  event.source.postMessage("Hi client");
Same comment as before.

2023-12-03 04:26 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +
Should include a link to the `message` event, and `postMessage()`

2023-12-05 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  - : Represents, in [server-sent events](/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), the last event ID of the event source. This is an empty string.
emmm, the raw documentation of https://developer.mozilla.org/en-US/docs/Web/API/ExtendableMessageEvent is that, and I just copy that

2023-12-05 04:54 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  - : Represents, in [server-sent events](/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), the last event ID of the event source. This is an empty string.
![image](https://github.com/mdn/content/assets/95597335/14c9c9eb-25eb-4a96-be9b-8597c02ac434)

I check the standard as above, and guess here is intended to suggest the property is initial to be an empty string

2023-12-05 05:01 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  - : Represents, in [server-sent events](/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events), the last event ID of the event source. This is an empty string.
...and if here is no event previously, the property will be an empty string; otherwise the property will be the last event ID of the event source

2023-12-05 05:13 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerglobalscope/messageerror_event/index.md
> +  - : Returns the event's data. It can be any data type.
![image](https://github.com/mdn/content/assets/95597335/bbf4cb85-0ab5-403b-9cb8-9c8b30a73d79)

in this situation, the property should use the initial value `null`

![image](https://github.com/mdn/content/assets/95597335/5899452e-1d86-4079-a01c-f91418fc9566)

2023-12-07 04:43 UTC, wbamberg approved these changes
👍 thank you @skyclouds2001 !

2023-12-07 04:43 UTC, merged