Fix link to Symbol
mdn/content pull request #30686
Opened 2023-12-01 09:17 UTC by teoli2003

There is no glossary entry for symbol, but we have a page about it in JS.

2023-12-01 11:27 UTC, bsmth requested changes
This list item is under "Glossary", and actually it would be great to add a Glossary entry for Symbol, shall we do this instead?

2023-12-03 05:09 UTC, Josh-Cena commented
@bsmth, the glossary entry was _removed_ because anything you write would be JavaScript-technical and not conceptual, and that defeats the purpose of a glossary entry.

2023-12-04 17:02 UTC, teoli2003 commented
I will try to write a short language-neutral symbol type glossary entry. That way we can discuss on something concrete.

2023-12-04 17:03 UTC, Josh-Cena commented
I see rationale for number/string/boolean because they are "conceptual data types" that directly correspond to types in any other language and is thus not JS-centric. BigInt my personal call is to remove as well, but it's short enough. Symbol is impossible to describe without a bunch of technical discussions and seems JS-specific.

2023-12-04 17:06 UTC, teoli2003 commented
This would be an experiment here (= in this PR). And if it isn't successful, it will be only a few lines that will be dropped and not a giant amount of work.

2023-12-04 17:09 UTC, Josh-Cena commented
Oh, _you_ actually approved the PR for its removal 🤣  https://github.com/mdn/content/pull/17749

2023-12-04 17:24 UTC, teoli2003 commented
Yes, I remember it! But as we regularly get proposal, ideas, to add it back, I think this may have been a bad idea.

2023-12-09 10:44 UTC, teoli2003 commented on files/en-us/glossary/type/index.md
> +  - [Symbol](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)
```suggestion
  - {{Glossary("symbol")}}
```

2023-12-09 10:45 UTC, teoli2003 commented
@Josh-Cena What do you think about an entry as simple as this?

2023-12-09 10:52 UTC, teoli2003 commented
(I dont understand why the preview doesn't work, though)

2023-12-09 16:57 UTC, Josh-Cena commented on files/en-us/glossary/symbol/index.md
> +A **symbol** is a data type that represents identifiers. Unicity is guaranteed for each of them. They are sometimes called _atoms_.
```suggestion
A **symbol** is a data type that represents unique, unforgeable identifiers. They are sometimes called _atoms_.
```

2023-12-09 16:57 UTC, Josh-Cena commented on files/en-us/glossary/symbol/index.md
> +In JavaScript, `symbol` is one of the [primitives](/en-US/docs/Glossary/Primitive) and can be created using the [`Symbol()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) factory method
```suggestion
In JavaScript, `symbol` is one of the [primitives](/en-US/docs/Glossary/Primitive) and can be created using the [`Symbol()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) factory method that returns a different symbol each time. They can be used as keys for objects which can never collide with other properties.
```

2023-12-10 18:54 UTC, Josh-Cena commented on files/en-us/glossary/symbol/index.md
> +In JavaScript, `symbol` is one of the [primitives](/en-US/docs/Glossary/Primitive) and can be created using the [`Symbol()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) factory method
```suggestion
In JavaScript, `symbol` is one of the [primitive types](/en-US/docs/Glossary/Primitive) and can be created using the [`Symbol()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) factory method that returns a different symbol each time. They can be used as keys for objects which can never accidentally collide with other properties.

JavaScript also defines two other categories of symbols: well-known symbols and registered symbols. Read the {{jsxref("Symbol")}} reference for more information.
```

2023-12-10 18:59 UTC, Josh-Cena approved these changes

2023-12-10 22:55 UTC, hamishwillee commented on files/en-us/glossary/symbol/index.md
> +A **symbol** is a data type that represents unique, unforgeable identifiers. They are sometimes called _atoms_.
Why do we care? I mean why is an unforgeable identifier useful?

2023-12-10 22:57 UTC, hamishwillee commented
FWIW It's been said above, but I'm OK with glossary entries for things that are cross language, or that are disambiguated. But if something is language specific and has no real generic meaning then it shouldn't be glossary. So BigInt does not make sense to be a glossary item IMO.

2023-12-10 23:02 UTC, Josh-Cena commented on files/en-us/glossary/symbol/index.md
> +A **symbol** is a data type that represents unique, unforgeable identifiers. They are sometimes called _atoms_.
If you have an object and you want to access a property (either read it or modify it), you cannot accidentally read a property that was not what you intended unless you have the reference to the original identifier.

```js
const obj = {
  [Symbol()]: someSecret;
}

function getProperty(x) {
  return obj[x];
}

getProperty("whatever you put here"); // Will never be someSecret
```

2023-12-10 23:52 UTC, hamishwillee commented on files/en-us/glossary/symbol/index.md
> +A **symbol** is a data type that represents unique, unforgeable identifiers. They are sometimes called _atoms_.
Might be worth saying that. Something like (I might not be using correct terminology):

```suggestion
A **symbol** is a data type that represents unique, unforgeable identifiers. They are sometimes called _atoms_.

Because a symbol is unique and unforgeable, you can only read a property value associated with a symbol if you have a reference to the original identifier.
```

2023-12-11 13:25 UTC, bsmth commented
> (I dont understand why the preview doesn't work, though)

Looks like it's something to do with redirects. Local preview looking good, ty

2023-12-11 13:25 UTC, bsmth approved these changes
Great, thank you all!

2023-12-11 13:30 UTC, merged