chore(games) Remove broken links, refer to WebXR instead of WebVR API
mdn/content pull request #30696
Opened 2023-12-01 11:01 UTC by bsmth

Removing a few dead links.

__Broken URLs:__

* https://code.tutsplus.com/tutorials/preparing-for-firefox-os--mobile-18515
* http://www.glge.org/ (removing as this is apparently abandoned since 10 years)
* https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list

__Notes:__
The WebVR article needs a little refresh to make sure prose is all pointing to WebXR instead. Leaving this for a follow-up. Maybe @zfox23 would like to have a look 👀

2023-12-01 14:22 UTC, zfox23 requested changes
ty! I'll also take a look at the page that need refreshed to WebXR as you said.

2023-12-01 15:39 UTC, bsmth commented
> ty! I'll also take a look at the page that need refreshed to WebXR as you said.

Great, thank you!

2023-12-01 15:46 UTC, zfox23 approved these changes

2023-12-01 15:46 UTC, merged

2023-12-02 22:55 UTC, Wasem9926 commented
abohosam_3632@hotmail.com