New css module: CSS syntax. Partially deprecated charset.
mdn/content pull request #30793
Opened 2023-12-05 09:08 UTC by estelle

The original task was to update the charset module. Turns out there is no such thing.
Charset was defined in CSS 2 but removed in the CSS syntax module.

- Move css_charset to css_syntax.
- Created a new document: css_syntax. This is a module landing page. It include the key concepts introduced in that module.
- Created a new document: a guide on CSS error handling by the parser. a subpage for CSS syntax.
- Updated the `@charset` page to indicate that it is NOT an at-rule, and has been deprecated in css-syntax.
- Updated custom-ident, the page that had the best explanation of CSS escape characters, adding a separate section for escaping characters in CSS. This PR does not include creating links to that section. That will be done as a separate PR (this PR is already big enough)

2023-12-07 22:06 UTC, estelle commented
> I have a question: browsers are supporting `@charset` means they don't complain about the syntax but ignore it or are they actually doing something different if we have `@charset "UTF-8"` and `@charset "iso-8859-15"?

It's been removed from the specification, so it's not in the module other than to say it's not needed, so not including it in the ist of properties introduced or defined in the specification/module. Added a sentence to the charset page, so people know the status, but it's in all browsers, so the deprecation is a spec thing, not an implementation thing.... yet.

2023-12-07 22:43 UTC, dipikabh requested changes
Hi @estelle, I've looked at the CSS syntax module page. I'll come back shortly to go through the remaining files.

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +  - : The formal grammar for defining valid values for CSS properties and functions, along with semantic constraints. A guide to CSS component value types, combinators, and multipliers.
```suggestion
  - : The formal grammar for defining valid values for CSS properties and functions, along with semantic constraints. A guide for understanding CSS component value types, combinators, and multipliers.
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +  - : Overview of how the user-agent handles
I guess this got left out. You might have meant to come back to complete this..

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +## Related Concepts
```suggestion
## Related concepts
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +spec-urls: https://drafts.csswg.org/css-syntax
The spec is rendering as "Unknown specification" though the link is valid

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +- [CSS values & units](/en-US/docs/Web/CSS/CSS_values_and_units) module
```suggestion
- [CSS values and units](/en-US/docs/Web/CSS/CSS_Values_and_units) module
```
- This page is not listed under Modules in the sidebar.
- Like in other module landing pages, there is no mention of "CSS values and units module" either in the intro para or anywhere on the https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units page.

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +
I think in the [module landing page template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_module_landing_page_template#related_concepts), we need to define a style for the "Related concepts" section.

We have a style followed here which groups properties, at-rules, etc by the module in which they are defined but we've not followed this approach in other pages like https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders#related_concepts.

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +[CSS selectors](/en-US/docs/Web/CSS/CSS_selectors) module
Each of these lead-ins can be followed by a colon
```suggestion
[CSS selectors](/en-US/docs/Web/CSS/CSS_selectors) module:
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +[CSS Cascade](/en-US/docs/Web/CSS/CSS_cascade) module
```suggestion
[CSS cascade](/en-US/docs/Web/CSS/CSS_cascade) module
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +- {{Glossary("Property/CSS", "property")}}
How about this:
```suggestion
- {{Glossary("Property/CSS", "CSS property")}} glossary term
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +[CSS Custom Properties for Cascading Variables](/en-US/docs/Web/CSS/CSS_cascading_variables) module
```suggestion
[CSS custom properties for cascading variables](/en-US/docs/Web/CSS/CSS_cascading_variables) module:
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +- {{cssxref("var()")}}
```suggestion
- {{cssxref("var")}}
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +[CSS Object Model (CSSOM)](/en-US/docs/Web/API/CSS_Object_Model) module
Is it called a module?
```suggestion
[CSS Object Model (CSSOM)](/en-US/docs/Web/API/CSS_Object_Model)
```

2023-12-07 22:43 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +- {{domxref("CSSStyleSheet.replace()", "replace(text)")}}
I didn't find these of these on this https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model page

2023-12-07 23:11 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +[CSS Object Model (CSSOM)](/en-US/docs/Web/API/CSS_Object_Model) module
the module landing page isn't done yet. Ii'll update to that when it is. In the meantime, we should use API.

2023-12-07 23:12 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +- [CSS values & units](/en-US/docs/Web/CSS/CSS_values_and_units) module
the page that is currently there is not a module landing page... yet. I'll be working on that soon. fingers crossed.

2023-12-07 23:38 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +### Key concepts and definitions
glossary terms is fine. Good call. We used "key concepts and definitions" in a different module, so went with it, but I didn't like the mushed list. Separating them is way better.

2023-12-07 23:45 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +- {{glossary("whitespace")}}
> * `<an + b>` notation 

Removed

> In fact, all these terms that have CSS in their titles on the linked pages can be preceded by CSS here. I am curious if there was a specific reason not to include it in the link text. 
I was going to, but we generally don't in other pages, but i wanted to, so will ;). 

> * [invalid](/en-US/docs/Web/CSS/CSS_syntax/error_handling) --> link text can match the page title
This is the concept of being "invalid". The term is a bit overused (here, :invalid, :user-invalid, form validation, etc., but it has a specific meaning, defined in that page.

> * [rule](/en-US/docs/Web/API/CSSRule) --> CSSRule interface?

Removed, since it's not that key of a concept.

2023-12-07 23:50 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +
good idea.

the related concepts in background and borders is well defined by the name of the property in the list. Here its'a bit of a mishmash. We could omit the modules, but including the CSS cascade module kind of makes it evident as to why all the values are listed in related instead of key concepts of syntax. the module on background wasn't necessary, and it was one of the first, but we likely should include the modules because when the module adds context, we should include it, so we might as well always include it.

2023-12-07 23:53 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +- {{domxref("CSSStyleSheet.replace()", "replace(text)")}}
CSSValue and CSSStylesheet is listed on that page. Should we write this instead?

```suggestion
- {{domxref("CSSValue.cssText")}}  property
- {{domxref("CSSStyleSheet.insertRule()")}} method
- {{domxref("CSSStyleSheet.replace()")}} method
```

2023-12-09 04:29 UTC, dipikabh requested changes
Syntax error handling is a really long page! Sending across what I've reviewed so far.

2023-12-09 04:29 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +- If a semi-colon is omitted between property declarations, the [missing semi-colon](#errors-within-css-declaration-blocks) causes an invalid value, so the declaration is ignored.
```suggestion
- An [error due to a missing semi-colon](#errors-within-css-declaration-blocks) between property declarations causes an invalid value, in which case, the property-value declaration is ignored.
```

2023-12-09 04:29 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +- If the [error is a property name or value](#errors-within-css-declaration-blocks), such as an unrecognized property name or invalid data type, just that property/value declaration is ignored.
```suggestion
- If the [error is a property name or value](#errors-within-css-declaration-blocks), such as an unrecognized property name or invalid data type, the property-value declaration is ignored.
```

2023-12-09 04:29 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +- If the [error is a property name or value](#errors-within-css-declaration-blocks), such as an unrecognized property name or invalid data type, just that property/value declaration is ignored.
These two can be combined to say that errors in CSS declaration blocks (the ruleset) can be due to invalid property name or missing semi-colon
```suggestion
- If a semi-colon is omitted between property declarations, the [missing semi-colon](#errors-within-css-declaration-blocks) causes an invalid value, so the declaration is ignored.
- If the [error is a property name or value](#errors-within-css-declaration-blocks), such as an unrecognized property name or invalid data type, just that property/value declaration is ignored.
```

2023-12-09 04:29 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +- If the issue is a [missing end-bracket](#auto-closed-endings), what gets ignored, if anything, depends on whether the user-agent can parse the error as nested CSS.
```suggestion
- If the [error is due to a missing end-bracket](#auto-closed-endings), the extent of what is ignored depends on the browser's ability to parse the error as nested CSS.
```

2023-12-09 04:29 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +After each declaration, style rule, at-rule, etc. is parsed, the user agent checks the parsed content against its expected [grammar](#grammar-check) for that construct. If it does not match the expec
```suggestion
After parsing each declaration, style rule, at-rule, and so on, the browser checks the parsed content against its expected [grammar](#grammar-check) for that construct. If the content does not match the expected grammar for that construct, the browser considers it invalid and ignores it.
```

2023-12-11 00:50 UTC, dipikabh requested changes, later dismissed

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +The valid CSS rules are the last ones in each declaration block above. The parser ignores the rules it doesn't understand as invalid. If the user agent does understand one of the prefixed rules, as a
- "rule" vs "declaration": In this [anatomy of CSS ruleset](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#anatomy_of_a_css_ruleset), each property-value pair is being called a declaration
- I think the last sentence is rather confusing because we're now introducing another concept. We can separate the two thoughts: one to say that the declarations are valid and another point to say that even though they are valid, they will be used because of cascade. Maybe include another example to show what happens when there are valid declarations but appear before prefixed values (that is, give an example for what we're saying in the Note later)

```suggestion
In both the declaration blocks above, the last declaration is valid. The parser ignores the declarations it doesn't understand as invalid. If the user agent does understand one of the prefixed declarations, for example, all browsers understand `display: flex;` and `border-radius: 50%;`, the values in the last, valid declaration are used, not because they are the valid ones, but rather due to the [cascade](/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#source_order) [order of appearance](/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers) rule.
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +> **Note:** Avoid including prefixed properties or property values. If you must, declare the prefixed values before the valid, non-prefixed standard compliant property and value.
```suggestion
> **Note:** Avoid including prefixed properties or property values. If you must, declare the prefixed values before the valid, non-prefixed standard property-value pairs.
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +If the content between the last semi-colon and the end of the stylesheet is valid, even if incomplete, the CSS will be parsed normally. Failing to properly close CSS statements doesn't necessarily ma
Can we provide an example for this?
```suggestion
If the content between the last semi-colon and the end of the stylesheet is valid, even if incomplete, the CSS will be parsed normally. Failing to properly close CSS statements doesn't necessarily make the statements invalid.
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +> **Note:** Do not take advantage of CSS's forgiving nature. Always close all of your statements and style blocks. It makes your CSS easier to read and maintain and ensures that the browser parses th
This note should probably not be confined to this section. Can probably be moved right before starting the "CSS parser errors" section.
```suggestion
> **Note:** Do not take advantage of CSS's forgiving nature. Always close all of your statements and style blocks. It makes your CSS easier to read and maintain and ensures that the browser parses the CSS you intended.
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +> **Note:** If a comment is with `/*` but not closed, any and all CSS encountered until the closing comment `*/` is found will be treated as a comment. Forgetting to close a comment may not make your
```suggestion
> **Note:** If a comment starts with `/*` but is not closed, all CSS code until the closing comment `*/` is encountered will be treated as part of the comment. While an unclosed comment does not invalidate your CSS, but it causes the CSS inside the comment to be ignored.
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +### Auto-closed endings
To make it consistent with other headings.
```suggestion
### Errors with auto-closed endings
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +After each declaration, style rule, at-rule, etc. is parsed, the user agent checks to make sure the grammar is the expected grammar for that declaration. For example, if a property value is of the wr
This section and content is not worded like errors as the other subsections. Does this need to be H2?

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/@charset/index.md
> +The **`@charset`** [CSS](/en-US/docs/Web/CSS) rule specifies the character encoding used in the style sheet. Although the first character is the `@` symbol, it is not an [at-rule](/en-US/docs/Web/CSS
```suggestion
The **`@charset`** [CSS](/en-US/docs/Web/CSS) rule specifies the character encoding used in the style sheet. Although the first character in `@charset` is the `@` symbol, it is not an [at-rule](/en-US/docs/Web/CSS/At-rule). The [CSS syntax](/en-US/docs/Web/CSS/CSS_syntax) module deprecates this rule, defining it as an unrecognized legacy rule to be dropped when a stylesheet is grammar-checked, but it is [fully supported in all browsers](#browser-compatibility).
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +title: CSS syntax error handling
Should this page be about syntax errors because there's no info about "handling". It is just making readers aware of the type of syntax errors.
```suggestion
title: CSS syntax errors
```

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/css_syntax/index.md
> +
This section in "Learn" can also be added to the list here: https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS#css_syntax

2023-12-11 00:50 UTC, dipikabh commented on files/en-us/web/css/custom-ident/index.md
> +- One to six hex (`ABCDEF0123456789`) digits. The hex digits can optionally be followed white space. The hex escape sequence gets replaced by the Unicode code point whose value is given by those digi
```suggestion
- One to six hex (`ABCDEF0123456789`) digits. The hex digits can optionally be followed by white space. The hex escape sequence gets replaced by the Unicode code point whose value is given by those digits. The whitespace allows the sequences to be followed by actual hex digits (versus replaced ones).
```

2023-12-13 20:59 UTC, estelle commented on files/en-us/web/css/css_syntax/index.md
> +  - : Overview of how the user-agent handles invalid CSS
```suggestion
  - : Overview of how the user-agent handles invalid CSS
  
- [Learn CSS first steps: CSS syntax](/en-US/docs/Learn/CSS/First_steps/What_is_CSS#css_syntax)

  - : Introductory guide to CSS, including an introcution to CSS syntax. 
```

2023-12-13 21:51 UTC, estelle commented on files/en-us/web/css/css_syntax/error_handling/index.md
> +- If the [error is a property name or value](#errors-within-css-declaration-blocks), such as an unrecognized property name or invalid data type, just that property/value declaration is ignored.
i want to keep these separate because some people may not get that a missing semi-colon creates an invalid value..

2023-12-15 08:16 UTC, closed without merging