draft Invokers API docs
mdn/content pull request #30829
Opened 2023-12-06 11:02 UTC by keithamus

### Description

This PR drafts up the documentation for "Invokers" ([OpenUI explainer](https://open-ui.org/components/invokers.explainer/)). This is a new experimental API for enabling buttons to control interactive elements.

### Motivation

As this feature is starting to land (flagged) in 3 major browsers, it seems right to start documenting the featureset.

### Additional details

- [Chrome Platform Status feature](https://chromestatus.com/feature/5142517058371584)
- [Mozilla has positive signals](https://github.com/mozilla/standards-positions/issues/902) on this feature.
- [Safari has no signal](https://github.com/WebKit/standards-positions/issues/264) but the [initial prototype has been merged](https://github.com/WebKit/WebKit/pull/18794) for testing 

### Related issues and pull requests

2023-12-06 11:05 UTC, teoli2003 commented
(Converted to draft so that nobody review this, yet)

2023-12-06 11:36 UTC, lukewarlow commented on files/en-us/web/api/invokers_api/index.md
> +The **Invokers API** provides developers with a standard, consistent, flexible mechanism for controlling interactive HTML Elements on the page. Invokers allow for declaratively control using HTML att
Second from the last line it should be declarative not declaratively.

2023-12-06 11:39 UTC, lukewarlow commented on files/en-us/web/api/invokers_api/index.md
> +It is very common on the web to control interactive elements using {{htmlelement("button")}} elements, adding JavaScript event listeners to control what a button does when pressed. Invokers provide a
Maybe drop the details elements mention as it won't be in v1?

2023-12-06 11:40 UTC, lukewarlow commented on files/en-us/web/api/invokers_api/index.md
> +  - : Turns a {{htmlelement("button")}} or {{htmlelement("input")}} element into a Invoker control button; takes the ID of the element to control as its value.
nit: maybe clarify not *all* inputs?

2023-12-06 11:44 UTC, lukewarlow commented on files/en-us/web/api/invokers_api/index.md
> +- [`invokeaction`](/en-US/docs/Web/HTML/Element/button#invokeaction)
This doesn't appear to actually link correctly

2023-12-06 11:46 UTC, lukewarlow commented on files/en-us/web/api/invokeevent/index.md
> +The **`InvokeEvent`** interface represents an event notifying the user when a [invoker control](/en-US/docs/Web/API/Invoker_API) is about to invoke an interactive element.
Dead link, should be Invokers_API

2023-12-06 11:48 UTC, lukewarlow commented on files/en-us/web/api/invokeevent/index.md
> +It is the event object for the `HTMLElement` {{domxref("HTMLElement.invoke_event", "invoke")}} event, which fires elements from an Invoker Control, when the Invoker Control is interacted with (for ex
"fires elements"?

2023-12-06 11:48 UTC, lukewarlow commented on files/en-us/web/api/invokeevent/index.md
> +It is the event object for the `HTMLElement` {{domxref("HTMLElement.invoke_event", "invoke")}} event, which fires elements from an Invoker Control, when the Invoker Control is interacted with (for ex
Interacted with could suggest hover or focus? Probably one for actual reviewers to decide on the wording cause I'd just be guessing.

2024-09-06 17:31 UTC, Josh-Cena reviewed
Is https://github.com/mdn/browser-compat-data/pull/21542 the corresponding BCD PR? Because curiously the data added there don't match the pages here. It would be good to have BCD so we can confirm that it's shipping somewhere because we don't document unimplemented things.

2024-09-06 17:58 UTC, lukewarlow commented
We'll need a new data PR because the feature ended up being renamed pretty late in the game.

2024-09-06 21:19 UTC, keithamus commented
Apologies I should have also linked https://github.com/mdn/browser-compat-data/pull/24362 which is the respective PR renaming these elements in BCD.

2024-09-09 21:26 UTC, keithamus commented
> Apologies I should have also linked [mdn/browser-compat-data#24362](https://github.com/mdn/browser-compat-data/pull/24362) which is the respective PR renaming these elements in BCD.

The BCD PR is now merged so I think this is ready for review.

2024-09-09 21:41 UTC, Josh-Cena requested changes
For a new API area, you would need the following:

1. An API landing page that summarizes the API surface. See https://developer.mozilla.org/en-US/docs/Web/API/URL_Fragment_Text_Directives for what it would look like minimally.
2. Optionally, some guide articles that explain how you could use these APIs for use cases: for example https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch. If you don't do this then at least have some examples and/or explainer on the API landing page.
3. For every additional member on existing interfaces, make sure the interface landing page's property list is also updated.
4. You would need to update `files/jsondata/GroupData.json` to include this new API. Then, each new page could have the right sidebars associated (see the two linked pages above and look around for more examples of which macros to use).

I think you would be the most appropriate person to create these articles, so would you like to do so?

2024-09-10 09:53 UTC, keithamus commented
@Josh-Cena sure, no problem. I've added an API page with examples and the respective interfaces. Hopefully this suffices.

2024-09-11 19:07 UTC, Josh-Cena requested changes

2024-09-11 19:07 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/command/index.md
> +### Basic example
Add an `## Examples` heading above, and HTML below

2024-09-11 19:07 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/commandforelement/index.md
> +A reference to an element in the DOM.
```suggestion
A reference to an existing {{domxref("HTMLElement")}} that the button controls.
```

General comment is we should be very precise about these types, here and elsewhere. `Element`? `HTMLElement`? `EventTarget`?

2024-09-11 19:07 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +A common pattern on the web is to have {{domxref("HTMLButtonElement", "button")}} elements control various aspects of the page, such as opening and closing {{domxref("Popover API", "popovers", "", "n
```suggestion
A common pattern on the web is to have {{HTMLElement("button")}} elements control various aspects of the page, such as opening and closing {{domxref("Popover API", "popovers", "", "nocode")}} or {{HTMLElement("dialog")}} elements, formatting text, and more.
```

General comment is we just link to HTML docs when we talk about the HTML elements (and we add the `<>`). Many HTML experts dislike it but it kind of sticks.

2024-09-11 19:07 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +- {{domxref("HTMLButtonElement.command", "command")}} provide a way to do this declaratively for a limited set of actions.
If you want to point to the HTML content attributes, link to the HTML docs. You can use Markdown links because there are no macros for these.

2024-09-11 21:23 UTC, keithamus commented on files/en-us/web/api/commandevent/commandevent/index.md
> +      - : A string containing the command for the controlled element to take.
This has to be either a built-in or prefixed with a `--`. I'll work this into here to make it clear.

2024-09-12 10:57 UTC, ryantownsend commented on files/en-us/web/api/invoker_commands_api/index.md
> +Historically creating these kinds of controls has required JavaScript event listeners added to the button which can then call the APIs on the element they control. The {{domxref("HTMLButtonElement.co
@keithamus it might be nice to mention the benefit of this is as soon as the visitor can see the button, they can interact with it – rather than either having to wait, or the more common thing: seeing it rendered, thinking they can interact and wondering why it's not working (because the JavaScript powering it has yet to download/parse/execute).

2024-09-16 17:38 UTC, keithamus commented on files/en-us/web/api/htmlbuttonelement/commandforelement/index.md
> +A reference to an element in the DOM.
It's `Element`. I'll adjust.

2024-09-23 03:23 UTC, Josh-Cena approved these changes
Thanks; I have a lot of nits proposed, but I think this looks good already.

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/command/index.md
> +- {{domxref("HTMLButtonElement.commandForElement", "commandForElement")}} property
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("HTMLButtonElement.commandForElement")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/commandevent/index.md
> +    It is case-sensitive and browsers set it to `beforeinput`, or `input`.
```suggestion
    It is case-sensitive and browsers set it to `beforeinput` or `input`.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/commandevent/index.md
> +- {{domxref("CommandEvent", "CommandEvent")}} interface
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("HTMLButtonElement.commandForElement"_}}
- {{domxref("CommandEvent")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/command/index.md
> +- {{domxref("CommandEvent", "CommandEvent")}} interface
```suggestion
- {{domxref("HTMLButtonElement.commandForElement")}}
- {{domxref("CommandEvent")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/source/index.md
> +- {{domxref("HTMLButtonElement.commandForElement", "commandForElement")}} property
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("HTMLButtonElement.commandForElement")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/index.md
> +- {{domxref("HTMLButtonElement.commandForElement", "commandForElement")}} property
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("HTMLButtonElement.commandForElement")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/source/index.md
> +An {{domxref("EventTarget")}} object.
```suggestion
An {{domxref("EventTarget")}} object. Usually an {{domxref("HTMLButtonElement")}}.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/command/index.md
> +The **`command`** property of the {{domxref("HTMLButtonElement")}} interface gets and sets the action to be performed on an element being controlled by a button. For this to have an effect, [`command
```suggestion
The **`command`** property of the {{domxref("HTMLButtonElement")}} interface gets and sets the action to be performed on an element being controlled by this button. For this to have an effect, [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor) must be set.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/command/index.md
> +A string.
```suggestion
A string. See the [`command`](/en-US/docs/Web/HTML/Element/button#command) attribute for valid values.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/commandforelement/index.md
> +- {{domxref("CommandEvent", "CommandEvent")}} interface
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("CommandEvent")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlelement/command_event/index.md
> +The **`command`** event of the {{domxref("HTMLElement")}} interface fires on a element that is controlled via a {{domxref("HTMLButtonElement", "button")}} with valid {{domxref("HTMLButtonElement.comm
```suggestion
The **`command`** event of the {{domxref("HTMLElement")}} interface fires on an element that is controlled via a {{domxref("HTMLButtonElement", "button")}} with valid {{domxref("HTMLButtonElement.commandForElement", "commandForElement")}} and {{domxref("HTMLButtonElement.command", "command")}} values, whenever the button is interacted with (e.g. it is clicked).
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlelement/command_event/index.md
> +### A note on event dispatch and cancellation
```suggestion
### Event dispatch and cancellation
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/htmlelement/command_event/index.md
> +- {{domxref("HTMLButtonElement.commandForElement", "commandForElement")}} property
```suggestion
- {{domxref("HTMLButtonElement.command")}}
- {{domxref("HTMLButtonElement.commandForElement")}}
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +The Invoker Commands API provides a way to declaratively assign behaviors to buttons, allowing control of interactive elements when the button is enacted (clicked or invoked via a keypress, such as t
```suggestion
The **Invoker Commands API** provides a way to declaratively assign behaviors to buttons, allowing control of interactive elements when the button is enacted (clicked or invoked via a keypress, such as the spacebar or return key).
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +## HTML Attributes
```suggestion
## HTML attributes
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/html/element/button/index.md
> +      - : The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. See the {{domxref("Popover API", "Popo
```suggestion
      - : The button will show a hidden popover. If you try to show an already showing popover, no action will be taken. See {{domxref("Popover API", "Popover API", "", "nocode")}} for more details.
    - `"hide-popover"`
      - : The button will hide a showing popover. If you try to hide an already hidden popover, no action will be taken. See {{domxref("Popover API", "Popover API", "", "nocode")}} for more details.
    - `"toggle-popover"`
      - : The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. See {{domxref("Popover API", "Popover API", "", "nocode")}} for more details.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +      - : This attribute can represent custom values that are prefixed with a two hyphen characters (`--`). Buttons with a custom value will dispatch the {{domxref("CommandEvent")}} on the controlled
```suggestion
- [`command`](/en-US/docs/Web/HTML/Element/button#command)
  - : Specifies the action to be performed on an element being controlled by a control `<button>`, specified via the `commandfor` attribute.
```

2024-09-23 03:23 UTC, Josh-Cena commented on files/en-us/web/api/invoker_commands_api/index.md
> +- [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor):
```suggestion
- [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor)
```

2024-09-23 21:32 UTC, Josh-Cena commented on files/en-us/web/api/commandevent/commandevent/index.md
> +- {{domxref("HTMLButtonElement.commandForElement"_}}
```suggestion
- {{domxref("HTMLButtonElement.commandForElement")}}
```

2024-09-23 21:38 UTC, Josh-Cena commented
Should I wait for the other reviewers to make a final pass?

2024-09-26 18:27 UTC, keithamus commented
Given it's been three days since your comment perhaps the "waiting for other reviewers" has passed anyway?

2024-09-26 22:56 UTC, Josh-Cena commented
I'll merge this some time next week.

2024-09-27 11:40 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +The **Invoker Commands API** provides a way to declaratively assign behaviors to buttons, allowing control of interactive elements when the button is enacted (clicked or invoked via a keypress, such
Perhaps "enacted" could be replaced with another word. It doesn't quite read naturally to me. Maybe "activated", idk what the normal word mdn uses is.

2024-09-27 12:52 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +Historically creating these kinds of controls has required JavaScript event listeners added to the button which can then call the APIs on the element they control. The {{domxref("HTMLButtonElement.co
It should be The commandForElement and command **properties** provide a way...

2024-09-27 12:53 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +Historically creating these kinds of controls has required JavaScript event listeners added to the button which can then call the APIs on the element they control. The {{domxref("HTMLButtonElement.co
Having said that it's not the properties that provide the way to do this declaratively it's the attributes so perhaps this should link to the attributes?

2024-09-27 12:55 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +  - : Gets and sets the element being controlled by the control button. The JavaScript equivalent of the [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor) HTML attribute.
```suggestion
  - : Gets and sets the element being controlled by the control button. The JavaScript equivalent of the [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor) HTML attribute.
  + : Gets and sets the element being controlled by the button. The JavaScript equivalent of the [`commandfor`](/en-US/docs/Web/HTML/Element/button#commandfor) HTML attribute.
```

2024-09-27 12:57 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +- `HTMLElement` {{domxref("HTMLElement.command_event", "command")}} event
The `HTMLElement` bit feels superfluous idk if it's included in other pages?

2024-09-27 12:57 UTC, lukewarlow commented on files/en-us/web/api/invoker_commands_api/index.md
> +<button commandfor="mypopover" command="toggle-popover">
We should be setting explicit type attributes in all these examples to encourage best practice (and avoid the oddities around forms)

2024-09-27 13:00 UTC, lukewarlow commented
The preview suggests there's issues with the browser compat data is that expected?

2024-09-27 13:03 UTC, lukewarlow commented on files/en-us/web/html/element/button/index.md
> +  - : Turns a {{htmlelement("button")}} element into a control button, controlling the given interactive element; takes the ID of the element to control as its value.
"control button" like elsewhere I feel like control button could be changed to something else? Given the API is Invoker Commands API

2024-09-27 18:53 UTC, keithamus commented on files/en-us/web/html/element/button/index.md
> +  - : Turns a {{htmlelement("button")}} element into a control button, controlling the given interactive element; takes the ID of the element to control as its value.
I'm borrowing this terminology from the existing prose around `popovertarget` - which uses "control button". Happy to change but I think it's worth keeping them the same.

2024-09-27 19:00 UTC, lukewarlow commented on files/en-us/web/html/element/button/index.md
> +  - : Turns a {{htmlelement("button")}} element into a control button, controlling the given interactive element; takes the ID of the element to control as its value.
Ah that's fine then

2024-09-28 05:43 UTC, Josh-Cena commented
> The preview suggests there's issues with the browser compat data is that expected?

I think the only issue is that there's no spec URL, which is kind of expected given that https://github.com/whatwg/html/pull/9841 is still open. @keithamus if you want to make an issue to BCD to keep it in the backlog it would be great.

2024-10-15 18:37 UTC, Josh-Cena commented
@keithamus Just waiting on the last bits of reviews to be addressed

2024-10-16 11:08 UTC, keithamus commented
> > The preview suggests there's issues with the browser compat data is that expected?
> 
> I think the only issue is that there's no spec URL, which is kind of expected given that [whatwg/html#9841](https://github.com/whatwg/html/pull/9841) is still open. @keithamus if you want to make an issue to BCD to keep it in the backlog it would be great.

https://github.com/mdn/browser-compat-data/issues/24739

2024-10-17 19:11 UTC, scottaohara commented on files/en-us/web/api/commandevent/index.md
> +<img id="the-image" src="photo.jpg" />
mind if we add something like this?  i know it's just an example.... but also, i talk to enough devs that are like 'well I copied the example from the spec/mdn" so....

```suggestion
<img id="the-image" src="photo.jpg" alt="[add appropriate alt text here]" />
```

while there are a few instances of these img examples, i'm just going to comment on them once.

2024-10-17 19:11 UTC, scottaohara commented on files/en-us/web/api/commandevent/index.md
> +</div>
similar to my img example comment, but would love to move away from supporting the narrative that showing a generic popover div was ever the primary use case for this attribute.

these sorts of examples can match the `<dialog>` element examples, if they were like...
```suggestion
<div popover id="mypopover" role="[declare appropriate ARIA role]">
  <!-- popover content here -->
  <button commandfor="mypopover" command="hide-popover">Hide popover</button>
</div>
```

while there are a few instances of these examples, i'm just going to comment on them once.

2024-10-24 16:18 UTC, Josh-Cena commented
@lukewarlow Let me know when this is good to merge

2024-10-24 16:21 UTC, lukewarlow commented
Lgtm!

2024-10-24 16:50 UTC, keithamus commented
It doesn't seem necessary to me to wait but if people would like to I don't mind.

2024-10-24 21:36 UTC, Josh-Cena commented
Thanks for all the work everyone; since we have BCD already, I think this meets the documentation criteria and we can merge it.

2024-10-24 21:36 UTC, merged