docs(CSS): Allow more usage of multi-keyword `display` values
mdn/content pull request #30831
Opened 2023-12-06 11:48 UTC by bsmth

### Description

This PR is a refresh in places where we talk about changing the outer display values, with an emphasis on single v multi-keyword values in some common cases, e.g.:

```
inline-flex -> inline flex
```

I'm looking at flexbox and `display` here, with room for changes to grid and other areas in follow-ups.

__Additions:__

* See Also linking the `display`, grid and flexbox modules
* hint that `display: inline flex` can be used for inline container in some docs
* multi-keyword values to `display` page live sample

__Changes:__

* Update prose such as "but this is not yet well-supported by browsers" and "support is available in most new browsers"
* "New" -> "Current" etc.

### Motivation

This feature is mature enough in stable versions, so we can start removing experimental status and prose that warns against usage.

See https://developer.mozilla.org/en-US/docs/Web/CSS/display#browser_compatibility

### Related issues and pull requests

- [x] https://github.com/mdn/content/pull/29103

2023-12-06 18:16 UTC, estelle commented on files/en-us/learn/css/css_layout/flexbox/index.md
> +Flexbox is widely available in modern browsers, but there are older browsers that don't support modern flexbox features, or flexbox at all.
This whole section can be removed. Flexbox has been in browsers for 9 years.

2023-12-06 19:19 UTC, estelle requested changes
cool to see two values is finally supported. Made some suggestions

2023-12-14 10:03 UTC, bsmth commented on files/en-us/learn/css/css_layout/flexbox/index.md
> +Flexbox is widely available in modern browsers, but there are older browsers that don't support modern flexbox features, or flexbox at all.
Good, done in ef217b5e8ca21f822d946c59021141f57406ecb4

2023-12-14 10:03 UTC, bsmth commented on files/en-us/learn/css/css_layout/flexbox/index.md
> +Let's recap what's happening here. The element with a {{cssxref("display")}} value of `flex` is acting like [Block-level content](/en-US/docs/Glossary/Block-level_content) in terms of how it interact
Nice, made some improvements in ef217b5e8ca21f822d946c59021141f57406ecb4

2023-12-14 10:03 UTC, bsmth commented on files/en-us/learn/css/css_layout/flexbox/index.md
> +You can make the container itself inline using an [outside `display` value](/en-US/docs/Web/CSS/display#outside) (e.g., `display: inline flex`), which affects how the container is laid out in the pag
Added in ef217b5e8ca21f822d946c59021141f57406ecb4

2023-12-14 10:14 UTC, bsmth commented on files/en-us/learn/css/css_layout/flexbox/index.md
> +You can make the container itself inline using an [outside `display` value](/en-US/docs/Web/CSS/display#outside) (e.g., `display: inline flex`), which affects how the container is laid out in the pag
Side note, I wasn't totally sure about calling it "legacy" here when starting on this PR, as the spec doesn't call for firmly deprecating the single-word syntax (as far as I can tell), but I think this is a good call to help promote using the multi-keyword values. A good data point is that this is good for learning:

>I plan to teach layout using `display:	[ <display-outside> || <display-inside> ]` immediately

source: https://bugzilla.mozilla.org/show_bug.cgi?id=1038294#c4

2023-12-14 10:15 UTC, bsmth commented on files/en-us/web/css/display-outside/index.md
> +> **Note:** When browsers that support multi-keyword syntax encounter a display property that only has an **outer** value (e.g., `display: block` or `display: inline`), the inner value is set to `flo
>All browsers now support it, so we can future-write the content on the display-outside and display-inside pages

super, tnx

2023-12-14 10:18 UTC, bsmth commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +| Single value   | Current value      |
>i am leaning toward single / multi

I think that's a good call

2023-12-14 10:24 UTC, bsmth commented on files/en-us/web/css/display/index.md
> +This can be specified using a single value:
Spotted that the spec refers to them as legacy now: https://www.w3.org/TR/css-display-3/#typedef-display-legacy, so I think we can.

2023-12-14 10:44 UTC, bsmth commented on files/en-us/web/css/display/index.md
> +> This is backwards-compatible with single-keyword syntax; for example, if you specify an element to be `display: grid`, you would expect that the box created on the grid container would be a block-l
I've removed the second sentence in b207093c181e7d0a7ab0cfc64c0a2ee8457e8ca0

2023-12-14 10:58 UTC, bsmth commented on files/en-us/web/css/css_display/index.md
> +- [Using the multi-keyword syntax with CSS display](/en-US/docs/Web/CSS/display/multi-keyword_syntax_of_display)
done in a68e7c227fd67ea1ceb2f10baa8a50c1959dd153

2023-12-14 10:58 UTC, bsmth commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +> **Note:** multi-keyword syntax may also be referred to as "two-value syntax" or "multi-value syntax."
done in a68e7c227fd67ea1ceb2f10baa8a50c1959dd153

2023-12-14 16:26 UTC, bsmth commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +In the example below, we have a floated item inside a container. The float is contained by the bordered box, which wraps it and the text alongside. If you remove the line `display: flow-root` then th
Yeah good idea (do we want to avoid floats in general?)

2023-12-14 22:37 UTC, estelle commented
Hi @bsmth when you want a review, please click on the "reset" icon next to my name under "reviewers". That sends me a notification. The red +/- lets me know you're still in edit mode. When you click on the reset, that red icon changes to a brown dot; the brown dot lets me know the ball is in my court.

2023-12-15 14:06 UTC, bsmth commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +In the example below, we have a floated item inside a container. The float is contained by the bordered box, which wraps it and the text alongside. If you remove the line `display: flow-root` then th
done in 888bc1a5c0d11002cf62277a3cb33da642e2eca3

2023-12-15 15:54 UTC, bsmth commented on files/en-us/web/css/display/index.md
> +> **Note:** When browsers that support multi-keyword syntax encounter a display property that only has an **outer** value (e.g., `display: block` or `display: inline`), the inner value is set to `flo
done in afbeb370849ca0a9341d2446fab43540b4bf817a

2023-12-18 23:50 UTC, estelle reviewed
Mostly looks good. just a few minor tweaks left to most of it. Major changes to the example.

2023-12-18 23:50 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +Choose the options in the `<select>` element to see the effect of different `display` values.
```suggestion
Change the selected option in the `<select>` element to see the effect of different `display` values.
```

2023-12-18 23:50 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +Changing between `display: flow-root` and `display: block flow-root` will achieve the same effect as the single `flow-root` value.
```suggestion
Changing between `display: flow-root` and `display: block flow-root` will achieve the same effect as the single-value `flow-root` keyword.
```

2023-12-18 23:50 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +</div>
```suggestion
  <div id="child">
    <p>The #child element (nested in the #parent).</p>
  </div>
</div>
<div id="sibling">
  <p>The #sibling (to the #parent)</p>
</div>
```
if you think this helps make it easier to understand

2023-12-19 00:05 UTC, estelle reviewed
the text was disappearing when the background was disappearing.

2023-12-19 00:05 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +  color: white;
```suggestion
```
changing colors because the text disappears when the background does.

2023-12-19 00:05 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +  background-color: mediumslateblue;
```suggestion
  background-color: oldlace;
  min-height: 2rem;
}

#child {
  margin-top: 4rem;
  outline: 2px dashed red;
}

#sibling {
  background-color: lavender;
```

2023-12-19 00:05 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +  margin-bottom: 40px;
```suggestion
  margin-bottom: 2rem;
```

2023-12-19 00:05 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +  color: black;
```suggestion
```
no longer needed.

2023-12-19 00:10 UTC, estelle reviewed
We have to update the example because 
- the white text was not visible when the background disappeared.
- the behavior of a block `<p>` inside an inline `<div>` is not something we want to explain

SO i made some suggestions. You may want to zero out or explicitly define the `margin` on the `p` remove the issue of omitting a mention but it still having an effect.

2023-12-19 00:10 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +In the example below, four `<div>` elements demonstrate how display values affect formatting contexts.
```suggestion
In the example below, two `<p>` elements, one inside a `<div>` demonstrate how display values affect formatting contexts.
```

2023-12-19 00:10 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +The elements that we should focus on are the "parent", "child", and "sibling" `<div>` elements which you can differentiate by their IDs.
```suggestion
The elements that we should focus on are the "parent", "child", and "sibling" `<div>` and `<p>` elements which you can differentiate by their IDs.
```

2023-12-19 01:19 UTC, adriana0108 commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +In the example below, four `<div>` elements demonstrate how display values affect formatting contexts.
Quem é o pai?

2023-12-19 01:23 UTC, adriana0108 commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +Changing between `display: flow-root` and `display: block flow-root` will achieve the same effect as the single `flow-root` value.
Não se fala nada inteligível?

2023-12-19 09:02 UTC, bsmth commented
> Mostly looks good. just a few minor tweaks left to most of it. Major changes to the example.

Great, tnx. Taking a look 👀

2023-12-19 09:04 UTC, bsmth commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +You might expect that the top margin of the child element gives it a positioning somewhere in the middle of the parent element, but what happens instead is something called [margin collapse](/en-US/d
sure, let's do that. Editing your suggestion so I can apply it directly.

2023-12-26 21:18 UTC, estelle commented on files/en-us/web/css/display/multi-keyword_syntax_of_display/index.md
> +<p id="sibling">The #sibling paragraph (to the #parent)</p>
```suggestion
  <p id="child">The #child paragraph (nested in #parent).</p>
</div>
<p id="sibling">The #sibling paragraph (sibling of #parent)</p>
```

2023-12-26 21:19 UTC, estelle approved these changes
Yay! 🎉

2023-12-26 21:19 UTC, merged

2024-01-08 11:07 UTC, bsmth commented
Thank you!