Add documentation of component.utils exportFunction and cloneInto
mdn/content pull request #30877
Opened 2023-12-08 18:06 UTC by rebloor

### Description

WIP to add component.utils exportFunction and cloneInto.

Todo:

- [ ] Finalize links in new pages
- [ ] Finalize location
- [ ] Add BCD
- [ ] Add internal references, e.g. from [Sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) 

### Motivation

These functions are references in [Sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) but not documented on MDN.

### Related issues and pull requests

Fixes #29771

2023-12-27 15:32 UTC, Rob--W requested changes
The Components.utils API is an internal implementation detail of Firefox. Many years ago legacy Firefox add-ons had access to it, but WebExtensions don't. Their content scripts only have access to `cloneInto`/`exportFunction`, which exposes the same functionality.

There may be old links on the web pointing to these methods; if that is the concern I'd rather want redirects to the WebExtension-specific documentation.

If you need a place to host the method descriptions, I recommend to put them under Content_scripts/.

2023-12-27 15:32 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/components/index.md
> +> **Note:** This API is based on Chromium's [`chrome.devtools`](https://developer.chrome.com/docs/extensions/mv2/devtools/) API.
Looks like a mistake? This API is Firefox-only.

2023-12-27 17:44 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/components/index.md
> +> **Note:** This API is based on Chromium's [`chrome.devtools`](https://developer.chrome.com/docs/extensions/mv2/devtools/) API.
@Rob--W  Indeed - I'll remove it.

2023-12-27 23:20 UTC, rebloor commented
@Rob--W I'm a little unclear about your feedback.

> The Components.utils API is an internal implementation detail of Firefox. Many years ago legacy Firefox add-ons had access to it, but WebExtensions don't. Their content scripts only have access to cloneInto/exportFunction, which exposes the same functionality.

Just background?

> There may be old links on the web pointing to these methods; if that is the concern I'd rather want redirects to the WebExtension-specific documentation.

The concern was, as per the issue: there is no documentation for exportFunction() and cloneInto() on MDN, however they are mentioned on [Share objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) but only with examples but not syntax documentation or links to that documentation for the functions. 

> If you need a place to host the method descriptions, I recommend to put them under Content_scripts/.

Do you mean: 
* Add-ons/WebExtensions/Content_scripts/components/utils/exportFunction
* Add-ons/WebExtensions/Content_scripts/components/utils/cloneInto

Or could we simplify to :

* Add-ons/WebExtensions/Content_scripts/exportFunction
* Add-ons/WebExtensions/Content_scripts/cloneInto

If we aren't following the usual API pattern and as neither the component nor utils page provides much information.

Or under the [Share objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts)?

2023-12-28 04:05 UTC, Rob--W commented
> @Rob--W I'm a little unclear about your feedback.
> 
> > The Components.utils API is an internal implementation detail of Firefox. Many years ago legacy Firefox add-ons had access to it, but WebExtensions don't. Their content scripts only have access to cloneInto/exportFunction, which exposes the same functionality. 
> 
> Just background?

No, not just background information. I am asserting that it does not make sense to add the articles for `Components` and `Components.utils`, because there is no way for extensions to use these today. The MDN articles for these existed in the past for the reasons I mentioned before, but were removed when Firefox-only (internal) APIs were removed from MDN. In case you are curious, this is how the documentation of `Components.utils.exportFunction` looked like in the past:

- 2015 (simply under `/en-US/docs/Components.utils.exportFunction`): https://web.archive.org/web/20150322003611/https://developer.mozilla.org/en-US/docs/Components.utils.exportFunction
- 2018 (page moved to `/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.exportFunction`): https://web.archive.org/web/20180512135500/https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.exportFunction

> The concern was, as per the issue: there is no documentation for exportFunction() and cloneInto() on MDN, however they are mentioned on [Share objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) but only with examples but not syntax documentation or links to that documentation for the functions.
> 
> > If you need a place to host the method descriptions, I recommend to put them under Content_scripts/.
> 
> Do you mean:
> 
>     * Add-ons/WebExtensions/Content_scripts/components/utils/exportFunction
> 
>     * Add-ons/WebExtensions/Content_scripts/components/utils/cloneInto

No.

> Or could we simplify to :
> 
>     * Add-ons/WebExtensions/Content_scripts/exportFunction
> 
>     * Add-ons/WebExtensions/Content_scripts/cloneInto

Yes. That is what I meant.

2023-12-28 18:07 UTC, rebloor commented
Thanks @Rob--W I've rearranged the content and added cross-references. Do you think we need to add the to functions to the navigation e.g.:
- Concepts
  - JavaScript APIs
  -  Content scripts
    - exportFunction()
    - cloneInto()
  - …

(I'm not even sure it's possible, we don't do this with any of the other narrative content.)

If we're not considering these as part of the supported web extension API set, do you think we need browser compatibility data?

2024-04-01 10:49 UTC, Rob--W requested changes
Here is partial feedback, please apply the general issues broadly to the whole PR and then request another review.

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +      - : `Boolean`. Whether the object's functions should be cloned. Default to `false`. Cloned functions have the same semantics as functions exported using [`Components.utils.exportFunction`](/en-
```suggestion
      - : `boolean`. Whether the object's functions should be cloned. Default to `false`. Cloned functions have the same semantics as functions exported using [`exportFunction`](/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Content_scripts/exportFunction). See [Cloning objects that have functions](#Cloning_objects_that_have_functions). {{optional_inline}}
```

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +title: components.utils.cloneInto()
```suggestion
title: cloneInto()
```

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +browser-compat: webextensions.api.components.utils.cloneInto
```suggestion
browser-compat: webextensions.api.ContentScriptGlobalScope.cloneInto
```
`components.utils` is an internal name and should not be exposed because it cannot be used. Here is an alternative suggestion, with a new made up name, ContentScriptGlobalScope, to have a namespace that can be referenced from mdn/content.

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +      - : `boolean`. Whether objects reflected from C++, such as DOM objects, should be cloned. Defaults to `false`. See [Cloning objects that contain DOM elements](#Cloning_objects_that_contain_DOM_
```suggestion
      - : `boolean`. Whether DOM objects should be passed by reference instead of cloned. DOM objects are usually not clonable. Defaults to `false`. See [Cloning objects that contain DOM elements](#Cloning_objects_that_contain_DOM_elements).
```

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +This add-on script creates an object, clones it into the content window and makes it a property of the content window global:
Can you replace all references of "add-on script" with "content script"? The original Components.utils.cloneInto method and its family of functions was documented in a general way because privileged code in add-ons, in general, could use this API anywhere. But in WebExtensions, only content scripts (and userScripts) can use it.

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +contentWindow.addonScriptObject = cloneInto(addonScriptObject, contentWindow);
```suggestion
window.addonScriptObject = cloneInto(addonScriptObject, window);
```

Replace contentWindow with window everywhere in this article.

2024-04-01 10:49 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +contentWindow.foo.addonScriptObject = cloneInto(
```suggestion
// Content script
contentWindow.foo.addonScriptObject = cloneInto(
```

For clarity emphasize in this whole example whether a script is a content script or a page script.

2024-09-20 06:52 UTC, Rob--W approved these changes
Thanks, this looks technically accurate. Could you address the nits and merge it?

2024-09-20 06:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/exportfunction/index.md
> +// ad// privileged scope: for example, a content script
What is `ad//` doing here and in other places below?

2024-09-20 06:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/exportfunction/index.md
> +  options            // object
```suggestion
  options            // optional object
```

2024-09-20 06:52 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/cloneinto/index.md
> +  options            // object
```suggestion
  options            // optional object
```

2024-09-20 16:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/content_scripts/exportfunction/index.md
> +// ad// privileged scope: for example, a content script
No idea, some search/replace error, but a bit of head-scratcher.

2024-09-20 17:07 UTC, merged