init documentation for `cancelAnimationFrame()` and `requestAnimationFrame()` of `DedicatedWorkerGlobalScope` interface
mdn/content pull request #30880
Opened 2023-12-08 19:42 UTC by skyclouds2001

### Description

see https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame and https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame

reference to https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames

using some content from `Window.requestAnimationFrame()` and `Window.cancelAnimationFrame()` and the example from the specification

### Motivation

### Additional details

Relates to #1519 

### Related issues and pull requests

2023-12-09 09:05 UTC, teoli2003 requested changes
I have a few questions here, and I'll need to do a second pass once all is fixed, but this is close to be mergeable.

2023-12-09 09:05 UTC, teoli2003 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +Finally, when necessary, we could send a message of "stop" to the worker to stop the animation:
```suggestion
Finally, if needed, the main thread can send a `"stop"`message to the worker to stop the animation:
```

2023-12-09 09:05 UTC, teoli2003 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +- {{domxref("Window.requestAnimationFrame()")}}
This one is not needed.
```suggestion
```

2023-12-09 09:05 UTC, teoli2003 commented on files/en-us/web/api/dedicatedworkerglobalscope/requestanimationframe/index.md
> +
Most comments from `cancelRequestAnimationFrame` also apply here. I'll make a second pass once they are fixed in both pages.

2023-12-09 09:05 UTC, teoli2003 commented on files/en-us/web/api/window/cancelanimationframe/index.md
> +- {{domxref("DedicatedWorkerGlobalScope.requestAnimationFrame()")}}
```suggestion
```

2023-12-09 09:05 UTC, teoli2003 commented on files/en-us/web/api/window/requestanimationframe/index.md
> +- {{domxref("DedicatedWorkerGlobalScope.cancelAnimationFrame()")}}
```suggestion
```

2023-12-11 10:18 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +  - : Thrown if the method is not supported in current worker.
and this expection is not required to documented in window. and window. , as in window scope, the exception will never throw

2023-12-11 10:22 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +  - : The ID value returned by the call to {{domxref("DedicatedWorkerGlobalScope.requestAnimationFrame()", "requestAnimationFrame()")}} that requested the callback.
yes, the handle must be created in the same dedicated worker

2023-12-11 15:42 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +Calling `cancelAnimationFrame()` method requires that current worker need to support this method, which means that current worker is created by {{domxref("Window", "window")}} or the creator of curre
```suggestion
Calling `cancelAnimationFrame()` method requires that the current worker need to support this method, which means that the current worker is created by {{domxref("Window", "window")}} or by a dedicated worker that also supports this method.
```

2023-12-11 15:42 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/requestanimationframe/index.md
> +Calling `requestAnimationFrame()` method requires that current worker need to support this method, which means that current worker is created by {{domxref("Window", "window")}} or the creator of curr
```suggestion
Calling `requestAnimationFrame()` method requires that the current worker need to support this method, which means that the current worker is created by {{domxref("Window", "window")}} or by a dedicated worker that also supports this method.
```

2023-12-14 07:53 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/cancelanimationframe/index.md
> +Calling `cancelAnimationFrame()` method requires that the current worker need to support this method, which means that the current worker is created by {{domxref("Window", "window")}} or by a dedicat
```suggestion
Calling `cancelAnimationFrame()` method requires that the current worker need to has an associated owner {{domxref("Window", "window")}}, which means that the current worker must be created by {{domxref("Window", "window")}} or by a dedicated worker that also has an associated owner {{domxref("Window", "window")}}.
```

2023-12-14 07:53 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/requestanimationframe/index.md
> +Calling `requestAnimationFrame()` method requires that the current worker need to support this method, which means that the current worker is created by {{domxref("Window", "window")}} or by a dedica
```suggestion
Calling `requestAnimationFrame()` method requires that the current worker need to has an associated owner {{domxref("Window", "window")}}, which means that the current worker must be created by {{domxref("Window", "window")}} or by a dedicated worker that also has an associated owner {{domxref("Window", "window")}}.
```

2023-12-14 12:56 UTC, teoli2003 requested changes
A few last grammar and typo fixes, and this is ready to be merged. Well done!

2023-12-14 13:26 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/requestanimationframe/index.md
> +Calling the `requestAnimationFrame()` method requires that the current worker need to has an associated owner {{domxref("Window", "window")}}, which means that the current worker must be created by {
```suggestion
Calling the `requestAnimationFrame()` method requires the current worker to have an associated owner {{domxref("Window", "window")}}. That means that the current worker must be created by {{domxref("Window", "window")}} or by a dedicated worker that also has an associated owner {{domxref("Window", "window")}}.
```

2023-12-14 13:26 UTC, skyclouds2001 commented on files/en-us/web/api/dedicatedworkerglobalscope/requestanimationframe/index.md
> +{{domxref("DedicatedWorkerGlobalScope.cancelAnimationFrame()", "cancelAnimationFrame()")}} to cancel the refresh callback request, the cancel action must be made in the same worker.
```suggestion
{{domxref("DedicatedWorkerGlobalScope.cancelAnimationFrame()", "cancelAnimationFrame()")}} to cancel the refresh callback request, the cancel action must have been made in the same worker.
```

2023-12-14 14:01 UTC, teoli2003 approved these changes
Thank you!

2023-12-14 14:06 UTC, merged