fix(html): add onerror and onload event info on iframe page
mdn/content pull request #30893
Opened 2023-12-09 15:18 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/12477

iframes have different behavior for `onload` and `onerror` events than other HTML elements. This is because of security reasons: https://bugs.chromium.org/p/chromium/issues/detail?id=365457#c6

Tested this on latest Chrome, Firefox, and Safari browsers. All have the same behavior.

2023-12-11 10:18 UTC, chrisdavidmills requested changes
Thanks for the addition @OnkarRuikar. I've left a few comments for you to consider.

2023-12-11 10:18 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +Using JavaScript, iframes can be used to probe the URL space of the local network's HTTP servers. That is why for the security reason user agents do not invoke [onerror](/en-US/docs/Web/API/HTMLEleme
```suggestion
JavaScript executed inside embedded `<iframe>` content could be used to probe the URL space of the local network's HTTP servers. Therefore, as a security precaution user agents do not fire the [error](/en-US/docs/Web/API/HTMLElement/error_event) event on `<iframe>`s, and the [load](/en-US/docs/Web/API/HTMLElement/load_event) event is always triggered even if the `<iframe>` content fails to load.
```

2023-12-11 10:18 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +Using JavaScript, iframes can be used to probe the URL space of the local network's HTTP servers. That is why for the security reason user agents do not invoke [onerror](/en-US/docs/Web/API/HTMLEleme
I also wonder whether it would be worth expanding this text a bit to explain why these behaviors fix the aforementioned security problem? Just a sentence on each? It feels a bit brief right now.

2023-12-11 13:59 UTC, OnkarRuikar commented on files/en-us/web/html/element/iframe/index.md
> +Using JavaScript, iframes can be used to probe the URL space of the local network's HTTP servers. That is why for the security reason user agents do not invoke [onerror](/en-US/docs/Web/API/HTMLEleme
```suggestion
Using JavaScript `<iframe>`s could be used to probe the URL space of the local network's HTTP servers. Therefore, as a security precaution user agents do not fire the [error](/en-US/docs/Web/API/HTMLElement/error_event) event on `<iframe>`s, and the [load](/en-US/docs/Web/API/HTMLElement/load_event) event is always triggered even if the `<iframe>` content fails to load.
```

2023-12-11 14:18 UTC, chrisdavidmills commented
> > I also wonder whether it would be worth expanding this text a bit to explain why these behaviors fix the aforementioned security problem? Just a sentence on each? It feels a bit brief right now.
> 
> For that we will have to explain how such attack is performed first which I think is off topic. The [spec doesn't shine much light on this though](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#iframe-load-event-steps). If you want I'll try to gather more info about this.

@OnkarRuikar I think it'd be nice to try to find some more details out about this, and perhaps just write a short description. I read this and am left wondering what this kind of attack would look like.

Maybe look into it but don't spent a huge amount of time on it. If you are unable to find out any more details, we can publish it as-is. It is still much mroe useful than having nothing at all.

2023-12-11 14:23 UTC, chrisdavidmills requested changes
@OnkarRuikar one more small language nitpick

2023-12-11 14:23 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +Using JavaScript `<iframe>`s could be used to probe the URL space of the local network's HTTP servers. Therefore, as a security precaution user agents do not fire the [error](/en-US/docs/Web/API/HTML
Better, but I am struggling a bit with "JavaScript `<iframe>`s" - what's a JavaScript iframe? Really, we mean load and error events fired on an iframe, right? Maybe something like "`error` and `load` events fired on `<iframe>`s could be used..." ?

2023-12-16 07:23 UTC, OnkarRuikar commented on files/en-us/web/html/element/iframe/index.md
> +Using JavaScript `<iframe>`s could be used to probe the URL space of the local network's HTTP servers. Therefore, as a security precaution user agents do not fire the [error](/en-US/docs/Web/API/HTML
```suggestion
The `error` and `load` events fired on `<iframe>`s could be used to probe the URL space of the local network's HTTP servers. Therefore, as a security precaution user agents do not fire the [error](/en-US/docs/Web/API/HTMLElement/error_event) event on `<iframe>`s, and the [load](/en-US/docs/Web/API/HTMLElement/load_event) event is always triggered even if the `<iframe>` content fails to load.
```

2023-12-16 07:35 UTC, OnkarRuikar commented
> I think it'd be nice to try to find some more details out about this

As the issue has already been handled, it is hard to find detailed info about the exploit. 
I could only find following links:
- https://bugs.chromium.org/p/chromium/issues/detail?id=365457#c3
- https://bugs.chromium.org/p/chromium/issues/detail?id=899559#c9
- https://bugs.chromium.org/p/chromium/issues/detail?id=1001374#c2

It boils down to network probing and security risks.

2023-12-18 12:23 UTC, chrisdavidmills approved these changes
OK, no worries @OnkarRuikar. Thanks for looking into this. Let's get this merged.

2023-12-18 12:23 UTC, merged