Rewrite Error.p.stack
mdn/content pull request #30908
Opened 2023-12-10 18:45 UTC by Josh-Cena

Fix #30906

2023-12-11 09:43 UTC, chrisdavidmills requested changes
@Josh-Cena thanks for the great work on this! It mostly makes sense; I have left a few suggestions for you to consider.

2023-12-11 09:43 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +> **Note:** The `stack` property is de-facto implemented by most, if not all, JavaScript engines. [The standard committee is looking to standardize this feature too](https://github.com/tc39/proposal-
```suggestion
> **Note:** The `stack` property is de facto implemented by all major JavaScript engines, and [the JavaScript standards committee is looking to standardize it](https://github.com/tc39/proposal-error-stacks). You cannot rely on the precise content of the stack string due to implementation inconsistencies, but you can generally assume it exists and use it for debugging purposes.
```

2023-12-11 09:43 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +Error: Function failled
```suggestion
Error: Function failed
```

2023-12-11 16:25 UTC, sidewayss commented
I just came across a case where Chrome does leaves `stack` undefined: the clipboard. Can't create a fiddle/pen/playground because reproducing it requires setting a breakpoint on the first line of this block. That shifts focus away from the page during the copy operation, causing an error.  Once it breaks, you step line-by-line (F10) a couple of times until the error is caught:
```
navigator.clipboard.writeText(txt)
    .then (()  => /* insert code here */; )
    .catch(err => alert(`Copy failed: ${err.stack ?? err}`));
```
Note the end of the last line where I fall back to `err.toString()` when `err.stack` is undefined. I just added that bit because of this behavior. Firefox does define `stack` here (though it's only one line deep). So would this be a Chrome bug, or simply a side-effect of not having a standard in place?

2023-12-11 16:30 UTC, teoli2003 commented
Note that the Clipboard is a weird beast as, in Webidl, it isn't an interface but a namespace. No surprise something strange is happening with it.

2023-12-11 17:33 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +Stack frames can be things other than explicit function calls, too. For example, event listeners, timeout jobs, and promise handlers all begin their own call chain. Source code within {{jsxref("Globa
It's quite hard to describe, or maybe I don't understand this deeply enough. I am writing a page for execution contexts (maybe in another year? 😛) https://github.com/mdn/content/issues/5006 and I'll talk more about stacks then.

2023-12-11 17:35 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +You can also use the `//# sourceURL` directive to name an eval source. For Firefox, see also the [Debug eval sources](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/debug_eval_
I don't know but I think it is Firefox-specific. After all, devtools are always implementation-inconsistent. I just copied this from the paragraph that was in examples.

2023-12-11 17:36 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +The following script demonstrates the use of `stack` property. It runs in your browser, so you can check how the stack trace looks in your browser.
The key here is that the stack trace is "from your browser", so if you don't use one of the browsers described above, or if you use a different version, you can verify what its stack structure looks like.

2023-12-11 17:42 UTC, Josh-Cena commented
> So would this be a Chrome bug, or simply a side-effect of not having a standard in place?

More likely a bug. But the only way to tell is by sending an issue and getting their reply.

2023-12-11 18:15 UTC, sidewayss commented
Chrome bug for clipboard error: https://bugs.chromium.org/p/chromium/issues/detail?id=1510545

2023-12-12 08:00 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +You can also use the `//# sourceURL` directive to name an eval source. For Firefox, see also the [Debug eval sources](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/debug_eval_
Oh, OK. I've edited my suggested change to suit.

2023-12-12 08:05 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +Stack frames can be things other than explicit function calls, too. For example, event listeners, timeout jobs, and promise handlers all begin their own call chain. Source code within {{jsxref("Globa
Is this any use: https://stackoverflow.com/questions/10057443/explain-the-concept-of-a-stack-frame-in-a-nutshell#10057535 ?

I wasn't thinking that it needed to be much, but it seems a little odd that there is no definition for terms such as these. I guess when you come to write your dedicated execution contexts page, you can link it to the definitions in there. I'll let this pass for now, as the definition of it is implied enough to not seriously impair understanding.

2023-12-12 08:10 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +You can also use the `//# sourceURL` directive to name an eval source. For Firefox, see also the [Debug eval sources](https://firefox-source-docs.mozilla.org/devtools-user/debugger/how_to/debug_eval_
Committed.

2023-12-12 08:11 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/error/stack/index.md
> +The following script demonstrates the use of `stack` property. It runs in your browser, so you can check how the stack trace looks in your browser.
Edit suggestion updated to suit. I'm not quite so sure about this one, so I'll let you check this before committing.

2023-12-12 08:13 UTC, chrisdavidmills approved these changes
OK, updates look good, so I'm setting this to approved. Nice work @Josh-Cena!

There are just a couple more comments from me for you to check out, and a couple of updated suggestions for you to review. After that we can merge.

2023-12-12 08:19 UTC, Josh-Cena commented
LGTM

2023-12-15 09:03 UTC, bsmth commented
Thanks, all! Shall we merge this one?

2023-12-15 09:34 UTC, merged

2023-12-15 09:34 UTC, chrisdavidmills commented
> Thanks, all! Shall we merge this one?

Yussssss ;-)

2024-01-29 17:44 UTC, sidewayss commented
> Chrome bug for clipboard error: https://bugs.chromium.org/p/chromium/issues/detail?id=1510545

fyi - this bug is fixed and heading for release in Chrome 122.  One less gap in the support for Error.prototype.stack.

2024-01-29 19:46 UTC, Josh-Cena commented
Great to know!

2024-02-28 01:06 UTC, sidewayss commented
Just got Chrome 122 and tested it to confirm that it contains the bug fix.