docs(css): Add module landing page for overscroll behavior
mdn/content pull request #30981
Opened 2023-12-13 13:07 UTC by dipikabh

### Description

This PR creates a new module landing page for the overscroll behavior module. It also creates a new glossary page to explain some related relevant terms.

Note that at this moment the module landing page does not include the "in action" section. I hope it can be taken up in a subsequent PR.

Spec: https://drafts.csswg.org/css-overscroll/

### Motivation

Scrolling is a focus area in [Interop 2023](https://wpt.fyi/interop-2023). Overscroll behavior is one of the features covered in scrolling. 

### Related issues and pull requests

This work is being tracked through the doc issue https://github.com/mdn/mdn/issues/416.

2023-12-14 05:12 UTC, dipikabh commented
I'm putting this PR in draft mode as I will be away for a bit and won't be able to attend to any review comments during this time. I plan to open it up for review once I'm back.

2024-01-05 15:49 UTC, dipikabh commented
Hi @estelle, I'd appreciate if you can review this work when you get the chance. Thanks!

2024-01-12 06:08 UTC, estelle requested changes
My suggestion for the longer module page intro is a really rough draft. I did it as a suggestion but think of it as bullet points ;)

2024-01-12 06:08 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
It would be good to describe what occurs by default, and what experience the features in this module enable. Readers may not fully understand these terms: scroll containe, scroll position, scroll boundary, embedded , scrollable areas, or trigger scrolling (hopefully they understand parent container.

Here's a very rough draft of a possible outline

```suggestion
The **CSS overscroll behavior** module provides properties to enable or prevent scroll chaining and overscroll.

If you have ever commented on a blog, you may have noticed if your comment is longer than the few lines provided by the {{htmlement("textarea")}}, scrolling past the end of the text area makes the whole blog scroll. Reaching the end of a scroll, known as a scroll boundary, may cause other content or the full page to scroll. This continuous scrolling experience is called scroll chaining.

If you've ever quickly scrolled through a website's terms and conditions to enable a checkbox, reaching the end of the content may not force the page scroll (or bounce if you're reading on your phone). You can control this overscroll behavior and prevent scroll chaining is preventable. This module defines the overscroll behavior, enabling you to define what should happen when the user scrolls beyond the boundaries of a scollable element.

If the contents of an element are larger than its container, and {{cssxref("overflow")}} is set to or defaults to allow scrolling as with `<textarea>`, when the user continues scrolling past the end of that elements scrollable area, the parent element or the underlying page will start scrolling. 

## Overscroll behavior in action

To enable and disable overscroll behavior in the box below, click the checkbox 'Toggle overscroll' then scroll the inner box. When overscroll is contained, the parent box will not start scrolling when your scroll to the edge of the inner box. When it isn't contained, the outer box will start scrolling.
```
Then include a prettified version of the interactive example at the top of  https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

2024-01-16 22:35 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - [Local and non-local boundary defaults](/en-US/docs/Glossary/Scroll_chaining#local_and_non-local_boundary_defaults)
I've gone with your second suggestion because I wanted to somehow convey that "scrollport' is on the same page that describes scroll containers.

2024-01-16 22:35 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +    - [Scrollport](/en-US/docs/Glossary/Scroll_container#scrollport)
I've gone with your second suggestion because I wanted to somehow convey that "scrollport' is on the same page that describes scroll containers.

2024-01-17 22:35 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +**Scroll chaining** refers to the behavior observed when scrolling within a scrollable element, such as a `<div>` or `<textarea>`, triggers scrolling in its parent element or the underlying page. Thi
Makes sense. Updated those last bits to:

> ....when the [scrollport](/en-US/docs/Glossary/Scroll_container#scrollport) boundary (top, bottom, left or right) of the scrollable element is reached. This behavior creates a continuous scrolling experience, both vertically and horizontally.

2024-01-17 22:38 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +You can use the shorthand {{CSSxRef("overscroll-behavior")}} CSS property to customize or disable the browser's default behavior.
Done, added both the property and the module to "See also"

2024-01-17 23:06 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +## Related terms
I did not find the same paragraph as is on those pages, but I've added a link to the glossary scroll chaining wherever the term appeared on those pages as well as in overscroll-behavior-y

2024-01-17 23:07 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +## Related terms
I've created a new glossary page for scroll boundary and moved the content from scroll chaining over to scroll boundary

2024-01-17 23:28 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - [Local and non-local boundary defaults](/en-US/docs/Glossary/Scroll_chaining#local_and_non-local_boundary_defaults)
Added link to the new scroll boundary glossary page.

While I can remove links to the terms "Boundary default action" and "Local and non-local boundary defaults" from here, I think we should still have them around in the glossary page because they are terms defined in this spec: https://drafts.csswg.org/css-overscroll/#index-defined-here

2024-01-17 23:34 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +## Related terms
> the boundary default terms don't necessarily need to be defined in the glossary, though a guide would be good. 

The way they are written now, I think it would be best to keep them here in the glossary in the new scroll boundary glossary page. And then we can link to these terms when we have guides. WDYT?

2024-01-17 23:50 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +- [CSS building blocks: Overflowing content](/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content)
Thanks. I added the chrome blog link to "See also".
It is already linked in the "See also" on overscroll-behavior property page (https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior#see_also)

2024-01-18 05:45 UTC, estelle requested changes
more suggestions

2024-01-18 05:45 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
Not sure if you saw the above....

2024-01-18 05:45 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +- [Take control of your scroll - customizing pull-to-refresh and overflow effects](https://developer.chrome.com/blog/overscroll-behavior) on developer.chrome.com (2017)
I meant to add the guide under guides. If it's already linked from an internal page, we don't need to link here. We need to write a guide 😐

2024-01-18 05:45 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - {{CSSxref("position")}} property
```suggestion
- [`scrollbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/scrollbar_role) ARIA role
- [Containing block](/en-US/docs/Web/CSS/Containing_block) concept

- [CSS overflow](/en-US/docs/Web/CSS/CSS_overflow) module:

  - {{cssxref("overflow")}} shorthand property
     - {{Cssxref("overflow-x")}}
     - {{Cssxref("overflow-y")}}
     - {{CSSxRef("overflow-block")}}
     - {{CSSxRef("overflow-inline")}}
  - {{CSSxRef("overflow-clip-margin")}} property
  - {{CSSxRef("scroll-behavior")}} property
  - {{CSSxRef("text-overflow")}} property
  - {{Glossary("Scroll_container", "Scroll container")}} and [scrollport](/en-US/docs/Glossary/Scroll_container#scrollport) glossary terms

- [CSS scroll snap](/en-US/docs/Web/CSS/CSS_scroll_snap) module:

  - {{cssxref("scroll-padding")}} shorthand property
  - {{cssxref("scroll-snap-type")}} property
  - {{cssxref("scroll-margin")}} shorthand property
  - {{cssxref("scroll-snap-stop")}} property
  - {{cssxref("scroll-snap-align")}} property

- [CSSOM view](/en-US/docs/Web/CSS/CSSOM_view) module:

  - {{domxref("Element.getBoundingClientRect()")}} method
  - {{domxref("Element.scroll()")}} method
  - {{domxref("Element.scrollBy()")}} method
  - {{domxref("Element.scrollIntoView()")}} method
  - {{domxref("Element.scrollTo()")}} method
  - {{domxref("Document.scroll_event", "scroll")}} Document event
```

2024-01-18 05:45 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - {{CSSxref("position")}} property
The idea is to include features that someone interested in this module may find relevant, not just to cover what is in the specification. We also don't need to include all therms in the specification; otherwise `<color>` and `<length>` would likely be on every module page. We want to surface stuff that is important to web developers over browser devs. (The spec is geared in the opposite: what is important to browser (rather than "web") developers as the focus)

2024-01-18 05:46 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - {{CSSxref("position")}} property
the scroll snap is in that weird order b/c i put parent properties first then child properties. 

That said, this suggestion needs work, but hoping it provides a good start.

2024-01-18 17:42 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +## Related concepts
For the "Related concepts" section, I went with the guidance of ["Terms defined by reference"](https://drafts.csswg.org/css-overscroll/#index-defined-elsewhere) section from the spec. Because for the sake of the module landing page template guideline, we should be able to say what the source or inspiration for "Related concepts" section is. This makes it easier for other authors to determine objectively what to add here.

Even in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animations#related_concepts, I think it might be nice to indicate what modules/specs the listed concepts/features are part of. This was my attempt to try to do that. 🙂 And by grouping them module-wise, I was trying to avoid repeating the module name for each.

What do you think about the following format. They're listed here in the order of concepts, properties, methods, and glossary terms. You can see the preview in this commit https://github.com/mdn/content/pull/30981/commits/59808127a07b5f8524f6e19ff30483acecc60530:
```
## Related concepts

- Containing block concept (CSS display module)
- overflow CSS property (CSS overflow module)
- position CSS property (CSS positioned layout module)
- getBoundingClientRect method (CSSOM view module)
- Scroll container and scrollport glossary terms (CSS overflow module)
```

> though i would also include box model and box-sizing (module page for this doesn't seem to exist) and possible CSS_logical_properties_and_values (though not sure that's necessary)

👍
I can add these to "See also"

2024-01-18 17:44 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
That's because I wasn't done addressing all of your review comments 😄. I left adding fixes mid-way last night with plans to resume with addressing the two remaining comments

2024-01-18 18:25 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
- For the intro para here, I think for the module page, we can let it be a more expanded version because this won't show up in other tools like property descriptions. I would prefer to not have a new, unexplained term (scroll chaining) in the intro para or we would need to link it to its glossary page. By saying "where embedded scrollable areas should not trigger scrolling of the parent container", we're essentially referring to "scroll chaining" without mentioning the term. WDYT?

2024-01-18 18:29 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
I've included the next three paragraphs you wrote (thank you!!), in slightly edited and reorganized way though. LMK what you think. I hope I haven't introduced any technical inaccuracy.

> When commenting on a blog, you might notice that if your comment exceeds the length of the provided {{htmlement("textarea")}}, scrolling beyond the end of the text area causes the entire blog to scroll. This is because reaching the end of a scrollable area, known as the scroll boundary, can lead to scrolling other content or the entire page. This continuous scrolling experience is called {{Glossary("Scroll_chaining", "scroll chaining")}}.

> In situations where the contents of an element are larger than its container, and {{cssxref("overflow")}} allows or defaults to scrolling (like in `<textarea>`), continued scrolling past the element's scrollable area will initiate scrolling in the parent element or the underlying page.

> Conversely, scrolling through a website's terms and conditions and reaching the end of the content to enable a checkbox, may not force the page to scroll or bounce (as on a phone). This example shows that you can control overscroll behavior and prevent scroll chaining.

> This module defines the overscroll behavior, enabling you to specify the actions when a user scrolls beyond the boundaries of a scrollable element.

2024-01-18 18:32 UTC, dipikabh commented on files/en-us/glossary/scroll_boundary/index.md
> +A **scroll boundary** is the point at which a scrollable element cannot be scrolled any further in a particular direction, either at the top or bottom (or left/right for horizontal scrolling). This t
Nice, thanks! Done

2024-01-18 18:34 UTC, dipikabh commented on files/en-us/glossary/scroll_boundary/index.md
> +When the content of a {{Glossary("Scroll_container", "scroll container")}} does not exceed the container size in the scrolling direction, the container is considered to be at its scroll boundary at a
Added

2024-01-18 18:39 UTC, dipikabh commented on files/en-us/glossary/scroll_boundary/index.md
> +This refers to a browser's default behavior when the scroll boundary of the scrollport is reached. This can lead to a visual effect such as a bounce or a functional action like pull-to-refresh on mob
Thanks for clarifying that distinction!

2024-01-18 19:03 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +- [Take control of your scroll - customizing pull-to-refresh and overflow effects](https://developer.chrome.com/blog/overscroll-behavior) on developer.chrome.com (2017)
IMO we should list MDN guides in the Guides section, that's why I added this link in "See also" instead ([my comment](url)).
I don't think it hurts to keep it in the "See also" here as well, at least until we have our own guide.

2024-01-18 19:14 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +  - {{CSSxref("position")}} property
Uh oh, I just redid this to undo my previous format based on your earlier feedback - see my comment https://github.com/mdn/content/pull/30981#discussion_r1457788310. I wasn't done addressing your comments from last week.

> The idea is to include features that someone interested in this module may find relevant, not just to cover what is in the specification. We also don't need to include all therms in the specification; otherwise <color> and <length> would likely be on every module page. We want to surface stuff that is important to web developers over browser devs. (The spec is geared in the opposite: what is important to browser (rather than "web") developers as the focus)

I see what you're saying but it also makes the process of updating this section very subjective.

Some of the additional and relevant concepts and properties can be moved to "See also", for example the `scrollbar` ARIA role in your list here.

2024-01-18 19:25 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module properties enable you to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularl
Like I mentioned in the PR description, I'd like to skip the "Overscroll behavior in action" section in this PR and attempt it in a follow up PR.

2024-01-18 19:32 UTC, dipikabh commented
@estelle Thanks for the review and your valuable inputs! I've now incorporated your feedback from both last week and today. I've left some comments unresolved so you can check if the fixes/responses adequately answer your feedback.

- For the "Related concepts" section, please see my [first](https://github.com/mdn/content/pull/30981#discussion_r1457788310) and [second](https://github.com/mdn/content/pull/30981#discussion_r1457878946) comment. LMK what you think.
- I've slightly edited the intro paras you added in the module landing page. I hope [the revised version](https://github.com/mdn/content/pull/30981#discussion_r1457835648) is okay.

2024-01-18 23:31 UTC, estelle reviewed
Two small edits other than the related concepts. With some specs, the "by reference" makes sense, such as with https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_syntax. Other specs, the concepts are very related, but not necessarily mentioned in the spec. Related concepts is where we achieve the goal of "surfacing content" (the goal from the 2023 London mtg). All the scroll modules are related; though not all of all of the features introduced,

2024-01-18 23:31 UTC, estelle commented on files/en-us/glossary/scroll_chaining/index.md
> +When a user scrolls within a scrollable element such as a `<div>` or `<textarea>` and the [scrollport](/en-US/docs/Glossary/Scroll_container#scrollport) boundary (top, bottom, left or right) of the s
```suggestion
When a user scrolls within a scrollable element such as a `<div>` or `<textarea>` and the [scrollport](/en-US/docs/Glossary/Scroll_container#scrollport) boundary (top, bottom, left or right) of the scrollable element is reached, there may be a "chained effect" in which the scroll action is seamlessly propagated to the parent element. This behavior creates a continuous scrolling experience, both vertically and horizontally.
```
if it's now controllable, it will no longer always be happening

2024-01-18 23:31 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module provides properties to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularly
```suggestion
The **CSS overscroll behavior** module provides properties to control the behavior of a {{glossary("scroll container")}} when its scroll position reaches the {{glossary("scroll boundary")}}. Controlling this aspect is particularly useful in scenarios where embedded scrollable areas should not trigger scrolling of the parent container.
```

2024-01-18 23:31 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module provides properties to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularly
or maybe link in line 12 instead (or both)

2024-01-18 23:31 UTC, estelle commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +## Related concepts
The reason a term is in any of the "Terms defined by reference" sections of a spec is not because they are necessarily related, but because they were mentioned, often just in passing as an example.

2024-01-19 03:53 UTC, dipikabh commented on files/en-us/glossary/scroll_chaining/index.md
> +When a user scrolls within a scrollable element such as a `<div>` or `<textarea>` and the [scrollport](/en-US/docs/Glossary/Scroll_container#scrollport) boundary (top, bottom, left or right) of the s
Makes sense! Fixed as suggested

2024-01-19 03:58 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +The **CSS overscroll behavior** module provides properties to control the behavior of a scroll container when its scroll position reaches the scroll boundary. Controlling this aspect is particularly
Thanks! I've linked both instances of scroll boundary

2024-01-19 04:22 UTC, dipikabh commented on files/en-us/web/css/css_overscroll_behavior/index.md
> +## Related concepts
Got it!

2024-01-19 04:28 UTC, dipikabh commented
Thanks @estelle for taking a look again. I've fixed the last two edit suggestions. I've also updated the "Related concepts" section as per your suggestion in [this comment](https://github.com/mdn/content/pull/30981#discussion_r1456927050).

2024-01-19 20:14 UTC, estelle approved these changes
w00t! 🎉

2024-01-19 20:14 UTC, merged