proxy.settings-passthrough guidance update
mdn/content pull request #31046
Opened 2023-12-15 18:05 UTC by rebloor

### Description

Add guidance as to the values and default settings for proxy.settings.passthrough.

### Motivation

Guidance was missing, so excepted values may not have been clear.

### Related issues and pull requests

Fixes #29680

2023-12-27 15:27 UTC, Rob--W requested changes

2023-12-27 15:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    - `IP_LITERAL[:PORT]`, but not with scheme, e.g., `SCHEME://]IP_LITERAL[:PORT]`
```suggestion
    - `HOST_NAME[:PORT]`, for example: `example.com` or `example.com:1234`
    - `IP_LITERAL[:PORT]`
```

Do not mention schemes, let alone match patterns. These are not relevant.

2023-12-27 15:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts`localhost` and `127.0.0.1` are never proxied.
```suggestion
    Hosts `localhost` and `127.0.0.1` are never proxied.
```

2023-12-27 15:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    You can use IPv6 addresses.
```suggestion
    You can use IPv6 addresses, for example `[::123]`
```

Added example to clarify that brackets have to be used to format it.

2023-12-30 17:14 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    You can use IPv6 addresses.
```suggestion
    You can use IPv6 addresses. For example, `[::123]`.
```

2024-03-28 22:47 UTC, dotproto requested changes
There are a couple of polish changes, but I think we're nearly there.

2024-03-28 22:47 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +> **Note:** Changing proxy settings requires private browsing window access because proxy settings affect private and non-private windows. Whether an extension can access private browsing windows is
Typo fix.

```suggestion
> **Note:** Changing proxy settings requires private browsing window access because proxy settings affect private and non-private windows. Whether an extension can access private browsing windows is under user control. See [Extensions in Private Browsing](https://support.mozilla.org/en-US/kb/extensions-private-browsing) for details. Your extension can check whether it has access to private browsing windows using {{WebExtAPIRef("extension.isAllowedIncognitoAccess")}}. If your extension doesn't have private window permission, calls to `proxy.settings.set()` throw an exception.
```

2024-03-28 22:47 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts `localhost` and `127.0.0.1` are never proxied.
The Firefox pref "[network.proxy.allow_hijacking_localhost](https://searchfox.org/mozilla-central/rev/28cc363411d2029aed04c969c8f98785cae110db/modules/libpref/init/StaticPrefList.yaml#11804-11808)" can be used to change this behavior. Are prefs typically considered when making statements like this?

2024-03-28 22:47 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts `localhost` and `127.0.0.1` are never proxied.
We might want to include the IPv6 loopback address here: `[::1]`. This addresses is included in the [relevant test suite](https://searchfox.org/mozilla-central/rev/28cc363411d2029aed04c969c8f98785cae110db/netwerk/test/gtest/TestProtocolProxyService.cpp#31).

2024-03-28 22:56 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts `localhost` and `127.0.0.1` are never proxied.
"typically" I'd say no. As an extension cannot programmatically change the preference I don't think it's relevant.

2024-03-28 22:56 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts `localhost` and `127.0.0.1` are never proxied.
```suggestion
    Hosts `localhost`, `127.0.0.1`, and `[::1]` are never proxied.
```

2024-03-28 22:56 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/proxy/settings/index.md
> +    Hosts `localhost` and `127.0.0.1` are never proxied.
Done

2024-03-28 23:23 UTC, dotproto approved these changes
LGTM

2024-04-01 10:11 UTC, Rob--W approved these changes

2024-04-02 09:22 UTC, merged