Add WASM tail calls to Fx 121 release notes
mdn/content pull request #31043
Opened 2023-12-15 17:23 UTC by pepelsbey

### Description

Add WASM tail calls to Fx 121 release notes. 

### Related issues and pull requests

https://github.com/mdn/content/issues/30333

2023-12-15 17:36 UTC, zfox23 requested changes
Thanks! Curious if you could clarify one thing... If there's no language you can think of for this, that's OK too.

2023-12-15 17:36 UTC, zfox23 commented on files/en-us/mozilla/firefox/releases/121/index.md
> +- WebAssembly now supports tail call optimization via new `return_call` and `return_call_indirect` alternatives to the [`call`](/en-US/docs/WebAssembly/Reference/Control_flow/call) instruction. This
In just a couple of extra words, is there a way for you to further explain what you mean by "enhances compatibility with programming languages"? I don't quite understand that point.

2023-12-18 09:46 UTC, pepelsbey commented on files/en-us/mozilla/firefox/releases/121/index.md
> +- WebAssembly now supports tail call optimization via new `return_call` and `return_call_indirect` alternatives to the [`call`](/en-US/docs/WebAssembly/Reference/Control_flow/call) instruction. This
> and enhances compatibility with programming languages **that use tail calls**

I added a small note that hopefully makes it a bit clearer. I didn’t want to go too deep into details explaining how the whole WASM thing works.

2023-12-18 13:44 UTC, zfox23 approved these changes

2023-12-18 13:44 UTC, zfox23 commented
ty :)

2023-12-18 13:44 UTC, merged