Update index.md
mdn/content pull request #31081
Opened 2023-12-17 09:55 UTC by dv3lah

Grid lines are created by default even when we do not set the columns or rows explicitly. Therefore, it is more accurate to avoid stating that the grid lines are created when we use explicit grid.

2023-12-18 16:30 UTC, zfox23 requested changes
Thanks for your contribution, @dv3lah! I don't quite understand yet what your change means, and part of that comes from my lack of experience using Grid. I think there's something here worth clarifying that may appear as you help me understand your change 🙂

The current text reads:
> Grid lines are created when you define [tracks](https://pr31081.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Grid_Tracks) in the explicit grid using [CSS Grid Layout](https://pr31081.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_grid_layout).

and your addition reads:

> Grid lines are created when we using CSS Grid layout.

I'm going to write an improvement below based on my current understanding of this feature that I think would offer additional clarity on this page. Please correct what I have wrong or change it to suit your preferences:

> Grid lines are unstyled elements that exist at the borders of a CSS grid and between grid cells. Grid lines are created anytime you use a CSS Grid Layout whether or not you define tracks in an explicit grid.

What do you think?

2023-12-18 19:10 UTC, dv3lah commented
Hey, thank you! I believe it would be more appropriate to phrase it in the following manner:

"Grid lines are created anytime you use a CSS Grid Layout. The grid lines can be visualized using the grid inspector tool found within the browser developer tools."

Please feel free to edit the paragraph from a grammatical perspective.

2023-12-18 19:19 UTC, zfox23 commented
> Hey, thank you! I believe it would be more appropriate to phrase it in the following manner:
> 
> "Grid lines are created anytime you use a CSS Grid Layout. The grid lines can be visualized using the grid inspector tool found within the browser developer tools."
> 
> Please feel free to edit the paragraph from a grammatical perspective.

Hmm 🤔  This glossary definition doesn't help me understand what the grid lines actually _are_ (i.e. where they exist within the grid), only when they are created and an introduction to how they can be visualized. Even as an experienced web developer, it took me a while to figure out where that tool was in devtools - so if you think it's important to include how someone can visualize the lines, I think we'd need to be more specific about where to find that information in a maintainable way.

How do you think we can meet in the middle between the definition we each proposed individually?

2023-12-18 20:16 UTC, dv3lah commented
I understand. If you believe it would be beneficial, we can consider providing instructions to users on how to visualize grid lines using the grid inspector tool. This tool is located next to the grid container in the developer tools, accessible when inspecting the grid container element. However, it is important to note that the design of grid lines can vary across different browsers. 

Therefore, to ensure accuracy, it may be best to stick with the statement "Grid lines are created anytime you use a CSS Grid Layout" for now, as this is a correct statement. 

The reason for proposing this change is to address the current inaccuracy in the documentation, which currently gives the impression that grid lines only appear when using explicit grid.

2023-12-18 20:36 UTC, zfox23 commented
That sounds good to me - please update the language in the markdown and I'll re-review afterward :)

2023-12-19 06:06 UTC, dv3lah commented
How can I do that?

2023-12-19 06:12 UTC, teoli2003 commented
Hi!

I assume you are using the GitHub UI. In that case, click on the _Edit_ menu entry to edit your proposal further:

![Capture d’écran 2023-12-19 à 07 09 39](https://github.com/mdn/content/assets/1466293/60654d35-98b0-4290-a0c3-af72401f9ef9)

Once done, you can re-request a review:
![Capture d’écran 2023-12-19 à 07 11 54](https://github.com/mdn/content/assets/1466293/1e675d12-385a-48c9-af73-3ab98b8d145a)

2023-12-19 09:47 UTC, dv3lah commented
Thank you, done.

2023-12-19 17:53 UTC, zfox23 approved these changes
thanks :)

2023-12-19 17:53 UTC, merged