feat(bot): auto update links of moved files
mdn/content pull request #31091
Opened 2023-12-18 03:33 UTC by OnkarRuikar

Every night the bot will create a PR to update all the links of moved files.

2023-12-18 04:51 UTC, Josh-Cena commented
Can this be part of the Yari CLI instead? It is my opinion that things that can be fixed locally should be fixed locally instead of waiting for another cleanup PR. Again PRs and commits are not zero-cost. We have formatting/linting daily fix because not everyone authors content locally, but everyone is and should be using the `move` CLI to move files.

2023-12-18 14:31 UTC, OnkarRuikar commented
> Can this be part of the Yari CLI instead? It is my opinion that things that can be fixed locally should be fixed locally, instead of waiting for another cleanup PR. Again, PRs and commits are not zero-cost. We have formatting/linting daily fixes, because not everyone authors content locally, but everyone is and should be using the `move` CLI to move files.

- I did submit a yari PR 9 months ago which does exactly what you are saying: https://github.com/mdn/yari/pull/8493 .
Multiple review & merge requests were made. Multiple rebases and conflict resolutions also happened. The PRs came up in the last community meeting as well. :rage: In OWD meeting last week we decided to have the implementation as an auto cleanup bot on content side.
If you could get the yari PR merged then it would be great. Meanwhile there is no harm in keeping this.

2023-12-18 16:36 UTC, Josh-Cena commented
Ugh, I keep forgetting how painful it is to get things merged in Yari. I feel you. No objection from me, then.

2023-12-19 12:02 UTC, OnkarRuikar commented
@teoli2003 ping

2023-12-19 13:14 UTC, teoli2003 requested changes
One nit.

I think we should then try this, keeping in mind that once Yari's PR will be merged we will undo this. (But this is an annoying problem, so worth solving it in the meantime)

2023-12-19 13:14 UTC, teoli2003 commented on scripts/update-moved-file-links.js
> +  updatedNo = 0;
Nit:

I prefer this syntax:
```suggestion
let totalNo = 0;
let updatedNo = 0;
```

2023-12-20 06:04 UTC, teoli2003 approved these changes
We should go ahead with this:
- this can't break mdn/content (and the Firefox release date was yesterday, so it can't be a problem there)
- it is easy to revert in case of problem (the modify files aren't modified every day)
- it is a band-aid

Let's merge this.

2023-12-20 06:04 UTC, merged