DO NOT MERGE: MDN React Tutorials #6: Accessibility
mdn/content pull request #31139
Opened 2023-12-19 05:42 UTC by mxmason

## Description

Following #31093, as part of mdn/mdn#474, this PR makes some modifications to the sixth page in our "Getting started with React" tutorial.

---

Do not merge this until #31093 has been merged and you have updated this PR with mdn main and checked for breakages.

2023-12-19 06:21 UTC, mxmason reviewed
A two-for-one special to close us out, @chrisdavidmills! Mostly some little line edits, but I called out some notable stuff.

2023-12-19 06:21 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +You can read more about this and other approaches to styling React components in the Smashing Magazine article, ["Styling Components In React"](https://www.smashingmagazine.com/2020/05/styling-compon
🔍 I replaced this reference since we're trying to get away from `create-react-app`

2023-12-19 06:21 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +
🔍 This is new! Reducers are a handy way to clean up state logic and I thought they'd be worth a mention

2023-12-19 06:21 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
> +Although this tutorial doesn't mention them, it is possible to build React components using [JavaScript classes](/en-US/docs/Web/JavaScript/Reference/Classes) – these are called class components. Unt
🔍 This line is just a whitespace cleanup

2023-12-19 06:21 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
>  ## Routing
Reach Router has now been absorbed into React Router, and React Router tragically does not preserve some of Reach Router's old accessibility considerations. Because offering a real "solution" to client-side routing would is its own topic, I linked out to some of Marcy Sutton's writing for now.

2023-12-19 15:24 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +If you click the "All", "Active", or "Completed" filter buttons with your mouse, you _won't_ see a visible focus indicator. Your code isn't broken! Our CSS uses the [`:focus-visible`](/en-US/docs/Web
@mxmason I think this info is useful, and it is also a good place for it. However, I do have a couple of issues to raise, which I think could warrant a bit of attention:

- `:focus-visible` doesn't allow the browser to decide when to show a visual focus indicator to the users — the browser does that anyway, using a set of internal heuristics. If you remove your `:focus-visible` style from the stylesheet you'll still get a focus indicator, it'll just be the browser default. What it does do is allow you to customize the focus indicator styling, without having to specify that you want it to appear on hover or some other state.
- It might be nice to say a little bit more about why the focus indicator doesn't appear when you click buttons, but it does when you focus an input field. Probably something along the lines of it not being needed on a button for mouse users as you just click and forget and its position isn't important like it is for a keyboard user. However, with an input it is important to help the user remember that they're on an input and still have a value to input...?

2023-12-19 16:22 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +If you click the "All", "Active", or "Completed" filter buttons with your mouse, you _won't_ see a visible focus indicator. Your code isn't broken! Our CSS uses the [`:focus-visible`](/en-US/docs/Web
@chrisdavidmills Okay, fair enough. The reason I said that the browser decides, though, is that that's what `:focus-visible` is – a set of heuristics internal to the user agent. You see the same behavior without our CSS because user agents use `:focus-visible` as a default now, instead of our old friend `:focus`

As for explaining why, I agree with your reasoning as to why browser devs did what they did, but there's no real documentation to prove that, so I shied away from writing something that could be seen as speculative. Right now, :focus-visible is really just "this is a browser suggestion"

2023-12-19 17:03 UTC, chrisdavidmills requested changes
Great work as always @mxmason! I've worked through the whole tutorial and all is working well. I've got some comments for you here, but nothing too major.

2023-12-19 17:03 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
>  `create-react-app` provides some tools for testing your application out of the box — you may have deleted the relevant files earlier in the tutorial. The documentation for `create-react-app` [covers
You've still got `create-react-app` references here.

2023-12-19 17:07 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +If you click the "All", "Active", or "Completed" filter buttons with your mouse, you _won't_ see a visible focus indicator. Your code isn't broken! Our CSS uses the [`:focus-visible`](/en-US/docs/Web
You're not wrong on any of this, but the text does talk specifically about the `:focus-visible` pseudo class, and not the wider concept. I think you can leave further explanation of the behavior itself (2nd bullet), but I think you should update the text a little to make sure it isn't perceived as inaccurate. Maybe a combination of what we both said - say that in general browser heuristics control focus visibility, and then go on to say that it's visual output can be customized using the `:focus-visible` pseudo?

2023-12-19 17:22 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Paste the following code near the top of `Todo.jsx`, above your `Todo()` function.
Yep, I argued with myself about writing this out because it's a little complicated, but it's probably worthwhile. Will do.

2023-12-19 17:24 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_resources/index.md
>  `create-react-app` provides some tools for testing your application out of the box — you may have deleted the relevant files earlier in the tutorial. The documentation for `create-react-app` [covers
Oops, don't look at me 🙈

2023-12-20 05:32 UTC, mxmason reviewed
Back to you, @chrisdavidmills!

2023-12-20 05:32 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
>  ### Aside: a note on our focus indicator
🔍  I added some heft to this section.

2023-12-20 05:32 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Up to this point, we've been writing JSX and letting React build the DOM from them. Most of the time, we don't need to target specific elements in the DOM because we can use React's state and props t
🔍 This section now moves into the `useEffect` section that follows a bit more nicely. By taking a bit more time to explain how `useRef` works,  my hope is that onboarding to `useEffect` will be less steep. I also added a specific explanation for `usePrevious` farther on.

2023-12-20 06:07 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
>  ### Using `useEffect()` to control our heading focus
Yeah, fair call; I could not tell you _why_ I wrote it the way I did before. Changed per your suggestion.

2023-12-20 10:09 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +If you click the "All", "Active", or "Completed" filter buttons with your mouse, you _won't_ see a visible focus indicator. Your code isn't broken! Our CSS uses the [`:focus-visible`](/en-US/docs/Web
Much better. I gave the section a bit of editorial tweaking. Have a look and let me know if you are OK with it.

2023-12-20 10:43 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Paste the following code near the top of `Todo.jsx`, above your `Todo()` function.
Cool, this new text is perfect.

2023-12-20 10:55 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
>  ### Aside: a note on our focus indicator
Cool, nice one. Just check my edits to see if you are OK with them.

2023-12-20 11:34 UTC, chrisdavidmills requested changes
@mxmason lovely work! Just a few more changes/suggestions for you to consider. Very close now!

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Doing this will populate our `editFieldRef` and `editButtonRef` with references to the DOM elements they're attached to, but _only_ after React has rendered the component. Test that out for yourself:
```suggestion
Doing this will populate our `editFieldRef` and `editButtonRef` with references to the DOM elements they're attached to, but _only_ after React has rendered the component. Test that out for yourself: add the following line somewhere in the body of your `Todo()` function, below where `editButtonRef` is initialized:
```

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +[`useEffect()`](https://react.dev/reference/react/useEffect) is so named because it runs any side-effects that we'd like to add to the render process, and which we can't run inside the main function
```suggestion
[`useEffect()`](https://react.dev/reference/react/useEffect) is so named because it runs any side-effects that we'd like to add to the render process, which can't be run inside the main function body. `useEffect()` runs right after a component renders, meaning the DOM elements we referenced in the previous section will be available for us to use.
```

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +`useEffect()` takes a function as an argument; this function is executed _after_ the component renders. To illustrate this, put the following `useEffect()` call just above the `return` statement in t
```suggestion
`useEffect()` takes a function as an argument; this function is executed _after_ the component renders. To demonstrate this, put the following `useEffect()` call just above the `return` statement in the body of `Todo()`, and pass a function into it that logs the words "side effect" to your console:
```

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +`useEffect()` takes a function as an argument; this function is executed _after_ the component renders. To illustrate this, put the following `useEffect()` call just above the `return` statement in t
Just so we aren't using "illustrate" twice in quick succession.

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Our `useEffect()` hook is behaving exactly as we designed it: it runs as soon as the component renders, sees that `isEditing` is `false`, and focuses the "Edit" button. Because there are three instan
```suggestion
Our `useEffect()` hook is behaving exactly as we designed it: it runs as soon as the component renders, sees that `isEditing` is `false`, and focuses the "Edit" button. There are three instances of `<Todo />`, and focus is given to the "Edit" button of the one that renders last.
```

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Our `useEffect()` hook is behaving exactly as we designed it: it runs as soon as the component renders, sees that `isEditing` is `false`, and focuses the "Edit" button. Because there are three instan
Just because "renders moves focus" is a bit of a mouthful. I found myself tripping over it when reading.

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +`usePrevious()` is a _custom hook_ that tracks a value across renders. It uses the `useRef()` hook to create a ref, and then updates the `useEffect()` hook. This means the `current` property of the r
```suggestion
`usePrevious()` is a _custom hook_ that tracks a value across renders. It uses the `useRef()` hook to create a ref, and then uses the `useEffect()` hook to store the value of `value` in the ref, as it is after the calling component has rendered. This means the `current` property of the ref will always contain the previous value of the `value` argument. You might think of it as intentionally being one value "behind" – hence the name `usePrevious()`.
```

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +`usePrevious()` is a _custom hook_ that tracks a value across renders. It uses the `useRef()` hook to create a ref, and then updates the `useEffect()` hook. This means the `current` property of the r
Does this work? I thought this could use a little more clarity.

2023-12-20 11:34 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Now we can define a `wasEditing` constant beneath the hooks at the top of `Todo()`. We want this constant to track the previous value of `isEditing`, so we call `usePrevious` with `isEditing` as an a
```suggestion
Now we can define a `wasEditing` constant to track the previous value of `isEditing`; this is achieved by calling `usePrevious` with `isEditing` as an argument. Add the following inside `Todo()`, below the `useRef` lines:
```

2023-12-20 12:28 UTC, mxmason reviewed
Back to you @chrisdavidmills! As I said, I'm on my phone so pardon the mess – I just wanted to get this back to you ASAP.

2023-12-20 12:28 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Our CSS file uses the [`:focus-visible`](/en-US/docs/Web/CSS/:focus-visible) pseudo-class to provide custom styling for the focus indicator, and the browser uses a set of internal rules to determine
I would strike "generally" from "button elements generally don't show a focus indicator". I'm 95 percent sure that the heuristic of focus-visible is tag-based,and button elements will never show a visible indicator.

2023-12-20 12:28 UTC, mxmason commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +`usePrevious()` is a _custom hook_ that tracks a value across renders. It uses the `useRef()` hook to create a ref, and then updates the `useEffect()` hook. This means the `current` property of the r
What about:

> `usePrevious()` is a _custom hook_ that tracks a value across renders. Its code can be tricky to reason about, so here's a breakdown of how it gets executed:
>
> 1. It uses the `useRef()` hook to create an empty ref
> 2. It returns the ref's `current` value to the component that called it
> 3. _When the component renders again_, it calls `useEffect()` and  updates the value stored in `ref.current`
> 4. Because ref.current is only updated in `useEffect()`, it's always one step behind whatever `value` is in the component's main render cycle – hence the name `usePrevious()`

Feel free to adjust this if you broadly like it. I'm on my phone so I'm just trying to throw down something serviceable :p

2023-12-20 13:19 UTC, chrisdavidmills commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/react_accessibility/index.md
> +Our CSS file uses the [`:focus-visible`](/en-US/docs/Web/CSS/:focus-visible) pseudo-class to provide custom styling for the focus indicator, and the browser uses a set of internal rules to determine
OK, done.

2023-12-20 13:20 UTC, chrisdavidmills approved these changes
@mxmason OK, changes made, and approving!

Have another look at the updated `usePrevious()` description, and let me know if you are happy. I mostly used your wording.

2023-12-20 14:07 UTC, mxmason commented
This looks great, @chrisdavidmills! I'm good to move on with this if you are. 

I assume that https://github.com/mdn/todo-react/pull/97 blocks this series of content PRs, so I'll do my best to get to your notes today. I'm also fine with merging and releasing this content, if you'd prefer.

And, of course, I'm happy to do one final sweep over all this content after we merge, just to make sure it's all tidy. I'm just excited to get this out! 😁

2023-12-21 08:38 UTC, chrisdavidmills commented
> This looks great, @chrisdavidmills! I'm good to move on with this if you are.
> 
> I assume that [mdn/todo-react#97](https://github.com/mdn/todo-react/pull/97) blocks this series of content PRs, so I'll do my best to get to your notes today. I'm also fine with merging and releasing this content, if you'd prefer.
> 
> And, of course, I'm happy to do one final sweep over all this content after we merge, just to make sure it's all tidy. I'm just excited to get this out! 😁

Faaaantastic.

Ideally, I'd like the demo repo to be updated before we merge the content, but I don't see that as an absolute dealbreaker as long as it is merged soon after. As you've seen on the other repo, I'm having trouble there because I don't have the privs to merge on that repo. If I don't find someone who does in the next 30 mins or so, I'm going to go ahead anyway and merge the content.

2023-12-21 12:07 UTC, merged

2023-12-21 12:11 UTC, chrisdavidmills commented
@mxmason And with that, your work is all merged, and the job is complete. It should go live on MDN in about 24 hours, possibly sooner. As soon as that happens, I'll give everything a read-through and get ready to file a PR to fix any minor bits we may have missed.

Great work though! It has been a pleasure working with you again. I hope you have a restful festive period.

2023-12-22 07:48 UTC, chrisdavidmills commented
@mxmason your updates are live! I'll give them a good read through now, and see if I can spot any typos. Let me know if you spot any, and I'll add them into a PR of fixes.