FF122 Clipboard API
mdn/content pull request #31137
Opened 2023-12-19 04:53 UTC by hamishwillee

FF122 adds support for the async clipboard API. This PR updates the docs to spec states.

The first commit can largely be ignored as a "subedit for current templates/patterns".
- Fixes layout issues such as odd line breaks.
- Adds securecontext header and inline in the places we have now agreed they need to go
- Obeys current patterns "The XXX interface of the YYY API ...", "The XXX property of the YYY interface" etc.
- Deletes all the comment about what a new API this is.

More to follow on.

2023-12-19 05:04 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
@sideshowbarker @wbamberg I was wondering if I could get some advice on events in the context of the clipboard API.

1. How do we show bubbles, cancelable, composed now. I couldn't find it in the [template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_event_subpage_template), but I think we add it as I have here right?
2. Events are normally listed in the interface on which they are fired, and in this case the cut, paste, copy are listed in the Element interface. They are also in the sidebar data for [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). But they aren't listed in that doc - only in interfaces, and that isn't very obvious. Is this a problem?

2023-12-19 05:09 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +The **`copy`** event fires when the user initiates a copy action through the browser's user interface or the [Clipboard API](/en-US/docs/Web/API/Clipboard_API).
FYI in a sense this is a tautology since the clipboard API requires transient activation/browser interaction. This doesn't hurt though, and I think perhaps improves the cross linking to the API.

2023-12-21 05:18 UTC, wbamberg commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
> @sideshowbarker @wbamberg @teoli2003 I was wondering if I could get some advice on events in the context of the clipboard API.
> 
> 1. How do we show bubbles, cancelable, composed now. I couldn't find it in the [template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_event_subpage_template), but I think we add it as I have here right?

I don't know (because it isn't in the template). I do know that we are supposed to document these only in prose, and only document "bubbles", not "does not bubble". I think this is wrong and we should always document "bubble status", because people don't understand "if omitted, doesn't bubble". See also https://github.com/mdn/content/issues/19590 of course.

What you've added looks sensible to me, except I think a table would be more scannable than prose.

> 2. Events are normally listed in the interface on which they are fired, and in this case the cut, paste, copy are listed in the Element interface. They are also in the sidebar data for [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). But they aren't listed in that doc - only in interfaces, and that isn't very obvious. Is this a problem?

By "they aren't listed in that doc - only in interfaces, and that isn't very obvious", do you mean that, say, `paste` isn't listed in the body of [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)? If so, then, well, first, what we do at the moment for API overview pages is horribly random. Not just for this but all over.

But I think the "Interfaces" section of the API overview page should be a mirror of the sidebar here - so it should list all the concrete WP features defined in this API. That means yes, it is a problem, and a page like [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API#interfaces) is doing approximately the right thing. Although I don't very much like "[Extensions to other interfaces](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API#extensions_to_other_interfaces)" being an H3 under "Interfaces". But that's what the template has.

Maybe we should do some more work on the template and then make all these pages consistent?

2023-12-21 05:43 UTC, teoli2003 commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
### The story about the current text
So here is the long story:
- initially, we had a table, taking up a lot of space (pushing below the fold more important info).
- when we created the template, we removed it without realizing the info was necessary.
- we started to have issues filed about the missing information
- to fix issues, we added a sentence at the end of the introduction in its paragraph
- it became the de facto standard.

### The (de facto) standard

- Add a sentence at the end of the description (in its paragraph):
  - Non-bubbling: _This event is not cancelable and does not bubble._ E.g. [message event](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) There are many of these!
  - Bubbling: _This event is cancelable and may bubble up to the {{domxref("Document")}} and {{domxref("Window")}} objects._ E.g [dragend event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event)
  - Bubbling and non-cancelable: _:This event is cancelable and may bubble up to the {{domxref("Document")}} and {{domxref("Window")}} objects._ [dragstart event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event)

### What we should do

I like this de facto standard because it brings this info above the fold, in a standard way, and is not too big.
I think we should:
- update the meta documentation, ironing out the text
- eventually, update the current occurrences (Shouldn't be difficult as they are standardized)
- little by little, adding them to all events (a project?)

2023-12-21 05:44 UTC, teoli2003 commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
cc/ @skyclouds2001

2023-12-22 04:13 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
Thanks @wbamberg and @teoli2003 I hope to look at this today, but probably with Xmas will not be able to do so until Wednesday. Sorry - need to get as much of the essential for FF release stuff done this week before everyone disappears (BCD/Release notes).

2023-12-22 05:39 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
@teoli2003 @wbamberg Firstly, regarding the events bubbling, cancellable, composable. 

I think you are saying:
- info about bubbles, cancellable, composable can be extracted from spec metadata in an automatable and reliable way
- We can update this to our page metadata and therefore as authors know for sure that the information in all pages is up to date. If there is no record that means we are missing data, if there is a record, we have the data, so we can be complete.
- We can choose to render this metadata as sentences in text
- Users can trust that if the information is not present then the bubblable or whatever is not something the interface does. Right?

If we can't do all that then I think the defacto standard is definitely broken, because there is no way for users or authors to know if the sentence is missing because we missed an update, or because something doesn't have the features.

Even if we can get all that data, I do not like the approach of a sentence. Yes it is compact, But if I'm interested in knowing if something does not bubble I have to read that whole sentence, then know the convention that the fact that it is not marked as bubblable means that it isn't. That's a lot more to ask of our readers. 

It might be the right thing though, if users only ever care that something bubbles, is cancellable or composable, and don't care if it does not. Is that the case?

2023-12-22 05:44 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
Wr.t. interfaces. 

> But I think the "Interfaces" section of the API overview page should be a mirror of the sidebar here - so it should list all the concrete WP features defined in this API. That means yes, it is a problem, and a page like [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API#interfaces) is doing approximately the right thing. Although I don't very much like "[Extensions to other interfaces](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API#extensions_to_other_interfaces)" being an H3 under "Interfaces". But that's what the template has.


Yes, that is what I mean.

IN https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API I can see the `Window : clipboardchange` event in the sidebar, but it isn't mentioned in the overview page itself and there is no other place within these docs that you would link to it because Element itself is not part of the API.

So yes, I think listing the events in the overview page makes sense to highlight them sufficiently - it is after all part of the API. 

> Maybe we should do some more work on the template and then make all these pages consistent?

Yes. I would just call this section `Events` or `Events first on other intefaces`. Thoughts?

2023-12-22 07:51 UTC, teoli2003 commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
>  * info about bubbles, cancellable, composable can be extracted from spec metadata in an automatable and reliable way

I don't think we can do this right now. w3c/webref certainly has the info, but linking an event in mdn/content and mdn/browser-compat-data to one in w3c/webref is not trivial because both projects chose to put them at different places.

But in the long term, yes.

>   * We can update this to our page metadata and therefore as authors know for sure that the information in all pages is up to date. If there is no record that means we are missing data, if there is a record, we have the data, so we can be complete.

If we can get them from w3c/webref, we don't need to store them in metadata, but we could: it is a kind of implementation detail.

Also, submitting PRs in Yari is a black hole right now (they have other focuses, so even small changes can stay ignored for months and years, even with numerous friendly pings), so relying on a new macro (for example) will lead us nowhere. We are working around this limitation for many cases already, as we don't want the docs to be held back. This may hopefully change in the future, but is a constraint for potential solutions right now, and I would prefer that web developers do not suffer because of it.

>   * We can choose to render this metadata as sentences in text

We can start doing this now, manually. We will gather experience that way, too.
 
>   * Users can trust that if the information is not present, then the bubblable or whatever is not something the interface does. Right?

Yep!

> If we can't do all that then I think the defacto standard is definitely broken, because there is no way for users or authors to know if the sentence is missing because we missed an update, or because something doesn't have the features.

I partially agree: yes, it is not working immediately out of the box, but it is very quickly better for developers. There are not so many events that bubble (the most common cases), and these can get the info very quickly (=likeky within a Quarter if we focus a bit on it).

Not agreeing on a sentence or a standard, doable, way, will lead to every event page doing something different: il will be harder for web developers and harder to fix afterward.

> Even if we can get all that data, I do not like the approach of a sentence. Yes, it is compact, But if I'm interested in knowing if something does not bubble, I have to read that whole sentence and then know the convention that the fact that it is not marked as bubblable means that it isn't. That's a lot more to ask of our readers.

We should decouple the discussions about displaying the info and the first implementation. It will be simple to remove a standard sentence for a new solution, being a macro, a table, or anything else; while, right now, whatever solution we choose, it means rechecking manually every event for mentions all over the place. Also, this will bring an improvement to the users as they need the bubbling info.

Maybe we should do some user testing about how to present this information? But I think we should at least agree on an interim solution (Sometimes, better is the enemy of good, a French say). 

I think the key points for having such an interim solution are:
- it immediately helps web dev (even if not 100%)
- it doesn't impair future choices; in fact, it eases them as replacing a standard sentence is easier than what we have now.

2023-12-28 05:07 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
@wbamberg W.r.t. interfaces I have just added these to the "Extensions to other interfaces" section. A little ugly, but it does match the template, and the intent of the template (yes, Background APIs are doing the right thing). 

Always happy to discuss updates to templates but I think this just dropped in my priority list.

2023-12-28 05:24 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
@teoli2003 I agree strongly with most of that, particularly about decoupling data and presentation, and finding some interim solution we can agree on..

Unfortunately the key points of the proposed interim solution are not met. The decision to use a sentence _does_ impair future choices unless you can guarantee complete coverage. 
A standard sentence allows you to know for sure what is supported, so for that case you can extract data for the known supported cases at some future time. But you can never know that for sure something is not supported unless you have data for that. Yes we'll get closer, but users will never be able to rely on any "absent text" being correct.

Even though I think it is "suboptimal" for both readers and authors, I'll leave this as is - adding my own custom table would be even worse. 

Setting this as resolved. We can continue discussion on a discussion, or we can just wait and see (and probably just discover readers don't care about whether something bubbles or not).

2023-12-28 05:59 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +To read from the clipboard, you must first have the `"clipboard-read"` permission.
Note, need to check this. There is some evidence that the permissions have gone from the spec.

2023-12-28 05:59 UTC, hamishwillee commented on files/en-us/web/api/clipboard/readtext/index.md
>  The `"clipboard-read"` permission of the [Permissions API](/en-US/docs/Web/API/Permissions_API) must be granted before you can read data from the clipboard.
Need confirmation.

2023-12-28 05:59 UTC, hamishwillee commented on files/en-us/web/api/clipboard/write/index.md
> +The `"clipboard-write"` permission of the [Permissions API](/en-US/docs/Web/API/Permissions_API) is granted automatically to pages when they are in the active tab.
Need confirmation.

2023-12-28 06:01 UTC, hamishwillee commented on files/jsondata/GroupData.json
> -        "Window: clipboardchange",
`Window: clipboardchange` is not implemented anywhere.

2023-12-28 23:48 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
Note, the spec defines that `read()` takes an option, but Firefox does not. I am checking of other browsers do.

2023-12-28 23:50 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +  - : Thrown if the access to read the clipboard is not allowed.
The spec says you throw if the options passed to `read()` do not match copied data - but (probably) no one supports that. Chrome throws if you don't grant permission, but the read permission has left the spec.

Upshot, I have left this in because users might get it, but not provided reasons that the request might be denied.

2023-12-28 23:51 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +> **Note:** Browsers that gate access to the method using the [Permissions API](/en-US/docs/Web/API/Permissions_API) `clipboard-read` permission (now removed from specification) may require you to gr
FYI, this change reframes the example to match the spec - it works without waiting for or checking permissions. The result is also logged to screen - so you get some information about why it fails.

2023-12-28 23:52 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> -> **Note:** The asynchronous Clipboard and [Permissions APIs](/en-US/docs/Web/API/Permissions_API) are still in the
Permissions have been removed from the spec

2023-12-29 01:01 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +
FMI maybe copy in more examples from the other sub documents here.

2023-12-29 01:24 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +Browsers commonly support reading text, HTML, and PNG image data — see [browser compatibility](#browser_compatibility) for more information.
This is what Chrome and Firefox allow. I've framed it as "commonly" and hope to mention in BCD.

2023-12-29 01:25 UTC, hamishwillee commented
This is ready for review. There is more I could do, and a little more I might need to do, but I think it is good for now.

2024-01-03 20:08 UTC, wbamberg commented
The stuff on permissions seems to be a complicated mess, so we should take care to explain it as well as we can.

As I understand it:
- clipboard read and clipboard write both require transient user activation in the spec and all browser implementations
- Chromium also defines `clipboard-read` and `clipboard-write` permissions, but these are not supported (and will never be supported) by Firefox or Safari
- `clipboard-read` is not in the spec (so Chromium's support is non-standard) but `clipboard-write` [is still in the spec](https://github.com/w3c/clipboard-apis/issues/163) (so is technically standard)

Does that cover it? Do you think we need to say something like this?

2024-01-04 04:28 UTC, skyclouds2001 commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
I have a question, that is how a event is composable or not composable defined. I remember in many spec like UI Events or Pointer Events, bubbles and cancellable are mentioned but composable not

2024-01-04 22:40 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
@skyclouds2001 The definition on MDN is here https://developer.mozilla.org/en-US/docs/Web/API/Event/composed

2024-01-04 23:29 UTC, hamishwillee commented
@wbamberg Your summary in https://github.com/mdn/content/pull/31137#issuecomment-1875907536 is _almost_ right.

> - clipboard read and clipboard write both require transient user activation in the spec and all browser implementations
> - Chromium also defines `clipboard-read` and `clipboard-write` permissions, but these are not supported (and will never be supported) by Firefox or Safari

This is correct

> - `clipboard-read` is [no longer](https://github.com/w3c/clipboard-apis/pull/132) in the spec (so Chromium's support is non-standard) but `clipboard-write` [is still in the spec](https://github.com/w3c/clipboard-apis/issues/163) (so is technically standard)

The distinction is that things are even more messy than you think.
- The definitions for permission API permissions were documented in the Permissions API spec but have since been removed. So clipboard spec is referencing permissions that do not exist in-spec.
- The clipboard-read permission was "agreed removed" but is still referenced in clipboard API - i.e. with statements like "check read permission"
- The clipboard-write permission is noted as removed in the spec, but is referenced, and in the issue you point to it looks a bit like the spec authors were perhaps premature to remove it from Permissions API

Upshot, the spec is so confused now it is IMO unimplementable, and so what the spec requires is now a matter of opinion. Given the notes in the spec and comments in the PR I made the decision that we should treat permissions as removed from the spec.
Partially this is because I agree with the decision to remove those permissions - the experience on chrome is (subjectively) worse, to benefit.

So what I did say in concepts section was treat permissions as a thing that a browser can choose to do:

![image](https://github.com/mdn/content/assets/5368500/647afad2-b9a2-4d7c-9c46-8e3a32f5473c)

I've tried to make this even more clear by adding a new note at the end of the concepts section to capture "the facts". Does this do what you need?

![image](https://github.com/mdn/content/assets/5368500/d102d1c4-3f38-43e2-9230-66db480c6dea)

2024-01-04 23:30 UTC, hamishwillee commented
PS, and I removed the clipboard API from the list of APIs that have permissions in Permission API. I see this as reasonable because the Permissions API spec does not mention the permissions (whether that was premature or not, it is what the spec says).

2024-01-05 04:11 UTC, skyclouds2001 commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
Well, thanks. Then it makes sense to mention if a event is composable or not

2024-01-05 05:16 UTC, hamishwillee commented
@wbamberg Thanks for your testing on this. It does look like Chrome requires permissions but does not require transient activation. It is not really clear what is going to happen to the spec. I am seeking clarification here: https://github.com/w3c/clipboard-apis/issues/163#issuecomment-1878072165

In any case, it's best to proceed with what we know, or at least we think we know. What I have done is 

1. highlight the different expectations of the APIs in the API overview page. This makes the two implementations (as I understand them) clear and provides some of the history. 
   ![image](https://github.com/mdn/content/assets/5368500/3b34336c-a9f1-4b5f-86e9-369690d295e4)
1. Updated the `read()` example (which previously mentioned permissions) to include a function that handles the case where they are defined or not defined.

The other examples are unchanged - they are very simple and don't mention permissions. I think this is appropriate, in particular at the moment while the status is a bit unclear. 

It may however be worth copying the `read()` example into the API overview page - thoughts?

I know this is still not rock solid, but IMO it is "better".

2024-01-05 05:26 UTC, hamishwillee commented on files/en-us/web/api/element/copy_event/index.md
> +This event [bubbles](/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture), is [cancelable](/en-US/docs/Web/API/Event/cancelable) and is [composed](/en-US/docs/Web/API/Event
> Then it makes sense to mention if a event is composable or not

@skyclouds2001 Thats the central point of this whole argument :-). The @teoli2003 theory is that we only have to add a sentence if the event is any of: composable, bubbles, cancellable. My theory is that if the sentence isn't there you don't know if they were accidentally omitted or just not supported. To that I add you may not even know that composed etc. exist if you never look up an item that talks about them - you are the proof of that point.

But we're not going around this loop again ... until I run into the next case I have to update.

2024-01-06 04:20 UTC, wbamberg requested changes, later dismissed
I probably made an annoying number of comments on things you didn't change...

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboard/writetext/index.md
>  ## Examples
Same comment as before: consider async/await, and a click handler.

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/index.md
Again not sure about the note below "You can only pass in one clipboard item at a time." In fact in this case I would just omit it.

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/index.md
> +The **`ClipboardItem`** interface of the [Clipboard API](/en-US/docs/Web/API/Clipboard_API) represents a single item format, used when reading or writing data via the {{domxref('Clipboard API')}}. Th
```suggestion
The **`ClipboardItem`** interface of the [Clipboard API](/en-US/docs/Web/API/Clipboard_API) represents a single item format, used when reading or writing clipboard data using {{domxref("clipboard.read()")}} and {{domxref("clipboard.write()")}} respectively.
```

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/index.md
> +### Writing to Clipboard
"to the"? And why capitalize "clipboard" here?

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/index.md
> +### Reading from Clipboard
"from the"? And why capitalize "clipboard" here?

2024-01-06 04:20 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/presentationstyle/index.md
> +For example, in some contexts an image might displayed inline, while in others it might be represented as an attachment.
```suggestion
For example, in some contexts an image might be displayed inline, while in others it might be represented as an attachment.
```

2024-01-06 04:20 UTC, wbamberg commented on files/jsondata/GroupData.json
> -      "events": [
I think we should also remove "/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard" from "guides".

2024-01-08 00:09 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +The Clipboard API allows users to programmatically read and write text and other kinds of data to and from the system clipboard in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), provide
Yes. I was thinking exactly the same thing and had decided to tell you that this morning.

2024-01-08 00:14 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +To cope with the different implementations, we define the following `checkPermission()` function that returns the permission value if the permission exists, `undefined` if it does not (or cannot be r
We don't _need_ to do this. I thought perhaps we _should_ because sometimes you use the permission information to configure your UI. We don't here, and since permissions are so "confrontational", perhaps not. I'll revert that bit to my previous.

2024-01-08 00:25 UTC, hamishwillee commented on files/en-us/web/api/clipboard/write/index.md
> +This example function replaces the current contents of the clipboard with a specified string.
I guess you use `writeText` if you **know** only ever want to write text into the clipboard for later reading - as it's more ergonomic. If you might need to write HTML or an image, you have to use this.

2024-01-08 00:28 UTC, hamishwillee commented on files/en-us/web/api/clipboarditem/index.md
> +### Writing to Clipboard
Ah, because I was using Clipboard as an interface name. That's weird.
```suggestion
### Writing to the clipboard
```

2024-01-08 00:28 UTC, hamishwillee commented on files/en-us/web/api/clipboarditem/index.md
> +### Reading from Clipboard
Ditto
```suggestion
### Reading from the clipboard
```

2024-01-08 02:44 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +{{EmbedLiveSample("Reading image data", "100%", "200")}}
> I understand from BCD that Chrome does not support images, but why is the permissions check throwing an error here?

Chrome supports PNG images only according to the docs, but testing shows jpg as well. Firefox now does just supports PNG for "parity".

> On Firefox this example works great. On Chrome I get the error message "Not allowed to read clipboard.", which is odd. I understand from BCD that Chrome does not support images, but why is the permissions check throwing an error here?

@wbamberg 

WTF indeed. This API is doing my head in. It turns out it also requires a Feature/Permission-Policy - see https://chromestatus.com/feature/5767075295395840 and https://github.com/w3c/webappsec-permissions-policy/issues/322

But since this appears to be granted to runner in both local and from the PR server, who knows :-(

Still playing.

2024-01-08 05:18 UTC, hamishwillee commented on files/jsondata/GroupData.json
> -      "events": [
Yes. Web extensions need information on the clipboard, but the clipboard does not need all this information on legacy ways of interacting with clipboard. 

We do at some point need to update this guide though, and also add a note to these docs that this stuff can also be used by extensions. Probably on release of this feature in Firefox.

2024-01-08 05:21 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +This example uses the `read()` method to read data from the clipboard and log whatever data is stored in the clipboard.
FYI I added this example to show exactly what is in each of those items, since when you read an image you always seem to get some HTML too. Note though that I haven't been able to to test reading JPG because when you copy the file from UI it gets stored in clipboard as PNG. I tried actually adding JPG using the following function but WRITING JPG is not supported (throws error).

```
async function writeImageToClipboard(imageUrl) {
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    const type = "image/jpg";
    const data = [new ClipboardItem({ [type]: blob })];
    await navigator.clipboard.write(data);
}
```

2024-01-08 05:42 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
>  ## Syntax
Note there are new options for the syntax to allow handling of unsanitised input but they are only JUST added to chrome 122 in https://chromestatus.com/feature/5716132676763648. I do not propose to add them right now, but will do so as a post process.

2024-01-08 07:12 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +> They have been removed from the [Permissions API](/en-US/docs/Web/API/Permissions_API) specification, but are still referenced in the Clipboard API specification.
Yes. All fixed up in new Security considerations.

2024-01-08 07:12 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +Chromium browsers require the `clipboard-read` and `clipboard-write` permissions from the [Permissions API](/en-US/docs/Web/API/Permissions_API) to read from, and write to, the clipboard.
Yes, all this stuff now in security considerations.

2024-01-08 07:14 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +The Clipboard API allows users to programmatically read and write text and other kinds of data to and from the system clipboard in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), provide
@wbamberg The precise situation is now captured in Security considerations section in this doc. That's from the Mozilla engineer and https://chromium.googlesource.com/chromium/src/+/10300ac7da93a7e322274f1e (FF107).

I'll get that in BCD too. But it shouldn't be hidden so I've put it here. In all the other docs with security considerations I state they need secure context (the ONLY common thing) and cross link to this section.

2024-01-08 07:15 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +{{EmbedLiveSample("Reading image data", "100%", "200")}}
OK, on rebuild the problem DOES appear to be permissions policy. AFAIK this can't then work for Chrome in our examples, but at least the example states why.

2024-01-08 10:37 UTC, hamishwillee commented on files/en-us/web/api/clipboard/readtext/index.md
> +This example retrieves the textual contents of the clipboard and inserts the returned text into an element's contents.
Done, though there is no such requirement on Chrome as we now know.

2024-01-08 11:00 UTC, hamishwillee commented on files/en-us/web/api/clipboard/write/index.md
> +- {{domxref("Clipboard.writeText()")}}
Yes. Good catch.

2024-01-08 11:10 UTC, hamishwillee commented on files/en-us/web/api/clipboard/writetext/index.md
>  ## Examples
Done. I'd feel happier if they were live examples, but I think the code looks correct.

2024-01-08 11:10 UTC, hamishwillee commented on files/en-us/web/api/clipboard_api/index.md
> +
If I do, will happen in the next iteration. Shouldn't be long - FF clipboard should come out of Nightly soon.

2024-01-08 11:13 UTC, hamishwillee commented
@wbamberg Thanks. I think I have now addressed all comments. As per https://github.com/mdn/content/pull/31137#discussion_r1444187684 I have discovered that some chrome-only options to `read()` have just been added Chrome 122. I don't propose to do those for this update, but I expect to do them when I come back..

2024-01-08 11:15 UTC, hamishwillee commented on files/en-us/web/api/clipboard/write/index.md
> +This example function replaces the current contents of the clipboard with a specified string.
But anyway, I left this because it is a good example of how to convert the text to blob.

2024-01-08 18:04 UTC, wbamberg commented on files/en-us/web/api/clipboard_api/index.md
> +The Clipboard API allows users to programmatically read and write text and other kinds of data to and from the system clipboard in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), provide
```suggestion
The Clipboard API allows users to programmatically read and write text and other kinds of data to and from the system clipboard in [secure contexts](/en-US/docs/Web/Security/Secure_Contexts), provided the user has met the criteria outlined in the [Security considerations](#security_considerations).
```

2024-01-08 19:36 UTC, wbamberg requested changes
Thanks for the updates. Really helpful for people to untangle the security requirements like this.

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboard/read/index.md
> +This differs from the previous version that it will display text, HTML, and image {{domxref("ClipboardItem")}} objects (rather than just images).
```suggestion
This differs from the previous version in that it will display text, HTML, and image {{domxref("ClipboardItem")}} objects (rather than just images).
```

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboard/read/index.md
> +Select the indicted frame below to paste this information from the clipboard into the frame.
indicted -> indicated?

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboard/read/index.md
> +Copy some text, or the butterfly (JPG) or clock (PNG) images below (to copy images right-click on them and then select "Copy image" from the context menu).
I'm not seeing the clock image in preview:

![Uploading Screen Shot 2024-01-08 at 11.24.51 AM.png…]()

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboard/read/index.md
> +- Even though the butterfly image is a PNG file, it is copied into the clipboard as a PNG.
```suggestion
- Even though the butterfly image is a PNG file, it is copied into the clipboard as a JPG.
```

?

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboard/writetext/index.md
> +    console.log(error.message);
```suggestion
    console.error(error.message);
```

2024-01-08 19:36 UTC, wbamberg commented on files/en-us/web/api/clipboarditem/clipboarditem/index.md
> +The below example requests a png image using the {{domxref("Fetch API")}}, and in turn, the {{domxref("Response.blob()", "responses' blob()")}} method, to create a new {{domxref("ClipboardItem")}}.
```suggestion
The below example requests a PNG image using the {{domxref("Fetch API")}}, and in turn, the {{domxref("Response.blob()", "responses' blob()")}} method, to create a new {{domxref("ClipboardItem")}}.
```

2024-01-08 22:48 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +Select the indicted frame below to paste this information from the clipboard into the frame.
```suggestion
Select the indicated frame below to paste this information from the clipboard into the frame.
```

2024-01-08 22:52 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +- Even though the butterfly image is a PNG file, it is copied into the clipboard as a PNG.
Thanks you. Good catch on the inconsistency, but actually the reverse.

```suggestion
- Even though the butterfly image is a JPG file, when read from the clipboard it is a PNG.
```

FYI only I can't find a "why" after a little searching, but both my testing and Internet seem to show that images copied from web page to clipboard default to PNG in the clipboard. I suspect that under the hood they are a canvas, and the canvas default is to write blob data to PNG.

2024-01-09 00:43 UTC, hamishwillee commented
@wbamberg I've accepted all the nit fixes. Now trying to work out what is going on with the non-rendering image. Frankly I am stumped, and not sure what to do next.
1. I can see the image is present in the folder and it displays locally.
2. On upload it is "not found". There is no error in the build.
3. If I use a different image it does not work. I thought maybe there was something wrong with the image I used, so I tried adding a few more new images and copies of the JPG that works (butterfly). Only the original butterfly renders.
4. I also tried pushing this as a new PR - https://github.com/mdn/content/pull/31592 . I thought perhaps original PR was not rendering. Again, it only renders the original butterfly that was uploaded - not even a duplicate butterfly with a new name is displayed.

Any suggestions? I think this is not a bug in my code. I'd like to merge and see if it is something to do with the PR reviewer.

2024-01-09 01:22 UTC, wbamberg commented
I don't think this is a bug in your code either. My suggestion:
- remove the PNG example
- file a Yari issue for the problem. We can use your [test PR](https://github.com/mdn/content/pull/31592) as a demonstration of the problem.
- merge this PR. I don't think we should on this problem.

2024-01-09 04:23 UTC, hamishwillee commented on files/en-us/web/api/clipboard/read/index.md
> +- This may not work on chromium browsers as the sample frame is not granted the [Permissions-Policy](/en-US/docs/Web/HTTP/Headers/Permissions-Policy) `clipboard-read` and `clipboard-write` permission
@wbamberg As discussed, I couldn't get the second image to display - created an issue in https://github.com/mdn/yari/issues/10287

This also logs an error on Chromium due to the permissions policy not being granted to the live sample frame. I tried a `LiveSampleLink` because I figured that might work, but on PR preview that page gives a "Not found". 

Anyway, think this is good for a re-review.

2024-01-09 04:35 UTC, wbamberg approved these changes
👍 Looks great, thank you for this @hamishwillee !

2024-01-09 04:36 UTC, merged

2024-01-09 07:36 UTC, hamishwillee commented
It only looks this way because of your help and patience. Thank you.