Adds clarifying note to using sandbox with iframe tag
mdn/content pull request #31164
Opened 2023-12-19 22:20 UTC by Tenkir

### Description

Adds  a note to explain the behavior of the iframe `sandbox` attribute when opening auxiliary windows.

### Motivation

We encountered an issue where we where not able to submit forms in a page linked to from an iframe. We only discovered this behavior with the `sandbox` attribute after finding [a gist from Google](https://googlechrome.github.io/samples/allow-popups-to-escape-sandbox/) demoing the changes adding `allow-popups-to-escape-sandbox` flag.

### Additional details

[whatwg proposal](https://wiki.whatwg.org/wiki/Iframe_sandbox_improvments)

2023-12-20 08:59 UTC, chrisdavidmills requested changes
Hi @Tenkir, thanks a lot for your contribution to MDN, much appreciated.

I think this is a good point to draw attention to, although I did have some thoughts on how to present the information:

1. More a cosmetic detail — since this note only contains one point, you can put it all on the same line, i.e. 
     > **Note:** When opening a link from an embedded page with the `sandbox` attribute, the Auxiliary Window is restricted to the same `sandbox` values unless `allow-popups-to-escape-sandbox` is included.
2. To be clear, we are specifically talking about the sandboxed behavior of new tabs or windows spawned from inside an iframe, right? Either created by following a basic link, or by completing an action that invokes an `open()` call that does the same thing via JS? I'd probably rephrase in that case, as "opening a link" is a bit ambiguous.
3. "Auxiliary Window" sounds a bit spec-language and potentially confusing. Maybe just "popup window or new tab", assuming my statement above is correct?
4. I also thought about the placement of your note. I think it would make sense to move the note to the "Scripting" section of the page, make it specifically about disallowing scripting being an issue, and give your form problem as an example. I'm sure most of the issues people have with this are due to scripting being disallowed in the newly spawned window, and then wondering why, so the "Scripting" section would be a good focal point for people to find the information.
5. Then you could also update the "allow-popups-to-escape-sandbox" description earlier in the page to something a bit more useful, as currently it is a bit value and doesn't really give a good use case. How about:
   
"Allows a sandboxed document to open new windows or tabs without forcing the same sandboxing restrictions upon them. This will allow, for example, a third-party advertisement to be safely sandboxed without blocking functionality in the page the ad links to, or form contained in a popup window spawned from a sandboxed document that disallows scripting to be submitted via JavaScript."

Let me know what you think of my suggestions.

2023-12-20 13:45 UTC, Tenkir commented
Hi @chrisdavidmills , thanks for the quick response!

> To be clear, we are specifically talking about the sandboxed behavior of new tabs or windows spawned from inside an iframe, right? Either created by following a basic link, or by completing an action that invokes an open() call that does the same thing via JS? I'd probably rephrase in that case, as "opening a link" is a bit ambiguous.

Yes, though I believe it will also apply if the current page is redirected within the same tab. Perhaps "redirecting, opening a popup window, or new tab"

> "Auxiliary Window" sounds a bit spec-language and potentially confusing. Maybe just "popup window or new tab", assuming my statement above is correct?

Agreed.

> I also thought about the placement of your note. I think it would make sense to move the note to the "Scripting" section of the page, make it specifically about disallowing scripting being an issue, and give your form problem as an example. I'm sure most of the issues people have with this are due to scripting being disallowed in the newly spawned window, and then wondering why, so the "Scripting" section would be a good focal point for people to find the information.

I would hesitate to locate this note here, as it can pertain to more than just scripting. The restriction applies to all `sandbox` flags, not just those pertaining to scripting. For example, the `allow-forms` flag will block the submission of pure HTML forms as well. 

My thought of locating it with the sandbox section is that, if a developer is utilizing the sandbox attribute, they would be most likely to be in this section, where the note is most relevant.

> Then you could also update the "allow-popups-to-escape-sandbox" description earlier in the page to something a bit more useful, as currently it is a bit value and doesn't really give a good use case. How about:

This makes sense, I can update that language.

2023-12-21 08:31 UTC, chrisdavidmills commented
> Hi @chrisdavidmills , thanks for the quick response!
> 
> > To be clear, we are specifically talking about the sandboxed behavior of new tabs or windows spawned from inside an iframe, right? Either created by following a basic link, or by completing an action that invokes an open() call that does the same thing via JS? I'd probably rephrase in that case, as "opening a link" is a bit ambiguous.
> 
> Yes, though I believe it will also apply if the current page is redirected within the same tab. Perhaps "redirecting the user, opening a popup window, or opening a new tab"

@Tenkir yup, makes perfect sense.

> 
> > I also thought about the placement of your note. I think it would make sense to move the note to the "Scripting" section of the page, make it specifically about disallowing scripting being an issue, and give your form problem as an example. I'm sure most of the issues people have with this are due to scripting being disallowed in the newly spawned window, and then wondering why, so the "Scripting" section would be a good focal point for people to find the information.
> 
> I would hesitate to locate this note here, as it can pertain to more than just scripting. The restriction applies to all `sandbox` flags, not just those pertaining to scripting. For example, the `allow-forms` flag will block the submission of pure HTML forms as well.

OK, fair point. In that case, maybe expand your content a little bit to talk about the real-world effects on popup/redirect/new tab content. I'm thinking that we want to make sure that it doesn't just basically repeat the contents of the `allow-popups-to-escape-sandbox` value description. Maybe something along the lines of:

> **Note:** When a popup or new tab is opened from content embedded in a `<iframe>`, or that content redirects the user, that popup/new location will have the same sandbox privileges as the original `<iframe>`. This can create problems such as ...(description). For example (give form example). To get around these problems, include the `allow-popups-to-escape-sandbox` value in your list of `sandbox` values. 

Hastily written, with placeholders, but you get the idea.
 
> My thought of locating it with the sandbox section is that, if a developer is utilizing the sandbox attribute, they would be most likely to be in this section, where the note is most relevant. Though I can see the value of locating it somewhere where a developer of a destination page who is not also developing the source iframe would find it.
> 
> > Then you could also update the "allow-popups-to-escape-sandbox" description earlier in the page to something a bit more useful, as currently it is a bit value and doesn't really give a good use case. How about:
> 
> This makes sense, I can update that language.

Cool

2023-12-22 22:14 UTC, Tenkir commented
@chrisdavidmills Had a bit of a kerfufle with your merging the upstream (as I typically rebase my commits for a cleaner git history). But it should be resolved now and ready for review.

2024-01-02 15:20 UTC, chrisdavidmills requested changes
Hi there @Tenkir, thanks for the most recent updates you made, and sorry it took me so long to respond to this. I think the placement of the new content is great; I just had some new wording suggestions for you to go over. Nearly there now!

2024-01-02 15:20 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +      - : Allows a sandboxed document to open new windows without forcing the sandboxing flags upon them. This will allow, for example, a third-party advertisement to be safely sandboxed without forc
```suggestion
      - : Allows a sandboxed document to open a new browsing context without forcing the sandboxing flags upon it. This will allow, for example, a third-party advertisement to be safely sandboxed without forcing the same restrictions upon the page the ad links to. If this flag is not included, a redirected page, popup window, or new tab will be subject to the same sandbox restrictions as the originating `<iframe>`.
```

2024-01-02 15:20 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new page, popup window or new tab
```suggestion
    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new browsing context is subject to the same sandbox restrictions. This can create issues — for example, if a page embedded within an `<iframe>` with a `sandbox="allow-scripts"` attribute set on it opens a new site in a separate tab, script-based functionality such as form submission will silently fail in that new tab. To get around these problems, include the `allow-popups-to-escape-sandbox` flag in the `<iframe>`'s `sandbox` attribute.
```

2024-01-02 15:20 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new page, popup window or new tab
I removed the second option you included in the workarounds sentence — "or include the applicable `sandbox` value to enable the desired behavior" — as I wasn't sure where you'd include this in the new browsing context content. Do you mean include it as part of a content security policy, or something else? Feel free to add it back in, provided you clarify it.

2024-01-02 16:29 UTC, Tenkir commented on files/en-us/web/html/element/iframe/index.md
> +    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new page, popup window or new tab
To clarify, I mean add the appropriate flag to the `sandbox` attribute to enable the desired behavior.
 
This doesn't necessarily have anything to do with scripts. I elected to use the form example, since not including the `allow-forms` flag will cause all HTML form elements to be blocked, whether they use JS in their submit handler or not.

For example, let's say I have an iframe with `allow-scripts`. This links to a new page where I have a pure HTML form element that does not use javascript. This form will be blocked. Additionally, using javascript in the submit handler will still be blocked, since `allow-forms` was not set, all form submission is blocked. It's entirely separate from the script-based qualifier.

I can update some language here to clarify that.

2024-01-02 16:41 UTC, Tenkir commented on files/en-us/web/html/element/iframe/index.md
> +    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new page, popup window or new tab
Proposed language:

> This can create issues — for example, if a page embedded within an `<iframe>` without a `sandbox="allow-forms"` or `sandbox="allow-popups-to-escape-sandbox"` attribute set on it opens a new site in a separate tab, form submission in that new browsing context will silently fail.

2024-01-02 16:51 UTC, chrisdavidmills commented on files/en-us/web/html/element/iframe/index.md
> +    > **Note:** When redirecting the user, opening a popup window, or opening a new tab from an embedded page within an `<iframe>` with the `sandbox` attribute, the new page, popup window or new tab
Ah, I understand now — yup, the proposed language looks fine.

2024-01-02 18:14 UTC, chrisdavidmills approved these changes
Great, thanks @Tenkir! Let's get this merged.

2024-01-02 18:15 UTC, merged