Add contextualIdentities.move
mdn/content pull request #31191
Opened 2023-12-21 08:04 UTC by rebloor

### Description

Documentation and release note in support of [Bug 1333395](https://bugzilla.mozilla.org/show_bug.cgi?id=1333395) Consider support for containers sort order.

2023-12-27 15:10 UTC, Rob--W requested changes

2023-12-27 15:10 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/move/index.md
> +Starting with this list of contextual identities `[id0, id1, id2, id3]`:
I guess that these were based on the testcase. In there, id0, id1, etc are variable names referring to the actual IDs. The examples below are unclear and not working.

I would simplify this section by showing how one can query identities, then choose the identity to move. For example, the scenario of moving the last identity to the start, and then back to the end. And another one where multiple identities are moved.

```js
let identities = await browser.contextualIdentities.query({});
let firstId = identities[0].cookieStoreId;

// Moves first identity to the end.
await browser.contextualIdentities.move(firstId, -1);

// Move identity to the start again.
await browser.contextualIdentities.move(firstId, 0);
```

Alternative way of moving the first identity to the end: by moving all other identities to the start we get the same effect:

```js
let identities = await browser.contextualIdentities.query({});
let ids = identities.map(identity => identity.cookieStoreId);
// Create array without the first item:
let otherIds = ids.slice(1);

// Moves other identities to the start,
// effectively putting the first identity to the end.
await browser.contextualIdentities.move(otherIds, 0);
```

Another example, move "Personal" identity before "Work". Important note: this example assumes containers with these names to exist. This is often not the case in customized or localized (non-English) Firefox instances.

```js
let identities = await browser.contextualIdentities.query({});

// Find cookieStoreId of container with name "Personal".
let personalId = identities.find(ci => ci.name === "Personal")?.cookieStoreId;
if (!personalId) {
  throw new Error("Personal container not found");
}

// Find index of container with name "Work".
let workIndex = identities.findIndex(identity => identity.name === "Work");
if (workIndex === -1) {
  throw new Error("Work container not found!");
}
await browser.contextualIdentities.move(personalId, workIndex);
```

2023-12-30 16:47 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/move/index.md
> +  - : `integer`. The position to move `cookieStoreIds` to in the list of contextual identities. `-1` indicates that the items are moved to the end of the list.
```suggestion
  - : `integer`. The position to move `cookieStoreIds` to in the list of contextual identities. Zero-based; `0` indicates the first position. `-1` indicates that the items are moved to the end of the list.
```

2023-12-30 16:49 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/move/index.md
> +A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that is fulfilled with an array of cookie store IDs representing the re-ordered list. If the request is for an invalid move
```suggestion
A [`Promise`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that is fulfilled when the contextual identities are reordered. If the request is for an invalid move or the contextual identities feature is not enabled, the promise is rejected.
```

2023-12-30 17:10 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/move/index.md
> +Starting with this list of contextual identities `[id0, id1, id2, id3]`:
Thanks for the suggestions @Rob--W

2024-01-05 13:31 UTC, Rob--W approved these changes
Please apply the suggested edits before merging.

2024-01-05 13:31 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/move/index.md
> +}
Edit to account for shifting by one:

```suggestion
// Find the index and ID of the container with the name "Personal".
let personalIndex = identities.findIndex((ci) => ci.name === "Personal");
if (personalIndex === -1) {
  throw new Error("Personal container not found");
}
let personalId = identities[personalIndex].cookieStoreId;

// Find the index of the container with the name "Work".
let workIndex = identities.findIndex((identity) => identity.name === "Work");
if (workIndex === -1) {
  throw new Error("Work container not found!");
}

if (personalIndex < workIndex) {
  // When the Personal identity moves, all following
  // identities shift to the left by one. To place
  // the Personal identity before the Work identity,
  // we should therefore subtract one.
  workIndex--;
}
```

2024-01-05 17:03 UTC, merged