added a release note for the removal of wrong type attributes on list
mdn/content pull request #31200
Opened 2023-12-21 16:41 UTC by dletorey

### Description

Added a FF 122 release note for the fix of incorrect types on lists

### Motivation

Working on [<ol type=disc> should have no effect per spec issue 31105](https://github.com/mdn/content/issues/31105)

### Related issues and pull requests

- [Bugzilla Issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1868087)

2024-01-18 22:45 UTC, dipikabh requested changes
Thanks, @dletorey. I've added a suggestion.

2024-01-18 22:45 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/122/index.md
> +- The `type` HTML attribute no longer has an effect if set to `none`, `disc`, `circle` or `square` on {{HTMLElement("ol")}} and no longer has an effect if set to `1`, `a`, `A`, `i` or `I` on {{HTMLEl
How about phrasing it like this:
```suggestion
- The `type` HTML attribute has been deprecated. This attribute no longer has an effect when set to `none`, `disc`, `circle` or `square` in {{HTMLElement("ol")}} and when set to `1`, `a`, `A`, `i` or `I` in {{HTMLElement("ul")}}. ([Firefox bug 1868087](https://bugzil.la/1868087)).
```

2024-01-23 14:08 UTC, dletorey commented on files/en-us/mozilla/firefox/releases/122/index.md
> +- The `type` HTML attribute no longer has an effect if set to `none`, `disc`, `circle` or `square` on {{HTMLElement("ol")}} and no longer has an effect if set to `1`, `a`, `A`, `i` or `I` on {{HTMLEl
So it has not been deprecated, it now only respects the types relavant to the list type 
So `<ul>` you can still add `type="square"` but not `type="1"` for example.

2024-01-23 14:21 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/122/index.md
> +- The `type` HTML attribute no longer has an effect if set to `none`, `disc`, `circle` or `square` on {{HTMLElement("ol")}} and no longer has an effect if set to `1`, `a`, `A`, `i` or `I` on {{HTMLEl
Ah! Thanks for clarifying @dletorey.
- Can we reword "This should not be set either as `type`" to replace "This" to say what it's referring to?
- Replace "as" with "because" just for readability and clarity
- The two instances of "on" can be replaced with "in"

2024-01-23 15:07 UTC, dletorey commented on files/en-us/mozilla/firefox/releases/122/index.md
> +- The `type` HTML attribute no longer has an effect if set to `none`, `disc`, `circle` or `square` on {{HTMLElement("ol")}} and no longer has an effect if set to `1`, `a`, `A`, `i` or `I` on {{HTMLEl
I have updated thgis now.
I was kinda wrong, it is deprecated but has been for a long while. 
But I have totally reworded the last sentence.

2024-01-23 15:34 UTC, dipikabh approved these changes
Perfect, thank you!

2024-01-23 15:34 UTC, merged