Screen Wake Lock API subedit
mdn/content pull request #31208
Opened 2023-12-22 00:39 UTC by hamishwillee

FF122 adds support for the [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) in https://bugzilla.mozilla.org/show_bug.cgi?id=1589554 in Nightly. 

As part of the release work, this is a quick subedit for the Screen Wake Lock API docs. Most of it is just layout change. There are a few minor parts where I have added better cross linking.

Related docs work can be tracked in https://github.com/mdn/content/issues/31112

2023-12-22 00:39 UTC, hamishwillee commented on files/en-us/web/api/screen_wake_lock_api/index.md
> +The Screen Wake Lock API prevents the screen from turning off, dimming or locking. It allows for a simple platform-based solution for visible (active) documents to acquire the platform screen wake lo
FYI I think API is mature enough to stop talking about workarounds

2023-12-22 00:42 UTC, hamishwillee commented on files/en-us/web/api/wakelocksentinel/index.md
> +The **`WakeLockSentinel`** interface of the [Screen Wake Lock API](/en-US/docs/Web/API/Screen_Wake_Lock_API) can be used to monitor the status of the platform screen wake lock, and manually release t
This is probably the only necessary fix in the doc as it implies that the sentinel can be used to reacquire the lock. That is not the case - it is single use, though it does tell you when the lock is lost and may need to be reacquired.

2023-12-27 22:45 UTC, hamishwillee commented on files/jsondata/GroupData.json
>        "overview": ["Screen Wake Lock API"],
Is there any way to add the Permission-Policy directive `screen-wake-lock` to this API? It is used for gating, and so is relevant?

2024-01-08 08:51 UTC, chrisdavidmills commented on files/en-us/web/api/screen_wake_lock_api/index.md
> +The Screen Wake Lock API prevents the screen from turning off, dimming or locking. It allows for a simple platform-based solution for visible (active) documents to acquire the platform screen wake lo
Yup, I agree.

2024-01-08 08:53 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
>        "overview": ["Screen Wake Lock API"],
Nope, 'fraid not. GroupData doesn't accept HTML or CSS features, or anything else that ain't pure API.

2024-01-08 08:57 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
>        "overview": ["Screen Wake Lock API"],
FWIW, I usually include a permissions policy section in my landing pages to detail this requirement. For example:

- https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API#permissions_policy_integration_and_iframe_support
- https://developer.mozilla.org/en-US/docs/Web/API/WebOTP_API#controlling_access_to_the_api

2024-01-08 09:42 UTC, chrisdavidmills requested changes
Hi @hamishwillee! I've reviewed this for you, and have a few fixes and suggestions for you to look through. Nothing too major.

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelock/request/index.md
> +The `request()` method is wrapped in a `try...catch` statement to account for if the browser refuses the request for any reason.
```suggestion
The `request()` method is wrapped in a `try...catch` statement to handle cases where the browser refuses the request for any reason.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelock/request/index.md
> +The `request()` method is wrapped in a `try...catch` statement to account for if the browser refuses the request for any reason.
Original wording seemed a bit awkward.

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelock/request/index.md
> +Note that the screen wake lock may be revoked by the device after it has been granted.
```suggestion
The screen wake lock may be revoked by the device after it has been granted.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelock/request/index.md
> +Note that the screen wake lock may be revoked by the device after it has been granted.
Or put it in a note box?

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/index.md
> +A screen wake lock is requested using the {{domxref('WakeLock.request()','navigator.wakeLock.request()')}} method, which returns a {{jsxref('Promise')}} that fulfills to an object of this type if the
```suggestion
A screen wake lock is requested using the {{domxref('WakeLock.request()','navigator.wakeLock.request()')}} method, which returns a {{jsxref('Promise')}} that fulfills with a `WakeLockSentinel` object if the lock is granted.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/index.md
> +A screen wake lock is requested using the {{domxref('WakeLock.request()','navigator.wakeLock.request()')}} method, which returns a {{jsxref('Promise')}} that fulfills to an object of this type if the
Just so it is completely obvious what is happening.

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/index.md
> +An acquired screen wake lock can be released manually via the {{domxref('WakeLockSentinel.release','release()')}} method, or automatically via the platform screen wake lock (this might happen if the
```suggestion
An acquired screen wake lock can be released manually via the {{domxref('WakeLockSentinel.release','release()')}} method, or automatically via the platform screen wake lock. The latter may occur if the document becomes inactive or loses visibility, if the device is low on power, or if the user turns on a power save mode.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/index.md
> +In this example we create an asynchronous function which requests a `WakeLockSentinel`.
```suggestion
In this example, we create an asynchronous function that requests a `WakeLockSentinel`.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/index.md
> +Once acquired we listen for the `release` event which can be used to give appropriate UI feedback.
```suggestion
Once the screen wake lock is acquired we listen for the `release` event, which can be used to give appropriate UI feedback.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +The `WakeLockSentinel` is released when the associated platform screen wake lock is revoked, and then remains `true`.
```suggestion
The `WakeLockSentinel` is released when the associated platform screen wake lock is revoked; `released` will return `true` thereafter.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +If needed, the application would heed to request a new screen wake lock (the current `WakeLockSentinel` cannot be reused).
```suggestion
If a subsequent screen wake lock is required, the application will need to request a new screen wake lock (the current `WakeLockSentinel` cannot be reused).
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +A boolean value, that is `false` until the {{domxref("WakeLockSentinel")}} has been released (either through a call to {{domxref("WakeLockSentinel.release()")}} or because the lock has been released
```suggestion
A boolean value that is `false` until the {{domxref("WakeLockSentinel")}} has been released (either through a call to {{domxref("WakeLockSentinel.release()")}} or because the lock has been released automatically) and the {{domxref("WakeLockSentinel/release_event", "release")}} event has been emitted, after which it becomes `true` and no longer changes.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +This example shows how **`released`**'s value changes within a {{domxref("WakeLockSentinel")}}'s life cycle.
```suggestion
This example shows how the value of `released` changes within a {{domxref("WakeLockSentinel")}}'s life cycle.
```

2024-01-08 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/type/index.md
> +The type `screen` is a screen wake lock.
Feels to me like you should explain that `screen` is currently the only available value. Maybe

 ```suggestion
Currently, the value is always `screen`, which represents a screen wake lock.
```

?

2024-01-08 23:33 UTC, hamishwillee commented on files/en-us/web/api/wakelock/request/index.md
> +Note that the screen wake lock may be revoked by the device after it has been granted.
I like your suggestion. Note not really needed.

2024-01-08 23:39 UTC, hamishwillee commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +The `WakeLockSentinel` is released when the associated platform screen wake lock is revoked, and then remains `true`.
Better. Slight mod, because I find the term "thereafter" a little clunky.
```suggestion
The `WakeLockSentinel` is released when the associated platform screen wake lock is revoked; afterwards `released` will always return `true`.
```

2024-01-08 23:41 UTC, hamishwillee commented on files/en-us/web/api/wakelocksentinel/type/index.md
> +The type `screen` is a screen wake lock.
Absolutely.

2024-01-08 23:48 UTC, hamishwillee commented on files/jsondata/GroupData.json
>        "overview": ["Screen Wake Lock API"],
Thanks very much. This is already present in the API doc - I was just hoping to make it more obvious :-).

FYI only note that it was under "Permissions Policy integration" but I have changed that to "Security considerations". Grouping all security features under a heading with this name seems to be where we are heading - makes sense to have just one heading name and collect Permissions Policy, Permissions API, Secure context, Transient user activation, etc all in one place.

2024-01-08 23:49 UTC, hamishwillee commented
Thanks very much Chris. I have accepted all your changes, with a minor change in I think one case. Should be good to merge.

2024-01-09 09:04 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
>        "overview": ["Screen Wake Lock API"],
Cool, I think that works. It's about the best we've got atm

2024-01-09 09:08 UTC, chrisdavidmills commented on files/en-us/web/api/wakelocksentinel/released/index.md
> +The `WakeLockSentinel` is released when the associated platform screen wake lock is revoked, and then remains `true`.
fair, fair.

2024-01-09 09:09 UTC, chrisdavidmills approved these changes
Lovely work @hamishwillee! Let's get this merged.

2024-01-09 09:12 UTC, merged