onChanged callback object content clarification
mdn/content pull request #31227
Opened 2023-12-22 17:41 UTC by rebloor

### Description

Clarifies that the `storage.onChanged` callback triggered as a result of `storageArea.set` only returns changed details.

### Related issues and pull requests

Fixes #31203

2023-12-22 19:08 UTC, erosman commented
The issue had to be updated.
Please hold the PR.

Sorry for the inaccurate test results.

2023-12-23 16:41 UTC, rebloor commented
@erosman updated based on your issue revisions

2023-12-23 17:07 UTC, erosman commented
Just a note which may save some developers some time. 
Feel free to include something about it or not.

While Firefox storage `onChanged` (currently, see [Bug 1833153](https://bugzilla.mozilla.org/show_bug.cgi?id=1833153)) returns all the values and Chrome (currently) only the changed values, the target storage area still contains all the values e.g.

```js
// same for browser and chrome APIs
browser.storage.onChanged.addListener()
browser.storage.sync.onChanged.addListener()

// the following contains all the values passed to the storage sync, changed and unchanged
browser.storage.sync.get()
```

2023-12-25 16:43 UTC, rebloor commented
@erosman sorry, I'm unclear what the note about `get` would achieve if the developers were trying to observe changed keys.

2023-12-25 17:08 UTC, erosman commented
> @erosman sorry, I'm unclear what the note about `get` would achieve if the developers were trying to observe changed keys.


When developing a cross-browser-compatible extension, API inconsistency is a major concern. [1]
What I came up with in this case was to use `onChanged` as a trigger and then get all the values from `storage.sync.get()`, the same way Firefox returns `onChanged`.
While that is not necessary in all the cases, it is helpful in some cases (especially when a large values has to be segmented). [2]

I don't know if it is something worth mentioning or not, and feel free to disregard it.

Please also note 
1. [Inconsistency: storage onChanged](https://github.com/w3c/webextensions/issues/511)
2. [Proposal: Increase maximum item size in Storage sync quotas](https://github.com/w3c/webextensions/issues/510)

2024-02-28 16:26 UTC, jpmedley requested changes

2024-02-28 16:26 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/onchanged/index.md
> +Fired when {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}}, {{WebExtAPIRef('storage.StorageArea.remove','storageArea.remove')}}, or {{WebExtAPIRef('storage.StorageArea.clear','storageAr
```suggestion
Fired when {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}}, {{WebExtAPIRef('storage.StorageArea.remove','storageArea.remove')}}, or {{WebExtAPIRef('storage.StorageArea.clear','storageArea.clear')}} executes against a storage area, returning details of the changed keys. A callback is called only when there are changes to the underlying data.
```

2024-02-28 16:26 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/onchanged/index.md
> +> **Note:** In Firefox, the information returned includes all keys within the storage area {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}} ran against. Also, receiving a callback is pos
```suggestion
> **Note:** In Firefox, the information returned includes all keys within the storage area {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}} ran against. Also, a callback may be invoked when there is no change to the underlying data. Details of the changed items are found by examining each returned key's {{WebExtAPIRef('storage.StorageChange')}} object. See [Firefox bug 1833153](https://bugzil.la/1833153).
```

2024-02-28 16:26 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +Fires when one or more items in a storage area change, returning details for the keys that changed. Compared to {{WebExtAPIRef("storage.onChanged")}}, this event enables you to listen for changes in
So, Firefox can pass changes for multiple areas, but everyone else only does one at a time? Do I understand this correctly?

2024-02-28 16:26 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +> **Note:** In Firefox, the information returned includes all keys within the storage area. Also, receiving a callback is possible when there is no change to the underlying data. Details of the chang
```suggestion
> **Note:** In Firefox, the information returned includes all keys within the storage area. Also, the callback may be invoked when there is no change to the underlying data. Details of the changed items are found by examining each returned key's {{WebExtAPIRef('storage.StorageChange')}} object. See [Firefox bug 1833153](https://bugzil.la/1833153).
```

2024-03-01 02:23 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/storage/storagearea/onchanged/index.md
> +Fires when one or more items in a storage area change, returning details for the keys that changed. Compared to {{WebExtAPIRef("storage.onChanged")}}, this event enables you to listen for changes in
@jpmedley, as I understand it, the difference is that Firefox returns all the keys from the storage area, whereas other browsers only return the changed ones only.

2024-03-04 15:23 UTC, jpmedley requested changes
Sorry for the delay. I had a long weekend. I don't usually request multiple passes of changes. I'm making an exception because I think we need to clarify the difference between Firefox and other browsers.

2024-03-04 15:23 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/onchanged/index.md
> +Fired when {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}}, {{WebExtAPIRef('storage.StorageArea.remove','storageArea.remove')}}, or {{WebExtAPIRef('storage.StorageArea.clear','storageAr
```suggestion
Fired when {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}}, {{WebExtAPIRef('storage.StorageArea.remove','storageArea.remove')}}, or {{WebExtAPIRef('storage.StorageArea.clear','storageArea.clear')}} executes against a storage area, returning details of only changed keys. A callback is called only when there are changes to the underlying data.
```

2024-03-04 15:23 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/storage/onchanged/index.md
> +> **Note:** In Firefox, the information returned includes all keys within the storage area {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}} ran against. Also, a callback may be invoked w
```suggestion
> **Note:** In Firefox, the information returned includes all keys within the storage area {{WebExtAPIRef('storage.StorageArea.set','storageArea.set')}} ran against whether they changed or not. Also, a callback may be invoked when there is no change to the underlying data. Details of the changed items are found by examining each returned key's {{WebExtAPIRef('storage.StorageChange')}} object. See [Firefox bug 1833153](https://bugzil.la/1833153).
```

2024-03-04 16:20 UTC, jpmedley approved these changes

2024-03-04 16:20 UTC, merged