MediaRecorder control | update exception section &  remove unexpected section
mdn/content pull request #31238
Opened 2023-12-23 03:59 UTC by skyclouds2001

### Description

update *Exceptions* section in `MediaRecorder.start()`, remove those exceptions that throw through *error* event, not in the method call

update *Errors* section to *Exceptions* section, style update

remove some unexpected *Instance properties* section from some event pages

some other text update

### Motivation

### Additional details

### Related issues and pull requests

2024-01-19 22:19 UTC, wbamberg requested changes

2024-01-19 22:19 UTC, wbamberg commented on files/en-us/web/api/mediarecorder/resume/index.md
> +    {{domxref("MediaRecorder.state")}} is already "recording", `resume()` has no effect.
IMO it would be better to put "If {{domxref("MediaRecorder.state")}} is already "recording", `resume()` has no effect." at the end of the preamble (i.e. immediately before the "Syntax" H2). Because this isn't exception information.

2024-01-19 22:19 UTC, wbamberg commented on files/en-us/web/api/mediarecorder/start/index.md
> +    stream's tracks is in a format that cannot be recorded using the current configuration, or if the `videoKeyFrameIntervalDuration` and `videoKeyFrameIntervalCount` parameter are both specificed wh
Use bullets for better scannability:

```suggestion
  - : Thrown in any of the following cases:
      - The media stream you are attempting to record is inactive.
      - One or more of the stream's tracks is in a format that cannot be recorded using the current configuration.
      - The `videoKeyFrameIntervalDuration` and `videoKeyFrameIntervalCount` parameter are both specified when creating the `MediaRecorder`.
```

(sorry I didn't check my Markdown formatting here so please double check I didn't break it)

2024-01-20 19:35 UTC, wbamberg commented on files/en-us/web/api/mediarecorder/resume/index.md
> +If {{domxref("MediaRecorder.state")}} is "inactive", an `InvalidStateError` exception will be raised.
I only meant the sentence about `recording`. Exceptions should be documented in the "Exceptions" section.

2024-01-21 11:31 UTC, skyclouds2001 commented on files/en-us/web/api/mediarecorder/resume/index.md
> +
```suggestion
```

2024-01-22 22:53 UTC, wbamberg approved these changes
👍

2024-01-22 22:53 UTC, merged