HTMLInputElement | update inherit info & adjust member description
mdn/content pull request #31263
Opened 2023-12-24 05:10 UTC by skyclouds2001

### Description

fix - `inputmode` to `inputMode`

remove some inherit members and add inherit info

update members list

some other update

### Motivation

### Additional details

### Related issues and pull requests

2023-12-24 06:46 UTC, teoli2003 requested changes

2023-12-24 06:46 UTC, teoli2003 commented on files/en-us/web/api/htmlinputelement/index.md
> +  - : Returns / Sets the element's [`step`](/en-US/docs/Web/HTML/Element/input#step) attribute, which works with [`min`](/en-US/docs/Web/HTML/Element/input#min) and [`max`](/en-US/docs/Web/HTML/Eleme
I don't like the structure: `Returns / Sets`; it is esthetically not pleasing, challenging to read, and doesn't convey information.

While we are modifying this page (a welcomed need),  we should:

- Don't use _Returns / Sets_, avoid a verb in these cases for read-write cases: _The element's `step`…_ instead of _Returns / Sets the element's `step`_
- Don't_use _Represents_ either: _Aclient-side image map._ instead of _Represents a client-side image map._

For read-only values, using _Returns_ is fine, though.

2023-12-25 07:21 UTC, teoli2003 approved these changes
👍

2023-12-25 07:21 UTC, merged

2024-03-13 02:49 UTC, 05101115389 commented
[package-lock.json](https://github.com/mdn/content/files/14581241/package-lock.json)