init documentation for `HTMLLinkElement.crossOrigin`
mdn/content pull request #31277
Opened 2023-12-24 17:25 UTC by skyclouds2001

### Description

see the spec, https://html.spec.whatwg.org/multipage/semantics.html#attr-link-crossorigin and https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes

### Motivation

### Additional details

### Related issues and pull requests

Fixes https://github.com/mdn/browser-compat-data/issues/21695

2023-12-25 07:14 UTC, teoli2003 requested changes

2023-12-25 07:14 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/crossorigin/index.md
> +- `anonymous` or an empty string (`""`)
```suggestion
- `anonymous` or the empty string (`""`)
```

2023-12-25 07:14 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/crossorigin/index.md
> +A string of a keyword specifying the CORS mode to use when fetching the resource. Available values are:
```suggestion
A string of a keyword specifying the CORS mode to use when fetching the resource. Possible values are:
```

2023-12-25 07:14 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/crossorigin/index.md
> +  - : Requests sent by the {{domxref("HTMLLinkElement")}} will use the `cors` mode and the `same-origin` credentials mode. This means that CORS is enabled and credentials are sent _if_ the resource i
Can we link to something explaining mode, and credentials mode (like a property?)

2023-12-25 07:14 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/crossorigin/index.md
> +  - : Requests sent by the {{domxref("HTMLLinkElement")}} will use the `cors` mode and the `include` credentials mode. All resources requests by the element will use CORS, regardless of what domain t
Same here

2023-12-26 06:30 UTC, teoli2003 approved these changes
👍

2023-12-26 06:30 UTC, merged

2023-12-26 10:44 UTC, TheOldMan2000 commented
The credentials links on that page are all returning 404 errors. Same issue, document not written yet?

2023-12-26 12:23 UTC, skyclouds2001 commented
> The credentials links on that page are all returning 404 errors. Same issue, document not written yet?

Emmm, would you please list which link is inaccessible?

2023-12-26 14:51 UTC, TheOldMan2000 commented
Sorry,

Referring to all the credentials hyperlinks pointing to 
`https://pr31277.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Request/credentials `

2023-12-26 15:39 UTC, skyclouds2001 commented
This is because the preview result only build the pages that has been changed, that is, only the pages that has been updated can view in the preview result

so in this case, since `HTMLLinkElement.crossOrigin` is the only page that has been updated, only `HTMLLinkElement.crossOrigin` can view, any other page cann't view