pageAction API edits
mdn/content pull request #31405
Opened 2023-12-30 10:59 UTC by abitrolly

* pageAction is used to create Address bar button
* HTML, JavaScript and CSS is not the same (no ESM if I remember correctly)
* Listening for clicks is in a background script
* Access to web page DOM is only possible with a content script
* Link to browser action
* Link to content scripts

### Description

Adds missing information and clarifications.

### Motivation

I've created Page Action extension to interact with web page, and then discovered that Page Action code can not do this. Spent quite a lot of time discovering that, so I want to make these changes so that other save time.

### Additional details

### Related issues and pull requests

2024-01-02 17:38 UTC, jpmedley requested changes

2024-01-02 17:38 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md
> +The API to control [address bar button](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions), which is a clickable icon inside the browser's address bar.
A sentence fragment is acceptable and common for the first part of a definition, which this is. Keeping the original also says the same thing with fewer words, which is a writing best practice. Please change this back.

2024-01-02 17:38 UTC, jpmedley commented on files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md
> +If you specify a popup, you define its contents and behavior using HTML, CSS, and JavaScript. JavaScript running in the popup gets access to all the same WebExtension APIs as your background scripts.
```suggestion
If you specify a popup, you define its contents and behavior using HTML, CSS, and JavaScript. JavaScript running in the popup gets access to all the same WebExtension APIs as your background scripts. Despite being named `pageAction`, the action code doesn't get access to web page content. To access web page DOM, you need to add a [content script](/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) and interact with it.
```

2024-01-03 02:34 UTC, abitrolly commented on files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md
> +The API to control [address bar button](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions), which is a clickable icon inside the browser's address bar.
If I change it back, then it a reader will be unaware that the page action and address bar button are the same thing.

How about leaving only the first part?

`The API to control [address bar button](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions).`

2024-01-03 02:38 UTC, abitrolly commented on files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md
> +The API to control [address bar button](/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions), which is a clickable icon inside the browser's address bar.
@jpmedley I went with the last variant. The address bar button is already explained in the screenshot and on UI page.

2024-01-03 15:37 UTC, jpmedley approved these changes

2024-01-04 22:35 UTC, hamishwillee commented
Merging - approved by jpmedly yesterday

2024-01-04 22:35 UTC, merged