init docs for `HTMLElement.spellcheck`
mdn/content pull request #31441
Opened 2023-12-31 22:10 UTC by skyclouds2001

### Description

see https://html.spec.whatwg.org/multipage/interaction.html#dom-spellcheck

### Motivation

### Additional details

### Related issues and pull requests

2024-01-01 10:54 UTC, teoli2003 requested changes
Let's use a live example, maybe with a checkbox to trigger spell-checking.

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/index.md
> +  - : A boolean value that controls the [spell-checking](/en-US/docs/Web/HTML/Global_attributes/spellcheck) hint. It can be presented on all HTML elements, though it doesn't have an effect on all of
```suggestion
  - : A boolean value that controls the [spell-checking](/en-US/docs/Web/HTML/Global_attributes/spellcheck) hint. It is available on all HTML elements, though it doesn't affect all of them.
```

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +The **`spellcheck`** property of the {{domxref("HTMLElement")}} interface represents a boolean value that controls the [spell-checking](/en-US/docs/Web/HTML/Global_attributes/spellcheck) hint. It can
```suggestion
The **`spellcheck`** property of the {{domxref("HTMLElement")}} interface represents a boolean value that controls the [spell-checking](/en-US/docs/Web/HTML/Global_attributes/spellcheck) hint. It is available on all HTML elements, though it doesn't affect all of them.
```

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +A boolean value that is `true` if spell and grammar of the text content in the element may be be checked, `false` otherwise.
```suggestion
A boolean value that is `true` if the spelling and grammar of the text content in the element may be checked, `false` otherwise.
```

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +```js
Let's make this a live example.

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +if (!spellcheckElement.spellcheck) {
The test is useless

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +// the spell and grammar of text content in the element may be checked
Spell = magic, Spelling is the word you want

Let's start a comment with a capital letter.
```suggestion
// The spelling and grammar of text content in the element may be checked
```

2024-01-01 10:54 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +// the spell and grammar of text content in the element may not be checked
```suggestion
// The spelling and grammar of text content in the element may not be checked
```

2024-01-05 12:47 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +});
```suggestion
});

element.focus()
```

2024-01-05 12:50 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +element.focus()
```suggestion
controller.addEventListener("change", (e) => {
  if (controller.checked) {
    element.spellcheck = true;
    label.innerText = "The spelling and grammar may be checked:";
  } else {
    element.spellcheck = false;
    label.innerText = "The spelling and grammar will not be checked:";
  }
});
```

2024-01-05 12:50 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +</div>
```suggestion
```

2024-01-05 12:51 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +{{EmbedLiveSample('Examples', 600, 200)}}
```suggestion
{{EmbedLiveSample('Examples', 600, 200)}}

Note that you must enable the browser setting to check spelling and grammar.
```

2024-01-08 07:47 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +</div>
```suggestion
<div>
  <span id="sc-label">The spelling and grammar may be checked: </span>
  <span id="sc-element" contenteditable="true" spellcheck="true">test</span>
</div>
<input id="spellcheck-controller" type="checkbox" checked />Enable spelling and grammar check
```

2024-01-08 07:47 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +const controller = document.getElementById("spellcheck-controller");
```suggestion
const label = document.getElementById("sc-label");
const element = document.getElementById("sc-element");
const controller = document.getElementById("sc-controller");
```

2024-01-08 07:47 UTC, teoli2003 commented on files/en-us/web/api/htmlelement/spellcheck/index.md
> +});
```suggestion
controller.addEventListener("change", (e) => {
  if (controller.checked) {
    element.spellcheck = true;
    label.innerText = "The spelling and grammar may be checked: ";
  } else {
    element.spellcheck = false;
    label.innerText = "The spelling and grammar may not be checked: ";
  }
});
```

2024-01-08 07:49 UTC, teoli2003 approved these changes
Thank you!

2024-01-08 07:52 UTC, merged