Add HTMLLinkElement.href
mdn/content pull request #31462
Opened 2024-01-02 10:47 UTC by teoli2003

This adds the missing `HTMLLinkElement.href` page.

Part of the project to document all interoperable features ([mdn/discussions#476](https://github.com/orgs/mdn/discussions/476))

2024-01-03 13:20 UTC, skyclouds2001 commented on files/en-us/web/api/htmllinkelement/href/index.md
> +The **`HTMLLinkElement.href`** property of the {{domxref("HTMLLinkElement")}} interface contains a string that is the URL associated with the link.
```suggestion
The **`href`** property of the {{domxref("HTMLLinkElement")}} interface contains a string that is the URL associated with the link.
```

I think the style of *`property`* is better then *`interface.property`*

2024-01-03 14:03 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/href/index.md
> +The **`HTMLLinkElement.href`** property of the {{domxref("HTMLLinkElement")}} interface contains a string that is the URL associated with the link.
Oh yes, it was a bad cut and past from my side.

2024-03-28 02:40 UTC, wbamberg requested changes

2024-03-28 02:40 UTC, wbamberg commented on files/en-us/web/api/htmllinkelement/href/index.md
> +It reflects the `href` attribute of the {{HTMLElement("link")}} element and is the empty string (`""`) if there are none.
```suggestion
It reflects the `href` attribute of the {{HTMLElement("link")}} element. If the element does not have an `href` attribute, then this property's value is the empty string (`""`).
```

2024-03-28 02:40 UTC, wbamberg commented on files/en-us/web/api/htmllinkelement/href/index.md
> +**Note:** Either this property or {{domxref("HTMLLinkElement.imageSrcset", "imageSrcset")}} must not be empty.
```suggestion
> **Note:** Either this property or {{domxref("HTMLLinkElement.imageSrcset", "imageSrcset")}} must not be empty.
```

This is odd though because isn't this restriction about the HTML element, not the HTMLLinkElement interface? I mean I can do this:

```js
const s = document.createElement("link") 
s.href  // ""
s.imageSrcset  // ""
```

2024-07-01 21:18 UTC, wbamberg approved these changes
👍 thank you!

2024-07-01 21:18 UTC, merged