Removed line about perspective() needing to be listed first
mdn/content pull request #31486
Opened 2024-01-03 13:00 UTC by ydaniv

### Description

This line is not correct.
It does need to come before functions in 3D to properly apply to them, but the transform will still work if it's not listed first.
In some cases it's even necessary to insert other functions before it. E.g. manually applying a transform-origin without using `transform-origin`.

### Motivation

### Additional details

### Related issues and pull requests

2024-01-03 15:49 UTC, dipikabh requested changes
Hello @ydaniv, the statement is correct. For clarity, I've suggested to combine the sentence with the previous line because they're part of the same topic.

2024-01-03 15:49 UTC, dipikabh commented on files/en-us/web/css/transform/index.md
>  The `transform` property may be specified as either the keyword value `none` or as one or more `<transform-function>` values.
```suggestion
The `transform` property may be specified as either the keyword value `none` or as one or more `<transform-function>` values. If {{cssxref("transform-function/perspective", "perspective()")}} is one of the {{cssxref("&lt;transform-function&gt;")}} values, it must be listed first.
```
A few references I found which also state the same rule:
- https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-transforms#three-dimensional-transforms: "Unlike other transform function values, perspective must be declared first (leftmost) when there are multiple transform function values."
- https://www.freecodecamp.org/news/complete-guide-to-css-transform-functions-and-properties/: "List perspective() first whenever you chain it with other [CSS transform functions](https://codesweetly.com/web-tech-terms-c#css-transform-functions). Otherwise, browsers might transform the selected element incorrectly."

2024-01-03 18:58 UTC, ydaniv commented on files/en-us/web/css/transform/index.md
>  The `transform` property may be specified as either the keyword value `none` or as one or more `<transform-function>` values.
@dipikabh can you find one place in the specs that claim this? I could not.
The links you provided are interesting but they are not specs.
It's a good advice for devs to place `perspective()` before the rest of the functions for it to take effect properly, but it's not necessary.
Here's an example where this is needed and working: https://jsbin.com/paceweyuba/edit?css,output
And BTW, this works consistently on Firefox, Safari, and Chrome.

2024-01-04 02:48 UTC, dipikabh commented on files/en-us/web/css/transform/index.md
>  The `transform` property may be specified as either the keyword value `none` or as one or more `<transform-function>` values.
Transform specifications is the first place I checked and I did not find any reference to validate that requirement, leading me to explore other sources. I agree that on MDN, we should be closer to the spec.

As you've noted, it is more of an advice. Could we then rephrase that sentence as a recommendation rather than a rule? This way, we'd also be making devs aware to look out for the placement of `perspective()` in the list to achieve the desired effect in various situations. We can probably add this as a "Note".

Thanks for sharing the example code.

2024-01-04 06:07 UTC, estelle commented on files/en-us/web/css/transform/index.md
>  The `transform` property may be specified as either the keyword value `none` or as one or more `<transform-function>` values.
Before transforms were fully supported, the `perspective()` had to be listed first or it had no effect. This legacy content may no longer be valid.

2024-01-04 14:32 UTC, dipikabh approved these changes
Thanks for flagging this sentence for removal, @ydaniv! 👍

2024-01-04 14:32 UTC, merged