Update template element description and add shadowrootmode attribute
mdn/content pull request #31490
Opened 2024-01-03 15:10 UTC by pepelsbey

⚠️ This is a draft because the demo doesn’t work with client-side rendered playground yet

### Description

Declarative shadow DOM reuses the `<template>` element for generating shadow root in the presence of the `shadowrootmode` attribute. This element is no longer for templating only, that needs to be reflected, too.

### Motivation

To support existing implementations in Chrome and Safari and prepare for the upcoming Firefox support.

### Related issues and pull requests

- https://github.com/mdn/content/issues/31102

2024-01-18 01:07 UTC, estelle commented on files/en-us/web/html/element/template/index.md
> +The **`<template>`** [HTML](/en-US/docs/Web/HTML) element is a mechanism for holding {{Glossary("HTML")}} fragments for two main use cases:
Drive by comment: I was reviewing #31577, so was looking for a good `shadowrootmode` explanation, but am not currently reviewing this PR. That said....

The first sentence of each /mdn/content/ page is used as the "summary" by Yari macros and some external sites/software, so I think it may be best to not end in a colon leading into a list as it might get rendered in an unexpected way. See /yari/build/extract-summary.ts for the script that creates the summary.

How about something like:

```suggestion
The **`<template>`** [HTML](/en-US/docs/Web/HTML) element is a mechanism for holding {{Glossary("HTML")}} fragments that can be cloned and inserted in the document by script. The `<template>` element can be used in two ways:
```
In this, I changed "main uses" to "used in two ways" because I think the first is the main use case, but maybe the latter is a main case too. I have not followed this discussion so may be wrong. For now, we can't say "main" though because its not yet fully supported, so, it may become main, but isn't there yet.

Here's a rough draft of an alternative intro (all the way up to attributes): The last paragraph is full of links, but i think this is the gist of the purpose of the template element and needs to be said somehow....

```md
The **`<template>`** [HTML](/en-US/docs/Web/HTML) element is a mechanism for holding {{Glossary("HTML")}} to be instantiated during runtime using JavaScript, rather than rendered immediately when a page is loaded, or to generate a Shadow DOM, or both.

By default, the element's contents are not rendered, only parsed, into a [document fragment](/en-US/docs/Web/API/DocumentFragment). If the `shadowrootmode` attribute is present and set to `open`, the element is replaced in the DOM by its content wrapped in a [shadow root](/en-US/docs/Glossary/Shadow_tree). In this case, the contents of the `<template>` element are rendered in place.

The `<template>` element can be used to [create custom elements](link_to_tutorial_or_example_below) with the elements' contents being the snippet of HTML markup that make up the custom element, with the contents being [cloned](/en-US/docs/Web/API/Node/cloneNode) and inserted into the DOM with JavaScript. Generally, with the [content](/en-US/docs/Web/API/HTMLTemplateElement/content) [appended](/en-US/docs/Web/API/Node/appendChild) to each custom element [attaching a shadow DOM](/en-US/docs/Web/API/Element/attachShadow).
```

2024-01-18 12:58 UTC, pepelsbey commented on files/en-us/web/html/element/template/index.md
> +The **`<template>`** [HTML](/en-US/docs/Web/HTML) element is a mechanism for holding {{Glossary("HTML")}} fragments for two main use cases:
@estelle Thank you for the idea. I tried to self-contain the intro and changed use-cases wording to fit. I don’t think we should shy away from describing declarative shadow DOM’s use case on MDN: it will be shipped in Firefox 123 (enabled by default) and already available in Chrome and Safari.

2024-01-18 16:13 UTC, dipikabh requested changes
Thanks for these updates, @pepelsbey!
I've done primarily an edit review and added some suggestions :)

2024-01-18 16:13 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +### Table row generation
Thanks for adding a title for this example! I'd suggest user action-based titles:
```suggestion
### Generating table rows
```

2024-01-18 16:13 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +### Declarative shadow DOM
what about:
```suggestion
### Implementing a declarative shadow DOM
```

2024-01-18 16:13 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +At the beginning of the markup, we have a hidden support warning that we will show later via JavaScript if the browser doesn't support the `shadowrootmode` attribute. After that, there are two {{HTML
Just a style preference to make the sentences more compact
```suggestion
In this example, a hidden support warning is included at the beginning of the markup. This warning is later set to be displayed via JavaScript if the browser doesn't support the `shadowrootmode` attribute. Next, there are two {{HTMLElement("article")}} elements, each containing nested {{HTMLElement("style")}} elements with different behaviors. The first `<style>` element is global to the whole document. The second one is scoped to the shadow root generated in place of the `<template>` element because of the presence of the `shadowrootmode` attribute.
```

2024-01-18 16:13 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +    <p>I'm in the Shadow DOM.</p>
```suggestion
    <p>I'm in the shadow DOM.</p>
```

2024-01-18 16:13 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +- [Introduction to declarative shadow DOM](https://developer.chrome.com/docs/css-ui/declarative-shadow-dom)
We have a [few guidelines](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide#see_also_section) for when we add external links to "See also", namely specifying the source site, mentioning the last update date and matching the title of the external page but still following sentence casing on MDN
```suggestion
- [Declarative shadow DOM](https://developer.chrome.com/docs/css-ui/declarative-shadow-dom) on developer.chrome.com (2023)
```

2024-01-19 09:50 UTC, pepelsbey commented
@dipikabh thank you for the great suggestions! I applied them all :)

2024-01-19 15:23 UTC, dipikabh requested changes
Thanks for the updates, @pepelsbey!

I have a few more suggestions.

2024-01-19 15:23 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +2. If the element contains the `shadowrootmode` attribute, the HTML parser will immediately generate a shadow DOM. The element is replaced in the DOM by its content wrapped in a [shadow root](/en-US/
Reconsidering these two points.
- Can we move this content to the "Usage notes" section (before the "The corresponding `HTMLTemplateElement` interface" paragraph)? This is basically a more detailed explanation of the one-liner introductory para.
- Also, the first sentence describes the default state and then there are two possibilities. Can we reword this to be explicit about what users can do? What do you think about:
```suggestion
By default, an element's content is not rendered, only parsed into a [document fragment](/en-US/docs/Web/API/DocumentFragment). You can use this fragment in the following ways:
- If you use the {{domxref("HTMLTemplateElement.content", "content")}} property in JavaScript, you can clone this fragment via the {{domxref("Node.cloneNode", "cloneNode")}} method and insert it into the DOM.
- If you add the `shadowrootmode` attribute to the element, the HTML parser will immediately generate a shadow DOM. The element is replaced in the DOM by its content wrapped in a [shadow root](/en-US/docs/Glossary/Shadow_tree).
```

2024-01-19 15:23 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
I was wondering if we could link to the documentation for `shadowroot` attribute  because the BCD table could indicate the browser support. But we don't have this attribute on MDN. In that case, maybe we shouldn't add this note here specifically for Chrome.

2024-01-24 16:52 UTC, pepelsbey commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
This is something worth mentioning because the previous Chrome-only implementation of the declarative shadow DOM has been around for two years with a polyfill as an option for non-supporting browsers. Now that all browsers have this attribute's new version, there might still be the old version in some projects’ code. I want this information to be available here.

By the way, it’s actually [mentioned](https://github.com/mdn/browser-compat-data/blob/main/html/elements/template.json#L49) in BCD.

2024-01-24 17:02 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
> This is something worth mentioning because the previous Chrome-only implementation of the declarative shadow DOM has been around for two years with a polyfill as an option for non-supporting browsers.

👍 This is helpful, thanks! Agree to keep this note with this context

> By the way, it’s actually [mentioned](https://github.com/mdn/browser-compat-data/blob/main/html/elements/template.json#L49) in BCD.

Good one! More support for keeping that note then!

2024-01-24 17:04 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
What do you think about creating two separate note boxes though? The first one is about parsing and the second one is a completely different topic, about `shadowroot`.

2024-01-24 17:05 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +2. If the element contains the `shadowrootmode` attribute, the HTML parser will immediately generate a shadow DOM. The element is replaced in the DOM by its content wrapped in a [shadow root](/en-US/
This content is now repeated twice, once at the top and second time in "Usage notes". Did you want to keep it only at the top of the page?

2024-01-24 17:15 UTC, pepelsbey commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
Good point! Done :)

2024-01-24 18:06 UTC, dipikabh commented on files/en-us/web/html/element/template/index.md
> +    > You may find the non-standard `shadowroot` attribute in older tutorials and examples that used to be supported in Chrome 90-110. This attribute has since been removed and replaced by the standa
Thanks!

2024-01-25 03:35 UTC, estelle commented on files/en-us/web/html/element/template/index.md
> +  - : Creates a [shadow root](/en-US/docs/Glossary/Shadow_tree) for the parent element. It is a declarative version of the {{domxref("Element.attachShadow()")}} method and accepts the same values.
```suggestion
  - : Creates a [shadow root](/en-US/docs/Glossary/Shadow_tree) for the parent element. It is a declarative version of the {{domxref("Element.attachShadow()")}} method and accepts the same {{glossary("enumerated")}} values.
```

2024-01-25 10:28 UTC, pepelsbey commented on files/en-us/web/html/element/template/index.md
> +2. If the element contains the `shadowrootmode` attribute, the HTML parser will immediately generate a shadow DOM. The element is replaced in the DOM by its content wrapped in a [shadow root](/en-US/
Oh, I guess I merged something wrong. Now it’s only in usage notes. Thanks!

2024-01-25 13:50 UTC, dipikabh approved these changes
Thank you @pepelsbey for all the updates! 👍

2024-01-25 13:50 UTC, merged