Clarify expected output in all cases
mdn/content pull request #31510
Opened 2024-01-04 11:40 UTC by damon314159

### Description

This PR adds a small clarification to the expected outcome from one of the exercises without giving away the solution.

### Motivation

The exercise eludes to use of the modulo operator to test for divisibility, but the linked guide does not clarify that zero is a positive result for this test and non zero is a negative result. Newcomers, while understanding division, may not understand how this relates to the modulo operator without a prompt as to expected results. Informing them that they should store 0 for even and 1 for odd, combined with the link to the page containing info that includes modulo, should be sufficient for the non mathematically inclined to piece together the method for themselves, without being too easy, or telling them which operator is required.

### Additional details

### Related issues and pull requests

2024-01-16 00:24 UTC, damon314159 commented
I'm not sure if I did this right - can someone let me know if there was something else I was supposed to do before someone will review it?

2024-02-02 19:45 UTC, dipikabh requested changes

2024-02-02 19:45 UTC, dipikabh commented on files/en-us/learn/javascript/first_steps/test_your_skills_colon__math/index.md
> +5. Check if `finalResult` is an even number using one of the [arithmetic operators](/en-US/docs/Learn/JavaScript/First_steps/Math#arithmetic_operators). Store the result (0 for even, 1 for odd) in a
```suggestion
5. Check if `finalResult` is an even number using one of the [arithmetic operators](/en-US/docs/Learn/JavaScript/First_steps/Math#arithmetic_operators). Store the result (`0` for even, `1` for odd) in a variable called `evenOddResult`.
```

2024-02-02 19:50 UTC, dipikabh approved these changes
This is a good clarification to add. Thank you @damon314159 👍

2024-02-02 19:50 UTC, merged

2024-02-02 19:51 UTC, dipikabh commented
Congratulations on landing your first PR here!
Welcome to the MDN project 🎉