initial documentation for HtmlLinkElement.hreflang
mdn/content pull request #31517
Opened 2024-01-05 06:27 UTC by ShubhamOulkar

This adds the missing HTMLLinkElement.hreflang page.

resource link
[hreflang](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-hreflang)

Part of the project to document all interoperable features ([mdn/discussions#476](https://github.com/orgs/mdn/discussions/476))

2024-01-05 20:39 UTC, dawei-wang reviewed
add missing word

2024-01-05 20:39 UTC, dawei-wang commented on files/en-us/web/api/htmllinkelement/hreflang/index.md
> +The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} interface has same semantics as {{domxref("HTMLAnchorElement.hreflang")}} property.
```suggestion
The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} interface has the same semantics as {{domxref("HTMLAnchorElement.hreflang")}} property.
```

2024-01-06 07:17 UTC, teoli2003 requested changes

2024-01-06 07:17 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/hreflang/index.md
> +The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} interface has the same semantics as the {{domxref("HTMLAnchorElement.hreflang")}} property.
We should explain it rather than link. That way,

- web devs don't need an extra link
- eventual tiny differences can be explained

This semantics is unlikely to change in the future, so this doesn't add any burden to maintain it.

2024-01-06 08:00 UTC, ShubhamOulkar commented on files/en-us/web/api/htmllinkelement/hreflang/index.md
> +The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} interface has the same semantics as the {{domxref("HTMLAnchorElement.hreflang")}} property.
I try to explain use case

2024-01-10 09:33 UTC, teoli2003 approved these changes

2024-01-10 09:33 UTC, teoli2003 commented on files/en-us/web/api/htmllinkelement/hreflang/index.md
> +The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} is used to indicate the language and the geographical targeting of a page. This improves SEO(Search Engine Optimization).
```suggestion
The **`hreflang`** property of the {{domxref("HTMLLinkElement")}} is used to indicate the language and the geographical targeting of a page. This hint can be used by browsers to select the more appropriate page or to improve {{Glossary("SEO")}}.
```

2024-01-10 09:35 UTC, merged