initial document for HTMLAnchorElement.hreflang
mdn/content pull request #31512
Opened 2024-01-04 12:33 UTC by ShubhamOulkar

This adds the missing HTMLAnchorElement.hreflang page.

Part of the project to document all interoperable features ([mdn/discussions#476](https://github.com/orgs/mdn/discussions/476))

2024-01-04 12:52 UTC, teoli2003 requested changes
Thank you very much. I propose a few changes, but this is close to be ready to land.

2024-01-04 12:52 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +The **`hreflang`** property of the {{domxref("HTMLAnchorElement")}} interface contains a string that is the language of the linked resource.
```suggestion
The **`hreflang`** property of the {{domxref("HTMLAnchorElement")}} interface is a string that is the language of the linked resource.
```

2024-01-04 12:52 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +Web browsers and search engines may use this information to better understand the language of the linked content, but they are not required to follow it. The value provided for the `hreflang` attribu
```suggestion
Web browsers and search engines may use this information to understand the language of the linked content better, but they are not required to follow it. The value provided for the `hreflang` attribute adheres to the format defined in {{RFC(5646, "Tags for Identifying Languages (also known as BCP 47)")}}. If not, it is ignored.
```

2024-01-04 12:52 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +Despite the presence of the `hreflang` attribute, web browsers are instructed not to rely solely on this when fetching the linked resource. Instead, they should use language information directly asso
```suggestion
Web browsers do not rely solely on the `hreflang` attribute after fetching the linked resource. Instead, they use language information directly associated with the resource (e.g., through HTTP headers) to determine its language.
```

2024-01-04 12:52 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +
I think we can quickly transform this into a live example. Can you do it, please?

2024-01-04 12:54 UTC, teoli2003 commented
Do you want to add it to the property list of `HTMLAnchorElement` in this PR or in separate one?

2024-01-04 13:13 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +
ok I will do it.

2024-01-05 03:14 UTC, ShubhamOulkar commented
@teoli2003 property is already listed on [HTMLAnchorElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement#instance_properties) page. 
I this only `ping` is not listed. we need small update in [google docs](https://docs.google.com/spreadsheets/d/1lvITVZJM8dx8s_Kee5UNI1hDfPNF0gXQwjPop5xIF5E/edit#gid=369545647)

2024-01-05 05:23 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlanchorelement/hreflang/index.md
> +
@teoli2003 live example is updated

2024-01-06 07:13 UTC, teoli2003 commented
(In the future, when a PR is ready for a re-review) click on the re-review button, so I get notified)
![Capture d’écran 2024-01-06 à 08 13 14](https://github.com/mdn/content/assets/1466293/2f9fc21b-62b1-4580-9518-7edc34f04e25)

2024-01-06 07:13 UTC, teoli2003 approved these changes
👍 Thank you very much!

2024-01-06 07:13 UTC, merged

2024-01-06 07:27 UTC, ShubhamOulkar commented
> (In the future, when a PR is ready for a re-review) click on the re-review button, so I get notified) ![Capture d’écran 2024-01-06 à 08 13 14](https://private-user-images.githubusercontent.com/1466293/294656786-2f9fc21b-62b1-4580-9518-7edc34f04e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjYyMjcsIm5iZiI6MTcwNDUyNTkyNywicGF0aCI6Ii8xNDY2MjkzLzI5NDY1Njc4Ni0yZjlmYzIxYi02MmIxLTQ1ODAtOTUxOC03ZWRjMzRmMDRlMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDZUMDcyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlmM2Q2YWRhYjhjNmJiMmNlY2FhZWRjY2M2NjhhZjFjMzkyNmU3ZWM4ZDRlODU4N2FiYWNmMzJhMjFjMTIyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RWh6Luxb_Pvui0iAA1ffjMMb8mWG-jQ3opXF1EHe9YE)

sure @teoli2003.

2024-01-06 07:27 UTC, ShubhamOulkar commented
> 👍 Thank you very much!