fix broken links and update the description of iterators
mdn/content pull request #31522
Opened 2024-01-05 12:32 UTC by yin1999

### Description

fix broken links and update the description of iterators.

In WebIDL, some iterators have been marked using `iterator<>` notation.

2024-01-05 12:33 UTC, yin1999 commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +> 2. Outside the webidl file, in the prose accompanying it. Such a prose is in the spec and usually has a sentence like this: _"The [value pairs to iterate over](https://webidl.spec.whatwg.org/#dfn-v
from [this example](https://webidl.spec.whatwg.org/#example-d2254660)

2024-01-05 15:28 UTC, dipikabh requested changes
Thanks for the link updates, @yin1999! I have a few suggestions for the text changes.

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
>  - `keys()` that returns an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the keys. E.g. {{domxref('FormData.keys()')}}
To make it similar to the verbiage in the "Value iterator" section
```suggestion
- `entries()`, which returns an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the value pairs. For example, see {{domxref('FormData.entries()')}}.
- `values()`, which returns an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the values. For example, see {{domxref('FormData.values()')}}.
- `keys()`, which returns an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the keys. For example, see {{domxref('FormData.keys()')}}.
```

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- `forEach()` that generates an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the value pairs, and then calls a given callback function one for each entry in the list. E.g
Same comment for `forEach()` here as in the "Value iterator" section

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +> **Note:** the value pairs to iterate over can be defined in two different ways:
```suggestion
> **Note:** The value pairs to iterate over can be defined in one of the following ways:
```

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +> 2. Outside the webidl file, in the prose accompanying it. Such a prose is in the spec and usually has a sentence like this: _"The [value pairs to iterate over](https://webidl.spec.whatwg.org/#dfn-v
Same edits can be applied as suggested above

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +The keyword `void` means that there is no return value. It is not a return value type. If the WebIDL entry reads `void`, the _Return value_ section in the docs should simply contain a sentence "None
To keep continuity from the previous paragraph, suggesting a change to phrasing of the first sentence:
```suggestion
If the return value is the `void` keyword, it means that there is no return value. It is not a return value type. If the WebIDL entry reads `void`, the _Return value_ section in the docs should simply state "None (\{{jsxref("undefined")}}).".
```

2024-01-05 15:28 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +The return value type is indicated before the method name — in the above case the value is an object of type `DOMString`. If followed by a question mark (`'?'`), a value of `null` can be returned too
```suggestion
The return value type is indicated before the method name — in the above case the value is an object of type `DOMString`. If the return type is followed by a question mark (`'?'`), a value of `null` can be returned too, and the documentation must explain _when_ this may happen. If no question mark is present, like here, the return value can't be `null`.
```

2024-01-06 01:13 UTC, yin1999 commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +- `forEach()`, which generates an [`iterator`](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) on the values, and then calls a given callback function one for each entry in the list.
According to the specification, the `forEach()` method does generate an iterator, but it is indeed clearer to modify it this way, developers do not need to care about how this method is implemented :)

2024-01-06 01:14 UTC, yin1999 commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.md
> +> **Note:** the value pairs to iterate over can be defined in three different ways:
I think we can remove the notecard highlighting, I'll do this

2024-01-06 04:23 UTC, dipikabh approved these changes
Changes look good. Thanks for these improvements, @yin1999!

2024-01-06 04:23 UTC, merged