intro and see also for export parts
mdn/content pull request #31599
Opened 2024-01-09 04:08 UTC by estelle

An example is currently being added in https://github.com/mdn/content/pull/28649. This adds a see also and improves the introduction.

2024-01-12 16:01 UTC, dipikabh requested changes
Thanks for the improvements @estelle. I've added my suggestions

2024-01-12 17:52 UTC, estelle commented
Thank you @dipikabh

2024-01-12 19:26 UTC, dipikabh requested changes
A few more tweaks needed

2024-01-12 19:26 UTC, dipikabh commented on files/en-us/web/html/global_attributes/exportparts/index.md
> +The global [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute makes a shadow tree element visible to its parent DOM. The {{CSSxRef("::part", "::part()")}} pseudo-element, with the part n
- The second sentence is introducing the pseudo-element abruptly. I recommend that we start the sentence with `part` to keep the continuity.
- This sentence "As the `::part()` pseudo-element is only visible to the parent DOM, when a shadow tree is nested, the parts are not visible to any ancestors other than the direct parent." is pretty long. I suggest we split it.
- Truncating the last sentence to avoid repetition with the next para
```suggestion
The global [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute makes a shadow tree element visible to its parent DOM. Using the `part` name as the parameter, the {{CSSxRef("::part", "::part()")}} pseudo-element can then be used to apply CSS styles to elements in the shadow tree from outside of it. However, the `::part()` pseudo-element is only visible to the parent DOM. This means that when a shadow tree is nested, the parts are not visible to any ancestors other than the direct parent. The `exportparts` attribute solves this limitation.
```

2024-01-12 19:26 UTC, dipikabh commented on files/en-us/web/html/global_attributes/exportparts/index.md
> +The global attribute [`part`](/en-US/docs/Web/HTML/Global_attributes#part) makes a shadow tree element visible to its parent DOM. The `part` attribute is assigned to an element in the shadow tree wit
This needs a bit more work

2024-01-12 19:26 UTC, dipikabh commented on files/en-us/web/html/global_attributes/exportparts/index.md
> +The `exportparts` attribute enables shadow tree parts to be visible outside the shadow DOM. This concept is referred to as "exporting". The `exportparts` attribute is placed on the element's _shadow
The last sentence can be simplified and made more clear
```suggestion
The `exportparts` attribute enables shadow tree parts to be visible outside the shadow DOM. This concept is referred to as "exporting". The `exportparts` attribute is placed on the element's _shadow host_, which is the element to which the _shadow tree_ is attached. The value of this attribute is a comma-separated list of `part` names present in the shadow tree. These names are made available to the DOMs outside the current structure.
```

2024-01-15 06:28 UTC, estelle commented on files/en-us/web/html/global_attributes/exportparts/index.md
> +The global [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute makes a shadow tree element visible to its parent DOM. Using the `part` name as the parameter, the {{CSSxRef("::part", "::pa
```suggestion
The global [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute makes a shadow tree element visible to its parent DOM. A `part` name is used as the parameter of the {{CSSxRef("::part", "::part()")}} pseudo-element. In this way, you can apply CSS styles to elements in the shadow tree from outside of it. However, the `::part()` pseudo-element is only visible to the parent DOM. This means that when a shadow tree is nested, the parts are not visible to any ancestors other than the direct parent. The `exportparts` attribute solves this limitation.
```

2024-01-15 21:19 UTC, dipikabh approved these changes
Thank you for the updates, @estelle!

2024-01-15 21:19 UTC, merged