update `{HTMLElement,SVGElement,MathMLElement}.style` live example | use for-of than for-in
mdn/content pull request #31631
Opened 2024-01-10 08:18 UTC by skyclouds2001

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-11 20:29 UTC, dipikabh requested changes

2024-04-11 20:29 UTC, dipikabh commented on files/en-us/web/api/htmlelement/style/index.md
> +    if (Number.isNaN(Number.parseInt(prop))) {
Before or if we add this check, we need to explain in prose the reason to check for numeric indices. Also, how common is it to encounter scenarios where `element.style` includes numeric indices or non-CSS properties? We can choose to keep the code simple and focused. Do you know if we mention in docs anywhere that `CSSStyleDeclaration` accessed via `element.style` can include numeric indices or strings?

2024-04-11 20:29 UTC, dipikabh commented on files/en-us/web/api/htmlelement/style/index.md
> +{{EmbedLiveSample("Getting_style_information", "100", "200")}}
The previous height of the result frame was okay. In fact, `200` adds a lot of empty space at the end in the output.

2024-04-11 20:36 UTC, dipikabh commented
Hi @skyclouds2001, thank you for waiting for the review of this PR.

I've left some comments and questions for you. I'm not sure we need the changes proposed in this PR.
We really value your contributions and effort. Please take a look and let me know your thoughts before I close the PR.

2024-04-12 03:42 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/style/index.md
> +{{EmbedLiveSample("Getting_style_information", "100", "200")}}
OK

2024-04-12 03:46 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/style/index.md
> +{{EmbedLiveSample("Getting_style_information", "100", "200")}}
```suggestion
{{EmbedLiveSample("Getting_style_information", "100", "115")}}
```

2024-04-12 03:46 UTC, skyclouds2001 commented on files/en-us/web/api/mathmlelement/style/index.md
> +{{EmbedLiveSample("Getting_style_information", "100", "200")}}
```suggestion
{{EmbedLiveSample("Getting_style_information", "100", "130")}}
```

2024-04-12 03:46 UTC, skyclouds2001 commented on files/en-us/web/api/svgelement/style/index.md
> +{{EmbedLiveSample("Getting_style_information", "100", "200")}}
```suggestion
{{EmbedLiveSample("Getting_style_information", "100", "130")}}
```

2024-04-12 04:07 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/style/index.md
> +    if (Number.isNaN(Number.parseInt(prop))) {
for example, the element below:

![image](https://github.com/mdn/content/assets/95597335/bad047d5-a75f-4dca-8dd8-53d635f62cf7)

the `style` property of the element is:

![image](https://github.com/mdn/content/assets/95597335/068f1f9b-5e18-4a2b-92b7-ac9ad980b654)

2024-04-12 04:34 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/style/index.md
> +// We loop through all styles
the difference is that

![image](https://github.com/mdn/content/assets/95597335/3365f1c6-9e05-4e91-8264-e16bf96d1805)

2024-04-12 04:37 UTC, skyclouds2001 commented on files/en-us/web/api/htmlelement/style/index.md
> +// We loop through all styles
but the origin comment is confusing, because for…of is able to use to loop through all styles

2024-04-15 18:25 UTC, dipikabh requested changes
Thanks, @skyclouds2001, for the updates and clarifications. I've suggested a few edits to the code comments.

2024-04-15 18:25 UTC, dipikabh commented on files/en-us/web/api/htmlelement/style/index.md
> +  // (the style directly defined via HTML style attribute)
```suggestion
  // We check if the property belongs to the CSSStyleDeclaration instance
  // We also ensure that the property is a numeric index (indicating an inline style)
```

2024-04-16 16:03 UTC, dipikabh approved these changes
Thanks a lot for landing these improvements, @skyclouds2001! Well done 🎉

2024-04-16 16:03 UTC, merged