Update index.md, rearrange alphabetically and add `dvw`, `dvh`, `lvh`, `lvw`, `svh`, and `svw`.
mdn/content pull request #31641
Opened 2024-01-10 18:50 UTC by francescorn

### Description

I am adding `dvw`, `dvh`, `lvh`, `lvw`, `svh`, and `svw`. I am rearranging the information alphabetically, unless there is a reason for previous organization.

### Motivation

It is easier to read and I am adding back the information on `dvw`, `dvh`, `lvh`, `lvw`, `svh`, and `svw`.

### Additional details

### Related issues and pull requests

Relates to #31617.

2024-01-11 21:13 UTC, dipikabh requested changes

2024-01-11 21:13 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
> +| `rem`  | [`font size`](/en-US/docs/Web/CSS/font-size) of the root element.                                                                       |
same comment
```suggestion
| `rem`  | Font size of the root element's font.                                                                       |
```

2024-01-11 21:13 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
> +| `rlh`  | [`line height`](/en-US/docs/Web/CSS/line-height) of the root element.                                                                   |
same comment as above

2024-01-11 21:13 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
>  | `vh`   | 1% of viewport's height.                                 |
These two should be moved down if we're going in alphabetical order

2024-01-11 21:13 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
> +| `dvw`  | 1% of the [dynamic viewport's](en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport) width. |
These can be linked to "/en-US/docs/Web/CSS/length#dynamic". Also, the link need only be on "dynamic"
```suggestion
| `dvh`  | 1% of the [dynamic](/en-US/docs/Web/CSS/length#dynamic) viewport's height. |
| `dvw`  | 1% of the [dynamic](/en-US/docs/Web/CSS/length#dynamic) viewport's width. |
```
- Similarly, the links below can be changed to /en-US/docs/Web/CSS/length#large, /en-US/docs/Web/CSS/length#small, and /en-US/docs/Web/CSS/CSS_logical_properties_and_values#inline_dimension
- Notice that there should be leading `/` that's currently missing in the slugs below

2024-01-13 00:18 UTC, francescorn commented
I fixed all the issues.

2024-01-13 00:32 UTC, francescorn commented
I fixed the above requests @dipikabh

2024-01-13 01:06 UTC, francescorn commented
I made the suggested changes.

2024-01-15 21:44 UTC, dipikabh requested changes
Thanks, @francescorn!

I've pointed a few more instances that can be fixed similar to the previous comment.
I'd appreciate if you can also look at the linting errors to make this PR mergable. Thank you!

2024-01-15 21:44 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
> +| `lvw`, | 1% of the [large viewport's](en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport) width. |
- The links can be updated to the specific section
- There is a straggling `,` after `lvw`

```suggestion
| `lvh`  | 1% of the [large](/en-US/docs/Web/CSS/length#large) viewport's height. |
| `lvw` | 1% of the [large](/en-US/docs/Web/CSS/length#large) viewport's width. |
```

2024-01-15 21:44 UTC, dipikabh commented on files/en-us/web/css/css_values_and_units/index.md
> +| `svw`  | 1% of the [small viewport's](en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport) width. |
```suggestion
| `svh`  | 1% of the [small](/en-US/docs/Web/CSS/length#small) viewport's height. |
| `svw`  | 1% of the [small](/en-US/docs/Web/CSS/length#small) viewport's width. |
```

2024-01-16 14:27 UTC, dipikabh approved these changes
Thank you, @francescorn 👍 

That was some messy linting with tables. Thank you for resolving those errors!

2024-01-16 14:27 UTC, merged

2024-01-16 22:15 UTC, francescorn commented
I will be more careful with linting.