Move Web/API/Houdini to Web/API/Houdini_APIs | fix the reference bug
mdn/content pull request #31677
Opened 2024-01-12 07:24 UTC by skyclouds2001

### Description

in https://developer.mozilla.org/en-US/docs/Web/API, the Houdini is a broken link:

![image](https://github.com/mdn/content/assets/95597335/db3c487c-7d92-4495-a6da-2b7b8d528ff7)

this is because the *overview* key does not match the summary page

![image](https://github.com/mdn/content/assets/95597335/47a2e391-cd07-408c-9d9e-7b0a3cd96817)

### Motivation

### Additional details

### Related issues and pull requests

2024-01-12 08:48 UTC, chrisdavidmills requested changes
Thanks for the update @skyclouds2001. The change largely makes sense to me, although I've made some suggestions that would make the link text more consistent.

I also think we should get @estelle's blessing on this one — it was her that moved the Houdini landing page under `/APIs` recently, as part of the project to remove the `/Guide` tree.

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/glossary/houdini/index.md
> +- [Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/api/css_object_model/index.md
> +- [Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/api/css_painting_api/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/api/css_properties_and_values_api/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/css/@property/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/css/@property/inherits/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/css/@property/initial-value/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/css/@property/syntax/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-12 08:48 UTC, chrisdavidmills commented on files/en-us/web/css/css_properties_and_values_api/index.md
> +- [CSS Houdini](/en-US/docs/Web/API/Houdini_APIs)
```suggestion
- [Houdini APIs](/en-US/docs/Web/API/Houdini_APIs)
```

2024-01-17 10:26 UTC, chrisdavidmills approved these changes
Let's just get this one merged; I don't think there is anything too controversial in here, thinking about it some more. Sorry for the delay.

2024-01-17 12:49 UTC, merged

2024-01-18 19:32 UTC, estelle commented
Thanks!