fix(html): add usage section to 'autocomplete' page
mdn/content pull request #31702
Opened 2024-01-13 08:44 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/30706

2024-01-15 14:26 UTC, chrisdavidmills requested changes
Thanks for the addition @OnkarRuikar. This is a really helpful section to include. I had a few thoughts for for you on how to improve it further.

2024-01-15 14:26 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +The value is an ordered set of space-separated token(s). The value contains either a single token (either "off" or "on") or multiple autofill detail tokens.
```suggestion
The value is an ordered set of space-separated token(s). The value contains either a single token ("off" or "on") or multiple autofill detail tokens.
```

2024-01-15 14:26 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +The value is an ordered set of space-separated token(s). The value contains either a single token (either "off" or "on") or multiple autofill detail tokens.
Also, what is ordered about the set? That might warrant an explanation.

2024-01-15 14:26 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +Multiple tokens are used to avoid confusing browsers when a form has inputs with similar values, e.g. billing vs shipping address.
You might to expand on what this means a bit. It took me a few reads to figure out what you meant.

Also, isn't the purpose to provide hints to the browser as to what values should be auto-filled? I'd start with something like that. The fact that this helps browsers to disambiguate autofill options for similar inputs is a useful side effect.

I'd also walk the reader through what it means to use these three values in the same `autocomplete` attribute. What do they mean, and what effect do they have, either separately, or when used all together?

2024-03-27 14:03 UTC, estelle commented on files/en-us/web/html/attributes/autocomplete/index.md
> +## Usage
The page has been updated to include a description section. We should remove this heading, and incorporate your content higher in this rewritten page

2024-03-27 14:05 UTC, estelle commented on files/en-us/web/html/attributes/autocomplete/index.md
> +<input autocomplete="section-blue shipping postal-code" />
include an example between 2 and 3 that doesn't include section-*, as section is only needed when you have multiple shipping addresses and therefor a postal codes for each

2024-04-09 14:00 UTC, bsmth commented
See also https://github.com/mdn/content/pull/28828

2024-04-18 18:31 UTC, estelle commented
I added an example to the description, see https://github.com/mdn/content/pull/33153, so I could close this.

2024-04-18 18:31 UTC, closed without merging

2024-04-18 18:40 UTC, OnkarRuikar commented
> I added an example to the description, see #33153, so I could close this.

Thanks! And sorry couldn't get back to this PR.