documentation for HTMLMapElement.areas
mdn/content pull request #31713
Opened 2024-01-14 10:52 UTC by ShubhamOulkar

### Description

adding new documentation for HTMLMapElement.areas

### Discussion 

### resource

2024-01-15 04:56 UTC, ShubhamOulkar reviewed
minor correction in content

2024-01-15 04:56 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like object ({{domxref("HTMLCollection")}}) of elements.
it is useful for beginners

2024-01-15 06:49 UTC, teoli2003 requested changes, later dismissed

2024-01-15 06:49 UTC, teoli2003 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +The **`areas`** read-only property of the {{domxref("HTMLMapElement")}} return {{domxref("HTMLCollection")}} object of {{HTMLElement("area")}} elements present in the {{HTMLElement("map")}} element.
Read-only is clear enough: no need to explain you can't modify it.

```suggestion
The **`areas`** read-only property of the {{domxref("HTMLMapElement")}} elements returns a collection of {{HTMLElement("area")}} elements associated with the {{HTMLElement("map")}} element. 

Two successive calls to this property will return the same object.
```

2024-01-15 06:49 UTC, teoli2003 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like {{domxref("HTMLCollection")}} object of `area` elements.
```suggestion
A live {{domxref("HTMLCollection")}} of {{domxref("HTMLAreaElement")}} objects.
```

2024-01-15 06:49 UTC, teoli2003 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +console.log(mapElement.areas); // output: HTMLCollection(2) [area, area]
```suggestion
console.log(mapElement.areas); // Output: HTMLCollection(2) [area, area]
```

2024-01-15 06:49 UTC, teoli2003 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +// iterate over each area element and change target value to _blank
```suggestion
// Iterate over each area element and change target value to _blank
```

2024-01-15 06:49 UTC, teoli2003 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +// click on left and right arrows, it will open a new tab.
As a live example, I don't think to make them open in a new tab is good.

Can we find something better here?

2024-01-15 06:55 UTC, skyclouds2001 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like object ({{domxref("HTMLCollection")}}) of elements.
But beside this, I don't think HTMLCollection is array-like

2024-01-15 07:40 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like object ({{domxref("HTMLCollection")}}) of elements.
This word is from mdn [HTMLCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection). 
Htmlcollections are array like object similar to 'arguments'. 

I thought if it is helpful for readers to follow content from other sources on MDN. 

In my opinion, Generic collection or just HTMLCollection are the most correct words. What is your opinion?

2024-01-15 07:44 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +// click on left and right arrows, it will open a new tab.
Then I will make dynamic changes in 'alt'.

2024-01-15 12:40 UTC, skyclouds2001 commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like object ({{domxref("HTMLCollection")}}) of elements.
Well, it seems ok for me now

2024-01-15 12:49 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like object ({{domxref("HTMLCollection")}}) of elements.
Ok, I will wait for @teoli2003 suggestions.

2024-01-15 12:56 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlmapelement/areas/index.md
> +An array-like {{domxref("HTMLCollection")}} object of `area` elements.
```suggestion
A  present {{domxref("HTMLCollection")}} of {{HTMLElement("area")}} objects.
```
`live` is not a proper word, what about `present' word?

2024-01-24 07:39 UTC, teoli2003 commented
Is this ready for re-review? Asking because the live sample is not working: https://pr31713.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLMapElement/areas

Anything I can do to help?

2024-01-24 10:56 UTC, ShubhamOulkar commented
> Anything I can do to help?

Thank you for reporting @teoli2003.

Yes, help me out. Local server shows the image. I don't know what is happening with preview URL. 

![image](https://github.com/mdn/content/assets/91728992/0f7b9e79-6d2f-46b4-876f-eb4886c81833)

2024-01-24 14:01 UTC, skyclouds2001 commented
Because the exact image is served on https://pr31713.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLMapElement/areas/left-right-arrow.png, but the demo is trying to get the image on https://live.mdnyalp.dev/en-US/docs/Web/API/HTMLMapElement/areas/left-right-arrow.png

2024-01-24 15:26 UTC, ShubhamOulkar commented
Is it macro problem? Or this src url will get update after rendering. 
I don't know how these macro add <iframe > with src attribute.

2024-07-13 06:21 UTC, Josh-Cena approved these changes
I have updated the example with something that better represents the usage of `areas`. I have verified that the live example works locally. Since this has been open for so long, I won't delay it further. Thanks for the work!

2024-07-13 06:22 UTC, merged