Add docs for *VideoFrameCallback() methods
mdn/content pull request #31762
Opened 2024-01-17 14:39 UTC by chrisdavidmills

### Description

`HTMLVideoElement.requestVideoFrameCallback()` and `HTMLVideoElement.cancelVideoFrameCallback()` have been supported in Chrome since version 83, and Safari since 15.4, but we haven't yet docs for them.

This PR fixes that.

See https://web.dev/articles/requestvideoframecallback-rvfc for a useful test demo.

### Motivation

### Additional details

### Related issues and pull requests

2024-01-17 18:24 UTC, skyclouds2001 commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +{{APIRef("Picture-in-Picture API")}}
I think it is not good to use {{APIRef("Picture-in-Picture API")}}, since it is not a part of the Picture-in-Picture API. And it is defined in a different spec, https://wicg.github.io/video-rvfc/. If the API summary will not be created, a {{APIRef("HTML DOM")}} might be better

2024-01-17 18:24 UTC, skyclouds2001 commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +{{APIRef("Picture-in-Picture API")}}
same as above

2024-01-17 18:24 UTC, skyclouds2001 commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +`undefined`.
```suggestion
None ({{jsxref('undefined')}}).
```

same as the [API method template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_method_subpage_template)

2024-01-17 18:24 UTC, skyclouds2001 commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +You can compare the `now` callback parameter and the `expectedDisplayTime` metadata property to determine whether your callback is a v-sync late. If `expectedDisplayTime` is within about five to ten
I wonder if it is a good idea to create a API summary, based on this *Description* section

2024-01-18 08:58 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +{{APIRef("Picture-in-Picture API")}}
Argh, that was a copy/paste error! I originally used the `requestPictureInPicture()` page as a template for this one.

Changed to "HTML DOM" in my next commit ;-)

2024-01-18 08:58 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +{{APIRef("Picture-in-Picture API")}}
Same as above.

2024-01-18 08:59 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +`undefined`.
Updated in next commit

2024-01-18 16:08 UTC, skyclouds2001 commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +You can compare the `now` callback parameter and the `expectedDisplayTime` metadata property to determine whether your callback is a v-sync late. If `expectedDisplayTime` is within about five to ten
ok, just a personal suggestion

2024-01-19 09:51 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +You can compare the `now` callback parameter and the `expectedDisplayTime` metadata property to determine whether your callback is a v-sync late. If `expectedDisplayTime` is within about five to ten
Yup, and your suggestions are always appreciated 🤗

2024-01-22 12:51 UTC, tomayac reviewed
Non-owner LGTM with the suggestions applied.

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +The **`cancelVideoFrameCallback()`** method of the {{domxref("HTMLVideoElement")}} interface cancels a previously-registered video frame request callback.
```suggestion
The **`cancelVideoFrameCallback()`** method of the {{domxref("HTMLVideoElement")}} interface cancels a previously-registered video frame callback.
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/index.md
> +  - : Cancels a previously-registered video frame request callback (see {{DOMxRef("HTMLVideoElement.requestVideoFrameCallback", "requestVideoFrameCallback()")}}).
```suggestion
  - : Cancels a previously-registered video frame callback (see {{DOMxRef("HTMLVideoElement.requestVideoFrameCallback", "requestVideoFrameCallback()")}}).
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +`requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}} — you typically use it to run a callback function that performs some operation and then calls `r
```suggestion
`requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}} — you typically use it to run a callback function that performs some operation and then call `requestVideoFrameCallback()` again to run the callback when the next video frame is composited. However, `requestVideoFrameCallback()` is tailored for video operations in several ways:
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +- Whereas `requestAnimationFrame()` tries to match the display refresh rate (most commonly 60Hz), `requestVideoFrameCallback()` tries to match the video frame rate. Specifically, the callback will ru
```suggestion
- In contrast, `requestAnimationFrame()` tries to match the display refresh rate (most commonly 60Hz), `requestVideoFrameCallback()` tries to match the video frame rate. Specifically, the callback will run at the lesser of the video frame rate and the browser paint refresh rate. For example, a 25fps video playing in a browser that paints at 60Hz would fire callbacks at 25Hz. A 120fps video in that same 60Hz browser would fire callbacks at 60Hz.
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +One thing to bear in mind is that `requestVideoFrameCallback()` does not offer any strict guarantees that the output from your callback will remain in sync with the video frame rate. It may end up be
```suggestion
One thing to bear in mind is that `requestVideoFrameCallback()` does not offer any strict guarantees that the output from your callback will remain in sync with the video frame rate. It may end up being fired one vertical synchronization (v-sync) late, relative to when the new video frame was presented (v-sync being a graphics technology that synchronizes the frame rate of a video and the refresh rate of a monitor).
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +const videoCallbackId = video.requestVideoFrameCallback(updateCanvas);
```suggestion
    // It's important to update the videoCallbackId each time you're calling requestVideoFrameCallback.
    videoCallbackId = video.requestVideoFrameCallback(updateCanvas);
};

// Initially register the callback to be notified about the first frame.
let videoCallbackId = video.requestVideoFrameCallback(updateCanvas);
```

2024-01-22 12:51 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +const videoCallbackId = video.requestVideoFrameCallback(updateCanvas);
Also see https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame#examples:~:text=//%20it%27s%20important%20to%20update%20the%20requestId%20each%20time%20you%27re%20calling%20requestAnimationFrame

2024-01-23 16:12 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +`requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}} — you typically use it to run a callback function that performs some operation and then calls `r
This didn't feel quite right to me, so I've tried making a more substantial change:

> `requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}}. You use it to run a callback function that performs some operation on the next video frame sent to the compositor. The callback finishes by calling `requestVideoFrameCallback()` again to run the callback when the next video frame is composited, and so on. However, `requestVideoFrameCallback()` is tailored for video operations in several ways:

WDYT?

2024-01-23 16:14 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +- Whereas `requestAnimationFrame()` tries to match the display refresh rate (most commonly 60Hz), `requestVideoFrameCallback()` tries to match the video frame rate. Specifically, the callback will ru
I handled this in a different way:

> - `requestAnimationFrame()` tries to match the display refresh rate (most commonly 60Hz). `requestVideoFrameCallback()` instead tries to match the video frame rate. Specifically, the callback will run at the lesser of the video frame rate and the browser paint refresh rate. For example, a 25fps video playing in a browser that paints at 60Hz would fire callbacks at 25Hz. A 120fps video in that same 60Hz browser would fire callbacks at 60Hz.

2024-01-23 16:27 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +const videoCallbackId = video.requestVideoFrameCallback(updateCanvas);
Ah, makes sense. I've updated the example as suggested but cleaned it up a bit and added some extra commentary to make it clearer why you need to do this.

2024-01-24 12:39 UTC, tomayac reviewed
Looks good to go, with one remark and one suggestion.

2024-01-24 12:39 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +Typical use cases for `requestVideoFrameCallback()` include video processing and painting to a canvas, video analysis, and synchronization with external audio sources. Per-frame processing was previo
FWIW, I also used the [`timeupdate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event) event in the past.

2024-01-24 12:39 UTC, tomayac commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +`requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}}. You use it to run a callback function that performs some operation on the next video frame sent
```suggestion
`requestVideoFrameCallback()` is used in the same way as {{domxref("Window.requestAnimationFrame()")}}. You use it to run a callback function that performs some operation when the next video frame is sent to the compositor. The callback finishes by calling `requestVideoFrameCallback()` again to run the callback when the next video frame is composited, and so on. However, `requestVideoFrameCallback()` is tailored for video operations in several ways:
```

2024-01-24 13:37 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +Typical use cases for `requestVideoFrameCallback()` include video processing and painting to a canvas, video analysis, and synchronization with external audio sources. Per-frame processing was previo
Ah, that is a much better way to do it. I've updated the text to suit.

2024-01-24 18:00 UTC, dipikabh requested changes
Hi @chrisdavidmills, I've done a readthrough and left a few suggestions.

2024-01-25 10:12 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +The **`requestVideoFrameCallback()`** method of the {{domxref("HTMLVideoElement")}} interface registers a callback function that runs when a new video frame is sent to the compositor, allowing develo
Some good suggestions here. I ended up with (in my next commit):

> The **`requestVideoFrameCallback()`** method of the {{domxref("HTMLVideoElement")}} interface registers a callback function that runs when a new video frame is sent to the compositor. This enables developers to perform efficient operations on each video frame.

2024-01-25 10:22 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +One thing to bear in mind is that `requestVideoFrameCallback()` does not offer any strict guarantees that the output from your callback will remain in sync with the video frame rate. It may end up be
Like it. I ended up with

> One thing to bear in mind is that `requestVideoFrameCallback()` does not offer any strict guarantees that the output from your callback will remain in sync with the video frame rate. It may end up being fired one vertical synchronization (v-sync) later than when the new video frame was presented. (V-sync is a graphics technology that synchronizes the frame rate of a video with the refresh rate of a monitor).

Basically the same, but with a typo fixed.

2024-01-25 10:23 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +The API runs on the main thread, video compositing likely happens on a separate compositing thread, and you've got to factor in the time taken for these operations to complete, and for the video itse
I used this verbatim

2024-01-25 10:24 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +      - : A {{domxref("DOMHighResTimeStamp")}} representing the time the callback was called.
Applied

2024-01-25 10:27 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +        - `width`: A number representing the width of the video frame in media pixels (visible decoded pixels, without aspect ratio adjustments).
Beautiful. I updated all of these verbatim.

2024-01-25 11:11 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +        - `rtpTimestamp`: A number representing the RTP timestamp associated with this video frame.
Super. Applied verbatim

2024-01-25 11:19 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +### Draw video frames onto a canvas
Updated.

It could be "drawing" or "rendering" really, but I think "drawing" sounds a bit more accurate. You are not doing much in the way of calculation or processing to calculate the pixels that are put on the canvas. You are just taking an exact copy of the pixels in each video frame and putting then on the canvas.

2024-01-25 11:23 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +  // Initially register the callback to be notified about the first frame.
I ended up changing this to 

> Initial registration of the callback to run on the first frame

And similar language for the earlier comment. The language about notification seemed a bit overly complex - you are running a callback function that does something to the next video frame sent to the compositor.

2024-01-25 11:24 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/index.md
> +  - : Registers a callback function that runs when a new video frame is sent to the compositor, allowing developers to perform efficient per-frame operations on video.
Good call. I've updated it to match.

2024-01-25 11:25 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +### Cancel a video frame callback
Updated!

2024-01-25 11:25 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +This example shows how to use `cancelVideoFrameCallback()` to cancel a previously registered video frame callback.
Updated

2024-01-25 11:26 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +  // so you can cancel the callback successfully
I've instead just removed the periods from the others. It feels weird to put periods at the end of code comments.

2024-01-25 11:28 UTC, chrisdavidmills commented on files/en-us/web/api/htmlvideoelement/cancelvideoframecallback/index.md
> +// Initially register the callback to be notified about the first frame.
Updated these comments in the same way as explained earlier.

2024-01-25 11:31 UTC, chrisdavidmills commented
Thank you so much for the thorough and helpful review, @dipikabh! I think I've fixed everything; let me know if you think it needs anything else.

2024-01-25 17:31 UTC, dipikabh commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +The **`requestVideoFrameCallback()`** method of the {{domxref("HTMLVideoElement")}} interface registers a callback function that runs when a new video frame is sent to the compositor, allowing develo
Excellent! Thanks!

2024-01-25 17:38 UTC, dipikabh commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +Typical use cases for `requestVideoFrameCallback()` include video processing and painting to a canvas, video analysis, and synchronization with external audio sources. Per-frame processing was previo
The updated text is good, thanks!
Just a nit to maintain the same tense
```suggestion
Typical use cases for `requestVideoFrameCallback()` include video processing and painting to a canvas, video analysis, and synchronization with external audio sources. Per-frame processing used to be done in a less efficient or accurate fashion by running operations on the current video display whenever the {{domxref("HTMLMediaElement.timeupdate_event", "timeupdate")}} event fired. This technique did not provide access to the actual video frames.
```

2024-01-25 17:38 UTC, dipikabh commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +Typical use cases for `requestVideoFrameCallback()` include video processing and painting to a canvas, video analysis, and synchronization with external audio sources. Per-frame processing was previo
Makes sense, thanks for the explainer

2024-01-25 17:39 UTC, dipikabh commented on files/en-us/web/api/htmlvideoelement/requestvideoframecallback/index.md
> +- `requestAnimationFrame()` tries to match the display refresh rate (most commonly 60Hz). `requestVideoFrameCallback()` instead tries to match the video frame rate. Specifically, the callback will ru
Looks good

2024-01-25 18:01 UTC, dipikabh approved these changes
All fixes look good, @chrisdavidmills. Thanks for taking the time to leave your responses :)

There's just two minor things, but the pages are looking in good shape. Feel free to merge when ready. Thank you for adding the docs!

2024-01-25 18:14 UTC, merged