Dialog tabindex
mdn/content pull request #31791
Opened 2024-01-18 19:50 UTC by estelle

And usage note about tabindex is not put on the dialog to fix https://github.com/mdn/content/issues/28750
Clarify while autofocus can be given to dialog, best practices are to add it to the close button
Minor grammar tweaks

2024-01-19 09:47 UTC, chrisdavidmills requested changes
Hi @estelle, great work as always. I feel like I've been horribly picky here, but there's actually not too much to sift through.

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- The CSS {{cssxref('::backdrop')}} pseudo-element can be used to style the backdrop of a modal dialog, which is displayed behind the `<dialog>` element when the dialog is displayed using the {{domxr
```suggestion
- The CSS {{cssxref('::backdrop')}} pseudo-element can be used to style the backdrop of a modal dialog, which is displayed behind the `<dialog>` element when the dialog is displayed using the {{domxref("HTMLDialogElement.showModal()")}} method. For example, this pseudo-element could be used to blur, darken, or otherwise obfuscate the inert content behind the modal dialog.
```

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- The CSS {{cssxref('::backdrop')}} pseudo-element can be used to style the backdrop of a modal dialog, which is displayed behind the `<dialog>` element when the dialog is displayed using the {{domxr
I just felt that only saying "obfuscate" made the sentence a little harder to understand than providing some examples of what you might do to achieve that.

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- The [`autofocus`](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute should be added to the element the user is expected to interact with immediately upon opening a modal dialog. If no ele
```suggestion
- The [`autofocus`](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute should be added to the element the user is expected to interact with immediately upon opening a modal dialog. If no other element involves more immediate interaction, it is recommended to add `autofocus` to the close button inside the dialog, or the dialog itself if the user is expected to click/activate it to dismiss.
```

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- The [`autofocus`](/en-US/docs/Web/HTML/Global_attributes/autofocus) attribute should be added to the element the user is expected to interact with immediately upon opening a modal dialog. If no ele
Not 100% sure about the last bit, but I felt this structure was a little more readable, and I liked the idea of incidentally letting the reader know you can autofocus the dialog itself, while providing some kind of use case.

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +When the dialog is closed, the return value is displayed under the "Show the dialog" button. If the dialog is closed by pressing the <kbd>Esc</kbd> key, the `return value` is not updated, and the `cl
```suggestion
When the dialog is closed, the return value is displayed under the "Show the dialog" button. If the dialog is closed by pressing the <kbd>Esc</kbd> key, the return value is not updated, and the `close` event doesn't occur, so the text in the {{HTMLElement("output")}} is not updated.
```

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can rece
```suggestion
- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can receive focus and be interactive. Therefore, you can consider adding `tabindex` to the dialog contents if appropriate.
```

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can rece
I'm not sure if this is appropriate really, or if you want to encourage readers to use `tabindex` if not absolutely necessary. But, as it was, it felt like you were implying this without saying it, and I feel it is good to be clear and explicit.

2024-01-19 09:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can rece
Also, now you've added this note, can you just get rid of the big red warning, or maybe link it to this note in some way? I wonder if readers will scan the page, see the big red warning, and still miss the rationale you've added down here.

2024-01-19 19:56 UTC, estelle commented on files/en-us/web/html/element/dialog/index.md
> +- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can rece
I prefer not to encourage using tabindex. I had written a sentence about "use semantic HTML elements that are interactive, and tabindex if you can't" but decided this wasn't the spot to discuss semantic elements. I am adding this because of the "why" about the warning. Not to replace it. I'll like to "usage notes". I can't link to the list item directly

2024-01-22 09:29 UTC, chrisdavidmills commented on files/en-us/web/html/element/dialog/index.md
> +- Do not add the `tabindex` property to the `<dialog>` element as it is not interactive and does not receive focus. The dialog's contents, including the close button contained in the dialog, can rece
Sure, totally understood.

2024-01-22 09:30 UTC, chrisdavidmills approved these changes
Yay, looks great — thanks @estelle! I'll get this merged.

2024-01-22 09:31 UTC, merged