Document for HTMLAnchorElement.text
mdn/content pull request #31887
Opened 2024-01-24 12:49 UTC by ShubhamOulkar

2024-01-25 13:45 UTC, skyclouds2001 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +This property is same as {{domxref("Node.textContent")}}.
```suggestion
The **`text`** property of the {{domxref("HTMLAnchorElement")}} reflects the {{HTMLElement("a")}} element text content.
This property is same as {{domxref("Node.textContent")}}.
```

the property is not read-only

2024-01-25 13:45 UTC, skyclouds2001 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +{{EmbedLiveSample("Example",100,100)}}
```suggestion

{{EmbedLiveSample("Example",100,100)}}
```

*Result* section is not necessary

2024-01-25 13:50 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +{{EmbedLiveSample("Example",100,100)}}
I kept it cus reader might check Node.textContent

2024-01-25 13:53 UTC, skyclouds2001 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +{{EmbedLiveSample("Example",100,100)}}
Or *###Result*

2024-01-25 14:11 UTC, ShubhamOulkar commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +{{EmbedLiveSample("Example",100,100)}}
My bad I didn't notice

2024-01-25 20:57 UTC, dawei-wang commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +This property is same as {{domxref("Node.textContent")}}.
```suggestion
This property is the same as {{domxref("Node.textContent")}}.
```

2024-01-26 06:22 UTC, teoli2003 requested changes
Almost ready.

2024-01-26 06:22 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +The **`text`** property of the {{domxref("HTMLAnchorElement")}} reflects the {{HTMLElement("a")}} element text content.
Only attribute can be reflected.
```suggestion
The **`text`** property of the {{domxref("HTMLAnchorElement")}} represents the text inside the the element. 
```

2024-01-26 06:22 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +pTag.textContent = anchorElement.text + " " + "text property";
Let's makes it clearer. Also template string are much more readable in this case:
```suggestion
pTag.textContent =  `Text property: ${anchorElement.text}`;
```

2024-01-26 08:22 UTC, teoli2003 commented on files/en-us/web/api/htmlanchorelement/text/index.md
> +This property is the same as {{domxref("Node.textContent")}}.
```suggestion
This property represents the same information as {{domxref("Node.textContent")}}.
```

2024-01-26 08:22 UTC, teoli2003 approved these changes
👍 (made an extra modif, technically "is the same" is incorrect, but that's pedantic)

2024-01-26 08:23 UTC, merged

2024-01-26 12:45 UTC, ShubhamOulkar commented
> 👍 (made an extra modif, technically "is the same" is incorrect, but that's pedantic)

I try to be less techie every day, but it sticks with me. I appreciate all feedbacks from you. 🙌

2024-01-26 14:29 UTC, teoli2003 commented
I didn't see it at the first rea because it is the kind of language you use every day, though it can be confusing for beginners.