Update index.md - Add information on `rcap`, `rex`, `ric`, and `rch` units
mdn/content pull request #31901
Opened 2024-01-25 04:56 UTC by francescorn

I am adding information about the `rcap`, `rex`, `ric`, and `rch` units. Issue #509.

### Description

I am adding information on `rcap`, `rex`, `ric`, and `rch` units.

### Motivation

Anyone will be able to learn more about `rcap`, `rex`, `ric`, and `rch` units.

### Additional details

[font-relative-lengths](https://www.w3.org/TR/css-values-4/#font-relative-lengths)

### Related issues and pull requests

Fixes #509

2024-01-26 20:32 UTC, francescorn commented
@estelle @Rumyra @dipikabh Can one of you review my patch when you have a chance? I am fixing my linting errors from now on 😅.

2024-01-27 17:28 UTC, dipikabh commented
Thanks @francescorn, I can take a look on Monday

2024-01-29 17:05 UTC, dipikabh requested changes
Thanks for adding this info, @francescorn!
I've added a few suggestions.

Also fyi, we work from the Editor's draft of specs for MDN updates: https://drafts.csswg.org/css-values-4/#font-relative-lengths

2024-01-29 17:05 UTC, dipikabh commented on files/en-us/web/css/length/index.md
> +  -
The definition list is not rendering properly. Hopefully, this fixes it.
```suggestion
 
```

2024-01-29 22:21 UTC, francescorn commented
Thank you for letting me know @dipikabh. I will reference the editor's draft specs in future prs. The above changes look good to me.

2024-01-30 04:05 UTC, dipikabh requested changes
Thank you for incorporating the fixes.
There still seems to be some issue with the rendering of the definition list. Please check if the suggested indentations fix the issue.

2024-01-30 04:05 UTC, dipikabh commented on files/en-us/web/css/length/index.md
> +- : Equal to the value of [`ic`](#ic) unit on the root element's font.
```suggestion
- `rex`
  - : Represents the x-height of the root element's {{Cssxref("font")}}.
- `ric`
  - : Equal to the value of [`ic`](#ic) unit on the root element's font.
```

2024-01-30 17:44 UTC, francescorn commented
The tests passed.

2024-01-30 19:59 UTC, dipikabh approved these changes
Perfect, thank you!

2024-01-30 19:59 UTC, merged