Media queries module
mdn/content pull request #31903
Opened 2024-01-25 05:54 UTC by estelle

CSS module landing page project
CSS media queries module and guides

scan is in a different PR: https://github.com/mdn/content/pull/31894 (open)

media query glossary is in a different PR
https://github.com/mdn/content/pull/31754 (merged)

CSS conditional module is already merged

2024-01-25 09:14 UTC, chrisdavidmills requested changes
@estelle fabulous work as always. I've got a few suggestions for you, most of them minor.

One thing I did notice is that the Printing guide doesn't appear in the sidebar. Does that require a sidebar macro to be fiddled with?

2024-01-25 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +The `not` keyword inverts the meaning of a single media query. It only negates the specific media query it is applied to, negating the _entire_ media query. This means it will not apply to every medi
```suggestion
The `not` keyword inverts the meaning of a single media query. For example...INCLUDE THE DESCRIPTION OF THE SINGLE MEDIA QUERY "NOT" EXAMPLE CURRENTLY AT THE BOTTOM OF THE SECTION, HERE

EXAMPLE CODE HERE

Note that `not` only negates the specific media query it is applied to — in a comma-separated list of media queries, each `not` applies to the single query it is contained within, applying to all the features within that single query. For example NOW DESCRIBE A COMMA-SEPARATED LIST EXAMPLE WITH A SINGLE NOT, TO SHOW WHAT YOU MEAN

EXAMPLE CODE HERE
```

2024-01-25 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +The `not` keyword inverts the meaning of a single media query. It only negates the specific media query it is applied to, negating the _entire_ media query. This means it will not apply to every medi
Sorry for the weird suggestion comment here - it is not really meant to be applied, but instead show you what structure I think should be used. I just found the section strange - it shows the simplest example at the end rather than the start, and then explains the comma-separated example weirdly, repeating itself about three times and then not showing an actual example.

2024-01-25 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +To negate a single feature within a media query, use `not()`. The `not()` functional notation logical operator encompassing a media feature negates only that feature within the query.
I think this line could then be deleted too. It also seems to repeat what was said above.

2024-01-25 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries_for_accessibility/index.md
> +Reducing animations or switching animation off completely based on the user's preference can also benefit users with low battery or low-end phones or computers.
```suggestion
Reducing animations or switching animation off completely based on the user's preference can also benefit users with low battery or low-end devices.
```

2024-01-25 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries_for_accessibility/index.md
> +The value of `prefers-reduced-motion` is `reduce`, not "none". This preference does not mean all animations must be removed, such as could be set with `* {animation: none !important;}`. Rather, users
```suggestion
The value of `prefers-reduced-motion` is `reduce`, not "none". This preference does not mean all animations must be removed, which could be achieved with `* {animation: none !important;}`. Rather, users expect motion animation, including those triggered by user interaction, to be disabled unless the animation is essential to the functionality or the information being conveyed (see [WCAG: Animation from Interactions](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html)).
```

2024-01-25 17:38 UTC, estelle reviewed
will change the order of the examples for "using" in the next commit.

2024-01-25 17:38 UTC, estelle commented on files/en-us/web/css/css_media_queries/index.md
> -### Media queries in HTML
it's linked to in the related, but this page is purely a "link to all the features" page, not an explanation of any of those features page.

2024-01-25 18:24 UTC, estelle commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +To negate a single feature within a media query, use `not()`. The `not()` functional notation logical operator encompassing a media feature negates only that feature within the query.
not a functional notation either, just parenthesis. oops.

2024-01-25 18:25 UTC, estelle commented
Thanks @chrisdavidmills. I changed the examples and explanations for discrete, not, and not with parens.

2024-01-26 01:38 UTC, estelle commented
https://github.com/mdn/yari/pull/10386 - adds the missing "Printing" to the CSSRef sidebar.
Also added the cssref into printing. it was missing there too.

2024-01-26 13:38 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/index.md
> -### Media queries in HTML
Oh, sorry, I missed that they were linked there. That's absolutely fine in that case.

`MediaQueryList.addListener()` is not included, but that's deprecated, so I can understand you getting rid.

2024-01-26 13:49 UTC, chrisdavidmills approved these changes
Fabulous work, @estelle. The not and discrete updates read so much better now. Couple more nitpicks, but approving so as not to hold you up.

2024-01-26 13:49 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +The `not` negates only the media query it is applied to. The `not`, without parenthesis, negates all the features within the media query in which it is contained. This means, in a comma-separated lis
```suggestion
The `not` negates only the media query it is applied to. The `not`, without parenthesis, negates all the features within the media query in which it is contained. This means, in a comma-separated list of media queries, each `not` applies to the single query it is contained within, applying to _all_ the features within that single query. In this example, the `not` applies to the first media query, which concludes at the first comma:
```

2024-01-26 13:49 UTC, chrisdavidmills commented on files/en-us/web/css/css_media_queries/using_media_queries/index.md
> +Both examples are valid. Media conditions can be grouped by wrapping them in parentheses `()` which can then be nested within a condition the same as a single media query.
```suggestion
Both examples are valid. Media conditions can be grouped by wrapping them in parentheses (`()`). These groups can then be nested within a condition the same as a single media query.
```

2024-01-26 21:49 UTC, merged