Adds TrustedTypePolicyFactory
mdn/content pull request #3192
Opened 2021-03-16 16:08 UTC by rachelandrew

Adds the TrustedTypePolicyFactory interface and subpages.

Spec: https://w3c.github.io/webappsec-trusted-types/dist/spec/#trusted-type-policy-factory

Reviewer: @jpmedley 

Joe: the MDN helper returned some odd things for this one and didn't create one page, however the spec matches BCD in terms of which pages should exist. So I've followed that.

2021-03-16 19:53 UTC, jpmedley requested changes
This looks generally good. My feedback is a mix of nits and some questions about things I think need to be elaborated on or clarified.

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/emptyscript/index.html
> +<p>The <a href="https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicyfactory-emptyscript">specification</a> explains that the <code>emptyScript</code> object can be used to d
This seems more appropriate to the introduction. There should be something similar for `trustedHTML`.

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/emptyscript/index.html
> +<p>Native Trusted Types implementations can support <code>eval(TrustedScript)</code>, therefore in the below example in a native implementation will return false for <code>eval(trustedTypes.emptyScri
```suggestion
<p>Native Trusted Types implementations can support <code>eval(TrustedScript)</code>, therefore in the below example a native implementation will return false for <code>eval(trustedTypes.emptyScript)</code>. A polyfill will return a truthy object.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/getattributetype/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing an attribute.</dd>
> {{domxref("DOMString","string")}}

I approve. It's a step in the direction of getting an IDL concept out of API reference. What prompted you to do this? Is it an official policy now?

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/getattributetype/index.html
> +  <li>"TrustedScriptURL</li>
```suggestion
  <li><code>"TrustedHTML"</code></li>
  <li><code>"TrustedScript"</code></li>
  <li><code>"TrustedScriptURL"</code></li>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/getpropertytype/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing a namespace.</dd>
I know what a namespace is, generally. What is it in this context?

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/getpropertytype/index.html
> +  <li>"TrustedScriptURL</li>
```suggestion
  <li><code>"TrustedHTML"</code></li>
  <li><code>"TrustedScript"</code></li>
  <li><code>"TrustedScriptURL"</code></li>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/index.html
> +<p>The below code creates a policy with the name <code>myEscapePolicy</code> with a function defined for <code>createHTML</code> which sanitizes HTML.</p>
```suggestion
<p>The below code creates a policy with the name <code>"myEscapePolicy"</code> with a function defined for <code>createHTML()</code> which sanitizes HTML.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/ishtml/index.html
> +  <p>The purpose of the functions <code>isHTML</code>, {{domxref("TrustedTypePolicyFactory.isScript","isScript()")}}, and {{domxref("TrustedTypePolicyFactory.isScriptURL","isScriptURL()")}} is to che
```suggestion
  <p>The purpose of the functions <code>isHTML()</code>, {{domxref("TrustedTypePolicyFactory.isScript","isScript()")}}, and {{domxref("TrustedTypePolicyFactory.isScriptURL","isScriptURL()")}} is to check if the object is a valid TrustedType object, created by a configured policy.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/ishtml/index.html
> +<p>A {{jsxref("boolean")}}, true if the object is a valid {{domxref("TrustedHTML")}} object.</p>
```suggestion
<p>A {{jsxref("boolean")}} that is true if the object is a valid {{domxref("TrustedHTML")}} object.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/ishtml/index.html
> +<p>In the below example the constant <code>html</code> was created by a policy, and therefore <code>isHTML</code> returns true. The second example is an attempt to fake an object, and the third is a
```suggestion
<p>In the below example the constant <code>html</code> was created by a policy, and therefore <code>isHTML()</code> returns true. The second example is an attempt to fake an object, and the third is a string. Both of these will return false when passed to <code>isHTML()</code>.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscript/index.html
> +  <p>The purpose of the functions <code>isScript</code>, {{domxref("TrustedTypePolicyFactory.isHTML","isHTML()")}}, and {{domxref("TrustedTypePolicyFactory.isScriptURL","isScriptURL()")}} is to check
```suggestion
  <p>The purpose of the functions <code>isScript()</code>, {{domxref("TrustedTypePolicyFactory.isHTML","isHTML()")}}, and {{domxref("TrustedTypePolicyFactory.isScriptURL","isScriptURL()")}} is to check if the object is a valid TrustedType object, created by a configured policy.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscript/index.html
> +<p>A {{jsxref("boolean")}}, true if the object is a valid {{domxref("TrustedScript")}} object.</p>
```suggestion
<p>A {{jsxref("boolean")}} that is true if the object is a valid {{domxref("TrustedScript")}} object.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscript/index.html
> +<p>In the below example the constant <code>url</code> was created by a policy, and therefore <code>isScriptURL</code> returns true. The second example is an attempt to fake an object, and the third i
```suggestion
<p>In the below example the constant <code>url</code> was created by a policy, and therefore <code>isScriptURL()</code> returns true. The second example is an attempt to fake an object, and the third is a string. Both of these will return false when passed to <code>isScriptURL()</code>.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscripturl/index.html
> +  <p>The purpose of the functions <code>isScriptURL</code>, {{domxref("TrustedTypePolicyFactory.isHTML","isHTML()")}}, and {{domxref("TrustedTypePolicyFactory.isScript","isScript()")}} is to check if
```suggestion
  <p>The purpose of the functions <code>isScriptURL()</code>, {{domxref("TrustedTypePolicyFactory.isHTML","isHTML()")}}, and {{domxref("TrustedTypePolicyFactory.isScript","isScript()")}} is to check if the object is a valid TrustedType object, created by a configured policy.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscripturl/index.html
> +<p>A {{jsxref("boolean")}}, true if the object is a valid {{domxref("TrustedScriptURL")}} object.</p>
```suggestion
<p>A {{jsxref("boolean")}}that is true if the object is a valid {{domxref("TrustedScriptURL")}} object.</p>
```

2021-03-16 19:53 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/isscripturl/index.html
> +<p>In the below example the constant <code>url</code> was created by a policy, and therefore <code>isScriptURL</code> returns true. The second example is an attempt to fake an object, and the third i
```suggestion
<p>In the below example the constant <code>url</code> was created by a policy, and therefore <code>isScriptURL()</code> returns true. The second example is an attempt to fake an object, and the third is a string. Both of these will return false when passed to <code>isScriptURL()</code>.</p>
```

2021-03-17 07:32 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/emptyhtml/index.html
> +<p class="summary">The <strong><code>emptyHTML</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns a {{domxref("TrustedHTML")}} object containing an em
@jpmedley surely because if you need to insert an empty string you can't once you are using trusted types, for example to remove something. This just seems to be a bit of functionality to give you that without needing to run an empty string through a policy.

2021-03-17 07:35 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/emptyscript/index.html
> +<p>The <a href="https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicyfactory-emptyscript">specification</a> explains that the <code>emptyScript</code> object can be used to d
there isn't for TrustedHTML, and I don't understand why you think there would be. I wanted to add this as an example because it's a very specific quirk really to be able to distinguish between a polyfilled version. It isn't what this interface is _for_ but is useful (and will go away once there is no need for polyfilling ...)

2021-03-17 07:37 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/getattributetype/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing an attribute.</dd>
nope, though I have seen the odd instance of it. I know you don't like linking to DOMString while I think we should link to DOMString ... seems like a good compromise ;)

2021-03-22 13:37 UTC, jpmedley requested changes

2021-03-22 13:37 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +  <dd>Thrown if policy names are restricted by the <a href="/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types">Content Security Policy `trusted-types` directive</a> and this name is
```suggestion
  <dd>Thrown if policy names are restricted by the <a href="/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types">Content Security Policy <code>trusted-types</code> directive</a> and this name is not on the allowlist.</dd>
```

2021-03-22 13:37 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +  <dd>A {{domxref("TrustedTypePolicyOptions")}} dictionary of user-defined functions for converting strings into trusted values.</dd>
Can you please move this in line?

2021-03-23 11:26 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/getpropertytype/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing a namespace.</dd>
not sure what you want to add here, I have added that it defaults to the HTML namespace. The MDN glossary entry isn't helpful to link to. Maybe: https://developer.mozilla.org/en-US/docs/Related/IMSC/Namespaces

2021-03-23 11:29 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/defaultpolicy/index.html
> +<p class="summary">The <strong><code>defaultPolicy</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns the default {{domxref("TrustedTypePolicy")}} or
I've added the example of logging information to the console with a default policy to the createPolicy page. I'm a bit confused by the Chromium specific stuff. My reading of this was that you create a policy with the name default and it gets used for bare string insertions. The non-normative text is normal for examples and prose that gives some ideas for use. Maybe I'm looking at a different part. Anyway, have a look at what I have done.

2021-03-23 11:29 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +  <dd>A {{domxref("TrustedTypePolicyOptions")}} dictionary of user-defined functions for converting strings into trusted values.</dd>
have done.

2021-03-23 11:30 UTC, rachelandrew commented
@jpmedley I had a few comments on some of your comments but the other things are done.

2021-03-24 13:43 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/emptyhtml/index.html
> +<p class="summary">The <strong><code>emptyHTML</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns a {{domxref("TrustedHTML")}} object containing an em
Please find out for sure.

2021-03-24 13:49 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/emptyscript/index.html
> +<p>The <a href="https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicyfactory-emptyscript">specification</a> explains that the <code>emptyScript</code> object can be used to d
>there isn't for TrustedHTML, and I don't understand why you think there would be.

Just asking the question.

>it's a very specific quirk really to be able to distinguish between a polyfilled version.

I thought maybe it was feature detection.

2021-03-24 13:50 UTC, jpmedley approved these changes

2021-03-30 10:26 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/emptyhtml/index.html
> +<p class="summary">The <strong><code>emptyHTML</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns a {{domxref("TrustedHTML")}} object containing an em
@jpmedley I found this issue which backs up my assumption that the purpose of these is to be able to assign an empty string. https://github.com/w3c/webappsec-trusted-types/issues/95

So can you clarify if you want me to add to the documentation something about this?

2021-03-31 15:51 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/emptyhtml/index.html
> +<p class="summary">The <strong><code>emptyHTML</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns a {{domxref("TrustedHTML")}} object containing an em
Yes, please.

2021-04-01 09:03 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/emptyhtml/index.html
> +<p class="summary">The <strong><code>emptyHTML</code></strong> read-only property of the {{domxref("TrustedTypePolicyFactory")}} interface returns a {{domxref("TrustedHTML")}} object containing an em
added in latest commit.

2021-04-01 16:32 UTC, jpmedley requested changes

2021-04-01 16:32 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +<h3 id="Default_policy">The default policy</h3>
I hate to throw this back at you again, but this needs to have information that aspects of the default policy are non-normative and specific to Chrome. This kind of thing is not unprecedented on MDN. If a normative approach emerges in the future, Chrome will likely be the first to implement it, giving us the chance to update this.

2021-04-02 10:19 UTC, rachelandrew commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +<h3 id="Default_policy">The default policy</h3>
I don't really understand what you want me to do here or where this non-normative information is from that you want me to include. I've searched the spec, for all instances of defaultPolicy, and I seem to have documented this according to the spec.

I also looked at the open issues on the spec: https://github.com/w3c/webappsec-trusted-types/issues

I did note in my original comment on this that I didn't understand your non-normative comment: https://github.com/mdn/content/pull/3192#discussion_r599485328

What aspect are you suggesting is specific to Chrome? Given that only Chromium has implemented I can't test it to find out what other UAs are doing to try and work this out myself.

If you can let me know where you have this Chromium specific info from I'll fold it in :)

2021-04-02 14:55 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +<h3 id="Default_policy">The default policy</h3>
https://w3c.github.io/webappsec-trusted-types/dist/spec/#default-policy-hdr

Basically this means that other browsers are not required to implement default behavior the way we have in Chrome. 
* Somewhere say that the default is currently set in Chrome by creating a policy with the name "default". If another browser implements this differently, they'll have a logical place to document it. If Chrome's current behavior is ratified, we'll be able to remove the word 'Chrome' from the description.
* Include a disclaimer that this isn't settled in the spec and may change in the future.

2021-04-06 14:49 UTC, jpmedley commented on files/en-us/web/api/trustedtypepolicyfactory/createpolicy/index.html
> +<h3 id="Default_policy">The default policy</h3>
I understand your concern. This is a judgement call based on experience with very new APIs. We'll discuss this in our 1:1 this week. Thank you for trusting me.

2021-04-06 14:50 UTC, jpmedley approved these changes

2021-04-06 14:50 UTC, merged