fix(docs): add a page describing everything about standardization statuses
mdn/content pull request #31941
Opened 2024-01-26 14:34 UTC by OnkarRuikar

We've been using a bot to update statuses (experimental, deprecated, and non-standard) stored in BCD repo. Since the bot automatically does the update it is no longer required to manually provide status information in the content repo.\
If the information is provided manually then it may cause conflict with the bot.

The PR:
- adds a new page which explains
  - the statuses
  - update procedure in BCD
  - a warning about updating them manually
  - mechanisms used to render the statuses in sidebars, header banners, and inline badges
- updates rest of the pages under /files/mdn
  - removes manual update instructions
  - adds links to the new page
  - adds missing information
 - fixes typos

2024-01-26 14:53 UTC, Rumyra commented
I'm assigning this to @bsmth and @chrisdavidmills - this all looks good @OnkarRuikar but I'd like a discussion about the naming of the new area (not 100% on 'standardization') - we also have a bit of work around a new notification for one of the apis and I don't want this to directly conflict with that, so putting Brian & Chris' eyes on it directly shoudl help 👍

2024-01-26 15:05 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
> +- Update the status data in `browser-compat-data` repository by [submitting a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data) to the
```suggestion
- Update the item's status data in the `browser-compat-data` repository by [submitting a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data).
```

2024-01-26 15:05 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
> +- Update the status data in `browser-compat-data` repository by [submitting a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data) to the
```suggestion
- Update the item's status data in the `browser-compat-data` repository by [submitting a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data).
```

2024-01-26 15:08 UTC, OnkarRuikar commented
> I'd like a discussion about the naming of the new area (not 100% on 'standardization')

Simply calling it `status` (as we've been doing in code) is not sufficient.
How about:
- feature status
- technology status
- item status

2024-01-26 15:11 UTC, bsmth commented
> * feature status
> * technology status

I like both of these and they're congruent with https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete

2024-01-26 15:31 UTC, bsmth requested changes
Could we change:

`Standardization` -> `Technology`

2024-01-26 16:20 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +Hence, there is no need to add them manually to the content.
```suggestion
Therefore, the only banner that is still manually added to the content is the **Secure context** banner.
```

This could also be a warning:

````markdown

> **Warning:**
> Do not manually add **\{{SeeCompatTable}}**, **\{{Deprecated_Header}}** or *\{{Non-standard_Header}}** banners...

````

What do you think?

2024-01-26 16:21 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/macros/index.md
> +to let macros interact with the platform and its contents.
Nit

```suggestion
Macros on MDN are implemented using server-executed [JavaScript](/en-US/docs/Web/JavaScript) code, interpreted using [Node.js](https://nodejs.org/en/).
On top of that, we have a number of libraries we've implemented that provide services and features to let macros interact with the platform and its contents.
```

2024-01-26 16:22 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_constructor_subpage_template/index.md
> +>   - : Do not provide status keys manually. To include (appropriate) technology status keys [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**d
```suggestion
>   - : Do not add or edit status keys manually. To include (appropriate) technology status keys [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**deprecated**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#deprecated), or **non-standard** refer section ["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
```

2024-01-26 16:22 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_event_subpage_template/index.md
> +>   - : Do not provide status keys manually. To include (appropriate) technology status keys [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**d
Same comment here and with the others

2024-01-26 16:25 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/aria_page_template/index.md
> +["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
Feel free to ignore if this is your preferred style, are you looking to break between links in the editor?

```suggestion
To include (appropriate) technology status keys [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**deprecated**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#deprecated), or **non-standard** refer section ["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
```

2024-01-26 16:35 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +Technology status of a feature tells developers implementation stage of the feature among browsers. Using it, developers can decide if a feature is stable enough to use in production code. Each featu
```suggestion
Technology status provides developers with information about the implementation stage of the feature among browser vendors. A technology status is one of the following:
```

2024-01-26 16:40 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +Statuses of all the features are being maintained at only one place: [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository. Those statuses are _automatically_ update
```suggestion
The technology status for a feature documented on MDN is defined in its accompanying [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository entry. The `status` front-matter keys are _automatically_ updated in the `mdn/content` repository whenever a new [version of BCD is released](https://github.com/mdn/browser-compat-data/releases), which is twice a week at most.
```

2024-01-26 16:44 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +As there is an automation in place to synchronize the data, _there is no need to manually update the statuses in the content code_. You need to [submit a pull request](https://github.com/mdn/browser-
```suggestion
> **Warning:**
> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data) in the BCD repository. After your changes are approved and merged in BCD, an automated pull request updates the statuses in the `mdn/content` repository.
```

2024-01-26 16:45 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Hence, it is best not to manually update technology statuses in the content code.
You could combine with the warning above (or remove this warning, saying "don't do it" is enough, I think).

2024-01-26 16:47 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +Following sections document mechanisms using which technology statuses are placed in content. As mentioned before, it is not required to use these mechanisms manually.
```suggestion
The following sections document mechanisms using which technology statuses in content. As mentioned, you should consider these mechanisms read-only as their inclusion in the content is automated.
```

2024-01-26 16:52 UTC, bsmth commented
Thanks, @OnkarRuikar I am done with that review round. Feel free to ignore/resolve the style comments, mostly some suggestions on `technology_status/index.md` for you to consider.

2024-01-27 00:32 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +Hence, there is no need to add them manually to the content.
When, in future, a new banner gets introduced the statement won't remain true. Going with the warning.

2024-01-27 00:35 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_event_subpage_template/index.md
> +>   - : Do not provide status keys manually. To include (appropriate) technology status keys [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**d
done

2024-01-27 00:37 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/aria_page_template/index.md
> +["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
The editor breaks lines in such manner to make it more readable.

2024-01-27 00:41 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +Statuses of all the features are being maintained at only one place: [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository. Those statuses are _automatically_ update
```suggestion
The technology statuses of all the features documented on MDN are defined in its accompanying [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository entry and are _automatically_ updated in the `mdn/content` repository whenever a new [version of BCD is released](https://github.com/mdn/browser-compat-data/releases).```

2024-01-27 00:45 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Hence, it is best not to manually update technology statuses in the content code.
Looks like there is no need to go into details of how it fails. Straight up saying "don't do it" sounds good. Removing the warning.

2024-01-27 00:49 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +Following sections document mechanisms using which technology statuses are placed in content. As mentioned before, it is not required to use these mechanisms manually.
```suggestion
The following sections document mechanisms using which technology statuses are rendered in MDN documents. As mentioned, you should consider these mechanisms read-only as their inclusion in the content is automated.
```

2024-01-29 11:09 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +  - : If none of the above status apply, then the feature is considered standard. We don't need to explicitly mention this status in the content code because the status is assumed by default.
```suggestion
  - : If none of the above statuses apply, then the feature is considered standard. We don't explicitly add this status to content pages as a technology status is `standard` by default.
```

2024-01-29 11:28 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +For more information on these terms, see the ["Experimental, deprecated, and obsolete"](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete) page. To see detailed instructions on how
One last comment is that I'm a little concerned that wording drifts in definitions, so I wouldn't define these here, but list and link, what do you think?

```suggestion
A technology status provides developers with information about the implementation stage of the feature among browser vendors and is one of the following:

- [`experimental`](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#setting-experimental)
- [`non-standard`](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#status-information)
- [`deprecated`](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#setting-deprecated)

If none of the above statuses apply, then the feature is considered `standard`.
We don't explicitly add this status to content pages as a technology status is `standard` by default.
For more information on these terms, see the ["Experimental, deprecated, and obsolete"](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete) page.

To see detailed instructions on how to choose a status for a feature, refer to the [choosing status properties](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#choosing-status-properties) section in the `@mdn/browser-compat-data` (BCD) repository.
```

2024-01-29 11:28 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +  - : If none of the above status apply, then the feature is considered standard. We don't need to explicitly mention this status in the content code because the status is assumed by default.
See later comment

2024-01-29 11:29 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +The technology statuses of all the features documented on MDN are defined in its accompanying [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository entry and are _au
Markdown  leftover

```suggestion
The technology statuses of all the features documented on MDN are defined in its accompanying [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository entry and are _automatically_ updated in the `mdn/content` repository whenever a new [version of BCD is released](https://github.com/mdn/browser-compat-data/releases).
```

2024-01-29 11:33 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +```
````suggestion
```yml
---
title: Feature name
status:
  - experimental
  - non-standard
  - deprecated
browser-compat: api.feature
---
```
````

2024-01-29 11:41 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
Is the code for this automation checked in somewhere? If not, should we put it in GH actions? Currently it's not apparent when this automation runs and what rules it has etc., or at least I can't find it from the PRs.

```suggestion
> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#updating-the-compat-data) in the BCD repository. After your changes are approved and merged in BCD, an [automated pull request](https://github.com/search?q=repo%3Amdn%2Fcontent+Synchronize+with+BCD&type=pullrequests) updates the statuses in the `mdn/content` repository.
```

2024-01-29 19:50 UTC, dipikabh commented
Thanks for these updates @OnkarRuikar.
Leaving a drive-by comment: also consider adding an entry for the new page on the [Page structures](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures) landing page.

2024-01-29 20:31 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are/should be added
Fly by.  "Why is "are" needed?
```suggestion
## What banners should be added
```

2024-01-29 20:33 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +> [update the technology status in `browser-compat-data` repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
Is there actual harm in someone doing this? 

I'm always going to add these because I know the state when I start, and before the script is run to get info from BCD. Unless this script is run as part of yari in my client?

2024-01-30 03:01 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are/should be added
"are" is for status macros where "are" added automatically by the automation.
"should be" is for other macros that writers are supposed to add.

2024-01-30 03:27 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +> [update the technology status in `browser-compat-data` repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
> Is there actual harm in someone doing this?

Since beginning of time we do create corresponding PR in BCD to add/update status in BCD. Not doing this was a bad practice as we were getting multiple complains that in page statuses and Compat table statuses at the bottom of the pages weren't matching.

So we made BCD a single source of truth. And started automated syncing content.

> I'm always going to add these because I know the state when I start, and before the script is run to get info from BCD.

If it helps there is no harm in adding these statuses manually while adding feature pages. But don't forget to update BCD repo as well. Not doing so will revert your status changes in content repo (we are not going to do reverse syncing to BCD).

My initial language was in this PR was a suggestion. But later reviewers have changed it to "don't do it".

> Unless this script is run as part of yari in my client?

No point in doing this as you'll have to update BCD repo first and get the PR merged. Then start documenting the new page in content.

2024-01-30 03:31 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
My initial language [was a suggestion](https://github.com/mdn/content/pull/31941/commits/817c86fa06013ee21d489b2a6b1e50746fad04ac#diff-dd0bb6f913e6339c55b69f997a1717c0d5f86f66541102b0cf17f3e2bba4066cR26).\
Do we need a poll or a broader discussion for "whether to make this a strict rule" or "leave it open ended with a warning"?

2024-01-30 04:09 UTC, OnkarRuikar commented
> Thanks for these updates @OnkarRuikar. Leaving a drive-by comment: also consider adding an entry for the new page on the [Page structures](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures) landing page.

We don't have to the list is [generated automatically](https://github.com/mdn/content/blob/05808d3600f3a5b856eaaf89359f1fdc3d255c26/files/en-us/mdn/writing_guidelines/page_structures/index.md?plain=1#L12). 
That reminded me to add the new page to the `MDNSidebar`: https://github.com/mdn/yari/pull/10409

2024-01-30 05:15 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
TLDR: No. Let's leave it as it is. I don't "like" this but it isn't worth arguing about as long as your script is run at regularly and is reliable. Also ignore my other comments if this is all agreed.

Outside your control, but I'd be much happier if the automation was much deeper - sidebars and these macros from metadata/BCD and out of the templates. As it is now we have "these macros are needed and so we're making you aware of them, but actually you don't have to know about them". So quite a lot of things for people to know, that can't be removed, but that are irrelevant to them.

2024-01-30 05:17 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +> [update the technology status in `browser-compat-data` repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
OK. I'm probably going to do it anyway on creation, because it is better, but as per https://github.com/mdn/content/pull/31941#discussion_r1470601136 if this is the consensus no worries.

2024-01-30 05:19 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are/should be added
You might want to consider splitting into two headings for "what you need to do" and "what is done for you".

2024-01-30 09:01 UTC, caugner commented
> How about:
> 
>     * feature status
> 
>     * technology status
> 
>     * item status

I would opt for "feature status" to be consistent with browser-compat-data, which documents the feature _support_ status. In this regard, experimental/non-standard/experimental could be considered the "feature _standardization_ status".

2024-01-30 10:46 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are/should be added
> You might want to consider splitting into two headings for "what you need to do" and "what is done for you".

+1, I think this is the important bit for authors and why I was suggesting to strongly word "do not" to avoid manually editing something that is automated / generated.

2024-01-30 10:50 UTC, bsmth commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
>I'd be much happier if the automation was much deeper - sidebars and these macros populated from metadata/BCD and never in the content part of the pages.

I agree, this would be great.

2024-01-30 14:33 UTC, dipikabh reviewed
Few drive-by nits

2024-01-30 14:33 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_landing_page_template/index.md
> +> Do not provide status header macros manually. Refer section ["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_te
```suggestion
> Do not provide status header macros manually. Refer to the section ["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses) to add these statuses to the page.
```

2024-01-30 14:33 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_method_subpage_template/index.md
> +> **Note:** This section is mandatory. If there isn't any parameter, put "None." Instead of the definition list.
```suggestion
> **Note:** This section is mandatory. If there isn't any parameter, put "None." instead of the definition list.
```

2024-01-30 14:33 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/aria_page_template/index.md
> +["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
```suggestion
To include the (appropriate) technology status key — [**experimental**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental), [**deprecated**](/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#deprecated), or **non-standard** — see the section ["How to add or update technology statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Technology_status#how_to_add_or_update_technology_statuses).
```

2024-01-30 14:33 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +When sidebars are rendered, the code looks for the statuses in each page's front-matter.
Even though the "read-only" part is mentioned before, should we again reiterate here:
```suggestion
When sidebars are rendered, the code looks for the statuses in each page's front-matter. As mentioned before, these statuses are updated automatically; you do not need to change them manually.
```

2024-01-30 18:05 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
> TLDR: No. Let's leave it as it is. I don't "like" this but it isn't worth arguing about as long as your script is run at regularly and is reliable. Also ignore my other comments if this is all agreed.
> 
> Outside your control, but I'd be much happier if the automation was much deeper - sidebars and these macros populated from metadata/BCD and never in the content part of the pages.

Yes, see also https://github.com/mdn/yari/pull/8289#issuecomment-1442594111 or https://github.com/mdn/yari/pull/7227. These bots are a workaround for things that should and fairly easily could be in the platform.

2024-01-31 05:01 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are/should be added
done

2024-01-31 05:07 UTC, OnkarRuikar commented
> Class: I would opt for "feature status" to be consistent with browser-compat-data, which documents the feature support status. In this regard, experimental/non-standard/experimental could be considered the "feature standardization status".

We still need to decide what do we call this status thingy:
a) technology status :tada: 
b) feature status :eyes: 
c) feature standardization status :rocket: 

Vote using the emojis.

2024-02-01 22:33 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +> [update the feature status in `browser-compat-data` repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses).
@OnkarRuikar Split works much better for me thanks. 

You could now change this:

```suggestion
[Update the feature status in `browser-compat-data` repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses) in order to change these values.

> **Note:** While you can manually/update these macros in content, values that don't match the browser compatibility data will be replaced/removed.
```

2024-02-01 22:37 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_event_subpage_template/index.md
>  > You should update or delete them according to the advice below:
@OnkarRuikar Shouldn't this be same advice as for the status keys (in all templates). 

I would section these, so for this set something like

```suggestion
> These macros are automatically added by the toolchain (there is no need to add/remove):
```

Then further down "These macros need to be added manually based on ..." or similar

2024-02-02 03:05 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/technology_status/index.md
> +> Do not manually update technology statuses in the `mdn/content` repository. To update a feature's technology status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/b
> Is the code for this automation checked in somewhere? If not, should we put it in GH actions?

At the moment the bot is hosted in [my personal repo](https://github.com/OnkarRuikar/temp/tree/main/.github/workflows). We are planning to move all the current and future bots in more public place like `https://github.com/openwebdocs/content-automation`.  As the end result of the bots' actions are only PRs so it shouldn't matter where they are publicly hosted.

2024-02-02 03:25 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_event_subpage_template/index.md
>  > You should update or delete them according to the advice below:
done

2024-02-06 15:40 UTC, bsmth approved these changes
Thanks, Onkar. Leaving a +1 👍🏻

2024-02-06 17:48 UTC, OnkarRuikar commented
@dipikabh, @hamishwillee , @wbamberg could you give it a final look and merge?

2024-02-06 21:40 UTC, hamishwillee commented
Don't block on my review. However I will give it a look on Friday if it hasn't merged. Thanks @OnkarRuikar for all your work on this one.

2024-02-06 21:47 UTC, wbamberg commented
@OnkarRuikar thank you for the ping. I will take a look tomorrow.

2024-02-07 15:28 UTC, dipikabh approved these changes
Thanks @OnkarRuikar for your work on this! 👍

2024-02-08 00:14 UTC, wbamberg requested changes

2024-02-11 08:07 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +that the [Bluetooth API](/en-US/docs/Web/API/Bluetooth) is only available in a [secure context](/en-US/docs/Web/Security/Secure_Contexts).
Was trying new formatter.

2024-02-11 08:14 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +For example, a page that has `\{{Compat}}` should usually have the `browser-compat` property added in front-matter.
Since contributors do not have to touch these macros, I thought we could mention them less. I've reverted to the old text with some tweaks.

2024-02-11 08:15 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  > For example, the `\{{Compat}}` macro depends on the `browser-compat` metadata value.
Reverted above para so this is still in business.

2024-02-11 08:33 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +If none of the above statuses apply, then the feature is considered `standard`.
Let's not name the default status as `standard`.  How about:
> If none of the above statuses apply, then the feature is considered a stable and standard feature.

***
> More of an issue really is that we link to definitions of "deprecated" and "experimental" but not "non-standard". Maybe out of scope for this PR, though.

A separate PR sounds nice.

2024-02-11 08:45 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
:( We never concluded on the "how to handle multiple compat links on a page" issue. In some conversation there was talk of putting prominent feature in API as the first bcd link and take it's status as the BCD status for the overview page.

The script at the moment takes the first compat link and takes statuses from there. I'll update the script once we conclude. Or let me know if we've concluded the discussion.

2024-02-11 23:39 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
FWIW I disagree with this. If a feature only ever appeared behind a flag it can be immediately removed if the docs on removal from the browser. Why? It was never part of the web platform or expectation if it was only ever behind a preference.

2024-02-11 23:47 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/index.md
> +2. **Feature status**: The [banner indicating the feature status](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#feature_status_page_banners) is automatically added. For that you n
FWIW (i.e. for your consideration) I would have hinted at what feature statuses are like this:

```suggestion
2. **Feature status**: A [banner indicating the feature status](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#feature_status_page_banners) (such as deprecated, non standard, or experimental) is added automatically, if needed. For that you need to [update the status in the browser-compat-data repository](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses).
```

2024-02-11 23:50 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +to indicate that the {{domxref("Bluetooth")}} interface is only available in a [secure context](/en-US/docs/Web/Security/Secure_Contexts).
```suggestion
Banners are added using macros. Banner macros should be inserted below the page metadata, alongside the page sidebar macro. For example, in the block below, the `\{{SecureContext_Header}}` macro has been used to indicate that the {{domxref("Bluetooth")}} interface is only available in a [secure context](/en-US/docs/Web/Security/Secure_Contexts).
```

2024-02-11 23:55 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  Banners are added to some pages, in particular API reference, in order to highlight important factors that will affect how the described content is used.
```suggestion
Banners are displayed in some pages, in particular API reference, in order to highlight important factors that will affect how the described content is used.
```

2024-02-12 00:05 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  For example, banners are used to highlight when a particular interface, method or property is deprecated, and should not be used in production code.
Maybe something like:

```suggestion
For example, banners are used to highlight when a particular interface, method or property is deprecated, and should not be used in production code, or can only be used in a secure context.

Banners are rendered using macros in the page content.
Some banner macros are added automatically to the page, while others are added manually.
```

2024-02-12 00:08 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  > For example, the `\{{Compat}}` macro depends on the `browser-compat` metadata value.
I'm unresolving this because IMO this whole page needs work, and in particular this particular example needs to be modified.

The whole point of the PR is that you don't need to manually add `\{{SeeCompatTable}}` and you shouldn't need to mess with the metadata. So I would no reference compat macro in the section on macros you have to add.

The way I would try  do this is add another section above `## How to add a banner` that shows what macros and data might appear in content. So showing them everything they might see. Then below explain how stuff is added - either automatically or not.

2024-02-12 00:10 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/links/index.md
> +To include an ordered list of links which includes this page and its siblings, write the following:
```suggestion
To include an ordered list of links that includes this page and its siblings, write the following:
```

2024-02-12 00:13 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_constructor_subpage_template/index.md
> +> Do not provide status header macros manually. Refer to the section ["How to add or update feature statuses"](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_f
I think we don't use quotes around section reference
```suggestion
> Do not provide status header macros manually. Refer to the section [How to add or update feature statuses](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses) to add these statuses to the page.
```

2024-02-12 00:16 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/page_types/api_event_subpage_template/index.md
> +>   - : Flags describing the status of this feature. An array which may contain one or more of the following: `experimental`, `deprecated`, `non-standard`. This key should not be set manually: it is
I won't mark any more, but pretty sure we don't quote the names of sections. I recall but have not checked style guide that we refer to: `[section name] of the [Xxxx] topic`

```suggestion
>   - : Flags describing the status of this feature. An array which may contain one or more of the following: `experimental`, `deprecated`, `non-standard`. This key should not be set manually: it is set automatically based on values in the browser compatibility data for the feature. See [How to add or update feature statuses](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses).
```

2024-02-12 05:56 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/index.md
> +2. **Feature status**: A [banner indicating the feature status](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#feature_status_page_banners) (such as deprecated, non standard, or ex
Well yes, but then there are the other cases of this same text :-)

2024-02-12 06:01 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/howto/write_an_api_reference/index.md
> +2. **Feature status**: A [banner indicating the feature status](/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#feature_status_page_banners) (such as deprecated, non standard, or ex
oh. updated the remaining two.

2024-02-12 18:22 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
The main point of this PR is to say: don't update these macros/front matter items manually in mdn/content, because they are derived from BCD. So I think it's important to say, here, how that derivation happens. Currently all it says is:

> The feature statuses of all the features documented on MDN are defined in its accompanying [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD) repository entry

...which doesn't cover the situation where a page has > 1 entries. Minimally we should document this here, even just like "If a page includes more than one BCD entry in the `browser-compat` key, then only the first entry is used to provide feature status values".

I think the rule "only the first" is a bit arbitrary, but at least if it's documented then it can be understood.

In the bigger picture, IMO:
- I don't think we have a good solution for `browser-compat` in API overview pages at the moment. A better solution probably involves Yari work to render compat in overview pages differently (e.g. https://github.com/orgs/mdn/discussions/564#discussioncomment-775202).
- I don't think we should allow `browser-compat` in guide pages
- I don't think we should allow > 1 `browser-compat` in "web platform feature" pages

But there needs to be appetite for doing the design and consensus-building work there and also work to fix the places where this stuff happens...

2024-02-12 21:53 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
@wbamberg Is this a typo? I.e. if something is behind a preference always (i.e. never been released) can't we immediately remove it if that feature is removed from the browser? 

Note that this is the same instruction as the next section which covers the case of when something was released

2024-02-12 22:14 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners should be added
```suggestion
## Banners that must be added manually
```

2024-02-12 22:15 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +## What banners are automatically added
```suggestion
### Banners that must be added automatically
```

2024-02-12 22:16 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  ## How to add a banner
@OnkarRuikar Changes are better, but still not quite right. So this topic is "Banners and notices" but it says nothing about notices. Should it? Assuming yes, we should make this topic level 2 and put the others under it.

Would you like me to take a shot at updating this as I would like it? 

```suggestion
## Banners
```

2024-02-12 22:52 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
I've not thought a lot about these rules tbh. Personally it seems like it would be OK to remove the docs immediately in this situation.

It's a bit odd to see a "guidelines for removing content" section that doesn't mention browser support, which AFAIK is the main rule we use to decide when to delete things. The idea I suppose being that if a feature is still supported, then people might still be using it, so need to have docs. And whether something's deprecated or not is not relevant to that.

> Note that this is the same instruction as the next section which covers the case of when something was released

Almost, except this has (vaguely and unhelpfully):

> At some point in the future, a decision may be made to actually remove the item from the documentation; we don't normally do this but if the item was especially unutilized or uninteresting, we may decide to do so.

...and the other has:

> It's unlikely that these items will be removed from the documentation anytime soon, if ever.

2024-02-12 23:27 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
I think we should explicitly state that we reflect the BCD rules for all these cases. For this particular case that means immediate removal. Otherwise there is no trigger to do so. I could do an update after this gets merged if there is interest.

2024-02-12 23:33 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
> we should explicitly state that we reflect the BCD rules for all these cases

Are you referring to https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features ? Because that says nothing about deprecation, standardization, etc. Which implies that a feature being removed from the specs changes nothing, and makes me wonder why we even cover this in a page about deprecation etc.

2024-02-12 23:59 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/experimental_deprecated_obsolete/index.md
>  If the item was implemented in any release version of any one or more browsers but _only_ behind a preference or a flag, do not delete the item from the documentation immediately. Instead, mark the i
Yes. So for the general case you're right - but for this specific case of something that "should be removed rather than deprecated" it would do no harm.

2024-02-13 07:57 UTC, teoli2003 commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
My understanding is that the automation only happens in reference pages (not guides). @OnkarRuikar Am I wrong?

2024-02-14 17:22 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
> My understanding is that the automation only happens in reference pages (not guides). @OnkarRuikar Am I wrong?

@teoli2003 The script processes all the pages that have `browser-compat` front-matter key. Page types were introduced in the content repo much later. Let me know if you want to have exclude or include page-types list. Do we need a discussion to come up with the list?

> I think the rule "only the first" is a bit arbitrary, but at least if it's documented then it can be understood.

I'll update the PR to add the info.

> I don't think we should allow browser-compat in guide pages

You mean the BCD table below, the status indicators, or both? I could find only 5 guide pages with the statuses so one PR should fix it.

2024-02-15 06:04 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  ## How to add a banner
By notices do you mean `> **Warning:**` and `> **Note:**` at the top of the pages?

> Would you like me to take a shot at updating this as I would like it?

Sure. I've given you access to my fork. Run `gh pr checkout 31941` to get the PR branch in your local.

2024-02-15 23:42 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  ## How to add a banner
> By notices do you mean > **Warning:** and > **Note:** at the top of the pages?

Actually, I meant things like `{{Compat}}` which are mentioned in the section on statuses. They aren't a banner or a notice.

2024-02-16 00:26 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  {{MDNSidebar}}
FYI @OnkarRuikar , I updated this to my taste in https://github.com/mdn/content/pull/31941/commits/07f16a4ba9dceeca29d619ce1c304c5f89c9da69

- Changed from Bluetooth to AudioDecoder, since that actually does require a secure context
- Added the AvailableInWorkersMacro
- Moved the discussion of the frontmatter status into a note where it is relevant.
- Removed link to Page type templates - I guess cross links are useful, but not actually all that useful in this case.
- All headings at same level. The first topic is now "Whare are banner macros added" - it's clearly just showing a single real-world example.

Hope this makes sense to you.

2024-02-16 01:03 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
> You mean the BCD table below, the status indicators, or both? I could find only 5 guide pages with the statuses so one PR should fix it.

I think they are separate questions.

1. **should guide pages be allowed "Browser compatibility" sections?** I think not, because BC sections are a quite formal part of the page and relate to specific web platform features, while guide pages are inherently informal, unstructured, and may cover a lot of different web platform features from different areas. Also I used to think we might one day be able to remove the `{{Compat}}` macro entirely, and have the page builder insert compat at the right place, based on the template, and that presupposes that pages that include BCD have a particular structure. But maybe people disagree.
2. **should guide pages be allowed "feature status" like experimental, deprecated, nonstandard?** I'm less sure about this one.

- If the answer to both these questions is "yes", then we need to explain how this works for guide pages, and in particular that whether a guide page gets a banner depends on which compat query it lists first.
- if the answer to both questions is "no", then we need to say that guide pages aren't allowed to include compat queries _or_ the status front matter 
- If the answer to (1) is "no" and (2) is "yes", then guide pages might want a way to indicate status without including a compat query in the front matter.

>  I could find only 5 guide pages with the statuses so one PR should fix it.

Yeah, skimming through, there are several examples of APIs that are experimental whose guide pages aren't, e.g.
- https://developer.mozilla.org/en-US/docs/Web/API/FedCM_API
- https://developer.mozilla.org/en-US/docs/Web/API/Window_Management_API

That does seem (logically) odd though, doesn't it?

I suppose pragmatically the best thing is probably just to say what this PR currently says, which is that if there is >1 BCD entry, we choose the status of the first one. And leave all these questions for another day.

2024-02-16 01:08 UTC, wbamberg commented on files/en-us/mdn/writing_guidelines/page_structures/feature_status/index.md
> +> Do not manually update feature statuses in the `mdn/content` repository. To update a feature's status, you need to [submit a pull request](https://github.com/mdn/browser-compat-data/blob/main/docs/
Except I don't any references to multiple BCD queries in https://pr31941.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Writing_guidelines/Page_structures/Feature_status#how_to_add_or_update_feature_statuses, is the update somewhere else?

2024-02-19 03:00 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +While most banners are inserted immediately below the page metadata, the `\{{AvailableInWorkers}}` macro is added at the bottom of the first section of text, before the first heading.
Why the strange requirement? Most pages add `{{AvailableInWorkers}}` directly below page metadata. Also, some pages don't added it immediately after first para, e.g. `Web/API/CookieStoreManager` and `Web/API/Headers`.
Some pages have it above `{{InheritanceDiagram}}` and some below the InheritanceDiagram macro.

It would be easy to for the secure context automation if we have a fix location. I suggest it should be directly below the front-matter section like other status banners.

2024-02-19 03:07 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +> The banner macros do not depend on this status metadata (but may one day be generated from it).
"but may one day be generated from it" do we need this?
Ideally we would love for yari to render all 9 status macro's content directly based on BCD. And remove the 9 macros from the platform.

2024-02-19 03:11 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  {{MDNSidebar}}
Thank you @hamishwillee for the changes!

> Changed from Bluetooth to AudioDecoder, since that actually does require a secure context

We are in process of automating the secure context macros so those macros are also going to be in automated macros' list.

2024-02-19 03:41 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +While most banners are inserted immediately below the page metadata, the `\{{AvailableInWorkers}}` macro is added at the bottom of the first section of text, before the first heading.
Because the strange requirement is what I was told to use when I started here, and I expect is the most common pattern in existing docs.

I've always felt the inconsistency odd. If you want to change it then cool, but we should get broad agreement and change it everywhere.

2024-02-19 03:42 UTC, hamishwillee commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
>  {{MDNSidebar}}
Awesome. That will be good. Then this can almost disappear.

2024-02-21 13:44 UTC, OnkarRuikar commented
> Minimally we should document this here, even just like "If a page includes more than one BCD entry in the browser-compat key, then only the first entry is used to provide feature status values".

Done in [above commit](https://github.com/mdn/content/pull/31941/commits/17e0ffd64b52ad9572514d37f164d685d6f37fc5).

2024-02-21 13:47 UTC, OnkarRuikar commented on files/en-us/mdn/writing_guidelines/page_structures/banners_and_notices/index.md
> +While most banners are inserted immediately below the page metadata, the `\{{AvailableInWorkers}}` macro is added at the bottom of the first section of text, before the first heading.
We can take this up in a separate PR or a discussion.

2024-02-21 18:01 UTC, wbamberg approved these changes
👍 thank you Onkar!

2024-02-22 22:44 UTC, hamishwillee approved these changes
The most active reviewers have now approved. Any reason not to merge?

2024-02-22 22:59 UTC, merged

2024-02-23 04:38 UTC, OnkarRuikar commented
Thank you all for the valuable inputs!

2024-02-23 06:03 UTC, hamishwillee commented
Thanks @OnkarRuikar - you've made things better, as always.