DRAFT: Containment module
mdn/content pull request #31950
Opened 2024-01-27 05:54 UTC by estelle

2024-01-30 13:53 UTC, chrisdavidmills requested changes
@estelle Hi there! More wonderful update work here. I've left you a bunch of comments, mostly nothing too major, although in a few places, I did find some of the explanations a little confusing. Let me know what you think of my suggestions anyway; I think some of this could be down to the fact that I am fairly new to container queries, so don't understand them quite as well as other parts of CSS.

2024-01-30 13:53 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +There are two special values of contain that are shorthand for the first three or all four of the containment types:
```suggestion
There are two special values of `contain` that are shorthand for the first three or all four of the containment types:
```

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +The {{cssxref("container-name")}} property specifies a list of query container names. These names can be used by `@container` rules to filter which query containers are targeted. The optional, case-s
```suggestion
The {{cssxref("container-name")}} property specifies a list of query container names. These names can be used by `@container` rules to filter which query containers are targeted. The optional, case-sensitive `<container-name>` filters the query containers that are targeted by the query.
```

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +If the `<style-feature>` includes a value, the style query evaluates to true if the computed value of the given in the CSS declaration or custom property value passed as the `style()` argument is tru
```suggestion
If the `<style-feature>` includes a value, the style query evaluates to true if the value of the CSS property passed as the `style()` argument is the same as that element's computed value of that property for the container being queried. Otherwise, it resolves to false.
```

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/css_containment/index.md
> +- [`@container` descriptors](/en-US/docs/Web/CSS/@container#descriptors):
the descriptors are then listed, so intentionally included the colon. If you still think it needs to go, feel free to merge (in other words, I think it's better with the colon, but if you disagree, not a hill i was considering dying on.

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Another advantage is that if the containing box is offscreen, the browser does not need to paint its contained elements — these are also offscreen as they are contained completely by that box.
I think this is covered enough in "relevant to user" below.

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Despite the name, style containment does not provide scoped styles such as you would get with the [Shadow DOM](/en-US/docs/Web/API/Web_components/Using_shadow_DOM).
```suggestion
Despite the name, style containment does not provide scoped styles such as you would get with the [Shadow DOM](/en-US/docs/Web/API/Web_components/Using_shadow_DOM) or {{cssxref("@scope")}}.
```

2024-01-31 03:43 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Paint containment essentially clips the box to the padding edge of the principal box. There can be no visible overflow. The same things are true for `paint` containment as `layout` containment (see a
```suggestion
Paint containment essentially clips the box to the padding edge of the [principal box]([/en-US/docs/Web/CSS/Visual_formatting_model#the_principal_box](https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model#the_principal_box). There can be no visible overflow. The same things are true for `paint` containment as `layout` containment (see above).
```

2024-01-31 03:44 UTC, estelle commented on files/en-us/web/css/@container/index.md
> +If the `<style-feature>` includes a value, the style query evaluates to true if the computed value of the given in the CSS declaration or custom property value passed as the `style()` argument is tru
reworded

2024-01-31 15:44 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +There are four types of containment: layout, paint, size, and style. Use the {{cssxref("contain")}} property to specify the type or types you want to apply to an element by including any combination
added the explanation to strict.

2024-01-31 15:44 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +If we give each `<article>` the `contain` property with a value of `content`, when new elements are inserted into the page, the browser does not need to recalculate layout or repaint any area outside
rewritten

2024-01-31 15:48 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Paint containment essentially clips the box to the padding edge of the principal box. There can be no visible overflow. The same things are true for `paint` containment as `layout` containment (see a
clarified that i meant additional notes

2024-01-31 15:50 UTC, estelle commented
@chrisdavidmills Thanks for the edit! I think i captured all your feedback.

2024-02-01 11:30 UTC, chrisdavidmills requested changes
@estelle few more bits for you - getting very close now!

2024-02-01 23:57 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +When using `strict`, make sure to include a size!
```suggestion
```

2024-02-01 23:58 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Paint containment essentially clips the box to the padding edge of the [principal box]([/en-US/docs/Web/CSS/Visual_formatting_model#the_principal_box](/en-US/docs/Web/CSS/Visual_formatting_model#the_
```suggestion
Paint containment essentially clips the box to the padding edge of the [principal box](/en-US/docs/Web/CSS/Visual_formatting_model#the_principal_box). There can be no visible overflow. The same additional notes are true for `paint` containment as `layout` containment (see above).
```

2024-02-01 23:58 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +Paint containment essentially clips the box to the padding edge of the [principal box]([/en-US/docs/Web/CSS/Visual_formatting_model#the_principal_box](/en-US/docs/Web/CSS/Visual_formatting_model#the_
fixed

2024-02-01 23:59 UTC, estelle commented on files/en-us/web/css/css_containment/using_css_containment/index.md
> +When using `strict`, make sure to include a size!
done

2024-02-01 23:59 UTC, estelle commented
Thanks @chrisdavidmills

2024-02-02 16:58 UTC, chrisdavidmills approved these changes
@estelle awesome, awesome, awesome

2024-02-02 16:58 UTC, merged