Add docs for `HTMLIFrameElement.allow`
mdn/content pull request #31979
Opened 2024-01-29 12:59 UTC by skyclouds2001

### Description

spec at https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allow

### Motivation

### Additional details

### Related issues and pull requests

2024-01-30 05:50 UTC, teoli2003 requested changes

2024-01-30 05:50 UTC, teoli2003 commented on files/en-us/web/api/htmliframeelement/allow/index.md
> +A string.
We must inform the reader here that this is a space-separated list of policies. Also, we should be sure the list of potential entries is one click away. Is there an explanation under `<iframe>` we could link to?

2024-02-02 08:48 UTC, skyclouds2001 commented on files/en-us/web/api/htmliframeelement/allow/index.md
> +The Permissions Policy specified by the `allow` attribute implements a further restriction on top of the policy specified in the {{HTTPHeader("Permissions-Policy")}} header. It doesn't replace it.
```suggestion
The Permissions Policy specified by the `allow` attribute implements a further restriction on top of the policy specified in the {{HTTPHeader("Permissions-Policy")}} header. It doesn't replace it.

See [`<iframe>`'s Permissions Policy syntax](/en-US/docs/Web/HTTP/Permissions_Policy#iframe_syntax) for more details.
```

2024-02-02 08:48 UTC, skyclouds2001 commented on files/en-us/web/api/htmliframeelement/allow/index.md
> +A string indicates the [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy) specified for this {{HTMLElement("iframe")}} element, each policy must be separated by space. See [`<iframe>`'s Pe
```suggestion
A string indicates the [Permissions Policy](/en-US/docs/Web/HTTP/Permissions_Policy) specified for this {{HTMLElement("iframe")}} element, each policy must be separated by space.
```

2024-05-08 15:26 UTC, teoli2003 approved these changes
👍

2024-05-08 15:26 UTC, merged