CSS :state() pseudo class
mdn/content pull request #32000
Opened 2024-01-30 04:53 UTC by hamishwillee

This add basic docs for the `:state()` pseudo class function. 

This class can be used to match against custom states defined in a custom element. It doesn't make any sense outside of the context of a web component/custom elements. I haven't tried to document/duplicate everything here, but instead just the CSS-ish bits and link to the more full examples.

The BCD for this is here: https://github.com/mdn/browser-compat-data/pull/22083

There isn't a formal CSS spec for this yet (though it is planned and agreed between browser vendors). The docs here currently derive from the definition the HTML live spec here https://html.spec.whatwg.org/multipage/custom-elements.html#exposing-custom-element-states

This is part of doing the work for #31971. I expect more to come, including a definition of the CSS `:part`.

@estelle @dipikabh Would appreciate your review/feedback/advice. This is quite minimalist right now and I am fine with that because I'm mostly hoping to expose the core ideas and provide access to the BCD data. For example, does this "have" to have an interactive example - if so I could perhaps make one similar to the one used for `:defined()`.

2024-01-31 17:39 UTC, dipikabh requested changes
Thanks for adding this page, @hamishwillee! I've added some edit suggestions.

2024-01-31 17:39 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +See [CustomStateSet](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) for a live example this code in action.
```suggestion
See [CustomStateSet](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) for a live example of this code in action.
```

2024-01-31 17:39 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +You can use `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) function pseudo-class to match a state only within the shadow DOM of the current custom element.
```suggestion
You can use `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function to match a state only within the shadow DOM of the current custom element.
```

2024-01-31 17:39 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +For example, in the [`CustomStateSet` labeled checkbox example](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) the following CSS is used to inject a grey `[x]` before the element when it is che
```suggestion
For example, in the [`CustomStateSet` labeled checkbox example](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox), the following CSS is used to inject a grey `[x]` before the element when it is in the "checked" state.
```

2024-01-31 17:39 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +<!-- {{EmbedInteractiveExample("pages/tabbed/pseudo-class-state.html", "tabbed-shorter")}} -->
I think we can remove this comment (maybe track the task via an issue?).

There are a few other pseudo-class pages without interactive examples.In this particular case, adding an interactive example might make more sense after the feature becomes more widely available and can be used without setting any preferences.

2024-01-31 17:39 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +### Styling with a custom state within a custom element
Seems like this can be reworded to better convey the intent.

2024-02-01 22:56 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +### Matching a custom element on a state
Doh.

```suggestion
### Matching a custom state
```

2024-02-01 23:02 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +### Styling with a custom state within a custom element
@dipikabh What I'm trying to do here is differentiate between the previous example which shows how you'd style a custom element that you are using, and this case, where we're styling the custom element inside its implementation.

I think this is better, but would be good for you to check.

```suggestion
### Matching a custom state inside a custom element
```

2024-02-01 23:06 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +You can use `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function to match a state only within the shadow DOM of the current custom element.
```suggestion
Custom elements can also match against a custom state as part of their implementation.
This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
```

2024-02-01 23:22 UTC, estelle reviewed
A lot more has to be done for for discoverability. Here are some ideas:

Add a cross-link to this page from this content:

* [CSS selectors module related concepts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors#related_concepts), right after the listing for `:popover-open`, another HTML defined pseudo-class
* https://developer.mozilla.org/en-US/docs/Web/API/CustomStateSet#interaction_with_css - add a description of `:state()` there.
* https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#custom_states_and_custom_state_pseudo-class_css_selectors

Add these here and then XLink to this `:state()` page as well:

- :host()
- :visited and :hover
- Web/API/Web_components
- CustomStateSet
- [Using custom elements](/en-US/docs/Web/API/Web_components/Using_custom_elements)
- [Using templates and slots](/en-US/docs/Web/API/Web_components/Using_templates_and_slots)
- {{domxref("Element.attachShadow()")}}
- {{domxref("ShadowRoot.adoptedStyleSheets")}}
- {{HTMLelement("template")}}
- {{CSSXref(":host")}}
- {{CSSXref(":host_function", ":host()")}}
- {{CSSXref(":host-context", ":host-context()")}}
- {{CSSXref("::slotted", "::slotted()")}}
- [CSS shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) module
- {{CSSXref("::part")}}



Add this Xlink in this page's see also, but don't add part there:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques

2024-02-01 23:31 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +The CSS `:state()` pseudo-class matches an element when the identifier passed as an argument is present in the `CustomStateSet` of the element.
Thanks @dipikabh . This is better. I modified your text just a little to "(custom elements that are not derived from built-in elements)" as the previous wording implied a subset of autonomous custom elements rather than a different type of custom element (those derived from build in elements).

2024-02-01 23:32 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +## Syntax
```suggestion
The **`:state()`** [CSS](/en-US/docs/Web/CSS) [pseudo-class](/en-US/docs/Web/CSS/Pseudo-classes) matches [custom elements](/en-US/docs/Web/API/Web_components/Using_custom_elements) that have the specified custom state.

## Syntax
```

2024-02-01 23:35 UTC, hamishwillee commented
Thanks very much for the review @dipikabh - much appreciated. Ready for another look.

2024-02-02 16:03 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +The CSS `:state()` pseudo-class matches an element when the identifier passed as an argument is present in the `CustomStateSet` of the element.
Got it, that's a good catch and fix. Thanks!

2024-02-02 17:02 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +### Styling with a custom state within a custom element
I see. This is good as is. Optionally, could it be made more apparent with something like:

> ### Matching a custom state in custom element's shadow DOM

2024-02-02 17:17 UTC, dipikabh approved these changes
This is looking good, thanks @hamishwillee. I've left two suggestions for the second example (heading and first sentence). I can take another look at your updates, but leaving a +1.
Estelle has some great suggestions for cross-linking to this page.

2024-02-02 17:17 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
What do you think rewriting the first sentence like this:
```suggestion
The `:state()` pseudo-class can also be used to match and style custom states within the implementation of custom elements.
This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
```

2024-02-04 22:49 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
A small modification because that implies that we're styling custom states, while we're styling custom elements. 

```suggestion
The `:state()` pseudo-class can also be used to match custom states within the implementation of custom elements.
This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
```

2024-02-04 22:51 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +### Styling with a custom state within a custom element
Yes, that's even better thank you.

2024-02-04 22:51 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +### Matching a custom state inside a custom element
```suggestion
### Matching a custom state in custom element's shadow DOM
```

As per @dipikabh suggestion!

2024-02-05 02:47 UTC, hamishwillee commented
@estelle Thanks, good points. I have been waiting on #31258 to merge as that had fixes to the Web API side. This is now in so have cross linked many of those. The ones I have chosen not to are things like templates & slots that are only peripherally related to states, and hover/visited, which are inbuilt states. 

@dipikabh I accepted your suggestions thanks. But I made some more changes around support for `:state()` following `::part()` that it would be good to sanity check too. The relevant parts are:
- This new example in CustomStateSet https://pr32000.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CustomStateSet#question_box_exposing_states_in_shadow_parts
- This bit of `:state()` that references it https://pr32000.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/:state#matching_a_custom_state_against_a_shadow_part

2024-02-05 18:29 UTC, dipikabh submitted a review, later dismissed
Hi @hamishwillee, I've added my suggestions for the newly added bits

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +The CSS `:state()` pseudo-class can also be used to target the [shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) of a custom element.
```suggestion
The `:state()` pseudo-class can also be used to target the [shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) of a custom element.
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +The shadow parts of a custom element are the parts of its shadow tree that it exposes to a containing page for styling purposes.
Rewording suggestion for compacting
```suggestion
Shadow parts are parts of a custom element's shadow tree that are exposed to a containing page for styling purposes.
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +The [`::part()`](/en-US/docs/Web/CSS/::part) pseudo element is used to match against specific parts, and can be followed by `:state()` to match against parts with a particular state.
```suggestion
The [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element is used to match these parts, and can be followed by the `:state()` pseudo-class to match parts that are in the specified state.
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +For example, consider a custom element named `<question-box>` that uses a `<labeled-checkbox>` custom element as part named `checkbox`:
```suggestion
For example, consider a custom element named `<question-box>` that uses a `<labeled-checkbox>` custom element as a part named `checkbox`:
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +The page CSS can then match against the part, and the part in a particular state, as shown:
```suggestion
The page CSS can then match this part and style it based on its state, in this case `checked`, as shown below:
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +question-box::part(checkbox):state(checked) {
```suggestion
}

question-box::part(checkbox):state(checked) {
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +See the ["Labeled checkbox" in `CustomStateSet`](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) for a live example of this code in action.
```suggestion
For a live example of this code in action, see the ["Labeled checkbox"](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) example on the `CustomStateSet` page.
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +A full (live) example is shown in the `CustomStateSet` example [Question box: exposing states in shadow parts](/en-US/docs/Web/API/CustomStateSet#question_box_exposing_states_in_shadow_parts).
```suggestion
For a live example of this code in action, see the ["Question box"](/en-US/docs/Web/API/CustomStateSet#question_box_exposing_states_in_shadow_parts) example on the `CustomStateSet` page.
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +### Matching a custom state against a shadow part
```suggestion
### Matching a custom state in shadow parts
```

2024-02-05 18:29 UTC, dipikabh commented on files/en-us/web/css/_doublecolon_part/index.md
>  - [CSS shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) module
```suggestion
- [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute
- {{CSSxRef(":state",":state()")}} pseudo-class function
- [`exportparts`](/en-US/docs/Web/HTML/Global_attributes#exportparts) attribute
- [CSS shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) module
```

2024-02-05 23:19 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +Developers can select a custom element with a specific state using the [`:state()`](/en-US/docs/Web/CSS/:state) _custom state pseudo-class_.
I tend to use "you" but never entirely sure. FYI I have been using the "with a specific state" because I've been thinking of the state as some data owned by the element. That's not a useful mental model, so thanks for fixing this.

```suggestion
You can select a custom element that is in a specific state using the [`:state()`](/en-US/docs/Web/CSS/:state) _custom state pseudo-class_.
```

2024-02-05 23:22 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +For example, the following CSS might be used to match a `labeled-checkbox` custom element where the element's `CustomStateSet` contains `checked`, and apply a solid border:
Slight modification

```suggestion
For example, the following CSS matches a `labeled-checkbox` custom element when the element's `CustomStateSet` contains the `checked` state, and applies a `solid` border to the checkbox:
```

2024-02-05 23:29 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +We then use `:state()` after `::part()` to match on `checkbox` parts with the `checked` state:
Don't know why, but I find that hard to parse. Compromise.

```suggestion
The second block follows `::part()` with `:state()` to match the `checkbox` parts that are in the `checked` state:
```

2024-02-05 23:33 UTC, hamishwillee commented on files/en-us/web/css/_doublecolon_part/index.md
>  - [CSS shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) module
Thanks. I just stuck to the previous format, but this is better.

2024-02-05 23:54 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +### Question box: exposing states in shadow parts
Good point

```suggestion
### Matching a custom state in the shadow parts of a custom element
```

2024-02-05 23:56 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +For a live example of this code in action, see the ["Question box"](/en-US/docs/Web/API/CustomStateSet#question_box_exposing_states_in_shadow_parts) example on the `CustomStateSet` page.
```suggestion
For a live example of this code in action, see the ["Question box"](/en-US/docs/Web/API/CustomStateSet#matching_a_custom_state_in_a_shadow_part_of_a_custom_element) example on the `CustomStateSet` page.
```

2024-02-06 00:00 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +### Matching a custom state in shadow parts
```suggestion
### Matching a custom state in a shadow part
```

2024-02-06 00:04 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +The [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element is used to match these parts, and can be followed by the `:state()` pseudo-class to match parts that are in the specified state.
"Shadow parts" on these lines looks repetitive.

```suggestion
Shadow parts are parts of a custom element's shadow tree that are exposed to a containing page for styling purposes.
They are defined and named using the [`part`](/en-US/docs/Web/HTML/Global_attributes#part) attribute.
The [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element is used to match shadow parts, and can be followed by the `:state()` pseudo-class to match parts that are in the specified state.
```

2024-02-06 00:04 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +For example, consider a custom element named `<question-box>` that uses a `<labeled-checkbox>` custom element as a part named `checkbox`:
```suggestion
For example, consider a custom element named `<question-box>` that uses a `<labeled-checkbox>` custom element as a shadow part named `checkbox`:
```

2024-02-06 00:12 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +The page CSS can then match against the part, and the part in a particular state, as shown:
Slight modification

```suggestion
The page CSS can then match the `checkbox` part and style it based on its `checked` state, as shown below:
```

2024-02-06 00:13 UTC, keithamus commented on files/en-us/web/api/customstateset/index.md
> +    const shadowRoot = this.attachShadow({ mode: "closed" });
The difference between an open vs closed shadowroot is quite small, so the meaningful benefits of encapsulation are already provided with an open shadowroot. Closed shadowroots are ever so slightly stricter, but can cause surprising ramifications for the developer. The biggest is that `el.shadowRoot` will be `null` even though the element does have a ShadowRoot. Some smaller ramifications are that `.composedPath()` on composed events emitted from within the shadowroot will elide shadow elements, and `.assignedSlot` on an element will always be `null` even if that element is assigned to a closed shadowroot slot. These seem like very small differences but can cause developer confusion unless the developer is keenly aware of these changes. Given that, my opinion is that unless the example is specifically requiring a closed shadowroot (for example for the purposes of demonstrating the above) it should default to `"open"` so that examples that get copy/pasted don't end up hitting these gotchas.

2024-02-06 00:24 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +    const shadowRoot = this.attachShadow({ mode: "closed" });
@keithamus Thanks for that explanation. For this example I am happy to change it.

As far as I can tell little of the above is explained in https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow - which is the point you would make the decision. It is spread around in https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot (fact that this is `null` if mode was attached as closed), https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath() - etc.

Do you think you might be able to add some reasoning in https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow as you have done here to explain this. I would expect that to cover why you would choose to use `closed` - I mean the spec authors must have seen it as useful at some point?

2024-02-06 00:30 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +  background: grey;
```suggestion
:host(:state(checked))::before { 
  content: "[x]";
```

2024-02-06 00:34 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +This is achieved by using `:state()` within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function, which matches a state only within the shadow DOM of the current custom element.
I don't want to do this because I'm lazy. But I agree with you.

2024-02-06 01:14 UTC, hamishwillee commented
@dipikabh Thanks for that through review. I've merged most of them "as is", and a few with minor modification. Otherwise the only significant adjustment since you saw this last is that I moved info in `:state()` to the intro.

@keithamus Thanks for your suggestions. I accepted both.

2024-02-06 02:31 UTC, hamishwillee commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +(See [Firefox bug 1861466](https://bugzil.la/1861466) and [Firefox bug 1866351](https://bugzil.la/1866351) for more details.)
FYI this is new. Rework now we have `:state(mystate)` not `--mystate` syntax.

2024-02-06 14:13 UTC, dipikabh commented on files/en-us/web/api/customstateset/index.md
> +For example, the following CSS might be used to match a `labeled-checkbox` custom element where the element's `CustomStateSet` contains `checked`, and apply a solid border:
This is good, thanks

2024-02-06 15:45 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +For a live example of this code in action, see the ["Labeled checkbox"](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) example on the `CustomStateSet` page.
IIRC we don't use quotes around section and page names
```suggestion
For a live example of this code in action, see the [Labeled checkbox](/en-US/docs/Web/API/CustomStateSet#labeled_checkbox) example on the `CustomStateSet` page.
```

2024-02-06 15:45 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +For a live example of this code in action, see the ["Matching a custom state in a shadow part of a custom element"](/en-US/docs/Web/API/CustomStateSet#matching_a_custom_state_in_a_shadow_part_of_a_cu
```suggestion
For a live example of this code in action, see the [Matching a custom state in a shadow part of a custom element](/en-US/docs/Web/API/CustomStateSet#matching_a_custom_state_in_a_shadow_part_of_a_custom_element) example on the `CustomStateSet` page.
```

2024-02-06 15:45 UTC, dipikabh commented on files/en-us/web/css/_colon_state/index.md
> +Additionally, the [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element followed by the `:state()` pseudo-class allows matching on the [shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) of a cust
Thank you!

2024-02-06 16:16 UTC, dipikabh submitted a review, later dismissed
Thanks for incorporating the feedback, @hamishwillee! This is getting pretty close.
A few more bits and bobs to tweak

2024-02-06 16:16 UTC, dipikabh commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +After adding `<my-custom-element>` to the HTML we can use the identifier added to the `CustomStateSet`, passed to the [`:state()`](/en-US/docs/Web/CSS/:state) function, as a custom state pseudo-class
```suggestion
After adding `<my-custom-element>` to the HTML, we can use the identifier added to `CustomStateSet` and pass it to the [`:state()`](/en-US/docs/Web/CSS/:state) pseudo-class for matching the custom element's custom state.
```

2024-02-06 16:16 UTC, dipikabh commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +The `:state()` pseudo class can also be used within the [`:host()`](/en-US/docs/Web/CSS/:host_function) CSS pseudo-class function to match a custom state [within custom element's shadow DOM](/en-US/d
It is a long sentence, splitting for readability
```suggestion
The `:state()` pseudo-class can also be used within the [`:host()`](/en-US/docs/Web/CSS/:host_function) pseudo-class function to match a custom state [within a custom element's shadow DOM](/en-US/docs/Web/CSS/:state#matching_a_custom_state_in_a_custom_elements_shadow_dom). Additionally, the `:state()` pseudo-class can be used after the [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element to match the [shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) of a custom element that is in a particular state.
```

2024-02-06 16:16 UTC, dipikabh commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +There several live examples in {{domxref("CustomStateSet")}} showing how this works.
```suggestion
There are several live examples in {{domxref("CustomStateSet")}} showing how this works.
```

2024-02-08 22:54 UTC, hamishwillee commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +#### Custom element custom states
The inconsistency does not bother me, but if we need it, then this is more accurate:

```suggestion
#### CustomStateSet and the :state() pseudo-class: States for custom elements
```

2024-02-08 22:59 UTC, hamishwillee commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +Custom states are represented as custom identifers that can be added to, or removed from, the element's {{domxref("ElementInternals.states")}} property (a {{domxref("CustomStateSet")}}). The CSS [`:s
Styling on `states` optional - it is a code variable too so not "wrong". On balance removal is better.

2024-02-08 23:03 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +Additionally, the [`::part()`](/en-US/docs/Web/CSS/::part) pseudo-element followed by the `:state()` pseudo-class allows matching on the [shadow parts](/en-US/docs/Web/CSS/CSS_shadow_parts) of a cust
FWIW I am not a fan of making the "aside" into its own sentence and comment - the way I had it makes it more clear that the aside is associated with the first comment. I appreciate that this approach is common even though it is IMO ugly. Accepting as I always accept editorial comments unless clearly wrong or worse.

2024-02-08 23:05 UTC, hamishwillee commented on files/en-us/web/css/_colon_state/index.md
> +For a live example of this code in action, see the ["Matching a custom state in a shadow part of a custom element"](/en-US/docs/Web/API/CustomStateSet#matching_a_custom_state_in_a_shadow_part_of_a_cu
Arrggg. I know that. Thanks for catching.

2024-02-08 23:25 UTC, hamishwillee commented on files/en-us/web/api/web_components/using_custom_elements/index.md
> +After adding `<my-custom-element>` to the HTML we can use the identifier added to the `CustomStateSet`, passed to the [`:state()`](/en-US/docs/Web/CSS/:state) function, as a custom state pseudo-class
Tweaked

```suggestion
We can use the identifier added to the custom element's `CustomStateSet` (`this._internals.states`) for matching the element's custom state.
This is matched by passing the identifier to the [`:state()`](/en-US/docs/Web/CSS/:state) pseudo-class.
```

2024-02-08 23:29 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +The shadow DOM is attached with `mode: 'closed'` to ensure that nodes within the shadow DOM are not available from outside the element, unless explicitly exposed as a [shadow part](/en-US/docs/Web/CS
Good catch. I'm just going to remove this line as it is no longer needed if we're not going to hide the shadow dom.

```suggestion
```

2024-02-08 23:47 UTC, hamishwillee commented on files/en-us/web/api/customstateset/index.md
> +### Labeled checkbox
It is good to fix now. Done in https://github.com/mdn/content/pull/32000/commits/12d3853e225af472515309dc9623a7bc52c4c860

2024-02-08 23:48 UTC, hamishwillee commented
Thanks @dipikabh - I hope you don't have reviewer fatigue. All suggestions either merged or addressed.

2024-02-09 19:44 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +#### Custom element custom states
This is good, thanks

2024-02-09 20:21 UTC, dipikabh commented
> Thanks @dipikabh - I hope you don't have reviewer fatigue.

Not at all, I enjoy the process. Thanks for your patience!

> What about this case where the experimental feature rolled out in an older release and this is just a minor feature update
> Do we go back and delete the note when the feature is permanent?

Do you mean from [this section](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/122#experimental_web_features) on the main release page? No, we don't delete the note from here, but we do delete the entry from the [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) page after it reaches a stable version, as per our usual process.

But I think you've raised a good point and this might be an oversight in the new process. For an experimental feature that has become stable, if we have an entry in the main release page (of a past release) but no entry in the "Experimental features" page, there is no way to show if and when a feature went experimental --> stable. We don't do that now either, but with the new process, would it mean going back to an older entry in the "Experimental web features" section on the main release page and linking the feature to the release note in which it became stable? I'll bring this up for discussion with the content team.

> Upshot, I don't plan to update the 122 release note for this :-)

121 would have needed an update ;)

2024-02-09 20:23 UTC, dipikabh approved these changes
Thank you @hamishwillee for addressing the comments and for your work on updating these docs!

2024-02-09 20:23 UTC, merged