Fix globals, part 1: indexedDB
mdn/content pull request #32040
Opened 2024-01-31 21:01 UTC by wbamberg

This is the first piece of updating globals, as discussed in https://github.com/orgs/mdn/discussions/360.

It updates a single page, [`indexedDB`](https://developer.mozilla.org/en-US/docs/Web/API/indexedDB), as a test.

The procedure is:
- yarn content move the global page to be under `Window`.
- update the page under `Window` to be an instance property page, and update the content accordingly
- create a new version of the page under `WorkerGlobalScope`, that's worker-specific
- manually delete the redirect from `Web/API/WorkerGlobalScope/indexedDB` to `Web/API/indexedDB`

The BCD is still weird, "api.indexedDB" rather than "api.Window.indexedDB", but I'm not going to try to fix that here.

(In this PR I also updated the main `WorkerGlobalScope` page to not have a separate section for nonstandard members. For the sake of simplicity, I probably should have left that alone.)

2024-02-01 07:34 UTC, teoli2003 requested changes

2024-02-01 07:34 UTC, teoli2003 commented on files/en-us/web/api/window/indexeddb/index.md
> +The **`Window.indexedDB`** read-only property provides a mechanism for applications to
This is what the template say.
```suggestion
The **`indexedDB`** read-only property of the {{domxref("Window")}} interface provides a mechanism for applications to
```

Note that we could have replaced _interface_ by _global scope_ to stress the difference between a property that is on Window-the-interface (`window.height`) vs on Window-the-global-scope (`window.indexedDB`).

Also, we could add a note saying that this property is usually called without a global object: `indexedDB`.

2024-02-01 07:34 UTC, teoli2003 commented on files/en-us/web/api/workerglobalscope/indexeddb/index.md
> +The **`WorkerGlobalScope.indexedDB`** read-only property provides a mechanism for workers to
Same comment than for the other page.

2024-02-01 17:58 UTC, wbamberg commented on files/en-us/web/api/window/indexeddb/index.md
> +The **`Window.indexedDB`** read-only property provides a mechanism for applications to
> Note that we could have replaced interface by global scope to stress the difference between a property that is on Window-the-interface (window.height) vs on Window-the-global-scope (window.indexedDB).

Sorry for my ignorance, but what is the difference? And I don't see a `height` property of `Window`.

2024-02-01 18:20 UTC, wbamberg commented on files/en-us/web/api/window/indexeddb/index.md
> +The **`Window.indexedDB`** read-only property provides a mechanism for applications to
> Also, we could add a note saying that this property is usually called without a global object: indexedDB.

Which Window properties is this not true of, and why? For instance we don't say this in the page for `console` but it also seems to be common practice there. If we wanted to do this I'd like it to be consistent.

2024-02-29 04:16 UTC, OnkarRuikar commented on files/en-us/web/api/workerglobalscope/index.md
>  - {{domxref("indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}
```suggestion
- {{domxref("Window/indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}
```

2024-02-29 04:46 UTC, OnkarRuikar commented
Don't know why
- https://pr32040.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/indexedDB
- https://pr32040.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WorkerGlobalScope/indexedDB 

still redirect and throw 404?

May be rebasing will help.

2024-02-29 05:52 UTC, wbamberg commented
> Don't know why
> 
>     * https://pr32040.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/indexedDB
> 
>     * https://pr32040.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WorkerGlobalScope/indexedDB
> 
> 
> still redirect and throw 404?
> 
> May be rebasing will help.

I _think_ but am not sure that preview doesn't handle changes to redirects. I think these links work locally.

2024-02-29 19:04 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/index.md
>  - {{domxref("indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}
I can only find 5:

```
files/en-us/web/api/window/index.md
60:- {{domxref("indexedDB", "Window.indexedDB")}} {{ReadOnlyInline}}

files/en-us/web/api/workerglobalscope/index.md
30:- {{domxref("indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}

files/en-us/web/api/indexeddb_api/index.md
38:  - : Provides access to a database. This is the interface implemented by the global object {{domxref("indexedDB")}} and is therefore the entry point for the API.

files/en-us/web/progressive_web_apps/how_to/share_data_between_apps/index.md
282:In this code example, the shared files are extracted from the form data and the user is redirected to a different page. It's up to you, using the code in your service worker, to handle the extracted files as you want. For example, you can send them to your app's main JavaScript code using the {{domxref("Worker.postMessage()")}} method or store them in an {{domxref("IndexedDB")}} database which can be accessed both by your service worker and app's main JavaScript code.

files/en-us/mozilla/firefox/releases/38/index.md
87:- The prefixed version of {{domxref("indexedDB")}}, `mozIndexedDB` has been removed ([Firefox bug 975699](https://bugzil.la/975699)).
```

...can you list the others please?

2024-03-01 06:07 UTC, OnkarRuikar commented on files/en-us/web/api/workerglobalscope/index.md
>  - {{domxref("indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}
> ...can you list the others please?

My bad. The regex included `{{domxref("IndexedDB API", "IndexedDB", "", "nocode")}}` as well.
However following could be changed

https://github.com/mdn/content/blob/d77e0bb76025b0a9aed9cff2573588f053fac924/files/jsondata/GroupData.json#L871

to one of the following:
- `"properties": ["Window.indexedDB"],`
- `"properties": ["Window.indexedDB", "WorkerGlobalScope.indexedDB"],`

2024-03-01 07:09 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/index.md
>  - {{domxref("indexedDB", "WorkerGlobalScope.indexedDB")}} {{ReadOnlyInline}}
Ah, good call on groupdata -> https://github.com/mdn/content/pull/32040/commits/e9fbac97121ecd66891fb6d2d35e120b8b9a8364.

2024-04-04 08:08 UTC, teoli2003 approved these changes
Thank you for the change.

This looks exactly how I expect globals to be. (We point to the same BCD id, which is the right thing to do for now)

2024-04-04 08:08 UTC, merged