Content update of Notification in Service Worker
mdn/content pull request #32099
Opened 2024-02-03 18:04 UTC by skyclouds2001

### Description

move the note in `ServiceWorkerGlobalScope.notificationclose` event to `Notification()` constructor

and update content indicating relative event on `Notification` in `ServiceWorkerGlobalScope.notificationclick`

also update example description by replacing event handler property usage to event

### Motivation

### Additional details

### Related issues and pull requests

2024-02-08 22:06 UTC, hamishwillee commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
Flyby. If the parent is optional, aren't all of the sub items (i.e why not action and title too)? Or are you saying that IFF `actions` is specified, then the `action` and `title` must be specified, but `icon` is optional?

2024-02-08 23:14 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
> IFF actions is specified, then the action and title must be specified, but icon is optional?

Basically, yes:
- `options` is optional (https://notifications.spec.whatwg.org/#service-worker-api)
-  `options` has an optional attribute `actions` (https://notifications.spec.whatwg.org/#dictdef-notificationoptions)
- `actions` is an array of `NotificationAction` objects, which have mandatory `action` and `title` properties, and an optional `icon` property (https://notifications.spec.whatwg.org/#dictdef-notificationaction)

2024-02-08 23:24 UTC, wbamberg commented on files/en-us/web/api/notification/notification/index.md
> +> **Note:** Trying to create a notification inside the {{domxref("ServiceWorkerGlobalScope")}} using the `Notification()` constructor will throw a `TypeError`, you should use {{domxref("ServiceWorker
```suggestion
> **Note:** Trying to create a notification inside the {{domxref("ServiceWorkerGlobalScope")}} using the `Notification()` constructor will throw a `TypeError`. Use {{domxref("ServiceWorkerRegistration.showNotification()")}} instead.
```

[comma splice](https://en.wikipedia.org/wiki/Comma_splice)

2024-02-08 23:24 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
Although weirdly it seems as if, if you call this constructor, you must not pass any actions, or you get a TypeError exception? https://notifications.spec.whatwg.org/#create-a-notification

2024-02-08 23:47 UTC, wbamberg requested changes

2024-02-08 23:47 UTC, wbamberg commented on files/en-us/web/api/notifications_api/using_the_notifications_api/index.md
> +  - api.ServiceWorkerRegistration.getNotifications
Guide pages don't have Browser compatibility sections. The section and the front matter key should be removed.

2024-02-08 23:47 UTC, wbamberg commented on files/en-us/web/api/notifications_api/using_the_notifications_api/index.md
> +spec-urls: https://notifications.spec.whatwg.org/
Same for "Specifications".

2024-02-08 23:47 UTC, wbamberg commented on files/en-us/web/api/serviceworkerglobalscope/notificationclick_event/index.md
> +_Inherits properties from its ancestor, {{domxref("ExtendableEvent")}} and {{domxref("Event")}}_.
```suggestion
_Inherits properties from its ancestors, {{domxref("ExtendableEvent")}} and {{domxref("Event")}}_.
```

2024-02-08 23:59 UTC, hamishwillee commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
Thanks. 

> Although weirdly it seems as if, if you call this constructor, you must not pass any actions, or you get a TypeError exception? https://notifications.spec.whatwg.org/#create-a-notification

It says "If a serviceWorkerRegistration was not provided and options["[actions](https://notifications.spec.whatwg.org/#dom-notificationoptions-actions)"] is not [empty](https://infra.spec.whatwg.org/#list-empty), then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror)."

So you you can only have actions if the serviceworker registration is provided.

Looking through this there are lots of missing cases that can throw a typerror

2024-02-09 00:43 UTC, wbamberg commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
> So you you can only have actions if the serviceworker registration is provided.

Right, but that operation I linked, https://notifications.spec.whatwg.org/#create-a-notification , can I think be reached from two paths:
- calling the `Notification()` constructor (https://notifications.spec.whatwg.org/#ref-for-create-a-notification)
- calling `ServiceWorkerRegistration.showNotification()` (https://notifications.spec.whatwg.org/#ref-for-create-a-notification%E2%91%A0)

...and it's only in the second of these cases that the registration gets passed. So if you call the constructor, you must not provide actions.

2024-02-09 05:45 UTC, skyclouds2001 commented on files/en-us/web/api/serviceworkerregistration/shownotification/index.md
> +        - `icon` {{optional_inline}}
> Right, but that operation I linked, https://notifications.spec.whatwg.org/#create-a-notification , can I think be reached from two paths:
> 
> * calling the `Notification()` constructor (https://notifications.spec.whatwg.org/#ref-for-create-a-notification)
> * calling `ServiceWorkerRegistration.showNotification()` (https://notifications.spec.whatwg.org/#ref-for-create-a-notification%E2%91%A0)
> 
> ...and it's only in the second of these cases that the registration gets passed. So if you call the constructor, you must not provide actions.

yes, `actions` parameter can not use with `Notification()` constructor

2024-02-09 17:24 UTC, wbamberg approved these changes
👍 thank you!

2024-02-09 17:24 UTC, merged