FIx #32105 | Fix incorrect note about `autocomplete` attribute of `<input>` element of `button` type
mdn/content pull request #32112
Opened 2024-02-04 18:59 UTC by skyclouds2001

### Description

relates with #31605 

### Motivation

### Additional details

### Related issues and pull requests

fixes #32105

2024-02-05 00:53 UTC, dawei-wang commented on files/en-us/web/html/element/input/button/index.md
> +> **Note:** Firefox will, unlike other browsers, by default, [persist the dynamic disabled state](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resettin
```suggestion
> **Note:** Firefox will, unlike other browsers, by default, [persist the dynamic disabled state](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing) of an `<input>` element of type `button` across page loads. Use the [`autocomplete`](/en-US/docs/Web/HTML/Element/input#autocomplete) attribute to control this feature.
```

2024-02-05 06:03 UTC, ShubhamOulkar reviewed
Following pages need note about firefox default behavior. 
 
- [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
- [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
- [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete

I had tested for `range`, `checkbox` and `radio` input types.


### sample code

```html
<input type="checkbox" id="firefox" />
<input id="_1" type="button" value="checked" />
<input id="_2" type="button" value="unchecked" />
```

```js
const firefox = document.querySelector("#firefox");
const _1 = document.querySelector("#_1");
const _2 = document.querySelector("#_2");

_1.addEventListener("click", () => {
  firefox.checked = true;
});

_2.addEventListener("click", () => {
  firefox.checked = false;
});

```

2024-02-05 08:51 UTC, skyclouds2001 commented
> Following pages need note about firefox default behavior.
> 
> * [ ]  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range
> * [ ]  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
> * [ ]  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete (it is necessary to put note on this page)
> 
> I had tested for `range`, `checkbox` and `radio` input types.

I've search the stackflow link https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing, and it existed in following documentations:

- Web/HTML/Attributes/autocomplete
- Web/HTML/Element/button [a mistake here and should be removed]
- Web/HTML/Element/input
- Web/HTML/Element/input/button
- Web/HTML/Element/input/checkbox
- Web/HTML/Element/input/radio

2024-02-05 08:58 UTC, skyclouds2001 commented on files/en-us/web/html/element/input/button/index.md
> +> **Note:** Firefox will, unlike other browsers, by default, [persist the dynamic disabled state](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resettin
> This note is about using `autocomplete` attribute for elements that accept data/validation from a user. This note is added because we might use type=button to dynamically update other input type elements.

Good opinion!

> Button are passive by default (value attribute for input buttons is name of a button), so we can't put `autocomplete` on buttons.

Yes, it is true.

> Also I like to mention that `<input type="button">'s` are similar to `<button type="button">'s`.
> Same for `submit` and `reset`.

Agree, but I think it is another task, and not willing to including in this PR.

2024-02-06 02:53 UTC, ShubhamOulkar commented
> so I assume above documentations need not to add more note

yup, Notes are present.

2024-02-06 20:53 UTC, dipikabh requested changes
Thanks @skyclouds2001 for this work. Thank you and @ShubhamOulkar both for checking other pages that might need to be updated 🙌 

I have added a few suggestions along with the rewording edit.

2024-03-07 22:07 UTC, dipikabh approved these changes

2024-03-07 22:08 UTC, dipikabh commented
Hi @skyclouds2001, I understand things can get busy. To keep the momentum going on this PR and so that it doesn't become stale, I've gone ahead and merged it with the changes I suggested.

I've also adjusted the PR description to remove `fixes` until we've addressed all the pages that need to be updated for a complete fix.

Appreciate your understanding and contributions!

2024-03-07 22:08 UTC, merged