Add `download` attribute for `<a>` on `<video>` element page's examples
mdn/content pull request #32127
Opened 2024-02-05 15:31 UTC by skyclouds2001

### Description

inspired by #29287 

### Motivation

### Additional details

### Related issues and pull requests

2024-02-05 19:38 UTC, dipikabh requested changes
Hi @skyclouds2001, thanks for adding the `download` attribute! The changes look good, except for one case where I've left a question.

2024-02-06 04:23 UTC, skyclouds2001 commented on files/en-us/web/html/element/video/index.md
> +  >
```suggestion
  <a href="https://archive.org/details/BigBuckBunny_124">download it</a>
```

2024-02-06 04:27 UTC, skyclouds2001 commented on files/en-us/web/html/element/video/index.md
> +    download="BigBuckBunny_124"
yes, the link is a website, so the `download` attribute should not be added

2024-02-06 14:04 UTC, dipikabh approved these changes
Thanks for your contribution, @skyclouds2001!

2024-02-06 14:04 UTC, merged