FF123 updates for permission publickey-credentials-create
mdn/content pull request #32135
Opened 2024-02-06 04:25 UTC by hamishwillee

FF123 supports Feature policy [`publickey-credentials-create`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create) in https://bugzilla.mozilla.org/show_bug.cgi?id=1870863
As per usual for FF, this can't be set on the header, but only via `allow` on the frame. 

This attempts to update the docs with some corrections according to advice from engineers and my interpretation of the spec. Note that I think there are probably more relevant exceptions, but I don't propose to go through all the specs right now.

The specific issues fixed are:
1. Docs say creating/getting a credential is a `SecurityError`. Spec says `NotAllowedError` [in step 5 here](https://w3c.github.io/webappsec-credential-management/#algorithm-create)
2. If allow is declared in an iframe then transient activation is required on the iframe as well, or you get the same error.
3. This explicitly said you can't use `create()` in an iframe, but that was changed in WebAuthn spec in https://github.com/w3c/webauthn/pull/1801 and to the Credential Management spec in https://github.com/w3c/webappsec-credential-management/pull/209. I added some examples.

Other docs work can be tracked in #31890

2024-02-06 04:28 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +Both directives have a default allowlist value of `"self"`, meaning that by default these methods can be used in top-level document contexts. In addition, `get()` can be used in nested browsing conte
Note, it is not clear to me whether `get()` also allows cross origin use now.

2024-02-06 08:09 UTC, dasJ commented on files/en-us/web/api/web_authentication_api/index.md
> +Both directives have a default allowlist value of `"self"`, meaning that by default these methods can be used in top-level document contexts. In addition, `get()` can be used in nested browsing conte
Since 118: https://phabricator.services.mozilla.com/D174108

2024-02-06 08:11 UTC, dasJ commented on files/en-us/web/api/web_authentication_api/index.md
> +   Permissions-Policy: publickey-credentials-set=*
Shouldn't this be `publickey-credentials-create`?

2024-02-09 01:13 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +   Permissions-Policy: publickey-credentials-set=*
```suggestion
   Permissions-Policy: publickey-credentials-create=*
```

2024-02-09 01:13 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +   Permissions-Policy: publickey-credentials-set=("https://*.auth.provider.com")
```suggestion
   Permissions-Policy: publickey-credentials-create=("https://*.auth.provider.com")
```

2024-02-09 01:25 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +Both directives have a default allowlist value of `"self"`, meaning that by default these methods can be used in top-level document contexts. In addition, `get()` can be used in nested browsing conte
Thanks. 
```suggestion
Both directives have a default allowlist value of `"self"`, meaning that by default these methods can be used in top-level document contexts.
In addition, `get()` can be used in nested browsing contexts loaded from the same origin as the top-most document. `get()` and `create()` can be used in nested browsing contexts loaded from the different origins to the top-most document (i.e. in cross-origin `<iframes>`), if allowed by the `Permission-Policy`s [`publickey-credentials-get`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-get) and [`publickey-credentials-create`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create), respectively.
```

2024-02-09 01:44 UTC, hamishwillee commented on files/en-us/web/http/headers/permissions-policy/publickey-credentials-create/index.md
> +The {{jsxref("Promise")}} will also reject with a `NotAllowedError` if access to the feature is granted by [`allow=` on an iframe](/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes) and the fra
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1870863#c8 transient activation is required for a cross-origin `create()` that is allowed by a permission policy on an iframe, but not otherwise (same origin, or for `get()`)

```suggestion
The {{jsxref("Promise")}} will also reject with a `NotAllowedError` if the feature is granted by [`allow=` on an iframe](/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes) and the frame does not also have {{glossary("Transient activation")}}, but only if the method is called cross-origin.
```

2024-02-09 01:51 UTC, hamishwillee commented on files/en-us/web/http/headers/permissions-policy/publickey-credentials-get/index.md
> +The {{jsxref("Promise")}} will also reject with a `NotAllowedError` if access to the feature is granted by [`allow=` on an iframe](/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes) and the fra
Transient activation not required for get
```suggestion
```

2024-02-09 02:02 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +In addition, `get()` can be used in nested browsing contexts loaded from the same origin as the top-most document. `get()` and `create()` can be used in nested browsing contexts loaded from the diffe
```suggestion
In addition, `get()` can be used in nested browsing contexts loaded from the same origin as the top-most document. `get()` and `create()` can be used in nested browsing contexts loaded from the different origins to the top-most document (i.e. in cross-origin `<iframes>`), if allowed by the `Permission-Policy`s [`publickey-credentials-get`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-get) and [`publickey-credentials-create`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create), respectively.
For cross-origin `create()` calls allowed by a permission policy defined on an `<iframe>`, the frame must also have {{glossary("Transient activation")}}.
```

2024-02-09 02:19 UTC, hamishwillee commented
Thanks @dasJ and @jschanck. I've fixed up the issues and also clarified the cases where Transient activation are required.

2024-02-09 04:31 UTC, wbamberg commented on files/en-us/web/api/credentialscontainer/create/index.md
> +    - The function is called cross-origin when the {{HTTPHeader("Permissions-Policy/publickey-credentials-create","publickey-credentials-create")}} policy is set by [`allow=` on an iframe](/en-US/doc
I found this a bit hard to understand. For one thing I thought having "is set by `allow=` on an iframe" but linking to /en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes - which is billed as an example* - is odd. Why not link to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow here?  

\* pet peeve of mine is when examples introduce new normative information instead of being illustrative

But that apart it reads like there are three conditions here that give rise to the exception:
1. cross-origin call
2. `publickey-credentials-create` is set on the iframe (and not sure what "(and permitted)" means)
3. the iframe does not have transient activation

But (2) doesn't look like a reason for _failure_, it looks like a prerequisite for _success_, no?

So could we put it like this:

```suggestion
    - The function is called cross-origin but the iframe's [`allow`](/en-US/docs/Web/HTML/Element/iframe#allow) attribute does not set the appropriate {{HTTPHeader("Permissions-Policy/publickey-credentials-create","publickey-credentials-create")}} policy.
    - The function is called cross-origin and the iframe does not have {{glossary("transient activation")}}.
```

...i.e. list two failure conditions? Is that even correct? If it is, this is easier me to to understand at any rate.

2024-02-09 05:12 UTC, hamishwillee commented on files/en-us/web/api/credentialscontainer/create/index.md
> +    - The function is called cross-origin when the {{HTTPHeader("Permissions-Policy/publickey-credentials-create","publickey-credentials-create")}} policy is set by [`allow=` on an iframe](/en-US/doc
@wbamberg 
With respect to the conditions, I think you have it. 
To make a cross origin call you need an iframe `allow` that specifies an appropriate policy to allow the gated feature to be used in the origin of the loaded file. The iframe also needs transient activation - i.e. it will fail unless both conditions are met. However it will not fail if the iframe is same origin even without transient activation. 

I'm going to merge this, but ...

I linked to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes because that actually explains how to use permission policy and iframes, while https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow says what it is for and then links to the top level Permissions-Policy doc. 

So essentially to find the information needed to actually use this feature now requires two clicks and some luck.
  
We could provide the more direct link I specify from `allow`, and perhaps also have an example here? 
OR we could create a proper standalone doc for iframe allow attribute - is there a model to copy for attributes? I see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly and similar but these all appear to be globals. Thoughts?

2024-02-09 05:25 UTC, wbamberg commented on files/en-us/web/api/credentialscontainer/create/index.md
> +    - The function is called cross-origin when the {{HTTPHeader("Permissions-Policy/publickey-credentials-create","publickey-credentials-create")}} policy is set by [`allow=` on an iframe](/en-US/doc
> I linked to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes because that actually explains how to use permission policy and iframes, while https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow says what it is for and then links to the top level Permissions-Policy doc.

Yeah, when I actually looked at the link targets I saw that too, which I suppose is why I was whining about it being in the examples section. It is good content. So I suppose minimally we should deep link there from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow.

> OR we could create a proper standalone doc for iframe allow attribute - is there a model to copy for attributes? I see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly and similar but these all appear to be globals. Thoughts?

AIUI they're not globals. For `readonly`, for example:

> The readonly attribute is supported by [text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), [search](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search), [url](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url), [tel](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel), [email](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email), [password](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password), [date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), [month](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month), [week](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week), [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time), [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local), and [number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) types and the [<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) form control elements. If present on any of these input types and elements, the [:read-only](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-only) pseudo class will match. If the attribute is not included, the [:read-write](https://developer.mozilla.org/en-US/docs/Web/CSS/:read-write) pseudo class will match.

What do you think about:
- in this PR, adding the deep-link from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#allow to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#iframes
- filing an issue for a standalone `allow` page
?

2024-02-09 06:11 UTC, hamishwillee commented on files/en-us/web/api/credentialscontainer/create/index.md
> +    - The function is called cross-origin when the {{HTTPHeader("Permissions-Policy/publickey-credentials-create","publickey-credentials-create")}} policy is set by [`allow=` on an iframe](/en-US/doc
Good plan:
- Added link in https://github.com/mdn/content/pull/32135/commits/fad947eb252a7b02bf5ffe20046b52fda719d3a3
- I created the issue here https://github.com/mdn/content/issues/32188 - I don't expect I will necessarily do the work.

2024-02-09 08:07 UTC, dasJ commented on files/en-us/web/api/web_authentication_api/index.md
> +   If using `set()`:
Stray `set` ;)

2024-02-09 09:43 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +   If using `set()`:
There is no "crying emoji", or I'd be using it.
```suggestion
   If using `create()`:
```

2024-02-09 19:01 UTC, wbamberg commented on files/en-us/web/api/web_authentication_api/index.md
> +2. The `<iframe>` must also have {{glossary("Transient activation")}} when the methods are called.
Is this only for `create()`?

2024-02-11 20:48 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +2. The `<iframe>` must also have {{glossary("Transient activation")}} when the methods are called.
Yes.

2024-02-11 22:49 UTC, wbamberg commented on files/en-us/web/api/web_authentication_api/index.md
> +2. The `<iframe>` must also have {{glossary("Transient activation")}} when the methods are called.
Then this is misleading, because the list goes like:

> If you wish to authenticate with `get()` or `create()` in an `<iframe>`, there are a couple of steps to follow:
>
> 1. The site embedding the relying party site must provide permission via an `allow` attribute:
> 
>    If using `get()`: ...
>
>    If using `create()`: ...
> 
> 2. The `<iframe>` must also have {{glossary("Transient activation")}} when the methods are called.

...which suggests that (2) applies to both get and create.

2024-02-11 23:17 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +2. The `<iframe>` must also have {{glossary("Transient activation")}} when the methods are called.
Yes it does. Thanks. Fixed.

2024-02-12 23:42 UTC, hamishwillee commented
@wbamberg Anything else needed here (when you have a moment)

2024-02-13 23:28 UTC, wbamberg requested changes, later dismissed
Just a couple of nits.

2024-02-13 23:28 UTC, wbamberg commented on files/en-us/web/api/web_authentication_api/index.md
> +`get()` and `create()` can be used in nested browsing contexts loaded from the different origins to the top-most document (i.e. in cross-origin `<iframes>`), if allowed by the `Permission-Policy`s [`
```suggestion
`get()` and `create()` can be used in nested browsing contexts loaded from the different origins to the top-most document (i.e. in cross-origin `<iframes>`), if allowed by the [`publickey-credentials-get`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-get) and [`publickey-credentials-create`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-create) `Permission-Policy` directives, respectively.
```

2024-02-13 23:28 UTC, wbamberg commented on files/en-us/web/api/web_authentication_api/index.md
> +> **Note:** Where a policy forbids use of these methods, the {{jsxref("Promise", "promises")}} returned by them will reject with a `NotAllowedError` {{domxref("DOMException")}}.
```suggestion
> **Note:** Where a policy forbids use of these methods, the {{jsxref("Promise", "promises", "", "nocode")}} returned by them will reject with a `NotAllowedError` {{domxref("DOMException")}}.
```

2024-02-15 22:07 UTC, hamishwillee commented on files/en-us/web/api/web_authentication_api/index.md
> +`get()` and `create()` can be used in nested browsing contexts loaded from the different origins to the top-most document (i.e. in cross-origin `<iframes>`), if allowed by the `Permission-Policy`s [`
Yes, much better thanks.

2024-02-15 22:14 UTC, wbamberg approved these changes
👍 thank you Hamish!

2024-02-15 22:14 UTC, merged

2024-02-15 22:23 UTC, hamishwillee commented
No, thanks for your patience and help.