Add content covering modern approach to vertical form controls
mdn/content pull request #32142
Opened 2024-02-06 16:18 UTC by chrisdavidmills

### Description

Chrome has added support for vertical form controls; see https://developer.chrome.com/blog/vertical-form-controls for some more details. Specifically: 

- Vertical Selects/buttons released in 119
- Vertical textareas/text-based inputs in 121
- Vertical progress/meter/input type range in 123?

This is done by setting `writing-mode` to `vertical-lr` or `vertical-rl`. In some cases, the `direction` property can also be used to configure the form rendering in more complex ways than just obvious text alignment (e.g. rendering range sliders top to bottom or bottom to top).

This PR adds a separate article to explain how this is all done in one place and updates several other articles to link from it in appropriate places. 

### Motivation

### Additional details

### Related issues and pull requests

See https://github.com/mdn/browser-compat-data/pull/22179 for the related compat data, which has turned out to be quite complicated.

2024-02-09 18:31 UTC, dizhang168 reviewed
Thanks for putting it all together!

2024-02-09 18:31 UTC, dizhang168 commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-rl` will create from controls with a right-to-left block flow direction, meaning that in controls with wrapping or multiple lines of text, subsequent lines will appear to th
Although not implemented in Chrome (and Safari) yet, it might be good to mention `writing-mode: sideways-lr` and `writing-mode: sideways-rl`.

2024-02-09 18:31 UTC, dizhang168 commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +> **Note:** The non-standard `appearance: slider-vertical` property is included to provide some measure of support for vertical controls to older versions of Safari and Chrome. Be aware that their ef
"Be aware that their effect is limited — it only causes `range` sliders to display vertically, and not `<meter>` and `<progress>` elements."
change to:
"Be aware that their effect is limited — it only causes `range` sliders to display vertically and value from bottom to top. It does not have any effect on `<meter>` and `<progress>` elements."

2024-02-09 18:31 UTC, dizhang168 commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +In text-based controls the difference is obvious — the flow of text starts at the top or bottom. In non-text-based controls such as range sliders, `direction` controls what direction the control is d
It might be good to add an explanation of "inline base direction" [1]. Since we follow the inline direction in which content is flowing from top to bottom, the left is mapped to the top and the right is mapped to left. 

[1] https://drafts.csswg.org/css-writing-modes/#inline-base-direction

2024-02-09 18:31 UTC, dizhang168 commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +Last but not least, we'll look at handle vertical {{htmlelement("textareas")}} and textual `<input>` types. Note that, while we have only shown an `<input type="text">` element in the examples below,
Should be `{{htmlelement("textarea")}}`

2024-02-09 18:48 UTC, dizhang168 commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +> **Note:** The non-standard `appearance: slider-vertical` property is included to provide some measure of support for vertical controls to older versions of Safari and Chrome. Be aware that their ef
Also maybe mention non-standard `orient` orient attribute for Firefox.

2024-02-11 16:19 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range wherein the knob slides up and down, you can set the {{cssxref("writing-mode")}} property to a value of `vertical-rl` or `vertical-lr`, as explained in [Creating vertical f
In my next commit, I've mentioned that it is non-standard, but I've kept the description that it says it is for older versions, because I think it is still accurate — yes, it is still supported, but the new `writing-mode` stuff isn't, therefore it is the way you'd do it for older versions. I think this makes sense. People who want to know the exact details of what is supported where can look at the compat data tables.

2024-02-11 16:20 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +The guide explains how to use the CSS {{cssxref("writing-mode")}} and {{cssxref("direction")}} properties to create and configure vertical form controls, including [`<input type="range">`](/en-US/doc
Ah yes, good call. I forgot to mention those in the intro! I've added them in my next commit.

2024-02-11 16:43 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-rl` will create from controls with a right-to-left block flow direction, meaning that in controls with wrapping or multiple lines of text, subsequent lines will appear to th
Sure thing, I can do that; just to check (as it is not completely clear from the spec), do the sideways values cause the text to be laid out vertically but with the characters drawn horizontally like you'd expect in latin languages? For example:

```
L
I
k
e

t
h
I
s
```

?

2024-02-11 16:52 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +> **Note:** The non-standard `appearance: slider-vertical` property is included to provide some measure of support for vertical controls to older versions of Safari and Chrome. Be aware that their ef
done, and done!

2024-02-11 16:55 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +In text-based controls the difference is obvious — the flow of text starts at the top or bottom. In non-text-based controls such as range sliders, `direction` controls what direction the control is d
Added. I pretty much used the spec definition verbatim, as it is pretty clear.

2024-02-11 16:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +Last but not least, we'll look at handle vertical {{htmlelement("textareas")}} and textual `<input>` types. Note that, while we have only shown an `<input type="text">` element in the examples below,
Ah, good spot, thanks! Fixed now.

2024-02-11 16:59 UTC, chrisdavidmills commented
Thanks a lot for the super helpful review, @dizhang168! I have answered all your comments. There is one outstanding question, and I'll make the change that's needed for that onceyou've provided an answer.

2024-02-13 12:36 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-rl` will create from controls with a right-to-left block flow direction, meaning that in controls with wrapping or multiple lines of text, subsequent lines will appear to th
Ah great, thank you for the explanation. I've added a note and updated the text description a bit to fit around it. Can you have another look at the https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#general_technique section and let me know if it sounds accurate.

2024-02-13 12:36 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-rl` will create from controls with a right-to-left block flow direction, meaning that in controls with wrapping or multiple lines of text, subsequent lines will appear to th
@dizhang168 ^

2024-02-13 19:00 UTC, dizhang168 reviewed
LGTM, all the behavior explanations I expect are there!

2024-02-14 14:08 UTC, chrisdavidmills commented
> LGTM, all the behavior explanations I expect are there!

@dizhang168 Lovely, thank you for the super helpful tech review! I'll now turn this over to the other editors for an editorial review.

2024-02-21 03:22 UTC, wbamberg commented
Hey Chris, I can take a look at this.

2024-02-21 09:54 UTC, chrisdavidmills commented
> Hey Chris, I can take a look at this.

Yay, thanks @wbamberg!

2024-02-23 18:54 UTC, wbamberg commented
I had some questions about the first two examples, the ones about range, meters, and progress bars.

## Chrome

(Canary, 124, started with FormControlsVerticalWritingModeDirectionSupport)

In [basic example](https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#basic_example) I expect vertical sliders, drawn "top to bottom" (I assume this means that the blue part is at the top and the grey part is at the bottom).

What I see is:

<img width="148" alt="Screen Shot 2024-02-23 at 10 36 54 AM" src="https://github.com/mdn/content/assets/432915/f4c7d7f6-92be-42c0-be6e-86e816bdc739">

In [Drawing the control from bottom to top](https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#drawing_the_control_from_bottom_to_top), I expect to see them going the other way, but I don't:

<img width="137" alt="Screen Shot 2024-02-23 at 10 37 59 AM" src="https://github.com/mdn/content/assets/432915/194c86e3-5e2e-4cc0-a9a1-da1db3b646db">

## Firefox

(Nightly, 125)

In [basic example](https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#basic_example) I expect vertical sliders, drawn "top to bottom".

What I see is:

<img width="135" alt="Screen Shot 2024-02-23 at 10 41 34 AM" src="https://github.com/mdn/content/assets/432915/ec831c06-f6e5-4701-9c18-8e64d3b151f7">

...that is, range has the expected direction, but the others don't.

In [Drawing the control from bottom to top](https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#drawing_the_control_from_bottom_to_top), I see:

<img width="143" alt="Screen Shot 2024-02-23 at 10 42 59 AM" src="https://github.com/mdn/content/assets/432915/f8cae1de-048d-48a2-a22d-0c01c788a29c">

...that is, `direction` does have an effect, but only for range.

Note that removing `appearance: slider-vertical;` doesn't seem to affect things either way.

## Safari

(16.6.1)

In [basic example](https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#basic_example) I expect only the range to be displayed vertically, per [the BCD](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode#browser_compatibility), drawn "top to bottom".

What I see is:

<img width="407" alt="Screen Shot 2024-02-23 at 10 50 07 AM" src="https://github.com/mdn/content/assets/432915/1621cb7b-f21e-4d24-9af6-b53f59ebb2c2">

But if I remove `appearance: slider-vertical;`, then I see:

<img width="387" alt="Screen Shot 2024-02-23 at 10 51 10 AM" src="https://github.com/mdn/content/assets/432915/22e43d7d-d212-4733-97f6-c5beb3387900">

...so it looks like `writing-mode` isn't having any effect in Safari.

2024-02-26 11:56 UTC, chrisdavidmills commented
@wbamberg so, for Safari, for [writing-mode](https://github.com/mdn/browser-compat-data/pull/22179/files#diff-66a99d765e9b9a542716b198a2a9edb6bbd4d01e564873177bc4b137606e5a32), I say "Support for range sliders, textual inputs, and textareas only". I think this is correct, but I also think I'm missing that this is available in Safari beta only, not full release version. @dizhang168 are you able to confirm that?

For Firefox, I've got the effect of [direction](https://github.com/mdn/browser-compat-data/pull/22179/files#diff-42a12004be7befdff1ccbf268cdaa710a1d27c8fe99ed4179d5e27fcf182a587) listed as false, which I'm pretty sure it was when I first wrote this. Another thing I need to update.

For Chrome, I've documented it how I was told the state would be in Chrome 124, but it isn't there yet. @dizhang168, have you got any updates on when this behavior is going to be in the final Chrome release version?

Thanks.

2024-02-27 09:09 UTC, chrisdavidmills commented
> I am working on the Intent to Ship for it (still planning for 124). To see the behavior for now, you need the latest 123 in Chrome Canary with experimental features enabled or by setting direction as on.
> 
> For safari, I saw the feature was added in this release note: https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes

Thanks for your help, @dizhang168!

So it looks like the Safari data has already bene updated, in https://github.com/chrisdavidmills/browser-compat-data/commit/52b5dd47cc02de5a3f67d6fbadf9815e3d649b00

And I've updated the Firefox information on direction in https://github.com/mdn/browser-compat-data/pull/22298

2024-02-27 16:37 UTC, wbamberg commented
> > To see the behavior for now, you need the latest 123 in Chrome Canary with experimental features enabled or by setting direction as on.

I saw the behavior shown in https://github.com/mdn/content/pull/32142#issuecomment-1961833182 with Chrome 124, started with FormControlsVerticalWritingModeDirectionSupport, as noted in the PR description. Is there something else I have to do to see the desired behavior?

> So it looks like the Safari data has already been updated, in [mdn/browser-compat-data#22295](https://github.com/mdn/browser-compat-data/pull/22295)

I haven't tested with Safari 17.4 yet, but it is odd that the has the note about _"Support for range sliders, textual inputs, and textareas only"_, when the screenshot seems to indicate that it works for other elements as well.

> And I've updated the Firefox information on direction in [mdn/browser-compat-data#22298](https://github.com/mdn/browser-compat-data/pull/22298)

Should we also indicate that the default direction is different for meter and progress elements (i.e. it is "bottom to top")?

2024-02-27 18:54 UTC, dizhang168 commented
> I saw the behavior shown in https://github.com/mdn/content/pull/32142#issuecomment-1961833182 with Chrome 124, started with FormControlsVerticalWritingModeDirectionSupport, as noted in the PR description. Is there something else I have to do to see the desired behavior?

That should be enough. If you are on Mac, the command would be something like this:
`/Applications/"Google Chrome Canary.app"/Contents/MacOS/"Google Chrome Canary" --enable-features=FormControlsVerticalWritingModeDirectionSupport`
With my canary currently at version 124.0.6323.0, I see below result:
<img width="807" alt="image" src="https://github.com/mdn/content/assets/18745440/db2976ca-0e74-48c9-a5b8-e6ac060002bd">

2024-02-27 19:09 UTC, wbamberg commented
I see it now, thank you! 🎉

2024-02-28 08:47 UTC, chrisdavidmills commented
> I haven't tested with Safari 17.4 yet, but it is odd that the has the note about "Support for range sliders, textual inputs, and textareas only", when the screenshot seems to indicate that it works for other elements as well.

@wbamberg That note is for Safari versions before 17.4 (starting at 14). I tested all the different font control types extensively in a Safari version previous to 17.4, and found that it only makes range sliders, textareas, and textual inputs (e.g. input type text, password, URL, email) vertical.

> Should we also indicate that the default direction is different for meter and progress elements (i.e. it is "bottom to top")?

Probably, but I'll wait until you've properly reviewed this PR, in case you uncover anything else that needs updating.

In testing just now, I also noticed that `direction` works to adjust the direction of vertical range sliders in Safari (previous to 17.4). I'll also need to update that.

2024-02-29 20:28 UTC, wbamberg commented
> > I haven't tested with Safari 17.4 yet, but it is odd that the has the note about "Support for range sliders, textual inputs, and textareas only", when the screenshot seems to indicate that it works for other elements as well.
> 
> @wbamberg That note is for Safari versions before 17.4 (starting at 14).

Sorry, you're right, I misread. Still, though, I think the note is wrong.

> I tested all the different font control types extensively in a Safari version previous to 17.4, and found that it only makes range sliders, textareas, and textual inputs (e.g. input type text, password, URL, email) vertical.

What I see is: the first example in that page does work in Safari, but only because of `appearance: slider-vertical;`. If I remove that line, none of the controls are vertical: https://codepen.io/willbamberg/pen/dyLyeZx.

2024-03-01 10:57 UTC, chrisdavidmills commented
> What I see is: the first example in that page does work in Safari, but only because of `appearance: slider-vertical;`. If I remove that line, none of the controls are vertical: https://codepen.io/willbamberg/pen/dyLyeZx.

When I load your demo in my release version of Safari (16.5.2), I don't add in `appearance: slider-vertical;`, but I still see the range slider showing vertically, but not the other two. Which is what I'd expect based on my previous testing.

Similarly, when I add in a `<textarea>` and an `<input type="text">` and expand the selector of your ruleset to also select those, they also become vertical. Again, as I'd expect.

So I still think my BCD note is right, but maybe I've got the version wrong? What version of Safari are you trying this in?

2024-03-01 23:41 UTC, wbamberg commented
> What version of Safari are you trying this in?

16.6.1:

<img width="1171" alt="Screen Shot 2024-03-01 at 3 38 33 PM" src="https://github.com/mdn/content/assets/432915/f32652dc-212a-422e-88b1-efc230d38aef">

2024-03-01 23:56 UTC, wbamberg requested changes

2024-03-01 23:56 UTC, wbamberg commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +#### HTML
Just a suggestion, but it reads a bit stilted having these into sentences and all the #### HTML etc headings. We do have these for reference pages but IMO they are not important for guide pages and this page would flow better without them. But just my opinion.

2024-03-01 23:56 UTC, wbamberg commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +### Adjusting text direction and line layout order
Again changing both in the same example makes it harder to see the effect of each.

2024-03-01 23:56 UTC, wbamberg commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- Other relevant elements: {{htmlelement("button")}}, {{htmlelement("meter")}}, {{htmlelement("progress")}}, and {{htmlelement("select")}}.
I think these should either all have periods or none (maybe all?).

2024-03-04 09:41 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +The guide explains how to use the CSS {{cssxref("writing-mode")}} and {{cssxref("direction")}} properties to create and configure vertical form controls, including [`<input type="range">`](/en-US/doc
Good call. I have done as you have suggested, in the next commit.

2024-03-04 09:46 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +The sections below show how to create different types of vertial form control, along with examples of each. Consult the browser compatibility information on each of the linked reference pages to find
Good spot; fixed!

2024-03-04 10:05 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +> **Note:** The non-standard `appearance: slider-vertical` property is included to provide some measure of support for vertical controls to older versions of Safari and Chrome. Be aware that their ef
I think this is an excellent idea — separation of concerns will make for much easier-to-read docs. I have separated these into their own example in the next commit, as suggested.

2024-03-04 10:49 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +### Adjusting text direction and option order
OK, example updated!

2024-03-04 10:50 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +Again, it is possible to use a {{cssxref("direction")}} property value of `rtl` to change the text direction from the default top to bottom to bottom to top. It is also worth nothing that in the abov
Yup, agreed. I've used your text in the next commit.

2024-03-04 10:53 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +This section shows how to handle vertical {{htmlelement("button")}} elements. Note that, while we have only used an actual `<button>` element in the examples below, the behavior is the same for other
Updated, ta.

2024-03-04 11:05 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +#### HTML
Agree, 100%. I only included them because I thought they were mandatory for guide pages as well as ref pages. REMOVED!

2024-03-04 11:40 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +### Adjusting text direction and line layout order
Updated, as with the other example! I also did the same to the second button example, so have a look at that, too.

2024-03-04 11:41 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- Other relevant elements: {{htmlelement("button")}}, {{htmlelement("meter")}}, {{htmlelement("progress")}}, and {{htmlelement("select")}}.
Good call. I've updated them so that all have periods.

2024-03-06 00:29 UTC, wbamberg approved these changes
Thanks Chris! I had one suggestion but approving this anyway as it looks great.

2024-03-06 00:29 UTC, wbamberg commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- [`<textarea>`](/en-US/docs/Web/HTML/Element/textarea)s, and text-based inputs such as [`<input type="text">`](/en-US/docs/Web/HTML/Element/input/text), [`<input type="datetime-local">`](/en-US/docs
```suggestion
- [`<input type="range">`](/en-US/docs/Web/HTML/Element/input/range) sliders, {{htmlelement("progress")}} bars, and {{htmlelement("meter")}} elements.
- {{htmlelement("select")}} elements.
- {{htmlelement("button")}} elements and button input types such as [`<input type="button">`](/en-US/docs/Web/HTML/Element/input/button), [`<input type="reset">`](/en-US/docs/Web/HTML/Element/input/reset), and [`<input type="submit">`](/en-US/docs/Web/HTML/Element/input/submit).
- {{htmlelement("textarea")}} elements and text-based input types such as [`<input type="text">`](/en-US/docs/Web/HTML/Element/input/text), [`<input type="datetime-local">`](/en-US/docs/Web/HTML/Element/input/datetime-local), and [`<input type="url">`](/en-US/docs/Web/HTML/Element/input/url).
```

(just a suggestion to make this more consistent)

2024-03-06 09:49 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- [`<textarea>`](/en-US/docs/Web/HTML/Element/textarea)s, and text-based inputs such as [`<input type="text">`](/en-US/docs/Web/HTML/Element/input/text), [`<input type="datetime-local">`](/en-US/docs
WFM, cheers @wbamberg!

2024-03-06 10:13 UTC, chrisdavidmills commented
OK, so I think we are pretty much done here.

Thanks so much for a great editorial review, @wbamberg. Before I leave this, I'll review all the compat comments and make any changes needed to the BCD.

And thanks for the technical review @dizhang168. I wanted to check in with you to see how the Chrome implementation is going. Looking at the examples in the new tutorial in the latest Canary, it looks like everything is working as it should, expect that the `direction` property doesn't seem to have any effect on range/meter/progress. When I look at the examples under https://pr32142.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#range_sliders_meters_and_progress_bars, the default seems to be bottom to top rendering (it should be top to bottom, right?), and `direction` seems to have no effect. 

Is that your current understanding, and if so, is this still on track to be implemented in Chrome 124?

2024-03-06 18:34 UTC, dizhang168 commented
Hi, that is correct. We are on track to ship it fully in stable in M124 (April 16, 2024 [1]). The Intent to Ship was approved last week. Would definitely appreciate if we can hold off until then, thanks!

[1] https://chromiumdash.appspot.com/schedule

2024-03-07 11:39 UTC, chrisdavidmills commented
> Hi, that is correct. We are on track to ship it fully in stable in M124 (April 16, 2024 [1]). The Intent to Ship was approved last week. Would definitely appreciate if we can hold off until then, thanks!
> 
> [1] https://chromiumdash.appspot.com/schedule

@dizhang168 Thanks for the info. I'm happy to hold off on publishing until the Chrome release. One question — I understand that it won't be in stable before then. But when that version hits beta, will this feature be enabled by default in beta? Or will it be behind a flag until it is in the release version? If the former, then I think we could publish it earlier than that.

2024-04-02 12:16 UTC, chrisdavidmills commented
Hi there @dizhang168! Any updates on when this might be enabled in Chrome? I just checked on the latest (125) Nightly, and the behavior still doesn't seem as expected.

2024-04-03 18:55 UTC, dizhang168 commented
Hi @chrisdavidmills! The feature is shipping soon, we are currently at 50% on stable and should reach 100% within the next two weeks. I think it is safe to publish these changes.

2024-04-03 20:40 UTC, estelle requested changes
Please include labels on all form controls.

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  <input type="range" min="0" max="11" value="9" step="1" />
While the `<form>` is optional in MDN examples, all form controls do need a label to always demonstrate best practices.

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  <input type="range" min="0" max="11" value="9" step="1" />
here too

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- The non-standard `appearance: slider-vertical` property can be used in older versions of Safari and Chrome.
link `appearance` property

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  <input type="range" min="0" max="11" value="9" step="1" orient="vertical" />
label

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +<form>
here too

2024-04-03 20:40 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  <div>
again

2024-04-03 23:15 UTC, estelle requested changes
Only include a link to the guide on pages where people are likely to rotate the form control. Limit to `<input type=range>, <progress>`, and `<meter>`.

The range page should include an example of a vertical bar. The progress and meter don't need to.

2024-04-03 23:15 UTC, estelle commented on files/en-us/web/html/element/input/button/index.md
> +- [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls)
Very rarely do people have to create vertical form controls out of input elements other than possibly range. Please remove from all the input pages other than range, and remove from select and textarea, but keep on meter and progress. Also, do add to https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling and https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms,

2024-04-03 23:15 UTC, estelle commented on files/en-us/web/html/element/input/range/index.md
> -## Non-standard Attributes
do not delete this section

2024-04-03 23:15 UTC, estelle commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range wherein the knob slides up and down, you can set the {{cssxref("writing-mode")}} property to a value of `vertical-rl` or `vertical-lr`, as explained in [Creating vertical f
```suggestion
To create a vertical range wherein the thumb slides up and down, set the {{cssxref("writing-mode")}} property with a value of either `vertical-rl` or `vertical-lr`. 

To provide a fallback for non-supporting browsers, set the CSS {{cssxref('appearance')}} property to the non-standard `slider-vertical` value for older versions of Chrome and Safari, and include the non-standard `orient="vertical"` attribute to support older versions of Firefox. To learn more, see [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls).
```
Then include examples to show top to bottom and bottom to top with `vertical-rl` or `vertical-lr` and the fallback example.

2024-04-04 07:33 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  <input type="range" min="0" max="11" value="9" step="1" />
I'm not including labels on all these examples, as they are not relevant to what we are demonstrating. I have however included a note to remind people of that best practice.

2024-04-04 07:35 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- The non-standard `appearance: slider-vertical` property can be used in older versions of Safari and Chrome.
done

2024-04-04 07:37 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +
I'm not spending lots more time on this article. It was already reviewed and approved once. There are many examples further down the page.

2024-04-04 07:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +In modern browsers, the {{cssxref("writing-mode")}} property can be set to a vertical value to cause relevant form controls to display vertically with normally horizontal text characters (for example
Added

2024-04-04 07:46 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +This is useful when creating vertical language forms. Specifically:
Note added about why not rotation. I don't think we need to add examples of vertical language forms.

2024-04-04 07:47 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +> **Note:** The experimental `sideways-lr` and `sideways-rl` values have much the same effect as `vertical-lr` and `vertical-rl` respectively, except that normally vertical text characters (for examp
Suggestion used

2024-04-04 07:49 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +In addition, the {{cssxref("direction")}} property can be used to control the direction of the content inside the controls:
But this is contextual; this is what we are already talking about. We don't need to spell it out exhaustively.

2024-04-04 07:50 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +This is referred to as the **inline base direction** — the primary direction in which content is ordered on a line, which defines on which sides the "start" and "end" of a line are. In text-based con
updated

2024-04-04 07:52 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +    at 50/100
done

2024-04-04 07:53 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- The non-standard `orient="vertical"` attribute can be added to the `<input type="range">` element itself in older versions of Firefox.
No change. Again, this is contextually obvious, we don't need it.

2024-04-04 07:54 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  appearance: slider-vertical;
updated

2024-04-04 07:55 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +It is also worth nothing that in the above example we've got the select options appearing from right to left, because we used `writing-mode: vertical-rl`. If we use `writing-mode: vertical-lr` instea
Updated

2024-04-04 07:56 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-lr` on the third one, to flow the text top to bottom but reverse the option order to go left to right.
Text updated. I'm not adding more to the example.

2024-04-04 07:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  writing-mode: vertical-rl;
removed

2024-04-04 07:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +  </div>
Not needed

2024-04-04 08:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +Last but not least, we'll look at handle vertical {{htmlelement("textarea")}}s and textual `<input>` types. Note that, while we have only shown an `<input type="text">` element in the examples below,
updated

2024-04-04 08:02 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +Let's look at a basic vertical text input example.
I've just deleted the line; not needed

2024-04-04 08:03 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +To display the buttons vertically, we can use CSS like this:
updated

2024-04-04 08:04 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +{{ EmbedLiveSample("Basic text input example", "100%", "130") }}
updated

2024-04-04 08:09 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-rl` on the first one, so that it displays just like in the the previous example — text flowing top to bottom, and lines flowing right to left.
updated

2024-04-04 08:10 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- `writing-mode: vertical-lr` on the third one, to flow the text top to bottom but reverse the flow of lines — left to right. Note that this has no effect on the `<input type="text">` element, as it
updated

2024-04-04 08:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +- CSS properties: {{cssxref("direction")}} and {{cssxref("writing-mode")}}.
I've removed this line and added in a couple of these links

2024-04-04 08:16 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/index.md
> +- [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls)
No; I think it is useful to expose here as well.

2024-04-04 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range wherein the knob slides up and down, you can set the {{cssxref("writing-mode")}} property to a value of `vertical-rl` or `vertical-lr`, as explained in [Creating vertical f
I've made this change and adjusted things around a bit. I'm not adding in another example as we link to the "Creating vertical form controls" page for examples.

2024-04-04 08:22 UTC, chrisdavidmills commented on files/en-us/web/html/element/textarea/index.md
> +- [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls)
No, as explained in an earlier comment.

2024-04-04 08:26 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/range/index.md
> -## Non-standard Attributes
ok, added back.

2024-04-04 17:49 UTC, estelle commented on files/en-us/web/html/element/input/button/index.md
> +- [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls)
Let's just pick a few places to include the guide. How about [meter](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter), [progress](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress), [range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) and, optionally, the [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) main page

2024-04-04 17:50 UTC, estelle commented on files/en-us/web/html/element/input/index.md
> +- [Creating vertical form controls](/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls)
let's keep this one, but remove it from all the sub-input pages (all the type pages).

2024-04-04 17:54 UTC, estelle commented on files/en-us/web/css/css_writing_modes/vertical_controls/index.md
> +You could use a [transform](/en-US/docs/Web/CSS/transform) to rotate the controls by 90 degrees, but that would place the controls in their own layer and cause unintended layout side effects such as
perfect

2024-04-04 23:10 UTC, estelle reviewed
just added a quick example to range. After that we should be good to go.

2024-04-04 23:10 UTC, estelle commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range wherein the thumb slides up and down, set the {{cssxref("writing-mode")}} property with a value of either `vertical-rl` or `vertical-lr`.
```suggestion
To create a vertical range wherein the thumb slides up and down, set the {{cssxref("writing-mode")}} property with a value of either `vertical-rl` or `vertical-lr`.

```html-hidden
<input type="range" min="0" max="10" value="8">
```end

```css
input[type="range"] {
   writing-mode: vertical-lr;
}
```end

{{EmbedLiveSample("Creating vertical range controls", 200, 200)}}

```

2024-04-04 23:10 UTC, estelle commented on files/en-us/web/html/element/input/range/index.md
> +To create a vertical range wherein the thumb slides up and down, set the {{cssxref("writing-mode")}} property with a value of either `vertical-rl` or `vertical-lr`.
this section is in "examples". Include a simple example and they can go to the link in the next sentence to learn more. Actually seeing a vertical range in the page will get people to click to the guide. :D

2024-04-05 16:11 UTC, estelle approved these changes

2024-04-05 16:12 UTC, merged