chore(macros): Remove 'Xref_cssinitial', 'Xref_cssinherited', 'Xref_csscomputed'
mdn/content pull request #32189
Opened 2024-02-09 12:50 UTC by bsmth

### Description

This PR removes the only occurrences of the following macros in content:

- `{{Xref_cssinitial}}`
- `{{Xref_cssinherited}}`
- `{{Xref_csscomputed}}`

There are no other uses of these macros and they can be replaced with regular Markdown links.

### Motivation

Removing unnecessary macros

2024-02-10 00:21 UTC, dipikabh requested changes
Thanks, @bsmth! I've added a comment.

2024-02-10 00:21 UTC, dipikabh commented on files/en-us/web/css/-webkit-mask-box-image/index.md
> +- [Computed value](/en-US/docs/Web/CSS/computed_value): as specified
Maybe we can replace these lines with the `{{CSSInfo}}` macro?
Some of the other `-webkit-mask-*` properties are using `{{CSSInfo}}`, so might work here.

2024-02-12 17:10 UTC, bsmth commented on files/en-us/web/css/-webkit-mask-box-image/index.md
> +- [Computed value](/en-US/docs/Web/CSS/computed_value): as specified
I get `Value not found in DB!`. And it looks like it's missing from mdn/data:

https://github.com/mdn/data/blob/af8a84ad4bdc9ea92fe74790eed43712c5668f6b/css/properties.json#L1362-L1378

Is it worth adding it, do you reckon?

2024-02-13 15:26 UTC, dipikabh commented on files/en-us/web/css/-webkit-mask-box-image/index.md
> +- [Computed value](/en-US/docs/Web/CSS/computed_value): as specified
Yeah, not worth it updating `mdn/data` for this non-standard property.

Plus, I found this odd: https://github.com/mdn/data/blob/af8a84ad4bdc9ea92fe74790eed43712c5668f6b/css/properties.json#L1341-L1348. For example, it does not include `-webkit-mask-composite`. No point chasing this one.

In any case, the note on [-webkit-mask-box-image](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-box-image) page does tell readers to refer to the [mask-border](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-border) property.
This is good as is I think.

2024-02-13 15:26 UTC, dipikabh approved these changes
Thanks, @bsmth 👍

2024-02-13 15:26 UTC, merged

2024-02-13 18:29 UTC, bsmth commented
Thank you!

2024-02-14 21:31 UTC, adeibnugandiSH commented
Hello Cs