Add runtime.on performance warning
mdn/content pull request #32222
Opened 2024-02-11 16:08 UTC by rebloor

### Description

Adds API documentation and release note for the `runtime.on performance` event introduced by [Bug 1861445](https://bugzilla.mozilla.org/show_bug.cgi?id=1861445) Add new hang warning event API for WebExtensionswarning.

See (TBC) for browser compatibility data.

2024-03-04 20:06 UTC, Rob--W requested changes

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +      - : `string`. "content_script", the performance warning event category.
This should be the `OnPerformanceWarningCategory` enum. It is also exposed as the `runtime.OnPerformanceWarningCategory` object. It currently reports content_script categories only, but the API by design is extensible to other kinds of warnings.

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +    - `tabId`
`tabId` is optional.

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +  console.log(`Performance warning: ${performanceWarningInfo.description}`);
```suggestion
function handlePerformanceWarning(details) {
  console.log(`Performance warning: ${details.description}`);
```

A bit shorter.

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +  - : The function called when this event occurs. The function is passed these arguments:
It is not passed these args but an object with the following properties.

See this example: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onBeforeNavigate

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +> **Note:** This API is based on Chromium's [`chrome.runtime`](https://developer.chrome.com/docs/extensions/reference/runtime/#event-onPerformanceWarning) API. This documentation is derived from [`ru
Please drop this boiletplate. This API doesn't even exist in Chromium.

2024-03-04 20:06 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/124/index.md
> +- Adds the {{WebExtAPIRef("runtime.onPerformanceWarning")}} event that enables extensions to obtain information when the browser detects that the extension has a runtime performance issue ([Firefox b
```suggestion
- Adds the {{WebExtAPIRef("runtime.onPerformanceWarning")}} event that enables extensions to obtain information when the browser detects that the extension has a runtime performance issue such as a slow-running content script ([Firefox bug 1861445](https://bugzil.la/1861445)).
```

2024-03-05 03:10 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
@Rob--W Is this also an object?, e.g. `OnPerformanceWarningSeverity`

2024-03-07 13:27 UTC, kzar commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
@rebloor If it helps, here are the entries from /toolkit/components/extensions/schemas/runtime.json:

```jason
{
  "id": "OnPerformanceWarningCategory",
  "type": "string",
  "enum": ["content_script"],
  "description": "The performance warning event category, e.g. 'content_script'."
},
{
  "id": "OnPerformanceWarningSeverity",
  "type": "string",
  "enum": ["low", "medium", "high"],
  "description": "The performance warning event severity. Will be 'high' for serious and user-visible issues."
}
```

2024-03-08 01:39 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
@kzar exactly, hence the question.

2024-03-08 12:02 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
Let's inline the potential values for now; I'll clarify with other engineers whether we really want to expose the supported values on an object. If so, then we can update the documentation to add extra articles with the enum values.

2024-03-08 12:11 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
I requested clarification at https://github.com/w3c/webextensions/issues/456#issuecomment-1985585040. Let's wait a week or so to allow for an answer before merging this PR.

I think that the most likely outcome is that we would retain these objects. Let's shape this patch towards that assumption since it is the least amount of work for you.

2024-03-11 01:45 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
@Rob--W I see that @kzar responded to [w3c/webextensions#456 (comment)](https://github.com/w3c/webextensions/issues/456#issuecomment-1985585040) - do I read that correctly that we are agreeing to document `OnPerformanceWarningCategory` and `OnPerformanceWarningSeverity` as types?

2024-03-12 18:40 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarning/index.md
> +        - `severity`
Yes.

2024-03-13 18:08 UTC, kzar commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarningcategory/index.md
> +- `"content_script"`: The performance warning originated from a content script.
```suggestion
- `"content_script"`: The performance warning relates to a slow content script.
```

2024-03-13 20:46 UTC, Rob--W approved these changes
Approved with kzar's suggestion applied.

2024-03-14 02:56 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/onperformancewarningcategory/index.md
> +- `"content_script"`: The performance warning originated from a content script.
Revised following feedback from @Rob--W 
```suggestion
- `"content_script"`: The performance warning is for a slow content script in this extension.
```

2024-03-14 03:01 UTC, merged