Clearer `log()` example
mdn/content pull request #32226
Opened 2024-02-11 17:32 UTC by nikk-ca

### Description

Rewrote the example of the CSS `log()` function.

### Motivation

This example shows a practical application of the function.

### Additional details

### Related issues and pull requests

2024-02-13 17:48 UTC, dipikabh requested changes
Thanks @nikk-ca! Showing a practical usage is indeed cool.
Would appreciate it if you could address my comments. Thanks!

2024-02-13 17:48 UTC, dipikabh commented on files/en-us/web/css/log/index.md
>  ### Sizes based on `log()` function
the heading will need to be redone to be more specific to the example
```suggestion
### Using the `log()` function on a logarithmic scale
```

2024-02-13 17:48 UTC, dipikabh commented on files/en-us/web/css/log/index.md
> +In this example, the width of each bar is relative to it's value on a [log<sub>10</sub> scale](https://en.wikipedia.org/wiki/Logarithmic_scale).
Explain how `log()` is being used

```suggestion
This example illustrates how the `log()` function can be used to visualize data values by using a [logarithmic scale](https://en.wikipedia.org/wiki/Logarithmic_scale). The width of each bar in this example is relative to its data value on a logarithmic scale with base 10.
```

2024-02-13 17:48 UTC, dipikabh commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
To not recommend inline styling, can we move the variables to the CSS code?

2024-02-14 16:38 UTC, nikk-ca commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
I'd normally agree, but in this case I put the value inline because it's specific to the individual element, rather than reusable.

That said, if inline styles aren't supposed to be used anywhere, I can totally change it 👍

```css
.value-50 {
  --value: 50;
}
.value-100 {
  --value: 100;
}
.value-500 {
  --value: 500;
}
.value-10000 {
  --value: 10000;
}
.value-2000000 {
  --value: 2000000;
}
```

2024-02-14 16:38 UTC, nikk-ca commented on files/en-us/web/css/log/index.md
> +In this example, the width of each bar is relative to it's value on a [log<sub>10</sub> scale](https://en.wikipedia.org/wiki/Logarithmic_scale).
Much better, thanks

2024-02-20 14:18 UTC, dipikabh commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
@nikk-ca we do have instances of inline styling in our docs, so let's go with your original proposal. We'd need to add a line about CSS custom properties though, as was in the original example.

2024-02-20 18:52 UTC, dipikabh commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
@nikk-ca In the "Result" section, the argument passed to the `EmbedLiveSample` macro needs to be updated to reflect the new heading.
`{{EmbedLiveSample('Sizes based on log() function', '100%', '220px')}}`

2024-02-20 21:41 UTC, nikk-ca commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
@dipikabh Done ✅

2024-02-21 16:11 UTC, dipikabh commented on files/en-us/web/css/log/index.md
> +<div class="bar" style="--value: 2000000">2,000,000</div>
Perfect, thank you!

2024-02-21 16:13 UTC, dipikabh approved these changes
Thanks for your contribution @nikk-ca for adding a practical example!

2024-02-21 16:13 UTC, merged

2024-02-21 16:14 UTC, dipikabh commented
Congratulations on landing your first PR here!
Welcome to the MDN project 🎉