Updated Date.parse()
mdn/content pull request #32253
Opened 2024-02-13 13:59 UTC by dletorey

### Description

- Added a note about Daylight Saving and how it can affect parsed Dates with no time zone set
- Updated the Non-Standard date strings

### Motivation

Working on the updates for [`Date.parse()` in Firefox 123](https://github.com/mdn/content/issues/319140

### Additional details

- [https://bugzilla.mozilla.org/show_bug.cgi?id=1870434](https://bugzilla.mozilla.org/show_bug.cgi?id=1870434)
- [https://bugzilla.mozilla.org/show_bug.cgi?id=1870570](https://bugzilla.mozilla.org/show_bug.cgi?id=1870570)
- [https://bugzilla.mozilla.org/show_bug.cgi?id=1872333](https://bugzilla.mozilla.org/show_bug.cgi?id=1872333)

### Related issues and pull requests

- No BCD needed
- Firefox Release PR - coming soon

2024-02-13 20:14 UTC, Josh-Cena requested changes

2024-02-13 20:14 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/parse/index.md
> +> **Note:** The local time zone comes from the system setting of the device, for example _London/Europe_ GMT. Daylight saving affects this, which is set by the local Government to that time zone, thi
This paragraph is hard to parse for me. It is easier to just point out that the timezone offset (relative to UTC) is calculated based on the timezone at the location of the device, and at the time denoted by the time itself, not at the time the code is run. You can then link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset, which does a much better exposition. (The London example is very interesting—maybe add it to that page?) However, none of this has anything special to do with `Date.parse`, so it's certainly out of context here, unless you add it to every method that deals with local timezones.

2024-02-13 20:14 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/parse/index.md
> +// Nan in Firefox ≤122
```suggestion
// NaN in Firefox ≤122
```

2024-02-13 21:12 UTC, dletorey commented on files/en-us/web/javascript/reference/global_objects/date/parse/index.md
> +> **Note:** The local time zone comes from the system setting of the device, for example _London/Europe_ GMT. Daylight saving affects this, which is set by the local Government to that time zone, thi
Cool, I shall get back on that next week (going on holiday in 10 mins).

BTW it is not just a London this it is most countries especially in Europe and at different times I can across this as i called `Date.parse("1 Jan 1970")` and it returned `-360000` doing further research I found it was everywhere.

2024-02-20 13:33 UTC, pepelsbey approved these changes
LGTM, thank you!

2024-02-20 13:38 UTC, merged