New guide: container style queries
mdn/content pull request #32254
Opened 2024-02-13 13:59 UTC by estelle

A new guide: under the containment module.

Links to this new guide will be added in a separate PR.

feedback: https://github.com/mdn/content/pull/32088

2024-02-14 18:58 UTC, chrisdavidmills requested changes
Hi @estelle! I've had a really good read through the new guide and left quite a few comments. I will admit I had difficulties understanding quite a bit of the stuff around style queries, particularly the custom property queries. I really do applaud you for trying to explain this stuff, as it doesn't seem easy.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +- All elements can be style query containers; setting a `container-type` is not required. When descendant styles don't impact the computed styles of an ancestor, containment is not needed.
ah, so this is true. I'm thinking maybe just remove the stuff about size queries needing containment from above, and deal with it here, to simplify the earlier paragraph.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +- A `<container-condition>` can include both style and size features. If including size features, include the `container-type` property.
Do you have an example included later on to show what it looks like when both are included?

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Style queries for custom properties allow you to query the custom properties, also called "CSS variables", of a parent element. [Custom properties are CSS properties](/en-US/docs/Web/CSS/Using_CSS_cu
```suggestion
Style queries for custom properties allow you to query the [custom properties](/en-US/docs/Web/CSS/Using_CSS_custom_properties), also called "CSS variables", of a parent element. They are included within a `<style-query>` just as you would include any regular CSS property within a feature query: either with or without a value.
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +#### Stand alone custom property queries
```suggestion
#### Standalone custom property queries
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
```suggestion
The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the value is the same as the value of the `initial-value` descriptor within the `@property` at-rule, if there is one. The style query will return true and match all elements that have a custom property value that differs from the `initial-value` or for all elements that have a custom property of any value if the custom property was declared without being registered.
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
To be honest, I'm really struggling to understand the last sentence in this paragraph. Can you try rephrasing it/breaking it up a bit?

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
Also, you talk about an example that uses `@property` above, but then you show an example that doesn't include `@property`.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
Also, this bit sounds contradictory — "When no value is included, the query will return false if the value..." I thought there was no value?

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this example, the `:root` element would not NOT match the style query as the custom property value for that element (and all the elements inheriting the value) is the same as the `initial-value`.
I've read this bit a few times now, and I don't understand why this is the case.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +@container style(--accent-color: blue) {
show an example element that matches it?

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this case, if the value of `--accent-color` were set to `blue`, `#00f`, `#0000ff`, `rgb(0 0 255 / 1)`, or `rgb(0% 0% 100%)` it would return true for `@container style(--accent-color: blue)`.
Explain a bit more about why having the `syntax` descriptor set to `<color>` makes this so.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +JavaScript updates the value of the CSS `--theme` variable on the {{htmlelement("body")}} element, which is an ancestor of the {{htmlelement("fieldset")}} and {{htmlelement("output")}} elements, when
```suggestion
JavaScript updates the value of the CSS `--theme` variable on the {{htmlelement("body")}} element, which is an ancestor of the {{htmlelement("fieldset")}} and {{htmlelement("output")}} elements, whenever a radio button is selected. When the text `<input>` is updated, the {{domxref("HTMLInputElement.value", "value")}} of the `other` radio button is updated only if the `other` radio button is {{domxref("HTMLInputElement.checked", "checked")}}, which in turn updates the value of `--theme`.
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +JavaScript updates the value of the CSS `--theme` variable on the {{htmlelement("body")}} element, which is an ancestor of the {{htmlelement("fieldset")}} and {{htmlelement("output")}} elements, when
I'm not really sure if this example is working as you intended it to. I've tried it in Chrome...

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +We use the `@property` at-rule to define a CSS variable `--theme` to be a {{cssxref("color_value", "&lt;color>")}} value and set the `initial-value` to `#00F`, ensuring equivalent colors are a match
```suggestion
We use the `@property` at-rule to define a CSS variable `--theme` to be a {{cssxref("color_value", "&lt;color>")}} value and set the `initial-value` to `#00F`, ensuring equivalent colors are a match whether declared using {{cssxref("rgb")}}, {{cssxref("hex-color")}}, {{cssxref("named-color")}}, or other syntax (for example, `#F00` is equal to `rgb(255 0 0)`, `#ff0000`, and `red`).
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The second style query states that when `--theme` is equivalent `red`, the `<output>`'s contents will also be bold. We did this to better demonstrate that the container query is a match,
Missing end of sentence?

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Try changing the color value. Notice that any equivalent of `red` will make the `<output>` red, while removing the outline. Any other valid color value, including `currentcolor` or `hsl(180 100% 50%)
I think I must be tired, but I don't really get the point of this example. I'm still not clear on how this example works, or what you'd use it for. I appreciate this is quite esoteric stuff, so probably hard to figure out a solid use case for.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The matching is done against the computed value of the parent container; if the parent's computed {{cssxref("font-weight")}} is `bold` (not `bolder` or `900`), there is a match. Just as with custom p
This stuff makes total sense! Shame it's not supported yet ;-)

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Style features that query a shorthand property will be true if the computed values match for each of its longhand properties, and false otherwise. For example, `@container style({{cssxref("border")}}
```suggestion
Style features that query a shorthand property will be true if the computed values match for each of its longhand properties, and false otherwise. For example, `@container style({{cssxref("border")}}: 2px solid red)` will resolve to true if all 12 longhand properties ({{cssxref("border-bottom-style")}}, etc.) that make up that shorthand are set to the same equivalent values.
```

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Do not apply the styles you are querying in the style query to the element you are styling with that query as this may cause an infinite loop.
An example to illustrate what you mean would be good here.

2024-02-14 18:58 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The above will return true for any element that has a value for `font-weight` that differs from its initial value. User-agent stylesheets set `font-weight: bold` for {{htmlelement("heading_elements",
```suggestion
The above example will return true for any element that has a value for `font-weight` that differs from its initial value. User-agent stylesheets set `font-weight: bold` for {{htmlelement("heading_elements", "heading")}} and {{htmlelement("th")}} elements, for example. Some browsers set {{htmlelement("strong")}} and {{htmlelement("b")}} to `bold`, others to `bolder`. {{htmlelement("optgroup")}} also sometimes has a `font-weight` other than `normal` set by the user agent. As long as the element's font-weight is not the default value for that user-agent, the style query will return true.
```

2024-02-15 01:24 UTC, estelle reviewed
Got thru half. I resolved the conversations i addressed so that i can keep track of them. Will hopefully finish before you see this ;)

2024-02-15 01:24 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Container names also enable querying styles from elements that aren't a direct parent. When a containment context is given a name, it can be specifically targeted using the `@container` at-rule inste
I rearranged this section.

2024-02-15 01:24 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Set `container-name: none` to prevent the container from matching any named container queries. That removes all associated container query names, but does not prevent the element from matching unname
added the following:

```css
article {
  container-name: none;
  container-type: size;
}

main {
  container-name: neverUsedName;
  container-type: normal;
}
```

> In the above example, the {{htmlelement("article")}} element can matched any unnamed container query. In other words, it will be tested by each `@container` query that doesn't include a name in the `<container-condition>`. On the other hand, assuming the `neverUsedName` is never used as a container query name, the {{htmlelement("main")}} element will never be queried. If it is, it will still not be tested against any size queries as the `container-type` value of `normal` means it is not a size query container.

2024-02-15 07:39 UTC, estelle reviewed
I think i addressed everything, There are three "examples would be good here" where I think we are already too much in the weeds with this guide so added about 5 examples, but not 8 ;)

2024-02-15 07:39 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this case, if the value of `--accent-color` were set to `blue`, `#00f`, `#0000ff`, `rgb(0 0 255 / 1)`, or `rgb(0% 0% 100%)` it would return true for `@container style(--accent-color: blue)`.
That is beyond the scope of this guide. Unfortunately, there are issues with the rgb docs on mdn, so not linking now. but i'll be updating those pages next month or so, so can link then.

2024-02-15 07:39 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The second style query states that when `--theme` is equivalent `red`, the `<output>`'s contents will also be bold. We did this to better demonstrate that the container query is a match,
just a period ;)

2024-02-15 07:39 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Try changing the color value. Notice that any equivalent of `red` will make the `<output>` red, while removing the outline. Any other valid color value, including `currentcolor` or `hsl(180 100% 50%)
I added more text explaining how to fill in the text box and what to expect and why.

2024-02-15 07:39 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Do not apply the styles you are querying in the style query to the element you are styling with that query as this may cause an infinite loop.
that is needed on the @container page, not here.

2024-02-15 16:13 UTC, estelle commented
The example is not fully working - the last: 

```css
output {
    color: var(--theme);
  }
```
seems to not be working. I am working on that, but didn't want to hold up the rest of the rerview. Should push a fix really soon

2024-02-16 15:00 UTC, chrisdavidmills requested changes
Thanks for all the hard work on this @estelle! This makes a lot more sense now; most of these new comments are fairly minor text suggestions. I still had a few points where I found it hard going, but these are now more focused on specific areas.

This is definitely going in the right direction.

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In the above example, the {{htmlelement("article")}} element can matched any unnamed container query. In other words, it will be tested by each `@container` query that doesn't include a name in the `
```suggestion
In the above example, the {{htmlelement("article")}} element can match any unnamed container query. In other words, it will be tested by each `@container` query that doesn't include a name in the `<container-condition>`. On the other hand, assuming the `neverUsedName` is never used as a container query name, the {{htmlelement("main")}} element will never be queried. Even if that name was removed, it would still not be tested against any size queries as the `container-type` value of `normal` means it is not a size query container.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A _container style query_ is a `@container` query that evaluates computed styles of the container element as defined in one or more `style()` functional notations. The boolean syntax and logic used t
```suggestion
A _container style query_ is a `@container` query that evaluates computed styles of the container element as defined in one or more `style()` functional notations. The boolean syntax and logic used to combine style features into a style query are the same as in [CSS feature queries](/en-US/docs/Web/CSS/CSS_conditional_rules/Using_feature_queries). The only difference is the function name — `style()` within a `<style-feature>` as opposed to `supports()` within a `<support-condition>`:
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The parameter of each `style()` function is a single `<style-feature>`. Per the CSS containment specification, a **`<style-feature>`** can be a valid CSS [declaration](/en-US/docs/Web/CSS/syntax#css_
```suggestion
The parameter of each `style()` function is a single **`<style-feature>`**. Per the CSS containment specification, a `<style-feature>` can be a valid CSS [declaration](/en-US/docs/Web/CSS/syntax#css_declarations), a CSS property, or a [`<custom-property-name>`](/en-US/docs/Web/CSS/var#values). The only style feature currently supported is custom properties, with or without a value. See the [browser compatibility table](#browser_compatibility).
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +If the `<style-feature>` includes a value, the style query evaluates to true if the computed value of the custom property value (or, in the future, the CSS declaration) passed as the `style()` argume
```suggestion
If the `<style-feature>` includes a value, the style query evaluates to true if the computed value of the custom property (or, in the future, the CSS declaration) passed as the `style()` argument is true for the container being queried. Otherwise, it resolves to false.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A few things to note:
The below points all seem to be recapping stuff said previously. Maybe frame it as a recap, or a summary?

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
I'm starting to understand what is going on here now. However, I think mixing the two different cases here — the one where the custom property is just used without an explicit definition, and the one where the custom property is explicitly defined using `@property` (or `CSS.registerProperty()`) makes things more confusing than it needs to be. I would just talk about them in completely separate sections, before then comparing them and pointing out the differences at the end of the second section.

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A style feature without a value evaluates to true if the computed value is different from the initial value for the given property.
That's only true when the custom property is explicitly defined using `@property` (or `CSS.registerProperty()`), right?

Also, I'd love to see a bit more explanation about why this is true. I understand what it is saying, but I don't really get why it is the case, or why this is useful.

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +If explicitly defined with the {{cssxref("@property")}} CSS at-rule or via JavaScript with {{domxref('CSS/registerProperty_static', 'CSS.registerProperty')}}, the style query `style(--theme-color)` w
```suggestion
If explicitly defined with the {{cssxref("@property")}} CSS at-rule or via JavaScript with {{domxref('CSS/registerProperty_static', 'CSS.registerProperty()')}}, the style query `style(--theme-color)` will only be true for elements where the computed value for `--theme-color` is different from the [`initial-value`](/en-US/docs/Web/CSS/@property/initial-value) set in the original definition. This is different from the example above in which the CSS variable was introduced via a simple CSS custom property value assignment; in that case querying that custom property will always return true.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this example, the `:root` element would not NOT match the style query as the custom property value for that element (and all the elements inheriting the value) is the same as the `initial-value`.
```suggestion
In this example, the `:root` element would NOT match the style query as the custom property value for that element (and all the elements inheriting the value) is the same as the `initial-value` — both are `rebeccapurple`. Only elements that differ from the initial value, in this case the {{htmlelement("main")}} and its descendants that inherit that changed value, are a match.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +If a style query includes a value for the custom property, the element's computed value for that property must be an exact match, with equivalent values only being a match if the custom property was
```suggestion
If a style query includes a value for the custom property, the element's computed value for that property must be an exact match, with equivalent values only being a match if the custom property was defined with a {{cssxref("@property")}} at rule (or a {{domxref('CSS/registerProperty_static', 'CSS.registerProperty()')}} method call) containing a `syntax` descriptor.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +This container style query matches any element that has `blue` as the {{cssxref("computed_value")}} of for the `--accent-color` custom property.
```suggestion
This container style query matches any element that has `blue` as the {{cssxref("computed_value")}} of the `--accent-color` custom property.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this case, the equivalent hexidecimal code `#0000ff` will match only if the property was defined as a color with `@property` or `CSS.registerProperty`. To ensure the container style query matches
```suggestion
In this case, other color values equivalent to sRGB `blue` (such as the hexadecimal code `#0000ff`) will match only if the `--accent-color` property was defined as a color with `@property` or `CSS.registerProperty()`, for example:
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +  initial-value: #00f;
```suggestion
  initial-value: #0000ff;
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +We use the `@property` at-rule to define a CSS variable `--theme` to be a {{cssxref("color_value", "&lt;color>")}} value and set the `initial-value` to `#00F`, ensuring equivalent colors are a match
```suggestion
We use the `@property` at-rule to define a CSS variable `--theme` to be a {{cssxref("color_value", "&lt;color&gt;")}} value and set the `initial-value` to `#00F`, ensuring equivalent colors are a match regardless of what syntax is used (for example, `#F00` is equal to `rgb(255 0 0)`, `#ff0000`, and `red`).
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +We use the `@property` at-rule to define a CSS variable `--theme` to be a {{cssxref("color_value", "&lt;color>")}} value and set the `initial-value` to `#00F`, ensuring equivalent colors are a match
I think mentioning things like the named-color data type makes this more complicated than needed. It is already quite complicated.

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The second style query states that when `--theme` is equivalent `red`, the `<output>`'s contents will also be bold. We did this to better demonstrate that the container query is a match.
```suggestion
The second style query states that when `--theme` is equivalent to `red`, the `<output>`'s contents will also be bold. We did this to better demonstrate that the container query is a match.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +These two style queries include values for the custom property. These will match if the container's `--theme` value is an equivalent color to the value listed, even if that value is the same as the `
```suggestion
The second and third style queries include values for the custom property. These will match if the container's `--theme` value is an equivalent color to the value listed, even if that value is the same as the `initial-value`. The first query matches elements whose `--theme` value is equivalent to `red`, `blue`, or `green`. When it is, the {{cssxref("color")}} will be the color current value of `--theme`.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Enter different color values into the text box. You may notice that values that are RGB equivalents of `red` will make the `<output>` red - as it matches `style(--theme: red)`, while removing the out
```suggestion
Try entering different color values into the text box. You may notice that values that are sRGB equivalents of `red` will make the `<output>` red — as it matches `style(--theme: red)` — while removing the outline, because `style(--theme)` returns false if the element's value for `--theme` is the same as the initial value for `--theme` defined by the `@property` at-rule. Any non-red sRGB valid color value, including `currentcolor` or `hsl(180 100% 50%)`, etc., makes the first style query return true; they are values that are different from the `initial-value`.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In this case, the `<output>` will have a large dotted border if it's nested in a container where `--theme: purple` is set, and that container is nested within a container whose `--theme` value is `re
```suggestion
In this case, the `<output>` will have a 5px dotted border if it's nested in a container where `--theme: purple` is set, and that container is nested within a container whose `--theme` value is `red`.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The above example will return true for any element that has a value for `font-weight` that differs from its initial value. User-agent stylesheets set `font-weight: bold` for {{htmlelement("heading_el
```suggestion
The above example will return true for any element that has a value for `font-weight` that differs from its initial value. User-agent stylesheets set `font-weight: bold` for {{htmlelement("heading_elements", "heading")}} and {{htmlelement("th")}} elements, for example. Some browsers set {{htmlelement("strong")}} and {{htmlelement("b")}} to `bold`, others to `bolder`. {{htmlelement("optgroup")}} also sometimes has a `font-weight` other than `normal` set by the user agent. As long as the element's `font-weight` is not the default value for that user-agent, the style query will return true.
```

2024-02-16 15:00 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +{{EmbedLiveSample('example','100%','200')}}
The example makes a bit more sense now. There seem to be bugs with the "Other color" field:

- If you set the value in the text field as `red`, `blue`, or `green`, the output seems to behave as described.
- If you set it to a valid color that isn't `red`, `blue`, or `green`, the output goes gray and dotted
- If you set it to a non-valid color, e.g. `^%^**`, it goes bold and red
- If you set it to equivalent color representations of `red`, `blue`, or `green`, you get a variety of behavior — for `rgb(0 255 0)`, you get gray and dotted (not green). For `rgb(0 0 255)`, you get blue and dotted. For `rgb(255 0 0)`, you get bold and red.

Is that the behavior you expected? I tested it in the latest Chrome Canary.

2024-02-16 18:21 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +{{EmbedLiveSample('example','100%','200')}}
yes, exactly as expected.

2024-02-16 18:24 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +  initial-value: #00f;
this was intentional

2024-02-16 20:20 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +
```suggestion

#### Registered properties
```

2024-02-16 20:21 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +#### Registered properties
```suggestion
#### Registered properties

```

2024-02-16 20:21 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A style feature without a value evaluates to true if the computed value is different from the initial value for the given property.
```suggestion
A style feature without a value evaluates to true if the computed value is different from the [initial value](#registered_properties) for the given property.
```

2024-02-16 20:33 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The `<style-query>` parameter of the `style()` functional notation can include just a CSS variable name; a custom property with no value. When no value is included, the query will return false if the
i added a header for register properties.

2024-02-16 20:35 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A style feature without a value evaluates to true if the computed value is different from the initial value for the given property.
added a link to the new registered properties heading.

2024-02-16 20:35 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A few things to note:
```suggestion
A few things to note that have already been mentioned but are important to remember:
```

2024-02-16 20:38 UTC, estelle commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +Container size queries are filtered by a size condition. The associated styles are applied to contained elements if the container element has been declared to be a container and the container conditi
```suggestion
Container size queries are filtered by a size condition. The associated styles are applied to contained elements if the container element has been declared to be a container and the container condition is true for that element. An element's size container is the nearest ancestor with containment.
```

2024-02-17 00:38 UTC, estelle commented
@chrisdavidmills when ready to merge, please review https://github.com/mdn/content/pull/32318 to add links to this new page.

2024-02-19 12:19 UTC, chrisdavidmills approved these changes
@estelle I've still got a few comments for you to consider, but I'll approve this so as not to hold you up. Well done for some great work on what is a pretty difficult subject to explain.

2024-02-21 17:59 UTC, merged