tablist can be empty + example
mdn/content pull request #3235
Opened 2021-03-17 17:31 UTC by thierryk

- Added mention of empty tablist in the widget description
- Added a paragraph explaining how ARIA works with empty tablist
- Added a markup example of tabs not based on list items
- Added a link to a [live example](https://tabpanelwidget.com) of widgets using an empty `tablist`

Original issue:  https://github.com/mdn/content/issues/366

2021-03-17 18:12 UTC, chrisdavidmills commented
I'm gonna give this one to @ericwbailey to review, as he know a lot more about ARIA than me. Thanks in advance ;-)

2021-03-19 00:19 UTC, ericwbailey commented
This one might take me a little bit to get to, I want to do some testing for where the rubber meets road with ARIA and actual AT.

2021-03-19 08:16 UTC, chrisdavidmills commented
> This one might take me a little bit to get to, I want to do some testing for where the rubber meets road with ARIA and actual AT.

This sounds amazing, please take your time. Much appreciated Eric.

2021-05-26 06:59 UTC, sideshowbarker commented
@ericwbailey Per https://github.com/mdn/content/pull/3235#issuecomment-802407360 it seems this is one still waiting on you.

2021-09-01 03:05 UTC, sideshowbarker commented
> @ericwbailey Per [#3235 (comment)](https://github.com/mdn/content/pull/3235#issuecomment-802407360) it seems this is one still waiting on you.

2021-09-01 23:57 UTC, scottaohara commented
if using an example such as the one provided here, there should be a note that VoiceOver / Safari do not presently support this `aria-owns` technique (due to lack of proper support for `aria-owns`).  For instance, if using VoiceOver with Firefox the expected numbering of tabs are announced when navigating to each `tab`.  Navigating using VO key + right arrow in Firefox will correctly navigate a user through the tabs in the tablist.  But with VoiceOver and Safari, the number of tabs in the tablist is not announced. Navigating using VO + right arrow does not go to the next tab in the tablist, because the tabs are never re-parented into the `tablist` due to the lack of `aria-owns` support.  Rather, the user is navigated into the contents of the tabpanel.

Again, I stress this is a lack of implementation with Webkit, but since there is no alternative for macOS / iOS, it seems really important that if showcasing this pattern people know it won't work as expected with Safari.

2021-09-02 16:41 UTC, thierryk commented
> Navigating using VO + right arrow does not go to the next tab in the tablist 

That's correct, *moving the cursor* goes to the next element (which for Webkit is the "panel"), but it should be noted that this does not prevent AT users to navigate through the Widget ([right/left arrow keys *alone*](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html#kbd_label) suffice to move through the tabs). 

>  But with VoiceOver and Safari, the number of tabs in the tablist is not announced

Yes, that may confuse people who are familiar with these widgets and expect to get the numbering of tabs (which is pretty useful too). :-(

2021-09-02 18:54 UTC, scottaohara commented
>noted that this does not prevent AT users to navigate through the Widget (right/left arrow keys alone suffice to move through the tabs).

correct, but it does prevent a VO user's ability to easily scan through the tabs to see what's available, without auto-selecting them, as would be expected when using VO+arrow keys specifically.  

Also, while I only mentioned iOS in passing in my above comment, it was to indicate that the same behavior happens there when swiping.  So, as arrow keys are not an option if using a touch interface alone, a user would likely have to interact with this a bit to realize it doesn't meet the expected element order they'd expect for a tablist, and then start exploring by touch to try and find the next tab (if that option of exploring is available to them) to more effectively use this pattern.

Again though, regardless of potential user impact the point is that aria-owns is not supported by Webkit at all, so if someone were to walk away from this example thinking they could use aria-owns in other more creative DOM patterns, they would be incorrect.  

A note would be best to indicate that again, nothing is technically incorrect here, but if you want this to work as expected with Webkit + VO, then this is not the pattern you should be using.

2021-09-02 21:19 UTC, thierryk commented
> correct, but it does prevent a VO user's ability to easily scan through the tabs to see what's available, without auto-selecting them, as would be expected when using VO+arrow keys specifically.

There may be a way to fix this issue while keeping the same pattern. I did a quick test to see if `aria-hidden` would allow to move the cursor as if there was no element between tabs: https://codepen.io/thierry/full/YzQyXdp

2021-09-02 23:26 UTC, scottaohara commented
understanding this is a proof of concept, this does seem to work around the issue... but by doing so it makes the content of the tabpanel inaccessible to VO / Narrator cursor.  NVDA is working quite funky with how some of the content is being exposed here too.  I'm sure it's not really worth me pushing too hard on this though with any further testing.

2021-09-03 00:01 UTC, thierryk commented
> this does seem to work around the issue... but by doing so it makes the content of the tabpanel inaccessible to VO / Narrator cursor.

Yes, there is no script on that test page so `aria-hidden` is never removed. I believe that should work though as long as we manage the state of the attribute (`true`/`false`).  We'll try a few things...
**Thank you very much for your feedback**

2021-09-03 16:43 UTC, thierryk commented
> there is no script on that test page so `aria-hidden` is never removed.

Here is a [working example](https://l54fb.csb.app) that seems to address the issue with cursor navigation in Safari.
If it works without creating new issues then it will help make that *markup pattern* (which does not rely on jump links) more "usable" to VO/Safari users. 
Once again, thanks @scottaohara for all your feedback.

2021-09-12 15:38 UTC, scottaohara commented
this update is unfortunately very broken on iOS safari/vo.   now none of the tabpanel content is accessible on iOS.  (would definitely recommend reverting this change in your script, as at least the previous version didn't break accessing content).

navigating on macOS with VO + left/right arrow makes the tabs select, as if you were using just left/right arrows.  but that should not be the case.   navigating with VO/left/right arrows would be for a user to scan the available tabs without selecting them.  Navigating past the visible tablist using vo+right arrow skips over the tabpanel and instead shows the 'tab through to leave this widget..." message.  A VO+left arrow key is then required for the user to navigate back to the tabpanel.  

i have not tried to review this with PC screen readers, nor do i think it's necessary since i'd recommend this workaround be removed.

again, i'd stress that if accepting this PR, it be done so simply with a note stating that this pattern is not supported in Webkit browsers.  The amount of effort to work around Webkit's lack of aria-owns support seems like it'd be better spent just adding the tabs into the tablist.

2021-09-14 02:07 UTC, thierryk commented
> this update is unfortunately very broken on iOS safari/vo

Thanks! We have reverted that change.

> stating that this pattern is not supported in Webkit browsers. 

I added this:

**Note**: this pattern is not supported by Voice Over in WebKit browsers due to the lack of support for [`aria-owns`](https://www.w3.org/TR/wai-aria-1.1/#aria-owns) in WebKit ([Bug 223798 ](https://bugs.webkit.org/show_bug.cgi?id=223798)).

> it'd be better [...] just adding the tabs into the tablist.

In my experience, browser vendors feel no pressure supporting features that are not implemented in the wild. In my opinion, if we want WebKit to fix that bug, we should "send the signal" that this pattern is here to stay (as it is *better on many levels*) rather than suggesting authors should rather ignore it and stick to "jump links". :(

2021-09-14 13:26 UTC, ericwbailey requested changes
I don't think a note is sufficient here, given the severity of the lack of support. VoiceOver on iOS is the majority screen reader for mobile, so a solution that doesn't work for it is a non-starter. 

I am also concerned about the note itself, given most developers I know will grab code and not care about the particulars. That means we have a responsibility to not create access barriers.

Thank you for your work on this, @thierryk. However, I would like to see this updated to remove the coded implementation and stress the lack of real world support.

2021-09-15 04:13 UTC, thierryk commented
> given most developers I know will grab code and not care about the particulars

I took the content of [tabpanelwidget.com](https://bugs.webkit.org/show_bug.cgi?id=223798) down. We've been working hard to come up with a great solution but I agree that the issue it creates in VoiceOver/WebKit is "counter productive".

I'll put the site back up once WebKit fixes that bug.

2021-09-15 04:13 UTC, closed without merging