Clean up global SVG attributes
mdn/content pull request #32366
Opened 2024-02-20 18:39 UTC by queengooborg

This PR performs a number of updates to the SVG attributes pages to clean up the pages:
- **Remove mention of global attributes on individual elements pages**
- **Remove landing pages for attribute categories**
- **Update BCD keys**

Note: review and merge along with https://github.com/mdn/browser-compat-data/pull/22267.

2024-02-21 09:57 UTC, chrisdavidmills approved these changes
I'm not really able to check this all in detail, but the pages I've looked at LGTM; nice work @queengooborg.

2024-02-21 16:33 UTC, queengooborg commented
Thank you, @chrisdavidmills!

Would you also be down to review/approve the BCD PR by chance?

2024-02-21 16:37 UTC, chrisdavidmills commented
> Thank you, @chrisdavidmills!
> 
> Would you also be down to review/approve the BCD PR by chance?

I am not, no. I can do, if no one grabs it.

2024-02-22 00:00 UTC, estelle commented on files/en-us/web/svg/element/a/index.md
> -  - : Most notably: {{SVGAttr("xlink:title")}}
when there is a "most notably" global attribute on an SVG page, we should ensure that it is somewhere on the page. Add a See Also to all the pages htat have a "most notably" global attribute if that attribute is not already in the context of page.

2024-02-22 00:01 UTC, estelle commented on files/en-us/web/svg/element/animate/index.md
> -
ensure the following links are in the page; if not in the content, within a "see also"

- {{SVGAttr("attributeName")}}
- {{SVGAttr("additive")}}
- {{SVGAttr("accumulate")}}
and possibly these:
- {{SVGAttr("onbegin")}}
- {{SVGAttr("onend")}}
- {{SVGAttr("onrepeat")}}

2024-02-22 00:06 UTC, estelle requested changes, later dismissed
I made a few comments. This PR is too big! Would it be possible to break it into 3: 
1. the updating of browser compat in the front matter
2. removal of global attributes (while ensuring the links to those under "most notably" are included in their relevant pages
3. removal of the attribute category landing pages

I spot checked for #1, and think it's ok.
Changes are required for #2.
I did not look at category 3.

2024-02-22 01:24 UTC, queengooborg commented
I can try splitting it into individual PRs, but I'm afraid there's a lot of crossover between the changes and they must be merged in order to prevent issues.

I'd probably recommend reviewing this PR per commit instead of all at once?

2024-02-22 05:22 UTC, estelle commented
Review #1: assuming BCD was updated, there are no visible issues here.

2024-02-22 06:08 UTC, estelle reviewed
Review part 2: Remove landing pages for attribute categories

A few minor issues in this section.

I'll review part 3 after the pages are updated to ensure the important attributes are not omitted from the element pages.

2024-02-22 06:09 UTC, estelle commented on files/en-us/web/svg/attribute/presentation/index.md
> -- [solid-opacity](#solid-opacity)
missing from the list on the main attribute page.

2024-02-22 06:09 UTC, estelle commented on files/en-us/web/svg/attribute/presentation/index.md
> -- [d](#d)
missing from the list on the main attribute page.

2024-02-22 06:09 UTC, estelle commented on files/en-us/web/svg/attribute/presentation/index.md
> -- [transform](#transform)
this doesn't matter ;)

2024-03-01 04:17 UTC, queengooborg commented
This PR is now ready for re-review and merging, along with the BCD PR!

2024-03-04 13:47 UTC, queengooborg commented
The BCD PR has been approved and merged, so this will be merged once the next BCD release is out!

2024-03-06 05:24 UTC, estelle approved these changes

2024-03-06 14:40 UTC, merged