Expand differences between class and function prototype properties
mdn/content pull request #32414
Opened 2024-02-23 21:53 UTC by DanKaplanSES

Fixes #31649

2024-02-23 21:56 UTC, DanKaplanSES commented
2nd sentence of my change:

> However, the `prototype` property of a `class` is not directly accessible or modifiable from within an instance of that class.

Should I surround the word "class" in backticks this way?

2024-02-24 00:02 UTC, Josh-Cena requested changes

2024-02-24 00:02 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/function/prototype/index.md
> +> **Note:** [Classes](/en-US/docs/Web/JavaScript/Reference/Classes) are a type of function, so most of the same rules apply. However, the `prototype` property of a `class` is not directly accessible
It's not the intention of this note to talk about instances. We are just saying `Object.getOwnPropertyDescriptor(class {}, "prototype").writable` is false.

```suggestion
> **Note:** [Classes](/en-US/docs/Web/JavaScript/Reference/Classes) are a type of function, so most of the description here applies to the `prototype` property of classes too. The only salient difference is that the `prototype` property of a class is not writable.
```

2024-02-24 16:36 UTC, Josh-Cena approved these changes
Thanks!

2024-02-24 16:36 UTC, merged