fix: flaws in web/svg batch 1
mdn/content pull request #3243
Opened 2021-03-17 22:05 UTC by nschonni

2021-03-17 22:45 UTC, nschonni commented
@chrisdavidmills looks like the CODEOWNERS isn't picking up the assignment for @mdn/yari-content-svg for some reason for this and the other 3 svg flaws PRs

2021-03-18 04:30 UTC, wbamberg requested changes
Thanks @nschonni ! I had a few comments, one about the cssxref argument and a few about what to do about mixin confusions in SVGElement.

2021-03-18 04:30 UTC, wbamberg commented on files/en-us/web/svg/attribute/data-_star_/index.html
> +<p>The <code><strong>data-*</strong></code> SVG attributes are called custom data attributes. They let SVG markup and its resulting DOM share information that standard attributes can't, usually for s
This is confusing. We're talking about `SVGElement` here which has a `dataset` property via the `HTMLOrForeignElement` mixin.

I don't know if `HTMLOrForeignElement` is one of the mixins that @Elchi3 is removing, in which case we should eventually be able to link to a `SVGElement.dataset` page. But if not, or until that happens, it would probably be better to keep all this description in the realm of `SVGElement`, by saying something like:

"Their custom data are available via the {{domxref("SVGElement")}} interface of the element the attributes belong to, with the <code>SVGElement.dataset</code> property."

Ugh, mixins!

2021-03-18 04:30 UTC, wbamberg commented on files/en-us/web/svg/attribute/data-_star_/index.html
> +<p>The {{domxref("HTMLOrForeignElement.dataset")}} property is a {{domxref("DOMStringMap")}} that provides the attribute <code>data-test-value</code> via <code>SVGElement.dataset.testValue</code>. Hy
This is confusing, in the same way. "The HTMLOrForeignElement.dataset property is a DOMStringMap that provides the attribute data-test-value via SVGElement.dataset.testValue." - wait, what? We just said it's HTMLOrForeignElement.dataset, now we're talking about `SVGElement.dataset`?

Given the state of things it would probably be better to do something like:

"The `dataset` property of [SVGElement](whatever) is a `DOMStringMap` that provides the attribute data-test-value via `SVGElement.dataset.testValue`."

Sorry, I know you are not introducing this confusion. But we may as well try to improve things :).

2021-03-18 04:30 UTC, wbamberg commented on files/en-us/web/svg/attribute/data-_star_/index.html
> + <li>The {{domxref("HTMLOrForeignElement.dataset")}} property used to access these attributes from scripts.</li>
Same comment. Given where we are, something like "The `dataset` property of [`SVGElement`](...)" would be better.

2021-03-18 09:59 UTC, chrisdavidmills commented
> @chrisdavidmills looks like the CODEOWNERS isn't picking up the assignment for @mdn/yari-content-svg for some reason for this and the other 3 svg flaws PRs

Hrm, I've played with the settings, and hopefully this will work in future.

2021-03-18 10:19 UTC, Elchi3 commented on files/en-us/web/svg/attribute/data-_star_/index.html
> +<p>The <code><strong>data-*</strong></code> SVG attributes are called custom data attributes. They let SVG markup and its resulting DOM share information that standard attributes can't, usually for s
Added HTMLOrForeignElement to my list. Thanks! 
It would be better to leave this as SVGElement.

2021-03-18 19:57 UTC, nschonni commented on files/en-us/web/svg/attribute/clip-path/index.html
> +   <td>{{cssxref('url()')}} | [ {{cssxref('basic-shape')}} || <code>&lt;geometry-box&gt;</code> ] | <code>none</code></td>
Ah, opened https://github.com/mdn/yari/pull/3281

2021-04-13 16:41 UTC, Ryuno-Ki commented
@nschonni I defer to @wbamberg's change requests here before looking into it.

(I received a notification for SVG team).

2021-05-13 14:09 UTC, closed without merging