RTCCodecStats - add docs
mdn/content pull request #32452
Opened 2024-02-27 05:14 UTC by hamishwillee

This adds docs for `RTCCodecStats`, a "codec statistics" object you can get by iterating a [`RTCStatsReport`](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport).

This is part of the ongoing work to finished RTC stats, which was started in https://github.com/mdn/content/pull/27028

2024-02-27 05:17 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +The **`clockRate`** property of the {{domxref("RTCCodecStats")}} dictionary is a positive number containing the media sampling rate in Hz.
Is there anyone we can ask to confirm behaviour of WebRTC stuff?

Specifically, "media sampling rate" is what the spec says. However this does not match [`RTCRtpCodecParameters.clockRate`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpCodecParameters#clockrate) - which is usually where I'd expect the data to come from.

Note that `RTCCodecStats.clockRate` is the media sampling rate, and not the 

Note that `RTCRtpCodecParameters.clockRate` is the clock rate is the rate at which the codec's RTP timestamp advances.
Most codecs have specific values or ranges of values they permit; see the [IANA payload format media type registry](https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-2) for details.

This need not be the same as the codecs sampling rate - according to wikipedia the video codecs typically use a clock rate of 90000 so their frames can be more precisely aligned with the RTCP NTP timestamp, even though video sampling rates are typically in the range of 1–60 samples per second.

So I just want to confirm ...

2024-03-06 22:12 UTC, dipikabh requested changes
Hi @hamishwillee, thanks for this work!
I've only done a language review. I understand some of the sentences are as they appear on other similar pages. I've commented/asked questions in case there is scope for improving clarity.

2024-03-06 22:12 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/timestamp/index.md
> +A {{domxref("DOMHighResTimeStamp")}} value indicating the time at which the activity described by the statistics in this object was recorded, in milliseconds elapsed since the beginning of January 1,
```suggestion
A {{domxref("DOMHighResTimeStamp")}} value indicating the time when the activity described by the statistics in this object was recorded. It is measured in milliseconds since January 1, 1970, UTC.
```

2024-03-06 22:12 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/timestamp/index.md
> +The value should be accurate to within a few milliseconds but may not be entirely precise, either because of hardware or operating system limitations or because of [fingerprinting](/en-US/docs/Glossa
Is this what we intend to say here:
```suggestion
The value is accurate to within a few milliseconds, though it might not be entirely precise because of hardware or operating system limitations. Additionally, [fingerprinting](/en-US/docs/Glossary/Fingerprinting) protection could reduce the precision or accuracy of the time reported.
```

2024-03-06 22:12 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/transportid/index.md
> +You can correlate the codec and associated transport statistics by matching the `RTCCodecStats.transportId` with a {{domxref("RTCTransportStats.id")}} value.
```suggestion
You can correlate the codec and associated transport statistics by matching the `RTCCodecStats.transportId` with an {{domxref("RTCTransportStats.id")}} value.
```

2024-03-08 02:34 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/index.md
> +The **`RTCCodecStats`** dictionary of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides statistics about a codec that is being used by RTP streams being sent or received by the associated {{d
Yes, that is better thanks. I've added glossary and also added back "being" in place. The reason is that the codec stats only apply while the streams are _being_ sent - there's no historical data and this gets deleted when all streams that use it are gone.

2024-03-08 02:38 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +{{Compat}}
Really not sure. I had decided not to until https://github.com/mdn/content/pull/32452/files#r1503650664 is resolved.

I guess so.

```suggestion
{{Compat}}

## See also

- {{domxref("RTCRtpCodecParameters.clockRate")}}
```

2024-03-08 02:42 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/id/index.md
> +Using the `id`, you can correlate this statistics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref(
Not doing this now. But I have emailed myself to perhaps do a new PR to change all of them globally.

2024-03-08 02:48 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/index.md
> +Note that other transports will use their own, different, `RTCCodecStats` objects.
Thanks. Yes, I prefer consolidate (added). I used coalesce because it is the spec term, but as far as I can tell the cases where the words have a different nuance do not apply here.

2024-03-08 02:53 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/mimetype/index.md
> +The **`mimeType`** property of the {{domxref("RTCCodecStats")}} dictionary is a string containing the codec's MIME media type and subtype.
I prefer MIME type and a glossary link. Modified your text. Thanks.

2024-03-08 02:55 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/payloadtype/index.md
> +The **`payloadType`** property of the {{domxref("RTCCodecStats")}} dictionary is a positive integer in the range from 0 to 127 that describes the format of the RTP payload used in RTP encoding or dec
```suggestion
The **`payloadType`** property of the {{domxref("RTCCodecStats")}} dictionary is a positive integer in the range from 0 to 127 that describes the format of the {{glossary("RTP")}} payload used in RTP encoding or decoding.
```

2024-03-08 03:26 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/timestamp/index.md
> +A {{domxref("DOMHighResTimeStamp")}} value indicating the time at which the activity described by the statistics in this object was recorded, in milliseconds elapsed since the beginning of January 1,
I'm good with this but have added to my notes to change globally once this and my other ones merge.

2024-03-08 04:04 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/timestamp/index.md
> +The value should be accurate to within a few milliseconds but may not be entirely precise, either because of hardware or operating system limitations or because of [fingerprinting](/en-US/docs/Glossa
No. My versions says "should be" within a few ms, whereas your version must be accurate to within a few ms irrespective of all factors. I actually don't know which it is, so would rather say "should be".

The bigger problem is that this text is many years old - all I've done is propagated the original info in a dictionary. I can't be sure from the spec that this is still true. I've asked here https://github.com/w3c/webrtc-stats/issues/786

2024-03-08 04:06 UTC, hamishwillee commented
@dipikabh Thanks for the review. I've accepted most of it. For the remainder I'll do as a post process against all the duplicates "at some point" (have taken a copy of actions)

2024-03-08 14:25 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/index.md
> +The **`RTCCodecStats`** dictionary of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides statistics about a codec that is being used by RTP streams being sent or received by the associated {{d
Nice and thanks for the explainer

2024-03-08 14:30 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/id/index.md
> +Using the `id`, you can correlate this statistics object with others, in order to monitor statistics over time for a given WebRTC object, such as an {{domxref("RTCPeerConnection")}}, or an {{domxref(
Sounds good

2024-03-08 14:35 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +{{Compat}}
This would need to be a slug link: /en-US/docs/Web/API/RTCRtpCodecParameters#clockrate

2024-03-08 14:58 UTC, dipikabh commented on files/en-us/web/api/rtccodecstats/timestamp/index.md
> +The value should be accurate to within a few milliseconds but may not be entirely precise, either because of hardware or operating system limitations or because of [fingerprinting](/en-US/docs/Glossa
Got it - "is" vs "should be", makes sense

Good move to to seek clarification 👍

2024-03-08 15:00 UTC, dipikabh approved these changes
Thanks, @hamishwillee. The changes and your clarifications/edits look good.

Only one nit in the RTCCodecStats/clockRate page (https://github.com/mdn/content/pull/32452#discussion_r1517797930), but leaving my +1

2024-03-11 00:17 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +{{Compat}}
Indeed. Thanks!
 Updated above.

2024-03-11 00:19 UTC, hamishwillee commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +- {{domxref("RTCRtpCodecParameters.clockRate")}}
Fix duplicate heading
```suggestion
## See also

- [`RTCRtpCodecParameters.clockRate`](/en-US/docs/Web/API/RTCRtpCodecParameters#clockrate)
```

2024-03-11 00:29 UTC, hamishwillee commented
thanks @dipikabh - appreciate your patience.

2024-03-11 22:19 UTC, hamishwillee commented
@wbamberg Can you please give this a look since you reviewed my other WebRTC stats PRs? It's had editorial/language review from @dipikabh already - some of those are outstanding because I'll do them as a job-lot later across all the docs.

There is a technical question about timestamps in https://github.com/mdn/content/pull/32452#discussion_r1517137405 - still hoping to get some info to be "certain" on that. But if you know about this already ...

2024-03-14 17:29 UTC, wbamberg commented on files/en-us/web/api/rtccodecstats/clockrate/index.md
> +The **`clockRate`** property of the {{domxref("RTCCodecStats")}} dictionary is a positive number containing the media sampling rate in Hz.
Right, so we could fix this in a follow-up if it turns out to be wrong.

2024-03-14 17:31 UTC, wbamberg approved these changes
Thanks Hamish! It's been a while since I saw one of these, it was hard to remember what they are supposed to look like! I had one super-nit, so approving anyway.

2024-03-14 17:31 UTC, wbamberg commented on files/en-us/web/api/rtccodecstats/index.md
> +  - : A string containing the media MIME type/sub-type, such as video/VP8.
```suggestion
  - : A string containing the media MIME type/subtype, such as video/VP8.
```

(matching the spec language and the linked page)

2024-03-14 22:50 UTC, hamishwillee commented
Thanks very much @wbamberg (and @dipikabh ). I appreciate these are not fun to review!

2024-03-14 22:53 UTC, merged