added section explaining path merging of url and base parameters
mdn/content pull request #32473
Opened 2024-02-28 14:58 UTC by teetotum

### Description

Added one new section explaining how url and base paths are merged; illustrated with four examples

### Motivation

The simple but erroneous assumption that url and base are simply concatenated is a mistake easy enough to make.
Even if a developer is conscious about making an assumption and therefore cross checking by viewing the documentation he/she will not find the information on the page currently.
The documentation page should have a section or a note addressing this.

### Additional details

[RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986.html#section-5.2)

### Related issues and pull requests

2024-02-29 18:55 UTC, teetotum reviewed
looks good to me

2024-03-14 01:06 UTC, wbamberg reviewed
Sorry to be slow reviewing this. I think the content is fine, but we usually don't have ad hoc top-level sections in these docs, so perhaps it would be better to have this as part of the preamble, before "Syntax".

It might also be worth having an example like:

```

const E = new URL("../articles", "https://developer.mozilla.org/api/v1/");
// => 'https://developer.mozilla.org/api/articles'
```

?

2024-03-22 11:16 UTC, teetotum commented
I added your example to show the effect of `../articles` and also another one to show the effect of `./articles` to have a complete collection of all combinations (can you confirm? did I miss one?).

I tried your suggestion of moving the text into the preamble. But it felt strange because at that point in the doc the constructor arguments have yet to be introduced to the reader.

Instead I moved the text into a _note_ under _Syntax -> Arguments_ where it seems to fit. I moved the examples into the _Examples_ section but kept them in their own block.

Not sure if the wording in the _note_ is too repetitive and should be trimmed down a bit. What do you think?

2024-03-22 23:30 UTC, wbamberg requested changes
Thank you for the update, @teetotum !

I would not make this a note, and I made a suggestion to:
- not claim we cover all possibilities, since I'm not sure we do, and not sure it is all that important to do that
- fix the URL fragment in the link

2024-03-22 23:30 UTC, wbamberg commented on files/en-us/web/api/url/url/index.md
> +> You can find examples for all possible combinations under [Examples - Merging of url and base paths](#merging-of-url-and-base-paths).
```suggestion
> See the examples under [Examples - Merging of url and base paths](#merging_of_url_and_base_paths).
```

2024-03-22 23:30 UTC, wbamberg commented on files/en-us/web/api/url/url/index.md
> +> You can find examples for all possible combinations under [Examples - Merging of url and base paths](#merging-of-url-and-base-paths).
However I would also not make this a note.

2024-03-23 07:46 UTC, teetotum commented
I applied your fix and turned the _note_ into regular text. It still sits in the _Parameters_ sections under the listed parameters but doesn't have the blue box anymore.

2024-03-23 19:09 UTC, wbamberg approved these changes
👍 thank you @teetotum !

2024-03-23 19:09 UTC, merged