Add documentation for display-mode: picture-in-picture
mdn/content pull request #32471
Opened 2024-02-28 14:11 UTC by chrisdavidmills

### Description

Chrome 123 adds support for the [`@media` `display-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode) `picture-in-picture` value. This PR adds MDN content to cover this, both including the value in the `display-mode` reference page (and making it less PWA-centric) and including an example of usage in the document PIP API pages.

- ChromeStatus: https://chromestatus.com/feature/5198101675769856
- Spec: https://drafts.csswg.org/mediaqueries-5/#display-mode-picture-in-picture
- Basic demo: https://document-picture-in-picture-api.glitch.me/display-mode.html

### Motivation

### Additional details

### Related issues and pull requests

- BCD: https://github.com/mdn/browser-compat-data/pull/22321
- dom-examples demo update: https://github.com/mdn/dom-examples/pull/263

2024-02-28 15:03 UTC, beaufortfrancois commented on files/en-us/web/css/@media/display-mode/index.md
> +| `picture-in-picture`      | This mode allows users to continue consuming specific content while they interact with other sites or applications on their device. The app is displayed in a floating an
Why is this \`none\` while the others are "(none)"?

2024-02-29 09:32 UTC, chrisdavidmills commented on files/en-us/web/api/document_picture-in-picture_api/using/index.md
> +In our demo, we combine the `display-mode: picture-in-picture` value with the {{cssxref("@media/prefers-reduced-motion", "prefers-reduced-motion")}} media feature to create light and dark color schem
Good idea. Added in next commit.

2024-02-29 09:35 UTC, chrisdavidmills commented on files/en-us/web/api/document_picture-in-picture_api/using/index.md
> +@media (display-mode: picture-in-picture) and (prefers-color-scheme: light) {
I dunno — I kinda like using it more interestingly than just the basic simplest example. But I do know what you mean. To mitigate any potential for confusion, I've also added a basic usage example to show what it looks like on its own.

2024-02-29 09:38 UTC, chrisdavidmills commented on files/en-us/web/css/@media/display-mode/index.md
> +| `picture-in-picture`      | This mode allows users to continue consuming specific content while they interact with other sites or applications on their device. The app is displayed in a floating an
Ooops. I've changed them all to "None", as I didn't think the parens were needed.

2024-02-29 09:41 UTC, beaufortfrancois commented on files/en-us/web/api/document_picture-in-picture_api/using/index.md
> +@media (display-mode: picture-in-picture) and (prefers-color-scheme: light) {
Adding a basic usage example looks good to me.

2024-02-29 09:43 UTC, beaufortfrancois commented on files/en-us/web/css/@media/display-mode/index.md
> +| `picture-in-picture`      | This mode allows users to continue consuming specific content while they interact with other sites or applications on their device. The app is displayed in a floating an
👍

2024-02-29 09:46 UTC, chrisdavidmills commented
Awesome, thanks for the tech review, @beaufortfrancois. I'll now move this on to the editorial review stage.

2024-03-13 18:59 UTC, wbamberg commented
I can look at this.

2024-03-13 23:38 UTC, wbamberg requested changes

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +The **`display-mode`** [CSS](/en-US/docs/Web/CSS) [media feature](/en-US/docs/Web/CSS/@media#media_features) can be used to test the mode in which an application is being displayed within a device's
```suggestion
The **`display-mode`** [CSS](/en-US/docs/Web/CSS) [media feature](/en-US/docs/Web/CSS/@media#media_features) can be used to test whether a web app is being displayed in a normal browser tab or in some alternative way, such as a standalone app or fullscreen mode.
```

I thought this opening paragraph could do with a more concrete description, and things like "display context" are a bit unclear.

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +- The [Fullscreen API](/en-US/docs/Web/API/Fullscreen_API) and other APIs such as the [Document Picture-in-Picture API](/en-US/docs/Web/API/Document_Picture-in-Picture_API) can be used to display reg
A few things about this:

>  A [progressive web app](/en-US/docs/Web/Progressive_web_apps) will often rely on opening apps [fullscreen](/en-US/docs/Web/API/Fullscreen_API) to provide an experience more like a native app. 

I think the link to fullscreen API here is misleading, it implies that PWAs have to use the fullscreen API "to provide an experience more like a native app", but they don't of course. AIUI the fullscreen API has nothing in particular to do with PWAs.
 
> this `display-mode` media feature corresponds to the Web app manifest's [`display`](/en-US/docs/Web/Manifest#display) member

I think this isn't quite right: _some_ of these values correspond to `display`, but not all. 

> Both apply to the top-level browsing context and any child browsing contexts

I assume it's also true that `display-mode` also applies to child browsing contexts outside PWAs, so this doesn't feel like it belongs under this bullet.

> we aware that the feature query will apply regardless of whether a web app manifest is present.

Should be media query not feature query?

> - The [Fullscreen API](/en-US/docs/Web/API/Fullscreen_API) and other APIs such as the [Document Picture-in-Picture API](/en-US/docs/Web/API/Document_Picture-in-Picture_API) can be used to display regular web app content in different contexts.

I think "contexts" here is not the best term, especially as we just talked about "browsing contexts".

```suggestion
For example:

- A [progressive web app](/en-US/docs/Web/Progressive_web_apps) [can set its display mode](/en-US/docs/Web/Progressive_web_apps/How_to/Create_a_standalone_app) by setting the [`display`](/en-US/docs/Web/Manifest#display) member in its manifest. In this case, the value of `display-mode` identifies the value that was set (but note that this may not the be same as the value requested in the manifest, since a browser may not support the requested mode).

- Any web app can use the [Fullscreen API](/en-US/docs/Web/API/Fullscreen_API) or the [Document Picture-in-Picture API](/en-US/docs/Web/API/Document_Picture-in-Picture_API) to set the display mode, and in this case the value of `display-mode` identifies to the mode that was set.

The `display-mode` value applies to the top-level browsing context and any child browsing contexts.
```

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +| Display mode              | Description
What does "Fallback display mode" mean for this media query? I understand what it means for the `display` manifest member: if you request, say, `standalone` and the browser doesn't support that, then you get `minimal-ui`, and if the browser doesn't support _that_, then you get `browser`. But what does it mean for the media query?

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +In this example, we combine the `display-mode: picture-in-picture` value with the {{cssxref("@media/prefers-reduced-motion", "prefers-reduced-motion")}} media feature to create light and dark color s
```suggestion
In this example, we combine the `display-mode: picture-in-picture` value with the {{cssxref("@media/prefers-color-scheme", "prefers-color-scheme")}} media feature to create light and dark color schemes that are applied based on the user's color scheme preference, only when the app is being shown in Picture-in-Picture mode.
```

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/index.md
> +  - : The mode in which an application is being displayed within a device's operating system, for example in `fullscreen` or `picture-in-picture` mode.
IMO "within a device's operating system" is a strange statement. Everything is "within a device's operating system". I would just say:

```suggestion
  - : The mode in which an application is being displayed: for example [fullscreen](/en-US/docs/Web/API/Fullscreen_API) or [picture-in-picture](/en-US/docs/Web/API/Document_Picture-in-Picture_API/) mode.
```

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +| `fullscreen`              | All of the available display area is used and no user agent {{glossary("chrome")}} is shown. This can be used to apply CSS only when the app has been put in fullscreen m
```suggestion
| `fullscreen`              | All of the available display area is used and no user agent {{glossary("chrome")}} is shown. This can be used to apply CSS only when the app has been put in fullscreen mode by the [Fullscreen API](/en-US/docs/Web/API/Fullscreen_API) or using the `fullscreen` value of the [`display`](/en-US/docs/Web/Manifest#display) member of the Wep App Manifest.                                                                                                                                             | `standalone`          |
```

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/api/document_picture-in-picture_api/using/index.md
> +The {{cssxref("@media/display-mode", "display-mode")}} [media feature](/en-US/docs/Web/CSS/@media#media_features)'s `picture-in-picture` value allows developers to apply CSS to a document based on wh
```suggestion
The `picture-in-picture` value of the {{cssxref("@media/display-mode", "display-mode")}} [media feature](/en-US/docs/Web/CSS/@media#media_features) allows developers to apply CSS to a document based on whether it is being displayed in Picture-in-Picture mode. Basic usage looks like so:
```

Very nitpicky but IMO this is more readable.

2024-03-13 23:38 UTC, wbamberg commented on files/en-us/web/api/document_picture-in-picture_api/using/index.md
> +In [our demo](https://mdn.github.io/dom-examples/document-picture-in-picture/), we combine the `display-mode: picture-in-picture` value with the {{cssxref("@media/prefers-reduced-motion", "prefers-re
```suggestion
In [our demo](https://mdn.github.io/dom-examples/document-picture-in-picture/), we combine the `display-mode: picture-in-picture` value with the {{cssxref("@media/prefers-color-scheme", "prefers-color-scheme")}} media feature to create light and dark color schemes that are applied based on the user's color scheme preference, only when the app is being shown in Picture-in-Picture mode.
```

2024-03-14 17:24 UTC, chrisdavidmills commented on files/en-us/web/css/@media/display-mode/index.md
> +| Display mode              | Description
Good point. I'm pretty sure this is wrongly copied from the manifest info. It doesn't make sense to have a fallback value for the media query, and the sec doesn't mention anything about fallback values for `display-mode`.

So, I've taken the liberty of removing that row, and also replacing the table with a dl - much more maintainable.

2024-03-14 17:32 UTC, chrisdavidmills commented
Brilliant, thanks for the review @wbamberg . I mostly just accepted your changes and then make a couple of small edits. Only one major-ish bit to check.

2024-03-14 17:36 UTC, wbamberg commented on files/en-us/web/css/@media/display-mode/index.md
> +| Display mode              | Description
Yes, I was going to say, if we can get rid of the fallback column then we can use a dl here. I also couldn't find this in the spec.

2024-03-14 17:39 UTC, wbamberg approved these changes
👍 thanks for the updates Chris!

2024-03-14 17:40 UTC, merged