http.server is not limited to serving static files
mdn/content pull request #32495
Opened 2024-03-01 01:07 UTC by hamishwillee

Fixes #32446

This modifies the [Running server-side languages locally](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server#running_server-side_languages_locally) section in _setting up a local testing server_ to make it clear that:
- The right way to serve local files depends on what you're doing
- If you're using a web framework that has a development server then using that server is probably the easiest approach for testing the code.
- Otherwise you can use some other server, and it points out that `http.server` is an option. I don't know much about this, but there seems to be a fairly good tutorial in realpython, so I linked to that. 
  - We could say more and separate out a section for this case if reviewers think that would be useful. The poster of the issue provided an example in the issue. I didn't want to make this document too heavyweight, because I think that most audiences for this doc will be using a web framework.

2024-03-01 02:45 UTC, wbamberg requested changes
Just a couple of gripes.

2024-03-01 02:45 UTC, wbamberg commented on files/en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server/index.md
> +If you're working with a web framework, usually the framework will provide its own simple and easy to use development server.
```suggestion
If you're working with a web framework, usually the framework will provide its own development server.
```

2024-03-01 02:45 UTC, wbamberg commented on files/en-us/learn/common_questions/tools_and_setup/set_up_a_local_testing_server/index.md
> +If you're not working directly with with a server-side framework or a programming language that provides a development server, Python's `http.server` module can also be used to test server-side code
```suggestion
If you're not working directly with with a server-side framework or a programming language that provides a development server, Python's `http.server` module can also be used to test server-side code written in languages such as Python, PHP, JavaScript, and so on, by invoking server-side Common Gateway Interface (CGI) scripts.
```

Could be worth a glossary entry but not really worth it.

2024-03-03 23:05 UTC, hamishwillee commented
@wbamberg - your gripe-fix-suggestions accepted. Thankyou!

2024-03-04 00:25 UTC, wbamberg approved these changes
👍 thank you Hamish, looks great.

2024-03-04 06:18 UTC, merged

2024-03-04 06:18 UTC, hamishwillee commented
THanks for the review!