Bluetooth - and interface can't return a promise
mdn/content pull request #32533
Opened 2024-03-03 22:12 UTC by hamishwillee

Fixes #32529

This states the purpose of the `Bluetooth` interface. While here, also added section for `Navigator.bluetooth` in the API page.

2024-03-05 05:08 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The [Permissions API](/en-US/docs/Web/API/Permissions_API) `bluetooth` permission can be used to test whether access to use a particular Bluetooth device is `granted`, `denied` or `prompt` (requires
This is true, but is only partial. There is a whole set of things you can pass to the query api as documented in https://webbluetoothcg.github.io/web-bluetooth/#permission-api-integration

2024-03-05 10:01 UTC, chrisdavidmills requested changes
Good work, @hamishwillee! I've got a few comments for you to trawl through, but nothing major to be concerned about.

2024-03-07 23:07 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/getavailability/index.md
> +In addition, a user can configure their browser to resolve with a particular value, which might not match whether or not a Bluetooth adapter is present, and this setting value be used if access is no
That's much better, but need to be clear that the permission is always used (according to spec) irrespective of the user configuration.

```suggestion
In addition, a user can configure their browser to return `false` from a `getAvailability()` call even if the browser does have an operational Bluetooth adapter, and vice versa. This setting value ignored if access is blocked by the permission.
```

> I'm assuming this setting is different on each browser that supports the API. Are you able to link to an example of what this looks like in Chrome?

Correct, the spec doesn't say how this must be implemented. Only Chrome has done so, so they are the only case. But no, I can't find how this is set in the current version of Chrome chrome://settings/privacy and I don't feel the need to add it at this point.

2024-03-07 23:16 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/getavailability/index.md
> +The {{JSxRef("Promise")}} will resolve with a value of `false` if access is disallowed by [`Permissions-Policy: bluetooth`](/en-US/docs/Web/HTTP/Headers/Permissions-Policy/bluetooth), if the user has
I've updated your change above to remove the addition of "powered" - the promise will resolve with `true` if the Bluetooth adapter is present but unpowered (in the absence of other conditions making it false).

My wording for the last sentence is actually "more correct", but I can see why you think it is overkill. I'll accept removal :-)

2024-03-07 23:19 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/index.md
> +    If this option is set, that is the value returned by this method.
Yes, I much prefer what you have done.

```suggestion
```

2024-03-07 23:20 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/requestdevice/index.md
>      - `filters[]`
Absolutely (though I have a sneaking liking for the approach).

```suggestion
    - `filters`
```

2024-03-07 23:23 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/requestdevice/index.md
> +      - : An array of `BluetoothScanFilters`.
In the spec the `BluetoothScanFilters` does not even exist. This has clearly been updated. This whole section needs to be updated. The values are the same as are taken by the permissiondescriptor. They should be updated at the same time. But I don't want to do that unless I can find someone in Chrome to find out what has been implemented, because it is hard to test that. I'm going to query on the spec.

For now

```suggestion
      - : An array of filter objects.
```

2024-03-07 23:25 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/requestdevice/index.md
> +        This filter consists of an array of `BluetoothServiceUUID`s, a `name` parameter, and a `namePrefix` parameter.
> Plus, the spec says they also contain arrays of manufacturer data and service data. Are you not putting this in because you are not sure if implementations are up to date?

Yes, as per https://github.com/mdn/content/pull/32533/files#r1516975135 I need a chrome developer. This update is about security, not fixing every detail. I will be finding said developer by first touching the spec.

2024-03-07 23:25 UTC, hamishwillee commented on files/en-us/web/api/bluetooth/requestdevice/index.md
> +    Or `options.filters` is `[]`.
```suggestion
```

2024-03-07 23:39 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The [Permissions API](/en-US/docs/Web/API/Permissions_API) `bluetooth` permission can be used to test whether access to use a particular Bluetooth device is `granted`, `denied` or `prompt` (requires
I know. The problem here is that it requires a lot of work on the Permissions API to expand on the permissionDescriptor "concept". This is the descriptor passed to https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query and is currently documented as a fixed object. In fact it is permission-specific object. 

I'm not sure right now the right way to do that, and since I don't know what is implemented I'm holding off sorting it out (or creating an issue). My temptation is to use a ... dictionary, but we don't love those here :-)

However on reflection, this says too little even "for now", so I will modify.

2024-03-08 00:35 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The returned {{jsxref("Promise")}} resolves to a `BluetoothPermissionResult`, an extended {{domxref("PermissionStatus")}} that returns an array of permitted devices in its `devices` property.
@chrisdavidmills OK, this section is updated. I have explained a bit more so that it's a bit more useful. More to be done, but I don't think it should block this.

2024-03-08 00:36 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The [Permissions API](/en-US/docs/Web/API/Permissions_API) `bluetooth` permission can be used to test whether access to use a particular Bluetooth device is `granted`, `denied` or `prompt` (requires
Done in link https://github.com/mdn/content/pull/32533#pullrequestreview-1923826350

2024-03-08 00:36 UTC, hamishwillee commented
THank you for the review. Should be good to look at again.

2024-03-08 09:15 UTC, chrisdavidmills approved these changes
Very nice work, @hamishwillee. I've left a couple more nitpicky morsels for you to chew on, but only very minor bits.

Approving so as not to hold you up.

2024-03-08 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/web_bluetooth_api/index.md
> +In order to use the feature the user must first grant explicit permission (they will not be prompted for access if it is not allowed for other reasons, such as being blocked by a `Permissions-Policy`
```suggestion
In order to use the feature the user must first grant explicit permission (they will not be prompted for access if it is not allowed for other reasons, such as being blocked by a Permissions Policy).
```

Or `Permissions-Policy` header, perhaps? But I think my suggestion is better. Really we're just talking about the general concept here.

2024-03-08 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/web_bluetooth_api/index.md
> +For example, the following code (modified from the example in the specification) returns the last Bluetooth device that was used, and for which the user has permission:
```suggestion
For example, the following code (modified from the example in the specification) returns the last Bluetooth device that was used, and for which the user granted permission:
```

?

The user grants permission for the browser to access these devices?

2024-03-08 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/web_bluetooth_api/index.md
> +Note that the `permissionDescriptor` options that can be passed to `query()` for the `bluetooth` permission are the same a the options that can be passed as arguments to {{DOMxRef("Bluetooth.requestD
```suggestion
Note that the options that can be passed to `query()` for the `bluetooth` permission are the same as the options that can be passed as arguments to {{DOMxRef("Bluetooth.requestDevice()")}}.
```

2024-03-08 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/web_bluetooth_api/index.md
> +Note that the `permissionDescriptor` options that can be passed to `query()` for the `bluetooth` permission are the same a the options that can be passed as arguments to {{DOMxRef("Bluetooth.requestD
I felt that mentioning `permissionDescriptor` might cause undue confusion — the reader might start looking for that identifying name, and then not find it, whereas if you just say "options", you just at the options object inside the `query()` call, and all is well. 

This is exactly what I did, anyway. I figured out what you meant pretty quickly, but that name caused a couple of seconds of extra cognitive dissonance.

2024-03-08 09:15 UTC, chrisdavidmills commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The returned {{jsxref("Promise")}} resolves to a `BluetoothPermissionResult`, an extended {{domxref("PermissionStatus")}} that returns an array of permitted devices in its `devices` property.
```suggestion
The returned {{jsxref("Promise")}} resolves to a `BluetoothPermissionResult`, an extended {{domxref("PermissionStatus")}} object that returns an array of permitted devices in its `devices` property.
```

2024-03-11 01:02 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +Note that the `permissionDescriptor` options that can be passed to `query()` for the `bluetooth` permission are the same a the options that can be passed as arguments to {{DOMxRef("Bluetooth.requestD
Agreed thanks. Note that I'm going to probably have to comment out much of this - its in the spec but not yet in Chrome (https://github.com/WebBluetoothCG/web-bluetooth/issues/620). I'll accept this for now though!

2024-03-11 01:43 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +The returned {{jsxref("Promise")}} resolves to a `BluetoothPermissionResult`, an extended {{domxref("PermissionStatus")}} that returns an array of permitted devices in its `devices` property.
This isn't implemented (yet) and there is no tracking of it. I'll accept this and comment it out for when this gets implemented.

2024-03-11 01:45 UTC, hamishwillee commented on files/en-us/web/api/web_bluetooth_api/index.md
> +For example, the following code (modified from the example in the specification) returns the last Bluetooth device that was used, and for which the user has permission:
Yes, access devices is granted individually, as well as based on stuff like the permissions-policy. But this bit isn't implemented, so merging and then will get commented out.

2024-03-11 02:27 UTC, hamishwillee commented
Thanks very much for the review @chrisdavidmills . I've accepted your changes. For query() I have hidden the updated text because this has not been implemented. Last part is to update the options to `requestDevice()`  but I'll do that as a follow on PR.

2024-03-11 02:28 UTC, merged

2024-03-11 08:53 UTC, chrisdavidmills commented
> Thanks very much for the review @chrisdavidmills . I've accepted your changes. For query() I have hidden the updated text because this has not been implemented. Last part is to update the options to `requestDevice()` but I'll do that as a follow on PR.

Nice one, all sounds good @hamishwillee!