Update WebRTC media source stats
mdn/content pull request #32538
Opened 2024-03-04 06:15 UTC by hamishwillee

This updates docs for  `RTCAudioSourceStats`, and adds docs for `RTCVideoSourceStats` - both of which are `type=media-sourc` objects you can get by iterating a [`RTCStatsReport`](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport).

This is part of the ongoing work to finished RTC stats, which was started in https://github.com/mdn/content/pull/27028

The changes to Audio source are mostly about API docs consistency. 

This has an associated BCD update in https://github.com/mdn/browser-compat-data/pull/22510

2024-03-05 01:19 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +- {{domxref("RTCAudioSourceStats.audioLevel", "audioLevel")}} {{Experimental_Inline}}{{optional_inline}}
The ones that are not marked `required` in the IDL.

2024-03-15 17:53 UTC, wbamberg requested changes

2024-03-15 17:53 UTC, wbamberg commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +  - : A positive number that represents the height, in pixels, of the last frame originating from this source.
Also if we say "positive" here should we say it for the others? Or maybe it isn't worth saying, too obvious?

2024-03-15 17:53 UTC, wbamberg commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +// framesPerSecond does not exist in the first second
This isn't accurate, `?.` here protects you against `videoSourceStats` being undefined or null, but not `framesPerSecond`: that is, it applies to the left hand side. It's still a good thing to do here because `videoSourceStats` might be null, and this avoids an error in that situation.

2024-03-15 17:53 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +  - : A string indicating the kind of media source. For an `RTCAudioSourceStats` this will always be `audio`.
This seems less helpful than what you had before. I never like it when a thing is called "X" and the docs say "Represents the X".

2024-03-18 03:02 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +The **`RTCAudioSourceStats`** dictionary of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides statistics information about an audio track ({{domxref("MediaStreamTrack")}}) that is attached to
This was because the `media-source` "type" is shared by both audio and video objects, and this is how the items are sorted in BCD. I added a `spec-urls` frontmatter for video and audio to fix this.

2024-03-18 03:07 UTC, hamishwillee commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +  - : A string indicating the kind of media source. For an `RTCAudioSourceStats` this will always be `audio`.
I'm a bit ambivalent - I guess it is somewhat useful to know the other values  this might return, even at this level. I'll revert.


```suggestion
  - : A string indicating whether this object represents stats for a video source or a media source. For an `RTCAudioSourceStats` this will always be `audio`.
```

2024-03-18 03:08 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +  - : A string indicating the kind of media source. For an `RTCVideoSourceStats` this will always be `video`.
```suggestion
  - : A string indicating whether this object represents stats for a video source or a media source. For an `RTCVideoSourceStats` this will always be `video`.
```

2024-03-18 03:22 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/frames/index.md
> +const frames = videoSourceStats.frames;
Thanks. Fixed with optional chaining.

2024-03-18 03:32 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +The **`framesPerSecond`** property of the {{domxref("RTCVideoSourceStats")}} dictionary indicates the number of frames from this video source in the last second.
A `RTCVideoSourceStats` represents stats for a video media track attached to a sender. The spec says "originating from". I suspect "sent" and "generated by"  are effectively synonyms in this case. But how about we use the spec words, so we can't be wrong.

```suggestion
The **`framesPerSecond`** property of the {{domxref("RTCVideoSourceStats")}} dictionary indicates the number of frames originating from this video source in the last second.
```

2024-03-18 03:34 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/frames/index.md
> +The **`frames`** property of the {{domxref("RTCVideoSourceStats")}} dictionary indicates the total number of frames sent from this video source over its lifetime.
```suggestion
The **`frames`** property of the {{domxref("RTCVideoSourceStats")}} dictionary indicates the total number of frames originating from this video source over its lifetime.
```

2024-03-18 03:36 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/frames/index.md
> +A number indicating the total number of frames from this source.
```suggestion
A number indicating the total number of frames originating from this source.
```

2024-03-18 03:39 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +A number indicating the frames from this source in the last second.
```suggestion
A number indicating the frames originating from this source in the last second.
```

2024-03-18 04:03 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +// framesPerSecond does not exist in the first second
@wbamberg Are you sure? I mean you're right that it protects the LHS (`videoSourceStats`) and not `framesPerSecond` but I don't think it matters. 
- If `videoSourceStats` does not exist then the result short circuits to undefined (`framesPerSecond` also doesn't exist of course).
- If `videoSourceStats` does exist but `framesPerSecond` does not then the result is `undefined` - which is what we want right?

2024-03-18 04:04 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/height/index.md
> +// 'height' does not exist until frames are being produced.
As above https://github.com/mdn/content/pull/32538/files#r1527778533

2024-03-18 04:08 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +  - : A positive number that represents the height, in pixels, of the last frame originating from this source.
> Do you think "most recently sent" might be clearer than "last"? Also in width.

Only if we were to use "sent". But if we're using the spec words "originating from" we can't. So no. I'm going to make it originating everywhere here.

2024-03-18 04:11 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +  - : A positive number that represents the height, in pixels, of the last frame originating from this source.
> Also if we say "positive" here should we say it for the others? Or maybe it isn't worth saying, too obvious?

Yes - we should say "positive" where they have to be.

In this interface it isn't really necessary but in some of the RTC stats the values can be negative because of the way things are calculated. So while I dislike using positive it is actually kind of safer.

2024-03-18 04:13 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +    This property is not defined on this stats object until after the first frame has been produced.
```suggestion
- {{domxref("RTCVideoSourceStats.frames", "frames")}} {{optional_inline}}
  - : A positive number that indicates the total number of frames originating from this video source.
- {{domxref("RTCVideoSourceStats.framesPerSecond", "framesPerSecond")}} {{optional_inline}}
  - : A positive number that represents the number of frames originating from this video source in the last second.
    This property is not defined on this stats object for the first second of its existence.
- {{domxref("RTCVideoSourceStats.height", "height")}} {{optional_inline}}
  - : A number that represents the height, in pixels, of the last frame originating from this source.
    This property is not defined on this stats object until after the first frame has been produced.
- {{domxref("RTCVideoSourceStats.width", "width")}} {{optional_inline}}
  - : A number that represents the width, in pixels, of the most recent frame originating from this source.
    This property is not defined on this stats object until after the first frame has been produced.
```

2024-03-18 04:17 UTC, hamishwillee commented
@wbamberg Thank you for the review. I think I've fixed this except for the question on optional chaining - please see my response here that I don't think it matters https://github.com/mdn/content/pull/32538/#discussion_r1527778533

(If I'm wrong, how would you address this?)

2024-03-18 05:19 UTC, wbamberg commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +// framesPerSecond does not exist in the first second
Yes, I agree with all that, I'm just saying the comment is wrong:

> // Note, test is conditional because
> // framesPerSecond does not exist in the first second

The test is conditional because `videoSourceStats` might be `null`. So for instance if the code did this:

```js
// where sender is an RTCRtpSender
const stats = await sender.getStats();
let videoSourceStats = null;

stats.forEach((report) => {
  if (report.type === "media-source" && report.kind==="video") {
    videoSourceStats = report;
   const fps = videoSourceStats.framesPerSecond;
    break;
  }
});
```

...then you wouldn't need `?.` because you know `videoSourceStats` is not null. Of course `framesPerSecond` can still be undefined, but that doesn't matter, as you say, and it's not affected by `?.`.

At least, such is my understanding.

2024-03-18 05:24 UTC, wbamberg commented
> @wbamberg Thank you for the review. I think I've fixed this except for the question on optional chaining - please see my response here that I don't think it matters #32538
> 
> (If I'm wrong, how would you address this?)

If I'm right :) I'd address it with something like:

```
// Note, test is conditional in case the stats object
// does not include video source stats
```

2024-03-18 05:28 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/framespersecond/index.md
> +// framesPerSecond does not exist in the first second
That makes sense. Thanks for clarifying and providing some words.

```suggestion
// Note, test is conditional in case the stats object
// does not include video source stats
```

2024-03-18 05:28 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/height/index.md
> +// 'height' does not exist until frames are being produced.
```suggestion
// Note, test is conditional in case the stats object
// does not include video source stats
```

2024-03-18 05:28 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/width/index.md
> +// 'width' does not exist until frames are being produced.
```suggestion
// Note, test is conditional in case the stats object
// does not include video source stats
```

2024-03-18 05:30 UTC, hamishwillee commented
Thanks very much. I must warn you, this is an "easy one" compared to the remote inbound stats :-0. There you have to get your head around who is reporting what.

2024-03-18 19:16 UTC, wbamberg requested changes

2024-03-18 19:16 UTC, wbamberg commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +const height = videoSourceStats?.height;
```suggestion
// videoSourceStats will be null if the report did not include video source stats
const frames = videoSourceStats?.frames;
const fps = videoSourceStats?.framesPerSecond;
const width = videoSourceStats?.width;
const height = videoSourceStats?.height;
```

(sorry I must have missed this first time round)

2024-03-18 19:16 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +The **`RTCAudioSourceStats`** dictionary of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides statistics information about an audio track ({{domxref("MediaStreamTrack")}}) that is attached to
Do you also need that for the individual members? And this looks like a systemic issue, e.g. https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnectionStats#specifications

2024-03-18 23:59 UTC, hamishwillee commented on files/en-us/web/api/rtcvideosourcestats/index.md
> +const height = videoSourceStats?.height;
Nyaa, that's my fault/brainfade. The `frames` is required if `videoSourceStats` is populated, and that was all I was thinking here. Thanks.

2024-03-19 10:14 UTC, bsmth commented
Removing myself from review as Will's got it covered! 😉

2024-03-22 00:39 UTC, hamishwillee commented
Ready for you to review when ready @wbamberg - the systemic question, is addressed in https://github.com/mdn/content/pull/32538#discussion_r1529492592

2024-03-22 23:35 UTC, wbamberg commented on files/en-us/web/api/rtcaudiosourcestats/index.md
> +The **`RTCAudioSourceStats`** dictionary of the [WebRTC API](/en-US/docs/Web/API/WebRTC_API) provides statistics information about an audio track ({{domxref("MediaStreamTrack")}}) that is attached to
Yeah I agree that setting spec-url is easier. I think it is wrong to link to the enum type but don't care much, since we don't AFAIK have particularly precise policies for what to link to in spec URLs.

2024-03-22 23:36 UTC, wbamberg approved these changes
👍 thank you Hamish!

2024-03-22 23:36 UTC, merged