Add criticalCHRestart docs
mdn/content pull request #32555
Opened 2024-03-05 11:22 UTC by tunetheweb

### Description

Add criticalCHRestart docs

### Motivation

Was added to BCD in https://github.com/mdn/browser-compat-data/pull/20520 but without MDN page so added here.

### Additional details

Includes in Chrome 116:
- https://polymer10-samples-dot-cr-status.appspot.com/feature/5140317616996352
- https://developer.chrome.com/blog/chrome-116-beta

### Related issues and pull requests

2024-03-05 14:40 UTC, arichiv reviewed
Thanks for this! Just one note

2024-03-05 14:40 UTC, arichiv commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +Website can indicate that a particular Client Hint is critical to the page by including it in a {{HTTPHeader("Critical-CH")}} HTTP response header. Doing so will trigger a connection restart if the h
The hint must also be listed in the Accept-CH response header, otherwise it's ignored. Critical-CH items can also be ignored if the hint isn't returnable by the browser.

2024-03-05 14:50 UTC, tunetheweb commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +Website can indicate that a particular Client Hint is critical to the page by including it in a {{HTTPHeader("Critical-CH")}} HTTP response header. Doing so will trigger a connection restart if the h
WDYT about this?:

```suggestion
A website can indicate that a particular Client Hint is critical to the page by including it in a {{HTTPHeader("Critical-CH")}} HTTP response header (as well as the {{HTTPHeader("Accept-CH")}} HTTP request header which is needed for all client hints whether critical or not). Doing so will trigger a connection restart if the hint listed in the `Critical-CH` HTTP response header could be (but wasn't) included in the HTTP request initially sent. This requires the browser to support that client hint, otherwise it is ignored and no connection restart occurs.
```

2024-03-05 18:48 UTC, arichiv commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +Website can indicate that a particular Client Hint is critical to the page by including it in a {{HTTPHeader("Critical-CH")}} HTTP response header. Doing so will trigger a connection restart if the h
SGTM

2024-03-14 03:06 UTC, wbamberg requested changes
Thank you @tunetheweb !

2024-03-14 03:06 UTC, wbamberg commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +A {{domxref("DOMHighResTimeStamp")}} representing the time after navigation {{domxref("PerformanceEntry.startTime")}} when the connection restart occured in milliseconds.
```suggestion
A {{domxref("DOMHighResTimeStamp")}} representing the time, in milliseconds, after navigation {{domxref("PerformanceEntry.startTime")}} when the connection restart occurred.
```

(we could omit "in milliseconds" because it's implicit in the definition of `DOMHighResTimeStamp`, but probably worth keeping)

Might it be clearer to say "representing the number of milliseconds elapsed since {{domxref("PerformanceEntry.startTime")}}"? Is that even correct?

2024-03-14 03:06 UTC, wbamberg commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +let restartTime =
```suggestion
const restartTime =
```

2024-03-14 03:06 UTC, wbamberg commented on files/en-us/web/api/performancenavigationtiming/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} representing the time at which the connection restart occured due to {{HTTPHeader("Critical-CH")}} HTTP response header mismatch.
```suggestion
  - : A {{domxref("DOMHighResTimeStamp")}} representing the time at which the connection restart occurred due to {{HTTPHeader("Critical-CH")}} HTTP response header mismatch.
```

2024-03-14 07:27 UTC, tunetheweb commented on files/en-us/web/api/performancenavigationtiming/criticalchrestart/index.md
> +A {{domxref("DOMHighResTimeStamp")}} representing the time after navigation {{domxref("PerformanceEntry.startTime")}} when the connection restart occured in milliseconds.
```suggestion
A {{domxref("DOMHighResTimeStamp")}} representing the number of milliseconds elapsed since {{domxref("PerformanceEntry.startTime")}} when the connection restart occurred in milliseconds.
```

2024-03-14 15:09 UTC, wbamberg approved these changes
👍 thank you @tunetheweb !

2024-03-14 15:09 UTC, merged