New glossary: Color space
mdn/content pull request #32571
Opened 2024-03-06 05:35 UTC by estelle

new glossary entry for a term we use but have never really defined

this is a glossary, not a guide, so is not expected to be in depth

2024-03-08 12:33 UTC, chrisdavidmills requested changes
@estelle I really enjoyed reading this — very informative. I've left a bunch of comments, but they are mainly small language tweaks. Shouldn't take too long to trawl through.

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
```suggestion
There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_ (`a98-rgb`) are different. There are many ways to describe the RGB components of a color. In {{Glossary("CSS")}} they can be represented as a single 24-bit integer in hexadecimal notation (for example, `#add8e6` is light blue), or in [`rgb()`](/en-US/docs/Web/CSS/color_value/rgb) functional notation as three separate numbers between 0 and 255 (for example, `rgb(46 139.5 87)`).

CSS `<color>` values in the sRGB color spaces include:

- {{cssxref("hex-color")}}
- {{cssxref("named-color")}}
- {{cssxref("color_value/rgb", "rgb()")}}
- {{cssxref("color_value/hsl", "hsl()")}} (hue, saturation, lightness)
- {{cssxref("color_value/hwb", "hwb()")}} (hue, whiteness, blackness).
- The `srgb`, `srgb-linear`, `a98-rgb`, and `prophoto-rgb` color spaces for the [`color()`](/en-US/docs/Web/CSS/color_value/color) function.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +The HSV (hue, saturation, and value) color space, and its synonym HSB (hue, saturation, and brightness), are represented in CSS as [`hwb()`](/en-US/docs/Web/CSS/color_value/hwb). Named colors are sim
Some of this stuff sounds like it is repeating the information above. Maybe include this extra info in the bullets I've suggested above, so it doesn't seem so repetitious? The bit about `currentColor` should definitely be kept.

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
The list of `color()` color spaces here is different from the definition list you include below. Maybe include them all here, and then before the definition list, include a lead-in sentence that says something like "The below list provides some more information about each of the predefined RGB color spaces:"

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : The predefined linear-light sRGB color space, `srgb-linear`, is the same as `srgb` except that the transfer function is linear-light with no gamma-encoding. The `srgb-linear` color space accept
```suggestion
  - : The predefined linear-light sRGB color space, `srgb-linear`, is the same as `srgb` except that the transfer function is linear-light with no gamma-encoding. The `srgb-linear` color space accepts the three `r`, `g`, and `b` values as numeric parameters, with in-gamut colors ranging from `0` to `1`. The whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : The sRGB color space, or "Standard RGB", is the standard RGB (red, green, blue) color space. It was created to be used on monitors, printers, and the Web. It is the most widely used color space
```suggestion
  - : The sRGB color space, or "Standard RGB", is the standard RGB (red, green, blue) color space. It was created to be used on monitors, printers, and the Web. It is the most widely used color space and is supported by most operating systems, software programs, monitors, and printers. sRGB is based on `r`, `g`, and `b`, with in-gamut values ranging from `0` to `1`. The whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Defined by Apple, the **Display P3** color space combines the DCI-P3 color gamut, the D65 white point, and sRGB gamma curve. It is a wide gamut space typical of current wide-gamut monitors, ena
```suggestion
  - : Defined by Apple, the **Display P3** color space combines the DCI-P3 color gamut, the D65 white point, and sRGB gamma curve. It is a wide gamut space typical of current wide-gamut monitors, enabling more vibrant greens and reds than the sRGB color gamut. The `display-p3` is based on `r`, `g`, and `b`, with in-gamut values ranging from `0` to `1`. The whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : The `a98-rgb`, is the Adobe® 1998 RGB color space designed to represent all the CMYK colors as RGB. About 50% of the visible colors specified by the CIELab color space can be achieved, encompas
```suggestion
  - : `a98-rgb` is the Adobe® 1998 RGB color space designed to represent all the CMYK colors as RGB. About 50% of the visible colors specified by the CIELab color space can be achieved, encompassing more cyan-green hues than other RGB color spaces. In-gamut `r`, `g`, and `b` values range from `0` to `1`. The transfer curve is a gamma function, close to but not exactly 1/2.2. The whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : `rec2020` is a broadcast industry standard for ultra high definition, 4k and 8k televisions. The ultra-wide gamut space is capable of representing almost all visible real-world colors, beyond t
```suggestion
  - : `rec2020` is a broadcast industry standard for ultra-high definition 4k and 8k televisions. The ultra-wide gamut space is capable of representing almost all visible real-world colors, beyond the capabilities of most current displays. Coverage is expected to increase over time as displays improve. In-gamut `r`, `g`, and `b` values range from `0` to `1`. The whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +Additional cylindrical sRGB spaces that are not in the CSS specification include: `HSI` (hue, saturation, and intensity), `Okhsv`, `Okhsl`, `HSLuv`, `HPLuv` and `Cubehelix`.
Feels like this should be a note.

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +The CIELAB color space, also referred to as L*a*b*, represents the entire range of color that humans can see. It expresses color as three values: L* for perceptual lightness and a* and b* for the fou
```suggestion
The CIELAB color space, also referred to as L*a*b*, represents the entire range of color that humans can see. It expresses color as three values: L* for perceptual lightness and a* and b* for the four unique colors of human vision: red, green, blue, and yellow.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +CIELab color functions include {{CSSXref("color_value/lab", "lab()")}} (lightness, a-axis, b-axis) and {{CSSXref("color_value/lch", "lch()")}} (lightness, chroma, hue) as well as {{CSSXref("color_val
```suggestion
CIELab color functions include {{CSSXref("color_value/lab", "lab()")}} (lightness, a-axis, b-axis) and {{CSSXref("color_value/lch", "lch()")}} (lightness, chroma, hue) as well as {{CSSXref("color_value/oklab", "oklab()")}} and {{CSSXref("color_value/oklch", "oklch()")}}. The lightness values are the same, but `lch()` is a polar, cylindrical coordinate system using polar coordinates `C` (chroma) and `H` (hue) rather than axes. Note the hue and lightness here are different from the same-named values in `hsl()` or other sRGB color spaces.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +CIE Lab color spaces, including LCH, Oklab and Oklch, are device-independent color spaces.
```suggestion
CIE Lab color spaces, including LCH, Oklab, and Oklch, are device-independent color spaces.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Expresses color as `L` in a range from `0` to `100`, and both `a` and `b` with a range from `-125` to `125`. The `a` and `b` axes are not bound by these range values which are references in def
```suggestion
  - : Expresses color as `L` in a range from `0` to `100`, and `a` and `b` with a range from `-125` to `125`. The `a` and `b` axes are not bound by these range values, which are references in defining percentage inputs and outputs in relation to the `Display P3` color space. The whitepoint is D50.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  -: This color space is the same as `lab-d50`, except the whitepoint is D65.
```suggestion
  - : This color space is the same as `lab-d50`, except that the whitepoint is D65.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Similar to `lab-d65`, but the range for `L` is `0` to `1`, and both `a` and `b` range from `-0.4` to `0.4`.
```suggestion
  - : Similar to `lab-d65`, but the range for `L` is `0` to `1`, and `a` and `b` range from `-0.4` to `0.4`.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +While combinations of red, green, and blue do work well for representing colors on screen, sRGB doesn't directly correspond to how humans perceive color.Created by the International Commission on Ill
```suggestion
While combinations of red, green, and blue work well for representing colors on screen, sRGB doesn't directly correspond to how humans perceive color. Created by the International Commission on Illumination (CIE) in 1931, the XYZ color spaces are the first defined quantitative links between distributions of wavelengths in the electromagnetic visible spectrum and perceived colors in human vision.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. CIE XYZs, three parameters corresponding to levels of stimuli
```suggestion
People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimuli of the three kinds of cone cells which, in principle, describe every color. The CIE XYZ color space, with its tri-stimulus values, encompasses all visible colors.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : `xyz-d50` is the same as `xyz-d65` except it uses `d50` as a white point.
```suggestion
  - : `xyz-d50` is the same as `xyz-d65` except it uses `d50` as the whitepoint.
```

2024-03-08 12:33 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : The `xyz` identifier is a synonym for the `xyz-d65` color space. The axes are not limited to a `0` to `1` range as the color space is not bound to the range and these values are only used as re
```suggestion
  - : The `xyz` identifier is a synonym for the `xyz-d65` color space. The axes are not limited to a `0` to `1` range as the color space is not bound to this range; these values are only used as reference points in defining percentage inputs and outputs. The whitepoint is D65.
```

2024-03-11 04:31 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +Additional cylindrical sRGB spaces that are not in the CSS specification include: `HSI` (hue, saturation, and intensity), `Okhsv`, `Okhsl`, `HSLuv`, `HPLuv` and `Cubehelix`.
```suggestion
> **Note:** Additional cylindrical sRGB spaces that are not in the CSS specification include: `HSI` (hue, saturation, and intensity), `Okhsv`, `Okhsl`, `HSLuv`, `HPLuv` and `Cubehelix`.
```

2024-03-11 04:34 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
i didn't create a list here because they are mostly listed below. This list is the enumerated list for the color function, but there are more color spaces than that limited list.

2024-03-11 04:34 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
```suggestion
There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_ (`a98-rgb`) are different. There are many ways to describe the RGB components of a color. In {{Glossary("CSS")}} they can be represented as a single 24-bit integer in hexadecimal notation (for example, `#add8e6` is light blue), or in functional notation, [`rgb()`](/en-US/docs/Web/CSS/color_value/rgb) as three separate numbers between 0 and 255 (for example, `rgb(46 139.5 87)`).

CSS `<color>` values in the sRGB color spaces include {{cssxref("hex-color")}}, {{cssxref("named-color")}}, {{cssxref("color_value/rgb", "rgb()")}}, {{cssxref("color_value/hsl", "hsl()")}} (hue, saturation, lightness), {{cssxref("color_value/hwb", "hwb()")}} (hue, whiteness, blackness). There are also the `srgb`, `srgb-linear`, `a98-rgb`, and `prophoto-rgb` color spaces for the [`color()`](/en-US/docs/Web/CSS/color_value/color) function.
```

2024-03-11 06:17 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +Color spaces are either rectangular or polar. Rectangular color spaces include `srgb`, `srgb-linear`, `display-p3`, `a98-rgb`, `prophoto-rgb`, `rec2020`, `lab`, `oklab`, `xyz-d50`, and `xyz-d65` (or
i added a link to eric portis's article which is really good

2024-03-11 06:22 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +The HSV (hue, saturation, and value) color space, and its synonym HSB (hue, saturation, and brightness), are represented in CSS as [`hwb()`](/en-US/docs/Web/CSS/color_value/hwb). Named colors are sim
the stuff above is the list of values that can be used in the `color()` function. I wanted to enumerate them in case someone is looking (there's most likely to come to this page from that page). While important for our readers, that list doesn't even include LAB values. I could get rid of the entire section `## Named color spaces`, but i think it's better to keep that even though it seems redundant to the part of the page we have to keep (these sections)

2024-03-11 09:50 UTC, chrisdavidmills approved these changes
Great stuff, thanks @estelle! I've left a few more comments, but mostly just very small language corrections.

Approving so as not to hold you up.

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +RGB is a color model that represents colors as mixtures of three underlying components - red, green, and blue color channels - that create various hues when combined. sRGB, or "Standard RGB", is the
```suggestion
RGB is a color model that represents colors as mixtures of three underlying components — red, green, and blue color channels — that create various hues when combined. sRGB, or "Standard RGB", is the underlying color space for {{Glossary("RGB")}} colors. sRGB is intended as a common color space for the creation of images for viewing on the Internet and World Wide Web (WWW). sRGB is primarily used for displaying colors on computer screens, including laptops and smartphones.
```

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
```suggestion
There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_ (`a98-rgb`) are different. There are many ways to describe the RGB components of a color. In {{Glossary("CSS")}} they can be represented as a single 24-bit integer in hexadecimal notation (for example, `#add8e6` is light blue), or in [`rgb()`](/en-US/docs/Web/CSS/color_value/rgb) functional notation as three separate numbers between 0 and 255 (for example, `rgb(46 139.5 87)`).
```

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +There are several RGB color spaces, like the _Adobe RGB_ color space, that can represent a wider {{glossary("gamut")}} of color than the _sRGB_ color space. The coordinates in _sRGB_ and _Adobe RGB_
I still felt this sentence seemed a bit awkwardly-phrased.

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Defined by Apple, the **Display P3** color space combines the DCI-P3 color gamut, the D65 white point, and sRGB gamma curve. It is a wide gamut space typical of current wide-gamut monitors, ena
```suggestion
  - : Defined by Apple, the **Display P3** color space combines the DCI-P3 color gamut, the D65 whitepoint, and sRGB gamma curve. It is a wide gamut space typical of current wide-gamut monitors, enabling more vibrant greens and reds than the sRGB color gamut. The `display-p3` is based on `r`, `g`, and `b`, with in-gamut values ranging from `0` to `1`. The whitepoint is D65.
```

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Developed by Kodak, the `prophoto-rgb` color space can represent all the colors likely to occur in nature and about 90% of CIElab colors. In-gamut `r`, `g`, and `b` values range from `0` to `1`
```suggestion
  - : Developed by Kodak, the `prophoto-rgb` color space can represent all the colors likely to occur in nature and about 90% of CIElab colors. In-gamut `r`, `g`, and `b` values range from `0` to `1`. The transfer curve is a gamma function, with a value of 1/1.8, and a small linear portion near black. The whitepoint is D50, the same one used by CIE Lab.
```

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +> **Note:** Additional cylindrical sRGB spaces that are not in the CSS specification include: `HSI` (hue, saturation, and intensity), `Okhsv`, `Okhsl`, `HSLuv`, `HPLuv` and `Cubehelix`.
```suggestion
> **Note:** Additional cylindrical sRGB spaces that are not in the CSS specification include: `HSI` (hue, saturation, and intensity), `Okhsv`, `Okhsl`, `HSLuv`, `HPLuv`, and `Cubehelix`.
```

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +  - : Developed by Kodak, the `prophoto-rgb` color space can represent all the colors likely to occur in nature and about 90% of CIElab colors. In-gamut `r`, `g`, and `b` values range from `0` to `1`
I also just thought that maybe you could link to a definition of white point somewhere, as it isn't explained anywhere. This would do: https://en.wikipedia.org/wiki/White_point.

Also, I've noticed that on the rest of the internet "white point" seems to be the standard way to write it, not "whitepoint"! So, maybe do a search and replace?

2024-03-11 09:50 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +Lab is rectangular coordinate system, with a central lightness `L` axis. Positive values along the `a` axis are a purplish red while negative values are the complement: green. Positive values along t
```suggestion
Lab is a rectangular coordinate system, with a central lightness `L` axis. Positive values along the `a` axis are a purplish red while negative values are the complement: green. Positive values along the `b` axis are yellow and negative are blue/violet. Desaturated colors have small values for `a` and `b` with greater absolute values being more saturated.
```

2024-03-11 18:14 UTC, merged