Fix misleading information regarding default value of `lang` attribute
mdn/content pull request #32604
Opened 2024-03-08 00:02 UTC by silverwind

### Description

Previously the word "unknown" was highlighed as code tag, which was misleading. The word appears in [old W3C specs](https://www.w3.org/TR/html401/struct/dirlang.html#language-info) as literal text only and I'd say it was never meant to be interpreted as string.

> The default value of this attribute is unknown

The [WHATWG spec](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes) gives a better description:

> Its value must be a valid BCP 47 language tag, or the empty string. Setting the attribute to the empty string indicates that the primary language is unknown.

### Motivation

I was mislead believing `"unknown"` was a valid value.

2024-03-08 00:03 UTC, silverwind commented on files/en-us/web/html/global_attributes/lang/index.md
> +> **Note:** The default value of `lang` is the empty string. It is recommended to always specify this attribute with the appropriate value.
```suggestion
> **Note:** The default value of `lang` is the empty string which means the language is unknown. It is recommended to always specify this attribute with the appropriate value.
```

2024-03-08 00:05 UTC, silverwind commented on files/en-us/web/html/global_attributes/lang/index.md
> +> **Note:** The default value of `lang` is the empty string which means the language is unknown. It is recommended to always specify this attribute with the appropriate value.
```suggestion
> **Note:** The default value of `lang` is the empty string which means the language is unknown, therefore it is recommended to always specify this attribute with the appropriate value.
```

2024-03-08 14:16 UTC, dipikabh requested changes

2024-03-08 14:16 UTC, dipikabh commented on files/en-us/web/html/global_attributes/lang/index.md
> +> **Note:** The default value of `lang` is the empty string which means the language is unknown, therefore it is recommended to always specify this attribute with the appropriate value.
@silverwind what do you think about this with a slight tweak:
```suggestion
> **Note:** The default value of `lang` is the empty string, which means that the language is unknown. Therefore, it is recommended to always specify an appropriate value for this attribute.
```

2024-03-08 14:28 UTC, silverwind commented on files/en-us/web/html/global_attributes/lang/index.md
> +> **Note:** The default value of `lang` is the empty string which means the language is unknown, therefore it is recommended to always specify this attribute with the appropriate value.
Sounds better, thanks.

2024-03-11 12:58 UTC, dipikabh approved these changes
Thanks, @silverwind! 👍

2024-03-11 12:58 UTC, merged