Refactor docs to separate WebGL v1 and v2 content.
mdn/content pull request #32613
Opened 2024-03-08 13:20 UTC by tsnee

### Description

WebGLRenderingContext and WebGL2RenderingContext have overloaded versions of the bufferData and bufferSubData functions. Before, all were documented under files/en-us/web/api/webglrenderingcontext. After a discussion on [a previous PR](https://github.com/mdn/content/pull/32598) it was decided to split them up.

### Motivation

As things stand today, webgl2renderingcontext/index.md contains broken links. This PR creates the files required to resolve those links.

### Related issues and pull requests

Relates to https://github.com/mdn/content/pull/32598

2024-03-09 01:07 UTC, wbamberg requested changes
Thank you @tsnee ! Like I say, I'm no expert on WebGL so I'd appreciate your checking my comments, which are just based on a read of the spec syntax.

2024-03-09 01:07 UTC, wbamberg commented on files/en-us/web/api/webglrenderingcontext/bufferdata/index.md
>  bufferData(target, usage)
It looks to me like either `size` or `srcData` must be provided, so this version should be omitted.

2024-03-09 01:07 UTC, wbamberg commented on files/en-us/web/api/webglrenderingcontext/bufferdata/index.md
>  ### Parameters
I can't comment below but maybe mark `size` and `srcData` optional and say one of them must be provided?

2024-03-09 01:07 UTC, wbamberg commented on files/en-us/web/api/webglrenderingcontext/buffersubdata/index.md
>  // WebGL1
```suggestion
```

2024-03-09 01:07 UTC, wbamberg commented on files/en-us/web/api/webglrenderingcontext/buffersubdata/index.md
>  bufferSubData(target, offset)
looks like this option is not valid, from the spec?

```
undefined bufferSubData(GLenum target, GLintptr offset, AllowSharedBufferSource data);
```

(also it's called `data` not `srcData` in the spec, not sure this is worth fixing.)

2024-03-09 13:48 UTC, tsnee commented
> Like I say, I'm no expert on WebGL so I'd appreciate your checking my comments, which are just based on a read of the spec syntax.

I am not either. Your comments look correct to me, but I don't know how to prove they are right. I am only just beginning to work with WebGL. I will see if I can write some sample code to find out what works and what does not. However I would feel a lot more confident if a subject matter expert could weigh in.

2024-03-10 09:46 UTC, tsnee commented on files/en-us/web/api/webgl2renderingcontext/bufferdata/index.md
> +browser-compat: api.WebGL2RenderingContext.bufferData
Thanks!

2024-03-10 09:48 UTC, davesmith00000 commented
Hi! @tsnee and I have been discussing some related work in the background for a ticket I raised (to do with WebGL2) on another repo, that has resulted in this valiant effort.
I wouldn't call myself a subject matter expert, and would happily bow to a higher authority if one showed up, but I have spent a good amount of time with the Kronos docs and translating them to usable interfaces.
All that said, @wbamberg's comments all look correct and reasonable to me, based on the Kronos docs links provided.
Hope that helps, great work all.

2024-03-10 10:14 UTC, tsnee commented on files/en-us/web/api/webgl2renderingcontext/bufferdata/index.md
> +bufferData(target, srcData, usage, srcOffset, length)
Yes

2024-03-10 10:16 UTC, tsnee commented on files/en-us/web/api/webgl2renderingcontext/buffersubdata/index.md
> +bufferSubData(target, dstByteOffset, srcData, srcOffset, length)
Yes

2024-03-10 10:16 UTC, tsnee commented on files/en-us/web/api/webgl2renderingcontext/buffersubdata/index.md
> +  - : A {{domxref("WebGL_API/Types", "GLuint")}} defaulting to 0.
I added a little more detail.

2024-03-10 10:17 UTC, tsnee commented on files/en-us/web/api/webglrenderingcontext/bufferdata/index.md
> -bufferData(target, srcData, usage, srcOffset, length)
OK

2024-03-10 10:17 UTC, tsnee commented on files/en-us/web/api/webglrenderingcontext/bufferdata/index.md
>  bufferData(target, usage)
Yes

2024-03-10 10:17 UTC, tsnee commented on files/en-us/web/api/webglrenderingcontext/bufferdata/index.md
>  ### Parameters
I accepted your suggestion.

2024-03-13 17:38 UTC, wbamberg requested changes
Thanks for the update @tsnee and for the review @davesmith00000 !

The only thing left here is to delete lines 17 and 18 from https://github.com/mdn/content/pull/32613/files#diff-f3fa71864e6aba88eba045c4a46156dcd01acefa12cdef0e0d1a547168ebc1c8

```
// WebGL1
bufferData(target, usage)
```

.per the comments at https://github.com/mdn/content/pull/32613/files#r1518443366 and https://github.com/mdn/content/pull/32613/files#r1518441714.

After that we should be good I think.

2024-03-13 19:15 UTC, tsnee commented
Oops, I thought I had already done that. I'm glad you double checked.

2024-03-13 20:09 UTC, wbamberg approved these changes
🎉 thank you for your work on this!

2024-03-13 20:09 UTC, merged