MDN Community: Discussion guidelines
mdn/content pull request #32620
Opened 2024-03-08 21:30 UTC by estelle

2024-03-10 23:12 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +3. Inform the approves and other essential voices of the discussion and your proposed timeline. If needed, reach out to them again after 2 weeks, and weekly thereafter, until they provide feedback.
```suggestion
3. Inform the approvers and other essential voices of the discussion and your proposed timeline. If needed, reach out to them again after 2 weeks, and weekly thereafter, until they provide feedback.
```

2024-03-10 23:14 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +7. If there are points of contention, arrange an online, synchronous, face-to-face meeting to resolve any remaining disagreements on in the discussion thread.
```suggestion
7. If there are points of contention, arrange an online, synchronous, face-to-face meeting to resolve any remaining disagreements (as captured in the discussion thread).
```

2024-03-10 23:17 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +If the discussion involves reaching out to and receiving feedback from experts, the timeline above can be extended as needed.
Might be nice to add a checklist section at the end that a discussion owner can copy/paste in and then checkoff as each step is complete.

2024-03-10 23:22 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +   - Face-to-face meetings must be announced in all [communication channels](/en-US/docs/MDN/Community/Communication_channels) (Slack, Discord, GitHub discussion, etc.).
I will never go on discord so I will never engage in this process. In any case, I think we have too many channels. Minimally community call and slack.

2024-03-10 23:32 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
I prefer the term owner to driver.

2024-03-10 23:42 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +If you are proposing new content or features, please open a new issue in the [relevant MDN GitHub repository](https://github.com/mdn/), such as [MDN Content](https://github.com/mdn/content/issues/) o
This is too much context/feels a bit repetitive. This is what I think is important:

```suggestion
The MDN community is encourage to [initiate, engage in, and resolve discussions](https://developer.mozilla.org/en-US/docs/MDN/Community/Discussions) related to the MDN Web Docs documentation.

While many discussions reach broad agreement very quickly, others may stall if there is no clear path to resolution: for example due to conflicting opinions.
This process explains how you can work with the community in order to progress discussions through to resolution in a reasonable timeframe.
```

2024-03-10 23:43 UTC, hamishwillee reviewed
THanks @estelle . I'm fine with the broad picture, but the discussion thread doesn't tell me if the result of the community call. I'll add some more reviewers.

2024-03-11 06:28 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
i prefer the term too, but the driver may not be the owner. The person driving the discussion (the driver) to a resolution may not be the same person who opened the discussion (the owner).

2024-03-11 06:29 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +   - Face-to-face meetings must be announced in all [communication channels](/en-US/docs/MDN/Community/Communication_channels) (Slack, Discord, GitHub discussion, etc.).
made this a bit more "appropriate channels" over "required channels" as not everyone is on discord or slack. Some may be more webDX community group based or similar.

2024-03-11 10:47 UTC, bsmth commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +The MDN community is encourage to [initiate, engage in, and resolve discussions](/en-US/docs/MDN/Community/Discussions) related to the MDN Web Docs documentation.
```suggestion
The MDN community is encouraged to [initiate, engage in, and resolve discussions](/en-US/docs/MDN/Community/Discussions) related to the MDN Web Docs documentation.
```

2024-03-11 10:49 UTC, bsmth commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +   - Informing all the appropriate channels - Slack, Discord, tagging people Github, and other channels if appropriate - of needed feedback by specific dates.
```suggestion
   - Informing all the appropriate channels - Slack, Discord, tagging people on GitHub, and other channels if appropriate - of needed feedback by specific dates.
```

2024-03-11 11:51 UTC, pepelsbey commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +   - Summarizing face-to-face conclusions in the relevant discussion on https://github.com/orgs/mdn/discussions within the relevant discussion.
```suggestion
   - Summarizing face-to-face conclusions in the relevant discussion on [Discussions](https://github.com/orgs/mdn/discussions).
```

2024-03-11 18:32 UTC, dipikabh requested changes
Leaving a few thoughts and plenty of questions

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +## Discussion timeline
Starting the document with this section might be a good idea. That is, we first define how to determine if a discussion is stalled and establish the expected timeline for resolution. And then adopt other strategies when we see there is no progress
```suggestion
## Expected turnaround times for discussions
```

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +Every discussion will follow a different timeline depending on the complexity of the topic, the levels of agreement and disagreement, and the parties involved. Most discussions should be resolved in
- What do you think about removing "parties involved"? It is ultimately about the consensus.
```suggestion
Every discussion will have a different timeline depending on the complexity of the topic and the consensus levels. Ideally, most discussions should be resolved within two months, allowing for the topic to be addressed at various internal meetings. This timeframe ensures diverse viewpoints are considered and everyone interested has the opportunity to contribute to the discussion.
```

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +4. Add the discussion topic to the agendas of relevant meetings.
We'll not know beforehand the discussions that will get stalled. Do these steps need to be done for every discussion opened? Folks in the community will not know who the drivers, stakeholders, and approvers are.

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +1. Each discussion is held / rooted in a [discussion on Github](https://github.com/orgs/mdn/discussions), which is the "source of truth" for the topic.
We don't need to say this, assuming it is covered on the parent page https://developer.mozilla.org/en-US/docs/MDN/Community/Discussions

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
When a discussion is initiated by maintainers, is it okay to go with the assumption that the author is the driver? How will community determine a driver? Also, the question of selecting a driver would arise only if a discussion hasn't progressed.

In the timeline section, we need to define the period of inactivity or non-resolution beyond which a discussion can be considered as stalled.

2024-03-11 18:32 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
This does not need to be a numbered step
```suggestion
Each topic of discussion needs a driver. The driver is responsible for:
```

2024-03-11 21:55 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +1. Each discussion is held / rooted in a [discussion on Github](https://github.com/orgs/mdn/discussions), which is the "source of truth" for the topic.
We do need to say #1, because we need to be clear that meeting minutes, verbal discussions, issues, and PRs are not sources. Recaps of any meetings, discussions, issues, and PRs must be documented in the discussion as the "source of truth". Also, we don't know if someone is going re-read the top level page when following the guidelines on this page.

2024-03-11 21:56 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +4. Add the discussion topic to the agendas of relevant meetings.
the intro explains when this guide, and therefore these steps , are relevant

2024-03-11 22:04 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +title: Resolving discussions
Changed to "Managing and resolving discussions".

2024-03-11 22:08 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
That is why this was originally called "resolving". Discussions only need drivers, guidelines, and timelines if they need help being resolved. This is expressed in the intro. 

Generally, the initiator may be the driver, but sometimes people start discussions but aren't invested in the outcome, while someone else may be more passionate about it. I want to provide guidelines open to interpretation, not rules... but someone might be more vested than me in this discussion ;)

2024-03-11 22:09 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
we have a 3 and a 1 so keeping the 2.

2024-03-11 22:29 UTC, hamishwillee commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
> The person driving the discussion (the driver) to a resolution may not be the same person who opened the discussion (the owner).

The person who cares is the owner, whoever posted it :-). The author is likely to be the owner.

But that's just semantics. The point here is that it is possible to look at this text and say "you mean the owner, or the author right". So perhaps a definition is needed. 

How does the driver get picked - it's obvious who the author is?

2024-03-11 22:35 UTC, hamishwillee approved these changes
I'm marking as approved because I see this as advice for people with a stalled discussion that they really want to progress. There are very few cases where I see a discussion actually _needs_ to be resolved, but if someone cares enough then this will be helpful.

What's missing for me in the whole picture is triage - looking at the discussions and deciding whether their resolution would actually make a real difference vs the cost. But that's a job for community management to evaluate.

2024-03-12 10:18 UTC, bsmth commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
In general I think we're describing an RFC process which might be good to compare:

* https://github.com/withastro/roadmap/blob/78b736c28fe487ad02ec76bb038ad1087c471057/README.md#astro-rfc

>**Astro’s RFC process is forked from the [Vue RFC process]** which itself owes inspiration to the **[React RFC process], [Rust RFC process] and [Ember RFC process].**

[vue rfc process]: https://github.com/vuejs/rfcs
[react rfc process]: https://github.com/reactjs/rfcs
[rust rfc process]: https://github.com/rust-lang/rfcs
[ember rfc process]: https://github.com/emberjs/rfcs
[proposals]: https://github.com/withastro/rfcs/tree/main/proposals

2024-03-12 19:07 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
Yes, I think bulleted makes better sense

2024-03-12 19:09 UTC, dipikabh commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +1. Each discussion is held / rooted in a [discussion on Github](https://github.com/orgs/mdn/discussions), which is the "source of truth" for the topic.
Got it! In that case, might help to add this clarification in.

2024-03-12 19:56 UTC, estelle commented on files/en-us/mdn/community/discussions/Resolving_discussions/index.md
> +2. Each topic of discussion needs a driver. The driver is responsible for:
The driver will generally be the author and owner, but doesn't have to be. Defining it to that person limits it. Leaving it undefined allows for anyone with the energy to move the discussion forward to take on that responsibility.

 I guess we could just write what I just said if required.

2024-03-12 20:34 UTC, dipikabh requested changes
Thanks for clarifications, @estelle. I've relooked at the page from the perspective of targeting only stalled discussions.

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +2. Identify any key stakeholders and needed approvers (the individuals who need to weigh in on the topic and give their approval), if any.
Sorry if I'm being pedantic. If I look at the timeline of a discussion as an example: someone opens a discussion, it receives a lot of opinions and ideas and responses, and this happens over say 4 weeks. But then the conversation dies without reaching a conclusion. It's then I would regard the discussion as stalled (for example, https://github.com/orgs/mdn/discussions/426. This one has not reached a conclusion even after async/meeting discussions)

Q - Do we need to define the time or the state when to consider a discussion stalled?

- If we're focusing only on stalled discussions in this document (which means "Post the discussion" has already happened), when should the drivers and stakeholders be assigned? Are we doing steps 1 and 2 for all discussions or only for stalled discussions? If this is applicable only for stalled, we could add another sentence as a lead-in for the steps (but would that be time-based or the author taking a call that the discussion is in limbo)?
- From the current wording, it seems that these steps are more to ensure that no discussion is stalled, that is, from the beginning every discussion is assigned a driver and approver and brought up in meetings so that it gets resolved within two months.

- I am not clear about "driver". How does a community person pick a driver? Echoing @hamishwillee's question here: "How does the driver get picked"? Or does someone invested in the topic assume that role? Similarly, would the community folk know who "key stakeholders and needed approvers" are?

- Suggesting "might" for driver because it is not an essential step ?



```suggestion
Every discussion has a different timeline depending on the complexity of the topic and the consensus levels. Ideally, most discussions should be resolved within two months, allowing for the topic to be addressed at various internal meetings. This timeframe ensures diverse viewpoints are considered and everyone interested has the opportunity to contribute to the discussion. If your discussion has not reached a conclusion within two months, consider performing some of the following steps:

1. You might want to assign a driver.
2. Identify any key stakeholders and needed approvers (individuals who need to weigh in on the topic and give their approval), if any.
```

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +6. During the second month, keeping reaching out the the community for feedback on the proposed plan, making updates to the plan in light of any new feedback. Rinse. Repeat.
"reaching out to the community" - this assumes that the discussion is initiated by a maintainer?
```suggestion
5. After a month, sort through the feedback, discussions, and agreements, and formulate an initial plan merging the feedback into a possible action plan. Re-inform and re-request feedback from all interested parties, including everyone who participated in the discussion in any way.
6. During the second month, keeping reaching out to the community for feedback on the proposed plan, making updates to the plan in light of any new feedback. Rinse. Repeat.
```

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +10. Close the discussion.
I think we should also mention that not all discussions will reach a conclusion. Maybe the action/fix required is part of a future year's roadmap. Maybe after two months, the conclusion reached is "can't happen now".

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +1. Each discussion is held / rooted in a [discussion on Github](https://github.com/orgs/mdn/discussions), which is the "source of truth" for the topic.
```suggestion
- The topic you post on [Github discussion](https://github.com/orgs/mdn/discussions) serves as the "source of truth" for the topic. To maintain continuity, remember to capture summaries and notes from any meetings and async discussions in this GitHub discussion thread.
```

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +   - Guiding the implementation of the discussion results or working with the appropriate team lead to ensure that the results are implemented.
```suggestion
- Each topic of discussion needs a driver. This may be the author of the discussion topic. The driver is responsible for:

   - Guiding the conversation.
   - Making people aware the discussion exists.
   - Setting the feedback timeline, informing people of it, changing the timeline as necessary, and sticking to the timeline as appropriate.
   - Informing all the appropriate channels - Slack, Discord, tagging people on GitHub, and other channels if appropriate - of needed feedback by specific dates.
   - Bringing up the topic in community and weekly meetings.
   - Organizing a synchronous, online face-to-face meeting if required (if there is disagreement). Face-to-face meetings should be rare and only if required (see the next point).
   - Summarizing face-to-face conclusions in the discussion topic.
   - Guiding the implementation of the discussion results or working with the appropriate team lead to ensure that the results are implemented.
```

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +9. [Create an issue](/en-US/docs/MDN/Community/Issues) with the final plan for implementing the resolution and put it into action.
What do you think about linking this to https://developer.mozilla.org/en-US/docs/MDN/Community/Issues#guidelines_for_reporting_an_issue?

2024-03-12 20:34 UTC, dipikabh commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +Once agreement has been achieved, the discussion can be closed, the resolution announced, and the plan for implementing the resolution can be put it into action!
```suggestion
3. Face-to-face meetings regarding a discussion should only be called if there is disagreement.

   - Face-to-face meetings must be announced in all relevant [communication channels](/en-US/docs/MDN/Community/Communication_channels), such as Slack, Discord, GitHub discussion, etc.
   - Conclusions of each face-to-face meeting must be entered into the GitHub discussion, which remains as the source of truth for the topic.
   - The driver is responsible for calling the meeting, informing all parties, reporting results back into the GitHub discussion.

Once agreement has been achieved, the resolution can be announced, the discussion can be closed, and the plan for implementing the resolution can be put it into action via a tracking issue!
```

2024-03-19 21:41 UTC, estelle commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +## Expected turnaround times for discussions
I don't think this is needed as it is inferred; turnaround times aren't needed for completed discussions.

2024-03-19 21:43 UTC, estelle commented
> Thanks for clarifications, @estelle. I've relooked at the page from the perspective of targeting only stalled discussions.

This is for all discussions (where a resolution is wanted); to prevent them from getting stalled.
also, these are guidelines, not rules. Not all discussions need a resolution. However, people who start a discussion wanting a resolution can benefit from guidelines to help them work toward a resolution in a timely manner.

2024-03-19 22:55 UTC, estelle commented on files/en-us/mdn/community/discussions/managing_and_resolving_discussions/index.md
> +Once agreement has been achieved, the discussion can be closed, the resolution announced, and the plan for implementing the resolution can be put it into action!
reversed the "announced" and "closed". Kept the rest original.

2024-03-24 16:01 UTC, dipikabh approved these changes
Thank you, @estelle, for putting these guidelines/doc together. Appreciate your patience in addressing my comments and questions.

2024-03-25 21:09 UTC, merged

2024-03-25 21:28 UTC, hamishwillee commented
Nicely done