fix(learn): Update page titles
mdn/content pull request #32643
Opened 2024-03-11 13:39 UTC by dipikabh

### Description

In the sidebar in the [Learn](https://developer.mozilla.org/en-US/docs/Learn) area, each drop-down's "first item" matches the drop-down header. This PR fixes a few discrepancies where the first item's page title is slightly different.

### Motivation

To follow the same style for page titles

### Additional details

A few instances where the above described style is followed

<kbd>![learnsidebar-1](https://github.com/mdn/content/assets/23019147/a84e4159-2371-4093-b3ae-96e7c54c658c)</kbd>

<kbd>![learnsidebar-2](https://github.com/mdn/content/assets/23019147/5eea3c24-543c-4116-a131-c0329e3d21ba)</kbd>

<kbd>![learnsidebar-4](https://github.com/mdn/content/assets/23019147/876b6d5b-64d7-4a17-b26f-49c7109d9668)
</kbd>

<kbd>![learnsidebar-3](https://github.com/mdn/content/assets/23019147/9f64bea2-6a9c-423e-8c4a-9f48fc5612c6)</kbd>

2024-03-11 18:00 UTC, estelle requested changes
The web forms should read "web forms". You may want to change the second half of the title, but the first two words should be the original. The rest of the PR looks good.

2024-03-11 18:00 UTC, estelle commented on files/en-us/learn/forms/index.md
> +title: Core forms learning pathway
```suggestion
title: Web forms learning pathway
```

2024-03-12 00:02 UTC, hamishwillee approved these changes
Other than Estelle's comment https://github.com/mdn/content/pull/32643/files#r1520191823 LTGM

2024-03-12 16:44 UTC, dipikabh commented on files/en-us/learn/forms/index.md
> +title: Core forms learning pathway
Thanks! I agree with your suggestion to go with "web forms". What do you think about the following title to align with other similar headings like "JavaScript building blocks" and "CSS building blocks": 

```suggestion
title: Web form building blocks
```
In my previous edit, I was trying to match the page title with the drop-down header, but ideally the header should be updated:

<kbd>![learnsidebar-5](https://github.com/mdn/content/assets/23019147/50a70acf-34b5-414c-9dec-0e0914f46c55)
</kbd>

2024-03-12 16:44 UTC, dipikabh commented
Thank you @estelle and @hamishwillee for the review.

2024-03-12 19:05 UTC, estelle approved these changes

2024-03-12 19:05 UTC, merged

2024-03-12 23:07 UTC, dipikabh commented
Thanks, @estelle!