RTCRemoteInboundRtpStreamStats - plus alignment with outbound
mdn/content pull request #32657
Opened 2024-03-12 06:11 UTC by hamishwillee

This adds docs for `RTCRemoteInboundRtpStreamStats `, a stats object/dictionary you can get by iterating a [`RTCStatsReport`](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport).

It is not very exciting. Largely following the same patterns as the other docs.

This shares some common properties with RTCRemoteOutoundRtpStreamStats. There have been some changes to align those.

This is part of the ongoing work to finished RTC stats, which was started in https://github.com/mdn/content/pull/27028

2024-03-15 05:44 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/packetsreceived/index.md
> +A positive integer value indicating the total number of received RTP packets at the remote endpoint.
NOTE, I am confused here. For context `RTCRemoteInboundRtpStreamStats` are statistics from the remote system about inbound stream stats. In other words, the local end sent some information to the remote end. The remote end has sent this information back to say what it received.


So for inbound stats my understanding is that you're getting the `packetsReceived` as measured at the remote end. This will simply be all received packets since the beginning of the session including retransmissions. 
This contrasts with `RTCInboundRtpStreamStats.packetsRecieved` which is the local end calculating stats for the inbound stream.

But the spec states for `packetsReceived`

> packetsReceived of type unsigned long long
> 
> Total number of RTP packets received for this SSRC. This includes retransmissions. At the receiving endpoint, this is calculated as defined in [RFC3550] section 6.4.1. At the sending endpoint the packetsReceived is estimated by subtracting the Cumulative Number of Packets Lost from the Extended Highest Sequence Number Received, both reported in the RTCP Receiver Report, and then subtracting the initial Extended Sequence Number that was sent to this SSRC in a RTCP Sender Report and then adding one, to mirror what is discussed in Appendix A.3 in [RFC3550], but for the sender side. If no RTCP Receiver Report has been received yet, then return 0.

So what's the sending and receiving endpoint here? Do they mean local and remote or do they mean "original sender". 
IF we assume receiving endpoint we mean "whatever is calculating the packets received" then this works because a receiver just counts what packets it got. 

I THINK the bit about "at the sending endpoint ..." is irrelevant. I.e. you might calculate the packetsRecieved in that way at the sender, but that has nothing to do with this data we are reporting.

2024-03-19 05:37 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/fractionlost/index.md
> +Note that the packet loss can be negative if more packets are received than expected, and in this case the fraction is set to zero.
Note that all of this is my "guess/evaluation" based on the RFC info and appending linked in the next section. All the spec says is that it is calculated as per those spec links. I have interpreted that to mean that the property contains the 8 bit unsigned integer in the RR/SR "fraction loss" field. That is calculated by 8 bit shifting a number so the fraction is now the number. 

It all sounds rational, but I can't prove it. I've tried a bunch of examples out and they all give me a value of zero :-( (which is what you get if there is no loss OR if the loss is negative).

2024-03-19 05:39 UTC, hamishwillee commented
@wbamberg Yet another one to look at. I will probably continue working on it to update `RTCRemoteOutoundRtpStreamStats` if you don't review it soon, as they have more common behaviour. But if you do start reviewing I'll stop that.

2024-03-19 05:53 UTC, wbamberg commented
ah right, so the quicker I review it the smaller it'll be? :)

2024-03-19 05:59 UTC, hamishwillee commented
@wbamberg Yes :-). I'll be pausing if you review this earlier so that neither of us have a moving target for the "common" changes that are in this PR.

2024-04-06 03:50 UTC, wbamberg commented
@hamishwillee , I have started on this.

2024-04-08 23:15 UTC, wbamberg requested changes, later dismissed

2024-04-08 23:15 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/index.md
> +  - : A string which is used to find the local {{domxref("RTCInboundRtpStreamStats")}} object that shares the same [synchronization source(SSRC)](#ssrc).
As before I think this would be better as a link to https://pr32657.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/ssrc.

2024-04-08 23:15 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/roundtriptimemeasurements/index.md
> +The **`roundTripTimeMeasurements`** property of the {{domxref("RTCRemoteOutboundRtpStreamStats")}} dictionary contains a positive integer value that represents the total number valid round trip time
```suggestion
The **`roundTripTimeMeasurements`** property of the {{domxref("RTCRemoteOutboundRtpStreamStats")}} dictionary is a positive integer value that represents the total number valid round of trip time measurements received for this [synchronizing source](/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/ssrc).
```

2024-04-08 23:15 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/roundtriptimemeasurements/index.md
> +The count can be used as a measure of the availability and reliability of round-trip-time measurement data.
```suggestion
The count can be used as a measure of the availability and reliability of round trip time measurement data.
```

2024-04-08 23:15 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/roundtriptimemeasurements/index.md
> +This is the count of _RTCP Sender Reports (SR)_ received for this [synchronizing source](#ssrc) that contain a "delay since last RR (DLRR)" field from which a valid round trip time can be derived (ac
```suggestion
This is the number of _RTCP Sender Reports (SR)_ received for this [synchronizing source](/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/ssrc) that contain a "delay since last RR (DLRR)" field from which a valid round trip time can be derived (according to {{rfc("3611","DLRR Report Block", "4.5")}}).
```

2024-04-08 23:15 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/totalroundtriptime/index.md
> +The **`totalRoundTripTime`** property of the {{domxref("RTCRemoteOutboundRtpStreamStats")}} dictionary indicates the cumulative number sum of all round trip time (RTT) measurements since the beginnin
```suggestion
The **`totalRoundTripTime`** property of the {{domxref("RTCRemoteOutboundRtpStreamStats")}} dictionary indicates the sum of all round trip time (RTT) measurements since the beginning of the session, in seconds.
```

2024-07-08 09:47 UTC, pepelsbey commented
@hamishwillee hey! Do you think we can still pull this through?

2024-07-09 00:29 UTC, hamishwillee commented
I've been putting this off as not a priority. Will have a look today, but my reviewer has gone on holiday.

2024-07-09 00:31 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/fractionlost/index.md
> +The **`fractionLost`** property of the {{domxref("RTCRemoteInboundRtpStreamStats")}} dictionary provides the fraction packet loss for this [synchronization source (SSRC)](/en-US/docs/Web/API/RTCRemot
```suggestion
The **`fractionLost`** property of the {{domxref("RTCRemoteInboundRtpStreamStats")}} dictionary provides the fraction of packets lost for this [synchronization source (SSRC)](/en-US/docs/Web/API/RTCRemoteInboundRtpStreamStats/ssrc) in the last reporting interval.
```

2024-07-09 00:33 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/index.md
> +  - : A string that is used to find the local {{domxref("RTCOutboundRtpStreamStats")}} object that shares the same [synchronization source (SSRC)](#ssrc).
Agreed (though it feels a bit weird to link to inbound stream stats info from the outbound stream info).

```suggestion
  - : A string that is used to find the local {{domxref("RTCOutboundRtpStreamStats")}} object that shares the same [synchronization source (SSRC)]([/en-US/docs/Web/API/RTCRemoteInboundRtpStreamStats/ssrc](en-US/docs/Web/API/RTCRemoteInboundRtpStreamStats/ssrc)).
```

2024-07-09 00:36 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/index.md
> +  - : A number indicating the fraction packet loss for this [synchronization source (SSRC)](#ssrc). Calculated as defined in [RFC3550] section 6.4.1 and Appendix A.3.
Agreed
```suggestion
  - : A number indicating the fraction of packets lost for this [synchronization source (SSRC)](en-US/docs/Web/API/RTCRemoteInboundRtpStreamStats/ssrc) since the last sender or receiver report.
```

2024-07-09 00:40 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/index.md
> +  - : An integer indicating the total number of RTP packets lost for this [synchronization source (SSRC)](#ssrc), as measured at the remote endpoint.
Only linking and defining the SSRC term for the first case - after that we should be able to use it as "SSRC"

```suggestion
  - : A number that indicates the estimated round trip time (RTT) for this SSRC, in seconds.
    This property will not exist until valid RTT data has been received.
- {{domxref("RTCRemoteInboundRtpStreamStats.roundTripTimeMeasurements", "roundTripTimeMeasurements")}} {{optional_inline}}
  - : A positive integer indicating the total number of valid round trip time measurements received for this [synchronization source (SSRC)](#ssrc).
- {{domxref("RTCRemoteInboundRtpStreamStats.totalRoundTripTime", "totalRoundTripTime")}} {{optional_inline}}
  - : A number indicating the cumulative sum of all round trip time measurements since the beginning of the session, in seconds.
    The average round trip time can be computed by dividing `totalRoundTripTime` by [`roundTripTimeMeasurements`](#roundtriptimemeasurements).

### Received RTP stream statistics

<!-- RTCReceivedRtpStreamStats -->

- {{domxref("RTCRemoteInboundRtpStreamStats.packetsReceived", "packetsReceived")}} {{optional_inline}}
  - : A positive integer indicating the total number of RTP packets received for this SSRC, including retransmissions.
- {{domxref("RTCRemoteInboundRtpStreamStats.packetsLost", "packetsLost")}} {{optional_inline}}
  - : An integer indicating the total number of RTP packets lost for this SSRC, as measured at the remote endpoint.
```

2024-07-09 00:41 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/index.md
> +  - : A positive integer that identifies the synchronization source (SSRC) of the RTP packets in this stream.
```suggestion
  - : A positive integer that identifies the SSRC of the RTP packets in this stream.
```

2024-07-09 00:42 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/index.md
> +  - : A string which is used to find the local {{domxref("RTCInboundRtpStreamStats")}} object that shares the same [synchronization source(SSRC)](#ssrc).
```suggestion
  - : A string which is used to find the local {{domxref("RTCInboundRtpStreamStats")}} object that shares the same [synchronization source(SSRC)](/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/ssrc).
```

2024-07-15 16:12 UTC, pepelsbey commented
> Will is on holiday, so it is not urgent unless you want to review it?

Thank you! As you said, it’s not a priority, so I’d leave it to Will since he’s already familiar with it.

2024-07-15 23:11 UTC, hamishwillee commented
Cool. I have a few more review comments to address in any case. This moves to end of the cycle job.

2024-07-30 04:18 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/index.md
> +<!-- TBD -->
Yes. Done.

2024-07-30 05:35 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/fractionlost/index.md
> +This has the effect of making the fractional part of the fraction packet loss into the 8 bit unsigned integer which is what is sent in the SR or RR packet and contained in this property.
@wbamberg Good point. Thinking about this, the algorithm is interesting, but it isn't "needed" by a user. All you need to know is how to turn the value into a percentage or fractional value, and that the value is indicative, not precise.

The algorithm is also more complicated than this because it has to account for wrapping of values used to hold packet counts etc.

So what I have done simplified this and linked to the explanation of the algorithm,

2024-07-30 05:37 UTC, hamishwillee commented on files/en-us/web/api/rtcremoteinboundrtpstreamstats/fractionlost/index.md
> +The fraction packet loss comes from the 8-bit `fraction lost` field of the last SR or RR RTCP packet.
I've expanded out what they are in the text, and also added links to spec in the See also section.

We should have an overview of the RTCP protocol somewhere that outlines these bits that we can link to. But it is something that probably should be done by someone as a complete overhaul.

2024-07-30 05:38 UTC, hamishwillee commented
@wbamberg I have accepted your suggestions and addressed all the issues you raised. No urgency, but this is ready for a new review when you are.

2024-07-31 23:51 UTC, wbamberg approved these changes
Thanks Hamish!

3 typo suggestions, but approving anyway so you can merge if you accept them :).

2024-07-31 23:51 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/index.md
> +  - : A string which is used to find the local {{domxref("RTCInboundRtpStreamStats")}} object that shares the same [synchronization source(SSRC)](/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/s
```suggestion
  - : A string which is used to find the local {{domxref("RTCInboundRtpStreamStats")}} object that shares the same [synchronization source (SSRC)](/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/ssrc).
```

2024-07-31 23:51 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/index.md
> +  - : A positive integer indicating the total number of {{glossary("RTCP")}} Sender Report (SR) blocks sent for this [synchronization source(SSRC)](#ssrc).
```suggestion
  - : A positive integer indicating the total number of {{glossary("RTCP")}} Sender Report (SR) blocks sent for this [synchronization source (SSRC)](#ssrc).
```

2024-07-31 23:51 UTC, wbamberg commented on files/en-us/web/api/rtcremoteoutboundrtpstreamstats/index.md
> +  - : A positive number that represents the total number of valid round trip time measurements received for this [synchronization source(SSRC)](#ssrc).
```suggestion
  - : A positive number that represents the total number of valid round trip time measurements received for this [synchronization source (SSRC)](#ssrc).
```

2024-08-02 00:45 UTC, hamishwillee commented
Thanks very much @wbamberg - appreciate your patience and help with these. One day I may be finished with all of these and we can both have a deep sign of relief.

2024-08-02 00:45 UTC, merged

2024-08-02 00:51 UTC, wbamberg commented
ha yes I admit to a feeling of dread when I see one of these 🤣