fix(aria-label): Improve page for clarity
mdn/content pull request #32688
Opened 2024-03-14 22:09 UTC by dipikabh

### Description

[Glossary page: Accessible name](https://developer.mozilla.org/en-US/docs/Glossary/accessible_name)
- Fixes subject-verb mismatches
- Edits for clarity

[Attribute: aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)
- Replaces link for "accessible name" to our glossary page
- Adds a description for the example code
- Reorganizes multi-para content in "Description" into bullets for better scanning of info
- Collates repeated info in text and note
- Adds missing period to note text
- Other general edits for clarity and readability

### Motivation

To improve readability, clarity, and organization

### Additional details

### Related issues and pull requests

2024-03-21 19:38 UTC, estelle requested changes
several very minor suggestions

2024-03-21 19:38 UTC, estelle commented on files/en-us/glossary/accessible_name/index.md
> +It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible names from their conten
```suggestion
It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible name from their contents. For example, given `<a href="foo.html">Bar</a>`, the accessible name of this `<a>` element is "Bar."
```
the plural made it sound like an element can have more than one accessible name. It is correct to use "names", but "name" is also ok, and less likely to create confusion.

2024-03-21 19:38 UTC, estelle commented on files/en-us/glossary/accessible_name/index.md
> +Other elements get their accessible names from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}}, {{HTMLElement("table")}}, and {{HTMLElement("figure")}}
```suggestion
Other elements get their accessible name from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}}, {{HTMLElement("table")}}, and {{HTMLElement("figure")}} contain a descendant {{HTMLElement("fieldset")}}, {{HTMLElement("caption")}}, or {{HTMLElement("figcaption")}} element, respectively, the association is automatic. For form elements like {{HTMLElement("textarea")}} and {{HTMLElement("input")}}, the accessible name comes from the associated {{HTMLElement("label")}} element; the association in this case has to be explicitly defined by setting the `for` attribute in the `<label>` element to match the `id` of the form control, unless the association is implicit as is the case when the form control is nested within the `<label>`.
```

2024-03-21 19:38 UTC, estelle commented on files/en-us/glossary/accessible_name/index.md
> +For some elements like {{HTMLElement("img")}}, the accessible name comes from their attributes; for example the `alt` attribute in the case of `<img>`. Given `<img src="grape.jpg" alt="banana"/>`, th
```suggestion
For some elements the accessible name comes from their attributes; for example, the `alt` attribute in the case of {{HTMLElement("img")}}. Given `<img src="grape.jpg" alt="banana"/>`, the image's accessible name is "banana."
```

2024-03-21 19:38 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +Sometimes, the default {{Glossary("accessible_name", "accessible name")}} of an element is missing or the accessible name does not accurately describe the contents of the element and there is no cont
```suggestion
Sometimes, the default {{Glossary("accessible_name", "accessible name")}} of an element is missing or the accessible name does not accurately describe the contents of the element and there is no content visible in the DOM that can be associated with the object to give it meaning. A common example of such an element is a button containing an SVG or an icon font without any text. (Check out this [video about you shouldn't use icon fonts](https://www.youtube.com/watch?v=9xXBYcWgCHA).)
```

2024-03-21 19:38 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +> **Note:** `aria-label` is intended for interactive elements or for those made interactive via other ARIA declarations when there's no visible text in the DOM to serve as a label.
```suggestion
> **Note:** `aria-label` is intended for interactive elements or for elements made interactive via other ARIA declarations when there's no visible text in the DOM to serve as a label.
```

2024-03-21 19:38 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +> **Note:** While `aria-label` can be used on any element that can have an accessible name, in practice however, it is supported only on interactive elements, widgets, landmarks, images, and iframes.
```suggestion
> **Note:** While `aria-label` can be used on any element that can have an accessible name, in practice however, it is supported only on interactive elements, [widgets](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles), [landmarks](/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles), images, and iframes.
```
people may not be sure what elements/roles are widgets and landmarks. let's link those to the list already on MDN. This added text is on line 55, so a bit redundant (but sometimes duplication is ok, just pointing it out.)

2024-03-21 19:38 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- Not all elements can be given an accessible name. Neither `aria-label` nor `aria-labelledby` should be used with non-interactive elements, inline structural roles such as with `code`, `term`, and `
```suggestion
- Not all elements can be given an accessible name. Neither `aria-label` nor `aria-labelledby` should be used with non-interactive elements, inline structural roles such as with `code`, `term`, and `emphasis`, and roles not mapped to the accessibility API, including `presentation`, `none`, and `hidden`. The `aria-label` attribute is intended for interactive elements only, including links, videos, form controls, and those with [landmark roles](/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles) or [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles); `aria-label` provides an accessible name when no visible label exists in the DOM.
```

2024-03-21 19:38 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- If you assign a `title` to an {{HTMLElement('iframe')}}, define an `alt` attribute for an {{HTMLElement('img')}}, and add {{HTMLElement('label')}} for an {{HTMLElement('input')}}, `aria-label` is n
```suggestion
- If you assign a `title` to an {{HTMLElement('iframe')}}, define an `alt` attribute for an {{HTMLElement('img')}}, or add {{HTMLElement('label')}} for an {{HTMLElement('input')}}, `aria-label` is not necessary. However, if an `aria-label` attribute is present, it will take precedence over the iframe's `title`, the image's `alt`, or the input's `<label>` text as the accessible name for that element.
```
making singular so as to ensure nothing is confusing, especially to our a11y readers with cognition differences.

2024-03-21 21:25 UTC, scottaohara commented on files/en-us/glossary/accessible_name/index.md
> +It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible names from their conten
thank you estelle.  i was feeling very iffy about these updates - so i'm glad you share my concern

2024-03-21 21:25 UTC, scottaohara commented on files/en-us/glossary/accessible_name/index.md
> +Other elements get their accessible names from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}}, {{HTMLElement("table")}}, and {{HTMLElement("figure")}}
i would remove the example of figure > figcaption.  since (though this is taking a while to get full implementation) figcaption will not provide a name to figure in the future. this was generally considered too noisy and redundant, especially since figcaptions can contain structured content which would not have their semantics communicated in the flattened text string that becomes the name.

2024-03-21 21:25 UTC, scottaohara commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- Not all elements can be given an accessible name. Neither `aria-label` nor `aria-labelledby` should be used with non-interactive elements, inline structural roles such as with `code`, `term`, and `
this isn't entirely true.  it's not just interactive elements that aria-label or aria-labelledby can be used with.  I realize this wasn't a change made in this PR, but since this PR is open, this information should be corrected.  There are various non-interactive elemetns which can benefit from having an aria-label/labelledby name, if one can't use the native features to provide one (e.g., tables, fieldsets)

2024-03-22 16:13 UTC, dipikabh commented on files/en-us/glossary/accessible_name/index.md
> +It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible names from their conten
probably the right fix here would be to also make "content" singular:

> It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible name from their content.

2024-03-22 16:35 UTC, dipikabh commented on files/en-us/glossary/accessible_name/index.md
> +Other elements get their accessible names from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}}, {{HTMLElement("table")}}, and {{HTMLElement("figure")}}
Thanks, both!

Fixing the last sentence as:

> The association needs to be explicitly defined by setting the `for` attribute in the `<label>` element to match the form element's `id`. Alternatively, an implicit association is created when the form control is directly nested within the `<label>` element.

@scottaohara thanks for the insights into the future direction of figure > figcaption regarding accessible name. I've removed their mention.

2024-03-22 16:44 UTC, dipikabh commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +> **Note:** While `aria-label` can be used on any element that can have an accessible name, in practice however, it is supported only on interactive elements, widgets, landmarks, images, and iframes.
This is good, thanks!

2024-03-22 16:47 UTC, dipikabh commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- If you assign a `title` to an {{HTMLElement('iframe')}}, define an `alt` attribute for an {{HTMLElement('img')}}, and add {{HTMLElement('label')}} for an {{HTMLElement('input')}}, `aria-label` is n
nice, thanks!

2024-03-22 18:43 UTC, dipikabh commented on files/en-us/glossary/accessible_name/index.md
> +It is best to use visible text as the accessible name. Many elements, including {{HTMLElement("a")}}, {{HTMLElement("td")}} and {{HTMLElement("button")}}, get their accessible names from their conten
Good point! Thanks

2024-03-22 20:16 UTC, dipikabh commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- Not all elements can be given an accessible name. Neither `aria-label` nor `aria-labelledby` should be used with non-interactive elements, inline structural roles such as with `code`, `term`, and `
@scottaohara I'm glad you mentioned this because I started looking at this page precisely because of this issue raised here: [ The documentation for aria-label mentions that this is for interactive elements only, but this doesn't seem right #31739 ](https://github.com/mdn/content/issues/31739)

There are two instances on the page that mention that `aria-label` should be used for interactive elements only.
1. I'm removing this note in the [Associated roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label#associated_roles) section:
> **Note:** The `aria-label` attribute is intended for interactive elements only. When placed on non-interactive elements, such as those listed above, it may not be read or may confuse your users as a non-interactive element that acts like an interactive one.

2. I'm updating the above point as follows (removing reference to non-interactive elements, removing `hidden`):

>  - Not all elements can be given an accessible name. Neither `aria-label` nor `aria-labelledby` should be used with inline structural roles such as with `code`, `term`, and `emphasis`, and roles not mapped to the accessibility API, including `none`. The `aria-label` attribute is intended for elements including links, videos, form controls, and those with [landmark roles](/en-US/docs/Web/Accessibility/ARIA/Roles#3._landmark_roles) or [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles); `aria-label` provides an accessible name when no visible label exists in the DOM.

3. Updating the list in the [Associated roles](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label#associated_roles) section as per https://w3c.github.io/aria/#namefromprohibited. `definition` was missing.

2024-03-22 20:33 UTC, dipikabh commented
Thank you, @estelle and @scottaohara, for your insightful reviews and suggestions! I've addressed all your comments. I'd appreciate if you could take another look.

Scott, your feedback about the use of `aria-label` and `aria-labelledby` for both interactive and non-interactive elements was particularly helpful. I have updated the text (and there is scope to add more details to address the linked issue).

(I've updated the PR description to include a reference to the issue that initiated this PR.)

2024-03-27 13:53 UTC, estelle approved these changes
Just some text simplification suggestions

2024-03-27 13:53 UTC, estelle commented on files/en-us/glossary/accessible_name/index.md
> +Other elements get their accessible name from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}} and {{HTMLElement("table")}} contain a descendant {{HTMLE
```suggestion
Other elements get their accessible name from the content of associated elements. For example, when a {{HTMLElement("fieldset")}} or {{HTMLElement("table")}} element contains a descendant {{HTMLElement("fieldset")}} or {{HTMLElement("caption")}} element, respectively, the association of the nested element providing an accessible name for the parent is automatic. For form elements like {{HTMLElement("textarea")}} and {{HTMLElement("input")}}, the accessible name comes from the associated {{HTMLElement("label")}} element. The association needs to be explicitly defined by setting the `for` attribute in the `<label>` element to match the form element's `id`. Alternatively, an implicit association is created when the form control is directly nested within the `<label>` element.
```

2024-03-27 13:53 UTC, estelle commented on files/en-us/glossary/accessible_name/index.md
> +For some elements like {{HTMLElement("img")}}, the accessible name comes from their attributes; for example, the `alt` attribute in the case of {{HTMLElement("img")}}. Given `<img src="grape.jpg" alt
```suggestion
For some elements, the accessible name comes from the element's attributes; for example, the `alt` attribute in the case of {{HTMLElement("img")}}. Given `<img src="grape.jpg" alt="banana"/>`, the image's accessible name is "banana."
```

2024-03-27 13:53 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +The code below shows an example of how to use the `aria-label` attribute to provide an accessible name for a `<button>` element. The button in this example contains an SVG graphic and lacks textual c
```suggestion
The code below shows an example of how to use the `aria-label` attribute to provide an accessible name for a `<button>` element. The button in this example contains an SVG graphic and lacks textual content, making the `aria-label` essential for screen reader users to understand its function, which in this case is "Close".
```
or "defined as" close

2024-03-27 13:53 UTC, estelle commented on files/en-us/web/accessibility/aria/attributes/aria-label/index.md
> +- Don't "overuse" `aria-label`. Remember that it's primarily for assistive technology. To provide additional instructions or to clarify the UI, use visible text with `aria-describedby` or [`aria-desc
```suggestion
- Don't "overuse" `aria-label`. Remember that it's primarily for assistive technologies. To provide additional instructions or to clarify the UI, use visible text with `aria-describedby` or [`aria-description`](/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description), not `aria-label`. Instructions should be accessible to all users, not just to those with screen readers (or preferably, make your UI more intuitive).
```

2024-03-27 14:40 UTC, scottaohara commented on files/en-us/glossary/accessible_name/index.md
> +Other elements get their accessible name from the content of associated elements. If some parent elements such as {{HTMLElement("fieldset")}} and {{HTMLElement("table")}} contain a descendant {{HTMLE
>For example, when a {{HTMLElement("fieldset")}} or {{HTMLElement("table")}} element contains a descendant **{{HTMLElement("fieldset")}}** or {{HTMLElement("caption")}} element

second instance of 'fieldset' should be 'legend'

2024-03-27 18:54 UTC, dipikabh commented
Thanks @estelle and @scottaohara for the reviews!

2024-03-27 18:54 UTC, merged