fix(games): Fix broken links to three.js, related 404s
mdn/content pull request #32721
Opened 2024-03-18 12:51 UTC by bsmth

### Description

You cannot use https://threejs.org/build/three.min.js to download three.js anymore. Instead linking to their install docs and some hints for setting up with Node.js. There are three main options at the moment:

* Node.js (saying this is the preferred method)
* download the GitHub release artifact (350MB zip)
* use a CDN for the JS

__Additions:__

* Add up-to-date install instructions for three.js

__Changes:__

* Link to Three.js tutorial for setup steps in other resources instead of copy pasting.
* Updating link to Phong Material to https://developer.playcanvas.com/user-manual/assets/types/material/
* The [paid Phaser plugin](https://phaser.io/shop/plugins/virtualjoystick) appears to be gone, linking to [the open source version](https://github.com/Gamegur-us/phaser-touch-control-plugin) with links to example code.

__Removals:__

* Removing https://aframevr.tumblr.com/

### Motivation

Keep external links working & install docs up-to-date

2024-03-19 20:44 UTC, estelle requested changes
Four of the pages are approved.
i have comments on two pages

2024-03-19 20:44 UTC, estelle commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
> +The basic PlayCanvas material is called [PhongMaterial](https://developer.playcanvas.com/user-manual/assets/types/material/) — add the following lines below the previous code.
PhongMaterial is now Material.
```suggestion
The basic PlayCanvas material is called [Material](https://developer.playcanvas.com/user-manual/assets/types/material/) — add the following lines below the previous code.
```

2024-03-19 20:44 UTC, estelle commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
>  const boxMaterial = new pc.PhongMaterial();
can this be written as ` pc.Material();` It's in a tool, so not sure what the tools output code is. The code should still work as its still supported, but the asset type is known as Material

2024-03-19 20:44 UTC, estelle commented on files/en-us/games/techniques/control_mechanisms/mobile_touch/index.md
> +If you want to see full example code that uses TouchControl, have a look at the [phaser-touch-control-plugin GitHub repository](https://github.com/Gamegur-us/phaser-touch-control-plugin/blob/master/d
this hasn't been updated in 9 years (Nov 8, 2015). 

We should stick with virtual joystick, as it is still being maintained, and it's free (Phaser - A fast, fun and free open source HTML5 game )  - https://phaser.io/. sample code i found https://codepen.io/rexrainbow

https://rexrainbow.github.io/phaser3-rex-notes/docs/site/virtualjoystick/

2024-03-20 08:51 UTC, bsmth commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
> +The basic PlayCanvas material is called [PhongMaterial](https://developer.playcanvas.com/user-manual/assets/types/material/) — add the following lines below the previous code.
That's a better fix, ty

2024-03-20 08:57 UTC, bsmth commented on files/en-us/games/techniques/control_mechanisms/mobile_touch/index.md
> +If you want to see full example code that uses TouchControl, have a look at the [phaser-touch-control-plugin GitHub repository](https://github.com/Gamegur-us/phaser-touch-control-plugin/blob/master/d
> this hasn't been updated in 9 years (Nov 8, 2015).

Yeah I was a little hesitant about this, too 😄 
 
> We should stick with virtual joystick, as it is still being maintained, and it's free (Phaser - A fast, fun and free open source HTML5 game ) - https://phaser.io/. sample code i found https://codepen.io/rexrainbow
> 
> https://rexrainbow.github.io/phaser3-rex-notes/docs/site/virtualjoystick/

This one is better. I removed the other link because although Phaser is free, the Virtual Joystick it was linking to is a paid plugin: https://old.phaser.io/shop/plugins/virtualjoystick.

I'll take a look at the rexrainbow version in more detail, that looks better, thanks.

2024-03-20 12:11 UTC, bsmth commented on files/en-us/games/techniques/3d_on_the_web/building_up_a_basic_demo_with_playcanvas/engine/index.md
>  const boxMaterial = new pc.PhongMaterial();
Looks like it but I just tested and this behaves differently from `PhongMaterial` with different methods etc so it's not a search/replace. I would update the prose to mention that Phong Material is still supported (as it says in the docs), so we're using that for now.

The existing JS code works without changing anything using the latest PlayCanvas Engine v1.65.0-dev (linked in the tutorial)

![image](https://github.com/mdn/content/assets/43580235/ca3e7348-61e4-4bc2-ac37-1f592d909945)

2024-03-20 12:53 UTC, bsmth commented on files/en-us/games/techniques/control_mechanisms/mobile_touch/index.md
> +If you want to see full example code that uses TouchControl, have a look at the [phaser-touch-control-plugin GitHub repository](https://github.com/Gamegur-us/phaser-touch-control-plugin/blob/master/d
>this hasn't been updated in 9 years (Nov 8, 2015).

All of the Phaser 2.x stuff is pretty old: https://phaser.io/download/release/v2.0.0

This page needs a refresh to upgrade to Phaser 3 at some point. I've pushed some changes that I think are okay for the moment.

2024-03-20 12:55 UTC, bsmth commented
Thanks @estelle for the reviews 🙌🏻
I've made some changes to fix the worst parts, but this whole page needs a revision eventually. Back over to you for another look when you're ready

2024-03-20 18:58 UTC, estelle approved these changes
LGTM! 🎉

2024-03-20 18:58 UTC, merged

2024-03-21 08:12 UTC, bsmth commented
Thank you!