fix: remove fieldset from custom demo, plus other fixes
mdn/content pull request #32761
Opened 2024-03-20 10:22 UTC by chrisdavidmills

### Description

As per https://github.com/mdn/content/issues/32749, the `<select>` demo [Customizing select styles](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#customizing_select_styles) shouldn't really use `<fieldset>`/`<legend>` to label a single `<select>`. There were other issues too.

This PR:

- Replaces `<fieldset>`/`<legend>` with `<section>`/`<label>`.
- Gives the `<select>` elements different `id` values, so we don't have duplicate IDs.
- Removes the `required` and `autocomplete` attributes, as they don't seem needed at all and distract from the point of the demo.
- Adds an `<hr>` and a bit of padding to separate things out a bit.
- Cuts down on the amount of selector cruft in the CSS — the selector chains before were way over the top.

I didn't:

- Fix the issue with wonky taxindexing (the custom select is tabbed to first, then the standard one) due to how taxindex is used to allow the custom select keyboard accessibility to work. I ran out of time on this, and I didn't consider it vital to fix. If anything, it acts as a reminder of the dangers of trying to reimplement browser form behavior yourself.

### Motivation

### Additional details

### Related issues and pull requests

Fixes https://github.com/mdn/content/issues/32749

2024-03-20 20:42 UTC, estelle requested changes
We should either remove this example, or, if we keep it, rewrite is as an HTML custom element and demonstrate best practices for using `<template>`, `<slot>`, ::part, etc.

The basis for the edit is valid and an improvement on what was there, but the original has the worst selectoritis I've seen on MDN, and the edit replaces rather than improves it. Let's improve it if we keep this.

2024-03-20 20:42 UTC, estelle commented on files/en-us/web/html/element/select/index.md
> +section#custom div.select datalist div.option:checked {
```suggestion
.select datalist .option:hover,
.select datalist .option:focus,
.select datalist .option:checked {
```
this is not your doing, but it is not good code. Datalists generally only contain options, though the spec reads "Either: [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2).
    Or: Zero or more [option](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element) and [script-supporting](https://html.spec.whatwg.org/multipage/dom.html#script-supporting-elements-2) elements." 
    
My preference is to get rid of this entire example. If we keep it, we should create a component `<template>`, `<slot>`, etc.If we do keep it, the CSS selectors all needs to edited down.

2024-03-21 01:05 UTC, estelle commented on files/en-us/web/html/element/select/index.md
> +section#custom div.select datalist div.option:checked {
We can now style select with CSS (no JS). See https://codepen.io/5t3ph/pen/MWyyYNz

2024-03-21 09:40 UTC, chrisdavidmills commented
@estelle thanks for your review. I've accepted all your changes — it is good to further improve on those selectors.

As for what to do next — I don't have time to significantly rewrite the example to use web components, and I don't want to delete the example either. Flawed as it is, I think it is still useful to some degree. I also feel that I have fixed the issue that was filed, and these suggestions are out of scope for it.

2024-03-21 18:48 UTC, estelle approved these changes

2024-03-21 18:48 UTC, merged