Autocomplete: add section-*
mdn/content pull request #32789
Opened 2024-03-21 21:12 UTC by estelle

Added information about the `section-*` token of the autocomplete attribute.
rearranged stuff to enable a "description" since the description was longer than an intro statement.
we need to document everything , but I did NOT add an example in this PR as this use case is rare and i just wanted to get this missing feature added.

2024-03-22 08:21 UTC, chrisdavidmills requested changes
Generally fine, just a few bits for you to look at. Nice work, @estelle!

2024-03-22 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +Some tokens may be used more than once with potentially different expected values, such as the `zip code` token in a form that contains both shipping and billing addresses. By including multiple toke
```suggestion
Some tokens may be used more than once with potentially different expected values, such as the `zip-code` token in a form that contains both shipping and billing addresses. Including multiple different tokens in a space-separated list causes the associated form controls to be given unique autocomplete values: in this case, `autocomplete="shipping zip-code"` and `autocomplete="billing zip-code"`.
```

2024-03-22 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +The source of the suggested values is generally up to the browser; typically values come from past values entered by the user, but they may also come from pre-configured values. For instance, a brows
```suggestion
The source of the suggested values is generally up to the browser; typically values come from past values entered by the user, but they may also come from pre-configured values. For instance, a browser might let the user save their name, address, phone number, and email addresses for autocomplete purposes. The browser may also offer the ability to save encrypted credit card information, for autocompletion following an authentication procedure.
```

2024-03-22 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +Some autocomplete values may need to be re-used multiple times. For example, a form may contain multiple shipping addresses and therefore multiple occurrences of `"shipping zip-code"` while still exp
```suggestion
Some autocomplete values may need to be re-used multiple times. For example, a form may contain multiple shipping addresses and therefore multiple occurrences of `"shipping zip-code"` while still expecting different values. In these cases, the first token in the space-separated list of tokens can be a `section-*` token. This token's first eight characters are always the string "section-", followed by a unique alphanumeric string chosen by the developer. All form fields given the same `section-*` token belong to a **named group**, and will therefore share the same autocomplete values.

 > **Note:** `section-*` values are matched case-insensitively. For example, `section-group1` denotes the same named group as `SECTION-GROUP1`.
```

2024-03-22 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +Some autocomplete values may need to be re-used multiple times. For example, a form may contain multiple shipping addresses and therefore multiple occurrences of `"shipping zip-code"` while still exp
I'm not sure whether any of this is correct, but this is more the kind of complete explanation I'd hope for. A short example to show what a couple of fields in the same named group look like would also be quite helpful.

Feel free to correct and revise as makes sense ;-)

2024-03-22 08:21 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +- "`section-*`"
The description here is fine, but in general, something feels off to me about this list of tokens. They are at the same level in the list as "off" and "on", but they are not complete values at the same level as those. They should be one level deeper, underneath a top-level description of "space-separated token list", or similar.

2024-03-23 02:41 UTC, estelle reviewed
@chrisdavidmills  thanks for the review. updated everything.

2024-03-23 02:41 UTC, estelle commented on files/en-us/web/html/attributes/autocomplete/index.md
> +- "`section-*`"
I don't like the look, but i created nested DLs

2024-03-23 12:53 UTC, chrisdavidmills commented on files/en-us/web/html/attributes/autocomplete/index.md
> +- "`section-*`"
The look of the nested DLs is never the greatest, but I do think this is easier to follow and makes more sense. Nice work.

2024-03-23 12:54 UTC, chrisdavidmills approved these changes
@estelle lovely, lovely, lovely.

2024-03-23 12:54 UTC, merged