fix: Add width, height attrs to canvas element
mdn/content pull request #32801
Opened 2024-03-22 15:09 UTC by bsmth

### Description

The canvas element had no width and height attributes applied, so it was looking a little broken. This PR adds them in to the live sample so it looks a little better:

```diff
-<canvas></canvas>
+<canvas width="680" height="380"></canvas>
```

The defaults are 150 x 300: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#attributes

### Motivation

Reader reports a strange-looking example.

### Related issues and pull requests

Fixes #31288

2024-03-22 18:18 UTC, wbamberg commented
I think this is another regression caused by the fact that the Playground loads content after `DOMContentLoaded` is fired, which should be fixed by https://github.com/mdn/yari/pull/10770.

You can see that the code sets canvas width and height inside the `DOMContentLoaded` event handler: https://github.com/mdn/content/blob/0a3268bf8ed20aac552104db23e6be8efd06082c/files/en-us/learn/javascript/building_blocks/looping_code/index.md?plain=1#L72-L75, and that the page used to work: https://web.archive.org/web/20230323062429/https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code.

So this page ought to not need this fix once https://github.com/mdn/yari/pull/10770 percolates, and that seems like a better fix since it's not hardcoding the size.

2024-03-22 18:18 UTC, wbamberg requested changes
See https://github.com/mdn/content/pull/32801#issuecomment-2015664132, I'm not sure this fix is needed.

2024-03-22 18:30 UTC, bsmth commented
Nice, thanks for checking, let me close for now and we can check if the Yari fix resolved it 👍

2024-03-22 18:30 UTC, closed without merging

2024-04-16 21:55 UTC, wbamberg commented
No, the Yari PR does not seem to have fixed the regression :(

2024-04-19 19:07 UTC, wbamberg commented
It is partly fixed by that PR. The canvas does occupy the whole iframe now, but actually it is a little _too_ big, so we get scrollbars:

<img width="783" alt="Screen Shot 2024-04-19 at 12 07 09 PM" src="https://github.com/mdn/content/assets/432915/93be8f68-fab3-4095-8ca4-61617b7f5dbe">