Fix outdated use of @font-face in "Learn to style HTML using CSS -> Web fonts"
mdn/content pull request #3283
Opened 2021-03-18 20:35 UTC by mireille-raad

The font face usage on  [this link](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts) is outdated. This PR fixes #2837 and #3006 . If accepted, I will submit another fix to [this code](https://github.com/mdn/learning-area/blob/master/css/styling-text/web-fonts/web-font-finished.css) in the learning area.

**Main Changes**
- WOFF/WOFF2 is supported by all major browsers. This PR simplifies the docs, removes EOT, SVG and TTF snippets from the code but keeps a reference for how to get them in the Fontsquirrel Generator.
- Fontsquirrel no longer generates the EOT,SVG and TTF files, update the docs accordingly (screenshots at the end).

**Modified file**: files/en-us/learn/css/styling_text/web_fonts/index.html

**Useful links**: https://www.w3.org/TR/WOFF2/ 

**Fontsquirrel screenshots**
<img width="228" alt="Screen Shot 2021-03-18 at 12 56 16 PM" src="https://user-images.githubusercontent.com/521705/111694099-0d9d0c00-87f7-11eb-9201-730f5ca10b0d.png">

2021-03-30 09:26 UTC, rachelandrew requested changes
Hi - apologies for the delay on this. It all looks good, just a couple of little nits. You mentioned you would also update the files for the learning area. It would be good if we merge the two together so they would be correct :)

2021-03-30 09:26 UTC, rachelandrew commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> +     WOFF2 supports the entirety of the TrueType and OpenType specifications, including Variable fonts, Chromatic fonts, and font Collections.
```suggestion
     WOFF2 supports the entirety of the TrueType and OpenType specifications, including variable fonts, chromatic fonts, and font collections.
```

2021-03-30 09:26 UTC, rachelandrew commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> + <li><code>src</code>: These lines specify the paths to the font files to be imported into your CSS (the <code>url</code> part), and the format of each font file (the <code>format</code> part). The l
```suggestion
 <li><code>src</code>: These lines specify the paths to the font files to be imported into your CSS (the <code>url</code> part), and the format of each font file (the <code>format</code> part). The latter part in each case is optional, but it is useful to declare it because it allows browsers to find a font they can use faster. Multiple declarations can be listed, separated by commas. As the browser will search through them and use the first one it can find that it understands, it is best to put newer, better formats like WOFF2 earlier on.</li>
```

2021-03-30 15:10 UTC, mireille-raad commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> +    The order in which you include font files is important. If you provide the browser with multiple options as to which font file to download, it will choose the first one it is able to use. That's
thank you, this is much clearer now 😄

2021-03-30 16:02 UTC, mireille-raad commented
@rachelandrew no worries at all. There are tons of Pull Requests and issues to deal with. Thanks for reviewing. 

I submitted the other PR for https://github.com/mdn/learning-area/pull/355 , if you or @sideshowbarker want to take a look.

2021-04-02 16:07 UTC, rachelandrew approved these changes
Great - and I can see the other has been merged too :)

2021-04-02 16:08 UTC, merged

2021-04-02 16:08 UTC, rachelandrew commented
thank you!