Fix 32619: clarify font-weight descriptor
mdn/content pull request #32853
Opened 2024-03-27 03:30 UTC by wbamberg

Fixes https://github.com/mdn/content/issues/32619.

This is an attempt to improve the page on the [`font-weight`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight) descriptor. I think https://github.com/mdn/content/issues/32619 was fundamentally caused by the fact that this page isn't very clear about what the `font-weight` descriptor is, how it relates to the `font-weight` property, and how it is used. It includes stuff which is just wrong:

> The values for the CSS descriptor is same as that of its corresponding font property.

...and stuff which makes it sound like this is the page for the property:

> The font-weight property is described using any one of the values listed below.

I've rewritten the description and syntax sections, more or less, and added two live samples that I hope show how this can actually be used. I have left the bit about variable font values 

I'm no expert here so might have mangled things. I do think though that this documentation could be improved. I think we should probably have glossary entries for font, font face, typeface. We should probably have a proper guide to using `@font-face` - [this](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts) is the only thing I could find and it's very basic. And if these changes or something like them are good, we should probably do something similar with the other descriptors.

2024-03-27 03:36 UTC, wbamberg commented
Oh, the live samples don't work, maybe because preview is broken? Sorry, you might need to test this locally.

2024-03-27 17:29 UTC, wbamberg commented
@bsmth , I know you care about the repo size, and this PR adds some sample fonts to the repo, and one of them at least is quite big (127K). There was some chat before about having a separate repo for assets that live samples could refer to. That still feels like the proper solution. Do you know what the status of this is? I see https://github.com/mdn/shared-assets exists, can it be referenced from live samples in mdn/content?

2024-04-02 11:56 UTC, bsmth commented
> @bsmth , I know you care about the repo size, and this PR adds some sample fonts to the repo, and one of them at least is quite big (127K). There was some chat before about having a separate repo for assets that live samples could refer to. That still feels like the proper solution.

Yes, that was the idea, indeed.

> Do you know what the status of this is? I see https://github.com/mdn/shared-assets exists, can it be referenced from live samples in mdn/content?

This can't be used yet, my hope was that it would be added to a GCP bucket that we could reference like `demo-assets.developer.mozilla.org` or something along those lines. I'm going to check again what the status is shortly and I'll come back to this PR with some info.

2024-04-02 16:04 UTC, bsmth commented
Hey @wbamberg - quick update to get something going in the meantime: I've enabled gh-pages for the assets repo in https://github.com/mdn/shared-assets/pull/8

This allows you to use the fonts from that repo and add your own if you need different ones. The examples cleanup work we'll be doing later in the year will likely consider this assets repo and have more robust deployment, but that should unblock you for now (although we may need a CSP entry for `mdn.github.io/shared-assets`)

2024-04-03 06:52 UTC, estelle requested changes
Sorry it took so long to review. I was having issues getting the example to work locally, before realizing i had a typo!

font descriptors are rarely well covered. I've seen 9 different font-family names with 9 different font weights, with the font-family  declared  every single time a font-weight was included, adding about 800 lines to the CSS. In production! This entry can prevent that. I included a good deal of feedback via text suggestions. Please don't feel like you need to use my wording, but please do include the content I am trying to convey. Thank you for writing this.

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +In this example we include a variable font, ["Montserrat"](https://fonts.google.com/specimen/Montserrat), using a single `@font-face` at-rule. We've used a `font-weight: 300 700` value to effectively
```suggestion
In this example we include a variable font, ["Montserrat"](https://fonts.google.com/specimen/Montserrat), using a single `@font-face` at-rule. We've used a `font-weight: 300 700` value to effectively limit the range of weights for which this font will be used. If a CSS rule includes "Montserrat" as its first declared `font-family`, but the `font-weight` property value is outside of the weight range specified by the `font-weight` descriptor, the next font in the `font-family` list will be used, as the `Monserrat` font is clamped to the limited range specified by the descriptor.
```
this is what we want to say, though this might not be exactly how you want to say it.

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +To show the effect of this we've included another font using "Montserrat" that does not set the `font-weight` descriptor, and we've called this "Montserrat-complete".
do you want to change the value to `auto`?

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-size: 2rem;
```suggestion
  font-size: 2rem;
  font-family: "Montserrat", "Montserrat-complete", serif;
```

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +<p class="four">Montserrat-complete, font-weight 900</p>
```suggestion
<p class="one">font-weight 200</p>
<p class="two">font-weight 400</p>
<p class="three">font-weight 600</p>
<p class="four">font-weight 800</p>
```

If we change to this, the two middle ones will be Monserrat and the first and list will be M-Complete. If we do this, however, we may want to use two very different fonts so the reader can quickly see that the middle two are different from the first and last. It is also how developers should be using `@font`; though most don't because font descriptors are rarely fully explained. In other words, I am super glad we are writing this!!!!!

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +}
```suggestion
p.one {
  font-weight: 100;
}

p.two {
  font-weight: 900;
}

p.three {
  font-weight: 100;
}

p.four {
  font-weight: 900;
}
```

2024-04-03 06:52 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +- Setting the `font-weight` property to `900` for "Montserrat-complete" gets a weight of 900.
```suggestion
- Setting the `font-weight` property to `200` for "Montserrat-complete" gets a weight of 200.
- Setting the `font-weight` property to `400` for "Montserrat" gets a weight of 400.
- Setting the `font-weight` property to `600` for "Montserrat" gets a weight of 600.
- Setting the `font-weight` property to `800` for "Montserrat-complete" gets a weight of 800.
```

2024-04-04 03:13 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-weight: bold;
I don't understand this comment.

>  it's the default action expected of "font-weight: bold;"

I'm not sure what "the default action" means here. Like, if you don't set the font-weight descriptor, like this:

```css
@font-face {
  font-family: "Karantina";
  src: url("Karantina-Regular.woff2");
}

@font-face {
  font-family: "Karantina";
  src: url("Karantina-Bold.woff2");
}

body {
  font-family: "Karantina", serif;
  font-size: 3rem;
}

p.one {
  font-weight: normal;
}

p.two {
  font-weight: bold;
}
```

...then both paras and the `<strong>` will select "Karantina-Bold" because that's matched last (I think). The browser will also apply synthetic boldification to para 2 and the `<strong>`:

<img width="602" alt="Screen Shot 2024-04-03 at 8 03 40 PM" src="https://github.com/mdn/content/assets/432915/e3b45e63-71ba-48ce-8442-00726e243b2c">

It's only because we've set the `font-weight` descriptor that:
- para 1 selects "Karantina-Regular",
- para 2 and the `<strong>` select "Karantina-Bold" don't apply synthetic boldification
... and we get proper typography:

<img width="679" alt="Screen Shot 2024-04-03 at 8 05 16 PM" src="https://github.com/mdn/content/assets/432915/47233fd0-9e58-4842-ba71-dd87ebe5648e">

That's what this example is showing: by setting the font-weight descriptor, you enable a rule to select the appropriate font file by setting the font-weight property.

At least such is my understanding.

2024-04-04 18:17 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-weight: bold;
Everything you wrote is correct. The issue is that the user will not be able to see a difference between a synthetic bold and the use of the actual bold font. 

I found this old example I wrote that barely works, but explains what I mean. At https://estelle.github.io/CSS/fonts/index.html#slide60 (slide 60 if the presentation doesn't actually move forward), if you change the font-weight in the `p.fwd` block to 700, you'll note the font family changes. The deck is old, and i had all the other fonts on my local machine when i did the presentation, so only the boldest font will work on your device. In that CSS, all the `@font` declarations are using the same `font-family` descriptor, but include different `font-weight` values and import complete different fonts. That was the user can see that a different font file is being used when the font-weight leads to different font-files used to render content. This is obviously not something one would do in production, but it enables the learner to really see what is going on.

In the current example on this page, the example will still be bold (or light) if the fonts don't even load. Yes, the second paragraph and the `<strong>` select `"Karantina-Bold"` and don't apply a synthetic a bold because we say so, but is it really just applying a synthetic bold? If we use drastically different fonts for normal v. bold in our `@font` `src` descriptor, the user will definitely see the effect. My suggestion was to invert bold and normal to show the difference, but drastically different fonts would be better (as it would be less confusing that "messing up" and explaining it)

2024-04-04 18:39 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-weight: bold;
I think this example should show the actual proper common usage of the font-weight descriptor to support multiple fonts in the same family, which is what it currently does. It implies "this is a good-practice way to use font-weight, if you're not using variable fonts". That's why I don't think we should change it to show something unrealistic, even if it is more illustrative.

I do agree that the counterfactual is not that clear, and that font synthesis makes the story more complicated. It might help to:

(a) find a font family that has a clearer differentiation between bold and normal weight
(b) maybe talk about the counterfactual (and even show it in the example) to explain what is happening (and that it is in fact broken)

That would make the example quite complex. I think one underlying problem here is that a lot of this explanation would go into a guide page, and because we don't have one, it is having to go here instead.

But I do think it is important for the first example here to show an actual good practice usage. Otherwise people have to infer it from unrealistic examples, and that's also putting a burden on them.

2024-04-04 23:31 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-weight: bold;
All valid points. We really do need a font guide!

We can leave as is, but I did think of other options. Sharing in case you want to include one of them:

1) Duplicating the first example as a second example, and just inverting the bold / normal descriptors, with something like "This example "accidentally" inverts the `font-weight` descriptors, leading to a bold font being rendered when the `font-weight` property is `normal` and a normal font is rendered when the property is `bold`.

2) including 3 katerina fonts, serving 'light' up to 500, regular from 501 to 700, and bold 701 and above (though this would be for the numeric example after this one)

3)  in the numeric example, leaving gaps, so fallback font-family is used below 200 and above 800 or something similar.

2024-04-08 08:59 UTC, bsmth commented on files/en-us/web/css/@font-face/font-weight/Karantina-Bold.woff2
Just a reminder you can use any of these instead of landing the assets in the content repo:

https://github.com/mdn/shared-assets/tree/main/fonts

i.e., https://mdn.github.io/shared-assets/fonts/FiraSans-Light.woff2

2024-04-10 02:51 UTC, wbamberg commented on files/en-us/web/css/@font-face/font-weight/Karantina-Bold.woff2
OK, now we're using Fira Sans and League Mono!

2024-04-13 01:17 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +}
We want to show that you can use a series of fonts and the browser will select the most appropriate font for the job. We want users to see using a font family list, and not having to declare a font family every time a font-weight is changed. Hence, my recommendation is to change the  example so all paragraphs use the same font-family declaration, demonstrating that when the font-weight property value is withing the range of font-weight descriptor, that font will be used. In this case, 2 and 3 will get league mono and 1 and 4 will get league mono complete.

```suggestion
p {
  font-family: "League Mono", "League Mono-complete", serif;
  font-size: 1.5rem;
}

p.one {
  font-weight: 200;
}

p.two {
  font-weight: 400;
}

p.three {
  font-weight: 600;
}

p.four {
  font-weight: 800;
}
```

2024-04-13 01:19 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +<p class="four">League Mono-complete, font-weight 900</p>
```suggestion
<p class="one">League Mono-complete, font-weight 200</p>
<p class="two">League Mono, font-weight 400</p>
<p class="three">League Mono, font-weight 600</p>
<p class="four">League Mono-complete, font-weight 800</p>
```

2024-10-11 00:34 UTC, wbamberg commented
Sorry @Josh-Cena . I will attempt to remember what's going on here.

2024-10-29 20:35 UTC, estelle reviewed
I am breaking things

2024-10-29 20:35 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +<strong>Fira Sans, default weight &lt;strong&gt; element</strong>
```suggestion
<p><strong>Fira Sans, default weight &lt;strong&gt; element</strong></p>
```

2024-10-29 20:35 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  src: url("https://mdn.github.io/shared-assets/fonts/LeagueMono-VF.ttf");
```suggestion
  font-family: "League Mono-complete";
  src: url("https://mdn.github.io/shared-assets/fonts/LeagueMono-VF.ttf");
```
```suggestion
@font-face {
  font-family: "FireSans";
  src: url("https://mdn.github.io/shared-assets/fonts/FiraSans-Regular.woff2");
```

Use a completely different font for fonts outside of 300 to 700 so people can see that a different font was actually used.

2024-10-29 20:35 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +  font-family: "League Mono", "League Mono-complete", serif;
```suggestion
  font-family: "League Mono", "FireSans", serif;
```

2024-10-29 20:35 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +- Setting the `font-weight` property to `900` for "League Mono-complete" gets a weight of 900.
```suggestion
- Setting the `font-weight` property to `200` gets a `normal` version of FireSans.
- Setting the `font-weight` property to `400` gets "League Mono" at a weight of 400.
- Setting the `font-weight` property to `600` gets "League Mono" at a weight of 600.
- Setting the `font-weight` property to `800` gets a boldened version of "FireSans".
```

2024-10-29 20:41 UTC, estelle commented on files/en-us/web/css/@font-face/font-weight/index.md
> +@font-face {
```suggestion
```

2024-11-22 20:20 UTC, wbamberg commented
Closing in favour of https://github.com/mdn/content/pull/36686

2024-11-22 20:20 UTC, closed without merging