32662 enable align content
mdn/content pull request #32862
Opened 2024-03-27 15:21 UTC by dletorey

### Description

- Updated the content to reflect `align-content` inn`display: block;` 
- Updated the example to include display block
- Reordered the syntax and removed explantions to remove duplication

### Motivation

Working on [Issue 32662](https://github.com/mdn/content/issues/32662)

### Related issues and pull requests

- Firfox release not PR - coming soon
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/22702)
- [Data PR](https://github.com/mdn/data/pull/721)

2024-03-27 23:59 UTC, estelle requested changes
I started the review. I am having issues with the example, so will create a Codepen for you with a proposed solution. But will do that tomorrow.

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +The [CSS](/en-US/docs/Web/CSS) **`align-content`** property sets the distribution of space between and around content items along a [flexbox](/en-US/docs/Web/CSS/CSS_flexible_box_layout)'s [cross-axi
We need to add block, and possibly multi-col to BCD

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +### align-content switcher
```suggestion
```
Only one example, so we can use "examples" in the Embed live sample, and not have this title

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +In this example you can switch between the different layouts flex, grid, and block. You can also switch between the different values for `align-content`.
```suggestion
In this example, you can switch between three different {{cssxref("display")}} property values, includ `flex`, `grid`, and `block`. You can also switch between the different values for `align-content`.
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +</section>
```suggestion
<section>
  <div class="olive"></div>
  <div class="coral"></div>
  <div class="deepskyblue"></div>
</section>
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +<section class="controls">
```suggestion
<fieldset class="controls">
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +  </section>
```suggestion
  </fieldset>
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +    <h2>Controls</h2>
```suggestion
    <legend>Controls</legend>
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +#outer {
```suggestion
section {
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +#inner {
```suggestion
section div {
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +const container = document.querySelector("#outer");
```suggestion
const container = document.querySelector("section");
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +    </p>
```suggestion
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +};
```suggestion
```
Let's make the note alwasy visible under the results as people should be told this and it should be searchable

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +{{EmbedLiveSample("align-content_switcher", 260, 310)}}
```suggestion
{{EmbedLiveSample("Examples", 260, 310)}}

In [block layout](en-US/docs/Web/CSS/CSS_box_alignment/Box_alignment_in_block_abspos_tables#align-content_and_justify-content), child elements are treated as a single element, meaning `normal` behaves differently.
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +  hideNote(alVal, display.value);
```suggestion
```

2024-03-27 23:59 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +  hideNote(values.value, dVal);
```suggestion
```

2024-03-28 05:52 UTC, estelle commented
> I started the review. I am having issues with the example, so will create a Codepen for you with a proposed solution. But will do that tomorrow.

https://codepen.io/estelle/pen/JjVymym

2024-04-02 15:19 UTC, dletorey commented on files/en-us/web/css/align-content/index.md
>  ## Formal definition
This is referenced in the data repo https://github.com/mdn/data/pull/721/files which I have updated and waiting for this to be approved.

2024-04-03 08:38 UTC, estelle reviewed
a few more edits

2024-04-03 08:38 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +  display: block;
```suggestion
```
we're using `js.style`, rather than class changes, so this CSS isn't used

2024-04-03 08:38 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +@layer pageSetUp {
the layer in the codepen was my way of saying "hidden". you can keep it, but it may confuse people so i would delete this line and the closing on line 172

2024-04-03 08:38 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +} */
these were options to play with. delete, but suggesting adding these lines in the "results" section might be good

2024-04-03 08:38 UTC, estelle commented on files/en-us/web/css/align-content/index.md
> +In [block layout](/en-US/docs/Web/CSS/CSS_box_alignment/Box_alignment_in_block_abspos_tables#align-content_and_justify-content), child elements are treated as a single element, meaning `space-between
```suggestion
In [block layout](/en-US/docs/Web/CSS/CSS_box_alignment/Box_alignment_in_block_abspos_tables#align-content_and_justify-content), child elements are treated as a single element, meaning `space-between`, `space-around`, and `space-evenly` behave differently.
```

2024-04-03 10:01 UTC, dletorey commented on files/en-us/web/css/align-content/index.md
> +} */
I just removed this as, to me, it doesn't make sense when having the `flex-wrap` property.

2024-04-03 10:01 UTC, dletorey commented on files/en-us/web/css/align-content/index.md
> +@layer pageSetUp {
Done

2024-04-03 18:10 UTC, estelle approved these changes

2024-04-03 18:10 UTC, merged