Update dnt/index.md to mention GPC
mdn/content pull request #32875
Opened 2024-03-28 23:00 UTC by andrew-aitchison

### Description

Do Not Track is obsolete. Mention the successor standard Global Privacy Control

### Motivation

This will make it easier for users to find a replacement for the obsolete feature which the page describes.

### Additional details

This change includes links giving context.

### Related issues and pull requests

None.

2024-03-28 23:53 UTC, wbamberg requested changes
Thank you @andrew-aitchison !

2024-03-28 23:53 UTC, wbamberg commented on files/en-us/web/http/headers/dnt/index.md
> +Use **`GPC`** (**G**lobal **P**rivacy **C**ontrol) instead.
```suggestion
DNT is deprecated in favor of [Global Privacy Control](https://globalprivacycontrol.org/), which is communicated using the {{HTTPHeader("Sec-GPC")}} header.
```

2024-03-29 10:12 UTC, andrew-aitchison commented on files/en-us/web/http/headers/dnt/index.md
> +Use **`GPC`** (**G**lobal **P**rivacy **C**ontrol) instead.
I'm happy with your first clause, up to the comma.
The Sec-GPC header is used to communicate with a remote web-server, but client-side scripts check navigator.globalPrivacyControl. Do we wish to put that much detail in the preamble ?

2024-03-29 17:11 UTC, wbamberg commented on files/en-us/web/http/headers/dnt/index.md
> +Use **`GPC`** (**G**lobal **P**rivacy **C**ontrol) instead.
The reason I only mentioned Sec-GPC is that this is the reference page for the DNT header, so the replacement is Sec-GPC. We could say:

> DNT is deprecated in favor of [Global Privacy Control](https://globalprivacycontrol.org/), which is communicated to servers using the {{HTTPHeader("Sec-GPC")}} header.

...but I would also be OK with something like:

> DNT is deprecated in favor of [Global Privacy Control](https://globalprivacycontrol.org/), which is communicated to servers using the {{HTTPHeader("Sec-GPC")}} header, and accessible to clients from {{domxref("navigator.globalPrivacyControl")}}.

2024-03-30 12:49 UTC, andrew-aitchison commented on files/en-us/web/http/headers/dnt/index.md
> +Use **`GPC`** (**G**lobal **P**rivacy **C**ontrol) instead.
I'd forgotten that this is a page describing a header. I'm happy with your last version.

Can you take it from here, or do I need to make a new pull request ?

2024-03-30 14:42 UTC, wbamberg commented on files/en-us/web/http/headers/dnt/index.md
> +Use **`GPC`** (**G**lobal **P**rivacy **C**ontrol) instead.
Thank you @andrew-aitchison , and yes, I can take if from here.

2024-03-30 14:42 UTC, wbamberg approved these changes
👍 thank you @andrew-aitchison !

2024-03-30 14:42 UTC, merged