Remove suggestion that order of table elements isn't important
mdn/content pull request #32909
Opened 2024-04-01 08:47 UTC by Mallonbacka

### Description

As stated in the related issue, the suggestion that `<thead>`, `<tfoot>` and `<tbody>` can be given in any order as children of a `<table>` deviates from the HTML spec, and causes the presentation to screen reader users to deviate from the visual structure, at least on one browser/AT combination. 

### Motivation

While it makes no difference most of the time, there is a case where this practice can be observed causing problems for a small set of assistive technology users. Since the practice deviates from the HTML spec, this also ensures that what MDN recommends to readers follows the specification.

I also found line 72 unclear, as it seemed to conflict with the prior content on line 71 - if the body can appear below the footer, how does the footer always appear at the bottom? I've removed the unclear part, so that the order (according to the specification) is unambiguous - `<thead>`, `<tbody>`, `<tfoot>`.

### Additional details

- [`<table>` in the HTML standard, with the relevant section highlighted](https://html.spec.whatwg.org/multipage/tables.html#the-table-element:~:text=In%20this%20order,supporting%20elements.)

### Related issues and pull requests

Fixes #32798

2024-04-01 09:53 UTC, chrisdavidmills requested changes
Hi there @Mallonbacka, and thanks so much for your contribution to MDN! I totally agree with the motivation for making this change, and I think your suggestions work well. I've just got one wording suggestion for you to consider, after which we can get it merged.

2024-04-01 09:53 UTC, chrisdavidmills commented on files/en-us/learn/html/tables/advanced/index.md
> +- The `<tfoot>` element needs to wrap the part of the table that is the footer — this might be a final row with items in the previous rows summed, for example. The table footer should be the last ele
I found "if you have one" slightly jarring and confusing. How about:

```suggestion
- The `<tfoot>` element needs to wrap the part of the table that is the footer — this might be a final row with items in the previous rows summed, for example. If included, the table footer should be the last element inside the table.
```

2024-04-01 11:07 UTC, Mallonbacka commented on files/en-us/learn/html/tables/advanced/index.md
> +- The `<tfoot>` element needs to wrap the part of the table that is the footer — this might be a final row with items in the previous rows summed, for example. The table footer should be the last ele
Thanks @chrisdavidmills 

This is a good suggestion, I'm happy to accept it.

2024-04-02 02:08 UTC, ferdnyc commented on files/en-us/learn/html/tables/advanced/index.md
> +- The `<tbody>` element needs to wrap the other parts of the table content that aren't in the table header or footer.
Would it be better to document `<thead>`, `<tbody>`, `<tfoot>` in that order, since that's now being prescribed as the order in which they should appear in the source? The copy for `<tbody>` would probably have to be reworded some, since it's not the last item on the list and can't rely on simply, "...and this is everything else", but I think it would still make the documentation flow more logically if the elements were documented in the same order they should be used.

2024-04-02 05:11 UTC, Mallonbacka commented on files/en-us/learn/html/tables/advanced/index.md
> +- The `<tbody>` element needs to wrap the other parts of the table content that aren't in the table header or footer.
Thanks for the suggestion. This is a good idea - I had originally focused on just removing the problematic claim, but I don't mind making some more involved changes. I'll add a commit here which does that.

2024-04-02 07:13 UTC, chrisdavidmills approved these changes
This is looking great, thanks @Mallonbacka! I just made one tiny change, and now I think we are ready to merge.

2024-04-02 07:13 UTC, merged