Document Compute Pressure API
mdn/content pull request #32923
Opened 2024-04-02 10:25 UTC by Elchi3

### Description

This pull request documents the [Compute Pressure API](https://w3c.github.io/compute-pressure/).

Technical reviewers: @kenchris, @arskama 

### Additional details

This PR creates the following pages:
- Overview page for the Compute Pressure API
- Reference pages: PressureObserver, PressureRecord, compute-pressure permission policy directive.

A more hands-on "Using the Compute Pressure API" guide page could be added in a follow-up PR.

### Related issues and pull requests

- BCD: https://github.com/mdn/browser-compat-data/pull/22687

2024-04-02 10:58 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +The **Compute Pressure API** is a JavaScript API that enables you observe the pressure of system resources such as the CPU.
to observe

2024-04-02 11:00 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +In real-time applications, such as video conferencing web apps, the Compute Pressure API lets you detect if the system is under unmanageable stress. It notifies you of high-level pressure state chang
It also allows you to detect still managable stress, so maybe we should reword. Obviously the system will do the best to handle stress on the system, but there is only so much it can do, so collaboration between system and app is quite useful

2024-04-02 11:02 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +You can use these pressure change signals, for example, to reduce or increase the video quality or the number of video feeds shown simultaneously to avoid dropping video frames, audio cuts, or delayi
It might be worth mentioning that this pressure can be external from the system and other apps so it might come at unexpected times, like turbulence in an airplane. It can be compared to network pressure which many streaming services adapt to

2024-04-02 11:03 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +- Web games, for which you could balance the quality and amount of 3D assets.
you could change the framerate, resolution, depth of field etc, to ensure low latency and stable frame rate

2024-04-02 11:03 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +- User interfaces, for which you could render placeholders instead of real data while the system is under pressure, and render the real content once the pressue has eased.
pressue => pressure

2024-04-02 11:09 UTC, arskama commented on files/en-us/web/api/compute_pressure_api/index.md
> +In real-time applications, such as video conferencing web apps, the Compute Pressure API lets you detect if the system is under unmanageable stress. It notifies you of high-level pressure state chang
"unmanageable" is "critical" state, 3 other levels of stress are available and manageable.

2024-04-02 12:49 UTC, Elchi3 commented on files/en-us/web/api/compute_pressure_api/index.md
> +In real-time applications, such as video conferencing web apps, the Compute Pressure API lets you detect if the system is under unmanageable stress. It notifies you of high-level pressure state chang
Reworded

2024-04-02 12:51 UTC, Elchi3 commented on files/en-us/web/api/compute_pressure_api/index.md
> +- `"thermals"` represents the global thermal state of the system. This state can be affected by other apps and sites than the observing site.
Do you think it would be better to remove thermals for now? The text says that this is in spec for now and advertises to always use the static PressureObserver.supportedSources property to be sure.

2024-04-03 08:34 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +- `"thermals"` represents the global thermal state of the system. This state can be affected by other apps and sites than the observing site.
I think it is fine with it then if we list it as unsupported in the browser support section

2024-04-03 08:36 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +Additional source types, such as `"gpu"` might be supported in the future. Use the static {{domxref("PressureObserver.supportedSources_static", "PressureObserver.supportedSources")}} property to see
Maybe reword this so that people will use this today, given thermals above.

Like, check supportedSources for what sources are supported on a given system as availability can vary by your user agent, your operating system, and your hardware, so be sure to check this. Additional source types, such as `"gpu"` might be supported in the future.

2024-04-03 09:27 UTC, tomayac reviewed
Just left a couple of comments. Looks pretty good already, thanks for documenting this!

2024-04-03 09:27 UTC, tomayac commented on files/en-us/web/api/compute_pressure_api/index.md
> +In real-time applications, such as video conferencing web apps, the Compute Pressure API lets you detect which pressure the system is currently facing. The system will handle any stress as best as it
```suggestion
In real-time applications, such as video conferencing web apps, the Compute Pressure API lets you detect which pressure the system is currently facing. The system will handle any stress as well as it can, but a collaboration between system and app is useful to handle the pressure best. This API notifies you of high-level pressure state changes, so you can adjust your workloads and still offer a pleasant user experience. The signal is proactively delivered when the system pressure trend is either rising or easing to allow timely adaptation.
```

2024-04-03 09:27 UTC, tomayac commented on files/en-us/web/api/compute_pressure_api/index.md
> +- Web games, for which you could balance the quality and amount of 3D assets, change the framerate, resolution, depth of field etc, to ensure low latency and stable frame rate.
```suggestion
- Web games, for which you could balance the quality and amount of 3D assets, change the framerate, resolution, depth of field etc., to ensure low latency and stable frame rate.
```

2024-04-03 09:27 UTC, tomayac commented on files/en-us/web/api/compute_pressure_api/index.md
> +Fast and delightful web applications should balance workloads when the system's computing resources are used at (near) full capacity. The Compute Pressure API's goal is to prevent, rather than mitiga
I was wondering how rAF mitigates? By triggering less frequently?

2024-04-03 09:27 UTC, tomayac commented on files/en-us/web/api/compute_pressure_api/index.md
> +The contributing factors (i.e. the underlying system metrics) for the pressure states above are not defined by the specification and can vary depending the underlying hardware and platform behavior.
```suggestion
The contributing factors (that is, the underlying system metrics) for the pressure states above are not defined by the specification and can vary depending on the underlying hardware and platform behavior. However, the specification requires that the change in contributing factors must be substantial to avoid flip-flopping between states. This means you can expect the API to not report different states overly often as they aren't responding to just one certain fluctuating system metric.
```

2024-04-03 09:27 UTC, tomayac commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +}
Should this example be complete, that is, show the `.observe()` part as well? Right now, it can't be pasted in the console for example.

2024-04-06 03:49 UTC, wbamberg requested changes
Thanks Florian!

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/unobserve/index.md
> +- `source`:
```suggestion
- `source`
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/unobserve/index.md
> +### Stopping to observe a specific source
```suggestion
### Stop observing a specific source
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +The **`disconnect()`** method of the {{domxref('PressureObserver')}} interface stops the pressure observer callback from receiving pressure records from any source and clears all pending records sinc
```suggestion
The **`disconnect()`** method of the {{domxref('PressureObserver')}} interface stops the pressure observer callback from receiving pressure records from all sources and clears all pending records since the callback was last invoked.
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +The **`disconnect()`** method of the {{domxref('PressureObserver')}} interface stops the pressure observer callback from receiving pressure records from any source and clears all pending records sinc
I don't understand "clears all pending records since the callback was last invoked". This seems to be a thing `disconnect()` does, that `unobserve()` does not do, but I don't know what it means really.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/index.md
> +  - : Stops the pressure observer callback from receiving pressure records from any source and clears all pending records since the callback was last invoked.
```suggestion
  - : Stops the pressure observer callback from receiving pressure records from all sources and clears all pending records since the callback was last invoked.
```

(but see also my comment in the `disconnect()` page about not understanding "clears all pending records since the callback was last invoked")

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +The following example collects 20 samples and then disconnects the pressure observer to disable receiving any more pressure records. The {{domxref('PressureObserver.takeRecords()')}} method is useful
```suggestion
The following example collects 20 samples and then disconnects the pressure observer to disable receiving any more pressure records. The {{domxref('PressureObserver.takeRecords()')}} method is used to store records before disconnecting.
```

maybe?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +    if (samples.length == 20) {
Is there a reason to use `==` here?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +      // read records before disconnecting and clearing all records
Why do we have to read them? We're not doing anything with them here (we can't, since `sampleRecords` will stop existing at the end of the block). So why are we doing this?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/observe/index.md
> +observe(source)
As already noted, this omits `options`.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/observe/index.md
> +A {{jsxref("Promise")}} that fulfills with {{jsxref("undefined")}}.
```suggestion
A {{jsxref("Promise")}} that fulfils with {{jsxref("undefined")}}.
```

US spelling I think.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +console.log(records[0].time);
This is unsafe if there are no records, right?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
So I believe that the observer callback doesn't remove records, right? So if the first time is is called, we have records 1,2,3, then it is called later with three more records, then that call will contain 1,2,3,4,5,6. Is that right?

And also that at any given time there might be records that have not been delivered yet (because the callback hasn't been invoked, right?

So are these the underlying reasons for this API? I think it would be nice to go into this a bit: why is this API provided and why might I want to call it.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/index.md
> +## Examples
Will there be an example?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/source/index.md
> +- `"cpu"` represents the average pressure of the central processing unit (CPU) across all its cores. This source is the CPU pressure for the thread the site is using, such as the main thread (window)
Just to be clear, it is _only_ the pressure on the thread in which _this observer_ is running. So if your web app is multithreaded you would need separate observers to get CPU notifications about the different threads.

If so, maybe rather than "the thread the site is using" we could say something like "the thread in which this observer is running"?

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/source/index.md
> +Additional source types, such as `"gpu"` might be supported in the future. Use the static {{domxref("PressureObserver.supportedSources_static", "PressureObserver.supportedSources")}} property to see
```suggestion
Use the static {{domxref("PressureObserver.supportedSources_static", "PressureObserver.supportedSources")}} property to see which source types are available. Availability can vary by your user agent, your operating system, and your hardware.
```

Just a suggestion, but IMO it's not useful to talk about what might happen in some future.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/source/index.md
> +The following example shows the use of the `source` property which you can log during pressure observation.
```suggestion
In the following example we log the value of the `source` property in the pressure observer callback.
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/state/index.md
> +The following example shows the use of the `state` property which you can log during pressure observation.
```suggestion
In the following example we log the value of the `state` property in the pressure observer callback.
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/time/index.md
> +The following example shows the use of the `time` property which you can log during pressure observation.
```suggestion
In the following example we log the value of the `time` property in the pressure observer callback.
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/time/index.md
> +The read-only **`time`** property returns the {{domxref("DOMHighResTimeStamp","timestamp", "", "no-code")}} recorded for a {{domxref("PressureRecord")}}. It corresponds to the time the data was obtai
I don't understand what the "time origin of the global object" is, or how to get it.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/api/compute_pressure_api/index.md
> +The Compute Pressure API is [policy-controlled](/en-US/docs/Web/HTTP/Permissions_Policy) by the token `"compute-pressure"`. Its default allowlist is `'self'` which allows usage in same-origin nested
```suggestion
The Compute Pressure API is [policy-controlled](/en-US/docs/Web/HTTP/Permissions_Policy) by the `"compute-pressure"` directive. Its default allowlist is `'self'` which allows usage in same-origin nested frames but prevents third-party content from using the feature.
```

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/http/headers/permissions-policy/compute-pressure/index.md
> +The default allowlist for `compute-pressure` is `*`.
https://pr32923.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Compute_Pressure_API#security_and_privacy_considerations says the default allowlist is `self`.

2024-04-06 03:49 UTC, wbamberg commented on files/en-us/web/http/headers/permissions-policy/compute-pressure/index.md
> +The HTTP {{HTTPHeader("Permissions-Policy")}} header `compute-pressure` directive controls access to the [Compute Pressure API](/en-US/docs/Web/API/Compute_Pressure_API).
I'm a bit puzzled though. I tried this API in Chrome on https://example.org/. I'm pretty sure https://example.org/ isn't sending the Permissions-Policy header.

I ran this in the console:

```js
function f() { console.log("hey")}
const p = new PressureObserver(f)
p.observe("cpu")
```

...and I don't see any security errors. Is this what I should expect?

2024-04-06 04:12 UTC, wbamberg commented on files/en-us/web/api/compute_pressure_api/index.md
> +The contributing factors (i.e. the underlying system metrics) for the pressure states above are not defined by the specification and can vary depending the underlying hardware and platform behavior.
If we accept the "just one" above (and I think we should) then we should also remove "certain" IMO.

2024-04-06 15:25 UTC, wbamberg commented on files/en-us/web/api/pressurerecord/source/index.md
> +### Using the source property
Oh also it's probably good to code-format `source` here (and similarly for `state` and `time` below):

```suggestion
### Using the `source` property
```

Personally I think code formatting in headings is ugly, but especially it helps l10n: https://github.com/orgs/mdn/discussions/271 so we should do it especially for common words like this.

2024-04-12 07:41 UTC, Elchi3 commented on files/en-us/web/api/compute_pressure_api/index.md
> +await observer.observe("cpu");
Yeah, removing the promise is being discussed: https://github.com/w3c/compute-pressure/issues/258. Feel free to add your thoughts

2024-04-12 07:47 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/pressureobserver/index.md
> +new PressureObserver(callback, options)
Yeah I will update this. It got moved last week. See https://github.com/w3c/compute-pressure/pull/261

2024-04-12 07:51 UTC, Elchi3 commented on files/en-us/web/api/pressurerecord/time/index.md
> +The read-only **`time`** property returns the {{domxref("DOMHighResTimeStamp","timestamp", "", "no-code")}} recorded for a {{domxref("PressureRecord")}}. It corresponds to the time the data was obtai
Yeah, discussion at https://github.com/w3c/compute-pressure/issues/257 I will try to write this up better and the implementation in Chrome will probably be updated as it confusingly uses Epoch timestamps.

2024-04-12 08:28 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/disconnect/index.md
> +{{APIRef("Compute Pressure API")}}{{SeeCompatTable}}
Ah thanks Will. I should have paid more attention to the recent discussions. I thought just on the interfaces is enough. Fixed in https://github.com/mdn/content/pull/32923/commits/4cebe7a144bc82009db301b2841ce18fe568d148 (in which I also fixed the banner for the worker availability).

2024-04-12 08:45 UTC, Elchi3 commented on files/en-us/web/api/compute_pressure_api/index.md
> +Fast and delightful web applications should balance workloads when the system's computing resources are used at (near) full capacity. The Compute Pressure API's goal is to prevent, rather than mitiga
That's what I thought, too. I read this in the explainer: https://github.com/w3c/compute-pressure?tab=readme-ov-file#prevent-instead-of-mitigate-bad-user-experiences. Maybe @kenchris can elaborate more on this so I can be more precise in the wording here.

2024-04-12 13:56 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/supportedsources_static/index.md
> +detectSupport(["cpu", "thermal", "gpu", "npu"]);
I ended up logging supported sources here which makes more sense imo.

2024-04-12 14:04 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/observe/index.md
> +  - : Thrown if the the [Compute Pressure API](/en-US/docs/Web/API/Compute_Pressure_API) is disallowed by a {{httpheader('Permissions-Policy/compute-pressure','compute-pressure')}} [Permissions Polic
I think this has to with calling observe in an iframe and having the constructor in the owning document? See the red box in the spec: https://w3c.github.io/compute-pressure/#the-observe-method

2024-04-12 14:17 UTC, Elchi3 commented on files/en-us/web/http/headers/permissions-policy/compute-pressure/index.md
> +The HTTP {{HTTPHeader("Permissions-Policy")}} header `compute-pressure` directive controls access to the [Compute Pressure API](/en-US/docs/Web/API/Compute_Pressure_API).
I think it is expected. Compute pressure is enabled for same-origin nested frames but disabled for third-party. Updated in https://github.com/mdn/content/pull/32923/commits/1de5b0dc2e2d1f974d92e9c49fa1209c36cb7b96.

2024-04-12 14:58 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
I'm afraid I don't have the answer here. Pinging @kenchris once more. What is `takeRecords()` for exactly?

2024-04-12 15:04 UTC, arskama commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
When ever the callback is invoke and records are delivered, they are also deleted.
takeRecords is a way to force delivering the records that haven't yet been delivered by the callback.

The user becomes active in requesting the records if any available.

2024-04-12 15:30 UTC, Elchi3 commented
Thanks everyone, I went through all the comments. I think the outstanding questions are:

- The explainer says that rAF could only be used to mitigate issues (by triggering less frequently) and the Compute Pressure API proactively prevents pressure. How is that meant exactly? (or maybe I should remove this sentence if it doesn't help anyone) [comment](https://github.com/mdn/content/pull/32923#discussion_r1549315961)
- Will `observe()` have a promise or not? [comment](https://github.com/mdn/content/pull/32923#discussion_r1554068839)
- Why can `observe()` throw a `NotAllowedError`, wouldn't the constructor throw before anyway?  [comment](https://github.com/mdn/content/pull/32923#discussion_r1554445742)
- What is `takeRecords()` for? Does anyone have a good example? [comment](https://github.com/mdn/content/pull/32923#discussion_r1554513057)
- When "cpu" is the source it watches the thread in which this observer is running, right? [comment](https://github.com/mdn/content/pull/32923#discussion_r1554515391)
- Epoch timestamps will be changed to document/worker creation timestamps in Chromium or what is the status? [comment](https://github.com/mdn/content/pull/32923#discussion_r1554516104)

2024-04-12 15:32 UTC, kenchris commented on files/en-us/web/api/pressurerecord/source/index.md
> +- `"cpu"` represents the average pressure of the central processing unit (CPU) across all its cores. This source is the CPU pressure for the thread the site is using, such as the main thread (window)
Nope, it's global CPU pressure for the system and it can then be external pressure caused by other apps on the system. We are planning to add local pressure at some later point

2024-04-12 15:35 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +await observer.observe("cpu");
@rakuco explains that in some details here: https://github.com/w3c/compute-pressure/issues/258#issuecomment-2047724262

Other observers like ResizeObserver, PerformanceObserver etc don't deal with external resources, and it's mostly measuring locally on what it is in the document - that is the big exception. We have to go out to a global resource which is an async operation and which can, but should not fail

2024-04-12 15:36 UTC, kenchris commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
It is useful when you are about to disconnect but would like to make sure you to receive any pending records before.

2024-04-12 15:36 UTC, kenchris commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
PerformanceObserver has the exact same API https://w3c.github.io/performance-timeline/#dom-performanceobserver-takerecords

2024-04-12 15:42 UTC, kenchris commented on files/en-us/web/api/pressureobserver/observe/index.md
> +  - : Thrown if the the [Compute Pressure API](/en-US/docs/Web/API/Compute_Pressure_API) is disallowed by a {{httpheader('Permissions-Policy/compute-pressure','compute-pressure')}} [Permissions Polic
You can construct it yes, but not do any observation. You might even have a shared worker and one starting observation from a document an iframe document that doesn't pass the policy test.

So say Zoom has a shared worker that works fine on the main zoom site, but then there is www.onlinedoctor.dk website that embeds the zoom SDK which also uses the shared worker, but this site decided to not allow the permission policy so it will fail

2024-04-12 15:48 UTC, kenchris commented on files/en-us/web/api/compute_pressure_api/index.md
> +Fast and delightful web applications should balance workloads when the system's computing resources are used at (near) full capacity. The Compute Pressure API's goal is to prevent, rather than mitiga
This part seems written by the old team. If the system is not able to perform well, requestanimationFrame will run at a lower frequency, so that might help the issue somewhat, but won't fix it. Also, that "fix" also only applies to some of the use-cases and probably won't be useful for webrtc (where you want to change resolution, or turn off feeds), or video games

2024-04-15 17:54 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
> It is useful when you are about to disconnect but would like to make sure you to receive any pending records before.

This seems like a great example usage.

> When ever the callback is invoke and records are delivered, they are also deleted.

I think the reason I wasn't sure about that was that the page for `takeRecords` says "emptying it out" while the docs on the observer don't say anything: also that the example for the observer (https://pr32923.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/PressureObserver/observe#log_current_pressure) only looks at the last record. I wonder if it would help to have an example that sends (or even mock-sends) records to an analytics endpoint as they are received, and also used `takeRecords` to send the last set when finishing up?

I wonder also if it would help to expand https://pr32923.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/PressureObserver/PressureObserver#changes a bit to say something like:

> An array containing all [PressureRecord](https://pr32923.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/PressureRecord) objects recorded since the last time the callback was called, or the last time the observer's `takeRecords()` was called.

?

2024-04-15 18:00 UTC, wbamberg commented on files/en-us/web/api/compute_pressure_api/index.md
> +await observer.observe("cpu");
That makes sense, but then the example ought to illustrate the usage, like

```js
try {
  const observer = new PressureObserver(callback);
  await observer.observe("cpu", {
    sampleInterval: 1000, // 1000ms
  });
} catch(error) {
  // report error setting up the observer 
}
```

?

2024-05-03 13:27 UTC, Elchi3 commented on files/en-us/web/api/compute_pressure_api/index.md
> +Fast and delightful web applications should balance workloads when the system's computing resources are used at (near) full capacity. The Compute Pressure API's goal is to prevent, rather than mitiga
Reworded.

2024-05-03 13:28 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +console.log(records[0].time);
Add an if condition.

2024-05-03 13:28 UTC, Elchi3 commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
I've updated https://pr32923.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/PressureObserver/PressureObserver#changes with your suggestion.

2024-05-03 13:29 UTC, Elchi3 commented on files/en-us/web/api/pressurerecord/source/index.md
> +- `"cpu"` represents the average pressure of the central processing unit (CPU) across all its cores. This source is the CPU pressure for the thread the site is using, such as the main thread (window)
Changed the meaning of "cpu" everywhere given it is global CPU pressure and not local pressure.

2024-05-03 13:30 UTC, Elchi3 commented on files/en-us/web/api/pressurerecord/time/index.md
> +The read-only **`time`** property returns the {{domxref("DOMHighResTimeStamp","timestamp", "", "no-code")}} recorded for a {{domxref("PressureRecord")}}. It corresponds to the time the data was obtai
Added a link to https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin to learn more.

2024-05-03 13:45 UTC, Elchi3 commented
I've addressed the review feedback and updated the docs per the latest spec change (supportedSources -> knownSources). I've also merged the BCD so that we can have spec and compat sections in the docs.

Marking as ready for final review.

2024-05-03 18:46 UTC, wbamberg requested changes
Thanks for the updates Florian. I had some tiny comments.

2024-05-03 18:46 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/observe/index.md
> +      - : A number representing the requested sampling interval expressed in milliseconds. Defaults to 0 meaning it will get as fast as the system can handle it.
```suggestion
      - : A number representing the requested sampling interval expressed in milliseconds. Defaults to 0 meaning it will get updates as fast as the system can handle it.
```

? something needs to go there anyway

2024-05-03 18:46 UTC, wbamberg commented on files/en-us/web/api/pressureobserver/takerecords/index.md
> +The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.
maybe add

```suggestion
The **`takeRecords()`** method of the {{domxref('PressureObserver')}} interface returns the current list of pressure records stored in the pressure observer, emptying it out.

It is useful when you want to a stop observing a source but would like to be sure to get any records that have not yet been passed into the observer callback. 
```

?

2024-05-14 17:15 UTC, wbamberg approved these changes
👍 thank you Florian!

2024-05-14 17:15 UTC, merged