feat: Editorial review: Add docs for notRestoredReasons
mdn/content pull request #32920
Opened 2024-04-02 07:40 UTC by chrisdavidmills

### Description

https://github.com/mdn/content/pull/27947 contains the engineering technical review for my work on [notRestoredReasons](https://w3c.github.io/navigation-timing/#dom-performancenavigationtiming-notrestoredreasons) docs, which has been completed and approved. Thank you to @tunetheweb for your thorough and detailed review work.

This is a new PR based on the same branch, which is intended to contain the editorial review for the same work.

---

### Background information

The `PerformanceNavigationTiming.notRestoredReasons` property is finally going to be launched in Chrome 123. This PR adds a reference page for the property and associated interfaces, and a guide to using it.

See https://developer.chrome.com/docs/web-platform/bfcache-notrestoredreasons/ for further details

### Motivation

### Additional details

### Related issues and pull requests

2024-04-02 16:36 UTC, skyclouds2001 reviewed
those self-links is better not to kept

2024-04-02 16:36 UTC, skyclouds2001 commented on files/en-us/web/api/notrestoredreasons/index.md
> +  - : An array of {{domxref("NotRestoredReasons")}} objects, one for each child {{htmlelement("iframe")}} embedded in the current document, which may contain reasons why the top-level frame was block
```suggestion
  - : An array of `NotRestoredReasons` objects, one for each child {{htmlelement("iframe")}} embedded in the current document, which may contain reasons why the top-level frame was blocked relating to the child frames. Each object has the same structure as the parent object — this way, any number of levels of embedded `<iframe>`s can be represented inside the object recursively. If the frame has no children, the array will be empty; if the document is in a cross-origin `<iframe>`, `children` will return `null`.
```

2024-04-02 16:36 UTC, skyclouds2001 commented on files/en-us/web/api/notrestoredreasons/index.md
> +  - : A {{Glossary("Serialization","serializer")}}; returns a JSON representation of the {{domxref("NotRestoredReasons")}} object.
```suggestion
  - : A {{Glossary("Serialization","serializer")}}; returns a JSON representation of the `NotRestoredReasons` object.
```

2024-04-02 16:36 UTC, skyclouds2001 commented on files/en-us/web/api/notrestoredreasondetails/index.md
> +  - : A {{Glossary("Serialization","serializer")}}; returns a JSON representation of the {{domxref("NotRestoredReasonDetails")}} object.
```suggestion
  - : A {{Glossary("Serialization","serializer")}}; returns a JSON representation of the `NotRestoredReasonDetails` object.
```

2024-04-02 16:37 UTC, skyclouds2001 commented on files/en-us/web/api/performancenavigationtiming/index.md
> +- {{domxref('PerformanceNavigationTiming.notRestoredReasons')}} {{ReadOnlyInline}}
```suggestion
- {{domxref('PerformanceNavigationTiming.notRestoredReasons')}} {{ReadOnlyInline}} {{Experimental_Inline}}
```

2024-04-02 16:38 UTC, skyclouds2001 commented on files/en-us/web/api/notrestoredreasons/tojson/index.md
> +spec-urls: https://html.spec.whatwg.org/multipage/nav-history-apis.html#notrestoredreasons
```suggestion
title: "NotRestoredReasons: toJSON() method"
short-title: toJSON()
slug: Web/API/NotRestoredReasons/toJSON
page-type: web-api-instance-method
browser-compat: api.NotRestoredReasons.toJSON
status:
  - experimental
spec-urls: https://html.spec.whatwg.org/multipage/nav-history-apis.html#notrestoredreasons
```

2024-04-02 16:38 UTC, skyclouds2001 commented on files/en-us/web/api/notrestoredreasondetails/tojson/index.md
> +spec-urls: https://html.spec.whatwg.org/multipage/nav-history-apis.html#notrestoredreasondetails
```suggestion
title: "NotRestoredReasonDetails: toJSON() method"
short-title: toJSON()
slug: Web/API/NotRestoredReasonDetails/toJSON
page-type: web-api-instance-method
browser-compat: api.NotRestoredReasonDetails.toJSON
status:
  - experimental
spec-urls: https://html.spec.whatwg.org/multipage/nav-history-apis.html#notrestoredreasondetails
```

2024-04-05 09:28 UTC, chrisdavidmills commented on files/en-us/web/api/notrestoredreasons/index.md
> +  - : An array of {{domxref("NotRestoredReasons")}} objects, one for each child {{htmlelement("iframe")}} embedded in the current document, which may contain reasons why the top-level frame was block
Yeah, good call. I'm not quite sure how I ended up leaving them there ;-)

2024-04-09 14:36 UTC, Elchi3 requested changes
Thanks for working on the docs for this addition to the Performance API, Chris!

The reference pages look alright to me. I'm a bit sad that the guide page is quite thin. I would have expected more info about what the bfcache is and what the strategies are to measure bfcache hit rate overall and for each of the blocking reasons what sort of code contributes to it being blocked and how to optimize etc. I think a more in-depth guide or how-to on bfcache optimization could be follow-up work. In this PR, though, I won't let you away without a glossary entry for "bfcache". That seems like a minimum here and I think it should be linked throughout the docs that you have created. 

Another must have for me is to update https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigation/type to point to this new API so that people who use TYPE_BACK_FORWARD today we will be aware of NotRestoredReasons.

Thank again! 👍

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +When a page has cross-origin frames embedded, we limit the amount of information shared about them to avoid leaking cross-origin information. We only include information that the outer page already k
Who is "we"? I guess it is not the web developer. This "we" seems to refer to the implementation or the specification and that is irrelevant to the web developer.
 
```suggestion
When a page has cross-origin frames embedded, the amount of information shared about them is limited to avoid leaking cross-origin information. Only information that the outer page already knows is included, and whether the cross-origin subtree caused bfcache blocking or not. No blocking reasons or information about lower levels of the subtree (even if some sub-levels are same-origin) are included.
```

2024-04-09 14:36 UTC, Elchi3 commented on files/jsondata/GroupData.json
> +        "/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons"
If you agree there should be a better title then this needs updating too

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/performancenavigationtiming/notrestoredreasons/index.md
> +The **`notRestoredReasons`** read-only property of the {{domxref("PerformanceNavigationTiming")}} interface returns a {{domxref("NotRestoredReasons")}} object providing report data on reasons why the
```suggestion
The **`notRestoredReasons`** read-only property of the {{domxref("PerformanceNavigationTiming")}} interface returns a {{domxref("NotRestoredReasons")}} object providing report data on reasons why the current document was blocked from using the back/forward cache ({{Glossary("bfcache")}}) on navigation.
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/performancenavigationtiming/notrestoredreasons/index.md
> +A [`PerformanceNavigationTiming`](/en-US/docs/Web/API/PerformanceNavigationTiming) instance can be obtained from features such as [`Performance.getEntriesByType()`](/en-US/docs/Web/API/Performance/ge
```suggestion
[`PerformanceNavigationTiming`](/en-US/docs/Web/API/PerformanceNavigationTiming) data can be obtained from the performance timeline using [`Performance.getEntriesByType()`](/en-US/docs/Web/API/Performance/getEntriesByType) or [`PerformanceObserver`](/en-US/docs/Web/API/PerformanceObserver).
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/performancenavigationtiming/index.md
> +  - : A {{domxref("NotRestoredReasons")}} object providing report data on reasons why the current document was blocked from using the [back/forward cache (bfcache)](https://web.dev/articles/bfcache)
```suggestion
  - : A {{domxref("NotRestoredReasons")}} object providing report data on reasons why the current document was blocked from using the back/forward cache ({{Glossary("bfcache")}}) on navigation.
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/reasons/index.md
> +{{domxref("NotRestoredReasons")}} interface returns an array of {{domxref("NotRestoredReasonDetails")}} objects, each representing a reason why the navigated page was blocked from using the [back/for
```suggestion
{{domxref("NotRestoredReasons")}} interface returns an array of {{domxref("NotRestoredReasonDetails")}} objects, each representing a reason why the navigated page was blocked from using the back/forward cache ({{Glossary("bfcache")}}).
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/index.md
> +The **`NotRestoredReasons`** interface of the {{domxref("Performance API", "Performance API", "", "nocode")}} provides report data containing reasons why the current document was blocked from using t
```suggestion
The **`NotRestoredReasons`** interface of the {{domxref("Performance API", "Performance API", "", "nocode")}} provides report data containing reasons why the current document was blocked from using the back/forward cache ({{Glossary("bfcache")}}) on navigation.
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/reason/index.md
> +{{domxref("NotRestoredReasonDetails")}} interface returns a string describing a reason that the page was blocked from using the [back/forward cache (bfcache)](https://web.dev/articles/bfcache).
```suggestion
{{domxref("NotRestoredReasonDetails")}} interface returns a string describing a reason that the page was blocked from using the back/forward cache ({{Glossary("bfcache")}}).
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/reason/index.md
> +  - : The page registers an [`unload`](/en-US/docs/Web/API/Window/unload_event) handler, which prevents bfcache usage. This serves as a useful warning, as `unload` is deprecated. See [Deprecating the
```suggestion
  - : The page registers an [`unload`](/en-US/docs/Web/API/Window/unload_event) handler, which prevents bfcache usage. This serves as a useful warning, as `unload` is deprecated. See [usage notes](/en-US/docs/Web/API/Window/unload_event#usage_notes) for more information.
```

2024-04-09 14:36 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/index.md
> +The **`NotRestoredReasonDetails`** interface of the {{domxref("Performance API", "Performance API", "", "nocode")}} represents a single reason why a navigated page was blocked from using the [back/fo
```suggestion
The **`NotRestoredReasonDetails`** interface of the {{domxref("Performance API", "Performance API", "", "nocode")}} represents a single reason why a navigated page was blocked from using the back/forward cache ({{Glossary("bfcache")}}).
```

2024-04-10 16:19 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +title: Reporting back/forward cache not restored reasons
This seems a bit too vague/general to me — this is specifically about monitoring reasons a document was blocked from using the bfcache. I thought about it a bit, and updated it to "Monitoring back/forward cache blocking reasons", which is slightly shorter, and a bit less wordy ... maybe?

2024-04-10 16:20 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons): Reporting on why the current document was blocked from usi
Updated as per my counter-suggestion (see earlier comment).

2024-04-10 16:23 UTC, chrisdavidmills commented on files/jsondata/GroupData.json
> +        "/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons"
Updated as detailed earlier.

2024-04-10 16:25 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +To enable monitoring bfcache blocking in the field the [`PerformanceNavigationTiming`](/en-US/docs/Web/API/PerformanceNavigationTiming) class includes a `notRestoredReasons` property. This returns an
I updated it to "To enable monitoring bfcache blocking reasons, the..."

2024-04-10 16:56 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +## Concepts and usage
I've used "## Back/forward cache (bfcache)"

2024-04-10 17:00 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +## Examples
I ended up using "## Logging bfcache blocking reasons"

2024-04-10 17:25 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/reporting_backforward_cache_not_restored_reasons/index.md
> +  const navEntries = performance.getEntriesByType("navigation");
That makes sense. I've added a `PerformanceObserver` example and restructured the section a bit to suit.

2024-04-11 14:40 UTC, Elchi3 approved these changes
Thank for adding the glossary page, and addressing my other feedback! There are some links to update still but I think this could land with the fixes submitted

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/glossary/bfcache/index.md
> +The bfcache is great for performance, so it is in your interests to make sure your pages are not blocked from using it. You can use the [`notRestoredReasons` API](/en-US/docs/Web/API/PerformanceNavig
Instead of sending people to a quite technical reference page, I would send them to the guide page.

```suggestion
The bfcache is great for performance, so it is in your interests to make sure your pages are not blocked from using it. You can use the [`notRestoredReasons` API](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) to monitor whether pages are blocked from using the bfcache, and reasons why.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/reason/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/reason/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasondetails/tojson/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/children/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/children/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/id/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/id/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/name/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/name/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/reasons/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/reasons/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/reasons/index.md
> +An array of {{domxref("NotRestoredReasonDetails")}} objects. See [Blocking reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons#blocking_reasons) for a list o
```suggestion
An array of {{domxref("NotRestoredReasonDetails")}} objects. See [Blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons#blocking_reasons) for a list of the possible blocking reasons.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/src/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/src/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/tojson/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/url/index.md
> +See [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons) for examples.
```suggestion
See [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons) for examples.
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/notrestoredreasons/url/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-11 14:40 UTC, Elchi3 commented on files/en-us/web/api/performancenavigationtiming/notrestoredreasons/index.md
> +- [Reporting back/forward cache not restored reasons](/en-US/docs/Web/API/Performance_API/Reporting_backforward_cache_not_restored_reasons)
```suggestion
- [Monitoring bfcache blocking reasons](/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons)
```

2024-04-12 09:12 UTC, chrisdavidmills commented on files/en-us/glossary/bfcache/index.md
> +The bfcache is great for performance, so it is in your interests to make sure your pages are not blocked from using it. You can use the [`notRestoredReasons` API](/en-US/docs/Web/API/PerformanceNavig
Yup, good call.

2024-04-12 10:05 UTC, merged