fix(svg attributes): Remove the element list and reorder sections (for attributes u-z )
mdn/content pull request #32965
Opened 2024-04-04 19:09 UTC by dipikabh

### Description

I came across the [SVG x attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x) page while triaging https://github.com/mdn/content/issues/32081.

The element list under "You can use this attribute with the following SVG elements:" resembles a Table of Contents (TOC) but it is not. I found this list alongside the "In this article" sidebar links confusing.

The links in the element list take you to the respective element pages whereas I was expecting navigation to sections on the attribute page itself.

Given that the sidebar is meant for in-page navigation, and each element section already includes a link to its  corresponding element page, the initial list of links appears to be redundant.

This PR:
- Removes the element list from attribute pages that contain subsequent sections for those elements. Each section contains a link to the corresponding element page, so that navigation aid is not lost.

- Renames "Example" to "Examples". This aligns with our use of the plural form for this section. For example, in the [SVG element page template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/SVG_element_page_template#examples), the guideline is: "Note that we use the plural "Examples" even if the page only contains one example."

- Changes the position of the "Examples" section so that it follows "Usage notes" or appears before "Specifications" (as in [SVG element page template](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/SVG_element_page_template#examples) and various other templates).
  (The appearance of examples before an explanation of the values was reported as a problem in https://github.com/mdn/content/issues/31825.)

- Uses the section name "Usage notes" when a description of values is included and the name "Usage context" when the section contains only a table. The section name "Context notes" appears only on SVG attribute pages; it has been updated to "Usage notes" or "Usage context" as appropriate.

**Note:** The improvements in this PR focus on attributes with names starting from U to Z.

### Motivation

To help streamline navigation and improve consistency with other parts of MDN

2024-04-04 21:29 UTC, estelle reviewed
I made a few suggestions to improve the docs as long as we're in her editing them.

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/width/index.md
> -- {{SVGElement('use')}}
do whatever you chose to do with viewbox here too

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/width/index.md
> +
Let's include an intro sentence for the example instead of a comment within the example.
```suggestion
This example includes three {{SVGElement("rect")}} elements with varied `width` attribute values.  The first `<rect>` has a `width="0"` set.  SVG elements with a width of `0` or less are not rendered. 

```

Some CSS can be added, such as `rect {outline: 5px red dotted}` to make it more clear that the element is not rendered at all (rather than just having a width of 0 and a height of 90).

Note if `rect {min-width: 10px;}` is set, the outline will not show, but if `rect {width: 10px;}` is set, all three will show and be 10px wide. This should be noted. If fixing these pages is beyond the scope of the PR, we need to create an issue. This page should note the effect of the CSS `width` property

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/word-spacing/index.md
> +
```suggestion
This example includes two {{SVGElement("text")}} elements with different `word-spacing` values.  
```

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/x/index.md
> +You can use this attribute with the SVG elements described in the sections below.
same comment as before.

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/x/index.md
> +  <rect x="220" y="20" width="60" height="60" />
```suggestion
  <rect x="220" y="20" width="60" height="60" fill="red" />
  <rect x="120" y="20" width="60" height="60" fill="yellow" />
  <rect x="20" y="20" width="60" height="60" fill="blue" />
```

2024-04-04 21:29 UTC, estelle commented on files/en-us/web/svg/attribute/x/index.md
> +
```suggestion
This example contains three {{SVGElement("rect")}} elements, each with an `x` value smaller than the previous value. 

```
adding a fill color, an intro, and changed the x values to be in descending order so it's apparent that they're not just laid out in code order

2024-04-09 18:25 UTC, dipikabh commented on files/en-us/web/svg/attribute/viewbox/index.md
> +
Using with slight tweaks:

> The code snippet below includes three  {{SVGElement("svg")}}s  with different `viewbox` attribute values and identical {{SVGElement("rect")}} and {{SVGElement("circle")}} descendants creating very different results. The size of `<rect>` is defined using relative units, so the visual size of the square produced looks unchanged regardless of the `viewBox` value. The radius length {{SVGAttr("r")}} attribute of the `<circle>` is the same in each case, but this user unit value is resolved against the size defined in the `viewBox`, producing different results in each case.

2024-04-09 18:31 UTC, dipikabh commented on files/en-us/web/svg/attribute/viewbox/index.md
> +The exact effect of this attribute is influenced by the {{ SVGAttr("preserveAspectRatio") }} attribute.
Thanks, tweaking slightly for formatting

2024-04-09 18:37 UTC, dipikabh commented on files/en-us/web/svg/attribute/width/index.md
> +
Yes, let's take this up in a separate issue/PR.

2024-04-09 22:05 UTC, dipikabh commented on files/en-us/web/svg/attribute/viewbox/index.md
> +You can use this attribute with the SVG elements described in the sections below.
- Section name

The term "Usage notes" has been commonly used in SVG attribute pages for sections that list possible values, as in https://pr32965.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/word-spacing#usage_notes.

IMO, "Usage notes" is similar to the "Description" section we typically use in CSS, except that the "Usage notes" sections in SVG attribute pages list and explain values. (We can consider resolving this inconsistency by updating our templates.) However, for this reason, "Usage" might not be a good choice here.

Additionally, the intention here is to list the elements with which the attribute can be used. It might be more fitting to name this section "Elements", similar to how we list "[Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attributes)" for HTML elements - here, we list elements supporting the attribute.

I intend to adjust the heading to "Elements". LMK what you think.

- Nesting element sections as H3s

While I can nest the elements as H3s, navigation to them may require some scrolling until we have support for H3s in the page sidebar. Having the sections as H3s does have the benefit of reducing the items in the sidebar. Regarding the suggestion to manually list the links to the sections, I am not in favor of doing that. Navigation can be provided through the in-page sidebar (when H3s are available). 

- Linking to elements

Inline linking as suggested in "You can use this attribute with the {{SVGElement("marker")}}, {{SVGElement("pattern")}}, {{SVGElement("svg")}}, {{SVGElement("symbol")}}, and {{SVGElement("view")}} SVG elements:" may not be ideal IMO. My original concern was that the links in the element list redirect to the respective element pages, whereas I anticipated navigation to sections within the attribute page itself. Each element section already includes a link to its corresponding element page. It is very likely that someone comes to the attribute page from an element page in the first place.

- About page TOC

> The MDN TOC for the page isn't always visible, and the example and other content in the sidebar makes the TOC for the elements a less good option.

I am curious to know your perspective about why the TOC is not always visible

- Section names are incorrect

I just noticed that the "[marker](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox#marker)" section name should actually be "`<marker>`".

2024-04-09 23:30 UTC, dipikabh commented
Hi @estelle, thanks a lot for reviewing these pages!

I've accepted your content additions/improvements (thank you for the suggestions). I believe we can address these concerns in a separate issue/PR. The focus of the current set is to fix the navigation and ordering of sections.

Please see my response in https://github.com/mdn/content/pull/32965#discussion_r1558350551 for the reasoning behind some of the changes. You can preview them on the [viewBox](https://pr32965.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox) page. If these changes look okay to you, I'll replicate them to other pages. Thanks!

2024-04-12 00:35 UTC, hamishwillee commented
I've removed my review request as it looks like @estelle has sorted this. You can add me back if further review is needed.

2024-04-13 01:05 UTC, estelle commented
> The focus of the current set is to fix the navigation and ordering of sections.

I am not a fan of the h2s as the reader doesn't know if "use" is an element or another section of the page; the elements aren't differentiated from the other page sections. As it's currently like that, and this doesn't address it but doesn't make it worse, no reason to hold up a PR (though opening an issue would be great so we can remember to address this in the future)

<img width="138" alt="side bar bottom where the elements aren 't differentiated from the other page sections." src="https://github.com/mdn/content/assets/69888/d55287d4-fb7f-4444-b9da-8084d25631fa">

2024-04-13 01:09 UTC, estelle commented on files/en-us/web/svg/attribute/width/index.md
>  ## feBlend
```suggestion
## `<feBlend>`
```
What do you think of this as a solution? (only doing one suggestion to show the idea. not expecting you to his "commit" to this.

2024-04-16 13:15 UTC, dipikabh commented on files/en-us/web/svg/attribute/width/index.md
>  ## feBlend
Yes. I had made this change in https://pr32965.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox#elements as a sample.

2024-04-16 13:22 UTC, dipikabh commented
> I am not a fan of the h2s as the reader doesn't know if "use" is an element or another section of the page.

Correct and I agree. I think we're saying the same thing :) Just to be sure:

Current [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox):

<kbd><img src="https://github.com/mdn/content/assets/23019147/76dfb1e0-0edf-4643-9ee8-580eb4e3282a" alt="viewbox_original" /></kbd>


What I'm proposing ([viewBox preview](https://pr32965.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox))

<kbd><img src="https://github.com/mdn/content/assets/23019147/ba602058-e899-48a6-96af-3900f695c842" alt="viewbox_proposed" /></kbd>

I am guessing that the only point where we differ is whether or not to have a hand-curated TOC to various element sub-sections. That is, I am not in favor of including this linked list:

<kbd><img src="https://github.com/mdn/content/assets/23019147/26c1cf7f-d9a3-41e3-b43b-ed617da45bd0)" alt="viewbox_toc" /></kbd>

2024-04-18 19:57 UTC, estelle requested changes
Some of the examples were duplicates, so made suggestions to create different yet useful ones.

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/x2/index.md
> +  <line x1="5" x2="9" y1="1" y2="9" stroke="blue" />
```suggestion
<svg viewBox="0 0 25 25" xmlns="http://www.w3.org/2000/svg">
  <line x1="2" x2="2" y1="5" y2="20" stroke="red" />
  <line x1="2" x2="12" y1="5" y2="20" stroke="green" />
  <line x1="2" x2="22" y1="5" y2="20" stroke="blue" />
```
the exact same example appeared twice on the page. This changes it enough so it's helpful in understanding

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/x1/index.md
> +  <line x1="9" x2="5" y1="1" y2="9" stroke="blue" />
```suggestion
<svg viewBox="0 0 25 25" xmlns="http://www.w3.org/2000/svg">
  <line x1="2" x2="22" y1="5" y2="20" stroke="red" />
  <line x1="12" x2="22" y1="5" y2="20" stroke="green" />
  <line x1="22" x2="22" y1="5" y2="20" stroke="blue" />
```

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/y/index.md
> +  <rect y="220" x="20" width="60" height="60" />
```suggestion
  <rect y="220" x="20" width="60" height="60" fill="red" />
  <rect y="120" x="20" width="60" height="60" fill="yellow" />
  <rect y="20" x="20" width="60" height="60" fill="purple" />
```

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/y/index.md
> +
```suggestion

This example contains three {{SVGElement("rect")}} elements, each with an `y` value smaller than the previous value.

```

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/y1/index.md
> +  <line x1="1" x2="9" y1="9" y2="5" stroke="blue" />
```suggestion
<svg viewBox="0 0 25 25" xmlns="http://www.w3.org/2000/svg">
  <line x1="2" x2="22" y1="0" y2="20" stroke="red" />
  <line x1="2" x2="22" y1="10" y2="20" stroke="green" />
  <line x1="2" x2="22" y1="20" y2="20" stroke="blue" />
```
exact same expample appeared twice in the same page. This is different enough to be useful

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/y2/index.md
> +  <line x1="1" x2="9" y1="5" y2="9" stroke="blue" />
```suggestion
<svg viewBox="0 0 25 25" xmlns="http://www.w3.org/2000/svg">
  <line x1="2" x2="22" y1="20" y2="0" stroke="red" />
  <line x1="2" x2="22" y1="20" y2="10" stroke="green" />
  <line x1="2" x2="22" y1="20" y2="20" stroke="blue" />
```
same issue

2024-04-18 19:57 UTC, estelle commented on files/en-us/web/svg/attribute/z/index.md
> +    style="filter: url(#diffuseLighting2); transform: translateX(220px);" />
```suggestion
  <filter id="diffuseLighting1" x="0" y="0" width="100%" height="100%">
    <feDiffuseLighting in="SourceGraphic">
      <fePointLight x="60" y="60" z="10" />
    </feDiffuseLighting>
  </filter>
  <filter id="diffuseLighting2" x="0" y="0" width="100%" height="100%">
    <feDiffuseLighting in="SourceGraphic">
      <fePointLight x="340" y="60" z="50" />
    </feDiffuseLighting>
  </filter>

  <rect
    x="0"
    y="0"
    width="200"
    height="200"
    filter="url(#diffuseLighting1)" />
  <rect
    x="200"
    y="0"
    width="200"
    height="200"
    filter="url(#diffuseLighting2)" />
```
removing CSS and making this all SVG

2024-04-19 15:43 UTC, dipikabh commented
Thanks for the suggestions, @estelle! I've applied them as is.

It might be better to address the content concerns and updates in a separate PR. This one was specifically aimed at fixing only the navigation, and I was waiting to get this approved before making similar changes to other attribute pages. I hope we can land this soon. In similar subsequent PRs, I'll happy to take up content improvements separately.

2024-04-19 18:40 UTC, estelle approved these changes

2024-04-19 18:41 UTC, merged

2024-04-22 12:36 UTC, dipikabh commented
Thanks, @estelle 🎉