update lab()
mdn/content pull request #32974
Opened 2024-04-06 00:26 UTC by estelle

The axes are hard to wrap ones head around, so i separated the L*A*B examples into an L example and an a+b example, and added a gradient so people could visualize the progressing about the a and b axes.

2024-04-06 09:07 UTC, chrisdavidmills requested changes
A few bits for you to consider @estelle. Great work overall!

2024-04-06 09:07 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/lab/index.md
> +### The a-axis and b-axis
```suggestion
### Linear gradients along the a and b-axes
```

To differentiate it clearly from what you are demonstrating in the previous example? Otherwise the example titles sound like they could be about exactly the same thing

2024-04-06 09:07 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/lab/index.md
> +
Maybe put a spacer of some kind in between the two sets of three, to break it up a bit and make the relationships clearer?

2024-04-06 09:07 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/lab/index.md
> +{{EmbedLiveSample("The a-axis and b-axis", '', '400')}}
Couple of things:

1. Need to change the heading here too, if you agree with my previous comment about the example heading.
2. You should make the demo slightly taller; it currently shows a vertical scrollbar in both Fx and Chrome.

2024-04-08 21:29 UTC, estelle reviewed
@chrisdavidmills Thanks. updated.
I used the feedback from this in updating oklab (https://github.com/mdn/content/pull/33006)

2024-04-09 11:43 UTC, chrisdavidmills approved these changes
Looks great, thanks @estelle!

2024-04-09 11:43 UTC, merged