Add experimental h1 UA styles removal
mdn/content pull request #33020
Opened 2024-04-09 17:38 UTC by pepelsbey

### Description

- Adds experimental h1 UA styles removal info into Firefox 125 release notes and to the Experimental features page
- Fixes headings levels for two other experimental features: they seem to be not grouped.

### Motivation

Upcoming [Firefox 125](https://github.com/mdn/mdn/issues/532) release.

### Additional details

- Bugzilla: [Remove UA styles for :is(article, aside, nav, section) h1 (Nightly only)](https://bugzilla.mozilla.org/show_bug.cgi?id=1883896)

### Related issues and pull requests

- https://github.com/mdn/content/issues/32746

2024-04-09 19:33 UTC, zcorpan commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>Yes</td>
The pref is `false` on Nightly and `true` on other channels. So this is either backwards or the `th` should say something like "UA styles removed?"

2024-04-10 10:40 UTC, pepelsbey commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>Yes</td>
Good point. I think it also makes sense to mention it in the description.

2024-04-10 20:07 UTC, dipikabh requested changes
Thanks, Vadim!
I have a few questions and suggestions.

2024-04-10 20:07 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +> **Note:** It's a reverse flag: it's set to `false` only in Nightly builds, which removes the UA styles, and to `true` in all other versions, which keeps them.
Is it correct or clear to say "removes the UA styles"? Maybe we need to say something to the effect of "With the new implementation, sectioning elements don't influence the nested `<h1>`."?
What about rephrasing the `true` part like this:
```suggestion
> **Note:** It's a reverse preference: it's set to `false` only in the Nightly build, which removes the UA styles, and to `true` in all other channels, which still uses sectioning elements for document outline.
```

2024-04-10 20:07 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <th>UA styles removed?</th>
With the note in place, I think we can go with the previous `th` (Enabled by default?). Otherwise this would be the only case where it is different from the other tables on this page.

2024-04-10 20:07 UTC, dipikabh commented on files/en-us/mozilla/firefox/releases/125/index.md
I guess any changes in `experimental_features` can be replicated here.

2024-04-10 22:45 UTC, pepelsbey commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +### UA styles for `<h1>` nested into sectioning elements
I think it’s important to keep the “UA styles” part. Otherwise, it’s not clear what is the nature of this change.

2024-04-10 22:52 UTC, pepelsbey commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +> **Note:** It's a reverse flag: it's set to `false` only in Nightly builds, which removes the UA styles, and to `true` in all other versions, which keeps them.
Thank you for the suggestions! A small edit: this preference affects only the styles. The outline is gone from the spec, and sections are on the websites.

```suggestion
> **Note:** It's a reverse preference: it's set to `false` only in the Nightly build, which removes the UA styles, and to `true` in all other channels, which still keep the UA styles for nested headings.
```

2024-04-11 15:51 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +### UA styles for `<h1>` nested into sectioning elements
I see your point. In other sections though, we just mention the name of the property or API or feature.

2024-04-11 16:18 UTC, dipikabh requested changes
It's close and getting better, thanks for the clarifications!

2024-04-11 16:18 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +> **Note:** It's a reverse flag: it's set to `false` only in Nightly builds, which removes the UA styles, and to `true` in all other versions, which keeps them.
Thanks for the clarification. What do you think these tweaks (splitting the sentence to aid with readability):

```suggestion
> **Note:** The preference for this feature works in reverse: it's set to `false` only in the Nightly build, which removes the UA styling for headings nested in sectioning elements. In all other channels, it's set to `true`, which still uses the UA styling for headings nested in sectioning elements.
```
or if that's too verbose, then (also, dropped "only", added "existing"):

```suggestion
> **Note:** The preference for this feature works in reverse: it's set to `false` in the Nightly build, which removes the UA styling for headings nested in sectioning elements. It's set to `true` in all other channels, which retains the existing UA styling for the nested headings.
```

2024-04-11 16:18 UTC, dipikabh commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <th>UA styles removed?</th>
I think another point to consider is that in other tables on the page, we don't use the "result" of the pref being enabled to name the column.

2024-04-15 09:52 UTC, pepelsbey commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +### UA styles for `<h1>` nested into sectioning elements
```suggestion
### UA style for `<h1>` elements nested in sectioning elements
```

2024-04-15 11:19 UTC, zcorpan requested changes

2024-04-15 11:19 UTC, zcorpan commented on files/en-us/mozilla/firefox/experimental_features/index.md
> +      <td>Yes</td>
Reopening, this should say "No" (and "Yes" on non-Nightly).

2024-04-15 12:50 UTC, dipikabh approved these changes
Thanks for the updates, @pepelsbey! Approving.

Note:
- @zcorpan's  [comment](https://github.com/mdn/content/pull/33020/files#r1565616335) needs to be fixed because of the table header change back to the previous one based on my suggestion but pref behavior is reverse. Sorry for the mix up
- Text changes need to be replicated to firefox/releases/125/index.md file as well.

2024-04-16 10:19 UTC, pepelsbey commented
> zcorpan's comment needs to be fixed
> text changes need to be replicated to firefox/releases/125/index.md file as well.

Done and done. Thank you both!

2024-04-16 10:20 UTC, merged