Add HTMLTable*Element.{valign|align}
mdn/content pull request #33035
Opened 2024-04-11 08:57 UTC by teoli2003

### Description

This PR adds docs for the following properties:
- `HTMLTableRowlElement.align`
- `HTMLTableRowElement.valign`
- `HTMLTableCaptionElement.align`
- `HTMLTableSectionElement.align`
- `HTMLTableSectionElement.valign`

### Motivation

These properties are supported by all engines.

Though deprecated, they are common tasks for beginners: we need documentation that points to the right way of doing this (TM), using `text-align` and `vertical-align`

### Additional details

There is no example as this is deprecated: the example sections point to examples using the modern (CSS) way of doing it so that they are one click away.

I used the same structure as in #32993.

`HTMLTableColElement` also has these two properties but their translation in CSS is more complicated so they will be in a separate PR.

### Related issues and pull requests

It is part of https://github.com/mdn/mdn/issues/520

2024-04-11 18:14 UTC, wbamberg requested changes

2024-04-11 18:14 UTC, wbamberg commented on files/en-us/web/css/vertical-align/index.md
> +  <tr style="vertical-align: bottom">
This example is a little complex now and I think it would help to have a short explanation at the start, right after the "Vertical alignment in a table cell" heading, something like:

> In this example we have a table with a single row containing six cells. The row sets `vertical-align` to`bottom`.
> - The first four cells each set their own `vertical-align` values, and these override the row's value.
> - The fifth cell does not set any `vertical-align` value, so inherits the row's value.
>
> The sixth cell is only used to ensure that the cells are tall enough to see the effect.

Also, I wonder if we could take some steps to make it less likely we'll see a scrollbar in this example. Even just reducing the size of the dummy text in cell 6 would help.

2024-04-11 18:14 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
The description is a bit weird now:

> This example demonstrates how the use of text-align on `<table>` elements, including `<tr>` rows and `<td>` cells.

...since it now includes other table elements. Probably better to say:

> This example demonstrates how the use of text-align on `<table>` elements.

2024-04-11 18:14 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
And again, it would be good to explain a bit about what's being set here and what the effect is.

2024-04-11 18:31 UTC, estelle commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
In general, to demonstrate best practices, avoid inline styles.

2024-04-12 13:36 UTC, teoli2003 commented on files/en-us/web/css/vertical-align/index.md
> +  <tr style="vertical-align: bottom">
- Added a text to describe
- Change the text of the 6th cell to a Lorem Ipsum and no scrollbar appear at any size
- Used a class and CSS instead of inline styling

2024-04-12 13:42 UTC, teoli2003 commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
I have improved the description and avoided inline styles now.

2024-04-12 17:55 UTC, wbamberg requested changes

2024-04-12 17:55 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +- it overrides the alignment of some cells to make it different of the default row alignment.
```suggestion
- The {{htmlelement("caption")}} is set to right-aligned.
- The first two {{htmlelement("th")}} elements use the default (left) alignment, while the third is set to right-aligned.
- Inside the {{htmlelement("tbody")}} element, the first row is set to right-aligned, the second is set to center-aligned, and the third uses the default (left) alignment.
- Within each row, some cells (c12, c31) are set to override the alignment of the row.
```

Note though that this assume you change the markup to put the three non-header rows inside a tbody.

2024-04-12 17:55 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
The inline style still seems to be here and at line 175?

2024-04-15 06:05 UTC, teoli2003 commented
I've added:
- <tbody> and accepted the changes
- removed the inline styles that I forgot to remove

Ready for another review

2024-04-15 06:05 UTC, teoli2003 commented on files/en-us/web/css/text-align/index.md
> +  <caption style="text-align: right">
Fixed

2024-04-15 16:31 UTC, wbamberg requested changes

2024-04-15 16:31 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +- The first two {{htmlelement("th")}} elements use the default (left) alignment, while the third is set to right-aligned.
I hadn't noticed, before, that the CSS includes a rule setting left-alignment for the `<th>`, and that in fact center-alignment is the default for table header cells.

So we should do one of these:
1. change this to say something like: "- The {{htmlelement("thead")}} element is set to have its cells left-aligned. The first two cells use this value, but the third {{htmlelement("th")}} cell is set to be right-aligned."
2. remove the `thead` rule in the CSS, and change this line to something like "- The first two {{htmlelement("th")}} elements use the default (center) alignment, while the third is set to right-aligned."

2024-04-15 16:31 UTC, wbamberg commented on files/en-us/web/css/text-align/index.md
> +  </thead>
Also missed this, sorry: `<th>` must be inside a `<tr>`, or this is invalid HTML.

2024-04-15 20:58 UTC, estelle reviewed
since we were talking about it during the call this morning, i took a look and have a few suggestions.

2024-04-15 20:58 UTC, estelle commented on files/en-us/web/api/htmltablecaptionelement/align/index.md
> +- {{cssxref("text-align")}}
```suggestion
- {{cssxref("text-align")}}
- {{cssxref("caption-side")}}
```
tangentially related, but few know about it, and it's not linked in many places, so this is a good place.

2024-04-15 20:58 UTC, estelle commented on files/en-us/web/api/htmltablerowelement/align/index.md
> +  - : Center the text in the cell. Use `text-align: center` instead.
```suggestion
  - : Center the text in the cell. Use `text-align: center` instead.
- `justify`
  - : Spread the text across the cell. Use `text-align: justify` instead.
- `char`
  - : Never fully supported, align text to a specified character. Use `text-align: <string>,` where the string is a single character, when supported.
```

2024-04-15 20:58 UTC, estelle commented on files/en-us/web/css/text-align/index.md
> +- The first two {{htmlelement("th")}} elements use the default (left) alignment, while the third is set to right-aligned.
```suggestion
- The first two {{htmlelement("th")}} elements inherit the left alignment from the `text-align: left` set on the {{htmlelement("thead")}}, while the third is set to right-aligned.
```
Alternatively, remove the alignment on thead, and write:

```
- The first two {{htmlelement("th")}} elements use the default (center) alignment, while the third is set to right-aligned.
```

The default for th is center, not left.
In the table CSS for html it reads 

> :is(thead,tbody,tfoot,tr,td,th)[align=absmiddle i] {
>   text-align: center;
> }

never saw absmiddle. so now for that rabbit hole....

2024-04-15 21:06 UTC, estelle commented on files/en-us/web/css/text-align/index.md
> +- The first two {{htmlelement("th")}} elements use the default (left) alignment, while the third is set to right-aligned.
Do you want to add a note in the values section, at line 63, about `<string>`
```
Note: Proposed in 2011, but not yet supported in any browser, the value can be a space-separated pair of values;  single character `<string>` value followed by any of the above values, that, when applied to a table cell, specifies the alignment character around which the cell’s contents will align.
```
see https://drafts.csswg.org/css-text-4/#text-align-property

2024-06-18 19:01 UTC, estelle commented on files/en-us/web/css/text-align/index.md
> +  </thead>
```suggestion
  <thead>
    <tr>
      <th>Col 1</th>
      <th>Col 2</th>
      <th class="right">Col 3</th>
    </tr>
  </thead>
```

2024-07-10 06:50 UTC, estelle approved these changes

2024-07-10 06:51 UTC, estelle commented
@wbamberg when you have a chance, a re-review would be great.

2024-07-24 23:33 UTC, wbamberg approved these changes
👍 thank you, @teoli2003 and @estelle !

2024-07-24 23:33 UTC, merged