Long animation frames api
mdn/content pull request #33039
Opened 2024-04-11 11:58 UTC by chrisdavidmills

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-12 04:47 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/scripts/index.md
> +short-title: attribution
```suggestion
short-title: scripts
```

2024-04-12 04:48 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/scripts/index.md
> +The **`scripts`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns an array of {{domxref("PerformanceScriptTiming")}} objects.
```suggestion
The **`scripts`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns an array of {{domxref("PerformanceScriptTiming")}} objects.
```

2024-04-12 04:53 UTC, skyclouds2001 reviewed
typo - readonly => read-only

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/scripts/index.md
> +The **`scripts`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns an array of {{domxref("PerformanceScriptTiming")}} objects.
```suggestion
The **`scripts`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns an array of {{domxref("PerformanceScriptTiming")}} objects.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/styleandlayoutstart/index.md
> +The **`styleAndLayoutStart`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time p
```suggestion
The **`styleAndLayoutStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time period spent in style and layout calculations for the current animation frame, in milliseconds.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/renderstart/index.md
> +The **`renderStart`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the start time of the rendering cyc
```suggestion
The **`renderStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the start time of the rendering cycle in milliseconds, which includes {{domxref("Window.requestAnimationFrame()")}} callbacks, style and layout calculation, {{domxref("ResizeObserver")}} callbacks, and {{domxref("IntersectionObserver")}} callbacks.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/firstuieventtimestamp/index.md
> +The **`firstUIEventTimestamp`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI
```suggestion
The **`firstUIEventTimestamp`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in milliseconds.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The **`blockingDuration`** readonly property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time the main thread
```suggestion
The **`blockingDuration`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time the main thread was blocked from responding to high priority tasks, such as user input, in milliseconds.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/executionstart/index.md
> +The **`executionStart`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and exe
```suggestion
The **`executionStart`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started, in milliseconds.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/forcedstyleandlayoutduration/index.md
> +The **`forcedStyleAndLayoutDuration`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the sc
```suggestion
The **`forcedStyleAndLayoutDuration`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script processing forced layout/style, in milliseconds. See [Avoid layout thrashing](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing#avoid_layout_thrashing) for an idea of what causes this.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/invoker/index.md
> +The **`invoker`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a string value indicating the identity of the feature that, when invoked, ran the script.
```suggestion
The **`invoker`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a string value indicating the identity of the feature that, when invoked, ran the script.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/invokertype/index.md
> +The **`invokerType`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a string value indicating the type of feature that, when invoked, ran the script.
```suggestion
The **`invokerType`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a string value indicating the type of feature that, when invoked, ran the script.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/pauseduration/index.md
> +The **`pauseDuration`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script in "pausin
```suggestion
The **`pauseDuration`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script in "pausing" synchronous operations, in milliseconds (for example {{domxref("Window.alert()")}} calls, or synchronous {{domxref("XMLHttpRequest")}}s).
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/sourcecharposition/index.md
> +The **`sourceCharPosition`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a number representing the script character position of the script feature that contribut
```suggestion
The **`sourceCharPosition`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a number representing the script character position of the script feature that contributed to the long animation frame (LoAF).
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +The **`sourceFunctionName`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a string representing the name of the function that contributed to the LoAF.
```suggestion
The **`sourceFunctionName`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a string representing the name of the function that contributed to the LoAF.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/sourceurl/index.md
> +The **`sourceURL`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a string representing the URL of the script.
```suggestion
The **`sourceURL`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a string representing the URL of the script.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/window/index.md
> +The **`window`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns a reference to a {{domxref("Window")}} object reference representing the `window` of the container (
```suggestion
The **`window`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a reference to a {{domxref("Window")}} object reference representing the `window` of the container (i.e. top-level document or {{htmlelement("iframe")}}) the long animation frame (LoAF)-causing script was executed in.
```

2024-04-12 04:53 UTC, skyclouds2001 commented on files/en-us/web/api/performancescripttiming/windowattribution/index.md
> +The **`windowAttribution`** readonly property of the {{domxref("PerformanceScriptTiming")}} interface returns an enumerated value describing the relationship of the container (i.e. top-level document
```suggestion
The **`windowAttribution`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns an enumerated value describing the relationship of the container (i.e. top-level document or {{htmlelement("iframe")}}) the long animation frame (LoAF)-causing script was executed in to the window that the current document is running in.
```

2024-04-16 17:32 UTC, dipikabh requested changes
Done one: PerformanceLongAnimationFrameTiming. Leaving suggestions and questions. I'll return shortly to look at the other files.

2024-04-16 17:32 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} indicating the total time the main thread was blocked from responding to high priority tasks, such as user input, in milliseconds. This is calculated by tak
- I coudn't find `PerformanceLongTaskTiming` page or the `Long task` glossary page.
- If you accept the suggestion to place "in milliseconds" earlier in the sentence, this change can be applied to other instances.

```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} in milliseconds, indicating the total time for which the main thread was blocked from responding to high priority tasks, such as user input. This is calculated by taking all the [long tasks](/en-US/docs/Web/API/PerformanceLongTaskTiming#description) within the LoAF that have a `duration` of more than `50ms`, subtracting `50ms` from each, adding the rendering time to the longest task time, and summing the results.
```

2024-04-16 17:32 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in millisec
```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} in milliseconds, indicating the time the first UI event (for example, a mouse or keyboard event) to be queued during the current animation frame.
```

2024-04-16 17:32 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for Long Animation Frames API examples.
- We could link to the specific example or the example section: "/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing#examples"
- We're not giving any example specific to the `PerformanceLongAnimationFrameTiming` interface either here or on the linked page. Do we want to clarify? Will linking to "/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing#examining_long-animation-frame_entries" help?
- This is also the first mention of "Long Animation Frames API" on this page.

```suggestion
See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for examples related to the Long Animation Frames API.
```

2024-04-16 21:12 UTC, dipikabh requested changes
2nd done

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +Note that the total `duration` in all three instances is 145ms. The total `blockingDuration` in the first two is the same (55ms) — the browser just decides to split the work in different ways in each
Oh, I've repeated the `145ms` info before the table - I found it useful as a reminder because it was last mentioned at the beginning of the example

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +`*` In options 2. and 3., there is only a single LoAF.
```suggestion
`*` In options 2 and 3, there is only a single LoAF.
```

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The third option however has a much longer `blockingDuration` because the browser is completely blocked and unable to interrupt the long task at all. This highlights the importance of optimizing long
```suggestion
Option 3, however, has a much longer `blockingDuration` because the browser is completely blocked and unable to interrupt the long task at all. This highlights the importance of optimizing long tasks by yielding — regardless of how the browser decides to handle the tasks, the blocking duration will still be less than if you don't yield at all.
```

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The reason why the `blockingDuration` of each task is calculated as `duration - 50ms` is that response delays of above 50ms start to be perceptible by users. This threshold is when users start notici
```suggestion
The reason why the `blockingDuration` of each task is calculated as `duration - 50ms` is that response delays of above 50ms start to be perceptible by users. This threshold is when users start noticing sluggishness; therefore, it is the time above the 50ms mark that is important to measure for determining the severity of jank.
```

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** See [Total Blocking Time (TBT)](https://web.dev/articles/tbt) for more details.
Can be moved to "See also"?

2024-04-16 21:12 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for Long Animation Frames API examples.
same comment as https://github.com/mdn/content/pull/33039#discussion_r1567717604

2024-04-17 08:11 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +The **`PerformanceLongAnimationFrameTiming`** interface provides metrics on [long animation frames (LoAFs)](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing#what_is_a_long_animation_fr
Good call; I've removed the link.

2024-04-17 08:19 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +Long animation frames (LoAFs) are rendering updates that are delayed beyond 50ms. LoAFs can cause slow user interface (UI) updates, resulting in seemingly unresponsive controls and [janky](/en-US/doc
Yours is better; I ended up using "result in slow user interface (UI) updates", as I felt like people might argue that the user interface is just slow because of a loAF — an existing UI update is not slowed down while in progress. It's a pretty subtle and pedantic difference, but one that is important, at least to some.

We ended up with:

> Long animation frames (LoAFs) are rendering updates that are delayed beyond 50ms. LoAFs can result in slow user interface (UI) updates, making controls appear unresponsive and causing [janky](/en-US/docs/Glossary/Jank) (non-smooth) animated effects and scrolling. This often leads to user frustration.

2024-04-17 08:21 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +The `PerformanceLongAnimationFrameTiming` interface provides a granular set of information on LoAFs allowing developers to narrow down their root causes:
Updated

2024-04-17 08:25 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +- It provides detailed information on each script that contributed to creating the LoAF, via the {{domxref("PerformanceLongAnimationFrameTiming.scripts")}} property. This returns an array of {{domxre
I agree with this, except that I used "A detailed..." for the first bullet, as it is a singular.

2024-04-17 08:30 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +This interface extends the following {{domxref("PerformanceEntry")}} properties for long animation frame timing performance entry types by qualifying them as follows:
I've updated it to this, which I think should mostly address your concerns:

> This interface extends the following {{domxref("PerformanceEntry")}} properties for long animation frame performance entries:

2024-04-17 08:33 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time taken to process the LoAF in it's entirety, in milliseconds.
"{{domxref("DOMHighResTimeStamp")}} in milliseconds" sounds a bit weird

I ended up with:

> Returns a {{domxref("DOMHighResTimeStamp")}} representing the time taken in milliseconds to process the LoAF in its entirety.

2024-04-17 08:37 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time when the animation frame started, in milliseconds.
Again, I used a slightly different structure:

> Returns a {{domxref("DOMHighResTimeStamp")}} representing the time in milliseconds when the animation frame started.

2024-04-17 08:42 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} indicating the total time the main thread was blocked from responding to high priority tasks, such as user input, in milliseconds. This is calculated by tak
The link you are having trouble with links to here: https://developer.mozilla.org/en-US/docs/Web/API/PerformanceLongTaskTiming#description. It works in my local test of this PR, and in the current live site.

Again, I have put the milliseconds slightly later in the sentence, not after {{domxref("DOMHighResTimeStamp")}}:

> Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time in milliseconds that the main thread was blocked from responding to high priority tasks, such as user input. This is calculated by taking all the [long tasks](/en-US/docs/Web/API/PerformanceLongTaskTiming#description) within the LoAF that have a `duration` of more than `50ms`, subtracting `50ms` from each, adding the rendering time to the longest task time, and summing the results.

2024-04-17 08:57 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in millisec
I ended up with:

> Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard), in milliseconds, to be queued during the current animation frame.

2024-04-17 09:05 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for Long Animation Frames API examples.
1. Good call — I've linked directly to the examples section.
2. We do give many examples — any time an entry is returned, either by a `PerformanceObserver` or by a timeline method such as `getEntries()`, and the entry type is specified as `"long-animation-frame"`, that entry will be a `PerformanceLongAnimationFrameTiming` instance. I didn't labour this point as it should be pretty obvious to folks experienced with using the performance APIs.
3. This is a good point. I've updated the opening sentence to:
   > The **`PerformanceLongAnimationFrameTiming`** interface is specified in the Long Animation Frames API and provides metrics on long animation frames (LoAFs) that occupy rendering and block other tasks from being executed.

2024-04-17 09:17 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The **`blockingDuration`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time the main threa
updated same as in the interface index page

2024-04-17 09:25 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +Take the case of a JavaScript file that takes a total of 145ms to process. After the first major chunk of script, which is processed after 65ms, we could consider breaking the execution of the script
I liked this rewrite, so I pretty much used all of it verbatim. I updated "you can set up yielding" to "you can yield".

2024-04-17 09:27 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** See [Optimize long tasks](https://web.dev/articles/optimize-long-tasks) for more information on long tasks and yielding.
OK, I've moved it to "See also" and added the latest update year in parens

2024-04-17 09:28 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +There are three options to consider here in how the script might end up being processed.
Updated

2024-04-17 09:31 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +3. We could also decide **not** to yield and let the browser deal with the entire script in one task.
These suggestions are nice — all used verbatim

2024-04-17 09:32 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** The browser will generally try to prioritize important tasks (such as user interactions) and rendering new frames over less important tasks it might have queued. The browser will _try_ to
like it; updated

2024-04-17 09:36 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +Assuming the rendering time is 10ms, timings for the LoAFs in each of the three options are as follows:
I ended up with:

> We mentioned earlier that the total processing time for the script is 145ms. Assuming the time for rendering the UI update is 10ms, the timings for the LoAFs in each of the three options are as follows:

I wanted to be specific that we are talking about processing the script, and I also put "rendering the UI update", as technically in the first version we have two frames, plus I'm not sure if there is other things implied in "the rendering"

2024-04-17 09:40 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +Note that the total `duration` in all three instances is 145ms. The total `blockingDuration` in the first two is the same (55ms) — the browser just decides to split the work in different ways in each
That's not a big problem; I've updated this sentence to:

> Note that the total `blockingDuration` in the first two is the same (55ms) — in each case the browser has decided to split the work in different ways.

2024-04-17 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +`*` In options 2. and 3., there is only a single LoAF.
Updated. I also decided to remove the periods from the table's leftmost column, as it looks neater that way.

2024-04-17 09:43 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The third option however has a much longer `blockingDuration` because the browser is completely blocked and unable to interrupt the long task at all. This highlights the importance of optimizing long
updated

2024-04-17 09:45 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The reason why the `blockingDuration` of each task is calculated as `duration - 50ms` is that response delays of above 50ms start to be perceptible by users. This threshold is when users start notici
Added; I also decided to prune the sentence a bit more to make it a bit less wordy:

> ...therefore, the time above the 50ms mark is important to measure for determining the severity of jank.

2024-04-17 09:55 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** See [Total Blocking Time (TBT)](https://web.dev/articles/tbt) for more details.
I'd rather leave this one here. I feel like it is very context-dependent — putting it down in "See also" will then require a whole bunch of explaining to clarify what it is referring to.

2024-04-17 09:55 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for Long Animation Frames API examples.
I've gone through and updated all instances of this sentence in the PR to be the same as in the interface landing page.

2024-04-17 16:13 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +- It provides detailed information on each script that contributed to creating the LoAF, via the {{domxref("PerformanceLongAnimationFrameTiming.scripts")}} property. This returns an array of {{domxre
makes sense

2024-04-17 16:14 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +This interface extends the following {{domxref("PerformanceEntry")}} properties for long animation frame timing performance entry types by qualifying them as follows:
Yeah, this is better

2024-04-17 16:15 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time taken to process the LoAF in it's entirety, in milliseconds.
This works too

2024-04-17 16:23 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in millisec
Any thoughts about the text within parentheses: "(for example, a mouse or keyboard event)"

2024-04-17 16:36 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +Assuming the rendering time is 10ms, timings for the LoAFs in each of the three options are as follows:
Looks good

2024-04-17 16:40 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +`*` In options 2. and 3., there is only a single LoAF.
Agree

2024-04-17 16:41 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +The reason why the `blockingDuration` of each task is calculated as `duration - 50ms` is that response delays of above 50ms start to be perceptible by users. This threshold is when users start notici
Yeah, this is better

2024-04-17 16:50 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** See [Total Blocking Time (TBT)](https://web.dev/articles/tbt) for more details.
Got it. Just to clarify, we don't need to provide any description of the content on the target page in 'See also'.
If you keep this external link here, maybe it does not need to be a "Note"?

2024-04-17 16:50 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +See [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing) for Long Animation Frames API examples.
thank you!

2024-04-17 17:45 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in millisec
Yeah, it's still a bit awkward. I tried again — how about this:

> Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time, in milliseconds, of the first UI (for example mouse or keyboard) event to be queued during the current animation frame.

?

2024-04-17 18:15 UTC, dipikabh requested changes

2024-04-17 18:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script processing forced layout/style, in milliseconds. See [Avoid layout thrashing](https://web.dev/articles
```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent, in milliseconds, by the script processing forced layout/style. See [Avoid layout thrashing](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing#avoid_layout_thrashing) to understand what causes this.
```

2024-04-17 18:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script in "pausing" synchronous operations, in milliseconds (for example {{domxref("Window.alert()")}} calls,
```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time, in milliseconds, spent by the script on "pausing" synchronous operations (for example, {{domxref("Window.alert()")}} calls or synchronous {{domxref("XMLHttpRequest")}}s).
```

2024-04-17 18:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a reference to a {{domxref("Window")}} object reference representing the `window` of the container (i.e. top-level document or {{htmlelement("iframe")}}) the LoAF-causing script was exe
```suggestion
  - : Returns a reference to a {{domxref("Window")}} object representing the `window` of the container (i.e., either the top-level document or an {{htmlelement("iframe")}}) in which the LoAF-causing script was executed.
```

2024-04-17 18:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns an enumerated value describing the relationship of the container (i.e. top-level document or {{htmlelement("iframe")}}) the LoAF-causing script was executed in to the window that the cu
```suggestion
  - : Returns an enumerated value describing the relationship of the container (i.e., either the top-level document or an {{htmlelement("iframe")}}) in which the LoAF-causing script was executed, relative to the window running the current document.
```

2024-04-17 18:16 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +> **Note:** See [Total Blocking Time (TBT)](https://web.dev/articles/tbt) for more details.
Yeah

2024-04-17 19:09 UTC, dipikabh requested changes
I've looked at all the pages now except https://pr33039.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing. I'll be able to get to it tomorrow.

2024-04-17 19:09 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/windowattribution/index.md
> +  - : The script was executed in a version of the current document embedded inside the current document in an `<iframe>`.
```suggestion
  - : The script was executed in a version of the current document embedded within the current document in an `<iframe>`.
```

2024-04-18 08:00 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +- [Optimize long tasks](https://web.dev/articles/optimize-long-tasks), web.dev (2024): contains more information on long tasks and yielding.
ok, updated

2024-04-18 08:01 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +- [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing)
I'm not sure I see the point of this; we don't add "guide" or "reference" to all the See also links habitually, do we? I've never done this before.

2024-04-18 08:05 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/firstuieventtimestamp/index.md
> +The **`firstUIEventTimestamp`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI
OK, I've now ended up with:

> a {{domxref("DOMHighResTimeStamp")}} indicating the time, in milliseconds, of the first UI event — such as a mouse or keyboard event — to be queued during the current animation frame.

2024-04-18 08:07 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/firstuieventtimestamp/index.md
> +- [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing)
Again, do we really have to start doing this for every see also link? If we do decide this is standard practice, it would be much better to automate it (look at the page type and add a word after each see also link based on that)

2024-04-18 08:11 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/scripts/index.md
> +Script attribution is only provided for scripts running in the main thread of a page, including same-origin `<iframe>`s. Cross-origin `<iframe>`s, [web workers](/en-US/docs/Web/API/Web_Workers_API),
updated

2024-04-18 08:12 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/scripts/index.md
> +An {{jsxref("Array")}} of {{domxref("PerformanceScriptTiming")}} objects.
link removed. I think you're right — it adds unnecessary noise.

2024-04-18 08:14 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/tojson/index.md
> +The **`toJSON()`** method of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface is a {{Glossary("Serialization","serializer")}}; it returns a JSON representation of the {{domxref("Perfo
removed

2024-04-18 08:14 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/tojson/index.md
> +### Using the toJSON method
updated

2024-04-18 08:23 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time when the script execution started, in milliseconds.
updates applied

2024-04-18 08:28 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started, in milliseconds.
Good point; they are all timestamps. I've removed "in milliseconds" for all of them, in all places.

2024-04-18 08:30 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script processing forced layout/style, in milliseconds. See [Avoid layout thrashing](https://web.dev/articles
updated

2024-04-18 09:11 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script in "pausing" synchronous operations, in milliseconds (for example {{domxref("Window.alert()")}} calls,
updated

2024-04-18 09:17 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a reference to a {{domxref("Window")}} object reference representing the `window` of the container (i.e. top-level document or {{htmlelement("iframe")}}) the LoAF-causing script was exe
updated

2024-04-18 09:22 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns an enumerated value describing the relationship of the container (i.e. top-level document or {{htmlelement("iframe")}}) the LoAF-causing script was executed in to the window that the cu
updated

2024-04-18 09:23 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/forcedstyleandlayoutduration/index.md
> +The **`forcedStyleAndLayoutDuration`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the s
applied suggestion

2024-04-18 09:25 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/invoker/index.md
> +| `"event-listener"`                        | The {{domxref("Element.tagName", "tagName")}} of the element, followed by a hash and its `id` (`#id`) or `src=` followed by its `src` value in square bra
updated

2024-04-18 09:30 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/invokertype/index.md
> +  - : A handler function for the resolved state of a web platform promise, for example {{domxref("fetch()")}}. Note that in the case of promises, all the handlers of the same promises are mixed toget
updated

2024-04-18 09:31 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/invokertype/index.md
> +  - : The evaluation of a standard script (for example via a {{htmlelement("script")}} element or [`import()`](/en-US/docs/Web/JavaScript/Reference/Operators/import) statement).
updated

2024-04-18 09:32 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/invokertype/index.md
> +The {{domxref("PerformanceScriptTiming.invoker")}} value's structure depends on the script's `invokerType` value. Check out the `invoker` page for more details.
updated

2024-04-18 09:33 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/pauseduration/index.md
> +The **`pauseDuration`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the script in "pausi
updated

2024-04-18 09:34 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourcecharposition/index.md
> +It is important to note that the reported function location will be the "entry point" of the script, i.e. the top level of the stack, and not any specific slow sub-function. See {{domxref("Performanc
updated

2024-04-18 09:36 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +browser-compat: api.PerformanceScriptTiming.sourceFunctionName
Ah yes, this one was missed the first time round. Florian added it in recently: https://github.com/mdn/browser-compat-data/pull/22851

2024-04-18 09:38 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +It is important to note that the reported function name will be the "entry point" of the script (i.e. the top level of the stack), and not any specific slow sub-function.
updated

2024-04-18 09:39 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +For example, if an event handler calls a top-level function, which in turn calls a slow sub-function, the `source*` fields will report the top-level function's name and location, not the slow sub-fun
updated

2024-04-18 09:40 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +`sourceFunctionName` would report `lib_func`, not `slow_function`
Updated

2024-04-18 09:41 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/sourceurl/index.md
> +It is important to note that the reported function location will be the "entry point" of the script, i.e. the top level of the stack, and not any specific slow sub-function. See {{domxref("Performanc
updated

2024-04-18 09:44 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/window/index.md
> +The **`window`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a reference to a {{domxref("Window")}} object reference representing the `window` of the container
suggestion applied

2024-04-18 09:45 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/windowattribution/index.md
> +The **`windowAttribution`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns an enumerated value describing the relationship of the container (i.e. top-level documen
suggestion applied

2024-04-18 09:45 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/windowattribution/index.md
> +  - : The current document is a descendant of the document the script was executed in, embedded inside it in an `<iframe>`.
updated

2024-04-18 09:46 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/windowattribution/index.md
> +  - : The script was executed in a version of the current document embedded inside the current document in an `<iframe>`.
updated

2024-04-18 17:25 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +- [Optimize long tasks](https://web.dev/articles/optimize-long-tasks), web.dev (2024): contains more information on long tasks and yielding.
Thank you!

2024-04-18 17:47 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/blockingduration/index.md
> +- [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing)
Correct, we don't add "reference", "property", or "data type" because the names already appear in code styling and we assume that to be indicative enough. Over in some CSS pages, we've wanted to, for example, distinguish between module pages and guide pages, that's where we've added the adjective. Honestly, it is a bit all over the place at the moment so we can omit "guide" here if that keeps the API pages similar.

2024-04-18 18:58 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started, in milliseconds.
Cool, thanks!

2024-04-18 19:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/executionstart/index.md
> +The **`executionStart`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and ex
for slightly smoother read?
```suggestion
The **`executionStart`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time when the script compilation finished and execution started.
```

2024-04-18 19:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started.
```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time when the script compilation finished and execution started.
```

2024-04-18 19:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/invokertype/index.md
> +  - : A handler function for the resolved state of a web platform promise, such as {{domxref("fetch()")}}. Note that in the case of promises, all the handlers of the same promises are grouped togethe
```suggestion
  - : A handler function for the resolved state of a web platform promise, such as {{domxref("fetch()")}}. Note that in the case of promises, all the handlers of the same promise are grouped together as a single `"script"` entry type.
```

2024-04-18 19:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/sourcefunctionname/index.md
> +browser-compat: api.PerformanceScriptTiming.sourceFunctionName
Ok cool 👍

2024-04-18 19:15 UTC, dipikabh commented on files/en-us/web/api/performancescripttiming/forcedstyleandlayoutduration/index.md
> +The **`forcedStyleAndLayoutDuration`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the total time spent by the s
thanks

2024-04-18 19:22 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time in milliseconds when the animation frame started.
```suggestion
  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time when the animation frame started.
```

2024-04-18 19:22 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/firstuieventtimestamp/index.md
> +- [Long animation frame timing](/en-US/docs/Web/API/Performance_API/Long_animation_frame_timing)
That is a good idea for automation! But maybe not a priority..
I'll leave this as is for now if it makes API docs stay consistent

2024-04-18 19:26 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time of the first UI event (for example mouse or keyboard) to be queued during the course of the current animation frame, in millisec
This is now the same as the intro on the firstuieventtimestamp/index.md page, which is good.

2024-04-18 21:50 UTC, dipikabh requested changes
I think I've looked at all the pages in this PR now.

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/styleandlayoutstart/index.md
> +The **`styleAndLayoutStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time
I am guessing this is also a timestamp (the starting time)?
Or is it the period spent in "style and layout calculations"? From the name, it seems it is the "Start" timestamp.
If updating, the change will need to be replicated everywhere.
```suggestion
The **`styleAndLayoutStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time period spent in style and layout calculations for the current animation frame.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time period spent in style and layout calculations for the current animation frame, in milliseconds.
this is probably a timestamp, not the duration

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +      - : A {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started.
```suggestion
      - : A {{domxref("DOMHighResTimeStamp")}} indicating the time when the script compilation finished and execution started.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +      - : String values indicating how the script was called (for example `"IMG#id.onload"` or `"Window.requestAnimationFrame"`) and the script entry point type (for example `"event-listener"` or `"r
```suggestion
      - : String values indicating how the script was called (for example, `"IMG#id.onload"` or `"Window.requestAnimationFrame"`) and the script entry point type (for example, `"event-listener"` or `"resolve-promise"`).
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +    > **Note:** Script attribution is only provided for scripts running in the main thread of a page, including same-origin `<iframe>`s. Cross-origin `<iframe>`s, [web workers](/en-US/docs/Web/API/We
This same text on another page could also be changed to"Note"
```suggestion
    > **Note:** Script attribution is provided only for scripts running in the main thread of a page, including same-origin `<iframe>`s. However, cross-origin `<iframe>`s, [web workers](/en-US/docs/Web/API/Web_Workers_API), [service workers](/en-US/docs/Web/API/Service_Worker_API), and [extension](/en-US/docs/Mozilla/Add-ons/WebExtensions) code will not have script attribution in long animation frames, even if they impact the duration of one.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +While LoAF thresholds are fixed at 50ms, this may lead to a large volume of reports when you first start performance optimization work. Initially, you may want to report LoAFs at a higher threshold v
```suggestion
While LoAF thresholds are fixed at 50ms, this may lead to a large volume of reports when you first start performance optimization work. Initially, you may want to report LoAFs at a higher threshold value and gradually decrease the threshold as you improve the site and remove the worst LoAFs. The following code could be used to capture LoAFs above a specific threshold for further analysis (for example, by sending them back to an analytics endpoint):
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +Long animation frame entries can be quite large, therefore think carefully about what data from each entry should be sent to analytics. For example, the summary times of the entries and the script UR
```suggestion
Long animation frame entries can be quite large; therefore, think carefully about what data from each entry should be sent to analytics. For example, the summary times of the entries and the script URLs might be enough for what you need.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The following code logs all LoAF entries greater than 150 ms where an interaction occurred during the frame. 150 is chosen because it is slightly less than the 200 millisecond Interaction to Next Pai
if we remove the previous reference to Google's INP
```suggestion
The following code logs all LoAF entries greater than 150ms where an interaction occurred during the frame. You could choose a higher or lower value depending on your needs.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +An alternative strategy is to look at which scripts appear most often in LoAF entries. Data could be reported back at a script and/or character position level to identify the most problematic scripts
```suggestion
An alternative strategy is to look at which scripts appear most often in LoAF entries. Data could be reported at the level of a script and/or character position to identify the most problematic scripts. This is useful in cases where themes or plugins causing performance issues are used across multiple sites.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The execution time of common scripts (or third-party origins) in LoAFs could be summed up and reported back to identify common contributors to LoAFs across a site or a collection of sites.
```suggestion
The execution times of common scripts (or third-party origins) in LoAFs could be summed and reported back to identify common contributors to LoAFs across a site or a collection of sites.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The Long Animation Frames API was preceded by the [Long Tasks API](https://w3c.github.io/longtasks/) (see {{domxref("PerformanceLongTaskTiming")}}) — this has a similar purpose and usage, exposing in
- Can we drop the link to the spec?
- Nit: Glossary page "See also" needs a minor correction - "Long Task API" should be "Long Tasks API"
- In "this has a similar purpose", it is not clear what "this" is referring to

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +This is useful, as long tasks can cause responsiveness issues. For example, if a user clicks a button while the main thread is dealing with a long task, the UI response to the click will be delayed u
- The beginning "This" needs to be clarified
- I think we should refrain from providing inline links to web.dev articles, they can be included in "See also".
```suggestion
This is useful because long tasks can cause responsiveness issues. For example, if a user clicks a button while the main thread is dealing with a long task, the UI response to the click will be delayed until the long task is completed. Conventional wisdom is to [break up long tasks into multiple smaller tasks](https://web.dev/articles/optimize-long-tasks) so that important interactions can be handled in between.
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +However, the Long Task API has its limitations:
```suggestion
However, the Long Tasks API has its limitations:
```

2024-04-18 21:50 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +> **Note:** See [Where long tasks fall short](https://github.com/w3c/long-animation-frames#where-long-tasks-fall-short) for more information on long task limitations.
Doesn't need to be a "Note"; it would sit better in the "See also" section.

2024-04-19 11:01 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/executionstart/index.md
> +The **`executionStart`** read-only property of the {{domxref("PerformanceScriptTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and ex
Sure, makes sense. Updated, here and on the interface landing page.

2024-04-19 11:02 UTC, chrisdavidmills commented on files/en-us/web/api/performancescripttiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started.
done

2024-04-19 11:05 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/index.md
> +  - : Returns a {{domxref("DOMHighResTimeStamp")}} representing the time in milliseconds when the animation frame started.
updated

2024-04-19 11:06 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +**Long animation frames** (LoAFs) can impact the user experience of a website. They can cause slow user interface (UI) updates, resulting in seemingly unresponsive controls and [janky](/en-US/docs/Gl
updated

2024-04-19 11:17 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +Good responsiveness means that a page responds quickly to interactions made with it. That involves being able to paint any updates needed by the user in a timely manner, and avoiding blocking these u
Update made. 

I'd prefer not to remove the reference to INP — it is an example of a commonly-used metric that provides good context for responsiveness.

2024-04-19 11:19 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +For smooth animations, updates need to be faster still — for an animation to run at a smooth 60 frames per second, each animation frame should render within around 16ms (1000/60).
I've made the change from "faster still" -> "fast".

I'm not sure the last sentence is needed. It repeats the information in the first sentence in the section.

2024-04-19 11:21 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +To return information on LoAFs and pinpoint troublemakers, you can observe performance timeline entries with an {{domxref("PerformanceEntry.entryType", "entryType")}} of `"long-animation-frame"` usin
"return" -> "obtain" done

We normally quote values that are strings, so I've not made the second change.

2024-04-19 11:22 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +Be aware however that the maximum buffer size for `"long-animation-frame"` entry types is 200, after which new entries are dropped, so the `PerformanceObserver` approach is the recommended one.
Done, apart from the quote dropping.

2024-04-19 11:23 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +## Examining "long-animation-frame" entries
code formatting added, but quotes not dropped

2024-04-19 11:24 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +Returned performance timeline entries with a type of `"long-animation-frame"` are represented by {{domxref("PerformanceLongAnimationFrameTiming")}} objects. This object has a {{domxref("PerformanceLo
Mostly used, with a few differences:

> Performance timeline entries returned with a type of `"long-animation-frame"` are represented by {{domxref("PerformanceLongAnimationFrameTiming")}} objects. This object has a {{domxref("PerformanceLongAnimationFrameTiming.scripts", "scripts")}} property containing an array of {{domxref("PerformanceScriptTiming")}} objects, each one of which contains information about a script that contributed to the long animation frame.

2024-04-19 11:27 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} indicating the total time in milliseconds that the main thread was blocked from responding to high priority tasks, such as user input. This is calculated by
Updates made; last sentence removed.

I'd prefer to link to this definition, as it seems more useful in this particular context.

2024-04-19 11:29 UTC, chrisdavidmills commented on files/en-us/web/api/performancelonganimationframetiming/styleandlayoutstart/index.md
> +The **`styleAndLayoutStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time
Correct, removed in all places.

2024-04-19 11:29 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +  - : A {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time period spent in style and layout calculations for the current animation frame, in milliseconds.
removed

2024-04-19 11:30 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +      - : A {{domxref("DOMHighResTimeStamp")}} indicating the time script compilation finished and execution started.
updated

2024-04-19 11:31 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +      - : String values indicating how the script was called (for example `"IMG#id.onload"` or `"Window.requestAnimationFrame"`) and the script entry point type (for example `"event-listener"` or `"r
updated

2024-04-19 11:33 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +    > **Note:** Script attribution is only provided for scripts running in the main thread of a page, including same-origin `<iframe>`s. Cross-origin `<iframe>`s, [web workers](/en-US/docs/Web/API/We
updated

2024-04-19 11:34 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +While LoAF thresholds are fixed at 50ms, this may lead to a large volume of reports when you first start performance optimization work. Initially, you may want to report LoAFs at a higher threshold v
updated

2024-04-19 11:36 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +An alternative strategy is to look at which scripts appear most often in LoAF entries. Data could be reported back at a script and/or character position level to identify the most problematic scripts
updated

2024-04-19 11:37 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The execution time of common scripts (or third-party origins) in LoAFs could be summed up and reported back to identify common contributors to LoAFs across a site or a collection of sites.
updated

2024-04-19 11:41 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The Long Animation Frames API was preceded by the [Long Tasks API](https://w3c.github.io/longtasks/) (see {{domxref("PerformanceLongTaskTiming")}}) — this has a similar purpose and usage, exposing in
1. I don't see why we need to drop the link to the spec. IF we do, readers won't have anywhere to go for further information on it.
2. Fixed
3. I updated this bit to "these specs both have a similar purpose and usage"

2024-04-19 11:48 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +This is useful, as long tasks can cause responsiveness issues. For example, if a user clicks a button while the main thread is dealing with a long task, the UI response to the click will be delayed u
Updated the start of the paragraph to "Cutting down the number of long tasks that occur on your website is useful because..."

Update made

Link removed and put into "See also"

2024-04-19 11:48 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +However, the Long Task API has its limitations:
Updated

2024-04-19 11:50 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +> **Note:** See [Where long tasks fall short](https://github.com/w3c/long-animation-frames#where-long-tasks-fall-short) for more information on long task limitations.
done, and done

2024-04-19 14:04 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +You can test whether the Long Animation Frames API is supported using {{domxref("PerformanceObserver.supportedEntryTypes")}}:
Yeah, the flaw does say it will redirect:

> Explanation: /en-US/docs/Web/API/PerformanceObserver/supportedEntryTypes redirects to /en-US/docs/Web/API/PerformanceObserver/supportedEntryTypes_static

It also says that the flaw is fixable.

If you want, it could be updated to:

`{{domxref("PerformanceObserver.supportedEntryTypes_static", "PerformanceObserver.supportedEntryTypes")}}`

...the way it's been done on [getEntriesByType](https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType#type).

2024-04-19 14:09 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +For smooth animations, updates need to be faster still — for an animation to run at a smooth 60 frames per second, each animation frame should render within around 16ms (1000/60).
Yeah, the last sentence was an attempt to reinforce by reiterating. But okay to skip it as well.

2024-04-19 14:11 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +To return information on LoAFs and pinpoint troublemakers, you can observe performance timeline entries with an {{domxref("PerformanceEntry.entryType", "entryType")}} of `"long-animation-frame"` usin
Oh ok, good to know, I don't think we quote the string values over in CSS

2024-04-19 14:14 UTC, dipikabh commented on files/en-us/web/api/performancelonganimationframetiming/styleandlayoutstart/index.md
> +The **`styleAndLayoutStart`** read-only property of the {{domxref("PerformanceLongAnimationFrameTiming")}} interface returns a {{domxref("DOMHighResTimeStamp")}} indicating the beginning of the time
Thank you!

2024-04-19 14:22 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +- [Where long tasks fall short](https://github.com/w3c/long-animation-frames#where-long-tasks-fall-short), Long Animation Frames API explainer (2024)
How about:
```suggestion
- [Where long tasks fall short](https://github.com/w3c/long-animation-frames#where-long-tasks-fall-short) on W3C (2024)
```

2024-04-19 14:22 UTC, dipikabh commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +This is useful, as long tasks can cause responsiveness issues. For example, if a user clicks a button while the main thread is dealing with a long task, the UI response to the click will be delayed u
Excellent! Thank you

2024-04-19 14:37 UTC, dipikabh approved these changes
Thanks for addressing all my comments, @chrisdavidmills! I'm leaving a +1 with just a few minor things for you to go over.

Appreciate your work on adding all these pages, thank you!

2024-04-19 14:39 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +- [Where long tasks fall short](https://github.com/w3c/long-animation-frames#where-long-tasks-fall-short), Long Animation Frames API explainer (2024)
I dunno; I would expect a link labeled "W3C" to go somewhere on W3.org.

2024-04-19 14:40 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +## Comparison with the Long Tasks API
Sure, updated

2024-04-19 14:46 UTC, chrisdavidmills commented on files/en-us/web/api/performance_api/long_animation_frame_timing/index.md
> +The Long Animation Frames API was preceded by the [Long Tasks API](https://w3c.github.io/longtasks/) (see {{domxref("PerformanceLongTaskTiming")}}) — these specs both have a similar purpose and usage
updated

2024-04-19 14:51 UTC, merged