Update: oklab()
mdn/content pull request #33048
Opened 2024-04-11 23:26 UTC by estelle

Similar to https://github.com/mdn/content/pull/33007
part of https://github.com/openwebdocs/project/issues/194

2024-04-16 18:09 UTC, dipikabh requested changes
Thanks, @estelle. The page is looking good. A few updates are needed.

2024-04-16 18:09 UTC, dipikabh commented on files/en-us/web/css/color_value/oklch/index.md
> +With the initial starting colors blue, red, and green, we declare progressively smaller values for chroma on them: starting from full color saturation at the highest value of `150` (equivalent to `10
```suggestion
With the initial starting colors blue, red, and green, we declare progressively smaller values for chroma on them: starting from full color saturation at the highest value of `0.4` (equivalent to `100%`) down to `0.01` (equivalent to `2%`), which is almost grey for all the colors.
```

2024-04-17 00:10 UTC, estelle commented on files/en-us/web/css/color_value/oklch/index.md
> +With the initial starting colors blue, red, and green, we declare progressively smaller values for chroma on them: starting from full color saturation at the highest value of `150` (equivalent to `10
good catch!

2024-04-17 00:28 UTC, estelle reviewed
Thanks for the review @dipikabh. especially for catching the 150 v. 0.4. good catch!

2024-04-17 00:28 UTC, estelle commented on files/en-us/web/css/color_value/oklch/index.md
> +OKlch is the cylindrical form of {{CSSXref("color_value/oklab", "OKlab")}}. It uses the same `L` axis as the {{cssxref("color_value/oklab","oklab()")}} color function of the [CIELab color space](/en-
rewrote the whole thing to:

> The **`oklch()`** functional notation expresses a given color in the Oklab {{glossary("color space")}}. `oklch()` is the cylindrical form of {{CSSXref("color_value/oklab", "OKlab()")}}, using the same `L` axis, and polar Chroma (`C`) and Hue (`h`) coordinates.

2024-04-17 00:28 UTC, estelle commented on files/en-us/web/css/color_value/oklch/index.md
> +  - : A {{CSSXref("&lt;number&gt;")}} between `0` and `1`, a {{CSSXref("&lt;percentage&gt;")}} between `0%` and `100%`, or the keyword `none` (equivalent to `0%` in this case). This value specifies t
moved the lightness /brightness sentence to be last in the paragraph

2024-04-17 12:46 UTC, dipikabh approved these changes
Thanks, @estelle! Just a few minor nits but it is ready to go. Leaving my +1.

2024-04-17 18:11 UTC, estelle commented on files/en-us/web/css/color_value/oklch/index.md
> +The **`oklch()`** functional notation expresses a given color in the Oklab {{glossary("color space")}}. `oklch()` is the cylindrical form of {{CSSXref("color_value/oklab", "oklab()")}}, using the sam
the color space is OKlab. OKlch is the color function. 

I finally figured it out when i was writing the "color values" guide. See https://pr33071.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/CSS_colors/Color_values#lab_and_oklab. The color spaces we generally will write about are `srgb`, `CIE L*a*b`, and `oklch`. 

- lch() and lab() are in "CIE Lab."
- oklch() and oklab() are in "oklch"

Unless I am wrong again.

2024-04-17 18:19 UTC, merged