Draft: new color guide and associated link updates
mdn/content pull request #33071
Opened 2024-04-13 08:15 UTC by estelle

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-04-19 15:02 UTC, caugner commented on files/en-us/web/css/css_colors/color_values/index.md
> +title: CSS color values
@estelle If you want this page to show up as "Color values" in the sidebar, add this:

```suggestion
title: CSS color values
short-title: Color values
```

2024-04-23 13:24 UTC, chrisdavidmills requested changes
@estelle I decided to go through all of it today, and get it out of the way. Quite a few comments here, but I think this is going in the right direction — the multiple guides are definitely a lot more readable than the big uber article of old.

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +Make sure your content is [accessible](/en-US/docs/Web/Accessibility). There are several ways color can be an {{Glossary("accessibility")}} problem. Improper or careless use of color can result in a
```suggestion
Make sure your content is [accessible](/en-US/docs/Web/Accessibility). There are several ways color can create an {{Glossary("accessibility")}} problem. Improper or careless use of color can result in a website or app that a percentage of your target audience may not be able to use adequately, resulting in lost traffic, lost business, and possibly even a public relations problem or a lawsuit. So it's important to consider your use of color carefully.
```

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +It's important to [understand color and luminance](/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance) and to always consider [color blindness](https://medlineplus.gov/colorblindness.ht
Couple of additional points: 

1. You forgot the URL in your "vestibular disorders" link.
2. It's probably worth mentioning that you should also consider turning animation off altogether for those who have a preference for reduced animation. (and link to the prefers-reduced-motion MQ?)

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +Using an eyedropper tool, we identify a color we like and determine that the color in question is `#D79C7A`, which is an appropriate rusty orange-red color that's so stereotypical of the Martian surf
```suggestion
Using an eyedropper tool, we identify a color we like and determine that the color in question is `#D79C7A`, which is an appropriate rusty orange-red color stereotypical of the Martian surface.
```

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +We now see a monochromatic palette based on the color we picked from the Mars photo. If you need a lot of related colors for some reason, those are likely to be good ones. But what we really want is
```suggestion
We now see a monochromatic palette based on the color we picked from the Mars photo. If you need a lot of related colors for some reason, those are likely to be good ones. But what we really want is an accent color. Something that will pop alongside the base color. To find that, we click the "add complementary" toggle underneath the menu that lets you select the palette type (currently "Monochromatic"). Paletton computes an appropriate accent color; clicking on the accent color in the bottom-right corner tells us that this color is `#508D7C`.
```

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +Once you have these colors, you will probably still need to select appropriate neutral colors. Common design practice is to try to find the sweet spot where there's just enough contrast that the text
```suggestion
Once you have these colors, you should select appropriate neutral colors. It is common design practice to try to find the sweet spot where there's just enough contrast that the text is crisp and readable without being too harsh for the eyes. It's easy to go too far in one way or another so be sure to get feedback on your colors once you've selected them and have examples of them in use available. If the contrast is too low, your text will be washed out by the background, leaving it unreadable, but if your contrast is too high, the user may find your site garish and unpleasant to look at.
```

2024-04-23 13:24 UTC, chrisdavidmills commented on files/en-us/web/css/font-palette/palette-mix/index.md
> +- {{glossary("color spaces")}}
```suggestion
- {{glossary("Color space")}}
```

2024-04-23 16:54 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +  - : Each must be an {{cssxref("&lt;integer&gt;")}} value between 0 and 255 (inclusive), or a {{cssxref("&lt;percentage&gt;")}} from 0% to 100%.
```suggestion
  - : Each must be an {{cssxref("&lt;integer&gt;")}} value between 0 and 255 (inclusive), a {{cssxref("&lt;percentage&gt;")}} from 0% to 100%, or the keyword `none`, which is equal to `0` in this case.
```

2024-04-24 06:41 UTC, estelle commented on files/en-us/web/css/css_colors/color_picker_tool/index.md
> +- {{CSSxRef("color_value/color", "color()")}}, which defines a color in any given color space.
used "the"

2024-04-24 06:42 UTC, estelle commented on files/en-us/web/css/css_colors/color_picker_tool/index.md
> +This tool will help you understand the syntax of the color notations in the sRGB color space.
moved into first paragraph

2024-04-24 06:49 UTC, estelle commented on files/en-us/web/css/css_colors/color_picker_tool/index.md
> +The older sRGB color notations, `<hex-color>`, `hsl()`, `hwb()`, and `rgb()`, do not express the full spectrum of visible colors. When using `hsl()`, `hwb()`, and `rgb()` to define a [relative color]
it's kind of why i included color() at all

changed to:

> > **Note:** The older sRGB color notations - `hsl()`, `hwb()`, and `rgb()` - do not express the full spectrum of visible colors. The `color()` function supports a much wider color gamut. For this reason, if using these functions to define [relative colors](/en-US/docs/Web/CSS/CSS_colors/Relative_colors), the output color returned by querying {{domxref("HTMLElement.style")}} property or the {{domxref("CSSStyleDeclaration.getPropertyValue()")}} method is a [`color(srgb ...)`](/en-US/docs/Web/CSS/color_value/color) value.

2024-04-24 06:53 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +#### HTML color picker
html color input type

2024-04-24 07:07 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +The values of `W` and `B` and range from `0%` to `100%` (or `0` to `1`). If the combined values of `W` and `B` is 100% (or `1`) or greater, the color will be grey, similar to setting the `s` to `0%`
added  / 50% to the last hsl example with a sentence explaining it.

2024-04-24 07:09 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +### LCH and OKLCH: CIELAB and Oklab color spaces
added lnks

2024-04-24 07:11 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +Wouldn't it be fantastic if you could simply change a hue of a color on a site without making text illegible? You can in the CIELAB and Oklab color spaces. For the CIELAB and oklab color spaces, you
kept them because that's what i linked, but made it 2 paragraphs.

2024-04-24 22:01 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +The `lch()` and `oklch()` both include a hue component, and are discussed here. The [`lab()` and `oklab()`](#lab-and-oklab) define color based on a red/green and a yellow/blue color axis and are desc
true. removed.

2024-04-24 22:01 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +<div id="srgb"></div>
done.

2024-04-24 23:16 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +Lab represents the entire range of colors that humans can see by specifying the color's lightness (`L`), a red/green axis value (`a`), a blue/yellow axis value (`b`), and an optional alpha transparen
literally a duplicate. sorry. removed.

2024-04-24 23:16 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +The `a` value is `<number>` between `-125` and `125` for `lab()` or `-0.4` and `0.4` for `oklab()`, a `<percentage>` between `-100%` and `100%`, or the keyword `none` (equivalent to `0%` in this case
i don't see an edit here.

2024-04-25 12:09 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/applying_color/index.md
> +> **Note:** We are using multiple [different CSS color notations](/en-US/docs/Web/CSS/CSS_colors/Color_values) in this example to demonstrate their use. This is not recommended for production code. W
```suggestion
> **Note:** We are using multiple [different CSS color value types](/en-US/docs/Web/CSS/CSS_colors/Color_values) in this example to demonstrate their use. This is not recommended for production code. When writing CSS, use the most intuitive value type for you and your team.
```

2024-04-25 12:09 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/applying_color/index.md
> +> **Note:** We are using multiple [different CSS color notations](/en-US/docs/Web/CSS/CSS_colors/Color_values) in this example to demonstrate their use. This is not recommended for production code. W
Simplified; I also wanted to make sure the link text more closely matched the name of the page you were linking to, to avoid potential confusion.

2024-04-25 12:09 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/applying_color/index.md
> +  - : The Web Graphics Library is an OpenGL ES-based API for drawing high-performance 2D and 3D graphics on the Web. See our [WebGL tutorial](/en-US/docs/Web/API/WebGL_API/Tutorial) to find out more.
Perfect.

2024-04-25 13:12 UTC, chrisdavidmills approved these changes
Wonderful work @estelle!

I've had a good look through your edits, and it is looking pretty much ready to go, IMO.

I've made a few more minor comments for you to look through, but I'm now setting this to approved, so you can get on and merge when done.

2024-04-25 13:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/color_values/index.md
> +In addition, as the older sRGB color notations discussed above - `hsl()`, `hwb()`, and `rgb()` - do not express the full spectrum of visible colors and the `color()` function supports a much wider co
```suggestion
The older sRGB color notations discussed above — `hsl()`, `hwb()`, and `rgb()`— do not express the full spectrum of visible colors, while the `color()` function supports a much wider color gamut. As a result, when using the older functions types to define relative colors (discussed next), the output color returned by querying {{domxref("HTMLElement.style")}} property or the {{domxref("CSSStyleDeclaration.getPropertyValue()")}} method will be a `color(srgb ...)` value. To see an example of converting these color functions to `color()` in the `srgb` color space, check out our [color picker tool](/en-US/docs/Web/CSS/CSS_colors/Color_picker_tool).
```

2024-04-25 13:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/color_values/index.md
> +In addition, as the older sRGB color notations discussed above - `hsl()`, `hwb()`, and `rgb()` - do not express the full spectrum of visible colors and the `color()` function supports a much wider co
I also think you should remove this paragraph from here, put it in place of the related paragraph in the next section, and remove the "(discussed next)" bit. It seems weird that the detail is here and not in the relative colors section.

Yes, this section uses `color()`, but this detail is not essential for an understanding of the example.

2024-04-25 13:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_colors/using_color_wisely/index.md
> +While higher [color contrast](https://digital.gov/guides/accessibility-for-teams/visual-design/#color-and-contrast) is often a good thing when it comes to accessibility, when animating, especially ra
```suggestion
While higher [color contrast](https://digital.gov/guides/accessibility-for-teams/visual-design/#color-and-contrast) is often a good thing when it comes to accessibility, when animating, especially rapidly, [reducing color contrast](/en-US/docs/Web/Accessibility/Seizure_disorders#reduce_contrast) on animating elements reduces seizure risk. If you include animations, use the [`prefers-reduced-motion`](/en-US/docs/Web/CSS/@media/prefers-reduced-motion) {{cssxref("@media")}} query feature to reduce animations for users who have selected that preference.
```

2024-04-25 17:22 UTC, estelle commented on files/en-us/web/css/css_colors/applying_color/index.md
> +> **Note:** It is important to [use colors wisely](/en-US/docs/Web/CSS/CSS_colors/Using_color_wisely). Always select appropriate colors, ensure there is enough contrast between text and the backgroun
went with:

> ensuring the contrast between text and the background is sufficient

2024-04-25 17:28 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +      <td><code>hsl(270deg 90% 50%)</code></td>
good catch!

2024-04-25 17:33 UTC, estelle commented on files/en-us/web/css/css_colors/color_values/index.md
> +In addition, as the older sRGB color notations discussed above - `hsl()`, `hwb()`, and `rgb()` - do not express the full spectrum of visible colors and the `color()` function supports a much wider co
changed to:

> 
Understanding `color()` is important when it comes to relative colors, discussed next. The older sRGB color notations discussed above — `hsl()`, `hwb()`, and `rgb()`— do not express the full spectrum of visible colors, while the `color()` function supports a much wider color gamut. As a result, when using the older functions types to define relative colors, the output color returned by querying {{domxref("HTMLElement.style")}} property or the {{domxref("CSSStyleDeclaration.getPropertyValue()")}} method will be a `color(srgb ...)` value. 

> To see an example of converting the `hsl()`, `hwb()`, and `rgb()` color functions to `color()` in the `srgb` color space, check out our [color picker tool](/en-US/docs/Web/CSS/CSS_colors/Color_picker_tool).

to make it more relevant here (i want to add it to color() instead of relative because i want to express why learning color is actually important.

2024-04-25 17:43 UTC, merged