Window.postMessage() - See Also
mdn/content pull request #3318
Opened 2021-03-20 14:46 UTC by hinell

Add see also section entry-link for experimental BroadcastChannel

2021-03-22 18:14 UTC, jpmedley requested changes

2021-03-22 18:14 UTC, jpmedley commented on files/en-us/web/api/window/postmessage/index.html
> +  <li>{{domxref("BroadcastChannel")}}</li> - For cross-origin communication.
```suggestion
  <li>{{domxref("BroadcastChannel")}} - For cross-origin communication.</li>
```

2021-03-23 03:38 UTC, wbamberg commented on files/en-us/web/api/window/postmessage/index.html
> +  <li>{{domxref("BroadcastChannel")}}</li> - For cross-origin communication.
Sorry to drive-by here, but for my education as much as anything - I thought `BroadcastChannel` was for *same-origin* messaging, and `postMessage` is for cross-origin messaging?

From https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API:

> The Broadcast Channel API allows basic communication between browsing contexts (that is, windows, tabs, frames, or iframes) and workers on the same origin.

2021-03-23 14:42 UTC, hinell commented on files/en-us/web/api/window/postmessage/index.html
> +  <li>{{domxref("BroadcastChannel")}}</li> - For cross-origin communication.
Yup. that's the difference. That's why it's linked from inside **See also.** It's related, but indirectly.

2021-03-24 17:53 UTC, jpmedley approved these changes

2021-03-24 17:53 UTC, merged