URL.parse() static method docs
mdn/content pull request #33207
Opened 2024-04-22 07:54 UTC by hamishwillee

FF126 supports the `URL.parse` static method. This adds a page with a live example, and does some fixes and cross linking to the `URL` constructor.

Related docs work can be tracked in #33080

2024-04-26 19:06 UTC, wbamberg requested changes
I guess the big comment here which is probably out of scope for this PR is that we should have a definitive separate guide to "resolving relative URLs" that we can point to from all the places that do this.

2024-04-26 19:06 UTC, wbamberg commented on files/en-us/web/api/url/parse_static/index.md
> +  log("\nRelative URL with base URL supplied as a URL object");
```suggestion
  log("\n Relative URL with base URL supplied as a URL object");
```

2024-04-26 19:06 UTC, wbamberg commented on files/en-us/web/api/url/parse_static/index.md
> +- [A polyfill of `URL.canParse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
Why link to a polyfill for a different method?

2024-04-26 19:06 UTC, wbamberg commented on files/en-us/web/api/url/url/index.md
> +    If `url` is an absolute URL, a given `base` will be ignored.
Again "ignored" is misleading.

2024-04-26 19:06 UTC, wbamberg commented on files/en-us/web/api/url/url/index.md
> +If you need a strict concatenation of the two arguments the `url` must not have a leading slash and the `base` must have a trailing slash.
So one reason I didn't like that PR was that it seemed like the reader/PR author just wanted URL to concatenate, but if you just want concatenation, why not just use concatenation? `${base}${url}`. I didn't really have the energy to argue about it though. But it does suggest to me that we should have much better documentation for resolving relative URLs, then we could just link to that from places like this.

2024-04-29 00:41 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +  - : A string or any other object with a {{Glossary("stringifier")}} — including, for example, an {{htmlelement("a")}} or {{htmlelement("area")}} element — that represents an absolute or relative UR
No, I would prefer we were accurate.

```suggestion
  - : A string or any other object with a {{Glossary("stringifier")}} — including, for example, an {{domxref("HTMLAnchorElement")}} or {{domxref("HTMLAreaElement")}} element — that represents an absolute or relative URL.
```

2024-04-29 00:45 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +- [A polyfill of `URL.canParse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
Copy paste error

2024-04-29 00:45 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +- [A polyfill of `URL.canParse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
```suggestion
- [`URL()` constructor](/en-US/docs/Web/API/URL/URL), which throws if the passed parameters define an invalid URL
```

2024-04-29 00:45 UTC, hamishwillee commented on files/en-us/web/api/url/url/index.md
> +    If `url` is an absolute URL, a given `base` will be ignored.
```suggestion
    If `url` is an absolute URL, a given `base` will not be used to create the resulting URL.
```

2024-04-29 00:54 UTC, zloirock commented on files/en-us/web/api/url/parse_static/index.md
> +- [A polyfill of `URL.canParse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
`core-js` contains `URL.parse` polyfill by this link, just the title should be renamed.

2024-04-29 00:55 UTC, zloirock commented on files/en-us/web/api/url/parse_static/index.md
> +- [A polyfill of `URL.canParse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
@hamishwillee

2024-04-29 01:07 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +> In particular, you can use an existing {{domxref("URL")}} object for either argument, and it will be stringified to the object's {{domxref("URL.href", "href")}} property.
We are a bit. I've modified the `url` and this so that the examples are in the  note. That way the `url` section is more concise and this note reads as useful additional information.

2024-04-29 01:23 UTC, zloirock commented on files/en-us/web/api/url/parse_static/index.md
> +- [`URL()` constructor](/en-US/docs/Web/API/URL/URL), which throws if the passed parameters define an invalid URL
https://github.com/mdn/content/pull/33207#discussion_r1582459147
```suggestion
- [`URL()` constructor](/en-US/docs/Web/API/URL/URL), which throws if the passed parameters define an invalid URL
- [A polyfill of `URL.parse()`](https://github.com/zloirock/core-js#url-and-urlsearchparams) is available in [`core-js`](https://github.com/zloirock/core-js)
```

2024-04-29 01:55 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +- [`URL()` constructor](/en-US/docs/Web/API/URL/URL), which throws if the passed parameters define an invalid URL
Thanks!

2024-04-29 02:01 UTC, hamishwillee commented on files/en-us/web/api/url/url/index.md
> +If you need a strict concatenation of the two arguments the `url` must not have a leading slash and the `base` must have a trailing slash.
I agree. I'm just trying to keep the work for this part constrained. Let me think on it.

2024-04-29 02:02 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +  log(`Url.parse("${url}", "${base}")\n// ${result}`);
Thanks. Good point.

2024-04-29 02:03 UTC, hamishwillee commented on files/en-us/web/api/url/parse_static/index.md
> +  log("//Relative URL appended to valid base URL");
@wbamberg
1. I have removed comments in the logs. 
   - The purpose of that was to provide clear relationship between the javascript and the log output - because by the time you got to the output it isn't so clear what the log is showing. 
   - This is now fixed by using literals (as you suggested) which reduces the separation, and using numbered log items to match the numbered code.
2. Yes, this makes sense. I don't really don't want to do it because of the additional thinking/effort :-(
3. Fixed up all the `Url .`=> `URL`. Sorry.
4. 
Appreciate all the advice.

2024-04-29 06:17 UTC, hamishwillee commented on files/en-us/web/api/url_api/resolving_relative_urls/index.md
> +---
@wbamberg Here is the updated "Resolving relative URLs" doc. Took me longer than expected and is much more "labored". Mostly because I wanted to be crystal clear in my understanding, and at the end of that I had lots of examples.

The actual behaviour is relatively simple - relative URLs are relative to the current directory (either down or up via a parent) or the site root. The current directory is the base URL up to the last forward slash. That's it, other than a tiny wrinkle that if your relative URL is "" then the whole base URL is used. I have not documented that, since its a stupid thing to do.

I haven't cut it back because while it is that simple, when I look at the examples I see edge cases that might not be so obvious. Such as the fact that if you don't specify a forward slash on the site, you get one by magic. And so on.
Would welcome feedback.

2024-04-29 06:19 UTC, hamishwillee commented on files/en-us/web/api/url/url/index.md
@wbamberg FYI, there are a bunch of examples below that demonstrate resolving URLs. I propose we delete those and link to the new topic?

https://github.com/mdn/content/pull/33207/files#r1582583678

2024-04-29 07:28 UTC, hamishwillee commented on files/en-us/web/api/url_api/resolving_relative_urls/index.md
> +---
Hmmm. I just scanned it again. It really does seem very heavyweight given the actual simplicity of the rules. 
If you don't have a chance to look I might rejig it later in the week (all to close to it right now). But my feeling on quick scan is that my summary in comment above with a few examples is probably enough.

2024-04-30 03:35 UTC, hamishwillee commented on files/en-us/web/api/url/url/index.md
Deleted.

2024-04-30 03:35 UTC, hamishwillee commented on files/en-us/web/api/url/url/index.md
> -### Merging of url and base paths
FYI, the merging of base paths is covered in the resolving relative URLs topic

2024-04-30 03:37 UTC, hamishwillee commented
@wbamberg All ready for another review. Includes new doc for Resolving URLs.

2024-05-04 18:56 UTC, wbamberg commented
Thank you for writing this! I think relative URL resolution is quite an important thing that AFAIK is documented nowhere on MDN. The nearest thing is https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL which doesn't do into enough detail.

But I have a couple of high level comments on this.

First, I think it's better to present this as a generic algorithm - "how browsers handle relative URLs" - rather than specifically as a feature of the `URL` interface. Because it is an algorithm for how browsers handle relative paths _in general_, and `URL` is just referring to that.

Second, I like that you have lots of examples and I appreciate explaining it in a fairly informal way. But it would be great if we could also present it in a more rigorous/precise way. The trick is to explain https://datatracker.ietf.org/doc/html/rfc3986.html#section-5.2 in a way that is more comprehensible but just as precise.

I've had a shot at writing this up below, perhaps we could get some version of this? What do you think?

*******

We could present URL resolution as a three-step process:

- split both URLs into their components
- calculate the value of each combined component
- compose the components

## Split URLs

First, split base and relative URLs into their components (we already define the components in https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL):

- scheme
- authority
- path
- query
- fragment

## Calculate component values

- if relative.scheme exists, components are:

  - relative.scheme, relative.authority, remove_dots(relative.path), relative.query, relative.fragment

- if relative.authority exists, components are:

  - base.scheme, relative.authority, remove_dots(relative.path), relative.query. relative.fragment

- if relative.path is "" and !relative.query, components are:

  - base.scheme, base.authority, base.path, base.query. relative.fragment

- if relative.path is "" and relative.query, components are:

  - base.scheme, base.authority, base.path, relative.query. relative.fragment

- if relative.path starts with "/", components are:

  - base.scheme, base.authority, remove_dots(relative.path), relative.query. relative.fragment

- if relative.path does not start with "/", components are:
  - base.scheme, base.authority, remove_dots(merge(base.path, relative.path)), relative.query. relative.fragment

### Merging base and relative paths

- if base has an authority and an empty path, then path is "/" followed by relative.path
- otherwise, remove from base.path all characters after the rightmost "/", (or the whole of base.path if base.path does not contain "/"), then append relative.path

(I'm not sure if we can assume that base must have an authority, and therefore simplify this a bit?)

### Remove dots

This is the process of removing "./" characters and processing "../" to remove parents. This is quite hard to explain precisely...

## Compose components

Finally we combine the components to produce a single URL:

- if scheme: add scheme + ":"
- if authority: add "//" + authority
- add path
- if query: add "?" + query
- if fragment: add "#" + fragment

Again, can we assume that scheme and authority are required for HTTPS URLs, so as to simplify the explanation?

2024-05-06 05:29 UTC, hamishwillee commented
@wbamberg 
1. Yes, I think this approach has merit. In particular because it catches all the edge cases - including a few like what happens if the relative URL is `""`, which I was aware of from testing but glossed over. I also prefer it because it is scalable in the event that the algorithm changes in some way.
2.  Should it still live under the API doc where I have put it? Given the URL API is effectively a standardized implementation of that algorithm it probably makes sense, and I can't think of a better place. 

My concern here is that I want to get docs for `URL.parse()` in to meet my FF126 release goals, and I have many other tasks to get through before that happens next week. This already took longer than expected and I think having some docs on the other things is more important than getting this perfect.

So if we agree this is the right place for the doc and that the doc is "better than what was there before", then I suggest I rename to "how browsers handle relative URLs" and you merge as is. Then I come back to this after the release.

2024-05-06 18:17 UTC, wbamberg commented on files/en-us/web/api/url/parse_static/index.md
> +    When specify a `base` URL, the resolved URL is not simply a concatenation of `url` and `base`.
```suggestion
    When you specify a `base` URL, the resolved URL is not simply a concatenation of `url` and `base`.
```

2024-05-06 18:32 UTC, wbamberg reviewed
Thanks!

TBH I didn't put a lot of time into reviewing the guide, since if it will get rewritten anyway there didn't seem like much point.

2024-05-06 18:32 UTC, wbamberg commented on files/en-us/web/api/url/parse_static/index.md
> +    When specify a `base` URL, the resolved URL is not simply a concatenation of `url` and `base`.
```suggestion
    When you specify a `base` URL, the resolved URL is not simply a concatenation of `url` and `base`.
```

2024-05-06 18:32 UTC, wbamberg commented on files/en-us/web/api/url/parse_static/index.md
> +    Parent-relative and current-directory-relative URLS are relative to the current directory of the `base` URL, which includes only path segments up until the last forward-slash, but not any after.
```suggestion
    Parent-relative and current-directory-relative URLs are relative to the current directory of the `base` URL, which includes only path segments up until the last forward-slash, but not any after.
```

2024-05-06 18:59 UTC, wbamberg commented
It seems like the spec deprecates the whole "relative URL" terminology:

> NOTE: Previous specifications used the terms "partial URI" and
      "relative URI" to denote a relative reference to a URI.  As some
      readers misunderstood those terms to mean that relative URIs are a
      subset of URIs rather than a method of referencing URIs, this
      specification simply refers to them as relative references.

(https://datatracker.ietf.org/doc/html/rfc3986.html#section-1.2.3)

2024-05-06 23:26 UTC, hamishwillee commented on files/en-us/web/api/url_api/resolving_relative_urls/index.md
> +The methods resolve the relative URL in the same way: the main difference between them is that the `URL()` constructor throws if invalid URLs are passed, while `parse()` returns `null`.
Only difference with respect to resolution (of course one is static, and the other is on the prototype).
```suggestion
The methods resolve the relative URL in the same way, except that the `URL()` constructor throws if invalid URLs are passed, while `parse()` returns `null`.
```

2024-05-06 23:30 UTC, hamishwillee commented on files/en-us/web/api/url_api/resolving_relative_urls/index.md
> +A relative path prefixed with `./` or no prefix, such as `./article` or `article`, is relative to the current directory of the URL represented by the `base` argument.
```suggestion
A relative path prefixed with `./` or no prefix, such as `./article`, `article`, or `./article/`, is relative to the current directory of the URL represented by the `base` argument.
```

2024-05-06 23:31 UTC, hamishwillee commented on files/en-us/web/api/url_api/resolving_relative_urls/index.md
> +// => https://test.example.org/api/v2/story
```suggestion
Similarly, below both base URL strings have a current directory of `https://test.example.org/api/v2/`.
We append `story/` and `story` to these to resolve the final absolute URL.

```js
log(new URL("./story/", "https://test.example.org/api/v2/").href);
// => https://test.example.org/api/v2/story/
log(new URL("./story", "https://test.example.org/api/v2/v3").href);
// => https://test.example.org/api/v2/story
```

2024-05-07 00:16 UTC, hamishwillee commented
Thanks @wbamberg 

I have 
- accepted your suggestions
- renamed the document to "Resolving relative references to a URL" and cross linked around the place
- In the three affected docs I now refer to relative URLs as relative references as per spec.
- Created https://github.com/mdn/content/issues/33455 to keep the follow on fixes alive.

2024-05-07 21:41 UTC, wbamberg approved these changes
👍 thank you @hamishwillee !

2024-05-07 21:42 UTC, merged