CSS modules: CSS table
mdn/content pull request #33236
Opened 2024-04-23 13:10 UTC by estelle

* made the table module follow the newish template guidelines
* added links to the module to the five table related properties.

2024-04-23 22:59 UTC, dipikabh requested changes
Thanks for these updates, @estelle. I’ve suggested some edits and have a few questions for you to consider.

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
>  {{Specifications}}
I think we should replace the `spec-urls` front matter key value with "https://drafts.csswg.org/css-tables-3/", the same spec link that you're also using in the note after the Specifications table

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +- [CSS flex layout](/en-US/docs/Web/CSS/CSS_flexible_box_layout) module
```suggestion
- [CSS flexible box layout](/en-US/docs/Web/CSS/CSS_flexible_box_layout) module
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +This CSS module defines styles applicable to the HTML {{htmlelement("table")}} element, used to render tabular data. By default, tables are rendered as a two-dimensional grid of table cells lined up
```suggestion
This CSS module defines styles applicable to the HTML {{htmlelement("table")}} element, which is used to render tabular data. By default, tables are rendered as a two-dimensional grid with cells lined up in a series of consecutive rows and columns. This layout is generated from the table structure and sized according to the content of the cells. This module also enables defining the position of the table's {{htmlelement("caption")}}, if present.
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +  - : An overview of CSS layouts, including setting table-related `display` values to enable using CSS table properties on any element.
```suggestion
  - : An overview of CSS layouts, including how to set table-related `display` values to enable using CSS table properties on any element.
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +  - : A building block guide to improving the appearance of HTML tables, covering table styling techniques.
```suggestion
  - : A guide to improving the appearance of HTML tables, covering table styling techniques.
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +  - : Introduction to HTML tables, including the HTML for rows and cells, headings, making cells span multiple columns and rows, and grouping cells in a column for styling purposes.
What do you think about moving both the HTML guides to "See also"?
```suggestion
  - : An introduction to HTML tables, including the HTML for creating rows and cells, headings, making cells span multiple columns and rows, and grouping cells in a column for styling purposes.
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +  - : Advanced HTML table features including captions and grouping table rows into table head, body and footer sections — as well as looking at the accessibility of tables for visually impaired users
What do you think about moving the link to the HTML guide to "See also"?
```suggestion
  - : A look at advanced HTML table features, including captions and grouping table rows into table head, body and footer sections — as well as looking at the accessibility of tables for visually impaired users.
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +- [CSS table layout](/en-US/docs/Learn/CSS/CSS_layout/Introduction#table_layout)
Like the other two, should we prefix this and the next also with "Learn: "

```suggestion
- [Learn: CSS table layout](/en-US/docs/Learn/CSS/CSS_layout/Introduction#table_layout)
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +- [Styling tables](/en-US/docs/Learn/CSS/Building_blocks/Styling_tables)
```suggestion
- [Learn: Styling tables](/en-US/docs/Learn/CSS/Building_blocks/Styling_tables)
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +- HTML table-related elements
The HTML element list can be moved to after the CSS property list. WDYT?
```suggestion
- HTML table-related elements:
```

2024-04-23 22:59 UTC, dipikabh commented on files/en-us/web/css/css_table/index.md
> +- [CSS box sizing](/en-US/docs/Web/CSS/CSS_box_sizing) module
```suggestion
- [CSS box model](/en-US/docs/Web/CSS/CSS_box_model) module
```

2024-04-23 23:16 UTC, estelle reviewed
Thanks for the review @dipikabh.

I committed most of your changes, and commented on those I did not commit.

2024-04-23 23:16 UTC, estelle commented on files/en-us/web/css/css_table/index.md
> +- [CSS box sizing](/en-US/docs/Web/CSS/CSS_box_sizing) module
The original was correct. See https://github.com/mdn/content/pull/33182

2024-04-23 23:16 UTC, estelle commented on files/en-us/web/css/css_table/index.md
>  {{Specifications}}
See the note below: the spec is not ready for implementation, and has a big orange warning when you visit the page, so opting not to update the spec-url.

2024-04-23 23:16 UTC, estelle commented on files/en-us/web/css/css_table/index.md
> +  - : Introduction to HTML tables, including the HTML for rows and cells, headings, making cells span multiple columns and rows, and grouping cells in a column for styling purposes.
i want to leave them here because few developers know how to write tables correctly, so prefer to leave them under guides in the hopes that they are read.

2024-04-23 23:16 UTC, estelle commented on files/en-us/web/css/css_table/index.md
> +- HTML table-related elements
I think the HTML elements are more relevant to anyone using this spec's properties, but won't argue if you insist.

2024-04-25 15:46 UTC, dipikabh approved these changes
Thanks for addressing the comments, @estelle! Leaving a +1 with one suggestion outstanding to possibly reword the "Note".

2024-04-25 16:23 UTC, merged