Update out of date time reference
mdn/content pull request #3330
Opened 2021-03-21 13:48 UTC by ckartchner

- Remove the reference to the time since 2010. As a living document, temporal references quickly become outdated.
- Clarify the contrast between the original actions required, and the default behavior today.

2021-03-21 14:11 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/responsive_design/index.html
> +<p>It is important to understand that <strong>responsive web design isn't a separate technology</strong> — it is a term used to describe an approach to web design or a set of best practices, used to
```suggestion
<p>It is important to understand that <strong>responsive web design isn't a separate technology</strong> — it is a term used to describe an approach to web design or a set of best practices, used to create a layout that can <em>respond</em> to the device being used to view the content. In Marcotte's original exploration this meant flexible grids (using floats) and media queries, however since that article was written, working responsively has become the default. Modern CSS layout methods are inherently responsive, and we have new things built into the web platform to make designing responsive sites easier.</p>
```

It wasn't "making an extra effort" the technique was defined as flexible grids and media queries.

2021-03-21 14:12 UTC, rachelandrew requested changes
Happy to remove the time ref, the other addition made the statement less accurate (see inline comment)

2021-03-21 15:06 UTC, ckartchner commented on files/en-us/learn/css/css_layout/responsive_design/index.html
> +<p>It is important to understand that <strong>responsive web design isn't a separate technology</strong> — it is a term used to describe an approach to web design or a set of best practices, used to
For me, after I removed the time span, the sentence felt more ambiguous, although the lack of clarity was already there.

My reading of the original sentence is that it seems to be contrasting "flexible grids and media queries" with "working responsively" or "the default". My addition was an attempt to clarify that it's the approach to producing responsive designs that has changed, with float based grids falling out of fashion to be replaced with what CSS now provides through flexbox and grid. 

I can mull this over this a little more, but it feels like this sentence still needs clarifying.

2021-05-26 07:00 UTC, sideshowbarker commented
@ckartchner This PR seems to be waiting on responses from you to review comments

2021-06-12 22:59 UTC, sideshowbarker commented
Closing for lack of response

2021-06-12 22:59 UTC, closed without merging