Fix globals, part 6: performance
mdn/content pull request #33339
Opened 2024-04-30 18:51 UTC by skyclouds2001

part of the #33019

2024-04-30 18:54 UTC, skyclouds2001 commented on package.json
> +  "packageManager": "yarn@1.22.19+sha1.4ba7fc5c6e704fce2066ecbfb0b0d8976fe62447"
```suggestion
  }
```

2024-05-04 23:32 UTC, wbamberg requested changes

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/performance_api/performance_data/index.md
> +The Performance API collects performance data for each global object (`window.performance` or `self.performance` in workers). See {{domxref("window.performance")}} for which APIs are available in win
```suggestion
With the Performance API you can collect performance data in both {{domxref("Window.performance", "Window")}} and {{domxref("WorkerGlobalScope.performance", "Worker")}} global contexts. If you are collecting performance metrics for multiple contexts, take a look at {{domxref("performance.timeOrigin")}} to synchronize time origins between contexts.
```

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/window/performance/index.md
> +The **`performance`** property of the {{domxref("Window")}} interface returns a {{domxref("Performance")}} object, which can be used to gather performance information about the context it is called i
```suggestion
The **`performance`** property of the {{domxref("Window")}} interface returns a {{domxref("Performance")}} object, which can be used to gather performance information about code running in the window's scope.
```

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/window/performance/index.md
> +A {{domxref("Performance")}} object offering access to performance and timing-related information for the context it is called on window.
```suggestion
A {{domxref("Performance")}} object offering access to performance and timing-related information about code running in the window's scope.
```

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/performance/index.md
> +The **`performance`** property of the {{domxref("WorkerGlobalScope")}} interface returns a {{domxref("Performance")}} object, which can be used to gather performance information about the context it
```suggestion
The **`performance`** property of the {{domxref("WorkerGlobalScope")}} interface returns a {{domxref("Performance")}} object, which can be used to gather performance information about code running in the worker's scope.
```

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/performance/index.md
> +Performance entries are per context. If you create a mark on the main thread (or other worker), you cannot see it in a worker thread, and vice versa.
```suggestion
Performance entries are per context. If you create a mark on a worker thread, you will not see it in the main thread or any other workers.
```

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/performance/index.md
> +See the table which provides an overview about the availability of the performance APIs in window and worker contexts at {{domxref("Window.performance")}}.
We should not do this. I think we should scrap that table in the Window page, and instead list in this page the APIs that are available to workers, something like:

```
Note that only the following performance API are available in worker contexts:
...list available APIs
```

....and we should put it in the preamble, just before the "Value" H2.

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/window/performance/index.md
>  ## Performance API availability
We shouldn't this section here - it's useless for people reading about `Window.performance`. Instead, in `Worker.performance`, we should list the APIs that _are_ supported in workers.

2024-05-04 23:32 UTC, wbamberg commented on files/en-us/web/api/performance/index.md
> +An object of this type can be obtained by calling `window.performance` or `self.performance` in workers. Note that Performance entries are per context. If you create a mark on the main thread (or oth
```suggestion
Performance entries are specific to each execution context. You can access performance information for code running in a window via {{domxref("Window.performance")}}, and for code running in a worker via {{domxref("WorkerGlobalScope.performance")}}.
```

2024-05-06 17:03 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/index.md
>    - : Returns the {{domxref("Performance")}} associated with the worker. It is a regular performance object, except that only a subset of its property and methods are available to workers.
```suggestion
  - : Returns the {{domxref("Performance")}} associated with the worker. Only a subset of the  properties and methods of the `Performance` interface are available to workers.
```

2024-05-06 17:04 UTC, wbamberg commented on files/en-us/web/api/workerglobalscope/performance/index.md
> +A {{domxref("Performance")}} object offering access to performance and timing-related information for the context it is called on worker.
```suggestion
A {{domxref("Performance")}} object offering access to performance and timing-related information for the context it is called on.
```

2024-05-06 17:05 UTC, wbamberg approved these changes
👍 Looks great, thank you @skyclouds2001 !

2024-05-06 17:08 UTC, merged