feat: styling and self-ref links removal
mdn/content pull request #33408
Opened 2024-05-04 08:48 UTC by PassionPenguin

### Description

1. better styles for callstack lists
2. self-ref link removal

### Motivation

1. the originally one display in one line, not like a `list`

2024-05-06 08:42 UTC, bsmth commented on files/en-us/glossary/call_stack/index.md
> +   > - greeting
General comment; we could use code blocks instead of "note"s, what do you think?

2024-05-06 08:43 UTC, bsmth approved these changes
Nice improvement, thank you! One comment open for you to consider, but already leaving a +1 on this 👍🏻

2024-05-06 08:58 UTC, PassionPenguin commented on files/en-us/glossary/call_stack/index.md
> +   > - greeting
hummm..it could be nice, as the code blocks are:

1. distinguishable, as they have a gray-shaded background, which, can separate between different section of call-stack operation
2. better styling, as they’re not either rendered as a list, nor will they be collapsed to show just in one line.

e.g. 

1. Ignore all functions, until it reaches the greeting() function invocation.
3. Add the greeting() function to the call stack list. Now we have call stack:

```   
- greeting
```

4. Execute all lines of code inside the greeting() function.
5. Get to the sayHi() function invocation.
6. Add the sayHi() function to the call stack list, and we have:

```
- sayHi
- greeting
```

7. Execute all lines of code inside the sayHi() function, until reaches its end.
8. Return execution to the line that invoked sayHi() and continue executing the rest of the greeting() function.
9. Delete the sayHi() function from our call stack list. Now the call stack looks like:

```
- greeting
```

10. When everything inside the greeting() function has been executed, return to its invoking line to continue executing the rest of the JS code.
11. Delete the greeting() function from the call stack list. And once again, the call stack become empty.
12. In summary, then, we start with an empty Call Stack. Whenever we invoke a function, it is automatically added to the Call Stack. Once the function has executed all of its code, it is automatically removed from the Call Stack. Ultimately, the Stack is empty again.

2024-05-06 09:30 UTC, bsmth commented on files/en-us/glossary/call_stack/index.md
> +   > - greeting
Looks better! I think we need this to make the linter happy:

````md
1. Ignore all functions, until it reaches the `greeting()` function invocation.
2. Add the `greeting()` function to the call stack list, and we have:

   ```plain
   - greeting
   ```

3. Execute all lines of code inside the `greeting()` function.
4. Get to the `sayHi()` function invocation
5. Add `sayHi()` to the call stack list, like:

   ```plain
   - sayHi
   - greeting
   ```

6. Execute all lines of code inside the `sayHi()` function, until reaches its end.
7. Return execution to the line that invoked `sayHi()` and continue executing the rest of the `greeting()` function.
8. Delete the `sayHi()` function from our call stack list. Now the call stack looks like:

   ```plain
   - greeting
   ```

9. When everything inside the `greeting()` function has been executed, return to its invoking line to continue executing the rest of the JS code.
10. Delete the `greeting()` function from the call stack list. Once again, the call stack become empty.
````

2024-05-07 08:34 UTC, bsmth commented on files/en-us/glossary/call_stack/index.md
> +```
````suggestion
   ```plain
   - greeting
   ```
````

2024-05-07 08:35 UTC, bsmth commented on files/en-us/glossary/call_stack/index.md
> +```
````suggestion
   ```plain
   - sayHi
   - greeting
   ```
````

2024-05-07 08:35 UTC, bsmth commented on files/en-us/glossary/call_stack/index.md
> +```
````suggestion
   ```plain
   - greeting
   ```
````

2024-05-07 08:36 UTC, bsmth requested changes
I believe the suggestions should fix the formatter complaints :)

2024-05-07 08:46 UTC, PassionPenguin commented
> I believe the suggestions should fix the formatter complaints :)
>
> - https://github.com/mdn/content/pull/33408#discussion_r1590760111

sorry for that! I must have forgotten patching it!

2024-05-07 08:53 UTC, bsmth approved these changes
Looks great, thank you! Let's merge 🚢

2024-05-07 08:53 UTC, merged