feat: improvements on glossary compile
mdn/content pull request #33411
Opened 2024-05-04 10:43 UTC by PassionPenguin

### Description

feat: some improvements

1. not all browsers support all functions in aspect of wasm, even in some latest versions of major browsers
2. link improvements

2024-05-04 10:49 UTC, PassionPenguin commented on files/en-us/glossary/compile/index.md
> -- [Compiling from Rust to WebAssembly](/en-US/docs/WebAssembly/Rust_to_Wasm)
replacing with a higher level doc should be better?

2024-05-07 06:27 UTC, chrisdavidmills requested changes
@PassionPenguin this is looking pretty good, nice work! I just had a couple of small suggestions for you to look at.

2024-05-07 06:27 UTC, chrisdavidmills commented on files/en-us/glossary/compile/index.md
> +Typically, a compiler transforms code written in a higher-level language such as [C++](https://en.wikipedia.org/wiki/C++) or [Rust](<https://en.wikipedia.org/wiki/Rust_(programming_language)>) or [Ja
```suggestion
Typically, a compiler transforms code written in a higher-level language such as [C++](https://en.wikipedia.org/wiki/C++), [Rust](<https://en.wikipedia.org/wiki/Rust_(programming_language)>), or [Java](<https://en.wikipedia.org/wiki/Java_(programming_language)>) into executable (runnable) code — so-called **binary code** or **machine code**. [WebAssembly](/en-US/docs/WebAssembly), for example, is a form of executable binary code that [can be compiled from code written in C++, Rust, C#, Go, Swift, and several other languages](https://webassembly.org/getting-started/developers-guide/) and run on any web page, with most features supported in modern browsers (see [browser compatibility table](/en-US/docs/WebAssembly#browser_compatibility)).
```

2024-05-07 06:27 UTC, chrisdavidmills commented on files/en-us/glossary/compile/index.md
> -- [Compiling from Rust to WebAssembly](/en-US/docs/WebAssembly/Rust_to_Wasm)
Yup, agreed!

2024-05-07 06:27 UTC, chrisdavidmills commented on files/en-us/glossary/compile/index.md
> +- [Compiler](https://en.wikipedia.org/wiki/Compiler) on Wikipedia
nit: maybe swap the order of the two links, as the "Compiler" link is more directly relevant to the subject matter?

2024-05-07 06:39 UTC, PassionPenguin commented on files/en-us/glossary/compile/index.md
> +- [Compiler](https://en.wikipedia.org/wiki/Compiler) on Wikipedia
absolutely yes! Will have a patch right away!

2024-05-07 07:22 UTC, chrisdavidmills approved these changes
@PassionPenguin perfecto! Let's get this one merged.

Thanks again.

2024-05-07 07:22 UTC, merged