feat: some improvements on glossary BiDi
mdn/content pull request #33421
Opened 2024-05-05 13:09 UTC by PassionPenguin

### Description

#### Modification

- the definition of the term. according to what the word bidirectional means, and the only macro referring to this glossary (i.e. bidi-ordering), this should be the property (characteristic) of a text, not the text itself.

#### Addition

- example of a BiDi text
- unicode's support of BiDi text

2024-05-09 07:38 UTC, chrisdavidmills requested changes
@PassionPenguin lovely, this is much better, and I thought the example really helped.

I just had a few language suggestions for you.

2024-05-09 07:38 UTC, chrisdavidmills commented on files/en-us/glossary/bidi/index.md
> +**BiDi** (BiDirectional) denotes the characteristic a document has, signifying that both right-to-left (RTL) and left-to-right (LTR) text orientations occurred in one document.
```suggestion
**BiDi** (BiDirectional) describes a document that contains both right-to-left (RTL) and left-to-right (LTR) text.
```

2024-05-09 07:38 UTC, chrisdavidmills commented on files/en-us/glossary/bidi/index.md
> +User Interfaces should design to display BiDi content correctly, but many failed in this. An example is the RTL Hebrew name Sarah: שרה, spelled sin (ש) on the right, resh (ר) in the middle, and heh (
```suggestion
User Interfaces should display BiDi content correctly, but many fail. An example is the Hebrew translation of the name Sarah: שרה, spelled (from right-to-left) sin (ש), resh (ר), heh (ה). Many programs would display the letters in the opposite order.
```

2024-05-09 07:38 UTC, chrisdavidmills commented on files/en-us/glossary/bidi/index.md
> +It is possible to simply flip the left-to-right display order to a right-to-left display order, but doing this sacrifices the ability to correctly display left-to-right scripts. With bidirectional sc
```suggestion
It is possible to flip the left-to-right display order to a right-to-left display order, but doing this sacrifices the ability to display BiDi scripts correctly — at least one is always incorrectly displayed. With bidirectional script support, it is possible to mix characters from different scripts on the same page, regardless of writing direction.
```

2024-05-09 07:41 UTC, chrisdavidmills requested changes
@PassionPenguin oop, one more thing I noticed.

2024-05-09 07:41 UTC, chrisdavidmills commented on files/en-us/glossary/bidi/index.md
> +- [UAX#9: Unicode Bi-directional Algorithm](https://www.unicode.org/reports/tr9/#Resolving_Weak_Types)
Shouldn't this link just point to https://www.unicode.org/reports/tr9/?

2024-05-09 07:58 UTC, PassionPenguin commented on files/en-us/glossary/bidi/index.md
> +- [UAX#9: Unicode Bi-directional Algorithm](https://www.unicode.org/reports/tr9/#Resolving_Weak_Types)
yeap, possibly just copied the wrong link

2024-05-21 11:08 UTC, chrisdavidmills approved these changes
This looks great! Thanks for your hard work on this @PassionPenguin, and apologies for the delay in merging it.

2024-05-21 11:08 UTC, merged