Adjust text formatting per Chinese copywriting guidelines
mdn/content pull request #33444
Opened 2024-05-06 15:47 UTC by ihavecoke

### Description

Refined text formatting to follow the recommendations from: https://sparanoid.com/note/chinese-copywriting-guidelines/

### Motivation

This change aims to improve the readability and professionalism of the copy by following the best practices outlined in the CJK Copywriting Guidelines. Specifically, it addresses:

- Adding spaces between English and Chinese words
- Adding spaces between numbers and units
- Using fullwidth punctuation for Chinese text
- Using halfwidth Arabic numerals
- Using halfwidth punctuation for English sentences
- Using correct casing for proper nouns
- Avoiding jargons and abbreviations

These adjustments will enhance the overall reading experience for both Chinese and English audiences.

### Additional details

The changes are based on the guidelines provided at https://sparanoid.com/note/chinese-copywriting-guidelines/, which is a widely recognized resource for Chinese copywriting best practices.

2024-05-06 16:46 UTC, Josh-Cena requested changes
cc @mdn/yari-content-zh @mdn/yari-content-ja @mdn/yari-content-ko 

At the very least, @ihavecoke please revert any changes to example code output, unless the browsers actually output the current text.

2024-05-06 17:09 UTC, Josh-Cena requested changes

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/guide/text_formatting/index.md
> +console.log(hanDecimalRMBInChina.format(1314.25)); // ￥ 一，三一四。二五
The original comment is correct:

![image](https://github.com/mdn/content/assets/15844309/808687d3-e32e-4bfd-9768-e0974f59b4f1)

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/reference/global_objects/bigint/tolocalestring/index.md
> +// 一二三，四五六，七八九，一二三，四五六，七八九
The same as the above comment, you can try this case.

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/formattoparts/index.md
> +df.format(Date.UTC(2012, 11, 17, 3, 0, 42)); // 2012 壬辰年
The same as the above comment, you can try this.

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md
> +// 一二三，四五六。七八九
same

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
> +// 9.9 亿
same

2024-05-07 01:28 UTC, yin1999 commented on files/en-us/web/javascript/reference/global_objects/number/tolocalestring/index.md
> +// 一二三，四五六。七八九
same

2024-05-07 14:19 UTC, ihavecoke commented
Thank you @yin1999 @Josh-Cena , for taking the time to review my pull request. 
Your suggestions were valuable and made a lot of sense. 
I have now made the necessary adjustments to the code based on your recommendations. 
I kindly request you to review it once again. Thank you.

2024-05-14 19:59 UTC, dipikabh commented
cc @hochan222, @mfuji09 - Could you or someone from your teams please review the changes in this PR? Thank you!

2024-05-15 08:28 UTC, hochan222 requested changes
Hello. In Korean, the content before the change is common and there are no grammatical problems.

> 2 개에서 4 개의
> 그리고 0 개 또는 1 개의

When expressing quantity and order in the combination of "number + unit noun", spacing is the rule, but if the number comes(not word), pasting is also allowed. In Korea, spaces are usually not used when numbers appear. It is a common.

- (bad) `한개`
- (good) `한 개`
- (good, more common) `1개`
- (good) `1 개`

> "DB 에 값이 없습니다!"

There should be no spaces.

- (bad) `DB 에`
- (good) `DB에`

2024-05-15 08:28 UTC, hochan222 commented on files/jsondata/L10n-SVG.json
> +    "ko": "임의의 개수의 설명 요소, {{SVGElement(\"script\")}}, 그리고 2 개에서 4 개의 {{SVGElement(\"stop\")}} 요소.",
```suggestion
    "ko": "임의의 개수의 설명 요소, {{SVGElement(\"script\")}}, 그리고 2개에서 4개의 {{SVGElement(\"stop\")}} 요소.",
```

2024-05-15 08:28 UTC, hochan222 commented on files/jsondata/L10n-SVG.json
> +    "ko": "임의의 개수의 애니메이션 요소, 설명 요소, {{SVGElement(\"mask\")}}, {{SVGElement(\"clipPath\")}}, {{SVGElement(\"marker\")}}, {{SVGElement(\"script\")}}, 그리고 {{SVGElement(\"style\")}} 요소, 그리고 0 개 또는 1 개의 {
```suggestion
    "ko": "임의의 개수의 애니메이션 요소, 설명 요소, {{SVGElement(\"mask\")}}, {{SVGElement(\"clipPath\")}}, {{SVGElement(\"marker\")}}, {{SVGElement(\"script\")}}, 그리고 {{SVGElement(\"style\")}} 요소, 그리고 0개 또는 1개의 {{SVGElement(\"meshgradient\")}} 요소.",
```

2024-05-15 08:28 UTC, hochan222 commented on files/jsondata/L10n-CSS.json
> +    "ko": "DB 에 값이 없습니다!",
```suggestion
    "ko": "DB에 값이 없습니다!",
```

2024-05-15 15:19 UTC, mfuji09 requested changes
This copywriting guidelines isn't for Japanese, and it isn't accepted from Japanese writers.
There are a lot of differences in writing behavior between Chinese and Japanese (or, there is few common things.)
We (Japanese community) already have an own writing guideline, so please let us (native Japanese writers) to decide how to write.

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/writing-mode/index.md
> +    <td>1994 年に至っては</td>
These examples are for mixed writing-mode. In Japanese, half-width spaces isn't used between Japanese characters and Latin letters in vertical / mixed-writing mode. So these examples intentionally omit spaces around numbers.

```suggestion
    <td>1994年に至っては</td>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/writing-mode/index.md
> +    <td>1994 年に至っては</td>
```suggestion
    <td>1994年に至っては</td>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/writing-mode/index.md
> +    <td>1994 年に至っては</td>
```suggestion
    <td>1994年に至っては</td>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/writing-mode/index.md
> +    <td>1994 年に至っては</td>
```suggestion
    <td>1994年に至っては</td>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/writing-mode/index.md
> +    <td>1994 年に至っては</td>
```suggestion
    <td>1994年に至っては</td>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/jsondata/L10n-Common.json
> +    "ja": "まだボランティアによって日本語に翻訳されていない記事です。MDN に参加して、翻訳してみませんか？",
```suggestion
    "ja": "まだボランティアによって日本語に翻訳されていない記事です。 MDN に参加して、翻訳してみませんか？",
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/text-decoration-skip-ink/index.md
> +<p>この文は、text-decoration-skip-ink: auto の使用例を示しています。</p>
```suggestion
<p>この文は、 text-decoration-skip-ink: auto の使用例を示しています。</p>
```

2024-05-15 15:19 UTC, mfuji09 commented on files/en-us/web/css/text-decoration-skip-ink/index.md
> +  この文は、text-decoration-skip-ink: all の使用例を示しています。
```suggestion
  この文は、 text-decoration-skip-ink: all の使用例を示しています。
```

2024-05-15 16:00 UTC, Josh-Cena reviewed
After applying the reviews for both JA and KO, there will be no changes left. Therefore I'll just go ahead and close it.

2024-05-15 16:00 UTC, closed without merging

2024-05-15 16:15 UTC, dipikabh commented
Thank you, @hochan222 and @mfuji09, for your prompt reviews and feedback!