New CSS guide: Understanding aspect ratio
mdn/content pull request #33461
Opened 2024-05-07 07:18 UTC by estelle

links to this new guide will be created in a separate PR.

2024-05-07 20:06 UTC, dipikabh requested changes
Thanks for creating the guide, @estelle 🙌 

I'm submitting a partial review. I should be able to come back to the remaining part tomorrow.

2024-05-07 22:29 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +When developing responsive sites, you often want to be able to set the inline-direction size to a percentage and have the block-direction change size proportionally, maintaining a specific aspect rat
>     * We have a glossary page on "aspect ratio": https://developer.mozilla.org/en-US/docs/Glossary/Aspect_ratio!!
Yeah, i created that page half way through writing this tutorial.

2024-05-08 05:00 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +title: Understanding aspect-ratio
I went with "Understanding aspect ratios and the aspect-ratio property"

An alternative could be "Understanding and setting aspect ratios".

2024-05-08 05:01 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +When developing responsive sites, you often want to be able to set the inline-direction size to a percentage and have the block-direction change size proportionally, maintaining a specific aspect rat
went with:

When developing responsive sites, you often want to be able to set the width of an element to a percentage and have the height change size proportionally, maintaining a specific aspect ratio. When it comes to replaced elements, like images and video, maintaining a specific aspect ratio is not only necessary for {{glossary("responsive web design")}}, but it's a vital component of good user experience by preventing [cumulative layout shift](/en-US/docs/Learn/Performance/Multimedia#rendering_strategy_preventing_jank_when_loading_images).

2024-05-08 05:02 UTC, MercyGraceFavorBlessing3579 commented
thank you so much for all your help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Estelle Weyl ***@***.***>
Sent: Wednesday, May 8, 2024 1:01:25 AM
To: mdn/content ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [mdn/content] New CSS guide: Understanding aspect ratio (PR #33461)


@estelle commented on this pull request.

________________________________

In files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md<https://github.com/mdn/content/pull/33461#discussion_r1593386492>:

> @@ -0,0 +1,543 @@
+---
+title: Understanding aspect-ratio


I went with "Understanding aspect ratios and the aspect-ratio property"

An alternative could be "Understanding and setting aspect ratios".

—
Reply to this email directly, view it on GitHub<https://github.com/mdn/content/pull/33461#discussion_r1593386492>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BGAIMKYH77POH3NMEXJGVITZBGWSLAVCNFSM6AAAAABHKMSACOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANBUGYZTAMZYHA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-05-08 05:04 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this guide, we learn about the `aspect-ratio` property, discuss aspect ratios for replaced and non-replaced elements, and then examine some common aspect ratio use cases.
Good catch. I dropped the first "in this guide"... that was the original outline, but the guide took a turn to the 2nd "in this guide"

> Using CSS, you can adjust the size of replaced and non-replaced elements based on their aspect ratio. In this guide, we will learn about the `aspect-ratio` property, discuss aspect ratios for replaced and non-replaced elements, and then examine some common aspect ratio use cases.

2024-05-08 05:07 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +## CSS `aspect-ratio` property
I partially updated the property page in a separate PR. The property page didn't even address the 2 values syntax. 

I think we need a guide on min-height v. height v. min-block-size v. block-size v. aspect-ratio. If all are declared, how is anything determined? This guides is already enough in the weeds. That will have to be a different guide.

2024-05-08 05:10 UTC, MercyGraceFavorBlessing3579 commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this guide, we learn about the `aspect-ratio` property, discuss aspect ratios for replaced and non-replaced elements, and then examine some common aspect ratio use cases.
thank you so much.

2024-05-08 05:12 UTC, MercyGraceFavorBlessing3579 commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +Every element rendered to the page has a height and a width, and, therefore, an {{glossary("aspect ratio")}}, which is the ratio between the width and height. These natural dimensions, the size of th
thanks for your input

2024-05-08 08:12 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this guide, we learn about the `aspect-ratio` property, discuss aspect ratios for replaced and non-replaced elements, and then examine some common aspect ratio use cases.
@MercyGraceFavorBlessing3579 Your comments are spam. Please stop.

2024-05-08 08:29 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +Every element rendered to the page has a height and a width, and, therefore, an {{glossary("aspect ratio")}}, which is the ratio between the width and height. These natural dimensions, the size of th
The inclusion of AR property details within this AR guide is intentional

2024-05-08 08:30 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this example, we used `height` and `width` to distort the image. We squashed the first one and stretched the third.
went with:

> We distorted the image by setting both a `height` and `width`. We squashed the first one and stretched the third.

2024-05-08 08:31 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +Here we declared a single dimension (in this case, `100vh` is the full height of the example {{htmlelement("iframe")}} viewport). For `aspect-ratio` to apply to replaced elements, one dimension must
went with:

> We declared a single dimension; `100vh` is the full height of the example {{htmlelement("iframe")}} viewport. For the `aspect-ratio` property value to apply to replaced elements, one dimension must be set. Setting both or neither doesn't work.

2024-05-08 09:33 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +<img src="flag.jpg" alt="Pride flag" />
```suggestion
<img src="flag.jpg?image=good" alt="Pride flag" />
```
just testing images

2024-05-08 09:36 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +<img src="flag.jpg?image=good" alt="Pride flag" />
```suggestion
<img src="flag.jpg?image=good" alt="Test image" />
<img src="/en-US/docs/Web/CSS/CSS_box_sizing/understanding_aspect-ratio/flag.jpg" alt="Pride flag" />
```

2024-05-08 09:38 UTC, estelle commented
please temporarily ignore the images on line 84/85. I am testing to see how to get images to show in preview.

2024-05-08 10:09 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +When developing responsive sites, you often want to be able to set the width of an element to a percentage and have the height change size proportionally, maintaining a specific aspect ratio. When it
note i did a pr to add CLS to the linked page: https://github.com/mdn/content/pull/33488

2024-05-08 16:59 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +title: Understanding aspect-ratio
By including the term "responsive design" in the title, I wanted to convey the importance of aspect ratios and why anyone should care about them. If we don't use it, we can omit the property name because it is a repetition of the words aspect ratio

2024-05-08 23:03 UTC, dipikabh requested changes
part 2 review

2024-05-08 23:03 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +Each box has one dimension defined: the {{cssxref("inline-size")}}, which is the width in horizontal languages, is set to {{cssxref("max-content")}}, which sets the size to be as wide as it needs to
```suggestion
Each box has one dimension defined: the {{cssxref("inline-size")}}, which is the width in horizontal languages, is set to {{cssxref("max-content")}}, which sets the size to be as wide as it needs to be to fit the content without wrapping. The second dimension, in this case, the {{cssxref("block-size")}} or {{cssxref("height")}}, is set to be the same length as the first dimension. This is accomplished with the {{cssxref("aspect-ratio")}} property. We defined the desired width-to-height ratio of the element's box to be `1`, which is the same as `1 / 1`, a square. This sets the the block direction to match the width of the element, without using the {{cssxref("height")}} or {{cssxref("block-size")}} properties.
```

2024-05-08 23:03 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In these examples, a size was explicitly set on the element itself. When working with non-replaced elements, aspect ratio works when there is no size dimension explicitly set.
```suggestion
In these examples, a size was explicitly set on the element itself. When working with non-replaced elements, aspect ratio comes into play when no size dimension is explicitly set.
```

2024-05-09 04:32 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +When developing responsive sites, you often want to be able to set the width of an element to a percentage and have the height change size proportionally, maintaining a specific aspect ratio. When it
updated to 

> but it's a vital component of good user experience by preventing loading [jank]((/en-US/docs/Learn/Performance/Multimedia#rendering_strategy_preventing_jank_when_loading_images)), the layout shift that occurs when media loads after the page has already been painted causing a reflow if space for the asset has not been reserved.

2024-05-09 06:03 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this example, the same quote is displayed in `200px` and `600px` wide containers, and a square set with a height matching its `200px` width:
here it's not setting aspect ratio, so not adding non-replaced, as it's not relevant, but will add it on the next example. Good call.

2024-05-09 06:23 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +    ><input type="checkbox" checked /> toggle <code>overflow: auto;</code> and
that is intentional. The default overflow visible is an issue.

2024-05-09 08:36 UTC, estelle commented
Thanks for the review @dipikabh

2024-05-10 22:09 UTC, dipikabh requested changes
Review of the remaining sections

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +A grid of square cells can be created by defining fixed column track sizes with each row being the same size as the column track. However, when creating responsive grids using `auto-fill` to fit as m
A few cross links can be added to reference pages
```suggestion
A grid of square cells can be created by defining fixed column track sizes, ensuring each row matches the size of the column track. However, when creating responsive grids using `auto-fill` to fit as many column tracks as possible within the container, the width of each item becomes uncertain. This makes it challenging to determine the appropriate height for creating square items.
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +By setting an aspect ratio on the items, we can ensure when the grid items are laid out, each grid item will be as tall as it is wide, creating square grid items no matter the width or height.
```suggestion
By setting an aspect ratio on the items, we can ensure when the grid items are laid out, each grid item will be as tall as it is wide, creating square grid items regardless of the container's dimensions.
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +In this square grid item example, the grid tracks are auto-sized, taking their size from the items. Each item will be at least 95px wide but could be much wider. No matter the width, each item will b
```suggestion
In this example of square grid items, the grid tracks are auto-sized, taking their size from the items. Each item will be at least `95px` wide but could be much wider. No matter the width, each item will be a square, with the height determined by the `aspect-ratio` to match its width.
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +For the content of a grid item to not grow beyond the preferred height set by the `aspect-ratio`, set the {{cssxref("min-height")}} to `0` and the {{cssxref("overflow")}} to a value other than `visib
```suggestion
For the content of a grid item to not grow beyond the preferred height set by the `aspect-ratio`, set the {{cssxref("min-height")}} to `0` and the {{cssxref("overflow")}} to a value other than `visible`. This will work for intrinsically sized content. If you have content that is intrinsically larger than the available space, set that content to not be larger than the grid item by setting the {{cssxref("max-height")}} (or {{cssxref("max-width")}}, depending on the content) to `100%`.
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +.item > * {
```suggestion
}

.item > * {
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +Alternatively, the [`object-fit` property](#fitting_replaced_elements_within_their_containers) can be used.
The placement of this sentence is odd. Also, it can be changed to active voice. It can also be removed if we're not demonstrating it in the current example

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +### Grid of square cells
How about:
```suggestion
### Creating responsive grids of square cells
```

2024-05-10 22:09 UTC, dipikabh commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +{{EmbedLiveSample("grid of square cells", "100", "350")}}
Is the height of this Result iframe intentional?

2024-05-13 05:27 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +## Common use cases
went with

> ## Common `aspect-ratio` use cases

2024-05-13 05:53 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +### Grid of square cells
went with "### Making grid cells square".

2024-05-13 05:56 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +{{EmbedLiveSample("grid of square cells", "100", "350")}}
no. it wasn't. thanks. good catch.

2024-05-13 17:21 UTC, estelle commented
@dipikabh Thanks for the review. Looks like we're close to there.

2024-05-14 19:20 UTC, dipikabh requested changes
Thanks for the updates, @estelle. A few last things..

2024-05-14 20:54 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +The inline-size of non-replaced block-level elements is the size of their container's [content box](/en-US/docs/Web/CSS/box-edge#content-box). Because they have an size by default, they don't need to
```suggestion
The inline-size of non-replaced block-level elements is the size of their container's [content box](/en-US/docs/Web/CSS/box-edge#content-box). Because they have a size by default, they don't need to have an explicit size set for the `aspect-ratio` property to work.
```

2024-05-14 20:56 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +- [CSS box sizing](/en-US/docs/Web/CSS/CSS_box_sizing) module
It's only tangential, so i think that reference is enough. I'll be adding CLS content in a few weeks, so will link that instead when it's published.

2024-05-14 20:57 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +    ><input type="checkbox" checked /> toggle <code>overflow: auto;</code> and
```suggestion
    ><input type="checkbox" checked /> Toggle between <code>overflow</code> values <code>auto</code> and
```

2024-05-14 20:57 UTC, estelle commented on files/en-us/web/css/css_box_sizing/understanding_aspect-ratio/index.md
> +    <code>overflow: visible;</code></label
```suggestion
    <code>visible</code></label
```

2024-05-15 13:57 UTC, dipikabh approved these changes
Thanks for addressing the feedback, @estelle. Approving!
There's a lint error, feel free to merge after resolving it.

2024-05-15 22:29 UTC, merged