Express: GoogleCloud hosting option
mdn/content pull request #3348
Opened 2021-03-22 03:25 UTC by hamishwillee

Fixes #3298

Google Cloud is another option/peer or azure, Amazon etc, so added that. 
Also fixed up note boxes to use standard notecard classes.

2021-03-22 06:48 UTC, CreaTorAlexander commented
```
<div class="notecard note">
  <h4>Note</h4>

```
Just a question becuase I also saw it in another PR of you and I don't understand it. For what is this *div classname and heading update* above?

2021-03-22 07:00 UTC, hamishwillee commented
@CreaTorAlexander This is the "proper" syntax for a note `div`- as documented [here](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#.note.notecard). There is no requirement to change these (or there would be a flaw), and arguably it isn't worth bothering because when we eventually move to markdown all of these will be fixed up in one go. 

I do it because I'm a little OCD :-) But only when I'm fixing up other things anyway.

2021-04-27 01:23 UTC, hamishwillee commented
@Ryuno-Ki Could you please review this?

2021-04-27 20:08 UTC, Ryuno-Ki requested changes
So far, looks good to me.
Please, address the Amazon and the broken link and this can be merged.

Bonus points, if you would update the product names I called out :-)

2021-04-27 20:08 UTC, Ryuno-Ki commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +<p>The good news when you're starting out is that there are quite a few sites that provide computing environments for "free", albeit with some conditions. For example, <a href="https://www.heroku.com
Does Amazon not offer https?

2021-04-27 20:08 UTC, Ryuno-Ki commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +  <p>Calls to <code>debug</code> can replace logging you might previously have done using <code>console.log()</code> or <code>console.error()</code>. Replace any <code>console.log()</code> calls in y
```suggestion
  <p>Calls to <code>debug</code> can replace logging you might previously have done using <code>console.log()</code> or <code>console.error()</code>. Replace any <code>console.log()</code> calls in your code with logging via the <a href="https://www.npmjs.com/package/debug">debug</a> module. Turn the logging on and off in your development environment by setting the DEBUG variable and observe the impact this has on logging.</p>
```
Sorry, my OCD over here :sweat_smile:

2021-04-27 20:08 UTC, Ryuno-Ki commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +  <p>For a high-traffic website in production you wouldn't use this middleware. Instead, you would use a reverse proxy like <em>Nginx</em>.</p>
```suggestion
  <p>For a high-traffic website in production you wouldn't use this middleware. Instead, you would use a reverse proxy like <em>nginx</em>.</p>
```
Looking through https://nginx.org/en/docs/faq.html it appears, that `nginx` is the product and `Nginx` is the company (but the literature is inconsistent here).

2021-04-27 20:08 UTC, Ryuno-Ki commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +  <p>The command above adds a <em>subset</em> of the available headers. They make sense for most sites. You can add/disable specific headers as needed by following the instructions on <a href="https:
The link text is a bit confusing here. Perhaps it should become
```suggestion
  <p>The command above adds a <em>subset</em> of the available headers. They make sense for most sites. You can add/disable specific headers as needed by following the instructions on <a href="https://www.npmjs.com/package/helmet">helmet</a>.</p>
```
?

2021-04-27 20:08 UTC, Ryuno-Ki commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +  <p>In 2020 Github changed the default repo branch name to "main" (from "master"). If using an older/existing repository you might need to call <code>git push origin master</code> instead.</p>
I believe, they stylise their product as
```suggestion
  <p>In 2020 GitHub changed the default repo branch name to "main" (from "master"). If using an older/existing repository you might need to call <code>git push origin master</code> instead.</p>
```

2021-04-30 04:39 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +<p>The good news when you're starting out is that there are quite a few sites that provide computing environments for "free", albeit with some conditions. For example, <a href="https://www.heroku.com
No idea how that crept in.

2021-04-30 04:48 UTC, hamishwillee commented on files/en-us/learn/server-side/express_nodejs/deployment/index.html
> +  <p>The command above adds a <em>subset</em> of the available headers. They make sense for most sites. You can add/disable specific headers as needed by following the instructions on <a href="https:
I modified slightly differently. Thanks.

2021-04-30 04:52 UTC, hamishwillee commented
Thanks @Ryuno-Ki - fixed!

2021-05-01 19:55 UTC, Ryuno-Ki approved these changes
Looks great!

2021-05-01 19:56 UTC, merged

2021-05-03 00:51 UTC, hamishwillee commented
Thanks for reviewing @Ryuno-Ki !