Add warmup function in WebExtensions browser.tabs page
mdn/content pull request #335
Opened 2020-12-17 01:43 UTC by ariasuni

[`tabs.warmup()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/warmup) is not in the page for [`tabs`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) right now, this fixes it.

- Fix links with flaw autofixer
- Also add “Non-standard” tag to `tabs.warmup` page

2020-12-18 17:14 UTC, rpl requested changes

2020-12-18 17:14 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
I'm not sure if this is really necessary (besides being not strictly related to the changes to fix the issue that the pull request title refers to). I'll leave this to someone that knows the new MDN system in more detail (my guess is that it may be good to apply this changes to the url for consistency, but the page seems to be reachable also with the url as is).

2020-12-18 17:14 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Gets information about the tab that this script is running in, as a <a href="/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab" title="This type contains information about a tab."><code>tab
thanks! I think that I would also prefer that part of the url to be in the same case of the namespace it does refer too).

2020-12-18 17:14 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Warm up a tab.</dd>
This entry should be moved in the section related to the Functions, these one looks the section for the events.

From a content perspective, "Warm up a tab" may not say much to a developer that reads about this method for the first time while looking this page, it may be worth to double-check if we can add some more details to make it clear what it does.
e.g. in the actual API doc page it says: `start the process of rendering the resources for an inactive tab... This then makes the actual tab switch faster than it would be otherwise.`

And so maybe something like `Warm up a tab to make sure it is rendered ready.`
@caitmuenster how that sounds/looks to you?

2020-12-18 17:15 UTC, mixedpuppy requested changes

2020-12-18 17:15 UTC, mixedpuppy commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Warm up a tab.</dd>
This needs to go up in the functions section, not in the events section.

2020-12-18 17:28 UTC, rpl requested changes
I missed this one in my previous round of comments.

2020-12-18 17:28 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/warmup/index.html
> +  - Non-standard
Non-standard may not be actually needed, it seems that some other of our Firefox specific methods does not have it neither (I guess that is used mainly for WebAPI available in a regular webpage given that there is no official standard for the WebExtensions APIs yet).

e.g. tab.hide doesn't have it neither:
https://github.com/mdn/content/blob/737b637828c554ce05fdd70737352ccd78b880b3/files/en-us/mozilla/add-ons/webextensions/api/tabs/hide/index.html#L2-L12

2020-12-19 18:05 UTC, ariasuni commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/warmup/index.html
> +  - Non-standard
I removed it for now.

2020-12-19 18:06 UTC, ariasuni commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Warm up a tab.</dd>
I came up with “Prepare the tab to make a potential following switch faster.” for a short yet descriptive explanation of what the function does.

2020-12-19 18:07 UTC, ariasuni commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Gets information about the tab that this script is running in, as a <a href="/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab" title="This type contains information about a tab."><code>tab
What do you mean? Should I change something?

2020-12-19 18:08 UTC, ariasuni commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
I removed this change, the flaw autofixer can still be used on another occasion etc. and I’d prefer this to be merged quickly.

2020-12-21 11:41 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Gets information about the tab that this script is running in, as a <a href="/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab" title="This type contains information about a tab."><code>tab
@ariasuni nothing to do here, my comment was just mean to be a "thank you" for spotting this small inconsistency.

2020-12-21 11:44 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Warm up a tab.</dd>
Sounds good to me, I'll leave to @caitmuenster to comment on it if it would need some tweak from an editorial and English spelling perspectives (I'm not native and I may get that wrong too ;-)).

2020-12-21 11:46 UTC, rpl approved these changes
lgtm, approving on my side (I'll leave to @caitmuenster a final review pass of the `tabs.warmup` description from her perspective).

2021-01-28 23:25 UTC, caitmuenster commented on files/en-us/mozilla/add-ons/webextensions/api/tabs/index.html
> + <dd>Warm up a tab.</dd>
Sorry, I missed this notification! @ariasuni, "Prepare the tab to make a potential following switch faster" sounds good to me. :)

2021-01-28 23:25 UTC, caitmuenster commented
This LGTM! Thank you @ariasuni! 🏅

2021-01-28 23:26 UTC, merged

2021-01-29 01:43 UTC, ariasuni commented
Nice, I’m happy that this improvement is now available to everyone!