feat: improvments on decryption
mdn/content pull request #33513
Opened 2024-05-09 11:26 UTC by PassionPenguin

### Description

#### Deletion

- deleted one unwritten link

#### Modification

- some improvements on the description

2024-05-09 16:36 UTC, wbamberg requested changes

2024-05-09 16:36 UTC, wbamberg commented on files/en-us/glossary/decryption/index.md
> +Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, decryption without knowing the specific secret, decryption is mathematically hard to perform, depending on
```suggestion
Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, is mathematically hard to perform. How hard depends on the security of the cryptographic algorithm chosen and evolves with the progress of {{glossary("cryptanalysis")}}.
```

- there was another error in this sentence, " decryption without knowing the specific secret"
- I think the original 2-sentence form was fine, and the PR introduced a new error ("evolves" no longer made sense).

2024-05-09 16:36 UTC, wbamberg commented on files/en-us/glossary/decryption/index.md
> +Decryption is a cryptographic primitive: it transforms a ciphertext message into plaintext using a cryptographic algorithm called a {{glossary("cipher")}}. Like encryption, decryption in modern ciphe
```suggestion
Decryption is an operation which transforms a ciphertext message into plaintext using a cryptographic algorithm called a {{glossary("cipher")}}. Like encryption, decryption in modern ciphers is performed by using a specific algorithm and a secret, called the {{glossary("key")}}.
```

- I don't think "cryptographic primitive" is helpful jargon here.
- I don't think that "Since the algorithm is often public..." sentence is helpful (and is potentially misleading, wrongly implying that if the algorithm is not public, then the key need not be secret).

2024-05-09 16:36 UTC, wbamberg commented on files/en-us/glossary/decryption/index.md
>  In {{glossary("cryptography")}}, **decryption** is the conversion of {{glossary("ciphertext")}} into {{glossary("Plaintext")}}.
```suggestion
In {{glossary("cryptography")}}, **decryption** is the conversion of {{glossary("ciphertext")}} into {{glossary("plaintext")}}.
```

2024-05-13 13:49 UTC, PassionPenguin commented on files/en-us/glossary/decryption/index.md
> +Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, decryption without knowing the specific secret, decryption is mathematically hard to perform, depending on
in the original context, `evolves` should means as cryptanalysis develops? so can we just say, the progress of that develpment(research)?

```suggestion
Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, is mathematically hard to perform. The difficulty depends on the security of the cryptographic algorithm chosen and the research progress of {{glossary("cryptanalysis")}}.
```

2024-05-13 13:51 UTC, PassionPenguin commented on files/en-us/glossary/decryption/index.md
> +Decryption is a cryptographic primitive: it transforms a ciphertext message into plaintext using a cryptographic algorithm called a {{glossary("cipher")}}. Like encryption, decryption in modern ciphe
- u're right. it's not helpful (not straight-forward).
- yeap, having the same idea here why the editor has this line added.

2024-05-13 17:49 UTC, wbamberg commented on files/en-us/glossary/decryption/index.md
> +Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, is mathematically hard to perform. The difficulty depends on the security of the cryptographic algorithm c
> in the original context, evolves should means as cryptanalysis develops?

Yes, I think so.

> so can we just say, the progress of that development(research)?

```suggestion
Decryption is the reverse process of {{glossary("encryption")}} and if the key stays secret, is mathematically hard to perform. How hard it is depends on how secure the cryptographic algorithm is, and that in itself is subject to change as the study of {{glossary("cryptanalysis")}} advances.
```

2024-05-14 02:16 UTC, wbamberg approved these changes
👍 thank you for the fixes, @PassionPenguin !

2024-05-14 02:16 UTC, merged