Convert noteblock in `/games` to GFM syntax
mdn/content pull request #33575
Opened 2024-05-13 03:24 UTC by queengooborg

This PR replaces all of the old noteblock syntax with GFM syntax, using a [script I wrote](https://github.com/queengooborg/mdn-toolkit/blob/main/upgrade-noteblock.js).  This performs the migration for the `/games` folder.

2024-06-13 20:15 UTC, dipikabh commented
Hi @queengooborg, sorry the delay, I'm getting to this only now. I've just gone through the related PRs and threads, and it seems we're waiting for some decision in the other yari PR you've opened: https://github.com/mdn/yari/pull/11108.
 
As an aside, I noticed this PR uses `![NOTE]`. Shouldn't these be `[!NOTE]`?

2024-06-13 20:27 UTC, queengooborg commented
> As an aside, I noticed this PR uses `![NOTE]`. Shouldn't these be `[!NOTE]`?

Good catch, thanks -- I had a typo in my converter script!

---

This is really waiting for a bugfix, not a decision, but the bugfix is now blocked by a decision apparently...

2024-07-19 14:41 UTC, Josh-Cena commented
This is now unblocked :)

2024-07-20 20:10 UTC, dipikabh approved these changes
Thanks, @queengooborg 👍, approving.
I can merge after the conflicts are resolved

2024-07-20 22:11 UTC, Josh-Cena commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +> [!NOTE] > [Another example without Canvas or external libraries](https://jsfiddle.net/jlr7245/217jrozd/3/).
```suggestion
> [!NOTE]
> [Another example without Canvas or external libraries](https://jsfiddle.net/jlr7245/217jrozd/3/).
```

2024-07-20 22:11 UTC, Josh-Cena commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +> [!NOTE] > [Here is another example without Canvas or external libraries.](https://jsfiddle.net/jlr7245/teb4znk0/20/)
```suggestion
> [!NOTE]
> [Here is another example without Canvas or external libraries.](https://jsfiddle.net/jlr7245/teb4znk0/20/)
```

2024-07-21 00:09 UTC, Josh-Cena commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +> [Another example without Canvas or external libraries](https://jsfiddle.net/jlr7245/217jrozd/3/).
Looks like a Prettier bug?

2024-07-21 00:12 UTC, Josh-Cena commented on files/en-us/games/tutorials/2d_breakout_game_pure_javascript/index.md
> +>
We should review this after new Yari is used in preview, because currently this still appears broken

2024-07-21 00:18 UTC, queengooborg commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +> [Another example without Canvas or external libraries](https://jsfiddle.net/jlr7245/217jrozd/3/).
It is a Prettier bug, but it's one we can easily work around:

```suggestion
> [!NOTE]
>
> [Another example without Canvas or external libraries](https://jsfiddle.net/jlr7245/217jrozd/3/).
```

2024-07-21 00:20 UTC, queengooborg commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +> [Here is another example without Canvas or external libraries.](https://jsfiddle.net/jlr7245/teb4znk0/20/)
```suggestion
> [!NOTE]
>
> [Here is another example without Canvas or external libraries.](https://jsfiddle.net/jlr7245/teb4znk0/20/)
```

2024-07-22 18:22 UTC, dipikabh requested changes, later dismissed

2024-07-22 18:22 UTC, dipikabh commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +>
```suggestion
```
there should be no blank line after `[!NOTE]`, it is rendering double Notes:

![2024-07-22 note rendering](https://github.com/user-attachments/assets/24838890-1817-4079-b26d-dff9d5491ffd)

2024-07-22 18:22 UTC, dipikabh commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +>
```suggestion
```

2024-07-22 20:34 UTC, queengooborg commented on files/en-us/games/techniques/2d_collision_detection/index.md
> +>
This was a bug in Yari that was recently fixed!  The blank line in between is required to mitigate a Prettier bug.

2024-07-23 11:48 UTC, dipikabh approved these changes

2024-07-23 11:48 UTC, merged