Adding "Formal Definition" heading above cssinfo
mdn/content pull request #3363
Opened 2021-03-22 12:04 UTC by butterydev

This PR adds a "Formal Definition" heading above cssinfo in the margin web/css doc.

I noticed this heading on other property docs and it appeared to be missing here.

Let me know if this is buttery or not.

Love MDN!!! Thanks!!!

Checklist — To help your pull request get merged faster, please do the following:

1. - [ ] Provide a summary of your changes — say what problem you are fixing, what files are changed, and what you've done. This doesn't need to be hugely detailed, as we can see exact changes in the "Files changed" tab.
1. - [ ] Provide a link to the issue(s) you are fixing, if appropriate, in the form "Fixes _url-of-issue_". GitHub will render this in the form "Fixes #1234", with the issue number linked to the issue. Doing this allows us to figure out what issues you are fixing, as well as helping to automate things (for example the issue will be closed once the PR that fixed it has been merged).
1. - [ ] Review the results of the automated checking we run on every PR and fix any problems reported (see the list of checks near the bottom of the PR page). If you need help, please ask in a comment!
1. - [ ] Link to any other resources that you think might be useful in reviewing your PR.

2021-03-23 04:12 UTC, wbamberg requested changes, later dismissed
I think ideally CSS properties should have a top-level heading structure like:

```
H2 - Constituent properties (if a shorthand)
H2 - Syntax
H2 - Description (optional)
H2 - Formal definition (contains {{cssinfo}})
H2 - Formal syntax (contains {{csssyntax}})
H2 - Examples
H2 - Specifications
H2 - Browser compatibility
H2 - See also
```

See https://developer.mozilla.org/en-US/docs/Web/CSS/border-color or https://developer.mozilla.org/en-US/docs/Web/CSS/flex#description for an example shorthand property, and https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip for an example not-shorthand property.

So to be really buttery, this should:

* add an H2#Constituent properties, before the H2#Syntax. This should list the properties for which `margin` is a shorthand. This can use the same wording as in, say, https://developer.mozilla.org/en-US/docs/Web/CSS/border-color#constituent_properties, and means we no longer need the second sentence "It is a shorthand for margin-top, margin-right, margin-bottom, and margin-left.".

* rename H2#Notes to Description, and move it to after H2#Syntax

* add H2#Formal definition, after the new H2#Description, and put the {{cssinfo}} call after it.

* move the existing H3#Formal syntax to be an H2 and to follow after the H2#Formal definition. Put the {{csssyntax}} call after it.

Does that make sense?

2021-03-23 15:08 UTC, butterydev commented
@wbamberg totally makes sense!!! thank you so much!!! ill get those updates!!!

thanks again!!!

2021-05-26 07:02 UTC, rachelandrew commented
@butterydev were you going to come back to this?

2021-05-26 07:02 UTC, sideshowbarker commented
@butterydev Per https://github.com/mdn/content/pull/3363#issuecomment-804981865 this PR seems to be waiting on further changes from you.

2021-06-09 04:03 UTC, wbamberg commented
I wanted to close this, so pushed some changes along the lines suggested in https://github.com/mdn/content/pull/3363#pullrequestreview-618190326 .

2021-06-09 04:10 UTC, rachelandrew approved these changes
lgtm :)

2021-06-09 04:11 UTC, merged