fix: Better element ID naming for disambiguation (fixes mdn/web-components-examples#74)
mdn/content pull request #33666
Opened 2024-05-19 08:34 UTC by ngdangtu-vn

### Description

This is the sibling PR with https://github.com/mdn/web-components-examples/pull/77

### Motivation

To match the web-components-examples example.

### Additional details

none

### Related issues and pull requests

- Fixes mdn/web-components-examples#74
- Relates to https://github.com/mdn/web-components-examples/pull/77
- **Depends on:** [#123](https://github.com/mdn/web-components-examples/pull/77)

2024-05-19 08:35 UTC, ngdangtu-vn commented
Hi @bsmth , I've updated the MDN doc example. Please take a look.

2024-06-07 09:15 UTC, bsmth commented
Thanks @ngdangtu-vn - sorry for the delay, I've been away and could not take a look. I've added myself as a reviewer now!

2024-06-12 12:09 UTC, bsmth commented on files/en-us/web/api/web_components/using_templates_and_slots/index.md
There's one more on L65 to get:

```diff
-<template id="my-paragraph">
+<template id="custom-paragraph">
```

2024-06-12 12:10 UTC, bsmth commented
Thanks a lot! There's one leftover line to fix, but then we're ready to merge and the accompanying PR, too.

2024-06-12 12:11 UTC, bsmth requested changes
See comment about L65 in `files/en-us/web/api/web_components/using_templates_and_slots/index.md`

2024-06-17 08:53 UTC, bsmth commented
Hey @ngdangtu-vn - thanks for your suggestions! Quick reminder there's one last thing to get on this branch and we're ready to go!

2024-06-21 08:20 UTC, bsmth commented
@ngdangtu-vn - is it okay with you if I make the changes on your branch and merge?

2024-06-22 08:36 UTC, ngdangtu-vn commented
@bsmth Sorry for later response, I think the the notification got lost somewhere. Hopefull it didn't pulling your task down too much.

2024-06-24 09:41 UTC, bsmth approved these changes
Super, looking good!

2024-06-24 09:41 UTC, bsmth commented
> @bsmth Sorry for later response, I think the the notification got lost somewhere. Hopefull it didn't pulling your task down too much.

Not a problem, well done on your contribution!

2024-06-24 09:41 UTC, merged

2024-06-24 10:15 UTC, ngdangtu-vn commented
> @ngdangtu-vn - is it okay with you if I make the changes on your branch and merge?

I don't at all. If it's convenience for you, please go ahead.