Disable individual static rules in DNR
mdn/content pull request #33733
Opened 2024-05-23 19:17 UTC by rebloor

### Description

Provides documentation for [Bug 1810762](https://bugzilla.mozilla.org/show_bug.cgi?id=1810762) [DNR] Disable individual static rules, including:

- release notes
- - documentation of `getDisabledRuleIds` and `updateStaticRules`

### Related issues and pull requests

BCD changes in (TBC)

2024-05-27 10:40 UTC, rpl requested changes
@rebloor thanks! follows an initial review pass (which include a couple of request for changes, a couple of nits and some thoughts and questions).

2024-05-27 10:40 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +  - : Modifies the enabled state of rules in a static ruleset.
Thought: may be worth including the term "individual" here to make it more immediately clear that in this case (unlike `updateEnabledRulesets`) we are not referring to enabled state of the entire ruleset? e.g. Modifies individual rules enabled state in a given static ruleset.

Same thought for the similarly wording in updatestaticrules/index.md.

2024-05-27 10:40 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Rules belonging to a ruleset can be modified while it is disabled but don't become effective until the ruleset is enabled.
Thought: how about "Rules belonging to a disabled ruleset can be modified and become effective when the ruleset is enabled"?

2024-05-27 10:40 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +  - : An object containing details of the ruleset and which of its rules are to be enabled or disabled.
Thought: I'm not sure the description for `options` is actually needed (and I wonder if the current wording may be a bit misleading), how about omitting it and just include description for its properties? alternatively we may call it "An object to specify which rules to enable/disable in a given static ruleset" or something along those lines.

2024-05-27 10:40 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/getdisabledruleids/index.md
> +{{WebExtExamples}}
Question: do we have an example snippet that is meant to be interpolated here? or should we omit this section in this PR and introduce the section back in a separate PR if we want to followup with a code snippet example?

2024-05-28 04:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +  - : Modifies the enabled state of rules in a static ruleset.
I don't think adding "individual" necessarily adds clarity, it is as likely to create confusion, e.g., suggesting that the API can only change the state of one rule at a time.

2024-05-28 04:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Rules belonging to a ruleset can be modified while it is disabled but don't become effective until the ruleset is enabled.
Or should it be:
```suggestion
Rules in a ruleset can be modified while the ruleset or rules are disabled. Any changes become effective when the ruleset and rules are enabled.
```

2024-05-28 04:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +  - : An object containing details of the ruleset and which of its rules are to be enabled or disabled.
In general, we normally provide a description for an `options` objects. 
```suggestion
  - : An object specifying a static ruleset and the rules to enable or disable in that ruleset.
```

2024-05-28 04:24 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +{{WebExtExamples}}
```suggestion
{{WebExtExamples("h2")}}
```

2024-06-04 11:28 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +  - : Modifies the enabled state of rules in a static ruleset.
@rebloor my thought was mainly due to the fact that for static rules there is another (pre-existing) API method that allows to enable/disable the entire ruleset, while the new one is meant to allow to enable/disable individual rules.

2024-06-04 11:30 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Rules belonging to a ruleset can be modified while it is disabled but don't become effective until the ruleset is enabled.
@rebloor I'd just cut out the "or rules" and the "and rules" parts, this method is one that is menat to enable/disable rules and so I think the note can just focus on the fact that changing rules enabled in a disabled rules become effective when the ruleset may become enabled (on the contrary change to the enable/disable state of rules part of an enabled ruleset are immediately effective.

2024-06-04 11:31 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +  - : An object containing details of the ruleset and which of its rules are to be enabled or disabled.
:+1:  I like the suggested version from your comment https://github.com/mdn/content/pull/33733#discussion_r1616558474

2024-06-04 11:34 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/getdisabledruleids/index.md
> +Returns the IDs of the disabled rules in a static ruleset.
sounds good, let's keep it as is, I'm marking this as resolved.

2024-06-04 11:37 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +{{WebExtExamples("h2")}}
Thought: if the example subsection is empty, wouldn't make sense to omit it for now and eventually add it if we will have an example to include in it?

2024-06-05 10:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +  - : Modifies the enabled state of rules in a static ruleset.
@rpl I don't see the issue:

- there are three parallel named APIs that deal with rules (in rulesets): updateDynamicRules, updateSessionRules, and updateStaticRules
- updateEnabledRulesets clearly indicates it deals with rulesets (not the rules within a ruleset)

2024-06-05 10:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Rules belonging to a ruleset can be modified while it is disabled but don't become effective until the ruleset is enabled.
```suggestion
Rules can be enabled and disabled while the ruleset containing them is disabled. Any changes become effective when the ruleset is enabled.
```

2024-06-05 10:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +{{WebExtExamples("h2")}}
@rpl Nothing is rendered from this macro until the API is present in the [example.json file](https://github.com/mdn/webextensions-examples/blob/main/examples.json). Then, this macro adds the Examples title (as h2) and a list of examples (using the API).

2024-06-11 11:54 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Rules belonging to a ruleset can be modified while it is disabled but don't become effective until the ruleset is enabled.
Thanks Richard, the wording tweaks you mentioned in https://github.com/mdn/content/pull/33733#discussion_r1627480918 looks great to me too.

2024-06-11 11:58 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +{{WebExtExamples("h2")}}
@rebloor ah, I see, then I definitely agree that it would be better to include it as you did and leave the macro logic to eventually show the section and list of examples if we will have added one to the example.json file.

2024-06-11 12:00 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +  - : Modifies the enabled state of rules in a static ruleset.
k, then, it was just a thought and not really a blocking issue or an actual request for change. Let's proceed with the current wording used in this PR.

2024-06-11 12:06 UTC, rpl approved these changes
@rebloor thanks a lot, apologies for not having been able to come back to this PR last week, this PR looks good and there are only two tweaks to the wording we discussed that seems to need to be applied before merging it.

r+wc, where "with comments" part referring to applying the tweaks to the wording from https://github.com/mdn/content/pull/33733/files#r1627480918 and https://github.com/mdn/content/pull/33733/files#r1616558474

2024-06-12 03:03 UTC, merged