Add a guide page on credential types
mdn/content pull request #33745
Opened 2024-05-24 18:42 UTC by wbamberg

This PR adds a new page that's an overview guide to the different credential types supported in the Credential Management API.

@hamishwillee , @chrisdavidmills , perhaps you are interested in looking at it?

2024-05-30 07:48 UTC, chrisdavidmills requested changes
@wbamberg nice work! I've had a look at it, and provided mostly text comments. The explanations of the APIs are nicely written, and mostly make sense.

2024-05-30 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +Support for federated identity in the Credential Management API was originally provided through the {{domxref("FederatedCredential")}} interface. However, this mechanism depends on technologies such
```suggestion
Support for federated identity in the Credential Management API was originally provided through the {{domxref("FederatedCredential")}} interface. However, this mechanism depends on technologies such as [third-party cookies](/en-US/docs/Web/Privacy/Third-party_cookies), which are intrinsically privacy-invasive. These technologies were [deprecated in browsers](/en-US/blog/goodbye-third-party-cookies/), therefore a new approach was needed.
```

2024-05-30 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +The [Federated Credential Management API](/en-US/docs/Web/API/FedCM_API) defines a privacy-preserving mechanism for federated identity on the web. In this mechanism, you call {{domxref("CredentialsCo
```suggestion
The [Federated Credential Management API](/en-US/docs/Web/API/FedCM_API) defines a privacy-preserving mechanism for federated identity on the web. You start by calling {{domxref("CredentialsContainer.get", "navigator.credentials.get()")}} to request a federated identity credential, and this triggers a protocol exchange between the browser and the IdP.
```

2024-05-30 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +A one-time password (OTP) is an authentication technique in which the website has a means to send messages to a user (such as an email address or a phone number) and uses this to send a unique code t
```suggestion
A one-time password (OTP) is an authentication technique in which the website sends a unique code to the user via a messaging system such as email or SMS. The user must then enter the code on the site to prove their control of the communications endpoint. Websites sometimes use this as a second authentication factor in addition to a password.
```

2024-05-30 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
I'm not sure about the third line down on this diagram — the one that says "Send SMS". The website doesn't send an SMS to the server — it sends a request to the server to send an SMS to the client.

So, perhaps the third line down should say something like "Request server to send SMS", and the fourth line down should be "Send SMS"?

2024-05-30 07:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/index.md
> +The central interface is the {{domxref("CredentialsContainer")}}, which is accessed through the {{domxref("navigator.credentials")}} property, and which provides three main functions:
```suggestion
The central interface is the {{domxref("CredentialsContainer")}}, which is accessed through the {{domxref("navigator.credentials")}} property and provides three main functions:
```

2024-05-30 15:59 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
That's fair. I suppose I wanted to avoid having a fifth entity here, so "send SMS" is a kind of shorthand for "ask the server to send an SMS".

2024-05-30 16:02 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +Modern browsers provide users with a password manager, which enables users to store the passwords they enter on websites, and later retrieve them when they need to log in again. Password managers can
I think it's overall better practice to have strong unique passwords and write them down somewhere than to have simple enough passwords that they can be remembered: https://www.schneier.com/blog/archives/2005/06/write_down_your.html.

2024-05-30 17:15 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
I've updated the diagram in https://github.com/mdn/content/pull/33745/commits/1fabf7453f3b4691193f3eaf84dbbd650338ec8c.

2024-05-30 17:30 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +- **Passwords** ({{domxref("PasswordCredential")}})
Hm, because it makes it look like a method call you mean? What I really want to say is "represented by" but thought that might be a bit too repetitive.

Do you like a table for this -> https://github.com/mdn/content/pull/33745/commits/13cde577aa3dd3ca5a151a8f53db236c7e5b2d68 ?

2024-05-31 00:23 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
Recommended things should be first. If possible we should deprecate/hide things that aren't recommended. This is one possible approach:

```suggestion
- **Federated identity credentials**: {{domxref("IdentityCredential")}}

  > **Note:** {{domxref("FederatedCredential")}} is still part of the specification but has been superseded by {{domxref("IdentityCredential")}}
```

Does legacy mean deprecated? If so we should say so, and also update https://developer.mozilla.org/en-US/docs/Web/API/FederatedCredential which notes that there is a better version.

2024-05-31 00:26 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
IdentityCredential Not in list of interfaces

2024-05-31 00:29 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +The Credential Management API enables a website to create, store, and retrieve {{glossary("credential", "credentials")}}, to help a user securely log into websites. It supports four different types o
```suggestion
The Credential Management API enables a website to create, store, and retrieve the {{glossary("credential", "credentials")}} that allow a user to securely log in. It supports four different types of credentials:
```

2024-05-31 00:31 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Class diagram showing the five different credential subclasses.](credential-types.svg)
Ditto for diagram - if it is deprecated have it below identiy cred and perhaps put box in grey?

2024-05-31 00:32 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +> **Note:** Although we're describing all the credential types together here, the different credential types are defined in various different specifications, which extend the main Credential Manageme
```suggestion
> **Note:** Although we're describing all the credential types together here, the different credential types are defined in a number of different specifications, which extend the main Credential Management API specification.
```

2024-05-31 00:43 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +> **Note:** Most browsers do not support this credential type and it is not widely used on the web. Instead, browsers automatically offer to store passwords in a password manager, and can automatical
So just to be clear the browser automatically stores credential types when needed/requested, and autofills forms or whatever, while the credential API just stores and gets credentials, but all the work for doing this and for populating forms has to be done by the developer?

If so, I wonder why any browser/site has implemented this. 

Perhaps make first _automatically_ italic.

2024-05-31 00:47 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +The browser then returns an `OTPCredential` object in the fulfilment of the `Promise` returned from `get()`, and this object contains the code. The website front end can then use the code to autofill
```suggestion
The browser then returns an `OTPCredential` object in the fulfilment of the `Promise` returned from `get()`, and this object contains the code. The website front end can use the code to autofill an input element on the site, or submit the code to the server automatically.
```

2024-05-31 00:59 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
![image](https://github.com/mdn/content/assets/5368500/4f02e999-e567-4528-8661-3c7fb3cfe56f)

So just to be clear on this - the website backend generates a code and sends it to the SMS server _via SMS" - that's what you mean by "then ask the server to send the message containing the code (**only SMS is supported as a transport**)"? 

I guess this allows for other transports in future, but it does feel odd that the website is capable of sending an SMS code to the user, but does so via an intermediary.

This is a little confusing. Suggestion, change image so that instead of `send SMS(code)` it is `send code (SMS transport)` or similar.

2024-05-31 01:03 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +An authenticator is an entity that is inside or attached to the user's device, and that can perform the cryptographic operations needed to register and authenticate users, and securely store the cryp
FMI could this be the google authenticator app, or similar? Just wondering where that kind of OTP might fit in.

2024-05-31 01:03 UTC, hamishwillee commented
Love it. Just a few suggestions.

2024-05-31 02:37 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +> **Note:** Most browsers do not support this credential type and it is not widely used on the web. Instead, browsers automatically offer to store passwords in a password manager, and can automatical
Well I'm not sure, I only learned last week or so that this API isn't really used, because neither MDN [nor web.dev](https://web.dev/articles/security-credential-management) say anything about that. One thing you can do with CM, that the browser won't do for you, is sign people in automatically. I suppose in general gives you much more control over how sign-in happens.

2024-05-31 02:59 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
> So just to be clear on this - the website backend generates a code and sends it to the SMS server _via SMS" 

No. The website backend generates a code then _causes an SMS containing that code to be sent to the device_. In fact how it does that is really an implementation detail in the website backend, IMO. I mean it could do it by having a guy text it from their cellphone, AFAIK, and it would work, just not be very scalable.

I added "SMS server" in response to Chris's comment:

> I'm not sure about the third line down on this diagram — the one that says "Send SMS". The website doesn't send an SMS to the server — it sends a request to the server to send an SMS to the client.
>
> So, perhaps the third line down should say something like "Request server to send SMS", and the fourth line down should be "Send SMS"?

on the previous version of the diagram, that looked like this:

<img width="847" alt="Screen Shot 2024-05-30 at 7 55 56 PM" src="https://github.com/mdn/content/assets/432915/44254235-648b-4b36-a600-3717399c7c20">

...but perhaps it was clearer before?

2024-05-31 03:02 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
I think given that our concept of deprecated is a bit squishy, and that people have gone to the trouble of speccing and implementing a replacement, I'd be happy to call this API deprecated.

2024-05-31 03:02 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
That's because they're defined in different specifications. If we merge the specs they will appear here. (same story as for the sidebar)

2024-05-31 04:09 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +> **Note:** Most browsers do not support this credential type and it is not widely used on the web. Instead, browsers automatically offer to store passwords in a password manager, and can automatical
As it is now the whole rationale is a bit wishy washy, but I'd say this is more than good enough for the current PR. We can find out more in a follow on.

2024-05-31 04:23 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
My take is that "Website back end" implies any servers that it uses, including any SMS server. 

That said I don't have a problem with having the server line. The problem is that `send SMS(code)` implied to me that the backend sent an SMS, and this was reinforced by the text "ask the server to send the message containing the code". 

You can fix this by changing this sentence to add "SMS:

> ask the **SMS** server to send the message containing the code

And update image from `send SMS(code)` to `request SMS code`.

Or revert.

But let's see what @chrisdavidmills says

2024-05-31 04:24 UTC, hamishwillee commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
That would be my preference. I'd try push that through BCD.

2024-05-31 23:33 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
> this was reinforced by the text "ask the server to send the message containing the code".

Yeah, that was because I updated the diagram but forgot to update the text.

I agree that either updating the text or reverting the diagram should work, and am happy to see what Chris thinks.

2024-06-03 09:33 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +- **Passwords** ({{domxref("PasswordCredential")}})
Yes, I think that is clearer; nice one @wbamberg

2024-06-03 09:39 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +Modern browsers provide users with a password manager, which enables users to store the passwords they enter on websites, and later retrieve them when they need to log in again. Password managers can
I agree with this, but even so, it is better for security to not have to write them down at all, regardless of how strong or weak they are.

That said, I will leave it up to you whether you add it. I don't think it is that important to the narrative that I'm going to die on this hill ;-)

2024-06-03 09:43 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
I think @hamishwillee's suggestion works well:

> You can fix this by changing this sentence to add "SMS:
>
>>    ask the SMS server to send the message containing the code
>
> And update image from send SMS(code) to request SMS code.

I don't think we need an additional line for "SMS server"; that just overcomplicated it. I too, am taking "Website back end" to mean "any and all servers that make up the back end portion of the application, which could include an SMS server".

2024-06-03 09:48 UTC, chrisdavidmills commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +> **Note:** Although we're describing all the credential types together here, the different credential types are defined in various different specifications, which extend the main Credential Manageme
"multiple", or "several"? "a number of" always sounds a bit vague and scrappy to me.

2024-06-03 17:42 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Sequence diagram showing sign-in using an OTP credential.](otp-get.svg)
-> https://github.com/mdn/content/pull/33745/commits/bc7a29b3371a4c6fc603534e1dd3efadf18ffef8

2024-06-03 17:50 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +![Class diagram showing the five different credential subclasses.](credential-types.svg)
-> https://github.com/mdn/content/pull/33745/commits/bf06e0b52faa11f2089e4d18ca5c6ebe029b5131

2024-06-03 18:07 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/credential_types/index.md
> +Support for federated identity in the Credential Management API was originally provided through the {{domxref("FederatedCredential")}} interface. However, this mechanism depends on technologies such
-> https://github.com/mdn/content/pull/33745/commits/b25f13dddb907a0e8688e6b53dbad3ab96c8b15c

2024-06-03 18:20 UTC, wbamberg commented on files/en-us/web/api/credential_management_api/index.md
> +  - a replacement type ({{domxref("IdentityCredential")}})
I didn't like this suggestion because it breaks up the bullet list. I tried putting the note at the end but felt it was too much visibility for such a detail in this very high-level section. In the end I copied the table from the "credential types" page - originally the same list appeared in both pages, before I updated the "credential types" page to use a table in https://github.com/mdn/content/pull/33745/commits/13cde577aa3dd3ca5a151a8f53db236c7e5b2d68, in response to https://github.com/mdn/content/pull/33745#discussion_r1620062699.

-> https://github.com/mdn/content/pull/33745/commits/4c42918806aa37a5ba67f3150163e05c1d54ce46

2024-06-03 18:21 UTC, wbamberg commented
OK, I think I'm done with updates to this PR, please take another look :).

2024-06-03 23:12 UTC, hamishwillee approved these changes
I am very happy with the fixes and whole doc.

I would merge, but not sure if @chrisdavidmills has had his final look.

2024-06-04 08:43 UTC, chrisdavidmills approved these changes
This is excellent, lovely work, @wbamberg!

Let's dooooo it!

2024-06-04 08:44 UTC, merged