CSS Module page: CSS Shapes
mdn/content pull request #33809
Opened 2024-05-29 02:30 UTC by estelle

update the css module landing page for CSS shapes. Fixes [#204](https://github.com/mdn/content/pull/33808)

2024-05-29 08:21 UTC, chrisdavidmills requested changes
@estelle few comments for you; looking mostly good.

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +Another resource is [Clippy](https://bennettfeely.com/clippy/), a tool for creating shapes with examples using the {{cssxref("clip-path")}}, which uses the same basic shape functions and values as `s
```suggestion
Another resource is [Clippy](https://bennettfeely.com/clippy/), a tool for creating shapes with examples using {{cssxref("clip-path")}}, which uses the same basic shape functions and values as `shape-outside`.
```

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +The **CSS shapes** module describes geometric shapes that can be used in CSS and defines properties that make use of shapes to control the geometry of an element's float area, to apply to exclusions,
```suggestion
The **CSS shapes** module describes geometric shapes. It also defines CSS properties that can use the shapes to control the geometry of an element's float area; this area can then be applied to exclusions, or specify an element's content area.
```

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +The **CSS shapes** module describes geometric shapes that can be used in CSS and defines properties that make use of shapes to control the geometry of an element's float area, to apply to exclusions,
As it was, this sentence was a bit confusing. I'm not 100% if this suggestion makes sense, but this is the direction I thought it should go in.

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +The specification defines several ways to define shapes. Shapes enable wrapping content around a shape rather than following the rectangle of the element's box. Shapes can also be used to wrap conten
```suggestion
The specification defines several ways to create shapes. Content can be wrapped around or within a shape rather than following the default rectangle shape of the element's box.
```

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +    Developer Tools
```suggestion
    Developer Tools.
```

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +  - : Creating rectangles, circles, ellipses and polygons with CSS shapes, the reference box, and the `shape-outside` property.
```suggestion
  - : Creating rectangles, circles, ellipses, and polygons with CSS shapes, the reference box, and the `shape-outside` property.
```

2024-05-29 08:21 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/index.md
> +  - : Create shapes from images file with an alpha channel and CSS Gradients.
```suggestion
  - : Creating shapes from semi-transparent image files and CSS Gradients.
```

2024-05-29 18:50 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +Another resource is [Clippy](https://bennettfeely.com/clippy/), a tool for creating shapes with examples using {{cssxref("clip-path")}}, which uses the same basic shape functions and values as `shape
```suggestion
Another resource is [Clippy](https://bennettfeely.com/clippy/), a tool for creating shapes with examples using the CSS {{cssxref("clip-path")}} property, which uses the same basic shape functions and values as the `shape-outside` property.

```

2024-05-29 18:51 UTC, estelle commented
i think i was able to fix the flaw too. Still not sure what caused it, but i added an empty line at the end of the page, and that made it happy.

2024-05-30 06:32 UTC, chrisdavidmills approved these changes
@estelle super awesome groovy yeahhhhh.

2024-05-30 06:32 UTC, merged