CSS guide update: basic shapes with shape outside
mdn/content pull request #33804
Opened 2024-05-28 23:48 UTC by estelle

this guide had some issues. 
* Added links
* fixed circle
* added information about newer functions.
* general update and grammar nits

2024-05-29 10:12 UTC, chrisdavidmills requested changes
@estelle some text suggestions for you. Nothing too major. Nice work!

2024-05-29 10:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +As an additional example, use the keywords `top left` for position to make a quarter circle shape in the top left corner of the page. The example below uses generated content to create a quarter-circ
```suggestion
The below example combines generated content with a `circle()` function that uses the keywords `top left` for position. This creates a quarter circle shape in the top left corner of the page for text to flow around.
```

2024-05-29 10:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +An ellipse is essentially a squashed circle. As such, the [`ellipse()`](/en-US/docs/Web/CSS/basic-shape/ellipse) function acts in a very similar way to `circle()`, except that we have to specify two
```suggestion
An ellipse is a squashed circle. As such, the [`ellipse()`](/en-US/docs/Web/CSS/basic-shape/ellipse) function acts in a very similar way to `circle()` except that we have to specify two radii, `x` and `y`, in that order.
```

2024-05-29 10:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +Another basic shape is more complex and enables the creation of multiple-sided polygon shape with the [`polygon()`](/en-US/docs/Web/CSS/basic-shape/polygon) function. This shape accepts three or more
```suggestion
The [`polygon()`](/en-US/docs/Web/CSS/basic-shape/polygon) function is more complex, enabling the creation of multiple-sided polygon shapes. This shape accepts three or more pairs of values (a polygon must at least draw a triangle). Each space-separated pair of values is separated with a comma and represents the coordinates of a single vertex drawn relative to the reference box. Each pair of coordinates defines an edge of the polygon, with the final edge defined by the first and last set of coordinates.
```

2024-05-29 10:12 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The example below creates a shape for text to follow using the `polygon()`. Change any of the coordinate values to see how the shape is changed.
```suggestion
The example below creates a shape for text to follow using the `polygon()` function. Try changing the coordinate values to see how the shape changes.
```

2024-05-29 18:13 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The [`inset()`](/en-US/docs/Web/CSS/basic-shape/inset) function defines a rectangle. This may not seem very useful as floating an item, without shapes, will give you a rectangular shape around it. Ho
I didn't like the original either, but this edit isn't quite right either. will marinate.

2024-05-29 18:14 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The `margin-box` will clip the shape. This means that shapes created in reference to other shapes that extend past the margin box will have the shape clipped to the margin box. This is demonstrated f
i didn't know what the original meant either. Will work on this too since i am not the only one perplexed.

2024-05-29 18:14 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The [`circle()`](/en-US/docs/Web/CSS/basic-shape/circle) value for `shape-outside` can accept two possible arguments. The first is the `shape-radius`.
good suggestion. will do.

2024-05-29 18:15 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +For your shape to use a different reference box, include a different {{cssxref("box-edge")}} value, for example, to use the border as a reference box for our circle, set:
no. the previous example is using the default. The next example changes the default.

2024-05-29 18:22 UTC, estelle reviewed
edits made in the GUI

2024-05-29 18:22 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The `margin-box` will clip the shape. This means that shapes created in reference to other shapes that extend past the margin box will have the shape clipped to the margin box. This is demonstrated f
```suggestion
Shapes created that extend past the margin box will have the shape clipped to the margin box. The following basic shapes demonstrate this.
```

2024-05-29 18:22 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The [`inset()`](/en-US/docs/Web/CSS/basic-shape/inset) function defines a rectangle. This may not seem very useful as floating an item, without shapes, will give you a rectangular shape around it. Ho
```suggestion
The [`inset()`](/en-US/docs/Web/CSS/basic-shape/inset) function defines a rectangle. This may not seem very useful as floating an item, without shapes, will give you a rectangular shape around it. However, the `inset()` type enables the definition of offsets, thus pulling the wrapping text around the reduced-size rectangle, over parts of the floated element.
```

2024-05-29 18:22 UTC, estelle commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The [`circle()`](/en-US/docs/Web/CSS/basic-shape/circle) value for `shape-outside` can accept two possible arguments. The first is the `shape-radius`.
```suggestion
The [`circle()`](/en-US/docs/Web/CSS/basic-shape/circle) value for `shape-outside` can accept two possible arguments: a `<shape-radius>` defining the size and the `<position>` defining its location.
```

2024-05-30 06:35 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +For your shape to use a different reference box, include a different {{cssxref("box-edge")}} value, for example, to use the border as a reference box for our circle, set:
Ah, right, ok. Yup, re-reading this, it makes sense.

2024-05-30 06:38 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The `margin-box` will clip the shape. This means that shapes created in reference to other shapes that extend past the margin box will have the shape clipped to the margin box. This is demonstrated f
I've read your update, and it makes a lot more sense. Nice work.

2024-05-30 06:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +The [`inset()`](/en-US/docs/Web/CSS/basic-shape/inset) function defines a rectangle. This may not seem very useful as floating an item, without shapes, will give you a rectangular shape around it. Ho
Yup update seems OK here too.

2024-05-30 06:41 UTC, chrisdavidmills approved these changes
@estelle great, I like the updates here too. Good to go!

2024-05-30 06:41 UTC, merged