Add optional_host_permissions docs
mdn/content pull request #33811
Opened 2024-05-29 04:04 UTC by rebloor

### Description

Adds documentation for `optional_host_permissions` in support of [Bug 1766026](https://bugzilla.mozilla.org/show_bug.cgi?id=1766026) Add optional_host_permissions in mv3 including:

- new `optional_host_permissions` key page
- updates to `optional_permissions` key page re specification of hosts
- updates to permissions API to add reference to `optional_host_permissions`
- release note

### Related issues and pull requests

Related BCD changes in https://github.com/mdn/browser-compat-data/pull/23177

2024-06-04 19:05 UTC, zombie requested changes

2024-06-04 19:05 UTC, zombie commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/contains/index.md
> +The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), [opti
I don't see where you've added the `#optional_host_permissions` anchor to the `manifesst.json/permissions` page, did I miss something?

In any case, I don't think we need this and the next three changes to the API methods docs, the existing text already links to the general explanation about host permissions [1], not to a specific manifest key like `optional_permissions`, so linking to `optional_host_permissions` key doesn't seem necessary here IMO.

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/optional_permissions/index.md
> +Starting with Firefox 84, users can to manage optional permissions from the Firefox Add-ons Manager. Extensions that use optional permissions can listen for [browser.permissions.onAdded](/en-US/docs/
```suggestion
Starting with Firefox 84, users can manage optional permissions from the Firefox Add-ons Manager. Extensions that use optional permissions can listen for [browser.permissions.onAdded](/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/onAdded) and [browser.permissions.onRemoved](/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/onRemoved) API events to know when a user grants or revokes these permissions.
```

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/contains/index.md
> +The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), [opti
@zombie Good point - I think I got carried away there! On further review, I also see that I needed a change under that "Host permissions" section

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/contains/index.md
> +The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), [opti
```suggestion
The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or a `permissions` property, which is an array of [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions), or both.
```

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/index.md
> +- The extension may need [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or [optional_host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensi
```suggestion
- The extension may need [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), but not know at install time which host permissions it needs. For example, the list of hosts may be a user setting. In this scenario, asking for a more specific range of hosts at runtime, can be an alternative to asking for "\<all_urls>" at install time.
```

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/permissions/index.md
> +  - : An array of [match patterns](/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns), representing [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_
```suggestion
  - : An array of [match patterns](/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns), representing [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions).
```

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/remove/index.md
> +The `Permissions` argument may contain either an `origins` property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), [op
```suggestion
The `Permissions` argument may contain either an `origins` property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), or a `permissions` property, which is an array of [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions), or both. Permissions must come from the set of permissions defined in the [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) manifest.json key.
```

2024-06-04 23:27 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/request/index.md
> +The `Permissions` argument may contain either an `origins` property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), [op
```suggestion
The `Permissions` argument may contain either an `origins` property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), or a `permissions` property, which is an array of [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions), or both. Permissions must come from the set of permissions defined in the [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) manifest.json key. The `origins` property may include permissions that match a subset of the hosts matched by an optional permission: for example, if optional_permissions include "\*://mozilla.org/", then `permissions.origins` may include "https\://developer.mozilla.org/".
```

2024-06-04 23:29 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/contains/index.md
> +The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions) or a `
```suggestion
The `Permissions` argument may contain either an origins property, which is an array of [host permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions), or a `permissions` property, which is an array of [API permissions](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions), or both.
```

2024-06-13 11:18 UTC, zombie approved these changes
thanks, lgtm.

2024-07-17 02:31 UTC, dotproto approved these changes
Only minor changes requested. Pre-approving to avoid blocking.

2024-07-17 02:31 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/optional_host_permissions/index.md
> +Use the {{webextapiref("permissions")}} API to ask for a permission. Asking for a permission may present the user with a dialog requesting they grant the host permission to your extension.
Since the method that the extension would call is named `request()`, I think we should use that verb for the operation performed by the developer rather than "ask."

```suggestion
Use the {{webextapiref("permissions")}} API to request an optional host permission at runtime. Requesting a host permission may present the user with a dialog asking whether they want to grant the permission to your extension.
```

2024-07-17 02:34 UTC, merged