New glossary: logical properties
mdn/content pull request #33860
Opened 2024-05-31 20:58 UTC by estelle

Part of https://github.com/openwebdocs/project/issues/205; 
which is needed for https://github.com/openwebdocs/project/issues/178

2024-06-03 10:23 UTC, chrisdavidmills requested changes
@estelle few bits for you to look at; looking mostly good!

2024-06-03 10:23 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +CSS **logical properties** provide a way to style layouts based on the document's writing mode and direction rather than the physical dimensions of the viewport. This enables more flexible and mainta
```suggestion
CSS **logical properties** provide a way to lay out content based on the document's writing mode and direction rather than the physical dimensions of the viewport. This enables more flexible and maintainable designs, especially for websites supporting multiple languages.
```

2024-06-03 10:23 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +Properties like {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} are **physical properties**. They define positions based on physical directions; with top, rig
It feels like you are saying the same thing twice in the two sentences of this paragraph, unless I'm missing something. Can you try to clarify this, or amalgamate the two together?

2024-06-03 10:23 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +The **block axis** refers to the axis that defines the stacking order of elements in a block layout. It's essentially the direction along which blocks of content, like paragraphs ({{htmlelement("p")}
```suggestion
The **block axis** refers to the axis that defines the stacking order of elements in a block layout. It's essentially the direction along which blocks of content, like paragraphs ({{htmlelement("p")}}), headings, and divs ({{htmlelement("div")}}), are laid out on a webpage. This is the vertical direction of the content flow, going from top to bottom, in left-to-right and left-to-right languages. **block-start** and **block-end** represent the start edge and end edge of content along the block axis, respectively, with `block-start` being the equivalent of `top` and `block-end` being the equivalent of `bottom`. In Japanese
```

2024-06-03 10:23 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +The **block axis** refers to the axis that defines the stacking order of elements in a block layout. It's essentially the direction along which blocks of content, like paragraphs ({{htmlelement("p")}
You've also got a last sentence "In Japanese..." that needs completing.

2024-06-03 10:23 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +The **inline axis** is perpendicular to the block axis. The inline axis represents the direction along which inline content like text flows within a block. This is the horizontal direction of the con
```suggestion
The **inline axis** is perpendicular to the block axis. The inline axis represents the direction along which inline content like text flows within a block. This is the horizontal direction of the content flow, going from left to right in left-to-right writing modes, like English, and right to left in right-to-left languages, like Arabic and Hebrew. The **inline-start** and **inline-end** directions depend on the writing direction. `inline-start` and `inline-end` represent the start edge and end edge of content along the inline axis, respectively. They are the equivalent of `left` and `right` for left-to-right writing modes, and `right` and `left` in right-to-left writing modes.
```

2024-06-03 18:29 UTC, estelle commented
@chrisdavidmills I rewrote it, integrating your suggestions, and added a physical properties glossary entry

2024-06-04 08:41 UTC, chrisdavidmills requested changes
Few more comments for you to consider. Nice work @estelle.

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}} define positions based on physical directions; with {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} referring to t
```suggestion
Whereas {{glossary("physical properties")}} define positions based on physical directions, logical properties such as {{cssxref("margin-block-start")}} and {{cssxref("padding-inline-end")}} use logical directional keywords relative to the content flow along the block and inline axes.
```

I don't think all of the physical examples are needed. You link to the physical properties page, where you provide examples of such properties. The original was rather long and cumbersome to read.

I have also included the information provided by the sentence above the "See also" section, which I am suggesting you delete.

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +The **block axis** refers to the axis that defines the stacking order of elements in a block layout. It's essentially the direction along which blocks of content, or **block direction**, like paragra
```suggestion
The **block axis** refers to the axis that defines the stacking order of elements in a block layout. It's essentially the direction along which blocks of content — like paragraphs ({{htmlelement("p")}}), headings, and divs ({{htmlelement("div")}}) — are laid out on a webpage. This is also known as the **block direction**. In left-to-right and left-to-right languages, the block direction is the vertical direction of the content flow, going from top to bottom.
```

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +The **inline axis** is perpendicular to the block axis. The inline axis represents the direction along which inline content, or **inline direction**, like text flows within a block. This is the horiz
```suggestion
The **inline axis** is perpendicular to the block axis. The inline axis represents the direction along which inline content such as text flows within a block. This is also known as the **inline direction**. In left-to-right writing modes, like English, the inline direction is horizontal, left-to-right. In right-to-left languages, like Arabic and Hebrew, the inline direction is horizontal, right-to-left.
```

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +**Inline-start** and **inline-end** represent the _start edge_ and _end edge_ of content along the inline axis, respectively, with the values and properties `inline-start` and `inline-end` being the
```suggestion
**Inline-start** and **inline-end** represent the _start edge_ and _end edge_ of content along the inline axis, respectively, with the values and properties `inline-start` and `inline-end` being equivalent to `left` and `right` properties and values in horizontal writing modes. Which ones are equivalent to `right` or `left` depends on the writing direction — for example `inline-start` is `left` in left-to-right languages and `right` in right-to-left languages.
```

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +Therefore, logical properties, like {{cssxref("margin-block-start")}} and {{cssxref("padding-inline-end")}}, use logical keywords relative to the content flow.
I'd suggest removing this and moving these details as per my suggestion above. This sentence feels a bit out of place and without context, in the current position.

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/physical_properties/index.md
> +CSS **physical properties** provide are CSS properties that define positions based on physical directions - such as {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("lef
```suggestion
CSS **physical properties** define positions based on physical directions or element sides. For example:

- The [inset properties](/en-US/docs/Glossary/Inset_properties) {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} refer to the physical dimensions of the viewport.
- Features such as {{cssxref("margin-top")}}, {{cssxref("border-right")}}, {{cssxref("padding-bottom")}}, and {{cssxref("border-bottom-left-radius")}} reference specific sides of an element, and style features by that physical direction.
```

2024-06-04 08:41 UTC, chrisdavidmills commented on files/en-us/glossary/physical_properties/index.md
> +This is opposed to {{glossary("logical properties")}}, which are relative to the content flow and use directional keywords that are relative to the block and inline axes.
```suggestion
This is opposed to {{glossary("logical properties")}}, which are relative to the content flow and use directional keywords relative to the block and inline axes.
```

2024-06-05 19:12 UTC, estelle commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}} define positions based on physical directions; with {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} referring to t
```suggestion
Whereas {{glossary("physical properties")}}, like {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("padding-bottom")}}, and {{cssxref("border-bottom-left-radius")}},  efine positions based on physical directions and reference specific sides of an element, logical properties logical properties such as {{cssxref("margin-block-start")}} and {{cssxref("padding-inline-end")}} use logical directional keywords that are relative to the content flow along the block and inline axes.
```

2024-06-05 19:12 UTC, estelle commented on files/en-us/glossary/logical_properties/index.md
> +Therefore, logical properties, like {{cssxref("margin-block-start")}} and {{cssxref("padding-inline-end")}}, use logical keywords relative to the content flow.
```suggestion
```

2024-06-05 19:17 UTC, estelle commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}} define positions based on physical directions; with {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} referring to t
Went with:

```
Whereas {{glossary("physical properties")}}, like {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("padding-bottom")}}, and {{cssxref("border-bottom-left-radius")}}, define positions and features based on physical directions and reference specific sides of an element, logical properties such as {{cssxref("block-start")}}, {{cssxref("inline-end")}}, {{cssxref("padding-block-end")}}, and {{cssxref("border-end-end-radius")}} use logical directional keywords that are relative to the content flow along the block and inline axes.
```

using 4 physical properties and their mapped logical property equivalents. I think that improves it a lot.

2024-06-05 19:17 UTC, estelle commented on files/en-us/glossary/logical_properties/index.md
> +Therefore, logical properties, like {{cssxref("margin-block-start")}} and {{cssxref("padding-inline-end")}}, use logical keywords relative to the content flow.
done

2024-06-06 08:04 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}} define positions based on physical directions; with {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} referring to t
Much better — my only issue is that I don't think `block-start` and `inline-end` are properties. Did you mean `margin-block-start` and `margin-inline-end`, or similar?

2024-06-06 08:05 UTC, chrisdavidmills commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}} define positions based on physical directions; with {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("bottom")}}, and {{cssxref("left")}} referring to t
The links are broken, you see. Of course, we might just not have documented them yet...

2024-06-06 08:10 UTC, chrisdavidmills approved these changes
Nice work @estelle; LGTM, pending one little query about property names. Should be a quick fix, so I'll approve.

2024-06-06 08:10 UTC, chrisdavidmills commented
@estelle the query is here: https://github.com/mdn/content/pull/33860#discussion_r1628974028

(just in case you have trouble finding it)

2024-06-06 08:32 UTC, estelle commented on files/en-us/glossary/logical_properties/index.md
> +Whereas {{glossary("physical properties")}}, like {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("padding-bottom")}}, and {{cssxref("border-bottom-left-radius")}}, define positions and features
```suggestion
Whereas {{glossary("physical properties")}}, like {{cssxref("top")}}, {{cssxref("right")}}, {{cssxref("padding-bottom")}}, and {{cssxref("border-bottom-left-radius")}}, define positions and features based on physical directions and reference specific sides of an element, logical properties such as {{cssxref("inset-block-start")}}, {{cssxref("inset-inline-end")}}, {{cssxref("padding-block-end")}}, and {{cssxref("border-end-end-radius")}} use logical directional keywords that are relative to the content flow along the block and inline axes.
```

2024-06-06 08:33 UTC, merged