Clarify `chrome.runtime.getPlatformInfo()` usage in different extension contexts
mdn/content pull request #33890
Opened 2024-06-03 05:45 UTC by Ashish-CodeJourney

### Description

Clarified the usage of `chrome.runtime.getPlatformInfo()` in the documentation to indicate that it can be called from various extension contexts, including background scripts, popups, options pages, and content scripts.

### Motivation

The current documentation suggests that `chrome.runtime.getPlatformInfo()` can only be called from the background script context. However, testing has shown that this API can be used in other contexts as well. Updating the documentation will help developers better understand the versatility of this API and avoid potential confusion.

### Additional details

### Related issues and pull requests

"Fixes #33874

2024-06-03 22:10 UTC, denilsonsa commented
If it can be called in so many contexts… Where is it blocked? Nowhere? Would it be better to remove that sentence completely?

(Feedback from the point of view of a web developer, I don't know how it is implemented in the real browsers.)

2024-06-04 04:57 UTC, Ashish-CodeJourney commented
> If it can be called in so many contexts… Where is it blocked?

while the `chrome.runtime` API is accessible in various contexts, its usage is limited in the web page's execution environment due to Content Security Policy restrictions. Content scripts and the Chrome Extension's own execution environment offer broader access to this API.

2024-06-10 05:26 UTC, Ashish-CodeJourney commented
@jpmedley what do you this, does this sounds good ?

2024-06-19 10:17 UTC, Ashish-CodeJourney commented
@Josh-Cena can you please look into this PR too ? I raised it a few weeks back and still there is no response from reviewer.

2024-06-19 10:28 UTC, Josh-Cena commented
Please ping @mdn/yari-content-mozilla-add-ons next time. I'm not a WebExt reviewer.

2024-06-19 10:30 UTC, Ashish-CodeJourney commented
> mdn/yari-content-mozilla-add-ons

Okay got it, 
and Thanks

2024-06-19 10:37 UTC, Ashish-CodeJourney commented
@mdn-bot

2024-06-19 10:41 UTC, Ashish-CodeJourney commented
@rebloor can you please look into it ?

2024-06-19 11:39 UTC, Rob--W requested changes

2024-06-19 11:39 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/runtime/getplatforminfo/index.md
> +Returns information about the current platform. This can be called in the background script context as well as in popups, options pages, and content scripts.
This method is not available to content scripts. Please edit the suggestion to just drop the last sentence, since unless stated otherwise, an API is available to background scripts, popup pages, etc.

2024-06-19 13:10 UTC, Rob--W requested changes

2024-06-20 04:38 UTC, Ashish-CodeJourney commented
@Rob--W 
thanks :)

2024-06-20 08:26 UTC, Rob--W approved these changes

2024-06-20 09:49 UTC, merged