Update index.md
mdn/content pull request #33913
Opened 2024-06-04 14:28 UTC by shaon07

update the class syntax. previously it was give wrong class syntax. i fix it with write one.

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-06-04 17:37 UTC, Josh-Cena requested changes
Please revert the change that added your name. That's totally unnecessary.

2024-06-05 02:12 UTC, estelle commented on files/en-us/learn/javascript/objects/object-oriented_programming/index.md
> +const shamirul = new Professor("MD Shamirul Islam", "mathematician");
Please don't include your name or the names of actual people in the documentation.

2024-06-05 02:33 UTC, wbamberg commented
As it says at the start of the page:

> For now, we'll describe these concepts without reference to JavaScript in particular, so all the examples are given in [pseudocode](https://developer.mozilla.org/en-US/docs/Glossary/Pseudocode).

The idea is that this page is not about JS per se, but OO concepts in general. So using pseudocode is intentional.

With this, people have to understand all the JS class syntax, which we haven't taught yet.

And this PR makes the page incoherent: for example the first code sample doesn't include a constructor, because we haven't talked about them yet. But this PR adds a constructor to the first sample, which the accompanying prose doesn't then mention, and then the next bit starts randomly talking about constructors.

2024-06-05 05:41 UTC, skyclouds2001 reviewed
I think the change it not correct, as it is only pseudocode to represent the concept of OOP

2024-06-05 05:53 UTC, Josh-Cena commented
Closing since this page is not about JavaScript.

2024-06-05 05:53 UTC, closed without merging