Add CloseWatcher reference pages
mdn/content pull request #33910
Opened 2024-06-04 12:20 UTC by Elchi3

### Description

Adds references pages for `CloseWatcher`. 

I reckon that my work here is quite minimal. Would be cool to write a bit more about this either in this PR or as a follow-up. 

### Motivation

This API is new and ships in Chromium based browsers in M126.

### Additional details

Link to spec: https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface

### Related issues and pull requests

BCD: https://github.com/mdn/browser-compat-data/pull/23207

2024-06-07 03:32 UTC, wbamberg requested changes

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +A `cancel` event is fired at a {{domxref("CloseWatcher")}} object before the `close` event, so that `close` can be prevented from firing, if necessary.
Should say in what circumstances this event is fired. I believe, if the user activates the close method (e.g. Escape, etc) or `requestClose()` is called.

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +```
The spec also has a better  example here:

```js
watcher.oncancel = async (e) => {
  if (hasUnsavedData && e.cancelable) {
    e.preventDefault();

    const userReallyWantsToClose = await askForConfirmation("Are you sure you want to close?");
    if (userReallyWantsToClose) {
      hasUnsavedData = false;
      watcher.close();
    }
  }
};
```

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +A `cancel` event is fired at a {{domxref("CloseWatcher")}} object before the `close` event, so that `close` can be prevented from firing, if necessary.
The spec indicates that you can't always cancel the event:

> For abuse prevention purposes, this event is only [cancelable](https://dom.spec.whatwg.org/#dom-event-cancelable) if the page has [history-action activation](https://html.spec.whatwg.org/multipage/interaction.html#history-action-activation), which will be lost after any given [close request](https://html.spec.whatwg.org/multipage/interaction.html#close-request). This ensures that if the user sends a close request twice in a row without any intervening user activation, the request definitely succeeds; the second request ignores any [cancel](https://html.spec.whatwg.org/multipage/indices.html#event-cancel) event handler's attempt to call [preventDefault()](https://dom.spec.whatwg.org/#dom-event-preventdefault) and proceeds to close the [CloseWatcher](https://html.spec.whatwg.org/multipage/interaction.html#closewatcher).

(also while I'm here `cancel` seems like an odd name for this event. I'd expect the name of an event to reflect the thing that happened (e.g. `click` when the user clicks) but that doesn't seem to apply here. I wonder why it's not called `beforeclose`)

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +The `cancel` event can be used to interrupt the close request. The `cancel` event is triggered by the `requestClose()` method.
It's unclear what "interrupt" means. Should it be "can be used to cancel..."?

Also it is (I think?) not only triggered by `requestClose()`, is it?

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/close_event/index.md
> +A `close` event is fired at a {{domxref("CloseWatcher")}} object when a close request was received.
I think it's worth being more clear on what "a close request was received" means. Also maybe worth saying that it is only fired if the `cancel` event that preceded this one was not canceled.

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/close_event/index.md
> +  // Dispose the watcher instance
```suggestion
  // Dispose of the watcher instance
```

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/close_event/index.md
> +A `close` event is fired at a {{domxref("CloseWatcher")}} object when a close request was received.
Also perhaps worth saying what you might expect to do in the `close` handler - close the UI component and call `destroy()`? When should you/shouldn't you call destroy?

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +The **`CloseWatcher()`** constructor creates a new {{domxref("CloseWatcher")}} object.
I think interesting things happen if you create more than one CloseWatcher, as described in the spec:

> If any [close watcher](https://html.spec.whatwg.org/multipage/interaction.html#close-watcher) is already active, and the [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window) does not have [history-action activation](https://html.spec.whatwg.org/multipage/interaction.html#history-action-activation), then the resulting [CloseWatcher](https://html.spec.whatwg.org/multipage/interaction.html#closewatcher) will be closed together with that already-active [close watcher](https://html.spec.whatwg.org/multipage/interaction.html#close-watcher) in response to any [close request](https://html.spec.whatwg.org/multipage/interaction.html#close-request). (This already-active [close watcher](https://html.spec.whatwg.org/multipage/interaction.html#close-watcher) does not necessarily have to be a [CloseWatcher](https://html.spec.whatwg.org/multipage/interaction.html#closewatcher) object; it could be a modal [dialog](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) element, or a popover generated by an element with the [popover](https://html.spec.whatwg.org/multipage/popover.html#attr-popover) attribute.)

...and in the last example under https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface.

Especially this is interesting:

> This means that calling [destroy()](https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcher-destroy), [close()](https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcher-close), or [requestClose()](https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcher-requestclose) properly is important. Doing so is the only way to get back the "free" ungrouped close watcher slot. Such close watchers created without user activation are useful for cases like session inactivity timeout dialogs or urgent notifications of server-triggered events, which are not generated in response to user activation.

...and it seems like we could provide some guidance here, although I'm not sure what...

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +let signalWatcher = new CloseWatcher({ signal: controller.signal };
These don't need to be `let`.

And given that creating two watchers causers things to happen, it might be better to split this example.

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +      - : An {{domxref("AbortSignal")}} that, if provided, the watcher can be destroyed by.
The spec is clearer here:

> If the [signal](https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcheroptions-signal) option is provided, then watcher can be destroyed (as if by [watcher.destroy()](https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcher-destroy)) by aborting the given [AbortSignal](https://dom.spec.whatwg.org/#abortsignal).

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +- {{domxref("CloseWatcher")}}, the interface of the objects it constructs.
This doesn't seem very useful.

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/destroy/index.md
> +The **`destroy()`** method of the {{domxref("CloseWatcher")}} interface deactivates the close watcher so that it will no longer receive `close` events.
```suggestion
The **`destroy()`** method of the {{domxref("CloseWatcher")}} interface deactivates the close watcher so that it will no longer receive `cancel` or `close` events.
```

?

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/destroy/index.md
> +Use the `destory()` method to dispose the watcher instance
```suggestion
Use the `destroy()` method to dispose of the watcher instance
```

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/destroy/index.md
> +  // Dispose the watcher instance
```suggestion
  // Dispose of the watcher instance
```

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/destroy/index.md
> +The **`destroy()`** method of the {{domxref("CloseWatcher")}} interface deactivates the close watcher so that it will no longer receive `close` events.
Again the spec gives some helpful guidance and context:

> Deactivates watcher, so that it will no longer receive [close](https://html.spec.whatwg.org/multipage/indices.html#event-close) events and so that new independent [CloseWatcher](https://html.spec.whatwg.org/multipage/interaction.html#closewatcher) instances can be constructed.
>
> This is intended to be called if the relevant UI element is torn down in some other way than being closed.

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/close/index.md
> +The **`close()`** method of the {{domxref("CloseWatcher")}} interface immediately fires the `close` event and deactivates the close watcher as if `destroy()` was called. It skips any logic in the `ca
As said before "It skips any logic in the `cancel` event handler.". It's more like, "call this method if YOU want to skip any logic..."

2024-06-07 03:32 UTC, wbamberg commented on files/en-us/web/api/closewatcher/requestclose/index.md
> +The **`requestClose()`** method of the {{domxref("CloseWatcher")}} interface fires a `cancel` event and if that event is not canceled with {{domxref("Event.preventDefault()")}}, proceeds to fire a `c
...and again the spec is helpful here:

> This is a helper utility that can be used to consolidate cancelation and closing logic into the [cancel](https://html.spec.whatwg.org/multipage/indices.html#event-cancel) and [close](https://html.spec.whatwg.org/multipage/indices.html#event-close) event handlers, by having all non-[close request](https://html.spec.whatwg.org/multipage/interaction.html#close-request) closing affordances call this method.

2024-06-24 19:01 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/index.md
> +The `CloseWatcher` API listens and responds to close requests. A close request can be for anything that the user wants to close, like a [popover](/en-US/docs/Web/API/Popover_API), a sidebar, a [dialo
Yes dialog (specifically when showModal is used) and popover (specifically when popover="auto") have an internal close watcher, so you don't need to use this API for those elements. However, for anything else you make yourself you would use this API.

2024-06-24 19:03 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/index.md
> +  // Close if some condition is met
A common case might be if you want to show an Are you sure prompt when closing an element with a "dirty" form inside.

2024-06-24 19:07 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +A `cancel` event is fired at a {{domxref("CloseWatcher")}} object before the `close` event, so that `close` can be prevented from firing, if necessary.
It's named cancel because that matches the existing Dialog event nomenclature. Dialogs have a cancel and a close. So close watcher is based on that.

The exact mechanics of when a cancel event is cancelable are slightly tricky to explain (and that's from someone who's written two implementations of this API). I'm also not entirely sure its useful to a developer, to know the exact specifics, I think it's more useful to just point out that it can't always be cancelled. (just my opinion)

2024-06-24 19:08 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +```
This isn't a very good example afaict this might not even work. Event listeners are synchrounous?

You'd be better off leaving this as a sync function and just using https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm in the example

2024-06-24 19:14 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +The `cancel` event can be used to interrupt the close request. The `cancel` event is triggered by the `requestClose()` method.
It's triggered by all close signals as well as `requestClose()`.

2024-06-24 19:16 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/close_event/index.md
> +A `close` event is fired at a {{domxref("CloseWatcher")}} object when a close request was received.
You don't need to call destroy() in a close event listener, close destroys the close watcher itself (in fact it does it before even dispatching the close event).

destroy is useful for example if you want to cleanup a component upon dismount, for example it's possible the close watcher is associated with a component that gets removed from the DOM before being closed. In that case you'd want to destroy the close watcher. In the same way you might call `removeEventListener` in a cleanup step.

2024-06-24 19:17 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/close_event/index.md
> +  // Dispose the watcher instance
As mentioned above you shouldn't be calling destroy inside of the close event

2024-06-24 19:21 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +A new {{domxref("CloseEvent")}} object.
The return value of the constructor is a CloseWatcher not a CloseEvent.

2024-06-24 19:23 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +```
Also worth noting that in both examples above you are explicitly calling close again. But requestClose will call close when cancel isn't prevented. Hence why my example falls through to close in most cases without any explicit API call

2024-07-02 10:07 UTC, lukewarlow commented
Anything I can do to help get this across the line? It's shipped in Chrome and I have a webkit implementation so it'll hopefully be merged and released there soon, having these docs will be useful for developers to make use of it.

2024-07-02 17:01 UTC, wbamberg commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +```
> Event listeners are synchrounous?

I'm not going to argue with you, but just for my education, isn't it fine to have asynchronous event listeners?

2024-07-02 17:30 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/cancel_event/index.md
> +```
It depends what you're trying to do with it. But it'd be like if you had a function that returns a promise. You called the function but you didn't actually wait on the response. In this case the decision you're awaiting isn't actually waited on by the event loop.

Your specific example I think would work because of how it's set up (you always preventDefault the event and then call close directly), but I just generally try to avoid using async event listeners because they're hard to reason about.

2024-07-02 19:42 UTC, wbamberg requested changes

2024-07-02 19:42 UTC, wbamberg commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +The **`CloseWatcher()`** constructor creates a new {{domxref("CloseWatcher")}} object.
Do you think it is worth trying to explain some of this: https://github.com/mdn/content/pull/33910/files#r1630586073 ? I think it would be helpful to but it's hard.

For the second quote we could perhaps say something like:

```suggestion
The **`CloseWatcher()`** constructor creates a new {{domxref("CloseWatcher")}} object.

You can create `CloseWatcher` instances without [user activation](/en-US/docs/Web/Security/User_activation), and this can be useful to implement cases like session inactivity timeout dialogs. However, if you create more than one `CloseWatcher` without user activation, then the newly-created one will be grouped together with the last one, so a single close request will close them both. This means that it is important to call {{domxref("CloseWatcher.destroy()", "destroy()")}}, {{domxref("CloseWatcher.close()", "close()")}}, and {{domxref("CloseWatcher.requestClose()", "requestClose()")}} properly.
```

The first one I don't know what to do about though, because I'm not sure how we can gloss "history-action activation".

2024-07-02 19:42 UTC, wbamberg commented on files/en-us/web/api/closewatcher/index.md
> +The `CloseWatcher` interface listens and responds to close requests. The user usually sends close requests using the <kbd>Esc</kbd> key, the back button on Android, the "z" gesture on iOS VoiceOver,
```suggestion
The `CloseWatcher` interface listens and responds to close requests.

Some UI components have "close behavior", meaning that the component appears, and the user can close it when they are finished with it. For example: sidebars, popups, dialogs, or notifications.

Users generally expect to be able to use a particular mechanism to close these elements, and the mechanism tends to be device-specific. For example, on a device with a keyboard it might be the <kbd>Esc</kbd> key, but Android might use the back button. For built-in components, such as [popover](/en-US/docs/Web/API/Popover_API) or {{htmlelement("dialog")}} elements, the browser takes care of these differences, closing the element when the user performs the close action appropriate for the device. However, when a web developer implements their own closable UI component (for example, a sidebar), it is hard to implement this kind of device-specific close behavior. The `CloseWatcher` interface solves this problem by delivering a `close` event to the when the user executes the close action for the device.
```

(just a suggestion, please feel free to reject if you prefer the original)

2024-07-03 11:29 UTC, Elchi3 commented
Thank you Will for reviewing this so thoroughly and making these docs so much better than my lazy initial pull request. I've accepted your suggestions.

2024-07-04 07:02 UTC, wbamberg approved these changes
I'm happy it's helpful, Florian :).

I will approve this but won't merge in case @lukewarlow has comments, especially whether can do better with https://github.com/mdn/content/pull/33910#discussion_r1663053251. I don't think this is a blocker for getting the PR merged though.

2024-07-04 13:35 UTC, lukewarlow commented on files/en-us/web/api/closewatcher/closewatcher/index.md
> +The **`CloseWatcher()`** constructor creates a new {{domxref("CloseWatcher")}} object.
Yeah I think that suggestion is probably about as good as you can get without being overly technical. Perhaps could just mention disposing (via destroy()) is important because of anti abuse mechanisms which may lead to multiple close watchers being closed at once otherwise?

2024-07-04 13:37 UTC, lukewarlow reviewed
LGTM

2024-07-04 16:33 UTC, merged