33695 radio button constraint validation
mdn/content pull request #33925
Opened 2024-06-04 22:29 UTC by estelle

fixes #33695 33695

2024-06-05 07:08 UTC, chrisdavidmills requested changes
Some thoughts

2024-06-05 07:08 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/radio/index.md
> +While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`v
This sounds a little over-complicated to me. For example, any radio button with `required` set will trigger the specified validation, not just ones in a group, and the description of the validation will probably sound a bit confusing to some, without any context of what that is in real terms (i.e. the browser telling you that you need to select an option).

How about something like this:

```suggestion
While radio buttons have no real value to be constrained, they can be set as required. Any radio button with the [`required`](/en-US/docs/Web/HTML/Attributes/required) attribute set (either directly, or via another radio button in a same-name group) will trigger the browser's in-built validation if no option is selected when form submission is attempted. The browser will ask the user to select an option. This is equivalent to the [`valueMissing`](/en-US/docs/Web/API/ValidityState/valueMissing) property of a {{domxref("ValidityState")}} object returning true during validation.
```

Hrm, still seems a bit wordy. Let me know if that helps at all.

2024-06-05 18:37 UTC, estelle commented on files/en-us/web/html/element/input/radio/index.md
> +While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`v
It is not the equivalent of valueMissing; it is ValueMissing . i'll rework it to include a single required.

2024-06-05 18:41 UTC, estelle commented on files/en-us/web/html/element/input/radio/index.md
> +While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`v
```suggestion
If a radio button is required or a same-named group or radio buttons has at least one member with `required` set, and no radio buttons is checked, the [`valueMissing`](/en-US/docs/Web/API/ValidityState/valueMissing) property of a {{domxref("ValidityState")}} object will return true during validation.
```

2024-06-06 07:35 UTC, chrisdavidmills commented on files/en-us/web/html/element/input/radio/index.md
> +While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`v
Ah, OK, so it is actually what `required` uses under the hood! Cool, I didn't know that.

2024-06-06 07:44 UTC, chrisdavidmills approved these changes
I had another suggestion for you. I'll approve this time so you can put this one to bed.

2024-06-06 08:37 UTC, estelle commented on files/en-us/web/html/element/input/radio/index.md
> +While radio buttons have no real value to be constrained, if any radio button in a same-name group of radio buttons has the `required` attribute set, and none of the radio buttons is checked, the [`v
```suggestion
In the case of a radio button with the [`required`](/en-US/docs/Web/HTML/Attributes/required) attribute set or a same-named group of radio buttons in which at least one member has required set, a radio button needs to be selected for the control to be considered valid. If no radio button is checked, the [`valueMissing`](/en-US/docs/Web/API/ValidityState/valueMissing) property of a {{domxref("ValidityState")}} object will return true during validation, and the browser will ask the user to select an option.
```

2024-06-06 08:38 UTC, estelle commented on files/en-us/web/html/element/input/radio/index.md
> +In the case of a radio button with the [`required`](/en-US/docs/Web/HTML/Attributes/required) attribute set or a same-named group of radio buttons in which at least one member has required set, a rad
```suggestion
In the case of a radio button with the [`required`](/en-US/docs/Web/HTML/Attributes/required) attribute set, or a same-named group of radio buttons in which at least one member has `required` set, a radio button needs to be selected for the control to be considered valid. If no radio button is checked, the [`valueMissing`](/en-US/docs/Web/API/ValidityState/valueMissing) property of a {{domxref("ValidityState")}} object will return `true` during validation, and the browser will ask the user to select an option.
```

2024-06-06 08:40 UTC, merged