Update Firefox 127 release notes for WebDriver conforming changes
mdn/content pull request #33934
Opened 2024-06-05 08:54 UTC by juliandescottes

This updates the WebDriver section of the Firefox 125 release notes for all the [note-worthy WebDriver changes in this release](https://bugzilla.mozilla.org/buglist.cgi?v1=fixed&resolution=FIXED&f2=cf_status_firefox126&query_format=advanced&o1=equals&f1=cf_status_firefox127&o2=notequals&status_whiteboard=%5Bwebdriver%3Arelnote%5D&columnlist=component%2Cresolution%2Cassigned_to%2Cshort_desc%2Cbug_type%2Cstatus_whiteboard&status_whiteboard_type=substring&v2=fixed).

2024-06-05 08:55 UTC, juliandescottes commented
cc @whimboo @lutien 

I have not listed https://bugzilla.mozilla.org/show_bug.cgi?id=1798464 because I'm not sure there are actually user visible changes?

2024-06-05 09:40 UTC, lutien approved these changes
Looks good to me, thanks!

2024-06-05 14:05 UTC, whimboo requested changes

2024-06-05 14:05 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/127/index.md
> +
Beside these entries you missed [bug 1888004](https://bugzilla.mozilla.org/show_bug.cgi?id=1888004).

2024-06-05 14:05 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/127/index.md
> +
And here we miss the entry for `permissions.setPermissions` ([bug 1875065](https://bugzilla.mozilla.org/show_bug.cgi?id=1875065)).

2024-06-05 14:57 UTC, juliandescottes commented on files/en-us/mozilla/firefox/releases/127/index.md
> +
🤦 I forgot to save my changes before pushing, thanks for noticing

2024-06-05 14:59 UTC, juliandescottes commented on files/en-us/mozilla/firefox/releases/126/index.md
> +- Improved error message for the `session.new` command when no capabilities are specified ([Firefox bug 1838152](https://bugzil.la/1838152)).
No worries that's the usual thing I forget to update as well :)

2024-06-05 14:59 UTC, juliandescottes commented on files/en-us/mozilla/firefox/releases/127/index.md
> +
Should be in now.

2024-06-05 15:19 UTC, whimboo approved these changes
Looks fine to me. Just two small nits.

2024-06-05 15:19 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/127/index.md
> +- Added the `permissions.setPermission` command which allows to update browser permissions (such as `geolocation`). The permissions module is an extension to the WebDriver BiDi specification [defined
```suggestion
- Added the `permissions.setPermission` command which allows to update browser permissions (such as `geolocation`). The permissions module is an extension to the WebDriver BiDi specification [defined in the Permissions specification](https://www.w3.org/TR/permissions/#webdriver-bidi-module-permissions) ([Firefox bug 1875065](https://bugzil.la/1875065)).
```

2024-06-05 15:19 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/127/index.md
> +- Fixed a bug where `WebDriver:GetElementText` failed to correctly capitalize text containing an underscore ([Firefox bug 1888004](https://bugzil.la/1888004)).
Maybe re-order so we have the commands listed alphabetically.

```suggestion
- Fixed a bug where `WebDriver:GetElementText` failed to correctly capitalize text containing an underscore ([Firefox bug 1888004](https://bugzil.la/1888004)).
- Fixed a bug in `WebDriver:SwitchToFrame` which could fail if the tab was in the middle of a navigation ([Firefox bug 1817820](https://bugzil.la/1817820)).
```

2024-06-06 08:33 UTC, juliandescottes commented
Thanks for the reviews! Will merge now and get started on the blog post.

2024-06-06 08:37 UTC, merged