Move touch events
mdn/content pull request #3393
Opened 2021-03-23 05:52 UTC by hamishwillee

This moves the Mozilla touch events (deprecated) out of the guide and below the standard [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events). Includes redirects.

This is part of fixing #2245

Note, this does not create any explicit links to the document because the events are largely irrelevant. However they can be found by search. One alternative would have been to archive this too.

@chrisdavidmills FYI

2021-03-23 05:58 UTC, hamishwillee commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)	/en-US/docs/Web/API/Touch_events/Mozilla_experimental_events
@chrisdavidmills This is causing an error but I can't see why: https://github.com/mdn/content/runs/2172587057?check_suite_focus=true#step:6:12

Any suggestions on how to debug?

2021-03-23 09:41 UTC, chrisdavidmills requested changes
Reviewed; couple of bits for you to look at. Cheers @hamishwillee !

2021-03-23 09:41 UTC, chrisdavidmills commented on files/en-us/web/guide/events/index.html
> +	<li>both <a href="/en-US/docs/Web/API/Touch_events">touch events</a> and the earlier <a href="/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)">Mozilla experimental touch events</a>,
The link to "Mozilla experimental touch events" needs updating to point the new location/slug you've given it.

2021-03-23 09:41 UTC, chrisdavidmills commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)	/en-US/docs/Web/API/Touch_events/Mozilla_experimental_events
Have you included a space to separate the to: and from: slugs? I think it is supposed to be a tab character. Yup, pretty flaky.

2021-03-26 00:46 UTC, hamishwillee commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)	/en-US/docs/Web/API/Touch_events/Mozilla_experimental_events
Yes, it is an exact copy of the tab in the line above. It also works locally.

2021-03-26 00:59 UTC, hamishwillee commented
@chrisdavidmills I removed the redirect to verify it is the cause of the problem. It is. However it works locally, and has a tab space, so I have no idea what could be wrong with it. We could merge without it? Otherwise we will need to escalate for debugging help

2021-03-26 09:28 UTC, chrisdavidmills commented
@peterbe can you help us here? We've got another flaky failing redirect, and we can't work out why it is the case. As @hamishwillee asserts, it works for him locally.

2021-03-26 11:29 UTC, peterbe commented
I think what's confusing about redirects is... 

1. you might think you're supposed to manually edit the `_redirects.txt` file when in fact you should be using the `yarn content add-redirect ...` CLI tool. 
2. I suspect that the same validation that runs in GitHub CI isn't running on your local server when you type `yarn start`. So you might be unnecessarily disappointed when CI breaks after all the hard work. 

We can solve both. For example, perhaps it's better to call it `_redirect.json` since that'd make it impossible to have to distinguish between a tab and spaces. Heck, I don't even know how to type a tab character because my IDE automatically transforms it to 4 spaces (or 2 depending on the file).

The other thing we could do to make things a whole lot easier is to do what Python poetry does. They have a lock file just like `yarn.lock` and `package-lock.json`. But they have a hash within the file itself. How the hash is computed isn't important but if the CLI is the only tool in the world that knows how to make the hash, you can easily and quickly check that only the CLI was allowed to edit the file. 

It was @fiji-flo who built most of the redirects tooling and it would be great to have some of your thoughts on this. 

PS. I love that this is being tracked in the [content-team-dev-papercuts Trello board](https://trello.com/b/3YgVTxvh/mdn-content-team-dev-papercuts) because then we can find out that multiple people are suffering from the same confusions.

2021-03-26 11:45 UTC, peterbe commented
I took my last comment [and turned it into an issue](https://github.com/mdn/yari/issues/3342) with a [PR](https://github.com/mdn/yari/pull/3343). It's not a great solution but I really think it can help with some of the confusion.

2021-03-26 16:25 UTC, peterbe commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental)	/en-US/docs/Web/API/Touch_events/Mozilla_experimental_events
Are you sure that's a `tab` character?
Also, can you delete this line and try:
```
yarn content add-redirect /en-US/docs/Web/Guide/Events/Touch_events_(Mozilla_experimental) /en-US/docs/Web/API/Touch_events/Mozilla_experimental_events
```

2021-03-29 00:59 UTC, hamishwillee commented
The script worked thanks @peterbe . 
The space/tab was definitely right, so I think this was something to do with their being an existing redirect from that file.

@chrisdavidmills Ready for you to merge now if you're happy.

2021-03-29 07:31 UTC, chrisdavidmills approved these changes
OK, let's do this.

2021-03-29 07:31 UTC, merged