33426 don't animate box model properties
mdn/content pull request #33933
Opened 2024-06-05 01:39 UTC by estelle

fixes #33426

2024-06-05 06:19 UTC, chrisdavidmills requested changes
Looking mostly good; few bits for you to look at.

2024-06-05 06:19 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +The second (and final) keyframe occurs at 100% (using the alias `to`). The {{cssxref("translate")}} is set to 0% and the {{cssxref("scale")}} of the element is set to 100%. This causes the header to
```suggestion
The second (and final) keyframe occurs at 100% (using the alias `to`). The {{cssxref("translate")}} property is set to 0% and the {{cssxref("scale")}} of the element is set to 100%. This causes the header to finish its animation flush against the left edge of the content area.
```

2024-06-05 06:19 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +Let's add another keyframe to the previous example's animation. Let's say we want the header size to increase as it moves from right to left for a while, then to decrease back to its original size. W
```suggestion
Let's add another keyframe to the previous example's animation. Let's say we want the header size to grow and then shrink back to its original size as it moves from right to left. While we could change the {{cssxref("font-size")}}, changing any properties that impact the box model negatively impacts performance. Instead, we scale the {{cssxref("::first-line")}} separately. That requires adding a second animation impacting only the header:
```

2024-06-05 06:19 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser that for the first and last 25% of the animation, the first line should be normal, but scale it up and back in the middle of the animation
```suggestion
This tells the browser the paragraph should be normal for the first and last 25% of the animation, but scaled up and back down again in the middle.
```

2024-06-05 06:19 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser that for the first and last 25% of the animation, the first line should be normal, but scale it up and back in the middle of the animation
BTW, when I look at the preview page, this example just looks the same as the first example.

2024-06-05 06:19 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +We start with creating the CSS for the animation. This animation will last for 3 seconds, be called "slidein", repeat 3 times, and alternate direction each time. In the {{cssxref("@keyframes")}}, the
```suggestion
We start with creating the CSS for the animation. This animation will last for 3 seconds, be called "slidein", repeat 3 times, and alternate direction each time. In the {{cssxref("@keyframes")}}, the scale and translation are manipulated along the x-axis to make the element slide across the screen.
```

2024-06-05 18:57 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle.
```suggestion
This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle. We set the spans's {{cssxref("display")}} property to `inline-block` as the `transform` properties have no effect on non-replaced {{glossary("inline-level content")}}.
```

2024-06-06 08:39 UTC, chrisdavidmills requested changes
Getting there. Few more thoughts for you ;-)

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
>  In this example the style for the {{HTMLElement("p")}} element specifies that the animation should take 3 seconds to execute from start to finish, using the {{cssxref("animation-duration")}} property
```suggestion
In this example the style for the {{HTMLElement("p")}} element specifies that the animation should take 3 seconds to execute from start to finish, using the {{cssxref("animation-duration")}} property, and that the name of the {{ cssxref("@keyframes")}} at-rule defining the keyframes for the animation sequence is "slidein".
```

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +The keyframes are defined using the {{cssxref("@keyframes")}} at-rule. In this case, we have just two keyframes. The first occurs at 0% (using the alias `from`). Here, we configure the {{cssxref("tra
```suggestion
In this case, we have just two keyframes. The first occurs at 0% (using the alias `from`). Here, we configure the {{cssxref("translate")}} property of the element to be at 100% (that is, at the far right edge of the containing element), and the {{cssxref("scale")}} of the element to be 300% (or three times its default inline size). This causes the first frame of the animation to have the header drawn off the right edge of the browser window.
```

We already say that in the previous paragraph

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +The second (and final) keyframe occurs at 100% (using the alias `to`). The {{cssxref("translate")}} property is set to 0% and the {{cssxref("scale")}} of the element is set to 100%. This causes the h
The trouble with this example is that it doesn't behave as described. The size animates, but the position doesn't.

I did some testing and got it to work as described by animating `transform: translateX(100%);` to `transform: translateX(0%);`

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +Let's add another keyframe to the previous example's animation. Let's say we want Alice's name to turn pink and grow and then shrink back to its original size and color as it moves from right to left
```suggestion
Let's add another keyframe to the previous example's animation. Let's say we want Alice's name to turn pink and grow and then shrink back to its original size and color as it moves from right to left. While we could change the {{cssxref("font-size")}}, changing any properties that impact the box model negatively impacts performance. Instead, we wrap her name in a {{htmlelement("span")}} and then scale and assign a color to that separately. That requires adding a second animation impacting only the `<span>`:
```

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle. We set the spans's {{cssxref("disp
```suggestion
This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle. We set the `<span>` element's {{cssxref("display")}} property to `inline-block` as the `transform` properties do not affect non-replaced {{glossary("inline-level content")}}.
```

2024-06-06 08:39 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle. We set the spans's {{cssxref("disp
Also, same comment about the `translate` animation on the paragraph not really doing what is described in the first example.

2024-06-07 18:59 UTC, estelle commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +The second (and final) keyframe occurs at 100% (using the alias `to`). The {{cssxref("translate")}} property is set to 0% and the {{cssxref("scale")}} of the element is set to 100%. This causes the h
ah, because i am growing the text, from a default center origin, it was growing in both directions, to 3x the viewport, so is "moving left" by 150% Fixed (in my next commit).

2024-06-07 19:33 UTC, estelle commented
@chrisdavidmills took this PR offline so I could better test it. When i grew the content using scaling, it grew in both directions, so "moved left". I translated it further to the right.

There are other issues on this page. For example, animation fill mode and play state are missing. Also, the content-visibility is a different scope and likely should be on a different page rather than this intro to the basics, but those are issues for different days.

2024-06-10 15:27 UTC, chrisdavidmills approved these changes
@estelle OK, looking much better. I've only got a few really small bts for you to consider this time; approving so as not to hold you up.

2024-06-10 15:27 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This basic example styles the {{HTMLElement("p")}} element using the {{cssxref("translate")}} and {{cssxref("scale")}} transition properties so that the text slides in from off the right edge of the
```suggestion
This basic example styles a {{HTMLElement("p")}} element using the {{cssxref("translate")}} and {{cssxref("scale")}} transition properties so that the text slides in from off the right edge of the browser window.
```

2024-06-10 15:27 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +In this case, we have just two keyframes. The first occurs at `0%` (using the alias `from`). Here, we configure the {{cssxref("translate")}} property of the element to be at `150vw` (that is, beyond
```suggestion
In this case, we have just two keyframes. The first occurs at `0%` (using the alias `from`). Here, we configure the {{cssxref("translate")}} property of the element to be at `150vw` (that is, beyond the far right edge of the containing element), and the {{cssxref("scale")}} of the element to be 200% (or two times its default inline size), causing the paragraph to be twice as wide as its `<body>` containing block. This causes the first frame of the animation to have the header drawn off the right edge of the browser window.
```

2024-06-10 15:27 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +The second (and final) keyframe occurs at `100%` (using the alias `to`). The {{cssxref("translate")}} property is set to `0%` and the {{cssxref("scale")}} of the element is set to `1` which is `100%`
```suggestion
The second keyframe occurs at `100%` (using the alias `to`). The {{cssxref("translate")}} property is set to `0%` and the {{cssxref("scale")}} of the element is set to `1`, which is `100%`. This causes the header to finish its animation in its default state, flush against the left edge of the content area.
```

2024-06-10 15:27 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back down again in the middle. We set the spans's {{cssxref("disp
```suggestion
This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back again in the middle. We set the spans's {{cssxref("display")}} property to `inline-block` as the `transform` properties do not affect non-replaced {{glossary("inline-level content")}}.
```

2024-06-10 15:27 UTC, chrisdavidmills commented on files/en-us/web/css/css_animations/using_css_animations/index.md
> +We've included the same keyframe animation, start with creating the CSS for the animation. This animation will last for 3 seconds, be called "slidein", repeat 3 times, and alternate direction each ti
```suggestion
We've included the same keyframe animation as the previous example. This animation will last 3 seconds, be called "slidein", repeat 3 times, and travel in an alternate direction each time. In the {{cssxref("@keyframes")}}, the scale and translation are manipulated along the x-axis to make the element slide across the screen.
```

2024-06-10 16:40 UTC, merged