feat: improvements on a11y glossary entries
mdn/content pull request #34095
Opened 2024-06-13 03:09 UTC by PassionPenguin

### Description

- improved links to keep consistent with other entries.

2024-06-13 23:30 UTC, hamishwillee commented on files/en-us/glossary/accessibility/index.md
> +**Accessibility** (often abbreviated to **A11y** — as in, "a", then 11 characters, and then "y") in web development means enabling as many people as possible to use websites, even when those people's
Fly-by comment (meaning I choose not to arbitrate on this), but the format `(**A11Y**)` is a very well understood way of indicating contraction/short form of a word. I find "(often abbreviated to **A11y** — as in, "a", then 11 characters, and then "y")" as verbose with no added value.

2024-06-14 03:06 UTC, PassionPenguin commented on files/en-us/glossary/accessibility/index.md
> +**Accessibility** (often abbreviated to **A11y** — as in, "a", then 11 characters, and then "y") in web development means enabling as many people as possible to use websites, even when those people's
many entries contains these abbreviations descriptions. this above was just copied from Web/Accessibility lol.

i totally agree with your point. l18n, l10n, ... this is a pretty common abbr way in computer science. maybe we can also remove Web/Accessibility's one.

<img width="779" alt="Screenshot 2024-06-14 at 11 06 02 AM" src="https://github.com/mdn/content/assets/41184947/1282a0b2-9b9c-4ce3-b334-096fdd4cecff">

2024-06-18 20:54 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +**Accessibility** (often abbreviated to **A11y** — as in, "a", then 11 characters, and then "y") in web development means enabling as many people as possible to use websites, even when those people's
I would argue that it might be a good thing to keep the verbose derivation of A11y in the Glossary for absolute beginners to web development. We can consider removing it from the [Web/Accessibility](https://developer.mozilla.org/en-US/docs/Web/Accessibility) page.

2024-06-18 21:33 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +Accessibility can be inspected or measured by tools like [Lighthouse Accessibility score](https://developer.chrome.com/docs/lighthouse/accessibility/scoring) and [Firefox Accessibility Inspector](htt
```suggestion
**Accessibility** (**A11y**) means enabling as many people as possible to use websites, even when those people's abilities are limited in some way. The most common way to achieve this is by ensuring that assistive technologies work properly to access the content. These technologies include {{glossary("screen reader", "screen readers")}}, screen magnifiers, speech recognition tools, and alternative input devices.

You can measure the accessibility of your website by using tools like [Lighthouse](https://developer.chrome.com/docs/lighthouse/accessibility/scoring) and the [Firefox Accessibility Inspector](https://firefox-source-docs.mozilla.org/devtools-user/accessibility_inspector/index.html).

Web accessibility is formally defined and discussed at the {{Glossary("W3C")}} through the {{Glossary("WAI", "Web Accessibility Initiative (WAI)")}}.
```

2024-06-18 21:39 UTC, dipikabh commented
Hi @PassionPenguin, thanks for this PR. To better understand the motivation, could you help explain the context for these changes and the reason for adding/deleting some of the links in "See also" across the three pages?

For example, I noticed that in `files/en-us/glossary/accessible_name/index.md`, links to `[ARIA roles](/en-US/docs/Web/Accessibility/ARIA/Roles)` and `[ARIA attribute](/en-US/docs/Web/Accessibility/ARIA/Attributes)` have been removed, and a link to the ARIA glossary page has been added instead.

Please check our "See also section" guidelines to see the recommended "Order of links" (that is, links to MDN pages before external links). Also check the broken links in https://pr34095.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Accessibility#see_also.

Let me know if you have any questions. We're more than happy to land improvements, but providing some context will help us understand and review them better.

2024-06-20 01:15 UTC, PassionPenguin commented on files/en-us/glossary/accessibility/index.md
> +Accessibility can be inspected or measured by tools like [Lighthouse Accessibility score](https://developer.chrome.com/docs/lighthouse/accessibility/scoring) and [Firefox Accessibility Inspector](htt
Here we have added some more detail on the usages of such tech, to help readers understand, "ah, it turns out that this is kinda accessbility implementaion!"

2024-06-20 01:15 UTC, PassionPenguin commented on files/en-us/glossary/accessibility/index.md
>  - [Accessible Rich Internet Applications (WAI-ARIA)](https://w3c.github.io/aria/)
put WAI and WAI-ARIA together, given they are in the order of

- WAI, the organization
- WAI-ARIA, the spec put forward by the org

2024-06-20 01:15 UTC, PassionPenguin commented on files/en-us/glossary/accessibility_tree/index.md
> +- [**state**](/en-US/docs/Web/Accessibility/ARIA/Attributes)
added link to attributes given aria-state is under attributes page right now

2024-06-20 01:15 UTC, PassionPenguin commented on files/en-us/glossary/accessible_name/index.md
> -- [ARIA attribute](/en-US/docs/Web/Accessibility/ARIA/Attributes)
```suggestion

- [ARIA roles](/en-US/docs/Web/Accessibility/ARIA/Roles)
- [ARIA attribute](/en-US/docs/Web/Accessibility/ARIA/Attributes)
```

2024-06-20 01:19 UTC, PassionPenguin commented on files/en-us/glossary/accessible_name/index.md
> +Assistive technologies will provide the user with the accessibility name property, which is the accessible name along with the element's role. While many elements don't need an accessible name, it's
added some description of APG's recommendation on role-name

<img width="1663" alt="Screenshot 2024-06-20 at 9 18 32 AM" src="https://github.com/mdn/content/assets/41184947/d760a00c-9774-465a-89be-3441af595215">


https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#:~:text=Accessible%20Name%20Guidance%20by%20Role,-Certain%20elements%20always&text=Indicates%20how%20necessary%20it%20is,element%20with%20the%20specified%20role.

2024-06-20 01:27 UTC, PassionPenguin commented
> Hi @PassionPenguin, thanks for this PR. To better understand the motivation, could you help explain the context for these changes and the reason for adding/deleting some of the links in "See also" across the three pages?
> 
> For example, I noticed that in `files/en-us/glossary/accessible_name/index.md`, links to `[ARIA roles](/en-US/docs/Web/Accessibility/ARIA/Roles)` and `[ARIA attribute](/en-US/docs/Web/Accessibility/ARIA/Attributes)` have been removed, and a link to the ARIA glossary page has been added instead.
> 
> Please check our "See also section" guidelines to see the recommended "Order of links" (that is, links to MDN pages before external links). Also check the broken links in https://pr34095.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/Accessibility#see_also.
> 
> Let me know if you have any questions. We're more than happy to land improvements, but providing some context will help us understand and review them better.

Thx for your kindly reviews!

a. links are reverted (while i still consider is it necessary to open up a new page on discussing too detailed computation and recommendation provided by WAI accname and WAI-APG)
b. links order. that have been discussed before, as i made several changes to make links better, though, some reviewers thought that `order of links` are just recommendation but not stereotype for writer to create better articles. in this case, accname are closely related to accessible name (as that's the spec concentrating on accessible name's implementation and computation) [ref](https://github.com/mdn/content/pull/33752#issuecomment-2134140559)
c. i have added motivations per changes! sorry for not providing them in time

2024-06-20 21:43 UTC, dipikabh requested changes
Hello @PassionPenguin, thanks for taking the time to explain the reason for adding the links. I was mostly looking for an overall context for the changes. Perhaps in the future, filling in the PR template questions could help.

I apologize for the mixed messages from reviewers about the order of links in "See also". I have a different opinion but will let it go.

I've left a few suggestions in the rest of the text. Thanks a lot for your contributions.

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +**Accessibility** (**A11y**) means enabling as many people as possible to use websites, even when those people's abilities are limited in some way. The most common way to achieve this is by ensuring
This can probably be improved further
```suggestion
**Accessibility** (**A11y**) means enabling as many people as possible to use websites, including those with limited abilities. The most common way to achieve this is by ensuring that assistive technologies work properly to access the content. These technologies include {{glossary("screen reader", "screen readers")}}, screen magnifiers, speech recognition tools, and alternative input devices.
```

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +  - {{Glossary("Accessibility name")}}
```suggestion
  - {{Glossary("Accessible description")}}
  - {{Glossary("Accessible name")}}
```

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +- [Glossary](/en-US/docs/Glossary)
I noticed a different style has been adopted here: https://github.com/mdn/content/pull/33423#discussion_r1590843688, and I understand you might have already implemented it on many pages, so I won't ask you to revert it.

However, to keep the list (and the page length) contained, I would have formatted this as (no link on Glossary):

For one term in in the list:
- Related glossary terms: <term 1 link>

For multiple terms:
- Related glossary terms: <term 1 link>, <term 2 link>

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
> +- [The W3C Web Accessibility Initiative (WAI)](https://www.w3.org/WAI/)
This can be applied to the other two pages as well
```suggestion
- [The Web Accessibility Initiative (WAI)](https://www.w3.org/WAI/) on W3C
```

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessibility/index.md
>  - [Accessible Rich Internet Applications (WAI-ARIA)](https://w3c.github.io/aria/)
This can be applied to the other two pages as well
```suggestion
- [Accessible Rich Internet Applications (WAI-ARIA)](https://w3c.github.io/aria/) specification
```

2024-06-20 21:43 UTC, dipikabh commented on files/en-us/glossary/accessible_name/index.md
> +Assistive technologies will provide the user with the accessibility name property, which is the accessible name along with the element's role. While many elements don't need an accessible name, it's
```suggestion
Assistive technologies provide users with the accessibility name property, which includes the accessible name along with the element's role. While many elements don't need an accessible name, it's necessary to provide an accessible name to override or supplement the content of elements with specified [roles](/en-US/docs/Web/Accessibility/ARIA/Roles). For example, a [`tabpanel`](/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role) is a section of content that appears after a user activates the associated element with a [`tab`](/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role) role. This role can be set on an element with no needed name, like the {{HTMLElement("div")}} element. The `tab` is the control and must have an accessible name. The `tabpanel` is the child (content section) of the `tab`. Adding `aria-labelledby` to the `tabpanel` is a best practice.
```

2024-06-20 22:14 UTC, Josh-Cena commented on files/en-us/glossary/accessibility/index.md
> +- [Glossary](/en-US/docs/Glossary)
FWIW I would have personally gone with

- <term 1 link>
- <term 2 link>

Without any extra text, per see also guidelines, but I have no feelings towards any of them.

2024-06-23 02:43 UTC, PassionPenguin commented on files/en-us/glossary/accessibility/index.md
> +- [Glossary](/en-US/docs/Glossary)
FYI, i have been translated pages under glossary folder for some time (processed about **300-350** files and PRs), and find that in most cases they are arranged in that style, and with suggestion from @bsmth, using the style of the most common case but without a link, i.e.

```markdown
- Glossary
  - a.
  - b.
```

2024-06-23 02:44 UTC, PassionPenguin commented on files/en-us/glossary/accessibility/index.md
> +  - {{Glossary("Accessibility name")}}
sorry for my typo! it's till now do I realize the difference

2024-06-26 17:21 UTC, dipikabh commented
This can be merged. Keeping it open for a short time in case we want to apply changes similar to https://github.com/mdn/content/pull/34165.

2024-06-27 09:05 UTC, bsmth commented
> This can be merged. Keeping it open for a short time in case we want to apply changes similar to #34165.

Thanks a lot! I also think the changes look good, with one comment that I think linking to `/Glossary` is not necessary, so I would just prefer not to do this:

```md
- [Glossary](/en-US/docs/Glossary)
  - {{Glossary("Term1")}}
```

And do this instead:

```md
- Glossary
  - {{Glossary("Term1")}}
  - {{Glossary("Term2")}}
```

Or indeed

```md
- {{Glossary("Term1")}}
- {{Glossary("Term2")}}
```

2024-06-27 09:05 UTC, bsmth approved these changes

2024-06-27 12:11 UTC, dipikabh commented
> linking to /Glossary is not necessary

Agree. I think we can do a batch update for all such instances (I see around 40) in a new PR, and land this one for now

2024-06-27 12:18 UTC, dipikabh approved these changes
Thanks a lot, @PassionPenguin

2024-06-27 12:18 UTC, merged