MV3 host permission install prompt
mdn/content pull request #34094
Opened 2024-06-13 01:44 UTC by rebloor

### Description

Addresses the documentation needed for [Bug 1889402](https://bugzilla.mozilla.org/show_bug.cgi?id=1889402) Grant origin permissions during install for mv3, including:

- a release note
- a note in the description of the [host permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) key

### Related issues and pull requests

Related update to the Extension Workshop Manifest V3 migration guide TBC

2024-06-20 00:24 UTC, Rob--W requested changes

2024-06-20 00:24 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/host_permissions/index.md
> +> **Note:** From Firefox 127. `host_permissions` for Manifest V3 extensions is considered a required permission and displayed to users during installation. However, if an extension update grants new
```suggestion
> **Note:** Until Firefox 126, Firefox did not include requested host permissions of Manifest Version 3 extensions in the install prompt. Starting from Firefox 127, host permissions listed in `host_permissions` and `content_scripts` do appear in the install prompt. However, if an extension update requests new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
```

On wording: "required" is not accurate.

The previous paragraph tries to emphasize that host_permissions are optional, and that is still the case: users can revoke them at any time.

The wording as written is technically true but potentially overstating the unreliability of them.

In practice:
- Chrome shows the permissions in the install prompt.
- Firefox 127 shows the permissions in the install prompt. Up until Firefox 126, host permissions were not shown in the install prompt. Starting from 127, they are. However, when a new permission is added in an update, Firefox will not show any prompt for it. Extensions who rely on the new host permissions are encouraged to use the permissions.contains API after install (runtime.onInstalled) to check whether the permission has been granted and show an onboarding page if needed.

2024-06-20 00:24 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/127/index.md
> +- [`host_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) for Manifest V3 extensions is now considered a required permission and displayed to users during insta
```suggestion
- [`host_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) for Manifest V3 extensions are now displayed to users during installation ([Firefox bug 1889402](https://bugzil.la/1889402)). However, if an extension update grants new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
```

2024-06-20 03:12 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/127/index.md
> +- [`host_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) for Manifest V3 extensions is now considered a required permission and displayed to users during insta
```suggestion
- [`host_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) for Manifest V3 extensions are now displayed to users during installation ([Firefox bug 1889402](https://bugzil.la/1889402)). However, if an extension update requests new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
```

2024-06-20 09:46 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/host_permissions/index.md
>  Users can also grant or revoke host permissions on an ad hoc basis. For example, in Firefox, users can do this using the [extensions panel](https://blog.mozilla.org/addons/2022/11/17/unified-extensio
@Rob--W is this better?
```suggestion
Users can [grant or revoke host permissions](https://support.mozilla.org/en-US/kb/extensions-button?_gl=1*bp9tzb*_ga*OTg4Nzg5MzUzLjE1NTg3MzE4Mzg.*_ga_X4N05QV93S*MTcxODg3NTc5NC40Ni4wLjE3MTg4NzU3OTQuMC4wLjA.#w_website-permissions) on an ad hoc basis. Therefore., most browsers treat `host_permissions` as optional. 

On installation, when you request permissions using this key:

- Until Firefox 126, requested host permissions weren't displayed in the install prompt. From Firefox 127, host permissions listed in `host_permissions` and `content_scripts` are displayed in the install prompt. However, if an extension update requests new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
- Chrome displays the permissions in the install prompt.
- Safari doesn't display requested host permissions in the install prompt.
```

2024-06-24 19:50 UTC, Rob--W approved these changes

2024-06-24 19:50 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/host_permissions/index.md
> +- Until Firefox 126, requested host permissions weren't displayed in the install prompt. From Firefox 127, host permissions listed in `host_permissions` and `content_scripts` are displayed in the ins
```suggestion
- Until Firefox 126, requested host permissions of Manifest Version 3 extensions weren't displayed in the install prompt. From Firefox 127, host permissions listed in `host_permissions` and `content_scripts` are displayed in the install prompt. However, if an extension update requests new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
```

Small edit to emphasize MV3. `host_permissions` is MV3-only, but the general advice here applies to any host permission, and this is the only documentation that we have on this.

2024-06-24 19:51 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/host_permissions/index.md
> +Users can [grant or revoke host permissions](https://support.mozilla.org/en-US/kb/extensions-button?_gl=1*bp9tzb*_ga*OTg4Nzg5MzUzLjE1NTg3MzE4Mzg.*_ga_X4N05QV93S*MTcxODg3NTc5NC40Ni4wLjE3MTg4NzU3OTQuMC
```suggestion
Users can [grant or revoke host permissions](https://support.mozilla.org/en-US/kb/extensions-button#w_website-permissions) on an ad hoc basis. Therefore., most browsers treat `host_permissions` as optional.
```

2024-06-25 02:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/host_permissions/index.md
> +- Until Firefox 126, requested host permissions weren't displayed in the install prompt. From Firefox 127, host permissions listed in `host_permissions` and `content_scripts` are displayed in the ins
```suggestion
- Until Firefox 126, a Manifest V3 extension's requested host permissions weren't displayed in the install prompt. From Firefox 127, host permissions listed in `host_permissions` and `content_scripts` are displayed in the install prompt. However, if an extension update requests new host permissions, these are not shown to the user. See ([Firefox bug 1893232](https://bugzil.la/1893232)).
```

2024-06-25 08:05 UTC, Rob--W approved these changes

2024-06-27 04:17 UTC, merged