feat: improvements on glossary Apple Safari
mdn/content pull request #34100
Opened 2024-06-13 05:18 UTC by PassionPenguin

### Description

- it's now supported on visionOS
- more detailed information
- linked with glossary WebKit

2024-06-14 21:01 UTC, dipikabh requested changes
Thanks, @PassionPenguin. I've added a few suggestions.

2024-06-16 18:55 UTC, Josh-Cena commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
This information is unnecessary for defining Safari and doesn't help readers understand what Safari is.

2024-06-17 00:10 UTC, PassionPenguin commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
shouldn't rendering engine been related to what a browser is? Given readers on site care about the implementation of different features supported by engines themselves

2024-06-17 03:57 UTC, Josh-Cena commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
Sure, but the history is irrelevant for a glossary entry and is more suitable for a Wikipedia-style article. The first paragraph is good enough.

2024-06-17 12:45 UTC, dipikabh commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
Agree, let's remove this info

2024-06-17 12:46 UTC, dipikabh requested changes

2024-06-17 12:46 UTC, dipikabh commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
```suggestion

```

2024-06-17 12:47 UTC, dipikabh approved these changes

2024-06-17 12:48 UTC, dipikabh commented on files/en-us/glossary/apple_safari/index.md
> +
```suggestion
```

2024-06-17 12:50 UTC, merged

2024-06-18 01:22 UTC, PassionPenguin commented on files/en-us/glossary/apple_safari/index.md
> +Safari was first introduced in 2003 on Mac OS X Panther and later on iOS in 2007, using the open source {{glossary("WebKit")}} engine, which was derived from [KHTML](https://en.wikipedia.org/wiki/KHT
well, seems to have removed far more information than history itself. now the page contains nothing but OS it supports.