CSS property update: gap
mdn/content pull request #34141
Opened 2024-06-14 03:54 UTC by estelle

* add applicable properties
* add description (with flex direction explanation)
* see also

addressed as part of CSS baseline / interop https://github.com/openwebdocs/project/issues/189 - subcomponent https://github.com/openwebdocs/project/issues/202

2024-06-18 03:43 UTC, dipikabh requested changes
Thanks for the improvements, @estelle. I've added some suggestions.

2024-06-18 03:43 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +The visible space between elements may differ from the value of the `gap` property, as the margins, padding, and distributed alignment may increase the visible separation between boxes beyond what is
```suggestion
The visible space between elements may differ from the specified `gap` value because margins, padding, and distributed alignment may increase the separation between elements beyond what is specified by `gap`.
```

2024-06-18 03:43 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +Early versions of the specification called this property `grid-gap`, and to maintain compatibility with legacy websites, browsers will still accept `grid-gap` as an alias for `gap`.
```suggestion
Early versions of the specification called this property `grid-gap`. To maintain compatibility with legacy websites, browsers still accept `grid-gap` as an alias for `gap`.
```

2024-06-18 03:43 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +- [Basic concepts of grid layout - Gutters](/en-US/docs/Web/CSS/CSS_grid_layout/Basic_concepts_of_grid_layout#gutters)
```suggestion
- [Basic concepts of grid layout: Gutters](/en-US/docs/Web/CSS/CSS_grid_layout/Basic_concepts_of_grid_layout#gutters)
```

2024-06-18 03:43 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +
While we're on this page, can we also change example headings to something like "Adding gap in flex layout" and so on?

2024-06-18 15:56 UTC, estelle commented on files/en-us/web/css/gap/index.md
> +The **`gap`** [CSS](/en-US/docs/Web/CSS) [shorthand property](/en-US/docs/Web/CSS/Shorthand_properties) sets the gaps ({{glossary("gutters")}}) between rows and columns. This property applies to [mul
I figure the "between" should be enough.

2024-06-18 17:03 UTC, estelle reviewed
@dipikabh Thank you for the review.

2024-06-18 19:10 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +  - : Specifies the width of the gutter separating the columns, {{glossary("flex item","flex items")}}, flex lines, and {{glossary("grid lines")}},.
```suggestion
  - : Specifies the width of the gutter separating columns, {{glossary("flex item","flex items")}}, flex lines, and {{glossary("grid lines")}}.
```

2024-06-18 19:10 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +  - : Specifies the width of the gutter separating the columns, flex items, flex lines, and grid lines relative to the dimension of the element.
```suggestion
  - : Specifies the width of the gutter separating columns, flex items, flex lines, and grid lines relative to the dimension of the element.
```

2024-06-18 19:10 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +This property is specified as a value for `<'row-gap'>`, followed optionally by a value for `<'column-gap'>`. If `<'column-gap'>` is omitted, it is set to the same value as `<'row-gap'>`. Both `<'row
```suggestion
This property is specified as a value for `<'row-gap'>`, followed optionally by a value for `<'column-gap'>`. If `<'column-gap'>` is omitted, it is set to the same value as `<'row-gap'>`. Both `<'row-gap'>` and `<'column-gap'>` can each be specified as a `<length>` or a `<percentage>`.
```

2024-06-18 19:10 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +This property defines gaps between columns in CSS multi-column layout, flex items and flex lines in flexible box layout, and both rows and columns in CSS grid layout.
Ah, gotcha

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +This property defines gaps between columns in [CSS multi-column layout](/en-US/docs/Web/CSS/CSS_multi-column_layout), flex items and flex lines in [CSS flexible box layout](/en-US/docs/Web/CSS/CSS_fl
```suggestion
This property defines gaps between columns in [CSS multi-column layout](/en-US/docs/Web/CSS/CSS_multicol_layout), between flex items and flex lines in [CSS flexible box layout](/en-US/docs/Web/CSS/CSS_flexible_box_layout), and between rows and columns in [CSS grid layout](/en-US/docs/Web/CSS/CSS_grid_layout).
```

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +The generated gaps create empty space the width or height of the gap's size.
how about:
```suggestion
The generated gaps create empty spaces that have the width or height of the gap's specified size.
```

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +In grid layout, the first value defines the gutter between rows and the second value sets the siz of the gutter between the column. In both grid and flex layouts, if only one value is included, that
```suggestion
In grid layout, the first value defines the gutter between rows, and the second value defines the gutter between columns. In both grid and flex layouts, if only one value is included, that value is used for both dimensions.
```

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +With flex containers, whether the first value is the gap between flex items or between flex line depends on the direction. Flex items are laid out in either rows or columns depending on the value of
```suggestion
With flex containers, whether the first value is the gap between flex items or between flex line depends on the direction. Flex items are laid out in either rows or columns depending on the value of the {{cssxref("flex-direction")}} property. For rows (`row` (the default) or `row-reverse`), the first value defines the gap between flex lines, and the second value defines the gap between items within each line. For columns (`column` or `column-reverse`), the first value defines the gap between flex items within a flex line, and the second value defines the gaps between each flex line.
```

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +In multi-column containers, the first value is the gap in between CSS columns. A dividing line can be added to the otherwise "empty space" via the {{cssxref("column-rule-style")}} property or {{cssxr
```suggestion
In multi-column containers, the first value defines the gap between columns. A dividing line can be added to the otherwise "empty space" by using the {{cssxref("column-rule-style")}} property or {{cssxref("column-rule")}} shorthand.
```

2024-06-18 19:27 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +With flex containers, whether the first value is the gap between flex items or between flex line depends on the direction. Flex items are laid out in either rows or columns depending on the value of
Yeah, this works. Thanks

2024-06-18 20:00 UTC, dipikabh requested changes
Thanks, @estelle. I've looked at the updates.

2024-06-18 20:00 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +If the value is specified as a percentage, the property resolves the value relative to the size of the element's content box. When this size is definite, the behavior is well-defined and consistent a
- It would help to explain "cyclic percentage sizes".
- It'll be even better to add a simple inline example, especially for the grid layout's case for intrinsic size and laying out contents.
- Can we say that "resolve against zero" basically means that `gap` value is ignored?
```suggestion
If the value is specified as a percentage, the property resolves the value relative to the size of the element's content box. When this size is definite, the behavior is well-defined and consistent across layout modes. As these three layout modes (multi-column, flex, and grid) treat cyclic percentage sizes differently, `gap` does so as well. In grid layout, cyclic percentage sizes resolve against zero for determining {{glossary("intrinsic size")}} contributions, but resolve against the element's content box when laying out the contents. In flex layout, cyclic percentage sizes always resolve against zero.
```

2024-06-18 20:00 UTC, dipikabh commented on files/en-us/web/css/gap/index.md
> +Early versions of the specification called this property `grid-gap`, and to maintain compatibility with legacy websites, browsers still accept `grid-gap` as an alias for `gap`.
I think placing this historical info at the beginning of the "Description" section might be better for the flow of content.

2024-06-20 18:30 UTC, estelle commented on files/en-us/web/css/gap/index.md
> +Early versions of the specification called this property `grid-gap`, and to maintain compatibility with legacy websites, browsers still accept `grid-gap` as an alias for `gap`.
I think it's better at the end because it's not important; whereas placing it at the beginning adds importance.

2024-06-20 18:42 UTC, estelle commented on files/en-us/web/css/gap/index.md
> +If the value is specified as a percentage, the property resolves the value relative to the size of the element's content box. When this size is definite, the behavior is well-defined and consistent a
```suggestion
If the value is specified as a percentage, the property resolves the value relative to the size of the element's content box. When this size is definite, the behavior is well-defined and consistent across layout modes. As these three layout modes (multi-column, flex, and grid) treat cyclic percentage sizes differently, `gap` does so as well. In grid layout, cyclic percentage sizes resolve against zero for determining {{glossary("intrinsic size")}} contributions, but resolve against the element's content box when laying out the contents.
```

2024-06-20 20:37 UTC, dipikabh approved these changes

2024-06-20 20:37 UTC, merged