feat: improvements on glossary engine
mdn/content pull request #34165
Opened 2024-06-14 14:03 UTC by PassionPenguin

### Description

better structure for entries engine(js engine) & rendering_engine.

- disambiguation
  - moved engine -> engine/javascript
  - moved rendering_engine -> engine/rendering

- better description on both

2024-06-21 14:25 UTC, dipikabh requested changes
Thanks for adding these improvements, @PassionPenguin

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/rendering/index.md
> +- [Web browser engine](https://en.wikipedia.org/wiki/Browser_engine) on Wikipedia
```suggestion
- [Browser engine](https://en.wikipedia.org/wiki/Browser_engine) on Wikipedia
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
- We could also add a link to the parent Engine page
- I know I didn't push for it in the other glossary PR yesterday, could we please start using this format:
```suggestion
- Related glossary terms: {{Glossary("Browser")}}, {{Glossary("Engine")}}
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +title: JavaScript Engine
```suggestion
title: JavaScript engine
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +**{{glossary("JavaScript")}} engines** are interpreters that parse and execute JavaScript code. Modern JavaScript engines use just-in-time compilation to convert JavaScript code into machine code tha
let's move the JavaScript link to the second occurrence in the sentence
```suggestion
**JavaScript engines** are interpreters that parse and execute {{glossary("JavaScript")}} code. Modern JavaScript engines use just-in-time (JIT) compilation to convert JavaScript code into machine code that can be executed by a computer's processor. A JavaScript engine is typically developed and used in web {{glossary("browser", "browsers")}} to run client-side code but can also be used in server-side environments like {{glossary("Node.js")}}.
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +In a browser, the JavaScript engine runs in concert with the rendering engine via the {{glossary("DOM", "Document Object Model")}} and {{glossary("WebIDL", "Web IDL")}} bindings. Some JavaScript engi
```suggestion
In a browser, the JavaScript engine operates together with the rendering engine via the {{glossary("DOM", "Document Object Model")}} and {{glossary("WebIDL", "Web IDL")}} bindings. Some JavaScript engines also execute {{glossary("WebAssembly")}} code in the same sandbox as regular JavaScript code.
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +Do not confuse JavaScript engines with {{glossary("rendering engine", "rendering engines")}}, which are also crucial part of browsers.
```suggestion
Do not confuse JavaScript engines with {{glossary("engine/rendering", "rendering engines")}}, which are also crucial parts of browsers.
```

2024-06-21 14:25 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +  - {{glossary("Rendering engine")}}
I think we can remove all these links because these terms are already linked in the text above

2024-06-23 02:34 UTC, PassionPenguin commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
1/ that's a good point
2/ currently we have mixed format in (500+ documents i translated):

```
- Glossary
  - ...
  - ...
```

or with link to glossary

```markdown
- Glossary
  - ...
  - ...
```

adapting a new format can be tricky to maintain the consistency on one hand, plus when we have entries (like those in a11y glossary pages), putting them in one line can be hard to identify each.

2024-06-23 02:37 UTC, PassionPenguin commented on files/en-us/glossary/engine/javascript/index.md
> +  - {{glossary("Rendering engine")}}
may **see also section** stands to provide a place for all references to be displayed? if so, then adding these links is much reasonable.

e.g. **references** section of a research paper or a book, the references may already be discussed in the footnotes or even in the text itself, but in the references section they are still in it

2024-06-23 02:37 UTC, PassionPenguin commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
```suggestion
- Glossary
  - {{Glossary("Engine")}}
  - {{Glossary("Browser")}}
```

2024-06-23 02:38 UTC, PassionPenguin commented on files/en-us/glossary/engine/javascript/index.md
> +  - {{glossary("Rendering engine")}}
```suggestion
  - {{glossary("Engine")}}
  - {{glossary("JavaScript")}}
  - {{glossary("WebAssembly")}}
  - {{glossary("Browser")}}
  - {{glossary("Node.js")}}
```

2024-06-26 17:01 UTC, dipikabh commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
Fair enough. What do you think about preceding the list with a phrase ending in colon, such as "Related glossary terms:". It's a nuance but instead of just saying "Glossary" might be helpful.

2024-06-26 17:05 UTC, dipikabh commented on files/en-us/glossary/engine/javascript/index.md
> +  - {{glossary("Rendering engine")}}
Good point, let's keep them then

2024-06-26 17:10 UTC, dipikabh commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
Even though making this change will introduce inconsistencies, let's try and fix in pages we're touching now and over time, we can work towards applying them on other glossary pages. LMK what you think.

2024-06-26 17:12 UTC, dipikabh commented
Apologies for the delay on getting back on this one, @PassionPenguin. There's only one outstanding comment now. I'd love to hear what you think and then we can land these changes. Thanks for your time and effort!!

2024-06-27 01:07 UTC, PassionPenguin commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
I will agree with it but still consider it kinda (somehow, but _acceptable_) unnecessary. I will advise to invite more that participate in such editions to have a discussion on it, for it will be a big change, and **open a PR to have a batch replace** for it :)

2024-06-27 12:06 UTC, dipikabh commented on files/en-us/glossary/engine/rendering/index.md
> +  - {{Glossary("Browser")}}
okay sure

2024-06-27 12:06 UTC, dipikabh approved these changes
Thanks, @PassionPenguin!

2024-06-27 12:07 UTC, merged