missed an IE mention / centering using margin
mdn/content pull request #34174
Opened 2024-06-14 23:00 UTC by estelle

2024-06-18 20:38 UTC, dipikabh requested changes

2024-06-18 20:38 UTC, dipikabh commented on files/en-us/web/css/margin/index.md
> +More commonly, though, people horizontally center element by setting {{cssxref("display")}}`: flex;` {{cssxref("justify-content")}}`: center;` on a container, which [centers its flex item](/en-US/doc
- How about the phrasing below (we can drop "to center an element horizontally" to avoid it repetition from the previous para)
- The quotes after the cssxref are adding an extra space before the ":". We can either remove the cssxref or link the entire property value pair.
```suggestion
A more common method to center an element horizontally is by setting `display: flex;` and `justify-content: center;` on a container, which [centers its flex item](/en-US/docs/Web/CSS/CSS_flexible_box_layout/Aligning_items_in_a_flex_container) children.
```

2024-06-20 18:45 UTC, estelle commented on files/en-us/web/css/margin/index.md
> +More commonly, though, people horizontally center element by setting {{cssxref("display")}}`: flex;` {{cssxref("justify-content")}}`: center;` on a container, which [centers its flex item](/en-US/doc
```suggestion
A more common method to center an element horizontally is by setting `display: flex;` and [`justify-content: center;`](/en-US/docs/Web/CSS/justify-content) on a container, which [centers its flex item](/en-US/docs/Web/CSS/CSS_flexible_box_layout/Aligning_items_in_a_flex_container) children.
```

2024-06-20 20:46 UTC, dipikabh approved these changes
Thanks

2024-06-20 20:46 UTC, merged