fix: remove duplicates
mdn/content pull request #34223
Opened 2024-06-17 11:57 UTC by tianyeeT

## Related MDN page

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/getSessionRules

## Summary

Remove `## examples` due to the possible duplicated chapter title you may see in the picture below, which is `getSession Rules()`. 

<img width="679" alt="image" src="https://github.com/mdn/content/assets/146603607/e8159443-b71b-4393-93ef-54f84103a962">

2024-06-17 22:53 UTC, hamishwillee commented
FWIW, because it wasn't clear to me from this post, the macro adds the following heading and sub-topic IFF there are any extensions. If there are no extensions then it is empty.

![image](https://github.com/mdn/content/assets/5368500/367d982f-90d7-4216-88b1-af8ee00157aa)

In most cases removing the `## Examples` heading results in complete removal of the section, because there are no extensions. However if there are extensions the heading level created by the macro is L3, and it should be L2. Worse, just because there are no extensions now, that doesn't mean there won't be in future.

My thinking is that the current behaviour is intentional - the heading is supposed to live under the `## Examples` heading, allowing the addition of other L3 examples.

If it were me, I'd modify the macro to state "None" if there are no extensions and leave the text as it is. Otherwise maybe remove both the heading AND the macro for any cases where there are no extensions.

@Rob--W Leaving for you though

2024-06-20 00:32 UTC, Rob--W commented
> My thinking is that the current behaviour is intentional - the heading is supposed to live under the `## Examples` heading, allowing the addition of other L3 examples.

Yes this was very intentional when these articles were written. The level 2 Examples appear in table of contents/navigation, and consistently exist everywhere. Sometimes there are actual inline code samples in the documentation.

When there are externally hosted code samples beyond a small inline code snippet, the level 3 example from the macro is expanded.


> If it were me, I'd modify the macro to state "None" if there are no extensions and leave the text as it is. Otherwise maybe remove both the heading AND the macro for any cases where there are no extensions.
> 
> @Rob--W Leaving for you though

Instead of None maybe something like "There are currently no sample projects for (api name) available at https://github.com/mdn/webextensions-examples ", to encourage people to contribute. (Or link the overview on MDN at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Examples )


In any case, the specific PR here should be closed since these headings should not be removed.

2024-06-20 00:34 UTC, Rob--W requested changes
As explained in the above comment, these headings should not be removed.

2024-06-24 01:25 UTC, tianyeeT commented
Thanks for the detailed explanation! @hamishwillee @Rob--W

2024-06-24 01:25 UTC, closed without merging