xyz color space
mdn/content pull request #34228
Opened 2024-06-17 18:30 UTC by estelle

clarification as to what the channels are (an impossible task, but giving people the gist.

2024-06-24 09:42 UTC, chrisdavidmills requested changes
@estelle noble attempt to try and clarify this, but I'm finding the new wording a bit confusing, TBH.

2024-06-24 09:42 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimul
```suggestion
People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimuli of the three kinds of cone cells which, in principle, describe every visible color. The `Y` channel represents the luminance of a color. The `Z` channel reflects the amount of blue in the color but is not the same as the `B` in RGB. The `X` axis is orthogonal to the Y- and Z- axis of the XYZ color 3D coordinate system.
```

2024-06-24 09:42 UTC, chrisdavidmills commented on files/en-us/glossary/color_space/index.md
> +People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimul
But even then, this doesn't really make sense. When you say "The `X` axis is orthogonal to the Y- and Z- axis the XYZ color 3-D coordinate system", what do you mean? We are currently describing XYZ, so how can X be orthogonal to Y and Z in the same system?

2024-06-24 18:02 UTC, estelle commented on files/en-us/glossary/color_space/index.md
> +People with normal vision have three kinds of cone cells that sense light, having peaks of spectral sensitivity in differing wavelengths. The CIE X, Y, and Z parameters correspond to levels of stimul
it's a 3d space, so think "cube". y and z make a flat plane, and x is at a right angle to that.

2024-06-25 10:58 UTC, chrisdavidmills approved these changes
@estelle, ah, I get this now. Thanks for the clarification.

2024-06-25 10:59 UTC, merged