fix(css): simplify unlayered style description
mdn/content pull request #34345
Opened 2024-06-22 11:33 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/18888

Current prose beat around bush and ends explaining implementation. The PR simplifies the statement as per the request.

2024-06-22 13:36 UTC, Josh-Cena commented on files/en-us/web/css/@layer/layer_cascade.png
Can we make this diagram in SVG? If you have the source code to generate it, we can even  add it to https://github.com/mdn/shared-assets, so we can maintain it.

2024-06-22 13:57 UTC, OnkarRuikar commented on files/en-us/web/css/@layer/layer_cascade.png
It is a screenshot of a rendered canvas. Unfortunately I don't know how to convert it to SVG. Is there any AI that converts scalar to vector?

The image is being referenced only once in the repo(this doc) so why put it in shared-assets? What is the criteria for adding to shared-assets repo?

2024-06-22 14:04 UTC, Josh-Cena commented on files/en-us/web/css/@layer/layer_cascade.png
> It is a screenshot of a rendered canvas.

Is there any way to edit this image afterwards? For example, if it's a rendered canvas, do you have the code that painted it? It's still better if you can try to draw the image in SVG, but no worries if not, maybe @bsmth can also redo it.

> What is the criteria for adding to shared-assets repo?

It's mainly just a way to move assets out of content, with the intention to reuse it. It also lets us commit the source code that generated the image so we can maintain it.

2024-06-23 01:43 UTC, OnkarRuikar commented on files/en-us/web/css/@layer/layer_cascade.png
> Is there any way to edit this image afterwards? For example, if it's a rendered canvas, do you have the code that painted it?

I don't have the code. I edited it using Gimp.

Is there a long term target to convert all illustrations to SVG?

2024-06-23 02:22 UTC, Josh-Cena commented on files/en-us/web/css/@layer/layer_cascade.png
Yeah. https://github.com/mdn/content/labels/reduce%20binary%20assets

2024-06-24 09:12 UTC, chrisdavidmills approved these changes
@OnkarRuikar looking pretty good to me. Approving, pending the diagram update and the paragraph update I suggested.

2024-06-24 09:12 UTC, chrisdavidmills commented on files/en-us/web/css/@layer/index.md
> +Here declaration order matters. First delcared layer gets lowest priority and the last layer gets highets priority. But priority is reversed when [`!important`](/en-US/docs/Web/CSS/important) flag is
```suggestion
The declaration order matters. The first declared layer gets the lowest priority and the last declared layer gets the highest priority. However, the priority is reversed when the [`!important`](/en-US/docs/Web/CSS/important) flag is used.
```

2024-06-24 09:32 UTC, bsmth commented on files/en-us/web/css/@layer/layer_cascade.png
Thanks for tagging me. Diagrams such as these are the exact candidates I'm pushing to keep source files for in shared assets repo. If GIMP can't export as SVG, you can recreate it on draw.io / app.diagrams.net. I can also do it for you if you're stuck.

2024-06-24 15:42 UTC, bsmth requested changes
We should move the png into the shared assets repo as an SVG, if you need some help, let me know!

2024-06-24 15:49 UTC, bsmth commented
> We should move the png into the shared assets repo as an SVG, if you need some help, let me know!

Just discussed in the community call, I can recreate the diagram for you. Hold tight for a PR in the shared-assets repo.

2024-06-25 07:43 UTC, bsmth commented on files/en-us/web/css/@layer/index.md
> +![Diagram showing cascade layer priorities](layer_cascade.png)
```suggestion
![Diagram showing cascade layer priorities](https://mdn.github.io/shared-assets/images/diagrams/css/at-rules/layer-cascade.svg)
```

2024-06-25 08:03 UTC, OnkarRuikar commented on files/en-us/web/css/@layer/index.md
> +![Diagram showing cascade layer priorities](layer_cascade.png)
@bsmth The new URL is giving the following error in page preview:
> Refused to load the image 'https://mdn.github.io/shared-assets/images/diagrams/css/at-rules/layer-cascade.svg' because it violates the following Content Security Policy directive: "img-src 'self' *.githubusercontent.com *.googleusercontent.com *.gravatar.com mozillausercontent.com firefoxusercontent.com profile.stage.mozaws.net profile.accounts.firefox.com media.prod.mdn.mozit.cloud media.stage.mdn.mozit.cloud interactive-examples.mdn.mozilla.net interactive-examples.mdn.allizom.net wikipedia.org www.google-analytics.com www.gstatic.com".

Will it work on live site?

2024-06-25 08:25 UTC, bsmth commented on files/en-us/web/css/@layer/index.md
> +![Diagram showing cascade layer priorities](layer_cascade.png)
This is a known bug, CSP rules have to be updated on dev (preview) env. They have been added in prod via Yari. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview for example.

2024-06-25 08:28 UTC, bsmth approved these changes
LGTM thank you!

2024-06-25 08:29 UTC, merged