Correct syntax rules for <ident>
mdn/content pull request #34340
Opened 2024-06-22 03:34 UTC by wbamberg

This is supposed to be the first bit of a fix for https://github.com/mdn/content/issues/28752. I want to have somewhere to document the rules for CSS identifiers, and I'm hoping https://developer.mozilla.org/en-US/docs/Web/CSS/ident is a reasonable place.

I _believe_ the description there is wrong, in particular that it says you can't have unescaped non-ASCII Unicode characters, which I think you can.

So this is basically part 1 of https://github.com/mdn/content/issues/28752#issuecomment-1707035191, and next steps would be parts 2, 3, and 4. But let's get the definition clear and in the right place first.

One thing I'm uncertain about - I follow the spec in saying that (for example) `&123` can be escaped like `\&123`, but actually, the string (and the output of `CSS.escape()`) is `\\&123` I guess because you have to escape the backslash itself in the string. We should probably say that because it's quite confusing.

2024-06-22 05:59 UTC, wbamberg commented on files/en-us/web/css/ident/index.md
> +- any ASCII character `A-Z` and `a-z`
```suggestion
- any ASCII character in the ranges `A-Z` and `a-z`
```

2024-06-22 12:55 UTC, Josh-Cena commented
> but actually, the string (and the output of `CSS.escape()`) is `\\&123`

That's just how the console displays it. `CSS.escape("&123").length` is `5` and ``CSS.escape("&123") === String.raw`\&123` ``

2024-06-22 16:03 UTC, wbamberg commented
> > but actually, the string (and the output of `CSS.escape()`) is `\\&123`
> 
> That's just how the console displays it. `CSS.escape("&123").length` is `5` and `` CSS.escape("&123") === String.raw`\&123` ``. The reason as you said is because you are writing CSS in a JS string literal, so you have to write `\\` to represent a single CSS backslash character. If you are writing this ident purely in CSS you would just need to write `\&123`.

Yes, but since you also have to do this when you use the escaped version in JS, it might be worth mentioning it here. But maybe it's better to mention it in the querySelector pages.

2024-06-22 16:10 UTC, Josh-Cena commented
Yeah, my thought. This page is for how to author CSS.

2024-07-02 19:00 UTC, dipikabh requested changes
The updates are looking good overall, @wbamberg. Thanks for adding the section!
Most of my suggestions are about trying to see if we can improve the clarity even further.

2024-07-02 19:02 UTC, dipikabh commented
> Yes, but since you also have to do this when you use the escaped version in JS, it might be worth mentioning it here. But maybe it's better to mention it in the querySelector pages.

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#escaping_special_characters mentions the need to escape twice

2024-07-02 21:44 UTC, wbamberg commented on files/en-us/web/css/ident/index.md
> +Additionally, an identifier must not start with an unescaped digit, and must not start with an unescaped hyphen followed by an unescaped digit.
> Couple of thoughts here:
> 
>     * What we're trying to do in the list above is say what characters can be included in the identifier and in this "Additionally" para say which ones can't be the first character in the identifier. So maybe we use "However" instead of "Additionally"?
> 

The way I see this, the rules after "additionally" are extra restrictions on top of the ones already listed, which is why I used "additionally". To me "however" would imply opposition to or a loosening of the previous restrictions, like "However, you can use a digit if preceded by a ...".

>     * Another alternative could be to skip this "Additionally" para altogether and convey this info through the list itself, like so:
> 
> 
> ```
> - any decimal digit (`0` to `9`), but not as the first character
> - a hyphen (`-`), but not as the first character if followed by a digit
> ```
> 

I think these are harder to understand than what's there now.

> WDYT?

2024-07-03 12:35 UTC, dipikabh approved these changes
Thanks, the updates are looking good. There's just one nit. Leaving a +1.

2024-07-03 12:35 UTC, dipikabh commented on files/en-us/web/css/ident/index.md
> +Escaping a character means representing it in a way that changes the way it is interpreted by a software system. In CSS, you can escape a character by adding a backslash (`\`) in front of the charact
to avoid repetition of "way"
```suggestion
Escaping a character means representing it in a way that changes how it is interpreted by a software system. In CSS, you can escape a character by adding a backslash (`\`) in front of the character. Any character, except the hexadecimal digits `0-9`, `a-f`, and `A-F`, can be escaped in this way. For example, `&` can be escaped as `\&`.
```

2024-07-03 17:41 UTC, merged