fix(css): update color-mix() page
mdn/content pull request #34371
Opened 2024-06-24 07:11 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/34351

The PR:
- elaborates `<color-space>` as part of `<color-interpolation-method>`
- use `oklab` instead of `srgb` in first example
-

2024-07-01 15:17 UTC, chrisdavidmills requested changes
Hi @OnkarRuikar, and thanks for tackling this update. I've got a few comments for you to consider.

2024-07-01 15:17 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/color-mix/index.md
> +The following live demo of the `color-mix()` function mixes two colors, `color-one` and `color-two`. You can change colors by clicking on them. You can also change the percentage and color space.
```suggestion
The following live demo mixes two colors, `color-one` and `color-two`, using the `color-mix()` function. The source colors are shown on the outside, and the mixed color is shown in the middle. You can change colors by clicking on them and choosing a new color using the resulting color picker. You can also change the percentage of each color included in the mix using the sliders, and the color space using the drop-down menu.
```

2024-07-01 15:17 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/color-mix/index.md
> +The following live demo of the `color-mix()` function mixes two colors, `color-one` and `color-two`. You can change colors by clicking on them. You can also change the percentage and color space.
I'm not going to block this PR on the live demo, but there are a couple of things that should be considered at some point:

1. The color pickers are completely inaccessible using the keyboard. Using native color picker inputs would help with this issue.
2. The output `color-mix()` line jumps between 1 and 2 lines of code, which makes the UI awkward to use. It would be good to put the output code line in a fixed-height box that can handle one or two lines, so that the UI doesn't jump around.

2024-07-01 15:17 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/color-mix/index.md
> +  background-color: color-mix(in oklab, #34c9eb 0%, white);
I'm wondering whether this example would be a bit more striking if you used a darker color, like dark blue or red? It seems bit wishy-washy right now.

2024-07-26 05:54 UTC, OnkarRuikar commented on files/en-us/web/css/color_value/color-mix/index.md
>  - `color1`, `color2`
`1` and `2` don't go well with value types. Using simply `<percentage>` and in prose mentioning there are two percentages.

2024-07-26 08:30 UTC, OnkarRuikar commented on files/en-us/web/css/color_value/color-mix/index.md
> +The following live demo of the `color-mix()` function mixes two colors, `color-one` and `color-two`. You can change colors by clicking on them. You can also change the percentage and color space.
Here is [the PR](https://github.com/mdn/css-examples/pull/193) to fix these issues in the css-examples repo.

2024-08-02 12:25 UTC, chrisdavidmills commented on files/en-us/web/css/color_value/color-mix/index.md
>  - `color1`, `color2`
Cool, looking good!

2024-08-02 12:30 UTC, chrisdavidmills reviewed
@OnkarRuikar looking great! I made a small grammar change, and I think it is now ready to merge.

2024-08-02 12:30 UTC, chrisdavidmills approved these changes
Ooops, approving.

2024-08-02 12:30 UTC, merged