feat(HTTP): Refresh 2XX response pages
mdn/content pull request #34422
Opened 2024-06-26 11:28 UTC by bsmth

### Description

This PR refreshes the HTTP status response code pages.

### Motivation

Keeping content up-to-date and useful.

__additions:__

- Examples in HTTP format
- See also links to HTTP status codes page
- Blog post links for more obscure codes
- Some usage notes where applicable
- Unify formatting with current conventions (e.g., `## Example` to `## Examples` with subsections)

2024-06-26 11:36 UTC, pransh15 commented
Well done on the examples! 👏

2024-06-26 11:38 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +    "feedNumber": "default"
```suggestion
    "feed": "default"
```

2024-06-26 11:39 UTC, bsmth commented on files/en-us/web/http/status/202/index.md
> +### Begin processing job
```suggestion
### Begin automated task
```

2024-07-03 14:38 UTC, bsmth commented on files/en-us/web/http/status/201/index.md
> +HTTP/1.1 201 CREATED
```suggestion
HTTP/1.1 201 Created
```

2024-07-09 03:20 UTC, dipikabh requested changes
Review for the 200 page

2024-07-09 03:20 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +<!doctype html>
should we add this comment:
```suggestion
<!doctype html>
<!-- HTML content will follow here -->
```

2024-07-09 03:20 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +Making a successful GET request to `https://example.com` returns the following response with the HTML contained in the message body:
also then, we can present this as the example scenario
```suggestion
In this example, a successful GET request to `https://example.com` returns a `200 OK` response. The response includes ...
```
should we say includes HTTP headers (as shown here), which is followed by the message body?

2024-07-09 03:20 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +An example response could look like this:
```suggestion
In this example, a successful response with a `200 OK` status could look like this:
```

2024-07-09 03:20 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +- {{Glossary("Idempotent")}} Glossary entry
how about
```suggestion
- Glossary: {{Glossary("Idempotent")}}
```

2024-07-10 18:29 UTC, dipikabh requested changes
Feedback for 201 page

2024-07-10 18:29 UTC, dipikabh commented on files/en-us/web/http/status/201/index.md
> +The new resource or a description and link to the new resource is created before the response is returned and the newly-created items are returned in the body of the message, located at either the UR
- same comment about first saying what it is and moving "it is part of" to the very end
- could we also move the "POST request" bit earlier in the intro?
- WDYT about the following flow:
```suggestion
The HTTP **`201 Created`** status response code indicates that the HTTP request has led to the creation of a resource. This status code is commonly sent as the result of a {{HTTPMethod("POST")}} request.
The new resource or a description and link to the new resource is created before the response is returned. The newly-created items are returned in the body of the message, located at either the URL of the request or the URL in the value of the {{HTTPHeader("Location")}} header. This status code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses).
```

2024-07-10 18:29 UTC, dipikabh commented on files/en-us/web/http/status/201/index.md
> +This status code is commonly sent as the result of a {{HTTPMethod("POST")}} request.
can be removed if moving to previous para

2024-07-10 18:29 UTC, dipikabh commented on files/en-us/web/http/status/201/index.md
> +### Response indicating new user created
```suggestion
### Receiving a response indicating user creation
```

2024-07-10 18:29 UTC, dipikabh commented on files/en-us/web/http/status/201/index.md
> +Assuming a REST API exists with an endpoint to manage users at `http://example.com/users` and a `POST` request with the following body will create a user:
Again, rephrasing to build up the scenario
```suggestion
Let's assume there's a REST API for managing users with an endpoint at `http://example.com/users`. In this example, we send a `POST` request with the following body to create a user:
```

2024-07-10 18:29 UTC, dipikabh commented on files/en-us/web/http/status/201/index.md
> +A generic 201 response may look like this:
```suggestion
After successful user creation, the `201 Created` response will look like this:
```

2024-07-11 18:13 UTC, dipikabh requested changes
Review for 202 page

2024-07-16 15:18 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
Good idea, what about this sentence order:

```
what it is. (200 means the request was successful)
what class it's in. (2XX range)
notes (if it's cacheable / other)
```

I want to bring the class (category) pretty high up in page information.

2024-07-16 15:19 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The meaning of success depends on the HTTP request method used:
Yeah the latter "The interpretation of a request being 'successful' depends on.."

2024-07-16 15:20 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +<!doctype html>
Yeah let's add

2024-07-16 15:24 UTC, bsmth commented on files/en-us/web/http/status/201/index.md
> +The new resource or a description and link to the new resource is created before the response is returned and the newly-created items are returned in the body of the message, located at either the UR
OK actually at the end of the intro might be better (we currently don't link to the classes at all)

2024-07-17 15:27 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +- {{HTTPMethod("GET")}}: The resource has been retrieved and is included in the response body.
I've gone with some other wording to keep it brief, do you want to have another look?

2024-07-17 15:27 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +- {{HTTPMethod("TRACE")}}: The response has a message body with the request message as received by the server.
Might want to check again after some rewording

2024-07-17 15:28 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The successful result of a {{HTTPMethod("PUT")}} or a {{HTTPMethod("DELETE")}} is often not `200 OK`, but {{HTTPStatus("204")}} `No Content`, or {{HTTPStatus("201")}} `Created` if the resource is upl
I think it's okay to have it separate as we're talking about methods you might expect a 200 for, but may respond with something else.

2024-07-17 15:28 UTC, bsmth commented on files/en-us/web/http/status/202/index.md
> +The HTTP **`202 Accepted`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has been acc
Have moved the "is part of" bit to the end in all pages

2024-07-18 14:39 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
This pattern looks good, thanks!

2024-07-18 14:59 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
Sorry, coming back to this one. My problem is with the placement of "following". Ideally, we'd want to say "following methods" because that's what the list contains.
How about rephrasing to something like:
```suggestion
The meaning of a `200 OK`, indicating a successful request, depends on the following HTTP request methods:
```

2024-07-18 14:59 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +- {{HTTPMethod("GET")}}: The resource has been retrieved and is included in the response body.
The rewording looks much better. Thanks! Adding a few nits

2024-07-18 15:06 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +- {{HTTPMethod("TRACE")}}: The response has a message body containing the request as received by the server.
```suggestion
- {{HTTPMethod("GET")}}: A resource was retrieved by the server and included in the response body.
- {{HTTPMethod("POST")}}: An action succeeded; the response has a message body describing the result.
- {{HTTPMethod("HEAD")}}: Identical to `GET`, except there is no message body.
- {{HTTPMethod("TRACE")}}: The response has a message body containing the request as received by the server.
```

2024-07-18 15:06 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +Although possible, a successful {{HTTPMethod("PUT")}} or {{HTTPMethod("DELETE")}} request often does not result in a `200 OK` response.
```suggestion
Although possible, successful {{HTTPMethod("PUT")}} or {{HTTPMethod("DELETE")}} requests often do not result in a `200 OK` response.
```

2024-07-18 15:06 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +The successful result of a {{HTTPMethod("PUT")}} or a {{HTTPMethod("DELETE")}} is often not `200 OK`, but {{HTTPStatus("204")}} `No Content`, or {{HTTPStatus("201")}} `Created` if the resource is upl
The new write up looks good

2024-07-18 15:21 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
Yeah I see what you mean, I'm coming from the perspective that a 200 looks different depending on the request method. So 'success' is different each time and the response has a different format depending on the request method.

2024-07-18 15:22 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
Your suggestion is good, we should add that the format (whether there's a body) is different, also.

2024-07-18 15:24 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +- {{HTTPMethod("GET")}}: The resource has been retrieved and is included in the response body.
Cool ty

2024-07-18 15:25 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +Although possible, a successful {{HTTPMethod("PUT")}} or {{HTTPMethod("DELETE")}} request often does not result in a `200 OK` response.
good

2024-07-18 15:29 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
Alternatives:

* "A `200 OK` has a different meaning and format depending on the request method:"
* "The meaning of 'successful', and the format of the 200 responses is different depending on the request method that the server is responding to:"

2024-07-18 18:46 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
1. The issue is that "is part of" is breaking the flow of info about the response code:

- "The HTTP 200 OK status response code indicates that a request has succeeded. It is part of the 200-299 class of successful responses. A 200 OK response is cacheable by default."

vs

- "The HTTP 200 OK status response code indicates that a request has succeeded. A 200 OK response is cacheable by default. It is part of the 200-299 class of successful responses."

I personally prefer the second version because it presents information in the order of first describing what it is, followed by any other essential info, and then additional useful info. Though important, I regard the category info secondary and to be mentioned only after the core details.

2. Similarly, in cases like [202](https://pr34422.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Status/202), the current order of sentences is breaking the flow of information.

- "The HTTP 202 Accepted status response code indicates that a request has been accepted for processing, but processing has not been completed or may not have started. It is part of the 200-299 class of [successful responses](https://pr34422.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Status#successful_responses).

    The actual processing of the request is not guaranteed; a task or action may fail or be disallowed when a server tries to process it. A 202 response is non-committal, meaning there is no way to later send an asynchronous HTTP response to indicate the outcome of the processing. This response code is typically used when the request is handled by another process or server, or when requests are processed in batches."

- I'd reorganize it as:

"The HTTP 202 Accepted status response code indicates that a request has been accepted for processing, but processing has not been completed or may not have started. The actual processing of the request is not guaranteed; a task or action may fail or be disallowed when a server tries to process it. A 202 response is non-committal, meaning there is no way to later send an asynchronous HTTP response to indicate the outcome of the processing. This response code is typically used when the request is handled by another process or server, or when requests are processed in batches. It is part of the 200-299 class of successful responses."

OR if we could add a "Description" section, we could move the addiitonal info there and keep the intro short, so:

```
The HTTP 202 Accepted status response code indicates that a request has been accepted
for processing, but processing has not been completed or may not have started. This
response code is typically used when the request is handled by another process or server,
or when requests are processed in batches. It is part of the 200-299 class of successful responses.

## Description

The actual processing of the request is not guaranteed; a task or action may fail or be
disallowed when a server tries to process it. A 202 response is non-committal, meaning there
is no way to later send an asynchronous HTTP response to indicate the outcome of the processing. 
```

LMK what you think. If you're not too keen with this suggestion, it might be better to revert to your original sentence structure, that is,  "The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates..." because it doesnt break the flow; I suggested the change so we could present more important info upfront.

2024-07-18 18:47 UTC, dipikabh commented on files/en-us/web/http/status/202/index.md
> +The HTTP **`202 Accepted`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has been acc
I added a longish response in https://github.com/mdn/content/pull/34422#discussion_r1683326208 :)

2024-07-18 19:05 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
Gotcha, going with your previous version :) with a tweak:

```suggestion
A `200 OK` response has a different meaning and format depending on the HTTP request method. Here's how they vary for different methods:
```

2024-07-18 23:09 UTC, dipikabh requested changes
For 204 and 205

2024-07-18 23:09 UTC, dipikabh commented on files/en-us/web/http/status/205/index.md
> +It's assumed that the client supports resetting the content for entering data on `205` responses via JavaScript, as this is not handled natively by browsers:
This one is not specific to the example and applies generally to 205. Could we add it as a note to the main content before "Status" section?

```suggestion
> **Note:** It's assumed that the client supports resetting the content after a `205` response. This is typically done via JavaScript, as resetting content after a `205` is not handled natively by browsers.
```

2024-07-18 23:09 UTC, dipikabh commented on files/en-us/web/http/status/205/index.md
> +Browser behavior differs if this response erroneously includes a body on persistent connections.
```suggestion
Browser behaviors differ if this response erroneously includes a body on persistent connections.
```

2024-07-18 23:10 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +In this example, a successful GET request to `https://example.com` returns a `200 OK` response.
```suggestion
### Receiving a `200 OK` for a `GET` request

In this example, a successful `GET` request to `https://example.com` returns a `200 OK` response.
```

2024-07-19 02:14 UTC, dipikabh requested changes
For 206 and 207

2024-07-19 02:14 UTC, dipikabh commented on files/en-us/web/http/status/207/index.md
>  > Browsers accessing web pages will never encounter this status code.
- I think we can move this note to after the content paras, before the "Status" section. Moving the note to a later position would help readers to first understand the concept of the status code and then better relate with the context of the info in the note.
- We can also add more context in the main content to establish relation between 207 and WebDAV, so then the note will make more sense.
- The flow of info in the note itself can be improved:
```suggestion
> **Note:** Browsers accessing web pages will never encounter this status code. The ability to return a _collection of resources_ is part of the {{Glossary("WebDAV")}} protocol and is only encountered by web applications that access a WebDAV server.
> 
```

2024-07-19 02:14 UTC, dipikabh commented on files/en-us/web/http/status/207/index.md
> +The HTTP **`207 Multi-Status`** status response code indicates that there might be a mixture of responses.
we can add the webdav context here:
```suggestion
The HTTP **`207 Multi-Status`** status response code indicates a mixture of responses. This response is used exclusively in the context of Web Distributed Authoring and Versioning ({{Glossary("WebDAV")}}).
```

2024-07-19 02:14 UTC, dipikabh commented on files/en-us/web/http/status/207/index.md
> +### 207 Multi-Status response
how about
```suggestion
### Receiving a `207` response in a WebDAV context
```

2024-07-19 02:14 UTC, dipikabh commented on files/en-us/web/http/status/207/index.md
We can add a single line here that is a sample `207 Multi-Status` response from a WebDAV server. And anything else that can be called out/highlighted from the response.

2024-07-19 08:33 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +A `200 OK` has the following meaning and format in response to these request methods:
great ty

2024-07-19 08:35 UTC, bsmth commented on files/en-us/web/http/status/205/index.md
> +See [204 No Content](/en-US/docs/Web/HTTP/Status/204) for more details.
good idea

2024-07-19 08:51 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
Thanks, Dipika!

>The issue is that "is part of" is breaking the flow of info about the response code

I agree, we're doing some hard work on some pages including the sentence as a standalone in different spots and it is a stopper in some cases. What we do on API pages is also a good convention:

```md
The **`SyncEvent`** interface of the {{domxref("Background Synchronization API")}} represents a sync action that is dispatched on the {{domxref("ServiceWorkerGlobalScope")}} of a ServiceWorker.
```

So we have:

>A **`this feature`** of the [parent or category](/path/to/parent) thing represents a ...

So we could move the original suggestion into the first sentence like:

* The HTTP **`200 OK`** [successful response](/en-US/docs/Web/HTTP/Status#successful_responses) status code indicates...

or

* The **`200 OK`** HTTP response is a [successful response status code](/en-US/docs/Web/HTTP/Status#successful_responses) that indicates...

Then we have a link to response class right away. We don't need to mention the number range, I guess it's too much, and that will be apparent when the reader clicks the "successful response" bit.

I think in general a Description section is not necessary as the pages are so short, the first two paras are the description, really, so we can optimize those instead! What do you reckon?

2024-07-19 13:00 UTC, dipikabh requested changes
For 208 and 226

2024-07-19 13:00 UTC, dipikabh commented on files/en-us/web/http/status/226/index.md
> +Given support for delta encodings, the server responds with the diff since a version with the ETag `abcd123`.
this sentence seems incomplete
```suggestion
Assuming the server supports delta encodings, it responds with the diff since the version with the ETag `abcd123`.
```

2024-07-19 13:59 UTC, bsmth commented on files/en-us/web/http/status/206/index.md
> +The HTTP **`206 Partial Content`** status response code is sent in response to a [range request](/en-US/docs/Web/HTTP/Range_requests).
maybe pending the successful request open question

2024-07-19 14:19 UTC, bsmth commented on files/en-us/web/http/status/203/index.md
> +The purpose of this status code is to allow transforming proxies to notify clients when changes have been applied to successful responses, since this may impact decisions regarding the content later.
Pending other discussion

2024-07-19 14:19 UTC, bsmth commented on files/en-us/web/http/status/206/index.md
>  ```http
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:19 UTC, bsmth commented on files/en-us/web/http/status/207/index.md
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:19 UTC, bsmth commented on files/en-us/web/http/status/208/index.md
> +The HTTP **`208 Already Reported`** status response code is used in a {{HTTPStatus("207")}} (`207 Multi-Status`) response to save space and avoid conflicts.
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:19 UTC, bsmth commented on files/en-us/web/http/status/208/index.md
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:20 UTC, bsmth commented on files/en-us/web/http/status/207/index.md
>  > Browsers accessing web pages will never encounter this status code.
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:20 UTC, bsmth commented on files/en-us/web/http/status/208/index.md
>  > Browsers accessing web pages will never encounter this status code.
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:22 UTC, bsmth commented on files/en-us/web/http/status/208/index.md
>  Responses for all other bindings will report with this `208` status code, so no conflicts are created and the response stays shorter.
Not super familiar with WebDAV terminology so I would just skip this one :)

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/208/index.md
> +### In a 207 Multi-Status response
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/226/index.md
> +IM stands for _instance manipulations_, the term used to describe an algorithm generating a _delta_.
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/226/index.md
> +The server's HTTP response uses the `226` status code, an `IM:` header that describes the diff algorithm used, and may include a `Delta-Base:` header with the {{HTTPHeader("ETag")}} matching the base
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/226/index.md
> +> Poor support for HTTP delta encodings means there are few implementations, and instead most systems rely solely on [compression methods](/en-US/docs/Web/HTTP/Compression) to reduce bandwidth, altho
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/226/index.md
> +Given support for delta encodings, the server responds with the diff since a version with the ETag `abcd123`.
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:23 UTC, bsmth commented on files/en-us/web/http/status/226/index.md
> +### Response using vcdiff algorithm
done in ab929ff3e93203ef8107ddb50e930406ab61d9b9

2024-07-19 14:25 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
What do you think about this: https://github.com/mdn/content/compare/main...bsmth:content:http-3xx-responses

2024-07-23 09:41 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
Do you want to check https://github.com/mdn/content/pull/34422/commits/f5c2080fb13ae8b7335cc3c05d864776645f934f? I think it's a good compromise for linking to the category while staying out of the way of the vital information, what do you think?

2024-07-29 23:45 UTC, dipikabh commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
"The HTTP 200 OK [successful response](https://github.com/en-US/docs/Web/HTTP/Status#successful_responses) status code indicates..." is indeed a very neat solution, providing all the info whilst not breaking the flow! Let's go with this format. Thank you!!

> I think in general a Description section is not necessary as the pages are so short, the first two paras are the description, really, so we can optimize those instead! What do you reckon?
I agree, no separate section required if it's just two short paras but also depends on the type of content; I would consider moving additional content to a separate "Description" section if the content starts explaining the mechanics of processing and if there are additional caveats (notes).

2024-07-29 23:50 UTC, dipikabh approved these changes
Thanks for all the updates, @bsmth!
This can land after the few remaining changes are applied.

2024-08-05 15:52 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The HTTP **`200 OK`** status response code is part of the `200`-`299` class of [successful responses](/en-US/docs/Web/HTTP/Status#successful_responses) and indicates that a request has succeeded.
Super, thank you!

2024-08-05 16:21 UTC, bsmth commented on files/en-us/web/http/status/205/index.md
> +> **Note:** It's assumed that the client supports resetting the content after a `205` response. This is typically done via JavaScript, as resetting content after a `205` is not handled natively by br
super, done in https://github.com/mdn/content/pull/34422/commits/446dfb251ab64931d2ab857eab6d52d19e3a0ae3

2024-08-05 16:22 UTC, bsmth commented on files/en-us/web/http/status/200/index.md
> +The response includes representation headers and a message body with the HTML resource:
```suggestion
The response includes representation headers and a message body with the HTML content:
```

2024-08-06 08:23 UTC, bsmth commented
Thanks Dipika, I forgot some minor things and fixed in https://github.com/mdn/content/pull/34422/commits/bc2e006761cb0aeceeede311c245209ba03367df but I will merge shortly!

2024-08-06 08:25 UTC, merged