Format and clean up MathML
mdn/content pull request #34430
Opened 2024-06-26 14:10 UTC by pepelsbey

### Description

- Block-level MathML is formatted and marked with `display="block"`\*
- Inline-level MathML is properly inlined
- Old `xmlns` attributes are removed
- Non-typical formatting is cleaned up
- Prettied also took care of some files I touched

\* this will help with styling, but that’s another task.

### Motivation

MathML clean-up project.

2024-06-26 14:33 UTC, Josh-Cena commented
Formatting inline MathML makes the source much longer without immediate benefits, IMO. No one is going to edit it by hand; you use a tool like TeXZilla, feed it the TeX source, and paste the output here. It's like an opaque blob of text. The only sensible cleanup that should be done is to recommend one official MathML generator and consistently use the output of that.

2024-06-27 04:11 UTC, fred-wang approved these changes
Thanks for doing this!

rubber-stamping=me

2024-06-27 12:11 UTC, pepelsbey commented
> Formatting inline MathML makes the source much longer without immediate benefits, IMO. No one is going to edit it by hand.

Thanks! We'll discuss it further with the content team. Personally, I prefer to have markup expanded. This way, I can spot a mistype or adjust the rendering.

For some people, SVG looks like a binary. For others, myself included, it's just markup, like HTML. The same goes for MathML.

2024-06-27 12:41 UTC, Josh-Cena commented
For SVG, there's no better way to hand-adjust the content than to manually write it. But MathML is fully reproducible from the TeX source code, which is conveniently embedded via `<annotation>`, if you ever hand-adjust it, you are just going to make it out of sync with the TeX. It's the same idea as Mermaid-generated SVGs, which I hope you've never hand-adjusted. The workflow should always be like "write TeX -> plug it into TeXZilla -> paste the output here, with no formatting and everything on the same line".

2024-07-01 10:17 UTC, pepelsbey commented
> MathML is fully reproducible from the TeX source code, which is conveniently embedded via `<annotation>`

I wish that would be the case. In many cases, the `<annotation>` is missing. Also, when I try to create MathML from TeX or TeX from MathML, tools often fail to convert for various reasons. So, I started to trust the MathML source more than the annotations while working on this task.

2024-07-01 13:27 UTC, Josh-Cena commented
> In many cases, the `<annotation>` is missing.

We should add them, then, otherwise our capability to edit them is severely limited.

> Also, when I try to create MathML from TeX or TeX from MathML, tools often fail to convert for various reasons.

In my experience TeXZilla is very stable. We should recommend it (it's made by @fred-wang).

I still don't think you should edit MathML by hand very often. There are a lot of fine tunings to equations such as kernings, offsets, and use of Unicode symbols that are usually missed if you don't do it algorithmically.

2024-07-03 00:56 UTC, dipikabh approved these changes
I've left a few edit suggestions for the prose touched. For the rest, I am deferring to Frédéric Wang's expertise :)

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/baseaudiocontext/createperiodicwave/index.md
> +The `createPeriodicWave()` method of the {{ domxref("BaseAudioContext") }} Interface is used to create a {{domxref("PeriodicWave")}}, which is used to define a periodic waveform that can be used to s
This is a really long sentence, best to split for better readability
```suggestion
The `createPeriodicWave()` method of the {{ domxref("BaseAudioContext") }} interface is used to create a {{domxref("PeriodicWave")}}. This wave is used to define a periodic waveform that can be used to shape the output of an {{ domxref("OscillatorNode") }}.
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/baseaudiocontext/createperiodicwave/index.md
> +The `real` and `imag` arrays have to have the same length, otherwise an error is thrown.
```suggestion
The `real` and `imag` arrays must have the same length, otherwise an error is thrown.
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/baseaudiocontext/createperiodicwave/index.md
> +  - : An dictionary object that specifies whether normalization should be disabled (if not specified, normalization is enabled by default.) It takes one property:
```suggestion
  - : A dictionary object that specifies whether normalization should be disabled. If not specified, normalization is enabled by default. It takes one property:
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/baseaudiocontext/createperiodicwave/index.md
> +Here, we create a `PeriodicWave` with two values. The first value is the DC offset, which is the value at which the oscillator starts. 0 is good here, because we want to start the curve at the middle
```suggestion
Here, we create a `PeriodicWave` with two values. The first value is the DC offset, which is the value at which the oscillator starts. A value of `0` is good here because it starts the curve at the middle of the `[-1.0; 1.0]` range. The second and subsequent values are sine and cosine components, similar to the result of a Fourier transform, which converts time domain values to frequency domain values. Here, with `createPeriodicWave()`, you specify the frequencies, and the browser performs an inverse Fourier transform to get a time domain buffer for the frequency of the oscillator. In this example, we set only one component at full volume (`1.0`) on the fundamental tone, so we get a sine wave. Bear in mind that the fundamental tone corresponds to the oscillator's frequency (which, by default, is `440 Hz`). Therefore, altering the oscillator's frequency effectively shifts the frequency of this periodic wave along with it.
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/canvasrenderingcontext2d/settransform/index.md
> +`setTransform()` has two types of parameter that it can accept. The older type consists of several parameters representing the individual components of the transformation matrix to set:
```suggestion
`setTransform()` accepts two types of parameters. The older type consists of several parameters representing the individual components of the transformation matrix to set:
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/xrrigidtransform/matrix/index.md
> +A {{jsxref("Float32Array")}} containing 16 entries which represents the 4x4 transform matrix which is described by the {{domxref("XRRigidTransform.position", "position")}} and {{domxref("XRRigidTrans
```suggestion
A {{jsxref("Float32Array")}} containing 16 entries, which represents the 4x4 transform matrix described by the {{domxref("XRRigidTransform.position", "position")}} and {{domxref("XRRigidTransform.orientation", "orientation")}} properties.
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/api/xrrigidtransform/matrix/index.md
> +All 4x4 transform matrices used in WebGL are stored in 16-element {{jsxref("Float32Array")}}s. The values are stored into the array in column-major order; that is, each column is written into the arr
is this the intended meaning?
```suggestion
All 4x4 transform matrices used in WebGL are stored in 16-element {{jsxref("Float32Array")}}s. The values are stored in the array in column-major order; that is, each column is written into the array top-down before moving to the next column to the right and writing it into the array. Therefore, for the array `[a0, a1, a2, …, a13, a14, a15]`, the matrix looks like this:
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/javascript/reference/global_objects/math/log1p/index.md
> +When you calculate log(1 + _x_) where _x_ is a small positive number, you should get an answer very close to _x_, because <math><semantics><mrow><munder><mo movablelimits="true" form="prefix">lim</mo
some commas and code fences
```suggestion
When you calculate `log(1 + _x_)`, where _x_ is a small positive number, you should get an answer very close to _x_ because: <math><semantics><mrow><munder><mo movablelimits="true" form="prefix">lim</mo><mrow ><mi>x</mi><mo stretchy="false">→</mo><mn>0</mn></mrow></munder><mfrac><mrow><mi>log</mi><mo>⁡</mo><mo stretchy="false">(</mo><mn>1</mn><mo>+</mo><mi>x</mi><mo stretchy="false">)</mo></mrow><mi>x</mi></mfrac><mo>=</mo><mn>1</mn></mrow><annotation encoding="TeX">\lim\_{x \to 0} \frac{\log(1+x)}{x} = 1</annotation></semantics></math>. If you calculate `Math.log(1 + 1.1111111111e-15)`, you should get an answer close to `1.1111111111e-15`. Instead, you will end up taking the logarithm of `1.00000000000000111022` (the roundoff is in binary, so sometimes it gets ugly), and get the answer `1.11022…e-15`, with only 3 correct digits. If you calculate `Math.log1p(1.1111111111e-15)` instead, you will get a much more accurate answer, `1.1111111110999995e-15`, with 15 correct digits of precision (actually 16 in this case).
```

2024-07-03 00:56 UTC, dipikabh commented on files/en-us/web/mathml/examples/mathml_pythagorean_theorem/index.md
> +the sum of the squares of the other two sides. Specifically, if <math><mi>a</mi></math> and <math><mi>b</mi></math> are the legs and <math><mi>c</mi></math> is the hypotenuse then <math><mrow><msup><
```suggestion
the sum of the squares of the other two sides. Specifically, if <math><mi>a</mi></math> and <math><mi>b</mi></math> are the legs and <math><mi>c</mi></math> is the hypotenuse, then <math><mrow><msup><mi>a</mi><mn>2</mn></msup><mo>+</mo><msup><mi>b</mi><mn>2</mn></msup><mo>=</mo><msup><mi>c</mi><mn>2</mn></msup></mrow></math>.
```

2024-07-03 17:36 UTC, Josh-Cena commented
Thanks 👍 I'm happy as long as they are collapsed!

Are the Prettier comments necessary? I don't think Prettier touches XML markup in Markdown.

2024-07-03 17:49 UTC, Josh-Cena requested changes
I don't have the capacity to review other pages (the diff is hard to read on GH and slow to render locally), but I have one suggestion for JS.

2024-07-03 17:49 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/math/log1p/index.md
> +When you calculate `log(1 + _x_)`, where _x_ is a small positive number, you should get an answer very close to _x_ because: <math><semantics><mrow><munder><mo movablelimits="true" form="prefix">lim<
```suggestion
When you calculate `log(1 + x)`, where `x` is a small positive number, you should get an answer very close to `x` because: <math><semantics><mrow><munder><mo movablelimits="true" form="prefix">lim</mo><mrow ><mi>x</mi><mo stretchy="false">→</mo><mn>0</mn></mrow></munder><mfrac><mrow><mi>log</mi><mo>⁡</mo><mo stretchy="false">(</mo><mn>1</mn><mo>+</mo><mi>x</mi><mo stretchy="false">)</mo></mrow><mi>x</mi></mfrac><mo>=</mo><mn>1</mn></mrow><annotation encoding="TeX">\lim\_{x \to 0} \frac{\log(1+x)}{x} = 1</annotation></semantics></math>. If you calculate `Math.log(1 + 1.1111111111e-15)`, you should get an answer close to `1.1111111111e-15`. Instead, you will end up taking the logarithm of `1.00000000000000111022` (the roundoff is in binary, so sometimes it gets ugly), and get the answer `1.11022…e-15`, with only 3 correct digits. If you calculate `Math.log1p(1.1111111111e-15)` instead, you will get a much more accurate answer, `1.1111111110999995e-15`, with 15 correct digits of precision (actually 16 in this case).
```

1. Don't use `_x_` in code.
2. If you are going to use `x` in code, you need to do it for later occurrences too.
3. I also strongly suggest you use plain text because it's not a code entity.
4. Whatever text changes you made here, you need to make the exact same changes to `expm1`.

2024-07-04 08:58 UTC, pepelsbey commented
> Are the Prettier comments necessary? I don't think Prettier touches XML markup in Markdown.

@Josh-Cena Unfortunately, Prettier is trying to replace `x_2` with `x*2` in annotations, and since they have to be literal to be reproducible, I can’t `x\_2` them. So, only ignoring helps.

2024-07-04 13:46 UTC, Josh-Cena commented
I see.

2024-07-09 13:05 UTC, Josh-Cena approved these changes
I've applied the `Math.log1p` change to `Math.expm1` for consistency. Merge it when you like.

2024-07-09 22:41 UTC, merged

2024-07-09 22:41 UTC, pepelsbey commented
Thank you everyone!