Docs for MAX_NUMBER_OF_DISABLED_STATIC_RULES
mdn/content pull request #34447
Opened 2024-06-27 10:06 UTC by rebloor

### Description

Adds documentation and release note for the `declarativeNetRequest` type `MAX_NUMBER_OF_DISABLED_STATIC_RULES` addressing the dev–doc-needed request from [Bug 1896628](https://bugzilla.mozilla.org/show_bug.cgi?id=1896628) [DNR] Enforce a limit to the maximum number of static rules disabled individually.

### Related issues and pull requests

BCD https://github.com/mdn/browser-compat-data/pull/23533

2024-07-01 07:50 UTC, Rob--W requested changes

2024-07-01 07:50 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- Adds the {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_STATIC_RULES","MAX_NUMBER_OF_DISABLED_STATIC_RULES")}} property to the declarativeNetRequest API. This property holds the maxim
Put this together with the line above about disabling static rules.

And maybe shorten it so that the changelog entry is not too large?

2024-07-01 07:50 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/max_number_of_disabled_static_rules/index.md
> +The maximum number of static rules that can be disabled on each static ruleset.
Mention that this can be done through https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/updateStaticRules and that the current list of disabled rules can be retrieved via https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/getDisabledRuleIds

And mention this constant in these APIs.

2024-07-01 07:50 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +- {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_STATIC_RULES")}}
Could you also mention the limit in the Limits section above? https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#limits

2024-07-05 00:21 UTC, Rob--W approved these changes

2024-07-05 00:21 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/max_number_of_disabled_static_rules/index.md
> +- in Chrome: `5000`
In Chrome the limit is across all static rulesets.

(In Firefox it is per ruleset)

@rpl Could you confirm that this is intentional? What should we document?

2024-07-05 00:21 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/max_number_of_disabled_static_rules/index.md
> +Rules are enable and disable in static rulesets with {{WebExtAPIRef("declarativeNetRequest.updateStaticRules","updateStaticRules")}} and a list of disabled rules for a static ruleset is obtained with
```suggestion
Rules are enabled and disabled in static rulesets with {{WebExtAPIRef("declarativeNetRequest.updateStaticRules","updateStaticRules")}} and a list of disabled rules for a static ruleset is obtained with {{WebExtAPIRef("declarativeNetRequest.getDisabledRuleIds","getDisabledRuleIds")}}.
```

2024-07-05 00:21 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Modifies the enabled state of rules in a static ruleset. The number of rules that can be disabled in a ruleset is limited to the value of {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_
Upon taking a closer look I noticed that limits are not well documented in the individual articles. Let's delete this part here, and append something like this at the end of the section:

> The number of enabled and disabled rules is limited, as explained at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#static_ruleset_limits

(Also do this at getAvailableStaticRuleCount and the other constants)

2024-07-05 00:21 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +- disable rules in a static rulesets up to the value of {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_STATIC_RULES","MAX_NUMBER_OF_DISABLED_STATIC_RULES")}}.
```suggestion
- disable rules in a static rulesets up to the value of {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_STATIC_RULES","MAX_NUMBER_OF_DISABLED_STATIC_RULES")}}. Disabling individual rules does not increase the number of available static rules.
```

Maybe also link to the full explanation at https://github.com/w3c/webextensions/issues/162#issuecomment-2101003747

(If you see a better way to describe what I wrote, please do so. It looks very subtle.)

2024-07-05 18:53 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/index.md
> +- disable rules in a static rulesets up to the value of {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_STATIC_RULES","MAX_NUMBER_OF_DISABLED_STATIC_RULES")}}.
@Rob--W I have rephrased this section, please take a look. In addition, given that we note that "the number of rules in enabled static rulesets for all extensions must not exceed the global limit," do we need to say something about what happens if someone tries to install an extension that (given other extensions they may have installed) exceeds that global limit?

2024-07-05 18:54 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/updatestaticrules/index.md
> +Modifies the enabled state of rules in a static ruleset. The number of rules that can be disabled in a ruleset is limited to the value of {{WebExtAPIRef("declarativeNetRequest.MAX_NUMBER_OF_DISABLED_
@Rob--W hopefully updated all the appropriate "other constants" and I've added the link to the manifest key where we had no particular comment about limits previously

2024-07-08 02:12 UTC, Rob--W approved these changes

2024-07-08 02:12 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/declarativenetrequest/max_number_of_disabled_static_rules/index.md
> +- in Chrome: `5000`
```suggestion
- in Chrome: `5000`, counted across all rulesets instead of per ruleset.
```

According to https://github.com/w3c/webextensions/issues/162#issuecomment-2211076093 Chrome is leaning towards not exposing a constant for now. Nevertheless it would be useful to clarify that the limit is across rulesets instead of per ruleset.

If in doubt I would also be okay with documenting that the limit is across all rulesets for now, and adjust that later to per ruleset if needed. It is always easier to document relaxed constraints than to tighten the restrictions later.

2024-07-08 02:53 UTC, merged