improvements on glossary links in see-also
mdn/content pull request #34454
Opened 2024-06-27 13:13 UTC by PassionPenguin

fixes #34451

2024-07-02 21:21 UTC, dipikabh requested changes
Hi @PassionPenguin, this change should not be replicated to non-glossary pages; the change on the writing guidelines page is not correct.

Also, we've decided to go with the plural form, that is, "Related glossary terms", even when the list has one item. (This is similar to what we do with the [Examples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/CSS_property_page_template#examples) section.)

2024-07-02 21:21 UTC, dipikabh commented on files/en-us/mdn/writing_guidelines/what_we_write/index.md
> +- Related glossary terms
This should stay as is
```suggestion
- Glossary
```

2024-07-02 21:21 UTC, dipikabh commented on files/en-us/web/css/css_grid_layout/index.md
> +- Related glossary termss:
```suggestion
- Related glossary terms:
```

2024-07-02 21:21 UTC, dipikabh commented on files/en-us/web/css/css_transforms/index.md
> +- Related glossary terms:
This need not be updated. It is already in a Related concepts section.

2024-07-02 21:21 UTC, dipikabh commented on files/en-us/web/http/cors/errors/corsalloworiginnotmatchingorigin/index.md
> +  - {{Glossary("CORS")}}
Please revert all changes in web/http files

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/css/css_cascade/index.md
> +- Related glossary terms: {{glossary("style origin")}}
```suggestion
- Glossary: {{glossary("style origin")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/css/css_grid_layout/index.md
> +- Related glossary terms:
```suggestion
- Glossary:
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/css/css_transforms/index.md
> +- Related glossary terms:
```suggestion
- Glossary terms:
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsalloworiginnotmatchingorigin/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsalloworiginnotmatchingorigin/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsdidnotsucceed/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsdidnotsucceed/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsdisabled/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsdisabled/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsexternalredirectnotallowed/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsexternalredirectnotallowed/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsinvalidallowheader/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsinvalidallowheader/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsinvalidallowmethod/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsinvalidallowmethod/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsmethodnotfound/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsmethodnotfound/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsmissingallowcredentials/index.md
> +- Related glossary term:
```suggestion
- Glossary: {{Glossary("CORS")}}
```

2024-07-05 08:11 UTC, PassionPenguin commented on files/en-us/web/http/cors/errors/corsmissingallowcredentials/index.md
> +  - {{Glossary("CORS")}}
```suggestion
```

2024-07-05 08:45 UTC, PassionPenguin commented
@dipikabh i have removed those unrelated changes :) now all changes are restricted within `Glossary/` :)

2024-07-08 11:56 UTC, dipikabh approved these changes
The updates look good. Thanks a lot for your contribution, @PassionPenguin! 🎉

2024-07-08 11:56 UTC, merged