Docs for support for execution-world MAIN
mdn/content pull request #34466
Opened 2024-06-27 18:47 UTC by rebloor

### Description

Documentation in support of [Bug 1736575](https://bugzilla.mozilla.org/show_bug.cgi?id=1736575) Support execution world MAIN in `scripting.executeScript()` and content_scripts including:

- a release note
- removal of comment about non-support for MAIN in `scripting.ExecutionWorld`
- addition of `scripting.ExecutionWorld` and the `world` property to `contentScripts.register()`

### Related issues and pull requests

Related BCD changes in PR TBC

2024-06-28 16:35 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- Support is now provided scripts to run in the web page execution environment. This is provided through support for `MAIN` in {{WebExtAPIRef("scripting.executionWorld","ExecutionWorld")}} for the {{
```suggestion
- Support is now provided for scripts to run in the web page execution environment. This is provided through support for `MAIN` in {{WebExtAPIRef("scripting.executionWorld","ExecutionWorld")}} for the {{WebExtAPIRef("scripting")}} API and the addition of `world` to the {{WebExtAPIRef("contentScripts.register()")}} API ([Firefox bug 1736575](https://bugzil.la/1736575)).
```

2024-07-01 08:02 UTC, Rob--W requested changes

2024-07-01 08:02 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/contentscripts/register/index.md
> +      - : {{WebExtAPIRef("contentScripts.ExecutionWorld")}}. The execution environment for a script to execute in.
Link to the content_scripts manifest key instead, like all other properties here already do.

2024-07-01 08:02 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/contentscripts/executionworld/index.md
> +title: contentScripts.ExecutionWorld
Drop this article. The API doesn't expose this type.

2024-07-02 15:23 UTC, Rob--W approved these changes

2024-07-02 22:15 UTC, merged