Persian & Arabic examples
mdn/content pull request #3449
Opened 2021-03-24 14:24 UTC by amirmp3

> Added persian & arabic-indic list style types example from 1 to 6.

> https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

2021-03-26 00:17 UTC, wbamberg requested changes
Thanks for adding these, @amirmp3 !

I think the idea of this section is that each `<ul>` gets the list-style for the value it's describing, if you see what I mean.

So rather than:

```html
 <dt><code>arabic-indic</code></dt>
 <dt><code>-moz-arabic-indic</code></dt>
 <dd>
 <ul>
  <li>E.g. ١, ٢, ٣, ٤, ٥, ٦</li>
 </ul>
 </dd>
```

...it would be:

```html
 <dt><code>arabic-indic</code></dt>
 <dt><code>-moz-arabic-indic</code></dt>
 <dd>
 <ul style="list-style-type: arabic-indic;">
  <li>Arabic-indic numbering</li>
  <li>E.g. ١, ٢, ٣, ٤, ٥, ٦</li>
 </ul>
 </dd>
```

...and rather than:

```html
 <dt><code>-moz-persian</code></dt>
 <dd>
 <ul>
  <li>E.g. ۱, ۲, ۳, ۴, ۵, ۶</li>
 </ul>
 </dd>
```

...it would be:

```html
 <dt><code>persian</code> {{experimental_inline}}</dt>
 <dt><code>-moz-persian</code></dt>
 <dd>
 <ul style="list-style-type: persian;">
  <li>Persian numbering</li>
  <li>E.g. ۱, ۲, ۳, ۴, ۵, ۶</li>
 </ul>
 </dd>
```

Does that make sense?

2021-03-27 20:41 UTC, amirmp3 reviewed
Added inline CSS list-style-type property to persian and arabic-indic unordered list example.

2021-03-27 20:44 UTC, amirmp3 commented
@wbamberg 

Yeah, thanks! According to the article, it's better to show real examples as well, so I added them.

2021-04-20 19:58 UTC, Ryuno-Ki commented
@wbamberg Ping

2021-04-21 00:13 UTC, wbamberg approved these changes
Sorry @amir2mi , this fell off my list. This looks great, and thanks for the contribution!

(but, we'll need to revisit this page when we look at converting it to Markdown)

2021-04-21 00:13 UTC, merged