Docs for content script injection into data URL pages
mdn/content pull request #34491
Opened 2024-06-28 17:51 UTC by rebloor

### Description

Docs in support of  [Bug 1475831](https://bugzilla.mozilla.org/show_bug.cgi?id=1475831) WebExtension: content scripts should be injected in data URL pages, including:

- release notes
- addition of `match_origin_as_fallback` to `content_scripts manifest` key

### Related issues and pull requests

Related BCD update in https://github.com/mdn/browser-compat-data/pull/23553

2024-06-28 21:32 UTC, Rob--W requested changes

2024-06-28 21:32 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- The [manifest key `content_scripts`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts) now supports `match_origin_as_fallback`, enabling scripts to be injected into `about:`,
Also mention the addition to the contentScripts.register API (and update the BCD accordingly). This is part of the set of changes to content_scripts and was implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1896669

https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register

And please include a mention of the change to blob:-URLs from https://bugzilla.mozilla.org/show_bug.cgi?id=1897113

2024-06-28 21:32 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- The {{WebExtAPIRef("scripting")}} API can now inject scripts into sandboxed pages with `about:blank`, `about:srcdoc`, and `data:` URLs ([Firefox bug 1475831](https://bugzil.la/1475831)).
Specifically the scripting.executeScript, insertCSS and removeCSS methods.

The registerContentScripts and updateContentScripts now have a new option to support the same capability, implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1853411. This needs their own documentation updates and BCD entries.

2024-06-30 16:55 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- The {{WebExtAPIRef("scripting")}} API can now inject scripts into sandboxed pages with `about:blank`, `about:srcdoc`, and `data:` URLs ([Firefox bug 1475831](https://bugzil.la/1475831)).
@Rob--W https://bugzilla.mozilla.org/show_bug.cgi?id=1853411 isn't marked as dev-doc-needed, any reason why it can't be flagged? I'll then address it as part of the backlog.

2024-06-30 16:59 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/128/index.md
> +- The {{WebExtAPIRef("scripting")}} API can now inject scripts into sandboxed pages with `about:blank`, `about:srcdoc`, and `data:` URLs ([Firefox bug 1475831](https://bugzil.la/1475831)).
I didn't flag it separately because it is part of the same feature. I figured that it would be less confusing for you to wait for the documentation PR and providing the extra context than to slap the dev-doc-needed keyword on multiple bugs without context.

2024-07-01 07:40 UTC, Rob--W approved these changes
Thanks!

The section about Limitations https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#limitations needs to be revised to spell out the new behaviors, but that can be covered as part of the sandbox documentation PR.

Please apply the suggested small change and then merge this PR.

2024-07-01 07:53 UTC, merged