fix(html): update positioning and scaling section
mdn/content pull request #34529
Opened 2024-07-01 07:01 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/32474

The `object-fit` doesn't work at all in any browser. And `object-position` works only in Firefox.

In the OWD meeting, it was decided to remove `object-fit` from the section. And [update BCD of `object-position`](https://github.com/mdn/browser-compat-data/issues/23586) to show that, for iframe, it's supported only in Firefox.

2024-07-01 14:09 UTC, Josh-Cena commented
This is also mentioned in `<embed>` and `<fencedframe>` (I would just assume other image-related elements do support these two properties). Should we update those too (given tests)?

Also the `object-fit` says it works for all replaced elements which then doesn't seem true.

https://github.com/w3c/csswg-drafts/issues/7143 is relevant here.

2024-07-10 17:21 UTC, dipikabh requested changes
@OnkarRuikar, thanks for working on this reported issue!

Please see my suggestions for the `iframe` page. If you agree, they can be applied to the other two pages as well.

I think we should add a similar note on the [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) page as well since it does not apply to all replaced elements.

2024-07-10 17:21 UTC, dipikabh commented on files/en-us/web/html/element/iframe/index.md
> +As a [replaced element](/en-US/docs/Web/CSS/Replaced_element), the position of the embedded document within the `<iframe>` element's box can be adjusted with the {{cssxref("object-position")}} proper
This suggestion is for the already existing phrasing:
- Since `<iframe>` is the replaced element, I was expecting to read "As a replaced element, iframe can..."
- Slight nit about "with" vs "using" => more direct and clear
```suggestion
Being a [replaced element](/en-US/docs/Web/CSS/Replaced_element), the `<iframe>` allows the position of the embedded document within its box to be adjusted using the {{cssxref("object-position")}} property.
```

2024-07-10 17:21 UTC, dipikabh commented on files/en-us/web/html/element/iframe/index.md
> +> The {{cssxref("object-fit")}} doesn't work on `<iframe>` element.
While this is correct, we can be more precise about what "doesn't work" mean because using the property will not be flagged as an error. WDYT about saying:
```suggestion
> The {{cssxref("object-fit")}} has no effect on `<iframe>` elements.
```

2024-07-11 07:30 UTC, bsmth commented
Removing myself from review because Dipika and Josh are on it!

2024-07-11 12:33 UTC, dipikabh requested changes
Thanks @OnkarRuikar. It's close, just a matter of replicating updates to `<embed>` and `<fencedframe>`.

2024-07-11 12:33 UTC, dipikabh commented on files/en-us/web/css/object-fit/index.md
> +> The `object-fit` has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and {{HTMLElement("fencedframe")}} elements.
I think we can leave out `<fencedframe>` because it is experimental and also not listed on the replaced elements page
```suggestion
> The `object-fit` property has no effect on {{HTMLElement("iframe")}} and {{HTMLElement("embed")}} elements.
```

2024-07-11 12:33 UTC, dipikabh commented on files/en-us/web/html/element/embed/index.md
> +> The {{cssxref("object-fit")}} doesn't work on `<embed>` element.
Can be updated similar to the note in `<iframe>`

2024-07-11 12:33 UTC, dipikabh commented on files/en-us/web/html/element/fencedframe/index.md
> +> The {{cssxref("object-fit")}} doesn't work on `<fencedframe>` element.
Can be updated similar to the note in `<iframe>`

2024-07-11 12:33 UTC, dipikabh commented on files/en-us/web/html/element/fencedframe/index.md
> +As a [replaced element](/en-US/docs/Web/CSS/Replaced_element), the position of the embedded document within the `<iframe>` element's box can be adjusted with the {{cssxref("object-position")}}.
Can be updated similar to the sentence on `<iframe>` page

2024-07-11 23:34 UTC, Josh-Cena commented on files/en-us/web/css/object-fit/index.md
> +> The `object-fit` has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and {{HTMLElement("fencedframe")}} elements.
IMO, we should mention `fencedframe`. Not being in the replaced elements list is a bug that should be fixed separately, but the `fencedframe` page itself claims that it's a replaced element.

2024-07-12 05:15 UTC, OnkarRuikar commented
> It's close, just a matter of replicating updates to `<embed>` and `<fencedframe>`.

My bad. I had this in mind but it slipped my mind in a split second.

> I think we can leave out `<fencedframe>` because it is experimental

Lets future future-proof the content by keeping it. If the `fencedframe` changes the behavior, we'll update accordingly.

> Not being in the replaced elements list is a bug that should be fixed separately

We have to update the page [here itself](https://github.com/mdn/content/pull/34529/commits/e0b715b2a334fe57a3c47df07265450376b773db) as it also contains a section about `object-fit`.

2024-07-15 01:07 UTC, dipikabh requested changes

2024-07-15 01:07 UTC, dipikabh commented on files/en-us/web/css/object-fit/index.md
> +> The `object-fit` has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and {{HTMLElement("fencedframe")}} elements.
```suggestion
> The `object-fit` property has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and {{HTMLElement("fencedframe")}} elements.
```

2024-07-15 01:07 UTC, dipikabh commented on files/en-us/web/css/replaced_element/index.md
> +  - : Specifies how the replaced element's content object should be fitted to the containing element's box. The `object-fit` has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and
```suggestion
  - : Specifies how the replaced element's content object should be fitted to the containing element's box. The `object-fit` property has no effect on {{HTMLElement("iframe")}}, {{HTMLElement("embed")}}, and {{HTMLElement("fencedframe")}} elements.
```

2024-07-15 01:07 UTC, dipikabh commented on files/en-us/web/html/element/embed/index.md
> +> The {{cssxref("object-fit")}} has no effect on `<embed>` elements.
```suggestion
> The {{cssxref("object-fit")}} property has no effect on `<embed>` elements.
```

2024-07-15 01:07 UTC, dipikabh commented on files/en-us/web/html/element/fencedframe/index.md
> +> The {{cssxref("object-fit")}} has no effect on `<fencedframe>` elements.
```suggestion
> The {{cssxref("object-fit")}} property has no effect on `<fencedframe>` elements.
```

2024-07-15 01:07 UTC, dipikabh commented on files/en-us/web/html/element/iframe/index.md
> +> The {{cssxref("object-fit")}} has no effect on `<iframe>` elements.
```suggestion
> The {{cssxref("object-fit")}} property has no effect on `<iframe>` elements.
```

2024-07-15 01:10 UTC, dipikabh approved these changes
Thanks, @OnkarRuikar!

2024-07-15 01:10 UTC, merged