fix: Use absolute URL for observatory link
mdn/content pull request #34591
Opened 2024-07-03 09:07 UTC by bsmth

Currently, the URL shows as a broken link even though it works.

### Description

__changes:__
* `/en-US/observatory/` to `https://developer.mozilla.org/en-US/observatory/`
* mdlint rule to ignore observatory link

2024-07-03 09:10 UTC, bsmth commented on files/en-us/web/security/practical_implementation_guides/index.md
> +Most of these guides are directly related to the [HTTP Observatory](https://developer.mozilla.org/en-US/observatory/) tool. Observatory performs security audits on a website and provides a grade and
@caugner does this need some handling in Yari to ignore as a flaw?

2024-07-03 09:14 UTC, caugner requested changes
Obseratory currently has no trailing slash.

2024-07-03 09:14 UTC, caugner commented on .markdownlint.jsonc
> +        "searchPattern": "/\\]\\(https:\\/\\/developer.mozilla.org\\/(?!en-US\\/(blog|observatory)\\/)/g",
```suggestion
        "searchPattern": "/\\]\\(https:\\/\\/developer.mozilla.org\\/(?!en-US\\/(blog\\/|observatory))/g",
```

2024-07-03 09:14 UTC, caugner commented on files/en-us/web/security/practical_implementation_guides/index.md
> +Most of these guides are directly related to the [HTTP Observatory](https://developer.mozilla.org/en-US/observatory/) tool. Observatory performs security audits on a website and provides a grade and
```suggestion
Most of these guides are directly related to the [HTTP Observatory](https://developer.mozilla.org/en-US/observatory) tool. Observatory performs security audits on a website and provides a grade and score along with recommendations for fixing the security issues it finds. These guides explain how to resolve issues surfaced by the HTTP Observatory tests: the tool links to the relevant guide for each issue, helping guide you towards an effective resolution. Interestingly, Mozilla's internal developer teams use this guidance when implementing websites to ensure that security best practices are applied.
```

2024-07-04 14:51 UTC, bsmth commented
This is fixed in the linked PR instead. Closing now

2024-07-04 14:51 UTC, closed without merging