fix(css): add bracketed range notation
mdn/content pull request #34670
Opened 2024-07-06 08:29 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/34186

Corresponding spec https://drafts.csswg.org/css-values-4/#numeric-ranges

2024-07-06 12:56 UTC, chrisdavidmills requested changes
Lovely work, thanks @OnkarRuikar! I've made a few comments for you to consider.

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +## Bracketed range notation (`[,]`)
```suggestion
## Bracketed range notation (`[min,max]`)
```

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +Some properties take numeric values that can be in a limited range, and any value out of the range makes the declarations invalid and the declaration is ignored. For example, the [`column-count`](/en
```suggestion
Some types can accept numeric values within a certain range. For example, the [`column-count`](/en-US/docs/Web/CSS/column-count) property can accept an integer value between positive 1 and infinity, inclusive. The corresponding syntax looks like this:

<integer [1,∞]>

Any value outside this specified range causes the whole declaration to be invalid, therefore the browser will ignore it.
```

You should put "<integer [1,∞]>" inside a code fence. I didn't do it above because it would have caused the suggestion to break. That also uses a code fence ;-)

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +The _bracketed range notation_ `[min, max]` indicates the range between `min` and `max` values. The range includes `min` and `max` values as well. The range notation is used in numeric type notations
```suggestion
The _bracketed range notation_ `[min, max]` indicates an inclusive range between a `min` and `max` value. This notation is used in numeric type notations and can include units, e.g. `<angle [0,180deg]>`. Positive and negative Infinity (-∞ and ∞) must not have units specified. Types specified in units can have zero values specified with or without units, for example `<time [0s,10s]>` or `<time [0,10s]>`.
```

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +Following are some examples:
```suggestion
Here are some more examples:
```

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +      <td><code>[,]</code></td>
```suggestion
      <td><code>[min,max]</code></td>
```

Maybe update the curly braces to be consistent with this too? I think min and max are pretty intuitive; more so than A and B.

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +- `<integer>` or `<integer [-∞,∞]>` - any integer from negative infinity to positive infinity
```suggestion
-  `<integer [-∞,∞]>`: Any integer from negative infinity to positive infinity is valid.
```

I wouldn't include `<integer>` — it doesn't include the range bracket notation. Or if you do want to include it, maybe include a line at the end of the bullet saying something like "Note that `<integer>` and `<integer [-∞,∞]>` are equivalent."

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +- `<integer [0,∞]>` - negative integers not allowed
```suggestion
- `<integer [0,∞]>`: Any integer from 0 to positive infinity is valid. Negative integers are invalid.
```

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +- `<time [0s,10s]>` or `<time [0,10s]>` - time less than 11 seconds
```suggestion
- `<time [0s,10s]>` or `<time [0,10s]>`: Any duration from 0 to 10 seconds is valid.
```

2024-07-06 12:56 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +- `<integer [-∞,-1]> | <integer [1,∞]>` - any integer except zero
```suggestion
- `<integer [-∞,-1]> | <integer [1,∞]>`: Any integer except zero is valid.
```

2024-07-08 01:44 UTC, OnkarRuikar commented on files/en-us/web/css/value_definition_syntax/index.md
> +Some properties take numeric values that can be in a limited range, and any value out of the range makes the declarations invalid and the declaration is ignored. For example, the [`column-count`](/en
````suggestion
Some types can accept numeric values within a certain range. For example, the [`column-count`](/en-US/docs/Web/CSS/column-count) property can accept an integer value between positive 1 and infinity, inclusive. The corresponding syntax looks like this:

```plain
<integer [1,∞]>
```

Any value outside this specified range causes the whole declaration to be invalid, therefore the browser will ignore it.
````

2024-07-08 01:55 UTC, OnkarRuikar commented on files/en-us/web/css/value_definition_syntax/index.md
> +Some properties take numeric values that can be in a limited range, and any value out of the range makes the declarations invalid and the declaration is ignored. For example, the [`column-count`](/en
> You should put "<integer [1,∞]>" inside a code fence. I didn't do it above because it would have caused the suggestion to break. That also uses a code fence ;-)

**Pro tip:** Backticks in the code fence should be more than backticks in the code, e.g. to add the syntax section (3 backticks) here use four backticks for the suggestion fence ````` ````suggestion ````` (to show this example I used five backticks `````` ````` ````suggestion ````` ``````).

2024-07-18 12:05 UTC, chrisdavidmills commented on files/en-us/web/css/value_definition_syntax/index.md
> +Some properties take numeric values that can be in a limited range, and any value out of the range makes the declarations invalid and the declaration is ignored. For example, the [`column-count`](/en
@OnkarRuikar ah, brilliant, I didn't know that — thanks for the tip!

2024-07-18 12:31 UTC, chrisdavidmills approved these changes
@OnkarRuikar great stuff, this is now ready to go! I made a few grammar fixes while I was re-reviewing.

2024-07-18 12:31 UTC, merged