feat: improvements on attribute & boolean/html
mdn/content pull request #34728
Opened 2024-07-09 08:02 UTC by PassionPenguin

@chrisdavidmills a further update than #33386 - boolean attribute actually *have an individual entry* `/Glossary/Boolean/HTML`

- **fixed**: trimed down `/Glossary/Attribute`, moving the detailed information of boolean attribute onto `/Glossary/Boolean/HTML`
- **fixed**: out-dated information according to the HTML spec *2.3.2* under `/Glossary/Boolean/HTML`

<img width="1288" alt="Screenshot 2024-07-09 at 4 00 07 PM" src="https://github.com/mdn/content/assets/41184947/5840f572-6af6-4810-8e8e-52003e7c8804">

- **added**: inter-glossary links

2024-07-09 13:18 UTC, Josh-Cena commented
The paragraph in the spec below your screenshot says what you removed in the content:

> If the attribute is present, its value must either be the empty string or a value that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the attribute's canonical name, with no leading or trailing whitespace.

2024-07-09 13:31 UTC, Josh-Cena requested changes

2024-07-09 13:31 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
I was about to say "it looks incorrect before and after!" then I realized it was just changed in #33386.

The lack of a value is a _syntax_ concept, not a _semantics_ concept. There's nothing about an attribute without value that implies it's boolean. The only thing you can be certain is that its value is the empty string, and it happens that the empty string is a legal value for boolean attributes. `<input placeholder>` or `<img alt>` are also valid markup.

The content before #33386 was fully accurate.

2024-07-09 13:31 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +<input required="anything" />
This example needs to be changed to `required="required"`. @chrisdavidmills's impression was not wrong: the only correct value to have is `"required"` and everything else is legacy and we shouldn't demonstrate it.

2024-07-10 01:06 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +<input required="anything" />
well **I was doubted** about maybe `anything` could be wrong when I take a look at `/Glossary/Boolean/HTML`, but when I take a closer look at the specification the doc references, I found that actually `anything` is correct.

<img width="1335" alt="image" src="https://github.com/mdn/content/assets/41184947/98dbd13c-b657-4505-8f10-d1a398e8a2a7">

The HTML spec describes a valid boolean attribute being set to true only requires **the presence** of such attr.

2024-07-10 01:09 UTC, PassionPenguin commented
> The paragraph in the spec below your screenshot says what you removed in the content:
> 
> > If the attribute is present, its value must either be the empty string or a value that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the attribute's canonical name, with no leading or trailing whitespace.
> 
> This glossary entry was written less than 2 years ago, so it's definitely not outdated.

Oops, that's correct. shall i do a cleanup right after.

2024-07-10 01:11 UTC, PassionPenguin commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
as the spec says

> [!note]
> The presence of a boolean attribute on an element represents the **true** value, and the absence...

so for the changes: `are considered to be true`, that should be correct.

2024-07-10 01:13 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
For boolean attributes, attributes without equals sign implies `true`. That's right. BUT, attributes without equals sign are NOT automatically boolean attributes having the value `true`. `<img src="..." alt>` is valid markup and is the same as `alt=""`; that doesn't make `alt` a boolean attribute.

2024-07-10 01:17 UTC, PassionPenguin commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
oops, that's my mistake. sorry about that 😭

2024-07-10 01:18 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
>  ```
There's no such thing as a "boolean attribute" in XML (in fact, there's not even the concept of "data types"), so not sure if we want to mention it. XML is like JSON where everything has to be a key-value pair.

2024-07-10 01:19 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +> **Note:** Though setting the value of a boolean attribute to anything may be parsed as true across different browsers, it's suggested to follow the [specification](https://html.spec.whatwg.org/#boo
Keep the previous mentions of "true" and "false"; those are the most common misconceptions.

Also I'm not sure why you are replacing a well-organized list with a less-organized example code and note block. I suggest keeping the list.

2024-07-10 01:20 UTC, PassionPenguin commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
as inferred from the content before and after the sentence, should the editor means to introduce `bool attr`?

2024-07-10 01:23 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
I think there's just no need to mention "boolean attribute" here. This page talks about _syntax_ but boolean is a _semantics_ concept. In the same way you wouldn't talk about "boolean parameters" on a page about "parameters" in general. Here's the previous text about HTML:

> You may see attributes without the equals sign or a value. That is a shorthand for providing the empty string in HTML

To me that sounds reasonable, and you can follow that with your corrected sentence: "However, this is not allowed in XML: XML requires the equals sign followed by the attribute name."

2024-07-10 01:25 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +A number of attributes are {{Glossary("Boolean/HTML", "boolean attributes")}}. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents
This still doesn't read right to me. While not strictly wrong, this can easily be misinterpreted as saying "only boolean attributes can be set without equals sign". Again, why do we need to mention boolean attributes at all? It's just an HTML shorthand for setting the value to `""`, whether that `""` represents `true` or the empty string or `null`.

2024-07-10 01:26 UTC, PassionPenguin commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
the concept `boolean attribute` should be **SYNTAX** (a micro one), according to the spec section 2.3 (Common microsyntaxes).

and followed up, having a brief description of such syntax and leaving a link to the main entry should be reasonable.

2024-07-10 01:27 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +  - {{Glossary("Attribute")}}
Why remove "enumerated"? "Enumerated attributes" and "boolean attributes" are the two biggest concepts about HTML attributes.

2024-07-10 01:29 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +You may see attributes without an equals sign or a value. They are {{Glossary("Boolean/HTML", "boolean attributes")}}, the shorthand for providing the empty string in HTML and are considered to be `t
HTML doesn't have the strict dichotomy of syntax vs. semantics. For example, content categories are more semantics but they direct how documents are parsed.

> There are various places in HTML that accept particular data types, such as dates or numbers. This section describes what the conformance criteria for content in those formats is, and how to parse them.

Data type is a semantic in any language. If I tell you that X is a "boolean attribute", that doesn't tell you anything about the syntax of the X attribute—it's exactly the same as all other attributes.

2024-07-10 01:33 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +  - {{Glossary("Attribute")}}
we are here under boolean attribute, not attribute

2024-07-10 01:35 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
>  ```
that was just a move from attribute to boolean/html. i was doubted the necessity of having xml mentioned in HTML. (but i do think leaving `However, this is not allowed in XML: XML requires the equals sign followed by the attribute name.` is reasonable)

2024-07-10 01:36 UTC, Josh-Cena commented
The same comment as your other glossary updates: the content, in its current form, is correct and understandable. We would prefer to make as few changes to it as possible unless there are provable errors.

The changes I would personally like to see in this PR:

1. Remove the misleading implication that "attribute without equals sign" and "boolean attribute" have anything to do with each other. "Attribute without equals sign" is not necessarily boolean and boolean attribute is not necessarily specified without equals sign. I'm fine with a passing mention on the "attributes" page that "HTML attributes have types; for example there are boolean attributes, enumerated attributes, etc." but it doesn't tell you anything about the syntax.
2. The `<input required>` example is good and should indeed be moved to the "boolean" entry.
3. More related glossary terms links are good.

Apart from these, I would take all other changes as unnecessary.

2024-07-10 01:37 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +> **Note:** Though setting the value of a boolean attribute to anything may be parsed as true across different browsers, it's suggested to follow the [specification](https://html.spec.whatwg.org/#boo
a. previous mentions are not restricted only in the misconceptions.
b. the code was moved from attribute.

2024-07-10 01:43 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +  - {{Glossary("Attribute")}}
Sure, and "enumerated" is also a kind of attribute, so they are related concepts? More links are always better and it's not like there's a link tax, so we don't have to remove them. Usually, all subpages discussing the same meta-topic should preferably be all cross-linked instead of just linking to the main meta-topic page.

2024-07-10 01:47 UTC, PassionPenguin commented on files/en-us/glossary/attribute/index.md
> +A number of attributes are {{Glossary("Boolean/HTML", "boolean attributes")}}. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents
a. still, for me the glossary should list the definitions (which are the most important things, as mentioned in the `glossary/index.md`). *attribute without a equal sign and a value are shorthand* should be mentioned in HTML/Attribute, not here, given it's not a definition, or at least merged with the sentence above.

b. mentioning boolean attribute, is it's a common definition (sub-concept of attribute), and it's not made by me, but also by previous editors. it's also a common practice across entries like this.

2024-07-10 01:48 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +If the boolean attribute is present, the value of it shuold be of the following cases:
```suggestion
If the attribute is present, it can have one of the following values:
```

Suggest revert since the previous one is clearer

2024-07-10 01:48 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +A **boolean attribute** in {{Glossary("HTML")}} is an attribute that represents `true` or `false` values. If an HTML tag contains a boolean attribute - no matter the value of that attribute - the att
```suggestion
A **boolean attribute** in {{Glossary("HTML")}} is an attribute that represents `true` or `false` values. If an HTML tag contains a boolean attribute - no matter the value of that attribute - the attribute is set to `true` on that element. If an HTML tag does not contain the attribute, the attribute is set to `false`.
```

(There's no mention of "attribute without equals sign" in this paragraph so not sure what "this" is referring to)

2024-07-10 01:48 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
>  - no value at all, e.g. `attribute`
```suggestion
- no value at all, e.g. `attribute` (This is not allowed in XML: XML requires the equals sign followed by the attribute name.)
```

If you _really_ want to mention it. I'm not sure if this is necessary and it seems you don't really think so either, but up to you.

2024-07-10 01:48 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +- attribute's canonical name, with no leading or trailing whitespace, e.g. `attribute="attribute"`
Personal suggestion is we don't have to go so technical. "Canonical name" is just because HTML is case-insensitive, but we have never mentioned anything other than lowercase, and I would expect most readers to believe they can only be written lower-cased. I'm fine either way.

2024-07-10 01:48 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> -Here's an example of a HTML boolean attribute `checked`:
Hmmm... So we have no examples left?

2024-07-10 01:49 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +If the boolean attribute is present, the value of it shuold be of the following cases:
(thx. the sentence was rewritten as i forget to copy the previous one)

2024-07-10 01:51 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +An attribute always has the form `name="value"` (the attribute's identifier followed by its associated value). You may see attributes without an equals sign or a value. That is a shorthand for provid
```suggestion
An attribute always has the form `name="value"` (the attribute's identifier followed by its associated value). You may see attributes without an equals sign or a value. That is a shorthand for providing the empty string in HTML. However, this is not valid in XML: XML requires all attributes to have an explicit value.
```

2024-07-10 01:51 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +  - {{Glossary("Attribute")}}
yeap. that's a good point:)

2024-07-10 01:51 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
> +  - {{Glossary("Attribute")}}
```suggestion
  - {{Glossary("Attribute")}}
  - {{Glossary("Enumerated", "Enumerated attribute")}}
```

2024-07-10 01:51 UTC, PassionPenguin commented on files/en-us/glossary/boolean/html/index.md
```suggestion

Here's an example of a HTML boolean attribute `checked`:

```html
<!-- The following checkboxes will be checked on initial rendering -->
<input type="checkbox" checked />
<input type="checkbox" checked="" />
<input type="checkbox" checked="checked" />

<!-- The following checkbox will not be checked on initial rendering -->
<input type="checkbox" />
```
```

2024-07-10 01:51 UTC, Josh-Cena commented on files/en-us/glossary/attribute/index.md
> +A number of attributes are {{Glossary("Boolean/HTML", "boolean attributes")}}. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents
```suggestion
A number of HTML attributes are {{Glossary("Boolean/HTML", "boolean attributes")}}. These attributes' values are only controlled by the presence or absence of the attribute. See {{Glossary("Boolean/HTML", "boolean attributes")}} for more information.
```

2024-07-10 01:58 UTC, Josh-Cena commented on files/en-us/glossary/boolean/html/index.md
> +- no value at all, e.g. `attribute` (This is not allowed in XML: XML requires the equals sign followed by the attribute name.)
```suggestion
- no value at all, e.g. `attribute`
```

Actually let's remove it. This page is about HTML, no need to bring in other languages.

2024-07-10 01:59 UTC, Josh-Cena approved these changes
I have gone ahead and made some changes myself, which IMO are necessary before merging this PR. @PassionPenguin thank you for the work—this looks great! I have annoyed you enough so let's merge this now 😄

2024-07-10 11:15 UTC, PassionPenguin commented
> I have gone ahead and made some changes myself, which IMO are necessary before merging this PR. @PassionPenguin thank you for the work—this looks great! I have annoyed you enough so let's merge this now 😄

Thanks. Your and other reviewer's points on the reviewing process are reasonable and thanks for your kind review.

You are right, that I have made some many unnecessary changes to the content. Though some of them might have improved the content, many are unnecessary, and even breaks the content.

In this case, what I do not take enough care is having moved content from `/Glossary/Attribute` to `/Glossary/Boolean/HTML` without a second thought. Sincerely thanks and appreciations for the suggestions made.

p.s. in the last commit, I have added a macro link (in the main content). everything else looks great. Thanks for your work!

2024-07-10 13:50 UTC, merged