fix(css): update sticky positioning section
mdn/content pull request #34776
Opened 2024-07-11 10:09 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/33146

The very first statement in the section throws heavy jargon at readers. Without knowing what sticky positioning means it's not being helpful. Rewarding the intro para in simple terms.

I think the accordion example is a bit too much for the simple intro. Replacing it with a simple one that asserts the importance of the entire inset area.

2024-07-11 12:31 UTC, bsmth commented on files/en-us/web/css/position/index.md
> +You must specify at least one of `top`, `right`, `bottom`, or `left` inset for sticky positioning to behave as expected. Otherwise, it will be indistinguishable from relative positioning.
I feel like these two paragraphs should go, it seems to be more confusing than clarifying. We could replace it with:

>The above CSS rule would position the element with id _one_ relatively until the viewport was scrolled such that the element would be less than 10 pixels from the top. Beyond that threshold, the element would be fixed to 10 pixels from the top.

But change to "The following CSS rule would" with some other minor improvements.

2024-07-12 06:03 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +You must specify at least one of `top`, `right`, `bottom`, or `left` inset for sticky positioning to behave as expected. Otherwise, it will be indistinguishable from relative positioning.
> I feel like these two paragraphs should go, it seems to be more confusing than clarifying. We could replace it with:

The feature itself is tricky so the description would be hard to grasp in one go. This is the main section about sticky positioning on MDN and search engines land people here. We have to define the concept somehow and can't skip the definition part.

2024-07-12 06:46 UTC, OnkarRuikar commented on files/en-us/web/css/position/index.md
> +You must specify at least one of `top`, `right`, `bottom`, or `left` inset for sticky positioning to behave as expected. Otherwise, it will be indistinguishable from relative positioning.
Yes, the values section already does define the concept in detail no need to repeat it in the examples section again.

2024-07-12 15:05 UTC, bsmth requested changes
Thanks Onkar! Although I think this example is really clever, I have to say the original helps me understand `position: sticky;` better. I had some trouble figuring out what I was supposed to do in the scroll box. If I compare it with the interactive example on the top of the page, the additions are a little too complex! 😄 

I think we can either revert the example changes to the one that's live on prod, or we do something that's got a little less going on like an element that sticks on scroll like here: https://developer.mozilla.org/en-US/docs/Web/CSS/position#try_it

What do you think?

2024-07-13 05:51 UTC, OnkarRuikar commented
>  I have to say the original helps me understand `position: sticky;` better.

I've brought the original sticky heading in list example back.

> I had some trouble figuring out what I was supposed to do in the scroll box.

I've changed the wording.

> If I compare it with the interactive example on the top of the page, the additions are a little too complex! 😄

The "try it" section already covers a simple example so we don't have to repeat similar/simplar thing again. I really wanted to demo what happens when all the inset boundaries are set and how the element stays confined to the inset area. :(

How about we keep the original and mine both? :)

2024-07-16 08:14 UTC, bsmth commented
Thanks, Onkar!

> > I had some trouble figuring out what I was supposed to do in the scroll box.
> 
> I've changed the wording.

Looks better, IMO 🙌🏻  

> How about we keep the original and mine both? :)

I think that's a good idea. Having a look at prose now, but overall looking good!

2024-07-16 08:18 UTC, bsmth commented on files/en-us/web/css/position/index.md
> +The following example demonstrates how an element behaves when all the inset boundaries are set. Here we have two light bulb emojis in a paragraph. Both the light bulbs have been made sticky, and ins
```suggestion
The following example demonstrates an element's behavior when all inset boundaries are set. Here, we have two light bulb emojis in a paragraph. The light bulbs use sticky positioning, and the inset boundaries are specified as 50px from the top, 100px from the right, 50px from the bottom, and 50px from the left. A gray background on the parent div element marks the inset area.
```

2024-07-16 08:20 UTC, bsmth commented on files/en-us/web/css/position/index.md
> +After you put both the bulbs in their right place, you'll notice that the bulbs act as relatively positioned inside the inset area. But as soon as they get moved out of the inset area they get fixed(
```suggestion
When you put both bulbs in their proper place, you'll notice that they are relatively positioned inside the inset area. When you move them out of the inset area, they are fixed (sticky) to the inset boundary in that direction.
```

2024-07-16 08:20 UTC, bsmth approved these changes
Some comments for you, but leaving a +1, thank you!

2024-07-16 08:46 UTC, bsmth commented on files/en-us/web/css/position/index.md
> +The following CSS rule would position the element with id one relatively until the viewport was scrolled such that the element would be less than 10 pixels from the top. Beyond that threshold, the el
```suggestion
The following CSS rule positions the element with id `one` relatively until the viewport is scrolled such that the element is 10 pixels from the top. Beyond that threshold, the element is fixed to 10 pixels from the top.
```

2024-07-16 08:48 UTC, merged