New: CSS view transitions module landing page
mdn/content pull request #34803
Opened 2024-07-12 07:31 UTC by estelle

I noticed this page was missing, so I threw together a first-best effort for a module landing page. 

note: the CSSViewTransitionRule, the one red link, is supported in Chrome 126, per BCD, but is not yet documented.

2024-07-30 02:18 UTC, dipikabh requested changes
Thanks for adding this page, @estelle. I've added a few quick suggestions.

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("view-transition-name")}}
should be marked as experimental?

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +> The CSS view transitions module also defines an additional property, `view-transition-class`, which is not currently supported in any browser.
```suggestion
> The module defines the CSS property `view-transition-class`, but it is currently not supported in any browser.
```

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +  - [`navigation`](/en-US/docs/Web/CSS/@view-transition#navigation) descriptor
Maybe we can drop the descriptor since this at-rule has just this one? The heading in that case can be just "At-rules"

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +### Selectors
Pseudo-elements?

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +> The CSS view transitions module also defines two additional pseudo-class, `:active-view-transition` and the functional pseudo-classs `:active-view-transition-type()`, which are not yet supported in
```suggestion
> The module defines the pseudo-classes `:active-view-transition` and `:active-view-transition-type()`, but they are currently not supported in any browser.
```

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +  - : Create view transitions and customize transition animations, including manipulating active view transitions.
```suggestion
  - : Explains how to create view transitions and customize transition animations, including manipulating active view transitions.
```

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +- [Web animations API](/en-US/docs/Web/API/Web_Animations_API)
```suggestion
- [CSS animations](/en-US/docs/Web/CSS/CSS_animations) module:

  - {{cssxref("animation")}} property
  - {{cssxref("@keyframes")}} at-rule
  - {{domxref("CSSKeyframesRule")}} interface
  - {{domxref("CSSStyleRule")}} interface
  - [Web animations API](/en-US/docs/Web/API/Web_Animations_API)
```

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("transform-function")}}
similar indentation, colon, and adjectives for the items in the list

2024-07-30 02:18 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("::view-transition-old()")}}
all experimental

2024-08-01 07:58 UTC, bsmth commented
Dipika's got this one, so I'm removing myself from the review for now!

2024-08-05 16:31 UTC, estelle reviewed
@dipikabh 
Thanks!

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +The **CSS view transitions** module defines the [View Transition API](/en-US/docs/Web/API/View_Transitions_API), along with associated properties and pseudo-elements, which allows developers to creat
updated

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("view-transition-name")}}
updated

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +  - [`navigation`](/en-US/docs/Web/CSS/@view-transition#navigation) descriptor
keeping as we want to list everything

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +### Selectors
Good catch. changed to selectors and pseudo elements

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("::view-transition-old()")}}
done

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +> The CSS view transitions module also defines two additional pseudo-class, `:active-view-transition` and the functional pseudo-classs `:active-view-transition-type()`, which are not yet supported in
went with 

> This module also defines the `:active-view-transition` and `:active-view-transition-type()`  pseudo-classes, but they are currently not supported in any browser.

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +  - : Create view transitions and customize transition animations, including manipulating active view transitions.
updated

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +- [Web animations API](/en-US/docs/Web/API/Web_Animations_API)
updated

2024-08-05 16:31 UTC, estelle commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("transform-function")}}
done

2024-08-06 15:48 UTC, dipikabh commented on files/en-us/web/css/css_view_transitions/index.md
> +- {{cssxref("view-transition-name")}}
thanks

2024-08-06 15:53 UTC, dipikabh approved these changes
Thanks, @estelle.

2024-08-06 15:53 UTC, merged