fix(css): update animation tips page
mdn/content pull request #34827
Opened 2024-07-13 09:09 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/18869

There is no need to use tricks to achieve the discussed tips on the page. As we have to resort to JS then the Web animation API is the best way to achieve this. The new API also makes the examples simple.

The PR uses `element.animate()` and `element.getAnimations()` method in the examples.

2024-07-16 01:48 UTC, estelle requested changes
the edits convert this CSS animation tips page to a web animations API guide. As this is a CSS tips and tricks page, not a web animations API page, I think we should keep keyframe animations in the page rather than create animations with JS. Alternatively, we can remove much of the content here and move it to the API section.

2024-07-16 01:48 UTC, estelle commented on files/en-us/web/css/css_animations/tips/index.md
> +The [CSS Animations](/en-US/docs/Web/CSS/CSS_animations) specification doesn't offer a way to run an animation again. You can't just set the element's {{cssxref("animation-play-state")}} to `"running
```suggestion
The [CSS Animations](/en-US/docs/Web/CSS/CSS_animations) specification doesn't offer a way to run an animation again. You can't just set the element's {{cssxref("animation-play-state")}} to `"running"` again. Instead, you have to use JavaScript to get a completed animation to replay.
```
"paused" and "stopped" are synonyms, so you can get a stopped animation to continue, but you can't get a completed one to restart, unless you change the class name or animation name, and likely other JS updating dom ways.

2024-07-16 01:48 UTC, estelle commented on files/en-us/web/css/css_animations/tips/index.md
> +The `playAnimation` method simply calls {{domxref("Element.animate()")}} method on the box to play the animation. The `animate` method takes the `colorChangeFrames` keyframe object and animation dura
```suggestion
The `playAnimation` method calls {{domxref("Element.animate()")}} method on the box to play the animation. The `animate` method takes the `colorChangeFrames` keyframe object and animation duration as arguments.
```
avoid calling things "simple" because it may not be for a reader.

2024-07-16 01:48 UTC, estelle commented on files/en-us/web/css/css_animations/tips/index.md
> +In the previous example if the run button is clicked before the animation is completed, then the current animation is stopped abruptly and the next animation starts from the start. If instead, you'd
```suggestion
In the previous example, if the run button is clicked before the animation is completed, the current animation will abruptly stop and the animation restarts from the `0%` or `from` starting keyframe. If you would like the current animation iteration to be complete before starting a new one, we can disable the `run` button while the animation is running, reenabling it based on the `animationend` event. Alternatively, if we want to enable multiple iterations of the animation, we can check to see if an animation is running on the element and increment the `animation-iteration` count for each button click while the animation is running.
```
this is more of a suggestion as to how to keep this relevant to CSS animations; if we opt to keep this content in the CSS section. it's not reflective of the rest of the content on this page; which is more animation API content..

2024-07-16 07:59 UTC, OnkarRuikar commented
We don't have to resort to/suggest tricks if better ways are available. Unfortunately, the Web Animation API went completely separate ways and it doesn't gel with CSS animations. Web Animation API uses `finish` event rather than `animationend` :(

I've filed [an issue](https://github.com/w3c/csswg-drafts/issues/10570#issuecomment-2227210634) to make the legacy CSS stylesheet-defined animations work with Web Animation API.

> Alternatively, we can remove much of the content here and move it to the API section.

Moved the page to the Web Animation API content area.

2024-08-08 06:18 UTC, estelle reviewed
Apologies. I had reviewed this prior to going on vacation, but I forgot to submit the review.

2024-08-08 06:18 UTC, estelle commented on files/en-us/web/api/web_animations_api/tips/index.md
> +In the case of the `animation-fill-mode` [forwards](/en-US/docs/Web/CSS/animation-fill-mode#forwards) value, animated properties behave as if included in a set [`will-change`](/en-US/docs/Web/CSS/wil
Are these one, two, or three different issues? the first sentence is about animation-fill-mode (AFM) and "will-change", but the thoughts don't seem connected. The second sentence is about new stacking context ( and AFM, but AFM isn't mentioned) but seems like it's a continuation of will change? Maybe:
```suggestion
In the case of the `animation-fill-mode: forwards`](/en-US/docs/Web/CSS/animation-fill-mode#forwards), properties remain at their final keyframe state after the animation is finished. If a new stacking context is created during the animation and is still present at the end of the animation, the target element retains the stacking context after the animation has finished. 

Another thing to note is that the properties that are animated during a CSS animation behave as if the property were included in [`will-change`](/en-US/docs/Web/CSS/will-change) property declaration. For example, if an at-keyframe animation includes the `color` and `transform` properties, the properties behave as if `will-change: color, transform` were set during the entirety of the animation, and will therefore continue to apply to the element if `animation-fill-mode` is set to `forwards` or `both`.
```
i am not sure if the above is correct, but just trying to understand what you meant.

2024-08-08 06:18 UTC, estelle commented on files/en-us/web/api/web_animations_api/tips/index.md
> +- [Animation Interface](/en-US/docs/Web/API/Animation/Animation)
```suggestion
- [Animation Interface](/en-US/docs/Web/API/Animation/Animation)
- [CSS animations](/en-US/docs/Web/CSS/CSS_animations) module
```

2024-08-08 06:18 UTC, estelle commented on files/en-us/web/css/css_animations/index.md
> +  - : Entry point to perform advanced animations using Web Animations API.
```suggestion
  - : Common animation requirements that can be solved with a few lines of JavaScript.
```
Not sure if mine is the best intro, but not sure people will know what "entry point" means, and the "advanced" seems scary, especially since it's not super advanced.

2024-08-08 09:07 UTC, OnkarRuikar commented on files/en-us/web/api/web_animations_api/tips/index.md
> +In the case of the `animation-fill-mode` [forwards](/en-US/docs/Web/CSS/animation-fill-mode#forwards) value, animated properties behave as if included in a set [`will-change`](/en-US/docs/Web/CSS/wil
```suggestion
In the case of the [`animation-fill-mode: forwards`](/en-US/docs/Web/CSS/animation-fill-mode#forwards), the animated properties remain at their final keyframe state after the animation is finished. If a new stacking context is created during the animation and is still present at the end of the animation, the target element retains the stacking context after the animation has finished. This is because the properties that are animated during a CSS animation behave as if the property were included in [`will-change`](/en-US/docs/Web/CSS/will-change) property declaration.
```

2024-08-08 17:19 UTC, estelle commented on files/en-us/web/api/web_animations_api/tips/index.md
> +In the case of the [`animation-fill-mode: forwards`](/en-US/docs/Web/CSS/animation-fill-mode#forwards), the animated properties remain at their final keyframe state after the animation is finished. T
```suggestion
In the case of [`animation-fill-mode: forwards`](/en-US/docs/Web/CSS/animation-fill-mode#forwards) (and `both`), the animated properties remain at their final keyframe state after the animation is finished. The properties keep the `will-change` status, so if a new stacking context is created during the animation and is still present at the end of the animation, the target element retains the stacking context after the animation has finished.
```

2024-08-08 17:19 UTC, estelle approved these changes
Thanks! 🎉

2024-08-08 18:46 UTC, merged

2024-08-08 19:20 UTC, Josh-Cena commented on files/en-us/web/css/css_animations/index.md
> +- - [Using the Web Animations API](/en-US/docs/Web/API/Web_Animations_API/Using_the_Web_Animations_API)
Typo here; can either of you send a follow up?