Updated the menu entry Firefox 87.0 compatible
mdn/content pull request #3484
Opened 2021-03-25 06:34 UTC by CreaTorAlexander

Fixes #3474

2021-03-25 07:26 UTC, chrisdavidmills requested changes
Thanks @CreaTorAlexander ; small nitpick to consider here.

2021-03-25 07:26 UTC, chrisdavidmills commented on files/en-us/tools/index.html
> +<p>You can open the Firefox Developer Tools from the menu by selecting <em>Tools</em> &gt; <em>Web Developer</em> &gt; <em>Web Developer Tools</em> or use the keyboard shortcut  <kbd>Ctrl</kbd> + <kb
On my mac at least, the second menu level is labeled "Browser Tools", not "Web Developer". What does it say on yours, @CreaTorAlexander ?

2021-03-25 08:41 UTC, CreaTorAlexander commented on files/en-us/tools/index.html
> +<p>You can open the Firefox Developer Tools from the menu by selecting <em>Tools</em> &gt; <em>Web Developer</em> &gt; <em>Web Developer Tools</em> or use the keyboard shortcut  <kbd>Ctrl</kbd> + <kb
I am currently on a linux machine and I can confirm that it has changed from *Toggle Tools* to *Web Developer Tools* there.
Later on I will check it on my mac. :+1:

2021-03-25 20:25 UTC, CreaTorAlexander commented on files/en-us/tools/index.html
> +<p>You can open the Firefox Developer Tools from the menu by selecting <em>Tools</em> &gt; <em>Web Developer</em> &gt; <em>Web Developer Tools</em> or use the keyboard shortcut  <kbd>Ctrl</kbd> + <kb
On my mac it is also *Web Developer Tools in Version 87*
![Bildschirmfoto 2021-03-25 um 21 25 52](https://user-images.githubusercontent.com/44900696/112538927-aeb83380-8db0-11eb-97bc-02d79b96b428.png)

2021-05-21 02:19 UTC, hamishwillee commented on files/en-us/tools/index.html
> +<p>You can open the Firefox Developer Tools from the menu by selecting <em>Tools</em> &gt; <em>Web Developer</em> &gt; <em>Web Developer Tools</em> or use the keyboard shortcut  <kbd>Ctrl</kbd> + <kb
This is correct from FF87, which is now merged. Thanks @CreaTorAlexander - I recently also updated https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox#toolbox with this info.

2021-05-21 02:20 UTC, hamishwillee approved these changes

2021-05-21 02:20 UTC, merged