FF129 Relnote: RTCDTMFSender.canInsertDTMF supported
mdn/content pull request #34862
Opened 2024-07-16 04:06 UTC by hamishwillee

FF129 supports [`RTCDTMFSender.canInsertDTMF`](https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/canInsertDTMF) in https://bugzilla.mozilla.org/show_bug.cgi?id=1623193

This adds a release note, as well as minor updates to docs for `RTCDTMFSender.insertDTMF()` (layout only) and to duplicate some example code.

Related docs work can be tracked in #34699

2024-07-31 00:28 UTC, dipikabh requested changes
Thanks for these updates, @hamishwillee. I've added some comments and suggestions for possible improvements.

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +The **`insertDTMF()`** method on the {{domxref("RTCDTMFSender")}} interface starts sending {{Glossary("DTMF")}} tones to the remote peer over the {{domxref("RTCPeerConnection")}}.
```suggestion
The **`insertDTMF()`** method of the {{domxref("RTCDTMFSender")}} interface initiates the sending of {{Glossary("DTMF")}} tones to the remote peer over the {{domxref("RTCPeerConnection")}}.
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +Sending of the tones is performed asynchronously, with [`tonechange`](/en-US/docs/Web/API/RTCDTMFSender/tonechange_event) events sent to the `RTCDTMFSender` every time a tone starts or ends.
```suggestion
Tones are sent asynchronously. Every time a tone starts or ends, a [`tonechange`](/en-US/docs/Web/API/RTCDTMFSender/tonechange_event) event is sent to the `RTCDTMFSender` .
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +As long as the connection is active, you can send tones at any time. Calling `insertDTMF()` replaces any already-pending tones from the `toneBuffer`.
Making this more direct
```suggestion
You can call `insertDTMF()` at any time while the connection is active. Each call to `insertDTMF()` replaces any pending tones in the `toneBuffer`.
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +    A "," character inserts a two second delay.
```suggestion
    A "," character inserts a two-second delay.
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +    The browser will enforce a minimum value of 30 ms (that is, if you specify a lower value, 30 ms will be used instead); the default is 70 ms.
```suggestion
    The browser will enforce a minimum value of 30 ms (that is, if you specify a lower value, 30 ms will be used instead). The default is 70 ms.
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +  - : Thrown if the DTMF tones couldn't be sent because the track has been stopped or is in a read-only or inactive state.
```suggestion
  - : Thrown if the DTMF tones cannot be sent because the track has been stopped or is in a read-only or inactive state.
```

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
>  ## Examples
Similar changes can be applied here if updating in `canInsertDTMF`. The phrasing here can focus on the use of `insertDTMF()`.

2024-07-31 00:28 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +Since `insertDTMF()` replaces the tone buffer, in order to add to the DTMF tones being played, it is necessary to call `insertDTMF` with a string containing both the remaining tones (stored in the `t
```suggestion
Since `insertDTMF()` replaces the tone buffer, in order to add to the DTMF tones being played, it is necessary to call `insertDTMF()` with a string containing both the remaining tones (stored in the `toneBuffer`) and the new tones appended together.
```

2024-07-31 12:25 UTC, bsmth commented
It looks like Dipika's got this one so I'm removing myself from reviewers for now.

2024-08-02 03:53 UTC, hamishwillee commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +The **`insertDTMF()`** method on the {{domxref("RTCDTMFSender")}} interface starts sending {{Glossary("DTMF")}} tones to the remote peer over the {{domxref("RTCPeerConnection")}}.
```suggestion
The **`insertDTMF()`** method of the {{domxref("RTCDTMFSender")}} interface sends {{Glossary("DTMF")}} tones to the remote peer over the {{domxref("RTCPeerConnection")}}.
```

2024-08-02 04:27 UTC, hamishwillee commented on files/en-us/web/api/rtcdtmfsender/caninsertdtmf/index.md
I'm always in two minds whether it is worth adding a heading when there is really only one example you can show. On the other hand, does no harm.

2024-08-02 04:30 UTC, hamishwillee commented on files/en-us/web/api/rtcdtmfsender/caninsertdtmf/index.md
>    const duration = 500;
In real code it makes sense to log the error cases but not success case. If this was a live example then I might show both, but not for a code fragment people might copy.

2024-08-02 04:37 UTC, hamishwillee commented
Thanks very much @dipikabh - I accepted most of the suggestions, or added reasons in the cases of "why not". Should be good for another look.

2024-08-02 15:43 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/caninsertdtmf/index.md
:). I do have some background on this requirement. Will and I worked on it some time back where he updated all the template guidelines (like this [one](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/API_property_subpage_template#examples)) to define that each example (even if there's one) should have an H3 descriptive heading. My reasoning is that after we do get H3 support in page TOC, it should be easy to scan what the example is about from the TOC. This would definitely help when there are more examples and readers can directly go to the one they're interested in, and so it was essential to standardize that all examples should have an H3 so as not to leave it to a subjective opinion.

2024-08-02 17:21 UTC, dipikabh approved these changes
It's looking good, thanks @hamishwillee.
There's just one typo and one suggestion. But leaving a +1 so you can merge when ready.

2024-08-02 17:21 UTC, dipikabh commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +    A "," character inserts a two-second delay.
Re-reading this and I think we can probably add a bit more explanation. Something along these lines...
```suggestion
    A comma character `,` in the string inserts a two-second delay. For example `"12,34"` will send tones for `1` and `2`, pause for two seconds, and then send `3` and `4`. Multiple commas add a longer delay, so `,,` will add four seconds.
```

2024-08-05 00:16 UTC, hamishwillee commented on files/en-us/web/api/rtcdtmfsender/insertdtmf/index.md
> +    A "," character inserts a two-second delay.
Sure. I didn't actually subedit any of these - just removed the odd line breaks. This is definitely helpful though, IMO

2024-08-05 00:22 UTC, merged