Native_manifests: pkcs11 paths may be relative
mdn/content pull request #34873
Opened 2024-07-16 17:52 UTC by Rob--W

### Description

Clarifies that the "path" property in pkcs11 manifests can be relative, everywhere.

And prepend "PKCS 11" to "module" to emphasize that this fragment of the table is about the manifests for the pkcs11 API, to avoid confusion in case the reader was looking for the native messaging manifest.

### Motivation

The documentation incorrectly claims that the path has to be absolute.

### Additional details

Undocumented support for relative paths existed for a long while, and became an explicit first-class supported feature in https://bugzilla.mozilla.org/show_bug.cgi?id=1759162

### Related issues and pull requests

2024-07-16 23:58 UTC, dotproto approved these changes
LGTM

2024-07-22 02:28 UTC, rebloor requested changes

2024-07-22 02:28 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/native_manifests/index.md
> +          The path to the PKCS #11 module may be absolute, or relative to the manifest itself.
```suggestion
          The path to the PKCS #11 module may be absolute or relative to the manifest itself.
```

2024-08-07 08:43 UTC, Rob--W commented
@rebloor I've applied the requested change (removed comma) and rebased to the main branch just in case.

2024-08-08 17:51 UTC, rebloor approved these changes

2024-08-08 17:51 UTC, merged