New property: SVG rx
mdn/content pull request #34892
Opened 2024-07-18 04:16 UTC by estelle

related to https://github.com/mdn/content/issues/34763

2024-07-18 14:05 UTC, chrisdavidmills requested changes
@estelle nice work as always; couple of bits that need looking at here. 

Also, most of the comments I made on the `rx` page apply to the `ry` page too. Have a look at both as you go through and make the changes.

I made a couple of additional comments on the `ry` page.

2024-07-18 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/rx/index.md
> +  fill: magenta;
Interesting; in Firefox, you don't see the colored ellipses rendered; you do in Chrome. Worth mentioning at all?

2024-07-18 14:05 UTC, chrisdavidmills commented on files/en-us/web/css/ry/index.md
> +- Geometrx properties: `ry`, {{cssxref("cx")}}, {{cssxref("cy")}}, {{cssxref("r")}}, {{cssxref("rx")}}, {{cssxref("x")}}, {{cssxref("y")}}, {{cssxref("height")}}, {{cssxref("height")}}
```suggestion
- Geometry properties: `ry`, {{cssxref("cx")}}, {{cssxref("cy")}}, {{cssxref("r")}}, {{cssxref("rx")}}, {{cssxref("x")}}, {{cssxref("y")}}, {{cssxref("height")}}, {{cssxref("height")}}
```

2024-07-18 18:05 UTC, estelle commented on files/en-us/web/css/ry/index.md
> +- Geometrx properties: `ry`, {{cssxref("cx")}}, {{cssxref("cy")}}, {{cssxref("r")}}, {{cssxref("rx")}}, {{cssxref("x")}}, {{cssxref("y")}}, {{cssxref("height")}}, {{cssxref("height")}}
LOL. oops, got overzealous with  replacing ry with rx

2024-07-18 18:20 UTC, estelle reviewed
Thanks @chrisdavidmills

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +The **`rx`** [CSS](/en-US/docs/Web/CSS) property defines the x-axis, or horizontal, radius of an SVG {{SVGElement("ellipse")}} and the horizontal curve of the corners of the SVG {{SVGElement("rect")}
kept the note below and removed the sentence instead.

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +> [!NOTE]
kept note, removing the sentence from the property summary first paragraph

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +/* initial value */
updated

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +/* length and percentage values */
updated

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +The {{cssxref("length-percentage")}} property value denotes the horizontal radius of ellipses and the horizontal border-radius of rectangles.
changed to:

> The {{cssxref("length")}}, {{cssxref("percentage")}}, or `auto` keyword value denotes ....

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +  - : As an absolute or relative length, it can be expressed in any unit allowed by the CSS {{cssxref("&lt;length&gt;")}} data type. Unitless and `px` values are SVG coordinate units if the {{SVGAttr
updated

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +This example demonstrates the effects of the viewBox attribute on unitless `rx` value declaration.
updated

2024-07-18 18:20 UTC, estelle commented on files/en-us/web/css/ry/index.md
> +We include an SVG image with four `<rect>` elements; all the rectangles are the same except for their {{SVGAttr("x")}} attribute value, which positions them along the y-axis.
good catch. updated.

2024-07-18 18:52 UTC, estelle commented on files/en-us/web/css/rx/index.md
> +  fill: magenta;
this seems to be FF not supporting pseudo-classes in SVGs. That's a bug. diving deeper.

2024-07-19 08:52 UTC, chrisdavidmills commented on files/en-us/web/css/rx/index.md
> +The **`rx`** [CSS](/en-US/docs/Web/CSS) property defines the x-axis, or horizontal, radius of an SVG {{SVGElement("ellipse")}} and the horizontal curve of the corners of the SVG {{SVGElement("rect")}
Looks fine.

2024-07-19 08:54 UTC, chrisdavidmills commented on files/en-us/web/css/rx/index.md
> +The {{cssxref("length-percentage")}} property value denotes the horizontal radius of ellipses and the horizontal border-radius of rectangles.
This works well.

2024-07-19 08:57 UTC, chrisdavidmills approved these changes
Superb work @estelle. This all looks great. and I agree with removing the example based on buggy/inconsistent feature for now. It would confuse several people. And we have enough examples to be going on with.

2024-07-19 08:58 UTC, merged