Added text-anchor property
mdn/content pull request #35167
Opened 2024-07-26 19:59 UTC by meyerweb

### Description

Adds documentation of the CSS property `text-anchor`, which replicates an SVG attribute.

### Motivation

The page currently doesn’t exist, and it needs to be created (see https://github.com/mdn/content/issues/34763).

2024-07-26 20:01 UTC, Josh-Cena commented on files/en-us/web/svg/attribute/text-anchor/index.md
> +## See Also
This comes after browser compat and "also" should be lowercase

2024-07-29 12:24 UTC, meyerweb commented on files/en-us/web/svg/attribute/text-anchor/index.md
> +## See Also
Fixed.

2024-08-01 11:53 UTC, bsmth requested changes
Thank you! All good except for the `CSSInfo` issue. Either we omit it or add an entry to `mdn/data`.

2024-08-02 02:49 UTC, meyerweb commented
> Thank you! All good except for the `CSSInfo` issue. Either we omit it or add an entry to `mdn/data`.

Per [Josh-Cena’s comment in 35107](https://github.com/mdn/content/pull/35107#issuecomment-2263714975), these should stay even if broken.  (This is the case on several other CSS pages, in fact.)  I can look into adding the information to `mdn/data` when I return from holiday, but in the meantime I believe this can be merged.

2024-08-02 08:16 UTC, bsmth commented
> > Thank you! All good except for the `CSSInfo` issue. Either we omit it or add an entry to `mdn/data`.
> 
> Per [Josh-Cena’s comment in 35107](https://github.com/mdn/content/pull/35107#issuecomment-2263714975), these should stay even if broken. (This is the case on several other CSS pages, in fact.) I can look into adding the information to `mdn/data` when I return from holiday, but in the meantime I believe this can be merged.

OK got it. I've opened a tracker in mdn/data so we don't forget!

2024-08-02 08:17 UTC, bsmth approved these changes
Thanks, Eric!

2024-08-02 08:56 UTC, merged