New page: stop-opacity property
mdn/content pull request #35170
Opened 2024-07-26 21:21 UTC by estelle

part of https://github.com/mdn/content/issues/34763

2024-08-01 11:55 UTC, bsmth commented on files/en-us/web/css/stop-color/index.md
> +> The `stop-color` property only applies to {{SVGElement('stop')}} element nested in an {{SVGElement("svg")}}. It doesn't apply other SVG, HTML, or pseudo-elements.
```suggestion
> The `stop-color` property only applies to {{SVGElement('stop')}} elements nested in an {{SVGElement("svg")}}. It doesn't apply to other SVG, HTML, or pseudo-elements.
```

2024-08-01 11:56 UTC, bsmth commented on files/en-us/web/css/stop-color/index.md
> +{{CSSInfo}}
This macro is broken here.

2024-08-01 11:57 UTC, bsmth commented on files/en-us/web/css/stop-color/index.md
> +We have an SVG with three {{SVGElement("rect")}} squares and three almost identical {{SVGElement("linearGradient")}} elements. Each gradient has four {{SVGElement("stop")}} elements creating gradient
```suggestion
We have an SVG with three {{SVGElement("rect")}} squares and three {{SVGElement("linearGradient")}} elements. Each gradient has four {{SVGElement("stop")}} elements creating gradients that go from black to white and then white to grey; the only difference between them is the `id` value.
```

2024-08-01 11:59 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +> The `stop-opacity` property only applies to {{SVGElement('stop')}} element nested in an {{SVGElement("svg")}}. It doesn't apply other SVG, HTML, or pseudo-elements.
```suggestion
> The `stop-opacity` property only applies to {{SVGElement('stop')}} elements nested in an {{SVGElement("svg")}}. It doesn't apply to other SVG, HTML, or pseudo-elements.
```

2024-08-01 12:02 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +The property value impacts the `stop-color`'s alpha channel; it can increase the transparency of a `<stop>`'s color but can not make the color defined by the `color-stop` property more opaque.
Can we link them?

```suggestion
The property value impacts the {{cssxref("stop-color")}}'s alpha channel; it can increase the transparency of a `<stop>`'s color but can not make the color defined by the `color-stop` property more opaque.
```

2024-08-01 12:03 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +The property value impacts the `stop-color`'s alpha channel; it can increase the transparency of a `<stop>`'s color but can not make the color defined by the `color-stop` property more opaque.
Also we have `color-stop` and `stop-color`, it would be good to disambiguate when they're so close together in prose.

2024-08-01 12:04 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +{{CSSInfo}}
Same issue with the broken macro here

2024-08-01 12:04 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +We have an SVG with a few {{SVGElement("polygon")}} stars and three almost identical {{SVGElement("linearGradient")}} elements: each has three {{SVGElement("stop")}} elements defining three color-sto
```suggestion
We have an SVG with a few {{SVGElement("polygon")}} stars and three {{SVGElement("linearGradient")}} elements: each has three {{SVGElement("stop")}} elements defining three color-stops that create a gradient going from blue to white to pink; the only difference between them is the `id` value.
```

2024-08-01 12:05 UTC, bsmth commented on files/en-us/web/css/stop-opacity/index.md
> +Each `polygon` has a gradient background set using the {{cssxref("fill")}} property; the gradient's`id` is the `url()` parameter. We set `magenta` as the fallback color.
```suggestion
Each `polygon` has a gradient background set using the {{cssxref("fill")}} property; the gradient's `id` is the `url()` parameter. We set `magenta` as the fallback color.
```

2024-08-01 12:06 UTC, bsmth commented
Thanks! Back over to you, Estelle if you want to have a look at the comments.

2024-08-02 14:39 UTC, chrisdavidmills requested changes
@estelle a few more bits for you to consider

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +  - : The color of the fill as any valid CSS {{cssxref("color_value", "&lt;color>")}} value.
```suggestion
  - : The color of the fill. This can be any valid CSS {{cssxref("color_value", "&lt;color>")}} value.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +We include a {{cssxref("stroke")}} and {{cssxref("stroke-width")}} outlining the rectangle. We define the colors of the first and last stops in each gradient, overriding their `stop-color` attribute
```suggestion
We include a {{cssxref("stroke")}} and {{cssxref("stroke-width")}} outlining the rectangle. We define the colors of the first and last stops in each gradient, overriding their `stop-color` attribute values using the `stop-color` property. Various different CSS {{cssxref("color_value", "&lt;color>")}} syntaxes are shown.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The **`stop-opacity`** [CSS](/en-US/docs/Web/CSS) property the opacity of a given color gradient stop in the SVG {{SVGElement("stop")}} element. If present, it overrides the element's {{SVGAttr("stop
```suggestion
The **`stop-opacity`** [CSS](/en-US/docs/Web/CSS) property defines the opacity of a given SVG {{SVGElement("stop")}} element within a gradient. If present, it overrides the element's {{SVGAttr("stop-opacity")}} attribute.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The `<opacity-value>` is a {{cssxref("number")}} and {{cssxref("percentage")}} denoting the opacity of the SVG gradient `<stop>` element.
```suggestion
The `<opacity-value>` is a {{cssxref("number")}} or {{cssxref("percentage")}} denoting the opacity of the SVG gradient `<stop>` element.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +With `0` or `0%`, the stop is fully transparent (that is, invisible). With `1` or `100%`, the element is the full opacity of the `stop-color` value; which may or may not be partially opaque.
```suggestion
With `0` or `0%` set, the stop is fully transparent. With `1` or `100%` set, the element is the full opacity of the `stop-color` value, which may or may not be partially opaque.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The SVG has a striped background to make translucency more apparent.
```suggestion
The SVG has a striped background to make the transparency settings more apparent.
```

2024-08-02 14:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The SVG has a striped background to make translucency more apparent.
translucency is not wrong, but I feel like transparency is more obvious/understandable.

2024-08-07 18:44 UTC, estelle commented on files/en-us/web/css/stop-opacity/index.md
> +The SVG has a striped background to make translucency more apparent.
your suggestion is WAY better.

2024-08-08 06:35 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +> The `stop-color` property only applies to {{SVGElement('stop')}} element nested in an {{SVGElement("svg")}}. It doesn't apply other SVG, HTML, or pseudo-elements.
This is done.

2024-08-08 06:35 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +We have an SVG with three {{SVGElement("rect")}} squares and three almost identical {{SVGElement("linearGradient")}} elements. Each gradient has four {{SVGElement("stop")}} elements creating gradient
This is done.

2024-08-08 06:36 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +> The `stop-opacity` property only applies to {{SVGElement('stop')}} element nested in an {{SVGElement("svg")}}. It doesn't apply other SVG, HTML, or pseudo-elements.
@estelle the "to" near the end of the sentence still needs to be added.

2024-08-08 06:37 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The property value impacts the `stop-color`'s alpha channel; it can increase the transparency of a `<stop>`'s color but can not make the color defined by the `color-stop` property more opaque.
This is fixed. They were both supposed to be `stop-color`, which has been updated.

2024-08-08 06:38 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +We have an SVG with a few {{SVGElement("polygon")}} stars and three almost identical {{SVGElement("linearGradient")}} elements: each has three {{SVGElement("stop")}} elements defining three color-sto
This is done.

2024-08-08 06:38 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +Each `polygon` has a gradient background set using the {{cssxref("fill")}} property; the gradient's`id` is the `url()` parameter. We set `magenta` as the fallback color.
This is done.

2024-08-08 06:39 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +  - : The color of the fill as any valid CSS {{cssxref("color_value", "&lt;color>")}} value.
This hasn't been applied @estelle; did you disagree with it?

2024-08-08 06:40 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +We include a {{cssxref("stroke")}} and {{cssxref("stroke-width")}} outlining the rectangle. We define the colors of the first and last stops in each gradient, overriding their `stop-color` attribute
This is done.

2024-08-08 06:41 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The **`stop-opacity`** [CSS](/en-US/docs/Web/CSS) property the opacity of a given color gradient stop in the SVG {{SVGElement("stop")}} element. If present, it overrides the element's {{SVGAttr("stop
done

2024-08-08 06:42 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +The `<opacity-value>` is a {{cssxref("number")}} and {{cssxref("percentage")}} denoting the opacity of the SVG gradient `<stop>` element.
done

2024-08-08 06:42 UTC, chrisdavidmills commented on files/en-us/web/css/stop-opacity/index.md
> +With `0` or `0%`, the stop is fully transparent (that is, invisible). With `1` or `100%`, the element is the full opacity of the `stop-color` value; which may or may not be partially opaque.
done

2024-08-08 06:44 UTC, estelle commented on files/en-us/web/css/stop-color/index.md
> +  - : The color of the fill as any valid CSS {{cssxref("color_value", "&lt;color>")}} value.
No. I just missed it ;)

2024-08-08 06:46 UTC, chrisdavidmills approved these changes
@estelle there are a couple of bits that I noticed were not actioned, which I've commented, however, these are really minor, so I've approved the PR.

2024-08-08 06:46 UTC, estelle commented on files/en-us/web/css/stop-opacity/index.md
> +> The `stop-opacity` property only applies to {{SVGElement('stop')}} elements nested in an {{SVGElement("svg")}}. It doesn't apply other SVG, HTML, or pseudo-elements.
```suggestion
> The `stop-opacity` property only applies to {{SVGElement('stop')}} elements nested in an {{SVGElement("svg")}}. It doesn't apply to other SVG, HTML, or pseudo-elements.
```

2024-08-08 06:48 UTC, estelle commented on files/en-us/web/css/stop-opacity/index.md
> +{{CSSInfo}}
PR has been filed on MDN/data - https://github.com/mdn/data/pull/753

2024-08-08 06:48 UTC, chrisdavidmills commented on files/en-us/web/css/stop-color/index.md
> +  - : The color of the fill as any valid CSS {{cssxref("color_value", "&lt;color>")}} value.
Ah, no worries. This is fixed, now, so resolving.

2024-08-08 06:49 UTC, merged