fix(css): add linear() function to the values section
mdn/content pull request #35240
Opened 2024-07-30 10:35 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/35187

2024-08-02 13:39 UTC, chrisdavidmills requested changes
@OnkarRuikar some comments for your consideration. Good work overall.

2024-08-02 13:39 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +/* Cubic-bezier value */
It also seems weird to only provide a single cubic-bezier() example, when the other functions have multiple examples. Provide a couple more?

2024-08-02 13:39 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +      - : The function interpolates linearly between the provided easing stop points. A stop point is a pair of an output progress and an input percentage. The input percentage is optional, and if th
How is it inferred? What values are inferred if you specify percentages on some pairs and not others?

2024-08-02 13:39 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +.jump-start {
I'm not convinced you need to show the `animation-timing-function` CSS for the step examples. You don't show it for the other examples.

A few thoughts:

1. It would be good to add a paragraph to each example section explaining what the example is doing in each case.
2. It would be good to set `animation-direction: alternate` in each case so you can see the animations moving backwards and forwards. At the moment they are a bit jarring.
3. In the `linear()` function examples, it is great how you've included the little graph behind the animated lines so you can see where 0%, 25%, 50%, etc., of the animation is. At least I'm assuming that's what it is! Add labels to the vertical lines so it is clear what they represent. Also, include the graph on all the examples?
4. On all the examples, add a bit of padding to each animated line and give the text code font and a white text shadow, to make them easier to read?

2024-08-03 11:59 UTC, OnkarRuikar commented on files/en-us/web/css/animation-timing-function/index.md
> +.jump-start {
> I'm not convinced you need to show the `animation-timing-function` CSS for the step examples. 

I have hidden it.

> 2. It would be good to set animation-direction: alternate in each case so you can see the animations moving backwards and forwards. At the moment they are a bit jarring.

Reverse animation makes it hard to understand `ease-in`, `ease-out`, `start`, and `end`. I've changed the animation  fill mode to `forwards` and made animation play on click of a button. Now step `end` value is demoed accurately.

> 3. In the linear() function examples, it is great how you've included the little graph behind the animated lines so you can see where 0%, 25%, 50%, etc., of the animation is. At least I'm assuming that's what it is! Add labels to the vertical lines so it is clear what they represent. Also, include the graph on all the examples?

Yes, the markings have been used to show animation stop points. Implemented all the suggestions.

> 4. On all the examples, add a bit of padding to each animated line and give the text code font and a white text shadow, to make them easier to read?

White shadow isn't working. Changed the background color from magenta to orange.

> 1. It would be good to add a paragraph to each example section explaining what the example is doing in each case.

Working on it.

2024-08-19 14:38 UTC, chrisdavidmills requested changes
@OnkarRuikar excellent work, this is much improved! I had a few more language nitpicks for you to go through, but nothing major.

2024-08-19 14:38 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +The example demonstrates `linear()` easing.
```suggestion
The example demonstrates the effects of various `linear()` easing functions.
```

2024-08-19 14:38 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +The following image shows graphs of all the `linear()` function values used in this example. Time(input) is plotted on the x-axis and the output is on the y-axis. As per the syntax, the input(time) r
```suggestion
The following image shows graphs of all the `linear()` function values used in this example. Input progress (time) is plotted on the x-axis and output progress is plotted on the y-axis. As per the syntax, the input progress ranges from 0 to 100%, and the output ranges from 0 to 1.
```

2024-08-19 14:38 UTC, chrisdavidmills commented on files/en-us/web/css/animation-timing-function/index.md
> +The following image shows graphs of all the cubic bezier function values used in this example. The input(time) ranges from 0 to 1 and the output ranges from -∞ to ∞.
Why does the horizontal axis in this one range from 0 to 1? In the previous example, it was 0 - 100%.

2024-08-20 01:34 UTC, OnkarRuikar commented on files/en-us/web/css/animation-timing-function/index.md
> +The example demonstrates `linear()` easing.
```suggestion
The example demonstrates the effects of various `linear()` easing function values.
```

2024-08-20 01:52 UTC, OnkarRuikar commented
@chrisdavidmills, thanks for the review!

> Why does the horizontal axis in this one range from 0 to 1? In the previous example, it was 0 - 100%.

Because the linear function accepts input progress as a percentage and the cubic bezier function accepts only numbers:
```
/* the linear function syntax can be reduced to the following */
linear( [<number> <percentage>{1,2}? ]# )
cubic-bezier( <number [0,1]> , <number> , <number [0,1]> , <number> ) 
```

2024-08-20 08:46 UTC, chrisdavidmills commented
> Because the linear function accepts input progress as a percentage and the cubic bezier function accepts only numbers:

@OnkarRuikar ok, that's totally fair. I haven't looked at these for a while ;-)

2024-08-20 08:56 UTC, chrisdavidmills approved these changes
@OnkarRuikar this looks great now; approving!

2024-08-20 09:02 UTC, merged