fix(css): font-stretch has been renamed to font-width
mdn/content pull request #35267
Opened 2024-08-01 12:24 UTC by OnkarRuikar

- related to https://github.com/mdn/content/issues/35265

2024-08-01 16:22 UTC, Josh-Cena commented
Instead of this, we should wait and properly fix this as part of https://github.com/mdn/content/issues/34347 by calling `font-stretch` a legacy alias of `font-width`.

2024-08-01 17:03 UTC, wbamberg commented
> Instead of this, we should wait and properly fix this as part of #34347 by calling `font-stretch` a legacy alias of `font-width`.

Is it worth landing some version of this though, while we wait for browsers to implement it? Because in the meantime people are confused.

2024-08-01 17:06 UTC, Josh-Cena commented
Hmmm, ok, that also sounds fine as an interim step.

2024-08-01 17:14 UTC, wbamberg commented
I suppose the difficulty with doing nothing until browsers implement this is that people will get confused by the formal syntax. But the difficulty with merging something like this PR now, is that people will get confused when they try to use `font-width` and it doesn't work. Again this is connected to MDN not being able to document features that don't have browser support.

So perhaps the best thing for now is for the note to say that browsers don't yet support the new name, and remember to update it when they do? At which point we could do https://github.com/mdn/content/issues/34347#issuecomment-2208743716 ?

2024-08-01 17:18 UTC, wbamberg commented on files/en-us/web/css/font-stretch/index.md
> +> The property [has now been renamed to `font-width`](https://drafts.csswg.org/css-fonts/#font-stretch-desc) in the specifications.
Suggestions:
- put this note at the top of the page, and explicitly say that `font-stretch` is now defined in the specifications as an alias for `font-width`, which is identical in behavior, but that the `font-width` name is not yet supported by any browsers.
- remove the pre-existing note from here
- also pass `font-width` to csssyntax, which should fix the formal syntax error.

2024-08-02 02:55 UTC, wbamberg requested changes

2024-08-02 02:55 UTC, wbamberg commented on files/en-us/web/css/font-stretch/index.md
> +> The `font-stretch` property [has now been renamed to `font-width`](https://drafts.csswg.org/css-fonts/#font-stretch-desc) in the specifications. And the `font-stretch` name remains as an alias for
```suggestion
> The `font-stretch` property [has now been renamed to `font-width`](https://drafts.csswg.org/css-fonts/#font-stretch-desc) in the specifications. The name `font-stretch` has been kept as an alias for the `font-width` property.
```

2024-08-02 02:55 UTC, wbamberg commented on files/en-us/web/css/font-stretch/index.md
> +> The new name `font-width` has not been supported by any browser yet.
```suggestion
> The new name `font-width` is not yet supported by any browsers.
```

2024-08-02 02:55 UTC, wbamberg commented on files/en-us/web/css/font-stretch/index.md
> +{{EmbedLiveSample("Setting font stretch percentages", "100%", 200)}}
Good idea, but this doesn't seem to be working in the preview. Do you want to have the font locally, as in https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#enabling_swash_glyphs, or are you supposed to load it from mdn/shared-assets?

2024-08-02 08:44 UTC, OnkarRuikar commented on files/en-us/web/css/font-stretch/index.md
> +{{EmbedLiveSample("Setting font stretch percentages", "100%", 200)}}
Yes, it's there in the shared-assets.

2024-08-03 00:28 UTC, wbamberg approved these changes
👍 thank you @OnkarRuikar !

2024-08-03 00:28 UTC, merged