Replace "ES6 In Depth: Symbols" with wayback machine link
mdn/content pull request #35295
Opened 2024-08-04 01:14 UTC by DanKaplanSES

### Description

Replace "ES6 In Depth: Symbols" with wayback machine link

- This new link is styled correctly. The one I replaced is not. 
- This is likely a bug in the original link -- https://hacks.mozilla.org/2015/06/es6-in-depth-symbols/ -- but I don't know how to contact the webmaster about it.
- Even if the problem is fixed on the original link, this new link will prevent other bugs causing problems in the future.

### Additional details

### Related issues and pull requests

2024-08-04 03:49 UTC, Josh-Cena requested changes
The original link is working:

<img width="731" alt="image" src="https://github.com/user-attachments/assets/46453cb1-ffff-4eb9-8967-d64ec2c95749">

Are there any issues?

2024-08-04 06:43 UTC, DanKaplanSES commented
Compare that same part of the page with the new link: the `<pre>` tags are styled in a more readable way.

2024-08-04 18:35 UTC, Josh-Cena commented
Thanks, but I don't think that's a  break significant enough to use wayback machine. These wayback machine links are hard to check and verify and we would not be able to restore it once it's fixed.

@Rumyra Do you know who we should contact to see if this is a Mozilla Hacks issue?

2024-08-18 21:36 UTC, DanKaplanSES commented
@Josh-Cena I completely agree! I just felt like providing the link in case nobody had the bandwidth to fix this styling issue on the other site. Thanks!

2024-08-27 04:29 UTC, Josh-Cena commented
Pinging @mdn/core-yari-content in case one of y'all know who to contact.

2024-08-27 10:20 UTC, bsmth commented
> Pinging @mdn/core-yari-content in case one of y'all know who to contact.

Taking a look into it, I'll see if we can get the formatting fixed on the original post.

2024-08-29 01:04 UTC, Josh-Cena commented
@bsmth: I think they have updated the platform but the post is now broken in another way:

<img width="398" alt="image" src="https://github.com/user-attachments/assets/c7640fda-2859-473b-bf46-2df5132b3fa0">

The emojis in code are not showing up.

2024-08-29 09:06 UTC, bsmth commented
> @bsmth: I think they have updated the platform but the post is now broken in another way:
> <img alt="image" width="398" src="https://private-user-images.githubusercontent.com/55398995/362496648-c7640fda-2859-473b-bf46-2df5132b3fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjI1ODQsIm5iZiI6MTcyNDkyMjI4NCwicGF0aCI6Ii81NTM5ODk5NS8zNjI0OTY2NDgtYzc2NDBmZGEtMjg1OS00NzNiLWJmNDYtMmRmNTEzMmIzZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTUzZjI2ZWE1OTUwYzMzNmMwZWJjZmYxOTA1YTY2ZWEzNDU0YjVkNzdkNzg1N2EwMGI5MDkyODg3MWMwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G6fo3QCLYy6SFau86TQnr-N8ZlbT8cCnWF5Bol_AMYw">
> 
> The emojis in code are not showing up.

Yes, I noticed this, and I've passed it on. I'll see if admins have bandwidth to fix 🤞🏻

2024-09-03 12:38 UTC, closed without merging

2024-09-03 12:38 UTC, bsmth commented
This is now fixed, so I'm closing the PR 👍🏻