fix em description
mdn/content pull request #35302
Opened 2024-08-04 23:15 UTC by gagan-bhullar-tech

### Description

PR fixes #35297

### Motivation

### Additional details

### Related issues and pull requests

2024-08-04 23:22 UTC, Josh-Cena requested changes
This is not what the issue asked for. You are changing the definition of `rem`, which is correctly "the root element". However there are multiple places on this page that referred to "the parent element" when talking about `em` (including here) and you need to fix those.

2024-08-04 23:38 UTC, gagan-bhullar-tech commented
> This is not what the issue asked for. You are changing the definition of `rem`, which is correctly "the root element". However there are multiple places on this page that referred to "the parent element" when talking about `em` (including here) and you need to fix those.

@Josh-Cena thanks. Updated PR.

2024-08-06 01:04 UTC, Josh-Cena requested changes

2024-08-06 01:04 UTC, Josh-Cena commented on files/en-us/learn/css/building_blocks/values_and_units/index.md
> +- `em` and `rem` are relative to the font size of its own element and the root element, respectively.
```suggestion
- `em` is relative to the font size of this element, or the font size of the parent element when used for {{cssxref("font-size")}}. `rem` is relative to the font size of the root element.
```

2024-08-06 01:04 UTC, Josh-Cena commented on files/en-us/learn/css/building_blocks/values_and_units/index.md
> +The third box uses `em` units. These are relative to its own element's font size. I've set a font size of `1em` on the containing {{htmlelement("div")}}, which has a class of `.wrapper`. Change this
```suggestion
The third box uses `em` units. These are relative to the element's font size. I've set a font size of `1em` on the containing {{htmlelement("div")}}, which has a class of `.wrapper`. Change this value to `1.5em` and you will see that the font size of all the elements increases, but only the last item will get wider, as its width is relative to that font size.
```

2024-08-06 01:04 UTC, Josh-Cena commented on files/en-us/learn/css/building_blocks/values_and_units/index.md
> +**To recap, the em unit means "my own element's font-size"** in the case of typography. The {{htmlelement("li")}} elements inside the {{htmlelement("ul")}} with a `class` of `ems` take their sizing f
```suggestion
**To recap, the `em` unit means "my parent element's font-size"** if used for `font-size` (and "my own font-size" when used for anything else). The {{htmlelement("li")}} elements inside the {{htmlelement("ul")}} with a `class` of `ems` take their sizing from their parent. So each successive level of nesting gets progressively larger, as each has its font size set to `1.3em` — 1.3 times its parent element's font size.
```

2024-08-06 01:59 UTC, Josh-Cena commented on files/en-us/learn/css/building_blocks/values_and_units/index.md
>  **To recap, the rem unit means "The root element's font-size"** (rem stands for "root em"). The {{htmlelement("li")}} elements inside the {{htmlelement("ul")}} with a `class` of `rems` take their siz
```suggestion
**To recap, the `rem` unit means "The root element's font-size"** (rem stands for "root em"). The {{htmlelement("li")}} elements inside the {{htmlelement("ul")}} with a `class` of `rems` take their sizing from the root element (`<html>`). This means that each successive level of nesting does not keep getting larger.
```

2024-08-06 02:22 UTC, Josh-Cena approved these changes
Thanks, LGTM

2024-08-06 02:23 UTC, merged