FF130 CSP report-to directive
mdn/content pull request #35331
Opened 2024-08-06 06:34 UTC by hamishwillee

FF130 supports the CPS [`report-to`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to) directive in https://bugzilla.mozilla.org/show_bug.cgi?id=1391243

I'm still working out what this means because the docs are a bit unclear/scattered - seeking confirmation of how it works (and what FF supports) in https://bugzilla.mozilla.org/show_bug.cgi?id=1391243#c11

This is draft until that happens.

Related docs work can be tracked in #35279

2024-08-12 08:29 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/index.md
> +These violation reports consist of {{Glossary("JSON")}} documents sent via an HTTP `POST` request to the specified URI.
Note, in reporting API need good link for this, and to cross link

2024-08-12 08:30 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
>  {{HTTPSidebar}}
This doc was all screwed up - it reflected the `Report-To` HTTP header, not the CSP directive.

2024-08-12 08:30 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +> [!NOTE]
Note, removed all the `Report-To` stuff other than this note. People shouldn't use it, but I wanted to make clear that it could be used, to remove misunderstandings I had from all these docs.

2024-08-12 08:32 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +> Content-Security-Policy: …; report-uri https://endpoint.example.com; report-to groupname
- [ ] Needs to be revisited. Probably should list all options here - see https://developer.chrome.com/blog/reporting-api-migration#csp_reporting_migration for inspiration

2024-08-12 08:33 UTC, hamishwillee commented on files/en-us/web/http/headers/index.md
> +  - : Response header used to specify server endpoints where the browser should send warning and error reports when using the [Reporting API)](/en-US/docs/Web/API/Reporting_API).
```suggestion
- {{HTTPHeader("Reporting-Endpoints")}}
  - : Response header used to specify server endpoints where the browser should send warning and error reports when using the [Reporting API](/en-US/docs/Web/API/Reporting_API).
- {{HTTPHeader("Report-To")}} {{deprecated_inline}} {{non-standard_inline}}
  - : Response header used to specify server endpoints where the browser should send warning and error reports when using the [Reporting API](/en-US/docs/Web/API/Reporting_API).
```

2024-08-12 08:34 UTC, hamishwillee commented on files/en-us/web/http/headers/report-to/index.md
> +---
FYI only - This is deprecated, but it still exists and lots of docs about it exist. FF also adding support in FF130. Adding to provide a clean deprecation path that matches BCD and browser reality.

2024-08-12 08:40 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +Content-Security-Policy: …; report-to <endpoint_name>
Can we have multiples of these? I mean can we report the same violations to multiple places as a backup?

2024-08-19 08:41 UTC, hamishwillee commented on files/en-us/web/api/cspviolationreportbody/index.md
> -> This interface is similar, but not identical to, the [JSON objects](/en-US/docs/Web/HTTP/CSP#violation_report_syntax) sent back to the [`report-uri`](/en-US/docs/Web/HTTP/Headers/Content-Security-P
FYI, this may have been true at some point, but not any more. From [testing](https://www.michalspacek.com/chrome-err_spdy_protocol_error-and-an-invalid-http-header#chrome-71-and-newer) I can see that the object is returned as the body of the report in the ReportObserver, or as a serialized JSON version in the `body` property of the report. 

So essentially one is an object and one is JSON, but the property names and content of stuff that is/can be serialized is the same. I have captured that.

The CSP docs will have to be updated because they still document the "similar" format for reports, where there are some casing differences in the property names.

2024-08-19 08:43 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +## Usage notes
I wanted to add this section here as a section so it can easily be deleted in future :-)

2024-08-19 08:44 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +> Content-Security-Policy: …; report-uri https://endpoint.example.com; report-to endpoint_name
Noe, it is only a groupname if you have a group, which only happens if the deprecated Report-To header is used to supply one. So this change is how it "should be" going forward.

2024-08-20 01:56 UTC, hamishwillee commented on files/en-us/web/api/cspviolationreportbody/index.md
> -> This interface is similar, but not identical to, the [JSON objects](/en-US/docs/Web/HTTP/CSP#violation_report_syntax) sent back to the [`report-uri`](/en-US/docs/Web/HTTP/Headers/Content-Security-P
I was wrong, reverting. The `report-to` uses Reporting API, while `report-uri` is used for CSP reports. They are different things, with the same info.

2024-08-20 08:11 UTC, hamishwillee commented
This is not "100%" finished, but the guts of it are - the remainder of the work that I know about can be done as a post process if this doesn't get reviewed in the next few days.
That work, specifically, is adding missing property docs for things like `CSPViolationReportBody`.

2024-08-20 11:50 UTC, chrisdavidmills requested changes
Nice work @hamishwillee. I've made several comments, but it is mostly language stuff. The intent behind the work makes a lot of sense, and it is a vast improvement.

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +A CSP violation report is a JSON-serialized version of the {{domxref("Report")}} object, with a `type` property that has a the value `"csp-violation"`, and a `body` that is the serialized form of a {
```suggestion
A CSP violation report is a JSON-serialized {{domxref("Report")}} object instance, with a `type` property that has a value of `"csp-violation"`, and a `body` that is the serialized form of a {{domxref("CSPViolationReportBody")}} object (see the respective objects for their property definitions).
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +Reports are sent to the target endpoint in a POST operation with the {{HTTPHeader("Content-Type")}} of `application/reports+json`.
```suggestion
Reports are sent to the target endpoint(s) via a `POST` operation with a {{HTTPHeader("Content-Type")}} of `application/reports+json`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +Any name can be used: here we've chosen "name-of-endpoint".
```suggestion
Any name can be used: here we've chosen `name-of-endpoint`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +The server can set this an endpoint name as the target for sending CSP violation reports using the `report-to` directive as shown.
```suggestion
The server can set this endpoint name as the target for sending CSP violation reports to using the `report-to` directive:
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +These violation reports consist of [JSON documents](#violation_report_syntax) sent via an HTTP POST request to the specified URI.
```suggestion
These violation reports consist of [JSON documents](#violation_report_syntax) sent via an HTTP `POST` request to the specified URI.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +The report JSON object is sent in an HTTP POST with the {{HTTPHeader("Content-Type")}} of `application/csp-report`.
```suggestion
The report JSON object is sent via an HTTP `POST` operation with a {{HTTPHeader("Content-Type")}} of `application/csp-report`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +It is an object with the single top level property `"csp-report"` that contains an object with the following properties:
```suggestion
It is an object with a single top-level property` `"csp-report"`` which contains an object with the following properties:
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +    Some browsers may provide different values, such as Chrome providing `style-src-elem`/`style-src-attr`, even when the actually enforced directive was `style-src`.
```suggestion
    Some browsers may provide different values, such as Chrome providing `style-src-elem`/`style-src-attr`, even when the enforced directive was `style-src`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +    Only applicable to `script-src*` and `style-src*` violations, when they contain the `'report-sample'`
```suggestion
    Only applicable to `script-src*` and `style-src*` violations, when they contain the `'script-sample'`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +    Only applicable to `script-src*` and `style-src*` violations, when they contain the `'report-sample'`
I wasn't sure where `report-sample` came from, so I guessed you meant `script-sample`. Am I wrong? If so, is there a link for more info that you can give?

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +It uses the following policy, disallowing everything but stylesheets from `cdn.example.com`.
```suggestion
It uses the following policy, disallowing everything except stylesheets loaded from `cdn.example.com`.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +A browser capable of enforcing CSP would send the following violation report as a POST request to `http://example.com/_/csp-reports`, when the document is visited:
```suggestion
A browser capable of enforcing CSP would send the following violation report as a `POST` request to `http://example.com/_/csp-reports` when the document is visited:
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +For example, if the `signup.html` attempted to load CSS from `http://anothercdn.example.com/stylesheet.css`, the browser would _not_ include the full path, but only the origin
```suggestion
For example, if `signup.html` attempted to load CSS from `http://anothercdn.example.com/stylesheet.css`, the browser would _not_ include the full path, only the origin,
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +This header allows the browser to report but not block on violations.
```suggestion
This header allows the browser to report but not block on violations for testing purposes.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +`/csp-violation-report-endpoint/` could for example run a PHP something like the following that logs the JSON detailing the violation and, if the violation is the first one added to the log file, sen
```suggestion
`/csp-violation-report-endpoint/` could for example run a PHP script like the following that logs the JSON detailing the violation and, if the violation is the first one added to the log file, sends an email to an administrator:
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/report-to/index.md
> +The HTTP **`Report-To`** {{glossary("response header")}} allows website administrators to define named groups of endpoints, that can then be used as the destination for warning and error reports, suc
```suggestion
The HTTP **`Report-To`** {{glossary("response header")}} allows website administrators to define named groups of endpoints that can be used as the destination for warning and error reports, such as CSP violation reports, {{HTTPHeader("Cross-Origin-Opener-Policy")}} reports, deprecation reports, or other generic violations.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/report-to/index.md
> +`Report-To` is often used in conjunction with other headers that select a particular group of endpoints to use for particular kind of report.
```suggestion
`Report-To` is often used in conjunction with other headers that select a group of endpoints to use for a particular kind of report.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/report-to/index.md
> +      - : The time in seconds that the browser should cache the reporting configuration.
```suggestion
      - : The time in seconds the browser should cache the reporting configuration for.
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/report-to/index.md
> +The server can then set that it wants this group to be the target for sending CSP violation reports by specifying the group name as the value of the {{CSP("report-to")}} directive:
```suggestion
The server can then specify that it wants this group to be the target for sending CSP violation reports by setting the group name as the value of the {{CSP("report-to")}} directive:
```

2024-08-20 11:50 UTC, chrisdavidmills commented on files/en-us/web/http/headers/reporting-endpoints/index.md
> +> This header replaces {{HTTPHeader("Report-To")}} {{deprecated_inline}} for declaring endpoints, and should be used by preference.
```suggestion
> This header replaces {{HTTPHeader("Report-To")}} {{deprecated_inline}} for declaring endpoints, and should be used in preference.
```

2024-08-23 03:02 UTC, hamishwillee commented on files/en-us/web/api/cspviolationreportbody/index.md
> +As before, we can trigger the violation loading by loading an external script from a location that is not covered by our CSP header:
I'm getting sloppy. Get so pleased with myself about the big picture the detail suffers. Sorry.

2024-08-23 03:11 UTC, hamishwillee commented on files/en-us/web/http/headers/report-to/index.md
> +      - : The time in seconds that the browser should cache the reporting configuration.
So far this is the only one I disagree with.

2024-08-23 03:16 UTC, hamishwillee commented on files/en-us/web/http/csp/index.md
> +If you wanted to have multiple endpoints that handle different types of reports, the `Reporting-Endpoints` header can contain a comma-separated list of endpoints:
Absolutely!

2024-08-23 03:25 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy-report-only/index.md
> +We might then define the destination of the report using `report-to` and `report-uri` as shown below.
Why not.

```suggestion
We might then define the destination of the report using {{CSP("report-to")}} and {{CSP("report-uri")}}, as shown below.
```

2024-08-23 03:27 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/index.md
> +    The endpoints that the token represents may be provided through other HTTP headers, such as {{HTTPHeader("Reporting-Endpoints")}}.
No, you can also provide this using `Report-To`, which is deprecated - and the reason I mentioned it. I guess it doesn't do any harm to do so.

```suggestion
    The endpoints that the token represents may be provided through other HTTP headers, such as {{HTTPHeader("Reporting-Endpoints")}} and {{HTTPHeader("Report-To")}} {{deprecated_inline}}.
```

2024-08-23 03:31 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/index.md
> +### Report violations only when testing
```suggestion
### Report but don't enforce violations when testing
```

2024-08-23 03:33 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +The endpoint name can also be the name of a group that is provided by the server in the {{HTTPHeader("Report-To")}} {{deprecated_inline}} HTTP response header, but this header is deprecated and shoul
```suggestion
It can also be the name of a group that is provided by the server in the {{HTTPHeader("Report-To")}} {{deprecated_inline}} HTTP response header.
```

2024-08-23 03:56 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-to/index.md
> +Content-Security-Policy: …; report-to <endpoint_name>
@chrisdavidmills 

I know you can use `Report-To` to define an endpoint name that maps to a number of URLs. The original docs suggested using that as a way to send reports to a backup endpoint.
However `Report-To` is deprecated, and hence on path for removal. 

So to clarify my question: 
- Can you defined multiple reporting end points using `Reporting-Endpoints` to get the same functionality as Report-To - sending the same report to multiple endpoints.
- If not, why is this not needed.

This is mostly an FMI thing, and doesn't really need to be covered.

2024-08-23 04:55 UTC, hamishwillee commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +    Only applicable to `script-src*` and `style-src*` violations, when they contain the `'report-sample'`
This is a very good question, which I have answered in https://github.com/mdn/content/pull/35331/commits/0f8f8a315906e74e29288367c19f48de44d515ab

It turns out `report-sample` is a keyword that you can apply  like `unsafe-inline`, or `report-to` that is required for the sample to be sent. This exists because if you have a violation you almost certainly can't trust stuff from your report, and you might not want to send it.

I've added all the restrictions to both this violation report and to the `SecurityPolicyViolationEvent`. I will also add to `CSPViolationReportBody` when I get to that!

2024-08-23 04:58 UTC, hamishwillee commented
@chrisdavidmills Thank you for that mammoth review. 

I accepted nearly everything, and fixed the specific open questions. Ready for another final look.

2024-08-23 07:39 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/index.md
> +    The endpoints that the token represents may be provided through other HTTP headers, such as {{HTTPHeader("Reporting-Endpoints")}}.
This is much better, nice one.

2024-08-23 07:52 UTC, chrisdavidmills commented on files/en-us/web/http/headers/content-security-policy/report-uri/index.md
> +It is an object with the single top level property `"csp-report"` that contains an object with the following properties:
My suggestion unfortunately introduced a double backtick, which screwed up the formatting. Sorry about that. I've made a small commit directly to your branch that fixes it.

2024-08-23 07:55 UTC, chrisdavidmills approved these changes
@hamishwillee I'm satisfied, you're satisfied, we're all satisfied!

And it's Friday. Let's get this merged.

2024-08-23 07:56 UTC, merged

2024-08-25 04:17 UTC, hamishwillee commented
Thanks @chrisdavidmills !!!