CSS: Remove bad practice
mdn/content pull request #35363
Opened 2024-08-07 19:36 UTC by estelle

we shouldn't show transitions on properties that would require the whole page to be re-laid out.
switching from font-size to bgcolor.

2024-08-08 12:03 UTC, chrisdavidmills requested changes
@estelle I totally agree with you on this change. Couple of comments for you to look at.

2024-08-08 12:03 UTC, chrisdavidmills commented on files/en-us/web/css/transition/index.md
> +  background-color: lime;
I can barely notice a difference between the before and after transition colors. Maybe change it to colors with a more striking difference, for example, `darkorange` and `yellow`?

Also maybe reduce the duration from `4s` to `2s`, so the change is a bit more perceivable?

2024-08-08 17:13 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +  transition: background-color 4s 1s;
```suggestion
  transition: background-color 2s 500ms;
```

2024-08-08 17:13 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +  background-color: lime;
```suggestion
  background-color: darkorange;
```

2024-08-08 17:14 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +In this example, when the user hovers over the element, there is a one-second delay before a four-second `background-color` transition occurs.
```suggestion
In this example, when the user hovers over the element, there is a half-second (`500ms`) delay before a two-second `background-color` transition occurs.
```

2024-08-08 17:15 UTC, estelle commented on files/en-us/web/css/transition/index.md
> +  background-color: lime;
agree. changed. Thanks.

2024-08-09 07:27 UTC, chrisdavidmills approved these changes
@estelle perfect, that hits the spot!

2024-08-09 07:27 UTC, merged