fix[tools]:list elements order (minor)
mdn/content pull request #3537
Opened 2021-03-26 14:29 UTC by AdrianSkar

Change the order of elements describing the pop-up to reflect whats shown in the image.

> What was wrong/why is this fix needed? (quick summary only)
The description list order doesn't reflect whats shown in the example image.

> MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_event_listeners
> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-03-26 23:30 UTC, sideshowbarker requested changes

2021-03-26 23:30 UTC, sideshowbarker commented on files/en-us/tools/page_inspector/how_to/examine_event_listeners/index.html
> +  <li>a curved arrow pointing to a stack; click it to show the code for the handler in the debugger</li>
```suggestion
 <li>a curved arrow pointing to a stack; click it to show the code for the handler in the debugger</li>
```

2021-03-26 23:32 UTC, sideshowbarker commented on files/en-us/tools/page_inspector/how_to/examine_event_listeners/index.html
> +  <li>a curved arrow pointing to a stack; click it to show the code for the handler in the debugger</li>
```suggestion
 <li>a curved arrow pointing to a stack; click it to show the code for the handler in the debugger</li>
```

2021-03-26 23:32 UTC, sideshowbarker approved these changes

2021-03-26 23:32 UTC, merged

2021-03-26 23:33 UTC, sideshowbarker commented
Adrian, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

2021-03-27 08:41 UTC, AdrianSkar commented
> 
> 
> Adrian, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

Thank you!