Adding GravitySensor API documentation.
mdn/content pull request #3541
Opened 2021-03-26 15:45 UTC by arskama

Fixes #3524
Implementation of GravitySensor API for Chrome 91 [1]
Dependency with update of compat-data [2]
[1] https://chromestatus.com/features/5384099747332096
[2] https://github.com/mdn/browser-compat-data/pull/9628

2021-03-31 23:31 UTC, wbamberg requested changes
Thanks for your contribution to MDN, @arskama ! I had a few comments.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +<p>If a feature policy blocks use of a feature, it is because your code is inconsistent
It feels inappropriate to have this paragraph right at the start like this. Is this really the second most important thing someone needs to know about the API?

If "If a feature policy blocks use of a feature", how would this be manifested? Would an exception be thrown in the constructor? If so, I would expect this would be documented in an "Exceptions" heading, like https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultWriter/WritableStreamDefaultWriter#exceptions.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>referenceFrame</code>: Either <code>'device'</code> or
We should explain what this option means.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>frequency</code>: The desired number of times per second a sample should
Since this is optional we should describe the default.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/index.html
> +<p>If a feature policy blocks use of a feature it is because your code is inconsistent with the policies set on your server. This is not something that would ever be shown to a user. See {{httpheader
Same comment as above about this paragraph.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/index.html
> +laSensor.start();</pre>
```suggestion
<pre class="brush: js">const gravitySensor = new GravitySensor({frequency: 60});

gravitySensor.addEventListener("reading", e =&gt; {
  console.log(`Gravity along the X-axis ${gravitySensor.x}`);
  console.log(`Gravity along the Y-axis ${gravitySensor.y}`);
  console.log(`Gravity along the Z-axis ${gravitySensor.z}`);
});

gravitySensor.start();</pre>
```

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/sensor_apis/index.html
> + <dd>Provides the gravity applied to the device along all three axes, but without the contribution of human artifact.</dd>
I don't understand what "without the contribution of human artifact" means here.

2021-03-31 23:31 UTC, wbamberg commented on files/en-us/web/api/sensor_apis/index.html
> +   <td>Defines <code>Accelerometer</code>, <code>GravitySensor</code> and <code>LinearAccelerationSensor</code>.</td>
```suggestion
   <td>Defines <code>Accelerometer</code>, <code>GravitySensor</code>, and <code>LinearAccelerationSensor</code>.</td>
```

2021-04-06 12:22 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +<p>If a feature policy blocks use of a feature, it is because your code is inconsistent
comment tackled in:
https://github.com/mdn/content/commit/7e7651d998db5ff6156dd6185085bde6f5aeeac7

2021-04-06 12:23 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>referenceFrame</code>: Either <code>'device'</code> or
comment tackled in:
https://github.com/mdn/content/commit/7e7651d998db5ff6156dd6185085bde6f5aeeac7

Not sure if needed more information, but otherwise a link to the specs is needed maybe.

2021-04-06 12:23 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>frequency</code>: The desired number of times per second a sample should
done in
https://github.com/mdn/content/commit/7e7651d998db5ff6156dd6185085bde6f5aeeac7

2021-04-06 12:23 UTC, arskama commented on files/en-us/web/api/gravitysensor/index.html
> +<p>If a feature policy blocks use of a feature it is because your code is inconsistent with the policies set on your server. This is not something that would ever be shown to a user. See {{httpheader
removed. I guess, if explained on the constructor, that is enough.

2021-04-06 12:24 UTC, arskama commented on files/en-us/web/api/gravitysensor/index.html
> +laSensor.start();</pre>
done

2021-04-06 12:24 UTC, arskama commented on files/en-us/web/api/sensor_apis/index.html
> + <dd>Provides the gravity applied to the device along all three axes, but without the contribution of human artifact.</dd>
removed, it was confusing.

2021-04-06 12:24 UTC, arskama commented on files/en-us/web/api/sensor_apis/index.html
> +   <td>Defines <code>Accelerometer</code>, <code>GravitySensor</code> and <code>LinearAccelerationSensor</code>.</td>
done

2021-04-06 12:25 UTC, arskama commented
@wbamberg. Thanks for the review!

2021-04-06 15:40 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>referenceFrame</code>: The local coordinate system represents
```suggestion
      <li><code>referenceFrame</code>: The local coordinate system representing 
```

2021-04-06 15:40 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +        frequency is the one defined by the underlying platform</li>
```suggestion
        frequency is the one defined by the underlying platform.</li>
```

2021-04-06 15:40 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>referenceFrame</code>: Either <code>'device'</code> or
I think what you have here is fine. We have a link to the spec in "Specifications" and people can refer to that if the need to.

2021-04-06 15:52 UTC, wbamberg requested changes
Thanks for the updates, @arskama ! I saw a couple of copy-edits, and think we ought to have a sentence in the Exceptions bit, as suggested.

2021-04-06 15:52 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +  <dd>If a feature policy blocks use of a feature, it is because your code is inconsistent
```suggestion
  <dd>Use of this feature was blocked by a feature policy. If a feature policy blocks use of a feature, it is because your code is inconsistent
```

It would be good to have an introductory sentence, like the one in this suggestion, to link this exception to the feature policy bit.

2021-04-07 06:08 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +        frequency is the one defined by the underlying platform</li>
fixed

2021-04-07 06:08 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +      <li><code>referenceFrame</code>: The local coordinate system represents
fixed

2021-04-07 06:08 UTC, arskama commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +  <dd>If a feature policy blocks use of a feature, it is because your code is inconsistent
correct.

2021-04-07 06:09 UTC, arskama reviewed
review comments fixed in 8c010d1d98ccde0f2eddd8e300f0cb09ed7c3a67

2021-04-07 16:56 UTC, wbamberg commented on files/en-us/web/api/gravitysensor/gravitysensor/index.html
> +  <dd>Use of this feature was blocked by feature policy. If a feature policy blocks use of a feature,
```suggestion
  <dd>Use of this feature was blocked by a feature policy. If a feature policy blocks use of a feature,
```

2021-04-07 17:00 UTC, wbamberg approved these changes
Thanks @arskama , looks great!

2021-04-07 17:01 UTC, merged

2021-04-08 06:48 UTC, arskama commented
Thanks @wbamberg for merging the patch.

I can see the pages now, but I was wondering why i don't see the GravitySensor in the list. (locally I do see it)
https://developer.mozilla.org/en-US/docs/Web/API/Sensor#interfaces_based_on_sensor
Am I missing something?

I was also wondering why a similar page, such as:
https://developer.mozilla.org/en-US/docs/Web/API/LinearAccelerationSensor/LinearAccelerationSensor
has a Inheritance sub-section on the Related Topics section but 
https://developer.mozilla.org/en-US/docs/Web/API/GravitySensor doesn't have that sub-section.

Thanks in advance.