Fixed no examples in XSLTProcessor `clearParameters()` method
mdn/content pull request #35432
Opened 2024-08-13 05:33 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/clearParameters
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xsltprocessor/clearparameters/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff

2024-08-15 15:45 UTC, Josh-Cena reviewed
See https://github.com/mdn/content/pull/35431#pullrequestreview-2240690810

2024-08-15 15:46 UTC, Josh-Cena requested changes
See https://github.com/mdn/content/pull/35431#pullrequestreview-2240690810

2024-08-16 01:41 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +`;
```suggestion
const xmlString = `
<items>
  <item>Item 1</item>
  <item>Item 2</item>
  <item>Item 3</item>
</items>
`;
```

2024-08-16 01:45 UTC, T34-active commented
See if the content meets your expectations

2024-08-16 02:04 UTC, Josh-Cena reviewed
Thanks. I've tried in three browsers and I don't see a difference before and after `clearParameters()` (both render three items), and I'm not sure what exactly is not working.

2024-08-16 02:04 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +### using clearParameters()
```suggestion
### Using clearParameters()
```

2024-08-16 03:42 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "yes");
Set this to "no" so there's a difference before and after? You may also want to add another `xsl:if` in your XSLT so there's something else to render.

2024-08-16 03:54 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "yes");
If I set it to 'no', the content after the `<hr>` element will not be displayed.
```
// Set the 'showItems' parameter to 'no' and perform transformation
xsltProcessor.setParameter(null, "showItems", "no");
resultFragment = xsltProcessor.transformToFragment(xmlDoc, document);
document.getElementById("result").appendChild(resultFragment);
```

2024-08-16 03:57 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "yes");
Yes, that's idea—that without `showItems` it shows something, and with `showItems: "no"` it shows nothing—tells you that `setParameter` does something meaningful. And I also suggested that your XSLT could be changed to something like:

```xml
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:param name="showItems" select="'yes'"/>
  <xsl:template match="/">
    <xsl:if test="$showItems = 'yes'">
      <ul>
        <xsl:for-each select="items/item">
          <li><xsl:value-of select="."/></li>
        </xsl:for-each>
      </ul>
    </xsl:if>
    <xsl:if test="$showItems = 'no'">
      <div>No content to show</div>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
```

2024-08-16 03:59 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "no");
This would render the `clearParameters` call useless. I suggested that you set it to "no" initially, and then call `clearParameters`, which would restore it to the default value of `yes` specified in `xsl:param`.

2024-08-16 04:02 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +`;
```suggestion
const xsltString = `
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:param name="showItems" select="'yes'"/>
  <xsl:template match="/">
    <xsl:if test="$showItems = 'yes'">
      <ul>
        <xsl:for-each select="items/item">
          <li><xsl:value-of select="."/></li>
        </xsl:for-each>
      </ul>
    </xsl:if>
    <xsl:if test="$showItems = 'no'">
      <div>No content to show</div>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
`;
```

2024-08-16 04:12 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "no");
```
const xmlString = `
<items>
  <item>Item 1</item>
  <item>Item 2</item>
  <item>Item 3</item>
</items>
`;

const xsltString = `
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:param name="showItems" select="'yes'"/>
  <xsl:template match="/">
    <!-- If showItems is 'yes', display the list of items -->
    <xsl:if test="$showItems = 'yes'">
      <ul>
        <xsl:for-each select="items/item">
          <li><xsl:value-of select="."/></li>
        </xsl:for-each>
      </ul>
    </xsl:if>
    <!-- If showItems is 'no', display a message -->
    <xsl:if test="$showItems = 'no'">
      <div>No content to show</div>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
`;

const parser = new DOMParser();
const xmlDoc = parser.parseFromString(xmlString, "application/xml");
const xsltDoc = parser.parseFromString(xsltString, "application/xml");

const xsltProcessor = new XSLTProcessor();
xsltProcessor.importStylesheet(xsltDoc);

// Perform the first transformation with the default value ('yes')
let resultFragment = xsltProcessor.transformToFragment(xmlDoc, document);
document.getElementById("result").appendChild(resultFragment);

// Add a horizontal rule to separate the results
document.getElementById("result").appendChild(document.createElement("hr"));

// Clear all parameters to reset to default values
xsltProcessor.clearParameters();

// Set the 'showItems' parameter to 'no' and perform the second transformation
xsltProcessor.setParameter(null, "showItems", "no");
resultFragment = xsltProcessor.transformToFragment(xmlDoc, document);
document.getElementById("result").appendChild(resultFragment);
```
See if the end result meets your expectations

2024-08-16 04:20 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "no");
`xsltProcessor.clearParameters();` followed by `xsltProcessor.setParameter(null, "showItems", "no");` is exactly equivalent to just doing the second step. I was suggesting you first set it to "no", do one `transformToFragment`, then `clearParameters`, and do the second `transformToFragment`.

2024-08-16 04:26 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "no");
```
const xmlString = `
<items>
  <item>Item 1</item>
  <item>Item 2</item>
  <item>Item 3</item>
</items>
`;

const xsltString = `
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:param name="showItems" select="'yes'"/>
  <xsl:template match="/">
    <!-- If showItems is 'yes', display the list of items -->
    <xsl:if test="$showItems = 'yes'">
      <ul>
        <xsl:for-each select="items/item">
          <li><xsl:value-of select="."/></li>
        </xsl:for-each>
      </ul>
    </xsl:if>
    <!-- If showItems is 'no', display a message -->
    <xsl:if test="$showItems = 'no'">
      <div>No content to show</div>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
`;

const parser = new DOMParser();
const xmlDoc = parser.parseFromString(xmlString, "application/xml");
const xsltDoc = parser.parseFromString(xsltString, "application/xml");

const xsltProcessor = new XSLTProcessor();
xsltProcessor.importStylesheet(xsltDoc);

// Set the 'showItems' parameter to 'no' and perform the first transformation
xsltProcessor.setParameter(null, "showItems", "no");
let resultFragment = xsltProcessor.transformToFragment(xmlDoc, document);
document.getElementById("result").appendChild(resultFragment);

// Add a horizontal rule to separate the results
document.getElementById("result").appendChild(document.createElement("hr"));

// Clear all parameters, resetting 'showItems' to its default value ('yes')
xsltProcessor.clearParameters();
resultFragment = xsltProcessor.transformToFragment(xmlDoc, document);
document.getElementById("result").appendChild(resultFragment);
```

2024-08-16 04:41 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/clearparameters/index.md
> +xsltProcessor.setParameter(null, "showItems", "no");
Yeah, that looks fine

2024-08-16 04:45 UTC, Josh-Cena approved these changes
Looks good, thanks!

2024-08-16 04:46 UTC, merged