Fixed no examples in XSLTProcessor `transformToDocument()` method
mdn/content pull request #35438
Opened 2024-08-13 06:48 UTC by T34-active

### Description
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/XSLTProcessor/transformToDocument
### Related issues and pull requests
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/xsltprocessor/transformtodocument/index.md
* Last commit: https://github.com/mdn/content/commit/b71d118ffc6d72b77efad9661110fcc9ede464eb

2024-08-13 06:50 UTC, T34-active reviewed
fix wrong element

2024-08-13 06:50 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/transformtodocument/index.md
> +<pre id="result"></pre>
```suggestion
<div id="result"></div>
```

2024-08-15 15:46 UTC, Josh-Cena requested changes
See https://github.com/mdn/content/pull/35431#pullrequestreview-2240690810

2024-08-16 03:19 UTC, Josh-Cena commented on files/en-us/web/api/xsltprocessor/transformtodocument/index.md
> +<div id="result"></div>
```suggestion
<pre id="result"></pre>
```

2024-08-16 03:20 UTC, Josh-Cena approved these changes
Looks good :+1: thanks!

2024-08-16 03:21 UTC, merged

2024-08-16 03:23 UTC, T34-active commented on files/en-us/web/api/xsltprocessor/transformtodocument/index.md
> +<div id="result"></div>
thanks!