click event bullet point fix
mdn/content pull request #35458
Opened 2024-08-13 23:58 UTC by gagan-bhullar-tech

### Description

PR fixes #35450

### Motivation

### Additional details

### Related issues and pull requests

2024-08-15 02:43 UTC, dipikabh requested changes

2024-08-15 02:43 UTC, dipikabh commented on files/en-us/web/api/element/click_event/index.md
>  - a touch gesture is performed on the element
```suggestion
- A pointing-device button (such as a mouse's primary button) is both pressed and released while the pointer is located inside the element.
- A touch gesture is performed on the element.
```

2024-08-15 02:43 UTC, dipikabh commented on files/en-us/web/api/element/click_event/index.md
> +- Any user interaction that is equivalent to a click, such as pressing the <kbd>Space</kbd> key or <kbd>Enter</kbd> key is pressed while the element is focused.
```suggestion
- Any user interaction that is equivalent to a click occurs, such as pressing the <kbd>Space</kbd> key or <kbd>Enter</kbd> key while the element is focused.
```

2024-08-15 02:43 UTC, dipikabh commented on files/en-us/web/api/element/click_event/index.md
> +> In practice, browsers don't fire this event for non-native control elements (such as a `<div>` with `tabIndex="0"`). See <a href="https://issues.chromium.org/issues/40776466">Chromium issue</a> for
```suggestion
> [!NOTE]
> In practice, browsers don't fire the `click` event for custom controls such as a `<div>` with `tabindex="0"`. To check the reason behind this behavior, see this <a href="https://issues.chromium.org/issues/40776466">Chromium issue</a>.
```

2024-08-15 03:14 UTC, Josh-Cena commented on files/en-us/web/api/element/click_event/index.md
> +> In practice, browsers don't fire the `click` event for custom controls such as a `<div>` with `tabindex="0"`. To check the reason behind this behavior, see this <a href="https://issues.chromium.org
```suggestion
> In practice, browsers don't fire the `click` event for custom controls such as a `<div>` with `tabindex="0"`. To check the reason behind this behavior, see this [Chromium issue](https://crbug.com/40776466).
```

Please, use Markdown

2024-08-15 13:28 UTC, dipikabh commented on files/en-us/web/api/element/click_event/index.md
> +> In practice, browsers don't fire the `click` event for custom controls such as a `<div>` with `tabindex="0"`. To check the reason behind this behavior, see this <a href="https://issues.chromium.org
of course! missed this

2024-08-15 13:29 UTC, dipikabh approved these changes
Thank you!

2024-08-15 13:29 UTC, merged

2024-10-06 18:50 UTC, benignant commented
@dipikabh, @Josh-Cena

I think the note should clearly refer only to the third bullet point, either by wording or by being inside that list item (indented 2 spaces).

The way it is now makes it sound like the `click` event does not fire at all on custom controls.

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

2024-10-06 21:20 UTC, Josh-Cena commented
@benignant That makes total sense. I think the note should be reworded to say "don't fire the `click` event for custom controls triggered by the third mechanism". Do you want to send a PR or issue?

2024-10-07 20:01 UTC, dipikabh commented
Or just indenting the note should be sufficient

2024-10-07 20:25 UTC, Josh-Cena commented
I think indenting would be too subtle. I would prefer it to be more explicit

2024-10-08 00:14 UTC, benignant commented
I opened PR https://github.com/mdn/content/pull/36256.