Remove HTMLTimeElement: dateTime syntax table, move it to <time>
mdn/content pull request #35453
Opened 2024-08-13 19:52 UTC by Josh-Cena

This table is poorly marked up and very inconsistent. It also shouldn't belong here but should belong in the `<time>` reference which is the canonical place for HTML attribute values.

2024-08-15 03:33 UTC, dipikabh requested changes
Thanks for fixing the table! Agree with moving it to the canonical element page.

I spotted a few nits you might want to take a quick look at.

2024-08-15 03:33 UTC, dipikabh commented on files/en-us/web/api/htmltimeelement/datetime/index.md
> +For valid values, see the [`<time>` reference](/en-US/docs/Web/HTML/Element/time#valid_datetime_values).
This would be better placed in "Value" to say: "For valid string formats, see the `datetime` valid values." 
And only linking `datetime`.

2024-08-15 03:33 UTC, dipikabh commented on files/en-us/web/html/element/time/index.md
>  ### Valid datetime values
```suggestion
### Valid `datetime` values
```

2024-08-15 03:33 UTC, dipikabh commented on files/en-us/web/html/element/time/index.md
> +      <th scope="col">Description</th>
Shouldn't the column names be swapped, the first one is Description and the second is Microsyntax (like a pattern)?

2024-08-15 03:33 UTC, dipikabh commented on files/en-us/web/html/element/time/index.md
> +        >
```suggestion
          Any combination of a valid local date and time string followed by a
          valid time-zone offset string
```

2024-08-15 03:44 UTC, Josh-Cena commented on files/en-us/web/html/element/time/index.md
>  ### Valid datetime values
Hi @dipikabh, when we loosened the heading typesetting guidelines, I made sure it says "you may use code formatting, but you are not required to". My agreement to the initial proposal was based on the intention of disambiguation, and when there's no ambiguity, I would prefer not to use code in headings.

2024-08-15 03:47 UTC, Josh-Cena commented on files/en-us/web/html/element/time/index.md
> +      <th scope="col">Description</th>
I believe it meant to say "Microsyntax name" and then "description" is more like "what this microsyntax expands to". 🤷‍♂️ Feels weird to me to have "description" be the shortest column. What about

```suggestion
      <th scope="col">Name</th>
      <th scope="col">Description</th>
```

2024-08-15 19:37 UTC, dipikabh commented on files/en-us/web/html/element/time/index.md
> +      <th scope="col">Description</th>
Sorry, I still see a discrepancy with the current column names and feel that we should swap them to better reflect their content.

Text like "Valid local date and time string" and "Four or more ASCII digits" seem more descriptive and read like an explanation, so would be better grouped under "Description".
Patterns like "`YYYY-MM-DDHH:MM`" (where we are also formatting them in backticks) indicate the syntax or format that must be followed rather than a description, so would sit better under "Microsyntax". In fact, might be good to retain "Microsyntax" because the [spec](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-time-string) also uses the term.

(I noticed that the same heading order is used in tables on HTMLFontElement color, face, size pages - but they're also all deprecated properties.)

2024-08-15 19:41 UTC, dipikabh approved these changes
Thanks a lot!

2024-08-15 20:17 UTC, Josh-Cena commented on files/en-us/web/html/element/time/index.md
>  ### Valid datetime values
My decision on this is because H1 headings can't have code formatting anyway, so we already have code-stripping happening for top-level headings.

2024-08-15 20:18 UTC, Josh-Cena commented on files/en-us/web/html/element/time/index.md
> +      <th scope="col">Description</th>
Alright, you are right that they are long enough to be "descriptions".

```suggestion
      <th scope="col">Description</th>
      <th scope="col">Microsyntax</th>
```

2024-08-15 23:43 UTC, Josh-Cena commented
Looks like we converged on something we can agree on, so I'm going to self-merge it. Thanks for the reviews

2024-08-15 23:43 UTC, merged

2024-08-16 01:26 UTC, dipikabh commented on files/en-us/web/html/element/time/index.md
>  ### Valid datetime values
H1s never figured in my mind as part of this discussion! :) It's only been about the section headings.