Added event listener instead of oninput attribute
mdn/content pull request #35503
Opened 2024-08-18 23:05 UTC by ADTmux

### Description

Added event listener in JS section instead of oninput attribute at `/en-US/docs/Web/HTML/Element/output`

### Motivation

These changes were required in issue [https://github.com/mdn/content/issues/35470](35470)

### Related issues and pull requests

Fixes #35470

2024-08-18 23:06 UTC, ADTmux commented
Hi, I am a beginner here. Please let me know if I need to do anything differently and I'll be happy to learn and work on it :)

2024-08-18 23:18 UTC, Josh-Cena requested changes
Looks mostly good

2024-08-18 23:18 UTC, Josh-Cena commented on files/en-us/web/html/element/output/index.md
> +document.addEventListener("DOMContentLoaded", function () {
You don't need this listener wrapper; our scripts are only run after DOM is loaded.

2024-08-18 23:18 UTC, Josh-Cena commented on files/en-us/web/html/element/output/index.md
> +  b.addEventListener("input", updateResult);
Don't change the semantics of the example; before they were listening for `input` on the form instead of each input, so it should do the same now.

2024-08-19 00:46 UTC, ADTmux commented on files/en-us/web/html/element/output/index.md
> +  b.addEventListener("input", updateResult);
Sure, updated as per requirements

2024-08-19 01:04 UTC, Josh-Cena commented on files/en-us/web/html/element/output/index.md
> +b.addEventListener("input", updateResult);
Add event listener to `form`?

2024-08-19 02:44 UTC, ADTmux commented on files/en-us/web/html/element/output/index.md
> +b.addEventListener("input", updateResult);
Added to form

2024-08-19 03:24 UTC, Josh-Cena approved these changes
Looks good :+1: Nice work!

2024-08-19 03:25 UTC, merged