Add stroke-* CSS SVG properties
mdn/content pull request #35516
Opened 2024-08-19 20:45 UTC by meyerweb

### Description

Adds documentation for the CSS properties `stroke-dasharray`,`stroke-dashoffset`,`stroke-linecap`,`stroke-linejoin`,`stroke-miterlimit`,`stroke-opacity`, and `stroke-width`, almost all of which replicate SVG attributes.  (`stroke-miterlimit` is similar to the corresponding SVG attribute, but not exactly the same.)

### Motivation

The pages currently don’t exist, and need to be created (see https://github.com/mdn/content/issues/34763).

2024-08-20 22:57 UTC, estelle commented
i am reviewing it; but it's taking a while....

2024-08-21 03:10 UTC, estelle requested changes
Review is at https://github.com/meyerweb/content/pull/5

2024-08-21 17:45 UTC, pransh15 commented
Hi folks 👋 
Thanks for starting with https://github.com/mdn/content/issues/34763!

I would like to understand the workflow here. I am confused since the feedback was shared in a PR on a fork(https://github.com/meyerweb/content/pull/5).

2024-08-22 03:30 UTC, estelle commented
> I would like to understand the workflow here. I am confused since the feedback was shared in a PR on a fork([meyerweb#5](https://github.com/meyerweb/content/pull/5)).
@pransh15 
For large PRs, it is sometimes easier to provide suggested edits via a PR rather than via the GitHub GUI.
Another example is https://github.com/chrisdavidmills/content/pull/10. Chris's PR was huge, and the PR feedback process went much faster there once we started using that method. This method makes sense only for XL PRs with tons of suggestions.

2024-08-26 15:33 UTC, pransh15 commented
TIL! I understand that, thanks for clarifying @estelle. This was helpful. :)

2024-08-26 19:40 UTC, meyerweb commented
After going through Estelle’s edits and making a few small tweaks, this is again ready to be reviewed.

2024-08-27 04:53 UTC, estelle approved these changes
thank you!

2024-08-27 04:53 UTC, merged