Fill the missing options, from Formal syntax below
mdn/content pull request #35540
Opened 2024-08-21 02:57 UTC by zhangenming

### Description

### Motivation

It's mentioned below but it's not here so I think it's missing

### Additional details

### Related issues and pull requests

2024-08-21 02:59 UTC, zhangenming commented
https://drafts.csswg.org/css-text/#intro

But according to the full text of the specification there is no mention of this option so I want to know what is going on
thanks

Or do I need to remove this option

2024-08-21 03:01 UTC, zhangenming commented
If math-auto is not in the specification, maybe we should give a hint

2024-08-21 04:13 UTC, Josh-Cena requested changes
This is in CSS text level 4: https://drafts.csswg.org/css-text-4/#text-transform-property We need to update the spec link in BCD too. According to the compat data, `math-auto` is already supported, so we indeed should document this, which means adding this to the values list below, and one example of how it may be used. Do you want to do that?

2024-08-21 06:05 UTC, Josh-Cena commented
When I said "examples" I meant an example on this page, but interactive examples are of course welcome :) 

Could you update the values list right below this code too? And an example section.

2024-08-21 07:04 UTC, zhangenming commented
I'm not confident that I can guarantee that the addition to the example will be appropriate

2024-08-21 16:54 UTC, Josh-Cena commented
Maybe check https://w3c.github.io/mathml-core/#new-text-transform-values? The idea is to map normal ASCII letters to math italic characters.

2024-08-22 01:31 UTC, zhangenming commented
i can't 
Not sure what to do
need more help

2024-08-22 01:49 UTC, Josh-Cena commented
I originally conceived of the following example:

```html
<div>
  (sin&hairsp;<span>x</span>)<sup>2</sup> + (cos&hairsp;<span>x</span>)<sup>2</sup> = 1
</div>
```

```css
div {
  text-transform: math-auto;
}
```

But in fact, using proper MathML markup, we get the same result out of the box:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <semantics>
    <mrow>
      <mo stretchy="false">(</mo>
      <mo lspace="0em" rspace="0em">sin</mo>
      <mspace width="0.16666666666666666em"></mspace>
      <mi>x</mi>
      <msup>
        <mo stretchy="false">)</mo>
        <mn>2</mn>
      </msup>
      <mo>+</mo>
      <mo stretchy="false">(</mo>
      <mo lspace="0em" rspace="0em">cos</mo>
      <mspace width="0.16666666666666666em"></mspace>
      <mi>x</mi>
      <msup>
        <mo stretchy="false">)</mo>
        <mn>2</mn>
      </msup>
      <mo>=</mo>
      <mn>1</mn>
    </mrow>
    <annotation encoding="TeX">(\sin\,x)^2+(\cos\,x)^2=1</annotation>
  </semantics>
</math>
```

@fred-wang What is the intended use case of `text-transform: math-auto`, outside of being able to specify `mi`?

2024-09-02 07:56 UTC, fred-wang commented
@Josh-Cena This italicization is something defined in MathML 3, when we wrote MathML Core it was suggested to expose the internal magic, so this is essentially what this CSS text-transform value is doing. I imagine, this could be used for italicization in math markup using HTML markup only, or to easily cancel italicization on single-char mi, but not sure these are strong use cases.

2024-09-02 14:05 UTC, Josh-Cena commented
Yes, I imagined that this was implemented only so that MathML rendering can reuse CSS machinery, but it seems there's no real use case that can't be solved using MathML natively?

2024-09-02 14:09 UTC, fred-wang commented
@Josh-Cena right, I'm not really aware of other use cases.

2024-09-02 14:31 UTC, Josh-Cena commented
I've added some description and an example based on my understanding. @fred-wang Could you review? Thanks!

2024-09-04 12:49 UTC, fred-wang approved these changes

2024-09-04 12:49 UTC, fred-wang commented on files/en-us/web/css/text-transform/index.md
> +  - : Used to automatically render text in math italic where appropriate. It transforms ASCII and Greek letters to [italic mathematical symbols](https://www.unicode.org/charts/PDF/U1D400.pdf) but onl
Just FYI, as I think it does not matter much for MDN but the exact set of characters  that are transformed is https://w3c.github.io/mathml-core/#italic-mappings

2024-09-04 12:49 UTC, fred-wang commented on files/en-us/web/css/text-transform/index.md
> +
This is fine, but I would use a `.math-identifier` identifier so we can more accurately tag math identifiers:

 `<span class="math-identifier">sin</span>`

etc

In your example, browsers would actually try to perform the transform on any text node, not just math identifiers.

2024-09-04 13:09 UTC, Josh-Cena commented on files/en-us/web/css/text-transform/index.md
> +  - : Used to automatically render text in math italic where appropriate. It transforms ASCII and Greek letters to [italic mathematical symbols](https://www.unicode.org/charts/PDF/U1D400.pdf) but onl
I did read that table and it looked like it's just Latin/Greek (+some variants like partial derivatives, variant greek, and dotless i/j), so I figured I could just handwave here.

2024-09-04 13:10 UTC, Josh-Cena commented on files/en-us/web/css/text-transform/index.md
> +
My goal is to show that `math-auto` is "smart" and only does the transform where necessary—otherwise why would we apply `math-identifier` to `sin` at all, when it would have no other semantic significance?

2024-09-11 19:38 UTC, Josh-Cena approved these changes
Going to merge this :) Thanks @fred-wang for the review

2024-09-11 19:40 UTC, merged