Remove an incorrect assertion about listboxes
mdn/content pull request #35553
Opened 2024-08-22 17:28 UTC by anonymous-gecko

### Description

* This change deletes a snippet of text that states that each child of a listbox should have a role of option. This assertion is incorrect since roles such as presentation and group are valid children of listboxes.

### Motivation

* To remove an incorrect assertion which would make developers hesitant to use roles other than option in their listboxes.

### Additional details

https://www.w3.org/WAI/ARIA/apg/patterns/listbox/examples/listbox-grouped

### Related issues and pull requests

2024-08-22 18:36 UTC, scottaohara requested changes
A better update to this would be to instead provide nuance to that sentence, rather than deleting it.   As now the paragraph ends with saying "a listbox can contain images." and taking that at face value, one could infer it means:

```
<div role=listbox ..>
  <img src=... alt=whatever>
  ...
</div>
```

but we don't really want that...  a listbox is meant to contain options.  those options may be contained within groups, or for visually structuring the options, they may be contained within generic or presentational elements.

2024-08-22 18:57 UTC, anonymous-gecko commented
> for visually structuring the options, they may be contained within generic or presentational elements.

Isn't it also acceptable for presentational elements to be contained within the listbox outside of options? Based on the w3.org example, the following should be acceptable:

```html
<ol role="listbox">
    <ol role="group">
        <li role="presentation">A-C</li>
        <li role="option">Aardvark</li>
        <li role="option">Baboon</li>
        <li role="option">Crab</li>
    </ol>

    <ol role="group">
        <li role="presentation">D-F</li>
        <li role="option">Deer</li>
        <li role="option">Earthworm</li>
        <li role="option">Frog</li>
    </ol>
</ol>
```

2024-08-22 19:06 UTC, scottaohara commented
no.  that wouldn't be acceptable with that markup alone.  (want to share the link where you pulled that from? maybe it needs correcting) That's attempting to treat A-C as the group name, but that isn't setup to do so.  so the group is unnamed, and A-C will likely be missed by someone using a screen reader, because it's rather uncommon for one to expect to not navigate a listbox in forms mode.

2024-08-22 20:52 UTC, anonymous-gecko commented
My bad, yes my example was incomplete. Could we copy the description from w3c?

> List boxes contain children whose role is option or elements whose role is group which in turn contain children whose role is option.

I believe it's probably unnecessary to state that elements whose role is presentation are also acceptable

2024-08-22 21:12 UTC, scottaohara commented
i think that'd be a better change. yah. thank you for suggesting

2024-08-22 21:59 UTC, anonymous-gecko commented
Alright, I added in the snippet and reworded the commit message. Let me know if there are any additional changes you'd like me to make

2024-08-22 21:59 UTC, Josh-Cena commented on files/en-us/web/accessibility/aria/roles/listbox_role/index.md
> +The `listbox` role is used to identify an element that creates a list from which a user may select one or more static items, similar to the HTML {{HTMLElement('select')}} element. Unlike {{HTMLElemen
```suggestion
The `listbox` role is used to identify an element that creates a list from which a user may select one or more static items, similar to the HTML {{HTMLElement('select')}} element. Unlike {{HTMLElement('select')}}, a listbox can contain images. Listboxes contain children whose role is [`option`](/en-US/docs/Web/Accessibility/ARIA/Roles/option_role) or elements whose role is [`group`](/en-US/docs/Web/Accessibility/ARIA/Roles/group_role) which in turn contain children whose role is `option`.
```

2024-08-23 15:15 UTC, scottaohara approved these changes
thank you for the update!

2024-08-23 18:26 UTC, merged