fix: fix incorrectly inserted image alt text is corrected
mdn/content pull request #35582
Opened 2024-08-25 05:20 UTC by C17AN

### Description

Fixes #35581.

### Motivation

I noticed something unusual in the original text while translating it into Korean, so I wanted to fix it.

### Additional details

### Related issues and pull requests

#35581.

2024-08-26 16:23 UTC, rebloor requested changes

2024-08-26 16:23 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/user_interface/index.md
> +          alt="Example of custom panel on developer tools"
```suggestion
          alt="Example of a custom panel on developer tools."
```

2024-08-27 00:32 UTC, C17AN commented on files/en-us/mozilla/add-ons/webextensions/user_interface/index.md
> +          alt="Example of custom panel on developer tools"
Thanks for suggestion!

2024-08-28 23:11 UTC, rebloor approved these changes

2024-08-28 23:11 UTC, merged

2024-08-28 23:12 UTC, rebloor commented
@C17AN thanks for finding and fixing that one