Modified deletefromDocument page
mdn/content pull request #35603
Opened 2024-08-27 04:57 UTC by ADTmux

### Description

Modified `en-US/docs/Web/API/Selection/deleteFromDocument` page where it now talks about nodes getting deleted rather than just text. I added a heading in the example because I thought we might want to show more elements than just one paragraph. 

### Motivation

Conveys what the function does better

### Additional details

### Related issues and pull requests

Fixes [https://github.com/mdn/content/issues/34943](#34943)

2024-08-27 04:57 UTC, ADTmux commented
Please let me know any opinions on this. Happy to discuss and learn :)

2024-08-27 05:00 UTC, Josh-Cena commented on files/en-us/web/api/selection/deletefromdocument/index.md
> +{{domxref("Selection")}} interface deletes the selected {{ domxref("Node", "Nodes") }} from the document's DOM.
```suggestion
{{domxref("Selection")}} interface deletes the selected {{domxref("Node")}} objects from the document's DOM.
```

`Nodes` is not a code entity. `domxref` is going to code-format it. Let's just reword it instead.

2024-08-27 05:06 UTC, Josh-Cena requested changes
Neither the content before and after is correct. It needs to account for both "partially selected nodes" and "fully selected nodes":

- If a node is only partially selected (can only happen if the node overlaps with the start or end of selection), then only the selected text gets deleted, and the node is kept.
- If a node is fully selected, then the node itself is removed.

I would also suggest you add the same verbiage to https://developer.mozilla.org/en-US/docs/Web/API/Range/deleteContents, and mention on the `deleteFromDocument` that it actually just calls `deleteContents` on the underlying `Range`.

2024-09-02 05:15 UTC, Josh-Cena commented
@ADTmux FYI, you still have a review suggestion outstanding.

2024-09-03 01:24 UTC, ADTmux commented
Hi @Josh-Cena , I was trying to read up about what you mentioned from [](https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/ranges.html#td-ancestor-container) , part 2.6. I did not add details to deleteFromDocument() since it is only a wrapper.

2024-09-03 01:59 UTC, Josh-Cena approved these changes
Thanks! I think this looks good. Great work.

2024-09-03 01:59 UTC, Josh-Cena commented on files/en-us/web/api/selection/deletefromdocument/index.md
> +This example lets you delete selected nodes by clicking a button. Upon clicking the
```suggestion
This example lets you delete selected text and/or nodes by clicking a button. Upon clicking the
```

2024-09-03 01:59 UTC, Josh-Cena commented on files/en-us/web/api/selection/deletefromdocument/index.md
> +{{domxref("Window.getSelection()")}} method gets the selected objects, and the
```suggestion
{{domxref("Window.getSelection()")}} method gets the selected content, and the
```

2024-09-03 02:00 UTC, Josh-Cena commented on files/en-us/web/api/selection/deletefromdocument/index.md
> +<h2>All of the selected nodes are removed.</h2>
```suggestion
<h2>All of the selected text/nodes are removed.</h2>
```

2024-09-03 02:10 UTC, Josh-Cena commented on files/en-us/web/api/selection/deletefromdocument/index.md
> +<h2>All of the selected text/nodes are removed.</h2>
```suggestion
<h2>All of the selected text/nodes will be removed.</h2>
```

2024-09-03 02:11 UTC, merged