ember prototype fix
mdn/content pull request #35673
Opened 2024-08-31 23:50 UTC by gagan-bhullar-tech

### Description

PR fixes #35640

### Motivation

### Additional details

### Related issues and pull requests

2024-09-01 04:35 UTC, Josh-Cena requested changes
You can't just change the code. Have you made sure the text explanations still make sense?

2024-09-01 05:47 UTC, gagan-bhullar-tech commented
@Josh-Cena I worked through the tutorial before making changes. These changes make sense for the latest ember version.

2024-09-01 05:53 UTC, Josh-Cena commented
I don't mean that. For example, in the second change, the paragraph below says:

> While this may look like familiar JavaScript, you may notice that we're calling the method [`pushObject()`](https://api.emberjs.com/ember/4.2/classes/ArrayProxy/methods/filterBy?anchor=pushObject) on our `todos` array.

You need to change that.

2024-09-01 07:44 UTC, gagan-bhullar-tech commented
@Josh-Cena updated text

2024-09-01 16:28 UTC, Josh-Cena commented
There are other locations too. Look around! Read both pages that you have modified.

2024-09-03 03:59 UTC, gagan-bhullar-tech commented
@Josh-Cena updated PR. Please review.

2024-09-03 04:25 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/ember_interactivity_events_state/index.md
> +    this.todos = [...this.todos];
```suggestion
    this.todos = [...this.todos, newTodo];
```

2024-09-03 04:26 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/ember_interactivity_events_state/index.md
> +And just like before, the `add()` function that will be called from the template. We are calling `push()` method on our `todos` array to add `newTodo` to `todos` array and then using the spread opera
```suggestion
And just like before, the `add()` function that will be called from the template. We [spread our `todos` array](/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to add `newTodo` to it, which creates a new array and will trigger the reactivity system to update the UI.
```

2024-09-03 04:28 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/ember_conditional_footer/index.md
> +   Using Javascript's `filter()` method, we're able to easily filter Objects in our array based on simple equals conditions. Here we're asking for all the todo items where the `isCompleted` property
```suggestion
   Using the [`filter()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method, we're asking for all the todo items where the `isCompleted` property is equal to `false`, and because `isCompleted` is `@tracked` in our `Todo` object, this getter will re-compute when the value changes on an Object in the array.
```

2024-09-03 04:28 UTC, Josh-Cena approved these changes
Thanks

2024-09-03 04:29 UTC, Josh-Cena commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/ember_interactivity_events_state/index.md
> +And just like before, the `add()` function that will be called from the template. We [spread our `todos` array](/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to add `newTodo` to it, w
```suggestion
And just like before, the `add()` function that will be called from the template gets annotated with the `@action` decorator to bind it to the class instance. We [spread our `todos` array](/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to add `newTodo` to it, which creates a new array and will trigger the reactivity system to update the UI.
```

2024-09-03 04:30 UTC, merged