fix(css): update color-scheme and prefers-color-scheme documents
mdn/content pull request #35759
Opened 2024-09-05 12:29 UTC by OnkarRuikar

- fix https://github.com/mdn/content/issues/35738

2024-09-10 12:14 UTC, chrisdavidmills requested changes
@OnkarRuikar these changes seem reasonable, but I made some changes to hopefully help clarify a few things. I'm not an expert on this particular area of CSS, but these suggestions seemed to make sense based on background reading.

2024-09-10 12:14 UTC, chrisdavidmills commented on files/en-us/web/css/color-scheme/index.md
> +The **`color-scheme`** [CSS](/en-US/docs/Web/CSS) property allows an element to indicate which color schemes it can comfortably be rendered in. User agents change the following aspects of the browser
```suggestion
The **`color-scheme`** [CSS](/en-US/docs/Web/CSS) property allows an element to indicate which color schemes it can comfortably be rendered in. User agents change the following aspects of the UI chrome to match the used color scheme:
```

2024-09-10 12:14 UTC, chrisdavidmills commented on files/en-us/web/css/color-scheme/index.md
> +- the color of the canvas surface
```suggestion
- The color of the canvas surface.
```

(Capitalize the other list items too, and add a period.)

2024-09-10 12:14 UTC, chrisdavidmills commented on files/en-us/web/css/color-scheme/index.md
> +Component authors must use [`prefers-color-scheme`](/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query to support the color schemes on reset of the elements.
```suggestion
Component authors must use the [`prefers-color-scheme`](/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature to support the color schemes on reset of the elements.
```

Also, what do you mean by "on reset of the elements"? I'm not sure what it means, although I do have some good guesses. You might want to expand on this a bit to make it clearer.

2024-09-10 12:14 UTC, chrisdavidmills commented on files/en-us/web/css/color-scheme/index.md
> +  - : If [page's supported color schems](/en-US/docs/Web/HTML/Element/meta/name#color-scheme) are set then the value indicates that the element supports the page's color schemes. If the page's color
```suggestion
  - : Indicates that the element can be rendered using the page's [color scheme](/en-US/docs/Web/HTML/Element/meta/name#color-scheme) settings. If the page does not have a color scheme set, the element is rendered using the page's default color settings.
```

2024-09-11 01:50 UTC, OnkarRuikar commented on files/en-us/web/css/color-scheme/index.md
> +- the default colors of other browser-provided UI, such as "spellcheck" underlines
```suggestion
- The color of the canvas surface.
- The default colors of scrollbars and other interaction UI.
- The default colors of form controls.
- The default colors of other browser-provided UI, such as "spellcheck" underlines.
```

2024-09-11 01:51 UTC, OnkarRuikar commented on files/en-us/web/css/color-scheme/index.md
> +Component authors must use [`prefers-color-scheme`](/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query to support the color schemes on reset of the elements.
```suggestion
Component authors must use the [`prefers-color-scheme`](/en-US/docs/Web/CSS/@media/prefers-color-scheme) media feature to support the color schemes on the rest of the elements.
```

2024-09-11 01:54 UTC, OnkarRuikar commented on files/en-us/web/css/color-scheme/index.md
> +- the color of the canvas surface
done

2024-09-11 07:22 UTC, chrisdavidmills approved these changes
@OnkarRuikar looking good, approving!

2024-09-11 07:22 UTC, merged