Add CSS `@custom-media` at-rule
mdn/content pull request #35755
Opened 2024-09-05 09:06 UTC by ramiy

### Description

[Media Queries Level 5](https://www.w3.org/TR/mediaqueries-5/) spec defines the `@custom-media` at-rule. This PR adds a new article to MDN explaining how and when to use Custom Media Queries.

### Additional details

* BCD: https://github.com/mdn/browser-compat-data/pull/24338

2024-10-03 00:58 UTC, estelle requested changes
Sorry for the delay. I must have accidentally dismissed this from my notifications.

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +- [CSS media queries](/en-US/docs/Web/CSS/CSS_media_queries)
```suggestion
- [CSS media queries](/en-US/docs/Web/CSS/CSS_media_queries) module
```

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +  - : A name identifying the custom media.
```suggestion
  - : A [`<dashed-ident>`](/en-US/docs/Web/CSS/dashed-ident); the name identifying the custom media.
```

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +By changing one line of code, all media queries using this custom media query alies in all CSS files are updated accordingly.
```suggestion
If the breakpoint changes, by changing one line of code, a single media feature value, all media queries using this custom media query alias in all CSS files are updated accordingly.
```

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +@custom-media --modern (color), (hover);
is this valid?

```css
@custom-media --modern ((color), (hover));
```
should we add a line recommending doing that instead since

```css
@media (((color) or (hover))) and (width > 1024px) {
}
```
is valid but

```css
@media (color) or (hover) and (width > 1024px) {
}
```
is not?

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +```css
and invalid class

2024-10-03 00:58 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +A `@custom-media` rule can refer to other custom media queries. However, loops are forbidden, and a custom media query must not be defined in terms of itself or of another custom media query that dir
```suggestion
A `@custom-media` rule can refer to other custom media queries and include the alias name within the feature list. However, ensure the custom media query is not defined in terms of itself or of another custom media query that directly or indirectly refers to it as loops are not valid. Any attempt to define a custom media query with a circular dependency will cause all the custom media queries in the loop to fail.
```
translate the spec, don't copy it. I tried making this more understandable but my suggestion can use a bit more work

2024-10-03 17:41 UTC, ramiy commented on files/en-us/web/css/@custom-media/index.md
> +- `<media-query-list>`
No problem, but lit's not wait for the other PR. When https://github.com/mdn/content/pull/36171 is merged, we will update this article.

2024-10-03 17:52 UTC, ramiy commented on files/en-us/web/css/@custom-media/index.md
> +@custom-media --modern (color), (hover);
This example is from the spec - https://drafts.csswg.org/mediaqueries-5/#example-532b0adb

We can add addition recommendations, but let's not change the spec recommendations.

2024-10-03 17:53 UTC, ramiy commented on files/en-us/web/css/@custom-media/index.md
> +```css
same as above, the example copied from the spec.

2024-10-03 23:27 UTC, estelle commented on files/en-us/web/css/@custom-media/index.md
> +- `<media-query-list>`
merged!

2024-10-04 08:04 UTC, ramiy commented on files/en-us/web/css/@custom-media/index.md
> +- `<media-query-list>`
@estelle I adde a link in the row bellow. Is it ok?

2024-10-04 18:19 UTC, estelle approved these changes
LGTM! thanks.

2024-10-14 20:00 UTC, ramiy commented
@estelle reminding you to merge this article.

2024-10-18 21:34 UTC, estelle commented
Hi @ramiy.  I asked about merging this and was told the MDN policy is to wait for at least one implementation, so I add the "waiting for implementation" tag.

2024-12-30 17:56 UTC, bsmth commented
FYI, this is removed from BCD in https://github.com/mdn/browser-compat-data/pull/25125

2025-01-24 17:48 UTC, Josh-Cena commented
Given that all vendor tracking issues have been open for 3+ years but there's no visible progress on any of them, combined with the fact that the BCD entries are gone as well, I think we are far from being ready for documentation. I will close this for now to prevent us from getting hung up infinitely on this PR, but feel free to either ping us here or send a new PR whenever this feature is actually shipping in at least one browser.

2025-01-24 17:48 UTC, closed without merging