fix(css): update container query pages
mdn/content pull request #35767
Opened 2024-09-06 06:38 UTC by OnkarRuikar

- fix https://github.com/mdn/content/issues/35762

The PR:
- adds missing information
- rewords the `## Naming containers` section. The section is not concise, has repetitive info, and is beating around the bush. The `container-type: normal` and `container-name: none` are the default values. We shouldn't ask readers to set them explicitly to achieve the default behavior.

2024-09-10 12:44 UTC, chrisdavidmills requested changes
Nice work @OnkarRuikar. I've made a few suggestions.

2024-09-10 12:44 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +A `<container-condition>` can include an optional case-sensitive {{cssxref("container-name")}}. A container name makes the container condition more specific. Such container condition is evaluated aga
```suggestion
A `<container-condition>` can include an optional case-sensitive {{cssxref("container-name")}}. A container name makes the container condition more specific — it is evaluated only against elements that have that name set in the `container-name` property.
```

2024-09-10 12:44 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +@container [ <container-name> ]? <container-query> {
This formal syntax isn't quite right. Check out the latest at https://drafts.csswg.org/css-conditional-5/#container-rule

2024-09-10 12:44 UTC, chrisdavidmills commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +In the above example, the styles within the container query block will apply to the descendants of all {{htmlelement("li")}} elements with a width that is greater than their height. Note that if ther
```suggestion
In the above example, the styles within the container query block will apply to the descendants of all {{htmlelement("li")}} elements with a width that is greater than their height. Note that other elements with `container-name: card` applied to them that match the size query will also have these styles applied to their elements' descendants.
```

I didn't think the spec example was very helpful — it made the sentence harder to read and also made me think "oh, is that example in one of the code blocks somewhere near"?

2024-09-11 02:14 UTC, OnkarRuikar commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +@container [ <container-name> ]? <container-query> {
Yes, the expanded version of 
`@container <container-condition>#` is 
`@container [[ <container-name> ]? <container-query>]#`.

2024-09-11 07:24 UTC, chrisdavidmills approved these changes
@OnkarRuikar great, nice work! Approving.

2024-09-11 07:25 UTC, merged

2024-09-11 14:56 UTC, benface commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The default value `container-type: normal` prevents the container from being a query container, meaning the element is not a size container but it can still be a [style container](#container_style_qu
> The default value `container-type: normal` prevents the container from being a query container

@OnkarRuikar, this is wrong/confusing. It only prevents the container from being queried with a size query, but it can still be a "query container" for style queries.

2024-09-12 03:06 UTC, OnkarRuikar commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The default value `container-type: normal` prevents the container from being a query container, meaning the element is not a size container but it can still be a [style container](#container_style_qu
We mentioned `but it can still be a style container` in the same sentence.

More explicit wording could be:
> The default value `container-type: normal` prevents the container from being a query container for size queries, meaning the element is not a size container. However, the container remains a [style container](#container_style_queries) that is a query container for style queries.

Could you [submit a PR](https://github.com/mdn/content/edit/main/files/en-us/web/css/css_containment/container_size_and_style_queries/index.md)?

2024-09-13 13:41 UTC, benface commented on files/en-us/web/css/css_containment/container_size_and_style_queries/index.md
> +The default value `container-type: normal` prevents the container from being a query container, meaning the element is not a size container but it can still be a [style container](#container_style_qu
Done: #35871. Thank you!