update redirected URLs
mdn/content pull request #35770
Opened 2024-09-06 08:27 UTC by OnkarRuikar

It is crucial to update redirects before the URLs start throwing 404.

2024-09-06 14:06 UTC, Josh-Cena requested changes
So I've personally excluded the 'Tools and setup' subtree from my dashboard (using the "configure include/exclude"). We need to renovate everything https://github.com/openwebdocs/project/issues/207 and it's likely that many of the links don't work at all. From what I see, some of them are not redirecting to a page with the same purpose. What do you think?

Open to discussing about this though, I just haven't taken a look at this subtree. The requested changes are as below.

2024-09-06 14:06 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/51/index.md
> +- The [PAC](</en-US/docs/Mozilla/Projects/Necko/Proxy_Auto-Configuration_(PAC)_file>) `FindProxyForURL(url, host)` function now strips paths and queries from https\:// URLs to avoid information leaka
I think we should be cautious about using web archive. I  think we should either remove this link, find another article that talks about the same thing,  or wait until the site comes back again.

2024-09-06 14:06 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/33/index.md
> +For details please [see the hacks post](https://hacks.mozilla.org/2014/07/event-listeners-popup-media-sidebar-cubic-bezier-editor-more-firefox-developer-tools-episode-33/). Special thanks to the 33 c
We allow link shorteners (I should add it to the allowed redirects).

2024-09-06 14:14 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/33/index.md
> +For details please [see the hacks post](https://hacks.mozilla.org/2014/07/event-listeners-popup-media-sidebar-cubic-bezier-editor-more-firefox-developer-tools-episode-33/). Special thanks to the 33 c
```suggestion
For details please [see the hacks post](https://hacks.mozilla.org/2014/07/event-listeners-popup-media-sidebar-cubic-bezier-editor-more-firefox-developer-tools-episode-33/). Special thanks to the 33 contributors that added [all the features and fixes](https://mzl.la/1pGLFDs) in this release.
```

2024-09-06 14:17 UTC, OnkarRuikar commented on files/en-us/mozilla/firefox/releases/51/index.md
> +- The [PAC](</en-US/docs/Mozilla/Projects/Necko/Proxy_Auto-Configuration_(PAC)_file>) `FindProxyForURL(url, host)` function now strips paths and queries from https\:// URLs to avoid information leaka
I'm in favour of removing the ancient info link. Cos it's hard to find the same articles. And the site isn't coming back.
```suggestion
- The [PAC](</en-US/docs/Mozilla/Projects/Necko/Proxy_Auto-Configuration_(PAC)_file>) `FindProxyForURL(url, host)` function now strips paths and queries from https\:// URLs to avoid information leakage (see [Firefox bug 1255474](https://bugzil.la/1255474), sniffing HTTPS URLS with malicious PAC files, or `CVE-2017-5384`).
```

2024-09-06 14:23 UTC, OnkarRuikar commented
A few points to discuss:
Why should we not use web archives? In the old FF release docs, we used them extensively because we wanted to preserve history.
- Google [decommissioned its URL shortener](https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/). That is why I think we need to be careful about non-reputed URL shorners.
- The MDN warning tool needs a file that would maintain ignore list.

2024-09-06 14:57 UTC, Josh-Cena commented
> The MDN warning tool needs a file that would maintain ignore list.

We already do; it's under `config/`.

> Why should we not use web archives?

Web archives are used when we need to specifically point to one website; for example, "web technology X" that's now obsolete and the website has been decommissioned. On the other hand, if we are just linking to a blog post to illustrate a point, then we can just pick another article to achieve the same effect.

I don't have huge problems with web archives but:

1. Sometimes sites are just off transiently. If we keep the link, it may be fixed without any action from us.
2. Web archives are slow to open, not automatically checkable, and are "stuck" forever.

> we need to be careful about non-reputed link shorteners.

I'm fairly sure that this is an official Mozilla shortener, no?

Google is infamous for tearing down its own products. I don't think we need to distrust other shorteners, especially when it has already been there for many years.

2024-09-08 17:15 UTC, Josh-Cena commented on files/en-us/learn/common_questions/tools_and_setup/available_text_editors/index.md
>          >
```suggestion
        <a href="https://macromates.com/manual/en/">Online Manual</a>
```

2024-09-08 17:15 UTC, Josh-Cena commented on files/en-us/learn/common_questions/tools_and_setup/available_text_editors/index.md
> +- [NetBeans IDE](https://netbeans.apache.org/front/main/index.html)
```suggestion
- [NetBeans IDE](https://netbeans.apache.org/)
```

2024-09-08 17:17 UTC, Josh-Cena approved these changes

2024-09-08 17:17 UTC, Josh-Cena commented on files/en-us/learn/common_questions/tools_and_setup/how_much_does_it_cost/index.md
> +Many editors are free, for example [Brackets](https://brackets.io/), [Bluefish](https://bluefish.openoffice.nl/index.html), [TextWrangler](https://www.barebones.com/products/textwrangler/), [Eclipse]
```suggestion
Many editors are free, for example [Brackets](https://brackets.io/), [Bluefish](https://bluefish.openoffice.nl/index.html), [TextWrangler](https://www.barebones.com/products/textwrangler/), [Eclipse](https://www.eclipse.org/), [Netbeans](https://netbeans.apache.org/), and [Visual Studio Code](https://code.visualstudio.com/). Some, like [Sublime Text](https://www.sublimetext.com/), you can test as long as you like, but you're encouraged to pay. Some, like [PhpStorm](https://www.jetbrains.com/phpstorm/), can cost between a few dozen and 200 dollars, depending on the plan you purchase. Some of them, like [Microsoft Visual Studio](https://visualstudio.microsoft.com/), can cost hundreds, or thousands of dollars; though Visual Studio Community is free for individual developers or open source projects. Often, for-pay editors will have a trial version.
```

2024-09-08 17:17 UTC, Josh-Cena commented on files/en-us/mozilla/firefox/releases/51/index.md
> +- The [PAC](</en-US/docs/Mozilla/Projects/Necko/Proxy_Auto-Configuration_(PAC)_file>) `FindProxyForURL(url, host)` function now strips paths and queries from https\:// URLs to avoid information leaka
```suggestion
- The [PAC](</en-US/docs/Mozilla/Projects/Necko/Proxy_Auto-Configuration_(PAC)_file>) `FindProxyForURL(url, host)` function now strips paths and queries from https\:// URLs to avoid information leakage (see [Firefox bug 1255474](https://bugzil.la/1255474) and [CVE-2017-5384](https://nvd.nist.gov/vuln/detail/CVE-2017-5384)).
```

2024-09-08 17:19 UTC, merged