update createBuffer() page to increase readability
mdn/content pull request #3578
Opened 2021-03-27 22:44 UTC by hamirmahal

> What was wrong/why is this fix needed? (quick summary only)

I think there's room for improvement in the readability of the `createBuffer()` page.

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBuffer

> Issue number (if there is an associated issue)

n/a

> Anything else that could help us review it

This is a minor change that just affects one paragraph.

2021-03-30 00:08 UTC, wbamberg requested changes
Thanks @hamirmahal ! I thought some of your changes were for the better, and some weren't :).

2021-03-30 00:08 UTC, wbamberg commented on files/en-us/web/api/baseaudiocontext/createbuffer/index.html
> +    data and give back decoded samples, but this ability is no longer in the specification,
```suggestion
    data and give back decoded samples, but this ability was removed from the specification,
```

It's a minor point but I think "was removed from" is better than "is no longer in" (active versus passive voice). I agree that "spec" => "specification" is better.

2021-03-30 00:08 UTC, wbamberg commented on files/en-us/web/api/baseaudiocontext/createbuffer/index.html
> +    then play via an {{ domxref("AudioBufferSourceNode") }}. For simple use cases
```suggestion
    <code>decodeAudioData()</code> does the same thing — takes compressed audio, such as an
    MP3 file, and directly gives you back an {{ domxref("AudioBuffer") }} that you can
    then play via an {{ domxref("AudioBufferSourceNode") }}. For simple use cases
```

2021-03-30 20:08 UTC, hamirmahal commented on files/en-us/web/api/baseaudiocontext/createbuffer/index.html
> +    data and give back decoded samples, but this ability is no longer in the specification,
Sounds good!

2021-03-30 20:09 UTC, hamirmahal commented
You're welcome, @wbamberg! No problem. I committed your suggestions.

2021-03-30 20:49 UTC, wbamberg approved these changes
Thanks @hamirmahal !

2021-03-30 20:49 UTC, merged

2021-03-31 16:35 UTC, hamirmahal commented
You're welcome, @wbamberg! Happy to help.