fix(markdownlint): report 'rgba()', 'hsla()', and old color syntax
mdn/content pull request #35807
Opened 2024-09-09 11:28 UTC by OnkarRuikar

Some people are still using the old color syntax, old `rgba()`, and old `hsla()` functions. The PR adds lint rule to report the cases.

**Note**: There was a suggestion to use [Stylelint to do this](https://stylelint.io/user-guide/rules/color-function-notation/). I don't think the stylelint works on markdown files. Also, like ESLint, Stylelint is a linter, so we may face the same issues using it on the CSS code spread over multiple code fences. Got no response from the concerned person when asked on Discord. So sending this PR that uses regex and markdownlinter.

2024-09-09 14:02 UTC, Josh-Cena commented
I believe you can run stylelint with https://www.npmjs.com/package/postcss-markdown as a preprocessor.

2024-09-09 14:09 UTC, fred-wang commented on .markdownlint.jsonc
> +        "message": "Dont't use the old syntax that uses commas. Use the new syntax that uses spaces instead.",
Don't

2024-09-09 14:10 UTC, fred-wang approved these changes
MathML: LGTM

2024-09-09 14:10 UTC, fred-wang commented on files/en-us/web/mathml/global_attributes/mathcolor/index.md
>  ## Syntax
I believe these are just examples. I think it's fine to use the new color syntax here, rather than disabling lint.

2024-09-10 16:48 UTC, Mouvedia commented
> I don't think the stylelint works on markdown files.

https://github.com/ota-meshi/postcss-markdown#linting-with-stylelint

2024-09-11 14:08 UTC, bsmth requested changes
I was revisiting this one again and I'm -1 on this PR.

I don't think we should forbid the use of `rgba()` and `hsla()` via linting, essentially. Similar to this comment: https://github.com/mdn/content/pull/35613#pullrequestreview-2289436859 we should be able to mention the old syntax in docs. `rgba()` is still widespread, and we need to explain to readers how it works if they find us through web search, but make sure when we mention the old syntax, we're promoting about modern alternatives.

2024-09-12 03:49 UTC, OnkarRuikar commented
I don't understand. We deleted the[ `rgba()` and `hsla()` pages](https://github.com/mdn/content/pull/23387) two years ago. We've already [replaced all the `rgba()`s in the content](https://github.com/mdn/content/pull/35613). So we are not explaining `rgba()` anywhere in content apart from the rightful places, i.e. https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb

> if they find us through web search, but make sure when we mention the old syntax,

We are not outright removing it from the entire repo. We are keeping them on the [rgb and hsl pages](https://github.com/mdn/content/pull/35807/files#diff-d94772e5c0be0b79fb2a89c2a1098d7a3e43d31e65fc25a90ae22f44d86afe78), because when you query rgba and hsla, readers will land on those pages.

> we need to explain to readers how it works

The lint rule is not that strict. It is going to [lint only the code fences](https://github.com/mdn/content/pull/35807/files#diff-a3896a09199fcbefc9739d4db147cbc9b55a1c45d1cadb776c89613bc890ab3aR238) and not prose. So, the `rgba()` and `hsla()` can be mentioned and explained in prose without hindrance and if really required, used in code blocks with magic comments.

So, this change will nudge contributors away from using the old functions, but it _doesn't entirely prevent them from doing so_.

2024-09-12 13:13 UTC, Josh-Cena commented
I don't see any signs of `rgba` being legacy. The only thing marked as legacy is the comma-separated syntax. So the motivation of this change would only be for consistency and stylistic preferences rather than for modernity. FWIW, I would go as far as preferring `rgba` when an alpha component is present just for the semantics. But, at the end of the day, it's not typical for us to impose stylistic preferences on how code should be written, especially enforcing them via linting—for example, we don't enforce using shorthand properties; we don't require using some array methods over others; etc.

2024-09-12 13:16 UTC, Josh-Cena commented
I just noticed that the note on `rgb` says

> It is recommended to use rgb().

I'm sure we'll get someone complaining that there's nothing wrong with `rgba()`, but we shall see. I have no opinions on which ones _we_ use, and it does have its supporting arguments (shaving off one byte...?) But I really don't want to take this choice away from writers.

2024-09-25 16:02 UTC, OnkarRuikar commented
We discussed this in the community call today. Linting these features is too early. Closing this PR for now.

2024-09-25 16:02 UTC, closed without merging