fix: flaws in web/javascript batch 6
mdn/content pull request #3583
Opened 2021-03-27 23:33 UTC by nschonni

2021-04-20 01:33 UTC, nschonni commented
@wbamberg any issues with this one?

2021-04-21 02:57 UTC, wbamberg requested changes
I think there's one place where the fix should be to correct the slug for the target of a link. Otherwise this looks great to me.

2021-04-21 02:57 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/webassembly/runtimeerror/index.html
> + <dt><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/RuntimeError/RunTimeError"><code>WebAssembly.RuntimeError()</code></a></dt>
It looks like the slug for this page is wrong:

https://github.com/mdn/content/blob/d2d2314c40b95b5c408d8f27d704f299b4660d03/files/en-us/web/javascript/reference/global_objects/webassembly/runtimeerror/runtimeerror/index.html#L3

...should be "Web/JavaScript/Reference/Global_Objects/WebAssembly/RuntimeError/RuntimeError"

Probably better to fix it there?

2021-04-21 03:12 UTC, nschonni commented on files/en-us/web/javascript/reference/global_objects/webassembly/runtimeerror/index.html
> + <dt><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/RuntimeError/RunTimeError"><code>WebAssembly.RuntimeError()</code></a></dt>
Yeah, if the slug is fixed there, the next time a flaw run is done across the repo, it'll fix the occurrences

2021-05-13 14:08 UTC, closed without merging