New pages: HTMLInputElement checkedness
mdn/content pull request #35880
Opened 2024-09-14 00:37 UTC by estelle

part of https://github.com/mdn/content/issues/35544

2024-09-14 00:51 UTC, Josh-Cena requested changes

2024-09-14 00:51 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/checked/index.md
> +The **`checked`** property of the {{DOMxRef("HTMLInputElement")}} interface specifies the current checkedness of the element; whether the form control is checked or not. It reflects the {{htmlelement
```suggestion
The **`checked`** property of the {{DOMxRef("HTMLInputElement")}} interface specifies the current checkedness of the element; that is, whether the form control is checked or not. It reflects the {{htmlelement("input")}} element's [`checked`](/en-US/docs/Web/HTML/Element/input#checked) attribute.
```

2024-09-14 00:51 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/checked/index.md
> +The boolean `checked` attribute is valid for the `radio`([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/i
```suggestion
The boolean `checked` attribute is valid for the `radio` ([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/input/checkbox)) input types.
```

2024-09-14 00:51 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/checked/index.md
> +A boolean attribute indicating whether this checkbox is checked by default (when the page loads). It does not indicate whether this checkbox is currently checked: if the checkbox's state is changed,
Then it does not "reflect" the attribute. An attribute is only "reflected" by a property if getting/setting the property is equivalent to getting/setting the attribute. Indeed, the `checked` attribute is reflected by the `defaultChecked` property, just like the `value` attribute is reflected by the `defaultValue` property.

2024-09-14 00:51 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/defaultchecked/index.md
> +The **`defaultChecked`** property of the {{DOMxRef("HTMLInputElement")}} interface specifies the default checkedness state of the element. This property represents the {{htmlelement("input")}} elemen
```suggestion
The **`defaultChecked`** property of the {{DOMxRef("HTMLInputElement")}} interface specifies the default checkedness state of the element. This property reflects the {{htmlelement("input")}} element's [`checked`](/en-US/docs/Web/HTML/Element/input#checked) attribute.
```

(Perhaps you could further clarify that the `checked` attribute in fact only sets the default state.)

2024-09-14 00:51 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/defaultchecked/index.md
> +The boolean `checked` attribute is valid for the `radio`([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/i
```suggestion
The boolean `checked` attribute is valid for the `radio` ([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/input/checkbox)) input types.
```

2024-09-15 20:58 UTC, estelle commented on files/en-us/web/api/htmlinputelement/checked/index.md
> +A boolean attribute indicating whether this checkbox is checked by default (when the page loads). It does not indicate whether this checkbox is currently checked: if the checkbox's state is changed,
updated!

2024-09-15 21:00 UTC, estelle commented on files/en-us/web/api/htmlinputelement/defaultchecked/index.md
> +The boolean `checked` attribute is valid for the `radio` ([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/
```suggestion
The boolean [`checked`](/en-US/docs/Web/HTML/Element/input#checked) attribute is valid for the `radio` ([`<input type="radio">`](/en-US/docs/Web/HTML/Element/input/radio)) and `checkbox` ([`<input type="checkbox">`](/en-US/docs/Web/HTML/Element/input/checkbox)) input types. The presence of the attribute sets the `defaultChecked` property to `true`.
```

2024-09-15 22:20 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/checked/index.md
> +The presence of the boolean [`checked`](/en-US/docs/Web/HTML/Element/input#checked) attribute indicates the checkbox is checked by default. It does not indicate whether this checkbox is currently che
```suggestion
The presence of the HTML [`checked`](/en-US/docs/Web/HTML/Element/input#checked) attribute indicates the checkbox is checked by default. It does not indicate whether this checkbox is currently checked: if the checkbox's state is changed, this content attribute does not reflect the change; only the `HTMLInputElement`'s `checked` IDL property is updated. The `checked` attribute is reflected by the {{domxref("HTMLInputElement.defaultChecked", "defaultChecked")}} property.
```

2024-09-15 22:27 UTC, Josh-Cena approved these changes

2024-09-16 10:44 UTC, merged