Update two manifest member (BCD data removed)
mdn/content pull request #35926
Opened 2024-09-18 05:41 UTC by skyclouds2001

### Description

see https://github.com/mdn/browser-compat-data/pull/23774, the two's BCD data is removed, but the two is still standard: so `browser-compat` key removed and `spec-urls` key added, also update *Browser compatibility* section with a sentence explaining the support status

### Motivation

### Additional details

### Related issues and pull requests

2024-09-20 18:55 UTC, dipikabh requested changes
Thanks a lot @skyclouds2001 for this PR! You beat me to it :)

the updates are good, just a minor nit with the wording

2024-09-20 18:55 UTC, dipikabh commented on files/en-us/web/manifest/categories/index.md
> +The feature is not supported by any of the browser implement yet.
```suggestion
The feature is not implemented by any browser yet.
```

2024-09-20 18:55 UTC, dipikabh commented on files/en-us/web/manifest/screenshots/index.md
> +The feature is not supported by any of the browser implement yet.
same here

2024-09-21 07:31 UTC, skyclouds2001 commented on files/en-us/web/manifest/screenshots/index.md
> +The feature is not supported by any of the browser implement yet.
```suggestion
The feature is not implemented by any browser yet.
```

2024-09-21 14:50 UTC, Josh-Cena commented
This wording implies that they should be supported by browsers but they are not. While if you read the BCD PR the motivation is "this is an app store feature and has nothing to do with browsers". Therefore we should probably say something similar to that: "Browser compatibility is irrelevant because this member is not used by browsers, but by app stores when publishing your app."

2024-09-21 18:37 UTC, skyclouds2001 commented
> Browser compatibility is irrelevant because this member is not used by browsers, but by app stores when publishing your app.

I think the following is better:

> Browser compatibility is irrelevant because this feature is not used by browsers, but by app stores when publishing your app. Though some browsers may use this feature, there is no requirement for browsers to implement any form of support."

2024-09-23 20:52 UTC, dipikabh commented
Thanks for pointing that out @Josh-Cena, that makes sense.

We could word it as:

> This manifest member is used by app stores and catalogs when publishing and listing web apps, so browser compatibility is not applicable. Browsers may parse this information, but it's optional and doesn't affect the core functionality of a web app. 

@skyclouds2001, WDYT?

2024-09-24 02:35 UTC, skyclouds2001 commented on files/en-us/web/manifest/screenshots/index.md
> +The feature is not implemented by any browser yet.
```suggestion
This manifest member is used by app stores and catalogs when publishing and listing web apps, so browser compatibility is not applicable. Browsers may parse this information, but it's optional and doesn't affect the core functionality of a web app.
```

2024-09-24 02:35 UTC, skyclouds2001 commented on files/en-us/web/manifest/categories/index.md
> +The feature is not implemented by any browser yet.
```suggestion
This manifest member is used by app stores and catalogs when publishing and listing web apps, so browser compatibility is not applicable. Browsers may parse this information, but it's optional and doesn't affect the core functionality of a web app.
```

2024-09-24 02:39 UTC, skyclouds2001 commented
Updated!

2024-09-24 02:39 UTC, zhowan2020 commented
[](url)

2024-09-24 02:39 UTC, zhowan2020 commented
Duplicate of #`

2024-09-24 13:14 UTC, dipikabh approved these changes
Thanks!

2024-09-24 13:14 UTC, merged