add information about <param> element deprecation
mdn/content pull request #35943
Opened 2024-09-18 20:35 UTC by ramyaparimi

### Description

This PR adds information about <param> element deprecation and linked [param page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/param) for more information.

Fixes https://github.com/mdn/content/issues/35681 

### Motivation

### Additional details

### Related issues and pull requests

2024-09-23 09:36 UTC, chrisdavidmills requested changes
Hi there @ramyaparimi, and thank you for your MDN contribution! I have a few thoughts on how you can improve it further. See my comment below.

Best regards.

2024-09-23 09:36 UTC, chrisdavidmills commented on files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
> +        <code>&#x3C;object></code> ({{htmlelement("param")}} element is deprecated. See {{htmlelement("param")}} for more information)
This is not a great way to fix the problem. It is repetitive (we've now got three links to the `<param>` reference page in the same table cell), and it doesn't tell the reader what to do instead; they have to guess, or go and look at the `<param>` page, which tells them to "Use the [`<object>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) element with a [`data`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object#data) attribute to set the URL of an external resource."

But that's covered in the first row of the table anyway. Looking at the attributes of `<object>` and `<embed>` that are not marked as obsolete, there is not really anything else they can do beyond what is already mentioned in the top three rows of the table. I would advise that you completely remove this row of the table.

You also need to update the last row of the table to remove the mention of `<param>`. Maybe update it to "contained within the opening and closing `<object>` tags"?

2024-09-23 15:35 UTC, ramyaparimi commented on files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
> +        <code>&#x3C;object></code> ({{htmlelement("param")}} element is deprecated. See {{htmlelement("param")}} for more information)
Thank you for the detailed information and explanation. I did feel a little uncomfortable linking param multiple times to simply divert to the param page but I didn't really know how else to handle. 
Your explanation helped me understand how to handle situations like this. I also realized it is okay to ask clarifying questions when in doubt 😄 .

2024-09-24 07:24 UTC, chrisdavidmills commented on files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
> +        <code>&#x3C;object></code> ({{htmlelement("param")}} element is deprecated. See {{htmlelement("param")}} for more information)
Yes, absolutely! If there is one aspect of a bug or issue you are unsure how to handle, you are more than welcome to ask questions, either in the issue or in a pull request you've opened to try to fix it.

Generally, it is better to help the reader get an answer to a question in as small a number of steps as possible, but this also needs to be balanced with repetition. If you can repeat a single line on a page to stop them having to navigate to another page and search, that is a good tradeoff. However, if the answer is an entire section, it might be better to link to it rather than repeat it.

On to your fix — it looked mostly pretty good, except that you seemed to mix the table row I said you should get rid of, and the one I said you should keep but update. I've taken the liberty of adding a commit to your to your PR to fix that, plus I've also made some other corrections to what was previously there (such as capitalizations).

I hope that's OK; I still really appreciate the time you've taken to help fix this issue, and I look forward to seeing more contributions from you in the future. Feel free to ask more questions; I'm always happy to help.

2024-09-24 07:26 UTC, chrisdavidmills approved these changes
LGTM; merging.

2024-09-24 07:26 UTC, merged

2024-09-24 18:39 UTC, ramyaparimi commented on files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.md
> +        <code>&#x3C;object></code> ({{htmlelement("param")}} element is deprecated. See {{htmlelement("param")}} for more information)
Thanks a bunch for the encouragement! And yes, it is absolutely okay to make the changes. I am still working on getting myself comfortable with contributing to the MDN docs. I definitely look forwarding to contributing more!
Already having 👀 on one of the issues to work on next!