Add scheduler.yield()
mdn/content pull request #35960
Opened 2024-09-19 16:45 UTC by brendankenny

### Description

Chrome 129 adds [`yield`](https://wicg.github.io/scheduling-apis/#dom-scheduler-yield) method to the [Scheduler interface](https://developer.mozilla.org/en-US/docs/Web/API/Scheduler). This PR adds reference documentation for the new method.

### Additional details
- [ChromeStatus entry](https://chromestatus.com/feature/6266249336586240)
- The [BCD PR for scheduler.yield()](https://github.com/mdn/browser-compat-data/pull/24439)
- [Chrome Beta announcement](https://developer.chrome.com/blog/chrome-129-beta#scheduleryield)

2024-09-19 20:54 UTC, tunetheweb reviewed
Overall LGTM.

Have a few (non-blocking) comments where it could potentially be improved further.

2024-09-19 20:54 UTC, tunetheweb commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +The main API methods are {{domxref('scheduler.postTask()')}} and {{domxref('scheduler.yield()')}}. `scheduler.postTask()` takes a callback function ("the task") and returns a promise that resolves wi
Worth calling out some more differences here?

- That `postTask` has more options for setting priority and/or aborting the task
- But that `scheduler.yield` is simpler to use as can be added without wrapping code in a function.

2024-09-19 20:54 UTC, tunetheweb commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +`scheduler.postTask()` creates a task with default priority [`user-visible`](#user-visible) that has a fixed priority and cannot be aborted.
Maybe:

```suggestion
`scheduler.postTask()` creates a task with an optional priority (defaulted to [`user-visible`](#user-visible)) that cannot be aborted.
```

And can it not be aborted? I thought that was one of the benefits of `postTask` over `yield` (see my comment above). What's https://developer.mozilla.org//en-US/docs/Web/API/Scheduler/postTask#aborting_tasks all about?

Or does this mean the default call can't be aborted (since it doesn't provide a `signal` argument). If so this should be reworded (appreciate you didn't write the original, but still let's fix this while in here).

2024-09-19 20:54 UTC, tunetheweb commented on files/en-us/web/api/scheduler/yield/index.md
> +For instance, if a `change` event listener on a checkbox results in a lot of work to filter content and update the page, this means there will be no visual feedback to the user that the checkbox was
This is a valid example. However, I worry about encouraging "no-op" yields.

Maybe should start with an example:

```js
button.addEventListener("click", async () => {
  // Provide feedback that the action was received, and is being processed
  await scheduler.yield();
  // Do longer processing
});
```

And then move on to your example: "It may also be sufficient to have the browser default actions provide that feedback. For instance, if a `change` event listener on a checkbox..."

2024-09-19 20:54 UTC, tunetheweb commented on files/en-us/web/api/scheduler/yield/index.md
> +`scheduler.yield()` enqueues its task at the front of a priority level's queue, while `scheduler.postTask()` tasks go at the end (in the spec, this is defined by a task queue's [effective priority](h
Whhhattt! This is news to me!

Even more reason to use `yield` over `postTask` then!

2024-09-20 15:59 UTC, malchata commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +The main API methods are {{domxref('scheduler.postTask()')}} and {{domxref('scheduler.yield()')}}. `scheduler.postTask()` takes a callback function ("the task") and returns a promise that resolves wi
```suggestion
The main API methods are {{domxref('scheduler.postTask()')}} and {{domxref('scheduler.yield()')}}. `scheduler.postTask()` takes a callback function (the task) and returns a promise that resolves with the return value of the function, or rejects with an error. `scheduler.yield()` turns any async function into a task by yielding the main thread to the browser for other work, with execution continuing when the returned promise is resolved.
```

2024-09-20 16:00 UTC, malchata commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +To break up long-runing JavaScript so it doesn't block the main thread, a `scheduler.yield()` can be inserted to temporarily yield the main thread back to the browser, which creates a task to continu
```suggestion
To break up long-running JavaScript tasks so they don'tt block the main thread, a call to `scheduler.yield()` can be inserted to temporarily yield the main thread back to the browser, which creates a task to continue execution where it left off.
```

2024-09-20 16:05 UTC, malchata reviewed
I think this generally looks fine, but I added a couple of suggestions for prose.

2024-09-20 16:05 UTC, malchata commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +`scheduler.yield()` returns a promise that can be awaited for when execution can continue. This allows work that belongs in the same function to stay in the same function but without blocking the mai
```suggestion
`scheduler.yield()` returns a promise that can be awaited for when execution can continue. This allows work that belongs in the same function to stay in the same function, but without blocking the main thread the entire time the function runs.
```

2024-09-20 16:05 UTC, malchata commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +`scheduler.yield()` takes no arguments. The task that triggers its continuation has a default [`user-visible`](#user-visible) priority, but if a `scheduler.yield()` is run within a `scheduler.postTas
```suggestion
`scheduler.yield()` takes no arguments. The task that triggers its continuation has a default [`user-visible`](#user-visible) priority, but if `scheduler.yield()` is called within a `scheduler.postTask()` callback, it will [inherit the priority of the surrounding task](/en-US/docs/Web/API/Scheduler/yield#inheriting_task_priorities).
```

2024-09-20 16:05 UTC, malchata commented on files/en-us/web/api/scheduler/yield/index.md
> +Similarly, the continuation of work after the `yield()` can be aborted if it occurs within a `postTask()` task and the [task is aborted](/en-US/docs/Web/API/Scheduler/postTask#aborting_tasks).
```suggestion
Similarly, the continuation of work after the `yield()` can be aborted if it occurs within a `postTask()` callback, and the [task is aborted](/en-US/docs/Web/API/Scheduler/postTask#aborting_tasks).
```

2024-09-20 16:05 UTC, malchata commented on files/en-us/web/api/scheduler/yield/index.md
> +Long tasks can be broken up by awaiting `scheduler.yield()`. The function returns a promise, yielding the {{Glossary('main thread')}} to allow the browser to execute other pending work—like respondin
I feel like this glossary definition should be linked much earlier in the guide.

2024-09-20 16:05 UTC, malchata commented on files/en-us/web/api/scheduler/yield/index.md
> +For instance, if a `change` event listener on a checkbox results in a lot of work to filter content and update the page, this means there will be no visual feedback to the user that the checkbox was
```suggestion
For instance, if a `change` event listener on a checkbox results in a lot of work to filter content and update the page, this means there will be no visual feedback to the user that the checkbox was checked until that work is complete. A `scheduler.yield()` can be inserted into the event listener to yield early so the checked state will be seen immediately, and then the remainder of the work can be done when the yield returns.
```

2024-09-23 18:31 UTC, brendankenny reviewed
also clarified the priority inheritance to be the best kind of correct, and added mention of requestIdleCallback priority inheritance

2024-09-23 23:49 UTC, philipwalton commented on files/en-us/web/api/scheduler/yield/index.md
> +Long tasks can be broken up by awaiting `scheduler.yield()`. The function returns a promise, yielding the main thread to allow the browser to execute other pending work—like responding to user input—
```suggestion
Long tasks can be broken up by awaiting `scheduler.yield()`. The function returns a promise, yielding to the main thread to allow the browser to execute other pending work—like responding to user input—if needed. The browser schedules a follow-up task that resovles the promise, at which point execution of the code can continue where it left off.
```

2024-09-23 23:49 UTC, philipwalton commented on files/en-us/web/api/scheduler/yield/index.md
> +```js
Should this code block call these functions?

2024-09-23 23:49 UTC, philipwalton commented on files/en-us/web/api/scheduler/yield/index.md
> +A `scheduler.yield()` within a `scheduler.postTask()` task will inherit the task's priority. For example, work after a `scheduler.yield()` within a [`'background'`](/en-US/docs/Web/API/Prioritized_Ta
I'm not familiar with the MDN style guide, but I noticed that you have single quotes around the string 'background' here but then use double quotes  in the code snippet.

2024-09-24 19:44 UTC, brendankenny commented on files/en-us/web/api/scheduler/yield/index.md
> +```js
> Should this code block call these functions?

yes, thanks!

2024-09-24 19:44 UTC, brendankenny commented on files/en-us/web/api/scheduler/yield/index.md
> +A `scheduler.yield()` within a `scheduler.postTask()` task will inherit the task's priority. For example, work after a `scheduler.yield()` within a [`'background'`](/en-US/docs/Web/API/Prioritized_Ta
Damn you prettier. Switching to double quotes for everything 🤮

2024-09-24 19:45 UTC, brendankenny commented
@chrisdavidmills I think this is ready for you

2024-09-25 06:08 UTC, Josh-Cena commented on files/en-us/web/api/scheduler/yield/index.md
> +{{APIRef('Prioritized Task Scheduling API')}}
```suggestion
{{APIRef('Prioritized Task Scheduling API')}}{{AvailableInWorkers}}
```

2024-09-25 12:17 UTC, chrisdavidmills requested changes
@brendankenny nice work! I've reviewed this pretty thoroughly and left quite a few comments, but most of them are fairly minor language suggestions/nitpicks.

2024-09-25 12:17 UTC, chrisdavidmills commented on files/en-us/web/api/scheduler/yield/index.md
> +#### Within `requestIdleCallback`
Also, I'd consider making this an h3 section, and moving it to below the "Aborting a yield" section, because it mentions aborting, so it reads as if you've already discussed it.

2024-09-25 12:17 UTC, chrisdavidmills commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +`scheduler.postTask()` is more configurable, like explicitly setting its task priority or `AbortSignal` to cancel the task. `scheduler.yield()` is simpler and can be `await`ed in any async function w
```suggestion
The two methods have similar functionality but different levels of control. `scheduler.postTask()` is more configurable — for example, it allows task priority to be explicitly set and task cancellation via an [`AbortSignal`](/en-US/docs/Web/API/AbortSignal). `scheduler.yield()` on the other hand is simpler and can be `await`ed in any `async` function without having to provide a followup task in another function.
```

2024-09-25 14:38 UTC, brendankenny commented on files/en-us/web/api/prioritized_task_scheduling_api/index.md
> +`scheduler.postTask()` called with no arguments creates a task with a default [`user-visible`](#user-visible) priority that cannot be aborted or have its priority changed.
Trying to clarify that this is just when it's called with no arguments:
```suggestion
When `scheduler.postTask()` is called with no arguments, it creates a task with a default [`user-visible`](#user-visible) priority that cannot be aborted or have its priority changed.
```

2024-09-25 15:38 UTC, brendankenny commented
Thanks for the great review @chrisdavidmills! I believe everything should be addressed.

2024-09-25 16:24 UTC, chrisdavidmills approved these changes
Nice work @brendankenny. Let's get this published, and we can iterate further if needed.

2024-09-25 16:24 UTC, merged