docs(manifest): Improvements to `orientation` page
mdn/content pull request #35977
Opened 2024-09-20 18:38 UTC by dipikabh

### Description

This work is part of improving the web/manifest docs.

Apart from normalizing the page layout to include "Syntax" and "Values", this PR includes the following changes:

- Explains all the orientation values
- Adds a "Description" section to show a visual representation of the orientations and cover all the info from the spec
- Adds prose to the existing example in "Examples" and adds another example with a scenario to explain the concept

### Motivation

To ensure all sections have sufficient explanation, all caveats from spec are covered, and the pages follow a similar template

### Additional details

Spec links: 
  - https://w3c.github.io/manifest/#orientation-member
  - https://w3c.github.io/screen-orientation/#screen-orientation-types

### Related issues and pull requests

Tracking issue: https://github.com/mdn/mdn/issues/560

Fixes https://github.com/mdn/content/issues/34927

2024-09-23 11:29 UTC, chrisdavidmills requested changes
Hi @dipikabh! Thanks for you awesome work on this, such an improvement of the existing manifest pages. I love that you taking this on.

I have some comments for you — mostly not serious.

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +{{EmbedLiveSample('Description', '', 800)}}
I love that you've created this with HTML and CSS!

OK, this is going to sound really nitpicky, but the small circle looks a bit odd. I'm assuming you want this to represent the hardware button at the bottom of the screen on older iPads and Android phones? You could make it look more like one of those buttons with CSS like this:

```css
.button {
  width: 20px;
  height: 20px;
  border-radius: 5px;
  background-color: darkgrey;
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  border-top: 1px solid #888;
  border-left: 1px solid #888;
}
```

(you'd have to vary the sides the borders are on in each orientation, to make the shadowing look consistent).

Or, you could do away with the button and write "top" and "bottom" at the top and bottom in each case. But that wouldn't look as nice. 

Just some thoughts, anyway.

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +For example, a video app is often better suited in landscape orientation, while a reading app typically works better in portrait orientation.
```suggestion
For example, a video app is often better suited to landscape orientation, while a reading app typically works better in portrait orientation.
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +- Web app manifest
```suggestion
- Web app manifest:
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +- Screen Orientation API
```suggestion
- Screen Orientation API:
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +  - It uses the orientation values to actively lock the screen to a specific orientation.
```suggestion
  - Uses orientation values to lock the screen to a specific orientation.
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +  - It allows dynamic changes to orientation during runtime (e.g., `screen.orientation.lock()`)
```suggestion
  - Allows dynamic changes to orientation during runtime (for example locking orientation using {{domxref("ScreenOrientation.lock", "screen.orientation.lock()")}})
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +> While the `orientation` manifest member sets the default orientation of the web app, the orientation of a top-level browsing context can be changed once the web app is running. This can be done thr
Is this note needed? It basically says the same thing as your bullets above. This seems repetitive as-is.

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +Remember that although it is encouraged, browsers may or may not implement the Screen Orientation API.
This wording is a bit odd. Maybe change it to something like "The Screen Orientation API has limited browser support. Check compatibility carefully before using."?

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +Remember that although it is encouraged, browsers may or may not implement the Screen Orientation API.
Also maybe make it a note if you agree with my previous comment about removing the note.

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +Certain UI/UX concerns and platform conventions may limit which screen orientations and [`display`]((/en-US/docs/Web/Manifest/display) modes can be used together.
```suggestion
Certain UI/UX concerns and platform conventions may limit which screen orientations and [`display`](/en-US/docs/Web/Manifest/display) modes can be used together.
```

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +Certain UI/UX concerns and platform conventions may limit which screen orientations and [`display`]((/en-US/docs/Web/Manifest/display) modes can be used together.
(extra paren is currently breaking the link)

2024-09-23 11:29 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +Consider this example of a photo viewing and editing app that works on both mobile phones and tablets. In the app's manifest file, as shown below, the `orientation` is set to `any`, allowing the app
Thinking about how patchy Screen Orientation API support is, is it wise to recommend using it for this kind of purpose? The [Screen Orientation API docs](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Orientation_API) suggests not, and actually link to a guide where this is done using CSS media queries.

2024-09-26 22:19 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +  - : A string with a keyword value, which includes:
Agree, it is reading odd. I wanted to convey that the value can be one of the keywords. This might be better:

>   - : A string that specifies a default orientation for the web app. The value must be one of the following keywords:

2024-09-26 22:29 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +      - : Displays the web app in the most natural orientation(s) for the device, as determined by the operating system, browser, user settings or the screen itself.
Valid point. I don't know why I wrote "orientation(s). Updating as:

>  - : Displays the web app in the most natural orientation for the device, as determined by the browser, operating system, user settings, or the screen itself.

2024-09-30 03:27 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +Consider this example of a photo viewing and editing app that works on both mobile phones and tablets. In the app's manifest file, as shown below, the `orientation` is set to `any`, allowing the app
Agree, removed the reference to the API and made the example prose a bit more generic

2024-09-30 03:29 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +Remember that although it is encouraged, browsers may or may not implement the Screen Orientation API.
Added this note:

  > [!NOTE]
  > The Screen Orientation API's [`lock()`](/en-US/docs/Web/API/ScreenOrientation/lock) method has limited support across browsers.
  > Check its compatibility if you plan to use this it to dynamically change screen orientation during runtime.

2024-09-30 03:30 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +> While the `orientation` manifest member sets the default orientation of the web app, the orientation of a top-level browsing context can be changed once the web app is running. This can be done thr
Yeah, removed it from here. In fact, sticking thes note back to the top of the page where it was in the previous version

2024-09-30 03:32 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +{{EmbedLiveSample('Description', '', 800)}}
I've redone the figures to remove the buttons, instead added app title bar to add a hint for the top edge of the app. I've also added more prose to explain this illustration.

2024-09-30 03:34 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +        This setting is the most flexible and allows the web app to be rotated freely between any of these orientations as permitted by the device.
Done, all primary and secondary descriptions now convey that device rotation will not the app orientation

2024-09-30 03:38 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +        - `portrait-primary` is 0 degrees.
This and your other questions on the value descriptions made me again look into app orientation vs screen orientation. Thanks for the nudge!

I've now redone all value descriptions and removed the reference to angles (those are mentioned more with relations to screen orientations (https://www.w3.org/TR/screen-orientation/#the-current-screen-orientation-type-and-angle)). 

I've also added some more clarifying info in the "Description" section to differentiate between device vs screen vs app orientation.

2024-09-30 03:39 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +        This is typically the default `portrait` orientation.
Likely might have been a copy paste error. Thanks for spotting! Moved this to `portrait-primary`

2024-09-30 03:40 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +        This is typically the default `landscape` orientation.
Should be fixed now

2024-09-30 03:47 UTC, dipikabh commented
Hi Chris, thanks for the excellent review suggestions and questions. I ended up redoing a lot of content, so it took a bit longer.
I'd appreciate if you can take another look to see if it makes sense now. Thanks!!

2024-09-30 09:04 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +  - : A string with a keyword value, which includes:
I have read your update, and it looks much better now. Marking this as resolved.

2024-09-30 09:05 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +      - : Displays the web app in the most natural orientation(s) for the device, as determined by the operating system, browser, user settings or the screen itself.
Perfect. Resolving.

2024-09-30 09:10 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +If a browser supports the `orientation` value, it will use this as the default orientation for the web app throughout the life of the web app, unless overridden at runtime.
```suggestion
If a browser supports the `orientation` value, it will use this as the default orientation for the web app throughout its lifespan, unless overridden at runtime.
```

2024-09-30 09:10 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +        - `portrait-primary` is 0 degrees.
I've read through it all again. This is great, much improved.

2024-09-30 09:13 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +{{EmbedLiveSample('Description', '', 800)}}
Your updates are excellent. Resolving this.

2024-09-30 09:17 UTC, chrisdavidmills approved these changes
@dipikabh wonderful work, Dipika. I just noticed a couple more small typos. Approving, so you can merge when you've considered those.

2024-09-30 09:17 UTC, chrisdavidmills commented on files/en-us/web/manifest/orientation/index.md
> +  > Check its compatibility if you plan to use this it to dynamically change screen orientation during runtime.
```suggestion
  > Check its compatibility if you plan to use it to dynamically change screen orientation during runtime.
```

2024-10-01 16:18 UTC, dipikabh commented on files/en-us/web/manifest/orientation/index.md
> +If a browser supports the `orientation` value, it will use this as the default orientation for the web app throughout the life of the web app, unless overridden at runtime.
Updating as:

> If a browser supports the specified `orientation` value, it will use this as the default app orientation throughout the app's lifespan, unless overridden at runtime.

2024-10-01 16:22 UTC, dipikabh commented
Thanks @chrisdavidmills for taking a look at all the updates and going through the page again. Merging this shortly.

2024-10-01 16:25 UTC, merged