add[webAPI]: links to docs on mentioned methods
mdn/content pull request #3597
Opened 2021-03-28 11:45 UTC by AdrianSkar

Add links to replaceState and pushState to the *See also* section

> What was wrong/why is this fix needed? (quick summary only)
Nothing, just a minor enhancement.

> MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Web/API/History/state

2021-03-29 18:01 UTC, A1T0M3CK reviewed
api status in monitor run webos android in this ip 179.43.100.44

2021-03-29 22:56 UTC, wbamberg requested changes
Thanks for this, @AdrianSkar ! Looks good, but let's have code styling and use brackets for functions.

2021-03-29 22:56 UTC, wbamberg commented on files/en-us/web/api/history/state/index.html
> +  <li><a href="/en-US/docs/Web/API/History/replaceState">History.replaceState</a></li>
```suggestion
  <li><a href="/en-US/docs/Web/API/History/pushState"><code>History.pushState()</code></a></li>
  <li><a href="/en-US/docs/Web/API/History/replaceState"><code>History.replaceState()</code></a></li>
```

2021-03-30 07:28 UTC, AdrianSkar commented on files/en-us/web/api/history/state/index.html
> +  <li><a href="/en-US/docs/Web/API/History/replaceState">History.replaceState</a></li>
Much better. Thank you.

2021-03-30 16:38 UTC, wbamberg approved these changes
Thanks @AdrianSkar !

2021-03-30 16:38 UTC, merged