fix(cspell): sort and unique ignore lists
mdn/content pull request #36009
Opened 2024-09-23 09:48 UTC by OnkarRuikar

The PR adds pre-commit hooks to sort and uniq the cSpell ignore list files.

2024-09-23 14:06 UTC, Josh-Cena reviewed
Can you make this a CI check too? To avoid people bypassing it or committing from web interface.

2024-09-24 01:21 UTC, OnkarRuikar commented
> To avoid people bypassing it or committing from web interface.

Let's not prevent people from contributing. [Like other stuff](https://github.com/mdn/content/pull/36009/files#diff-00b16177a6e849b9b4f81126bb37adeee3b84639f4ca0eaf03f5e9d596fb420fR31-R33), we can always auto-fix it at midnight.

2024-09-24 01:36 UTC, Josh-Cena commented
Most people do not change cspell files. Those that do (usually to address the weekly spellcheck errors) should ensure that they are changed in a correct manner.

2024-09-24 01:55 UTC, Josh-Cena commented
Unfortunately I would expect them to fix obvious typos but not, say, add things to dictionaries. It's too much of a judgment call to tell what to do with each word and I'm afraid, putting myself into the shoes of a new contributor, they would not have the courage to do. For example, who knows if I should add `greetme` to the dictionary or if I should change it to `greetMe`? Who knows if this abbreviation is actually a standard and/or intentional? Again I think we are too optimistic about how much freedom new contributors are willing to exercise—when I'm triaging issues, I do not put up "good first issue" unless new contributors know _exactly_ which line to edit and what to change it to, without using any of their own discretion.

Ideally it would be reviewdog. But the changes are too non-local and result in proposed diff located in uncommentable areas. So, the workflow could output a whole dictionary file and ask them to copy&paste, or it could output a diff that we can apply (since ideally it would only be a few lines added each time anyway). What I don't want is two PRs every week, one called "fix typos" another called "fix dictionary file".

2024-09-24 02:08 UTC, OnkarRuikar commented
Agree. Fixing typos in code is not good first worthy. I'll remove the good first label.

It's [not possible to comment on unedited lines](https://github.com/orgs/community/discussions/4452#discussioncomment-10348839). I'll create a new check workflow that will run when the list files are edited.

2024-09-28 16:50 UTC, Josh-Cena requested changes

2024-09-28 16:50 UTC, Josh-Cena commented on scripts/sort_and_unique_file_lines.js
> +  return a < b ? -1 : a > b ? 1 : 0;
Use `Intl.Collator` with `sensitivity: "accent"`

2024-09-28 16:50 UTC, Josh-Cena commented on scripts/sort_and_unique_file_lines.js
> +  return new RegExp(`^${string1}$`, "gi").test(string2);
Since we are using `Intl.Collator` anyway, here we can simply test if `compare()` returns `0`. This also avoids the input containing syntax characters.

2024-09-29 03:01 UTC, OnkarRuikar commented on scripts/sort_and_unique_file_lines.js
> +  return new RegExp(`^${string1}$`, "gi").test(string2);
will track this with the above previsous comment.

2024-09-29 03:16 UTC, OnkarRuikar commented on scripts/sort_and_unique_file_lines.js
> +  return a < b ? -1 : a > b ? 1 : 0;
The collator sounds good but cSpell doesn't seem use collator for comparisons. So after formatting the files using collator, I am getting the following errors from cspell because now the code treets 'acosh' = '𝚊𝚌𝚘𝚜𝚑'.
```log
files/en-us/web/javascript/reference/global_objects/intl/displaynames/of/index.md:28:153 - Unknown word (nonterminal)
files/en-us/web/javascript/reference/global_objects/intl/displaynames/of/index.md:68:48 - Unknown word (canadien)
files/en-us/web/javascript/reference/global_objects/math/acosh/index.md:14:300 - Unknown word (𝚊𝚌𝚘𝚜𝚑)
files/en-us/web/javascript/reference/global_objects/math/asinh/index.md:14:204 - Unknown word (𝚊𝚜𝚒𝚗𝚑)
files/en-us/web/javascript/reference/global_objects/math/atanh/index.md:14:397 - Unknown word (𝚊𝚝𝚊𝚗𝚑)
files/en-us/web/javascript/reference/global_objects/math/cbrt/index.md:14:83 - Unknown word (𝚌𝚋𝚛𝚝)
files/en-us/web/javascript/reference/global_objects/math/expm1/index.md:14:83 - Unknown word (𝚎𝚡𝚙𝚖)
files/en-us/web/javascript/reference/global_objects/math/hypot/index.md:14:109 - Unknown word (𝚑𝚢𝚙𝚘𝚝)
files/en-us/web/javascript/reference/global_objects/math/log/index.md:14:182 - Unknown word (𝚕𝚘𝚐)
files/en-us/web/javascript/reference/global_objects/math/log10/index.md:14:182 - Unknown word (𝚕𝚘𝚐)
files/en-us/web/javascript/reference/global_objects/math/log1p/index.md:14:192 - Unknown word (𝚕𝚘𝚐)
files/en-us/web/javascript/reference/global_objects/math/log2/index.md:14:182 - Unknown word (𝚕𝚘𝚐)
files/en-us/web/javascript/reference/global_objects/math/sqrt/index.md:14:179 - Unknown word (𝚜𝚚𝚛𝚝)
```

The MathML pages [use non-ASCII characters(a-zA-Z)](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/acosh/index.md?plain=1#L14), that look like ASCII, in the formulas. I don't know the reason for using non ASCII abcd characters in the MathML code. Need to ask @fred-wang. Should we change those to make ASCII?

2024-09-29 03:22 UTC, Josh-Cena commented on scripts/sort_and_unique_file_lines.js
> +  return a < b ? -1 : a > b ? 1 : 0;
The MathML formulae often use the monospace Latin characters. Including JS pages I wrote, because I converted them using TeXZilla, so yes I'd be curious to hear what Frédéric says, including whether it's possible to make TeXZilla use inline CSS instead.

I'm surprised that `𝚌𝚋𝚛𝚝` and `cbrt` are considered equal though. Maybe we should keep using `toUpperCase` then—just change the regex to use `a.toUpperCase() === b.toUpperCase()`.

2024-09-29 03:34 UTC, OnkarRuikar commented on scripts/sort_and_unique_file_lines.js
> +  return a < b ? -1 : a > b ? 1 : 0;
Now I've used `toLowerCase` for all the comparisons.

2024-09-29 05:02 UTC, Josh-Cena approved these changes
👍

2024-09-29 05:02 UTC, merged

2024-09-30 05:44 UTC, OnkarRuikar commented
PR https://github.com/mdn/content/pull/36109 tested this PR check workflow. 
- I created the #36109 PR using the GitHub web interface.
- New words were added at the beginning of the ignore-list.txt.
- The workflow failed with the following error:
  > The file is not formatted properly. Run 'node scripts/sort_and_unique_file_lines.js .vscode/ignore-list.txt' to format the file.
  > Error: Process completed with exit code 1.
- Then I ran `git fetch origin patch-3:patch-3` on my PC to get the PR branch.
- Then ran the suggested command to format the list file: `node scripts/sort_and_unique_file_lines.js .vscode/ignore-list.txt`
- Then pushed the changes using `git push -u origin patch-3`.