Fix: Glossary for Cloud
mdn/content pull request #36026
Opened 2024-09-24 09:26 UTC by ragul1697

### Description
Fixes #35519 - Added Glossary item for `Cloud`

### Additional details
Since MDN focuses on the web, it might be beneficial to include content about hosting web applications. Additionally, adding information about cloud services and cloud service providers could be valuable.

2024-09-24 12:05 UTC, chrisdavidmills requested changes
Hi there @ragul1697, and thank you for your contribution to MDN! I've provided you with a few comments to consider, although I think this is largely going in the right direction.

2024-09-24 12:05 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +**Cloud** or **Cloud Computing** refers to the on-demand delivery of a wide range of computing services such as servers, storage, databases, networking, software, analytics, and intelligence via the
You could also consider mentioning data centers, and provide some examples of some of the services you mention above.

I'd remove "software" from your list. Most if not all of them are software, so it seems to be a bit too vague.

2024-09-24 12:05 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +**Cloud** or **Cloud Computing** refers to the on-demand delivery of a wide range of computing services such as servers, storage, databases, networking, software, analytics, and intelligence via the
Also, when you say "intelligence", what do you mean? AI? Again, I'd remove that, unless you want to instead provide examples of tools that use AI or LLMs.

2024-09-24 12:05 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +- [What is Cloud Computing?](https://cloud.google.com/learn/what-is-cloud-computing?hl=en) on Google Cloud
Also link to https://en.wikipedia.org/wiki/Cloud_computing?

2024-09-24 12:05 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +This model enables faster innovation, flexible scalability, and significant cost savings. Users can access and utilize these services through a _pay-as-you-go_ pricing model, ensuring they only pay f
Mention "Software as a service" here, and its relationship with cloud pay-as-you-go and subscription models?

2024-09-24 17:35 UTC, ragul1697 commented
Thanks for all the comments. I will make the changes soon and let you know.

2024-09-27 23:23 UTC, cwangsanata commented
I think another good addition would be to include different cloud deployment style (e.g. Private Cloud, Public Cloud, etc.) as mentioned in the [NIST Definition of Cloud Computing](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-145.pdf). Also including the document itself could be a good source for additional reading.

2024-10-04 09:03 UTC, ragul1697 commented
Hi @chrisdavidmills, I have made some changes for the Glossary item on Cloud Computing. Pease have a look at it. Thanks

2024-10-04 14:34 UTC, chrisdavidmills requested changes
@ragul1697 great work., thank you so much. This content is interesting and useful. I've provided a bunch of comments, but most of them are fairly minor grammar/consistency updates.

The only really major one is the last one; I really don't think you need the last section.

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +**Cloud** refers to servers that are accessed over the Internet, and the software and databases that run on those servers.
```suggestion
The **Cloud** refers to servers located worldwide that are accessed over the Internet, and the software and databases that run on those servers.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +Instead of storing data or running programs on a local computer or server, users rely on these remote resources. Cloud servers are located in data centers all over the world. By using {{glossary("Clo
```suggestion
Instead of storing data or running programs on a local computer or server, users can access cloud resources to perform tasks: this is known as {{glossary("Cloud computing")}}.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud/index.md
> +### Key features of the Cloud
```suggestion
### Key features of the cloud
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +title: Cloud Computing
```suggestion
title: Cloud computing
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +slug: Glossary/Cloud_Computing
```suggestion
slug: Glossary/Cloud_computing
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +**Cloud Computing** refers to the on-demand delivery of a wide range of computing services such as servers, storage, databases, networking, analytics, and intelligence via the Internet.
```suggestion
**Cloud computing** refers to the on-demand delivery of a wide range of computing services such as servers, storage, databases, networking, analytics, and intelligence via the Internet — also known as **cloud services**.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +This model enables faster innovation, flexible scalability, and significant cost savings. Users can access and utilize these services through a _pay-as-you-go_ pricing model, ensuring they only pay f
```suggestion
This model enables faster innovation, flexible scalability, and significant cost savings. Users can use cloud-based services through a _pay-as-you-go_ pricing model, ensuring they only pay for what they use, making them highly efficient and adaptable solutions for businesses and individuals alike.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +> The {{glossary("Cloud")}} in Cloud Computing refers to the server infrastructure on which cloud services are built and hosted.
```suggestion
> The {{glossary("Cloud")}} in Cloud computing refers to the server infrastructure on which cloud services are built and hosted.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +### Cloud Services
I'd suggest just deleting this section. I've added in the cloud services term to the opening paragraph in an earlier section, so this now seems repetitious. Also, the second sentence here isn't needed. That's pretty obvious to the target audience.

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +Cloud Service Providers are the companies which provides these cloud services. Most popular cloud service providers are Google (Google Cloud Platform), Amazon AWS (Amazon Web Services), and Microsoft
```suggestion
**Cloud service providers** are companies that provide cloud services, such as Google (Google Cloud Platform), Amazon AWS (Amazon Web Services), and Microsoft (Azure).
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +### Types of Cloud Computing
```suggestion
### Types of cloud computing
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +The three main types of cloud computing include Infrastructure as a Service(IaaS), Platform as a Service(PaaS), and Software as a Service(SaaS). Each type of cloud computing provides different levels
```suggestion
The three main types of cloud computing are Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS). Each type of cloud computing provides different levels of control, flexibility, and management.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +IaaS provides virtualized computing resources over the internet, including servers, storage, and networking, allowing users to rent and manage the infrastructure they need which gives the users highe
```suggestion
IaaS provides virtualized computing resources over the internet, including servers, storage, and networking, allowing users to manage their infrastructure. This gives users a high level of flexibility and control over the resources.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +**Examples:** Amazon Web Services (AWS EC2), Microsoft Azure Virtual Machines, Google Compute Engine (GCE)
```suggestion
- **Examples:** Amazon Web Services (AWS EC2), Microsoft Azure Virtual Machines, Google Compute Engine (GCE).
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +> **Use case:** A company needing to scale its server infrastructure rapidly without owning physical servers might use IaaS.
```suggestion
- **Use case:** A company needing to scale its server infrastructure rapidly without owning physical servers.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +
Delete the space in between. Copy this pattern for the other sections too.

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +Examples: Google App Engine, Microsoft Azure App Service, Heroku, AWS Elastic Beanstalk
```suggestion
- **Examples**: Google App Engine, Microsoft Azure App Service, Heroku, AWS Elastic Beanstalk.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +> **Use case:** A developer who wants to focus on writing code and application logic, without managing servers or operating systems, would use PaaS.
```suggestion
- **Use case:** A developer who wants to focus on writing code and application logic, without managing servers or operating systems.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +> **Use case:** A business using SaaS doesn't need to install or manage software locally. Instead, they access the software (like email, CRM, or collaboration tools) directly from a web browser.
```suggestion
- **Use case:** A business using SaaS doesn't need to install or manage software locally. Instead, they access the software (like email, CRM, or collaboration tools) directly from a web browser.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +Examples: Google Workspace, Microsoft 365, Slack, Github, ChatGPT
```suggestion
- **Examples**: Google Workspace, Microsoft 365, Slack, Github, ChatGPT.
```

2024-10-04 14:34 UTC, chrisdavidmills commented on files/en-us/glossary/cloud_computing/index.md
> +### Cloud Deployment MOdels
I would delete this whole section. I think the above section covering Iaas/PaaS/SaaS is useful, as it gives readers an idea of different types of Cloud service. But going into different cloud deployment models goes beyond providing a useful definition of cloud computing ad isn't needed in this article.

2024-10-05 14:13 UTC, ragul1697 commented on files/en-us/glossary/cloud_computing/index.md
> +### Cloud Deployment MOdels
Sure, I will remove it. Can we add the [NIST Definition of Cloud Computing](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-145.pdf) under see also section? I think that document is some kind of standard but the contents are explained in other references also.

2024-10-05 14:24 UTC, ragul1697 commented
Hi @chrisdavidmills, completed all the changes requested. Thank you✌️

2024-10-08 20:21 UTC, Josh-Cena commented on files/en-us/glossary/cloud/index.md
> +### Key features of the cloud
``` suggestion
Key features of the cloud include:
```

2024-10-08 20:24 UTC, Josh-Cena commented on files/en-us/glossary/cloud_computing/index.md
> +### Cloud Services
Try to remove as many of these headings as possible. Glossaries are short and don't need many subsections. Also pay attention that you must start from h2 and go down, not start from h3.

2024-10-14 13:10 UTC, ragul1697 commented on files/en-us/glossary/cloud_computing/index.md
> +### Cloud Services
Yes, I understand. Glossary should be small and I started this entry like that. But I had to add more content to it as requested by others. At the moment MDN doesn't have any resources related to Cloud and Cloud Computing. 

In future, it might be useful if MDN provides guides for Cloud topics related to Web dev as most of the current technologies are using Cloud servers for various purposes.

2024-10-15 16:15 UTC, Josh-Cena approved these changes
I've taken liberty to reorganize the "cloud computing" page so it is much terser and doesn't use headings, but all information is still there. This looks great and we just need approval from @chrisdavidmills

2024-10-16 06:18 UTC, chrisdavidmills approved these changes
OK, approving! 

Thanks to @Josh-Cena for helping to tidy this up a bit. I also made a small edit to tighten the text up a bit further (the second paragraph was a bit wordy, and used "cloud services" too often). I am really happy with this now.

Our biggest thanks here must go to @ragul1697 for sticking with us through all the change requests and producing a nice piece of content for MDN. Your contribution is much appreciated!

2024-10-16 06:19 UTC, merged

2024-10-16 06:50 UTC, ragul1697 commented
Thank you @chrisdavidmills.