docs(manifest): Improvements to `id` page
mdn/content pull request #36020
Opened 2024-09-23 20:05 UTC by dipikabh

### Description

This work is part of improving the web/manifest docs.

Apart from normalizing the page layout to include "Syntax" and "Values", this PR includes the following changes:

- Organizes the information into a "Description" section and covers all info from the spec
- Replaces the existing example with more realistic scenarios
- Adds the tables of examples from the spec as a separate example section

### Motivation

To ensure all sections have sufficient explanation, all caveats from spec are covered, and the pages follow a similar template

### Additional details

Spec link: https://w3c.github.io/manifest/#id-member

### Related issues and pull requests

Tracking issue: https://github.com/mdn/mdn/issues/560

2024-09-24 08:24 UTC, chrisdavidmills requested changes
@dipikabh more fabulous work! Just a few comments for you.

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +The `id` manifest member serves as a unique identifier for your web app. It allows browsers to distinguish between different applications, even if they are served from the same URL. This includes the
```suggestion
The `id` manifest member serves as a unique identifier for your web app. It allows browsers to distinguish between different applications, even if they are served from the same URL:
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +- When a browser comes across an app manifest with an `id` that does not correspond to an already installed application, it treats that manifest as a description of a distinct application, even if it
```suggestion
- When a browser comes across an app manifest with an `id` that does not correspond to an already installed application, it treats that manifest as a definition of a distinct application, even if it is served from the same URL as another application.
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +- Use a leading `/` to be explicit that the `id` is a root-relative URL path.
```suggestion
- Use a leading `/` to specify that the `id` is a root-relative URL path.
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +- Fragments in the `id` are always removed during processing.
```suggestion
- Fragments in the `id` are removed during processing.
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +In this case, even though both manifest files are served from the same URL, browsers will treat the new manifest as a description of a distinct application because the `id` is different. As a result,
```suggestion
In this case, even though both manifest files are served from the same URL, browsers will treat the new manifest as a definition of a distinct application because the `id` is different. As a result, users can have both versions installed simultaneously.
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +Assume that the manifest URL for your app is `https://example.com/app/manifest.json`, and the `start_url` is defined as `https://example.com/app/home`. The following table demonstrates how different
```suggestion
Assume that the manifest URL for your app is `https://example.com/my-app/manifest.json`, and the `start_url` is defined as `https://example.com/my-app/home`. The following table demonstrates how different `id` values in the manifest will be resolved:
```

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +Assume that the manifest URL for your app is `https://example.com/app/manifest.json`, and the `start_url` is defined as `https://example.com/app/home`. The following table demonstrates how different
Also, is the manifest URL relevant to any of these examples?

2024-09-24 08:24 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +| undefined                     | `https://example.com/my-app/`      | Assuming `start_url` is `https://example.com/my-app/#here` for this example; `id` defaults to `start_url` with fragment removed
This one comes off as a bit weird and jarring because in the previous paragraph, you already say `start_url` is something different. Maybe don't put this one in the table, and instead describe it in a separate paragraph below the table?

2024-09-25 22:46 UTC, dipikabh commented on files/en-us/web/manifest/id/index.md
> +The `id` manifest member is used to represent the identity of your web application.
Good catch, the same idea is getting repeated in the second sentence. I guess I picked that up from the spec, which talks about "id represents identity" and then "identity is used by user agents...".

I also noticed that I've used "represents" here, but on other pages I've been trying to stick with "...manifest member is used to specify..." to make clear it's something developers need to add.

So I'm thinking of going with this version (and dropping the second sentence):

> The `id` manifest member is used to specify a unique identifier for your web application.

2024-09-25 22:51 UTC, dipikabh commented on files/en-us/web/manifest/id/index.md
> +The `id` manifest member serves as a unique identifier for your web app. It allows browsers to distinguish between different applications, even if they are served from the same URL. This includes the
Simplified this even further to:
```suggestion
The `id` manifest member serves as a unique identifier for your web app. It allows browsers to distinguish between different applications:
```

2024-09-25 23:10 UTC, dipikabh commented on files/en-us/web/manifest/id/index.md
> +- When a browser comes across an app manifest with an `id` that does not correspond to an already installed application, it treats that manifest as a description of a distinct application, even if it
I'm inclined to us "description" in this context because that's what the spec uses.

I also think it might be more appropriate to use "description" because the manifest file provides information about the web app rather than strictly defining it.

2024-09-25 23:16 UTC, dipikabh commented on files/en-us/web/manifest/id/index.md
> +Assume that the manifest URL for your app is `https://example.com/app/manifest.json`, and the `start_url` is defined as `https://example.com/app/home`. The following table demonstrates how different
Nope, you're right, the manifest URL is not needed here. Thanks for catching the URL typo :)

2024-09-25 23:29 UTC, dipikabh commented on files/en-us/web/manifest/id/index.md
> +| undefined                     | `https://example.com/my-app/`      | Assuming `start_url` is `https://example.com/my-app/#here` for this example; `id` defaults to `start_url` with fragment removed
Removed it from the table. Added it to the "fragments are removed" point in the "Description":

> - Fragments in the `id` are removed during processing. For example, if `id` is set to `foo#bar`, it will be resolved as `foo`. Similarly, if `id` is undefined and the `start_url` is `https://example.com/app/#home`, `id` will resolve to `https://example.com/app/`.

2024-09-26 00:24 UTC, dipikabh commented
Thanks for reviewing, @chrisdavidmills - excellent observations and suggestions.
The updates are ready for another look.

I've also updated the "Syntax" in https://github.com/mdn/content/pull/36020/commits/0ab8dbcba4079bb105f2166c49aec2855a8d1ae2 to show a few uses cases.

2024-09-26 06:59 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +The `id` manifest member is used to represent the identity of your web application.
Perfect!

2024-09-26 07:00 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +The `id` manifest member serves as a unique identifier for your web app. It allows browsers to distinguish between different applications, even if they are served from the same URL. This includes the
Yup, this works well. The bullets handle the "from the same URL" part.

2024-09-26 07:04 UTC, chrisdavidmills commented on files/en-us/web/manifest/id/index.md
> +| undefined                     | `https://example.com/my-app/`      | Assuming `start_url` is `https://example.com/my-app/#here` for this example; `id` defaults to `start_url` with fragment removed
Great stuff!

2024-09-26 07:05 UTC, chrisdavidmills approved these changes
Awesome work, thanks @dipikabh. And I think the updated syntax section is really good. I'd say this ready to merge.

2024-09-26 07:05 UTC, merged