Add a11y alt attribute explainer to html img element
mdn/content pull request #36067
Opened 2024-09-26 17:06 UTC by JohannesBeranek

### Description

This adds some explanation on how to choose a good alt attribute for an image and what is meant by the *Don't* and *Do* examples already present.

### Motivation

The existing example can easily be interpreted as "write down what you see in the image", as there is not much context given as to why or how the alt text was chosen in the *Do* example. 

### Additional details

I don't have any experience on committing to MDN and I am not a native speaker, but I've got decades of experience fighting usability issues and educating people on how to choose when to use a non-empty `alt` attribute and what to write. While it's hard to improve on the already existing documentation in a short and concise way, and actually adding anything meaningful that does not go too deep into the topic (there are already references to pages about a11y in that section), I hope I can provide a good base which, with the help of some native speakers, can help improve MDN.

### Related issues and pull requests

See issue #36050

2024-09-26 17:08 UTC, JohannesBeranek commented on files/en-us/web/html/element/img/index.md
> +In terms of accessibility, if you prepend the phrase "Something I saw on my travels:" to the examples above, a screen reader could read the *Don't* example as "Something I saw on my travels: image",
I honestly don't know how to "correctly" reference the good/bad Do/Don't sections, so feel free to tell me or point me in the right direction

2024-09-30 09:34 UTC, chrisdavidmills requested changes
Hello @JohannesBeranek, and thank you so much for your contribution to MDN. I think your suggestions are reasonable, and the language was pretty good. I have got a couple of suggestions for you to consider. My text suggestion is mainly to break up the long run-on sentence you added, and add macros to create links to the element reference pages.

2024-09-30 09:34 UTC, chrisdavidmills commented on files/en-us/web/html/element/img/index.md
> +In terms of accessibility, if you prepend the phrase "Something I saw on my travels:" to the examples above, a screen reader could read the _Don't_ example as "Something I saw on my travels: image",
It took me a little while to figure out what you meant here. Are you referring to including a paragraph containing this text before the image? If so, I'd make that clearer, and perhaps also advise that if you want combine descriptive text with an image, make sure the descriptive text and alt text work well together.

A good example could perhaps be having the descriptive text say "On my travels I saw a crested penguin with red eyes, an orange beak, and pink feet — this is a Rockhopper penguin". This would work quite well with an alt text of "A Rockhopper Penguin on a beach."

2024-09-30 09:34 UTC, chrisdavidmills commented on files/en-us/web/html/element/img/index.md
> +For images used to trigger an action, like inside an `<a>` tag or a `<button>` tag, consider using the triggered action as `alt` attribute value (like `alt="next page"` instead of `alt="arrow right"`
```suggestion
For images used to trigger an action, for example when nested inside an {{htmlelement("a")}} or {{htmlelement("button")}} element, consider describing the triggered action inside the `alt` attribute value. For example, you could write `alt="next page"` instead of `alt="arrow right"`. You could also consider adding an optional further description to a `title` attribute; this may be read by screen readers if requested by the user.
```

2024-09-30 12:07 UTC, JohannesBeranek commented on files/en-us/web/html/element/img/index.md
> +In terms of accessibility, if you prepend the phrase "Something I saw on my travels:" to the examples above, a screen reader could read the _Don't_ example as "Something I saw on my travels: image",
It's a bit hard to word - the idea is that if you want a simple test to check if an alt text could be appropriate, you try to make a sentence with it. It doesn't really matter what the sentence says, but it has to be a sentence that actually has a connection to the alt text AND works WITHOUT the alt text (for a sighted person).

I unfortunately don't get your example ; it reads to me as if, depending on placement of the image, either a sighted person would have an image breaking up a sentence ("- this is [image]"), or a blind person wouldn't have ANY benefit from the alt text (it just repeats what's already there: "- this is a Rockhopper penguin. A Rockhopper Penguin on a beach.". Read that, without the image in front of you. I think that might make it easier to follow what I'm trying to say. In your example I would actually use an empty alt text - that is, if I understood your example correctly.

Also, I wanted to keep the example as short as possible, as this is primarily an intro to what the following links expand upon, making sure people at least get the most basic idea of why alt text content is important in terms of accessibility (and yes, a11y is way more than blind people, but it points them in the right direction).

How about:
```
A simple accessibility test is to read the alt attribute content together with any preceding sentence to see if it conveys the same meaning as the image.

Together with a preceding sentence "On my travels I saw a cute little animal:", the _Don't_ example could be read by a screen reader "On my travels I saw a cute little animal: image", and thus wouldn't make sense.
```

I would actually prefer to get the "Rockhopper" part out as well to be honest, because pretty much no sighted person would look at that image and know that this penguin is a "Rockhopper", so that's probably something more appropriate for the title attribute (so a sighted person would get that information as a tooltip as well when hovering the image).

2024-10-03 12:35 UTC, chrisdavidmills commented on files/en-us/web/html/element/img/index.md
> +In terms of accessibility, if you prepend the phrase "Something I saw on my travels:" to the examples above, a screen reader could read the _Don't_ example as "Something I saw on my travels: image",
Thanks for digging into this a bit. Yes, I understand what you mean now, and I like your suggestion. This makes it much clearer.

I also think you could do away with the "Rockhopper" word. It doesn't take anything away from what the examples is trying to show, and removes that uncertainty.

2024-10-04 09:46 UTC, JohannesBeranek commented
@chrisdavidmills is this better now?

Thanks for taking the time!

2024-10-14 09:34 UTC, chrisdavidmills requested changes
Hi @JohannesBeranek, and thank you for your continued work on this. I have a couple more text suggestions for you. If you are happy with these, then I think we can get it merged. Let me know what you think!

2024-10-15 14:18 UTC, JohannesBeranek commented
@chrisdavidmills happy with the suggestions, commited them!

2024-10-16 05:58 UTC, chrisdavidmills approved these changes
Awesome. Approving!

Thanks again @JohannesBeranek. Your contribution is much appreciated.

2024-10-16 05:58 UTC, merged