Match pattern fragment clarification
mdn/content pull request #36069
Opened 2024-09-27 04:25 UTC by rebloor

### Description

Clarifies how fragments are handled in response to [https://github.com/mdn/content/issues/14018](https://github.com/mdn/content/issues/14018)

### Related issues and pull requests

Fixes #14018

2024-11-15 18:04 UTC, rebloor commented
@Rob--W @dotproto reminder that I'm looking for a review on this one

2024-11-16 20:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Contains an unsupported match character.</td>
This is not a syntactically invalid match pattern, just one that never matches.

The other examples here are examples of match patterns that are rejected as a value for "match pattern" types, but this one is accepted.

On the other hand, the example below with a host name is also syntactically valid but listed as invalid. In Chrome it is valid but in Firefox it is ignored.

2024-11-16 20:26 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Contains an unsupported match character.</td>
```suggestion
      <td>Contains a reference fragment, which are never included in the URLs to match against.</td>
```

Can probably be phrased better than this. It is not that the character is unsupported technically, but that the URL that the pattern is matched against never includes the reference fragment.

2024-11-17 22:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Contains an unsupported match character.</td>
@Rob--W made some changes to address, let me know what you think

2024-11-20 04:24 UTC, dotproto requested changes

2024-11-20 04:24 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Invalid</td>
`file://*` is invalid when declared in `host_permissions` in Firefox but works in Chrome. Chrome auto-corrects it to `file:///*`. 

`file:///*` works in both Firefox and Chrome.

2024-11-20 04:24 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Invalid</td>
Ugh, we're in weird territory now. This pattern (`https://mozilla.org:80/`) doesn't work for two reasons: the aforementioned origin redirect and a mismatch between the declared port and port required by the scheme. HTTPS runs on port 443, HTTP runs on port 80. 

Nether Chrome or Firefox will log an install time error/warning if an extension requests `https://mozilla.org:80/`. This permission is "valid" (but meaningless). You can see this in action if you use `await chrome.permissions.getAll()` to check the extension's current permission; the response object will look something like this: `{ permissions: [], origins: ["https://mozilla.org:80/*"]}`.

If you modify the host permission to request a port that matches the scheme (e.g. `https://www.mozilla.org:443/` or `http://example.com:80/`), both Chrome and Firefox will grant the host permission and the extension will be able to access data for that host.

2024-11-20 21:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
FYI @Rob--W does this mean I misunderstood your comment? ("On the other hand, the example below with a host name is also syntactically valid but listed as invalid. In Chrome it is valid but in Firefox it is ignored.")

2024-11-20 22:04 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Invalid</td>
@dotproto so should we use another port, such as 8080. I assume from your comment that this was just a poorly chosen example given that 80 has a binding, or is.the statement "_host_ must not include a port number." Incorrect

2024-11-20 22:10 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Invalid</td>
Added note re-Chrome behavior

2024-11-22 16:30 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
@dotproto also commented on the port number example [here](https://github.com/mdn/content/pull/36069#discussion_r1849497036), pointing out that there was a mismatch between the protocol and port number. So, to clarify, the statement "host must not include a port number." is incorrect? Therefore, we should:

- add a port to the details of how the [host](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#host) can be specified with a note about the issues in Firefox
- add an example to the [examples](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#examples) with a note that the port number must match the protocol
- remove the port example from the invalid list

2024-11-26 01:14 UTC, dotproto approved these changes
Approving as there's only one small change left to land. 

---

While working on this review I realized that my feedback has been scoped to how match patterns are used for (optional) host permissions declarations in the extension manifest, but but that's just one of several ways that match patterns are used in extensions.

We should probably address the different ways that match patterns are used in a separate PR.

For tracking presupposes, I've collected a list of ways that match patterns are currently used. They way match patterns work may or may not be shared across these locations.

1. host permissions declared in the `host_permissions` and `optional_host_permissions` manifest fields.
    * same usage pattern should apply to the `origins` field of the object passed to [`permissions.request()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request)

2. the `matches` field of content script declarations
    * should also apply to the `matches` field in the object passed to [`scripting.registerContentScripts()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/registerContentScripts)
    * should also match the `matches` field in the object passed to [`userScripts.register()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts/register)

3. the `matches` as used in entries of the [`web_accessible_resources`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources#manifest_v3_syntax) manifest field (MV3 only).

4. In the `hide_matches` and `show_matches` fields of the [`page_action`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/page_action) manifest field.

5. the `url` field of the [`webRequest.RequestFilter`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter) object.

6. the `url` field of the filter object passed to [`tabs.onUpdated()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated).

7. the `url` field of the options argument passed to [`tabs.query()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query)

8. the `matches` field of the generic [`UrlFilter`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/events/UrlFilter) object.

This list is non-exhaustive. I should go through searchfox.org and cs.chromium.org to look for additional uses I may have missed.

2024-11-26 22:21 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
@dotproto @Rob--W Any feedback on my comments?

2024-11-28 10:23 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
> - add a port to the details of how the [host](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#host) can be specified with a note about the issues in Firefox

Looks like there is already a note "host must not include a port number.". This can be revised to limit to Firefox and include a link to the Firefox bug.

(I just checked [WebKit's source code](https://searchfox.org/wubkat/rev/795fdaece398b18bdefcd3954e0da2312ca92ee9/Source/WebKit/UIProcess/Extensions/WebExtensionMatchPattern.cpp#409) and confirmed that Safari supports ports too)

> - add an example to the [examples](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#examples) with a note that the port number must match the protocol

I don't know why you would suggest that. The default port for http is 80, for https 443. When a user or website navigates there, the port is automatically omitted because it is the default port. So if a match pattern were to look like `https://example.com:443/*`, then it would never match because extensions would never encounter such a URL in practice.

Your suggestion would basically be a "bad example" example. It is a syntactically valid match pattern, but known to never match anything.

> - remove the port example from the invalid list

Could move the example to the good section with a remark that it does not work in Firefox + bug number.

2024-11-28 21:39 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
@Rob--W 

>  * add an example to the [examples](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#examples) with a note that the port number must match the protocol
> 
> I don't know why you would suggest that. The default port for http is 80, for https 443. When a user or website navigates there, the port is automatically omitted because it is the default port. So if a match pattern were to look like `https://example.com:443/*`, then it would never match because extensions would never encounter such a URL in practice.

Because of @dotproto [comment](https://github.com/mdn/content/pull/36069#discussion_r1849497036):

> Ugh, we're in weird territory now. This pattern (https://mozilla.org:80/) doesn't work for two reasons: the aforementioned origin redirect and a mismatch between the declared port and port required by the scheme. HTTPS runs on port 443, HTTP runs on port 80.

> Neither Chrome or Firefox will log an install time error/warning if an extension requests https://mozilla.org:80/. This permission is "valid" (but meaningless). You can see this in action if you use await chrome.permissions.getAll() to check the extension's current permission; the response object will look something like this: { permissions: [], origins: ["https://mozilla.org:80/*"]}.

> If you modify the host permission to request a port that matches the scheme (e.g. https://www.mozilla.org:443/ or http://example.com:80/), both Chrome and Firefox will grant the host permission and the extension will be able to access data for that host.

So essentially, because the "bad" example is `https://mozilla.org:80/` so includes the wrong port for the protocol, but doesn't say that so. And I was suggesting adding a "good" example with the note.

2024-11-29 00:19 UTC, dotproto requested changes

2024-11-29 00:19 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td><code>*.</code> followed by part of the hostnamp plus a port number.</td>
The port is optional.

2024-11-29 00:55 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
Fragments in the URL are ignored - first sentence -  (therefore) a match pattern containing fragments fails to match any URL - second sentence.
```suggestion
Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. Therefore, a match pattern containing `#` will fail to match with any URL.
```

2024-11-29 00:59 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Contains a reference fragment: the URL that the pattern is matched against has any reference fragment removed before matching.</td>
As I understand it, that's not the point. The point is that if you have a URL of `https://www.mozilla.org/#section1`, as per the text in the previous comment, it has the fragment removed before matching. So the URL used to match against the match pattern is `https://www.mozilla.org/` (the match pattern is unchanged).

2024-11-29 01:00 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td><code>*.</code> followed by part of the hostnamp plus a port number.</td>
Hence, why this follows <td><code>*.</code> followed by part of the hostname.</td>

2024-12-02 17:27 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
Simeon's comment and mine are not contradicting.

The current example is `https://mozilla.org:80/`. The original explanation was `Host must not include a port number.`. Simeon states that while the example does not work in Chrome, it failed for a different reason than in Firefox. Firefox does simply not support ports, whereas in Chrome the match pattern is not going to match anything, in practice. HTTPS runs on port 443, HTTP runs on port 80. In theory a website could try serving HTTPS over port 80 or HTTP over port 443, but let's ignore that for now.

I can confirm that Chrome supports match patterns where the scheme is 443 (https) or 80 (http). They still do not work in Firefox because ports are not supported.

In any case, the message is not "Port number must match the protocol.", but "Ports are supported in Chrome, not in Firefox", and as an example you could use port number 8080 for example.

2024-12-03 02:02 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
Ping @dotproto

2024-12-03 02:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Is syntactically valid and matches in Chrome but is ignored in Firefox.</td>
Thanks @Rob--W. However, it doesn't make sense to include the port example in the invalid examples list so I've moved it to the valid examples list with the note about support.

2024-12-03 02:52 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> -> The path pattern string should not include a port number. Adding a port, as in: `http://localhost:1234/*` causes the match pattern to be ignored. However, `http://localhost:1234` will match with `h
@dotproto @Rob--W is this still relevant, given host can include ports? (Or should it be rephrased more along the lines of "if you include a port in the host pattern, you can't include a path.")

2024-12-04 00:24 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
Ah, I missed your last comment because I was only looking at my pull request queue. 

Looks like we may have different views on what "match" means in this context. I don't think it's accurate to say "a match pattern containing `#` will fail to match with any URL." 

As I see it, if an extension requests access to a given pattern, then any URL on which the extension receives additional access grants as a result is a match for that pattern. The actual string the developer typed or their intent when typing it don't affect whether or not a pattern is matched.

More concretely, if I declare `"http://example.com/sub/path/#my-fragment"` in `host_permissions` an extension, install it, and then visit `http://example.com/`, the extension will be able to access the URL of that tab. The extension will not match URLs with a fragment as I may have wanted, but the pattern I declared can still match URLs that I visit.

2024-12-04 22:57 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td><code>*.</code> followed by part of the hostnamp plus a port number.</td>
Ah! My mistake. I missed the context of content outside the diff view.

2024-12-05 01:58 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
@dotproto However, isn't your example incorrect in that "http://example.com/sub/path/#my-fragment" would only match with "http://example.com/sub/path/"? Presumably, the fragment is not considered part of the path in either the match pattern or the URL being matched. Hence:
```suggestion
Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered part of the _path_ and are ignored during pattern matching. Therefore, a match pattern containing `#` will fail to match with only the URL containing the fragment. For example, in the match pattern `"http://example.com/sub/path/#my-fragment"` the browser will look for a match on `"http://example.com/sub/path/"`. This matches with any URL containing that host and path and any fragment. So, it matches `"http://example.com/sub/path/#my-fragment"`,  `"http://example.com/sub/path/#another-fragment"`, etc.
```

2024-12-05 19:03 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
@rebloor @Rob--W, in order to make sure we're all on the same page, I put together an example extension that tests a bunch of host permissions match patterns and how various URLs do (not) match them. https://gist.github.com/dotproto/f199f3f0ed96b50761e4b537c72f26b8

As you can see in the tests for `"http://www.example.edu/test/*#fragment"`, Chrome and Firefox both ignore the entire path for host permissions checks. This does not apply to other types of match patterns, such as the `matches` field in a content script declaration.

2024-12-05 21:07 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` that precedes it are considered as part of the _path_ and are ignored during pattern matching. A m
I started looking at how Safari handles host permissions declarations and it's a whole different world. It's so different that it simply has to be out of scope for the time being.

2024-12-06 00:25 UTC, dotproto commented
I just re-requested review from myself. As I mentioned in this review, so far I've been primarily focused on how match patterns behave for `host_permissions` requests. For the moment, I think it would be best to keep this PR scoped to that use case in Chrome and Firefox. 

I've created an internal task for myself (`CD-93`) to build out a test suite that flexes all of the various match patterns uses across WebExtensions (and across browser implementations). I'm tentatively hoping to tackle this in Q1 2025. 

@rebloor and @Rob--W, does that sound like a reasonable approach?

2024-12-06 01:38 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +      <td>Contains an unsupported match character.</td>
The basic structure of this pattern does match when used in `host_permissions`. I tested this using a modified version of [this test extension](https://gist.github.com/dotproto/f199f3f0ed96b50761e4b537c72f26b8) and received the following output from Chrome and Firefox.

Firefox 133.0 buildID 20241121140525 
```text
manifest patterns (1): ["http://example.com/#fragment"]
granted  patterns (1): ["http://example.com/*"]
pattern  origins  (1): ["http://example.com"]
  Request URL                                        Observed URL (indicates pattern match)
Testing pattern "http://example.com/#fragment"
  http://example.com                                 tab.url = http://example.com/
  http://example.com#fragment                        tab.url = http://example.com/#fragment
  http://example.com/                                tab.url = http://example.com/
  http://example.com/#fragment                       tab.url = http://example.com/#fragment
  http://example.com/subpath                         tab.url = http://example.com/subpath
  http://example.com/subpath#fragment                tab.url = http://example.com/subpath#fragment
  http://example.com/sub/path/                       tab.url = http://example.com/sub/path/
  http://example.com/sub/path/#fragment              tab.url = http://example.com/sub/path/#fragment
```

Chrome Version 131.0.6778.86 (Official Build) (arm64)
```text
manifest patterns (1): ["http://example.com/#fragment"]
granted  patterns (1): ["http://example.com/*"]
pattern  origins  (1): ["http://example.com"]
  Request URL                                        Observed URL (indicates pattern match)
Testing pattern "http://example.com/#fragment"
  http://example.com                                 tab.url = http://example.com/
  http://example.com#fragment                        tab.url = http://example.com/#fragment
  http://example.com/                                tab.url = http://example.com/
  http://example.com/#fragment                       tab.url = http://example.com/#fragment
  http://example.com/subpath                         tab.url = http://example.com/subpath
  http://example.com/subpath#fragment                tab.url = http://example.com/subpath#fragment
  http://example.com/sub/path/                       tab.url = http://example.com/sub/path/
  http://example.com/sub/path/#fragment              tab.url = http://example.com/sub/path/#fragment
```

Safari Version 18.1 (20619.2.8.11.10)
```text
manifest patterns (1): ["http://example.com/#fragment"]
granted  patterns (1): ["*://*.example.com/*"]
pattern  origins  (1): ["http://example.com"]
  Request URL                                        Observed URL (indicates pattern match)
Testing pattern "http://example.com/#fragment"
  http://example.com                                 tab.url = http://example.com/
  http://example.com#fragment                        tab.url = http://example.com/#fragment
  http://example.com/                                tab.url = http://example.com/
  http://example.com/#fragment                       tab.url = http://example.com/#fragment
  http://example.com/subpath                         tab.url = http://example.com/subpath
  http://example.com/subpath#fragment                tab.url = http://example.com/subpath#fragment
  http://example.com/sub/path/                       tab.url = http://example.com/sub/path/
  http://example.com/sub/path/#fragment              tab.url = http://example.com/sub/path/#fragment
```

2024-12-09 01:48 UTC, rebloor commented
@dotproto so are you saying to put this on hold until you've done your testing in Q1 next year?

2024-12-09 06:15 UTC, dotproto commented
> @dotproto so are you saying to put this on hold until you've done your testing in Q1 next year?

No, I was suggesting that we solidify and merge this PR and follow up in a couple months with another set of changes

2024-12-10 02:03 UTC, rebloor commented
> No, I was suggesting that we solidify and merge this PR and follow up in a couple months with another set of changes

@dotproto OK, so it's now waiting on you to clear the change request/approve (I think everything's been addressed)

2024-12-22 17:01 UTC, rebloor commented
@dotproto a reminder that's waiting on your review and update of the change requested flag

2025-03-10 01:37 UTC, dotproto commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> -> The path pattern string should not include a port number. Adding a port, as in: `http://localhost:1234/*` causes the match pattern to be ignored. However, `http://localhost:1234` will match with `h
I think it's still relevant to say that fragments aren't considered when evaluating match patterns. IMO we should also recommend omitting them.

The note portion isn't accurate. There are some situations where an extension may explicitly want to connect to a specific port. For example, an application might expose a web server on `localhost` using a well-known port, or a web server may be publicly accessible on the Internet using a non-standard port. In both cases specify a port is necessary. 

If we were to retain the note, I'd suggest tweaking it to recommend against including the port number unless it is strictly necessary. For example, prefer `http://example.com/*` over `http://example.com:80/*`. Over-specifying the host in a match pattern may result in unexpected or inconsistent behavior. For example, `http://example.com:443/*` will not match when a user navigates to `http://example.com/` in Firefox, but it will in Chrome.

2025-03-20 02:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
```suggestion

Neither the [URL fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) nor the `#` which precedes it are considered as part of the _path_. This means that fragments aren't considered when evaluating match patterns.
```

2025-03-20 02:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> +> Firefox doesn't support the inclusion of a port number due to ([Firefox bug 1362809](https://bugzil.la/1362809)) and ([Firefox bug 1468162](https://bugzil.la/1468162)).
@dotproto re the comments about port numbers in https://github.com/mdn/content/pull/36069/files#r1986494273, doesn't this address that issue?

2025-03-20 02:48 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/match_patterns/index.md
> -> The path pattern string should not include a port number. Adding a port, as in: `http://localhost:1234/*` causes the match pattern to be ignored. However, `http://localhost:1234` will match with `h
> I think it's still relevant to say that fragments aren't considered when evaluating match patterns. IMO we should also recommend omitting them.

@dotproto is this addressed by the proposed change above?

2025-12-03 08:32 UTC, dotproto approved these changes
I've been blocking this too long. I think we have material improvements here. While there is more we can do, IMO we should address additional improvements in follow-on PRs rather than continuing to hold off on landing these changes.

2025-12-09 22:44 UTC, merged