Fix grammatical / phrasing error
mdn/content pull request #36130
Opened 2024-09-30 15:07 UTC by sensingturtle

### Description

The original phrasing doesn’t look or sound grammatically correct.

### Motivation

To keep the content on MDN high quality.

2024-09-30 15:26 UTC, Josh-Cena requested changes

2024-09-30 15:26 UTC, Josh-Cena commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
```suggestion
Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS, construct the CSSOM tree, and recursively calculate computed styles. In terms of web performance optimization, there are lower hanging fruits, as the total time to create the CSSOM is generally less than the time it takes for one DNS lookup.
```

The original one is only slightly wrong—it's saying that there are things that can be more easily fixed than CSS because CSS is pretty fast already.

2024-10-01 00:01 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
FYI, fruit is better than fruits in this fix. The first sentence is really bad - does this fix it? (i.e. is the time unique colour relevant?)

```suggestion
Building the CSSOM is very, very fast, and this build time is not displayed in the developer tools.
Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS, construct the CSSOM tree, and recursively calculate computed styles. In terms of web performance optimization, there are lower hanging fruit, as the total time to create the CSSOM is generally less than the time it takes for one DNS lookup.
```

2024-10-01 01:35 UTC, Josh-Cena commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
How is the plural of "fruit" not "fruits"? Or is "there are lower hanging fruit" a phrase by itself that I'm not aware of? 😅

2024-10-01 02:18 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
fruit is a collective noun taking a singular verb: Fruit is good for you; The tree bears fruit (not fruits).

Don't blame me, I'm just the messenger :-)

2024-10-01 02:24 UTC, Josh-Cena commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
But in "fruit is good" you would use "is" because "fruit" is singular here right? Subject and verb have to agree. "There are fruit" just doesn't feel right.

2024-10-01 05:19 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
I interpret "fruit is good" as meaning "All fruit is good" or "all types of fruit are good". Gosh, that's confusing. But it is always "fruit".

Sorry I can't give you a grammatical point to work with: I don't know the rules "as rules".

2024-10-01 05:20 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
I'm more worried about the first sentence above.

2024-10-01 05:45 UTC, Josh-Cena commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
I can live by "there is lower hanging fruit" where "fruit" is a collective noun, but "there are lower hanging fruit" is a subject-verb agreement error. And as I type this apparently Grammarly agrees:

<img width="448" alt="image" src="https://github.com/user-attachments/assets/a2c79152-7d97-44ac-88f3-135fddc3bcc9">

2024-10-01 08:00 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
Yeah, except that I can't.

2024-10-01 08:02 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
Or "many other quick wins"

2024-10-02 03:02 UTC, sensingturtle commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
@hamishwillee I like your suggestion “many other quick wins”. It will also help resolve the grammatical (subject-verb) discussion that you were having with @Josh-Cena

2024-10-02 03:11 UTC, Josh-Cena commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
I agree with "many other quick wins". It's not as illustrative as "there are lower hanging fruits", but at least it's something we can agree on.

2024-10-04 00:55 UTC, hamishwillee commented on files/en-us/web/performance/how_browsers_work/index.md
> +Building the CSSOM is very, very fast and is not displayed in a unique color in current developer tools. Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS,
OK, then this. Committing. Review then pushed back to you @Josh-Cena 
```suggestion
Building the CSSOM is very, very fast, and this build time information is not displayed in the developer tools.
Rather, the "Recalculate Style" in developer tools shows the total time it takes to parse CSS, construct the CSSOM tree, and recursively calculate computed styles. In terms of web performance, there are many better ways to invest optimization effort, as the total time to create the CSSOM is generally less than the time it takes for one DNS lookup.
```

2024-10-04 03:11 UTC, Josh-Cena approved these changes
:+1:

2024-10-04 03:11 UTC, merged

2024-10-04 03:55 UTC, hamishwillee commented
Thanks @Josh-Cena @sensingturtle