Fix - Missing Reference for -webkit-fill-available
mdn/content pull request #36190
Opened 2024-10-04 13:20 UTC by ragul1697

### Description

Fixes #35618 - Added CSS Reference entry for `-webkit-fill-available`

2024-10-04 14:50 UTC, chrisdavidmills requested changes
Hi @ragul1697! I had never heard of this before, so I found researching it interesting. Thanks for adding it.

I do have an issue with your content update — `-webkit-fill-available` is a value, not a property, so it doesn't fit in the list you have inserted it into.

Maybe you could add a "Values" section at the bottom of the page, add an entry below it for `-webkit-fill-available`, and explain that it is a proprietary value for sizing properties such as width and height, which causes a container to take up all the available space in that dimension. What do you think?

You could perhaps also explain that really this is a non-standard way of doing what Flexbox's `stretch` value achieves, and you should use that instead to fix such problems? Or am I misunderstanding this?

2024-10-04 14:51 UTC, Josh-Cena commented
It is not a property. I think you need to make a new section called "-webkit-prefixed property values" and explain which property it is for and what standard replacement exists. You should also not use cssxref because there's no page for it and there won't be one.

2024-10-06 13:41 UTC, ragul1697 commented
Hi @chrisdavidmills, I have made changes for the `-webkit-fill-available` CSS Value. Please have a look at it. Thanks😎

2024-10-06 16:23 UTC, Josh-Cena commented on files/en-us/web/css/webkit_extensions/index.md
> +  - `stretch` or `fill-available` are available as standard replacements.
```suggestion
  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available` are available as standard replacements.
```

2024-10-07 09:32 UTC, chrisdavidmills requested changes
This is nearly there now, nice work @ragul1697! I just had an edit suggestion and a question for you.

2024-10-07 09:32 UTC, chrisdavidmills commented on files/en-us/web/css/webkit_extensions/index.md
> +  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available
```suggestion
  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. The flexbox `stretch` value (see for example {{CSSxRef("align-items")}} and {{CSSxRef("justify-items")}}) provides a standard replacement.
```

2024-10-07 09:32 UTC, chrisdavidmills commented on files/en-us/web/css/webkit_extensions/index.md
> +  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available
I've edited it like this because I thought it would be good to link to some examples of where `stretch` is used, and also, I couldn't find any evidence of `fill-available` being specified anywhere, or supported without the `-webkit-` prefix (I did a few tests). Do you know where it is specified?

2024-10-07 12:37 UTC, ragul1697 commented on files/en-us/web/css/webkit_extensions/index.md
> +  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available
`fill-available` is available only in Safari browser. But `stretch` and `fill-available` are doing the same work so any examples for `stretch` can be used as reference for `fill-available`.

For Reference: https://caniuse.com/?search=fill-available

2024-10-07 13:14 UTC, chrisdavidmills commented on files/en-us/web/css/webkit_extensions/index.md
> +  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available
It's not a standard though, is it? It isn't defined in an official specification?

2024-10-07 13:32 UTC, ragul1697 commented on files/en-us/web/css/webkit_extensions/index.md
> +  - : Used with sizing properties like {{CSSxRef("width")}} and {{CSSxRef("height")}}, to allow elements to take up all the available space within their parent container. `stretch` or `fill-available
Yes, not a standard yet.

2024-10-08 08:52 UTC, ragul1697 commented
Hi @chrisdavidmills, I have added the suggested content. Thanks😎

2024-10-08 10:14 UTC, chrisdavidmills approved these changes
Perfect, thank you @ragul1697! Merging.

2024-10-08 10:14 UTC, merged