New pages: HTML<form>NoValidate
mdn/content pull request #36289
Opened 2024-10-09 21:29 UTC by estelle

part of #35544

2024-10-15 19:08 UTC, Josh-Cena requested changes

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/formnovalidate/index.md
> +page-type: web-api-instance-method
```suggestion
title: "HTMLButtonElement: formNoValidate property"
short-title: formNoValidate
slug: Web/API/HTMLButtonElement/formNoValidate
page-type: web-api-instance-property
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlformelement/novalidate/index.md
> +page-type: web-api-instance-method
```suggestion
title: "HTMLFormElement: noValidate property"
short-title: noValidate
slug: Web/API/HTMLFormElement/noValidate
page-type: web-api-instance-property
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlformelement/novalidate/index.md
> +If this attribute is not set or the value is set to `false`, the form is validated. This can be overridden by setting the {{domxref("HTMLInputElement.formnovalidate")}} and {{domxref("HTMLButtonEleme
```suggestion
If this attribute is not set or the value is set to `false`, the form is validated. This can be overridden by setting the {{domxref("HTMLInputElement.formNoValidate")}} or {{domxref("HTMLButtonElement.formNoValidate")}} property to `true`, either via JavaScript or the HTML `formnovalidate` attribute, for the control used to submit the form.
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/formnovalidate/index.md
> +page-type: web-api-instance-method
```suggestion
title: "HTMLInputElement: formNoValidate property"
short-title: formNoValidate
slug: Web/API/HTMLInputElement/formNoValidate
page-type: web-api-instance-property
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlinputelement/formnovalidate/index.md
> +The **`formNoValidate`** property of the {{domxref("HTMLInputElement")}} interface is boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML/
```suggestion
The **`formNoValidate`** property of the {{domxref("HTMLInputElement")}} interface is a boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML/Constraint_validation) when submitted via the {{htmlelement("input")}}. It reflects the `<input>` element's [`formnovalidate`](/en-US/docs/Web/HTML/Element/input#formnovalidate) attribute.
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlbuttonelement/formnovalidate/index.md
> +The **`formNoValidate`** property of the {{domxref("HTMLButtonElement")}} interface is boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML
```suggestion
The **`formNoValidate`** property of the {{domxref("HTMLButtonElement")}} interface is a boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML/Constraint_validation) when submitted via the {{htmlelement("button")}}. It reflects the `<button>` element's [`formnovalidate`](/en-US/docs/Web/HTML/Element/button#formnovalidate) attribute.
```

2024-10-15 19:08 UTC, Josh-Cena commented on files/en-us/web/api/htmlformelement/novalidate/index.md
> +The **`noValidate`** property of the {{domxref("HTMLFormElement")}} interface is boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML/Const
```suggestion
The **`noValidate`** property of the {{domxref("HTMLFormElement")}} interface is a boolean value indicating if the {{htmlelement("form")}} will bypass [constraint validation](/en-US/docs/Web/HTML/Constraint_validation) when submitted. It reflects the `<form>` element's [`novalidate`](/en-US/docs/Web/HTML/Element/form#novalidate) attribute; if the attribute present, the value is `true`.
```

2024-10-15 21:15 UTC, estelle commented
@Josh-Cena Thanks for the review and catching those!

2024-10-26 17:43 UTC, Josh-Cena approved these changes

2024-10-26 17:43 UTC, merged