doc: Added additional information about using URLs, base64 strings
mdn/content pull request #36364
Opened 2024-10-15 19:08 UTC by Ashish-CodeJourney

### Description
Updated the `<audio>` element documentation to include more detailed information about different source options and their implications.

### Motivation
These changes provide readers with a more comprehensive understanding of the `<audio>` element's capabilities and limitations, particularly regarding different source types like URLs, base64-encoded strings, and MediaStream objects.

### Additional details
- Added information about URL sources and their impact on server requests during seeking
- Included details about using base64-encoded strings as audio sources
- Mentioned limitations of MediaStream sources
- Provided a functional example of a base64-encoded audio file

### Related issues and pull requests
Fixes #36338

These changes aim to address gaps in the existing documentation and provide more practical, real-world examples for developers working with the `<audio>` element.

2024-10-15 19:10 UTC, Josh-Cena requested changes

2024-10-15 19:10 UTC, Josh-Cena commented on files/en-us/web/html/element/audio/index.md
> +   ```
Data URLs are still URLs. You should link to https://developer.mozilla.org/en-US/docs/Web/URI and say all resource URLs including HTTP and Data URLs are valid.

2024-10-15 19:10 UTC, Josh-Cena commented on files/en-us/web/html/element/audio/index.md
> +3. `MediaStream` objects: While supported, `MediaStream` sources have limitations. They are not seekable and only support a limited set of codecs. This is most commonly used for live audio streams or
You cannot do this in HTML. How do you attach the `MediaStream` to an `HTMLMediaElement`?

2024-10-15 19:19 UTC, Ashish-CodeJourney commented on files/en-us/web/html/element/audio/index.md
> +   ```
Yes makes sense, Incorporated

2024-10-15 19:25 UTC, Ashish-CodeJourney commented on files/en-us/web/html/element/audio/index.md
> +3. `MediaStream` objects: While supported, `MediaStream` sources have limitations. They are not seekable and only support a limited set of codecs. This is most commonly used for live audio streams or
Yes i get it, made some changes for `MediaStream`

2024-10-15 19:51 UTC, Josh-Cena commented
@Ashish-CodeJourney, next time, remember that AI-generated content is strictly forbidden. I think it's quite obvious that your writing is AI-assisted, in part because your link is referring to the old location of data URLs.

2024-10-15 19:55 UTC, Ashish-CodeJourney commented
> @Ashish-CodeJourney, next time, remember that AI-generated content is strictly forbidden. I think it's quite obvious that your writing is AI-assisted, in part because your link is referring to the old location of data URLs which no longer exists anywhere in content.

I should disable my copilot,
And about that link '"URI" I think it's still reflects the same

I will take care of this from next time

2024-10-15 19:57 UTC, Ashish-CodeJourney commented
> @Ashish-CodeJourney, next time, remember that AI-generated content is strictly forbidden. I think it's quite obvious that your writing is AI-assisted, in part because your link is referring to the old location of data URLs which no longer exists anywhere in content.

I only use AI tools for checking grammar, but will take care of this

2024-10-15 20:47 UTC, Josh-Cena commented
> I should disable my copilot,

That should be fine. I use Copilot too and I don't think it comes off very robotic. But yes just keep in mind that we want it to be your own voice.

2024-10-16 11:16 UTC, Ashish-CodeJourney commented
> > I should disable my copilot,
> 
> That should be fine. I use Copilot too and I don't think it comes off very robotic. But yes just keep in mind that we want it to be your own voice.

Yes obviously, even I don't like LLM-generated content
that sounds too `robotic` and not genuine.

I will try to be more specific and own words.

thanks for suggestions.

2024-10-26 17:31 UTC, Josh-Cena approved these changes
Sure, thanks

2024-10-26 17:31 UTC, merged