Issue #32981 || Corrected Spinbutton and Slider role "only read-write" content and did some changes on both so that both roles can be more consistent and similar.
mdn/content pull request #36488
Opened 2024-10-24 13:27 UTC by SASHWAT12

…e additional changes for both the roles to be more consistent and similar

### Description

### Motivation

### Additional details

### Related issues and pull requests

2024-10-24 14:27 UTC, scottaohara requested changes
good first pass in trying to fix up these two docs.

i've taken it a bit further though, and corrected some inaccuracies with the original PR proposal.

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completio
```suggestion
The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completion of a task, progressing in a single direction. For instance, a file upload's progress bar that conveys the data transfer up to 100%, when the file has fully uploaded.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +The [`meter`](/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role) role, similar to HTML's {{HTMLElement('meter')}} element, is a read-only gauge. It indicates the amount of something within a known
```suggestion
The [`meter`](/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role) role, similar to HTML's {{HTMLElement('meter')}} element, is a read-only range. It represents a scalar measurement within a known range, or a fractional value. For instance, a computer's battery indicator, the disk usage of a hard drive or a car's gas gauge.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +The `slider` role is a read-write range: it's value changes via user interaction. As such, it must be able to receive focus. In addition, keyboard interaction, mouse clicks, and touch interaction mus
it was already mentioned that the slider is a read-write input range, so it doesn't need to be repeated.  

```suggestion
A `slider` role's value changes via user interaction. As such, it must be able to receive focus. In addition, to adjust the value keyboard interaction, mouse clicks, and touch interaction must be supported.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +ARIA provides developers with six different range [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles), including progressbars, meters, scrollbars, range input, sliders and spinbu
again a range input is not an aria role.  a range input (html) is the same as a role=slider.

```suggestion
ARIA provides developers with five different [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles) that inherit from the range abstract role, including progressbars, meters, scrollbars, spinbuttons and sliders.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The [`meter`](/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role) role, similar to HTML's {{HTMLElement('meter')}} element, is a read-only gauge. It indicates the amount of something within a known
```suggestion
The [`meter`](/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role) role, similar to HTML's {{HTMLElement('meter')}} element, is a read-only range. It represents a scalar measurement within a known range, or a fractional value. For instance, a computer's battery indicator, the disk usage of a hard drive or a car's gas gauge.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completio
```suggestion
The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completion of a task, progressing in a single direction. For instance, a file upload's progress bar that conveys the data transfer up to 100%, when the file has fully uploaded.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The `slider` role, similar to HTML's `input` of type `range`, [`<input type="range">`](/en-US/docs/Web/HTML/Element/input/range), is a read-write input range. Sliders allow users to select a value be
```suggestion
The `slider` role, similar to HTML's `input` of type `range`, [`<input type="range">`](/en-US/docs/Web/HTML/Element/input/range), is a read-write input range. Sliders allow users to select a value between predefined minimum and maximum values. The user selects a value by moving a slider thumb along a horizontal or vertical slider to select a value.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +The `spinbutton` role is a read-write range: it's value changes via user interaction. As such, it must be able to receive focus. In addition, keyboard interaction, mouse clicks, and touch interaction
this seems like it was pulled from the slider doc and just replaced slider with spinbutton.  The deletion of saying it was the only one whose value changes via user interaction was a good fix, but might as well call out the similarities between slider and spinbutton here.

```suggestion
The `spinbutton` and `slider` roles' values change via user interaction. As such, these roles must be able to receive focus. In addition, to adjust the value keyboard interaction, mouse clicks, and touch interaction must be supported.
```

2024-10-24 14:27 UTC, scottaohara commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  > To change the spinbutton value, touch-based assistive technologies need to respond to user gestures for increasing and decreasing the value by synthesizing key events.
This warning seems like it was copied over from the slider doc. It's not really accurate/applicable to most spinbutton implementations, so i suggest removing it.

```suggestion
```

2024-10-24 18:28 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +ARIA provides developers with six different range [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles), including progressbars, meters, scrollbars, range input, spinbuttons and sl
Thank you for highlighting the inaccuracy. I have implemented the change.

2024-10-24 18:28 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completio
I have implemented the change.

2024-10-24 18:29 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/slider_role/index.md
> +The `slider` role is a read-write range: it's value changes via user interaction. As such, it must be able to receive focus. In addition, keyboard interaction, mouse clicks, and touch interaction mus
Thanks for highlighting, repetitive stuff is corrected.

2024-10-24 18:29 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +ARIA provides developers with six different range [widget roles](/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles), including progressbars, meters, scrollbars, range input, sliders and spinbu
Same changes are implemented

2024-10-24 18:29 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The [`meter`](/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role) role, similar to HTML's {{HTMLElement('meter')}} element, is a read-only gauge. It indicates the amount of something within a known
Suggested changes are implemented.

2024-10-24 18:29 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The [`progressbar`](/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role) role, similar to HTML's {{HTMLElement('progress')}} element, is a read-only range. It indicates the portion of completio
Requested changes are implemented

2024-10-24 18:29 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  The `slider` role, similar to HTML's `input` of type `range`, [`<input type="range">`](/en-US/docs/Web/HTML/Element/input/range), is a read-write input range. Sliders allow users to select a value be
Changes are made

2024-10-24 18:30 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
> +The `spinbutton` role is a read-write range: it's value changes via user interaction. As such, it must be able to receive focus. In addition, keyboard interaction, mouse clicks, and touch interaction
I'm glad you found the fix helpful. I understood your point about highlighting the similarities between the slider and spinbutton and the changes has been incorporated.

2024-10-24 18:30 UTC, SASHWAT12 commented on files/en-us/web/accessibility/aria/roles/spinbutton_role/index.md
>  > To change the spinbutton value, touch-based assistive technologies need to respond to user gestures for increasing and decreasing the value by synthesizing key events.
As suggested the less applicable warning is removed. Please let me know if any further improvements can be done.

2024-10-24 18:32 UTC, SASHWAT12 commented
Implemented requested changes from review, further making content more accurate and clearer.  Please let me know if any further improvements can be done.

2024-11-06 10:07 UTC, SASHWAT12 commented
> good first pass in trying to fix up these two docs.
> 
> i've taken it a bit further though, and corrected some inaccuracies with the original PR proposal.

2024-12-02 18:10 UTC, closed without merging