Add HTMLTableElement.createTBody() page
mdn/content pull request #365
Opened 2020-12-17 18:15 UTC by PolariTOON

This PR adds a page about the `HTMLTableElement.createTBody()` method, and a link to it in the `HTMLTableElement` page.

This also fixes the description of the `HTMLTableElement.createTFoot()`.

The compatibility table about the `HTMLTableElement.createTBody()` method was already available.

2020-12-17 20:04 UTC, sideshowbarker commented
This looks great and I’m planning to review it thoroughly (if somebody else doesn’t beat me to it) — but I have a general comment for now: For reasons explained in https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/316411, I think it’s time for us to start moving away from using static property and method syntax for instance properties and methods — at least not proliferating the practice any further by doing it in new content like this.

To be clear, what I mean specifically is, we would:

* not have this new article say *“The `HTMLTableElement.createTBody()` method…”*
* not title the article **HTMLTableElement.createTBody()**

…but instead:

* have the article say *“The `createTBody()` method of `HTMLTableElement` objects…”* (or something like that)
* have the title be **HTMLTableElement: createTBody() method**

See also https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641/17 for a summary from @chrisdavidmills about the titling.

2020-12-21 19:56 UTC, Rumyra commented
I'm happy with these changes - are we expecting to have a verdict about naming static method pages? Or would you say it's ok to go ahead and approve this and that conversation is still open? @sideshowbarker

2020-12-21 20:14 UTC, sideshowbarker requested changes
Let’s change to *The `createTBody()` method of `HTMLTableElement` objects*.

2020-12-21 20:14 UTC, sideshowbarker commented on files/en-us/web/api/htmltableelement/createtbody/index.html
> +<p>The <code><strong>HTMLTableElement.createTBody()</strong></code> method creates and returns a new {{HTMLElement("tbody")}} element associated with a given {{HtmlElement("table")}}.</p>
```suggestion
<p>The <code><strong>createTBody()</strong></code> method of {{domxref("HTMLTableElement")}} objects creates and returns a new {{HTMLElement("tbody")}} element associated with a given {{HtmlElement("table")}}.</p>
```

2020-12-21 20:18 UTC, sideshowbarker commented
> I'm happy with these changes - are we expecting to have a verdict about naming static method pages? Or would you say it's ok to go ahead and approve this and that conversation is still open? @sideshowbarker

I just now added a suggested revision here that switches the wording in this new page to *The `createTBody()` method of `HTMLTableElement` objects*. If @PolariTOON commits that suggestion, then I think this can be merged.

2020-12-21 20:58 UTC, PolariTOON commented
@sideshowbarker I committed the change you requested.

2020-12-21 21:18 UTC, sideshowbarker requested changes

2020-12-21 21:18 UTC, sideshowbarker commented on files/en-us/web/api/htmltableelement/createtbody/index.html
> +title: HTMLTableElement.createTBody()
```suggestion
title: 'HTMLTableElement: createTBody()'
```

2020-12-21 21:18 UTC, sideshowbarker commented on files/en-us/web/api/htmltableelement/createtbody/index.html
> +<pre class="syntaxbox"><em>HTMLTableSectionElement</em> = <em>table</em>.createTBody();</pre>
```suggestion
<pre class="syntaxbox"><var>table</var>.createTBody();</pre>
```

2020-12-21 21:18 UTC, sideshowbarker commented on files/en-us/web/api/htmltableelement/createtfoot/index.html
> +<p>The <code><strong>HTMLTableElement.createTFoot()</strong></code> method returns the {{HTMLElement("tfoot")}} element associated with a given {{HtmlElement("table")}}. If no footer exists in the ta
```suggestion
<p>The <code><strong>createTFoot()</strong></code> method of {{domxref("HTMLTableElement")}} objects returns the {{HTMLElement("tfoot")}} element associated with a given {{HtmlElement("table")}}. If no footer exists in the table, this method creates it, and then returns it.</p>
```

2020-12-21 21:18 UTC, sideshowbarker commented on files/en-us/web/api/htmltableelement/createthead/index.html
>  <p>The <code><strong>HTMLTableElement.createTHead()</strong></code> method returns the {{HTMLElement("thead")}} element associated with a given {{HtmlElement("table")}}. If no header exists in the ta
```suggestion
<p>The <code><strong>createTHead()</strong></code> method of {{domxref("HTMLTableElement")}} objects returns the {{HTMLElement("thead")}} element associated with a given {{HtmlElement("table")}}. If no header exists in the table, this method creates it, and then returns it.</p>
```

2020-12-21 21:18 UTC, sideshowbarker commented
> @sideshowbarker I committed the change you requested.

Thanks — I just now added a few more. I think once those are committed, we should be good to go on this.

2020-12-21 21:42 UTC, PolariTOON commented on files/en-us/web/api/htmltableelement/createtbody/index.html
> +title: HTMLTableElement.createTBody()
I changed the title of the three method pages modified in this PR

2020-12-21 21:43 UTC, PolariTOON commented on files/en-us/web/api/htmltableelement/createtbody/index.html
> +<pre class="syntaxbox"><em>HTMLTableSectionElement</em> = <em>table</em>.createTBody();</pre>
I made the change in three pages

2020-12-21 21:44 UTC, PolariTOON commented on files/en-us/web/api/htmltableelement/createtfoot/index.html
> +<p>The <code><strong>HTMLTableElement.createTFoot()</strong></code> method returns the {{HTMLElement("tfoot")}} element associated with a given {{HtmlElement("table")}}. If no footer exists in the ta
I applied the suggestion

2020-12-21 21:44 UTC, PolariTOON commented on files/en-us/web/api/htmltableelement/createthead/index.html
>  <p>The <code><strong>HTMLTableElement.createTHead()</strong></code> method returns the {{HTMLElement("thead")}} element associated with a given {{HtmlElement("table")}}. If no header exists in the ta
Same here

2020-12-21 21:48 UTC, sideshowbarker approved these changes

2020-12-21 22:04 UTC, sideshowbarker commented
> I'm happy with these changes - are we expecting to have a verdict about naming static method pages? Or would you say it's ok to go ahead and approve this and that conversation is still open? @sideshowbarker

With the review changes here now applied, I think this is OK to approve and merge. The larger general question is something we can take to another meta-issue, I guess

2020-12-21 22:04 UTC, merged

2020-12-22 01:19 UTC, sideshowbarker commented
@PolariTOON Thanks much, and welcome aboard 🎉