the default option of a select
mdn/content pull request #36658
Opened 2024-11-05 11:43 UTC by jolka-ef

Update information about the selected option.

Fixes #36573

2024-11-05 12:47 UTC, chrisdavidmills requested changes
Hi there @jolka-ef , and thank you for your contribution to MDN! What you added was fine, but I've offered a suggestion that I feel makes it a little clearer, plus I've also suggested an extra sentence that provides another bit of information that was missing. Let me know what you think!

2024-11-05 12:47 UTC, chrisdavidmills commented on files/en-us/web/html/element/select/index.md
> +Each `<option>` element should have a [`value`](/en-US/docs/Web/HTML/Element/option#value) attribute containing the data value to submit to the server when that option is selected. If no `value` attr
```suggestion
Each `<option>` element should have a [`value`](/en-US/docs/Web/HTML/Element/option#value) attribute containing the data value to submit to the server when that option is selected. If no `value` attribute is included, the value defaults to the text contained inside the element. You can include a [`selected`](/en-US/docs/Web/HTML/Element/option#selected) attribute on an `<option>` element to make it selected by default when the page first loads. If no `selected` attribute is specified, the first `<option>` element will be selected by default. If multiple `<option>` elements have `selected` attributes specified, the last one in the source order will be selected by default.
```

2024-11-05 16:54 UTC, jolka-ef commented
I think now it's much better and clearer than what I added. Thanks a lot!

2024-11-05 17:51 UTC, jolka-ef commented
@chrisdavidmills  Before I begin my actual comment, I would like to apologize in advance for my inadequate level of English proficiency. 
I am not a native speaker :)
I think the text is now much better and clearer, although I have some doubts about this part

_**If multiple `<option>` elements have `selected` attributes specified, the last one in the source order will be selected by default.**_

because if I understand the [specification](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element) correctly, that's not usage they encourage.
Specs states 

**_A select element whose multiple attribute is not specified must not have more than one descendant option element with its selected attribute set._**

2024-11-19 10:40 UTC, jolka-ef commented
Hi @chrisdavidmills !
I add only part of changes. Is it okay with you ?

2024-11-19 11:40 UTC, chrisdavidmills commented
> Hi @chrisdavidmills ! I add only part of changes. Is it okay with you ?

Hi @jolka-ef! Sorry I missed this earlier. Yes, I think this is fine—the change you've made fixes the actual issue you were tackling. Thanks so much!

2024-11-19 11:40 UTC, chrisdavidmills approved these changes
LGTM!

2024-11-19 11:40 UTC, merged