Remove guide mutation events
mdn/content pull request #3667
Opened 2021-03-30 06:28 UTC by hamishwillee

This removes [Guide/Events/Mutation_events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events) as part of fixing #2245.

In summary, the guide topic is almost identical to the webapi page [MutationEvent](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent). So this mostly just deletes the guide page, updates links to `MutationEvent`, and adds a redirect to `MutationEvent`

2021-03-30 07:15 UTC, chrisdavidmills requested changes
Just a couple of teensy commments (just one waaaaafer-thin mint...)

2021-03-30 07:15 UTC, chrisdavidmills commented on files/en-us/web/guide/events/index.html
> +MutationEvent</a>, but the use of these events has been deprecated in favor of the lighter <a href="/en-US/docs/Web/API/MutationObserver">Mutation Observer</a> approach.</p>
"WebAPIs MutationEvent" seems like a strange/awkward choice for link text. Wouldn't something like "MutationEvent reference page" be better?

2021-03-30 07:15 UTC, chrisdavidmills commented on files/en-us/web/api/mutationevent/index.html
> +<p>In addition, they should be avoided because they have <strong>performance issues</strong> and <strong>poor cross-browser support</strong> (as described in the following sections).</p>
I would replace "they" wth "mutation events" in this sentence. Your structural update is much better, but I don't think it is clear enough what "they" is referring to from the previous sentence.

2021-04-05 23:41 UTC, hamishwillee commented on files/en-us/web/guide/events/index.html
> +MutationEvent</a>, but the use of these events has been deprecated in favor of the lighter <a href="/en-US/docs/Web/API/MutationObserver">Mutation Observer</a> approach.</p>
Absolutely. FYI this page will eventually be deleted.

2021-04-05 23:58 UTC, hamishwillee commented on files/en-us/web/events/index.html
> +  <tr>
@chrisdavidmills Thanks for the review. I fixed up as per your suggestions. This change is new - as previously discussed, addition of mutation events to the event reference with the sole purpose of pointing out that we now use mutation observers for this now.

2021-04-06 00:01 UTC, hamishwillee commented
@chrisdavidmills PS Do you think it is "worth" adding BCD for MutationEvent?  Essentially this would show that the Mutation event is more than just deprecated - but actually removed in most places.

My leaning is "not worth it", but you might feel differently.

2021-04-06 08:58 UTC, chrisdavidmills approved these changes
I think this is looking good now; thanks @hamishwillee !

I'd agree that `MutationEvent` BCD is not really worth it.

2021-04-06 08:58 UTC, merged

2021-04-07 08:17 UTC, hamishwillee commented
@chrisdavidmills 

> I'd agree that MutationEvent BCD is not really worth it.

Except if we decide that BCD is the canonical source of deprecation info :-0