Add docs for <meta> media attribute
mdn/content pull request #36692
Opened 2024-11-08 09:23 UTC by sedlukha

### Description

Add missed docs for `<meta>` `media` attribute

2024-11-08 20:49 UTC, estelle requested changes
thank you for noting the missing content. I suggested a rewrite of the specification language to make it more useful to MDN Web Docs readers. Feel free to edit my suggested edits.

2024-11-08 20:49 UTC, estelle commented on files/en-us/web/html/element/meta/index.md
> +- `media`
let's move this to above `name`, as attribute lists are in alphabetical order on MDN.

2024-11-08 20:49 UTC, estelle commented on files/en-us/web/html/element/meta/index.md
> +  - : The `media` attribute says which media the metadata applies to. The value must be a valid [media query list](/en-US/docs/Glossary/Media_query). Unless the `name` is [theme-color](/en-US/docs/We
```suggestion
  - : The `media` attribute defines which media the theme color defined in the `content` attribute should be applied to. Its value is a [media query](/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries), which defaults to `all` if the attribute is missing. This attribute is only relevant when the element's [`name`](/en-US/docs/Web/HTML/Element/meta/name) attribute is set to [`theme-color`](/en-US/docs/Web/HTML/Element/meta/name/theme-color). Otherwise, it has no effect, and should not be included.
```
The language in the specification is generally geared toward browser developers. On MDN, we interpret the spec content to make it more digestible and understandable to devs. Language like "no effect on the processing model and must not be used by authors" is really useful in the spec, but not so much for our readers.

2024-11-10 17:29 UTC, sedlukha commented on files/en-us/web/html/element/meta/index.md
> +- `media`
done

2024-11-13 04:07 UTC, estelle approved these changes
Thanks! 🎉

2024-11-13 04:07 UTC, merged