chore(css): Move CSS examples - Shapes, transforms, transition, display
mdn/content pull request #36740
Opened 2024-11-11 16:01 UTC by bsmth

### Description

As part of an initiative to reduce repo maintenance & code duplication, this PR moves some external examples into content. This PR converts the following macros to live samples:

```
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/inset.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/inset-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/circle.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/circle-generated.html", '100%', 700)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/ellipse.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/ellipse-keywords.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/basic-shape/polygon.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/box/margin-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/box/border-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/box/padding-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/box/content-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/box/bottom-margin-box.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/circle.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/box.html", '100%', 810)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/image.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/threshold.html", '100%', 820)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/shape-margin.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/generated-content.html", '100%', 850)}}
{{EmbedGHLiveSample("css-examples/shapes/overview/clip-path.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/simple-example.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/margin.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/threshold.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/generated-content.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/gradient.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/shapes/image/radial-gradient.html", '100%', 800)}}
{{EmbedGHLiveSample("css-examples/modules/transforms.html", '100%', 900)}}
{{EmbedGHLiveSample("css-examples/transitions/js-transitions.html", '100%', 500)}}
{{EmbedGHLiveSample("css-examples/display/multi-keyword/span-flex.html", '100%', 440)}}
{{EmbedGHLiveSample("css-examples/display/multi-keyword/inline-flex.html", '100%', 440)}}
{{EmbedGHLiveSample("css-examples/display/multi-keyword/multi-keyword-flex.html", '100%', 640)}}
{{EmbedGHLiveSample("css-examples/display/multi-keyword/inline-block.html", '100%', 440)}}
```

### Motivation

Motivation is described in the project issue.

### Related issues and pull requests

- https://github.com/mdn/mdn/issues/597

## TODO

- [ ] Add star to shared assets repo

2024-11-19 14:10 UTC, chrisdavidmills requested changes
Hey @bsmth! I've looked through all of these. I can verify that they (at least mostly) display correctly by running them in MDN Playground. However, they are not displaying on the preview pages, which is a bit strange.

2024-11-19 14:57 UTC, bsmth commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +{{EmbedLiveSample("inset", "", "250px")}}
That is strange, I did notice the output box was empty occasionally on localhost, but had content on refresh, I wonder if it's a Playground problem with lazy loading / order of loading resources. Needs some investigation.

2024-11-19 16:16 UTC, bsmth commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +{{EmbedLiveSample("inset", "", "250px")}}
@chrisdavidmills this is a known issue due to changes in Playground envs, it should be resolved in the coming days.

2024-11-20 09:51 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/basic_shapes/index.md
> +{{EmbedLiveSample("inset", "", "250px")}}
OK. In that case, I'm happy with all the additions, except where commented.

2024-11-26 11:28 UTC, bsmth commented on files/en-us/web/css/css_shapes/shapes_from_images/index.md
> +  shape-image-threshold: 0.2;
Correct! This is wrong in the original, fixed in c22e6d2e333a4eccaf489e777626a21587d22d3f

2024-11-26 16:25 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/shapes_from_images/index.md
> +  shape-image-threshold: 0.2;
Cool, that looks fixed now in the code listing in the page.

Although...now the live example doesn't appear to render in the page, or in Playground... ;-§

2024-11-26 16:26 UTC, chrisdavidmills commented on files/en-us/web/css/css_shapes/shapes_from_images/index.md
> +  shape-outside: url(https://mdn.github.io/shared-assets/images/examples/star-shape.png);
Again, looks correct on the page code listing, but I can't see it rendered in the live example in the page, or in Playground.

2024-11-26 16:26 UTC, chrisdavidmills approved these changes
@bsmth looks fixed, so approving, although I can't see the examples rendered anywhere.

2024-11-27 13:59 UTC, bsmth commented
> @bsmth looks fixed, so approving, although I can't see the examples rendered anywhere.

Thanks a lot! The playground in preview builds is probably not going to be fixed until next week given Rari release prio, so we can ignore for now as Playground is working on prod (& localhost). I'll double check on the branch, but we should be good to go!

2024-11-27 14:18 UTC, merged