chore(css): Move CSS examples - Modules, filter functions, flow layout, grid layout
mdn/content pull request #36752
Opened 2024-11-12 12:09 UTC by bsmth

### Description

As part of an initiative to reduce repo maintenance & code duplication, this PR moves some external examples into content. This PR converts the following macros to live samples:

```
{{EmbedGHLiveSample("css-examples/modules/animation.html", '100%', 650)}}
{{EmbedGHLiveSample("css-examples/modules/backgrounds.html", '100%', 430)}}
{{EmbedGHLiveSample("css-examples/modules/basicUI.html", '100%', 320)}}
{{EmbedGHLiveSample("css-examples/box-alignment/overview/grid-align-items.html", '100%', 700)}}
{{EmbedGHLiveSample("css-examples/box-alignment/overview/flex-align-items.html", '100%', 700)}}
{{EmbedGHLiveSample("css-examples/box-alignment/overview/grid-gap.html", '100%', 700)}}
{{EmbedGHLiveSample("css-examples/modules/compositing.html", '100%', 460)}}
{{EmbedGHLiveSample("css-examples/layout/normal-flow.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/flow/formatting-contexts/float.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/flow/formatting-contexts/bfc-overflow.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/flow/formatting-contexts/bfc-flow-root.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/flow/formatting-contexts/inline.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/modules/generated_content.html", '100%',420)}}
{{EmbedGHLiveSample("css-examples/grid/docs/autoplacement.html", '100%', 1200)}}
{{EmbedGHLiveSample("css-examples/types/filterfunctions.html", '100%', '500')}}
{{EmbedGHLiveSample("css-examples/inline-formatting/inline.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/inline-formatting/break.html", '100%', 720)}}
{{EmbedGHLiveSample("css-examples/inline-formatting/mbp.html", '100%', 920)}}
{{EmbedGHLiveSample("css-examples/inline-formatting/align.html", '100%', 920)}}
{{EmbedGHLiveSample("css-examples/inline-formatting/text-align.html", '100%', 920)}}
{{EmbedGHLiveSample("css-examples/flow/formatting-contexts/float.html", '100%', 720)}}
```

### Motivation

Motivation is described in the project issue.

### Related issues and pull requests

- https://github.com/mdn/mdn/issues/597

2024-11-13 11:28 UTC, Rumyra requested changes

2024-11-13 11:28 UTC, Rumyra commented on files/en-us/web/css/css_generated_content/index.md
> +Click "Play" in the example above to see or edit the code for the animation in the MDN Playground.
I don't think this example animates:
```suggestion
Click "Play" in the example above to see or edit the code in the MDN Playground.
```

2024-11-13 11:28 UTC, Rumyra commented on files/en-us/web/css/inline_formatting_context/index.md
> +  special inspiration from the fact.
To make it consistent with the rest
```suggestion
  Before that night— <span>a memorable night, as it was to prove—
  hundreds of millions of people</span> had watched the rising smoke-wreaths
  of their fires without drawing any special inspiration from the fact.
```

2024-11-13 11:53 UTC, bsmth commented on files/en-us/web/css/css_generated_content/index.md
> +Click "Play" in the example above to see or edit the code for the animation in the MDN Playground.
nice, copy-paste err

2024-11-14 10:11 UTC, Rumyra approved these changes

2024-11-14 10:41 UTC, merged