New page: dateTime property
mdn/content pull request #36987
Opened 2024-11-26 23:06 UTC by estelle

Part of [missing baseline](https://github.com/openwebdocs/project/issues/214) project

* Add missing HTMLModElement.dateTime reference
* improve see also and intro of HTMLTimeElement.dateTime slightly.

2025-01-02 17:18 UTC, Josh-Cena commented on files/en-us/web/api/htmlmodelement/datetime/index.md
> +const  = document.createElement("ins");
```suggestion
const el2 = document.createElement("ins");
```

2025-01-06 17:14 UTC, wbamberg requested changes

2025-01-06 17:14 UTC, wbamberg commented on files/en-us/web/api/htmlmodelement/datetime/index.md
> +```
It's not really clear to me what this example is trying to do. Is it supposed to follow on from the previous example? In that case presumably `el1` should be `deletion`.

Perhaps making this whole thing into a live sample, where the user can show the value of both attributes, might help? You could have an example which starts out with something like:

```html
<p>This paragraph <span>can be</span> changed.</p>
```

...and have a button to change it:

```html
<p>This paragraph
  <del datetime=the-date>can be</del>
  <ins datetime=the-date>has been</ins> changed.</p>
```

...and have a button to show the values. And another button a reset so they can try again.

2025-01-06 17:14 UTC, wbamberg commented on files/en-us/web/api/htmlmodelement/datetime/index.md
> +el2.innerHTML = " was"
We shouldn't use `innerHTML` for setting text.

2025-01-06 17:14 UTC, wbamberg commented on files/en-us/web/api/htmlmodelement/datetime/index.md
> +```
Also if `el1` should be `deletion` maybe `el2` should be `insertion`? Or maybe `deletedText` and `insertedText`?

2025-01-10 07:25 UTC, estelle commented on files/en-us/web/api/htmlmodelement/datetime/index.md
> +```
i switched to your suggested variable names. thanks for the suggestions. I didn't go with a live example, but did add a lot of explanatory text.

2025-01-23 19:11 UTC, wbamberg approved these changes
👍 thank you!

2025-01-23 19:11 UTC, merged