Optional-only permissions
mdn/content pull request #36988
Opened 2024-11-26 23:24 UTC by rebloor

### Description

Adds details to describe the ability of the optional permissions key to contain optional-only permissions and to note that these can only be requested individually when using the permissions.request API.

### Related issues and pull requests

See [Bug 1919323](https://bugzilla.mozilla.org/show_bug.cgi?id=1919323) Add support for optional-only permissions

2024-12-03 19:11 UTC, dotproto approved these changes
LGTM

2024-12-03 21:36 UTC, Rob--W requested changes

2024-12-03 21:36 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/request/index.md
> +Requested permissions must be defined in the [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) manifest.json key. The `origins` property can inclu
```suggestion
Requested permissions must be defined in the [`optional_permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) manifest.json key. The `origins` property can include permissions matching a subset of the hosts matched by an optional permission. For example, if `optional_permissions` include `"*://mozilla.org/"`, then `permissions.origins` can include `"https://developer.mozilla.org/"`.
```

Fixed domain and formatting.

2024-12-03 21:36 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/request/index.md
> +Requests for optional-only permissions can't include any other optional permissions.
Where is the concept of "optional-only permissions" defined? Can you turn the text in a link to that section?

2024-12-03 21:36 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/optional_permissions/index.md
> +Optional permissions are either permissions available for use in the [`permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions) key or optional-only permissi
In the context of optional permissions, "optional-only" is nearly equivalent to regular "optional permissions". The only difference is that regular permissions can usually be requested at install time, but optional-only permissions cannot. And that extensions should only include one permission when requesting an optional-only permission (but avoid the impression that the requirement applies to all permissions).

To minimize confusion, I think that it would be better to keep the original framing, and add "(optional only)" behind specific API permissions in the list, with "optional-only" linking to a new section that explains what it is.

2024-12-10 03:00 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/permissions/request/index.md
> +Requests for optional-only permissions can't include any other optional permissions.
Link added

2024-12-10 03:00 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/manifest.json/optional_permissions/index.md
> +Optional permissions are either permissions available for use in the [`permissions`](/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions) key or optional-only permissi
New optional-only potion section added

2024-12-22 16:58 UTC, rebloor commented
@Rob--W I've made the updates requested, please review and let me know if there's anything else

2024-12-22 20:59 UTC, erosman commented
Just an idea....

The page lists:
- Permissions that can be requested as `optional_permissions`
- Permissions that are granted silently in `optional_permissions`

In future, it will possibly have:
- Permissions that can ONLY be requested as `optional_permissions`

It could be good to have:
- Permissions that are not (currently) available as `optional_permissions`


There are some that might become available e.g.
- [Make Contextual Identity extensions be an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1386673)
- [[meta] Allow more permissions to be used as an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1458585)
- [[DNR] Support declarativeNetRequest and declarativeNetRequestWithHostAccess as an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1827855)

2024-12-24 15:44 UTC, Rob--W approved these changes

2024-12-24 17:24 UTC, merged