New pages: htmlmediaelement API
mdn/content pull request #37006
Opened 2024-11-27 19:52 UTC by estelle

part of [Missing baseline pages](https://github.com/openwebdocs/project/issues/214) project

2024-12-05 22:33 UTC, arinthros commented
Thank you @estelle! I was looking to add `played` because I needed it this week and discovered it was missing, and here is an MR already opened for it.

2024-12-05 22:37 UTC, arinthros commented
Should these also be added as entries into the main HTMLMediaElement page? https://github.com/mdn/content/blob/2682b7e331038a76a8476c1ff899659215097747/files/en-us/web/api/htmlmediaelement/index.md?plain=1#L29 

I'm new to this repo, so maybe they're scooped up in a build job, but it looks like the properties are also enumerated in the parent element page by hand.

2024-12-05 23:28 UTC, estelle commented
> Should these also be added as entries into the main HTMLMediaElement page?
> 
> https://github.com/mdn/content/blob/2682b7e331038a76a8476c1ff899659215097747/files/en-us/web/api/htmlmediaelement/index.md?plain=1#L29
> 
> I'm new to this repo, so maybe they're scooped up in a build job, but it looks like the properties are also enumerated in the parent element page by hand.

I am not sure if this was your question, but the two properties are already on the landing page. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#htmlmediaelement.played.

2025-01-06 17:59 UTC, wbamberg requested changes

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +The readonly **`played`** property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the media, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file, has played
We use "read-only" and AFAIK the usual wording here is "The $NAME read-only property of the $INTERFACE interface".

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +The readonly **`played`** property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the media, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file, has played
> the media, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file

"the media" here is ungrammatical IMO. Could be "the source" or "the resource". Also, "audio or audio file"?

I would have a para break before "It returns".

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +A {{domxref("TimeRanges")}} object, which includes the number of ranges as a `length`, with the `start` and `end` time for each range.
I don't think code-formatting `start` and `end` is appropriate since they're not actually properties. TBH I think you could just say "A  {{domxref("TimeRanges")}} object representing the time ranges that have been played." and leave the specifics to the linked page, which someone is is going to have to read anyway if they are to use this property.

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +```
would be great to see this as a live sample.

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +- {{domxref("HTMLMediaElement")}}
I don't think we should link to the parent here.

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/seeking/index.md
> +The readonly **`seeking`** property of the {{domxref("HTMLMediaElement")}} interface is a boolean indicating whether the media, the {{htmlelement("audio")}} or {{htmlelement("audio")}}, is in the pro
Mostly the same comments for this paragraph.

2025-01-06 17:59 UTC, wbamberg commented on files/en-us/web/api/htmlmediaelement/seeking/index.md
> +- {{domxref("HTMLMediaElement")}}
Same comment.

2025-01-06 18:51 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +The readonly **`played`** property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the media, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file, has played
```suggestion
The **`played`** read-only property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the resource, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file, has played. It returns a new {{domxref("TimeRanges")}} object that contains the ranges of the media source that the browser has played, if any, at the time the attribute is evaluated.
```

2025-01-06 18:52 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +- {{domxref("HTMLMediaElement")}}
```suggestion
- {{domxref("HTMLMediaElement.buffered")}}
```

2025-01-06 18:52 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/seeking/index.md
> +- {{domxref("HTMLMediaElement")}}
```suggestion
```

2025-01-06 18:53 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/seeking/index.md
> +The readonly **`seeking`** property of the {{domxref("HTMLMediaElement")}} interface is a boolean indicating whether the media, the {{htmlelement("audio")}} or {{htmlelement("audio")}}, is in the pro
```suggestion
The **`seeking`** read-only property of the {{domxref("HTMLMediaElement")}} interface is a Boolean indicating whether the media, the {{htmlelement("audio")}} or {{htmlelement("audio")}}, is in the process of seeking to a new position.
```

2025-01-06 18:54 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +A {{domxref("TimeRanges")}} object, which includes the number of ranges as a `length`, with the `start` and `end` time for each range.
```suggestion
A {{domxref("TimeRanges")}} object; representing the time ranges that have been played.
```

2025-01-06 19:06 UTC, wbamberg commented
It still says `<audio>` or `<audio>`.

2025-01-06 21:48 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/played/index.md
> +The **`played`** read-only property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the resource, an {{htmlelement("audio")}} or {{htmlelement("audio")}} media file, has pl
```suggestion
The **`played`** read-only property of the {{domxref("HTMLMediaElement")}} interface indicates the time ranges the resource, an {{htmlelement("audio")}} or {{htmlelement("video")}} media file, has played. It returns a new {{domxref("TimeRanges")}} object that contains the ranges of the media source that the browser has played, if any, at the time the attribute is evaluated.
```

2025-01-06 21:49 UTC, estelle commented on files/en-us/web/api/htmlmediaelement/seeking/index.md
> +The **`seeking`** read-only property of the {{domxref("HTMLMediaElement")}} interface is a Boolean indicating whether the resource, the {{htmlelement("audio")}} or {{htmlelement("audio")}}, is in the
```suggestion
The **`seeking`** read-only property of the {{domxref("HTMLMediaElement")}} interface is a Boolean indicating whether the resource, the {{htmlelement("audio")}} or {{htmlelement("video")}}, is in the process of seeking to a new position.
```

2025-01-06 21:50 UTC, estelle commented
> It still says `<audio>` or `<audio>`.

fixed. I was going to ask "How did I not see that?" but I know exactly why ...

2025-01-07 18:41 UTC, wbamberg approved these changes
👍 thank you Estelle!

2025-01-07 18:41 UTC, merged