add: SVG Angle MDN Feature Pages
mdn/content pull request #37013
Opened 2024-11-28 09:41 UTC by yashrajbharti

### Description

This PR adds the MDN feature pages for the SVGAngle interface as part of a recent project to document missing Widely available pages for interface features. 

### Motivation

I believe that my support in documenting the SVGAngle interface can significantly help developers by providing essential resources.

### Additional details

For more context, see the discussion on missing documentation tracked at https://openwebdocs.github.io/web-docs-backlog/baseline/. Additionally, related projects for adding widely available web features can be found at https://github.com/openwebdocs/project/issues/214. 

### Related issues and pull requests

Relates to [#214](https://github.com/openwebdocs/project/issues/214)

2024-12-04 00:49 UTC, wbamberg requested changes
Thanks for your PR!

Please review the templates we use for reference pages: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#api_reference_subpage and be sure to follow them. If you have any questions about specific aspects of the templates, please feel free to ask.

2024-12-05 06:13 UTC, yashrajbharti commented
Thanks for the resources, I will be correcting my way of writing the docs using this! and will fix the mistakes on this (and some other PRs soon)! I intend to write for clarity and completeness and this helps!

2024-12-05 08:08 UTC, yashrajbharti commented
@wbamberg Thanks for referring me to the Page Templates. I believe most of the format is now correct. I do have a question: If the value of any property (e.g., `valueInSpecifiedUnits`) throws a `DOMException`, where is that generally documented?

2024-12-05 18:48 UTC, wbamberg commented
> @wbamberg Thanks for referring me to the Page Templates. I believe most of the format is now correct. I do have a question: If the value of any property (e.g., `valueInSpecifiedUnits`) throws a `DOMException`, where is that generally documented?

That's a good question! I think the answer in general is: we don't document exceptions like this. For example, in the case you gave,  setting `valueInSpecifiedUnits` throws if the object is read only, but that's going to be true of any property, so it's not helpful to mention it.

2024-12-05 19:54 UTC, wbamberg requested changes
Thanks for the updates. I've left comments on just one of the pages, as I expect similar comments are going to apply to the others.

Apart from things like formatting conventions, the tricky part is thinking about: what do we want to tell readers about these APIs? What do they need to know about them? Just paraphrasing the spec is usually not helpful, because then they might as well go and read the spec.

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +A reference to the updated {{domxref("SVGAngle")}} object.
It seems to return undefined.

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +  - : Thrown if the `unitType` is not a valid value or is `SVG_ANGLETYPE_UNKNOWN`.
I think we wouldn't document this exception. It's true of any method that you must pass it valid params. Also

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +Converting an angle to degrees
This is not a sentence. You could make it a heading and then have a short prose description of what the example is doing.

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +console.log(angle.unitType); // Output: 2 (SVG_ANGLETYPE_DEG)
Because this example doesn't show the state of the object before calling `convertToSpecifiedUnits`, it doesn't show the effect of calling it. Also, `value` is always degrees, so AFAICT is unaffected by this method.

For instance, you could do:

```suggestion
// Create an SVGAngle object
const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
const angle = svg.createSVGAngle();

// Set the angle's value in radians (Math.PI / 2)
angle.newValueSpecifiedUnits(SVGAngle.SVG_ANGLETYPE_RAD, Math.PI / 2);

// Retrieve the angle's value as a string
console.log(angle.valueAsString); // Output: 1.5708rad
console.log(angle.unitType); // Output: 3 (SVG_ANGLETYPE_RAD)

// Convert the angle's value to degrees
angle.convertToSpecifiedUnits(SVGAngle.SVG_ANGLETYPE_DEG);

// Retrieve the angle's value as a string
console.log(angle.valueAsString); // Output: 90deg
console.log(angle.unitType); // Output: 2 (SVG_ANGLETYPE_DEG)
```

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +Attempting to convert to an unsupported unit type
I don't think this example is needed.

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +- {{domxref("SVGAngle.newValueSpecifiedUnits")}}
I don't think there's a lot of point in linking to other members of the same interface. They're all in the sidebar already. This section is for related pages which are not already accessible from the page.

2024-12-05 19:54 UTC, wbamberg commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +When the `convertToSpecifiedUnits()` method is successfully called, the `SVGAngle` object's `valueInSpecifiedUnits` is converted to match the specified `unitType`, and its value is updated accordingl
This doesn't belong in "return value", it's a general description of the method's behavior. So it should go at the start, before `## Syntax`.

Also, this reads like it's copied from the spec. What do we want developers to understand about what this method does?

I'm not at all familiar with this API, but for example, it seems like we could say something like:

```suggestion
This function will:
- set the {{domxref("SVGAngle.unitType", "unitType")}} property to the given unit type
- update the {{domxref("SVGAngle.valueInSpecifiedUnits", "valueInSpecifiedUnits")}} and {{domxref("SVGAngle.valueAsString", "valueAsString")}} properties so the angle value is represented in the given unit type
```

Is that correct?

2024-12-06 06:58 UTC, yashrajbharti commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +- {{domxref("SVGAngle.newValueSpecifiedUnits")}}
fixed!!

2024-12-06 06:59 UTC, yashrajbharti commented on files/en-us/web/api/svgangle/converttospecifiedunits/index.md
> +When the `convertToSpecifiedUnits()` method is successfully called, the `SVGAngle` object's `valueInSpecifiedUnits` is converted to match the specified `unitType`, and its value is updated accordingl
yes, I have added it before syntax, along with other fixes

2024-12-17 01:03 UTC, wbamberg requested changes
Thanks for the updates!

I started reviewing this but stopped when I got to https://github.com/mdn/content/pull/37013/files#diff-9122079f4f6ce53752a712afdd280a97e8be60040e0739ccb94c1f96bb2a492e, because it seems like it doesn't followed the template either.

Please, check that _all_ the pages follow the template, and that any other comments that seem to be applicable to other pages (for example, the way the unit types are described and formatted) are followed. Otherwise I have to make the exact same comment again and again, and it isn't very efficient.

2024-12-17 21:34 UTC, yashrajbharti commented
@wbamberg  In the [UnitType Page](https://github.com/mdn/content/pull/37013/files#diff-44ab84b819cec1c791e61ee6217de36a39e7d3bb77f35972514ffd74af3a37b3), I was unsure if we will saw the unique constants that each of the `SVGAngle.SVG_ANGLETYPE` corresponds to. (For example SVGAngle.SVG_ANGLETYPE_DEG = 2)

2025-01-06 18:57 UTC, wbamberg commented
> @wbamberg In the [UnitType Page](https://github.com/mdn/content/pull/37013/files#diff-44ab84b819cec1c791e61ee6217de36a39e7d3bb77f35972514ffd74af3a37b3), I was unsure if we will document the unique constants that each of the `SVGAngle.SVG_ANGLETYPE` corresponds to. (For example SVGAngle.SVG_ANGLETYPE_DEG = 2)

I think actually since we have https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle#constants, then we should not document the constant values in these pages at all, and just link to https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle#constants. I'm not sure whether we should document the numeric values (but if we do, it should be in https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle#constants).

2025-01-06 19:06 UTC, yashrajbharti commented
@wbamberg  Thanks for your answer, when I was documenting, I saw constants documented in the parent's interface in almost all cases. Such as [SVGTransform | Constants](https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform#constants), [SVGTextContentElement | Constants](https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement#constants), [SVGFEColorMatrixElement | Constants](https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement#constants) the list goes on.

However it also seems these are following an older format as data is represented in tables.

With that said, only SVGAngle seems to miss out on constants being documented.

2025-01-06 19:20 UTC, wbamberg requested changes

2025-01-07 09:25 UTC, yashrajbharti commented
Made the fixes in value, and  removed the part where we assumed angle as instance when we createSVGAngle as it will always be the case, so the word assume isn't required.

2025-01-07 17:40 UTC, wbamberg approved these changes
👍 looks great, thank you @yashrajbharti !

2025-01-07 17:40 UTC, merged