Correct the element name
mdn/content pull request #37025
Opened 2024-11-29 08:25 UTC by Snoopy1866

### Description

Accroding to the html source code example, the outer element is `<article>` not `<div>`.

### Motivation

### Additional details

### Related issues and pull requests

2024-12-01 09:14 UTC, chrisdavidmills requested changes
Thanks for your contribution to MDN, @Snoopy1866! Your changes are correct, but I've just made one small suggestion that fixes an incorrect `class` name and makes a small language suggestion.

Accept it if you agree.

Thanks again!

2024-12-01 09:14 UTC, chrisdavidmills commented on files/en-us/web/css/@scope/index.md
> +- The second `@scope` block also defines its scope root as elements with a class of `.feature`, but in addition defines a scope limit of `figure`. This ensures that contained rulesets will only be ap
```suggestion
- The second `@scope` block also defines its scope root as elements with a class of `.feature`, but also defines a scope limit of `figure`. This ensures that contained rulesets will only be applied to matching elements within the scope root (`<article class="feature"> ... </article>` in this case) that **are not** nested inside descendant `<figure>` elements. This `@scope` block contains a single ruleset that styles `<img>` elements with a thick black border and a golden background color.
```

2024-12-01 10:49 UTC, Snoopy1866 commented
Agree!

2024-12-03 09:40 UTC, chrisdavidmills approved these changes
Perfect, let's get this merged. Thanks again for your contribution @Snoopy1866, and wishing you all the best.

2024-12-03 09:40 UTC, merged