Add docs for improved error reporting for IndexedDB large value read failures
mdn/content pull request #37041
Opened 2024-12-01 16:20 UTC by chrisdavidmills

### Description

Chrome has updated its error reporting for IndexedDB large value read failures with transient causes such as low memory and unrecoverable causes such as source blob files being deleted.

Chrome 130 updates the `DOMException` types to be more appropriate, and Chrome 132 further updates them and improves the associated error messages. The data source is https://chromestatus.com/feature/5140210640486400.

In this PR, I have organized the different `IDBRequest.error` types into categories to hopefully make them easier to parse, and described and explained the large value read failure errors.

### Motivation

### Additional details

### Related issues and pull requests

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +A {{domxref("DOMException")}} or `null` if there is no error. The following error names can be returned
The phrasing "error names can be returned in the exception object" read a bit weird to me. How about "The exception object will have one of the following names, depending on what caused the error." ?

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you abort the transaction, then all requests still in progress receive this error.
The asynchronous errors like this are not "thrown" in the sense that you can't try/catch them from script. So I would avoid that phrasing here and below.

From a script perspective, an error event is fired at the IDBRequest; if the developer has assigned an event handler, then the handler can inspect the request's `error` property and specifically `error.name` to see what the cause was.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown in the `keyPath` argument contains an invalid key path.
Typo: "in" should be "if".

But more importantly, `SyntaxError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `TransactionInactiveError`
`TransactionInactiveError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `ReadOnlyError`
`ReadOnlyError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `DataError`
This description for `DataError` ("data provided to an operation does not meet requirements") applies only when it is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `DataCloneError`
`DataCloneError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `InvalidAccessError`
`InvalidAccessError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `InvalidStateError`
`InvalidStateError` is thrown synchronously when certain methods are called. It would never appear as a request's error. So this is not useful for this page.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you run out of disk quota and the user declined to grant the application more space.
Some browsers prompt the user; others use heuristics. So this could be softened a bit.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you try to open a database with a version lower than the one it already has.
Per above, not "thrown" but returned via the request's error property.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
>  In addition to the error codes sent to the {{ domxref("IDBRequest") }} object,
Not new, but this doesn't make much sense in this context.

"In addition to the error codes sent to the IDBRequest object..." - so far so good, that's what this page is about

"... asynchronous operations can also ..." - that doesn't make sense. This whole page is about how asynchronous operations that occur when the request is being executed, so this is like saying "In addition to A, there's also A". 

Finally "...raise exceptions." - as noted, async operations can't raise exceptions, they fire error events.

2024-12-02 19:15 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +Large IndexedDB values are not stored directly in the underlying database; instead, they are stored as separate files that are accessed via a reference stored in the database. This category of errors
This is all a Chromium implementation detail, so doesn't really belong in MDN like this. Different browsers could (and do) approach storing large values very differently. 

This page should lead with the error types (below), explain the cause (maybe mentioning that implementations can store values in different ways) and how developers should reason about what to do (e.g. retry if recovery is possible, wipe the database, etc)

2024-12-03 09:43 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +A {{domxref("DOMException")}} or `null` if there is no error. The following error names can be returned
Yup, that reads much better. I've used your wording, in the next commit.

2024-12-03 10:17 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you abort the transaction, then all requests still in progress receive this error.
Right, OK, that makes sense. So, for the ones that still belong on this page, I have marked them as asynchronous errors, and added a bit of text that comments on how they can be handled, based on your text above. Let me know if you think that approach makes sense.

I've also improved the code example snippet on the page so that the event handler logs the error name and message, rather than just the error object.

2024-12-03 10:24 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown in the `keyPath` argument contains an invalid key path.
Duh, yeah, sorry. I should have clocked this. I wrote most of the original IndexedDB MDN docs but have not looked at them for years! TBH, they could really use an overhaul, but that is beyond the scope of this PR.

For now, I've removed the errors that shouldn't be listed here, gone through the spec to see what methods they _are_ thrown on, and ensured they are included in their ref pages' "Exceptions" sections.

2024-12-03 10:33 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `TransactionInactiveError`
As before, I've removed it from this page and made sure that it is covered on the relevant method/property pages.

2024-12-03 10:36 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `ReadOnlyError`
As before, I've removed it from this page and made sure that it is covered on the relevant method/property pages.

2024-12-03 10:42 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `DataError`
As before, I've removed it from this page and made sure that it is covered on the relevant method/property pages.

2024-12-03 10:48 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `InvalidAccessError`
As before, I've removed it from this page and made sure that it is covered on the relevant method/property pages.

2024-12-03 11:15 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `InvalidStateError`
As before, I've removed it from this section and made sure that it is covered on the relevant method/property pages.

In this case, `InvalidStateError` can be thrown when you try to access the actual `error` property before the request is complete. So I've mentioned that on this page.

2024-12-03 11:19 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you run out of disk quota and the user declined to grant the application more space.
I've updated it to:

> Thrown if the application runs out of disk quota. In some cases, browsers prompt the user for more space, and the error is thrown if they decline the request. In other cases, the browser uses heuristics to determine whether more space can be assigned.

Does that work for you?

2024-12-03 11:20 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you try to open a database with a version lower than the one it already has.
As with `AbortError`, I've indicated that this error is asynchronous, and removed the "thrown" wording.

2024-12-03 11:25 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Thrown if you abort the transaction, then all requests still in progress receive this error.
I've also removed the "thrown" language in each case.

2024-12-03 11:29 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
>  In addition to the error codes sent to the {{ domxref("IDBRequest") }} object,
Yup, totally agree. I think I can just remove this section. This page is about async errors related to requests; there is no need to highlight that other errors occur in other places.

2024-12-03 11:39 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +Large IndexedDB values are not stored directly in the underlying database; instead, they are stored as separate files that are accessed via a reference stored in the database. This category of errors
Entirely agree. I've rephased/restructured it as suggested, and indicated that the storage description is just an example, which is the way Chrome does it.

2024-12-03 18:28 UTC, inexorabletash reviewed
Looking good, a few more nits/suggestions.

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbcursor/request/index.md
> +- `InvalidStateError` {{domxref("DOMException")}}
`request` never throws

(`key`/`primaryKey`/`value` do while the cursor is advancing since it's in between positions, but `request` has a stable value for the lifetime of the `IDBCursor` so never throws)

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbdatabase/createobjectstore/index.md
> +    either an empty string or an array containing an empty string.
Should be: "either an empty string or an array."

The array contents don't matter.

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbdatabase/createobjectstore/index.md
>    - : Thrown if a request is made on a source database that does not exist
Also if the upgrade transaction has completed, or is processing a request.

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Received if you insert data that doesn't conform to a constraint when creating stores and indexes.
"when creating stores and indexes" may be misleading; when you're calling `createObjectStore()` or `createIndex()` those are synchronous ops that throw. You could reword this as "... doesn't conform to a constraint when populating stores."

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +    For example, you will get this error if you try to add a new key that already exists in the record.
nit: "store" not "record"

alternately: "a new key that already exists for a record in the store"

(a record is a key/value pair in a store)

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Received for transient read failure errors, including general disk IO errors. See "Large value read failure errors" below for more details.
Should "Large value read..." be a hyperlink to the section?

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +- `NotFoundError` or `NotReadableError`
Looking at the spec, we don't issue "NotFoundError" in this case. 

https://github.com/w3c/IndexedDB/pull/430/files only added "NotReadableError" for this case.

But maybe I missed something?

2024-12-03 18:28 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +More recent browser versions have changed the error types and improved the error messages to help developers distinguish between transient and unrecoverable cases.
Maybe add: "Specifically, "NotReadableError" signals that the record is present in the database, but that the value could not be retrieved."

2024-12-04 18:21 UTC, wbamberg commented on files/en-us/web/api/idbdatabase/createobjectstore/index.md
>    - : Thrown if a request is made on a source database that does not exist
We should also remove that old Firefox bug info at this point.

2024-12-04 23:48 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +More recent browser versions have changed the error types and improved the error messages to help developers distinguish between transient and unrecoverable cases.
I might have some more questions about this, but for now:

First, is this behavior cross-browser/per spec? If not, what do other browsers do?
 
Second, reading this, I'm not that sure how strong the link is between transient/unrecoverable and specifically "large file read" errors. So I see docs that say: `DataError` or `UnknownError` are for transient errors, and `NotFoundError` or `NotReadableError` are for unrecoverable errors. But these ask me to read the section on "Large value read failure errors" for more detail. But really that section seems to be about a specific case that arises from a specific browser's implementation in some situations. Can we have transient/unrecoverable errors  in other situations (presumably so, right?). If so, then this seems to overstate the connection.

Maybe it might be better to call this section "Transient and unrecoverable read errors", and say: sometimes read errors have transient causes (such as low memory) and sometimes they are unrecoverable (for example, if the data itself has been deleted). Developers will want to handle these cases differently. In the first case the error will be `DataError` or `UnknownError` (which one depends on ? browser version? browser engine?). In the second case, the error will be `NotFoundError` or `NotReadableError` (again, depending on ?).

Overall, I think it's best to approach this from the point of view of: what useful advice can we give a developer trying to write cross-browser code that can properly distinguish and handle transient and unrecoverable errors?

2024-12-05 01:07 UTC, inexorabletash commented on files/en-us/web/api/idbrequest/error/index.md
> +More recent browser versions have changed the error types and improved the error messages to help developers distinguish between transient and unrecoverable cases.
This is where I might need to tag in others like @evanstade and @abhishek-shanthkumar and @asutherland

I believe recent Chromium changes were made to align behavior with Gecko (Firefox). But per https://github.com/w3c/IndexedDB/issues/423 there was a little bit of churn on all sides as we went from unspecified behavior to specified. Can the other folks I've tagged comment on what comprehensive documentation would be, and how much of a link there is between transient/unrecoverable vs. "large file" ?

Re:  _"it might be better to call this section "Transient and unrecoverable read errors""_ - agreed.

2024-12-10 09:05 UTC, chrisdavidmills commented on files/en-us/web/api/idbcursor/request/index.md
> +- `InvalidStateError` {{domxref("DOMException")}}
Yup, the spec makes this pretty clear. I've removed this "Exceptions" section.

2024-12-10 09:09 UTC, chrisdavidmills commented on files/en-us/web/api/idbdatabase/createobjectstore/index.md
> +    either an empty string or an array containing an empty string.
updated

2024-12-10 09:16 UTC, chrisdavidmills commented on files/en-us/web/api/idbdatabase/createobjectstore/index.md
>    - : Thrown if a request is made on a source database that does not exist
I've added the missing information and removed the out-of-date Firefox info.

2024-12-10 09:18 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : Received if you insert data that doesn't conform to a constraint when creating stores and indexes.
Sounds good; I've used your wording.

2024-12-10 09:20 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +    For example, you will get this error if you try to add a new key that already exists in the record.
Makes sense; I've updated it to "...new key that already exists in the store."

2024-12-10 09:29 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `NotFoundError` or `NotReadableError`
https://chromestatus.com/feature/5140210640486400 mentions `NotFoundError` being thrown in Chrome 130/131 for unrecoverable failures, but `NotReadableError` in Chrome 132, but I think I should just mention `NotReadableError` here regardless. Any historic Chrome info can go in the browser compat table.

2024-12-10 09:34 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `NotFoundError` or `NotReadableError`
Looking at the spec, `NotFoundError` is thrown on methods like `deleteObjectStore()` or `deleteIndex()` when the object store or index is not found. I've made sure it is mentioned in the exceptions lists on the appropriate pages.

2024-12-10 09:42 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- `NotFoundError` or `NotReadableError`
I've also done the same thing with the transient error names — just left `UnknownError` in this list and removed `DataError`, making sure that instead, `DataError` is mentioned on the method pages that can throw it.

2024-12-10 10:34 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +More recent browser versions have changed the error types and improved the error messages to help developers distinguish between transient and unrecoverable cases.
OK, I have:

- Added "Specifically, this error signals that the record is present in the database, but the value could not be retrieved." to the description of `NotReadableError` earlier on, as I think it makes more sense there.
- Updated the title to "Transient and unrecoverable read errors".
- Rearranged the structure a bit to be something more like Will suggested.
- Linked to the browser compat table for more information on browser-specific error types and behavior.

I'm hoping that we can get some more information about the state of things in other browsers to put here. Do you think this PR needs to be blocked on that info, or can we add it over time?

2024-12-10 19:03 UTC, inexorabletash reviewed
LGTM, one minor suggestion. I don't think we need to wait on perfect compat data before landing.

2024-12-11 09:22 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +  - : If you try to open a database with a version lower than the one it already has, this error is received.
Good call; done.

2024-12-11 23:18 UTC, wbamberg requested changes

2024-12-11 23:18 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +Read errors occur when an IndexedDB stores large blob values (for example, audio files for an offline podcast app), and then subsequently fails to read those values even though the associated records
"Read errors occur when an IndexedDB stores large blob values" - is it true that read errors only occur for "large blob values"? Is that even really relevant here?

I think the key message is: some read errors are transient and some are unrecoverable. As a developer you probably need to know the difference, so you can handle them seprately. Transient errors are signalled with `UnknownError`, and unrecoverable errors are signalled with `NotReadableError`.

I think everything else here is not that important. You might want to refer to large values in passing, as an example of an unrecoverable error: "for example, sometimes the browser might store large values in a separate file, referenced from the database, and the referenced file might have been deleted by a disk space recovery program". You might also want to explain a bit about what a developer should do in each case, which could be (for the "unrecoverable errors" case) a version of your paragraph beginning "Possible corrective actions". If you do that though it would also be good to say what a developer should do in the other case, if there is anything to say here.

2024-12-11 23:18 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +> The errors that represent these cases may vary across browsers. Check the [browser compatibility information](#browser_compatibility) for more details.
Not sure this note is needed. Everything might vary across browsers, you always need to check BCD.

2024-12-11 23:18 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +Such errors can manifest in different ways depending on browser, operating system, etc. For example, different IndexedDB implementations store large values in different ways. In Chrome, large Indexed
I don't think this paragraph is needed. It's also quite unclear "such errors" - errors such as what? Just read errors? There's no indication that this means specifically unrecoverable read errors. As I said above, I think a compressed version of this might be given as an example of "unrecoverable errors". I don't think the stuff about Chrome's implementation is needed or really in scope.

2024-12-11 23:18 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +Possible corrective actions for such cases might include notifying the user, deleting the entry from the database, then attempting to re-fetch the data from the server.
Again this is referring only to unrecoverable errors, but that's not clear from the context ("such cases" - which cases?)

2024-12-11 23:21 UTC, wbamberg commented on files/en-us/web/api/idbrequest/error/index.md
> +- Unrecoverable causes such as source blob files being deleted, represented in the spec by the `NotReadableError` type.
FWIW I think "represented in the spec by" is a slightly strange way to word this. We always describe the spec. Why can't we say something like  "Transient causes such as low memory are signalled using the `UnknownError` type."

2024-12-12 10:15 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- Unrecoverable causes such as source blob files being deleted, represented in the spec by the `NotReadableError` type.
Yeah, you're right. I've updated these sentences to use "signalled by":

> - Transient causes such as low memory, signalled by an `UnknownError` type.
> - Unrecoverable causes such as source blob files being deleted, signalled by a `NotReadableError` type.

2024-12-12 10:16 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +Possible corrective actions for such cases might include notifying the user, deleting the entry from the database, then attempting to re-fetch the data from the server.
OK; updated to "Possible corrective actions for unrecoverable read errors might include..."

2024-12-12 10:16 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +> The errors that represent these cases may vary across browsers. Check the [browser compatibility information](#browser_compatibility) for more details.
OK, I've removed the note.

2024-12-12 10:36 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +Such errors can manifest in different ways depending on browser, operating system, etc. For example, different IndexedDB implementations store large values in different ways. In Chrome, large Indexed
I've updated the paragraph to say "unrecoverable read errors" rather than "such errors" and removed the mention of Chrome, making the description more generic. However, I think it's useful to have an example of how an unrecoverable read error might occur, as readers might rightly think "well, how on earth could that happen?"

2024-12-12 11:15 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +Read errors occur when an IndexedDB stores large blob values (for example, audio files for an offline podcast app), and then subsequently fails to read those values even though the associated records
OK, so it is possible with any value, although it is more likely to happen with large values, for the kinds of reasons detailed in the example. So I've updated this sentence to "Read errors occur when an IndexedDB stores values and then subsequently fails to read those values..." and moved the example large file down to the example paragraph.

I've also restructured the section a bit, and attempted to fill in some more information on possible causes and solutions around transient errors. Saying that, it was hard to find much information around these.

@inexorabletash, can you check what I've written here and let me know if you think it makes sense? Thanks.

2024-12-12 11:17 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +- Unrecoverable causes such as source blob files being deleted, represented in the spec by the `NotReadableError` type.
Update - this ended up getting restructured significantly in a later edit.

2024-12-12 18:06 UTC, wbamberg approved these changes
👍 thank you Chris, I'm happy with this.

2024-12-16 09:32 UTC, chrisdavidmills commented on files/en-us/web/api/idbrequest/error/index.md
> +Read errors occur when an IndexedDB stores large blob values (for example, audio files for an offline podcast app), and then subsequently fails to read those values even though the associated records
Update — I'm going to go ahead and merge this, so we can have it squared away before the end of the year. If you do have issues with what I have written, I'll fix it up in a new PR.

2024-12-16 09:32 UTC, merged