Corrected spelling of word 'area'
mdn/content pull request #371
Opened 2020-12-17 19:10 UTC by pranjalshinde

I have changed a misspelled word 'arena' to 'area' in the document.

2020-12-17 19:38 UTC, chrisdavidmills requested changes
Hi @pranjalshinde !

First change looks fine, but the second one looks like a mistake?

2020-12-17 19:38 UTC, chrisdavidmills commented on files/en-us/games/anatomy/index.html
> +<p><span class="seoSummary">This article looks at the anatomy and workflow of the average video game from a technical point of view, in terms of how the main loop should run. It helps beginners to th
This change is fine...

2020-12-17 19:38 UTC, chrisdavidmills commented on files/en-us/games/anatomy/index.html
> +<p>The goal of every video game is to <strong>present</strong> the user(s) with a situation, <strong>accept</strong> their input, <strong>interpret</strong> those signals into actions, and <strong>ca
Whereas these three lines need to be removed.

2020-12-17 20:09 UTC, pranjalshinde commented on files/en-us/games/anatomy/index.html
> +<p>The goal of every video game is to <strong>present</strong> the user(s) with a situation, <strong>accept</strong> their input, <strong>interpret</strong> those signals into actions, and <strong>ca
Thank you for reviewing the code! It was a mistake which has resolved now.

2020-12-17 20:57 UTC, chrisdavidmills requested changes
ooop, one more comment, sorry!

2020-12-17 20:57 UTC, chrisdavidmills commented on files/en-us/games/anatomy/index.html
> -<p><span class="seoSummary">This article looks at the anatomy and workflow of the average video game from a technical point of view, in terms of how the main loop should run. It helps beginners to th
My apologies. On giving this a second read, I can see that "arena" is more correct than "area" in this context. But even better would be "...beginners to modern game development understand..."

2020-12-18 05:56 UTC, pranjalshinde commented on files/en-us/games/anatomy/index.html
> -<p><span class="seoSummary">This article looks at the anatomy and workflow of the average video game from a technical point of view, in terms of how the main loop should run. It helps beginners to th
Ohh okay!! I will make changes as you said...Thank you!!

2020-12-18 06:17 UTC, pranjalshinde commented
Changed "It helps beginners to the modern game development arena understand..." to  "It helps beginners to modern game development understand..."

2020-12-18 07:53 UTC, chrisdavidmills approved these changes
@pranjalshinde this is perfect now, thanks so much for your contribution!

2020-12-18 07:53 UTC, merged

2020-12-18 08:35 UTC, pranjalshinde commented
This was my first PR!! Thank you so much for the help!!!

2020-12-18 08:36 UTC, chrisdavidmills commented
@pranjalshinde I didn't realize that. Congratulations, and welcome! It's great to have you in the community.