Correct typo in stroke-linejoin svg attribute page
mdn/content pull request #37112
Opened 2024-12-05 20:49 UTC by farskid

### Description

There's a typo at https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin. it says `as been` instead of `has been`.

2024-12-06 10:24 UTC, chrisdavidmills requested changes
Hi @farskid, and thank you for your contribution to MDN! I've got a suggestion for you to consider — I think this is simpler, easier to read, and still effective. I removed the link to the compat table because there is no data there for `arcs` to say what browsers it is supported in, so the link is not useful.

I've filed an issue on the browser-compat-data project to ask if someone can add this data to make the compat table more useful: https://github.com/mdn/browser-compat-data/issues/25336.

Finally, there is an equivalent note in the `miter-clip` section — can you update that one, while you are here?

Thanks again!

2024-12-06 10:24 UTC, chrisdavidmills commented on files/en-us/web/svg/attribute/stroke-linejoin/index.md
> +> The `arcs` value has been introduced in SVG2 and it isn't widely supported yet, see [Browser compatibility](#browser_compatibility) below for details.
```suggestion
> The `arcs` value was introduced in SVG2 and isn't widely supported.
```

2025-02-03 10:54 UTC, bsmth commented
Hi @farskid - there's a review comment above for you, do you want to come back to this one? Thank you :)

2025-02-17 08:34 UTC, chrisdavidmills approved these changes
LGTM; thanks for fixing this, @Josh-Cena.

2025-02-17 08:37 UTC, merged