Add `::details-content` page
mdn/content pull request #37118
Opened 2024-12-06 11:58 UTC by lukewarlow

### Description

Add a page for the new `::details-content` pseudo element.

### Motivation

To help web developers discover this new feature.

### Additional details

### Related issues and pull requests

**Depends on:** https://github.com/mdn/interactive-examples/pull/2874

2024-12-09 10:32 UTC, chrisdavidmills requested changes
Nice work @lukewarlow. I've got a few comments for you to consider, but nothing too major.

2024-12-09 10:32 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_details-content/index.md
> +The **`::details-content`** [CSS](/en-US/docs/Web/CSS) [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) represents the contents of an {{HTMLElement("details") }}.
```suggestion
The **`::details-content`** [CSS](/en-US/docs/Web/CSS) [pseudo-element](/en-US/docs/Web/CSS/Pseudo-elements) represents the expendable/collapsible contents of a {{HTMLElement("details")}} element.
```

2024-12-09 10:32 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_details-content/index.md
> +{{EmbedInteractiveExample("pages/tabbed/pseudo-element-details-content.html", "tabbed-shorter")}}
Maybe comment this out until the interactive example is merged unless you'd rather just wait on publishing this until it is available?

2024-12-09 10:32 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_details-content/index.md
> +
Include a "Results" section containing an embedlivesample macro to show what the code looks like rendered? Follow the same pattern used in the https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button page.

2024-12-09 10:32 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_details-content/index.md
> +- [`<details>`](/en-US/docs/Web/HTML/Element/details)
Include the summary element too?

2024-12-09 10:32 UTC, chrisdavidmills commented on files/en-us/web/css/_doublecolon_details-content/index.md
> +## Specifications
I'd include a second example too, to show an animated transition from the closed to the open state of the details content, as shown in the spec: https://drafts.csswg.org/css-pseudo-4/#details-content-pseudo

AFAIUI, this is the main use case for this pseudo?

2024-12-11 09:26 UTC, chrisdavidmills approved these changes
@lukewarlow nice one.

I thought your updates looked great, but I thought the examples could use a bit of description/explanation. Because I worked on the `allow-discrete` animation stuff recently and it is still fresh in my head, I decided to edit the page directly and drop an explanation in. I hope that's OK with you.

I won't merge it yet, so you can check it out to make sure you are happy with it.

2024-12-11 09:29 UTC, chrisdavidmills commented
@lukewarlow, oooh, I also increased the transition duration to 600ms so that it is a bit easier to see what is happening. I also put the opacity transition first, as I thought it was easier to explain if I explained that one first.

2025-01-03 16:33 UTC, bsmth commented
@chrisdavidmills shall we merge this one :)

2025-01-03 17:10 UTC, merged