Update the rust version for rust wasm tutorial
mdn/content pull request #37141
Opened 2024-12-09 02:27 UTC by wtlin1228

### Description

Update the rust version used in the `Compiling from Rust to WebAssembly` page.

### Motivation

Reduce the mismatches when readers follow this tutorial.

### Additional details

### Related issues and pull requests

2024-12-09 08:56 UTC, chrisdavidmills requested changes
Hi @wtlin1228, and thank you for updating this! I've run through the tutorial with your changes and tested that it still works.

I have a couple of suggestions that I thought you could make while you are here, for a bit of extra improvement:

- You should change "Firstly, run the following command:" to "First, run the following command inside your `hello-wasm` directory:"
- In the "A digression about code size" section it says "If you check out the generated WebAssembly code size, it may be a few hundred kilobytes.". When I ran through the tutorial to test it, it was only 17KB, so I'm assuming that this has improved massively since the tutorial was first published. Maybe delete this section?

What do you think?

2024-12-09 10:31 UTC, wtlin1228 commented
Hi @chrisdavidmills, good suggestions! I'll go through the tutorial and update it as much as I can.

2024-12-10 08:37 UTC, wtlin1228 commented on files/en-us/webassembly/rust_to_wasm/index.md
> -This does a number of things (and they take a lot of time, especially the first time you run `wasm-pack`). To learn about them in detail, check out [this blog post on Mozilla Hacks](https://hacks.moz
The first run took 8s only

2024-12-10 11:10 UTC, chrisdavidmills approved these changes
Nice work @wtlin1228, your changes look great.

I also took it upon myself to copy edit the page a bit, as some of the language was a bit sloppy.

Let's get this merged!

2024-12-10 11:10 UTC, merged