Update CSP practical guide for consistency
mdn/content pull request #37227
Opened 2024-12-16 11:15 UTC by chrisdavidmills

### Description

After the [main MDN CSP guide](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) was updated to follow accepted advice from elsewhere (such as OWASP and Google), it became clear that our [practical CSP guide](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/CSP) (which is referenced by the [HTTP Observatory](https://developer.mozilla.org/en-US/observatory) tool)also needing updating to be consistent with this advice.

This PR attempts to do that. We need to be careful before merging that this is not only correct, but also gels with the reports returned by Observatory and Mozilla's sec team.

### Motivation

### Additional details

### Related issues and pull requests

2024-12-16 18:07 UTC, wbamberg reviewed
Thank you for this, Chris! I had a few comments. I also wonder though: why do we need this document, in this form, as well as https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#strict_csp ? It seems like they cover essentially the same ground, except https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#strict_csp adds some more details, that someone would have to know anyway if they want to implement strict CSP?

Should we consider making this doc much shorter, and just say "implement strict CSP, here's the link"?

2024-12-16 18:07 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +3. If an allowed script goes on to load other, third-party scripts, those scripts will fail to load because they won't have the required nonce or hash. Mitigate this problem by adding the `strict-dyn
Does "allows the first script to pass its nonce or hash value onto scripts that it loads" imply that there's actual passing on of the value? If so, there isn't: it just makes the trust kind of transitive, so a nonced script is considered trustworthy to dynamically load other scripts, which don't themselves need to be nonced.

2024-12-16 18:07 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +5. If you are still having trouble with certain items, you can consider widening the policy to be more permissive, adding specific sources as highlighted during testing; for example, `style-src 'self
Other weakenings, which keep a nonce/hash based approach: `unsafe-eval` makes the policy significantly less secure but still protects you against inline JS. And `unsafe-hashes` if you really can't get rid of inline event handlers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#unsafe-hashes.

2024-12-16 18:15 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +- Disable the use of unsafe [inline JavaScript](/en-US/docs/Web/HTTP/CSP#inline_javascript), meaning inline [event handler attributes](/en-US/docs/Web/HTML/Attributes#event_handler_attributes) such a
It's also probably worth mentioning somewhere that if a directive contains nonce or hashes, then AFAIK `unsafe-inline` is ignored (https://web.dev/articles/strict-csp#fallbacks, https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#inline_javascript).

Which makes me wonder why the observatory seems to complain about unsafe-inline in https://developer.mozilla.org/en-US/observatory/analyze?host=csp-evaluator.withgoogle.com.

2024-12-18 14:00 UTC, chrisdavidmills commented
> Thank you for this, Chris! I had a few comments. I also wonder though: why do we need this document, in this form, as well as https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#strict_csp ? It seems like they cover essentially the same ground, except https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#strict_csp adds some more details, that someone would have to know anyway if they want to implement strict CSP?
> 
> Should we consider making this doc much shorter, and just say "implement strict CSP, here's the link"?

@wbamberg I intended that this document be a short, snappy, "quickfire" guide to what you need to, do, which links back to your guide for a much more in-depth treatment of the topic. It looks from your comments that I perhaps haven't gone far enough. I'll revisit it now, considering your comments. I'll also look at the Observatory scoring criteria, to make sure I don't miss anything out that really needs to be in here.

2024-12-18 15:55 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +- Disable the use of unsafe [inline JavaScript](/en-US/docs/Web/HTTP/CSP#inline_javascript), meaning inline [event handler attributes](/en-US/docs/Web/HTML/Attributes#event_handler_attributes) such a
I've removed the incorrect sentence; I thought I'd done that already, TBH ;-)

I've also added a bullet about `unsafe-inline` being ignored if hashes/nonces are present, later on.

2024-12-18 16:17 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +5. If you are still having trouble with certain items, you can consider widening the policy to be more permissive, adding specific sources as highlighted during testing; for example, `style-src 'self
Added info on these

2024-12-18 19:06 UTC, wbamberg commented
> Thanks @wbamberg! I also chopped down some of the sections a bit, and removed all the extra examples at the bottom, and they didn't seem that useful really, and diluted the message of the guide. WDYT?

I'm not going to harp on about this endlessly, but for example, we just landed a guide about XSS, which describes strict CSP as one of the main defenses. The relevant bit is just this: https://developer.mozilla.org/en-US/docs/Web/Security/Attacks/XSS#deploying_a_csp . It doesn't quote a strict CSP, or talk about steps to deploying it, or strict-dynamic, or any other considerations. It really just says very quickly what a strict CSP is, and points to the guide page, which ought to give people all this detail and more. CSP is complicated, and duplicating a lot of these details introduces a lot of scope for errors.

2024-12-18 19:16 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +   - Adding `unsafe-hashes` allowsusing hashes to enable usage of inline event handlers and `style` attribute values.
```suggestion
   - Adding `unsafe-hashes` allows using hashes to enable usage of inline event handlers and `style` attribute values.
```

(although I prefer "allows you to use", "allows using" feels ungrammatical to me)

2024-12-18 19:24 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +## Additional guidance
I'm afraid I don't really have very good suggestions here, but this section feels a bit disorganized. It feels like a list of things about CSP, in any order, some of which are fairly critical security recommendations, some of which are deployment suggestions, some of which are quite niche web compat recommendations.

Some of them connect to and pay out information promised in the previous section, like `report-to` - why isn't this listed in "steps for implementing a CSP"?

Some are already covered in "Solution" but are duplicated here, like `object-src 'none'`.

`data` URL guidance is listed twice, the first time saying "care needs to be taken" (which I don't think is very helpful, what kind of care?) and the second says don't do it.

I think the bit about SVG is super niche and not warranted here.

It might be good to cut out all the duplicated/not needed stuff, put normal deployment things like `report-to` in the previous section, and see if there's a remaining list of "things not to put in your CSP", and if there ius, then add that as a subsection to "Solution".

2024-12-18 19:26 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +   - Adding `default-src https:` still provides some protection, disabling unsafe inline/`eval()` and only allowing loading of resources (images, fonts, scripts, etc.) over HTTPS.
I wonder: if you can deploy a strict CSP at all - that is, if you can add nonces or hashes to your sources - why would you also need to allowlist some sources, or allowlist all HTTPS sources?

2024-12-19 10:12 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
It is misleading, I agree, but not untrue; one problem is that the coverage was meant to be wider than these HTTP header pages, but for the moment we only have on other guide. ;-(

I've updated the main landing page to improve things here, calling the articles out as summaries, saying they cover "some best practices" and not "the best practices", and changing the subsection to be about "HTTP security fundamentals". I've also changed the description of the CSP article to say it is specifically about mitigating XSS.

2024-12-19 10:19 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +   - Adding `unsafe-hashes` allowsusing hashes to enable usage of inline event handlers and `style` attribute values.
Yeah, I agree that wording is better; updated.

2024-12-19 11:04 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +## Additional guidance
Yeah, this section was really crappy. I have added a separate section on reporting only CSPs, included some stuff in the "Steps..." section, and deleted/de-duplicated.

Also, it turns out that the Firefox SVG issue has bene fixed (see https://bugzilla.mozilla.org/show_bug.cgi?id=1773976), so I've just removed all that stuff.

2024-12-19 11:06 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +   - Adding `default-src https:` still provides some protection, disabling unsafe inline/`eval()` and only allowing loading of resources (images, fonts, scripts, etc.) over HTTPS.
Yeah, good point. I have changed this bullet from additions to the policy, to an alternative policy.

2024-12-19 18:04 UTC, wbamberg requested changes
Thanks for the updates, Chris! I like the shape of this document a lot better now.

2024-12-19 18:04 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
```suggestion
> If at all possible, avoid including unsafe sources inside your CSP. Examples include:
> - `unsafe-inline`
> - `data:` URIs inside `script-src`, `object-src`, or `default-src`
> - overly broad sources or form submission targets
>
> Similarly, the use of `script-src 'self'` can be unsafe for sites with JSONP endpoints. These sites should use a `script-src` that includes the path to their JavaScript source folder(s).
```

Is the JSONP thing only relevant to `self`? I thought it was an issue for any kind of location-based policy. I don't really understand this very well though.

2024-12-19 18:04 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +## Report-only CSPs
I would have made this an H3.

2024-12-19 18:04 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> [!NOTE] > `report-to` is preferred over the deprecated `report-uri`; however, both are still needed because `report-to` does not yet have full cross-browser support.
I guess the `>` at the start of this is a workaround for the new note format not working when the content starts with a backtick? In this situation Josh uses the old format. You could also do:

```suggestion
> [!NOTE] The `report-to` directive is preferred over the deprecated `report-uri`; however, both are still needed because `report-to` does not yet have full cross-browser support.
```

2024-12-19 18:09 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +   - `unsafe-eval` allows dynamic evaluation of strings as JavaScript, but beware: it defeats much of the purpose of having a CSP.
Could even pull step 8 out of the list into a subsequent paragraph, to emphasise that this is a departure from the main approach.

2024-12-20 10:08 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
>  - Preventing [manipulator-in-the-middle](/en-US/docs/Glossary/MitM) (MiTM) attacks by upgrading any HTTP connections to HTTPS. This is helped by the CSP [`upgrade-insecure-requests`](/en-US/docs/Web/
updated ;-)

2024-12-20 10:12 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
>  ### Steps for implementing CSP
I disagree; it is not just that — strict CSP is the main thrust of it, but it also covers other things, like alternatives if strict CSP isn't for you, and reporting. I'm going to leave this as-is.

2024-12-20 10:22 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +2. Make sure that external and internal scripts (included via {{htmlelement("script")}} elements) that you want to run have the correct nonce inserted into the [`nonce`](/en-US/docs/Web/HTML/Element/
OK, I have updated the structure, merging the two bullets into one and adding an extra bullet about choosing nonces or hashes.

2024-12-20 10:24 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +3. If an allowed script goes on to load other, third-party scripts, those scripts will fail to load because they won't have the required nonce or hash. Mitigate this problem by adding the [`strict-dy
Yup, your suggestion is much better ;-)

Updated.

2024-12-20 10:35 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
Suggestion applied. I don't know about the JSONP thing either.

2024-12-20 10:36 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +## Report-only CSPs
Yeah, I agree with this. It's not really a standalone topic. Updated.

2024-12-20 10:39 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> [!NOTE] > `report-to` is preferred over the deprecated `report-uri`; however, both are still needed because `report-to` does not yet have full cross-browser support.
No, that's just what prettier does to it as a result of the error. I usually fix such instances in the manner you've suggested, but I missed this one. Fixed now!

2024-12-20 17:12 UTC, wbamberg commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
>  ### Steps for implementing CSP
Yes, fair enough.

2024-12-20 17:16 UTC, wbamberg approved these changes
Thank you for the updates, Chris! I'm not merging in case you want feedback from the people tagged in your description, but otherwise I'm happy for this to go.

2024-12-21 14:21 UTC, merged

2024-12-21 14:24 UTC, chrisdavidmills commented
> Thank you for the updates, Chris! I'm not merging in case you want feedback from the people tagged in your description, but otherwise I'm happy for this to go.

Thank YOU, @wbamberg! I think this is much better now, and it doesn't really lack any information that it had before. I am therefore electing to merge it rather than leave it lying around. If anyone else has concerns about the content update, I can always create a new PR to handle it.

2025-01-06 07:49 UTC, mozfreddyb commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
The JSONP issue is a problem for all sorts host-based lists.

2025-01-06 09:22 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
@mozfreddyb looking at https://stackoverflow.com/questions/613962/is-jsonp-safe-to-use#614006, it seems that JSONP is an old hack for achieving cross-domain requests, and we no longer need to do it now we have CORS. This being the case, do we still need to mention it? Do people still do JSONP out in the wild?

If so, what do you think I should say here?

2025-01-06 12:29 UTC, mozfreddyb commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
Dunno if people use it. Probably just fine to ignore alltogether, I agree.

2025-01-06 14:33 UTC, chrisdavidmills commented on files/en-us/web/security/practical_implementation_guides/csp/index.md
> +> If at all possible, avoid including unsafe sources inside your CSP. Examples include `unsafe-inline`, `data:` URIs inside `script-src`, `object-src`, or `default-src`, and overly broad sources or f
OK. I've filed https://github.com/mdn/content/pull/37521