Update index.md
mdn/content pull request #37339
Opened 2024-12-22 15:01 UTC by geryogam

2024-12-23 11:18 UTC, chrisdavidmills requested changes
Hi there @geryogam, and thank you for this fantastic contribution to MDN. It improves consistency with the rest of MDN, and significantly improves readability.

I've made some suggestions, but nothing serious.

All the best.

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +The cascade is in ascending order, meaning animations take precedence over normal values, whether those values are declared in user, author, or user-agent styles, important values take precedence ove
That sentence is long and difficult to parse; how about splitting it up like this?

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +If any of the layered styles in A, B, or C, have selectors with higher specificity matching an element, similar to `:root body p { color: black; }`, it doesn't matter. Those declarations are removed
```suggestion
If any layered styles in A, B, or C have selectors with higher specificity matching an element, similar to `:root body p { color: black; }`, it doesn't matter. Those declarations are removed from consideration because of _origin_; normal layered styles have less precedence than normal unlayered styles. If, however, the more specific selector `:root body p { color: black; }` was found in `unlayeredStyles.css`, as both _origin and importance_ have the same precedence, _specificity_ would mean the more specific, black declaration would win.
```

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +Only relevant to author styles are inline styles, declared with the `style` attribute. Normal inline styles take precedence over any other normal author styles, no matter the specificity of the selec
I'm not 100% sure about this, but it feels like moving the bit about animations/transitions as you have done splits the previous point into two, making it slightly less obvious what the third sentence connects to or why it is there. 

As a fix to this, maybe add to the end of the third sentence something like ", unless it is being animated."?

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +Important inline styles take precedence over any other author styles, important or not, inline or not, layered or not. Important styles also take precedence over animated properties but not transitio
```suggestion
Important inline styles take precedence over all other author styles, regardless of whether they are important, inline, or layered. Important styles also take precedence over animated properties, but not transitioned properties. Three things can override an important inline style:

- An important user style.
- An important user agent style.
- A transitioned property.
```

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +[CSS animations](/en-US/docs/Web/CSS/CSS_animations), using {{cssxref("@keyframes")}} at-rules, define animations between states. `@keyframes` don't cascade, meaning that at any given time CSS takes
```suggestion
[CSS animations](/en-US/docs/Web/CSS/CSS_animations), using {{cssxref("@keyframes")}} at-rules, define animations between states. `@keyframes` don't cascade, meaning that at any given time CSS takes values from only one single set of `@keyframes` and never mixes multiple ones. If multiple sets of `@keyframes` are defined with the same animation name, the last defined set in the origin and layer with the greatest precedence is used. Other `@keyframes` are ignored, even if they animate different properties.
```

2024-12-23 11:18 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +[CSS animations](/en-US/docs/Web/CSS/CSS_animations), using {{cssxref("@keyframes")}} at-rules, define animations between states. `@keyframes` don't cascade, meaning that at any given time CSS takes
Breaking up long sentence, clearing up perceived plurality weirdness.

2024-12-24 14:03 UTC, geryogam commented on files/en-us/web/css/cascade/index.md
> +The cascade is in ascending order, meaning animations take precedence over normal values, whether those values are declared in user, author, or user-agent styles, important values take precedence ove
Thanks, I agree it's more readable.

2024-12-24 14:23 UTC, geryogam commented on files/en-us/web/css/cascade/index.md
> +Only relevant to author styles are inline styles, declared with the `style` attribute. Normal inline styles take precedence over any other normal author styles, no matter the specificity of the selec
Alright, I added a distinct sentence for animated and transitioned properties for normal inline styles, following the same structure as important inline styles.

2024-12-30 10:21 UTC, chrisdavidmills commented on files/en-us/web/css/cascade/index.md
> +Only relevant to author styles are inline styles, declared with the `style` attribute. Normal inline styles take precedence over any other normal author styles, no matter the specificity of the selec
Yup, this looks good - thanks!

2024-12-30 10:25 UTC, chrisdavidmills approved these changes
Great, thanks for the updates, @geryogam! This is ready to merge.

2024-12-30 10:25 UTC, merged

2024-12-30 22:29 UTC, geryogam commented
Thanks for the review!