Reference for stage 3 temporal
mdn/content pull request #37344
Opened 2024-12-23 06:12 UTC by Josh-Cena

https://github.com/mdn/content/issues/27745

Far from ready for review, and I'll work on this alone for a while

2025-01-03 22:07 UTC, justingrant commented
Amazing work on this!  Given the scale of the PR, I assume that there will be lots of smaller follow-ups to tune and improve this content over time. 

I'll leave a few notes inline on a few pages.

2025-01-05 01:20 UTC, justingrant reviewed
@Josh-Cena this is such good technical writing!  Really excellent work on these docs. Thank you so much for doing this massive amount of high-quality work. 

I ran out of time to review more than the ZDT index page, but I left a lot of comments there relating to time zones and offsets. Feel free to follow up with me here or in the Temporal proposal repo with any follow-ups. I'll try to post more feedback when I have time.

Also, a more general question: when the docs refer to a Temporal type, should the namespace be included (i.e. `Temporal.ZonedDateTime`) or excluded (i.e. `ZonedDateTime`)?  We (the Temporal champions) always assumed that it'd be better for programmers to always see the full namespaced name so they'd not be tempted to write `ZonedDateTime.from` and fail because they forgot the namespace. But there may be existing conventions in MDN that exclude the namespace, and if so then OK!

2025-01-05 01:20 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +- If the time is specified in UTC via the `Z` offset.
```suggestion
- If the time is specified in UTC via the `Z` offset. Using `Z` in an RFC 9557 string tells Temporal to use the square-bracketed time zone annotation to determine the offset.
```

2025-01-05 01:20 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +  - : Use the offset to calculate the exact time. This keeps the same exact time as originally calculated when we stored the time. The time zone identifier is still used to then infer the correct off
```suggestion
  - : Use the offset to calculate the exact time. This option "uses" the offset when determining the instant represented by the string, which will be the same instant originally calculated when we stored the time, even if the offset at that instant has changed. The time zone identifier is still used to then infer the (possibly updated) offset and use that offset to convert the exact time to local time.
```

2025-01-05 01:20 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +  - : Use the time zone identifier to re-calculate the offset, ignoring what's specified. This keeps the same local time as originally calculated when we stored the time. Note that this causes the sa
```suggestion
  - : Use the time zone identifier to re-calculate the offset, ignoring the offset that's specified in the string. This option keeps the same local time as originally calculated when we stored the time, but may correspond to a different instant. Note that this option may cause the same local time interpretation ambiguity as demonstrated above, which is resolved using the `disambiguation` option.
```

2025-01-05 01:20 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +Note that the `Z` offset does not mean `+00:00`; it is always considered valid regardless of the time zone. The time is interpreted as a UTC time, and the time zone identifier is then used to convert
```suggestion
Note that the `Z` offset does not mean `+00:00`; it is always considered valid regardless of the time zone. The time is interpreted as a UTC time, and the time zone identifier is then used to convert it to local time. In other words, `Z` enforces the same behavior as the `ignore` option and its results can never be ambiguous.
```

2025-01-05 01:20 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +> Although {{jsxref("Temporal/Instant/from", "Temporal.Instant.from()")}} also takes an ISO 8601 string in the same form, there is no ambiguity because it always ignores the time zone identifier and
Like above, we should refer to RFC 9557 here, not ISO 8601.

2025-01-05 01:45 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +### ISO 8601 format
So, we should remove mentions to "ISO 8601" across the board and replace them with "RFC 9557", right? Because we have this same section in every API.

2025-01-05 01:48 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +Firefox has always been overriding these legacy names, while others have not (Safari and Chrome). There is [an effort in TC39 to properly handle these canonical identifiers](https://github.com/tc39/p
For context, this paragraph has always been there; it's just moved from `Intl.Locale#getTimeZones` to here now we have a more canonical place to talk about time zones. While writing these docs, I checked `resolvedOptions().timeZone` again, and it seems that Chrome now stops canonicalizing while Firefox and Safari still canonicalize in opposite directions.

2025-01-05 01:50 UTC, Josh-Cena commented
> Also, a more general question: when the docs refer to a Temporal type, should the namespace be included (i.e. `Temporal.ZonedDateTime`) or excluded (i.e. `ZonedDateTime`)?

We have no conventions. I usually use `Temporal.ZonedDateTime` for the first time on a page, but then I may shorten it for brevity, because repeating it many times seems noisy. I'll try to replace a few of these where it's fine, but for example we often use `DateTimeFormat` without `Intl.` too.

2025-01-05 01:52 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +### ISO 8601 format
Yeah, that's probably a good idea. Developers still know ISO 8601 (and to a lesser extent, RFC 3339) more than the brand-new RFC 9557, so it'd be smart to provide a Google honeytrap for "parse an ISO 8601 string with a time zone" but I think it's fine to mention all three standards in one place, and then to refer to RFC 9557 everywhere else.

2025-01-05 01:58 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +Firefox has always been overriding these legacy names, while others have not (Safari and Chrome). There is [an effort in TC39 to properly handle these canonical identifiers](https://github.com/tc39/p
Lol, I didn't know that Chrome had already made that change. When did they make it?  I just tested on latest non-Canary Chrome (`131.0.6778.205 (Official Build) (arm64)`) and it's still canonicalizing to the old IDs: 

<img width="608" alt="image" src="https://github.com/user-attachments/assets/95c15b1b-9087-4910-aa58-bd6a251b7f42" />

In any case, I'd still recommend replacing this paragraph with the content in https://github.com/mdn/content/pull/37344#discussion_r1903175463.

2025-01-05 02:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +Firefox has always been overriding these legacy names, while others have not (Safari and Chrome). There is [an effort in TC39 to properly handle these canonical identifiers](https://github.com/tc39/p
D'oh, I must have messed up somewhere in my tests or was just tired. Yeah it doesn't seem like they've changed.

2025-01-05 02:11 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +We already demonstrated how ambiguity may arise from interpreting a local time in a time zone, without providing an explicit offset. However, if you provide an explicit offset, then another conflict
```suggestion
We already demonstrated how ambiguity may arise from interpreting a local time in a time zone, without providing an explicit offset. However, if you provide an explicit offset, then another conflict arises: between the offset as specified, and the offset as calculated from the time zone and the local time. This is an unavoidable real-world issue: if you store a time in the future, with an anticipated offset, then before that time comes, the time zone definition may have changed due to political reasons. For example, suppose in 2018, I set a reminder at the time `2019-12-23T12:00:00-02:00[America/Sao_Paulo]` (which is a daylight saving time; Brazil is in the southern hemisphere, so it enters DST in October and exits in February). But before that time comes, in early 2019, Brazil decides to stop observing DST, so the real offset becomes `-03:00`. Should the reminder now still fire at noon (keeping the local time), or should it fire at 11:00 AM (keeping the exact time)?
```

2025-01-05 18:40 UTC, justingrant commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/index.md
> +Firefox has always been overriding these legacy names, while others have not (Safari and Chrome). There is [an effort in TC39 to properly handle these canonical identifiers](https://github.com/tc39/p
OK, cool. It was my previous understanding that V8 was planning to sync up changes to this behavior with Temporal Stage 4. The reasoning is that currently the only way to compare two time zones for equality is to use `resolvedOptions().timeZone` by checking to see if they both canonicalize to the same ID. Once Temporal is available, then `Temporal.ZonedDateTime.equals` can be used for this purpose instead, which makes it less worrisome to change `resolvedOptions().timeZone` canonicalization behavior.

2025-01-05 23:49 UTC, Josh-Cena commented
@justingrant I have two hesitations:

1. In your suggested edit, I'm not sure the following is correct:
   
   > You can, in rare circumstances, use an ISO 8601 / RFC 3339 string in place of an offset time zone identifier in two APIs only: `Temporal.ZonedDateTime.prototype.withTimeZone` and in the `timeZoneId` option when using `Temporal.ZonedDateTime.from` to create an instance from a property bag.
   
   As I understand, all places that accept time zone identifiers, including `toZonedDateTime` and `Temporal.Now`, accept such strings. I've reworded this section a bit:
   
   > For convenience, when providing a time zone identifier to `Temporal` APIs such as `Temporal.ZonedDateTime.prototype.withTimeZone()` and the `timeZoneId` option of `Temporal.ZonedDateTime.from()`, you can provide it in a few other forms:
   >
   > - As another `ZonedDateTime` instance, whose `timeZoneId` will be used.
   > - As an [RFC 9557 string](#rfc_9557_format) wih a time zone annotation, whose time zone identifier will be used.
   > - As an ISO 8601 / RFC 3339 string containing an offset, whose offset will be used as an offset identifier; or, if using `Z`, then the `"UTC"` time zone is used. This usage is generally not recommended, because as discussed above, offset identifiers lack the ability to safely derive other `Temporal.ZonedDateTime` instances across an offset transition like when daylight saving time starts or ends. Instead, consider just using `Temporal.Instant` or fetching the user's actual named time zone.

2. The spec makes exclusive references to ISO 8601, because I understand it, RFC 9557 is essentially "ISO 8601 + ECMAScript extensions". Is it expected that this extension, once standardized, is also going to be identified as ISO 8601? Or is the spec going to be updated in this case? For example, https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimezonestring.

2025-01-06 10:47 UTC, justingrant commented
> As I understand, all places that accept time zone identifiers, including `toZonedDateTime` and `Temporal.Now`, accept such strings. I've reworded this section a bit:

Whoops, yep you're correct. I forgot about those other callsites. As long as your revised text includes the explanation of why ZDT.from(string) requires a bracketed extension, then I'm happy.

> The spec makes exclusive references to ISO 8601, because I understand it, RFC 9557 is essentially "ISO 8601 + ECMAScript extensions". Is it expected that this extension, once standardized, is also going to be identified as ISO 8601? Or is the spec going to be updated in this case? For example, https://tc39.es/proposal-temporal/#sec-temporal-parsetemporaltimezonestring.

The spec should probably be updated to reflect RFC 9557, which was published a few months ago, but it's hard to know without seeing the context. Could you file an issue in the proposal repo with any mentions of ISO 8601 that you found?  Thanks!

2025-01-06 17:14 UTC, Josh-Cena commented
Suggestion for MDN reviewers (copied from Slack):

Rather than dividing "vertically" by classes, I suggest dividing "horizontally" by properties of the same name because they are often copied around. The Temporal overview page has several tables summarizing all available APIs. There are the following groups:

- All pages outside Temporal
- `Temporal.Duration`
- `Temporal.Now`
- Methods (for methods and properties, check https://pr37344.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#shared_class_interface):
  - Construction (`constructor`, `from*()`, `with*()`)
  - Arithmetic (`add()`, `subtract()`, `since()`, `until()`, `round()`, `equals()`, `compare()`)
  - Serialization (`toString()`, `toLocaleString()`, `valueOf()`, `toJSON()`)
- Properties:
  - Calendar (`calendarId` to `dayOfYear`)
  - Time (`hour` to `nanosecond`)
- Misc (all from `ZonedDateTime`): `getTimeZoneTransition()`, `startOfDay()`, `timeZoneId`, `offset`, `offsetNanoseconds`
- [Conversion methods](https://pr37344.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#conversion_between_classes)

2025-01-07 19:04 UTC, Josh-Cena commented
I've made a spreadsheet here: https://docs.google.com/spreadsheets/d/1RrRHL0m08R4V4WtuWBbSWr9a1gO4RiIaH42WrPv_Uhs/edit Welcoming anyone on the team for editorial reviews!

2025-01-09 09:42 UTC, chrisdavidmills requested changes
@Josh-Cena here is a review of all the pages outside temporal. Looking good, nothing major as far as I can see!

2025-01-09 09:42 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +    All {{jsxref("Temporal")}} objects implement the `toJSON()` method which returns a string (the same as calling `toString()`). Thus, they will be stringified as strings. Similarly, {{jsxref("Date"
```suggestion
    All {{jsxref("Temporal")}} objects implement the `toJSON()` method, which returns a string (the same as calling `toString()`). Thus, they will be stringified as strings. Similarly, {{jsxref("Date")}} objects implement `toJSON()`, which returns the same as [`toISOString()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).
```

2025-01-09 09:42 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +    All {{jsxref("Temporal")}} objects implement the `toJSON()` method which returns a string (the same as calling `toString()`). Thus, they will be stringified as strings. Similarly, {{jsxref("Date"
Also, maybe a stupid question, but is it necessary to say "Thus, they will be stringified as strings."? Surely the process of stringification always creates a string?

2025-01-09 15:51 UTC, meyerweb requested changes

2025-01-09 17:27 UTC, Josh-Cena commented on files/en-us/web/javascript/guide/numbers_and_dates/index.md
> +> The `Date` object is now considered legacy and should be avoided in new code. We will update this section with modern alternatives soon.
By "soon" I mean "soon": I will be writing the `Temporal` guide as soon as this reference gets merged, so it's not really "when appropriate".

2025-01-09 17:29 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/array/tolocalestring/index.md
> +  - : An object with configuration properties. What you can pass here depends on what elements are being converted. For example, for numbers, see {{jsxref("Number.prototype.toLocaleString()")}}.
I think my original "for X, see Y" reads better; in general I usually prefer more commas to less.

2025-01-09 17:31 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/totemporalinstant/index.md
> +A new {{jsxref("Temporal.Instant")}} object with the same {{jsxref("Temporal/Instant/epochMilliseconds", "epochMilliseconds")}} value as this date's timestamp. Its {{jsxref("Temporal/Instant/microsec
Oof, good catch, there are no such things.

2025-01-09 17:31 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/date/totemporalinstant/index.md
> +A new {{jsxref("Temporal.Instant")}} object with the same {{jsxref("Temporal/Instant/epochMilliseconds", "epochMilliseconds")}} value as this date's timestamp. Its {{jsxref("Temporal/Instant/microsec
```suggestion
A new {{jsxref("Temporal.Instant")}} object with the same {{jsxref("Temporal/Instant/epochMilliseconds", "epochMilliseconds")}} value as this date's timestamp. Its microsecond and nanosecond components are always `0`.
```

2025-01-09 17:35 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/index.md
> +- {{jsxref("Temporal")}}
We don't need to manually add any status badges or banners; they are automatically derived from BCD where needed. Manually adding them may cause them to be added in places where the BCD sync script does not recognize and eventually go stale.

2025-01-09 17:37 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/datetimeformat/index.md
> +The date-time component styles requested may not directly correspond to a valid format supported by the locale, so the format matcher allows you to specify how to match the requested styles to the cl
```suggestion
The date-time component styles requested might not directly correspond to a valid format supported by the locale, so the format matcher allows you to specify how to match the requested styles to the closest supported format.
```

2025-01-09 17:38 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/datetimeformat/index.md
> +- `formatMatcher`
This is not a "date-time component option" in the sense that everywhere else where we link to that H4, we are not referring to this option, but to options like `year` or `hour`. This however is tightly connected to those for the purpose of `DateTimeFormat` itself, which is why it's still under the same section.

2025-01-09 17:39 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/datetimeformat/index.md
> +- If the `dateStyle` is specified, then you can format {{jsxref("Temporal.PlainDate")}}, {{jsxref("Temporal.PlainYearMonth")}}, and {{jsxref("Temporal.PlainMonthDay")}} objects.
```suggestion
You can format different object types depending on which of the style shortcut options you include:

- If the `dateStyle` is specified, then you can format {{jsxref("Temporal.PlainDate")}}, {{jsxref("Temporal.PlainYearMonth")}}, and {{jsxref("Temporal.PlainMonthDay")}} objects.
```

2025-01-09 17:40 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/index.md
> +- {{domxref("Temporal/Instant/toLocaleString", "Temporal.Instant.prototype.toLocaleString()")}}
I blame Copilot.

2025-01-09 17:42 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/intl/index.md
> -- {{jsxref("Date.prototype.toLocaleTimeString()")}}
I've removed all references to specific locale-sensitive functions here, because there are too many of them and this is the `Intl` landing page. Instead, I've moved them to each of the `Intl` class that they are relevant to.

2025-01-09 17:43 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/json/stringify/index.md
> +    All {{jsxref("Temporal")}} objects implement the `toJSON()` method which returns a string (the same as calling `toString()`). Thus, they will be stringified as strings. Similarly, {{jsxref("Date"
This is because the API is called `JSON.stringify`, so we use "stringify" as a synonym as "serialize"... We really meant to say "serialized as strings". People may expect them to be "serialized as objects", i.e. `"{ "hour": 12, "minute": 30 }` etc.

2025-01-09 18:10 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/epochmilliseconds/index.md
> +The **`epochMilliseconds`** accessor property of {{jsxref("Temporal.Instant")}} instances returns an integer representing the number of milliseconds elapsed since the Unix epoch (midnight at the begi
It is a convention to say "this X" where X is the natural-language form of the class; for example, "this map", "this date", "this array". This is a substitution for "to the instant represented by the `Instant` object that is `this`".

2025-01-09 21:30 UTC, fiji-flo commented
@Josh-Cena changing the PR title to `[new-ci] Reference for stage 3 temporal` would trigger a preview using rari (so you get the new sidebar). I see that I land these changes tomorrow and we can change the title back.

2025-01-09 21:36 UTC, Josh-Cena commented
OK but the new CI action is getting skipped

2025-01-09 22:55 UTC, meyerweb requested changes
Temporal.Instant and Temporal.PlainDate index pages

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Replace `calendar_id` with the calendar to use. May have a _critical flag_ by prefixing the key with `!`: e.g., `[!u-ca=iso8601]`. This flag generally tells other systems that it cannot be igno
s/in ISO/as an ISO 8601 calendar date/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +The {{jsxref("Temporal/PlainDate/from", "Temporal.PlainDate.from()")}}, {{jsxref("Temporal/PlainDate/with", "Temporal.PlainDate.prototype.with()")}}, {{jsxref("Temporal/PlainDate/add", "Temporal.Plai
s/and the counterparts/and their counterparts/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +The {{jsxref("Temporal/PlainDate/from", "Temporal.PlainDate.from()")}}, {{jsxref("Temporal/PlainDate/with", "Temporal.PlainDate.prototype.with()")}}, {{jsxref("Temporal/PlainDate/add", "Temporal.Plai
Not sure if “In the ISO calendar” should be “In the ISO 8601 calendar” or not.

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Returns a calendar-specific lowercase string representing the era of this date, or `undefined` if the calendar does not use eras (e.g. ISO 8601). `era` and `eraYear` together uniquely identify
s/same way as `year` does/same way that `year` does/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Returns a non-negative integer representing the year of this date within the era, or `undefined` if the calendar does not use eras (e.g. ISO 8601). The year index usually starts from 1 (more co
s/same way as `year` does/same way that `year` does/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Returns a boolean indicating whether this date is in a leap year. A leap year is a year that has more days (a leap day or leap month) than a common year. [Calendar](/en-US/docs/Web/JavaScript/R
s/(a leap day or leap month)/(due to a leap day or leap month)/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Returns an integer representing the number of years of this date relative to the start of a calendar-specific epoch year. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal
s/middle of the year, the year/middle of the year, that year/

2025-01-09 22:55 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +  - : Returns a string representing this date in the same [RFC 9557 format](#rfc_9557_format) as calling {{jsxref("Temporal/PlainDate/toString", "toString()")}}.
This method is automatically called by {{jsxref("JSON.stringify()")}} when a `Temporal.Instant` object is stringified.

2025-01-09 23:28 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/index.md
> +  - : Returns a string with a language-sensitive representation of this instant. In implementations with [`Intl.DateTimeFormat` API](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeF
@meyerweb For simple changes like this you can use the suggestion button to just propose the new sentence.

2025-01-09 23:34 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/index.md
> +The {{jsxref("Temporal/PlainDate/from", "Temporal.PlainDate.from()")}}, {{jsxref("Temporal/PlainDate/with", "Temporal.PlainDate.prototype.with()")}}, {{jsxref("Temporal/PlainDate/add", "Temporal.Plai
I reckon this is fine, since the methods are named `toZonedDateTimeISO` etc. too 🤷‍♂️

2025-01-10 13:18 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/index.md
> +  - : Returns a string with a language-sensitive representation of this instant. In implementations with [`Intl.DateTimeFormat` API](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeF
Today I learned about the suggestion button!  Will do.

2025-01-10 16:47 UTC, meyerweb requested changes
plainDateTime and plainMonthDay indexes

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the 1-based day index in the week of this date. Days in a week are numbered sequentially from `1` to {{jsxref("Temporal/PlainDateTime/daysInWeek", "daysI
```suggestion
  - : Returns a positive integer representing the 1-based day index in the week of this date. Days in a week are numbered sequentially from `1` to {{jsxref("Temporal/PlainDateTime/daysInWeek", "daysInWeek")}}, with each number mapping to its name. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. 1 usually represents Monday in the calendar, even when locales using the calendar may consider a different day as the first day of the week (see {{jsxref("Intl/Locale/getWeekInfo","Intl.Locale.prototype.getWeekInfo()")}).
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the number of days in the week of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent.
```suggestion
  - : Returns a positive integer representing the number of days in the week of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. For the ISO 8601 calendar, this is always 7, but in other calendar systems it may differ from week to week.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the number of days in the year of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent.
```suggestion
  - : Returns a positive integer representing the number of days in the year of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. For the ISO 8601 calendar, this is 365, or 366 in a leap year.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a calendar-specific lowercase string representing the era of this date, or `undefined` if the calendar does not use eras (e.g. ISO 8601). `era` and `eraYear` together uniquely identify
```suggestion
  - : Returns a calendar-specific lowercase string representing the era of this date, or `undefined` if the calendar does not use eras (e.g. ISO 8601). `era` and `eraYear` together uniquely identify a year in a calendar, in the same way that `year` does. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. For Gregorian, it is either `"gregory"` or `"gregory-inverse"`.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the 1-based month index in the year of this date. The first month of this year is `1`, and the last month is the {{jsxref("Temporal/PlainDateTime/monthsI
```suggestion
  - : Returns a positive integer representing the 1-based month index in the year of this date. The first month of this year is `1`, and the last month is the {{jsxref("Temporal/PlainDateTime/monthsInYear", "monthsInYear")}}. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Note that unlike {{jsxref(""Date/getMonth,"Date.prototype.getMonth()"}}, the index is 1-based. If the calendar has leap months, then the month with the same {{jsxref("Temporal/PlainDate/monthCode","monthCode")}} may have different month indexes for different years.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a calendar-specific string representing the month of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent.
```suggestion
  - : Returns a calendar-specific string representing the month of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Usually it is `M` plus a two-digit month number. For leap months, it is the previous month's code followed by `L`. If the leap month is the first month of the year, the code is `M00L`.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the number of months in the year of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent.
```suggestion
  - : Returns a positive integer representing the number of months in the year of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. For the ISO 8601 calendar, this is always 12, but in other calendar systems it may differ.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the 1-based week index in the {{jsxref("Temporal/PlainDateTime/yearOfWeek", "yearOfWeek")}} of this date, or `undefined` if the calendar does not have a
```suggestion
  - : Returns a positive integer representing the 1-based week index in the {{jsxref("Temporal/PlainDateTime/yearOfWeek", "yearOfWeek")}} of this date, or `undefined` if the calendar does not have a well-defined week system. The first week of the year is `1`. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Note that for ISO 8601, the first and last few days of the year may be attributed to the last week of the previous year or the first week of the next year.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns an integer representing the number of years of this date relative to the start of a calendar-specific epoch year. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal
```suggestion
  - : Returns an integer representing the number of years of this date relative to the start of a calendar-specific epoch year. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Usually year 1 is either the first year of the latest era or the ISO 8601 year `0001`. If the epoch is in the middle of the year, that year will have the same value before and after the start date of the era.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns an integer representing the year to be paired with the {{jsxref("Temporal/PlainDateTime/weekOfYear", "weekOfYear")}} of this date, or `undefined` if the calendar does not have a well-de
```suggestion
  - : Returns an integer representing the year to be paired with the {{jsxref("Temporal/PlainDateTime/weekOfYear", "weekOfYear")}} of this date, or `undefined` if the calendar does not have a well-defined week system. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Usually this is the year of the date, but for ISO 8601, the first and last few days of the year may be attributed to the last week of the previous year or the first week of the next year, causing the `yearOfWeek` to differ by 1.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a new `Temporal.PlainDateTime` object representing this date-time with the time part entirely replaced by the new time (in a form convertible by {{jsxref("Temporal/PlainTime/from", "Tem
```suggestion
  - : Returns a new `Temporal.PlainDateTime` object representing this date-time with the time part entirely replaced by the new time (in a form convertible by {{jsxref("Temporal/PlainTime/from", "Temporal.PlainTime.from()")}}).
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainmonthday/index.md
> +  - : Creates a new `Temporal.PlainMonthDay` object from another `Temporal.PlainMonthDay` object, an object with month and day properties, or an RFC 9557 string.
```suggestion
  - : Creates a new `Temporal.PlainMonthDay` object from another `Temporal.PlainMonthDay` object, an object with month and day properties, or an [RFC 9557](https://datatracker.ietf.org/doc/html/rfc9557) string.
```

2025-01-10 16:47 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainmonthday/index.md
> +  - : Returns a calendar-specific string representing the month of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent.
```suggestion
  - : Returns a calendar-specific string representing the month of this date. [Calendar](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal#calendars)-dependent. Usually it is `M` plus a two-digit month number. For leap months, it is the previous month's code followed by `L`. If the leap month is the first month of the year, the code is `M00L`.
```

2025-01-10 17:42 UTC, bsmth reviewed
Some general comments for comparison group

2025-01-10 17:42 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/compare/index.md
> +The **`Temporal.Instant.compare()`** static method returns a number (-1, 0, 1) indicating whether the first instant comes before, is the same as, or comes after the second instant. Equivalent to comp
Nits:

```suggestion
The **`Temporal.Instant.compare()`** static method returns a number (-1, 0, or 1) indicating whether the first instant comes before, is the same as, or comes after the second instant. The comparison is equivalent to comparing the {{jsxref("Temporal/Instant/epochNanoseconds", "epochNanoseconds")}} of the two instants.
```

2025-01-10 17:42 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/compare/index.md
> +  - : Same as `instant1`.
```suggestion
  - : A string or {{jsxref("Temporal.Instant")}} instance representing the second instant to compare. It is also converted to a `Temporal.Instant` object using the same algorithm as `instant1`.
```

2025-01-10 17:42 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/equals/index.md
> +The **`equals()`** method of {{jsxref("Temporal.Instant")}} instances returns `true` if this instant is equivalent in value to another instant (in a form convertible by {{jsxref("Temporal/Instant/fro
Do we have anything to link to from 'epoch nanoseconds'?

2025-01-10 17:42 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/compare/index.md
> +The **`Temporal.PlainDate.compare()`** static method returns a number (-1, 0, 1) indicating whether the first date comes before, is the same as, or comes after the second date. Equivalent to comparin
Same suggestion nit here, so I won't repeat after this one:

```suggestion
The **`Temporal.PlainDate.compare()`** static method returns a number (-1, 0, or 1) indicating whether the first date comes before, is the same as, or comes after the second date. The comparison is equivalent to comparing the year, month, and day fields of the underlying ISO 8601 dates.
```

2025-01-10 17:42 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/compare/index.md
> +  - : Same as `date1`.
Prefer to be a little more explicit here, I'll avoid repeating this suggestion in the others:

```suggestion
  - : A string, an object, or a {{jsxref("Temporal.PlainDate")}} instance representing the second date to compare. It is converted to a `Temporal.PlainDate` object using the same algorithm as `date1`.
```

2025-01-10 18:03 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +As an input, you may optionally include the offset and time zone identifier, in the same format as [`ZonedDateTime`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#rfc_955
Yes, must not be the literal string `Z`. I was assuming that the `Z` offset is much more commonly used than any offset string so readers should be familiar with it already, and if not you can find it on the linked `ZonedDateTime` page too.

2025-01-10 18:16 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/index.md
> +  - : Returns a positive integer representing the 1-based day index in the week of this date. Days in a week are numbered sequentially from `1` to {{jsxref("Temporal/PlainDateTime/daysInWeek", "daysI
@meyerweb General response about these: I try to avoid duplicating any explanations between `PlainDate` and `PlainDateTime`. As mentioned at the beginning of the description, you can find all informational documentation in `PlainDate`, which is why I'm purposefully omitting these from both the landing page and each subpage.

2025-01-10 19:34 UTC, bsmth reviewed
For Temporal.Now

2025-01-10 19:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/index.md
> +Then, this instant can further be interpreted in a time zone (which is the system time zone {{jsxref("Temporal/Now/timeZoneId", "Temporal.Now.timeZoneId()")}} by default) in the same fashion as {{jsx
Maybe you'd like to reword for clarity that you don't need to 'first create an instant and then interpret that in a time zone' if that makes sense:

```suggestion
An instant can be interpreted in a time zone (which is the system time zone {{jsxref("Temporal/Now/timeZoneId", "Temporal.Now.timeZoneId()")}} by default) in the same fashion as {{jsxref("Temporal/Instant/toZonedDateTimeISO", "Temporal.Instant.prototype.toZonedDateTimeISO()")}}. To get a {{jsxref("Temporal.ZonedDateTime")}} object, you can use {{jsxref("Temporal/Now/zonedDateTimeISO", "Temporal.Now.zonedDateTimeISO()")}}. You can also get different parts of the date and time, for example:

- The date using {{jsxref("Temporal/Now/plainDateISO", "Temporal.Now.plainDateISO()")}}
- The time using {{jsxref("Temporal/Now/plainTimeISO", "Temporal.Now.plainTimeISO()")}}
- The date time using {{jsxref("Temporal/Now/plainDateTimeISO", "Temporal.Now.plainDateTimeISO()")}}.
```

Feel free to reword, but I feel "Then you have XYZ … then you can" gives the impression of a sequential operation.

2025-01-10 19:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/index.md
> +For example, if the computer is set to the time zone "America/New_York", then `Temporal.Now.zonedDateTimeISO()` may return a zoned date-time like: `2021-08-01T10:40:12.345-04:00[America/New_York]`. T
Same rationale as above with "then, X":

```suggestion
For example, if the computer is set to the time zone "America/New_York", `Temporal.Now.zonedDateTimeISO()` returns a zoned date-time like: `2021-08-01T10:40:12.345-04:00[America/New_York]`. In this case, `Temporal.Now.plainTimeISO()` would have returned the time part of this zoned date-time: `10:40:12.345`. However, if you call `Temporal.Now.plainTimeISO("UTC")`, it returns the time part of the zoned date-time in the UTC time zone: `14:40:12.345`. This is especially useful for cross-system communication where the other end may be expecting the time in a different time zone.
```

2025-01-10 19:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/index.md
> +To offer protection against timing attacks and [fingerprinting](/en-US/docs/Glossary/Fingerprinting), the precision of the `Temporal.Now()` functions might get rounded depending on browser settings.
We're usually not adding the browser-specifics into prose like this, worth considering with the prefs if they should be in BCD instead, although this feels like important info to surface.

2025-01-10 19:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/timezoneid/index.md
> +The **`Temporal.Now.timeZoneId()`** static method returns a [time zone identifier](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#time_zones_and_offsets) representing the
Clarify not `"America/New_York"` as default :)

```suggestion
The **`Temporal.Now.timeZoneId()`** static method returns a [time zone identifier](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#time_zones_and_offsets) representing the system's current time zone. Most systems will return a primary time zone identifier such as `"America/New_York"`, though offset time zone identifier such as `"-04:00"` is possible too. The time zone identifier returned is the default time zone used by the other `Temporal.Now` methods.
```

2025-01-10 19:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/timezoneid/index.md
> +browser-compat: javascript.builtins.Temporal.Now.timeZoneId
Check BCD on this

2025-01-10 19:54 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/now/index.md
> +To offer protection against timing attacks and [fingerprinting](/en-US/docs/Glossary/Fingerprinting), the precision of the `Temporal.Now()` functions might get rounded depending on browser settings.
We have a section like this for every single API that deals with system time, and this section seems to have been there since around FF 80.

2025-01-10 19:54 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/now/timezoneid/index.md
> +browser-compat: javascript.builtins.Temporal.Now.timeZoneId
Already noted in the review sheet

2025-01-10 20:03 UTC, meyerweb reviewed
PlainTime, PlainYearMonth, and ZonedDateTime indexes

2025-01-10 20:12 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plaintime/index.md
> +  - : Returns `true` if this time is equivalent in value to another time (in a form convertible by {{jsxref("Temporal/PlainTime/from", "Temporal.PlainTime.from()")}}), and `false` otherwise. They are
This creates nested `code` which does not render nicely. In general I don't like links-in-code much because you can't do that in plain Markdown; it's very trivial to go from here to the `compare()` page anyway.

2025-01-10 20:40 UTC, meyerweb requested changes
Temporal index page

2025-01-10 20:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/index.md
> +JavaScript has had the {{jsxref("Date")}} object for handling date and time since its first days. However, the `Date` API is based on the poorly designed `java.util.Date` class from Java, which was a
```suggestion
JavaScript has had the {{jsxref("Date")}} object for handling date and time since its first days. However, the `Date` API is based on the poorly designed `java.util.Date` class from Java, which was replaced in the early 2010s; but, because of JavaScript's goal of backward compatibility, `Date` sticks around in the language.
```

2025-01-10 20:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/index.md
> +[Time zone](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#time_zones_and_offsets) underlies a significant number of date-related bugs. When interacting with a `Date` via
```suggestion
[Time zones](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#time_zones_and_offsets) underlie a significant number of date-related bugs. When interacting with a `Date` via the "combination of components" model, the time can only be in two time zones: UTC and local (device), and there's no way to specify an arbitrary time zone. Also lacking is the concept of "no time zone": this is known as a _calendar date_ (for dates) or _wall-clock time_ (for times), which is a time you "read off a calendar or clock". For example, if you are setting a daily wake up alarm, you will want to set it to "8:00AM" regardless of whether it is daylight saving time or not, whether you have traveled to a different time zone, etc.
```

2025-01-10 20:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/index.md
> +A second feature lacking from `Date` is the [calendar system](#calendars). Most people may be familiar with the Gregorian calendar, where there are two eras: BC and AD, there are 12 months, each mont
```suggestion
A second feature lacking from `Date` is a [calendar system](#calendars). Most people may be familiar with the Gregorian calendar, where there are two eras, BC and AD; there are 12 months; each month has a different number of days; there's a leap year every 4 years; and so on. However, some of these concepts may not apply when you are working with another calendar system, such as the Hebrew calendar, the Chinese calendar, the Japanese calendar, etc. With `Date`, you can only work with the Gregorian calendar model.
```

2025-01-10 20:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/index.md
> +  - Representing a time zone-unaware date/time (which are all prefixed with "Plain"):
```suggestion
  - Representing a time-zone-unaware date/time (which are all prefixed with "Plain"):
```

2025-01-10 20:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/index.md
> +There are three most prominent periodic events on Earth: its rotation around the sun (365.242 days for one revolution), the moon's rotation around Earth (29.5 days from new moon to new moon), and its
```suggestion
There are three prominent periodic events on Earth: its rotation around the sun (365.242 days for one revolution), the moon's rotation around the Earth (29.53 days from new moon to new moon), and its rotation around its axis (24 hours from sunrise to sunrise). Every culture has the same measure of a "day", which is 24 hours. Occasional changes such as daylight saving time are not part of the calendar, but are part of the [time zone](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal/ZonedDateTime#time_zones_and_offsets)'s information.
```

2025-01-10 20:44 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/now/index.md
> +To offer protection against timing attacks and [fingerprinting](/en-US/docs/Glossary/Fingerprinting), the precision of the `Temporal.Now()` functions might get rounded depending on browser settings.
OK, not blocking, something for us (me?) to note for a follow-up

2025-01-13 10:35 UTC, chrisdavidmills commented on files/en-us/web/javascript/guide/numbers_and_dates/index.md
> +> The `Date` object is now considered legacy and should be avoided in new code. We will update this section with modern alternatives soon.
I appreciate that, but it is always better if possible to write such vagaries in a way that doesn't sound like it is promising something quickly, and really could be any time. You know, in case life gets in the way and it doesn't end up being written "soon" ;-)

That said, I don't feel that strongly about it.

2025-01-13 10:36 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/index.md
> +- {{jsxref("Temporal")}}
Ah, of course. Sorry, I am still getting used to what BCD does automatically ;-)

2025-01-13 10:36 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/datetimeformat/index.md
> +- `formatMatcher`
Right, OK.

2025-01-13 10:37 UTC, chrisdavidmills commented on files/en-us/web/javascript/reference/global_objects/intl/index.md
> -- {{jsxref("Date.prototype.toLocaleTimeString()")}}
Makes sense, thanks.

2025-01-13 10:38 UTC, chrisdavidmills approved these changes
Giving my approval, so I don't end up blocking this one later on.

2025-01-13 16:30 UTC, bsmth reviewed
One comment for Time zone & calendar group

2025-01-13 17:07 UTC, bsmth reviewed
One comment for Time components group

2025-01-13 21:02 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/minute/index.md
> +```
Made a typo above, nice catch

2025-01-13 21:06 UTC, meyerweb requested changes
Temporal.Instant constructors

2025-01-13 21:06 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/fromepochmilliseconds/index.md
> +console.log(instant.toString()); // 1970-01-01T00:00:00Z
```suggestion
console.log(instant.toString()); // 1970-01-01T00:00:00Z
const vostok1_liftoff = Temporal.Instant.fromEpochMilliseconds(-275248380000);
console.log(vostok1_liftoff.toString()); // 1961-04-12T06:07:00Z
const sts1_liftoff = Temporal.Instant.fromEpochMilliseconds(355924804000);
console.log(sts1_liftoff.toString()); // 1981-04-12T12:00:04Z

```

2025-01-13 21:48 UTC, meyerweb requested changes
Temporal.PlainDate constructors

2025-01-13 21:48 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/plaindate/index.md
> +console.log(plainDate2.month); // 5
```suggestion
console.log(plainDate2.year); // 4658
console.log(plainDate2.month); // 5
console.log(plainDate2.day); // 22
```

2025-01-13 21:48 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/from/index.md
> +    - The provided properties are insufficient to unambiguously determine a date. You usually need to provide a `year` (or `era` and `eraYear`), and a `month` (or `monthCode`), and a `day`.
```suggestion
    - The provided properties are insufficient to unambiguously determine a date. You usually need to provide a `year` (or `era` and `eraYear`), a `month` (or `monthCode`), and a `day`.
```

2025-01-13 21:48 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/from/index.md
> +    - The provided non-numerical properties are not valid, for example, if `monthCode` is never a valid month code in this calendar.
```suggestion
    - The provided non-numerical properties are not valid; for example, if `monthCode` is never a valid month code in this calendar.
```

2025-01-13 21:48 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/from/index.md
> +console.log(d3.toString()); // "-000616-08-12[u-ca=chinese]"
This confused me, perhaps because I don’t understand what `.toString()` gets to construct its string.  Is this showing me the ISO 8601 date and then telling me the date was constructed using the Chinese calendar?  That’s my guess, given the result of the Meiji example, but I still feel hesitant about it.  Some clarification in the prose up the page would be welcome.

2025-01-13 21:48 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindate/with/index.md
> +console.log(newDate.toString()); // 2021-07-31
```suggestion
console.log(newDate.toString()); // 2021-07-31
const nextDecade = date.with({ year: date.year + 10 });
console.log(nextDecade.toString()); // 2031-07-06
```

2025-01-13 22:43 UTC, meyerweb requested changes
Temporal.PlainDateTime and Temporal.PlainTime constructors

2025-01-13 22:43 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/with/index.md
> +    - The provided non-numerical properties are not valid, for example, if `monthCode` is never a valid month code in this calendar.
```suggestion
    - The provided non-numerical properties are not valid; for example, if `monthCode` is never a valid month code in this calendar.
```

2025-01-13 22:43 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/with/index.md
> +console.log(newDT.toString()); // "2021-07-01T13:34:56"
```suggestion
console.log(newDT.toString()); // "2021-07-01T13:34:56"
const newDT2 = dt.with({month: 2, day: 22, millisecond: 222});
console.log(newDT2.toString()); // "2021-02-22T13:34:56.222"
const nextDecade = dt.with({year: dt.year + 10});
console.log(nextDecade.toString()); // "2031-07-01T13:34:56"
```

2025-01-14 12:13 UTC, bsmth reviewed
Few comments for Arithmetic group

2025-01-14 12:13 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/since/index.md
> +const now = Temporal.now.instant();
Aside from `Temporal.now` -> `Temporal.Now`, this example need another look, because of rounding, you get `missing "year" calendar field` with

```js
const lastUpdated = Temporal.Instant.fromEpochMilliseconds(1735235418000);
const now = Temporal.Now.instant();
const duration = now.since(lastUpdated, { smallestUnit: "minute" });
const roundedDuration = duration.round({ largestUnit: "day", relativeTo: lastUpdated }); 
                                ^
```

2025-01-14 14:26 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/since/index.md
> +// Expected output: "[number] months, [number] days since last billing"
No we aren't. `toLocaleString` is a shortcut that avoids calling `Intl.DurationFormat`. However, Firefox does not implement this yet. If you want to test `Duration.toLocaleString`, try it on https://tc39.es/proposal-temporal/docs in another browser instead.

2025-01-14 14:40 UTC, meyerweb requested changes
Temporal.PlainMonthDay and Temporal.PlainYearMonth constructors

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainmonthday/from/index.md
> +        - : Corresponds to the {{jsxref("Temporal/PlainMonthDay/monthCode", "monthCode")}} property. If both `month` and `monthCode` are provided, they must be consistent.
Should this say “Optional if a `month` value has been supplied; otherwise, required.” or words to that effect?

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainmonthday/with/index.md
> +There's no obvious way to create a new `Temporal.PlainMonthDay` object with a different calendar that represents the same month-day, so to replace its `calendarId` property, you need to convert it to
```suggestion
There's no obvious way to create a new `Temporal.PlainMonthDay` object with a different calendar that represents the same month-day, so to replace its `calendarId` property, you need to convert it to a {{jsxref("Temporal.PlainDate")}} object using {{jsxref("Temporal/PlainMonthDay/toPlainDate", "toPlainDate()")}}, change the calendar, and then convert it back.
```

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/plainyearmonth/index.md
> +A new `Temporal.PlainYearMonth` object, representing the year-month of the date specified by `year`, `month`, `referenceDay` (in the ISO calendar), interpreted in the calendar system specified by `ca
```suggestion
A new `Temporal.PlainYearMonth` object, representing the year-month of the date specified by `year`, `month`, and `referenceDay` (in the ISO calendar), interpreted in the calendar system specified by `calendar`.
```

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/plainyearmonth/index.md
> +The same ISO year-month can represent different months on different days with non-ISO calendars. Therefore, you virtually always want to specify a `referenceDay` when using a non-ISO calendar.
I feel like at least a sentence explaining how/why this can be so is warranted.  It’s hard for my Gregorian head to wrap around the idea of a month being represented by “different months on different days”.  Like, I don’t even know how to parse that part of the sentence in a way that makes any kind of sense.

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/from/index.md
> +Each `PlainYearMonth` stores a whole ISO 8601 date internally, which has the same year-month in the target calendar as what's exposed. The reference day is visible when stringifying with {{jsxref("Te
```suggestion
Each `PlainYearMonth` stores a whole ISO 8601 date internally, which has the same year-month in the target calendar as what's exposed. The reference day is visible when stringifying with {{jsxref("Temporal/PlainYearMonth/toString", "toString()")}}, which outputs an ISO date. The reference day is chosen arbitrarily but consistently; that is, every `(year, month)` pair always maps to the same ISO reference day. It does not use the day provided in the input. Instead, the reference day is always chosen to be the first valid day of the month.
```

2025-01-14 14:40 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/with/index.md
> +There's no obvious way to create a new `Temporal.PlainYearMonth` object with a different calendar that represents the same year-month, so to replace its `calendarId` property, you need to convert it
```suggestion
There's no obvious way to create a new `Temporal.PlainYearMonth` object that represents the same year-month in a different calendar, so to replace its `calendarId` property, you need to convert it to a {{jsxref("Temporal.PlainDate")}} object using {{jsxref("Temporal/PlainYearMonth/toPlainDate", "toPlainDate()")}}, change the calendar, and then convert it back.
```

2025-01-14 15:17 UTC, meyerweb requested changes
Temporal.ZonedDateTime constructors

2025-01-14 15:17 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/with/index.md
> +console.log(newDT.toString()); // "2021-07-01T13:34:56-04:00[America/New_York]"
```suggestion
const newZDT = zdt.with({ hour: 13 });
console.log(newZDT.toString()); // "2021-07-01T13:34:56-04:00[America/New_York]"
```

2025-01-14 15:17 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/with/index.md
> +zdt.with({ month: 12, offset: "-05:00" }, { offset: "reject" }); // OK
```suggestion
zdt.with({ month: 12, offset: "-05:00" }, { offset: "reject" }).toString(); // "2021-12-01T12:00:00-05:00[America/New_York]"
```

2025-01-14 15:17 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/withcalendar/index.md
> +console.log(newDT.toLocaleString("en-US", { calendar: "islamic" }));
```suggestion
const zdt = Temporal.ZonedDateTime.from("2021-07-01T12:34:56[America/New_York]");
const newZDT = zdt.withCalendar("islamic");
console.log(newZDT.toLocaleString("en-US", { calendar: "islamic" }));
```

2025-01-14 15:17 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/withcalendar/index.md
> +console.log(newDT.toLocaleString("en-US", { calendar: "islamic" }));
These changes aren’t strictly necessary as the code worked without the changes, but it feels more consistent with other ZonedDateTime constructor pages using `zdt` _et al._ instead of plain `dt`.

2025-01-14 15:17 UTC, meyerweb commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/withplaintime/index.md
> +This method will replace all time properties, defaulting to `0` if unspecified. If you only want to replace some of the time properties, use the {{jsxref("Temporal/ZonedDateTime/with", "with()")}} me
```suggestion
This method will replace all time properties, defaulting to `0` where properties are unspecified. If you only want to replace some of the time properties, use the {{jsxref("Temporal/ZonedDateTime/with", "with()")}} method instead.
```

2025-01-14 16:24 UTC, bsmth reviewed
Only one comment for Calendar: month-related group

2025-01-14 16:24 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/monthcode/index.md
> +The set accessor of `monthCode` is `undefined`. You cannot change this property directly. Use the {{jsxref("Temporal/PlainYearMonth/with", "with()")}} method to create a new `Temporal.PlainYearMonth`
General comment about the `monthCode` pages, I know we're trying to avoid duplication, but the explanation about the format this returns might be useful in these pages. Specifically:

```md
Usually it is `M` plus a two-digit month number.
For leap months, it is the previous month's code followed by `L` (even if it's conceptually a derivative of the following month; for example, in the Hebrew calendar, Adar I has code `M05L` but Adar II has code `M06`).
If the leap month is the first month of the year, the code is `M00L`.
```

2025-01-14 16:35 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/monthcode/index.md
> +The set accessor of `monthCode` is `undefined`. You cannot change this property directly. Use the {{jsxref("Temporal/PlainYearMonth/with", "with()")}} method to create a new `Temporal.PlainYearMonth`
I personally disagree: I don't see this as a useful detail. You should treat `monthCode` as an opaque identifier for comparison and identification, and not assume its structure in any case.

2025-01-14 19:06 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/plainmonthday/plainmonthday/index.md
> +The same ISO month-day can represent different dates in different years with non-ISO calendars. Therefore, you virtually always want to specify a `referenceYear` when using a non-ISO calendar.
```suggestion
The same ISO month-day can represent different dates in different years with non-ISO calendars. For example, the days 2021-07-01 and 2022-07-01 may fall on different month-days in a non-Gregorian calendar, and just specifying "07-01" is insufficient to unambiguously determine a month-day in the target calendar. Therefore, you virtually always want to specify a `referenceYear` when using a non-ISO calendar.
```

2025-01-15 17:37 UTC, bsmth reviewed
Couple of comments for Conversion group, nearly there

2025-01-15 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/tozoneddatetime/index.md
> +// This wall-clock time never existed. So we need to choose from 01:05:00-05:00 or 03:05:00-04:00.
Do you want to mention "due to DST changeover" in the comment?

2025-01-15 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plaindatetime/tozoneddatetime/index.md
> +// This wall-clock time never existed. So we need to choose from 01:05:00-05:00 or 03:05:00-04:00.
I find the interleaving ambiguous and not-existing examples is a little hard to follow, but leave if you prefer it.

2025-01-15 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/toplaindatetime/index.md
> +> After a `Temporal.ZonedDateTime` is converted to `Temporal.PlainDateTime`, it will no longer be aware of its time zone. This means that subsequent operations like arithmetic or with will not adjust
Minor one if you like:

```suggestion
> After a `Temporal.ZonedDateTime` is converted to `Temporal.PlainDateTime`, it's no longer time zone aware. Subsequent operations like arithmetic or `with` operations will not adjust for DST and may not yield the same results as equivalent operations with `Temporal.ZonedDateTime`. However, unless you perform those operations across a time zone offset transition, it's impossible to notice the difference. Be very careful when performing this conversion because subsequent results are probably correct most of the time, but may be incorrect across time zone transitions like when DST starts or ends.
```

2025-01-15 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/toplaintime/index.md
> +
Is the warning like on `toplaindatetime` also useful regarding accuracy of subsequent calculations across DST boundaries, etc?

2025-01-16 12:47 UTC, bsmth reviewed
Minor comments in Serialization group

2025-01-16 12:47 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/tojson/index.md
> +const ymStr = date.toJSON(); // '2021-08'
```suggestion
const ymStr = ym.toJSON(); // '2021-08'
```

2025-01-16 14:38 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/tolocalestring/index.md
> +Every time `toLocaleString` is called, it has to perform a search in a big database of localization strings, which is potentially inefficient. When the method is called many times with the same argum
@bsmth Do you feel strongly about it? Because this same paragraph is on every `toLocaleString` page so I'd rather not change it. "Big database" is used to emphasize the speed differences.

2025-01-16 15:34 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/tolocalestring/index.md
> +Every time `toLocaleString` is called, it has to perform a search in a big database of localization strings, which is potentially inefficient. When the method is called many times with the same argum
>Do you feel strongly about it?

I don't mind it, but I can see people asking what "big" means. I'll leave it as your call.

2025-01-16 17:37 UTC, bsmth reviewed
Last ones on Temporal.Duration

2025-01-16 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/duration/days/index.md
> +console.log(d4Balanced.days); // 0
For these examples where we have `d4Balanced`, I feel like it might be good to show why we get `0`:

```js
console.log(d4Balanced.days); // 0
console.log(d4Balanced.weeks); // 1
```

2025-01-16 17:37 UTC, bsmth commented on files/en-us/web/javascript/reference/global_objects/temporal/duration/years/index.md
> +console.log(d4.years); // 12
```suggestion
console.log(d3.years); // 1
console.log(d4.years); // 0
```

2025-01-16 17:39 UTC, bsmth approved these changes
Amazing work. Some comments for you to check, but I'm more than happy to leave a +1, well done 👏🏻

2025-01-16 19:13 UTC, Josh-Cena commented on files/en-us/web/javascript/reference/global_objects/temporal/instant/tolocalestring/index.md
> +Every time `toLocaleString` is called, it has to perform a search in a big database of localization strings, which is potentially inefficient. When the method is called many times with the same argum
This note has been there for quite a while on other `toLocaleString` pages, and it was added in response to someone being confused about the performance benefits of `Intl` objects, so I presume this is good enough.

2025-01-16 20:01 UTC, Josh-Cena commented
I plan to merge it some time next week, because I currently have another PR that depends on the Intl changes, and I also need to work on the guide. People are encouraged to leave comments as early as possible, but we can definitely accept follow-up PRs, preferably for bug fixes, especially from the champion group.

2025-01-20 17:29 UTC, printfn commented on files/en-us/web/javascript/reference/global_objects/date/totemporalinstant/index.md
I wonder if it might be good to mention that this function will throw a RangeError if the date is invalid (has a value of NaN). For example `new Date('foo').toTemporalInstant()`.

2025-01-20 17:38 UTC, Josh-Cena commented
@printfn Done, thanks for pointing out! I plan to merge it today, so if you have or don't have more comments please feel free to send them.

2025-01-20 22:27 UTC, Josh-Cena commented
I'm going to go ahead and merge it. Thanks everyone! I understand that this is not the final version, and we will surely continue to iterate on it.

2025-01-20 22:28 UTC, merged

2025-01-22 04:38 UTC, justingrant commented
Thanks so much @Josh-Cena for making this happen!

Also grateful for @meyerweb for all the work you did on the docs previously, and in helping to review this PR. 

Developers worldwide are going to be thankful. 🙏

2025-03-23 18:41 UTC, Eroiica commented
Reasoned about Vercel and xAI partnership for 18 seconds
Here's a summary of the key points from the announcement:

Vercel and xAI Partnership
Zero-Frictions AI for Developers:
Vercel and xAI are partnering to simplify AI integration in development projects.

Grok Models on Vercel:
xAI's Grok models are now available directly through Vercel, making it easier to implement AI features.

Exclusive xAI Free Tier:
Developers can take advantage of an exclusive free tier—no extra sign-up required.

Integrated Billing:
You pay for what you use through your existing Vercel account, streamlining the process.

Simplified Configuration:
Enjoy zero-configuration requirements for authentication, API keys, and environment variables, reducing setup complexity.

Additional Announcements from Vercel
Vercel Ship Event:
The event is scheduled for June 25, with options to attend in New York City or stream online. Early sign-ups offer the best ticket prices and workshop access.

Full-Stack Integrations:
Vercel is also promoting full-stack application development via v0 integrations available on the Vercel Marketplace. These integrations include:

Adding storage with services like Upstash, Supabase, or Neon.

Seamless database setup without a new account.

Generating and executing SQL commands for database interactions.

This collaboration is designed to reduce the friction often associated with integrating AI, making it a more accessible tool for developers building modern, full-stack applications. Do you need more details on any specific part of the announcement?





You said:
Reference for stage 3 temporal #37344
 Merged
Josh-Cena merged 46 commits into mdn:main from Josh-Cena:temporal  on Jan 20
 Merged
Reference for stage 3 temporal
#37344
Josh-Cena merged 46 commits into mdn:main from Josh-Cena:temporal  on Jan 20
+17,552 −105 
 Conversation 247
 Commits 46
 Checks 9
 Files changed 282
Conversation
Josh-Cena
Member
Josh-Cena commented on Dec 23, 2024 • 
#27745

Far from ready for review, and I'll work on this alone for a while

It is now ready for review! It's extremely big but I think it's more worthwhile getting it in as a whole. Im already leaving the guide to a second PR.

For reviewers (both editorial and technical): I've made a spreadsheet here: https://docs.google.com/spreadsheets/d/1RrRHL0m08R4V4WtuWBbSWr9a1gO4RiIaH42WrPv_Uhs/edit Welcoming anyone on the team for editorial reviews! Technical review from the champion group is greatly appreciated too. It seems we have roughly 4 weeks to make this happen.

@Josh-Cena
Reference for stage 3 temporal
27a3784
@github-actions github-actions bot added Content:JS size/xl labels on Dec 23, 2024
@github-actionsGitHub Actions
Contributor
github-actions bot commented on Dec 23, 2024 • 
Preview URLs (282 pages)
External URLs (41)
@Josh-Cena
More description
a477fa3
@Josh-Cena Josh-Cena mentioned this pull request on Dec 25, 2024
What's the plan to get Temporal docs into MDN? tc39/proposal-temporal#1449
Open
Josh-Cena added 16 commits 3 months ago
@Josh-Cena
Duration docs
9f50952
@Josh-Cena
Fix link
bd0796c
@Josh-Cena
Complete Duration docs
fbd0601
@Josh-Cena
Instant docs
6ab2afd
@Josh-Cena
Now docs
ef79211
@Josh-Cena
TZ and calendar docs
02295b7
@Josh-Cena
PlainDate docs
0936403
@Josh-Cena
Change ISO format description
889b358
@Josh-Cena
ZonedDateTime-specific stuff docs
7ca2b31
@Josh-Cena
PlainMonthDay docs, copy date-related fields to PlainDateTime
7d9cdfe
@Josh-Cena
PlainYearMonth docs
a0ab015
@Josh-Cena
PlainTime docs
f4342cf
@Josh-Cena
Intl docs
4974d24
@Josh-Cena
PlainDateTime docs
0a172b6
@Josh-Cena
ZonedDateTime docs, easy part
ac18c5f
@Josh-Cena
ZonedDateTime docs... and that shall be all
ac298ef
@Josh-Cena Josh-Cena mentioned this pull request on Jan 3
feat(sidebars/jsref): support temporal mdn/rari#72
 Merged
@Josh-Cena
Simplifications and fixes
f385d12
@Josh-Cena Josh-Cena force-pushed the temporal branch from 7daf469 to f385d12 
2 months ago
@Josh-Cena Josh-Cena marked this pull request as ready for review 2 months ago
@Josh-Cena Josh-Cena requested a review from a team as a code owner 2 months ago
@Josh-Cena Josh-Cena requested review from chrisdavidmills and hamishwillee and removed request for a team 2 months ago
59 hidden items
Load more…
@github-actions github-actions bot removed the merge conflicts 🚧 label on Jan 14
Josh-Cena
Josh-Cena commented on Jan 14
.../en-us/web/javascript/reference/global_objects/temporal/plainmonthday/plainmonthday/index.md
Outdated
Josh-Cena added 3 commits 2 months ago
@Josh-Cena
Update index.md
bf72961
@Josh-Cena
Update index.md
0ca21c0
@Josh-Cena
Update index.md
25e1bb1
bsmth
bsmth reviewed on Jan 15
Member
bsmth left a comment
Couple of comments for Conversion group, nearly there

...s/en-us/web/javascript/reference/global_objects/temporal/instant/tozoneddatetimeiso/index.md
Outdated
...n-us/web/javascript/reference/global_objects/temporal/plaindatetime/tozoneddatetime/index.md
Outdated
...n-us/web/javascript/reference/global_objects/temporal/zoneddatetime/toplaindatetime/index.md
Outdated
files/en-us/web/javascript/reference/global_objects/temporal/zoneddatetime/toplaintime/index.md
@github-actions github-actions bot added the merge conflicts 🚧 label on Jan 15
@github-actionsGitHub Actions
Contributor
github-actions bot commented on Jan 15
This pull request has merge conflicts that must be resolved before it can be merged.

@Josh-Cena
Merge branch 'main' into temporal
aa9c790
@github-actions github-actions bot removed the merge conflicts 🚧 label on Jan 15
@Josh-Cena
Reviews, some (?) conversion methods
4b68919
bsmth
bsmth reviewed on Jan 16
Member
bsmth left a comment
Minor comments in Serialization group

files/en-us/web/javascript/reference/global_objects/temporal/instant/tolocalestring/index.md
files/en-us/web/javascript/reference/global_objects/temporal/instant/valueof/index.md
files/en-us/web/javascript/reference/global_objects/temporal/plainyearmonth/tojson/index.md
Outdated
bsmth
bsmth reviewed on Jan 16
Member
bsmth left a comment
Last ones on Temporal.Duration

files/en-us/web/javascript/reference/global_objects/temporal/duration/compare/index.md
Outdated
files/en-us/web/javascript/reference/global_objects/temporal/duration/days/index.md
files/en-us/web/javascript/reference/global_objects/temporal/duration/years/index.md
Outdated
bsmth
bsmth approved these changes on Jan 16
Member
bsmth left a comment
Amazing work. Some comments for you to check, but I'm more than happy to leave a +1, well done 👏🏻

@Josh-Cena
Last group of reviews
1a21ed6
@Josh-Cena
Member
Author
Josh-Cena commented on Jan 16
I plan to merge it some time next week, because I currently have another PR that depends on the Intl changes, and I also need to work on the guide. People are encouraged to leave comments as early as possible, but we can definitely accept follow-up PRs, preferably for bug fixes, especially from the champion group.

This was referenced on Jan 20
Add missing Temporal spec_url entries mdn/browser-compat-data#25714
 Merged
Rename Temporal timeZoneID -> timeZoneId, typo mdn/browser-compat-data#25715
 Merged
Add Date.toTemporalInstant mdn/browser-compat-data#25716
 Merged
printfn
printfn reviewed on Jan 20
files/en-us/web/javascript/reference/global_objects/date/totemporalinstant/index.md
@Josh-Cena
Mention toTemporalInstant RangeError
3fd90b9
@Josh-Cena
Member
Author
Josh-Cena commented on Jan 20
@printfn Done, thanks for pointing out! I plan to merge it today, so if you have or don't have more comments please feel free to send them.

@Josh-Cena Josh-Cena changed the title [new-ci] Reference for stage 3 temporal Reference for stage 3 temporal on Jan 20
@Josh-Cena
Member
Author
Josh-Cena commented on Jan 20
I'm going to go ahead and merge it. Thanks everyone! I understand that this is not the final version, and we will surely continue to iterate on it.

@Josh-Cena Josh-Cena merged commit a4e9bce into mdn:main on Jan 20
9 checks passed
@Josh-Cena Josh-Cena deleted the temporal bra [...]