Adds PerformanceObserver.supportedEntryTypes
mdn/content pull request #3743
Opened 2021-04-01 10:01 UTC by rachelandrew

Fixes: #2667 

Adds a page for the `supportedEntryTypes` property and the link to it from the main `PerformanceObserver` page.

Reviewer @jpmedley

2021-04-01 16:37 UTC, jpmedley requested changes
This looks good. I have a question about the example.

2021-04-01 16:37 UTC, jpmedley commented on files/en-us/web/api/performanceobserver/supportedentrytypes/index.html
> +<h2 id="Example">Example</h2>
Here's a different example from the spec. Do you think this would be better?

https://w3c.github.io/performance-timeline/#example-2

2021-04-02 09:35 UTC, rachelandrew commented on files/en-us/web/api/performanceobserver/supportedentrytypes/index.html
> +<h2 id="Example">Example</h2>
I'll add it as well, I think it's actually quite a useful thing (if you want to use this) to just be able to quickly check in the console what is supported. And, I think that was to some extent why the issue was raised because people were asking for support info on MDN. So I'd like to keep the one-liner.

2021-04-02 14:43 UTC, jpmedley approved these changes

2021-04-02 14:43 UTC, merged