Certain HTML elements default to border-box behavior
mdn/content pull request #3795
Opened 2021-04-03 08:13 UTC by x86chi

I had reference below CSS W3C specification:

> Note: Certain HTML elements, such as button, default to border-box behavior. See HTML for details on which elements have this behavior.
> 
> [`border-box`, `box-sizing` property — CSS Box Sizing Module Level 3](https://www.w3.org/TR/css-sizing-3/#valdef-box-sizing-border-box)

You can find a list of "Certain HTML elements" through to search "box-sizing: border-box" text in https://html.spec.whatwg.org/

2021-04-05 03:09 UTC, x86chi commented on files/en-us/web/css/box-sizing/index.html
> +   <p><strong>Note:</strong> Certain HTML elements, such as <code>&lt;button&gt;</code>, default to <code>border-box</code> behavior.</p>
```suggestion
   <p><strong>Note:</strong> Certain HTML elements, <code>&lt;table&gt;</code> and Form controls default to <code>border-box</code> behavior. See <a href="https://html.spec.whatwg.org/multipage/rendering.html#tables-2">WHATWG HTML</a> for details on which is Form controls and have this behavior.</p>
```

Would this be a more explicit?

2021-04-07 19:05 UTC, ericwbailey requested changes

2021-04-07 19:05 UTC, ericwbailey commented on files/en-us/web/css/box-sizing/index.html
> +   <p><strong>Note:</strong> Certain HTML elements, such as <code>&lt;button&gt;</code>, default to <code>border-box</code> behavior.</p>
I like this. Can we also move it outside of the `ul` to line 39?

2021-04-08 20:45 UTC, ericwbailey approved these changes
Lovely. Thank you!

2021-04-08 20:45 UTC, merged