fix: flaws in web/api/n*
mdn/content pull request #3822
Opened 2021-04-04 17:44 UTC by nschonni

2021-04-05 15:06 UTC, jpmedley requested changes
@henrik Thank you for your help. Please fix the marked items.

2021-04-05 15:06 UTC, jpmedley commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
We're trying to move away from identifiers like `HTMLOrForeignElement` that can't actualy appear in a script. Since the existing link redirects, leaving this as is, will save us from needing to fix it later.

2021-04-05 15:11 UTC, nschonni commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
Right now the flaws fixing does change it, which is why it's included here

2021-04-05 15:17 UTC, jpmedley commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
I'm not following your reasoning.

2021-04-05 15:23 UTC, nschonni commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
I know there is a discussion about "unmixing" those things, but this PR is built on the current flaw fixing. If I undo it, it will just get flagged again till the work on unmixing is done, and doesn't need to block this PR

2021-04-05 19:24 UTC, henrik commented
@jpmedley Assume this was a mismention :) No worries.

2021-04-08 14:20 UTC, jpmedley commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
We're not expecting all flagged issues to be cleared at this stage. I'll merge PR whether this is flagged or not. Please commit the change.

cc: @sideshowbarker

2021-04-09 06:28 UTC, sideshowbarker commented on files/en-us/web/api/node/setuserdata/index.html
> +    longer available from Web content. {{domxref("HTMLOrForeignElement.dataset")}} or <a
I agree we should change it to `HTMLElement.dataset` — which I guess means ignoring/rejecting the current flaw-fixer suggestion. This seems like a case where the flaw fixer should itself be fixed to not report this as a flaw — that is, the flaw fixer isn’t doing what we actually want it to doing in this case, but is instead suggesting a bad/undesirable change.

2021-05-13 14:08 UTC, closed without merging