[Markdown] First draft of Markdown spec
mdn/content pull request #3950
Opened 2021-04-09 00:01 UTC by wbamberg

Here's a first draft of a spec for writing Markdown in MDN.

The idea is that this specifies a baseline (GFM) and we then add extra bits for anything else we need to support. Adding these extra bits would be separate PRs which would close separate issues, like https://github.com/mdn/content/issues/3483. 

However, I included a resolution for https://github.com/mdn/content/issues/3512 to show what it would look like, and because this seemed like it could be resolved in the way I've written it up here.

So anyway, I'm interested in things like:

* whether we think this is going to be adequate in terms of the guidance it gives to writers and implementors.
* whether this general approach of landing a draft spec full of holes and then filling the holes in subsequent PRs sounds like a good one (I think it is, since it gives us a place to work these things out).
* is the extra stuff highlighting aspects of GFM useful? We could omit it and just ask people to read the spec but it feels like helpful background for some of the later sections.
* anything else?

There is also a need for some other spec about how we manage the conversion - how we get from the HTML we have to this Markdown. But since that's more of a project doc that has a limited shelf-life, it seems better to keep is separate. Then this doc can just talk about how things will be in the end state.

2021-04-09 00:34 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>Writers will be able to include KumaScript macro calls in prose content:</p>
Might be worth saying that this can be both as a block or inline (otherwise you might assume from example that the macro must be on its own line).

2021-04-09 00:38 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>In GFM (but not CommonMark) there is a syntax for tables: <a href="https://github.github.com/gfm/#tables-extension-">https://github.github.com/gfm/#tables-extension-</a>. We will make use of this
FWIW  I have never seen a great markdown syntax for tables, in particular tables that support merging adjacent cells. The solution has always been to allow HTML for more complicated tables.

2021-04-09 00:44 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +  <li>GFM won't parse GFM block elements in table cells.</li>
But they will  parse html in GFM table cells .... though this sux because you have to have the whole table on one line.

2021-04-09 00:46 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +  <li>GFM won't parse GFM block elements in table cells.</li>
You can't apply CSS styling in markdown on a per-table basis

2021-04-09 00:48 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +
FYI only, the "standard" form for a table in markdown (as shown above) _looks_ like a table. This is cool until you have to write one, or modify the content in any column. 

There is a simpler syntax which I usually prefer to use because you don't, as an author, have to think too much about the layout at authoring time.
```
Header 1 | Header2
--- | ---:
I'm a test | yes i am
`inline` is ok | * lists aren't
```

Which renders as

Header 1 | Header2
--- | ---:
I'm a test | yes i am
`inline` is ok | * lists aren't

Note:
- You must have the header
- Colon can be used in the line after header to indicate alignment of the column text

2021-04-09 00:56 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<h3>KumaScript</h3>
Images heading?

2021-04-09 01:15 UTC, hamishwillee commented
@wbamberg My 2 bits. Yes to all your questions, at least for now.

This reads as what it is - a spec with some reasoning and justification and comparison. That's good for first author and implementer audience. Later on we should simplify it down to a cheatsheet - e.g. like https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet along with a list of things that we know can't be ported using markdown in our system (I'm thinking some tables - we may need to think up some way to apply per-table styling).

2021-04-09 01:34 UTC, sideshowbarker commented
> * whether we think this is going to be adequate in terms of the guidance it gives to writers and implementors.

Yes

> * whether this general approach of landing a draft spec full of holes and then filling the holes in subsequent PRs sounds like a good one (I think it is, since it gives us a place to work these things out).

I agree it’s a good approach. In general with pretty much everything we do, I prefer the approach of landing something and than iterating on it over time — rather than blocking on trying to make it problem-free from the get-go.

> * is the extra stuff highlighting aspects of GFM useful? We could omit it and just ask people to read the spec but it feels like helpful background for some of the later sections.

I think it’s useful to have the info summarized at point-of-use. 

> * anything else?

I’d prefer to have the entire doc written in markdown rather than HTML :)

2021-04-09 01:37 UTC, wbamberg commented
> I’d prefer to have the entire doc written in markdown rather than HTML :)

The irony of laboriously writing out, in HTML, a document about using Markdown, was not lost on me :)

2021-04-09 03:16 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>In GFM (but not CommonMark) there is a syntax for tables: <a href="https://github.github.com/gfm/#tables-extension-">https://github.github.com/gfm/#tables-extension-</a>. We will make use of this
Yeah, I agree. I will have an issue for tables, and I think it's likely we'll end up deciding to use HTML.

2021-04-09 03:17 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>Writers will be able to include KumaScript macro calls in prose content:</p>
I thought of this but then struggled to come up with an inline macro other than *xref, and I expect these to disappear eventually. I guess I could have {{optional_inline}}.

2021-04-09 03:35 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>In GFM (but not CommonMark) there is a syntax for tables: <a href="https://github.github.com/gfm/#tables-extension-">https://github.github.com/gfm/#tables-extension-</a>. We will make use of this
IFF we want to use markdown for more tables we could invent a syntax to apply a style to a markdown block. This would allow us to use markdown for a bigger number of tables - ie.  with basic styling like "hide the header" and "add a header column". I've seen this approach in reStructured text, but not in markdown systems.

2021-04-09 11:09 UTC, chrisdavidmills requested changes
Nice work @wbamberg ! I've left a few comments for you, but nothing major.

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<h3>Markdown in HTML blocks</h3>
This implies we'll be regularly including HTML blocks inside MDN markdown content, whereas I thought we were trying to minimize this as much as possible? I don't really get the point of this section, and why we need to include the `<div>` in the first place.

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>In GFM (but not CommonMark) there is a syntax for tables: <a href="https://github.github.com/gfm/#tables-extension-">https://github.github.com/gfm/#tables-extension-</a>. We will make use of this
I think I agree with this too. markdown table syntax is really horrible, and I think we'll need to resort to HTML here.

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +  <p> The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag.</p>
It would be nice to include a real example of a code fence being used on a simple code example, just so people definitely know what we mean.

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +</pre>
I suppose this is the furthest we need to go for now, as we haven't really many other decisions yet as to what other terms we will include in the info string. In which case this is fine.

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>This last means that if you write:</p>
word missing from this sentence?

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +</pre>
Ah...I just saw the other stuff on extensions below. Seems weird that the bit you include here is the only part specified in GFM...!

2021-04-09 11:09 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<ul>
See https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#code_syntax_highlighting for a more conclusive list

2021-04-09 19:07 UTC, jpmedley commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<h3>Markdown in HTML blocks</h3>
During the transition to markdown, mixing might be a useful allowance. Though, I would call it out as something that is a temporary allowance.

2021-04-09 19:07 UTC, jpmedley commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +Writers will use code fences for example code blocks. They will be able to specify the language of the code sample using the first word of the info string, and this will be used to provide syntax hig
```suggestion
Writers will use code fences for example code blocks. They must specify the language of the code sample using the first word of the info string, and this will be used to provide syntax highlighting for the block. The following words will be supported:
```

2021-04-09 19:07 UTC, jpmedley commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +Writers will use code fences for example code blocks. They will be able to specify the language of the code sample using the first word of the info string, and this will be used to provide syntax hig
so that we can apply language-specific formatting.

2021-04-09 19:07 UTC, jpmedley commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<p>Writers will be able to include KumaScript macro calls in prose content:</p>
What about {{readonlyinline}}?

2021-04-09 21:50 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +  <li>GFM won't parse GFM block elements in table cells.</li>
I didn't call this out here because that's true of all elements in GFM, and is not specific to tables.

2021-04-09 21:51 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<h3>KumaScript</h3>
Sorry, I don't understand this comment.

2021-04-09 22:37 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<h3>Markdown in HTML blocks</h3>
OK, I can remove this.

2021-04-09 22:38 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +</pre>
> Ah...I just saw the other stuff on extensions below. Seems weird that the bit you include here is the only part specified in GFM...!

Sorry, I don't understand this comment.

2021-04-09 22:38 UTC, wbamberg commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +<ul>
Thanks! I'll update this (it should be exhaustive).

2021-04-09 22:51 UTC, wbamberg commented
OK, I pushed some changes which I hope resolve the comments, and asked for clarification on a couple of comments that I didn't understand...

2021-04-12 00:21 UTC, hamishwillee commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +  <li>GFM won't parse GFM block elements in table cells.</li>
Fair enough. I only raised it because tables are the only place where I ever feel the need to add styling from whatever the site-wide setting is. So this is "where the lack matters".

2021-04-12 07:41 UTC, chrisdavidmills commented on files/en-us/mdn/contribute/markdown_in_mdn/index.html
> +</pre>
Don't worry, just ignore this bit.

2021-04-12 07:45 UTC, chrisdavidmills approved these changes
I think I'm happy with this as it stands. We can publish now and iterate later.

2021-04-12 07:45 UTC, chrisdavidmills commented
Anyone else got any other significant concerns before we merge?

2021-04-12 08:14 UTC, sideshowbarker approved these changes

2021-04-12 08:22 UTC, merged