Add an example to the SVG “transform-origin” doc
mdn/content pull request #4056
Opened 2021-04-13 06:07 UTC by sideshowbarker

This change adds an example to the SVG “transform-origin” article. The example is based on code snippets from a Stack Overflow question (with attribution give, and with a link to the CC BY-SA license).

The purpose of the example is in part to demonstrate how the same transformation that can be performed with `transform-origin` can also be performed with `transform` only (which is useful for targeting browsers that don’t have support for `transform-origin` — or that don’t support it as expected).

Related: https://github.com/mdn/browser-compat-data/issues/9834

2021-04-13 16:39 UTC, Ryuno-Ki requested changes
Some nitpicks. But the attribution part is important for Creative Commons Licenses.

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +<p>The third image image show how to do the transformation in browsers that don’t support <code>transform-origin</code> — because the code for the third image does the same transformation as the seco
```suggestion
<p>The third image image shows how to do the transformation in browsers that don't support <code>transform-origin</code> — because the code for the third image does the same transformation as the second image's <code>transform-origin</code>-based code, but by only using <code>transform</code>, without <code>transform-origin</code>.</p>
```

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +<p>(Note: These examples use a modified version of a code snippet in a Stack Overflow <a href="https://stackoverflow.com/questions/67057190/safari-doesnt-respect-transform-origin-svg-attribute">quest
https://stackoverflow.com/q/67057190 would be the permalink to the question and https://stackoverflow.com/a/67057754 for the answer (copy link target of the Share button there)

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +<p>(Note: These examples use a modified version of a code snippet in a Stack Overflow <a href="https://stackoverflow.com/questions/67057190/safari-doesnt-respect-transform-origin-svg-attribute">quest
CC BY requires attribution, i.e. a link to the profile.

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +&lt;h4&gt;Reference image&lt;/h4&gt;
This newline will create a blank line in the output. Can you move it to line 81?

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +  &lt;svg width="200" height="200" viewBox="0 0 200 200"&gt;
Do we need a XMLNS attribute here?

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +</pre>
Would it make sense to incluse those three SVGs as images?

2021-04-13 16:39 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +      max-width: 200px;
Do we have a statement regarding relative units?
(I'd need to look up our guidelines)

2021-04-13 17:19 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +  &lt;svg width="200" height="200" viewBox="0 0 200 200"&gt;
> Do we need a XMLNS attribute here?

Not for a SVG content embedded HTML, right? The HTML parser just ignores any XMLNS attributes.

2021-04-13 17:20 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +</pre>
> Would it make sense to incluse those three SVGs as images?

You mean PNG bitmap copies of them?

2021-04-13 17:21 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +      max-width: 200px;
> Do we have a statement regarding relative units?

Not that I’m aware of

2021-04-13 17:24 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +<p>(Note: These examples use a modified version of a code snippet in a Stack Overflow <a href="https://stackoverflow.com/questions/67057190/safari-doesnt-respect-transform-origin-svg-attribute">quest
> [stackoverflow.com/q/67057190](https://stackoverflow.com/q/67057190) would be the permalink to the question and [stackoverflow.com/a/67057754](https://stackoverflow.com/a/67057754) for the answer (copy link target of the Share button there)

ah OK thanks — changed to those URLs

> CC BY requires attribution, i.e. a link to the profile.

OK, added

2021-04-13 17:24 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +&lt;h4&gt;Reference image&lt;/h4&gt;
> This newline will create a blank line in the output. Can you move it to line 81?

Yup, moved

2021-04-13 18:27 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +  &lt;svg width="200" height="200" viewBox="0 0 200 200"&gt;
Hm, would need to check.
I rather thought, that these would be copy-pastable.
It doesn't hurt to have the XMLNS present, at the very least.

2021-04-13 18:28 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +</pre>
Exactly. Or SVGs as `<img />`.

2021-04-13 18:29 UTC, Ryuno-Ki commented
Let me know once this ready for re-review.

2021-05-26 07:26 UTC, sideshowbarker commented
Update: I will try to make time this week to get back to this

2021-06-03 10:40 UTC, Ryuno-Ki commented
I assume, you are still about to make changes here, since you did not re-request a review.
Am I right with this?

2021-06-03 10:44 UTC, sideshowbarker commented
> I assume, you are still about to make changes here, since you did not re-request a review.

The only remaining change I plan to make is in response to the review comment at https://github.com/mdn/content/pull/4056#discussion_r612608272. That’s the only thing blocking this.

2021-07-16 13:33 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +</pre>
I added a single PNG reference image. (A single one, since the images are all supposed to look exactly the same, if everything is working per-spec.)

2021-07-16 13:33 UTC, sideshowbarker commented
> The only remaining change I plan to make is in response to the review comment at [#4056 (comment)](https://github.com/mdn/content/pull/4056#discussion_r612608272). That’s the only thing blocking this.

I added a PNG reference image — so this should now be ready for re-review.

2021-07-17 14:05 UTC, Ryuno-Ki commented
Let me take a look then :-)

2021-07-17 15:06 UTC, Ryuno-Ki approved these changes
Looks good so far. I'm not quite sure, whether the HTML is semantically correct, but the browser can handle it from what I can tell.

2021-07-17 15:06 UTC, Ryuno-Ki commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +    &lt;svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"&gt;
I was about to ask for `<title>` elements here, but TalkBack on Android is skipping the SVGs altogether and only reads the `<figcaption>`.

2021-07-18 06:02 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +<p>(Note: These examples use a modified version of a code snippet in a Stack Overflow <a href="https://stackoverflow.com/q/67057190">question</a> from <a href="https://stackoverflow.com/users/1033939
Yep, thanks — put it into notecard formatting

2021-07-18 06:02 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +  &lt;figure&gt;
Yes — thanks for catching that. Not sure what I had been thinking…

2021-07-18 06:03 UTC, sideshowbarker commented on files/en-us/web/svg/attribute/transform-origin/index.html
> +    &lt;svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"&gt;
Yeah the existing markup seems to work as it should be with VoiceOver

2021-07-18 06:04 UTC, sideshowbarker commented
@Ryuno-Ki Thanks much for the review — gonna go ahead and merge

2021-07-18 06:05 UTC, merged