Background fetch registration
mdn/content pull request #4093
Opened 2021-04-14 09:57 UTC by rachelandrew

Here is the epic that is `BackgroundFetchRegistration`. All of the properties are very similar so if you look at a couple maybe and if there is anything you want changed I can rattle through the others if it will also be the same in those.

Reviewer: @jpmedley

2021-04-14 17:32 UTC, jpmedley requested changes

2021-04-15 12:27 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/failurereason/index.html
> +  <dd>A response had a not-ok status.</dd>
Yes, it's defined in the Fetch spec https://fetch.spec.whatwg.org/#ok-status

2021-04-15 12:37 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing a copy of the background fetch's id.</dd>
I don't think there is a standard, looks like in CSS we are most often using ID.

In the API docs there is a mix but on a quick search around, when referring to a property a lot seem to be using lowercase. Some are using lowercase when referring to the property itself then uppercase when referring more to the concept of an ID. There is certainly a lot of lowercase usage in the API docs however. So, it could go either way, I've not changed it right  now as it seems reasonably consistent with other things, but I'm fine to if you would rather I did.

2021-04-15 13:12 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
I don't understand, the first phrase is exactly that, the recordsAvailable flag is false. That's the cause of the error.

2021-04-15 13:12 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/matchall/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
as above, the first phrase is the thing that went wrong.

2021-04-15 15:23 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchregistration/index.html
> +  <dd>A {{domxref("DOMString","string")}} containing a copy of the background fetch's id.</dd>
Please change it. Two reasons. As I said, I believe "ID" to be more prevalent in N. American practice and that's consistent with MDN using U.S. English. "ID" is also more common on MDN.

```bash
jmedley-macbookpro:en-us jmedley$ grep -r -n " id " ./ | wc -l
     365
jmedley-macbookpro:en-us jmedley$ grep -r -n " ID " ./ | wc -l
     893
```

2021-04-15 15:52 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
The flag being set is a result of the error, not a cause. See [steps 10 to 13 here](https://wicg.github.io/background-fetch/#perform-a-background-fetch-algorithm). If I'm reading the algorithm correct, `backgroundfetchsuccess` also sets `recordsAvailable` to false. That implies that `match()` and `matchAll()` only work on in progress fetches. If so, that needs to be stated before we can merge these.

2021-04-15 16:02 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
It's step 1 of what happens when you call matchAll (which match()) also calls https://wicg.github.io/background-fetch/#background-fetch-registration-match-all

> "If the context object's records available flag is unset, return a promise rejected with an InvalidStateError DOMException."

I don't understand how you are getting to steps 10 - 13 from that. That's about performing a background fetch, which unsets the flag if stuff goes wrong, but that's a different part of the process I think.

2021-04-16 14:10 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
The point I'm trying to make is that to avoid or handle the error, the developer needs to know what conditions caused the flag to be set.

Re steps 10 to 13 it looks to me like:
1. I background fetch some data.
2. The fetch operation does something to the flag.
3. Later, I attempt a match.
4. The flag state requires me to get an error. 

To address this, I need to know what conditions set the flag in the first place.

2021-04-20 10:47 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code> return a promise that resolves with an <code>InvalidStateError</code> {{domxref(
The flag is initially set, it's unset if there are no records (because they have all been fetched). I have added an additional statement to that end.

2021-04-20 20:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code>, indicating that there is not a fetch in progress,  return a promise that resolv
```suggestion
  <dd>A {{domxref("DOMException")}} indicating that you called `match()` when there are no fetches in progress. You can potentially avoid this error by checking {{domxref("BackgroundFetchRegistration.recordsAvailable")}}, which will be false when no fetches are in progress.</dd>
```

2021-04-20 20:51 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchregistration/match/index.html
> +  <dd>If the {{domxref("BackgroundFetchRegistration.recordsAvailable","recordsAvailable")}} flag is <code>false</code>, indicating that there is not a fetch in progress,  return a promise that resolv
Isn't the ultimate cause of the error the result of calling `match()` when there are no fetches in progress? Knowing that this is related to `recordsAvailable` isn't something I need to know in this context because I encounter the error in the `catch()` clause of the `match() method's returned promise. I really do not see the value of leading with the flag in this description.

2021-04-22 16:18 UTC, jpmedley approved these changes

2021-04-22 16:18 UTC, merged