an explainer for the demo
mdn/content pull request #4096
Opened 2021-04-14 10:42 UTC by rachelandrew

Fixes #4062 

Adds an explanation of what happens in the Interactive Example, as it isn't very clear and will be hard to make so due to the interaction between the various flex properties.

2021-04-15 01:17 UTC, ericwbailey requested changes

2021-04-15 01:17 UTC, ericwbailey commented on files/en-us/web/css/flex-basis/index.html
> +<figure style="padding-bottom: 2em;">
What's our policy on inline styling like this? I assume it's to flag an issue if we need better defaults?

2021-04-15 01:17 UTC, ericwbailey commented on files/en-us/web/css/flex-basis/index.html
> +  <img src="firefox-flex-basis.jpg" alt="The Firefox Flexbox Inspector showing the size of the item once it has shrunk">
```suggestion
  <img src="firefox-flex-basis.jpg" alt="The Firefox Flexbox Inspector showing the size of the item once it has shrunk.">
```

Periods supply a nice pause for AT to help communicate the end of the alt description.

2021-04-15 04:00 UTC, rachelandrew commented on files/en-us/web/css/flex-basis/index.html
> +<figure style="padding-bottom: 2em;">
I'm going to raise it as an issue, if you remove it in DevTools you'll see the problem I'm fixing. I figured I'd do that for now then raise an issue for the site CSS.

2021-04-19 13:54 UTC, ericwbailey commented on files/en-us/web/css/flex-basis/index.html
> +<figure style="padding-bottom: 2em;">
Ah yep, yikes.

2021-04-19 13:54 UTC, ericwbailey approved these changes

2021-04-19 13:54 UTC, merged