update accessibility page for deafness
mdn/content pull request #4109
Opened 2021-04-14 15:39 UTC by emilylederman

Updated section for deafness to reflect cultural themes + a wider range of resources

> What was wrong/why is this fix needed? (quick summary only)
Section was sparsely populated + did not provide sufficient resources for design; rewritten through deaf lens

> MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-04-14 15:59 UTC, Ryuno-Ki requested changes
Welcome to MDN, @emilylederman!
It's so great to have you with us!

I looked through your suggestions and have some remarks from my own experience with the German deaf community.
Perhaps we can find some middle ground?

I'd love to have a section on cultural background of the DHH community. Given that the page in question is rather an introduction into accessibility, I'm not quite sure, whether it's the right place to give these information, though.

Therefore, I request some changes before we can merge them in :-)

2021-04-14 15:59 UTC, Ryuno-Ki commented on files/en-us/learn/accessibility/what_is_accessibility/index.html
> +<h3 id="People_with_hearing_impairments">Deaf people</h3>
I'm not sure, whether we want to rephrase this heading.

As a father of a deaf child (or, profound hearing impairment, as you call it down), I can tell, that there is a difference between the deaf and the hard-of-hearing community. I could live with the „Deaf and hard-of-hearing” you used below.

2021-04-14 15:59 UTC, Ryuno-Ki commented on files/en-us/learn/accessibility/what_is_accessibility/index.html
> +<p><a href="https://www.nad.org/resources/american-sign-language/community-and-culture-frequently-asked-questions/">Deaf and hard-of-hearing (DHH)</a> people have various levels of hearing loss rangi
```suggestion
<p><a href="https://www.nad.org/resources/american-sign-language/community-and-culture-frequently-asked-questions/">Deaf and hard-of-hearing (DHH)</a> people have various levels of hearing loss ranging from mild to profound. Although some do use AT (see <a href="https://www.nidcd.nih.gov/health/assistive-devices-people-hearing-voice-speech-or-language-disorders">Assistive Devices for People with Hearing, Voice, Speech, or Language Disorders</a>), they are not widespread.</p>
```

Yes, Google Chrome released an auto-captioning extension. From what I hear, the quality is sub-par and not representing the content on an acceptable level (compared to a manual translation). That might be different for US content, where you have a broader corpus to Machine Language-translate from.

I'm cautious to advertise it. Perhaps add it in a „See also” section?

2021-04-14 15:59 UTC, Ryuno-Ki commented on files/en-us/learn/accessibility/what_is_accessibility/index.html
> +<p>To provide access, textual alternatives must be provided. Videos should be manually captioned, and transcripts should be provided for audio content. Furthermore, due to high levels of <a href="htt
The language deprivation has a cultural note as well.
Especially in the Deaf community, the „hearing people” (= „us”) forbid the use of sign language in school. Lip reading allows for ~30% of content to be deciphered (because words like „mother” and „brother” look the same). Therefore, the DHH community had less access to knowledge.

That being said, „late-deafened” people (caused by age, trauma or else) have less language deprivation since they learned during their hearing phase.

Therefore, I'd ask to rephrase this paragraph.

Text simplification is helping a wider audience, too. For example, people for which the given language is not their first one. In Germany, we have the concept of [Leichte Sprache](https://en.wikipedia.org/wiki/Leichte_Sprache), which could give some examples (likely a whole new section, which could then be linked to from this one?)

2021-04-14 15:59 UTC, Ryuno-Ki commented on files/en-us/learn/accessibility/what_is_accessibility/index.html
> +<p>Deaf people also represent a significant userbase — "466 million people worldwide have disabling hearing loss", says the World Health Organization's <a href="https://www.who.int/mediacentre/factsh
```suggestion
<p>Deaf and hard-of-hearing people also represent a significant userbase — "466 million people worldwide have disabling hearing loss", says the World Health Organization's <a href="https://www.who.int/mediacentre/factsheets/fs300/en/">Deafness and hearing loss</a> fact sheet.</p>
```

2021-04-14 16:39 UTC, chrisdavidmills commented
Thanks for the review, @Ryuno-Ki !

2021-05-26 07:25 UTC, sideshowbarker commented
@emilylederman This PR seems to be waiting on responses from you to review comments

2021-06-03 10:54 UTC, Ryuno-Ki commented
@sideshowbarker Since there was no response (and the GitHub activity chart seem to be quiet), would it be okay if I pick up this PR and submit commits to get a first iteration over the finish line?

2021-06-03 19:35 UTC, sideshowbarker commented
> @sideshowbarker Since there was no response (and the GitHub activity chart seem to be quiet), would it be okay if I pick up this PR and submit commits to get a first iteration over the finish line?

Yes please 👍 — that would be great

2021-06-09 19:57 UTC, Ryuno-Ki commented
@sideshowbarker I pushed the suggested changes but not the rephrase inquiry.
I'd appreciate a second pair of eyeballs on this :-)

2021-06-09 19:58 UTC, Ryuno-Ki commented
For the record:

```sh
git fetch upstream pull/4109/head:a11y-updates
git checkout a11y-updates
# Make changes
git commit -S -s
git push git@github.com:emilylederman/content.git a11y-updates:patch-1
```

Was used to update this PR.
See https://medium.com/google-cloud/pull-push-to-someone-elses-upstream-github-pr-6073ae5005e7

2021-06-10 02:29 UTC, sideshowbarker approved these changes
Reviewed both the full patch and with https://github.com/mdn/content/pull/4109/files?w=1 (so I could view the non-whitespace changes in isolation) — and it all looks excellent to me.

2021-06-10 02:29 UTC, merged