Adding the BackgroundFetchEvent interface
mdn/content pull request #4135
Opened 2021-04-15 15:25 UTC by rachelandrew

Adds the BackgroundFetchEvent interface.

Reviewer: @jpmedley

2021-04-16 13:59 UTC, jpmedley requested changes

2021-04-16 13:59 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchevent/index.html
> +<p><em>Inherits properties from its ancestor, {{domxref("Event")}}</em>.</p>
```suggestion
<p><em>Inherits properties from its ancestor, {{domxref("ExtendableEvent")}}</em>.</p>
```

2021-04-16 13:59 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchevent/index.html
> +<p>In this example, if the user clicks on the UI displaying the download progress, a new window will open. The current {{domxref("BackgroundFetchRegistration")}} is returned by calling <code>event.re
```suggestion
<p>In this example, if the user clicks on the user interface displaying the download progress, a new window will open. The current {{domxref("BackgroundFetchRegistration")}} is returned by calling <code>event.registration</code>.</p>
```

2021-04-16 13:59 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchevent/registration/index.html
> +<p>In this example, if the user clicks on the UI displaying the download progress, this fires the <code>onbackgroundfetchclick</code> event. The current {{domxref("BackgroundFetchRegistration")}} is
```suggestion
<p>In this example, if the user clicks on the user interface displaying the download progress, this fires the <code>onbackgroundfetchclick</code> event. The current {{domxref("BackgroundFetchRegistration")}} is returned by calling <code>event.registration</code>.</p>
```

2021-04-16 16:54 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchevent/index.html
> +
It looks like `ExtendableEvent` is more like an abstract base class and isn't used anywhere directly. My suggestion is the standard approach for event inheritance, but I don't think it's correct for this event. Don't merge this suggestion. I've made a note to bring it up in Monday's editorial meeting.

2021-04-16 18:14 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchevent/index.html
> +
There are some other interfaces which extend ExtendableEvent but have been documented to extend Event - FetchEvent is an example https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent which is why I followed suit.

2021-04-19 19:10 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchevent/index.html
> +
I forgot to bring it up. Then we'll stick with extending event. We'll need to leave out the inheritance diagram. That's why I'm still going to bring this up.

2021-04-21 15:04 UTC, jpmedley approved these changes

2021-04-21 15:04 UTC, merged