Adds BackgroundFetchUpdateUIEvent
mdn/content pull request #4164
Opened 2021-04-16 10:47 UTC by rachelandrew

This is the last of the Background Fetch interfaces.

Reviewer @jpmedley

2021-04-16 17:33 UTC, jpmedley requested changes

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> +<p>A <code>BackgroundFetchUpdateUIEvent</code> has an internal flag <code>UI updated</code>, which is initially unset. This cannot be updated by a web developer but is set when the {{domxref("Backgro
```suggestion
<p class="summary">The <strong><code>BackgroundFetchUpdateUIEvent</code></strong> interface of the {{domxref('Background Fetch API','','',' ')}} is an event type passed to {{domxref("ServiceWorkerGlobalScope.onbackgroundfetchsuccess")}} and {{domxref("ServiceWorkerGlobalScope.onbackgroundfetchfail")}}, and provides a method for updating the title and icon of the app to inform a user of the success or failure of a background fetch. </p>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> +<p>A <code>BackgroundFetchUpdateUIEvent</code> has an internal flag <code>UI updated</code>, which is initially unset. This cannot be updated by a web developer but is set when the {{domxref("Backgro
I'm suggesting this because its more succinct. Is there a property that reflects the state fo the flag? Assuming there is, all the developer needs to know is that "suchAndSuch property indicates whether the UI has been updated.

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> + <dd>Creates a new <code>BackgroundFetchUIEvent</code> object. This constructor is not typically used, as the browser creates these objects itself and provides them to background fetch event callback
```suggestion
 <dd>Creates a new <code>BackgroundFetchUIEvent</code> object. This constructor is not typically used, as the browser creates these objects itself and passed them to {{domxref("ServiceWorkerGlobalScope.onbackgroundfetchsuccess")}} and {{domxref("ServiceWorkerGlobalScope.onbackgroundfetchfail")}}.</dd>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> +  <dd>Provides a method to update the title and icon in the user interface in order to show the status of a background fetch. Resolves with a {{jsxref("Promise")}}.</dd>
```suggestion
  <dd>Updates the title and icon in the user interface to show the status of a background fetch. Resolves with a {{jsxref("Promise")}}.</dd>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +<p class="summary">The <strong><code>updateUI()</code></strong> method of the {{domxref("BackgroundFetchUpdateUIEvent")}} interface provides a method to update the title and icon in the user interfac
```suggestion
<p class="summary">The <strong><code>updateUI()</code></strong> method of the {{domxref("BackgroundFetchUpdateUIEvent")}} interface updates the title and icon in the user interface to show the status of a background fetch.</p>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +<p>After this method has run successfully, the UI Updated flag of the {{domxref("BackgroundFetchUpdateUIEvent")}} is set.</p>
How is this useful to a deverloper?

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +  <dd>An object containing one or both of the following:
```suggestion
  <dd>An object containing any of the following:
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
```suggestion
          <dd>A {{domxref("DOMString","string")}} which is equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
This `<link>` element is a bit out of nowhere. What link element does the spec have in mind? You should probably provide more information.

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which represents an image MIME type.</dd>
```suggestion
          <dd>A {{domxref("DOMString","string")}} containing an image MIME type.</dd>
```

2021-04-16 17:33 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +      <li>The {{domxref("BackgroundFetchUpdateUIEvent")}} UI updated flag is already set.</li>
Does this mean I can only call `updateUI()` once on a single event? If so, then the opening paragraph should say, that this function can only be called once, and this should say, "`updateUI()` has already been called."

2021-04-16 17:58 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> +<p>A <code>BackgroundFetchUpdateUIEvent</code> has an internal flag <code>UI updated</code>, which is initially unset. This cannot be updated by a web developer but is set when the {{domxref("Backgro
no, no property. Probably wouldn't have mentioned it other than that it's used to set that fact that it has run already.

2021-04-16 17:59 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +<p>After this method has run successfully, the UI Updated flag of the {{domxref("BackgroundFetchUpdateUIEvent")}} is set.</p>
Because it's the reason it will error if you run it again. I'd say that's useful to know.

2021-04-16 18:01 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
Don't understand how it's out of nowhere, there is only one html `<link>` element, and I linked to it. If you know what a link is, and know what the sizes attribute is that's handy to know. If you don't there is an MDN page to tell you about it. Which actually could do with an update, I've added it to my list of stuff on the HTML and CSS side that needs improving.

2021-04-16 18:08 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
This is all fyi within a dictionary, [I posted to an issue earlier](https://github.com/mdn/browser-compat-data/issues/8938#issuecomment-821061568) where someone was asking for ImageResource to be documented, I don't think there has really been a final decision on what to do about dictionaries so for now I'm documenting them inline.

2021-04-19 17:36 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> +<p>A <code>BackgroundFetchUpdateUIEvent</code> has an internal flag <code>UI updated</code>, which is initially unset. This cannot be updated by a web developer but is set when the {{domxref("Backgro
Use my suggestion then.

2021-04-19 17:38 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +<p>After this method has run successfully, the UI Updated flag of the {{domxref("BackgroundFetchUpdateUIEvent")}} is set.</p>
Isn't the sequence of events:

something happens which causes --> the flag to be set --> then an error is thrown

If that's the case then doesn't the developer need to know the something that happened?

2021-04-19 17:48 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
I don't know what the link is in this context. Is it something a user clicked to start a background fetch?

2021-04-20 12:53 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +          <dd>A {{domxref("DOMString","string")}} which iis equivalent to a {{htmlelement("link")}} <code>sizes</code> attribute.</dd>
no, it's just more context, which is why I linked to it. The dictionary for image-resource is a bunch of stuff related to an image, a web developer who knows what the sizes attribute is, then has the info they need to know what this is, it ties it all together.

2021-04-20 13:25 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/updateui/index.html
> +<p>After this method has run successfully, the UI Updated flag of the {{domxref("BackgroundFetchUpdateUIEvent")}} is set.</p>
isn't that what I already have? The "something" that has happened is that "this method has run successfully". You seemed to want to remove it in the first comment, I think it should stay, as the reason you can't run the thing repeatedly is that the flag is set.

2021-04-20 14:24 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/index.html
> + <dd>Creates a new <code>BackgroundFetchUIEvent</code> object. This constructor is not typically used, as the browser creates these objects itself and provides them to background fetch event callback
If we are going to link to these then we should also document them.

2021-04-20 14:50 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/backgroundfetchupdateuievent/index.html
> +  <dd>A {{domxref("BackgroundFetchRegistration")}}.</dd>
do you have an example? I can't find any mention of `registration: bfrInstance` on MDN or in the spec, so I'm not sure what you are asking for.

And would we not just mention that this extends Event as the dictionary is documented there? https://developer.mozilla.org/en-US/docs/Web/API/Event/Event If we need to document it here as well, why is this one different? (So I know for another time as we normally just say that it inherits properties from x).

2021-04-21 15:55 UTC, jpmedley commented on files/en-us/web/api/backgroundfetchupdateuievent/backgroundfetchupdateuievent/index.html
> +  <dd>A {{domxref("BackgroundFetchRegistration")}}.</dd>
Here's what the init dictionary looks like in Chrome: third_party/blink/renderer/modules/background_fetch/background_fetch_event_init.idl

So the init for an event looks like this: 

`let newEvent = new SomeEvent('SomeEvent', { registration: bfrIinstance });`

If you use more of the defaults:

```
let newEvent = new SomeEvent('SomeEvent', { 
  registration: bfrIinstance,
  changeDefault: true
});```

2021-04-22 10:22 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/backgroundfetchupdateuievent/index.html
> +  <dd>A {{domxref("BackgroundFetchRegistration")}}.</dd>
Sorry, where does `changeDefault` come from?

I'm looking at the spec for `Event` here: https://dom.spec.whatwg.org/#interface-event which doesn't mention `changeDefault`.

I don't see what you are seeing here: https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/background_fetch/background_fetch_event.idl

Or in the one that relates to this method https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/background_fetch/background_fetch_update_ui_event.idl

I'm still confused by what you are asking me to do as it doesn't map to anything I can find in a specification. And. as I asked, why is this one different and not just inheriting Event ... if I don't know why this one is different, we'll end up having the same discussion again.

I feel like I'm being really dim but it's like we are looking at two different things.

2021-04-23 07:56 UTC, rachelandrew commented on files/en-us/web/api/backgroundfetchupdateuievent/backgroundfetchupdateuievent/index.html
> +  <dd>A {{domxref("BackgroundFetchRegistration")}}.</dd>
After our conversation I have updated this using the same style as Event https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

2021-04-26 17:19 UTC, jpmedley approved these changes

2021-04-26 17:19 UTC, merged