Add a page for WebHID API
mdn/content pull request #4234
Opened 2021-04-19 05:02 UTC by SnorlaxYum

Add a page for WebHID API. Later I will add pull requests one by one for the global interfaces `HID`, `HIDConnectionEvent`, `HIDInputReportEvent`, `HIDDevice`.

As for compat data, already added a pull request: https://github.com/mdn/browser-compat-data/pull/9910

And it seems the backend didn't recognize the correct specification url, it should be: https://wicg.github.io/webhid/ . So maybe ur backend developers should work to fix that recognization problem?

2021-04-20 18:28 UTC, jpmedley requested changes
Hi,

Thank you for your submission. The first paragraph shows that you can write. The feedback I have is to make this fit better with how we do things in MDN. (Any website that depends on writing will likely have requirements specific to it.) In case you haven't found them yet, [here's MDN's guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference).

One general comment I have is that descriptions of things need to be very specific. I've made some suggestions. 

Let me know if you have any questions. I'm here to help.

Joe

2021-04-20 18:28 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>The Event about HID Input Report.</dd>
```suggestion
    <dd>Passed to {{domxref("HIDDevice. oninputreport")}} when a user interacts with the specified device.</dd>
```

2021-04-20 18:28 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>The Event about HID Connection.</dd>
```suggestion
    <dd>Passed to {{domxref("HID.onconnect")}} and {{domxref("HID.ondisconnect")}} when a device is connected or disconnected.</dd>
```

2021-04-20 18:28 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +<p>Retrieve devices and log the device names to the console.</p>
Please use complete sentences when introducing examples.

2021-04-20 18:28 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    navigator.hid.addEventListener('disconnect', ({device}) => {
```suggestion
    navigator.hid.addEventListener('disconnect', (device) => {
```

2021-04-20 19:20 UTC, Ryuno-Ki commented on files/en-us/web/api/webhid_api/index.html
> +<p>A HID (Human Interface Device) is a type of device that takes input from or provides output to humans. It also refers to the HID protocol, a standard for bi-directional communication between a hos
Is there a legal public version of it?
I've heard of Chicago Manual of Style from A List Apart the first time. A research brings up a book that's still for sale.
Kinda bummer, that we refer to a styleguide, which is not publicly available for everyone to check :-/

2021-04-21 03:10 UTC, SnorlaxYum commented on files/en-us/web/api/webhid_api/index.html
> +    navigator.hid.addEventListener('disconnect', ({device}) => {
The [original example](https://wicg.github.io/webhid/#example-1) was doing the destructuring assignment

2021-04-21 20:27 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +<p>A HID (Human Interface Device) is a type of device that takes input from or provides output to humans. It also refers to the HID protocol, a standard for bi-directional communication between a hos
It's a rather pricy book. I don't generally hold people to standards in books they don't own. This is common enough that was worth sharing that its a thing.

2021-04-21 20:30 UTC, jpmedley requested changes
I'm making these requests with an apology. I incorrectly capitalized some of my suggestions. I don't like to subject volunteers to multiple rounds of review. Please forgive and accept the changes.

2021-04-21 20:30 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>provides methods for connecting to HID devices, listing attached HID devices and event handlers for connected HID devices.</dd>
```suggestion
    <dd>Provides methods for connecting to HID devices, listing attached HID devices and event handlers for connected HID devices.</dd>
```

2021-04-21 20:30 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>represents an HID device. It's possible for a single physical device to be represented by multiple `HIDDevice` obects.</dd>
```suggestion
    <dd>Represents an HID device. It's possible for a single physical device to be represented by multiple `HIDDevice` obects.</dd>
```

2021-04-21 20:30 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>passed to {{domxref("HIDDevice.oninputreport")}} when an input report is received from the any associated HID device.</dd>
```suggestion
    <dd>Passed to {{domxref("HIDDevice.oninputreport")}} when an input report is received from the any associated HID device.</dd>
```

2021-04-21 20:30 UTC, jpmedley commented on files/en-us/web/api/webhid_api/index.html
> +    <dd>passed to {{domxref("HID.onconnect")}} and {{domxref("HID.ondisconnect")}} when a device is connected or disconnected.</dd>
```suggestion
    <dd>Passed to {{domxref("HID.onconnect")}} and {{domxref("HID.ondisconnect")}} when a device is connected or disconnected.</dd>
```

2021-04-22 13:52 UTC, rachelandrew commented
@SnorlaxYum Specs need to be added to Yari if they don't already exist in the system (which is likely the case if you are documenting something with no existing interfaces documented already). 

I've added this one in https://github.com/mdn/yari/pull/3599 however even once merged it may take a little while to show up. Add the spec tables as you have been doing and it will resolve once it is all there.

2021-04-22 14:09 UTC, SnorlaxYum commented
@rachelandrew awesome, thanks.

2021-04-23 07:58 UTC, rachelandrew commented on files/en-us/web/api/webhid_api/index.html
> +<p>You can connect to a device with {{domxref("HID.requestDevices")}}. In this case, we gonna select from all the available devices.</p>
```suggestion
<p>You can connect to a device with {{domxref("HID.requestDevices")}}. In this case, we select from all the available devices.</p>
```

2021-04-26 17:23 UTC, jpmedley approved these changes

2021-04-26 17:23 UTC, merged

2021-04-26 17:23 UTC, jpmedley commented
Thank you for the help.