outline border.radius changes
mdn/content pull request #4300
Opened 2021-04-20 12:50 UTC by mirunacurtean

> What was wrong/why is this fix needed? (quick summary only)
- Removed outline property notes and table from experimental features page as it is already enabled by default in all release channels. 
- Added Note under demo https://developer.mozilla.org/en-US/docs/Web/CSS/outline about the layout.css.outline-follows-border-radius.enabled pref being enabled by default. 

> MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#outline_property
https://developer.mozilla.org/en-US/docs/Web/CSS/outline

> Issue number (if there is an associated issue)
#3453

2021-04-21 03:56 UTC, rachelandrew commented on files/en-us/web/css/outline/index.html
> +<div class="note">
If there should be any additional support info I think this should be detailed in BCD, I'm not sure of any reason to add browser-specific notes to the page like this, it will just become out of date and we don't do this for other properties.

2021-04-21 07:53 UTC, chrisdavidmills commented on files/en-us/web/css/outline/index.html
> +<div class="note">
Ah yes, @rachelandrew is right here.

So, `-moz-outline-radius*` properties e.g. [-moz-outline-radius](https://github.com/mdn/browser-compat-data/blob/main/css/properties/-moz-outline-radius.json) should be updated to say that their `version_removed` for Firefox and Firefox Android is 88.

And `outline*` properties e.g. [outline](https://github.com/mdn/browser-compat-data/blob/main/css/properties/outline.json) should be updated to include the note that you put in this page. I think just as a note on the existing support info is fine. And then remove the note from this page.

@mirunacurtean You can find a load of information on what these constructs should look like in the BCD data at https://developer.mozilla.org/en-US/docs/MDN/Structures/Compatibility_tables.

We can also go through this in our meeting later today if you have questions.

2021-04-21 10:04 UTC, mirunacurtean commented on files/en-us/web/css/outline/index.html
> +<div class="note">
Noted and thanks @rachelandrew. 
Ignore all notifications - I was just trying to update the branch to include the latest changes, 
@chrisdavidmills I did start to make some changes to the BCD in the outline pages instead, but they did not pass all checks so I'd like to go them and the other ones in our meeting today.

2021-04-21 19:49 UTC, peterbe requested changes
@mirunacurtean You need to undo your changes to `package.json` and `yarn.lock`. 
If you need any help at all with that, ping me on Slack.

2021-04-22 13:03 UTC, mirunacurtean commented
Tried to bring this up to date and unfortunately erased all the changes. 
Created a new ticket just for  removal of reference from the Experimental Features page. https://github.com/mdn/content/pull/4380

2021-04-22 13:03 UTC, closed without merging