WebDriver conformance changes for Firefox 88
mdn/content pull request #4322
Opened 2021-04-20 18:50 UTC by whimboo

Sorry for being late again with our changes but this is is what happened for WebDriver.

2021-04-20 18:51 UTC, whimboo commented
CC @juliandescottes

2021-04-20 20:35 UTC, juliandescottes reviewed
Content looks good to me, thanks! Small typos, but I think @chrisdavidmills will review that better than I can :)

2021-04-20 20:35 UTC, juliandescottes commented on files/en-us/mozilla/firefox/releases/88/index.html
> +  <li>Fixed a bug where pointer actions other than <code>down</code> and <code>up</code> inappropriatelly lead to buttons to be pressed ({{bug(1686361)}}).</li>
```suggestion
  <li>Fixed a bug where pointer actions other than <code>down</code> and <code>up</code> inappropriately lead to buttons to be pressed ({{bug(1686361)}}).</li>
```

(and maybe "lead to buttons to be pressed" -> "lead (led?) buttons to be pressed")

2021-04-20 20:35 UTC, juliandescottes commented on files/en-us/mozilla/firefox/releases/88/index.html
> +  <li>Fixed a race condition in <code>WebDriver:GetCurrentURL</code> that could have lead the command to return the URL of the previously opened page, or even a hang in Marionette ({{bug(1664881)}}).
```suggestion
  <li>Fixed a race condition in <code>WebDriver:GetCurrentURL</code> that could have led the command to return the URL of the previously opened page, or even a hang in Marionette ({{bug(1664881)}}).</li>
```

2021-04-21 07:16 UTC, chrisdavidmills requested changes
Couple of small change requests, but nothing major. Nice work @whimboo !

2021-04-21 07:16 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/releases/88/index.html
> +  <li>Marionette will no longer be enabled unless the <code>--marionette</code> command line argument or the <code>MOZ_MARIONETTE</code> environment variable have been specified. As such the <code>ma
"have been" sounds a bit awkward. "is" would work better

2021-04-21 07:16 UTC, chrisdavidmills commented on files/en-us/mozilla/firefox/releases/88/index.html
> +  <li>Fixed a bug where pointer actions other than <code>down</code> and <code>up</code> inappropriatelly lead to buttons to be pressed ({{bug(1686361)}}).</li>
"to be" -> "being"

2021-04-21 16:22 UTC, whimboo commented
@chrisdavidmills please check again. I just pushed the required changes.

2021-04-21 16:37 UTC, chrisdavidmills approved these changes
Perfect, thanks @whimboo !

2021-04-21 16:37 UTC, merged