HID interface page
mdn/content pull request #4368
Opened 2021-04-22 03:24 UTC by SnorlaxYum

Added a page about this interface. And this page is needed for https://github.com/mdn/content/pull/4234 .
Still, the same problem as the parent doc: it seems the backend didn't recognize the correct specification url, it should be: https://wicg.github.io/webhid/ .

2021-04-22 18:50 UTC, jpmedley requested changes

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> +     <td>{{SpecName('WebHID API', '#dom-hid', 'HID')}}</td>
```suggestion
     <td>{{SpecName('WebHID', '#dom-hid', 'HID')}}</td>
```

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> +     <td>{{SpecName('WebHID API', '#dom-hid', 'HID')}}</td>
I forgot to check this in your other PR. The first parameter is a key that comes [from this file](https://github.com/mdn/yari/blob/main/kumascript/macros/SpecData.json#L1647). PRs are welcome if you need one that's missing.

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> +     <td>{{SpecName('WebHID API', '#dom-hid', 'HID')}}</td>
Frankly, I wouldn't bother to learn this. We're about to change how this is done.

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> +<p><em>The <code>HID</code> interface doesn't inherit any property.</em></p>
@Rumyra This isn't something we're doing now, is it?

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>The event that's fired when an HID device is connected.</dd>
```suggestion
 <dd>Fired when an HID device is connected.</dd>
```

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>The event that's fired when an HID device is connected.</dd>
Your grammar teach told you never to use a sentence fragment. One exception is in a list of definitions in a reference work. There are several reasons for this:
* We know what the subject would be because of the term in the line above it. 
* That makes the subject of this sentence redundant and a writing best practice is to omit needless words.
* Reference materials are often scanned rather than read all the way through. Removing the extra material makes scanning easier.

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>The event that's fired when an HID device is disconnected.</dd>
```suggestion
 <dd>Fired when an HID device is disconnected.</dd>
```

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>Returns a {{jsxref("Promise")}} that resolves to an array of connected {{domxref("HIDDevice")}}s.
```suggestion
 <dd>Returns a {{jsxref("Promise")}} that resolves with an array of connected {{domxref("HIDDevice")}} objects.
```

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>Returns a {{jsxref("Promise")}} that resolves to an array of connected {{domxref("HIDDevice")}}s.
The `domxref` macro will render the text in a monospaced font. For aesthetic reasons, many people avoid mixing fonts within the same word.

2021-04-22 18:50 UTC, jpmedley commented on files/en-us/web/api/hid/index.html
> + <dd>Returns a {{jsxref("Promise")}} that resolves to an array of connected {{domxref("HIDDevice")}}s from the HID device selected from popup.
```suggestion
 <dd>Returns a {{jsxref("Promise")}} that resolves with an array of connected {{domxref("HIDDevice")}} objects from the HID device selected from popup.
```

2021-04-23 02:55 UTC, SnorlaxYum commented on files/en-us/web/api/hid/index.html
> +     <td>{{SpecName('WebHID API', '#dom-hid', 'HID')}}</td>
kk ;) will do it when it's needed in the future

2021-04-23 02:59 UTC, SnorlaxYum commented on files/en-us/web/api/hid/index.html
> + <dd>The event that's fired when an HID device is connected.</dd>
kk, next time I'll treat the `dd` content as an attributive clause for the `dt`

2021-04-23 07:47 UTC, rachelandrew commented on files/en-us/web/api/hid/index.html
> +<p><em>The <code>HID</code> interface doesn't inherit any property.</em></p>
According to [the API guide](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference#structure_of_an_interface_page) we only add this if the interface inherits.

2021-04-23 07:58 UTC, SnorlaxYum commented on files/en-us/web/api/hid/index.html
> +<p><em>The <code>HID</code> interface doesn't inherit any property.</em></p>
my mistake. it actually inherits from its parent, EventTarget. just fixed it.

2021-04-26 17:21 UTC, jpmedley approved these changes

2021-04-26 17:21 UTC, merged

2021-04-26 17:21 UTC, jpmedley commented
Thanks for your help.