Fix: Broken link to `Accept-Type` in "HTTP Messages"
mdn/content pull request #4433
Opened 2021-04-24 04:51 UTC by Shinyaigeek

> What was wrong/why is this fix needed? (quick summary only)

I fixed link's label and href to `Accept` in "HTTP Message" page.

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages

> Issue number (if there is an associated issue)

fix: #4429 

> Anything else that could help us review it

2021-04-25 17:40 UTC, wbamberg requested changes
Thanks @Shinyaigeek , this is a good fix. But I think while we are here we could fix the grammar:

"like A,B" -> "like A or B"

2021-04-25 17:40 UTC, wbamberg commented on files/en-us/web/http/messages/index.html
> + <li><em>Request headers</em>, like {{HTTPHeader("User-Agent")}}, {{HTTPHeader("Accept")}}, modify the request by specifying it further (like {{HTTPHeader("Accept-Language")}}), by giving context (li
```suggestion
 <li><em>Request headers</em>, like {{HTTPHeader("User-Agent")}} or {{HTTPHeader("Accept")}}, modify the request by specifying it further (like {{HTTPHeader("Accept-Language")}}), by giving context (like {{HTTPHeader("Referer")}}), or by conditionally restricting it (like {{HTTPHeader("If-None")}}).</li>
```

2021-04-26 01:16 UTC, Shinyaigeek commented on files/en-us/web/http/messages/index.html
> + <li><em>Request headers</em>, like {{HTTPHeader("User-Agent")}}, {{HTTPHeader("Accept")}}, modify the request by specifying it further (like {{HTTPHeader("Accept-Language")}}), by giving context (li
Thank you for reviewing !!
I think so, I applied your commit suggestion, Thank you 👍

2021-04-28 17:02 UTC, wbamberg approved these changes
Thanks @Shinyaigeek , and welcome to the MDN contributor community!

2021-04-28 17:02 UTC, merged