fix: colgroup child count
mdn/content pull request #450
Opened 2020-12-19 02:23 UTC by nschonni

2020-12-19 02:37 UTC, sideshowbarker approved these changes

2020-12-20 23:09 UTC, vkWeb requested changes

2020-12-20 23:09 UTC, vkWeb commented on files/en-us/mdn/editor/keyboard_shortcuts/index.html
> +  <col>
Looks like one extra `col` here.

2020-12-20 23:12 UTC, nschonni commented on files/en-us/mdn/editor/keyboard_shortcuts/index.html
> +  <col>
Thanks! I must have gone and fixed it twice 😆

2020-12-20 23:17 UTC, vkWeb commented on files/en-us/mdn/editor/keyboard_shortcuts/index.html
> +  <col>
@nschonni happens :rofl:

2020-12-20 23:18 UTC, vkWeb approved these changes
Now let's merge! :tada:

2020-12-21 07:48 UTC, chrisdavidmills approved these changes

2020-12-21 07:48 UTC, merged