Adds TransformStreamDefaultController
mdn/content pull request #4530
Opened 2021-04-27 16:41 UTC by rachelandrew

Documenting the `TransformStreamDefaultController` interface.

I also updated the main Streams API overview to link to this interface, and TransformStream. In working on this I saw that TransformStream is missing a bunch of pages: https://developer.mozilla.org/en-US/docs/Web/API/TransformStream

Reviewer: @jpmedley

2021-04-29 14:23 UTC, jpmedley requested changes
Typo wise, this is really clean. I have a few conceptual questions that I think users will have an so need to be answered.

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/enqueue/index.html
> +<p>In this example an endoded string is passed to the queue using the <code>enqueue()</code> method.</p>
```suggestion
<p>In this example an encoded string is passed to the queue using the <code>enqueue()</code> method.</p>
```

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/enqueue/index.html
> +<pre class="brush: js">controller.enqueue(this.textencoder.encode(String(chunk)))</pre>
Is `controller` an instance of `ReadableStream`. Please make it clear what this is.

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/error/index.html
> +<pre class="syntaxbox">TransformStreamDefaultController.error(e);</pre>
```suggestion
<pre class="syntaxbox">TransformStreamDefaultController.error(reason);</pre>
```

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/error/index.html
> +  <dt><code>e</code></dt>
```suggestion
  <dt><code>reason</code></dt>
```

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/error/index.html
> +<pre class="syntaxbox">TransformStreamDefaultController.error(e);</pre>
The IDL term seems useful here. 'Reason' is more descriptive than 'e'.

2021-04-29 14:23 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
Please describe how to get an instance of this.

2021-04-30 13:51 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/desiredsize/index.html
> +<p class="summary">The <strong><code>desiredSize</code></strong> read-only property of the {{domxref("TransformStreamDefaultController")}} interface returns the desired size to fill the queue of the
No it's letting you know the state of the readable stream so you can apply backpressure or do some other management https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts#backpressure in my next commit I've added a link to that.

2021-04-30 14:08 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
I'm having trouble doing so without using the terminology "Internal slots" of which you are not fond https://streams.spec.whatwg.org/#ts-internal-slots it doesn't help that TransformStream itself isn't documented as I actually think this is better detailed there, in the same way as ReadableStream https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream

It's created by constructing a TransformStream, which I already have. The details of that really belong to TransformStream.

2021-04-30 14:15 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/enqueue/index.html
> +<pre class="brush: js">controller.enqueue(this.textencoder.encode(String(chunk)))</pre>
We're dealing with `TransformStreamDefaultController` so it's an instance of that, as part of the transformer. I found a succinct example that maybe is better. Adding in my next commit.

2021-04-30 15:34 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
You should reach out to the spec author. If there's not a constructor, there should be a property on another object that returns it. I can't find one anywhere.

2021-05-18 15:55 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
sorry I totally missed this, I think it was during the period I also had all the Learn CSS PRs to wrangle and it all got a bit noisy.

I've just had another look at this to refresh my memory, and I'm not really sure what I'd be asking a spec author that isn't already in the spec (so I think I don't understand what the problem you have here is, I must be missing something).

In https://streams.spec.whatwg.org/#ts-default-controller-abstract-ops it seems clear that the TransformStreamDefaultController is created during the setup process of a TransformStream, I think it needs documenting in the missing pages of TransformStream. But if you can explain again what I should ask a spec author, that isn't what is detailed there I'm happy to, I just don't understand what I'd be asking them right now :)

2021-05-18 18:06 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
I'm asking about `TransformStreamDefaultController`. You state that it's created when constructing a `TransformStream`. I can't find a method or property anywhere that returns it. It doesn't have a constructor either. How do I get an instance of it?

2021-06-03 19:28 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
I've been chatting to people in the whatwg irc about this, and the only way to gain access is via the Transformer callbacks https://streams.spec.whatwg.org/#transformer-api

So, I still think this is better detailed in the TransformStream constructor docs, as that is how a developer would be accessing it. Those docs don't exist as there is just an interface page, but I could write it.

2021-06-04 14:50 UTC, jpmedley commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
Please write it. Then add a quick line about getting it from the TransformStream with a link to the details.

2021-06-08 10:58 UTC, rachelandrew commented on files/en-us/web/api/transformstreamdefaultcontroller/index.html
> +<p>When constructing a {{domxref("TransformStream")}}, the <code>TransformStreamDefaultController</code> is created. It therefore has no constructor.</p>
I've created a separate PR for the missing TransformStream pages, and added a line to the main page for this one.

2021-06-08 18:43 UTC, jpmedley approved these changes

2021-06-08 18:50 UTC, jpmedley commented
I'm not sure why this is failing, and I'm not sure which of our colleagues to ask for help.

2021-06-09 08:05 UTC, merged