Fix URLs for IndexedDB examples
mdn/content pull request #456
Opened 2020-12-19 08:48 UTC by bershanskiy

URLs used to point to https://github.com/mdn/IDBIndex-example , but apparently have moved since. The new location is https://github.com/mdn/indexeddb-examples .

2020-12-19 10:39 UTC, chrisdavidmills requested changes
I don't think these changes are quite right. In each case, the repo and live example link should reference the IDBIndex example specifically, not the general IndexedDB demos repo.

The URLs would be:

* https://github.com/mdn/indexeddb-examples/tree/master/idbindex
* https://mdn.github.io/indexeddb-examples/idbindex/

2020-12-19 10:40 UTC, chrisdavidmills commented
And the link text should referenced the IDBIndex demo specifically, where appropriate.

2020-12-19 13:00 UTC, bershanskiy commented
Thanks for the review! I updated the links and added a text about IDBIndex in article about IDBObjectStore. Should I change anything else?

2020-12-19 19:29 UTC, chrisdavidmills approved these changes
Looking much better; couple of URLs still need fixing up a bit.

2020-12-19 19:29 UTC, chrisdavidmills commented on files/en-us/web/api/idbindex/index.html
> +<p>Finally, we iterate through each record, and insert the data into an HTML table. For a complete working example, see our <a href="https://mdn.github.io/indexeddb-examples/idbindexidbindex/">Indexe
The live URL here isn't quite right.

2020-12-19 19:29 UTC, chrisdavidmills commented on files/en-us/web/api/idbindex/keypath/index.html
> +<p>Finally, we iterate through each record, and insert the data into an HTML table. For a complete working example, see our <a href="https://github.com/mdn/indexeddb-examples/tree/master/idbindex/tre
Slightly wrong here too

2020-12-20 14:56 UTC, chrisdavidmills approved these changes
Perfect!

2020-12-20 14:57 UTC, merged