Moving some http links to https
mdn/content pull request #4633
Opened 2021-04-30 22:57 UTC by jamesaucode

> What was wrong/why is this fix needed? (quick summary only)

Found a few http links while I was going through the docs, changing them to https

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/API/Console/dirxml
https://developer.mozilla.org/en-US/docs/Web/API/Console/error
https://developer.mozilla.org/en-US/docs/Web/API/Console/group
https://developer.mozilla.org/en-US/docs/Web/API/Console/groupCollapsed
https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd
https://developer.mozilla.org/en-US/docs/Web/API/Console/info
https://developer.mozilla.org/en-US/docs/Web/API/Console/log
https://developer.mozilla.org/en-US/docs/Web/API/Console/time
https://developer.mozilla.org/en-US/docs/Web/API/Console/timeLog
https://developer.mozilla.org/en-US/docs/Web/API/Console/trace
https://developer.mozilla.org/en-US/docs/Web/API/Console/warn
https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API
https://developer.mozilla.org/en-US/docs/Web/API/mutationobserver
https://developer.mozilla.org/en-US/docs/Web/API/PaymentAddress
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events
https://developer.mozilla.org/en-US/docs/Web/API/Window/name
https://developer.mozilla.org/en-US/docs/Web/CSS
https://developer.mozilla.org/en-US/docs/Web/JavaScript
https://developer.mozilla.org/en-US/docs/Web/Tutorials

> Issue number (if there is an associated issue)

N/A

> Anything else that could help us review it

N/A

2021-05-01 01:04 UTC, wbamberg requested changes
Thanks for this, @jamesaucode ! I think many of these links are obsolete and should just be removed. I highlighted a few individual ones, but also:

* all the http://www.opera.com/dragonfly/ ones
* http://getfirebug.com/
* http://www.softwareishard.com/

2021-05-01 01:04 UTC, wbamberg commented on files/en-us/web/api/paymentaddress/index.html
> +<p>It may be useful to refer to the Universal Postal Union web site's <a href="https://www.upu.int/en/activities/addressing/s42-standard.html">Addressing S42 standard</a> materials, which provide inf
This link is 404. Maybe it wants to be https://www.upu.int/en/Postal-Solutions/Programmes-Services/Addressing-Solutions#addressing-s42-standard ?

2021-05-01 01:04 UTC, wbamberg commented on files/en-us/web/api/touch_events/using_touch_events/index.html
> + <li><a href="https://www.javascriptkit.com/javatutors/touchevents.shtml">Introduction to Touch events in JavaScript</a></li>
This link gives me a security error, shall we just remove it?

2021-05-01 01:04 UTC, wbamberg commented on files/en-us/web/api/window/name/index.html
> +    href="https://www.thomasfrank.se/sessionvars.html">SessionVars</a> and Dojo's <a
Let's remove this one.

2021-05-01 17:56 UTC, jamesaucode commented on files/en-us/web/api/paymentaddress/index.html
> +<p>It may be useful to refer to the Universal Postal Union web site's <a href="https://www.upu.int/en/activities/addressing/s42-standard.html">Addressing S42 standard</a> materials, which provide inf
Yes it seems like the case, will change the link to that instead

2021-05-04 04:10 UTC, wbamberg approved these changes
Thanks for the updates, @jamesaucode !

2021-05-04 04:10 UTC, merged