specify attribute support
mdn/content pull request #4675
Opened 2021-05-03 14:23 UTC by mrtnmgs

The aria-element can only be used on certain elements.

> What was wrong/why is this fix needed? (quick summary only)
Missing important information

> MDN URL of main page changed
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-05-04 00:18 UTC, ericwbailey requested changes
Looks good to me. I suggested a couple of tweaks: 

- Add a newline between the heading element and content to match the treatment elsewhere on this page
- Incorporate the source into the copy to remove the orphaned word

2021-05-04 00:18 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-label_attribute/index.html
> +
```suggestion
<h3 id="support">Elements supporting aria-label</h3>

The <code>aria-label</code> attribute <a href="https://www.tpgi.com/short-note-on-aria-label-aria-labelledby-and-aria-describedby/">should only be used</a> on the following elements:
- interactive elements
- landmark elements
- elements that have an explicit widget role
- <code>iframe</code> and <code>img</code> elements

```

2021-05-04 16:32 UTC, mrtnmgs commented
thanks for the suggestions @ericwbailey

2021-05-04 22:53 UTC, ericwbailey requested changes
One more tweak and we should be good! We'll need to wrap the content in HTML elements so it renders.

2021-05-04 22:53 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-label_attribute/index.html
> +- <code>iframe</code> and <code>img</code> elements
```suggestion
<p>The <code>aria-label</code> attribute <a href="https://www.tpgi.com/short-note-on-aria-label-aria-labelledby-and-aria-describedby/">should only be used</a> on the following elements:</p>

<ul>
  <li>Interactive elements</li>
  <li>Landmark elements</li>
  <li>Elements that have an explicit widget role</li>
  <li><code>iframe</code> and <code>img</code> elements</li>
</ul>
```

2021-05-05 08:49 UTC, mrtnmgs commented
Well, my PR was sloppy! Sorry about that. First time using the built-in github features, I was a bit disoriented.

2021-05-06 00:00 UTC, ericwbailey approved these changes
No worries! Happy to help, and congratulations on your first MDN contribution 🎉

2021-05-06 00:08 UTC, merged