Upgrade h2->h1, h3->h2, and so forth.
mdn/content pull request #4686
Opened 2021-05-04 01:09 UTC by kenrussell

Currently there are very few entries in the table of contents sidebar;
just "General Topics", "Shaders, Programs, and GLSL", etc., but there
are many individual pieces of advice. h2 entries show up in the TOC,
so promote everything one heading level to make it easier to see all
of the individual pieces of advice at a glance.

> What was wrong/why is this fix needed? (quick summary only)

Ease of browsing improvement.

> MDN URL of main page changed

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

> Issue number (if there is an associated issue)

None

> Anything else that could help us review it

Somewhat of a matter of opinion, but hoping reviewers will approve.

2021-05-04 21:34 UTC, jdashg approved these changes

2021-05-05 04:13 UTC, wbamberg commented
Thanks for this PR!

But I don't think we should do this. For one thing, the title "WebGL best practices" is also rendered as an H1, so now all the old H2 headings, which are logically underneath of the title, are now alongside it.

Also, only H2s are shown in the ToC, so now all the old top-level organization ("General Topics" etc) is now lost in the ToC.

Also though, and this isn't the fault of this change, the headings that are now in the ToC are so long and wordy that the ToC is really hard to scan like this. In general the headings could use some copy-editing, and sometimes seem like bits of the body text in a very big font. For example:

***************

<img width="953" alt="Screen Shot 2021-05-04 at 9 06 09 PM" src="https://user-images.githubusercontent.com/432915/117095925-a098f380-ad1c-11eb-8327-d072a56e214e.png">

***************

I'm sympathetic to the problem here and don't really understand why MDN ToCs only show H2 headings. One possible alternative:

* scrap the current H2 headings
* promote the current H3 headings to H2 _and rewrite them so they are short enough to be scannable_.

Or, if rewriting the heading is not practical, keep the current structure and have a list of all the individual pieces of advice at the start (essentially a hand-written, full width ToC).

2021-05-05 08:26 UTC, kenrussell commented
@wbamberg here's an update removing the h1 headings and editing down the new h2 headings to make them more scannable. Would you accept this version?

2021-05-05 17:12 UTC, wbamberg requested changes
Thanks for your updates, I like this version much more!

I had a few suggestions:
* some copy edits
* some changes to try to make the headings a bit more compact
* some headings that still want to be prose
* some changes to try to make headings be more consistently commands

But I'm not at all expert in this domain so if you think I've mangled the sense of any of this please let me know.

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Use_mipmaps_for_any_texture_youll_see_in_3d!">Use mipmaps for any texture you'll see in 3d!</h2>
```suggestion
<h2 id="Use_mipmaps_for_any_texture_youll_see_in_3d">Use mipmaps for any texture you'll see in 3d</h2>
```

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Support_for_float_textures_doesnt_mean_theyre_renderable">Support for float textures doesn't mean they're renderable!</h2>
```suggestion
<h2 id="Support_for_float_textures_doesnt_mean_theyre_renderable">Support for float textures doesn't mean they're renderable</h2>
```

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Support_for_float_textures_doesnt_mean_theyre_renderable">Support for float textures doesn't mean they're renderable!</h2>
Maybe "Don't assume you can render float textures" ?

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h3 id="Render-to-float32_doesnt_imply_float32-blending!">Render-to-float32 doesn't imply float32-blending!</h3>
```suggestion
<h3 id="Render-to-float32_doesnt_imply_float32-blending">Render-to-float32 doesn't imply float32-blending</h3>
```

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="invalidateFramebuffer">invalidateFramebuffer</h2>
```suggestion
<h2 id="Use_invalidateFramebuffer">Use invalidateFramebuffer</h2>
```
(or "Consider...")?

(the other H2s are generally in a command-form)

2021-05-05 17:12 UTC, wbamberg commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Non-blocking_async_data_readback">Non-blocking async data readback</h2>
```suggestion
<h2 id="Use_non-blocking_async_data_readback">Use non-blocking async data readback</h2>
```

(or "Consider...")?

2021-05-26 07:17 UTC, sideshowbarker commented
@kenrussell This PR seems to be waiting on your to review the commit suggestions from @wbamberg

2021-05-27 01:45 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Know_your_limits_and_extensions">Know your limits (and extensions)</h2>
Thanks, done in the forthcoming commit.

2021-05-27 01:45 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h3 id="Take_advantage_of_universally_supported_WebGL_1_extensions">Take advantage of universally supported WebGL 1 extensions</h3>
Done slightly differently in the forthcoming commit.

2021-05-27 01:45 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h3 id="And_to_a_lesser_degree_VAO_attachments_vertexAttribPointer_disableenableVertexAttribArray">And to a lesser degree, VAO attachments (vertexAttribPointer, disable/enableVertexAttribArray)</h3>
Done slightly differently in the forthcoming commit.

2021-05-27 01:45 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h3 id="Eagerly_lose_contexts_too">Eagerly lose contexts too</h3>
Done slightly differently in the forthcoming commit.

2021-05-27 01:46 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Prefer_builtins_instead_of_buiding_your_own">Prefer builtins instead of buiding your own</h2>
Thanks, done in the forthcoming commit.

2021-05-27 01:46 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Use_mipmaps_for_any_texture_youll_see_in_3d!">Use mipmaps for any texture you'll see in 3d!</h2>
Thanks, done in the forthcoming commit.

2021-05-27 01:46 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Support_for_float_textures_doesnt_mean_theyre_renderable">Support for float textures doesn't mean they're renderable!</h2>
Done slightly differently in the forthcoming commit.

2021-05-27 01:47 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h3 id="Render-to-float32_doesnt_imply_float32-blending!">Render-to-float32 doesn't imply float32-blending!</h3>
Thanks, done in the forthcoming commit.

2021-05-27 01:47 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="invalidateFramebuffer">invalidateFramebuffer</h2>
Thanks, done in the forthcoming commit.

2021-05-27 01:47 UTC, kenrussell commented on files/en-us/web/api/webgl_api/webgl_best_practices/index.html
> +<h2 id="Non-blocking_async_data_readback">Non-blocking async data readback</h2>
Thanks, done in the forthcoming commit.

2021-05-27 01:49 UTC, kenrussell commented
Sorry for the delay getting back to this and thanks for the editorial suggestions. Have addressed all of them, some slightly differently than suggested. How does this version look?

2021-05-27 03:42 UTC, wbamberg approved these changes
This looks great, thanks for the putting the work into this page, @kenrussell !

2021-05-27 03:42 UTC, merged