Pagemacro debugger
mdn/content pull request #4690
Opened 2021-05-04 02:01 UTC by hamishwillee

As per #3196 we are removing the Page macro (transclusion).

[Debugger Keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Keyboard_shortcuts) was transcluding two sections from [All keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts). 

This deletes [Debugger Keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Keyboard_shortcuts), and replaces the one link to it (from top level [The Firefox JavaScript Debugger](https://developer.mozilla.org/en-US/docs/Tools/Debugger)) with direct links to the same sections in the "All keyboard shortcuts". Also adds a redirect.

Other options I chose not to do were:
- Duplicate the table - decided better for maintenance to just have this once.
- Copy the debugger table into debug topic and link to it from "All keyboard shortcuts". Decided better to have all keyboard shortcuts in one place.

2021-05-04 03:15 UTC, hamishwillee commented on files/en-us/tools/style_editor/index.html
> +<p>See <a href="/en-US/docs/Tools/Keyboard_shortcuts#source_editor">All keyboard shortcuts > Source editor</a> for the default source editor shortcuts.</p>
@chrisdavidmills Here I couldn't copy the key mapping in because even though this is the ONLY place it was transcluded, the source editor can in theory apply to different types of source. So I chose to link back.

2021-05-04 04:56 UTC, hamishwillee commented on files/en-us/tools/tools_toolbox/index.html
> + <li>Select "Toggle Tools" from the Web Developer menu (under "Tools" on OS X and Linux, or "Firefox" on Windows)</li>
@chrisdavidmills This is the beginning of page https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox
I think it is a bit incorrect. I was referring to a wrench that no longer exists. Can you confirm that nowdays the ways to open the toolbar are:
- Keyboard keys
- Right click on any element and click inspect element
- On any platform (right?), use hamburger and do **Web Developer** - then do Toggle Tools or select specific tool.

There aren't any other ways right?

2021-05-04 04:57 UTC, hamishwillee commented on files/en-us/tools/eyedropper/index.html
> -<div>{{ToolsSidebar}}</div><div class="geckoVersionNote">
Note, FF31 irrelevant now.

2021-05-04 04:59 UTC, hamishwillee commented on files/en-us/tools/keyboard_shortcuts/index.html
> +<div class="notecard note">
@chrisdavidmills I couldn't remove this "Source Editor" section to another page because I don't think there is one. At the moment this is only linked by the Style editor section - is there another place you can edit things? I.e. is the specific or generic?

2021-05-04 05:01 UTC, hamishwillee commented on files/en-us/tools/keyboard_shortcuts/index.html
> +<p>See <a href="/en-US/docs/Tools/Eyedropper#keyboard_shortcuts">Eyedropper > Keyboard Shortcuts</a>.</p>
@chrisdavidmills Section above is about a tool called "Scratchpad". I can't find any docs on that so I can't move this. Any ideas on what it is for?

2021-05-04 11:27 UTC, chrisdavidmills requested changes
Not much to change here, from the outset. 

I think this way of doing it is ok, although it does make me wonder if it would be better to just have a single page with all shortcuts listed on it, and then link the landing pages for each tool to their specific section on that page for the tool-specific shortcuts?

Then someone who wants all the shortcuts in one place can just visit that page anyway?

Thoughts? I've not got a particularly strong opinion about this.

2021-05-04 11:27 UTC, chrisdavidmills commented on files/en-us/tools/tools_toolbox/index.html
> + <li>Select "Toggle Tools" from the Web Developer menu (under "Tools" on OS X and Linux, or "Firefox" on Windows)</li>
I think it would be better to list the three most common different ways, which you've basically got correct above, except that the hamburger menu option now seems to be Hamburger menu > More tools > Web developer tools.

2021-05-04 11:30 UTC, chrisdavidmills commented on files/en-us/tools/keyboard_shortcuts/index.html
> +<div class="notecard note">
I'm really not sure

2021-05-04 11:31 UTC, chrisdavidmills commented on files/en-us/tools/keyboard_shortcuts/index.html
> +<p>See <a href="/en-US/docs/Tools/Eyedropper#keyboard_shortcuts">Eyedropper > Keyboard Shortcuts</a>.</p>
This is gone; see https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools#scratchpad for details.

2021-05-04 22:28 UTC, hamishwillee commented
> I think this way of doing it is ok, although it does make me wonder if it would be better to just have a single page with all shortcuts listed on it, and then link the landing pages for each tool to their specific section on that page for the tool-specific shortcuts?

Thanks @chrisdavidmills. That was my concern, as in the description:

>  I am not certain this was the best decision, mostly because now the shortcuts are scattered. I do think that that if you're using web console, page inspector etc you probably are happy enough with the current way. If you think I'd be better off duplicating or linking to the All ... doc instead let me know - relatively easy fix.

I think I will revert this. I'll push back to draft and fix up on Friday.

2021-05-07 02:05 UTC, hamishwillee commented on files/en-us/tools/tools_toolbox/index.html
> + <li><a href="/en-US/docs/Tools/3D_View">3D view</a> (Removed in Firefox 47)</li>
@chrisdavidmills Should I just delete this link -  Firefox 47 was 2016? Note that the document could still exist, but you'd find it by search if you were on an old build

2021-05-07 02:11 UTC, hamishwillee commented on files/en-us/tools/tools_toolbox/index.html
> + <li>Select "Toggle Tools" from the Web Developer menu (under "Tools" on OS X and Linux, or "Firefox" on Windows)</li>
Done!

2021-05-07 02:14 UTC, hamishwillee commented
@peterbe Just FYI, this popped up - but the URL is not new.
![image](https://user-images.githubusercontent.com/5368500/117388265-cba66180-af2d-11eb-9d5e-2e20e84ad017.png)

2021-05-07 02:17 UTC, hamishwillee commented
@chrisdavidmills Ready for your re-review. 
As we discussed this inverts the changes - we now keep the single keyboard shortcut page. Where pagemacros were part of a page the inclusion was replaced with a link. Where there was a dedicated page for a specific tool's keyboard mappings I just deleted the page, and fixed up links to it from appropriate places.

2021-05-07 07:29 UTC, chrisdavidmills approved these changes
Nice work @hamishwillee ; I think this is now ready to merge.

2021-05-07 07:29 UTC, chrisdavidmills commented on files/en-us/tools/tools_toolbox/index.html
> + <li><a href="/en-US/docs/Tools/3D_View">3D view</a> (Removed in Firefox 47)</li>
Yeah, let's get rid of it. I'll do that now.

2021-05-07 07:36 UTC, merged

2021-05-07 17:03 UTC, peterbe commented
> @peterbe Just FYI, this popped up - but the URL is not new.
> ![image](https://user-images.githubusercontent.com/5368500/117388265-cba66180-af2d-11eb-9d5e-2e20e84ad017.png)

It gets confused because of this diff portion:
```diff
-<p><a name="mac-function-key-note">1. By default, on some Macs, the function key is remapped to use a special feature: for example, to change the screen brightness or the volume. See this </a><a href="https://support.apple.com/kb/HT3399">guide to using these keys as standard function keys</a>. To use a remapped key as a standard function key, hold the Function key down as well (so to open the Profiler, use <kbd>Shift</kbd> + <kbd>Function</kbd> + <kbd>F5</kbd>).</p>
+<p><a id="mac-function-key-note">1.</a> By default, on some Macs, the function key is remapped to use a special feature: for example, to change the screen brightness or the volume. See this <a href="https://support.apple.com/kb/HT3399">guide to using these keys as standard function keys</a>. To use a remapped key as a standard function key, hold the Function key down as well (so to open the Profiler, use <kbd>Shift</kbd> + <kbd>Function</kbd> + <kbd>F5</kbd>).</p>
```

I think the simple solution might be to change the messaging from:
```diff
-Note! This is a new URL 👀
+Note! This is maybe a new URL 👀
```

CC @escattone

2021-05-07 17:18 UTC, escattone commented
@peterbe 👍 I like your simple solution, but would suggest the wording `Note! This may be a new URL 👀`.

2021-05-07 17:23 UTC, peterbe commented
> @peterbe 👍 I like your simple solution, but would suggest the wording `Note! This may be a new URL 👀`.

https://github.com/mdn/yari/pull/3752