Remove spec tables in JS docs, and replace with macro call
mdn/content pull request #4691
Opened 2021-05-04 02:43 UTC by wbamberg

@Elchi3 , here's that PR.

It only looks at pages that already have the `browser-compat` front matter item.

I guess it won't be mergeable until after https://github.com/mdn/yari/pull/3518 gets deployed :).

2021-05-04 13:19 UTC, Elchi3 requested changes
Afaict only the lexical grammar table doesn't work.
For trailing commas, Mike submitted a BCD PR.
The rest looks really great 🎉

2021-05-04 13:19 UTC, Elchi3 commented on files/en-us/web/javascript/reference/lexical_grammar/index.html
> +{{Specifications}}
This one is a reference page and the compat table displays features grouped under "grammar", but the specification table is not loaded from BCD here because that "grammar" group itself has no spec_url.
Ideally, this page become an overview page of "grammar" features with sub pages for the features it currently talks about. That's a bit of work, so I propose to either leave in the old spec table, or to remove the entire specification section.

2021-05-04 16:29 UTC, wbamberg commented on files/en-us/web/javascript/reference/lexical_grammar/index.html
> +{{Specifications}}
I just undid this change for the lexical grammar page.

2021-05-04 16:49 UTC, Elchi3 approved these changes

2021-05-04 17:16 UTC, wbamberg commented
This seems to leave us with 10 pages under /JavaScript that use `{{SpecName}}`:

```
files/en-us/web/javascript//guide/regular_expressions/unicode_property_escapes/index.html:   <td>{{SpecName('ESDraft', '#sec-runtime-semantics-unicodematchproperty-p', 'RegExp: Unicode property escapes')}}</td>
files/en-us/web/javascript//guide/regular_expressions/groups_and_ranges/index.html:   <td>{{SpecName('ESDraft', '#sec-classranges', 'RegExp: Ranges')}}</td>
files/en-us/web/javascript//guide/regular_expressions/quantifiers/index.html:   <td>{{SpecName('ESDraft', '#sec-quantifier', 'RegExp: Quantifiers')}}</td>
files/en-us/web/javascript//guide/regular_expressions/character_classes/index.html:   <td>{{SpecName('ESDraft', '#sec-characterclass', 'RegExp: Character classes')}}</td>
files/en-us/web/javascript//guide/regular_expressions/assertions/index.html:   <td>{{SpecName('ESDraft', '#sec-assertion', 'RegExp: Assertions')}}</td>
files/en-us/web/javascript//data_structures/index.html:   <td>{{SpecName('ESDraft', '#sec-ecmascript-data-types-and-values', 'ECMAScript Data Types and Values')}}</td>
files/en-us/web/javascript//eventloop/index.html:   <td>{{SpecName('HTML WHATWG', 'webappapis.html#event-loops', 'Event loops')}}</td>
files/en-us/web/javascript//reference/iteration_protocols/index.html:   <td>{{SpecName('ESDraft', '#sec-iteration', 'Iteration')}}</td>
files/en-us/web/javascript//reference/lexical_grammar/index.html:			<td>{{SpecName('ESDraft', '#sec-ecmascript-language-lexical-grammar', 'Lexical Grammar')}}</td>
files/en-us/web/javascript//reference/strict_mode/index.html:   <td>{{SpecName('ESDraft', '#sec-strict-mode-code', 'Strict Mode Code')}}</td>
```

I wonder what we should do about them. It would be nice to retire SpecData.

2021-05-04 17:30 UTC, Elchi3 commented
I wonder if these pages could have the spec links in See also (or if we really want, in "Specifications") as list items.

In any case, I don't see a need that they should go through macro processing. It is just links...

2021-05-05 10:30 UTC, Elchi3 commented
Let's do this! :)

2021-05-05 10:31 UTC, merged

2021-06-22 08:35 UTC, teoli2003 commented
(For tracking purpose) This is part of #1146.