Move bind to different line for onclick1 method
mdn/content pull request #4730
Opened 2021-05-05 13:58 UTC by akanshgulati

Remove bind directly used in addEventListener method to avoid memory leak as removeListener on current method will not work

> What was wrong/why is this fix needed? (quick summary only)

> MDN URL of main page changed

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-05-05 18:00 UTC, Ryuno-Ki reviewed
I have some thoughts on this.

2021-05-05 18:00 UTC, Ryuno-Ki commented on files/en-us/web/api/eventtarget/addeventlistener/index.html
> +  // bind creates a new instance of the method and we can assign it to own method if `this` instance is fixed for the method
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind says

> The bind() method creates a new function that, when called, has its this keyword set to the provided value, with a given sequence of arguments preceding any provided when the new function is called.

A new instance would be `new MyClass()`. A method is often associated with a class.
So I'm a bit unhappy with the wording here, but can get the sentiment.

2021-05-11 20:03 UTC, Ryuno-Ki commented
@sideshowbarker Friendly ping

2021-05-12 07:19 UTC, sideshowbarker reviewed
I agree the existing example in the MDN article is not great — and after looking at it I feel like I’d kind of like to rewrite the whole thing — but the change in this PR as currently written doesn’t seem like it will result in greater clarity for readers about that example.

The text added also not doesn’t make clear what problem this change is solving; the issue description says, *Remove bind directly used in addEventListener method to avoid memory leak as removeListener on current method will not work* — but reading through the example, it’s not clear that’s what it’s doing. Maybe it needs some additional code that shows removeListener being called somewhere else outside that function, or something.

Otherwise, even though that existing example is maybe not so great, there’s not actually an bug in it. It will work. But the problem with it is what happens if/when somebody using that code wants to remove that event listener somewhere outside that function.

2021-05-14 16:09 UTC, akanshgulati commented on files/en-us/web/api/eventtarget/addeventlistener/index.html
> +  // bind creates a new instance of the method and we can assign it to own method if `this` instance is fixed for the method
@sideshowbarker I agree with the words not appropriate, I was more focused on stating the problem first. We can think of better comment and notification for the user to understand the reason.

2021-05-14 16:32 UTC, akanshgulati commented
@Ryuno-Ki Please check it again, I have tried to add more sense to that comment and description.

2021-05-14 18:48 UTC, Ryuno-Ki commented on files/en-us/web/api/eventtarget/addeventlistener/index.html
> +<p>The {{jsxref("Function.prototype.bind()")}} method creates a new function for a given function that lets you specify the value that
I get what you mean, but I think, it's not correct.

I am reading „creates a new function” as a return value of `bind`.
Instead, the function it's called on is mutated, i.e. I don't have to assign a return value.

2021-05-14 18:49 UTC, Ryuno-Ki reviewed
The example looks good now!
But we'll need to get the explanation right.

2021-05-19 06:54 UTC, sideshowbarker requested changes

2021-05-19 06:54 UTC, sideshowbarker commented on files/en-us/web/api/eventtarget/addeventlistener/index.html
> +  should be used as <code>this</code> for all calls. This easily bypass problems where it's unclear what <code>this</code> will be, depending on
```suggestion
<p>The {{jsxref("Function.prototype.bind()")}} method lets you establish a fixed 
  <code>this</code> context for all subsequent calls — bypassing problems where it's unclear what <code>this</code> will be, depending on
```

2021-05-19 06:54 UTC, sideshowbarker commented on files/en-us/web/api/eventtarget/addeventlistener/index.html
> +  // bind creates a new method with fixed `this` context assigned to onclick2
```suggestion
  // bind causes a fixed `this` context to be assigned to onclick2
```

2021-05-26 07:38 UTC, sideshowbarker approved these changes

2021-05-26 07:42 UTC, merged

2021-05-26 11:01 UTC, akanshgulati commented
@sideshowbarker Thanks for updating it, but the whole point of raising the issue was to avoid using `bind` directly inside the addEventListener callback method in the example.

2021-05-26 11:44 UTC, sideshowbarker commented
> @sideshowbarker Thanks for updating it, but the whole point of raising the issue was to avoid using `bind` directly inside the addEventListener callback method in the example.

I'm confused by that statement. Are you saying that the code in the patch I merged doesn't avoid using `bind` directly inside the addEventListener callback method in the example?

It's the same code you put into the patch, right? I didn't change the code, did I? My only suggestions and changes were to the comments. I didn't alter the code, and neither did any other reviewer, right?

So what are you saying?

Are you unhappy with the patch that got merged?

Do you want to revert the merge?

If not, what else would you like to have happen at this point?

2021-05-26 11:53 UTC, akanshgulati commented
@sideshowbarker Thanks for quick reply. Actually I checked the MR status coming as being merged and assumed that it has gone live too on production. My bad. Seems like the changes are merged but not went live yet.

2021-05-26 12:02 UTC, sideshowbarker commented
> @sideshowbarker Thanks for quick reply. Actually I checked the MR status coming as being merged and assumed that it has gone live too on production. My bad. Seems like the changes are merged but not went live yet.

Ah, ok, cool

Yeah, it can take up to 48 hours before the changes will show up in the production site.