Client hints updates
mdn/content pull request #4907
Opened 2021-05-11 08:08 UTC by hamishwillee

Fixes #1408

This does lots of other tidy up around the area.

2021-05-21 04:13 UTC, hamishwillee commented on files/en-us/web/http/headers/accept-ch-lifetime/index.html
> +<div>{{HTTPSidebar}}{{securecontext_header}}{{Deprecated_header}}</div>
Note, this is  non-standard. Last time I had both that and a deprecated header Chris suggested the deprecated header along covers that you should not use it.

2021-05-21 04:14 UTC, hamishwillee commented on files/en-us/web/http/headers/accept-ch/index.html
> -  <li>{{HTTPHeader("Accept-CH-Lifetime")}}</li>
FYI, removed as is deprecated.

2021-05-21 04:53 UTC, hamishwillee commented on files/en-us/glossary/forbidden_header_name/index.html
> + <li><code>Feature-Policy</code></li>
@Elchi3 How does one find out if something is a forbidden header name? Specifically, I checked the Fetch spec, and it matches the list here except it does not mention Feature-Policy. So how would I find out that Feature Policy is forbidden (I searched on forbidden in the permission-policy spec too and the term does not appear).

The main reason I ask is that the client hints all have "?" in the table for forbidden, so would help me to understand how you confirm their status.

Further, w.r.t. this doc, should I also add Permission-Policy?

2021-05-21 04:53 UTC, hamishwillee commented on files/en-us/web/http/headers/accept-ch/index.html
> +      <td>no</td>
Assumed - waiting on response to https://github.com/mdn/content/pull/4907/files#r636634168

2021-05-21 06:32 UTC, hamishwillee commented
Hi @Elchi3 
I'm trying to work out if we have missed any Client hint headers in docs.

We already document these headers:
- `Device-Memory`
- `Viewport-Width`
- `Width`
- `Save-Data`
  - [ ] Note, need to add that this is a low entropy hint (ie one that will likely be sent even if not requested using Accept-CH).
  - [ ] Note, need to document what low entropy hints are.
- (Deprecated and not in the spec) `Accept-CH-Lifetime`
- (Deprecated BCD and is in the current spec `DPR`)

I think we are missing these (do you know of any reason _not_ to include them)?:
- `Viewport-Height`
- `RTT`
- `Downlink`
- `ECT`

Further there are a bunch of new [User Agent Client Hints](https://wicg.github.io/ua-client-hints/#sec-ch-ua). These are defined in a "Draft Community Group Report, 4 May 2021" (i.e. not a standards track thingy yet). I haven't done a full check but at least some of these are [implemented in chrome 90](https://www.chromestatus.com/feature/5995832180473856) (and not yet in firefox https://bugzilla.mozilla.org/show_bug.cgi?id=935216#c67). What is our position on documenting these? (i.e. "do we document these"?):
- `Sec-CH-UA`  - low entropy hint. 
- `Sec-CH-UA-Arch`
- `Sec-CH-UA-Bitness`
- `Sec-CH-UA-Full-Version`
- `Sec-CH-UA-Mobile` - low entropy hint. 
- `Sec-CH-UA-Model`
- `Sec-CH-UA-Platform` - low entropy hint. 
- `Sec-CH-UA-Platform-Version`

Are there any others you know of?

Last of all, can you please review and merge this if it is OK? I'd like to do follow on fixes with bumping against other work people are doing :-)

2021-05-21 07:19 UTC, chrisdavidmills commented
Seems that @Elchi3 is a better choice of official reviewer for this one.

2021-05-24 20:33 UTC, jpmedley commented on files/en-us/glossary/forbidden_header_name/index.html
> + <li><code>Feature-Policy</code></li>
Actually it's `Permissions-Policy` with an 's'.

2021-05-26 23:05 UTC, hamishwillee commented
@Elchi3 (or @chrisdavidmills ) do you think you might have time to look at this today? Then I can continue the work tomorrow :-)

2021-05-27 17:49 UTC, Elchi3 commented
Sorry Hamish, I will try to get to it but probably not this week.

2021-05-28 00:37 UTC, hamishwillee commented
@Elchi3 Thank you - just wanted to make sure this was on your radar. Plenty to go on with :-)

FWIW An answer to the question above in https://github.com/mdn/content/pull/4907#issuecomment-845694070 is more useful than an actual review of the PR, as it would unblock me.

2021-05-31 14:38 UTC, Elchi3 commented
> I think we are missing these (do you know of any reason _not_ to include them)?:
> 
> * `Viewport-Height`
> * `RTT`
> * `Downlink`
> * `ECT`

These look good to me, although I'm not sure there is a (somewhat stable) specification for `Viewport-Height`. Maybe leave this out for now? (or maybe I'm missing something, pointers to specs appreciated).

> What is our position on documenting these? (i.e. "do we document these"?):
> * `Sec-CH-UA`  - low entropy hint.
> * `Sec-CH-UA-Arch`
> * `Sec-CH-UA-Bitness`
> * `Sec-CH-UA-Full-Version`
> * `Sec-CH-UA-Mobile` - low entropy hint.
> * `Sec-CH-UA-Model`
> * `Sec-CH-UA-Platform` - low entropy hint.
> * `Sec-CH-UA-Platform-Version`

Not sure who "ours" is in "our position". Mozilla thinks is it "non-harmful" in https://mozilla.github.io/standards-positions/
My feeling is we could document this now but maybe check what you know against https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions#when_to_document_new_technologies?

> Are there any others you know of?

There seem to be quite a few Client hints specs but it looks like you got the main ones here. Of course things are always in flux...

2021-05-31 14:46 UTC, Elchi3 commented on files/en-us/glossary/forbidden_header_name/index.html
> + <li><code>Feature-Policy</code></li>
I thought the list from the Fetch spec is exhaustive and new forbidden headers would start with `Sec-` but maybe that is a misunderstanding from my side.

I previously only confirmed these by looking at the Fetch spec...

2021-05-31 15:08 UTC, Elchi3 requested changes
Thanks for the PR! Some nits but LGTM otherwise

2021-05-31 15:08 UTC, Elchi3 commented on files/en-us/glossary/client_hints/index.html
> +  <p>Client hints can also be specified in HTML using the <code>meta</code> element with the <code><a href="/en-US/docs/Web/HTML/Element/meta#attr-http-equiv">http-equiv</a></code> attribute.</p>
```suggestion
  <p>Client hints can also be specified in HTML using the {{HTMLElement("meta")}} element with the <code><a href="/en-US/docs/Web/HTML/Element/meta#attr-http-equiv">http-equiv</a></code> attribute.</p>
```

2021-05-31 15:08 UTC, Elchi3 commented on files/en-us/glossary/client_hints/index.html
> + <li><a href="https://wicg.github.io/client-hints-infrastructure/">Client Hints Infrastructure, W3C Draft Community Group Report, 29 April 2021</a></li>
This now has May 17 as a date for me and probably changes frequently. I don't think it is useful to add this.
```suggestion
 <li><a href="https://wicg.github.io/client-hints-infrastructure/">Client Hints Infrastructure</a></li>
```

2021-05-31 15:08 UTC, Elchi3 commented on files/en-us/web/http/headers/dpr/index.html
> +  - Exerimental
Deprecated, non-standard, experimental? What is going on here?

2021-05-31 15:08 UTC, Elchi3 commented on files/en-us/web/http/headers/index.html
> + <dt>{{HTTPHeader("Accept-CH-Lifetime")}} {{experimental_inline}} {{deprecated_inline}}</dt>
No longer experimental?

2021-06-01 07:16 UTC, hamishwillee commented on files/en-us/glossary/forbidden_header_name/index.html
> + <li><code>Feature-Policy</code></li>
Thanks @Elchi3. The fetch spec being exhaustive seems a reasonable assumption. Just wasn't one I wanted to make. Happy to go with that now.

I wont add `Permissions-Policy` because I now know that this will be done "all in one go" later on.

2021-06-01 07:17 UTC, hamishwillee commented on files/en-us/web/http/headers/index.html
> + <dt>{{HTTPHeader("Accept-CH-Lifetime")}} {{experimental_inline}} {{deprecated_inline}}</dt>
@Elchi3 Still experimental but also deprecated.

2021-06-01 07:19 UTC, hamishwillee commented on files/en-us/web/http/headers/dpr/index.html
> +  - Exerimental
@Elchi3 This is a reflection of the BCD. 
![image](https://user-images.githubusercontent.com/5368500/120282482-7f1c2f00-c2fd-11eb-8e5b-cec30d3269be.png)

Previously experimental was omitted - so all I did was add the tag as well (this updates the sidebar with the icon).

2021-06-01 07:21 UTC, hamishwillee commented on files/en-us/web/http/headers/index.html
> + <dt>{{HTTPHeader("Accept-CH-Lifetime")}} {{experimental_inline}} {{deprecated_inline}}</dt>
For all of these I matched the docs to BCD. Note that arguably for page headers you only need one of these - the deprecated. But since I can't find a clear policy on that I haven't removed the other headers. I have been trying to discuss/get agreement on  that in the context of auto-generation of headers from BCD.

2021-06-01 07:24 UTC, hamishwillee commented
@Elchi3 I think I've either merged or answered your nits, and also fixed the conflicts. 

Thanks very much for the info on which headers to document. That will come as follow on.

2021-06-01 08:32 UTC, Elchi3 commented on files/en-us/web/http/headers/index.html
> + <dt>{{HTTPHeader("Accept-CH-Lifetime")}} {{experimental_inline}} {{deprecated_inline}}</dt>
Thanks for matching BCD, let's go with this then.

2021-06-01 08:32 UTC, Elchi3 approved these changes
Thanks Hamish! 🎉

2021-06-01 08:32 UTC, merged