Add to Map vs Object comparison table
mdn/content pull request #4923
Opened 2021-05-11 18:48 UTC by erikleo

> What was wrong/why is this fix needed? (quick summary only)
The comparison table for Map vs Object shows only advantages of Map over JavaScript object which could cause the reader think that Map is superior to object in every way, which is not true.  Adding an significant difference between the 2 data types in regard to serialization that may be important when the reader is choosing between to two.

> MDN URL of the main page changed
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-05-12 08:26 UTC, sideshowbarker requested changes

2021-05-12 08:26 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/map/index.html
> +        <p>No native serialzation.</p>
```suggestion
        <p>No native support for serialization or parsing.</p>
        <p>(But you can build your own serialization and parsing support for <code>Map</code> by using {{jsxref("JSON.stringify()")}} with its <em>replacer</em> argument, and by using {{jsxref("JSON.parse()")}} with its <em>reviver</em> argument. See the Stack Overflow question <a href="https://stackoverflow.com/q/29085197/">How do you JSON.stringify an ES6 Map?</a>).</p>
```

2021-05-12 13:48 UTC, erikleo commented
lgtm

2021-05-13 02:55 UTC, sideshowbarker approved these changes

2021-05-13 03:03 UTC, merged

2021-05-13 03:03 UTC, sideshowbarker commented
Erik, thanks much for this refinement, and congrats on landing your first docs change here — welcome aboard 🎉