Correct description of transform-origin
mdn/content pull request #4925
Opened 2021-05-11 20:58 UTC by brady-ds

* **Problem:** The description of `transform-origin` should explain that, effectively, the transform origin is translated to (0, 0), the CSS `transform` property is applied so that those transformations are about the transform origin, and then the transform origin is translated back to its original location.  Instead, the description says the reverse: (0, 0) is translated to the transform origin, the `transform` property is applied, and then (0, 0) is restored back to its original location.  This would incorrectly make the transformations apply around the point mirroring the transform origin.  The code example immediately following also contradicts the wrong description.

* **URL:** <https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin>

* **Issue:** None

2021-05-12 21:39 UTC, ericwbailey requested changes

2021-05-12 21:39 UTC, ericwbailey commented on files/en-us/web/css/transform-origin/index.html
> +<p>This property is applied by first translating the element by the negated value of the property, then applying the element's transform, then translating by the property value. This means, this defi
I don't think "by the negated value of the property" is clear enough. Can we rephrase it to be more descriptive, like in your PR description?

2021-05-12 22:17 UTC, brady-ds commented
Besides expanding the indicated paragraph as requested, I also added [b0382b2](https://github.com/mdn/content/pull/4925/commits/b0382b29c62f5470af7d52b5934071d99a68c298) to clean up language in the prior paragraph that was inconsistent with the property name and therefore inconsistent with the text I added.  Since it could be considered an unrelated correction, please let me know if you would prefer it as a separate PR.

2021-05-19 00:06 UTC, ericwbailey requested changes
This is great, thank you. One last little tweak, and then I think this is good to go!

2021-05-19 00:06 UTC, ericwbailey commented on files/en-us/web/css/transform-origin/index.html
> +<p>where, reading from right to left, <code>translate(100%, -50%)</code> is the translation to bring the transform origin to the true origin, <code>rotate(45deg)</code> is the original transformation
```suggestion
<p>Reading from right to left, <code>translate(100%, -50%)</code> is the translation to bring the transform origin to the true origin, <code>rotate(45deg)</code> is the original transformation, and <code>translate(-100%, 50%)</code> is the translation to restore the transform origin to its original location.</p>
```

2021-05-23 21:18 UTC, ericwbailey approved these changes
Wonderful. Thank you for your effort on this, and apologies for the delay in getting back to you. Also, congrats on your first MDN contribution!

2021-05-23 21:20 UTC, merged