close #4957 by linking to slice() from splice() pg
mdn/content pull request #4976
Opened 2021-05-13 21:37 UTC by hamirmahal

This commit tries to close https://github.com/mdn/content/issues/4957.

> What was wrong/why is this fix needed? (quick summary only)

I think it would be helpful to readers if we linked to [`Array.prototype.slice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) from [`Array.prototype.splice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)'s page since a reader might look for one while on the page of the other.
> MDN URL of the main page changed

[`Array.prototype.splice()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)
> Issue number (if there is an associated issue)

#4957 
> Anything else that could help us review it

2021-05-13 22:56 UTC, wbamberg requested changes
Thanks @hamirmahal ! I agree that this is a nice cross-link, but I had some editorial comments (as a rule, I like to keep docs concise and direct).

2021-05-13 22:56 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/splice/index.html
> +    href="https://en.wikipedia.org/wiki/In-place_algorithm">in place</a>. If you would like to access part of an array without modifying it, please see {{jsxref("Array.prototype.slice()", "slice()")}
```suggestion
    href="https://en.wikipedia.org/wiki/In-place_algorithm">in place</a>. To access part of an array without modifying it, see {{jsxref("Array.prototype.slice()", "slice()")}}.</p>
```

2021-05-14 20:09 UTC, hamirmahal commented
You're welcome, @wbamberg! I like your suggestion and committed it. Thanks for the improvement!

2021-05-14 22:59 UTC, wbamberg approved these changes
👍 looks good, thank you @hamirmahal !

2021-05-14 22:59 UTC, merged

2021-05-15 18:56 UTC, hamirmahal commented
You're welcome, @wbamberg! Happy I could help.