Update index.html
mdn/content pull request #500
Opened 2020-12-20 21:44 UTC by Zearin

Minor markup tweaks

2020-12-21 19:38 UTC, Rumyra requested changes
Thanks @Zearin ! A couple of review points :)

2020-12-21 19:38 UTC, Rumyra commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">let domRect = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
By and large the syntax section of pages isn't a precise reflection of js, more how something is to be expected to be used with correctly names params and returns. Also by adding `let` it implies `const` isn't applicable (whereas it is). However edits here highlight the vars that are missing:

```suggestion
<pre class="syntaxbox notranslate">var <var>domRect</var> = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
```

2020-12-21 19:38 UTC, Rumyra commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> + <dd>An object specifying the location and dimensions of a rectangle. All properties default to <code>0</code>. The properties are:
Convention has it nested extra options, or object properties such as this are held in a `ul` within the `dd` - however this does highlight the original `ul` was not inside the `dd`

```suggestion
<dd>An object specifying the location and dimensions of a rectangle. All properties default to <code>0</code>. The properties are:
  <ul>
     <li><code>x</code>: The coordinate of the left side of the rectangle.</li>
     <li><code>y</code>: The coordinate of the top side of the rectangle.</li>
     <li><code>width</code>: The width of the rectangle.</li>
     <li><code>height</code>: The height of the rectangle.</li>
   </ul>
  </dd>

2020-12-21 21:50 UTC, Zearin commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">let domRect = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
I just remember seeing “`let` is the new `var`” everywhere when the ES6 syntax started to become available.  I remember reading that let follows more sensible rules for scope, and so it should be preferred over `var`.  That’s all I was going for.  I wasn’t intending to imply anything about `const`.

2020-12-21 21:54 UTC, Zearin commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">let domRect = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
(I can’t believe I missed wrapping `domRect` in an HTML `var` element, though! Thanks.)

So, I forgot to ask for clarity: **Is it really preferred on MDN to use `var`?**  

I was under the (strong) impression that it should be avoided (except for things like legacy code, blah blah, where the different scoping rules might introduce unintended consequences...).

2020-12-22 14:01 UTC, Rumyra commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">let domRect = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
So syntax boxes are in a weird category of being not quite the js you would write, but an example of usage. We probably do need to clarify precise guidelines (and in doing so conventions we use now could change).

In reference to `var` vs `let` vs `const` when it comes to examples (as in the page section examples) which ever seems appropriate is absolutely fine...

And there's every chance we'll change the syntax box conventions in the future, but for now it's probably best to stick with `var` anticipating a wider discussion :)

2020-12-26 19:22 UTC, Zearin commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">let domRect = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
Thanks, @Rumyra!

2020-12-29 14:20 UTC, Rumyra approved these changes

2020-12-29 14:20 UTC, Rumyra commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> + <dl>
It seems rather than over writing your `dl` @Zearin the review has included both yours and mine amends here... I'm going to see if I can rectify my end 👍

2020-12-29 14:20 UTC, Rumyra commented on files/en-us/web/api/domrectreadonly/fromrect/index.html
> +<pre class="syntaxbox notranslate">var <var>domRect</var> = DOMRectReadOnly.fromRect(<var>rectangle</var>)</pre>
This is perfect thanks

2020-12-29 14:20 UTC, merged

2020-12-29 14:21 UTC, Rumyra commented
All done - thanks so much @Zearin 🎉