fix: document cookie live examples
mdn/content pull request #5031
Opened 2021-05-16 08:59 UTC by shuta13

> What was wrong/why is this fix needed? (quick summary only)

I have made some fixes to live examples in `Document.cookie`

> MDN URL of the main page changed

<https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie>

> Issue number (if there is an associated issue)

https://github.com/mdn/content/issues/3288

> Anything else that could help us review it

- `Samesite` specification changed in Chromium : https://web.dev/samesite-cookies-explained/
- Live samples of `SameSite=None; Secure` on [glitch.com](https://glitch.com/) : https://pointy-flannel-mambo.glitch.me

2021-05-19 22:27 UTC, wbamberg requested changes
Thanks @shuta13 for this PR! Having educated myself a bit on this, I think this looks great.

A few things:

* I guess we need `SameSite=None` because the live sample is hosted in an iframe, so accessing the cookie is cross-origin? If so, I think it would be worth adding a comment where we are setting these values, because we don't want people just copying them without thinking about it. For example:

```js
// Note that we are setting `SameSite=None;` in this example because the example
// needs to work cross-origin.
// It is more common not to set the `SameSite` attribute, which results in the default,
// and more secure, value of `SameSite=Lax;`
document.cookie = "name=oeschger; SameSite=None; Secure";
document.cookie = "favorite_food=tripe; SameSite=None; Secure</span>";
```

?

* I don't think we need the "ES5" versions. The features in the ES2016 versions have been supported long enough.

* the new live samples use `console.log` to show the output. I think it's nice if live samples can show output without the reader having to open the devtools. The easy way to do this (and probably the best way here, since it's consistent with the others in this page) is to use `alert()`, but usually I prefer to have some bit of UI in the example where I can show the output.

2021-05-21 05:30 UTC, shuta13 commented
@wbamberg 

Thanks for the review! 

> ? or something, anyway, that will let people know about this.

I see. I found it's important to inform the viewers. I'll add comments as you suggested!

> I don't think we need the "ES5" versions. The features in the ES2016 versions have been supported long enough. This also implies you don't need t call the ES2016 version things like "checkACookieExistsES2016", you can just call it "checkACookieExists".

Okay, I'll remove ES5 syntax and rename then function.

> the new live samples use console.log to show the output. I think it's nice if live samples can show output without the reader having to open the devtools. The easy way to do this (and probably the best way here, since it's consistent with the others in this page) is to use alert(), but usually I prefer to have some bit of UI in the example where I can show the output.

I also think that using `console.log` is not a good idea because it requires opening devtools... 

I would like to try something other than using `alert()` , what would be the best implementation? I would like to avoid creating modals as there are many things to consider and they are difficult to control...

2021-05-26 07:47 UTC, sideshowbarker commented
@shuta13 This PR seems to be waiting at least in part for you review/accept the commit suggestions from @wbamberg

2021-05-26 10:04 UTC, shuta13 reviewed
@wbamberg cc @sideshowbarker 
Sorry for the late reply.
I have made some changes based on what you have pointed out.
Please check it out.

2021-05-26 10:04 UTC, shuta13 commented on files/en-us/web/api/document/cookie/index.html
> +&lt;div&gt;
I thought of a UI like the one in the image below to avoid using `console.log`.

![ui-to-replace-console-log](https://user-images.githubusercontent.com/38882716/119641657-dbda9e00-be54-11eb-8ebb-750ce516a88d.png)

2021-05-26 19:11 UTC, wbamberg requested changes
Thanks for the updates @shuta13 ! I like them but had a few more comments.

2021-05-26 19:11 UTC, wbamberg commented on files/en-us/web/api/document/cookie/index.html
> +&lt;div&gt;
I like this, but it should also have a "Reset" button that just clears the. output. Otherwise it looks like the example only works once.

2021-05-26 19:11 UTC, wbamberg commented on files/en-us/web/api/document/cookie/index.html
> +  Check a cookie existence
```suggestion
  Check a cookie exists
```

2021-05-26 19:11 UTC, wbamberg commented on files/en-us/web/api/document/cookie/index.html
> +    output.textContent = '>> The cookie "reader" has "1" for value'
```suggestion
    output.textContent = '>> The cookie "reader" has a value of "1"'
```

2021-05-26 19:11 UTC, wbamberg commented on files/en-us/web/api/document/cookie/index.html
> +&lt;div&gt;
Also, for consistency in the page, you might consider replacing the `alert` calls in the other examples with your implementation here.

2021-05-27 03:17 UTC, shuta13 reviewed
@wbamberg 

Thank you for the comments.
Please check back as I have made some updates based on these.

2021-05-27 03:17 UTC, shuta13 commented on files/en-us/web/api/document/cookie/index.html
> +&lt;button onclick="clearOutputCookies()"&gt;
I've added a button for "Reset" as pointed out in https://github.com/mdn/content/pull/5031#discussion_r640049153

I thought that "Reset" might be interpreted as resetting the cookie, so I chose the name "Clear".

2021-05-27 04:08 UTC, wbamberg approved these changes
Looks great, thanks for all your work on this page, @shuta13 !

2021-05-27 04:08 UTC, merged

2021-05-28 03:56 UTC, sideshowbarker commented
@shuta13 Thanks much, and congrats on landing your first docs change here — welcome aboard 🎉