fix: link title matching text
mdn/content pull request #507
Opened 2020-12-20 23:40 UTC by nschonni

Find: ` title="(\w*)">\1</a>`
Replace: `>$1</a>`

2020-12-20 23:54 UTC, vkWeb requested changes

2020-12-20 23:54 UTC, vkWeb commented on files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.html
> + Secondly, signals must be <a href="https://en.wikipedia.org/wiki/Low-pass_filter" title="Low-pass filter">low-pass filtered</a> before sampling, otherwise <a href="https://en.wikipedia.org/wiki/Alia
Lowercase `A` in Aliasing.

2020-12-20 23:54 UTC, vkWeb commented on files/en-us/web/api/window/index.html
> + <dd><code>DOMParser</code> can parse XML or HTML source stored in a string into a DOM <a href="/en-US/docs/DOM/document">document</a>. <code>DOMParser</code> is specified in <a href="https://w3c.git
Uppercase d in document needed.

2020-12-20 23:54 UTC, vkWeb commented on files/en-us/glossary/canvas/index.html
> +<p><span class="seoSummary">The <strong>canvas element</strong> is part of <a href="https://en.wikipedia.org/wiki/HTML5">HTML5</a> and allows for dynamic, <a href="https://en.wikipedia.org/wiki/Scrip
please lowercase b in Bitmap.

2020-12-20 23:54 UTC, vkWeb commented on files/en-us/learn/css/howto/css_faq/index.html
> +<p>When multiple rules apply to a certain element, the rule chosen depends on its style <a href="/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance#Specificity">Specificity</a>. Inline
Lowercase S in Specificity.

2020-12-21 00:03 UTC, nschonni commented on files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.html
> + Secondly, signals must be <a href="https://en.wikipedia.org/wiki/Low-pass_filter" title="Low-pass filter">low-pass filtered</a> before sampling, otherwise <a href="https://en.wikipedia.org/wiki/Alia
Good call, i'll see if I can do a backwards match for the regex to keep the casing

2020-12-21 00:08 UTC, nschonni commented
@vkWeb was able to change the regex to use the link text for the final replacement so it just drops the `title`

2020-12-21 07:08 UTC, vkWeb approved these changes
Now this looks good. As always nice work, thanks @nschonni. :smile:

2020-12-21 07:37 UTC, chrisdavidmills approved these changes

2020-12-21 07:38 UTC, chrisdavidmills commented
Thanks @nschonni , and thanks @vkWeb for the review!

2020-12-21 07:38 UTC, merged