Demix ChildNode.remove to Element, CharacterData, DocumentType
mdn/content pull request #5088
Opened 2021-05-18 12:29 UTC by Elchi3

The abstract mixin page
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

becomes
https://developer.mozilla.org/en-US/docs/Web/API/Element/remove
https://developer.mozilla.org/en-US/docs/Web/API/CharacterData/remove
https://developer.mozilla.org/en-US/docs/Web/API/DocumentType/remove

IDL
https://dom.spec.whatwg.org/#interface-childnode

BCD
https://github.com/mdn/browser-compat-data/pull/10506

2021-05-18 12:47 UTC, chrisdavidmills requested changes
A few minor comments, but nothing much. Nice work @Elchi3 !

2021-05-18 12:47 UTC, chrisdavidmills commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/ChildNode/remove	/en-US/docs/Web/API/Element/remove
These redirects look duplicated; remove one?

2021-05-18 12:47 UTC, chrisdavidmills commented on files/en-us/web/api/characterdata/remove/index.html
> +<h2 id="Example">Example</h2>
Horribly nitpicky, but shouldn't this heading be "Examples", for consistency with other reference pages?

2021-05-18 12:47 UTC, chrisdavidmills commented on files/en-us/web/api/documenttype/remove/index.html
> +<h2 id="Example">Example</h2>
"Examples"?

2021-05-18 12:47 UTC, chrisdavidmills commented on files/en-us/web/api/documenttype/remove/index.html
> +<p>The <code><strong>DocumentType.remove()</strong></code> method removes a document's <code>doctype</code>.</p>
Why would you ever want to do this? I do wonder if it's possible to add a line or two describing why you might want to do this, if such information is available.

2021-05-18 12:47 UTC, chrisdavidmills commented on files/en-us/web/api/element/remove/index.html
>  <h2 id="Example">Example</h2>
"Examples"?

2021-05-19 14:12 UTC, Elchi3 commented on files/en-us/_redirects.txt
> +/en-US/docs/Web/API/ChildNode/remove	/en-US/docs/Web/API/Element/remove
They aren't duplicate actually (dot vs slash), but some other stuff was redirecting that shouldn't anymore now that the CharacterData and DocumentType pages exist. Fixed that.

2021-05-19 14:13 UTC, Elchi3 commented on files/en-us/web/api/documenttype/remove/index.html
> +<p>The <code><strong>DocumentType.remove()</strong></code> method removes a document's <code>doctype</code>.</p>
Not sure why anyone wants to do it, but if it is because of getting to quirks mode, I've added a note to the doc saying that this is a bad idea.

2021-05-21 08:21 UTC, chrisdavidmills approved these changes
OK, looking good to go. Nice one @Elchi3 !

2021-05-21 08:21 UTC, merged