Document the href attributes on interfaces including SVGURIReference
mdn/content pull request #5112
Opened 2021-05-19 09:58 UTC by foolip

Follow-up to https://github.com/mdn/content/pull/5111.

2021-05-19 09:58 UTC, foolip commented
There was an impressive diversity of style here, and I tried to match the local style in each file, but probably failed in some case.

2021-05-19 17:40 UTC, jpmedley requested changes
Thank you for doing this. I found a few typos.

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svggradientelement/index.html
> + <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to the {{SVGAttr("gradientUnits")}} attribute on the given element. Takes one of the constants defined in {{domxref("SVGUnitTypes")}}.</dd>
```suggestion
 <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to the {{SVGAttr("gradientUnits")}} attribute on the given element. This property takes one of the constants defined in {{domxref("SVGUnitTypes")}}.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svggradientelement/index.html
> + <dd>An {{domxref("SVGAnimatedTransformList")}} corresponding to attribute {{SVGAttr("gradientTransform")}} on the given element.</dd>
```suggestion
 <dd>An {{domxref("SVGAnimatedTransformList")}} corresponding to the {{SVGAttr("gradientTransform")}} attribute on the given element.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svggradientelement/index.html
> + <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to attribute {{SVGAttr("spreadMethod")}} on the given element. One of the spread method types defined on this interface.</dd>
```suggestion
 <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to the {{SVGAttr("spreadMethod")}} attribute on the given element. One of the spread method types defined on this interface.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svgaelement/index.html
> + <dd>Is an {{domxref("SVGAnimatedString")}} that reflects the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute.</dd>
```suggestion
 <dd>Aan {{domxref("SVGAnimatedString")}} that reflects the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svgfilterelement/index.html
> + <dd>An {{domxref("SVGAnimatedString")}} that corresponds the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute of the given {{SVGElement("filter")}} element.</dd>
```suggestion
 <dd>An {{domxref("SVGAnimatedString")}} that corresponds to the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute of the given {{SVGElement("filter")}} element.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svggradientelement/index.html
> + <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to the {{SVGAttr("gradientUnits")}} attribute on the given element. Takes one of the constants defined in {{domxref("SVGUnitTypes")}}.</dd>
```suggestion
 <dd>An {{domxref("SVGAnimatedEnumeration")}} corresponding to the {{SVGAttr("gradientUnits")}} attribute on the given element. This property takes one of the constants defined in {{domxref("SVGUnitTypes")}}.</dd>
```

2021-05-19 17:40 UTC, jpmedley commented on files/en-us/web/api/svgmpathelement/index.html
> +  <dd>An {{domxref("SVGAnimatedString")}} that corresponds the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute of the given {{SVGElement("mpath")}} element.</dd>
```suggestion
  <dd>An {{domxref("SVGAnimatedString")}} that corresponds to the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute of the given {{SVGElement("mpath")}} element.</dd>
```

2021-05-19 19:43 UTC, foolip commented on files/en-us/web/api/svgaelement/index.html
> + <dd>Is an {{domxref("SVGAnimatedString")}} that reflects the {{SVGAttr("href")}} or {{SVGAttr("xlink:href")}} attribute.</dd>
I stuck to the existing convention in this file. I don't like it, but there are quite a lot of or "Is a/an ..." like this across more than 100 files, and I didn't want to fix them all.

2021-05-19 19:47 UTC, foolip commented
Thanks @jpmedley, changes applied!

2021-05-20 14:14 UTC, jpmedley approved these changes

2021-05-20 14:14 UTC, merged