Drop SVG attribute counts
mdn/content pull request #5148
Opened 2021-05-20 13:01 UTC by ddbeck

Never count attributes again! This is a follow up to https://github.com/mdn/content/pull/5147. It changes all the remaining cases of:

> X elements are using this attribute: [long list of attribute refs]

to

> These elements use this attribute: [long list of attribute refs].

2021-05-20 13:20 UTC, chrisdavidmills approved these changes
Yup yup! Nice work.

2021-05-20 13:20 UTC, chrisdavidmills commented
oop, little conflict to fix.

2021-05-20 18:13 UTC, wbamberg commented
![SpanishInquisitionCantCount](https://user-images.githubusercontent.com/432915/119028268-1d9eac80-b95c-11eb-947b-531ce6e4721b.gif)

I hate to be picky, but to me:

 > These elements use this attribute:

... doesn't read as well as:

> The following elements use this attribute:

Something about "these/this". Is that just me?

2021-05-20 21:42 UTC, ddbeck commented
@wbamberg 

> Something about "these/this". Is that just me?

No, not just you. I thought it was slightly awkward when I wrote it, but it was a solution (to my problem of not wanting to count more things than I have fingers) that could be achieved through an uncomplicated regular expression.

The _right_ way to do this is probably to make a section for this, like the permitted property lists we came up for the CSS recipe:

> ## Applicable elements
>
> You can use this attribute with the following SVG elements:
>
> - `elem1`
> - `elem2`
> - …
> - `elemN`

Or for cases where all elements are supported:

> ## Applicable elements
>
> You can use this attribute with any SVG element.

2021-05-20 21:47 UTC, wbamberg commented
> The right way to do this is probably to make a section for this, like the permitted property lists we came up for the CSS recipe:

Yes, I agree (and had the same thought, after commenting of course).

2021-05-20 21:50 UTC, ddbeck commented
I could do that with this PR, unless you think we ought to put it up for discussion more widely first.

2021-05-20 22:34 UTC, wbamberg commented
@Rumyra , @Elchi3 , are you +1 on Daniel making the change described in https://github.com/mdn/content/pull/5148#issuecomment-845496959 ? Are there other people we should ask here?

2021-05-21 06:46 UTC, Elchi3 commented
Sounds good to me!

(I will say here that I'm not a big fan of attribute reference pages. I think if I would write SVG docs from scratch, attribute pages would sit inline or under their element page. Yes, this might mean some duplication, but at least I could then document the attribute in context of its element. I could be convinced if readers would search for attributes on their own specifically, but right now I'm not. I think readers will want to use attributes in the context of an element, so 🤷 )

2021-05-21 14:18 UTC, Rumyra commented
Yeh looks good to me :)

2021-06-12 22:47 UTC, sideshowbarker commented
@ddbeck This status of this PR seems to be that it’s waiting for the change described in https://github.com/mdn/content/pull/5148#issuecomment-845496959 to be made, right?

2021-06-14 11:41 UTC, ddbeck commented
@sideshowbarker Yes, that's correct and this PR slipped my mind. I'll try to finish this today (but definitely by the end of my day tomorrow).

2021-06-15 14:53 UTC, ddbeck commented
OK, I kinda regret that I spent as much time on this as I have today, but I've now turned these very long sentences into actual lists or a paragraph saying, "You can use this attribute with any SVG element." I tried to make this as regular as I could, across all of the SVG attribute pages. As you can see, it's a huge diff. I'm sorry.

There is something I haven't done: created a section for "Applicable elements", as previously discussed. That's kinda hard to do in a quick-and-dirty way, particularly because it's underspecified. I don't know where in the outline the section should go and I don't think the page type is sufficiently well-defined trust that I could insert the section in the right spot.

Honestly, I don't think it's a good use of my time to sort this out page-by-page, so I propose leaving it at this. Like @Elchi3 says, these pages might not be that interesting to readers anyway. If y'all think this is good enough, let's merge this (barring any immediate brokenness to deal with) and move on.

2021-06-15 19:18 UTC, wbamberg commented on files/en-us/web/svg/attribute/kernelunitlength/index.html
> +  <li>{{SVGElement("feConvolveMatrix")}}, {{SVGElement("feDiffuseLighting")}}</li>
```suggestion
  <li>{{SVGElement("feConvolveMatrix")}}</li>
  <li>{{SVGElement("feDiffuseLighting")}}</li>
```

2021-06-15 19:57 UTC, wbamberg requested changes
Thanks Daniel, for your work on this. I found a few formatting typos.

While most of these pages have this bit at the start, before the example, a few have placed it later. I found:

https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/mask
https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox
https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/pointer-events
https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/transform
https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/color-profile

It's a little weird how these pages plunge right from this into the example, but when we remove all the `div id=` from the live samples we will want to add "Example" H2 headings, and that should help these pages communicate their organization better.

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/stroke-dasharray/index.html
> -<div class="threecolumns">
Needs to remove the closing /div

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/strikethrough-thickness/index.html
> -<ul>
This should delete the "Elements" H2 and the para preceding this list.

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/vector-effect/index.html
> +  <li>{{SVGElement("textPath")}} {{SVGElement("tspan")}}</li>
```suggestion
  <li>{{SVGElement("textPath")}}</li>
  <li>{{SVGElement("tspan")}}</li>
```

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/flood-color/index.html
> +  <li>{{SVGElement("feFlood")}} and {{SVGElement("feDropShadow")}}</li>
```suggestion
  <li>{{SVGElement("feFlood")}}</li>
  <li>{{SVGElement("feDropShadow")}}</li>
```

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/from/index.html
> +  <li>{{SVGElement("animate")}}, {{SVGElement("animateColor")}}, {{SVGElement("animateMotion")}}</li>
```suggestion
  <li>{{SVGElement("animate")}}</li>
  <li>{{SVGElement("animateColor")}}</li>
  <li>{{SVGElement("animateMotion")}}</li>
```

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/in2/index.html
> +  <li>{{SVGElement("feBlend")}}, {{SVGElement("feComposite")}} and {{SVGElement("feDisplacementMap")}}</li>
```suggestion
  <li>{{SVGElement("feBlend")}}</li>
  <li>{{SVGElement("feComposite")}}</li>
  <li>{{SVGElement("feDisplacementMap")}}</li>
```

2021-06-15 19:57 UTC, wbamberg commented on files/en-us/web/svg/attribute/xlink_colon_href/index.html
> +  <li>{{SVGElement("use")}}}</li>
```suggestion
  <li>{{SVGElement("use")}}</li>
```

2021-06-18 16:56 UTC, ddbeck commented on files/en-us/web/svg/attribute/strikethrough-thickness/index.html
> -<ul>
Fixed with c89511d71abd9215abed41e0370e99088f4d6a57

2021-06-18 16:56 UTC, ddbeck commented on files/en-us/web/svg/attribute/stroke-dasharray/index.html
> -<div class="threecolumns">
Fixed with 96599d0d99f5f237466e0e18d86f764adefd9fac

2021-06-18 16:59 UTC, ddbeck commented
@wbamberg Thanks for the review! Fixes applied and marked resolved, where it was obvious. One outstanding question for you:
 
> While most of these pages have this bit at the start, before the example, a few have placed it later. I found:
> 
> https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/mask
> https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox
> https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/pointer-events
> https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/transform
> https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/color-profile
> 
> It's a little weird how these pages plunge right from this into the example, but when we remove all the `div id=` from the live samples we will want to add "Example" H2 headings, and that should help these pages communicate their organization better.

I wasn't quite clear on what steps you thought I should take here. Should I make all of the pages like the links above? Or change the linked pages to be like the others? Or something else?

2021-06-18 17:18 UTC, wbamberg commented
> @wbamberg Thanks for the review! Fixes applied and marked resolved, where it was obvious. One outstanding question for you:
> 
> > While most of these pages have this bit at the start, before the example, a few have placed it later. I found:
> > https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/mask
> > https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/viewBox
> > https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/pointer-events
> > https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/transform
> > https://pr5148.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute/color-profile
> > It's a little weird how these pages plunge right from this into the example, but when we remove all the `div id=` from the live samples we will want to add "Example" H2 headings, and that should help these pages communicate their organization better.
> 
> I wasn't quite clear on what steps you thought I should take here. Should I make all of the pages like the links above? Or change the linked pages to be like the others? Or something else?

I think that those 5 cases should follow the pattern of the other pages, and include this "You can use this attribute" bit at the start, immediately after the introductory paragraph.

Sorry to be unclear, this bit of my comment:

> > It's a little weird how these pages plunge right from this into the example, but when we remove all the `div id=` from the live samples we will want to add "Example" H2 headings, and that should help these pages communicate their organization better.

...was more of a general comment about all these pages, and not a thing I expect you to do anything about in this PR.

2021-06-18 17:28 UTC, ddbeck commented
> I think that those 5 cases should follow the pattern of the other pages, and include this "You can use this attribute" bit at the start, immediately after the introductory paragraph.

Thank you for the clarification. Done! ✅

2021-06-18 17:34 UTC, wbamberg approved these changes
👍 Thanks Daniel!

2021-06-18 17:34 UTC, merged