Adds InputDeviceInfo
mdn/content pull request #5152
Opened 2021-05-20 13:59 UTC by rachelandrew

Adds InputDeviceInfo.

Reviewer: @jpmedley 

The getCapabilities() method returns a dictionary `MediaTrackCapabilities`. I believe we are documenting these inline now, which is what I have done.

That is listed as an interface on the overview page so if we are leaving it inline I'll remove that https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API

However, an equivalent dictionary  `MediaTrackConstraints` has a page already https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints which I wanted to point out as I don't know if we want to move that one inline or just live with the inconsistency.

2021-05-20 15:53 UTC, jpmedley requested changes
This is exceptionally clean. Most of my issues discussions about content and how to approach it. That's the best place to operate.

2021-05-20 15:53 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +<p>A <code>MediaTrackCapabilities</code> object containing the following members:</p>
There's no way to dereference `MediaTrackCapabilities` in JS. Three options.

* **"An object containing..."** Simplest approach does not provide a name that engineers can use to discuss it.
* **Leave as is.** We would need to explain that it doesn't appear anywhere. (I don't like idioms that require explanation.)
* **"A capabilities object..."** Gives engineers a piece of language to discuss it with. May be seen by some as inaccurate.

What are your thoughts?

2021-05-20 15:53 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +  <dd>A {{domxref("ConstrainDOMString")}} object containing a group ID.</dd>
In our IDL as well as in the spec, these are `typedef`, not `dictionary`. I'm not sure what to do about that. What do you think? We'll probably need to discuss this at the editor's weekly. 

The same applies to all the constraints.

2021-05-20 15:53 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +    If the feature can be controlled by a script the source will report both true and false as possible values.</dd>
I don't get this at all. I dug into `ConstraintBoolean`. Despite my speech about avoiding broken conceptual links this morning, this feels like a rabbit hole you shouldn't get into right now. If you have a quick way to resolve the confusion, please do so.

2021-05-20 15:53 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +    If the feature can be controlled by a script the source will report both true and false as possible values.</dd>
In particular, I don't know what "If the feature can be controlled by a script" means.

2021-05-20 15:53 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/index.html
> +  <dd>Returns a <code>MediaTrackCapabilities</code> object describing the primary audio or video track of a device's MediaStream</dd>
```suggestion
  <dd>Returns a <code>MediaTrackCapabilities</code> object describing the primary audio or video track of a device's <code>MediaStream</code>.</dd>
```

2021-05-21 15:43 UTC, rachelandrew commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +<p>A <code>MediaTrackCapabilities</code> object containing the following members:</p>
I think this is one of these places where we are going to disagree. I'd rather give the name because if someone was to look it up in the spec they could find it. As I'm sure I've mentioned before I do like giving people the language that would let them go into the spec. We link to the spec, so it's not outside the bounds of possibility that someone will look at this, then go to the spec and wonder why we didn't mention the name of the object. (I actually just asked my Twitter followers in case I am in a group of one for spec exploring).

I've seen other pages referring to A <object_name> dictionary object in these cases.

I wonder if we could add a glossary page and then refer to them linking that as an explanation of what these types of objects are.

2021-05-21 15:45 UTC, rachelandrew commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +    If the feature can be controlled by a script the source will report both true and false as possible values.</dd>
Hmm, that seems clear to me. If the device has controllable gain control, so you could write a script that allowed it to be turned on or off, then it reports that it can do both. I have no idea how many devices do, but the spec allows for it.

2021-05-21 15:51 UTC, rachelandrew commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +  <dd>A {{domxref("ConstrainDOMString")}} object containing a group ID.</dd>
I've mirrored what the companion interface does here. I thought it worthwhile as these are a bit more involved so linking to the description seemed useful.

2021-05-21 15:51 UTC, rachelandrew commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +  <dd>A {{domxref("ConstrainDOMString")}} object containing a group ID.</dd>
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints

2021-05-21 17:57 UTC, jpmedley commented on files/en-us/web/api/inputdeviceinfo/getcapabilities/index.html
> +    If the feature can be controlled by a script the source will report both true and false as possible values.</dd>
It never occurred to me you would encounter anything in a JS context that wasn't controllable by a script, save the ocassional read-only property.

2021-05-21 17:58 UTC, jpmedley approved these changes

2021-05-21 17:58 UTC, merged