fix fixable flaws in Web/API/Window/requestIdleCallback
mdn/content pull request #5165
Opened 2021-05-20 19:22 UTC by peterbe

The page was using code inside the `<pre>` tag which all gets rendered away anyway.

2021-05-20 19:42 UTC, peterbe commented
Confusingly, none of those `macros` flaws are new. They come from the sidebar I think.

2021-05-20 20:03 UTC, jpmedley requested changes

2021-05-20 20:03 UTC, jpmedley commented on files/en-us/web/api/window/requestidlecallback/index.html
> +  class="brush: js">var handle = window.requestIdleCallback(callback[, options])</pre>
```suggestion
  class="brush: js">window.requestIdleCallback(callback);<br/>
  window.requestIdleCallback(callback, options);</pre>
```

2021-05-20 20:03 UTC, jpmedley commented on files/en-us/web/api/window/requestidlecallback/index.html
> +  class="brush: js">var handle = window.requestIdleCallback(callback[, options])</pre>
The [syntax rules](https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections) have recently changed.

2021-05-20 20:09 UTC, peterbe commented on files/en-us/web/api/window/requestidlecallback/index.html
> +  class="brush: js">var handle = window.requestIdleCallback(callback[, options])</pre>
Thanks! 
But no need for a `<br/>` tag inside `<pre>`. 

Updated: https://pr5165.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Window/requestIdleCALLback#syntax
(cache busting the URL see my latest update)

2021-05-26 07:46 UTC, sideshowbarker commented
@jpmedley This PR seems to be waiting on your re-review/approval of changes made in response to your review comments

2021-06-02 15:11 UTC, jpmedley approved these changes

2021-06-02 15:13 UTC, jpmedley requested changes
Sorry for the delay. I've been out of the office. 

The suggestion I just made should resolve the merge conflict.

2021-06-02 15:13 UTC, jpmedley commented on files/en-us/web/api/window/requestidlecallback/index.html
> +  - polyfill
```suggestion
  - polyfill
browser-compat: api.Window.requestIdleCallback
```

2021-06-02 19:08 UTC, peterbe commented on files/en-us/web/api/window/requestidlecallback/index.html
> +  - polyfill
Resolved now.

2021-06-03 11:34 UTC, peterbe commented
Back to you @jpmedley

2021-06-03 16:52 UTC, jpmedley approved these changes

2021-06-03 16:52 UTC, merged