Add CSS abs() function
mdn/content pull request #5168
Opened 2021-05-20 22:38 UTC by ramiy

> What was wrong/why is this fix needed? (quick summary only)

Create a new MDN page for a new CSS function.

> MDN URL of the main page changed

https://developer.mozilla.org/en-US/docs/Web/CSS/abs()

> Issue number (if there is an associated issue)

No.

> Anything else that could help us review it

`abs()` is a functional notation defined in [CSS Values and Units Module Level 4](https://drafts.csswg.org/css-values-4/#sign-funcs).

See also: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions

2021-05-21 06:51 UTC, rachelandrew requested changes
Thanks for this, I've been working through the CSS functions trying to give each a page, couple of suggestions inline but I would take a look at the `calc()` page as a good example, although as I don't think this has any support yet we won't add an interactive example at the top.

2021-05-21 06:51 UTC, rachelandrew commented on files/en-us/web/css/abs()/index.html
> +<p>The <code>abs()</code> function takes only one expression as its argument.</p>
Could we have a syntax block here as on https://developer.mozilla.org/en-US/docs/Web/CSS/calc() not all of these have this, but I think it's generally useful so I've been adding them.

2021-05-21 06:51 UTC, rachelandrew commented on files/en-us/web/css/abs()/index.html
> +<p>The font-size will always be positive.</p>
You need to explain in this example why the font size will always be positive. What is happening here?

2021-05-21 12:00 UTC, ramiy commented on files/en-us/web/css/abs()/index.html
> +<p>The <code>abs()</code> function takes only one expression as its argument.</p>
@rachelandrew 

Are you talking about the `<pre>` block?

2021-05-21 12:04 UTC, ramiy commented on files/en-us/web/css/abs()/index.html
> +<p>The font-size will always be positive.</p>
done.

2021-05-21 12:54 UTC, rachelandrew commented on files/en-us/web/css/abs()/index.html
> +<p>The <code>abs()</code> function takes only one expression as its argument.</p>
Yes, on `calc()` it has:

```
/* property: calc(expression) */
width: calc(100% - 80px);
```

So one or more examples of actual usage.

2021-05-21 14:27 UTC, ramiy commented on files/en-us/web/css/abs()/index.html
> +<p>The <code>abs()</code> function takes only one expression as its argument.</p>
A simple syntax block was added. You can change it later.

2021-05-21 14:59 UTC, rachelandrew requested changes

2021-05-21 14:59 UTC, rachelandrew commented on files/en-us/web/css/abs()/index.html
> +<p>In this example we are making sure <code>font-size</code> value will always be positive even if the <code>--font-size</code> variable is negetive.</p>
```suggestion
<p>The <code>abs()</code> function can be used to ensure that a value is always positive. In the following  example a CSS custom property <code>--font-size</code> is used as the value of {{cssxref("font-size)}}. Wrapping this custom property in <code>abs()</code> will convert a negative value to a positive one.</p>

<pre class="brush: css;">h1 {
  font-size: abs( var( --font-size ) );
}
</pre>

```

2021-05-21 14:59 UTC, rachelandrew commented on files/en-us/web/css/abs()/index.html
> +<p>You can also control the gradient direction using <code>abs()</code> function.</p>
This would be clearer is you explained what the user would see. The examples need to further explain what the function does, otherwise they don't add a lot from the syntax example. That's especially important in unimplemented things, because we can't just give people something they can try out.

So something like,

"In the following example, with an angle of -45deg the gradient would start red and transition to blue. By using <code>abs</code> to make the value positive, the gradient will start blue and transition to red."

2021-05-21 23:13 UTC, ramiy commented on files/en-us/web/css/abs()/index.html
> +<p>You can also control the gradient direction using <code>abs()</code> function.</p>
Not sure if I agree with that. I assume MDN readers know basic CSS and can read code. This page should simply explain what abs() does, not how gradient work.

2021-05-22 00:04 UTC, ericwbailey commented on files/en-us/web/css/abs()/index.html
> +<p>You can also control the gradient direction using <code>abs()</code> function.</p>
I agree with Rachel.

2021-05-22 09:02 UTC, ramiy commented on files/en-us/web/css/abs()/index.html
> +<p>You can also control the gradient direction using <code>abs()</code> function.</p>
Ok, the second example updated.

2021-05-22 14:23 UTC, rachelandrew approved these changes
thank you!

2021-05-22 14:24 UTC, merged