Create a new page for CSS `sign()` function
mdn/content pull request #5192
Opened 2021-05-21 15:42 UTC by ramiy

> What was wrong/why is this fix needed? (quick summary only)

Create a new MDN page for a new CSS function.

> MDN URL of the main page changed

https://developer.mozilla.org/en-US/docs/Web/CSS/sign()

> Issue number (if there is an associated issue)

No.

> Anything else that could help us review it

`sign()` is a functional notation defined in [CSS Values and Units Module Level 4](https://drafts.csswg.org/css-values-4/#sign-funcs).

See also: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions

2021-05-21 16:03 UTC, ramiy commented
@rachelandrew

2021-05-22 14:29 UTC, rachelandrew requested changes

2021-05-22 14:29 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +--sign: sign( --value );</pre>
Would be helpful to show an example without a custom property here, you can add multiple lines to show usage.

2021-05-22 14:29 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +<p><strong>Note:</strong> While the <a href="/en-US/docs/Web/CSS/abs()"><code>abs()</code></a> returns the absolute value of the argument, <code>sign()</code> returns the sign of the argument.</p>
```suggestion
<div class="notecard note">
<h4>Note</h4>
<p>While the <a href="/en-US/docs/Web/CSS/abs()"><code>abs()</code></a> returns the absolute value of the argument, <code>sign()</code> returns the sign of the argument.</p>
</div>
```

2021-05-22 14:29 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +For example, in background-position positive percentages resolve to a negative length, and vice versa, if the background image is larger than the background area. Thus sign(10%) might return 1 or -1,
can we see code for the example please, this is a fairly confusing statement otherwise.

2021-05-22 14:31 UTC, rachelandrew commented
@ramiy just a note, the BCD folk tend not to want completely unsupported things in BCD. We're trying to come up with a standard way to indicate "no support at all" without adding a BCD table here https://github.com/mdn/content/issues/5118

2021-05-22 19:29 UTC, ramiy commented on files/en-us/web/css/sign()/index.html
> +--sign: sign( --value );</pre>
Do you have an idea for example?

2021-05-22 19:31 UTC, ramiy commented on files/en-us/web/css/sign()/index.html
> +For example, in background-position positive percentages resolve to a negative length, and vice versa, if the background image is larger than the background area. Thus sign(10%) might return 1 or -1,
Copy & Paste from the spec - https://drafts.csswg.org/css-values-4/#sign-funcs

2021-05-24 08:50 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +--sign: sign( --value );</pre>
just show a basic example, so it's clear that this can be used without the custom property.

2021-05-29 12:17 UTC, ramiy commented on files/en-us/web/css/sign()/index.html
> +--sign: sign( --value );</pre>
Replaced `--sign` var with `top` property.

2021-05-31 20:41 UTC, ramiy commented
@rachelandrew Examples updated. Please review.

2021-06-04 14:30 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +For example, in <a href="/en-US/docs/Web/CSS/background-position"><code>background-position</code></a> positive percentages resolve to a negative length, and vice versa, if the background image is la
```suggestion
For example, in {{cssxref("background-position")}} positive percentages resolve to a negative length, and vice versa, if the background image is larger than the background area. Thus <code>sign(10%)</code> might return <code>1</code> or <code>-1</code>, depending on how the percentage is resolved! (Or even <code>0</code>, if it’s resolved against a zero length.)
```

2021-06-04 14:32 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +}</pre>
You are saying it might resolve one way or another, so I would suggest showing that in the example. As we don't have an implementation of this right now. So if you give this a container (and thus something to resolve against) you can give a clear example of what the value would resolve to.

If we have implementations wouldn't matter so much as people could see/check in DevTools but we need to be a bit more explicit with things that don't have a way to demo them.

2021-06-04 14:33 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +Another usecase is to control the <a href="/en-US/docs/Web/CSS/position"><code>position</code></a> of the element. Either a positive or a nagative value.
```suggestion
Another usecase is to control the {{cssxref("position")}} of the element. Either a positive or a negative value.
```

2021-06-04 14:34 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +Another usecase is to control the <a href="/en-US/docs/Web/CSS/position"><code>position</code></a> of the element. Either a positive or a nagative value.
Why is this useful? I'd suggest adding that answer to the description.

2021-06-04 14:35 UTC, rachelandrew requested changes
Couple of inline suggestions and comments

2021-08-15 08:56 UTC, sideshowbarker commented
@ramiy It seems maybe this is waiting on your response to the review comment at https://github.com/mdn/content/pull/5192#pullrequestreview-676351901

2021-08-15 11:39 UTC, ramiy commented on files/en-us/web/css/sign()/index.html
> +}</pre>
I don't have a better example. We can release the page as is, and let the community add better examples.

2021-08-16 08:29 UTC, rachelandrew commented on files/en-us/web/css/sign()/index.html
> +}</pre>
I explained above how to make the example better. At the moment it doesn't really demonstrate anything. 

Give the element a container, with a width, then in the explanation to the example explain what the background position would be based on being `sign(10%)` of the container width. What would it resolve to?

2021-08-16 08:34 UTC, teoli2003 commented
I'm afraid this sat still for too long and, with the conversion of the CSS area to Markdown last week, this will need some extra work.

(I wonder why Github doesn't indicate any merge conflict, btw)

2021-08-19 17:28 UTC, ramiy commented on files/en-us/web/css/sign()/index.html
> +}</pre>
@rachelandrew can you insert a code suggestion to the PR?

2021-09-19 07:44 UTC, sideshowbarker commented
> I'm afraid this sat still for too long and, with the conversion of the CSS area to Markdown last week, this will need some extra work.

I think that’s just because it’s an entirely new file

2021-09-19 08:00 UTC, sideshowbarker commented
> with the conversion of the CSS area to Markdown last week, this will need some extra work.

I went ahead and converted it to Markdown. But I’m not sure from who this PR is waiting on action from at this point…

2021-09-19 10:05 UTC, ramiy commented
I think the PR is ready for merge. For suggestions people can create new PRs.

2021-09-27 07:17 UTC, rachelandrew approved these changes

2021-09-27 07:17 UTC, merged