Remove inline styles from CSS border pages
mdn/content pull request #5202
Opened 2021-05-22 07:25 UTC by wbamberg

> What was wrong/why is this fix needed? (quick summary only)

> MDN URL of the main page changed

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-05-25 15:37 UTC, mirunacurtean requested changes
The comments about the `length` and `percentage` values are applied to all examples in the tables.
About the `border-style `pages changes - I much prefer the new **Result** examples and although it was helpful having examples in the **Values** table as well, I can see how it achieves consistency with other Properties pages. 
Outside of that, everything looks good to me.

2021-05-25 15:37 UTC, mirunacurtean commented on files/en-us/web/css/border-top-left-radius/index.html
> -   <td>An arc of ellipse is used as the border
We have two "Arc of ellipse" examples but this one should be the "Arc of a circle". Could you please update?
Would be even more useful if the additional data regarding the <length> values defining what shape does the arc of the border manifest as. 
If I may suggest, maybe something like "`<td>`An arc of a circle is used as the border, This is produced by using a single `<length>` value" would work.

2021-05-25 15:37 UTC, mirunacurtean commented on files/en-us/web/css/border-top-left-radius/index.html
> -   <td>An arc of ellipse is used as the border
The same as the previous request. It would be useful to include the information about the different `length` values producing an ellipse arc.

2021-05-25 15:37 UTC, mirunacurtean commented on files/en-us/web/css/border-bottom-left-radius/index.html
> -			<td>An arc of circle is used as the border
Adding a note on the impact of similar of different `length` values, or the way using a `percentage` in square or non-square shapes results in different arcs, would be useful.

2021-05-25 16:56 UTC, wbamberg commented on files/en-us/web/css/border-top-left-radius/index.html
> -   <td>An arc of ellipse is used as the border
It looks like this comment is on the current content (the table, which does indeed contain the error you mentioned) not the new content in this PR?

Also this PR does include a little more information: https://github.com/mdn/content/pull/5202/files#diff-e08c95e839fc9662d04d34d7eddba53f715f94d9dc2c0a0833966efb6625c698R81

2021-05-25 16:57 UTC, wbamberg commented
@mirunacurtean , thanks for your review! But it looks like these comments are on the old content (the table, highlighted in red in this PR because I'm removing it) not the new content I'm replacing it with. Or have I missed something?

Thanks!

2021-05-26 10:03 UTC, mirunacurtean commented on files/en-us/web/css/border-top-left-radius/index.html
> -   <td>An arc of ellipse is used as the border
Yes. It seems I looked at the changes the other way around when comparing them. Sorry for the misunderstanding

2021-05-26 10:09 UTC, mirunacurtean approved these changes
Looking only at the new pages and the modifications I see no issues. Thank you for making it consistent with other pages and the great work on the Examples.

2021-05-26 10:11 UTC, merged