UPDT-and-FIX
mdn/content pull request #5216
Opened 2021-05-23 10:17 UTC by stebenwolf

UPDT links

2021-05-24 00:39 UTC, hamishwillee requested changes

2021-05-24 00:39 UTC, hamishwillee commented on files/en-us/glossary/character_set/index.html
> +<section id="quick_links">
This breaks the sidebar. The toolchain looks for a section id named (case senstive) "Quick_links" and uses this to populate the sidebar. So essentially the section is now invisible. 

If you switch this back you can see it appear in the sidebar:
![image](https://user-images.githubusercontent.com/5368500/119282151-e130c080-bc7b-11eb-84e8-20da6e920ddc.png)

2021-05-24 00:39 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Block_cipher_mode_of_operation">Block cipher mode of operation</a></li>
Why change any of these glossary links? They all work - so what is the point?

Further, you might argue they are _better_. A macro-generated links is auto-translated to the correct locale.

2021-05-24 00:40 UTC, hamishwillee commented
Thanks, but 
- can you explain the value of changing these from macro to link? 
- either way, the quick links thing has to be fixed, because it breaks the page.

2021-05-24 00:40 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +<section id="quick_links">
As above, breaks page

2021-05-24 11:23 UTC, stebenwolf commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +<section id="quick_links">
My bad, thanks for pointing it out!

2021-05-24 11:35 UTC, stebenwolf commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Block_cipher_mode_of_operation">Block cipher mode of operation</a></li>
Hi @hamishwillee ,
Thanks for the details, I didn't know that.
I made these changes while working on the French translation of the page, and I had been told that using direct links was better than using macros (maybe I misunderstood it). To reduce possible further mistakes, is there a page that lists how to properly contribute (technically speaking) ? I looked through the MDN docs but couldn't find one. Thank you for your help

2021-05-25 01:16 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Block_cipher_mode_of_operation">Block cipher mode of operation</a></li>
Hi @stebenwolf 

1. Thanks for contributing. I definitely do not want to discourage you. 
2. Generally we're trying to reduce macro usage, prior to moving to markdown-based source. There is no clear direction on whether you should use bare links or macros - I have heard both. Personally I use the macros for cross references because they are so much easier, and because I think that easing translation is important. Not sure how Glossary and other macros work with respect to translation, so perhaps the argument does not hold for them. 
3. There is WAY TOO MUCH on contributing to MDN :-). Start here: https://github.com/mdn/content#making-contributions

Then for lots of additional detail you can dig down from: https://developer.mozilla.org/en-US/docs/MDN

2021-05-25 01:17 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +<section id="quick_links">
Still broken

2021-05-25 01:19 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Symmetric-key_cryptography">Symmetric-key cryptography</a></li>
@peterbe I know that an xref macro (e.g. jsxref) has the benefit that translation automatically supplies the correct language path. Is there any similar "magic" for glossary macro, or would it be correct to say that the main benefit is brevity of the syntax?

2021-05-25 16:47 UTC, peterbe commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Symmetric-key_cryptography">Symmetric-key cryptography</a></li>
The `Glossary.ejs` macro has the advantage that is uses `smartLink` which is good because if you were to copy this page over to French, you won't need to touch the line `{{Glossary("Cryptography")}}` at all because the locale of that is automatically injected. 
If the French page exists, it becomes `/fr/docs/Glossary/Cryptography` and if it doesn't yet exist it becomes `/en-US/docs/Glossary/Cryptography` and it can take care of making a note to the French reader that it had to fall back to Englihs (US). 

So in my view `{{Glossary(PAGE)}}` is better than `<a href="...">`.

2021-05-27 06:58 UTC, stebenwolf commented
> The `Glossary.ejs` macro has the advantage that is uses `smartLink` which is good because if you were to copy this page over to French, you won't need to touch the line `{{Glossary("Cryptography")}}` at all because the locale of that is automatically injected. 
If the French page exists, it becomes `/fr/docs/Glossary/Cryptography` and if it doesn't yet exist it becomes `/en-US/docs/Glossary/Cryptography` and it can take care of making a note to the French reader that it had to fall back to Englihs (US). 

So in my view `{{Glossary(PAGE)}}` is better than `<a href="...">`.  


Thank you very much for these detailed explanations @peterbe !
I now understand better why using {{Glossary("Cryptography")}} is better

Do you know if using a <a href="..."> is better anywhere on MDN (apart from external URLs) ? or can I take it as a rule of thumb to use macros everywhere?

2021-05-27 16:02 UTC, peterbe commented
> Do you know if using a [ is better anywhere on MDN (apart from external URLs) ? or can I take it as a rule of thumb to use macros everywhere?](...)

It's complicated because of Markdown. But in general, if there's a macro for making links, use that instead of `<a>`. 
At least for the time being.

2021-05-28 01:28 UTC, hamishwillee commented on files/en-us/glossary/symmetric-key_cryptography/index.html
> +   <li><a href="/en-US/docs/Glossary/Symmetric-key_cryptography">Symmetric-key cryptography</a></li>
OK, captured in https://github.com/mdn/content/pull/5399. Thanks Peter

2021-05-28 01:28 UTC, hamishwillee commented
@stebenwolf OK, so since the remaining changes in this PR are related to Glossary links, I am closing this PR. Hope that makes sense.

2021-05-28 01:28 UTC, closed without merging