Fix up MDN instructions and templates for browser-compat
mdn/content pull request #5225
Opened 2021-05-24 00:27 UTC by hamishwillee

The new way of doing browser compatibility sections is to list the BCD path in the page frontmatter `browser-compat` key and just use `{{Compat}}` as a placeholder. Also we no longer have hidden sections.

This fixes just one template: https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_landing_page_template. If this is merged I'll do the other MDN instructional docs/templates - e.g. https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/SVG_element_page_template

This follows follows on naturally from https://github.com/mdn/content/pull/4398 and https://github.com/mdn/content/issues/2228

@wbamberg @Elchi3 Sanity check would be good :-)

2021-05-24 03:58 UTC, wbamberg commented
Thanks for doing this @hamishwillee ! Definitely needed, and this general update looks fine. Having said that, I'm not actually sure yet whether we will be doing this for API pages in particular. See https://github.com/mdn/content/discussions/4920.

What you've written here definitely applies for https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#css_feature_reference_page and very likely:

https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#api_reference_subpage
https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#html_element_reference_page
https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#svg_element_reference_page
https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#http_header_reference_page

...and of course JS, which does not seem to be documented here... 

This update could also talk about using the {{Specifications}} macro, instead of a handwritten table.

2021-05-25 03:47 UTC, hamishwillee commented
Hi @wbamberg,  Thank you for the feedback.  IMO there isn't any reason not to roll this out to API docs and everywhere else. Even if we are sporadic about roll out, the howto docs should reflect a consistent approach. 

I will add update for `{{Specifications}}` too. Originally I decided not to because these are not as well rolled out. But then I realised that's not the point as this is for new docs, and the update to BCD needs to include this information going forward.

2021-05-25 06:57 UTC, hamishwillee commented
@wbamberg et al, OK I did a further update to add info on how to update the specifications table.

That lead me to wondering how you update the `spec_url`, which lead to me updating https://developer.mozilla.org/en-US/docs/MDN/Structures/Compatibility_tables with:
- basic information on how to find the spec URL 
- Fixes to update from pointing to git main branch rather than master
- Updated AbortController as an example (it is a better example than the other two as it has both the spec and browser compat.

Anyway, needs a re-review before I go and roll everything out everywhere :-)

2021-05-25 06:58 UTC, hamishwillee commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<h4 id="Compatibility_table_example">Compatibility table example</h4>
Note, headings needed to force the tables below the things that talk about them.

2021-05-25 06:59 UTC, hamishwillee commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>You can also specify the desired API as the first argument to the macro as shown: <code>\{{Compat("api.AbortController")}}</code>. This can be useful if multiple compatibility tables are required
FWIW I don't know if this is something we still want to advertise.

2021-05-25 09:39 UTC, Elchi3 requested changes, later dismissed
Thanks for updating this!

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>First you need to find the "address" for the relevant compatibility data you wish to include. This can be determined by inspecting its source file. For example:</p>
I think we've been calling this query string or just query in other places.

```suggestion
<p>First you need to find the query string for the relevant compatibility data you wish to include. This can be determined by inspecting its source file. For example:</p>
```

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +  <li>{{domxref("AbortController")}} compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/api/AbortController.json">AbortController.json</a> and has address
```suggestion
  <li>{{domxref("AbortController")}} compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/api/AbortController.json">AbortController.json</a> and can be queried using <code>api.AbortController</code>.</li>
```

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +  <li>{{HTTPHeader("Content-Type")}} HTTP header compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/http/headers/content-type.json">content-type.json</a> a
```suggestion
  <li>{{HTTPHeader("Content-Type")}} HTTP header compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/http/headers/content-type.json">content-type.json</a> and the query is <code>http.headers.Content-Type</code>.</li>
```

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +  <li>{{domxref("VRDisplay.capabilities")}} property compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/api/VRDisplay.json">VRDisplay.json</a> and has addr
```suggestion
  <li>{{domxref("VRDisplay.capabilities")}} property compatibility data is defined in <a href="https://github.com/mdn/browser-compat-data/blob/main/api/VRDisplay.json">VRDisplay.json</a> and its query is <code>api.VRDisplay.capabilities</code>.</li>
```

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>The compatibility data address should be specified in the page front-matter using the <code>browser-compat</code> key.
```suggestion
<p>The compatibility data query should be specified in the page front-matter using the <code>browser-compat</code> key.
```

2021-05-25 09:39 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>You can also specify the desired API as the first argument to the macro as shown: <code>\{{Compat("api.AbortController")}}</code>. This can be useful if multiple compatibility tables are required
Yep, this is fine. Guide pages typically want a compat table (or multiple).

2021-05-26 03:27 UTC, wbamberg commented
> Hi @wbamberg, Thank you for the feedback. IMO there isn't any reason not to roll this out to API docs and everywhere else. 

For *API landing pages* specifically, it's not at all obvious to me that the approach of adding a single BCD query into front matter makes sense, because the tech covered by a single API landing page doesn't correspond to a single BCD query. For example, which single query would you use to describe the compat status of the WebRTC API: https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API ?

2021-05-28 06:22 UTC, hamishwillee commented
@wbamberg @Elchi3 

Re https://github.com/mdn/content/pull/5225#issuecomment-848426600 "For API landing pages specifically, it's not at all obvious ..."

OK, I get you. Part of the problem is that it is not all that clear in the original doc. At the moment it talks about just one compat table. What I **think** this should say is that you may find it useful to display BCD tables for the main interfaces in an API - so work out the keys for each of them and put them in compatibility section using separate  compat macro (or something similar). Does that make sense? For now I have just reverted that section.

If so, what about specifications? That macro does not take a BCD entry. So do we say "create your own table" or do I remove this section, or what?

FURTHER ...
I have updated the API reference and API reference method pages, because those actually can use the compat and specification macros. As part of that I reworked the top note to better highlight frontmatter. IMO this is much cleaner.

2021-05-31 15:19 UTC, Elchi3 commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>You can also specify the desired API as the first argument to the macro as shown: <code>\{{Compat("api.AbortController")}}</code>. This can be useful if multiple compatibility tables are required
fwiw, this is also true for specification tables, see https://github.com/mdn/yari/blob/main/kumascript/macros/Specifications.ejs

2021-05-31 15:24 UTC, Elchi3 commented
> If so, what about specifications? That macro does not take a BCD entry. So do we say "create your own table" or do I remove this section, or what?

The specification macro can actually take a BCD query if needed. I think having a manual spec table is fine as the exception, too, though. I mean it is just links to specs really. If certain pages need something more fancy, then I would decide on a case by case basis. The majority of reference-type pages should be fine with just {{Specifications}} imo.

2021-06-01 00:36 UTC, hamishwillee commented on files/en-us/mdn/structures/compatibility_tables/index.html
> +<p>You can also specify the desired API as the first argument to the macro as shown: <code>\{{Compat("api.AbortController")}}</code>. This can be useful if multiple compatibility tables are required
Thanks @Elchi3. I did test that and it didn't work. Must have made a mistake. Will try again.

2021-06-01 00:37 UTC, hamishwillee commented
>> If so, what about specifications? That macro does not take a BCD entry. So do we say "create your own table" or do I remove this section, or what?

> The specification macro can actually take a BCD query if needed. I think having a manual spec table is fine as the exception, too, though. I mean it is just links to specs really. If certain pages need something more fancy, then I would decide on a case by case basis. The majority of reference-type pages should be fine with just {{Specifications}} imo.

Great news. I did test this, which is why I thought it did not work. Will retest and update appropriately.

2021-06-04 06:58 UTC, hamishwillee commented
@Elchi3 I've rebased to master and modified the API Landing page to improve the browser compat and specifications sections as discussed. It now says
- Both these sections are optional
- They can have multiple tables or none. Do what is sensible for the API.

Can you please review and (ideally) merge. After I'll roll out more broadly.

2021-06-04 09:31 UTC, Elchi3 approved these changes
Awesome, thanks Hamish!

2021-06-04 09:32 UTC, merged