Remove Page macro: Feature-Policy accelerometer
mdn/content pull request #5240
Opened 2021-05-24 06:14 UTC by hamishwillee

Partial fix for #3196

Feature policies like [Feature-Policy: accelerometer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/accelerometer) previously imported the standard definition of `allowlist` from [Using Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#allowlist).

My take on this is that the `allowlist` is important to have in each of the policies, and it should be duplicated rather than linked. This is partially based on the fact that Feature-Policy is "soon" to be replaced by Permission-Policy (on MDN) so there will be no further modification of the content - ie duplication creates no maintenance issue. 

This duplicates the same text for allowlist in each policy. This test is a minor modification of the original. In particular it does not mention the generic "all features have a default value" as that is not necessary to mention here.

2021-05-25 01:54 UTC, hamishwillee commented
@wbamberg Could you please review this. While it looks like a lot, in fact it is mostly copy-paste. So if you are happy with the way allowlist looks for one of the docs you can be sure it will be fine for the rest.

Other than that the fixes get compat from BCD, and the spec if present. That stuff also easy to review - and I have tested it.

2021-05-31 23:09 UTC, wbamberg commented
Sorry to be slow looking at this.

I think in a case like this it's better to write the thing once in (in https://pr5240.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Headers/Feature-Policy#syntax probably) and link to it from the directive pages. The reason is that this is really always the same thing in all the directives, so learning it for one directive means learning it for all of them. By linking to a single definition this is made obvious to the reader. By duplicating it, it's not: they might be similar but subtly different, and a reader has to have that possibility in mind.

I don't feel terribly strongly about this though.

I'm not sure what to do about the duplication in https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#allowlist. Probably keep it, since it's guide not reference content.

2021-06-04 05:48 UTC, hamishwillee commented
@wbamberg Thanks for the review - hard to fit everything in :-).

Much as I hate to say it, I agree. Have fixed up as you suggested, leaving the "Using" Guide topic unchanged.

Ready for re-review.

2021-06-05 00:33 UTC, wbamberg commented on files/en-us/web/http/headers/feature-policy/fullscreen/index.html
> +<p>Default allow list for <code>fulscreen</code> is <code>'self'</code>.</p>
```suggestion
<p>Default allow list for <code>fullscreen</code> is <code>'self'</code>.</p>
```

2021-06-05 03:14 UTC, wbamberg requested changes
Thanks for making these updates @hamishwillee . I like it much better like this. There was one where you changed the default policy, and a few that still have the duplicated version.

2021-06-05 03:14 UTC, wbamberg commented on files/en-us/web/http/headers/feature-policy/document-domain/index.html
> +<p>Default allow list for <code>document-domain</code> is <code>'self'</code>.</p>
I'm not sure why this changed? From the spec it looks like "*" is correct? https://html.spec.whatwg.org/multipage/infrastructure.html#policy-controlled-features

2021-06-05 03:14 UTC, wbamberg commented on files/en-us/web/http/headers/feature-policy/unoptimized-images/index.html
> +  </dd>
This one still has the duplicated version?

2021-06-05 03:14 UTC, wbamberg commented on files/en-us/web/http/headers/feature-policy/unsized-media/index.html
> +  </dd>
This one too, or is there a reason these have them?

2021-06-05 03:14 UTC, wbamberg commented on files/en-us/web/http/headers/feature-policy/vibrate/index.html
> +  </dd>
and this.

2021-06-07 01:45 UTC, hamishwillee commented on files/en-us/web/http/headers/feature-policy/unoptimized-images/index.html
> +  </dd>
I missed a few because I went through the Directives list on the Feature-Policy page and it omits a couple of directives. I'll fix these cases and add them to the list.

2021-06-07 01:50 UTC, hamishwillee commented on files/en-us/web/http/headers/feature-policy/unsized-media/index.html
> +  </dd>
As above. Missed this because I was dumb and relied on all of them being linked from the top level page. Thanks for being more careful than me.

2021-06-07 02:05 UTC, hamishwillee commented on files/en-us/web/http/headers/feature-policy/document-domain/index.html
> +<p>Default allow list for <code>document-domain</code> is <code>'self'</code>.</p>
That's what we call a screwup. Thanks for catching.

2021-06-07 02:17 UTC, hamishwillee commented
Thanks @wbamberg - sorry about those. All fixed now I believe.

2021-06-08 00:56 UTC, wbamberg approved these changes
Thanks @hamishwillee , this looks great. I'm happy the review's useful :)

2021-06-08 00:56 UTC, merged

2021-06-08 01:23 UTC, hamishwillee commented
> I'm happy the review's useful :)

@wbamberg Well, it does ruin my air of infallibility. Amazing how careful you can think you're being and still miss the bleedingly obvious :-(