Adds MIDIOutput
mdn/content pull request #5390
Opened 2021-05-27 13:43 UTC by rachelandrew

Adds the MIDIOutput Interface

Reviewer: @jpmedley 

On looking at this I discovered that there is an additional method `clear()` unimplemented by Chrome, and with no BCD. I did a search and [found a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=471798#c22), with a note that it might be implemented for 93. So I made a basic documentation page for the method and I'll submit BCD with a link to the bug, I can always update it if it does ship.

The MIDI interfaces are fairly sparsely documented. Mostly just overview pages.

2021-06-02 20:00 UTC, jpmedley requested changes

2021-06-02 20:00 UTC, jpmedley commented on files/en-us/web/api/midioutput/send/index.html
> +  var noteOnMessage = [0x90, 60, 0x7f];    // note on, middle C, full velocity
```suggestion
  var noteOnMessage = [0x90, 60, 0x7f];    // note on middle C, full velocity
```

2021-06-02 20:00 UTC, jpmedley commented on files/en-us/web/api/midioutput/send/index.html
> + </table>
```suggestion
<p>{{Specifications}}</p>
```

2021-06-03 08:54 UTC, rachelandrew commented on files/en-us/web/api/midioutput/send/index.html
> +  <dd>A sequence of one or more valid MIDI messages. Each entry represents a single byte of data.</dd>
that's a good idea, I found a link on midi.org that explains midi messages.

2021-06-03 16:22 UTC, jpmedley approved these changes

2021-06-03 16:22 UTC, merged