Put browser-compat info in front-runner for api/s*
mdn/content pull request #5426
Opened 2021-05-28 12:22 UTC by teoli2003

> What was wrong/why is this fix needed? (quick summary only)

We want to have browser-compat in front-runner: this allows us to write {{Compat}} without parameter, and in the future, {{Spec}} (and likely more).

This PR covers api/s* for the case without problem: 1 macro Compat in the page and its parameter matching the slug. Other cases (no Compat macros on a page, multiple Compat macros, macro not matching the slug, will be done at a later stage).

> MDN URL of the main page changed

539 files in api/* 

> Issue number (if there is an associated issue)

openwebdocs/project#36

> Anything else that could help us review it

2021-05-31 16:20 UTC, Elchi3 requested changes

2021-05-31 16:20 UTC, Elchi3 commented on files/en-us/web/api/subtlecrypto/importkey/index.html
> +    const pemFooter = "-----END PUBLIC KEY--browser-compat: api.SubtleCrypto.importKey
Something is going on here.

2021-05-31 16:20 UTC, Elchi3 commented on files/en-us/web/api/subtlecrypto/exportkey/index.html
> +  const pemExported = `-----BEGIN PUBLIC KEY-----\n${exportedAsBase64}\n-----END PUBLIC KEY--browser-compat: api.SubtleCrypto.exportKey
Same here.

2021-05-31 16:27 UTC, Elchi3 commented on files/en-us/web/api/subtlecrypto/exportkey/index.html
> +  const pemExported = `-----BEGIN PUBLIC KEY-----\n${exportedAsBase64}\n-----END PUBLIC KEY--browser-compat: api.SubtleCrypto.exportKey
btw I haven't checked if it happens elsewhere. The Crypto API pages might have more of this.

2021-06-01 05:48 UTC, teoli2003 commented on files/en-us/web/api/subtlecrypto/importkey/index.html
> +    const pemFooter = "-----END PUBLIC KEY--browser-compat: api.SubtleCrypto.importKey
Fixed (lazy regexp).

2021-06-01 05:49 UTC, teoli2003 commented on files/en-us/web/api/subtlecrypto/exportkey/index.html
> +  const pemExported = `-----BEGIN PUBLIC KEY-----\n${exportedAsBase64}\n-----END PUBLIC KEY--browser-compat: api.SubtleCrypto.exportKey
Fixed (lazy crypto).

I checked the whole Web Crypto API to be sure: these were the only two cases with cryptographic keys (that contains the --- trigerring the problem).

2021-06-01 06:04 UTC, Elchi3 approved these changes
Thank you! 👍

2021-06-01 06:05 UTC, merged