Adds an overview for the Web MIDI API
mdn/content pull request #5433
Opened 2021-05-28 15:03 UTC by rachelandrew

The missing overview page for Web MIDI, I included some examples from the spec.

Reviewer: @jpmedley

2021-06-02 18:02 UTC, jpmedley requested changes

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> + <dd>Queues messages to the linked MIDI port, messages can be sent immediately or after a specified delay.</dd>
```suggestion
 <dd>Queues messages to the linked MIDI port. Messages can be sent immediately or after a specified delay.</dd>
```

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> + <dd>Represents the event passed to {{domxref("MIDIInput.onmidimessage")}}.</dd>
```suggestion
 <dd>The event passed to {{domxref("MIDIInput.onmidimessage")}}.</dd>
```

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> + <dd>Represents the event passed to the {{domxref("MIDIAccess.onstatechange")}} and {{domxref("MIDIPort.onstatechange")}} event handlers, when a port becomes available or unavailable.</dd>
```suggestion
 <dd>The event passed to the {{domxref("MIDIAccess.onstatechange")}} and {{domxref("MIDIPort.onstatechange")}} event handlers, when a port becomes available or unavailable.</dd>
```

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> +<h3>Gaining access to the MISI port</h3>
```suggestion
<h3>Gaining access to the MIDI port</h3>
```

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> +<p>In this example the list or input and output ports are retrieved and printed to the console.</p>
```suggestion
<p>In this example the list of input and output ports are retrieved and printed to the console.</p>
```

2021-06-02 18:02 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> + </table>
<p>{{Specifications}}</p>

2021-06-03 09:12 UTC, rachelandrew commented on files/en-us/web/api/web_midi_api/index.html
> +  - Web MIDI API
I guess we wait until this is resolved https://github.com/mdn/content/discussions/4920

2021-06-03 09:12 UTC, rachelandrew commented on files/en-us/web/api/web_midi_api/index.html
> +  - Web MIDI API
and for now omit it, I can always do a roundup of overview pages once that is resolved.

2021-06-03 16:24 UTC, jpmedley commented on files/en-us/web/api/web_midi_api/index.html
> +  - Web MIDI API
SGTM

2021-06-03 16:25 UTC, jpmedley approved these changes

2021-06-03 16:25 UTC, merged