Put browser-compat info in front-runner for api/[xyz]*
mdn/content pull request #5447
Opened 2021-05-28 19:25 UTC by teoli2003

> What was wrong/why is this fix needed? (quick summary only)

We want to have browser-compat in front-runner: this allows us to write {{Compat}} without parameter, and in the future, {{Spec}} (and likely more).

This PR covers api/[xyz]* for the case without problem: 1 macro Compat in the page and its parameter matching the slug. Other cases (no Compat macros on a page, multiple Compat macros, macro not matching the slug, will be done at a later stage).

> MDN URL of the main page changed

203 files in api/* 

> Issue number (if there is an associated issue)

openwebdocs/project#36

> Anything else that could help us review it

2021-05-31 16:42 UTC, Elchi3 requested changes
A few mixups here

2021-05-31 16:42 UTC, Elchi3 commented on files/en-us/web/api/xrinputsource/targetrayspace/index.html
> +    world space browser-compat: api.XRInputSource.targetRaySpace
This doesn't work.

2021-05-31 16:42 UTC, Elchi3 commented on files/en-us/web/api/xrwebgllayer/getviewport/index.html
> +    article browser-compat: api.XRWebGLLayer.getViewport
This is wrong

2021-05-31 16:42 UTC, Elchi3 commented on files/en-us/web/api/xrinputsource/targetrayspace/index.html
> +    world space browser-compat: api.XRInputSource.targetRaySpace
This doesn't work

2021-06-01 06:15 UTC, teoli2003 commented on files/en-us/web/api/xrinputsource/targetrayspace/index.html
> +    world space browser-compat: api.XRInputSource.targetRaySpace
Fixed (lazy regexp problem)

2021-06-01 06:16 UTC, teoli2003 commented on files/en-us/web/api/xrwebgllayer/getviewport/index.html
> +    article browser-compat: api.XRWebGLLayer.getViewport
Fixed (lazy regexp problem)

2021-06-01 06:18 UTC, teoli2003 commented on files/en-us/web/api/xrinputsource/targetrayspace/index.html
> +    world space browser-compat: api.XRInputSource.targetRaySpace
Same as first comment… (Same file, same line)

2021-06-01 06:27 UTC, Elchi3 requested changes

2021-06-01 06:27 UTC, Elchi3 commented on files/en-us/web/api/xrview/transform/index.html
> +    <strong>&lt;&lt;&lt;--- finish and add link browser-compat: api.XRView.transform
One more to fix here

2021-06-01 06:45 UTC, teoli2003 commented on files/en-us/web/api/xrview/transform/index.html
> +    <strong>&lt;&lt;&lt;--- finish and add link browser-compat: api.XRView.transform
Fixed

2021-06-01 06:47 UTC, Elchi3 approved these changes
Well done! 👍

2021-06-01 06:47 UTC, merged