Added content to block level and inline level elements
mdn/content pull request #5448
Opened 2021-05-29 02:57 UTC by weeklyd3

> What was wrong/why is this fix needed? (quick summary only)

I added more details, not fixed any bugs.

> MDN URL of the main page changed
 - en-us/web/html/inline_elements/index.html
 - en-us/web/html/block-level_elements/index.html

> Issue number (if there is an associated issue)

No issue number.
> Anything else that could help us review it

N/A

2021-06-02 00:57 UTC, ericwbailey requested changes

2021-06-02 00:57 UTC, ericwbailey commented on files/en-us/web/html/block-level_elements/index.html
> +<p>HTML (<strong>Hypertext Markup Language</strong>) elements historically were categorized as either "block-level" elements or "inline-level" elements. Since this is a presentational characteristic
What do you mean by "line breaks"? I'd like to update this phrasing so as to not confuse it with a `br` element.

2021-06-02 00:57 UTC, ericwbailey commented on files/en-us/web/html/block-level_elements/index.html
> +<p>The following is a complete list of all HTML "block-level" elements (although "block-level" is not technically defined for elements that are new in HTML5). You can create your own block elements b
Thoughts on updating this language so it can't be interpreted as needing to make all elements `display: block`?

2021-06-02 00:57 UTC, ericwbailey commented on files/en-us/web/html/inline_elements/index.html
> + <dd>By default, inline elements do not force a new line to begin in the document flow. Block elements, on the other hand, typically cause a line break to occur (although, as usual, this can be chang
```suggestion
 <dd>By default, inline elements do not force a new line to begin in the document flow. Block elements, on the other hand, typically cause a line break to occur (although this can be changed using the CSS <a href="/en-US/docs/Web/CSS/display"><code>display</code></a> property).</dd>
```

I don't like assumptive phrases like this, so removing while we're here.

2021-07-28 12:27 UTC, rachelandrew commented
Closing as comments made by a reviewer were marked as resolved with no change being made, and the originally suggested changes do not add anything that I feel is required to the document. As pointed out in the review, they potentially add confusion rather than clarity.

2021-07-28 12:27 UTC, closed without merging