FF90: Adds support for HTTP Sec-Fetch-* headers
mdn/content pull request #5499
Opened 2021-05-31 07:31 UTC by hamishwillee

This updates the documents for `Sec-Fetch-*` headers as requested in #5375.

- [ ] [Sec-Fetch-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site)
- [ ] [Sec-Fetch-Mode](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode)
- [ ] [Sec-Fetch-User](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-User)
- [ ] [Sec-Fetch-Dest](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest)
- [ ] Release note

This depends a bit on BCD to tell me if this should still be considered experimental:  [BCD](https://github.com/mdn/browser-compat-data/pull/10679)

2021-06-01 06:47 UTC, hamishwillee commented on files/en-us/web/http/headers/index.html
> - <dd>It is a request header that indicates the request's mode to a server. It is a Structured Header whose value is a token with possible values <code>cors</code>, <code>navigate</code>, <code>nested
Note, `nested-navigate` and `nested-document` are not present in the spec

2021-06-01 06:48 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-fetch-dest/index.html
> +Sec-Fetch-Dest: frame
note, `frame` and `iframe` have an issue note in the spec "frame and iframe haven’t landed in Fetch yet. <https://github.com/whatwg/fetch/issues/948>". But that PR has merged, so I believe these should be included.

2021-06-01 06:49 UTC, hamishwillee commented on files/en-us/glossary/fetch_metadata_request_header/index.html
> + <li><a href="https://web.dev/fetch-metadata/">Protect your resources from web attacks with Fetch Metadata</a> (web.dev)</li>
This is a good doc on the headers, and how you use them to create a resource isolation policy. It omits the User header. We could do something similar, but link is appropriate IMO for now. I have linked this and the following playground in all the docs.

2021-06-01 06:54 UTC, hamishwillee commented
This is ready for review. @annevk @Elchi3 You may be interested in providing feedback.

2021-06-01 09:08 UTC, annevk reviewed
Thanks! Generally looks good to me.

2021-06-01 09:08 UTC, annevk commented on files/en-us/glossary/fetch_metadata_request_header/index.html
> + <li><a href="https://web.dev/fetch-metadata/">Protect your resources from web attacks with Fetch Metadata</a> (web.dev)</li>
It seems better to link this (and the one below) after the list of the headers in its own paragraph.

2021-06-01 09:08 UTC, annevk commented on files/en-us/glossary/http_header/index.html
> + <li>{{Glossary("Fetch metadata request header")}}: Headers wtih metadata about the resource in the message body (e.g. encoding, media type, etc.).</li>
```suggestion
 <li>{{Glossary("Fetch metadata request header")}}: Headers with metadata about the resource in the message body (e.g. encoding, media type, etc.).</li>
```

2021-06-01 09:08 UTC, annevk commented on files/en-us/web/http/headers/sec-fetch-dest/index.html
> +
Nit: spurious newline.

2021-06-01 09:08 UTC, annevk commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +  <dd>The request initiator and the server hosting the resource have the same domain and/or subdomain, but not necessarily the same scheme and port.</dd>
Do we explain the Public Suffix List somewhere on MDN? Might be worth referencing if we do.

Also, I think same scheme is a requirement here.

2021-06-01 12:26 UTC, dergoegge requested changes
`none` is not a valid value for `sec-fetch-dest`

But other than that, this looks good to me.

2021-06-01 12:26 UTC, dergoegge commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +Sec-Fetch-Dest: none
```suggestion
Sec-Fetch-Dest: empty
```

2021-06-01 12:26 UTC, dergoegge commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +Sec-Fetch-Dest: none
```suggestion
Sec-Fetch-Dest: empty
```

2021-06-01 22:33 UTC, hamishwillee commented on files/en-us/glossary/fetch_metadata_request_header/index.html
> + <li><a href="https://web.dev/fetch-metadata/">Protect your resources from web attacks with Fetch Metadata</a> (web.dev)</li>
Thanks. Good point. I have handled this by pulling the headers under their own bullet "Related headers". Looks a lot better.

2021-06-01 22:33 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-fetch-dest/index.html
> +
Fixed thanks.

2021-06-01 22:35 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +Sec-Fetch-Dest: none
Thanks!

2021-06-01 22:57 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +  <dd>The request initiator and the server hosting the resource have the same domain and/or subdomain, but not necessarily the same scheme and port.</dd>
@annevk Good point. Unfortunately not, which is IMO an omission. We need something like https://web.dev/same-site-same-origin/. I have created #5557 to track creation, but it should not hold up this PR. 

Regarding "Also, I think same scheme is a requirement here.". My interpretation of the spec was that same site here means "schemelessly same site": https://html.spec.whatwg.org/multipage/origin.html#schemelessly-same-site - can you confirm - happy to change it if you're _sure_ that the scheme is a requirement.

2021-06-02 05:15 UTC, annevk commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +  <dd>The request initiator and the server hosting the resource have the same domain and/or subdomain, but not necessarily the same scheme and port.</dd>
See https://w3c.github.io/webappsec-fetch-metadata/#abstract-opdef-set-site. It references https://html.spec.whatwg.org/multipage/origin.html#same-site.

2021-06-04 04:56 UTC, hamishwillee commented on files/en-us/web/http/headers/sec-fetch-site/index.html
> +  <dd>The request initiator and the server hosting the resource have the same domain and/or subdomain, but not necessarily the same scheme and port.</dd>
Thanks very much - I'll change it (FWIW that's the link I followed and why I thought the scheme doesn't matter - even with your confirmation I find this non-intuitive).

2021-06-04 04:59 UTC, hamishwillee commented
@Rumyra This has been checked by the technical experts, so should be good for your review and merge.

2021-06-04 14:54 UTC, Rumyra approved these changes
Thanks @hamishwillee - awesome work 👍

2021-06-04 14:54 UTC, merged