Docs: link to redirect docs in location/href docs
mdn/content pull request #5535
Opened 2021-06-01 10:15 UTC by rbrishabh

Fixes #5523 
Hi  @sideshowbarker, I think just adding the link for redirection should give users enough context to users on what it is, and why they might want to use it!

Do you think this fix works? 
let me know if any changes are required!
Thank you!

2021-06-01 10:24 UTC, sideshowbarker requested changes
This change does not seems sufficient for resolving #5523. The issue description for that issue asked that the difference between redirection and navigation in this context be explained.

I recommend reading https://developer.mozilla.org/en-US/docs/Web/API/Location/replace and https://html.spec.whatwg.org/multipage/history.html#dom-location-replace-dev and then updating this patch by adding an explanation based on what those other documents explain.

2021-06-01 10:27 UTC, sideshowbarker commented
> I think just adding the link for redirection should give users enough context to users on what it is, and why they might want to use it!

I don’t think can agree with that — I don’t most users would actually find that just having that link — and reading the content of https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections — would given them enough context.

2021-06-01 11:03 UTC, rbrishabh commented
Sure @sideshowbarker! I'm on it!
Thanks for the quick review

2021-06-01 11:25 UTC, rbrishabh commented
Hey @sideshowbarker ! Does this look better now?
if you want me to provide more context here, just let me know, happy to make the changes!

2021-06-12 23:05 UTC, sideshowbarker approved these changes

2021-06-12 23:16 UTC, sideshowbarker requested changes

2021-06-12 23:16 UTC, sideshowbarker commented on files/en-us/web/api/location/href/index.html
> +  able to use the back button to navigate to it.</p>
```suggestion
  want <em>redirection</em>, use {{domxref("Location/replace","location.replace()")}}. The difference from setting the <code>href</code> property value is that when using the <code>location.replace()</code> method, after navigating to the given URL, the current page will not be saved in session <a href="/en-US/docs/Web/API/History_API">history</a> — meaning the user won't be able to use the back button to navigate to it.</p>
```

2021-06-12 23:16 UTC, sideshowbarker approved these changes

2021-06-12 23:25 UTC, merged

2021-06-12 23:26 UTC, sideshowbarker commented
Rishabh, thanks much, and congrats on landing your first docs change here — welcome aboard 🎉