Removed "experimental" warning
mdn/content pull request #556
Opened 2020-12-22 05:55 UTC by impressivewebs

2020-12-22 07:52 UTC, sideshowbarker requested changes

2020-12-22 07:52 UTC, sideshowbarker commented on files/en-us/web/api/mediakeysession/index.html
> -<p>{{APIRef("EncryptedMediaExtensions")}}{{SeeCompatTable}}</p>
You want to delete on the `{{SeeCompatTable}}`, but keep the `{{APIRef("EncryptedMediaExtensions")}}` part.

2020-12-22 09:47 UTC, impressivewebs commented on files/en-us/web/api/mediakeysession/index.html
> -<p>{{APIRef("EncryptedMediaExtensions")}}{{SeeCompatTable}}</p>
@sideshowbarker Ok, I'm not entirely sure how to edit an existing PR, but I did something that seemed to allow me to edit it Hopefully that works.

2020-12-23 01:47 UTC, sideshowbarker approved these changes

2020-12-23 01:47 UTC, sideshowbarker commented on files/en-us/web/api/mediakeysession/index.html
> -<p>{{APIRef("EncryptedMediaExtensions")}}{{SeeCompatTable}}</p>
> I'm not entirely sure how to edit an existing PR, but I did something that seemed to allow me to edit it Hopefully that works.

Yes, it worked fine — thanks

2020-12-23 01:47 UTC, merged