Update global attributes spec URLs to match BCD
mdn/content pull request #558
Opened 2020-12-22 07:47 UTC by sideshowbarker

This change aligns the MDN spec URL values for HTML global attributes to sync with the spec URL data we have in BCD.

See https://github.com/mdn/browser-compat-data/pull/8064 for discussion on the changes we made to some of URL values when we added them to BCD.

2020-12-22 11:59 UTC, Elchi3 requested changes
Just one nit!

(Also, I made some more PRs against BCD re global attributes and I can bake a PR for mdn/content updates later)

2020-12-22 11:59 UTC, Elchi3 commented on files/en-us/web/html/attributes/autocomplete/index.html
> +			<td>{{SpecName('HTML WHATWG', "#attr-fe-autocomplete")}}</td>
```suggestion
			<td>{{SpecName('HTML WHATWG', "#attr-fe-autocomplete", "autocomplete")}}</td>
```

2020-12-24 10:15 UTC, Elchi3 approved these changes

2020-12-24 10:15 UTC, Elchi3 commented
(not a code owner. sigh)

2020-12-28 10:57 UTC, chrisdavidmills approved these changes

2020-12-28 10:57 UTC, merged