Adds WebOTP API and OTPCredential
mdn/content pull request #5624
Opened 2021-06-03 12:53 UTC by rachelandrew

Adds the overview page for the WebOTP API, and the OTPCredential Interface.

I have added the spec, plus add the spec data into BCD:

- https://github.com/mdn/yari/pull/3964
- https://github.com/mdn/browser-compat-data/pull/10742 

I also fixed a link on Credential, which is why it's in there, as I had it open.

Reviewer @jpmedley

2021-06-03 16:54 UTC, jpmedley commented
These may be marked P1, but they seem awfully hight priority to me.

2021-06-03 16:59 UTC, jpmedley requested changes
Looking good! Just a couple of nits.

2021-06-03 16:59 UTC, jpmedley commented on files/en-us/web/api/webotp_api/index.html
> +<p>Phone numbers are often used as a way to identify the user of an app, and in order to verify that the number belongs to the user, SMS is frequently deployed. A typical scenario would involve a mes
```suggestion
<p>Phone numbers are often used as a way to identify the user of an app, and to verify that the number belongs to the user, SMS is frequently deployed. A typical scenario would involve a message being sent to the user with a one-time password. They would then need to copy and paste that password into a form to verify that the user owns the number.</p>
```

2021-06-03 16:59 UTC, jpmedley commented on files/en-us/web/api/webotp_api/index.html
> +<p>The WebOTP API removes friction from this process, by allowing the password to be received by the app and verified automatically, with no need to copy and paste any codes.</p>
```suggestion
<p>The WebOTP API removes friction from this process by allowing the password to be received by the app and verified automatically, with no need to copy and paste any codes.</p>
```

2021-06-03 16:59 UTC, jpmedley commented on files/en-us/web/api/webotp_api/index.html
> +  <dd>Extends {{domxref("Credential")}} and contains the attributes that are returned when a new one-time password is created.</dd>
What's the argument for mentioning its inheritance here? If the inheritance changes, which happens enough to be a concern, I worry that no one would think to look here for possible updates.

2021-06-04 15:07 UTC, rachelandrew commented on files/en-us/web/api/webotp_api/index.html
> +  <dd>Extends {{domxref("Credential")}} and contains the attributes that are returned when a new one-time password is created.</dd>
Only in that this appears to do very little, so I thought the ref might be useful. Could go either way though.

2021-06-04 17:11 UTC, jpmedley approved these changes

2021-06-04 17:11 UTC, merged