Updated and added pages for private class features
mdn/content pull request #5690
Opened 2021-06-04 19:41 UTC by meyerweb

Private class features needed some better explanation on their reference page, and a short-ish guide to their use added.  I developed these changes and additions in consultation with folks at Igalia who did the private class feature implementation in Blink.

2021-06-07 16:38 UTC, peterbe commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> -browser-compat: javascript.classes.private_class_fields
As mentioned in the meeting, this might have been a bug in the yari tooling or a matter of a merge conflict of old files. 
We should keep this line and then revert back to `<p>{{Compat}}</p>` somewhere around line 250.

2021-06-07 16:39 UTC, peterbe commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +</table>
Also, these lines should reverted to just `{{Specifications}}`.

2021-06-07 16:39 UTC, peterbe commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +<p>{{Compat("javascript.classes.public_class_fields")}}</p>
Ditto :)

2021-06-07 18:23 UTC, wbamberg requested changes
Thanks Eric, this looks great. I had some comments, mostly copy-editing things.

It would be worth drafting a consistent note describing the fact that this is a proposal and not part of the main standard (as I understand it) and using it across all the pages here.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<pre class="brush: js">class ClassWithPrivateField {
Give this the "example-bad" class?

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<h3 id="Private_instance_fields">Private instance fields</h3>
I can't comment on the H2#Examples but... this doesn't read like an "Examples" section, it reads like a "Description" section albeit a very example-rich one (which is a good thing!).

The difference really being that "Description" is telling you essential stuff about the thing, that isn't necessarily given anywhere else, while "Examples" is showing you, well, examples of that stuff.

So I would rename this to "Description".

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<p>There is a provenance restriction on private static fields: Only the class which
I don't know what "provenance restriction" means. If it is a technical term we should link to it. Honestly I think we could just delete this opening clause without losing anything.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<p>The same provenance restriction previously mentioned for private static fields holds
Again here.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<p>{{Compat("javascript.classes.private_class_fields")}}</p>
This should be reverted to `{{Compat}}`

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +<p>{{Compat("javascript.classes.private_class_fields")}}</p>
This should be just `{{Compat}}`.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +<h3 id="Private_instance_fields">Private instance fields</h3>
Oh and now I see that all the class pages do this. Well then I don't know what we should do. Keep it I suppose.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> -  <li><a href="https://github.com/tc39/proposal-class-fields#class-field-declarations-for-javascript">Class field declarations for JavaScript</a> explainer, by the <a href="https://github.com/tc39/pr
Link to the new guide page?

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> -browser-compat: javascript.classes.public_class_fields
As Peter said above, we should have this in front matter and remove it from the `{{Compat}}` call.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +  <p><strong>This page describes experimental features.</strong></p>
As noted before we might want to consider using a common form of wording across all three pages for this issue. Perhaps rather than loaded words like "experimental" we could say that it is a proposal ans not yet part of the ES spec? Also the formatting of the note has be be pedantically exact for the Markdown conversion to work properly. It has to be `<strong>Note:</strong>`.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +  <p>Both Public and private field declarations are an <a
I'm not sure why this change was made.

2021-06-07 18:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +<table class="standard-table">
As before, we should revert this change and just have `{{Specifications}}` here, then it will pick up the spec link from the BCD front matter item.

2021-06-07 21:09 UTC, meyerweb commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +</ul>
So that brings up a much bigger question, but one I’m willing to take on now rather than later.  _Should_ the private class fields (properties?) and methods be given their own pages?  I went back and forth on splitting this page up, so I’m not opposed to the idea.  I just don’t know if it’s a _good_ idea.  What do you think?  (cc:ing @peterbe and @Elchi3 on this question.)

2021-06-07 21:27 UTC, wbamberg commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +</ul>
Also @Rumyra :). In the issue about this: https://github.com/mdn/content/issues/5386 it is expected that they are separate pages, which is what made me think of it. I might have a little preference for separate pages, but don't feel strongly either way :).

2021-06-07 21:44 UTC, meyerweb commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +</ul>
Right, thank you, dumb omission on my part.  I’ll take the discussion over there, Ruth.

2021-06-07 21:53 UTC, peterbe commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +</ul>
Acknowledge the ping but I'm abstaining from opinion. Not confident enough about the content itself at that level.

2021-06-08 03:35 UTC, hamishwillee commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +title: Private class features
I "weakly oppose" separate pages. Separating like this only makes sense if the monolithic whole is impossible to parse and navigation. Generally that is not the case, and there will be common ideas that it makes sense to read together.

2021-06-08 13:35 UTC, Rumyra commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +</ul>
😆 I commented in the project issue about separate pages https://github.com/mdn/content/issues/5386#issuecomment-856770143 but along with @wbamberg my opinion on this isn't strong enough to stop this work getting merged. @hamishwillee made the good point we can split it up later if it's warranted

2021-06-08 19:30 UTC, meyerweb commented
Based on the above conversation(s), I’m going to choose to keep to a single page rather splitting into two pages.  Given that, I’ll address the requests and update.  Thanks, all!

2021-06-08 20:15 UTC, meyerweb commented
I made edits and have pushed changes.  I _think_ I addressed all the requested changes, but the way GitHub mixes requests up so that files aren’t grouped together made it hard to be sure.  Let me know if anything else is needed.

2021-06-09 21:23 UTC, wbamberg requested changes
Thanks for the updates! It looks like the reinstated `browser-compat` front matter item for public fields needs to be `javascript.classes.public_class_fields`, not `javascript.classes.private_class_fields`?

There were a couple of other comments that still might need attention (but please do let me know if you don't think they are applicable):

* https://github.com/mdn/content/pull/5690#discussion_r646808664

* https://github.com/mdn/content/pull/5690#discussion_r646811951 - it's worth having a link to the reference page from this guide page.

* https://github.com/mdn/content/pull/5690#discussion_r646832788 ... and a link going back the other way...

Finally I wonder if it's worth having some common way to describe the status of these features.

* https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields has a note saying that public class fields are an experimental stage 3 TC39 proposal. 
* https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields says private fields are stage 3 but not as a note and not mentioning experimental.
* https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Guide/Working_With_Private_Class_Features doesn't say anything about the status of private fields.

It might be good to use a common message across all three pages - perhaps a modified version of the note in https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields ?

2021-06-09 21:23 UTC, wbamberg commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +browser-compat: javascript.classes.private_class_fields
Should this be ` browser-compat: javascript.classes.public_class_fields` ?

2021-06-09 21:32 UTC, meyerweb commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +browser-compat: javascript.classes.private_class_fields
No, it should be `javascript.classes.private_class_fields`.  They’re different things.

2021-06-09 21:33 UTC, meyerweb commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +browser-compat: javascript.classes.private_class_fields
(Hit return too soon)  As for the two-way links, agreed, and I missed those.  I’ll harmonize the warning notes as well.  Stand by!

2021-06-09 21:50 UTC, meyerweb commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +<p>And you can have static private fields, for things you want to be both private and set in stone at construction.</p>
I tried addressing this without adding subheadings in the latest push; let me know if it feels like it works.  If not, I’ll see about using headings.

2021-06-10 00:24 UTC, wbamberg commented on files/en-us/web/javascript/guide/working_with_private_class_features/index.html
> +<p>And you can have static private fields, for things you want to be both private and set in stone at construction.</p>
Yes, I like this approach :).

2021-06-10 19:47 UTC, sideshowbarker commented
> Finally I wonder if it's worth having some common way to describe the status of these features.
> 
>     * [pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields](https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) has a note saying that public class fields are an experimental stage 3 TC39 proposal.
> 
>     * [pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields](https://pr5690.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) says private fields are stage 3 but not as a note and not mentioning experimental.


It seems both of those have outdated status info at this point, and should be removed. See https://github.com/mdn/content/commit/c59c12266cf301fa52ab28a609c90ce7966b3014 and https://github.com/mdn/content/pull/5850 — the Class Fields proposal was merged into the ES spec in April. And because also in April, Safari 14.1 shipped with full support for class fields, that means all browser engines now have full support.

2021-06-10 19:58 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
>  <ul>
I’m curious about the rationale for dropping these links. I’m not objecting — just wondering.

2021-06-10 19:58 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/classes/private_class_fields/index.html
> +  stage 3 proposal</a> to allow private class features by using a hash
Given that the proposal was merged into the ES spec April, the part part about *There is however a stage 3 proposal to allow private class features by using a hash # prefix* should be changed to just, *However, private class fields can be created using a hash # prefix*, or some such. And also, I think everywhere the content says *class properties* or *class features*, it should instead say *class fields*.

2021-06-10 20:27 UTC, meyerweb commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
>  <ul>
I dropped the TC39 link because TC39 documentation seems to have a habit of disappearing once the proposals become ECMAized.  I can’t remember why the other one; I’ll recheck it and either restore or keep off.

2021-06-10 20:29 UTC, meyerweb commented on files/en-us/web/javascript/reference/classes/public_class_fields/index.html
> +browser-compat: javascript.classes.private_class_fields
@sideshowbarker makes a good point: the warnings are about to become moot, and should be removed.  So I’ll harmonize by removing the warnings and patching the holes.  Once more, stand by!

2021-06-18 02:51 UTC, hamishwillee commented
What's blocking this? Anything I can do to help?

2021-06-18 18:13 UTC, meyerweb commented
> What's blocking this? Anything I can do to help?

Actually, I’m not sure if this just needs review, or if it needs more updates.  @wbamberg, I think you’re the arbiter of that, yes?

2021-06-18 18:33 UTC, wbamberg commented
Most of the comments in https://github.com/mdn/content/pull/5690#pullrequestreview-680150955 are addressed (thanks!). The only remaining thing in there is to update the various notes and things about it being experimental, not in the ES spec and so on.

@sideshowbarker already removed the note about this from "public class fields" (https://github.com/mdn/content/commit/c59c12266cf301fa52ab28a609c90ce7966b3014), so the only remaining part is the suggestion in https://github.com/mdn/content/pull/5690#discussion_r649487506 to drop the reference to stage 3 in "private class fields".  With that change I'm 👍 on this PR.

@sideshowbarker also had this comment in https://github.com/mdn/content/pull/5690#discussion_r649487506 :

> I think everywhere the content says class properties, it should instead say class fields.

2021-06-22 05:31 UTC, sideshowbarker approved these changes

2021-06-22 23:07 UTC, hamishwillee commented
@wbamberg Anything else you need from this?

2021-06-22 23:26 UTC, wbamberg approved these changes
Thanks for all your work on this, Eric!

2021-06-22 23:26 UTC, merged