add detail about qualified attribute names to Element.getAttributeNames documentation
mdn/content pull request #5715
Opened 2021-06-06 03:37 UTC by trusktr

> What was wrong/why is this fix needed? (quick summary only)

[The spec](https://dom.spec.whatwg.org/#dom-element-getattributenames) says the names should be [qualified](https://dom.spec.whatwg.org/#concept-attribute-qualified-name) which it describes as being prefixed by `namespace:`.

> MDN URL of the main page changed

https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNames

> Issue number (if there is an associated issue)

> Anything else that could help us review it

https://bugs.chromium.org/p/chromium/issues/detail?id=1216840

2021-06-06 05:40 UTC, sideshowbarker requested changes

2021-06-06 05:40 UTC, sideshowbarker commented on files/en-us/web/api/element/getattributenames/index.html
> +  names returned prefixed by the namespace and a colon (f.e. <strong><code>namespace:other-attribute</code></strong>).</p>
In Safari, Firefox, and Chrome, `getAttributeNames()` doesn’t actually return the names prefixed by the namespace and a colon, right?

If so, then this text should be rewritten to state something like, _“While for namespaced attributes, the DOM spec requires `getAttributeNames()` to return the attribute name prefixed by the namespace and a colon (for example, `namespace:attribute-name`), browsers instead return just the attribute name.”_

@annevk Can you confirm that suggested language is correct? And also if so, why does the DOM spec have this requirement, if no UAs actually conform to it?

2021-06-06 05:41 UTC, sideshowbarker commented
Given that no browsers actually follow his requirement, have you filed an issue against the DOM spec?

2021-06-08 08:52 UTC, sideshowbarker requested changes
So it seems that both the prose and example added in the PR’s patch as currently written don’t actually conform to the spec requirements. Therefore, I’ve added some commit suggestions which I think should bring both the patch’s prose and example into conformance with the actual spec requirements.

Of course feel free rewrite or refine the suggestions in any way want — if you find the wording is confusing or wrong, or if you find the suggestions can be improved upon in any way.

---

Details:

The actual root spec requirement is at https://dom.spec.whatwg.org/#dom-element-getattributenames:

> The <dfn class="dfn-paneled idl-code" data-dfn-for="Element" data-dfn-type="method" data-export="" id="dom-element-getattributenames"><code>getAttributeNames()</code></dfn> method steps are to return the <a data-link-type="dfn" href="#concept-attribute-qualified-name" id="ref-for-concept-attribute-qualified-name⑧">qualified names</a> of the <a data-link-type="dfn" href="#concept-attribute" id="ref-for-concept-attribute⑤⓪">attributes</a> in <a data-link-type="dfn" href="https://heycam.github.io/webidl/#this" id="ref-for-this①⑥⑤">this</a>’s <a data-link-type="dfn" href="#concept-element-attribute" id="ref-for-concept-element-attribute①⑤">attribute list</a>, in order; otherwise a new <a data-link-type="dfn" href="https://infra.spec.whatwg.org/#list" id="ref-for-list①⓪">list</a>.

…where `qualified names` is a link to https://dom.spec.whatwg.org/#concept-attribute-qualified-name:

> An <a data-link-type="dfn" href="#concept-attribute" id="ref-for-concept-attribute⑥①">attribute</a>’s <dfn class="dfn-paneled" data-dfn-for="Attr" data-dfn-type="dfn" data-export="" id="concept-attribute-qualified-name">qualified name</dfn> is its <a data-link-type="dfn" href="#concept-attribute-local-name" id="ref-for-concept-attribute-local-name②③">local name</a> if its <a data-link-type="dfn" href="#concept-attribute-namespace-prefix" id="ref-for-concept-attribute-namespace-prefix⑥">namespace prefix</a> is null, and its <a data-link-type="dfn" href="#concept-attribute-namespace-prefix" id="ref-for-concept-attribute-namespace-prefix⑦">namespace prefix</a>, followed by "<code>:</code>", followed by its <a data-link-type="dfn" href="#concept-attribute-local-name" id="ref-for-concept-attribute-local-name②④">local name</a>, otherwise.

Note in particular: That says that qualified name is the namespace *prefix*, followed by ":", followed by its local name.

That’s different from what’s currently in this PR patch’s prose:

> namespaced attributes have their names returned prefixed by the namespace and a colon

So the commit suggestions I added include updating the prose part of the patch to conform to the actual spec requirements.

The spec requirements are actually different from what’s currently in this PR patch’s example code — that is, the current patch’s example code is this:

```js
const element = document.createElement('div')

element.setAttribute('foo', 'bar')
element.setAttributeNS('http://example.com/lorem', 'foo', 'bar')

// Iterate over element's attributes
for (let name of element.getAttributeNames()) {
  let value = element.getAttribute(name);
  console.log(name, value);
}

// logs:
// foo bar
// http://example.com/lorem:foo bar
```
One mismatch there is, the spec doesn’t say `getAttributeNames()` must return `http://example.com/lorem:foo` (the same mismatch that this PR patch’s prose has).

The second mismatch is that `element.setAttributeNS('http://example.com/lorem', 'foo', 'bar')` isn’t actually setting a namespace *prefix* for the `foo` attribute (it’s setting only the *namespace* itself) — and therefore per-spec the expected output for both iterations of that loop is just `foo bar`.

A code example which matches the actual spec requirements would be something like this:

```js
const element = document.createElement('a')

// set "href" attribute with no namespace and no namespace prefix
element.setAttribute('href', 'https://example.com')
// set "href" attribute with namespace and also "xlink" namespace prefix
element.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', 'https://example.com')
// set "show" attribute with namespace but no namespace prefix
element.setAttributeNS('http://www.w3.org/1999/xlink', 'show', 'new')

// Iterate over element's attributes
for (let name of element.getAttributeNames()) {
  let value = element.getAttribute(name);
  console.log(name, value);
}

// logs:
// href https://example.com
// xlink:href https://example.com
// show new
```
…and so the commit suggestions I added include updating the example code to that.

2021-06-08 08:52 UTC, sideshowbarker commented on files/en-us/web/api/element/getattributenames/index.html
> +  names returned prefixed by the namespace and a colon (f.e. <strong><code>namespace:other-attribute</code></strong>).</p>
```suggestion
<p>The names returned by <strong><code>getAttributeNames()</code></strong> are <em>qualified</em> attribute names, meaning that attributes with a namespace prefix have their names returned with that namespace prefix (<em>not</em> the actual namespace URI), followed by a colon, followed by the attribute name (for example, <strong><code>xlink:href</code></strong>), while any attributes which have no namespace prefix have their names returned as-is (for example, <strong><code>href</code></strong>).</p>
```

2021-06-08 08:52 UTC, sideshowbarker commented on files/en-us/web/api/element/getattributenames/index.html
>  <h2 id="Example">Example</h2>
```suggestion
<h2 id="Example">Example</h2>

<p>The following example shows how:</p>

<ul>
  <li>For an attribute which has a namespace prefix, <code>getAttributeNames()</code> returns that namespace prefix along with the attribute name.</li>
  <li>For an attribute which has no namespace prefix, <code>getAttributeNames()</code> returns just the attribute name, as-is.</li>
</ul>

<p>It’s important to understand that:
<ol>
  <li>An attribute can be present in the DOM with a namespace but lacking a namespace prefix.</li>
  <li>For an attribute in the DOM that has a namespace but lacks a namespace prefix, <code>getAttributeNames()</code> will return just the attribute name, with no indication that the attribute is in a namespace.</li>
</ol>

<p>The example below includes such a “namespaced but without a namespace prefix” case.</p>
```

2021-06-08 08:52 UTC, sideshowbarker commented on files/en-us/web/api/element/getattributenames/index.html
> +// http://example.com/lorem:foo bar
```suggestion
<pre class="brush:js">
const element = document.createElement('a')

// set "href" attribute with no namespace and no namespace prefix
element.setAttribute('href', 'https://example.com')
// set "href" attribute with namespace and also "xlink" namespace prefix
element.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', 'https://example.com')
// set "show" attribute with namespace but no namespace prefix
element.setAttributeNS('http://www.w3.org/1999/xlink', 'show', 'new')

// Iterate over element's attributes
for (let name of element.getAttributeNames()) {
  let value = element.getAttribute(name);
  console.log(name, value);
}

// logs:
// href https://example.com
// xlink:href https://example.com
// show new
```

2021-07-26 12:05 UTC, sideshowbarker approved these changes

2021-07-26 12:09 UTC, sideshowbarker approved these changes

2021-07-26 12:09 UTC, merged

2021-07-26 12:10 UTC, annevk approved these changes

2021-07-26 12:10 UTC, annevk commented on files/en-us/web/api/element/getattributenames/index.html
> +<p>The names returned by <strong><code>getAttributeNames()</code></strong> are <em>qualified</em> attribute names, meaning that attributes with a namespace prefix have their names returned with that
Nit: s/URI//

2021-07-28 06:16 UTC, sideshowbarker commented on files/en-us/web/api/element/getattributenames/index.html
> +<p>The names returned by <strong><code>getAttributeNames()</code></strong> are <em>qualified</em> attribute names, meaning that attributes with a namespace prefix have their names returned with that
> Nit: s/URI//

Thanks – opened https://github.com/mdn/content/pull/7373