Replace <sub>/<sup> in api/*
mdn/content pull request #5766
Opened 2021-06-07 16:48 UTC by teoli2003

This is part of #5012 and deals with files in api/*.

Notes for the reviewer: 
- I have replaced m/s\<sup>2\<\sup> by the unicode character: m/s².
- I had some \<sub> used to denote indices in formulas and I have replaces them by _ or nothing depending of the context. Note that my knowledge and use of LaTeX makes me biased ans I read _ as marks for indices very easily.

2021-06-07 23:44 UTC, hamishwillee commented on files/en-us/web/api/devicemotionevent/acceleration/index.html
> +    per second squared (m/s²)</a>.</p>
FWIW I'm OK with the inconsistency of approach - the result is better and does no harm

2021-06-07 23:46 UTC, hamishwillee commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
Not so sure about this. I probably would have left the sub in. @wbamberg did you have an opinion on this.

Note the PR is in draft, but I figure we can resolve the question early.

2021-06-08 02:42 UTC, wbamberg commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
I would probably have left these as `<sub>` too. But I'd be OK with either.

2021-06-08 02:44 UTC, wbamberg commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
@Gregoor , what would the converter do with markup like `<code>matrix3d(<var>m<sub>11</sub></var>, <var>m<sub>12</sub></var>, <var>m<sub>13</sub></var>, <var>m<sub>14</sub></var>, <var>m<sub>21</sub></var>, <var>m<sub>22</sub></var>, <var>m<sub>23</sub></var>, <var>m<sub>24</sub></var>, <var>m<sub>31</sub></var>, <var>m<sub>32</sub></var>, <var>m<sub>33</sub></var>, <var>m<sub>34</sub></var>, <var>m<sub>41</sub></var>, <var>m<sub>42</sub></var>, <var>m<sub>43</sub></var>, <var>m<sub>44</sub></var>)</code>`?

Leave the whole thing as HTML?

2021-06-08 05:56 UTC, teoli2003 commented on files/en-us/web/api/devicemotionevent/acceleration/index.html
> +    per second squared (m/s²)</a>.</p>
Yes, I think this works well for units.

2021-06-08 08:30 UTC, teoli2003 commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
I have no strong feeling here. An argument is that is is a kind of place were we expect valid JavaScript, and \<sub aren't. I'm leaving it that way for the moment (pass 2), but revisit this once we have Gregor's opinion.

2021-06-08 08:37 UTC, Gregoor commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
@wbamberg surprisingly it does convert it to `matrix3d(m11, m12, m13, m14, m21, m22, m23, m24, m31, m32, m33, m34, m41, m42, m43, m44)`. Which I would consider a bug, since there is no conversion rule for `<sub>`, but the current implementation for turning nodes into text just checks at a high level if it finds a convertible one (in this case `<var>`).

2021-06-08 08:38 UTC, teoli2003 commented
Thanks for the early review! 

I've done a second pass, correcting obvious bugs, but alse re-evaluating some of the decisions I took in the first pass.

I want to mention the following pages:

1. **WebXR Device API: Lighting** ([original](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Lighting), [as proposed in this PR](https://pr5766.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WebXR_Device_API/Lighting))
In this one, I think the two subscripts were needed to match the drawings. Finally, as the capital theta was already an unusual Unicode character, I opted to use a Unicode Latin Subscript Letter for both the subscript i and r: Θᵢ and Θᵣ.
It looks good, and I think it semantically makes sense as it is a name. (Note that like for m/s², this solution doesn't scale to all similar cases)
2. **XRRigidTransform.matrix** ([original](https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/matrix), [as proposed in this PR](https://pr5766.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/XRRigidTransform/matrix))
I wanted to do the same here as p_x, p_y, p_z are variable names and not true indices: but there aren't any Unicode Latin Subscript Letter for _y_ and _z_ (but there are for _x_). So I decided to revert and keep the \<sub> for these three. The look matches the MathML just below, and I think it is important. (The MathML doesn't render well in many browsers, but that's a separate issue.)
3. **WebGLRenderingContext.blendFuncSeparate** ([original](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFuncSeparate), [as proposed in this PR](https://pr5766.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WebGLRenderingContext/blendFuncSeparate)) and
**WebGLRenderingContext.blendFunc** ([original](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc), [as proposed in this PR](https://pr5766.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WebGLRenderingContext/blendFunc))
In these pages, R<sub>S</sub>, G<sub>S</sub>, B<sub>S</sub> and A<sub>S</sub> are the RGB(A) of the source, and R<sub>D</sub>, G<sub>D</sub>, B<sub>D</sub> and A<sub>D</sub> are the RGB(A) of the destination. In my first commit, I tried to replace the sub elements with _, but it was ugly. So I'm reverting to keep the \<sub>s. But as these variables were not defined in the pages, I've added an explanation for them.
4. **WebXR Device API: Cameras** ([original](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Cameras), [as proposed in this PR](https://pr5766.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/WebXR_Device_API/Cameras))
In this one, I wanted to match the MathML style of the matrix; as there werent too many of them, I used the Unicode characters. But I'm open to bring back \<sub>s. (For the same, I've also _italicized_ with \<em>s)

The other changes in this 2nd pass are fixes of small glitchs (typo-like)

2021-06-08 09:04 UTC, teoli2003 commented on files/en-us/web/api/dommatrixreadonly/index.html
> + <p>For a 3D matrix, the returned string contains all 16 elements and takes the form <code>matrix3d(<var>m11</var>, <var>m12</var>, <var>m13</var>, <var>m14</var>, <var>m21</var>, <var>m22</var>, <va
I think I will keep it that way then, as the ultimate result after the HTML-MD migration will be the same.

2021-06-09 19:35 UTC, wbamberg requested changes
Thanks @teoli2003 for making thoughtful choices here! I would probably have kept more `<sub>` elements, but that seems like a matter of opinion.

But I do think we should do something about these footnotes, which will not work in Markdown. It seems to me that in all these cases it would be simple to change them into normal prose without losing anything.

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/filesystemflags/index.html
> +<p id="note1">[1] When <code>create</code> is <code>false</code>, the value of <code>exclusive</code> is irrelevant and ignored.</p>
This isn't going to work in Markdown. I think it would be fine to keep the cells as n/a and have a sentence before the table like "Note that when `create` is false, the value of `exclusive` is irrelevant and ignored."

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.html
> +<p id="note1">[1] In Gecko, {{event("dragend")}} is not dispatched if the source node is moved or removed during the drag (e.g. on drop or {{event("dragover")}}). <a href="https://bugzilla.mozilla.or
Again here. I think this could be rewritten to not be a note, especially as it's only referenced in one place. Or even omitted entirely (it's in the BCD for `dragend`, which seems to me that best place for it: https://developer.mozilla.org/en-US/docs/Web/API/Document/dragend_event#browser_compatibility).

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/push_api/best_practices/index.html
>  <p><a id="mitigations-footnote-1">[1]</a> In the case of Firefox, see {{bug(1524619)}}, in which we find that Firefox 68 implements this, disabled by default, behind the preference <code>dom.webnotif
Again here. Since the footnote is only referenced in the immediately preceding paragraph, let's just make it another paragraph.

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/rtcrtptransceiverdirection/index.html
> +<p id="note_1">[1] To determine if a sender has at least one active encoding, the {{Glossary("user agent")}} gets its parameters using {{domxref("RTCRtpSender.getParameters()")}}, then looks at the p
/me cries about more footnotes.

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/rtcicecandidatestats/priority/index.html
> +    the priority of the candidate's type and <em>p_local</em> is the priority of
I would personally have kept `<sub>` here and in similar places, rather than replacing the `_`. But I think this is a matter of opinion and general familiarity with different conventions, and I don't really feel qualified to have a strong opinion.

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/webxr_device_api/cameras/index.html
> +<pre class="brush: js">let matrixArray = [a1, a2, a3, a4, a5, a6, a7, a8,
Worth noting that in cases like this Yari already discards the internal markup.

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/xrinputsourcearray/foreach/index.html
> +            href="#spec-iterables">[1]</a>)</td>
More footnotes. Again I'm not sure how the footnote model is helping readers here, rather than just having a paragraph of text after the table (assuming even that is useful).

2021-06-09 19:35 UTC, wbamberg commented on files/en-us/web/api/window/unhandledrejection_event/index.html
> + <li>{{domxref("WindowEventHandlers.onunhandledrejection", "onunhandledrejection")}} event handler property (See <a href="#seealso-footnote-1">[1]</a>)</li>
Let's just delete this one, or if it is really worth keeping, make it a paren:

> * `onunhandledrejection` event handler property (this is defined on the WindowEventHandlers mixin, which is available on both the Window interface and all types of Worker interfaces).

2021-06-10 04:25 UTC, teoli2003 commented on files/en-us/web/api/filesystemflags/index.html
> +<p id="note1">[1] When <code>create</code> is <code>false</code>, the value of <code>exclusive</code> is irrelevant and ignored.</p>
Good idea. Fixed in next commit.

2021-06-10 04:33 UTC, teoli2003 commented on files/en-us/web/api/html_drag_and_drop_api/drag_operations/index.html
> +<p id="note1">[1] In Gecko, {{event("dragend")}} is not dispatched if the source node is moved or removed during the drag (e.g. on drop or {{event("dragover")}}). <a href="https://bugzilla.mozilla.or
Yes, gone in next commit.

2021-06-10 04:50 UTC, teoli2003 commented on files/en-us/web/api/push_api/best_practices/index.html
>  <p><a id="mitigations-footnote-1">[1]</a> In the case of Firefox, see {{bug(1524619)}}, in which we find that Firefox 68 implements this, disabled by default, behind the preference <code>dom.webnotif
Yes, update in next commit.

As the page is marked as a draft and not linked, I've opened an issue to get it finished: #5840.

2021-06-10 05:09 UTC, teoli2003 commented on files/en-us/web/api/rtcrtptransceiverdirection/index.html
> +<p id="note_1">[1] To determine if a sender has at least one active encoding, the {{Glossary("user agent")}} gets its parameters using {{domxref("RTCRtpSender.getParameters()")}}, then looks at the p
Here, I just kept the note in place, removing the footnote links (and anchor). Works well as the table is small. (Fixed in next commit)

2021-06-10 05:11 UTC, teoli2003 commented on files/en-us/web/api/webxr_device_api/cameras/index.html
> +<pre class="brush: js">let matrixArray = [a1, a2, a3, a4, a5, a6, a7, a8,
Yep, I noticed. Removed to please my greps ;-)

2021-06-10 05:35 UTC, teoli2003 commented on files/en-us/web/api/rtcicecandidatestats/priority/index.html
> +    the priority of the candidate's type and <em>p_local</em> is the priority of
I brought back the `\<sub>` here. I wasn't happy with the underscore. (In next commit)

2021-06-10 05:44 UTC, teoli2003 commented on files/en-us/web/api/xrinputsourcearray/foreach/index.html
> +            href="#spec-iterables">[1]</a>)</td>
This footnote was useless (it is a kind of automatic mixin and we remove them). I'm getting rid of it. (in next commit)

2021-06-10 05:46 UTC, teoli2003 commented on files/en-us/web/api/window/unhandledrejection_event/index.html
> + <li>{{domxref("WindowEventHandlers.onunhandledrejection", "onunhandledrejection")}} event handler property (See <a href="#seealso-footnote-1">[1]</a>)</li>
Yes! Mixin-related. (Gone in next commit)

2021-06-10 15:31 UTC, wbamberg approved these changes
Thanks for the updates @teoli2003 !

2021-06-10 15:31 UTC, merged

2021-06-11 00:05 UTC, hamishwillee commented
Seconding what Will said. Good decisions.