CSS grouping rule
mdn/content pull request #585
Opened 2020-12-22 15:42 UTC by rachelandrew

I am working on #344 in which I discovered that many of the CSSRule interfaces only had their main interface page. So there will be a few linked PRs as I work through them.

This one adds the missing pages to https://developer.mozilla.org/en-US/docs/Web/API/CSSGroupingRule and fixes up some stuff on the interface page.

2020-12-23 06:47 UTC, sideshowbarker commented
Should @jpmedley review this one, or is it OK for me to review it?

2020-12-24 13:56 UTC, rachelandrew commented
@sideshowbarker if you are about then I'm sure it's fine - prior to Yari I was just adding directly to MDN - I'm going to have a whole stack of these and can always do a PR for any additional snags he spots on return.

2020-12-28 09:41 UTC, sideshowbarker commented
> @sideshowbarker if you are about then I'm sure it's fine

OK, thanks — I’ll make some time tonight to review this (and others)

2020-12-28 21:12 UTC, sideshowbarker requested changes

2020-12-28 21:12 UTC, sideshowbarker commented on files/en-us/web/api/cssgroupingrule/insertrule/index.html
> +<dl>
```suggestion
<dl>
 <dt>A {{domxref("DOMException")}} IndexSizeError</dt>
 <dd>Thrown if <var>index</var> is greater than the number of child CSS rules.</dd>
```

2020-12-28 21:12 UTC, sideshowbarker commented on files/en-us/web/api/cssgroupingrule/insertrule/index.html
> +  <dd>Thrown if the new rule is an <code>@namespace</code> at-rule, and list contains anything other than <code>@import</code> at-rules, and <code>@namespace</code> at-rules.</dd>
```suggestion
  <dd>Thrown if the rule being inserted is an <code>@namespace</code> at-rule, and the list of child CSS rules contains anything other than <code>@import</code> at-rules and <code>@namespace</code> at-rules.</dd>

```

2021-01-01 13:35 UTC, sideshowbarker approved these changes

2021-01-01 13:35 UTC, merged