Adds RemotePlayback
mdn/content pull request #5858
Opened 2021-06-10 15:28 UTC by rachelandrew

Adds the `RemotePlayback` interface.

I have also created a PR for the URLs in BCD, so once that is merged the specs will show up.

Reviewer: @jpmedley

2021-06-14 15:03 UTC, jpmedley requested changes, later dismissed

2021-06-14 15:03 UTC, jpmedley commented on files/en-us/web/api/remoteplayback/watchavailability/index.html
> +  <dd>A callback that allows the page to obtain the remote playback device availability for the corresponding media element.</dd>
`callback RemotePlaybackAvailabilityCallback = void(boolean available);` (From the IDL.)

Can you work in somehow that this gets passed a boolean?

2021-06-14 15:03 UTC, jpmedley commented on files/en-us/web/api/remoteplayback/watchavailability/index.html
> +<p>In the following example, after checking that there is no currently connected device, <code>watchAvailability</code> is used to watch for remote devices becoming available. <a href="https://beaufo
```suggestion
<p>In the following example, after checking that there is no currently connected device, <code>watchAvailability()</code> is used to watch for remote devices becoming available. <a href="https://beaufortfrancois.github.io/sandbox/media/remote-playback.html">See the working example</a> (Requires a supported device and a connected remote playback device).</p>
```

2021-06-15 10:47 UTC, rachelandrew commented on files/en-us/web/api/remoteplayback/prompt/index.html
> +  <dd>User agents <em>may</em> throw this error if there is already an unsettled promise for this media element, or even this browsing context.</dd>
as far as a developer goes it probably doesn't matter, the UA might just ignore the second request and continue with the original promise. Only matters to the developer if they see the error, so I've reworded this.

2021-06-15 10:49 UTC, rachelandrew commented on files/en-us/web/api/remoteplayback/cancelwatchavailability/index.html
> +<p>If a <code>callbackId</code> of a specific device is passed in, then that device will be removed from the list of watched devices. Otherwise, the whole list will be cleared.</p>
Could be, I thought it worth introducing the fact this can work to clear one or all.

2021-06-15 15:58 UTC, jpmedley commented on files/en-us/web/api/remoteplayback/cancelwatchavailability/index.html
> +<p>If a <code>callbackId</code> of a specific device is passed in, then that device will be removed from the list of watched devices. Otherwise, the whole list will be cleared.</p>
I think reference has to be constructed for someone dipping in at any point and leaving. Someone can read it all the way through, but it shouldn't be needed. 

* If this stays here, someone reading all the way through will see it, but someone just reading the `id` parameter will likely miss it.
* If it moves to the `id` parameter, both will see it.

Please move it.

2021-06-18 14:23 UTC, rachelandrew commented
@jpmedley I've made the requested change, not sure why I can't re-request the review.

2021-06-30 16:12 UTC, rachelandrew commented
@jpmedley I don't think there is anything outstanding on this one.

2021-06-30 18:17 UTC, jpmedley approved these changes

2021-06-30 18:17 UTC, merged