Remove unnecessary span elements in Web API Docs
mdn/content pull request #5859
Opened 2021-06-10 15:41 UTC by mfuji09

> What was wrong/why is this fix needed? (quick summary only)

There are some span elements which are unnecessary in various documents.

> MDN URL of the main page changed

https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get
https://developer.mozilla.org/en-US/docs/Web/API/Element/slot
https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath
https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API/Using_the_Media_Capabilities_API
https://developer.mozilla.org/en-US/docs/Web/API/MediaList
https://developer.mozilla.org/en-US/docs/Web/API/MediaList/mediaText
https://developer.mozilla.org/en-US/docs/Web/API/URL/port
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Compressed_texture_formats

2021-06-10 17:16 UTC, wbamberg requested changes
It looks like an error crept into one of these?

2021-06-10 17:16 UTC, wbamberg commented on files/en-us/web/api/media_capabilities_api/using_the_media_capabilities_api/index.html
> +<p><span class="seoSummary">The <a href="/en-US/docs/Web/API/Media_Capabilities_API">Media Capabilities API</a> provides several key features to help you better decide how to handle media, but also t
Looks like this removed the closing tag but not the opening one? If we added a paragraph break after "in real time." we could remove the opening tag as well.

2021-06-11 16:41 UTC, mfuji09 commented on files/en-us/web/api/media_capabilities_api/using_the_media_capabilities_api/index.html
> +<p><span class="seoSummary">The <a href="/en-US/docs/Web/API/Media_Capabilities_API">Media Capabilities API</a> provides several key features to help you better decide how to handle media, but also t
It's my mistake. It shouldn't be delete in this subject. I have correct it. Thank you!

2021-06-11 17:45 UTC, wbamberg approved these changes
Thanks!

2021-06-11 17:45 UTC, merged