HTTP RTT Header - client hint doc
mdn/content pull request #5883
Opened 2021-06-11 07:13 UTC by hamishwillee

This header is in the Network Information spec here: https://wicg.github.io/netinfo/#rtt-request-header-field

There is not all that much information, but you can see it is associated with the [NetworkInformation.rtt](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/rtt) and there is some useful general guidance in https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints.

Spec update is in https://github.com/mdn/browser-compat-data/pull/10951

2021-06-11 07:14 UTC, hamishwillee commented on files/en-us/web/http/headers/rtt/index.html
> + <p>The hint allows a server to choose what information is sent based on the network responsiveness/latency. For example, it might choose not to respond to some requests.</p>
Note, I am not completely happy with this. It is true that this is something it might do, but I'm not sure what the limits are, if any, on what a server can do. For example, could it decide to respond with a low res image instead?

2021-06-14 14:19 UTC, Elchi3 commented on files/en-us/web/http/headers/rtt/index.html
> + <p>The hint allows a server to choose what information is sent based on the network responsiveness/latency. For example, it might choose not to respond to some requests.</p>
I'm not an expert with client hints. I thought upon a bad connection `RTT` is useful to serve **less** resources and `Downlink` is useful to serve **smaller** resources?

2021-06-15 02:20 UTC, hamishwillee commented on files/en-us/web/http/headers/rtt/index.html
> + <p>The hint allows a server to choose what information is sent based on the network responsiveness/latency. For example, it might choose not to respond to some requests.</p>
@Elchi3 Thanks.  FYI only [the example chrome gives](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints#helping_users_on_slow_networks) use the hints to determine a "network score" that then decides whether to serve web fonts, hero images, carousel and associated javascript. In other words "kind of" :-). 

Upshot though is that my question is also kind of answered - the server can do what it likes.

I still don't really get the RTT case though. Server requests RTT, client provides it, so now server knows that latency is low and decides not to send web fonts, and a carousel. Presumably the request for these is still made and this implies that the page has to configure itself to reasonably work without that information.

2021-06-15 07:28 UTC, hamishwillee commented
@Elchi3 OK, this got bigger
- I added the missing network headers ECT and Downlink
- Updated Save-Data to better cross link.
- Cross linked all of these to the equivalent web API 
- Added sections for client headers in both the main headers page and in the client headers page. 

I think this is a good place to stop for now. In future though it might be worth having a client headers guide much like https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints and cut back the glossary entry. This gives us a structure to work with now though.

Can you please review again :-)

2021-06-15 09:16 UTC, Elchi3 requested changes
Thanks for your work! Some comments.

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/ect/index.html
> +<pre class="brush: http">ect: &lt;value&gt;</pre>
```suggestion
<pre class="brush: http">ECT: &lt;value&gt;</pre>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/ect/index.html
> +<pre class="brush: http">ect: &lt;value&gt;</pre>
Describe \<value> in a Directives section?

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/ect/index.html
> +<p>Server first needs to opt in to receive the <code>Downlink</code> header by sending the response headers {{HTTPHeader("Accept-CH")}} containing <code>Downlink</code>.</p>
```suggestion
<p>A server first needs to opt in to receive the <code>ECT</code> header by sending the {{HTTPHeader("Accept-CH")}} response header containing <code>ECT</code>.</p>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/ect/index.html
> +<p>Then on subsequent requests the client might send <code>Downlink</code> header back:</p>
```suggestion
<p>Then on subsequent requests the client might send an <code>ECT</code> header back:</p>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/ect/index.html
> +    <li>{{HTTPHeader("ECT")}}</li>
```suggestion
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/downlink/index.html
> +    <li>{{HTTPHeader("Downlink")}}</li>
```suggestion
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/index.html
> +<p>HTTP {{Glossary("Client_hints", "Client hints")}} are a set of request headers that provide useful information about the client such as device type and network conditions, and allow servers to opt
```suggestion
<p>HTTP {{Glossary("Client_hints", "Client hints")}} are a set of request headers that provide useful information about the client such as device type and network conditions, and allow servers to optimize what is served for those conditions.</p>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/index.html
> +  <div>
I think you don't need the div and p elements in dd.

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/rtt/index.html
> +<p>The RTT value is rounded to the nearest 25 milliseconds to prevent fingerprinting; There are many other mechanisms an attacker might use to obtain similar round-trip information.</p>
Same here, I would move this into a "Directives" section providing details about \<number>

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/rtt/index.html
> +<p>Server first needs to opt in to receive the <code>RTT</code> header by sending the response headers {{HTTPHeader("Accept-CH")}} containing <code>RTT</code>.</p>
```suggestion
<p>A server first needs to opt in to receive the <code>RTT</code> header by sending the {{HTTPHeader("Accept-CH")}} response header containing <code>RTT</code>.</p>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/rtt/index.html
> +<p>Then on subsequent requests the client might send <code>RTT</code> header back:</p>
```suggestion
<p>Then on subsequent requests the client might send an <code>RTT</code> header back:</p>
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/rtt/index.html
> +    <li>{{HTTPHeader("RTT")}}</li>
```suggestion
```

2021-06-15 09:16 UTC, Elchi3 commented on files/en-us/web/http/headers/save-data/index.html
> +       <li>{{HTTPHeader("Save-Data")}}</li>
```suggestion
```

2021-06-18 01:13 UTC, hamishwillee commented on files/en-us/glossary/client_hints/index.html
> +<p>The set of "hint" headers are listed in the topic <a href="/en-US/docs/Web/HTTP/Headers#client_hints">HTTP Headers</a> and <a href="#hint_types">summarised below</a>.</p>
Arrgg. Thanks. US-English is my bane.

2021-06-18 01:17 UTC, hamishwillee commented on files/en-us/web/http/headers/accept-ch/index.html
> +{{Specifications}}
Reverted. Can't wait for this to work.

2021-06-18 01:23 UTC, hamishwillee commented on files/en-us/web/http/headers/rtt/index.html
> +    <li>{{HTTPHeader("RTT")}}</li>
@Elchi3 FYI the inclusion was deliberate. Now that Yari does the right thing and renders this "link to self" as a black unclickable link, it makes this list into a clear "set", which I quite like (and is easy to copy-paste when documenting new mthods) :-). Upshot I will do as you have suggest but I don think of this as broken.

2021-06-18 01:35 UTC, hamishwillee commented on files/en-us/web/http/headers/index.html
> +  <div>
Removed. Note the  `p` was there previously because there are two paragraphs - but I have decided to merge these into one. Thanks.

2021-06-18 01:50 UTC, hamishwillee commented on files/en-us/web/http/headers/downlink/index.html
> +<p>The Downlink value is rounded to the nearest 25 kilobits per second to prevent fingerprinting; There are many other mechanisms an attacker might use to obtain similar information.</p>
@Elchi3 Thanks. Fixed for the three cases.

I copied DPR header which omits this rather than https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/HTTP_header_page_template (which is correct). I will fix up the DPR case when I do the device client hints updates next.

2021-06-18 01:56 UTC, hamishwillee commented
@Elchi3 Thanks for the detailed review - I seem to have injected more errors than usual :-(. 

I accepted all changes, added directives sections, reverted the specifications section. Note that I kept the specifications macro for the **new** header docs. Yes they show missing info now, but I'm hoping that the spec issue will be resolved soon and don't think it worth adding the manual table while we wait. Happy to add a manual table if you think this is a "requirement".

2021-06-18 09:04 UTC, Elchi3 commented
> Note that I kept the specifications macro for the **new** header docs. Yes they show missing info now, but I'm hoping that the spec issue will be resolved soon and don't think it worth adding the manual table while we wait. Happy to add a manual table if you think this is a "requirement".

This was the correct call! These headers use https://wicg.github.io/netinfo/ which does in fact work as soon as the latest BCD is on MDN production in a few hours. What doesn't work right now is HTTP features that reference IETF specs. You can follow https://github.com/w3c/browser-specs/issues/280 to be notified when it's available upstream.

2021-06-18 09:14 UTC, Elchi3 approved these changes
Thanks Hamish, fantastic work! 👍

2021-06-18 09:14 UTC, merged