Update example code in IDBObjectStore.delete() doc
mdn/content pull request #5972
Opened 2021-06-14 05:32 UTC by sideshowbarker

Fixes https://github.com/mdn/content/issues/5084

2021-06-14 21:43 UTC, wbamberg requested changes
This is a tricky one because the example is part of a bigger example which is at https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js (and which has already got out of sync with the snippet in this page, one of the perils of using [`EmbedGHLiveSample`](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedGHLiveSample.ejs)).

In the bigger example `db` is declared global: https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js#L6 , but even with that addressed, this example won't be runnable on its own - for example it also uses `note` which will be undefined in this snippet.

Perhaps if we changed the `note` bits to use `console.log` it might be better as a standalone example? Or maybe it would be better to lean into the GH example, by copying https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js#L218-L232 instead, and in the text around this example explained where `db` and `note` are supposed to be coming from, and how this snippet fits into the overall application at https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js ?

2021-06-14 21:43 UTC, wbamberg commented on files/en-us/web/api/idbobjectstore/delete/index.html
> +const db = DBOpenRequest.result;
Isn't `DBOpenRequest` going to be undefined here?

2021-06-14 21:56 UTC, sideshowbarker commented on files/en-us/web/api/idbobjectstore/delete/index.html
> +const db = DBOpenRequest.result;
```suggestion
const db;
```

2021-06-14 21:57 UTC, sideshowbarker commented on files/en-us/web/api/idbobjectstore/delete/index.html
> +const db = DBOpenRequest.result;
> Isn't `DBOpenRequest` going to be undefined here?

oops — yeah, fixed now

2021-06-14 21:58 UTC, sideshowbarker commented on files/en-us/web/api/idbobjectstore/delete/index.html
> +const db;
```suggestion
let db;
```

2021-06-14 22:09 UTC, sideshowbarker commented
> Perhaps if we changed the `note` bits to use `console.log` it might be better as a standalone example? Or maybe it would be better to lean into the GH example, by copying [mdn/to-do-notifications@`gh-pages`/scripts/todo.js#L218-L232](https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js#L218-L232) instead, and in the text around this example explained where `db` and `note` are supposed to be coming from, and how this snippet fits into the overall application at [mdn/to-do-notifications@`gh-pages`/scripts/todo.js](https://github.com/mdn/to-do-notifications/blob/gh-pages/scripts/todo.js) ?

Those all sound like great improvements to me, but the only thing I was attempting to do in this PR was just to resolve the specific issue the OP of #5084 pointed out. The other improvements will need more time than I’m going to personally be able to put in on this one.

So we could either merge this PR and raise a new issue for follow-up changes, or we can close this PR unmerged and add a comment to #5084 noting the additional changes needed, and block that issue on those changes getting made — and I can un-assign that issue and label it with “help wanted” to encourage someone else to pick it up to get it resolved.

2021-06-15 04:52 UTC, wbamberg commented
That's fair enough. Since I'm the one complaining I tried a slightly different approach in https://github.com/mdn/content/pull/6013, that just uses the code from the example app directly and tries to explain its context a bit.

If you like it, please merge it, or if you like this more minimal change better we could just merge this PR as it is.

2021-06-15 05:20 UTC, sideshowbarker commented
> I tried a slightly different approach in #6013, that just uses the code from the example app directly and tries to explain its context a bit.

Wow yeah that’s how it should be

> If you like it,

I like it :) Merged — much thanks

2021-06-15 05:21 UTC, sideshowbarker commented
Closing as superseded by https://github.com/mdn/content/pull/6013

2021-06-15 05:21 UTC, closed without merging