update return types of getUTCMonth
mdn/content pull request #6031
Opened 2021-06-15 17:02 UTC by mxdvl

> What was wrong/why is this fix needed? (quick summary only)

add NaN for non-number dates

> MDN URL of the main page changed

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMonth

> Issue number (if there is an associated issue)

#6030

> Anything else that could help us review it

This is as per the spec linked at the bottom of the page

2021-06-15 19:23 UTC, sideshowbarker requested changes
“if the date is NaN” does not seem like the right wording here.

What I mean is, the Date object this method is called from can’t itself be NaN — because it’s an object.

So the thing that can be NaN is an internal property/slot of the Date object. So I guess wording like “the time value of the object is NaN” might be better.

But it seems like what it comes down to is, this can actually only be NaN if the date is invalid — if the date were constructed with from an in valid value, by e.g., calling `new Date('foo bar baz')` or some such. And in that case, all the `get*` methods are going to return NaN.

So maybe, “NaN if the Date object it’s called from doesn’t represent a valid date”, or something like that?

2021-06-16 08:45 UTC, mxdvl commented
Thanks @sideshowbarker, that’s a very valid point.

I’ve updated the language now, and actually simplified by saying the return type is `number`, which includes `NaN`. Should number be a clickable link to the [global `Number` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)?

2021-06-16 11:20 UTC, sideshowbarker requested changes

2021-06-16 11:20 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/getutcmonth/index.html
> +<p>A <code>number</code>. If the date is valid, an integer number, between 0 and 11,
```suggestion
<p>A <code>number</code>. If the <code>Date</code> object represents a valid date, an integer number, between 0 and 11,
```

2021-06-16 11:20 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/getutcmonth/index.html
> +</p>
```suggestion
  if the <code>Date</code> object doesn’t represent a valid date.</p>
```

2021-06-16 11:22 UTC, sideshowbarker commented
> Should number be a clickable link to the [global `Number` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)?

I think that wouldn’t be correct — because it returns a number primitive, not a Number object.

So I think it’s fine to leave it unlinked.

> I’m happy to update the other `get*` methods accordingly.

Yes, once we get this one wrapped up, that would be great

2021-06-17 02:15 UTC, sideshowbarker approved these changes

2021-06-17 02:25 UTC, merged

2021-06-17 02:25 UTC, sideshowbarker commented
Max, nice work — thanks much, and congrats on landing your first docs change here — welcome aboard 🎉