Adds HIDInputReportEvent
mdn/content pull request #6103
Opened 2021-06-18 09:26 UTC by rachelandrew

Adds HIDInputReportEvent.

Reviewer @jpmedley

2021-06-18 18:22 UTC, jpmedley requested changes

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/data/index.html
> +<p class="summary">The <strong><code>data</code></strong> read-only property of the {{domxref("HIDInputReportEvent")}} interface contains the data sent by device as the input report.</p>
```suggestion
<p class="summary">The <strong><code>data</code></strong> read-only property of the {{domxref("HIDInputReportEvent")}} interface contains the data sent by the device as the input report.</p>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +<pre class="brush: js">new HIDInputReport(type, HIDInputReportEventInit)</pre>
```suggestion
<pre class="brush: js">new HIDInputReport(type);
new HIDInputReport(type, HIDInputReportEventInit)</pre>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
```suggestion
	<dt><code>HIDInputReportEventInit</code>{{optional_inline}}</dt>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
I can't find this structure in our IDL. The spec might be out of date.

@tomayac Do you know anything about this?

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +      <dd>The a {{jsxref("DataView")}} object containing the input report.</dd>
```suggestion
      <dd>A {{jsxref("DataView")}} object containing the input report.</dd>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +      <dd>An 8-bit reportId. If the HID device does not use report IDs, will be <code>0</code>.</dd>
```suggestion
      <dd>An 8-bit report ID. If the HID device does not use report IDs, this will be <code>0</code>.</dd>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
Also, I assume this has a constructor that it inherits from Event. But it seems like, if it has its own init structure, there would be a constructor shown on the IDL.

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/index.html
> +  <dd>An 8-bit reportId. If the HID device does not use report IDs, will be <code>0</code>.</dd>
```suggestion
  <dd>An 8-bit report ID. If the HID device does not use report IDs, this will be <code>0</code>.</dd>
```

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/index.html
> +<p>The following example demonstrates listening for an inputreport that will allow the application to detect which button is pressed on a Joy-Con Right device. You can see more examples, and live dem
input report or `inputReport`?

2021-06-18 18:22 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/reportid/index.html
> +<p>An 8-bit reportId. If the HID device does not use report IDs, will be <code>0</code>.</p>
```suggestion
<p>An 8-bit report ID. If the HID device does not use report IDs, this will be <code>0</code>.</p>
```

2021-06-18 18:49 UTC, rachelandrew commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
it's in that spec PR of yesterday too, so it's in the spec which is why I added it. https://github.com/WICG/webhid/pull/68/files

2021-06-18 19:34 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
Makes sense. Make sure it's `false` in the BCD. @tomayac Any idea when this will land?

2021-06-21 07:13 UTC, tomayac commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
Relaying the question to @nondebug, the implementor.

2021-06-28 15:57 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
@nondebug, any answer on this?

2021-06-28 17:19 UTC, nondebug commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
I've filed https://crbug.com/1224597 to update the HIDInputReportEvent implementation to match the spec and add HIDInputReportEventInit. I don't know when the spec PR will land, it's in review so hopefully soon.

2021-06-28 18:26 UTC, jpmedley commented on files/en-us/web/api/hidinputreportevent/hidinputreportevent/index.html
> +	<dt><code>HIDInputReportEventInit</code></dt>
I've stared the ticket and added a note as a reminder to come back here and finish this.

2021-08-20 16:02 UTC, teoli2003 commented
@rachelandrew  It looks to me that at least part of this landed in another PR you did? Should we close this one?

2021-08-20 19:37 UTC, jpmedley commented
I want to at least took at the differences (I ask sheepishly). I forgot we had this sitting here, then did a second PR. Since Rachel did all the other HID docs, I have to consider the possibility that her docs contain things that I missed.

2021-08-20 20:07 UTC, teoli2003 commented
No worry, the interface name in the title rang a bell when I parsed the list of open PRs. Hence my question.

2021-09-13 11:33 UTC, Elchi3 commented
Should we land this now (so it gets converted to markdown) and improve things later?

2021-09-13 17:54 UTC, jpmedley commented
@rachelandrew Chrome still does not support the constructor for this. Now that we have a process for orphans, can you please remove the constructor page, and make sure the page structures are up to date. Then I'll approve the PR.

2021-09-20 08:49 UTC, rachelandrew commented
@jpmedley we don't want to merge this as you also documented it and yours was merged. See: https://github.com/mdn/content/pull/6103#issuecomment-902913772

2021-09-21 02:07 UTC, jpmedley commented
Correct. I forgot what the plan had been.

2021-09-29 10:27 UTC, rachelandrew commented
Closing as two of us did the same work and I've now added my examples to the other version.

2021-09-29 10:27 UTC, closed without merging