Improve no spec messages on CompositionEvent.*
mdn/content pull request #6112
Opened 2021-06-18 15:07 UTC by teoli2003

This is (the first) part of #6108.

We are dealing with features that are no more on the standard track (deprecated), with bcd tables. The idea is to remove the `{{Specifications}}`, that implies missing data in this case, without putting back an outdated table like before

`CompositionEvent.locale`: Removed the macro, indicated that this is not on a standard track, linked to a github issue on UIEvents showing how much of a mess it is.
`CompositionEvent.initCompositionEvent`: Removed the macro, made a somewhat generic info that init* methods are superseded by constructors.

2021-06-18 21:59 UTC, sideshowbarker requested changes

2021-06-18 21:59 UTC, sideshowbarker commented on files/en-us/web/api/compositionevent/initcompositionevent/index.html
> +<p>This method is not more on a standardization track. It is kept for compatibility purpose. Use the constructor {{domxref("CompositionEvent.CompositionEvent", "CompositionEvent()")}}.</p>
```suggestion
<p>This method is no longer on a standardization track. It is kept for compatibility purposes. Use the constructor {{domxref("CompositionEvent.CompositionEvent", "CompositionEvent()")}}.</p>
```

2021-06-18 21:59 UTC, sideshowbarker commented on files/en-us/web/api/compositionevent/locale/index.html
> +<p>This property was in early versions of different specifications. It is nowadays only kept for compatibility purpose and the way
```suggestion
<p>This property was in early versions of different specifications. It is now only kept for compatibility purposes, and the way
```

2021-06-18 21:59 UTC, sideshowbarker commented on files/en-us/web/api/compositionevent/initcompositionevent/index.html
> +<p class="notecard note">Nowadays, the correct way of creating a {{domxref("CompositionEvent")}} is to use
```suggestion
<p class="notecard note">The correct way of creating a {{domxref("CompositionEvent")}} is to use
```

2021-06-19 03:03 UTC, teoli2003 commented on files/en-us/web/api/compositionevent/locale/index.html
> +<p>This property was in early versions of different specifications. It is nowadays only kept for compatibility purpose and the way
Grammar fixes

2021-06-19 03:03 UTC, teoli2003 commented on files/en-us/web/api/compositionevent/initcompositionevent/index.html
> +<p class="notecard note">Nowadays, the correct way of creating a {{domxref("CompositionEvent")}} is to use
Grammar fixes

2021-06-19 03:07 UTC, teoli2003 commented on files/en-us/web/api/compositionevent/initcompositionevent/index.html
> +<p>This method is not more on a standardization track. It is kept for compatibility purpose. Use the constructor {{domxref("CompositionEvent.CompositionEvent", "CompositionEvent()")}}.</p>
Accepted commit suggestion

2021-06-19 03:49 UTC, sideshowbarker approved these changes

2021-06-19 03:49 UTC, merged