Update no-spec msg for Gamepad.displayId
mdn/content pull request #6181
Opened 2021-06-21 09:22 UTC by teoli2003

This is part of #6108.

We are dealing with features that are no more on the standard track (deprecated), with bcd tables. The idea is to remove the `{{Specifications}}`, that implies some data is missing on mdn/browser-spec-data, without putting back an outdated table like before.

Here I deal with one WebVR property `Gamepad.displayId` that is not the most typical one as gamepads are excluded of the fundamental WebXR Display API specification, and:
 - I added a note at the top;
 - I replaced `{{Specification}}` with a more adequate text.

**There are a lot more pages (~70 pages) about WebVR on MDN and I would like to do something similar (but not a cut & paste: minor adaptations each time). Before proceeding with these pages, I would like a careful review of one adaptation (here!), so that I don't redo the work several times.**

@dontcallmedom , I think you are quite active on immersive-web, so I'm interested in your feedback (but not only yours).

2021-06-21 09:53 UTC, dontcallmedom approved these changes
This looks like a good approach to me!

paging @dominiccooney in case he wants to chime in

2021-06-21 11:33 UTC, sideshowbarker requested changes

2021-06-21 11:33 UTC, sideshowbarker commented on files/en-us/web/api/gamepad/displayid/index.html
> +  <p>There is no direct replacement for this property. The {{domxref("Gamepad")}} object associated to an {{domxref("XRInputSource")}} can be obtained using the {{domxref("XRInputSource.gamepad")}} p
```suggestion
  <p>There is no direct replacement for this property. The {{domxref("Gamepad")}} object associated with an {{domxref("XRInputSource")}} can be obtained using the {{domxref("XRInputSource.gamepad")}} property.</p>
```

2021-06-21 11:33 UTC, sideshowbarker commented on files/en-us/web/api/gamepad/displayid/index.html
> +<p>This property was part of the old <a href="https://immersive-web.github.io/webvr/spec/1.1/#gamepad-getvrdisplays-attribute">WebVR API</a> that has been superseded by the <a href="https://immersive
```suggestion
<p>This property was part of the old <a href="https://immersive-web.github.io/webvr/spec/1.1/#gamepad-getvrdisplays-attribute">WebVR API</a> that has been superseded by the <a href="https://immersive-web.github.io/webxr-gamepads-module/">WebXR Gamepads Module</a>. It is no longer on track to becoming a standard.</p>
```

2021-06-21 11:33 UTC, sideshowbarker commented on files/en-us/web/api/gamepad/displayid/index.html
> +<p>As long as all browsers are not implementing the new <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals">WebXR APIs</a>, it is recommended to rely on framework
```suggestion
<p>Until all browsers have implemented the new <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals">WebXR APIs</a>, it is recommended to rely on frameworks, like <a href="https://aframe.io/">A-Frame</a>, <a href="https://www.babylonjs.com/">Babylon.js</a>, or <a href="https://threejs.org/">Three.js</a>, or a <a href="https://github.com/immersive-web/webxr-polyfill">polyfill</a>, to develop WebXR applications that will work across all browsers <a href="https://developer.oculus.com/documentation/oculus-browser/browser-vr-xr/">[1]</a>.</p>
```

2021-06-21 11:36 UTC, sideshowbarker approved these changes

2021-06-21 11:37 UTC, sideshowbarker approved these changes

2021-06-21 11:38 UTC, sideshowbarker commented
Let’s wait to hear from @dominiccooney before merging

2021-06-30 08:49 UTC, Elchi3 approved these changes
Let's merge this. Feel free to review still afterwards and let us know if something got wrong!

2021-06-30 08:49 UTC, merged

2021-06-30 08:51 UTC, teoli2003 commented
Thanks. We can indeed change this later: I'll do the same for the other 60+ webvr pages in another PR, time to review again there.