HTML Element page template - update for browser-compat
mdn/content pull request #6217
Opened 2021-06-22 06:32 UTC by hamishwillee

This updates the [HTML_element_page_template](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/HTML_element_page_template template) for improved front-matter information (in particular browser compat) and generally for best-practice.

2021-06-22 06:35 UTC, teoli2003 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +	<li><code>\{{draft()}}</code> — this generates a <strong>Draft</strong> banner that indicates that the page is not yet complete, and should only be removed when the first draft of the page is comple
Do we want to continue recommanding the {{Draft}} macro? I think that with the github contribution process, it is no more needed: draft pages would not land (yet).

A kind of remnant of the wiki era.

2021-06-22 06:49 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +	<li><code>\{{draft()}}</code> — this generates a <strong>Draft</strong> banner that indicates that the page is not yet complete, and should only be removed when the first draft of the page is comple
That I do not know. It is a very good question. If it comes to a vote, then I say "yes", nothing should be submitted if it isn't already past basic draft.

2021-06-22 06:49 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +	<li><code>\{{draft()}}</code> — this generates a <strong>Draft</strong> banner that indicates that the page is not yet complete, and should only be removed when the first draft of the page is comple
@teoli2003 Also consider https://github.com/mdn/yari/discussions/4071

2021-06-23 12:50 UTC, Elchi3 requested changes
Thanks Hamish, some comments.

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +title: '&lt;NameOfTheElement&gt;: The NameOfTheElement Embed element'
```suggestion
title: '&lt;NameOfTheElement&gt;: The NameOfTheElement element'
```

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +<p>The frontmatter at the top of the page is used to define "page metadata". The values should be updated appropriately for the particular element.</p>
Not sure why it would need to be "page metadata".
```suggestion
<p>The frontmatter at the top of the page is used to define page metadata. The values should be updated appropriately for the particular element.</p>
```

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +<dt><strong>Title</strong></dt>
```suggestion
<dt><strong>title</strong></dt>
```

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +      <li>Any other tags that represent terms people might search for related to the technology. For example the <code><a href="/en-US/docs/Web/HTML/Element/video">&lt;video&gt;</a></code> element in
```suggestion
      <li>Any other tags that represent terms people might search for related to the technology. For example, the <code><a href="/en-US/docs/Web/HTML/Element/video">&lt;video&gt;</a></code> element includes the tags: <strong>HTML Video</strong>, <strong>Multimedia</strong>, <strong>Media Player</strong>, <strong>Movie Playback</strong>, etc.</li>
```

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +	<li><code>\{{draft()}}</code> — this generates a <strong>Draft</strong> banner that indicates that the page is not yet complete, and should only be removed when the first draft of the page is comple
I agree to remove this.

2021-06-23 12:50 UTC, Elchi3 commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +<p>The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone <a href="https://github.com/mdn/interactive-
Now we're not a wiki anymore and given we removed this text for the compat table, I think we could remove it for the interactive examples, too.

2021-06-25 03:48 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/html_element_page_template/index.html
> +	<li><code>\{{draft()}}</code> — this generates a <strong>Draft</strong> banner that indicates that the page is not yet complete, and should only be removed when the first draft of the page is comple
I have deleted this from this doc, and all the other templates.

2021-06-25 04:00 UTC, hamishwillee commented
Thanks! I've accepted suggestions, removed draft macro from all the templates, fixed up copy paste error in front matter title for all templates. Removed the interactive example text.
Should be good.

2021-06-25 13:16 UTC, Elchi3 approved these changes
Great, thank you! 👍

2021-06-25 13:16 UTC, merged