Fixed #6226
mdn/content pull request #6269
Opened 2021-06-23 14:52 UTC by FarazzShaikh

> What was wrong/why is this fix needed? (quick summary only)

The example for why variables are useful [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables) was overly complicated.

> Issue number (if there is an associated issue)

Fixes #6226 

> Anything else that could help us review it

2021-06-23 20:57 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/variables/index.html
> +<div id="example_without_variabele">
```suggestion
<div id="example_without_variable">
```

2021-06-23 20:57 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/variables/index.html
> +    <p>{{ EmbedLiveSample('example_without_variabele', '100%', 50, "", "", "hide-codepen-jsfiddle") }}</p>
```suggestion
    <p>{{ EmbedLiveSample('example_without_variable', '100%', 50, "", "", "hide-codepen-jsfiddle") }}</p>
```

2021-06-23 20:59 UTC, wbamberg requested changes
Thanks for this PR, it's a much, much better example of why we need variables!

I fixed a typo and had a suggestion for rewording and simplifying the text.

2021-06-23 20:59 UTC, wbamberg commented on files/en-us/learn/javascript/first_steps/variables/index.html
> +<p>You may not fully understand the syntax we are using (yet!), but you should be able to get the idea — if we didn't have variables available, we'd have to ask the reader for their name multiple tim
```suggestion
<p>You may not fully understand the syntax we are using (yet!), but you should be able to get the idea. If we didn't have variables available, we'd have to ask the reader for their name every time we needed to use it!</p>
```

2021-06-24 03:40 UTC, FarazzShaikh commented
Thank you! Sounds good, I have made the changes

2021-06-24 03:45 UTC, wbamberg approved these changes
👍 thanks for your contribution!

2021-06-24 03:45 UTC, merged