Warn about XHR upload listener requirements
mdn/content pull request #627
Opened 2020-12-24 13:57 UTC by mildsunrise

The XHR spec seems to indicate that upload events should be registered between the `open()` call and the `send()` call. It also mentions that registering upload events causes the request to have a preflight. I think these two things are important to mention.

But browsers are buggy and on Chromium, events won't fire unless I register them *before* `open()`. I tried to find an open issue but was unable to. [This one](https://bugs.chromium.org/p/chromium/issues/detail?id=700891) is close but not it.

Mention this too, to hopefully save hours of frustration to someone else.

2020-12-28 09:03 UTC, sideshowbarker requested changes
This looks really great (modulo the nits)

2020-12-28 09:03 UTC, sideshowbarker commented on files/en-us/web/api/xmlhttprequest/upload/index.html
> +<div class="note"><strong>Note:</strong> Attaching event listeners to this object prevents the request from being a "simple request" and will cause a preflight request to be issued if cross-origin; s
```suggestion
<div class="note notecard"><strong>Note:</strong> Attaching event listeners to this object prevents the request from being a "simple request" and will cause a preflight request to be issued if cross-origin; see <a href="/en-US/docs/Web/HTTP/CORS">CORS</a>. Because of this, event listeners need to be registered before calling {{domxref("XMLHttpRequest.send", "send()")}} or upload events won't be dispatched.</div>
```
I think we’re supposed to added `notecard` to the `class` value for all notes and warnings. But I’m not certain it’s actually necessary — and if so, why — so I hope @peterbe can confirm (though we don’t need to block this PR on getting that confirmation).

2020-12-28 09:03 UTC, sideshowbarker commented on files/en-us/web/api/xmlhttprequest/upload/index.html
> +<div class="note"><strong>Note:</strong> The spec also seems to indicate that event listeners should be attached after {{domxref("XMLHttpRequest.open", "open()")}}. However browsers are buggy on this
```suggestion
<div class="note notecard"><strong>Note:</strong> The spec also seems to indicate that event listeners should be attached after {{domxref("XMLHttpRequest.open", "open()")}}. However, browsers are buggy on this matter, and often need the listeners to be registered <em>before</em> {{domxref("XMLHttpRequest.open", "open()")}} to work.</div>
```

2021-02-24 04:05 UTC, sideshowbarker approved these changes

2021-02-24 04:07 UTC, merged

2021-02-24 04:08 UTC, sideshowbarker commented
Alba, thanks much, and sorry for the delay in getting back to this. Congrats on landing your first docs change here — welcome aboard 🎉

2021-02-24 20:22 UTC, mildsunrise commented
no problem! thanks :)