adds the Element.attachInternals() method
mdn/content pull request #6337
Opened 2021-06-25 14:07 UTC by rachelandrew

To go alongside #6335 this is the `attachInternals()` method for Element.

Reviewer: @jpmedley

2021-06-28 17:53 UTC, jpmedley requested changes

2021-06-28 17:53 UTC, jpmedley commented on files/en-us/web/api/element/attachinternals/index.html
> +<p>The <strong><code>Element.attachInternals()</code></strong> method returns a {{domxref("ElementInternals")}} object. The primary use case for doing so is in order that a <a href="/en-US/docs/Web/W
>The `attachInternals()` method of the {{domref('Element')}} interface...

Did they change how these are done?

2021-06-28 17:53 UTC, jpmedley commented on files/en-us/web/api/element/attachinternals/index.html
> +<p>The <strong><code>Element.attachInternals()</code></strong> method returns a {{domxref("ElementInternals")}} object. The primary use case for doing so is in order that a <a href="/en-US/docs/Web/W
```suggestion
<p>The <strong><code>Element.attachInternals()</code></strong> method returns a {{domxref("ElementInternals")}} object. This method allows a <a href="/en-US/docs/Web/Web_Components/Using_custom_elements">custom element</a> to participate in HTML forms. The <code>ElementInternals</code> interface provides utilities for working with these elements in the same way you would work with any standard HTML form element, and also exposes the <a href="https://wicg.github.io/aom/explainer.html">Accessibility Object Model</a> to the element.</p>
```

2021-06-28 17:53 UTC, jpmedley commented on files/en-us/web/api/element/attachinternals/index.html
> +<p>The <strong><code>Element.attachInternals()</code></strong> method returns a {{domxref("ElementInternals")}} object. The primary use case for doing so is in order that a <a href="/en-US/docs/Web/W
Is `attachInternals()` usable now? We shouldn't be describing or linking to experimental features that [aren't yet implemented](https://www.chromestatus.com/feature/5534549008187392).

2021-06-28 17:53 UTC, jpmedley commented on files/en-us/web/api/element/attachinternals/index.html
> +  <dd>Thrown if the "internals" feature was disabled as part of the element definition.</dd>
Is there a link for the "internals" feature?

2021-07-01 10:47 UTC, rachelandrew commented on files/en-us/web/api/element/attachinternals/index.html
> +<p>The <strong><code>Element.attachInternals()</code></strong> method returns a {{domxref("ElementInternals")}} object. The primary use case for doing so is in order that a <a href="/en-US/docs/Web/W
yes it's supported, it's how you use ElementInternals and how I tested ElementInternals :)

2021-07-01 10:52 UTC, rachelandrew commented on files/en-us/web/api/element/attachinternals/index.html
> +  <dd>Thrown if the "internals" feature was disabled as part of the element definition.</dd>
it's in the spec https://html.spec.whatwg.org/multipage/custom-elements.html#concept-custom-element-definition-disable-internals I can't see it in the MDN custom elements docs, which may well be somewhat out of date. I don't know when all of this stuff was written.

2021-07-01 16:35 UTC, jpmedley commented on files/en-us/web/api/element/attachinternals/index.html
> +  <dd>Thrown if the "internals" feature was disabled as part of the element definition.</dd>
I hate to leave a conceptual link, but this looks like a rabbit hole. Can you open an issue about this in the content repo and include a reference to this page so that someone knows come back and add a link.

2021-07-06 07:29 UTC, rachelandrew commented on files/en-us/web/api/element/attachinternals/index.html
> +  <dd>Thrown if the "internals" feature was disabled as part of the element definition.</dd>
https://github.com/mdn/content/issues/6617

2021-07-07 15:18 UTC, jpmedley approved these changes

2021-07-08 07:50 UTC, merged