Markup tweaks and minor copy-edits
mdn/content pull request #654
Opened 2020-12-26 19:21 UTC by Zearin

2020-12-27 19:55 UTC, ericwbailey requested changes
Some nice feedback here. I have a few nitpicks about use of `var` and `samp`, but overall I like what you're proposing.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code><strong>aria-live</strong></code>: The <code>aria-live=<var>POLITENESS_SETTING</var></code> is used to set the priority with which screen reader should treat updates to live regions - the
Let's not add the `var` element. While it is technically accurate semantically, it suggests that you can place markup in the attribute's value, which isn't allowed.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +  <p class="comment"><code><strong>aria-controls</strong></code>: The <code>aria-controls=<var>[IDLIST]</var></code> is used to associate a control with the regions that it controls. Regions are iden
Same comment about the `var` element for `aria-controls`.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +	 <div class="warning"><strong>TODO:</strong> Determine if the <code>aria-controls</code> aspect of <code>live</code> regions is implemented in current assistive technologies (and which ones). Needs
I don't believe we place todos in our live documents. If you'd like to investigate that, I think filing an issue would be a good way to let others know you're investigating it.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +    (TODO: link to ARIA form tutorial with aria info)</td>
Same as previous comment about todos.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +       (TODO: add more info here).</td>
Same as the first comment about todos.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The Paciello Group has some <a href="https://www.paciellogroup.com/blog/2014/03/screen-reader-support-aria-live-regions/">information about the state of the support of Live Regions</a> (2014). Pau
```suggestion
<p>The Paciello Group has some <a href="https://www.paciellogroup.com/blog/2014/03/screen-reader-support-aria-live-regions/">information about the state of the support of Live Regions</a> (2014). Paul J. Adam has researched <a href="http://pauljadam.com/demos/aria-atomic-relevant.html">the support of Aria-Atomic and Aria-Relevant</a> in particular.</p>
```

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code><strong>aria-describedby</strong></code>: The <code>aria-describedby=<var>[IDLIST]</var></code> is used to associate a region with its descriptions, similar to <code>aria-controls</code>,
Same as other comments about `var`.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
```suggestion
<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content will be announced. For instance, when the clock changes from <code>"17:33"</code> to <code>"17:34"</code>, assistive technologies will only announce "<samp>4</samp>", which won't be very useful to users.</p>
```

Moving the `samp` element to wrap only what AT might announce.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
```suggestion
<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content will be announced. For instance, when the clock changes from "<code>17:33</code>" to "<code>17:34</code>", assistive technologies will only announce <samp>"4"</samp>, which won't be very useful to users.</p>
```

Moving the `code` element to wrap only what AT might announce.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p><code>aria-atomic="true"</code> ensures that each time the live region is updated, the entirety of the content is announced in full (e.g. <samp>"Time: 17:34"</samp>).</p>
```suggestion
<p><code>aria-atomic="true"</code> ensures that each time the live region is updated, the entirety of the content is announced in full (e.g. "<samp>Time: 17:34</samp>").</p>
```

Moving the `samp` element to wrap only what AT might announce.

2020-12-27 19:55 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code>aria-live="polite"</code> indicates that the screen reader should wait until the user is idle before presenting updates to the user. This is the most commonly used value, as interrupting t
```suggestion
 <li><code>aria-live="polite"</code> indicates that the screen reader should wait until the user is idle before presenting updates to the user. This is the most commonly used value, as interrupting the user with <code>assertive</code> might interrupt their flow.</li>
```

Quotes are extraneous here.

2021-01-01 23:09 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +	 <div class="warning"><strong>TODO:</strong> Determine if the <code>aria-controls</code> aspect of <code>live</code> regions is implemented in current assistive technologies (and which ones). Needs
I didn’t create a TODO, really.  I just prefixed the already-existing text to label it for what it is.  

(It confused me the first time I was reading through the page and didn’t realize that this block of text was not part of the main content, but rather a public commentary on something the main content is missing.)

So, I figured…at least make it obvious that this text is different.

2021-01-01 23:09 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +    (TODO: link to ARIA form tutorial with aria info)</td>
Again, I didn’t create the note.  This time I just changed “TBD” to “TODO” for the sake of consistency.

2021-01-01 23:09 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +       (TODO: add more info here).</td>
(ditto)

2021-01-01 23:13 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
I left the quotes within the `code` element to indicate that it is a string.  While the similar change to `samp` makes sense, I think it’s a good idea to leave quotes around strings for code snippets.  (I can remember consistently confused by this sort of thing in various documentation when I was learning to program many years ago.)

2021-01-01 23:14 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code>aria-live="polite"</code> indicates that the screen reader should wait until the user is idle before presenting updates to the user. This is the most commonly used value, as interrupting t
Same reasoning as an earlier comment. (I think keeping strings quoted helps newcomers understand the docs better.)

2021-01-01 23:19 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code><strong>aria-live</strong></code>: The <code>aria-live=<var>POLITENESS_SETTING</var></code> is used to set the priority with which screen reader should treat updates to live regions - the
I don’t see how it suggests that to the reader.  It simply displays that text with slightly different formatting as an indicator that the text is a “stand-in”.  In that respect, it’s no different than the `strong` element.

If MDN won’t make use of the poor, neglected `var` element (in this perfect use-case scenario)…who will?  😉

2021-01-01 23:32 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code><strong>aria-live</strong></code>: The <code>aria-live=<var>POLITENESS_SETTING</var></code> is used to set the priority with which screen reader should treat updates to live regions - the
There is also existing precedent for `var` in other MDN docs.  [`Map.prototype.get()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get), for example.

2021-01-05 20:56 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> + <li><code><strong>aria-live</strong></code>: The <code>aria-live=<var>POLITENESS_SETTING</var></code> is used to set the priority with which screen reader should treat updates to live regions - the
I still don't really agree with his, but if there's precedent, hey, who am I to stand in the way of progress?

2021-01-05 20:56 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +	 <div class="warning"><strong>TODO:</strong> Determine if the <code>aria-controls</code> aspect of <code>live</code> regions is implemented in current assistive technologies (and which ones). Needs
Gotcha.

2021-01-05 20:57 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
Interesting. I was thinking the opposite, in that strings coming along for the ride in a copy/paste would break things.

2021-01-05 23:47 UTC, Zearin commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
Oh?  Can you elaborate?  I don’t follow…

2021-01-07 15:29 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p>The first time the function executes, the entirety of the string that is added will be announced. On subsequent calls, only the parts of the content that changed compared to the previous content w
If I am new to code, I may not understand the difference between the string itself and what signifies it. Same principle as people who copy the `$` portion of a terminal command and then are confused when it doesn't work.

2021-02-10 21:27 UTC, Ryuno-Ki commented on files/en-us/web/accessibility/aria/aria_live_regions/index.html
> +<p><code>aria-atomic="true"</code> ensures that each time the live region is updated, the entirety of the content is announced in full (e.g. "<samp>Time: 17:34</samp>").</p>
Thinking ahead about the markdown-based editing: `<samp>` could be replaced with `<code>`, too here?

2021-02-24 03:56 UTC, sideshowbarker commented
@Zearin Please let us know if you plan on getting back to this one

2021-05-26 06:10 UTC, sideshowbarker commented
Closing for lack of response even after having given this a bump in February

2021-05-26 06:10 UTC, closed without merging