"on the client-side" -> "by the user" for checkbox `value` attribute
mdn/content pull request #658
Opened 2020-12-27 01:44 UTC by sollyucko

AFAIK, the value of the `value` attribute can be seen by the client (i.e. by JS and CSS), but it isn't (normally) shown to the user.

2020-12-28 23:37 UTC, vkWeb requested changes
@sollyucko thanks for catching this ;) Yes this sounds wrong.

But see that line's intent is not to say that browsers don't have access to `value`, they do have access for sure. It's purpose is to convey that `value`'s value isn't displayed on the client-side.

So let us re word it.

2020-12-28 23:37 UTC, vkWeb commented on files/en-us/web/html/element/input/checkbox/index.html
> +<p>A {{domxref("DOMString")}} representing the value of the checkbox. This is never seen by the user, but on the server this is the <code>value</code> given to the data submitted with the checkbox's
```suggestion
<p>A {{domxref("DOMString")}} representing the value of the checkbox. This is not displayed on the client-side, but on the server this is the <code>value</code> given to the data submitted with the checkbox's <code>name</code>. Take the following example:</p>
```

2020-12-31 21:15 UTC, sollyucko commented
Sure, that sounds like a good way to word it.

2021-02-12 15:25 UTC, mirunacurtean approved these changes
That's fine. Well done, thank you.

2021-02-12 15:27 UTC, merged