Add .github/workflows/ping-other-repos.yml
mdn/content pull request #6591
Opened 2021-07-05 08:59 UTC by sideshowbarker

For every push to the repo, the `.github/workflows/ping-other-repos.yml` file added in this change creates a GitHub `repository_dispatch` event to send a ping to the https://github.com/w3c/mdn-spec-links/ repo (where it triggers the build of the contents of that repo).

Along with https://github.com/w3c/mdn-spec-links/, other repos can be added to this later — any repos that want to have some action triggered each time a push to the BCD repo occurs.

https://github.com/marketplace/actions/repository-dispatch has docs on the GitHub Action this uses, and docs for the underlying API it uses are at https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event

---

This is identical to the https://github.com/mdn/browser-compat-data/blob/main/.github/workflows/ping-other-repos.yml workflow that @ddbeck and I worked on together for BCD. Adding additional repos we may want to start pinging also later would just be a matter of copy/pasting the existing w3c/mdn-spec-links step, and just changing repo-name part.

2021-07-06 16:06 UTC, peterbe requested changes
This is smart and clever and it's fantastic to know this has been matured and tested in the BCD project. Let's get this landed but first let's tidy it up a bit. 

1. The name of the file is great and so is the `name:`
2. But it's weird that it says "repos" and then there's only 1. 
3. Can you add a code comment above or below `- name: Ping w3c/mdn-spec-links` that explains that this is just one of many and you can look at this one above/below more as an example. 
4. Can you write a code comment near the top of the file that explains A) why this exists in general, B) a mention of the BCD equivalent. 
5. Can we call the secret something that isn't tied to your name but rather mentions `W3C` and perhaps some underscores to be really verbose, like `W3C_SPEC_REPO_PINGER` :)
6. That `if: ${{ github.repository == 'mdn/content' }}` needs to move up so it applies to the whole workflow rather than just `name: Ping w3c/mdn-spec-links`

Once you've picked a good name for the secret, how do you intend to share that secret with me or @escattone ? Keybase or gpg file?

2021-07-06 22:59 UTC, sideshowbarker commented
>  3. Can you add a code comment above or below `- name: Ping w3c/mdn-spec-links` that explains that this is just one of many and you can look at this one above/below more as an example.

✅

>     4. Can you write a code comment near the top of the file that explains A) why this exists in general,

✅

> B) a mention of the BCD equivalent.

✅

>     5. Can we call the secret something that isn't tied to your name but rather mentions `W3C` and perhaps some underscores to be really verbose, like `W3C_SPEC_REPO_PINGER` :)

✅

>     6. That `if: ${{ github.repository == 'mdn/content' }}` needs to move up so it applies to the whole workflow rather than just `name: Ping w3c/mdn-spec-links`

✅

> Once you've picked a good name for the secret, how do you intend to share that secret with me or @escattone ? Keybase or gpg file?

The way @ddbeck and I did it was by Matrix direct message (which gets end-to-end encrypted). Shall we do it that way?

2021-07-07 00:50 UTC, peterbe approved these changes

2021-07-07 01:04 UTC, sideshowbarker commented
Is this causing a CI failure?

2021-07-07 01:06 UTC, sideshowbarker commented
d’oh — nevermind, I see it’s he system-file-changes thing

2021-07-07 01:22 UTC, merged