Adds the missing pages for the HID interface
mdn/content pull request #6625
Opened 2021-07-06 13:25 UTC by rachelandrew

Adds the missing pages. HID already had the main interface page.

Again referencing this PR: https://github.com/WICG/webhid/pull/68/files as the spec is quite sketchy on the details.

Reviewer: @jpmedley

2021-07-07 15:55 UTC, jpmedley requested changes

2021-07-07 15:55 UTC, jpmedley commented on files/en-us/web/api/hid/onconnect/index.html
> +<p class="summary">The <strong><code>onconnect</code></strong> EventHandler of the {{domxref("HID")}} interface is an {{event("Event_Handlers", "Event Handler")}} that processes the events fired when
```suggestion
<p class="summary">The <strong><code>onconnect</code></strong> {{event("Event_Handlers", "Event Handler")}} of the {{domxref("HID")}} interface processes the events fired when the user agent connects to the HID device.</p>
```

2021-07-07 15:55 UTC, jpmedley commented on files/en-us/web/api/hid/ondisconnect/index.html
> +<p class="summary">The <strong><code>ondisconnect</code></strong> EventHandler of the {{domxref("HID")}} interface is an {{event("Event_Handlers", "Event Handler")}} that processes the events when th
```suggestion
<p class="summary">The <strong><code>ondisconnect</code></strong> {{event("Event_Handlers", "Event Handler")}} of the {{domxref("HID")}} interface processes the events when the user agent disconnects from the HID device.</p>
```

2021-07-07 15:55 UTC, jpmedley commented on files/en-us/web/api/hid/requestdevice/index.html
> +  <p>The device filters are used to narrow the list of devices presented to the user. If no filters are present, all connected devices are shown. When one of more filters are included, a device is in
>one of more filters

Is this supposed to be 'one *or* more filters'?

2021-07-07 15:55 UTC, jpmedley commented on files/en-us/web/api/hid/requestdevice/index.html
> +<h3>Matching a device will all four filter rules</h3>
What?

2021-07-07 15:55 UTC, jpmedley commented on files/en-us/web/api/hid/requestdevice/index.html
> +  <p>This next example includes two filters, devices will be shown if they match either of these filters.</p>
```suggestion
  <p>This next example includes two filters. Devices will be shown if they match either of these filters.</p>
```

2021-07-08 07:45 UTC, rachelandrew commented on files/en-us/web/api/hid/requestdevice/index.html
> +  <p>The device filters are used to narrow the list of devices presented to the user. If no filters are present, all connected devices are shown. When one of more filters are included, a device is in
```suggestion
  <p>The device filters are used to narrow the list of devices presented to the user. If no filters are present, all connected devices are shown. When one or more filters are included, a device is included if any filter matches. To match a filter, all of the rules included in that filter must match.</p>
```

2021-07-08 07:45 UTC, rachelandrew commented on files/en-us/web/api/hid/requestdevice/index.html
> +<h3>Matching a device will all four filter rules</h3>
```suggestion
<h3>Matching a device with all four filter rules</h3>
```

2021-07-09 15:38 UTC, rachelandrew commented
@jpmedley I've resolved everything on this one.

2021-07-09 17:34 UTC, jpmedley approved these changes

2021-07-09 17:34 UTC, merged