Release note for Web Cache Api use for webextensions
mdn/content pull request #6682
Opened 2021-07-08 15:40 UTC by mirunacurtean

> What was wrong/why is this fix needed? (quick summary only)

Fixes https://github.com/mdn/content/issues/5378

2021-07-08 16:52 UTC, rpl requested changes

2021-07-08 16:52 UTC, rpl commented on files/en-us/mozilla/firefox/releases/90/index.html
> +  <li>Starting with this version, the <a href= "/en-US/docs/Web/API/Cache">Cache API</a> can be used in the extension page (for content script injection) and the worker globals. For more details see
Remove `(for content script injection)`, the Cache API available in a content script is the one from the attached webpage (and the changes from Bug 1575625 are unrelated to that, the patch landed did actually enable using it from extension pages, like the background page or a browserAction popup, moz-extension workers and to allow caching moz-extension urls, (this part did not work before that bug was fixed).

2021-07-08 19:11 UTC, mirunacurtean commented on files/en-us/mozilla/firefox/releases/90/index.html
> +  <li>Starting with this version, the <a href= "/en-US/docs/Web/API/Cache">Cache API</a> can be used in the extension page (for content script injection) and the worker globals. For more details see
@rpl Thanks for the clarifications. I remove what you requested and added further details that you provided on the scope of this fix. Hope it looks good now!

2021-07-09 12:47 UTC, rpl approved these changes
looks good, but as described below I think we may omit the additional details from the release notes and keep the description in this list item simple as it was in the previous version (just without the reference to the content script).

(I mainly described why the note on the content script was wrong for completeness of the review comment).

2021-07-09 12:47 UTC, rpl commented on files/en-us/mozilla/firefox/releases/90/index.html
> +  <li>Starting with this version, the <a href= "/en-US/docs/Web/API/Cache">Cache API</a> can be used in the extension pages (like background page, browserAction popups, moz-extension workers or allow
Nit, personally I think we may omit the details from the release notes and leave it as:
```
Starting with this version, the Cache API can be used in the extension pages and worker globals. For more details, see ... 
```

2021-07-09 15:12 UTC, Rumyra approved these changes

2021-07-09 15:12 UTC, Rumyra commented on files/en-us/mozilla/firefox/releases/90/index.html
> +  <li>Starting with this version, the <a href= "/en-US/docs/Web/API/Cache">Cache API</a> can be used in the extension pages (like background page, browserAction popups, moz-extension workers or allow
I'm going to merge this as I still have to do an edit of the release notes this afternoon - @rpl I'll modify for what you've said in that pr 👍

2021-07-09 15:12 UTC, merged