"?." instead of "Optional chaining" in ref title
mdn/content pull request #6683
Opened 2021-07-08 16:44 UTC by rgmuslin

Some people (like myself) are not familiar from the start with the general operator names, especially for the (relatively) new ones. Personally I have looked for ?. in the list of all operators on this page and could not find it quite for a while not knowing that its "right" name is "optional chaining". Therefore I hope that putting the operator itself as the title into the operator list will be more readable, especially for javascript learners.

> What was wrong/why is this fix needed? (quick summary only)

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-07-08 17:29 UTC, sideshowbarker requested changes

2021-07-08 17:29 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/index.html
> + <li>{{JSxRef("Operators/Optional_chaining", "?.", "", 1)}}</li>
```suggestion
 <li>{{JSxRef("Operators/Optional_chaining", "<code>?.</code> (Optional chaining)", "", 1)}}</li>
```

2021-07-08 17:51 UTC, sideshowbarker approved these changes

2021-07-08 17:52 UTC, merged

2021-07-08 17:52 UTC, sideshowbarker commented
Thanks much, and congrats on landing your first docs change here — welcome aboard 🎉

2021-07-13 18:37 UTC, rgmuslin commented
:)