add image-resolution
mdn/content pull request #676
Opened 2020-12-28 08:21 UTC by rachelandrew

Fixes: https://github.com/mdn/sprints/issues/3643

Add the CSS `image-resolution` property and linking it from relevant places as detailed in the issue. No BCD as this property is unimplemented, although I found a Chromium bug which I have linked from the page.

2020-12-28 20:51 UTC, ericwbailey approved these changes

2020-12-28 21:53 UTC, sideshowbarker requested changes

2020-12-28 21:53 UTC, sideshowbarker commented on files/en-us/web/api/window/devicepixelratio/index.html
> +<p><a href="https://mdn.mozillademos.org/files/15023/devicePixelRation_Diff..jpg"><img alt="This image describe the impact of different value on retina display." src="./devicepixelration_diff..jpg" s
It’s intentional that the filename has an extra dot before the extension? `devicePixelRation_Diff..jpg` rather than just `devicePixelRation_Diff.jpg`? (I realize that the jpg file it’s replacing already had the extra dot — I’m just wondering if preserving that extra dot is necessary/intentional.)

2020-12-28 21:53 UTC, sideshowbarker commented on files/en-us/web/css/image-resolution/index.html
> +<p>The <strong><code>image-resolution</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> property specifies the intrinsic resolution of all raster images used in or on the element. It affects cont
```suggestion
<p>The <strong><code>image-resolution</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> property specifies the intrinsic resolution of all raster images used in or on the element. It affects content images such as replaced elements and generated content, and decorative images such as <code>background-image</code> images.</p>
```

2020-12-28 21:53 UTC, sideshowbarker commented on files/en-us/web/css/image-resolution/index.html
> +<p>The image resolution is defined as the number of image pixels per unit length, e.g., pixels per inch. By default, CSS assumes a resolution of one image pixel per CSS px unit; however, the image-re
```suggestion
<p>The image resolution is defined as the number of image pixels per unit length, e.g., pixels per inch. By default, CSS assumes a resolution of one image pixel per CSS px unit; however, the <code>image-resolution</code> property allows a different resolution to be specified.</p>
```

2020-12-28 21:53 UTC, sideshowbarker commented on files/en-us/web/css/image-resolution/index.html
> + <dd>If the "snap" keyword is provided, the computed resolution is the specified resolution rounded to the nearest value that would map one image pixel to an integer number of device pixels. If the r
```suggestion
 <dd>If the <code>snap</code> keyword is provided, the computed resolution is the specified resolution rounded to the nearest value that would map one image pixel to an integer number of device pixels. If the resolution is taken from the image, then the used intrinsic resolution is the image’s native resolution similarly adjusted.</dd>
```

2020-12-28 21:53 UTC, sideshowbarker commented on files/en-us/web/css/image-resolution/index.html
> +<p>When printing the document use a higher resolution.</p>
```suggestion
<p>When printing the document, use a higher resolution.</p>
```

2020-12-29 05:27 UTC, rachelandrew commented on files/en-us/web/api/window/devicepixelratio/index.html
> +<p><a href="https://mdn.mozillademos.org/files/15023/devicePixelRation_Diff..jpg"><img alt="This image describe the impact of different value on retina display." src="./devicepixelration_diff..jpg" s
I just did the fixable flaws thing on this page as I was adding a link to it, the resulting  image was then still too large to be accepted by the linter so I then ran it through an optimization however I retained the original filename (though it is now a jpeg). It could be changed I think.

2020-12-31 23:25 UTC, sideshowbarker commented
Testing this locally led me to discover that Yari doesn’t yet handle `.jpg` resources correctly. But the fix turned out to be very easy, so I wrote a patch and opened https://github.com/mdn/yari/pull/2300/. I guess we should wait for that fix to get merged and deployed, and then once that’s live, we can merge this.

2021-01-01 08:45 UTC, sideshowbarker commented on files/en-us/web/api/window/devicepixelratio/index.html
> +<p><a href="https://mdn.mozillademos.org/files/15023/devicePixelRation_Diff..jpg"><img alt="This image describe the impact of different value on retina display." src="./devicepixelration_diff..jpg" s
>> It’s intentional that the filename has an extra dot before the extension?
>
> It could be changed I think.

OK, I renamed it

2021-01-01 08:46 UTC, sideshowbarker approved these changes

2021-01-01 08:48 UTC, rachelandrew commented
@sideshowbarker ah I'd assumed that was a Windows-related issue, I occasionally run into path problems.

2021-01-01 08:50 UTC, sideshowbarker commented
> @sideshowbarker ah I'd assumed that was a Windows-related issue, I occasionally run into path problems.

Yeah it baffled me. Took me a while to hunt down the cause. Glad it was an easy fix.

2021-01-15 10:00 UTC, merged