Update index.html
mdn/content pull request #683
Opened 2020-12-28 13:42 UTC by beaufortfrancois

This PR updates Web NFC API to reflect latest spec changes.
See https://github.com/w3c/web-nfc/blob/gh-pages/EXPLAINER.md#changes-done-after-origin-trial-ot and https://web.dev/nfc/

Disclaimer: I'm an editor of the spec.

2020-12-28 15:01 UTC, Rumyra commented
The changes look perfectly fine, I'm only pausing on reviewing as this change would mean moving the existing page (which I will look into 👍 )

2020-12-28 19:07 UTC, sideshowbarker requested changes

2020-12-28 19:07 UTC, sideshowbarker commented on files/en-us/web/api/ndefreader/index.html
> + <dd>An event handler for <code>readingerror</code> event which is called to notify that an error occurred during reading.</dd>
```suggestion
 <dd>An event handler for the <code>readingerror</code> event, which is fired when an error occurs during reading.</dd>
```

2020-12-28 20:11 UTC, sideshowbarker approved these changes

2020-12-28 20:12 UTC, sideshowbarker commented
Converted to draft status so that we don’t accidentally merge this before resolution of https://github.com/mdn/content/pull/683#issuecomment-751740187.

2020-12-29 14:42 UTC, Rumyra commented
The linked page is already correctly named: https://developer.mozilla.org/en-US/docs/Web/API/NDEFReader/onreadingerror

One assumes then that `{{domxref(NDEFReader.onreadingerror)}}` will work - I'm happy to approve @sideshowbarker

2020-12-29 14:42 UTC, Rumyra approved these changes

2020-12-29 14:55 UTC, merged

2020-12-29 19:30 UTC, beaufortfrancois commented
When will this change be live?

2020-12-30 06:06 UTC, sideshowbarker commented
> When will this change be live?

I guess likely not until after January 4th, when the @mdn/core-yari-dev team is back.

2021-01-04 21:32 UTC, peterbe commented
If you're waiting for a merged PR to be in production you can partially use: https://whatsdeployed.io/s/DLi/mdn/content
But the CDN will cache content too so even if your commit has made it into the daily production build, it could still be hours until you can actually see it in developer.mozilla.org.

2021-01-05 02:04 UTC, sideshowbarker commented
> But the CDN will cache content too

Is there any way from the user side to force cache invalidation for a particular resource? I’m guessing not, but figured it worth asking a least. 

> so even if your commit has made it into the daily production build, it could still be hours until you can actually see it in developer.mozilla.org.

It seems like it would be good if we were able to give contributors some rough idea of just how long it takes in total.

For example, there’s a certain time each day when the push to production happens, right? There’s some cron job that runs at least once a day, I guess? So maybe we can document what time that actually is.

And then along with that, we have a rough idea of how long the cache invalidations take — 4 hours, or 6 hours, or 8 hours?

So maybe in the end we could say something like, _It should take at most 32 hours (or whatever the actual number works out to) for a change you contribute to finally show up on the production site_.

2021-01-05 09:53 UTC, beaufortfrancois commented
Is it the same for mdn/browser-compat-data?
https://github.com/mdn/browser-compat-data/pull/8458/ has been merged for instance, but still not live as far as I can see

2021-01-05 12:41 UTC, peterbe commented
> For example, there’s a certain time each day when the push to production happens, right? There’s some cron job that runs at least once a day, I guess? So maybe we can document what time that actually is.
> 
> And then along with that, we have a rough idea of how long the cache invalidations take — 4 hours, or 6 hours, or 8 hours?
> 
> So maybe in the end we could say something like, _It should take at most 32 hours (or whatever the actual number works out to) for a change you contribute to finally show up on the production site_.

The complete build runs every 24h at around 7PM US/Eastern time. But we don't specify the time so I think we're at the mercy of GitHub's pick of the clock. 

The CDN is configured to hold on to things 24h (coincidence number) too. 
So the max ("worst case") time from merged-to-`main` till you can see it in the browser is 48h. 

If you can think up a good place to explain and document this in the README (or contribution guide) we can solidifiy it there.

2021-01-05 12:43 UTC, peterbe commented
> Is it the same for mdn/browser-compat-data?
> [mdn/browser-compat-data#8458](https://github.com/mdn/browser-compat-data/pull/8458) has been merged for instance, but still not live as far as I can see

That project makes a release (to npmjs.com) roughly every 7 days. I think it's almost always on Thursdays. 
Once it's released, Dependabot will upgrade our version of it in mdn/yari and it should get auto-merged. Then, in the next 24h it will be used in a new build.

2021-01-05 14:48 UTC, sideshowbarker commented
> If you can think up a good place to explain and document this in the README (or contribution guide) we can solidifiy it there.

Raised https://github.com/mdn/content/pull/959