added clarity
mdn/content pull request #6879
Opened 2021-07-14 00:56 UTC by ConsciousClay

This section is in need of **parallelism**. The structure is parallel, but the wording is not. Also, novel terms should _really_ be explained either immediately (which is ideal) or later but with an adjacent parenthetical remark. The original didn't do either.

2021-07-14 07:10 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
the rest is fine, but this I feel needs to stay, as the change could be interpreted as adding `display: inline`, however, other values of display give the box an outer display type of inline and I want to keep the clarity here.

2021-07-14 07:10 UTC, rachelandrew requested changes
See comment inline.

2021-07-15 16:58 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
Okay! Whatever you think is best. I had a look at the preview page, and it contains this glaring error:

> Some HTML elements, such as <a>, <span>, <em> and <strong>, The <a> element, used for links, <span>, <em> and <strong> use inline as their outer display type by default.

Besides that, it looks good to me.

2021-07-17 17:32 UTC, ConsciousClay commented
uh oh, I was trying to clean my old unused branches and deleted this one by mistake. I thought GitHub would warn me first if the branch wasn't merged. How do I open this PR again?

2021-07-19 06:42 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
```suggestion
<p>If a box has an outer display type of <code>inline</code>, then:</p>
```

2021-07-19 06:44 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>Some HTML elements, such as <code>&lt;a&gt;</code>, <code>&lt;span&gt;</code>, <code>&lt;em&gt;</code> and <code>&lt;strong&gt;</code>,
This is a weird fragment, what were you trying to add here?

2021-07-19 06:44 UTC, rachelandrew requested changes
See comments inline

2021-07-19 15:40 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
The structure is already parallel. What I wanted to do is make the wording parallel. These two sentences are in parallel structure but not in wording:

1) If a box is defined as a block, it will behave in the following ways

2) If a box has an outer display type of inline, then:

The first uses "**define**" as the predicator. The second uses "**has**". Moreover, the second makes explicit the concept of **outer display type**, but the first doesn't. I may be failing to understand something here, but right now I don't see any reason why we shouldn't use consistent, parallel wording. Parallelism is just a general aim of clear writing. It's used all the time.

2021-07-19 15:48 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>Some HTML elements, such as <code>&lt;a&gt;</code>, <code>&lt;span&gt;</code>, <code>&lt;em&gt;</code> and <code>&lt;strong&gt;</code>,
That sentence is a disaster. I have no idea how it became so garbled. Just an accident. 😶

My aim was to make the sentences parallel:

1) Some HTML elements, such as <h1> and <p>, use block as their outer display type by default.

To make the parallel sentence we would have something like:

2) Some HTML elements, such as <a>, <span>, <em> and <strong> use inline as their outer display type by default.

Now they are parallel.

2021-07-19 15:52 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
I would suggest changing the first one then, that's the problematic one as already explained.

2021-07-19 16:14 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>If a box is defined as <code>inline</code>, then:</p>
Done. I also amended my blunderous sentence about the HTML elements.

How's it look?

2021-07-28 09:25 UTC, rachelandrew requested changes
See inline comment

2021-07-29 19:46 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>In CSS we broadly have two types of boxes — <strong>block boxes</strong> and <strong>inline boxes</strong>. These characteristics refer to how the box behaves in terms of page flow, and in relatio
I was using the term **"property"** broadly because that's how I'm used to it being used. Properties in this case are synonymous with **features** or **qualities**. I didn't intend the technical meaning found in programming jargon. I suppose we can change the term **property** to **quality** or **feature**?

2021-07-30 09:14 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>In CSS we broadly have two types of boxes — <strong>block boxes</strong> and <strong>inline boxes</strong>. These characteristics refer to how the box behaves in terms of page flow, and in relatio
When writing technical documentation, you have to avoid using language that has special meaning, as it is confusing. I'm fully aware of how the word property is used in English, but this is not an essay. But anyhow, the whole sentence is just wrong. They aren't an "inner or outer display type" they always have both.

A box has an outer display type (which is either block or inline), it has an inner display type, which dictates whether the children follow block and inline layout (flow), grid, or flex layout. In the new spec, this is referred to by two values for the display property, so you might have:

```
.box {
  display: block flow; /* a block box with flow layout children*/
}

.box {
 display: inline flex; / * an inline box with flex children, in the old spec this is display: inline-flex; */
}
```

2021-07-30 16:44 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>In CSS we broadly have two types of boxes — <strong>block boxes</strong> and <strong>inline boxes</strong>. These characteristics refer to how the box behaves in terms of page flow, and in relatio
I don't know what the reference to an essay is about. This is how I normally talk.

So you want me to instead say that boxes have an outer and inner display type? That's fine. I'm just not used to saying that abstract things have abstract things, e.g., that numbers have anything. This sounds odder to me than speaking clearly about properties.

It doesn't matter to me what you decide. I'm just trying to add clarity to these pages. If you want to change something, then just do it or tell me to do it, and I'll do it. There's no need to insinuate I'm trying to use special language, because I don't intend that at all.

2021-07-30 16:58 UTC, ConsciousClay reviewed
done

2021-07-30 19:14 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>In CSS we broadly have two types of boxes — <strong>block boxes</strong> and <strong>inline boxes</strong>. These characteristics refer to how the box behaves in terms of page flow, and in relatio
When I say this isn't an essay, what I'm saying is that this is technical documentation. It has to be edited with an understanding of the language being described. That means that sometimes words will be used in a way other than they are used in standard English. If you try and add clarity, but instead change the technical meaning of things, then we need to catch that in the edit.

I assumed that you were somewhat interested in understanding what was actually meant, hence taking the time to show an example rather than just making a change. 

When editing this learn material I'd suggest having the relevant property pages open (in this case the one for display) as that would help should how the property and values are described formally. We don't want to get too far from that as this learning material should help people to access the main documentation once they are done with the beginner material.

2021-07-30 19:23 UTC, rachelandrew approved these changes

2021-07-30 19:23 UTC, merged

2021-07-30 19:50 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>In CSS we broadly have two types of boxes — <strong>block boxes</strong> and <strong>inline boxes</strong>. These characteristics refer to how the box behaves in terms of page flow, and in relatio
> I assumed that you were somewhat interested in understanding what was actually meant, hence taking the time to show an example rather than just making a change.

Thanks!

Okay, I totally understand the point about simplicity and fidelity with technical meanings. I'll aim for that.

2021-07-30 20:23 UTC, Ryuno-Ki commented
Wow, I learned new things from following with the conversations in the comments.
Thanks for taking the time to explain things, Rachel!