First Day on GitHub & THE FLAME OF OPEN SOURCE
mdn/content pull request #6890
Opened 2021-07-14 12:06 UTC by wildcard

> What was wrong/why is this fix needed? (quick summary only)

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-07-14 12:08 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/github/index.html
> + <li><a href="https://guides.github.com/introduction/flow/">Flame of Open Source</a> by <a href="https://www.twilio.com/quest#world">TwilloQuest<a/> - Old school game to learn how to make your first
Independantly of the usefulness of it this url is clearly not the correct one.

2021-07-14 12:09 UTC, wildcard commented on files/en-us/learn/tools_and_testing/github/index.html
> + <li><a href="https://guides.github.com/introduction/flow/">Flame of Open Source</a> by <a href="https://www.twilio.com/quest#world">TwilloQuest<a/> - Old school game to learn how to make your first
Thanks! missed it...

2021-07-14 12:10 UTC, wildcard commented on files/en-us/learn/tools_and_testing/github/index.html
> + <li><a href="https://guides.github.com/introduction/flow/">Flame of Open Source</a> by <a href="https://www.twilio.com/quest#world">TwilloQuest<a/> - Old school game to learn how to make your first
Fixed it thanks ❤️

2021-07-14 12:21 UTC, teoli2003 requested changes

2021-07-14 12:21 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/github/index.html
> + <li><a href="https://www.twilio.com/quest/learn/open-source">Flame of Open Source</a> by <a href="https://www.twilio.com/quest#world">TwilloQuest<a/> (Old school game to learn how to make your first
You wrote `<a/>` instead of `</a>`.
And, as you have to fix this line anyway, I think it should be move at the end of the list.

2021-08-15 09:00 UTC, sideshowbarker commented
@wildcard This is waiting on your response to https://github.com/mdn/content/pull/6890#pullrequestreview-706206582

2021-09-01 02:51 UTC, sideshowbarker commented
Closing for lack of response

2021-09-01 02:51 UTC, closed without merging