Correct adjacent sibling combinator grammar
mdn/content pull request #6906
Opened 2021-07-15 02:21 UTC by SgtPooki

> What was wrong/why is this fix needed? (quick summary only)

The grammar and plurality of the adjacent sibling combinator's description implied that a selector of `h2 + p` would return multiple `p`'s per `h2`. This change should resolve any confusion.

> Issue number (if there is an associated issue)
None that I know of.

> Anything else that could help us review it
N/A

2021-07-15 08:18 UTC, teoli2003 reviewed
Thanks for the proposal. The original text was indeed difficult to understand. I tried to improve a bit over your proposals.

2021-07-15 08:18 UTC, teoli2003 commented on files/en-us/web/css/css_selectors/index.html
> + <dd>The <code>+</code> combinator selects a single, immediately succeeding/following, sibling element. An element can only be adjacent to sibling (same parent) elements where no siblings exist betwe
```suggestion
 <dd>The <code>+</code> combinator matches the second element only if it _immediately_ follows the first element.<br>
```
Thiis is close to what is in the specific page and avoid the word sibling that is complex. It also avoid the use of the `/` sign and of parenthesis that all are making the sentence difficult to read,

2021-07-15 08:18 UTC, teoli2003 commented on files/en-us/web/css/css_selectors/index.html
> + <strong>Example:</strong> <code>h2 + p</code> will match all {{HTMLElement("p")}} elements which have an immediately preceeding {{HTMLElement("h2")}} element.</dd>
```suggestion
 <strong>Example:</strong> <code>h2 + p</code> will match all {{HTMLElement("p")}} elements that _immediately_ follows {{HTMLElement("h2")}} element.</dd>
```

2021-07-15 08:19 UTC, teoli2003 requested changes
After these changes, I'm ready to approve and merge.

2021-07-18 23:22 UTC, ericwbailey commented on files/en-us/web/css/css_selectors/index.html
> + <strong>Example:</strong> <code>h2 + p</code> will match all {{HTMLElement("p")}} elements which have an immediately preceeding {{HTMLElement("h2")}} element.</dd>
We'd need to wrap immediately in `em`, right?

2021-07-19 05:37 UTC, teoli2003 commented on files/en-us/web/css/css_selectors/index.html
> + <strong>Example:</strong> <code>h2 + p</code> will match all {{HTMLElement("p")}} elements which have an immediately preceeding {{HTMLElement("h2")}} element.</dd>
I fixed it. Wasn't awake that day! Thanks Eric!

2021-07-19 05:40 UTC, teoli2003 approved these changes

2021-07-19 05:41 UTC, merged

2021-07-19 05:42 UTC, teoli2003 commented
Thanks a lot!

I went forward and merged the fixed version.

Congratulations upon your merged commit here!