added clarity
mdn/content pull request #6946
Opened 2021-07-15 21:26 UTC by ConsciousClay

Also, I've never seen a present participle or a gerund used to signify the name of a **categorial concept** before. It sounds odd to say "**margin collapsing**" as if it were such a concept. I may very well be wrong here, since my skills are with English and not with web development.

2021-07-16 04:57 UTC, teoli2003 requested changes
Just one change, I think.

Note that they are other occurrences of the same problem at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

As you are using the GitHub UI, and as this will require a `yarn content move` in the terminal, I propose we will do this in separate PR (I can do it).

2021-07-16 04:57 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>A key thing to understand about margins is the concept of <strong>margin collapse</strong>. If you have two elements whose margins touch, and both margins are positive, those margins will combine
```suggestion
<p>A key thing to understand about margins is the concept of <strong>margin collapse</strong>. If you have two elements whose margins touch, and both margins are positive, those margins will combine to become one margin, and its size will be equal to the largest individual margin. If one margin is negative, its value will be <em>subtracted</em> from the total. Where both are negative, the margins will collapse and the largest value will be used.</p>

I think we need the passive form here.
```

2021-07-16 06:40 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
https://www.w3.org/TR/CSS2/box.html#collapsing-margins this is referred to generally (and in specifications) as margin collapsing/collapsing margins and is what people will search for. Please check the specifications for the specific use of technical terms.

2021-07-16 07:01 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
I wonder if "margin collapsing" isn't a grammar error that is becoming the technical usual term, magnified by its extend use on MDN.

2021-07-16 17:27 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
I do see one instance of the words "**margin collapsing**" at the **w3** site. But in that sentence, it seems "collapsing" is a  **verb** (present participle) serving as the **predicate** of "margin". The words "margin" and "collapsing" are not functioning _united_ as a **compound noun**. The header of that specification is "**Collapsing margins**", which is perfectly idiomatic. Perhaps this is where the confusion lay?

Compare:
- I will not take part in the ship's sailing.
- But "ship's sailing" would never be used as a categorial concept (or rubric). One reason is those two words do not form a compound noun.

2021-07-16 17:39 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
However, the newer specifications [here ](https://drafts.csswg.org/css2/#collapsed-margin)do use the term "margin collapsing" as a compound noun. Or at least as a grammatical unit of some sort. In any case, it's very strange. I'll try getting in touch with them about this and see what they say.

2021-07-16 18:07 UTC, ConsciousClay commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
I was wrong. [There _are_](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_h&page=9ISOUCn-8TP4.html) some instances of gerunds and nouns functioning together as compound nouns:

housekeeping
shipbuilding
sightseeing
cabinetmaking
mountainclimbing

Still, "margin collapsing" sounds strange. So be it.

2021-08-04 12:08 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<p>A key thing to understand about margins is the concept of <strong>margin collapse</strong>. If you have two elements whose margins touch, and both margins are positive, those margins will combine
```suggestion
<p>A key thing to understand about margins is the concept of <strong>margin collapsing</strong>. If you have two elements whose margins touch, and both margins are positive, those margins will combine to become one margin, and its size will be equal to the largest individual margin. If one margin is negative, its value will be <em>subtracted</em> from the total. Where both are negative, the margins will collapse and the largest value will be used.</p>
```

2021-08-04 12:08 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/the_box_model/index.html
> +<h4 id="Margin_collapse">Margin collapse</h4>
```suggestion
<h4 id="Margin_collapsing">Margin collapsing</h4>
```

2021-08-05 04:25 UTC, teoli2003 approved these changes

2021-08-05 04:25 UTC, merged