Remove mentions of RTCDataChannelInit dictionary
mdn/content pull request #7148
Opened 2021-07-22 05:39 UTC by teoli2003

`RTCDataChannelInit` is a dictionary used only in `createDataChannel`. I anonymize it. (=== remove it).

With this, I'm finishing the `RTCDataChannel` rabbit hole.

2021-07-22 14:30 UTC, jpmedley requested changes

2021-07-22 14:30 UTC, jpmedley commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> -  <dd>An <a href="#rtcdatachannelinit_dictionary"><code>RTCDataChannelInit</code>
[Chrome still supports this](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/peerconnection/rtc_peer_connection.idl;l=163)

2021-07-22 15:05 UTC, teoli2003 commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> -  <dd>An <a href="#rtcdatachannelinit_dictionary"><code>RTCDataChannelInit</code>
Hi! I have not removed the description/support for it, only anonymized it: Instead of saying  

_An RTCDataChannelInit dictionary providing configuration options…_ 

(With `RTCDataChannelInit` being a link to the section immediately below.)

It now says:

_An object providing configuration options for the data channel.
    It can contain the following fields:_

followed by the content of the previous section.

2021-07-22 18:57 UTC, jpmedley requested changes

2021-07-22 18:57 UTC, jpmedley commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> +        with an agreed-upon id.
```suggestion
        with an agreed-upon ID.
```

2021-07-22 18:57 UTC, jpmedley commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> +        with an agreed-upon id.
I changed this one instead of the next occurrence because 'ID' is more common on this site than 'id', 550 vs. 212. I searched on ' ID ' and ' id ', notice the spaces. This avoid counting '.id', '<code>id' etc..

2021-07-22 18:57 UTC, jpmedley commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> +        permitted values are 0-65534.
```suggestion
        permitted values are 0 to 65534.
```

2021-07-22 20:42 UTC, bigboss978 commented on files/en-us/web/api/rtcpeerconnection/createdatachannel/index.html
> +        permitted values are 0-65534.
let outputStrings = []
for (let i = 0, n = inputValues.length; i < n; ++i) {
  outputStrings.push(String(inputValues[i]));
}

2021-07-29 14:25 UTC, jpmedley approved these changes

2021-07-29 14:26 UTC, merged