Fix broken links for ARIA pages, template
mdn/content pull request #722
Opened 2020-12-29 07:21 UTC by lychyi

## Summary
It looks like a bunch of ARIA links are still broken even though some were fixed in #608. This PR finds and replaces anywhere that starts with `/en/Accessibility` to `/en-US/docs/Web/Accessibility`

## Other changes as a result of this one
This PR also removes erroneous anchor in the ARIA-related bugs page. In the "Notes" column for [this page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/How_to_file_ARIA-related_bugs) the anchor contents say: "Discuss NVDA Issues" but it tries to link to what I assume is a defunct page on MDN about JAWS: 

![image](https://user-images.githubusercontent.com/14299381/103265063-8e1f3f80-4961-11eb-9b37-0256e2240dc0.png)

2020-12-30 19:37 UTC, ericwbailey requested changes
Thanks for this. I'm noticing the presence of the `title` attribute on many of these links. I know it's not your doing, but this is a "leave it better than you found it moment", as the `title` attribute's content is duplicative at best and (ironically) inaccessible at worst.

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/accessible_dynamic_content/index.html
> +<p>This content has been moved to <a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets" title="An overview of accessible web applications and widgets">An over
Can we remove the `title` attribute on this link? I know it's not your work, but its presence is superfluous at best.
```suggestion
<p>This content has been moved to <a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets">An overview of accessible web applications and widgets</a>.</p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/an_overview_of_accessible_web_applications_and_widgets/index.html
> +<p>So, for the Tabs widget example above, the user should be able to navigate into and out of the widget's container (the &lt;ol&gt; in our markup) using the Tab and Shift-Tab keys. Once keyboard foc
This `title` is actively harmful. Let's remove it.
```suggestion
<p>So, for the Tabs widget example above, the user should be able to navigate into and out of the widget's container (the &lt;ol&gt; in our markup) using the Tab and Shift-Tab keys. Once keyboard focus is inside the container, the arrow keys should allow the user to navigate between each tab (the &lt;li&gt; elements). From here, conventions vary from platform to platform. On Windows, the next tab should automatically be activated when the user presses the arrow keys. On Mac OS X, the user can press either Enter or the Spacebar to activate the next tab. An in-depth tutorial for creating <a href="/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets">Keyboard-navigable JavaScript widgets</a> describes how to implement this behavior with JavaScript.</p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html
> + <li>If an alert also provides interactive controls (such as form controls that allow the user to rectify a problem, or an "OK" button that discards the alert) the <a href="/en-US/docs/Web/Accessibil
Remove this `title` too.
```suggestion
 <li>If an alert also provides interactive controls (such as form controls that allow the user to rectify a problem, or an "OK" button that discards the alert) the <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role">alertdialog</a> role should be used instead. </li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_property" title="Using the aria-invalid property">Using the aria-invalid property</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_property">Using the aria-invalid property</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-describedby_attribute/index.html
> +<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-describedby" rel="external"><code>aria-describedby</code></a> attribute is used to indicate the IDs of t
```suggestion
<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-describedby" rel="external"><code>aria-describedby</code></a> attribute is used to indicate the IDs of the elements that describe the object. It is used to establish a relationship between widgets or groups and text that described them. This is very similar to <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute">aria-labelledby</a>: a label describes the essence of an object, while a description provides more information that the user might need.</span></p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute/index.html
> +<p>Note that the alert has the ARIA <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role" title="Using the alert role"><code>role attribute set to "alert."</code></a></p>
```suggestion
<p>Note that the alert has the ARIA <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role"><code>role attribute set to "alert."</code></a></p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute" title="Using the aria-required property">Using the aria-required attribute</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-required_attribute">Using the aria-required attribute</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-invalid_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role" title="Using the alert role">Using the alert role</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role">Using the alert role</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-label_attribute/index.html
> +<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-label" rel="external"><code>aria-label</code></a> attribute is used to define a string that labels the c
```suggestion
<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-label" rel="external"><code>aria-label</code></a> attribute is used to define a string that labels the current element. Use it in cases where a text label is <em>not</em> visible on the screen. If there is visible text labeling the element, use <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute">aria-labelledby</a> instead.</span></p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-orientation_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-required_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_textbox_role" title="Using the textbox role">Textbox</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_textbox_role">Textbox</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-required_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute" title="Using the aria-invalid property">Using the aria-invalid attribute</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute">Using the aria-invalid attribute</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemax_attribute/index.html
> +<p id="The_aria-valuemax_attribute_is_used_to_define_the_maximum_value_allowed_for_a_range_widget_such_as_a_slider.2C_spinbutton_or_progressbar._If_the_aria-valuenow_has_a_known_maximum_and_minimum.2
```suggestion
<p id="The_aria-valuemax_attribute_is_used_to_define_the_maximum_value_allowed_for_a_range_widget_such_as_a_slider.2C_spinbutton_or_progressbar._If_the_aria-valuenow_has_a_known_maximum_and_minimum.2C_the_author_SHOULD_provide_properties_for_aria-valuemax_and_aria-valuemin._The_value_of_aria-valuemax_MUST_be_greater_than_or_equal_to_the_value_of_aria-valuemin."><span class="seoSummary">The <a href="https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuemax">aria-valuemax</a> attribute is used to define the maximum value allowed for a range widget such as a slider, spinbutton or progressbar.</span> If the <a class="property-reference" href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute"><code>aria-valuenow</code></a> has a known maximum and minimum, the author <strong class="rfc2119">SHOULD</strong> provide properties for <code>aria-valuemax</code> and <a class="property-reference" href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuemin_attribute"><code>aria-valuemin</code></a>. The value of <code>aria-valuemax</code> <strong class="rfc2119">MUST</strong> be greater than or equal to the value of <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuemin_attribute"><code>aria-valuemin</code></a>.<span class="seoSummary"> </span></p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemax_attribute/index.html
> +<p><code>aria-valuemax</code> is a <strong>required</strong> attribute of role <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider<
```suggestion
<p><code>aria-valuemax</code> is a <strong>required</strong> attribute of role <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a>, <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_scrollbar_role">scrollbar</a> and <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_spinbutton_role">spinbutton</a>.</p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemax_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemax_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute" title="Using the aria-label attribute">aria-valuenow</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute">aria-valuenow</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemax_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute" title="Using the aria-required attribute">aria-valuetext</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute">aria-valuetext</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemin_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemin_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute" title="Using the aria-label attribute">aria-valuenow</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute">aria-valuenow</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuemin_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute" title="Using the aria-required attribute">aria-valuetext</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute">aria-valuetext</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuenow_attribute/index.html
> +<p><code>aria-valuenow</code> is a <strong>required</strong> attribute of role <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider<
```suggestion
<p><code>aria-valuenow</code> is a <strong>required</strong> attribute of role <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a>, <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_scrollbar_role">scrollbar</a> and <a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_spinbutton_role">spinbutton</a>.</p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuenow_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuenow_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute" title="Using the aria-required attribute">aria-valuetext</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute">aria-valuetext</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-valuetext_attribute/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role" title="Using the slider role">slider</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role">slider</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_slider_role/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute" title="Using the aria-label attribute">aria-valuenow</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute">aria-valuenow</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_slider_role/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute" title="Using the aria-required attribute">aria-valuetext</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute">aria-valuetext</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/forms/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/ARIA/Basic_form_hints" title="Basic form hints">Basic form hints</a>: Adding hints and descriptions for invalid or required fields</li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/ARIA/Basic_form_hints">Basic form hints</a>: Adding hints and descriptions for invalid or required fields</li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/how_to_file_aria-related_bugs/index.html
> +   <td><p>Discuss NVDA issues</p></td>
```suggestion
   <td>Discuss NVDA issues</td>
```

We shouldn't need a paragraph element inside of a table cell.

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/web_applications_and_aria_faq/index.html
> +<p>For more information about how to create accessible widgets with ARIA, see the <a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets" title="en-US/docs/Web/
```suggestion
<p>For more information about how to create accessible widgets with ARIA, see the <a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets">Overview of accessible web applications and widgets</a>.</p>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/web_applications_and_aria_faq/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets" title="en-US/docs/Web/Accessibility/An overview of accessible web applications and widgets">An over
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets">An overview of accessible web applications and widgets</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/web_applications_and_aria_faq/index.html
> + <li><a href="/en-US/docs/Web/Accessibility/Accessible_forms" title="en-US/docs/Web/Accessibility/Accessible forms">Accessible forms</a></li>
```suggestion
 <li><a href="/en-US/docs/Web/Accessibility/Accessible_forms">Accessible forms</a></li>
```

2020-12-30 19:37 UTC, ericwbailey commented on files/en-us/web/accessibility/index.html
> + <dt><a href="/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets" title="en-US/docs/Web/Accessibility/Keyboard-navigable JavaScript widgets">Keyboard-navigable JavaScript widgets</a>
```suggestion
 <dt><a href="/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets">Keyboard-navigable JavaScript widgets</a></dt>
```

2020-12-30 21:59 UTC, lychyi commented on files/en-us/web/accessibility/aria/how_to_file_aria-related_bugs/index.html
> +   <td><p>Discuss NVDA issues</p></td>
@ericwbailey There are a few in this table, I believe it was used for alignment purposes. Should I remove them all (it was probably a hack to get them to align to the top instead of being vertically centered)?

2020-12-30 22:01 UTC, lychyi commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-describedby_attribute/index.html
> +<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-describedby" rel="external"><code>aria-describedby</code></a> attribute is used to indicate the IDs of t
I believe this one is necessary. It is not a repetition of the content and it gives context to the link itself. I'm not an expert here, but it reads fine on VO which is the SR that I have on hand. Alternatively, I could change `title` to `aria-label` but there are over 2k instances of link titles in MDN, probably something that should be elevated to an issue if using `title` is not a good choice overall?

2020-12-30 22:02 UTC, lychyi commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_alert_role/index.html
> + <li>If an alert also provides interactive controls (such as form controls that allow the user to rectify a problem, or an "OK" button that discards the alert) the <a href="/en-US/docs/Web/Accessibil
Same as [below](https://github.com/mdn/content/pull/722#discussion_r550339225), this `title` adds extra information to the contents.

2020-12-31 00:40 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-describedby_attribute/index.html
> +<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-describedby" rel="external"><code>aria-describedby</code></a> attribute is used to indicate the IDs of t
In these situations, `title`'s presence would most likely be read as:

>This is very similar to using the aria-labelledby attribute a label describes the essence of an object, while a description provides more information that the user might need.

Or: 

>This is very similar to using the aria-labelledby attribute aria-labelledby a label describes the essence of an object, while a description provides more information that the user might need.

Both situations aren't ideal. If you are a sighted screen reader user or refreshable braille user, the discrepancy between written text and announced text can be confusing. 

Using `aria-label` runs against [the first rule of ARIA](https://www.w3.org/TR/using-aria/#firstrule). It also has some issues with translation in certain browsers, plus the aforementioned visible text/announced text issue.

I agree that `title` abuse is a widespread problem on this site and deserves an issue, but I'd like to see these removed given it is a section that deals specifically with accessibility.

2020-12-31 00:40 UTC, ericwbailey commented on files/en-us/web/accessibility/aria/how_to_file_aria-related_bugs/index.html
> +   <td><p>Discuss NVDA issues</p></td>
That'd be great, thank you! If there's visual alignment issues it should be handled in the CSS.

2020-12-31 01:38 UTC, lychyi commented on files/en-us/web/accessibility/aria/aria_techniques/using_the_aria-describedby_attribute/index.html
> +<p><span class="seoSummary">The <a class="external" href="https://www.w3.org/TR/wai-aria/#aria-describedby" rel="external"><code>aria-describedby</code></a> attribute is used to indicate the IDs of t
I see, I have it backwards then, I assumed it helped clarify the link not confuse it. Always learning. Thanks for the explanation!

2020-12-31 01:50 UTC, ericwbailey approved these changes
Awesome stuff! Thanks for going the extra mile here 🙂

2020-12-31 06:41 UTC, lychyi commented
@ericwbailey caught some more `title` attributes. I did a scan for pages in `**/accessibility` so hopefully this is it for this section

2021-01-02 20:27 UTC, ericwbailey commented
@lychyi Amazing, thanks for that. I'm seeing one conflict, then I think this is good to go.

2021-01-04 10:08 UTC, chrisdavidmills approved these changes
Another couple of merge conflicts crept in. I've fixed those, and will now merge.

2021-01-04 10:09 UTC, merged

2021-01-04 10:09 UTC, chrisdavidmills commented
Thanks @lychyi !