CSSSupportsRule
mdn/content pull request #723
Opened 2020-12-29 08:26 UTC by rachelandrew

Working on #344 

This PR updates CSSSupportsRule. There are no specific properties or methods for this one, so the update is to make it consistent with the others and add an example.

Reviewer: @jpmedley

2021-01-05 21:32 UTC, jpmedley requested changes

2021-01-05 21:32 UTC, jpmedley commented on files/en-us/web/api/csssupportsrule/index.html
> +<p>The <strong><code>CSSSupportsRule</code></strong> interface represents a single CSS {{cssxref("@supports")}} <a href="/en-US/docs/Web/CSS/At-rule">at-rule</a>. It implements the {{domxref("CSSCond
Should this link to @supports or "at-rule"? Either way, it should be done with the macro instead of an anchor tag. I've seen this in at least one other place. Please check this throughout.

This is a child interface, not an implementor of an interface. Please add the inheritance sequence to [InterfaceData](https://github.com/mdn/kumascript/blob/master/macros/InterfaceData.json). Then add the InheritanceDiagram macro to this page:

`<p>{{InheritanceDiagram}}</p>`

You'll be able to remove the description of the inheritance out of the text.

2021-01-06 08:04 UTC, rachelandrew commented on files/en-us/web/api/csssupportsrule/index.html
> +<p>The <strong><code>CSSSupportsRule</code></strong> interface represents a single CSS {{cssxref("@supports")}} <a href="/en-US/docs/Web/CSS/At-rule">at-rule</a>. It implements the {{domxref("CSSCond
I've not encountered the InheritanceDiagram before. The InterfaceData file I think is now in Yari. PR here: https://github.com/mdn/yari/pull/2352

All of these CSSRule interfaces that I have updated will have identical text at the start because I just edited what was already there to remove the legacy type stuff. So I'll go round and change them all as per the above.

2021-01-08 15:15 UTC, jpmedley commented on files/en-us/web/api/csssupportsrule/index.html
> +<p>The <strong><code>CSSSupportsRule</code></strong> interface represents a single CSS {{cssxref("@supports")}} <a href="/en-US/docs/Web/CSS/At-rule">at-rule</a>. It implements the {{domxref("CSSCond
Thank you.

2021-01-08 15:16 UTC, jpmedley approved these changes

2021-01-08 15:16 UTC, merged