Adds NavigatorUAData
mdn/content pull request #7280
Opened 2021-07-26 09:40 UTC by rachelandrew

Adds the `NavigatorUAData` interface.

Reviewer @jpmedley

2021-07-29 13:54 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/gethighentropyvalues/index.html
> +<p class="summary">The <strong><code>getHighEntropyValues()</code></strong> method of the {{domxref("NavigatorUAData")}} interface is a {{jsxref("Promise")}} that resolves with a dictionary object co
Can you please do a follow up PR to define entropy in this context. There are no definitions on the internet but I don't want to hold this up. 

I got this definition from an engineer: "Low-entropy hints are hints that don't give away too much information, or give information that would be too easy to discover in other ways to realistically hide. In the context of client hints, this means that these hints are available in every request, whether or not the origin involved requested it or if the frame involved is a 1st or 3rd party context."

2021-07-29 14:06 UTC, rachelandrew commented on files/en-us/web/api/navigatoruadata/gethighentropyvalues/index.html
> +<p class="summary">The <strong><code>getHighEntropyValues()</code></strong> method of the {{domxref("NavigatorUAData")}} interface is a {{jsxref("Promise")}} that resolves with a dictionary object co
I was thinking it might be a good glossary entry? As other things may well need to link to it.

2021-07-29 14:22 UTC, jpmedley requested changes
Clean as usual. I have a few questions though.

2021-07-29 14:22 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/gethighentropyvalues/index.html
> +<p>In the following value a number of hints are requested using the <code>getHighEntropyValues()</code> method. When the promise resolves, this information is printed to the console.</p>
```suggestion
<p>In the following example a number of hints are requested using the <code>getHighEntropyValues()</code> method. When the promise resolves, this information is printed to the console.</p>
```

2021-07-29 14:22 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/index.html
> +<div class="notecard note">
I think this is important enough to be after the summary. Please move.

2021-07-29 14:22 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/tojson/index.html
> +</div>
Please add this note or something like it to the `getHighEntropyValues()` page.

2021-07-29 14:22 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/tojson/index.html
> +  <p>The terms <em>high entropy</em> and <em>low entropy</em> refer to the amount of information these values reveal about the browser. The values available as JSON, are the same as those that can be
>The values available as JSON...

This seems like a repeat of the basic description of `toJSON()`. Does this need to be here? Am I missing something?

2021-07-29 15:45 UTC, rachelandrew commented on files/en-us/web/api/navigatoruadata/tojson/index.html
> +  <p>The terms <em>high entropy</em> and <em>low entropy</em> refer to the amount of information these values reveal about the browser. The values available as JSON, are the same as those that can be
I was just making the note about values again, and also noting that the values returned are only those available as properties, and not the high entropy values.

2021-07-29 19:29 UTC, jpmedley requested changes

2021-07-29 19:29 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/tojson/index.html
> +  <p>The terms <em>high entropy</em> and <em>low entropy</em> refer to the amount of information these values reveal about the browser. The values available as JSON, are the same as those that can be
I'm not getting that out of this description. All I'm getting is a repeat of the summary. Please take another shot at this.

2021-07-30 01:12 UTC, hamishwillee commented on files/en-us/web/api/navigatoruadata/gethighentropyvalues/index.html
> +<p class="summary">The <strong><code>getHighEntropyValues()</code></strong> method of the {{domxref("NavigatorUAData")}} interface is a {{jsxref("Promise")}} that resolves with a dictionary object co
> I got this definition from an engineer: "Low-entropy hints are hints that don't give away too much information, or give information that would be too easy to discover in other ways to realistically hide. In the context of client hints, this means that these hints are available in every request, whether or not the origin involved requested it or if the frame involved is a 1st or 3rd party context."

@jpmedley That's interesting. FWIW my guess from the meaning of the term "entropy" (and the hints that are marked as "low entropy) was that the low entropy hints were the ones where only a small set of possible values are allowed - while the high entropy hints were much less constrained. That ties in quite well with what the engineer said - the information in the low entropy hints will necessarily be quite broad.

2021-07-30 13:59 UTC, jpmedley commented on files/en-us/web/api/navigatoruadata/gethighentropyvalues/index.html
> +<p class="summary">The <strong><code>getHighEntropyValues()</code></strong> method of the {{domxref("NavigatorUAData")}} interface is a {{jsxref("Promise")}} that resolves with a dictionary object co
The difference is context. This is specifically about the meaning of low entropy in a privacy/security context. With the possibility of fingerprinting that this API creates, the privacy/security context is the one that's needed.

2021-07-30 17:28 UTC, jpmedley approved these changes

2021-07-30 17:28 UTC, merged