(CSS: Web Fonts) - various typographical fixes/improvements
mdn/content pull request #7355
Opened 2021-07-27 20:23 UTC by ConsciousClay

Nothing to add

2021-07-27 20:27 UTC, Ryuno-Ki commented
Gently reminder on https://github.com/mdn/content/pull/7207#issuecomment-886012404

2021-07-27 20:41 UTC, ConsciousClay commented
> Gently reminder on [#7207 (comment)](https://github.com/mdn/content/pull/7207#issuecomment-886012404)

I thought I did. If my prefix isn't good enough, you can suggest a different format and I'll follow it.

2021-07-27 20:47 UTC, Ryuno-Ki commented
I'm a bit puzzled about

> Nothing to add

If I were looking at e-mail notifications, this line would require me to follow the link to the PR so I can assess the workload.
If I'm pretty busy, I might not do that right away. You can do yourself a favour by providing a bit more context (about what you changed, why you changed it etc) and help the reviewers take a look at your changes.

If you need a format, I suggest to look at other closed PRs for how they phrased their PRs.

Thank you for taking time to contribute to MDN Web Docs. We appreciate the effort.

2021-07-28 07:08 UTC, rachelandrew requested changes
Please see my note about word choice.

2021-07-28 07:08 UTC, rachelandrew commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> +<p>This system works well, but traditionally web developers' font choices were limited. There are only a handful of fonts that you can guarantee to be available across all common systems — the so-cal
```suggestion
<p>This system works well, but traditionally web developers' font choices were limited. There are only a handful of fonts that you can guarantee to be available across all common systems — the so-called <a href="/en-US/docs/Learn/CSS/Styling_text/Fundamentals#web_safe_fonts">Web-safe fonts</a>. You can use the font stack to specify preferred fonts, followed by web-safe alternatives, followed by the default system font. However, this increases your workload because of the testing required to make sure that your designs work with each font.</p>
```

Try to use the simplest words possible, remembering that our audience may not be using English as their first language.

2021-07-29 19:54 UTC, ConsciousClay commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> +<p>This system works well, but traditionally web developers' font choices were limited. There are only a handful of fonts that you can guarantee to be available across all common systems — the so-cal
Sure thing 👍

I was trying to avoid repeated use of the morpheme/phoneme "**work**", given that the sentence already used the word "**workload**".

2021-07-29 19:58 UTC, Ryuno-Ki commented
Can you resolve the merge conflict?

2021-07-29 20:04 UTC, ConsciousClay commented
> 
> 
> Can you resolve the merge conflict?

There are always merge conflicts when I file PRs. I don't know anything about what they are or how to resolve them.

2021-07-29 20:06 UTC, Ryuno-Ki commented
I imagine that this might feel quite frustrating :-(

Are you willing to learn what they are and how to resolve them or do you want someone else to assist you on them?

2021-07-29 20:09 UTC, ConsciousClay commented
> 
> 
> I imagine that this might feel quite frustrating :-(
> 
> Are you willing to learn what they are and how to resolve them or do you want someone else to assist you on them?

It's not frustrating for me. I thought they were somewhat trivial because my PRs get merged anyhow.

I'm willing to resolve them myself if I know how. You want to provide some guidance?

2021-07-29 20:12 UTC, Ryuno-Ki commented
If my time permits.
It's already evening over here, so I won't be around for much longer.

The first step should be to learn what they are about. GitHub provides some documentation about them:
https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

The one here should be able to get resolved within GitHub's web UI: https://github.com/mdn/content/pull/7355/conflicts (hit the „Resolve conflicts” button to get there).

You have to decide, which variant is correct (or combine them to a final one), then scroll all the way up and click on „Mark as resolved”. That should allow you to save the changes.

2021-07-29 20:21 UTC, ConsciousClay commented
@Ryuno-Ki Could you explain what I'm looking at here?

![image](https://user-images.githubusercontent.com/51193876/127560177-ccd3d2d8-1e4e-4de6-b8a9-3735b69d6936.png)

In particular, what's the difference between **current change** and **incoming change**? And what's the difference between the upper half of the text (lines 182-188) and the bottom half (lines 188-194)?

Thanks

2021-07-29 21:03 UTC, Ryuno-Ki commented
I can - and I will.

You're proposing a change like this:

![image](https://user-images.githubusercontent.com/3097194/127564883-c1bd4b79-5af4-4a27-98d2-ab5edce78109.png)

Edited by others, the current state in the target codebase is

https://github.com/mdn/content/blob/eef62291f54b9bdab36ad0d19e7ea6fb92add7f1/files/en-us/learn/css/styling_text/web_fonts/index.html#L180-L187

Both modified the text. Git tries to make sense of it, but can't decide, which variant is correct. That's why it asks for a human to assist (=> a merge conflict).

Regarding the naming, I defer to https://stackoverflow.com/a/59658315 by @VonC (we're  dealing with a merge and not a rebase here):

> It depends on the type of operation ([merge or rebase](https://stackoverflow.com/a/7062773/6309)) leading to that conflict.
> 
> In your case, a merge, where:
> 
> * current change represents what you have (the destination of the merge)
> * incoming change represents what you merge (the source of the merge)
> 
> Then:
> 
> * Option 1 ("Accept Incoming changes") would ignore completely what you had, and keep what you merge.
> * Option 2 ("Accept current changes") would ignore completely what you merge, and keep what you had.
> 
> Don't forget, in case of a rebase, ["what you have" and "what you merge" are reversed](https://stackoverflow.com/a/2960751/6309).

2021-07-29 22:33 UTC, ConsciousClay commented
Okay, done. Thanks. I marked the conflict as resolved and then I merged the commit.

2021-07-30 08:55 UTC, rachelandrew approved these changes

2021-07-30 08:55 UTC, rachelandrew commented on files/en-us/learn/css/styling_text/web_fonts/index.html
> +<p>But there is an alternative that works very well. (It's even supported by such older browser's as IE version 6). CSS allows you to specify font files, available on the web, to be downloaded along
```suggestion
<p>But there is an alternative that works very well. (It's even supported by such older browsers as IE version 6). CSS allows you to specify font files, available on the web, to be downloaded along with your website as it's accessed. This means that any browser supporting this CSS feature can display the fonts you've specifically chosen. Amazing! The syntax required looks something like this:</p>
```

2021-07-30 08:56 UTC, merged