Text fixes in a few Learn CSS documents
mdn/content pull request #7378
Opened 2021-07-28 09:04 UTC by rachelandrew

Fixes: #7173 
Fixes: #7098 
Fixes: #6658 

Minor text snags, I also fixed some notecards, and the height on some examples to remove scrollbars while I was on these pages.

2021-07-28 09:31 UTC, teoli2003 requested changes
Looks good except the technical changes about notes (made a few days ago by @wbamberg in preparation of the migration to Markdown). (see first comment for reference)

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
> +  <h4>Note:</h4>
In #7170, @wbamberg made all notes consistent through CSS (like in JS last month). This allows the md converter to parse them correctly, and also prevent yari to raise a _sectioning flaw_.

So `<p><strong>Note</strong></p>: See {{…` is the way to go for notes (and warnings, with the correct text).

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
> +<div class="notecard note">
See comment above.

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
> +<div class="notecard note">
See comment before

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/debugging_css/index.html
> +<h4>Note:</h4>
See comment before.

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/debugging_css/index.html
> +  <h4>Note:</h4>
See comment before.

2021-07-28 09:31 UTC, teoli2003 commented on files/en-us/learn/css/building_blocks/sizing_items_in_css/index.html
> +  <h4>Note:</h4>
See comment before.

2021-07-29 09:44 UTC, rachelandrew commented on files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
> +  <h4>Note:</h4>
Then I would strongly suggest the style guide is changed https://developer.mozilla.org/en-US/docs/MDN/Guidelines/CSS_style_guide#.note.notecard as I've been changing then to the "new" way of doing them that was added to the style guide.

2021-07-30 02:13 UTC, hamishwillee commented on files/en-us/learn/css/building_blocks/cascade_and_inheritance/index.html
> +  <h4>Note:</h4>
Makes sense to me https://github.com/mdn/content/pull/7437

2021-07-30 09:28 UTC, rachelandrew commented
@teoli2003 I fixed up the notes :)

2021-08-04 10:58 UTC, rachelandrew commented
@teoli2003 could you re-look at this one for me?

2021-08-04 14:14 UTC, teoli2003 approved these changes

2021-08-04 14:14 UTC, merged

2021-08-04 14:14 UTC, teoli2003 commented
Thanks!