Fixes #6676
mdn/content pull request #7394
Opened 2021-07-28 17:26 UTC by Anurella

> What was wrong/why is this fix needed? (quick summary only)
An example was needed to highlight the use of :scope pseudo class.

> Issue number (if there is an associated issue)
 #6676

> Anything else that could help us review it

2021-07-28 17:39 UTC, Ryuno-Ki reviewed
I believe, the `package-lock.json` should not be part of this PR.

I've highlighted some small nitpicks you can address while waiting for the proper review by the team.

2021-07-28 17:39 UTC, Ryuno-Ki commented on README.md
> +within your browser. Do not forget to run npm install for dependencies.
```suggestion
within your browser. Do not forget to run `npm install` for dependencies.
```
By declaring it as `<code>`, it is easier to understand what to run.

2021-07-28 17:39 UTC, Ryuno-Ki commented on README.md
>  this local preview service is available at `http://localhost:5000`
```suggestion
this local preview service is available at `http://localhost:5000/`
```
can save a redirect in the web browser (tiny performance win).

2021-07-28 17:39 UTC, Ryuno-Ki commented on changes.md
> +1. [Example of :scope in element.querySelector()](https://github.com/mdn/content/issues/6676)
What is the motivation for this file?

2021-07-28 17:39 UTC, Ryuno-Ki commented on files/en-us/web/api/element/queryselector/index.html
> +  retrieve direct children of the <code>parentElement </code></p>
```suggestion
  retrieve direct children of the <code>parentElement</code>.</p>
```

2021-07-28 17:39 UTC, Ryuno-Ki commented on files/en-us/web/api/element/queryselector/index.html
> +<h4 id="Javascript"> JavaScript</h4>
```suggestion
<h4 id="Javascript">JavaScript</h4>
```

2021-07-28 17:39 UTC, Ryuno-Ki commented on files/en-us/web/api/element/queryselector/index.html
> +<h4 id="result"> Result </h4>
```suggestion
<h4 id="result">Result</h4>
```

2021-07-28 17:47 UTC, Anurella commented on changes.md
> +1. [Example of :scope in element.querySelector()](https://github.com/mdn/content/issues/6676)
Added to .gitignore

2021-07-28 18:32 UTC, Ryuno-Ki commented
Looks good to me.

Whoever happens to review this, please take a look, whether the id attributes have the right casing.
(I'm unsure what the right way is off-hand).

2021-07-28 18:33 UTC, Ryuno-Ki commented
The failing tests is about `changes.md`:

> First line in a file should be a top-level heading [Context: "## Issues to be worked on"]

2021-07-28 18:45 UTC, Ryuno-Ki commented
I filled a follow-up to deal with the detected flaws, so don't worry about them.

2021-07-28 22:59 UTC, sideshowbarker requested changes
Looks great — I just have a few styling changes to suggest

2021-07-28 22:59 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +
```suggestion


```

2021-07-28 22:59 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +<h3 id="Get_direct_descendants_using_scope_pseudo_class"> Get direct descendants using :scope pseudo-class</h3>
```suggestion
<h3 id="get_direct_descendants_using_the_scope_pseudo_class">Get direct descendants using the :scope pseudo-class</h3>
```

2021-07-28 22:59 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +  retrieve direct children of the <code>parentElement</code>.</p>
```suggestion
<p>This example uses the <a href="/en-US/docs/Web/CSS/:scope">:scope</a> pseudo-class to retrieve direct children of the <code>parentElement</code> element.</p>
```

2021-07-28 22:59 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +
```suggestion


```

2021-07-28 23:01 UTC, sideshowbarker commented
Would also be good to have a review from @rachelandrew

2021-07-28 23:36 UTC, sideshowbarker commented
@Anurella This branch originally had another commit, “Added a note and example for using fill() with empty array” 443067fc6a0d184bc2f28b3d23a06d823d1ab125 that I think you didn’t intend to be part of this PR but instead for another PR? I have stripped that commit out of this PR branch, so if you don’t have a local copy of that commit, here’s copy of the diff:

````diff
commit 443067fc6a0d184bc2f28b3d23a06d823d1ab125
Author: Anurella <ndukwuamaka@yahoo.com>
Date:   Wed Jul 28 22:11:09 2021 +0100

    Added a note and example for using fill() with empty array

diff --git a/files/en-us/web/javascript/reference/global_objects/array/fill/index.md b/files/en-us/web/javascript/reference/global_objects/array/fill/index.md
index e42dae9481..ae6f2a2594 100644
--- a/files/en-us/web/javascript/reference/global_objects/array/fill/index.md
+++ b/files/en-us/web/javascript/reference/global_objects/array/fill/index.md
@@ -48,6 +48,11 @@ The modified array, filled with `value`.
 - `fill` is a mutator method: it will change the array itself and return it, not a copy of it.
 - If the first parameter is an object, each slot in the array will reference that object.
 
+<div class="note notecard" markdown="1">
+Note: Using Array.Fill() on an empty array would not modify it as the array has nothing to be modified. To use Array.Fill() when declaring an array, make sure to assign slots to the array.
+<a href="#using_fill_to_populate_an_empty_array">See example</a>
+</div>
+
 ## Polyfill
 
 ```js
@@ -135,6 +140,15 @@ console.log(arr[1][0]); // 1
 console.log(arr[2][0]); // 1
 ```
 
+### Using fill() to populate an Empty Array
+
+This example shows how to populate an array with random values. The end value 
+does not have to be specified.
+
+```js
+let tempGirls = Array(5).fill("girl",0);
+```
+
 ## Specifications
 
 {{Specifications}}
````

2021-07-29 00:30 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +
```suggestion
```

2021-07-29 00:31 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +
```suggestion

```

2021-07-29 00:31 UTC, sideshowbarker commented on files/en-us/web/api/element/queryselector/index.html
> +<p>{{ EmbedLiveSample('Get_direct_descendants_using_scope_pseudo_class', 600, 160) }}</p>
```suggestion
<p>{{ EmbedLiveSample('Get_direct_descendants_using_scope_pseudo_class', 600, 160) }}</p>

```

2021-07-29 09:04 UTC, sideshowbarker approved these changes

2021-08-27 10:55 UTC, rachelandrew approved these changes

2021-08-27 10:57 UTC, merged