correct grammatical error on animation-name CSS reference page
mdn/content pull request #7399
Opened 2021-07-28 20:42 UTC by idorenyinudoh

> What was wrong/why is this fix needed? (quick summary only)

There's a grammatical error that could lead to confusion

> Issue number (if there is an associated issue)

> Anything else that could help us review it

2021-07-28 23:29 UTC, wbamberg requested changes
Thanks for your PR, @idorenyinudoh ! I like the first change but think the second one (to animation-name) is not needed.

2021-07-28 23:29 UTC, wbamberg commented on files/en-us/web/css/animation-name/index.html
> +<p>The <strong><code>animation-name</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> property specifies the names of one or more {{cssxref("@keyframes")}} at-rule or at-rules describing the anim
I think "one or more at-rules" is fine here.

2021-07-29 03:20 UTC, idorenyinudoh commented
> Thanks for your PR, @idorenyinudoh ! I like the first change but think the second one (to animation-name) is not needed.

Yeah that's one a mistake. My bad.

2021-07-29 22:24 UTC, wbamberg commented on files/en-us/web/css/animation-name/index.html
> +<p>The <strong><code>animation-name</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> property specifies the names of one or more {{cssxref("@keyframes")}} at-rule or at-rules describing the anim
```suggestion
<p>The <strong><code>animation-name</code></strong> <a href="/en-US/docs/Web/CSS">CSS</a> property specifies the names of one or more {{cssxref("@keyframes")}} at-rules describing the animation or animations to apply to the element.</p>
```

2021-07-29 22:35 UTC, wbamberg approved these changes
👍 thanks for the fix @idorenyinudoh !

2021-07-29 22:35 UTC, merged