(CSS Layout: Normal Flow) - various typographical fixes/improvements
mdn/content pull request #7493
Opened 2021-08-01 19:05 UTC by ConsciousClay

- Fixed mechanics: punctuation, grammar, and paragraphing
- Improved diction
- Added some boldness for key terms
- Applied consistent use of contractions

2021-08-02 06:46 UTC, rachelandrew requested changes
Please see my comment inline.

2021-08-02 06:46 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/normal_flow/index.html
> +<p>By default, a <a href="/en-US/docs/Web/HTML/Block-level_elements">block level element</a>'s content fills the available inline space of the parent element containing it and grows along the perpend
please return this to using block, rather than perpendicular.

2021-08-03 21:52 UTC, ConsciousClay commented on files/en-us/learn/css/css_layout/normal_flow/index.html
> +<p>By default, a <a href="/en-US/docs/Web/HTML/Block-level_elements">block level element</a>'s content fills the available inline space of the parent element containing it and grows along the perpend
Oooh, I still don't understand. 😕

Okay, done.

2021-08-04 10:21 UTC, rachelandrew approved these changes

2021-08-04 10:21 UTC, merged