update template to avoid extra references to issue
mdn/content pull request #7499
Opened 2021-08-01 23:35 UTC by hamirmahal

> Issue number to be fixed (ie 'Fixes #7500', if there is an associated issue)

Fixes #7500.

> What was wrong/why is this fix needed? (quick summary only)

#123 has a lot of unnecessary references.

> Anything else that could help us review it

[`.github/PULL_REQUEST_TEMPLATE`](https://github.com/mdn/content/blob/main/.github/PULL_REQUEST_TEMPLATE) in their pull request

2021-08-01 23:51 UTC, sideshowbarker requested changes

2021-08-01 23:51 UTC, sideshowbarker commented on .github/PULL_REQUEST_TEMPLATE
> +> Issue number to be fixed (for example, 'Fixes #X', where X is the associated issue number, if it exists)
```suggestion
> Issue number to be fixed (for example, 'Fixes <span>#</span>123', where `123` is the associated issue number, if it exists)
```
I think this will work. But @hamishwillee should also review this

2021-08-02 00:36 UTC, hamishwillee commented on .github/PULL_REQUEST_TEMPLATE
> +> Issue number to be fixed (for example, 'Fixes #X', where X is the associated issue number, if it exists)
@sideshowbarker The problem is that people see the raw version, not the rendered version. So if you have spans in there, that is what people see and maybe copy. The trick is to use an issue number that doesn't and is unlikely to exist - then you don't need to have any particular markup. 

I would propose something like:

```
> Issue number that this PR fixes (if any). For example, for a PR that fixes issue 987654321 you would write:  Fixes #987654321
```

Which renders as

> Issue number that this PR fixes (if any). For example, for a PR that fixes issue 987654321 you would write:  Fixes #987654321

2021-08-02 01:26 UTC, sideshowbarker approved these changes

2021-08-02 01:26 UTC, merged