Adds missing pages to CSSStyleSheet
mdn/content pull request #7545
Opened 2021-08-03 13:38 UTC by rachelandrew

The newer constructor and methods for creating stylesheets (known as Constructable StyleSheets) were missing from the docs. This PR adds them.

Reviewer: @jpmedley

2021-08-04 14:10 UTC, jpmedley requested changes

2021-08-04 14:10 UTC, jpmedley commented on files/en-us/web/api/cssstylesheet/replace/index.html
> +  <dd>If the stylesheet has its disallow modification flag yet to indicate it may not be changed.</dd>
This sentences doesn't sound right. I can't work out what it might be trying to say.

2021-08-04 14:10 UTC, jpmedley commented on files/en-us/web/api/cssstylesheet/replace/index.html
> +<p>In the following example a new stylesheet is created and two CSS rules are added using <code>replace</code>. The first rule is then printed to the console, which will return: <code>body { font-siz
```suggestion
<p>In the following example a new stylesheet is created and two CSS rules are added using <code>replace()</code>. The first rule is then printed to the console, which will return: <code>body { font-size: 1.4em };</code></p>
```

2021-08-04 20:02 UTC, Ryuno-Ki commented on files/en-us/web/api/cssstylesheet/index.html
> + <li><a href="https://developers.google.com/web/updates/2019/02/constructable-stylesheets">Constructable Stylesheets</a></li>
I can find several instances of this domain + path in MDN. I suggest opening a new ticket to remove / replace them.

2021-08-05 09:05 UTC, rachelandrew commented on files/en-us/web/api/cssstylesheet/index.html
> + <li><a href="https://developers.google.com/web/updates/2019/02/constructable-stylesheets">Constructable Stylesheets</a></li>
I've added moving that to my list, when I do that I'll also update these links.

2021-08-05 09:06 UTC, rachelandrew commented on files/en-us/web/api/cssstylesheet/cssstylesheet/index.html
> +      <dd>A {{domxref("DOMString","string")}} containing the baseURL used to resolve relative URLs in the stylesheet.</dd>
```suggestion
      <dd>A {{domxref("DOMString","string")}} containing the <code>baseURL</code> used to resolve relative URLs in the stylesheet.</dd>
```

2021-08-05 09:18 UTC, rachelandrew commented on files/en-us/web/api/cssstylesheet/index.html
> + <li><a href="https://developers.google.com/web/updates/2019/02/constructable-stylesheets">Constructable Stylesheets</a></li>
removing the links for now.

2021-08-05 18:44 UTC, jpmedley approved these changes

2021-08-05 18:44 UTC, merged