Refine explanation list-style in Safari
mdn/content pull request #7594
Opened 2021-08-04 17:26 UTC by plweil

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Addresses #4103

> What was wrong/why is this fix needed? (quick summary only)
The explanation and workaround were a bit outdated; new information and better workarounds have since come to light.

> Anything else that could help us review it

2021-08-09 06:00 UTC, rachelandrew commented on files/en-us/web/css/list-style/index.html
> +<p>The most straightforward way to address this is to add an explicit <code>role="list"</code> to the <code><ul></code> element in the markup. This will restore the list semantics without affecting t
```suggestion
<p>The most straightforward way to address this is to add an explicit <code>role="list"</code> to the <code>&lt;ul&gt;</code> element in the markup. This will restore the list semantics without affecting the design.</p>
```

2021-08-09 06:01 UTC, rachelandrew requested changes
I think the unencoded `<ul>` is what is causing the sectioning errors.

2021-08-16 08:32 UTC, rachelandrew commented
@plweil can you fix the conflicts?

2021-08-17 12:00 UTC, sideshowbarker commented
@plweil @rachelandrew The merge conflict here was due to the `files/en-us/web/css/list-style/index.html` file on the `main` branch having been deleted and replaced by the `files/en-us/web/css/list-style/index.md` file (as a result of the mass-migration of all the CSS docs to markdown).

So the fix was to convert the `files/en-us/web/css/list-style/index.html` file on this branch to become the `files/en-us/web/css/list-style/index.md` file.

I went ahead and pushed that change — so it can now be reviewed at https://github.com/mdn/content/pull/7594/files to make sure it got converted OK.

2021-08-21 13:13 UTC, rachelandrew approved these changes

2021-08-21 13:13 UTC, merged