(CSS Layout: Grids) - various typographical fixes/improvements
mdn/content pull request #7600
Opened 2021-08-04 22:18 UTC by ConsciousClay

- Mechanics
- Diction
- Made explicit and added explanation for jargon
- Improved explanation of **fr** units
- Marked up terms for emphasis

2021-08-05 04:03 UTC, rachelandrew requested changes
Please see my comments inline, as some of these changes have introduced technical inaccuracies.

2021-08-05 04:03 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>In addition to creating grids using lengths and percentages, we can use the <code>fr</code> (<em>fraction</em>) unit to flexibly size grid tracks. <a href="https://mozilladevelopers.github.io/play
the fr unit is not defined in the spec as a fraction unit, please refer to the specifications before making edits like this. The prose you have added is also incorrect, as the unit deals with available, not all space.

2021-08-05 04:03 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
The columns and rows are not commonly referred to as tracks, they are defined in the spec as tracks.

2021-08-05 04:03 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>These let you specify the start and end lines at once, separated by a forware slash <code>/</code>.</p>
```suggestion
<p>These let you specify the start and end lines at once, separated by a forward slash <code>/</code>.</p>
```

2021-08-05 18:49 UTC, ConsciousClay commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>In addition to creating grids using lengths and percentages, we can use the <code>fr</code> (<em>fraction</em>) unit to flexibly size grid tracks. <a href="https://mozilladevelopers.github.io/play
I don't fully understand. I checked the specs and then I saw Mozilla's own page on the topic which I linked to. Are you saying that the definition from MDN is wrong? I've reverted to the original.

2021-08-05 18:53 UTC, ConsciousClay commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
Okay, but later in the article the term "_track_" is used instead of rows and columns. It's used without any remark as to its meaning or purpose. There's no notice given to the reader at all as to why the terminology changed. I was just trying to fill that void. If columns and rows aren't commonly referred to as tracks, then tracks shouldn't have ever been substituted as if it's the norm.

2021-08-06 03:23 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
What I'm saying is that track is the actual terminology, not just something people call it. Whereas gutters are not spec terminology (because the gap doesn't really equate to the gutter due to the fact other things can add space between tracks).

2021-08-06 03:26 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>In addition to creating grids using lengths and percentages, we can use the <code>fr</code> (<em>fraction</em>) unit to flexibly size grid tracks. <a href="https://mozilladevelopers.github.io/play
that playground you linked to is incorrect, the spec never refers to the unit as "fraction". It's a flexible length, or `<flex>`.

2021-08-07 18:05 UTC, ConsciousClay commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
Did you want me to make any changes?

2021-08-09 10:32 UTC, rachelandrew commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
yes, in order that you are not conflating spec terminology with a term people use to describe something but that isn't actually how it is described in the spec. In fact, the spec includes details as to why the gap isn't a gutter.

2021-08-10 20:54 UTC, ConsciousClay commented on files/en-us/learn/css/css_layout/grids/index.html
> +<p>A grid will typically have <strong>columns</strong>, <strong>rows</strong>, and gaps between each. The columns and rows are commonly referred to as <strong>tracks</strong>, while the gaps are comm
I reverted the statement.

2021-08-16 08:24 UTC, rachelandrew approved these changes

2021-08-16 08:24 UTC, merged