WebDriver conformance changes for Firefox 91
mdn/content pull request #7648
Opened 2021-08-06 07:20 UTC by juliandescottes

The following PR contains all the user facing changes to Marionette for the Firefox 91 release. Here a [list of all the changes](https://bugzilla.mozilla.org/buglist.cgi?j_top=OR&f1=cf_status_firefox91&o1=equals&resolution=FIXED&o2=equals&query_format=advanced&f2=cf_status_firefox91&v1=fixed&component=Marionette&v2=verified&product=Testing&).

@whimboo can you please cross-check? Thanks.

2021-08-06 10:11 UTC, whimboo requested changes
Some small changes that I would propose. Let me know what you think.

2021-08-06 10:11 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/91/index.html
> +  <li>Fixed a bug which prevented to close prompts opened by popup windows, which could make Marionette hang ({{bug(1721982)}}).</li>
```suggestion
  <li>Fixed a bug, which caused the commands <code>WebDriver:AcceptAlert</code> and <code>WebDriver:DismissAlert</code> to hang for user prompts as opened by a popup window ({{bug(1721982)}}).</li>
```

2021-08-06 10:11 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/91/index.html
> +  <li>Minor performance improvement related to unnecessary log operations ({{bug(1708532)}})</li>
I though a bit more about that entry, and maybe it's not worth mentioning it for the release notes.

2021-08-06 11:26 UTC, juliandescottes commented
Thanks, applied suggestions.

2021-08-06 12:09 UTC, whimboo approved these changes
r=me with the nit fixed.

2021-08-06 12:09 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/91/index.html
> +  <li>Fixed a bug, which caused the commands <code>WebDriver:AcceptAlert</code> and <code>WebDriver:DismissAlert</code> to hang for user prompts as opened by a popup window ({{bug(1721982)}}).</li>
```suggestion
  <li>Fixed a bug, which caused the commands <code>WebDriver:AcceptAlert</code> and <code>WebDriver:DismissAlert</code> to hang for user prompts as opened in a popup window ({{bug(1721982)}}).</li>
```

2021-08-06 12:09 UTC, whimboo commented on files/en-us/mozilla/firefox/releases/91/index.html
> +  <li>Fixed a bug, which caused the commands <code>WebDriver:AcceptAlert</code> and <code>WebDriver:DismissAlert</code> to hang for user prompts as opened by a popup window ({{bug(1721982)}}).</li>
Sorry, I missed that part. It's not that the popup actually opens the user prompt.

2021-08-06 19:23 UTC, whimboo commented
@Rumyra could you please have a look? Thanks.

2021-08-08 19:25 UTC, Rumyra approved these changes

2021-08-08 19:27 UTC, Rumyra commented
This looks great to me - I've approved - can someone confirm the above conversations are resolved - thank you!

Let me know if there's anything else, I'm currently working on a personal branch tidying up the release notes, so I can add anything there 👍

2021-08-09 06:51 UTC, juliandescottes commented
> This looks great to me - I've approved - can someone confirm the above conversations are resolved - thank you!
> 
> Let me know if there's anything else, I'm currently working on a personal branch tidying up the release notes, so I can add anything there 👍

Thanks!

All the initial review comments were folded in the first commit, and the additional nit was automatically added as a new commit. Everything should be resolved.

2021-08-09 17:03 UTC, Rumyra commented
Thanks @juliandescottes 👍

2021-08-09 17:03 UTC, merged