Adds missing TextTrack pages
mdn/content pull request #7664
Opened 2021-08-06 15:24 UTC by rachelandrew

Adds the missing pages to the `TextTrack` WebVTT interface.

Reviewer @jpmedley

2021-08-07 13:16 UTC, AnilSeervi commented on files/en-us/web/api/texttrack/mode/index.html
`seoSummary` class can also be removed from this file.

2021-08-09 15:05 UTC, jpmedley requested changes

2021-08-09 15:05 UTC, jpmedley commented on files/en-us/web/api/texttrack/removecue/index.html
> +  <p><strong>Note:</strong> The {{domxref("TextTrackCue")}} interface is an abstract class used as the basis for other cue types such as {{domxref("VTTCue")}}. Therefore, when removing a cue you will
```suggestion
  <p><strong>Note:</strong> The {{domxref("TextTrackCue")}} interface is an abstract class used as the parent for other cue interfaces such as {{domxref("VTTCue")}}. Therefore, when removing a cue you will be passing in one of the cue types that inherit from <code>TextTrackCue</code>.</p>
```

2021-08-09 15:05 UTC, jpmedley commented on files/en-us/web/api/texttrack/removecue/index.html
> +  <p><strong>Note:</strong> The {{domxref("TextTrackCue")}} interface is an abstract class used as the basis for other cue types such as {{domxref("VTTCue")}}. Therefore, when removing a cue you will
Please copy this rewrite to the interface summary.

2021-08-09 15:05 UTC, jpmedley commented on files/en-us/web/api/texttrack/removecue/index.html
> +<p>In the following example a cue added to a video text track using <code>addCue()</code>, then removed using <code>removeCue</code>.</p>
```suggestion
<p>In the following example a cue is added to a video text track using <code>addCue()</code>, then removed using <code>removeCue</code>.</p>
```

2021-08-10 12:55 UTC, AnilSeervi commented on files/en-us/web/api/texttrack/index.html
> +<p><strong>Note:</strong> The {{domxref("TextTrackCue")}} interface is an abstract class used as the parent for other cue interfaces such as {{domxref("VTTCue")}}. Therefore, when adding or removing
`cue types` can be `cue interfaces`

2021-08-11 15:21 UTC, jpmedley approved these changes

2021-08-11 15:21 UTC, merged