improve grammar
mdn/content pull request #7683
Opened 2021-08-07 11:53 UTC by hv48067

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

2021-08-07 12:01 UTC, teoli2003 requested changes
Thanks, there are a few fixes that are needed.

2021-08-07 12:01 UTC, teoli2003 commented on files/en-us/web/css/css_fonts/opentype_fonts_guide/index.html
> +<p>There are a huge number of possible features. You can see examples of a number of the above, and there are several resources available for finding more of them.</p>
them sounds corrrect to me. Why the _the?

2021-08-08 23:52 UTC, hamishwillee commented on files/en-us/web/css/css_fonts/opentype_fonts_guide/index.html
> +<p>There are a huge number of possible features. You can see examples of a number of the above, and there are several resources available for finding more of them.</p>
Agree, though perhaps "examples **for** a number of them"

2021-08-10 04:59 UTC, hv48067 commented on files/en-us/web/css/css_fonts/opentype_fonts_guide/index.html
> +<p>There are a huge number of possible features. You can see examples of a number of the above, and there are several resources available for finding more of them.</p>
The word <b>them</b> doesn’t seem to fit this context. Consider replacing it with the.

2021-08-10 05:43 UTC, teoli2003 requested changes
If you accept the two suggestions (click the commit button below each of them), we are good to go.

2021-08-10 05:43 UTC, teoli2003 commented on files/en-us/web/css/css_fonts/opentype_fonts_guide/index.html
> +<p>This is sometimes the trickiest thing to work out if you don't have any documentation that came with the fonts (many types of designers and foundries will provide sample pages and CSS just for thi
Please revert to this:
```suggestion
<p>This is sometimes the trickiest thing to work out if you don't have any documentation that came with the fonts (many type designers and foundries will provide sample pages and CSS just for this very reason). But there are some sites that make it easier to figure out. You can visit <a href="https://wakamaifondue.com">wakamaifondue.com</a>, drop your font file on the circle where instructed, and in a few moments you'll have a full report on all the capabilities and features of your font. <a href="https://axis-praxis.org">Axis-praxis.org</a> also offers a similar capability, with the ability to click on the features to turn them on or off in a given text block.</p>
```

2021-08-10 05:43 UTC, teoli2003 commented on files/en-us/web/css/css_fonts/opentype_fonts_guide/index.html
> +<p>There are a huge number of possible features. You can see examples of a number of the above, and there are several resources available for finding more of them.</p>
Sounds grammatically correct to both Hamish and me…
```suggestion
<p>There are a huge number of possible features. You can see examples of a number of them above, and there are several resources available for finding more of them.</p>
```

2021-08-10 06:33 UTC, teoli2003 approved these changes

2021-08-10 06:34 UTC, merged

2021-08-10 06:34 UTC, teoli2003 commented
Thanks