Allow rebase strategy
mdn/content pull request #7689
Opened 2021-08-07 13:29 UTC by Ryuno-Ki

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

As discussed in https://github.com/mdn/content/discussions/6480 rebase should not be forbidden outright any more.
However, a warning is still apt.

> What was wrong/why is this fix needed? (quick summary only)

Looking at actual behaviour, sometimes a PR branch was updated by rebasing main instead of merging it.
If this becomes acceptable behaviour, we should reflect that in our documentation.

> Anything else that could help us review it

I'd like to have the discussion of the general direction in https://github.com/mdn/content/discussions/6480 and use this PR for forging the wording.

2021-08-08 19:22 UTC, Rumyra commented
Thanks so much @Ryuno-Ki 🙏 Rebase is the _one thing_ that everyone likes to make confusing 😆

I've got one nit and will also let @escattone take a quick look 👍

2021-08-08 23:56 UTC, hamishwillee commented on README.md
> +from GitHub leed to nowhere. Your changes are replayed on top of the current
typo: "leed"

2021-08-09 00:19 UTC, hamishwillee commented on README.md
> +main branch at that point in time. Any additional changes should be made as
I much prefer rebasing. As a reviewer it is rare to get lost in the historical rewrite,  and rebase it creates a *much* better story for git archeologists.

Anyway, this is perhaps simpler?

> While merging with the `main` branch using `git pull` is recommended (because it provides a more consistent git history), rebasing your changes using  `git rebase` is also permitted.

2021-08-09 15:21 UTC, Ryuno-Ki commented on README.md
> +from GitHub leed to nowhere. Your changes are replayed on top of the current
That's embarassing :blush:

2021-08-09 15:23 UTC, Ryuno-Ki commented on README.md
> +main branch at that point in time. Any additional changes should be made as
In my experience, the merge strategy insofar, as it does provide an easier mental model.
For `git bisect` it's more challenging, since you will have commits with multiple parents.

My intention is to express, that rebase is „okay if you know what you're doing”.
I also noticed some stripped GPG verifications in my personal experience. That could also go into this PR.

2021-08-09 16:49 UTC, Rumyra requested changes, later dismissed

2021-08-09 23:00 UTC, hamishwillee commented on README.md
> +main branch at that point in time. Any additional changes should be made as
I'm not sure what you've said actually captures "OK if you know what you're doing" because even if you know what you're doing you'll still have the highlighted issue (notifications leading nowhere).  I prefer my text because it captures "rebase is allowed but merge is currently preferred". 

Further, the  "Any additional changes should be made as commits" jarred a bit. Either approach requires changes be made as commit - unless the point is to suggest don't do squash rebase (which is something I often do, and like).

It is completely up to you though - much easier to criticize than come up with text in the first place :-)

2021-08-10 19:51 UTC, Ryuno-Ki commented on README.md
> +from GitHub leed to nowhere. Your changes are replayed on top of the current
I was faster :-)
(Was that the nit you mentioned?)

2021-08-10 19:55 UTC, Ryuno-Ki commented on README.md
> +main branch at that point in time. Any additional changes should be made as
Fair point.
It's quite difficult to me to come up with a good phrasing (in a language that is not my first one) that „sounds good”.
Hence, I'm thankful for all the feedback you provide Hamish.

I will think more about how to put „rebase is allowed but merge is currently preferred” in elegant words.
Meanwhile: would the current state be good to go? Or shall I drop the „Any additional changes should be made as commits” part? (jarred is a word I would need to look up to remember its meaning, but I can understand the sense of it).

Squashing is a whole different subject. I only do it once I'm confident to not have to revert a commit.
But I feel, it would go to deep into git advanced knowledge at this point.

2021-08-10 19:56 UTC, Ryuno-Ki commented
@Rumyra Given https://github.com/mdn/content/pull/7689#issuecomment-894843329 is there any other changes I definitively need to make from your point of view?

2021-08-10 22:24 UTC, hamishwillee approved these changes

2021-08-10 22:24 UTC, merged

2021-08-10 22:26 UTC, hamishwillee commented on README.md
> +main branch at that point in time. Any additional changes should be made as
It is hard to find exactly the right words. I've removed the "Any additional ..." bit and merged. Thank you!