Tidying up
mdn/content pull request #771
Opened 2020-12-30 15:37 UTC by Rumyra

- Removes draft
- Removes events sub heading (not sure why it was there)
- Moves parse method to static method section
- Adds definitions for toSum and type

2020-12-31 13:00 UTC, chrisdavidmills requested changes
I've grabbed this one ;-)

Few comments for your to address. Cheers @Rumyra !

2020-12-31 13:21 UTC, Rumyra commented on files/en-us/web/api/cssnumericvalue/index.html
> +	<dd>Converts the object's value to a {{domxref("CSSMathSum")}} object to values of the specified unit.</dd>
Haha - this is taken from the member page - I'll update both 👍

2020-12-31 13:23 UTC, Rumyra commented on files/en-us/web/api/cssnumericvalue/index.html
> +<h2 id="Static_Methods">Static Methods</h2>
So interestingly Joe has pushed back on titles not being title case - unless I've muddled it up, but not looking at recent docs I've done ☺️ I think I'm going to be changing quite a few headings...

2020-12-31 13:27 UTC, Rumyra commented on files/en-us/web/api/cssnumericvalue/index.html
>  <h2 id="Methods">Methods</h2>
So I decided this as I had seen it somewhere else and it seemed like a quick win whilst we're deciding the _correct_ way. I quite like h2 methods and h3 sub headers for instance and static - it means existing pages need not change. But sorry I'm discussing this in the wrong place 😆

2021-01-02 18:18 UTC, chrisdavidmills approved these changes
Looks good for now; thanks @Rumyra !

2021-01-02 18:18 UTC, merged