some minor improvement
mdn/content pull request #7734
Opened 2021-08-09 05:35 UTC by hv48067

changing wordy words, removing unnecessary wordy words and commas, and using some easy phase

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)
some words are wordy and some are redundant or unnecessary.

> Anything else that could help us review it

2021-08-09 05:47 UTC, teoli2003 requested changes
Almost good to go.

2021-08-09 05:47 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>One of the most common style changes made to lists is a change in the indentation distance—that is, how far the list items are pushed over to the right. This often leads to frustration, because wh
I know it was there before, but there is an unmatched `</span>` at the end of the line. Could you remove it?

2021-08-09 05:47 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p> To understand why this is the case, and more importantly how to avoid the problem altogether, it's necessary to examine the details of list construction.</p>
nit: Leading space to remove.

2021-08-09 05:47 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>As it turns out, nobody seems to have used the first option. The second option was taken by Internet Explorer for Windows and Macintosh, and Opera. The third was adopted by Gecko and by extension
```suggestion
<p>As it turns out, nobody seems to have used the first option. The second option was taken by Internet Explorer, and Opera. The third was adopted by Firefox.</p>
```
Embedded Geckos and IE for Mac are long dead. Let's simplify a bit.

2021-08-09 08:40 UTC, hv48067 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>One of the most common style changes made to lists is a change in the indentation distance—that is, how far the list items are pushed over to the right. This often leads to frustration, because wh
No, I didn't remove it, it wasn't already.

2021-08-09 08:44 UTC, hv48067 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>As it turns out, nobody seems to have used the first option. The second option was taken by Internet Explorer for Windows and Macintosh, and Opera. The third was adopted by Gecko and by extension
Oh, I don't know about thanks.

2021-08-09 08:44 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>One of the most common style changes made to lists is a change in the indentation distance—that is, how far the list items are pushed over to the right. This often leads to frustration, because wh
I know, but can you fix it as we edit this page :-)

2021-08-09 08:49 UTC, sideshowbarker commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>In the end, we can see that none of the browsers mentioned in this article is right or wrong about how they layout lists. They use different default styles, and that's where the problems creep in.
The change to this paragraph should be reverted. *layout* is a noun or adjective. *lay out* is a verb. See https://www.grammar.com/layout_vs._lay_out and other style guides. (And note this is similar to *markup* vs *mark up*.)

2021-08-09 09:21 UTC, teoli2003 commented
Feel free to re-request my review, once you have committed the fixes.

2021-08-09 09:25 UTC, hv48067 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>In the end, we can see that none of the browsers mentioned in this article is right or wrong about how they layout lists. They use different default styles, and that's where the problems creep in.
The layout is a noun that means the way something is arranged.
Lay out is a verb phrase that refers to the act of arranging something.
ok got it, thanks

2021-08-10 05:34 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>One of the most common style changes made to lists is a change in the indentation distance—that is, how far the list items are pushed over to the right. This often leads to frustration, because wh
It is not matched by an opening `<span>`, making the URL invalid. It is a remnant of a removed `<span class="seoSummary>` that we remove.

2021-08-10 05:36 UTC, teoli2003 requested changes
You still need to revert layout -> lay out

2021-08-10 05:36 UTC, teoli2003 commented on files/en-us/web/css/css_lists_and_counters/consistent_list_indentation/index.html
> +<p>In the end, we can see that none of the browsers mentioned in this article is right or wrong about how they layout lists. They use different default styles, and that's where the problems creep in.
You still need to revert this change.

2021-08-10 05:44 UTC, teoli2003 approved these changes

2021-08-10 05:46 UTC, merged

2021-08-10 05:46 UTC, teoli2003 commented
Thanks a lot!

Congratulations upon your first merged commit here!

2021-08-10 05:55 UTC, hv48067 commented
> Thanks a lot!
> 
> Congratulations upon your first merged commit here!

Thank you very much sir for your wonderful guidance and for helping me as a beginner and for patiently correcting my mistake.