COMMAS
mdn/content pull request #7741
Opened 2021-08-09 09:13 UTC by hv48067

Unnecessary comma in the compound object, consider removing it.
you are missing a comma after the introductory phrase <b>In English and Arabic</b>. Consider adding a comma.
you are missing a comma or two with the interrupter <b>however</b> Consider adding the comma(s).

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

2021-08-09 09:21 UTC, sideshowbarker commented
The edits in this PR that add commas are good, but I think the edits that remove commas are not. In all cases, they’re removing discretionary commas — commas that were added at the discretion of the author, for the sake of better readability or avoiding any ambiguity. And to me at least, the paragraphs read better with those commas included, and read worse without them.

2021-08-09 09:31 UTC, rachelandrew commented
@hv48067 can I ask that you give your PRs a descriptive title including some info about the document that you have changed? Otherwise, we have to open each up fully to see what it's about.

2021-08-09 17:57 UTC, ericwbailey commented
@hv48067 Is there a reason commas is all caps in your PR title? It differs from our existing PR titles, but I'm wondering if there's a convention I'm unaware of.

2021-08-10 05:28 UTC, hv48067 commented
> @hv48067 Is there a reason commas is all caps in your PR title? It differs from our existing PR titles, but I'm wondering if there's a convention I'm unaware of.

No, it's just to highlight the issue.

2021-08-10 05:50 UTC, teoli2003 commented
Please don't write in all caps, it is considered screaming, and bad etiquette.

Also try to give a hint of where (that is, in which page/area) the problem is in the title, it helps the team of reviewers to decide to review the bug or not: most of us specialized in specific areas.

I will reformulate this one for you, as an example.

2021-08-10 05:59 UTC, hv48067 commented
> Please don't write in all caps, it is considered screaming, and bad etiquette.
> 
> Also try to give a hint of where (that is, in which page/area) the problem is in the title, it helps the team of reviewers to decide to review the bug or not: most of us specialized in specific areas.
> 
> I will reformulate this one for you, as an example.

ok sir I will mind about it next time.

2021-08-10 06:01 UTC, teoli2003 requested changes
A few commas to reintroduce.

2021-08-10 06:01 UTC, teoli2003 commented on files/en-us/web/css/css_logical_properties/basic_concepts/index.html
> +<p>The block dimension is the other dimension and the direction in which blocks — such as paragraphs — display one after the other. In English and Arabic, these run vertically, whereas in any vertica
```suggestion
<p>The block dimension is the other dimension, and the direction in which blocks — such as paragraphs — display one after the other. In English and Arabic, these run vertically, whereas in any vertical writing mode these run horizontally.</p>
```

2021-08-10 06:10 UTC, teoli2003 approved these changes

2021-08-10 06:11 UTC, merged

2021-08-10 06:11 UTC, teoli2003 commented
Thanks!

2021-08-10 06:21 UTC, hv48067 commented
Thank you very much sir for your guidance.