Fix mistakes from Accessibility_inspector
mdn/content pull request #7759
Opened 2021-08-09 11:27 UTC by Yongjun042

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

 Accessibility_inspector
-some alt text are missing. add more infromation to alt text. Typo error. 

 Accessibility_inspector/Simulation
-equalize image size in table. change some words.
  Usually color blind people can't distinguish colors but they are good at distinguishing specific color.

> Anything else that could help us review it

2021-08-09 23:18 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/index.html
> +<p><img alt="Accessibility tree loadid in new tab JSON viewer" src="accessibility_json.png" style="display: block; margin: 0px auto;"></p>
loaded typo

2021-08-09 23:21 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/index.html
> +<p>An extra context menu option is added, both for the general context menu on the web page when right-clicking a UI feature, and the HTML pane of the page inspector when right-clicking a DOM element
So before this said right-click a UI feature and press CTRL on the keyboard at the same time. Now it says "just right click on UI feature". Can you confirm this is intentional - ie CTRL is not needed?

2021-08-09 23:22 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/simulation/index.html
> +<p>"Color blindness" is a bit of a misnomer, since most people with these disorders can see colors, but have diffrence for the distinctions that people with normal color vision can see; color vision
Please revert this. The new text is incorrect, the original text was correct.

2021-08-09 23:26 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/simulation/index.html
> +   <td><img alt="Colorful image of a cat's face paint, with protanopia simulation" src="colorcat_protanopia.png"></td>
Please revert this, and for the other cases as it is "less correct". This is not an image of a cat's face paint, but of a painted cat face. Either way, the fact it is painted is a bit irrelevant.

2021-08-09 23:27 UTC, hamishwillee requested changes
Thanks for contributing. Good to see alt added to the images, but some changes needed.

2021-08-10 01:02 UTC, Yongjun042 commented on files/en-us/tools/accessibility_inspector/index.html
> +<p>An extra context menu option is added, both for the general context menu on the web page when right-clicking a UI feature, and the HTML pane of the page inspector when right-clicking a DOM element
this action is for showing context menu. I ctrl-clicked web page but noting happens except left-ctrl-click make link open in new tab.

2021-08-10 01:21 UTC, Yongjun042 commented on files/en-us/tools/accessibility_inspector/simulation/index.html
> +<p>"Color blindness" is a bit of a misnomer, since most people with these disorders can see colors, but have diffrence for the distinctions that people with normal color vision can see; color vision
revert simulation/index.html file.

2021-08-11 11:00 UTC, Yongjun042 commented on files/en-us/tools/accessibility_inspector/simulation/index.html
> +<p>"Color blindness" is a bit of a misnomer, since most people with these disorders can see colors, but have diffrence for the distinctions that people with normal color vision can see; color vision
> 
> 
> Please revert this. The new text is incorrect, the original text was correct.

revert simulation/index.html file.

2021-08-13 01:06 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/index.html
> +<p><img alt="Accessibility tree loadid in new tab JSON viewer" src="accessibility_json.png" style="display: block; margin: 0px auto;"></p>
See this ^^^. "tree loadid" should be "tree loaded"

2021-08-13 01:07 UTC, hamishwillee commented on files/en-us/tools/accessibility_inspector/index.html
> +<p>An extra context menu option is added, both for the general context menu on the web page when right-clicking a UI feature, and the HTML pane of the page inspector when right-clicking a DOM element
Thanks!

2021-08-13 12:28 UTC, Yongjun042 commented on files/en-us/tools/accessibility_inspector/index.html
> +<p><img alt="Accessibility tree loadid in new tab JSON viewer" src="accessibility_json.png" style="display: block; margin: 0px auto;"></p>
> 
> 
> See this ^^^. "tree loadid" should be "tree loaded"

my bad

2021-08-16 00:30 UTC, hamishwillee approved these changes
Thanks very much for these fixes!

2021-08-16 00:30 UTC, merged