Update WebXR reference pages for markdown
mdn/content pull request #7822
Opened 2021-08-11 13:16 UTC by Elchi3

Mostly removal of "summary" and "seo-summary" classes but also some table fixes and fixing notecard divs.

2021-08-11 15:22 UTC, teoli2003 requested changes
2 differences with I did in HTTP:
- I ditch `class="standard-table"'
- I keep `class="properties"`

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrreferencespace/reset_event/index.html
> +<table>
In HTTP and in CSS we kept the table with class `properties` as they can't be converted to md anyway (no header row). In CSS they are added by a macro, In HTTP on the page.

In API, I think this will concern the events reference pages only.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/inputsourceschange_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/select_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/selectend_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/selectstart_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/squeeze_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/squeezeend_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/squeezestart_event/index.html
> +<table>
To keep.

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsession/visibilitychange_event/index.html
> +<table>
To keep

2021-08-11 15:22 UTC, teoli2003 commented on files/en-us/web/api/xrsystem/devicechange_event/index.html
> +<table>
To keep

2021-08-11 18:52 UTC, teoli2003 commented
Reference for `standard-table`: https://github.com/mdn/mdn-minimalist/pull/681

There is a discussion in it for `properties` too. My plan is to keep these tables in HTTP. Given that these tables have a clear structure, and are used in precise contexts (Events for Web/API), we could easily read them to change them in the future.

cc/ @wbamberg here.

2021-08-12 06:49 UTC, Elchi3 commented
Updated to remove standard-table and to keep properties table for now. It makes sense.

2021-08-12 06:56 UTC, teoli2003 approved these changes

2021-08-12 06:56 UTC, merged