Reframed Sentences
mdn/content pull request #7842
Opened 2021-08-12 05:40 UTC by NegiAkash890

> Issue number that this PR fixes (if any)

Fixes #5761

> What was wrong/why is this fix needed? (quick summary only)

Sentences were reframed .

2021-08-12 12:30 UTC, Rumyra requested changes

2021-08-12 12:30 UTC, Rumyra commented on files/en-us/glossary/property/javascript/index.html
> +<p>A <strong>JavaScript property</strong> is a part of an object, that associates a key and a value.</p>
```suggestion
<p>A <strong>JavaScript property</strong> is a characteristic of an object, often describing attributes associated with a data structure.</p>
```

Whilst I understand why you made this change, I think the original is easier understood. This phrasing is to blunt and will confuse readers 👍

2021-08-12 16:26 UTC, NegiAkash890 commented on files/en-us/glossary/property/javascript/index.html
> +<p>A <strong>JavaScript property</strong> is a part of an object, that associates a key and a value.</p>
Hi, @Rumyra I picked up the `property` definition from here : 

https://262.ecma-international.org/6.0/#sec-property

If that sounds blunt then I will remove it for sure

2021-08-16 12:44 UTC, Rumyra commented on files/en-us/glossary/property/javascript/index.html
> +<p>A <strong>JavaScript property</strong> is a part of an object, that associates a key and a value.</p>
:) yes I see - I think the original here should be kept, as we try to translate specs so they are better understood by developers - thanks!

2021-08-18 17:06 UTC, jpmedley commented on files/en-us/glossary/property/javascript/index.html
> +<p>A <strong>JavaScript property</strong> is a part of an object, that associates a key and a value.</p>
For what it's worth, I'd also point out that JS properties are just as likely to be indicators of object state as they are to hold data.

2021-08-23 14:24 UTC, Rumyra approved these changes

2021-08-23 14:25 UTC, merged

2021-08-23 14:25 UTC, Rumyra commented
Thanks @NegiAkash890