Fixed the Ball prototype method
mdn/content pull request #785
Opened 2020-12-31 00:51 UTC by maruthimohan

Fixed the documentation related to the section: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features#Creating_our_new_objects

Fixes #754

2020-12-31 12:27 UTC, avivmu reviewed
Looks good, a few comments concerned with cosmetics

2020-12-31 12:27 UTC, avivmu commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +  for (let j = 0; j &lt; balls.length; j++) {
is the formatting intentionally off?

2020-12-31 12:27 UTC, avivmu commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +      const distance = Math.sqrt(dx * dx + dy * dy);
You can use [Math.hypot](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot):
 `Math.hypot(dx, dy))`

2020-12-31 12:27 UTC, avivmu commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +		The Ball prototype's <code>collisionDetect()</code> method needs a small update. As you would read below, the <code>EvilCircle</code> would start eating the bouncing balls by setting the <code>exis
> only needs to be considered only
duplicate "only"
Also, this line is quite long, should we split it?

2021-01-01 06:49 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +      const distance = Math.sqrt(dx * dx + dy * dy);
Hey @avivmu, thanks for the suggestion. Since it is a continuing tutorial from the previous chapter, I did not want to modify anything except the small code addition ` && balls[j].exists` in the `if` expression.

2021-01-01 06:51 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +  for (let j = 0; j &lt; balls.length; j++) {
hey @avivmu, yes, for the `<pre>` tag, it seems to consider the indentation related spacing while rendering the content inside it. So I had to adjust its actual formatting to make it look proper on the page.

2021-01-01 06:51 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +		The Ball prototype's <code>collisionDetect()</code> method needs a small update. As you would read below, the <code>EvilCircle</code> would start eating the bouncing balls by setting the <code>exis
thanks for catching it, I will fix it and rewrite the sentence to make it easier to read.

2021-01-01 20:49 UTC, Ryuno-Ki commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +  for (let j = 0; j &lt; balls.length; j++) {
Alternative would be to start a new line directly after `<pre class="brush: js">`. But that will yield an empty line in the codeblock …

2021-01-01 20:56 UTC, sideshowbarker requested changes
This looks really great modulo a couple of suggestions for refinements.

2021-01-01 20:56 UTC, sideshowbarker commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +    As discussed above, the only addition is to check if the ball exists (i.e. <code>balls[j].exists</code>) in the <code>if</code> conditional.
```suggestion
    As discussed above, the only addition is to check if the ball exists — by using <code>balls[j].exists</code> in the <code>if</code> conditional.
```

2021-01-01 20:56 UTC, sideshowbarker commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +		The Ball prototype's <code>collisionDetect()</code> method needs a small update. As you would read below, the <code>EvilCircle</code> would start eating the bouncing balls by setting the <code>exis
```suggestion
		The <code>Ball</code> prototype's <code>collisionDetect()</code> method needs a small update. If the code were kept as-is, the <code>EvilCircle</code> would start eating the bouncing balls by setting the <code>exists</code> property to <code>false</code>. And that would reduce the number of balls involved in collision detection. A ball needs to be considered for collision detection only if the <code>exists</code> property is <code>true</code>. So, replace the existing <code>collisionDetect()</code> code with the following code:
```

2021-01-01 22:52 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +    As discussed above, the only addition is to check if the ball exists (i.e. <code>balls[j].exists</code>) in the <code>if</code> conditional.
@sideshowbarker thanks for the suggestion, included in the latest commit.

2021-01-01 22:53 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +		The Ball prototype's <code>collisionDetect()</code> method needs a small update. As you would read below, the <code>EvilCircle</code> would start eating the bouncing balls by setting the <code>exis
@sideshowbarker the updated version looks better. Included this in the latest commit.

2021-01-01 22:56 UTC, maruthimohan commented on files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.html
> +  for (let j = 0; j &lt; balls.length; j++) {
@Ryuno-Ki good one! surprisingly, it did not add an extra line.

2021-01-01 22:58 UTC, sideshowbarker approved these changes

2021-01-01 23:01 UTC, sideshowbarker commented
@maruthimohan I’ve approved this but we’ll need somebody from the @mdn/yari-content-learn team (which in practice means @chrisdavidmills) to also approve and merge it.

2021-01-01 23:19 UTC, maruthimohan commented
>@maruthimohan I’ve approved this but we’ll need somebody from the @mdn/yari-content-learn team (which in practice means @chrisdavidmills) to also approve and merge it.

@sideshowbarker Got it and thank you for spending time reviewing this PR. 

I wish you a happy new year!

2021-01-02 00:02 UTC, sideshowbarker commented
> @sideshowbarker Got it and thank you for spending time reviewing this PR.

Thank you for your work on spotting problems in the existing docs and coming up with good fixes

2021-01-02 18:23 UTC, chrisdavidmills approved these changes
LGTM!

2021-01-02 18:23 UTC, merged