Updated example
mdn/content pull request #7874
Opened 2021-08-13 06:19 UTC by NegiAkash890

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #7840 

> What was wrong/why is this fix needed? (quick summary only)

Example update

2021-08-13 07:08 UTC, teoli2003 commented
(I asked the creator of the issue to review this)

2021-08-15 16:11 UTC, vlwkaos commented on files/en-us/web/javascript/reference/statements/class/index.md
> +    this.type = '4-wheeler';
In the previous example, as far as I know, property `name` was used to denote `type` or className, not to add a functionality or a property to a derived class. In this example `type` is somewhat ambiguous to be used as Car's property because it looks like it serves as an identifier like `name` in my opinion. 

I think the example suggested in issue #7840 better represents OOP since it shows that `FilledRectangle`, as a derived class of Rectangle, has an added property `color` that is not generic. Correct me if I am wrong.

2021-08-30 07:20 UTC, TrangOul approved these changes

2021-10-20 01:49 UTC, himanshugarg requested changes
@NegiAkash890 thanks for the PR. I have made the changes requested in the review. Could you please take a look and accept if they look good.

2021-11-03 13:51 UTC, Elchi3 commented
@NegiAkash890 are you planning to come back to this PR?

2021-11-22 08:44 UTC, Elchi3 commented
Looks like https://github.com/mdn/content/pull/10649 addressed this now.

2021-11-22 08:44 UTC, closed without merging