Adds CSSFontFaceRule
mdn/content pull request #795
Opened 2020-12-31 07:21 UTC by rachelandrew

Working on #344 
Fixes: #228 

This PR adds the missing documentation for CSSFontFaceRule and the CSSFontFaceRule.style property. BCD already exists.

https://drafts.csswg.org/css-fonts-4/#om-fontface

Reviewer: @jpmedley

2021-01-05 22:34 UTC, jpmedley requested changes

2021-01-05 22:34 UTC, jpmedley commented on files/en-us/web/api/cssfontfacerule/index.html
> +<p>The <strong><code>CSSFontFaceRule</code></strong> interface represents an {{cssxref("@font-face")}} <a href="/en-US/docs/Web/CSS/At-rule">at-rule</a>. It implements the {{domxref("CSSRule")}} inte
I just got why there's two links here. (Head slap. "D'oh") Shouldn't the second link be `{{domxref('at-rule')}}?

It "inherits from", not implements the interface. Also needs `{{InheritanceDiagram}}`. 

(I've said this elsewhere, but I don't know in what order you will be reading these.)

2021-01-05 22:34 UTC, jpmedley commented on files/en-us/web/api/cssfontfacerule/style/index.html
> +<p>This example uses the CSS found as an example on the {{cssxref("@font-face")}} page. The first {{domxref("CSSRule")}} returned will be a <code>CSSFontFaceRule</code>. The <code>style</code> proper
It looks like you're duplicating the CSS from @font-face. Is the first statement really needed?

2021-01-06 08:28 UTC, rachelandrew commented on files/en-us/web/api/cssfontfacerule/style/index.html
> +<p>This example uses the CSS found as an example on the {{cssxref("@font-face")}} page. The first {{domxref("CSSRule")}} returned will be a <code>CSSFontFaceRule</code>. The <code>style</code> proper
Not sure I understand, I was just linking to where that had come from so folk could see the connection. I don't need to if you don't want me to.

2021-01-08 15:50 UTC, jpmedley requested changes

2021-01-08 15:50 UTC, jpmedley commented on files/en-us/web/api/cssfontfacerule/style/index.html
> +<p>This example uses the CSS found as an example on the {{cssxref("@font-face")}} page. The first {{domxref("CSSRule")}} returned will be a <code>CSSFontFaceRule</code>. The <code>style</code> proper
If the CSS is identical, then the value of the connection isn't clear to me. How does knowing these are connected help me understand `CSSFontFaceRule`?

2021-01-08 16:35 UTC, rachelandrew commented on files/en-us/web/api/cssfontfacerule/style/index.html
> +<p>This example uses the CSS found as an example on the {{cssxref("@font-face")}} page. The first {{domxref("CSSRule")}} returned will be a <code>CSSFontFaceRule</code>. The <code>style</code> proper
Only in that it gives some context, if someone wondered what that CSS was doing they know where to go have a look (as it is explained on the CSS property page). That said if you don't want references like that, it's not exactly a hill I'm going to die on so I can remove if you prefer.

2021-01-13 15:48 UTC, jpmedley approved these changes

2021-01-13 15:48 UTC, merged