CSS page templates - convert to markdown
mdn/content pull request #8000
Opened 2021-08-17 07:17 UTC by hamishwillee

Since we're now working in markdownland for CSS. @rachelandrew can you sanity check please - it is "mostly" what was there previously, modified to the newish format I used on API ref and HTTP headers, then further migrated to markdown.

It should be right, unless the HTML format was wildly wrong.

Don't squash!

2021-08-20 15:57 UTC, teoli2003 requested changes
One small change.

2021-08-20 15:57 UTC, teoli2003 commented on files/en-us/mdn/structures/page_types/css_property_page_template/index.md
> +```js
```suggestion
```css
```

2021-08-23 00:39 UTC, hamishwillee commented on files/en-us/mdn/structures/page_types/css_property_page_template/index.md
> +```js
Thanks!

2021-08-23 06:00 UTC, teoli2003 approved these changes

2021-08-23 06:00 UTC, merged

2021-08-23 06:00 UTC, teoli2003 commented
Let's land this.