examples for CSSPropertyRule
mdn/content pull request #801
Opened 2020-12-31 11:35 UTC by rachelandrew

Adding examples and a few tweaks based on changes requested to my other CSSRule PRs.

2021-01-08 17:00 UTC, jpmedley requested changes

2021-01-08 17:00 UTC, jpmedley commented on files/en-us/web/api/csspropertyrule/syntax/index.html
> +<div>{{APIRef("CSS Properties and Values API")}}{{SeeCompatTable}}</div>
```suggestion
<div>{{APIRef("CSS Properties and Values API")}}</div>
```

2021-01-08 17:23 UTC, rachelandrew commented on files/en-us/web/api/csspropertyrule/index.html
> +<div>{{APIRef("CSS Properties and Values API")}}{{SeeCompatTable}}</div>
Do we want to do that? This one isn't the same as the others. It doesn't have implementation in Firefox or Safari, just the Chromium browsers. It's a Houdini API https://drafts.css-houdini.org/css-properties-values-api-1/#dom-csspropertyrule

And I wasn't sure if this was one Ruth had demos for so I had left the draft in place. 

The other CSSRule interfaces have better interop and have examples so they don't have the macros.

2021-01-13 16:37 UTC, jpmedley requested changes

2021-01-13 16:37 UTC, jpmedley commented on files/en-us/web/api/csspropertyrule/index.html
> +<div>{{APIRef("CSS Properties and Values API")}}{{SeeCompatTable}}</div>
I confirmed it with Chris. Please remove this.

2021-01-15 02:21 UTC, jpmedley approved these changes

2021-01-15 02:21 UTC, merged