adds BluetoothUUID
mdn/content pull request #8018
Opened 2021-08-17 16:00 UTC by rachelandrew

Adding the BluetoothUUID interface in Markdown.

Reviewer @jpmedley

2021-08-17 16:07 UTC, teoli2003 submitted a review, later dismissed

2021-08-17 16:07 UTC, teoli2003 commented on files/en-us/web/api/bluetoothuuid/canonicaluuid/index.md
> +The **`canonicalUUID`**  property of the {{domxref("BluetoothUUID")}} interface returns the 128-bit UUID when passed a 16- or 32-bit UUID alias.
It is a method, not a property.

2021-08-17 16:10 UTC, teoli2003 commented
Before merging this, it would be better to switch the whole Bluetooth API to Markdown. I'm not sure we want to have too much of a mix of md and html files in the same API.

2021-08-17 18:45 UTC, jpmedley requested changes

2021-08-17 18:45 UTC, jpmedley commented on files/en-us/web/api/bluetoothuuid/getcharacteristic/index.md
> +The **`getCharacteristic()`**  method of the {{domxref("BluetoothUUID")}} interface returns a UUID representing a registered characteristic when passed a name or the 16- or 32-bit UUID alias.
I'm not asking for a lot of detail. I'm thinking in terms of simple handles to help someone new to Bluetooth research on their own.

2021-08-19 12:53 UTC, rachelandrew commented on files/en-us/web/api/bluetoothuuid/canonicaluuid/index.md
> +The **`canonicalUUID`**  property of the {{domxref("BluetoothUUID")}} interface returns the 128-bit UUID when passed a 16- or 32-bit UUID alias.
> It is a method, not a property.

ah yes I missed this one - the tool made all the methods properties :D

2021-08-19 19:21 UTC, jpmedley approved these changes

2021-08-20 07:21 UTC, rachelandrew commented
> Before merging this, it would be better to switch the whole Bluetooth API to Markdown. I'm not sure we want to have too much of a mix of md and html files in the same API.

if we can get the conversion script to work for me, I'll happily do it. At the moment I'd have to do the conversion by hand.

2021-09-16 07:10 UTC, rachelandrew commented
@teoli2003 this is blocked on you - now the md conversion is done, I'd like to merge it

2021-09-16 15:41 UTC, jpmedley approved these changes

2021-09-20 16:11 UTC, merged