Adds CustomStateSet
mdn/content pull request #8093
Opened 2021-08-19 12:13 UTC by rachelandrew

Adds the `CustomStateSet` interface in Markdown. As this is an addition to `ElementInternals` this also adds the property page and link to that Interface in HTML.

Reviewer @jpmedley

2021-08-19 19:19 UTC, jpmedley requested changes
Please see the comments I made on line 19 of the interface page. I don't believe your assessment of what this interface is is correct. I'd like to resolve this before I finish the review.

2021-08-19 19:19 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
I do not believe this is literally an instance of Set. It's `add()` method [pushes to a variable called `list_`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/custom/custom_state_set.cc;l=80). I suspect that `list_` is an instance of the [list structure in the C++ Standard Template Library](https://www.geeksforgeeks.org/list-cpp-stl/). I can't the variable's initialization.

2021-08-19 19:19 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
[I found it](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/custom/custom_state_set.h;l=53). It's a [vector](https://www.geeksforgeeks.org/vector-in-cpp-stl/). Can you please explain this without reference to `Set`?

2021-08-19 19:19 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
I know the spec language makes it sound like this is a Set. I think it merely means that the same algorithms should be used.

2021-08-19 19:19 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +States are stored as a `<dashed-ident>` as this format can then be accessed from CSS using the _custom state pseudo-class_.
Is that [this](https://developer.mozilla.org/en-US/docs/Web/CSS/:state)? Maybe add a link.

2021-08-19 19:26 UTC, rachelandrew commented on files/en-us/web/api/customstateset/index.md
> +States are stored as a `<dashed-ident>` as this format can then be accessed from CSS using the _custom state pseudo-class_.
I think that page is incorrect, or maybe an old version looked like that. I'll check tomorrow and remove it if I'm right. The current spec has the names stored in the set used directly which is why they are a dashed-ident.

2021-08-19 19:30 UTC, rachelandrew commented on files/en-us/web/api/customstateset/index.md
> +States are stored as a `<dashed-ident>` as this format can then be accessed from CSS using the _custom state pseudo-class_.
I spotted the discussion, I'll remove that page you found as it's incorrect https://github.com/WICG/custom-state-pseudo-class/issues/6

2021-08-19 19:36 UTC, rachelandrew commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
It describes it as `setlike`, I have one in another interface described as `maplike`. Sets and maps they may not be but in BCD we also have a whole bunch of methods and so on which can be used due to their set- or maplike-ness. 

So I don't know how to deal with this, other than to refer to set or map? Should we then create pages for each of these methods? If we don't, and also don't refer to set, how is someone supposed to know that's how they work with this?

You can see the BCD table in the preview: https://pr8093.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/CustomStateSet

2021-08-20 18:32 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
MDN Helper should have built these pages for you and you would have done very little to them before submitting. Let me look into this.

2021-09-01 06:01 UTC, rachelandrew commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
@jpmedley did you get anywhere with this? I've seen other instances of these setlike and maplike interfaces so would be good to know how to deal with them, as the specs seem to assume they then just gain set and map functionality.

2021-09-01 15:49 UTC, jpmedley commented on files/en-us/web/api/customstateset/index.md
> +A instance of `CustomStateList` is returned by {{domxref("ElementInternals.states")}}. The `CustomStateList` object is a {{jsxref("Set")}}, and therefore the properties and methods available on a `Se
Things got in my way. I'll look at it today.

2021-09-02 13:59 UTC, jpmedley requested changes

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/clear/index.md
> +The **`clear`** method of the {{domxref("CustomStateSet")}} interface removes all elements from the `CustomStateSet` object.
```suggestion
The **`clear()`** method of the {{domxref("CustomStateSet")}} interface removes all elements from the `CustomStateSet` object.
```

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/delete/index.md
> +The **`delete`** method of the {{domxref("CustomStateSet")}} interface deletes a single value from the `CustomStateSet`.
```suggestion
The **`delete()`** method of the {{domxref("CustomStateSet")}} interface deletes a single value from the `CustomStateSet`.
```

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/entries/index.md
> +The **`entries`** method of the {{domxref("CustomStateSet")}} interface returns a new {{jsxref("Iterator")}} object, containing an array of `[value,value]` for each element in the `CustomStateSet`.
`[value,value]`? I don't understand.

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/foreach/index.md
> +The **`forEach`** method of the {{domxref("CustomStateSet")}} interface executes a provided function for each value in the `CustomStateSet` object.
```suggestion
The **`forEach()`** method of the {{domxref("CustomStateSet")}} interface executes a provided function for each value in the `CustomStateSet` object.
```

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/has/index.md
> +The **`has`** method of the {{domxref("CustomStateSet")}} interface returns a {{jsxref("Boolean")}} asserting whether an element is present with the given value.
```suggestion
The **`has()`** method of the {{domxref("CustomStateSet")}} interface returns a {{jsxref("Boolean")}} asserting whether an element is present with the given value.
```

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/keys/index.md
> +The **`keys`** method of the {{domxref("CustomStateSet")}} interface is an alias for {{domxref("CustomStateSet.values")}}.
```suggestion
The **`keys()`** method of the {{domxref("CustomStateSet")}} interface is an alias for {{domxref("CustomStateSet.values")}}.
```

2021-09-02 13:59 UTC, jpmedley commented on files/en-us/web/api/customstateset/values/index.md
> +The **`values`** method of the {{domxref("CustomStateSet")}} interface returns a new iterator object that yields the values for each element in the `CustomStateSet` object in insertion order.
```suggestion
The **`values()`** method of the {{domxref("CustomStateSet")}} interface returns a new iterator object that yields the values for each element in the `CustomStateSet` object in insertion order.
```

2021-09-09 13:32 UTC, rachelandrew commented on files/en-us/web/api/customstateset/entries/index.md
> +The **`entries`** method of the {{domxref("CustomStateSet")}} interface returns a new {{jsxref("Iterator")}} object, containing an array of `[value,value]` for each element in the `CustomStateSet`.
Exactly what it says really, it's a set so there isn't a key, just the same as regular set entries https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/entries

2021-09-09 14:13 UTC, jpmedley approved these changes

2021-09-09 14:13 UTC, merged