Bug 1669566 add cookie store id to browser.downloads
mdn/content pull request #8106
Opened 2021-08-19 17:58 UTC by rebloor

Changes adding cookieStoreId to browser.download.download, downloads.DownloadQuery (browser.download.search), and downloads.DownloadItem (browser.download.erase). This provides documentation for  [Bug 1669566](https://bugzilla.mozilla.org/show_bug.cgi?id=1669566).

Corresponding changes to browser-compat-data to be completed shortly.

2021-08-24 04:08 UTC, hamishwillee commented on files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.html
> +  <dd>The cookie store ID of the contextual identity the download is associated with. If omitted, the default cookie store is used. Use requires the "cookies" <a href="/en-US/docs/Mozilla/Add-ons/Web
Is "contextual identity" enough for someone who is somewhat familiar with web extensions to know what you mean?

2021-08-24 04:17 UTC, hamishwillee commented
The original bug referred to the cookieStoreId applying to `erase` as well. I presume that ended up being documented in the DownloadQuery?

2021-08-24 16:18 UTC, rebloor commented
> The original bug referred to the cookieStoreId applying to `erase` as well. I presume that ended up being documented in the DownloadQuery?

Yes,  because `browser.download.erase` and `browser.download.search` both use `downloads.DownloadQuery` the "addition" was achieved by adding `cookieStoreId` to the type.  a similar reason to why `cookieStoreId` was added to `downloads.DownloadItem`.

2021-08-24 17:38 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.html
> +  <dd>The cookie store ID of the contextual identity the download is associated with. If omitted, the default cookie store is used. Use requires the "cookies" <a href="/en-US/docs/Mozilla/Add-ons/Web
I've added a cross-reference link to the article on how to work with contextual identities, which should help anyone who's unfamiliar with this. I also noticed that there isn't any reference to contextual identities in the details about the cookies API and have opened a [new issue about this](https://github.com/mdn/content/issues/8267).

I've not been able to find any information specifically relating to how cookies are used with downloads. My assumption is that the behavior is identical to that for web pages e.g. when the download occurs the website may create or read cookies. Similarly, the extension may create or read cookies to store its own information about the download. @Rob--W you commented on the original bug, is there anything we need to add about cookie use/behavior here?

I have to admit I find
> "If the specified url uses the HTTP or HTTPS protocol, then the request will include all cookies currently set for its hostname."
a little ambiguous.  I assume this means that any cookies set for the hostname could be updated by the download host as part of the download. @Rob--W could you help clarify?

2021-08-30 23:30 UTC, hamishwillee requested changes
This is good, but I think this query is still open: https://github.com/mdn/content/pull/8106/files#discussion_r695064608

Specifically, up the top it says

> If the specified url uses the HTTP or HTTPS protocol, then the request will include all cookies currently set for its hostname.

And in the `cookieStoreId` it says

> If omitted, the default cookie store is used.". 

My assumption is that the top point is the "default", but if you use the `cookieStoreId` then you get a different set. However it might be that you get the `cookieStoreId` as well. I think both places should be explicit - define the default set and up the top note that the specified URL might be overridden.

But really up to Rob to confirm

2021-08-30 23:32 UTC, hamishwillee commented on files/en-us/mozilla/firefox/releases/92/index.html
> +  <li>Support for <code>cookieStoreId</code> is added to {{WebExtAPIRef('downloads.download')}}, {{WebExtAPIRef('downloads.DownloadQuery')}}, and {{WebExtAPIRef('downloads.DownloadItem')}}. The addit
This is strictly accurate. FWIW I did find the text "The addition to the two types provides support in" a little hard to parse, because it wasn't immediately obvious (to me) that the preceding sentence was one method and two types. Probably not worth "fixing".

2021-08-31 17:30 UTC, rebloor commented on files/en-us/mozilla/firefox/releases/92/index.html
> +  <li>Support for <code>cookieStoreId</code> is added to {{WebExtAPIRef('downloads.download')}}, {{WebExtAPIRef('downloads.DownloadQuery')}}, and {{WebExtAPIRef('downloads.DownloadItem')}}. The addit
Methods all start with a lowercase letter, types with an uppercase letter, properties are either block capitals or start with a lowercase letter, and events prefixed with "on".  If we need changes for the other outstanding point, I'll update.

2021-08-31 17:41 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/api/downloads/download/index.html
> +  <dd>The cookie store ID of the contextual identity the download is associated with. If omitted, the default cookie store is used. Use requires the "cookies" <a href="/en-US/docs/Mozilla/Add-ons/Web
> I've not been able to find any information specifically relating to how cookies are used with downloads. My assumption is that the behavior is identical to that for web pages e.g. when the download occurs the website may create or read cookies. 

It is indeed:
- If the `incognito` option is used, private browsing cookies are used.
- If the `cookieStoreId` option is used, the cookie store described by this parameter is used.
- If neither is given, the default cookies are used (i.e. from the normal browsing session).


> Similarly, the extension may create or read cookies to store its own information about the download. @Rob--W you commented on the original bug, is there anything we need to add about cookie use/behavior here?

Although the extension offers a `headers` option, the option does not allow custom cookies to be set. Only existing cookies are passed with the request (and any cookies received from the server will be saved if any).


> I have to admit I find
> 
> > "If the specified url uses the HTTP or HTTPS protocol, then the request will include all cookies currently set for its hostname."
> 
> a little ambiguous. I assume this means that any cookies set for the hostname could be updated by the download host as part of the download. @Rob--W could you help clarify?

The line here is a technically not incorrect description of how cookies are being sent with requests, but it's very confusing. Cookies are indeed derived from the host name (but also other components such as scheme (secure flag), path, and so on).

Given the confusion here, I think that it's worthwhile to clarify this (e.g. by being less vague and including what I described above if needed).

2021-08-31 18:05 UTC, Rob--W requested changes
`cookieStoreId` is not only used with contextual identities ("container tabs" is the more common term), but it can also be used to select the private browsing mode or the normal browsing context. Limiting the documentation to just the "contextual identities" feature is not accurate.

I think that the best way to resolve this is to add a new article that describes the `cookieStoreId` concept (https://github.com/mdn/content/issues/8267) and link to that from here.

2021-08-31 18:05 UTC, Rob--W commented on files/en-us/mozilla/firefox/releases/92/index.html
> +  <li>Support for <code>cookieStoreId</code> is added to {{WebExtAPIRef('downloads.download')}}, {{WebExtAPIRef('downloads.DownloadQuery')}}, and {{WebExtAPIRef('downloads.DownloadItem')}}. The addit
Use `WebExtensions`, not `Web extensions`.

The emphasis on "extensions using contextual identities" is somewhat unfortunate. It seems to suggest that the feature is only available to extensions that "use" contextual identities (there is a `contextualIdentities` API and permission). "use" could suggest two things: management of identities, or operating a container-aware extension. The current wording and link skews more towards the former, while the feature is intended to allow extensions to be more container-aware.

Could you rephrase it, so that it sounds more like `Extensions can now associate downloads with specific cookie stores, such as container tabs`?

2021-09-01 08:35 UTC, hamishwillee commented on files/en-us/mozilla/firefox/releases/92/index.html
> +  <li>Support for <code>cookieStoreId</code> is added to {{WebExtAPIRef('downloads.download')}}, {{WebExtAPIRef('downloads.DownloadQuery')}}, and {{WebExtAPIRef('downloads.DownloadItem')}}. The addit
And that perhaps confirms https://github.com/mdn/content/pull/8106#pullrequestreview-742151844 - the default is the cookies from the host, but you can use the ones associated with specific cookie stores. Near the top it should say that.

2021-09-01 21:12 UTC, Rob--W approved these changes
The current version of the patch doesn't address the top-level comment that I had at https://github.com/mdn/content/pull/8106#pullrequestreview-743045401, i.e. that `cookieStoreId` is not just limited to containers. In the absence of better documentation, I'm fine with merging this PR as is, but when an article for `cookieStoreId` is added (in #8267), then the `cookieStoreId` property descriptions introduced by this PR should be updated to link to that new article instead.

2021-09-02 16:24 UTC, rebloor commented
@hamishwillee Do the changes resolve your change request?

2021-09-02 23:22 UTC, hamishwillee approved these changes
@Rob--W Yes, the bit I asked to be changed has been changed and makes it clear that the  cookies depend on more than just the protocol. 

> If the URL uses the HTTP or HTTPS protocol, the request includes all the relevant cookies, that is, those cookies set for the URL's hostname, secure flag, path, and so on. The default cookies, the cookies from the normal browsing session, are used unless:

The only reason I slightly question it is that it defines "The default cookies" as "the cookies from the normal browsing session" - and I immediately wondered how that differed from " those cookies set for the URL's hostname, secure flag, path, and so on."

I suspect someone more expert than me will get the distinction so no change required.

2021-09-03 14:43 UTC, Rumyra commented
Thanks everyone! Going to merge 👍

2021-09-03 14:43 UTC, merged