Fixed small grammatical error on the Clipping and Masking page
mdn/content pull request #8148
Opened 2021-08-20 20:43 UTC by Astrono2

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'
N/A

> What was wrong/why is this fix needed? (quick summary only)
"It is therefore little surprise, that (...)" is not grammatically correct. I figured it's meant to say "(...) a little surprising, that (...)".  

> Anything else that could help us review it
It's beyond me to try to interpret the intended meaning besides a small grammatical error, but it seems to me that it's not surprising for "One of the most powerful tools in a web developer's toolbox" to be put into SVG. This PR makes it grammatically correct, but someone might want to check if the sentence itself makes sense.

2021-08-20 20:50 UTC, teoli2003 requested changes

2021-08-20 20:50 UTC, teoli2003 commented on files/en-us/web/svg/tutorial/clipping_and_masking/index.html
> +<p>One of the most powerful tools in a web developer's toolbox is <code>display: none</code>. It is therefore a little surprising, that it was decided to take this CSS property into SVG as well, toge
The original sentence is correct and doesn't mean the same as your fix. It means "It was not surprising". 

I propose to rephrase it like this, which simplifies the phrase.

```suggestion
<p>One of the most powerful tools in a web developer's toolbox is <code>display: none</code>. It is therefore a not a surprise that it was decided to take this CSS property into SVG as well, together with <code>visibility</code> and <code>clip</code> as defined by CSS 2. For reverting a previously set <code>display: none</code> it is important to know, that the initial value for all SVG elements is <code>inline</code>.</p>
```

2021-08-21 13:40 UTC, Ryuno-Ki commented
I remove @mdn/yari-content-svg since @teoli2003 is already reviewing.
Thanks Jean-Yves!

2021-08-21 23:42 UTC, Astrono2 commented on files/en-us/web/svg/tutorial/clipping_and_masking/index.html
> +<p>One of the most powerful tools in a web developer's toolbox is <code>display: none</code>. It is therefore a little surprising, that it was decided to take this CSS property into SVG as well, toge
Oh you're right, my bad. I don't know how I got confused over that. Your suggestion for making it more clear is perfect.

2021-08-22 05:04 UTC, teoli2003 approved these changes

2021-08-22 05:05 UTC, merged

2021-08-22 05:05 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: