Directly link to Regexpr and String objects and methods
mdn/content pull request #8163
Opened 2021-08-21 08:47 UTC by tdelmas

Directly link to Regexpr and String objects and methods instead of giving the link to the index of the docs

> What was wrong/why is this fix needed? (quick summary only)

If it was useful to say those methods were explained in details, then it's better to directly link to the explanation.

And it's "Much better" according to https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide

2021-08-21 08:54 UTC, teoli2003 requested changes

2021-08-21 08:54 UTC, teoli2003 commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the [`RegExp`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) methods [`test()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) and [`
Yes, you are right. We even have a macro to create these links more easily (and they should take care of alt text, preview, typography, …).

```suggestion
Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec")}} and with the {{jsxref("String")}} methods {{jsxref("String/match", "match()")}}, {{jsxref("String/replace", "replace()}}, {{jsxref("String/search", "search()")}}, and {{jsxref("String/split", "split()")}}.
```

2021-08-21 17:36 UTC, tdelmas commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the [`RegExp`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) methods [`test()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) and [`
Thank you, I didn't know, it's nice!

2021-08-21 17:52 UTC, teoli2003 requested changes

2021-08-21 17:52 UTC, teoli2003 commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec")}} and with the {{jsxref("String")}} methods {{jsxref("Strin
Sorry I left a typo.
```suggestion
Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec")}} and with the {{jsxref("String")}} methods {{jsxref("String/match", "match()")}}, {{jsxref("String/replace", "replace()")}}, {{jsxref("String/search", "search()")}}, and {{jsxref("String/split", "split()")}}.
```

2021-08-21 18:05 UTC, tdelmas commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec")}} and with the {{jsxref("String")}} methods {{jsxref("Strin
I've fixed it and added back the parenthesis for `exec()`

2021-08-21 18:09 UTC, teoli2003 requested changes

2021-08-21 18:09 UTC, teoli2003 commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec()")}} and with the {{jsxref("String")}} methods {{jsxref("Str
There is a spurious backtick added back by cut and paste, and a missing parenthesis
```suggestion
Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()")}} and {{jsxref("RegExp/exec", "exec()")}} and with the {{jsxref("String")}} methods {{jsxref("String/match", "match()")}}, {{jsxref("String/replace", "replace()")}}, {{jsxref("String/search", "search()")}}, and {{jsxref("String/split", "split()")}}.
```

2021-08-21 18:10 UTC, teoli2003 commented on files/en-us/web/javascript/guide/regular_expressions/index.md
> +Regular expressions are used with the {{jsxref("RegExp")}} methods {{jsxref("RegExp/test", "test()`")}} and {{jsxref("RegExp/exec", "exec()")}} and with the {{jsxref("String")}} methods {{jsxref("Str
(Once you'll get your first PR merged, the tests will run automatically: it will be easier)

2021-08-22 07:59 UTC, teoli2003 approved these changes

2021-08-22 07:59 UTC, merged

2021-08-22 08:00 UTC, teoli2003 commented
Thanks a lot!

Congratulations upon your first merged commit here! Welcome aboard! :tada:

2021-08-23 07:56 UTC, tdelmas commented
Thanks!