Add WebXR Hit Test reference docs - pt 4
mdn/content pull request #8224
Opened 2021-08-23 08:39 UTC by Elchi3

Part 4 documents `XRHitTestResult` and its two methods `getPose()` and `createAnchor()`.

Specs:
- https://immersive-web.github.io/hit-test/#xr-hit-test-result-interface
- https://immersive-web.github.io/anchors/#anchor-creation

2021-08-24 15:11 UTC, jpmedley requested changes

2021-08-24 15:11 UTC, jpmedley commented on files/en-us/web/api/xrhittestresult/index.md
> +To get hit test results, you need to provide a {{domxref("XRHitTestSource")}}. See {{domxref("XRSession.requestHitTestSource()")}} for more information.
```suggestion
In addition to showing `XRHitTestResult` within a frame loop, this example demonstrates a few things you must do before requesting this object. While setting up the session, specify `"hit-test"` as one of the `requiredFeatures`. Next, call {{domxref("XRSession.requestHitTestSource()")}} with the desired references. (Obtain this by calling {{domxref("XRSession.requestReferenceSpace()")}}.) This returns a {{domxref("XRHitTestSource")}}. That you will use in the frame loop to get `XRHitTestResult` objects. 
```

2021-08-24 15:11 UTC, jpmedley commented on files/en-us/web/api/xrhittestresult/index.md
> +Once you found intersections on real-world surfaces using hit testing, you can create an {{domxref("XRAnchor")}} to attach a virtual object to that location.
```suggestion
Once you find intersections on real-world surfaces using hit testing, you can create an {{domxref("XRAnchor")}} to attach a virtual object to that location.
```

2021-08-24 15:41 UTC, Elchi3 commented on files/en-us/web/api/xrhittestresult/createanchor/index.md
> +  // add anchored objects to the scene
I think it is more involved. I can try to follow-up and query an SME to help me on this (if you think this is mission-critical).

2021-08-24 15:42 UTC, Elchi3 commented on files/en-us/web/api/xrhittestresult/getpose/index.md
> +### Getting the hit test result's pose
Sentence case per https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide#page_titles

2021-08-25 14:03 UTC, jpmedley commented on files/en-us/web/api/xrhittestresult/createanchor/index.md
> +  // add anchored objects to the scene
I'll approve the PR, but I think we need to give some kind of handle the reader even if it's just a link to something like an article or a more robust example.

2021-08-25 14:04 UTC, jpmedley commented on files/en-us/web/api/xrhittestresult/createanchor/index.md
> +  // add anchored objects to the scene
I don't just check actual links. I make sure that conceptual links aren't broken either.

2021-08-25 14:04 UTC, jpmedley approved these changes

2021-08-25 14:04 UTC, merged