Add reference pages for WebXR dynamic viewport scaling
mdn/content pull request #8280
Opened 2021-08-25 10:04 UTC by Elchi3

This adds reference pages for `XRView.requestViewportScale() `and `XRView.recommendedViewportScale`.
Also fixes some typos on the `XRView` page.

Specs:
- https://immersive-web.github.io/webxr/#dom-xrview-requestviewportscale
- https://immersive-web.github.io/webxr/#dom-xrview-recommendedviewportscale

2021-08-25 16:02 UTC, jpmedley requested changes

2021-08-25 16:02 UTC, jpmedley commented on files/en-us/web/api/xrview/requestviewportscale/index.md
> +
I have a tool that will be build boilerplates for an interface and all its members. Ruth and Rachel have been using it for nearly a year. Would you like me to show you how to use it?

2021-08-25 16:02 UTC, jpmedley commented on files/en-us/web/api/xrview/requestviewportscale/index.md
> +
(Caveat here is that it can't do things that aren't already in Chrome.)

2021-08-25 16:02 UTC, jpmedley commented on files/en-us/web/api/xrview/requestviewportscale/index.md
> +The call to {{domxref("XRWebGLLayer.getViewport()")}} applies the change and returns the updated viewport.
```suggestion
The following example shows how to request and apply a new viewport scale. The call to {{domxref("XRWebGLLayer.getViewport()")}} applies the change and returns the updated viewport.
```

2021-08-25 16:41 UTC, Elchi3 commented on files/en-us/web/api/xrview/recommendedviewportscale/index.md
> +
I've been using Value sections for properties. Syntax only makes sense for methods or constructors. We discussed this here: https://github.com/mdn/content/discussions/5992

2021-08-26 14:30 UTC, jpmedley requested changes
If the syntax is going away, then the value heading needs to be promoted. It was formerly a subsection of Syntax.

2021-08-26 16:06 UTC, jpmedley approved these changes

2021-08-26 16:07 UTC, merged