Update navigator.canShare, navigator.share, Web Share API
mdn/content pull request #8381
Opened 2021-08-27 07:34 UTC by hamishwillee

Further updates to `navigator.canShare`.

The main reason is that following some digging, I have verified that the message is a bit flawed. Essentially it can return invalid `true` if it does not understand data. It is however useful for feature detection.
I added a simple example using pseudo code for that, and explained it. 

Also removed the non-standard header and experimental flag. IMO it is not to either - though I am testing that in BCD. BCD also has spec update. 

Also noted that the value for the data is a "base set". This can be extended. Lots of work to be done in Web Share API doc (still to be created).

2021-08-27 19:17 UTC, jpmedley requested changes

2021-08-30 00:39 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +    <li>The specification does not require that new supported fields in the data are valid. It is possible that extension fields might be dropped even if valid, and the data still be considered "shar
There isn't one. I'm removing this future looking stuff based on Joe's comments.

2021-08-30 00:56 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +<p>The method can be used to feature-test if a data types is supported on a particular platform, including both the existing fields and new share data type extensions.</p>
Fair enough. Removed

2021-08-30 00:58 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +  <p><strong>Warning:</strong> The method is flawed in that it may return <code>true</code> for invalid share data that specifies more than one property:</p>
Thanks. I will fix.

2021-08-30 01:01 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +     Properties that are not supported on a particular platform will be ignored (the method will return <code>false</code> if there are no other valid properties in the data).</p>
@jpmedley Thanks. You're right. I will replace the grumpy subjective viewpoint with a simple statement about the comparison only being on "data properties understood by the implementation".

2021-08-30 01:57 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +<p>The method will generally also return <code>false</code> if the implementation does not support sharing of an indicated data type, for example files, or if sharing that data type would be consider
@saschanaz 
- This attempts to capture some general guidance about what might cause `false` to be returned. 
- Is this a reasonable statement? I know that it is true for `files` - but is it the intent of the API?
- When you refer to "implementation" in the spec about files perhaps not being shareable, do you mean "the user agent" or the underlying OS to which the share data is being passed?
- The term "hostile share" is used in the spec. I can imagine what it would mean, but does not appear to be defined. Is there one that I am missing?

2021-08-30 01:59 UTC, hamishwillee commented
@saschanaz @jpmedley Thanks for the review - adjusted to address your points. A few specifics:
- Removed the info about dependency on Permission API. There is no `web-share` permission - just  a web share "permission policy" permission.
- Does not talk about future extensions, though it does still mention base set of options.
- I now use the terminology  valid/invalid property indicate whether a property is understood by the implementation and "supported" to mean understood and will be evaluated, but not necessarily allowed. 
- I added a clarification of what is likely to return false in https://github.com/mdn/content/pull/8381#discussion_r698115221

2021-08-30 11:35 UTC, saschanaz commented on files/en-us/web/api/navigator/canshare/index.html
> +<p>The method will generally also return <code>false</code> if the implementation does not support sharing of an indicated data type, for example files, or if sharing that data type would be consider
The statement is now changed so I'll only answer the last two ones.

>When you refer to "implementation" in the spec about files perhaps not being shareable, do you mean "the user agent" or the underlying OS to which the share data is being passed?

Kinda both, the OS or the user agent not supporting the OS feature properly.

>The term "hostile share" is used in the spec. I can imagine what it would mean, but does not appear to be defined. Is there one that I am missing?

That's from https://github.com/w3c/web-share/issues/127 but admittedly it's way too vague. Filed https://github.com/w3c/web-share/issues/217

2021-08-30 15:47 UTC, jpmedley requested changes

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +<p>A {{jsxref("Promise")}}. This will be resolved with <code>undefined</code> once the data has been sent to the share target, or rejected with one of the <a href="#exceptions">Exceptions</a> given b
```suggestion
<p>A {{jsxref("Promise")}} that resolves with <code>undefined</code> once the data has been sent to the share target, or rejected with one of the <a href="#exceptions">Exceptions</a> given below.</p>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +      <li>The <code>data</code> parameter has been omitted completely or only only contains "unknown" properties. Note that any properties that are not recognized by the user agent are ignored.</li>
```suggestion
      <li>The <code>data</code> parameter was omitted completely or only contains properties with unknown values. Note that any properties that are not recognized by the user agent are ignored.</li>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +      <li>URL data is badly formatted.</li>
```suggestion
      <li>A URL is badly formatted.</li>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +<p>The example below shows how a button click can be used to invoke the Web Share API to share MDN's URL.
```suggestion
<p>The example below shows a button click invoking the Web Share API to share MDN's URL.
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +  <p><strong>Note:</strong> This code sample handles feature detection by testing for <code>navigator.canShare()</code> rather than for <code>navigator.share()</code>.
```suggestion
  <p><strong>Note:</strong> This sample feature detects by testing for <code>navigator.canShare()</code> rather than for <code>navigator.share()</code>.
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/navigator/share/index.html
> +  <li><a href="https://wpt.live/web-share/">https://wpt.live/web-share/</a> (web platform tests)</li>
Why include web platform tests? We don't do that on other web features.

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +<p>The <strong>Web Share API</strong> provides a mechanism for sharing text, links, files and other content to an arbitrary <em>share target</em> selected by the user.</p>
```suggestion
<p>The <strong>Web Share API</strong> provides a mechanism for sharing text, links, files, and other content to an arbitrary <em>share target</em> selected by the user.</p>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +<p>The API consists of just two methods:</p>
Please format this like the other API overview pages. [Here's an example](https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API#interfaces).

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +  <li>{{domxref("navigator.canShare()")}}: Validate that the specified data is sharable (check if a call with the same data to {{domxref("navigator.share()")}} would succeed).</li>
```suggestion
  <li>{{domxref("navigator.canShare()")}}: Returns a boolean indicating whether the specified data sharable; indicates whether a call with the same data to {{domxref("navigator.share()")}} would succeed.</li>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +  <li>{{domxref("navigator.share()")}}: Share the specified data. This method must be called on a button click or other user activation (requires {{Glossary("transient activation")}}).</li>
```suggestion
  <li>{{domxref("navigator.share()")}}: Returns a {{jsxref("Promise")}} that resolves if the passed data was successfully shared. This method must be called on a button click or other user activation (requires {{Glossary("transient activation")}}).</li>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +  If the policy is supported but has not been granted, both methods will immediately indicate that the data is not sharable.</p>
```suggestion
  If the policy is supported but has not been granted, both methods will indicate that the data is not sharable.</p>
```

2021-08-30 15:47 UTC, jpmedley commented on files/en-us/web/api/web_share_api/index.html
> +<p>The code fragment below shows how you can share a link using {{domxref("navigator.share()")}} triggered off a button click.</p>
```suggestion
<p>The code below shows how you can share a link using {{domxref("navigator.share()")}}, triggered off a button click.</p>
```

2021-08-30 23:41 UTC, hamishwillee commented on files/en-us/web/api/web_share_api/index.html
> +  <li>{{domxref("navigator.canShare()")}}: Validate that the specified data is sharable (check if a call with the same data to {{domxref("navigator.share()")}} would succeed).</li>
@jpmedley I'm proposing and going to accept thismodification of your wording to remove the text after the semicolon. The method does check if the data is sharable, but there are other reasons why `navigator.share()` might fail.
```suggestion
  <li>{{domxref("navigator.canShare()")}}: Returns a boolean indicating whether the specified data sharable.</li>
```

We could keep the sentence and clarify that, but I think the first part captures the concept sufficiently.

2021-08-30 23:46 UTC, hamishwillee commented on files/en-us/web/api/web_share_api/index.html
> +  <li>{{domxref("navigator.share()")}}: Share the specified data. This method must be called on a button click or other user activation (requires {{Glossary("transient activation")}}).</li>
@jpmedley Re "resolves if the passed data was successfully shared". Technically if "successfully passed to a share target", since it can fail before actually being shared outside of this API. I have modified but let me know if you think the distinction is not useful. 

```suggestion
  <li>{{domxref("navigator.share()")}}: Returns a {{jsxref("Promise")}} that resolves if the passed data was successfully sent to a share target. This method must be called on a button click or other user activation (requires {{Glossary("transient activation")}}).</li>
```

2021-08-30 23:48 UTC, hamishwillee commented on files/en-us/web/api/navigator/canshare/index.html
> +  <li>Sharing the specified data would be considered a "hostile share" by the user-agent.</li>
No. I raised that and it is being addressed in https://github.com/w3c/web-share/issues/217. We will have to fix as a post-process.

2021-08-30 23:56 UTC, hamishwillee commented on files/en-us/web/api/navigator/share/index.html
> +  <li><a href="https://wpt.live/web-share/">https://wpt.live/web-share/</a> (web platform tests)</li>
@jpmedley Mostly because I find them very useful, in particular for testing whether features are _now_ supported on a particular browser despite what the browser-compat-data says. I assume that others might also find them useful, and not necessarily be aware of them. 

As you say, it is inconsistent. I'll remove them.

2021-08-30 23:56 UTC, hamishwillee commented on files/en-us/web/api/web_share_api/index.html
> +<p>The API consists of just two methods:</p>
Thanks. I copied the Battery Status API - in retrospect, perhaps not a good choice.

2021-08-31 02:52 UTC, hamishwillee commented
Thanks for review @jpmedley. Since then ...
- I accepted all your suggestions (with some minor qualifications). Github wouldn't let me batch merge them - sorry if you got multiple notifications.
- Updated the top level API landing page to match the 'standard'
- Removed the link to web tests

2021-08-31 15:32 UTC, jpmedley approved these changes

2021-08-31 15:32 UTC, merged

2021-08-31 15:32 UTC, jpmedley commented
Thanks for your patience.

2021-09-01 08:37 UTC, hamishwillee commented
Thanks for yours @jpmedley - much appreciated.