Updated Note
mdn/content pull request #8391
Opened 2021-08-27 13:18 UTC by NegiAkash890

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #8268 

> What was wrong/why is this fix needed? (quick summary only)

Reframed Note paragraph

2021-08-28 17:47 UTC, rachelandrew commented on files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.html
> +<p><strong>Note</strong>: If you want to have a copy of the repository on your local machine that's ready to use, you could go the root directory of the unzipped folder, there open up a terminal , an
```suggestion
<p><strong>Note</strong>: To set up the project on your local machine, go to the root directory of the unzipped folder, open a terminal in that location, and execute the <code>npm install</code> command in the terminal. This will install all of the project dependencies that are stored in the `package.json` file.</p>
```

2021-08-28 17:48 UTC, rachelandrew requested changes
I've suggested a simplification of this note in the comments.

2021-08-31 11:55 UTC, sideshowbarker commented
@rachelandrew I think this one is waiting on your re-review

2021-09-02 03:44 UTC, rachelandrew approved these changes

2021-09-02 03:44 UTC, merged