Bug-1575625-Make-Cache-API-available-to-webextensions
mdn/content pull request #8397
Opened 2021-08-27 17:08 UTC by rebloor

Provides the documentation for [Bug-1575625](https://bugzilla.mozilla.org/show_bug.cgi?id=1575625) to provide a note that the web extensions address (`moz-extension://`) is also considered secure.

2021-09-07 16:24 UTC, rebloor commented
@wbamberg @rpl When you have a moment, your review would be appreciated

2021-09-07 17:12 UTC, wbamberg commented
Unassigning myself since I'm not working on add-ons any more.

2021-09-10 03:10 UTC, wbamberg commented
Sorry, I didn't look carefully enough to see that this is a change to a web docs page, not an add-ons page.

As it stands, I don't think we can say this - for one thing it's presumably not the case that other browsers consider `moz-extension://` a secure origin. So at an absolute minimum it should say "Firefox considers...". And I guess that might be OK. But I'm not that keen on random notes about specific browsers in the web docs: as far as possible we want to document the standards and document deviations from them in BCD.

It feels like this would fit better in the ["secure contexts"](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) page, perhaps in a section on browser-specific behavior. It would have to deal with @rpl 's footnote in https://bugzilla.mozilla.org/show_bug.cgi?id=1575625#c11 - but even given that, I think it would be better to document this there rather than in the Cache API page. That would also give us a place to capture the nuance in that footnote where `isSecureContext` doesn't necessarily mean you can use a secure-context API.

Or maybe better would be to capture this in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#background_script_environment , which is explicitly about the APIs available to extensions, and which currently doesn't mention this issue at all.

2021-09-10 16:22 UTC, rebloor commented
@rpl I will leave you to comment in the first instance

2021-09-15 02:01 UTC, sideshowbarker commented
@wbamberg This one seems to be waiting on a response from you

2021-09-15 02:19 UTC, wbamberg commented
I commented in https://github.com/mdn/content/pull/8397#issuecomment-916596473 , I think @rebloor is waiting for a response from @rpl .

2021-09-20 16:00 UTC, rpl commented
@wbamberg @rebloor I'm sorry I missed to notice this mention earlier.

Based on @wbamberg comment https://github.com/mdn/content/pull/8397#issuecomment-916596473, it looks that we may want to create a section to collect notes related to WebAPI available in WebExtensions globals (and special cases related to that).
I looked to the section we do have at the moment, and I didn't find one where we could just drop a note about the Cache WebAPI.

I'm not sure if it is worth creating it just for this short note about the Cache API, but it may be reasonable to:

- if we plan to add more in the future, it may be worth adding a new section to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API (e.g. one named "**Standard WebAPI listing**" with notes like this one for the Cache API and a link to the standard WebAPI reference doc page)
- if we are not sure that an entire section would be needed to collect more notes about standard WebAPI behaviors in extension context, then I think that a new section in  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#background_script_environment as suggested by @wbamberg can also be a valid alternative

2021-09-20 19:07 UTC, rebloor commented
@sideshowbarker Following your forced push from a few days ago this PR is showing files/en-us/web/api/cache/index.html Is in addition. Any idea why, how do I resolve?

2021-09-20 19:07 UTC, rebloor commented
@wbamberg @rpl Revised changes for your consideration

2021-09-21 09:28 UTC, sideshowbarker commented
> @sideshowbarker Following your forced push from a few days ago this PR is showing files/en-us/web/api/cache/index.html Is in addition. Any idea why, how do I resolve?

Fixed now

2021-09-21 16:24 UTC, rebloor commented
@sideshowbarker Still doesn't appear to be fixed, after reverting my initial commit I shouldn't have any changes in web/api/cache/index.md yet my original change is still there plus some other random changes

2021-09-21 17:22 UTC, rebloor commented
Thanks @sideshowbarker

2021-09-21 17:29 UTC, sideshowbarker commented
> @sideshowbarker Still doesn't appear to be fixed, after reverting my initial commit I shouldn't have any changes in web/api/cache/index.md yet my original change is still there plus some other random changes

OK, sorry for the churn. Pushed another update, and I think the branch is now in the state it should be

2021-09-22 10:49 UTC, rpl requested changes

2021-09-22 10:49 UTC, rpl commented on files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +
Unfortunately that isn't technically precise, in the extension pages `isSecureContext` returns `true` from way before Firefox 90 ([1]), but the problem is that for some WebAPI features that are meant to be restricted to secure contexts by spec... being a secure context is not enough from an "concrete  implementation" perspective, in particular when the underlying implementation can't (or just don't) check the same conditions that are checked behind `isSecureContext`, and instead they do explicit checks on the principal scheme.

And so, in Firefox 90 we fixed a bug from the `Cache` WebAPI, which should have considered the "moz-extension" scheme as allowed (but the moz-extension scheme was already meant to be considered secure, the Cache WebAPI was just doing its own checks which used to donn't consider the moz-extension scheme and was falling back to not allowing the API).

To be technically precise here, without being too overwhelming for the extension developer that may not be interested in the "low level details", here we may try to say something that introduce the concept of secure context, states that the extension pages are considered secure context and invite to file bugs on bugzilla if a WebAPI should be available in secure context but it is not available or doesn't work correctly in extension pages (with a link to "https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions&component=Untriaged" and maybe Bug 1575625 as an example of a bug filed for this kind of bugs).

@rebloor @wbamberg wdyt?

(I'm sorry that finding a reasonable place for this kind of notes is being trickier than we originally thought, but on the bright side the next time we will need to document this kind of fixes it should become way easier, once we have been able to agree on a reasonable approach for this case).  

-----

[1]: I haven't tried to bisect from exactly when, but the current mechanisms we use to determine is an url is a secure context has been introduced in Firefox 67 from [Bug 1328695](https://bugzilla.mozilla.org/show_bug.cgi?id=1328695) and based on the diff of the patches landed it looks that it was the case even before Firefox 67, it was based on the fact that the url schema is moz-extension, and so it is likely that has been always the case, or for long enough to don't matter anymore)

2021-09-22 15:54 UTC, rebloor commented
@sideshowbarker Infortunately the file is back again.  I'm thinking that once I got agreement on the changes I will abandon this branch and start a new one.

2021-09-22 16:28 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +
I have reworded along the lines you suggest @rpl. However, I'm inclined to leave out the comment about filing bugs, as there is already enough information about filing bugs with issues found in Firefox. Thoughts?  Also, as with the Web API changes that originally started this discussion, should this comment be more general/not Firefox specific. However, I don't seem to be able to find similar references for Chrome etc.

2021-09-22 16:58 UTC, wbamberg commented on files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.html
> +
I think it would be better to remove the edit to https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts from this PR, and keep this information within the add-ons documentation, for the following reasons:

* as @rpl says, it's a bit misleading, because just being "considered a secure context" isn't apparently a guarantee that you can actually use an API
* it's rather browser-specific, which we'd like to discourage on MDN
* it's not that helpful to users - presumably what users really want to know is: "which APIs can I use from an extension background script?" and this doesn't directly answer that question.

I like the new bit in https://pr8397.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#background_script_environment . I think if we want this document to be cross-browser we can't link to Bugzilla for "file a bug".

I think there are a couple of options here.

* One is just to say more or less what you have: in theory WebExtensions should be able to use secure context APIs, although in practice some APIs might still not be available. Easy but not terribly helpful.
* The other is to enumerate the secure APIs and say which ones people can actually use - helpful but lots of work and hard to maintain.

And as you say, I'm not sure what the cross-browser story is. If https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension is intended to be a cross-browser page (which I think it is?) then this section should at least acknowledge that. Ideally we would know the situation for other browsers and ensure the words given here are correct for them. Or alternatively we could make it clear that  the words here are for Firefox and the situation for other browsers is unknown.

The other thing is whether this section is a bit buried and hard to find. I think @rpl suggested adding something to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API , which is currently only about the WebExtension APIs. But it could have a section on "Web APIs" or something, that talks about the Web APIs available to background scripts.

2021-09-23 17:25 UTC, rpl commented
> I think it would be better to remove the edit to https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts from this PR...

:+1: on removing the change applied on this doc page,  @wbamberg points seems convincing + personally I'm not sure the extension developer would get easily on that doc page while looking for Web APIs that should work in an extension.

> I like the new bit in https://pr8397.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#background_script_environment . I think if we want this document to be cross-browser we can't link to Bugzilla for "file a bug".

I'm also fine with removing the link to bugzilla, or to use a warning box as it looks we are already doing for the Firefox specific notes about the availability of "alert/confirm/prompt" from the background pages.

> The other thing is whether this section is a bit buried and hard to find. I think @rpl suggested adding something to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API , which is currently only about the WebExtension APIs. But it could have a section on "Web APIs" or something, that talks about the Web APIs available to background scripts.

I would be ok with listing this kind of compatibility info in a "Web APIs" section eventually added to that `WebExtensions/API` doc page, but I'm wondering:

at that point wouldn't be more easier to maintain those notes over the time if we would use a compatibility table generated from metadata stored in mdn/browser-compat-data? (so that we can also allow us to include compatibility notes related to other vendors)

@wbamberg wdyt?

2021-09-23 17:46 UTC, wbamberg commented
> > I think it would be better to remove the edit to https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts from this PR...
> 
> 👍 on removing the change applied on this doc page, @wbamberg points seems convincing + personally I'm not sure the extension developer would get easily on that doc page while looking for Web APIs that should work in an extension.
> 
> > I like the new bit in https://pr8397.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#background_script_environment . I think if we want this document to be cross-browser we can't link to Bugzilla for "file a bug".
> 
> I'm also fine with removing the link to bugzilla, or to use a warning box as it looks we are already doing for the Firefox specific notes about the availability of "alert/confirm/prompt" from the background pages.
> 

Yes, I think this is fine. For the add-ons pages, the main thing is to be clear that this is Firefox-specific, and to think about how it would feel for an Edge extension developer to read the page, say. Will they be confused? Will they just think, this is Firefox documentation, and stop reading?

> > The other thing is whether this section is a bit buried and hard to find. I think @rpl suggested adding something to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API , which is currently only about the WebExtension APIs. But it could have a section on "Web APIs" or something, that talks about the Web APIs available to background scripts.
> 
> I would be ok with listing this kind of compatibility info in a "Web APIs" section eventually added to that `WebExtensions/API` doc page, but I'm wondering:
> 
> at that point wouldn't be more easier to maintain those notes over the time if we would use a compatibility table generated from metadata stored in mdn/browser-compat-data? (so that we can also allow us to include compatibility notes related to other vendors)
> 
> @wbamberg wdyt?

Yeah, when I was writing that comment I had that vague thought too. This does seem like a browser compat issue, and it would be great to have a table of secure APIs and browser versions to help visualise which APIs are available where.

But I can't see how it really fits into BCD unfortunately. BCD is organized in terms of web platform features, and which browsers support them. For example, we can easily represent questions like _"which browsers support tabs.executeScript"_ or _"which browsers support the Cache API"_.

But we want to represent something like "_which browsers support {some API} **in extensions**"_ and I don't see how we can fit that shape of question into this model.

The nearest thing I could think of would be the [`worker_support` subfeature](url), which lets us say when a feature is available in workers. But even if BCD allowed us to add an `extension_support` feature (which I doubt) that doesn't really help much because you can't use the existing `{{Compat}}` macro to show a summary table of "extension support for all secure APIs".

So the best I could think of would be a table just maintained in content of APIs and browser support for them. I don't know enough about the domain to know if this would be useful though (I mean, if 99% of secure context APIs are actually available in all platforms, then it's probably better just to say "all secure context APIs are supported, except for...").

2021-09-24 16:43 UTC, rebloor commented
@wbamberg @rpl I'm wondering if we are overthinking this. Looking at the other extensions documentation, none of it appears to progress beyond noting that extensions have "access to the same APIs as web pages." The issue that triggered this documentation request seems isolated and other similar issues that may exist shouldn't be fundamentally different from any other bug or issue in Firefox/extensions.

2021-09-27 09:19 UTC, rpl commented
> @wbamberg @rpl I'm wondering if we are overthinking this. Looking at the other extensions documentation, none of it appears to progress beyond noting that extensions have "access to the same APIs as web pages." The issue that triggered this documentation request seems isolated and other similar issues that may exist shouldn't be fundamentally different from any other bug or issue in Firefox/extensions.

I'm definitely fine with just the mention in the Firefox 90 release notes that we already have:
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/90#changes_for_add-on_developers

Given that the extension globals are being considered already as Secure Contexts in Firefox for quite some time, the fact that the Cache WebAPI wasn't working as expected from moz-extension urls was a bug and it got already a mention in release notes for Firefox 90.

If in the future we have more WebAPIs that we would like to explicitly annotate for compatibility in extension globals across browser vendors we can reconsider one of the approaches that we have been discussing in this PR.

2021-09-27 17:12 UTC, rebloor commented
Thanks @rpl, therefore going to close this PR. @wbamberg Please let me know if you have any other thoughts

2021-09-27 17:12 UTC, closed without merging