Add Introduction of EmbedGHLiveSample
mdn/content pull request #8440
Opened 2021-08-29 07:05 UTC by pocketdr

Update a new to inserting live sample.

2021-08-29 12:29 UTC, mutoe requested changes

2021-08-29 12:29 UTC, mutoe commented on files/en-us/mdn/structures/macros/commonly-used_macros/index.html
> + <li><code>{{TemplateLink("EmbedGHLiveSample")}} supported a new way to simply inserting live sample. You can get more information at <a href="/en-US/docs/MDN/Structures/Code_examples#github_live_sam
Is there a redundant `code` mark here?

2021-08-30 05:03 UTC, Elchi3 requested changes

2021-08-30 05:03 UTC, Elchi3 commented on files/en-us/mdn/structures/macros/commonly-used_macros/index.html
> + <li>{{TemplateLink("EmbedGHLiveSample")}} supported a new way to simply inserting live sample. You can get more information at <a href="/en-US/docs/MDN/Structures/Code_examples#github_live_samples">
```suggestion
 <li>{{TemplateLink("EmbedGHLiveSample")}} allows to embed live samples from GitHub pages. You can get more information at <a href="/en-US/docs/MDN/Structures/Code_examples#github_live_samples">GitHub live samples</a>.</li>
```

2021-08-30 07:36 UTC, Elchi3 approved these changes
Thank you! 👍

2021-08-30 07:36 UTC, merged