Django/Express Fix up notes and other crud prior to markdown conversion
mdn/content pull request #8457
Opened 2021-08-30 07:51 UTC by hamishwillee

Fixing up notes so that the markdown converter can be used.

2021-08-30 23:49 UTC, wbamberg commented on files/en-us/learn/server-side/django/deployment/index.html
> +  <p><strong>Note:</strong> Remember that price is not the only selection criteria. If your website is successful, it may turn out that scalability is the most important consideration.</p>
```suggestion
  <p><strong>Note:</strong> Remember that price is not the only selection criterion. If your website is successful, it may turn out that scalability is the most important consideration.</p>
```

2021-08-30 23:55 UTC, wbamberg requested changes
Thanks for this Hamish, it's great to see.

There was one grammar issue I couldn't let go, otherwise this looks good

2021-08-31 00:05 UTC, hamishwillee commented
Thanks @wbamberg - what criteria did you use to assess this? Trigger trigger trigger :-)

2021-08-31 00:37 UTC, wbamberg approved these changes
aaargh. Thanks Hamish!

2021-08-31 00:37 UTC, merged