Remove dead links and anchors in headings for Plugins/Guide
mdn/content pull request #8458
Opened 2021-08-30 08:59 UTC by teoli2003

There were dozens of dead links on this page (linking to the delete Plugins reference).

I also fixed all fragments, and moved links out of headings.

Overall this fixes 198 flaws that are almost 2% of all flaws on MDN.

One day, we will be able to just delete the whole plugin guide!

2021-08-30 09:35 UTC, teoli2003 commented
Companion PR to add spec url: mdn/browser-compat-data#12219

2021-08-31 04:12 UTC, wbamberg requested changes
This is great! I had one comment.

2021-08-31 04:12 UTC, wbamberg commented on files/en-us/plugins/guide/index.html
> -<div class="originaldocinfo">
I think the H3 under here should be H2 (since semantically it doesn't belong under "Constants").

2021-08-31 05:11 UTC, teoli2003 commented on files/en-us/plugins/guide/index.html
> -<div class="originaldocinfo">
Absolutely. I missed that. Commit in.

2021-08-31 05:12 UTC, wbamberg approved these changes
👍

2021-08-31 05:12 UTC, merged