update: adds interactive demo link for `overscroll-behaviour`
mdn/content pull request #8482
Opened 2021-08-31 04:31 UTC by anirudh-modi

> What was wrong/why is this fix needed? (quick summary only)

This is to add an interactive demo for `overscroll-behavior` which was recently merged in `interactive-example` repo. https://github.com/mdn/interactive-examples/pull/1870

2021-08-31 04:39 UTC, anirudh-modi commented
Hi @wbamberg here is the PR for adding an interactive demo for `overscroll-behavior`.

One issue which I am facing is that when I start my server and go to the `overscroll` page it is showing a `404`, I am not sure if this will be auto fixed or do I need to do anything else.

<img width="1103" alt="131441205-28873398-3030-4528-8910-d8894c262e9b" src="https://user-images.githubusercontent.com/16587779/131442782-4c723d27-48c3-4b9c-9b2b-efcab54d7b2d.png">

2021-09-08 18:11 UTC, wbamberg requested changes
Thanks @anirudh-modi ! This is great but the `## Syntax` line needs to be moved up so it's just after the `{{EmbedInteractiveExample}}` line. See for example https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side.

2021-09-14 16:15 UTC, anirudh-modi commented
@wbamberg Is this how it should be?

<img width="533" alt="Screenshot 2021-09-14 at 9 45 01 PM" src="https://user-images.githubusercontent.com/16587779/133294958-92e22431-bab9-47a5-b757-25a900f18fb1.png">

2021-09-14 16:22 UTC, anirudh-modi commented on files/en-us/web/css/overscroll-behavior/index.md
> +
@wbamberg  I guess this text should be in the original position right? I am not 100% sure if I have misplaced it

2021-09-14 17:08 UTC, wbamberg commented on files/en-us/web/css/overscroll-behavior/index.md
> +
Yeah, I think it would be best for those two paragraphs, "By default, mobile browsers..." and. "In some cases..." to be immediately after the interactive example, and before the H2 "Syntax"

2021-09-14 17:12 UTC, wbamberg commented on files/en-us/web/css/overscroll-behavior/index.md
> +
Like this:

<img width="575" alt="Screen Shot 2021-09-14 at 10 11 55 AM" src="https://user-images.githubusercontent.com/432915/133303130-d60e15ee-6bfb-4ffb-82a0-ba2b84407de4.png">

2021-09-15 02:47 UTC, anirudh-modi commented on files/en-us/web/css/overscroll-behavior/index.md
> +
@wbamberg done..

2021-09-15 02:50 UTC, wbamberg approved these changes
Looks great. Thanks for all your work on this one @anirudh-modi !

2021-09-15 02:50 UTC, merged

2021-09-15 03:40 UTC, anirudh-modi commented
Thanks for your support @wbamberg