Adds the AudioData interface
mdn/content pull request #8511
Opened 2021-09-01 05:47 UTC by rachelandrew

Adds `AudioData` from WebCodecs.

Reviewer @jpmedley

2021-09-01 15:45 UTC, jpmedley requested changes

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/clone/index.md
> +The **`clone`** method of the {{domxref("AudioData")}} interface creates a new `AudioData` object with reference to the same media resource as the original.
```suggestion
The **`clone()`** method of the {{domxref("AudioData")}} interface creates a new `AudioData` object with reference to the same media resource as the original.
```

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/clone/index.md
> +  - : Thrown if the `AudioData` object has been {{domxref("Transferable","transfered")}}.
What does this mean?

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/clone/index.md
> +let AudioData2 = AudioData.clone();
```suggestion
The following example clones a copy of `AudioData` as `audioData2`.

```js
let audioData2 = AudioData.clone();
```

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/close/index.md
> +The **`close`** method of the {{domxref("AudioData")}} interface clears all state and releases the reference to the media resource.
```suggestion
The **`close()`** method of the {{domxref("AudioData")}} interface clears all states and releases the reference to the media resource.
```

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/copyto/index.md
> +The **`copyTo`** method of the {{domxref("AudioData")}} interface copies a plane of an `AudioData` object to a destination buffer.
```suggestion
The **`copyTo()`** method of the {{domxref("AudioData")}} interface copies a plane of an `AudioData` object to a destination buffer.
```

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
```suggestion
To return the sample format of an `AudioData` object use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In an interleaved format, the audio samples are laid out in a single buffer, therefore the `AudioData` has a single **plane**. This plane contains a number of elements equal to {{domxref("AudioData.numberOfFrames")}} * {{domxref("AudioData.numberOfChannels")}}.
```

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
>In an interleaved format, the audio samples are laid out in a single buffer, therefore the `AudioData` has a single **plane**.

This latter suggests interleaved and planer, yet you said interleaved _or_ planer earlier. What am I missing?

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
What about interleaved format?

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +  - : Returns the sample format of the audio.
Florian recently challenged me on the the term 'Returns' when referring to properties, stating that it should only be used for methods. I never had a problem with this. What are your thoughts? ( I can't remember what he used instead.)

2021-09-01 15:45 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +  - : Clears all state and releases the reference to the media resource.
```suggestion
  - : Clears all states and releases the reference to the media resource.
```

2021-09-01 15:50 UTC, Elchi3 commented on files/en-us/web/api/audiodata/index.md
> +  - : Returns the sample format of the audio.
He uses "represents" but he is open to feedback on this.

2021-09-02 07:30 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +  - : Returns the sample format of the audio.
What was his argument? I think if you asked a dev to describe what is happening they would say that it returns the value.

The Write an API documentation also agrees currently: "The InterfaceName.property read-only property returns a {{domxref("type")}} that..."

2021-09-02 07:34 UTC, rachelandrew commented on files/en-us/web/api/audiodata/audiodata/index.md
> +The **`AudioData()`** constructor creates a new {{domxref("AudioData")}} object which represents an individual audio sample.
I have no evidence of anyone doing anything with it, to be honest. All the examples I can find are for video.

2021-09-02 07:35 UTC, rachelandrew commented on files/en-us/web/api/audiodata/allocationsize/index.md
> +The **`allocationSize`** method of the {{domxref("AudioData")}} interface returns the size in bytes required to hold the sample as filtered by options passed into the method.
the one that is filtered by the options passed in. An `AudioData` is a sample, however you can filter it down by the options passed in.

2021-09-02 07:37 UTC, rachelandrew commented on files/en-us/web/api/audiodata/clone/index.md
> +  - : Thrown if the `AudioData` object has been {{domxref("Transferable","transfered")}}.
I linked to the docs for transferable objects, so I didn't think we also needed to include it here. I'm not sure what it adds to do so.

2021-09-02 07:38 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
As explained in the para above, it has a single plane.

2021-09-02 14:01 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
Both definitions mention planes. That's why I'm confused.

2021-09-02 14:10 UTC, jpmedley requested changes

2021-09-02 14:10 UTC, jpmedley commented on files/en-us/web/api/audiodata/audiodata/index.md
> +      - : A timestamp in microseconds.
```suggestion
      - : An integer indicating the data's time in microseconds .
```

2021-09-02 14:10 UTC, jpmedley commented on files/en-us/web/api/audiodata/allocationsize/index.md
> +The **`allocationSize`** method of the {{domxref("AudioData")}} interface returns the size in bytes required to hold the sample as filtered by options passed into the method.
```suggestion
The **`allocationSize()`** method of the {{domxref("AudioData")}} interface returns the size in bytes required to hold the current sample as filtered by options passed into the method.
```

2021-09-02 14:10 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
Is 'interleaved' simply the definition for a single-plane format?

2021-09-03 06:43 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
yes both have planes, interleaved only has one. I'm no expert on audio formats, but the spec text and algorithms treat it as such.

2021-09-07 15:44 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
Closing this in favor of a new suggestin.

2021-09-07 15:55 UTC, jpmedley requested changes

2021-09-07 15:55 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
```suggestion
To return the sample format of an `AudioData` object use the {{domxref("AudioData.format")}} property. The format is stored in buffers called planes, and may be described as **interleaved** or **planar**. In interleaved format, the audio samples are a single plane that contains a number of elements equal to {{domxref("AudioData.numberOfFrames")}} times {{domxref("AudioData.numberOfChannels")}}.
```

2021-09-07 15:55 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
>The format is stored in buffers called planes

This is the keystone of my proposal. It allows later descriptions to be simplified.

2021-09-07 15:55 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
```suggestion
In planar format, the number of planes is equal to {{domxref("AudioData.numberOfChannels")}}, and each plane contains a number of elements equal to {{domxref("AudioData.numberOfFrames")}}.
```

2021-09-07 15:55 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
These two suggestions rise and fall together. 

I don't know if I've improved this merely substituted my writing preferences for yours. Tell me what you think.

2021-09-07 15:56 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
Thank you for your patience.

2021-09-09 09:02 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
My only concern is that the spec does not state that buffers are called planes, I'm wondering if by simplifying this we actually infer some relationship that isn't quite correct (though may be correct in terms of how WebCodecs deals with it). I don't know enough about audio to be able to say. I think my version maintains the distinction in the spec, yours makes them equivalent. If that is correct, then the simplification works.

2021-09-09 09:03 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +In a planar format, the audio samples from the different channels are laid out in different buffers. The `AudioData` has a number of planes equal to {{domxref("AudioData.numberOfChannels")}}, each pl
I think this is fine with regard to the spec, whatever the answer to the above point is!

2021-09-09 14:01 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
If planes aren't buffers, then I don't understand the relationship between them and I can't judge whether your version is even correct. Please ping the spec author for clarification.

2021-09-20 18:13 UTC, chcunningham commented on files/en-us/web/api/audiodata/clone/index.md
> +let AudioData2 = AudioData.clone();
nit: s/AudioData.clone()/audioData.clone()/

2021-09-20 19:52 UTC, chcunningham commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
I'm using buffer as synonym for "array". Buffer is a more generic concept than plane. It would be correct to say that any plane is a buffer, but not the other way around. 

For example, if you called

`audioData.copyTo(destination, {planeIndex: 0})`

After this call I would describe `destination` as being a buffer containing (a copy of) plane 0. 

If you instead called

`audioData.copyTo(destination, {planeIndex: 0, frameCount: 1})`

I'd still call `destination` a buffer, but now it only contains a single frame from plane 0.

I read both of your phrasing as being correct w/ some small nits of my own.
- "In a interleaved format.." - the 'a' is helpful here because there are multiple interleaved formats. Alternatively, you could pluralize format.
- "... the audio samples are" - I'd mention channels here as you do for planar format. e.g. "the audio samples _from the different channels_ are".
- "The format is stored in buffers called planes" - little fast/loose, but maybe ok if you were both clear on the meaning. Technically it's the "data" or "samples" that are stored in buffers, with a arrangement defined by "format".  
-

2021-09-21 20:29 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
@jpmedley I haven't got back to this yet, elsewhere this also refers to transferable objects which have been removed in the last few days so we had a discussion about that and I raised https://github.com/mdn/content/pull/9141, I figured I could link that it once it is merged when I edit this one.

I'll try and edit this to be correct and acceptable at the same time. :)

2021-09-22 14:00 UTC, jpmedley commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
ack

2021-09-24 07:36 UTC, rachelandrew commented on files/en-us/web/api/audiodata/index.md
> +To return the sample format of an `AudioData` use the {{domxref("AudioData.format")}} property. The format may be described as **interleaved** or **planar**. In a interleaved format, the audio sample
@jpmedley latest commit addresses this. I think.

2021-09-27 13:42 UTC, jpmedley approved these changes

2021-09-27 13:42 UTC, merged

2021-09-27 23:43 UTC, chcunningham commented
:fireworks: thanks @rachelandrew