Match Array.p.sort() doc’s code to expected output
mdn/content pull request #852
Opened 2021-01-02 13:16 UTC by sideshowbarker

This change adds some `.join()` calls to one of the code examples in the Web/JavaScript/Reference/Global_Objects/Array/sort article, to make the example code match the expected output shown.

Fixes https://github.com/mdn/content/issues/848

The change also includes a fix for a broken hyperlink.

2021-01-05 16:53 UTC, sideshowbarker commented
> This fixes the issue but I'm unsure if we really want to do this. I think this example should be re-written to not have code and output section separately. I think it is unnecessarily hard to read and understand this way. How about this?
> 
> ```js
> let stringArray = ['Blue', 'Humpback', 'Beluga'];
> let numericStringArray = ['80', '9', '700'];
> let numberArray = [40, 1, 5, 200];
> let mixedNumericArray = ['80', '9', '700', 40, 1, 5, 200];
> 
> function compareNumbers(a, b) {
>   return a - b;
> }
> 
> stringArray.join(); // 'Blue,Humpback,Beluga'
> stringArray.sort(); // ['Beluga', 'Blue', 'Humpback']
> 
> numberArray.join(); // '40,1,5,200'
> numberArray.sort(); // [1, 200, 40, 5]
> numberArray.sort(compareNumbers); // [1, 5, 40, 200]
> 
> numericStringArray.join(); // '80,9,700'
> numericStringArray.sort(); // [700, 80, 9]
> numericStringArray.sort(compareNumbers); // [9, 80, 700]
> 
> mixedNumericArray.join(); // '80,9,700,40,1,5,200'
> mixedNumericArray.sort(); // [1, 200, 40, 5, 700, 80, 9]
> mixedNumericArray.sort(compareNumbers); // [1, 5, 9, 40, 80, 200, 700]
> ```
> 
> What do you think?

Agreed, yes — will amend the patch here to do it that way instead

> That way the reader doesn't need to jump back and forth between the code and output.

Yep, exactly — this is much better

2021-01-14 13:23 UTC, chrisdavidmills commented
@sideshowbarker pinging you on this one.

2021-01-14 15:23 UTC, sideshowbarker commented
> @sideshowbarker pinging you on this one.

Thanks, will make time to get back to this

2021-01-26 18:22 UTC, Ryuno-Ki commented
There's a merge conflict.

2021-02-01 03:57 UTC, sideshowbarker commented
Sorry, will make time this week to finish this

2021-02-01 08:06 UTC, Ryuno-Ki commented
All good. I merely wanted to bring this up in case it fell off the radar. Take your time.

2021-02-18 17:12 UTC, Elchi3 commented
Removing review request for now. Please re-request it from me if changes are made :)

2021-02-24 06:12 UTC, sideshowbarker commented
@Elchi3 Sorry for the long delay in getting back to this one. I made the code-example replacement as suggested in https://github.com/mdn/content/pull/852/#issuecomment-754741222 — so this should be ready for another look now.

2021-02-24 11:56 UTC, Elchi3 requested changes
Thanks @sideshowbarker! Need to remove the section that is now inline with the new code example.

So, everything that comes with "This example produces the following output." needs to be removed.

2021-02-24 16:29 UTC, sideshowbarker commented
> So, everything that comes with "This example produces the following output." needs to be removed.

oops — thanks, yep, now removed

2021-02-25 12:49 UTC, Elchi3 approved these changes
Thanks Mike!

2021-02-25 12:49 UTC, merged