Adds Glossary page for Clickjacking
mdn/content pull request #8577
Opened 2021-09-02 22:48 UTC by KanishkTagade

> What was wrong/why is this fix needed? (quick summary only)
This PR adds a page for the Clickjacking entry in Glossary from https://datatracker.ietf.org/doc/html/rfc7034.

This is my first time contributing to MDN, so apologies if I have missed out anything.

2021-09-27 14:46 UTC, ddbeck requested changes
Hi @KanishkTagade and thanks for this PR. Welcome to the project! This is a good first start on a glossary entry.

To add this page, we need to a solve significant problem first. Right now, this page is a content island. No pages link to it (and it links only to one other MDN page). To justify adding this page, you need to find some instances of "clickjacking" appearing in other MDN pages and link to your new page from them.

When it comes to the glossary entry itself, I've raised a couple of issues in line comments. 

Thank you again!

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> +<p>Clickjacking can be prevented by implementing a Content Security Policy (CSP) and <a href="https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html">other defense metho
The linked page links _back_ to MDN, to pages such as https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes. Let's save the reader the round trip and link to them directly.

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> +<p>Clickjacking is an interface-based attack that tricks website users into unwarily clicking on malicious links. In clickjacking, the attackers embed their malicious links into buttons or legitimate
A couple of suggestions here:

- Punctuation fix
- Dropping the OWASP citation here (I thinking citing a four-year old list undermines the point)

```suggestion
<p>Clickjacking is an interface-based attack that tricks website users into unwarily clicking on malicious links. In clickjacking, the attackers embed their malicious links into buttons or legitimate pages in a website. In an infected {{glossary("Site")}}, whenever a user clicks on a legitimate link, the attacker gets the confidential information of that user, which ultimately compromises the user's privacy on the Internet.</p> 
```

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> + <li><a href="/en-US/docs/Web/Security/Types_of_attacks#clickjacking">Clickjacking</a></li>
This page seems to be an incomplete draft. Perhaps we should link to something a bit more substantial such as https://developer.mozilla.org/en-US/docs/Web/Security#clickjacking_protection

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> + <li><a href="https://owasp.org/www-community/attacks/Clickjacking">Clickjacking on OWASP</a></li>
For consistency with the previous item

```suggestion
 <li><a href="https://owasp.org/www-community/attacks/Clickjacking">Clickjacking</a> on OWASP</li>
```

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> + <li><a href="https://www.getastra.com/blog/knowledge-base/clickjacking-all-you-need-to-know/">Example of Clickjacking in action</a></li>
Link directly to the cited heading

```suggestion
 <li><a href="https://www.getastra.com/blog/knowledge-base/clickjacking-all-you-need-to-know/#Example_of_Clickjacking_in_Action">Example of Clickjacking in action</a></li>
```

2021-09-27 14:46 UTC, ddbeck commented on files/en-us/glossary/clickjacking/index.html
> + <li><a href="https://portswigger.net/web-security/clickjacking">Another article about Clickjacking</a></li>
Can we provide more descriptive link text here? This doesn't exactly say "this is a valuable resource" to readers 😃 

```suggestion
 <li><a href="https://portswigger.net/web-security/clickjacking">Clickjacking (UI redressing)</a> on PortSwigger Web Security Academy</li>
```

2021-09-29 08:32 UTC, KanishkTagade commented on files/en-us/glossary/clickjacking/index.html
> +<p>Clickjacking can be prevented by implementing a Content Security Policy (CSP) and <a href="https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html">other defense metho
Added direct linking to MDN pages

2021-09-29 08:32 UTC, KanishkTagade commented on files/en-us/glossary/clickjacking/index.html
> + <li><a href="/en-US/docs/Web/Security/Types_of_attacks#clickjacking">Clickjacking</a></li>
Linked to the suggested URL

2021-09-29 11:08 UTC, ddbeck requested changes
Thanks for the updates, @KanishkTagade. This is starting to look really good!

We still have one last issue to resolve: no pages on MDN link _to_ this glossary entry yet. I'd suggest finding a two or three places where we use the term "clickjacking" in other pages (or where we ought to mention it) and link to this glossary entry. That way, this page won't be lonely. 😃

2021-10-29 21:22 UTC, KanishkTagade commented
Hey @marcelozarate, thank you for writing and suggesting the relevant links. I have checked all the existing MDN content links provided by you and proposed the changes for the same (by adding and/or replacing the existing "clickjacking" word/link with this MDN glossary entry. 

It would be really helpful if you or @ddbeck can give it a look and guide me on the next steps. Thank you very much :)

2021-10-31 23:56 UTC, hamishwillee commented
Hi @KanishkTagade,

Thanks so much. Unfortunately you have made the right changes but in the wrong place. If you look at this PR file tab (reproduced below) you can see that the changes have been made to your main branch, but only ONE file has been changed:

![image](https://user-images.githubusercontent.com/5368500/139605442-e6eb3057-d60d-4210-96a6-e142a221447d.png)

I can see that you have made all the other chances, but you have made them to different branches - not "main" - so they won't show up in this PR. For example, if you look below, you can see you fixed the problem in patch 12 branch, not main branch:

![image](https://user-images.githubusercontent.com/5368500/139605427-fe915a6e-70f6-4c39-804c-b9c16b2d172d.png)

So what you need to do is make all your changes in one branch - main - and then they will all show up in this PR. You can do this on your default branch https://github.com/KanishkTagade/content
YOu will know you have succeeded if you make the change and this PR shows that you have changed more than one file.

Thanks!

2021-10-31 23:58 UTC, hamishwillee commented
PS I'll help you push this to the end. YOu might want to start again doing this locally and creating a new PR because glossary entries have migrated to markdown now. Up to you.

2021-11-02 09:06 UTC, KanishkTagade commented
Hello @hamishwillee, Thank you for your suggestions. As requested, I have made all the changes and created a separate PR. Request you to please go through and let me know if any more changes are required. Thank you very much once again :)

2021-11-02 21:38 UTC, hamishwillee commented
Closing, because I see you've reopened a new one: #10226

Thanks @KanishkTagade - I won't review the new one because I can see you've done it right - and it is getting review from others.

2021-11-02 21:38 UTC, closed without merging