sup not working in code (at least in Firefox)
mdn/content pull request #858
Opened 2021-01-02 17:46 UTC by joendres

![grafik](https://user-images.githubusercontent.com/16019814/103463177-c8eef200-4d2a-11eb-9030-1427b835a268.png)

2021-01-02 17:52 UTC, nschonni commented
Looks like Yari might be stripping them out
![image](https://user-images.githubusercontent.com/1297909/103463274-50237200-4cf9-11eb-9566-71b507c6b828.png)

2021-01-02 18:27 UTC, sideshowbarker requested changes

2021-01-02 18:27 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/number/index.html
> +const smallestInt = Number.MIN_SAFE_INTEGER  // -(<code>2**53 - 1</code>) =&gt; -9007199254740991</pre>
```suggestion
<pre class="brush: js notranslate">const biggestInt  = Number.MAX_SAFE_INTEGER  //  (<code>2^53 - 1</code>) =&gt;  9007199254740991
const smallestInt = Number.MIN_SAFE_INTEGER  // -(<code>2^53 - 1</code>) =&gt; -9007199254740991</pre>
```
I think the caret in the more common and familiar way to indicate superscript; see https://pages.uoregon.edu/ncp/Courses/MathInPlainTextEmail.html

> Use "^" for superscripts: 2^6, e^3, etc. ("**" instead of "^" is also OK.)

So while that says the double-asterisk syntax is "OK", it suggests we should prefer the caret.

2021-01-02 18:28 UTC, sideshowbarker commented
> Looks like Yari might be stripping them out

Alerting @mdn/core-yari-dev

2021-01-05 14:00 UTC, peterbe commented
Yeah this is tricky. We've moved to using PrismJS on the server (in Node) which operates differently. 
One of the things we lost is the ability to highlight specific lines. Another is the ability to inject custom HTML tags into the snippet code. Basically, we're about as basic as Markdown is when you inject code with triple-back-ticks. And moving to a more constrained formatting tool (like Markdown) is something we probably want to do in 2021.

In Yari, all the code in the `<pre>` is treated as text. Almost like when a human, using a browser, highlights the text with the mouse cursor and then copies and pastes into notepad. 

PrismJS in Node is much more limited than PrismJS in the browser :(
Many PrismJS plugins don't work. But at least we now have support for ~16 lexers without any added weight to the JS bundles. 

The other thing to keep in mind is that there are huge advantages of treating the snippet code as plain text. For example, we could run automation on it and do things like auto-format based on Prettier. If the snippet code now also contains formatting, that might make things much harder. 
Similarly, when I code in VS Code, to type code comments my only formatting is to use `*` or similar characters to create emphasis or padding.

2021-04-30 17:18 UTC, closed without merging