Glossary - bunch of prep for markdown conversion
mdn/content pull request #8590
Opened 2021-09-03 07:04 UTC by hamishwillee

This PR fixes up HTML to ease conversion to markdown. It is not complete:
- Fixes up notes
- Removes about half the instances of seosummary
- Removes style markup in images and text.

@wbamberg et al, there is no consistency in Glossary sidebar. As there is no sidebar macro, my proposal is that we use this macro as a proxy for that - essentially listing all glossary entries: `<div>{{QuickLinksWithSubpages("/en-us/docs/Glossary")}}</div>` - thoughts?

2021-09-03 08:13 UTC, teoli2003 requested changes

2021-09-03 08:13 UTC, teoli2003 commented on files/en-us/glossary/site/index.html
> +    </ul>
A newline is missing here

2021-09-03 08:13 UTC, teoli2003 commented on files/en-us/glossary/index.html
> +
Github says that a newline is missing here.

2021-09-03 08:13 UTC, teoli2003 commented on files/en-us/glossary/index.html
> +<p>Glossary terms can be selected from the sidebar.</p>
On mobile, there are no sidebars, it is below the main text. How could we formulate this in a more neutral way?

2021-09-03 08:17 UTC, teoli2003 commented
> There is no consistency in Glossary sidebar. As there is no sidebar macro, my proposal is that we use this macro as a proxy for that - essentially listing all glossary entries: `<div>{{QuickLinksWithSubpages("/en-us/docs/Glossary")}}</div>` - thoughts?
Pro:
- unified
- even without macros, easy to update (find/replace)
- always up-to-date
Minus:
- Very long sidebar

I can live with it until we revisit all sidebars, with one change: some pages have related pages that display in the sidebar, they should be moved back to the main article (_See also_/_Learn more_/_Whatever_ section)

2021-09-06 01:09 UTC, hamishwillee commented on files/en-us/glossary/index.html
> +<p>Glossary terms can be selected from the sidebar.</p>
Good point - from the menu:

```suggestion
<p>Glossary terms can be selected from the menu.</p>
```

2021-09-06 01:18 UTC, hamishwillee commented
@teoli2003 Thanks very much for the review. I've tidied the indicated cases.

Re the sidebar question, perhaps the best approach is to simply defer this to Yari and build the sidebar based on file location. I'll raise a separate issue for discussion.

With respect to ..

> with one change: some pages have related pages that display in the sidebar, they should be moved back to the main article (See also/Learn more/Whatever section)

Yes. Plan is to make those a "See Also" but not in this iteration .

2021-09-06 04:48 UTC, teoli2003 approved these changes

2021-09-06 04:49 UTC, teoli2003 commented
Thanks

2021-09-06 04:49 UTC, merged

2021-09-11 04:31 UTC, hamishwillee commented
@teoli2003 FYI only, the plan is for this sidebar to be auto-generated by Yari. So I won't be manually adding it.