add missing <head> tag and rearrange closing tag
mdn/content pull request #8667
Opened 2021-09-05 15:37 UTC by AnilSeervi

2021-09-05 17:19 UTC, wbamberg commented
Thanks for this PR!

Would you like to try converting it into a [live sample](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples)? This would make the page much more useful IMO.

It would involve:

* splitting up that HTML code block into three parts: HTML, CSS, JavaScript, and placing each part under an H3 heading under the existing "Example" H2. The HTML part only needs to include the content of the `<body>`.

* Adding a fourth H3, "Result" and under that adding a line like: `{{EmbedLiveSample("Example", "100", "300""}}` (you might want to experiment with the third parameter, which sets the iframe height).

I think this would make the page much more useful!

For the next level improvement, rather than using `console.log()` for output, the example might write the output into a part of the iframe (like a `<div>` underneath the drop zone, say) - then readers would be able to see the output without needing the devtools open.

2021-09-05 17:22 UTC, AnilSeervi commented
> Thanks for this PR!
> 
> Would you like to try converting it into a [live sample](https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples)? This would make the page much more useful IMO.
> 
> It would involve:
> 
> * splitting up that HTML code block into three parts: HTML, CSS, JavaScript, and placing each part under an H3 heading under the existing "Example" H2. The HTML part only needs to include the content of the `<body>`.
> 
> * Adding a fourth H3, "Result" and under that adding a line like: `{{EmbedLiveSample("Example", "100", "300""}}` (you might want to experiment with the third parameter, which sets the iframe height).
> 
> I think this would make the page much more useful!
> 
> For the next level improvement, rather than using `console.log()` for output, the example might write the output into a part of the iframe (like a `<div>` underneath the drop zone, say) - then readers would be able to see the output without needing the devtools open.
> 
> 
> 

Will try converting it to the liveSample.

2021-09-05 17:26 UTC, wbamberg commented
Oh, I forgot. Here's an example of a page that contains a live sample: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event#live_example . This one doesn't include CSS, and personally I would use "JavaScript" as the heading text rather than "JS", but otherwise it's a reasonable one to copy :).

2021-09-05 17:49 UTC, wbamberg commented
Also, predictably, all the related events use similar examples:

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrag
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragend
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragleave
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragover
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragstart
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrop

These should all be live samples. But if this is too big a task for you now, let me know and I'll file a bug. Or file one yourself if you prefer :).

2021-09-05 17:53 UTC, AnilSeervi commented
Thank you. I'll attempt converting the example to livesample for this page first and then have the same replaced in other pages you've mentioned accordingly.

2021-09-05 17:58 UTC, AnilSeervi commented
> Also, predictably, all the related events use similar examples:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrag
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragend
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragleave
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragover
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondragstart
> https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondrop
> 
> These should all be live samples. But if this is too big a task for you now, let me know and I'll file a bug. Or file one yourself if you prefer :).
> 

You may file the bug and assign it to me. I'll work on it.

2021-09-05 17:59 UTC, wbamberg commented
> Thank you. I'll attempt converting the example to livesample for this page first and then have the same replaced in other pages you've mentioned accordingly.

That sounds like a great plan :).

2021-09-06 15:25 UTC, AnilSeervi commented
@wbamberg, does this look good?

2021-09-06 18:25 UTC, wbamberg requested changes
Thanks @AnilSeervi , this is so much better!

I had some code style suggestions, please ask if any of them don't make sense to you :).

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +<pre class="brush: html">&lt;div&gt;
We should be able to remove this outer `<div>`.

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +&lt;h1&gt;Examples of &lt;code&gt;ondragenter&lt;/code&gt;, &lt;code&gt;ondragleave&lt;/code&gt;, &lt;code&gt;ondragend&lt;/code&gt;&lt;/h1&gt;
We should also be able to remove this heading - the content of the example is clear from the context.

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +   &lt;p id="source" ondragstart="dragstart_handler(event);" draggable="true"&gt;
Rather than assigning event handler in the HTML, it would be better to have them all in the JavaScript (as we already do for more of them).

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> + &lt;div id="target" ondrop="drop_handler(event);" ondragover="dragover_handler(event);"&gt;Drop Zone&lt;/div&gt;
Also here it would be better to use the JavaScript to add event handlers.

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +&lt;textarea readonly class="event-log"&gt;&lt;/textarea&gt;</pre>
I would use an ID for this, not a class, like `id="event-log"`, since there can be only one of them.

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +</pre>
Consider refactoring this CSS so the boxes line up properly and to simplify it. Something like:

```css
div, .event-log{
    margin: 1em;
}

#source, #target {
    padding: 2em;
    border: 1px solid black;
}

#source {
    color: blue;
}

.event-log {
    width: 25rem;
    height: 4rem;
    padding: .2rem;
}
```

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> + event_log.textContent += "dragStart\n";
We should ident by more than one space - 2 or 4 (but the CSS uses 4, so maybe be consistent with that?).

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> + var el = document.getElementById("source");
Here and above as well, let's use `const` rather than `var`.

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +   &lt;p id="source" ondragstart="dragstart_handler(event);" draggable="true"&gt;
(See https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#inline_event_handlers_%E2%80%94_dont_use_these )

2021-09-06 18:25 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
>   el.ondragenter = dragenter_handler;
Consider using `addEventListener` here instead (see https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#adding_and_removing_event_handlers )

2021-09-06 18:28 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +</pre>
Also please check the indentation above (in particular the closing brace should line up with the start of the line containing the opening brace, like:

```css
selector {
    property: value;
}                       /* <---- line this up with the start of the rule. */
```

2021-09-06 18:55 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
>   el.ondragenter = dragenter_handler;
Perhaps also consider having a button called "Reload" or something, with an event handler like:

```js
 const button = document.querySelector("button");
 button.addEventListener("click", () => {
   document.location.reload();
 });
```

...then people can play it again without having to reload the page.

2021-09-10 02:30 UTC, wbamberg commented
@AnilSeervi , please let me know if you think you will get to this in the next couple of days. I'm sorry to nag, but I'm planning to convert all the Web/API docs into Markdown early next week, and would like to close as many PRs as possible beforehand. If you won't have time no worries - I could finish it myself.

2021-09-10 13:26 UTC, AnilSeervi commented
> 
> 
> @AnilSeervi , please let me know if you think you will get to this in the next couple of days. I'm sorry to nag, but I'm planning to convert all the Web/API docs into Markdown early next week, and would like to close as many PRs as possible beforehand. If you won't have time no worries - I could finish it myself.

Sorry, I got busy. I'll make the changes right now.

2021-09-10 14:12 UTC, AnilSeervi commented
I'm yet to add a reload/restart button to revert the drag. I was thinking, is there a way to just reload/refresh the iframe so that the example will be in its initial state again?

2021-09-10 15:32 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +const button = document.querySelector("#reload");
```suggestion
const button = document.getElementById("reload");
```

Consistently use either `getElementById` or `querySelector` (sorry this is my fault).

2021-09-10 15:33 UTC, wbamberg commented on files/en-us/web/api/globaleventhandlers/ondragenter/index.html
> +    document.location.reload();
```suggestion
  document.location.reload();
```

Consistent 2-apace indentation.

2021-09-10 15:36 UTC, wbamberg approved these changes
@AnilSeervi thanks for all your work on this! It's a **big** improvement to the page.

2021-09-10 15:36 UTC, merged

2021-09-10 15:38 UTC, AnilSeervi commented
No problem.
What about the other pages that use the same but slightly altered examples. Should they be also changed to live samples before conversion to markdown?.

2021-09-10 15:46 UTC, wbamberg commented
They don't need to be fixed before the conversion, no. We can do it afterwards.

What we really want is to minimise the number of PRs against Web/API that are open at the time we convert (hopefully this Tuesday: https://github.com/mdn/content/issues/8741), as they will have to be redone.

2021-09-10 16:03 UTC, AnilSeervi commented
> 
> 
> They don't need to be fixed before the conversion, no. We can do it afterwards.
> 
> What we really want is to minimise the number of PRs against Web/API that are open at the time we convert (hopefully this Tuesday: #8741), as they will have to be redone.

Sure. Will work on it after they are converted.

I should have changed the PR title before it was merged.