Add pages for URLPattern API
mdn/content pull request #8734
Opened 2021-09-07 22:17 UTC by lucacasonato

This commit adds documentation pages for the URLPattern interface.

This API is shipping in Chrome 95 and Deno 1.15. It is available behind
flags in Chrome 93 and Deno 1.14.

cc @wanderview

2021-09-07 23:38 UTC, wanderview commented
Note, we have some mdn docs written and staged for mdn.  See:

https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md

Its mostly code examples.  Cc @jpmedley

2021-09-07 23:42 UTC, lucacasonato commented
Ah, perfect. I'll integrate these here.

2021-09-07 23:43 UTC, wanderview commented
Ok.  I'm not sure I'm of the mdn process.  @jpmedley was heavily involved with what I linked above.

2021-09-08 04:44 UTC, sideshowbarker commented
> Ah, perfect. I'll integrate these here.

I guess I’ll wait to review until those have been integrated

2021-09-08 10:09 UTC, lucacasonato commented
Examples have been integrated now.

2021-09-08 16:22 UTC, wanderview commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
I'm not sure this part is quite right.  Fixed text in curly braces, like `{foo}`, could be called a non-capturing group.  But you can also put a capturing group within the curly braces.  For example, `{:name}`.  What's more, you can include a prefix and suffix around the capturing group, like `{file_:type.jpg}`.  This can be useful for when you want to repeat the prefix/suffix.  For example, in hostnames you can do `{:sub.}*example.com` that will capture any subdomains of example.com.

I'm not sure if its described elsewhere in this doc yet, but without the curly braces you sometimes get a default prefix value.  This only happens in pathname and if the preceding character is `/`.  This enables code like `/foo/:details*/index.html` to match both `/foo/index.html` and `foo/bar/baz/index.html`.

2021-09-08 16:22 UTC, wanderview commented on files/en-us/web/api/urlpattern/index.html
> +  can be placed anywhere in the pattern.
I'm not sure if its worth mentioning, but `*` is a greedy match that matches as many characters as possible.

2021-09-08 16:22 UTC, wanderview commented on files/en-us/web/api/urlpattern/index.html
> +  other parts, the group will match all characters.
I'm not sure if its worth mentioning, but the segment wildcard is a non-greedy match matching as few characters as possible.

2021-09-08 16:23 UTC, wanderview commented
Overall, this looks great!  Thanks so much for writing it!  I just had a few comments on the main doc describing the pattern syntax.

2021-09-08 21:04 UTC, jpmedley requested changes
Thank you for your submission.

The number of requested changes probably looks scary. I think your writing skills are solid. The bulk of these requests are for making your submission consistent with current MDN practice. This is a difficult target to hit, we know. There are many out of date pages on MDN and we're a bit behind on updating our writer reference.

Let me know if you have questions. I'm here to help.

Thanks for your patience.

2021-09-08 21:04 UTC, jpmedley commented on files/en-us/web/api/urlpattern/username/index.html
> +  the pattern used to match the username part of a URL. This value may be differ
```suggestion
  the pattern used to match the username part of a URL. This value may differ
```

2021-09-08 21:04 UTC, jpmedley commented on files/en-us/web/api/urlpattern/username/index.html
> +<h3 id="Value">Value</h3>
```suggestion
<h2 id="Value">Value</h3>
```

2021-09-08 21:04 UTC, jpmedley commented on files/en-us/web/api/urlpattern/username/index.html
> +</ul>
```suggestion
```

2021-09-08 21:25 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.html
> +<h2 id="Pattern_syntax">Pattern syntax</h2>
Might it make sense to break out the syntax reference into a seperate page in the API guides section?

2021-09-08 22:09 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
I'll integrate this. Do these things I called "non capturing groups" have a real name? Sub-patterns would sorta make sense to me.

2021-09-08 22:33 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
Renamed to "sub-patterns" until we have a better name.

Also added a section on automatic group prefixing in pathnames, and explained how sub-patterns can be used to disable the behaviour.

2021-09-08 22:35 UTC, lucacasonato commented
Pending tasks:

- [ ] Decide if "Pattern syntax" section should be moved to its own page (in "API Guides")?
- [ ] Decide if "sub-pattern" is the right name for the thing I previously referred to as "non-capturing groups"

2021-09-09 13:52 UTC, jpmedley requested changes

2021-09-09 13:52 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.html
> +<h2 id="Pattern_syntax">Pattern syntax</h2>
@ddbeck Thoughts?

2021-09-09 13:53 UTC, jpmedley commented
>Decide if "sub-pattern" is the right name for the thing I previously referred to as "non-capturing groups"

@jeffposnick What do you think?

2021-09-09 14:02 UTC, wanderview commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
> Do these things I called "non capturing groups" have a real name? 

The path-to-regexp docs just list it under "custom prefix and suffix".

In the spec we call the curly braces a group "open" and "close".  That is probably the most exact what to describe this.  Without curly braces you get implicit open/close around `*`, `:foo`, `(foo)`, etc.  You can use curly braces to explicitly set the group open/close to select your prefix/suffix.

And then you can set an open/close around plain text without a group if you want to apply a modifier like `?`, etc, to it.  That could be called a non-capturing group.

I must admit I don't really like "sub-patterns" as it seems to imply some kind of nesting of patterns which I don't think is really the case here.

2021-09-09 14:05 UTC, wanderview commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
What about "explicit grouping"?

@blakeembrey, @domenic, @jeffposnick, any naming suggestions here for `{ }` syntax?

2021-09-09 15:02 UTC, jeffposnick commented on files/en-us/web/api/urlpattern/index.html
> +  pieces of a pattern that are surrounded by curly braces (<code>{}</code>).
Maybe "group delimiters" would work?

2021-09-09 22:54 UTC, wbamberg commented
@lucacasonato , we're just on the cusp of converting all the Web/API docs to Markdown. I'm hoping we'll be able to do this early next week (Monday/Tuesday).

Because this PR contains only new pages, this PR won't be broken by the change. However, unless it gets merged in the next day or so, these pages will need to be converted to Markdown before the PR can be merged.

It's probably a good idea to wait until all the content reviews are done before converting though.

## How to convert to Markdown

Yari provides a command-line tool to convert from HTML to Markdown.

To run the tool, first clone mdn/yari. As the [quickstart](https://github.com/mdn/yari/#quickstart) describes, set the `CONTENT_ROOT` variable to point to your mdn/content, then from your Yari clone run:

```
yarn
yarn dev
```

...then once `yarn dev` has finished building stuff, cancel the `yarn dev` process and run:

```
yarn md h2m web/api/urlpattern --mode=replace
```

This will convert web/api/urlpattern and everything under that to Markdown.

It will generate a report with a name like "md-conversion-problems-report-2021-09-09T17/59/58.011Z.md" complaining about all the things that couldn't be converted. Ideally there won't be anything, although there are some HTML elements we're choosing not to convert.

If you have any problems let me know. Or if you would like me to convert instead, let me know and I could push the changed files to your PR here.

2021-09-15 11:01 UTC, lucacasonato commented
@wbamberg Markdown conversion done. Only challenge was a unordered list inside of a table. See files/en-us/web/api/urlpattern/urlpattern/index.md line 45.

2021-09-15 15:18 UTC, jpmedley requested changes
Apologies. It's rare that I request multiple rounds of changes. This is just one quick one to match what's done elsewhere.

2021-09-15 15:18 UTC, jpmedley commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +| Exception               | Explanation
```suggestion
| Exception               | Description                                                                                                                                                                                                                  |
```

2021-09-15 15:18 UTC, jpmedley commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +| Exception               | Explanation
This is the most common way this is currently done.

2021-09-15 15:27 UTC, wbamberg commented
Nice, thanks!

> @wbamberg Markdown conversion done. Only challenge was a unordered list inside of a table. See files/en-us/web/api/urlpattern/urlpattern/index.md line 45.

In this case the whole table should stay as HTML. It won't be readable in GFM.

2021-09-16 18:18 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +| Exception               | Explanation
Changed the table back to HTML as @wbamberg suggested below.

2021-09-16 18:49 UTC, wbamberg commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +| Exception               | Explanation
Sorry if I wasn't clear. This commit: https://github.com/lucacasonato/content/commit/31c17d8cdf8b27bd0d3f7b42416900e0777e3a25 changes from a GFM table to an HTML `<dl>`.

The first question here is: **which structure should we use on MDN for exceptions, a `<table>` or a `<dl>`?** The original PR used a table, and checking the first example under https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#examples I saw it used a table, so I thought that was correct.

But looking the actual page template uses `<dl>`: https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_constructor_subpage_template. So `<dl>` is probably correct.

(FWIW I think we should use `<dl>`).

**If we use `<dl>`**, then we should use Markdown for it, because our Markdown `<dl>` syntax supports nested lists.

The syntax would be:

```
- {{jsxref("TypeError")}}
  - : Indicates one of the following:
    - The given pattern or base URL is not valid or syntactically correct.
    - A `baseURL` is provided, and input is an absolute pattern or a structured object.
```

2021-09-16 19:26 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +| Exception               | Explanation
Ok - updated. I originally had based it off api/url/url/index.md, which uses a markdown table. That should probably be changed to a `<dl>` too.

2021-09-20 12:26 UTC, crowlKats commented on files/en-us/web/api/urlpattern/index.md
> +const result = pattern.exec("/fo'/bar', 'https://example.com/baz');
```suggestion
const result = pattern.exec('/foo/bar', 'https://example.com/baz');
```

2021-09-21 15:41 UTC, jpmedley requested changes

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +If you do not want this automatic prefixing, you can disable it by surrounding
```suggestion
If you do not want automatic prefixing, you can disable it by surrounding
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +the group with a group delimiters (`{}`). Group delimiters do not have automatic
```suggestion
the it with a group delimiters (`{}`). Group delimiters do not have automatic
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +### Wildcard token
```suggestion
### Wildcard tokens
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +more times is provided by the wildcard token (`*`). This can be can be placed
```suggestion
The wildcard token (`*`) is a shorthand for an unnamed capturing group that
matches all characters zero or more times. You can place this
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a `URLPattern` can be constructed from a full
```suggestion
The following example shows how to construct a `URLPattern` from a full
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +URL string with patterns embedded. For example, a `:` can be both the URL
```suggestion
URL string with embedded patterns. For example, a `:` can be both the URL
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +URL syntax or part of the pattern syntax then it just works.
```suggestion
`:foo`. It works if there is no ambiguity between whether a character is
part of the URL syntax or part of the pattern syntax.
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a URLPattern constructed from an ambiguous
```suggestion
The following example shows how a `URLPattern` constructed from an ambiguous
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +base URLs.
```suggestion
The following example shows how `test()` and `exec()` can use base URLs.
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +`URLPattern`. It's important to note that the base URL in these cases is treated
```suggestion
`URLPattern`. Note that the base URL in these cases is treated
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +`URLPattern` will also have a value for every component; even if it's the empty
```suggestion
`URLPattern` will also have a value for every component, even if it's the empty
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a custom regular expression can be used with a
```suggestion
The following example shows how to use a custom regular expression with a
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made optional by placing
```suggestion
The following example shows how to make a matching group optional by placing
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made repeated by placing
```suggestion
The following example shows how to repeat a matching group by placing
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made both optional and
```suggestion
The following example shows how to use a matching group to be both optional and
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +repeated. This is done by placing a `*` modifier after the group. Again, the
```suggestion
repeated. Do this by placing a `*` modifier after the group. Again, the
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/index.md
> +a matching group can be made optional or repeated without a matching group.
Please look at this sentence again. The second highlighted line doesn't make sense.

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/test/index.md
> +  - : The URL or URL parts that the matcher will match against. This can either
```suggestion
  - : The URL or URL parts to match against. This can either
```

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +    Omitted parts in the object will be treated as wildcards (`*`).
@jeffposnick Does this apply to `test()` as well?

2021-09-21 15:41 UTC, jpmedley commented on files/en-us/web/api/urlpattern/username/index.md
> +`admin` for the `username` part. This pattern matches only if the username part
```suggestion
The below example creates a {{domxref("URLPattern")}} object with
`admin` for the `username`. This pattern matches only if the username part
```

2021-09-23 09:52 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +The **`URLPattern`** interface matches URLs or parts of URLs against a pattern.
I don't think so. Contacts picker is not centralised in a single interface like URLPattern is.

2021-09-23 09:53 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +The **`URLPattern`** interface matches URLs or parts of URLs against a pattern.
I retract that statement - I'll add an overview page, because the URLPattern syntax will eventually also be used in service workers.

2021-09-23 10:00 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +match if it contains one or more digits:
This does not make sense I think. The meaning is changed.

2021-09-23 10:06 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made repeated by placing
This changes meaning. How about:
> The following example shows how to make a matching group repeating

2021-09-23 10:08 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made repeated by placing
Actually, the original text is the only correct one. You are not repeating the group, but you are setting the "repeated" modifier on the group.

2021-09-23 10:09 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/index.md
> +The following example shows how a matching group can be made both optional and
Changes meaning again. Updated to

> The following example shows how to make a matching group that is both optional and repeated

2021-09-23 10:13 UTC, lucacasonato commented on files/en-us/web/api/urlpattern/urlpattern/index.md
> +    Omitted parts in the object will be treated as wildcards (`*`).
Nope.

2021-09-23 11:12 UTC, lucacasonato commented
@jpmedley I have split out the examples and pattern syntax into a new "URL Pattern API" page.

2021-09-24 13:28 UTC, jpmedley approved these changes

2021-09-24 13:28 UTC, merged

2021-09-24 13:28 UTC, jpmedley commented
Thank you for your help.

2021-09-24 13:31 UTC, lucacasonato commented
Thanks for seeing this through!