feat: add Info properties to Intl.Locale (Calendars)
mdn/content pull request #8768
Opened 2021-09-09 10:40 UTC by romulocintra

Add Info properties to Intl.Locale

Related issue : tc39/ecma402-mdn#21

This breaks down #5197  into small parts with (Main Page Link + Minimal Valuable Page for the Option and Browser Compat data PR )

2021-09-10 09:57 UTC, teoli2003 requested changes, later dismissed
That looks quite good already, a small change and a table to transform to a definition list are all I see that needs to be changed.

Thaanks!

2021-09-10 09:57 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +The `calendar` property returns a list of all supported calendars for the  `Locale`  all list items indicates the `Locale`'s calendar era. The following table shows all the valid Unicode calendar key
Two extra spaces, and I don't like _'s_ after code-like phrase. I propose:
```suggestion
The `calendar` property returns a list of all supported calendars for the `Locale` all list items indicates the `Locale` object's calendar era. The following table shows all the valid Unicode calendar key strings, along with a description of the calendar era they represent.
```

2021-09-10 09:57 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
A table is not a good structure for this, a definition list is much better. We use an extension of Github Markdown for these ([documentation](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#definition_lists))

So basically:
```
* `buddhist`
    * : Thai Buddhist calendar
* `chinese`
    * : Traditional Chinese calendar
[…]
```

2021-09-10 10:19 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
This table is a copy from https://github.com/mdn/content/blob/cc6d65453242d60e746579de4cecd6892cee57d3/files/en-us/web/javascript/reference/global_objects/intl/locale/calendar/index.md, should both be updated?

2021-09-10 10:22 UTC, teoli2003 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
Yes, please.

2021-09-13 10:14 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
Not questioning but only giving suggestions, IMHO feels more readable and saw it in several places like [Intl.Locale.prototype.numberingSystem
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystem)

![image](https://user-images.githubusercontent.com/1572026/133066044-7a38b317-ba07-4e72-b4b5-8454a6326c2a.png)


Aside from that how I can add those warnings using the list 

![image](https://user-images.githubusercontent.com/1572026/133066147-bd7b17dd-540d-46e4-9922-edbcdc62657c.png)

2021-09-16 09:26 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
The same happens here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/collation
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/hourCycle
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/numberingSystem

Those pages I need to replicate to add documentation for finish the Locale Info

2021-09-16 16:21 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
Hi!

It seems like there are maybe three questions in here, and I'm not sure which is the one I am being asked :).

**1) how can I represent those warnings using the list syntax?**

You can include block elements including warning boxes in list items:

```
- a term
  - : a description of the term
    > **Warning:** It can contain warnings

- another term
   - : another description
 ```

...although in this particular case I might prefer to have a separate section "deprecated collation types" or something, rather than using a warning note.

**2) should we use tables rather than `<dl>`?**

It's **very** conventional on MDN to use `<dl>` for things like the value that a property can take. Consistency is really important for reference docs, so if we want to talk about using tables instead that should be a whole MDN-wide conversation (and honestly I don't think it would get far). We should not even consider doing something different in some small set of cases just because it feels nicer there. Or perhaps I misunderstand this question?

**3) how can we include the same content in multiple places in MDN?**

This is tricky! We have a macro for this  called [`{{page}}`](https://github.com/mdn/yari/blob/main/kumascript/macros/page.ejs). I think this should still work in Markdown (except that you can in general only refer to ID attributes that are generated from headings).

But `{{page}}` is problematic for a couple of reasons. First the implementation is very tricky because it introduces a build dependency between different pages in the site. Second, when used ad hoc it is also  hard to maintain, because the "source" text doesn't know where it is being embedded (or even that it is being embedded at all) so it's very easy for maintainers of the source text to make changes that destroy the meaning of the text in its embedded context.

So we would really like to deprecate the general use of `{{page}}`. Unfortunately though, there is a real use case for it as you point out, and duplicating content across many pages is also bad for maintainability. If possible I like to use links for this, but that's not always possible. I wonder if eventually we might get a more controlled version of `{{page}}`, where the source texts are explicitly identified as fragments (rather than just being normal parts of normal pages). But that seems a long way off.

2021-09-17 07:40 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
First thanks for your feedback, regarding this :

> **2) should we use tables rather than `<dl>`?**
> 
> It's **very** conventional on MDN to use `<dl>` for things like the list of values that a property can take. Consistency is really important for reference docs, so if we want to talk about using tables instead that should be a whole MDN-wide conversation (and honestly I don't think it would get far). We should not even consider doing something different in some small set of cases just because it feels nicer there. Or perhaps I misunderstand this question?
> 

My point is that the table syntax is used all over those documents that I'm only duplicating to a new page, if the intention is to have consistency by using `<dl>` where previously we used tables I understand but is a different effort that I wanted to clarify.  Thanks

2021-09-22 09:54 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +<table class="standard-table">
Updated the PR, thanks for clarifying

2021-09-28 09:38 UTC, Elchi3 requested changes
Thanks @romulocintra, some nits and then should be good to go

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendar/index.md
> +    > **Warning:** The islamicc calendar key has been deprecated. Please use islamic-civil.
```suggestion
    > **Warning:** The `islamicc` calendar key has been deprecated. Please use `islamic-civil`.
```

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +The **`Intl.Locale.prototype.calendars`** property is an accessor property which returns a list of 1 or more unique calendar identifiers for the `Locale`.
```suggestion
The **`Intl.Locale.prototype.calendars`** property is an accessor property which returns an array of one or more unique calendar identifiers for the `Locale`.
```

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +The `calendar` property returns a list of all supported calendars for the `Locale` all list items indicates the `Locale` object's calendar era. The following table shows all the valid Unicode calenda
```suggestion
The `calendar` property returns an array of all supported calendars for the `Locale`. The array items indicate the `Locale` object's calendar era. The following table shows all valid Unicode calendar key strings, along with a description of the calendar era they represent.
```

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +    > **Warning:** The islamicc calendar key has been deprecated. Please use islamic-civil.
```suggestion
    > **Warning:** The `islamicc` calendar key has been deprecated. Please use `islamic-civil`.
```

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +console.log(arEG.calendars); // Prints ["gregory", "coptic", "islamic", "islamic-civil", "islamic-tbla"
```suggestion
console.log(arEG.calendars); // logs ["gregory", "coptic", "islamic", "islamic-civil", "islamic-tbla"]
```

2021-09-28 09:38 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/calendars/index.md
> +console.log(jaJP.calendars); // Prints ["gregory", "japanese"]
```suggestion
console.log(jaJP.calendars); // logs ["gregory", "japanese"]
```

2021-09-28 09:41 UTC, Elchi3 approved these changes
Thanks! 👍

2021-09-28 09:45 UTC, merged