WebCodecs API Overview page.
mdn/content pull request #8802
Opened 2021-09-10 09:48 UTC by rachelandrew

Adding the API overview for `WebCodecs`.

Reviewer: @jpmedley

2021-09-10 10:28 UTC, teoli2003 commented
Note that `GroupData.json` is now in mdn/content. I think it may be good to add the relevant entry in this very same PR (It allows to test/review the sidebars)

2021-09-10 13:29 UTC, rachelandrew commented
@teoli2003 is it ok to list interfaces in the GroupData file that are not written yet? I'm currently working through these, there are some in PR and some not done yet. I expect to finish them next week.

If not I'll do the PR for the file with the last of the interfaces.

2021-09-10 13:35 UTC, teoli2003 commented
It is ok (the sidebar macros are pretty resilient), but if you prefer to wait, just wait :-)

2021-09-10 16:16 UTC, jpmedley requested changes

2021-09-10 16:16 UTC, jpmedley commented on files/en-us/web/api/webcodecs_api/index.md
> +For example, the {{domxref("Web Audio API")}}, and {{domxref("WebRTC API")}}.
```suggestion
For example, the {{domxref("Web Audio API")}}, and the {{domxref("WebRTC API")}}.
```

2021-09-10 16:16 UTC, jpmedley commented on files/en-us/web/api/webcodecs_api/index.md
> +reduced performance and power efficiency, and an additional development overhead.
```suggestion
reducing performance and power efficiency, and adding additional development overhead.
```

2021-09-10 16:16 UTC, jpmedley commented on files/en-us/web/api/webcodecs_api/index.md
> +In the following example frames are returned from a {{domxref("MediaStreamTrackProcessor")}}, then encoded.
```suggestion
In the following example, frames are returned from a {{domxref("MediaStreamTrackProcessor")}}, then encoded.
```

2021-09-14 08:12 UTC, rachelandrew commented
> It is ok (the sidebar macros are pretty resilient), but if you prefer to wait, just wait :-)

that's added now.

2021-09-14 14:12 UTC, jpmedley approved these changes

2021-09-15 05:25 UTC, merged