Document XRWebGLLayer.fixedFoveation
mdn/content pull request #8823
Opened 2021-09-10 17:35 UTC by Elchi3

Spec: https://immersive-web.github.io/webxr/#dom-xrwebgllayer-fixedfoveation

2021-09-13 18:12 UTC, jpmedley requested changes

2021-09-13 18:12 UTC, jpmedley commented on files/en-us/web/api/xrwebgllayer/fixedfoveation/index.md
> +If the user agent or device does not support the `fixedFoveation` property at all, it is {{jsxref("null")}} on getting and a no-op on setting.
I might expect `null` if the API is present, but not supported by the device. I would expect `undefined` if the UA doesn't have the API. Am I missing something?

2021-09-14 00:41 UTC, dominiccooney commented on files/en-us/web/api/xrwebgllayer/fixedfoveation/index.md
> +If the user agent or device does not support the `fixedFoveation` property at all, it is {{jsxref("null")}} on getting and a no-op on setting.
I had the same gut reaction to this. There might be better phrasing than "support" and maybe moderate "at all." The situation is:
- Any UA which implements XRWebGLLayer (spec talk:) *must* (plain English, pragmatist:) *should* have this property.
- Some drivers/devices/UAs don't do anything useful with the property. Then it has the value `null` (and this is exactly how WebIDL `float?` works) and setting it is a no-op.

So how about:

> Some devices don't support foveated rendering. In that case `fixedFoveation` is {{jsxref("null")}} and setting it will not do anything.

2021-09-14 00:56 UTC, jpmedley commented on files/en-us/web/api/xrwebgllayer/fixedfoveation/index.md
> +If the user agent or device does not support the `fixedFoveation` property at all, it is {{jsxref("null")}} on getting and a no-op on setting.
"This property is `undefined` if the API is not supported by the user agent and `null` if it is supported by the user agent, but not by the underlying operating system or hardware."

I'm not crazy about the word 'no-op'. Explaining when both 'undefined' and 'null' are returned is more precise.

2021-09-14 09:41 UTC, Elchi3 commented on files/en-us/web/api/xrwebgllayer/fixedfoveation/index.md
> +If the user agent or device does not support the `fixedFoveation` property at all, it is {{jsxref("null")}} on getting and a no-op on setting.
Thanks, went with Dominic's suggestion which is what the spec says but worded a lot better.

2021-09-16 14:23 UTC, jpmedley approved these changes

2021-09-16 14:23 UTC, merged