Fixes #1172 - moves links out of headings
mdn/content pull request #8842
Opened 2021-09-11 12:54 UTC by himanshugarg

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #1172

> What was wrong/why is this fix needed? (quick summary only)

The links inside headings broke permalinks to the headings

> Anything else that could help us review it

No. Thanks.

2021-09-12 06:47 UTC, teoli2003 requested changes

2021-09-12 06:47 UTC, teoli2003 commented on files/en-us/web/accessibility/seizure_disorders/index.html
> +<h6 id="light-level">light-level</h6>
Rather than `<h6>`, I would use a `<dl>` here (that allows linking).

I would even remove the `<h5>` (the _unique_ subheading of this `<h4>`) and transform it into text.

2021-09-12 06:47 UTC, teoli2003 commented on files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
> +<h4 id="manifest.json_2">manifest.json</h4>
I think a `<dl>` would be better than `<h4>` in this file.

2021-09-12 06:47 UTC, teoli2003 commented on files/en-us/mozilla/add-ons/webextensions/chrome_incompatibilities/index.html
> +<h4 id="notifications">notifications</h4>
I think a `<dl>` would be better than `<h4>` in this file.

2021-09-12 06:47 UTC, teoli2003 commented on files/en-us/web/svg/attribute/index.html
> +<h4 id="Core_attributes">Core attributes</h4>
In this file, I think `<h4>` (even without links) would also render better as `<dl>`.

2021-09-12 07:41 UTC, himanshugarg commented
Will resolve. Thanks for reviewing

2021-09-12 23:54 UTC, himanshugarg commented on files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
> +<h4 id="manifest.json_2">manifest.json</h4>
Sure. I'll go ahead and update the others on this page for consistency and a cleaner look.

2021-09-13 01:17 UTC, himanshugarg commented on files/en-us/web/accessibility/seizure_disorders/index.html
> +<h6 id="light-level">light-level</h6>
Done

2021-09-13 17:31 UTC, rebloor requested changes

2021-09-13 17:31 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
> +    <p><a href="https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json">manifest.json</a></p>
Rather than adding this slightly awkward additional line, in most cases there are references provided in the introductory paragraph where a link can be  e.g.
`<p>None of the functions require a permission to operate, so there are no features in the <code><a href="https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json">manifest.json</a></code> file that need to be highlighted.</p>`

Where a suitable reference doesn't exist, it should be accommodated by prefixing something e.g. in line 434 
`In <code><a href="https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json">manifest.json</a></code>, none of the zoom functions require permissions …` or similar.

2021-09-14 04:14 UTC, himanshugarg commented
Note, a lot of id's are gone. Hopefully that is not a problem because the permalinks never worked. But let me know if it is.

2021-09-14 17:19 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
> +    <p>None of the functions require a permission to operate, so there are no features in the <a href="https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json">manifest
I noticed that in some places where manifest.json, tabs.html, and tabs.js are mentioned in the text (not including headings), they are in plain text, whereas most occurrences are in code format. Code format would be the standard, so if you have a moment, could you standardize?

2021-09-14 17:20 UTC, rebloor approved these changes

2021-09-14 17:22 UTC, rebloor commented
@himanshugarg Please note: I am only approving in regard to the add-on file changes, please wait for all approvals.

2021-09-15 04:00 UTC, himanshugarg commented on files/en-us/mozilla/add-ons/webextensions/working_with_the_tabs_api/index.html
> +    <p>None of the functions require a permission to operate, so there are no features in the <a href="https://github.com/mdn/webextensions-examples/blob/master/tabs-tabs-tabs/manifest.json">manifest
Done. Thanks for your time on the review. Looks a lot better now.

2021-09-15 04:18 UTC, teoli2003 commented
@himanshugarg This is really nice. Can you make sure we don't have _dangling_ links in the other files too. Either by integrating the link in a sentence or by putting it on the definition term of the definition list?

2021-09-15 04:25 UTC, himanshugarg commented
> Can you make sure we don't have _dangling_ links in the other files too. Either by integrating the link in a sentence or by putting it on the definition term of the definition list?

Sure. You mean propagate the id's everywhere they haven't been propagated, right?

2021-09-15 04:38 UTC, teoli2003 commented
> > Can you make sure we don't have _dangling_ links in the other files too. Either by integrating the link in a sentence or by putting it on the definition term of the definition list?
> 
> Sure. You mean propagate the id's everywhere they haven't been propagated, right?

No, not having a link alone on a paragraph, especially where it is a copy of the text right above.

2021-09-15 12:46 UTC, himanshugarg commented
I have merged some more on one page, but some are still left in:-
1. https://pr8842.content.dev.mdn.mozit.cloud/en-US/docs/Web/Accessibility/Seizure_disorders
2. https://pr8842.content.dev.mdn.mozit.cloud/en-US/docs/Web/SVG/Attribute
3. https://pr8842.content.dev.mdn.mozit.cloud/en-US/docs/Web/XSLT/Transforming_XML_with_XSLT

2021-09-15 12:52 UTC, teoli2003 commented
These three pages have so many other problems, that these are not problematic. Given that @rebloor has approved the webextension-related pages, I will go and merge this.

2021-09-15 12:53 UTC, teoli2003 approved these changes

2021-09-15 12:53 UTC, merged

2021-09-15 12:53 UTC, teoli2003 commented
Thanks! These kinds of changes are far from obvious.

2021-09-15 13:45 UTC, himanshugarg commented
>These kinds of changes are far from obvious.

Yes wasn't as simple as I thought it to be. Next time, I will split the PR's to simplify the changes and reviews.