compareDocumentPosition: Add bit descriptions and move the table into Return value
mdn/content pull request #8865
Opened 2021-09-12 22:15 UTC by gibson042

An attempt to improve the page's clarity.

2021-09-12 22:32 UTC, hamishwillee commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
```suggestion
<pre class="brush: js">compareDocumentPosition(otherNode)
```
Syntax blocks now lose all the extra styling and return value. That means you'll need to revisit the description that refers to the bits that are removed.

FWIW this all looks like a step in the right direction.

2021-09-12 23:55 UTC, gibson042 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
The receiver is very relevant to understanding of this method's behavior, could we keep it as in the recently-modified [randomUUID](https://github.com/mdn/content/blob/2c5018d3cbc1c8880b303032eda6af38e8b1d24e/files/en-us/web/api/crypto/randomuuid/index.html#L24)?
```suggestion
<pre class="brush: js">node.compareDocumentPosition(otherNode)
```

2021-09-13 00:16 UTC, hamishwillee commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
I do understand why you want to do this, but there is also a lot to be said for consistent documentation formatting:
- There was much discussion on the content of the syntax block, and pretty much it resolved down to the syntax section on functions being used as an indication of the parameters, rather than the thing that the item is called on or the return type
- It is possible to discuss the method behaviour without relying on the syntax block having that `node.` prefix. 

@Elchi3 Would you care to comment?

2021-09-13 00:24 UTC, gibson042 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
Thank you. If it is indeed important that the receiver not be named in the syntax block, then I will make the changes (although I am curious about randomUUID being merged _with_ a named receiver just two days ago).

2021-09-13 00:47 UTC, hamishwillee commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
Different reviewers catch different things. I would not have approved that change without making the comment that it does not match the guidelines. You will find a heap of docs that have not yet been migrated to the new format.

I figured I'd wait on @Elchi3 to comment on how important this is for this case. I expect that we will have the general rule for 99% of cases but that doesn't mean there won't be cases where someone says "really, let's leave this alone"

2021-09-13 09:49 UTC, Elchi3 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +<pre class="brush: js"><em>compareMask</em> = <em>node</em>.compareDocumentPosition(<em>otherNode</em>)
The syntax section in this PR looks good to me (now). The docs on what we agreed are here, btw: https://developer.mozilla.org/en-US/docs/MDN/Structures/Syntax_sections

2021-09-13 09:49 UTC, Elchi3 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +  <li>{{DOMxRef("Node.contains()"}}</li>
I think the build fails because this is not a valid macro call.

```suggestion
  <li>{{DOMxRef("Node.contains()")}}</li>
```

2021-09-13 09:50 UTC, Elchi3 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +    {{JSxRef("Bitwise AND (&)","Bitwise AND operator (&)")}}
I don't think this call will work. Why change to a macro?

2021-09-13 11:56 UTC, teoli2003 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +  <li>{{DOMxRef("Node.contains()"}}</li>
Committing this so we can see the results of the tests and swiftly lands this once the last comment is fixed.

2021-09-13 13:04 UTC, gibson042 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +    {{JSxRef("Bitwise AND (&)","Bitwise AND operator (&)")}}
The \<a> approach was reported as a flaw.

2021-09-13 13:39 UTC, teoli2003 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +    {{JSxRef("Bitwise AND (&)","Bitwise AND operator (&)")}}
Ha! It was missing a Web/. That's why. We don't need to fix the URL now.

2021-09-13 13:42 UTC, teoli2003 requested changes
With the right way of doing it (sorry for the hurry, we need to get this landed quickly for a large conversion to start :-) )

2021-09-13 13:42 UTC, teoli2003 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +    {{JSxRef("Bitwise_AND","Bitwise AND operator (&)")}}
```suggestion
    <a href="/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators">bitwise AND operator</a>
```

2021-09-13 13:47 UTC, teoli2003 requested changes

2021-09-13 13:47 UTC, teoli2003 commented on files/en-us/web/api/node/comparedocumentposition/index.html
> +    <a href="/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators">bitwise AND operator</a>
```suggestion
    <a href="/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND">bitwise AND operator</a>
```

(Second attempt, sorry)

2021-09-13 13:48 UTC, teoli2003 approved these changes

2021-09-13 13:49 UTC, teoli2003 commented
I confirm, the flaw was a redirect to fix. We can merge this now.

2021-09-13 13:49 UTC, merged