New Web Background Sync documentation
mdn/content pull request #8905
Opened 2021-09-14 13:03 UTC by captainbrosset

This fixes #8904. A page about the `Web Background Sync` API was missing. This PR is adding it.

2021-09-14 16:21 UTC, sideshowbarker requested changes
1. I recognize that the spec title is “Web Background Synchronization”, but for consistency with how we handle other cases, we should drop the “Web” part in MDN — including in the `files/en-us/web/api/web_background_synchronization_api` directory name (so, would need to do a `git mv` on the branch.

2. The `files/en-us/web/api/serviceworkerglobalscope/index.html` changes are fine but in a couple of hours, that `index.html` isn’t going to exist in the repo any longer, so those changes will need to be replicated in the `index.md` source (so this PR branch will need to be rebased after the big markdown-conversion merge happens today

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +title: Web Background Synchronization API
```suggestion
title: Background Synchronization API
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +slug: Web/API/Web_Background_Synchronization_API
```suggestion
slug: Web/API/Background_Synchronization_API
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +The Web Background Synchronization API provides a way to defer tasks to be run in a {{domxref('Service Worker API','service worker')}} until the user has a stable network connection.
```suggestion
The Background Synchronization API provides a way to defer tasks to be run in a {{domxref('Service Worker API','service worker')}} until the user has a stable network connection.
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +## Web Background Synchronization Concepts and Usage</h2>
```suggestion
## Background Synchronization Concepts and Usage
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +> **Note:** At the time of writing, the Web Background Synchronization API is only available through an installed [Progressive Web App](/en-US/docs/Web/Progressive_web_apps)
```suggestion
> **Note:** At the time of writing, the Background Synchronization API is only available through an installed [Progressive Web App](/en-US/docs/Web/Progressive_web_apps)
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +## Web Background Synchronization Interfaces
```suggestion
## Background Synchronization Interfaces
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +  - : Registers tasks to be run in a service worker at a later time with network connectivity. These tasks are referred to as background sync requests.
```suggestion
  - : Registers tasks to be run in a service worker at a later time with network connectivity. These tasks are referred to as _background sync requests_.
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +  - : An event handler fired whenever a {{Event("sync")}} event occurs. This happens at timed intervals, that are specified when registering a {{domxref('SyncManager')}}.
```suggestion
  - : An event handler fired whenever a {{Event("sync")}} event occurs. This happens at timed intervals that are specified when registering a {{domxref('SyncManager')}}.
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +This code checks to see if a Background Sync task with a given tag is registered.
```suggestion
This code checks to see if a background-sync task with a given tag is registered.
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +### Listening for a Background Sync within a Service Worker
```suggestion
### Listening for a background sync within a Service Worker
```

2021-09-14 16:21 UTC, sideshowbarker commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +The following example shows how to respond to a background sync event in the service worker.
```suggestion
The following example shows how to respond to a background-sync event in the service worker.
```

2021-09-15 12:10 UTC, captainbrosset commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +  - : An event handler fired whenever a {{Event("sync")}} event occurs. This happens at timed intervals, that are specified when registering a {{domxref('SyncManager')}}.
This was actually the incorrect definition. I ended up changing the whole line.

2021-09-15 12:12 UTC, captainbrosset commented on files/en-us/web/api/web_background_synchronization_api/index.md
> +This code checks to see if a Background Sync task with a given tag is registered.
I didn't make these changes, and kept `background sync` (with no dash). English isn't my first language, but it felt odd to me linking those 2 words like this. Let me know if this is needed.

2021-09-15 12:35 UTC, sideshowbarker approved these changes

2021-09-15 12:35 UTC, merged

2021-09-15 12:37 UTC, captainbrosset commented
Woohoo, first PR merged! Thank you for the really quick review and useful info on the chat. A very smooth experience!

2021-09-15 12:57 UTC, sideshowbarker commented
Cheers 🎉 Thanks and congrats on getting this landed — it’s a great addition