Adds WebCodecs AudioDecoder
mdn/content pull request #8906
Opened 2021-09-14 13:24 UTC by rachelandrew

More WebCodecs, this time `AudioDecoder`.

Reviewer @jpmedley

2021-09-14 14:47 UTC, jpmedley requested changes

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/audiodecoder/index.md
> +      - : A callback which is passed a single argument of the error that has been thrown, otherwise `undefined`.
'Otherwise undefined'?

I don't understand this. A callback is either called or it isn't. I don't think it's ever called and passed `undefined`. What does this mean?

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/close/index.md
> +Undefined.
```suggestion
### Return Value

{{jsxref('undefined')}}.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/close/index.md
> +Undefined.
I'll be able to get exact numbers after the md conversion. This is consistent with what I've seen over many years.

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/configure/index.md
> +The **`configure`** method of the {{domxref("AudioDecoder")}} interface enqueues a control message to configure the audio decoder for decoding chunks.
```suggestion
The **`configure()`** method of the {{domxref("AudioDecoder")}} interface enqueues a control message to configure the audio decoder for decoding chunks.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/configure/index.md
> +The **`configure`** method of the {{domxref("AudioDecoder")}} interface enqueues a control message to configure the audio decoder for decoding chunks.
I've fixed this in the templates. Please do git pull.

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/configure/index.md
> +Undefined.
```suggestion
{{jsxref("Undefined")}}.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/decode/index.md
> +The **`decode`** method of the {{domxref("AudioDecoder")}} interface enqueues a control message to decode a given chunk of audio.
```suggestion
The **`decode()`** method of the {{domxref("AudioDecoder")}} interface enqueues a control message to decode a given chunk of audio.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/decode/index.md
> +Undefined.
```suggestion
{{jsxref("Undefined")}}.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/decode/index.md
> +  - : Thrown if the `chunk` is unable to be decoded due to relying on other frames for decoding.
What does this mean?

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/flush/index.md
> +The **`flush`** method of the {{domxref("AudioDecoder")}} interface returns a promise that resolves once all pending messages in the queue have been completed.
```suggestion
The **`flush()`** method of the {{domxref("AudioDecoder")}} interface returns a Promise that resolves once all pending messages in the queue have been completed.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/flush/index.md
> +A {{jsxref("Promise")}} that resolved with undefined.
```suggestion
A {{jsxref("Promise")}} that resolves with undefined.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/flush/index.md
> +  - : A rejected promise returned if the {{domxref("AudioDecoder.state","state")}} is not `"configured"`.
```suggestion
  - : The Promise rejected because the {{domxref("AudioDecoder.state","state")}} is not `"configured"`.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/index.md
> +  - : Resets all state including configuration, control messages in the control message queue, and all pending callbacks.
```suggestion
  - : Resets all states including configuration, control messages in the control message queue, and all pending callbacks.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/reset/index.md
> +The **`reset`** method of the {{domxref("AudioDecoder")}} interface resets all state including configuration, control messages in the control message queue, and all pending callbacks.
```suggestion
The **`reset()`** method of the {{domxref("AudioDecoder")}} interface resets all states including configuration, control messages in the control message queue, and all pending callbacks.
```

2021-09-14 14:47 UTC, jpmedley commented on files/en-us/web/api/audiodecoder/reset/index.md
> +Undefined.
```suggestion
{{jsxref("Undefined")}}.
```

2021-09-15 05:37 UTC, rachelandrew commented on files/en-us/web/api/audiodecoder/close/index.md
> +Undefined.
Happy to do this, although we haven't been so far.

2021-09-16 09:20 UTC, rachelandrew commented on files/en-us/web/api/audiodecoder/decode/index.md
> +  - : Thrown if the `chunk` is unable to be decoded due to relying on other frames for decoding.
What it says really ... https://w3c.github.io/webcodecs/#key-chunk

2021-09-16 09:38 UTC, rachelandrew commented on files/en-us/web/api/audiodecoder/close/index.md
> +The **`close`** method of the {{domxref("AudioDecoder")}} interface ends all pending work and releases system resources.
```suggestion
The **`close()`** method of the {{domxref("AudioDecoder")}} interface ends all pending work and releases system resources.
```

2021-09-16 11:57 UTC, rachelandrew commented on files/en-us/web/api/audiodecoder/decode/index.md
> +  - : Thrown if the {{domxref("AudioEncode.state","state")}} is not `"configured"`.
```suggestion
  - : Thrown if the {{domxref("AudioDecoder.state","state")}} is not `"configured"`.
```

2021-09-16 15:43 UTC, jpmedley approved these changes

2021-09-16 15:43 UTC, merged