Move Acknowledgements note up to fix duplicate sections
mdn/content pull request #8910
Opened 2021-09-14 15:35 UTC by AnilSeervi

2021-09-14 15:39 UTC, AnilSeervi commented
It still creates duplicate headlines.🤔

2021-09-14 16:59 UTC, rebloor commented
@AnilSeervi The duplication comes from a "manually" inserted Example extensions section in lines 39 to 43. Delete these lines and move the browser compatibility/extension examples block back above the acknowledgments and you should be good.

2021-09-14 21:53 UTC, rebloor requested changes

2021-09-14 21:53 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/api/devtools/inspectedwindow/index.html
> -<p>{{WebExtExamples("h2")}}</p>
Restore these lines, the macro is correct way of including the examples. Then delete lines 39 to 43:
```
<h2 id="Example_extensions">Example extensions</h2>
<ul>
 <li><a class="external" href="https://github.com/mdn/webextensions-examples/tree/master/devtools-panels" rel="noopener">devtools-panels</a></li>
</ul>
```

2021-09-16 15:22 UTC, AnilSeervi commented on files/en-us/mozilla/add-ons/webextensions/api/devtools/inspectedwindow/index.html
> -<p>{{WebExtExamples("h2")}}</p>
That fixes it.

2021-09-16 16:55 UTC, rebloor approved these changes

2021-09-16 16:57 UTC, rebloor commented
Thanks  @maddhruv that is looking good now

2021-09-16 16:57 UTC, merged