Correct the Date.p.getTimezoneOffset() doc
mdn/content pull request #893
Opened 2021-01-04 04:07 UTC by sideshowbarker

Fixes https://github.com/mdn/content/issues/665

2021-01-05 14:25 UTC, Elchi3 requested changes
Thanks for getting into this! Some comments inline.

2021-01-05 14:25 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
Not `true` for me.
`currentLocalDate.getTimezoneOffset()` is `-60` and `laborDay2016at0324GMTminus2.getTimezoneOffset();` is `-120`

2021-01-05 14:25 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +currentLocalDate.getTimezoneOffset() === laborDay2016at0324GMTminus2.getTimezoneOffset();
I think what I like about the current example is that it shows what's the output of `getTimezoneOffset()`, but this code doesn't do that directly.

"Using xyz" example sections on MDN usually try to just show what happens when you call the method. Examples showing a specific (non-basic) behavior are then put in their own example sub section with further explanation. This is so that you can look at the code and grasp what the method is doing without much reading.

2021-01-05 14:25 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +<div class="notecard note">
Again a note box :) Might be fine here, but not sure if the style is really needed.

2021-01-05 14:25 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> -<p>The <strong><code>getTimezoneOffset()</code></strong> method returns the time zone difference, in minutes, from current locale (host system settings) to UTC.</p>
I like the new summary sentence without the "host system settings" part. It is much easier. I wonder though if we really want to remove it from the whole doc, or if it should be at least mentioned in the description section.

2021-01-05 18:19 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
> Not `true` for me.
> `currentLocalDate.getTimezoneOffset()` is `-60` and `laborDay2016at0324GMTminus2.getTimezoneOffset();` is `-120`

OK, so it seems that’s somehow due to DST I suppose? You’re in DST, I’m not.

But regardless, I’m baffled as to why it would return a different value depending on which Date instance you call it from.

Date instances just hold Unix time as single integer, right? And Date instances have no additional properties that store a time-zone offset.

So where can the difference that you observe actually be coming from?

Looking at the spec, I can’t see where it would be coming from —

https://tc39.es/ecma262/#sec-date.prototype.gettimezoneoffset

2021-01-06 07:48 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
> `currentLocalDate.getTimezoneOffset()` is `-60` and `laborDay2016at0324GMTminus2.getTimezoneOffset();` is `-120`

OK, just from testing, I think I may have identified why/when there’s a difference: It will be different when both of the following are true:

* the local timezone is a timezone that adjusts for DST but is not currently in DST
* the date of the instance is date that *is* within DST

…or when both of the following are true:

* the local timezone is a timezone that adjusts for DST and is currently in DST
* the date of the instance is date that *is not* within DST

That is based on the following testing with Node:
```
$ TZ=CET faketime -f '2021-12-04 12:00:43' node
> new Date().getTimezoneOffset() === new Date('Nov 01 2016 03:24:00 GMT+0100').getTimezoneOffset()
true
> new Date().getTimezoneOffset() === new Date('May 1, 2016 03:24:00 GMT-0000').getTimezoneOffset()
false

$ TZ=CET faketime -f '2021-05-04 12:00:43' node
> new Date().getTimezoneOffset() === new Date('Nov 01 2016 03:24:00 GMT+0100').getTimezoneOffset()
false
> new Date().getTimezoneOffset() === new Date('May 1, 2016 03:24:00 GMT-0000').getTimezoneOffset()
true
```
However, I find nothing in the ES spec which clearly states that. I guess  https://tc39.es/ecma262/#sec-local-time-zone-adjustment might be — but if so, I don’t understand it well enough to judge whether or not that is stating the behavior I see from testing.

I found a historical discussion at https://esdiscuss.org/topic/override-localtza that’s relevant.

Anyway, I’ll go a further update to add language describing that behavior. But once I have that, I would really hope we can get in from TC39 somebody who understands the spec/UA requirements and so will be able to confirm whether what I end up writing is accurate or not.

2021-01-06 10:35 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
Thanks Mike, I appreciate you getting into the details here. Maybe @sffc can shed some light how getTimezoneOffset works? 

Often, these things are called out as implementation-specific in the spec, so maybe it isn't actually in the spec? I'm not sure I can see it but I haven't studied the spec text a lot for the moment.

2021-01-06 16:29 UTC, amitwebx commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> -<p>The <strong><code>getTimezoneOffset()</code></strong> method returns the time zone difference, in minutes, from current locale (host system settings) to UTC.</p>
Mentioning should be better, I guess.

2021-01-07 14:57 UTC, sideshowbarker commented
I’ll write more examples later, but for now I have pushed updates to the prose of the article to more precisely describe what `getTimezoneOffset()` does. The Description now reads:

> `date.getTimezoneOffset()` returns the difference, in minutes, between _date_ as evaluated in the UTC time zone, and _date_ as evaluated in the local time zone.

…and I added the following subsection:

> ### Varied results in Daylight Saving Time (DST) time zones
> In a time zone that annually shifts in and out of Daylight Saving Time (DST), the number of minutes returned by calling `getTimezoneOffset()` can vary.
>
> Consider a given local time zone and a date _date1_ that are both in DST, and consider _minutes_, the number of minutes returned by calling `date1.getTimezoneOffset()`; then:
> 
> * If the local time zone is currently in DST, but a given date _date2_ is not in DST, then the number of minutes returned by `date2.getTimezoneOffset()` is minutes ± 60.
> * If the local time zone is not currently in DST, but a given date _date3_ is in DST, then the number of minutes returned by `date3.getTimezoneOffset()` is minutes ± 60.
> 
> In a time zone that doesn’t annually shift in and out of Daylight Saving Time (DST), the number of minutes returned by calling `getTimezoneOffset()` always returns the same number of minutes, regardless of the date instance it’s called from.
> 
> Note: The above description is a simplification. In implementations, the IANA time zone database (tzdata) is used for precisely determining the effect of DST on the calculation of the time-zone difference.

2021-01-07 15:17 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +currentLocalDate.getTimezoneOffset() === laborDay2016at0324GMTminus2.getTimezoneOffset();
> I think what I like about the current example is that it shows what's the output of getTimezoneOffset(), but this code doesn't do that directly.
> 
> "Using xyz" example sections on MDN usually try to just show what happens when you call the method.

You’re right. But in this specific case, the problem with showing what happens is that we can’t show what `getTimezoneOffset()` will actually output — because the output is system-dependent, and will vary based on what time zone the reader is in, and vary even based on whether or not it’s currently DST in the time zone the reader is in.

And so if two readers copy the same `getTimezoneOffset()` code from the example, and pastes it into their browser devtools consoles, they’re likely to get different output from another.

So it kind of seems like the only alternative in this case is to put comments saying, e.g., *If you’re in the CET time zone and it’s January, the number of minutes returned will be -60; and if you’re in the JST time zone, the number of minutes returned will always be -540.*

2021-01-08 15:16 UTC, Elchi3 commented
Thanks Mike! I've read through your added subsection and I *think* it makes sense. We might want to see if we can get some i18n folk to double-check this, though.

2021-01-08 15:18 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +currentLocalDate.getTimezoneOffset() === laborDay2016at0324GMTminus2.getTimezoneOffset();
Okay, to avoid confusion it probably isn't a good idea in this case then.
It seems like people need to read the whole page anyways to really understand what exactly this method is returning.

2021-03-16 07:17 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
> Often, these things are called out as implementation-specific in the spec, so maybe it isn't actually in the spec?

This is actually in the spec — in the https://tc39.es/ecma262/#sec-local-time-zone-adjustment **LocalTZA** section, which explicitly states the behavior is “implementation-defined”:

> LocalTZA( <var>t</var>, <var>isUTC</var> ) is an <a href="https://tc39.es/ecma262/#implementation-defined">implementation-defined</a> algorithm that returns an <a href="https://tc39.es/ecma262/#integral-number">integral Number</a> representing the local time zone adjustment, or offset, in milliseconds. The local political rules for standard time and daylight saving time in effect at <var>t</var> should be used to determine the result in the way specified in this section.

But in practice, implementations consistently use Note: the IANA time zone database (tzdata) — and so that’s why in the patch I added the following:

> Note: The above description is a simplification. In implementations, the IANA time zone database (tzdata) is used for precisely determining the effect of DST on the calculation of the time-zone difference.

2021-03-16 07:29 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> -<p>The <strong><code>getTimezoneOffset()</code></strong> method returns the time zone difference, in minutes, from current locale (host system settings) to UTC.</p>
> I like the new summary sentence without the "host system settings" part. It is much easier. I wonder though if we really want to remove it from the whole doc, or if it should be at least mentioned in the description section.

OK, to try to help clarify that, I added the following language:

> that is, the time zone of the host system in which the browser is being used (if the code is run from the Web in a browser), or otherwise the host system of whatever JavaScript runtime (for example, a Node.js environment) the code is executed in.

2021-03-16 07:46 UTC, sideshowbarker commented on files/en-us/web/javascript/reference/global_objects/date/gettimezoneoffset/index.html
> +// true, always — regardless of the values of the Date instances
>>     // true, always — regardless of the values of the Date instances
>
> Not `true` for me.
> `currentLocalDate.getTimezoneOffset()` is `-60` and `laborDay2016at0324GMTminus2.getTimezoneOffset();` is `-120`

OK, I’ve pushed a commit that updates the comment to this:

```diff
-// true, always — regardless of the values of the Date instances
+// true, always, in any timezone that doesn't annually shift in and out of DST
+// false, sometimes, in any timezone that annually shifts in and out of DST
```

2021-03-16 07:48 UTC, sideshowbarker commented
OK, I think I’ve now addressed all the outstanding review commentsm, I don’t plan to make any further changes of my own at this time — so if my resolutions to the review comments are satisfactory, then this should be ready to merge.

2021-03-16 14:29 UTC, Elchi3 approved these changes
Thanks for getting back to this Mike, lets merge it! :)

2021-03-16 14:29 UTC, merged