Fix typography and structure of PerformanceNavigationTiming.type
mdn/content pull request #8933
Opened 2021-09-15 08:15 UTC by teoli2003

Strings were not in `<code>`. Read-only was mentioned twice. Fixed the structure to match the most recent property page template.

(Found when reviewing the _Giant MD Conversion PR™_.)

2021-09-15 08:46 UTC, rachelandrew reviewed
Just a couple of comments based on writing a bunch of similar pages recently.

2021-09-15 08:46 UTC, rachelandrew commented on files/en-us/web/api/performancenavigationtiming/type/index.md
> +The value is one of the following strings:
```suggestion
A {{domxref("DOMString","string")}} containing one of the following values:
```

2021-09-15 08:46 UTC, rachelandrew commented on files/en-us/web/api/performancenavigationtiming/type/index.md
> +- `navigate`
when Joe and I have been doing these we have been making string values obviously strings, so this would be "navigate". I don't know if that's actually what happens everywhere, but if not maybe we need to revise what we are doing instead!

2021-09-15 13:08 UTC, teoli2003 commented on files/en-us/web/api/performancenavigationtiming/type/index.md
> +- `navigate`
I was applying the rule I was told for string literals (coming from IDL enums).

I have no strong feeling (except that all reviewers should have the same rules). I have asked the question on slack and we will have the official rule. If you and Joe are applying this rule, either it is correct (likely) or there will be 100s of pages to fix, so one more will not be a big deal.

2021-09-16 17:34 UTC, jpmedley requested changes

2021-09-16 17:34 UTC, jpmedley commented on files/en-us/web/api/performancenavigationtiming/type/index.md
> -### Return Value
Doesn't removing the return value make this less scannable? After all, this content is more like a dictionary than a magazine article.

2021-10-26 15:50 UTC, jpmedley approved these changes

2021-10-26 15:52 UTC, merged