Adds VideoDecoder
mdn/content pull request #8984
Opened 2021-09-16 12:28 UTC by rachelandrew

Another WebCodec API: `VideoDecoder`.

Reviewer: @jpmedley

2021-09-16 16:22 UTC, jpmedley requested changes

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/index.md
> +The **`VideoDecoder`** interface of the {{domxref('WebCodecs API','','',' ')}} decodes chunks of video.
```suggestion
The **`VideoDecoder`** interface of the {{domxref('WebCodecs API','','','true')}} decodes chunks of video.
```

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/index.md
> +The **`VideoDecoder`** interface of the {{domxref('WebCodecs API','','',' ')}} decodes chunks of video.
This makes the title not monospaced.

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/index.md
> +  - : Represents the state of the underlying codec and whether it is configured for decoding.
```suggestion
  - : Indicates whether the underlying codec is configured for decoding.
```

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +The **`VideoDecoder()`** constructor creates a new {{domxref("VideoDecoder")}} object with the provided `init.output` callback assigned as the output callback, the provided `init.error` callback as t
I'm not crazy about describing the init members in the summary when they are described in a dedicated section. What's the argument for it?

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +  - : A dictionary object containing two required callbacks.
```suggestion
  - : A dictionary object containing two callbacks.
```

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +      - : A callback which is passed a single argument of an {{domxref("VideoFrame")}} object.
```suggestion
      - : A callback which takes a {{domxref("VideoFrame")}} object as its only argument.
```

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +      - : A callback which is passed a single argument of the error that has been thrown.
```suggestion
      - : A callback which takes an {{jsxref("Error")}} object as its only argument.
```

2021-09-16 16:22 UTC, jpmedley commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +In the following example an `VideoDecoder` is created with the two required callback functions, one to deal with the decoded frame and the other to handle errors.
```suggestion
In the following example a `VideoDecoder` is created with the two required callback functions, one to deal with the decoded frame and the other to handle errors.
```

2021-09-16 16:28 UTC, rachelandrew commented on files/en-us/web/api/videodecoder/configure/index.md
> +      - : A {{domxref("BufferSource")}} containing a sequence of codec specific bytes, commonly known as extradata.
yep.

2021-09-17 06:32 UTC, rachelandrew commented on files/en-us/web/api/videodecoder/videodecoder/index.md
> +The **`VideoDecoder()`** constructor creates a new {{domxref("VideoDecoder")}} object with the provided `init.output` callback assigned as the output callback, the provided `init.error` callback as t
I feel these intros should be a summary of what's going on I guess, but I'm not altogether bothered either way. I don't think we describe anywhere else that the video `state` is set to unconfigured which is important as you have to both create the decoder and configure it, where with some things you create an object and it's ready to go.

2021-09-17 14:24 UTC, jpmedley approved these changes

2021-09-17 14:24 UTC, merged