Feat locales info options
mdn/content pull request #8985
Opened 2021-09-16 12:54 UTC by romulocintra

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

2021-09-24 09:40 UTC, Elchi3 requested changes
Very great work! Some nits inline.

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/hourcycles/index.md
> +console.log(arEG.hourCycles); // Prints ["h12"]
```suggestion
console.log(arEG.hourCycles); // logs ["h12"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/hourcycles/index.md
> +console.log(jaJP.hourCycles); // Prints ["h23"]
```suggestion
console.log(jaJP.hourCycles); // logs ["h23"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/hourcycles/index.md
> +The **`Intl.Locale.prototype.hourCycles`** property is an accessor property which returns a list of 1 or more unique hour cycle identifiers for the `Locale`.
```suggestion
The **`Intl.Locale.prototype.hourCycles`** property is an accessor property which returns a list of one or more unique hour cycle identifiers for the `Locale`.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/hourcycles/index.md
> +There are 2 main types of time keeping conventions (clocks) used around the world: the 12 hour clock and the 24 hour clock. The `hourCycles` property makes it easier for JavaScript programmers to acc
```suggestion
There are two main types of time keeping conventions (clocks) used around the world: the 12 hour clock and the 24 hour clock. The `hourCycles` property makes it easier to access all clock types available for a particular locale. Like other additional locale data, the hour cycle type is an [extension subtag](https://www.unicode.org/reports/tr35/#u_Extension), which extends the data contained in a locale string. The hour cycle type can have several different values, which are listed in the table below.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/index.md
> +  - : Returns the part indicating the ordering of characters `ltr (left-to-right)` or `rtl (right-to-left)`.
```suggestion
  - : Returns the part indicating the ordering of characters `ltr` (left-to-right) or `rtl` (right-to-left).
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/numberingsystems/index.md
> +The **`Intl.Locale.prototype.numberingSystems`** property is an accessor property that returns of 1 or more unique numbering system identifiers according to the [numeral system](https://en.wikipedia.
```suggestion
The **`Intl.Locale.prototype.numberingSystems`** property is an accessor property that returns one or more unique numbering system identifiers according to the [numeral system](https://en.wikipedia.org/wiki/Numeral_system) used by the `Locale`.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/numberingsystems/index.md
> +### Obtaining  supported `numberingSystem` values via the locale string
```suggestion
### Obtaining supported `numberingSystem` values via the locale string
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/numberingsystems/index.md
> +console.log(arEG.numberingSystems); // Prints ["arab"]
```suggestion
console.log(arEG.numberingSystems); // logs ["arab"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/numberingsystems/index.md
> +console.log(ja.numberingSystems); // Prints ["latn"]
```suggestion
console.log(ja.numberingSystems); // logs ["latn"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/textinfo/index.md
> +The **`Intl.Locale.prototype.textInfo`** property is an accessor property which returns the ordering of characters `ltr (left-to-right)` or `rtl (right-to-left)` for the associated `Locale`.
```suggestion
The **`Intl.Locale.prototype.textInfo`** property is an accessor property which returns the ordering of characters indicated by either `ltr` (left-to-right) or by `rtl` (right-to-left) for the associated `Locale`.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/textinfo/index.md
> +### Obtaining the Text Info
```suggestion
### Obtaining text info 
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/textinfo/index.md
> +console.log(ar.textInfo.direction); // Prints "rtl"
```suggestion
console.log(ar.textInfo); // logs { direction: "rtl" }
console.log(ar.textInfo.direction); // logs "rtl"
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/textinfo/index.md
> +console.log(es.textInfo.direction); // Prints "ltr"
```suggestion
console.log(es.textInfo); // logs { direction: "ltr" }
console.log(es.textInfo.direction); // logs "ltr"
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/timezones/index.md
> +The **`Intl.Locale.prototype.timeZones`** property is an accessor property which returns a `List` of supported time zones for choosen `Locale`.
```suggestion
The **`Intl.Locale.prototype.timeZones`** property is an accessor property which returns an array of supported time zones for a chosen `Locale`.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/timezones/index.md
> +console.log(arEG.timeZones); // Prints ["Africa/Cairo"]
```suggestion
console.log(arEG.timeZones); // logs ["Africa/Cairo"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/timezones/index.md
> +console.log(jaJP.hourCycles); // Prints ["Asia/Tokyo"]
```suggestion
console.log(jaJP.hourCycles); // logs ["Asia/Tokyo"]
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/timezones/index.md
> +console.log(ar.hourCycles); // Prints undefined
```suggestion
console.log(ar.hourCycles); // logs undefined
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/weekinfo/index.md
> +The **`Intl.Locale.prototype.weekInfo`** property is an accessor property which returns the `WeekInfo` record fields `FirstDay`, `Weekend` and `MinimalDays` for the associated `Locale`.
```suggestion
The **`Intl.Locale.prototype.weekInfo`** property is an accessor property which returns a `weekInfo` object with the properties `firstDay`, `weekend` and `minimalDays` for the associated `Locale`.
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/weekinfo/index.md
> +console.log(he.weekInfo); // Prints {firstDay: 7, weekend: [5, 6], minimalDays: 1}
```suggestion
console.log(he.weekInfo); // logs {firstDay: 7, weekend: [5, 6], minimalDays: 1}
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/weekinfo/index.md
> +console.log(af.weekInfo); // Prints  {firstDay: 7, weekend: [6, 7], minimalDays: 1}
```suggestion
console.log(af.weekInfo); // logs  {firstDay: 7, weekend: [6, 7], minimalDays: 1}
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/weekinfo/index.md
> +console.log(enGB.weekInfo) // Prints  {firstDay: 1, weekend: [6, 7], minimalDays: 4}
```suggestion
console.log(enGB.weekInfo) // logs  {firstDay: 1, weekend: [6, 7], minimalDays: 4}
```

2021-09-24 09:40 UTC, Elchi3 commented on files/en-us/web/javascript/reference/global_objects/intl/locale/weekinfo/index.md
> +console.log(msBN.weekInfo) // Prints {firstDay: 7, weekend: [5, 7], minimalDays: 1}  // Brunei weekend is Friday and Sunday but not Saturday
```suggestion
console.log(msBN.weekInfo) // logs {firstDay: 7, weekend: [5, 7], minimalDays: 1}  // Brunei weekend is Friday and Sunday but not Saturday 
```

2021-09-28 09:24 UTC, Elchi3 approved these changes
Superb! Congrats on landing your first PR here!

2021-09-28 09:24 UTC, merged

2021-09-28 09:29 UTC, romulocintra commented
> Superb! Congrats on landing your first PR here!

Thank you @Elchi3  , may I ask to have a quick l look at #8768  that is strictly related