Glossary - remove explicit summary in preparation for markdowning
mdn/content pull request #9005
Opened 2021-09-17 01:50 UTC by hamishwillee

Also fixes some ids and classes that just aren't needed

2021-09-17 04:50 UTC, teoli2003 requested changes

2021-09-17 04:50 UTC, teoli2003 commented on files/en-us/glossary/node/dom/index.html
> +<p></p>
This is weird.

2021-09-17 07:17 UTC, hamishwillee commented on files/en-us/glossary/node/dom/index.html
> +<p></p>
Thanks. Ran my regexp in the wrong order. Fixed now.

2021-09-18 02:11 UTC, teoli2003 approved these changes

2021-09-18 02:13 UTC, teoli2003 requested changes
One typo in macro.

2021-09-18 02:13 UTC, teoli2003 commented on files/en-us/glossary/user_agent/index.html
> +<p>The user agent string can be accessed with {{Glossary("JavaScript")} on the client side using the {{domxref("Navigator/userAgent", "NavigatorID.userAgent")}} property.</p>
```suggestion
<p>The user agent string can be accessed with {{Glossary("JavaScript")}} on the client side using the {{domxref("Navigator/userAgent", "NavigatorID.userAgent")}} property.</p>
```

2021-09-19 10:56 UTC, teoli2003 approved these changes

2021-09-19 10:58 UTC, merged

2021-09-19 23:07 UTC, hamishwillee commented on files/en-us/glossary/user_agent/index.html
> +<p>The user agent string can be accessed with {{Glossary("JavaScript")} on the client side using the {{domxref("Navigator/userAgent", "NavigatorID.userAgent")}} property.</p>
Good catch. Thank you!