Update index.html
mdn/content pull request #9032
Opened 2021-09-17 17:58 UTC by zootechdrum

On line 195 the sentence instructs us to "Modify your FilterButton <script> like this: "
```
<script>
   export let filter = 'all'
</script>
```

However, this is being received as a prop from out Todos component.  We should not be setting the variable 'filter' to anything in our FilterButton.svelte. We should just be exporting the variable 'filter' to indicate that we are receiving it as a prop, right ?

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

2021-09-19 05:29 UTC, teoli2003 reviewed
Not able to review the core fix, but saw a typo to fix.

2021-09-19 05:29 UTC, teoli2003 commented on files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_components/index.html
> +<h2 id="Sharing_data_between_components_passFing_a_handler_as_a_prop">Sharing data between components: passing a handler as a prop</h2>
This extra `F`is clearly a typo
```suggestion
<h2 id="Sharing_data_between_components_passing_a_handler_as_a_prop">Sharing data between components: passing a handler as a prop</h2>
```

2021-09-27 13:04 UTC, ddbeck requested changes
Hi @zootechdrum and thanks for this PR. I see it's your first to the project—welcome!

> However, this is being received as a prop from out Todos component. We should not be setting the variable 'filter' to anything in our FilterButton.svelte. We should just be exporting the variable 'filter' to indicate that we are receiving it as a prop, right ?

To answer your question: strictly speaking, there is no requirement to set a value for a prop. However, `export let filter = 'all'` sets `'all'` as the default value for the prop. The component will use `'all'` until it's modified by another component. This makes sense in the context of the entire page, so I suggest that we do not apply your proposed change.

That said, the issue @teoli2003 caught is a good one and I'm glad your PR brought it to our attention. I recommend reverting your change and applying the suggested one. Thank you!

2021-11-22 09:07 UTC, Elchi3 commented
This PR was opened against an HTML source file of MDN. We have meanwhile migrated the content to Markdown. I suggest you open a new PR against the markdown source. Sorry for any inconveniences!

2021-11-22 09:07 UTC, closed without merging