WebXR createProjectionLayer: fix options listing
mdn/content pull request #9095
Opened 2021-09-20 09:03 UTC by Elchi3

Definition lists don't really work with nested lists, falling back to just lists.

2021-09-21 12:39 UTC, jpmedley requested changes

2021-09-21 12:39 UTC, jpmedley commented on files/en-us/web/api/xrwebglbinding/createprojectionlayer/index.md
> +- `depthFormat` {{optional_inline}}: A {{domxref("GLenum")}} defining the data type of the depth texture data or `0` indicating that the layer should not provide a depth texture (in that case {{domxr
If the parenthetical is a complete sentence, it's punctuated as such. If it's a subordinate clause it's punctuated as you did here.

2021-09-21 17:11 UTC, jpmedley approved these changes

2021-09-21 17:11 UTC, merged

2021-09-21 18:09 UTC, swanprincess386 commented
> Definition lists don't really work with nested lists, falling back to just lists.

2021-09-21 18:44 UTC, wbamberg commented
> Definition lists don't really work with nested lists, falling back to just lists.

Definition lists should certainly work with nested lists: if they don't it's a markup problem or a Yari problem. In this case it looks like the alignment of the `dd` contents was a little off, which confused m2h. Lines in the `dd` need to align with the `:`.

The source for this was:

```
- `textureType` {{optional_inline}}
  - : An string defining the type of texture the layer will have. Possible values:
    - `texture`: The textures of {{domxref("XRWebGLSubImage")}} will be of type `gl.TEXTURE_2D`.
    - `texture-array`: the textures of {{domxref("XRWebGLSubImage")}} will be of type `gl.TEXTURE_2D_ARRAY` (WebGL 2 contexts only).
    The default value is `texture`.
- `colorFormat` {{optional_inline}}
  - : A {{domxref("GLenum")}} defining the data type of the color texture data. Possible values:
    - `gl.RGBA`
    - `gl.RGBA`
    Additionally, for contexts with the {{domxref("EXT_sRGB")}} extension enabled:
    - `ext.SRGB_EXT`
    - `ext.SRGB_ALPHA_EXT`
    Additionally, for {{domxref("WebGL2RenderingContext")}} contexts:
    - `gl.RGBA8`
    - `gl.RGB8`
    - `gl.SRGB8`
    - `gl.RGB8_ALPHA8`
   The default value is `gl.RGBA`.
- `colorFormat` {{optional_inline}}
  - : A {{domxref("GLenum")}} defining the data type of the depth texture data or `0` indicating that the layer should not provide a depth texture (in that case {{domxref("XRProjectionLayer.ignoreDepthValues")}} will be `true`).
  Possible values within {{domxref("WebGLRenderingContext")}} contexts with the {{domxref("WEBGL_depth_texture")}} or within {{domxref("WebGLRenderingContext")}} contexts:
    - `gl.DEPTH_COMPONENT`
    - `gl.DEPTH_STENCIL`
    Additionally, for {{domxref("WebGL2RenderingContext")}} contexts:
    - `gl.DEPTH_COMPONENT24`
    - `gl.DEPTH24_STENCIL24`
   The default value is `gl.DEPTH_COMPONENT`.
- `scaleFactor` {{optional_inline}}
  - : A floating-point value which is used to scale the layer during compositing. A value of `1.0` represents the default pixel size for the frame buffer. See also {{domxref("XRWebGLLayer.getNativeFramebufferScaleFactor()")}}. Unlike other layers, the `XRProjectionLayer` can't be created with an explicit pixel width and height, because the size is inferred by the hardware (projection layers fill the observer's entire view).
```

Both lines starting "The default value is " need to be indented by 1 more space, and the line starting "Possible values within" needs to be indented by 2 more spaces. With those changes I get:

<img width="412" alt="Screen Shot 2021-09-21 at 11 43 30 AM" src="https://user-images.githubusercontent.com/432915/134229071-1cfa474a-47bb-4d03-b1b4-ac1b0b631016.png">

2021-09-22 09:58 UTC, Elchi3 commented
ahh thanks Will! I should have tried harder. Good to know that this works.