Adds AudioEncoder
mdn/content pull request #9140
Opened 2021-09-21 10:26 UTC by rachelandrew

Adds `AudioEncoder` part of WebCodecs.

Reviewer @jpmedley

2021-09-21 16:26 UTC, jpmedley requested changes

2021-09-21 16:26 UTC, jpmedley commented on files/en-us/web/api/audioencoder/audioencoder/index.md
> +In the following example a `AudioEncoder` is created with the two required callback functions, one to deal with the decoded frame and the other to handle errors.
```suggestion
In the following example an `AudioEncoder` is created with the two required callback functions, one to deal with the decoded frame and the other to handle errors.
```

2021-09-21 16:26 UTC, jpmedley commented on files/en-us/web/api/audioencoder/encode/index.md
> +  - : Thrown if the `AudioData` object has been {{Glossary("Transferable Objects","transferred")}}.
Should this be has *not* been transferred?

2021-09-22 07:51 UTC, rachelandrew commented on files/en-us/web/api/audioencoder/encode/index.md
> +  - : Thrown if the `AudioData` object has been {{Glossary("Transferable Objects","transferred")}}.
no, if it has is correct.

2021-09-22 07:52 UTC, rachelandrew commented on files/en-us/web/api/audioencoder/encode/index.md
> +  - : Thrown if the `AudioData` object has been {{Glossary("Transferable Objects","transferred")}}.
(and that's a link to the new glossary page I mentioned in the other PR.)

2021-09-22 14:52 UTC, jpmedley commented on files/en-us/web/api/audioencoder/encode/index.md
> +  - : Thrown if the `AudioData` object has been {{Glossary("Transferable Objects","transferred")}}.
Is it an error because the current context no longer has exclusive access to the object? Allowing changes in this situation would certainly have unintended consequences. This seems like something we should mention if it's true.

2021-09-23 14:50 UTC, rachelandrew commented on files/en-us/web/api/audioencoder/encode/index.md
> +  - : Thrown if the `AudioData` object has been {{Glossary("Transferable Objects","transferred")}}.
I think that's why it's best to link to the (new) glossary entry about transferable objects, it's not a thing exclusive to this API. The glossary entry has been merged but isn't showing up yet.

2021-09-24 15:06 UTC, jpmedley approved these changes

2021-09-24 15:06 UTC, merged