Details for window.maximize()
mdn/content pull request #9147
Opened 2021-09-21 15:35 UTC by talha-ah

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'
Not reported yet

> What was wrong/why is this fix needed? (quick summary only)
Content was needed for window.maximize()

> Anything else that could help us review it

2021-09-22 02:29 UTC, wbamberg reviewed
Thanks for this PR! But I think we should:

* delete the entry here for `maximize()`
* delete the entry below it for `minimize()`
* delete the linked page for `minimize()` (https://github.com/mdn/content#deleting-a-document)

These functions are apparently XUL-only, which means they are proprietary Firefox functions, which we should not document here.

If you'd like to make these changes, please go ahead :).

2021-09-22 06:39 UTC, teoli2003 requested changes
There is a typo to fix.

2021-09-22 06:39 UTC, teoli2003 commented on files/en-us/web/api/window/index.md
> +  - : Miximizes the window.
```suggestion
  - : Maximizes the window.
```

2021-09-22 18:53 UTC, wbamberg commented
@teoli2003 , what do you think about https://github.com/mdn/content/pull/9147#pullrequestreview-760400502 ?

2021-09-23 07:41 UTC, teoli2003 commented
Oh! Good catch! I missed that it was XUL-only. Yes, of course, like with minimize() this should be delete.

2021-09-23 07:41 UTC, teoli2003 approved these changes

2021-09-23 07:44 UTC, merged