add note about encoding
mdn/content pull request #9162
Opened 2021-09-22 09:52 UTC by rachelandrew

Fixes #9149 adds a note about encoding entities.

2021-09-22 18:32 UTC, wbamberg commented on files/en-us/web/html/element/pre/index.html
> +<div class="notecard note"><strong>Note:</strong> If you have HTML tags in the content you want to display literally, rather than parsed as HTML, you will need to encode the angle brackets. For examp
```suggestion
<div class="notecard note"><p><strong>Note:</strong> If you have HTML tags in the content you want to display literally, rather than parsed as HTML, you will need to encode the angle brackets. For example <code>&amp;lt;p&amp;gt;</code> to display <code>&lt;p&gt;</code>.</p></div>
```

(to keep the Markdown converter happy)

2021-09-23 11:03 UTC, Un-index commented
HI, I have a PR at #9164 that addresses the same issue. I'm going to wait till this is merged so we don't have 2 fixes for the same thing and it could be an addition to yours.

2021-09-24 07:35 UTC, rachelandrew commented
> Hi, I have a PR at #9164 that addresses the same issue. I'm going to wait till this is merged so we don't have 2 fixes for the same thing and it could instead be a modification to yours.

@Un-index the usual etiquette, if you want to suggest a modification to an existing PR, is to propose changes to the PR, rather than create another one.

2021-09-24 10:46 UTC, Un-index commented
> @Un-index the usual etiquette, if you want to suggest a modification to an existing PR, is to propose changes to the PR, rather than create another one.

Well I was working on it way before said PR even existed, then later on I made mine a modification to yours with parts from my own commit included - I agree at that point the changes should’ve been proposed here instead, (now that I know that is possible for contributors). 

I suppose attempting to adopt the usual etiquette would entail closing my PR, and then suggesting my changes. I’ll do that.

2021-09-24 11:06 UTC, Un-index requested changes
Request to modify the note (this was created accidentally).

2021-09-25 10:27 UTC, digi-booster commented
> Request to modify the note (this one was created accidentally, please dismiss).

You can also dismiss your suggestion by deleting your comment.

2021-10-05 16:28 UTC, Un-index commented
The usual etiquette, if you don't want to accept a suggested change, is to reject it in order to prevent wastage of time on either side, rather than blatantly ignoring it.

2021-10-05 16:39 UTC, wbamberg commented
This PR is rotted now because Markdown conversion happened. I think the best plan is to close it and reopen.

@rachelandrew , let me know if you want to open a new PR for this, otherwise I will take care of it (since it was me that broke it).

@Un-index , I'm not sure what you want to happen here. In https://github.com/mdn/content/pull/9162#pullrequestreview-762955761 you left a comment "Request to modify the note" but I don't see any actual proposed changes there.

2021-10-05 16:39 UTC, closed without merging

2021-10-06 21:42 UTC, Un-index commented
The change was proposed 12 days ago and is present right before your pst.