Remove text about the deprecated payment method "basic-card"
mdn/content pull request #9212
Opened 2021-09-23 20:54 UTC by maxlgu

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

Fixes #9211

> What was wrong/why is this fix needed? (quick summary only)

W3C has deprecated the "basic-card" payment method[1], so MDN should remove the corresponding text as well.

[1] https://www.w3.org/TR/payment-method-basic-card/

> Anything else that could help us review it

2021-09-23 20:54 UTC, maxlgu commented
@rsolomakhin

2021-09-23 20:55 UTC, maxlgu commented
@rsolomakhin, @jpmedley , PTAL. Thanks!

2021-09-23 21:13 UTC, rsolomakhin requested changes
Should some page link to Google Pay, Samsung Pay, and Apple Pay tutorials or API reference?

2021-09-23 21:13 UTC, rsolomakhin commented on files/en-us/web/api/payment_request_api/index.md
> -  - Credit Card
Remaining payment methods still use credit cards, so it should be OK to leave this line as-is.

2021-09-24 12:40 UTC, jpmedley requested changes

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/_wikihistory.json
> -  "Web/API/BasicCardRequest": {
@wbamberg Is this a file contributors should be touching?

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/web/api/payment_request_api/index.md
> +Many problems related to online shopping-cart abandonment can be traced to checkout forms, which can be difficult and time consuming to fill out and often require multiple steps to complete. The **Pa
```suggestion
Many problems related to online shopping-cart abandonment can be traced to checkout forms, which can be difficult and time consuming to fill out and often require multiple steps to complete. The **Payment Request API** is meant to reduce the number of steps needed to complete a payment online, potentially doing away with checkout forms. It aims to make the checkout process easier, by having payment apps store a user's details, which are then passed along to a merchant, hopefully without requiring an HTML form.
```

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/web/api/paymentaddress/index.md
> +Once the payment flow has been triggered using {{domxref("PaymentRequest.show()")}} and the promise resolves successfully, the {{domxref("PaymentResponse")}} object available inside the fulfilled pro
```suggestion
Once the payment flow has been triggered using {{domxref("PaymentRequest.show()")}} and the promise resolves successfully, the {{domxref("PaymentResponse")}} object available from the fulfilled promise (`instrumentResponse` above) will have a {{domxref("PaymentResponse.details")}} property containing response details. This has to conform to the structure defined by the payment method provider.
```

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/web/api/paymentrequest/paymentrequest/index.md
> +        whoever controls the payment methods for the expected shape of the data object.
```suggestion
        whomever controls the payment methods for the expected shape of the data object.
```

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/web/api/paymentresponse/details/index.md
> +This data is returned by the payment app that satisfies the payment request. Developers need to consult whoever controls the URL for the expected shape of the details object.
```suggestion
This data is returned by the payment app that satisfies the payment request. Developers need to consult whomever controls the URL for the expected shape of the details object.
```

2021-09-24 12:40 UTC, jpmedley commented on files/en-us/web/api/paymentresponse/index.md
> +  - : Returns a JSON-serializable object that provides a payment method specific message used by the merchant to process the transaction and determine successful fund transfer. The contents of the ob
```suggestion
  - : Returns a JSON-serializable object that provides a payment method specific message used by the merchant to process the transaction and determine successful fund transfer. The contents of the object depend on the payment method being used. Developers need to consult whomever controls the URL for the expected shape of the details object.
```

2021-09-24 13:15 UTC, rsolomakhin approved these changes

2021-09-24 14:26 UTC, maxlgu commented on files/en-us/web/api/payment_request_api/index.md
> -  - Credit Card
Done.

2021-09-24 14:31 UTC, maxlgu commented
@rsolomakhin , Google Pay, Apple Pay have already lived in the payment_request_api/index.md page. I have just added Samsung Pay to the list.

2021-09-27 13:59 UTC, jpmedley approved these changes

2021-09-27 14:00 UTC, jpmedley commented on files/en-us/_wikihistory.json
> -  "Web/API/BasicCardRequest": {
@wbamberg I'm asking because I don't think I've ever seen a content PR that touched this file.

2021-09-27 14:16 UTC, maxlgu commented
@jpmedley , do you know whether the reply by github-actions has anything that needs our attention? I am not familiar with submitting PR to MDN. Please let me know if any action from me is needed. Thanks!

This thread is waiting for @wbamberg 's reply. After that, an owner of this repo can merge the pull requests.

2021-09-27 16:27 UTC, wbamberg commented on files/en-us/_wikihistory.json
> -  "Web/API/BasicCardRequest": {
This file should not be edited directly but it gets edited by the [`yarn content delete`](https://github.com/mdn/content#deleting-a-document) command, which also takes care of other housekeeping like removing redirects.

2021-09-27 16:28 UTC, wbamberg commented on files/en-us/_wikihistory.json
> -  "Web/API/BasicCardRequest": {
It's totally fine for contributors to run `yarn content delete`.

2021-09-27 17:00 UTC, maxlgu commented on files/en-us/_wikihistory.json
> -  "Web/API/BasicCardRequest": {
Thanks @wbamberg.

Calling `yarn content delete Web/API/BasicCardResponse -r` and `yarn content delete Web/API/BasicCardRequest -r` leads to the same changes we have had.

Resolving this thread.

2021-09-27 17:05 UTC, maxlgu commented
Addressed @jpmedley's concern on wiki history based on @wbamberg 's advice. So the thread is ready to review. PTAL. Thanks!

Specifically, I think the reviewer need to resolve `3 workflows awaiting approval` and merge this pull request.

2021-09-28 16:49 UTC, merged