Note about event listeners
mdn/content pull request #9258
Opened 2021-09-25 08:10 UTC by Konrud

Note that adding HTML elements using `innerHTML` will result in the removal of the previously set event listeners.
Appreciate any addition / correction of the note.

2021-09-26 18:39 UTC, wbamberg commented
@Konrud , I thought this was surprising, so I tried it out, and did reproduce this in Firefox but couldn't in Chrome. Do you know if this is specced behavior? Have you reproduced  it in Chrome?

2021-09-27 12:31 UTC, Konrud commented
I've created a [test](https://jsfiddle.net/Konrud/gxpn4om5/). 
 I've checked it in:
 * **Chrome** Version 94.0.4606.61 (Official Build) (64-bit)  [Windows 10]
 * **Firefox** Version 92.0 (64-bit) [Windows 10]
 * **Opera** Version:79.0.4143.50 [Windows 10]
 * **Edge** Version 94.0.992.31 (Official build) (64-bit) [Windows 10]
 
In all of them, I've been able to reproduce this very behavior.

As for the specced behavior, I'm not sure it's even in the spec (at least I couldn't find it). I believe it has to do with the way `innerHTML`  works. That is, by using `+=` we are actually taking previously created elements in the DOM, convert them into the string representation, append another data to the string, and add it to the DOM as a string that will be parsed by the UA. I think that's why all the event listeners are removed. We are working with the DOM elements represented as a string rather than Nodes.

2021-09-27 21:17 UTC, wbamberg requested changes
Thanks for creating a fiddle for this! I can reproduce this on Chrome. Before, I was using the Chrome devtools, in which I could not, and still can't, reproduce.

I agree we should document this, but I don't think a note at the start is the right way. At the moment we have:

```
H3 Usage notes
    H4 Reading the HTML contents of an element
    H4 Replacing the contents of an element
    H4 Security considerations
```

I think we should add an H4:

```
H3 Usage notes
    H4 Reading the HTML contents of an element
    H4 Replacing the contents of an element
    H4 Appending to an element
    H4 Security considerations
```

...and in there have a line or two about this, and a simple example like the existing ones, and note this issue about event listeners. I don't think it needs the `> **Note:**` style, it can just be a paragraph.

2021-09-28 12:43 UTC, Konrud commented
@wbamberg, I've changed it according to your suggestion. Please let me know if it's sufficient or should be extended/changed.

2021-09-28 23:57 UTC, wbamberg commented on files/en-us/web/api/element/innerhtml/index.md
> +### Appending the contents to an element
```suggestion
### Appending HTML to an element  
```

2021-09-28 23:57 UTC, wbamberg approved these changes
Looks great, thank you @Konrud !

2021-09-29 00:00 UTC, merged