Class static initialization blocks
mdn/content pull request #9281
Opened 2021-09-27 08:34 UTC by hamishwillee

https://bugzilla.mozilla.org/show_bug.cgi?id=1725689 adds support for static initialisation blocks in classes (ES13 feature). This PR adds docs - part of the work in #8606

@Rumyra I am not particularly confident of this. I don't think anything is "wrong" - I just don't think it adds anything over what the explainers from v8.dev or the 2ality.blog do. That's the problem with not being particularly confident with JavaScript - it is easy enough to paraphrase, but not do anything innovative.

Anyway, I have left in draft, so it doesn't merge until you have a chance to look at it.

I will add an interactive exmaple if you think this is otherwise OK.

2021-09-27 08:38 UTC, hamishwillee commented
PS Before we are done will also cross link to the new doc from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#static_methods_and_properties

2021-09-27 08:39 UTC, hamishwillee commented on files/en-us/web/javascript/reference/classes/constructor/index.md
> -The `constructor` method is a special method of
Changes in this doc are just layout and can be ignored.

2021-09-27 08:40 UTC, hamishwillee commented on files/en-us/web/javascript/reference/classes/static/index.md
> +The **`static`** keyword defines a static method or property for a class, or a [class static initialization block](/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks) (se
This is most important change here - link to new doc. Also below I added a syntax block.

2021-09-27 13:19 UTC, Rumyra commented
Thanks so much @hamishwillee - I'm taking a look now 👍

2021-09-27 14:48 UTC, Rumyra requested changes
Honestly I think this is good @hamishwillee - I get it's paraphrasing, but I think that's fine.

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +**Class static initialization blocks** are special ES13 methods of a {{jsxref("Statements/class", "class")}} that enable more flexible initialization of {{jsxref("Classes/static", "static")}} propert
```suggestion
**Class static initialization blocks** are a special feature of a {{jsxref("Statements/class", "class")}} that enable more flexible initialization of {{jsxref("Classes/static", "static")}} properties than can be achieved using per-field initialization.
```

Just thinking it's ok without ES version

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Any static intitialization of a super class is performed first, before that of its sub classes!
```suggestion
Any static intitialization of a super class is performed first, before that of its sub classes.
```

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +// > 'Outer y'
```suggestion
var y = 'Outer y';

class A {
  static field = 'Inner y';
  static {
    var y = this.field;
  }
}

// vars defined in static block is not hoisted
console.log(y);
// > 'Outer y'
```

Just, well I like space :)

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Note that any static intitialization of a super class is performed first, before that of its sub classes!
```suggestion
Note that any static intitialization of a super class is performed first, before that of its sub classes.
```

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +// > private
```suggestion
let getDPrivateField;

class D {
  #privateField;
  constructor(v) {
    this.#privateField = v;
  }
  static {
    getDPrivateField = (d) => d.#privateField;
  }
}

getDPrivateField(new D('private'));
// > private
```

2021-09-27 14:48 UTC, Rumyra commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Prior to ES13 more complex static initialization might be achieved by using a static method that is called after the other properties to perform static initialization, or having a method that is exte
```suggestion
Prior to ES13 more complex static initialization might be achieved by using a static method that is called after the other properties to perform static initialization, or having a method that is external to the class that performs initialization tasks.
```

2021-09-27 23:34 UTC, hamishwillee commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +**Class static initialization blocks** are special ES13 methods of a {{jsxref("Statements/class", "class")}} that enable more flexible initialization of {{jsxref("Classes/static", "static")}} propert
OK. So what is our policy on JavaScript versioning? If you try this on a non-supporting JavaScript engine it will syntax error due to unexpected keyword, which isn't very helpful. I guess we will include browser engine BCD which is somewhat useful.

2021-09-27 23:44 UTC, hamishwillee commented
@Rumyra Great - I've accepted your change. Will do the release note and interactive example separately. Ready for re-review.

I think this is "OK" as reference. I'm just disappointed that the source materials show a deeper understanding of the practical use of the feature. I've linked them though, so nothing is lost.

2021-09-28 03:22 UTC, digi-booster commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Static blocks allow statements to be evaluated during initialization, which allows initializatons that (for example) include `try...catch` or set multiple fields from a single value.
```suggestion
Static blocks allow statements to be evaluated during initialization, which allows initializations that (for example) include `try...catch` or set multiple fields from a single value.
```

2021-09-28 03:23 UTC, digi-booster commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Any static intitialization of a super class is performed first, before that of its sub classes.
```suggestion
Any static initialization of a super class is performed first, before that of its sub classes.
```

2021-09-28 03:24 UTC, digi-booster commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +The output shows that the blocks and fields are evaluatd in execution order.
```suggestion
The output shows that the blocks and fields are evaluated in execution order. 
```

2021-09-28 03:24 UTC, digi-booster commented on files/en-us/web/javascript/reference/classes/class_static_initialization_blocks/index.md
> +Note that any static intitialization of a super class is performed first, before that of its sub classes.
```suggestion
Note that any static initialization of a super class is performed first, before that of its sub classes.
```

2021-09-28 03:44 UTC, hamishwillee commented
Sure, love a good typo fix :-)

2021-09-28 10:29 UTC, Rumyra approved these changes

2021-09-28 10:29 UTC, merged