add example for readAsText
mdn/content pull request #9288
Opened 2021-09-27 11:08 UTC by Braweria

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

No issue number, it was my personal issue when reading the file.

> What was wrong/why is this fix needed? (quick summary only)

It was unlear to me how to use it. When I saw the example used in [`readAsDataUrl()`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL), which is a bit similar to `readAsText`. So I added an example to this file as well. Example works with a `.txt` file in mind, for other text files more code would need to be written, this is a basic usage.

> Anything else that could help us review it

Working example: https://jsfiddle.net/u9q6en4g/

2021-09-27 22:56 UTC, wbamberg requested changes
Thanks for the PR, @Braweria ! I had a couple of minor comments.

Also though, you could easily make this into a live sample so people can run it in the page. Just add something like this after the JS code block:

```
### Result

{{EmbedLiveSample("Example")}}
```

2021-09-27 23:00 UTC, hamishwillee commented
@wbamberg I've been cross reviewing this at the same time - I added the `{{EmbedLiveSample("Example")}}`. I'll stop commenting and leave this with you.

@Braweria Thanks for this!

2021-09-27 23:03 UTC, wbamberg commented
Thanks Hamish! I see you already pushed the change to make this into a live sample 👍 .

2021-09-28 06:36 UTC, Braweria commented on files/en-us/web/api/filereader/readastext/index.md
> +    // convert image file to base64 string
Yes, I overlooked that comment. I copied the original function from the other document I mentioned and just applied it for `readAsText`.

2021-09-28 23:53 UTC, wbamberg commented on files/en-us/web/api/filereader/readastext/index.md
> +    // this will then display a .txt file
```suggestion
    // this will then display a text file
```

2021-09-28 23:55 UTC, wbamberg approved these changes
Thanks for this new example, @Braweria ! It's looking great.

2021-09-28 23:55 UTC, merged