create table for `compareFunction` return values
mdn/content pull request #9322
Opened 2021-09-28 15:59 UTC by glgoose

I initially got shortly confused when reading the sentence `If compareFunction(a, b) returns a value > than 0, sort b before a.` because I read the part `returns a` as that it returns the value `a`.
In this case it just meant 'a value' as in 'any' function return value, not the value of `a`.

Since there is an argument also called `a` this can be initially confusing to read.
I looked at ways to word it differently but in the end I think a table most clearly expresses at a glance what is about.

> Issue number that this PR fixes (if any). For example: 'Fixes #987654321'

> What was wrong/why is this fix needed? (quick summary only)

> Anything else that could help us review it

2021-09-28 22:06 UTC, wbamberg requested changes
Thanks for the PR, @glgoose ! I agree that the table is a good way to show this. I had a few comments though.

2021-09-28 22:06 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +| `compareFunction(a, b)` returns | sort order            |
Maybe consider wording this like "`compareFunction(a, b)` return value", then making the cell entries just "< 0" etc.

2021-09-28 22:06 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +| value > 0                       | sort `a` before `b`   |
It looks like this has reversed the original:

> If compareFunction(a, b) returns a value > than 0, sort b before a.
> If compareFunction(a, b) returns a value < than 0, sort a before b.

2021-09-28 22:06 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +| value === 0                     | `a` and `b` are equal |
Consider "keep original order of `a` and `b`" - because "`a` and `b` are equal" is not a sort order.

2021-09-28 22:06 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
>    > **Note:** The [ECMAScript Standard, 10th edition](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-intro) (2019)
Relatedly, I would delete this note, since the BCD table already captures sort stability more helpfully, and there's a whole section on sort stability in this page (however it is under "examples", while I would prefer to have it moved to be under "Description").

2021-09-30 07:00 UTC, glgoose commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +| `compareFunction(a, b)` returns | sort order            |
Great, I'll change it. That's how I had it originally, and then I went a bit back & forth doubting between what conveyed it most clearly.

2021-09-30 07:30 UTC, glgoose commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
>    > **Note:** The [ECMAScript Standard, 10th edition](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-intro) (2019)
I deleted the note.
Should I also have moved it elsewhere? I wasn't quite clear on what you meant with "I would prefer to have it moved to be under "Description""

2021-09-30 07:48 UTC, glgoose commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
>    > **Note:** The [ECMAScript Standard, 10th edition](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-intro) (2019)
Or more specifically I saw the section titled `Sort stability` but I wasn't clear on wether you also wanted that note to be deleted to be copied there, and if so where exactly in that section.

2021-09-30 07:51 UTC, glgoose commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
> +> **Note:** `compareFunction(a, b)` must always return the same value when given a specific pair of
I hadn't noticed there was a 4th bullet point because the original note about the ECMA standard was squeezed in between the 3rd & 4th bullet point.
I converted the 4th bullet point to a Note, because that seemed to be fitting here.

To be honest, the meaning of it isn't entirely clear to me. Perhaps an example or some extra clarification of this point could help?

2021-10-01 18:36 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/array/sort/index.md
>    > **Note:** The [ECMAScript Standard, 10th edition](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-intro) (2019)
Sorry, my "it" was ambiguous.

I mean that the section "Sort stability" would be better in "Description" than "Examples".

I think "Description" should, well, describe the behavior of the thing, and "Examples" should illustrate aspects of the behavior. So ideally someone could just read "Description" and get a complete description of the thing, and "Examples" can supplement that. So in general "Examples" should not introduce any new aspects of the thing.

In this case the concept of sort stability is not really covered in the "Description", and the section in "Examples" reads more like a description to me.

But I'm aware that this is quite out of scope for your original PR, so let me know if you just want to merge this as it is, or if you also wanted to move "Sort stability".

I hope that's clearer!

2021-10-07 22:07 UTC, wbamberg approved these changes
👍 thanks for your PR, @glgoose !

2021-10-07 22:23 UTC, merged