add collator options
mdn/content pull request #9332
Opened 2021-09-29 07:24 UTC by romulocintra

Update collation options.

https://github.com/tc39/ecma402/pull/459

2021-09-29 20:47 UTC, wbamberg reviewed
I think we should consider formatting this as list.

Also, forgive my ignorance here, but following the links, it looks like these values are coming ultimately from https://github.com/unicode-org/cldr/blob/latest/common/bcp47/collation.xml#L13-L31, but there are some values listed there that are not included here (for example, `emoji`, `standard`, `search`). Is this intended?

2021-09-29 20:47 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +        "`big5han`", "`compat`", "`dict`", "`direct`",
This would be a lot easier to read as a list.

2021-09-30 07:15 UTC, romulocintra commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +        "`big5han`", "`compat`", "`dict`", "`direct`",
Already updated to be a list :)

2021-10-01 11:05 UTC, romulocintra commented
> I think we should consider formatting this as list.
> 
> Also, forgive my ignorance here, but following the links, it looks like these values are coming ultimately from https://github.com/unicode-org/cldr/blob/latest/common/bcp47/collation.xml#L13-L31, but there are some values listed there that are not included here (for example, `emoji`, `standard`, `search`). Is this intended?

Hi @wbamberg  search and standard don't have support on ECMA402 https://tc39.es/ecma402/#sec-intl-collator-internal-slots , emoji still unclear the support, meaning as soon as we have it sure we will include.

2021-10-01 16:26 UTC, wbamberg requested changes
Thanks @romulocintra for the clarification and formatting the options as lists. Just a tweak to list them in alphabetical order.

2021-10-01 16:26 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          - `compat`
```suggestion
          - `compat`
          - `dict`
          - `direct`
```

2021-10-01 16:26 UTC, wbamberg commented on files/en-us/web/javascript/reference/global_objects/intl/collator/collator/index.md
> +          - `compat`
```suggestion
          - `compat`
          - `dict`
          - `direct`
```

2021-10-01 17:58 UTC, wbamberg approved these changes
👍 thank you @romulocintra !

2021-10-01 17:58 UTC, merged