Improvements to the working with the clipboard guide
mdn/content pull request #9344
Opened 2021-09-29 17:21 UTC by rebloor

#### Summary
This change includes:

-  making navigator.clipboard the "primary" approach given that document.execCommand is deprecated (addressing https://github.com/mdn/content/issues/4864)
-  provides a summary of the limitations with navigator.clipboard in the introduction
-  adds a note that the use of document.execCommand in hidden fields (addressing https://github.com/mdn/content/issues/1807) 

#### Motivation
To make the article more comprehensive and current.

#### Related issues

- https://github.com/mdn/content/issues/4864
- https://github.com/mdn/content/issues/1807

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-09-29 19:56 UTC, Rob--W requested changes

2021-09-29 19:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>The difference between the two APIs is that {{domxref("Clipboard", "navigator.clipboard")}} is analogous to the keyboard copy, cut, and paste actions – exchanging data between a webpage and clipbo
One of the two is supposed to be document.execCommand, right?

2021-09-29 19:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>However, while {{domxref("Clipboard.readText", "navigator.clipboard.readText()")}} and {{domxref("Clipboard.writeText", "navigator.clipboard.writeText()")}} work on all browsers,{{domxref("Clipboa
space after comma (`browsers,{{domxref`)

2021-09-29 19:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +  <li>work with images use {{WebExtAPIRef("clipboard.setImageData","browser.clipboard.setImageData()")}} to write images to the clipboard and {{domxref("Document.execCommand()","document.execCommand(
Collapse double spaces to one (`images  to`).

2021-09-29 19:56 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> + <li>You can write to the clipboard with execCommand in all execution contexts <em>except background pages</em>. In Firefox, you can't select text or focus an input field in background pages, so you
This whole bullet point can be removed. It used to be true in the past, but it is not any more.
Let's remove it entirely to avoid confusion (and remove the similar comment from the Chrome list).

The relevant bugs was https://bugzilla.mozilla.org/show_bug.cgi?id=1272869

2021-09-30 15:28 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>The difference between the two APIs is that {{domxref("Clipboard", "navigator.clipboard")}} is analogous to the keyboard copy, cut, and paste actions – exchanging data between a webpage and clipbo
Yes, the first reference should be to document.execCommand

2021-09-30 15:30 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>However, while {{domxref("Clipboard.readText", "navigator.clipboard.readText()")}} and {{domxref("Clipboard.writeText", "navigator.clipboard.writeText()")}} work on all browsers,{{domxref("Clipboa
Thanks for spotting that.

2021-09-30 15:31 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +  <li>work with images use {{WebExtAPIRef("clipboard.setImageData","browser.clipboard.setImageData()")}} to write images to the clipboard and {{domxref("Document.execCommand()","document.execCommand(
Thanks, fixed

2021-09-30 15:35 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> + <li>You can write to the clipboard with execCommand in all execution contexts <em>except background pages</em>. In Firefox, you can't select text or focus an input field in background pages, so you
Thanks, I'll leave you to resolve this conversation when you have confirmed I've deleted the right items

2021-10-01 17:16 UTC, Rob--W requested changes
Thanks for fixing up the document. There are still points to improve, largely due to pre-existing issues.

2021-10-01 17:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> + <li>From version 57 onward, you can copy images to the clipboard using the {{WebExtAPIRef("clipboard.setImageData","browser.clipboard.setImageData()")}} API.</li>
I think that it's preferable to remove these two bullet points, since they concern old versions and Chrome also implements them. By putting it here and omitting it in Chrome, there is an incorrect impression that it's unique to Firefox.

Could you add the compat tables to the bottom of this page, for this `clipboard` extension API (`clipboard.setImageData`), and the compat table for the Clipboard API?

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility
   * The compat table of read/write looks very confusing, it would be great if you can figure out why the table is as confusing as it is and fix the browser-compat-data data.

I think that if anything needs to be put here, that it's the fact that Firefox doesn't support `navigator.clipboard.write` yet (with a reference to the compat table).

2021-10-01 17:16 UTC, Rob--W commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>The difference between the two APIs is that {{{domxref("Document.execCommand()","document.execCommand")}} this is analogous to the keyboard copy, cut, and paste actions – exchanging data between a
`{{{domxref("Document.execCommand()","document.execCommand")}}` has a superfluous `{` at the start, which seems to be causing rendering issues. See the preview generated by the bot above to verify the rendered result.

2021-10-04 15:17 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> +<p>The difference between the two APIs is that {{{domxref("Document.execCommand()","document.execCommand")}} this is analogous to the keyboard copy, cut, and paste actions – exchanging data between a
Fixed

2021-10-04 15:29 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
>   <li>When using content scripts, the Clipboard API is available only for HTTPS pages. As a workaround, use messaging between your content scripts and the background script.</li>
Added a clarification to the introduction in the read and write sections

2021-10-04 16:50 UTC, rebloor commented on files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> + <li>From version 57 onward, you can copy images to the clipboard using the {{WebExtAPIRef("clipboard.setImageData","browser.clipboard.setImageData()")}} API.</li>
Done.

The issue with the clipboard API browser compatibility table notes for read and write don't appear to be because of the information in the browser-compact-data per se e.g.

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/7352080/135888219-b7ec7496-51a1-4842-ad8d-469194254e87.png">

looks fine. I think the rendering is the issue:

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/7352080/135888678-8ea920ae-fba7-436f-a7c1-d701769371a3.png">

I've created https://github.com/mdn/yari/issues/4757 to get this addressed.

2021-10-18 19:22 UTC, Rob--W requested changes

2021-10-25 13:06 UTC, Rob--W approved these changes
Apply the following changes and merge the PR.

2021-10-28 16:38 UTC, merged