Update index.html
mdn/content pull request #9348
Opened 2021-09-29 21:10 UTC by msaleh75894

Instead on just one website that offer hiring influencers 
I have added 3 options to choose from

#### Summary
Instead on just one website that offer hiring influencers 
I have added 3 options to choose from

#### Motivation
This is going to help readers choose from more than one  serivce 

#### Supporting details
links included

2021-09-29 22:28 UTC, estelle commented
My take is that all services should be removed instead of new ones added. MDN is not a place to market marketing services.

2021-09-29 22:34 UTC, estelle requested changes
I suggest removing all three. MDN is not a place to market marketing services.

2021-09-30 13:21 UTC, Rumyra commented
Hi @msaleh75894 thanks for your contribution! It's correct we are trying to minimise the number of external links on MDN currently.

A good update would be to remove the whole Youtube paragraph - it's out of date - and instead add a note about youtube and twitch to the social media paragraph 👍

2021-10-06 18:07 UTC, wbamberg commented on files/en-us/games/publishing_games/game_promotion/index.html
> +<p>There are two options to get coverage from the YouTubers: first is you contact them directly and send a link to your game via email or private message. The second is earned in time - if you're kno
```suggestion
```

2021-10-06 18:08 UTC, wbamberg commented on files/en-us/games/publishing_games/game_promotion/index.html
> +<p>There are two options to get coverage from the YouTubers: first is you contact them directly and send a link to your game via email or private message. The second is earned in time - if you're kno
```suggestion
```

2021-10-11 10:25 UTC, Rumyra commented
Due to the conflicts I'm going to suggest we close this, open an issue to remove the paragraph and tackle it after md conversion. Let me know what you think @wbamberg

2021-10-15 04:26 UTC, wbamberg commented
> Due to the conflicts I'm going to suggest we close this, open an issue to remove the paragraph and tackle it after md conversion. Let me know what you think @wbamberg

I agree and have filed https://github.com/mdn/content/issues/9831.

2021-10-15 04:26 UTC, closed without merging