partitionKey in the cookies API
mdn/content pull request #9382
Opened 2021-09-30 17:52 UTC by rebloor

#### Summary
Added details about the inclusion of partitionKey in the cookies API to the:
- the cookies object
- the Firefox 94 release notes

#### Related issues
Addresses  [Bug 1669716](https://bugzilla.mozilla.org/show_bug.cgi?id=1669716) (https://github.com/mdn/content/issues/9363)

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [x] Fixes a typo, bug, or other error

2021-09-30 20:15 UTC, Rob--W requested changes
Property also needs to be documented at:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/get
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/remove

The feature needs to prominently be documented at the main page too. For example, see the level of depth in the documentation of a similar property: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies#first-party_isolation

The section should include:
- Reference to https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning
- While this feature is internally called "dynamic first-party isolation (dFPI)", its public name is "dynamic partitioning" - https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning#dynamic_state_partitioning
- Partitioned cookies are not visible to getAll by default. This is an intentional design decision, because extensions that aren't aware of partitioned cookies may inadvertently copy cookies to another partition. For a write-up of examples, see https://phabricator.services.mozilla.com/D123491#4106552
- From the documentation, it should be obvious that extensions that want to do the right thing should be aware of `partitionKey`. To maintain compatibility with browsers that don't support `partitionKey`, extensions can check for the presence of `partitionKey` on the returned cookie, and if it is set, put it on the object of the cookie that they're updating or removing (some extensions that want to update cookies would use `cookies.get` to get a cookie, and then use `cookies.set` with the details of the cookie).

Let me know if you have more questions about this API or the level of documentation.

2021-10-11 15:45 UTC, Trikolon requested changes
Feedback for the state partitioning article changes. Thank you for working on this!

2021-10-11 17:55 UTC, rebloor commented
@Trikolon Thanks for your review, the re-review button doesn't work for me, could you take a look at my changes.

2021-10-11 18:13 UTC, Trikolon approved these changes
Thanks!

2021-10-11 19:50 UTC, Rob--W requested changes

2021-10-14 07:31 UTC, Rob--W reviewed
A few more small remarks (on top of the changes requested during my last review).

I found those after looking at the preview from the github-actions bot.

2021-10-18 12:09 UTC, Rob--W approved these changes
The Github actions bot failed to update the preview, but it seems to look good enough. Thanks!

2021-10-18 18:57 UTC, Rob--W requested changes

2021-10-20 12:56 UTC, Rob--W reviewed
Just one more revision, after that rebase the PR so that it can be merged.

2021-10-21 17:39 UTC, Rob--W approved these changes
One more overlooked change. Please add the suggested change and rebase.

Then the bot should be able to generate a preview.

If it looks good to you, merge it \o/

2021-10-22 16:28 UTC, Rob--W approved these changes
Changes still LGTM. Unfortunately, it seems that there are now many merge conflicts, likely due to #9910. Feel free to merge after resolving the merge conflict. If you'd like another review, that's also fine by me.

2021-10-22 18:12 UTC, merged