API Routing would be a useful definition here.
mdn/content pull request #9424
Opened 2021-10-01 16:59 UTC by TGillispie

Similar to application layer routing.

#### Summary

Adding API routing as it is used all over the place in API Development, (Express, Fastify, League/Route, etc.) Service layer or API routing is similar but different from client appliation routing.

#### Motivation

I'm building a list of (Restful API) vocabulary words for my team at NOAA NEFSC and am using MDN Web Docs as one of my primary resources.  It would be nice to have a good definition of routing on the server.

#### Supporting details

Not sure.

#### Related issues

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-01 18:05 UTC, wbamberg commented
@TGillispie , I have a PR open at the moment to convert the Glossary into Markdown (https://github.com/mdn/content/pull/9384). Could I please ask that you resubmit this PR when that's merged?

2021-10-01 18:52 UTC, TGillispie commented
Sure thing.

On Fri, Oct 1, 2021 at 11:06 AM wbamberg ***@***.***> wrote:

> @TGillispie <https://github.com/TGillispie> , I have a PR open at the
> moment to convert the Glossary into Markdown (#9384
> <https://github.com/mdn/content/pull/9384>). Could I please ask that you
> resubmit this PR when that's merged?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/content/pull/9424#issuecomment-932445902>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUS76CDC73G4LD6HLWY5YXLUEX2AFANCNFSM5FFDKPOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-05 16:05 UTC, wbamberg requested changes
Thanks for this PR, @TGillispie ! Since my PR to convert the whole glossary has conflicts now anyway I thought we should try to merge this one before I try again.

I had a couple of comments. The first doesn't actually refer to any changes you've made and is more like copy-editing, the second is a bit more substantive and please let me know if I've destroyed the sense of what you were saying.

This page has a "See also" section listing examples of the existing definitions - it would be helpful I think to include examples of this one too.

2021-10-05 20:51 UTC, TGillispie commented
I think your modification is great and I really like the first suggestion.
 "a software component that routes a client request to the appropriate
handler".  Mentioning "endpoint" might be too specific and a potential
cause for confusion. I request holds more than just an endpoint and each of
those parts could be used for routing.

Also, I think it might make sense to change "The code usually..." to "The
router code usually..."

On Tuesday, October 5, 2021, wbamberg ***@***.***> wrote:
> @wbamberg requested changes on this pull request.
>
> Thanks for this PR, @TGillispie ! Since my PR to convert the whole
glossary has conflicts now anyway I thought we should try to merge this one
before I try again.
>
> I had a couple of comments. The first doesn't actually refer to any
changes you've made and is more like copy-editing, the second is a bit more
substantive and please let me know if I've destroyed the sense of what you
were saying.
>
> This page has a "See also" section listing examples of the existing
definitions - it would be helpful I think to include examples of this one
too.
>
> ________________________________
>
> In files/en-us/glossary/routers/index.html:
>
>> @@ -4,11 +4,12 @@
>
> tags:
>
> - Intro
>
> ---
>
> -<p>There are two definitions for <strong>routers</strong> on the web:</p>
>
> +<p>There are three definitions for <strong>routers</strong> on the
web:</p>
>
>
>
> <ol>
>
> <li>For the network layer, the router is a networking device that decides
data {{Glossary('Packet')}}s directions. They are distributed by retailers
allowing user interaction to the internet.</li>
>
> <li>For {{Glossary('SPA')}} in application layer, router is a library
that decides what web page is presented by a given {{Glossary('URL')}}.
This middleware module is used for all URL functions, as these are given a
path to a file that is rendered to open the next page.</li>
>
> ⬇️ Suggested change
>
> - <li>For {{Glossary('SPA')}} in application layer, router is a library
that decides what web page is presented by a given {{Glossary('URL')}}.
This middleware module is used for all URL functions, as these are given a
path to a file that is rendered to open the next page.</li>
>
> + <li>For a {{Glossary('SPA', 'Single-page application' )}} in the
application layer, a router is a library that decides what web page is
presented by a given {{Glossary('URL')}}. This middleware module is used
for all URL functions, as these are given a path to a file that is rendered
to open the next page.</li>
>
> ________________________________
>
> In files/en-us/glossary/routers/index.html:
>
>>
>
> <ol>
>
> <li>For the network layer, the router is a networking device that decides
data {{Glossary('Packet')}}s directions. They are distributed by retailers
allowing user interaction to the internet.</li>
>
> <li>For {{Glossary('SPA')}} in application layer, router is a library
that decides what web page is presented by a given {{Glossary('URL')}}.
This middleware module is used for all URL functions, as these are given a
path to a file that is rendered to open the next page.</li>
>
> + <li>For {{Glossary('API')}} in a service layer, router is code that
parses a request and directs or routes the request to various handlers
within a program. The code usually accepts a response from the handler and
facilitates its return to the requester.</li>
>
> ⬇️ Suggested change
>
> - <li>For {{Glossary('API')}} in a service layer, router is code that
parses a request and directs or routes the request to various handlers
within a program. The code usually accepts a response from the handler and
facilitates its return to the requester.</li>
>
> + <li>In the implementation of an {{Glossary('API')}} in a service layer,
a router is a software component that parses a request and directs or
routes the request to various handlers within a program. The code usually
accepts a response from the handler and facilitates its return to the
requester.</li>
>
> ...looking at, say, https://expressjs.com/en/starter/basic-routing.html,
I wonder if it would be helpful to be more specific, like "a software
component that routes a client request to the appropriate handler" or
something like that. Or "a software component that determines the handler
that will be called when a client makes a request to a particular
endpoint". But maybe that's too specific.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci6.googleusercontent.com/proxy/s7FZdtV2XDpNYLQieOpiiwzvCdSwCa-9J1qnRwlT32zUB7t0sGKurhh6x3R92DDB0TSoN6ZtIM1DfQT48aT8rMhupmDu5pAbbk5kXrSlVK2r-tJLrumG_mAQXfS-qlKOwzGEkDTEGVtO2SPPcimySx82hj_cye-UL1NosKc18VcoK8VUCoOg1c_4dLI5u5lQZvZSVZS3zRPN40Qzi_9UgEWu5oHiMoS7tPW9fcRYWj-O6_oWOW91=s0-d-e1-ft#https://github.com/notifications/beacon/AUS76CATLU6MCSXIJIWD54DUFMO6VA5CNFSM5FFDKPOKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOFX7DIDY.gif
>

-- 
*Tyler Gillispie*
*Software Prog**ram Developer*
*Contractor with Technical Engineering Support Alliance, LLC*
*(TESA)*
*NOAA Fisheries, Northeast Fisheries Science Center*
Fishery Monitoring and Research Division

25 Bernard Saint Jean Drive

East Falmouth, MA 02536

2021-10-05 21:05 UTC, TGillispie commented on files/en-us/glossary/routers/index.html
> + <li>For {{Glossary('API')}} in a service layer, router is code that parses a request and directs or routes the request to various handlers within a program.  The code usually accepts a response from
I think your modification is great and I really like the first suggestion.
 "a software component that routes a client request to the appropriate
handler".  Mentioning "endpoint" might be too specific and a potential
cause for confusion. I request holds more than just an endpoint and each of
those parts could be used for routing.

Also, I think it might make sense to change "The code usually..." to "The
router code usually..."

2021-10-05 21:25 UTC, TGillispie commented on files/en-us/glossary/routers/index.html
> + <li>For {{Glossary('API')}} in a service layer, router is code that parses a request and directs or routes the request to various handlers within a program.  The code usually accepts a response from
I've tried to suggest a change.  Everything is "outdated" and I'm not sure how to suggest a change or add additional examples.

2021-10-05 23:39 UTC, wbamberg commented on files/en-us/glossary/routers/index.html
> + <li>For {{Glossary('API')}} in a service layer, router is code that parses a request and directs or routes the request to various handlers within a program.  The code usually accepts a response from
Can you suggest a change by clicking on the blue plus icon in https://github.com/mdn/content/pull/9424/files#diff-60233fed042a50d257069c8756268d3ae2130e386a9522503551f28ba876a2abR12 ?

2021-10-06 17:43 UTC, wbamberg approved these changes
Thanks for your contribution @TGillispie ! And it's great to know you're using MDN in NOAA!

(and yes, it can get pretty confusing. Please don't hesitate to ask if you want any help getting a contribution through.)

2021-10-06 17:43 UTC, merged