Replaced "the" article with "a". Replaced the past tense with the present tense.
mdn/content pull request #9481
Opened 2021-10-03 10:53 UTC by annakhyzhnya

Replaced "the" article with "a".
Replaced the past tense with the present tense.

#### Summary

#### Motivation

#### Supporting details

#### Related issues

#### Metadata

- [ ] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-03 11:10 UTC, teoli2003 requested changes
One change seems to modify the meaning a little bit; overall it is a good improvement!

2021-10-03 11:10 UTC, teoli2003 commented on files/en-us/web/http/headers/last-modified/index.md
> +as a validator to determine if a resource receives or stores the same. Less accurate
This seems to change a bit the meaning. What about
```suggestion
as a validator to determine if the resource is the same as the previously stored one. Less accurate
```

(Feel free to iterate here)

2021-10-03 12:29 UTC, annakhyzhnya commented on files/en-us/web/http/headers/last-modified/index.md
> +as a validator to determine if a resource receives or stores the same. Less accurate
yeap, I did not get the meaning. This one "as a validator to determine if the resource is the same as the previously stored one" is correct. Thanks)

2021-10-04 05:30 UTC, teoli2003 approved these changes

2021-10-04 05:31 UTC, merged

2021-10-04 05:31 UTC, teoli2003 commented
Thanks for the PR and your time yesterday! All fine!