Update execCommand index.md
mdn/content pull request #9505
Opened 2021-10-03 13:25 UTC by Eccenux

#### Summary

Not sure how to phrase it, but the page should say that execCommand is only partially deprecated. The command `insertText` was lately implemented in FF89 and is available in all other browsers (except IE).

Oh, I made a typo: programtially -> programmatically. But cannot edit the file again (at least in Github GUI, weird...)

As a side note: This new GUI for the MDN wiki is very weird. I'm an editor of Wikipedia from 16 years and of MDN probably 10 years... And this is confusing. No preview even and a lot of effort for fixing a typo or something.

#### Motivation

See: https://github.com/w3c/editing/issues/160#issuecomment-806165950

#### Supporting details

#### Related issues

Should probably also mention this in Compat.

#### Metadata

- [ ] Adds a new document
- [X] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-03 23:03 UTC, hamishwillee commented
FYI I fixed up "programmatically" and reworded this slightly to my taste. However leaving to @jpmedley or someone more expert to verify they are happy with the technical content change.

2021-11-24 05:23 UTC, wbamberg requested changes, later dismissed
Thanks for this PR, @Eccenux , and I'm sorry to take so long to review it.

 I had a few comments - mostly copy-edits and some comments on the example, which I would love to see converted into a live sample.

2021-11-24 05:23 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +    textarea.focus();
I think it would be better just to assume that the argument is a selector (or an element) so we can keep this example focused on the important stuff.

2021-11-24 05:23 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +insertText('<b></b>', '#someEditorTextarea');
I'm not sure why the example would insert `'<b></b>'` rather than something that would be visible.

2021-11-24 05:23 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +An example on how to insert text with both plain `textarea` and `contentEditable` elements:
Also I think this would work really well as a live sample. You could just have the textarea in the HTML section, and a button to call the function, then in the JS section have the function and a listener for the button click that calls the function.

2021-11-24 05:23 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +> **Note:** While this method is deprecated, it is still useful in some cases.
I don't think we should make this a note. We should just make it part of the page.

2021-11-24 05:23 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +> For example, the [Clipboard API](/en-US/docs/Web/API/Clipboard_API) doesn't replace `insertText` command.
"For example" is a bit strange here as it implies that there are lots of other cases where the Clipboard API isn't enough, but then we only talk about the insert text case. Are there other examples? If so it might be worth listing them, in case people encounter them. If not, we might say something less broad like:

>  While this method is deprecated, the `insertText` command can be used for programmatically replacing text at cursor while preserving the undo buffer (edit history) in plain `textarea` and `input` elements. The Clipboard API does not support this use case.

I think it might also be worth going into a bit more detail in this page about exactly why the clipboard API is inadequate here. I'm sorry if this seems obvious to you but I'm at least not very familiar with these usages and I expect a lot of other readers might not be, either.

2021-11-28 02:39 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +> For example, the [Clipboard API](/en-US/docs/Web/API/Clipboard_API) doesn't replace `insertText` command.
For example was mostly related to previous sentence. But you can find other examples in this report:  
w3c/editing#160

You can add other examples if you think this would be important. I simply believe that insertText is the most useful command  in practice as any textarea editor currently needs that. You can work around other missing commands (like undo/redo). You cannot insert tags in a  code editor in textarea without insertText.

> I think it might also be worth going into a bit more detail in this page about exactly why the clipboard API is inadequate here. I'm sorry if this seems obvious to you but I'm at least not very familiar with these usages and I expect a lot of other readers might not be, either.

The whole thing is only really needed because undo history was broken by browsers few years back. So now when you do input.value='abc' then the user is not able to undo that. Changing input.value used to work just fine and you didn't even need the . If you use execComand the operation can be undone.  
Amongst many other sites Wikipedia also suffers from this problem with undo buffer to this date [https://phabricator.wikimedia.org/T33780](https://phabricator.wikimedia.org/T33780)  (so when you write code, press bold you cannot undo this)

So yes, Clipoard API is not enough. That's why Mozill actually made this insertText work. If you are still not convinced with the w3c issue, then there are a lot more comments on the Mozill bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1220696

2021-11-28 02:40 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +> You can and should use it for programmatically replacing text at cursor in order to preserve the undo buffer (edit history) in plain `textarea` and `input` elements.
"can **and should**" was intentional here. There is no other way to do that. If you don't use execCommand you will cripple user experience.

2021-11-28 02:49 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +An example on how to insert text with both plain `textarea` and `contentEditable` elements:
Sure. I have no problems with that. You can use my code freely:  
https://jsbin.com/baxusiw/edit?html,js,console,output  
  
Same thing exported to Gist: [https://gist.github.com/Eccenux/4adb35f3a319c1df605690b2d6020e7a](https://gist.github.com/Eccenux/4adb35f3a319c1df605690b2d6020e7a)

2021-11-28 02:51 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +    var pasted = true;
When you use let there you remove IE compatibility. The code will just brake the editor.

2021-11-28 02:57 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +insertText('<b></b>', '#someEditorTextarea');
It does that because that is what bold button usually does. Add tags or other markup. You could implement moving the cursor inside tags or adding bold around selection... But that would make the code much more complicated.

2021-11-28 03:04 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +> **Note:** While this method is deprecated, it is still useful in some cases.
At the top the page is yelling at you that the feature is "**Deprecated**". So there should be a **Note** that makes it clear that the method is still useful, still in use and still supported.

2021-11-29 23:38 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +> You can and should use it for programmatically replacing text at cursor in order to preserve the undo buffer (edit history) in plain `textarea` and `input` elements.
It hardly seems worth arguing about, but "can and should" is redundant. If there were two ways to replace text while preserving undo history, and one was better, then "should" would be needed. Since it's not possible to preserve undo history any other way, "should" is not needed. There's only one way to do it.

2021-11-29 23:40 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +    var pasted = true;
We have a documented policy of using `let` and `const` in our examples: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#declaring_variables.

2021-11-29 23:44 UTC, wbamberg commented on files/en-us/web/api/document/execcommand/index.md
> +> **Note:** While this method is deprecated, it is still useful in some cases.
Please don't make this a note. The text is clear as it is.

2021-11-30 01:21 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +> You can and should use it for programmatically replacing text at cursor in order to preserve the undo buffer (edit history) in plain `textarea` and `input` elements.
Maybe I read too many rfc and w3c specs. For me "should" is a strong indicator of recommendation. But your are right - probably not worth to argue about that.

2021-11-30 01:36 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +> **Note:** While this method is deprecated, it is still useful in some cases.
I think this note about feature deprecation is misleading and another note is needed for balance. Currently you get confused devs. Like this for example:  
https://twitter.com/LeaVerou/status/1462122134256422913

2021-11-30 01:38 UTC, Eccenux commented on files/en-us/web/api/document/execcommand/index.md
> +    textarea.focus();
For the sake of simplicity I guess you can assume it would be an element.

2021-12-15 20:37 UTC, Eccenux commented
Is this still waiting on some more feedback from me? I don't know how your review process works.

2021-12-15 23:04 UTC, wbamberg commented
> Is this still waiting on some more feedback from me? I don't know how your review process works.

There are some comments that haven't been addressed.

* https://github.com/mdn/content/pull/9505#discussion_r755702122
* https://github.com/mdn/content/pull/9505#discussion_r755702616
* https://github.com/mdn/content/pull/9505#discussion_r755709457 (I know you don't agree with this one but I'd still like it made please)

2021-12-16 18:21 UTC, Eccenux commented
Sorry, but I don't really know how MDN's process work and unfortunately don't have time to find out... I did try to make changes to my branch before and I was not able to do them. Sorry, but this just doesn't feel like w "wiki" (fast) anymore. I don't mind if you add more info later, but I just wanted a few simple notes added (in accordance to changes in Firefox 89).

2021-12-16 18:34 UTC, wbamberg commented
OK, no worries @Eccenux ! If you don't mind, I can try to finish off this PR.

2021-12-20 23:28 UTC, wbamberg commented
I just pushed a commit that makes some copy-edits to the text and converts the example to a live sample, based on https://jsbin.com/baxusiw/edit?html,js,console,output.

@Elchi3 or @Rumyra  , would you mind having a look?

2021-12-22 13:47 UTC, Rumyra approved these changes
Yes this looks all fine to me 👍 I'll approve so you can merge, just in case anyone else wants to take a look

2021-12-22 18:28 UTC, wbamberg commented
Thanks Ruth, and thanks for all the work you've done on this @Eccenux !

2021-12-22 18:28 UTC, merged