FF94 : Updates to sanitizer API
mdn/content pull request #9579
Opened 2021-10-05 05:38 UTC by hamishwillee

This is part of update for FF94 in  #9366

The API has the following changes w.r.t. current docs (by inspection and testing)
- Sanitizer.getConfiguration()
- `Sanitizer.sanitizeToString()` method removed.
-  `Element.setHTML()` method added. 
- Some new configuration options, but these are still not actually supported anywhere. 

There is still a fair bit to do so putting in draft for now.

2021-10-05 05:39 UTC, hamishwillee commented on files/en-us/web/api/element/index.md
> +  - : Applies a string using a {{DOMxRef("Sanitizer")}} directly to an existing element node.
Will improve this text when I understand what it means.

2021-10-05 05:42 UTC, hamishwillee commented on files/en-us/web/api/html_sanitizer_api/index.md
> +        {{SpecName('HTML Sanitizer API','#sanitizer-api')}}
How do we currently do this for APIs - I can add the main classes but they don't link to the top of the spec as this link would.

2021-10-05 05:45 UTC, hamishwillee commented on files/en-us/web/api/html_sanitizer_api/index.md
> +This example shows the use of the {{domxref('Sanitizer.sanitize()')}} method.
Need to add example of `Element.setHTML` too. So far just removed the invalid `sanitizeToString()` example

2021-10-05 05:46 UTC, hamishwillee commented on files/en-us/web/api/sanitizer/sanitizer/index.md
> +        `true` ensures that comments are retained.
Confirming this with spec (i.e. that no actual sanitization can ever be needed of the comment text)

2021-10-05 05:47 UTC, hamishwillee commented on files/en-us/web/api/sanitizer/sanitizer/index.md
>  new Sanitizer().sanitizeToString("abc <script>alert(1)</script> def");
Will need to remove this example as it uses removed string: `sanitizeToString()` example

2021-10-22 01:48 UTC, hamishwillee commented
Can I please get a review on this next week?  Good to not have these things hanging on too long.

FYI @Rumyra this isn't urgent because the changes are behind a preference (i.e. not "shipped" in FF94). The API is still in flux - what this documents is the things that have been implemented - there are some bits still to come.

2021-10-22 15:08 UTC, Rumyra requested changes
Only a couple of minor things - thanks @hamishwillee this is awesome

2021-10-25 10:09 UTC, Rumyra approved these changes

2021-10-25 10:09 UTC, merged