add note about stopImmediatePropagation()
mdn/content pull request #9582
Opened 2021-10-05 08:36 UTC by mindplay-dk

#### Motivation

Describes another small caveat.

2021-10-05 14:36 UTC, jpmedley requested changes

2021-10-05 14:36 UTC, jpmedley commented on files/en-us/web/api/event/stoppropagation/index.md
> +prevent immediate propagation to other event-handlers - if you want to stop those,
```suggestion
prevent immediate propagation to other event-handlers. If you want to stop those,
```

2021-10-05 14:36 UTC, jpmedley commented on files/en-us/web/api/event/stoppropagation/index.md
> +see {{domxref("Event.stopImmediatePropagation", "stopImmediatePropagation()")}} method.
```suggestion
see {{domxref("Event.stopImmediatePropagation", "stopImmediatePropagation()")}.
```

2021-10-06 14:12 UTC, jpmedley approved these changes

2021-10-08 08:47 UTC, mindplay-dk commented
Ehm, I don't really know this syntax - I just copy/pasted some existing markup and modified the text... If it isn't correct, I don't really know how to correct it, sorry...

2021-10-08 13:44 UTC, jpmedley requested changes

2021-10-11 15:57 UTC, jpmedley approved these changes

2021-10-11 20:00 UTC, jpmedley requested changes
Apologies. I still left out a character when correcting the macro.

2021-10-13 13:49 UTC, jpmedley approved these changes

2021-10-13 13:49 UTC, merged