Add reference pages for IdleDetector().
mdn/content pull request #9661
Opened 2021-10-08 03:16 UTC by jpmedley

#### Summary
Reference for the Idle Detection API.

#### Motivation
This was enabled in Chrome in version 94.

#### Supporting details
https://www.chromestatus.com/feature/4590256452009984

#### Related issues
NA

#### Metadata

- [x] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-08 15:16 UTC, jpmedley commented
FYI, the failing test says, "error: Cannot read property 'length' of null". This looks like a script regression rather than a content problem. Can someone please help?

2021-10-15 16:53 UTC, Rumyra requested changes
Just a few minor things - I wonder if when the macro is fixed the tests will pass

2021-10-16 01:36 UTC, LorenzNickel requested changes

2021-10-26 12:48 UTC, Rumyra approved these changes

2021-10-26 12:48 UTC, merged