[Markdown][Add-ons] Make acknowledgements convertible as Markdown notes
mdn/content pull request #9845
Opened 2021-10-15 18:19 UTC by wbamberg

Part of https://github.com/mdn/content/issues/9842.

In Markdown notes have to start with **Note:**. Many of the notes in the add-ons docs are to acknowledge that the APIs are derived from Chrome APIs, and use **Acknowledgement** instead. This PR changes those cases to use **Note:** instead.

2021-10-16 05:49 UTC, teoli2003 requested changes
3 tiny changes and we are good to go!

2021-10-16 06:15 UTC, teoli2003 approved these changes

2021-10-16 06:15 UTC, merged

2021-10-16 15:59 UTC, rebloor commented
Did we have to include the colon after "note"? Mkes it look as though we weren't quite sure whether this is the title or not

2021-10-16 17:31 UTC, wbamberg commented
> Could we update this to make "Note:" prefix to the sentences starting "This API …".

You mean instead of:

```
<p><strong>Note:</strong></p>
<p>This API...
```

...have:

```
<p><strong>Note:</strong> This API...
```

?

2021-10-17 16:01 UTC, rebloor commented
@wbamberg That is my thinking