Adding a note about the option to return a Promise instead of using the sendResponse() function
mdn/content pull request #9918
Opened 2021-10-19 08:08 UTC by jobisoft

sendResponse() is deprecated

#### Summary

The sendResponse() function is deprecated and should no longer be used. This PR changes the used examples to return a Promise and shows the two possible ways to do it.

I removed usage of sendResponse() in the example and let the handler return a Promise. Once as being an async function and always returning a Promise, which is fine if only one such listener is registered, which is 99% use-case out there, but also pointing out how to do it if multiple listeners are used.

#### Motivation

I am the lead add-on reviewer for Thunderbird and I get sendResponse() in reviews a lot and developers pointed me to this page showing them the deprecated usage.

#### Metadata

- [ ] Adds a new document
- [x] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-19 17:44 UTC, jobisoft commented
I adjusted the title of the PR as requested.

2021-10-19 17:46 UTC, rebloor requested changes
Just a couple small things in the text, otherwise also waiting for a technical review

2021-10-19 20:23 UTC, rpl submitted a review, later dismissed
The "deprecation note" in the [runtime.onMessage API doc page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) was actually "deprecated" some time ago but we didn't remove it, apologies for the confusion.

The old standardization effort as part of which that sendResponse was meant to be deprecated didn't get to actually deprecate it (it has never been removed from the specs draft) and in the meantime a new community group has been created to work on specs related to the extension APIs.

I also quickly discussed about this PR with @Rob--W and we both agreed that we should:
- keep sendResponse in the example included in this page
- and instead remove only the deprecation warning still included in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage 

The motivations are the following ones:

- the support for returning a Promise from the runtime.onMessage listener is currently supported only in Firefox

- the promise-based API provided in Safari WebExtensions does not support that and only support that `sendResponse` parameter (and the same is likely true also in the promise-based APIs that Chrome did recently introduce, I haven't tried it explicitly but I'm sure that it does still support `sendResponse`).

- even in the webextension-polyfill project, which is explicitly called out as an example in the warning box currently part of runtime.onMessage, we have added the `sendResponse` parameter quite some time ago: https://github.com/mozilla/webextension-polyfill/pull/97

2021-10-21 15:09 UTC, rebloor approved these changes
Looks good to me

2021-10-24 16:43 UTC, merged