Remove redundant WebRTC tutorial
mdn/content pull request #997
Opened 2021-01-06 10:46 UTC by lolaodelola

These pages were duplicates so I've removed them.

2021-01-06 11:39 UTC, chrisdavidmills requested changes
Looking mostly good @lolaodelola ; just a small query for you to answer.

2021-01-06 11:39 UTC, chrisdavidmills commented on files/en-us/_wikihistory.json
>    "web-rtc-tutorial-landing/connecting_the_peers/Answering_a_Call": {
Shouldn't this entry be removed as well?

2021-01-06 13:30 UTC, lolaodelola commented on files/en-us/_wikihistory.json
>    "web-rtc-tutorial-landing/connecting_the_peers/Answering_a_Call": {
@chrisdavidmills I used the deletion command to reccursively remove the files, so that actual file isn't present in my directory structure. Is is safe for me to manually remove this line from `_wikihistory.json`?

2021-01-06 14:34 UTC, chrisdavidmills commented on files/en-us/_wikihistory.json
>    "web-rtc-tutorial-landing/connecting_the_peers/Answering_a_Call": {
Yes, I think so.

2021-01-07 12:47 UTC, lolaodelola commented
@chrisdavidmills is this okay now?

2021-01-07 13:28 UTC, chrisdavidmills approved these changes
Yup, looks great!

2021-01-07 13:28 UTC, merged