New Page: aria-current
mdn/content pull request #9996
Opened 2021-10-21 22:32 UTC by estelle

- [X] Adds a new document
- [ ] Rewrites (or significantly expands) a document
- [ ] Fixes a typo, bug, or other error

2021-10-21 23:20 UTC, estelle commented
Does aria-current and the target of the page (link example.com#someId) need a current? I don't think so, but figured I would ask. 

If :target is styled????

2021-10-23 00:15 UTC, LorenzNickel requested changes

2021-10-27 14:03 UTC, ericwbailey requested changes

2021-10-27 14:04 UTC, ericwbailey approved these changes

2021-10-27 14:05 UTC, merged